### PR TITLE
Add doc on ansible_version, fix #13204

### LINKED ISSUE #13204: Variable ansible_version Is not Documented
The variable `ansible_version` is not documented. You have to search the Google group or the GitHub issues to know about it.

### PR DESCRIPTION
**Pull request by mscherer**
##### Issue Type:
- Docs Pull Request

### CODE REVIEW

**Comment by jpic** [comment]
lgtm

**Comment by amenonsen** [comment]
Thanks, merged.

**Comment by bcoca** [comment]
ansible_version was added in 1.8, not 2.0

**Comment by jpic** [comment]
Good catch, thanks !

If you don't decide to revert it, PR #15021 fixes the version.

**Pull request merged**
