### PR TITLE
Extend YAML inventory script with _meta hostvars

### PR DESCRIPTION
**Pull request by jcassee**
Because hostvars are now returned when the `--list` option is used, the `--extra-vars` options makes no sense and is removed.
- A `--file` option is added to select the YAML inventory definition file. The default is still `hosts.yml` in the script directory.
- The `--list` option has become the default action.
- Output is sorted and indented for easy human consumption.

Because @jhoekx is the original author I would like to get his opinion about these changes too.

### CODE REVIEW

**Comment by jhoekx** [comment]
I never quite understood why you'd need extra-vars, but you could add additional variables with it. It does not look like it's replaced by --list, but I don't mind removing them.

The other changes look good to me as long as you've tested them :-)

**Comment by jcassee** [comment]
@jhoekx: no, `--extra-vars` has not made a return in the `--list` option because I could not find a nice way of applying extra variables against certain hosts.

**Comment by mpdehaan** [comment]
I'm also unclear why this takes a "-f" argument when the other inventory files don't, because Ansible wouldn't have a way to pass that file.

Given we have text based inventory and dynamic inventory sources, my general thought it we remove this from core and let it evolve as needed.

**Comment by jcassee** [comment]
The reason for using a script is to treat a static file as a dynamic inventory source. This makes it possible to make a dynamic inventory source based on the static inventory.

Let me give you my example: I have a Vagrantfile that I can use to bring up VMs for any of the hosts in my inventory. To make that work I have a dynamic inventory script that adds `ansible_ssh_host` and related variables to make it connect to the VMs instead of the real machines. This way I can test changes to a cluster of machines:

```
VAGRANT_HOSTS=machine1,machine2 vagrant up
```

It is easier to consume, adapt and output JSON than to parse the INI-style file. There is no inventory plugin that understands the plain inventory file, but we have one for YAML. Hence my use of this inventory script.

(The `-f` option is not used by Ansible directly of course but is useful for testing and when it is called by another script.)

**Pull request closed without merging**
