### PR TITLE
minor typo fix

### PR DESCRIPTION
**Pull request by richlv**
##### SUMMARY
minor typo fix

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_action

### CODE REVIEW

**Comment by rubentsirunyan** [comment]
Good one :)

**Comment by D3DeFi** [comment]
Hey guys,
@richlv thank you for improving our documentation! :)
@rubentsirunyan don't be afraid to use `shipit` or `LGTM`, especially if the PR is related to the module that you're a maintainer of 

shipit

**Comment by Akasurde** [comment]
@richlv Thanks for the contribution. @rubentsirunyan @D3DeFi Thanks for the review.

**Comment by rubentsirunyan** [comment]
@D3DeFi I didn't know I had permission for `shipit` :)

**Pull request merged**
