### PR TITLE
win_domain_user - Use guid if given to allow for special attribute changes such as samAccountName

### LINKED ISSUE #45298: error message returned when changing SamAccountName using win_domain_user
##### SUMMARY

The module can successfully change a user's SamAccountName, but it returns the error "Cannot find an object with identity: 'Bob Smith'..."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_domain_user

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/Users/me/ansible/ansible.cfg) = 10
HOST_KEY_CHECKING(/Users/me/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/me/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target is Windows Server 2012 R2 Datacenter running as Domain Controller. All Windows updates have been applied. Last Windows updates were dated Aug-16 2018.

##### STEPS TO REPRODUCE

Create a new user or update an existing user so that `name` and `SamAccountName` are not the same. For example, name could be "Bob Smith" and SamAccountName could be "bsmith".

```yaml
  - win_domain_user:
      attributes: 
        samAccountName: bsmith
      name: Bob Smith
```

##### EXPECTED RESULTS

Expect the user "Bob Smith" to have a new SamAccountName of "bsmith" and to receive a message that there was a successful change.

##### ACTUAL RESULTS

The change **does** occur. The user's SamAccountName is updated. But the module returns an error because the module attempts to retrieve all of the user's details at the end to return that data, but it uses the **old** SamAccountName to get the user:

```powershell
Get-ADUser -Identity $username -Properties * @extra_args
```

The PowerShell cmdlet `Get-ADUser` can retrieve a user by
* Distinguished Name
* objectGUID
* sAMAccountName
The only safe way to handle this is to determine the GUID of the user at the beginning of the module and use that for every subsequent `Get-ADUser` command as GUID is the only parameter than can never change.

```paste below
TASK [win_domain_user] **********************************************************************************************
task path: /Users/me/ansible/auslab-add-user.yml:49
Using module file /Users/me/.virtualenvs/win_ansible/lib/python2.7/site-packages/ansible/modules/windows/win_domain_user.ps1
<172.16.1.90> ESTABLISH WINRM CONNECTION FOR USER: adbindadminpriv on PORT 5986 TO 172.16.1.90
EXEC (via pipeline wrapper)
fatal: [172.16.1.90]: FAILED! => {
    "changed": true, 
    "msg": "Cannot find an object with identity: 'Bob Smith' under: 'DC=auslab,DC=company,DC=com'.", 
    "password_updated": false
}
```

### PR DESCRIPTION
**Pull request by ShachafGoldstein**
##### SUMMARY
Fixes: #45298

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_domain_user
win_domain_user.ps1

### CODE REVIEW

**Comment by ShachafGoldstein** [comment]
After merege I can write the patch for #44757
So when both name and guid are given, it will use `Rename-ADObject`

**Comment by jiuka** [comment]
Hi @ShachafGoldstein 

The `guid` parameter seems to only be used for the `$identity`. Why not call it `identity` and default it to `$name`? This would give us a parameter which is only used to identify/find the User by can be used to identify it either by DN, GUID, SID or SAM. This would be probably a nice and clean interface for the other win_domain_ models too.

Marius

**Comment by jborean93** [comment]
See https://github.com/ansible/ansible/pull/61594#issuecomment-531627483, sorry for the delay

**Comment by jborean93** [comment]
Superseded with https://github.com/ansible/ansible/pull/61594.

**Pull request closed without merging**
