### PR TITLE
Config 4

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

Moar docs, adding callbacks to 'configurable plugins'

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

config
##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Comment by alikins** [comment]
With generate_rst_plugins_config_4,  missing docs/metadata/errors it shows is at https://gist.github.com/alikins/bfe8a97e1de88b13e2635bbf277a8128  (mostly lookups, actions, terminal)

Though there are a couple of yaml load errors:

../../lib/ansible/plugins/lookup/cartesian.py
yaml error: 'dict' object has no attribute 'read'
returndocs={'_list': {'type': 'lists', 'description': ['list of lists composed of elements of the input lists']}}

../../lib/ansible/plugins/lookup/etcd.py:
yaml error: 'dict' object has no attribute 'read'
returndocs={'_raw': {'elements': 'strings', 'type': 'list', 'description': ['list of values associated with input keys']}}

**Comment by bcoca** [comment]
@alikins, lookups are still to be done, action are already documented as modules, terminal ... i had no plans on. Look at ansible-doc for the list of supported plugin types

**Comment by alikins** [comment]
Couple of other things I noticed:

lib/ansible/plugins/inventory/host_list.py: The DOCUMENTATION docstring is a raw (r'') string which seems to confuse docs generation with newlines.


Some of the rst is getting generating incorectly resulting in rst warnings. Some of these are likely template/plugin_formatter bugs, but many look like DOCUMENTATION string oddities.

```
/home/adrian/src/ansible/docs/docsite/rst/host_group_vars_plugin.rst:58: WARNING: Explicit markup ends without a blank line; unexpected unindent.
WARNING: /home/adrian/src/ansible/docs/docsite/rst/accelerate_plugin.rst:7: (ERROR/3) Error in "versionadded" directive:
1 argument(s) required, 0 supplied.

.. versionadded::
/home/adrian/src/ansible/docs/docsite/rst/advanced_host_list_plugin.rst:32: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/adrian/src/ansible/docs/docsite/rst/constructed_plugin.rst:113: WARNING: Block quote ends without a blank line; unexpected unindent.

/home/adrian/src/ansible/docs/docsite/rst/host_list_plugin.rst:35: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/adrian/src/ansible/docs/docsite/rst/ini_plugin.rst:33: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adrian/src/ansible/docs/docsite/rst/linear_plugin.rst:26: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adrian/src/ansible/docs/docsite/rst/local_plugin.rst:25: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adrian/src/ansible/docs/docsite/rst/logentries_plugin.rst:132: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/adrian/src/ansible/docs/docsite/rst/mongodb_plugin.rst:132: WARNING: Explicit markup ends without a blank line; unexpected unindent.
WARNING: /home/adrian/src/ansible/docs/docsite/rst/openstack_plugin.rst:7: (ERROR/3) Error in "versionadded" directive:
versionadded" directive:
1 argument(s) required, 0 supplied.
```

**Comment by bcoca** [comment]
@alikins you might need to namespace by plugin type as there can be collisions in names across diff plugin types

**Comment by abadger** [comment]
Merged to devel and cherry-picked for 2.4.0rc2

**Pull request merged**
