### PR TITLE
Add an isset("$var") function to only_if

### PR DESCRIPTION
**Pull request by dhozac**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good.   To be consistent with other function/variable usage in ansible, this should probably be "is_set".

I'll merge this once 0.8 starts

**Comment by mpdehaan** [comment]
merged, renamed to is_set

thanks!

**Comment by cyrusdavid** [comment]
Hi, is this in the documentation?

**Comment by jctanner** [comment]
@vohof doesn't appear to be. Please open a docs bug, or a pull request if you don't mind.

**Pull request merged**
