### PR TITLE
Add documentation for usage of encrypted postgresql passwords.

### PR DESCRIPTION
**Pull request by jinnko**
PostgreSQL requires the encrypted password is generated correctly.  Document how to generate this.

### CODE REVIEW

**Comment by jctanner** [comment]
@jinnko this patch breaks doc parsing for the module. Please revise ...

```
jtanner@u1304:~/ansible$ ansible-doc postgresql_user
Traceback (most recent call last):
  File "/home/jtanner/ansible/lib/ansible/utils/module_docs.py", line 48, in get_docstring
    doc = yaml.safe_load(child.value.s)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<string>", line 29, column 9:
          - "When passing an encrypted passw ... 
            ^
expected <block end>, but found '<scalar>'
  in "<string>", line 29, column 90:
     ... nerated with the format C('str("md5") + md5( password + username ... 
                                         ^
ERROR: module postgresql_user missing documentation (or could not parse documentation)
```

**Comment by jinnko** [comment]
@jctanner Fixed the parsing.  Brackets seem impossible to successfully escape within the C() construct so avoided that.

**Comment by jctanner** [comment]
@jinnko thank you!

**Comment by cajunken** [comment]
Can anyone tell me more about the encrypted postgres password choices?  I can't seem to get mine to work encrypted or decrypted.  Here's my play, I've guessed different values for encrypted to no avail:
postgresql_user: name={{ dbuser }} encrypted=true password={{ dbpassword }} role_attr_flags=CREATEDB,LOGIN,SUPERUSER

Can someone please tell me what I'm doing wrong here?  Thanks!

**Comment by jinnko** [comment]
@cajunken here's a working example task

```
- name: Create postgresql roles
  postgresql_user: 
    encrypted=yes
    name=replication
    password=md500bc5524ef0a0f6d24b5822bd5d5db4d
    role_attr_flags=INHERIT,LOGIN,NOCREATEDB,NOCREATEROLE,SUPERUSER
  sudo_user: postgres
```

Note that the password used here is the encrypted password.  From the docs:

```
When passing an encrypted password it must be generated with the format
'str["md5"] + md5[ password + username ]', resulting in a total of 35 characters.
An easy way to do this is: echo "md5`echo -n "verysecretpasswordJOE" | md5`"
```

Therefore the command to run in the terminal to use the password "secret" is:

```
echo "md5`echo -n "secretreplication" | md5`"
```

**Comment by jctanner** [comment]
@cajunken if you need assistance with module usage, please use irc or the mailing list rather than comments in a closed ticket.

**Pull request merged**
