### PR TITLE
Rename serange to selevel to be consistent with selinux docs

### PR DESCRIPTION
**Pull request by sfromm**

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged, can you give me an example command line execution for setting all of these so I can show it in the docs?

**Comment by sfromm** [comment]
Set the setype to some non-default value:

```
$ ansible test -i ../ansible-playbooks/ansible_hosts -m file -a "setype=default_t path=/etc/exports"
limbo | success >> {
    "changed": true, 
    "group": "root", 
    "mode": 420, 
    "path": "/etc/exports", 
    "secontext": "system_u:object_r:default_t:s0", 
    "state": "file", 
    "user": "root"
}
```

If I remove the setype option, it will revert to the default:

```
$ ansible test -i ../ansible-playbooks/ansible_hosts -m file -a "path=/etc/exports"
limbo | success >> {
    "changed": true, 
    "group": "root", 
    "mode": 420, 
    "path": "/etc/exports", 
    "secontext": "system_u:object_r:exports_t:s0", 
    "state": "file", 
    "user": "root"
}
```

Would it help if I included an example playbook that exercised these options, similar to user_commands.yml?

**Comment by mpdehaan** [comment]
probably good enough with your docs addition, may want to note that the "revert to default" behavior though, as I would expect that leaving it off would leave it as is instead.

Can it be made to do that, that would be more consistent w/ the remainder of how operations work?

leaving off the file mode will never change the mode back, etc

**Comment by sfromm** [comment]
Yes, I can change the file module so that if you drop an selinux option it doesn't revert the context to default.  

An explicit option that sets the file's context to the default from the policy (if available) would be nice to have.

**Comment by mpdehaan** [comment]
yeah, maybe just context=default could do the right thing ... I don't imagine anyone would ever choose to name a context 'default'.

Thanks!

**Pull request merged**
