### PR TITLE
azure module add support for storageProfile #58929

### LINKED ISSUE #58929: module azure_rm_postgresqlserver: support for storageProfile
##### SUMMARY
On Azure, when creating a managed Postgres server, the "[Backup redundancy options](https://docs.microsoft.com/en-us/azure/postgresql/concepts-backup)" need to be set during the creation. (even if it'sa part of the Update API, I tried, we cannot update it)

It would be nice to handle the SotrageProfile part. [See the doc here](https://docs.microsoft.com/en-us/rest/api/postgresql/servers/update#storageprofile)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_postgresqlserver

##### ADDITIONAL INFORMATION
Add backup redundancy flag

```yaml
- name: Create (or update) managed PostgreSQL server
  azure_rm_postgresqlserver:
    resource_group: "{{ resource_group }}"
    name: "{{ postgres_server_name }}"
    sku:
      name: GP_Gen5_2
    location: "{{ location }}"
    storage_mb: "{% if is_prod %}100000{% else %}5120{% endif %}"
    geo_redundant_backup: "{% if is_prod %}yes{% else %}no{% endif %}"
    enforce_ssl: yes
    admin_username: "{{ postgres_admin_username }}"
    admin_password: "my_password"
    version: "{{ postgres_server_version }}"
  tags: ["postgres"]
```

ping @zikalino

### PR DESCRIPTION
**Pull request by Sispheor**
##### SUMMARY
azure module add support for storageProfile for azure_rm_postgresqlserver

Fixes #58929

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
azure_rm_postgresqlserver

##### ADDITIONAL INFORMATION

- [Python SDK reference]( https://docs.microsoft.com/en-us/python/api/azure-mgmt-rdbms/azure.mgmt.rdbms.postgresql.models.storageprofile?view=azure-python)
- [Ansible issue reference](https://github.com/ansible/ansible/issues/58929)

### CODE REVIEW

**Comment by Sispheor** [comment]
ping @MyronFanQiu

**Comment by Fred-sun** [comment]
@Sispheor Thanks for your contribution. CI verify fail is related to C(geo_redundant_backup). Can you fix CI and move forward with the review. Thank you very much!

**Comment by Sispheor** [comment]
Hi @Fred-sun . I'm on it.
Do you know if API call are mocked during tests? The flag actually exists.

**Comment by Fred-sun** [comment]
@Sispheor I'm not sure about that.  But I will find out it! Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Do you know if API call are mocked during tests?

**Comment by Sispheor** [comment]
The error is "msg": "Error creating the PostgreSQL Server instance: Azure Error: GeoRedundantBackupNotSupported\nMessage: Geo-Redundant Backup is not supported"

Maybe the testing subscription is not allowed to activate geo redundant backup. I remove the flag from the test.

**Comment by Fred-sun** [comment]
Yes, remove the flag test pass!

**Comment by Sispheor** [comment]
@Fred-sun It's ok.

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@haiyuazhang @gavinfish review_need!

**Comment by Fred-sun** [comment]
Ping to review and meger!

**Comment by revolunet** [comment]
thanks, this allow to change the backup retention time which is quite critical :)

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@Sispheor Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by Akasurde** [comment]
Hi @Sispheor, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
