### PR TITLE
Remove needless get_next_task_for_host calls

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Called with `peek=True` and the return values are not used.

ci_complete

Introduced in https://github.com/ansible/ansible/commit/c669a381d117ccd96d4d59ab9191a107d08dfdb4
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/plugins/strategy/__init__.py`

### CODE REVIEW

**Review by Shrews — APPROVED** [review]
FWIW, I was not able to find a scenario where this would break anything. I tried testing with a playbook with multiple hosts that failed a `run_once` task to trigger this code, but I saw no breakage with various alterations to the test playbook.

**Comment by mkrizek** [comment]
For the record, there was a concern that removing those `get_next_task_for_host` calls may cause issues because `get_host_state` which is called from `get_next_task_for_host` contains a [side-effect](https://github.com/ansible/ansible/blob/68bdfd005200030ae9668d3a785ed9c10344bee6/lib/ansible/executor/play_iterator.py#L220-L224). Concerns about methods having side-effects in general aside, this should not be an issue here because `get_host_state` is called from `mark_host_failed` anyway.

**Comment by mkrizek** [comment]
rebuild_merge

**Comment by mkrizek** [comment]
bot_status

**Pull request merged**
