### PR TITLE
panos_restart

### PR DESCRIPTION
**Pull request by ivanbojer**
ISSUE TYPE

New Module Pull Request
COMPONENT NAME

panos_restart

ANSIBLE VERSION

ansible 2.1.0.0
config file =
configured module search path = Default w/o overrides
SUMMARY

New panos module that allows for remote restart of the PANW FW device

### CODE REVIEW

**Comment by ivanbojer** [comment]
Migrated from: https://github.com/ansible/ansible-modules-extras/pull/3386

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by privateip** [comment]
Overall looks good.  One minor change. Ansible 2.3 now requires a snippet of metadata for every new module.  Please add the following to your module and then it can be merged.

```
ANSIBLE_METADATA = {'status': ['preview'],
                    'supported_by': 'community',
                    'version': '1.0'}
```

Details on the usage of metadata can be found [here](https://github.com/ansible/proposals/issues/30) for the time being while documentation is still being updated.

**Comment by ivanbojer** [comment]
@privateip Thank you for the review. I've added latest METADATA requirements.

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by privateip** [comment]
thanks.. merged into devel

**Pull request merged**
