### PR TITLE
adding param to the ec2_vol module allowing custom iops setting when creating EBS volume

### PR DESCRIPTION
**Pull request by podollb**
adding param to allow for specifying custom iops setting when creating an EBS volume

### CODE REVIEW

**Comment by mpdehaan** [comment]
@lwade -- can you help review this one?

Thanks again!

**Comment by lwade** [comment]
This is just fine for inclusion, thanks! :)

**Comment by mpdehaan** [comment]
This is fine to merge, I noticed the "version_added" field was not in the YAML, so I will add that so it appears in the docs and users of 1.2.2 will not try to use it.

Will show up in next docs push.

Thank you for adding this and thanks @lwade for reviewing!

**Comment by podollb** [comment]
There is an additional requirement that maybe should be called out, and that is that the boto version needs to be somewhere around 2.7 or newer. The boto API I'm using is the method create_volume(self, size, zone, snapshot=None, volume_type=None, iops=None) that accepts 6 params. In in old versions of boto, the API only accepts 4 params.

**Comment by lwade** [comment]
Yup, this just needs to be clear in the docs.  If its a feature we want (which it probably is), then really we have no choice.

**Comment by lwade** [comment]
Actually, I might need to make an edit to this but its no problem.  We need to split the methods we use to create the volume. I'll open a new PR for this.

**Pull request merged**
