### PR TITLE
Added ability to create EBS volume based off of snapshot.

### PR DESCRIPTION
**Pull request by mlieberman85**
Changed the ec2_vol module so it allows for someone to use a snapshot.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you give an example for the documentation section?

Thanks!

**Comment by mpdehaan** [comment]
looks like volume_size or snapshot should be set to be mutually_exclusive (see module_common code for this capability)

**Comment by willthames** [comment]
This is similar to my #4508 but my understanding is that volume_size and snapshot are not mutually exclusive. 

http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-CreateVolume.html

This only says that size is not required if creating from a snapshot, but not that size cannot be passed in addition (this is one of the mechanisms for increasing the size of an EBS volume - take a snapshot, create a bigger volume based on it, and replace the old volume with the new volume)

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-expand-volume.html

**Comment by sritchie** [comment]
Are you guys planning on merging this in?

**Comment by jctanner** [comment]
@mlieberman85 closing this in favor of https://github.com/ansible/ansible/pull/4508

I did add your example in 1584d8f01b229fc9e1b3f85c6f3c014a36005141

**Pull request closed without merging**
