### PR TITLE
Documenting how to change VM's params

### PR DESCRIPTION
**Pull request by jtyr**
##### SUMMARY
I wanted to change params of one VM via `vmware_guest` module and it took me a while to find [this post](https://github.com/ansible/ansible/issues/27939) which actually helped me to do it. After this experience, I think it's a good idea to document it in the module documentation.

##### ISSUE TYPE
Docs Pull Request

##### COMPONENT NAME
`vmware_guest`

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Review by goneri — APPROVED** [review]

**Comment by angystardust** [comment]
I'm wondering if one have to poweroff the vm to increase the memory even when you have the memory hotplug enabled... :thinking:

**Comment by goneri** [comment]
> I'm wondering if one have to poweroff the vm to increase the memory even when you have the memory hotplug enabled... thinking

Yes, this is a good point @angystardust, thanks. @jtyr, could you please mention the purpose of `hotadd_memory`, `hotremove_memory` and `hotadd_cpu`.

**Review by goneri — CHANGES_REQUESTED** [review]
Thanks for the patch, could you please mention `hotadd_cpu`, `hotadd_memory` and `hotremove_memory`.

**Review by goneri — APPROVED** [review]

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @jtyr  for the Ansible documentation patch!

**Pull request merged**
