### PR TITLE
Scaleway inventory plugin: small improvements

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
Scaleway inventory plugin:
- ~~fix `AttributeError` (thanks to Frédéric Saumon for pointing that).~~ fixed in another PR
- mark `oauth_token` option as mandatory
- remove `print` statement
- mention exception in error message
- refactor: options don't need to be attributes

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
scaleway inventory plugin

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel dc7e50fa90) last updated 2018/06/18 11:23:09 (GMT +200)
```

### CODE REVIEW

**Comment by s-hertel** [comment]
Rebased after causing the conflict. From a code review, this looks good to me.

**Comment by remyleone** [comment]
LGTM as well.

**Comment by remyleone** [comment]
@pilou- I wanted to ask you, instead of having the id of the server as key, don't you think it would be a better idea to have a public DNS for the machine as the key? I'm not sure about how to handle the case for machines without public addresses. Could you give me a little bit of insight?

**Comment by remyleone** [comment]
@pilou- I started working on that in #41658 let me know what you think

**Comment by remyleone** [comment]
Should it be backported as well?

**Comment by pilou-** [comment]
Yes, `print` statement is a problem and its deletion should be backported, other changes are optional.
@s-hertel should I create a PR targeting `stable-2.6` with all these changes or only with https://github.com/ansible/ansible/pull/41642/commits/0908150b128d55527298fa5c7e2e68c7f8250e51 ?

**Comment by s-hertel** [comment]
@pilou- This looks safe to backport, I'd go for it. @mattclay is the release manager for 2.6. He might have an opinion.

**Comment by pilou-** [comment]
Here it is: #41733.

**Pull request merged**
