### PR TITLE
Disable PowerShell null comparison test.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Disable PowerShell null comparison test. Too many false positives due to unknown types.

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

ansible-test

##### ANSIBLE VERSION

```
ansible 2.6.0 (ps-null-check a8e6db8a61) last updated 2018/03/21 10:45:53 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

### CODE REVIEW

**Comment by mattclay** [comment]
@nitzmahone and I discussed this and agreed that although the test can catch legitimate issues, it's much more likely to have false positives due to the unknown types of module args.

**Comment by mattclay** [comment]
If the changes to Get-AnsibleParam in https://github.com/ansible/ansible/pull/37718 enable proper type detection during code analysis, then disabling this rule may not be needed.

**Comment by mattclay** [comment]
Marking this as WIP until we're sure it's needed.

**Comment by dagwieers** [comment]
So if I explicitly typecast a variable
```powershell
[string]$username = Get-AnsibleParam -obj $params -name "username" -type "str"
```
And then compare it to $null as we used to, it still complains about it. Which is the most basic thing that could have worked.

Surprisingly, if you do this:
```powershell
$username = (Get-AnsibleParam -obj $params -name "username" -type "str") -as [string]
```

it does work correctly, but it is not an option simply because we lost the $null value as we now have an empty string (unsurprisingly).

**Review by dagwieers — APPROVED** [review]
I prefer this PR over changing all the modules.

**Pull request merged**
