### PR TITLE
tags lists are properly uniqued and joined now

### LINKED ISSUE #6310: Tags in array cause traceback
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Debian Wheezy
##### Summary:

Bug seems similar to https://github.com/ansible/ansible/issues/4524
##### Actual Results:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 307, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 247, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 248, in run
    play = Play(self, play_ds, play_basedir, included_roles=included_roles, vault_password=self.vault_password)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 85, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 358, in _load_roles
    roles = self._build_role_dependencies(roles, [], self.vars)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 307, in _build_role_dependencies
    self._build_role_dependencies([dep], dep_stack, passed_vars=dep_vars, level=level+1)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 241, in _build_role_dependencies
    passed_vars['tags'] = __merge_tags(role_vars)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 239, in __merge_tags
    return list(set(old_tags + new_tags))
TypeError: cannot concatenate 'str' and 'list' objects
```

### PR DESCRIPTION
**Pull request by bcoca**
, also avoids type issues when passed as list/set or strings, fixes #6310

Signed-off-by: Brian Coca <briancoca+ansible@gmail.com>

### CODE REVIEW

**Comment by jctanner** [comment]
@jimi-c can you take a look at this?

**Comment by drybjed** [comment]
Ansible works correctly with above changes.

**Comment by bcoca** [comment]
probably also fixes #4524 new errors

**Comment by bcoca** [comment]
and probably also fixes #6310

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
