### PR TITLE
azure_rm_subnet: fix CI error for deleting the azure_tags

### PR DESCRIPTION
**Pull request by mmyyrroonn**
##### SUMMARY

There will be a CI error about the conflict between the code and the documentation due to the PR #55233

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure_rm_subnet

##### ADDITIONAL INFORMATION

```paste below
The PR #55233 delete the "azure_tags" in the documentation
```

### CODE REVIEW

**Comment by yuwzho** [comment]
shipit

**Comment by zikalino** [comment]
just wondering why ci didn't fail for #55233?

**Comment by MyronFanQiu** [comment]
> just wondering why ci didn't fail for #55233?
Maybe because it's a doc pull request? I don't know either. The CI failed in the other PR, thus I created this one.

**Comment by acozine** [comment]
I'm seeing a CI failure on #55602, which is the 2.8 backport PR for #55233. I'll open a backport for this PR and mark it docs so I can ride herd on it.

**Pull request merged**
