### PR TITLE
Added pip-python to the search for CentOS 6 compatibility

### PR DESCRIPTION
**Pull request by tonk**
This should solve #1667 once and for all.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks like this should continue to pass required=False to get_bin_path on the second invocation so it can still make it to the 3rd case.

**Comment by wzzrd** [comment]
I'm not behind a computer right note, but are you sure this is needed? I'm
pretty sure at least Fedora has both pip-python and python-pip...

**Comment by tonk** [comment]
Maybe Fedora, but my CentOS 6 doesn't.

@mpdehaan I agree, I'm not a real Python programmer, I'm just starting to learn.

Do you pull and fix or should I fix and resubmit a pull request?
What is your preferred procedure?

**Comment by mpdehaan** [comment]
it's all good.

I believe you can update the pull request, but submitting a new one is fine
too

see https://help.github.com/articles/using-pull-requests

"Pull requests can be sent from any branch or commit but it's recommended
that a topic branch be used so that follow-up commits can be pushed to
update the pull request if necessary."

**Comment by tonk** [comment]
The request is updated. It's the commit with hash 7bba04b (two posts above this one)

**Comment by mpdehaan** [comment]
merged in, thanks!

**Pull request merged**
