### PR TITLE
[stable-2.17] ansible-doc: correctly treat separate paragraphs in top-level descriptions as separate paragraphs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #83155 to stable-2.17.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

### CODE REVIEW

**Comment by webknjaz** [comment]
The RHEL failures are unrelated and at to be fixed separately.

**Comment by felixfontein** [comment]
@webknjaz @nitzmahone @mattclay thanks for reviewing and merging!

**Pull request merged**
