### PR TITLE
openssl_certificate_info: fix missing doc type

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fix missing doc type.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
openssl_certificate_info

### CODE REVIEW

**Comment by felixfontein** [comment]
There's currently a problem with the openSUSE servers, which causes the test failures.

**Comment by felixfontein** [comment]
The OpenSUSE problems have been resolved, tests run through now (here and other crypto PR).

**Comment by acozine** [comment]
Thanks @felixfontein - feel free to backport this if you'd like to see it in the latest docs.

**Comment by felixfontein** [comment]
@acozine thanks! will create a backport, though not today :)

**Pull request merged**
