### PR TITLE
Ensure that the script is run with elevated privileges

### LINKED ISSUE #20654: ConfigureRemotingForAnsible.ps1 fails if not run as local administrator
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ConfigureRemotingForAnsible.ps1
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 6673673042) last updated 2017/01/25 08:11:36 (GMT +100)
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

stock configuration
##### OS / ENVIRONMENT

controller: WSL (windows pretending to be Ubuntu 16.04)
target: Windows Server 2012 R2
##### SUMMARY

Now that ConfigureRemotingForAnsible.ps1 writes to the event log, it attempts to access the security log, but this is not available, if for example you are running as a domain administrator.
Typically ConfigureRemotingForAnsible.ps1 would be run as a local administrator, but there are occassions, such as when you wish to regenerate the self-signed certificate where it is useful to be able to run as a domain administrator.
##### STEPS TO REPRODUCE

connect to a server 2012 r2 machine via remote desktop as a domain administrator
download ConfigureRemotingForAnsible.ps1
wget https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -Output ConfigureRemotingForAnsible.ps1
attempt to run .\ConfigureRemotingForAnsible.psi1

```yaml

```

##### EXPECTED RESULTS

remoting to be set up
##### ACTUAL RESULTS

fails as security event log is not available 

```
sorry don't have exact output available at this time, will update if required.
```

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ConfigureRemotingForAnsible.ps1

##### ANSIBLE VERSION

v2.3

##### SUMMARY

This fixes #20654

### CODE REVIEW

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
@dagwieers This is failing CI on Windows Server 2008 R2 with the following error from the EC2 user-data execution:

```
2017-01-26T16:38:03.303Z: Ec2HandleUserData: Message: The errors from user scripts: Invoke-Expression : At line:1 char:11
+ #Requires -RunAsAdministrator
+           ~~~~~~~~~~~~~~~~~~~
Parameter RunAsAdministrator requires an argument.
At C:\Program Files\Amazon\Ec2ConfigService\Scripts\UserScript.ps1:34 char:1
+ Invoke-Expression $config_script
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseExcep 
   tion
    + FullyQualifiedErrorId : ParameterRequiresArgument,Microsoft.PowerShell.C 
   ommands.InvokeExpressionCommand
```

**Comment by dagwieers** [comment]
Very weird. It should not require an argument: https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Requires

And if it does on Windows Server 2008, Microsoft fucked up again. Sigh.

**Comment by mattclay** [comment]
@dagwieers The same error is occurring on the Windows Server 2008 AMI as well.

**Comment by mattclay** [comment]
@dagwieers I checked `help requires` for PS 3 and `-RunAsAdministrator` isn't documented as supported there.

**Comment by jhawkesworth** [comment]
last time I looked S2008R2 extended support ends Jan 2020, so I guess that means supporting PS3 for another 3 years :-(

**Comment by dagwieers** [comment]
@mattclay The whole point of doing #Requires was that it was backward compatible IMO (why else define it the same way as comments in Powershell instead of making it part of the language itself). And they broke that because it doesn't ignore what it does not understand apparently. Sigh. Oh well, I'll just do the same thing in Powershell, I just thought that this was more elegant and *the* way to do it.

**Comment by dagwieers** [comment]
Alright, let's see if this works :-)

**Comment by dagwieers** [comment]
Sigh, can someone relaunch ?

**Comment by dagwieers** [comment]
ready_for_review

**Comment by dagwieers** [comment]
@mattclay @jhawkesworth @nitzmahone @trondhindenes @JimFicarra Please review and test this.
I need two more shipits :-)

**Review by mattclay — APPROVED** [review]

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
