### PR TITLE
Add port argument for bigsuds

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

```
>= ansible 1.9.2
```
##### SUMMARY

This patch adds the port argument as a valid parameter to the f5_spec.

This argument is supported in bigsuds version 1.0.4 and greater, so
this patch uses the **version** variable of the bigsuds module to
determine when the port value should be honored by the module.

The rationale for this patch is that on some platforms that VEs are deployed to, a port-forwarding configuration may be set up where you would want to connect to the forwarded port because you are unable to connect to the true port.

For example, a Vagrant instance of BIG-IP may forward a port from 10443 to 443, and your ansible playbooks are on the host, so it would need to access the BIG-IP from https://localhost:10443

### CODE REVIEW

**Comment by caphrim007** [comment]
@mite can you look at this?

**Comment by caphrim007** [comment]
@mhite can you look at this?

**Comment by mhite** [comment]
I'm a little worried that you are doing exact string matches on version numbers. Would be nice if we presumed anything below 1.0.3 doesn't support port, and anything 1.0.4 and greater does. What do you think?

**Comment by caphrim007** [comment]
good point. lemme fix that

**Comment by caphrim007** [comment]
how about now. does >= 1.0.4 make more sense?

**Comment by mhite** [comment]
Yes, better! Hopefully using ASCII sort order string comparison won't present any gotchas. (I don't think it will.)

**Comment by mhite** [comment]
Actually, you'll need a different parameter name other than `port` as this is already used in various modules which leverage f5_argument_spec(). IE. bigip_pool_member, etc. Additionally, each module will need their `DOCUMENTATION =` section updated to reflect the new option. Messy :) but necessary once this is merged.

**Comment by caphrim007** [comment]
Suggestions on what it should be called?

**Comment by caphrim007** [comment]
bigip_port? I can update the documentation strings if this is merged

**Comment by mhite** [comment]
Since the BIG-IP host parameter is `server`, I'm thinking `server_port` is more appropriate -- and not taken by any of the BIG-IP modules themselves. (You can always have an alias, too, in the argument spec to allow for `bigip_port` also.)

Sound good?

**Comment by caphrim007** [comment]
Works for me! Lemme update the pr

**Comment by caphrim007** [comment]
@mhite updated PR. also, I forgot to add it to the values returned by f5_argument_spec so I added that too.

**Comment by mhite** [comment]
I think I uncovered a bigger issue, unfortunately. There was an old PR that move some of the common setup logic (well, mostly) into `ansible/lib/ansible/module_utils/f5.py`. When you changed `f5_parse_arguments` in that file, it basically impacted all F5 modules:

```
return (module.params['server'],module.params['user'],module.params['password'],module.params['state'],module.params['partition'],module.params['validate_certs'],module.params['server_port'])
```

Notice all the modules this unpack them:

```
$ grep f5_parse_arguments *
bigip_monitor_http.py:    (server,user,password,state,partition,validate_certs) = f5_parse_arguments(module)
bigip_monitor_tcp.py:    (server,user,password,state,partition,validate_certs) = f5_parse_arguments(module)
bigip_node.py:    (server,user,password,state,partition,validate_certs) = f5_parse_arguments(module)
bigip_pool.py:    (server,user,password,state,partition,validate_certs) = f5_parse_arguments(module)
bigip_pool_member.py:    (server,user,password,state,partition,validate_certs) = f5_parse_arguments(module)
bigip_virtual_server.py:    (server,user,password,state,partition,validate_certs) = f5_parse_arguments(module)
```

So basically all those have to also be updated in unison or else all the modules with throw `ValueError` when you try to run them.

`ValueError: too many values to unpack`

This brings up something I don't like which is the helper utility file is not in -extras, but in the normal ansible repo, so rev'ing them together is not possible AFAIK. I kind of hate that. Also, the bigip_facts module doesn't use this helper, so it's an outlier.

So sorry you kicked over a rock, but this brings up the bigger issue of how to best deal with fixing this issue long term. ;( Any thoughts?

**Comment by caphrim007** [comment]
touche`

I think this is more of a fundamental problem with the way that the different modules receive the parameters given. By unpacking those arguments as they do, that function blocks the future expansion of common variables that can be added....sorta.

We cannot change the underlying data without affecting all of the modules that use it. A more appropriate return value may be something like a dict or plain object that itself is populated by the module.param.get method.

I see that we also fail in the parse method if bigsuds is not found which, as mentioned offline, is going to not work when only a REST approach is used

So lemme add a workaround that takes both your comments into account and I'll post an updated PR! Thanks for the fantastic testing!

**Comment by mhite** [comment]
I have a few thoughts on addressing this long term:
- Can the common library live in extras, and not the main repo? [I don't think so, but I'm not sure.]
- Can we just coordinate this update along with all the necessary module updates?
- If we are going to do that, perhaps we should revisit the data structure returned to be more 'update' friendly. IE. Have it return a dictionary or object container.

**Comment by caphrim007** [comment]
1. I dont think it can live in extras because it is in module_utils, and that is not an extras "thing"
2. We could, as long as all the changes land in a single release. If we include an interim set of conditional code to check, then we can have separate PRs that address each change without needing to get all the changes in a single PR.
3. Lemme update this PR with a more flexible data structure for you to review.

**Comment by mhite** [comment]
It would actually be great to NOT have the included library outside extras. It seems to make things unnecessarily hard. @bcoca is this possible?

**Comment by caphrim007** [comment]
actually, the bigip_facts module is close enough to how I was going to suggest it be done that why dont i just make PR's for the other modules to have them look like bigip_facts?

f5_parse_arguments cannot be used for REST related work, so I would need to use a different check instead of bigsuds_found. So if I change the existing modules, I would extract that and the ssl context check is already handled by bigip_api

**Comment by bcoca** [comment]
@mhite, not yet, we are looking at options to 'decouple' this better, but there are issues as most shared code is used across core and extras and would create duplication.

**Comment by bcoca** [comment]
for now, just create 2 PRs and make sure they are linked and we'll do the merges as close to each other as possible (make sure link and warning about dependency is on the top of each one).

**Comment by caphrim007** [comment]
thanks for the info @bcoca

**Comment by mhite** [comment]
@caphrim007 -- Now that the changes have been merged for all the various modules in ansible-modules-extras/#2054, it should be safe to merge this. Agree?

 https://github.com/ansible/ansible-modules-extras/pull/2054

**Comment by mhite** [comment]
@caphrim007 -- Now that the unpacking behavior has been changed in https://github.com/ansible/ansible-modules-extras/pull/2102, we should be good to merge this. Agree?

**Comment by caphrim007** [comment]
i suspect yes, but we should run the modules through a test run first, "just in case"

**Comment by mhite** [comment]
Good point. I'll run it through the test suite.

**Comment by mhite** [comment]
I ran it through the test suite; it didn't introduce any regression. However, I didn't do any specific testing of the new feature itself since all my F5's run on standard 443. I did notice this when peaking at the code:

```
server_port = dict(default='443', required=False),
```

You probably actually want:

```
server_port = dict(type='int', default=443, required=False),
```

**Comment by caphrim007** [comment]
@mhite addressed your comment

**Comment by mhite** [comment]
Looks good. Gave it another test to check for regression. No issue. 

Not really sure what's up with the Travis CI build failure. Presuming that's something else unrelated to this change, I'd say...

shipit

**Comment by mhite** [comment]
Also, once this gets merged, we need to update the doc string on all the modules impacted to mention the new server_port parameter.

**Comment by caphrim007** [comment]
@mhite the build failed because of a url timeout. re-triggering travis to try again.

**Comment by caphrim007** [comment]
@gregdek tried to re-run travis several times, but the build doesnt seem to pass (not due to this patch). Will this prevent the merge from happening?

**Comment by gregdek** [comment]
@caphrim007 unclear to me; I'm not involved in the PR process for ansible/ansible repo. @bcoca?

**Comment by jctanner** [comment]
+1

**Pull request merged**
