### PR TITLE
Backport/2.7/52166

### PR DESCRIPTION
**Pull request by rockandska**
* Fix rabbitmq_plugin idempotence due to information message in new version of rabbitmq (https://github.com/ansible/ansible/pull/52166)  

cherry pick from 540b07b

### CODE REVIEW

**Comment by rockandska** [comment]
Sorry for the disturbance with this backport and the force push, forgot to increase `merge.renamelimit` who cause some unwanted behaviour.

**Comment by jgkirschbaum** [comment]
Seems ok for me.

**Review by jgkirschbaum — APPROVED** [review]
Seems good to me.

**Comment by abadger** [comment]
Merged for the 2.7.9 release.

**Pull request merged**
