### PR TITLE
Networking Docs - Added platform guides for EXOS and SLX-OS

### PR DESCRIPTION
**Pull request by LindsayHill**
##### SUMMARY
New networking platform guides for Extreme EXOS and SLX-OS

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
slxos_command
exos_command
##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (nos_facts b0b79d9335) last updated 2018/07/19 19:21:06 (GMT -700)
  config file = /home/extreme/.ansible.cfg
  configured module search path = [u'/home/extreme/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/extreme/ansible/lib/ansible
  executable location = /home/extreme/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

EXOS and SLX-OS modules were added to Ansible 2.6. 

They only support `network_cli` today.

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by LindsayHill** [comment]
Fixed conflict that arose due to Extreme Ironware changes getting merged

**Comment by LindsayHill** [comment]
Rebased again, to incorporate https://github.com/ansible/ansible/pull/41155 changes for MikroTik

**Comment by gundalow** [comment]
@LindsayHill Yay for docs. Is it correct that this will need to go into `devel` *and* `stable-2.6`?

**Comment by LindsayHill** [comment]
I guess it does apply to both `devel` and 2.6 branches, since the code is already there in 2.6. 

Not too fussed if it gets cherry picked or not.

**Review by samccann — APPROVED** [review]

**Comment by gundalow** [comment]
@samccann could we please backport this to 2.6?

**Comment by samccann** [comment]
@gundalow done by https://github.com/ansible/ansible/pull/43513.

**Pull request merged**
