### PR TITLE
docker_* modules: add docker module defaults group

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Similar to #62719, adds a module defaults group `docker` for the `docker_*` modules (except `docker_stack`).

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
docker_compose
docker_config
docker_container_info
docker_container
docker_host_info
docker_image_info
docker_image
docker_login
docker_network_info
docker_network
docker_node_info
docker_node
docker_prune
docker_secret
docker_service
docker_swarm_info
docker_swarm
docker_swarm_service_info
docker_volume_info
docker_volume

### CODE REVIEW

**Comment by felixfontein** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @danihodovic @dariko @hannseman @jwitko @kassiansun @sluther @tbouvet

**Comment by felixfontein** [comment]
With #63171 merged, the tests should now pass.

**Comment by Andersson007** [comment]
passed ! :)

**Comment by felixfontein** [comment]
The result looks as follows:
module-defaults

**Comment by acozine** [comment]
Thanks @felixfontein!

**Comment by felixfontein** [comment]
@Andersson007 @acozine thanks for helping with this!

**Pull request merged**
