### PR TITLE
[cloud] Don't assume a non-AWS S3 url is Walrus

### PR DESCRIPTION
**Pull request by florv**
##### SUMMARY

Currently Ansible assumes that if an S3 URL is not Amazon AWS then it is a Walrus instance and enables quirks specific to Walrus by calling `connect_walrus()` provided by boto.

The Walrus quirks prevents the s3_bucket module from connecting to other
implementations of S3 like Pithos. This pull request adds the "walrus" option which allows the user to enable those quirks when needed.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
s3_bucket

##### ANSIBLE VERSION
```
ansible 2.4.0 (s3_bucket 3ce7cdc319) last updated 2018/01/15 14:53:04 (GMT +200)
  config file = 
  configured module search path = [u'$HOME/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/src/ansible/lib/ansible
  executable location = $HOME/src/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

### CODE REVIEW

**Comment by sivel** [comment]
This looks like a backwards incompatible change.  Perhaps `walrus` should default to `True`

**Comment by florv** [comment]
ready_for_review

I changed the default value to make it backward compatible and edited the documentation accordingly.

**Comment by florv** [comment]
What's the status of this PR? Is there something left to do for it to be merged? I haven't seen any feedback the last couple of months or so.

I'm waiting on a reply, thank you.

**Comment by willthames** [comment]
@florv looks like we're planning to move s3_bucket to boto3 - can you have a look at #37189 and see if it makes things better or worse for walrus before we migrate?

**Comment by s-hertel** [comment]
Hi, @florv. It looks like this was fixed in cfe7c9606c6fd628388aecc32127737d35c60877. Please let me know if that didn't resolve the issue!

**Pull request closed without merging**
