### PR TITLE
allow use of os-client-config environment variable to configure the plugin

### LINKED ISSUE #50243: OpenStack inventory plugin should respect OS_CLOUD
##### SUMMARY

The OpenStack inventory plugin does not use the `OS_CLOUD` environment variable like the OpenStack CLI tools and the older inventory script.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

* lib/ansible/plugins/inventory/openstack.py

##### ADDITIONAL INFORMATION

I'm transitioning from using the OpenStack inventory script to the plugin. I have a clouds.yaml with multiple clouds, and have been using `export OS_CLOUD` to limit which one is used. However, the environment variable isn't read by the plugin.

I'm aware of the `only_clouds` parameter, but I think the environment variable could be used as well. I was planning on giving other users the same `openstack.yml` inventory file, who may or may not have the same clouds in the `clouds.yaml`.

### PR DESCRIPTION
**Pull request by dariko**
##### SUMMARY
Currently the `openstack` inventory plugin can only be configured referencing a `clouds.yaml` file, making it cumbersome to use when the other tools used (including the `os_*` modules) allow for the configuration to be given using environment variables.

This PR introduces a new parameter `use_os_client_config` is introduced. When set to `true`, this parameter disables the custom cloud configuration logic and delegates the authentication  to the [os-client-config](https://docs.openstack.org/os-client-config/latest/user/configuration.html) library.

I think delegating the authentication to the `os-client-config` library should be the default, but I left the `use_or_client_config` defaulting to `false` to maintain backward compatibility.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openstack

##### ADDITIONAL INFORMATION
Fixes #50243

### CODE REVIEW

**Review by cloudnull — APPROVED** [review]
this looks great! :+1:

**Comment by cloudnull** [comment]
shipit

**Comment by dariko** [comment]
@cloudnull Hi, any news on this?

**Review by cloudnull — CHANGES_REQUESTED** [review]
looks like there's a merge conflict. Once that's resolved we can get this shipped.

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by Akasurde** [comment]
@dariko Thanks for the contribution. Closing as per above.

**Pull request closed without merging**
