### PR TITLE
Azure acs module (azure_rm_acs)

### PR DESCRIPTION
**Pull request by julienstroheker**
##### SUMMARY

- Adding the the azure_rm_acs module

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- azure_rm_acs.py
##### ANSIBLE VERSION

```
ansible 2.4.0 (az-acs e37e15468b) last updated 2017/08/18 00:14:15 (GMT +000)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible/lib/ansible
  executable location = /app/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

TO DO before the merge : 
- [X] Clean the logs call
- [X] Add docstring and comments some decision in the code
- [X] Improve Int. Tests
- [X] Lint

### CODE REVIEW

**Comment by julienstroheker** [comment]
I have the following error in the ci : 
```
 "msg": "Error creating the ACS instance: Azure Error: MissingSubscriptionRegistration\nMessage: The subscription is not registered to use namespace 'Microsoft.ContainerService'. See https://aka.ms/rps-not-found for how to register subscriptions."
```

Let me know if you want me to hide my int. tests for now or if you can add the rights to use this provider ?

Thanks

**Comment by julienstroheker** [comment]
Removing the WIP. 
Module done.

**Comment by trstringer** [comment]
@mattclay can you run `az provider register -n Microsoft.ContainerService` on this subscription?

**Comment by trstringer** [comment]
This looks good to me.

shipit (after passing CI)

**Comment by mattclay** [comment]
@tstringer The subscription has been updated. This PR needs to be updated due to merge conflicts. Once that's done CI will be re-run.

**Comment by julienstroheker** [comment]
Will reopen a clean one, sorry about that

**Comment by dagwieers** [comment]
@julienstroheker You can still fix the original branch and force-push to it. No need to close and open a new PR.

**Pull request closed without merging**
