### PR TITLE
Meraki utility now loads() JSON

### PR DESCRIPTION
**Pull request by kbreit**
##### SUMMARY
Meraki utility now `loads()` using the JSON module. Modules were modified to account for these changes.
Additional bugs were fixed in the code.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
meraki module utility

##### ANSIBLE VERSION
```
ansible 2.7.0dev0 (meraki/util_request_jsonify 182979ffc4) last updated 2018/05/29 20:06:47 (GMT -500)
  config file = None
  configured module search path = ['/Users/kbreit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kbreit/Documents/Programming/ansible/lib/ansible
  executable location = /Users/kbreit/Documents/Programming/ansible/bin/ansible
  python version = 3.5.4 (default, Feb 25 2018, 14:56:02) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### Additional Information
This should also be backported to 2.6.

### CODE REVIEW

**Comment by kbreit** [comment]
shipit

**Comment by kbreit** [comment]
shipit

**Comment by dagwieers** [comment]
bot_status

**Comment by dagwieers** [comment]
bot_status

**Comment by kbreit** [comment]
shipit

**Comment by dagwieers** [comment]
We can wait for ansibot in vain, or just do it :-/

**Pull request merged**
