### PR TITLE
module_utils/network/cloudengine/ce:   add a util function to ce.

### PR DESCRIPTION
**Pull request by yuandongx**
##### SUMMARY

module_utils/network/cloudengine/ce:   add a util function to ce.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/network/cloudengine/ce.py
##### ADDITIONAL INFORMATION

'get_config' The second time the configuration is retrieved from the cache.
It will get the same configuration with first time  once more.
So I want to add anthoer method.

```paste below

```

### CODE REVIEW

**Comment by hwDCN** [comment]
bot_status

**Comment by hwDCN** [comment]
shipit

**Comment by hwDCN** [comment]
bot_status

**Comment by xuxiaowei0512** [comment]
bot_status

**Pull request closed without merging**
