### PR TITLE
ansible-test - fix coverage for test modules

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Fixes the coverage path translation for modules located in integration test paths. Instead of trying to match by the unique temporary path name that the module is executed as, the reporting tool will translate it to the static path that the module is actually located under.

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Review by mattclay — APPROVED** [review]
This looks good. I spotted a few issues while testing it, but I don't think they're related to these changes. I'll look into them more in January.

**Comment by jborean93** [comment]
Backport PRs

+ stable-2.16 - https://github.com/ansible/ansible/pull/84399
+ stable-2.17 - https://github.com/ansible/ansible/pull/84400
+ stable-2.18 - https://github.com/ansible/ansible/pull/84401

**Pull request merged**
