### PR TITLE
[WIP] Fixed multibyte character handling issue with py27 for tower_job_wait

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY
- Fixed multibyte character handling issue for tower_job_wait module for issue  #55585
- Added multibyte hostname handling test as an integration test

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- tower_job_wait module

##### ADDITIONAL INFORMATION
- The original issue is here #55585

### CODE REVIEW

**Comment by saito-hideki** [comment]
Re-run shippable CI

**Comment by AlanCoding** [comment]
The test failure is from

> The Tower server sent back a server error. Please try again later.

This isn't a problem with either your fix or the CLI library. I don't know what's going on with the target Tower instance (but trying again later will not help).

This PR look good to me. Maybe the server bug needs to be side stepped for now somehow.

**Comment by saito-hideki** [comment]
@AlanCoding Thank you for the review! :)
Is there anything I can do to solve this CI issue ?

**Comment by AlanCoding** [comment]
We should upgrade testing Tower server, that's the only thought I have on it right now.

**Comment by AlanCoding** [comment]
Migrating your PR here https://github.com/ansible/awx/pull/5170

close_me

**Pull request closed without merging**
