### PR TITLE
Bug Fix: Portset did not allow you to add port when creating a portset

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Portset did not allow you to add port when creating a portset

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
- na_ontap_portset.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by thedoubl3j — APPROVED** [review]
looks good to me. bug fix and also updated the related test.

**Review by lonico — APPROVED** [review]
shipit

**Comment by thedoubl3j** [comment]
merging, shipit from maintainers @lonico and PR opened by maintainer @carchi8py

**Comment by carchi8py** [comment]
@thedoubl3j is it possible to backport this change to 2.8.*?

**Pull request merged**
