### PR TITLE
add a module for creating annotations for the librato metrics service.

### PR DESCRIPTION
**Pull request by Sedward**
This is a service that we use called Librato. This module is similar to the datadog_event. It allows us to put annotations on our metrics timelines during deployment. Let me know if there are corrections that need to be made.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for the submission!

@elee -- we really don't want super-long list comprehensions like that :)

**Comment by Sedward** [comment]
@mpdehaan I just noticed I've got some leftover cruft on lines 125 and 155. I can remove those lines are push again.

**Comment by mpdehaan** [comment]
Yeah if you can update that that would be great, thanks!

One of our devs uses librato and is looking forward to this one!

**Comment by mpdehaan** [comment]
merged, thank you.  I fixed some things in the docs section, let me know if you would like to make upgrades by sending in a pull request and I'll get it merged quickly.

I also added a missing GPLv3 license header (C) to you, if this is a problem, let us know, though it's the assumed standard for new modules.

Thanks!

**Comment by Sedward** [comment]
No problem. Thanks!

**Pull request closed without merging**
