### PR TITLE
GreyNoise module

### PR DESCRIPTION
**Pull request by shortstack**
GreyNoise modules for interacting with the GreyNoise API

##### SUMMARY
There is 1 new module for interacting with the [GreyNoise API](https://github.com/GreyNoise-Intelligence/api.greynoise.io), which has made consuming data coming back from GreyNoise API more simplified, allows for parsing/filtering.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- greynoise

### CODE REVIEW

**Comment by shortstack** [comment]
specifically, we will be able to use this in parts of our CI processes that hook into elastalert and the hive. as for general use, i've found it to be helpful when querying the API this way and being able to filter/parse as needed, vs just curling or having to use a web UI.

**Comment by shortstack** [comment]
hi,

requesting this be looked at again :) we would love to have this added. it is helpful in lookup tables and other repetitive queries against the GreyNoise API.

**Comment by jpmens** [comment]
I assume this is a prime candidate for Ansible's new [content collections](https://www.ansible.com/blog/getting-started-with-ansible-collections) :)

**Comment by jpmens** [comment]
[This URL](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html) is likely more informative

**Pull request closed without merging**
