### PR TITLE
Extend find to filter by ownership

### LINKED ISSUE #63526: find_module: find files based on ownership
##### SUMMARY
Find files based on ownership.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
find

##### ADDITIONAL INFORMATION
To fix ownership of files, you currently have to find files, then use the file module to update them, but as the find module does not allow to search on ownership, you have to update them all, every time.

Current implementation:
```
- name: Find existing log files
  find:
    paths: "{{ monitoring_log_path }}"
    patterns: '*.log'
  register: log_files
  become: yes

- name: Change existing log files permissions
  file:
    path: '{{ item.path }}'
    state: file
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0640
  with_items: '{{ log_files.files }}'
  when: log_files.files is defined
  become: yes
```
Expected find task implementation:
```
- name: Find existing log files
  find:
    paths: "{{ monitoring_log_path }}"
    owner: not {{ user }}
    group: not {{ group }}
    patterns: '*.log'
  register: log_files
  become: yes
```

### PR DESCRIPTION
**Pull request by pfac**
##### SUMMARY
Extends the find module to filter files by owner and group, using either the name or the respective identifier.

Resolves #63526

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Module find.

##### ADDITIONAL INFORMATION
When attempting to fix ownership of files, since the find module does not allow finding files with a specific ownership, it is required to update all files.

See #63526 for the original idea.

### CODE REVIEW

**Review by Akasurde — CHANGES_REQUESTED** [review]
Could you please add test for this change ? Thanks.

**Comment by Akasurde** [comment]
Similar to https://github.com/ansible/ansible/pull/39549

**Comment by pfac** [comment]
Added tests and fixed issues revealed. Thanks for the heads-up, I failed to find these tests before, so I assumed there weren't any.

**Comment by pfac** [comment]
I'm giving up since this is not going anywhere. Let me know if anything changes.

**Pull request closed without merging**
