### PR TITLE
zabbix: add validate certs

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

Adding the `validate_certs` option to disable certificate checking when using self signed certificates.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
zabbix_host
zabbix_group
zabbix_hostmacro
zabbix_maintenance
zabbix_screen

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION

Adding the `validate_certs` option to disable certificate checking when using self signed certificates.

### CODE REVIEW

**Comment by eikef** [comment]
shipit

**Comment by eikef** [comment]
(already discussed in #24595, this is the same PR but rebased)

**Comment by D3DeFi** [comment]
shipit

**Comment by resmo** [comment]
needs_revision

The `validate_certs` is a new param and so a `version_added` needs to be added to the docs. The doc fragments `validate_certs.py` does not allow to add a `version_added` because it can potentially used in other modules. 

I would suggest to add a doc fragment for zabbix modules where the common docs are shared including `validate_certs`having a version_added.

**Comment by dj-wasabi** [comment]
So if I understand this correctly to get this merged, I'll have create a new file in module_docs_fragments and place the documentation that is shared between all the zabbix moldules in this file?

**Comment by resmo** [comment]
yes, because new params has to be versioned per module and the new param validate_certs added in 2.5 only applies to the zabbix modules.

Other shared docs between zabbix modules can also be added later to this doc fragment.

**Comment by eikef** [comment]
So basically, renaming validate_certs.py in the module_docs_fragment to zabbix.py, adding a version_added to it, and referencing the zabbix.py doc-fragment instead of validate_certs should be enough for this PR. You do not need to move the existing documentation in other modules that may be shared if you do not want to -- once this PR is in I can do a PR for that maintenance work :)

**Comment by resmo** [comment]
shipit

**Comment by resmo** [comment]
Thanks!

**Comment by dj-wasabi** [comment]
Thank you!

**Pull request merged**
