### PR TITLE
2.8: Clear 'connection related' plugin vars for next loop iteration (#59024)

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Backport of https://github.com/ansible/ansible/pull/59024

(cherry picked from commit a752e2a4670f3b87a570f03d9b2719f8412ad575)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/executor/task_executor.py`

### CODE REVIEW

**Comment by abadger** [comment]
Merged for the 2.8.3 release.

**Comment by abadger** [comment]
I was asked to revert this for now as it causes a different set of regressions from the 2.8.2 release. https://app.shippable.com/github/ansible/ansible/runs/133206/41/tests  @jborean93 is looking into a fix that won't cause new issues to crop up.  This will not make the 2.8.3 release.

**Comment by abadger** [comment]
Reverted here: https://github.com/ansible/ansible/commit/a0688027a5b80143868efe669354c6db34cf22f5

**Comment by jborean93** [comment]
https://github.com/ansible/ansible/issues/59414 has details on the issue.

**Pull request merged**
