### PR TITLE
Additional documentation for with_subelements

### PR DESCRIPTION
**Pull request by randomvariable**
This improves the ability to work on EC2 related tasks, where you may have run an EC2 task that creates many items with another list of items.

Documentation explaining what happens has been added to the relevant wiki page https://github.com/randomvariable/ansible/blob/with_dict_lists/docsite/rst/playbooks_loops.rst#iterating-over-a-nested-list-as-the-output-of-register .

A better plugin name is welcome.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks like it seems to be the same as "with_subelements", but I could be wrong.  Could you explain a bit about how this is different?

**Comment by mpdehaan** [comment]
(I'm also wondering if it might be possible to teach with_subelements to cover both cases if not).

**Comment by randomvariable** [comment]
Oh yeah, haha.
The item.0 and item.1 syntax threw me. Maybe the example in this updated commit would help?

**Comment by mpdehaan** [comment]
Think you may mean "{{ item.1.id }}"

Otherwise looks good

**Comment by randomvariable** [comment]
Ooof. Fixed now.

**Comment by amenonsen** [comment]
This PR is still relevant, and I found the added example quite useful. As far as I can tell, the commit no longer applies only because of the extraneous whitespaces changes included originally (removing whitespace at the end of various lines, which were subsequently fixed in other commits).

@randomvariable, any chance you could update the PR to just include the new example?

**Comment by amenonsen** [comment]
I rebased this PR and, in the process, changed my mind. I think the existing example is sufficient, and this PR should be closed. (This adds a lengthy example of using ec2 and iterating over its JSON results, but in terms of _subelement_ usage, it adds nothing new or explanatory.)

**Comment by bcoca** [comment]
closing as per above

**Pull request closed without merging**
