### PR TITLE
Fix hacking/test-module to allow running modules with pdb

### PR DESCRIPTION
**Pull request by michael-dev2rights**
##### SUMMARY

hacking/test-module fails if given a debugger to run - this fixes that

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

hacking/test-module

##### ANSIBLE VERSION

```
ansible 2.3.0.0 (ansible-d2r ff3dc4f1e7) last updated 2017/03/21 10:44:16 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mikedd/dev/ansible/ansible-d2r/library']
  python version = 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

what I did:
run 
    hacking/test-module -m lib/ansible/modules/system/ping.py --debugger=(which pdb)

what I expected to happen:
module should be run under pdb

what actually happened:
hacking/test-module crashed. 

extra information:
at one point in debugging somewhere in the system I also had to patch an "import pdb.pdb" statement to be simply "import pdb" not sure where that was though. 

```
PROMPT> hacking/test-module -m lib/ansible/modules/system/ping.py --debugger=(which pdb)
* including generated source, if any, saving to: /home/mikedd/.ansible_module_generated
Traceback (most recent call last):
  File "hacking/test-module", line 266, in <module>
    main()
  File "hacking/test-module", line 260, in main
    rundebug(options.debugger, modfile, argspath, modname, module_style)
  File "hacking/test-module", line 235, in rundebug
    modfile, argspath = ansiballz_setup(modfile, modname)
TypeError: ansiballz_setup() takes exactly 3 arguments (2 given)


PROMPT> git checkout mdd-fix-test-module-pdb
Switched to branch 'mdd-fix-test-module-pdb'
PROMPT> hacking/test-module -m lib/ansible/modules/system/ping.py --debugger=(which pdb)
* including generated source, if any, saving to: /home/mikedd/.ansible_module_generated
* ansiballz module detected; extracted module source to: /home/mikedd/debug_dir
> /home/mikedd/debug_dir/ansible_module_ping.py(23)<module>()
-> ANSIBLE_METADATA = {'metadata_version': '1.0',
(Pdb) 

```

### CODE REVIEW

**Comment by michael-dev2rights** [comment]
also added a .gitignore fix because it currently doesn't ignore #autosave# files.

**Comment by gundalow** [comment]
If this is the right way then it needs documenting on `dev_guide`

**Comment by akofink** [comment]
This fix works for me. I couldn't get pdb working with the test-module without it. I agree that there needs to be a section in the dev_guide for 'Debugging your module'.

**Comment by s-hertel** [comment]
Also appreciating this, though it would be nice to not have to patch the debugger. Epdb requires a lot of patching.

**Pull request merged**
