### PR TITLE
Fixing Issue#18995

### PR DESCRIPTION
**Pull request by sermilrod**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
```
jenkins_job
```

##### ANSIBLE VERSION
For Ansible 2.3

##### SUMMARY

jenkins_job module fails creating jobs of type OrganizationFolder [Issue#18995](https://github.com/ansible/ansible/issues/18995)

### CODE REVIEW

**Comment by sermilrod** [comment]
ready_for_review

**Comment by abadger** [comment]
This is an owner PR to a community owned module.  Merging.

**Comment by abadger** [comment]
thanks @sermilrod !

**Comment by sermilrod** [comment]
Anytime! Happy to maintain the module!

**Pull request merged**
