### PR TITLE
allow sudo to take a user

### PR DESCRIPTION
**Pull request by weaselkeeper**
First attempt at getting sudo -u functionality.  It's not optimum, needs a bit of cleanup.  But it seems to work without breaking other stuff so far.  Only works on ad-hoc at the moment, haven't done any playbook stuff yet, so haven't tried to work it into that yet.

### CODE REVIEW

**Comment by mpdehaan** [comment]
thanks, in queue for review in a few days, much appreciated

**Comment by jkleint** [comment]
This looks pretty good.  What do you think about folding Runner's sudo and sudo_user parameters into one that's either the username or None?  Since you'll only ever need a sudo username when you're using sudo, it would simplify things a bit.  Similarly, it might also make sense to have ansible's --sudo option take an optional username (that defaults to root) instead of introducing another parameter.  Cuts down on parameters the user has to worry about.

Oh, and we should probably quote the username in the sudo command; I know this guy who's username is `root rm -rf /` and he is no fun at parties.  ;)

**Comment by mpdehaan** [comment]
not so concerned.  Further, I do not want to break script compatibility by changing the CLI options, most people will not be needing to specify "--sudo root".   I assume --sudo-user would imply sudo=True.

we have a command module that allows rm -rf, so I don't see tremendous concern over that :) 
Quoting is technically correct of course.

**Comment by weaselkeeper** [comment]
On Fri, May 4, 2012 at 7:10 AM, Michael DeHaan
reply@reply.github.com
wrote:

> not so concerned.  Further, I do not want to break script compatibility by changing the CLI options, most people will not be needing to specify "--sudo root".   I assume --sudo-user would imply sudo=True.
> 
> we have a command module that allows rm -rf, so I don't see tremendous concern over that :)
> Quoting is technically correct of course.

It can definitely use some more work.  I don't like how I passed the
sudo_user info across to the connector module, it's far from elegant,
but it does work and I wasn't able to come up with a better way at the
time.

Quoting is always good though :)

##

**Comment by mpdehaan** [comment]
manually merged, I made a few additions to make it work better with playbooks, so sudo_user can also be expressed there.

I also intend to allow these variables/settings to bubble up from inventory variables in a future commit.

**Comment by weaselkeeper** [comment]
On Sun, May 6, 2012 at 5:19 PM, Michael DeHaan
reply@reply.github.com
wrote:

> manually merged, I made a few additions to make it work better with playbooks, so sudo_user can also be expressed there.
> 
> I also intend to allow these variables/settings to bubble up from inventory variables in a future commit.

Most excellent!  thanks.

## 

http://neon-buddha.net

**Pull request closed without merging**
