### PR TITLE
Fix non-sudo execution, add --sudo-user to ansible-playbook

### PR DESCRIPTION
**Pull request by jkleint**
The recent addition of --sudo-user was always trying to use sudo in every case.  This fixes it and also adds --sudo-user to ansible-playbook (actually to utils.base_parser).  It also turns on sudo mode if you --ask-sudo-pass.

### CODE REVIEW

**Comment by mpdehaan** [comment]
merge commits are all messed up in here, can you resubmit just the patch in question

git rebase vs git merge is helpful

**Comment by jkleint** [comment]
Sorry, will do first thing tomorrow.

**Comment by mpdehaan** [comment]
yeah I can web merge away from my development setup, I cannot cherry pick at all that way.

I can cherry pick this tonight though so don't worry about it -- seeing I'd like to spare the users the pain
of this -- but for next time, yeah, something to remember.

**Comment by mpdehaan** [comment]
manually cherry picked and pushed, thanks!

**Comment by jkleint** [comment]
Cool, will rebase next time.  Thanks!

**Pull request closed without merging**
