### PR TITLE
docker_network: adding/updating tests

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
#32927 and #32580 have been fixed already. This adds tests for that.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_network

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @DBendit

**Comment by felixfontein** [comment]
BTW, I also wanted to resolve (in a third commit) why the idempotency checks in basic.yml don't work. So far, my result seems to be that due to a bug in docker, `docker network inspect <nname>` and the corresponding docker-py calls always return an empty set of containers for the network. That's why the module thinks the container has to be added again every time...

**Comment by DBendit** [comment]
> BTW, I also wanted to resolve (in a third commit) why the idempotency checks in basic.yml don't work. So far, my result seems to be that due to a bug in docker, `docker network inspect <nname>` and the corresponding docker-py calls always return an empty set of containers for the network. That's why the module thinks the container has to be added again every time...

If the source libraries are lying to us, there's not a ton that we can do about it. In this case, the changes look good. Thanks for adding these checks - I sort of took it at face value that the PR I mentioned did the things it said it did.

shipit

**Comment by felixfontein** [comment]
I already wanted to add that test earlier, and I was wondering why we forgot to close that issue...

> If the source libraries are lying to us, there's not a ton that we can do about it.

Yep. I'll try to find out why that's happening a bit; if I ever do, we can still fix this later ;)

**Comment by felixfontein** [comment]
Interestingly, when I connect the container to the network manually (CLI `docker network connect test-network test-container`), `docker network inspect test-network` lists the container.

**Comment by felixfontein** [comment]
I went through docker-cli, moby and docker-py sources; I really don't see why the CLI way should work, while the docker_network module way doesn't. They should result in the same... I might take another look later, but for now I'm giving up on this :)

**Comment by felixfontein** [comment]
@DBendit thanks for reviewing!
@samdoran thanks for merging!

**Pull request merged**
