### PR TITLE
Show version without supplying a dummy action

### LINKED ISSUE #12004: ansible-galaxy won't show it's version if called without an action
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0 (devel 1b810e3101)
##### Ansible Configuration:

n/a
##### Environment:

Gentoo Linux, Python 2.7.9
##### Summary:

To see the version of ansible-galaxy one has to provide a fake action because without an action ansible-galaxy will just show the usage and an error message.
##### Steps To Reproduce:

Clone current devel, switch to hacking and execute `ansible-galaxy --version`
##### Expected Results:

```
$ ansible-galaxy --version
ansible-galaxy 2.0.0 (devel 1b810e3101) last updated 2015/08/19 12:39:34 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/19 12:40:20 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/19 12:40:33 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/19 12:40:47 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/19 12:41:00 (GMT +200)
  config file = 
  configured module search path = None
```
##### Actual Results:

```
$ ansible-galaxy --version
Usage: ansible-galaxy [init|info|install|list|remove] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
```

### PR DESCRIPTION
**Pull request by muffl0n**
fixes #12004

### CODE REVIEW

**Comment by gildegoma** [comment]
"Blindly" tested this change: it works fine for me :)

**Comment by bcoca** [comment]
merged manually

**Comment by gildegoma** [comment]
@bcoca @muffl0n :+1: thanks guys!

**Comment by muffl0n** [comment]
Awesome! Thanks for merging this!

**Pull request closed without merging**
