### PR TITLE
added dynamic gitlab runner inventory

### PR DESCRIPTION
**Pull request by morph027**
##### SUMMARY
This adds a dynamic inventory for Gitlab CI runners.

##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
2.5.0
```

### CODE REVIEW

**Comment by gundalow** [comment]
```
contrib/inventory/gitlab_runners.py:62:9: E722 do not use bare 'except'
contrib/inventory/gitlab_runners.py:68:13: E722 do not use bare 'except'
```

**Comment by Shaps** [comment]
Looks good to me. I have tested it on `ansible 2.8.0.dev0` and works fine. 

@Lunik  Unless you have any objections, I'm happy for it to be merged

**Comment by mattclay** [comment]
@morph027 Thank you for your contribution. However, new `contrib/inventory/` scripts are not being accepted. Instead, convert your inventory script to an inventory plugin. See [developing inventory](https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#inventory-plugins) for additional details.

**Comment by Shaps** [comment]
Given this previous comment, I believe this can be closed. 
@morph027 we'd appreciate if you could covert it into an inventory plugin :)

**Comment by morph027** [comment]
Just started my first plugin (https://github.com/ansible/ansible/pull/53058). When merged, i'll can start to convert this one too ;)

**Comment by Shaps** [comment]
@morph027 great, thank you very much!

**Comment by morph027** [comment]
https://github.com/ansible/ansible/pull/53897

**Pull request closed without merging**
