### PR TITLE
win_defrag: not running on all drives using /C

### LINKED ISSUE #48660: win_defrag: Defrag all volume do not work correctly
##### SUMMARY
Defrag all volume do not work correctly because "defrag /c" do nothing.

##### ISSUE TYPE
- Bug Report Pull request

##### COMPONENT NAME
win_defrag

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
Windows 8, 8.1, 10, 2012, 2012R2, 2016, 2019

##### STEPS TO REPRODUCE
Run this play
```yaml
- name: Defrag
  hosts: windows
  gather_facts: false
  tasks:
  - name: Defrag all volumes
    win_defrag:
      priority: normal
    register: defrag
  - debug:
      var: defrag
```

##### EXPECTED RESULTS
Invoke dafrag on all volumes

##### ACTUAL RESULTS
Do not invoke defrag due dafrag util issue.

### PR DESCRIPTION
**Pull request by ShachafGoldstein**
##### SUMMARY
Fixes: #48660

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_defrag.ps1

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by ShachafGoldstein** [comment]
@jborean93 @nitzmahone - Please review when you have the time

**Comment by jhawkesworth** [comment]
Code change looks good to me.

**Comment by specator** [comment]
It strange because on WS2016 (1607) it works fine, but on WS2019 (1809 and 1903) this returns nothing.

**Comment by specator** [comment]
I think that problem with **[String]::Join(' ', ... )** because just **(Get-CimInstance -Class Win32_Volume -Filter "(drivetype=3 OR drivetype=2)" -Property DriveLetter).DriveLetter)** returns correct array with DriveLetters.

**Comment by specator** [comment]
Also I had checked that your script do not include partitions mapped with **mountpoints** ([link](https://docs.microsoft.com/en-us/windows/desktop/fileio/volume-mount-points)). E.g. when I can mount a partition to **c:\mounted drives\Vol1**

**Comment by ShachafGoldstein** [comment]
Changed to fix mounted path issue, regarding the WS2019, can you tell me what .net and Powershell versions you have on the machine?

**Comment by jhawkesworth** [comment]
@specator can you confirm if @ShachafGoldstein 's latest version of this fix works for you on WS2019?

**Comment by jborean93** [comment]
PR is migrated to https://github.com/ansible-collections/community.windows/pull/3.

**Pull request closed without merging**
