### PR TITLE
Consistent lazy unvaulting for ansible-inventory

### LINKED ISSUE #31141: ansible-inventory failure with vaulted value in yaml inventory
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`ansible-inventory` CLI

##### ANSIBLE VERSION
```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

Also tested in 2.4, same behavior.

##### CONFIGURATION
```
ansible-config dump --only-changed
```
(no output)

##### OS / ENVIRONMENT
Running from Mac, python 2.7
controlling N/A

##### SUMMARY
Putting a vaulted value inside of a yaml inventory file causes an error running `ansible-inventory` on that file, apparently related to the serialization before writing the result to the terminal.

##### STEPS TO REPRODUCE
Use the following as your inventory file. Save file to `vault/yaml_subvar/ansible_example.yml` relative to where you're running it from, [example file in source control](https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/vault/yaml_subvar/ansible_example.yml).

```yaml
# https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
ungrouped:
  hosts:
      green.example.com:
          firstvariable: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              32633234373965356537366531333238363166393039306462633137353462396335653531633637
              6335366138623264303862306535303366646630643262650a386433376130383562343037613764
              62653330643635623033323764383461613331336339336435633864303032646233393336643366
              6163383166626565660a623836303939326564346338343338346366373561623862633065613266
              6132
          anyvariable: value
```

Now run `ansible-inventory` to list the outputs from this. Provide "password" as the vault password, as that is the password I used to vault the contents with `ansible-vault encrypt_string 191.168.100.32`. As so:

```
ansible-inventory -i vault/yaml_subvar/ansible_example.yml --list --ask-vault-pass -vvv
```

##### EXPECTED RESULTS
```
{
    "_meta": {
        "hostvars": {
            "green.example.com": {
                "firstvariable": "191.168.100.32", 
                "anyvariable": "value"
            }
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "green.example.com"
        ]
    }
}
```

How am I sure of the validity of this expectation? Corresponding `ansible-playbook` command:

```
ansible-playbook -i vault/yaml_subvar/ansible_example.yml --ask-vault-pass debug.yml
```

(the vault password "password" is provided to this command as well)

Contents of `debug.yml`:

```
---

- hosts: all
  gather_facts: false
  vars:
    msg: 'hello world {{ firstvariable }}'
  tasks:
    - debug: var=msg
```

output:

```
Vault password: 

PLAY [all] *************************************************************************************************************************************************************

TASK [debug] ***********************************************************************************************************************************************************
ok: [green.example.com] => {
    "msg": "hello world 191.168.100.32"
}

PLAY RECAP *************************************************************************************************************************************************************
green.example.com          : ok=1    changed=0    unreachable=0    failed=0  
```

This proves that the functionality of Ansible works. Thus, the problem lies with `ansible-inventory` alone.

##### ACTUAL RESULTS
```
ansible-inventory 2.5.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible-inventory
  python version = 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
No config file found; using defaults
Vault password: 
Parsed /Users/alancoding/Documents/repos/ansible-inventory-file-examples/vault/yaml_subvar/ansible_example.yml inventory source with yaml plugin
ERROR! Unexpected Exception, this is probably a bug: u'191.168.100.32' is not JSON serializable
the full traceback was:

Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/EGG-INFO/scripts/ansible-inventory", line 109, in <module>
    exit_code = cli.run()
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/cli/inventory.py", line 164, in run
    results = self.dump(results)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/cli/inventory.py", line 181, in dump
    results = json.dumps(stuff, sort_keys=True, indent=4)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: u'191.168.100.32' is not JSON serializable
```

Note that the value was successfully unencrypted (191.168.100.32). Some kind of display/unicode error prevented the data's serialization.

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Given an inventory source with vaulted content, this polishes behavior in 2 cases,
1) vault secrets given
2) vault secrets not given

Prior behavior was that --yaml option returned 'unvaulted' content in both cases, even with valid secrets, and default JSON format would not work in either case.

New behavior with this change is that 'unvaulted' content is returned in both cases when secrets are not given (2) and in scenario (1) it correctly decrypts in both formats.

Here, I summarize with a table.

|      | secrets provided | secrets not provided |
|------|------------------|----------------------|
| json | 💥->✅            | 💥->ㅃ*               |
| yaml | ㅃ->✅            | ㅃ->ㅃ               |

table key:
 - ✅ returns all decrypted plaintext variables
 - 💥error
 - ㅃ returns 'undecrypted' vault content
 - `*` qualifier, this isn't a raw object due to rules of the JSON standard

Replaces #36862 with new suggested method

Fixes #31141

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
ansible-inventory CLI

##### ANSIBLE VERSION
```
ansible --version
ansible 2.6.0 (just_dont_decrypt a2efe74001) last updated 2018/03/05 13:28:04 (GMT -400)
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/Documents/repos/ansible/lib/ansible
  executable location = /Users/alancoding/Documents/repos/ansible/bin/ansible
  python version = 2.7.11 (default, Oct 17 2016, 14:59:40) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### ADDITIONAL INFORMATION
Note that JSON output can not be loaded again (via `json.loads`) without additional post-processing. This returns it as a normal string, and I suspect that is best.

As far as AWX is concerned, this fixes it for me.

For JSON loading, This requires reserving the "!vault " starting string in the variables namespace. While this could be a problem for some people, I feel like it shouldn't be.

### CODE REVIEW

**Comment by AlanCoding** [comment]
Dump of demos from the table, start from the top left, go right and then down.

json, secrets provided

```
ansible-inventory -i vault/single_var_file/inventory.ini --list --export --vault-id=alan@vault/password
{
    "_meta": {
        "hostvars": {
            "host1": {}, 
            "host2": {}
        }
    }, 
    "all": {
        "children": [
            "raleigh", 
            "ungrouped"
        ]
    }, 
    "raleigh": {
        "hosts": [
            "host1", 
            "host2"
        ], 
        "vars": {
            "should_be_artemis_here": "artemis\n"
        }
    }, 
    "ungrouped": {}
}

```

json, secrets not provided

```
ansible-inventory -i vault/single_var_file/inventory.ini --list --export
{
    "_meta": {
        "hostvars": {
            "host1": {}, 
            "host2": {}
        }
    }, 
    "all": {
        "children": [
            "raleigh", 
            "ungrouped"
        ]
    }, 
    "raleigh": {
        "hosts": [
            "host1", 
            "host2"
        ], 
        "vars": {
            "should_be_artemis_here": "!vault: $ANSIBLE_VAULT;1.2;AES256;alan\n30386264646430643536336230313232653130643332356531633437363837323430663031356364\n3836313935643038306263613631396136663634613066650a303838613532313236663966343433\n37636234366130393131616631663831383237653761373533363666303361333662373664336261\n6136313463383061330a633835643434616562633238383530356632336664316366376139306135\n3534"
        }
    }, 
    "ungrouped": {}
}
```

yaml, secrets provided

```
ansible-inventory -i vault/single_var_file/inventory.ini --list --export --vault-id=alan@vault/password --yaml
all:
  children:
    raleigh:
      hosts:
        host1: {}
        host2: {}
      vars:
        should_be_artemis_here: 'artemis

          '
    ungrouped: {}
```

yaml, secrets not provided

```
ansible-inventory -i vault/single_var_file/inventory.ini --list --yaml
all:
  children:
    raleigh:
      hosts:
        host1:
          should_be_artemis_here: &id001 !vault |-
            $ANSIBLE_VAULT;1.2;AES256;alan
            30386264646430643536336230313232653130643332356531633437363837323430663031356364
            3836313935643038306263613631396136663634613066650a303838613532313236663966343433
            37636234366130393131616631663831383237653761373533363666303361333662373664336261
            6136313463383061330a633835643434616562633238383530356632336664316366376139306135
            3534
        host2:
          should_be_artemis_here: *id001
    ungrouped: {}

```

**Comment by bcoca** [comment]
And I hope this #37019 can restore the previous 'yaml only' behaviour on demand

**Comment by bcoca** [comment]
After looking at this more closely, it makes sense to pass everything 'vaulted' when no secrets are provided, the toggle I add above can be 'in addition to' this.

**Comment by alikins** [comment]
ah, this is for same issue https://github.com/ansible/ansible/pull/31946/ was intended for

If we can change module_utils.basic.jsonify() then this pr (37029) seems reasonable at first glance

**Comment by abadger** [comment]
@AlanCoding  I'm going to try to talk to you on slack about this because on the surface, this seems like a bad feature idea.  But I bet there's an underlying use case that we could implement in a different way.

**Comment by jesusvazquez** [comment]
Hi, what is the update on this? Did https://github.com/ansible/ansible/pull/37029#issuecomment-372768372 discussion happen?

I'd like to know why this could be a bad idea too and if this PR is finally going through.

Thanks!

**Comment by AlanCoding** [comment]
@jesusvazquez The problem with this PR is that it's still not reversible. The implementation here is arbitrarily using the string prefix of "!vault" to indicate vaulted content. But the problem is that this output wouldn't be readable by `ansible-playbook` subsequently (which was the entire point of `ansible-inventory`). The issue is that no agreed-upon schema for vaulted secrets in JSON existed before now. We now have that (details in linked issues), but this PR hasn't been updated. I do have this item on my own planning agenda, and I will return to implement the new schema, unless someone else gets to it first.

**Comment by jesusvazquez** [comment]
Thanks for the explanation @AlanCoding. Looking forward for those changes.

**Comment by AlanCoding** [comment]
I just installed latest `devel` so I could run my testing matrix here. This is what I find:

|      | secrets provided | secrets not provided |
|------|------------------|----------------------|
| json | 💥->ㅃ            | 💥->ㅃ               |
| yaml | ㅃ->ㅃ            | ㅃ->ㅃ               |

```
$ ansible-inventory -i vault/single_var_file/inventory.ini --list --export --vault-id=alan@vault/password
{
    "_meta": {
        "hostvars": {
            "host1": {}, 
            "host2": {}
        }
    }, 
    "all": {
        "children": [
            "raleigh", 
            "ungrouped"
        ]
    }, 
    "raleigh": {
        "hosts": [
            "host1", 
            "host2"
        ], 
        "vars": {
            "should_be_artemis_here": {
                "__ansible_vault": "$ANSIBLE_VAULT;1.2;AES256;alan\n30386264646430643536336230313232653130643332356531633437363837323430663031356364\n3836313935643038306263613631396136663634613066650a303838613532313236663966343433\n37636234366130393131616631663831383237653761373533363666303361333662373664336261\n6136313463383061330a633835643434616562633238383530356632336664316366376139306135\n3534"
            }
        }
    }, 
    "ungrouped": {}
}
$ ansible-inventory -i vault/single_var_file/inventory.ini --list --export
{
    "_meta": {
        "hostvars": {
            "host1": {}, 
            "host2": {}
        }
    }, 
    "all": {
        "children": [
            "raleigh", 
            "ungrouped"
        ]
    }, 
    "raleigh": {
        "hosts": [
            "host1", 
            "host2"
        ], 
        "vars": {
            "should_be_artemis_here": {
                "__ansible_vault": "$ANSIBLE_VAULT;1.2;AES256;alan\n30386264646430643536336230313232653130643332356531633437363837323430663031356364\n3836313935643038306263613631396136663634613066650a303838613532313236663966343433\n37636234366130393131616631663831383237653761373533363666303361333662373664336261\n6136313463383061330a633835643434616562633238383530356632336664316366376139306135\n3534"
            }
        }
    }, 
    "ungrouped": {}
}
$ ansible-inventory -i vault/single_var_file/inventory.ini --list --export --vault-id=alan@vault/password --yaml
all:
  children:
    raleigh:
      hosts:
        host1: {}
        host2: {}
      vars:
        should_be_artemis_here: !vault |-
          $ANSIBLE_VAULT;1.2;AES256;alan
          30386264646430643536336230313232653130643332356531633437363837323430663031356364
          3836313935643038306263613631396136663634613066650a303838613532313236663966343433
          37636234366130393131616631663831383237653761373533363666303361333662373664336261
          6136313463383061330a633835643434616562633238383530356632336664316366376139306135
          3534
    ungrouped: {}
$ ansible-inventory -i vault/single_var_file/inventory.ini --list --yaml
all:
  children:
    raleigh:
      hosts:
        host1:
          ansible_verbosity: 0
          should_be_artemis_here: &id001 !vault |-
            $ANSIBLE_VAULT;1.2;AES256;alan
            30386264646430643536336230313232653130643332356531633437363837323430663031356364
            3836313935643038306263613631396136663634613066650a303838613532313236663966343433
            37636234366130393131616631663831383237653761373533363666303361333662373664336261
            6136313463383061330a633835643434616562633238383530356632336664316366376139306135
            3534
        host2:
          ansible_verbosity: 0
          should_be_artemis_here: *id001
    ungrouped: {}
```

The decision was basically that ansible-inventory will not support un-vaulting. The use case I had in mind works perfectly fine with this. I think this can be classified as resolved.

**Pull request closed without merging**
