### PR TITLE
Do not error if collection specified null dependencies

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Fixes the issue I described in https://github.com/ansible/ansible/issues/67574

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/galaxy/collection.py

##### ADDITIONAL INFORMATION
Tested with the steps I outlined in that issue, and it installs now.

### CODE REVIEW

**Review by samdoran — APPROVED** [review]

**Review by jborean93 — APPROVED** [review]

**Comment by s-hertel** [comment]
I'm still experiencing traceback you posted in the bug with this PR:
```
...
  File "/home/liveuser/ansible/lib/ansible/galaxy/collection.py", line 834, in _build_dependency_map
    if no_deps or len(dependency_map[collection].dependencies) == 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by s-hertel** [comment]
Specifically, when the `dependencies` key has no value, installing fails both on devel and this branch with that traceback, but builds fine.

**Review by s-hertel — COMMENTED** [review]
It may be easiest to modify the dependencies property.
```diff
     @property
     def dependencies(self):
         if self._metadata:
-            return self._metadata.dependencies
+            dependencies = self._metadata.dependencies
         elif len(self.versions) > 1:
-            return None
+            dependencies = {}
+        else:
+            self._get_metadata()
+            dependencies = self._metadata.dependencies
 
-        self._get_metadata()
-        return self._metadata.dependencies
+        if dependencies is None:
+            dependencies = {}
+
+        return dependencies
```

**Comment by s-hertel** [comment]
After some further investigation: what this PR fixes is when the dependency with the bad dep is already installed. e.g. softasap.redis_box is already installed, and I'm installing a collection that has softasap.redis_box as a dependency. This doesn't work when installing a collection that contains a dependency that has its own bad dependency that isn't already installed or installing a collection with a bad dependency. My patch above fixes it universally.

**Comment by AlanCoding** [comment]
I agree @s-hertel's proposal will be more airtight, because the case I originally had also involved referencing the dependencies property.

I just need to re-test with that..

and it works. If you want to make a new PR, I'd approve it, but I'll push a change this with essentially what you have there.

**Comment by AlanCoding** [comment]
> what this PR fixes is when the dependency with the bad dep is already installed. e.g. softasap.redis_box is already installed, and I'm installing a collection that has softasap.redis_box as a dependency

Yes, agreed that this is the critical distinction. I kind of saw how there were the 2 different code paths for when it's already installed versus when it gets it anew, and it makes sense how that other case didn't occur to me because I was running repeatedly locally without force-with-deps option.

**Review by s-hertel — APPROVED** [review]

**Comment by samdoran** [comment]
Looks like the unit tests need updating.

**Comment by AlanCoding** [comment]
thanks, hopefully it should be mergeable now

**Pull request merged**
