### PR TITLE
Adding gcp auth module for ansible vault lookups

### PR DESCRIPTION
**Pull request by sharkannon**
##### SUMMARY
Adding the ability to use GCP IAM authentication for vault lookups.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
gcp_auth

### CODE REVIEW

**Comment by sharkannon** [comment]
Is there any possibility on getting this triaged?

**Comment by sharkannon** [comment]
@rambleraptor @erjohnso I was told to CC you guys on this PR, wanted to get this in.

**Comment by curtisstpierre** [comment]
Is there any chance this will get looked at? It seems like this has been open for a while and would be great to get in.

**Review by rambleraptor — APPROVED** [review]
I'm not an expert on the GCP client libraries, but this looks fine!

**Pull request closed without merging**
