### PR TITLE
Don't produce Cartesian Product

### PR DESCRIPTION
**Pull request by bradleyy**
This should take the nth element of all the arrays, and construct arrays with them.

Useful if you're attempting to do something like:
- name: put DB filenames in file
  shell: ls {{download_dir}}/*.sql | sort
  register: sql_files
- name: put DB names in var
  shell: ls *.sql | sort | sed -e 's/.sql//' chdir={{download_dir}}
  register: db_names
- name: install DBs
  action: mysql_db db={{ item[0] }} state=import target={{ item[1] }}
  with_nested: "{{ db_names.stdout_lines }}, {{ sql_files.stdout_lines }}"

### CODE REVIEW

**Comment by bradleyy** [comment]
For reference, I believe this fixes the "with_nested" functionality. Currently, the with_nested loops over the cartesian product:

[1,2],[3,4] becomes a loop over [1,3],[1,4],[2,3],[2,4]

Rather than what I think the intent was:

[1,2],[3,4] becomes [1,3],[2,4]

**Comment by mpdehaan** [comment]
This doesn't take a string, it takes two or more lists.

https://github.com/ansible/ansible-examples/blob/master/language_features/loop_nested.yml

You can't simply feed it strings joined by commas and expect that to be a set of lists.

However the following should work, let me know if it does not:

with_nested:
-  list_variable_name_one
  - list_variable_name_two

Do not need to use "{{ }}" here.

In which case this not working would be a different bug report.

Thanks!

**Comment by bradleyy** [comment]
My apologies for putting a red herring in there. I did document that the with_nested is:

**Creating a Cartesian Product**

I'm sorry that I left that line in there, even though it works perfectly. Please ignore it. It isn't a different bug report, the fact that the with_nested method creates a Cartesian Product.

The example you sent: https://github.com/ansible/ansible-examples/blob/master/language_features/loop_nested.yml

currently produces the following 27 item loop (is this intended?):

TASK: [shell echo "nested test a={{item[0]}} b={{item[1]}} c={{item[2]}}"] ****
changed: [localhost] => (item=['red', 1, 'up']) => {"changed": true, "cmd": "echo \"nested test a=red b=1 c=up\" ", "delta": "0:00:00.003491", "end": "2013-07-11 15:49:27.601040", "item": ["red", 1, "up"], "rc": 0, "start": "2013-07-11 15:49:27.597549", "stderr": "", "stdout": "nested test a=red b=1 c=up"}
changed: [localhost] => (item=['red', 1, 'down']) => {"changed": true, "cmd": "echo \"nested test a=red b=1 c=down\" ", "delta": "0:00:00.003639", "end": "2013-07-11 15:49:27.709776", "item": ["red", 1, "down"], "rc": 0, "start": "2013-07-11 15:49:27.706137", "stderr": "", "stdout": "nested test a=red b=1 c=down"}
changed: [localhost] => (item=['red', 1, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=red b=1 c=strange\" ", "delta": "0:00:00.003369", "end": "2013-07-11 15:49:27.820553", "item": ["red", 1, "strange"], "rc": 0, "start": "2013-07-11 15:49:27.817184", "stderr": "", "stdout": "nested test a=red b=1 c=strange"}
changed: [localhost] => (item=['red', 2, 'up']) => {"changed": true, "cmd": "echo \"nested test a=red b=2 c=up\" ", "delta": "0:00:00.003585", "end": "2013-07-11 15:49:27.925990", "item": ["red", 2, "up"], "rc": 0, "start": "2013-07-11 15:49:27.922405", "stderr": "", "stdout": "nested test a=red b=2 c=up"}
changed: [localhost] => (item=['red', 2, 'down']) => {"changed": true, "cmd": "echo \"nested test a=red b=2 c=down\" ", "delta": "0:00:00.003590", "end": "2013-07-11 15:49:28.036824", "item": ["red", 2, "down"], "rc": 0, "start": "2013-07-11 15:49:28.033234", "stderr": "", "stdout": "nested test a=red b=2 c=down"}
changed: [localhost] => (item=['red', 2, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=red b=2 c=strange\" ", "delta": "0:00:00.003519", "end": "2013-07-11 15:49:28.144240", "item": ["red", 2, "strange"], "rc": 0, "start": "2013-07-11 15:49:28.140721", "stderr": "", "stdout": "nested test a=red b=2 c=strange"}
changed: [localhost] => (item=['red', 3, 'up']) => {"changed": true, "cmd": "echo \"nested test a=red b=3 c=up\" ", "delta": "0:00:00.003441", "end": "2013-07-11 15:49:28.253989", "item": ["red", 3, "up"], "rc": 0, "start": "2013-07-11 15:49:28.250548", "stderr": "", "stdout": "nested test a=red b=3 c=up"}
changed: [localhost] => (item=['red', 3, 'down']) => {"changed": true, "cmd": "echo \"nested test a=red b=3 c=down\" ", "delta": "0:00:00.003305", "end": "2013-07-11 15:49:28.365511", "item": ["red", 3, "down"], "rc": 0, "start": "2013-07-11 15:49:28.362206", "stderr": "", "stdout": "nested test a=red b=3 c=down"}
changed: [localhost] => (item=['red', 3, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=red b=3 c=strange\" ", "delta": "0:00:00.003421", "end": "2013-07-11 15:49:28.472072", "item": ["red", 3, "strange"], "rc": 0, "start": "2013-07-11 15:49:28.468651", "stderr": "", "stdout": "nested test a=red b=3 c=strange"}
changed: [localhost] => (item=['blue', 1, 'up']) => {"changed": true, "cmd": "echo \"nested test a=blue b=1 c=up\" ", "delta": "0:00:00.003459", "end": "2013-07-11 15:49:28.584062", "item": ["blue", 1, "up"], "rc": 0, "start": "2013-07-11 15:49:28.580603", "stderr": "", "stdout": "nested test a=blue b=1 c=up"}
changed: [localhost] => (item=['blue', 1, 'down']) => {"changed": true, "cmd": "echo \"nested test a=blue b=1 c=down\" ", "delta": "0:00:00.003303", "end": "2013-07-11 15:49:28.703247", "item": ["blue", 1, "down"], "rc": 0, "start": "2013-07-11 15:49:28.699944", "stderr": "", "stdout": "nested test a=blue b=1 c=down"}
changed: [localhost] => (item=['blue', 1, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=blue b=1 c=strange\" ", "delta": "0:00:00.003356", "end": "2013-07-11 15:49:28.815831", "item": ["blue", 1, "strange"], "rc": 0, "start": "2013-07-11 15:49:28.812475", "stderr": "", "stdout": "nested test a=blue b=1 c=strange"}
changed: [localhost] => (item=['blue', 2, 'up']) => {"changed": true, "cmd": "echo \"nested test a=blue b=2 c=up\" ", "delta": "0:00:00.003616", "end": "2013-07-11 15:49:28.924892", "item": ["blue", 2, "up"], "rc": 0, "start": "2013-07-11 15:49:28.921276", "stderr": "", "stdout": "nested test a=blue b=2 c=up"}
changed: [localhost] => (item=['blue', 2, 'down']) => {"changed": true, "cmd": "echo \"nested test a=blue b=2 c=down\" ", "delta": "0:00:00.003576", "end": "2013-07-11 15:49:29.035049", "item": ["blue", 2, "down"], "rc": 0, "start": "2013-07-11 15:49:29.031473", "stderr": "", "stdout": "nested test a=blue b=2 c=down"}
changed: [localhost] => (item=['blue', 2, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=blue b=2 c=strange\" ", "delta": "0:00:00.003245", "end": "2013-07-11 15:49:29.142891", "item": ["blue", 2, "strange"], "rc": 0, "start": "2013-07-11 15:49:29.139646", "stderr": "", "stdout": "nested test a=blue b=2 c=strange"}
changed: [localhost] => (item=['blue', 3, 'up']) => {"changed": true, "cmd": "echo \"nested test a=blue b=3 c=up\" ", "delta": "0:00:00.003411", "end": "2013-07-11 15:49:29.251484", "item": ["blue", 3, "up"], "rc": 0, "start": "2013-07-11 15:49:29.248073", "stderr": "", "stdout": "nested test a=blue b=3 c=up"}
changed: [localhost] => (item=['blue', 3, 'down']) => {"changed": true, "cmd": "echo \"nested test a=blue b=3 c=down\" ", "delta": "0:00:00.003625", "end": "2013-07-11 15:49:29.361594", "item": ["blue", 3, "down"], "rc": 0, "start": "2013-07-11 15:49:29.357969", "stderr": "", "stdout": "nested test a=blue b=3 c=down"}
changed: [localhost] => (item=['blue', 3, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=blue b=3 c=strange\" ", "delta": "0:00:00.003574", "end": "2013-07-11 15:49:29.470740", "item": ["blue", 3, "strange"], "rc": 0, "start": "2013-07-11 15:49:29.467166", "stderr": "", "stdout": "nested test a=blue b=3 c=strange"}
changed: [localhost] => (item=['green', 1, 'up']) => {"changed": true, "cmd": "echo \"nested test a=green b=1 c=up\" ", "delta": "0:00:00.003542", "end": "2013-07-11 15:49:29.582407", "item": ["green", 1, "up"], "rc": 0, "start": "2013-07-11 15:49:29.578865", "stderr": "", "stdout": "nested test a=green b=1 c=up"}
changed: [localhost] => (item=['green', 1, 'down']) => {"changed": true, "cmd": "echo \"nested test a=green b=1 c=down\" ", "delta": "0:00:00.003594", "end": "2013-07-11 15:49:29.690811", "item": ["green", 1, "down"], "rc": 0, "start": "2013-07-11 15:49:29.687217", "stderr": "", "stdout": "nested test a=green b=1 c=down"}
changed: [localhost] => (item=['green', 1, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=green b=1 c=strange\" ", "delta": "0:00:00.003476", "end": "2013-07-11 15:49:29.797661", "item": ["green", 1, "strange"], "rc": 0, "start": "2013-07-11 15:49:29.794185", "stderr": "", "stdout": "nested test a=green b=1 c=strange"}
changed: [localhost] => (item=['green', 2, 'up']) => {"changed": true, "cmd": "echo \"nested test a=green b=2 c=up\" ", "delta": "0:00:00.003330", "end": "2013-07-11 15:49:29.905845", "item": ["green", 2, "up"], "rc": 0, "start": "2013-07-11 15:49:29.902515", "stderr": "", "stdout": "nested test a=green b=2 c=up"}
changed: [localhost] => (item=['green', 2, 'down']) => {"changed": true, "cmd": "echo \"nested test a=green b=2 c=down\" ", "delta": "0:00:00.003267", "end": "2013-07-11 15:49:30.023106", "item": ["green", 2, "down"], "rc": 0, "start": "2013-07-11 15:49:30.019839", "stderr": "", "stdout": "nested test a=green b=2 c=down"}
changed: [localhost] => (item=['green', 2, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=green b=2 c=strange\" ", "delta": "0:00:00.003320", "end": "2013-07-11 15:49:30.130917", "item": ["green", 2, "strange"], "rc": 0, "start": "2013-07-11 15:49:30.127597", "stderr": "", "stdout": "nested test a=green b=2 c=strange"}
changed: [localhost] => (item=['green', 3, 'up']) => {"changed": true, "cmd": "echo \"nested test a=green b=3 c=up\" ", "delta": "0:00:00.003451", "end": "2013-07-11 15:49:30.239904", "item": ["green", 3, "up"], "rc": 0, "start": "2013-07-11 15:49:30.236453", "stderr": "", "stdout": "nested test a=green b=3 c=up"}
changed: [localhost] => (item=['green', 3, 'down']) => {"changed": true, "cmd": "echo \"nested test a=green b=3 c=down\" ", "delta": "0:00:00.003483", "end": "2013-07-11 15:49:30.347470", "item": ["green", 3, "down"], "rc": 0, "start": "2013-07-11 15:49:30.343987", "stderr": "", "stdout": "nested test a=green b=3 c=down"}
changed: [localhost] => (item=['green', 3, 'strange']) => {"changed": true, "cmd": "echo \"nested test a=green b=3 c=strange\" ", "delta": "0:00:00.003478", "end": "2013-07-11 15:49:30.458637", "item": ["green", 3, "strange"], "rc": 0, "start": "2013-07-11 15:49:30.455159", "stderr": "", "stdout": "nested test a=green b=3 c=strange"}

**Comment by mpdehaan** [comment]
It's supposed to create a cartesian product.

**Pull request closed without merging**
