### PR TITLE
Added restart_delay to handle slow init stop methods

### PR DESCRIPTION
**Pull request by jeviolle**
Reference ansible issue 2435

### CODE REVIEW

**Comment by mpdehaan** [comment]
looks like this should add a "type='bool"', can you update this?

Otherwise looks good!

**Comment by jeviolle** [comment]
why would a type=bool be needed, restart_delay takes an integer as a value? let me know

**Comment by jeviolle** [comment]
I've added another commit to test if a script has been added to /etc/rc using update-rc.d. This is similar to how the chkconfig services are handled in the service module as well.

If the init script hasn't already been added via update-rc.d defaults, the enabled=yes returns success but no links are created using update-rc.d.

**Comment by mpdehaan** [comment]
Looks like this one can't be automatically merged.

Can you please rebase this?

**Comment by mpdehaan** [comment]
this should be rebased, not merged.

I will let you resubmit, but I am closing this due to merge commits in the pull request.

**Pull request closed without merging**
