### PR TITLE
Update vmware_host

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix adds following:
* Update logic in vmware_host
* Update example documentation
* Added test case for vmware_host

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_host.py
test/integration/targets/vmware_host/aliases
test/integration/targets/vmware_host/tasks/main.yml

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@jctanner ready_for_review

**Comment by dagwieers** [comment]
As discussed, #25144 includes your changes too (in your name).

Please verify :-)

**Comment by Akasurde** [comment]
Superseded by PR 25144.

**Pull request closed without merging**
