### PR TITLE
fix ipv6 for ssh connection

### PR DESCRIPTION
**Pull request by JuiceboxSingularity**
Fixes ipv6 when using ssh

### CODE REVIEW

**Comment by amenonsen** [comment]
Why is tempHost needed at all? Does something break if you leave self.host as '[...]'? Because if not, you could just change that one last block in **init** and be done. Also, you should at least remove the FIXME comment just above (and maybe drop the explicit comparisons to be consistent with other code, i.e. use «if self.host» and «if self._ipv6»).

**Comment by JuiceboxSingularity** [comment]
SSH breaks with the square brackets. Style and comments have been changed.

**Comment by amenonsen** [comment]
Hi @JuiceboxSingularity. I've been looking into your patch, and I can't see any reason not to just _always_ wrap the hostname/IP for scp and sftp in square brackets. It works for hostnames, IPv4, and IPv6 with ssh, scp, and sftp.

**Comment by amenonsen** [comment]
I submitted the simpler approach described above as #11816. Please check if that works for you?

**Comment by JuiceboxSingularity** [comment]
Seems good, thanks.

**Pull request closed without merging**
