### PR TITLE
[docker_container] Adding support for `mounts` option

### LINKED ISSUE #42054: docker_container should support --mount option
##### SUMMARY

docker_container should support --mount option, since that is the recommended way to bind volumes to a container according to https://docs.docker.com/storage/bind-mounts/
 
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/stefanlandro/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

Irreleveant

##### OS / ENVIRONMENT

Irreleveant

##### STEPS TO REPRODUCE

```yaml

- name: "docker container with mount"
   docker_container:
     mount: "type=volume,src=NFSVOL,volume-driver=local,dst=/destination,volume-opt=type=nfs,volume-opt=device=:/source,"volume-opt=o=addr=172.0.0.1,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576,retrans=2"

```

##### EXPECTED RESULTS

Same behaviour as running ```docker run --mount ...```

### PR DESCRIPTION
**Pull request by DBendit**
##### SUMMARY
Fixes #42054

Still very much a WIP. Just claiming it for now.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
docker_container

##### ADDITIONAL INFORMATION
N/A for now.

### CODE REVIEW

**Comment by felixfontein** [comment]
A potentially very ambitious project :) The interesting questions will begin when talking about how this behaves with the current volume-related options, and with idempotency. That depends a lot on how docker is handling this option internally.

**Comment by DBendit** [comment]
@felixfontein Thankfully, mounts and volumes are not only completely independent of each other, they can co-exist and be configured side-by-side. The only concern is mountpoint collisions, but I'm willing to let Docker handle that for us. As a result, it's not nearly so complicated as it could have been (or at least, I don't see the complexity quite yet).

**Comment by felixfontein** [comment]
@DBendit hi there! Just wanted to ask how you're doing on this one? Do you need any help?

**Comment by felixfontein** [comment]
Feature freeze has been pushed out to April 4th, so you still have almost two weeks if you want to get this included in Ansible 2.8.

**Comment by DBendit** [comment]
I was just reminded about this by a friend of mine who needs this functionality. I'll take another crack at it this week.

**Comment by belak** [comment]
I'm also looking forward to this... `-v` automatically creates any mount as a directory even if it doesn't exist while `--mount` will error... honestly I'd prefer the second behavior.

**Comment by Vladimir-csp** [comment]
I agree with @belak, this dir autocreation wreaks havoc on the host in case of an error, instead of raising an error.

**Comment by felixfontein** [comment]
Ok, I think I see what the problem is. Passing mounts to docker is pretty easy, but extracting the current mounts from an existing container is not that simple.

**Comment by felixfontein** [comment]
I was able to solve that mystery. The API documentation (current: https://docs.docker.com/engine/api/v1.39/) seems to be incomplete. Comment from my code:

> According to https://github.com/moby/moby/, support for HostConfig.Mounts has been included at least since v17.03.0-ce, which has API version 1.26.
> The previous tag, v1.9.1, has API version 1.21 and does not have HostConfig.Mounts. I have no idea what about API 1.25...

**Comment by felixfontein** [comment]
I think this is now done!

ready_for_review

**Comment by WojciechowskiPiotr** [comment]
Can you use 'volumes' and 'mounts' at the same time?

**Comment by felixfontein** [comment]
Yes, both together should work. I thought I added some simple tests for that, apparently I didn't... I'll add some later...

Anyway, it can happen that there are collisions (a volume and a mount with the same target). Docker should bail out on this on container creation. I'll also add a test for that.

**Comment by WojciechowskiPiotr** [comment]
> Yes, both together should work. I thought I added some simple tests for that, apparently I didn't... I'll add some later...
> 
> Anyway, it can happen that there are collisions (a volume and a mount with the same target). Docker should bail out on this on container creation. I'll also add a test for that.

How about adding preference, so if there is a collision then 'mount' parameters are used?

**Comment by felixfontein** [comment]
IMO collisions are errors and should not be ignored in any way. For now I'm happy if docker daemon handles that for us, but it would be nicer if the module could prevent this. But (same as @DBendit) I'm willing to let docker do that for now. I find it more important that `mounts` works in the first place :)

**Comment by WojciechowskiPiotr** [comment]
> IMO collisions are errors and should not be ignored in any way. For now I'm happy if docker daemon handles that for us, but it would be nicer if the module could prevent this. But (same as @DBendit) I'm willing to let docker do that for now. I find it more important that `mounts` works in the first place :)

Fine for me :) Let's put it on TODO list :) Let me know when it's ready for final review.

**Comment by felixfontein** [comment]
Current result:
```
02:26 TASK [docker_container : mounts + volumes (collision, should fail)] ************
02:27 fatal: [testhost]: FAILED! => {"changed": false, "msg": "Error creating container: 400 Client Error: Bad Request (\"Duplicate mount point: /tmp\")"}
02:27 ...ignoring
```
This will probably also happen if two `mounts` have the same target, or two volumes have the same target. So if we add a check, it should also cover collisions in `volumes` which are already possible now.

Now that all tests passed, I think this is ready for a final review.

@DBendit are you also interested in taking a look? After all, you started this :)

**Comment by felixfontein** [comment]
@WojciechowskiPiotr I created #59064 to track the collision detection.

**Comment by felixfontein** [comment]
@WojciechowskiPiotr I'm looking forward to the final review you promised ;)

**Review by jwitko — APPROVED** [review]
Thanks to all for this PR!  Great change!

**Comment by WojciechowskiPiotr** [comment]
shipit

**Comment by felixfontein** [comment]
This new feature will be available in Ansible 2.9, [currently planned](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_9.html#expected) for mid October 2019.

@DBendit thanks for getting this started!
@jwitko @WojciechowskiPiotr thanks for reviewing this!

**Pull request merged**
