### PR TITLE
document `jsonfile` fact cache

### PR DESCRIPTION
**Pull request by tamsky**

### CODE REVIEW

**Comment by bcoca** [comment]
actually both were available at the same time, but redis was only one that was well tested

**Comment by tamsky** [comment]
Then the statement in the original is false as well, and deserves correction?

> At the time of writing, Redis is the only supported fact caching engine.

Would you like my commit/PR altered to reflect this new (to me) information?

**Comment by bcoca** [comment]
nah, just 'Currently Ansible ships with 2 persistent cache plugins: redis and jsonfile'

**Comment by tamsky** [comment]
updated commit, reorganized it to flow more logically, and fixed the ansible.cfg example.

**Pull request merged**
