### PR TITLE
Fixing upgrade_policy idempotence

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Fixing #37903

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
azure_rm_virtualmachine_scaleset

##### ANSIBLE VERSION
2.5

### CODE REVIEW

**Comment by zikalino** [comment]
@yuwzho could you check it and shipit?

**Comment by zikalino** [comment]
shipit

**Comment by zikalino** [comment]
bot_status

**Review by yuwzho — APPROVED** [review]

**Comment by yuwzho** [comment]
shipit

**Comment by zikalino** [comment]
bot_status

**Comment by yuwzho** [comment]
shipit

**Comment by zikalino** [comment]
shipit

**Comment by yuwzho** [comment]
Fixes #37904 , #37903

@zikalino I think you have created several issues with this PR, can you link them?

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/60363/64/tests

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/71750/64/tests

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/75991/75/tests

**Comment by yuwzho** [comment]
shipit

**Comment by yungezz** [comment]
@zikalino  pls update one existing test to cover the change

**Comment by Fred-sun** [comment]
@jborean93 Could you help to review this PR? Thank!

**Pull request merged**
