### PR TITLE
Add Ubuntu xenial 16.04 image to travis

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

2.2, devel
##### SUMMARY

Adds ubuntu xenial 16.04 to the list of images run by travis.
Also fix broken tests.

Before merging the image should appear in dockerhub ansible/ansible and the IMAGE=robinro/\* hack be removed.

### CODE REVIEW

**Comment by robinro** [comment]
not all tests pass yet

the apt_repository tests fail, because they use repos, which aren't available for 16.04

**Comment by robinro** [comment]
feel free to build on top of this PR

**Comment by resmo** [comment]
@robinro I also added support for ubuntu 16.04 in the tests see #15561 but I introduced an issue with fedora in my mysql test changes

**Comment by gundalow** [comment]
Hi,
I'm updating the Docker images to speed up deb/rpm builds in https://github.com/ansible/ansible/pull/15692 once integrated it would be great if you could add the the relevant changes into this new OS image.

Give me a shout if you need a hand with any of this (gundalow on freenode).

**Comment by robinro** [comment]
@gundalow if you already need to rebuild all docker images, maybe you can also include this (ubuntu 16.04).

**Comment by resmo** [comment]
@robinro btw, I would rather set the systemd path to /etc/systemd instead of creating a dir manully in /usr/lib/systemd. I used it in https://github.com/ansible/ansible/pull/15561/commits/c8ef0b1bf0fdd359be173d09efb428538f996127 and it worked for me

**Comment by robinro** [comment]
@resmo sounds good to me. I'll rebase once your changes are in and clean that up.

**Comment by gundalow** [comment]
Hi, 
I don't have permission to build docker images, however you are right it may make sense that that once these three (mine +16.04 +OpenSUSE)  are integrated Docker Hubs is updated as one block.

**Comment by resmo** [comment]
tests for Ubuntu 16.04 and Debian 8 has been merged, so ready for rebase this PR. There are 2 open PR from me https://github.com/ansible/ansible-modules-core/pull/3541 and https://github.com/ansible/ansible-modules-core/pull/3582 related to Debian 8 and Ubuntu 16.04.

**Comment by robinro** [comment]
It's rebased now. The tests don't pass yet, but those are other issues as far as I see.

**Comment by robinro** [comment]
All tests pass now except mysql for which a fix exists, see comments by @resmo.
Maybe in the future one can also consider the order of things. Checking facts should be one of the first tests in my opinion and not the last (breaks when iproute2 is not installed in this case).
When these fixes are in, please re-trigger the test on this and integrate it when it gets green.

**Comment by robinro** [comment]
replaced by #15936

**Pull request closed without merging**
