### PR TITLE
Module maven_artifact : manage file dest attributes

### PR DESCRIPTION
**Pull request by laurentribot**
##### SUMMARY
Managing destination file attributes/permissions

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Module : modules/packaging/language/maven_artifact

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by ericcitaire** [comment]
shipit

**Comment by kbenyous** [comment]
👍 
shipit

**Comment by chrisisbeef** [comment]
shipit

**Comment by tumbl3w33d** [comment]
Hi @laurentribot, thank you for this PR. A problem I see here is that `dest` is not necessarily a file, which causes undesired behavior.

Example:
``` yaml
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - maven_artifact:
        version: latest
        artifact_id: spring-core
        group_id: org.springframework
        dest: /tmp/
        keep_name: yes
        mode: 0755
        owner: root
        group: www-data
```
Here we would end up with a corrupted /tmp/ folder that's not world writable anymore. As user I would expect that the file that gets downloaded (in this case `spring-core-4.3.10.RELEASE.jar`) gets the mode and ownerships applied, not the destination folder.

I can't imagine anyone would expect the destination folder to be affected by these settings, so I'd suggest you put some condition to handle this. Something like "if dest is a path, affect the downloaded file instead". Maybe you mention that in the `dest` documentation like "if file mode or ownerships are specified they affect the downloaded file, not the destination path". Feel free to reword.

In addition, I'd like to see your documentation snippet replaced by a [fragment](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-fragments)
```
extends_documentation_fragment:
    - files
```
The rest looks good to me but I will look at it once more when you updated. Thank you for your work so far!

**Comment by tumbl3w33d** [comment]
needs_revision

**Comment by zigarn** [comment]
Link #21577

**Comment by tumbl3w33d** [comment]
LGTM. Copying code from the copy module doesn't really make this a DRY solution, but at least we know it's battle hardened. Maybe a core dev with more comprehensive project overview can suggest a way to reuse that code directly.

You can go ahead and rebase it.

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by tumbl3w33d** [comment]
shipit

**Comment by tumbl3w33d** [comment]
@laurentribot I'm afraid you need to put ready_for_review so we get rid of the needs_revision label first.

**Comment by tumbl3w33d** [comment]
shipit

**Comment by tumbl3w33d** [comment]
@chrisisbeef we could need your attention here.

**Comment by tumbl3w33d** [comment]
bot_status

**Comment by tumbl3w33d** [comment]
@calfonso I'm afraid @chrisisbeef doesn't currently have time for reviewing stuff and several issues like this one are stuck which kinda paralyzes this module's development. This one even received a few shipits before (including Chris'). Don't you think we can get this in?

**Pull request merged**
