### PR TITLE
WIP: Add download_only option to the apt module

### LINKED ISSUE #23220: [Feature Request] apt module: add state "downloaded"
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
apt module, potentially other package managing modules

##### ANSIBLE VERSION
n/a

##### OS / ENVIRONMENT
Debian and derivatives

##### SUMMARY
Add option to download packages locally without installing them.

##### STEPS TO REPRODUCE
Emulating the user experience of:

    apt-get -d / apt-get download / apt-get --download-only [package1 package2]

Example:

```yaml
tasks:
  - name: Download all latest packages, but don't install yet
    apt:
      update_cache: yes
      only_upgrade: yes
      state: downloaded
```

##### EXPECTED RESULTS

After setting this flag, the specified package(s) can be installed later without requiring a download from the repository server(s).

##### ACTUAL RESULTS

Currently, this functionality of apt-get is not exposed in the apt module.

### PR DESCRIPTION
**Pull request by Taoquitok**
##### WIP to complete

- [ ] Fix perpetual `changed: true` state. Once file is dowloaded, stop reporting changed.
- [ ] Tests to validate above

##### SUMMARY

Extend apt module to add the apt/aptitude flag `--download-only` to allow for downloading packages without installing

Fixes #23220

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- apt.py

##### ADDITIONAL INFORMATION
#23220 is a long standing feature request for a useful edge case. Adding the `--download-only` flag will allow for users to download packages ahead of time.

Duplicate of closed #61500. I've refreshed pull request in hopes to correct labels and increase visibility

###### BEFORE
```ansible
---
- name: Install hello
  apt: 
    name: hello
    state: present
```
```log
TASK [Install hello] ******************************
changed: [testhost] => {"cache_update_time": 1590261291, "cache_updated": false, "changed": true, "stderr": "", "stderr_lines": [], "stdout": "Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  hello
0 upgraded, 1 newly installed, 0 to remove and 76 not upgraded.
```

###### AFTER
```ansible
- name: download hello without installing
  apt: 
    name: hello
    state: present
    download_only: true
```
```log
TASK [download hello without installing] ******************************
changed: [testhost] => {"cache_update_time": 1590261291, "cache_updated": false, "changed": true, "stderr": "", "stderr_lines": [], "stdout": "Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  hello
0 upgraded, 1 newly installed, 0 to remove and 76 not upgraded.
Need to get 27.4 kB of archives.
After this operation, 106 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 hello amd64 2.10-1build3 [27.4 kB]
Fetched 27.4 kB in 0s (108 kB/s)
Download complete and in download only mode
```

### CODE REVIEW

**Comment by Taoquitok** [comment]
ready_for_review

**Comment by paltaa** [comment]
Is there any way to use this feature without having to wait for the PR to be merged?

**Comment by Taoquitok** [comment]
> Is there any way to use this feature without having to wait for the PR to be merged?

Hey Paltaa, 
Yeah you can copy the apt.py file into your project and place it under a `library` folder in the top level of any play project that needs it
So something like: `/ansible/Library/apt.py`

Ansible-playbook will automatically pick up the apt_module under there.  
fyi, the version linked is for the bleeding edge devel. If you need this for a specific version do say and I'll chuck up a copy for you

**Comment by paltaa** [comment]
Great @Taoquitok, thank you very much for the quick reply, will try this and report back

**Comment by paltaa** [comment]
Worked like a charm in /library/apt.py, thanks! Also, is there a way to easily specify where to download the .deb?

**Comment by Taoquitok** [comment]
> Worked like a charm in /library/apt.py, thanks! Also, is there a way to easily specify where to download the .deb?

It'll go to the default apt cache location `/var/cache/apt/archives/`.   
#I think you can override that via the apt properties, but I wouldn't suggest it as apt uses that for everthing.  
Rather it's best to move/copy the file after downloading

**Comment by Taoquitok** [comment]
ready_for_review

**Comment by Taoquitok** [comment]
bot_status

**Comment by sivel** [comment]
This doesn't appear to properly handle change detection, in my tests it always reports `changed: true`

Change detection is handled on whether or not these strings appear in the output:

```
APT_GET_ZERO = "\n0 upgraded, 0 newly installed"
APTITUDE_ZERO = "\n0 packages upgraded, 0 newly installed"
```

With `--download-only` it is always reporting:

```
0 upgraded, 19 newly installed, 0 to remove and 8 not upgraded.
```

or 

```
0 packages upgraded, 18 newly installed, 0 to remove and 8 not upgraded.
```

I tested this using `vim`, with both `apt-get` and `aptitude`.

As such, it looks like work will have to be made to validate whether this caused the module to actually need to download something so that it's not reporting a change regardless of what is happening.

**Comment by Taoquitok** [comment]
Hey @sivel,

Thanks for the testing. It's correctly downloading/not downloading depending on check mode, but agreed that the output may need adjusting.

The native behaviour of aptitude/apt-get returns the change count prompt regardless of if the `-s` simulate flag is provided, and then depending on if it's apt or aptitude, you'll get some additional prompts (examples at end).  

I followed a similar pattern to other modules which can perform dry runs, and let it report "changed" as expected, with the understanding that no change has taken place, and followed the `apt` module's current practice of displaying some output

Saying that... to properly remain consistent to the current `apt:` check_mode, I could drop the log output, returning to the standard `changed: [host]` as current and nothing else, and then only include the apt output for `check_mode: false` ?

Example apt output:  
apt with simulate:
```log
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed
  hello
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Inst hello (2.10-1 Ubuntu:16.04/xenial [amd64])
Conf hello (2.10-1 Ubuntu:16.04/xenial [amd64])
```
apt without simulate:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed
  hello
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 27.3 kB of archives.
After this operation, 106 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 hello amd64 2.10-1 [27.3 kB]
Fetched 27.3 kB in 0s (119 kB/s)
Download complete and in download only mode
```
aptitude with simulate:
```log
The following NEW packages will be installed:
  hello
0 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.3 kB of archives. After unpacking 106 kB will be used.
Would download/install/remove packages.
```
aptitude without simulate:
```log
The following NEW packages will be installed:
  hello
0 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.3 kB of archives. After unpacking 106 kB will be used.
Get: 1 http://archive.ubuntu.com/ubuntu xenial/main amd64 hello amd64 2.10-1 [27.3 kB]
Fetched 27.3 kB in 0s (116 kB/s)
```

**Comment by Taoquitok** [comment]
@sivel,

Follow on to the above... Just double checked my code and I'm not actually putting in anything to prompt it to output to console... seems to just be happening... looking further into why

**Comment by Taoquitok** [comment]
@sivel 
Sorry for the spam..., just double checking the current apt behaviour and this is consistent with the latest, and previous, versions of ansible.  
Current behaviour with `apt:` in check mode:
```log
TASK [Install hello] ********************************************************************************************************************************************************************************************************************************************************************************************************
The following NEW packages will be installed:
  hello
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
changed: [localhost]
```

Seeing this, the behaviour with `download_only` is in keeping.  
  
Seeing this I'd argue the issue you've highlighted as being a separate bug to this feature, unless it's deemed necessary to review and fix at this point.  
  
This does beg a different question, assuming that the current live logging is appropriate, do we want an additional bit of logging to make it clearer that the package was _only downloaded_?

**Comment by sivel** [comment]
Ignore `check_mode` for the time being.

If this option cannot properly report change detection during an actual live execution, why does it need to be part of the module?

I can only see this being accepted if the module can properly report whether something was actually downloaded or not.  Otherwise, just use `command: apt-get install --download-only whatever` since it will always report `changed: true`.

Basically here is what I am talking about:

```yaml
- name: download hello without installing
  apt: 
    name: hello
    state: present
    download_only: true

- name: download hello without installing, this should not produce a change
  apt: 
    name: hello
    state: present
    download_only: true
  register: second
    
- assert:
    that:
      - second is not changed
```

The first time these tasks are run, the first should set `changed: true` as it just downloaded the files.  The 2nd time it should not, and should produce `changed: false`.  As it stands, no matter how many times you run the task with this PR, it will report that the module made a change, regardless if it actually downloaded anything.

You will need to make adjustments to the module for the above to actually happen, otherwise there is no reason to accept this PR.

**Comment by sivel** [comment]
Also, what I was trying to indicate in my previous comment, was that no matter how many times you run `apt-get` with `--download-only`, it *always* reports `N newly installed` regardless of whether it needed to download packages or not.

That is the problem. The change detection expects it to say `0 newly installed`.  That needs to be accommodated in this pull request, otherwise the module *always* reports a change, no matter if packages were downloaded or now.

**Comment by Taoquitok** [comment]
@sivel

Ah, I see what you mean. Never crossed my mind that that'd be an issue, but I do see why.
Thankfully the file on disk doesn't change even though apt-get/aptitude outputs that, so, I could add in some logic to compare lists of files matching the name before and after running the download and use that to dictate the changed state, plus tests to validate the behaviour

**Comment by nitzmahone** [comment]
closing as per above

**Pull request closed without merging**
