### PR TITLE
Revert "Add podman container module to ansible"

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

This reverts commit f01468a9d97f5af4ff61b3b7cac6e3f09015f791.

These integration tests are causing instability since they leave containers running bound to ports needed by later tests.

Additionally, this module needs major functional and architectural changes before it can be merged, such as:
- ~Using `+=` can result in O(n**2) operations. It is far slower than using other string formatting methods~
-  The module needs to have the capacity to evaluate different aspects of a running container, compare that to what is specified in the task, then bring the container to the desired state.
- The `construct_command_from_params()` function has a cyclomatic complexity of 94, which is far too complex.

```
("712:0: 'construct_command_from_params'", 94)
```

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/cloud/podman/podman_container.py`

### CODE REVIEW

**Comment by sshnaidm** [comment]
Removing leftovers - https://github.com/ansible/ansible/pull/58428

**Comment by sshnaidm** [comment]
@samdoran 

> Using += can result in O(n**2) operations. It is far slower than using other string formatting methods

Not sure why you meant string formatting methods, I don't use anywhere ``+=`` for strings, only for lists. In lists it's cheaper than "extend" function afaik. Where is O(n**2) here?

> The module needs to have the capacity to evaluate different aspects of a running container, compare that to what is specified in the task, then bring the container to the desired state.

If you mean idempotency for running containers, it's exactly what I started to do in second iteration. I left a "TODO" in "different" method about it.

> The construct_command_from_params() function has a cyclomatic complexity of 94, which is far too complex.

I suppose it's because we have 94 parameters. We can reduce parameters, but not sure it's the goal. Anyway we'll need to parse/check them.

**Comment by mattclay** [comment]
Another issue with the module is that it's setting `ansible_facts`:

https://github.com/ansible/ansible/blob/3fc0694ffc683423522199a39016684a031251f8/lib/ansible/modules/cloud/podman/podman_container.py#L1168

https://github.com/ansible/ansible/blob/3fc0694ffc683423522199a39016684a031251f8/lib/ansible/modules/cloud/podman/podman_container.py#L1220

Which is what is causing tests on https://github.com/ansible/ansible/pull/58428 to fail:

https://app.shippable.com/github/ansible/ansible/runs/129658/62/tests

**Comment by samdoran** [comment]
@sshnaidm 

> Not sure why you meant string formatting methods, I don't use anywhere += for strings, only for lists. In lists it's cheaper than "extend" function afaik. Where is O(n**2) here?

You're correct. I looked at this took quickly. That was an incorrect assessment. Sorry about that. 😊

> If you mean idempotency for running containers, it's exactly what I started to do in second iteration. I left a "TODO" in "different" method about it.

I would rather this be in the module before it is merged rather than left as a TODO.

> I suppose it's because we have 94 parameters. We can reduce parameters, but not sure it's the goal. Anyway we'll need to parse/check them.

Reducing the parameters isn't the goal, but rearchitecting the way the module leverages the parameters. This will be a pretty complex module due to the complexity of the underlying tool.

I would like to include a `podman_container` module in Ansible, but this needs further iteration and review.

**Comment by sshnaidm** [comment]
> I would like to include a podman_container module in Ansible, but this needs further iteration and review.

Then maybe we can collaborate on it and improve it instead of reverting it completely? It doesn't break users and it does its work.
Maybe I don't understand and break some Ansible development principles and my way of iterations is not compatible with them, while everything should be done at once. If so, I'm sorry, it wasn't obvious for me.

**Comment by felixfontein** [comment]
This kind of collaboration should not take place as commits in `devel` IMO. That's what PRs are for. First, if you keep the collaboration checkbox ticked, people with commit access to ansible/ansible (such as @sdoran) can push to your branch as well. Second, you can create PRs on PRs (by creating a PR on the branch which the PR wants to merge).

IMO (and I think that's the idea of the core team as well) everything in `devel` should be close to being release ready. A module where the most important part is missing (i.e. idempotence), and where a lot of things might be completely changed / rewritten before it is ready for release, should not be in `devel`, but in a branch. If the module would have very few options, but these would be a representative set of what kind of options there'd be, and everything else is implemented, having that in `devel` would be OK for me; then more options could be done by various people in new PRs. But for that, the module in `devel` should be in a polished enough state. And that's clearly not yet the case here.

**Comment by sshnaidm** [comment]
@felixfontein I see, I come from openstack field and it's an opposite there, usually we commit small changes step by step and release once a half year. But as I see it's different in Ansible development process. Thanks for explanation, it's more clear now.

**Comment by webknjaz** [comment]
@sshnaidm I support the idea of removing this and reworking properly, sorry that I merged it prematurely. I missed a few important things in the review and nobody seemed to have objections. Now it's clear that I overlooked a number of things and I recommend polishing this module first, before re-submitting.

**Comment by sshnaidm** [comment]
OK, fell free to revert it.

**Pull request merged**
