### PR TITLE
Remove local logic from os_server that's no longer needed

### PR DESCRIPTION
**Pull request by emonty**
##### SUMMARY
This logic has been supported in shade for a long time, we just haven't
gotten around to updating the module to stop having local copies of it.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
os_server

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/30753/2/tests

**Comment by emonty** [comment]
FYI to other reviewers - we're using this PR to test some zuul integration things - so it may sit here broken for a little while.

**Comment by mnaser** [comment]
recheck

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by Akasurde** [comment]
Closing as per above comment.

**Pull request closed without merging**
