### PR TITLE
no logging for service account contents

### PR DESCRIPTION
**Pull request by rambleraptor**
##### SUMMARY

Service Account Contents should not be logged.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

gcp_utils.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rambleraptor** [comment]
shipit

**Comment by rambleraptor** [comment]
bot_status

**Comment by jctanner** [comment]
bump

**Comment by jctanner** [comment]
Github gave an 500ISE when the bot tried to merge this.

**Comment by rambleraptor** [comment]
that's weird. I'll send another shipit in 10-15 to see if GitHub clears up.

**Comment by rambleraptor** [comment]
shipit

**Comment by sivel** [comment]
GitHub is having issues, I was able to get it merged though.

**Comment by rambleraptor** [comment]
awesome, thank you!

**Pull request merged**
