### PR TITLE
ec2_vpc: allow setting of dhcp options

### PR DESCRIPTION
**Pull request by willthames**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ec2_vpc

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel b8dd4dd52b) last updated 2017/01/17 16:30:08 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Add `dhcp_options` parameter to `ec2_vpc` module

### CODE REVIEW

**Comment by willthames** [comment]
I didn't actually write the code, I'm just submitting it on behalf of @mmochan 

As such I can say that the included change has been tested many times and meets my approvaal.

**Comment by mmochan** [comment]
@willthames I didn't write this code either.

**Comment by willthames** [comment]
@mmochan, oh oops - where did it come from?

**Comment by willthames** [comment]
Ah, found it: https://github.com/ansible/ansible-modules-core/pull/995/

**Comment by willthames** [comment]
Closing, looks like the code is in `ec2_vpc_net.py`.

**Pull request closed without merging**
