### PR TITLE
tower_workflow_template: Add missing options

### LINKED ISSUE #49728: tower_workflow_template extra_vars
##### SUMMARY
extra_vars not working for tower_workflow_template module.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_workflow_template.py

##### ANSIBLE VERSION
```
ansible 2.7.4
```

##### OS / ENVIRONMENT
CentOS 7.4

##### STEPS TO REPRODUCE

Create workflow as per example:
https://docs.ansible.com/ansible/latest/modules/tower_workflow_template_module.html#tower-workflow-template-module

Add "extra_var:" argument

```yaml
  tower_workflow_template:
  ...
     extra_vars:
        hello: world
  ...
```

##### EXPECTED RESULTS
Should create workflow with latest extra_vars

##### ACTUAL RESULTS

```paste below


Traceback (most recent call last):
  File "/home/lufimtsev/.ansible/tmp/ansible-tmp-1544457275.09-227335667154249/AnsiballZ_tower_workflow_template.py", line 113, in <module>
    _ansiballz_main()
  File "/home/lufimtsev/.ansible/tmp/ansible-tmp-1544457275.09-227335667154249/AnsiballZ_tower_workflow_template.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/lufimtsev/.ansible/tmp/ansible-tmp-1544457275.09-227335667154249/AnsiballZ_tower_workflow_template.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_tower_workflow_template_payload_THeAOl/__main__.py", line 191, in <module>
  File "/tmp/ansible_tower_workflow_template_payload_THeAOl/__main__.py", line 175, in main
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 698, in modify
    return self.write(pk, create_on_missing=create_on_missing, force_on_exists=True, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 1137, in write
    kwargs['extra_vars'] = parser.process_extra_vars(kwargs['extra_vars'])
  File "/usr/lib/python2.7/site-packages/tower_cli/utils/parser.py", line 130, in process_extra_vars
    opt_dict = string_to_dict(extra_vars_opt, allow_kv=True)
  File "/usr/lib/python2.7/site-packages/tower_cli/utils/parser.py", line 105, in string_to_dict
    'variables.\nvariables: \n%s' % var_string
tower_cli.exceptions.TowerCLIError: failed to parse some of the extra variables.
variables:
{
```

### PR DESCRIPTION
**Pull request by albertomurillo**
##### SUMMARY
tower_workflow_template: Add missing options

The following options can be set on a workflow template but the
functionallity to do so from this module was missing.

inventory
ask_variables_on_launch
ask_inventory_on_launch

Fixes #49728

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
tower_workflow_template

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by AlanCoding** [comment]
shipit

**Comment by albertomurillo** [comment]
shipit

**Comment by albertomurillo** [comment]
cc @LeoUfimtsev @Moumoutaru

**Comment by kdelee** [comment]
shipit

**Pull request merged**
