### PR TITLE
opennebula  inventory script

### PR DESCRIPTION
**Pull request by marcindulak**
##### SUMMARY

OpenNebula dynamic inventory script based on https://github.com/OpenNebula/addon-pyone API.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

contrib/inventory/opennebula.py

##### ANSIBLE VERSION

https://github.com/ansible/ansible/commit/f2b65fc5fe6b17ea51bb2fdd5e151edae1b2dc4b

##### ADDITIONAL INFORMATION

The inventory script uses https://github.com/OpenNebula/addon-pyone, but there exists also
an alternative https://github.com/python-oca/python-oca, which does not seem actively  maintained.
On the other hand an opennebula module based on https://github.com/python-oca/python-oca (?) has been commited to ansible recently https://github.com/ansible/ansible/blob/01280226549b350da7f837d57067097a9b445d45/lib/ansible/modules/cloud/opennebula/one_vm.py. In case when https://github.com/python-oca/python-oca resumes activities, contrib/inventory/opennebula.py could be extended to work with both APIs.

### CODE REVIEW

**Comment by howels** [comment]
Any plans to merge this? Looks like a useful PR.

**Comment by burlito** [comment]
Hi,

Is there any current reason why this pull-request is not merged or declined (or talked about)?

**Comment by marcindulak** [comment]
As far as I remember the submission of this inventory script happened after ansible officially stopped accepting inventory scripts and moved to inventory plugins. I'm not sure what's the state of the plugins today 
https://github.com/ansible/ansible/issues/68419. There were some discussions about rewriting the inventory script into a plugin, whose I cannot find anymore, maybe in the https://github.com/OpenNebula/addon-pyone repo which has the issues not visible anymore.

**Comment by marcindulak** [comment]
It may be worth checking with the author of https://github.com/hamidyousefi/opennebula_inventory in order to get the inventory (plugin/collection?) into ansible.

**Pull request closed without merging**
