### PR TITLE
now exceptions are 'old time python' compatible

### PR DESCRIPTION
**Pull request by bcoca**
as per comment in #5852

Signed-off-by: Brian Coca <briancoca+dev@gmail.com>

### CODE REVIEW

**Comment by jimi-c** [comment]
@bcoca could you rebase this?

**Comment by bcoca** [comment]
@jimi-c done

**Comment by jimi-c** [comment]
Thank you sir, in queue for testing.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
