### PR TITLE
#10530 disable cowsay by default

### PR DESCRIPTION
**Pull request by chriskite**

### CODE REVIEW

**Comment by srgvg** [comment]
:-1:

**Comment by bcoca** [comment]
this seems to have syntax errors as per travis build

**Comment by willthames** [comment]
Not sure why you'd change the variable name rather than changing the value of the default (which will break people's existing configurations and settings)

**Comment by conrado** [comment]
I believe using ansible means customizing so many settings, changing this behavior is irrelevant.

**Comment by amenonsen** [comment]
The syntax error has been fixed, but the code has drifted. I think the PR should be closed. I'm not fond of cowsay at all, but a PR that changes default configuration with no attempt to provide some kind of rationale (not even "I hate cows") is just a waste of time.

**Comment by bcoca** [comment]
```
 __________________________________                                                                                                                                                                      
< Closing for reasons stated above >                                                                                                                                                                     
 ----------------------------------                                                                                                                                                                      
        \   ^__^                                                                                                                                                                                         
         \  (oo)\_______                                                                                                                                                                                 
            (__)\       )\/\                                                                                                                                                                             
                ||----w |                                                                                                                                                                                
                ||     ||  
```

**Comment by chriskite** [comment]
@amenonsen It looks like you didn't read the linked issue: https://github.com/ansible/ansible/issues/10530

**Pull request closed without merging**
