### PR TITLE
Support for postgresql default privileges

### LINKED ISSUE #29701: Add support to postgresql_privs for ALTER DEFAULT PRIVILEGES
From @sfilipov on 2016-08-22T09:47:02Z
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

postgresql_privs
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

Currently `postgresql_privs` module does not support `ALTER DEFAULT PRIVILEGES`. This is a feature request to add such an option.

https://www.postgresql.org/docs/9.4/static/sql-alterdefaultprivileges.html

Copied from original issue: ansible/ansible-modules-core#4493

### PR DESCRIPTION
**Pull request by vfoucault**
##### SUMMARY

Fixes #29701 and #23657

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

* postgresql_privs
##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/vianneyfoucault/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/vianneyfoucault/anaconda2/lib/python2.7/site-packages/ansible
  executable location = /Users/vianneyfoucault/anaconda2/bin/ansible
  python version = 2.7.13 |Anaconda, Inc.| (default, Sep 21 2017, 17:38:20) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

##### ADDITIONAL INFORMATION

- The ALTER DEFAULT PRIVILEGES is implemented with type 'default_privs'
- Added a Query Builder for simplification
- Some minor lint

```

```

### CODE REVIEW

**Comment by vfoucault** [comment]
bot_status

**Comment by Akasurde** [comment]
@vfoucault Could you please add integration tests for your change - [here](https://github.com/ansible/ansible/tree/devel/test/integration/targets/postgresql/tasks) ?

**Comment by alivespirit** [comment]
Are there any updates on this? We really need to alter default privileges in our case and we have to do it using `shell` for now...

**Comment by vfoucault** [comment]
Hello.

Ain't got no time to update tests, so far. Fell free to write them.

My code is in production for several month now and working fine.

Tell me if you need help writing tests.

Regards

**Comment by anasbouzid** [comment]
Thanks for supporting this feature. I'm wondering if there is a simple way to add the optional
[`[ FOR { ROLE | USER } target_role [, ...] ]`](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html) syntax
Edit: A workaround is to specify the target role in the schema `schema: public FOR ROLE postgres,my_role`

**Pull request merged**
