### PR TITLE
powershell: Add support for list parameters

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This is a first implementation of list parameters.

It will convert a single string, or comma-separated value into an Array.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

powershell

##### ANSIBLE VERSION

v2.3

### CODE REVIEW

**Comment by dagwieers** [comment]
Shippable error unrelated to changes. Windows tests take longer than VM lifetime.
https://app.shippable.com/github/ansible/ansible/runs/17713/9/console

**Comment by jhawkesworth** [comment]
Nice feature.
I wondered if it ought to support some other delimiters (like | as used in win_iis_webapppool but... may as well keep it simple for now (I don't actually know if python args have similar).

shipit

**Comment by dagwieers** [comment]
Close and reopen to redo Shippable run.

**Comment by jborean93** [comment]
would be good to have, I know there are a few modules where I've got this logic in there manually. One thing that would be great to have is to specify the type of elements in the list, i.e. it's a list of paths so it expands the strings but simple is good :)

shipit

**Comment by dagwieers** [comment]
@jborean93 I agree it would be useful to indicate the type of list-elements, however I don't think there's an implementation for Python modules. And I did not want to introduce new capabilities in the Windows modules.

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
