### PR TITLE
Docs for module_defaults feature

### PR DESCRIPTION
**Pull request by agaffney**
##### SUMMARY
This commit adds some documentation for the `module_defaults` feature (added in #22648)

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docs

##### ANSIBLE VERSION
N/A

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
It may very well be, but how is this different then: `https://github.com/ansible/ansible/commit/e526743b4f91a571f48bff4280ce5e441f72a292#diff-76ffc0551f8cf3d6255500316568e60bR242`

**Comment by agaffney** [comment]
That particular feature is deprecated and requires something explicit to use in each task. It also doesn't allow for easily providing some default arguments while explicitly specifying others.

The `module_defaults` feature has already been merged, and this PR is just to add documentation for it.

**Comment by itdependsnetworks** [comment]
Not trying to roll back the updates, it was my understand the other implementation was removed since you could dynamically create args, and thus considered unsafe. This to me would seem to fall in the same bucket. 

Again, not questioning the decision, just trying to understand.

**Comment by agaffney** [comment]
I do not know the reasoning for the other feature being deprecated, but frankly, it's a little late to question the inclusion of the `module_defaults` feature. It was well debated and generally agreed upon by the Ansible core devs. This PR is just a follow-up to add docs for the feature, since they weren't included in the original PR.

**Comment by itdependsnetworks** [comment]
I think something is getting lost in translation, I am not making a case on anything. I am simply looking for information. I think I can more succinctly ask my question as such: 

- Does this allow for dynamic inclusion of arguments into a module?
- If so, does that present a risk?

Perhaps it was my misunderstanding of the other referred issue (dynamic args to module is not unsafe) and/or perhaps this is not applicable at all (there is no way to dynamically include arguments), but I am simply trying to get information.

**Comment by agaffney** [comment]
The `module_defaults` feature does have some of the same potential for abuse, but it's "safer" because it must be explicitly configured in the playbook rather than just being able to change the value of a variable. There was some resistance from some of the same folks that didn't like the other feature, but it was acknowledged that the feature is almost necessary for some cases and that this implementation is the "best" combination of explicit definition and magic.

**Comment by itdependsnetworks** [comment]
Thanks for the clarification!

tbh, this is a welcome feature, as I can get similar functionality.

**Comment by maxamillion** [comment]
rebuild_merge

**Pull request merged**
