### PR TITLE
Correct python module name for jinja2

### PR DESCRIPTION
**Pull request by jblaine**

### CODE REVIEW

**Comment by mpdehaan** [comment]
On Fedora it's python-jinja2

We should probably just mention it may be different based on OS.

**Comment by jblaine** [comment]
The point of the PR and patch was to reference them by the Python module name (which is known to be a single thing), not any OS-specific package name.

**Comment by jblaine** [comment]
Did you even look at the diff?

**Comment by mpdehaan** [comment]
I missed that top line.  My fault.

But please don't assume I didn't TRY to read it.  I'm just busy :)

**Comment by mpdehaan** [comment]
merged, thanks!  will be in next push

**Pull request merged**
