### PR TITLE
New module swap: manage activation and deactivation of swap partitions

### PR DESCRIPTION
**Pull request by shatQ**
##### SUMMARY
Aim of this module is provide idempotent way of activation and deactivation swap partitions, including modification of fstab. This request is continuation of PR [#49390](https://github.com/ansible/ansible/pull/49390).

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
swap

### CODE REVIEW

**Comment by gundalow** [comment]
@jtyr Would welcome your views on this

**Comment by jtyr** [comment]
@gundalow I have provided my opinion in the previous PR (https://github.com/ansible/ansible/pull/49390#issuecomment-443889372).

**Comment by shatQ** [comment]
@jtyr Regarding to your [comment](https://github.com/ansible/ansible/pull/49390#issuecomment-443889372), I agree that it's not so difficult add support for swap in `mount`, but doing that will make it more complex and as you said mount already does a lot.  What I'm missing in `mount ` is lack of flexibility.

What whould you say for idea of re-working `mount `to make it modular? I'm thinking about similar pattern as is used in `filesystem`, for example:
- generic class for platform with common functionallity
- separate classes per each type of platform with specific methods
- helper class for managing fstab updates

That approach would improve code readability and make it more friendly for contributors which would like to enxtend it for new platforms.

**Comment by jtyr** [comment]
@shateq PRs improving the `mount` module are more than welcome.

**Pull request closed without merging**
