### PR TITLE
rm developing_modules_general_OLD.rst

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY

rm developing_modules_general_OLD.rst
Causes lots of warnings.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

docs/docsite/rst/dev_guide/developing_modules_general_OLD.rst

##### ANSIBLE VERSION

```
ansible 2.5.0 (rst_yaml_jinja_lex_warning 3867afb172) last updated 2017/09/12 17:42:27 (GMT -400)
  config file = /home/adrian/src/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
Hum, so there is a load of content that's only on this page, so -1 to this at the moment

**Review by gundalow — CHANGES_REQUESTED** [review]
-1

**Comment by alikins** [comment]
As far as I can tell, this doc isn't linked from any other docs, so not sure how someone would discover it. The doc does get rendered as html albeit with some errors (see http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general_OLD.html). But there doesn't appeak to be any links to it from the rest of the docs.

**Comment by gundalow** [comment]
Correct, please leave as is for the moment

**Comment by alikins** [comment]
Renamed to use ._rst suffix so we dont try to build this doc by default.

**Pull request closed without merging**
