### PR TITLE
docker_service: rename to docker_compose.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
As discussed in #408 ([original suggestion](https://github.com/ansible/ansible/pull/50428#issuecomment-451687999) by @WojciechowskiPiotr), this PR renames the `docker_service` module to `docker_compose`.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
docker_service
docker_compose

### CODE REVIEW

**Comment by felixfontein** [comment]
TODO: directly after merge, add `!component =lib/ansible/modules/cloud/docker/docker_compose.py` to all issues for `docker_compose` (see [here](https://ansibullbot.eng.ansible.com/metadata/byfile_sorted.html) for a list).

**Comment by felixfontein** [comment]
ready_for_review

**Comment by jctanner** [comment]
@felixfontein ping us on irc whenever you want this merged. The core support label is due to the filename change, but this is still definitely "community" support.

**Comment by felixfontein** [comment]
@jctanner I think the core support label is there because the PR touches docs/docsite/rst/scenario_guides/guide_docker.rst and test/sanity/code-smell/no-underscore-variable.py. I guess since nobody complained for half a week, it's time to merge this. I'll ask on IRC.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@felixfontein Thank you for this

**Comment by felixfontein** [comment]
@jctanner @gundalow thanks for your comments and for merging!

**Pull request merged**
