### PR TITLE
Fix for issue #4730 - stacktrace when deferenencing a non-existent group

### PR DESCRIPTION
**Pull request by janeznemanic**
Added exception handling for bug reported in issue #4730. My first pull request so I apologize if it is a little messy.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Yeah please resubmit this as a single commit.

You may wish to look into topic branches in git as well as how to do a squash merge of your existing branch.

Thanks!

**Comment by janeznemanic** [comment]
Will do that.

**Comment by jctanner** [comment]
@janeznemanic any chance you could get this squashed down to one commit?

**Comment by janeznemanic** [comment]
@jctanner Could you have a look at this pull request https://github.com/ansible/ansible/pull/5131 . It is the same fix as this one here but just one commit. I really apologize for the whole mess. I'm newbie to github and git and I am still struggling with these tools.

**Comment by jctanner** [comment]
@janeznemanic we just need to close this one then.

**Pull request closed without merging**
