### PR TITLE
DEFAULT_MODULE_PATH in setup.py

### PR DESCRIPTION
**Pull request by skyl**
Using `DEFAULT_MODULE_PATH` in setup.py allows for the use of `ANSIBLE_LIBRARY` environment variable to set the location of the install.

### CODE REVIEW

**Comment by jimi-c** [comment]
What exactly is it about that option that makes it unsuitable for your needs? We generally don't like adding duplicate functionality like this.

**Comment by mpdehaan** [comment]
James is referring to the ANSIBLE_LIBRARY environment variable.

**Comment by skyl** [comment]
Can we use ANSIBLE_LIBRARY to define where setup.py installs the modules?

**Comment by mpdehaan** [comment]
I'm not really wanting to change that.

If you want to run locally you can do that by checking out and doing "source ./hacking/env-setup".

**Comment by mpdehaan** [comment]
I've decided to listen to reason as this really doesn't hurt anything :)

Done!

You may also be interested in "source ./hacking/env-setup" as an easy way to run from checkout without installation.

**Comment by skyl** [comment]
Cool! I contributed something to ansible! I was probably just going to sed this in, if need be. Much better for me to have it officially in.

**Pull request merged**
