### PR TITLE
Speedup inventory

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

hopefully faster w/o being wrong
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

inventory
##### ANSIBLE VERSION

```
2.4/2.5
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in sanity, unit and integration tests. Here's one of the unit test failures:

```
>       for group in self._groups:
E       RuntimeError: Set changed size during iteration

lib/ansible/inventory/host.py:107: RuntimeError
```

**Comment by mattclay** [comment]
CI failure in `test/integration/targets/var_blending/roles/test_var_blending/tasks/main.yml:21`:

```
failure: AnsibleUndefinedVariable: 'groups_tree_var' is undefined
```

**Comment by willthames** [comment]
@bcoca I'm getting AttributeError from host.__hash__, bisecting took me to this patch. I'm struggling to debug it to work out what's going on. Absolutely nothing obvious in debug output

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/will/src/ansible/lib/ansible/plugins/strategy/__init__.py", line 84, in results_thread_main
    result = strategy._final_q.get()
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/home/will/src/ansible/lib/ansible/inventory/host.py", line 37, in __setstate__
    return self.deserialize(data)
  File "/home/will/src/ansible/lib/ansible/inventory/host.py", line 82, in deserialize
    g.deserialize(group_data)
  File "/home/will/src/ansible/lib/ansible/inventory/group.py", line 77, in deserialize
    self._hosts = set(self.hosts)
  File "/home/will/src/ansible/lib/ansible/inventory/host.py", line 48, in __hash__
    return hash(self.name)
AttributeError: 'Host' object has no attribute 'name'
```

I can't share my inventory I'm afraid, and I am not having much luck finding the source of the issue or creating a simple reproduction of the issue.

The problem starts with `__setstate__`, as `data` has the problem

```
print data['groups'][1]['hosts'][1].__dict__
{}
```

I'm not really sure how to look further back into what's going on to diagnose why the data is bad.

**Comment by willthames** [comment]
Managed to reduce the problem to a simple test case: #30903

**Pull request merged**
