### PR TITLE
Configure retry file usage and location

### PR DESCRIPTION
**Pull request by tartansandal**
New configuration settings: 

retry_files_enabled = True
retry_files_save_path = '$HOME/.ansible-retry'

### CODE REVIEW

**Comment by johnhamelink** [comment]
:+1: would love to see this merged - those .retry files are quite annoying, yet useful enough that I don't want to see them go! :smile:

**Comment by resmo** [comment]
+1 but IMHO retry_files_enabled = True should be the default

**Comment by tartansandal** [comment]
retry_files_enabled = True is the default.

K

**Comment by fesplugas** [comment]
:+1:

**Comment by kuba** [comment]
Regarding the destination of the *.retry files there are couple of things I'd like to discuss, some of which might require general design decision changes accepted by @mpdehaan:
1. Extending the argument from https://github.com/ansible/ansible/pull/5515#commitcomment-5294095 **retry files are just temporary** stuff. What about using [Python's tempfile module](http://docs.python.org/2/library/tempfile.html) instead? It provides sane security defaults, is cross system, doesn't clutter up $HOME, etc. Also, with the current patch approach, it's not possible to achieve this random file destination functionality, whereas it would be easy to reset it to `$HOME/.ansible-retry` easily.
2. What if `$HOME` is not defined? ;)
3. If you do not agree with the first point, then maybe let's at least create `~/.ansible/` for all Ansible related stuff, including `~/.ansible/retry`.

Happy to hear your comments! I hope you will not tell me off for not writing this on the mailing list.

**Comment by rwehner** [comment]
+1. This would be useful for my set up.

**Comment by tartansandal** [comment]
Hi Jakob,

I'll just note that we do do `os.path.expandvars('$HOME/.ansible-retry')` but in a different location.  See line 485 of `lib/ansible/playbook/__init__.py`. I choose this location to be consistent with the surrounding code in both locations.  Also note that a helpful non-fatal warning message is generated if the file cannot be created and notes about ensuring that the directory exists are made in the sample configuration file. 

Other comments to go on the devel mailing list when I get a chance.

**Comment by kuba** [comment]
@tartansandal I made an error and you missed the point.

I meant: `os.path.expandvars(C.RETRY_FILES_SAVE_PATH) == os.path.expandvars('$HOME/.ansible-retry')` check in that line.

Now, consider the following situations:
1. Leave the default variables. If `$HOME/.anisble-retry` doesn't exist Ansible creates it.
2. Set `retry_files_save_path = $HOME/.ansible-retry`. Same behaviour as in 1.
3. Set `retry_files_save_path = /home/kuba/.ansible-retry`. If `/home/kuba/.ansible-retry` doesn't exist, Ansible yells at me.
4. Set `retry_files_save_path = ~/.ansible-retry`. Same fail as in 3.

Personally, I find this behaviour confusing. I'd expect it to create `/home/kuba/.ansible-retry` in any of the cases.

**Comment by tartansandal** [comment]
Yeah, I do get your point and have thought about it in the past.  There are other cases involving soft-links and and whether there is a trailing slash.  The current specification (and what is implemented) is that ansible will create the directory only if the default "value" has not been changed.  The comment in the sample configuration indicates that, if you change the default, then its your responsibility to make sure it exists.  There was a desire to keep the implementation as simple as possible and to not introduce unnecessary code paths.

**Comment by mpdehaan** [comment]
All the test-playbook stuff is now obsolete now so this is due for a rebase.  I am still open to this being user configurable, but this would need to be resubmitted.

Thanks!

**Comment by alozovskoy** [comment]
@mpdehaan, It's not worked in 1.7 version. bin/ansible-playbook and lib/ansible/constants.py does not contain changes from this issue (perhaps other changes from this commit does not exist in Ansible code now).

**Comment by mmoya** [comment]
@tartansandal are you planning to resubmit this ?

**Comment by tartansandal** [comment]
I was,  but I never found time. Feel free to run with it if you want.

**Comment by mmoya** [comment]
@tartansandal ok, will take care of this.

**Comment by sruon** [comment]
Any update on this? Will help if required.

**Comment by mmoya** [comment]
Resubmited as #9404, let's continue discussion there.

**Pull request closed without merging**
