### PR TITLE
WIP: win_dns_record + patches

### LINKED ISSUE #51923: FeatReq: Add support for DNS record management on Windows DNS Server
##### SUMMARY
Add a `win_dns_record` module for managing DNS records in Windows DNS server (ie usually extra records in an AD environment).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_dns_record (proposed)

##### ADDITIONAL INFORMATION

Active Directory has unique dependencies on DNS -- so much so that it requires its own, dedicated DNS system to work effectively. For some organizations, it may even be their primary DNS platform. Thus support for managing records within that system is sought.

### PR DESCRIPTION
**Pull request by Daniel-Sanchez-Fabregas**
##### SUMMARY

Fixes #51923
##### ISSUE TYPE

   * Feature Pull Request

##### COMPONENT NAME

win_dns_record
##### ADDITIONAL INFORMATION

Add patches to an existing PR #51925.
(Asked at #ansible-windows and recommended to add this PR, but open to more instructions)

### CODE REVIEW

**Comment by Daniel-Sanchez-Fabregas** [comment]
@angystardust In this PR, CNAME idempotency works for me (fixing https://github.com/ansible/ansible/pull/51925#issuecomment-462695899).

I have done minor changes I hope that are OK:
* 9cf5f2d8e6 Refactorize diff and changed to read DNS end state: Now diff is colorized and the state is calculated reading with `Get-DnsServerResourceRecord` after the changes.
* 7ddffe4723 Add computer_name parameter: Allow to choose the DNS server. 
* 6136ed6a1e Refactorize check mode: Cosmetic changes `if (-not $check_mode)` => `-WhatIf:$check_mode`

**Comment by angystardust** [comment]
Tested and works great! :+1:

**Comment by it-praktyk** [comment]
@Daniel-Sanchez-Fabregas, can you explain a relation between the current PR and the PR https://github.com/ansible/ansible/pull/36493?

Thank you.

**Comment by Daniel-Sanchez-Fabregas** [comment]
I liked more @johnboy2 PR #51925 than my initial PR #36493.
It's simple and with more record types.

**Comment by angystardust** [comment]
One minor glitch: in check-mode, the module always report an `ok` status even if I'm trying to register an A record which doesn't exist

**Comment by Daniel-Sanchez-Fabregas** [comment]
Thanks for the check @angystardust 

(I'm trying now to generate integration tests).

**Comment by Daniel-Sanchez-Fabregas** [comment]
Seems that integration tests are taken care of in 90995a072d57da472085d266ae7dd9d89ea5550f and this changes are merged in the initial PR.
This PR is redundant.

**Pull request closed without merging**
