### PR TITLE
This module allows users to manage partitions on a BIG-IP

### PR DESCRIPTION
**Pull request by caphrim007**
##### SUMMARY
Adds module which allows users to manage partitions on a BIG-IP

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/network/f5/bigip_partition.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 18 2017, 20:47:33) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION
* Unit tests included
* Functional tests included

### CODE REVIEW

**Comment by caphrim007** [comment]
@gundalow ready for review

**Comment by gundalow** [comment]
Do we have the ability to run bigip integration tests in shippable?

**Comment by caphrim007** [comment]
No, I was just including them for completeness. Should I remove them?

**Comment by gundalow** [comment]
@caphrim007 You can remove them as they are in your repo and run by you.

**Comment by caphrim007** [comment]
@gundalow, there are functional tests for configsync actions as well. remove those?

**Comment by gundalow** [comment]
Keep the unit tests as we can run them via Shippable.

`test/integration/targets` is for tests at can run via Shippable.

Even when we move to using DCI (Distributed CI) we will need able to run integration tests from the F5Networks repo.

**Comment by caphrim007** [comment]
@gundalow ok, pushed changes. waiting for shippable to finish. then ready for review

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel`, will be releases in `2.5.0`

**Pull request merged**
