### PR TITLE
Import pass.py from github.com/morphje/ansible_pass_lookup

### PR DESCRIPTION
**Pull request by sigio**
##### ISSUE TYPE
- New Lookup Plugin Pull Request
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

Adding a 'password-store' lookup plugin, which allows one to query or create passwords with
a specified length and store these with 'pass'

Plugin is/has been developed at https://github.com/morphje/ansible_pass_lookup

### CODE REVIEW

**Comment by bcoca** [comment]
just some bikeshedding,  rename to `passwordstore` to make sure it is not ambiguous and clearly tied to the service.

**Comment by sigio** [comment]
The unix command to interact with passwordstore is pass... which is also the original name from before a website existed. Website is passwordstore.org, but most people refer to it as pass.

From the manpage: 'Pass - The Unix Password Manager'

I myself would prefer 'pass' as this is also significantly shorter, but given that more tools would probably be around that do things with passwords, I can understand the need to maybe rename this.

**Comment by dagwieers** [comment]
Hmm, the name is a difficult one. Just "pass" may seem ambiguous, however anything else but "pass" is simply incorrect and confusing (as a pass user). Personally I would stick to "pass".

**Comment by morphje** [comment]
@bcoca I've added a passwordstore.py to my repo, renaming it as requested. I've also cleaned up the code a bit. I'm not sure on how to update this pull request to change over to the new file?
New commit: https://github.com/morphje/ansible_pass_lookup/commit/d83c20cec4cf3f8e4bc51a21cd505dce0bcf17f7 

also tested it with ansible 2.2.1

**Comment by dagwieers** [comment]
@morphje Either you do a PR to sigio's branch that he than has to merge. Or you create a new PR and put in that one: "This closed #XYZ" so this PR gets closed automatically if yours gets merged.

You could also ask sigio to integrate your changes in his branch if you think that is easier ?

**Comment by morphje** [comment]
@dagwieers  since it's my repo that sigio cloned before he had access to it,  i'll just close this one and create a new pull request. Thanks.

**Comment by bcoca** [comment]
closing in favor of #21314

**Pull request closed without merging**
