### PR TITLE
create install_options parameter for homebrew module

### PR DESCRIPTION
**Pull request by renanivo**
This parameter enable homebrew option flags. Ex:

``` yml
- name: install wget
  homebrew: name=wget state=present install_options=enable-debug,enable-iri
```

It executes:

``` bash
brew install wget --enable-debug --enable-iri
```

### CODE REVIEW

**Comment by fesplugas** [comment]
Awesome I was looking for this option right now.

:+1:

**Comment by mpdehaan** [comment]
This looks good to me, thanks!

One small things for the module docs if you can please update this...

Add the "version_added" attribute for the parameter, so it will show up in the docs as new in 1.4:

```
version_added: "1.4"
```

This may users still on 1.3 won't try the command and be confused as to why it's not there.

Thanks!

**Comment by renanivo** [comment]
@mpdehaan well thought out. Already done. 

Thanks

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
