### PR TITLE
become: Add missing documentation for pfexec, dzdo and machinectl

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docs/bin/plugin_formatter.py
lib/ansible/plugins/become/pfexec.py

### CODE REVIEW

**Comment by gundalow** [comment]
@Akasurde Could you please include an example of the error message here

**Comment by Akasurde** [comment]
```
# PYTHONPATH=../../lib ../bin/plugin_formatter.py -t rst --plugin-type become --template-dir=../templates --module-dir=../../lib/ansible/plugins/become -o rst -v
Evaluating become files...
Generating rst
Generating plugin pages
about to template doas
about to template dzdo
about to template enable
about to template ksu
about to template machinectl
about to template pbrun
about to template pfexec
Traceback (most recent call last):
  File "../bin/plugin_formatter.py", line 774, in <module>
    main()
  File "../bin/plugin_formatter.py", line 761, in main
    process_plugins(plugin_info, templates, outputname, output_dir, options.ansible_version, plugin_type)
  File "../bin/plugin_formatter.py", line 557, in process_plugins
    text = templates['plugin'].render(doc)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "../templates/plugin.rst.j2", line 112, in top-level template code
    {% for key, value in options|dictsort recursive %}
  File "../templates/plugin.rst.j2", line 172, in template
    {% for env in value.env %}
TypeError: 'NoneType' object is not iterable
```

**Review by bcoca — APPROVED** [review]

**Comment by bcoca** [comment]
I agree, this should not be a fatal error, not all plugins are required to populate ALL possible configuration avenues ... its just nice that they do.

**Review by samccann — APPROVED** [review]
docs portion LGTM

**Comment by Akasurde** [comment]
@bcoca @samccann Thanks for the review.

**Pull request merged**
