### PR TITLE
Add Foreman to list of Dynamic inventories

### PR DESCRIPTION
**Pull request by dLobatog**
##### SUMMARY
Add Foreman to the list linking to the docs. If necessary, I could move the documentation in https://github.com/theforeman/foreman_ansible_inventory/ to this page. 

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
Dynamic inventories

##### ANSIBLE VERSION
2.2 onwards

### CODE REVIEW

**Comment by dLobatog** [comment]
Anything I can do here @dharmabumstead @docschick?

**Comment by bcoca** [comment]
@dLobatog curios on why you don't link to the one included with Ansible? https://github.com/ansible/ansible/blob/devel/contrib/inventory/foreman.py

Also, I've derived an 'inventory plugin' which will be able to reduce the specific code and leverage shared infrastructure here #25565

**Review by dharmabumstead — APPROVED** [review]

**Comment by dLobatog** [comment]
I can link to the one in ansible/ansible - that repository is just meant to mirror the one in ansible/ansible and provide a README with links to the manual on how to use it. I don't have any preference, https://theforeman.org/plugins/foreman_ansible/ could also be a good fit.

It's the first time I hear about inventory plugins, let me check it out @bcoca 😄

**Review by dLobatog — COMMENTED** [review]
Any updates here?

**Review by dharmabumstead — CHANGES_REQUESTED** [review]
Please revise so that it's in the same format as the rest of the list. Suggestion:  

  `Foreman <http://www.python.org/>`_ / Satellite 6  

(Github won't display this comment correctly without interpreting it as markdown formatting. See [this](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#internal-and-external-links) for how to add proper links in RST.)

**Comment by dharmabumstead** [comment]
@bcoca please review and either merge or close.

**Review by dharmabumstead — APPROVED** [review]

**Review by dharmabumstead — APPROVED** [review]
Docs OK with edits.  Needs core team sign off.

**Review by dLobatog — COMMENTED** [review]
Thanks @dharmabumstead for the edit

**Review by dLobatog — COMMENTED** [review]
Anything missing here?

**Comment by dharmabumstead** [comment]
Please feel free to rebase and reopen.

**Pull request closed without merging**
