### PR TITLE
add docker module

### PR DESCRIPTION
**Pull request by cove**
Let me know if any changes/fixes are required. Thx!

Ref: https://github.com/cove/docker-ansible/issues/3

### CODE REVIEW

**Comment by mpdehaan** [comment]
Haven't had time to review yet, but thanks.

First thing I noticed:
-    with_items: $DockerContainers

This should be written as just:

```
 with_items: docker_containers
```

As loops and conditionals need not rely on template evaluation.

Examples should use with_underscores and not camel_case also.

**Comment by cove** [comment]
Thanks to @exell-christopher for suggesting some better names for the class in this module.

**Comment by thijsterlouw** [comment]
:+1:  nice work. I have raised an issue with CoreOS guys about adding Python back, so this can be used in combination with CoreOS

**Comment by resmo** [comment]
+1

**Comment by jctanner** [comment]
@cove thank you!

**Comment by cove** [comment]
@jctanner yep! thanks.

**Comment by jmonteiro** [comment]
awesome job! :)

**Comment by keybits** [comment]
Great to see this in Ansible core - very handy module! Thanks to @cove for the hard work on it and fixing issues promptly.

**Comment by sritchie** [comment]
Hey guys, what's the best way to specify a port mapping to UDP in this new system? I've tried `ports=[(5555,', 'udp),', '5555]`, but that looks incorrect.

**Comment by jctanner** [comment]
@sritchie send your question to the ansible-project mailing list please.

**Pull request merged**
