### PR TITLE
postgresql: move CI test of *_publication, *_ext, *_slot to separate targets

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql: move CI test of *_publication, *_ext, *_slot to separate targets

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
postgresql_publication
postgresql_slot
postgresql_ext

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by kostiantyn-nemchenko — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Review by andytom — APPROVED** [review]
LGTM, shipit

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko @andytom thank you for approving!

**Review by gundalow — APPROVED** [review]

**Pull request merged**
