### PR TITLE
parse_address: add an option to return valid IP addresses

### LINKED ISSUE #84178: add param for parse_address() function
### Summary

In the common function parseaddress(), the validation of IPv4 addresses does not seem to be effective, as shown in the following example code:
```
>>> from ansible.parsing.utils.addresses import patterns
>>> ipv4_pattern = patterns['ipv4']
>>> ipv4_pattern.match("30.251.3.[a:e]")                # match failed
>>> from ansible.parsing.utils.addresses import parse_address
>>> parse_address("192.168.[1:20].11[1:3]", True)  # match success because of patterns['hostname']
('192.168.[1:20].11[1:3]', None)
```

so, can we add a param like only_ips to control the validation of ip addresse only？i add some code in parseaddress() as follows：
```
def parse_address(address, allow_ranges=False, only_ips=False):

    port = None
    for matching in ['bracketed_hostport', 'hostport']:
        m = patterns[matching].match(address)
        if m:
            (address, port) = m.groups()
            port = int(port)
            continue
    
    ###########################################
    check_ps = ['ipv4', 'ipv6', 'hostname']
    if only_ips:   
        # only check ip address
        check_ps.pop()
    ###########################################
           
    host = None
    for matching in check_ps:
        m = patterns[matching].match(address)
        if m:
            host = address
            continue
    
    ###########################################   
    if not host and only_ips:
        raise AnsibleError("Not a valid ipv4 or ipv6 address: %s" % address)
    ###########################################

    # If it isn't any of the above, we don't understand it.
    if not host:
        raise AnsibleError("Not a valid network hostname: %s" % address)

    if not allow_ranges and '[' in host:
        raise AnsibleParserError("Detected range in host but was asked to ignore ranges")

    return (host, port)
```
The test results are as follows:
```
>>> from ansible.parsing.utils.addresses import parse_address
>>> parse_address("192.168.[1:20].11[1:3]", True)
('192.168.[1:20].11[1:3]', None)
>>> parse_address("192.168.[1:20].11[a:e]", True)
('192.168.[1:20].11[a:e]', None)
>>> parse_address("192.168.[1:20].11[a:e]", True, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python3.12/lib/python3.12/site-packages/ansible/parsing/utils/addresses.py", line 209, in parse_address
    raise AnsibleError("Not a valid ipv4 or ipv6 address: %s" % address)
ansible.errors.AnsibleError: Not a valid ipv4 or ipv6 address: 192.168.[1:20].11[a:e]
```

### Issue Type

Feature Idea

### Component Name

all

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

* Added an option to return valid IP address after parsing the
  given string.
* Added tests
* Updated docs

Fixes: #84178

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by bcoca** [comment]
im not sure this is correct or needed, the issue was with invalid ranges, if the ranges were valid and set to 'no ranges', it would not have made it to matching hostname

**Comment by spyinx** [comment]
> im not sure this is correct or needed, the issue was with invalid ranges, if the ranges were valid and set to 'no ranges', it would not have made it to matching hostname
I just feel that the pattern of IPv4 here was not used while reading the code, which is not perfect for this function. In addition, sometimes it is also desirable to have verification when writing the range of IP addresses since the code already has this function. If IP verification support can be added, then the pattern of IPv4  here will be meaningful. We strive for code perfection as much as possible, not just for basic functionality, right? However, in large-scale clusters, writing IP ranges is also very common. In order to prevent writing errors, it is also hoped that there can be verification instead of getting stuck in pinging incorrect IPs. Especially with a repeated retry mechanism, if detailed logs are not opened, the problem cannot be seen at once. Finally, i think we also need a config option to control the check of ip address only, then this param can be useful.

**Comment by bcoca** [comment]
I believe a custom inventory plugin (similar to this I was toying with https://github.com/bcoca/ansible/blob/cidr_inventory/lib/ansible/plugins/inventory/cidr.py) is better suited for your case vs a global option to disallow hostnames in all inventories.

Your case specifically deals with IPs + ranges, other cases can be a lot more complicated, for example 'chroot' requires a path as a 'hostname', we also allow ranges in hostnames `web0[1-9]` so the function handles things in a generic way. To have something more specific, i recommend a custom inventory plugin as that can handle definitions and verification for specific use cases, like yours.

**Comment by spyinx** [comment]
> I believe a custom inventory plugin (similar to this I was toying with https://github.com/bcoca/ansible/blob/cidr_inventory/lib/ansible/plugins/inventory/cidr.py) is better suited for your case vs a global option to disallow hostnames in all inventories.
> 
> Your case specifically deals with IPs + ranges, other cases can be a lot more complicated, for example 'chroot' requires a path as a 'hostname', we also allow ranges in hostnames `web0[1-9]` so the function handles things in a generic way. To have something more specific, i recommend a custom inventory plugin as that can handle definitions and verification for specific use cases, like yours.

for parse_address(), i still thinks it need a param to only check ipv4 or ipv6, look the code as follow, not like ipv4, hostname cannot write like ipv6 address:  
```shell
>>> from ansible.parsing.utils.addresses import parse_address
>>> from ansible.parsing.utils.addresses import patterns
>>> patterns["ipv6"].match("240E:0982:990A:0002:1")       # match failed
>>> patterns["ipv6"].match("240E:0982:990A:0002::1")      # match success
<re.Match object; span=(0, 21), match='240E:0982:990A:0002::'> 
>>> 
>>> parse_address("240E:0982:990A:0002::1")                   # match success 
('240E:0982:990A:0002::1', None)
>>> parse_address("240E:0982:990A:0002:1")                    # match failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python3.12/lib/python3.12/site-packages/ansible/parsing/utils/addresses.py", line 213, in parse_address
    raise AnsibleError("Not a valid network hostname: %s" % address)
ansible.errors.AnsibleError: Not a valid network hostname: 240E:0982:990A:0002:1
>>> 
>>> patterns["ipv4"].match("192.16.1.x")
>>> parse_address("192.16.1.x")
('192.16.1.x', None)
>>> 

```

**Comment by bcoca** [comment]
Yes, hostname is a catchall, intentionally. There is a problem with bad/incorrectly defined IPs, but we would need a per hostname/ip marker to validate at runtime, which we do not have a way of defining, much less passing to the function.

It then falls on the connection plugin to either validate or handle the error of a bad entry, in many cases we cannot know an entry is incorrect until we attempt to use it. Most users are not guaranteed to ONLY use IP addresses.

**Comment by mkrizek** [comment]
Closing per https://github.com/ansible/ansible/issues/84178#issuecomment-2447757980

**Pull request closed without merging**
