### PR TITLE
Deprecate tests used as filters

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
This PR adds a deprecation warning for using jinja tests as filters for eventual removal.

See https://github.com/ansible/proposals/issues/83

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
tests/filters

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

Things to be done:

- ~~Update docs to use proper test syntax instead of filter syntax~~
- ~~Update tests to use proper test syntax instead of filter syntax~~

### CODE REVIEW

**Comment by bcoca** [comment]
I would not warn ... if we want to remove this make it a deprecation, not a warning.

**Comment by sivel** [comment]
> I would not warn ... if we want to remove this make it a deprecation, not a warning.

Apologies, the title doesn't reflect functionality, we are using deprecations.

**Comment by sivel** [comment]
I've taken this a step forward, and aliased some tests to names that work better grammatically when using the `is` syntax.

I've also added a deprecation warning for using the old test names.

**Review by dharmabumstead — APPROVED** [review]
Thanks @sivel

**Comment by sivel** [comment]
Yay! A successful CI run: https://app.shippable.com/github/ansible/ansible/runs/44403/summary/console

I'll add the conversion script soon.

**Comment by sivel** [comment]
Hopefully I won't need to make any more commits before merge, but here is record of successful build: https://app.shippable.com/github/ansible/ansible/runs/44558/summary/console

**Comment by sivel** [comment]
@gundalow @dharmabumstead @bcoca @thaumos 

This PR is complete and ready for some reviews, if you all may be so kind to take a quick glance. The actual functional part of this change is rather small.  There are a number of doc updates, most of which @dharmabumstead approved earlier (excluding the porting guide).

All integration tests are passing, so the included script seems to do it's job fairly well.

As a side note, here is a grep command I used just to help verify that there weren't any "tests as filters" still lingering:

```
egrep -HRn '\|\ ?(failed|failure|succeeded|success|changed|change|skipped|skip|match|search|regex|version_compare|any|all|is_dir|is_file|is_link|exists|link_exists|is_abs|is_same_file|is_mount|issubset|issuperset|isnan)\b' *
```

**Comment by sivel** [comment]
ready_for_review

**Comment by dharmabumstead** [comment]
Doc changes were reviewed and approved but this needs a tech review from the core team and a rebase.

**Comment by sivel** [comment]
Wonderful :)

I'll hit another rebase soon.

**Comment by sivel** [comment]
Rebase completed and tests are green.

**Comment by abadger** [comment]
Looks good to me.  Couple of three nonblockers:

* Feels like we should have a deprecated test for using tests as filters.
Something that makes sure we don't break the old functionality prematurely.

* Do we need successful?  I do agree that it reads better than is success
but success doesn't read entirely wrong and we don't have the same type of
alias for the other similar tests, do we?

* Match and search don't read right with is syntax.  Maybe in the future
renaming would be good ( var is pattern(".*test");.  var is like
(".*test"); etc). One problem with coming up with a replacement is that
match and search do mostly the same thing.  Maybe a replacement could
toggle between the two via a parameter instead of having two different test
functions:

Var is like(".*test", anchor=true)

I've never really understood the purpose of match either...  Perhaps only
having search functionality and turning multiline on and off via a
parameter would make the most sense? I think the following does the same as
match, then:

Var is like ("^test_.*", multiline=False)

Where like is implemented via re.search.

**Comment by sivel** [comment]
@abadger 

* I agree on the test, and I added a simple test to validate the deprecation warning.

* As for `successful` I still want to include this.  Somewhere along the line we added a weird `succeeded` test, which presumably was added to go better with `failed` and `skipped`, however, I still think `successful` reads better than `succeeded` does.  We do have aliases for the other tests too: `failure`, `change`, and `skip`. We may want to look into consolidating those later, although I don't think they carry much tech debt.

* I agree on `search` and `match` as well.  I couldn't immediately come up with a good solution, and figured I'd ignore them for now.  I do _like_ your `like` suggestion.  I think I was actually the "author" of the `search` and `match` _filters_ originally, but I can't tell you exactly what I was thinking. We can always discuss this later and do an implementation elsewhere.

**Comment by abadger** [comment]
Cool.  The test is the only thing that felt like we should fix now.  +1
from me.

**Comment by sivel** [comment]
rebuild_merge

**Comment by astorije** [comment]
Off-topic but seeing @ansibot's message above: is there a way to opt-out from @ansibot? I haven't participated to this project in well over a year and get mentions I'd like to silence (without muting the whole repo). I looked at the help link it provides and no luck.
Thanks!

**Comment by sivel** [comment]
rebuild_merge

One more automated try

**Pull request merged**
