### PR TITLE
Add ssl, validate_certs in InfluxDB modules

### LINKED ISSUE #31923: influxdb_database module unable create SSL connections
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

influxdb_database module

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/username/.ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Oct  2 2017, 09:52:26) [GCC 4.2.1 Compatible OpenBSD Clang 4.0.0 (tags/RELEASE_400/final)]

```

##### CONFIGURATION

COLOR_VERBOSE(/home/username/.ansible.cfg) = cyan
DEFAULT_HASH_BEHAVIOUR(/home/username/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/username/.ansible.cfg) = [u'/home/username/ansible/inventory']
DEFAULT_MANAGED_STR(/home/username/.ansible.cfg) = This file is managed by Ansible.%n
template: {file}
date: %Y-%m-%d %H:%M:%S
user: {uid}@{host}

##### OS / ENVIRONMENT

OpenBSD hostname.domainname.com 6.2 GENERIC.MP#0 amd64

##### SUMMARY

`influxdb_database` module doesn't seem to be able to connect to TLS/SSL enabled InfluxDB servers.

##### STEPS TO REPRODUCE

InfluxDB server listening locally on default (8086) port, with TLS/SSL enabled gives following error:
```<server-hostname> (0, '\r\n{"msg": "", "failed": true, "exception": "  File \\"/tmp/ansible_vdg1JE/ansible_module_influxdb_database.py\\", line 127, in find_database\\n    databases = client.get_list_database()\\n  File \\"/usr/lib/python2.7/site-packages/influxdb/client.py\\", line 525, in get_list_database\\n    return list(self.query(\\"SHOW DATABASES\\").get_points())\\n  File \\"/usr/lib/python2.7/site-packages/influxdb/client.py\\", line 381, in query\\n    expected_response_code=expected_response_code\\n  File \\"/usr/lib/python2.7/site-packages/influxdb/client.py\\", line 256, in request\\n    raise requests.exceptions.ConnectionError\\n", "invocation": {"module_args": {"username": "XXXXX", "database_name": "smokeping", "hostname": "server-hostname.domainname.com", "state": "present", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": 8086}}}\r\n', 'Shared connection to server-hostname closed.\r\n')
The full traceback is:
  File "/tmp/ansible_vdg1JE/ansible_module_influxdb_database.py", line 127, in find_database
    databases = client.get_list_database()
  File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 525, in get_list_database
    return list(self.query("SHOW DATABASES").get_points())
  File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 381, in query
    expected_response_code=expected_response_code
  File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 256, in request
    raise requests.exceptions.ConnectionError

failed: [server-hostname] (item={'key': u'smokeping', 'value': {u'present': True}}) => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "database_name": "smokeping", 
            "hostname": "server-hostname.domainname.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 8086, 
            "state": "present", 
            "username": "XXXXX"
        }
    }, 
    "item": {
        "key": "smokeping", 
        "value": {
            "present": true
        }
    }, 
    "msg": ""
}
```

In the InfluxDB server log files, I can see that TLS connection is not being established:
```influxd: 2017/10/19 05:05:18 http: TLS handshake error from 10.XX.XX.XX:59134: tls: first record does not look like a TLS handshake```
I've also verified that correct SSL certificate is installed for InfluxDB server and checked it by running following command on the server:
`curl https://server-hostname.domainname.com:8086/`
`openssl s_client -showcerts -connect server-hostname.domainname.com:8086`

```yaml
- name: "manage influxdb databases"
  influxdb_database:
    hostname: "{{ influxdb_hostname }}"
    database_name: "{{ item.key }}"
    state: "{{ item.value.present | ternary('present','absent') }}"
    username: "{{ influxdb_admin_username }}"
    password: "{{ influxdb_admin_password }}"
  with_dict: "{{ influxdb_databases }}"
```

##### EXPECTED RESULTS

Connection to proceed, when proper sertificates are present.

##### ACTUAL RESULTS

Connection failed without giving any meaningful error message about the cause.

```

```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This fix adds ssl and validate_certs argument spec for InfluxDB
modules. Also, refactors code.

Fixes: #31923

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/influxdb.py
lib/ansible/modules/database/influxdb/influxdb_database.py lib/ansible/modules/database/influxdb/influxdb_retention_policy.py
lib/ansible/utils/module_docs_fragments/influxdb.py

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@abadger @kamsz @akasurde @sivel @nitzmahone @mattclay @nmorsman 

This refactor takes GPL licensed code to BSD licensed module_utils, I would like to ask permission for change.

Thanks.

**Comment by abadger** [comment]
I give permission to relicense any code I contributed to Ansible's InfluxDB modules to BSD for the purpose of moving common code into a shared, module_utils, file.  I understand that once the code is licensed BSD for that purpose, it can be used under the BSD license for other purposes as well.

**Comment by sivel** [comment]
You have my permission to relicense the code I contributed to BSD.

**Comment by Akasurde** [comment]
I give permission to relicense any code I contributed to Ansible's InfluxDB modules to BSD.

**Comment by nmorsman** [comment]
You have my permission to relicense code I contributed to BSD.

**Comment by mattclay** [comment]
I give permission to relicense any code I contributed to Ansible's InfluxDB modules to BSD.

**Comment by nitzmahone** [comment]
I give permission to relicense code I've contributed to Ansible InfluxDB modules to BSD.

**Comment by Akasurde** [comment]
@kamsz Could you please provide your permission?

**Comment by kamsz** [comment]
I give permission to relicense code I've contributed to Ansible InfluxDB modules to BSD.

**Pull request merged**
