### PR TITLE
Document get_url module check_mode support right

### PR DESCRIPTION
**Pull request by bluikko**
##### SUMMARY

The `get_url` module does not really support `check_mode` as pointed out in #65687.  
This is a simple PR to update the documentation to correctly say that `check_mode` is supported but the `changed` status will reflect comparison to an empty source file.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

get_url

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bluikko** [comment]
@jpmens I hope I got this right - does the "Docs Pull Request" refer to separate documentation or does it also include the inline documentation for modules (as in this case)? And I think the change type should be `known_issue`?

**Comment by jpmens** [comment]
@bluikko to be honest, I don't know. I should, but I don't.

**Comment by jpmens** [comment]
shipit

**Comment by bluikko** [comment]
The patch also removes `supports_check_mode=True` from argspec. I guess it is debatable if that should stay in.

**Comment by jpmens** [comment]
shipit

**Comment by bluikko** [comment]
This should be the final version, now the `attributes` block will document "partial" support with `details` describing it.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @bluikko for the Ansible docs fix and @jpmens for the tech review!

**Pull request merged**
