### PR TITLE
Apply tags conditionally so that the module does not throw up an erro…

### PR DESCRIPTION
**Pull request by brtkwr**
…r when using an older distro of openstacksdk

(cherry picked from commit c517538bd81149f5b507617e5f3385f98ec4642a)

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by emonty** [comment]
shipit

**Comment by gtema** [comment]
shipit

**Comment by abadger** [comment]
Backports need to have a changelog fragment.  This change looks good once a changelog fragment is added.

**Comment by abadger** [comment]
@brtknr Are you going to add a changelog fragment?

**Comment by brtknr** [comment]
Done

**Comment by abadger** [comment]
Merged for the 2.8.1 release.

**Pull request merged**
