### PR TITLE
Clarify documentation on _info vs. _facts modules

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Clarifies documentation on _info vs. _facts modules, since that question always comes up again.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
docs/docsite/rst/dev_guide/developing_modules_checklist.rst

### CODE REVIEW

**Review by resmo — APPROVED** [review]
shipit

**Review by bcoca — APPROVED** [review]

**Comment by felixfontein** [comment]
@acozine suggested to add some more examples on what are facts and what are not facts. @bcoca @resmo can you check whether these make sense (or maybe you have some more/better ideas)?

**Comment by resmo** [comment]
shipit

**Comment by acozine** [comment]
Thanks @felixfontein, looks good.

**Comment by acozine** [comment]
And thanks @resmo for the review!

**Comment by felixfontein** [comment]
@resmo @bcoca @acozine thanks everyone!

**Pull request merged**
