### PR TITLE
Address FIXME's in sysctl.py

### PR DESCRIPTION
**Pull request by ChrisAHolland**
##### SUMMARY

`sysctl.py` had 2 FIXME's that have remained unaddressed for years. This PR makes the small changes needed to cleanup the codebase.

Exited early on falsey `sysctl_path` and unindented the code blocks.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`sysctl.py`

### CODE REVIEW

**Comment by ChrisAHolland** [comment]
@Akasurde I don't want to waste any of your times, but do you know why these tests are failing? Having a similar issue in #69226  

Any advice is much appreciated!

**Comment by Akasurde** [comment]
@ChrisAHolland CI test for centos/6/3 is a known [failure](https://github.com/ansible/ansible/issues/62275) and is not related to this change.

**Comment by ChrisAHolland** [comment]
> @ChrisAHolland CI test for centos/6/3 is a known [failure](https://github.com/ansible/ansible/issues/62275) and is not related to this change.

Interesting. Hopefully I can fix anything I can and get this merged!

**Comment by bcoca** [comment]
i would just remove the FIXME instead, code is fine, adding multiple return points can make it harder to update later on.

**Comment by ChrisAHolland** [comment]
@bcoca Okay. I thought the update would help clean the code up a little, but I can't figure out why these minuscule changes would be causing a failure.

I will just remove the FIXME comments if you'd like so that nobody else wastes time on them.

**Review by bcoca — APPROVED** [review]

**Comment by ChrisAHolland** [comment]
@bcoca Thanks!

**Comment by jimi-c** [comment]
Thanks!

**Pull request merged**
