### PR TITLE
ecs_service: add propagate_tags and tags properties

### LINKED ISSUE #61560: ecs_service module should include tags and propagateTags fields
##### SUMMARY
The ecs_service module should include tags and propagateTags fields.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ecs_service

##### ADDITIONAL INFORMATION
The ecs_service module should include tags and propagateTags fields as specified here: https://docs.aws.amazon.com/AmazonECS/latest/userguide/service_definition_parameters.html

### PR DESCRIPTION
**Pull request by kevinwsin**
##### SUMMARY
This adds the propagate_tags and tags properties to the ecs_service module.

Fixes #61560.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ecs_service

### CODE REVIEW

**Comment by kevinwsin** [comment]
Hello, just wanted to check on the next steps for this PR / how to get a review.  Thank you in advance!

**Comment by MichalTaratuta** [comment]
Any updates when this will be implemented ?

**Comment by MichalTaratuta** [comment]
I tried to run a playbook with this module and it's failing with `The new ARN and resource ID format must be enabled to propagate tags. Opt in to the new format and try again.` even though it's enabled in AWS

**Comment by kevinwsin** [comment]
@MichalTaratuta was that for an existing resource?  And are you running the playbook using an IAM role w/ the new format setting?

**Comment by mawaldne** [comment]
@MichalTaratuta I know you posted your question a long time ago, but I'll post an answer here in case others run into it.

That error: `The new ARN and resource ID format must be enabled to propagate tags. Opt in to the new format and try again.`. For containers/tasks/services you have to opt in to a new arn format, otherwise you can't tag them. If you go to ECS in the amazon console and click 'Account Settings' on the left you can read about it there. You're just changing the format of arns on new resources. Old ones stay the same until recreated. 

I ended up running this command to enable it for all IAM roles on my amazon account:
```
aws ecs put-account-setting-default --name serviceLongArnFormat --value enabled
aws ecs put-account-setting-default --name taskLongArnFormat --value enabled
aws ecs put-account-setting-default --name containerInstanceLongArnFormat --value enabled
```

After that you should be able to run this module.

**Pull request closed without merging**
