### PR TITLE
New AWS module for ec2 internet gateway facts

### PR DESCRIPTION
**Pull request by naslanidis**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ec2_vpc_igw_facts
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel c5d3aac822) last updated 2017/01/15 12:44:25 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides


```
##### SUMMARY

This module returns internet gateway facts for an AWS account.

```
TASK [print output] ************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false, 
        "internet_gateways": [
            {
                "attachments": [
                    {
                        "state": "available", 
                        "vpc_id": "vpc-02642b23"
                    }
                ], 
                "internet_gateway_id": "igw-12e3645d", 
                "tags": [
                    {
                        "key": "Name", 
                        "value": "igw-test"
                    }
                ]
            }
        ]
    }
}
```

### CODE REVIEW

**Comment by naslanidis** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2093

**Comment by willthames** [comment]
Oops, I accidentally moved this PR using repomerge again! 

My improvements are at https://github.com/ansible/ansible/pull/20213, I can rebase my fixes on top of your latest fix if you like.

**Comment by willthames** [comment]
For me this is a :-1: until the parameters are more Ansiblish (lower snake_case rather than CamelCase) - there are a bunch of simplifications in #20213 that would be nice to have.

**Comment by naslanidis** [comment]
@willthames if you want to rebase your fixes on top of my latest that would be good. Sorry I didn't see your changes in the other PR.

**Comment by willthames** [comment]
No problem, I wouldn't really expect you to. Thanks for the quick feedback. How would you like the results of the rebase - update #20213 or a PR against your repo?

**Comment by naslanidis** [comment]
@willthames thanks a PR would be great. I can review and merge tonight.

**Comment by willthames** [comment]
Probably better to either cherry-pick or rebase my commit onto yours to avoid the merge commit and then re-force push (a git rebase upstream/devel would do the trick)

**Comment by naslanidis** [comment]
@dharmabumstead  @mhite @caphrim007 @gundalow @Qalthos @privateip

Apologies. I attempted to rebase and mistakenly included some other files into my PR. I've now down a hard reset to hopefully clean it up.

**Comment by willthames** [comment]
shipit

**Comment by j-carl** [comment]
shipit

**Comment by zimbatm** [comment]
Please remove me from the bot mentions. The linked help page doesn't give me a way to do it myself.

**Comment by willthames** [comment]
Adding this comment to four PRs doesn't help reduce unwanted notifications!

The reason you got this is because you are a maintainer for an AWS module. Today we realised that a bunch of new modules had had zero requests for feedback, and were effectively stuck in a queue. We unblocked the queue, perhaps too quickly, unleashing a bit too much spam. However, today should be a one off, but you will still get notified about future new modules.

There are a number of possibilities:
* you want to be a maintainer for that module still but not get new module maintenance requests. We'd need to discuss a way to achieve that - if we don't have any people acking new AWS modules then PRs just languish. Currently I'm not sure what the best way is.
* you no longer want to be a maintainer for the module at all. To save you some effort, just reply to this comment and I'll raise the necessary requests (it was my nudging that caused the queue to be unblocked so I'll take the hit as some form of recompense)

**Comment by zimbatm** [comment]
I was being a bit of a dick :) Can you remove me as a maintainer? I don't remember subscribing for this kind of work. Thanks!

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
2x shipits, merged and thanks all.

**Pull request merged**
