### PR TITLE
docker-py: bump minimal version to 1.8.0

### LINKED ISSUE #20776: docker_container has incorrect minimum docker-py version
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- docker_container

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /usr/home/sean/work/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
- Nothing.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The docker_container documentation says it requires a docker-py>=1.7.0. However, as of 2.2.1.0, the minimum version is actually 1.8.0 because of the addition of the `decode` argument to the `pull` method. That keyword argument was added for docker-py 1.8.0-rc1.

##### STEPS TO REPRODUCE
Use docker_container with a remote host that has 1.7.x, such as CentOS 7.2's 1.7.2.

##### EXPECTED RESULTS
Work.

##### ACTUAL RESULTS
```
failed: [host.example.com] (item=worker) => {"failed": true, "item": "worker", "msg": "Error pulling image imagename:latest - pull() got an unexpected keyword argument 'decode'"}
```

### LINKED ISSUE #29512: docker_container fails while pulling new image
From @maciej on 2016-11-07T17:28:08Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = [redacted]/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
[defaults]
host_key_checking=False
```

##### OS / ENVIRONMENT

Running ansible from: macOS Sierra
Provisioning: CentOS 7.2, Docker installed from https://yum.dockerproject.org/repo/main/centos/7

##### SUMMARY

`docker_container` module fails with: 
```
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image httpd:latest - pull() got an unexpected keyword argument 'decode'"}
```
while pulling an image

##### STEPS TO REPRODUCE

Execute ansible-playbook with the following play:

```
- name: "Start container"
  docker_container:
    name: whatever
    image: "httpd"
    pull: true
```

Copied from original issue: ansible/ansible-modules-core#5515

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This is a revive of PR #37513 by @Akasurde. Bumps the minimum required version of docker-py from 1.7.0 (released February 2016) to 1.8.0 (released April 2016). The latest docker-py version (which still supports Python 2.6) is 1.10.6, so this should hardly be a problem for anyone.

Fixes #29512, fixes #20776.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/docker_common.py
docker_container
docker_image_facts
docker_image
docker_login
docker_network
docker_secret
docker_service
docker_swarm
docker_swarm_service
docker_volume
lib/ansible/utils/module_docs_fragments/docker.py

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @skylerbunny @kassiansun LGTM, could you please review this ? Thanks.

**Review by kassiansun — APPROVED** [review]

**Comment by kassiansun** [comment]
shipit

**Review by tbouvet — APPROVED** [review]

**Comment by tbouvet** [comment]
shipit

**Comment by Akasurde** [comment]
@felixfontein @kassiansun @tbouvet Thanks for the contribution.

**Comment by felixfontein** [comment]
@Akasurde thanks for bringing this through!

**Comment by skylerbunny** [comment]
Looks good here. I spent a little extra time overnight checking API-DockerAPI-versions stuff, didn't see any issues.

**Comment by felixfontein** [comment]
Thanks for checking, @skylerbunny!

**Pull request merged**
