### PR TITLE
Zabbix: add integration test for zabbix_user module

### PR DESCRIPTION
**Pull request by sky-joker**
##### SUMMARY
integration test for zabbix_user module

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
zabbix_user

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
Looks good. Thanks for these tests!

shipit

**Comment by mattclay** [comment]
The tests are [failing](https://app.shippable.com/github/ansible/ansible/runs/159738/59/tests) and have been disabled in https://github.com/ansible/ansible/pull/67487.

**Comment by D3DeFi** [comment]
Hello, I would argue that we don't need tests on AIX at all, so it is ok for them to be skipped, but disabling them as a whole was unecessary tho. Is there something else we should do before re-enabling them?

**Comment by mattclay** [comment]
@D3DeFi The tests have already been disabled on AIX. The test failures on Ubuntu will need to be fixed before the tests can be re-enabled.

**Comment by sky-joker** [comment]
Hello all, This [PR](https://github.com/ansible/ansible/pull/67475) can solve this [problem](https://app.shippable.com/github/ansible/ansible/runs/159738/59/tests).

**Comment by D3DeFi** [comment]
> 
> 
> @D3DeFi The tests have already been disabled on AIX. The test failures on Ubuntu will need to be fixed before the tests can be re-enabled.

MB, somehow failed to see that it related to the ubuntu as well, thanks

**Pull request merged**
