### PR TITLE
WIP: Google Compute Instances fact module

### PR DESCRIPTION
**Pull request by rambleraptor**
##### SUMMARY

This is a handwritten version of a module to generate facts for Google Cloud Compute Engine instances.

If this looks good, the intention is to use this as a template to create facts modules for all GCP modules.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

gcp_compute_instance_facts
##### ANSIBLE VERSION

```
2.6
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by andygeorge** [comment]
This PR is working great for us, and seems to be the best way to pull instance facts, relative to the other open GCP/GCE facts PRs (#35276 #36429). Would love to see this in 2.6.

**Comment by rambleraptor** [comment]
Thanks a lot for that! This PR is part of a broader effort to get facts modules for all of the new gcp_* modules that we've been building. I don't think that this will make it into 2.6 (the final RC is already underway), but I'm aiming to get facts modules for GCE instances + the rest of GCP into 2.7.

If you have any feedback about this PR, it would be really appreciated

**Comment by andygeorge** [comment]
Awesome, good to know. We _do_ also need a "`gce_facts`" analog of `ec2_facts` (eg the module that runs on each instance itself), but this was a good starter to get us up and running, at least. We'll add feedback as we continue to use this.

**Comment by rambleraptor** [comment]
Does the ec2_facts module fetch metadata information whereas the other ec2-related facts module fetch broader information about the instance (machine-type for instance)?

**Pull request closed without merging**
