### PR TITLE
unarchive: avoid archive transfer in case of creates= existence

### PR DESCRIPTION
**Pull request by rdolejsi**
Unarchive no longer transfers archive if creates= check succeeds.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not concerned with the support for new versions of the module on older ansible runtimes or vice versa as that's not a supported use case.

**Comment by mpdehaan** [comment]
In queue for review, thanks!

**Comment by rdolejsi** [comment]
Please let me know the timeframe for discussion / inclusion. I have multiple other pending contributions blocked by this pending pull request. Worse case I will need to close the pull request and restructure my forked tree to be able to contain it..

Thank you,
Roman

**Comment by rdolejsi** [comment]
Closing pull request due to maintainers inactivity, need to restructure own forked repo.

**Pull request closed without merging**
