### PR TITLE
Issue #7816 adding md5 checksum verification for get_url module

### PR DESCRIPTION
**Pull request by hahnicity**

### CODE REVIEW

**Comment by hahnicity** [comment]
Sorry for the terrible branching... I'm sure I can do it better if you need it.

**Comment by mpdehaan** [comment]
Yes, please -- if you can submit this without merge commits this would be great.

I'd suggest git pull --rebase vs git merge, and git pull --rebase vs git pull.

You should be able to cherry pick the commits you like onto the new branch.

**Comment by muffl0n** [comment]
I already added an option to support all algorithms that are supported by hashlib. See PR #7639.

**Comment by mpdehaan** [comment]
I prefer this one for some reasons noted on the ticket in #7639.

I would welcome exposure of other parameters though, but I would like them to be done in a way that's a bit more consistent if possible.

Though realistically, I think md5sum and sha256 would cover 99% of needs if not more, so probably not needed...

**Comment by mpdehaan** [comment]
# Revision Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We'd like to see a few things tweaked if you don't mind.  If you can help resolve these items, we'd greatly appreciate it:
- The check to see if hashlib is present is only done for the sha256 sum
- I'm seeing where the sha256 code is computed but not the md5, which appears to remain missing, and would appreciate clarification.   destination = hashlib.validate(...) etc seems to be missing.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by muffl0n** [comment]
It seems like my comment from August 8th somehow vanished in the void. I'll try to reconstruct it from memory:
As stated in #7639 I would prefer my solution where we are not restricting the users to two algorithms we have chosen for them but to give them the freedom to choose between all algorithms that haslib provides. I think that cutting down the possibilities we have, thanks to hashlib, makes no sense at all.
I prefer #7639 not just because it's my PR but because it's more foresighted than other PRs.

**Comment by hahnicity** [comment]
The check to see if hashlib is present is only done for the sha256 sum
- I'm confused, md5 in python only needs needs the python md5 module

I'm seeing where the sha256 code is computed but not the md5, which appears to remain missing, and would appreciate clarification. destination = hashlib.validate(...) etc seems to be missing.
- But we are computing the md5 sum, in fact it's already been computed by the module so we don't need to recompute it

I'm working on fixing the branching right now

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
