### PR TITLE
added module for defining a supervisor program config

### PR DESCRIPTION
**Pull request by guymatz**
##### SUMMARY
Module to allow for the creation/deletion/change of supervisord program configuration

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
supervisor_prod

##### ANSIBLE VERSION
```
ansible 2.3.0 (supervisor_prog_module 40a9c716c2) last updated 2017/03/09 15:47:21 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by maxamillion** [comment]
Thanks for the module submission! The module code looks good, could you please add integration tests for it?

**Comment by guymatz** [comment]
Sure!  Can you point me to a good example of an integration test?

Thanks!!

**Comment by maxamillion** [comment]
@guymatz There are many here https://github.com/ansible/ansible/tree/devel/test/integration/targets but I think a good one that might be similar to what you'd be doing is https://github.com/ansible/ansible/tree/devel/test/integration/targets/service

**Comment by guymatz** [comment]
Great!  Thanks!  Is there a doc somewhere that details how to write an
integration test?

**Comment by guymatz** [comment]
http://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html ?

**Comment by maxamillion** [comment]
@guymatz yes, sorry ... I should have linked that doc as well, thanks again! :)

**Comment by gundalow** [comment]
Thank you for your PR.
As part of reviewing the backlog of PRs we are looking at PRs older PRs that haven't been updated in a while

Given that:
* last comments on this were in Feb 2018
* This is a new module (rather than bug fix, or feature improvement to an existing module)

Therefore I'm going to close this.

If you or anyone else wants to continue with this work then please do feel free to create a fresh PR and `@mention` the previous reviewers in here.

**Pull request closed without merging**
