### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by piffey**
We use a lot of bulk multi-line keyfiles like ops.pub and devs.pub. Since this would be nice to have for our sake, thought maybe some others might like it too.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Question for you, I do like the idea, and I definitely see the need to manage keys in bulk, but could you just manage authorized_keys with file or template in that case?   This way you know only the keys you have authorized are actually going to remain on the system.

I agree you would want to add them together, though you could use a template with a Jinja2 include directive to make a larger authorized keys file out of two smaller ones?

Curious as to your thoughts...

**Comment by mpdehaan** [comment]
FYI, may want to create a "topic branch" for each new pull request and look into "git rebase -i" before sending pull requests, so you don't have the extra commit in there :)

**Comment by piffey** [comment]
Definitely. We've been using just a templated authorized_keys file for right now. The thing I liked about doing it this way was being able to separate out by role or whatever the groups of keys we'd be adding. More a logical thing than anything else and it was so simple of a feature to add. I guess that's just as easy to do with a jinja template, I guess I just thought there should be no reason authorized_keys shouldn't handle multi-line keyfiles. Either way though, the job can still get done and that's what matters.

On the topic branch end, thanks for the tips. Only really have experience working in svn. Will make sure future pulls come from a topic branch. That'd definitely make it easier to keep track of in the fork as well. :)

**Comment by mpdehaan** [comment]
I'll open up another ticket about the prune idea.

Sounds good to me, thanks!

**Comment by mpdehaan** [comment]
Actually, I'm just ok with templating in that case too, and not adding prune, perhaps we add a documentation item instead.

**Pull request merged**
