### PR TITLE
acknowledge operations are update operations now

### PR DESCRIPTION
**Pull request by richlv**
+label: docsite_pr

##### SUMMARY
Acknowledge operations are update operations since Zabbix 4.0

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
zabbix_action

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
Just for the info, here are links to the same action operations under different zabbix versions - [3.4 doc](https://www.zabbix.com/documentation/3.4/manual/config/notifications/action/acknowledgement_operations) and [4.0 doc](https://www.zabbix.com/documentation/4.0/manual/config/notifications/action/acknowledgement_operations). API doesn't seems to have naming related to action ops changed, but I agree that at least option descriptions can reflect changes in the GUI.

**Comment by D3DeFi** [comment]
shipit

**Comment by D3DeFi** [comment]
-label needs_triage

**Comment by richlv** [comment]
Yes, Zabbix API documentation has a bugreport against it at https://support.zabbix.com/browse/ZBX-15511 :)

**Comment by samccann** [comment]
Thanks @richlv for the Ansible documentation clarification!

**Pull request merged**
