### PR TITLE
Add Pure Storage FlashBlade Snapshot module

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Add module to manage snapshots of Pure Storage FladeBlade filesystems

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
storage/purestorage/purefb_snap

##### ANSIBLE VERSION
2.6

##### ADDITIONAL INFORMATION
Add the ability to manage FlashBlade filesystem snapshots, including create, delete and recover.

### CODE REVIEW

**Comment by sdodsley** [comment]
Oops - have to wait for #32467 to merge before this can pass tests

**Review by jbilbro — APPROVED** [review]
I have tested this on my Flashblade running Purity//FB 2.1.5 and 2.1.7 and it works perfectly.  Please merge!

**Comment by sdodsley** [comment]
shipit

**Review by sdodsley — COMMENTED** [review]
shipit

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel` will be released in 2.6.0

**Pull request merged**
