### PR TITLE
osx_defaults: refactor

### LINKED ISSUE #29329: Incorrect documentation: osx_defaults does not allow reading values
From @wizonesolutions on 2016-06-28T11:54:45Z
Copying from https://github.com/ansible/ansible/issues/16455
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
osx_defaults

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/kevin/wizardbox/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
$ cat ansible.cfg
[defaults]
roles_path = ./data/ansible/roles
```
##### OS / ENVIRONMENT

OS X, locally
##### SUMMARY

http://docs.ansible.com/ansible/osx_defaults_module.html says that the module can be used to read from defaults, but it can't. It can only write and update. There are no read examples, and `value` is required when `state=present`.
##### STEPS TO REPRODUCE

N/A

```
- name: check if spelling correction is enabled
  osx_defaults: key={{ item }}
  with_items:
    - NSAutomaticSpellingCorrectionEnabled
    - WebAutomaticSpellingCorrectionEnabled
  register: spelling_status
```
##### EXPECTED RESULTS

The defaults to be registered into a variable.
##### ACTUAL RESULTS

```
TASK [check if spelling correction is enabled] *********************************
failed: [localhost] (item=NSAutomaticSpellingCorrectionEnabled) => {"failed": true, "item": "NSAutomaticSpellingCorrectionEnabled", "msg": "Missing value parameter"}
failed: [localhost] (item=WebAutomaticSpellingCorrectionEnabled) => {"failed": true, "item": "WebAutomaticSpellingCorrectionEnabled", "msg": "Missing value parameter"}
```

Copied from original issue: ansible/ansible-modules-extras#2492

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* Code refactor
* Documentation update
* Add 'list' parameter
* Example update

Fixes: #29329

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/system/osx_defaults.py

### CODE REVIEW

**Comment by dagwieers** [comment]
We would need integration tests to ensure this is working as expected.

**Comment by dagwieers** [comment]
@akasurde We need to test more than just running it once.

- Idempotency tests
- Check-mode tests
- Check return values

For the WG members I wrote about it a bit here: https://github.com/ansible/community/wiki/Reviewing#integration-tests

I know you did not write this module, but currently the macOS WG is understaffed, and we need to make sure that any changes don't impact existing functionality. I hope you understand.

**Comment by Akasurde** [comment]
@dagwieers I just wanted to run these test on MacOS so added one test case to check. Now, I have added a bunch of testcases to check idempotency and check mode support. 

Just check once and let me know. Thanks.

**Review by dagwieers — APPROVED** [review]
LGTM, the integration tests give me confidence :-)

**Review by gundalow — APPROVED** [review]

**Pull request merged**
