### PR TITLE
[WIP] cert validation fixes

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
[WIP] Start of cert validation fixes

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/urls.py

##### ADDITIONAL INFORMATION
A few things this PR does:

1. Doesn't effectively disable SSL verification if `no_proxy` is true.
1. Keeps the temporary ca cert bundle through the end of execution, avoiding rebuilding it for each `open_url`/`Request.open` call.

### CODE REVIEW

**Comment by sivel** [comment]
bot_skip

**Comment by kbreit** [comment]
CC @dagwieers 

I've done some performance testing on this using my Meraki network modules. There doesn't appear to be any regressions, at least related to the Meraki modules.

I'll test more modules, maybe tonight, but I am seeing some performance improvements when running integration tests. `meraki_snmp` is showing a 6% performance increase over 3 trials (0:38 and 0:36) and `meraki_content_filtering` is a 3% performance increase (1:03 and 1:01).

**Comment by dagwieers** [comment]
Let me recap [my preferred implementation](https://github.com/ansible/ansible/issues/52717#issuecomment-466066170) in this PR in case we have to retain the existing functionality:

- Once on every module invocation (may be the first request performed), check the timestamp of the certificate-database
  - If cert-database is fairly recent (timeout or ttl) or cert-database is locked, use it
  - If not, lock cert-database and check for newer certs
    - If newer certs exist, rebuild cert-database, unlock database
    - Otherwise touch cert-database and unlock

The lock would be there to ensure we don't have multiple modules rebuilding the database at the same time. The timeout value is there just to avoid the somewhat more expensive check for updated certs.

**Comment by sivel** [comment]
Putting this back in WIP, as I want to look into utilizing `ssl.get_default_verify_paths` where possible, and `ssl.SSLContext.load_verify_locations` to avoid creating an on disk CA bundle at all when possible.  We can then walk `/etc/ansible` and add PEM files directly.

**Pull request closed without merging**
