### PR TITLE
Make interprocess polling interval configurable

### PR DESCRIPTION
**Pull request by pshchelo**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 26755b3a62) last updated 2016/07/01 17:10:17 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 1d0d5db97a) last updated 2016/07/01 17:26:00 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 00b8b96906) last updated 2016/07/01 17:26:00 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

As recently there was back-and-forth with this hardcoded value
(0.001 -> 0.01 -> 0.005), obviously the optimal value for it depends on
Ansible usage scenario and is better to be configurable.

This patch adds a new config option in DEFAULT section,
`internal_poll_interval`, with default of 0.001 corresponding to the
value hardcoded in Ansible v2.1.
This config option is then used instead of hardcoded values where
needed.

Related issue: #14219

### CODE REVIEW

**Comment by resmo** [comment]
Makes sense, LGTM

**Comment by pshchelo** [comment]
On average, increasing the value from default 0.001 to 0.01 leads to about 50% less CPU consumption by ansible process.
The most effect is to be seen when there are multiple ansible workers and strategy is "free".

Simple proof:

configuration

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

$ cat /proc/cpuinfo | grep "model name" | head -n1
model name      : Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz

$ ansible-playbook --version
ansible-playbook 2.2.0 (config-polling 3987351f63) last updated 2016/09/15 11:46:25 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 683e5e4d1a) last updated 2016/09/15 10:59:04 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 8749c40fee) last updated 2016/09/15 10:59:04 (GMT +300)
  config file = /home/pshchelo/devel/ansible-files/ansible.cfg
  configured module search path = Default w/o overrides
```

configs/playbooks

```
$ ls
ansible.cfg testhosts testcpu.yaml

$ cat ansible.cfg
[defaults]
internal_poll_interval = 0.001

$ cat testhosts
host1 ansible_connection=local
host2 ansible_connection=local
host3 ansible_connection=local
host4 ansible_connection=local
host5 ansible_connection=local

$ cat testcpu.yaml
---
- hosts: all
  gather_facts: no
  strategy: free
  tasks:
    - name: do nothing
      command: sleep 30
      async: 60
      poll: 10
```

testing

```
$ /usr/bin/time --format "%Us user\n%P CPU" ansible-playbook -i testhosts testcpu.yaml 
...
8.66s user
29% CPU

$ sed -i 's/0.001/0.01/' ansible.cfg

$ /usr/bin/time --format "%Us user\n%P CPU" ansible-playbook -i testhosts testcpu.yaml
...
4.41s user
15% CPU
```

Notice the x2 difference in user time and CPU.

**Comment by jimi-c** [comment]
@pshchelo per the other perf issue, if you'd like to adopt this to the changes in result processing I can merge it in before 2.2 RC2.

**Comment by pshchelo** [comment]
@jimi-c I would really like to have it in 2.2. reworking the PR now.

The thing is, our use case (however "not-ansibly") involves running potentially dozens of ansible-playbook processes each against a single node, but from the server-side component w/o human interaction. Unfortunately this one-node-per-playbook restriction is imposed by the outer framework we are using Ansible under. That is why being able to save even couple of CPU% is important for me.

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by jimi-c** [comment]
And cherry-picked to `stable-2.2`

**Pull request merged**
