### PR TITLE
Docs: Added code-block wrappers to code examples: developing_module_utilities.rst #78961

### PR DESCRIPTION
**Pull request by Deepshaded**
List of changed files:

- docs/docsite/rst/dev_guide/developing_module_utilities.rst
##### SUMMARY
- Added code block wrappers to code examples in docs/docsite/rst/dev_guide/developing_module_utilities.rst
- Fixes:  Docs: Add code-block wrappers to code examples: developing_module_utilities.rst #78961

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Review by ariordan-redhat — COMMENTED** [review]
Built doc looks good to me.

**Comment by ariordan-redhat** [comment]
Hi @Deepshaded,

Thank you for this PR.  Your changes look good to me. 

Could you please rebase your branch to remove the merge commit?  
(See [this comment](https://github.com/ansible/ansible/pull/78968#issuecomment-1264373356)). I can merge it after the rebase.

Thank you!

**Comment by Deepshaded** [comment]
Yes, sure. Working on it.

**Review by ariordan-redhat — APPROVED** [review]
Looks good to me

**Comment by ariordan-redhat** [comment]
Thank you for contributing to the Ansible docs, @Deepshaded !

**Comment by Deepshaded** [comment]
Thank you for the opportunity :)

**Comment by ariordan-redhat** [comment]
Fixes #78961

**Pull request merged**
