### PR TITLE
Creates base Sophos XG module

### PR DESCRIPTION
**Pull request by rdelcampog**
##### SUMMARY
Implementation of SFOSModule Base Class that can easily be used to implement other endpoints to control Sophos XG NGFWs. Taking as base the @MatrixCrawler Sophos UTM module. Sophos XG API is based on XML request so XMLTODICT and a lot of checks and response checks have to be made.

I will try to add a module for each API endpoint described in Sophos XG API Docs (can be downloaded from [this KB](https://community.sophos.com/kb/en-us/132560)). A fully functional Sophos XG virtual appliance [can be downloaded for free](https://secure2.sophos.com/es-es/products/next-gen-firewall/free-trial.aspx) in order to test this module.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- sfos_iphost

##### ADDITIONAL INFORMATION
Fully tested against SFOS v17.5.1.

##### ANSIBLE VERSION
```
ansible 2.7.6
  config file = None
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
```

### CODE REVIEW

**Comment by rdelcampog** [comment]
Some other modules waiting for PR after this one is approved:
- https://github.com/rdelcampog/ansible/tree/sfos_iphost_facts
- https://github.com/rdelcampog/ansible/tree/sfos_iphost_group
- https://github.com/rdelcampog/ansible/tree/sfos_fqdnhost
- https://github.com/rdelcampog/ansible/tree/sfos_fqdnhost_facts
- https://github.com/rdelcampog/ansible/tree/sfos_webserver

**Comment by rdelcampog** [comment]
ready_for_review

**Comment by Qalthos** [comment]
This should be using an httpapi plugin rather than manually calling fetch_url. See https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/httpapi for examples

**Comment by rdelcampog** [comment]
> This should be using an httpapi plugin rather than manually calling fetch_url. See https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/httpapi for examples

Hi @Qalthos, SophosXG API has a very strange implementation. For example, the API always returns a 200 OK HTTP code, even if the request fails for bad credentials or bad endpoint.

I can't look into HTTPAPI right now, but I'll take a look later and see if it's possible to use this plugin.

Thanks.

**Comment by NilashishC** [comment]
needs_info

**Pull request closed without merging**
