### PR TITLE
Better s3 example for the dest parameter.

### PR DESCRIPTION
**Pull request by lwade**
Minor change to improve the docs chunk.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!

I also notice these examples are formatted a bit weird with the "module: S3" and so on.

Can they be presented on one line or with indentation?

If using complex args,

s3:
    key: val
    key2: val

etc?

**Comment by lwade** [comment]
Yeah good catch.  I can certainly take a look at that after adding this example.  Otherwise happy to close/re-open or rebase this.

**Comment by mpdehaan** [comment]
minor nit, we are standardizing on stuff like

s3: foo

versus

action: s3 foo for docs things.

I'll merge this regardless and tweak, thanks!

**Comment by mpdehaan** [comment]
actually we made a lot of cleanup changes recently, any chance you could reapply this change on top of the latest?

Thanks and sorry for the confusion!

**Comment by lwade** [comment]
@mpdehaan, sure, lets close this down and I'll open a new PR.

**Pull request closed without merging**
