### PR TITLE
Fix redfish_facts Chassis command GetFanInventory returning duplicates of the same Fan entity

### PR DESCRIPTION
**Pull request by xmadsen**
##### SUMMARY

This pull request fixes a bug in the redfish_facts `Chassis` command `GetFanInventory` where the `get_fan_inventory()` function in redfish_utils.py was returning a list of one fan instance repeated a number of times equal to the number of fan objects found by redfish.

If multiple chassis objects were found to loop over, the `result['entries'] = fan_results` would be set multiple times, rather than just once at the end, so I outdented that line to run only after all chassis were looped over.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

redfish_facts

##### ADDITIONAL INFORMATION

```yaml
- name: Test Redfish modules
  hosts: localhost
  gather_facts: false
  vars:
    baseuri: 10.240.50.79
    user: USERID
    password: PASSW0RD

  tasks:
    - name: Get Fan inventory
      redfish_facts:
        category: Chassis
        command: GetFanInventory
        baseuri: "{{ baseuri }}"
        username: "{{ user }}"
        password: "{{ password }}"

```

```
ansible-playbook 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/xander/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/lib/ansible
  executable location = /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

Loading callback plugin default of type stdout, v2.0 from /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/lib/ansible/plugins/callback/default.pyc

PLAYBOOK: test_redfish_facts.1.yml **********************************************************************************Positional arguments: ../test_redfish_facts.1.yml
become_method: sudo
inventory: (u'/etc/ansible/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in ../test_redfish_facts.1.yml

PLAY [Test Redfish modules] *****************************************************************************************META: ran handlers

TASK [Get Fan inventory] ********************************************************************************************task path: /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/test_redfish_facts.1.yml:10
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: xander
<127.0.0.1> EXEC /bin/sh -c 'echo ~xander && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524 `" && echo ansible-tmp-1551125853.04-192166449626524="` echo /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524 `" ) && sleep 0'
Using module file /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/lib/ansible/modules/remote_management/redfish/redfish_facts.py
<127.0.0.1> PUT /home/xander/.ansible/tmp/ansible-local-1764r1mlDa/tmpNZflVm TO /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/AnsiballZ_redfish_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/ /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/AnsiballZ_redfish_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/AnsiballZ_redfish_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "ansible_facts": {
        "redfish_facts": {
            "fan": {
                "entries": [
                    {
                        "FanName": "Fan 6 Tach", 
                        "Reading": 25, 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 6 Tach", 
                        "Reading": 25, 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 6 Tach", 
                        "Reading": 25, 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 6 Tach", 
                        "Reading": 25, 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 6 Tach", 
                        "Reading": 25, 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 6 Tach", 
                        "Reading": 25, 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }
                ], 
                "ret": true
            }
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "baseuri": "10.240.50.79", 
            "category": [
                "Chassis"
            ], 
            "command": [
                "GetFanInventory"
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "USERID"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0
```

After:
```
ansible-playbook 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/xander/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/lib/ansible
  executable location = /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

Loading callback plugin default of type stdout, v2.0 from /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/lib/ansible/plugins/callback/default.pyc

PLAYBOOK: test_redfish_facts.1.yml **********************************************************************************Positional arguments: ../test_redfish_facts.1.yml
become_method: sudo
inventory: (u'/etc/ansible/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in ../test_redfish_facts.1.yml

PLAY [Test Redfish modules] *****************************************************************************************META: ran handlers

TASK [Get Fan inventory] ********************************************************************************************task path: /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/test_redfish_facts.1.yml:10
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: xander
<127.0.0.1> EXEC /bin/sh -c 'echo ~xander && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524 `" && echo ansible-tmp-1551125853.04-192166449626524="` echo /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524 `" ) && sleep 0'
Using module file /mnt/c/Users/amadsen/Coding/lenovo-redfish-automated-testing/ansible/lib/ansible/modules/remote_management/redfish/redfish_facts.py
<127.0.0.1> PUT /home/xander/.ansible/tmp/ansible-local-1764r1mlDa/tmpNZflVm TO /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/AnsiballZ_redfish_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/ /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/AnsiballZ_redfish_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/AnsiballZ_redfish_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/xander/.ansible/tmp/ansible-tmp-1551125853.04-192166449626524/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "ansible_facts": {
        "redfish_facts": {
            "fan": {
                "entries": [
                    {
                        "FanName": "Fan 1 Tach", 
                        "Reading": 25, 
                        "ReadingUnits": "Percent", 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 2 Tach", 
                        "Reading": 24, 
                        "ReadingUnits": "Percent", 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 3 Tach", 
                        "Reading": 23, 
                        "ReadingUnits": "Percent", 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 4 Tach", 
                        "Reading": 24, 
                        "ReadingUnits": "Percent", 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 5 Tach", 
                        "Reading": 25, 
                        "ReadingUnits": "Percent", 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }, 
                    {
                        "FanName": "Fan 6 Tach", 
                        "Reading": 25, 
                        "ReadingUnits": "Percent", 
                        "Status": {
                            "Health": "OK", 
                            "State": "Enabled"
                        }
                    }
                ], 
                "ret": true
            }
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "baseuri": "10.240.50.79", 
            "category": [
                "Chassis"
            ], 
            "command": [
                "GetFanInventory"
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "USERID"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0
```

### CODE REVIEW

**Review by billdodd — COMMENTED** [review]
The fix for the duplicate fan entries looks good. Thanks for catching that.

But wondering why there is also the change to get_disk_inventory(), which looks like the same change you have in PR #52939?

**Comment by xmadsen** [comment]
@billdodd made a git flub, should be resolved now.

**Review by billdodd — APPROVED** [review]
Fix looks good. Thanks.

shipit

**Comment by jose-delarosa** [comment]
Thanks for this, tested it and looks good.

shipit

**Comment by jose-delarosa** [comment]
Asked Core Team yesterday in IRC to merge but no luck, will try again today.

**Comment by gundalow** [comment]
@xmadsen Thank you for the patch
@jose-delarosa Once a PR gets the `label/shipit` added it will be normally merged within the next few days.

**Pull request merged**
