### PR TITLE
Fix assorted shell-related issues with the git module.

### PR DESCRIPTION
**Pull request by wenottingham**
##### SUMMARY

See https://github.com/ansible/ansible/issues/65956.

Notably:
- always pass `expand_user_and_vars=False` - we don't want to be expanding versions that look like env vars
- always pass cmd as a list for anything that takes versions to avoid shells trying to figure out arguments
- don't strip *all* whitespace from the branch list, as certain whitespace characters are valid

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
git

### CODE REVIEW

**Comment by samdoran** [comment]
Can you please add a changelog fragment and an integration test that breaks with the current quoting behavior?

Also please, add a toggle to control the environment variable behavior with the default being how it is currently.

**Comment by wenottingham** [comment]
When would a user ever be passing a refspec parameter to the git module as something that resolves to an environment variable they would expect to be expanded?

**Comment by samdoran** [comment]
I admit, that sounds crazy. I can't think of a scenario where that would be expected, but people do crazy things, and I want to avoid breaking their crazy things when possible.

I'd have to get others to weigh in on changing the default behavior without a setting to control it, especially for a core supported module. The consensus when we looked at this during triage was it needs to be opt-in since it's a change in behavior (even though that behavior does seem really wonky).

**Comment by samdoran** [comment]
We looked at this again in backlog today. After discussing more, adding a toggle isn't necessary, but setting `expand_user_and_vars=False` is only half the fix. User vars still need to be expanded on `git_path` as well as the path to the the checkout.

**Pull request closed without merging**
