### PR TITLE
Revise templating

### PR DESCRIPTION
**Pull request by dne**
- Factor utils.template into utils.simple_template and utils.jinja2_template.
- Remove 'setup_cache' argument (only used once, in the template module).
- For utils.template_from_file, change the 'no_engine' arg to 'engine' (takes
  either 'simple' or 'jinja2')
- In the template module, use Jinja2 templating only; everywhere else, use
  "simple" variable replacement.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Fair warning -- I am generally against folks refactoring code without some discussion of it first, especially when there are no related features from it.   Everyone has a different vision for things, and this just moves things around from what I can tell.

Setup cache stuff is a little weird, I expect changes in 0.5.  I would rather see a named argument with a default than two functions in that case, but it's likely to change a bit anyway.

engine is only passed for the template file module now, so that's not neccessary to have it take a type either.  I don't want to support multiple template engines at this point. 

As stated on the mailing list, we're in feature freeze mode now to get 0.4 out, and there's some major playbook refactoring due in 0.5, so it makes sense to wait anyway.

**Comment by dne** [comment]
Fair enough.

The main problem I see with how templating currently works, is that it's impossible to bypass the variable replacement when using the template module.

This change fixed that -- use either variable replacement (in playbooks and includes) or Jinja2 (template module).

**Comment by mpdehaan** [comment]
Why did you need to bypass the variable replacement logic?  It should not be replacing any variables that are not defined.

**Comment by dne** [comment]
What's the point in passing a Jinja2 template through variable replacement? IMO, you'd want either one or the other, but not both at the same time. This was the crux of my patch.

Also a template might contain Bourne/PHP/Perl code, and then you'd have to worry about variable names clashing.

**Comment by mpdehaan** [comment]
For simple templates, not having to resort to Jinja2 syntax.   $foo seems a lot more natural.

Templating out code is possibly but also a little weird, I'd hope people would use the copy module in that case as there should be no need to template it.

**Comment by dne** [comment]
Sure, it goes both ways -- with a "simple" template you don't need/want it passed through Jinja2.

Another couple of lines on top of my patch would allow for an "engine" argument for the template module (defaulting to either "simple" or "jinja2", whichever you prefer).

In many cases config files are code.

**Comment by mpdehaan** [comment]
Understood.

I should this is a good example why you should talk about what you want to do, and also explain this in the PRs.   Saves the ongoing discussion and makes it much clear than just talking about lines of code.

Anyway, I don't think we need this right now, but we can look at making the jinja2 and the varReplace seperate named arguments later.

**Pull request closed without merging**
