### PR TITLE
Add support for checking host against global known host files.

### PR DESCRIPTION
**Pull request by iiordanov**
Hi Michael,

I've added support for the standard SSH known hosts files as well as the user known hosts file. Please note there are two possible locations for the global known_hosts file and I check both.

Also, please note I've added a check for existence into the new loop which iterates over the list of hosts files, and if none of the files were found (i.e. the number of files not found is equal to the length of the list), I output the error that you used to output before ("previous known host file not found"). Therefore the original check for existence became obsolete and I've removed it.

Thanks!
iordan

### CODE REVIEW

**Comment by risaacson** [comment]
@iiordanov What behavior are you trying to change for this? I have done some testing but I am not seeing a change in the ssh connection plugin execution.

**Comment by iiordanov** [comment]
If machines _are_ in /etc/ssh/ssh_known_hosts file, but _are not_ in the
user used to run ansible's ${HOME}/.ssh/known_hosts file, then ansible does
not "trust" them and parallel execution is broken.

On Mon, Mar 3, 2014 at 11:26 PM, Richard Isaacson
notifications@github.comwrote:

> @iiordanov https://github.com/iiordanov What behavior are you trying to
> change for this? I have done some testing but I am not seeing a change in
> the ssh connection plugin execution.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/6156#issuecomment-36591124
> .

## 

The conscious mind has only one thread of execution.

**Comment by risaacson** [comment]
@iiordanov That helps out a bit and I don't think I would have figured this out right away without that comment.

I was able to do a|b testing between devel and a branch with this change cherry-picked. The files I used for testing are in this gist: https://gist.github.com/risaacson/8097b8635ee7353ac2a1

Next time it would be helpful if you apply your changes to a branch that has a descriptive name. The CONTRIBUTING.md document.

Thanks for the contribution! This will definitely help speed up runs in some instances.

**Comment by mpdehaan** [comment]
It should be noted that this doesn't cover paramiko, so if someone wants paramiko to have the same behavior (about knowing when to lock to ask questions) it would need to be made more intelligent.

I'm ok with this, for the most part, but in case someone finds this later, heads up that "paramiko_ssh.py" was not yet modified.

**Comment by iiordanov** [comment]
Thanks guys! I don't think I'll have a chance to work on paramiko soon, but
if I do, I'll let you know.

Cheers!
iordan

On Tue, Mar 4, 2014 at 10:04 AM, Michael DeHaan notifications@github.comwrote:

> It should be noted that this doesn't cover paramiko, so if someone wants
> paramiko to have the same behavior (about knowing when to lock to ask
> questions) it would need to be made more intelligent.
> 
> I'm ok with this, for the most part, but in case someone finds this later,
> heads up that "paramiko_ssh.py" was not yet modified.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/6156#issuecomment-36632925
> .

## 

The conscious mind has only one thread of execution.

**Pull request merged**
