### PR TITLE
Backport/2.9/docs

### PR DESCRIPTION
**Pull request by acozine**
##### SUMMARY
Backports this week's docs changes for the upcoming release.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs.ansible.com

### CODE REVIEW

**Comment by Lunik** [comment]
#63670 should not be backported. Please read the full thread of the PR

**Comment by acozine** [comment]
All these changes are docs-only.

**Comment by acozine** [comment]
@Lunik isn't it better to have the examples correct for the code that exists in 2.9? The code changes in `devel` (2.10) and the docs updates that go with them make a great improvement. But we can't backport those changes.

**Comment by Lunik** [comment]
@acozine If we can't merge #63499 for now, then this make sense.

**Pull request merged**
