### PR TITLE
cloudstack: streamline modules doc

### PR DESCRIPTION
**Pull request by dpassante**
##### SUMMARY

This PR includes:
* Parameter types added
* Copyright format fixes
* Doc style fixes

I start by the first five modules to ensure I'm in the right way before changing the whole :)

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

cloudstack

### CODE REVIEW

**Comment by resmo** [comment]
btw I noticed, that ansible-lint does not like `local_action` anymore and suggest to use `delegate_to: localhost`. Should we follow that in the examples?

**Comment by dpassante** [comment]
I think we should follow that in examples, `delegate_to` seems to be more commonly used.

**Review by samccann — COMMENTED** [review]
Thanks @dpassante for the docs PR!  And it's good to keep the file counts low like this so they are easier to get reviewed.

Since you cleaned up cs_cluster.py, can you also remove it from here:
https://github.com/ansible/ansible/blob/devel/test/sanity/validate-modules/ignore.txt#L99

With your fixes, we hopefully won't need to ignore that module in sanity tests anymore!

**Comment by acozine** [comment]
Thanks for updating the docs - and for doing only a few files at a time! Mammoth PRs of this kind are hard to review.

**Comment by dpassante** [comment]
@samccann Thanks for review.
Unfortunately, it's still necessary to ignore this module since hypervisor choices in argument_spec also include lowercase hypervisor names.

~~~
ERROR: lib/ansible/modules/cloud/cloudstack/cs_cluster.py:0:0: E326 argument_spec for 'hypervisor' defines choices as '['KVM', 'kvm', 'VMware', 'vmware', 'BareMetal', 'baremetal', 'XenServer', 'xenserver', 'LXC', 'lxc', 'HyperV', 'hyperv', 'UCS', 'ucs', 'OVM', 'ovm', 'Simulator', 'simulator']' but documentation defines choices as '['KVM', 'VMware', 'BareMetal', 'XenServer', 'LXC', 'HyperV', 'UCS', 'OVM']'
~~~

**Comment by dpassante** [comment]
Should we add lowercase hypervisor names in the documentation?

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @dpassante for the Ansible doc fix. I'll open a separate issue to request someone simplify the code so that upper/lowercase is accepted w/o having to have both in the argspec.

**Comment by resmo** [comment]
regreted already a few times I did it this way.

**Pull request merged**
