### PR TITLE
AWS SSM Connection Plugin Unit Tests

### PR DESCRIPTION
**Pull request by deepsvc**
##### SUMMARY
This Pull Request covers the unit tests for AWS SSM Connection Plugin, introduced in the PR https://github.com/ansible/ansible/pull/49652

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
connection/aws_ssm

##### ADDITIONAL INFORMATION

This PR adds Unit Tests for AWS SSM Connection Plugin.

For execution following command can be used:
```bash
test/runner/ansible-test units --tox --python 2.7 test/units/plugins/connection/test_aws_ssm.py```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/111888/10/tests

**Comment by deepsvc** [comment]
@mattclay Hi, I fixed that import issue, and the current issue is with Python 2.6 version. As plugin only has support for Python 2.7. Unit tests also only supports for that. Can you please advise for this?

**Comment by mattclay** [comment]
@deepsvc You can use `skipif` to skip tests on Python 2.6.

See: https://docs.pytest.org/en/latest/skipping.html#id1

**Comment by agaur123** [comment]
Hey @mattclay, we have reviewed all the test cases and they are running absolutely fine. About the issue with Python 2.6, so that we also have fixed. Can you please review it.

**Comment by mattclay** [comment]
These tests should be in the same PR as the connection plugin since it hasn't been merged yet.

**Comment by Akasurde** [comment]
Hi @deepsvc, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
