### PR TITLE
Load Balancer creation support / module rename

### PR DESCRIPTION
**Pull request by claco**
As discussed earlier and up for review:
- Rename rax_clb to rax_clb_nodes as it's main function is to manage
  what nodes are in an exiting load balancer
- Add rax_clb that now does load balancer creation/deletion with a more
  detailed level than was possible in rax

### CODE REVIEW

**Comment by claco** [comment]
@sivel Started the work on the rax_clb rename/creation. WIP as it doesn't yet have some of the deeper levels, like specifying virtual ips with specific ip addresses/ports, accessList, connectionLogging, connectionThrottle, etc. I went for the top level necessities first.

**Comment by sivel** [comment]
I'll do my best to take a look over this today.

I think it is ok that it doesn't cover the full ability of the product/api at this point.  I'd go with the 80/20 rule.  Implement the functionality that the 80% are more likely to use, and work on the other 20% down the road.

**Comment by sivel** [comment]
Couple of quick things:
1. The notes section of the documentation should be updated. `RAX_CREDS` should actually be `RAX_CREDS_FILE`, See https://github.com/sivel/ansible/blob/rax-improvements/library/cloud/rax#L122-L128
2. Can you switch the `#<<INCLUDE_ANSIBLE_MODULE_COMMON>>` line over to the new style boilerplate? See https://github.com/sivel/ansible/blob/rax-improvements/library/cloud/rax#L614
3. Although not required for the project in whole, please make sure to PEP8 format the code for rax modules, excluding the DOCUMENTATION section.
4. Try to standardize on quote types for strings, I personally prefer `'` (single quotes)
5. To make it easier for contribution in the future, please alphabatize the DOCUMENTATION, AnsibleModule call and the `module.params.get` section (I'm not as concerned with order of parameters to the functions
6. Avoid creating variable names that override builtin functions such as `type`
7. Add support for dealing with a load balancer by ID
8. Use something less static for building the 'instance' dict, such as how it looks in the refactor of the rax module: https://github.com/sivel/ansible/blob/rax-improvements/library/cloud/rax#L222-L225
9. fail_json, should return more than `msg`, where appropriate, so that you can act on failures and decide when you think it is failed using failed_when, in addition to `msg` it should also return the `balancers` attr.
10. There are some unused imports: `time` and `exc`

This is just a quick list based on a code review, I'll run some functional tests a bit later.

**Comment by claco** [comment]
Thanks that that list. Based on some of this things, I should probably go update the rax_network PR as well. :-)

**Comment by sivel** [comment]
I'm also having trouble getting it to run right now.  Using the example provided I'm getting back a 400 `JSON does not match the expected schema` from the API.  I'm just starting to troubleshoot now.

**Comment by claco** [comment]
I would bet it's meta data related. {} vs. [], so I probably forgot to remote that block.

**Comment by sivel** [comment]
Yes, I did track it down to being metadata

**Comment by claco** [comment]
I meant to map the hash to the crazy array format that part of the api uses, and apparently put that in a different branch. did I mention WIP? :-P

**Comment by sivel** [comment]
No prob, this is why you need testers ;)  I'll keep an eye here an continue testing.

**Comment by sivel** [comment]
For current purposes, I have the metadata stuff commented out, but here are a few observations:
1. `wait_timeout` is not respected, `pyrax.utils.wait_for_build` is hardcoded for `interval=5` and `attempts=5`
2. This module is only idempotent in the respect that it won't touch an LB of the same name, I would like to see this "ensure" a configuration of a LB.  Such as, get it's details, and only update if they don't match, and if they do match, don't update (making sure to set `changed` appropriately).  You will likely have to do this one attribute at a time, since the objects won't be identical (nodes and such).
3. When checking the status to determine if you use fail_json or exit_json, you should also take into account a situation where we don't wait, but should still get back whatever info is available for that LB.  So the line `if balancer.status == 'ACTIVE':` should probably be `if balancer.status == 'ACTIVE' or not wait=:`

**Comment by jctanner** [comment]
@sivel @claco What's the current status for this PR? Are you guys still working on it or is it ready to go?

**Comment by sivel** [comment]
@jctanner give us a day or so.  I feel comfortable with it, but we will need to rebase and squash.  I'll reach out to @claco to verify as well.

**Comment by jctanner** [comment]
Closed per #4835

**Pull request closed without merging**
