### PR TITLE
Fix huawei file can not get ansibot response

### PR DESCRIPTION
**Pull request by zhongjun2**
##### SUMMARY
Fix huawei file can not get ansibot response

lib/ansible/module_utils/hwc_utils.py
lib/ansible/plugins/doc_fragments/hwc.py
 doesn't get labels/maintainers set

ansible/ansible#54836
Labels not set

#54833 did work

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

### CODE REVIEW

**Comment by bcoca** [comment]
can you explain the problem this solves? what errors are you getting? what behaviour is not happening?

**Comment by zhongjun2** [comment]
ansible/ansible#54832
labels are set

Is the following inference correct?
If we defined something as a folder, then we should define others as a folder.
It means if we set “cloud/vmware/: &vmware” [1] we also should set “module_utils/vmware: *vmware”[2]
Even if the module_utils/vmware.py is a file

[1] https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml#L184
[2] https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml#L825

**Review by gundalow — CHANGES_REQUESTED** [review]
Hi,
As I mentioned on IRC I think this is a problem with Ansibulbot, so need raising via https://github.com/ansible/ansibullbot/issues

**Comment by zhongjun2** [comment]
The issue raised in Ansibulbot is :  https://github.com/ansible/ansibullbot/issues/1186

**Comment by gundalow** [comment]
Issue tracked in bot repo.

**Pull request closed without merging**
