### PR TITLE
added ability to override jinja enviornment from first line of template

### PR DESCRIPTION
**Pull request by bcoca**
now you can put jinja2 options in the first line of the template (will get removed from output)

It MUST start the first line with '#env:', all valid jinja environment settings will be updated before processing the template.

example:
# env: variable_end_string: @@, variable_start_string: @@

this changes how jinja2 substitutes variables from looking at  {{ var }} to looking at @@ var @@

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good, I would probably change "env:" to "jinja2:" so it's very clear what it is doing when someone reads the template.

**Comment by bcoca** [comment]
Updated as per review, now uses #jinja2: as a override code

**Comment by mpdehaan** [comment]
ugh, I totally mangled history for this in github when I fixed some attribution issues.  Do you mind trying to rebase this and resubmitting?  you may need to check out the repo again. 

Very sorry!

**Comment by bcoca** [comment]
Will get you patch/pull today.

Brian Coca

**Pull request closed without merging**
