### PR TITLE
Add obsdpkg: package management for OpenBSD.

### PR DESCRIPTION
**Pull request by eest**
This is a module used to manage packages on OpenBSD.
I also include a patch for library/setup that makes the pkg_mgr fact available.

Review and input from @dhozac.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Generally looks good.  One naming question though...

Most of the other package managers are named after the command, though obviously this is split into a few.   It seems simpler though, as "obsdpkg" is a bit hard for me to type?

Perhaps it should be called 'pkg_add' (even though it also supports state=absent)?

It's also available for a bit more than OpenBSD, technically.

(I also noticed a "obsdpkg" and a "bsdpkg" both in the examples)

**Comment by eest** [comment]
The reason I made the decision to call it "obsdpkg" is that I want to be clear that that this module is used for managing packages on OpenBSD, and not other systems that happen to have similar tools. Even though the names of the tools are shared among for example FreeBSD and OpenBSD, the implementations differ.

(As you already hinted, I also think using "pkg_add" to remove a package sounds pretty confusing).

The differing examples have been fixed in the last commit.

**Comment by mpdehaan** [comment]
Ok, compromise then, how about openbsd_pkg?

**Comment by eest** [comment]
This is fine with me. I will close this PR and return with the new name.

**Comment by mpdehaan** [comment]
great, thanks!

**Pull request closed without merging**
