### PR TITLE
Fix omapi_host on python3 (#67559)

### LINKED ISSUE #67559: omapi_host fails on python3 with TypeError: a bytes-like object is required, not 'str'
##### SUMMARY
omapi_host needs to use byte strings on python3 otherwise getting "TypeError: a bytes-like object is required, not 'str'" errors

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
omapi_host module

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```
##### STEPS TO REPRODUCE
Create or remote a DHCP reservation using omapi_host module

##### EXPECTED RESULTS

Completed without errors

##### ACTUAL RESULTS

```paste below
"module_stdout": "Traceback (most recent call last):\r
  File \"/root/.ansible/tmp/ansible-tmp-1582083593.0190487-137096835301943/AnsiballZ_omapi_host.py\", line 102, in <module>\r
    _ansiballz_main()\r
  File \"/root/.ansible/tmp/ansible-tmp-1582083593.0190487-137096835301943/AnsiballZ_omapi_host.py\", line 94, in _ansiballz_main\r
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r
  File \"/root/.ansible/tmp/ansible-tmp-1582083593.0190487-137096835301943/AnsiballZ_omapi_host.py\", line 40, in invoke_module\r
    runpy.run_module(mod_name='ansible.modules.net_tools.omapi_host', init_globals=None, run_name='__main__', alter_sys=True)\r
  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r
    return _run_module_code(code, init_globals, run_name, mod_spec)\r
  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r
    mod_name, mod_spec, pkg_name, script_name)\r
  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r
    exec(code, run_globals)\r
  File \"/tmp/ansible_omapi_host_payload_4n9lnp9o/ansible_omapi_host_payload.zip/ansible/modules/net_tools/omapi_host.py\", line 315, in <module>\r
  File \"/tmp/ansible_omapi_host_payload_4n9lnp9o/ansible_omapi_host_payload.zip/ansible/modules/net_tools/omapi_host.py\", line 304, in main\r
  File \"/tmp/ansible_omapi_host_payload_4n9lnp9o/ansible_omapi_host_payload.zip/ansible/modules/net_tools/omapi_host.py\", line 154, in __init__\r
  File \"/tmp/ansible_omapi_host_payload_4n9lnp9o/ansible_omapi_host_payload.zip/ansible/modules/net_tools/omapi_host.py\", line 159, in connect\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 980, in __init__\r
    self.initialize_authenticator(newauth)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 1064, in initialize_authenticator\r
    response = self.query_server(msg)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 1053, in query_server\r
    self.send_message(message)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 1044, in send_message\r
    self.protocol.send_message(message, sign)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 944, in send_message\r
    message.sign(self.authenticators[self.defauth])\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 466, in sign\r
    self.signature = authenticator.sign(self.as_string(forsigning=True))\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 457, in as_string\r
    self.serialize(ret, forsigning)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 443, in serialize\r
    outbuffer.add_bindict(self.obj)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 212, in add_bindict\r
    self.add_net16string(key).add_net32string(value)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 183, in add_net32string\r
    return self.add_net32int(len(string)).add(string)\r
  File \"/root/.local/lib/python3.6/site-packages/pypureomapi.py\", line 145, in add\r
    self.buff.write(data)\r
TypeError: a bytes-like object is required, not 'str'\r"

```

### PR DESCRIPTION
**Pull request by amasolov**
##### SUMMARY

Fixes #67559 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

module omapi_host

### CODE REVIEW

**Comment by amasolov** [comment]
ready_for_review

**Review by nerzhul — APPROVED** [review]
Fine to me, thanks

**Comment by jeanfabrice** [comment]
Hi,
same issue here. Can this be merged?

**Comment by amasolov** [comment]
Moved to [#788](https://github.com/ansible-collections/community.general/pull/788) in ansible-collections/community.general

**Pull request closed without merging**
