### PR TITLE
aci_bd_dhcp_label: New module to manage DHCP Labels

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This is a new ACI module to manage DHCP Labels for Bridge Domains.

This is a reworked version of #32571

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
aci_bd_dhcp_label

### CODE REVIEW

**Comment by dagwieers** [comment]
cc @mtorelli @amitswt

**Comment by mtorelli** [comment]
Can we change

-owner=dict(type='str'),

+owner=dict(type='str', default='infra', aliases=['scope'], choices=['infra', 'tenant']),

So that this object matches the default value, name (i.e., scope) and the possible choices that exist in the UI.

Mike

**Comment by dagwieers** [comment]
@mtorelli Definitely, I think scope is a much better name for this, and naming should follow the UI as much as possible. Thanks for the feedback.

PS If you could test this on ACI infrastructure, that would be welcome.

**Comment by mtorelli** [comment]
Works with Ansible 2.9.0 but you have to make the modification below since "owner" is now "scope".

`*** aci_bd_dhcp_label.py	2019-11-08 12:53:19.000000000 -0500
--- modified.py	2019-11-08 12:52:11.000000000 -0500
***************
*** 234,241 ****
          argument_spec=argument_spec,
          supports_check_mode=True,
          required_if=[
!             ['state', 'absent', ['bd', 'tenant', 'dhcp_label', 'owner']],
!             ['state', 'present', ['bd', 'tenant', 'dhcp_label', 'owner']],
          ],
      )
  
--- 234,241 ----
          argument_spec=argument_spec,
          supports_check_mode=True,
          required_if=[
!             ['state', 'absent', ['bd', 'tenant', 'dhcp_label', 'scope']],
!             ['state', 'present', ['bd', 'tenant', 'dhcp_label', 'scope']],
          ],
      )
`

**Comment by aciguru** [comment]
https://github.com/CiscoDevNet/ansible-aci/issues/15

**Pull request closed without merging**
