### PR TITLE
add ability to add tags

### PR DESCRIPTION
**Pull request by brianhhq**
##### SUMMARY
add ability to add tags into ecs cluster

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by brianhhq** [comment]
cool. ready to ship it. @Java1Guy please take a look at this PR. Much appreciated.

**Comment by brianhhq** [comment]
bot_status

**Comment by brianhhq** [comment]
@Java1Guy please take a look at this PR. Much appreciated.

**Comment by brianhhq** [comment]
bot_status

**Comment by brianhhq** [comment]
ready_for_review

**Comment by wimnat** [comment]
shipit

**Pull request closed without merging**
