### PR TITLE
issue 2625

### PR DESCRIPTION
**Pull request by vmindru**
we can use this as a workaround, until we decide what is to be done with the issue itself.
https://github.com/ansible/ansible-modules-core/issues/2625

### CODE REVIEW

**Comment by jimi-c** [comment]
I understand the problem, it looks like we should be checking the status of the async task properly there and making sure we get a started=true result before deleting the tmp dir. Doing an arbitrary sleep there will probably work 99% of the time, however I'd prefer this to be fixed properly and not covered up by that sleep.

**Comment by vmindru** [comment]
surely a proper fix is better than a simple sleep, the whole poitn is rather  a workaround for someone who needs this fixed sooner then later and , if we don't have time for a proper fix , and to revel the actual problem  @jimi-c  what is the mailing list where such topics should be discussed, e.g. a collective decision on what shall be the approach to get this  fixed.  I am failry new to the community and not familiar with the habbits around.

**Comment by vmindru** [comment]
Ok let's cancel this PR , this actually should be done in the async_wrapper , initial sleep here was 1 sec and seems not enough on fast connection systems, also as teh comment sugests on the initial code probably this has to be done by IPC. 

```
vmindru@vmhodesk:~/proj/ansible/ansible-devel/lib/ansible/modules/core/utilities/logic$ git diff
diff --git a/utilities/logic/async_wrapper.py b/utilities/logic/async_wrapper.py
index 55f5283..884447c 100644
--- a/utilities/logic/async_wrapper.py
+++ b/utilities/logic/async_wrapper.py
@@ -153,7 +153,7 @@ if __name__ == '__main__':
             notice("Return async_wrapper task started.")
             print json.dumps({ "started" : 1, "ansible_job_id" : jid, "results_file" : job_path })
             sys.stdout.flush()
-            time.sleep(1)
+            time.sleep(2)
             sys.exit(0)
         else:
             # The actual wrapper process
vmindru@vmhodesk:~/proj/ansible/ansible-devel/lib/ansible/modules/core/utilities/logic$ 
```

**Comment by willthames** [comment]
@vmindru - here's the community page with details about where to have discussions: http://docs.ansible.com/ansible/community.html

This one would fit well in ansible-devel (mailing list or IRC!)

**Pull request closed without merging**
