### PR TITLE
IP Infusion OcNOS support

### PR DESCRIPTION
**Pull request by momose**
##### SUMMARY

Supported IP Infusion whitebox switch OS, OcNOS.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ocnos

##### ADDITIONAL INFORMATION

This is a second pull request after fixed issues in pointed out in 1st PR.

```paste below

```

### CODE REVIEW

**Comment by abenokraitis** [comment]
Greetings, although we haven't updated ansibot yet, no new modules will be included in 2.10 due to the disaggregation effort underway. Please move/migrate all content in ansible to a Collection and publish it in Galaxy going forward. Here is a good primer on Collections with additional developer resources: https://www.ansible.com/blog/getting-started-with-ansible-collections

**Comment by momose** [comment]
Thank you for your comment. 
I was also guided to move our modules to Collection on IRC. I'll move them.

And I understood new modules won't be merged in 2.10, but is this policy that platform dependent modules will not be merged to Ansible core repository applied to subsequent versions as well? I just want to confirm if there is no chance to be merged such modules.

Thanks,

**Comment by abenokraitis** [comment]
@momose take a look at what is being proposed as 2.10 and going forward: https://github.com/ansible-community/collection_migration/blob/master/scenarios/nwo/ansible.yml All subsequent content will continue to be as collections.

**Comment by momose** [comment]
@abenokraitis Thank you for the pointer. I'll close this PR.

**Pull request closed without merging**
