### PR TITLE
apt update - resending as asked

### PR DESCRIPTION
**Pull request by RaymiiOrg**
Please ignore the yum stuff.  Resding the apt module update as requested.

### CODE REVIEW

**Comment by mpdehaan** [comment]
ok so I basically need to add the git remote and cherry-pick some but not all of these commits?  Can you just send me a pull request for only the apt changes?

**Comment by RaymiiOrg** [comment]
How do I do the latter?

**Comment by mpdehaan** [comment]
ok, so on a clean checkout (or another branch, if this was done on a
branch), it looks roughly like this:

git checkout -b new_branch_for_apt
git cherry-pick <SHA-CODE> <SHA-CODE> <SHA-CODE>
git checkout -b devel
git checkout -b new_branch_for_apt_squashed
git merge new_branch_for_apt --squash

# submit pull request from this branch

If you have the commits on your own devel, it's a little messier, and is a
reason you really want to start a new branch for each commit.

**Comment by dhozac** [comment]
Superseded by #2238.

**Pull request closed without merging**
