### PR TITLE
Add os_profile to VM facts, allow to filter by OS

### PR DESCRIPTION
**Pull request by pmarques**
##### SUMMARY

Adding os_profile dictionary to host_vars. Allow the dynamic inventory to filter by OS.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

lib/ansible/plugins/inventory/azure_rm.py

### CODE REVIEW

**Comment by Fred-sun** [comment]
@nitzmahone @jborean93

**Comment by Fred-sun** [comment]
@nitzmahone @jborean93 Could you help review this PR? The contributor request review from you? Thanks!

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
LGTM. @zikalino  can  you pls review this PR also?

**Comment by Fred-sun** [comment]
@zikalino  Please help review and push merged ! Thanks!

**Comment by pmarques** [comment]
TBH, I got some doubts about the way I implemented this. When we use a marketplace image, there is no osProfile property. while I'm think about this any comment will be appreciated.

**Comment by Fred-sun** [comment]
@pmarques Thanks for your update, Could you help confirm that how about the PR going ahead? need changed or need push for review?  Thanks!

**Comment by Fred-sun** [comment]
@zikalino Please help review this PR and push for merge! Thanks!

**Comment by yungezz** [comment]
@nitzmahone  Matt, need your reviewing.

**Comment by Fred-sun** [comment]
@nitzmahone Please help review this PR when you're available! Thanks!

**Comment by Fred-sun** [comment]
@nitzmahone Matt, need your reviewing.

**Comment by Fred-sun** [comment]
kindly ping

**Comment by Fred-sun** [comment]
@zikalino @nitzmahone

**Comment by Fred-sun** [comment]
@zikalino @nitzmahone review_need

**Comment by Fred-sun** [comment]
@nitzmahone @zikalino Please help review this when you're available! Thanks!

**Comment by Fred-sun** [comment]
@zikalino @nitzmahone review_need

**Comment by yuwzho** [comment]
shipit

**Pull request merged**
