### PR TITLE
[WIP] ssh: Display ssh config in verbose mode

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Based on work done by Alikins (https://github.com/ansible/ansible/pull/23241)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/connection/ssh.py

##### ADDITIONAL INFORMATION
Based on https://github.com/ansible/ansible/pull/23241

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
**1.** I tried to execute:
```
ansible myhostname -m ping -vvvv
```
It returned SSH CONFIG DEBUG with parameters and corresponding values, but in the end:
```
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 142, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 644, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 721, in _execute_module
    self._make_tmp_path()
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 289, in _make_tmp_path
    tmpdir = self._remote_expand_user(remote_tmp, sudoable=False)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 592, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 986, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 1091, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 334, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 975, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 739, in _bare_run
    os.write(self.sshpass_pipe[1], to_bytes(self._play_context.password) + b'\n')
OSError: [Errno 9] Bad file descriptor

myhostname | FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```
Configuration of both systems below:
```
# uname -a
Linux myhostname 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
# cat /etc/*release
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
```
ssh packages version
```
libssh2.x86_64                       1.4.3-10.el7_2.1                  @anaconda
openssh.x86_64                       7.4p1-16.el7                      @base    
openssh-clients.x86_64               7.4p1-16.el7                      @base    
openssh-server.x86_64                7.4p1-16.el7                      @base    
sshpass.x86_64                       1.06-2.el7                        @extras  
```

I tried the same command without your changes and it has been done without any errors.

**2.** This function seems quite useful but now it's difficult to know about this, so better if this possibility will be mentioned in documentation

**Comment by Andersson007** [comment]
needs_revision

**Comment by alikins** [comment]
+1 to adding collection of the ssh version as well

**Comment by alikins** [comment]
@Andersson007 and 'ansible myhostname -m ping -vvvv' works without this pr?

**Comment by Andersson007** [comment]
> @Andersson007 and 'ansible myhostname -m ping -vvvv' works without this pr?

Yes, @alikins , exactly. I tried with this PR and without on the same pair of servers.

**Comment by Andersson007** [comment]
@alikins @Akasurde, today I fetched Ansible repo and tried "ansible myhostname -m ping -vvvv" for confidence, caught this exception again, the full output below:
```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
SSH password: 
BECOME password[defaults to SSH password]: 
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /root/ansible/lib/ansible/plugins/callback/minimal.pyc
META: ran handlers
<myhostname> ESTABLISH SSH CONNECTION FOR USER: andreyk
<myhostname> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=andreyk -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/fc3d08c546 spblnx125 -G
<myhostname> (0, 'user andreyk\nhostname spblnx125\nport 22\naddressfamily any\nbatchmode no\ncanonicalizefallbacklocal yes\ncanonicalizehostname false\nchallengeresponseauthentication yes\ncheckhostip yes\ncompression yes\ncontrolmaster auto\nenablesshkeysign no\nclearallforwardings no\nexitonforwardfailure no\nforwardagent no\nforwardx11 no\nforwardx11trusted yes\ngatewayports no\ngssapiauthentication yes\ngssapidelegatecredentials no\nhashknownhosts no\nhostbasedauthentication no\nidentitiesonly no\nkbdinteractiveauthentication yes\nnohostauthenticationforlocalhost no\npasswordauthentication yes\npermitlocalcommand no\nprotocol 2\nproxyusefdpass no\npubkeyauthentication yes\nrequesttty auto\nrhostsrsaauthentication no\nrsaauthentication yes\nstreamlocalbindunlink no\nstricthostkeychecking ask\ntcpkeepalive yes\ntunnel false\nuseprivilegedport no\nverifyhostkeydns false\nvisualhostkey no\nupdatehostkeys false\ncanonicalizemaxdots 1\ncompressionlevel 6\nconnectionattempts 1\nforwardx11timeout 1200\nnumberofpasswordprompts 3\nserveralivecountmax 3\nserveraliveinterval 0\nciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc\ncontrolpath /root/.ansible/cp/fc3d08c546\nhostkeyalgorithms ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss\nhostbasedkeytypes ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss\nkexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1\nloglevel DEBUG3\nmacs umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\npubkeyacceptedkeytypes ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss\nxauthlocation /usr/bin/xauth\nidentityfile ~/.ssh/id_rsa\nidentityfile ~/.ssh/id_dsa\nidentityfile ~/.ssh/id_ecdsa\nidentityfile ~/.ssh/id_ed25519\ncanonicaldomains\nglobalknownhostsfile /etc/ssh/ssh_known_hosts /etc/ssh/ssh_known_hosts2\nuserknownhostsfile ~/.ssh/known_hosts ~/.ssh/known_hosts2\nsendenv LANG\nsendenv LC_CTYPE\nsendenv LC_NUMERIC\nsendenv LC_TIME\nsendenv LC_COLLATE\nsendenv LC_MONETARY\nsendenv LC_MESSAGES\nsendenv LC_PAPER\nsendenv LC_NAME\nsendenv LC_ADDRESS\nsendenv LC_TELEPHONE\nsendenv LC_MEASUREMENT\nsendenv LC_IDENTIFICATION\nsendenv LC_ALL\nsendenv LANGUAGE\nsendenv XMODIFIERS\nfingerprinthash SHA256 MD5\nconnecttimeout 10\ntunneldevice any:any\ncontrolpersist 60\nescapechar ~\nipqos lowdelay throughput\nrekeylimit 0 0\nstreamlocalbindmask 0177\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\n')
<myhostname> SSH CONFIG DEBUG: user andreyk
hostname myhostname
port 22
addressfamily any
batchmode no
canonicalizefallbacklocal yes
canonicalizehostname false
challengeresponseauthentication yes
checkhostip yes
compression yes
controlmaster auto
enablesshkeysign no
clearallforwardings no
exitonforwardfailure no
forwardagent no
forwardx11 no
forwardx11trusted yes
gatewayports no
gssapiauthentication yes
gssapidelegatecredentials no
hashknownhosts no
hostbasedauthentication no
identitiesonly no
kbdinteractiveauthentication yes
nohostauthenticationforlocalhost no
passwordauthentication yes
permitlocalcommand no
protocol 2
proxyusefdpass no
pubkeyauthentication yes
requesttty auto
rhostsrsaauthentication no
rsaauthentication yes
streamlocalbindunlink no
stricthostkeychecking ask
tcpkeepalive yes
tunnel false
useprivilegedport no
verifyhostkeydns false
visualhostkey no
updatehostkeys false
canonicalizemaxdots 1
compressionlevel 6
connectionattempts 1
forwardx11timeout 1200
numberofpasswordprompts 3
serveralivecountmax 3
serveraliveinterval 0
ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
controlpath /root/.ansible/cp/fc3d08c546
hostkeyalgorithms ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
hostbasedkeytypes ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
loglevel DEBUG3
macs umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
pubkeyacceptedkeytypes ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
xauthlocation /usr/bin/xauth
identityfile ~/.ssh/id_rsa
identityfile ~/.ssh/id_dsa
identityfile ~/.ssh/id_ecdsa
identityfile ~/.ssh/id_ed25519
canonicaldomains
globalknownhostsfile /etc/ssh/ssh_known_hosts /etc/ssh/ssh_known_hosts2
userknownhostsfile ~/.ssh/known_hosts ~/.ssh/known_hosts2
sendenv LANG
sendenv LC_CTYPE
sendenv LC_NUMERIC
sendenv LC_TIME
sendenv LC_COLLATE
sendenv LC_MONETARY
sendenv LC_MESSAGES
sendenv LC_PAPER
sendenv LC_NAME
sendenv LC_ADDRESS
sendenv LC_TELEPHONE
sendenv LC_MEASUREMENT
sendenv LC_IDENTIFICATION
sendenv LC_ALL
sendenv LANGUAGE
sendenv XMODIFIERS
fingerprinthash SHA256 MD5
connecttimeout 10
tunneldevice any:any
controlpersist 60
escapechar ~
ipqos lowdelay throughput
rekeylimit 0 0
streamlocalbindmask 0177

<myhostname> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=andreyk -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/fc3d08c546 myhostname -V
<myhostname> (0, '', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\n')
<myhostname> SSH VERSION: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

<myhostname> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=andreyk -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/fc3d08c546 spblnx125 '/bin/sh -c '"'"'echo ~andreyk && sleep 0'"'"''
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 142, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 644, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 721, in _execute_module
    self._make_tmp_path()
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 289, in _make_tmp_path
    tmpdir = self._remote_expand_user(remote_tmp, sudoable=False)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 592, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 986, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 1091, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 334, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 975, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/root/ansible/lib/ansible/plugins/connection/ssh.py", line 739, in _bare_run
    os.write(self.sshpass_pipe[1], to_bytes(self._play_context.password) + b'\n')
OSError: [Errno 9] Bad file descriptor

myhostname | FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```
After that I tried the same command with arg -vvv, -vv and without this - no error occurred.

Additionally
```
# ansible-test sanity --python 2.7  --base-branch devel lib/ansible/plugins/connection/ssh.py
```
passed well

**Comment by gundalow** [comment]
@akasurde said this requires further testing and isn't needed to get into Ansible 2.8 so marking as WIP.

Testing & review feedback welcome.

**Comment by Akasurde** [comment]
I am no longer working on this.

**Pull request closed without merging**
