### PR TITLE
Enable environment keyword at play level

### PR DESCRIPTION
**Pull request by ks888**
##### Issue Type:

Feature Pull Request
##### Ansible Version:

`ansible 1.8 (devel f4d649bea0)`
##### Environment:

N/A
##### Summary:

Enable environment keyword at play level. This feature enables to setup environment variables at play level.

[This post in ML](https://groups.google.com/forum/#!topic/ansible-project/w3aqRqZ1hIw) also suggests that this feature would be useful.
##### How to use:

```
- hosts: testhost
  roles:
     - php
     - nginx
  environment:
    http_proxy: http://proxy.example.com:8080
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Very cool feature idea! 

Note to us, we should mention this in the docs once merged.

**Comment by bcoca** [comment]
#  Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by ks888** [comment]
@bcoca
Hi, I rebased the pr. Please take a look!

**Comment by gildegoma** [comment]
Absolutely :+1: (vote to shift to P1 priority ;-)

In my opinion, this is a _must have feature_ to allow wider galaxy roles sharing. So far, I use following trick for each task that potentially could be executed behind a corporate proxy (depending of network context):

```
- name: my task
  whatever_module_you_want: ...
  environment: '{{ proxy_env }}'
```

In a "no proxy" context, a dummy dictionary must be created, as illustrated below:

```
#
# 'No proxy' is implemented with 'proxy_env' dictionary 
# that does not contain http_proxy and https_proxy keys
#
proxy_env:
  fake_dictionary: something
```

**Comment by gildegoma** [comment]
I'll give a [try to this PR](http://docs.ansible.com/developing_test_pr.html) this week.

**Comment by gildegoma** [comment]
@mpdehaan @bcoca it works for me!  Tested on `1.9 devel` (41399dedaf923a9b95dd0c047803b9e8fd738e89) and `v1.8.2`. 
I verified this with Ubuntu 12.04 for both, the control machine and the managed server.

@ks888 Thanks a lot for this patch :green_heart: :yellow_heart: :heart:! 
I am looking forward to getting this feature in future Ansible release.

**Comment by ks888** [comment]
@gildegoma Thank you for testing my pr. I definitely agree with your opinion, that is, this feature promotes  wider galaxy roles sharing.

**Comment by gildegoma** [comment]
@bcoca thank you! :grinning:

**Pull request merged**
