### PR TITLE
Support unix socket with urls/uri

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY

Support unix socket with urls/uri. See #42341

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/urls.py
lib/ansible/modules/net_tools/basic/uri.py

##### ANSIBLE VERSION

```
2.7
```

##### ADDITIONAL INFORMATION
```
$ ansible localhost -m uri -a 'url=http://localhost/ unix_socket=/Users/matt/projects/flask/get.sock'
localhost | SUCCESS => {
    "changed": false,
    "connection": "close",
    "content_length": "2",
    "content_type": "text/html; charset=utf-8",
    "cookies": {},
    "cookies_string": "",
    "date": "Wed, 01 Aug 2018 18:11:07 GMT",
    "msg": "OK (2 bytes)",
    "redirected": false,
    "server": "gunicorn/19.9.0",
    "status": 200,
    "url": "http://localhost/"
}
```

### CODE REVIEW

**Review by bcoca — APPROVED** [review]

**Comment by sivel** [comment]
~Currently missing https functionality.~

**Comment by sivel** [comment]
@jamescassell I see you gave this a 👍

Were you able to test this and verify that it met your needs?

**Comment by akamac** [comment]
I'm eager to see this PR merged!

**Comment by sivel** [comment]
@akamac is it possible that you could test this PR and let us know if it is working for you?

**Comment by akamac** [comment]
@sivel works for me with docker socket:
```
- name: get node swarm state
  uri:
    unix_socket: /var/run/docker.sock
    url: http://localhost/nodes?filters={{ filters | to_json | urlencode }}
    return_content: yes
    status_code:
      - 200
      - 503
  vars:
    filters:
      name: "{ '{{ ansible_hostname }}': true }"
  register: node_info
  changed_when: false
```

**Pull request merged**
