### PR TITLE
Add win_mssql_query module: Module for query MSSQL database

### PR DESCRIPTION
**Pull request by dlazz**
##### SUMMARY
This new module allows user to query MSSQL Server databases
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
win_mssql_query

##### ANSIBLE VERSION

```
2.8
```

##### ADDITIONAL INFORMATION
Example: List all the databases on a SQL Server
```
tasks:
    - name: get databases
      win_mssql_query:
        query: "SELECT name FROM sys.databases" 
        server_instance: localhost
        server_instance_user: sa
        server_instance_password: "{{ sa }}"
      register: databases

    - debug:
        msg: "{{ item.name }}"
      loop: "{{ databases.output }}"
      when: databases.output != []
```
Output:
```

PLAY [win_mssql_query] *************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [ansible]

TASK [get databases] ***************************************************************************************************************************************************************************
changed: [ansible-test] => {"changed": true, "output": [{"name": "master"}, {"name": "tempdb"}, {"name": "model"}, {"name": "msdb"}]}

TASK [debug] ***********************************************************************************************************************************************************************************
ok: [ansible] => (item={'name': 'master'}) => {
    "msg": "master"
}
ok: [ansible] => (item={'name': 'tempdb'}) => {
    "msg": "tempdb"
}
ok: [ansible] => (item={'name': 'model'}) => {
    "msg": "model"
}
ok: [ansible] => (item={'name': 'msdb'}) => {
    "msg": "msdb"
}

PLAY RECAP *************************************************************************************************************************************************************************************
ansible               : ok=3    changed=1    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by it-praktyk** [comment]
I'm for no.

IMHO executing SQL queries - e.g. due to a lack of idempotency - should not be available as a built-in Ansible module.

**Comment by dagwieers** [comment]
Idempotency is not a requirement for modules. Some things cannot be idempotent, but are still useful for automation and are welcome in Ansible.

That said, doing queries is idempotent in itself, as it is read-only (does not make changes).

**Comment by it-praktyk** [comment]
@dagwieers, the query can be - as I understand - any correct SQL command also e.g. 'UPDATE'.

The integration tests - as I expect - will not really run under Ansible CI because they require installed MSSQL Server that is not available under them.

**Comment by dagwieers** [comment]
@it-praktyk In that case it won't be *guaranteed* idempotent, but that's not a reason for not including modules. There may be other reasons though...

**Comment by mattclay** [comment]
@dlazz It would be good to run these tests in CI. How long does a minimal install of SQL Server 2017 Express Edition take? If it's not too long and can be automated as part of the test (when SQL Server isn't already installed), that would allow us to run the tests on at least 2012 R2 and 2016.

**Comment by dlazz** [comment]
@it-praktyk I ensure that tests work, you can try them yourself, the only problem here is that unfortunately there isn't a sql express installation available. I tried to automate a minimal sql express setup with or without chocolatey, but I always ran in several problems, I'll try it agin..

This module isn't idempotent and potentially dangerous, you can do every query you want if your user has high privileges, you can virtually drop a database (win_file module could be dangerous too if you accidentally delete a directory). But at the same time it's very powerful and helped me many times to perform multiple tasks on several sql servers or allowing non technical users to run on demand maintenance tasks, providing them ad hoc playbooks on a CI.

I decided to share thinking it could be useful for others, but guys, if you don't think so, no problems, merging is not mandatory ;)

@mattclay I will try to add the sql server setup in tests, maybe this time it will work! 

Thanks you all

**Comment by zoredache** [comment]
It sure seems like it would be a good idea to come up with a way that you could support parameterized queries if this module is going to be accepted.  If there is a is a query module for a database, then someone is almost certainly going to try to construct a query from un-trusted facts, vars, or task results, and and we might just get a [Bobby tables](https://m.xkcd.com/327/) situation.

**Comment by varunchopra** [comment]
@it-praktyk I suppose @dagwieers was referring to `SELECT` statements specifically as from a programming perspective, it's what you'd call "querying".

I welcome this module honestly. Idempotence isn't required in this case. Even if it is, we can add an optional `check: SELECT id FROM tablename` or something to check if a result exists, and execute the `query: <statement>` only if that `id` doesn't exist.

Should also add the option of executing `.sql` files.

As for MSSQL, there are a bunch of roles that can automate the installation of Express I think.

**Comment by schwartzmx** [comment]
@zoredache This module could support parameterized queries,  while also not having to require the SQLPS module (`Invoke-SqlCmd`).   Here's an example gist I have from a while back, https://gist.github.com/schwartzmx/27a8289f8cece6c9151ed9a9520a78dd

On the topic of idemptotency,  any query could be made idempotent.   There are constructs such as `MERGE` in t-sql,  and other ways to ensure idempotency via t-sql.

**Comment by dagwieers** [comment]
@chopraaa Yup, I assumed it was only possible to do queries, and I guess that's what a lot of people would expect based on the name. So maybe the module could be named differently to avoid any confusion, eg. **win_mssql_client** or **win_mssql_command**.

@schwartzmx When we say a module is idempotent, we usually mean that every use is guaranteed to be idempotent. Obviously, like **win_command**, some uses can be made idempotent, but that doesn't mean the module is idempotent (otherwise we could claim that every module is idempotent). It is a semantic discussion.

**Comment by jhawkesworth** [comment]
I inherited a module to query a different database which supports an optional idempotence mode - I think this could be made to do the same thing (sorry I realize I never answered question above from ages go).
The way it works is there's the main 'query' arg, but also optional 'creates' or 'deletes' args, both of which can take another sql statement.  If the 'creates' returns > 0 rows then the main 'query' does not get run (as it is assumed to be created).  Equally if 'deletes' returns 0 rows then the main query is not run (as it is assumed the necessary rows for the main query have been deleted.

You can obviously make a mess if you put updates statements in 'creates' or 'deletes' args, but you can at least have a basic form of idempotency if you write sensible queries.

**Comment by dagwieers** [comment]
During the [next Windows WG meeting](https://github.com/ansible/community/issues/420) on 2019-01-29 we will review and decide on the inclusion of this module in Ansible v2.8. Your presence in the meeting could be helpful.

*If there's anything you wanted to improve/fix, please do so before the meeting.*

**Comment by nitzmahone** [comment]
There's a new capability coming in 2.8 called "collections" that allows first class distribution of all Ansible plugins via galaxy.ansible.com. We think this is probably a good candidate for that, since it has pretty heavy testing requirements that we're not ready to impose on our CI environment (eg an installed SQL Server).

**Comment by dlazz** [comment]
Ok, thank you all.

**Pull request closed without merging**
