### PR TITLE
[inventory/azure_rm] Filter by tags from environment variables

### LINKED ISSUE #62574: Filtering by tag for Dynamic Inventory Ansible with "azure_rm plugin"
##### SUMMARY

In the legacy [Azure inventory script](https://github.com/ansible/ansible/blob/devel/contrib/inventory/azure_rm.py), it supports selecting hosts with specific tag key with environment variables like below.

https://github.com/ansible/ansible/blob/558ce6575d9ea43adc9116f88a1cc95b3110a7dd/contrib/inventory/azure_rm.py#L139-L141

But in the new [Azure inventory plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/azure_rm.py), it no longer supports any more. And this may make users confused when they try to migrate from the script to plugin.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure inventory plugin

##### ADDITIONAL INFORMATION

Enable selecting hosts with tags set in environment variables.

```yaml

```

### PR DESCRIPTION
**Pull request by gavinfish**
##### SUMMARY

Resolves #62574

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure inventory plugin

##### ADDITIONAL INFORMATION

Finish this [tutorial](https://docs.microsoft.com/en-us/azure/ansible/ansible-manage-azure-dynamic-inventories#enable-the-vm-tag) with Ansible(version >= 2.8).

```paste below

```

### CODE REVIEW

**Comment by gavinfish** [comment]
Hi @nitzmahone could you please help me review this one? Thanks.

**Comment by rpurcelldesj** [comment]
@nitzmahone Hi Matt, I see you are one of the first contributor who has committed a big part of the new code in the new version of the azure_rm.py for ansible 2.8 could you help us with the review of this PR or if you can't just point us to someone who can ?

Thanks, have a nice day!

**Comment by rpurcelldesj** [comment]
@anshulbehl I missed the meeting this morning, I wanted to show you this PR. Could you take a look at hit or summon someone else ?

Thanks!

**Comment by gavinfish** [comment]
@rpurcelldesj Does the `keyed_groups` property works for you?

Refer to https://docs.microsoft.com/en-us/azure/ansible/ansible-manage-azure-dynamic-inventories#ansible-version--28.

**Pull request closed without merging**
