### PR TITLE
Cpm time info

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

Get Time/Date and NTP parameters from WTI OOB and PDU devices

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

cpm_time_info

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by anthonyhbarrera** [comment]
Hello, what access level is required to get the Date/Time/NTP data?

**Comment by mattsene** [comment]
Hi, 

When there will be a "configure" module for the Date/Time/NTP?

**Comment by anthonyhbarrera** [comment]
Hello, what access level is required to get the Date/Time/NTP data?

**Comment by adam1978978** [comment]
What access level do users need to access the Date/Time/NTP data?

**Comment by wtinetworkgear** [comment]
@mattsene yes there is, we posted this morning. There were a few bugs we ironed out in the internal API to the box. Its located:
https://github.com/ansible/ansible/pull/64403

**Comment by wtinetworkgear** [comment]
@adam1978978 In the WTI box there are currently four user levels. View Only, User, SuperUser and 
Administrator. To get Time/Date/NTP parameters you currently need to be a SuperUser and up (with API Access enabled). 
If you want to configure these parameters with the configure module:
https://github.com/ansible/ansible/pull/64403

You need to be an Administrator.

**Comment by Huskersdj** [comment]
What firmware version is required?

**Comment by wtinetworkgear** [comment]
@Huskersdj The current release for the DSM 6.58 and VMR 2.15 will have the current RESTful API that will support this module. If you need any help upgrading or need a demo unit online email us at support@wti.com and we will take care of you.

**Comment by Huskersdj** [comment]
What are the timezone numbers mean and correspond to ?

**Comment by scarshouldofwon** [comment]
Can I use the API out of the Ansible context ?

**Comment by wtinetworkgear** [comment]
@Huskersdj We should document that better in the API Documentation, but if you login to a WTI device and go to the "Real Time Clock" menu (/F from the main menu) you can get a list the corresponds to the list below:

1.  (GMT-1200) Kwajalein
2.  (GMT-1100) Midway Island           
3.  (GMT-1000) US/Hawaii               
4.  (GMT-0900) US/Alaska               
5.  (GMT-0800) US/Pacific              
6.  (GMT-0800) US/Arizona              
7.  (GMT-0700) US/Mountain             
8.  (GMT-0600) US/Central              
9.  (GMT-0500) US/Eastern              
10. (GMT-0500) US/Indiana (East)       
11. (GMT-0430) Caracas                 
12. (GMT-0400) Atlantic/Santiago       
13. (GMT-0330) New Foundland           
14. (GMT-0300) Greenland/Buenos Aires  
15. (GMT-0200) Mid Atlantic            
16. (GMT-0100) Cape Verde Is.          
17. (GMT+0000) GMT (No DST)            
18. (GMT+0000) London/Dublin           
19. (GMT+0100) Paris/Rome
20. (GMT+0200) Cairo/Jerusalem
21. (GMT+0300) Moscow
22. (GMT+0330) Tehran
23. (GMT+0400) Abu Dhabi, Muscat
24. (GMT+0430) Kabul
25. (GMT+0500) Islamabad, Karachi
26. (GMT+0530) New Delhi, Calcutta
27. (GMT+0545) Kathmandu
28. (GMT+0600) Sri Lanka/Dhaka
29. (GMT+0630) Rangoon
30. (GMT+0700) Bangkok
31. (GMT+0800) Beijing, Hong Kong
32. (GMT+0900) Tokyo
33. (GMT+0930) Darwin
34. (GMT+1000) Syndey/Guam
35. (GMT+1100) Magaden
36. (GMT+1200) Fiji, Marshal Is.
37. (GMT+1300) Tonga

**Comment by wtinetworkgear** [comment]
@scarshouldofwon Yes, you can use the API calls with wget, curl, python, c# or any other language or program that can make http/https calls. If you want to try out the API I suggest using Postman (https://www.getpostman.com/) which is an awesome tool to try things out. Also the WTI API documentation is here (https://ftp.wti.com/pub/TechSupport/Restful_WTI/current/api/api.html) and some Python sample scripts using the APIs are in our github repository.

**Pull request closed without merging**
