### PR TITLE
Fix YAML source and lint it

### PR DESCRIPTION
**Pull request by adrienverge**
##### ISSUE TYPE
- Feature Pull Request
###### 1) Fix problems in YAML source

This change corrects problems reported by the yamllint linter.

For instance, it removes key duplications (some keys in dicts were repeated, hence creating confusion). It also fixes cosmetic problems such trailing spaces and extra new lines.

---
###### 2) Lint YAML files

This commit enables YAML linting in Travis tests, using the [`yamllint` tool](http://yamllint.readthedocs.org/). It checks syntax errors, key duplicates, and cosmetic problems.

The main goal is to **prevent future syntax errors to enter the code base without being noticed**. While it would be a huge effort to be PEP8 compliant, it is relatively easy to have correct YAML style _now_ and prevent future problems by enabling linting.

Note: for those (like me) caring about code attribution: use `git blame -w` to ignore whitespace-only changes.

Note: I disabled some linting checks (such as indentation), they can be enforced in the future if needed. Similarly, current checks can also be disabled.

### CODE REVIEW

**Comment by bcoca** [comment]
most of the whitespace fixes can be ignored and they are purely stylistic, we don't normally apply style changes as they break attribution.

**Comment by adrienverge** [comment]
Hi @bcoca,

It's not only whitespaces: there were a few duplicated keys in dicts (which are silently ignored by pyyaml).

About attribution: I agree, but git is great: `git blame -w` ignores whitespace-only changes.

**Comment by bcoca** [comment]
resubmit the PR with just the dupes

**Comment by adrienverge** [comment]
@bcoca Done at #15678!

(I opened a new PR to keep all the cosmetic fixes available somewhere.)

**Comment by gundalow** [comment]
@adrienverge What's your thoughts on what to do with this PR?
Glad to see that https://github.com/ansible/ansible/pull/15678 got merged

**Comment by adrienverge** [comment]
Hi @gundalow,

I see a real benefit in linting trailing spaces, extra lines, indentation and such. Beyond the cosmetic perspective, it can detect bugs before they occur (indentation) and prevent code attribution problems (with `git blame` for example) because new commits will not be able to add useless whitespaces.

If you give me a go, I'll rebase and resubmit. Otherwise we can close. What do you and @bcoca think?

**Comment by gundalow** [comment]
I've added this to the agenda for the Core Team meeting today so we can get agreement from the Core Team.

**Comment by gundalow** [comment]
So we discussed this in the Core Meeting and in the Testing Working Group today

The conclusions are:
- We are happy to raise the standard and enforce for yaml, though **only** under the `test/` directory structure
- CI is not done in Shippable, not Travis now, so that bit of code will need moving

Thank you :)

**Comment by adrienverge** [comment]
Great news!

I have rebased the branch on `devel`, fixed all new YAML problems on new files, updated commit messages, and narrowed tests to the `test` directory.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@adrienverge Thank you for the quick update.

@mattclay I'm happy with this. yamllint is installed via `test/utils/shippable/code-smell-requirements.txt`

Is their anything else we need to do before merging?

**Comment by gundalow** [comment]
@adrienverge Can you please rebase then we'll get this merged. Thanks again

**Comment by adrienverge** [comment]
@gundalow done

**Comment by mattclay** [comment]
@adrienverge For some reason I'm not seeing a Shippable CI run associated with the latest commit for this PR. Could you try squashing your commits and force pushing your changes? Hopefully that will trigger CI to run.

**Comment by adrienverge** [comment]
> For some reason I'm not seeing a Shippable CI run associated with the latest commit for this PR

Yes, this is strange! I amended and pushed again, the build started this time. (I'm not for squashing the two commits because they bring two logical changes.)

**Pull request merged**
