### PR TITLE
edit the playbook callback ,callback in cli can be set,but in the playbook_executor not be used!

### PR DESCRIPTION
**Pull request by maBrons**
##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Docs Pull Request
##### ANSIBLE VERSION

```

```
##### SUMMARY

```

```

### CODE REVIEW

**Comment by bcoca** [comment]
what are you trying to accomplish?

**Comment by maBrons** [comment]
Bugfix Pull Request
I trying to fix the bug，ansible/cli/playbook/PlaybookCLI import ansible.cli.CLI,in the CLI you can set callback ,but in the PlaybookCLI not used the callback.this problem can not be found in the ansible.cli.adhoc.AdHocCLI.

maxiaoganggg@163.com

From: Brian Coca
Date: 2016-07-01 06:20
To: ansible/ansible
CC: maBrons; Author
Subject: Re: [ansible/ansible] edit the playbook callback ,callback in cli can be set,but in the playbook_executor not be used! (#16517)
what are you trying to accomplish?

**Comment by bcoca** [comment]
I don't understand, can you please fill in the issue template? give examples of the expected and actual results.

**Comment by maBrons** [comment]
Just a moment, please.

**Comment by maBrons** [comment]
from ansible.cli.playbook import PlaybookCLI as mycli

# from ansible.cli.adhoc import AdHocCLI as mycli

from ansible.plugins.callback.minimal import CallbackModule

class CallbackTest(CallbackModule):
    def **init**(self,testCallbackMessgae):
        super(CallbackTest,self).__init()
        self.testCallbackMessgae = testCallbackMessgae
test = CallbackTest('this is test!')

# in playbook this callback useless,but in adhoc can use

cli = mycli(['/usr/bin/ansible-playbook','/tmp/test.yml'],callback=test)
cli.parse()
exit_code = cli.run()

**Comment by bcoca** [comment]
Thanks for filing a ticket!

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please use the issue template provided when you open a new issue. That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

# Closing this ticket

If you still feel like this should be a ticket, please reopen a new one and properly fill in the template.

**Pull request closed without merging**
