### PR TITLE
Show BGP Status In JSON

### PR DESCRIPTION
**Pull request by permitanyany**
Show BGP Status In JSON
+label: docsite_pr
+label: issue #311

##### SUMMARY
Show BGP Status In JSON

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
nclu

##### ANSIBLE VERSION
ansible 2.5.2
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

##### ADDITIONAL INFORMATION
Issue #311

### CODE REVIEW

**Comment by ericpulvino** [comment]
Looks clean.

**Comment by IPvSean** [comment]
there is a new requirement for all submitted PRs for the contest ansible/community#311 (and in general for networking doc PRs) to provide playbook output. Since this is a new rule, and Cumulus VX is widely available and easy to use, I will go ahead and test the 5 PRs submitted by @permitanyany

PR https://github.com/ansible/ansible/pull/40734 looks good! Here is the playbook and output

```
cumulus@oob-mgmt-server:~$ cat bgp.yml
---
- name: test playbook for cumulus
  hosts: leaf01
  gather_facts: false
  tasks:
    - name: Check BGP Status
      nclu:
        commands:
            - show bgp summary json
      register: output
    - name: Print BGP Status In JSON
      debug:
        var: output["msg"]
```

playbook output->

```
cumulus@oob-mgmt-server:~$ ansible-playbook bgp.yml

PLAY [test playbook for cumulus] **************************************************************************************

TASK [Check BGP Status] ***********************************************************************************************
ok: [leaf01]

TASK [Print BGP Status In JSON] ***************************************************************************************
ok: [leaf01] => {
    "output[\"msg\"]": {
        "ipv4 unicast": {
            "as": 65000,
            "bestPath": {
                "multiPathRelax": "false"
            },
            "dynamicPeers": 0,
            "peerCount": 3,
            "peerMemory": 59904,
            "peers": {
                "swp51": {
                    "idType": "interface",
                    "inq": 0,
                    "msgRcvd": 0,
                    "msgSent": 0,
                    "outq": 0,
                    "peerUptime": "never",
                    "peerUptimeMsec": 0,
                    "prefixReceivedCount": 0,
                    "remoteAs": 0,
                    "state": "Idle",
                    "tableVersion": 0,
                    "version": 4
                },
                "swp52": {
                    "idType": "interface",
                    "inq": 0,
                    "msgRcvd": 0,
                    "msgSent": 0,
                    "outq": 0,
                    "peerUptime": "never",
                    "peerUptimeMsec": 0,
                    "prefixReceivedCount": 0,
                    "remoteAs": 0,
                    "state": "Idle",
                    "tableVersion": 0,
                    "version": 4
                },
                "swp53": {
                    "idType": "interface",
                    "inq": 0,
                    "msgRcvd": 0,
                    "msgSent": 0,
                    "outq": 0,
                    "peerUptime": "never",
                    "peerUptimeMsec": 0,
                    "prefixReceivedCount": 0,
                    "remoteAs": 0,
                    "state": "Idle",
                    "tableVersion": 0,
                    "version": 4
                }
            },
            "ribCount": 0,
            "ribMemory": 0,
            "routerId": "192.168.0.11",
            "tableVersion": 0,
            "totalPeers": 3,
            "vrfId": 0,
            "vrfName": "Default"
        },
        "ipv6 unicast": {},
        "l2vpn evpn": {}
    }
}

PLAY RECAP ************************************************************************************************************
leaf01                     : ok=2    changed=0    unreachable=0    failed=0
```

@acozine this one is ready to be accepted test on 
```
cumulus@oob-mgmt-server:~$ ansible --version
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/cumulus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

with Cumulus VX->
```
cumulus@leaf01:~$ cat /etc/lsb-release
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=3.5.3
DISTRIB_DESCRIPTION="Cumulus Linux 3.5.3"
```

**Comment by acozine** [comment]
Looks good, but needs a rebase since we merged another change to nclu.py. @permitanyany can you rebase your `patch-5` branch, please? Once it's rebased off of `devel` you can force-push to your fork, updating this PR.

**Comment by permitanyany** [comment]
@acozine Sorry for the newb question, but is there a way to rebase via the github site? I see many tutorials, but they only show how do so via the cli.

**Comment by permitanyany** [comment]
@acozine any ideas?

**Comment by acozine** [comment]
@permitanyany we've been looking at your PRs from oldest to newest, so just seeing your question now. I think the only way to accomplish this via the github site is to open a new PR with the same change, but based on the most recent code. If you do that, please link from the new PR to this one. Thanks!

**Comment by acozine** [comment]
Thanks @permitanyany! Closing this one in favor of #41844.

**Pull request closed without merging**
