### PR TITLE
Added example to include wait_for command - Issue 311

### PR DESCRIPTION
**Pull request by jvanderaa**
… command.

##### SUMMARY

Example including a single command output with a `wait_for`

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

Network Cisco ASA

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by beeankha** [comment]
Hello @jvanderaa , thank you for submitting a PR to this repo.  We'll be testing before merging, so stay tuned and we'll update with a comment as we go through the queue!

**Comment by acozine** [comment]
Hi @jvanderaa we'd like to see a playbook and output showing that the new example works - see the Validation section of ansible/community#311 for the rules, and @IPvSean's comment on #40369 for an idea of what to do. Reach out if you have questions. Thanks!

**Comment by beeankha** [comment]
@jvanderaa , just pinging to see if you could rebase + provide the info requested above by @acozine .  If we don't hear back from you by the end of this month (July 2018), we'll close this PR out.

**Comment by jvanderaa** [comment]
Yeah I can. Been a crazy few weeks for me. Apologies for delay.

**Comment by jvanderaa** [comment]
```ansible
$ ansible-playbook asa_example.yml -i ./hosts

PLAY [Show ASA Wait for Result] **************************************************************************************************

TASK [ASA>> Get Ping output] *****************************************************************************************************
[DEPRECATION WARNING]: Param 'auth_pass' is deprecated. See the module docs for more information. This feature will be removed in
 version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'timeout' is deprecated. See the module docs for more information. This feature will be removed in
version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [asav-1]

TASK [debug] *********************************************************************************************************************
ok: [asav-1] => {
    "msg": [
        "Type escape sequence to abort.",
        "Sending 101, 350-byte ICMP Echos to 8.8.8.8, timeout is 2 seconds:",
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "Success rate is 100 percent (101/101), round-trip min/avg/max = 20/37/60 ms"
    ]
}

PLAY RECAP ***********************************************************************************************************************
asav-1                     : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by beeankha** [comment]
Hi @jvanderaa, thank you so much for your updates!  We would still like to see the full example playbook pasted into this thread so we can test this PR.  As an added note, please ensure that you name each task in the playbook (a brief description about why that particular task is being executed) so that we can keep track of the output we get on our end.

**Comment by jvanderaa** [comment]
Sure thing, apologies.

```
---
- name: Show ASA Wait for Result
  hosts: asa_examples
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ASA>> Get Ping output
      asa_command:
        commands:
          - ping 8.8.8.8 repeat 101 size 350
        authorize: yes
        auth_pass: "{{ ansible_become_pass }}"
        wait_for:
          - result[0] contains 100
        timeout: 100
        retries: 2
      register: ping_output

    - debug:
        msg: "{{ ping_output.stdout_lines.0 }}"

```

**Comment by samccann** [comment]
Closing this PR in favour of this new one:
[https://github.com/ansible/ansible/pull/45190](url)

 - removed some deprecated items and added titles to all the examples for asa_command.
 

Thanks again @jvanderaa for participating in the challenge and you will get credit for this addition! BTW - it would be helpful in the future if you used a topic branch for ansible changes. It makes it easier for someone to pop into your topic branch and make a few minor edits before merging. I didn't want to do that to your devel, so I created a new PR for this.

**Pull request closed without merging**
