### PR TITLE
Add rpmkey module

### PR DESCRIPTION
**Pull request by hacosta**
This module can be used to import public keys into your rpm database.

### CODE REVIEW

**Comment by lwade** [comment]
Hey @hacosta, just took a brief look and version_added should be 1.3 rather than 0.13.  Also, it seems the examples have state=imported yet the parameter options only mention state=present/absent.

**Comment by hacosta** [comment]
@lwade fixed those problems in my latest branch, please let me know if you have other questions/concerns

**Comment by mpdehaan** [comment]
also should probably be rpm_key

In queue for review...

**Comment by mpdehaan** [comment]
Can you please submit this without merge commits?

Use git pull --rebase vs git pull and git rebase vs git merge and you should be fine

Also create a new branch for each topic you are working on and it will be easier to avoid mixing commits up

**Pull request closed without merging**
