### PR TITLE
Add ::1 where we see 127.0.0.1, for better ipv6 support

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by mpdehaan** [comment]
While this sounds like a good idea the host separator doesn't really allow entry of this IIRC because it will split on colons.

**Comment by mscherer** [comment]
I just tested with: 

```
$ ansible -u misc -i '::1,' all -m ping       
::1 | success >> {
    "changed": false, 
    "ping": "pong"
}
```

We fixed it in https://github.com/ansible/ansible/pull/3879

And even with ini file as inventory:

```
$ ansible -i /tmp/hosts ipv6 -m ping 
::1 | success >> {
    "changed": false, 
    "ping": "pong"
}
$ cat /tmp/hosts 
[ipv6]
::1
```

But yes, there is still a small issue on the ini file inventory when needing to set the port, as you cannot user [::1]:22 since this conflict with the syntax for range ( ie, webserver[a-f].example.org ).

**Comment by gundalow** [comment]
"But yes, there is still a small issue on the ini file inventory when needing to set the port, as you cannot user [::1]:22 since this conflict with the syntax for range ( ie, webserver[a-f].example.org )."

Sounds like an extension of https://github.com/ansible/ansible/issues/5338

**Comment by jimi-c** [comment]
Re-implemented your patch in devel, so closing this.

Thanks!

**Pull request closed without merging**
