### PR TITLE
Added new LogicMonitor module.

### PR DESCRIPTION
**Pull request by ethanculler**
Module allows you to manage a LogicMonitor account including:
Hosts - Add, remove, schedule downtime (sdt)
Host groups - Add, remove, schedule downtime (sdt)
Collectors - Add, remove, schedule downtime (sdt)

Updates:
cleaned up whitespace and comments
added list and dict parameter types to "groups" and "properties" parameters respectively.

### CODE REVIEW

**Comment by jctanner** [comment]
@ethanculler can you switch your boolean parameters to use the bool type please?

```
dict(default='no', type='bool')
```

**Comment by mpdehaan** [comment]
I feel I should reply to this one as it's been in our backlog for some time -- though our large backlog is not an excuse for a delay in response.

My gut feeling is this module is still a bit large for our criteria of inclusion, and without an underlying library might grow unmaintained, which is a bit of a concern for us since it's a proprietary service we may not have time to support and keep updated.

However, this doesn't mean that this module can't be used by folks, especially by adding it to their library path.   This can definitely help some Logic Monitor users that want to use this.

I think we'd have less concerns if it used a library binding in PyPi, but with the large volumes of logic that is implemented here, keeping it up as underlying changes in Ansible happen (such as the validate certs addition, etc) would be somewhat prohibitive.

My apologies and I hope you understand.  Definitely do keep this around on a repo in GitHub and tell people how to add it to their installations if they are interested.

**Comment by mpdehaan** [comment]
Hi just wanted to provide an additional update to this.

ansible galaxy - http://galaxy.ansible.com/ has a mechanism for including libraries in it.

For instance, if you create a role named "logicmonitor" and have a "library" directory in that role that has "logicmonitor' the library in it, this library can be used with any future task in the ansible playbook.

(The role does not have to include any tasks)

If you would like to add things to the "monitoring" category, this would be an excellent way to make this availability to all users, and it would be easily discoverable.

**Comment by mpdehaan** [comment]
If you have questions about getting this to work, email me and I'd be happy to provide info -- I'm reachable at michael@ansible.com

**Pull request closed without merging**
