### PR TITLE
add option to display per host start to default

### LINKED ISSUE #51042: display_skipped_hosts flag delays task banner which is confusing on slow tasks
##### SUMMARY
I have a long running shell script that my playbook runs.  It takes a couple of minutes.  The task immediately before it displayed its banner but it appeared to hang on this task.  After troubleshooting the issue I determined it was the following shell task that gave this apparent hang.  If the task banner of the shell task displayed when it started it would have been obvious which task it was waiting on. 

I discovered this issue with the yaml stdout_plugin.  After trying many other plugins I realized that unixy was still printing the banner at task start.  Since yaml inherits from default I determined this must be why it does this in many others.

Hopefully there is a way to determine if the task will be skipped at task start instead of delaying it.

##### ISSUE TYPE
display_skipped_hosts was set to False in ansible.cfg.  Although this is desired, it was unclear that a consequence of this is the delay of task banners.

##### COMPONENT NAME
lib/ansible/plugins/callback/default.py

##### ANSIBLE VERSION

```ansible 2.7.5
  config file = /home/ec2-user/ansible.cfg
  configured module search path = [u'/home/ec2-user/library', u'/home/ec2-user/apps/library', u'/home/ec2-user/ansible_commands']
  ansible python module location = /home/ec2-user/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 2.7.14 (default, Jul 26 2018, 19:59:38) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### CONFIGURATION

```ACTION_WARNINGS(/home/ec2-user/ansible.cfg) = False
ANSIBLE_FORCE_COLOR(/home/ec2-user/ansible.cfg) = True
COMMAND_WARNINGS(/home/ec2-user/ansible.cfg) = True
DEFAULT_ASK_PASS(/home/ec2-user/ansible.cfg) = False
DEFAULT_BECOME(/home/ec2-user/ansible.cfg) = True
DEFAULT_BECOME_EXE(/home/ec2-user/ansible.cfg) = sudo -u
DEFAULT_BECOME_METHOD(/home/ec2-user/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/ec2-user/ansible.cfg) = root
DEFAULT_FORKS(/home/ec2-user/ansible.cfg) = 50
DEFAULT_GATHERING(/home/ec2-user/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/ec2-user/ansible.cfg) = merge
DEFAULT_MODULE_PATH(/home/ec2-user/ansible.cfg) = [u'/home/ec2-user/library', u'/home/ec2-user/apps/library', u'/home/ec2-user/ansible_commands']
DEFAULT_NO_LOG(/home/ec2-user/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/home/ec2-user/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/ec2-user/ansible.cfg) = 30
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/home/ec2-user/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/ec2-user/ansible.cfg) = False
HOST_KEY_CHECKING(/home/ec2-user/ansible.cfg) = False
INVENTORY_ENABLED(/home/ec2-user/ansible.cfg) = [u'yaml']
SYSTEM_WARNINGS(/home/ec2-user/ansible.cfg) = True

```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

```yaml
- name: Illustrating problem
  hosts: all
  tasks:
    - name: Do nothing
      debug: msg="nothing to see here"
    - name: Catch some Z's
      command: sleep 100
```

##### EXPECTED RESULTS

Display the TASK [Catch some Z's] and then hang there.

##### ACTUAL RESULTS

Displays TASK [Do nothing] with output and then hangs without ever showing TASK [Catch some Z's] unless you are patient enough to see if it ever completes.

### LINKED ISSUE #53779: Running tasks are not displayed when strategy = free
##### SUMMARY
It's not clear which tasks are active when the strategy is set to 'free'. In regular mode, in which only one task runs at a time, the currently running task is displayed in the most recent line.

In free mode, in which multiple tasks may be running at once, the running tasks are not shown until completed. This can be problematic when developing playbooks, because if a task is hanging (happens commonly during package updates) a user might not be sure which task is stalling.

If displaying the currently running tasks on the latest line doesn't aesthetically make sense when multiple tasks are running, then I propose a status bar at the bottom of the shell which cycles through currently running tasks. This status bar could be recycled for later features as well.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 16 2019, 19:49:22) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]

```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/home/user/.ansible.cfg) = -C -i $ANSIBLE_KEY_FILE -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_STRATEGY(/home/user/.ansible.cfg) = free
DEFAULT_VAULT_PASSWORD_FILE(/home/user/.ansible.cfg) = $ANSIBLE_VAULT_PWD
```

##### OS / ENVIRONMENT

Fedora 29 XFCE, running inside KVM machine.

##### STEPS TO REPRODUCE

Run a playbook with strategy=free. To best illustrate the issue, deploy to a single machine and run a task which takes a long time, like an update or a shell command like `sleep 5m`

```yaml
---
- hosts: {{ host }}
  tasks:
    - name: Wait for five minutes
      command: sleep 5m
```

##### EXPECTED RESULTS

Task takes five minutes to complete, While waiting, the UI conveys to the user which tasks are running.

##### ACTUAL RESULTS

User is unsure which task is causing ansible to stall.

### PR DESCRIPTION
**Pull request by bcoca**
fixes #53779
fixes #51042, might need tweaking to deal with task banners being displayed when not displaying 'skipped'

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

callbacks/default

### CODE REVIEW

**Comment by PikachuEXE** [comment]
@bcoca 
Is it possible to install the version in this PR and perform a manual test?

**Comment by bcoca** [comment]
@PikachuEXE yes, the PR is a 'branch' you can checkout or you can just download the doc fragment and callback plugin files and use 'adjacent' directories to test

**Review by Andersson007 — APPROVED** [review]
I tried it manually - works as expected, good job

shipit

**Comment by Andersson007** [comment]
If possible, would be better to add some active points that's increasing every second ;)

**Review by jamescassell — APPROVED** [review]
LGTM

**Comment by Asgoret** [comment]
@Andersson007 hi! is there any information when problem with stucking ansible will be resolved? I have this error on:
```
ansible 2.7.8
  config file = None
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Mar  5 2019, 06:22:51) [GCC 6.3.0 20170516]
```

**Comment by Andersson007** [comment]
@Asgoret , hi, I don’t understand what do you mean:) Just I tried to use that @bcoca added and it worked well

**Comment by Asgoret** [comment]
@Andersson007 Oh... I mention you because you are in review list) I mean on version 2.7.8 problem is reproduced. Ansible stuck in random place and random playbook. It can work perfect for 10-20 times and next 3 times stuck. Then again all works perfect. So... i can't find any workaround. I tried adding more forks or use paramiko didn't help me.  It's very odd because in local environment i can't reproduce it.

**Comment by Andersson007** [comment]
@Asgoret , I didn’t come across with it. Anyway I’m afraid it’s almost  impossible to solve this kind of problems without knowledge how to reproduce it.

**Comment by Asgoret** [comment]
@Andersson007 yeah....i understand it. Is there any full trace for ansible with all system cals?

**Comment by Andersson007** [comment]
@Asgoret , you could increase output verbosity by using -vvvv key, maybe you'll catch something interesting.
(I haven't heard of other ways to get additional information)

**Comment by Andersson007** [comment]
For questions like this better to use ansible development mailing list or ansible-devel irc channel.
There are many people who may give advice.

**Comment by PikachuEXE** [comment]
Would this be released in 2.8 or 2.9?
Sorry I don't quite understand what `devel` stands for right now

**Comment by bcoca** [comment]
it stands for 'development' which means in future 'stable-2.9' branch creation, this will be there, it was merged AFTER creating stable-2.8 branch, so it won't be in that version.

**Pull request merged**
