### PR TITLE
Properly load module_prefix for collections in task_executor.py

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY

Allow us to properly load a module from collections

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
check experimental

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 62981a4e343f730055fb387f358c38f20a3e7057

**Comment by pabelanger** [comment]
check experimental

**Review by Qalthos — APPROVED** [review]

**Review by nitzmahone — DISMISSED** [review]
I was never a fan of this approach, at least without having the connection opt-in to it. The original version of this was already pretty dangerous, as it can false-positive and load a completely unrelated action. eg:
```
tasks:
- my_awesome_module:
```
would invoke a `my` action if it were present, even in the original version (regardless if it was a networking connection or not).

It's made worse in this version by the fact that the prefix is being completely discarded, and relying on the `collection_list` (which may often be empty) to resolve the action. Did you want the built-in action, the one from the current collection, or the one from the collection that the module came from?

Ultimately, we're missing the context to do this properly. Unless we smuggle in some extra data to consult, the "right" way to do this would be to have a proper connection object for each network OS and have a metadata flag or a callback in the connection that the action resolver can call into to allow the connection to alter what happens.

A short-term fix would be to use the source collection where the module was found to look up the right action dispatcher, but that only works if they're always in the same collection. Consider a community networking module that relies on the shared action dispatcher. Bang.

I think this is one that's going to require some discussion/changes- maybe collectionizing networking is the right time to define/require first-class connection plugins for it...

**Comment by cidrblock** [comment]
Ok, Let's move forward with 60420, with the understanding that the action plugin will be coming from core.

**Comment by nitzmahone** [comment]
Yeah, this is ok to merge as is for now, but we'll definitely need to revisit the underlying mechanism to be able to fully collectionize networking stuff.

**Pull request merged**
