### PR TITLE
vmware: Add more integration tests to Zuul CI

### PR DESCRIPTION
**Pull request by goneri**
##### SUMMARY

- vmware_content_library_info
- vmware_content_library_manager
- vmware_guest_disk
- vmware_host
- vmware_host
- vmware_host_firewall_manager
- vmware_host_ipv6
- vmware_host_powermgmt_policy
- vmware_vswitch

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

vmware_content_library_info
vmware_content_library_manager
vmware_guest_disk
vmware_host
vmware_host
vmware_host_dns
vmware_host_firewall_manager
vmware_host_ipv6
vmware_host_powermgmt_policy
vmware_vswitch

### CODE REVIEW

**Comment by mariolenz** [comment]
By defining these Zuul aliases, you make Zuul run the integration tests for these modules... right? In that case, I think a better name for this PR would be something like "vmware: Add more integration tests to Zuul CI" or similar. After all, that's what it amounts to.

Apart from this cosmetic issue, I don't think there's a reason to not merge this PR as long as the Zuul job succeeds.

**Comment by goneri** [comment]
Thanks @mariolenz for your feedback, I updated the title. For the record, the `zuul/vmware/vcenter_2esxi` alias is not run yet by the CI.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
!waffling community_review
!waffling needs_revision

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
I remove `vmware_host_dns` since the test fails consistently. I will address that in https://github.com/ansible/ansible/pull/66877.

**Pull request merged**
