### PR TITLE
[WIP]: A few ideas for updating the windows introduction.

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### ISSUE TYPE

- Docs Pull Request
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides

```
##### SUMMARY

Started out just wanting to add that fetch is a module you can use on windows, but then I started tweaking a few other bits.

Not totally sure if the powershell stuff I've added is in the right place but thought I'd put this up as a work in progress PR (I know @nitzmahone has some doc revisions pending right now anyway).

Doesn't fix anything exactly, although it came up on the google group about fetch and windows a while back, and the powershell one-liner stuff just came out of my experience.

```
See diff for changes.
```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
cc @nitzmahone @trondhindenes - I'd appreciate your thoughts.

**Comment by dharmabumstead** [comment]
I don't appear to have the proper permissions to merge this.

**Comment by nitzmahone** [comment]
I'm pretty much completely rewriting this doc right now anyway, had planned to incorporate in the new one.

**Comment by jhawkesworth** [comment]
since @nitzmahone is on top of this, I'm going to close this one, but leave the branch hanging around just in case there's anything you can use.

**Comment by jhawkesworth** [comment]
sorry missed this had been merged, ignore previous comment.

**Pull request merged**
