### PR TITLE
vmware_guest: Extend facts with vmware tools informations

### PR DESCRIPTION
**Pull request by aperigault**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
2.2.1
```

##### SUMMARY
All in subject

### CODE REVIEW

**Comment by nerzhul** [comment]
shipit

**Comment by nerzhul** [comment]
@aperigault i'm refactoring the facts now

**Comment by dagwieers** [comment]
Rebase and shipit !

**Comment by aperigault** [comment]
Branch rebased!

**Comment by nerzhul** [comment]
just a question, what happend if there are no vmware tools ?

**Comment by aperigault** [comment]
@nerzhul If there are no vmware tools, module return this:
```
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "0",
```

**Comment by nerzhul** [comment]
perfect

shipit

**Comment by dagwieers** [comment]
shipit

**Comment by nerzhul** [comment]
ping @jctanner

**Comment by nerzhul** [comment]
ping @jctanner

**Pull request merged**
