### PR TITLE
new module: win_package

### PR DESCRIPTION
**Pull request by trondhindenes**
win_package does the same as win_msi, but has more features:

-Ability to install exe files as well as msi files
-source (path) can be specified as both a local file, an URL or a UNC path (install from network share)
-support for network credentials if the package resides on a UNC path (file share, and the Ansible "action account" does not have permissions to the location)
-If a reboot is needed, this will be output in the attribute "restart required"

This module uses the basic plumbing of the "Package" DSC resource from the Microsoft team.

### CODE REVIEW

**Comment by sivel** [comment]
If this handles msi packages as well, it probably makes sense to go ahead and deprecate win_msi sooner rather than later.  1.7 was listed as beta for Windows support, so I wouldn't imagine it would be too big of a deal.

**Comment by trondhindenes** [comment]
Yep, I'd say this one does everything that win_msi does.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by Constantin007** [comment]
Hi Guys,

Is it possible to change "ensure" option with "state" ? Just for the sake of consistency - using same convention in all modules...

Kind Regards,
Constantin

**Pull request closed without merging**
