### PR TITLE
Add option -UseMyCert to use existing SSL cert for WinRM listener

### PR DESCRIPTION
**Pull request by guliaka**
In domain environment with existing Enterprise CA many people would like to use existing SSL certs when configuring windows machines for Ansible management. This option was added to script

### CODE REVIEW

**Comment by ShachafGoldstein** [comment]
Is this one still relevant?

**Comment by jhawkesworth** [comment]
I am not keen to add any more features to this script.  While the script is useful for getting started, I think users shoud create their own scripts that meet the exact needs of their organisation.
I think a better place to create such scripts would be powershell gallery.

**Comment by guliaka** [comment]
I added this capability for use within my organisation and thought it would
be useful to others. So take it or leave it I'm fine with either....

**Comment by jhawkesworth** [comment]
Thanks for responding @guliaka Since the script has moved on anyway I think lets close this as it can't be merged without further work.  No harm in leaving the branch around in case others want to adapt your changes though.

**Pull request closed without merging**
