### PR TITLE
Update openstack_guidelines.rst: Remove os_ prefixes

### PR DESCRIPTION
**Pull request by shaderecker**
##### SUMMARY

Remove the terminology related to the "os_" prefixes. Nobody  should create new modules with those prefixes anymore.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME

+label: docsite_pr

### CODE REVIEW

**Comment by Shrews** [comment]
I would argue that it doesn't make sense for this guide to exist in Ansible documentation anymore since the OpenStack modules were moved to a [collection](https://github.com/openstack/ansible-collections-openstack). It seems more fitting for it to exist there. I'm not sure why this bit wasn't removed in the great migration.

**Comment by shaderecker** [comment]
Ok thanks for the hint @Shrews. I will reach out to the OpenStack Community  and see where we can integrate it there.

**Comment by sshnaidm** [comment]
@shaderecker we have guidelines up to date in https://github.com/openstack/ansible-collections-openstack/blob/master/docs/openstack_guidelines.rst
Not sure why this file is still here, maybe need to delete it to prevent confusion?

**Comment by gundalow** [comment]
Could this file be replaced with a link to https://github.com/openstack/ansible-collections-openstack/blob/master/docs/openstack_guidelines.rst just incase anyone has it bookmarked?

**Comment by shaderecker** [comment]
@sshnaidm sorry I did not see it there.

@gundalow  How do you want to link to the new destination? Just put the link in the rst file? Or any other means of redirect?
And maybe we should point to the opendev location: https://opendev.org/openstack/ansible-collections-openstack/src/branch/master/docs/openstack_guidelines.rst

**Comment by gundalow** [comment]
I think you can replace the file with

```
.. _OpenStack_module_development:
OpenStack Ansible Modules
=========================

Please see the `OpenStack guidelines <https://opendev.org/openstack/ansible-collections-openstack/src/branch/master/docs/openstack_guidelines.rst>`_,  for further information
```

**Comment by shaderecker** [comment]
Thank you @gundalow. I am closing this in favor of #73617

**Pull request closed without merging**
