### PR TITLE
Make PKGBUILD packaging standards compliant.

### PR DESCRIPTION
**Pull request by barthalion**
- replace pointless patch with PYTHON=python2
- simplify git describe command
- move pkgver() function lower, so build chroots can make use of it
- align packages in optdepends using spaces
- use double quotation marks only where it's needed
- unify usage of brackets sorrounding variables
- shorten pkgdesc (kudos to Fedora)
- if PKGBUILD is kept here only for reference, there is no point of
  keeping maintainer information

### CODE REVIEW

**Comment by jctanner** [comment]
@leucos and @DMBuce is this something you can test?

**Comment by leucos** [comment]
WorksForMe™
However, I consider using curly braces around variables a better/safer practice.
Beside this, :+1:

**Comment by leucos** [comment]
... and I would leave the maintainer line too, so I don't have to manually add it when I build the source package and send it to AUR... thanks !

**Comment by DMBuce** [comment]
Works for me, although I have one comment. Dropping --long from the `git describe` options will cause pkgver to lose the commit hash if HEAD happens to have a tag pointing at it. This could make it more difficult for users to find the exact commit they built against, which is useful information when e.g. filing bug reports. So I think the option should be kept, unless there's a compelling reason for dropping it.

**Comment by barthalion** [comment]
@leucos: as I already wrote in the commit message, README states that PKGBUILD is here only for reference. There is always a possibility that someone will take over the package in AUR, consequently making the information out of date here, which is not the case if we simply remove it. Additionally we (you) would have to store lines about every contributor to the package. It simply makes no sense.

Using curly variables where they are not needed is neither better or safer.

@DMBuce: That's the point of tagging commits in repositories, isn't it? User can easily check which commit is "hidden" behind the tag or just include the tag in his report.

**Comment by leucos** [comment]
@Barthalion : I've read your commit message, and I don't know why you say "is here only for reference". If one day someone else takes care of ansible-git, we might just remove the line or change if to the new maintainer's name.
Until then, this is the file I use to build the package and if I could avoid editing it before building it would be better. I don't see what's the problem with this line, really. 
In the light of "Mak(ing) PKGBUILD packaging standards compliant", is does make sense to have a maintainer line. It also does make sense to have a list of contributors for the PKGBUILD. I don't know why "it doesn't make sense".

I don't see any problem with curly variables either. I just think it's a good practice to do it this way : it's more readable, and it preserves expansion wherever they are used. What are the downsides ?

**Comment by DMBuce** [comment]
@Barthalion Sure, but I'm not claiming that the change makes it impossible to track down which commit the package was built against; only that it makes it less obvious and therefore more difficult. I know that if it were me, I wouldn't be sure why `pacman -Q ansible-git` didn't have the commit hash and would have to look at the PKGBUILD or $srcdir I used to see why. A user who deletes his build environment would not be able to do that, and would have to either guess or reproduce the bug with a new build.

Which is not the end of the world and does not matter that much, so I won't complain any more if the change is kept. I just have a personal preference for including that information in the package version, and wanted to point out the change so that it wasn't lost among the whitespace and style changes.

**Comment by barthalion** [comment]
@leucos I say "is here only for reference" because this is what you wrote in README. It doesn't make sense, because it's not relevant to Ansible itself, it's useful information only if you are AUR user wanting to contact the maintainer. But here, in Git repository, we can use `git blame` to found the author of possibly broken or unneeded line.

Better readability of curly braces around every variable is arguable. Like with every debatable practice you need to keep the consistency: you use brackets in lines 39-40 and 52-56, but happily ignore `prepare()`, `build()`, the first line of `package()` and lines 42-50. Furthermore in neither of those places you need to ensure that variable will be expanded.

@DMBuce Right, I haven't thought about it. I would be surprised if pkgver didn't have the hash too – I'll rebase my changes and leave `--long` untouched.

**Comment by leucos** [comment]
@Barthalion again, I use this file to build the AUR package. What's wrong having the maintainer line in it ? "The PKGBUILD and patch in this directory are here for reference" means you'd rather use yaourt to get and build the package. If you send a patch for this file, I suppose you assume it is the one used to build for AUR or I don't see the point in sending PR.

(BTW since there is no more patch, we should fix the README too)

"Like with every debatable practice you need to keep the consistency" : good point, I should have used them eveywhere. You should have fixed that ;)

Now I don't think this needs more debate, Just do like you feel.

**Comment by barthalion** [comment]
Rebased the commit to keep information about current AUR maintainer and bring back `--long` for `git describe`.

**Comment by DMBuce** [comment]
Looks good to me. Thanks for accepting my feedback.

**Comment by jctanner** [comment]
@Barthalion looks like this currently has a merge conflict. Can you take a look and resolve it?

**Comment by barthalion** [comment]
Just pushed fixed commit.

**Comment by jctanner** [comment]
@Barthalion thank you!

**Pull request merged**
