### PR TITLE
ANSIBLE_REMOTE_TMP

### PR DESCRIPTION
**Pull request by weaselkeeper**
Cleanup of ansible remote tempdir code.  Only modifying runner.py and doc files. Tested fine on my systems, Ubuntu, Debian and RH/CentOS but could use more testing obviously.

### CODE REVIEW

**Comment by mpdehaan** [comment]
in queue for testing tomorrow.  Thanks!

tip for the future, always use git pull --rebase, not git pull, as it avoids merge commits leaking into the history, and keeps your commits at the top of the stack.

**Comment by weaselkeeper** [comment]
Cool, noted.  Thanks!

On Fri, May 11, 2012 at 6:06 PM, Michael DeHaan
reply@reply.github.com
wrote:

> in queue for testing tomorrow.  Thanks!
> 
> tip for the future, always use git pull --rebase, not git pull, as it avoids merge commits leaking into the history, and keeps your commits at the top of the stack.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ansible/ansible/pull/378#issuecomment-5664160

## 

http://neon-buddha.net

**Comment by mpdehaan** [comment]
manually merged

**Comment by weaselkeeper** [comment]
On Sat, May 12, 2012 at 9:26 AM, Michael DeHaan
reply@reply.github.com
wrote:

> manually merged

This is the second time you've had to  manually merge my PR,  is that
because I was doing git pull without the --rebase option from
weaselkeeper/ansible?

## 

Good ideas require good thought.

**Comment by mpdehaan** [comment]
yeah you should probably just alias git pull to git pull --rebase and it will be good to go next time.

I also did a squash commit so I could see the changes all together, and made some slight simplifications on top.

**Comment by weaselkeeper** [comment]
On Sat, May 12, 2012 at 9:33 AM, Michael DeHaan
reply@reply.github.com
wrote:

> yeah you should probably just alias git pull to git pull --rebase and it will be good to go next time.
> 
> I also did a squash commit so I could see the changes all together, and made some slight simplifications on top.

OK, works for me.  Follow on question.  I currently pull from
weaselkeeper/ansible and rebase to ansible/ansible to get upstream
stuff.  Would it be better to pull from ansible/ansible, rebase often,
 and just push to weaselkeeper/ansible?  I use weaselkeeper/ansible a
lot because I do the dev work from both home and work, but I can
always just ssh into one machine to do it and leave
weaselkeeper/asnsible only for cleaned up commits after I am done with
something.

Thanks

## 

English is a language where much confusion reigns over the power of
nouns, to become verbs.

**Comment by mpdehaan** [comment]
git pull = git fetch + git merge
git pull --rebase = git fetch + git rebase

I think you probably want to make sure you just push to weaselkeeper any time you rebase from devel.  That's essentially what I do for me as well.

**Comment by weaselkeeper** [comment]
On Sat, May 12, 2012 at 9:50 AM, Michael DeHaan
reply@reply.github.com
wrote:

> git pull = git fetch + git merge
> git pull --rebase = git fetch + git rebase
> 
> I think you probably want to make sure you just push to weaselkeeper any time you rebase from devel.  That's essentially what I do for me as well.

Ok, thanks.

## 

gaje, gaijin, and goyim, all mean 'other' or 'foreigner' in Romany,
Japanese and Hebrew. Odd that.

**Pull request closed without merging**
