### PR TITLE
Add missing dependency to deb package.

### PR DESCRIPTION
**Pull request by matt2000**
I ran into this while testing a playbook in a Docker container using ubuntu/utoptic as the base.

### CODE REVIEW

**Comment by matt2000** [comment]
This is actually a bug-fix. The deb package will fail to install on some systems without this change.

**Comment by bcoca** [comment]
which systems? how can i reproduce? it is weird to need ssh-client as a build depenency

**Comment by matt2000** [comment]
I can't reproduce this with a 'hello world' playbook, so it must be specific to the original playbook I was using, and so not a problem with ansible itself.

**Comment by bcoca** [comment]
well, the file updated is part of the deb package build source, it would not affect playbooks at all, only the building of the .deb from the ansible source

**Pull request closed without merging**
