### PR TITLE
New cloudformation dry run module for Ansible check mode

### PR DESCRIPTION
**Pull request by cytopia**
##### SUMMARY

An Ansible module that will show the differences that would occur in case you actually run cloudformation_module. Changes to be shown include:

* Stack template changes
* Stack parameter changes
* Stack tag changes

Changes that can be omitted by the module:

* Stack template description
* Stack parameters that use `NoEcho: true`
* The diff output can be in `json` or `yaml` depending on your preferred choice to view the diff.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
cloudformation_diff

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

##### ADDITIONAL INFORMATION

For reference see here: https://github.com/cytopia/ansible-modules

### CODE REVIEW

**Comment by cytopia** [comment]
Could I please get a human reviewer here letting me know how to fix

* Shebang: what is wrong with `#!/usr/bin/env python`
* `Unable to parse documentation`
* and `ModuleNotFoundError: No module named 'cfn_flip'` (which is required)

**Comment by willthames** [comment]
Can this be done by adding check mode and diff capability to the existing cloudformation module?

I'm not in favour of a specific diff module when ansible has a diff mode that we'd just need to hook in to.

**Comment by willthames** [comment]
> Could I please get a human reviewer here letting me know how to fix
>
>    Shebang: what is wrong with #!/usr/bin/env python

Ansible uses /usr/bin/python as a shebang, and will do python replacement at module execution time. There are various reasons for this (for one, it's how `ansible_python_interpreter` works)

>    Unable to parse documentation

These are mostly YAML errors. In particular you need to be careful with colons - YAML thinks that a colon followed by a space is a dictionary key/value separator.

You'll also need a `RETURN` section. See the [documentation docs](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html).

>    and ModuleNotFoundError: No module named 'cfn_flip' (which is required)

You need to wrap the import in a `try/except ImportError` and set a variable that is then used later once the `AnsibleModule` is created so that you can do `module.fail_json(msg="Cannot import cfn_flip. Try pip install cfn_flip or similar")`. This is relatively well documented in the [new module checklist page](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_checklist.html)

**Comment by cytopia** [comment]
@willthames thanks for helping me out.

> Can this be done by adding check mode and diff capability to the existing cloudformation module?
> 
> I'm not in favour of a specific diff module when ansible has a diff mode that we'd just need to hook in to.

I also thought about this too prior creating a dedicated module. However with Cloudformation there is no real *dry* run **yet**.

If this was integrated in `cloudformation_module` it should be 100% reliable and tell you if changes will occur or not. But this is not the case. Even though you would change the Cloudformation template (differing from remote), the stack might not be applied right away. Some examples are *Stack description* or some changes that happen within the *CloudInit* section. Additionally, if you have parameter that are set to `NoEcho: true`, they will always report as changed as the remote side reports them as `******` instead of the real value.

Therefore I have created a separate module which is a pure `diff` module that is also tweakable in the way you want your diff (`changes`) to be shown.

You can for example:
* Ignore unecho-ed parameters
* Ignore trailing newlines
* Ignore stack descriptions

And the above options to ignore should be adjusted per case... So I guess it is better to make this a separate module, stating that it is only *a best guess*.

Once Cloudformation itself offers a *dry* run, that part should go into the original module and mine should be removed.

**Comment by cytopia** [comment]
@willthames why has the label `ci_verified` been removed?

**Comment by tedder** [comment]
`close_me`, this done in the `cloudformation` module with #23483. That'll cut down the parallel development

**Pull request closed without merging**
