### PR TITLE
Permit logging of all commands executed/shelled

### PR DESCRIPTION
**Pull request by ghost**
This may be the wrong way to go about this, but I have not been able to find a solution with callbacks as they just don't seem to have the information. I am looking for a way to log _all_ commands shelled out by Ansible. Here's an example of these logs from a simple Ansible playbook that does Gather Facts and installs Apache.

```
May 13 15:00:03 testserver ansible-setup: Invoked with filter=* fact_path=/etc/ansible/facts.d 
May 13 15:00:03 testserver ansible-setup: /sbin/ip -4 route get 8.8.8.8
May 13 15:00:03 testserver ansible-setup: /sbin/ip -6 route get 2404:6800:400a:800::1012
May 13 15:00:03 testserver ansible-setup: /sbin/ip addr show primary lo
May 13 15:00:03 testserver ansible-setup: /sbin/ip addr show secondary lo
May 13 15:00:03 testserver ansible-setup: /sbin/ip addr show primary eth1
May 13 15:00:03 testserver ansible-setup: /sbin/ip addr show secondary eth1
May 13 15:00:03 testserver ansible-setup: /sbin/ip addr show primary eth0
May 13 15:00:03 testserver ansible-setup: /sbin/ip addr show secondary eth0
May 13 15:00:04 testserver ansible-yum: Invoked with name=httpd list=None install_repoquery=True conf_file=None disable_gpg_check=False state=latest disablerepo=None enablerepo=None 
May 13 15:00:04 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q '--disablerepo=*' --pkgnarrow=installed --qf '%{name}-%{version}-%{release}.%{arch}' httpd
May 13 15:00:05 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q '--disablerepo=*' --pkgnarrow=installed --qf '%{name}-%{version}-%{release}.%{arch}' --whatprovides httpd
May 13 15:00:05 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q --qf '%{name}-%{version}-%{release}.%{arch}' --whatprovides httpd
May 13 15:00:31 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q --qf '%{name}-%{version}-%{release}.%{arch}' httpd
May 13 15:00:32 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q --qf '%{name}-%{version}-%{release}.%{arch}' httpd-2.2.15-9.0.1.el6_1.2.x86_64
May 13 15:00:32 testserver ansible-yum: /usr/bin/yum -d 2 -y install httpd
May 13 15:00:41 testserver ansible-yum: Invoked with name=mod_ssl list=None install_repoquery=True conf_file=None disable_gpg_check=False state=latest disablerepo=None enablerepo=None 
May 13 15:00:41 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q '--disablerepo=*' --pkgnarrow=installed --qf '%{name}-%{version}-%{release}.%{arch}' mod_ssl
May 13 15:00:41 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q '--disablerepo=*' --pkgnarrow=installed --qf '%{name}-%{version}-%{release}.%{arch}' --whatprovides mod_ssl
May 13 15:00:41 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q --qf '%{name}-%{version}-%{release}.%{arch}' --whatprovides mod_ssl
May 13 15:00:41 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q --qf '%{name}-%{version}-%{release}.%{arch}' mod_ssl
May 13 15:00:42 testserver ansible-yum: /usr/bin/repoquery --show-duplicates --plugins --quiet -q --qf '%{name}-%{version}-%{release}.%{arch}' mod_ssl-2.2.15-39.0.1.el6.x86_64
May 13 15:00:42 testserver ansible-yum: /usr/bin/yum -d 2 -y install mod_ssl
May 13 15:00:46 testserver ansible-file: Invoked with directory_mode=None force=False remote_src=None path=/var/log/httpd owner=root follow=False group=root state=directory content=NOT_LOGGING_PARAMETER serole=None diff_peek=None setype=None selevel=None original_basename=None regexp=None validate=None src=None seuser=None recurse=False delimiter=None mode=0750 backup=None 
May 13 15:00:47 testserver ansible-service: Invoked with name=httpd pattern=None enabled=True state=started sleep=None arguments= runlevel=default 
May 13 15:00:47 testserver ansible-service: /sbin/chkconfig --list httpd
May 13 15:00:47 testserver ansible-service: /sbin/chkconfig httpd on
May 13 15:00:47 testserver ansible-service: /sbin/initctl status httpd
May 13 15:00:48 testserver ansible-service: Invoked with name=httpd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default 
May 13 15:00:48 testserver ansible-service: /sbin/initctl status httpd
```

### CODE REVIEW

**Comment by ghost** [comment]
The requirement here is you set ANSIBLE_LOG_COMMANDS=TRUE to make this logging happen and since you can't do playbook-wide envs I'm just hacking around it by setting this env in /etc/environment on the target hosts that need to get this logging enabled.

**Comment by bcoca** [comment]
'environment' is an allowed keyword in plays (since 1.9 iirc)

We would prefer this as a directive though.

**Comment by ghost** [comment]
I'm just stabbing blindly here, so if you can help me to figure out what the most elegant way of doing this is or somehow integrating this logging into a verbose setting or feature flag that would be excellent. My research led me down many dead ends as the contents of basic.py are shipped to the target and executed there which means it loses access to a lot of useful information (I think).

**Comment by bcoca** [comment]
i'm tempted to make this a debug/audit flag

**Comment by msabramo** [comment]
This would be cool to have. Also nice to have would be a way to get ansible to show stdout from tasks but without the full JSON objects with `start`, `end`, `delta`, etc. I find that I either get not enough output or too much and what I really want is in between. E.g.:
- http://stackoverflow.com/questions/20563639/ansible-playbook-shell-output
- http://blog.cliffano.com/2014/04/06/human-readable-ansible-playbook-log-output-using-callback-plugin/

I wonder if the -v flags could be augmented with something more granular. E.g.:
- `--show-commands`
- `--show-stdout`

**Comment by msabramo** [comment]
See http://stackoverflow.com/questions/20563639/ansible-playbook-shell-output

**Comment by bcoca** [comment]
so this is the 'correct' place to enable logging of shelled commands, but the mechanism to pass the activation needs to be different. It is quite complicated at this point, I'll look into drumming up an example.

**Comment by ghost** [comment]
Thanks! Our Security and Risk teams would greatly appreciate the extra verbosity. :+1:

**Comment by amenonsen** [comment]
@bcoca any news here? I could also use this feature.

**Comment by bcoca** [comment]
fixed via ddafed4403756577ff4274e75cc753b853d5a5e3, this is now tied to the ansible having debug=true

**Pull request closed without merging**
