### PR TITLE
New boto3_facts module

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY

boto3_facts aims to help users see whether their python and module
versions are as expected.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
boto3_facts

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (devel 88764165ad) last updated 2018/06/29 08:09:23 (GMT +1000)
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/will/src/opensource/ansible/lib/ansible
  executable location = /Users/will/src/opensource/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

### CODE REVIEW

**Comment by ryansb** [comment]
I'm a bit conflicted on this: giving the version and python path that Ansible+cloud modules are using seems really useful. 

The way we should solve this for modules is to use `boto3_at_least()` and `botocore_at_least()` to require the right versions for the features of each module. The issue that causes is, of course, that a user may get halfway through a playbook and *only then* get the failure notification of the boto3/botocore version, because their modules up to that point allowed an old enough version of boto3 to continue. 

I don't like needing users to add tasks ahead of time to do checking, but if we have to support a case like this, maybe the best option would be to do something like `assert_python_requirements` or similar, where users could do something like:

```
- assert_python_requirements:
    modules:
      - boto3>1.9
      - botocore>=1.4.11
      - docker>1.0
      - azure-sdk>5.1
      - requests>3
```

That way we'd be able to benefit AWS module users as well as anyone else using a module that needs a third-party library.

**Comment by willthames** [comment]
I don't think your solution solves the problem at hand @ryansb.

We'll always have the problem where we get support requests for modules that don't actually work with older botocore, the user does pip install --upgrade botocore, thinks they've solved the problem, and haven't because they're doing `connection: local` and as a result using a different python and botocore to the one they think they're using.

Asking a user to add a  `boto3_facts` task before a failing task would be an easy way for users to validate that they are using the version of botocore that they think they are.

The following playbook is insightful, on OS X at least:

```
- hosts: fakehost
  gather_facts: no
   
  tasks:
  - boto3_facts:
    delegate_to: localhost

- hosts: fakehost
  connection: local
  gather_facts: no
   
  tasks:
  - boto3_facts:
```

```
$ ansible-playbook boto3_facts.yml -v -i fakehost,
No config file found; using defaults

PLAY [fakehost] ******************************************************************************************************************************************************************************

TASK [boto3_facts] ***************************************************************************************************************************************************************************
ok: [fakehost -> localhost] => {"boto3_version": "1.7.42", "botocore_version": "1.10.42", "changed": false, "python": "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python", "python_version": "2.7.14 (default, Mar  9 2018, 23:57:12) \n[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]"}

PLAY [fakehost] ******************************************************************************************************************************************************************************

TASK [boto3_facts] ***************************************************************************************************************************************************************************
ok: [fakehost] => {"changed": false, "python": "/usr/bin/python", "python_version": "2.7.10 (default, Oct  6 2017, 22:29:07) \n[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]"}

PLAY RECAP ***********************************************************************************************************************************************************************************
fakehost                   : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by s-hertel** [comment]
It would be nice to have something like this. Remembering a docker issue that got out of hand because people continued to post to it after being closed (because of issues with installing the SDK in the right place), I kind of like the broader use case of 
```
- assert_python_requirements:
    modules:
      - boto3>1.9
      - botocore>=1.4.11
      - docker>1.0
      - azure-sdk>5.1
      - requests>3
```
As long as it also output information about which version was installed and accepted delegate_to, would it also solve the problem?

**Comment by willthames** [comment]
@s-hertel, I can see that would be handle the more general case if it also printed out python, python version.

Only problem would likely be ensuring that we parse the module constraints correctly

**Comment by ryansb** [comment]
@s-hertel so you're saying the return on this module (pass or fail) would include:

- Python path
- Existing versions of the specified packages
- Python version
- Site packages directory

That sounds like it would resolve both the interactive "which python is my stuff using" issue, as well as allow users to write playbooks requiring at least version `x.y.z` of boto3/botocore.

**Comment by ryansb** [comment]
@willthames I think we'd want to outsource parsing those constraints to the `pip` or `distutils` libraries. I definitely agree we shouldn't implement that sort of logic ourselves.

**Comment by willthames** [comment]
Superseded by #43108

**Pull request closed without merging**
