### PR TITLE
Fixed apt_key's add_key stalling indefinitely, and test code leaking into production

### PR DESCRIPTION
**Pull request by jlitola**
HEAD version of apt_key didn't work properly due missing input to "apt-get add -". Additionally bit of test code had improper indent level, causing it to be run in production.

### CODE REVIEW

**Comment by dhozac** [comment]
None of that test code should be in there. Feel free to remove all of it completely, and I'll go ahead and merge this.

**Comment by jlitola** [comment]
@dhozac 

Seems that the TestRunner is using environment variable ANSIBLE_TEST_APT_KEY for enabling mocking of some functions in apt_key, and thus removing the code from library/apt_key would break the tests.

**Comment by dhozac** [comment]
You can just remove the tests too. Such tests are not really useful. Actual testing of the module should be part of changing it, and obviously this didn't happen with the tests there...

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
