### PR TITLE
Add Support for bare repos

### PR DESCRIPTION
**Pull request by cg-soft**
This is the real one now. I recloned and reapplied my changes, so hopefully, this one is less messy.

I added one test and ensured stuff passes.

### CODE REVIEW

**Comment by mpdehaan** [comment]
So on the old commit I raised a question about what you use this for, can you share?

**Comment by cg-soft** [comment]
We use bare repos for three purposes:
- Central repos ala "github", i.e. places where folks push into and pull from, but never edit. This saves the space taken by the workspace.
- Reference repos used by our build slaves - which is the main reason I need them, since we use ansible to manage our build farm. See also <tt>--reference</tt> in https://www.kernel.org/pub/software/scm/git/docs/git-clone.html. We may wish to expose this flag in the git modules also, even though in my case I don't need it as jenkins will do the cloning.
- Temporary repos for various data gathering or interfacing with other tools. For example, Jira uses them to crossreference git commits with the issues referenced in those commits.

**Comment by cg-soft** [comment]
Rebased and added support for custom "origin" name for bare repos.

**Comment by sayap** [comment]
Pardon my ignorance, but why is it necessary to wrap things in `str()`?

**Comment by cg-soft** [comment]
I removed that in my latest commit.... for a while I had test failures
which appeared to be related to some unicode thing, but that was a red
herring.

**Comment by cg-soft** [comment]
Added support for "git clone --reference" and rebased.

**Comment by mpdehaan** [comment]
Commits are now super-mangled once again.

What you need to do is set up a new branch in git for every topic you are working on.   This is called a "topic branch" if you want to read up on it (google: "git topic branch").

From there, always use "git pull --rebase" and "git pull" vs "git pull" or "git merge".   This will prevent stray commits from entering the history of the pull request, and only your commits will come up in the review.

Sorry about the confusion and I am happy to let you resubmit if you like, and would hope that you do.

Once you get it squared away it is not too bad.

(Doing everything on one branch is the cause of most problems)

Thanks!

**Pull request closed without merging**
