### PR TITLE
Add '--playbook-dir' argument to the command-line interface 'ansible-playbook'

### PR DESCRIPTION
**Pull request by jamescherti**
##### SUMMARY
This pull request adds '--playbook-dir' argument to the command-line interface 'ansible-playbook'.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- ansible-playbook

### CODE REVIEW

**Comment by bcoca** [comment]
why?

needs_info

**Comment by jamescherti** [comment]
Source code editor plugins like [ale](https://github.com/dense-analysis/ale) copy the Ansible Playbook that is edited to '/tmp/RANDOMNAME.yml', and execute syntax checkers against the temporary file it created (it executes commands like: 'ansible-lint' and 'ansible-playbook --syntax-check' against files that are located in /tmp/, instead of executing them from the project or Ansible Playbook directory).  

The Ansible Playbook that is edited is copied to /tmp/ because it allows [ale](https://github.com/dense-analysis/ale) to check the syntax of the Ansible Playbook while the user is typing it (this avoids forcing the user to save the file to check for errors or warnings).

The '--playbook-dir' argument will allow the user to execute or check the syntax of an Ansible Playbook from any location (including the standard input).

**Steps to reproduce the issue:**

Create the directory ~/test_project/:
```
$ mkdir ~/test_project
$ cd ~/test_project
```

Create the file "import.yml":
```
---

- debug: msg="debug message"
```

Create the file "test.yml":
```
---

- hosts: localhost
  tasks:
    - name: "import_tasks: from import.yml"
      import_tasks: import.yml
```

Execute 'ansible-playbook' against 'import.yml' (result: no error):
```
$ ansible-playbook --syntax-check test.yml ; echo "Errno: $?"
Errno: 0
```

Copy test.yml to /tmp/ and execute ansible-playbook against /tmp/test.yml (result: error):
```
$ ansible-playbook --syntax-check /tmp/test.yml ; echo "Errno: $?"
ERROR! Unable to retrieve file contents
Could not find or access '/tmp/import.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
Errno: 1
```

With --playbook-dir argument, the user will be able to specify the project / Ansible Playbook directory (result: success):
```
$ ansible-playbook --syntax-check /tmp/test.yml --playbook-dir ~/test_project ; echo "Errno: $?"
```

**Comment by bcoca** [comment]
at this point it is not the playbookdir ... and we really don't have a 'project' concept (awx/tower/controller does)

**Comment by jamescherti** [comment]
If what I explained is not a --playbook-dir / Playbook Directory, what should it be called? --project-dir (like ansible-lint)? Other?

(the purpose of this pull request is to allow the user to specify the directory from which the Ansible Playbook will be executed)

**Comment by sivel** [comment]
Aside from naming, I think you'll need to convince us that the feature needs to exist first.

**Comment by jamescherti** [comment]
I will discuss this with the maintainers of ansible-lint https://github.com/ansible-community/ansible-lint/issues/1651 and get back to you.

**Pull request closed without merging**
