### PR TITLE
Add support for same SSH and sudo password (follow up to pull request #2548)

### PR DESCRIPTION
**Pull request by stoned**
- option --same-pass/-j
- configuration file 'same_pass' item
- environment variable ANSIBLE_SAME_PASS

### CODE REVIEW

**Comment by mpdehaan** [comment]
thinking about this, what if we just made it that if you did --ask-pass and --ask-sudo-password and your sudo password was <ENTER>, it just used the same thing you gave for --ask-pass?

That way we could avoid the extra option altogether.

**Comment by stoned** [comment]
You mean if you answer a stray/single return to the 'sudo password:' prompt we should consider the sudo password to be the same as the SSH password if it was provided ?

**Comment by mpdehaan** [comment]
maybe?

I am thinking of how we can get away without the option.

Basically it would be like the field having a default of the other, since
you said "let me enter this and the other" and then you entered the first
and then opted out of the second.

What do you think?

It's less options to remember, which strikes me as good, and we could even
update the prompt to say "[enter: same as previous]" or something?

**Comment by stoned** [comment]
That would also work for me. I'm going to implement it.

**Comment by mpdehaan** [comment]
Great!

I am trying to control option sprawl and I think that would be most
intuitive.

Perfect!

**Comment by stoned** [comment]
cf. pull request #2602

**Pull request closed without merging**
