### PR TITLE
Added win_reboot module and tests.

### PR DESCRIPTION
**Pull request by cchurch**
Add module to check if Windows host needs a reboot, reboot only if necessary, or force a reboot/shutdown.

### CODE REVIEW

**Comment by trondhindenes** [comment]
Nice! On 2012 and newer OS-es, there's one more check you can do using the servermanager namespace:
https://gist.github.com/trondhindenes/ea42b3cb517fec95bf8b

(The stuff I've seen from the PowerShell team uses this and the pendingfiles key in combination in order to check).

**Comment by wozz** [comment]
I think the winrm connection is being closed too soon with this module.  I keep getting a trace back when the connection closes.

```
fatal: [host] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible-1.7.1-py2.7.egg/ansible/runner/__init__.py", line 561, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible-1.7.1-py2.7.egg/ansible/runner/__init__.py", line 666, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible-1.7.1-py2.7.egg/ansible/runner/__init__.py", line 913, in _executor_internal_inner
    conn.close()
  File "/usr/local/lib/python2.7/site-packages/ansible-1.7.1-py2.7.egg/ansible/runner/connection_plugins/winrm.py", line 257, in close
    self.protocol.close_shell(self.shell_id)
  File "/usr/local/lib/python2.7/site-packages/winrm/protocol.py", line 192, in close_shell
    rs = self.send_message(xmltodict.unparse(rq))
  File "/usr/local/lib/python2.7/site-packages/winrm/protocol.py", line 173, in send_message
    return self.transport.send_message(message)
  File "/usr/local/lib/python2.7/site-packages/winrm/transport.py", line 103, in send_message
    raise WinRMTransportError('http', ex.reason)
WinRMTransportError: 500 WinRMTransport. [Errno 54] Connection reset by peer
```

**Comment by cchurch** [comment]
@wozz I haven't observed this issue (using OSX as the control machine and Windows 2008/2012 on Rackspace).  What environment are you testing against?

**Comment by wozz** [comment]
I'm using OSX as the control and controlling Windows 2008R2 on EC2.  It doesn't happen every time, but maybe 50%.

**Comment by wozz** [comment]
Checked on 2012 and I'm not getting any errors.  The issue seems specific to my 2008 setup.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
