### PR TITLE
Add support for multiple required auth for openssh v6.2 onwards.

### PR DESCRIPTION
**Pull request by wfranzini**

### CODE REVIEW

**Comment by jimi-c** [comment]
Hi @wfranzini, shouldn't this include a check of the SSH version, so that this doesn't break for older versions still?

**Comment by wfranzini** [comment]
Hi @jimi-c I don't think a check against ssh version is required, since my commit just _drop_ GSSApiAuthentication=no and PubKeyAuthentication=no when a password is used.  

This feature is enable on the server side not on the client side (ie. I'm using ossh 6.0 client against ossh 6.2 server).

Let me know if more info are needed.

**Comment by amenonsen** [comment]
This PR the same as #6846, where I've posted an updated patch with the merge conflicts resolved. This PR can be closed. There are no backwards-compatibility concerns.

**Comment by bcoca** [comment]
closing this in favor of dupe #6846

**Pull request closed without merging**
