### PR TITLE
jenkins_plugin: Adds url_password documentation

### PR DESCRIPTION
**Pull request by deiga**
##### SUMMARY

Add missing documentation for `url_password` option for the `jenkins_plugin` module

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

jenkins_plugin
##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jtyr** [comment]
Thanks for opening this PR, @deiga. There is more parameters than just the `url_password` inherited from the `module_utils`. Please see:

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L974

Instead of documenting all of these, I would prefer to make a **Note** that all `url_argument_spec` parameters are available in this module as well and link to the right page (if there is any).

**Comment by deiga** [comment]
@jtyr, Huh, I didn't know that :)

Are there any existing examples in documentation for the `url_argument_spec`?

**Comment by jtyr** [comment]
This I don't know. Google is your friend ;o)

**Comment by Akasurde** [comment]
resolved_by_pr #34895

**Pull request closed without merging**
