### PR TITLE
Enable filters test for python 3

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

tests

### CODE REVIEW

**Comment by mscherer** [comment]
This fail on:
```
TASK [lookups : create a password (with salt) file] ****************************
fatal: [testhost]: FAILED! => {"failed": true, "msg": "Unexpected templating type error occurred on ({{ lookup('password', output_dir + '/lookup/password_with_salt encrypt=sha256_crypt') }}): salt must be unicode, not bytes"}
```

Which is different from https://github.com/ansible/ansible/issues/17308

**Comment by mscherer** [comment]
So this PR is linked to https://github.com/ansible/ansible/issues/17308 (but at the time I comment, shippable do not react)

**Comment by mscherer** [comment]
So now that #17308 is fixed, and since CI should be green (it was red due to yum timeout), I guess this one can be merged ?

**Comment by abadger** [comment]
Merged to devel and cherry-picked to stable-2.2

**Pull request merged**
