### PR TITLE
Fixes generators and other misc fixes

### PR DESCRIPTION
**Pull request by caphrim007**
##### SUMMARY
fixed itertools.imap busting several things that used to be lists,
profiles not being set correctly, upon create, when it was a separate
method, allowed port having the wrong lowest port (zero is allowed),
empty port value should just be interpreted as None.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/f5/bigip_virtual_server.py

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by caphrim007** [comment]
ready_for_review

**Comment by caphrim007** [comment]
@gundalow

**Comment by caphrim007** [comment]
or @Qalthos merge at your convenience

**Comment by gundalow** [comment]
Does this need backporting to `stable-2.3`?

**Comment by caphrim007** [comment]
@gundalow that'd be nice if it could be

**Comment by gundalow** [comment]
Cherry picked into `stable-2.3` https://github.com/ansible/ansible/pull/23172

**Pull request merged**
