### PR TITLE
add a new module ce_ftp that is used to transfer file.

### PR DESCRIPTION
**Pull request by wxxyd**
##### SUMMARY

add a new module ce_ftp that is used to transfer file.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/cloudengine/ce_ftp.py
##### ADDITIONAL INFORMATION

```paste below
EXAMPLES :
 '''
    - name: "ftp get file"
      ce_ftp:
        ftp_server: 10.78.106.33
        ftp_user: huawei
        ftp_password: huaweiDC
        remote_file: /mpu/profile_666_04211257.dat
        local_file: /usr/xuyuandong/1.txt 
        mode: get
'''
return :
'''
    "changed": true,
    "local_file": {
        "date": "Nov 07 16:57:47 2018",
        "name": "/usr/xuyuandong/1.txt",
        "size": "10,153,720 (Byte)"
    },
    "mode": "get",
    "remote_file": {
        "date": "Apr 21  2015",
        "name": "/mpu/profile_666_04211257.dat",
        "size": "10,153,720 (Byte)"
    }
'''
```

### CODE REVIEW

**Comment by justbiaoliu** [comment]
shipit

**Comment by liukun2348** [comment]
shipit

**Comment by xuxiaowei0512** [comment]
shipit

**Review by yuandongx — APPROVED** [review]

**Review by yuandongx — COMMENTED** [review]
shipit

**Review by justbiaoliu — COMMENTED** [review]
shipit

**Review by liukun2348 — COMMENTED** [review]
shipit

**Comment by xuyuandong0512** [comment]
bot_status

**Pull request closed without merging**
