### PR TITLE
VMware: create a diskless VM using vmware_guest

### PR DESCRIPTION
**Pull request by itaispiegel**
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
vmware_guest module does not allow creating a VM without a disk.
The issue appears to be in the select_datastore function. The function checks different edge cases, and for the case of not cloning from a template and not providing a disk, the function will fail with the reason of failing to find a matching datastore.

```python
if not datastore:
    if len(self.params['disk']) != 0 or self.params['template'] is None:
        self.module.fail_json(msg="Unable to find the datastore with given parameters."
                                  " This could mean, %s is a non-existent virtual machine and module tried to"
                                  " deploy it as new virtual machine with no disk. Please specify disks parameter"
                                  " or specify template to clone from." % self.params['name'])
    self.module.fail_json(msg="Failed to find a matching datastore")
```

##### STEPS TO REPRODUCE
```yaml
```

##### ACTUAL RESULTS
```

```
#39743

### CODE REVIEW

**Comment by Akasurde** [comment]
@itaispiegel Thanks for the PR. Could you please rebase ?

**Comment by Akasurde** [comment]
@itaispiegel There is already one open PR which achieve this - https://github.com/ansible/ansible/pull/35812

**Comment by Akasurde** [comment]
@itaispiegel Did you get chance to try above mentioned PR ? needs_info

**Comment by itaispiegel** [comment]
Yes, I'm sorry that I didn't response in quite a while.
The other PR that you posted does not solve this issue, since it does not change the case that the user hasn't provided a template to clone from or a disk to add to the VM. Thus it will still fail.

I'll fix the conflicts and then I hope we can merge this :)

**Comment by itaispiegel** [comment]
I finished fixing the conflicts and I think that we can finally get this DONE :)

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible/ansible/pull/66057

**Pull request closed without merging**
