### PR TITLE
Adding --list-vars option to ansible-playbook

### PR DESCRIPTION
**Pull request by risingmoon**
I wanted a way to list out variables without running any plays.

First commit is the implementation of the code.
Second commit is my efforts to refactor and implement some PEP8 standards to this file.

### CODE REVIEW

**Comment by bcoca** [comment]
we don't normally take formatting patches as they obscure the origins, also the 80 column limit is something we don't agree with much, at this point with screen size evolution it is actually counter productive.

**Comment by risingmoon** [comment]
If I omit the second commit and PEP8 style changes then it should be fine?

**Comment by risingmoon** [comment]
@bcoca I've removed the styling formats and just moved my imports to the top.

**Comment by risingmoon** [comment]
Fixed merge conflicts.

**Pull request closed without merging**
