### PR TITLE
New module win_service_stat

### PR DESCRIPTION
**Pull request by trondhindenes**
##### SUMMARY
New module win_service_stat to return information about windows services

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_service_stat

##### ANSIBLE VERSION
```
2.5.0
```

##### ADDITIONAL INFORMATION
A simple module which returns info about whether a service exists or not, and some more info if it does. Can be used to conditionally perform software upgrades etc.

### CODE REVIEW

**Comment by trondhindenes** [comment]
Hm looks like I have to tweak the script to work on 2008R2 aswell. I'll be back!

**Comment by jborean93** [comment]
Hey @trondhindenes, I don’t think this is needed. You can run the current win_service with just `name` and it gives you the info about the service including whether it exists or not.

**Comment by trondhindenes** [comment]
Hm! If that's the case, I'd say documentation for win_service is missing some important pieces. Checking.

**Comment by trondhindenes** [comment]
You're absolutely right, and it also gracefully handles non-existing services. Closing this, will open a new one to get docs right.

**Comment by trondhindenes** [comment]
Closing. Docs update in #32320

**Pull request closed without merging**
