### PR TITLE
New AWS module for describing RDS facts using boto3

### PR DESCRIPTION
**Pull request by naslanidis**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

rds_facts
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel e396d5d508) last updated 2016/08/24 12:13:10 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 368ca738fa) last updated 2016/08/24 12:13:21 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 0749ce6faa) last updated 2016/08/24 12:13:30 (GMT +1000)
```
##### SUMMARY

This is a facts module for describing RDS instances in AWS using the current boto3 API.

Note: There is a facts command option within the older RDS module however this uses the old API and doesn't provide information required for working with Aurora, encryption and other newer features. 

```
TASK [print rds facts] *********************************************************
ok: [localhost] => {
    "msg": {
        "changed": false, 
        "db_instances": [
            {
                "AllocatedStorage": 25, 
                "AutoMinorVersionUpgrade": true, 
                "AvailabilityZone": "ap-southeast-2b", 
                "BackupRetentionPeriod": 7, 
                "CACertificateIdentifier": "rds-ca-2015", 
                "CopyTagsToSnapshot": false, 
                "DBInstanceClass": "db.t2.medium", 
                "DBInstanceIdentifier": "test-instance", 
                "DBInstanceStatus": "available", 
                "DBParameterGroups": [
                    {
                        "DBParameterGroupName": "test-param-group", 
                        "ParameterApplyStatus": "in-sync"
                    }
                ], 
                "DBSecurityGroups": [], 
                "DBSubnetGroup": {
                    "DBSubnetGroupDescription": "Dev subnet group", 
                    "DBSubnetGroupName": "test-subnet-group", 
                    "SubnetGroupStatus": "Complete", 
                    "Subnets": [
                        {
                            "SubnetAvailabilityZone": {
                                "Name": "ap-southeast-2b"
                            }, 
                            "SubnetIdentifier": "subnet-25bef123", 
                            "SubnetStatus": "Active"
                        }, 
                        {
                            "SubnetAvailabilityZone": {
                                "Name": "ap-southeast-2a"
                            }, 
                            "SubnetIdentifier": "subnet-ac680123", 
                            "SubnetStatus": "Active"
                        }
                    ], 
                    "VpcId": "vpc-aad24123"
                }, 
                "DbInstancePort": 0, 
                "DbiResourceId": "db-WJWNIULS77P3NJY7RGZNCPHTBA", 
                "Endpoint": {
                    "Address": "test-instance.c4nb0jta2bug.ap-southeast-2.rds.amazonaws.com", 
                    "HostedZoneId": "Z32T0VRHXEXXXX", 
                    "Port": 3306
                }, 
                "Engine": "mysql", 
                "EngineVersion": "5.6.23", 
                "InstanceCreateTime": "2016-09-04T08:58:56.275000+00:00", 
                "LatestRestorableTime": "2016-09-04T09:10:00+00:00", 
                "LicenseModel": "general-public-license", 
                "MasterUsername": "root", 
                "MonitoringInterval": 0, 
                "MultiAZ": false, 
                "OptionGroupMemberships": [
                    {
                        "OptionGroupName": "test-option-group", 
                        "Status": "in-sync"
                    }
                ], 
                "PendingModifiedValues": {}, 
                "PreferredBackupWindow": "12:37-13:07", 
                "PreferredMaintenanceWindow": "sat:19:06-sat:19:36", 
                "PubliclyAccessible": false, 
                "ReadReplicaDBInstanceIdentifiers": [], 
                "StorageEncrypted": false, 
                "StorageType": "gp2", 
                "VpcSecurityGroups": [
                    {
                        "Status": "active", 
                        "VpcSecurityGroupId": "sg-a5838123"
                    }
                ]
            }
        ]
    }
}
```

### CODE REVIEW

**Comment by naslanidis** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2847

**Comment by willthames** [comment]
See also #19772 - I'm pretty certain this PR has more features but I'd like to standardise on a common results output backward compatible with the old `rds` module - would be good to merge approach if possible

**Comment by mattclay** [comment]
CI failure due to:

```
2017-02-02 01:16:52 iteritems has been removed in python3.  Alternatives:
2017-02-02 01:16:52     for KEY, VALUE in DICT.items():
2017-02-02 01:16:52     from ansible.module_utils.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-02-02 01:16:52     from ansible.compat.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-02-02 01:16:52 ./lib/ansible/modules/cloud/amazon/rds_facts.py:        for key, value in module.params.get('filters').iteritems():
```

**Comment by willthames** [comment]
#21884 should provide improved rds_snapshot_facts and rds_instance_facts modules. There's probably more to be done to add additional data in the returned instance facts.

**Comment by tremble** [comment]
close_me

It looks like rds_instance_info should cover this.

**Pull request closed without merging**
