### PR TITLE
assume 'all' when only exclusions added to subset

### LINKED ISSUE #30929: Fact ansible_mounts does not exist if facter facts are excluded
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

setup

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = []
  ansible python module location = /home/tkrahn/.virtualenvs/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/tkrahn/.virtualenvs/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION

DEFAULT_GATHER_SUBSET(/home/tkrahn/workspace/ansible/ansible.cfg) = !facter

##### SUMMARY

If facter facts are not gathered fact _ansible_mounts_ does not exist.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: true
  tasks:
  - debug: var=ansible_mounts
```

##### EXPECTED RESULTS

Fact _ansible_mounts_ is provided

##### ACTUAL RESULTS

Fact _ansible_mounts_ is not provided. 

```

```

I might be wrong but as far as i remember facter facts are always  prefixed with __facter__

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

fixes #30929

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

fact gathering
##### ANSIBLE VERSION

```
2.x
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/81213/4/tests
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/81213/55/tests

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/87755/8/tests

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/92474/5/tests
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/92474/56/tests

**Comment by nitzmahone** [comment]
It's been calcified this way for so long that changing it now would probably cause more problems than it solves... Closing.

**Pull request closed without merging**
