### PR TITLE
win_tempfile: New module implementing tempfile on Windows

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

win_tempfile

##### ANSIBLE VERSION

v2.3

##### SUMMARY

This module implements the **tempfile** module for Windows.

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to PEP 8 issue:

```
2017-02-18 21:56:58 ERROR: PEP 8: lib/ansible/modules/windows/win_tempfile.py:72:4: W292 no newline at end of file (current)
```

The PEP 8 tests can be run locally with `make pep8`.

**Comment by jhawkesworth** [comment]
Tested against windows 10.
Hopefully this will turn you into a windows module maintainer, @dagwieers so then your windows ship its can take effect.

shipit

**Comment by dagwieers** [comment]
I am already the maintainer of win_psexec and win_shortcut, but that is not enough ;-)

**Comment by jborean93** [comment]
Having a look now, you will need to add your github account and the module to https://github.com/ansible/ansibullbot/blob/master/MAINTAINERS.txt for you to be considered a maintainer.

**Comment by dagwieers** [comment]
Aha, I thought it was something you had to earn...
ansible/ansibullbot#378
Achievement unlocked !

**Comment by jborean93** [comment]
Looks good, looking forward to your ship its working :)

shipit

**Pull request merged**
