### PR TITLE
locale module

### PR DESCRIPTION
**Pull request by AugustusKling**
Module to implement basic handling of locales as requested in issue #5314. It accepts locales when given in the form of `en_US.UTF-8`. Creation and removal of locales is handled via locale-gen.
So far I have only tested/used the module with Debian 7.

Note that I'm only aware of Ansible since yesterday evening so I may well have missed some existing building blocks. If this is the case, please point me to common building blocks (such as file manipulation and process handling).

### CODE REVIEW

**Comment by ometra** [comment]
Useful module for base system setup, thanks !

Just a problem : on Ubuntu, the file `/etc/locale.gen` is replaced by multiple files under `/var/lib/locales/supported.d/`.

**Comment by AugustusKling** [comment]
To collect some sources and try to understand the reasoning behind Ubuntu's approach.

https://wiki.ubuntu.com/LocalesThatDontSuck:
_Getting locale changes into upstream glibc is unnecessarily hard. The glibc maintainer (correctly) requires proof of the correctness of a change before it's included, but the onus of demonstrating that change falls to the glibc package maintainers._
[…]
_In addition, updating locales requires a complete rebuild of the glibc package. This is a very time and resource intensive build just for the sake of arch-indep files._
According to https://blueprints.launchpad.net/ubuntu/+spec/belocs-locales this proposed spec has been implemented.

Basically Ubuntu split locale management into multiple configuration files, one per language. These are stored in `/var/lib/locales/supported.d/*` when a language pack is installed. That language pack is a package called `language-pack-de-base` for example for German locales and provides `/var/lib/locales/supported.d/de`.
`/var/lib/locales/supported.d/de` contains:

```
de_DE.UTF-8 UTF-8
de_CH.UTF-8 UTF-8
de_BE.UTF-8 UTF-8
de_LI.UTF-8 UTF-8
de_LU.UTF-8 UTF-8
de_AT.UTF-8 UTF-8
```

Ubuntu does have a modified version of `locale-gen` which optionally takes a locale to install. If not given it reads all lines in `/var/lib/locales/supported.d/*` and installs/removes locales from the system to match what it found in `/var/lib/locales/supported.d/*`. Additionally `/usr/share/locales/install-language-pack` and `/usr/share/locales/remove-language-pack` are provided to facilitate working with locales.

To me it seems that for Ubuntu you might be better off to just go for the language packs instead of single locales and thus manage the locales using `apt`. For example in ansible you could use:

```
  - name: German locales are present in Ubuntu
    apt: pkg=language-pack-de-base
```

That being said I see still use in handling Ubuntu with an amended locale module for ansible to gain independence of distributions. However I'm not sure what implementation would be most reliable and future proof given the documentation for Ubuntu is vague; even https://help.ubuntu.com/community/Locale says:
_There is precious little documentation covering locales, either in books or on the web._

Assuming handling for Ubuntu is added to the ansible module, what is your opinion on just calling the scripts in `/usr/share/locales/`?

**Comment by ometra** [comment]
Using the scripts in `/usr/share/locales/` forces us to use different module parameters for Ubuntu (`de` vs `de_DE.UTF-8`) and we loose the granularity of the Debian way. 

It seems that generating locale using `locale-gen` with locale to install on Ubuntu updates the file `/var/lib/locales/supported.d/local` (that's the way I use it). If it's true, the module just needs to be modified to update this file on Ubuntu instead of `/etc/locale.gen` in the `replace_line` method independently of the language packs support.

**Comment by AugustusKling** [comment]
It seems the scripts are not meant to be called outwit package management and their use for our purposes is probably a bad idea.

Directly modifying `/var/lib/locales/supported.d/local` followed by calling `locale-gen` (or calling `locale-gen` with a locale as parameter) results in installing that locale (and only the given locale). Stripping the locale from `/var/lib/locales/supported.d/local` followed by calls to `locale-gen` does however not remove the locale.
A locale installed without using the language packs can be removed with a call similar to `localedef --delete-from-archive it_IT.utf8`.

Sadly editing another file is not good enough as we'd loose the possibility to get rid of locales once they are not needed anymore. I have yet to find proper documentation for Ubuntu that allows to distinguish between the proper way of adding and removing single locales from calls that just work coincidentally on a single Ubuntu release.

**Comment by ometra** [comment]
What about calling `locale-gen` with the `--purge` option which removes all existing locales before processing ?

**Comment by AugustusKling** [comment]
It should now be possible to add and remove locales on Ubuntu, too. Removing locales takes a while if many locales are installed, though, because `locale-gen --purge` regenerates all locales in addition to purging the single unwanted locale.
Those distributions that work like Debian should continue to work.

Please test and report back.

**Comment by htgoebel** [comment]
I have several issues with this module:
1) It is **Ubuntu-only**. It not even works on Debian, as Debian does not have `/var/lib/locales/`
2) **Function**: From a module called `locale` I'd expect to **set the locale**.
3) **Naming**: As this module only _generates_ locales, it should be called _locale-gen_ (or such like).

**Comment by AugustusKling** [comment]
The code works fine for me on Debian and Ubuntu. Please detail _precisely_ what you mean by setting the locale.
It is essential to include more detail if you want helpful advise on why something does not work.

**Comment by htgoebel** [comment]
Maybe it woks on Debian 7. But my Deian 6 system does not have /var/lib/locales/. But for sure, this will not work on Fedora, Suse, Mageia.On these, there is no need to generate locale files on the fly.

But I would appreciate being able to _set_ the locale environment (e.g. /etc/default/locale, /etc/sysconfig/i18n). And this is what I'd expect from a module called `locale`.

**Comment by aisrael** [comment]
+1 on renaming this `locale-gen`, and then maybe creating another module `locale` to _set_ the locale (right now I just call `/usr/sbin/update-locale` on Ubuntu).

**Comment by jimi-c** [comment]
We're going to merge this, but per the comments above we're going to rename it to `locale_gen` per our naming convention for modules.

**Comment by jimi-c** [comment]
Thanks!

**Comment by AugustusKling** [comment]
I was going to change the name as per the comments but just did not find the time yet to do so. Thanks to all for testing and commenting.

**Pull request merged**
