### PR TITLE
Allow ansible-galaxy to install roles from URLs

### PR DESCRIPTION
**Pull request by willthames**
ansible-galaxy can now refer to SCM URLs (git and hg at this point)
for role names
Dependencies need to use the full SCM URLs too.
Otherwise all seems to work well

Test rolesfile

```
http://bitbucket.org/willthames/git-ansible-galaxy,v1.1
https://bitbucket.org/willthames/hg-ansible-galaxy
```

(works with ssh too)

### CODE REVIEW

**Comment by mpdehaan** [comment]
As posted to the ML, how does the code know a http:// and https:// URL is git or hg or svn?

I'm wondering if maybe we need to do git+https:// or something.

**Comment by willthames** [comment]
@mpdehaan see lines 334 onwards. It uses `git ls-remote` and `hg identity` - whichever has an exit status of 0 is the right SCM to use. 

No real need for the git+https although might want to extend it to svn, bzr etc.

**Comment by willthames** [comment]
Changed to use git+http as it does make determining SCM simpler and more explicit. 

I can squash commits before this is accepted but wanted to preserve history for now in case this needs further revision.

**Comment by mpdehaan** [comment]
Checking this out now...

**Comment by mpdehaan** [comment]
Awesome, I've merged this, also adding a docs section to the ansible-galaxy docs page.

I've also upgraded error handling in a few minor places, and made the system understand that github.com URLs are git+ protocol in a few cases, as I originally found the "non-tarball" message a little confusing and wanted to fix that up.

This works solidly and I greatly appreciate the tests.

Docs should appear soon and I'll also write the list about this.

We also need to update the galaxy website eventually to cross-reference docs about these options.

Thank you very much this will be a very very popular feature!

**Comment by mpdehaan** [comment]
Closing this, I'll reply to the list discussion in a bit.

Thanks!

**Comment by ibratoev** [comment]
it already is ;)

**Comment by willthames** [comment]
Awesome, that's great news.

I haven't had a look yet but on your note regarding github, it should be
able to handle downloading from a github URL pointing to an archive rather
than a repo. I think there's an integration test for that.

Will

**Comment by willthames** [comment]
Created #8714 for the github archive problem.

**Pull request closed without merging**
