### PR TITLE
Use a sensible default value for -d in ansible-pull, if not provided

### PR DESCRIPTION
**Pull request by mscherer**
This permit to prototype faster the usage, and reduce error
( since some people may likely checkout in /tmp or something
like this without thinking about it )

### CODE REVIEW

**Comment by mpdehaan** [comment]
Just a requests since I'm seeing this a lot in your commits, in the topic, please mention what piece of ansible the pull request is about, from the topic you can't tell this is about ansible-pull.  Thanks!

Why is checking out into temp an error?   Seems like this would be better solved by a documentation update?

I also don't particularly care for this one as it would leave a bunch of temp files around if the playbook were to fail.

Thanks!

**Comment by mscherer** [comment]
My goal was to make the command line of ansible-pull as short as possible. While someone could perfectly use a fixed directory in /tmp , there is no way to make it safe without writing a complete shell script and so I suspect most people will just use a fixed directory ( like /tmp/checkout ) and i think this should be avoided. So directly integrating it in ansible-pull look like the best option.

Now, if you think that having directories is a problem, we can also clean it unconditionnaly if that's a temporary directory, it was just easier to not do it.

**Comment by pypingou** [comment]
FWIW I think @mscherer's approach is a good one.

**Comment by mscherer** [comment]
For the record, I have added auto cleaning ( using atexit ) on https://github.com/mscherer/ansible/tree/pull_temporary_dir 

I also fixed the commit changelog, so I hope this is better, but I will wait for Michael to be back on irc to discuss ( or rather tomorow ), as I do not want to propose a 2nd PR since this one was closed, and I feel this would be a bit rude to insist too much.

**Pull request closed without merging**
