### PR TITLE
Update connection logic in vmware module_utils

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix updates logic of connection in vmware module_utils

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/vmware.py

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
bot_status

**Comment by Akasurde** [comment]
@dagwieers we need one more shipit

**Comment by dagwieers** [comment]
@Akasurde Given the situation I think that's one too many ;-)

**Comment by Akasurde** [comment]
@jctanner Could you please merge this ?

**Comment by dagwieers** [comment]
I am very happy with this.

**Comment by Akasurde** [comment]
@dagwieers Thanks for review and merge.

**Pull request merged**
