### PR TITLE
Faster than normal clone, using git clone depth 1

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/ansible/ansible/issues/10080 #10080 
By default, git will clone full repository, it will eat your disk space.
For example, the linux kernel git repository larger than 1GB.
If you clone full repository, you may take long times and need more
diskspace.

We can make things getting easier, just clone git repo with depth.

it will working as normal, but save your time and diskspace.

### CODE REVIEW

**Comment by ghost** [comment]
Any problem with this pull request? can it be merged into master branch now?

**Comment by bcoca** [comment]
we go merging by priority and age, please be patient.

**Comment by ghost** [comment]
Two weeks past, any new updates?

**Comment by amenonsen** [comment]
I don't think this PR should be applied in its present form. At most, we want to add a sentence under the clone/cd/source example block that says "For a faster clone without full history, you can add the `--depth 1` option to the `git clone` command above". Repeating the block with one changed command is entirely unnecessary.

The patch also contains ten unrelated whitespace changes, so it'll inevitably accumulate merge conflicts over time.

**Comment by ghost** [comment]
Due to long time no active , i will close it .thanks

**Pull request closed without merging**
