### PR TITLE
adding selective rule addition & removal support to ec2_group while keep...

### PR DESCRIPTION
**Pull request by praddy**
Hi,

I am adding support for selectively adding or removing rules to/from security groups. The default behaviour is still the same old, "exact: no" should be used to trigger the selective behaviour. I have also refactored some of the code here as part of the this exercise.

Thanks,
- praddy

### CODE REVIEW

**Comment by jimi-c** [comment]
Very nice, I'll get this into queue for testing as soon as possible.

**Comment by praddy** [comment]
Awesome, thanks.

**Comment by praddy** [comment]
Added another commit which fixes another existing issue.

**Comment by mpdehaan** [comment]
I find the exact parameter here pretty confusing in particular WRT the explanation.   Typically we've done something like "append=yes|no".

**Comment by praddy** [comment]
Rebased the changes. @mpdehaan I chose exact because `exact=yes` means make the respective security group exactly what I wish to (in the module args), in case it already exists. That, in my opinion, is a destructive change and should be explicitly called out. Not sure if `append=no` sends as strong a message as `exact=yes`. In case of `exact=no`, `state` reflects what exactly would be done: `state=present` means respective rules will be added & `state=absent` means respective rules will be removed. I think using `append=yes` & `state=absent` together will be more confusing.

**Comment by mpdehaan** [comment]
# Possible Duplicated Efforts

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

It looks like the work from this pull request was duplicated by a recent change in the module.

For some additional information:

```
* we've recently accepted parameters that allowed two new parameters "purge_rules" and "purge_egress_rules" that control these items seperately
* these seem to offer the same capabilities
```

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always neccessary.

Thank you once again for this and your interest in Ansible!

**Comment by praddy** [comment]
I think the patch that has been accepted doesn't provide a way to selectively remove rules. This patch provides that functionality too.

**Pull request closed without merging**
