### PR TITLE
messaging: Add new modules for kafka-acls

### PR DESCRIPTION
**Pull request by gdelpierre**
##### SUMMARY
This module aims to allow a user to manage Kafka ACLs  

Internally it relies on kafka scripts (kafka-acls.sh).

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

 - kafka_acls.py

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/gdelpierre/devel/roles/ansible.cfg
  configured module search path = [u'./library/']
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

### CODE REVIEW

**Comment by gdelpierre** [comment]
cc @Spredzy @pilou- @mscherer @jwoodrich

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/37934/2/tests

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/38060/2/tests

**Comment by Akasurde** [comment]
Please submit a new module request to https://github.com/ansible-collections/community.general. Thanks for your contribution.

**Pull request closed without merging**
