### PR TITLE
File Lookup +  vault clean branch

### PR DESCRIPTION
**Pull request by bcoca**
rebased branch and pushed again but it doesn't seem to have been picked up in #8110

### CODE REVIEW

**Comment by damncabbage** [comment]
This looks like it's merge-conflicted again. :worried:

**Comment by bcoca** [comment]
back to drawing board

On Mon, Sep 15, 2014 at 9:17 PM, Rob Howard notifications@github.com
wrote:

> This looks like it's merge-conflicted again. [image: :worried:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/pull/8533#issuecomment-55682872.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
rebased, repushed, re ... tired

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by bcoca** [comment]
can this one be reopened? it doesn't affect the task library

**Comment by dellis23** [comment]
Can this be reopened?  This functionality is critical for any project that has a more than a couple of encrypted files IMO.

**Comment by raboof** [comment]
AFAICS this is a change to ansible's core, not to a module, so it should be re-openable, right?

**Comment by dellis23** [comment]
@raboof It seems like that's the case to me

**Comment by stevekaten** [comment]
+1.  Need this functionality.

**Comment by nocive** [comment]
+1

**Comment by raboof** [comment]
aaaand it won't apply cleanly anymore...

**Comment by bcoca** [comment]
i'll get to this soon

**Comment by mcameron** [comment]
+1

**Comment by mlartz** [comment]
+1, really need encrypted file support for keys, certificates, and such.

**Comment by pdostal** [comment]
+1, it'll be so useful.

**Comment by dwt** [comment]
+1

**Comment by ilya-epifanov** [comment]
+1

**Comment by flmmartins** [comment]
+1

**Comment by flmmartins** [comment]
I've tried using lookup as a way to get the content of an encrypted file and put the clear content inside a file in my remote but it's not working =(.
I don't want my encrypted content exposed using debug. Ideas?

  name: Create content for pem file if staging

  lineinfile: dest={{app_path}}/config/public.pem
              state=present
              backup=yes
              create=yes
              line="{{ lookup('file', 'files/staging/public.pem chars=ascii_letters,digits,hexdigits,punctuation') }}"

**Comment by aioue** [comment]
+1

**Comment by nodunnock** [comment]
+1, would love this feature

**Comment by esacteksab** [comment]
Came here looking for this feature. Would be incredibly useful!

**Comment by pdostal** [comment]
:+1: It'd be nice to **merge** rouge8/ansible@d1d5e1a !

**Comment by leetrout** [comment]
:shipit: Definitely a missing feature

**Comment by lorencarvalho** [comment]
ARGH I WANT IT

**Comment by Kahn** [comment]
+1 Looks good to me

**Comment by ienliven** [comment]
+1

**Comment by rypervenche** [comment]
+1 This would indeed be extremely useful.

**Comment by perzizzle** [comment]
+1

**Comment by mauricios** [comment]
+1 definitely a missing feature!

**Comment by nocive** [comment]
anybody home?

**Comment by bcoca** [comment]
this is on my list under 'post v2'

**Comment by leonard84** [comment]
+1 definitely needed

**Comment by mcameron** [comment]
People landing here might find this useful: https://gist.github.com/mcameron/1595a04f8efcd19138c2

**Comment by dwt** [comment]
@mcameron Uhm, are you seriously suggesting to protect ssh keys by base64 encoding them? 😟

**Comment by moorereason** [comment]
@dwt No, he's putting the base64 encoded key into a vaulted file.  From his instructions:  "Don't EVER forget to encrypt your vault-keys.yaml."

**Comment by bcoca** [comment]
base64 encoding 'protects' the key from mangling when passed in a text context (which can break binary data), its not security but makes it resistant to errors, this is also referenced as 'armor'.

Closing this PR w/o merging as I hope to have this built into v2 (current devel) soon, not only for lookups but for the copy module also.

**Comment by adeck** [comment]
+1

SYN?

**Pull request closed without merging**
