### PR TITLE
DellEMC PowerMAX and VMAX modules for Ansible

### PR DESCRIPTION
**Pull request by rawstorage**
##### SUMMARY
Added new storage module for PowerMAX and VMAX arrays.  Requires install of Dell EMC PyU4V python module to function available on PyPi and PIP

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
Storage Modules for PowerMAX and VMAX
Provisioning Modules
dellpmax_createsg.py
dellpmax_addvolume.py
dellpmax_create_emptysg.py
dellpmax_addcascadedsg.py
dellpmax_createhostgroup.py
dellpmax_createhost.py
dellpmax_createportgroup.py
dellpmax_createmaskingview.py
dellpmax_expandlun.py

Local Replication Modules

dellpmax_createsnapshot.py
dellpmax_manage_snap.py

Remote Replication Modules

dellpmax_manage_srdf.py

Cleanup Modules

dellpmax_deletehost.py
dellpmax_deletehostgroup.py
dellpmax_deletemaskingview.py
dellpmax_deleteportgroup.py
dellpmax_deletestoragegroup.py

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in tests:

https://app.shippable.com/github/ansible/ansible/runs/93552/1/tests
https://app.shippable.com/github/ansible/ansible/runs/93552/2/tests
https://app.shippable.com/github/ansible/ansible/runs/93552/3/tests

**Comment by rawstorage** [comment]
added __init__.py file and checked requirements for submitting group of modules.  Hopefully have met all requirements

**Comment by mattclay** [comment]
@rawstorage You can easily run the tests locally from your checkout if you have Docker:

```
bin/ansible-test sanity --docker -v lib/ansible/modules/storage/dellemc/
```

**Comment by mattclay** [comment]
CI failure in tests:

https://app.shippable.com/github/ansible/ansible/runs/93936/1/tests
https://app.shippable.com/github/ansible/ansible/runs/93936/2/tests
https://app.shippable.com/github/ansible/ansible/runs/93936/3/tests

**Comment by rawstorage** [comment]
Closing Request, will open fresh one when issues addressed.

**Pull request closed without merging**
