### PR TITLE
Nova compute enhancements

### PR DESCRIPTION
**Pull request by emonty**
There's a bunch of updates here, but most of them center around enhancements to telling Nova to actually provide a working IP address at boot, and on ensuring that one has such a thing on subsequent checks. There are a few things around image and flavor selection by name which make config expression much cleaner to read ("Ubuntu Server 14.04.1 LTS" rather than "169d484a-dde2-44c8-8f15-daaa1ba69e94") In general, this stack should get us to feature parity with the OpenStack provisioning that the OpenStack infra team uses in production so that we can transition to using ansible instead of custom scripts (whee!) It's all in one PR because each of the different features in here touch the same bits, so making independent pull requests that don't conflict was kinda impossible - but I'm happy to split it up if that's better.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Monty,

Can you please split this up into seperate pull requests (i.e. per module where relevant)?

This would make things easier to review on a case by case basis.

Thanks!

**Comment by emonty** [comment]
Sure thing!

**Comment by emonty** [comment]
@mpdehaan Added 5 new pull requests ( #8445 #8446 #8447 #8448 #8449 )  that are _most_ of this split out. There will be some merge conflicts between them, but I can take care of those as they come depending on if and how you want to sequence landing any of these. There are two changes I did not break out because the merge conflicts would be stupendous - I'll make a new patch and rebase those once these badboys are in. #

**Comment by CaptTofu** [comment]
I finally had a minute to try this out on the plane. Wondering what would be the best way for me to sanity check - I reckon each pull request at a time...

**Comment by mpdehaan** [comment]
Ok the deal with this set is that the merge conflicts did get pretty fun, so here's what I'm going to do.

The seperate patches were GREAT for review, and I'm ok with all of them.  I'm going to merge this _together_, this one, and then update the version_added strings for each.

**Pull request merged**
