### PR TITLE
Fix gcp_dns_resource_record_set_facts wrong endpoint

### LINKED ISSUE #70167: gcp_dns_resource_record_set_facts return allways empty list
##### SUMMARY

When trying to retrieve current records on a zone it never returns any value because the if on next line is always false:
https://github.com/ansible/ansible/blob/14bcd3b7a307aa1920292e32a021b66cf43eb977/lib/ansible/modules/cloud/google/gcp_dns_resource_record_set_facts.py#L116

It is caused because the collection function has the wrong endpoint
https://github.com/ansible/ansible/blob/14bcd3b7a307aa1920292e32a021b66cf43eb977/lib/ansible/modules/cloud/google/gcp_dns_resource_record_set_facts.py#L126
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_dns_resource_record_set_facts.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.12
  config file = None
  configured module search path = ['/Users/miquel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible@2.8/2.8.12_1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/opt/ansible@2.8/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### OS / ENVIRONMENT

Tested on Linux and MacOS

##### STEPS TO REPRODUCE

```yaml
---
- name: Update SRV records
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: "get info on a managed zone"
      gcp_dns_managed_zone_facts:
        dns_name: somedoman.internal.
        project: mashmetv
        auth_kind: serviceaccount
        service_account_file: "./credentials.json"
      register: zone
    - debug: var=zone
    - name: Get info on a resource record set
      gcp_dns_resource_record_set_facts:
        #managed_zone: "{{ zone['items'][0] }}"
        managed_zone:
          name: mashme-internal
        project: mashmetv
        auth_kind: serviceaccount
        service_account_file: "./credentials.json"
      register: records
    - debug: var=records
```
##### EXPECTED RESULTS

The expected results is to see the content of records as a list of all the resource record on the zone

##### ACTUAL RESULTS

Only an empty list is returned

```paste below
ok: [localhost] => {
    "records": {
        "changed": false,
        "failed": false,
        "items": []
    }
}
```

### PR DESCRIPTION
**Pull request by wolmi**
##### SUMMARY

Fixes #70167 

##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

gcp_dns_resource_record_set_facts

### CODE REVIEW

**Comment by Akasurde** [comment]
@rambleraptor I am not quite sure about the procedure for backporting the GCP related fixes? Can you please provide some details?

**Comment by mkrizek** [comment]
Note that `2.8` is security and critical bug fixes only: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#release-status

**Review by Akasurde — CHANGES_REQUESTED** [review]
As above

**Comment by wolmi** [comment]
I've added the fragment for the changelog

**Comment by wolmi** [comment]
@Akasurde can your review again?

**Comment by Akasurde** [comment]
@wolmi Like @mkrizek said https://github.com/ansible/ansible/pull/70189#issuecomment-647465038, Ansible-2.8 is accepting only critical and security bugfixes. This does not follow under these categories. So I think we can close this. Thanks.

**Comment by wolmi** [comment]
Thanks for the quick answer, can you develop a little bit more what is the criteria to decide when an issue is critical bug fix? on the link provided explains that "there can sometimes be exceptions for critical issues" but no criteria os process is explained.

**Comment by Akasurde** [comment]
Critical fixes are meant for CVE fixes and fixes where the Ansible core engine itself is not working. In this case, we have the fix for 2.9 and 2.10 release which means updating Ansible version will solve the problem. Also, with the introduction of Ansible collection, you can just install the latest version of the collection to get the issue fixed.

I agree that the docs around this are not that clear. I hope you are satisfied with this explanation.

**Comment by wolmi** [comment]
It's Cristal clear!! 😁

Thanks

**Comment by Akasurde** [comment]
@wolmi, Thanks.

**Pull request closed without merging**
