### PR TITLE
Subversion: Only fire changed when content has changed 

### PR DESCRIPTION
**Pull request by mintsoft**
##### SUMMARY

Previously if you checkout only a branch of part of a subversion repostitory
and another part of the repository is updated then the change handler would
fire even if the branch/subdirectory that we're interested in hasn't changed.

This now parses the output to only indicate that there has been a change when
the actual content is changed.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

Subversion

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
Also tested under
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by mintsoft** [comment]
@dsummersl is there anything particular I can do to get this more attention? It should be ready to go :)

**Comment by dsummersl** [comment]
@mintsoft I was able to test this and confirm that this fixes the issue; thanks! Also verified that `ansible-test` cases are passing now.

shipit

**Comment by mintsoft** [comment]
Hmm is ansibot supposed to have merged the commit in by now @dsummersl  ?

**Comment by dsummersl** [comment]
Hmm, yes. I see a couple things: this PR is labelled with `stale_ci`, and when I mouse over that tag it says "Close and reopen this PR to get it retested". It also is labelled with `core_review` which https://docs.ansible.com/ansible/latest/community/development_process.html#workflow suggests that this PR will have to wait for a core member for the final go ahead - I guess my shipit doesn't count here :(

I'd suggest getting that first `stale_ci` to go away.

**Comment by mintsoft** [comment]
@dsummersl Ahh I see, I'll have to see if I can entice a core team member to have a look. 

Maybe @maxamillion could do me the favour 😉

**Comment by maxamillion** [comment]
rebuild_merge

**Pull request merged**
