### PR TITLE
Added Markdown syntax

### PR DESCRIPTION
**Pull request by tonk**
In the `ansible-doc` program of JP Mens, I added things to generate Markdown syntax.
This is very handy when you have a `Markdoc` wiki, so everything can be done in Python.

I'm just starting to learn Python, so maybe things can be improved. If so, please let me know.

### CODE REVIEW

**Comment by mpdehaan** [comment]
When adding options to the function it is better for future proofing to add a render_type operation with a default of "console" than a boolean that only supports one type.

This keeps us from refactoring it later.  Make that change and we can see about including this.

Thanks!

**Comment by jpmens** [comment]
@tonk I think Michael means something like this:

``` python
def tty_ify(text, render_type="console"):
```

That means someone can invoke `tty_ify()` giving _text_ only.

**Comment by mpdehaan** [comment]
Yes, and there shouldn't be a --markdown flag, but rather something like an --output-type flag, where the default is console.

Really, TBH, I don't see great use in this outputing markdown, but I'll entertain it.

**Comment by tonk** [comment]
Completely reworked the program and now it's a lot easier to add other output types.

Please review (if time permits)

**Pull request closed without merging**
