### PR TITLE
Fix for #24148, plus minor changes

### LINKED ISSUE #24148: Sysctl module fails on OEL5
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sysctl
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Running on: Ubuntu 16.04
Works when remote: OEL6 (python 2.6.6)
Doesn't work when remote: OEL5 (python 2.4.3)

##### SUMMARY

sysctl fails when trying to set a parameter on OEL5.

##### STEPS TO REPRODUCE

```yaml
- hosts: hostname
  tasks:
  - sysctl:
      name: kernel.shmmni
      value: 4096
      state: present
```

##### EXPECTED RESULTS

Parameter should be set.
##### ACTUAL RESULTS

```
fatal: [hostname]: FAILED! =>
{
"changed": false, 
"failed": true, 
"module_stderr": "Shared connection to hostname closed.\r\n",

"module_stdout": "
Traceback (most recent call last):\r\n
  File \"/tmp/ansible_ctF6H0/ansible_module_sysctl.py\", line 397, in ?\r\n
    main()\r\n
  File \"/tmp/ansible_ctF6H0/ansible_module_sysctl.py\", line 391, in main\r\n
    result = SysctlModule(module)\r\n
  File \"/tmp/ansible_ctF6H0/ansible_module_sysctl.py\", line 142, in __init__\r\n
    self.process()\r\n
  File \"/tmp/ansible_ctF6H0/ansible_module_sysctl.py\", line 162, in process\r\n
    self.read_sysctl_file()\r\n
  File \"/tmp/ansible_ctF6H0/ansible_module_sysctl.py\", line 320, in read_sysctl_file\r\n
    if not line or line.startswith((\"#\", \";\")):\r\n
TypeError: expected a character buffer object\r\n
", 

"msg": "MODULE FAILURE",
"rc": 0}
```

### PR DESCRIPTION
**Pull request by xalkina**
##### SUMMARY

Fixes #24148.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

sysctl
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by bcoca** [comment]
Question About This One
=======================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  

Ansible versions >= 2.4 do not support python 2.4 nor 2.5, I created an alternate fix for 2.3 in #24166

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by xalkina** [comment]
Dropping support for python2.4 is one thing, and making everything possible to ensure that python2.4 breaks is another! ;-)

As I can see, your change replicates the fix with a slightly different implementation/syntax, so there's no reason for confrontation.

This also suggests that there's no plan for point releases between 2.3 and 2.4.

**Comment by bcoca** [comment]
@xalkina i did not mean to be confrontational, but we already have changes in module_utils/basic.py that break execution of modules on python2.4/2.5 so any change that enables it on the module itself becomes irrelevant.

I had already written my version of the patch before I saw yours, I considered just applying it but it was against development, which made it harder for me to juggle so I chose what I viewed as the simpler/quicker path. It was not meant as a slight, I'm sorry if that is what it looked like.

2.3.x releases stem from the stable-2.3 branch, this the workflow we've been following since 2.0. We make stable branches for the major release, but not the minor ones.

**Comment by xalkina** [comment]
Didn't know that core functionality of ansible2.4 won't work with python2.4. In that case, of course the fix doesn't bring any value.

Not sure I understood your comment on the 2.3.x though. There's a bug, and there's a fix. It wouldn't be included in a future 2.3.x release, or there won't be any?

**Pull request closed without merging**
