### PR TITLE
Add umask support to git module.

### PR DESCRIPTION
**Pull request by eigood**
As requested in #10279

### CODE REVIEW

**Comment by bcoca** [comment]
this needs rebasing and version added should be at least 2.0

**Comment by amenonsen** [comment]
The change is sensible, but needs to target `source_control/git.py` in the `ansible-modules-core` repository. @eigood any interest in rebasing and resubmitting a PR to that repository? (Also note @bcoca's comment about `version_added` above.)

Meanwhile, this PR should be closed.

**Comment by md5** [comment]
@eigood Any chance your up for submitting a new PR against [`ansible/ansible-modules-core`](https://github.com/ansible/ansible-modules-core) that updates the [`source_control/git.py`](https://github.com/ansible/ansible-modules-core/blob/devel/source_control/git.py) file as @amenonsen suggests and includes the changes requested by @bcoca?

**Comment by amenonsen** [comment]
Closing due to lack of updates and the fact that the change belongs in another repository anyway.

**Comment by md5** [comment]
@amenonsen You'll probably want to close #10279 in that case as well.

**Comment by amenonsen** [comment]
@md5 I don't suppose I could convince you to reopen this PR against ansible-modules-core instead? ;-)

**Comment by md5** [comment]
@amenonsen I've opened https://github.com/ansible/ansible-modules-core/pull/3268

**Pull request closed without merging**
