### PR TITLE
Added support for VPC subnets

### PR DESCRIPTION
**Pull request by jimbydamonk**
Adds support through boto for VPC subnets. 

```
- name: Create ELB    
  local_action:
    module: ec2_elb_lb
    state: present
    name: 'New ELB'
    security_group_ids: 'sg-123456, sg-67890'
    region: us-west-2
    subnets: 'subnet-123456, subnet-67890'
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
```

Or of you have created the through ec2-vpc and register a vpc variable 

```
 - name: Create ELB  
  local_action:
    module: ec2_elb_lb
    state: present
    name: 'New ELB'
    security_group_ids: 'sg-123456, sg-67890'
    region: us-west-2
    subnets: "{{ vpc.subnets | join(',',  attribute='id') }}"       
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
```

### CODE REVIEW

**Comment by jctanner** [comment]
@jimbydamonk can you fix the merge conflicts? I presume they came from the recent module doc fragments.

@willthames can you review this?

**Comment by willthames** [comment]
The commit looks very reasonable to me. Unfortunate timing as really the conflicts come from both #6913 and #6914. 

Rebasing the commit onto devel shouldn't be too much work, it'll only be the call to the ElbManager constructor that will need particular care.

**Comment by jimbydamonk** [comment]
I will take a look at fixing the merge conflicts.

**Comment by jimbydamonk** [comment]
@willthames Merged and tested.

**Comment by mpdehaan** [comment]
All of the merge conflicts above are a problem.

Please use "git pull --rebase" vs "git pull" and "git rebase" vs "git merge" and it will be easier.

Anyway, we can't accept this with merge commits -- it makes things very hard to review and test and messes up source control history.

I highly recommend using a topic branch in git versus a branch named "devel" to avoid this in the future.

I'm going to close this one and will let you resubmit, thanks! 

If you have questions you can also ask on Ansible-devel list.

**Comment by jimbydamonk** [comment]
Yup. I got side tracked with work, but I should have a new pull request tomorrow.

**Comment by juliedavila** [comment]
darn here I was making it as well and you beat me to it. Nice! Can't wait to put it use.

**Pull request closed without merging**
