### PR TITLE
ansible now captures returncode errors on inventory scripts

### LINKED ISSUE #10013: Inventory script errors not checked or exposed
##### Issue Type:

Bug report / Feature idea
##### Ansible Version:

```
% ansible --version
ansible 1.8.2
  configured module search path = None
```
##### Environment:

Running from OS X, against Ubuntu Trusty.
##### Summary:

If using a dynamic inventory script that fails, ansible does not fail how I'd expect, including checking exit status and relaying output (at least stderr).
##### Steps To Reproduce:
1. Have an inventory script that fails (exits non-zero)
2. Use it: `ansible-playbook site.yml -i /path/to/script`
3. See ansible blow up still trying to parse JSON in the output
##### Expected Results:

I would expect ansible to check the script's exit status around [here](https://github.com/ansible/ansible/blob/1b8faa68d99f2f1f373df4ce43e6c2ff71d81257/lib/ansible/inventory/script.py#L45), and ideally relay at least stderr to me.

Example:

```
% ansible-playbook site.yml -i /path/to/script
ERROR: running inventory script /path/to/script failed, stderr below:

Something's not configured
```
##### Actual Results:

```
% ansible-playbook site.yml -i /path/to/script
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-playbook", line 160, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 118, in __init__
    self.parser = InventoryScript(filename=host_list)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/inventory/script.py", line 49, in __init__
    self.groups = self._parse(stderr)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/inventory/script.py", line 57, in _parse
    self.raw  = utils.parse_json(self.data)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/utils/__init__.py", line 551, in parse_json
    results = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

### PR DESCRIPTION
**Pull request by bcoca**
should fix #10013

### CODE REVIEW

**Comment by danp** [comment]
I'm having trouble getting `source ./hacking/env-setup` working but this change looks reasonable.

**Comment by danp** [comment]
When should I expect this to show up in a release?

**Comment by danp** [comment]
Sorry, that was poorly phrased. I'm not sure what the flow is from PR merge -> available in a release. Is that documented somewhere?

**Comment by bcoca** [comment]
this will be included in 1.9

**Comment by danp** [comment]
Thanks!

**Pull request merged**
