### PR TITLE
Riak module.

### PR DESCRIPTION
**Pull request by jsmartin**

### CODE REVIEW

**Comment by jsmartin** [comment]
Sorry for the initial monster pull request.  I've split them up into separate projects.

**Comment by mpdehaan** [comment]
Ok, various things.

Needs an EXAMPLES section, see other modules. 

parameters:
-        riak_config_dir=dict(default="/etc/riak"),
-        riak_http_ip=dict(required=False, default='127.0.0.1'),
-        riak_http_port=dict(required=False, default=8098),
-        ring_ready=dict(default=False, choices=BOOLEANS),
-        target_node=dict(default='riak@127.0.0.1', required=False),
-        wait_for_handoffs=dict(default=False, choices=BOOLEANS),
-        wait_for_service=dict(
-            required=False, default=None, choices=['riak_kv']) 

It should be obvious that it is Riak, so remove any "riak_" prefixes.

**Comment by mpdehaan** [comment]
In DOCUMENTATION, it looks like the 'action' parameter needs a 'choices' attribute.  Also since "action" is also already a keyword in ansible, can we call this something like 'command' ?

Can the http_ip/port be combined to be like

http://192.168.1.20:88 ?

so that there is a default implied port?

ring_ready?  It says it returns true if all modules agree, does this mean it should be modelled as a command choice versus a seperate parameter

**Comment by mpdehaan** [comment]
CHOICES = BOOLEANS is now replaced by "type=bool", BTW.

We need to make this apply to all modules.

**Comment by mpdehaan** [comment]
another question, is ring ready slow or could it be returned every time?

I see sometimes things call "riak admin" and elsewhere it is "riak-admin", is this intended?  Should the module raise an error if riak-admin is not found?

**Comment by mpdehaan** [comment]
Will let you tweak these things and resubmit, feel free to continue to comment on the ticket...

**Comment by jsmartin** [comment]
All very good comments. I've implemented these fixes, will test them out with my ansible-examples stuff and resubmit both in a few days.  Ring_ready doesn't take long to run, so I'll just include it by default.  Thanks!

**Pull request closed without merging**
