### PR TITLE
adding feature to fetch an existing role

### PR DESCRIPTION
**Pull request by patlachance**
##### SUMMARY

I couldn't find an easy way to retrieve the 'role_id' associated to a given AWS IAM role, so I suggest to add a fetch feature to this module.
Example use case where the 'role_id' is required: restrict access to S3 Buckets to specific IAM roles

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

modules/cloud/amazon/iam_role.py

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/a371885/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

Same return as create or update role.

```

```

### CODE REVIEW

**Comment by willthames** [comment]
I wrote iam_role_facts module to solve this problem. https://github.com/ansible/ansible/pull/32874

**Comment by patlachance** [comment]
@willthames thanks for your comment. I tweaked this module last summer but realize over the weekend that I hadn't submitted a PR. I was not aware of your module proposal but could use it if it gets merged.

**Comment by willthames** [comment]
You can also use it prior to merge - just download the module and put it in your library directory alongside your playbooks.

**Comment by ryansb** [comment]
Closing in favor of iam_role_facts

**Pull request closed without merging**
