### PR TITLE
pep8 ec2.py plugin

### PR DESCRIPTION
**Pull request by graingert**
Our codebase requires that all code complies with pep8, to be able to include the ec2.py plugin we had to format it.

It could become increasingly difficult to port changes from ansible to this script back into our codebase if they diverge.

### CODE REVIEW

**Comment by sivel** [comment]
You may want to take a look at https://github.com/ansible/ansible/blob/devel/CODING_GUIDELINES.md 

> There is no need to submit code changes for pep8 and pyflake fixes, as these break attribution history. Project leadership will make these periodically.

**Comment by graingert** [comment]
@sivel This makes a lot of sense for ansible packages, but ec2.py is a plugin that users are expected to copy into their repositories.

**Comment by bcoca** [comment]
closing as per rule discussed above

**Comment by adamchainz** [comment]
I would like `ec2.py` de-linted too - I've copied it into two codebases in my time and had to de-lint it each.

**Pull request closed without merging**
