### PR TITLE
Remove platform dev guides from core docs

### PR DESCRIPTION
**Pull request by samccann**
##### SUMMARY

Core developer guide shouldn't have docs for collection-specific dev guides like vmware etc.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs/docsite/Makefile
docs/docsite/rst/dev_guide/ansible_index.rst
docs/docsite/rst/dev_guide/core_index.rst
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mariolenz** [comment]
The CI fails:

```
01:39 Running sanity test "package-data"
01:39 Run command with data: /root/.ansible/test/venv/sanity.package-data/3.10/d50ea0a1/bin/python /root/ansible/test/sanity/code-smell/package-data.py
01:51 ERROR: Found 1 package-data issue(s) which need to be resolved:
01:51 ERROR: docs/docsite/rst/dev_guide/index.rst:0:0: File was not added to sdist (100%)
01:51 See documentation for help: https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/package-data.html
01:51 FATAL: The 1 sanity test(s) listed below (out of 4) failed. See error output above for details.
01:51 package-data
```

**Comment by mariolenz** [comment]
@felixfontein Is this what you meant with "(some of) the platform guides should be removed from the ansible-core docs"?

**Review by felixfontein — APPROVED** [review]
LGTM

**Comment by mariolenz** [comment]
@samccann Any news on this PR?

**Comment by samccann** [comment]
Verified on test that the guides are removed from ansible-core docs.

**Pull request merged**
