### PR TITLE
porting_guide_2.4 stub entries

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
The majority of the doc was completed in
https://github.com/ansible/ansible/pull/24539 however some items were
not complete so were removed. This PR add the remaining items back in

##### ISSUE TYPE
 - Docs Pull Request

### CODE REVIEW

**Review by dharmabumstead — APPROVED** [review]
Thanks @gundalow!

**Review by dharmabumstead — CHANGES_REQUESTED** [review]
needs copy edit before merge after stubs are finished.

**Review by bcoca — APPROVED** [review]
removed incorrect inventory options .. also new feature, no need for porting, old way still works.

did update deprecation for inventory options and made several notes that developers should look at new features to start migration, most things should work transparently w/o change though.

**Comment by jborean93** [comment]
I've had to add one bit of info around deprecated return values for a Windows module I forgot to do in the first PR.

**Review by dharmabumstead — APPROVED** [review]
Approved with edits.

**Comment by abadger** [comment]
cherrypicked for 2.4.0rc5

**Pull request merged**
