### PR TITLE
Digital Ocean Inventory refactor

### LINKED ISSUE #15752: Add support for DigitalOcean tags to external inventory script
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME
digital ocean dynamic inventory script

##### ANSIBLE VERSION

n/a
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

n/a
##### SUMMARY

Support DigitalOcean's new tags feature in the inventory script with a new CLI option, auto-generated groups, and returned host-specific variables.

n.b.: tags are currently only available as a feature in DO's API, but not in the web control panel.
##### STEPS TO REPRODUCE
- Add `--tags` [CLI option](https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py#L85) to retrieve all tags.
- Add `tag_TAG` [generated group](https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py#L40).
- Add `do_tags` [variable](https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py#L50) when run against a host.
##### EXPECTED RESULTS

`./digital-ocean.py --tags --pretty` should output e.g.

```
{
  "tags": [
    "tag_1",
    "tag_2",
    "tag_3"
  ]
}
```

`do_tags` variable could be e.g. a comma-separated list of tags on that droplet.
##### ACTUAL RESULTS

n/a

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* Remove 'dopy' dependency
* Update documentation
* Incorporate BondAnthony's IP address related code
* Add Tags support

Fixes: #15752

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
contrib/inventory/digital_ocean.py

##### ANSIBLE VERSION
```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @BondAnthony

**Comment by BondAnthony** [comment]
@Akasurde please add PR https://github.com/Akasurde/ansible/pull/2 to this PR.

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
Can someone please review this please ?

**Comment by BondAnthony** [comment]
I've tested this with 2.4 and the inventory script works as expected. No changes to functionality with this update.

This removes the `dopy` dependency which is out of date.

**Comment by BondAnthony** [comment]
shipit

**Comment by andrewsomething** [comment]
Great to see this being refactored to remove dopy. Though I noticed one issue with the new implementation. It doesn't handle paginated responses. By default, the DO API only returns 25 objects per page.

Here's a quick example of how you might deal with the pagination:

```python
if method == 'GET':
    resp_data = {}
    incomplete = True
    while incomplete:
        resp = requests.get(url, data=data, headers=self.headers, timeout=self.timeout)
        json_resp = resp.json()

        for key, value in json_resp.items():
            if isinstance(value, list) and key in resp_data:
                resp_data[key] += value
            else:
                resp_data[key] = value

        try:
            url = json_resp['links']['pages']['next']
        except KeyError:
            incomplete = False
```

You can test this by appending `?per_page=1` to the URL if you don't have more than 25 Droplets. You might want to append `?per_page=200` to all GET requests as that is the max size and will reduce the number of round trips needed.

See: https://developers.digitalocean.com/documentation/v2/#links

**Comment by BondAnthony** [comment]
@andrewsomething thank you for pointing this out. We will make sure this gets included in @Akasurde pull request. Lots of refactoring of the DO modules!

**Comment by Akasurde** [comment]
@andrewsomething @BondAnthony Sorry for delay, was busy with other stuff. Let me know if it is good, I will merge it.

**Pull request merged**
