### PR TITLE
Apply tags conditionally so that the module does not throw up an erro…

### PR DESCRIPTION
**Pull request by brtkwr**
…r when using an older distro of openstacksdk

(cherry picked from commit c517538bd81149f5b507617e5f3385f98ec4642a)

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by emonty** [comment]
shipit

**Comment by gtema** [comment]
shipit

**Comment by abadger** [comment]
2.7.11 is being released on Thursday.  We try to merge all backports on Monday before the release so that other projects, sites, and people have a chance to test the upcoming tree before a release.  This PR was not ready to merge on Monday so it won't go into 2.7.11 unless 2.7.11 is delayed.

2.7.11 is also the last release in the 2.7.x series which will contain non-critical bugfixes.  We don't think this qualifies as a critical bugfix so I will be closing it after the release on Thursday.  If you think this is critical, please take it to a Core Team IRC meeting ( https://github.com/ansible/community/tree/master/meetings ) to have a vote on whether to either slip the 2.7.11 release to get it in or to release a 2.7.12 with this change included.

**Comment by brtknr** [comment]
@abadger Without this change, os_stack will be left broken in 2.7.* series.

**Pull request closed without merging**
