### PR TITLE
os_server - add "tag" to instance nics

### PR DESCRIPTION
**Pull request by MaxBab**
##### SUMMARY
A custom "tag" could be passed to the instance metadata with the nics.
Add support for the "tag" to the module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
os_server

##### ADDITIONAL INFORMATION
Depends-On: https://review.opendev.org/#/c/675306/

### CODE REVIEW

**Review by cloudnull — APPROVED** [review]
shipit

**Comment by MaxBab** [comment]
@cloudnull 
Hi,
Could you take a look at the patch once again, please?
I rebased it.

Thanks.

**Review by cloudnull — APPROVED** [review]
shipit

**Review by odyssey4me — APPROVED** [review]
shipit

**Pull request merged**
