### PR TITLE
Remove deprecation for TRANSFORM_INVALID_GROUP_CHARS

### LINKED ISSUE #61889: group contains deprecated call to be removed in 2.10
##### SUMMARY
group contains call to Display.deprecated or AnsibleModule.deprecate and is scheduled for removal

```
b/ansible/inventory/group.py:54:20: ansible-deprecated-version: Deprecated version ('2.10') found in call to Display.deprecated or AnsibleModule.deprecate
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
```
b/ansible/inventory/group.py
```

##### ANSIBLE VERSION
```
2.10
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes #61889

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

` lib/ansible/inventory/group.py`

### CODE REVIEW

**Review by jamescassell — CHANGES_REQUESTED** [review]
If you fix the group format, doesn't it break the purpose of the tests?

**Comment by mkrizek** [comment]
> If you fix the group format, doesn't it break the purpose of the tests?

I didn't think the purpose of any of the tests this PR changes was to test valid/invalid group formats. I just changed them to be valid to align with the new default.

**Review by bcoca — CHANGES_REQUESTED** [review]
don't merge this, we might end up just removing the deprecation and not changing the default

**Comment by samdoran** [comment]
This was discussed in the IRC meeting today and the vote was to remove the deprecation message but keep the current default. This will still show a warning for invalid characters in group names. Removing that warning can be discussed separately in the future.

We should probably backport the removal of the deprecation warning. Since we will not be changing the default, there is no need to warn about the change in previous versions.

**Review by jamescassell — APPROVED** [review]
shipit

**Review by s-hertel — APPROVED** [review]

**Review by samdoran — APPROVED** [review]

**Review by bcoca — APPROVED** [review]

**Pull request merged**
