### PR TITLE
add timestamp_default to config

### PR DESCRIPTION
**Pull request by jpmens**
Forgive me for doing this now, but then it's over with. :)

### CODE REVIEW

**Comment by jpmens** [comment]
Completes #1195

Example from `~/.ansible.cfg` with an strftime(3) format

```
[defaults]
timestamp_format = %Y-%m-%dT%H:%M:%S
```

**Comment by mpdehaan** [comment]
Not complete until the config file in examples also has the setting in there.

**Comment by mpdehaan** [comment]
Also, the question comes up if there are any other timestamps in the code.  People are going to expect it changes all of them.  This is why I didn't want to take this now, actually.

**Comment by jpmens** [comment]
Only other timestamps I find are in backup_local() in `module_common.py` used for creating backup copies of files.

We could change that to use this timestamp, though I'd replace all white space in the resulting string to dashes for safety.

**Comment by mpdehaan** [comment]
Getting the parameter into module common would be non-trivial.

Another way to do this is to make the format string for $ansible_managed
configurable instead, which I think is easier and then it's more obvious
too.

And people could use this to add their own warnings if they wanted like "DO
NOT EDIT THIS FILE UNDER PAIN OF DEATH!"

**Pull request closed without merging**
