### PR TITLE
New module: tower_notification

### LINKED ISSUE #50511: New module request: tower_notification
##### SUMMARY

Add a module to create Ansible Tower notification templates.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

tower_notification

##### ADDITIONAL INFORMATION

The tower_notification module could be used to automate the configuration of Ansible Tower and AWX via Ansible itself. There are multiple existing modules to do so, however the notification feature in Tower is not covered at the moment.

```yaml
---
- name: Add webhook notification
  tower_notification:
    name: webhook notification
    notification_type: webhook
    url: http://www.example.com/hook
    headers:
      X-Custom-Header: value123
    state: present
    tower_config_file: "~/tower_cli.cfg"

- name: Add Slack notification
  tower_notification:
    name: slack notification
    notification_type: slack
    channels:
      - general
    token: cefda9e2be1f21d11cdd9452f5b7f97fda977f42
    state: present
    tower_config_file: "~/tower_cli.cfg"

- name: Delete notification
  tower_notification:
    name: old notification
    state: absent
    tower_config_file: "~/tower_cli.cfg"
```

### PR DESCRIPTION
**Pull request by samcarpentier**
##### SUMMARY

Adds a module to create Ansible Tower notification templates. Fixes #50511.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

tower_notification

##### ADDITIONAL INFORMATION

```yaml
---
- name: Add webhook notification
  tower_notification:
    name: webhook notification
    notification_type: webhook
    url: http://www.example.com/hook
    headers:
      X-Custom-Header: value123
    state: present
    tower_config_file: "~/tower_cli.cfg"

- name: Add Slack notification
  tower_notification:
    name: slack notification
    notification_type: slack
    channels:
      - general
    token: cefda9e2be1f21d11cdd9452f5b7f97fda977f42
    state: present
    tower_config_file: "~/tower_cli.cfg"

- name: Delete notification
  tower_notification:
    name: old notification
    state: absent
    tower_config_file: "~/tower_cli.cfg"
```

### CODE REVIEW

**Comment by jainnikhil30** [comment]
@samcarpentier 

Could you please add some integration tests for this module ?

**Comment by Moumoutaru** [comment]
Was about to open a PR for this module before I saw this. What all do we need to get this merged in?

**Comment by AlanCoding** [comment]
I think the lack of integration tests are kind of a blocker for now. There are several other open PRs for these modules I think I need to poke the bot to merge at the moment as well.

**Comment by samcarpentier** [comment]
Thank you all for the feedback. I will look into integration tests implementation when I have a few minutes.

When is the deadline to be included in the Ansible 2.8 release?

**Comment by AlanCoding** [comment]
dates are in the roadmap:

https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_8.html

**Comment by samcarpentier** [comment]
@AlanCoding @jainnikhil30

Integration tests have been implemented and are now all passing.

**Comment by AlanCoding** [comment]
shipit

**Comment by AlanCoding** [comment]
new module PRs are not automatically merged by the bot, so these have to wait until someone goes through doing triage, as long as it has the ships.

**Comment by rooftopcellist** [comment]
shipit

**Pull request merged**
