### PR TITLE
[WIP] Add a 'ansible-role' cli

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY
Add a 'ansible-role' cli

This is split off from the https://github.com/ansible/ansible/pull/44983 role arg spec pr.

Apply a role to a host list, similar to 'ansible localhost -m ping'

For example using  test1 role in test/integration/targets/validate_arg_spec
 $ cd test/integration/targets/validate_arg_spec

 # will use the 'default' role arg specs from meta/arg_specs.yml
 $ ansible-role localhost -r test1

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

lib/ansible/cli/role.py

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (ansible_role_ier 31618fb8ea) last updated 2018/09/19 14:26:36 (GMT -400)
  config file = /home/adrian/src/ansible/ansible.cfg
  configured module search path = ['/home/adrian/ansible/my-modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 16:29:00) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

### CODE REVIEW

**Comment by jamescassell** [comment]
Awesome!  Beats having to create a trivial playbook for each role, or a generic playbook like
```yaml
---
- hosts: "{{ ansible_limit }}"
  roles:
  - "{{ role_name }}"
```

**Comment by samccann** [comment]
@jborean93 @alikins is this CLI command still relevant now that we have ansible-galaxy w/ role and collection support? Can we close the PR if its no longer needed?

**Comment by bcoca** [comment]
@samccann actually, `ansible -m include_role -a 'name=rolename' all` would be the equivalent, `ansible-galaxy` was never for execution of roles, just installing and it predates this PR by a long time.

**Comment by Shrews** [comment]
I believe we can close this as there are no plans to implement `ansible-role`. As @bcoca stated above, this can be performed at the CLI level using the adhoc command and `include_role`.

**Pull request closed without merging**
