### PR TITLE
ansible_tower: fix broken import, reuse tower_argument_spec and documentation fragment

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
- Fix [broken import](https://github.com/ansible/community/wiki/Testing%3A-progress-tracker#fixing-broken-imports) in `module_utils/tower.py` and `web_infrastructure/ansible_tower/tower_job_wait.py`
- reuse `tower_argument_spec` and tower documentation fragment
- remove Python 2.6 from requirements

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
tower

##### ANSIBLE VERSION
```
ansible-playbook 2.5.0 (devel c9f2b931db) last updated 2017/09/07 17:22:11 (GMT +200)
```

### CODE REVIEW

**Comment by pilou-** [comment]
Pull request updated (conflict on `skip.txt` resolved)

**Comment by wwitzel3** [comment]
shipit

**Comment by pilou-** [comment]
Pull request updated (conflict on `skip.txt` resolved).

@wwitzel3 : Ansibullbot reset shipit count after a rebase, could you comment using `shipit` again ?

@ghjm (as randomly selected maintainer of `web_infrastructure/ansible_tower` namespace) could you please review this pull request ? At least two `shipit` comments (from maintainers or namespace maintainers or core team members) are required in order to add [shipit](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-shipit) label.

**Comment by wwitzel3** [comment]
shipit

**Comment by matburt** [comment]
shipit

**Comment by pilou-** [comment]
bot_status

**Pull request merged**
