### PR TITLE
RFE: use 'show vlan' instead of 'show vlan brief' in edgeswitch_vlan

### PR DESCRIPTION
**Pull request by larsks**
According to [this discussion][1], the `show vlan` and `show vlan
brief` commands are identical. The advantage to using the `show vlan`
command is that it makes this module compatible with the Netgear M4100
series of switches, which have a cli that is almost but not quite
identical to the EdgeSwitch.

I don't have access to an edgeswitch to test this. Maybe @f-bor could check?

[1]: https://community.ui.com/questions/Difference-between-show-vlan-and-show-vlan-brief/7f9c1734-d304-4027-9e83-3cc3bb061d9a

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

edgeswitch_vlan

### CODE REVIEW

**Review by f-bor — CHANGES_REQUESTED** [review]
For clarity, can you also rename the function parse_vlan_brief ?
Also you have to adapt the tests:
- rename the file test/units/modules/network/edgeswitch/fixtures/edgeswitch_vlan_show_vlan_brief which is used for the command output
- reflect your changes in test/units/modules/network/edgeswitch/test_edgeswitch_vlan.py (check for vlan_brief inside)

**Comment by f-bor** [comment]
> I don't have access to an edgeswitch to test this. Maybe @f-bor could check?

I did the test, you are right, it's exactly the same output.

**Comment by larsks** [comment]
> Also you have to adapt the tests:

Yes, I just wanted to limit the amount of work I was doing until I knew if the modified command was even going to work :). I'll update the tests etc today.

**Comment by f-bor** [comment]
ah sure, I didn't get it :)

**Comment by larsks** [comment]
I'm not 100% positive, but the test failures don't appear to be related to these changes:

>00:01 Shippable run 5e4ea064a038d20006f74d99 has 132 jobs instead of the expected 165 jobs.
>00:01 
>00:01 Try re-running the entire matrix.

**Comment by Akasurde** [comment]
Hi @larsks, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.network<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
