### PR TITLE
Adding defaults_file to mysql_db module

### PR DESCRIPTION
**Pull request by himyouten**
I've added a defaults_file parameter to the mysql_db module to allow loading different my.cnf files.

This allows having various my.cnf for different roles without having to put the user/pass into the book all the time.

E.g.:
mysql_db: name=vmp state=dump target=/tmp/dump.sql defaults_file=~/.my-prod-slave.cnf

The only changes were in the loading of the parameters and not the import, dump, present and absent logic.

Logic was changed to always load the my.cnf (defaults to ~/.my.cnf if defaults_file is not set) and then overriding the settings with those passed in the playbook.  The following my.cnf properties are read, user, password, host, port and socket.

User and password are not required anymore, but defaults to "root" and empty string, respectively.

The functionality of the original was great, we just preferred to use defaults files vs. explicitly setting the user/pass into the playbook.

Cheers
Himmy

### CODE REVIEW

**Comment by Jmainguy** [comment]
Looks to be cool functionality.

**Comment by Jmainguy** [comment]
Lots of mysql_db changes lately, looks like there is a merge conflict now. If you can get those resolved it will help the approval along I am sure.

**Comment by himyouten** [comment]
Glad you think it's cool!  I'll get on it and resolve those conflicts

**Comment by himyouten** [comment]
Resolved the conflicts!

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
