### PR TITLE
gather_facts action plugin: Fix loading network facts modules for smart gathering

### PR DESCRIPTION
**Pull request by trishnaguha**
##### SUMMARY

Fix loading network facts modules for smart gathering.
Currently the connection plugin is loaded but not the network_os which is why the <network_os>_facts module is not invoked.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/action/gather_facts.py

### CODE REVIEW

**Review by bcoca — APPROVED** [review]

**Review by bcoca — CHANGES_REQUESTED** [review]
I would add a changelog since this would need backporting

also some test cases so this does not break in the future

**Comment by ikhan2010** [comment]
@trishnaguha is this ready to merge?

**Comment by abadger** [comment]
As beta1 is being released now, all future merges need to have changelog entries to tell users of pre-releases what has changed since beta1.

This appears to be an approved bugfix which is eligible to be merged before rc1 but it does need to have the changelog added.

**Comment by abadger** [comment]
@bcoca bcoca says he's given a review of this via slack.  So this is now waiting on changes from @trishnaguha

**Comment by trishnaguha** [comment]
The PR now addresses the review.

**Review by bcoca — APPROVED** [review]

**Comment by trishnaguha** [comment]
@abadger Backporting PR https://github.com/ansible/ansible/pull/62413

**Pull request merged**
