### PR TITLE
docs/docsite: fixes broken docs/docsite/rst/cli references

### PR DESCRIPTION
**Pull request by falcon78921**
##### SUMMARY

This PR aims to fix the broken Edit on GitHub links
when referencing Ansible CLI tools.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs/docsite/rst/conf.py
docs/docsite/_themes/sphinx_rtd_theme/breadcrumbs.html

### CODE REVIEW

**Comment by falcon78921** [comment]
ready_for_review

**Comment by acozine** [comment]
Thanks @falcon78921 we're going to discuss this in the docs [Working Group](https://github.com/ansible/community/issues/389#issuecomment-545023576) meeting tomorrow. Hope you can join us!

**Comment by falcon78921** [comment]
Hey @acozine :wave: 

Per the DaWGs meeting, I removed the Edit on GitHub link for Ansible internals (https://meetbot.fedoraproject.org/ansible-docs/2019-10-29/dawgs_aka_docs_working_group.2019-10-29-14.31.html).

When grep searching for `ansible-` in `docs/docsite`, there are two pages in `dev_guide/testing/sanity` that begin with `ansible-`:

~~~
cli/ansible-doc.rst
cli/ansible-config.rst
cli/ansible-playbook.rst
cli/ansible-galaxy.rst
cli/ansible-vault.rst
cli/ansible-inventory.rst
cli/ansible-console.rst
cli/ansible-pull.rst
dev_guide/testing/sanity/ansible-doc.rst
dev_guide/testing/sanity/ansible-var-precedence-check.rst
~~~

If I added `if pagename.startswith('ansible-')` to breadcrumbs, my guess is the Edit on GitHub reference would be stripped from those `dev_guide` pages. For the time being, I kept the `-cli` addition to the Ansible internals. I could change the `dev_guide` pages to have different names, but I figured I would start here and see which direction you would want to go in.

**Comment by acozine** [comment]
@falcon78921 thanks for all your work on this. The trouble with renaming the docs pages for the CLI elements is that we then have to maintain redirects from the old page names to the new page names. Is there an advantage that outweighs the maintenance?

**Comment by falcon78921** [comment]
Thanks @acozine :)

I'll continue to work on this and see if I can get the breadcrumbs match to work better.

**Comment by falcon78921** [comment]
@acozine Ok, so I played around with the `if` in breadcrumbs. I was able to strip the Edit link on the CLI pages. I also verified that the module and other doc pages work. However, I'm running into a problem with the pages in `dev_guide/sanity/testing`. Out of all of the documentation, there are two pages that contain `ansible` in the `pagename`:

~~~
dev_guide/testing/sanity/ansible-doc.rst
dev_guide/testing/sanity/ansible-var-precedence-check.rst
~~~

`ansible-doc` already exists in `cli` for the `ansible-doc` tool, which is being matched to strip the link out. `ansible-var-precedence-check` is also being matched. Just an idea, is it possible to rename those pages to something else and have `ansible-` exclusively for CLI tools? Again, unless I'm missing something here, then those links for editing would be broken. Other than that, I think I have a solution.

**Comment by falcon78921** [comment]
After further testing, I actually think keeping `-cli` for the pages documenting Ansible internals is the better way to go. I tried using `startswith()` in the if statement for `breadcrumbs.html`, however, it doesn't seem to apply (maybe I'm missing something?).

If I do `if 'ansible' in pagename`, it seems too broad. It accomplishes not having to change the names of the `cli` pages, however, there are some pages in `dev_guide/sanity/testing` that would conflict. Also, having `if 'ansible' in pagename` may cause issues down the road when expanding.

I think as the PR stands now, this will remove Edit On GitHub links for `ansible-` CLI pages and eliminate the confusion/404 errors (i.e. For community members that are trying to contribute). I definitely see the value of having Edit on GitHub links in documentation (especially for users who are not familiar with using `git` on the CLI).

**Pull request closed without merging**
