### PR TITLE
Remove hardcoded ansible user for junos_user integration tests

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Remove hardcoded 'ansible' user for testing.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test: junos network-integration

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 6a94633b0a10713d85d02f6ab225ad8a00eb045b

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now ae571887e009988b5242c2c4a4920148775c8036

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 73e0bfcab87793462d474201691f8ba8978ca43e

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 999aa0e9116f564e7fdc6739420d39da0874893f

**Review by ganeshrn — APPROVED** [review]

**Review by Qalthos — APPROVED** [review]

**Pull request merged**
