### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by fangchin**
# Summary

This is a follow-up pull request to [[ansible] Devel (#652)](https://github.com/ansible/ansible/pull/652). Please refer to [this comment](https://github.com/ansible/ansible/pull/652#issuecomment-7184005).
# Details
1. The updated `lib/ansible/inventory/expand_hosts.py` handles all forms discussed in [ansible] Devel (#652)'s comments, especially [this](https://github.com/ansible/ansible/pull/652#issuecomment-7176973).
2. The original built-in test function in 1. was removed and replaced with enhanced `test/simple_hosts` test input and updated `test/TestInventory.py`. The existing Greek and Norse myth themes are maintained 8-)
3. `CHANGELOG.md` updated
4. `ansible.1` **INVENTORY** section updated
5. `examples/hosts` further updated with revised comments
6. `Makefile` updated; `s/make debian/make deb/` - tested. on Ubuntu 11.04 64 bit
7. `make tests` passes
   
   fangchin@zettar1:~/work/zettar/ansible$ make tests
   PYTHONPATH=./lib nosetests -v
   test_complex_exclude (TestInventory.TestInventory) ... ok
   test_complex_vars (TestInventory.TestInventory) ... ok
   test_script (TestInventory.TestInventory) ... ok
   test_script_all (TestInventory.TestInventory) ... ok
   test_script_combined (TestInventory.TestInventory) ... ok
   test_script_norse (TestInventory.TestInventory) ... ok
   test_script_restrict (TestInventory.TestInventory) ... ok
   test_script_vars (TestInventory.TestInventory) ... ok
   test_simple (TestInventory.TestInventory) ... ok
   test_simple_all (TestInventory.TestInventory) ... ok
   test_simple_combined (TestInventory.TestInventory) ... ok
   test_simple_exclude (TestInventory.TestInventory) ... ok
   test_simple_norse (TestInventory.TestInventory) ... ok
   test_simple_port (TestInventory.TestInventory) ... ok
   test_simple_restrict (TestInventory.TestInventory) ... ok
   test_simple_ungrouped (TestInventory.TestInventory) ... ok
   test_simple_vars (TestInventory.TestInventory) ... ok
   test_one (TestPlayBook.TestPlaybook) ... ok
   test_yaml_hosts_list (TestPlayBook.TestPlaybook) ... ok
   test_assemble (TestRunner.TestRunner) ... ok
   test_async (TestRunner.TestRunner) ... ok
   test_command (TestRunner.TestRunner) ... ok
   test_copy (TestRunner.TestRunner) ... ok
   test_facter (TestRunner.TestRunner) ... SKIP
   test_fetch (TestRunner.TestRunner) ... ok
   test_git (TestRunner.TestRunner) ... ok
   test_large_output (TestRunner.TestRunner) ... ok
   test_ping (TestRunner.TestRunner) ... ok
   test_service (TestRunner.TestRunner) ... ok
   test_yum (TestRunner.TestRunner) ... SKIP
   test_parse_kv_basic (TestUtils.TestUtils) ... ok
   test_template_basic (TestUtils.TestUtils) ... ok
   test_template_unicode (TestUtils.TestUtils) ... ok
   test_template_varReplace_iterated (TestUtils.TestUtils) ... ok
   test_template_whitespace (TestUtils.TestUtils) ... ok
   test_varLookup_list (TestUtils.TestUtils) ... ok
   test_varReplace_almost_alternative (TestUtils.TestUtils) ... ok
   test_varReplace_almost_alternative2 (TestUtils.TestUtils) ... ok
   test_varReplace_alternative (TestUtils.TestUtils) ... ok
   test_varReplace_alternative_greed (TestUtils.TestUtils) ... ok
   test_varReplace_caps (TestUtils.TestUtils) ... ok
   test_varReplace_invalid_list (TestUtils.TestUtils) ... ok
   test_varReplace_list (TestUtils.TestUtils) ... ok
   test_varReplace_list_nolist (TestUtils.TestUtils) ... ok
   test_varReplace_list_oob (TestUtils.TestUtils) ... ok
   test_varReplace_middle (TestUtils.TestUtils) ... ok
   test_varReplace_multiple (TestUtils.TestUtils) ... ok
   test_varReplace_nested (TestUtils.TestUtils) ... ok
   test_varReplace_nested_int (TestUtils.TestUtils) ... ok
   test_varReplace_nested_list (TestUtils.TestUtils) ... ok
   test_varReplace_notcomplex (TestUtils.TestUtils) ... ok
   test_varReplace_simple (TestUtils.TestUtils) ... ok
   test_varReplace_unicode (TestUtils.TestUtils) ... ok
   ---
   
   Ran 53 tests in 34.309s
   
   OK (SKIP=2)

Thank you!

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you send me this as a squashed commit?

Just create a new branch off of your existing branch, call it "ranges" or something, and do a "git merge --squash otherbranch"

This makes it easier to review.

Thanks!

**Comment by fangchin** [comment]
Will do soon.

Can you send me this as a squashed commit?

**Comment by fangchin** [comment]
Done. Please review.   I am new to git. So, I did the following:
1. Re-forked your devel branch once more
2. Cloned my "new" ansible repo to a different directory on my local machine
3. Copied all updated/new files to the new local cloned repo
4. Commit these updated/new changes
5. `git push origin`

Will study up `git` soon. Thanks.

**Comment by mpdehaan** [comment]
can you send me a pull request for this?  I do not see one.

**Comment by fangchin** [comment]
Please check.  Thanks.

can you send me a pull request for this?  I do not see one.

**Pull request closed without merging**
