### PR TITLE
Updated nmcli.py for several versions

### PR DESCRIPTION
**Pull request by 110marc**
Errors found/fixed and now working on all tested Red Hat versions:

- 7.0: nmcli too version 0.9.9.1-13.git20140326.4dba720.el7
- 7.6: nmcli tool, version 1.12.0-10.el7_6
- 7.7: nmcli tool, version 1.18.0-5.el7

1. Conversion

__Error__
```
TypeError: argument of type 'int' is not iterable
```

__Fix__

Added line 587
```
from ansible.module_utils._text import to_text
```

Replaced several lines:
```
sed -i 's/cmd.extend(\[key, value\])/cmd.extend(\[key, to_text(value)\])/g' /usr/lib/python2.7/site-packages/ansible/modules/net_tools/nmcli.py
```

2. NMCLI syntax

__Error__
```
Error: invalid <setting>.<property> 'autoconnect'.
```

__Reproduce__

Working/Not Working
```
[root@localhost ~]# nmcli con mod enp0s3 connection.autoconnect yes
[root@localhost ~]# nmcli con mod enp0s3 autoconnect yes
Error: invalid <setting>.<property> 'autoconnect'.
[root@localhost ~]# 
```

__Fix__
```
Added 'connection.autoconnect' to the nmcli.py rather than 'autoconnect'
```

3. NMCLI version and NM-glib package dependency

__Error__
```
The error was: ValueError: Namespace NMClient not available
"msg": "Failed to import the required Python library (NetworkManager glib API)"
```

__Fix__
```
try/except block code lines 566 to 582
```

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by fumiyas** [comment]
I've tried this patch and confirmed my problem (#63291) was gone,
but this patch makes the `type` parameter is required.

Is this an expected change? I'm using Ansible 2.9.1 + 3.7.5.

Task:

```yaml
- nmcli:
    conn_name: "Wired connection 1"
    state: present
    dns4:
      - 127.0.0.1
  become: true
```

Output (YAML):

```
fatal: [dc2]: FAILED! => changed=false
  invocation:
    module_args:
      ageingtime: 300
      arp_interval: null
      arp_ip_target: null
      autoconnect: true
      conn_name: Wired connection 1
      dhcp_client_id: null
      dns4:
      - 127.0.0.1
      dns4_search: null
      dns6: null
      dns6_search: null
      downdelay: null
      egress: null
      flags: null
      forwarddelay: 15
      gw4: null
      gw6: null
      hairpin: true
      hellotime: 2
      ifname: null
      ingress: null
      ip4: null
      ip6: null
      ip_tunnel_dev: null
      ip_tunnel_local: null
      ip_tunnel_remote: null
      mac: null
      master: null
      maxage: 20
      miimon: null
      mode: balance-rr
      mtu: null
      path_cost: 100
      primary: null
      priority: 128
      slavepriority: 32
      state: present
      stp: true
      type: null
      updelay: null
      vlandev: null
      vlanid: null
      vxlan_id: null
      vxlan_local: null
      vxlan_remote: null
  msg: Type of device or network connection is required while performing 'modify' operation. Please specify 'type' as an argument.
```

**Comment by nikaro** [comment]
PR #65726 have been merged so i think this one can be closed.
@Akasurde

**Comment by mkbajzek** [comment]
@nikaro I'm still unable to use the `nmcli` module on Ubuntu 16.04 due to the `"Error: invalid <setting>.<property> 'autoconnect'."` error (regardless of what I set the `autoconnect` field to or whether I omit it entirely).

Locally modifying `lib/ansible/modules/net_tools/nmcli.py` to match the `connection.autoconnect` syntax @110marc used in this branch fixes the problem.

I recognize that #65726 contained a lot of what's in this branch, but would it be possible to also pull in that `connection.autoconnect` change?

**Comment by nikaro** [comment]
I'm not an Ansible maintainer so i can't do anything. But you are probably right. I don't use `nmcli` anymore for the moment so i cannot test.

But if this pull request is to be merged, i think it needs to be rebased on origin/devel and its commits squashed into a signle one.

**Comment by mkbajzek** [comment]
@110marc do you have any suggestions/preference for how to proceed here? I'd obviously rather your code be merged than someone else essentially duplicate the changes.

**Comment by mkbajzek** [comment]
I've raised the `connection.autoconnect` problem as an issue on `ansible-collections/community.general`: [#459](https://github.com/ansible-collections/community.general/issues/459)

**Comment by Akasurde** [comment]
Migrated to https://github.com/ansible-collections/community.general/pull/478

**Comment by Akasurde** [comment]
@110marc Thanks for the contribution.

**Pull request closed without merging**
