### PR TITLE
check if folder already exists before creation

### PR DESCRIPTION
**Pull request by orryun**
##### SUMMARY
Ansible will check if folder exists before creation

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
vcenter_folder

##### ANSIBLE VERSION
2.7

### CODE REVIEW

**Comment by Akasurde** [comment]
@orryun Thanks for the PR. Could you please add integration test for this change here - https://github.com/ansible/ansible/tree/devel/test/integration/targets/vcenter_folder/tasks ?

**Comment by orryun** [comment]
@Akasurde I added a simple test, any other thoughts?

**Review by Akasurde — APPROVED** [review]

**Comment by Akasurde** [comment]
cc @dericcrago @pdellaert Could you please review this ?

**Comment by orryun** [comment]
When PRs usually get merged here?

**Comment by Akasurde** [comment]
@orryun We need to 2 approvals for PR to get merge. You have one and will have to wait for one more. I pinged 2 people who can give you one. Once that is done we can merge it.

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Comment by Akasurde** [comment]
@orryun Thanks for the contribution.

**Pull request merged**
