### PR TITLE
Correct usages of module.warn

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/database/postgresql/postgresql_idx.py

### CODE REVIEW

**Comment by Andersson007** [comment]
Hello, please, fix a typo in the return query value’s description “to be execute.” => “to be executed.” too ;)

**Comment by Akasurde** [comment]
@Andersson007 Could you please take another look ? Thanks.

**Review by Andersson007 — APPROVED** [review]
shipit

**Comment by Andersson007** [comment]
thank you

**Pull request merged**
