### PR TITLE
Added support for iptables module iprange

### PR DESCRIPTION
**Pull request by MonsieurBon**
##### SUMMARY
This PR adds support for iprange and its parameters src-range/dst-range to the iptables module

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
iptables

### CODE REVIEW

**Comment by pazoozooCH** [comment]
+1

**Comment by LinusU** [comment]
ship_it

🚀

**Comment by MonsieurBon** [comment]
@LinusU did you mean to write that without an underscore?

**Comment by LinusU** [comment]
probably not 😬 

shipit

**Comment by MonsieurBon** [comment]
@LinusU awesome, thx!

**Comment by MonsieurBon** [comment]
bot_status

**Comment by sebastiendarocha** [comment]
Great :smile: 

shipit

**Comment by gundalow** [comment]
Merged into `devel` and will be released in Ansible 2.8.
Thank you all!

**Comment by MonsieurBon** [comment]
Cool, thx! Is there already a release date for 2.8?

**Comment by gundalow** [comment]
2.8 dates (subject to change) https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_8.rst

**Pull request merged**
