### PR TITLE
Support for OS X 10.10 DP3.

### PR DESCRIPTION
**Pull request by jbenden**
The attached commit fixes two known problems with Yosemite 10.10 OS X.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Appreciate the additions.

May I ask that you share information about what the known problems were?   (Errors?  Incorrect values?)

Also, what behaviors exist on prior versions with this change.

Thanks for elaboration.

**Comment by jbenden** [comment]
For some reason, the general reading of sysctl -a fails to read the two properties in question under OS X 10.10. They are simply missing from the output. However, directly querying them works as required. This is what the proposed patch changes.

Because the same variables are read under any version of OS X, this change will not break previous versions.

**Comment by ericduran** [comment]
Quick FYI: I just tested the patch on 10.10 & it fixed the issue for me.

**Comment by mpdehaan** [comment]
This now contains a change in the memfree math.  Is this saying memfree was wrong in all previous OS X versions as well or does this change need to be OS specific?

(In general, it's a good idea to keep these kinds of changes on seperate branches and therefore as seperate branch submissions, so one thing doesn't hold up another).

In interest of not having OS X have fact gathering issues, I'm going to merge this regardless.

Thanks!

**Pull request merged**
