### PR TITLE
Fix one more failing test on Python 3

### PR DESCRIPTION
**Pull request by mgedmin**
This required me to add some Python 3 compatibility to
module_utils/basic.py, which makes this PR larger than usual.  I tried
to split it into small, semantically coherent commits for ease of
review.

### CODE REVIEW

**Comment by abadger** [comment]
Thanks @mgedmin !

**Comment by abadger** [comment]
@mgedmin we found out that six is python-2.6 and above so we can't use it here.  I'll work up an alternative for six.string_types in basic.py.  Just wanted to mention it here so that we remember this constraint for other module code.

**Comment by abadger** [comment]
Oops, my bad.  six is being used in the inventory, not in basic.py.  So we're fine.

**Comment by mgedmin** [comment]
I was avoiding six in module_utils/ because it might not be present on the remote host.

**Pull request merged**
