### PR TITLE
[2.9] acme_* modules: bump acme-test-container version

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #62381 to stable-2.9.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
test/lib/ansible_test/_internal/cloud/acme.py

### CODE REVIEW

**Comment by abadger** [comment]
@felixfontein Now that we're shpping ansible-test as a end-user tool we'll need to add changelog fragments for things like this.

**Comment by felixfontein** [comment]
@abadger Good point! I've added a changelog fragment; is `minor_changes` the correct section? I could also use `bugfixes` since almost all changes (at least the ones I am interested in) are fixing bugs in some sense :)

**Comment by abadger** [comment]
@felixfontein I haven't been too picky about which of those two was used in the past.  bugfixes is probably the better one to use for backports in the future.

**Comment by abadger** [comment]
Merged for 2.9.0rc1

**Comment by felixfontein** [comment]
@abadger thanks! I probably would have used `bugfixes` if this wasn't still before 2.9.0 :)

**Pull request merged**
