### PR TITLE
Don't send JOIN and PART commands if channel is not set

### PR DESCRIPTION
**Pull request by rpthms**
##### SUMMARY
Currently, the irc module is sending JOIN and PART commands even if the channel key is not set in the irc module. This causes the module to send JOIN and PART commands to the #None channel. 

    Sep 15 16:09:07 buster znc[37]: [2019-09-15 16:09:07.508726] (rpthms/Freenode) ZNC -> CLI [:*status!znc@znc.in NOTICE rpthms :Welcome to ZNC!]
    Sep 15 16:09:07 buster znc[37]: [2019-09-15 16:09:07.509133] (rpthms/Freenode) CLI -> ZNC [JOIN None]
    Sep 15 16:09:36 buster znc[37]: [2019-09-15 16:09:36.031655] Connecting user/network [rpthms/Freenode]
`
This results in an exception generated by the irc module:

    TASK [znc : IRC module test task] *********************************************************************************************************************************************
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Timeout waiting for IRC JOIN response
    fatal: [buster.local]: FAILED! => {"changed": false, "msg": "unable to send to IRC: Timeout waiting for IRC JOIN response"}

This module can send PRIVMSGs to either a channel or a list of nicks, so sending JOIN and PART doesn't make sense in cases where channel is undefined. The same goes for the TOPIC command, which is used to set a topic for channels.

This patch ensures that the JOIN, PART and TOPIC commands are only sent if the channel is defined.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
irc

### CODE REVIEW

**Comment by jpmens** [comment]
looks good to me, @rpthms, thank you.

shipit

**Comment by rpthms** [comment]
bot_status

**Comment by jpmens** [comment]
shipit

**Comment by gundalow** [comment]
rebuild_merge

**Pull request merged**
