### PR TITLE
Correct repository name to install

### PR DESCRIPTION
**Pull request by sugitk**
##### SUMMARY

The name of repository is not correct to install.

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

On RHEL8, here is the list of ansible repos:

```
# LANG=C subscription-manager repos --list | grep ansible
Repo ID:   ansible-2-for-rhel-8-x86_64-source-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/source/SRPMS
Repo ID:   ansible-2.8-for-rhel-8-x86_64-source-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2.8/source/SRPMS
Repo ID:   ansible-2-for-rhel-8-x86_64-debug-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/debug
Repo ID:   ansible-2-for-rhel-8-x86_64-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/os
Repo ID:   ansible-2.8-for-rhel-8-x86_64-debug-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2.8/debug
Repo ID:   ansible-2.8-for-rhel-8-x86_64-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2.8/os
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@sugitk Thanks for the PR. Could you please refer devel branch before backporting this to Stable-2.8 branch. You can find backporting document [here](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs).

**Comment by Akasurde** [comment]
cc @maxamillion Could you please review this ? Thanks in advance.

**Comment by sugitk** [comment]
@Akasurde Sorry for my bad manner..  Do I have to close this and submit a new PR for the devel branch?

**Comment by Akasurde** [comment]
> @Akasurde Sorry for my bad manner.. Do I have to close this and submit a new PR for the devel branch?

Don't be sorry. I think you can do it in GitHub UI itself - https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request

**Comment by sugitk** [comment]
I will close this ticket out to avoid messed communication

**Pull request closed without merging**
