### PR TITLE
Fix fallout from #70028.

### LINKED ISSUE #72431: ansible-test integration on shippable is no longer reporting any test data
##### SUMMARY
Both in the overview (see f.ex. https://app.shippable.com/github/ansible/ansible/runs/175858/summary/console) nor in the detail view for failed tests (https://app.shippable.com/github/ansible/ansible/runs/175858/82/tests) anything is shown.

This is only the case for ansible-test for `devel` when using the `integration` subcommand. `sanity` and `units` work fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION
devel

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fix fallout from #70028. Fixes #72431.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test

### CODE REVIEW

**Comment by felixfontein** [comment]
Change was suggested by @bcoca, I only converted it to a PR :)

**Review by bcoca — APPROVED** [review]

**Review by mattclay — APPROVED** [review]

**Comment by felixfontein** [comment]
@bcoca @mattclay thanks!

**Pull request merged**
