### PR TITLE
fix ext comparission in inv plugins

### LINKED ISSUE #43162: File name extension encoding issues in python 3 ansible 2.6.1
##### SUMMARY

I was trying to migrate from Ansible 2.4 on Python 2.7 to Ansible 2.6 on Python 3.7. Ansible stopped parsing my `inventory.config` which had a simple `constructed` plugin. Using Ansible 2.6 on Python 2.7 works fine.

From the debugging output:
```
inventory.config did not meet constructed requirements
```

My `inventory.config`, which worked great on Ansible 2.4 looked like:
```
---
plugin: constructed
groups:
  <group name>: <group definition>
  <group name>: <group definition>
  <group name>: <group definition>
```

I dug around in the `constructed.py` and found that it was failing on:
```
ext in ['.config'] + C.YAML_FILENAME_EXTENSIONS
```

I printed `ext`, and got `b'.config'`. If I changed the test to `ext in [b'.config'] + C.YAML_FILENAME_EXTENSIONS`, it worked.

@agaffney said on IRC:
>it's almost certainly byte vs. unicode. I just did a quick test in an interactive py3 interpreter, and was able to reproduce the 'in' keyword not matching for byte vs. unicode

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`constructed` plugin
`/usr/local/lib/python3.7/site-packages/ansible/plugins/inventory/constructed.py`

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = ['/Users/mwraith/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:13:13) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

My `ansible.cfg` has the following inventory plugins:
```
[inventory]
enable_plugins = constructed, host_list, script, yaml, ini
```

##### OS / ENVIRONMENT

macOS High Sierra 10.13.6

##### STEPS TO REPRODUCE

inventory.config:
```yaml
---
plugin: constructed
groups: []
```
playbook:
```yaml
- debug: msg="test"
```

##### EXPECTED RESULTS

I'd expect it to not fail on parsing inventory.config.

##### ACTUAL RESULTS

```
27634 1532372792.39836: Considering b'inventory.config'
 27634 1532372792.39843: Examining possible inventory source: b'/path/to/testinv/inventory.config'
 27634 1532372792.39849: Attempting to use plugin constructed (/usr/local/lib/python3.7/site-packages/ansible/plugins/inventory/constructed.py)
 27634 1532372792.39859: /path/to/testinv/inventory.config did not meet constructed requirements
```

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
fixes #43162

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

inventory
##### ANSIBLE VERSION

```
2.x
```

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]

**Comment by agaffney** [comment]
TIL that `.endswith()` accepts a tuple of strings

**Comment by ghost** [comment]
Reported errors:
*aws_ec2.py*
```Python
# to text is not closing parenthesis
if to_text(path.endswith(('.aws_ec2.yml', '.aws_ec2.yaml')):

if to_text(path).endswith(('.aws_ec2.yml', '.aws_ec2.yaml')):
```

*virtualBox.py*
```Python
# colon at the end of assignation
            valid = super(InventoryModule, self).verify_file(path): 

# I'd put the whole comparison within an if statement instead
    def verify_file(self, path):
        valid = False
        if (
            super(InventoryModule, self).verify_file(path) and
            to_text(path).endswith(('.vbox.yaml', '.vbox.yml'))
        ):
            valid = True
        return valid
```

**Comment by abadger** [comment]
Seeing to_text in so many places makes it feel like this conversion is happening at the wrong level.  It's supposed to be converted to text when it enters the system.  So figure out where path is entering ansible and convert it to text there.

**Comment by abadger** [comment]
Okay, I think what's happening is that you end up using options.inventory before the options are converted into text (IIRC, that was done when options are used as default values for globals.  Someone should probably check whether config manager broke that as well).

**Comment by abadger** [comment]
config manager is safe... I've traced this back further and found that we're converting the command line options into text type in bin/ansible.  So path should be a text type by the time we handle it in constructed.  Are you calling Ansible as an API?  If so, you need to pass text strings in not byte strings (on Python2, text strings would be unicode type.)

**Comment by ghost** [comment]
this is a tough one @abadger (convert it `to_text` only once) `path` is declared in several places for different contexts.
My finding is that the variable to be changed is `source`, in the `parse_souce` method from the `InventoryManager` class and well it can go backwards to the class initialization where it is passed as an argument of type `list`; see: [ansible/inventory/manager.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/manager.py)

I might be wrong, but that's as far as I have tracked this value

**Pull request closed without merging**
