### PR TITLE
quotes removed from become_method

### PR DESCRIPTION
**Pull request by francescor**
just experimented that with quotes it does not work (ansible 1.9.1)

### CODE REVIEW

**Comment by bcoca** [comment]
what does not work? 

the quotes should not affect the method working or not.

**Comment by francescor** [comment]
but it does, at least in my installation (fedora 21 + ansible 1.9.1)

By having the following in  /etc/ansible/ansible.cfg

``` bash
become_method='su'
become_ask_pass=True
```

I get

```
ansible -a 'whoami' example.com
'SU' password: 
example.com | FAILED => Internal Error: this module does not support running commands via 'su'
```

while everything works fine with

```
become_method=su
```

```
$ ansible -a 'whoami' example.com
SU password: 
example.com | success | rc=0 >>
root
```

(note now there are no quotes around SU)

btw: with a playbook I get an error, too: and again only if I use the quote:

```
fatal: [example.com] => Internal Error: this module does not support running commands via 'su'
```

**Comment by bcoca** [comment]
updated config file to remove bad examples

**Comment by abadger** [comment]
@francescor  I've just pushed the following commit to devel: https://github.com/ansible/ansible/commit/5b0b1f8da6d713410037584679ebe99a0ce099f7

That should fix unquote string values that are entered into the config file.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
