### PR TITLE
Renamed the avi_ansible_utils to avi. Fixed the import error and clea…

### PR DESCRIPTION
**Pull request by grastogi23**
…ned up code.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

module_utils.avi_ansible_utils

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Renamed module_utils.avi_ansible_utils back to module_utils.avi. Fixed the import collision for avi.sdk issue by importing absolute_import.

```

```

### CODE REVIEW

**Comment by grastogi23** [comment]
@abadger updated the module name as discussed.

**Comment by mattclay** [comment]
CI failure due to a python 2.4 syntax error:

```
2017-02-28 23:41:51 Compiling ./lib/ansible/module_utils/avi.py ...
2017-02-28 23:41:51 SyntaxError: ('future feature absolute_import is not defined',)
```

If the AVI modules do not support python 2.4 (for example, due to the AVI SDK not supporting 2.4), then you can exclude them from the python 2.4 syntax checks by adding them to this file as part of your PR: https://github.com/ansible/ansible/blob/devel/test/compile/python2.4-skip.txt

**Comment by gundalow** [comment]
CI failure.

Also please rebase and update the AVI modules I've just merged, thanks

**Comment by grastogi23** [comment]
updated all the modules. They should all now be consistent with no CI failures.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Abadger said he was happy with this

**Pull request merged**
