### PR TITLE
Add serf inventory plugin

### PR DESCRIPTION
**Pull request by msabramo**
Add inventory plugin for [Serf](https://serfdom.io/).
Requires [`serfclient` Python module](https://pypi.python.org/pypi/serfclient).

```
$ /Users/marca/dev/git-repos/ansible/plugins/inventory/serf.py --list
{"serf": ["mt1-pyweb01", "mt2-pyweb01", "mt1-pyweb02", "serf", "mt3-pyweb01", "mt4-pyweb01", "mt2-pyweb02", "mt3-pyweb02", "localmonkey", "marca-mac2.local", "mt5-pyweb01"], "_meta": {"hostvars": {"mt5-pyweb01": {"deploy_env": "mt5", "os": "Ubuntu 12.04"}, "mt2-pyweb02": {"deploy_env": "mt2", "os": "Ubuntu 12.04.5 LTS, Precise Pangolin"}, "mt2-pyweb01": {"deploy_env": "mt2", "os": "Ubuntu 10.04"}, "mt3-pyweb02": {"deploy_env": "mt3", "os": "Ubuntu 12.04.5 LTS, Precise Pangolin"}, "mt3-pyweb01": {"deploy_env": "mt3", "os": "Ubuntu 12.04"}, "marca-mac2.local": {"deploy_env": "dev,dev=true"}, "mt4-pyweb01": {"deploy_env": "mt4", "os": "Ubuntu 12.04.5 LTS, Precise Pangolin"}, "serf": {}, "mt1-pyweb01": {"deploy_env": "mt1", "os": "Ubuntu 10.04"}, "mt1-pyweb02": {"deploy_env": "mt1", "os": "Ubuntu 12.04.4 LTS, Precise Pangolin"}, "localmonkey": {"deploy_env": "dev", "os": "Ubuntu 14.04.2 LTS, Trusty Tahr", "dev": "true"}}}}

$ /Users/marca/dev/git-repos/ansible/plugins/inventory/serf.py --host mt5-pyweb01
{"deploy_env": "mt5", "os": "Ubuntu 12.04"}
```

Cc: @sudarkoff

### CODE REVIEW

**Comment by bcoca** [comment]
just curious, how does it know where to go for querying the information (no config?)

**Comment by msabramo** [comment]
Well the way it's written now, it requires the node to already be a member of a Serf cluster. Which means you have Serf (and `serfclient`) installed and you're running the Serf agent and you've joined it other nodes. I believe it talks to the Serf agent at `localhost:7946`.

**Comment by msabramo** [comment]
or maybe it's `localhost:7373`. Not sure.

**Comment by bcoca** [comment]
merging this, i expect that if there are problems (or someone wants this configurable) there will be subsequent PRs to deal with the issue.

**Comment by msabramo** [comment]
Very cool. Thanks for the quick turnaround!

A little context on why this could be useful. I can set up my Ansible playbooks to configure Serf on new and existing nodes and then the nodes get picked up by Serf automatically and I can target them with Ansible without having to add them to inventory files.

So I think Ansible and Serf complement each other nicely.

**Comment by msabramo** [comment]
Ah, `serfclient` talks to `localhost:7373` by default and I've hard-coded that.

One could set up Serf to expose port 7373 to the world (it binds to 127.0.0.1 by default) and then clients could connect to a Serf agent remotely. I think I'll work on another PR to make things configurable.

**Comment by msabramo** [comment]
One easy way to make things configurable is to do it in `serfclient` instead.

E.g.: https://github.com/KushalP/serfclient-py/pull/11 -- Use SERF_RPC_ADDR env var, if set

**Comment by msabramo** [comment]
See https://github.com/ansible/ansible/pull/11294, which makes this configurable via environment variables -- `SERF_RPC_ADDR` and `SERF_RPC_AUTH`

**Pull request merged**
