### PR TITLE
Introduce the 'always_run' task clause.

### PR DESCRIPTION
**Pull request by stoned**
The 'always_run' task clause allows one to execute a task even in
check mode.

While here implement Runner.noop() to check if a runner really
should execute its task, with respect to check mode option and
'always_run' clause.

Also add the optional 'jinja2' argument to check_conditional() :
it allows to give this function a jinja2 expression without exposing
the 'jinja2_compare' implementation mechanism.

### CODE REVIEW

**Comment by stoned** [comment]
Here is my new take on #3522

**Comment by mpdehaan** [comment]
This looks pretty good but the noop function seems to be poorly named because it does something.   Probably should be called "should_run_task" or something like that?

**Comment by bcoca** [comment]
on_check: skip|run|check (default)?

**Comment by stoned** [comment]
Sure I'll rename the noop() method.

**Comment by stoned** [comment]
Would  Runner.check_run() suit you ? Or may be Runner.check_run_p() ?

**Comment by stoned** [comment]
Or even Runner.no_run() ?

**Comment by jimi-c** [comment]
I think Runner.on_check_do_run() is descriptive.

**Comment by stoned** [comment]
yes indeed it is but why not, but I admit what bother me a little is that it would require to replace all instances of 'if self.runner.check' by 'if not self.runner.on_check_do_run()'. So... what about Runner.no_run_on_check() ? :-)

**Comment by jimi-c** [comment]
Thinking about it, I'm fine with that, though going back I see the logic of calling it noop, so maybe noop_on_check() would work and be a little more descriptive than just noop().

**Comment by stoned** [comment]
Ok for noop_on_check(). I'll make another branch and a new PR.
Thanks.

**Comment by stoned** [comment]
Please see updated proposal in PR #3899

**Pull request closed without merging**
