### PR TITLE
Fix various warning on accelerate module, found by pyflakes

### PR DESCRIPTION
**Pull request by mscherer**
Running pyflakes on accelerate module, i stumbled accross various warning. Most of them are harmless ( missing import, too much import ), but in order to reduce the noise, I fixed them. There is however 1 real bug in a code path executed in case of error, so likely almost never exercised.

### CODE REVIEW

**Comment by mscherer** [comment]
I would even propose this patch:

```
diff --git a/library/utilities/accelerate b/library/utilities/accelerate
index 574e99c..de709e0 100644
--- a/library/utilities/accelerate
+++ b/library/utilities/accelerate
@@ -428,6 +428,6 @@ def main():

     daemonize(module, password, port, timeout, minutes)

-# this is magic, see lib/ansible/module_common.py
-#<<INCLUDE_ANSIBLE_MODULE_COMMON>>
+from ansible.module_utils.basic import AnsibleModule # import *
+
 main()
```

but it seems a bit like a hack. Without it, it show this:

```
library/utilities/accelerate:407: undefined name 'AnsibleModule'
```

With the regular import *, pyflakes complain it cannot check for undefined variables.

**Comment by mpdehaan** [comment]
cc @jimi-c for comment

FYI we have a "make pyflakes" target in the Makefile which works like our "make pep8"

**Comment by mpdehaan** [comment]
The snippet import is correctly written as:

```
from ansible.module_utils.basic import *
```

No need for the crazy comment thing.

**Comment by mscherer** [comment]
Yeah, but if I used this snipet, pyflakes complain:

```
 $ pyflakes system/ping    
system/ping:51: 'from ansible.module_utils.basic import *' used; unable to detect undefined names
```

So I wonder if this could be improved before 1.4 .

**Comment by mscherer** [comment]
And make pyflakes do not verify ansible modules, nor submodules ( see https://github.com/ansible/ansible/pull/4782 , I didn't add the ansible modules due to the problem of eithe rmisisng AnsibleModule, or the problem of "unable to detect undefined name" )

**Comment by jctanner** [comment]
@mscherer https://github.com/mscherer/ansible/commit/f8f70989d57eba09968664b9c3826ed77bca32df removes the socket import, which actually breaks the accelerate daemon ...

Nov  6 21:54:52 el6 ansible-accelerate: exception caught, exiting accelerated mode: global name 'socket' is not defined#012Traceback (most recent call last):#012  File "/root/.ansible/tmp/ansible-1383792892.78-53220949674946/accelerate", line 412, in daemonize#012    server = ThreadedTCPV6Server(("::", port), ThreadedTCPRequestHandler, module, password, timeout)#012  File "/root/.ansible/tmp/ansible-1383792892.78-53220949674946/accelerate", line 201, in **init**#012    self.address_family = socket.AF_INET6#012NameError: global name 'socket' is not defined

It seems ok if you re-add "import socket".

**Comment by mscherer** [comment]
@jctanner yeah, it was added after my patch ( c1ed4793 was pushed 3 days ago, my patch date back to 5 days ago ), I will fix and push.

**Comment by jctanner** [comment]
@mscherer thank you!

**Pull request merged**
