### PR TITLE
k8s: Fix .to_dict not needed

### PR DESCRIPTION
**Pull request by jfrabaute**
##### SUMMARY
Fixes small bug in k8s module

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
k8s

##### ADDITIONAL INFORMATION
Trying to deploy a simple ConfigMap with the "k8s" module and "force" set to true should reproduce the error.

### CODE REVIEW

**Comment by willthames** [comment]
There should be a test case for this under test/integration/targets/k8s - could you add one please?

I'm not 100% convinced this is correct in all cases (e.g. when `wait` is not set, `result['result']` will be k8s_obj, which I'd think needs `.to_dict`), but a new test case along with the existing test suite should confirm if more changes are required (it may well be that the test suite doesn't check `force`)

**Comment by jfrabaute** [comment]
> There should be a test case for this under test/integration/targets/k8s - could you add one please?

Yes, I'll work on this. One question.
The README in this folder says:

```
cd test/integration/targets/k8s
./runme.sh -vv
```

But there is no "runme.sh" in this particular folder.
https://github.com/ansible/ansible/tree/devel/test/integration/targets/k8s

> 
> I'm not 100% convinced this is correct in all cases (e.g. when `wait` is not set, `result['result']` will be k8s_obj, which I'd think needs `.to_dict`), 

This is what was happening for me. I don't have "wait" set and it was raising an exception. I checked and "k8s_obj" is a dict when not set.
It is also a dict when set.

> but a new test case along with the existing test suite should confirm if more changes are required (it may well be that the test suite doesn't check `force`)

I'll try to add a test on the existing code to reproduce the problem I was having.

**Comment by willthames** [comment]
Yeah, that's a little out of date (I wrote the original README and then runme.sh got removed by someone else). 

I think 

```
cd test/integration/targets
ansible -m include_role -a name=k8s localhost
```

might do the trick but not 100% sure - I'll take a look later if not.

**Comment by willthames** [comment]
The tests really aren't working very well at the moment, I'm disappointed that the result of the refactor wasn't properly tested.

I'll have a PR up for that shortly which will be a better basis for the tests needed for this PR

**Comment by willthames** [comment]
I had to create https://github.com/ansible/ansible/pull/56163 for ansible_role being broken

In the mean time I've been using the following playbook:

```
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    k8s_openshift: no

  roles:
    - test/integration/targets/k8s
```

**Comment by geerlingguy** [comment]
I believe we may be running into this in some circumstances even when we are not using `force`; we're ending up with an error like:

```
TASK [Update the secret in the namespace] **************************************
task path: /var/jenkins_home/workspace/job-name/src/k8s-update-secret/main.yml:51
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
<127.0.0.1> EXEC /bin/sh -c 'echo ~jenkins && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585 `" && echo ansible-tmp-1558125808.4-215671049649585="` echo /var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585 `" ) && sleep 0'
<127.0.0.1> Attempting python interpreter discovery
<127.0.0.1> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<127.0.0.1> Python interpreter discovery fallback (unsupported Linux distribution: debian)
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /var/jenkins_home/.ansible/tmp/ansible-local-10668DHEDp3/tmpWKS8g0 TO /var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/ /var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/AnsiballZ_k8s.py", line 114, in <module>
    _ansiballz_main()
  File "/var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/AnsiballZ_k8s.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/jenkins_home/.ansible/tmp/ansible-tmp-1558125808.4-215671049649585/AnsiballZ_k8s.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_k8s_payload_UTeKfv/__main__.py", line 258, in <module>
  File "/tmp/ansible_k8s_payload_UTeKfv/__main__.py", line 254, in main
  File "/tmp/ansible_k8s_payload_UTeKfv/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py", line 174, in execute_module
  File "/tmp/ansible_k8s_payload_UTeKfv/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py", line 321, in perform_action
AttributeError: 'dict' object has no attribute 'to_dict'
```

**Comment by willthames** [comment]
@geerlingguy if you're hitting it without `force`, that's a different issue and should be raised as such.

That said, I might have fixed your issue with #56168

**Comment by fabianvf** [comment]
@jfrabaute let me know if you have any difficulties with that test case

**Comment by willthames** [comment]
Rebased and added a changelog fragment so we can backport this to 2.8 - I do have a working test for this but I'll raise that separately so that the backport doesn't need to include the test suite changes

**Comment by willthames** [comment]
Thanks @jfrabaute!

**Comment by jfrabaute** [comment]
Sorry, I haven't taken the time to work on the test after sending the PR.
Thank you for the help and merging it!

**Pull request merged**
