### PR TITLE
Create methods for regex validation for MACs address, IPv4s addresses…

### LINKED ISSUE #80551: Allow for validate_argument_spec advanced data validation
### Summary

validate_argument_spec is a great approach, but it is quite limiting in mostly being focused on defining variable type checks.

It would be nice to apply Jinja2 filters against the variables you are validating to verify variable logic.  Like using the regex filter or ipaddr filter.

If not you could also create fields to allow for regex validation and new types focused on network variable types like MACs address, IPv4s addresses, IPv6 addresses, IPv4 prefixes, and IPv6 prefixes.

### Issue Type

Feature Idea

### Component Name

validate_argument_spec

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by tachyontec**
…, IPv6 addresses, IPv4 prefixes, and IPv6 prefixes.

##### SUMMARY

Add the method for regex validation, so ip addresses and mac addresses can be verified with regex patterns.

Fixes #80551 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

validate_argument_spec.py

##### ADDITIONAL INFORMATION

*this methods are not called by any other function, but they are ready to be implemented.

Each of the methods returns True if they pass the check and False if not.

```paste below

```

### CODE REVIEW

**Comment by bcoca** [comment]
wouldn't these be more useful as test plugins? then assert/fail additions become easy.

**Comment by nitzmahone** [comment]
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.
Our reasons for this are:

   * we're thinking a deeper integration with test plugins would make more sense, and for these specific types, regexes aren't the best solution (instead using things like `ipaddress.IPv6Address` that are well-tested and proven for all the weird corner cases).

However, we're absolutely always up for discussion.
Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If you or anyone else has any further questions, please let us know by using any of the communication methods listed in the page below:

   * https://docs.ansible.com/ansible/latest/community/communication.html

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by tachyontec** [comment]
Hello and thank you for your feedback.

I tried to open a discussion here on the issue: https://github.com/ansible/ansible/issues/80551 ,but received no answer. I have also sent message to the community channel at matrix.org, with no answer there as well. Is there any better way to reach someone that can give some feedback?

I really appreciate the time you took to write this, and i can use ipadress filters instead, but i don't understand how this should be implemented as a test plugin.
Could you please give me some more info on how to implement a test plugin here?
Which is the proper directory that i should ass this test plujgin ?

**Comment by felixfontein** [comment]
Test plugins for these things already exist in [ansible.utils](https://galaxy.ansible.com/ansible/utils).

**Pull request closed without merging**
