### PR TITLE
New module: cnos_interface

### PR DESCRIPTION
**Pull request by dkasberg**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

cnos_interface module

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
Please update the title

**Comment by bcoca** [comment]
also, remove merge commit

**Comment by dkasberg** [comment]
I don't know how to remove a merge commit since I'm relatively new to GitHub.   Search indicates that should do the following:

git revert -m parent-number <commit> 

However I'm not sure what the parameters should be.  Would this be correct?

git revert -m c16a4a7    0dbae08

Thanks in advance for your help!

**Comment by dkasberg** [comment]
Any suggestions to my previous comment on how to remove a merge commit?

**Comment by mattclay** [comment]
Tests for `cnos` modules should go into `test/integration/roles/` instead of `test/integration/targets/`, since we're not able to run them as part of CI or through `ansible-test` as-is. Previously, the suggestion was to create an empty `aliases` file for tests in `test/integration/targets/`, but this is no longer recommended. In the future, if a virtual appliance, such as an AWS AMI image, becomes available, we can revisit the possibility of running `cnos` module tests via `ansible-test`.

needs_revision

**Comment by mattclay** [comment]
@dkasberg Have you tried the [rebase instructions](http://docs.ansible.com/ansible/dev_guide/developing_rebasing.html)? That should remove merge commits.

**Comment by dkasberg** [comment]
rebased.

**Review by gundalow — APPROVED** [review]

**Pull request merged**
