### PR TITLE
made inventory consistent in config file, deprecated old config hostfile

### PR DESCRIPTION
**Pull request by bcoca**
should bring naming consistency as per #10104

### CODE REVIEW

**Comment by tyll** [comment]
This beaks overriding the inventory with ANSIBLE_HOSTS, becaus it introduces ANSIBLE_INVENTORY. ANSIBLE_INVENTORY is also not added to the documentation, only ANSIBLE_HOSTS.

**Comment by bcoca** [comment]
ANSIBLE_HOSTS should still work to override the hostfile entry, but made note to update docs with ANSIBLE_INVENTORY

**Comment by tyll** [comment]
ANSIBLE_HOSTS does not work if there is a "inventory" section in the config file. This seems to be silently addressed by you for the v2 branch in commit cdefeb6d84499d86bf6fef8352b06d626c1bf4ae - this will make ANSIBLE_INVENTORY not work if there is a "hosts" section in the config file, which might cause less trouble.

**Comment by bcoca** [comment]
I thought that was case in both trees, v2 is about to be merged in so leaving it as is

**Pull request merged**
