### PR TITLE
Fix typo in azure_rm_subnet

### PR DESCRIPTION
**Pull request by sylr**
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>

##### SUMMARY
Fix typo

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
Azure

### CODE REVIEW

**Comment by yuwzho** [comment]
shipit

**Comment by zikalino** [comment]
bot_status

**Comment by zikalino** [comment]
shipit

**Comment by zikalino** [comment]
bot_status

**Comment by Akasurde** [comment]
@sylr Thanks for submitting this patch.

**Comment by zikalino** [comment]
@Akasurde do you know what's the reason that this commit was not merged automatically?
I am just trying to figure this out. according to ansibull documentation, after **shipit**, prs like this should be merged automatically

**Comment by Akasurde** [comment]
I am not sure. @jctanner will have some insights about this.

**Pull request merged**
