### PR TITLE
[stable-2.8] Update default test container to use Python 3.8.0b2 (#58877)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Backport of #58877 for Ansible 2.8

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`test/runner/completion/docker.txt`

### CODE REVIEW

**Comment by samdoran** [comment]
I believe we need to backport #55862 in order to address these test failures.

**Comment by mattclay** [comment]
@abadger What do you think about backporting #55862?

If we don't want to do that we can simply add the necessary ignores to this PR instead.

**Comment by abadger** [comment]
I've asked jborean to confirm there's no features in #55862 and that it is okay with him to backport.  I'm okay with it being backported if he signs off on those two things.

**Comment by abadger** [comment]
Update: @jborean93  says he'd rather that does not get backported.  So we should add the necessary ignores to this PR instead.

**Comment by abadger** [comment]
Merged for the 2.8.3 release.

**Pull request merged**
