### PR TITLE
Add pre_tasks and post_tasks for roles.

### PR DESCRIPTION
**Pull request by benosman**
This is something i've wanted for a while; the ability to have pre_tasks and post_tasks for each role.

My primary use case is apt (or yum) sources, to avoid unnecessarily calling apt-get update many times.

The idea would be that in the pre_tasks of a role, all the keys and repos would be set - if there are changes then apt-update is run once, otherwise it is not run. This would help me in re-running the playbook periodically for configuration updates with out the delay each time.

I tried to keep the changes as simple and as consistent as possible with that is already there, even though this area of code could probably do with some refactoring to reduce duplication.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hmm, this could be interesting for having a role like "monitoring_window_wrapped" or "load_balanced".

I like the idea.

**Comment by zellski** [comment]
@mpdehaan - does this feature still have the blessing of the powers that be, do you think? If someone (possibly even me) fixed the pull request from Apr 17 2014, would it be merged?

I'm forced to move away from using roles as often as I'd like, because I have to jump through so many ugly hoops to do setup before meta/main.yml dependencies are evaluated.

**Comment by akkie** [comment]
I would also be interested in this feature :+1:

**Comment by amenonsen** [comment]
I notice that devel has pre_tasks and post_tasks, documented in docsite/rst/guide_rolling_upgrade.rst:

```
The ``pre_tasks`` keyword just lets you list tasks to run before the roles are called.
```

I can't quite tell if that's the same thing that this PR intends (though I think it is), because there's no documentation at all included in the PR. Anyway, the code in devel is significantly different from the code at the time the PR was created, it's not just a matter of resolving a merge conflict. But I think v2 already does what was intended.

I think this PR should be closed now.

**Comment by gregdek** [comment]
Seems like v2 solves this, and even if it doesn't, a major rewrite of this patch would now be necessary in any case.

@benosman thanks for the PR, but we're closing now. If you think v2 doesn't solve your case here, happy to have you submit a new PR.

**Pull request closed without merging**
