### PR TITLE
Clean up unused imports for nxos related code

### PR DESCRIPTION
**Pull request by pabelanger**
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Review by danielmellado — APPROVED** [review]
Thanks for the cleanup, Paul, let's wait for Zuul to complete before merging this

**Comment by pabelanger** [comment]
@danielmellado sadly, zuul won't report back, as we don't test nxos here

**Comment by danielmellado** [comment]
01:51 E           AttributeError: <module 'ansible.modules.network.nxos.nxos_evpn_vni' from '/root/ansible/lib/ansible/modules/network/nxos/nxos_evpn_vni.py'> does not have the attribute 'run_commands' Seems like you might've removed a few required imports.

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now fff2e5dabb624a6495e31b53343d4f457741b751

**Review by trishnaguha — APPROVED** [review]

**Pull request merged**
