### PR TITLE
Fix var naming

### PR DESCRIPTION
**Pull request by stroebitzer**
+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by jamescassell — CHANGES_REQUESTED** [review]
The original version may have been incorrect, but the new version is certainly incorrect. Perhaps you meant `address.address`?

**Comment by acozine** [comment]
@stroebitzer thanks for taking the time to open a PR on the Ansible documentation! 

I'm not sure what problem you're trying to solve in this PR, though. Can you post more information? What problem did you see with the existing example? Can you post before-and-after playbook output?

If you're interested in documentation, feel free to join our chat group on the #ansible-docs channel on freenode IRC.

**Comment by stroebitzer** [comment]
The playbook simply did not work in my environment. The variable "address" got regitstered in a previous step and used afterwards via "instance.address".

After changing the usage to "address" everything worked for me.

**Comment by acozine** [comment]
I see the earlier task that registers `address` as a variable. I'd like to see this change tested before we merge it, and I do not have a GCE account to test it on. @rambleraptor or @erjohnso could you test out this revision?

**Comment by rambleraptor** [comment]
Hello! Yeah, I'll test this out and get an answer for you today.

**Comment by rambleraptor** [comment]
Yeah, this doesn't work for the same reasons that @acozine described. `instance.address` as placed in the guide isn't correct either. It should be `address.address` as @jamescassell said.

**Comment by acozine** [comment]
@rambleraptor thanks for the review - can you take a second look with the additional commit?

**Review by jamescassell — APPROVED** [review]

**Comment by rambleraptor** [comment]
Looks good!

**Comment by acozine** [comment]
Thanks everybody!

**Pull request merged**
