### PR TITLE
📝 Add a GitHub-specific security policy note

### PR DESCRIPTION
**Pull request by webknjaz**
It'll show up at https://github.com/ansible/ansible/security/policy and will help us guide users to the proper docs page.

##### SUMMARY

N/A

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

N/A

##### ADDITIONAL INFORMATION

The default template GitHub suggests for this file looks like:
```markdown
# Security Policy

## Supported Versions

Ansible applies security fixes according to the 3-versions-back support
policy. Please find more information in [our docs](
https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#release-status)
Use this section to tell people about which versions of your project are
currently being supported with security updates.

| Version | Supported          |
| ------- | ------------------ |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :x:                |
| 4.0.x   | :white_check_mark: |
| < 4.0   | :x:                |

## Reporting a Vulnerability

Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.
```

### CODE REVIEW

**Comment by abadger** [comment]
Pushing people to the existing documentation with as little project specific documentation as possible here seems better.  That way we don't have to update multiple spots if our policies or email addresses change.

Probably a docs team decision as to whether and what we would want to do with this.

**Comment by webknjaz** [comment]
@abadger I've updated it as per @acozine's feedback.

**Review by acozine — APPROVED** [review]
Looks good. Short and sweet.

**Comment by webknjaz** [comment]
Here's how it looks like now: https://github.com/ansible/ansible/security/policy

**Pull request merged**
