### PR TITLE
Fix for changing method only on specified interface

### PR DESCRIPTION
**Pull request by obourdon**
##### SUMMARY
Properly fix the interface method change code so that only specified interface gets its method
changed, not all of them

Test added for interface method change

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
interfaces_file

##### ANSIBLE VERSION
```
ansible 2.6.0 (work 10cc45a2fb) last updated 2018/04/19 14:56:13 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible/lib/ansible
  executable location = /home/vagrant/ansible/bin/ansible
  python version = 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0]
```

##### ADDITIONAL INFORMATION
Before:

```
# The loopback network interface
auto lo eth0
iface lo inet manual

# The primary network interface
iface eth0 inet manual
```

After:

```
# The loopback network interface
auto lo eth0
iface lo inet loopback

# The primary network interface
iface eth0 inet manual
```

### CODE REVIEW

**Comment by obourdon** [comment]
@hryamzik hopefully you required tests which enlighted the fact that there was a huge bug in the fix :-(. Many thanks again and will try not to forget about tests next times. Deeply sorry.

**Comment by hryamzik** [comment]
LGTM

Thanks @obourdon!

**Comment by obourdon** [comment]
@ansibot could this be merged please ?

**Comment by obourdon** [comment]
@gundalow any way to get this merged, not sure I should use the @ansibot alias :-(

**Comment by obourdon** [comment]
@ansibot @gundalow any way to get this integrated please ?

**Comment by gundalow** [comment]
rebuild_merge

**Pull request merged**
