### PR TITLE
Implement 'ignore_changed' which allows one to ignore the changed state ...

### PR DESCRIPTION
**Pull request by stoned**
...of tasks.

### CODE REVIEW

**Comment by andrew-d** [comment]
@stoned - Thanks for this PR!  I was just looking for something that did this (on the [list](https://groups.google.com/forum/#!topic/ansible-project/U6QkqTD7S20)).

**Comment by dagolden** [comment]
I'd like to see this applied.  I have some custom fact gathering modules and and it would be nice for them not to show up as changed when they run.

**Comment by srgvg** [comment]
+1 

The people from the League of Idempotence, striving for `changed: false` approve this

**Comment by dagwieers** [comment]
+1 for this PR, not sure of **ignored_changed: yes** is the best way to do it, why not **changed: no**.

Avoiding negative variable/option names is a best practice.

http://truelogic.org/wordpress/2009/02/27/how-not-to-name-a-boolean-variable/
http://www.makinggoodsoftware.com/2009/05/04/71-tips-for-naming-variables/

@dagolden facts modules should never indicate they changed something. Fix your custom facts modules ! Let me know if you need help with this.

**Comment by giulianob** [comment]
Would be great if you could do something like

```
- action: command ufw add proto tcp from any to any port 8080
  changed: result.stdout.find('Skipping') != 1
```

**Comment by mpdehaan** [comment]
perhaps a "changed_when", yes.  I like the idea.

I think it would probably require usage with "register" as we don't want to save /all/ command results.

**Comment by dagwieers** [comment]
@giulianob That's a great idea ! Especially if one can still do **changed: yes** or **changed: no** at the same time.

I guess a **failed: result.rc > 3** would be as useful, as some tool indicate a different return code for different levels of success.

``` yaml
 - action: command hpsum /various /weird /options /i /cannot /recall /from /memory
   register: hpsum
   changed: hpsum.rc != 3
   failed: hpsum.rc > 128
```

**Comment by stoned** [comment]
I can give a try at this in the next 12h

**Comment by giulianob** [comment]
@dagwieers  That looks great! Did @mpdehaan prefer "changed" or "changed_when" ?

@stoned Thanks for your work, I know I will use the hell out of this feature to keep my playbooks fully idempotent.

**Comment by stoned** [comment]
I pushed and sent a PR for an implementation of 'changed_when', see #3524

**Comment by mpdehaan** [comment]
Yep, I am thinking we merge changed_when instead of this, as per above, since it's more generic, and you could still do:

changed_when: False

Though that's not quite "gramatically" correct, it's one less operator.

always_run is of course a good idea also.

**Pull request closed without merging**
