### PR TITLE
Refactor E-Series Hosts module to use module_utils

### PR DESCRIPTION
**Pull request by lmprice**
Refactor the NetApp E-Series module to utilize the common module_utils
and doc_fragments.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
netapp_e_host

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/lorenp/ansible/lib/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
This patch is intended to bring the NetApp E-Series modules more in line with the other NetApp modules and with the updated best practices by utilizing doc_fragments and module_utils for common code. This patch is not intended to change any existing functionality or output.

This patch is a simplification of my original PR (#20764); I was asked to split it into one PR per module.

### CODE REVIEW

**Comment by hulquest** [comment]
Thank you for the contribution.  LGTM
shipit

**Comment by hulquest** [comment]
Adding a second shipit to move the process along.

**Comment by gundalow** [comment]
Rebase needed

**Comment by calfonso** [comment]
@lmprice We would like you to mention that you're re-licensing as we require BSD license for module_utils. We'll need you to check with any other contributors and if there are any, have them comment in the PR that they approve of the license change.

**Comment by lmprice** [comment]
@timuster @hulquest Can you give me a shipit here?

**Comment by hulquest** [comment]
LGTM
shipit

**Pull request merged**
