### PR TITLE
docs: Update Python 2 doc links

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Update links from Python 2 to Python 3

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/basic.py
lib/ansible/modules/assemble.py
lib/ansible/modules/replace.py
lib/ansible/plugins/lookup/pipe.py

### CODE REVIEW

**Comment by samccann** [comment]
Hmm.. I need to think about this one a bit. I feel like we can replace all of these with intersphinx links. I don't know that it will save us from having to update to python4 at some distant ansible future, but it's cleaner. Do these have to be tied to python3.8 specifically, or do they just need to be python3?

**Comment by Akasurde** [comment]
> Hmm.. I need to think about this one a bit. I feel like we can replace all of these with intersphinx links. I don't know that it will save us from having to update to python4 at some distant ansible future, but it's cleaner. Do these have to be tied to python3.8 specifically, or do they just need to be python3?

There are few links, I am not sure efforts required for intersphinx links. Find and replace is faster IMO.

We can switch to `/3/` instead of `/3.8/` and let Python doc website handle redirection.

**Comment by Akasurde** [comment]
@samccann Can you please point me to an example where intersphinx is done? May be worth try.

**Review by acozine — COMMENTED** [review]
+1 for using `/3/` so we don't have to update for dot releases. I added a couple of commits to the branch - updating the `/3.8/` instances to `/3/` and adding a separate link to the 2.6 documentation in the section on formatting strings to work with 2.6 AND 3.x.

**Review by lmalivert — APPROVED** [review]
LGTM 👍🏽

**Comment by lmalivert** [comment]
Change looks good @acozine

**Comment by Akasurde** [comment]
@samccann @lmalivert @acozine Thanks for the review and merge.

**Comment by lmalivert** [comment]
You're welcome @Akasurde!

**Pull request merged**
