### PR TITLE
update docker library module to allow private repository pulls

### PR DESCRIPTION
**Pull request by pixie79**

### CODE REVIEW

**Comment by trevorbernard** [comment]
@jimi-c Is there a time frame on when this will be merged?

**Comment by jimi-c** [comment]
@trevorbernard since 1.7 has been released, we're going to be looking to merge more things in soon, so we'll try and get this is in sooner rather than later.

**Comment by jimi-c** [comment]
# Revision Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We'd like to see a few things tweaked if you don't mind.  If you can help resolve these items, we'd greatly appreciate it:
- There is no documentation for the new parameter. When you add this, please be sure to also set the `version_added` field for the new parameter to `1.8`.
- The registry parameter does not seem to have a default value, so what happens if it is not set? It would seem to be an error currently, as the registry url would be malformed. 
- It would also seem that it would be a good idea to just let the user specify the entire registry url, as currently both the transport (https) and registry version (v1) are assumed, which may not be the case for all users or at some point in the future.
- Some other commit has caused a conflict with this, so rebasing it would help us get it tested and merged more quickly.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by jimi-c** [comment]
# Merged

Hi!

This has been merged inSince I did modify the code as specified above, github is not detecting the merge correctly, so I have closed this manually.

This will be included in the next major release. 

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request closed without merging**
