### PR TITLE
Use separators to remove trailing space added to lines end with comma

### PR DESCRIPTION
**Pull request by cuongnv23**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/parsing/utils/jsonify.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 61e6e7868c) last updated 2017/01/21 09:04:05 (GMT +700)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Rework of https://github.com/ansible/ansible/pull/20536

### CODE REVIEW

**Comment by cuongnv23** [comment]
@bcoca can you help to land this? thanks!

**Comment by bcoca** [comment]
you still have not specified what problem this solves? what breaks with the extra space?

**Comment by bcoca** [comment]
also i was not against the new test, just the removal of the old one

**Comment by cuongnv23** [comment]
@bcoca The extra spaces are unnecessary, with a large number of target hosts, it may increase total file size a lot. We should remove these spaces to make output clean.

**Comment by bcoca** [comment]
if that is what you worry about, why have indent? that creates MANY more white spaces than the trailing ,

**Comment by bcoca** [comment]
I'm going to pass on this as the format option already allows for condensed JSON when size is an issue, when using formatting you are already choosing readability over size.

**Pull request closed without merging**
