### PR TITLE
Reformat code: examples consistently

### PR DESCRIPTION
**Pull request by jpmens**
- added terse syntax to modules.rst
  - added description of special variables to template module

### CODE REVIEW

**Comment by jpmens** [comment]
Fixes #1394

**Comment by mpdehaan** [comment]
Outstanding, thanks!

**Comment by jpmens** [comment]
I'll admit that this looks a bit funny to me as well in the code examples, but I'm impartial: if @mpdehaan and you want this changed, I'll revert back to the `action` syntax.

**Comment by mpdehaan** [comment]
@mpdehaan does not.

remember local_action is just an alias for delegate_to.

**Pull request merged**
