### PR TITLE
Feature Request: Support skeleton directory (useradd -k) in user module

### PR DESCRIPTION
**Pull request by 0x46616c6b**
When I create a system account for a Apache virtual host it would be nice to create this user with a special skeleton. 

For example:

```
- name: ensure vhost users are present
  user:
    name: {{ item['user'] }}
    home: /var/www/{{ item['host'] }}
    skeleton: /etc/wwwskel
    password: {{ item['password'] }}
    shell: {{ item['shell'] }}
  with_items: vhosts
```

Otherwise I need 4 actions to create /var/www/{{ item['host'] }}/{conf,logs,php-fcgi,www}

### CODE REVIEW

**Comment by jacobweber** [comment]
This would be very useful for me too...hope it gets included.

**Comment by jpospychala** [comment]
any chance to get it merged?

**Comment by mpdehaan** [comment]
This is a P4 ticket.  Currently we are working P2 tickets.  It's in queue.

**Comment by 0x46616c6b** [comment]
Closed because wrong branch used in the PR. New PR #7960

**Pull request closed without merging**
