### PR TITLE
expanding command module to handle rc_{ok,changed,failed}

### PR DESCRIPTION
**Pull request by fdavis**
Hello, this is a PR for the rc modifications to the command module.

I'm currently stuck on is_succesful from lib/ansible/runner/return_data.py
Is it possible to get it the list of non-failing rc's.

Will I need to add the rc logic to runner so it can parse what is successful from module_args?

```
def is_successful(self, rc_ok = [0]):
    return self.comm_ok and (self.result.get('failed', False) == False) and (self.result.get('rc',0) in rc_ok)
```

I started a gist of my testing [here](https://gist.github.com/fdavis/4751195).

### CODE REVIEW

**Comment by mpdehaan** [comment]
I would consider overriding is_successful for the command module by making a subclass.

**Comment by dhozac** [comment]
I'd be tempted to just remove the rc check from is_successful. I'm not sure if anything still relies on that, but it really seems like a decision that should be up to the module, not enforced by central code. Using fail_json or setting failed=True doesn't seem like a lot of extra work for someone writing a module.

**Comment by mpdehaan** [comment]
Not removing it from the code, but just passing check_rc=False is fine.

I don't approve of removing it.

**Comment by dhozac** [comment]
That is in ReturnData, i.e. the thing processing the resulting JSON in ansible(-playbook), not in the module. Modules themselves should decide whether or not rc=0 is success or failure or whatever. As-is, that is not possible.

**Comment by mpdehaan** [comment]
Hmm, ok, I was thinking we were talking abut module common.

Yes, I agree the command module should be where the failed=True/False logic
is for that, totally, and only the failed boolean should matter.

+1

**Comment by dhozac** [comment]
Aside from that, I think rc_ok and rc_failed should be mutually exclusive, and the presence of one should imply the values for the other, assuming rc_changed is already handled. This is currently missing documentation for all the options, and implementation of anything but rc_changed.

**Comment by mpdehaan** [comment]
Yes, and AnsibleModuleCommon already has power tools for mutally exclusive
and such.

As for "currently missing documentation" of what is mutually exclusive,
it's left up to the user to explain in English rather than auto-generated.
Fine w/ keeping it that way.

**Comment by fdavis** [comment]
Hello, 

I set this up so that the current default behaviour is maintained. (If no rc's are specified)
By that I mean an (rc == 0) implies successful change, and (rc != 0) implies failed change.

I have one outstanding issue, and that is with the tests.
I get:

```
Traceback (most recent call last):
  File "/home/fdavis/ansible/test/TestRunner.py", line 132, in test_command
    assert 'failed' not in result
AssertionError: 
    {u'stdout': u'', u'changed': True, u'end': u'2013-02-11 20:46:06.688897', u'start': u'2013-02-11 20:46:06.648099', u'cmd': [u'false'], u'rc': 1, u'failed': True, u'stderr': u'', u'delta': u'0:00:00.040798', 'invocation': {'module_name': 'command', 'module_args': 'false'}} = self._run('command', [ "false" ])
    assert {u'stdout': u'', u'changed': True, u'end': u'2013-02-11 20:46:06.688897', u'start': u'2013-02-11 20:46:06.648099', u'cmd': [u'false'], u'rc': 1, u'failed': True, u'stderr': u'', u'delta': u'0:00:00.040798', 'invocation': {'module_name': 'command', 'module_args': 'false'}}['rc'] == 1
>>  assert 'failed' not in {u'stdout': u'', u'changed': True, u'end': u'2013-02-11 20:46:06.688897', u'start': u'2013-02-11 20:46:06.648099', u'cmd': [u'false'], u'rc': 1, u'failed': True, u'stderr': u'', u'delta': u'0:00:00.040798', 'invocation': {'module_name': 'command', 'module_args': 'false'}}
```

So I updated the test, because I believe we are changing that behaviour?
Such that failed should be in the result of a failed command.

By the way, I updated the [previous gist](https://gist.github.com/fdavis/4751195) to reflect my testing.

**Comment by dhozac** [comment]
The ReturnData hunk should just be removing the rc check altogether. It will never be called with check_rc=True.

Documentation should specify the list is comma-separated. While this is common for other modules too, specifying it doesn't hurt.

rc_ok/failed/changed should be initialized into params in _load_params, not scattered throughout.

The entire exit_json call shouldn't be duplicated just to set one thing. In this case, you may either have a variable for module.exit_json or module.fail_json, or do what other modules typically do and use module.exit_json(**result), where result is a dict with all the values.

Indeed, changing the test case is correct. After this, failed should be set when a command fails.

**Comment by fdavis** [comment]
Okay, I misunderstood on the ReturnData.

My problem with setting rc_ok/failed/changed = None in _load_params, was that the mutual exclusive check is triggered.  The current _check_mutually_exclusive counts any terms in params even if they are initialised to None.

Can I change count_terms?:  

```
def _count_terms(self, check):
    count = 0
    for term in check:
-      if term in self.params:
+      if term in self.params and self.params[term] is not None:
           count += 1
    return count
```

**Comment by mpdehaan** [comment]
Sounds like this one is in a weird state regarding code.   Let me knock this one out sometime, if that's ok..

Shouldn't be very involved...

**Comment by fdavis** [comment]
Go ahead.  Closing.

**Pull request closed without merging**
