### PR TITLE
Fix module loading in multi-threading environments

### LINKED ISSUE #13822: Document that Ansible API is not thread-safe
When ansible loads a module from disk for a plugin, it first checks
to see if the module has already been loaded (i.e., exists in
sys.modules), and if it does, it returns that reference rather than
loading the module again (which, as described in issue #13110, must
not happen because repeating the module load may re-initialize
module global variables).    

When a module is loaded, the reference is immediately added to  
sys.modules, even before the module initialization is complete. 
Therefore, if two threads race the module loading code, the first
will begin loading the module from disk, and the second will see  
the module in sys.modules.  It might begin using that module before
it is even fully loaded, resulting in AttributeErrors on objects 
which should be defined in the module.

This can be reproduced by wrapping the Python API example at http://docs.ansible.com/ansible/developing_api.html in a function and then adding the following:

``` python
import threading
t1 = threading.Thread(target=test)
t1.start()
t2 = threading.Thread(target=test)
t2.start()
t1.join()
t2.join()
```

This results in the this traceback:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "test.py", line 13, in test
>     variable_manager = VariableManager()
>   File "lib/ansible/vars/__init**.py", line 92, in **init**
>     self._fact_cache = FactCache()
>   File "lib/ansible/plugins/cache/__init__.py", line 35, in **init**
>     self._plugin = cache_loader.get(C.CACHE_PLUGIN)
>   File "lib/ansible/plugins/__init__.py", line 335, in get
>     obj = getattr(self._module_cache[path], self.class_name)(_args, *_kwargs)
> AttributeError: 'module' object has no attribute 'CacheModule'

The problem can be corrected by wrapping module loading in a mutex.

### PR DESCRIPTION
**Pull request by jeblair**
When ansible loads a module from disk for a plugin, it first checks
to see if the module has already been loaded (i.e., exists in
sys.modules), and if it does, it returns that reference rather than
loading the module again (which, as described in issue #13110, must
not happen because repeating the module load may re-initialize
module global variables).

When a module is loaded, the reference is immediately added to
sys.modules, even before the module initialization is complete.
Therefore, if two threads race the module loading code, the first
will begin loading the module from disk, and the second will see
the module in sys.modules.  It might begin using that module before
it is even fully loaded, resulting in AttributeErrors on objects
which should be defined in the module.

This change wraps the method which checks for existence in
sys.modules and loads modules from disk in a global mutex so that
more than one module is never loaded from disk at a time.

Fixes #13822

### CODE REVIEW

**Comment by jimi-c** [comment]
Ansible's API has never been advertised as being thread-safe, as we use the multiprocessing library (which does everything in forks). This patch may fix the module loading issue, however I'm sure there are many other places in the code which may harbor similar race conditions. As such, I'm not particularly opposed to this patch, however I am against trying to make the entire API thread safe.

**Comment by bcoca** [comment]
-1, adding threading and locking code we do not use adds complexity, performance degradation and possible pitfalls for no gain

**Comment by emonty** [comment]
@jimi-c @bcoca would you accept a patch to the documentation then that says "the python API is known to not be thread safe?" I think that might have prevented confusion in this case.

**Comment by jimi-c** [comment]
@emonty absolutely.

**Comment by bcoca** [comment]
done 2374abbeda465c0aded55fabc18085a1530c9377

**Pull request closed without merging**
