### PR TITLE
AWS route53 module

### PR DESCRIPTION
**Pull request by bpennypacker**
Here's a basic Amazon route53 module.  It lets you create, query, and delete individual DNS records.

### CODE REVIEW

**Comment by jpmens** [comment]
Glanced at it; looks nice.

A few nits:
1. Module's name (in DOCUMENTATION) says 'rds', but it's called 'route53' according to examples.
2. The GET example registers "rec", but the following DELETE example uses "r".
3. Maybe add an example with AAAA, showing how quoting of colons is necessary?

**Comment by bpennypacker** [comment]
Thanks for the comments JP.  I've fixed the typos.  As far as #3 goes, what's the right way to quote things due to the colons?  I've never encountered the issue before and despite the notes I've found on it I've been unable to write a task that successfully adds an AAAA record. From what I've read on the Google group it looks like it should be what I have below, but it throws errors:

action: 'route53 command=create zone=foo.net record=foobar.foo.net type=AAAA value="::1"'

**Comment by jpmens** [comment]
See what I mean? If you can't, how will others? :-D

It ought to work by quoting the whole command, i.e.

action: "route53 command=create zone=foo.net record=foobar.foo.net type=AAAA value=::1"

**Comment by mpdehaan** [comment]
@lwade would you like to help review this also?

**Comment by lwade** [comment]
Took this for a spin (created and delete some NS, A and AAAA records) and it works well.  @bpennypacker ++ :)

**Comment by mpdehaan** [comment]
merged, thank you!

**Pull request merged**
