### PR TITLE
Fix bugs in ec2 library module

### PR DESCRIPTION
**Pull request by gavares**
Corrects an issue with specifying group_name vs group_id when using VPC instances (see commit message)

Include private IP/DNS info in json value returned from ec2 module.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks.... @lwade, care to give this a quick review when you get a chance?

**Comment by dhozac** [comment]
You should use git pull --rebase or git rebase in your topic branches.

The mutually exclusive arguments should use the common handling for that from module_common. Just set mutually_exclusive in the AnsibleModule call.

As I recall, lwade said that group_ids doesn't work for the non-VPC case. Have you tested that?

**Comment by mpdehaan** [comment]
re: what Daniel said above, if you grep for "mutually_exclusive" in the library/ directory you will see some examples of how that works as a parameter to the AnsibleModule class.    Basically it's a built-in facility for argument checking so you don't have to write custom code for it, and all the error messages end up uniform.

**Comment by gavares** [comment]
No problem. Did rebase originally but was worried that it would cause a conflict so went for the merge. I'll undo the merge and make the mutex changes and resubmit.

**Comment by lwade** [comment]
Hey folks.

Thanks for looking at this Grant.  Couple of things from me here:
- I'll have to test again to refresh my memory but I believe security_group_ids parameter in boto run_instances only works for VPC, not for EC2.  So with the method we use, security_groups is EC2 and security_group_ids is for VPC.  We should probably differentiate better in the module parameters.
- Using the group_id _only_ would break compatibility with Eucalyptus private clouds, unfortunately. A run_instances call requires the group name at the moment.

I'm more in favour of adding another parameter (VPC group ID, to complement VPC subnet ID) and going down the route of having the mutex combos to sanity check the parameters still, so that a VPC group ID and group_id or group_name cannot be set aswell. 

Thoughts?

**Comment by gavares** [comment]
Good points. I also like the idea of adding another param (vpc_group_id) and mutex combos.  I'll try and get those changes in this evening and test them against EC2. I don't have any Eucalyptus clouds to test against so I'll leave that up to you (or anyone else who cares to test).

**Comment by gavares** [comment]
With the latest push, I think I covered the changed mentioned by @lwade 

One addition with this push is addition of the "region" parameter as an alternative to the ec2_url parameter as seen in the boto interface and the cloudformation module interface.

Someone should probably verify that I got the version number correct in the two newly documented params.

**Comment by mpdehaan** [comment]
Hey Grant, unrelated question for you...

Can you drop me a line at michael DOT dehaan AT gmail?

Thanks!

**Comment by lwade** [comment]
This looks good for inclusion.  I'll test in the background. Thanks Grant! :)

**Comment by dhozac** [comment]
This looks like it should use the `**kwargs` notation to only have one run_instances call, so future updates won't forget to handle both cases. Something like:

```
if vpc_subnet_id is not None:
    extra_args = dict(security_group_ids=[vpc_group_id], subnet_id=vpc_subnet_id)
else:
    extra_args = dict(security_groups=[group_name])
res = ec2.run_instances(..., **extra_args)
```

should do the trick.

**Comment by mpdehaan** [comment]
@lwade any chance to test?

**Comment by lwade** [comment]
Testing now as sanity check.

**Comment by lwade** [comment]
All good here :) Booooosh, merge it @mpdehaan!

**Comment by mpdehaan** [comment]
in queue!   Looks like it doesn't apply cleanly which isn't a big deal.   

Can you "git rebase" @gavares ?

Thanks!

**Comment by mpdehaan** [comment]
This looks like it still needs to be rebased.

I am closing this one and open to resubmissions.

**Pull request closed without merging**
