### PR TITLE
moved README.md to README.rst, normalizes on rst and auto uploads description to pipy

### PR DESCRIPTION
**Pull request by StephenWeber**
Set a default long_description based on the first few lines of README.md

Added a script that will convert README.md into ReStructured Text for
PyPI, send project metadata to PyPI, and delete the temporary file.

Code based on
https://coderwall.com/p/qawuyq/use-markdown-readme-s-in-python-modules

Addresses #13234 when script applied to project by core dev with access to the PyPI account.

### CODE REVIEW

**Comment by StephenWeber** [comment]
Alternatively, this script could be folded into setup.py at the risk that it could cause problems / unnecessary dependencies. The script could also live elsewhere (such as in ./hacking)

**Comment by sivel** [comment]
I think I would prefer just converting the README.md to README.rst permanently and dropping the md file.  That would solve a few problems and make this easier in the process.

**Comment by bcoca** [comment]
would rst appear readable in github?

**Comment by bcoca** [comment]
duh! docsite/rst/ ... seems to work well enough, I'm happy to have 1 less format to deal with

**Comment by StephenWeber** [comment]
Converting the MD to RST permanently would also be acceptable, and I can do that instead if that's the desire.

**Comment by bcoca** [comment]
quick straw poll in core team, with over 50% votes in, its unanimous for unifying formats on RST.

**Comment by gundalow** [comment]
Rebase needed
Also it's been agreed we should use these headings http://openalea.gforge.inria.fr/doc/openalea/doc/_build/html/source/sphinx/rest_syntax.html#headings

**Comment by StephenWeber** [comment]
Gods I've made a mess.

**Pull request closed without merging**
