### PR TITLE
New module: Add a module to handle postgresql table space (database/postgresql/postgresql_tablespace)

### PR DESCRIPTION
**Pull request by Dorn-**
##### SUMMARY

Atm, you have no possibility to handle seriously the postgresql tablespace with ansible.
Add a new module to handle the tablespace into postgresql. You can add / modify or delete a schema for a specific user. This module is really close from the actual postgresql modules.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
modules/database/postgresql/postgresql_tablespace

##### ANSIBLE VERSION

```
ansible 2.4.0 (postgresql_tablespace 2ccb8ca1a3) last updated 2017/04/14 11:48:35 (GMT +200)

```
#### EXAMPLE

```
- name: Creates tablespace
  become: true
  become_user: postgres
  postgresql_tablespace:
    name: "tbs_fizzbuz"
    owner: "foo"
    location: /app/pgsql/tablespaces/tbs_fizzbuz
    state: present

TASK: [role-postgres-9 | Creates tablespace] ********************************** 
<localhost> REMOTE_MODULE postgresql_tablespace location=/app/pgsql/tablespaces/tbs_fizzbuz name=tbs_fizzbuz state=present owner=foo
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-tmp-1458314354.31-23394801009585 && chmod a+rx /tmp/ansible-tmp-1458314354.31-23394801009585 && echo /tmp/ansible-tmp-1458314354.31-23394801009585']
<localhost> PUT /tmp/tmpnG81an TO /tmp/ansible-tmp-1458314354.31-23394801009585/postgresql_tablespace
<localhost> EXEC ['/bin/sh', '-c', u'chmod a+r /tmp/ansible-tmp-1458314354.31-23394801009585/postgresql_tablespace']
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=phsbtqykenfcjxabibzzmegogykyxpeb] password: " -u postgres /bin/sh -c '"'"'echo BECOME-SUCCESS-phsbtqykenfcjxabibzzmegogykyxpeb; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1458314354.31-23394801009585/postgresql_tablespace'"'"''
<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /tmp/ansible-tmp-1458314354.31-23394801009585/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "tablespace": "tbs_fizzbuz"}
```

### CODE REVIEW

**Comment by PierreRochard** [comment]
@Dorn- It may be beneficial to use the pgutils function to factor out common arguments as we see in the postgresql_db module: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/postgresql/postgresql_db.py#L213

`import ansible.module_utils.postgres as pgutils`
`argument_spec = pgutils.postgres_common_argument_spec()`

postgresql_db is the only module that currently does this, I'm wondering if it would be well received if I started refactoring the other pg modules to do so. I'm open to ideas/advice

**Comment by Dorn-** [comment]
Hello @PierreRochard,
Seems a good idea to me, I'll update this PR asap.
There should be my old module to handle schema to update too :)

Kind regards

**Comment by nerzhul** [comment]
can you fix version to 2.5 as 2.4 merge window was missed ?

**Comment by gboucherie** [comment]
In which version do you think this module will be released ?
Thanks

**Comment by Dorn-** [comment]
Maybe one day ...

**Comment by maxamillion** [comment]
Apologies for the lag time on this, if you are still interested in contributing the module please update the `version_added` field to `2.8` and add integration tests. I think the code looks good and I'm happy to merge once that is done. Thank you for the pull request!

**Comment by Andersson007** [comment]
Hi, @Dorn- This is really good PR. Maybe you find some time and complete it (also see my notes in https://github.com/ansible/ansible/pull/50568). In any case, thanks for your participation.

**Comment by maxamillion** [comment]
waiting_on_contributor

**Comment by dagwieers** [comment]
We have another contributed module with the same name: https://github.com/ansible/ansible/pull/50568

**Comment by Andersson007** [comment]
duplicate of https://github.com/ansible/ansible/pull/52914

@gundalow , close this PR, please

**Pull request closed without merging**
