### PR TITLE
Change hacking scripts to python3 syntax

### PR DESCRIPTION
**Pull request by qwazerty**
Improve compatibility with python3.

### CODE REVIEW

**Comment by bcoca** [comment]
You are updating many files you should not in this request, including documentation and module shared code that MUST be 2.4 compatible and your changes break.

**Comment by qwazerty** [comment]
Well that was indeed too much changes at once. Though the `except ... as ...` syntax would work on python2.4.

I've reduce the scope of the PR.

**Comment by abadger** [comment]
`except [...] as [...]` does not work on python2.4.  That was introduced in python-2.6.

@bcoca: I've reviewed this.  as long as hacking/module_formatter.py can move compatibility up to python-2.6, this is good to merge.

**Comment by qwazerty** [comment]
If this is not fine for `hacking/module_formatter.py` I'll remove it from this PR.

**Comment by bcoca** [comment]
Well, the first thing is that I want to remove all those print statements and port it to use display class, so this change will be irrelevant then. Outside of contrib/ everything should be using the display class.

But since I don't know when I'll get around to that ... I don't oppose merging this in it's current state.

**Comment by abadger** [comment]
Thanks @bcoca and @qwazerty !

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
