### PR TITLE
user module, fix user home dir creation (bug from #71952)

### PR DESCRIPTION
**Pull request by rpluem-vf**
##### SUMMARY

#71952 introduced a regression that causes the users home directory and its contents (if there is a skeleton directory) to be owned by `root:root` if the home directory is freshly created. Furthermore the mail spool file was not created if the user already existed, but the mail spool file did not or if `luseradd` was used.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
user

##### ADDITIONAL INFORMATION
From https://github.com/ansible/ansible/pull/71952#issuecomment-842154069:

Before this change, if I did `user: name=foo home=/foo`, then `/foo` would get created and owned by `foo (since useradd would chown it appropriately). After this change, it is owned by root``.

### CODE REVIEW

**Comment by rpluem-vf** [comment]
I decided to put this back in draft as I reread the hint from relrod and I currently do not really understand why the already existing tests did not detect this issue. I thought I understood, but this was wrong. I want to be sure I understand this.

**Comment by rpluem-vf** [comment]
Some comments:

1. I am happy to squash the commits if needed and helpful as there has been quite some back and forth especially as I wanted to get the tests correct first and fail for the correct reasons.
2. I am currently unclear with regards to creating the mail spool file. The behaviour is now consistent and respects the settings for `useradd` in `/etc/default/useradd` / follows the behaviour of `luseradd`, but it could be also decided that the mail spool file should be always created if `create_home` is `yes`.

**Comment by rpluem-vf** [comment]
> Some comments:
> 
> 1. I am happy to squash the commits if needed and helpful as there has been quite some back and forth especially as I wanted to get the tests correct first and fail for the correct reasons.
> 2. I am currently unclear with regards to creating the mail spool file. The behaviour is now consistent and respects the settings for `useradd` in `/etc/default/useradd` / follows the behaviour of `luseradd`, but it could be also decided that the mail spool file should be always created if `create_home` is `yes`.

@samdoran : I guess the PR is not in focus because of the `needs_revision` / `needs_rebase` tags it has, but I have questions for getting this resolved. Hence the nudge via a mention.

**Comment by samdoran** [comment]
> I guess the PR is not in focus because of the needs_revision / needs_rebase tags it has, but I have questions for getting this resolved.

I have started reviewing this several times, but it's _a lot_ of changes and I have not been able to get through it successfully without being drawn away into other things.

The bot flags PRs with more than 50 commits. It's not an issue since we squash before merging.

Is there any way to make this a simpler and more targeted fix? If not, we will probably need to revert #71952.

**Comment by rpluem-vf** [comment]
Thanks Sam. I will have a look after my vacation.

**Comment by rpluem-vf** [comment]
@samdoran : Sorry for not finding time, hence I understand the revert. Once I find time I will try to create a new PR which
1. Contains the changes from #71952
2. The changes from #74731
and all this in a form that is digestable for review.

**Comment by samdoran** [comment]
@rpluem-vf It's no problem at all. Life happens. 😄

**Pull request closed without merging**
