### PR TITLE
Schema validation for argument_spec

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Schema validation for argument_spec

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
test/sanity/validate-modules

##### ANSIBLE VERSION

```paste below
2.8
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sivel** [comment]
bot_skip

**Comment by sivel** [comment]
I haven't added any ignores yet so that the results can be seen.

I believe everything this has caught is legitimate.

The `dict_keys` for `choices` should be fixed. We cannot guarantee that it will always work going forward, and we need to ensure they are cast to a list.

https://app.shippable.com/github/ansible/ansible/runs/89443/1/tests

**Review by mattclay — APPROVED** [review]

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
@sivel I've rebased your PR (and squashed the commits to make it simpler), and updated ignore.txt: https://github.com/ansible/ansible/compare/devel...felixfontein:arg-spec-schema
Should I force-push it to your branch, or create a new PR?

**Comment by tremble** [comment]
Please be careful when merging the change, we've been cleaning up a little already and some of the ignore.txt entries aren't needed any more...

**Comment by sivel** [comment]
@felixfontein please create a new PR.

**Comment by felixfontein** [comment]
The new PR is #65747.

**Pull request closed without merging**
