### PR TITLE
added deployment configuration to ecs_service

### LINKED ISSUE #2434: Batch mode for delegate_to and local_action (take 2)
I'll try this again.  I had suggested a feature in #2389 which was closed
before I think anyone even understood what the suggestion was.  I tried to
clarify what I meant, but it seems like comments to a closed issue go to
/dev/null.  

We have roughly 1200 servers which are currently configured with cfengine.
Cfengine is good for determining what to do based on dynamic data, but I have
wanted to find something that can handle group complexity better without
becoming unwieldy or be a resource hog.  Obviously, I'm toying around
with ansible, and trying to get it to wrap around a lot of existing stuff.

I have several times wished that delegate_to had an option to do batch
processing instead of firing off for each host in the loop and killing the
delegate server.  A batch job is supposedly possible by working around the problem as
described here:
http://jpmens.net/2012/11/03/an-action-plugin-for-ansible-to-handle-ssh-host-keys/

That solution seems less than obvious.  As a newbie working through this, the
most intuitive thing I could see would be a "batch=yes" option or something
similar, which would cause delegate_to to run once, and just send the entire
list of hosts ansible is going to loop over.  

Anyway, just a suggestion! :)

### PR DESCRIPTION
**Pull request by simplesteph**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ecs_service
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added deployment_configuration as an optional configuration parameter for the ecs_service module, which allows to set minimumHealthyPercent and maximumPercent in both create and update functions. It doesn't do anything beyond using the existing parameters for boto3. It checks for existence of parameters and raises an exception is the arguments are not named correctly

this fixes #2434

### CODE REVIEW

**Comment by simplesteph** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3135

**Comment by simplesteph** [comment]
cc @gregdek see https://github.com/ansible/ansible-modules-extras/pull/3135#issuecomment-266586190

**Comment by simplesteph** [comment]
ready_for_review

**Comment by simplesteph** [comment]
I'll put the ship it flag in two days should I don't receive any additional feedback! Let me know if any additional feedback @zacblazic @rmorlok

**Comment by simplesteph** [comment]
shipit

**Comment by simplesteph** [comment]
@gregdek I'm not sure if the bot is active on this PR?

**Comment by kkarimi** [comment]
@simplesteph maybe it's worth rebasing and pinging the bot again? this is a very useful PR..

**Comment by simplesteph** [comment]
Closing in favour of https://github.com/ansible/ansible/pull/19911

**Pull request closed without merging**
