### PR TITLE
New Module: gitlab_deploy_key and related tests

### PR DESCRIPTION
**Pull request by marwatk**
##### SUMMARY
Adds module gitlab_deploy_key for manipulating Gitlab deploy keys

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
gitlab_deploy_key

##### ANSIBLE VERSION

```
ansible 2.6.0 (gitlab-deploy-keys 20d50e915f) last updated 2018/05/14 18:23:21 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mwatkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mwatkins/git/ansible/lib/ansible
  executable location = /home/mwatkins/git/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### ADDITIONAL INFORMATION
This module:
* uses the Gitlab v4 web API directly
* includes unit tests for adding, updating and deleting both modified and unmodified elements
* is completely self-contained other than base-ansible dependencies
* passes unit tests on all supported python versions

I have [another PR](https://github.com/ansible/ansible/pull/40096) for also dealing with Gitlab Hooks that is very similar to this module.

### CODE REVIEW

**Comment by marwatk** [comment]
This module is very similar to my [gitlab_hooks module PR](https://github.com/ansible/ansible/pull/40096)

**Comment by maxamillion** [comment]
Thank you for the pull request! This looks good (+1 for tests). Similar request as for the `gitlab_hooks` module, would you mind adding support for check mode? 

Also, just a comment on long term maintainability, you might consider refactoring the common methods out into a module_util for `gitlab` that you utilize in both your modules.

**Comment by marwatk** [comment]
TIL about check_mode :) Will add. 

On the refactoring I wasn't sure with the conflict in #39991 if only one of these would make it, so I left the util methods in both just in case (I hated having the duplicate code, though). While I'm in there adding check_mode I'll refactor both to use a common util.

**Comment by maxamillion** [comment]
@marwatk if they both use the same util lib unmodified, it should merge cleanly.

*should* being the operative word :)

**Comment by marwatk** [comment]
@maxamillion Ok, both updated with identical common libs. I sacrificed a cvs repo to the git gods, so... fingers crossed.

**Comment by maxamillion** [comment]
rebuild_merge

**Pull request merged**
