### PR TITLE
oVirt: Add depracation warning to all modules

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

This PR renames modules from plural to singular and adds deprecation warning to all oVirt modules.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ovirt

##### ANSIBLE VERSION

```
2.5.3
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina @ryansb @mkrizek

**Review by mwperina — APPROVED** [review]
shipit

**Comment by ryansb** [comment]
This has conflicts with devel that must be resolved with a rebase of your branch.

**Comment by machacekondra** [comment]
Confictls resolved.

**Review by mwperina — APPROVED** [review]
shipit

**Comment by machacekondra** [comment]
shipit

**Review by ryansb — APPROVED** [review]

**Pull request merged**
