### PR TITLE
Add rollbar_deployment module

### PR DESCRIPTION
**Pull request by kavu**
My first module for Ansible. 

Please review. I'll be glad to fix it as needed.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks pretty good, sorry for the delay in response, there is a large queue!

Can you see if you can get this updated to use the new "module_utils/url" code that defines "fetch_url"?

This way the system will validate the SSL connections for the Rollbar server.

Thanks!

**Comment by kavu** [comment]
@mpdehaan sure, I'll try my best! But could you provide an ideal example module with using `module_utils/url` and `fetch_url`? Thanks!

**Comment by mpdehaan** [comment]
Basically I'd grep through the source and find any of them, and any will do.

flowdock module has an example for instance:

```
181:    response, info = fetch_url(module, url, data=data)
```

Be sure to import module_utils.urls at the bottom too.

Thanks!

**Comment by kavu** [comment]
@mpdehaan, done!

**Pull request merged**
