### PR TITLE
Remove unused import for iosxr l3_interfaces

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY

Remove unused import from iosxr_l3_interfaces facts.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

iosxr_l3_interfaces

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
