### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by jsoref**
##### SUMMARY
miscellaneous fixes

##### ISSUE TYPE
 - Docs Pull Request

##### ADDITIONAL INFORMATION
-- this isn't particularly systematic, I'm just starting to read the docs. I will do a more formal spelling pass assuming someone helps me get most of these changes accepted.

Sorry about picking the wrong branch to work from... I can try to rebase, but it's probably going to make a mess. For now, I'm more interested in seeing what people have to say about the changes in general.

### CODE REVIEW

**Comment by dharmabumstead** [comment]
Thanks @jsoref. A good deal of this material will be rewritten as part of a larger doc report over the next couple of months, and this is helpful. I will review over the next day or two. Thanks for helping to improve the core docs!

**Comment by jsoref** [comment]
@dharmabumstead: so, I'd like to have [jsoref/spelling](https://github.com/jsoref/spelling) run against this repository.

But, it's clearly a fast moving project. If I'm to run this tool, I'd need some guidance (especially what portion of things to try to work on/when). Normally, I run my tool against entire repos and then possibly reslice the patches based on categories of changes (docs, comments, internal variables, public strings, private functions, public functions).

Note: for me, it's much cheaper to run my script once against an entire repo than to slice a repo by directory, since typically spelling errors exist throughout, and a fix applied once applies everywhere. The only time there's a win is if a slice is likely to only have unrelated spelling errors.

**Comment by dharmabumstead** [comment]
@jsoref please hold off until my reorg/rewrite is done. I expect phase one of this done by next week. Thanks.

**Comment by jsoref** [comment]
Sure. You're also welcome to try the tools yourself. One approach is to use `fchurn` (once before you do your work, and once before you commit). The output should be all newly introduced (and likely misspelled) terms -- that would help you avoid introducing additional misspellings.

(I'm open to suggestions on how to make the tools easier to use. I think I'm going to provide long names for each script which will be used internally and leave the short names as aliases -- that should make collisions w/ local scripts less of an issue.)

Anyway, tag me when you're ready. I'll probably be using Ansible a lot next week....

**Comment by dharmabumstead** [comment]
Merging this before doc reorg. Thanks for the hard work, @jsoref!

**Comment by jsoref** [comment]
I've started using Ansible... I'll probably spend much more time making PRs/Issues.
But please do let me know when the reorg is done, and then I'll use https://github.com/jsoref/spelling on this project...

**Pull request merged**
