### PR TITLE
synchronize: Overwrite '--rsh' via rsync_opts

### LINKED ISSUE #15907: sychronize rsync_opts and --private-key= will send two --rsh arguments
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
synchronize module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (TEST_RSYNC_SSHKEY 42f6114b61) last updated 2016/05/17 19:11:57 (GMT -400)
  lib/ansible/modules/core: (devel 67de0675c3) last updated 2016/05/17 19:12:01 (GMT -400)
  lib/ansible/modules/extras: (devel e8391d6985) last updated 2016/05/17 19:12:06 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

fedora 23 controlhost
##### SUMMARY

rsync_opts with "-i keyfile" combined with --private-key= on the ansible cli, will construct two --rsh arguments to the rsync command.
##### STEPS TO REPRODUCE

```
- hosts: foohost
  gather_facts: False
  user: admin
  #connection: local
  tasks:
    - name: push with become to different remote user and delegate to different host
      synchronize:
        mode: push
        src: /tmp/foo
        dest: /tmp/foo_
        rsync_opts: --rsh "ssh -o PasswordAuthentication=no -i /home/admin/.ssh/id_rsa.bak"
/.ssh/id_rsa.bak"
      become: yes
      become_user: admin
      become_method: su  
      delegate_to: barhost

```
##### EXPECTED RESULTS

Only a single --rsh option.

##### ACTUAL RESULTS

Verbose output ...

```
changed: [barhost-> foohost] => {"changed": true, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh -i /home/jtanner/.ssh/id_rsa -S none -o StrictHostKeyChecking=no' --rsh \"ssh -o Pass
wordAuthentication=no -i /home/admin/.ssh/id_rsa.bak\" --out-format='<<CHANGED>>%i %n%L' \"/tmp/foo\" \"foohost:/tmp/foo_\"", "invocation": {"module_args": {"_local_rsync_path": "rsync", "_substitute_controller": false, "archive":
 true, "checksum": false, "compress": true, "copy_links": null, "delete": false, "dest": "foohost:/tmp/foo_", "dest_port": 22, "dirs": false, "existing_only": false, "group": null, "links": null, "mode": "push", "owner": null, "part
ial": false, "perms": null, "private_key": "/home/jtanner/.ssh/id_rsa", "recursive": null, "rsync_opts": ["--rsh \"ssh -o PasswordAuthentication=no -i /home/admin/.ssh/id_rsa.bak\""], "rsync_path": null, "rsync_timeout": 0, "set_remote_user": true, "sr
c": "/tmp/foo", "ssh_args": null, "times": null, "verify_host": false}}, "msg": ".d..t...... foo/\n<f..t...... foo/1\n<f..t...... foo/2\n<f..t...... foo/3\n", "rc": 0, "stdout_lines": [".d..t...... foo/", "<f..t...... foo/1", "<f..t...... foo/2", "<f..t.
..... foo/3"]}
```

### LINKED ISSUE #24705: The synchronize requires SSH be present even when not using it
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
synchronize

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = 
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]

```

##### CONFIGURATION
Using docker connection plugin

##### OS / ENVIRONMENT
Alpine 3.4 container

##### SUMMARY
https://github.com/ansible/ansible/blob/b729b35/lib/ansible/modules/files/synchronize.py#L476-L477

This code snippet requires that `ssh` be findable when `src` or `dest` include a `:`. When using synchronize with the docker connection plugin on distros that don't have an ssh client by default (e.g. Alpine), this check fails, despite the fact that SSH is not used.

##### STEPS TO REPRODUCE
1. Run two Alpine containers.
2. On one of them, install ansible. Take note of the other container's ID.
3. Run `ansible -c docker -m synchronize /etc $OTHER_CONTAINER_ID:/tmp` from the one where Ansible is installed.

##### EXPECTED RESULTS
Synchronization occurs.

##### ACTUAL RESULTS
Synchronization does not occur, and Ansible errors with:

```
"msg": "Failed to find required executable ssh in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

### PR DESCRIPTION
**Pull request by erwilan**
##### SUMMARY
Prevent the synchronize module to add the rsync option '--rsh' if the user or the synchronize plugin passed it via the task argument 'rsync_opts'.
The synchronize plugin does this if the 'docker' connection plugin is used.

Fixes #15907
Fixes #24705

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
modules/files/synchronize.py

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /share/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible-dev/local/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by ryansb** [comment]
@d3prof3t it looks like this fixes #24705 , would you be able to test it out to help get this fixed?

**Comment by d3prof3t** [comment]
Sure @ryansb 

Will catch up with you on IRC if have any issues.

**Comment by tima** [comment]
@d3prof3t  Was this fixed by #24705? Can we close this now?

**Comment by calfonso** [comment]
@d3prof3t could you follow up on this please? we need to know if this fixes #27405

**Comment by d3prof3t** [comment]
@calfonso I could not look into this issue. Sorry. It would be great if someone else could look into it.

**Comment by maxamillion** [comment]
@calfonso do you happen to know what the current status is on this? Is this in need of someone to confirm and review?

**Comment by ryansb** [comment]
Yeah - needs a confirmation that this patch addresses #24705

**Comment by maxamillion** [comment]
Reopened, the bot closed due to inactivity but I think that was too hasty given the state of the PR.

**Comment by maxamillion** [comment]
@ryansb @calfonso @jctanner @abadger This patch does not address #24705 in my testing when using the original reproducer provided by the Issue author.

**Comment by jctanner** [comment]
This does not seem to fix https://github.com/ansible/ansible/issues/15907 either.

```
fatal: [el7host -> el6host]: FAILED! => {                                                                                                                                                                                              
    "changed": false,                                                              
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no --rsh \"/usr/bin/ssh -o PasswordAuthentication=no -i /home/vagrant/.ssh/id_rsa\" --out-format=<<CHANGED>>%i %n%L /tmp/foo el7host:/tmp/foo_",
```

**Comment by erwilan** [comment]
thank you for your feedback @jctanner!

you have to pass each rsync_opts argument as a separate list item - e.g.:

```
rsync_opts: ["--rsh", "/usr/bin/ssh -o PasswordAuthentication=no -i /home/vagrant/.ssh/id_rsa"]
```

or:

```
rsync_opts:
    - "--rsh"
    - "/usr/bin/ssh -o PasswordAuthentication=no -i /home/vagrant/.ssh/id_rsa"
```


rsync also allows this:

```
rsync_opts: ["--rsh=/usr/bin/ssh -o PasswordAuthentication=no -i /home/vagrant/.ssh/id_rsa"]
```

or

```
rsync_opts:
    - "--rsh=/usr/bin/ssh -o PasswordAuthentication=no -i /home/vagrant/.ssh/id_rsa"
```

(in #15907 you pass a string to rsync_opts:
```
rsync_opts: --rsh "ssh -o PasswordAuthentication=no -i /home/admin/.ssh/id_rsa.bak"
```
)

(note my comments in #23575)

**Comment by goneri** [comment]
Hi @erwilan, thanks for the PR. It needs to be rebased, could you also add a changelog fragment and a test coverage.

**Pull request closed without merging**
