### PR TITLE
Fixed a parsing HEAD problem, when ansible is checked out as a submodule

### PR DESCRIPTION
**Pull request by andronat**
Fixed a parsing HEAD problem, when ansible is checked out as a
submodule in git

### CODE REVIEW

**Comment by andronat** [comment]
https://github.com/ansible/ansible/pull/992#issuecomment-8262639

Yes, this is my solution. Any comments?

**Comment by mpdehaan** [comment]
Much appreciated.

Almost there!   Since this is just to supply the value to --version, it should not call exit(), as we might want to use this version elsewhere in the application -- where having an "exit" on failure is not good -- especially if someone were later to check the application version from a background process.  

Note we normally just don't call exit either -- normally we could just raise errors.AnsibleError, but it's probably most accurate to just return the version string without the git info -- that way we know it's 0.7 or 0.8 and that's better than nothing -- and it also won't crash the program.   Just reporting the version without the git info is better in that case.

Fix this up and I'll take it.   Thanks!

Also minor, but should be fixed -- We also don't really use docstrings for comments unless when describing a function, so you should switch the comments to "#" for consistency.  Doc strings are still great when describing functions and classes.

**Comment by mpdehaan** [comment]
Works for me, great, thanks... this will be in 0.7 when it releases tomorrow.

**Comment by mpdehaan** [comment]
I changed "n/a" to just "" as when running from a package we don't want to append the git version info.

**Pull request merged**
