### PR TITLE
contrib/inventory/nsot.py: Make it compatible with NSoT v1.x

### PR DESCRIPTION
**Pull request by allanice001**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
contrib/inventory/nsot

##### ANSIBLE VERSION

```
2.2.0.0
```

##### SUMMARY

To make this compatible with NSoT v1.x, removing ['data']['devices'].

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
@coxley I believe you created the original inventory script. Could you please review this change. Thanks

**Review by gundalow — CHANGES_REQUESTED** [review]
As discussed in #ansible-meeting on 2016-12-20 

* This change breaks anyone using NSoT < 1.0 which was released 1.0 (2016-04-27)
* Can you please make this compatible with old and newer nsot data

Thanks

**Comment by coxley** [comment]
Changes look appropriate for the new API version to me! Simple enough change really.

@allanice001, if you could just show output testing the functionality from a `--list` or something that'd be cool. :)

**Comment by gundalow** [comment]
@allanice001 Could you please show the `--list` output (or similar) as requested above.

**Comment by allanice001** [comment]
$ NSOT_INVENTORY_CONFIG=$PWD/test.yaml nsot.py --list | jq '.'
   {
     "routers": {
       "hosts": [
         "test1.example.com"
       ],
       "vars": {
         "cool_level": "very",
         "group": "routers"
       }
     },
     "firewalls": {
       "hosts": [
         "test2.example.com"
       ],
       "vars": {
         "cool_level": "enough",
         "group": "firewalls"
       }
     },
     "_meta": {
       "hostvars": {
         "test2.example.com": {
           "make": "SRX",
           "site_id": 1,
           "id": 108
         },
         "test1.example.com": {
           "make": "MX80",
           "site_id": 1,
           "id": 107
         }
       }
     },
     "rtr_and_fw": {
       "hosts": [
         "test1.example.com",
         "test2.example.com"
       ],
       "vars": {}
     }
   }
   $ NSOT_INVENTORY_CONFIG=$PWD/test.yaml nsot.py --host test1 | jq '.'
   {
      "make": "MX80",
      "site_id": 1,
      "id": 107
   }

**Comment by gundalow** [comment]
@coxley The details you've asked for have been added. If you are happy I'll get this merged.

**Comment by coxley** [comment]
Sorry, have been out of town. LGTM!!

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Thanks everyone, merged.

Just as a heads up, we have a Network Working Group that you may be interested in https://github.com/ansible/community/blob/master/MEETINGS.md

**Pull request merged**
