### PR TITLE
New module for setting up Avi Pool Health Monitors

### PR DESCRIPTION
**Pull request by grastogi23**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

avi.avi_healthmonitor
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module for setting up Avi Pool Health Monitor. 

```

```

### CODE REVIEW

**Review by khaltore — APPROVED** [review]
+label shipit

**Review by gundalow — CHANGES_REQUESTED** [review]
I've not been through everything, though please ensure if in the documentation you specifuy:
* a default
* required: True

That this is also reflected in `argspec`

**Comment by grastogi23** [comment]
fixed both the issues.

**Comment by grastogi23** [comment]
@gundalow I have made all the changes as requested in the review.

**Review by gundalow — APPROVED** [review]

**Comment by ericsysmin** [comment]
shipit

**Comment by ericsysmin** [comment]
+shipit

**Comment by khaltore** [comment]
shipit

**Comment by ericsysmin** [comment]
shipit

**Pull request merged**
