### PR TITLE
Make sure we get all data

### PR DESCRIPTION
**Pull request by dhozac**
Ensures we don't have a case of the process dying with data still in the buffer that remains unread. This will lead to randomly truncated outputs of modules, and failures.

### CODE REVIEW

**Comment by mpdehaan** [comment]
In all, seems to make sense, though strange it hasn't been reported before, and I am curious how you reproduced this.   

Don't have a lot of time to review this AM (will look later), so hopefully you can explain intent a bit, so when I look at this more closely I can take that into account.

(A) 

I'm a bit curious what prompted the change from the 1024 to 9000.   It seems the code would work generically with set to either value, and am wondering if the move to 9000 has covered up a small logic error, which seems to be... (perhaps)

(B) 

```
 elif p.poll() is not None:
      break
```

the original poll condition was polling /while/ p was None (which seemed to be the opposite of what it does now)

There is a "large data" test in testutils that should probably still pass even if it's reading a small value, though of course the default test environment is paramiko, not -c ssh.  It would be worthwhile possibly repeating that test with an explicit "-c ssh" ?

**Comment by dhozac** [comment]
I haven't been able to reproduce at all, which is why it's been sitting in my repo since end of September. @dagwieers and @arrfab have seen it.

I changed from 1024 to 9000 since 9000 is a packet size, and should decrease the number of runs through the loop for longer outputs. It's not needed for this change, just something I did at the same time.

The condition is the same.

```
while p.poll() is None:
    ...
```

is equivalent to

```
while True:
    if p.poll() is not None:
        break
```

The difference is that condition is only checked when there isn't data available. I've run tests repeatedly with ANSIBLE_TRANSPORT="ssh", but haven't been able to reproduce at all, before the fix or after.

Our hope is that getting this part of the main tree would let us see if it fixes the problem. It occurs so rarely even for the people who it does happen to, so it's one of those things that time will have to tell...

**Comment by mpdehaan** [comment]
Thanks, the perils of skimming code before breakfast are apparent.

Seems fair to me, I'll merge it.

**Comment by dagwieers** [comment]
I experienced this today after months of no issues, cannot reproduce. Thanks for merging !

**Comment by arrfab** [comment]
yep, thanks for merging it : i'll ping back if issue is back too (was happening randomly though, so not easily reproduceable)

**Pull request merged**
