### PR TITLE
Misc fixes for several errors

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This fixes the usage of fail_json and string format

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/network/aci/msc.py

##### ANSIBLE VERSION

```paste below
2.8-devel
```

### CODE REVIEW

**Review by mkrizek — APPROVED** [review]

**Review by samerd — APPROVED** [review]
Thanks for the fixes in onyx code

**Comment by anasb** [comment]
Please remove me from your cc list.

**Review by dagwieers — APPROVED** [review]

**Comment by dagwieers** [comment]
@anasb No problem, but it means you won't be getting any notifications for Onyx modules in Ansible. You appeared as a member of $team_onyx, so https://github.com/ansible/ansible/pull/47986 removes you from that list.

**Comment by acozine** [comment]
@dagwieers @anasbadaha looks like we got the wrong GitHub account in #47552.

**Comment by dagwieers** [comment]
@acozine Fixed in https://github.com/ansible/ansible/pull/47986

**Comment by Akasurde** [comment]
Thanks everyone for help and support.

**Pull request merged**
