### PR TITLE
Apt module support for installing/removing specific version of package

### PR DESCRIPTION
**Pull request by dne**
This uses standard APT syntax, e.g.:

```
ansible webservers -m apt -a "pkg=nginx=1.1.19-1 state=installed"
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Excellent, thanks!

**Comment by mpdehaan** [comment]
Hey one quick comment, didn't initially see this, but this would make it more consistent with the yum module.''

Instead of:

apt pkg=foo=VERSION state=installed

Can we instead make that work as:

apt pkg=foo state=VERSION 

If so, that will make things more consistent.

Thanks!

**Comment by mpdehaan** [comment]
opened a ticket to track this, it's a new feature so no rush:

https://github.com/ansible/ansible/issues/199

let me know if this is something you have time for or if we need to find someone else to take it.

**Comment by dne** [comment]
Maybe I'm blind, but from reading the yum module code I can't see that it actually supports this syntax?!

**Comment by mpdehaan** [comment]
Yeah, I'm sorry, you're correct, it appears to work exactly as the apt one.

Nevermind, this is ok.  It's a little confusing if someone is coming from Puppet land, but I think it's ok.

Thanks!

**Pull request merged**
