### PR TITLE
Win setup gather more facts

### PR DESCRIPTION
**Pull request by trondhindenes**
This script gathers some extended facts on windows hosts in a json array attribute called "ansible_interfaces". This info is needed for some network-related modules I'm working on.

### CODE REVIEW

**Comment by cchurch** [comment]
When I run it against my current test instance (Windows 2008 R2 SP1), `ansible_interfaces` returns `["System.Collections.Hashtable", null]`, where I'd expect it to return something more meaningful.

I also get the following on stderr:

```
Cannot index into a null array. At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1409104391.18-21192582 1426412\setup.ps1:177 char:5 + $thisadapter = New-Object psobject @{ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : NullArray
```

**Comment by trondhindenes** [comment]
That is indeed strange. I'm spinning up a 2008R2 server as well to see if I can repro.

**Comment by trondhindenes** [comment]
I just tested on a 2008R2 SP1 machine (with PowerShell 3.0 installed as per ansible requirements), and it works fine. Could you send me the output of this code from your machine?

$netcfg = Get-WmiObject win32_NetworkAdapterConfiguration
$ActiveNetcfg = @(); $ActiveNetcfg+= $netcfg | where {$_.ipaddress -ne $null}
$ActiveNetcfg

**Comment by cchurch** [comment]
```
DHCPEnabled      : False
IPAddress        : {104.130.24.10, fe80::f8cd:929a:64b6:41ea, 2001:4802:7800:1:be76:4eff:fe20:63bd}
DefaultIPGateway : {104.130.24.1, fe80::def}
DNSDomain        :
ServiceName      : Xennet6
Description      : Citrix PV Ethernet Adapter #0
Index            : 7

DHCPEnabled      : False
IPAddress        : {10.176.1.103, fe80::20e5:c318:39e8:e168}
DefaultIPGateway :
DNSDomain        :
ServiceName      : Xennet6
Description      : Citrix PV Ethernet Adapter #1
Index            : 8
```

**Comment by trondhindenes** [comment]
Thanks Chris, I think I see what's causing it. Ive done a new commit on this PR, would you care to try it on your system?

**Comment by cchurch** [comment]
With only this pull request, my output from `ansible_interfaces` is now:

```
["System.Collections.Hashtable", "System.Collections.Hashtable"]
```

However, if I apply your change from https://github.com/ansible/ansible/pull/8768 I get:

```
[{"default_gateway": "104.130.24.1", "dns_domain": null, "interface_index": 12, "interface_name": "Citrix PV Ethernet Adapter #0"}, {"default_gateway": null, "dns_domain": null, "interface_index": 13, "interface_name": "Citrix PV Ethernet Adapter #1"}]
```

So this one looks good to me, provided https://github.com/ansible/ansible/pull/8768 is merged first.

**Comment by trondhindenes** [comment]
I should have thought of that. It's exactly why I wanted deeper json conversions in the first place.

**Comment by cchurch** [comment]
# Cleanup Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We do require submissions to be free of merge commits, which cause difficulties in reviewing and merging code, and also affect the history of the source tree.
To resolve this problem, it may be helpful to create a new branch and cherry-pick commits onto it.
- In general, always start a "topic branch" named after each thing you would like to contribute
- use "git pull --rebase" vs "git pull" to stay in tune with upstream, as well as "git rebase" vs "git merge"
- if you have things broken out over many commits, consider submitting just one squashed commit that keeps the history concise

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by trondhindenes** [comment]
Sorry about that, I knew I had some hiccups in my own repo but I didn't realize I sent that mess into the PR. So, if I understand it correctly yu wanted me to simply bunch together all my 3 minor PRs into a single one, which I've done here: #8812. Hopefully that one's clean (looks clean to me) and can be merged without problems. We can go ahead and close this PR.

**Comment by cchurch** [comment]
Merged via #8812

**Pull request closed without merging**
