### PR TITLE
Azure Virtual Machine Scale Set support (azure_rm_virtualmachine_scaleset)

### PR DESCRIPTION
**Pull request by sozercan**
##### SUMMARY

Adds support for Azure Virtual Machine Scale Sets

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

azure_rm_virtualmachine_scaleset

##### ANSIBLE VERSION

```
ansible 2.4.0 (azure-vmss 0e644221fd) last updated 2017/08/18 06:20:52 (GMT +000)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible/lib/ansible
  executable location = /app/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by sozercan** [comment]
@tstringer @haroldwongms this is ready!

**Comment by trstringer** [comment]
Looks good to me!

shipit

**Comment by sozercan** [comment]
bot_status

**Comment by sozercan** [comment]
!needs_revision

@tstringer is ansibot broken?
bot_broken

**Comment by haroldwongms** [comment]
shipit

**Comment by sozercan** [comment]
bot_status

**Pull request merged**
