### PR TITLE
Add inventory script for Foreman.

### PR DESCRIPTION
**Pull request by fcuny**
The inventory script can be used to build dynamically an inventory by queriying Foreman's API.

We're using [Foreman](http://theforeman.org/) at work to manage our inventory and creating new hosts. This pull request add a script to get the inventory from Foreman for Ansible.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hello Frank,

We are not going to include support for foreman in core due to issues with the management of that project and how it interacts with other projects.

Out of professional courtesy I'm not going to go into details here, but if you'd like to shoot me a private email, I can explain (though I'm not going to change my stance on this).

Thank you!

**Comment by ohadlevy** [comment]
just wondering, any chance this can be re-evaluated?

**Comment by mywebpower** [comment]
+1 for being included

**Comment by DimmKirr** [comment]
+1

**Comment by demueller** [comment]
+1

**Pull request closed without merging**
