### PR TITLE
Update documentation for passwordstore lookup

### PR DESCRIPTION
**Pull request by sigio**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
lookup_plugins/passwordstore

##### ANSIBLE VERSION
devel from 2017/02/15

##### SUMMARY
Adding documentation (mostly a copy from the readme.md) for the newly merged passwordstore lookup plugin.

### CODE REVIEW

**Comment by gundalow** [comment]
@sigio Thank you for updating the docs. The formatting of the code doesn't appear quite right (if you do "Files Changed" then "View". Would it be possible for you to take a look at this?

I think if you write it with `::` at the end of the sentence it should render correctly:

```
Create pass with random 16 char password. If password exists just give the password::

    password="{{ lookup('pass', 'example/test create=true')}}`
```

needs_revision

**Comment by sigio** [comment]
Fixed, didn't know I could see the results here immediately... as I couldn't get sphynx to install locally to check.

**Review by gundalow — APPROVED** [review]
Thanks

**Review by dharmabumstead — APPROVED** [review]
Approved with edits. Thanks @sigio!

**Comment by dharmabumstead** [comment]
Thanks @sigio!

**Pull request merged**
