### PR TITLE
initial commit of win_domain_controller

### PR DESCRIPTION
**Pull request by nitzmahone**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
win_domain_controller

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Great, I have a use for this, looking forward to trying it out.  Many thanks,
Jon

**Comment by nitzmahone** [comment]
Please do! It's very minimal right now- I wanted to have all the pieces necessary to stand up a basic forest from scratch, and now we do. Feel free to file bugs/enhancements or hack in stuff you need if there are things it doesn't do that you wish it did.

**Comment by nitzmahone** [comment]
The authentication story for these is a bit of a nightmare- I think I'll probably go back to an action wrapper to handle the mid-stream auth switch and reboot (an early prototype did that).

**Comment by jhawkesworth** [comment]
No worries I am happy to have a 'create vms from inventory' play which is separate from putting our software stack on to the different server types for now.

**Pull request merged**
