### PR TITLE
Azure Availability Set facts module (azure_rm_availabilityset_facts)

### PR DESCRIPTION
**Pull request by julienstroheker**
##### SUMMARY

New module that adds support for Azure Availability Set (facts)

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- azure_rm_availabilityset_facts

##### ANSIBLE VERSION

```
ansible 2.4.0 (az-availabilityset-facts 34b06d9dc6) last updated 2017/08/14 21:58:17 (GMT +000)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible/lib/ansible
  executable location = /app/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by haroldwongms** [comment]
shipit

**Comment by trstringer** [comment]
shipit

**Comment by haroldwongms** [comment]
shipit

**Comment by julienstroheker** [comment]
@tstringer @haroldwongms Do I need to do something on that one ?

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
