### PR TITLE
Add rel_file to ansible_managed template variable

### LINKED ISSUE #45654: "{rel_file}" in ansible_managed
##### SUMMARY

Add a new format variable to `ansible_managed`, which behaves like `{file}` but contains only the path relative to `ansible.cfg`.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

Core? (`lib/ansible/template`)

##### ADDITIONAL INFORMATION

Currently, using `{{ ansible_managed }}` in templates will insert a dynamic string into the file, with the path to the template file, the current time and the user/host name executing the template task being dynamic.

In its default configuration, this violates the priniciple of plays being idempotent. Two different users will create a change in the file, even if otherwise nothing has changed.

One could work around this by setting

```ini
ansible_managed = Ansible managed: {file}
```

in `ansible.cfg`, but even this might result in changes if the plays are stored in a SCM repository and checked out by different users in different locations. One might get around even this (by configuring `ansible_managed = Ansible managed: DO NOT EDIT`), but then it becomes guesswork to find the responsible template file (especially in larger repos).

I suggest adding another format variable to [`template/__init__.py`](https://github.com/ansible/ansible/blob/211aeebd0d/lib/ansible/template/__init__.py#L101-L105), which should contain a relative path (either relative to `ansible.cfg`, or the current working directory).

### PR DESCRIPTION
**Pull request by dmke**
##### SUMMARY
This add a `rel_file` format string to the `ansible_managed` template variable.

Fixes #45654

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`template`?

##### ADDITIONAL INFORMATION
The relative path resolution is very simplistic: it just strips the `inventory_dir` from the `template_path`, which may or may not be enough for this feature.

Here's a sample output of this patch applied to `stable-2.9`:

```console
$ fgrep ansible_managed ./ansible.cfg
ansible_managed = Ansible managed: {rel_file} - DO NOT EDIT

$ cat playbooks/testbed.yml
---
- hosts: localhost
  roles:
  - testbed

$ cat roles/testbed/tasks/main.yml
---
- name: create file
  template:
    src: test.j2
    dest: /tmp/test.ansible

$ cat roles/testbed/templates/test.j2
{{ ansible_managed }}

$ ansible-playbook playbooks/testbed.yml --diff
PLAY [localhost] *************************************************************

TASK [Gathering Facts] *******************************************************
ok: [localhost]

TASK [testbed : create file] *************************************************
--- before
+++ after: /home/dm/.ansible/tmp/ansible-local-13670DFMU7R/tmpIK7AXO/test.j2
@@ -0,0 +1,1 @@
+# Ansible managed: roles/mm/templates/test.j2 - DO NOT EDIT

changed: [localhost]

PLAY RECAP *******************************************************************
localhost: ok=2 changed=1 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0
```

##### TODOs

- Bike shedding: How should the variable be named? `rel_file` might not be descriptive enough.
- Path resolution: Is the current implementation too naïve? If so, what are the environments I should consider? Is basing this off of `inventory_dir` the wrong approach?
- Documentation: I have not yet touched the documentation. The rationale from #45654 should be included.
- Test: As far as I can tell, this is not heavily tested. I also haven't touched the tests yet.

I'm not a Python developer by trade, so this small patch might contain non-idiomatic code. I'm open for suggestions.

### CODE REVIEW

**Review by bcoca — CHANGES_REQUESTED** [review]
a couple of things
   a) `inventory_dir` might not be present (see implicit localhost) 
   b) inventory is not the source for relative file paths, the 'play' is, if they happen to be the same in your setup that is coincidental, but inventory is not part of template/vars/files search path (it is for host_vars/group_vars, but that is diff system)

You might want to look at the dwim functions and how they use a search path, it is not as simple as you might think, specially when `templates/` is optionally added and when roles appear in the mix, all create special cases.

**Comment by dmke** [comment]
> a) `inventory_dir` might not be present (see implicit localhost)

I was not aware of [this](https://docs.ansible.com/ansible/2.9/inventory/implicit_localhost.html). However, if `task_vars.get('inventory_dir')` returns `None`, `rel_path` end up as being the same as `path`

> b) inventory is not the source for relative file paths, the 'play' is, if they happen to be the same in your setup that is coincidental, but inventory is not part of template/vars/files search path

Indeed, I have `inventory = ./hosts` in my `ansible.cfg` (with both files checked into the repository).

> You might want to look at the dwim functions and how they use a search path

Hm, grep'ing for `dwim` yields 80+ results, with `path_dwim` defined in `lib/ansible/parsing/dataloader.py`. Do you mean that class?

Alternatively, might a simple `os.getcwd()` suffice as `base_dir` for this purpose? Presumably, one would invoke `ansible-playbook` always from the same working directory? I mean, the use case for `rel_file` is a shared repository, which *should* be fully self-contained (i.e. containing one or more inventories, the Ansible configuration, playbooks, roles, and plugins, as this minimizes setup-time for each user interacting with that repo).

**Comment by bcoca** [comment]
yes, dataloader has several dwim (do what i mean) functions for resolving relative paths, depending on context, you end up using one of those

cwd is not correct, you need basedir, since you can `cd /var/tmp && ansible-playbook ~/projects/play.yml`. We purposefully avoid using cwd when we can to avoid issues like that, we are always relative to either inventory, playbook or role.

**Comment by dmke** [comment]
Okay, thanks for the info.

Can you recommend a debugger (or anything more sophisticated than `print()`) to step through the code base for runtime introspection? As I said, I'm not a Python developer, and the Ansible code base is... a bit overwhelming :-)

**Comment by bcoca** [comment]
epdb is THE debugger, others exist (i do abuse `print()` but also the `q` library).

**Comment by bcoca** [comment]
Closing this as other modifications introduced `template_fullpath` leaving `template_path` as the 'unresolved' path supplied to the template, this could be relative or not, but results in more or less the same as this modification that relies on having a `base_path` or not.

**Pull request closed without merging**
