### PR TITLE
ovirt_host: Fix fail condititon of upgrade

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

This PR changes the fail condition of host upgrade so it takes into account also the case when VM fails to migrate during upgrade.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ovirt_host

##### ANSIBLE VERSION

```paste below
2.6
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
shipit

**Comment by machacekondra** [comment]
shipit

**Comment by Shaps** [comment]
:+1: You just made the 40000th commit to Ansible! :D

**Comment by gundalow** [comment]
Congratulations, this is the 40,000 commit to Ansible!

**Comment by mwperina** [comment]
:+1:

**Pull request merged**
