### PR TITLE
adding hdinsight cluster

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY

Adding HDInsight cluster

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
azure_rm_hdinsightcluster

##### ANSIBLE VERSION
2.7

### CODE REVIEW

**Comment by zikalino** [comment]
@mattclay could you pls add hdinsight to the subscription?

Error Code: MissingSubscriptionRegistration\n\tMessage: The subscription is not registered to use namespace 'Microsoft.HDInsight'

**Comment by zikalino** [comment]
@mattclay could you add hdinsight?

**Comment by mattclay** [comment]
@zikalino Added. Tests now have a new failure:

https://app.shippable.com/github/ansible/ansible/runs/91293/71/tests

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino Could you help confirm this PR ready for review or not? Thanks!

**Pull request closed without merging**
