### PR TITLE
Make user module create accounts with temporary passwords

### PR DESCRIPTION
**Pull request by kalininsn**
This Pull Request adds new option passchangeonfirstlogin to user module, if it set to 'yes', after user creation procedure command 'chage -d 0' is being called, so after first login user should change his password

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this.

There are a few things with this pull request that should be changed.

The parameter should not be allruntogetherlikethis, but should be something like "change_on_first_login", or it seems even better to just expose the various aspects of chage  directly, allowing more flexibility, which may also warrant additional parameters.

This is a little gross in that it would require most of the parameters to chage, such as "chage_min", "chage_max", etc.   However I think once added, people will soon want the other knobs and buttons to be exposed.

There's a stray print that makes the return of the module not completely JSON, that may work if it appears after the JSON, but must be removed.

Finally, since this is a new option, in the DOCUMENTATION block under the parameter, add "version_added: '1.6'".

I do note that it doesn't detect when the password age has been changed with the "change=True", which should probably

**Comment by kalininsn** [comment]
Thanks a lot for feedback, i'll try to fix it all tomorrow

**Comment by kalininsn** [comment]
Here are some fixes for PR

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Pull request closed without merging**
