### PR TITLE
add callback for playbook and playbook executor

### PR DESCRIPTION
**Pull request by lkx007**
##### SUMMARY

we want to use callback to get task result when ansible playbook execute tasks.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`lib/ansible/cli/playbook.py`
`lib/ansible/executor/playbook_executor.py`

### CODE REVIEW

**Comment by samdoran** [comment]
cc @bcoca @abadger

**Comment by bcoca** [comment]
@lkx007 i'm not sure what you want to accomplish with this, tqm already has a way of loading the callback
needs_info

**Comment by lkx007** [comment]
@bcoca I want to record all playbook results to database automatally using PlaybookExecutor by adding callback param.

**Comment by bcoca** [comment]
you just need to enable a callback plugin, not add callback in these functions

**Comment by maxamillion** [comment]
Closing as this isn't necessary, if this functionality is desired that's what the [callback plugins](https://docs.ansible.com/ansible/latest/plugins/callback.html) are for.

**Pull request closed without merging**
