### PR TITLE
added module for defining a supervisor program config

### PR DESCRIPTION
**Pull request by guymatz**
##### SUMMARY
Module to allow for the creation/deletion/change of supervisord program configuration

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
supervisor_prog

##### ANSIBLE VERSION
```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by mattclay** [comment]
The test `ansible-test compile --python 2.4` failed with the following error:

```
lib/ansible/modules/system/supervisor_prog.py:268:15: SyntaxError: finally:
```

The test `ansible-test compile --python 3.5` failed with the following error:

```
lib/ansible/modules/system/supervisor_prog.py:266:21: SyntaxError: except Error, e:
```          

The test `ansible-test compile --python 3.6` failed with the following error:

```
lib/ansible/modules/system/supervisor_prog.py:266:21: SyntaxError: except Error, e:
```          

The test `ansible-test sanity --test ansible-doc --python 2.6` failed with the following error:

```
Command "ansible-doc supervisor_prog" returned exit status 1.
>>> Standard Error
ERROR! module supervisor_prog missing documentation (or could not parse documentation): expected string or buffer
```

The test `ansible-test sanity --test pep8` failed with the following errors:
            
```
lib/ansible/modules/system/supervisor_prog.py:276:17: E126 continuation line over-indented for hanging indent
lib/ansible/modules/system/supervisor_prog.py:297:17: E126 continuation line over-indented for hanging indent
lib/ansible/modules/system/supervisor_prog.py:328:13: E121 continuation line under-indented for hanging indent
lib/ansible/modules/system/supervisor_prog.py:381:1: W293 blank line contains whitespace
lib/ansible/modules/system/supervisor_prog.py:482:1: W293 blank line contains whitespace
lib/ansible/modules/system/supervisor_prog.py:606:17: E126 continuation line over-indented for hanging indent
```

The test `ansible-test sanity --test validate-modules` failed with the following errors:

```
lib/ansible/modules/system/supervisor_prog.py:0:0: E305 DOCUMENTATION.options.stdout_logfile_backups.description.0: expected basestring @ data['options']['stdout_logfile_backups']['description'][0]. Got None
lib/ansible/modules/system/supervisor_prog.py:0:0: E305 DOCUMENTATION.options.redirect_stderr.choices: expected list for dictionary value @ data['options']['redirect_stderr']['choices']. Got None
lib/ansible/modules/system/supervisor_prog.py:0:0: E305 DOCUMENTATION.options.stderr_logfile_backups.description.0: expected basestring @ data['options']['stderr_logfile_backups']['description'][0]. Got None
lib/ansible/modules/system/supervisor_prog.py:0:0: E307 version_added should be 2.3. Currently 0.9
lib/ansible/modules/system/supervisor_prog.py:0:0: E312 No RETURN documentation provided
lib/ansible/modules/system/supervisor_prog.py:0:0: E208 module_utils imports should import specific components, not "*". line 652
lib/ansible/modules/system/supervisor_prog.py:0:0: E107 Imports should be directly below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 652
lib/ansible/modules/system/supervisor_prog.py:0:0: E105 GPLv3 license header not found
```

**Comment by dagwieers** [comment]
bot_status

**Comment by mattclay** [comment]
@guymatz This PR has unrelated commits from devel. Please [rebase](https://docs.ansible.com/ansible/dev_guide/developing_rebasing.html) your branch.

**Comment by mattclay** [comment]
needs_rebase

**Comment by jctanner** [comment]
@guymatz how did you create your fork and feature branch? There's some "extra" commits that shouldn't be there, so I'm trying to understand how that happened.

needs_info

**Comment by guymatz** [comment]
@jctanner I forked, but I didn't create a feature branch . . .  I thought that I didn't need to since I had forked . . .  I guess I should?  Sorry!  a bit new to this very communal programming.  I followed this guide, but maybe not closely enough: https://docs.ansible.com/ansible/dev_guide/developing_modules_checklist.html

**Comment by guymatz** [comment]
bot_status

**Comment by guymatz** [comment]
@dagwieers  Wow, you're a real person!  Thanks for all of the RPMs over the years!  :-)

**Comment by guymatz** [comment]
@dagwieers  @gregswift @tbielawa please be merciless with your criticisms.  Only way to learn, and all that . . .

**Comment by jctanner** [comment]
@guymatz I would suggest closing this and re-submitting with a feature branch. The basic process is:

1) create the fork on github (you've already done that, so you might need to delete the fork and recreate to clear your commits)
2) clone your fork 
3) git checkout -b FEATURE_NAME
4) make your changes
5) git add <changed files>
6) git commit -m "your message"
7) git push origin FEATURE_NAME
8) In the github UI (https://github.com) you should see a notification on your fork's page that a new branch has been created with a diff
9) click on that notification to create the pullrequest

**Comment by mattclay** [comment]
@guymatz You'll also need to reset your devel branch back to a clean state so you can branch off of it. One way to do that is this:

1. Save a copy of your module, since it's just one file.
2. Get rid of all the unwanted commits on your devel branch with `git reset HEAD~20`.
3. Update your devel branch on GitHub with a force push `git push --force`.
3. Then follow the instructions from jctanner, using the copy of your module you saved earlier.

Without this your new feature branch will have all the unwanted commits from your devel branch, as will your devel branch on GitHub.

**Comment by mattclay** [comment]
@guymatz jctanner has updated his instructions. If you re-create your fork, ignore my instructions.

**Comment by mattclay** [comment]
needs_rebase

**Comment by guymatz** [comment]
@jctanner @mattclay Will do!  Thanks!!

**Pull request closed without merging**
