### PR TITLE
Stackdriver code deploy and annotation module

### PR DESCRIPTION
**Pull request by bwhaley**
This module implements the Stackdriver [code deploy](http://feedback.stackdriver.com/knowledgebase/articles/212917-sending-code-deploy-events-to-stackdriver) and [annotation](http://feedback.stackdriver.com/knowledgebase/articles/260455-sending-annotation-events-to-stackdriver) API. 

NOTE: The module works fine but `make webdocs` does not work for me and I have no idea why. It fails with the error [in this gist](https://gist.github.com/bwhaley/10508449). I asked in IRC chat but nobody helped. Happy to fix if you can see what the problem is.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Nice leeroy jenkins reference :)  

We can look at fixing the docs stuff, I'll probably also break up the module examples so they aren't all on one line too.

**Comment by jimi-c** [comment]
@bwhaley we've created some wrappers around urllib (contained within `lib/ansible/module_utils/urls.py`) that add some things like authentication and SSL certificate validation. Could you please rewrite the urllib\* parts to use fetch_url() instead? Take a look at some of the other core modules to see how it's used for API calls, or if you have any questions you can ping me on IRC (`jimi|ansible`).

Thanks!

**Comment by bwhaley** [comment]
@jimi-c Let me know if this is what you had in mind and if I missed anything you wanted.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
