### PR TITLE
Python 3.9 Controller minimum for document

### PR DESCRIPTION
**Pull request by akira6592**
##### SUMMARY

According to #77566 controller needs Python 3.9 or higher.

So I fixed installation guide and porting guide.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- installation guide
- porting guide

### CODE REVIEW

**Comment by akira6592** [comment]
Depends on #77566

**Review by sivel — APPROVED** [review]
Only applicable for devel (2.14)

**Comment by akira6592** [comment]
Thank you for your approval. 

OK. I don't have  plans to backport.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @akira6592 for the Ansible docs fix!

**Comment by akira6592** [comment]
Thank you for merging!

**Pull request merged**
