### PR TITLE
Update intro_getting_started.rst

### PR DESCRIPTION
**Pull request by Gr4cchus**
##### SUMMARY

When running ansible(ansible 2.9.15) on centos 8(4.18.0-240.1.1.el8_3.x86_64) this is the output of the command `ansible all -a "/bin/echo hello"`
Not sure if relevant or not. 
##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Gr4cchus** [comment]
Seems the output of the command of the old doc is from a previously executed command which was not relevant to what was suppose to be run.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The output in the docs is a correct reflection of the `ping` usage shown above, you are using a different command and it is expected you get different output.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by Gr4cchus** [comment]
Two different commands are issued, ping and echo. The output reflects only 1 of the commands and ignores the most recent command issued which caused confusion.

**Comment by Gr4cchus** [comment]
> # Possible Misunderstanding
> Hi!
> 
> Thanks very much for your submission to Ansible. It sincerely means a lot to us.
> 
> We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.
> 
> The output in the docs is a correct reflection of the `ping` usage shown above, you are using a different command and it is expected you get different output.
> 
> In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
> 
> * https://groups.google.com/forum/#!forum/ansible-project
> 
> Thank you once again for this and your interest in Ansible!

Two different commands are issued, ping and echo. The output reflects only 1 of the commands and ignores the most recent command issued which caused confusion.

**Pull request closed without merging**
