### PR TITLE
cloud: ovirt: Various fixes for oVirt modules

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

modules/cloud/ovirt/

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This PR contains various commits which fixes various issues in oVirt modules.

### CODE REVIEW

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
@mwperina @ryansb

**Review by mwperina — APPROVED** [review]
:+1:

**Comment by ryansb** [comment]
Can you please rebase this?

**Pull request merged**
