### PR TITLE
Add GPL License header to rackhd inventory file.

### PR DESCRIPTION
**Pull request by abednarik**
##### SUMMARY

Add GPL License header to rackhs inventory file

#24342

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

contrib/inventory/rackhd.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.0 (apt_download_only 4def437187) last updated 2017/05/03 14:32:40 (GMT +000)
  config file =
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

### CODE REVIEW

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by sivel** [comment]
Per the referenced issue, I believe we will need sign off from each of the authors mentioned before we can license this file as GPL.

As far as the ticket states, you are not an original author of that file.

**Comment by Akasurde** [comment]
OK.

**Comment by gundalow** [comment]
@keedya
@mattclay
@Shaps 
Can you please sign off on this change, thanks in advance.

**Comment by Shaps** [comment]
ok for me

**Review by mattclay — APPROVED** [review]

**Review by keedya — APPROVED** [review]

**Comment by abednarik** [comment]
Hi @gundalow 

 I think all contributors signed off this one. Sorry to bother, just want to help you reviewing thousand of Issues and PR.

Cheers.

**Comment by gundalow** [comment]
@abednarik hum, appears this got lost in my GitHub email. Rebase needed, which may mean someone else to get approval from

rebase_needed

**Comment by abednarik** [comment]
Hi @gundalow , no problem. I just did the rebase. I think we need @Shaps approval also to merge this.

Thanks.

**Review by Shaps — APPROVED** [review]

**Comment by abednarik** [comment]
Hi @gundalow 

 This one is ready to merge, if you are ok with that.

Thanks.

**Pull request merged**
