### PR TITLE
Missing documentation about the include directive for requirements files

### PR DESCRIPTION
**Pull request by Lujeni**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
ansible-galaxy

##### SUMMARY
https://github.com/Lujeni/ansible/blob/devel/lib/ansible/cli/galaxy.py#L339

The `include` directive is missing documentation.

### CODE REVIEW

**Comment by Lujeni** [comment]
Hello @abadger ,

Should I modify something to integrate this documentation ?
Thanks

**Comment by Lujeni** [comment]
Hello @abadger @dharmabumstead 

Need some update ?

Thanks

**Review by dharmabumstead — APPROVED** [review]
Doc updates OK.  Need someone from core to tech review and sign off.

**Comment by Lujeni** [comment]
friendly bump.

@dharmabumstead do you know who can review this MR pls?

Thanks

**Review by gundalow — APPROVED** [review]
Approved with minor formatting changes

**Pull request merged**
