### PR TITLE
Add an 'extra_args'-parameter to the npm module

### PR DESCRIPTION
**Pull request by pari-**
##### SUMMARY
This PR adds an 'extra_args'-parameter to the npm module, in an analogous manner of the pip module.

Instead of adding all possible parameters, I deem this change the most advantageous one when it comes to functionality gain versus cost + it's flexible and can cover potential functionality added to future npm versions.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
npm

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/pringl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pringl/.pyenv/versions/2.7.13/envs/python-2.7.13_ansible-2.5.0.0/lib/python2.7/site-packages/ansible
  executable location = /Users/pringl/.pyenv/versions/python-2.7.13_ansible-2.5.0.0/bin/ansible
  python version = 2.7.13 (default, Jun 15 2017, 10:33:06) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### ADDITIONAL INFORMATION
None

### CODE REVIEW

**Comment by xcambar** [comment]
Hey @pari-, thanks for the PR.

Can you add tests, please, so that we won't break in the future?
0, 1, many extra arg(s) would be nice to have. Thanks.

**Comment by pari-** [comment]
Hi @xcambar,

`extra_args` is just a string, additionally appended to the to-be-executed arg list - so: what kind of test or rather what kind of potential "breaking scenario" do you have in mind (I might lack some fantasy here) ;-)


regards,
pari

**Comment by xcambar** [comment]
I'd like to make sure that `extra-args: "arg1 arg2"`, will be correctly evaluated as 2 separate arguments "arg1" and "arg2" and not a single argument "arg1 arg2", which is certainly not what you're after.

If these tests fail, that would force your PR to introduce `extra_args` as an array, not a string.

**Comment by pari-** [comment]
@xcambar there's no need to enforce the behaviour you described above i.e. I am absolutely fine (and so is `npm`) if the supplied `extra_args` are evaluated to one argument, no matter how many there are.

Would you mind elaborating on the actual use-case you have in mind? I am still not seeing what you'd want to test this for, since I do not see a potential breaking scenario (which is also why modules like `pip` implement it the very same way).

**Comment by xcambar** [comment]
Unfortunately, it's not how the pip module is built. It exposes `extra_args` as a string, but under the hoods, [splits the string into an array](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py#L481-L482), to prevent just what I describe above.

**Comment by pari-** [comment]
@xcambar it does that only to handle `-e` properly .... (if `editable`is set, otherwise it'll just pass `extra_args` on as string).

Would you please elaborate on your "breaking scenarios" - otherwise I thankfully decline your proposal to add a test that is of no real value.

Thanks

**Comment by xcambar** [comment]
You know why I only highlighted 2 lines? Because I read too fast and not enough 😖 

You're right, this seems legit. Thanks for helping me understand a bit more, even though it's the hard way 😝 

shipit

**Comment by jctanner** [comment]
!waffling stale_ci

**Comment by xcambar** [comment]
shipit

**Pull request closed without merging**
