### PR TITLE
win_environment: Added tests and return info in document

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Adds tests for the win_environment module and also adds in the return information for this module to the docs page.

##### ISSUE TYPE
 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME
win_environment

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 6a3ce18e4b) last updated 2017/05/25 20:15:42 (GMT +1000)
  config file = /mnt/c/dev/module-tester/ansible.cfg
  configured module search path = [u'/home/jordan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/dev/linux-ansible/lib/ansible
  executable location = /mnt/c/dev/linux-ansible/bin/ansible
  python version = 2.7.13 (default, Apr 13 2017, 08:16:29) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Thanks for documenting return values too, surprised I missed that before.

shipit

**Comment by jhawkesworth** [comment]
bot_status

**Comment by jborean93** [comment]
No worries, I've made plenty of omissions for previous changed. I wonder if this works now that we are maintainers for all Windows things

shipit

**Comment by jhawkesworth** [comment]
as module maintainer I think it should be enough for me too give it the ok. However the stale ci tag has appeared, which I guess might be stopping things.

Going to close and reopen to trigger CI again and see if that helps, will probably need to ship it again after.

**Comment by jhawkesworth** [comment]
To trigger CI

**Comment by jhawkesworth** [comment]
shipit

**Comment by jhawkesworth** [comment]
bot_status

**Review by dagwieers — APPROVED** [review]

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
bot_status

**Comment by dagwieers** [comment]
@jhawkesworth @jborean93 It appears we are not all considered maintainers :-/
So only @jhawkesworth shipit is counting for automerge :-(

**Comment by jhawkesworth** [comment]
Ah, I think I see what's going on here.  Because I'm external commiter, I appear in 'ansible shipits' - but that seems to have stopped my 'maintainer shipit' from counting.

Just going to merge it since I can.

**Pull request merged**
