### PR TITLE
module_utils/basic.py: Support logical or condition in required_if

### PR DESCRIPTION
**Pull request by ganeshrn**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

basic

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0 (devel cba66dfedc)
```

##### SUMMARY

```
Add logical 'or' condition support in 'required_if'
for requirements.
* If requirements is a list all parameters within it should
  be present.
* If requirements is a tuple atleast one parameter should
  be present
```

### CODE REVIEW

**Comment by gundalow** [comment]
+1 from me

It's on my list to better document all the required_one_of, require_if, etc

Would have been useful for https://github.com/ansible/ansible/pull/20548 which I just reviewed.

**Comment by evgeni** [comment]
Would love to have that for #20548 too.

Not sure I love the semantic dependency on list vs tuple, but I guess that's the best we can do here without introducing a trainwreck full of new params.

**Review by gundalow — APPROVED** [review]

**Comment by abadger** [comment]
Yeah, list vs tuple isn't a good way to determine this.  I think it's a blocker.  The idea of the feature is good, though.  Have to figure out another way to do this.

**Comment by gundalow** [comment]
needs_revision (based on abadger's comment above)

**Comment by abadger** [comment]
It's too bad this is currently AND... AND can also be done by specifying something multiple times whereas OR has to be done in one call.

Two ways I can think of doing this:
* Have a new check for required_if using OR instead of AND.
* Add an optional fourth tuple value that's a boolean that selects between AND vs OR.

The second option probably makes the most sense from the module author's standpoint.  It is a bit hacky in the implementation but if no one can come up with a better alternative it's probably the best choice.

**Comment by ganeshrn** [comment]
@abadger Initially even I thought of adding a optional fourth tuple value but later changed it to list/tuple thinking this might be easier for users instead of making them pass extra tuple value. If everyone is ok with second option I will modify the PR accordingly. What would be the best approach for second option?
* Fourth tuple value is logical operation ie `or`, `and` with default as `and`
```
required_if(a, b, [c, d], 'or')
```
Or
* Optional fourth tuple is boolean. `True` is considered as logical `or` and default is `False` which indicates logical `and`
```
required_if(a, b, [c, d], True)
```

**Comment by abadger** [comment]
boolean seems better for me.  @bcoca, any opinion from you on this?

**Comment by bcoca** [comment]
boolean looks better to me also

**Comment by ganeshrn** [comment]
@abadger @bcoca Fixed review comment.

**Comment by abadger** [comment]
Code looks good and the shippable test failure is unrelated.

**Comment by abadger** [comment]
Merged to the devel branch for inclusion in 2.3

**Comment by abadger** [comment]
Thanks @ganeshnalawade for the code and @evgeni @gundalow and @bcoca for the review!

**Pull request merged**
