### PR TITLE
New module: cnos_factory

### PR DESCRIPTION
**Pull request by dkasberg**
ISSUE TYPE

New Module Pull Request
COMPONENT NAME

cnos_factory

ANSIBLE VERSION

ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

SUMMARY

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to:

```
2017-02-21 22:47:25 ============================================================================
2017-02-21 22:47:25 lib/ansible/modules/network/cnos/cnos_factory.py
2017-02-21 22:47:25 ============================================================================
2017-02-21 22:47:25 TRACE:
2017-02-21 22:47:25     'str' object is not callable
2017-02-21 22:47:25 ERROR:304:Unknown DOCUMENTATION error, see TRACE
```

@sivel This looks like a bug in the module validator.

**Comment by sivel** [comment]
That error is not coming from the validator, but from `get_docstring` in ansible.  It is a result of `options` having a value of `None`.

Instead of `options:` it should be specified as `options: {}`

`options` is allowed to be `None`, but only when not in combination of `extends_documentation_fragment`

**Comment by mattclay** [comment]
@sivel Is there anything easy we can do in the module validator to make that kind of error more self explanatory?

**Comment by sivel** [comment]
> @sivel Is there anything easy we can do in the module validator to make that kind of error more self explanatory?

Yes, there is a bug in `get_docstring`:

```
diff --git a/lib/ansible/utils/module_docs.py b/lib/ansible/utils/module_docs.py
index 47e0b59..b7ffcda 100755
--- a/lib/ansible/utils/module_docs.py
+++ b/lib/ansible/utils/module_docs.py
@@ -117,7 +117,7 @@ def get_docstring(filename, verbose=False):
                                     elif isinstance(doc[key], MutableSequence):
                                         doc[key] = sorted(frozenset(doc[key] + value))
                                     else:
-                                        raise Exception("Attempt to extend a documentation fragement (%s) of unknown type: %s" (fragment_name, filename))
+                                        raise Exception("Attempt to extend a documentation fragement (%s) of unknown type: %s" % (fragment_name, filename))
 
                     elif 'EXAMPLES' == theid:
                         plainexamples = child.value.s[1:]  # Skip first empty line
```

However, there may be things we can do in the validator, to check the schema of `options` to ensure it is a `dict` when `extends_documentation_fragment` is also present.

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Pull request merged**
