### PR TITLE
Update ec2_lc with missing LaunchConfig params

### PR DESCRIPTION
**Pull request by terretta**
Add support for instance_profile_name and associate_public_ip_address.

### CODE REVIEW

**Comment by jimi-c** [comment]
Both of these fields need a version_added property (set to 1.7).

**Comment by aknapp** [comment]
Any chance of this getting merged?

**Comment by jimi-c** [comment]
Hi @aknapp, I actually merged in #7997, which would seem to have a lot of crossover functionality with this (but also added even more params). If you agree, we can close this PR out.

**Comment by aknapp** [comment]
Looks good to me, feel free to close this. Thanks!

**Comment by jimi-c** [comment]
Will do, thanks!

**Pull request closed without merging**
