### PR TITLE
Generate plugin rst

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY
tweaks to plugin_formatter and templates to generate rst docs for plugins

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

docs/docsite/

##### ANSIBLE VERSION

```
ansible 2.4.0 (generate_plugin_rst bfdf018bc2) last updated 2017/08/31 16:25:02 (GMT -400)
  config file = /home/adrian/src/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by mattclay** [comment]
bot_status

**Comment by abadger** [comment]
Provisional support to cherry-picking this to 2.4.0rc2 (I will be cutting rc2 on Wednesday).

Bcoca and dharmabumstead approved that plan but would like to see the final form that is merged into devel.  If this isn't in before rc2 is cut we'll have to consider whether it should go into rc3 or not.

**Comment by alikins** [comment]
the active version of this is at https://github.com/ansible/ansible/compare/devel...alikins:generate_plugin_rst_config_4  (rebased ontop  of https://github.com/ansible/ansible/pull/29542).

**Comment by alikins** [comment]
now rebased against current devel (so generate_plugin_rst_config_4 can be ignored now...)

**Pull request merged**
