### PR TITLE
Make ansible-vault view not write plaintext to a tempfile

### PR DESCRIPTION
**Pull request by amenonsen**
…when it can just feed the PAGER on stdin instead.

### CODE REVIEW

**Comment by bcoca** [comment]
nice

**Comment by bcoca** [comment]
you could also just feed self.pager() function in the cli

**Comment by amenonsen** [comment]
@bcoca thanks for the suggestion, I didn't notice CLI's `pager()` method. I've pushed a revised version along those lines (and tested it with single/multiple files, with more/less/nonexistent-pager and so on).

**Comment by bcoca** [comment]
he, even nicer that we get to remove soo many lines

**Pull request merged**
