### PR TITLE
Aws secrets on missing

### PR DESCRIPTION
**Pull request by rene1977**
##### SUMMARY
Add "on_missing" option for aws_secret lookup. This option controls how to handle a not existing secret (ResourceNotFoundException). Naming based on "config" lookup.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
aws_secret

##### ADDITIONAL INFORMATION
The option "on_missing" can be set to:

- 'error' - return a fatal error (default, old behavior)
- 'warn' - return empty list and print the warning "[WARNING]: Skipping, did not find secret ..."
- 'skip' - return empty list

playbook:
```
---
- name: aws_secret lookup
  hosts:
    - "localhost"
  gather_facts: no
  tasks:
    - debug:
        var: bla
      vars:
        bla: "{{ lookup('aws_secret','non-existing-secret',region='eu-west-1') }}"
```

before:
```
TASK [debug] ********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('aws_secret','non-existing-secret',region='eu-west-1') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'aws_secret'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to retrieve secret: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret."}
```

after with option "on_missing='warn'":
```
PLAY [aws_secret lookups] *******************************************************************************************************************
[WARNING]: Skipping, did not find secret non-existing-secret


TASK [debug] ********************************************************************************************************************************
ok: [localhost] => {
    "bla": []
}
```

### CODE REVIEW

**Comment by rene1977** [comment]
bot_status

**Comment by rene1977** [comment]
ready_for_review

**Comment by rene1977** [comment]
Info from markuman in IRC:

> it's too late to merge it in this repository. ansible is made a big split.
https://github.com/ansible-collections/community.amazon
in the near future, most aws related pr will end up here

**Comment by flowerysong** [comment]
The setting in the config module that you based this on predates the more generic control over lookup error handling that was added in Ansible 2.6, which doesn't require any code changes within plugins.

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "query('aws_secret','non-existing-secret',region='eu-west-1', errors='ignore')": []
}

TASK [debug] *******************************************************************
[WARNING]: An unhandled exception occurred while running the lookup plugin
'aws_secret'. Error was a <class 'ansible.errors.AnsibleError'>, original
message: Failed to retrieve secret: An error occurred
(ResourceNotFoundException) when calling the GetSecretValue operation: Secrets
Manager can't find the specified secret.
ok: [localhost] => {
    "query('aws_secret','non-existing-secret',region='eu-west-1', errors='warn')": []
}

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'aws_secret'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to retrieve secret: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret."}
```

**Comment by rene1977** [comment]
@flowerysong 
Thank you for the info about the generic lookup error setting. I guess in this case even a ignore_errors to the task would work.
But working with optional configured secrets and also handle missing permissions does not mean that i wanna ignore all kinds of errors. For me it makes sense to have a finer control about the return conditions.
I am still interested to merge that upstream so i will close here and try open it on the right place.

**Pull request closed without merging**
