### PR TITLE
add hw_disks to vmware_guest_facts data

### PR DESCRIPTION
**Pull request by phemmer**
##### SUMMARY

This adds a `hw_disks` attribute to the output of `vmware_guest_facts`.
The format of each element in the list can be directly consumed by the `vmware_guest` module `disk` parameter. This provides a mechanism for discovering the existing disk configuration so that you can modify it (ref #39321).

```json
            "hw_disks": [
                {
                    "datastore": "FLL2-ENT-UNITY-02", 
                    "size_kb": 512000, 
                    "type": "thin"
                }, 
                {
                    "datastore": "FLL2-ENT-UNITY-02", 
                    "size_kb": 12582912, 
                    "type": "thin"
                }
            ], 
```

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

vmware_guest_facts

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /Users/phemmer/git/c14n-platform/ansible.cfg
  configured module search path = [u'/Users/phemmer/git/c14n-platform/library']
  ansible python module location = /Users/phemmer/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /Users/phemmer/ansible-2.5/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### ADDITIONAL INFORMATION
The example usage for my use case where I wanted to clone a VM from a template, and set the `autoselect_datastore` param, looks like this:

```yaml
vmware_guest_facts:
  name: mytemplate
  register: template

vmware_guest:
  template: mytemplate
  disk: '{{template.instance.hw_disks|map("combine",{"datastore":None,"autoselect_datastore":True})|list}}'
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@phemmer Thanks for the PR. There is already a module which provides disk informations of already existing VMs and Templates - [`vmware_guest_disk_facts`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_disk_facts.py). Let me know if satisfies your requirement. 

needs_info

**Comment by phemmer** [comment]
>There is already a module which provides disk informations of already existing VMs and Templates - vmware_guest_disk_facts 

Ah, I see this is a new module not in 2.5. However now I question why this is a separate module. I don't think it makes sense to have a `vmware_guest_network_facts`, `network_guest_cdrom_facts`, etc.

There's also a few issues with it for which I added comments to the [implementation pr (#36026)](https://github.com/ansible/ansible/pull/36026#pullrequestreview-115595839).

Aside from those issues, it might work. I'll need to write a custom filter to transform the output into something `vmware_guest` can use (it would be better if they shared the same keys), which is a nuisance, but minor (for me anyway, it might be major for others who don't know python).

**Comment by Akasurde** [comment]
Yes. This is new module in 2.6.

I think the idea behind separate module is to keep things simple and "do one thing and do it perfectly" philosophy. We have seen performance related issues when you have 10K+ VMs and you are trying to gather lot of facts in single module itself. So, rather than asking for everything at once from large number of VMs, it is better to ask for limited amount of information.

One might not need information about disks while using vmware_guest_facts but if one does then will use `vmware_guest_disk_facts`.

Let me know if it make sense.

**Comment by Akasurde** [comment]
@phemmer any news ? needs_info

**Pull request closed without merging**
