### PR TITLE
Added gce_img_facts module.

### PR DESCRIPTION
**Pull request by Rahul-CSI**
##### SUMMARY

Added a module gce_facts to collect the google cloud instance facts.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

gce_img_facts

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### ADDITIONAL INFORMATION
The gce_img_facts module collects the GCE Image facts.
A list containing each image info as a dictionary.

Module accepts filter parameter, which have following options
and each option can have python regular expression to filter the images.
- archiveSizeBytes: Archived image size in bytes.
- creationTimestamp: Image creation timestamp.
- description: Desciption.
- diskSizeGb: Boot disk size in Gb.
- family: Image family.
- id: Image id.
- name: Image name.
- selfLink: Image self link.
- sourceDisk: Source disk of image.
- sourceDiskId: Id of source disk of image.
- sourceType: Type of source disk.
- status: Status of image.

The module returns facts which include below information per image.
- Archived image size in bytes.
- Image creation timestamp.
- Description of the image.
- Boot disk size in Gb.
- Image family.
- ID of the image.
- Image license details.
- Name of the image.
- Raw disk details.
- Link to image.
- Source disk from which this disk is created.
- Id of the source disk.
- Type of the source disk.
- Status of the disk.

```

```

### CODE REVIEW

**Comment by varunchopra** [comment]
Shouldn't we be using strings in snake case instead?

**Comment by Rahul-CSI** [comment]
@chopraaa 

Can you please explain where we need to use strings in snake case?
What is snake case?

**Comment by Rahul-CSI** [comment]
@rambleraptor Could you please review this PR?

**Comment by varunchopra** [comment]
@Rahul-CSI This is `snake_case`. What you're using is `camelCase`.

I see a lot of things wrong with this but I'll leave it up to the maintainers to review.

**Comment by rambleraptor** [comment]
Hello! Now that `gcp_compute_image_facts` exists, is this module still needed?

**Comment by Akasurde** [comment]
@Rahul-CSI Thanks for the contribution. Like @rambleraptor said there is a module `gcp_compute_image_info.py` to handle this. Thanks.

**Pull request closed without merging**
