### PR TITLE
Let authorized_keys be tested on python 3

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

test of authorized_keys

### CODE REVIEW

**Comment by mscherer** [comment]
So the wide try/except on https://github.com/ansible/ansible-modules-core/blob/devel/system/authorized_key.py#L263 is masking a python 3 error (and is quite unhelpful. I guess we should first fix that either by removing try/execpt here, or by using at least a better message.

**Comment by mscherer** [comment]
So https://github.com/ansible/ansible-modules-core/pull/5276

**Comment by mscherer** [comment]
So now, we see the traceback:

```
Traceback (most recent call last): 
  File "/tmp/ansible_fhootp1e/ansible_module_authorized_key.py", line 496, in <module> 
    main() 
  File "/tmp/ansible_fhootp1e/ansible_module_authorized_key.py", line 490, in main 
    results = enforce_state(module, module.params) 
  File "/tmp/ansible_fhootp1e/ansible_module_authorized_key.py", line 410, in enforce_state 
    parsed_new_key = parsekey(module, new_key) 
  File "/tmp/ansible_fhootp1e/ansible_module_authorized_key.py", line 308, in parsekey 
    options = parseoptions(module, options) 
  File "/tmp/ansible_fhootp1e/ansible_module_authorized_key.py", line 253, in parseoptions 
    if options_dict.has_key(key): 
AttributeError: 'keydict' object has no attribute 'has_key'
```

**Comment by mscherer** [comment]
Now, new trace back:

```
Traceback (most recent call last):
  File "/tmp/ansible_sh16ejbd/ansible_module_authorized_key.py", line 496, in <module>
    main()
  File "/tmp/ansible_sh16ejbd/ansible_module_authorized_key.py", line 490, in main
    results = enforce_state(module, module.params)
  File "/tmp/ansible_sh16ejbd/ansible_module_authorized_key.py", line 410, in enforce_state
    parsed_new_key = parsekey(module, new_key)
  File "/tmp/ansible_sh16ejbd/ansible_module_authorized_key.py", line 308, in parsekey
    options = parseoptions(module, options)
  File "/tmp/ansible_sh16ejbd/ansible_module_authorized_key.py", line 259, in parseoptions
    options_dict[key] = value
  File "/tmp/ansible_sh16ejbd/ansible_module_authorized_key.py", line 164, in __setitem__
    self.itemlist.append(key)
AttributeError: 'dict_keys' object has no attribute 'append'
```

This one is a bit more complex to fix, as dict changed a lot in python3.

**Comment by abadger** [comment]
Fix for authorized_keys is in.  Merging this.  If it passes on devel I'll merge the fix and the test enabling to stable-2.2.

**Comment by abadger** [comment]
Merged to devel and stable-2.2

**Pull request merged**
