### PR TITLE
[WIP] test runner: do coverage-related injection only if needed

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

Make the test runner (`ansible-test`) use `inject_command()` only when
needed, that is, when the `--coverage` flag is used. This function
messes up with paths, interpreters and stuff, causing problems in some
situations.

This commit introduces `inject_command_if_needed()`, which calls
`inject_command()` only when `--coverage` is set, otherwise calls
`run_command()` directly.

I've been trying to run `connection_lxd` integration test, which is a
bit harder than others to run because it's not part of `posix/ci` (or
any other alias for that matter) and I've been doing so from within a
virtualenv. The test was failing because of that injection thing.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
test runner

##### ANSIBLE VERSION

```
ansible-playbook 2.4.0
  config file = None
  configured module search path = [u'/home/vdupras/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vdupras/src/ansible/.tox/py27/lib/python2.7/site-packages/ansible
  executable location = /home/vdupras/src/ansible/.tox/py27/bin/ansible-playbook
  python version = 2.7.12 (default, Jun  9 2017, 11:18:57) [GCC 5.4.0]
```

##### ADDITIONAL INFORMATION

One way to reproduce the problem is to run `container_lxd` trough a virtualenv, after having properly set up a `centos-7-amd64` LXD container.

```
$ . .tox/py27/bin/activate
$ ./test/runner/ansible-test integration --local connection_lxd
...

TASK [remove remote file with unicode filename and content] ***************************************************************************************************
fatal: [lxd-pipelining]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/bin/sh: /tmp/ansible-test-coverage-RNxgFb/coverage/injector.py: No such file or directory\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 127}
```

And with this fix:

```
$ ./test/runner/ansible-test integration --local connection_lxd

...

PLAY RECAP ****************************************************************************************************************************************************
lxd-no-pipelining          : ok=11   changed=8    unreachable=0    failed=0
lxd-pipelining             : ok=11   changed=8    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by ghost** [comment]
Oops, regression. Will fix soon.

**Comment by nitzmahone** [comment]
cc @mattclay

**Comment by mattclay** [comment]
The connection_lxd test is out-of-date. It hasn't been updated since we migrated to ansible-test.

To fix the test, the script just needs to include: `ANSIBLE_TEST_REMOTE_INTERPRETER=''`

No changes to ansible-test are required.

**Comment by ghost** [comment]
@mattclay done in #27421. Closing this PR.

**Pull request closed without merging**
