### PR TITLE
datadog_event module: submit your events to DataDog service.

### PR DESCRIPTION
**Pull request by arturaz**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good -- quick question though.

Is source type name fixed in their API?  I didn't see an Ansible :), and if not, I'm wondering if it could just be a free text field

**Comment by arturaz** [comment]
Yup, its fixed. Used for icons and stuff.

**Comment by mpdehaan** [comment]
merged then, maybe you can submit an RFE on that part :)

**Comment by mpdehaan** [comment]
thanks!

**Comment by arturaz** [comment]
RFE? :)

**Pull request merged**
