### PR TITLE
don't set default:None in documentation when there is no default

### PR DESCRIPTION
**Pull request by evgeni**
##### SUMMARY
otherwise "None" will be rendered as a string on docsite

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by evgeni** [comment]
!needs_revision

**Comment by Fred-sun** [comment]
@MyronFanQiu @yungezz This PR just changed the document, please help to review and push the merge. Thank you very much!

**Comment by yungezz** [comment]
@Fred-sun no related with azure.

**Comment by Fred-sun** [comment]
Yes,  I will pay special attention to the lib/ansible/module/cloud/azure module with azure label in future. Thank you very much!

**Comment by acozine** [comment]
Thanks @evgeni for the PR to improve the Ansible documentation. I'm going to try rebasing this and see if I can get it ready for merge.

**Comment by evgeni** [comment]
Thanks! Didn't notice it needs a rebase (and GH doesn't send mails on label changes).

**Comment by acozine** [comment]
Failures look unrelated. I've kicked off a fresh CI run.

**Comment by acozine** [comment]
Passing CI at last! Thanks again @evgeni.

**Pull request merged**
