### PR TITLE
Skip objects that were removed during getting object names with get_a…

### LINKED ISSUE #37254: vmware.py:find_vm_by_id() fails when a VM is deleted from the folder
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
2.4
```

##### SUMMARY

vmware.py:find_vm_by_id() fails when a VM is deleted from the folder during the search. The relevant piece of code:
* https://github.com/ansible/ansible/blob/5e827f4cc437bf3529da7fb0ff66875570c14c39/lib/ansible/module_utils/vmware.py#L215-L228

Technically, when looping  for f_obj.childEntity, a VM may get deleted from the folder during the looping. The piece of code referenced above does not catch the resulting exception and makes the search fail. The exception has the msg " 'The object has already been deleted or has not been completely created'". Note! it's not about deleting the VM which is being searched, but any of the other VMs in that same folder. Of course the bug appears only sporadically.

A similar issue has been faced in vmware/pyvmomi#445

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
The find does not fail.

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by wojciechkopciewicz**
…ll_objs. Fixes #37254

##### SUMMARY

Skipping objects that were removed during get_all_objs lifetime.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

module_utils/vmware.py

##### ANSIBLE VERSION

```
ansible 2.6.0dev0 (devel 4c1673d012) last updated 2018/05/22 14:43:02 (GMT +200)
  config file = None
  configured module search path = [u'/home/wojtek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/wojtek/tools/ansible/lib/ansible
  executable location = /home/wojtek/tools/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@pdellaert @dericcrago Could you please review this ?

**Comment by wojciechkopciewicz** [comment]
@Akasurde  @pdellaert @dericcrago @karniemi
I fixed some other places that seem to have the same problem.

**Comment by sumkincpp** [comment]
@wojciechkopciewicz  Are you still interested in this PR? This needs to be rebased.

**Pull request closed without merging**
