### PR TITLE
- make extra-vars override all other vars and facts in playbooks

### PR DESCRIPTION
**Pull request by skvidal**
I think this should cover fact/play injection properly.

### CODE REVIEW

**Comment by mpdehaan** [comment]
In queue for testing for Friday, as this is a bugfix I want to include this _for_ 1.0, if others want to pound on it that is also welcome.

Thanks!

**Comment by dhozac** [comment]
The _run_play hunk looks bogus to me. SETUP_CACHE is indexed by hostname, so play.vars doesn't look right there. Putting all of play.vars in SETUP_CACHE would be wrong too. Would this handle overriding inventory vars in a play without gathering facts for the first action, since it applies extra_vars after running, instead of before?

**Comment by mpdehaan** [comment]
nice review.

yep, 
-        self.SETUP_CACHE.update(play.vars) 

should probably be 
-        self.SETUP_CACHE[host].update(play.vars)

so update each host.

and yes, do it each time rather than in gather_facts, gather_facts does not need arguments so much anyway.   If concerned it could be a step between gather_facts and the tasks, but it doesn't seem to need that.

**Comment by mpdehaan** [comment]
The play.vars concern is probably about overwriting something, I would be tempted to pass extra_vars down and do that explicitly with just those.

**Comment by dhozac** [comment]
I've tested this some, and it does appear to work, even in the inventory case I was concerned about. Just dropping the _run_play hunk should fix the only issue here.

**Comment by mpdehaan** [comment]
great

**Comment by skvidal** [comment]
between those two comments I'm a bit confused - what changes do you want made?

**Comment by dhozac** [comment]
Just remove the self.SETUP_CACHE.update(play.vars) from _run_play, and I'll merge this. (Would break hostvars iteration.)

**Comment by skvidal** [comment]
Updated the PR. Lemme know if that is everything and thank you both for the review.

**Comment by dhozac** [comment]
Looks good. Thanks!

**Pull request merged**
