### PR TITLE
Vultr: Introducing vultr_block_storage_facts module

### PR DESCRIPTION
**Pull request by Spredzy**
##### SUMMARY

This commit introduces a new module called vultr_block_storage_facts.          
                                                                            
This module aims to return the list of block storage volume avaiable        
in Vultr.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

  - vultr_block_storage_facts

##### ANSIBLE VERSION

  - devel

##### ADDITIONAL INFORMATION

  - N/A

### CODE REVIEW

**Comment by Spredzy** [comment]
Depends-On: https://github.com/ansible/ansible/pull/43202

**Review by resmo — COMMENTED** [review]
needs rebase but otherwise looks good to me

**Comment by Spredzy** [comment]
@resmo PR has been rebased

**Review by resmo — APPROVED** [review]
shipit

**Pull request merged**
