### PR TITLE
Add an option to stack filters in EC2 inventory script.

### PR DESCRIPTION
**Pull request by ikalinin**
Added an option to stack filters in EC2 inventory script.

### CODE REVIEW

**Comment by ikalinin** [comment]
Thanks for catching that, it's fixed now!

**Comment by aioue** [comment]
Related: #14901

**Comment by ryansb** [comment]
Closed and reopened to kick shippable into gear.

**Comment by ryansb** [comment]
Merged as https://github.com/ansible/ansible/commit/259b05dd8e706d1e3b548f72481cea74c3ecc6d6

**Pull request closed without merging**
