### PR TITLE
nxos_facts: cdp support

### PR DESCRIPTION
**Pull request by chifu1234**
##### SUMMARY
It is simply a copy of lldp protocol and ipv6 interfaces.
Testet with N77k

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Name of the /module/nxos/nxos_facts.py 

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/home/void/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 18 2017, 08:48:18) [GCC 6.3.0]
```

### CODE REVIEW

**Comment by chifu1234** [comment]
Should we add cdp information to the lldp fact, since it is basically the same. We could add an attribute source in ansible_net_neighbors with value cdp/lldp ?

**Comment by gundalow** [comment]
@chifu1234 We discussed this in the Network IRC meeting (2017-10-05), yes these should be added to `ansible_net_neighbors`

**Comment by chifu1234** [comment]
@gundalow This output OK?:   
```
  "ansible_net_neighbors": [
            {
                "Eth5/9": [
                    {
                        "host": "xxx", 
                        "port": "Eth5/37", 
                        "source": "lldp"
                    }
                ], 
                "Eth6/9": [
                    {
                        "host": "xxx", 
                        "port": "Eth6/37", 
                        "source": "lldp"
                    }
                ]
            }, 
            {
                "Ethernet5/9": [
                    {
                        "host": "xxxx", 
                        "port": "Ethernet5/37", 
                        "source": "cdp"
                    }
                ], 
                "Ethernet6/9": [
                    {
                        "host": "xxx", 
                        "port": "Ethernet6/37", 
                        "source": "cdp"
                    }
                ], 
                "mgmt0": [
                    {
                        "host": "xxx", 
                        "port": "GigabitEthernet0/37", 
                        "source": "cdp"
                    }
                ]
            }
        ], 
```

**Comment by gundalow** [comment]
@chifu1234 Do you think listing the source is needed?

**Comment by gundalow** [comment]
@chifu1234 Do you think listing the source is needed?

**Comment by chifu1234** [comment]
@gundalow No i think its not. Will update the code today. Should I update the Documentation too?

**Comment by gundalow** [comment]
@chifu1234 Yes please.
Also real world `EXAMPLES` are also useful.

**Comment by chifu1234** [comment]
@gundalow I dont know if I understand you right, but I think examples are not necessary - the users can't handle the behavior for cdp nor lldp.

**Comment by gundalow** [comment]
@chifu1234 Do the updates to the documentation as you see fit then we can review again. This looks fairly close to getting merged. Thanks again.

**Pull request merged**
