### PR TITLE
Integration test suite: retry in a new environment

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
When delegated and retry-on-error enabled, if a failure occurs, retry in a clean environment.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ansible-test

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 9c5b55232c) last updated 2017/05/07 23:45:07 (GMT +200)
```

### CODE REVIEW

**Comment by mattclay** [comment]
@pilou- What problem are you trying to solve with this change? If an individual test fails, it should be able to be re-run with the environment as-is. If that's not the case, then that is an issue that should be resolved with the test. This is often done by using block/always logic in the test playbook, but in some cases can be done during test setup at the start of the playbook.

**Comment by pilou-** [comment]
@mattclay Tasks of destructive targets modify the environment, then the result of the second pass might differs. This is the case for the postgresql target ([see](https://github.com/ansible/ansible/pull/23686#issuecomment-299747079)).

The purpose of the second run is to execute tasks with a more verbose log level in order to be able to analyse failure. Logs aren't usable if the execution path of the second run differs from the execution path of the first run.

This pull request allows to ensure that logs are usable: second run is executed in a clean/fresh environment which is the same the previous one.

**Comment by mattclay** [comment]
@pilou- Just because a test is destructive does not mean it should be unable to be repeated in the same environment a second time. The postgresql test should make sure that the database is initialized as required for the test, whether it is being run the first or second time.

**Comment by pilou-** [comment]
Indeed, it does not mean that. But requiring that destructive tests are idempotent and check/clean the environment is a constraining requirements, making them more complicated. Using a new environment seems more reliable than assuming tests are doing the right thing.

**Comment by mattclay** [comment]
If the test cannot be run a second time, it's already making assumptions about the environment that may not be true the first time. Although our CI process runs integration tests in our docker containers or on fresh EC2 instances, those are not the only supported scenarios. We also make a reasonable effort to support running the tests in a user provided environment, assuming the environment provides basic dependencies required for the tests.

**Comment by pilou-** [comment]
Is this proposal incompatible with other supported scenarios ?

I agree tests should not make assumptions about the environment, but this behavior isn't tested or guaranteed.

When a Debian/Ubuntu package is installed the first time, it could run some post install scripts which would not be executed again if the package hasn't been purged first. When removing a package, the `package` ansible module doesn't allow to purge it. Hence in order to be idempotent, for each `package` task of destructive tests, a specific case for Debian and Ubuntu environment should be added. Even if only a few target are currently concerned, it doesn't seem straightforward.

An improvement of this proposal could be to use the proposed behavior only when destructive targets are tested.

**Comment by mattclay** [comment]
Idempotence for integration tests needs to be handled by the integration tests.

No integration test is guaranteed to have a clean environment. Only the first test run with remote or docker delegation receives a clean environment. All other tests run in a dirty environment, due to changes made by preceding tests. Using a clean environment for the first test retried when using only docker delegation still leaves the integration tests to handle the situation in all other scenarios.

There's not really much point in trying to resolve the issue in ansible-test when it's unavoidable that the issue needs to be resolved in the integration tests themselves.

**Comment by mattclay** [comment]
This was discussed further on IRC. Thanks @pilou- for this PR and for volunteering to document the requirement that tests be repeatable in the same environment.

I'm closing this PR since the approach we should take is to make integration tests repeatable, rather than providing a clean environment on retry.

**Pull request closed without merging**
