### PR TITLE
oom_killer and oom_score_adj are available since docker-py 1.8.0.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The `oom_killer` and `oom_score_adj` options have been available in docker-py since 1.8.0 (and before), and not since 2.0.0 as claimed in #47711. Adjusting the values accordingly.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by WojciechowskiPiotr** [comment]
shipit

**Review by resmo — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
@WojciechowskiPiotr @resmo thanks for reviewing this!

**Pull request merged**
