### PR TITLE
Update env-setup

### PR DESCRIPTION
**Pull request by lonico**
Make it easier to run UTs locally, and to resolve units.compat.

##### SUMMARY

With Ansible 2.7, I could run Unit Tests locally using:
```
python -tt <path_to_ut_file>
```
With Ansible 2.8, this fails because units.compat cannot be resolved.
```
Traceback (most recent call last):
  File "ansible/test/units/modules/storage/netapp/test_na_ontap_flexcache.py", line 12, in <module>
    from units.compat import unittest
ModuleNotFoundError: No module named 'units'
```

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

hacking

##### ANSIBLE VERSION

```paste below
2.8.0.dev0
```

##### ADDITIONAL INFORMATION

```
source source ansible/hacking/env-setup
python -tt <path_to_ut_file>

(ansible28) launicolas (feature/DEVOPS-1024-private-set-up-my-own-vsim-using *) ansible-playbooks $ python -tt ansible/test/units/modules/storage/netapp/test_na_ontap_flexcache.py 
Create: AnsibleExitJson({'changed': True},)
.b'<xml><attributes-list><flexcache-info><vserver/><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info></attributes-list><num-records>1</num-records></xml>'
b'<xml><attributes-list><flexcache-info><vserver/><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info></attributes-list><num-records>1</num-records></xml>'
Create: AnsibleExitJson({'changed': False},)
.b'<xml><attributes-list><flexcache-info><vserver>flex</vserver><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info></attributes-list><num-records>1</num-records></xml>'
b'<xml><attributes-list><flexcache-info><vserver>flex</vserver><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info></attributes-list><num-records>1</num-records></xml>'
b'<xml><attributes-list><flexcache-info><vserver>flex</vserver><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info></attributes-list><num-records>1</num-records></xml>'
Delete: AnsibleExitJson({'changed': True},)
.Delete: AnsibleExitJson({'changed': False},)
.b'<xml><attributes-list><flexcache-info><vserver/><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info></attributes-list><num-records>1</num-records></xml>'
info: {'origin_cluster': 'ocluster', 'origin_volume': 'ovolume', 'origin_vserver': 'ovserver', 'size': None, 'volume': 'volume', 'vserver': None}
.b'<xml><attributes-list><flexcache-info><vserver>repeats</vserver><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info><flexcache-info><vserver>repeats</vserver><origin-vserver>ovserver</origin-vserver><origin-volume>ovolume</origin-volume><origin-cluster>ocluster</origin-cluster><volume>volume</volume></flexcache-info></attributes-list><num-records>2</num-records></xml>'
...Info: missing required arguments: hostname, username, password, volume, vserver
.
----------------------------------------------------------------------
Ran 9 tests in 0.015s

OK

```
```

### CODE REVIEW

**Comment by gundalow** [comment]
Hi,
Are you aware that `ansible-test` (which is in the $PATH) can be used to do this, and it understand requirements.txt?

https://docs.ansible.com/ansible/devel/dev_guide/testing_units.html#testing-units

**Comment by lonico** [comment]
> Hi,
> Are you aware that `ansible-test` (which is in the $PATH) can be used to do this, and it understand requirements.txt?
> 
> https://docs.ansible.com/ansible/devel/dev_guide/testing_units.html#testing-units

Yes, and no.

Yes, we are using ansible-test in our CI pipeline, and we run the pipeline on all of our branches.

No, I don't use ansible-test in my development environment.   It's one more thing to remember.   It's easier and faster for me to run the UT directly when debugging a new testcase or feature.  Once I push the changes to my branch on our git repo, our Jenkins pipeline is automatically triggered and will run all our UTs using ansible-test for all supported python versions.

If I use ansible-test (with docker), it takes around 30 seconds to run a simple test.  Here is a best case:
```
time ansible-test units --python 2.7 --docker default na_ontap_cluster

real    0m25.307s
```

while I can run the same test in a second:
```
time python -tt  ansible/test/units/modules/storage/netapp/test_na_ontap_cluster.py -b
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK

real    0m0.400s
```

There is still a lot of value for ansible-test,  for instance if I wanted to test on a different version of python than the one I installed.   But most of it can be done in our pipeline.

**Comment by bcoca** [comment]
just run `make tests` which triggers ansible-test unit testing (i keep shortcuts in Makefile)

**Review by bcoca — CHANGES_REQUESTED** [review]
I would not add this to the pythonpath as it might unintentionally inject test code into the main ansible execution.

**Comment by mattclay** [comment]
@lonico You can run the unit tests faster using ansible-test without Docker:

`ansible-test units --python 2.7 na_ontap_cluster`

If you really want to run them without ansible-test, I suggest running pytest directly:

`pytest <path_to_ut_file>`

or

`python -m pytest <path_to_ut_file>`

All of those will work without adding anything else to the PYTHONPATH.

**Comment by lonico** [comment]
@bcoca  I agree with your point about PYTHONPATH.
@mattclay  I had to install pytest, but I can't argue with that.  This is good for me.

**Comment by lonico** [comment]
Seems better not to modify PYTHONPATH, and pytest is a good alternative.

**Pull request closed without merging**
