### PR TITLE
Fix azure_rm_keyvaultkey/azure_rm_keyvaultsecret bugs

### PR DESCRIPTION
**Pull request by yungezz**
##### SUMMARY

azure keyvault tests was failed because
1. added to wrong group
2. try to access invalid tenant configuration
3. bugs in azure key vault key/secrets

Fix issue #39624 #39625 #40976

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

integration tests of azure key vault.

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/yungez/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### ADDITIONAL INFORMATION

@yuwzho  @zikalino 

```

```

### CODE REVIEW

**Comment by yungezz** [comment]
@mattclay Hi Matt, @nitzmahone  suggested I put the azure service principal object id  lookup plugin inside test because that plugin should not be checkin now, since `cloud as inventory`. Checkin it  into test directly could unblock keyvault bug fixing. I need your help on where  to put the plugin to in test  folder. I tried to put it at same  place of test playbook, but met `plugin not found` error. Could you pls shed some  light? Thanks.

**Comment by yungezz** [comment]
@mattclay  HI Matt, do you have chance to help look at where in test folder to put the azure sp objectid lookup plugin? thanks.

**Comment by mattclay** [comment]
@yungezz Since the test target is just an Ansible role, you should be able to put the lookup plugin in the `lookup_plugins` directory for the test as documented here:

https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout

**Comment by yungezz** [comment]
thank you @mattclay for the instruction!

**Comment by yungezz** [comment]
ready_for_review

**Comment by yungezz** [comment]
@jborean93 @nitzmahone @mattclay

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
