### PR TITLE
cs_vlan_ip_range: Update return values documentation

### PR DESCRIPTION
**Pull request by dpassante**
##### SUMMARY

Some minor changes on return values documentation.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

cs_vlan_ip_range

### CODE REVIEW

**Comment by resmo** [comment]
seems start/end_ipv6 is also missing, isn't it?

**Comment by dpassante** [comment]
Right !

**Comment by dpassante** [comment]
Fixed by the last commit.

**Review by resmo — APPROVED** [review]
shipit

**Pull request merged**
