### PR TITLE
docker_container: add networks_cli_compatible option

### LINKED ISSUE #29558: docker_container networks not working as expected (viz. mac addresses)
From @gfarrell on 2016-10-24T17:33:05Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

[Relevant Docker docs](https://docs.docker.com/engine/reference/run/#/network-settings). Should be able to set mac address for the connected networks (I have my container connected to two networks, but need its mac address set in one of them. Using the `mac_address` configuration option only sets the address in the default bridge network, not in my custom network.
##### STEPS TO REPRODUCE

Try to set mac address on container, fail to do so.

```
- name: start container
  become: false
  docker_container:
    name: blah
    state: started
    restart_policy: always
    image: "{{ blah.image }}"
    env: "{{ blah.environment }}"
    log_opt: "{{ log_opts }}"
    volumes: "{{ blah.volumes }}"
    ports: "{{ blah.ports }}"
    mac_address: "{{ mac_address.stdout }}"
    networks:
        - name: "{{ custom_network_name }}"
          ipv6_address: "{{ blah_ipv6_address }}"
          driver: bridge
```
##### EXPECTED RESULTS

I would expect the custom network to have the mac address specified.
##### ACTUAL RESULTS

Container gets two networks, one being the default bridge, the other being the custom network. Only the former gets the custom mac address.

Copied from original issue: ansible/ansible-modules-core#5371

### LINKED ISSUE #53923: Docker: Change default for purge_networks within docker_container
##### SUMMARY
The default behaviour of docker_container should be equivalent to that of the docker cli command.
I think this should be implemented, even though it is a breaking change for a few people. I consider the breakage to be minor.

It is also the opposite default behaviour compared to docker_network module, where the `connected` list is canonical.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_container

##### ADDITIONAL INFORMATION
#19508

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This is a WIP implementing a new feature described in #53923. Mostly experimental right now.

Fixes #53923, fixes #29558 (when new option is set to `yes`).

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

CC @agowa338

**Comment by agowa338** [comment]
lgtm

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
@agowa338 thanks for reviewing!

**Pull request merged**
