### PR TITLE
Pull request for temp/iosxr-2.7-fixes

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Backports related to iosxr network integration testing for zuul.ansible.com

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible-test iosxr

Depends-On: https://github.com/ansible/ansible/pull/57755

### CODE REVIEW

**Comment by pabelanger** [comment]
This needs changelog fragments, but first need to collect all backports

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 41ecc8cef502c7bbde5e0ecd066d3ab4c6b74685

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now a611ca942ec531c4b65a79a299e5845ac3b03f12

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 0413f43d67fa53d6765b66c07709a449f7e1edef

**Comment by abadger** [comment]
The decision from the networking team leadership is that none of these bugs qualify as critical so we'll have to continue testing stable-2.7 releases manually rather than enabling zuul for 2.7.x

**Pull request closed without merging**
