### PR TITLE
Adding waiter to cluster remove process

### PR DESCRIPTION
**Pull request by inhumantsar**
##### SUMMARY
This PR adds a waiter to the AWS EKS cluster remove process. 

This should make life easier when automating the removal of dependent resources such as Security Groups and Subnets.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
aws_eks_cluster

##### ADDITIONAL INFORMATION
I'm a new contributor, please be nice :)

### CODE REVIEW

**Comment by willthames** [comment]
This looks great - can you update the test suite (test/integration/targets/aws_eks) to use this?

**Comment by inhumantsar** [comment]
@willthames thanks :) added

**Review by willthames — CHANGES_REQUESTED** [review]
This needs version checks - looks like cluster_deleted needs 1.12.38

**Comment by willthames** [comment]
@inhumantsar I've updated the test suite to latest ansible test suite standards

You'll need to add a test to old_version.yml for using wait with state absent for versions older than 1.12.38 and some logic to aws_eks_cluster to ensure that that test passes

**Comment by inhumantsar** [comment]
@willthames would it be reasonable to have Ansible warn and ignore `wait=yes` rather than fail outright?

**Comment by inhumantsar** [comment]
i hate git sometimes

**Comment by willthames** [comment]
@inhumantsar I've fixed up your branch. It's best to ensure you do `git pull --rebase` rather than just git pull.

**Comment by inhumantsar** [comment]
@willthames is there anything more this needs?

**Review by s-hertel — APPROVED** [review]
So nice to have another fixed test suite.

**Comment by willthames** [comment]
This needs to cope with older boto3

```
NotImplementedError: Waiter cluster_deleted could not be found for client <class 'botocore.client.EKS'>. Available waiters: ('EC2', 'route_table_exists'), ('EC2', 'security_group_exists'), ('EC2', 'subnet_exists'), ('EC2', 'subnet_has_map_public'), ('EC2', 'subnet_no_map_public'), ('EC2', 'subnet_has_assign_ipv6'), ('EC2', 'subnet_no_assign_ipv6'), ('EC2', 'subnet_deleted'), ('EC2', 'vpn_gateway_exists'), ('WAF', 'change_token_in_sync'), ('WAFRegional', 'change_token_in_sync'), ('EKS', 'cluster_active'), ('RDS', 'db_instance_stopped')
```

**Comment by willthames** [comment]
Line 249 should probably be `module.fail_json_aws`

**Comment by willthames** [comment]
> This needs to cope with older boto3

That was an incorrect interpretation of what's going wrong, it looks like it just needs the waiter to be added to lib/ansible/module_utils/aws/waiters.py

**Review by willthames — CHANGES_REQUESTED** [review]
I don't think this is working still

```
TASK [aws_eks : remove EKS cluster, waiting until complete] ********************
task path: /root/.ansible/test/tmp/aws_eks-wret1aaz-ÅÑŚÌβŁÈ/test/integration/targets/aws_eks/tasks/full_test.yml:143
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<testhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866 `" && echo ansible-tmp-1565688105.5251505-160042990714866="` echo /root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866 `" ) && sleep 0'
Using module file /root/ansible/lib/ansible/modules/cloud/amazon/aws_eks_cluster.py
<testhost> PUT /root/.ansible/tmp/ansible-local-129o626bk8i/tmpifhnrdz5 TO /root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py
<testhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/ /root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py && sleep 0'
<testhost> EXEC /bin/sh -c 'ANSIBLE_DEBUG_BOTOCORE_LOGS=True /tmp/ansible.sitji5wt.test/virtualenv/bin/python /root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py && sleep 0'
<testhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py", line 139, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py", line 131, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py", line 65, in invoke_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py", line 296, in <module>
  File "/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py", line 292, in main
  File "/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py", line 235, in ensure_absent
  File "/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py", line 258, in wait_until
  File "/tmp/ansible.sitji5wt.test/virtualenv/lib/python3.6/site-packages/botocore/waiter.py", line 329, in wait
    last_response=response
botocore.exceptions.WaiterError: Waiter cluster_deleted failed: Max attempts exceeded

fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py\", line 139, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py\", line 131, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565688105.5251505-160042990714866/AnsiballZ_aws_eks_cluster.py\", line 65, in invoke_module\n    spec.loader.exec_module(module)\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py\", line 296, in <module>\n  File \"/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py\", line 292, in main\n  File \"/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py\", line 235, in ensure_absent\n  File \"/tmp/ansible_aws_eks_cluster_payload_wa5gbqxo/__main__.py\", line 258, in wait_until\n  File \"/tmp/ansible.sitji5wt.test/virtualenv/lib/python3.6/site-packages/botocore/waiter.py\", line 329, in wait\n    last_response=response\nbotocore.exceptions.WaiterError: Waiter cluster_deleted failed: Max attempts exceeded\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

The VPC teardown code immediately after worked fine, which suggests that the EKS cluster had been deleted (if the cluster exists the VPC teardown code always fails), but the waiter didn't correctly notice and timed out.

**Comment by willthames** [comment]
I had a look at the waiter code and fixed the issues. Tests are now passing

**Review by willthames — APPROVED** [review]

**Comment by willthames** [comment]
rebuild_merge

**Comment by willthames** [comment]
Merged, thanks @inhumantsar !

**Comment by inhumantsar** [comment]
Thanks @willthames!

**Pull request merged**
