### PR TITLE
apt over apt-get

### PR DESCRIPTION
**Pull request by mbk87**
apt over apt-get 

+label: apt over apt-get 

##### SUMMARY

apt is preferred method over apt-get

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by jborean93** [comment]
I'm not sure when `apt` was introduced but isn't `apt` just a nicer wrapper around `apt-get`? Sounds like we should have the one that's more compatible with older versions.

**Comment by bcoca** [comment]
maybe a text with 'you might want to use `apt` in newer versions/`apt-get` in older versions'

**Review by samccann — COMMENTED** [review]
This page - https://debian-handbook.info/browse/stable/sect.apt-get.html
 suggests apt is also available for debian. If I'm reading that correctly, can you also change apt-get to apt in the debian section? (same comment will apply about adding a note to say older distributions use apt-get).

**Comment by samccann** [comment]
@mbk87 thanks for your work on Ansible documentation!

**Pull request merged**
