### PR TITLE
If pip install requirements.txt fails, upgrade pip

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
In `stable-2.3` on Windows pip installing the requirements fails with:

```
2017-10-31 11:31:18 Run command: pip install --disable-pip-version-check -c test/runner/requirements/constraints.txt -r test/runner/requirements/windows-integration.txt
<snip>
2017-10-31 11:31:21 Collecting cryptography>=1.3 (from requests-ntlm>=0.3.0->pywinrm>=0.2.1->-c test/runner/requirements/constraints.txt (line 2))
2017-10-31 11:31:21   Downloading cryptography-2.1.2.tar.gz (441kB)
2017-10-31 11:31:21     Complete output from command python setup.py egg_info:
2017-10-31 11:31:21     error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
2017-10-31 11:31:21     
2017-10-31 11:31:21     ----------------------------------------
2017-10-31 11:31:21 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JF_wFZ/cryptography
```

As a **work around** if `generate_pip_install` fails we upgrade pip then retry `generate_pip_install`.

Reviewing this and providing a better fix (if needed) is tracked in https://github.com/ansible/ansible/issues/32398

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by abadger** [comment]
Looks good.  +1

**Review by nitzmahone — APPROVED** [review]
Fix is fine w/ me, at least as a temporary thing...

**Comment by nitzmahone** [comment]
What's with all the pep8 failures- did we accidentally backport some sanity tests or lose a whitelist file? Worst case we could just disable pep8 sanity back here anyway- much more important that we're on top of that in devel.

**Comment by gundalow** [comment]
So pep8 is failing as the messages that pep8 is now pycodestyle is going to STDERR.

Cherry-picking that fix

**Pull request merged**
