### PR TITLE
Allow host like selectors in tags

### PR DESCRIPTION
**Pull request by rektide**
This allows task's tags to to have selectors alike hosts: one can do dbserver:webserver:&bleeding-edge:!stable in a single tag.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you please resubmit this to use with_under_scores rather than camelCase, so it is consistent with the rest of the application?

The evalutatePattern function should probably be renamed something like evaluate_tag_pattern, though I'm also curious if the same logic can be used for both the host pattern and groups code.   Perhaps not.

Thanks!

**Comment by rektide** [comment]
Thanks, apologies for the style mistakes. I too started this with high hopes of shared logic with the host pattern, but I couldn't manage to swing it, never quite understood all the things the host pattern code was doing.

**Comment by mpdehaan** [comment]
Not having them share is probably wise, it probably does have slightly
different things going on (like host ranges).

**Comment by mpdehaan** [comment]
This looks like it needs some changes to make the playbook --list-tags feature understand the new tagging operations.  Can you update this and resubmit?  Thanks!

**Pull request closed without merging**
