### PR TITLE
remove the obsolete TODO comments

### PR DESCRIPTION
**Pull request by beyondacm**
##### SUMMARY
Remove the obsolete TODO comments. 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible/lib/ansible/plugins/connection/winrm.py

##### ADDITIONAL INFORMATION

The pending task of this TODO comment has already resolved in the earlier version,  please check the following commit (https://github.com/ansible/ansible/commit/db83c0e7cdac8e86026eeae5314185c667e6da1c)

### CODE REVIEW

**Review by jborean93 — APPROVED** [review]
Error handling can always be improved but I guess there's no real need to keep the TODO around.

**Comment by beyondacm** [comment]
> Error handling can always be improved but I guess there's no real need to keep the TODO around.

Many thanks! @nitzmahone can you help me to review this PR when you are available?

**Pull request merged**
