### PR TITLE
Update cnos_vrf.py to to fix coverity bug.

### PR DESCRIPTION
**Pull request by amuraleedhar**
(cherry picked from commit ac546457c8bdda12707738dfaa843bf4d791339d)

##### SUMMARY
Cherry-pick #55954 to 2.8.x
This changes are pertaining to fix for coverity bugs ran against cnos modules

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib//ansible/modules/network/cnos/cnos_vrf.py

##### ADDITIONAL INFORMATION
Pasted below is the coverity issue which I am trying address

def map_config_to_obj(module):
229 objs = []
230 output = run_commands(module, {'command': 'show vrf'})
Condition output === None, taking true branch.
null_check: Comparing output to a null-like value implies that output might be null-like.
231 if output is None:
232 module.fail_json(msg='Could not fetch VRF details from device')
CID 80685 (#1 of 1): Bad use of null-like value (FORWARD_NULL)3. property_access: Accessing a property of null-like value output.
233 vrfText = output[0].strip()

### CODE REVIEW

**Comment by abadger** [comment]
Hi, backports need a changelog fragment before being merged.  Once that's added I can merge this for the next 2.8.x release.

**Comment by amuraleedhar** [comment]
Added changelog fragment too

**Comment by amuraleedhar** [comment]
Why it is getting cancelled?

**Comment by abadger** [comment]
It looks like it's happening because you merged instead of rebasing.  Meeting confuses git history and the boy is trained to reject prs that contain merge commits

**Comment by amuraleedhar** [comment]
Messed Up with this I guess

**Comment by amuraleedhar** [comment]
Hi Toshio,

I know I have messed it up.
I have closed that PR and raised a fresh one
Please look at the following PR and merge it.
https://github.com/ansible/ansible/pull/56693

Thanks & Regards

-Anil

**Pull request closed without merging**
