### PR TITLE
Fixes/detect missing filters

### PR DESCRIPTION
**Pull request by ferringb**
The core of this pull request is the 3rd rev; 110d4e2, which adds awareness at the template level of missing filters and allows that error to propagate upwards.  In other words, the following now properly fails:
- hosts: all
  tasks:
  - debug: msg="this should fail {{ ansible_inventory_hostname|missing_filter }}"

The other two revs (dcb7722 and 146e243) fix the underlying test code this uses so they actually are working as intended (ie, undefined variables being an error is being turned on/off).

I will say, I'm not hugely happy w/ the form of the fix here, but until there is better unification of the multiple template functions in the utils.template module, this is kind of the best that comes to mind.

### CODE REVIEW

**Comment by mpdehaan** [comment]
The integer true stuff should not be mixed up with this commit.

Can you please resubmit this pull request including only the change this PR is about?

Thanks!

**Comment by ferringb** [comment]
Grumble... Offhand, I realize you probably get intermixed/crap commits in pull requests semi often- but those deps are actually required per my message above.

Take a look at TestPlaybook.py, specifically _test_playbook_undefined_vars ; then note the test_playbook_undefined_vars3\* tests that were added by this fix.  Those tests fail without the previous two revs (integers and the Runner constants unbinding) being in place.  They're actually required, although it's nonobvious.

Please reopen the pull request (afaik that's doable in github, I just lack the rights).

**Comment by jimi-c** [comment]
If it's required as part of the pull, it should all be sent as one PR then. We can reopen this and close the other one if that's the case.

**Comment by ferringb** [comment]
A question then; given this particular PR- which the first two commits
should go in /anyways/ since they fix shit, and the last builds on it (and
the last is an arguable fix- I'm not happy specifically w/ how I fixed it
since it smells hackish to me), how exactly do y'all prefer this be pushed
to you?

General git interaction in my experience, you split the PR's up and send
each individual topic- which I did here.  The point of that is to
parallelize and ensure the non-arguable fixes go in rather w/out being
being delayed by the potentially arguable topic branch.  Since merging is
the norm here, it doesn't screw up resultant PRs that build from it.

What exactly do y'all prefer for this sort of scenario?  I'm asking since I
expect this is going to come up again- the sort of work I'm doing lately
has involved a fair amount of spelunking the core and sorting issues along
the way for my final goal.

**Comment by jimi-c** [comment]
If one commit depends on another, they should be in the same pull request. Either that, or send one pull request at a time. The main issue here was that one PR included all of the commits while the other didn't, making it superfluous.

**Pull request closed without merging**
