### PR TITLE
ios integration tests to network_cli

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Also fixes some (mostly python3 related) issues with ios modules

##### ISSUE TYPE

 - Tests Pull Request

##### COMPONENT NAME

ios

##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI timed out running tests. I've restarted the tests.

**Comment by gundalow** [comment]
AWS Ios test failing
```
2017-12-15 02:37:19 Run command: ansible -m vyos_command -a 'commands=?' -u vyos -i vyos-1-1-8, -e 'ansible_host=ec2-54-237-229-164.compute-1.amazonaws.com ansible_port=22 ansible_connection=network_cli ansible_ssh_private_key_file=test/cache/id_rsa ansible_network_os=vyos' vyos-1-1-8
2017-12-15 02:37:32 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: socket_path does not exist or cannot be found
2017-12-15 02:37:32 vyos-1-1-8 | FAILED! => {
2017-12-15 02:37:32     "changed": false, 
2017-12-15 02:37:32     "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_AMZJlO/ansible_module_vyos_command.py\", line 233, in <module>\n    main()\n  File \"/tmp/ansible_AMZJlO/ansible_module_vyos_command.py\", line 203, in main\n    responses = run_commands(module, commands)\n  File \"/tmp/ansible_AMZJlO/ansible_modlib.zip/ansible/module_utils/network/vyos/vyos.py\", line 117, in run_commands\n  File \"/tmp/ansible_AMZJlO/ansible_modlib.zip/ansible/module_utils/connection.py\", line 140, in __rpc__\n  File \"/tmp/ansible_AMZJlO/ansible_modlib.zip/ansible/module_utils/connection.py\", line 115, in _exec_jsonrpc\nansible.module_utils.connection.ConnectionError: socket_path does not exist or cannot be found\n", 
2017-12-15 02:37:32     "module_stdout": "", 
2017-12-15 02:37:32     "msg": "MODULE FAILURE", 
2017-12-15 02:37:32     "rc": 0
```

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/30470 will need updating to match this as well

**Review by ganeshrn — APPROVED** [review]

**Review by trishnaguha — APPROVED** [review]

**Comment by bdowling** [comment]
I'd just like to mention that this fix, adding "optional newline" is in contrast to say how ios_config save works by simply sending an extra carriage return with the command, rather than looking for the prompt.  Carriage return also would work at the IOS delete user prompt, vs, y..  Would like to see things like this be consistent one way or the other.  #32744

Also.. it is sending carriage-return, not 'newline' that is being sent.

**Pull request merged**
