### PR TITLE
[stable-2.15] docsite build: upgrade sphinx-ansible-theme and antsibull-core

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #80734 to stable-2.15.

##### ISSUE TYPE
- Docs Pull Request
- Test Pull Request

##### COMPONENT NAME
docsite build

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM

**Comment by sivel** [comment]
Is there a reason this needs to be backported?  In order to backport will also require a container update, and I'd tend to forgo doing so.

**Comment by felixfontein** [comment]
There are two reasons (quoting #80734):

> * The sphinx-ansible-theme upgrade fixes a CSS bug (https://github.com/ansible-community/sphinx_ansible_theme/issues/56).

(We should probably allow the docsite build dependencies to be slightly different from the docsite test dependencies to avoid having to force a container rebuild in such cases.)

> * The antsibull-core upgrade allows the Ansible docsite build to download collections once Ansible Community Galaxy is replaced with the new codebase. This isn't urgent, but could well happen before Ansible 8 (whose docsite is built from the stable-2.15 branch) is EOL.

This can also wait until the plans for migrating to the new Community Galaxy are clearer, especially w.r.t. when exactly the switch happens.

And also here, this is mainly required for the docs build, not the docs sanity test - unfortunately right now both use the same requirements.

**Comment by samccann** [comment]
I would agree this pr backport can wait until Galaxy NG is closer to replacing Galaxy, just in case something else changes and requires another update to antsibull-docs.

**Comment by mattclay** [comment]
Closing, since `docs` is being migrated to https://github.com/ansible/ansible-documentation/ -- The backport should be done there if it is still needed.

**Pull request closed without merging**
