### PR TITLE
Add an "executable" option to the command and shell modules

### PR DESCRIPTION
**Pull request by lllama**
The option will be passed to the Popen object created and will be used to
execute the command instead of the default shell.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good, the docs need to mark this argument as added in 0.9, so if you can update this, it's good to go.

It looks like this in the docstring for both:

```
ssh_key_type:
    required: false
    default: rsa
    version_added: "0.9"
    description: foo
```

**Comment by lllama** [comment]
Added in version_added as required.

Rebased on top of master - apologies if this isn't the right way to do it.

**Comment by dhozac** [comment]
You will want to rebase on devel. master isn't used.

**Comment by lllama** [comment]
Sorry. My mistake - I did rebase on devel. Spotted the "no such branch"
error when trying master.

Felix

On 8 Nov 2012, at 10:16 AM, Daniel Hokka Zakrisson notifications@github.com
wrote:

You will want to rebase on devel. master isn't used.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ansible/ansible/pull/1532#issuecomment-10182542.

**Comment by mpdehaan** [comment]
Hmm, you have a lot of merge commits in the history now, probably from doing a "git merge".

Can you perhaps resubmit this change directly on devel?

It should ideally show up as just a few commits, preferably one.

**Comment by lllama** [comment]
Yes, it seems to have pulled in some merges with the rebase. I'll delete the request and give it another go.

**Pull request closed without merging**
