### PR TITLE
Add move_home option to user module

### PR DESCRIPTION
**Pull request by aclindsa**
This is a first attempt at addressing https://github.com/ansible/ansible/issues/4441

### CODE REVIEW

**Comment by jimi-c** [comment]
@aclindsa Generally we try and use '_' between distinct words, so could you modify this patch to be 'move_home' instead? We will fix 'createhome' later, which appears to be an oversight.

**Comment by aclindsa** [comment]
@jimi-c Ah, I was trying to follow the local 'convention'. How does this look?

**Comment by jimi-c** [comment]
Yep this looks good, in queue for testing.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
