### PR TITLE
Fix task banner with 'actionable' callback when using templates in name

### LINKED ISSUE #31074: when stdout_callback=actionable task names with variables write to log without values
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
callback_plugins        = plugins
stdout_callback         = actionable

##### ANSIBLE VERSION
```
ansible-2.5.0-100.git201709282105.3e7b24069.devel.el7.centos
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/home/bond/_ansible_bug_call/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s -o UserKnownHostsFile=/dev/null
ANSIBLE_SSH_CONTROL_PATH(/home/bond/_ansible_bug_call/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
ANSIBLE_SSH_PIPELINING(/home/bond/_ansible_bug_call/ansible.cfg) = True
DEFAULT_CALLBACK_PLUGIN_PATH(/home/bond/_ansible_bug_call/ansible.cfg) = [u'/home/bond/_ansible_bug_call/plugins']
DEFAULT_FORKS(/home/bond/_ansible_bug_call/ansible.cfg) = 100
DEFAULT_LOG_PATH(/home/bond/_ansible_bug_call/ansible.cfg) = /home/bond/_ansible_bug_call/logs/ansible.log
DEFAULT_REMOTE_PORT(/home/bond/_ansible_bug_call/ansible.cfg) = 48022
DEFAULT_REMOTE_USER(/home/bond/_ansible_bug_call/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/bond/_ansible_bug_call/ansible.cfg) = [u'/home/bond/_ansible_bug_call/core/roles']
DEFAULT_TIMEOUT(/home/bond/_ansible_bug_call/ansible.cfg) = 120
HOST_KEY_CHECKING(/home/bond/_ansible_bug_call/ansible.cfg) = False
PARAMIKO_RECORD_HOST_KEYS(/home/bond/_ansible_bug_call/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/bond/_ansible_bug_call/ansible.cfg) = True
```
##### OS / ENVIRONMENT
Centos 7.4

##### SUMMARY
When i use stdout_callback=actionable task name with variables in screen output and log displayed with variable name, not variable value

##### STEPS TO REPRODUCE
clone test playbook
https://github.com/LuckySB/ansible_bug_stdout_callback_actionable
run test.sh

```
git clone https://github.com/LuckySB/ansible_bug_stdout_callback_actionable
./test.sh

# uncomment stdout_callback=actionable in ansible.cfg
# and run again
./test.sh
```

##### EXPECTED RESULTS
with and without stdout_callback=actionable
```
PLAY [localhost] ******************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************
ok: [localhost]

TASK [test : Normal name] *********************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Normal name"
}

TASK [test : Name with number vars 42] ********************************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with number vars 42"
}

TASK [test : Name with string vars 100] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with string vars 100"
}

TASK [test : Name with function vars 2] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with function vars 2"
}

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=0

```

##### ACTUAL RESULTS
without stdout_callback=actionable
```
PLAY [localhost] ******************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************
ok: [localhost]

TASK [test : Normal name] *********************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Normal name"
}

TASK [test : Name with number vars 42] ********************************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with number vars 42"
}

TASK [test : Name with string vars 100] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with string vars 100"
}

TASK [test : Name with function vars 2] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with function vars 2"
}

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=0

```

with stdout_callback=actionable
```
PLAY [localhost] ******************************************************************************************************************************************************

TASK [test : Normal name] *********************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Normal name"
}

TASK [test : Name with number vars {{number_var}}] ********************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with number vars 42"
}

TASK [test : Name with string vars {{string_var}}] ********************************************************************************************************************
ok: [localhost] => {
    "msg": "Name with string vars 100"
}

TASK [test : Name with function vars {{number_float_var1}}] ***********************************************************************************************************
ok: [localhost] => {
    "msg": "Name with function vars 2"
}

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=0

```

### PR DESCRIPTION
**Pull request by agaffney**
##### SUMMARY
This commit splits apart the `default` callback plugin's `_print_task_banner()` function into functions that can be reused in callback plugins that inherit from `default`. It also uses those new functions in the `actionable` callback plugin to store the properly rendered task banner from the beginning of the task.

This fixes #31074.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
`actionable` and `default` callback plugins

##### ANSIBLE VERSION
```
ansible 2.6.0 (actionable_task_title e0a40582aa) last updated 2018/04/01 18:11:18 (GMT -500)
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by LuckySB** [comment]
merge it  please

**Comment by bcoca** [comment]
shared code should really go into the base class, not the default plugin

**Comment by agaffney** [comment]
While I'd generally agree, this particular shared code contains assumptions about output formatting that aren't necessarily valid outside the `default` callback plugin and other plugins that inherit from it.

**Comment by bcoca** [comment]
which is a good reason for them not to use default for this kind of thing

**Comment by agaffney** [comment]
I've reworked this PR as just a change to `actionable.py` by copying/modifying a few functions from `default.py`.

**Pull request merged**
