### PR TITLE
Mdd ec2 group ec2response except fix

### PR DESCRIPTION
**Pull request by michael-dev2rights**
##### SUMMARY

handle boto.exception.EC2ResponseError exceptions which happen inside ec2_group

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ec2_group module.

##### ANSIBLE VERSION

```
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mikedd/dev/ansible/ansible-add-modules/library']
  ansible python module location = /home/mikedd/dev/ansible/ansible-add-modules/lib/ansible
  executable location = /home/mikedd/dev/ansible/ansible-add-modules/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

based off my old integration test cases https://github.com/ansible/ansible/pull/22499

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests:

```
Error in get_all_security_groups: AWS was not able to validate the provided access credentials\" in result.msg
```

**Comment by michael-dev2rights** [comment]
close/reopen to retrigger CI.

**Comment by michael-dev2rights** [comment]
@s-hertel it looks to me like this PR is now obsolete;  It used to add error checking and test fixes but you and @willthames seem to have made the same changes anyway into devel.  Could you please have a very quick check and confirm then I'll just close it.

**Comment by s-hertel** [comment]
@michael-dev2rights ec2_group has been ported to boto3 so this needs to be rebased, although I think there are several places in this module that still does need to have try/except handling.

**Comment by ryansb** [comment]
Going to close this until it's refactored to the boto3 calls.

**Pull request closed without merging**
