### PR TITLE
added sample output for echo example

### LINKED ISSUE #72701: Example output missing on Getting Started doc
##### SUMMARY

The `echo` example in Getting Started does not include the output.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

intro_getting_started.rst

### PR DESCRIPTION
**Pull request by gdiamond**
##### SUMMARY

Command examples should have example output.  The `run echo command on server` is needed.
Fixes #72701.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

intro_getting_started
docs

### CODE REVIEW

**Review by bmillemathias — APPROVED** [review]
Thanks for adding the output, that's definitively useful for new user.
Where there is `SUCCESS` I have `CHANGED`

Out of curiosity which version of ansible you run

**Comment by gdiamond** [comment]
> Out of curiosity which version of ansible you run

I had some issues getting my development environment set up and had 2.5.1 (default for Ubuntu 18.04 LTS).  I switched to v2.9.15 and upstream/devel (0fa1cd88ce) to get the same output as you. 
```
aserver.example.org | CHANGED | rc=0 >>
hello
```

**Review by gdiamond — COMMENTED** [review]
This is my first PR with changes.  I'm hoping I did it correctly.

**Review by felixfontein — APPROVED** [review]

**Comment by bmillemathias** [comment]
Do we require a 

> This is my first PR with changes. I'm hoping I did it correctly.

Yes you did, don't hesitate sending other patches

**Comment by samccann** [comment]
Thanks @gdiamond for the Ansible docs fix!  And welcome to Ansible!

**Pull request merged**
