### PR TITLE
gconftool2 module

### PR DESCRIPTION
**Pull request by kevensen**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
gconftool2

##### ANSIBLE VERSION
```
ansible 2.3.0
```

##### SUMMARY
```
This module enables the modification of GNOME2 configuration.
```

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged, thanks

**Comment by gundalow** [comment]
@kevensen From looking at this again
Can you please raise one PR that fixes the following:

1) Your description refers to pam (where I assume you copied this from)
2) States set/unset are not really the norm, present/absent is what we would expect.

Thanks,
John

**Comment by kevensen** [comment]
Doh!  I created https://github.com/ansible/ansible/pull/19540 to address this.

**Comment by gundalow** [comment]
Fixes have been merged, thanks

**Pull request merged**
