### PR TITLE
System facts

### PR DESCRIPTION
**Pull request by ibt23sec5**
##### SUMMARY
This is a new facts module extending basic facts with detailed system information.

The module `system_facts` is an ansible wrapper of `psutil` python module and the subset names and related parameters of this module matches to major part of `psutil` functions. 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
system_facts

##### ADDITIONAL INFORMATION
The aim is to put in place a new facts module gathering additional informations about server parameters and states. As mentioned in the summary, this module wraps the `psutil` python module, but it could be great to extend it with the maximum of several parameters not included in gather_facts module. Typically the content of many system configuration files (for example as already implemented for `resolv.conf`)  could be implemented too. 
The most important is to use lightweight python functions and avoid the shell calls for the performance reasons. That's why the subset choices makes the sense if you want to call this module repetitively to get for example a list of running processes.  

Tested on:
- RHEL 8.3
- Debian 10

```
# Return all system facts
- name: Get all system facts
  ansible.builtin.system_facts:

# Returns only cpu_percent and cpu_times subsets
- name: Get CPU metrics
  ansible.builtin.system_facts:
    subsets:
      - cpu_percent
      - cpu_times
```

### CODE REVIEW

**Comment by mkrizek** [comment]
!needs_collection_redirect

**Comment by mkrizek** [comment]
Hi!

Thank you very much for your submission to Ansible. It means a lot to us that you've taken the time to contribute.

Since Ansible 2.10 we are no longer accepting new modules/plugins into Ansible core.  However, we recommend looking into providing this functionality through Ansible Galaxy via Ansible Collections. You can find more information about collections at:

   * https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html.

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
The mailing list and irc are great ways to ask questions, or post if you don't think this particular issue is resolved.

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Thank you once again for this and your interest in Ansible!

**Comment by mattclay** [comment]
Closing, since it appears, based on previous comments, that it was unintentionally re-opened.

**Pull request closed without merging**
