### PR TITLE
Issue #7358 Create non-unique parameter for group module

### PR DESCRIPTION
**Pull request by hahnicity**
I created a non_unique parameter for all platforms except AIX which requires a chsec call to change group ID security. Furthermore the chsec call has three separate options which is not conducive to being represented with a boolean.

### CODE REVIEW

**Comment by jimi-c** [comment]
So one thing I noticed in a quick test, when trying to remove a non-unique group the module fails because it's finding the first group (which belongs to a user) and tries to remove that:

<pre>
$ ansible -m group -a "name=testing2 state=absent gid=1001 non_unique=yes" ubuntu1204
192.168.122.110 | FAILED >> {
    "failed": true, 
    "msg": "groupdel: cannot remove the primary group of user 'testing'\n", 
    "name": "testing2"
}
</pre>

That will need to be addressed before this can be merged in.

**Comment by hahnicity** [comment]
Weird, I have had success with the operation

```
(ansible)greg@gregr:~/workspace/python/ansible/hacking$ ansible targets -m group -a "name=testing2 non_unique=yes gid=1005 state=absent" -i inventory -s
localhost | success >> {
    "changed": true, 
    "name": "testing2", 
    "state": "absent"
}
```

I also am using ubuntu 12.04. 

My steps were:
- Create testing1 with gid 1005
- Create testing2 with gid 1005
- Remove testing2 with gid 1005

Perhaps I am missing some of your steps or I am not testing on the correct env. I will try to play around with this to reproduce

**Comment by hahnicity** [comment]
Nvm I reproduced when I looked more closely at your comment

**Comment by hahnicity** [comment]
Blah... I did some pretty bad branching on this one...

**Comment by hahnicity** [comment]
jimi-c I'm not sure your concern is easily addressed: I would have to do some perl mucking which would not go through groupdel 

```
[ ! -f /etc/group.lock ] && perl -ne 'next if /^<group name>:/; print' /etc/group > /etc/group.lock && mv /etc/group.lock /etc/group && grpconv
```

If this still blocks the feature from being merged then I guess the feature itself could be closed. If we can not resolve this issue I will just close the pull and place my other commits in a separate pull.

**Comment by jimi-c** [comment]
Yes, I think this would be a deal-breaker, since it results in a somewhat unpredictable removal. So we'll go ahead and close this, and you can resubmit other things as needed. Thanks!

**Pull request closed without merging**
