### PR TITLE
Updating tower_job_template.py

### PR DESCRIPTION
**Pull request by ahuffman**
##### SUMMARY
The main purpose is to get several key features functioning properly, namely ask_credential, which wasn't mapped correctly in the python code.

Added several features that the API supports:
vault_credential - ability to specify named vault_credential.
verbosity - Updated verbosity to have a default of '0' (normal output) and updated python documentation.
force_handlers_enabled - Allows forcing job handlers to always run.
start_at_task - Allows starting a playbook at a named task.
timeout - Allows specifying a timeout for the playbook.  Defaults to '0'.
fact_caching_enabled - Allows enabling fact caching on the job template.
ask_diff_mode - Allows prompting to run the job template in diff mode.
ask_skip_tags - Allows prompting for tags to skip at job launch.
ask_verbosity - Allows prompting for verbosity level at job launch.
ask_credential - Fixed mapping to ask_credential_on_launch.
survey_enabled - Enables the survey on the job template (something else would have to create the spec.)
diff_mode_enabled - Allows enabling diff mode on the job template.
credential - Getting rid of machine_credential, network_credential, and cloud_credential as the current code only takes in the last mapped item, which was cloud_credential.  All 3 mapped to credential, and there was no logic or need for this, as there's no distinction in the job template between the 3 types.  The job template only cares about the name of the credential.
concurrent_jobs_enabled - Allows enabling concurrent (simultaneous) job runs on the job template.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

tower_job_template

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ahuffman/git/ansible-tiaa-onboarding/roles/tower-job-template/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### ADDITIONAL INFORMATION

Fixing ask_credential to actually work and not throw an error, and adding multiple features available via the UI and API.

```
TOWER_JOB_TEMPLATE    (/usr/lib/python2.7/site-packages/ansible/modules/web_infrastructure/ansible_tower/tower_job_template.py)

        Create, update, or destroy Ansible Tower job templates. See https://www.ansible.com/tower for an overview.

OPTIONS (= is mandatory):

- ask_credential
        Prompt user for credential on launch.
        [Default: False]

- ask_extra_vars
        Prompt user for extra_vars on launch.
        [Default: False]

- ask_inventory
        Propmt user for inventory on launch.
        [Default: False]

- ask_job_type
        Prompt user for job type on launch.
        [Default: False]

- ask_tags
        Prompt user for job tags on launch.
        [Default: False]

- become_enabled
        Should become_enabled.
        [Default: False]

- cloud_credential
        Cloud_credential to use for the job_template.
        [Default: None]

- description
        Description to use for the job_template.
        [Default: None]

- extra_vars_path
        Path to the extra_vars yaml file.
        [Default: None]

- forks
        The number of parallel or simultaneous processes to use while executing the playbook.
        [Default: None]

- host_config_key
        Allow provisioning callbacks using this host config key.
        [Default: None]

- inventory
        Inventory to use for the job_template.
        [Default: None]

- job_tags
        The job_tags to use for the job_template.
        [Default: None]

= job_type
        The job_type to use for the job_template.
        (Choices: run, check, scan)

- limit
        A host pattern to further constrain the list of hosts managed or affected by the playbook
        [Default: None]

- machine_credential
        Machine_credential to use for the job_template.
        [Default: None]

= name
        Name to use for the job_template.


- network_credential
        The network_credential to use for the job_template.
        [Default: None]

= playbook
        Playbook to use for the job_template.


= project
        Project to use for the job_template.


- skip_tags
        The skip_tags to use for the job_template.
        [Default: None]

- state
        Desired state of the resource.
        (Choices: present, absent)[Default: present]

- tower_config_file
        Path to the Tower config file. See notes.
        [Default: None]

- tower_host
        URL to your Tower instance.
        [Default: None]

- tower_password
        Password for your Tower instance.
        [Default: None]

- tower_username
        Username for your Tower instance.
        [Default: None]

- tower_verify_ssl
        Dis/allow insecure connections to Tower. If `no', SSL certificates will not be validated. This should only be used on personally
        controlled sites using self-signed certificates.
        [Default: True]

- verbosity
        Control the output level Ansible produces as the playbook runs.
        (Choices: verbose, debug)[Default: None]


NOTES:
      * If no `config_file' is provided we will attempt to use the tower-cli library defaults to find your Tower host information.
      * `config_file' should contain Tower configuration in the following format host=hostname username=username password=password

REQUIREMENTS:  ansible-tower-cli >= 3.0.2

AUTHOR: Wayne Witzel III (@wwitzel3)
        METADATA:
          status:
          - preview
          supported_by: community
        

EXAMPLES:
- name: Create tower Ping job template
  tower_job_template:
    name: Ping
    job_type: run
    inventory: Local
    project: Demo
    playbook: ping.yml
    machine_credential: Local
    state: present
    tower_config_file: "~/tower_cli.cfg"

TOWER_JOB_TEMPLATE    (/home/ahuffman/git/ansible-1/lib/ansible/modules/web_infrastructure/ansible_tower/tower_job_template.py)

        Create, update, or destroy Ansible Tower job templates. See https://www.ansible.com/tower for an overview.

OPTIONS (= is mandatory):

- ask_credential
        Prompt user for credential on launch.
        [Default: no]
        type: bool

- ask_diff_mode
        Prompt user to enable diff mode (show changes) to files when supported by modules.
        [Default: no]
        type: bool

- ask_extra_vars
        Prompt user for (extra_vars) on launch.
        [Default: no]
        type: bool

- ask_inventory
        Propmt user for inventory on launch.
        [Default: no]
        type: bool

- ask_job_type
        Prompt user for job type on launch.
        [Default: no]
        type: bool

- ask_limit
        Prompt user for a limit on launch.
        [Default: no]
        type: bool

- ask_skip_tags
        Prompt user for job tags to skip on launch.
        [Default: no]
        type: bool

- ask_tags
        Prompt user for job tags on launch.
        [Default: no]
        type: bool

- ask_verbosity
        Prompt user to choose a verbosity level on launch.
        [Default: no]
        type: bool

- become_enabled
        Activate privilege escalation.
        [Default: no]
        type: bool

- concurrent_jobs_enabled
        Allow simultaneous runs of the job template.
        [Default: no]
        type: bool

- credential
        Name of the credential to use for the job template.
        [Default: (null)]

- description
        Description to use for the job template.
        [Default: (null)]

- extra_vars_path
        Path to the `extra_vars' YAML file.
        [Default: (null)]

- fact_caching_enabled
        Enable use of fact caching for the job template.
        [Default: no]
        type: bool

- force_handlers_enabled
        Enable forcing playbook handlers to run even if a task fails.
        [Default: no]
        type: bool

- forks
        The number of parallel or simultaneous processes to use while executing the playbook.
        [Default: (null)]

- host_config_key
        Allow provisioning callbacks using this host config key.
        [Default: (null)]

- inventory
        Name of the inventory to use for the job template.
        [Default: (null)]

- job_tags
        Comma separated list of the tags to use for the job template.
        [Default: (null)]

= job_type
        The job type to use for the job template.
        (Choices: run, check, scan)

- limit
        A host pattern to further constrain the list of hosts managed or affected by the playbook
        [Default: (null)]

= name
        Name to use for the job template.


= playbook
        Path to the playbook to use for the job template within the project provided.


= project
        Name of the project to use for the job template.


- skip_tags
        Comma separated list of the tags to skip for the job template.
        [Default: (null)]

- start_at_task
        Start the playbook at the task matching this name.
        [Default: (null)]

- state
        Desired state of the resource.
        (Choices: present, absent)[Default: present]

- survey_enabled
        Enable a survey on the job template.
        [Default: no]
        type: bool

- tower_config_file
        Path to the Tower config file. See notes.
        [Default: None]

- tower_host
        URL to your Tower instance.
        [Default: None]

- tower_password
        Password for your Tower instance.
        [Default: None]

- tower_username
        Username for your Tower instance.
        [Default: None]

- tower_verify_ssl
        Dis/allow insecure connections to Tower. If `no', SSL certificates will not be validated. This should only be used on personally
        controlled sites using self-signed certificates.
        [Default: True]

- vault_credential
        Name of the vault credential to use for the job template.
        [Default: (null)]

- verbosity
        Control the output level Ansible produces as the playbook runs. 0 - Normal, 1 - Verbose, 2 - More Verbose, 3 - Debug, 4 -
        Connection Debug.
        (Choices: 0, 1, 2, 3, 4)[Default: 0]


NOTES:
      * If no `config_file' is provided we will attempt to use the tower-cli library defaults to find your Tower host information.
      * `config_file' should contain Tower configuration in the following format host=hostname username=username password=password

REQUIREMENTS:  ansible-tower-cli >= 3.0.2

AUTHOR: Wayne Witzel III (@wwitzel3)
        METADATA:
          status:
          - preview
          supported_by: community
        

EXAMPLES:
- name: Create tower Ping job template
  tower_job_template:
    name: "Ping"
    job_type: "run"
    inventory: "Local"
    project: "Demo"
    playbook: "ping.yml"
    credential: "Local"
    state: "present"
    tower_config_file: "~/tower_cli.cfg"

```

### CODE REVIEW

**Comment by stoleas** [comment]
I can confirm that these changes work for Ansible Core 2.5 on Ansible Tower 3.2.3.

**Comment by ahuffman** [comment]
Tested with 3.2.4 tower and ansible 2.5.2 today.

**Comment by willthames** [comment]
Tested with 1.0.6 AWX and ansible devel.

**Comment by willthames** [comment]
Merged, thanks very much @ahuffman

**Comment by epolkovnikov** [comment]
Looks like "credential:" is taking only machine credential now. Also I could not find a way to set both machine and cloud credential. The previous version of the module and Tower 3 UI supports it, but not the module. 
With the previous version I used
machine_credential: "my_machine_cred"
cloud_credential: "my_cloud_cred" 
And it worked just fine, adding both credentials to Credential field in Ansible Tower 3 UI.
Thinking the new module moved to the list model too, I tried list like
credential: [ "my_machine_cred", "my_cloud_cred" ], but it was interpreted as a single line and complaining "no such object".

Suggestion is to keep machine_credential, cloud_credential, network_credential parameters for compatibility and functional reasons.

**Comment by ahuffman** [comment]
There's no such thing as a cloud credential/network credential/machine
credential in v3.2.x of Tower's API (just look at the API endpoint for a job template).  There's only a "credential" or "vault
credential" that can be added to a Job Template.  Just switch the param for
what you used to use as cloud/net/machine to credential and it'll work.  The credential you specify just refers back to the name of the credential, it doesn't care what type it is unless it's a vault credential.

Regards,
Andrew

**Comment by epolkovnikov** [comment]
Hello Andrew,

Thanks for clarification. What if we need both machine credential and cloud credential together. E.g. ssh + aws?
In my case for some reason I am getting:
Scenario 1: Using just a machine cred - Ok
Scenario 2: Using just a cloud cred – fails with “You must provide an SSH credential”
Scenario 3: Both machine and cloud creds as list/array ends with “Failed to update job template: The requested object could not be found.”
Scenario 4: Both machine and cloud creds as comma separated string ends with “Failed to update job template: The requested object could not be found.”

I noticed we are on tpwer_cli 3.1.4
as of `cat /usr/lib/python2.7/site-packages/tower_cli/VERSION`
Is it the right one?

Also, just if you know: any hints on if/when there could be support for "instance_group", "label", "diff_mode" for templates? And what would be involved to get support for them?
http://tower-cli.readthedocs.io/en/latest/api_ref/resources/job_template.html seem to have them

Thanks again,
Evgeny

**Comment by ahuffman** [comment]
The cloud/network credential types in Tower 3.2.x are used only for syncing inventories.  You attach them to one of the built-in dynamic inventory scripts:
https://docs.ansible.com/ansible-tower/latest/html/userguide/credentials.html

You attach machine and vault credentials to a job template.  If you have any other specific credential types such as for accessing a network device/AWS/Azure/Google, they should be stored in an ansible-vault in your project repository and accessed with your vault credential and called by the modules in your playbooks with jinja2 templating as you do for other variables.

Take a look at this commit to see all the features coming to the module in Ansible 2.7: https://github.com/ansible/ansible/pull/38821/commits/6aff316a9f3af003d9ecbea4bdc6455125f0914a  .

diff_mode_enabled will be an option.  Via the API there's not a way that I can see to add a label, there must be another endpoint that handles that, similar to surveys (I'd have to investigate.)  If you visit your 3.2.x Tower server/api/v2/job_templates scroll down to the bottom of the page and you can see all the possible options for the endpoint.  For instance group you can create an inventory and attach an instance group to it, so that way anything in that inventory always will run off the instance group.

Also it looks like ansible-tower-cli (3.3.0) is the latest version so you may want to do a pip install --upgrade ansible-tower-cli.  You can also list the files associated with a package with pip show --files ansible-tower-cli

**Comment by epolkovnikov** [comment]
Thanks for the info.

But still :-)
What if we need not just to pull dynamic AWS inventory, but also actually do something with the AWS resources, like create an instance, an RDS, a KMS key?
In addition, within our org it was decided to use explicit AWS individual accounts and not the role. So adding AWS credentials to Job Templates was a way of choice.

And finally: It is possible to add Cloud Creds via the Web UI and via tower-cli command line tool using expression like 
tower-cli job_template associate_credential --credential=X --job-template=Y
So not having a way to add cloud credential via the module looks surprising and limiting when comparing to the means of the Web UI and CLI.

**Comment by ahuffman** [comment]
@epolkovnikov I see what you mean now.  We should allow the module parameter for "credential" to accept a list or string.  I think it would be more usable as a list because from the perspective of the Tower UI you see all attached credentials in the same field.  Also, I know you cannot attach more than 1 machine credential, but I'm not sure if there's any other rules/limits we might have to account for with other types.

I'd have to spend some time looking at how to implement that to avoid any future issues such as your use-case.  If you are able to look at it and put in a PR go for it.  Not sure when I'll have the time to actually look at it with my current schedule.

**Pull request merged**
