### PR TITLE
openssl_csr: modify CSR when diff found between existing CSR and user values

### PR DESCRIPTION
**Pull request by psykotox**
##### SUMMARY
Modify CSR when diff found between existing CSR and user values

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

modules/crypto/openssl_csr.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]
```

##### ADDITIONAL INFORMATION

Needs Python pyOpenssl module with version greater than 0.15.
With Debian Jessie you have to install python-openssl on backports repo.

### CODE REVIEW

**Comment by cpointner** [comment]
@psykotox i'm currently working on moving this module to the new standardized way to build openssl based crypto modules and if you don't mind i will integrate your changes into my PR. Of course i will add you as a Co-Author.

**Comment by psykotox** [comment]
@cpointner Sure, you can integrate my changes into your PR.

**Comment by cpointner** [comment]
Thanks @psykotox. If you are interested [here](https://github.com/ansible/ansible/compare/devel...mgit-at:openssl_csr_rewrite) are my changes. They are basically finished. I just need to wait for #27221 or #27231 to be merged.

**Comment by Spredzy** [comment]
Thanks @psykotox for submitting this PR. As @cpointner informed you earlier, he has made a PR that has been merged since.

Could you please close this PR as it is considered solved. Feel free to open a new PR is therre a feature you'd like to see in this module that aren't in it yet.

**Pull request closed without merging**
