### PR TITLE
Documentation showing a worked example of how to use the include_tasks module

### PR DESCRIPTION
**Pull request by projectredfern**
##### SUMMARY
I found the include_tasks module a useful tool once I had mastered it. I thought that others might also find it useful if they could read through a worked example and see it applied in context. I wrote a page of documentation in order to help other Ansible users.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
A worked example for the include_tasks module.

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bcoca** [comment]
this might be better suited for https://github.com/ansible-examples

**Comment by dagwieers** [comment]
I think this could fit in a section that explains different ways to organize your playbooks. Because we have so many possibilities these days, beyond roles, that is not well explained IMO.

**Comment by projectredfern** [comment]
@bcoca, @dagwieers 
Thanks for your inputs, both of you. I would be happy to move it to https://github.com/ansible/ansible-examples, and then to create a section about playbook organisation, if that made sense. Alternatively, I could write additional documentation for the user-guide section expanding on playbook organisation, *there*.

As before your comments are welcomed. Thanks.

**Comment by bcoca** [comment]
also pinged @acozine about this, we might want to discuss how to highlight 'real world' examples better in docs site, either use/point at ansible-examples or integrate into the site itself

**Comment by projectredfern** [comment]
@bcoca Fantastic.

**Comment by projectredfern** [comment]
I am closing this pull requesthttps://github.com/ansible/ansible/pull/53004

**Comment by acozine** [comment]
Superseded by #53004.

**Pull request closed without merging**
