### PR TITLE
make sanity tests work on Python 3.8 and 3.9

### LINKED ISSUE #67118: pylint sanity test fails on Python 3.8
##### SUMMARY
When running `ansible-test sanity --venv --python 3.8 --test pylint plugins/` inside the `theforeman.foreman` collection (https://github.com/theforeman/foreman-ansible-modules), the test fails with

```
ERROR: plugins/module_utils/foreman_helper.py:13:0: syntax-error: Cannot import 'contextlib' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 380)'
ERROR: plugins/module_utils/foreman_helper.py:15:0: syntax-error: Cannot import 'collections' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 96)'
ERROR: plugins/module_utils/foreman_helper.py:16:0: syntax-error: Cannot import 'functools' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 276)'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/egolov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/egolov/Devel/theforeman/foreman-ansible-modules/venv3/lib64/python3.7/site-packages/ansible
  executable location = /home/egolov/Devel/theforeman/foreman-ansible-modules/venv3/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

```

##### CONFIGURATION

```paste below
<empty>
```

##### OS / ENVIRONMENT

Fedora 31

##### STEPS TO REPRODUCE

```yaml
ansible-test sanity --venv --python 3.8 --test pylint plugins/
```

##### EXPECTED RESULTS

No errors / or at least valid sanity/pylint errors ;)

##### ACTUAL RESULTS

```
ERROR: plugins/module_utils/foreman_helper.py:13:0: syntax-error: Cannot import 'contextlib' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 380)'
ERROR: plugins/module_utils/foreman_helper.py:15:0: syntax-error: Cannot import 'collections' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 96)'
ERROR: plugins/module_utils/foreman_helper.py:16:0: syntax-error: Cannot import 'functools' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 276)'
```

##### ADDITIONAL  INFO

I've traced the issue to `astroid-2.2.5` (a dependency of `pylint`), when using `astroid-2.3.3` everything works.

### PR DESCRIPTION
**Pull request by evgeni**
##### SUMMARY

Fixes: #67118

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by evgeni** [comment]
Damn, this seems to be something with `astroid` :(

**Comment by evgeni** [comment]
Hah, nothing that can't be fixed with better code :)

**Comment by evgeni** [comment]
the shippable errors look unrelated

**Comment by mattclay** [comment]
@evgeni Could you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment)?

**Comment by evgeni** [comment]
@mattclay done

**Comment by evgeni** [comment]
Shippable errors still unrelated 🤷

**Comment by evgeni** [comment]
@mattclay could you please have another look?

**Comment by evgeni** [comment]
with Fedora 32 out and shipping with Python 3.8, I'd love to see Ansible tested on 3.8 :)

**Comment by mattclay** [comment]
@evgeni Testing Python 3.9a6 with these changes resulted in internal pylint errors. Since 3.9 hasn't been released yet and is failing, we should probably scale this PR back to just adding 3.8 support.

I did some brief testing with 3.8 as well, and while it does appear to be working, both 3.8 and 3.7 are showing some differences in behavior compared to 3.6 so I'd like to look into those more.

**Comment by evgeni** [comment]
Hmm. Which 3.9 version and what was failing? Rather sure stuff was passing when I originally tested things, but that's some time ago.

**Comment by mattclay** [comment]
@evgeni Rebase your PR and run the following:

```
ansible-test sanity --test pylint --docker --python 3.9 lib/ansible/galaxy/collection.py -v
```

That will use Python 3.9a6 and results in the following error:

```
internal error with sending report for module ['lib/ansible/galaxy/collection.py']
'Call' object has no attribute 'value'
```

**Comment by evgeni** [comment]
Thanks, I'll try to have a look on Monday during work.

**Comment by evgeni** [comment]
So this is fixed when I update to pylint 2.5.x, but then we have new linting issues :(

**Comment by pabelanger** [comment]
we just hit this on content team, testing with 3.6 for now.

**Comment by evgeni** [comment]
closing in favor of https://github.com/ansible/ansible/pull/70155

**Pull request closed without merging**
