### PR TITLE
Clarifiy the usage of env_file in the docker_container module

### PR DESCRIPTION
**Pull request by ntwrkguru**
Clarified the usage of C(env_file) and provided an example of the same.
+label: docsite_pr

##### SUMMARY

Clarified the usage of C(env_file) and provided an example of the same.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

docker_container.py

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:26:36) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by kassiansun — APPROVED** [review]

**Comment by kassiansun** [comment]
shipit

**Comment by felixfontein** [comment]
@ntwrkguru would you mind rebasing against current `devel` branch to remove the conflicts?

**Comment by ntwrkguru** [comment]
Not sure what you want me to do here. It was such a simple change, I did it through the web editor. I'm happy to contribute, but this is becoming more trouble than it's worth. @felixfontein

**Comment by felixfontein** [comment]
Hmm, Ansible doesn't accept merge commits, and the Github "resolve conflicts" tool always inserts them. (It doesn't [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).)

You can use the `git` command line tool to remove the merge commit, rebase manually, and then force push the result. It's not trivial (and a bit dangerous), though. It should look like this (assuming you added the Ansible git repo as remote `upstream`):
```
git checkout devel
git pull upstream devel   # make sure you have the current devel branch
git checkout patch-1
git reset --hard HEAD^   # remove the merge commit
git rebase devel   # git rebase will stop because of conflicts, which you then have to resolve
git push -f   # force-push the result
```

**Comment by ntwrkguru** [comment]
I merged devel from ansible/ansible to my fork, then tried your instructions, but there were merge commits. I've literally spent more time trying to remove conflicts that I didn't create than I spend adding a couple of examples. Sorry to sound like a dick, but this isn't worth my time at this point. I would recommend that the process be examined, because I can't imagine many casual contributors will want to deal with fixing issues that they didn't introduce. You can fix it or just cancel the PR, either way doesn't matter to me.

**Comment by felixfontein** [comment]
Do you mind if I re-create the PR with your patch? I cannot ping you in the commit message (Ansible doesn't allow this either), though, so I cannot directly attribute you (only from the PR thread).

And sorry that this turned out to be this complicated. Usually, if PRs are processed quickly enough, things are merged before conflicts (and thus the need to rebase) show up. Unfortunately there has been a shortage of active `docker_container` maintainer lately...

**Comment by ntwrkguru** [comment]
Yea, that's cool. I don't care about the attributes. Like I said, I'm happy to help out, but that contribution took, literally, 2 minutes. I spent 20 trying to remove conflicts, so at some point, it just becomes too much.

**Comment by felixfontein** [comment]
I created a new PR in #44535. Feel free to close this one.

**Comment by ntwrkguru** [comment]
Thanks.

**Pull request closed without merging**
