### PR TITLE
xml module: Make user interface much more restricted

### LINKED ISSUE #28194: xml module: "ensure: present" command does not work poperly
_From @hammersoft on May 18, 2017 9:5_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION
unknown

##### SUMMARY
Hi! 
I am using this xml

```xml
<?xml version='1.0' encoding='utf-8'?>
<tomcat-users>
    <role rolename="admin"/>
    <role rolename="admin-gui"/>
    <role rolename="admin-script"/>
    <role rolename="manager"/> 
</tomcat-users>
```

and next ansible task:
```yaml
- name: "Check selected roles"
  xml:
    path: "/etc/tomcat/tomcat-users.xml"
    xpath: "/tomcat-users/role[@rolename=\"{{ item }}\"]"
    pretty_print: True
    ensure: present
  with_items:
    - "manager"
    - "manager-script"
```
According to documentation 
> ensure:
>    description:
>      - Set or remove an xpath selection (node(s), attribute(s))

expecting to add node <role rolename="manager-script"/> into xml file. 
Task reporting all ok, but no new nodes added. 

With **ensure: absent** works fine: only specified node `<role rolename="manager"/>` is gone. 

Is this behaviour correct or this is error?

_Copied from original issue: cmprescott/ansible-xml#110_

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
So the xml module has a lot of parameters that combined together do specific things. however it does not really describe which parameters are required together, or which ones are required.

This PR fixes that situation and makes it impossible to provide confusing parameters combinations. We need **required_by** functionality https://github.com/ansible/ansible/pull/28662 to do this right.

Also, `pretty_print` was used as a flag to modify the output, but also as an action to reformat the file (without other change). This is problematic the way it was designed. This fixes that too.

This fixes #28194

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
xml

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by dagwieers** [comment]
So I am going to go forward and merge this without **required_by** so we can test it again when this is being released. This PR includes too many stuff already applicable to users.

**Comment by mattclay** [comment]
@dagwieers I've [disabled the xml test](https://github.com/ansible/ansible/commit/a7fd806fde22c14226ea1dba2158a5d53ec32d37) due to [memory allocation errors](https://app.shippable.com/github/ansible/ansible/runs/35055/19/console) that were occurring repeatedly on Shippable on the xml test.

I don't know why it started failing, or why it stopped failing just before I disabled it. I'll try to take a look at it next week when I'm not traveling.

**Comment by dagwieers** [comment]
I noticed it. I wonder since what PR this has been happening. And does this happen for all targets at some point, or only a specific one (linux/ubuntu1604/1) ? Because I am not doing anything special, I recently added support for lxml.objectify comparison, but the examples we are using are very small XML files. It must be a bug in python/lxml...

**Comment by mattclay** [comment]
@dagwieers It only seems to happen on the ubuntu1604 docker image.

**Comment by dagwieers** [comment]
Would be nice to see what version of python and lxml is available, and whether there is an update of these packages. So could we not just skip that one instead ?

**Pull request merged**
