### PR TITLE
Add new module for managing linux swap  

### PR DESCRIPTION
**Pull request by shatQ**
##### SUMMARY

Add module for managing swap which allows to set up swap area on a device, activate or deactivate swapping and update fstab.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

swap
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jtyr** [comment]
This overlaps with what the `mount` module is doing. And for the creation of swap FS, I would rather see a patch for the `filesystem` module.

**Comment by shatQ** [comment]
I would not agree that it overlaps existing functionality. The `mount` module is not capable to handle swap activation as it was desined to use "mount" system utility which doesn't support swap.

```
def mount(module, args):
    """Mount up a path or remount if needed."""

    mount_bin = module.get_bin_path('mount', required=True)
    name = args['name']
    cmd = [mount_bin]
    ...
```

Linux OS use `swapon/swapoff` utility to enable/disable swapping.  The common part of my module and `mount` module is modification of fstab entries.

So, the fact is that currently there is no idempotent whay to manage swap. The only option for now is creating ansible role based on `command `module. 

I agree that `mount` and `filesystem` could be extended to support swap, but according to Linux/Unix philosophy programs should be focused on one functionality and do it properly rather than be combo tools. The other argument is that swap is actually not a filesystem, so maybe handling it by separate module is a proper way.

Does it mean that swap should have deticated module, well that's room for discussion. I'm just sharing my idea, that I found working well. 

If you prefer to extend `mount` and `filesystem` functionality I can try to adapt them.

**Comment by jtyr** [comment]
I'm more in favour of extending the existing modules (`mount` to handle `swapon/swapoff` and `filesystem` to handle `mkswap`).

**Comment by shatQ** [comment]
OK, thx for review.

**Comment by bcoca** [comment]
@shateq  I'm thinking we might want this to activate/deactivate swap partitions, the current mount module does too much and not always well. I do agree we should use filesystem module for making such partitions though.

**Comment by shatQ** [comment]
@bcoca Hi, I've just read your message, unfortunately few minutes after I removed my fork of ansible repository as I thought it was not accepted :(  Should I create new pull request or there is some way to attach my new fork (https://github.com/shateq/ansible/tree/devel-swap-support) to this PR?

I already did some test with `filesystem `module. It's nice designed and provides filesystem generic class. Swap support can be added easly.

I will upload patched version of `filesystem `as soon as you tell me if I can work with current PR or I need create new one.

**Comment by bcoca** [comment]
@shateq well, github keeps a copy of the PR code for a whlie, but then it is hard to make changes when the source is gone. I'm leaving the specifics up to you.

Glad to hear filesystem works well for you.

**Comment by shatQ** [comment]
@bcoca I decided to create two new PRs and close current one:
- [#49455](https://github.com/ansible/ansible/pull/49455) - refactored version of `swap `module with functionallity limited to swap activation/deactivation
- [#49456](https://github.com/ansible/ansible/pull/49456) - improved version of `filesystem `module with possibility creation swap filesystem

**Comment by jtyr** [comment]
I'm not in favor of this `swap` module because people expect the functionality to be in the `mount` module instead (e.g. #31437). You are right, @bcoca, that the `mount` module does a lot and not always well but that's given by differences between all possible platforms it supports. Adding support for swap into the `mount` module is quite simple and logically falls into that module competence as it takes care of mounting and updating of the `fstab`. Duplicate the `fstab` functionality across two modules or extracting it into another `module_utils` could make things even more complicated.

I strongly recommend to add the swap functionality into the `mount` module.

**Pull request closed without merging**
