### PR TITLE
Fix templating task action with host-specific vars

### LINKED ISSUE #75568: core 2.11.3 marking ansible_os related variables as incorrect distro.
### Summary

SInce updating to `core 2.11.3` some `ansible_os_family` variables on some servers are being returned as Debian instead of Redhat (Amazon Linux2).

### Issue Type

Bug Report

### Component Name

yum

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.3] 
  config file = /home/russell/repos/ansible/ansible.cfg
  configured module search path = ['/home/russell/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/russell/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True

(Colleague running 2.11.3 version, I am still on 2.9.10 to make testing easier)
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/russell/repos/ansible/ansible.cfg) = False
DEFAULT_ROLES_PATH(/home/russell/repos/ansible/ansible.cfg) = ['/home/russell/repos/ansible/roles', '/home/russell/ansible/roles']
DEFAULT_STRATEGY(/home/russell/repos/ansible/ansible.cfg) = linear
DEFAULT_TIMEOUT(/home/russell/repos/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/russell/repos/ansible/ansible.cfg) = /home/russell/.vault_pass.txt
HOST_KEY_CHECKING(/home/russell/repos/ansible/ansible.cfg) = False

(Colleague running 2.11.3 version, I am still on 2.9.10 to make testing easier)
```

### OS / Environment

```
$ uname -r
4.14.104-95.84.amzn2.x86_64
```

### Steps to Reproduce

When running a playbook that uses `ansible_pkg_mgr` on ansible version `2.9.10` to a Amazon Linux2 host, `yum` is returned.

When running the same playbook on `core: 2.11.3` to a Amazon Linux2 host `apt` is returned.

Task in question:

```
- name: ensure sudo package is installed
  action:
    module: '{{ ansible_pkg_mgr }}'
    name: '{{ admin_users_sudo_package }}'
    state: present
  when: admin_users_sudo_package is defined```
```

Ran on 2.9.10:

```
TASK [ae.users : debug ansible family] *****************************************************************
ok: [ip-10-80-0-135.us-east-2.compute.internal] => {
    "msg": "family: RedHat"
}
ok: [ip-10-80-0-164.us-east-2.compute.internal] => {
    "msg": "family: RedHat"
}
ok: [ip-10-80-0-71.us-east-2.compute.internal] => {
    "msg": "family: Debian"
}
ok: [ip-10-80-0-211.us-east-2.compute.internal] => {
    "msg": "family: RedHat"
}

TASK [ae.users : ensure sudo package is installed] *****************************************************
ok: [ip-10-80-0-135.us-east-2.compute.internal]
ok: [ip-10-80-0-211.us-east-2.compute.internal]
ok: [ip-10-80-0-164.us-east-2.compute.internal]
ok: [ip-10-80-0-71.us-east-2.compute.internal]

```

Ran on 2.11.3

```
TASK [ae.users : ensure sudo package is installed] ********************************************************************************
ok: [ip-10-18-0-76.us-west-2.compute.internal]
ok: [ip-10-18-0-171.us-west-2.compute.internal]
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
fatal: [ec2-44-225-183-160.us-west-2.compute.amazonaws.com]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

Host in question:

```
root@x-useast2-es-3[x-useast2]:~$ uname
Linux

root@x-useast2-es-3[x-useast2]:~$ uname -r
4.14.104-95.84.amzn2.x86_64
```

### Expected Results

I expect yum to returned on yum based hosts, not apt.

### Actual Results

```console
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
fatal: [ec2-44-225-183-160.us-west-2.compute.amazonaws.com]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}```
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes #75568

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/plugins/strategy/linear.py`

### CODE REVIEW

**Comment by bcoca** [comment]
the action should be the same for all hosts, this was initially intentional. I would bring this up in core meeting if we want to change that.

**Comment by mkrizek** [comment]
ok, just to provide more context. The "regression" (doing `task.action = templar.template(task.action)`) was introduced in #67684, so it had worked before that and we didn't seem to mention the change in behavior (bugfix?) in the porting guide. 

Also, `task.action = templar.template(task.action)` is not done in the `free` strategy, so running different actions for different hosts based on a variable has been possible in the `free` strategy.

**Comment by bcoca** [comment]
that was probably an oversight in both cases, but initially there were 2 things that were supposed to be the same for all hosts, task name and task action.

**Comment by nitzmahone** [comment]
As Martin implies above, this is sort of a regression, sort of not- it was definitely an unintended oversight in the collections changes (guilty), but what the actual correct behavior should be is a gray area, because we've never done first-pass action resolution under a host loop. Late Action->Module resolution behavior was also unintentionally affected by the collections change in the same way. This change restores the original behavior, but off the top of my head, also means that the `task.action` that's available to various callbacks will be internally inconsistent and/or an un-rendered template in such cases. The new `task.resolved_action` will also be incorrect in the same cases, and is not currently addressed by this PR. We know there will always be cases where `task.resolved_action` is also incorrect/inconsistent with what actually ran, but until we move it to a host-specific location and resolve what host-agnostic callbacks should see, it's not clear what we can do.

There are some future enhancements that might actually require task actions to be resolved under a host loop at parse-time if we want pedantic correctness (and/or the same degree of parse-time failure vs runtime failure we currently offer), so this is something we should hammer out as a group what we think is "correct behavior" pretty soon.

**Review by bcoca — APPROVED** [review]

**Review by s-hertel — APPROVED** [review]
I like the flexibility of this. Maybe the task.resolved_action limitation is just something that should be documented for module_defaults - if the action isn't resolved on the first pass, the resolved action is None and module_defaults will be ignored (since module_default entries need to be resolved pre-fork).

**Pull request merged**
