### PR TITLE
[stable-2.7] Add AIX support to reboot module (#50353)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

* Add ability for reboot module to work for AIX

(cherry picked from commit 1dac10e5c3e362d6eace6ddb7bd42c5de48b6b2d)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`reboot.py`

### CODE REVIEW

**Comment by samdoran** [comment]
This may need to be rebased once #50616 is merged.

**Comment by abadger** [comment]
Yep, needs a rebase and then it can be merged.

**Comment by samdoran** [comment]
Rebased and ready to merge.

**Comment by abadger** [comment]
Merged for 2.7.6

**Pull request merged**
