### PR TITLE
Added OS Family facts

### PR DESCRIPTION
**Pull request by tonk**
Handy to group on OS Family, not just on OS.

### CODE REVIEW

**Comment by dhozac** [comment]
This has whitespace issues. Make sure you use 4 spaces and not tabs.

**Comment by tonk** [comment]
Fixed the space/tab issue.

**Comment by mpdehaan** [comment]
FYI:  4 space indent is our standard, think I saw 3, if not, just sharing.  In queue to look at later.

**Comment by mpdehaan** [comment]
merged in, shortened up the code a small amount and renamed the fact to "os_family" from "osfamily"

**Comment by mpdehaan** [comment]
thanks!

**Pull request closed without merging**
