### PR TITLE
Add `--gpg-whitelist` option to ansible-pull

### PR DESCRIPTION
**Pull request by andreaso**
##### SUMMARY

Provides a direct mapping to the git module's `gpg_whitelist` parameter.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible-pull

### CODE REVIEW

**Comment by bcoca** [comment]
we are not sure about adding this one here, both beting gpg specific and git already having env vars and configs that provide this.

Also it makes sense to accept this key with the keystore and not do it inline with the request.

**Comment by andreaso** [comment]
Is it really a problem that `--gpg-whitelist` is a gpg specific option, given that it's really only an add-on to the existing `--verify-commit` option, which in itself is gpg specific?

But yeah, there are other ways to define which keys Ansible should trust. Just felt very convenient to be able to hook into functionality already implemented in Ansible's git module.

**Comment by bcoca** [comment]
the --verify-commit does NOT have to be gpg specific, the implementation is, but if tomorrow CVS becomes again the new hot SCM with it's own commit verification, the implementation can be done w/o renaming the options.

**Comment by bcoca** [comment]
https://github.com/ansible/community/issues?q=is:open+label:meeting_agenda+label:core

**Pull request closed without merging**
