### PR TITLE
VMware: Add 'connected' option for virtual network adapters.

### PR DESCRIPTION
**Pull request by native0090**
##### SUMMARY

Added the option to connect or disconnect virtual network adapters in vmware_guest when reconfiguring 
networks. Before it was not possible to connect/disconnect a virtual network adapter.

(This is the updated PR for #46276)

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

vmware_guest

### CODE REVIEW

**Comment by mpk93** [comment]
Can anyone give me a hint on how to integrate the test into the main integration task of vmware_guest?

**Comment by Tomorrow9** [comment]
There is a main file in: test/integration/targets/vmware_guest/tasks/main.yml

**Comment by mpk93** [comment]
Can I manually trigger a testrun, or should I just make a dummy commit? There seemed to be a problem with Shippable or GitHub.

**Comment by samdoran** [comment]
Closing/reopening the PR or pushing a new commit are currently the only ways to trigger a test run. There is an [open request](https://github.com/ansible/ansibullbot/issues/1161) to add a command to the bot.

**Review by pdellaert — APPROVED** [review]
LGTM

**Pull request closed without merging**
