### PR TITLE
added firewalld module

### PR DESCRIPTION
**Pull request by maxamillion**
This is round 2 for the pull request originating at https://github.com/ansible/ansible/pull/3810

Adds basic firewalld management to ansible.

### CODE REVIEW

**Comment by jimi-c** [comment]
A couple of minor things:

1) In your argument_spec, 'permanent' should be set to type='bool', and you won't need to do string comparisons to check it. 
2) Most of your params are not being set to the defaults as indicated in the documentation section.

Get those fixed up and I'll get this in the queue for testing.

**Comment by maxamillion** [comment]
Added defaults where applicable, changed permanent to type='bool'

**Comment by jimi-c** [comment]
I'm guessing this is because my test system is F17, but it's not working for me:

<pre>
TASK: [firewalld port=9999/tcp permanent=true state=enabled] ****************** 
failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1376430206.26-9017371969185/firewalld", line 1216, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1376430206.26-9017371969185/firewalld", line 190, in main
    if fw.connected == False:
AttributeError: 'FirewallClient' object has no attribute 'connected'
</pre>

Also, before I installed the firewalld package, it was returning ok for the task despite not changing anything, that should probably be a failure.

**Comment by maxamillion** [comment]
Before you installed the firewalld package it should have errored out trying to import from firewall.client and I'm not sure about the F17 issue since it's EOL and I don't have a F17 machine around, I've tested on F19 though. I'll look at this and see if I can reproduce.

**Comment by jimi-c** [comment]
Yeah probably want to at least test on F18 as well, and anything else that might support firewalld, perhaps even add in a check for minimum support when it comes to the firewalld version or the python library it supplies.

**Comment by maxamillion** [comment]
I tested against Fedora 18 and Fedora 19, works on both. I did go ahead and add a version check in there just for sanity sake though.

**Comment by mpdehaan** [comment]
Looks like the above can be done using a try/except and raise an error when you get that with a module.fail_json(...)

**Comment by maxamillion** [comment]
Added try/except around that call. I _think_ that's what you were referring to, if there is something else you'd like me to fix or think a different method would be better please let me know and I'll gladly fix.

**Comment by jimi-c** [comment]
Merged, thanks! One minor change was to move it from net_infrastructure to system, since net_infra is used mainly for networking gear. Since firewalld is a system daemon, the system folder seemed more appropriate.

**Pull request merged**
