### PR TITLE
🎨 Deduplicate to_bool() implementation

### PR DESCRIPTION
**Pull request by webknjaz**
##### SUMMARY
bool parser in module_utils and bool converter in core filter plugin are loosely the same. So I've made filter plugin reuse the function from module_utils.

##### ISSUE TYPE

- Refactoring Pull Request

##### COMPONENT NAME

lib/ansible/plugins/filter/core.py

##### ADDITIONAL INFORMATION

N/A

### CODE REVIEW

**Comment by dagwieers** [comment]
The implementations are not the same, so this is problematic IMO.

The old implementation considered everything lowercase that matches ('yes', 'on', '1', 'true', 1) as True, everything else is False.

The new implementation considers only the below:

    BOOLEANS_TRUE = frozenset(('y', 'yes', 'on', '1', 'true', 't', 1, 1.0, True))
    BOOLEANS_FALSE = frozenset(('n', 'no', 'off', '0', 'false', 'f', 0, 0.0, False))

and returns an error otherwise. So this may break stuff that expected the older behaviour.

On top of that, the old implementation would retain None values, while this does not.

I don't think we want to do this.

**Review by dagwieers — CHANGES_REQUESTED** [review]
The implementations are slightly different in how they handle some values (i.e. 't' and floats) and None values.

**Comment by dagwieers** [comment]
BTW I am not in favor of using Emojis/Unicode art in commit messages. If we start to do this we are distracting people from what matters IMO.

The index at https://github.com/ansible/ansible has been bothering me for some time with children_crossing, snake, cherries, and pick emojis. I don't think it helps us in any way.

**Comment by bcoca** [comment]
the new implementation is 'more correct' , but @dagwieers is right , this will break existing plays.

A deprecation message should be in place explaining how the current and future implementations will work, probably with a toggle `strict=false|true` to allow the user to control which one is active

**Comment by dagwieers** [comment]
@bcoca I wouldn't say considering 't' as True is more correct. I wonder where that came from.

**Comment by bcoca** [comment]
i said 'more' but not 'totally' for a reason ... 

also, i agree about emoji, they make git log look funky

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/111001/5/tests

CI failure in integration tests:

- https://app.shippable.com/github/ansible/ansible/runs/111001/14/tests
- https://app.shippable.com/github/ansible/ansible/runs/111001/38/tests
- https://app.shippable.com/github/ansible/ansible/runs/111001/53/tests
- https://app.shippable.com/github/ansible/ansible/runs/111001/68/console

**Comment by bcoca** [comment]
so discussed this with more core members, since this affects a commonly used filter we would prefer a deprecation notice and a transition period, with a toggle,  default to current behaviour and eventually move the default to the 'common implementation

**Comment by samdoran** [comment]
Superseded by https://github.com/ansible/ansible/pull/70721

**Pull request closed without merging**
