### PR TITLE
updates to nxos_bgp_af added purge_networks

### PR DESCRIPTION
**Pull request by hazelfire5**
##### SUMMARY

Fixes the existing issue that removes all other advertised networks when adding a new network to the address-family using `nxos_bgp_af.py` aka `lib/ansible/modules/network/nxos/nxos_bgp_af.py` module. 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

`nxos_bgp_af`
##### ADDITIONAL INFORMATION

When adding networks to a device (`networks:[network1/network2]`) using module `nxos_bgp_af` there seems to be a bug where even when you select `present` it will actually wipe out any other networks currently being advertised in that address-family. I would think that marking it `present` wouldn't force it to delete the others. I have instead, added a new argument that asks about `network_purge` and defaults to `False` and only removes old networks if wanted.

The below should only add `10.3.32.0/24` to the advertisement and leaves the rest alone but instead, wipes out all other networks.
```
---
- name: Advertise BGP Networks
  hosts: lab_nxos
  connection: local
  gather_facts: no
  vars_files:
    - credentials.yml
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      timeout: 60
  tasks:

    - name: BGP add route
      nxos_bgp_af:
        afi: ipv4
        safi: unicast
        asn: 99999
        networks: [10.3.32.0/24]
        vrf: default
        provider: "{{ cli }}"
        state: present
```

#### Expected Results (on device)
```
router bgp 99999
  router-id 10.3.31.253
  cluster-id 10.3.31.253
  timers bgp 2 6
  log-neighbor-changes
  address-family ipv4 unicast
    network 10.3.0.0/22
    network 10.3.8.0/24
    network 10.3.9.0/24
    network 10.3.10.0/24
    network 10.3.11.0/24
    network 10.3.12.0/24
    network 10.3.13.0/24
    network 10.3.14.0/24
    network 10.3.15.0/24
    network 10.3.16.0/23
    network 10.3.24.0/24
    network 10.3.28.0/24
    network 10.3.29.0/24
    network 10.3.30.0/24
    network 10.3.31.4/30
    network 10.3.31.12/30
    network 10.3.31.20/30
    network 10.3.31.128/28
    network 10.3.31.144/28
    network 10.3.31.160/27
    network 10.3.31.253/32
    network 10.3.32.0/24
```
#### Actual Results (on device)
```
router bgp 99999
  router-id 10.3.31.253
  cluster-id 10.3.31.253
  timers bgp 2 6
  log-neighbor-changes
  address-family ipv4 unicast
    network 10.3.32.0/24
```
#### Actual Ansible Output
```
changed: [lab_nxos] => {
    "changed": true, 
    "commands": [
        "router bgp 99999", 
        "address-family ipv4 unicast", 
        "network 10.3.32.0/24", 
        "no network 10.3.0.0/22", 
        "no network 10.3.8.0/24", 
        "no network 10.3.9.0/24", 
        "no network 10.3.10.0/24", 
        "no network 10.3.11.0/24", 
        "no network 10.3.12.0/24", 
        "no network 10.3.13.0/24", 
        "no network 10.3.14.0/24", 
        "no network 10.3.15.0/24", 
        "no network 10.3.16.0/23", 
        "no network 10.3.24.0/24", 
        "no network 10.3.28.0/24", 
        "no network 10.3.29.0/24", 
        "no network 10.3.30.0/24", 
        "no network 10.3.31.4/30", 
        "no network 10.3.31.12/30", 
        "no network 10.3.31.20/30", 
        "no network 10.3.31.128/28", 
        "no network 10.3.31.144/28", 
        "no network 10.3.31.160/27", 
        "no network 10.3.31.253/32"
    ], 
    "invocation": {
        "module_args": {
            "additional_paths_install": null, 
            "additional_paths_receive": null, 
            "additional_paths_selection": null, 
            "additional_paths_send": null, 
            "advertise_l2vpn_evpn": null, 
            "afi": "ipv4", 
            "asn": "99999", 
            "auth_pass": null, 
            "authorize": null, 
            "client_to_client": null, 
            "dampen_igp_metric": null, 
            "dampening_half_time": null, 
            "dampening_max_suppress_time": null, 
            "dampening_reuse_time": null, 
            "dampening_routemap": null, 
            "dampening_state": null, 
            "dampening_suppress_time": null, 
            "default_information_originate": null, 
            "default_metric": null, 
            "distance_ebgp": null, 
            "distance_ibgp": null, 
            "distance_local": null, 
            "host": "lab_nxos", 
            "inject_map": null, 
            "maximum_paths": null, 
            "maximum_paths_ibgp": null, 
            "networks": [
                "10.3.32.0/24"
            ], 
            "next_hop_route_map": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "auth_pass": null, 
                "authorize": null, 
                "host": "lab_nxos", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": 60, 
                "transport": "cli", 
                "use_proxy": true, 
                "use_ssl": null, 
                "username": "username", 
                "validate_certs": null
            }, 
            "redistribute": null, 
            "safi": "unicast", 
            "ssh_keyfile": null, 
            "state": "present", 
            "suppress_inactive": null, 
            "table_map": null, 
            "table_map_filter": null, 
            "timeout": 60, 
            "transport": "cli", 
            "use_proxy": true, 
            "use_ssl": null, 
            "username": "username", 
            "validate_certs": null, 
            "vrf": "default"
        }
    }
}
```

### CODE REVIEW

**Review by trishnaguha — COMMENTED** [review]
Please add test for the new parameter.

**Comment by cb241508** [comment]
not sure if it's been accounted for, but this same thing happens with the "redistribute" parameter as well.  exact same behavior.

**Comment by hazelfire5** [comment]
Sorry guys, just noticed this, let me get working on those Tests as soon as I can.

**Comment by hazelfire5** [comment]
Hey @cb241508 , i was looking into what you said here and I think this should be approached a bit different. What it sounds like is maybe instead of creating a new argument like 'networks_purge', this might be an opportunity to add 'strict' to the 'state' arguments. It seems like 'state' argument functionality is somewhat botched here. 

present - items just needs to be there [already exists]
absent - these specific items need to be gone [already exists]
strict - only these items must exist [to be added]

I think that is likely the better approach here. 

@trishnaguha Any weigh in on this approach? I am gonna start tinkering on that now as it seems like a larger [and tastier] fish to fry and will allow this module to perform better without adding any additional unneeded code.

**Comment by marbarmar** [comment]
The option strict (only these items must exist [to be added]) which @hazelfire5 has described above is exactly what our company need. Will this option be added in the official Ansible "nxos_bgp_af" module? 
If so please let me know in which one. Thank you.

**Comment by hazelfire5** [comment]
Hey @marbarmar / @cb241508 / @trishnaguha ,
I went ahead and made some changes to my code and removed the networks_purge but instead, add the option 'strict'. It should fix the previous issues. I will work on posting tests but so far everything looks good to me.

**Comment by NilashishC** [comment]
Hi @hazelfire5. Thank you for this pull request and apologize for the delay. Here are a couple of points that I wanted to share:

- `state: present` removing existing configuration doesn't seem to be the expected behaviour and definitely looks like a bug to me.

- Your PR does fix this issue. However, IIUC, merging this patch can potentially be a breaking change for existing playbooks that use this module because this is actually changing how `state: present` behaves. Users _may_ expect the module to remove existing `networks` that are not specified in the task and once they upgrade their Ansible version (with this patch in it), their workflow would most likely break.

- With Ansible 2.9, we introduced [Network Resource Modules](https://docs.ansible.com/ansible/devel/network/user_guide/network_resource_modules.html) which operate with [different states](https://docs.ansible.com/ansible/devel/network/user_guide/network_resource_modules.html#network-resource-module-states). Looks like, the `state: strict` in your PR is equivalent to `state: overridden` in the Resource Modules and the altered behaviour of `state: present` is what you'd expect `state: merged` to do.

- We will be working on a consolidated BGP Resource Module for NX-OS later this year. Once the model is ready, you can probably review it and share your thoughts early on.

- As of March 2, 2020, the ansible/ansible GH repo is frozen. All PRs/issues need to be opened against individual collections (https://github.com/ansible-collections/).

**Comment by hazelfire5** [comment]
- Your PR does fix this issue. However, IIUC, merging this patch can potentially be a breaking change for existing playbooks that use this module because this is actually changing how state: present behaves. Users may expect the module to remove existing networks that are not specified in the task and once they upgrade their Ansible version (with this patch in it), their workflow would most likely break.

This seems like a scary decision to retain a bug. If users are moving up incrementally, this shouldn't cause any issues as they can decide when to move to the next version. If they are building and deploying ansible new every time on each build, they could run into issues but thats the problem with doing new builds each time and not pinning your ansible version.

- With Ansible 2.9, we introduced Network Resource Modules which operate with different states. Looks like, the state: strict in your PR is equivalent to state: overridden in the Resource Modules and the altered behaviour of state: present is what you'd expect state: merged to do.

It is interesting, by introducing Network Resource Modules, people MUST retest their playbooks and adapt them to use this new functionality which feels pretty invasive. 

- We will be working on a consolidated BGP Resource Module for NX-OS later this year. Once the model is ready, you can probably review it and share your thoughts early on.

This is too long, I will have to fork this repo myself and do my own fixes away from the Ansible community. I have multiple fixes I have wanted to make to the functionality of Ansible that won't move due to this new version of Ansible. 

- As of March 2, 2020, the ansible/ansible GH repo is frozen. All PRs/issues need to be opened against individual collections (https://github.com/ansible-collections/).

Great.

**Comment by hazelfire5** [comment]
I am closing this PR since there will be no obvious movement.

**Pull request closed without merging**
