### PR TITLE
[Backport] Update connection logic in vmware module_utils

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix updates logic of connection in vmware module_utils.

Fixes: #28577

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/vmware.py

##### ANSIBLE VERSION
```
2.3-stable
```

### CODE REVIEW

**Comment by dagwieers** [comment]
I am surprised this has not been merged yet. I thought we had this done before ?

**Review by dagwieers — APPROVED** [review]

**Comment by dagwieers** [comment]
Ah, this is in the stable-2.3 branch :-)

As I don't know what the rules are with backporting stuff, I prefer if @jctanner or @gundalow look at this one.

**Comment by Akasurde** [comment]
@dagwieers its backport to stable-2.3 branch

**Comment by bcoca** [comment]
FYI, In general we don't use backport PRs, we normally decide on backport when merging to /devel, the person merging should do the backport as they should know the context best at the time. Also backports need to wait during RC process as there is a freeze.

**Pull request merged**
