### PR TITLE
Added json file module.

### PR DESCRIPTION
**Pull request by miguelcnf**
As written in the doc section this module will add, update or delete a specific key on a given json file.
It allows to manage json files without having to use templates, much like the ini_file module.

Miguel

### CODE REVIEW

**Comment by mpdehaan** [comment]
I suspect most people will be just installing JSON files rather than wanting to do key-based surgery on them, but we can think about this one.

Please correct "version_added" to "1.7" and add the GPL license header to this one with appropriate copyright (assigned to you is fine).

**Comment by miguelcnf** [comment]
I have the specific need to do key-based changes on temp files with values retrieved in runtime, hence why I wrote this. 

It might be useful to someone else so I thought of sharing it.

**Comment by antonbabenko** [comment]
:+1: I also need it to just override few keys when dealing with npm & bower

**Comment by miguelcnf** [comment]
@mpdehaan I had this on my fork's devel branch and of course it's getting all the fetching form upstream commits. Do you want me to close it and open a new one on a proper branch?

**Comment by miguelcnf** [comment]
Closing this in favour of #8554 so that changes are in a proper branch.

**Pull request closed without merging**
