### PR TITLE
add updateable tags

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Add updateable tags in azure_rm_sqldatabase module. ----#59392

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_sqldatabase
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Review by gavinfish — APPROVED** [review]
LGTM

**Comment by gavinfish** [comment]
shipit

**Comment by Fred-sun** [comment]
merge_need!

**Comment by gavinfish** [comment]
@haiyuazhang please review this and give a shipit if it makes sense.

**Comment by Fred-sun** [comment]
This PR has been migrated to [#64](https://github.com/ansible-collections/azure/pull/64)

**Pull request closed without merging**
