### PR TITLE
consul_acl: fix broken import

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
Fix [broken import](https://github.com/ansible/community/wiki/Testing%3A-progress-tracker#fixing-broken-imports) in `consul_acl` module.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
consul_acl

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel e3d99e35d3) last updated 2017/12/08 17:21:03 (GMT +200)
```

### CODE REVIEW

**Comment by colin-nolan** [comment]
Looks good to me 👍

**Comment by pilou-** [comment]
@colin-nolan `LGTM`, `+1`, or `shipit` are [recognized](https://github.com/ansible/ansibullbot/blob/master/ansibullbot/triagers/plugins/shipit.py#L14) by the bot (without any character around, space excepted), `Looks good to me` isn't :)

**Comment by colin-nolan** [comment]
@pilou- I know ;) - I was leaving time for sgargan to approve.

However, given his absence and that I now have the power:
shipit

**Comment by colin-nolan** [comment]
shipit

**Pull request merged**
