### PR TITLE
Fixes 27878: subnet should in the virtual network resource group

### LINKED ISSUE #27878: Can't create VM in a VNET that exists in a different resource group in v2.4
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py 

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansibleadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
- none
##### OS / ENVIRONMENT
CentOS 7.2 on Azure
Linux anscontrol01 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY
I am trying to create a new VM in an existing resource group. The VM needs to be part of a vnet/subnet that belongs to another resource group in the same region.

Following is the snippet from the playbook -
  - name: Create a VM in the web server rg
    azure_rm_virtualmachine:
      resource_group: webserverrg <-- This is the resource group where the VM needs to be created
      name: webvm02
      vm_size: Standard_D1_v2
      admin_username: admin2
      admin_password: MyPassword@1
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      os_type: Linux
      virtual_network_resource_group: baserg  <-- This is where the VNET already exists
      virtual_network_name: intvnet  <-- The name of the existing VNET
      subnet_name: websubnet <-- The subnet this VM needs to be part of

When running the playbook - I get the following error -
TASK [Create a VM in the web server rg] *************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: fetching subnet websubnet - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/virtualNetworks/intvnet' under resource group 'webserverrg' was not found."}

It seems the virtual_network_resource_group parameter is not taking effect.

##### STEPS TO REPRODUCE

```yaml
- name: Executing playbook
  hosts: localhost
  connection: local
  tasks:
  - name: Create base resource group
    azure_rm_resourcegroup:
      name: baserg
      location: southindia

  - name: Create internal virtual network
    azure_rm_virtualnetwork:
      name: intvnet
      resource_group: baserg
      address_prefixes_cidr:
        - "10.2.0.0/16"

  - name: Create web subnet
    azure_rm_subnet:
      name: websubnet
      virtual_network_name: intvnet
      resource_group: baserg
      address_prefix_cidr: "10.2.1.0/24"

  - name: Create resource group for web servers
    azure_rm_resourcegroup:
      name: webserverrg
      location: southindia

  - name: Create a VM in the web server rg
    azure_rm_virtualmachine:
      resource_group: webserverrg
      name: webvm01
      vm_size: Standard_D1_
      admin_username: admin2
      admin_password: qazWSX@098
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      os_type: Linux
      virtual_network_name: intnet
      virtual_network_resource_group: baserg
      subnet_name: websubnet
```

##### EXPECTED RESULTS

Expectation was to be able to create a VM in the RG webserverrg which uses the Subnet websubnet from intvnet VNet which exists in RG baserg

##### ACTUAL RESULTS

Failed to create VM with the following error -
"msg": "Error: fetching subnet websubnet - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/virtualNetworks/intvnet' under resource group 'webserverrg' was not found."

```
The full traceback is:
  File "/tmp/ansible_XGz1AX/ansible_module_azure_rm_virtualmachine.py", line 1214, in create_default_nic
    subnet = self.network_client.subnets.get(self.resource_group, virtual_network_name, self.subnet_name)
  File "/usr/lib/python2.7/site-packages/azure/mgmt/network/operations/subnets_operations.py", line 183, in get
    raise exp

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "admin_username": "admin2",
            "allocated": true,
            "append_tags": true,
            "client_id": null,
            "image": {
                "offer": "UbuntuServer",
                "publisher": "Canonical",
                "sku": "16.04-LTS",
                "version": "16.04.201708030"
            },
            "location": null,
            "name": "webvm02",
            "network_interface_names": null,
            "open_ports": null,
            "os_disk_caching": "ReadOnly",
            "os_type": "Linux",
            "password": null,
            "profile": null,
            "public_ip_allocation_method": "Static",
            "remove_on_absent": [
                "all"
            ],
            "resource_group": "webserverrg",
            "restarted": false,
            "secret": null,
            "short_hostname": null,
            "ssh_password_enabled": true,
            "ssh_public_keys": null,
            "started": true,
            "state": "present",
            "storage_account_name": null,
            "storage_blob_name": null,
            "storage_container_name": "vhds",
            "subnet_name": "websubnet",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "virtual_network_name": "intvnet",
            "virtual_network_resource_group": "baserg",
            "vm_size": "Standard_D1_v2"
        }
    },
    "msg": "Error: fetching subnet websubnet - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/virtualNetworks/intvnet' under resource group 'webserverrg' was not found."
}

```

### PR DESCRIPTION
**Pull request by yuwzho**
##### SUMMARY

Fixes #27878

##### ISSUE TYPE

 - Bugfix Pull Request

##### ANSIBLE VERSION

```
2.4
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Cherry-picked to temp-post-staing-2.4.3 https://github.com/ansible/ansible/commit/eb937460b8f136c74e559e034ef8239c4546683c, will be available in the 2.4.4 release.

**Comment by isaacegglestone** [comment]
This is a huge problem for me at the moment any way to get this change before 2.4.4 is released?
I don't particularly want to run a whole dev version just over these three lines in the the one file that are broken.

**Comment by nicolaibaralmueller** [comment]
What is the status of this issue? virtual_network_resource_group does not work at intended. It is not possible to create a vm by referencing vlan in another resource group. This is must feature for our implementation of azure - ansible.

**Comment by isaacegglestone** [comment]
@nicolaibaralmueller.  To mitigate my environment I just pulled down the one file with the issue and added it to my base. That solved my issue. I have my ansible controller continuously update itself with latest code and I noticed that about and a week and half or so (can’t remember the exact date that the file became the same as the one from the latest source.) I think this means if you get the latest the problem will go away but let me know how that goes for you.

**Comment by nicolaibaralmueller** [comment]
@isaacegglestone  Thanks, but we won't be working with dev versions. Company policy only to use official releases.

**Comment by isaacegglestone** [comment]
@nicolaibaralmueller Sorry I wasn’t clear it’s not a dev release it’s the latest stable that had it fixed.  I installed it via pip.

**Comment by jborean93** [comment]
@isaacegglestone you can place this version, the latest devel copy https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py, or a manually edited version in a folder called `library` that is adjacent to your playbook in a roles directory. Ansible will load any module in that folder first before calling on the builtin modules so you can override the default 2.4.3 version with a custom copy without upgrading Ansible.

**Comment by isaacegglestone** [comment]
@jborean93 thanks but there seems to have been a minor update to the stable version because it’s now working for me and after I diff the two files the latest stable was the same as the working version. If that doesn’t turn out to be true for @nicolaibaralmueller then he can do what you suggested.

**Comment by devops-raj** [comment]
This just fixes the subnet issue,
however if you network interface is in a different RG to the VM it's attached to you still get an error even when you define: virtual_network_resource_group
 
eg:
Error fetching network interface mynetworkinterface123 - Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/networkInterfaces/mynetworkinterface123' under resource group 'MyComputeResourceGroup' was not found.

**Comment by karishmakhubchandani** [comment]
Hi I am facing the same issue, I am using ansible version 2.5.2 my vm is in different resource group and my network interface and Virtual network are in different resource group and when i try to create vm through ansible it gives me the same error - rg not found. can anyone please let me know if its resolved else ill have to switch to a different automation tool as its a very critical issue

**Comment by devops-raj** [comment]
@karishmakhubchandani apply the path mentioned in issue #39998
It fixed the issue for me.

**Comment by karishmakhubchandani** [comment]
Hi,

Thanks alot for the help, it worked.

**Comment by karishmakhubchandani** [comment]
@devops-raj  This worked but because of this patch I am not able to start, stop or delete the same vm, it works if NIC and VM are in same RG but it throws an error when NIC and VM are in different RG
NIC rg - dev-network-rg
VM rg - dev-compute-rg
Error message - 
failed: [localhost] (item=11) => {"changed": false, "item": "11", "msg": "Error fetching network interface tdt-test-nic11 - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/networkInterfaces/tdt-test-nic11' under resource group 'dev-compute-rg' was not found."}
any updates on this ?

**Pull request merged**
