### PR TITLE
Added installation instructions for Arch Linux.

### PR DESCRIPTION
**Pull request by TwoD**
Hi, thought I'd make a small contribution to the documentation.
I've built the docs and it looks good but I'd be happy to make any adjustments if deemed necessary.

Cheers,
Henrik

### CODE REVIEW

**Comment by bcoca** [comment]
We might want to add a note about ansible_python_interpreter for localhost on archlinux.

**Comment by amenonsen** [comment]
The change looks good, and the URL it links to is still valid. It can be merged. I don't know where Python lives on ArchLinux, so I can't say what we should say about ansible_python_interpreter, if anything. @bcoca?

**Comment by jody-frankowski** [comment]
@bcoca @amenonsen On archlinux, from the official packages, python is installed in /usr/bin as:
/usr/bin/python -> python3
/usr/bin/python2 -> python2.7

**Comment by amenonsen** [comment]
So we should recommend setting `ansible_python_interpreter=/usr/bin/python2`. @TwoD, feel like adding that to the commit?

**Comment by TwoD** [comment]
I added the same note Gentoo has, and included a link to the ArchWiki in case someone stumbles across something else and notes it there.

**Pull request merged**
