### PR TITLE
Backport of 62152: hall: remove the module for supporting nonexistent messenger

### PR DESCRIPTION
**Pull request by Andersson007**
(cherry picked from commit 8b42de29fac4093c976478ee893845c06ed4bcd6)

##### SUMMARY
Backport of #62152 : hall: remove the module for supporting nonexistent messenger (**from 2015**)

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@gundalow regarding our yesterday's discussion, please look

**Comment by tonyseek** [comment]
shipit

**Review by gundalow — COMMENTED** [review]
Could you please remove `hall.py` from `ignore.txt` as well.

**Review by gundalow — APPROVED** [review]

**Comment by abadger** [comment]
Merged for 2.9.0rc1.

In case anyone is wondering.  The service that provided the backend for this went away in 2015.  So no one can have been using this module since then.  We decided that we didn't need a deprecation period based on how long ago that was.

**Pull request merged**
