### PR TITLE
Adding support for OpenWrt

### PR DESCRIPTION
**Pull request by skinp**
- Add support for OpenWrt detection in setup module
- Add module `opkg` to handle packages on OpenWrt

### CODE REVIEW

**Comment by mpdehaan** [comment]
looks pretty solid.

How many OpenWRTs are you managing?   Curious to see a module for this, but not against it esp. as the code is pretty simple and straightforward.

**Comment by skinp** [comment]
For now, I'm only managing 3 OpenWrt routers. 2 of them being lab machines, I have to reflash or thinker with them quite often so being able to automate the reinstallation to a baseline is priceless...

**Comment by dhozac** [comment]
Interesting. Do you know how common Python is on them? I know all of ours are lacking that, and don't really have enough space to install it, so I have an opkg module in sh that I use.

**Comment by skinp** [comment]
I might have been lucky... all of my OpenWrt routers have enough space to handle a python installation.  

Don't you have any with USB ports? I do have one where I had to install python on an external USB drive...

**Comment by dhozac** [comment]
Our OpenWRT/OpenEmbedded boxes do have USB, but additional storage is not exactly what that is used for. They're embedded devices controlling various machines, and they number in the hundreds...

I was mostly curious how typical Python was on them, if this was going to be generally useful. Sounds like that's a yes, and it looks good to me. You can set type='list' on the name parameter to have it automatically split on , for you, and accept a complex argument list.

**Comment by mpdehaan** [comment]
merged, thanks, additional upgrades are of course welcome, and what Daniel says about list would be good to add.

**Pull request merged**
