### PR TITLE
Iterative template

### PR DESCRIPTION
**Pull request by dhozac**
This is for variables containing variables. The implementation is potentially a bit too simplistic, and it does have performance implications.

Here are the times (in seconds) 100000 iterations took on my laptop with the unmodified code, modified with a plain variable and modified with a variable in a variable.

varReplace-based template: 0.87
varReplace-based iterative template: 1.22
varReplace-based iterative template (2 iterations): 2.05
Jinja2-based template: 70.03
Jinja2-based iterative template: 117.72
Jinja2-based iterative template (2 iterations): 185.16

### CODE REVIEW

**Comment by dhozac** [comment]
(Performance testing script is at https://gist.github.com/2941061)

**Comment by mpdehaan** [comment]
This does something different than I think a lot of folks were asking for, but maybe you meant to do something different.   The use case many people have is say they have a common path segment, like "installDir", and then in the same variable section they want to reuse installDir:

```
vars:
   - installDir: "/srv"
   - fooDir: "$installDir/foo"
```

Do to this, we just have to loop through the variables and repeatedly template against a dictionary of vars that keeps getting updated as we go, but the template engine just needs to run once.

What is the use case for needing to run the template engine twice?

**Comment by mpdehaan** [comment]
nevermind -- I see it is accomplishing the same thing, just another way.

basically in my example we'd be templating once per variable in the list, which may be just as bad if there was a long list of a variables.  This seems reasonable to me.

merging, thanks!

**Comment by dhozac** [comment]
Right. This way it performs the substitution at point of use, allowing e.g. vars_files to override the referenced variable, or even with_items.

**Pull request merged**
