### PR TITLE
ec2_metric_alarm: TreatMissingData feature (attempt #3)

### PR DESCRIPTION
**Pull request by ediskandarov-cur**
##### SUMMARY

This introduces option for `TreatMissingData` in `ec2_metric_alarm` module.

There is alread pull request for this, but it was abandoned by the author. I rebased it and made sure things works correctly (as reported by someone from the community in referenced issues).

Existing pull request: #23407 #33086
Issues:

#28160
#23493

##### ISSUE TYPE

* Feature Pull Request

##### COMPONENT NAME
ec2_metric_alarm module

##### ANSIBLE VERSION

```
ansible --version
ansible 2.5.0
  config file = None
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

### CODE REVIEW

**Comment by ediskandarov-cur** [comment]
I took branch of PR #33086 as a base and made a rebase from `ansible:devel` as was requested.

**Comment by ediskandarov-cur** [comment]
Had to squash commits..

**Comment by willthames** [comment]
All feature requests (including boto3 ports) require tests. See https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/GUIDELINES.md#integration-tests-for-aws-modules for some documentation

It's also worth meeting the same AWS guidelines to use AnsibleAWSModule for improved AWS connection handling and exception handling

**Comment by joebowbeer** [comment]
Has the third attempt to add support for this important missing feature been abandoned?

**Pull request closed without merging**
