### PR TITLE
added parameter for allowing prerelease packages in win_chocolatey fo…

### LINKED ISSUE #33243: win_chocolatey: Installing latest prerelease packages not implementet?
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`win_chocolatey`

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/ubuntu/vault.txt
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
From Ubuntu 17.04
Against Windows Server 2012R2

##### SUMMARY
I can't find any way to install the *latest* prerelease of a Chocolatey package without setting the version for the package explicit. In the Chocolatey CLI this is done with a `--pre` or `--prerelease` flag. 
The args that are available in the module is `install_args` and `params`, none of them can take `--pre` as an argument. I guess `prerelease: yes` in combination with `state: latest` must be implemented to do what I want. The case comes when we are developing new tools and want to test them out as prerelease packages before bumping to stable. 

##### STEPS TO REPRODUCE
Have a Chocolatey package on a feed, only available as prerelease (no stable yet). 

```yaml

- name: Install SomeTool
     win_chocolatey: name=SomeTool source="{{ InternalSoftwareChocoFeed }}" state=latest
     tags: SomeTool
```

OR 

```yaml
- name: Install SomeTool
     win_chocolatey: name=SomeTool source="{{ InternalSoftwareChocoFeed }}" state=latest install_args="--pre"
     tags: SomeTool
```

##### EXPECTED RESULTS
Install latest prerelease package if some flag is given. 

##### ACTUAL RESULTS

```
fatal: [SomeServer]: FAILED! => {
    "changed": false,
    "choco_error_cmd": "choco.exe install -v --no-progress -y SomeTool --timeout 2700 --failonunfound --source SomeFeed --installargs --pre",
    "choco_error_log": [
        "Chocolatey v0.10.7",
        "Installing the following packages:",
        "SomeTool",
        "By installing you accept licenses for the packages.",
        "SomeTool not installed. The package was not found with the source(s) listed.",
        " If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.",
        " Version: \"\"",
        " Source(s): \"SomeFeed\"",
        "",
        "Chocolatey installed 0/1 packages. 1 packages failed.",
        " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).",
        "",
        "Failures",
        " - SomeTool - SomeTool not installed. The package was not found with the source(s) listed.",

        " If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.",
        " Version: \"\"",
        " Source(s): \"SomeFeed\""
    ],
    "command": "choco.exe install -v --no-progress -y SomeTool --timeout 2700 --failonunfound --source SomeFeed --installargs --pre",
    "failed": true,
    "msg": "Error installing package 'SomeTool'",
    "rc": 1,
    "stdout": "Chocolatey v0.10.7\r\nInstalling the following packages:\r\nSomeTool\r\nBy installing you accept licenses for the packages.\r\nSomeTool not installed. The package was not found with the source(s) listed.\r\n If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.\r\n Version: \"\"\r\n Source(s): \"SomeFeed\"\r\n\r\nChocolatey installed 0/1 packages. 1 packages failed.\r\n See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).\r\n\r\nFailures\r\n - SomeTool - SomeTool not installed. The package was not found with the source(s) listed.\r\n If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.\r\n Version: \"\"\r\n Source(s): \"SomeFeed\"\r\n",
    "stdout_lines": [
        "Chocolatey v0.10.7",
        "Installing the following packages:",
        "SomeTool",
        "By installing you accept licenses for the packages.",
        "SomeTool not installed. The package was not found with the source(s) listed.",
        " If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.",
        " Version: \"\"",
        " Source(s): \"SomeFeed\"",
        "",
        "Chocolatey installed 0/1 packages. 1 packages failed.",
        " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).",
        "",
        "Failures",
        " - SomeTool - SomeTool not installed. The package was not found with the source(s) listed.",

        " If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.",
        " Version: \"\"",
        " Source(s): \"SomeFeed\""
    ]
}
```
As you can see, with `install_args` the command that is executed becomes `--installargs --pre`.

### PR DESCRIPTION
**Pull request by andmos**
##### SUMMARY

Support `--prerelease` flag for installing prerelease Chocolatey packages. 
Fixes #33243

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

win_chocolatey
##### ANSIBLE VERSION

```
ansible --version
ansible 2.6.0 (devel 02999b77a4) last updated 2018/03/08 14:34:37 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /vagrant/ansible/lib/ansible
  executable location = /vagrant/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

Before this change, installation of package fails if only prerelease package is available in the feed.
Now picks the prerelease package. If stable package is installed, `state=latest` and `prerelease=yes`:
```
 "stdout_lines": [
        "Chocolatey v0.10.8",
        "Upgrading the following packages:",
        "dips-dbupgrade",
        "By upgrading you accept licenses for the packages.",
        "",
        "You have dips-dbupgrade v2.4.0 installed. Version 16.0.1-build0001 is available based on your source(s).",
        "[NuGet] Attempting to resolve dependency 'dips-dwdba (≥ 10.0.1)'.",
        "[NuGet] Uninstalling 'dips-dbupgrade 2.4.0'.",
        "[NuGet] Successfully uninstalled 'dips-dbupgrade 2.4.0'.",
        "[NuGet] Installing 'dips-dbupgrade 16.0.1-build0001'.",
        "[NuGet] Successfully installed 'dips-dbupgrade 16.0.1-build0001'.",
        "",
```

### CODE REVIEW

**Comment by andmos** [comment]
If we find a package available as prerelease at chocolatey.org I'm sure we can add some tests for this too.

**Comment by andmos** [comment]
@jborean93 @jhawkesworth if somebody can take a look at this PR before it grows old that would be great. As far as I know this parameter scratches the itch me and my guys have, so there is no rush - 2.6 release is an OK target.

**Review by dagwieers — APPROVED** [review]
Code looks fine.

**Comment by dagwieers** [comment]
I don't object to this, although I have no need for it and have no understanding of how this could interact with other invocations without this option. It clearly is a niche feature.

**Comment by andmos** [comment]
We had the case where we needed to test some chocolatey packages in a staging environment before we mark them as "stable" in the next phase, thus the prerelease-number. So we want to be able to install the *latest prerelease* packages in some environments without specifying the exact version of the package as we have to do today. We also had a case where the only available package in the feed was a prerelease package, which was the main case for the issue.

**Comment by dagwieers** [comment]
@andmos Are you contributing to Chocolatey packages ?

**Comment by andmos** [comment]
We use Chocolatey for packing software at the company where I work, so we have some private NuGet servers we push a lot of private built packages to, yes. Some of these will be released to chocolatey.org in a near future. So yes, I work with Chocolatey (have also contributed to the project) but don't have anything publicly on chocolatey.org yet.

**Comment by dagwieers** [comment]
Ok, so since v2.6 is still in its infancy and this is a community supported module I don't see why we can't put this into the hands of people that need this and see where this leads us ;-)

**Pull request merged**
