### PR TITLE
Play recap stats and callbacks for include_role, consolidate with include_tasks

### LINKED ISSUE #77336: callback: An include_role task failure triggers a v2_runner_on_ok hook instead of v2_runner_on_failed
### Summary

When include_role fails -- for example, when it can't find the role it is meant to include -- it does not seem to be considered a failure. The playbook stats summary shows ``failed=0`` and the task fires ``v2_runner_on_ok`` instead of ``v2_runner_on_failed``.

The ansible-playbook command exits with exit code 2, correctly detecting the failure.

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/home/dmsimard/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dmsimard/dev/virtualenvs/ansible/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/dmsimard/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dmsimard/dev/virtualenvs/ansible/bin/ansible
  python version = 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = ['/home/dmsimard/dev/virtualenvs/ansible/lib64/python3.10/site-packages/ara/plugins/callback']
```

### OS / Environment

Fedora 35, though it should not be relevant to the issue.

### Steps to Reproduce

I originally bumped into the issue in ara integration tests with a regular playbook (https://github.com/ansible-community/ara/issues/346) but I've included two reproducers in this gist: https://gist.github.com/dmsimard/8c77ea6db405fbf7b11e8f78f8818afb

### Expected Results

The include_role failure should be interpreted as a failure (``v2_runner_on_failed``), NOT as 'ok' via ``v2_runner_on_ok``.

This is my naive view from the perspective of the callback interface, I have not yet investigated why this is happening.

### Actual Results

```console
$ ansible-playbook successful.yml || echo $?
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
2022-03-22 20:38:43,314 DEBUG ara.plugins.callback.default: v2_playbook_on_start

PLAY [Reproducer that does not fail] ********************************************************************************************************************************************************************************************************************
2022-03-22 20:38:43,357 DEBUG ara.plugins.callback.default: v2_playbook_on_play_start

TASK [A successful task] ********************************************************************************************************************************************************************************************************************************
2022-03-22 20:38:43,448 DEBUG ara.plugins.callback.default: v2_playbook_on_task_start
2022-03-22 20:38:43,469 DEBUG ara.plugins.callback.default: v2_runner_on_start
ok: [localhost] => {
    "msg": "Hello o/"
}
2022-03-22 20:38:43,480 DEBUG ara.plugins.callback.default: v2_runner_on_ok

TASK [Include a role that does not exist] ***************************************************************************************************************************************************************************************************************
2022-03-22 20:38:43,566 DEBUG ara.plugins.callback.default: v2_playbook_on_task_start
2022-03-22 20:38:43,609 DEBUG ara.plugins.callback.default: v2_runner_on_start
2022-03-22 20:38:43,617 DEBUG ara.plugins.callback.default: v2_runner_on_ok   # <-- should be v2_runner_on_failed
ERROR! the role 'does_not_exist' was not found in /home/dmsimard/dev/sandbox/include_role/roles:/home/dmsimard/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/dmsimard/dev/sandbox/include_role

The error appears to be in '/home/dmsimard/dev/sandbox/include_role/successful.yml': line 11, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      include_role:
        name: does_not_exist
              ^ here

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
# failed should be 1 above

2022-03-22 20:38:43,693 DEBUG ara.plugins.callback.default: v2_playbook_on_stats
2 # <-- Exit code 2 (non-zero)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

This moves handling of callbacks and play recap stats from
_load_included_file to individual strategies so include_role tasks are
accounted for, not just include_tasks.

Fixes #77336

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by webknjaz** [comment]
Needs rebase.

**Review by bcoca — CHANGES_REQUESTED** [review]
Code mostly LGTM, but i would add a toggle in `_load_included_file`, then guard the code instead of removing it, to allow for other strategy plugins to still use the current code, otherwise they'll 'lose' the ability to track results.   We can add deprecation layer and point to this PR for implementation if needed.

**Review by bcoca — APPROVED** [review]

**Review by s-hertel — APPROVED** [review]

**Pull request merged**
