### PR TITLE
rabbitmq_binding: Add support for state=absent

### PR DESCRIPTION
**Pull request by sn4kebite**
##### SUMMARY
Add support for setting state=absent so that bindings can be deleted.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
rabbitmq_binding

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0 (devel 03f71e778b) last updated 2018/11/13 13:28:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jon/ansible-git/lib/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### ADDITIONAL INFORMATION
Example playbook:
```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: rabbitmq exchange
      rabbitmq_exchange:
        name: test
        type: direct
    - name: rabbitmq queue
      rabbitmq_queue:
        name: test
    - name: rabbitmq bindings
      rabbitmq_binding:
          source: test
          destination: test
          routing_key: 'foo'
          type: queue
          state: absent
```

Before change (after binding has been created):
```paste below
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq exchange] ******************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq queue] *********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq bindings] ******************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0
```

After change:
```paste below
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq exchange] ******************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq queue] *********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rabbitmq bindings] ******************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0
```

### CODE REVIEW

**Comment by Shaps** [comment]
Looks ok to me

**Review by gundalow — APPROVED** [review]
Change looks good, thank you for this :)

**Comment by Shaps** [comment]
Hi @sn4kebite, would you be able to add some tests for this module as well? 
I believe this should be considered an actual bug since module accepted `state=absent` but did nothing about it.

**Review by gundalow — COMMENTED** [review]
Thank you for adding the integration tests, and tidying up the existing setup task.

Could you please add a changelog then we will merge this into devel for release in Ansible 2.8 https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@sn4kebite Thanks, merged into `devel` for release in Ansible 2.8
@Shaps Thanks for the review!

**Pull request merged**
