### PR TITLE
Allow vault commands to work with a symlink, by manipulating the real file

### PR DESCRIPTION
**Pull request by sivel**
##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
`parsing/vault/__init__.py`

##### ANSIBLE VERSION

```
v2.3
```

##### SUMMARY

This PR allows the vault commands to work against a symlink by editing the real file, and not replacing the symlink.

This is done via a decorator on the public methods.  I looked into treating the problem at a lower level, unfortunately, the API is a bit inconsistent, and as a result, there are too many places where the file may be manipulated.

### CODE REVIEW

**Comment by sivel** [comment]
I'm having some small problems with the docker containers not all having vi installed, in order to perform the tests against `ansible-vault edit`.

I'm debating as a result, switching to unit instead of integration tests here.  Getting the tests right is going to a take a little more time.

**Comment by bcoca** [comment]
sadly there are heathens out there that think an editor different than vi should be the distro default!

**Comment by sivel** [comment]
Ok, all tests rewritten and passing.

**Comment by sivel** [comment]
Resolved by #20417

**Pull request closed without merging**
