### PR TITLE
Document that lookups are evaluated on server side

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by techtonik** [comment]
From here https://groups.google.com/forum/#!topic/ansible-project/96XWmqlCtSc

**Comment by mpdehaan** [comment]
While this is true, "outside sources" can also mean web services.

I'd prefer another sentence be added here.

Lookup plugins allow access of data in Ansible from outside sources.   These lookups are evaluated on the control machine and can include file contents on the control machine, or even remote data services such as values in a datastore such as Redis.

Something like that?

**Comment by techtonik** [comment]
Something is very wrong with my typing abilities today. PTAL.

**Comment by mpdehaan** [comment]
I'll tweak this one.  Thanks for the heads up.

**Comment by mpdehaan** [comment]
Done, thanks!

**Pull request closed without merging**
