### PR TITLE
New template_from_string implementation.

### PR DESCRIPTION
**Pull request by Tinche**
A few unit tests for said implementation.

### CODE REVIEW

**Comment by mpdehaan** [comment]
looks good, I think I realized I also have to test what happens when it evaluates things that are hashes and such for passing them around, but this itself is solid.

In queue for testing, thanks!

**Comment by Tinche** [comment]
Hi, any news on this?

If you can think of a scenario where this fails, I'd love a failing test (or two) and I can work on it further.

**Comment by mpdehaan** [comment]
Been travelling.  Still in queue for testing.

Don't worry, not planning on rejecting it.

**Comment by Tinche** [comment]
No probs, just checking up. No rush or anything :)

**Comment by mpdehaan** [comment]
I got templates working recently using a very similar implementation so I believe we can close this one.

Yes, we do want more tests in regard to that though!

**Pull request closed without merging**
