### PR TITLE
runtime-metadata sanity test: do not fail deprecation version checks if galaxy.yml has empty `version`

### LINKED ISSUE #83822: ansible-test sanity fails when deprecating modules without version in galaxy.yml
### Summary

I wanted to deprecate a module in ansible-collections/community.vmware#2136 but ran into a failing sanity CI workflow.

I like to have `version: null` in `galaxy.yml` for code that doesn't have a version because it's not been released. But this runs into a very serious problem (traceback) here:

https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py#L92-L93

Sorry, but I can't "complete all sections as described" since this is a GHA workflow that fails and I'm not 100% sure what it's based on. But I hope the information I'm giving you is enough to understand the problem.

### Issue Type

Bug Report

### Component Name

ansible-test

### Ansible Version

```console
2.15 and later
```

### Configuration

```console
I don't know what the CI workflow really uses.
```

### OS / Environment

I don't know what the CI workflow really uses.

### Steps to Reproduce

Deprecate a module while having `version: null` in `galaxy.yml` of the collection.

### Expected Results

At least a "normal" fail and error message, but actually I would like you to skip the test in this case. I'll open a feature request for this so you can handle both issues independently: #83823

### Actual Results

```console
Traceback (most recent call last):
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py", line 310, in <module>
    main()
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py", line 303, in main
    validate_metadata_file(
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py", line 279, in validate_metadata_file
    schema(routing)
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 274, in _exec
    return func(path, v)
           ^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 274, in _exec
    return func(path, v)
           ^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 274, in _exec
    return func(path, v)
           ^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 274, in _exec
    return func(path, v)
           ^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.ansible/test/venv/sanity.runtime-metadata/3.11/d1d5b1f1/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py", line 93, in removal_version
    if version <= current_version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ansible/lib/ansible/utils/version.py", line 264, in __le__
    return self._cmp(other) <= 0
           ^^^^^^^^^^^^^^^^
  File "/root/ansible/lib/ansible/utils/version.py", line 226, in _cmp
    if self.core < other.core:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### LINKED ISSUE #83823: ansible-test sanity: Ignore deprecating modules without version in galaxy.yml
### Summary

This is a follow-up to #83822

I wanted to deprecate a module in ansible-collections/community.vmware#2136 but ran into a failing sanity CI workflow.

I like to have `version: null` in `galaxy.yml` for code that doesn't have a version because it's not been released. But this runs into a very serious problem (traceback) here:

https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py#L92-L93

I think the test should succeed for `version: null` in `galaxy.yml`.

### Issue Type

Feature Idea

### Component Name

ansible-test

### Additional Information

This would allow me to have `version: null` in `galaxy.yml` for code that doesn't have a version because it's not been released and still deprecate modules.

Once I really prepare / want to do a release, I'll add the version to `galaxy.yml` and the test would kick in again and tell me about any problems there.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #83822.
Closes #83823.

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by bcoca** [comment]
can you add a test?

**Comment by felixfontein** [comment]
Sure thing. I've added some very basic tests for runtime-metadata which check the problems fixed here, and allow to test more things in the future.

While working on that I noticed that `SemanticVersion.parse()` does not set `self.vstring`, which results in `__repr__()` printing `SemanticVersion(None)`. Since the pattern `version = SemanticVersion()` / `version.parse(...)` is used multiple times in ansible-test (including the one introduced in this test, it's used four times), I think it's better to fix that as well.

**Comment by mariolenz** [comment]
I'm trying to understand why the CI failed, but I'm afraid I don't. Does it have something to do with this PR or is it unrelated?

Sorry if this is a dumb question, but I don't understand the log at all. I didn't have many opportunities to follow how the ansible (-core) CI works since you've moved the modules I'm interested in to separate collections. But the CI failure _looks_ to me like it might be unrelated to this PR.

**Comment by bcoca** [comment]
yep, i re ran from interface, it was a unrelated transitory error with test setup

**Comment by felixfontein** [comment]
@bcoca thanks for reviewing and merging!

**Comment by felixfontein** [comment]
Backports in #83856 #83857 #83858.

**Pull request merged**
