### PR TITLE
Fix illegal set operation in FreeBSD section of user module.

### PR DESCRIPTION
**Pull request by tronner**
This fixes issue #4461.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This appears to have a lot of merge requests and other junk in it now.

I would suggest starting each new fix on a different branch in github to avoid this.

Also always use "git pull --rebase" vs "git pull" and "git rebase" vs "git merge" to avoid merge commits, as we do not allow those in the history as they present review problems.

Thank you!

**Comment by mpdehaan** [comment]
Looks like you might want to set up a new branch and just cherry-pick this commit.

**Comment by tronner** [comment]
Thanks for your answer.

Yes, it's a little messy like this :)

100% agree on the merge commits. I hate those too and always use rebase instead of merge, but haven't incorporated that in my github workflow yet because it isn't entirely clear to me how. Can you recommend me documentation that describes your git workflow with github?

I can't find how to change this pull request, so I will create a new one. Correct?

**Comment by mpdehaan** [comment]
Yeah I would create a new one.

I actually can commit direct but roughly:

git checkout -b topic_branch_name

# work on stuff as you would want to

git commit -a

# maybe another commit

git commit -a

# pull in the latest upstream changes

git fetch

# move my commits to the top of the stack

git rebase origin devel 

# push my current branch to my github

git push topic_branch_name # push to my repo on github

# make pull request to ansible/ansible project from github

**Comment by mpdehaan** [comment]
that formatting was totally non-intentional :)

**Comment by mpdehaan** [comment]
closing this, please resubmit as per above and let me know if you have any questions.

Thanks!

**Pull request closed without merging**
