### PR TITLE
git - use remote_tmp directory

### LINKED ISSUE #30064: Cannot use git module with custom `key_file` or `ssh_opts` as non-root user on system with noexec `/tmp`
##### ISSUE TYPE

bug report

##### COMPONENT NAME

git module

##### ANSIBLE VERSION

1.9.2
$ ansible --version
ansible 1.9.2
configured module search path = None

##### CONFIGURATION

$ cat ansible.cfg
[defaults]
roles_path=roles/

##### OS / ENVIRONMENT

CentOS 6.5.

##### SUMMARY

**:

When using `key_file` or `ssh_opts` with the git module, it writes an ssh wrapper script to a temporary location and then git executes it.

This temporary script is written to the module dir, if accessible to the current user, or otherwise to the default system temp dir.

When sudoing to a non-root, non-ansible user, the module dir generally isn't be accessible, so it falls back to the system temp dir.

But in a system with a noexec-mounted `/tmp` dir, this fails with "cannot exec: permission denied", as originally reported in https://github.com/ansible/ansible/issues/6567

This is the same basic scenario as https://github.com/ansible/ansible/issues/7375, but the fix there failed to account for the noexec-tmp possibility.

**

##### STEPS TO REPRODUCE

**:

On a target system with a noexec-mounted `/tmp`, run a task such as this:

```
- name: clone MyProject codebase
  sudo_user: "{{ myproject_user }}"
  git: repo={{ myproject_repo_clone_url }}
       version={{ myproject_ref }}
       key_file={{ myproject_home }}/deploy_key
       dest={{ myproject_repo_dir }}
```

**

##### EXPECTED RESULTS

**:

Repo should be successfully cloned, as the given `sudo_user`, using the given `key_file`.

**

##### ACTUAL RESULTS

**:

```
TASK: [myrole | clone MyProject codebase] ************************************ 
failed: [server.example.com] => {"cmd": "/usr/bin/git ls-remote 'ssh:********@github.com/myorg/MyProject.git' -h refs/heads/master", "failed": true, "rc": 128}
stderr: fatal: cannot exec '/tmp/tmpyWsoGi': Permission denied
fatal: unable to fork

msg: fatal: cannot exec '/tmp/tmpyWsoGi': Permission denied
fatal: unable to fork
```

Copied from original issue: ansible/ansible-modules-core#1912

### LINKED ISSUE #33947: Ansible git module ignores remote_tmp
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /Users/tbessoussa/workspace/System/ansible.cfg
  configured module search path = [u'/Users/tbessoussa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
```
DEFAULT_BECOME(/Users/tbessoussa/workspace/System/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/Users/tbessoussa/workspace/System/ansible.cfg) = sudo
DEFAULT_REMOTE_TMP(/Users/tbessoussa/workspace/System/ansible.cfg) = /var/www/tmpansible
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Git module fails because it IGNORES the `remote_tmp` variable and always uses `/tmp/` for temp dir.

##### STEPS TO REPRODUCE
Disallow execution for `/tmp`
Put a `remote_tmp = /var/www/tmpansible`
Run your playbook containing the git module: 

```yaml
- name: Git checkout version
  run_once: true
  git:
    repo: git@github.com:xxxx.git
    dest: "..."
    force: yes
    version: "..."
  register: git_deploy
  until: git_deploy|succeeded
```

##### EXPECTED RESULTS
I except the clone to be done, but instead it fails.

##### ACTUAL RESULTS

```
FAILED! => {"attempts": 2, "changed": false, "cmd": ["/usr/bin/git", "fetch", "--tags", "origin"], "failed": true, "msg": "Failed to download remote objects and refs:  fatal: cannot exec '/tmp/tmpw24enb': Permission denied\nfatal: unable to fork\n"}
```

### PR DESCRIPTION
**Pull request by narimantos**
##### SUMMARY

fixes: #33947 
fixes: #30064

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

git

##### ADDITIONAL INFORMATION

This is my first contribution to the Ansible repo. I will look into refining tests for this change. 
Any pointers are welcome! 

```paste below

```

### CODE REVIEW

**Review by samdoran — CHANGES_REQUESTED** [review]
Thank you for fixing this issue. Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

Regarding tests, this may be a bit tricky to test. From reading the original issue, it seems we need to mount a directory with `noexec`, then run a play using a different tmp dir to make sure it is honored.

It's probably best to do that in a separate integration test target rather than incorporating it with the existing tests. Briefly, our integration tests are located at ` test/integration/targets`. Each directory is an Ansible role, _but_ if there is ` runme.sh` or `runme.py`, that will be run instead of treating the directory like a role.

In my testing, it doesn't seem we'll be able to remount `/tmp` with `noexec` inside a container, so some other solution will be needed. Maybe setting `ANSIBLE_KEEP_REMOTE_FILES=1`, setting that as the `remote_tmp`, then looking at it after the test ran? I'm not sure.

**Comment by myounsi1616** [comment]
I have tested this fix on one of our server which has /tmp mount as noexec and it worked as expected.

**Review by samdoran — APPROVED** [review]

**Comment by samdoran** [comment]
rebuild_merge

**Comment by samdoran** [comment]
Please create a [backport PR](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs) for this to be included in previous versions.

**Pull request merged**
