### PR TITLE
ec2_vol improvements

### PR DESCRIPTION
**Pull request by blair**
/cc @lwade

### CODE REVIEW

**Comment by blair** [comment]
BTW, I'm having a problem updating the docs, so the changes do not update them.

Blair

```
$ make docs
PYTHONPATH=./lib python hacking/module_formatter.py -A 1.1 -t man -o docs/man/man3/ --module-dir=library --template-dir=hacking/templates
 processing module source ---> library/add_host
 processing module source ---> library/apt
 processing module source ---> library/apt_key
 processing module source ---> library/apt_repository
 processing module source ---> library/assemble
 processing module source ---> library/async_status
 processing module source ---> library/async_wrapper
 processing module source ---> library/authorized_key
 processing module source ---> library/bzr
Traceback (most recent call last):
  File "hacking/module_formatter.py", line 347, in <module>
    main()
  File "hacking/module_formatter.py", line 338, in main
    return_data(text, options, outputname, module)
  File "hacking/module_formatter.py", line 130, in return_data
    f.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 930: ordinal not in range(128)
make: *** [modulepages] Error 1
```

**Comment by ciupicri** [comment]
That's going to be fixed by pull https://github.com/ansible/ansible/pull/2432

**Comment by blair** [comment]
I rebased (locally only) this branch on top of the #2432 fix and did 'make docs' but it made to changes.  Are the docs not changed into 'devel' any more?  Suggest updating github's comment about what to do before submitting a pull request.

**Comment by lwade** [comment]
Hi @blair, agreed something needs to be done here to make this better since my logic is broken anyhow.  However, I don't think your proposal is correct.  What I was trying to do with inst.root_device_type is basically determine that if the instance is EBS-backed, it'll be either Windows or Linux (since non-EBS Windows is unlikely), thus default to the Windows best practices (/dev/sdb onwards) which is possible with Linux but not recommended.  If it's not EBS backed, it's probably Linux and therefore use /dev/sdf onwards.  

So in your patch, the != 'ebs' would still be /dev/sdf (not /dev/sdb) per best practices here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html

This is all quite messy anyhow, so what I've done is actually write a conditional statement which properly checks to see whether its windows or not (based on password data):  https://github.com/ansible/ansible/pull/2442

Regarding commit 27b426f, I'd suggest adding a helpful message to the user as well:

module.exit_json(msg="Volume mapping already exists on the host", changed=False)

... or suchlike.

**Comment by blair** [comment]
Thanks for the suggestion on the message, I'll add that.

We must be looking at different web pages ;)

For EBS Linux: recommended is /dev/sd[f-p] and /dev/sd[f-p][1-6]
For EBS Windows: recommended is xvd[f-p]
For instance storage Linux: /dev/sd[b-e]
For instance storage Windows: xvd[a-e]

Actually, looking at this more, given this is for attaching an EBS volume, it should always be [f-p] regardless of OS?

**Comment by lwade** [comment]
When that page talks about instance store volumes it's not talking about instance store backed instances but for ephemeral space you can allocate as additional volumes.  Thus it's not differentiating between instance types.

However the windows best practice is for xvd[a-e] and I guess Windows users don't care about the underlying device name anyway, so this _should_ be changed.

**Comment by blair** [comment]
OK, now I'm more confused.  The ec2_vol at the top says "creates an EBS volume and optionally attaches it to an instance."  So in my mind we're not even talking about ephemeral space?  This module doesn't work with anything but EBS volumes, right?

**Comment by lwade** [comment]
Correct but the block device mapping pages aren't talking about EBS-backed and instance-store-backed instances.  They are only talking about EBS volumes and ephemeral storage volumes against hosts, so they aren't differentating against the two, i.e.:

> For EBS Linux: recommended is /dev/sd[f-p] and /dev/sd[f-p][1-6]
> For EBS Windows: recommended is xvd[f-p]
> For instance storage Linux: /dev/sd[b-e]
> For instance storage Windows: xvd[a-e]

**Comment by mpdehaan** [comment]
what is the consensus on this?

**Comment by blair** [comment]
I suggest merging https://github.com/ansible/ansible/pull/2442 and then I'll rebase this and make the suggested corrections and @lwade can review it again.

**Comment by mpdehaan** [comment]
ok that sounds reasonable, @lwade see if you can answer my questions on
#2442 about the password thing.   I'm a little hesitant to merge it because
I don't understand why it's checking for the OS that way.

**Comment by mpdehaan** [comment]
@blair merged #2442, if you would like to update this go ahead.   Releae date for this release is scheduled for Tuesday, but this was in progress so I'm fine with considering it for making 1.1.

**Comment by blair** [comment]
@mpdehaan @lwade rebase is done and incorporated lwade's advice.

**Comment by mpdehaan** [comment]
@lwade -- mind helping review?

This is past our 1.1 feature freeze cutoff,  so it looks like this will go into 1.2.

**Comment by mpdehaan** [comment]
I'm not sure we need the sudo comment.  It seems obvious and generic to ansible in general.

**Comment by mpdehaan** [comment]
dependencies are also now handled with the 'requirements' documentation YAML...

**Comment by mpdehaan** [comment]
if you can update these things and submit a new pull request we can include them.  Thanks.

**Pull request closed without merging**
