### PR TITLE
Added preferred group attribute to EPG for mso_schema_template_anp_epg 

### PR DESCRIPTION
**Pull request by nkatarmal-crest**
##### SUMMARY

Added support for enabling a preferred group in MSO while creating EPG. 
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mso_schema_template_anp_epg

### CODE REVIEW

**Review by devarshishah3 — CHANGES_REQUESTED** [review]
please add the attribute in the example in the comments as well

**Review by devarshishah3 — APPROVED** [review]

**Comment by devarshishah3** [comment]
@gundalow : Please let me now what needs to be done in order to merge this. This is an ask from a  joint customer

**Comment by Qalthos** [comment]
https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#when-will-your-pull-request-be-merged

**Comment by dagwieers** [comment]
rebuild_merge

**Pull request merged**
