### PR TITLE
Do not wipe contracts when modifying epg

### LINKED ISSUE #62137: MSO EPG rerun removes contracts
##### SUMMARY
When rerunning this module, if contracts are applied to the EPG , this module will remove all contracts and come back with a status of changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mso_schema_template_anp_epg

##### ANSIBLE VERSION

```
ansible 2.8.2
```

##### STEPS TO REPRODUCE

To test, built the EPG with the config below. I would just manually assign a contract in MSO. Rerun playbook and it will wipe out the contracts. Static Subnets on the EPG appear unaffected.

```
  - name: Creating EPGs
    mso_schema_template_anp_epg:
        <<: *mso-login
        schema: LAB
        template: LAB
        anp: Test_Derrick
        epg: Test_Derrick_EPG
        bd:
          name: Test_Derrick_BD
        state: present
    delegate_to: localhost
```

##### EXPECTED RESULTS
I expect the contracts to not get blown away. Status should come back as "ok" and not changed.

##### ACTUAL RESULTS
All contracts are removed.

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This prevents existing contracts to be wiped.

This fixes #62137

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mso_schema_template_anp_epg

### CODE REVIEW

**Comment by dagwieers** [comment]
@DerrickTJ Can you please test this?

**Comment by DerrickTJ** [comment]
Yeah, it doesn't like taking that. It will work fine at creating a new EPG but as soon as that EPG has a contract attached it will error out with a "bad request"

```fatal: [localhost -> localhost]: FAILED! => {"changed": true, "current": {"bdRef": {"bdName": "Test_Derrick_BD", "schemaId": "5d1f6ed90f0000cf07fd6e14", "templateName": "TEMPLATENAME"}, "contractRelationships": [{"contractRef": "/schemas/5cb4c47d0e0000c0011bba06/templates/Multisite/contracts/ICMP_CT", "relationshipType": "consumer"}, {"contractRef": "/schemas/5cb4c47d0e0000c0011bba06/templates/Multisite/contracts/ICMP_CT", "relationshipType": "provider"}], "displayName": "Test_Derrick_EPG2", "intraEpg": "unenforced", "name": "Test_Derrick_EPG2", "preferredGroup": false, "proxyArp": false, "selectors": [], "subnets": [], "uSegAttrs": [], "uSegEpg": false}, "data": [{"op": "replace", "path": "/templates/TEMPLATENAME/anps/Test_Derrick/epgs/Test_Derrick_EPG2", "value": {"bdRef": {"bdName": "Test_Derrick_BD", "schemaId": "5d1f6ed90f0000cf07fd6e14", "templateName": "TEMPLATENAME"}, "contractRelationships": [{"contractRef": "/schemas/5cb4c47d0e0000c0011bba06/templates/Multisite/contracts/ICMP_CT", "relationshipType": "consumer"}, {"contractRef": "/schemas/5cb4c47d0e0000c0011bba06/templates/Multisite/contracts/ICMP_CT", "relationshipType": "provider"}], "displayName": "Test_Derrick_EPG2", "intraEpg": "unenforced", "name": "Test_Derrick_EPG2", "preferredGroup": false, "proxyArp": false, "selectors": [], "subnets": [], "uSegAttrs": [], "uSegEpg": false}}], "info": {"body": "{\"code\":400,\"message\":\"Bad Request: (0)(0)/epgs(0)(0)/contractRef/schemaId error.path.missing\"}", "connection": "close", "content-language": "en", "content-length": "95", "content-type": "application/json", "date": "Thu, 17 Oct 2019 14:54:05 GMT", "msg": "HTTP Error 400: Bad Request", "server": "nginx", "status": 400, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://CORP-CMSO-SV-002/api/v1/schemas/5d1f6ed90f0000cf07fd6e14"}, "msg": "MSO Error 400: Bad Request: (0)(0)/epgs(0)(0)/contractRef/schemaId error.path.missing", "payload": {"code": 400, "message": "Bad Request: (0)(0)/epgs(0)(0)/contractRef/schemaId error.path.missing"}}```

You'll notice above that it does know about the contract relationships though, it just isn't attaching it to any VAR to put back into the payload.

```"contractRelationships": [{"contractRef": "/schemas/5cb4c47d0e0000c0011bba06/templates/Multisite/contracts/ICMP_CT", "relationshipType": "consumer"}, {"contractRef": "/schemas/5cb4c47d0e0000c0011bba06/templates/Multisite/contracts/ICMP_CT", "relationshipType": "provider"}]```

**Comment by dagwieers** [comment]
Right,now  I remember. The interface outputs references in a different way it expects them as input. And that makes it impossible to merge the data-structures as-is.

**Comment by dagwieers** [comment]
So we have to rewrite these references 😕

**Comment by DerrickTJ** [comment]
Do you know how it is expect the payload to be formatted? Shouldn't be too hard to move that data around.

**Pull request closed without merging**
