### PR TITLE
Add Fedora 26 to shippable

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY
Add Fedora 26 Dockerfile.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
tests

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by s-hertel** [comment]
cc @mattclay

**Comment by mattclay** [comment]
I'm in the process of updating all of our Fedora images for CI. We'll be switching to testing Python 3 there since that is the default version installed. Our current Fedora images and the one in this PR are testing Python 2 instead.

**Comment by mattclay** [comment]
New Fedora 25 and Fedora 26 Docker images have been added: https://github.com/ansible/ansible/pull/27794

These images use Python 3 instead of Python 2. I also have a PR to enable them in CI: https://github.com/ansible/ansible/pull/27795

However, there are still some issues to work through with the Fedora 26 images and test stability, so the updated images are not yet being used on Shippable.

**Comment by mattclay** [comment]
@mkrizek Thanks for this PR. It reminded me to finish the Fedora image updates I had started working on earlier. I'm closing this since we don't want to add new Python 2 testing for Fedora.

**Pull request closed without merging**
