### PR TITLE
GetManagerNicInventory

### PR DESCRIPTION
**Pull request by xmadsen**
##### SUMMARY

This change adds a GetManagerNicInventory command to the Manager category in redfish_facts. There hasn't been a command to retrieve the Manager's network interface(s)'s details until now, and my enhancement extends the functionality of the redfish_utils `get_nic_inventory()` command by specifying a resource type to the function, which can currently be 'Manager' or 'Systems', taken from the 'category' variable in redfish_facts. This change ultimately amounts to specifying either the self.manager_uri for the 'Manager' category, or the self.systems_uri for the 'Systems' category.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

redfish_facts and redfish_utils

##### ADDITIONAL INFORMATION

```paste below
- name: Test Redfish modules
  hosts: localhost
  gather_facts: false
  vars:
    baseuri: 10.240.50.79
    user: USERID
    password: PASSW0RD

  tasks:
    - name: Test getting Manager NIC inventory
      redfish_facts:
        category: Manager
        command: "{{ item }}"
        baseuri: "{{ baseuri }}"
        username: "{{ user }}"
        password: "{{ password }}"
      failed_when: false
      with_items:
        - GetManagerNicInventory
     register: manager_nics

    - debug:
        var: manager_nics



$ ansible-playbook test_redfish_facts.yml

PLAY [Test Redfish modules] *************************************************************************************************
TASK [Test getting Manager NIC inventory] ***********************************************************************************ok: [localhost] => (item=GetManagerNicInventory)

TASK [debug] ****************************************************************************************************************ok: [localhost] => {
    "manager_nics": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": "GetManagerNicInventory",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "ansible_facts": {
                    "redfish_facts": {
                        "manager_nics": {
                            "entries": [
                                {
                                    "AutoNeg": true,
                                    "Description": "Manager Ethernet Interface",
                                    "FQDN": "XCC-7X07-6666666666",
                                    "IPv4Addresses": [
                                        {
                                            "Address": "10.240.50.79",
                                            "AddressOrigin": "Static",
                                            "Gateway": "10.240.48.1",
                                            "SubnetMask": "255.255.252.0"
                                        }
                                    ],
                                    "IPv6Addresses": [
                                        {
                                            "Address": "fd55:faaf:e1ab:210c:a94:efff:fe3c:83b3",
                                            "AddressOrigin": "SLAAC",
                                            "AddressState": "Preferred",
                                            "PrefixLength": 64
                                        },
                                        {
                                            "Address": "fe80::a94:efff:fe3c:83b3",
                                            "AddressOrigin": "LinkLocal",
                                            "AddressState": "Preferred",
                                            "PrefixLength": 64
                                        }
                                    ],
                                    "MTUSize": 1500,
                                    "NameServers": [
                                        "",
                                        "",
                                        "",
                                        "::",
                                        "::",
                                        "::"
                                    ],
                                    "PermanentMACAddress": "08:94:ef:3c:83:b3",
                                    "SpeedMbps": null,
                                    "Status": {
                                        "Health": null,
                                        "State": "Enabled"
                                    }
                                },
                                {
                                    "AutoNeg": false,
                                    "Description": "Management Network Interface",
                                    "IPv4Addresses": [
                                        {
                                            "Address": "169.254.95.118",
                                            "AddressOrigin": "Static",
                                            "Gateway": "0.0.0.0",
                                            "SubnetMask": "255.255.0.0"
                                        }
                                    ],
                                    "IPv6Addresses": [
                                        {
                                            "Address": "fe80::a94:efff:fe3c:83b4",
                                            "AddressOrigin": "LinkLocal",
                                            "AddressState": "Preferred",
                                            "PrefixLength": 64
                                        }
                                    ],
                                    "MTUSize": 1500,
                                    "PermanentMACAddress": "08:94:ef:3c:83:b4",
                                    "SpeedMbps": 100,
                                    "Status": {
                                        "Health": null,
                                        "State": "Enabled"
                                    }
                                }
                            ],
                            "ret": true
                        }
                    }
                },
                "changed": false,
                "failed": false,
                "failed_when_result": false,
                "invocation": {
                    "module_args": {
                        "baseuri": "10.240.50.79",
                        "category": [
                            "Manager"
                        ],
                        "command": [
                            "GetManagerNicInventory"
                        ],
                        "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "username": "USERID"
                    }
                },
                "item": "GetManagerNicInventory"
            }
        ]
    }
}

PLAY RECAP ******************************************************************************************************************localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0

```

### CODE REVIEW

**Review by billdodd — CHANGES_REQUESTED** [review]
@xmadsen - thanks for the PR.

The code looks good. I do think it would be helpful if you added an entry in the redfish_facts EXAMPLES doc string to show an example with GetManagerNicInventory (to let users know that option is available).

**Review by billdodd — APPROVED** [review]
@xmadsen - thanks for adding the example. Looks good.

shipit

**Comment by xmadsen** [comment]
Added the example.

**Comment by xmadsen** [comment]
thanks @billdodd (and apologies for accidentally closing the request); do i need to do anything from here or is it up for someone else to review?

**Comment by billdodd** [comment]
@xmadsen -  Nothing else needed on your end. Just needs another of the Redfish community maintainers to review and then one of us (@jose-delarosa or I) will need to request one of the core devs to merge it. (Changes to modules in `module_utils/` don't get merged automatically based on community approvals hence the need for that last step.)

**Comment by xmadsen** [comment]
got it, thanks!

**Comment by jose-delarosa** [comment]
shipit

@billdodd, can you please reach out to the core team in IRC (#ansible-devel) to merge this PR?

Thanks,

**Comment by billdodd** [comment]
@jose-delarosa - Will do.

**Comment by maxamillion** [comment]
shipit

**Pull request merged**
