### PR TITLE
Added to_datetime filter

### PR DESCRIPTION
**Pull request by hryamzik**
##### ISSUE TYPE

- New Filter Pull Request
##### COMPONENT NAME

`to_datetime` filter
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

Converts string to datetime object, for example:

``` yml
- debug: msg="{{ (("2016-08-04 20:00:12"|to_datetime) - ("2015-10-06"|to_datetime('%Y-%d-%m'))).seconds  }}"

```

### CODE REVIEW

**Comment by muxator** [comment]
The documentation for `to_datetime()` should be added to `docsite/rst/playbook_filters.rst`.

**Comment by hryamzik** [comment]
@muxator thanks, updated.

**Comment by mscherer** [comment]
Look good to me

**Comment by Pax-nl** [comment]
I was hoping to_datetime() would accept epoch/unix time stamp.

I need to convert the ctime returned by find.

**Comment by hryamzik** [comment]
@paxpacis you can just specify format.

**Comment by Pax-nl** [comment]
@hryamzik 

Nice, can you show me how? I gave it a unix time stamp but it failed.

**Comment by hryamzik** [comment]
@paxpacis see summary for passing format example, I can't test it right now.

**Comment by dorkmatt** [comment]
@hryamzik sadly this doesn't support unix time stamp, as the `strptime` function doesn't support it.

**Comment by hryamzik** [comment]
@dorkmatt you can actually add timestamp support by checking if format string equals `%s` and getting a `time` object with `time.localtime` or `datetime.datetime.fromtimestamp`.

**Pull request merged**
