### PR TITLE
`docker pull' image instead of building if no path is given

### PR DESCRIPTION
**Pull request by hkariti**
Resending #6065

### CODE REVIEW

**Comment by jctanner** [comment]
@hkariti can you please rebase and fix the merge conflicts from b1a3e367b6b4b88acef677f24cb6e483380f335d

**Comment by hkariti** [comment]
Tried to add it nicely alongside build.
I also noticed a problem - pulling can download several images, and in that case the id returned will be chosen practically at random. Don't know how to tackle this, as I'm pretty sure build returns a single value.

**Comment by jctanner** [comment]
@hkariti can you explain the new workflow here? I'm a bit confused about what this would do or what the intended use case is.

**Comment by mpdehaan** [comment]
You may wish to coordinate this with #6340 ?

**Comment by hkariti** [comment]
@mpdehaan I was about to mention that request as well. He seems to have done a more thorough job, so I think it's better to use that.

**Comment by mpdehaan** [comment]
Ok, we will close this one out and track the other.  Thank you!

**Pull request closed without merging**
