### PR TITLE
Move acme_* modules from web_infrastructure into crypto category

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
As discussed in #43756, moves all `acme_*` modules from the `web_infrastructure` category into the `crypto` category. The reason they ended up in `web_infrastructure` is historic (the `crypto` category didn't exist back then), and they fit better in `crypto`.

CC @Spredzy @resmo

##### ISSUE TYPE
 - Docs Pull Request

(I guess this category fits best...)

##### COMPONENT NAME
acme_account
acme_certificate
acme_certificate_revoke
letsencrypt

##### ANSIBLE VERSION
```
2.7.0
```

### CODE REVIEW

**Comment by resmo** [comment]
I would even suggest to create a crypto/acme subdir so they get grouped in the docs.

**Comment by felixfontein** [comment]
@resmo I thought about that, but I thought I read somewhere that adding another hierarchy level isn't allowed (except in some special cases such as `cloud` and `network`). But I don't really remember where I thought I read this, so maybe (hopefully) I'm wrong :)

**Comment by resmo** [comment]
@felixfontein it is not "allowed" create new directories in modules/ but in modules/crypto/ is definitely okay.

**Comment by felixfontein** [comment]
@resmo Ah ok. I'll do that then :)
Another question: do I have to split up this PR (because ansibot complains about multiple modules in one PR), or can I ignore it in this case?

**Comment by resmo** [comment]
shipit

**Comment by resmo** [comment]
shipit

**Comment by felixfontein** [comment]
@resmo Thanks for handling this!

**Pull request merged**
