### PR TITLE
Allow httpapi for resource modules

### PR DESCRIPTION
**Pull request by Qalthos**
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

eos

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
This looks like it will cause some issues with our ansible.netcommon collection. Mostly because, this now means we need to depend on both arista.eos and cisco.nxos.

**Pull request merged**
