### PR TITLE
add 'known_host' module

### PR DESCRIPTION
**Pull request by neomantra**
This module manages SSH known_host entries in a known_hosts file.
It does this using ssh-keyscan and ssh-keygen.

This complements the authorized_key module.

### CODE REVIEW

**Comment by mpdehaan** [comment]
neat!  in queue for review!

**Comment by mpdehaan** [comment]
I encountered some problems during testing, first is addressed by this patch, I think:

```
diff --git a/library/system/known_host b/library/system/known_host
index 042a7d7..a388c82 100644
--- a/library/system/known_host
+++ b/library/system/known_host
@@ -150,7 +150,7 @@ def get_known_hosts_pathname(module, user, path=None, manage_dir=True):
         finally:
            f.close()
         if module.selinux_enabled():
-            module.set_default_selinux_context(keysfile, False)
+            module.set_default_selinux_context(hostsfile, False)

     try:
         os.chown(hostsfile, uid, gid)
```

Also, from testing on CentOS 6.3, I encountered an additional error:

```
diff --git a/library/system/known_host b/library/system/known_host
index 042a7d7..a388c82 100644
--- a/library/system/known_host
+++ b/library/system/known_host
@@ -150,7 +150,7 @@ def get_known_hosts_pathname(module, user, path=None, manage_dir=True):
         finally:
             f.close()
         if module.selinux_enabled():
-            module.set_default_selinux_context(keysfile, False)
+            module.set_default_selinux_context(hostsfile, False)

     try:
         os.chown(hostsfile, uid, gid)
```

The user testing if the user is not defined on the system could also use some additional error handling:

```
 "msg": "Failed to lookup user notauser: 'getpwnam(): name not found: notauser'"
```

If you can take care of these, I can look at retesting and merging this.

Thanks!

**Comment by neomantra** [comment]
Ah, I don't have an selinux_enabled system and couldn't test that code path.  It was a copy-paste-modify omission from the `authorized_keys` module.   I'm about to add a commit for it, but wanted to ask this first...

Regarding the additional error handling, that and other scaffolding was lifted from the `authorized_keys` module.   It handles this error exactly the same way (as I copied it from there):
https://github.com/ansible/ansible/blob/devel/library/system/authorized_key#L120

If you tell me what you want there, I will change it (and to the authorized_key module too).

**Comment by mpdehaan** [comment]
I'd recommend doing an install of CentOS 6.x in a VM.

authorized_keys should be similarly improved so this still has to fix it here :)

**Comment by neomantra** [comment]
Regarding the error message itself, I'm not sure what you'd like to see different.  The current code is simply has that message and the string-ized exception:

```
try:
    user_entry = pwd.getpwnam(user)
except KeyError, e:
    module.fail_json(msg="Failed to lookup user %s: %s" % (user, str(e)))
```

Would you like to see something like this?

```
"msg": "Failed to get the password database entry for user 'notauser' (getpwnam(): name not found: notauser)"
```

**Comment by steverweber** [comment]
Please include options for a raw key.  Its nice that you support the resolving of hostnames to a key but doing this at runtime would circumvent the point of the known_host file.  :)

example:
known_hosts: user=charlie key="sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTuAAABBBOA9j6O+vsyCY5MnTL8s6RIJijNfyOHGm/RL1MmhDlbeK4FpqZlybzZG/nQZjGm8qbpIXZjZlRhQ7Iq1UhG++Co="

this would also support using lookup like how authorized_key examples.

thanks/.

**Comment by neomantra** [comment]
@steverweber   for this you would still need to specify the host, right?   so more like:

```
known_hosts: user=charlie host="foobar.com" key="sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTuAAABBBOA9j6O+vsyCY5MnTL8s6RIJijNfyOHGm/RL1MmhDlbeK4FpqZlybzZG/nQZjGm8qbpIXZjZlRhQ7Iq1UhG++Co="
```

**Comment by steverweber** [comment]
I don't understand why you would need to include the host option..

support this...

```
- shell: ssh-keyscan test.com
  register: _host_key
- known_hosts: user=charlie key="{{ _host_key.stdout }}"
```

or with the host name hashed

```
- shell: ssh-keyscan -H test.com
  register: _host_key
- known_hosts: user=charlie key="{{ _khost_key.stdout }}"
```

or 

```
- known_hosts: user=charlie key="THE RAW KNOWN_HOST LINE"
```

**Comment by steverweber** [comment]
Allowing a raw known_host line could be more secure.  If the known host gets computerised, I want the git clone command that I might run latter in the playbook to fail or lock-up if the key don't fit.

Thanks

**Comment by neomantra** [comment]
It looks like your original example was only including the key part and not the host part?   If you think it should be the whole raw line, then that makes sense.   Or maybe there should be both options?
- specify `host`, with optional `key`; if key is not set then look it up with `ssh-keyscan`
- or specify `line` to insert a line verbatim (one advantage of using this over `lineinfile` is that it finds the known_hosts file for you)

Thoughts?

**Comment by steverweber** [comment]
sounds good to me... but perhaps just use key..  without the extra `line` option.
- specify `host`, with optional `key`; if key is not set then look it up with ssh-keyscan
- if just `key` is specify insert/remove it verbatim similar to `authorized_key` module

**Comment by steverweber** [comment]
or how about support for..

`- known_hosts: user=charlie key="{{ _khost_key.stdout }}"  state=...`
`- known_hosts: user=charlie host="example.com" state=...`

NO support for both host and key in this format:
`- known_hosts: user=charlie host="example.com" key='${KEY}'`
- specify `host`, will look up the key with ssh-keyscan
- if just `key` is specify insert/remove it verbatim, similar to `authorized_key` module

**Comment by neomantra** [comment]
@mpdehaan I applied your suggested changes.  I also applied the same error message change to `authorized_key`

@steverweber I created issue #3665 for your suggestion.  I don't have time to work on it for a while myself and don't want to hold up the initial pull of this module.

**Comment by mpdehaan** [comment]
Another question is does this work with hashed known hosts files?

**Comment by neomantra** [comment]
Yes, there is a `hash` argument.  That basically adds `-H` flags to the various command line programs.

**Comment by mpdehaan** [comment]
I really like the idea above about it working with ssh-keyscan and not just requiring the key, though that seems like it could be done as a follow on.

Testing now!

**Comment by mpdehaan** [comment]
Testing on EL 6:

failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1376173632.4-121674600851537/known_host", line 1222, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1376173632.4-121674600851537/known_host", line 288, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1376173632.4-121674600851537/known_host", line 227, in enforce_state
    present = check_presence(temp_path, host)
  File "/root/.ansible/tmp/ansible-1376173632.4-121674600851537/known_host", line 165, in check_presence
    output = subprocess.check_output(["ssh-keygen", "-f", hostsfile, "-F", host])
AttributeError: 'module' object has no attribute 'check_output'

Please test this on CentOS or equivalent and let me know when you think it is working.

**Pull request closed without merging**
