### PR TITLE
asa_config doc attach acl to interface

### PR DESCRIPTION
**Pull request by hemskgren**
##### SUMMARY

asa_config doc example to attach acl to interface
+label: docsite_pr
Issue ansible/community#311

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

asa_config
##### ANSIBLE VERSION

```
2.5.4
```

##### ADDITIONAL INFORMATION

+label: docsite_pr
Issue ansible/community#311

```

```

### CODE REVIEW

**Comment by beeankha** [comment]
@hemskgren We'll also be taking a look at this PR and testing when we get the chance.

**Comment by hemskgren** [comment]
See https://gist.github.com/hemskgren/c9b94468186201916e8ceee332513028
Playbook line 2-17 + 45-52
and output line 131-135

**Comment by beeankha** [comment]
@hemskgren , thank you so much for providing us with the requested information!  Pasting everything directly in this thread for easier referencing:

Playbook
```
$ more asa_pr311.yml
---
- name: modify my Cisco ASA with ansible
  hosts: "{{ devices }}"
  gather_facts: false
  connection: network_cli
  vars:
    #cli:
    host: "{{ inventory_hostname }}"
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ password }}"

  - name: attach ASA acl on interface vlan13/nameif cloud13
    asa_config:
      lines:
        - access-group cloud-acl_access_in in interface cloud13
      #provider: "{{ cli }}"
    register: acc_group
```

Output
```
TASK [attach ASA acl on interface vlan13/nameif cloud13] ******************************************************************************
task path: /home/christer/github/ansible-test/asa_pr311.yml:44
changed: [192.168.96.1] => {"changed": true, "updates": ["access-group cloud-acl_access_in in interface cloud13"]}
```

In addition to the above, we’d also like to see what the results look like from the device to show that the playbook had the desired effect. Please reference what you provided in [41376](https://github.com/ansible/ansible/pull/41376) as an example.

**Comment by hemskgren** [comment]
Below is text from the device config before running the playbook:

```
hemasa01# show runn access-group | inc cloud13
access-group cloud-acl_access_in in interface cloud13
hemasa01# 
hemasa01# conf t
hemasa01(config)# no access-group cloud-acl_access_in in interface cloud13
hemasa01(config)# show runn access-group | inc cloud13                    
hemasa01(config)# 
hemasa01(config)#
```

And here is the text from the device config after the playbook ran:

```
hemasa01# sh runn access-group | inc cloud13
access-group cloud-acl_access_in in interface cloud13
hemasa01#
```

**Comment by hemskgren** [comment]
This attach acl example is idempotent.

**Comment by acozine** [comment]
Looks great, thank you! I'll kick off the CI again and as soon as it's green, we'll merge.

**Comment by acozine** [comment]
rebuild_merge

**Pull request merged**
