### PR TITLE
Skip tests with unsatisfied deps

### PR DESCRIPTION
**Pull request by abadger**
##### SUMMARY
Tests for modules or other plugins whose deps fall outside of ansible's core dependency set need to check whether the deps are installed and skip if they are not.

This PR skips for several tests which were found to be running even when their deps were not installed.

##### ISSUE TYPE
- Bugfix Pull Request

##### ADDITIONAL INFORMATION
backport to 2.8 when merged.

### CODE REVIEW

**Comment by abadger** [comment]
\cc @mattclay

**Comment by abadger** [comment]
@mattclay I'm not quite sure why the cloudstack test is failing now.... The pytestmark to skip the test on python-2.6 is functioning correctly locally.  I can change it to skip the test if it's on python-2.6 in a different way (it was using unittest before).... I'm just not sure why this syntax is failing in our setup.

**Comment by abadger** [comment]
@mattclay, I figured out what my mistake was.  The test was failing when it tested whether it could import the cs module.  The toplevel code in the test all runs and registers whether any of the conditions would cause it to skip.  Since I was trying to import ```cs``` to test for its availabilty, it was failing with a SyntaxError on python-2.6.  I moved that test for whether to skip inside of the condition for python-2.6 so that it only runs on Python-2.7+

Should work now! :crossed_fingers:

**Comment by abadger** [comment]
ready_for_review :-)

**Review by mattclay — APPROVED** [review]

**Pull request merged**
