### PR TITLE
Fix OS X facts for media interface

### LINKED ISSUE #11104: OSX media_type facts for bridge interface is wrong
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
ansible 2.0.0
  configured module search path = /usr/share/ansible
</code>
##### Ansible Configuration:

None
##### Environment:

Management server: CentOS 6.6
Managed server: OSX
##### Summary:

Using setup module against an OSX computer, the media_type fact for the ansible_bridge0 interface shows as "ype>".
##### Steps To Reproduce:

1) From management server, run the ansible command using the setup module:
ansible mac -m setup
2) View the ansible_bridge0 fact in the output
##### Expected Results:

Based on the output of 'ifconfig -a' on the OSX machine
media: <unknown type>
So the fact should be set to:
"media_type": "unknown type"
##### Actual Results:

```
    "ansible_bridge0": {
        "device": "bridge0", 
        "flags": [
            "UP", 
            "BROADCAST", 
            "SMART", 
            "RUNNING", 
            "SIMPLEX", 
            "MULTICAST"
        ], 
        "ipv4": [], 
        "ipv6": [], 
        "macaddress": "xx:xx:xx:xx:xx:xx", 
        "media": "Unknown", 
        "media_select": "<unknown", 
        "media_type": "ype>", 
        "mtu": "1500", 
        "options": [
            "PERFORMNUD"
        ], 
        "status": "inactive", 
        "type": "unknown"
    }, 
```

### PR DESCRIPTION
**Pull request by sysadmin75**
Fixes #11104

### CODE REVIEW

**Comment by bcoca** [comment]
needs rebase

**Comment by sysadmin75** [comment]
Once I do the rebase, will I have to redo the pull request?

**Comment by bcoca** [comment]
no, the PR is based on your branch name, you can even redo the whole branch with a --force and the PR will stay with it.

**Comment by sysadmin75** [comment]
I'm decent using git for basic rebase and branch operations. But I'm confused on how to proceed with this. I've compared the latest ansible file lib/ansible/module_utils/facts.py against my branch version and the diff is exactly the same as my PR. I'm not sure where the conflict is.

**Comment by bcoca** [comment]
so probably because it duplicates some of #11103, which I already merged?

**Comment by bcoca** [comment]
closing in favor of #11113

**Pull request closed without merging**
