### PR TITLE
panos_commit

### PR DESCRIPTION
**Pull request by ivanbojer**
ISSUE TYPE

New Module Pull Request
COMPONENT NAME

panos_commit

ANSIBLE VERSION

ansible 2.1.0.0
config file =
configured module search path = Default w/o overrides
SUMMARY

New panos module that allows user to commit current candidate configuration to the firewall

### CODE REVIEW

**Comment by ivanbojer** [comment]
Migrated from: https://github.com/ansible/ansible-modules-extras/pull/3384

**Comment by privateip** [comment]
Overall looks good.  One minor change. Ansible 2.3 now requires a snippet of metadata for every new module.  Please add the following to your module and then it can be merged.

```
ANSIBLE_METADATA = {'status': ['preview'],
                    'supported_by': 'community',
                    'version': '1.0'}
```

Details on the usage of metadata can be found [here](https://github.com/ansible/proposals/issues/30) for the time being while documentation is still being updated.

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by mattclay** [comment]
@ivanbojer Tests are failing due to issues with metadata, as seen from the Shippable logs:

```
2016-12-20 19:46:41 Run command: ansible-doc panos_commit
2016-12-20 19:46:42 ERROR: Command "ansible-doc panos_commit" returned exit status 0.
2016-12-20 19:46:42 >>> Standard Error
2016-12-20 19:46:42  [WARNING]: Non-dict metadata detected in /root/src/github.com/ansible/ansible/
2016-12-20 19:46:42 lib/ansible/modules/network/panos/panos_commit.py, skipping
```

**Comment by ivanbojer** [comment]
@mattclay Thank you for review. Not sure why but I changed metadata format from yaml back to json.

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by mattclay** [comment]
@ivanbojer Currently all the modules we ship only use dict metadata, which is why the tests didn't like the yaml based version.

**Comment by privateip** [comment]
thanks... merged into devel

**Pull request merged**
