### PR TITLE
2.6: Warn when cond is used on meta tasks that don't support them (#41126)

### PR DESCRIPTION
**Pull request by mkrizek**
(cherry picked from commit 5f7ffd39dc8e8043aaed59c365b0e9c759ee829b)

##### SUMMARY

Partial fix for https://github.com/ansible/ansible/issues/46275

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

strategy

##### ANSIBLE VERSION

```paste below
2.6
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mattclay** [comment]
This is essentially a new feature -- adding a warning where there was not one before. This kind of change should not be backported, as the change in behavior is likely to be unexpected.

**Comment by mkrizek** [comment]
For the record, this was created as per https://github.com/ansible/ansible/issues/46275#issuecomment-427790606 to **fix** the traceback that was caused by using a function that was not present in `stable-2.6`. This was to backport said function - https://github.com/ansible/ansible/issues/46275#issuecomment-427889673.

**Comment by mattclay** [comment]
@mkrizek Thank you for the reminder. It's been just under a month since that discussion and I'd already completely forgotten about it. Could you please open a new backport for this? Sorry for the trouble.

**Comment by mattclay** [comment]
@mkrizek On further consideration, and after re-reading the original discussion, I think think only the missing function should be backported.

**Comment by mkrizek** [comment]
@mattclay Sounds right - https://github.com/ansible/ansible/pull/48175

**Pull request closed without merging**
