### PR TITLE
Handles exceptions raised when getting network interfaces

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

contrib/inventory/azure_rm.py

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
The possibility exists that a ResourceNotFound error may be
raised if the network interface under a resource group is
not found.

This patch handles the exception and continues on with processing
of the interfaces.

### CODE REVIEW

**Comment by caphrim007** [comment]
@nitzmahone

**Comment by caphrim007** [comment]
@nitzmahone ready_for_review

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by caphrim007** [comment]
@nitzmahone any update on this?

**Comment by nitzmahone** [comment]
I'm not a fan of just silently swallowing any error that might occur while looking up network interfaces- that's a way bigger hammer than is necessary (and still won't include any external NICs in the looked-up details). That said, I think in one of the SDK refreshes that's occurred since we originally built this stuff, they've added a way to do a "get" from a URI instead of resourcegroup+name, so we should be able to look up NICs from arbitrary RGs now without parsing the URI. I've added this to the 2.3 milestone and should be able to poke at it sometime in the next week or so.

**Comment by bcoca** [comment]
cc @caphrim007 could you address @nitzmahone's comments?

**Comment by caphrim007** [comment]
@bcoca I thought @nitzmahone was suggesting he was just going to add it to a todo list for future work. I didn't dig very deep into the Azure SDK stuff since his last comment.

**Comment by abadger** [comment]
@tstringer Is this something you want to look into?

**Comment by trstringer** [comment]
@abadger thanks for looping me into this!

@caphrim007 is this still an issue? And what exactly is the scenario where a machine would be passed in with reference nics that don't exist?

Just looking at the small scope of this PR, I'm apt to react with @nitzmahone I personally don't like swallowing all CloudError exceptions that would be raised here.

**Comment by caphrim007** [comment]
@tstringer the situation I was in was that I had an account that was shared and (somehow) one of my colleagues created a device that had no nics, or, created a device with nics and then removed those nics.

This happened some time ago though so I no longer have the environment to test with. Not sure to what extent I would be able to re-create the error now, but I can stay on this ticket and try if you'll change anything and want someone to test those changes.

**Comment by trstringer** [comment]
@caphrim007 ah ok thank you for the context. Personally I feel like that is an acceptable failure as that shouldn't be a normal situation and possibly warrants a failure like that.

@nitzmahone thoughts?

**Comment by caphrim007** [comment]
The problem is that Ansible is not resilient to the configuration; one that I have no control over. I was expecting Ansible to just pass over the host

**Comment by trstringer** [comment]
Ok I can understand that. Do you think there's a way you can get my repro steps? I think that's the next logical thing to do here for me to wrap my head around what you're seeing and what the experience is vs. what the experience should be.

**Comment by caphrim007** [comment]
@tstringer I can try

**Pull request closed without merging**
