### PR TITLE
use new client

### PR DESCRIPTION
**Pull request by zengchen1024**
##### SUMMARY
1.  refactor the HwcSession and split it into two classes of Config and _ServiceClient instead. Because HwcSession is a little complex and not a single function class.
2. add two methods of 'build_path' and 'get_region'

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
hwc_network_vpc
hwc_smn_topic

##### ADDITIONAL INFORMATION
I have tested the changes on the real environment.

### CODE REVIEW

**Comment by zhongjun2** [comment]
shipit

**Comment by zhongjun2** [comment]
bot_status

**Comment by TommyLike** [comment]
shipit

**Comment by zhongjun2** [comment]
bot_status

**Comment by zhongjun2** [comment]
shipit

**Comment by zhongjun2** [comment]
shipit

**Comment by zhongjun2** [comment]
bot_status

**Pull request merged**
