### PR TITLE
make various modules pep8 compliant

### PR DESCRIPTION
**Pull request by mscherer**
After finding make pep8, i started to fix some modules. However, since there is around 800 errors, I will just do a few files for each PR, so this can be easier to review. I can also do 1 big push if needed, but it is gonna take more time.

### CODE REVIEW

**Comment by sivel** [comment]
There was a recent discussion on the mailing list and another ticket about this.

I'd recommend looking at those discussions as the agreement/decision is that code changes for the sake of formatting changes is a bad idea.

**Comment by alanfairless** [comment]
In general I agree with that policy for small one off changes.  

At the same time I support the idea of making a one time exception for a pass through the code with the specific goal of pep8 formatting.  IMO code readability and comprehensibility are far underrated; humans are excellent at pattern recognition and conventions help our pattern recognizers engage.  

Because of that, for long time Python developers standard formatted code is subtly more welcoming and approachable, and unnecessary deviations (though individually they are each trivial) are collectively a mental burden when reviewing.  

That said, the primary authors naturally spend more time with the code than the rest of us so whatever they need is most important.  Just my $0.02.  :)

**Comment by alanfairless** [comment]
One approach that might make reviewing changes easier and eliminate possible side effects is to first make a pass that ONLY changes formatting, such that we could verify that before and after compiles to the same byte code.

So for example, the parts of the patch where the comparisons are changed from the form `a == False` to the form `a is False` would be omitted.  (The `is` operator is pointer comparison, requiring the very same object instance on both sides.  There's only one instance of objects like True, False, and None.)

**Comment by mscherer** [comment]
Well, pep8 is showing a warning for those changes ( the a == False  vs a is False ). Now, if we want to be serious into enforcing pep8 compliance ( and the mere presence of "make pep8" is a sign we may want, or rather wanted it ), then we need to have it clean, or that's just noise. The same was done for pyflakes, and make pyflakes work fine.

And once everything is cleaned, there is system like http://pep8.me/ that ensure the code stay clean from that point of view.

**Comment by mpdehaan** [comment]
As a general policy I do not allow outside folks to make pep8 changes, it breaks attribution and upsets review.

We periodically run "make pep8" to fix things 

Things are quite readable in a lot of these edits and many of these line changes are unneccessary.

Things where a warning are detected are different.

There's no reason to think pep8 is a holy grail, it's only a standard of suggestions.

For instance this in particular:

```
-    cmd = [ module.get_bin_path('getfattr', True) ]
 +    cmd = [module.get_bin_path('getfattr', True)]
```

The original was actually MORE readable.

It is for this reason that I don't really agree with cargo-culting these things without understanding them or coming up to one's own judgements.

I'd much rather you guys actually help out with bugs than just rearrange the spacing before brackets.  It's just not useful.

Let's focus on the things that are actually important.

There are some things in here I agree with like:

```
-            addr_list.append( parseaddr(addr)[1] )
+            addr_list.append(parseaddr(addr)[1])
```

But would much rather see those sections updated in the context of a change to that area of the code, to where I know they were actually tested, and things will continue to improve over time.

**Comment by mscherer** [comment]
Then another option is to add more ignore to "make pep8", because when i run it on git HEAD, I see around 840 warnings. So unless I missed something, that's hardly usable as is to enforce any kind of style, or even to see if things got changed on this part.

Also, what do you mean by "outside folks" ?

**Comment by danieljaouen** [comment]
Just adding my $0.02:  I think an exception should be made for a one-time pass for general pep8 cleanup.  Non-pep8-compliance tends to scare away experienced Python developers, so you're kind of shooting yourself in the foot here.

**Pull request closed without merging**
