### PR TITLE
ovirt and rhevm are (sort of?) deprecated, point to ovirt_vms

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

ovirt
rhevm

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This patch adds a note that the modules `ovirt` and `rhevm` was replaced by new `ovirt_vms` module.

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina

**Comment by gundalow** [comment]
Do ovirt and rhevm need formally deprecating?

**Comment by machacekondra** [comment]
Not really, because those modules work with oVirt/RHEV version 3, but new modules are working with oVirt/RHV version 4 only. But oVirt 3 doesn't has any new releases and RHEV3 will stop be supported soon, so I wouldn't deprecate those modules.

**Comment by gundalow** [comment]
Thanks for the background.
I wonder if the message should be along the lines of:
`This module only supports oVirt/RHEV  v3. A newer module M(ovirt_vms) supports v4.`

**Comment by machacekondra** [comment]
That looks better, thanks for suggestion.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Great, thanks

**Pull request merged**
