### PR TITLE
VMware: Better handling of vmware-vm-shell timeout ('NoneType' object has no attribute 'owner')

### PR DESCRIPTION
**Pull request by jeking3**
##### SUMMARY

`vmware-vm-shell` handles a timeout by returning `None` which causes a `NoneType` error.  This updates the handling to fail the module if the timeout is exceeded and returns information about the vm, process id, start time, end time, and timeout in the result.

The process exitCode can be negative (for example 0xc0000005 when a process crashes) and that was not handled properly either.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

vmware-vm-shell

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (sandbox eed8db8bfd) last updated 2018/11/01 18:12:39 (GMT +000)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /ansible/lib/ansible
  executable location = /ansible/bin/ansible
  python version = 2.7.15 (default, Sep 12 2018, 02:38:23) [GCC 6.4.0]
```

##### ADDITIONAL INFORMATION

Here is the timeout error before the fix:

```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_vm_shell_payload_X97U1R/__main__.py", line 244, in __init__
    self.execute_command(vm, module.params)
  File "/tmp/ansible_vmware_vm_shell_payload_X97U1R/__main__.py", line 272, in execute_command
    owner=res_data.owner,
...
    },
    "msg": "'NoneType' object has no attribute 'owner'"
}

```

### CODE REVIEW

**Comment by jeking3** [comment]
@mkrizek what's next for this one?

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@pdellaert @dericcrago @Im0 @tchernomax @ckotte Could you please review this ?

**Comment by ckotte** [comment]
LGTM

**Pull request merged**
