### PR TITLE
Allow including files through variables

### PR DESCRIPTION
**Pull request by dhozac**
This makes things like
action: authorized_key user=root key="${<files/ansible_ssh_key.pub}"
possible, as well as allowing arbitrary scripts to be executed and their output consumed, with e.g.
action: authorized_key user=root key="${|cat files/ansible_ssh_key.pub}"
for a UUoC award.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I very much like the feature and generic piping here solves some other problems.   I think many people are comfortable with variables being deferenced by "${foo} but "${<" is kind of in the vein of operators we like to make fun of other tools for, unfortunately.   

What other options might we have for syntax?

Originally I had proposed

<<${filename)>>

for loading from files, but what about something simpler?

$FILE{...}

and

$PIPE{...}

?

**Comment by dhozac** [comment]
Yeah, I wasn't happy with the syntax either. I only went with ${< and ${| because they were the easiest to implement in the regexp. They're now $FILE{...} and $PIPE{...} instead.

**Comment by mpdehaan** [comment]
Wow, you are quick!

The other thing I was thinking is people are going to try to do is run this on things that aren't variables.

Perhaps this gets done /after/ varLookup?  (And at the end of the template function?)

This may actually imply $FILE( ) and $PIPE( ) and we drop the FILE{ } and PIPE{ } since that feels a little weird still.

So you could do $FILE($foo) and still $FILE(/etc/foo.txt) just the same

(edit: fixed $foo)

**Comment by dhozac** [comment]
I'm not sure I understand what you mean, you mean try to use these on things that don't get interpolated by varReplace?

**Comment by mpdehaan** [comment]
Exactly

**Comment by dhozac** [comment]
I'm not sure how you're suggesting that gets fixed, other than running varReplace on it...

**Comment by mpdehaan** [comment]
I didn't mean to press close, one sec

**Comment by mpdehaan** [comment]
Ok, so make a new function called "varReplaceFilesAndPipes"

utils.template does it's varReplace thing (which is a recursive loop), then it (may) call Jinja2, this gets called at the end of all that.   So it's a third kind of templating where we already have 2 that runs at the end of utils.template.  If the code looks a lot like varReplace that is ok.

**Comment by dhozac** [comment]
The only downside of doing it as a separate step in the templating process, is that you won't be able to put variables that get interpolated in your files. I'm tempted to call that a feature though...

Do you want me to squash these before merging?

**Comment by mpdehaan** [comment]
yes please, thanks!

**Comment by dhozac** [comment]
Okay, that should do it.

**Comment by mpdehaan** [comment]
in queue for testing/merging/understanding, thanks very much!!!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
