### PR TITLE
fix(azure_rm_containerregistry): Fixed sku idempostency

### PR DESCRIPTION
**Pull request by sagarafr**
##### SUMMARY
#45330

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by Fred-sun** [comment]
@yungezz @MyronFanQiu This PR has been changed very little, please help to review and promote the merger. Thank you very much!

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
pls fix CI failure then I'll merge it.

**Comment by sagarafr** [comment]
Hello @yungezz, I think the job is on error because of I push force the initial commit. Could you please rerun the job ? Thanks you

**Comment by sagarafr** [comment]
Hello @yungezz, can you merge this fix ?
All CI failure was resolved.
Thanks you in advance

**Comment by Fred-sun** [comment]
@yungezz All checks have passed,Please merge this fix when you're free! Thank a lot!

**Comment by Fred-sun** [comment]
@yungezz All the tests have passed, please help to merge, thank you!

**Comment by Fred-sun** [comment]
Once merged, we can close Issue #45330.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
