### PR TITLE
Backport: Fixes some NIC bugs (#39213)

### PR DESCRIPTION
**Pull request by yuwzho**
##### SUMMARY

* add loadbalancer

* dict check nullable

* add default vallue when get list

* create backend addr pool

* fix the set

* fix to dict

* fix ideponement

* use param security group name when create

* nic can has no nsg

* add test

* fix

* fix

* fix

* fix idemponet

* add document

* fix test

* add configuration

* fix

* fix

* remove all resources

* fix

* fix test

* add version added

* fix lint

* fix lint

* fix lint

* remove new feature and only submit bugfix

* remove useless test

* fix

(cherry picked from commit 39ca41eb1bf2f6c0f02df8ba19e26ca2adc414de)

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

azure_rm_networkinterface

##### ANSIBLE VERSION

```
2.5.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by yuwzho** [comment]
Something wrong happened to container instance, but my change is about network interface, what should I do? @mattclay

**Comment by mattclay** [comment]
@yuwzho I've restarted tests for this PR.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/63425/63/tests

> test/integration/targets/azure_rm_networkinterface/tasks/main.yml:36 / [localhost] azure: azure_rm_networkinterface : Create NIC using virtual_network_resource_group parameter resource_group={{ resource_group }}, name=testnic001rg, virtual_network=testnic001, virtual_network_resource_group={{ resource_group_secondary }}, subnet=testnic001, public_ip_name=testnic001, public_ip_allocation_method=Static, security_group=testnic001

> failure: Unsupported parameters for (azure_rm_networkinterface) module: virtual_network_resource_group Supported parameters include: ad_user, api_profile, append_tags, auth_source, cert_validation_mode, client_id, cloud_environment, ip_configurations, location, name, open_ports, os_type, password, private_ip_address, private_ip_allocation_method, profile, public_ip, public_ip_address_name, public_ip_allocation_method, resource_group, secret, security_group_name, state, subnet_name, subscription_id, tags, tenant, virtual_network_name

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
CI failures are unrelated to the change.

**Pull request merged**
