### PR TITLE
rax.py inventory plugin: group metadata can be a comma-separated list

### PR DESCRIPTION
**Pull request by ghost**
This should open the door for using the metadata field to designate multiple roles for a cloud server, production/staging tags, or maybe even allowing multiple developers to use a shared Rackspace Cloud account without using a hostname naming convention and the '--limit' parameter.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Please share an example of how this would be used?

It sounds like you are suggesting having a rackspace group that contains commas in it, which I'm not sure I agree with.

Additionally, per code conventions, instead of grouplist, variables should be like group_list.

Anyway, let me know what this is intended to do so we don't have to try to reverse engineer from the code.  Thanks!

**Comment by sivel** [comment]
@mpdehaan This would allow you to place a server into multiple custom groups, rather than only a single custom group, in use with targeting groups of servers using 'hosts: foo'

My input on this:
1. This will not work well with the 'rax' module.  The rax module, assumes that a group is singular as well, and has a lot of logic built around that fact.
2. If this were implemented, I would prefer that it look for a separate meta key called 'groups' that is a list of "secondary" groups for the server.
3. The "group" meta key, should remain a single "primary" group for the server.

**Comment by sivel** [comment]
And to mention I do have a number of changes to rax.py that I utilize personally that contains this functionality:

https://gist.github.com/sivel/8406271

**Comment by ghost** [comment]
Oh, wow. Let's use @sivel 's version instead! Essentially, all I was trying to solve for was finer-grained grouping, which that diff does much better. 

Perhaps it would just be sufficient to create a metadata item "roles", and comma-separate that. Either way, I was trying to figure out a viable workflow around what already existed, and thought this feature would be a step in the right direction.

Currently, I use one playbook to add servers to the environment, "vars_prompt"ing for a server base name, a quantity for the rax module's "count" parameter, and a list of comma-separated roles to apply to the server. A second playbook runs over every server on the account, applying roles based on the comma-separated list. Existing servers obviously don't get modified, but the newly provisioned-ones do.

One use case I was thinking of involved a subset of servers on an account being controlled by Ansible, where others aren't (multiple devs with access to a shared account). Hopefully, those servers are getting a custom hosts file populated by hostvars[]. The servers not controlled by ansible (or those belonging to another developer) would cause the play to fail, as Ansible would not be able to access them.

I understand that for this use case, one should simply fork the inventory plugin and edit it, but I would think this is a common enough situation that it's a "default feature".

**Pull request closed without merging**
