### PR TITLE
First batch for _facts -> _info rename

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
`_facts` modules should always return `ansible_facts` (and should do so only when these are actually host-specific facts). This renames the first batch of `_facts` modules which do not return `ansible_facts` to `_info`.

Besides these, there are ~200 cloud modules which are named `_facts` but do not return `ansible_facts` (determined via grep, haven't looked in detail yet). These will come later.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
python_requirements_facts
~~jenkins_job_facts~~
~~intersight_facts~~
zabbix_group_facts
zabbix_host_facts
~~github_webhook_facts~~
k8s_facts
~~bigip_device_facts~~
~~bigiq_device_facts~~

### CODE REVIEW

**Comment by felixfontein** [comment]
(There are **not** new modules, but renamed modules.)

**Comment by willthames** [comment]
@felixfontein not sure if splitting this into multiple PRs would be a better idea - I'd be happy enough to merge the k8s changes once I've validated the k8s test suite passes

**Review by willthames — CHANGES_REQUESTED** [review]
Definitely needs a changelog fragment!

**Comment by felixfontein** [comment]
@willthames I can split it up, but that is a lot of extra work and leads to a lot of merge conflicts (for porting guide, since all PRs have to modify it at the same position). That's why I decided to put it into one PR in the end.

**Review by willthames — APPROVED** [review]

**Comment by willthames** [comment]
`k8s_info` passes test suite.

**Comment by willthames** [comment]
`python_requirements_info` passes test suite

**Comment by D3DeFi** [comment]
`zabbix_group_info` should be OK.
 
As for `zabbix_host_facts`, what about adjusting module to return `ansible_facts` instead of current `hosts` variable? Or maybe return both at the same time if we want to be backwards compatible.

**Comment by ffdybuster** [comment]
@D3DeFi `zabbix_host_facts` doesn't query facts about the current host the module is executed on, but from a (possibly) remote server, so it should not be a `_facts` module. `ansible_facts` is for host-related data. (See [here](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_checklist.html#contributing-to-ansible-objective-requirements).)

**Comment by D3DeFi** [comment]
Oh, I've misunderstood it completely. Thanks for correcting me :) 

Lets change `zabbix_host_facts` to `zabbix_host_info` as well then! You have my vote.

**Comment by felixfontein** [comment]
Rebasing to remove conflicts in `bigip_device_facts`.

**Comment by felixfontein** [comment]
I threw out most modules, so now it is only about `python_requirements_facts`, `zabbix_group_facts`, `zabbix_host_facts` and `k8s_facts`, so I guess we can merge it now. I'll create two new PRs once this is merged, one for the network modules and one for the others based on the original PR commits. (These won't conflict.)

@willthames @D3DeFi if you don't complain, I'll merge this tomorrow.

**Comment by D3DeFi** [comment]
sure :)
+1

**Comment by felixfontein** [comment]
@willthames @D3DeFi thanks a lot for reviewing this!

**Pull request merged**
