### PR TITLE
Add the option to use config file instead of enviroment variables

### PR DESCRIPTION
**Pull request by dgoetz**
##### SUMMARY
Add the option to use config file instead of enviroment variables and some error handling for the requests. This is done because of the Foreman integration does not allow to give environment variables to the callback plugin.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Foreman callback plugin

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### ADDITIONAL INFORMATION
Use case is running Ansible roles from Foreman GUI through proxy, which results in empty reports because access is denied as it uses the default values. I only managed to get it working through adding configuration directly to the callback script which is not a good practice as it is provided by the ansible package and will be overritten on update.

### CODE REVIEW

**Comment by bcoca** [comment]
no need to do this, you can declare config items and they will be automatically parsed from ansible.cfg

**Comment by dgoetz** [comment]
@bcoca Can you give me a hint on how to do so as I found no way to set the required environment variables? Or do you mean it should use ansible.cfg instead of its own ini file? I used the ini file as it will already exist when using the dynamic inventory script for Foreman.

**Comment by bcoca** [comment]
You can see an example here: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/logentries.py
You just need to define the options in the docs and the env vars there, Ansible then reads the docs to lookup the config settings.

As for using the external ini, you can still do that, but i would suggest also allowing ansible.cfg entries to be available for those wanting a unified config.

**Comment by dgoetz** [comment]
Thanks for the example. I think I already got it (and it is much easier), but requires some more testing. Afterwards I will rework my PR. 
I will drop the external ini then to not require an additional python module.

**Comment by dgoetz** [comment]
I changed the PR like you suggested and it works fine for me, but I see some tests failing (and one pending as it loops while failing to connect) and I have no idea why or if it is really an issue of my changes.

**Comment by dLobatog** [comment]
cc myself @dlobatog

**Pull request merged**
