### PR TITLE
urls: fix typo in examples section (#39777)

### LINKED ISSUE #39777: urls.py - typo in example section
##### ISSUE TYPE

 
 - Documentation Report

##### COMPONENT NAME

urls

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel a121b5073c) last updated 2018/05/06 16:40:14 (GMT +200)
  config file = /Users/kamjar.gerami/Documents/haxx/ansible/source_code/ansible/lib/ansible/modules/cloud/misc/ansible.cfg
  configured module search path = [u'/Users/kamjar.gerami/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kamjar.gerami/Documents/haxx/ansible/source_code/ansible/lib/ansible
  executable location = /Users/kamjar.gerami/Documents/haxx/ansible/source_code/ansible/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

DEPRECATION_WARNINGS(/Users/kamjar.gerami/Documents/haxx/ansible/source_code/ansible/lib/ansible/modules/cloud/misc/ansible.cfg) = False

##### OS / ENVIRONMENT

Darwin kamger.lan 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

##### SUMMARY

Typo in urls.py fetch_url() example section.

##### STEPS TO REPRODUCE

```
  Example::

        data={...}
        resp, info = fetch_url(module,
                               "http://example.com",
                               data=module.jsonify(data)
                               header={'Content-type': 'application/json'},
                               method="POST")
        status_code = info["status"]
        body = resp.read()
        if status_code >= 400 :
            body = info['body']
```

##### ACTUAL RESULTS

```
The error was: TypeError: fetch_url() got an unexpected keyword argument 'header'
```

### PR DESCRIPTION
**Pull request by kamigerami**
##### SUMMARY

missing s in keyword argument header and , in the line above it.

Fixes #39777 
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

urls
##### ANSIBLE VERSION

```
ansible 2.6.0 (devel a121b5073c) last updated 2018/05/06 16:40:14 (GMT +200)
  config file = /Users/kamjar.gerami/Documents/haxx/ansible/source_code/ansible/lib/ansible/modules/cloud/misc/ansible.cfg
  configured module search path = [u'/Users/kamjar.gerami/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kamjar.gerami/Documents/haxx/ansible/source_code/ansible/lib/ansible
  executable location = /Users/kamjar.gerami/Documents/haxx/ansible/source_code/ansible/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Comment by kamigerami** [comment]
bot_status

**Comment by kamigerami** [comment]
Closing and re-opening for CI trigger.

**Comment by kamigerami** [comment]
Closing and re-opening for CI trigger.

**Comment by kamigerami** [comment]
Closing and re-opening for CI trigger.

**Comment by Akasurde** [comment]
@kamigerami I see several failures https://app.shippable.com/github/ansible/ansible/runs/64339/25/console but these seems to be irrelevant to changes. cc @mattclay

**Comment by kamigerami** [comment]
@Akasurde and @mattclay I totally agree - all of the failures have been due to shippables environment. 

This commit does not change anything that would cause failures. 

shippit!

**Comment by mattclay** [comment]
I've fixed the issue that was causing the unrelated failures and restarted CI.

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
