### PR TITLE
Create Pagerduty namespace and update existing module names

### PR DESCRIPTION
**Pull request by mattyjones**
##### SUMMARY

I am building out several pagerduty modules and in order to start creating pull requests for them I am creating the initial pr to rename existing pagerduty modules to be more specific and based upon the api they are using as well as creating a new directory `pagerduty` under `monitoring` to keep them organized as currently there are 6 modules completed.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

- /modules/monitoring/pagerduty_incident
- /modules/monitoring/pagerduty_maintenance_window

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel f20d809b4c) last updated 2017/09/08 20:14:10 (GMT -400)
  config file = None
  configured module search path = [u'/Users/matt.jones/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/matt.jones/Projects/mattyjones/ansible/lib/ansible
  executable location = /Users/matt.jones/Projects/mattyjones/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### ADDITIONAL INFORMATION
I am working on creating modules for each pagerduty api endpoint. Currently I have teams, users, and contact_info complete. I have also created a library of common functions for these modules. This pr refactors the names or existing pagerduty modules and also creates a directory where they can be grouped together by product.

### CODE REVIEW

**Comment by mattyjones** [comment]
What needs to de done by myself or refactored to get this merged. I would like to start refactoring the existing modules one at a time and get the new modules pushed in one at a time.

Thanks!

**Comment by mattyjones** [comment]
@jborean93 Anything I can do to help with this, I understand everyone probably has day jobs that take priority. All the new modules will be submitted one at a time but it made sense to me anyway to submit this change as a whole.

**Comment by jborean93** [comment]
@mattyjones, for initial modules you need to get 2 community members to review and add a shipit. I don't work in this area so can't really give a proper review myself. Best bet is to review other people's PR's and ask for people to do the same for you.

**Comment by gundalow** [comment]
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

**Comment by gundalow** [comment]
Please update the https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/porting_guide_2.5.rst to include the rename.

**Pull request closed without merging**
