### PR TITLE
Remove cursor parameter since it's the default and breaks.

### PR DESCRIPTION
**Pull request by mmriis**
##### SUMMARY
mysql_replication module gave an error. It sets the same cursorclass as in the `module_utils/mysql.py` and removing this redundant parameter fixes the error.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mysql_replication

##### ADDITIONAL INFORMATION
mysql_replication module didn't work for me. It gave me the following error using this task:

```yaml
- name: test
  mysql_replication:
    mode: getmaster
```
```
The full traceback is:
  File "/tmp/ansible_mysql_replication_payload_88feug8a/__main__.py", line 245, in main
    connect_timeout=connect_timeout)
  File "/tmp/ansible_mysql_replication_payload_88feug8a/ansible_mysql_replication_payload.zip/ansible/module_utils/mysql.py", line 78, in mysql_connect
    return db_connection.cursor(cursorclass=mysql_driver.cursors.DictCursor)

fatal: [db01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "master_auto_position": false,
            "master_connect_retry": null,
            "master_host": null,
            "master_log_file": null,
            "master_log_pos": null,
            "master_password": null,
            "master_port": null,
            "master_ssl": false,
            "master_ssl_ca": null,
            "master_ssl_capath": null,
            "master_ssl_cert": null,
            "master_ssl_cipher": null,
            "master_ssl_key": null,
            "master_user": null,
            "mode": "getmaster",
            "relay_log_file": null,
            "relay_log_pos": null,
            "ssl_ca": null,
            "ssl_cert": null,
            "ssl_key": null
        }
    },
    "msg": "unable to find /root/.my.cnf. Exception message: cursor() got an unexpected keyword argument 'cursorclass'"
}
```

### CODE REVIEW

**Comment by Pluggi** [comment]
Works for me!

**Comment by Andersson007** [comment]
@mmriis hello, thank you for reporting and 
i use MySQLdb of version 1.2.5 and i haven't seen any errors with the playbook from the description.
I looked at the related source code of mysql.py and it looks a bit strange.
Could you tell me which library do you use in this case and which version?

needs_info

**Review by Andersson007 — COMMENTED** [review]
@mmriis hello, thank you for reporting and
i use MySQLdb of version 1.2.5 and i haven't seen any errors with the playbook from the description.
I looked at the related source code of mysql.py and it looks a bit strange.
Could you tell me which library do you use in this case and which version?

needs_info

**Comment by mmriis** [comment]
@Andersson007  I just tried running this and it works now...(?)

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymysql
>>> pymysql.get_client_info()
'0.8.0'
```
This is on the server side.. locally I dont have either library installed.

That version is from Dec 20, 2018 though.

I'm confused.

**Comment by Andersson007** [comment]
@mmriis , yep, on the server side.
As we know the modules use pymysql or MySQLdb if pymysql is not presented, so seems you use pymysql. Ok, thanks!
As i wrote above when we use MySQLdb the 'cursorclass' keyword arg is presented in the library, therefore no errors happen.
I'm trying to figure it out, probably the problem is in mysql.py logic because
it mustn't use 'cursorclass' in case of using pymysql lib..
Ok, i'll look at the source code again. Thank you for your feedback!

**Comment by Andersson007** [comment]
@mmriis , could you please try #61832 (better not only showing master status)
waiting for your feedback

if we just remove this keyword_arg as in your PR it'll break the module, e.g.
it returns
```
"Is_Slave": false
```
but actually it must be
```
ok: [mysrv] => {
    "Connect_Retry": 60, 
    "Exec_Master_Log_Pos": 1316, 
    "Is_Slave": true, 
    "Last_Errno": 0, 
    "Last_Error": "", 
    ...
```

**Comment by Andersson007** [comment]
@mmriis , sorry, i did a lot of manipulation but now my pr just clarifies actual logic and i don't now why it works correctly. i caught that error before but now i can't. I have pymysql of 0.9.3 version

**Pull request closed without merging**
