### PR TITLE
derived aci_access_port_to_interface_policy_leaf_profile for fex port…

### PR DESCRIPTION
**Pull request by LucRobalo**
… selector

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by smnmtzgr** [comment]
@LucRobalo Can you describe why we need a new module here? interface_type "fex" is already available with [aci_access_port_to_interface_policy_leaf_profile](https://docs.ansible.com/ansible/devel/modules/aci_access_port_to_interface_policy_leaf_profile_module.html#aci-access-port-to-interface-policy-leaf-profile-module)

**Comment by LucRobalo** [comment]
This module is required if you need to had an interface selector to a fex interface profile as the object in the policy model is not the same.

The reference you make is used to create a inter selector of type fex while here it is for Port on the fex.

Sorry for the typo. I removed the fex option from the documentation as you cannot daisy chain fex.

I will check the file tomorrow and update it in me repo.

Sorry for the mistakes this is my first time.

Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dagwieers** [comment]
@rsmeyers @devarshishah3 Please advice. Is this needed/useful?

**Comment by rsmeyers** [comment]
yes, this is needed when managing fex'es

**Comment by dagwieers** [comment]
@LucRobalo This PR is created in someone else's name. CI also detected various issue that need to be resolved.

**Comment by LucRobalo** [comment]
@dagwieers i will check thia sorry for not having cleaned it up

**Comment by aciguru** [comment]
Moved to

https://github.com/CiscoDevNet/ansible-aci/issues/17

**Pull request closed without merging**
