### PR TITLE
Skipping facts not available in AIX WPARs

### PR DESCRIPTION
**Pull request by mplonka**
Skipping facts not available in AIX WPARs

### CODE REVIEW

**Comment by mplonka** [comment]
CPU & swap information is not available on AIX WPARs.
This is a port of #3307 from release1.2 branch.

**Comment by mpdehaan** [comment]
Can you please submit this without merge commits?

I would recommend starting a new branch for starters, probably named "aix_wpar" so it does not need to get mixed in with other updates you might make on the development branch.

Then, always use "git pull --rebase" vs "git pull" and "git rebase" vs "git merge".

Thanks!

**Comment by mpdehaan** [comment]
Ok I will just cherry pick this one :)

**Comment by mpdehaan** [comment]
merged in, thanks!

**Pull request closed without merging**
