### PR TITLE
Rabbitmq parameters module

### PR DESCRIPTION
**Pull request by chrishoffman**
This module adds support for setting cluster-wide parameters in RabbitMQ

### CODE REVIEW

**Comment by mpdehaan** [comment]
Awesome, I am not sure if I shared but one I almost wrote a "rabbit MQ to INI file and back again" transformation script, just out a want to be able to manage it in a sane way.  This is great and there is a strong chance I will be using this for Ansible Commander for our celery guests, if we go that route.

**Comment by mpdehaan** [comment]
Merged in, thanks!

**Comment by chrishoffman** [comment]
The config files are really tough to work with and I am glad they give the rabbitmqctl utility.  I have a few more that I want to do, specifically policy and cluster, and the feature set should be complete.  Looking forward to seeing the Commander in action and would love to help.

**Comment by mpdehaan** [comment]
Getting ideas together, will probably be a week or two before I have a
skeleton project ready to share.

But absolutely, that will be great!

**Pull request merged**
