### PR TITLE
postgresql_db fails with owner containing a "-"

### PR DESCRIPTION
**Pull request by legrostdg**
```
TASK: [postgresql_db db=cartoterra owner=www-cartoterra template=template_postgis] ********************* 
failed: [192.168.122.216] => {"failed": true}
msg: Database query failed: ERREUR:  erreur de syntaxe sur ou près de « - »
LINE 1: CREATE DATABASE cartoterra OWNER www-cartoterra TEMPLATE tem...
                                            ^


FATAL: all hosts have already failed -- aborting
```

### CODE REVIEW

**Comment by legrostdg** [comment]
second commit fixes https://github.com/ansible/ansible/issues/1819

**Comment by dhozac** [comment]
has_table_privilege and has_database_privilege shouldn't be changed, the database layer will quote those values. Drop those two hunks and this looks good to me, thanks!

**Comment by dhozac** [comment]
Merged, thanks!

**Pull request merged**
