### PR TITLE
Add in a ssh_host_key module to manage ssh host keys in the main system /etc/ssh/ssh_known_hosts file

### PR DESCRIPTION
**Pull request by kormoc**
Add in a ssh_host_key module to manage ssh host keys in the main system /etc/ssh/ssh_known_hosts file

### CODE REVIEW

**Comment by mpdehaan** [comment]
This seems like this really should be a "known_hosts" module that is generic, rather than something that is specific to /etc/ssh/known_hosts.

And in most cases, you could just template the file.

The problem with just adding to it line by line is you don't know what is in something that you don't want to be there.

**Comment by jctanner** [comment]
@kormoc also take a look at the known hosts module snippet I created yesterday for the git module: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/known_hosts.py

**Comment by kormoc** [comment]
@jctanner I submitted #5587 to fix up the known hosts management in the git module. It's entirely broken for me right now

@mpdehaan `known_hosts_file` is a option to specify the path. This defaults to `/etc/ssh/ssh_known_hosts` but is user configurable.

I'm not sure what you mean by the line to line addition is an issue. This mirrors the current authorized_keys file behaviour. Why would this file be different?

**Comment by bcoca** [comment]
I do this with a simple play, i dont see the need for a module

**Comment by kormoc** [comment]
I believe there is value in having this as a module. I currently have a few dozen spots where we need to pull in these keys and this would simplify and prevent mistakes when copying and pasting a bunch of tasks. DRY after all

**Pull request closed without merging**
