### PR TITLE
Update setup module for facts derived from classes

### PR DESCRIPTION
**Pull request by sfromm**
This changes and organizes facts into a base class Facts and several
sub classes that implement the necessary functionality.  The classes
are:
- Facts: base class.  Implements basic facts that should be common to a
  number of platforms.  It is also where SSH keys and SELinux facts are
  set.
- Hardware: A subclass of Facts that should be further
  subclassed per platform for CPU, memory, and related facts.
  - LinuxHardware: subclass of Hardware for Linux platforms
  - SunOSHardware: subclass of Hardware for SunOS platforms
  - FreeBSDHardware: subclass of Hardware for FreeBSD
- Network: A subclass of Facts that that should be further
  subclassed per platform for IP, both IPv4 and IPv6, information.
  - LinuxNetwork: Currently only implementation for determining network
    facts.
- Virtual: A subclass of Facts that that should be further
  subclassed per platform to determine virtual environment facts.
  - LinuxVirtual: Currently only implementation for determining virtual
    facts.

If facts are needed for additional platforms, one of the above classes
(eg Network) can be further subclassed and implement the necessary
functionality.

In addition, it fixes get_network_facts() to work on Fedora17.  That
broke due to changes to ifconfig output.

Changes were tested against debian, centos5, centos6, solaris10, and freebsd9.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This in all looks very good.   The one thing I don't particularly like is the signature of this method, and if you update it, I can apply things

def ansible_facts():
    facts = {}
    f = Facts(facts)
    f.populate()
    f = Hardware(f.facts)
    f.populate()
    f = Network(f.facts)
    f.populate()
    f = Virtual(f.facts)
    f.populate()
    return f.facts

If f is a dictionary, it's bad form to assign it to other types of variables repeatedly, and the idea that we construct a Virtual based on a Network is a little confusing.

What you should do is have each class set a ".facts" attribute and then just do:

results  = {}
results.update(Virtual.compute())
results.update(Hardware.compute())
results.update(Network.compute())

This also changes things such that rather than the indivdual methods having side effects, they instead return individual hashes, making them more easy to test inside a debugger.  

For instance, i could just instantiate a Network object and call compute on it, and it would print out a hash.

(I tend to like epdb... because it has a built in remote debugger that works very well and technically allows for remote debugging of ansible modules.)

**Comment by mpdehaan** [comment]
Another thing is I think that rather than unkown facts seing set to "NA" they should be missing.  This way, they are not available in the list of variables if you run the setup module, and also do not take up any memory.

**Comment by mpdehaan** [comment]
Also, how does LinuxHardware vs SunOS Hardware get selected?  I'm reading through the code and it looks like it's going to pick Hardware every time.   Perhaps something that didn't get pushed or I'm just not reading it right.

Seems like we'd have a top level class for each OS Type, and a method to get the OS type, that returns a class that can return it's Hardware Fact class or something like that.   Didn't see that though?

Thanks for doing this.   This is pretty close and I think it will be very very useful for people adding new platforms and keeping the setup code organized!

**Comment by mpdehaan** [comment]
I'm also changing the setup module to not write to a file anymore, so you will be able to delete the MD5 and file writing parts... I will have that pushed to the existing copy of library/setup soon...

**Comment by sfromm** [comment]
Comment inline below.

On Sat, Jul 14, 2012 at 7:56 AM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> This in all looks very good.   The one thing I don't particularly like is
> the signature of this method, and if you update it, I can apply things
> 
> def ansible_facts():
>     facts = {}
>     f = Facts(facts)
>     f.populate()
>     f = Hardware(f.facts)
>     f.populate()
>     f = Network(f.facts)
>     f.populate()
>     f = Virtual(f.facts)
>     f.populate()
>     return f.facts
> 
> If f is a dictionary, it's bad form to assign it to other types of
> variables repeatedly, and the idea that we construct a Virtual based on a
> Network is a little confusing.
> 
> What you should do is have each class set a ".facts" attribute and then
> just do:
> 
> results  = {}
> results.update(Virtual.compute())
> results.update(Hardware.compute())
> results.update(Network.compute())

That is certainly doable and makes sense.  I think the reason for sending
in the facts from other components was that some facts depend on others.
 But, that can likely be addressed by setting the variables at object
instantiation and inheriting them.  One I can think of off the top of my
head is _distribution_ and _distribution_.

I'll try to follow up this week with an updated patch.

> This also changes things such that rather than the indivdual methods
> having side effects, they instead return individual hashes, making them
> more easy to test inside a debugger.
> 
> For instance, i could just instantiate a Network object and call compute
> on it, and it would print out a hash.
> 
> (I tend to like epdb... because it has a built in remote debugger that
> works very well and technically allows for remote debugging of ansible
> modules.)

## 

Stephen Fromm

**Comment by sfromm** [comment]
On Sat, Jul 14, 2012 at 7:57 AM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> Another thing is I think that rather than unkown facts seing set to "NA"
> they should be missing.  This way, they are not available in the list of
> variables if you run the setup module, and also do not take up any memory.

I was thinking of setting 'NA' as a marker that a given set of facts had
not yet been implemented for one's platform.  There are also several facts
that presently (ie on devel branch) default to 'NA' or 'None' because they
haven't been implemented or there is no corollary for that platform.  Two
examples include virtualization_role, virtualization_type, and the DMI
facts.  The approach in this patch preserves the current behavior as much
as possible.  That said, I'm open to not initializing these facts on
platforms that need to be implemented.

## 

Stephen Fromm

**Comment by sfromm** [comment]
On Sat, Jul 14, 2012 at 8:02 AM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> Also, how does LinuxHardware vs SunOS Hardware get selected?  I'm reading
> through the code and it looks like it's going to pick Hardware every time.
>   Perhaps something that didn't get pushed or I'm just not reading it right.

In the Hardware **new**() method, it checks the the platform variable in
all subclasses of Hardware.  When it finds one that matches the return
value of platform.system(), it returns that subclass for instantiation.  If
it doesn't find a matching subclass, it returns Hardware itself for
instantiation.

The same is true for Network and Virtual.

> Seems like we'd have a top level class for each OS Type, and a method to
> get the OS type, that returns a class that can return it's Hardware Fact
> class or something like that.   Didn't see that though?

I was thinking in terms of a set of facts that would then be implemented
per platform.  The class for that set of facts would then instantiate the
appropriate subclass.  This way, the logic is in the classes.

> Thanks for doing this.   This is pretty close and I think it will be very
> very useful for people adding new platforms and keeping the setup code
> organized!

Sure thing.   I hope it gets it moves things forward enough such that
people do not have tweak the code to sidestep tracebacks/exceptions for
unknown platforms.

## 

Stephen Fromm

**Comment by mpdehaan** [comment]
(A) sounds good, I think the cleanup in return values will be worth it.

(B) I think any NA/None stuff needs to go because there are ways to check for an empty fact in the template, and "NA" is not empty, and doing a string comparison test to "NA" feels weird and not what you would expect.  Plus, it means more facts come back, which just take up time and space.

(C) ok apparently I read too quickly there, would be pretty sure the code you added worked.

Thanks!

**Comment by mpdehaan** [comment]
looks like my force push wrecked utter hell on this pull request, I am going to close it, but it's my fault, not yours.

please resubmit whenever you like.

**Comment by pas256** [comment]
mdehaan and I were chatting in IRC today:

I was trying to run `ansible-playbook -c local ...` on my OSX laptop, and had issues with:

```
GATHERING FACTS ********************* 
failed: [localhost] => {"failed": true, "msg": "", "parsed": false}
```

I traced the issue down to the setup module, inside get_interfaces(), line 225

```
bytelen = struct.unpack('iL', fcntl.ioctl(                                                         
    s.fileno(), SIOCGIFCONF, struct.pack(                                                          
        'iL', length, names.buffer_info()[0])                                                      
    ))[0]          
```

On OSX, this code stacktraces with

```
IOError: [Errno 102] Operation not supported on socket
```

mdehaan doesn't like that code anyway, so since you are working on the setup module, perhaps you wouldn't mind looking into that code and removing it (paraphrased).

Please let me know if there is something I can do to help.

**Comment by mpdehaan** [comment]
my point was I don't think the setup module has any business making low level ioctl calls and that info should be available easier, though I think once we have the OS detection stuff committed the answer to Peter's problem is a little simpler… don't compute Linux facts on OS X :)

**Comment by sfromm** [comment]
On Wed, Jul 18, 2012 at 2:47 PM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> looks like my force push wrecked utter hell on this pull request, I am
> going to close it, but it's my fault, not yours.
> 
> please resubmit whenever you like.

Okay, I was wondering what happened when I tried to pull in latest changes
from upstream.  I'm working on restoring the last PR and some changes to
that following prior discussion here.

sf

**Comment by sfromm** [comment]
On Wed, Jul 18, 2012 at 2:55 PM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> my point was I don't think the setup module has any business making low
> level ioctl calls and that info should be available easier, though I think
> once we have the OS detection stuff committed the answer to Peter's problem
> is a little simpler… don't compute Linux facts on OS X :)

The ioctls are there specifically to help with determining network
information.  I'm trying to limit how much I execute system calls via
subprocess because parsing command output is such a fragile process.  In my
short time with the setup module, the output from sestatus and ifconfig
have broken fact collection.  As much as possible, I'd prefer to avoid
parsing system call output for fact values.

For the specific case of network facts, I'd prefer to avoid system calls
completely.  Unfortunately, I haven't found a mechanism that, in ipv4 land,
returns all ip addresses associated with a node and, in ipv6 land, returns
the prefix for the specified address.  If others have a suggestion, please
let me know. :-)  One option is netifaces, but it isn't stdlib.

In regards to Peter's problem, yes, the proposed changes should solve this
problem.

**Comment by mpdehaan** [comment]
I was wondering about proc, but fair enough -- just not running it on OS X is really all there is to it :)

**Comment by sfromm** [comment]
On Wed, Jul 18, 2012 at 3:18 PM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> I was wondering about proc, but fair enough -- just not running it on OS X
> is really all there is to it :)

Turns out I was mistaken for ipv6.  /proc/net/if_inet6 does have all you
need.  There is no equivalent for ipv4 in /proc.  You can try to gather
some of that information from /proc/net/tcp, but that doesn't have ifname
and netmask.

sf

**Comment by sfromm** [comment]
Funny enough, I found macaddrs buried in /sys/class/net.  I may be able to
get rid of the ioctls and make things more readable.  :-)

**Pull request closed without merging**
