### PR TITLE
Fix a possible issue with comparing values with $null

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:
- Fix $null comparison.
- Simplify Get-AnsibleParam in the same effort

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
Ansible.ModuleUtils.Legacy.psm1

##### ANSIBLE VERSION
v2.6

### CODE REVIEW

**Review by jborean93 — APPROVED** [review]
Looks good to me

**Comment by jborean93** [comment]
@dagwieers I can't remember, was this to fix an actual issue or just to work with the pslint rules we had at the time?

**Comment by dagwieers** [comment]
@jborean93 This was originally to fix the PSLint rule which we then disabled. But IIRC this was a genuine issue in this specific case as indicated by the comment above the $null comparison.

So we make it very simple, if it is actually $null, we return $null with no special treatment from the very start, easier to read that code IMO.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/71742/18/tests

**Comment by dagwieers** [comment]
@mattclay The CI failures are caused by regressions in Ansible v2.6 (fixed by: #42330).

**Comment by dagwieers** [comment]
@jborean93 The `$null -eq $value` was in the meantime already fixed, but this still simplifies the logic. So I would prefer if it got merged anyhow.

**Comment by jborean93** [comment]
@dagwieers is this actually fixing an issue, I'm reluctant to change `Legacy.psm1` unless there is a real reason to.

**Comment by dagwieers** [comment]
Readability, there's no need anymore to check for an array, or that complexity. Check the diff without whitespace-changes and you'll see this is trivial.

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Fair enough, didn't have the whitespace-changes check and it seems trivial now.

**Pull request merged**
