### PR TITLE
Several enhancements for Radware modules and their unit testing

### PR DESCRIPTION
**Pull request by minievg**
##### SUMMARY
Adding support for Plugin runnable type
Adding support for device arrays in vdirect_runnable module.
Adding "output" dictionary to the vdirect_runnable module result dictionary.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vdirect_runnable vdirect_file vdirect_commit

##### ADDITIONAL INFORMATION
These are mainly enhancements for vdirect_runnable module.
It adds support of another runnable type - Plugin
And allows specifying device names lists in addition to single device name.

### CODE REVIEW

**Comment by evgenyfedoruk** [comment]
Hi guys,

Here is a PR with some Radware modules enhancements.
Please review it.

Regards

**Comment by ganeshrn** [comment]
rebuild_merge

**Comment by ganeshrn** [comment]
@evgenyfedoruk @minievg  For the fix to be available in 2.9 version you need to cherry-pick this PR to stable-2.9 branch.

**Comment by evgenyfedoruk** [comment]
@ganeshrn Thanks for merging it. I will consider porting it back to 2.9

**Pull request merged**
