### PR TITLE
Fix connection_lxd and connection_docker integration tests

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

`connection_lxd` and `connection_docker` tests were failing with a "injector.py: No such file or directory"
error. We fix the problem by overriding `ANSIBLE_TEST_REMOTE_INTERPRETER`.

I've also added a little helper comment in connection_docker's inventory.

This is a simpler fix than my previous proposal, pr #27395 and was done with the tip from @mattclay.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
integration tests

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = None
  configured module search path = [u'/home/vdupras/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vdupras/src/ansible/.tox/py27/lib/python2.7/site-packages/ansible
  executable location = /home/vdupras/src/ansible/.tox/py27/bin/ansible
  python version = 2.7.12 (default, Jun  9 2017, 11:18:57) [GCC 5.4.0]
```

##### ADDITIONAL INFORMATION

One way to reproduce the problem is to run `container_lxd` trough a virtualenv, after having properly set up a `centos-7-amd64` LXD container.

```
$ . .tox/py27/bin/activate
$ ./test/runner/ansible-test integration --local connection_lxd
...

TASK [remove remote file with unicode filename and content] ***************************************************************************************************
fatal: [lxd-pipelining]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/bin/sh: /tmp/ansible-test-coverage-RNxgFb/coverage/injector.py: No such file or directory\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 127}
```

And with this fix:

```
$ ./test/runner/ansible-test integration --local connection_lxd

...

PLAY RECAP ****************************************************************************************************************************************************
lxd-no-pipelining          : ok=11   changed=8    unreachable=0    failed=0
lxd-pipelining             : ok=11   changed=8    unreachable=0    failed=0
```

It's the same result with `connection_docker`.

### CODE REVIEW

**Comment by s-hertel** [comment]
cc @mattclay

**Comment by mattclay** [comment]
@hsoft You should no longer need to set `ANSIBLE_TEST_REMOTE_INTERPRETER` in these tests. I've [added support](https://github.com/ansible/ansible/pull/27436) for a `non_local` alias to accommodate this and related scenarios more easily.

**Comment by ghost** [comment]
@mattclay Yes, I've seen this. That's a lot of aborted PR's lately :) But then again, that allows me to discover ansible's test suite.

**Comment by mattclay** [comment]
@hsoft Feel free to ping me in #ansible-devel on IRC if you'd like to discuss anything testing related. It might be easier to coordinate there then over PR comments.

**Pull request closed without merging**
