### PR TITLE
Basic RDS support for EC2 inventory

### PR DESCRIPTION
**Pull request by peterjanes**
For issue 2383.

### CODE REVIEW

**Comment by blair** [comment]
Suggest looking at 5d0f78d which was just merged into devel which provides the region name in addition to the availability zone.  Could you incorporate this change in the RDS info.

\cc @lwade

**Comment by mpdehaan** [comment]
any update on this, @blair @peterjanes @lwade ?

**Comment by peterjanes** [comment]
Current projects aren't using RDS, so I don't anticipate having time to add regions in the near future.

**Comment by lwade** [comment]
I'm not using RDS for anything too but this looks good for starters.

**Comment by blair** [comment]
This commit looks good by itself, but it would be odd for parts of ec2's returned data to include the region and others not.

**Comment by lwade** [comment]
Agreed, hopefully someone can add this later :)

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
