### PR TITLE
Added support for iptables IPVS match

### PR DESCRIPTION
**Pull request by stephan2012**
##### SUMMARY

Added support for the missing IPVS match target in the `iptables` module

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

iptables

##### ADDITIONAL INFORMATION

Setting up Source NAT for, e.g. one-armed IPVS-based loadbalancers lacked support for the VIP address and VPort arguments. This PR implements these arguments and allows issueing

```yaml
- name: "Setup SNAT for LVS"
  iptables:
    table: nat
    chain: POSTROUTING
    match: ipvs
    vaddr: '192.168.1.11/24'
    vport: 443
    jump: SNAT
    to_source: '192.168.1.21'
    comment: "SNAT the VIP"
```

which is the equivalent of

```
iptables -t nat -A POSTROUTING -m ipvs --vaddr 192.168.1.11 --vport 443 -j SNAT --to-source 192.168.1.21
```

Like other matches it requires a kernel module to be loaded first (`xt_ipvs` in this case).

### CODE REVIEW

**Comment by relrod** [comment]
Can you rebase this to resolve the conflict, and add a changelog and (if possible) tests?

**Comment by stephan2012** [comment]
@relrod, at the moment I am too busy. Either please take over or wait until I can do it.

**Comment by ophum** [comment]
@stephan2012 Thank you for your feature!. I fixed conflict of your pull request, because I need this, too.

**Comment by stephan2012** [comment]
> @stephan2012 Thank you for your feature!. I fixed conflict of your pull request, because I need this, too.

@ophum Big thanks for taking care of this issue!

**Comment by stephan2012** [comment]
Closing in favor of PR #76219.

**Pull request closed without merging**
