### PR TITLE
eos_config: Added fix for bug #54400 - support for !! in config mode

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### SUMMARY
Fixes bug #54400

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/network/common/config.py

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by Qalthos** [comment]
rebuild_merge

**Review by Qalthos — APPROVED** [review]

**Comment by GomathiselviS** [comment]
rebuild_merge

**Pull request merged**
