### PR TITLE
[FEATURE] add spacewalk api dynamic inventory script

### PR DESCRIPTION
**Pull request by jacobsalmela**
Signed-off-by: Jacob Salmela <me@jacobsalmela.com>

##### SUMMARY
Introduces a dynamic inventory script that uses the Spacewalk API (v2.9).  This is a different approach than the existing `spacewalk.py` dynamic inventory script, which uses `spacewalk-reports` command.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`spacewalk_api.py`

##### ADDITIONAL INFORMATION
This is a dynamic inventory script that uses the Spacewalk API as a source.   Spacewalk isn't really being developed anymore, but some people still use it heavily for patching, which makes it a decent source of truth for some.  

In addition to getting hosts and groups, I have also included other things like `dmidecode` information, CPU stuff, and network information.  

More to come to expand this script if the PR is merged.

### CODE REVIEW

**Comment by imlight** [comment]
@jacobsalmela :- This script is good , only problem is it is adding all the hosts to the all the groups listed in spacewalk. 

I mean if host A is part of group X and host B is part of group Y and hosts A, B are part group Z , then with this inventory script it looks like below in AWX 

Group X [ A,B]
Group Y [A,B]
Group Z[A,B]

**Comment by jacobsalmela** [comment]
OK I will take a look and send an update.

**Comment by imlight** [comment]
@jacobsalmela  I do not think the issue I am seeing has anything to do with the "-" character in the group name.

**Comment by jacobsalmela** [comment]
I'm not seeing the same behavior in my tests...
```
...
...
    },
    "all": {
        "children": [
            "development",
            "production",
            "ungrouped"
        ]
    },
    "development": {
        "hosts": [
            "client",
            "talvath"
        ]
    },
    "production": {
        "hosts": [
            "client",
            "talvath"
        ]
    },
    "ungrouped": {}
}
```

**Comment by jacobsalmela** [comment]
Thanks to some outside help, I should be able to fix the issue

**Comment by jacobsalmela** [comment]
OK @imlight I think the above should fix it

**Comment by imlight** [comment]
That looks to work . 

Thanks

**Comment by jacobsalmela** [comment]
Cool.  Now we'll just wait and see if the Ansible team thinks it's merge-worthy!

**Comment by guymatz** [comment]
Hi!!  Did this ever get merged?  I could really use it!!

**Comment by sivel** [comment]
This PR is still open, and thus not merged. We are no longer accepting new inventory scripts to this repo. This PR would need to likely be re-submitted to https://github.com/ansible-collections/community.general or other appropriate collection repository.

**Comment by jacobsalmela** [comment]
OK, the next chance I get, I'll resubmit it there.

**Comment by Akasurde** [comment]
Hi @jacobsalmela, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
