### PR TITLE
CPM plug configuration for WTI Power Devices

### PR DESCRIPTION
**Pull request by syncpak**
##### SUMMARY
Added the module cpm_plugconfig to be able configure various plug parameters of WTI Power devices.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
cpm_plugconfig

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (cpm_plugconfig 62de3fb580) last updated 2018/11/02 08:50:27 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kenp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kenp/ansible/lib/ansible
  executable location = /home/kenp/ansible/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### ADDITIONAL INFORMATION

This module was created as a companion to cpm_plugcontrol. We originally planned on having one module to control and configure the WTI plugs, but is got very messy. So the module was broken out into control and configure operations. Existing WTI customers please contact service@wti.com for access to a BETA version of CPM or VMR code to enable the new RESTful API call to enable this feature.

```paste below

```

### CODE REVIEW

**Comment by mattsene** [comment]
What version of your WTI firmware do i need to use this ?

**Comment by syncpak** [comment]
@mattsene for this particular module you need the firmware we currently have in BETA. To get a copy please email service@wti.com and tell them you need the BETA for Ansible module compatibility testing.

**Comment by actionemb** [comment]
Seems to work. We have a DSM and a CPM and this modules seems to works.

**Comment by mmorrisdev** [comment]
Do you have a product manual link for your DSM device? I am trying to coordinate our units with this Ansible module's parameters.

**Comment by syncpak** [comment]
@mmorrisdev the manuals for all WTI product can be found here. http://www.wti.com/t-product-manuals.aspx

**Comment by wtinetworkgear** [comment]
[shipit]

**Comment by syncpak** [comment]
shipit

**Comment by mattsene** [comment]
shipit

**Comment by vientiane** [comment]
shipit

**Comment by wtinetworkgear** [comment]
shipit

**Comment by scarshouldofwon** [comment]
shipit

**Comment by gundalow** [comment]
Merged into `devel` for release in Ansible 2.8
Thanks for the reviews!

**Pull request merged**
