### PR TITLE
Added some items to the 2.6 Roadmap

### PR DESCRIPTION
**Pull request by abadger**
##### SUMMARY
Add items to roadmap.  @thaumos, is this the appropriate place and level of granularity or do you want them restricted to changelog?

##### ISSUE TYPE
 - Docs Pull Request

##### ANSIBLE VERSION

```
2.6
```

##### ADDITIONAL INFORMATION
Needs review by @thaumos

### CODE REVIEW

**Comment by gundalow** [comment]
+1 to adding this level of detail to changelog

**Comment by abadger** [comment]
I think the module defaults feature deserves to be called out in here.  Not sure about the listing of modules we're concentrating on fixing.

**Comment by abadger** [comment]
Also note in changelog, we'll end up with a random pile of changelog entries, not a coherent picture of which modules we concentrated effort on.  Do we have a release notes doc somewhere?  That's likely where we want a list of modules we successfully concentrated on fixing to land.

**Comment by gundalow** [comment]
Changelog wise, should we have one fragment file per module listing all the bug fix work?

**Comment by abadger** [comment]
I think one fragment per-module defeats the advantages that reno grants us (no conflicts.  Ability to easily cherry-pick a change with its changelog)

**Comment by abadger** [comment]
We still need to figure out where and how to document these, but it won't be done in the 2.6 roadmap document.

**Pull request closed without merging**
