### PR TITLE
s3_bucket: fix connections for buckets with dots in names

### PR DESCRIPTION
**Pull request by zyv**
##### SUMMARY
Refer to 689f135 for similar fix in s3 module.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
modules/cloud/amazon/s3_bucket

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.0.0
  config file = /home/zaytsev/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION
Creating buckets with dots in name fails for AWS non-classic accounts (see boto/boto#2836), example below:

```
s3_bucket:
  name: test.bucket
  state: present
```

Since `OrdinaryCallingFormat` is used by default in most cases anyways, turn the logic around to cover also the last statement.

### CODE REVIEW

**Comment by zyv** [comment]
+affects_2.3

**Comment by zyv** [comment]
@wimnat @ryansb anyone?

**Review by s-hertel — APPROVED** [review]
Reran CI and still passes. Without this fix creating/deleting a bucket with a . in the name results in a traceback. Looks great, thanks for the fix. This doesn't appear to break anything.

**Comment by s-hertel** [comment]
shipit

**Pull request merged**
