### PR TITLE
Bug fixes for GCP modules (as of 2019-01-09T15:35:45-08:00)

### PR DESCRIPTION
**Pull request by rambleraptor**
##### SUMMARY
Bug fixes for GCP modules (as of 2019-01-09T15:35:45-08:00)
This PR is the result of the following Magic Modules PRs:
  - [Skip acceptance tests during non-acceptance runs.](https://github.com/GoogleCloudPlatform/magic-modules/pull/1223)
  - [Remove old gcompute wording](https://github.com/GoogleCloudPlatform/magic-modules/pull/1219)
  - [Un-Beta kms links for compute disk](https://github.com/GoogleCloudPlatform/magic-modules/pull/1204)

##### ISSUE TYPE
- Bugfix Pull Request

##### ADDITIONAL INFORMATION
```
This was generated by [Magic Modules](https://github.com/googlecloudplatform/magic-modules)
```

### CODE REVIEW

**Comment by rambleraptor** [comment]
shipit

**Comment by rambleraptor** [comment]
shipit

**Comment by erjohnso** [comment]
shipit

LGTM

**Comment by rambleraptor** [comment]
shipit

**Comment by jctanner** [comment]
bot_status

**Pull request merged**
