### PR TITLE
Document `--` args separator in encrypt_string cmd

### LINKED ISSUE #46574: ansible-vault fails to encrypt_string that begins with minus character
##### SUMMARY

ansible-vault unable to encrypt string that begins with a '-' character.  The '-' or '--' is interpreted as a parameter and not a string.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-vault

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul  3 2018, 06:28:28) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
ansible-vault encrypt_string '-test'
```

##### EXPECTED RESULTS

```
New Vault password:
Confirm New Vault password:
!vault |
          $ANSIBLE_VAULT;1.1;AES256
          39633034643332643538313034356631656464313965386366343038353132393639353736303336
          3962313663313036376331646439366634316137386162340a333839616362316333616333356239
          32306235623536363930346530313964663035316662656133323865663661383035656463346435
          3438323236626636660a643565396231363737396361653537373463663439616135363666376232
          6364
Encryption successful
```

##### ACTUAL RESULTS

```paste below
Usage: ansible-vault encrypt_string [--prompt] [options] string_to_encrypt

ansible-vault: error: no such option: -t

```

### PR DESCRIPTION
**Pull request by webknjaz**
Fixes #46574

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

vault

##### ANSIBLE VERSION

```paste below
devel
```

##### ADDITIONAL INFORMATION
See #46574

### CODE REVIEW

**Comment by bcoca** [comment]
this is a standard for command line parsing, it doesn't only apply to vault, if we document it, it should go on all CLI options, though i think that is redundant.

**Comment by webknjaz** [comment]
@bcoca see related #46574: users (including myself) often don't realize that such thing is available. Also, It's a common practice to point to it in usage info.

**Comment by bcoca** [comment]
im not against putting it in usage, but its not exclusive to vault, also i would add an FAQ entry

**Comment by ericwb** [comment]
I agree is not a well known option either.  Putting in the usage here helps a little, but I think it could really use some more documentation on what it means to use `--`.  Is this a common pattern in CLI arguments (even non-Python)?  I think it would be good to document in the ansible-vault user guide.

https://docs.ansible.com/ansible/2.6/user_guide/vault.html

**Comment by webknjaz** [comment]
> Is this a common pattern in CLI arguments (even non-Python)?

@ericwb actually it's been a common POSIX practice long before Python existed. So yes, I'd say _especially_ outside of Python :)

**Comment by jimi-c** [comment]
Per discussion, we're going to go ahead and close this as it's more of a shell-specific option as opposed to a vault option.

Thanks!

**Pull request closed without merging**
