### PR TITLE
os_client_config: fix broken import

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
Fix [broken import](https://github.com/ansible/community/wiki/Testing%3A-progress-tracker#fixing-broken-imports) in `os_client_config` module.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
cloud/openstack/os_client_config.py

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0 (devel 7bc85f9b44) last updated 2017/07/14 11:19:12 (GMT +200)
```

### CODE REVIEW

**Review by emonty — APPROVED** [review]
shipit

**Comment by pilou-** [comment]
bot_status

**Comment by pilou-** [comment]
@emonty the bot [ignores](https://github.com/ansible/ansibullbot/issues/677) commands wrote in review summary. Could you please comment this pull request using [`shipit`](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#cmd-shipit) ?

**Review by emonty — APPROVED** [review]
shipit

**Comment by pilou-** [comment]
@rcarrillocruz  @shrews (as randomly selected maintainer of `cloud/openstack` namespace) could you please review this pull request ? At least two `shipit` comments (from maintainers or namespace maintainers or core team members) are required in order to [automerge](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#community) this pull request.

**Comment by Shrews** [comment]
shipit

**Comment by pilou-** [comment]
bot_status

**Review by emonty — APPROVED** [review]
shipit

**Comment by pilou-** [comment]
bot_status

**Comment by pilou-** [comment]
@emonty Ansibot:
- ignores your previous `shipit` comment because a commit has been added
- [ignores](https://github.com/ansible/ansibullbot/issues/677) `shipit` written in review summary.

Could you please comment this pull request using [`shipit`](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#cmd-shipit) ?

**Comment by abadger** [comment]
Merged to devel for inclusion in 2.4.0

**Pull request merged**
