### PR TITLE
add ismount function in module_utils

### LINKED ISSUE #2186: Mount fails if ansible user has no read permission inside mount
##### Summary:

A bug in python os.path makes the mount module fail when
- state=mounted
- filesystem: nfs (probably most others as well)
- the mount is already present
- the ansible user has no read permission inside the mount

The reason for this is that ansible uses os.path.ismount(mountpath) which fails if pointed at a mount inside which the user has no read permission, see http://bugs.python.org/issue2466.
This is quite common if you use nfs with root_squash or kerberos.

The python-bug is quite old and unfixed, so maybe it's worthwhile to have a workaround in ansible. The function in question is 10 lines of python.
##### Steps To Reproduce:

See Summary
##### Expected Results:

Should return 'ok'
##### Actual Results:

returns failed

### PR DESCRIPTION
**Pull request by robinro**
- needed to fix https://github.com/ansible/ansible-modules-core/issues/2186
  via pull request https://github.com/ansible/ansible-modules-core/pull/2737

### CODE REVIEW

**Comment by robinro** [comment]
I'm not completely sure the inclusion of the python license is sufficient the way I did it.

**Comment by abadger** [comment]
Thanks @robinro I've merged this so that we don't have this dependency blocking the fix to the mount module.  It is in the devel branch so it will be in 2.1.0 when we release that.

**Comment by abadger** [comment]
I see that https://github.com/ansible/ansible-modules-core/pull/2737 is marked stable-2.0 (meaning that it's a bugfix that we'd like to see in the 2.0.x releases at some point) so I've cherry-picked this to the stable-2.0 branch as well (so it will appear in 2.0.1 or 2.0.2).

**Comment by robinro** [comment]
thanks for the quick merge @abadger

**Pull request merged**
