### PR TITLE
Allow AnsibleVaultEncryptedUnicode to pass through exec_jsonrpc (#48306)

### PR DESCRIPTION
**Pull request by Im0**
##### SUMMARY

Backport of https://github.com/ansible/ansible/pull/48306.   Fixing https://github.com/ansible/ansible/issues/47200

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

module_utils/connection.py

##### ADDITIONAL INFORMATION

```paste below
* Allow AnsibleVaultEncryptedUnicode to pass through exec_jsonrpc

* Add changelog

(cherry picked from commit f05979932b7a9187a6d60b051d01c94f918dd0da)

Conflicts:
	lib/ansible/module_utils/connection.py
```

### CODE REVIEW

**Comment by Im0** [comment]
Unrealted errors:
`
15:22 fatal: [testhost]: FAILED! => {
15:22     "changed": false,
15:22     "invocation": {
15:22         "module_args": {
15:22             "data": null,
15:22             "file": null,
15:22             "id": null,
15:22             "key": null,
15:22             "keyring": null,
15:22             "keyserver": null,
15:22             "state": "present",
15:22             "url": "https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc",
15:22             "validate_certs": true
15:22         }
15:22     },
15:22     "msg": "Failed to download key at https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc: Request failed: <urlopen error _ssl.c:830: The handshake operation timed out>"
15:22 }
`

**Comment by Im0** [comment]
Starting tests again to see if erlang repo is fixed.

**Comment by Im0** [comment]
Once again, failing on rabbitmq server deployment which appears to be repo related... completely irrelevant for this backport.

`
"stderr": "E: There were unauthenticated packages and -y was used without --allow-unauthenticated\n", 
`

**Comment by abadger** [comment]
Merged for the 2.7.10 release

**Pull request merged**
