### PR TITLE
Pacman module

### PR DESCRIPTION
**Pull request by Cightline**
Sorry for the late pull-request. It should be done, there are a few things I had to change (I was reading the man pages for pacman). I've added my contact info, ansible version (0.0.9), and modified the code to use "pacman -Q" which will only match the exact name instead of "pacman -Qs" which will match any package with that part of the name. Also its using "pacman -Qu" which will (based on return codes) tell me if the package is the latest or not. I've used "name" with the alias "pkg". State has "latest", "installed", "absent" which "latest" will trigger a "pacman -Syy" (package db update).

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks pgood, you should update the "name" and "state" parameter to pass required=True versus manually erroring out if they are not supplied.

Another thing you may want to explore is to make it work for lists of packages like yum and apt do, where the pkg name can be a comma seperated string of package names.  

This allows multiple package installations without multiple SSH calls, which makes things more efficient.

This looks like it does not update the package database when just doing an install, it may be useful to follow the pattern of the apt module for that with update-cache=yes|no rather than always just doing that for an update only?

**Comment by Cightline** [comment]
On Sat, Nov 24, 2012 at 4:10 PM, Michael DeHaan notifications@github.comwrote:

> Looks pgood, you should update the "name" and "state" parameter to pass
> required=True versus manually erroring out if they are not supplied.
> 
> Another thing you may want to explore is to make it work for lists of
> packages like yum and apt do, where the pkg name can be a comma seperated
> string of package names.
> 
> This allows multiple package installations without multiple SSH calls,
> which makes things more efficient.
> 
> This looks like it does not update the package database when just doing an
> install, it may be useful to follow the pattern of the apt module for that
> with update-cache=yes|no rather than always just doing that for an update
> only?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/1670#issuecomment-10678555.

Ok, I got "required=True" added in for "state" and "name". Also "pkgs =
p["name"].split(",")" enables it to accept multiple packages (its been in
the code, I think I got it from the apt module). I've tested the multiple
packages before too and thats why I have the "for package in packages:" in
"install_packages()" and "remove_packages()" so it will fail on the one
that caused the problem (if a problem happens).

I fixed up the top too, (where the descriptions are)

I've not added a update-cache because "latest" will run a pacman -Syy
(pretty much the same as "apt-get update") then install the package. I'm
not sure what exactly you mean in the last sentence. If the user specifies
"latest" the package database will be updated, if the user specifies
"installed" it will install w/o updating the package database, and "absent"
just removes it and nothing else.

Let me know what you think_, *I'll fix it up. *_**

**Comment by Cightline** [comment]
Also I'll add the update-cache, but would it be like "apt-get update;
apt-get ugprade" or is it just a "apt-get update". Because "name=firefox
state=latest" updates (apt-get update)

On Mon, Nov 26, 2012 at 3:15 AM, Forrest Shoemake <shoemakeforrest@gmail.com

> wrote:
>

**Comment by mpdehaan** [comment]
The apt logic basically allows you to select when you update the cache, seperate of what operations you perform.

For example

apt name=foo update-cache=yes 

will run the apt-get update first

apt name=foo

would use the old cache

and basically at no point does it decide to update the cache for you

If you were to say

apt name=firefox state=latest

What I'm suggesting, I _think_, is that it never does the -Syy unless you ask for it, so it lines up with apt.

It may not be true I am understanding it correctly

This would also mean if running it with mutliple packages in with_items, the -Syy would not be executed each time so it would be faster.

**Comment by mpdehaan** [comment]
Note seeing I am not an arch user, if this NEEDS to be different, just let me know.   I'm thinking it seems analogous to the logic in the apt module from my reading of the code.

Thanks!

**Comment by Cightline** [comment]
Is it ok if I do pacman name=firefox, state=installed update-cache=yes?, like you said that would just be one pacman -Syy (apt-get update), instead of it running over and over.

**Comment by mpdehaan** [comment]
yes, that's fine with me.

**Comment by mpdehaan** [comment]
Ok, so sorry for siting on this, can you see on the list if some other arch users want to help test?

**Comment by Cightline** [comment]
Sure, looks like I'm going to have time today so I should have something ready.

**Comment by Cightline** [comment]
Ok take a look, its pretty simple, I've put the version as "1.0" for "Eruption" (go ahead and change it if you need to if its incorrect or something).

**Comment by mpdehaan** [comment]
Thanks very much -- yeah if you don't mind, please post this to the list.  It would be better if some arch users can look at it vs. me.

**Comment by mpdehaan** [comment]
merged in, sorry for the delay.

You may want to post the mailing list to get some people using it :)

**Comment by mpdehaan** [comment]
Thanks!

**Comment by Cightline** [comment]
Sweet, no problem. I changed my github email and my phone did not not
notify me of this (I'm manually checking it now)

**Comment by senorsmile** [comment]
I am an arch user and the pacman module works fine.  The only two requests I would have would be 
-an option to do a sysupgrade (like pacman -Syyu)
-an option to see all available upgrades (pacman -Syyup)

Thanks for making the pacman module!

**Comment by Cightline** [comment]
No problem, I'll look into it when I get a chance.

**Pull request merged**
