### PR TITLE
Add environment to plays and roles.

### PR DESCRIPTION
**Pull request by jhriggs**
(See https://groups.google.com/d/msg/ansible-project/w3aqRqZ1hIw/SCMV3qwaE-wJ). Play-level environment is used for every task in the play unless task's environment is set. Task environment overrides play environment (i.e. they are not merged).

Future thoughts:
- Merge play + task environment rather than override or make it optional?
- Add environment settings to roles.

### CODE REVIEW

**Comment by jimi-c** [comment]
Yes, the environments should be merged rather than overriding, otherwise this could lead to some confusing situations. In task.py, I believe it should be:

<pre>
self.environment  = ds.get('environment', {}).update(play.environment)
</pre>

I think a straight update is the correct way to go (as opposed to a dictionary merge), as the task would be an override.

**Comment by jimi-c** [comment]
For safety, it'd probably be best NOT to do it as I show above (just in case someone specifies an environment that is not a dictionary, which would lead to a traceback).

**Comment by jhriggs** [comment]
My concern with merging/updating play + task is that the user then has no way to unset or not use the play's environment, if needed for a particular task. Or, do you think that is an exception case not really worth worrying about?

WRT "NOT to do it as I show above", are you just saying that some sanity checks need to be done on the values first to ensure that they are dictionaries?

**Comment by jhriggs** [comment]
See if this latest commit addresses your concerns/recommendations.

**Comment by jhriggs** [comment]
Any thoughts on this one, @jimi-c?

**Comment by bcoca** [comment]
sorry, an alternate implementation was already merged, plays already support environment in current devel

**Comment by jhriggs** [comment]
@bcoca: What about environment at the role level which is also part of this PR? Does that exist also, or should I open a new PR for role environment?

**Comment by bcoca** [comment]
@jhriggs i missed that, yes a new PR would be required

**Pull request closed without merging**
