### PR TITLE
Changes to make ansible work on OSX. 

### PR DESCRIPTION
**Pull request by cread**
Mostly to do with how we get md5sum of a file and the users home directory of a file and the users home directory.

This has been tested on: 

OSX Lion (10.7.3)
Ubuntu 10.04 LTS

### CODE REVIEW

**Comment by cocoy** [comment]
Hi Chris,

I think the issue   #229 might also affected ..On my test it's somewhere on library/setup, using expandvars instead of expanduser

diff --git a/library/setup b/library/setup
index 20f3d33..291d5f0 100755
--- a/library/setup
+++ b/library/setup
@@ -295,7 +295,7 @@ except:
        (k,v) = opt.split("=")
        setup_options[k]=v   

-ansible_file = setup_options.get('metadata', DEFAULT_ANSIBLE_SETUP)
+ansible_file = os.path.expandvars(setup_options.get('metadata', DEFAULT_ANSIBLE_SETUP))
 ansible_dir = os.path.dirname(ansible_file)

If you could add that much better. :)

**Comment by cread** [comment]
Correct, it is. 

If you have a look at the first change block in lib/ansible/runner.py you'll see I switch from using $HOME/ to ~/ and add a corresponding os.path.expanduser in library/setup

**Comment by mpdehaan** [comment]
The python one liner embedded in the SSH call is kind of heinous.  I would rather keep this out of the code.

It would be much better to modify the shell execution to execute md5sum or md5 as appropriate, and teach runner to know how to parse both formats of returns.  (make a parse_shell_md5 function in utils or something)

The md5sum function in utils is of course fine, as is including the md5sum functions in the modules.

See if you can fix the inline python and I'll take this.

Also see about fixing what cocoy mentioned, I assume that's recent devel branch damage from another patch.

**Comment by mpdehaan** [comment]
closing this, please resubmit w/ changes

thanks.

**Pull request closed without merging**
