### PR TITLE
kubevirt: more unit tests

### PR DESCRIPTION
**Pull request by mmazur**
##### SUMMARY
We've had a bunch of unit tests written, but we never submitted them upstream. Better late than never.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
kubevirt

### CODE REVIEW

**Comment by mmazur** [comment]
For the time being this contains all the commits from #57685. Once that gets merged, I'll rebase this on top of devel.

**Comment by mmazur** [comment]
This closes #52558.

**Comment by mmazur** [comment]
@pkliczewski @machacekondra – please review/+1 and let's try getting batch 1 in

**Review by machacekondra — APPROVED** [review]
+1

**Review by pkliczewski — APPROVED** [review]

**Comment by pkliczewski** [comment]
+1

**Comment by mmazur** [comment]
I did a rebase just in case. Anybody got any idea who do we get for a reviewer?

**Comment by mmazur** [comment]
@willthames nobody (outside the kubevirt modules maintainers) looked at these for the past 2 weeks and these need core approval. What can I do?

**Comment by willthames** [comment]
@mmazur - additional passing tests - what's not to like :)

**Pull request merged**
