### PR TITLE
Adding a recurse option to file (applies only to state=directory)

### PR DESCRIPTION
**Pull request by dstoflet**

### CODE REVIEW

**Comment by dhozac** [comment]
Don't use tabs. Use spaces.

**Comment by mpdehaan** [comment]
thanks for this and for tweaking formatting, in queue for testing!

this will be nice to have!

**Comment by mpdehaan** [comment]
BTW, random git tip -- you may want to look into topic branches in git and "git rebase -i", which will allow you to keep things in just one commit without the "Fix" commits.

(Basically keep the first commit with the description and squash the next three -- git rebase -i is pretty neat)

**Comment by mpdehaan** [comment]
all merged in, thanks very much, this is useful!

**Pull request closed without merging**
