### PR TITLE
add plugin for uncompress module

### PR DESCRIPTION
**Pull request by Jmainguy**

### CODE REVIEW

**Comment by Jmainguy** [comment]
This needs to get merged before https://github.com/ansible/ansible-modules-extras/pull/1301 in extras will work

**Comment by juju4** [comment]
Any progress on this? Thanks

**Comment by jctanner** [comment]
deprecated by http://docs.ansible.com/ansible/unarchive_module.html

**Comment by juju4** [comment]
not for gunzip https://github.com/ansible/ansible/issues/22774

**Comment by Jmainguy** [comment]
@juju4 I have reopened it and updated it to latest devel. I will do what I can to get this merged in. Thanks for following up.

**Comment by juju4** [comment]
Thanks a lot @Jmainguy !

**Pull request closed without merging**
