### PR TITLE
Kc update ip filter

### PR DESCRIPTION
**Pull request by itdependsnetworks**
##### SUMMARY

Adding to the ipaddr filters. 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ipaddr filter
##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### ADDITIONAL INFORMATION

This is not %100. I presume there will be changed in naming, so I didn't spend too much time on that. I do not know how to indicate which filters will be deprecated. 

```

```

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Pinging @privateip @gundalow @rcarrillocruz

**Comment by gundalow** [comment]
Currently no way of marking a filter as deprecated, though bcoca is working on something that will hopefully make it into 2.4.

**Comment by itdependsnetworks** [comment]
- Are you ok with names
- Do all of the filters make sense
- Are my tests complete enough
- Any glaring issues

**Review by privateip — APPROVED** [review]

**Comment by privateip** [comment]
LGTM

**Review by gundalow — APPROVED** [review]

**Pull request merged**
