### PR TITLE
Added the option to login all and logout all targets

### PR DESCRIPTION
**Pull request by kobihk**
##### SUMMARY
Currently, In case that we discover more than one target 
we can't use the login without specifying which target we want.
This patch implements the option to login all targets and logout from all targets.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

open-iscsi-module

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/khakimi/git/ansible-playbooks/ansible.cfg
  configured module search path = [u'/home/khakimi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:36) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by kobihk** [comment]
@tareqalayan could you please CR

**Review by tareqalayan — APPROVED** [review]

**Comment by kobihk** [comment]
Hi @jborean93 ,
Could you please let me know how we can get progress with this patch?

Thanks,
   Kobi

**Comment by tareqalayan** [comment]
@jborean93 can u please review this?

**Comment by jborean93** [comment]
I can’t because I don’t have any experience in this field so my reviews are next to worthless.

**Comment by kobihk** [comment]
@petr-balogh @jimi-c @abadger could you please CR and help us to get progress with this PR

**Review by petr-balogh — APPROVED** [review]
LGTM

**Pull request closed without merging**
