### PR TITLE
win_timezone: Add diff support, integration tests

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:

- Diff support
- Returns both previous_timezone and timezone
- Adds integration tests
- More examples
- Improved documentation

This fixes #25071 (not really fixes, but rather includes)

##### ISSUE TYPE

 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME

win_timezone

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by dagwieers** [comment]
@jborean93 I am sorry, I only noticed you had added integration tests too after I updated Etherpad. This was related an obvious bug in #24571 which triggered me to go an add those tests (and add diff-support since I was going to have to return before and after anyway).

**Comment by jborean93** [comment]
No worries whatever way to get tests added I don't mind :), I'll try and have a look next week as I'm away this weekend and don't have access to a computer.

**Comment by dagwieers** [comment]
@nitzmahone @jborean93 @jhawkesworth @trondhindenes Ready to be reviewed and merged.

**Comment by dagwieers** [comment]
Wake up call to to WWG :-) @nitzmahone @jborean93 @jhawkesworth @trondhindenes

**Comment by jborean93** [comment]
Sorry I thought I got to this before, looks good.

shipit

**Pull request merged**
