### PR TITLE
Lineinfile atomic

### PR DESCRIPTION
**Pull request by bcoca**
removes main race condition as it now writes to temp file instead of dest file, now no chance of programs reading file in the middle of write.

There is still a race in that the file might change between being read and updated but this should be minor and always consistent.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This pull request strangely appears to have some other commits in it.

Can you resubmit this?

**Comment by bcoca** [comment]
Will do, don't know wtf happens when I push around 2am, this is the 3rd
time I get it mixed.

Brian Coca

**Comment by mpdehaan** [comment]
do not allow github to get wet or feed it after midnight

**Comment by bcoca** [comment]
Resubmitted in #2860

**Pull request closed without merging**
