### PR TITLE
aci_domain: Manage phys, vmm, l2ext, l3ext and FC domain profiles

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
A new ACI module to manage physical, virtual, external bridged, external routed and fibre channel domain profiles.

This module still needs integration tests once it is formally review and accepted.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
aci_domain

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by dagwieers** [comment]
cc @rsmeyers @nilloBE Please test and review !

**Comment by gundalow** [comment]
I don't see anything obviously wrong. If people are happy then will need `EXAMPLES`, `RETURNS` and tests.

**Comment by rsmeyers** [comment]
Not sure if we should provide the option via this way to create a VMM domain, as it opens up a certain complexity. I would only add vmm here when we covered the full use-case.

**Comment by dagwieers** [comment]
Can you elaborate about the full use case ?

If we don't do it this way, it means having 5 `aci_*_domain` modules here, and another 5 for `aci_eap_to_*_domain` , another 5 for `aci_epg_to_*_domain` and 5 more `aci_*_domain_to_vlan_pool`. I prefer adding `domain_type` and `vm_provider` and leave it at one module each

**Comment by rsmeyers** [comment]
I agree that having it in 1 module is great, but I would currently remove the option to create a vmm domain our of this module, the reason is that when you create a VMM domain, we need to create 10 more objects for which we need to create more ansible modules..., which is currently not the plan, so it won't be feasible anyway to use this module to create a vmm domain...

**Comment by dagwieers** [comment]
Which 10 other objects ? Because for the microsoft vmm provider I think we're only missing one more module for our scenario. And aci_rest is there for the missing functionality.

**Comment by rsmeyers** [comment]
For VMware it's gonna be a lot of them I fear...., but yeah, as long as we have it planned it's ok,,,

**Comment by dagwieers** [comment]
Can we please stop the madness of ansibot not dealing properly with broken PRs ?

I took me 5 minutes to rebase my branch, and while I corrected it before ansibot visited the PR, ansibot was using the old information to send out a hundred notifications and mis-tagged the PR, which **it should not do**.

I shouldn't be forced to race against the time to fix my branch because the problem is not that it is broken, the problem is that ansibot goes into bezerk mode too quickly for no good reason.

bot_broken

**Comment by dagwieers** [comment]
Merging, integration tests and examples follow...

**Comment by nilloBE** [comment]
I do not know if there is enough to test at the moment. For physical and external domains this is fine. For VMM domains we need to be able to specify all required parameters. This is dependent on the domain type (vmware, redhat, microsoft). I believe it would be great to add to the module.

For VMware:
- domain_name
- vswitch_type: [vds, avs, ave]
- access_mode: [ro, rw]
- vcenter_name
- vcenter_ip: [ip or FQDN]
- vds_version: [5.1, 5.5, 6.0, 6.5, default]
- stats_collection: [disabled, enabled]
- datacenter_name
- mgmt_epg
- credential_name
- port_channel_mode: [on, lacp-active,lacp-passive,mac-pining,mac-pinning-plus]
- vswitch_policy: [cdp, lldp, none]

For RHV:
- domain_name
- rhvm_name
- rhvm_ip:  [ip or FQDN]
- datacenter_name
- mgmt_epg
- credential_name

For Microsoft:
- domain_name
- scvmm_name
- scvmm_ip: [ip or FQDN]
- scvmm_cloud_name
- port_channel_mode: [on, lacp-active,lacp-passive,mac-pining,mac-pinning-plus]

let me know if you need more info or disagree :)

**Comment by rsmeyers** [comment]
Due to the amount of modules we had to make, we limited this module and didn’t include VMM.
In a next phase for sure we need to add this.
Let’s docment the limitation of this module currently.

**Comment by dagwieers** [comment]
So, it's not easy to add conditional parameters, another solution may be needed.

PS I would like to see a new open issue rather than comments in a closed PR which is not tracked.

**Comment by nilloBE** [comment]
Fair enough. I will add a new issue to track this. We can then decide whether we want to keep it as a single module or not.

**Pull request merged**
