### PR TITLE
Add some docs/examples

### LINKED ISSUE #841: ansible-pull wants a manpage
```
$ ansible-pull --help
Usage: ansible-pull [options]

Options:
  -h, --help            show this help message and exit
  -d DEST, --directory=DEST
                        Directory to checkout git repository
  -U URL, --url=URL     URL of git repository
  -C CHECKOUT, --checkout=CHECKOUT
                        Branch/Tag/Commit to checkout.  Defaults to HEAD.
```

Noticed this while checking out the man pages.

### PR DESCRIPTION
**Pull request by timlnx**
Add a basic ansible-pull man page.

Add the example playbooks/scripts to the RPM package.

Closes #841

### CODE REVIEW

**Comment by mpdehaan** [comment]
ansible-pull being in the package and having a manpage is good, all of examples shouldn't be in the RPM though.

Can you update this?

**Comment by timlnx** [comment]
I respectfully disagree with not including examples in the package. I know personally that being able to just `less /usr/share/doc/$program/exmaples....` something has saved me a boat load of time in the past.

I will update this pull request with your requested changes if that is what you wish.

**Comment by mpdehaan** [comment]
My issue is not so much the example yaml files, but the scripts directory.  

I may wish to include things in there that are not complete and I don't wish to support.

**Comment by timlnx** [comment]
How do you feel about just dumping the shipping of scripts instead?

**Comment by mpdehaan** [comment]
sounds great

**Comment by timlnx** [comment]
Updated.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
