### PR TITLE
Code review: MySQL module

### PR DESCRIPTION
**Pull request by marktheunissen**
This is not finished, I'm just creating the pull request for the purposes of code review.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!  I am closing this ticket because we don't want to apply yet, we can still review it using this interface.

**Comment by mpdehaan** [comment]
+state     = params.get("state", None)

Looks like state can default to "present" here, which also means the check to see if it is absent or present or None can just be absent or present

**Comment by mpdehaan** [comment]
if it allows creating and removing databases, things might get weird with state=present/absent applying to both users and databases.   

This seems like it might be reason to split things into a mysql_user module, and a mysql_database module, and whatever else you might find appropriate.

I do not think we have to exactly mirror what other people do here, but see how this particular module from Puppet namespaces things:

https://github.com/camptocamp/puppet-mysql and also https://github.com/DavidS/puppet-mysql

There may also be similar examples from chef.

In general, each ansible "module" should probably deal with just one resource type, and I am ok with having more than one if they all start with "mysql_" and so on

Better than having it take a "mode=user" and "mode=database" and so forth, which may be confusing

**Comment by marktheunissen** [comment]
1. I was thinking of requiring either a db=database or user=username parameter, but not both. Is it preferable to split the module instead of just having exclusive OR for these two main operations?
2. I'm connecting to the DB using the MySQLdb library. Another option would be to do it the same way the Puppet module does, which is to execute the 'mysql' command line tool. 

These approaches have pros/cons, the Puppet way requires the mysql username/password combination to be stored on the remote machine, for example in a file ~/.my.cnf. However it also means that you don't have to specify a login user/pass in the Ansible playbook. 

That can be handy in the case that you're doing the same task on multiple MySQL database servers, and each one has a different user/password combination. Maybe there's another way around that?

Anyway I'd be happy to switch it to use the mysql command line option if you think that'd be better

**Comment by mpdehaan** [comment]
Replies inline

On Jul 12, 2012, at 9:51 AM, Mark Theunissenreply@reply.github.com wrote:

> 1. I was thinking of requiring either a db=<database> or user=<user> parameter, but not both. Is it preferable to split the module instead of just having exclusive OR for these two main operations?
> 
> Split
> 1. I'm connecting to the DB using the MySQLdb library. Another option would be to do it the same way the Puppet module does, which is to execute the 'mysql' command line tool. 

Library seems smart, did not mean to say be implemented like them, just look at how they are broken up..

**Pull request closed without merging**
