### PR TITLE
Add a note to say that *BSD and Solaris are also supported

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

hostname

### CODE REVIEW

**Comment by mscherer** [comment]
Migrated from https://github.com/ansible/ansible-modules-core/pull/5324

**Comment by jctanner** [comment]
@mscherer "Also works on"

**Comment by xen0l** [comment]
This also works on illumos-based operating systems (e.g. OpenIndiana or OmniOS). Mentioning that would be good as well. Otherwise, +1.

**Comment by bcoca** [comment]
most modules are supposed to work on POSIX systems unless otherwise noted

**Comment by mscherer** [comment]
This one wasn't saying anything about NetBSD support, and yet wasn't supported until 3 days ago (when another related PR was merged). HP-UX and AIX are posix and not supported. 

So should we rather list excluded systems ?

**Comment by bcoca** [comment]
yep, the basic assumption should be it works on any system with compliant python

**Comment by bcoca** [comment]
closed via f86e6a21522ee8469390dc7fc220f72f60972a7c

**Pull request closed without merging**
