### PR TITLE
docker_swarm: add diff support

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adds `--diff` support to docker_swarm.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
docker_swarm

### CODE REVIEW

**Comment by felixfontein** [comment]
I think this should also be merged ASAP (even before #52886), so it's easier to find out what went wrong. In case of the failed tests in #52886, it would have told us right away what was wrong.

shipit

**Comment by WojciechowskiPiotr** [comment]
shipit

**Comment by gundalow** [comment]
@felixfontein and @WojciechowskiPiotr Thank you!

**Comment by felixfontein** [comment]
@WojciechowskiPiotr thanks for reviewing!
@gundalow thanks for merging!

**Pull request merged**
