### PR TITLE
Change logic for FreeIPA inventory plugin to obtain all hosts.

### PR DESCRIPTION
**Pull request by erinn**
##### SUMMARY
The original version of this script only returned hosts from the IPA server that were members of a group. This version returns all hosts, as well as host groups and their members. It also returns the SSH fingerprint variable for each host. 

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
plugins/inventory/freeipa.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by erinn** [comment]
Not happening folks, I don't even have an IPA environment anymore. You can take this and rebase yourself if necessary or remove it.

**Comment by samdoran** [comment]
@Nosmoht @Akasurde Can you please look at this?

**Comment by Akasurde** [comment]
@erinn Could you please rebase this, so that we can take a look into this ?

**Comment by erinn** [comment]
No, I no longer have an IPA server. I think this was opened 2+ years ago.
________________________________

**Pull request closed without merging**
