### PR TITLE
WIP: aci_config_rollback: Fix test to use dict output

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
The output of the modules is translated to JSON, so the test should reflect that.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
aci_config_rollback

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by acozine** [comment]
@dagwieers could you rebase this one (or close if it's no longer relevant)?

**Comment by dagwieers** [comment]
It is not a complete fix. I'd like to keep it open, but let's make it WIP.

**Comment by acozine** [comment]
I tried rebasing this, but got muddled. Is this PR still needed? Or has it been superseded by more recent work (see #33016 and #43847 and #43441 etc.)?

**Comment by acozine** [comment]
@dagwieers I missed your comment as I was writing mine.

**Pull request closed without merging**
