### PR TITLE
update ce_bgp_af to fix bugs

### PR DESCRIPTION
**Pull request by yanzhangi**
##### SUMMARY

Modify XML in the module
Some grammatical errors in modules
Some display updates lines are inaccurate

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/cloudengine/ce_bgp_af.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by hwDCN** [comment]
shipit

**Comment by xuxiaowei0512** [comment]
bot_status

**Comment by yanzhangi** [comment]
read_for_review

**Comment by hwDCN** [comment]
shipit

**Comment by xuxiaowei0512** [comment]
bot_status

**Comment by xuxiaowei0512** [comment]
shipit

**Comment by xuxiaowei0512** [comment]
bot_status

**Review by yuandongx — APPROVED** [review]

**Comment by yanzhangi** [comment]
bot_status

**Pull request merged**
