### PR TITLE
update vsphere_guest.py to include snapshot operations

### PR DESCRIPTION
**Pull request by Abdul-Anshad-A**
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vsphere_guest

##### ANSIBLE VERSION
ansible 2.3.0 (devel)

##### SUMMARY
The vsphere_guest module lacks the ability to handle snapshot operations of vmware guests. This is an initial effort for the feature request(https://github.com/ansible/ansible-modules-core/issues/4942).

EXAMPLES:
### List all snapshots

```
vsphere_guest:
    vcenter_hostname: <hostname>
    username: <username>
    password: <password>
    validate_certs: False
    guest: <vm_name>
    snapshot_op:
        op_type: list_all
```
### Remove a snapshot

```
 snapshot_op:
     op_type: remove
     name: <snapshot_name_to_delete>
```
### Create a snapshot

```
 snapshot_op:
     op_type: create
     name: <snapshot_name_to_create>
     description: <snapshot_description>
```
### Revert snapshot

```
 snapshot_op:
     op_type: revert
     name: <snapshot_name_to_revert>
```
### List current snapshot of a VM

```
 snapshot_op:
     op_type: list_current
```

### CODE REVIEW

**Comment by Abdul-Anshad-A** [comment]
Migrated from https://github.com/ansible/ansible-modules-core/pull/5390

**Comment by ikkaro** [comment]
Operations working: create, remove, revert.
During the operations of list_all and list_current, you have to pass to ansible-playbook the -v option to see the returned information 

`- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create snapshot
    vsphere_guest:
      vcenter_hostname: XXXXX
      username: user
      password: pass
      validate_certs: False
      guest: SERVER
      snapshot_op:
        op_type: list_current
`

Output running ansible playbook:

`PLAY [localhost] *********************************************************************************************************************************
TASK [Create snapshot] *********************************************************************************************************************************ok: [localhost]
PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0`

Output runing ansible-playbook -v
`PLAY [localhost] *********************************************************************************************************************************
TASK [Create snapshot] *********************************************************************************************************************************
ok: [localhost] => {"changed": false, "msg": "Guest SERVER - snapshot1"}
PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0  `

**Comment by Abdul-Anshad-A** [comment]
@ikkaro Thank you for testing this out !

**Comment by nerzhul** [comment]
we now have vmware_guest_snapshot.py module in devel to manage snapshots with the official vmware API. I think this should be closed

@jctanner @dav1x ?

**Comment by jctanner** [comment]
I'm very sorry about the open/close toggling. This PR exposed a bug in ansibot that i'm trying to fix right now.

**Comment by jctanner** [comment]
Okay, I think the bot bug is resolved. We have snapshotting in vmware_guest_snapshot with pyvmomi, so we should start treating vsphere_guest as a deprecated module. We will need to do a wider assessment of vmware_* versus vsphere_* to officially mark it as deprecated, but this one can be closed for now.

wontfix

**Pull request closed without merging**
