### PR TITLE
fireball DOCUMENTATION

### PR DESCRIPTION
**Pull request by jpmens**
I thought I'd help along with the little I've learned ...

The example is _very_ brittle (white-space-wise) but looks ok to me in .rst and .man

### CODE REVIEW

**Comment by jpmens** [comment]
Still needs at very least, info on passwords (i.e. keys): how to generate, etc.

**Comment by mpdehaan** [comment]
That's automagic, you won't have to think about it and they periodically will regenerate.

hosts: devservers should be 'hosts: all', or it all should be devservers -- needs to match one way or the other.

**Comment by jpmens** [comment]
Changed

**Comment by mpdehaan** [comment]
Merged, thanks, fireball's getting it's own documentation in the playbooks or connections section (and both) before release, so this will complete it nicely.

**Pull request merged**
