### PR TITLE
reword "except Error as e:" into "except Error, e:" to be compatible with Python 2.5

### PR DESCRIPTION
**Pull request by timurb**
Fix for #5852

I've changed all occurences in a code base for that.

Although we probably need to discuss first if we need this everywhere or only in parts of the code run on remote server (i.e. `library/*` etc).

### CODE REVIEW

**Comment by mpdehaan** [comment]
Probably could have just been library, but agree this shouldn't hurt.

Thank you!

**Comment by timurb** [comment]
@mpdehaan 
Which of the Ansible parts run on managed hosts? Library only or callbacks/runners/plugins etc as well?

I could modify the patch to use Python 2.5 syntax for that parts only if you feel that is the correct way.

**Comment by tongpu** [comment]
This change makes running
`local_action: command ...`
fail on a system where /usr/bin/python defaults to Python 3.

Is there another possibility to ensure compatibility with python 2.4 and 2.5, because I believe this is going to return as an even bigger problem as more distributions are going to default to Python 3.

**Comment by bcoca** [comment]
stuff in Library runs on managed hosts, everything else runs on master.
Also, most of the cloud plugins tend to run on master (hosts: localhost).

**Comment by bcoca** [comment]
@Lukas, I don't know of any way to write exceptions that is  compatible
2.4-3.3, if you do that would be the way to go.

**Comment by sivel** [comment]
The way you handle it for python 2.4-3.4, or at least the way that I have historically handled it is something like:

```
except Exception:
    e = sys.exc_info()[1]
    # Do something with e
```

**Comment by bcoca** [comment]
e magically appears when not specified?

**Comment by bcoca** [comment]
nvmd

On Mon, Feb 3, 2014 at 10:45 AM, Brian Coca briancoca@gmail.com wrote:

> e magically appears when not specified?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
So Ansible doesn't support Python 3.  When the day comes when there aren't a lot of enterprise users asking for management of EL 5 hosts, we are happy to change that, but right now all of those platforms still have Python 2 interpreters.

I'm not comfortable with the e = sys.exc_info() idiom really, I think we should use the features in the language we support.

Again, once EL 5 is no longer something we have to deal with, I have no problem moving to something that python 3 likes, but right now, there just aren't many python 3 only platforms we have to deal with, and in those cases, installing python 2 is easy.

They really should be viewed as different languages.

Note: things outside the library directory require python 2.6 or later, and have more freedom.  library/ Modules (not action plugins, just the library modules in core) are the part that have to support 2.4.

**Comment by tongpu** [comment]
I fully understand that Ansible doesn't support Python 3, but I didn't have these issues before.
I need to look into the packaging of Ansible on Arch Linux, because I know that it worked with 1.4.3 and I'm somehow led to believe that my problem is related to packaging.

**Comment by jimi-c** [comment]
The above has been merged in (even though github is not reflecting it properly). Thanks!

@tongpu issues related to packaging would be another issue. If you can recreate the problem please open another issue here on github so we can track it. Thanks!

**Pull request closed without merging**
