### PR TITLE
added --pass-limit-to-inventory as discussed in https://groups.google.com/forum/#!topic/ansible-devel/ZGwvE7RgWTc

### PR DESCRIPTION
**Pull request by bigzaqui**
##### SUMMARY
the idea is simple, if  --pass-limit-to-inventory is used when running ansible-playbook, then when the inventory is called, it will have the arguments --list --limit BLABLA 

so you can use it to narrow the scope of the inventory

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/cli/__init__.py
lib/ansible/cli/playbook.py
lib/ansible/inventory/__init__.py
lib/ansible/inventory/dir.py
lib/ansible/inventory/script.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by gundalow** [comment]
@bigzaqui We were discussion this PR in networktocode channel today. It seems like there is some interest in this still. Would you be able to rebase it please.

**Comment by ogenstad** [comment]
+1

**Comment by abadger** [comment]
From @bcoca on IRC:

> not good idea, several issues, not smallest one is that it disallows playbooks to access data outside limit, which most need
> having a caching inventory is normally a better solution

**Comment by dbarrosop** [comment]
> not good idea, several issues, not smallest one is that it disallows playbooks to access data outside limit, which most need

That might be assuming too much. How do you know how his or my backend work? That is extremely useful for people running their own inventories as they can use that limit to determine the data to fetch from their backend. If you want to ignore the feature for people using the `hosts` file I think it's fine but custom inventories should have that information. People with their inventory scripts can also choose to ignore that limit if they don't like it.

> having a caching inventory is normally a better solution

If your operations are data driven a cache is useless.

**Comment by ogenstad** [comment]
Given that this would only apply with the optional `--pass-limit-to-inventory` parameter I don't really understand the objection about accessing data outside of the limit.

What are the other issues not mentioned?

**Comment by calfonso** [comment]
Hi!

We believe recent commits  #23001 should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request closed without merging**
