### PR TITLE
Add release parameter for redhat_subscription

### PR DESCRIPTION
**Pull request by jasonwalsh**
##### SUMMARY

Adds a `release` parameter to the `redhat_subscription` module. This change is useful for pinning a specific release of Red Hat Subscription Manager.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

`redhat_subscription`

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### ADDITIONAL INFORMATION

```paste below
Translates to:

$ subscription-manager register --release=<RELEASE>
```

### CODE REVIEW

**Comment by maxamillion** [comment]
LGTM

cc @alikins @barnabycourt @kahowell

**Comment by jasonwalsh** [comment]
Any update on this?

**Comment by mkrizek** [comment]
cc @samdoran

**Review by mkrizek — APPROVED** [review]

**Review by samdoran — APPROVED** [review]

**Comment by jamescassell** [comment]
Does this provide more or different functionality than #43211 ? (Though I guess that one was merged after this one.)  Seems like we've added two ways to do the same thing in 2.8.

**Comment by seandst** [comment]
subscription-manager itself provides two ways to do the same thing. This works with the `subscription-manager register` subcommand, while the rhsm_release module allows for changing the release on an already-registered system. It probably makes sense to have both.

**Pull request merged**
