### PR TITLE
Add new windows module: win_hosts

### PR DESCRIPTION
**Pull request by mhunsber**
##### SUMMARY

**Added module:** win_hosts
**Rationale:** It is common to want to manipulate `%windir%\system32\drivers\etc\hosts` in a windows environment. It would be possible to edit this file with `win_copy` or `win_template`, but you might want to add or remove a single entry, and not have to define the entire file content.
**Design decision:** I made `state=present` always replace the ip address of a host in-place if the current ip does not match the provided one. This is because when resolving dns names, the windows host will pick the first match

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

win_hosts
##### ANSIBLE VERSION

```paste below
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### EXAMPLE USAGE

**`%windir%\system32\drivers\etc\hosts`**
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
127.0.0.1 localhost # you would not do this
```
**`playbook.yml`**
```
---
- name: test out win_hosts
  hosts: windows_hosts
  tasks:
    - name: Ensure localhost is ipv6 # you also would not do this
      win_hosts:
        state: present
        host_name: localhost
        ip_address: '::1'
```

`ansible-playbook playbook.yml --diff`
```
PLAY [test out win_hosts] *****************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: [192.168.101.36]

TASK [Ensure localhost is ipv6] ***********************************************************************************************

-[127.0.0.1 localhost # you would not do this]
+[::1 localhost]
changed: [192.168.101.36]

PLAY RECAP ********************************************************************************************************************
192.168.101.36             : ok=2    changed=1    unreachable=0    failed=0

```

### CODE REVIEW

**Comment by jborean93** [comment]
@mhunsber thanks for your work here, I'm just wondering what do you think the advantages of having this  instead of just using the [win_lineinfile](https://docs.ansible.com/ansible/latest/modules/win_lineinfile_module.html) module? I probably want to bring this to the windows working group and get the wider communities feelings on it. Please feel free to join at the next meeting to talk about this a bit more, otherwise post your comments here. Details for this are https://github.com/ansible/community/tree/master/group-windows.

**Comment by dagwieers** [comment]
The hosts file can consist of a single IP address and multiple names. So in my opinion you have 3 cases:
- **state: present**
  - ip and host provided  -- *Add a new entry, or add host to existing entry*
- **state: absent**
  - ip and host provided -- *Remove host from existing entry, or remove host altogether if only this entry*
  - ip provided only -- *Remove entry and all aliases*

PS I think a separate module has merit, as it's not necessarily managing only lines.

**Comment by mhunsber** [comment]
> What do you think the advantages of having this instead of just using win_lineinfile?

Wow, somehow I missed that win_lineinfile existed, thanks.

> The hosts file can consist of a single IP address and multiple names

Thanks for the feedback. I did not know you could have one ip with multiple names following.

Also, [netlib dns](https://www-archive.mozilla.org/docs/netlib/dns.html) supports resolving multiple ip addresses to a single host name. I tested it by having the following lines in hosts:
```
192.168.1.1 foo
192.168.1.2 foo
```
and used `Resolve-DnsName "foo"` in PowerShell which returned
```
Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
foo                                            A      0     Answer     192.168.1.1
foo                                            A      0     Answer     192.168.1.2
```
Since that means hostnames/ipaddresses are many-to-many, we may have 4 cases:

- **state: present**
  - ip and host provided -- *Add a new entry, or add host to existing entry*
- **state: absent**
  - ip and host provided -- *Remove host from existing entry, or remove host altogether if only this entry*
  - ip provided only -- *Remove entry and all aliases*
  - host provided only -- *Remove alias from all entries, removing entries if  it's the only alias*

Adding entries also causes a problem where the user may want to ensure that the alias is mapped to the correct ip, and not simply add another entry. for example, in my hosts file above, I may want to ensure that the *foo* alias is only mapped to *192.168.1.3*
Would we need something like `groups_action` from [win_user](https://docs.ansible.com/ansible/latest/modules/win_user_module.html#win-user-module)? such as an `ip_action` that can be `add` `replace` or `remove` ? That would also suggest that the module could take `ip_address` as an array.

I'm interested in what thoughts are on this.

**Comment by mhunsber** [comment]
Sorry for all of the commits, I had some trouble getting git to fix the line endings.

Here's what I changed:
### multiple aliases
from @dagwieers suggestion, I made the module recognize multiple aliases for a single ip such as:
```
192.168.1.1 alias1 alias2 alias3
````
#### state=present
a task that looks for the ip 192.168.1.1 with **alias4** present would yield 
```
192.168.1.1 alias1 alias2 alias3 alias4
```
unless a different entry already has alias4 mapped to 192.168.1.1, then it does nothing. For example, if the host file looked like this, no changes would be made:
```
192.168.1.1 alias1 alias2 alias3
192.168.1.2 foo
192.168.1.1 alias4
```
#### state=absent
likewise, a task the looks for the ip 192.168.1.1 with **alias2** *absent* would yield 
```
192.168.1.1 alias1 alias3
```
if **alias2** was the only alias for the entry, the entry would be removed

### ip_action
consider the following hosts lines:
```
192.168.1.1 mysite.local
192.168.1.2 mysite.local
```
#### Option 1: add
Since it seems possible to have multiple ips with the same alias (as I showed with `Resolve-DnsName`), I added an `ip_action` argument with an `add` option, which will add the alias to the ip even if the alias exists under a different ip. So if I run a task configured as
```
win_hosts:
  state: present
  ip_address: 192.168.1.3
  host_name: mysite.local
  ip_action:add
```
the new host file will look like this:
```
192.168.1.1 mysite.local
192.168.1.2 mysite.local
192.168.1.3 mysite.local
```
#### Option 2: replace (default)
For most cases, though, an application will grab the first ip it can resolve. For example, if you run `ping mysite.local` with the above host entries, windows will always use `192.168.1.1`. To aid in that, the default option, `replace` will remove the alias from other ips. so if instead I run the same task, except configured with `ip_action: replace` the host file would look like this:
```
192.168.1.1 mysite.local
```
### state=absent 
#### only ip_address provided
as suggested, this will remove all entries with the provided `ip_address`
#### only host_name provided
this will remove the provided `host_name` from any entries, and remove the entry altogether if `host_name` was the only alias.
### Other
- accounts for any whitespace between ip and alias since you could have `                  192.168.1.1                foo alias          foo.bar` as a valid host entry
- leaves end of line comments alone since you could have ` 192.168.1.1 alias1 # alias2 alias3` as well

**Comment by jborean93** [comment]
@mhunsber we spoke about this at the recently Windows Working Group, the consensus was that we should have this module but to make sure we have very thorough tests to cover some of the edge cases you described here.

For the UI maybe we should have the following options;

* `state` - either present or absent which controls whether the line is in the file or not
* `ip_address` - the IP address to manage
* `hosts`? - a list of hosts for `ip_address`, action will control this behaviour
* `action` - add/remove/set
    * `add` - will ensure the value(s) in `hosts` are added to entry for `ip_address`
    * `remove` - will ensure the value(s) in `hosts` are removed from the entry for `ip_address`
    * `set` (default) - will ensure only the value(s) in `hosts` are set for `ip_address`

Let me know your thoughts on this.

**Comment by mhunsber** [comment]
@jborean93 I really like the UI suggestions, especially the idea of making `hosts` a list.

> `hosts`? - a list of hosts for `ip_address`, action will control this behavior

I think "`hosts`" is confusing because sometimes IPs are also considered "hosts," plus it clashes with the name of the module and file that is being edited. Looking at the [wikipedia article](https://en.wikipedia.org/wiki/Hosts_(file)#File_content) for the hosts file, it seems to consistently refer to the human-friendly names as "host names". If we're unsure about the name for this option I suggest either `hostnames`, `host_names`, or just `names`.

> `remove` - will ensure the value(s) in `hosts` are removed from the entry for `ip_address`

I like the choices for action, but want some clarification on its use. I am confused about the desired behaviors of and differences between *action=remove* and *state=absent*. It makes sense to me that `action` would only control behavior when `state` is *present*. Let me know if I am wrong, but I understand that to mean there could be multiple ways to say entries should be absent, but two of them seem redundant:
* **state**=present and **action**=remove
  * Remove the values in `hosts` from the entry for `ip_address` if they exist, removing if no remaining hosts
* **state**=absent (action is irrelevant?)
  * *if only `hosts` provided*: remove `hosts` from all lines, removing if no remaining hosts.
  * *if only `ip_address` provided*: remove the line entirely
  * *if both `ip_address` and `hosts` provided*: this seems like the same thing as using state=present and action=remove

It would be helpful if we decided which options are required in what circumstances. For sure, `ip_address` and `hosts` should be required when the state is *present,* but neither of them would necessarily be required if the state is *absent* For example, if none of `hosts`, `ip_address`, or `action` are required when the state is *absent*, an interesting use could be to remove **all** hosts entries with
```
win_hosts:
  state: absent
```
which could actually be very useful, if you wanted to ensure the target is getting all of its dns resolutions from a dns server.

**Comment by dagwieers** [comment]
@mhunsber The Unix documentation also considers the first named entry the "canonical_hostname" and the others "aliases", but I don't think we have to consider this important (may need to test if these are represented by the resolver as A or CNAME records).

Also If you got the "host names" way, I would prefer you use **hostnames** over **host_names**, since we tend to use **hostname** for a lot of other modules as well. And almost never use **host_name** (the ones that do this really are doing it wrong, we should clean that up).

**Comment by mhunsber** [comment]
@dagwieers I'll work with **host_names** for now then, and if others think it should be changed to **aliases** or something else, it will be an easy switch.

> we may need to test if these are represented by the resolver as A or CNAME records

fwiw you're right about the "canonical hostname", it looks like the first named entry is an A record, and the following are CNAME records, which point to the canonical hostname. But I agree, I don't think we need to consider it important:
```
10.1.2.3 first second third
```
```
PS C:\Windows\system32> Resolve-DnsName first

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
first                                          A      0     Answer     10.1.2.3


PS C:\Windows\system32> Resolve-DnsName second

Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
second                         CNAME  0     Answer     first

Name       : first
QueryType  : A
TTL        : 0
Section    : Answer
IP4Address : 10.1.2.3



PS C:\Windows\system32> Resolve-DnsName third

Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
third                          CNAME  0     Answer     first

Name       : first
QueryType  : A
TTL        : 0
Section    : Answer
IP4Address : 10.1.2.3
```

**Comment by dagwieers** [comment]
@mhunsber Ouch, if there's really a difference between first and subsequent names, we probably need to take that into account. Since for some services/software this could make a difference in behavior.

I wonder if there's a similar user interface used in another module for managing zone files that we could reuse ?

**Comment by mhunsber** [comment]
@dagwieers if not, we could make the UI
* `state` - either present or absent which controls whether the line is in the file or not
* `ip_address` - the IP address to manage
* `canonical_name` - a canonical name for the IP address (type A record)
* `aliases`? - a list of cname records for `canonical_name`, action will control this behaviour
* `action` - add/remove/set
  * `add` - will ensure the value(s) in `aliases` are added to entry for `canonical_name`
  * `remove` - will ensure the value(s) in `aliases` are removed from the entry for `canonical_name`
  * `set` (default) - will ensure only the value(s) in `aliases` are set for `canonical_name`

This would also resolve the confusion I brought up before about the difference between `action=remove` and `state=absent`, since action would only matter for the *additional* names in the entry. For example,
```
win_hosts:
  state: absent
  ip_address: 127.0.0.1
  canonical_name: localhost
```
would remove the entry (including all aliases) for `127.0.0.1 localhost`, while
```
win_hosts:
  state: present
  ip_address: 127.0.0.1
  canonical_name: localhost
  action: remove
  aliases:
    - loopback
```
would just remove the `loopback` alias from the `127.0.0.1 localhost` entry

let me know your thoughts on this.

**Comment by dagwieers** [comment]
During the [next Windows WG meeting](https://github.com/ansible/community/issues/420) on 2019-01-29 we will review and decide on the inclusion of this module in Ansible v2.8. Your presence in the meeting could be helpful.

*If there's anything you wanted to improve/fix, please do so before the meeting.*

**Comment by mhunsber** [comment]
Earlier I had mentioned that if the hosts file has a name mapped to multiple ip addresses, that `Resolve-DnsName` would show results for both. That is true, but I couldn't find any applications that were able to use the hosts file in that way. `ping` would always grab the first IP in the hosts file that it could find. The only exception was if one IP was ipv4 and the other ipv6, then you could have both entries. The current commit supports a name mapped to 1 ipv4 and 1 ipv6 address only. Originally I had an option for `ip_action` that would control whether or not multiple IPs would be allowed per hostname, but with the addition of `action` as a way to control the behavior for aliases, I had removed the `ip_action` option. If asked to map a name that already exists to a new ip address of the same class, it removes the old entry and adds a new one with the corrected ip, which seems more like the behavior you would expect from the module. If `action` is `remove` or `add`, the module will also add the aliases from the old entry back to the new entry.

Example
```
192.168.100.1 alice bob carol # previous entry
```
```
win_hosts:
  canonical_name: alice
  state: present
  ip_address: 192.168.100.2
  aliases:
    - dave
  action: add
```
results in
```
# previous entry
192.168.100.2 alice bob carol dave # new entry
```

The other interesting behavior about the hosts file is when both an ipv6 and ipv4 address are listed. For a name to work for both ipv4 and ipv6, it has to be present for both ip entries, even if it is a cname record for another name already mapped to the other ip class. For example, here `myself` will only resolve to the ipv4 address `127.0.0.1`
```
127.0.0.1 localhost myself
::1 localhost
```
but if changed to be in both entries, then the alias resolves to either ipv4 or ipv6
```
127.0.0.1 localhost myself
::1 localhost myself
```

I wasn't able to think of a good behavior for how to handle this, so I sort of threw my hands up and decided that if the entry is a different type than the one requested, the module will skip over it.

**Comment by jborean93** [comment]
@mhunsber thanks for this, I've slightly tweaked the tests to properly backup the hosts file but everything else looks great.

**Pull request merged**
