### PR TITLE
support for launching multiple instances in ec2 module

### PR DESCRIPTION
**Pull request by lwade**
uncomment/add count parameter and provide the capability to launch more than one instance at a time in the ec2 module.

### CODE REVIEW

**Comment by lwade** [comment]
I added myself to the authors line but whilst I've made some changes much of the work is based off skvidal's, so I can't claim all the credit.  Do with it as you wish :)

**Comment by lwade** [comment]
Note that I've increased the wait slightly.  This is really to cater (in a hackish way) for the fact that with more instance launches comes the potential for more delay in the boot process.  In Eucalyptus its possible to see that instances will enter running (and thus trigger the wait) but may not have actually booted if we're setting up many on the same NC (intensive disk I/O means slower VM boot).  Increasing the wait to 5s might just give us a little bit more time to avoid outright failure and disappointment.

**Comment by dhozac** [comment]
Shouldn't this also set min_count to count?

The comment should be indented like the rest of the code.

**Comment by lwade** [comment]
Correct, thanks dhozac.  Changes made, we'll make them the same to keep them consistent.  This does have implications in launching, potentially.  It could mean the launch fails if capacity does not exist but then this is probably no bad thing, since the user would like to know why and with verbose output should be able to tell. 

For those interested:  min_count and max_count set the reservation size.  Boto folks would phrase it as "Run me $max_count instances but if there isn't space $min_count is the minimum I'd like to launch".

**Comment by lwade** [comment]
Tested with latest ec2 module changes, works.

**Comment by lwade** [comment]
Updated indentation and comment per review.

**Comment by mpdehaan** [comment]
manually merged, pushing shortly, thanks!

**Pull request closed without merging**
