### PR TITLE
ipa_dnsrecord: Add state append

### LINKED ISSUE #33193: Add possibility to set up several ips for hostname in module ipa_dnsrecord
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ipa_dnsrecord

##### ANSIBLE VERSION

```
v.2.4.1
```

##### OS / ENVIRONMENT

centOS 7
##### SUMMARY

Please, add possibility to set up several ip-addresses (record_value) for one hostname (record_name) in module ipa_dnsrecord. For now if I will define several record_values - it will replace old value with new one. It is logical and sometimes really needed to have a possibility to define two or more ip-addresses for one hostname and it is possible to do so in free_ipa web-interface.
Thanks in advance!
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

State 'append' allow user to append additional details into an
existing dnsrecord.

Fixes: #33193

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE 
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/33193_ipa_dnsrecord_append.yml
lib/ansible/modules/identity/ipa/ipa_dnsrecord.py

### CODE REVIEW

**Review by resmo — COMMENTED** [review]
`state=append` seems not to be idempotent.

**Comment by Akasurde** [comment]
> `state=append` seems not to be idempotent.

Yes, I'm working on that.

**Comment by tntclaus** [comment]
This does not fix 33193 in anyway https://github.com/ansible/ansible/issues/33193

I could not comment there as it is locked, so I write here. `state: append` is not idempotent. What can be really useful is something like this:

```
- ipa_dnsrecord:
    ipa_host: spider.example.com
    ipa_pass: Passw0rd!
    state: present
    zone_name: example.com
    record_name: vm-001
    record_type: 'AAAA'
    record_value:
     - '::1'
     - '2007::02'
```

**Comment by Elyytscha** [comment]
https://github.com/ansible/ansible/issues/33193 cant believe that this is not fixed since 2017

so there is no possible way till this is merged to setup a srv record with multiple records like

```
0 25 8883 example0.com
0 25 8883 example1.com
0 25 8883 example2.com
0 25 8883 example3.com
```
with the ipa_dnsrecord module?

hm feels like as 75% of the ansible modules can't cover my use cases and i have to do always those weird, unreadable, monsterous shell tasks instead ..

**Comment by Koma-Andrea** [comment]
Any news on that?

**Pull request closed without merging**
