### PR TITLE
win_regmerge: Clean up parameter handling

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_regmerge

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Changes include:
- Use Get-AnsibleParam with -type support
- Replace $result PSObject with normal hash

### CODE REVIEW

**Comment by jhawkesworth** [comment]
This looks good.
Needs #21377 but should be merged when that has landed

shipit

**Comment by dagwieers** [comment]
ready_for_review

**Comment by dagwieers** [comment]
bot_status

**Comment by gundalow** [comment]
shipit

**Pull request merged**
