### PR TITLE
modules/user: Fix returned groups issue

### LINKED ISSUE #80669: user module doesn't output the right 'groups' value in the return values.
### Summary

the return value 'groups' of user module should output the groups which a user **currently** belongs to, not has now been added to.

In the documentation, the description of return value 'groups' says as follows.
> List of groups of which the user is a member.

[https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#return-groups](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#return-groups)

### Issue Type

Bug Report

### Component Name

user

### Ansible Version

```console
$ ansible --version

ansible [core 2.12.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all


BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

### Steps to Reproduce

ansible-playbook -i hosts user.yml -k -K -vvvv
```
- hosts: all
  become: true
  tasks:
    - name: Create user
      user:
        name: "testuser"
        groups: 
          - www-data
          - sudo
        append: false
        state: present
    - name: Append a group to the user
      user:
        name: "testuser"
        groups:
          - man
        append: true
        state: present
```

### Expected Results

'groups' should output the groups which a user **currently** belongs to, not has now been added to.

### Actual Results

```console
The first "Create user" task is right because the user is now created for the first time. However, the second task "Append a group to the user" doesn't have the right value for "groups" since it outputs the 

TASK [Create user] **********************************************************************************************************************************************************************************
task path: /root/project/user.yml:5
<10.32.2.155> ESTABLISH SSH CONNECTION FOR USER: ubuntu
(( long output... ))
changed: [10.32.2.155] => {
    "changed": true,
    "comment": "",
    "create_home": true,
    "group": 1003,
    "groups": "www-data,sudo",
    "home": "/home/testuser",
    "invocation": {
        "module_args": {
            "append": false,
            "authorization": null,
            "comment": null,
            "create_home": true,
            "expires": null,
            "force": false,
            "generate_ssh_key": null,
            "group": null,
            "groups": [
                "www-data",
                "sudo"
            ],
            "hidden": null,
            "home": null,
            "local": null,
            "login_class": null,
            "move_home": false,
            "name": "testuser",
            "non_unique": false,
            "password": null,
            "password_expire_max": null,
            "password_expire_min": null,
            "password_lock": null,
            "profile": null,
            "remove": false,
            "role": null,
            "seuser": null,
            "shell": null,
            "skeleton": null,
            "ssh_key_bits": 0,
            "ssh_key_comment": "ansible-generated on agkr-testbox",
            "ssh_key_file": null,
            "ssh_key_passphrase": null,
            "ssh_key_type": "rsa",
            "state": "present",
            "system": false,
            "uid": null,
            "umask": null,
            "update_password": "always"
        }
    },
    "name": "testuser",
    "shell": "/bin/sh",
    "state": "present",
    "system": false,
    "uid": 1002
}
TASK [Append a group to the user] *******************************************************************************************************************************************************************
task path: /root/project/user.yml:13
<10.32.2.155> ESTABLISH SSH CONNECTION FOR USER: ubuntu
(long output...)
changed: [10.32.2.155] => {
    "append": true,
    "changed": true,
    "comment": "",
    "group": 1003,
    "groups": "man",
    "home": "/home/testuser",
    "invocation": {
        "module_args": {
            "append": true,
            "authorization": null,
            "comment": null,
            "create_home": true,
            "expires": null,
            "force": false,
            "generate_ssh_key": null,
            "group": null,
            "groups": [
                "man"
            ],
            "hidden": null,
            "home": null,
            "local": null,
            "login_class": null,
            "move_home": false,
            "name": "testuser",
            "non_unique": false,
            "password": null,
            "password_expire_max": null,
            "password_expire_min": null,
            "password_lock": null,
            "profile": null,
            "remove": false,
            "role": null,
            "seuser": null,
            "shell": null,
            "skeleton": null,
            "ssh_key_bits": 0,
            "ssh_key_comment": "ansible-generated on agkr-testbox",
            "ssh_key_file": null,
            "ssh_key_passphrase": null,
            "ssh_key_type": "rsa",
            "state": "present",
            "system": false,
            "uid": null,
            "umask": null,
            "update_password": "always"
        }
    },
    "move_home": false,
    "name": "testuser",
    "shell": "/bin/sh",
    "state": "present",
    "uid": 1002
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by ifkirne**
##### SUMMARY

Get the list of the groups the user belongs to by leveraging the **_user_group_membership_** function

Fixes #80669 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

user

### CODE REVIEW

**Comment by Akasurde** [comment]
@ifkirne Thanks for the contribution. We already have an elaborate fix https://github.com/ansible/ansible/pull/80696 for the same issue. It would be a great idea to provide views on that PR. Thanks.

**Comment by ifkirne** [comment]
@Akasurde Thanks for your feedback. I think leveraging the user_group_membership method, to get the list of the groups that a user belongs to without the need to construct it as in the fix #80696, is a simpler and cleaner way to resolve this issue. @s-hertel , @webknjaz I would love to get your feedback on this fix.

**Comment by s-hertel** [comment]
It is more expensive to call it again. The other PR was avoiding duplicate work because we already look up the existing groups once to determine the final state.

**Comment by s-hertel** [comment]
Can you add some tests for this?

I closed my PR since it needed a rebase, so now we can figure out what to do in this PR instead. Here was some initial testing with strace https://gist.github.com/s-hertel/316312d381263c3546dfb40dd02de253. Calling `grp.getgrall()` multiple times does add unnecessary syscalls, but I didn't try to look into how environment may factor into the overhead.

The other downside to this approach is the value won't be correct for --check + --diff mode.

**Comment by Akasurde** [comment]
@ifkirne Could you please address the above comment? Thanks in advance.

**Pull request closed without merging**
