### PR TITLE
fixing issue #1768: copy module can't overwrite/replace read-only files ...

### PR DESCRIPTION
**Pull request by kavink**
..., As recommended checking the destination directory is writable,(Still making sure its readable) then creating a hardlink and doing an atomic replace

### CODE REVIEW

**Comment by bcoca** [comment]
kavink, 

seems you beat me to the fix by a nose!

we approached this a bit differently but I think a merge of both patches is a better solution:

From yours:
- use os.link, looks cleaner than the existing shutil
- keep link exception check

From mine:
- check dir permissions so we can send the specific error and avoid the exception
- add ability to copy even if file is not readable (md5 will always be None), I should should change it to only work with 'force'

**Comment by bcoca** [comment]
I just realized os.link will only work if both the tmp file and destination are in the same partition, the reason it was using shutil.copy was because it could not be assured, so this extra copy occurred before calling module.atomic_replace

**Comment by kavink** [comment]
In what scenario will the temp file and destination not be in same partition ? btw i had just merged your commit with mine...

**Comment by bcoca** [comment]
ansible temp dir is in different partition than destination (/tmp vs /home
for example)

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by kavink** [comment]
Ahhh , reverted that, so only difference now is the force flag... But i guess i should close this pull request and we can just use #2100 ?

**Comment by mpdehaan** [comment]
works for me, we'll continue discussion over there.

**Pull request closed without merging**
