### PR TITLE
Adds module doc fragment for F5 modules

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

To reduce documentation duplication, this module fragment is
being created for use in all F5 modules.

### CODE REVIEW

**Comment by caphrim007** [comment]
@gundalow here's that document fragment code. I dont see the failure in Shippable???

**Comment by gundalow** [comment]
1. Click "Details"
2. Click the red ("1890.8" in this case)
3. Expand "build_ci" as it has a red marker
4. Expand "test/utils/shippable/ci.sh" as it's the only thing under it
5. Scroll up from the bottom and spot

> fatal: [testhost]: FAILED! => {"changed": true, "failed": true, "msg": "Yum command has been deprecated, redirecting to '/usr/bin/dnf -d 2 -y install sos'.\nSee 'man dnf' and 'man yum2dnf' for more information.\nTo transfer transaction metadata from yum to DNF, run:\n'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'\n\nError: Failed to synchronize cache for repo 'updates'\n", "rc": 1, "results": [""]}

Note that doesn't have anything to do with your code :(

Is the branch that you created this from up to date with devel?

**Comment by caphrim007** [comment]
@gundalow thanks for the tips. Yep, it was created from an up-to-date devel at the time. Rebasing on the current devel and trying again

**Comment by caphrim007** [comment]
@gundalow doesnt looks like these are my errors either. merge?

**Comment by gundalow** [comment]
@caphrim007 Thanks for this, did you want to add a link to your website's documentation under `notes:`?

The failing test is in the Windows test, and unrelated to this change.

Assigning to @privateip for final review & merge

For updating the modules one PR that does all of `networking/f5` would most likely be easiest to review/

**Comment by caphrim007** [comment]
yeah i can add a note

**Comment by caphrim007** [comment]
@gundalow are notes merged with the notes in modules? Or do the notes in a module overwrite the notes key in this fragment?

**Comment by gundalow** [comment]
@caphrim007 I believe they are merged

**Pull request merged**
