### PR TITLE
Zabbix facts

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
Implemented fixes requested in PR #39653 and #39654:
- documentation shall use appropriate module doc fragment
- all zabbix modules should have validate_certs option
- removed duplicate code

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
- zabbix_host_facts
- zabbix_group_facts

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (devel 13c7d149bb) last updated 2018/06/04 12:36:01 (GMT +200)
  config file = None
  configured module search path = [u'~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ~/projects/ansible/ansible-fork/lib/ansible
  executable location = ~/projects/ansible/ansible-fork/bin/ansible
  python version = 2.7.14 (default, Oct 31 2017, 21:12:13) [GCC 6.4.0]
```

### CODE REVIEW

**Comment by D3DeFi** [comment]
@resmo mind having a look please? Should I implement (below) requested change as well?
https://github.com/ansible/ansible/pull/39653/files#r187874825

Don't see any harm in having it in this state, but it is definitely and odd feature, which is expecting that user will not provide one of the 2 essential options (e.g. similar to not using this module at all). 

Btw, If I want to add myself as a maintainer for the whole modules/monitoring/zabbix folder, should I create separate PR or is it ok to commit it to this one?

**Comment by resmo** [comment]
@D3DeFi if one of the args `host_ip`or `host_name`is required, I would add the `required_one_of=[['host_ip', 'host_name']],` to the arg_spec.

**Review by resmo — APPROVED** [review]
code LGTM

**Comment by resmo** [comment]
@D3DeFi would be a pleasure to add you as a maintainer for these. feel free to add a PR to .github/BOTMETA.yml

**Pull request merged**
