### PR TITLE
New AWS module for managing IAM groups fork from @naslanidis

### PR DESCRIPTION
**Pull request by mpostument**
##### SUMMARY
The module was forked from https://github.com/ansible/ansible/pull/21236. Because author left this module unfinished 

##### ISSUE TYPE
New Module Pull Request

##### COMPONENT NAME
iam_group

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Module to allow managing AWS IAM groups.

As per the below PR, it was decided that the iam module should be split in to separate ones i.e. iam_role, iam_user, iam_group. This module completes the iam_group module.

I debated whether to include the user output, however as this is returned by the get_group API action and is useful I decided to keep it.

https://boto3.readthedocs.io/en/latest/reference/services/iam.html#IAM.Client.get_group
```
TASK [debug] *************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "iam_group": {
            "group": {
                "arn": "arn:aws:iam::1234567890:group/test_group", 
                "create_date": "2017-02-10T09:43:01+00:00", 
                "group_id": "AGPAIDBWE123SFINE55TM", 
                "group_name": "test_group", 
                "path": "/"
            }, 
            "users": [
                {
                    "arn": "arn:aws:iam::1234567890:user/test_user1", 
                    "create_date": "2017-02-10T07:12:32+00:00", 
                    "path": "/", 
                    "user_id": "AIDAIZTPYHR4123S22YU2", 
                    "user_name": "test_user1"
                }
            ]
        }
    }
}

```

### CODE REVIEW

**Comment by willthames** [comment]
When I suggested using my convert friendly names function, it was pre-review, and there were some bugs in it. The latest version is now in the codebase: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/iam_role.py#L184-L197

**Comment by willthames** [comment]
It might also be worth moving convert_friendly_names_to_arns to module_utils/ec2.py so that both modules would benefit from future improvements, as well as any further modules that could make use of it.

**Comment by mpostument** [comment]
@willthames your function give me an error when managed_policy is empty list
```
AttributeError: 'NoneType' object has no attribute 'startswith'
```
But it is working when 
```
if not [policy.startswith('arn:') for policy in policies if policy is not None]:
```

**Comment by mpostument** [comment]
@willthames Should new PR will be created for moving this function to ec2.py?

**Comment by willthames** [comment]
I don't call the conversion function with a `None` list:

```
    if managed_policies:
        managed_policies = convert_friendly_names_to_arns(connection, module, managed_policies)
```

**Comment by willthames** [comment]
We can move the conversion function separately

**Comment by willthames** [comment]
do you mean an empty list or a list containing None

```
iam_role:
  managed_policies:
  -
```

would I suppose need the `None` check

**Comment by mpostument** [comment]
Yep, a list containing None.
```
if not [policy.startswith('arn:') for policy in policies if policy is not None]:
```
This fixed problem

**Review by willthames — CHANGES_REQUESTED** [review]
```
$ flake8 lib/ansible/modules/cloud/amazon/iam_group.py
lib/ansible/modules/cloud/amazon/iam_group.py:165:1: F401 'json' imported but unused
lib/ansible/modules/cloud/amazon/iam_group.py:368:13: F821 undefined name 'module'
lib/ansible/modules/cloud/amazon/iam_group.py:379:13: F821 undefined name 'module'
```

The first of these is relatively unimportant, the latter two must be fixed

**Comment by mpostument** [comment]
Flake8 is fixed

**Review by willthames — APPROVED** [review]

**Comment by mpostument** [comment]
@willthames This PR can be merged?

**Comment by willthames** [comment]
Reopening for hopeful final CI before merge

**Comment by mpostument** [comment]
@willthames can you restart it again. Run 25544 status is TIMEOUT. Looks like it is failed on uploading test reports

**Comment by mpostument** [comment]
@willthames CI build was successful

**Comment by willthames** [comment]
I squashed the commits while preserving authorship, the results were dc8a05d and 4e54df7 which are now merged

**Comment by willthames** [comment]
Thanks @Infectsoldier for all your hard work getting this sorted for merging, and thanks to @naslanidis for the original work!

**Pull request closed without merging**
