### PR TITLE
Playbook callback problem fixed

### PR DESCRIPTION
**Pull request by yinhejianke**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bcoca** [comment]
what problem is this fixing?

needs_info

**Comment by yinhejianke** [comment]
from ansible.plugins.callback import CallbackBase
class Playbook_ResultCallback(CallbackBase):
    '''

    '''

    infos = {}

    def v2_on_any(self, *args, **kwargs):
        self.on_any(args, kwargs)
        for one in args:
            if hasattr(one, "_host"):
                self.infos[one._host.name] = one._result

####################
    results_callback = Playbook_ResultCallback()
    # args = ['ansible-playbook', "/home/wushujun/Documents/Python/ansible/pub_key/update.yaml"]
    callback_data = PlaybookCLI(args, callback=results_callback)
    callback_data .run()

results_callback.infos   nothing ...
no data callback.
so I think it's a bug.
________________________________
junshuwu@live.cn

**Comment by bcoca** [comment]
you can make any arbitrary code as a bug, can you show how this affects existing Ansible code?

a playbook that reproduces the problem you are trying to fix?

needs_info

**Comment by yinhejianke** [comment]
from ansible.cli.playbook import PlaybookCLI
import pprint
from ansible.plugins.callback import CallbackBase
import os
import yaml


HOST_PATH = BASE_DIR = os.path.dirname(os.path.abspath(__file__)) + "/temp"
class Playbook_ResultCallback(CallbackBase):
    '''

    '''

    infos = {}

    def v2_on_any(self, *args, **kwargs):
        self.on_any(args, kwargs)
        for one in args:
            if hasattr(one, "_host"):
                self.infos[one._host.name] = one._result

def main():
    results_callback = Playbook_ResultCallback()
    playbook_info = [{'connection': 'local',
                      'hosts': 'cisco',
                      'tasks': [{'name': 'cisco test',
                                 'telnet': {'command': ['terminal length 0', 'show version'],
                                            'login_prompt': 'Username: ',
                                            'password': 'admin',
                                            'prompts': ['[>#]', 'Password: ', '--More-- '],
                                            'user': 'admin'}}]}]

    Command_Infos = "[cisco]\n10.30.41.150\n10.30.41.151\n10.30.41.152"

    Tem_path = HOST_PATH + "/playbook.yaml"
    with open(Tem_path, "w+") as f:
        yaml.dump(playbook_info, f)

    Tem_hosts = HOST_PATH + "/hosts"
    with open(Tem_hosts, "w+") as f:
        f.write(Command_Infos)

    args = ['ansible-playbook', Tem_path, "-i", Tem_hosts]
    aa = PlaybookCLI(args, callback=results_callback)
    aa.run()
    pprint.pprint(results_callback.infos)   #########  no any data print.



if __name__ == "__main__":
    main()


________________________________
junshuwu@live.cn

**Comment by bcoca** [comment]
Internal Ansible API
====================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us
to have an active community that is willing to submit feedback so that we may
continue to make Ansible better.

The internal Python API is considered an unsupported aspect of Ansible and this
is not considered a bug unless there is an issue with an Ansible binary
(`ansible`, `ansible-playbook`, `ansible-doc`, etc) or an issue with an external
API such as are provided for the development of plugins (modules, dynamic
inventories, callbacks, strategies, etc).

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists or IRC to talk about this and we might be persuaded otherwise.

   * IRC: #ansible on irc.freenode.net   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!
Internal Ansible API
====================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us
to have an active community that is willing to submit feedback so that we may
continue to make Ansible better.

The internal Python API is considered an unsupported aspect of Ansible and this
is not considered a bug unless there is an issue with an Ansible binary
(`ansible`, `ansible-playbook`, `ansible-doc`, etc) or an issue with an external
API such as are provided for the development of plugins (modules, dynamic
inventories, callbacks, strategies, etc).

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists or IRC to talk about this and we might be persuaded otherwise.

   * IRC: #ansible on irc.freenode.net   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
