### PR TITLE
new module: manage attachable entity profiles [network/aci/aci_aep]

### PR DESCRIPTION
**Pull request by schunduri**
##### SUMMARY

New Cisco ACI Module to manage Attachable Entity profile

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

aci_aep
##### ANSIBLE VERSION

```
v2.4
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by schunduri** [comment]
@dagwieers can you please review the changes and merge it

**Comment by dagwieers** [comment]
@schunduri Could you take the one from the aci-ansible project. There are a few differences.

**Comment by schunduri** [comment]
@dagwieers this file is the one merged onto datacenter aci-ansible project

**Review by dagwieers — APPROVED** [review]
@schunduri I added the latest changes from aci-ansible. Good to go now.

**Comment by schunduri** [comment]
@dagwieers Sure thank you :)

**Pull request merged**
