### PR TITLE
fixing problems updating stack set

### PR DESCRIPTION
**Pull request by ismferd**
##### SUMMARY
I'm having errors updating stack sets.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

- Module: cloudformation_stack_sets
https://docs.ansible.com/ansible/devel/modules/cloudformation_stack_set_module.html

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /Users/ismaelfernandez/.ansible.cfg
  configured module search path = [u'/Users/ismaelfernandez/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ismaelfernandez/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### ADDITIONAL INFORMATION
Firstly, change_set and instances have been created without errors:
```
---
- name: Create a stack set with instances
  cloudformation_stack_set:
    profile: "{{ boto_profile | default(omit) }}"
    name: my-stack-to-delete-jessio
    description: Create stack set
    state: present
    capabilities: CAPABILITY_IAM
    administration_role_arn: arn:aws:iam::{{ admin_account.stdout }}:role/PlatformAdministrationRole
    execution_role_name: PlatformExecutionRole
    template:  roles/stack_sets/templates/example_pre_cfn.yaml
    regions:
      - eu-west-1
    failure_tolerance:
      parallel_percentage: 100
      fail_percentage: 40
    accounts: "{{ executors_account_id.stdout }}"
```

So, When I have launched again that didn't work as I expected catching this error:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/ismaelfernandez/.ansible/tmp/ansible-tmp-1541700373.86-89204874531189/AnsiballZ_cloudformation_stack_set.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/Users/ismaelfernandez/.ansible/tmp/ansible-tmp-1541700373.86-89204874531189/AnsiballZ_cloudformation_stack_set.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/ismaelfernandez/.ansible/tmp/ansible-tmp-1541700373.86-89204874531189/AnsiballZ_cloudformation_stack_set.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/tt/mlmx2kd91vs1y11my58n74s00000gn/T/ansible_cloudformation_stack_set_payload_3U73E6/__main__.py\", line 669, in <module>\n  File \"/var/folders/tt/mlmx2kd91vs1y11my58n74s00000gn/T/ansible_cloudformation_stack_set_payload_3U73E6/__main__.py\", line 615, in main\n  File \"/var/folders/tt/mlmx2kd91vs1y11my58n74s00000gn/T/ansible_cloudformation_stack_set_payload_3U73E6/ansible_cloudformation_stack_set_payload.zip/ansible/module_utils/aws/core.py\", line 251, in deciding_wrapper\n  File \"/Users/ismaelfernandez/Library/Python/2.7/lib/python/site-packages/botocore/client.py\", line 320, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Users/ismaelfernandez/Library/Python/2.7/lib/python/site-packages/botocore/client.py\", line 623, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.OperationInProgressException: An error occurred (OperationInProgressException) when calling the UpdateStackInstances operation: Another Operation on StackSet arn:aws:cloudformation:eu-west-1:XXXXXXXXX:stackset/my-stack-to-delete-jessio:bfb8d800-a03b-4b28-950b-56480c7b9c85 is in progress\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
My solution have been clean the code related with cfn.update_stack_instances because, that is doing in `update_stack_set`

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @s-hertel

**Comment by ismferd** [comment]
@ansibot ping

**Comment by ismferd** [comment]
@ryansb Can you check it?

**Comment by stealthizer** [comment]
While working with stack sets I've found this exact problem.  This solution worked for me!

**Pull request closed without merging**
