### PR TITLE
RabbitMQ 3.6.7 changed a couple of response codes

### PR DESCRIPTION
**Pull request by marlier**
##### SUMMARY
RabbitMQ 3.6.7 (released 3/15/2017) embeds a new HTTP server, and changed the response code returned from several endpoints.  This updates the rabbitmq_queue and rabbitmq_exchange modules to allow for this.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- rabbitmq_exchange
- rabbitmq_queue

##### ANSIBLE VERSION
All

##### ADDITIONAL INFORMATION
See RabbitMQ release notes here: [https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_7](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_7)

### CODE REVIEW

**Comment by manuel-sousa** [comment]
shipit

**Comment by hyperized** [comment]
This issue affects multiple versions (as described here: https://github.com/ansible/ansible/issues/22694). Can this be backported into 2.2 (and probably 2.3) as well?

**Comment by LukasBeaton** [comment]
Any idea when this fix might get merged in?

**Comment by gundalow** [comment]
closing and reopening to retrigger ci

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel` and cherry picked into `stable-2.3` https://github.com/ansible/ansible/commit/c5971f018fd6f5594a2b43aed7339be4b7fb2bb4

2.3.1 Changelog updated in https://github.com/ansible/ansible/pull/25485

**Pull request merged**
