### PR TITLE
Add support for openSUSE and SUSE Linux Enterprise to ansible.spec

### PR DESCRIPTION
**Pull request by l1k**

### CODE REVIEW

**Comment by dirtyharrycallahan** [comment]
You may want to take a look at pull request 4689. I believe I submitted that about a month ago.Since then there have been at least two subsequent pull requests, yours may be the third, to improve SuSE and openSuSE support for building the rpms.

**Comment by l1k** [comment]
Thanks, I didn't notice that.

I think there's an issue with your solution (pull request #4689), it breaks support for Fedora and other non-RHEL distros. That's because you replaced the "%if 0%{?rhel} && 0%{?rhel} <= 5 ... %else" statement with one %if statement for RHEL > 5 and another for RHEL <= 5.

Do have the numbers of the other pull requests handy?

**Comment by mpdehaan** [comment]
Closing this as a duplicate.

I'll copy your comment to the other ticket as well.

**Comment by l1k** [comment]
Found pull request #4850 via the reference in your own pull request. That solution doesn't break Fedora support. Neither does mine, plus it includes the fdupes mumbojumbo that rpmlint on opensuse.org otherwise complains about.

But as always, there's more than one way to do it. :)

**Pull request closed without merging**
