### PR TITLE
Refactor format_allowed_section in gce_net module.

### PR DESCRIPTION
**Pull request by peterandiw**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

cloud/google/gce_net.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

This is to increase understandability of the code, so hopefully the flow
can help those who read this code to better understand its output and
to prevent possibility of future bugs.

Being related to fix #20528, this is a refactor to some of the code beginning from 3b667b6b06d1e26aba1d97cf89e8905b80a20457's commit for better understanding.

### CODE REVIEW

**Comment by supertom** [comment]
Hi @peterandiw, thanks for having a look at this.  I agree this code is convoluted. 

Would you mind some unit tests in test/units/modules/cloud/google/test_gce_net.py (you'll need to create this file)?  Adding the tests will allow everyone to keep this function maintained.  Furthermore, we're planning a refactoring of the entire module, and so, having tests for standalone functions like this will allow them to be easily ported over.

**Comment by peterandiw** [comment]
Sure @supertom . Sorry it took me quite a long time to respond.

**Comment by peterandiw** [comment]
Considering the latest test result, I think I need to refactor the other method first.

**Comment by mattclay** [comment]
CI failure due to unit tests: https://app.shippable.com/runs/58945c7fbc668d1000b1047b/2/tests

**Comment by Akasurde** [comment]
@peterandiw Are you still working on this, let us know ? Thanks, needs_info

**Pull request closed without merging**
