### PR TITLE
openshift_raw and openshift_scale: fix broken import

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
`openshift_raw` and `openshift_scale` modules: fix broken import

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/k8s/

##### ANSIBLE VERSION
```
ansible 2.6.0 (devel 7437d6fdc4) last updated 2018/04/23 02:48:26 (GMT +200)
```

### CODE REVIEW

**Comment by chouseknecht** [comment]
@pilou- 

Looks good to me. Thanks for fixing this!

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
@pilou- This should be good to merge once `test/sanity/validate-modules/ignore.txt` is updated.

**Comment by mattclay** [comment]
Unstable CI result unrelated to changes.

**Comment by mattclay** [comment]
@pilou- Thanks for the fixes!

**Comment by pilou-** [comment]
`git` target is unstable on `freebsd/11.1/1`:
```
TASK [git : ARCHIVE | Archive repo using various archival format] **************
failed: [testhost] (item=tar.gz) => {
  "changed": false,
  "cmd": "/usr/local/bin/git clone --origin origin https://github.com/jimi-c/test_role /root/ansible_testing/git",
  "item": "tar.gz",
  "msg": "Cloning into '/root/ansible_testing/git'...\nFatal error 'thread 0x801a16a00 exits with resources held!' at line 318 in file /usr/src/lib/libthr/thread/thr_exit.c (errno = 25)\nerror: fetch-pack died of signal 6",
  "rc": 128,
  "stderr": "Cloning into '/root/ansible_testing/git'...\nFatal error 'thread 0x801a16a00 exits with resources held!' at line 318 in file /usr/src/lib/libthr/thread/thr_exit.c (errno = 25)\nerror: fetch-pack died of signal 6\n",
  "stderr_lines": ["Cloning into '/root/ansible_testing/git'...",
  "Fatal error 'thread 0x801a16a00 exits with resources held!' at line 318 in file /usr/src/lib/libthr/thread/thr_exit.c (errno = 25)",
  "error: fetch-pack died of signal 6"],
  "stdout": "",
  "stdout_lines": []}
changed: [testhost] => (item=tar) => {"after": "4f2148c62783a6df42a2ae7e5436b8b2ce4deb1f", "before": null, "changed": true, "item": "tar"}
changed: [testhost] => (item=tgz) => {"after": "4f2148c62783a6df42a2ae7e5436b8b2ce4deb1f", "before": "4f2148c62783a6df42a2ae7e5436b8b2ce4deb1f", "changed": true, "item": "tgz", "remote_url_changed": false}
changed: [testhost] => (item=zip) => {"after": "4f2148c62783a6df42a2ae7e5436b8b2ce4deb1f", "before": "4f2148c62783a6df42a2ae7e5436b8b2ce4deb1f", "changed": true, "item": "zip", "remote_url_changed": false}
 	to retry, use: --limit @/root/ansible/test/integration/git-gE4jC1.retry
```

**Pull request merged**
