### PR TITLE
Add digital-ocean cloud support.

### PR DESCRIPTION
**Pull request by zbal**
Same as [previous PR](/ansible/ansible/pull/3188).

Add support for [Digital Ocean](https://www.digitalocean.com) cloud provider; this module rely on [dopy](https://pypi.python.org/pypi/dopy).

It allows:
- creation / deletion of droplets (servers) based on:
  - size
  - region
  - image
- add / remove SSH keys (those keys get then added to the root user of the newly created servers)
- optional wait until server is created

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!

Can you please rename this to "digital_ocean" from "do" ?  "do" is likely to be future language construct.

Also, can you also add an example of SSH key management?

**Comment by zbal** [comment]
Module has been renamed (yes indeed do may not be the greatest name). Added documentation for ssh key and improve other docs.

**Comment by mpdehaan** [comment]
Thanks!

Quick note -- I see you have a merge commit in there.

The trick is to start a new branch for each feature you submit, and then use "git pull --rebase" vs "git pull" or "git rebase" vs "git merge".

I'll cherry pick these for now, though in the future, watch the merge commits and it will make it easier on me.

Thanks!

**Comment by zbal** [comment]
Noted !

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request closed without merging**
