### PR TITLE
Module mail to send out emails as an action

### PR DESCRIPTION
**Pull request by dagwieers**
Sending mails could be part of the workflow to have teams/responsibles perform specific task. Or simply to notify that a process has finished successfully (e.g. provisioning).

### CODE REVIEW

**Comment by dagwieers** [comment]
@go2sh Not sure what the first remark is about. But the second is handled by smtplib itself already.

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by jpmens** [comment]
filename is `library/mail` but _module_ name in DOCUMENTATION is `email`. Which is correct?

**Comment by mpdehaan** [comment]
filename since you can't call it without the filename being right
-- patches accepted.

I doubt we'll be interfacing to worldwide post offices to enable snail mail
any time soon

(Really though the module formatter shouldn't need a "name" in the
DOCUMENTATION string since it could be based on the filename every time,
imagine all the saved bandwidth!)

**Comment by jpmens** [comment]
while pondering a `fax` module, I've submitted https://github.com/ansible/ansible/pull/1343

**Comment by vanne** [comment]
Just and idea: what about a template for the mail body?

**Comment by dagwieers** [comment]
Yes, please ! :-)

You can already accomplish something similar by using $FILE(), although it my not template the file. I think the obvious solution is something like this. Maybe $TEMPLATE() ?

**Comment by jpmens** [comment]
Excellent idea, but surely non-trivial, at least with my understanding of how Ansible works.

The mail module would have to do the templating which means Jinja2 support on the node, unless "mail" gets the same behind-the-scenes magic that "template" already has...

I'm probably completely off-track though...

**Comment by dagwieers** [comment]
I'll be (trying to) implement $TEMPLATE() when commuting back home.

**Comment by mpdehaan** [comment]
It seems mail could entirely be a server side action regular than a regular
module, and then that all gets much simpler.

It could use the local templating code then.

**Comment by mpdehaan** [comment]
the other question is should mail be BYPASS_HOST_LOOP in some cases,
or have a way to turn that on, so if you just want to email "play all
done for these hosts" you can do it without sending 50 (or more)
emails?

Though you could put it in a play by itself if you wanted, I guess

**Comment by dagwieers** [comment]
There are cases where people want to delegate the mail module to another host. I think @arrfab blogged about it.

For debug/fail I don't see a point in running that anywhere else than local though.

How do you make a pure server-side module ?

**Comment by dagwieers** [comment]
For mails outside the host loop we use the callback mechanism already. In this case the point is to send a mail for each host (in case of provisioning it is done to make sure another team/person should be taking care of his part in the workflow).

That's why I categorized mail as a workflow module (much like fail, debug, pause, wait_for...)

**Comment by dagwieers** [comment]
From IRC with @mpdehaan @dhozac @vanne:

```
(04:12:02 PM) dag: Does $FILE() also template ?
(04:12:10 PM) daniel_hozac: yes
(04:12:15 PM) dag: ok, great
(04:12:15 PM) daniel_hozac: hmm
(04:12:38 PM) daniel_hozac: no, it appears it doesn't anymore.
(04:12:42 PM) daniel_hozac: it did originally.
(04:14:37 PM) dag: I got a feature request for the mail module to allow to use a template for the body of the mail
(04:15:02 PM) dag: that seems useful, but I hate to add a separate (mutual exclusive) option for this, $FILE() seems so much more useful for this
(04:15:19 PM) daniel_hozac: that'd be awkward though, as it wouldn't template the same way that template oes
(04:15:55 PM) dag: ah ?
(04:16:17 PM) daniel_hozac: template uses jinja2, even if $FILE() would allow templating, it'd be ansible templating
(04:16:34 PM) dag: if I would allow an option to specify a file, I would have to create an action plugin to send that file over, and that seems too painful for this specific thing
(04:16:48 PM) daniel_hozac: yep
(04:16:53 PM) dag: can't we create $TEMPLATE() ?
(04:16:54 PM) daniel_hozac: and also to template it first
(04:17:09 PM) daniel_hozac: should be trivial
(04:17:27 PM) dag: trivial for you, hard for me, but I'll accept the challenge (for my commute home)
(04:17:58 PM) vanne: tia dag
(04:18:18 PM) ***vanne must find some time to learn python
(04:20:08 PM) vanne: $TEMPLATE() sounds good btw. should be usable elsewhere too.
(04:21:12 PM) daniel_hozac: dag-:  i can do it if you like
(04:22:03 PM) mdehaan: dag-: with_* is my solution to not needing $FOO type things
(04:22:43 PM) mdehaan: I want "with_fileglob" to have brothers like "with_filedata"
(04:23:00 PM) mdehaan: so maybe like "with_template" but right now you only get one $item at a time
(04:23:17 PM) mdehaan: which can be limiting
(04:23:29 PM) mdehaan: I find stuff like $FILE kind of like Perl and I want to minimize that, while keeping it around for backwards compat
(04:24:52 PM) dag: so $TEMPLATE() will not get accepted ?
(04:30:08 PM) dag: mdehaan: is there a point in make a pull-request for $TEMPLATE() ?
```

Not sure if creating $TEMPLATE() would get accepted, so I'll wait until this is clear.

**Comment by jpmens** [comment]
On the way to the hotel I was thinking along those lines as well; almost had implementation mentally ready ... ;-) I certainly hope $TEMPLATE() or similar gets acccepted.

**Comment by dhozac** [comment]
#1502 may have a solution...

**Pull request merged**
