### PR TITLE
Enable more Windows tests in CI.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Enable more Windows tests in CI.

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

Windows integration tests

##### ANSIBLE VERSION

```
ansible 2.5.0 (windows-tests 3523a4d9b2) last updated 2017/09/15 14:04:00 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

### CODE REVIEW

**Comment by dagwieers** [comment]
@mattclay Just out of interest. Why did you disable the banner ? Was there an issue or just because it looks nicer ? :-)

The option to disable the banner is only available in the latest version, so that's why we could not enable it by default when we introduced it.

**Comment by mattclay** [comment]
@dagwieers The tests did not pass with the banner enabled.

**Comment by dagwieers** [comment]
@mattclay I now see that the **win_psexec** tests are disabled for Shippable. I think they were not stable enough to run on all Windows platforms.

**Comment by mattclay** [comment]
@dagwieers Correct. The win_psexec tests do pass now, but not reliably enough for use in CI yet.

**Pull request merged**
