### PR TITLE
dynamodb_table: AnsibleAwsModule, billing_mode, point_in_time_recovery

### LINKED ISSUE #56923: dynamodb_table support for On-Demand billing
##### SUMMARY
A new billing mode was added to DynamoDB [back in Nov, 2018](https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing/) called On-Demand which acts as an alternative to setting RCU and WCU values. This feature is already [supported in Boto 3 with the BillingMode attribute](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.ServiceResource.create_table). This feature request is to implement the On-Demand billing option in the dynamodb_table module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
dynamodb_table

##### ADDITIONAL INFORMATION
Note that there's already an Issue opened for this which wasn't filled in correctly: #54963. Instead of letting that issue languish any further, I suggest closing it in favor of this one.

Another link explaining how the new pricing model works: https://aws.amazon.com/dynamodb/pricing/

I'd suggest adding a 'billing_mode' parameter to the module which can hold a value of either 'provisioned' or 'pay_per_request' to reflect Boto3 values. The 'indexes' parameter will also need to be updated since GSI's can also support on-demand billing. 'billing_mode' should probably default to 'pay_per_request' since that seems like a more popular and generic setting unless you know exactly how many RCU/WCU's you want; This is the reason AWS added this mode, of course. To support backwards compatibility with existing tasks, if 'read_capacity' and 'write_capacity' are set then the 'billing_mode' would switch to 'provisioned' automatically.

Example:
```yaml
- dynamodb_table:
    name: my-table
    region: us-east-1
    hash_key_name: id
    hash_key_type: STRING
    range_key_name: create_time
    range_key_type: NUMBER
    billing_mode: PAY_PER_REQUEST
    tags:
      tag_name: tag_value
```

### PR DESCRIPTION
**Pull request by anryko**
##### SUMMARY

Fix `AnsibleAwsModule` migration stale PR (#45402). Add `billing_mode` and `point_in_time_recovery`. Small bug fixes. Integration tests fixes.

Fixes #45402
Fixes #56923

##### ISSUE TYPE

- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME

- dynamodb_table

##### ADDITIONAL INFORMATION

```yaml
    - name: enable on-demand billing and backups
      dynamodb_table:
        name: table_name
        hash_key_name: myhashkey
        billing_mode: PAY_PER_REQUEST
        point_in_time_recovery: yes
```

### CODE REVIEW

**Comment by marknet15** [comment]
Hi @anryko I'm not sure if you are still currently working on this PR but I have created the following based on your changes, if you wouldn't mind taking a look at ? it provides some fixes on top of your changes based on usage of your updated module internally.
https://github.com/anryko/ansible/pull/1

**Comment by tremble** [comment]
Hi @marknet15 thanks for taking the time to try and move this forward.

Unfortunately the AWS modules have been moved from the main Ansible repository.  There are now two repos which include AWS modules 
- https://github.com/ansible-collections/amazon.aws which includes the 'supported' modules
- https://github.com/ansible-collections/community.aws which includes the 'community' modules (and will be the initial home for most future modules)

dynamodb_table can now be found in the 'community' repo: https://github.com/ansible-collections/community.aws/blob/master/plugins/modules/dynamodb_table.py

Additionally the IAM policies used for testing have been moved into https://github.com/mattclay/aws-terminator/tree/master/hacking (the repo will probably get renamed at some point)

**Comment by marknet15** [comment]
Hi @tremble, no problem at all and thanks for your response and extra information, much appreciated! I will look at getting the ball rolling and re-create the PR as requested.

**Comment by Akasurde** [comment]
Closing in favor of https://github.com/ansible-collections/community.aws/pull/65

**Comment by Akasurde** [comment]
@anryko Thanks for the contribution.

**Pull request closed without merging**
