### PR TITLE
jsonify inventory

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

Use same 'jsonifyier' that  we use for modules in ansible-inventory to allow encoding 'problem cases'

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ansible-inventory
##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by s-hertel** [comment]
LGTM

**Comment by s-hertel** [comment]
Actually eating my words.
I had to add this to get it to work right for datetime objects:
```
+from datetime import datetime

 from ansible.module_utils._text import to_bytes, to_text
 from ansible.module_utils.six import binary_type, iteritems, text_type
@@ -39,6 +40,8 @@ class _SetEncoder(json.JSONEncoder):
     def default(self, obj):
         if isinstance(obj, Set):
             return list(obj)
+        elif isinstance(obj, datetime):
+            return obj.isoformat()
```

**Comment by sivel** [comment]
> I had to add this to get it to work right for datetime objects:

I think this is a good addition, but we shouldn't have any datetime objects coming from vars, unless someone uses a YAML date.  If so, you are likely going to experience problems with that elsewhere.

**Comment by s-hertel** [comment]
I'm just experiencing the datetime issues with the WIP aws_ec2 inventory plugin. If that should be handled in aws_ec2 that's fine too.

**Comment by bcoca** [comment]
i would add the 'datetime' as many modules hit this issue also (i thought we had fixed already, but clearly we did not)

**Comment by abadger** [comment]
Merged and cherrypicked to stable-2.4

**Pull request merged**
