### PR TITLE
Netbox secrets

### LINKED ISSUE #48354: A lookup plugin to fetch secrets from Netbox
##### SUMMARY
A lookup plugin to fetch secrets from Netbox

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
netbox-secrets

##### ADDITIONAL INFORMATION
This would complement the Netbox inventory plugin already available for ansible to allow fetching secrets associated with servers. This is also similar to exsiting plugins for Lastpass and HashiCorp's vault. My use case is that I store passwords for servers out-of-band management facilities in netbox and want to have Ansible use them to configure a monitoring system.

```yaml
Example usage:
    - name: query Netbox for secret
      debug: msg={{ lookup("netbox_secrets", netbox_host="https://not_netbox.hyperslice.net:443", private_key_file=".netbox-private-key.pem", token="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", device="someserver", secret_name="ilo-password")}}
	  
Example response:
TASK [query  for Netbox secret] 
ok: [someserver] => {
    "msg": "hunter2"
}
```

### PR DESCRIPTION
**Pull request by ollybee**
##### SUMMARY
A lookup plugin to fetch secrets from Netbox
Fixes #48354

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
netbox-secrets

##### ANSIBLE VERSION
```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/monitoring/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION

```paste below
    - name: query  for Netbox secret
      debug: msg={{ lookup("netbox_secrets", netbox_host="https://netbox.hyperslice.net:443", private_key_file=".netbox-private-key.pem", token="<redacted>", device="someserver", secret_name="test_username")}}


~/ansible$ ansible-playbook lookup.yml -i ./netbox_inventory.yml --connection=local --limit someserver -vvvv
ansible-playbook 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/monitoring/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/home/monitoring/ansible/netbox_inventory.yml did not meet host_list requirements, check plugin documentation if this is unexpected
/home/monitoring/ansible/netbox_inventory.yml did not meet virtualbox requirements, check plugin documentation if this is unexpected
Fetching: https://netboxdev.hyperslice.net/api/dcim/regions/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/tenancy/tenants/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/racks/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/sites/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/device-roles/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/device-types/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/manufacturers/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/devices/?limit=0&name=someserver
Fetching: https://netboxdev.hyperslice.net/api/virtualization/virtual-machines/?limit=0&name=someserver
Parsed /home/monitoring/ansible/netbox_inventory.yml inventory source with netbox plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: lookup.yml ********************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in lookup.yml

PLAY [all] ******************************************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [query  for Netbox secret] *********************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/monitoring/ansible/lookup.yml:8
fatal: [someserver]: FAILED! => {
    "msg": "lookup plugin (netbox_secrets) not found"
}
        to retry, use: --limit @/home/monitoring/ansible/lookup.retry

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************
someserver                 : ok=0    changed=0    unreachable=0    failed=1

~/ansible$ ansible-playbook lookup.yml -i ./netbox_inventory.yml --connection=local --limit someserver -vvvv
ansible-playbook 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/monitoring/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/home/monitoring/ansible/netbox_inventory.yml did not meet host_list requirements, check plugin documentation if this is unexpected
/home/monitoring/ansible/netbox_inventory.yml did not meet virtualbox requirements, check plugin documentation if this is unexpected
Fetching: https://netboxdev.hyperslice.net/api/dcim/sites/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/regions/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/tenancy/tenants/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/device-roles/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/device-types/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/racks/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/manufacturers/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/devices/?limit=0&name=someserver
Fetching: https://netboxdev.hyperslice.net/api/virtualization/virtual-machines/?limit=0&name=someserver
Parsed /home/monitoring/ansible/netbox_inventory.yml inventory source with netbox plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: lookup.yml ********************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in lookup.yml

PLAY [all] ******************************************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [query  for Netbox secret] *********************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/monitoring/ansible/lookup.yml:8
ok: [someserver] => {
    "msg": "hunter2"
}
META: ran handlers
META: ran handlers

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************
someserver                 : ok=1    changed=0    unreachable=0    failed=0


```

### CODE REVIEW

**Comment by gundalow** [comment]
@ollybee Thank you for the PR, your first I believe. FYI, we have out first NetBox modules in review as well https://github.com/ansible/ansible/pull/46936 would welcome your feedback on them

You can run `test/runner/ansible-test sanity --test pylint` from your Ansible checkout which will help you resolve the issues above


@FragmentedPacket I believe you've been looking at NetBox, would you be interested in taking a look at this

**Comment by FragmentedPacket** [comment]
@gundalow I can take a look. I don't use secrets, but I'm sure I can set up a test.

**Comment by ollybee** [comment]
I used this today at work but I'm not sure if it's the best approach, I would be interested in feedback. My use case was that we had credentials for servers out of band management system stored in Netbox, I used Ansible to lookup those passwords and update an SNMP community string.

**Comment by FragmentedPacket** [comment]
@ollybee I'm not sure i'd be the best resource for this as it's not something we currently use. Your use case sounds fine. If you run your playbook using this lookup plugin using `-vvvv` does the password show up? That would be my main concern with this is any sensitive info in cleartext.

**Comment by alexbarcelo** [comment]
I am very interested in this lookup plugin, but I don't know what's the status.

@ollybee are you currently working on it? Do you need help? Will it be merged? I can code, or test it, if it helps.

Seeing that there are NetBox components and NetBox inventory, this seems the last missing piece for a nice complete integration :)

**Comment by Akasurde** [comment]
@ollybee Thanks for the contribution. This is implemented via https://github.com/netbox-community/ansible_modules/commit/dd389495bfaa00debaaf50cbb99f6ed05d1d7eee.

**Comment by Akasurde** [comment]
Hi @ollybee, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/netbox-community/ansible_modules<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
