### PR TITLE
vmware_guest improvements: annotations & customvalues

### PR DESCRIPTION
**Pull request by nerzhul**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
vmware_guest improvements:
  * Idempotency fix on annotations permitting to change them on reconfiguration
  * Permit to set VMware customvalues attributes on VM
  * Gather annotation & customvalues and report it into module facts

New facts:
```
changed: [127.0.0.1] => {"changed": true, "failed": false, "instance": {"annotation": "this is a huge vm", "customvalues": {"components": "apache2", "datacenter": "production"}, "hw_guest_full_name": null, "hw_guest_id": null, "hw_interfaces": [], "hw_memtotal_mb": 1024, "hw_name": "test_vm_07", "hw_power_status": "poweredOn", "hw_processor_count": 1, "hw_product_uuid": "43214556-a8f6-82fc-b9d6-e51bd5a4065e", "ipv4": null, "ipv6": null, "module_hw": true}}
```

### CODE REVIEW

**Comment by dav1x** [comment]
@nerzhul I'm pretty sure that vmware requires an annotation to be removed before it can be re-written. 

https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.ConfigSpec.html

```
	
User-provided description of the virtual machine. Because this property is optional in the virtual machine configuration, it is necessary to pass an explicit empty string in a ConfigSpec object to remove an annotation that is already present in the VirtualMachineConfigInfo for a virtual machine.
Reconfigure privilege: VirtualMachine.Config.Rename 
```

**Comment by dav1x** [comment]
I guess it does this automatically. I tested with a VM powered on and off and works great!

LGTM

**Comment by nerzhul** [comment]
@dav1x API should do it then because i only call the current call to make it work properly

**Comment by nerzhul** [comment]
shipit

**Comment by dagwieers** [comment]
@nerzhul @jctanner I have been looking at `customvalues:`, but they are called *fields* within the VMware API and they are called *attributes* within the vSphere client itself.

https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.CustomFieldsManager.html

From the vSphere SDK, the scripts to modify these fields are also called: addVMCustomField.pl, setVMAgeCustomField.pl and queryVMCustomField.pl

So my preference is to also call it `fields:` within the interface to the user.
I took the liberty to put this in PR #20107 already.

**Pull request merged**
