### PR TITLE
Mutually reference Windows and non-Windows modules

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
To make it easier for Windows or non-Windows users to find the relevant
module information, we are mutually referencing both variants in their
documentation.

We are also adding a special note if a module works on both Windows and
non-Windows targets.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

Windows and non-Windows modules

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by gundalow** [comment]
If we are happy with this we should cherry pick into `stable-2.3` which will soon become the default docs.

**Comment by dagwieers** [comment]
@nitzmahone @jborean93 @jhawkesworth @trondhindenes Ready for review.

**Comment by dagwieers** [comment]
@gundalow I expect that the devel-branch documentation stays accessible to us too ?

**Comment by gundalow** [comment]
http://docs.ansible.com/ansible/win_command_module.html will redirect to the latest stable (currently `2.3`)

You will be able to select `devel` (or `2.2`) documentation

**Review by gundalow — APPROVED** [review]

**Review by nitzmahone — APPROVED** [review]
Potentially useful pattern when there is a corresponding Windows/non-Windows module, at least short-term. A metadata-based `see_also` kind of thing might not be a bad longer-term solution.

**Review by dharmabumstead — CHANGES_REQUESTED** [review]
Please change all instances of "look at" to "use".

**Comment by dagwieers** [comment]
@dharmabumstead I finally got around fixing this. Hope this is now acceptable for merging.

**Comment by dagwieers** [comment]
Shippable acting up again ? Close and re-open.

**Comment by mattclay** [comment]
@dagwieers The error is caused by the `uri` test depending on the `apt` test, which isn't running for your PR as you didn't change that module.

As a work-around until I can fix the issue, you can include `ci_complete` in your last commit message to bypass change detection. The tests will take longer, but should work.

**Comment by dagwieers** [comment]
@mattclay Thanks !

**Review by dharmabumstead — APPROVED** [review]
Thanks @dagwieers!

**Comment by dagwieers** [comment]
@mattclay Still fails, I probably did something wrong as it did not act on my commit message.
Probably just easier to just merge it. Everybody approved.

ci_complete

**Comment by dagwieers** [comment]
Close and re-open.

**Comment by dagwieers** [comment]
@gundalow Can this be merged ?

**Pull request merged**
