### PR TITLE
Add note to use script module rather than inline here documents

### LINKED ISSUE #32729: add cmd parameter + example to shell (and/or command?)
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
shell

##### ANSIBLE VERSION
```
ansible-playbook 2.4.1.0
  config file = 
  configured module search path = [u'/Users/lynchg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lynchg/.virtualenvs/a2x/lib/python2.7/site-packages/ansible
  executable location = /Users/lynchg/.virtualenvs/a2x/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### SUMMARY
When outputting heredocs using shell, it's necessary to use
```
- shell:
    cmd: |
      cat <<EOF
      This is a test.
      EOF
```
But this `cmd` param is not documented _anywhere_.

##### STEPS TO REPRODUCE
```
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - shell:
        cmd: |
          cat <<EOF
          This is a test.
          EOF
      register: result

    - debug:
        var: result
```

##### EXPECTED RESULTS
A `cmd` param should be listed in the `command` and/or `shell` modules.  It should also be listed as a possible argument.

##### ACTUAL RESULTS
It's not mentioned anywhere.  I found it from a stackoverflow answer - https://stackoverflow.com/a/40230416/4721729

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY
Fixes #32729 

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME
`shell.py`

##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by bcoca** [comment]
i would really suggest using script module instead

**Comment by samdoran** [comment]
Figured you would say that. 😉 

I was mainly adding at the request of the user in the original issue. Would it be better to add a note to the docs saying using `script` or `copy` with `content` rather than a here doc?

**Comment by bcoca** [comment]
script, copy+content requires still another 2 tasks on remote

**Comment by samdoran** [comment]
rebuild_merge

**Comment by ScottRochford** [comment]
The script module seems to return the results in (invalid?) JSON, which isn't exactly convenient for the quick-and-dirty use cases that the 'raw' module was ideal for.  Can that behaviour be changed?  I don't see an option for it.  Or do we have to hack some kind of JSON-stripper on to the end of each command line?  'python -m json.tool' fails to decode it, I suspect due to "host | RESULT =>" prefixes.

**Pull request merged**
