### PR TITLE
[stable-2.7] User - Fix shadow file parsing on AIX (#55230)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY
Backport of #55230 for Ansible 2.7

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`lib/ansible/modules/system/user.py`

### CODE REVIEW

**Comment by abadger** [comment]
@samdoran Once you get the stable-2.8 backport working, would you mind checking to be sure the relevant commit was also applied to stable-2.7 or taking a guess as to why stable-2.7 might already be safe (since the tests here are not failing).

**Comment by samdoran** [comment]
Sure thing.

**Comment by samdoran** [comment]
The issue was with the Fedora 29 container not having a timezone set and returning `n/a`. The test would fail when trying to return the original system timezone to `n/a`, which is invalid.

It looks like maybe the Fedora 29 container now has Etc/UTC as the default timezone. Maybe that was changed recently? I didn't find anything definitive in looking at the build history of the containers on the commit history of the Dockerfile repo.

Just to be on the safe side, I will also include the upstream test fix in this PR.

**Comment by abadger** [comment]
Cool.  Thanks.  Merged for the 2.7.11 release

**Pull request merged**
