### PR TITLE
Major rewrite of Netbox implementation support

### PR DESCRIPTION
**Pull request by BlackestDawn**
##### SUMMARY

Rewriting of Netbox implementation support by moving the shared parts (module_utils/net_tools/netbox/net_utils.py) into a class-object instead of a series of methods. By using a class-object lots of "logic" can be run "automatically" (by __init__()) and/or be moved into minimum viable versions of class-methods. This has significantly reduced the amount of "logic" needed in the actual modules and they can almost solely focus on the "logic" that is specific to themselves, mainly in preparing the data and how/what to use for specific steps in the overall process.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

netbox_device
netbox_interface
netbox_ip_address
netbox_prefix
netbox_site

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
Hey I really appreciate your effort on this. I'm no longer supporting the Netbox modules within core and they've been moved to Ansible Collections under fragmentedpacket/netbox_modules. There is a link to the Github for these as well.

I did a big rewrite to move everything into classes earlier this year and that is what the collections are using.

**Comment by FragmentedPacket** [comment]
This move was made due to Ansible planning to move most modules out of core and into Ansible Collections. I would love to keep you involved though with the collections if you're using them and any possible improvements you think they need

**Comment by Akasurde** [comment]
@BlackestDawn Thanks for the contribution.

**Comment by Akasurde** [comment]
Hi @BlackestDawn, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/netbox-community/ansible_modules<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
