### PR TITLE
SoftLayer: Added flavor option

### PR DESCRIPTION
**Pull request by MajeedMirza**
##### SUMMARY

Added flavor option to allow for use of SoftLayer flavor templates when creating new virtual machines. This new way of ordering machines allows for [suspend billing](https://cloud.ibm.com/docs/vsi?topic=virtual-servers-requirements#requirements) support where machines that are shut off have their billing suspended till they are turned back on. 

The `flavor` parameter can only be used if the `cpus` and `memory` parameters are left blank as those parameters are specified in the flavor template (e.g. `B1_1X4X25`).

See here for examples of ordering a vm with the flavor parameter:
https://softlayer-python.readthedocs.io/en/latest/api/managers/vs.html

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

SoftLayer flavor support

##### ADDITIONAL INFORMATION

To see all flavor options use the slcli command:
 `slcli vs create-options`

### CODE REVIEW

**Comment by mcltn** [comment]
+label shipit

**Comment by YuriG7** [comment]
shipit

**Comment by YuriG7** [comment]
It would be great to pull available flavours from SoftLayer and show them in the error message when an incorrect flavour is specified.

**Comment by MajeedMirza** [comment]
Stale PR, closing and reopening

**Comment by mcltn** [comment]
shipit

**Comment by MajeedMirza** [comment]
bot_status

**Comment by MajeedMirza** [comment]
bot_broken 
Maintainer has approved however has not been automerged and has not given a reason for why it has not been automerged. Requesting bot status shows `automerge: automerge shipit test failed` with no reason provided and no updated labels.

**Review by mcltn — APPROVED** [review]
approved

**Comment by mcltn** [comment]
shipit

**Comment by mattclay** [comment]
bot_status

**Comment by mattclay** [comment]
I've restarted tests since the results are stale.

**Comment by MajeedMirza** [comment]
bot_status

**Comment by mcltn** [comment]
right, and I thought there had been one, but maybe it was not from an
approved individual?

**Comment by bmcsheehy** [comment]
Shipit

**Comment by mcltn** [comment]
bot_status

**Comment by mcltn** [comment]
needs_revision

**Comment by mcltn** [comment]
shipit

**Comment by bmcsheehy** [comment]
shipit

**Comment by MajeedMirza** [comment]
bot_status

**Comment by mcltn** [comment]
@MajeedMirza We still need at least two more community reviewers for this request and comment shipit.

**Comment by MajeedMirza** [comment]
@mcltn It has been tagged as stale again, so will have to close and reopen the PR. Do you know if that means all the previous shipit comments will be lost again? Kind of ridiculous how long we've been trying to get this PR to go through.

**Comment by kinanjaouni** [comment]
shipit

**Comment by YuriG7** [comment]
shipit

**Pull request merged**
