### PR TITLE
Added parted module

### PR DESCRIPTION
**Pull request by ColOfAbRiX**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

parted
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 89c826df9d) last updated 2016/09/16 15:12:47 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 48d932643b) last updated 2016/09/16 15:13:15 (GMT +000)
  lib/ansible/modules/extras: (feature/gluster_volume 95f4f52167) last updated 2016/09/19 16:44:19 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

The module is a wrapper around the linux command parted intened to work with disk partitions.
The module implements the parted commands as described by command documentation. 
It can be used to read information about the existing configuration, create, update or remove partitions as with the parted command itself

### CODE REVIEW

**Comment by ColOfAbRiX** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2971
**UPDATE**: This pull request lost the reference to my original repository, so I opened a new one her https://github.com/ansible/ansible/pull/20399

**Comment by tasleson** [comment]
@ColOfAbRiX 

I've been playing around with this a bit and have the following observations:

1. The format strings are not compatible with python 2.6.6 (EL6)
eg.
```diff
-                    script += "set {} {} on ".format(number, flag)
+                    script += "set {0} {1} on ".format(number, flag) 
```

2. When you query an empty device, the module writes an empty dos label to the disk.  Do we want to write to a disk on a query?

eg. when I try this with a blank disk
```yaml
- name: read current partitions on a device
  parted: device=/dev/sdb
```
I get
```bash
$ ansible -b -i $HOME/ai testing -m parted -a 'device=/dev/sdb'
f25 | SUCCESS => {
    "changed": true, 
    "partition_info": {
        "generic": {
            "dev": "/dev/sdb", 
            "logical_block": 512, 
            "model": "ATA VBOX HARDDISK", 
            "physical_block": 512, 
            "size": 8388608, 
            "table": "msdos"
        }, 
        "partitions": []
    }, 
    "script": "unit KiB mklabel msdos"
}

```
3. The example:

```yaml
- name: create a new primary partition
  parted: device=/dev/sdb number=1 state=present
```
Doesn't work for me regardless if I have 1 or more partitions on the device

4. The partition remove example **does** work for me

5. The function `get_device_info` doesn't check the exit code.  If you make a mistake like I did and not elevate to root privs when running the module you get a nice python stack trace.  However, if you add a check then the code fails the other corner case where there is nothing on the disk as parted will return some information, but exit with a non-zero exit code.

I'm wondering if I'm doing something wrong as I'm not getting the same success as others.  FYI I'm new to ansible, and ansible development so that's entirely possible.  I'll dig into more of the code this week to see if I can understand where I'm going wrong.

Thanks!

**Comment by ColOfAbRiX** [comment]
Amazing feedback, thank you. I'll review each point and come back.
I've got only one problem: after Ansible merged the ansible-modules-extra repository I don't know how I can make changes to this pull request. Do you know what I can do?

**Comment by gundalow** [comment]
Reviews welcome on https://github.com/ansible/ansible/pull/20399

**Comment by ColOfAbRiX** [comment]
@tasleson , to answer each of your points:

1. I've amended the code
2. No, we don't want that. I've added a new default value for `state`, which is the empty string "". That makes the module to fetch only the device info
3. I missed a required parameter for the partition, that is `part_type`. I set a default value for it, so even when it's missing a primary partition is created.
4. Good :)
5. Good point, now it does check for the return code.

As stated in my previous comment, this pull request lost the reference to the repository so that I can't update it. I created a new pull request with the changes here https://github.com/ansible/ansible/pull/20399. Please use the code over there as well as comments.

**Pull request closed without merging**
