### PR TITLE
[2.10] Docsite backports of 71938, 71907

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
[2.10] Docsite backports of
#71938 
#71907 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docsite

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @samccann @acozine

**Comment by acozine** [comment]
rebuild_merge

**Comment by acozine** [comment]
Thanks @Andersson007 for the backport.

**Pull request merged**
