### PR TITLE
fix issue [ get_url does not change mode when checksum matches ]

### LINKED ISSUE #29614: get_url does not change mode when checksum matches
From @sfilipov on 2016-10-04T08:12:37Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Host: Ubuntu 16.04
Managed: Ubuntu 14.04
##### SUMMARY

`get_url` does not change mode when the checksum of the file matches. If the file needs to be downloaded due to the checksum not matching, then after download, the correct mode will be set.
##### STEPS TO REPRODUCE
1. Define a `get_url` task where destination is a file and set the checksum to the sha256 of the file. After the first run, the file will be downloaded and the checksum will match.
2. Now add a `mode` argument to `get_url` such that it differs from the one on the downloaded file and Ansible needs to make a change.
3. Rerun task.

```
- name: Download file
  get_url:
    url: https://xxxxxxxxxxx
    dest: /usr/local/bin/some_executable
    checksum: "sha256:somehash"
  become: yes

- name: Mode needs to be changed
  get_url:
    url: https://xxxxxxxxxxx
    dest: /usr/local/bin/some_executable
    checksum: "sha256:somehash"
    mode: 0755
  become: yes
```
##### EXPECTED RESULTS

Mode is changed on second run to match one described in task -- task is changed
##### ACTUAL RESULTS

Changing mode is short circuited due to checksum match -- task OKs

Copied from original issue: ansible/ansible-modules-core#5141

### PR DESCRIPTION
**Pull request by ptux**
##### SUMMARY

Fixes #29614

- get_url does not change mode when checksum matches

I just have modified the program flow.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

get_url.py

##### ANSIBLE VERSION

```
ansible 2.7
```

### CODE REVIEW

**Comment by ptux** [comment]
@jpmens

I'm going to implement #27617 too.
So, it would be great if you review this PR ASAP.

**Comment by jpmens** [comment]
shipit

**Comment by ptux** [comment]
shipit, please.

**Comment by samdoran** [comment]
@ptux Please create a changelog fragment. See [fragments](https://github.com/ansible/ansible/tree/stable-2.6/changelogs/fragments) for examples.

**Comment by ptux** [comment]
@samdoran 
thanks for your comment.
cloud you check this PR again?

this PR does not fix #27617.
I'll open another PR for #27617.
so, i have changed the SUMMRY back.

**Comment by samdoran** [comment]
@ptux Apologies for misreading. Thanks for correcting the summary.

**Comment by samdoran** [comment]
@ptux I added tests to cover this scenario and verified your fix. I'll merge this once the tests pass.

**Comment by samdoran** [comment]
Please create a [backport PR](https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process) for this to be included in previous versions.

**Comment by ptux** [comment]
@samdoran 

Thanks for the commit for test code.
I'll read it in order to write test code myself next time.

Also, I'm going to create a backport PR to 2.6 which is [Supported (security and general bug fixes)].

**Comment by samdoran** [comment]
@ptux This can be backported to both 2.6 and 2.5 since those are both receiving bugfixes.

**Comment by ptux** [comment]
@samdoran I see.

**Pull request merged**
