### PR TITLE
if users are None/empty, dont assume sameness (#58875)

### PR DESCRIPTION
**Pull request by bcoca**
(cherry picked from commit 4ef2545eb5d661566e06629015967c2d1b8924e3)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

action

### CODE REVIEW

**Review by jamescassell — APPROVED** [review]
shipit

**Comment by sivel** [comment]
@bcoca I'd just recommend cherry-picking `74ac229` into this PR:

`git cherry-pick -x 74ac229`

**Review by jamescassell — APPROVED** [review]
works for me

**Comment by abadger** [comment]
mattclay knows about the rhel 7.6 failures which seem unrelated to this PR.  Going to merge for 1.8.3

**Pull request merged**
