### PR TITLE
In the script action: Get around a Python bug.

### PR DESCRIPTION
**Pull request by jphalip**
This is a fix for issue #4256.

### CODE REVIEW

**Comment by jimi-c** [comment]
Thanks, I'll review this as soon as possible.

**Comment by mpdehaan** [comment]
Thanks for this!

As a minor code review note, when something can be written as a list comprehension, we prefer it that way to make it more readable.
-        tokens = map(lambda s: s.decode('UTF8'), tokens)

Should likely be:

tokens = [ s.decode('UTF8') for s in tokens ]

This is something we can take care of though, just wanted to point it out.

**Comment by jphalip** [comment]
Sure, no problem! I'll update the PR in a minute.

**Comment by jphalip** [comment]
PR updated, thanks!

**Comment by jctanner** [comment]
Bug and patch verified, merging pull request.

**Pull request merged**
