### PR TITLE
Concatenate ini files in inventory directory

### PR DESCRIPTION
**Pull request by maethor**
This pull request follows a discussion on the project mailing list : https://groups.google.com/forum/#!topic/ansible-project/d51VnOdLa_o

When parsing an inventory in a directory, all the "ini" files are now concatenated in a temp file before being parsed all in one shot.

This allows to declare objects in a file and reference them in the next file, to efficiently split an "ini" inventory in many files. For instance : `prod/01_hosts`, `prod/02_role_groups`, `prod/03_client_groups` and `prod/04_realm_groups`

### CODE REVIEW

**Comment by g-k-r** [comment]
this might solve #5749 as well

**Comment by maethor** [comment]
This might correct many bugs.

In fact, this just recreate the natural behavior we could expect when splitting an inventory file into many files in a directory : just concatenating all the parts before parsing them in one shot.
All the parsing is completely delegate to the "file" parser, which can only reduce the sources of bugs.

**Comment by bcoca** [comment]
wouldn't using fileintput.intput( initfiles_list) achieve the same?

**Comment by bcoca** [comment]
hmm, actually this breaks my setup, most of my files start without a
section, just hosts directly, if concatenated, the first host of file B get
assigned to last group of file A.

**Comment by maethor** [comment]
Of course, I didn't thought about that. :(
Do you see a workaround ?

I don't know about fileintput.intput( initfiles_list).

The other solution is to recreate the "context" in InventoryParser, by passing "groups" and "hosts" to the constructor. This way, each InventoryParser would be aware of the groups and hosts already discovered by DirectoryParser. Unlike my first patch, this would even includes groups and hosts discovered in other types of inventories (scripts, other directories, etc.).

What do you think ?

**Comment by bcoca** [comment]
I see 2 workarounds:
a) don't support files with ungrouped hosts
b) automatically assign a group per filename

but if we look at changing the implementation, make the parser not
aggregating all parses at the end, but incremental, you'll get the
functionality you desire and not break existing inventory layouts.

**Comment by srgvg** [comment]
Just some extra thoughts.
- this talks about grouping ini files in a directory; what about the ini files in a subdirectory?
- with this update, logic depends more on the sorting of the ini file names; this might change the outcome of certain setups
- a pet peeve of mine, is the inner Inventory logic that calculates the group depth, which is not 100% correct (sometimes a father group gets the same depth as a children group), although so far the practical implications of this are none to very limited ( I recall just having once had to slightly rewrite groups and children groups in another order, to fix the right variable precedence); mentioning this as the parsing of InventoryDirs influences this.
- right now, the logic in inventorydir, kind of reparses all groups and hosts, and sometimes you get a different inventory (different values for group.depth) by putting eg a script in a dir and calling the dir as the inventory, as compared to when you would cal the inventory script directly (this is also valid if replace inventory script here with a subdirectory or an ini file)

Slightly off topic: vars_plugins now are called each time for every host, which has a significant  performance penalty.

I personally think the ansible.Inventory might benefit of a more general rewrite. Just thinking out loud.
How about reimplementing the parsing of ini files and directories (and the current group_vars vars_plugin) in a separate inventory script? This would have the benefit of keeping current code backwards compatible, and to experiment with other ways of parsing inventory?

**Comment by maethor** [comment]
Sounds great, yes, but I really don't have time to do a complete rewrite. Sorry.

I think performance is not a big deal here, because this is executed just one when the user launch ansible.

**Comment by srgvg** [comment]
Those were just some comments TBD, I didn't intend to mean you'd have to code it :) If people are interested in discussing these, this needs to happen on the mailing list of course.
(Performance remark was more about the vars_plugins, not specific to the inventory host/groups themselves.)

**Comment by jctanner** [comment]
@maethor we can't accept this unless the issues @bcoca referenced are resolved.

**Comment by mpdehaan** [comment]
Closing per the above.

**Comment by mpdehaan** [comment]
@sergevanginderachter -- discussion about other properties of inventory in this ticket would be better brought up on the development mailing list where there can be a wider discussion, don't infer closing this has any bearing on those above comments.

**Pull request closed without merging**
