### PR TITLE
Completely rewrite the full_skip callback plugin

### PR DESCRIPTION
**Pull request by whitequark**
##### SUMMARY

The existing plugin was unreliable: it would often reorder statements
in confusing ways. For example, the following task:

```
- name: install mysql
  apt: name={{item}} state=present
  with_items:
  - python-mysqldb # for ansible
  - default-mysql-server
```
would result in the following output:

```
ok: [localhost] => (item=[u'python-mysqldb', u'default-mysql-server'])

TASK [prestashop : install mysql] **********************************************************************
```

if the previous task was skipped as well because of a logic error.

In addition, it reimplemented `_print_task_banner` incompletely,
did not take the 'free' play strategy into account, and was somewhat
confusingly written.

All of this is now fixed. I also took the liberty of changing
the verbosity threshold for printing the skipped tasks to 1,
since that shows the *reason* for skipping the task, and it seems
logical to display the task itself also.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
plugins/callback/full_skip

### CODE REVIEW

**Comment by whitequark** [comment]
Rebased.

**Comment by scottsb** [comment]
Since part of the aim here is clarity, would it be possible to either rename the filter/flush/anul/quash methods to be clearer or else add a bit of inline documentation explaining their purpose? Without that I think this just keeps the clarity at about the same level, just with a different implementation.

**Comment by whitequark** [comment]
This PR has been stale for half a year without anyone from Ansible even commenting on it. Why would I waste any more time on this? Clearly Ansible doesn't care about contributions.

**Comment by bcoca** [comment]
@whitequark we do care about submissions, but for community plugins like this one we normally deffer to the author/maintainer(s) and don't get involved directly, the core team is already enough of a bottleneck.

Failing that we do have IRC and mailing lists as well as IRC meetings for those that need extra help in getting a review.

**Comment by whitequark** [comment]
Oh, that explains things. I had no idea there is any such process, is it documented anywhere?

**Comment by bcoca** [comment]
http://docs.ansible.com/ansible/latest/community/index.html though we need to update module to 'modules and plugins'

**Pull request closed without merging**
