### PR TITLE
Update DigitalOcean dynamic inventory to API v2

### PR DESCRIPTION
**Pull request by alezkv**
Update to API version 2.
In API v 2 to get inventory is done in one request, so there is no need to cache any more.

### CODE REVIEW

**Comment by bcoca** [comment]
i'm not sure that removing the cache is a good thing, specially when people invoke playbooks frequently.

**Comment by oryband** [comment]
digitalocean's new team account support work only with v2. Furthermore, using v1 doesn't return any error - just an OK with empty droplets list, which is very misleading.

Please update to v2, this is a very big deal.

**Comment by oryband** [comment]
@ofir-petrushka @avivl @fuzzyami

**Comment by bcoca** [comment]
im tempted to make this a do_v2 inventory plugin, or is there no case where someone would need to use the v1 version?

**Comment by oryband** [comment]
@bcoca isn't v2 supposed to do what v1 does and more? we should just move to use v2 imo

**Comment by bcoca** [comment]
I do not know, that is why I'm asking, not everyone keeps backward compatibility between versions, even when they try it is not normally perfect.

**Comment by oryband** [comment]
@bcoca well, i guess the answer is here:
- https://developers.digitalocean.com/
- https://www.digitalocean.com/company/blog/apiv2-officially-leaves-beta/

**Comment by alezkv** [comment]
more precise answer is here:
https://developers.digitalocean.com/documentation/changelog/api-v1/sunsetting-api-v1/

> We’re not going to pull the rug out from under you. In order to give everyone time to port their tools, version 1 will not be turned off until November 1st 2015.

**Comment by oryband** [comment]
@izhukov even though they wrote this, v1 completely doesn't work **now** for users who are part of a team.

**Comment by bcoca** [comment]
OK, seems that this cannot break it more than it is already but will enable people to use it.

**Pull request merged**
