### PR TITLE
influxdb_user: Fixed unhandled exception on invalid login credentials

### LINKED ISSUE #50131: Influxdb_user yields an unhandled exception when presented with invalid login credentials
##### SUMMARY
Influxdb_user yields an unhandled exception when presented with invalid login credentials

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Influxdb_user

##### ANSIBLE VERSION
devel branch

##### STEPS TO REPRODUCE

```yaml
---
- hosts: local
  connection: local
  tasks:
    - name: Add test user
      influxdb_user:
        username: admin
        password: invalid_admin_pw
        user_name: test
        state: present
```

##### EXPECTED RESULTS
Graceful failure

##### ACTUAL RESULTS
```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1545206143.83-41094482064230/AnsiballZ_influxdb_user.py", line 113, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1545206143.83-41094482064230/AnsiballZ_influxdb_user.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1545206143.83-41094482064230/AnsiballZ_influxdb_user.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_influxdb_user_payload_veBDH1/__main__.py", line 197, in <module>
  File "/tmp/ansible_influxdb_user_payload_veBDH1/__main__.py", line 164, in main
  File "/tmp/ansible_influxdb_user_payload_veBDH1/__main__.py", line 92, in find_user
  File "/home/vagrant/.local/lib/python2.7/site-packages/influxdb/client.py", line 769, in get_list_users
    return list(self.query("SHOW USERS").get_points())
  File "/home/vagrant/.local/lib/python2.7/site-packages/influxdb/client.py", line 416, in query
    expected_response_code=expected_response_code
  File "/home/vagrant/.local/lib/python2.7/site-packages/influxdb/client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 401: {"error":"authorization failed"}
```

### PR DESCRIPTION
**Pull request by mdrose**
##### SUMMARY
Fixes  #50131

Catches invalid authentication errors when searching for users and exits properly.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
influxdb_user

### CODE REVIEW

**Review by gundalow — APPROVED** [review]
Thank you for the fix, looks good

**Comment by winem** [comment]
There are no negative tests at all for this module. I would love to see some negative tests - and volunteer to do this during christmas holidays although the error message is pretty descriptive already.

**Review by resmo — APPROVED** [review]
shipit

**Comment by resmo** [comment]
I would be okay, to merge now and would appreciate your PR for extended test use cases. @gundalow ?

**Pull request merged**
