### PR TITLE
eos test fix rollup

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Backports of fixes landed to 2.8 in an attempt to make 2.7 tests pass

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

eos_eapi
eos_l2_interface

### CODE REVIEW

**Review by pabelanger — APPROVED** [review]
This makes stable-2.7 green for eos network-integration jobs, for example:

  https://dashboard.zuul.ansible.com/t/ansible/build/ad4a1387607d4e3db4956d73cf78f2d8

**Comment by abadger** [comment]
There's a discussion ongoing in the networking team to figure out whether we want to consider these things critical bugs or disable zuul on this subset of tests for stable-2.7.  @ikhan will discuss with me and we'll eventually either close this or try to merge all of these similar things for a single new 2.7.x release.

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
stable-2.7 tests passed properly.

**Comment by abadger** [comment]
The decision from the networking team leadership is that none of these bugs qualify as critical so we'll have to continue testing stable-2.7 releases manually rather than enabling zuul for 2.7.x

**Pull request closed without merging**
