### PR TITLE
mysql_replication: add channel parameter

### LINKED ISSUE #29311: mysql_replication: feature - Support Multi-Source Replication
From @paihu on 2016-05-07T03:33:27Z

##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

[module: database/mysql/mysql_replication.py]
##### SUMMARY

MySQL support Multi-Source Replication ( https://dev.mysql.com/doc/refman/5.7/en/replication-multi-source.html ), but this module isn't support Multi-Source Replication.

Can you add a new option (called "channel",who accept string input) to this module?

exmaple

```
# Change master to master server 192.168.1.1 for channel "master-1"
- mysql_replication: mode=changemaster master_host=192.168.1.1 channel=master-1
```

Copied from original issue: ansible/ansible-modules-extras#2180

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
mysql_replication: add channel parameter

fixes https://github.com/ansible/ansible/issues/29311

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/mysql/mysql_replication.py```

##### EXAMPLES
```
- name: Stop replication in channel master-1
  mysql_replication:
    mode: stopslave
    channel: master-1
```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by HOSTED-POWER** [comment]
looks good, shipit!

**Comment by Andersson007** [comment]
@HOSTED-POWER thank you  for review! shipit needs to be in a separate line, would be cool if you add a comment with standalone shipit inside

**Comment by HOSTED-POWER** [comment]
ok sorry :)

shipit

**Comment by Andersson007** [comment]
@HOSTED-POWER thank you!

**Comment by gundalow** [comment]
@Andersson007 Thank you for this feature and tests
@HOSTED-POWER Thank you for your review.

Merged into `devel` for release in Ansible 2.10

**Comment by Andersson007** [comment]
@gundalow thank you for merging!

**Comment by HOSTED-POWER** [comment]
BTW I can add that we use it in production now, the parts we are using are working properly for sure :)

**Comment by Andersson007** [comment]
@HOSTED-POWER thanks for the feedback! :)

**Comment by Andersson007** [comment]
@HOSTED-POWER #63547 please look, probably it could be interesting for someone who use MySQL

**Pull request merged**
