### PR TITLE
s3: added option to set server-side encryption

### PR DESCRIPTION
**Pull request by ghost**
This addition exposes the 'encrypt_key' option in Boto, enabling automatic server-side encryption by S3.

Reference: http://boto.readthedocs.org/en/latest/ref/s3.html#boto.s3.key.Key.set_contents_from_file

### CODE REVIEW

**Comment by lwade** [comment]
It seems like this would break for s3-compatible implementations.  I don't think I'm aware of any s3-compatible platform which supports encrypt_key

**Comment by atlashealth** [comment]
@lwade, how about we move non-S3 implementations into their own modules? You'll notice that Boto handles other storage providers in separate classes. Otherwise, we're sacrificing better security in exchange for abstraction.

**Comment by lwade** [comment]
Other storage providers (like Glacier and GCS) don't use the same API. I don't think that's a good idea as it just adds bloat and defeats the point of the commonality of the s3 interface.  As with the ec2 module I think its a case of constructing parameters based on what parameters have been chosen, rather than making them mandatory, whether false or not.  Either that or a simple conditional or somesuch in the upload_s3file function which checks for this parameter (if encrypt_key).  Ultimately we have folks who may be using this against Eucalyptus (like we do), RiakCS, Swift, HCP etc etc.

**Comment by atlashealth** [comment]
@lwade - that sounds like a reasonable approach. We'll tackle that this week and will append this PR.

**Comment by lwade** [comment]
Thanks @atlashealth

**Comment by atlashealth** [comment]
@lwade, please take a look at cd3e6e4a0fc324b4642f2d085ad87a8375b99d1b. What I did is replace the previous "encrypt_key" argument with an optional hash called "provider_options." The hash can be populated with the values supported by boto's set_contents_from_filename method. 

I ran several integration tests locally - with and without provider_options set - looks good at my end.

**Comment by lwade** [comment]
Hi @atlashealth, sorry for the wait.  Let me take a peek.

**Comment by lwade** [comment]
Looks good! Thanks for doing this, being able to pass some of those additional parameters will be useful and it doesn't break a baseline of interop with other s3-compatible providers.

**Comment by lwade** [comment]
One thing I meant to add here, it would be great to put an example in the examples section.

**Comment by mpdehaan** [comment]
Hi everyone,

We've just gotten through a large wave of crazy things and are looking to merge things like this, but yes, we will need an example.

Can this be updated?

I would also change "version_added" to "1.8" at this time.

Otherwise, looks good.  I guess I would say if it's only one parameter, a boolean versus "provider_options" might make sense, but I'll wait for the example.

Thank you!

**Comment by philm** [comment]
Sorry, we converted our @atlashealth GitHub account to an "organization" and I lost track of this one. Will add to my list.

**Comment by philm** [comment]
All set!

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Pull request closed without merging**
