### PR TITLE
Fix for #6353 adding a newline between assembled files

### PR DESCRIPTION
**Pull request by pgehres**

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks like this might result in extra newlines when the delimiter is set:

```
   if delimit_me and delimiter:
        # un-escape anything like newlines
        delimiter = delimiter.decode('unicode-escape')
        tmp.write(delimiter)
        # always make sure there's a newline after the 
        # delimiter, so lines don't run together
        if delimiter[-1] != '\n':
            tmp.write('\n')
    if os.path.isfile(fragment):
        tmp.write(file(fragment).read())
        # always put a newline between fragments
        tmp.write('\n')
```

**Comment by mpdehaan** [comment]
This otherwise looks like it will fix the problem.   Can you add a "if not delimiter" in there before the extra \n write at the bottom?

**Comment by pgehres** [comment]
So, the only way I see that happening is if delimiter is "\nDELIMITER" otherwise you just end up with the newline between the delimiter start and the previous fragment.

On a similar note, this would result in an extra "\n" at the end of the file. I could reuse "delimit_me" to add the "\n" between files at the top of the loop, similar to the way the delimiter works. Thoughts?

**Comment by mpdehaan** [comment]
So I was just testing this as follows:

```
root@llamacube:~/ansible# ansible -i "127.0.0.1," 127.0.0.1 -m "assemble" -a "src=/tmp/inputs dest=/tmp/dest delimiter='---'" -c local
```

/tmp/inputs/bar
    bar
    bar
    bar 
    <EOF>

/tmp/inputs/baz

```
baz baz no newline<EOF>
```

/tmp/inputs/foo

```
foo new newline<EOF>
```

/tmp/inputs/glorp

```
 glorp
 glorp
 glorp
 <EOF>
```

And when I run this before your change, I get the following output:

```
bar
bar
bar with newline

---
baz baz no newline
---
foo no newline
---
glorp?
glorp?
glorp?
```

And when I run it with your change, I get what seems to be redundant newlines:

```
bar 
bar
bar with newline


---
baz baz no newline

---
foo no newline

---
glorp?
glorp?
glorp?
```

From the above, the original behavior seems to make more sense to me.   I also tested this without the delimiter on the development branch...

The devel branch HEAD produces:

```
bar
bar
bar with newline

baz baz no newline
foo no newline
glorp?
glorp?
glorp?
```

The version you have produces the following:

```
bar
bar
bar with newline


baz baz no newline

foo no newline

glorp?
glorp?
glorp?
```

Apologies on the crazy test examples.

From the above, it seems like the development branch head version does not result in extra newlines, but also that with the above patch applied the newlines are inserted too frequently.

**Comment by pgehres** [comment]
Weird.  I'll test again against 1.5.3 and devel and see what I get. Thanks.

**Comment by mpdehaan** [comment]
See my comment on the other ticket, there's a commit on March 6th that may have addressed this (to devel only, most likely).

If that works, we can slate for inclusion in the next dot release.

**Comment by mpdehaan** [comment]
This fix does appear to exist on the 1.5.3 branch.

**Comment by jimi-c** [comment]
Closing, as the other PRs above were merged instead (which included this work). Thanks!

**Pull request closed without merging**
