### PR TITLE
Add workaround for evasive in apache2_module

### LINKED ISSUE #22635: Apache Enable Module... Module fails if already enabled
Verify first that your issue/request is not already reported on GitHub.
Also test if the latest release, and master branch are affected too.
>>> DONE , using latest version from pip... will try and use latest from source.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
http://docs.ansible.com/ansible/apache2_module_module.html

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides

```

##### SUMMARY
Ansible apache module fails if evasive is already enabled, only seems to be evasive.

##### STEPS TO REPRODUCE

[https://github.com/ShadeySecurity/pyAssetContext/blob/master/playbooks/install-pyAssetContext.yml](url)

##### EXPECTED RESULTS

I expected an ok / no change
##### ACTUAL RESULTS

Failed due to already existing

```
TASK [Apache Modules Setup] ****************************************************
ok: [127.0.0.1] => (item=ssl)
ok: [127.0.0.1] => (item=proxy)
ok: [127.0.0.1] => (item=proxy_http)
ok: [127.0.0.1] => (item=headers)
ok: [127.0.0.1] => (item=expires)
ok: [127.0.0.1] => (item=wsgi)
ok: [127.0.0.1] => (item=rewrite)
ok: [127.0.0.1] => (item=security2)
...ignoring
failed: [127.0.0.1] (item=evasive) => {"failed": true, "item": "evasive", "msg": "Failed to set module evasive to enabled: Module evasive already enabled\n", "rc": 0, "stderr": "", "stdout": "Module evasive already enabled\n", "stdout_lines": ["Module evasive already enabled"]}
```

### PR DESCRIPTION
**Pull request by robinro**
##### SUMMARY

* Fixes #22635, allow to load/unload evasive module
* Clean up workarounds for php/shib
* Add test for evasive workaround
* Remove use of re module, since all searches work with native python

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
apache2_module

##### ANSIBLE VERSION
* ansible 2.2
* devel

### CODE REVIEW

**Comment by n0trax** [comment]
I think the regex in the `_run_threaded` method will not work without `re`...i'm not sure if the number of spaces is always the same in different apache versions.

The workaround list is much better to extend than the previous version. I'm fine with that.

If we still need `re`, we can adjust the return statements.
- _run_threaded:
    `return bool(re.search(r'threaded:[ ]*yes', stdout))`
- _module_is_enabled:
    `return bool(re.search(name, stdout))`

**Comment by robinro** [comment]
@n0trax I readded the re package for threaded and php to not change the behavior there.
Also there are unit tests now for the name replacements that we encountered so far.

**Comment by n0trax** [comment]
@robinro Look's nice :smile:

Just two things. You can replace `searchstring` (line 146/147) with `replace_name(name)`. The prefixed blank is not needed.
How about renaming `replace_name` method into `create_apache_identifier` or something similar?

**Comment by robinro** [comment]
I renamed the function to `create_apache_identifier`. I'd like to keep the leading space in the searchstring, since it avoids maching some part of a modulename (e.g. `alias_module` vs. `vhost_alias_module`).

**Comment by n0trax** [comment]
@robinro 
You're right...we should leave the blank.

**Comment by n0trax** [comment]
shipit

**Comment by robinro** [comment]
shipit
Does @ansibot need ones own confirmation to ship a PR?

**Pull request merged**
