### PR TITLE
Show the offending file name with the include + with_items error

### PR DESCRIPTION
**Pull request by veeti**

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm fine with this addition, though can you reformat this to remove the one-line if?   This is something we try to avoid in coding standards.   

Thanks!

https://github.com/ansible/ansible/blob/devel/CODING_GUIDELINES.md

**Comment by veeti** [comment]
Done.

**Comment by veeti** [comment]
Ping?

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
