### PR TITLE
ACME: add support for IP identifiers

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
According to https://tools.ietf.org/html/draft-ietf-acme-ip-05. First interoperability tests with letsencrypt/pebble#221 are looking good. This is essentially the `acme_certificate` part of #53228.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
acme_certificate

### CODE REVIEW

**Comment by felixfontein** [comment]
I've just tested this against the v1 and v2 staging servers of Let's Encrypt, that still works (at least for `http-01` validation).

**Comment by felixfontein** [comment]
@mattclay I want to preserve the trailing whitespaces in the OpenSSL outputs which are part of the unit tests. I've tried to skip the pep8 tests for this unit tests (df7e282d87f5cdf0d01cbe65492e2412ea7ca470), but this apparently didn't work. Do you know what went wrong? I could also do this by adding `""" + r"""` at the end of the line. Is this maybe a better approach (because it also will stop random editor settings to cut them off)?

**Comment by mattclay** [comment]
@felixfontein Definitely don't skip the pep8 checks. For large static content like that, I'd put it in a separate file and load it during the test instead of trying to embed it in the code.

**Comment by felixfontein** [comment]
@mattclay I've rearranged it as follows: a27afa7349477b57637b9f037cf2d04d19647d90 Is the folder structure ok? (I.e. will the CI system find the tests if lib/ansible/module_utils/acme.py is changed?)

**Comment by mattclay** [comment]
@felixfontein Yes, the folder structure is correct. The unit tests to run will be determined based on import analysis, so there's no issue there. It's actually more important that the fixtures are in the correct location so changes to them will run the tests. Those are OK as well.

You can check with the following commands:

`ansible-test units --changed-path test/units/module_utils/acme/fixtures/cert_1.pem -e`
`ansible-test units --changed-path lib/ansible/module_utils/acme.py -e`

Those will show what tests will run based on files changing.

**Comment by felixfontein** [comment]
@mattclay great, thanks a lot!

**Comment by felixfontein** [comment]
ready_for_review

**Review by resmo — APPROVED** [review]
don't see anything to block this from getting in. Good job.

shipit

**Comment by felixfontein** [comment]
@resmo thanks for reviewing and merging!
@mattclay thanks for helping with the tests!

**Pull request merged**
