### PR TITLE
Zabbix host tags & macros integration tests + zbx server version increase

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
Increased Zabbix server version to 4.4 to allow testing of host tags (not supported in lower version) and made some compatibility adjustments in other roles to work with newer version.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
test/integration/targets/setup_zabbix
test/integration/targets/zabbix_host
test/integration/targets/zabbix_template

### CODE REVIEW

**Comment by D3DeFi** [comment]
Will fail until #66996 is merged

**Comment by D3DeFi** [comment]
ready_for_review

**Comment by sky-joker** [comment]
Looks good to me!

shipit

**Comment by D3DeFi** [comment]
> 
> 
> Looks good to me!
> 
> shipit

Thanks @sky-joker

**Comment by gundalow** [comment]
Thanks all

**Pull request merged**
