### PR TITLE
Add support for modifying connection zones in nmcli module

### LINKED ISSUE #21591: RFE: modify connection zones in nmcli module
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
nmcli module

##### ANSIBLE VERSION
```
devel branch, as of Feb 17 2017
```

##### SUMMARY
The Ansible `nmcli` module has no way to modify the "zone" of an interface.

It would be great if I could do something like this to set the zone on the `docker0` interface:

```yaml
- nmcli:
    conn_name: docker0
    zone: MyZone
```

but the "zone" parameter is not yet supported. I have to run a command like `nmcli connection modify docker0 connection.zone MyZone`

### PR DESCRIPTION
**Pull request by oussemos**
##### SUMMARY

Added code for modifying connection zones in nmcli module
pep8 fixes in test_nmcli.py file.
Fixes: #21591

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
nmcli

### CODE REVIEW

**Comment by oussemos** [comment]
cc @Akasurde

**Comment by Akasurde** [comment]
cc @ssahani

**Comment by corbinstuard** [comment]
Does this need to be tested? +1

**Comment by rcny** [comment]
Any news when will this be available?

**Comment by ph0en** [comment]
@oussemos  could you please update PR?

**Comment by Akasurde** [comment]
Hi @oussemos, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
