### PR TITLE
Update ce_bgp_neighbor_af to fix bugs

### PR DESCRIPTION
**Pull request by yanzhangi**
##### SUMMARY

Add some update statements

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible/modules/network/cloudengine/ce_bgp_neighbor_af.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by hwDCN** [comment]
LGMT

**Comment by hwDCN** [comment]
+1

**Review by yuandongx — APPROVED** [review]
+1

**Comment by xuxiaowei0512** [comment]
bot_status

**Pull request merged**
