### PR TITLE
ec2.py boto_profile option for multiple AWS account credentials in boto file

### PR DESCRIPTION
**Pull request by ghost**
Add an ec2 inventory option "boto_profile" that allows
the use of boto profiles for separating credentials as
specified in

http://boto.readthedocs.org/en/latest/boto_config_tut.html

### CODE REVIEW

**Comment by willthames** [comment]
#5987 allows an EC2_PROFILE environment variable to be set to configure the profile.

**Comment by ghost** [comment]
Yes it does. I prefer not encoding static information in environment variables. With a setting in the .ini file, you can have inventory directories with ec2.py and ec2.ini for multiple AWS accounts where hosts might live.

Not to say the approach of #5987 is wrong, ideally both would be supported. That is the common paradigm with boto/aws CLI utilities.

**Comment by amenonsen** [comment]
@jeffb-bt @jalaziz I guess this PR should be closed in favour of #9130 now?

**Comment by gregdek** [comment]
Closing in favor of #9130 (which I hope gets merged soon!)

**Pull request closed without merging**
