### PR TITLE
nxos_logging: add example using aggregate

### PR DESCRIPTION
**Pull request by smolz**
add example using aggregate
+label: docsite_pr
+label: issue ansible/community#311

##### SUMMARY

add example using aggregate

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

nxos_logging
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/ansible.cfg
  configured module search path = [u'/usr/local/lib/python2.7/dist-packages/napalm_ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by trishnaguha** [comment]
cc @IPvSean

**Comment by acozine** [comment]
@smolz thanks for this one too! Just as on #41038, if you can provide a playbook and output from running it, that will speed up the review process. See the new Validation section of https://github.com/ansible/community/issues/311.

**Review by trishnaguha — APPROVED** [review]

**Comment by smolz** [comment]
Example playbook:
```
---
  - name: configure logging
    hosts: nx1
    tasks:

      - name: Configure logging using aggregate
        nxos_logging:
          aggregate:
            - { dest: console, dest_level: 2 }
            - { dest: logfile, dest_level: 6, name: testfile }
            - { facility: daemon, facility_level: 0 }
          state: present`

```
Output from running the playbook
```
=> ansible-playbook aggregate.yml 

PLAY [configure logging] *************************************************************************************************************************************************

TASK [Configure logging using aggregate] *********************************************************************************************************************************
changed: [nx1]

PLAY RECAP ***************************************************************************************************************************************************************
nx1                        : ok=1    changed=1    unreachable=0    failed=0   
```

Before playbook:
```
nx1# sh run | in logg
logging server 10.18.37.144 5 use-vrf default
logging server 10.18.37.145 5 use-vrf default
nx1#
```
After playbook:
```
nx1# sh run | in logg
logging logfile testfile 6
logging server 10.18.37.144 5 use-vrf default
logging server 10.18.37.145 5 use-vrf default
logging level daemon 0
nx1#
```

**Comment by acozine** [comment]
Thanks @smolz, for the contribution and for the follow-up!

**Comment by IPvSean** [comment]
@smolz message me at ansible-network@redhat.com about the contest t-shirt

**Pull request merged**
