### PR TITLE
[2.3] Change: set the 'canonical_url' to /latest/

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY

Original PR #49190

(cherry picked from commit 59e7a9442e0fbb9c827f6c4d58ea7aebf5b04b02)

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by abadger** [comment]
shipit

**Review by abadger — APPROVED** [review]

**Review by acozine — APPROVED** [review]
This change will tell search engines that they should be pointing users to the `latest` docs rather than to `2.4`. Currently the 2.4 docs are prioritized, because they don't have a `canonical_url` set, because they are long-lived, and because there are lots of links to them elsewhere on the web.

**Review by Xaroth — CHANGES_REQUESTED** [review]
As mentioned in the original PR (and in #53175 ). the ``srtd`` theme does not allow for canonical url configuration.

**Comment by acozine** [comment]
Per @Xaroth's comment, this change will not help, because the theme in place on the 2.3 documentation does not support this setting. We will seek alternative solutions.

**Pull request closed without merging**
