### PR TITLE
Sanity fixes to parameter types

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
These are fixes required for #50085

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
Various modules

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by dagwieers** [comment]
The CI failure is related to previously undocumented parameters.

**Comment by mattclay** [comment]
@dagwieers Not all the failures were due to undocumented parameters.

This PR introduced some new failures:

```
lib/ansible/modules/database/mysql/mysql_replication.py:203:161: E501 line too long (163 > 160 characters)
lib/ansible/modules/database/mysql/mysql_variables.py:23:8: W291 trailing whitespace
lib/ansible/modules/database/postgresql/postgresql_db.py:50:17: W291 trailing whitespace
```

I'm working on fixes now.

**Comment by dagwieers** [comment]
@mattclay That's weird, the CI output only showed the two issues.
https://app.shippable.com/github/ansible/ansible/runs/107745/summary/console

**Comment by mattclay** [comment]
@dagwieers The failures are visible on the tests tab:

https://app.shippable.com/github/ansible/ansible/runs/107745/1/tests

**Comment by mattclay** [comment]
The fixes in https://github.com/ansible/ansible/pull/52342 have been merged.

**Comment by dagwieers** [comment]
@mattclay I honestly never looked at that :-/

**Pull request merged**
