### PR TITLE
[Docs] update node req table for 2.15

### PR DESCRIPTION
**Pull request by oraNod**
##### SUMMARY
Adds 2.15 to the table at https://docs.ansible.com/ansible-core/2.15/installation_guide/intro_installation.html#node-requirement-summary

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/installation_guide/intro_installation.rst

##### ADDITIONAL INFORMATION
Minor docs update.

### CODE REVIEW

**Comment by sivel** [comment]
Should we just link to https://docs.ansible.com/ansible-core/2.15/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix where we maintain this information already instead of duplicating it?

**Comment by samccann** [comment]
@sivel thanks! I knew it existed somewhere else but was struggling to find it! Yeah, I agree would be great to remove this table and just point to that spot where it's maintained.

**Comment by oraNod** [comment]
Thanks @sivel I was wondering if there was a better way. It felt like that table was a maintenance pit.

It looks like there might be a couple of minor discrepancies with the details in that support matrix and that node requirements table.

- Node requirements table has a callout for 2.11 control nodes that states "a soft requirement of Python 3.8 as not packaged for older versions"
- For 2.12, the node requirements table lists Python 2.6 - 2.7 for managed nodes. The support matrix lists only Python 2.6 for managed nodes.

Are those things we should port over to the support matrix?

Cheers.

**Comment by sivel** [comment]
At this point, since 2.11 is EOL, we can ignore that bit of detail.  For the 2.12, I think was a typo, it was meant to be 2.6-2.7.  Must have gotten list in formatting changes.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
I have to update that release/maint table soon to EOL 2.12 and I'll patch the python versions in that PR.. thanks everyone!

**Pull request merged**
