### PR TITLE
mysql_replication: add resetmaster choice to mode param

### LINKED ISSUE #42870: mysql_replication: missing 'reset master' mode
##### SUMMARY
mysql_replication module supports many action, but one that is missing and may be useful is 'reset master' action. And as it already supports reset slave, it would make it more consistent.

See https://dev.mysql.com/doc/refman/8.0/en/reset-master.html for details.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
mysql_replication

##### ANSIBLE VERSION

```
ansible 2.6.0
  python version = 3.7.0 (default, Jul  4 2018, 23:50:59) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
mysql_replication: add resetmaster choice to mode param
fixes: https://github.com/ansible/ansible/issues/42870

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/mysql/mysql_replication.py```

##### EXAMPLE
```
- name: >
     Run RESET MASTER command which will delete all existing binary log files
     and reset the binary log index file on the master
   mysql_replication:
     mode: resetmaster
```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by bmalynovytch — APPROVED** [review]
LGTM 👍 
shipit

**Comment by Andersson007** [comment]
@bmalynovytch thank you! :)

**Review by resmo — APPROVED** [review]
shipit

**Comment by Andersson007** [comment]
resmo: thank you for reviewing and merging!

**Pull request merged**
