### PR TITLE
Adding same_vpc_only option to EC2 dynamic inventory configuration

### PR DESCRIPTION
**Pull request by mpeters**
This will filter the list of hosts that are returned to be just those
in the same VPC where the inventory script is being run

### CODE REVIEW

**Comment by mpdehaan** [comment]
(A) Looks like this one is in need of a rebase, can you take care of this?

(B) This looks pretty good to me, but I have a bit of a concern about a high number of API calls if there are a lot of machines in the VPC.    Do you think there might be a different way to do this so we could get all the macs in one API call?

**Comment by mpeters** [comment]
Getting the mac address should only be done once. It's trying to get the vpc_id of the control/master machine that the inventory is running on. It then compares it against the vpc_id that is returned for each host (which was already happening).

**Comment by mpdehaan** [comment]
# Cleanup Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We do require submissions to be free of merge commits, which cause difficulties in reviewing and merging code, and also affect the history of the source tree.
To resolve this problem, it may be helpful to create a new branch and cherry-pick commits onto it.
- In general, always start a "topic branch" named after each thing you would like to contribute
- use "git pull --rebase" vs "git pull" to stay in tune with upstream, as well as "git rebase" vs "git merge"
- if you have things broken out over many commits, consider submitting just one squashed commit that keeps the history concise

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by mpeters** [comment]
A new pull request has been created with a clean branch without any merge commits in it's history to replace this one: #8581

**Comment by mpdehaan** [comment]
Thanks, I'm going to close this one out per the above, thank you!

**Pull request closed without merging**
