### PR TITLE
Load plugins from playbook basedir

### PR DESCRIPTION
**Pull request by dhozac**
Same as PR #1055, rebased on devel.

### CODE REVIEW

**Comment by mpdehaan** [comment]
looks solid, will look into merging shortly

**Comment by mpdehaan** [comment]
When manually merging this and running "make tests" I am getting errors.

# 

## ERROR: test_playbook_vars (TestPlayBook.TestPlaybook)

Traceback (most recent call last):
  File "/home/mdehaan/ansible/test/TestPlayBook.py", line 167, in test_playbook_vars
    playbook.run()
  File "/home/mdehaan/ansible/lib/ansible/playbook/**init**.py", line 186, in run
    self._run_play(play)
  File "/home/mdehaan/ansible/lib/ansible/playbook/__init__.py", line 333, in _run_play
    self._do_setup_step(play)
  File "/home/mdehaan/ansible/lib/ansible/playbook/__init__.py", line 312, in _do_setup_step
    transport=play.transport, sudo_pass=self.sudo_pass, is_playbook=True
  File "/home/mdehaan/ansible/lib/ansible/runner/__init__.py", line 602, in run
    results = self._parallel_exec(hosts)
  File "/home/mdehaan/ansible/lib/ansible/runner/__init__.py", line 519, in _parallel_exec
    [job_queue.put(i) for i in hosts]
  File "<string>", line 2, in put
  File "/usr/lib64/python2.6/multiprocessing/managers.py", line 725, in _callmethod
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <type 'module'>: attribute lookup __builtin__.module failed

---

**Comment by dhozac** [comment]
I remember seeing that error, but I don't remember what caused it or how I fixed it, if I even did anything to fix it... Oddly enough, rebasing on top of devel and running make tests works fine here. I'll play with it and see if it comes back to me.

**Comment by mpdehaan** [comment]
Yeah perhaps I merged the conflict around module loading incorrectly or
something.

**Comment by mpdehaan** [comment]
Resubmit this if you figure out how to get the error fixed.

This makes my CPU's fans go relatively psycho for some reason.

**Comment by dhozac** [comment]
I've pushed my rebased tree which passes make tests here. Does it still throw that error on you?

**Comment by dhozac** [comment]
Still passes make tests here.

**Comment by mpdehaan** [comment]
reopened for testing

**Comment by mpdehaan** [comment]
yep, this is still exploding.  Something is keeping a reference to a module object and those are not pickleable.

I couldn't find it, but it's part of this branch only.

**Comment by mpdehaan** [comment]
CentOS 6.2 if you want to test.

**Comment by dhozac** [comment]
Ah ha! That is why I couldn't reproduce it, but had seen it before. Was easy enough once I could test myself, I have pushed a fixed branch and that passes make tests here on RHEL 6 too.

**Pull request closed without merging**
