### PR TITLE
Fix broken issue link

### PR DESCRIPTION
**Pull request by rndmh3ro**
##### SUMMARY
Fix broken issue link

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY
Fix broken issue link

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
xenserver_guest_powerstate.py

### CODE REVIEW

**Review by djspiro — APPROVED** [review]

**Comment by bvitnik** [comment]
PR #67376 also fixes this so we have a little clash :)

**Comment by rndmh3ro** [comment]
@Akasurde has more fixes than mine, so I'll close this pr. :)

**Comment by Akasurde** [comment]
@rndmh3ro I am sorry. I didn't mean to step on your work. I should have seen this PR first. Anyways, thanks for the contribution.

**Comment by rndmh3ro** [comment]
Don't worry about it! :)

**Pull request closed without merging**
