### PR TITLE
docker_swarm: fix ca_force_rotate idempotency

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fix `ca_force_rotate idempotency` idempotency.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_swarm

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Comment by WojciechowskiPiotr** [comment]
shipit

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
@WojciechowskiPiotr thanks for reviewing!
@gundalow thanks for merging!

**Pull request merged**
