### PR TITLE
Unarchive should work when parent directory is not writable

### PR DESCRIPTION
**Pull request by willthames**
Correct unarchive so that the checks for writeability are
sensible.

Added a test for when parent directory is not writable

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!  Flagging this for P2 so hopefully can get in 1.7 if time.   Much appreciated.

**Comment by mpdehaan** [comment]
Note this appears to be just a test and not the fix, per discussion on ansible-project.  Lowering priority for now.

**Comment by willthames** [comment]
No, it has both. Two files changed - one is the test, one is the unarchive module itself.

**Comment by willthames** [comment]
@Tenzer good point :) I was more worried about ensuring that it was a directory, I don't know why I kept the existence check.

**Comment by willthames** [comment]
@Tenzer updated the fix to incorporate your observation. (of course now the line has changed your line level comment has gone!)

**Comment by Tenzer** [comment]
@willthames It's more important the code is correct than keeping my comments ;)

**Comment by mpdehaan** [comment]
Merged, thanks!

**Pull request merged**
