### PR TITLE
Move ome_* and idrac_* modules one level up

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The `ome_*` and `idrac_*` modules in `remote_managment/dellemc` should not be in subdirectories. That causes doc generation to not work properly. For example, the modules are not listed here: https://docs.ansible.com/ansible/devel/modules/list_of_remote_management_modules.html#imc while there is an empty "Dellemc" title. The module docs pages are generated, though (see for example https://docs.ansible.com/ansible/devel/modules/ome_device_info_module.html).

This affects two modules new for 2.8 (`idrac_*`), and one new for 2.9 (`ome_*`).

Thanks to @fbecker for pointing this out [here](https://github.com/ansible/ansible/pull/53438#issuecomment-515756886).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ome_device_info
idrac_firmware
idrac_server_config_profile

### CODE REVIEW

**Comment by felixfontein** [comment]
cc @Sajna-Shetty

**Comment by felixfontein** [comment]
(ansibot is confused, it thinks this PR contains new modules, but it doesn't; the modules are just moved around.)

**Comment by rajeevarakkal** [comment]
@felixfontein How to we identify/differentiate this as "DellEMC" modules? Module names can't have company names in it. Also Botmeta details needs to be updated?

**Comment by felixfontein** [comment]
@rajeevarakkal they will show up under https://docs.ansible.com/ansible/devel/modules/list_of_remote_management_modules.html#dellemc because they are in a subdirectory called `dellemc`. There's no need to update BOTMETA since the entries in there only are about the remote_management/dellemc directory, and not for specific entries in there.

**Comment by rajeevarakkal** [comment]
@felixfontein are you suggesting to have the modules directly under "dellemc" folder (remove `idrac `& `ome` folder)?

**Comment by rajeevarakkal** [comment]
@felixfontein Our preference is to remove `dellemc` folder and keep `idrac `and `ome `folder as is. Let us know this will help?

**Comment by felixfontein** [comment]
> @felixfontein are you suggesting to have the modules directly under "dellemc" folder (remove `idrac `& `ome` folder)?

Yes, because right now, there's one level too many of folders. So one level has to go, and I assumed you probably want `dellemc` to be removed.

> @felixfontein Our preference is to remove dellemc folder and keep idrac and ome folder as is. Let us know this will help?

In that case I guessed wrong :-) I'll adjust the PR accordingly.

**Comment by felixfontein** [comment]
ready_for_review

**Comment by rajeevarakkal** [comment]
@felixfontein, Apologies for delayed review; We had a second thought to retain our brand "dellemc" in the folder structure as the respective module names already contains product names (ome/idrac) like what you proposed initially. 

It will be great if you can revert back to single "dellemc" folder approach (all the modules under this folder) .

**Comment by felixfontein** [comment]
@rajeevarakkal I've updated the PR accordingly. If it looks fine to you now, I'll merge.

**Comment by rajeevarakkal** [comment]
@felixfontein, Thanks, this looks fine 👍

**Comment by rajeevarakkal** [comment]
shipit

**Comment by felixfontein** [comment]
Great! I'll create a backport to stable-2.8 so that the iDRAC modules will be moved one level up (the OME module was added for 2.9). Then they will also show up correctly in documentation for 2.8.

**Pull request merged**
