### PR TITLE
Fixes #68121: Move kubectl plugin migration to proper place.

### LINKED ISSUE #68121: kubectl connection plugin migration routed to wrong collection
##### SUMMARY

During the 'great migration', the `kubectl` connection plugin was missed in the initial routing mapping, so it needs to be updated in the `routing.yml` file (https://github.com/ansible/ansible/blob/temp-2.10-devel/lib/ansible/config/routing.yml#L19-L20).

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

The Great Collection Migration

##### ANSIBLE VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

  1. Observe the `lib/ansible/config/routing.yml` file.
  2. Look at the value of `plugin_routing.connection.kubectl.redirect`

##### EXPECTED RESULTS

The value should be `community.kubernetes.kubectl`

##### ACTUAL RESULTS

The value is `community.general.kubectl`

### PR DESCRIPTION
**Pull request by geerlingguy**
##### SUMMARY

Closes #68121

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

The Great Collection Migration

##### ADDITIONAL INFORMATION

N/A

### CODE REVIEW

**Review by nitzmahone — APPROVED** [review]

**Review by bcoca — APPROVED** [review]

**Comment by bcoca** [comment]
forgot to mention previously, but you also need to update BOTMETA.yml

**Comment by geerlingguy** [comment]
@bcoca fixed

**Comment by sivel** [comment]
Hello!

This pull request was submitted against the `temp-2.10-devel` base branch.  That branch has been protected, and development has been moved back to the `devel` branch.

To update this pull request, you will need to follow these steps:

1. Rebase your branch against the `devel` branch of `ansible/ansible`
1. Force push to your git remote
1. Change the target branch by using the `Edit` button for the pull request title, and select `devel` from the `base` dropdown.
1. Close and then re-open the pull request so that CI will re-run against the new base branch.

needs_info

**Comment by geerlingguy** [comment]
Doing as requested...

**Comment by geerlingguy** [comment]
@sivel Do we need to delete the openstack/third-party-check from the testing cycle for ansible/ansible now?

**Comment by emonty** [comment]
@geerlingguy Removing those OpenDev jobs right now.

**Comment by geerlingguy** [comment]
Hmm... I'm not able to trigger a rebuild here. @gundalow do you know who would be able to do that?

**Comment by sivel** [comment]
An open/close will restart the build. If you need just a single job restarted, a committer can kick it.  Asking in #ansible-devel usually works.  A bot feature is planned to allow that functionality.

**Comment by geerlingguy** [comment]
Trying another open / close cycle then...

**Comment by geerlingguy** [comment]
@sivel - I've done an open/close again, and it triggered a new shippable run, but it's also still throwing in the openstack check (@emonty mentioned that should be going away?)

**Pull request merged**
