### PR TITLE
 Update plugins/netconf/ce.py to fix a bug(failed to get veriosn information via neocnf).

### PR DESCRIPTION
**Pull request by yuandongx**
##### SUMMARY

I tried to get version information, but failed.
And debug it,found that netconf api was wrong.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

changelogs/fragments/plugins-netconf-ce-fix.yaml
### netconf api to get version information should be....
image

image
```paste below


<!--- Paste verbatim command output below, e.g. before and after your change -->

```

### CODE REVIEW

**Comment by hwDCN** [comment]
LGTM

**Review by felixfontein — APPROVED** [review]
I assume you tested this with real hardware.

LGTM

**Comment by felixfontein** [comment]
@xuxiaowei0512 will you create appropriate backport PRs?

**Comment by xuxiaowei0512** [comment]
@felixfontein  Yes, you'r right, no test no committing.
Backport pr is also necessary, I will do it!
Thank you very much for your help, best regards from me.

**Pull request merged**
