### PR TITLE
Initial add of the cpm_time_config module

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
cpm_time_config

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by scarshouldofwon** [comment]
What is the current version of the firmware that is needed to use the module?

**Comment by wtinetworkgear** [comment]
@scarshouldofwon The current release for the DSM 6.58 and VMR 2.15 will have the current RESTful API that will support this module. If you need any help upgrading or need a demo unit online email us at support@wti.com and they will take care of you.

**Comment by mattsene** [comment]
Hi,
Is the date fixed format of mm/dd/yyyy or can they also be input as dd/mm/yyyy

**Comment by wtinetworkgear** [comment]
@mattsene The data is fixed at mm/dd/yyyy

**Comment by Mariom949** [comment]
What address can I use for the NTP time services?

**Comment by wtinetworkgear** [comment]
@Mariom949 You can use any accessible NTP server either by IP address (and if the DNS is defined) or by name. https://www.ntppool.org/en/use.html

**Pull request closed without merging**
