### PR TITLE
Update dellos10_command.py

### PR DESCRIPTION
**Pull request by amybuck**
##### SUMMARY
Updated Dell OS10 to Dell EMC OS10

+label: docsite_pr

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
dellos10_command

##### ANSIBLE VERSION
```paste below
devel
```

### CODE REVIEW

**Comment by jborean93** [comment]
@trishnaguha @ganeshrn this change seems ok to me, any objections to merging it?

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
From the docs perspective it looks good and matches what Dell EMC calls the product now, but will wait on the merge to see if there's any replies from the prior comment.

**Comment by gundalow** [comment]
Need @skg-net to approve this before merging

**Review by skg-net — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @amybuck for helping to improve the Ansible documentation!

**Pull request merged**
