### PR TITLE
aci_aep_to_domain: New module to bind AEP to domain

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
New module to bind AEP to domain

This module still needs integration tests once it is formally review and accepted.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
aci_aep_to_domain

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by dagwieers** [comment]
@jmcgill298 @schunduri @brunocalogero Please review. I'd rather have it reviewed first before making integration tests.

**Comment by dagwieers** [comment]
cc @rsmeyers @nilloBE Please test and review !

**Comment by gundalow** [comment]
Not seeing anything obviously wrong here. As Dag stated will need test, `EXAMPLES` and `RETURNS` adding if people think this is the right approach.

**Review by dagwieers — COMMENTED** [review]
LGTM

**Comment by nilloBE** [comment]
At the moment it is only supporting three VMM domain types: vmware, microsoft and openstack.

we need to add more:
redhat
kubernetes
openshift
cloudfoundry

**Comment by nilloBE** [comment]
I did basic testing, adding and deleting domains to AEP. Tested with existing and un-existing domains. Works ok.

**Comment by dagwieers** [comment]
@nilloBE So Redhat (RHEV) was already added because I stumbled on it by accident, however it was not listed in the module documentation. But the others I have no documentation on. So I don't know what the internal name is associated with it.

```python
VM_PROVIDER_MAPPING = dict(
    microsoft='Microsoft',
    openstack='OpenStack',
    redhat='Redhat',
    vmware='VMware',
)
```
So if you have a document with REST calls using these, I'd be delighted to add them.

It would also be nice if we could document since what version of APIC each is supported. I read that Kubernetes is supported since v3.0, but again no idea how I need to add it.

**Comment by dagwieers** [comment]
PS It would probably be best to open a new issue for this, rather than adding comments to an already merged PR. An open issue is being tracked, a closed PR is not.

**Comment by nilloBE** [comment]
Fair enough, forgive me :) ... my dev experience is close to null ... doing that now and adding info on the internal objects for each VMM domain.

**Pull request merged**
