### PR TITLE
Fix delegate_to using incorrect ansible_become_* vars (#34259)

### LINKED ISSUE #34259: delegated task uses an incorrect 'ansible_become_pass'
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegate_to

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /Users/tagir/.config/ansible/ansible.cfg
  configured module search path = [u'/Users/tagir/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
```
 ANSIBLE_PIPELINING(/Users/tagir/.config/ansible/ansible.cfg) = True
 CACHE_PLUGIN(/Users/tagir/.config/ansible/ansible.cfg) = jsonfile
 CACHE_PLUGIN_CONNECTION(/Users/tagir/.config/ansible/ansible.cfg) = .
 CACHE_PLUGIN_TIMEOUT(/Users/tagir/.config/ansible/ansible.cfg) = 60
 DEFAULT_BECOME_METHOD(/Users/tagir/.config/ansible/ansible.cfg) = su
 DEFAULT_GATHERING(/Users/tagir/.config/ansible/ansible.cfg) = smart
 DEFAULT_JINJA2_EXTENSIONS(/Users/tagir/.config/ansible/ansible.cfg) = jinja2.ext.do
 DEFAULT_MODULE_NAME(/Users/tagir/.config/ansible/ansible.cfg) = shell
 DEFAULT_ROLES_PATH(/Users/tagir/.config/ansible/ansible.cfg) = [u'/Users/tagir/git/ansible/r oles']
 DEFAULT_STDOUT_CALLBACK(/Users/tagir/.config/ansible/ansible.cfg) = debug
 RETRY_FILES_ENABLED(/Users/tagir/.config/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
In my environment `ansible_become_pass` is defined on a per-host basis. This does not play well with the delegated tasks, because instead of using the password of the host the task is delegated to, the password of the delegating host is used.

##### STEPS TO REPRODUCE
Sample inventory file:
```yaml
---
all:
  hosts:
    ns1:
      ansible_become_pass: ns1
    ns2:
      ansible_become_pass: ns2
    ns3:
      ansible_become_pass: ns3
```

Sample playbook:
```yaml
---
- hosts: all
  tasks:
    - debug: msg="{{ ansible_become_pass }}"
      delegate_to: ns1
```

##### EXPECTED RESULTS
`ansible_become_pass` to be `ns1` for every run of the delegated task.

##### ACTUAL RESULTS
The value of the `ansible_become_pass` is taken from the variables of the respective host.

```
$ ansible-playbook -i inventory.yml playbook.yml

PLAY [all] **********************************************************************************

TASK [debug] ********************************************************************************
ok: [ns1 -> None] => {}

MSG:

ns1

ok: [ns2 -> None] => {}

MSG:

ns2

ok: [ns3 -> None] => {}

MSG:

ns3


PLAY RECAP **********************************************************************************
ns1                        : ok=1    changed=0    unreachable=0    failed=0
ns2                        : ok=1    changed=0    unreachable=0    failed=0
ns3                        : ok=1    changed=0    unreachable=0    failed=0
```

### PR DESCRIPTION
**Pull request by bauen1**
##### SUMMARY
This Pull Request Fixes #34259
Ansible was using the hosts become_pass variables and not the variables from the delegated_to host, this leads to authentication errors when using `delegate_to` and `become: true` (this is also a security bug, since passwords will be send to the wrong host).

##### ISSUE TYPE
- Bugfix Pull Request

##### ADDITIONAL INFORMATION
This patch was provided by @klondi [here](https://github.com/ansible/ansible/issues/34259#issuecomment-426055503).

### CODE REVIEW

**Comment by kondi** [comment]
https://github.com/klondi, not https://github.com/kondi ;)

**Comment by bauen1** [comment]
ready_for_review

**Comment by bcoca** [comment]
@bauen1 not sure this is correct since we don't rely on play_context at this point (we did in past), become is now handled by the plugins and the variables are passed in from the executor

**Comment by bauen1** [comment]
@bcoca From my understanding the executor relies on play_context to provided the variables, see https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py#L513-L516.
I also tested this and it worked in my case.

**Comment by bcoca** [comment]
that is there for backwards compatibility, but this is what sets the used options from variables:
https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py#L949

**Comment by bauen1** [comment]
I'm not too familiar with the code base of ansible.
However, as far as I understand the code, `play_context` is responsible for setting `become_pass` to the right value, it does however currently not take `delegate_to` into account when reading `sudo_pass` and `su_pass`, which is the bug described in #34259.
I'm therefor quite sure that fixing `play_context` is correct, since it's the root of the issue.

**Comment by bcoca** [comment]
@bauen1 that used to be the case, it is not anymore

**Comment by bauen1** [comment]
@bcoca After doing some more experimenting, you're right after all.

Switching to `ansible_become_password` makes this patch useless.
However there is another issue, since ansible will currently evaluate `ansible_become_password` in the context of the host and not in the context of the delegated host.

Example:
```yaml
# hosts.yml
---
all:
    hosts:
        a:
            ansible_become_password: "a"
        b:
            ansible_become_password: "b-{{ inventory_hostname }}"
            # should normally evaluate to b-b
```
```yaml
#!/usr/bin/env ansible-playbook
# site.yml
---
- hosts:
    - a
    - b
  gather_facts: false
  tasks:
    - name: print become password
      debug:
        msg: "password: {{ ansible_become_password }}"

- hosts: a
  gather_facts: false
  tasks:
    - name: test1
      become: true
      ping:
      delegate_to: b
      # ansible_become_password will evaluate to b-a instead of b-b
      # ansible will fail to authenticate with the remote host
```

I'm not really sure if this can be fixed easily.

**Comment by bcoca** [comment]
i was doing very similar patch, just using `set_variables` on templar to change the context to be the specific host, there is another bug that requires slightly different templating than you do here.

i.e `ansible_host: {{ ansible_fqdn| process}}` as that will template using the inventory_hostname variables instead of the delegated host ones. So i have a `vm.get_vars(task=self._task, host=self._task.delegate_to)` to create the dict needed to handle all cases, you are further ahead than me so if you want to incorporate that here ...

**Comment by bauen1** [comment]
So this would increase the example to this:
```yaml
# hosts.yml
---
all:
    hosts:
        a:
            ansible_host: "host-a-{{ inventory_hostname }}"
            # should normally evaluate to "host-a-a"
            ansible_become_password: "a"
        b:
            ansible_host: "host-b-{{ inventory_hostname }}"
            # should normally evaluate to "host-b-b"
            ansible_become_password: "b-{{ inventory_hostname }}"
            # should normally evaluate to "b-b"
```
```yaml
#!/usr/bin/env ansible-playbook
# site.yml
---
- hosts:
    - a
    - b
  gather_facts: false
  tasks:
    - debug:
        msg: "password: {{ ansible_become_password }}\nhost: {{ ansible_host }}"

- hosts: a
  gather_facts: false
  tasks:
    - name: test1
      become: true
      ping:
      delegate_to: b
      # ansible_host will evaluate to "host-b-a" instead of "host-b-b"
      # ansible_become_password will evaluate to "b-a" instead of "b-b"
      # ansible would fail to authenticate with the remote host
```

Also it seems like #39413 is caused by this too.

**Comment by bauen1** [comment]
@bcoca I would love to incorporate your changes, could you push them somewhere for me to look at, I'm also at a bit of a loss where `ansible_host` for the delegated connection is set.
There are also a few more cases where something from `final_vars` is templated using the host currently run.

**Comment by bcoca** [comment]
I was trying to get #55219, to ensure all resolution happens outside of play_contxt, which simplifies the patch to only update task_executor

**Comment by bcoca** [comment]
probably fixes #33516

**Comment by bauen1** [comment]
Using the test provided in #55644 says it's still an issue.

**Comment by bauen1** [comment]
@bcoca could you give this another look ? Apart from the small git-mess it should be working now.

**Comment by equinox0815** [comment]
What is the status of this? I have the same issue as #30630. 
Using the following inventory and playbook i can confirm that this PR fixes my problem

```
[all:vars]
host_domain=example.com
ansible_host={{ inventory_hostname }}.{{ host_domain }}
ansible_user=root
ansible_port=222

[hosts]
host-a
host-b
```

```
- hosts: host-a
  tasks:
  - command: hostname
    register: result
    delegate_to: host-b
  - debug:
      var: result.stdout
```

**Comment by bauen1** [comment]
I'm waiting on a review by @bcoca (I have pinged him a few times on IRC too)
Technically this should be good to merge.
And nice that you found it helpfull.

**Comment by equinox0815** [comment]
@bcoca, @bauen1 any updates on this?

**Comment by bauen1** [comment]
Apart from the new conflicts, this should be good to merge, so this PR just needs someone to review it.
(I'll try to fix the conflicts shortly)

**Comment by bauen1** [comment]
Rebased ontop of current devel branch.
All that would now be necessary is a review.
@bcoca @equinox0815

**Comment by Pyropace** [comment]
can someone merge this please ? need this fix as well

**Comment by bcoca** [comment]
closing via alternate #69244

**Pull request closed without merging**
