### PR TITLE
On OpenBSD, swap the values for distribution_version and distribution…

### PR DESCRIPTION
**Pull request by jasperla**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

facts (setup module)

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

This PR swap the values for the `distribution_release` and `distribution_version` facts on OpenBSD. This was done to be more inline with other platforms Ansible runs on, and to have less "surprising" values for OpenBSD users.
OpenBSD ships regular releases with a numbered version (e.g. 6.0). There are several "flavors" so to say, `release`, `current`, `beta` and `stable` which are output into the `sysctl kern.version` string.

This PR brings the values inline with for example RH7 where the `_version` is a numerical value (7.2) and the `_release` a string (Maipo).

Before:
```
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "OpenBSD", 
        "ansible_distribution_release": "6.0", 
        "ansible_distribution_version": "current"
    }, 
    "changed": false
}
```
after:
```
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "OpenBSD", 
        "ansible_distribution_release": "current", 
        "ansible_distribution_version": "6.0"
    }, 
    "changed": false
}
```

Which is closer to:
```
        "ansible_distribution": "RedHat", 
        "ansible_distribution_major_version": "7", 
        "ansible_distribution_release": "Maipo", 
        "ansible_distribution_version": "7.2", 
```

This change was discussed and agreed with several other OpenBSD developers.

### CODE REVIEW

**Comment by jasperla** [comment]
@eest could you please review?

**Comment by abadger** [comment]
Reviewed the code change.  From the code standpoint this looks good to me.  It is backwards incompatible, though.  I've mentioned this on IRC to get feedback.

**Comment by jasperla** [comment]
@abadger Thanks; I've talked to a fellow OpenBSD developers who use ansible (@r-p-e and @ajacoutot) and they agreed with the change at least.

**Comment by ajacoutot** [comment]
Yes, I confirm this is something we want in OpenBSD, even if it's backward incompatible.

**Comment by abadger** [comment]
Merged to devel and added a 2.3.0 changelog entry:
- The version and release facts for OpenBSD hosts were reversed.  This has been
  changed so that version has the numeric portion and release has the name of
  the release.

**Comment by jasperla** [comment]
Thanks!

**Pull request merged**
