### PR TITLE
VMware: new module: vmware_guest_boot_manager

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This module can be used to manage virtual machine boot order and
related parameters.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest_boot_manager.py

##### ANSIBLE VERSION

```
2.6devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@pdellaert @dericcrago Could you please review this ?

**Comment by mihai-satmarean** [comment]
Thanks! This is actually great! Can it be back ported or used in Ansible 2.5?

**Comment by Akasurde** [comment]
@mihai-satmarean I am sorry but new modules are not backported to old version.

**Comment by mihai-satmarean** [comment]
Thanks for the info. 
So placing the library in the library folder and loading it with --module-path= works for us using Ansible 2.5.4

**Comment by Akasurde** [comment]
@mihai-satmarean Thats great !!! Thanks for the information. Let me know if there is any issue.

**Comment by mihai-satmarean** [comment]
@Akasurde Maybe I missed it, is the module provides one time boot change functionality? EG: Next boot from network?
If not, can be added?
Thanks!

**Comment by mihai-satmarean** [comment]
Any ideas for onetime boot only?

**Comment by Akasurde** [comment]
@mihai-satmarean Sorry, didn't check. will check and let you know.

**Comment by Alex5252** [comment]
I checked the vmware_guest_boot_manager module (ansible 2.7.0.dev0 (devel 5bcdf4f204) last updated 2018/07/17 21:27:23 (GMT +300)).
I did not find the problem.

I checked the boot_order option with the parameters "ethernet" and "disk", it works as expected.
I checked the boot_delay option, it works as expected.
The enter_bios_setup option is used to enter the BIOS, the next time it boots.
The boot_retry_enabled option with the true and false flags works as expected.
The boot_retry_delay option sets the reboot period.

@mihai-satmarean Please see https://kb.vmware.com/s/article/1003558 . From the article it appears that it is necessary to restart the virtual machine, in order to apply the boot option.
And according to the documentation https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/BootOptions.rst there is no possibility to set a one-time boot.

**Comment by mihai-satmarean** [comment]
Thank you. just placed a feature request here
https://github.com/vmware/pyvmomi/issues/702

**Comment by Alex5252** [comment]
@mihai-satmarean I've never found a mention that virtualization vmware generally has a "one time next boot change only" function.
The option "One Time Boot" I saw only on the HP C7000 blade chassis. Those the implementation of this functionality requires an external control program (daemon/script, maybe ansible tower or rundeck) that will set the download over the network, for example, and then, as the virtual machine boots over the network, launch the playlist for booting, from the hard disk, for example.
Another option is to always use the boot over the network, and on the server dhcp/tftp prepare the type of boot - from the hard drive, over the network, from cdrom.

**Comment by mihai-satmarean** [comment]
Majority of the servers with out-of-band management card have this.

2018-07-18 10:33 GMT+02:00 Alex5252 <notifications@github.com>:

**Pull request merged**
