### PR TITLE
Make newer stuff PEP8 compliant

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
So we fixed everything that was not a module to be PEP8 compliant, and
in the meantime these 5 new files were additionally disabled from PEP8
testing.

This fixes it.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

various files

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by bcoca** [comment]
don't merge this yet, im in middle of major modifications to most of these files and dont want a repeat of the  rebase issues with inventory project

**Comment by dagwieers** [comment]
Ok, let me know when you're finished, ignore more "legacy" files as you go.
And I will redo the PEP8 work, no problem.

**Comment by mattclay** [comment]
I've restarted CI since some of the failures were unrelated to this PR.

**Comment by dagwieers** [comment]
@bcoca Since this is now shipping with v2.4 I guess now is the time to merge this.

**Comment by bcoca** [comment]
sorry, should have removed my objections a couple of weeks back, i'm done and there should not be conflicts.

**Comment by bcoca** [comment]
just review the files, i had moved/removed some things that the PR might inadvertently add back.

**Comment by dagwieers** [comment]
Did you look at the PR ? Looks fine to me.

**Review by gundalow — APPROVED** [review]
https://github.com/ansible/ansible/pull/26951/files?w=1 looks good

**Pull request merged**
