### PR TITLE
Introduced ansible-rsync to core.

### PR DESCRIPTION
**Pull request by tima**
This replace #2979 and fixes the borked history. I created patches and started over to avoid any more confusion. 

I'm positive I did not use "git merge" however I may have forgotten --rebase when I did my git pull. Oh well. Hope this works this time.

### CODE REVIEW

**Comment by mpdehaan** [comment]
History is fine, in queue for testing!  (Others help testing also welcome, travelling a bit so may be a little bit on my end).

**Comment by srgvg** [comment]
I tested with following task

``` yaml
    synchronize: 
      src=templates/reverseproxies/apachesites/{{app}}/{{ZUIL}}/
      dest=/etc/apache2/sites-enabled/
      mode=push
      delete=yes
      verbosity=1
```

Using by default connection ssh, user root, no sudo with local key through ssh-agent.
This fails badly:

``` bash
failed: [rp] => {"cmd": "rsync --archive --delay-updates --compress -v --temp-dir /root/.ansible/tmp/ansible-1371128288.62-133653582453891 --delete-after --rsh 'ssh -i None -o StrictHostKeyChecking=no' templates/reverseproxies/varwww/ root@None:/var/www", "failed": true, "rc": 12}
msg: Warning: Identity file None not accessible: No such file or directory.
ssh: Could not resolve hostname None: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(601) [sender=3.0.7]
```

I see two issues here:
- I tries to set a keyfile, whilst this should not be necessary here;
- It does not set inventory_hostname as a proper hostname

Also the module seems to check for existence of a "private_key" parameter, but that parameter is not documented; (also I don't see why rsync needs a private key on the remote host as ansible already can log in to it? But I'm nto sure what the exact flow is between the action plugin and the module.)

**Comment by srgvg** [comment]
Sorry, I copy-pasted the wrong task; the right one has the correct src & dest as per the error. (Don't have access to the original repo now)

**Comment by tima** [comment]
Without the context that your running this in its hard to understand what you are trying to do here. 

Are you trying to sync from a local path to a remote host path? 

The private_key is undocumented because its for internal use only. The module assumes a private key will be used for any remote connections. 

<tim/>

Sent from my iPhone

**Comment by srgvg** [comment]
Yes, this is just a copy from local host where ansible runs to a remote host, syncing two directories, hence pushing a dir structure to the remoite ansible managed hosts. (the paths in the pasted task are from an other, but identical task). This is the most basic usage for this module I guess.

I'll take a look, to do some other tests.

**Comment by srgvg** [comment]
I did an extra test, with a minimal playbook:

``` bash
$ cat play.yml
- hosts: antares.ginsys.net
  gather_facts: False
  tasks: 
  - synchronize: src=~/tmp dest=~/tmp

$ ansible-playbook play.yml

PLAY [antares.ginsys.net] ***************************************************** 

TASK: [synchronize src=~/tmp dest=~/tmp] ************************************** 
failed: [antares.ginsys.net] => {"cmd": "rsync --archive --delay-updates --compress --quiet --temp-dir /home/serge/.ansible/tmp/ansible-1371299107.57-268884885681543 --rsh 'ssh -i None -o StrictHostKeyChecking=no' ~/tmp serge@None:~/tmp", "failed": true, "rc": 255}
msg: Warning: Identity file None not accessible: No such file or directory.
ssh: Could not resolve hostname None: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(601) [sender=3.0.7]


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/tmp/ansible/play.retry

antares.ginsys.net         : ok=0    changed=0    unreachable=0    failed=1   
```

Same problem.

**Comment by tima** [comment]
Can I see your inventory file? Are you specifying an identity file for this host? I'm trying to figure out why inventory_hostname is coming back None. I don't see how this line would fall thru to that value yet it is.

```
dest_host = inject.get('delegate_to',
                              inject.get('ansible_ssh_user',
                              inject['inventory_hostname']))
```

Thanks.

**Comment by srgvg** [comment]
This was just a very basic test hosts file:

``` bash
$ cat /etc/ansible/hosts 
localhost
antares.ginsys.net
```

**Comment by srgvg** [comment]
Hey @tima, any update on this? Can I help?

**Comment by hayeah** [comment]
Idea: instead of always returning True for "changed", you could invoke rsync with "-i" (itemize), if the stdout is empty, then nothing is changed.

**Comment by tima** [comment]
@hayeah I'm all for more accurate feedback though I don't think your suggestion use of the itemize option works that way. 

Do you have a patch or demo code?

<tim/>

**Comment by tima** [comment]
@sergevanginderachter Work has me tied up with things that I haven't put enough time in to recreating the bug you are experiencing. 

I'll see if I can fit something in today. 

<tim/>

**Comment by tima** [comment]
I found and fixed the two bonehead mistakes I made. I amended and push a new version for further review.

**Comment by srgvg** [comment]
First hings firsts, running a test with defaults (paramiko, gives following error.
I assume this module can only run with -c ssh? Might be needed to check on the transport and give a proper error message?

Then, when running with -c ssh, It at first runs the module, but then it hangs on the remote side.

Details about what I tested and how, see this gist: https://gist.github.com/sergevanginderachter/5946849

Looks like on the remote end it start a --server, logging in on itself through ssh? Also, I don't see the difference when changing the mode from default push, to pull.

I'm starting nog being sure if I use your module the right way.

Could you elaborate on what exactly should happen, from a user point, and explain how this works the backend, what the action_plugin does, ans what the modules does? Also, how does delegate_to: exactly is supposed to work here? Maybe some use cases would be nice to explain.

**Comment by srgvg** [comment]
Can you explain why a private key is being used on the remote host? I'd expect rsync to be initiated from the local ansible command host, using the existing keys & connection?

**Comment by tima** [comment]
"I assume this module can only run with -c ssh? Might be needed to check on the transport and give a proper error message?"

Good point. ssh is just as required as having rsync here though I don't know if we should force ssh as the transport protocol. There is nothing stopping a user from using paramiko and using ssh with rsync.

I'm a bit confused to what you are expecting based on how rsync works and the docs for this module. 

The gist you pointed me to is running rsync on the localhost to sync testfile to the remote, antares.ginsys.net. The private key is not going out to the remote the local is using it to connect. If you do a pull rsync still runs on your localhost but in that mode it will go to the remote to get testfile and bring it to /tmp/, your destination.

You're not even getting that far because you don't have a ssh private key defined in your config, inventory file and (I presume) in your config.

Right now a key is required because that is most IMO and what I needed to get my job done. I was trying to get this baseline in to core so others can start contributing features to this module that they need. 

Hope that clarifies for you.

**Comment by srgvg** [comment]
> I'm a bit confused to what you are expecting based on how rsync works and
> the docs for this module.
> 
> It might be that I'm the one who is confused on how to use this module.

Can you provide a simple example with full detail in gist, how I can do
these two basic tasks?
- syncing a local folder on the ansible command host to a remote node
- syncing a remote folder on the remote node to the local ansible command
  host​​

> The gist you pointed me to is running rsync on the localhost to sync
> testfile to the remote, antares.ginsys.net. The private key is not going
> out to the remote the local is using it to connect. If you do a pull rsync
> still runs on your localhost but in that mode it will go to the remote to
> get testfile and bring it to /tmp/, your destination.
> 
> You're not even getting that far because you don't have a ssh private key
> defined in your config, inventory file and (I presume) in your config.

Yes, I have​​. I have a key set up and I am logging in passwordless on that
 host. Ansible is connecting to it, See
https://gist.github.com/sergevanginderachter/5946849#file-test-output-L14 for
a process list on the remote host: ansible module, rsync, ssh is running on
the remote host: so on the antares host, this runs eventually:

`ssh -i None -o StrictHostKeyChecking=no -l serge antares.ginsys.net .....`

I don't understand why the remote module spawns an rsync connecting to
itself over SSH?

**Comment by lwade** [comment]
Note:  suggest renaming this from synchronize to rsync.  In my opinion "synchronize" sets the wrong level of expectation for the user.

**Comment by tima** [comment]
@lwade I'm not opposed to that. I was on the fence when I first showed this code. I think it was @mpdehaan that suggested synchronize rather than rsync. Not sure though it was months ago. Maybe he can chime in here again?

@sergevanginderachter What in the embedded docs is not sufficient? Here is a rendered copy if it helps: https://github.com/tima/ansible-rsync/blob/master/README.md. Also, I don't see any sign of ansible passing a identity key in the verbose output lines you posted. Where did you define that key? --identity-key command line? The ANSIBLE_PRIVATE_KEY_FILE environ variable? private_key_file in your ansible.cfg?  "I don't understand why the remote module spawns an rsync connecting to itself over SSH?" It's not. I don't think you understand what you are looking at. Don't take this the wrong way, but have you read thru the code?

**Comment by srgvg** [comment]
@tima 

I don't define a key anywhere except in `.ssh/config`, ansible just uses it, just like a manual rsync does.
I don't use `--identity-key` not do I configure that anywhere. As I said, ansible by itself can connect to my nodes without a problem, even when using the synchronizze plugin, ansible does contact the node and runs the module. That is not the problem.

The point is really that I'm trying to test the module in the simplest possible way, and I can't get it to work.

To show you I'm doing this in a clean environment, see below: clean checkout of your repo, and one simple base command to rsync a local directory to the remote server. I even deleted /etc/ansible to make sure no old ansible.cfg was in the way, so all I have here are defaults:

(this is using paramiko:)

``` bash
serge@cyberlab:~$ cd tmp
serge@cyberlab:~/tmp$ git clone git://github.com/tima/ansible.git
Cloning into 'ansible'...
remote: Counting objects: 30822, done.
remote: Compressing objects: 100% (16827/16827), done.
remote: Total 30822 (delta 17652), reused 24717 (delta 11959)
Receiving objects: 100% (30822/30822), 12.09 MiB | 603 KiB/s, done.
Resolving deltas: 100% (17652/17652), done.
serge@cyberlab:~/tmp$ cd ansible/
[dvl] serge@cyberlab:~/tmp/ansible$ gi
origin  git://github.com/tima/ansible.git (fetch)
origin  git://github.com/tima/ansible.git (push)
* devel                              aa93854 Merge pull request #3443 from ajsalminen/arg_unicode_fix
  remotes/origin/HEAD                -> origin/devel
  remotes/origin/ansible-rsync-take2 5d49805 Introduced ansible-rsync to core.
  remotes/origin/devel               aa93854 Merge pull request #3443 from ajsalminen/arg_unicode_fix
  remotes/origin/rsync               52b3848 Introduced ansible-rsync to core.
## devel
[dvl] serge@cyberlab:~/tmp/ansible$ git co ansible-rsync-take2 
Branch ansible-rsync-take2 set up to track remote branch ansible-rsync-take2 from origin by rebasing.
Switched to a new branch 'ansible-rsync-take2'
[nsbl-rsync-tk2] serge@cyberlab:~/tmp/ansible$ . hacking/env-setup 

Setting up Ansible to run out of checkout...

PATH=/home/serge/tmp/ansible/bin:/home/serge/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PYTHONPATH=/home/serge/tmp/ansible/lib:
ANSIBLE_LIBRARY=/home/serge/tmp/ansible/library
MANPATH=/home/serge/tmp/ansible/docs/man:

Remember, you may wish to specify your host file with -i

Done!

[nsbl-rsync-tk2] serge@cyberlab:~/tmp/ansible$ ansible -i antares.ginsys.net, all -m synchronize -a "src=./hacking/ dest=~/tmp/" -vvv
<antares.ginsys.net> ESTABLISH CONNECTION FOR USER: serge on PORT 22 TO antares.ginsys.net
<antares.ginsys.net> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1373555248.7-216698528055214 && chmod a+rx $HOME/.ansible/tmp/ansible-1373555248.7-216698528055214 && echo $HOME/.ansible/tmp/ansible-1373555248.7-216698528055214'
<antares.ginsys.net> PUT /tmp/tmpAebKj2 TO /home/serge/.ansible/tmp/ansible-1373555248.7-216698528055214/synchronize
<antares.ginsys.net> EXEC /bin/sh -c '/usr/bin/python /home/serge/.ansible/tmp/ansible-1373555248.7-216698528055214/synchronize; rm -rf /home/serge/.ansible/tmp/ansible-1373555248.7-216698528055214/ >/dev/null 2>&1'
antares.ginsys.net | FAILED >> {
    "cmd": "rsync --archive --delay-updates --compress --quiet --temp-dir /home/serge/.ansible/tmp/ansible-1373555248.7-216698528055214 --rsh 'ssh -i None -o StrictHostKeyChecking=no' ./hacking/ serge@antares.ginsys.net:~/tmp/", 
    "failed": true, 
    "msg": "Warning: Identity file None not accessible: No such file or directory.\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nPermission denied (publickey,password).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(601) [sender=3.0.7]\n", 
    "rc": 12
}

[nsbl-rsync-tk2] serge@cyberlab:~/tmp/ansible$ ansible -i antares.ginsys.net, all -m ping
antares.ginsys.net | success >> {
    "changed": false, 
    "ping": "pong"
}

[nsbl-rsync-tk2] serge@cyberlab:~/tmp/ansible$ 
```

When I'm doing ssh, it hangs:

``` bash
[nsbl-rsync-tk2] serge@cyberlab:~/tmp/ansible$ ansible -i antares.ginsys.net, all -m synchronize -a "src=./hacking/ dest=~/tmp/" -vvv -c ssh
<antares.ginsys.net> ESTABLISH CONNECTION FOR USER: serge
<antares.ginsys.net> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'antares.ginsys.net', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1373555613.03-41444414250156 && chmod a+rx $HOME/.ansible/tmp/ansible-1373555613.03-41444414250156 && echo $HOME/.ansible/tmp/ansible-1373555613.03-41444414250156'"]
<antares.ginsys.net> PUT /tmp/tmpo9VAmG TO /home/serge/.ansible/tmp/ansible-1373555613.03-41444414250156/synchronize
<antares.ginsys.net> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'antares.ginsys.net', "/bin/sh -c '/usr/bin/python /home/serge/.ansible/tmp/ansible-1373555613.03-41444414250156/synchronize; rm -rf /home/serge/.ansible/tmp/ansible-1373555613.03-41444414250156/ >/dev/null 2>&1'"]
```

Checking what happens on the remote node, I see the ansible module executes this rsync command:

``` bash
rsync --archive --delay-updates --compress --quiet --temp-dir /home/serge/.ansible/tmp/ansible-1373555613.03-41444414250156 --rsh ssh -i None -o StrictHostKeyChecking=no ./hacking/ serge@antares.ginsys.net:~/tmp/
```

So the remote node _is_ trying to connect to itself over ssh. It tries to sync the local dir /hacking/ to the tmp dir over ssh to antares (itself). It seems to me that's the command that should be run on the local ansible command node.

When I test this command manually to check what happens, I see it asks for the passphrase of the remote user on the remote node, which is logical.

To sync something from the local ansible command host to the remote  node, the rsync proces is initiated on the remote host, not on the local ansible command host, and that doesn't seem logical to me.

Can anyone at least confirm if this works for him/her? Am I the only one to bump into this behaviour?

**Comment by srgvg** [comment]
Also, from your docs, these parts confuse me:

```
Dest: Path on the destination machine that will be synchronized from the source; The path can be absolute or relative.

In push mode the localhost or delgate is the source; In pull mode the inventory hostname in context is the source.
```
- With other ansible modules, it's custom that the delegate host comes in place of the node; here it comes in place of the ansible command host. This is confusing.
- When pull mode and using delegate, what is the destination?

**Comment by tima** [comment]
@sergevanginderachter 

When you said you where defining an identity key it wasn't clear where you were doing it. I've been chasing my tail trying to figure out how my code was turning the ansible identity key configuration to None. 

So with that clear, I have to make the identity key optional in the code and deal with a missing key if rsync fails to connect. That should support what you are trying to do. It also handle situations where ansible is running as root.

I still need to figure out why the rsync module is getting transferred to the remote when it should stay local.

> With other ansible modules, it's custom that the delegate host comes in place of the node; here it comes in place of the ansible command host. This is confusing.

I got and still get confused on these things also -- is this code running from the remote or is it local? what if you throw in a delegate? Now who's running this code. 

I used the delegate example in the Ansible docs where a task takes the host out of a load balancer pool managed by the delegate. Ansible is connecting to the delegate to execute its task. The inventory_hostname is just the subject or the record in context if you will. 

So interpreted that to mean delegating a rsync call is like delegating a task to your load balancer. 

**UPDATE:** It's been a couple of months since I've been deep in this code and it just came back to me -- when Ansible sees a delegate_to defined it connects to and ships out the module code to that server and not the host in context aka inventory_hostname.

Hum, I may have just solved my remaining problem here.

> When pull mode and using delegate, what is the destination?

Currently the logic is that the delegate would be the destination so its remote syncing to delegate,

**Comment by tima** [comment]
@sergevanginderachter 

I think that last commit I made here may have fixed the last issue may have fixed the "calling itself" problem.

> ansible -i RSYNC.ini all -m synchronize -a "src=hacking/ dest=/tmp/" -vvv -c ssh
> 
> "cmd": "rsync --archive --delay-updates --compress --quiet --temp-dir /.statelite/tmpfs/tmp/ansible-tappnel/ansible-1373591726.75-21827380656812 --rsh 'ssh -i /home/tappnel/.ssh/id_encom -o StrictHostKeyChecking=no' hacking/ tappnel@example.com:/tmp/"

**Comment by srgvg** [comment]
The SSH key problem went away it seems. But the rsync process still gets run on the remote node, whichj is logical as that happens in the module, and not in the actiobn_plugin.

As you said you also got confused on where the code runs, let's step back a minute. Does the following describe the intended behaviour?
- "rsync" will run between the local ansible host and the remote node
- when using delegate, I would expect it to run between the local ansible host, and the delegate host
- pull and push just tweak the order of the host ijn the ansible command, setting source and destination
- There is no support for syncing between 2 remote nodes

Given this, that latter point would be the only reason why you might need a module, but given this behaviour of only rsyncing between local and remote, only an action_plugin would suffice.

Do you agree so far?

**Comment by tima** [comment]
I agree however I have a use for that last point. The thought of having no module like fetch had occurred me and would have made my life a lot easier otherwise.

Supporting the delegate option where rsync always runs from the local doesn't make sense to me. What is the task doing with the inventory_hostname ? The implementing the delegate as you suggest would remove it entirely from the tasks operation.

I know I looked at switching the connection object passed to the execute module function with a local and proved too messy. I thought I had solved that with the delegate_to "default" before I screwed up my commit history and (apparently) lost something.

**Comment by tima** [comment]
@sergevanginderachter: if you explicitly define localhost as the delegate do things work as expected? I away on holiday that I can't test this myself.

**Comment by srgvg** [comment]
Hm, I answered that last question, but it seems I didn't post it.

When doing a local action, things work well.
When delegating to localhost it works, as far as the the module runs / the rsync process gets started on localhost. Then there still was the issue it tried to rsync/ssh to elsewhere (instead of targetting localhost?)

I still think the main issue is getting the module to run on the right host, which seems to me to be allways localhost for most basic features, hence only needing an action plugin.

**Comment by tima** [comment]
Good to know. At this point it seems to be limited to the delegate being ignored. 

@mpdehaan said on the mailing list that setting the delegate_to in the inject should work. It's not though so I'm going to have to look in to why.

**Comment by mpdehaan** [comment]
Testing this again right now that we have the setup function merged into the rsync module.

Thanks for perseverance on this :)

**Comment by mpdehaan** [comment]
I've merged this in, made a few minor style/docs tweaks and to take advantage of some module common features added since this was started.

Looks good and survived initial testing.

I'll email the list to let people know about this one and get some extra testing on it, but glad to see this and I like the interface.

Thanks!

**Comment by markscarbrough** [comment]
I may be late to the game, but I tried this module a few days ago and it seemed that it reports 'changed', even when no files are modified by rsync. I agree with @hayeah, you could consider using the rsync --itemize-changes flag, which to my knowledge is the only way to reliably differentiate between a successful run with changes and a run with no changes. Here is a humble bash script I previously converted to an ansible module for my own use, the -i logic is in there and works for my use cases (reporting ok when no changes are made by rsync):

``` bash
#!/bin/bash

source $1

# always itemize changes, but allow user to add flags for maximum flexibility
RSYNC_ARGS="-i ${flags}"

# run rsync command and capture stdout
RSYNC_OUTPUT=`rsync ${RSYNC_ARGS} ${src} ${dest} 2> /dev/null`
if [ $? -eq 0 ]; then
  # lines beginning with these characters indicate file modification:  < > . * c h 
  # see rsync man page for more info
  RSYNC_OUTPUT=`echo $RSYNC_OUTPUT | grep '^[\<\>\.\*ch]'`
  if [ -z $RSYNC_OUTPUT ]; then
    echo 'ok=true'
  else
    echo 'changed=true'
  fi
else
  echo 'failed=true'
fi

# example usage to push files recursively:
#   - local_action: rsync src=/usr/local/src/degrib dest=$inventory_hostname:/usr/local flags=-a
```

**Pull request closed without merging**
