### PR TITLE
modules: network: ingate: Add module ig_system

### PR DESCRIPTION
**Pull request by ingatesystems**
Manage licenses, patches and upgrades on an Ingate SBC.

SUMMARY
Module for handling system level operations on an Ingate SBC.

ISSUE TYPE
New Module Pull Request

COMPONENT NAME
ig_system

ADDITIONAL INFORMATION

### CODE REVIEW

**Review by NilashishC — APPROVED** [review]

**Comment by ingatesystems** [comment]
ready_for_review

**Comment by ingatesystems** [comment]
ready_for_review

**Comment by ingatesystems** [comment]
ready_for_review

**Comment by ingatesystems** [comment]
ready_for_review

**Comment by ingatesystems** [comment]
Hi, is there anything I can improve/fix in order to get this PR merged? It has been lingering for a while now. Thanks Erik

**Pull request closed without merging**
