### PR TITLE
Remove .travis.yml files from galaxy init skeletons

### PR DESCRIPTION
**Pull request by dmsimard**
These files have existed for many years but in light of the recent
circumstances around Travis, we should not include them by default in
the galaxy init skeletons.

##### SUMMARY

Remove .travis.yml files from galaxy init skeletons

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-galaxy

### CODE REVIEW

**Comment by s-hertel** [comment]
We should check with the Galaxy team and make sure this isn't still a feature built into community Galaxy https://docs.ansible.com/ansible/latest/galaxy/dev_guide.html#travis-integrations.

cc @newswangerd

**Comment by newswangerd** [comment]
@s-hertel are these travis files for setting up travis to test roles using molecule?

We do still support travis integration for galaxy, but as far as I know, it's just a webhook that you can call after a successful travis run to update your roles on galaxy. I don't know that these templates are required for that to work.

**Comment by s-hertel** [comment]
@newswangerd Thanks for taking a look, it appears so. They're not required but could be a part of someone's workflow.

@dmsimard We thought during triage if this feature still existed removing it from the role skeletons could be a breaking change. Wonder if it merits a breaking_changes changelog fragment or if we should just keep the files while the feature exists...?

**Review by bcoca — APPROVED** [review]

**Comment by dmsimard** [comment]
Thanks for taking care of this @bcoca @s-hertel :)

**Pull request merged**
