### PR TITLE
update ansible-galaxy testserver to use SSLContext.load_cert_chain

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Update another case of #80490 so the test will be compatible with Python 3.12.

##### ISSUE TYPE
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by bcoca — APPROVED** [review]

**Comment by s-hertel** [comment]
Marked as a draft since https://github.com/ansible/ansible/pull/80721 may make it possible to remove this file altogether.

**Comment by webknjaz** [comment]
@s-hertel FYI [`trustme`] is a brilliantly designed piece (both API- and CLI-wise) I like to use for provisioning proper ephemeral TLS in tests. Maybe we should consider integrating it?

[`trustme`]: https://trustme.rtfd.io

**Comment by webknjaz** [comment]
Yeah, I've been using trustme in web frameworks and apps for the past 4-5 years but many don't know it exists. It's designed by Nathaniel J. Smith who is known for coming up with beautiful API ideas.

**Review by mattclay — APPROVED** [review]

**Comment by s-hertel** [comment]
I'm having some issues syncing a local git server with the Galaxy NG container, so I'm I'm going to merge this as-is to fix test failures in https://github.com/ansible/ansible/pull/80834, and continue working on updating the ansible-galaxy test suite in a later PR.

**Pull request merged**
