### PR TITLE
Module to install software on FreeBSD using portinstall

### PR DESCRIPTION
**Pull request by berenddeboer**
Hi ansibleworks, here a packager module to install stuff via FreeBSD. pkgng is off very little value as there are no repositories. This is my first contribution to ansible, and I barely no any Python, so all feedback gladly accepted.

### CODE REVIEW

**Comment by arsatiki** [comment]
How interesting! I was going to write the same module myself. I can test your module with my server and see what happens.

**Comment by arsatiki** [comment]
First impressions:
1. It uses the "old style" package management system, e.g. `pkg_info` instead of `pkg info`. I'm using pkgng and I'd love to have a knob to enable using it instead.
2. I don't quite understand the mysql55 -problem and the hacks resulting from it. Can you provide an example of the problem? Perhaps there is a less hacky way to do the same.
3. Does this module even need support removals? Since pkgng is the future (_knocks on wood_) and there is already a pkgng module, I'd like to offload all package management tasks to it. Could we trim this module down to focus exclusively on building and creating the package. For example, it could simply run `make package` and then allow pkgng to install the local package.

**Comment by mpdehaan** [comment]
Nice to see this.

One thing though, this really needs to be submitted _without_ merge commits.

Always use "git pull --rebase" vs "git pull" and "git rebase" vs "git merge".

Also not sure I like the mysql hack in there or understand that.

We of course DO need to have all package modules able to support removals.

Can you resubmit this without merge commits?

I'll defer to @arsatiki on question 1 as I don't quite understand the underlying logic behind that question.

Thanks!

**Comment by bcoca** [comment]
removals won't be hard, the hard part is updates, which is why most of us
that tried to make this module gave up and waited for pkgng.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by berenddeboer** [comment]
> > > > > "Brian" == Brian Coca notifications@github.com writes:

```
Brian> removals won't be hard, the hard part is updates, which is
Brian> why most of us that tried to make this module gave up and
Brian> waited for pkgng.
```

I would rather do that with a:

  portsnap update && portupgrade -a --batch

utility or so.

It seems we have waited and will wait a long time for pkgng.

## 

All the best,

Berend de Boer

**Comment by berenddeboer** [comment]
arsatiki:

1a. old style is the default for FreeBSD 9 out of the box.

1b. pkgng has no public repositories.

1c. yes, support for pkgng would be great, should just look at if this is enabled I suppose. Should not be hard.
1. if you install mysql55-client, the actual package that gets installed is mysql-client! So given you have mysql55-client in your ansible playbook, how do you know this maps to mysql-client? I don't have a good answer to that. The current code works for quite a wide range.
2. yes removals work.

**Pull request closed without merging**
