### PR TITLE
adding connection draining and cross zone load balancing options to ec2_elb_lb

### PR DESCRIPTION
**Pull request by mschurenko**
Please let me know if there are any issues with my pull request. I have added a feature to configure ELB attributes. I have done cross zone load balancing and connection draining. I did not implement accessLog as I have no need for that ATM. More information can be found http://boto.readthedocs.org/en/latest/ref/elb.html#module-boto.ec2.elb under modify_lb_attribute.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you please submit this as a squashed commit to make this easier to review?

Thanks!

**Comment by mpdehaan** [comment]
cc @jsmartin

**Comment by mschurenko** [comment]
Ok. Is this correct now? Sorry I have never done this before. Thanks.

**Comment by mschurenko** [comment]
I'm going to delete my fork and resubmit.

**Pull request closed without merging**
