### PR TITLE
core: remove pycompat24

### PR DESCRIPTION
**Pull request by grimreaper**
##### SUMMARY
This file was used for python2.4 compatibility. Since we now only
support python2.7+/python3.5+ there is no further need for this module

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION

This was found when reading ansible contribution guidelines. It does not
appear to be needed/used anymore.

### CODE REVIEW

**Comment by jamescassell** [comment]
Pretty sure we want to keep it for third party modules...

**Comment by bcoca** [comment]
also, we still support 2.6 on targets, 2.7 is controller, but I agree with @jamescassell , this is a good file to keep for those using custom modules and in need of compatibility shims.

**Review by gundalow — CHANGES_REQUESTED** [review]
I believe external modules may still use this.

**Comment by mattclay** [comment]
Closing, since this isn't something we can merge without breaking backwards compatibility for existing users.

Even though we no longer support Python 2.4, there may be modules that still import `pycompat24`, `get_exception` or `literal_eval`. Those will need to go through a deprecation cycle so that content authors will have time to make changes before they are removed.

**Pull request closed without merging**
