### PR TITLE
Make length of decorator match default callback plugin

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

profile_tasks callback plugin
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/ally/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fixes the output of `profile_tasks` to match the length of the existing default callback plugin (80 columns)

```
### Before:
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Saturday 29 October 2016  22:11:32 -0500 (0:00:00.070)       0:00:00.070 ******    # UNACCEPTABLE
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

Saturday 29 October 2016  22:11:34 -0500 (0:00:01.363)       0:00:01.433 ****** 
=============================================================================== 
setup ------------------------------------------------------------------- 1.36s    # DIOS MIO

### After:
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Saturday 29 October 2016  22:03:56 -0500 (0:00:00.073)       0:00:00.073 ******* 
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

Saturday 29 October 2016  22:03:57 -0500 (0:00:01.346)       0:00:01.419 ******* 
================================================================================ 
setup -------------------------------------------------------------------- 1.35s
```

### CODE REVIEW

**Comment by bcoca** [comment]
That should not be a constant but terminal dependent, the display class does a calculation already.

**Comment by bcoca** [comment]
setup some things in #18262 to make this easier, the filled function should be removed and use the banner instead (added cows option that will make it work for this purpose).

**Comment by ghost** [comment]
Thanks @bcoca, I'll take a look and revise this later today.

**Comment by bcoca** [comment]
closed via 62a434141e7f96299f820af3ca08fe86231300ed

**Pull request closed without merging**
