### PR TITLE
First try and making the nagios module NOOPpable

### PR DESCRIPTION
**Pull request by timlnx**
Could you review this and make sure I'm doing this the right way?

My approach was 

```
if we were going to exit with a failure AND we're in check_mode:
    exit with changed=False
else(if: we were about to do something):
    exit with changed=True (but don't do anything)
```

Also, some automatic trailing whitspace cleanup snuck in

### CODE REVIEW

**Comment by mpdehaan** [comment]
It looks like no.

Basically if it's going to fail, you shouldn't have a test where it doesn't fail in check mode.

The purpose of check mode should be to do everything up until the actual point of change, and then just return changed=True if it were going to change.  Otherwise, it does nothing and returns changed=False.

**Comment by timlnx** [comment]
I got ya now. Where "do everything" includes exploding on errors ty. Will refactor

**Comment by timlnx** [comment]
Updated the logic, rebased off of ansible/devel.

**Comment by mpdehaan** [comment]
ok, in queue for looking at.

Thank you!

**Comment by mpdehaan** [comment]
Yeah because this module always does something and doesn't need to change any resources, this is good.

Thanks!

**Pull request merged**
