### PR TITLE
new module: get_url

### PR DESCRIPTION
**Pull request by jpmens**
get module (with new module-magic-code!)
    Usage: ansible -m get -a "url=http://xxxxxxx  dest=fileordirctory"
    all cleanups as per @mpdehaan's suggestions
    add daisychain
    added example playbook (get_url.yml) with URLencode example

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for putting up with me -- will test this in a bit!

**Comment by jpmens** [comment]
Thank **you** for leading me along; if I mastered Python and the required git/Github-foo this would be much less painful. :)

**Comment by mpdehaan** [comment]
Running the example playbook I get:

< TASK: [Grab a bunch of jQuery stuff] >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

failed: [localhost] => (item=jquery.min.js) => {"failed": true, "group": "root", "item": "jquery.min.js", "mode": "0755", "msg": "refusing to convert between directory and file", "path": "/var/www/html/javascript", "secontext": "unconfined_u:object_r:httpd_sys_content_t:s0", "state": "directory", "user": "root"}
failed: [localhost] => (item=mobile/latest/jquery.mobile.min.js) => {"failed": true, "group": "root", "item": "mobile/latest/jquery.mobile.min.js", "mode": "0755", "msg": "refusing to convert between directory and file", "path": "/var/www/html/javascript", "secontext": "unconfined_u:object_r:httpd_sys_content_t:s0", "state": "directory", "user": "root"}
failed: [localhost] => (item=ui/jquery-ui-git.css) => {"failed": true, "group": "root", "item": "ui/jquery-ui-git.css", "mode": "0755", "msg": "refusing to convert between directory and file", "path": "/var/www/html/javascript", "secontext": "unconfined_u:object_r:httpd_sys_content_t:s0", "state": "directory", "user": "root"}

This is because it daisy chains into the file module and specifies the same directory as originally given as a parameter.
I think you want to always give a name for the file you are getting, and this will not be a problem.

**Comment by mpdehaan** [comment]
I'll hack on Runner some, I may be able to make this work easily.

**Comment by jpmens** [comment]
Before you do that: the info{} dict already contains `destpath` which is the final destination for the content (i.e. for the resulting file). Can we use that to overwrite what the file module thinks is `file=` ?

**Comment by jpmens** [comment]
No, that idea doesn't work: tried to fail_json(file=dest, ....)

**Comment by mpdehaan** [comment]
I've merged this, along with mechanisms to allow the daisychaining operations to work with the dest=directory pattern that the example playbook was used, plus a fix to allow you to download "/" successfully from a website.

If you can test this further, that would be great.

I basically used your playbook and taked on "mode=0644" and verified that it could set the mode, but I didn't check for all the possible failure scenarios of the get_url module after tweaking the code a little bit.

**Comment by jpmens** [comment]
Thanks Michael. 

There's something wrong with the _daisychain_ stuff, but I can't find it. If I remove the daisychain to `file` module, everything I test works. Daisychaining into `file` produces:

```
failed: [127.0.0.1] => {"failed": true, "msg": "", "parsed": false}
```

with a task of (note: `dest=` is a directory)

```
get_url url=http://localhost/~jpm/yyy.cgi?name=Michael dest=/tmp/u/
```

The URL is actually grabbed (I see that in Web server logs) and the file is created.
This only appears to happen if the destination is a dir. I've tried to follow your modifications to `get_url` and understand them, but I fail when I get to `file` module: don't grok what's happening. (Maybe I've seen too many cows today ... :-)

Must get some sleep now.

**Comment by mpdehaan** [comment]
Hmm, dest=directory was working fine in your playbook example for me.   (It did not work in the original, however)

Basically if a module returns a dictionary for "daisychain_args" those arguments are stringified and passed to the daisy chained module.   If you add some debug to print out what arguments are used in the executor_internal_error function in runner/**init**.py you may be able to figure more out.

That kind of parse error is the symptom of a traceback, but Ansible has printed out tracebacks in those conditions for a while now, so you should have seen that on screen.

**Comment by jpmens** [comment]
Somewhere here:

```
index 30583a8..3e3df97 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -572,12 +572,16 @@ class Runner(object):
         else:
         result = self._execute_async_module(conn, tmp, module_name, inject=inject)

+        print "JPJPJP 1"
     chained = False
     if result.is_successful() and 'daisychain' in result.result:
         chained = True
+            print "JPJPJP 2", self.module_name
         self.module_name = result.result['daisychain']
+            print "JPJPJP 3", self.module_name
         if 'daisychain_args' in result.result:
         self.module_args = result.result['daisychain_args']
+            print "JPJPJP ", self.module_args
         result2 = self._executor_internal_inner(host, inject, port)
         changed = result.result.get('changed',False) or result2.result.get('changed',False)
         result.result.update(result2.result)
```

produces this output

```
JPJPJP 1
JPJPJP 2 get_url
JPJPJP 3 file
JPJPJP  {u'url': u'http://localhost/~jpm/yyy.cgi?name=Michael', u'dest': u'/tmp/u/', u'path': u'/tmp/u//yyy.cgi'}
JPJPJP 1
failed: [127.0.0.1] => {"failed": true, "msg": "", "parsed": false}
```

I'm off now -- will try more tomorrow AM (CET)

**Comment by mpdehaan** [comment]
those arguments look fine to me.   The question is really about the output of the second call and why it's giving you "msg" : "" and not showing the traceback.

The return parser stuff is in utils, where you could probably make it print all the things it tries to parse pretty easily.

**Comment by jpmens** [comment]
Found it! ;-)

The `file` module is failing because there's an `=` in one of the args. (We were discussing this in [#644](https://github.com/ansible/ansible/pull/647) ...

Sending you a small PR

**Comment by jpmens** [comment]
I'll add:
1. It's was my fault all along for passing `url=` into the daisychain, but I feel that's good to have in the _msg_.
2. Your new `ANSIBLE_MODULE_COMMON` is a godsend for cases like these: a central location for such fixes.
3. No, I won't update `file` to use it -- at least not for the time being -- sorry. :-)

**Pull request merged**
