### PR TITLE
Second pass at OSX support.

### PR DESCRIPTION
**Pull request by cread**
Mostly to do with how we get md5sum of a file and the users home directory of a file and the users home directory.

This one now uses a try/catch instead of a python one liner for remote file md5 calc

This has been tested on:

OSX Lion (10.7.3)
Ubuntu 10.04 LTS

### CODE REVIEW

**Comment by mpdehaan** [comment]
ok, thanks, will review shortly.   much appreciated

**Comment by mpdehaan** [comment]
Try catch could be implemented better because that will end up making two remote calls.  Further, it's an untyped exception catch, it seems like you want to check for the right exception type rather than just catching all of them.

Why not something like a shell statement with testing for the existance of md5sum and executing if present, and if not, executing the other?

**Comment by cread** [comment]
What's the difference between a complex chunk of shell with conditionals
and the python one-liner?

On Wed, Apr 25, 2012 at 4:50 PM, Michael DeHaan <
reply@reply.github.com

**Comment by mpdehaan** [comment]
python -c requires byte compilation on the host, and further there has been some flux in the digest modules between different versions of python.  There are already host facilities for calculating md5sums.

**Comment by cread** [comment]
OK, I'll buy that.

Try
https://github.com/cread/ansible/commit/d73ba72abc996fbde62bcb105b4381b8f311318bon
for size, that more to your tastes?

Not sending another pull request yet as I don't want to spam the issues
list...

On Wed, Apr 25, 2012 at 5:05 PM, Michael DeHaan <
reply@reply.github.com

**Comment by mpdehaan** [comment]
Split that into an assignment to a variable versus the one liner, but yeah.   Much more efficient
and pretty easy to follow too.   Send me a pull request.   Thanks!

OS X support is going to be very nice to have.

We should discuss users and service modules on the list, probably.

**Pull request closed without merging**
