### PR TITLE
Added config-context as an opt-in

### LINKED ISSUE #50342: To make config-context as opt-in in netbox dynamic inventory
##### SUMMARY
It makes the config-context as an opt-in as discussed in #47394

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
config-context as an opt-in in netbox dynamic inventory

##### ADDITIONAL INFORMATION
If False
```
ansible-inventory -i netbox_inventory.yml --host ABC
{
    "ansible_host": "x.x.x.x",
    "device_roles": [
        "ACI IPN"
    ],
    "device_types": [
        "ABC"
    ],
    "manufacturers": [
        "Cisco"
    ],
    "primary_ip4": "x.x.x.x",
    "racks": [
        "ABC"
    ],
    "sites": [
        "ABC"
    ],
    "tenants": [
        "XYZ"
    ]
}
```
If True
```
ansible-inventory -i netbox_inventory.yml --host ABC
{
    "ansible_host": "x.x.x.x",
    "config_context": [
        {
            "xx": {
                "net": {
                    "vpn_asn": 60000
                }
            }
        }
    ],
    "device_roles": [
        "ACI IPN"
    ],
    "device_types": [
        "ABC"
    ],
    "manufacturers": [
        "Cisco"
    ],
    "primary_ip4": "x.x.x.x",
    "racks": [
        "ABC"
    ],
    "sites": [
        "ABC"
    ],
    "tenants": [
        "XYZ"
    ]
}
```

### PR DESCRIPTION
**Pull request by nikkytub**
##### SUMMARY
Config-context as an opt-in in netbox dynamic inventory.
Fixed #50342

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Config-context as an opt-in in netbox dynamic inventory

##### ADDITIONAL INFORMATION
Please check #50342 for additional information

### CODE REVIEW

**Comment by nikkytub** [comment]
@gundalow Could you please review and merge it?

**Comment by nikkytub** [comment]
@sieben @Anthony25 @FragmentedPacket @pilou- Please review the changes

**Review by gundalow — APPROVED** [review]

**Comment by remyleone** [comment]
Could you put some documentation about what config-contexts are? Is there a page of documentation about what it is?

**Comment by nikkytub** [comment]
@sieben It is a very interesting feature. We are using it to store many info like VRF config for our routers, to store IP addresses of syslog servers etc. Please check the official documentation for more info here https://netbox.readthedocs.io/en/latest/additional-features/context-data/

**Comment by remyleone** [comment]
Could you add it in the description inside the documentation block?

**Comment by nikkytub** [comment]
Sure

**Comment by nikkytub** [comment]
@sieben Done:)

**Comment by sieben** [comment]
LGTM

**Comment by gundalow** [comment]
Thanks all, merged and will be released in Ansible 2.8

**Pull request merged**
