### PR TITLE
[2.8] purefa_user: Fix Incorrect parameter used causing crashes. (#57588)

### PR DESCRIPTION
**Pull request by resmo**
(cherry picked from commit 35dcd231be4f0afe2e1ee7a53769b3de1cc5222f)

##### SUMMARY
backport of #57588

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
purefa_user

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by abadger** [comment]
@resmo, I don't think we'd usually change the return value in an already released ansible as it could break user's playbooks.  You could add the new value to 2.8 to help people transition to the new value, though.

**Comment by abadger** [comment]
Note to self: I checked the renaming of api_token to api in the parameters and that should be allowed as a backport because there was already an api_token from the common argspec so both parameters couldn't be used at the same time before.

**Comment by sdodsley** [comment]
shipit

**Comment by abadger** [comment]
Merged for the 2.8.2 release.

**Pull request merged**
