### PR TITLE
Made vmnics attribute optional

### LINKED ISSUE #62643: vmware_dvs_host marks vnics as mandatory
##### SUMMARY
Setting vnics is mandatory when adding hosts to a dvs. While this is good in most cases, there are some in which you deliberately not willing to assign any physical uplinks to the dvs (ie: when there will be and agent VM handling the uplink traffic)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_dvs_host 

##### ANSIBLE VERSION
```paste below
ansible 2.8.2
  config file = /home/loci/.ansible.cfg
  configured module search path = [u'/home/loci/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Jul  9 2019, 16:43:02) [GCC 8.3.0]

```
Tested with latest module version from git: (#59221) / d9b9e07d0b12c888763085e16457133dd3dd13f2

##### CONFIGURATION

```paste below
DEFAULT_SCP_IF_SSH(/home/loci/.ansible.cfg) = smart
HOST_KEY_CHECKING(/home/loci/.ansible.cfg) = False

```

##### OS / ENVIRONMENT
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

##### STEPS TO REPRODUCE

```yaml

- name: Add all nodes to all dvSwitches
  tags:
    - add_hosts_to_dvs
  vmware_dvs_host:
    hostname: '{{ hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    switch_name: '{{ dvs.switch_name }}'
    #    vmnics: '{{ dvs.uplink_interfaces }}'                                                          
    state: present
    esxi_hostname: '{{ hostvars[item].fqdn }}'
  delegate_to: localhost
  loop: '{{ groups["esxis"] }}'

```

##### EXPECTED RESULTS

I'd expect the dswitch to be created an the host without a physical nic plugged into it (the same way it can be done via the vSphere Web interfaces.

##### ACTUAL RESULTS

```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_dvs_host_payload_Aamtme/ansible_vmware_dvs_host_payload.zip/ansible/module_utils/basic.py", line 1540, in _check_required_arguments
    check_required_arguments(spec, param)
  File "/tmp/ansible_vmware_dvs_host_payload_Aamtme/ansible_vmware_dvs_host_payload.zip/ansible/module_utils/common/validation.py", line 193, in check_required_arguments
    raise TypeError(to_native(msg))

failed: [vcenter1 -> localhost] (item=host9) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "esxi_hostname": "<sensitive info removed>", 
            "hostname": "<sensitive info removed>", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "state": "present", 
            "switch_name": "<sensitive info removed>", 
            "username": "administrator@<sensitive info removed>", 
            "validate_certs": "no"
        }
    }, 
    "item": "host9", 
    "msg": "missing required arguments: vmnics"


```

This seems to do the trick:
diff vmware_dvs_host.py vmware_dvs_host.py.new
270c270
<             vmnics=dict(required=True, type='list'),
---
>             vmnics=dict(required=False, type='list'),

### PR DESCRIPTION
**Pull request by nemethloci**
##### SUMMARY

Set vmnics attribute to be optional

Fixes: #62643

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Review by goneri — CHANGES_REQUESTED** [review]
Looks good to me, could you just please add a changelog entry: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs

This module does not have any functional-test coverage, it would be great if you can add one too. This is not a blocker.

**Comment by nemethloci** [comment]
Please check and let me know, if this is what was missing still (sorry for long delay). Unfortunately I didn't have resources for the tests (I have no access to vcenter currently, nor much time).

**Comment by nemethloci** [comment]
Hi, please check the commits tabs, I had to rebase since I requested the review.

**Comment by nemethloci** [comment]
> Looks good to me, could you just please add a changelog entry: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs
> 
> This module does not have any functional-test coverage, it would be great if you can add one too. This is not a blocker.

done.

**Comment by mnecas** [comment]
-label ovirt

**Comment by goneri** [comment]
Hi!

Thank you for your PR. Since March 2, 2020, the Ansible team does not accept any new changes on the VMware modules on the core `ansible/ansible` repository.
The development continue but in the new VMware collection repository: https://github.com/ansible-collections/vmware
We have no way to properly migrate a Github issue  between the two projects. Could you please reopen the PR there? https://github.com/ansible-collections/vmware

@nemethloci, please ping me once the PR is migrated. I will merge it.

Links:
- https://groups.google.com/forum/#!msg/ansible-devel/6UAfogEDtG8/wMTgxBGWCgAJ
- https://github.com/ansible-collections/overview/blob/master/README.rst

needs_info

**Comment by goneri** [comment]
Superseded by https://github.com/ansible-collections/vmware/pull/186 . Thanks @nemethloci for the new PR.

**Pull request closed without merging**
