### PR TITLE
Add support for CA SAAM sesu prompt

### PR DESCRIPTION
**Pull request by aburegaiba**
##### SUMMARY

Add support for "computer associates technologies" SAAM
    add waiting message for Privilege escalation with "sesu"

##### COMPONENT NAME
play_context.py

##### ANSIBLE VERSION
 2.5

##### ADDITIONAL INFORMATION
https://docops.ca.com/ca-privileged-identity-management/12-8/en/reference/reference-guide/sesu-utility-substitute-user/

### CODE REVIEW

**Comment by samdoran** [comment]
The existing prompt regexp, which is case insensitive, matches this prompt: `(\w+\'s )?Password|...[truncated]`

**Comment by aburegaiba** [comment]
The regex " (\w+\'s )?Password " doesn't work with the waiting message for Privilege escalation with "sesu" : "Please enter your password"

for example : 

```
cat hosts.reset.sesu
[...]
[reset:vars]
ansible_connection=ssh
ansible_become_exe="sesu -"
become_method=su


ansible all -i hosts.reset.sesu --become -u **** -kK -m command -a 'bash -c hostname' -vvv
<s***************> ESTABLISH SSH CONNECTION FOR USER: ****
<s***********> SSH: EXEC sshpass -d25 ssh -o ControlMaster=no -o StrictHostKeyChecking=no -o User=***** -o Connel9985784 '/bin/sh -c '"'"'chmod u+x /home/*********/.ansible/tmp/ansible-tmp-1523007813.01-8681883777749/ /home/***ansible-tmp-1523007813.01-8681883777749/command.py && sleep 0'"'"''
<s***********> ESTABLISH SSH CONNECTION FOR USER: ****
<s********> SSH: EXEC sshpass -d25 ssh -o ControlMaster=no -o StrictHostKeyChecking=no -o User=*****-o Connes********** '/bin/sh -c '"'"'sesu - -H -S  -p "[sudo via ansible, key=*******] password:h -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-*******; /usr/bin/python /home/******/.ansible1523007813.01-8681883777749/command.py; rm -rf "/home/******/.ansible/tmp/ansible-tmp-1523007813.01-8681883777749&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
s********4 | FAILED | rc=0 >>
MODULE FAILURE

s********2 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n",
    "unreachable": true
}

```

**Comment by samdoran** [comment]
Ok. I couldn't find an example of the prompt from reading the linked docs.

**Comment by alikins** [comment]
This needs a test case for the new regex.

**Comment by abadger** [comment]
@aburegaiba Please show us output of what the prompt is.  From testing with my guesses as to what the prompt is from:
> "sesu" : "Please enter your password"

either the old regex will work or the new regex will also fail to match.  We need to see the actual su - prompt output to evaluate this change.

**Comment by samdoran** [comment]
After some discussion, the best path forward is to make this configurable rather than adding another hard coded prompt string. Leaving this open until a user configurable option is added.

**Comment by abadger** [comment]
Okay... is the prompt: ```Please enter your password:``` ?

**Comment by aburegaiba** [comment]
yes is it

**Comment by aburegaiba** [comment]
a example of privilege escalation with "sesu" : 

$ sesu -
Please enter your password:

**Comment by aburegaiba** [comment]
if bad password : 
sesu -
Please enter your password:
Please enter your password:
Please enter your password:
Too many password attempts
#return to prompt

if empty exit :
sesu -
Please enter your password:
#return to prompt

**Comment by Mathhhh** [comment]
Hi,
I am very interested in a support for CA SAAM sesu prompt.
Is there any possibility to add it ?

**Comment by maxamillion** [comment]
This is still waiting on a test case for the new regex to ensure an untended regression doesn't pop up later on.

needs_revision

**Comment by Akasurde** [comment]
I think, PR #50991 supersedes this PR. Please correct me if I am wrong. cc @sivel

**Pull request closed without merging**
