### PR TITLE
Make use of LocalConnection explicit

### PR DESCRIPTION
**Pull request by sfromm**
Various changes to make LocalConnection explicit:
- Added -c, --connection option to ansible
- Added 'connection' awareness to playbook

I also added a DEFAULT_TRANSPORT constant that sets the default transport in playbook and runner.

### CODE REVIEW

**Comment by mpdehaan** [comment]
urg, the fix to make parser options not dicts anymore and institute sorting via SortedOptParser or whatever has caused this to conflict.

Can you git rebase off of the integration branch and resubmit this?

Thanks!

**Comment by mpdehaan** [comment]
if you don't want to merge this or get stuck, let me know, and I can see what it will take.

**Comment by sfromm** [comment]
I updated my localconnection branch.  Take a look and let me know if that works.  Thanks.  :-)

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
