### PR TITLE
Add support for requirements & control_requirements to module-formatter,...

### PR DESCRIPTION
**Pull request by jpmens**
... ansible-doc, templates (rst, man)

as discussed on the mailing-list today.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Nice to have!

you will need to fix this part:

+requirements: [ Python I(urllib2) and I(urlparse) modules ]

requirements should be an array of strings.

**Comment by jpmens** [comment]
It _is_ an array of strings, and it's handled thusly; that is just an example using inline formatting.

**Comment by jpmens** [comment]
changed anyway

**Comment by mpdehaan** [comment]
"and" is legal in YAML, that's new to me, regardless the C(foo) was also not machine readable.

**Comment by mpdehaan** [comment]
not seeing updated pull request ATM, btw

**Comment by jpmens** [comment]
There it is

**Comment by mpdehaan** [comment]
great, in queue for testing, thanks!

**Comment by jpmens** [comment]
Is there something missing on this? I assume you've had tons to do, but I'd have thought this teeny tiny little patch would make it for 1.1. ;-)

**Comment by mpdehaan** [comment]
It hasn't been on the forefront of the things I've needed to test since it was doc related, but I'll take a look at it.

**Comment by mpdehaan** [comment]
Merged.

Note that I corrected the docs for get_url to not include requirements on things that are already in core python.

I also tweaked the formatting of the list of requirements to use HTML list elements, in hopes that it would maybe be a bit more semantic.

Good stuff, thanks!

**Pull request closed without merging**
