### PR TITLE
 mysql_user support REQUIRE NONE to remove a REQUIRE SSL "GRANT

### PR DESCRIPTION
**Pull request by Alexander198961**
Fixes for:
[https://github.com/ansible/ansible/issues/53604](https://github.com/ansible/ansible/issues/53604)
[https://github.com/ansible/ansible/issues/29811](https://github.com/ansible/ansible/issues/29811)
COMPONENT NAME
mysql_user
ANSIBLE VERSION
ansible 2.7.10

Need do some modifications

### CODE REVIEW

**Comment by Alexander198961** [comment]
I will do some testing

**Comment by Alexander198961** [comment]
@gundal Does this make sense try to split this pr because I am trying to fix two issues #53604
#29811 ?
Thnaks

**Comment by bmalynovytch** [comment]
@Alexander198961 Are the fix common or do they share some bits of code ?
If yes, then one branch / PR is fine, otherwise, splitting will make things easier to test & review.

**Comment by Andersson007** [comment]
@Alexander198961 could you please split this and move to https://github.com/ansible-collections/community.general

**Comment by Akasurde** [comment]
@Alexander198961 Any news? 


needs_info

**Comment by Alexander198961** [comment]
i will check tomorrow

**Comment by Akasurde** [comment]
Hi @Alexander198961, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.mysql<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
