### PR TITLE
[WIP] Make magic vars available to loops

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Make magic vars available to loops

see #49294 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/executor/task_executor.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bcoca** [comment]
these shoudl be derived from the connection plugins, not play context, since they can have additional overrides that play context currently ignores

**Comment by sivel** [comment]
> these shoudl be derived from the connection plugins, not play context, since they can have additional overrides that play context currently ignores

This PR just reuses the existing code within `TaskExecutor` that adds these magic vars.  Basically making these vars that are accessible in `TaskExecutor._execute` accessible within `TaskExecutor._get_loop_items`

The goal isn't really to change the fundamental functioning of how `TaskExecutor` builds it's vars that a task will have access to.

**Comment by bcoca** [comment]
but those are not the final value, that gets composed in the plugins, but you are now giving the user access to 'intermediate values'.

**Comment by sivel** [comment]
> but those are not the final value, that gets composed in the plugins, but you are now giving the user access to 'intermediate values'.

Wouldn't they already have access to them?  I'm not sure what point you are making.

Are you concerned that by doing this earlier in `run` that they may not be final but would be finalized in `_execute`?

I'm not sure how better to allow loop to use magic vars that a task should later be able to use anyway.

**Comment by bcoca** [comment]
But that is something we might still need to build into the plugins, i.e 'local' uses ` getpass.getuser()` to set remote_user (ignoring the play_context value) .. and it does nothing to return/publish/display that value, much less update `ansible_user`.

**Comment by bcoca** [comment]
> Wouldn't they already have access to them? I'm not sure what point you are making.

no, not really, they might have access to specific variables that are used to create the final values, but the value you are exposing is an intermediate one, which might not make any sense to the user at that point.

> Are you concerned that by doing this earlier in run that they may not be final but would be finalized in _execute?

somewhat, but even in _execute we are not populating these vars with the final value, since task_executor never uses them, only the plugins themselves have the final value, this is why I was saying we might need to add a facility to the plugins to populate them.

**Pull request closed without merging**
