### PR TITLE
Bugfix for os_coe_cluster_template module  (#54819)

### LINKED ISSUE #54819: os_coe_cluster_template can't handle labels and docker_storage_driver well
##### SUMMARY

The current choices for param docker_storage_driver misses 'overlay2'.
Param labels only accept string data type, and can not handle extra spaces or tailling newline well in key/value strings.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_coe_cluster_template

##### ANSIBLE VERSION

```
2.8.0.dev0
```

##### CONFIGURATION

```
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```
coe_template.yml
---
tasks:
    - include_vars: "var.yml"
    - name: Create a new Magnum template
      os_coe_cluster_template:
        state: present
        name: "{{ template_name }}"
        coe: kubernetes
        image_id: "{{ image }}"
        keypair_id: "{{ key_name }}"
        external_network_id: "{{ public_net }}"
        public: no
        flavor_id: "{{ node_flavor }}"
        master_flavor_id: "{{ master_flavor }}"
        floating_ip_enabled: yes 
        network_driver: calico
        volume_driver: cinder
        docker_storage_driver: "{{ docker_storage_driver }}"
        labels: "{{ template_labels }}"

var.yml

---                            
                               
image: xxxxxxxxxxxxxxx
public_net: xxxxxxxxxxxxxxxx
key_name: xxxxxxxxxxxxxx
master_flavor: c1.c2r4         
node_flavor: c1.c4r8           
docker_storage_driver: overlay2                                                                                                                                                               
......
template_labels: >-             
  container_infra_prefix = {{ container_infra_prefix }},
  kube_tag = {{ version }},    
  cloud_provider_enabled = true,
  cloud_provider_tag = {{ cloud_provider_tag }},
  ingress_controller = octavia,
  octavia_ingress_controller_tag = {{ octavia_ingress_controller_tag }},
  heat_container_agent_tag = {{ heat_container_agent_tag }},
  etcd_volume_size = 20,       
  docker_volume_size = 20,     
  prometheus_monitoring = true 
```

##### EXPECTED RESULTS

The call will be succeed and the coe cluster template will be created successfully.

##### ACTUAL RESULTS

```
For docker_storage_driver:
value of docker_storage_driver must be one of: devicemapper, overlay, got: overlay2

For labels:
If you pass with a dict data type, it will return 400 Bad request.
If you pass with a string data type, with spaces/tailling newline, the template will create with the wrong label attributes, like:
{u' prometheus_monitoring ': u' true"\n', u' cloud_provider_enabled ': u' true', u' octavia_ingress_controller_tag ': u' 1.14.0', u' kube_tag ': u' v1.13.5', u' ingress_controller ': u' octavia', u' etcd_volume_size ': u' 20', u' docker_volume_size ': u' 20',  u' cloud_provider_tag ': u' 1.14.0', u' heat_container_agent_tag ': u' stein-dev'}

It will cause Magnum fail to parse these labels and use the defaults without throwing any exception.
```

### PR DESCRIPTION
**Pull request by NewpTone**
* Support 'overlay2' in docker_storage_driver

* Fixed the data type in labels

* Improve string process with parsing labels

##### SUMMARY

Fixes #54819

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

os_coe_cluster_template

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mnaser** [comment]
shipit

**Comment by openstacker** [comment]
@emonty  @mnaser  could you please help review this one? Thank you very much.

**Comment by mnaser** [comment]
shipit

**Review by cloudnull — APPROVED** [review]
shipit

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Pull request merged**
