### PR TITLE
win_regedit: Cleanup, check/diff mode support, HKCC fix

### LINKED ISSUE #20283: win_regedit: Idempotency issue
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_regedit

##### ANSIBLE VERSION

v2.3

##### OS / ENVIRONMENT

Windows 10

##### SUMMARY

When I run the following task:
```yaml
  - name: Enable VideoLan Client for ISO images
    win_regedit:
      key: 'HKCR:\Windows.IsoFile\shell\Open\command'
      value: '(default)'
      data: '"%ProgramFiles%\VideoLAN\VLC\vlc.exe" --started-from-file "%1"'
      datatype: 'expandstring'
```

It reports a change the first time:
```
TASK [Enable VideoLan Client for ISO images] ***********************************************************
changed: [computer61] => (item={u'type': u'expandstring', u'data': u'"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe" --started-from-file "%1"', u'value': u'(default)', u'key': u'HKCR:\\Windows.IsoFile\\shell\\Open\\command'}) => {"changed": true, "data_changed": false, "data_type_changed": false, "item": {"data": "\"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe\" --started-from-file \"%1\"", "key": "HKCR:\\Windows.IsoFile\\shell\\Open\\command", "type": "expandstring", "value": "(default)"}}
```

And an error every subsequent run:
```
TASK [Enable VideoLan Client for ISO images] ***********************************************************
failed: [computer61] (item={u'type': u'expandstring', u'data': u'"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe" --started-from-file "%1"', u'value': u'(default)', u'key': u'HKCR:\\Windows.IsoFile\\shell\\Open\\command'}) => {"changed": false, "data_changed": false, "data_type_changed": false, "failed": true, "item": {"data": "\"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe\" --started-from-file \"%1\"", "key": "HKCR:\\Windows.IsoFile\\shell\\Open\\command", "type": "expandstring", "value": "(default)"}, "msg": "Property (default) does not exist at path HKEY_CLASSES_ROOT\\Windows.IsoFile\\shell\\Open\\command."}
```

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

win_regedit

##### ANSIBLE VERSION

v2.3

##### SUMMARY

The following changes have been made:
- Added check-mode support
- Added diff support
- Corrected HCCC to HKCC (according to windows documentation)
- Updated documentation, and examples
- Added -aliases support to module_utils/powershell.ps1
- Renamed `key > value > data` to `path > name > data`
- Re-indented code and consistency changes
- Implemented REG_NONE support

This fixes #20283, #20343 and #20595

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Looks good to me, but haven't tested it yet. Just wondering if you haven't checked in the win_regedit.py as you mention updated docs and examples but only .ps1 in this PR?

**Comment by dagwieers** [comment]
@jhawkesworth Still working on the docs.

I am open for non-destructive registry updates for each of the registry hives :-)
Like:
```yaml
    - name: Disable Keyboard layout hotkey for all users
      key: HKU:\.DEFAULT\Keyboard Layout\Toggle
      value: Layout Hotkey
      data: 3
      datatype: dword
    - name: Disable Language hotkey for current users
      key: HKCU:\Keyboard Layout\Toggle
      value: Language Hotkey
      data: 3
      datatype: dword
```

**Comment by dagwieers** [comment]
I am not happy that this module uses:

    key > value > data

whereas the convention in Windows is:

    path > name > value

So while I would prefer to add aliases to make it work, the `value:` parameter (which is not really a value, but rather an entry) conflicts with prior usage. So we cannot make it use the normal convention.

I do want to get rid of the `value:` parameter though. That is plain wrong and confusing.
Naming is too important to fuck it up in this way :-(

**Comment by dagwieers** [comment]
@nitzmahone This one is also for you. I added aliases support to `Get-AnsibleParam` because I needed it here (and I didn't want any cascading code in the module for a required parameter).

**Comment by jhawkesworth** [comment]
Aliases would be useful to have in powershell.ps1 - from memory win_file could be simplified with this as src and path (and possibly something else) are synonymous.

I'd prefer if changes to powershell.ps1 were in separate PRs just in case of a need to backout a particular changeset.  I am probably being overly cautious though as most likely would just make a new change if it needed it.

**Comment by dagwieers** [comment]
@jhawkesworth I agree, but then I cannot build on them until they are merged. Or it becomes hell to manage it.

**Comment by dagwieers** [comment]
@joshludwig @smadam813 @jctanner @nitzmahone Can someone review and test this ?
The change to powershell.ps1 was reviewed/approved by @nitzmahone yesterday.

**Comment by dagwieers** [comment]
And obviously it has been working fine in production for my use-cases.

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by jhawkesworth** [comment]
Had a quick look and the integration test failed last time (its re-running again at the moment) 'cos it was expecting
'key: HKCU\\Software is not a valid powershell path, see module documentation for examples.'
but following the aliasing stuff its returning

'path: HKCU\\Software is not a valid powershell path, see module documentation for examples.'

i.e. doesn't match because. 'key' has become 'path'.

The important thing about that test is that it catches invalid paths which from memory caused powershell to return an unhelpful message, so in this case I think its ok just to change the test.

**Comment by jhawkesworth** [comment]
The change would be somewhere near ansible/test/integration/targets/win_regedit/tasks/main.yml L32

**Comment by dagwieers** [comment]
@jhawkesworth Thanks for that !

CI was down and seems to be stuck now so I didn't see any of the integration test failures.
Let's see if Shippable is working now, sigh...

**Comment by dagwieers** [comment]
Shippable bails out again with:

    ERROR: 500: An error occurred (InstanceLimitExceeded) when calling the RunInstances operation: Your quota allows for 0 more running instance(s). You requested at least 1

**Comment by mattclay** [comment]
@dagwieers I've switched our Windows CI back over to AWS region us-east-1 where our instance limit is higher, until our limit increase goes through on us-east-2, where the tests were running. I've also restarted CI for this PR.

**Comment by mattclay** [comment]
@dagwieers Tests are now failing with legitimate errors:

```
            At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1485447159.85-84805739460372\win_regedit.ps1:418 char:5
+ if ($name.ToLower() -eq "(default)") {
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dagwieers** [comment]
Thanks @mattclay, appreciated !

BTW Yes, I am fixing it right now.

**Comment by dagwieers** [comment]
@mattclay I am also surprised to see that the tests take 31mins to complete (or rather fail). That is a rather long time to test a single module.

**Comment by mattclay** [comment]
@dagwieers Actually, all Windows tests are running, per the Shippable output:

```
2017-01-26 16:41:17 Mapping 4 changed file(s) to tests.
2017-01-26 16:41:17 lib/ansible/module_utils/powershell.ps1 -> windows-integration: all (targeted)
2017-01-26 16:41:17 lib/ansible/modules/windows/win_regedit.ps1 -> windows-integration: win_regedit (targeted)
2017-01-26 16:41:17 lib/ansible/modules/windows/win_regedit.py -> windows-integration: none
```

If the changes were isolated to `win_regedit` then only those tests would run.

**Comment by dagwieers** [comment]
@mattclay Here we go again (in 15 mins):

    ERROR: Timeout waiting for windows/2008-SP2 instance 90e352b7-db9d-4298-bbf5-203b9df5b85a.

**Comment by mattclay** [comment]
@dagwieers: Fresh errors from CI:

```
            At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1485455327.39-58934777178159\win_regedit.ps1:556 char:46
+         } elseif (Test-ValueData -Path $path -Value $name) {
+                                              ~~~~~~
```

**Comment by dagwieers** [comment]
@mattclay Maybe I should invest some time in running these tests locally. However last time that proved to be more difficult than expected.

**Comment by mattclay** [comment]
@dagwieers Actually, @gundalow and I wanted to talk to you about that. You can use `ansible-test` to run the tests without involving Shippable or a PR. When you have time, just ping one of us on IRC.

**Comment by dagwieers** [comment]
@mattclay @jhawkesworth @nitzmahone @trondhindenes @JimFicarra @dav1x @jctanner Please review and test this.

I would like to start using the `-aliases` functionality in some other modules. (See #20671 and #20672)
So I need 2 shipits !

**Comment by jhawkesworth** [comment]
here's one

shipit

**Comment by gundalow** [comment]
@joshludwig @smadam813 I believe you two are the maintains for this module, could you please let me know if you are happy with these changes, thanks.

**Comment by trondhindenes** [comment]
shipit, taking the liberty of merging this in since you guys are depending on it for other things.

**Comment by trondhindenes** [comment]
we should probably revisit how we figure out the path type (reg vs filesystem) - i prefer get-psdrive to regexing, but that can wait - seems to be working fine as-is.

**Pull request merged**
