### PR TITLE
Add Homebrew installation option

### PR DESCRIPTION
**Pull request by robynlarsen**

### CODE REVIEW

**Comment by bcoca** [comment]
Sorry, but we don't recommend using homebrew to install ansible and have removed it from our docs to minimize its use. 

As such I'm going to pass on this request.

**Comment by robynlarsen** [comment]
@bcoca is there a reason homebrew isn't recommended?

**Comment by bcoca** [comment]
yes,  do to the homebrew package mangling ansible internals, creating a slew of user issues.

After trying to fix the issues with the packages we got nowhere, so we 'unlisted' homebrew as a way to minimize the number of issues from users (worked!).

**Comment by robynlarsen** [comment]
Thanks @bcoca

**Pull request closed without merging**
