### PR TITLE
docker modules: add missing option types

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This adds all missing option types for the docker modules.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docker_compose
docker_config
docker_container
docker_container_facts
docker_image
docker_image_facts
docker_login
docker_network
docker_network_facts
docker_secret
docker_stack
docker_swarm
docker_swarm_service
docker_volume

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @hannseman since this affects docker_swarm_service as well

**Review by danihodovic — APPROVED** [review]

**Comment by felixfontein** [comment]
Things to do:
- remove things like `required=False` and `default=None`
- order for argument_spec: `type`, `required`, `default`, `choices`, ...
- order for options docs: `description`, `type`, `required`, `choices`, `default`, `added_in_version`, `aliases`

See comments in #52421 by @dagwieers

**Comment by felixfontein** [comment]
I'll rebase another time once #52420 has been merged, then this should be ready to get merged.

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
@danihodovic thanks for reviewing!

**Pull request merged**
