### PR TITLE
Update zabbix template role

### PR DESCRIPTION
**Pull request by aminmaghsodi**
There was a bottleneck in role zabbix_template which force the user to define template_name in all use cases and it was unneeded. for example when users want to import a zabbix template json, it has its name.
There was another bottleneck too. almost all the templates on repositories are in  xml format, so we couldn't use them because it just accepts json, So support for xml templates added in this patch.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

zabbix_template
##### ANSIBLE VERSION

2.5.0
```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by eikef** [comment]
This looks good to me, although some of the comment/linebreak changes were IMHO unnecessary -- still, not a showstopper.

shipit

**Comment by D3DeFi** [comment]
yep, ok with the changes as well. Would be nice to have `required_one_of=['template_name', 'template_json']` instead of conditionals, but still fine.
shipit

**Review by resmo — CHANGES_REQUESTED** [review]
the docs https://github.com/ansible/ansible/pull/40431/files#diff-1bb9ed3a0fde03d49a28d67008d04eb4L45 of `template_name` must be updated as well and add a note, that the default changed:

~~~diff
 template_name:
          description:
              - Name of zabbix template.
+             - Optional since version 2.7.
-        required: true
~~~

Further to me it is not clear, when a template_name is required and when not, could you explain this a bit? Can we say that either template_json or template_name is required?

please ping me again, when ready.

**Comment by aminmaghsodi** [comment]
@resmo I added a new description.

**Comment by aminmaghsodi** [comment]
I added a new patch for this.

**Pull request closed without merging**
