### PR TITLE
[WIP] New module: Add apache2_conf module (web_infrastructure/apache2_conf)

### PR DESCRIPTION
**Pull request by urajio**
##### SUMMARY
This module use a2enconf/a2ensite same way as apache2_module use a2enmod.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
apache2_fragment

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/div/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION
The functionality of this module can be easily extended in the future to completely replace the apache2_module.

### CODE REVIEW

**Comment by nerzhul** [comment]
name seems unclear to me, fragment make me think about a fragment part in a configuration file, do you have a better name ?

**Comment by urajio** [comment]
Hi @nerzhul, Could you advise something? English is not my native language, I just took this term from man a2enconf(8).

**Comment by nerzhul** [comment]
apache2_conf seems better

**Comment by robinro** [comment]
Thanks @urajio for this module. On a quick view the code looks really clean.

I also like `apache2_conf` more than `fragments`.
Please also note in the docs which distros are supported. As far as I see it only works on debian/ubuntu.
A nice error message for non-ubuntu systems would also be nice, which you can get by checking for the `available_dir` or the `a2en*` binary.

To fully replace `apache2_module` one would also need to support the suse based systems, which in general don't have a2ensite, a2enconf.

It would be nice to have integration tests. This would also clarify the supported distros in the test code.

Not sure you are aware: There are previous proposals for similar modules: https://github.com/ansible/ansible/pull/7521 https://github.com/ansible/ansible-modules-extras/pull/1240
Maybe some of the discussion/code there can be helpful.

@n0trax Maybe you also want to review this?

**Comment by n0trax** [comment]
First of all...Thanks to @urajio for this module.

What about splitting this module in two separate modules? apache2_site and apache2_conf
In my opinion it makes more clear, what the purpose of the module is. What do you think?

An apache2_site module can reuse some code of the apache2_module. Maybe we can add apache2.py to module_utils.

IMHO it is better to use the apache binary to detect if a site is enabled or disabled. This could be done with '-t -D DUMP_VHOSTS' similar to the '-M' switch in the apache2_module. 
Unfortunately there is no switch for detecting activated files in conf-enabled.

Does anyone know if there are plans to add a2ensite/a2dissite... to OpenSUsE?

And of course I agree with @robinro...Integration tests would be very nice ;-)

**Comment by urajio** [comment]
Hi @n0trax,
I agree that it will be better to split module, but I plan to do it later. Here is my TODO for now:
1. add Integration tests
2. add site "priority number", or "tag" to the module parameters. To be able to control the order of sites inclusion in the Apache configuration.
3. add apache2 module management code
4. split code to module_utils/apache2.py and module/apache2_conf, _site, _module

I do not think it would be better to check the site with Apache binary: firstly, the site can be defined anywhere in the Apache configuration, not only in the files from the directory sites-avavilabile. Secondly, a2ensite/a2dissite does not do this.

**Comment by robinro** [comment]
If you stick to a2ensite and debian/ubuntu, the best approach imo is looking for the files.

The module names and APIs should be fixed before this gets merged, so I'm looking forward to you finishing the list you posted.

**Comment by gundalow** [comment]
Hi,
Thanks for the new module, and the existing reviews.
I've added the `[WIP]` prefix to the subject, please remove that once you've completed your to do list.

**Comment by gundalow** [comment]
Nice to see tests being added, thanks for that.

We've recently improved the documentation for module development, you may find some useful info in https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html

**Comment by n0trax** [comment]
@robinro @urajio I agree with you, the best approach to check for the enabled/disabled site/config is to look for the files.

The  `-D DUMP_VHOSTS` switch shows only activated sites. E.g. if there is a conditional around a vhost config, like `<IfModule mod_ssl.c>` and the ssl module was not loaded, the vhost will not appear via DUMP_VHOSTS.

What do you think about using this behavior to detect inactive site configurations? Maybe as a optional module parameter to display a warning/hint if a site configuration is enabled, but not active within apache?

**Comment by urajio** [comment]
I want to clarify: this module is not designed to enable / disable Apache modules or VirtualHosts, it is designed to enable / disable configuration files.
There is no way to know exactly what these configuration files do - for this you would have to write the complete Apache configuration parser and partially emulate its internal logic.

**Comment by n0trax** [comment]
@urajio I agree with you completely.

With my propose I don't want to detect a enabled or disabled VirtualHost or module. The intention is to check, whether the configuration file, that is enabled, is visible in httpd. In my opinion this can be a hint if a module is missing or something. In short....it can be helpful for debugging in some cases.

**Comment by urajio** [comment]
@n0trax how can this be done?

**Comment by n0trax** [comment]
@urajio this can be done with `apache2ctl -t -D DUMP_VHOSTS`, `-t` is running a syntax check for the configuration files and `-D DUMP_VHOSTS` is dumping details of the virtual hosts configuration.

A simple example...you have a webserver with disabled mod_ssl and want to enable the ubuntu default_ssl vhost.
```
# apache2ctl -M | grep ssl
# a2ensite default-ssl.conf 
Enabling site default-ssl.
To activate the new configuration, you need to run:
  service apache2 reload
# apache2ctl -t -D DUMP_VHOSTS
VirtualHost configuration:
```
With the disabled ssl module, the default-ssl vhost is not active. Maybe this is not the result you want.
```
# a2enmod ssl
# apache2ctl -t -D DUMP_VHOSTS
VirtualHost configuration:
*:443                  lolcathost (/etc/apache2/sites-enabled/default-ssl.conf:2)
```
After enabeling the ssl module the default-ssl.conf appears in the list of the active vhosts. Maybe this can also be used to check for a specific vhost that should be active.

IMHO this gives a useful feedback to the user, but I also think this can be implemented later. What do you think?

**Comment by urajio** [comment]
@n0trax yes, this can be done for Debian. But SuSE generate config with new settings only at Apache (re)start.

**Comment by n0trax** [comment]
@urajio you have a2ensite and a2dissite as requirements in the module documentation, so i think your module will not support SuSE.

As far as I know the SuSE vhost configuration is located in /etc/apache2/vhost.d and not managed by sysconfig, am I right?
The apache configuration is also generated on a apache2ctl call, not only with a (re)start.

**Comment by dagwieers** [comment]
-label windows

**Comment by samccann** [comment]
Hi @urajio Unfortunately we are no longer accepting new content submissions into the Ansible project, but instead you should create an Ansible Content Collection and publish it on Ansible Galaxy. 

Developing a Collection: https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#developing-collections

Creating a Galaxy namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html

Hope this helps!

**Pull request closed without merging**
