### PR TITLE
Test service enabled during check run (from bug report)

### PR DESCRIPTION
**Pull request by gtrafimenkov**
##### ISSUE TYPE
- Bug Demonstration Pull Request
##### ANSIBLE VERSION

```
ansible 2.2.0 (bug-service-enabled-during-check-run f6859a426e) last updated 2016/07/09 20:58:44 (GMT +000)
  lib/ansible/modules/core: (detached HEAD db8af4c5af) last updated 2016/07/09 15:54:05 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 618e740d52) last updated 2016/07/09 15:54:05 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This pull request demonstrates a bug in the service module.  Integration tests are expected to fail on Debian 7, Ubuntu 12.04, Ubuntu 14.04 until the bug is fixed.

### CODE REVIEW

**Comment by bcoca** [comment]
note that bug was just for update-rc.d but the test seems to cover many diff init systems (good thing)

**Comment by mattclay** [comment]
@gtrafimenkov These tests should be run together with the destructive tests on Shippable to avoid slowing down CI by launching additional jobs.

**Comment by mattclay** [comment]
@gtrafimenkov Thank you for submitting additional tests.

If you will be submitting a PR to fix the bug exposed by these new tests, please include a reference to this PR. If not, please open an issue describing the bug and reference this PR. This way the tests can be merged once the bug has been fixed.

**Comment by bcoca** [comment]
@mattclay bug has been fixed

**Comment by gtrafimenkov** [comment]
> @gtrafimenkov These tests should be run together with the destructive tests on Shippable to avoid slowing down CI by launching additional jobs.

@mattclay sure, I will make necessary changes and also improve the test itself (it is too hackish at the moment)

**Comment by gtrafimenkov** [comment]
Here is a new improved pull request: https://github.com/ansible/ansible/pull/16739
- I've improved the tests - made them more universal, now they are run on all systems, not only Ubuntu variants
- new tests are run together with other destructive tests, so they don't slow down CI pipeline

**Comment by mattclay** [comment]
@gtrafimenkov Closing this PR since you've opened #16739 as a replacement.

**Pull request closed without merging**
