### PR TITLE
Added host inventory option to zabbix_host_facts module

### PR DESCRIPTION
**Pull request by sky-joker**
##### SUMMARY
This pull request adds an option to get the host inventory to zabbix_host_facts.  
Useful for automation based on host inventory info.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

zabbix_host_facts.py

##### ADDITIONAL INFORMATION
This pull request reflected the following advice.
https://github.com/ansible/ansible/pull/54220

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
Tested in #54220 against all currently supported Zabbix server releases (3.0, 3.4, 4.0).

Works nicely

**Comment by D3DeFi** [comment]
shipit

**Comment by D3DeFi** [comment]
bot_status

**Comment by D3DeFi** [comment]
ok smthing is not probably right with ansibot
bot_broken

**Comment by resmo** [comment]
shipit

**Review by resmo — APPROVED** [review]

**Pull request merged**
