### PR TITLE
Add q/query aliases to lookup

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

Also forces `wantlist=True` when using the alias
Should make using lookups with `loop` much easier

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

L
##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by maxamillion** [comment]
:+1: 

shipit

**Comment by kustodian** [comment]
Like the change, I'm just not sure about the name, because `L` isn't something which will be obvious to the user what it actually does and Ansible is well know for it's readability. And when you think about it it's even harder to search for it on Google, what are you going to type `ansible l command`?

I'm more for `llookup` (aka list lookup), but that is also bad.

**Comment by maxamillion** [comment]
Agreed, `llookup` is more explicit even though it is more typing.

**Review by maxamillion — APPROVED** [review]
Based on feedback from today's ansible-core IRC meeting about the bikeshedding aspect of the change, the code looks good. :+1:

**Comment by sivel** [comment]
My personal opinion about `wantlist` for `q|query` is that it should be forced as true, and not configurable.

**Comment by bcoca** [comment]
@sivel check code, already done

**Comment by sivel** [comment]
> @sivel check code, already done

Awesome, thanks!  I must not have refreshed and was looking at an older version.  👍

**Pull request merged**
