### PR TITLE
Add support for bare git reference repos

### PR DESCRIPTION
**Pull request by cg-soft**
This adds two parameters to the git module:
-  bare (boolean)  Indicates this is to be a bare repositori
-  reference (string) Indicates the path or url to the reference repo. Check out the "--reference" option in the "git clone" man page

Added appropriate tests.

### CODE REVIEW

**Comment by cg-soft** [comment]
I hope I did it right this time. Things start making more sense now, apologies for being a github noob.

**Comment by cg-soft** [comment]
This was #4570, now hopefully done correctly

**Comment by jctanner** [comment]
@cg-soft thank you! extra thanks for adding tests!

**Comment by cliffrowley** [comment]
The git bare option is useful for creating repositories server side that will be pushed to by a client after the fact.  However this module doesn't appear to allow creation of a bare repository without supplying the `repo` parameter.  Was this intentional?

If not, I'd like to respectfully request that the module be modified so that the `bare` option can be supplied without requiring `repo`.  For example:

`git: dest=/var/lib/git/some_repo bare=yes`

I'm no python programmer or I'd have a stab at it myself, however if there's no interest in doing so I guess I'll be forced to give it a stab at some point :-)

Note: I haven't created an issue for this in case it was in fact intentional.

**Comment by cg-soft** [comment]
So you're looking for a wrapper of "git init". I suppose it makes sense.
I'm in the process of adding some other small stuff (see
http://stackoverflow.com/questions/20644613/why-does-git-clone-not-take-a-refspec)
to ensure that one can specify arbitrary refspecs. Not sure when I'll
actually get around to finishing this, so if you're in a hurry, you might
want to try a hand yourself.

**Pull request merged**
