### PR TITLE
Fixed incorrect request body when creating VM snapshot with disks

### PR DESCRIPTION
**Pull request by nemethloci**
##### SUMMARY

disk id was incorrectly set as disk_snapshot_id.

Fixes: 67813

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ovirt_snapshot

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mnecas** [comment]
+1

**Comment by mnecas** [comment]
Thank you for the PR.

**Review by mnecas — APPROVED** [review]
+1

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
