### PR TITLE
Skip parameters that are being deprecated

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
So in most cases when parameters are deprecated, you may not want to
advertise them in the documentation. One reason for this is because
these parameters were not introduced within Ansible but predate
upstreaming them.

So this change avoids reporting parameters that are not documented and
are deprecated. It's only a small subset of the existing E322 errors.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
test sanity validate-modules

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by dagwieers** [comment]
Somehow these reported issues do not show on my system (using python 2.7) and `azure_tags` fragment is not being imported, so this seems false, but unrelated to my change. I will have to ignore that file anyway. **False positive**

**Comment by gundalow** [comment]
Sometimes we may want to deprecate options and still document them, network `provider` being an example of that.

**Comment by dagwieers** [comment]
And this patch doesn't prevent that. Now it generates false positives, which we canceled out.

**Review by gundalow — APPROVED** [review]

**Review by sivel — APPROVED** [review]

**Comment by sivel** [comment]
I'm fine with the code change, looks like gundalow is good with the behavior.  Merging.

**Pull request merged**
