### PR TITLE
ios_config doc example bgp

### PR DESCRIPTION
**Pull request by hemskgren**
##### SUMMARY

add ios_config doc example for bgp
+label: docsite_pr
Issue ansible/community#311

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
2.5.4
```

##### ADDITIONAL INFORMATION

+label: docsite_pr
Issue ansible/community#311

```

```

### CODE REVIEW

**Comment by beeankha** [comment]
@hemskgren As with your other PRs, we'll put this in the testing queue and will update when we're done taking a look!

**Comment by acozine** [comment]
Hi @hemskgren, can you provide a playbook and output showing that your example works? Take a look at #40369 for an example of what we're looking for. The Validation section of ansible/community#311 gives guidelines for what we need. Thanks!

**Comment by samccann** [comment]
@hemskgren - we merged one of your other PRs and would love to merge this one as well, but we need some more verification information. Please add the test playbook, and the output before and after running the playbook. See https://github.com/ansible/community/issues/311 and how @beeankha added these details in https://github.com/ansible/ansible/pull/41253.
Thanks!

**Comment by acozine** [comment]
We're wrapping up the gamification exercise (ansible/community#311) at the end of August. I hope you can add the playbook, playbook output, and proof of state on the network device to this PR before then! If not, though, we'll close it.

You've already got one merged PR, you have 3 open PRs that are so close! If you can get them fixed up and submit one more, you'll win the Ansible swag!

**Comment by acozine** [comment]
Closing this, since we are closing out the network gamification exercise.

**Pull request closed without merging**
