### PR TITLE
Add a note about running in a virtualenv

### PR DESCRIPTION
**Pull request by amenonsen**
Based on a Dec 2013 PR by @sivel, but rephrased by me.

Closes #5335

### CODE REVIEW

**Comment by amenonsen** [comment]
Any thoughts on the wording here? I believe this accurately reflects the present situation, but if it's at all possible to reuse the interpreter that runs ansible for local connections, it would be greatly preferable, since it eliminates the problem altogether.

**Comment by abadger** [comment]
@amenonsen @sivel, I wasn't able to get these instructions to work.  I think you have to activate the virtualenv in addition to using an alternate python binary.  Something like this stackoverflow answer: http://stackoverflow.com/questions/20575084/best-way-to-always-run-ansible-inside-a-virtualenv-on-remote-machines

**Comment by amenonsen** [comment]
@abadger Sorry for the delayed response. I'd never used `virtualenv` before, so I took some time to familiarise myself with it. I believe you're right, of course, it'll need to be activated in `.bashrc` or similar before it's used on the far end of an ssh connection. But I'm not sure what level of detail is appropriate for the Ansible docs in this case. Anyway, given that #5335 languished for two years with neither input nor updates, I suspect the best thing to do might be to close both PRs and accept the status quo until someone more motivated provides a complete description.

**Comment by amenonsen** [comment]
I'm closing this PR now. Unfortunately, neither has #5335 been closed, nor have the outstanding questions been answered; but I never had the necessary expertise to revise the PR, and no longer have the time to try.

**Pull request closed without merging**
