### PR TITLE
Raw module

### PR DESCRIPTION
**Pull request by acasajus**
Added raw module

It's not a real module. It just sends the raw shell command via SSH and gets the result.
This will allow to execute commands even if there's no python/json installed in the target machine

+removed empty spaces

### CODE REVIEW

**Comment by mpdehaan** [comment]
I like this, as it's a good way to install python-simplejson for older machines so that they can run real modules.   This is in queue for review/merger after the 0.3 release today.   Thanks!

**Comment by acasajus** [comment]
That was exactly my thinking :)

**Comment by mpdehaan** [comment]
ok, so from list discussion, we think a better approach is if python-simplejson isn't installed we output using "key=value key=value" format, and maybe output gets truncated or something where it would be hard to quote.   This would prevent complicating the docs.

I will file a ticket about this idea.   If you'd like to work on it, that would be very welcome!

**Comment by mpdehaan** [comment]
https://github.com/ansible/ansible/issues/204

Very sorry that you spent extra work on this and we're not taking it -- though the alternative should be pretty easy.   If you want to avoid PR's possibly not getting taken, it would be a good idea to join the mailing list, and ask first about features maybe.   

There are also other modules that could be similarly modified, if setup could in fact work in that mode, it would even allow basic playbooks to bootstrap hosts.

**Comment by acasajus** [comment]
Is http://groups.google.com/group/ansible-project?lnk=srg the mailing list? I can't find any the thread related to the PR...

**Comment by acasajus** [comment]
I haven't found the thread yet. Anyways, I don't see how to send the stdout and stderr using key=value pairs easily. This module is not just for when simplejson is not there. What if python is not there (like a router with linux) ?

"Not complicating the docs" doesn't seem a really deep motive to avoid this functionality. I'll voluteer to modify the docs to include this if the PR gets pulled in the end.

**Comment by mpdehaan** [comment]
FYI -- looks like I can't just simply reopen this but I can open a ticket to manually merge.

**Comment by acasajus** [comment]
I'll include a link here to the #214 issue :)

**Comment by mpdehaan** [comment]
That link is already linked above.  FYI, I'm still looking at merging this in this week.

**Comment by acasajus** [comment]
Oops. My bad :P

**Pull request closed without merging**
