### PR TITLE
Enhancements to the cobbler inventory script

### PR DESCRIPTION
**Pull request by opoplawski**
##### SUMMARY

This makes a couple minor and one major change to the cobbler inventory script:

- Drop note about script not logging in as it appears to be able to do so now
- Make orderby_keyname a config parameter
- Handle multiple cobbler servers

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
cobbler inventory

### CODE REVIEW

**Comment by ryansb** [comment]
cc/ @alikins

**Comment by opoplawski** [comment]
Any comments here?  I've got some further enhancements - handling sub-profiles as sub-groups, which required shifting to the newer json format of output using 'hosts' and 'children'.

**Comment by jimi-c** [comment]
@opoplawski sorry for not getting back sooner on this. It's no longer mergable, curious if you'd want to migrate this to an inventory plugin instead?

**Comment by opoplawski** [comment]
Hmm, I'll take a look at inventory plugins when I have a chance, which might not be very soon I'm afraid.  In the meantime I did a quick rebase that hopefully works.

**Comment by opoplawski** [comment]
This has been rebased against stable-2.9, mainly just so others can see my latest version of the script.

**Comment by jimi-c** [comment]
@opoplawski seems like it was a bad rebase? There are quite a few conflicting files in odd places.

**Comment by opoplawski** [comment]
It was rebased against release-2.9 instead of master.  It appears impossible to change the target branch of the PR.  I suppose I could close and open one against that if possible.  Or figure out where the script lives now if anywhere..

**Comment by jimi-c** [comment]
Yeah I'd close and re-create, this would not be back-ported to 2.9. Scripts are overall getting deprecated in favor of inventory plugins which work much better. You may want to look at converting it and publishing it via a collection instead.

**Comment by mattclay** [comment]
Closing, since inventory scripts are no longer in the `devel` branch and features/enhancements to the stable branches are not being accepted. 

The cobbler inventory script has been moved to the community.general collection [1], although as @jimi-c points out, it would be better to provide an inventory plugin instead of continuing to work on the inventory script.

[1] https://github.com/ansible-collections/community.general/blob/master/scripts/inventory/cobbler.py

**Comment by opoplawski** [comment]
Converted to inventory plugin:
https://github.com/ansible-collections/community.general/pull/627
https://github.com/cobbler/ansible

**Pull request closed without merging**
