### PR TITLE
module_utils/ovirt.py: fix broken import

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
Fix [broken import](https://github.com/ansible/community/wiki/Testing%3A-progress-tracker#fixing-broken-imports) in `module_utils/ovirt.py`.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
module_utils/ovirt.py

##### ANSIBLE VERSION

```
ansible-playbook 2.5.0 (devel c9f2b931db) last updated 2017/09/07 17:22:11 (GMT +200)
```

### CODE REVIEW

**Comment by samdoran** [comment]
cc @machacekondra @joshainglis @karmab

**Review by Akasurde — APPROVED** [review]
shipit

**Comment by machacekondra** [comment]
shipit

**Comment by pilou-** [comment]
bot_status

**Comment by pilou-** [comment]
@samdoran if there were an entry in `.github/BOTMETA.yml` for `module_utils/ovirt.py`:
- `ovirt` label would be automatically added (path components which are existing GitHub labels are automatically added)
- some people could be notified automatically (for that `maintainers` or `notified` must be defined in the `.github/BOTMETA.yml` entry)

Should a such entry be added ?

**Review by Akasurde — APPROVED** [review]
shipit

**Comment by mattclay** [comment]
@Akasurde The changes look good. Once the conflict is resolved this can be merged.

**Comment by pilou-** [comment]
@Akasurde updated (conflict resolved)

**Comment by samdoran** [comment]
@pilou- Probably a good idea. We already have an entry for `modules/cloud/ovirt`, so it would make sense to add an equivalent for `module_utils` related to the module.

**Pull request merged**
