### PR TITLE
fix error if path had wildcard in it 

### PR DESCRIPTION
**Pull request by kvprasoon**
##### SUMMARY
Fixes issue #73128. Code changes same as proposed by the issue Author.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`fetch.py`

### play
image

### before
image

### after
image

### CODE REVIEW

**Comment by samdoran** [comment]
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and add integration tests. See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

**Comment by kvprasoon** [comment]
@samdoran Thanks for the response. I can't see a common existing variable which can be used as a file name for tests. Pls guide me there.

**Comment by jborean93** [comment]
@kvprasoon I would modify the following test to include `[]` in the filename to test out this particular scenario https://github.com/ansible/ansible/blob/devel/test/integration/targets/win_fetch/tasks/main.yml#L191.

**Comment by kvprasoon** [comment]
Thanks @jborean93 :-) . I have added a test.

**Comment by bcoca** [comment]
note: the posix path behavior should be the same

**Comment by kvprasoon** [comment]
@bcoca I didn't get you. Can you help me to understand.

**Comment by bcoca** [comment]
@kvprasoon fetch is a 'dual mode' action, it can act on windows and POSIX(linux/unix) targets, as such we want to keep the  behaviors the same across these platforms, when possible, even though they are 2 different code paths. 

The note was mostly meant for the reviewers to ensure we do not create a deviation.

**Comment by kvprasoon** [comment]
Thanks.

Its already discussed in the issue I think.

https://github.com/ansible/ansible/issues/73128#issuecomment-758730926

**Comment by bcoca** [comment]
ah, yes, then ignore my comment, @sivel was already on it

**Comment by kvprasoon** [comment]
@sivel @boca are we good here ?

**Comment by kvprasoon** [comment]
@jborean93 anything else to be done here ?

**Comment by kvprasoon** [comment]
anyone ?
@sivel @boca

**Comment by kvprasoon** [comment]
@jborean93 or anyone to merge this if its still relevant ?

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Sorry @kvprasoon for having this one slip through. Thanks for the changes and fix here.

**Pull request merged**
