### PR TITLE
Panos object

### PR DESCRIPTION
**Pull request by ivanbojer**
##### SUMMARY

Given that there will be a number of different objects that need to be created in PANW devices we decided to club them all into one instead of having separate 15+modules. Therefore retiring first two modules in lieu of panos_object

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

panos_object

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb  6 2017, 11:22:10) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by samdoran** [comment]
Rather than remove a the old module entirely, would it be possible to keep it around with the old name and emit a warning to use the new name? This is generally what we do when moving module names around to avoid breaking playbooks.

It does seem you have added new functionality to the module that replaced it, but would calling the new module with old module parameters breaking anything? If not, I would like to create the link and warning for a better transition experience.

**Comment by ivanbojer** [comment]
The way we create these objects uses new improved API calls. The old API calls are being deprecated and I would like to avoid the loss of the functionality. I can definitely leave the old ones and emit a warning. I do like to 'cut to cord' as old modules were being made 'preview' and this one will be 'stable'.

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by samdoran** [comment]
Ok. I'll let you make that decision as the maintainer.

For #28031 and #28033 I went ahead and added the deprecation warning since those modules still exist. Once tests pass, I'll get them merged.

**Pull request merged**
