### PR TITLE
vdirect_commit:  committing pending configuration on Radware ADC devices

### PR DESCRIPTION
**Pull request by evgenyfedoruk**
##### SUMMARY
This module allows to commit pending configuration changes on a list of Radware ADC devices
via vDirect server.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
vdirect_commit

##### ANSIBLE VERSION

```
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/usr/share/my_modules/']
python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
The module uses PYPI vdirect_client module.
The module receives a list of Radware ADC devices and following three options of commit operations:
 - apply (default=True)
 - save (default=True)
 - sync (default=True)

### CODE REVIEW

**Comment by gundalow** [comment]
Other PR for modules https://github.com/ansible/ansible/pull/31243

**Comment by evgenyfedoruk** [comment]
This module is a WIP for now. This will be modified. Please do not review yet.

**Comment by evgenyfedoruk** [comment]
Removed [WIP], it's ready for review

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel` will be released in `2.5.0`

**Pull request merged**
