### PR TITLE
Added SMTP Authentification

### PR DESCRIPTION
**Pull request by elbuo8**
Added the ability to use authentication credentials to log in into an smtp server.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This needs to add the "version_added" attribute in the DOCUMENTATION block so it will be clear what version these have been added in the docs.

Can you update this?

Thanks!

**Comment by elbuo8** [comment]
Sure thing. Already added.

**Comment by mpdehaan** [comment]
Curious how this one might have been tested in terms of Python versions:

```
[root@localhost ansible]# python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> true && false
  File "<stdin>", line 1
    true && false
          ^
SyntaxError: invalid syntax
```

Let me know and please update your and statement to use "and".

It also seems like it should use "required_together" in the argument spec for username and password.
Grep through the module directory and you should be able to find a few examples.   This will eliminate someone specifying the username and wonder why it might be be used if they leave off the password.

Thanks!

**Comment by elbuo8** [comment]
Whoa. Totally my bad. I ran "make tests" assuming it would catch any dumb thing I might have done. Fixed. 

Also, added the "required_together" parameter :)

**Comment by elbuo8** [comment]
Bump?

**Comment by mattmakai** [comment]
+1

**Comment by zupo** [comment]
+1, also need it!

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Pull request closed without merging**
