### PR TITLE
Output tags while listing tasks

### PR DESCRIPTION
**Pull request by muffl0n**
Output tags for each listed task. This is primarily for debugging reasons but could be handy apart from that.

### CODE REVIEW

**Comment by mpdehaan** [comment]
If there are no tags the output here would be "(tags: )" ?

Can we fix that part so it leaves off the (tags) part in that case?

Thanks!

**Comment by muffl0n** [comment]
I'm not sure, can this ever be empty? Wouldn't it at least contain "all"? Maybe this should be filtered out as this has no benefit. I'm giving it a try.

**Comment by muffl0n** [comment]
No tags specified:

```
  play #1 (localhost):
    debug msg="foo"
```

Tag "bar" specified:

```
  play #1 (localhost):
    debug msg="bar" (tags: bar)
```

The implicit tag 'all' is hidden.

**Comment by muffl0n** [comment]
Is there anything I should change to get this merged?

**Comment by mpdehaan** [comment]
I'm needing to think about this one if I would want it in the output.   Probably can be included but still need to consider.

**Comment by bcoca** [comment]
already implemented as part as tag revamping

**Comment by muffl0n** [comment]
@bcoca: Could you tell me when this was implemented? I just upgraded to 1.8.4 and was wondering if this is already included in this release and where to find it.

**Comment by bcoca** [comment]
implemented in  1.9

**Pull request closed without merging**
