### PR TITLE
proxmox_kvm add `disk` option

### PR DESCRIPTION
**Pull request by helldorado**
##### SUMMARY
@LaurentDumont @killswitch-GUI @fredmiranda @berendt @xoxys this PR Fix issues #40921 #41940 #32294 #28277

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

[proxmox_kvm](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/proxmox_kvm.py)

##### ANSIBLE VERSION

```
ansible --version
ansible 2.7.10
  config file = None
  configured module search path = ['/Users/helldorado/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Apr 15 2019, 10:52:16) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### ADDITIONAL INFORMATION
Note: For the parameter `pause`, we recommand using option `pause` in `loop_control` which allows you to control the time (in seconds) between execution of items in a task loop. Cf https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#loop-control

For testing the PR before Merged you can download directly module from https://github.com/helldorado/ansible/blob/devel/lib/ansible/modules/cloud/misc/proxmox_kvm.py and put in `playbooks/library/proxmox_kvm.py`

### CODE REVIEW

**Comment by gundalow** [comment]
@LaurentDumont @killswitch-GUI @fredmiranda @berendt @xoxys  @joshainglis @karmab Hi, I believe this fixes an issue in proxyox_kvm that you might be interested in, was wondering if you might be able to take a look at this PR to see if it's good.

**Comment by robertbryanwilliams** [comment]
I have also been impacted by the failure to create linked clones and could possibly test this if those fixes are included in this.

**Comment by gundalow** [comment]
@helldorado Any thoughts on @robertbryanwilliams comment above?

**Comment by helldorado** [comment]
@robertbryanwilliams This PR fixes most issues, including problems with clones. 

Feedback after testing would be appreciable

**Comment by robertbryanwilliams** [comment]
@helldorado @gundalow  I can confirm that passing `full: no` now results in a linked clone as desired using the patched module.  

Ansible 2.8.0
Py 3.6
ProxMox 5.3-9

Previous Disk info when this was failing: 
image


Successful Linked Clone seen from UI:
image


Please let me know if any other tests need to take place to get this Merged and I would be happy to assist as I am able. 

Thanks!

**Comment by robertbryanwilliams** [comment]
I was able to see that the new VMID cannot be passed to the clone command per the documentation on Line 374. The below returns

> MSG: VM with vmid = 126 does not exist in cluster

```
   - name: Clone new VM from Template 
      proxmox_kvm:
        clone: Win10Template
        api_user: auser
        node: PMXNODE
        api_password: apassword
        validate_certs: no
        api_host: myhost
        name: newVMName
        timeout: 400
        full: no
        vmid: 126
```

**Comment by h3po** [comment]
@robertbryanwilliams @helldorado The storage path in the screenshot looked weird to me. This is what it looks like on my cluster, hdd_vm being an rbd ceph pool.
`virtio0: hdd_vm:base-188-disk-0/vm-306-disk-0,cache=writeback,size=100G`
Notice there is no `/306/` separating the base and child names.

**Comment by helldorado** [comment]
thank's @robertbryanwilliams for feedback
@h3po this is default storage. Your can see your storage via `pvesm status`

```
root@glacius:~# pvesm status
Name         Type     Status           Total            Used       Available        %
SAS           dir     active      3844633584        39866012      3609400660    1.04%
SSD           dir     active       408315520           73784       387430780    0.02%
local         dir     active        51473980         4806984        44029228    9.34%
```
`306` is your `vmid`.

**Comment by h3po** [comment]
> thank's @robertbryanwilliams for feedback
> @h3po this is default storage. Your can see your storage via `pvesm status`
> `306` is your `vmid`.

I meant to bring the difference in formats between the formats to your attention:
local:**316/** base-316-disk-0.raw **/126/** vm-126-disk0.qcow2
hdd_vm:base-188-disk-0/vm-306-disk-0

**Comment by robertbryanwilliams** [comment]
bump - Just updated to 2.9.x to gain Proxmox 6.x support #59340 and was upset to see that this still hadn't made it in. 

Specifically the issue surrounding the `format` parameter from #67048.

Please let me know if I can help move this along in any way. @helldorado @h3po

**Pull request closed without merging**
