### PR TITLE
docker module can't pull a remote image anymore

### PR DESCRIPTION
**Pull request by prune998**
all the details in the issue https://github.com/ansible/ansible/issues/9339

### CODE REVIEW

**Comment by jimi-c** [comment]
Hi @prune998, there are a couple of issues with this:

1) there appears to be a cut/paste error in this (the URL is hard-coded). 
2) this pull request is against release1.7.2 - all PRs must be sent to the devel branch.

Please get the patch corrected, and re-submit this PR against the development branch.

Thanks!

**Comment by prune998** [comment]
Well, I tried to help, but you're not taking it.
I'd rather let everybody trying to use the docker module report a bug until you correct it. I'm not going to install the devel branch on my productions servers to see if there is a regression with the docker module. Sorry.
There is one, I pointed it out, you can either correct it (the patch is not that hard to read/understand) or wait until the new release is out and hope it correct the bug...

Regards,

**Comment by jimi-c** [comment]
@prune998 we definitely appreciate the time you've taken to send us a PR, and the comments I gave above were aimed at making sure you received credit for your fix as opposed to us tweaking your patch.

However, we do clearly note in our community/contributing document (http://docs.ansible.com/community.html#contributing-code-features-or-bugfixes) that all PRs should be made against the `devel` branch. I only closed this issue because GitHub does not support changing the source of a PR, so it would have to be changed via a new request.

If you do not currently run devel and do not wish to modify existing servers it is quite easy to do a git checkout on another machine/vm/docker container so you have a clean environment on which to work, so we hope you do resubmit this based on our guidelines.

Thank you again!

**Comment by prune998** [comment]
sorry beeing rude. This is a production regression, and I find it funny to have to wait until next release to correct it. 
I'll try to test the devel version when I can and see if the bad behaviour is corrected, as it seems some part of the code greatly changed.

**Comment by jimi-c** [comment]
@prune998 we will most likely be doing a 1.7.3 sooner rather than later, so if you find that it is fixed in devel (or if you do send us an updated PR) we'll get this included in that (as well as several other bugs we've fixed in that module).

**Pull request closed without merging**
