### PR TITLE
New module for SMTP configuration on Pure Storage FlashBlade

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
New module to configure SMTP for a Pure Storage FlashBlade

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
purefb_smtp.py

### CODE REVIEW

**Review by genegr — APPROVED** [review]
shipit

**Review by sile16 — COMMENTED** [review]
If you try and change both host & sender domain, it only changes the host.  If you run it again, it then changes the sender domain.

**Comment by sdodsley** [comment]
@sile16 good catch - I'll fix that

**Comment by sile16** [comment]
shipit

**Review by sile16 — APPROVED** [review]
looks good

**Review by anshulbehl — APPROVED** [review]

**Review by JohnLieske — APPROVED** [review]

**Pull request merged**
