### PR TITLE
Fixes #24414, Added support for a ETCD folders

### LINKED ISSUE #24414: Extend the ETCD Lookup to get all variables from a folder
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Plugin ETCD Lookup

##### ANSIBLE VERSION
All

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
OS: Linux

##### SUMMARY
The feature basically is calling to get a ETCD key/value, when you make an API call to request a folder, the response must be all the keys-values inside of it.

##### STEPS TO REPRODUCE

```yaml
- name: 'ETCD Variables'
  hosts: 127.0.0.1
  connection: local
  remote_user: root
  vars:
    - REGION: 'SAMPLE'
    - RELEASE: 'liberty'
  pre_tasks:
    ## This step will fullfil the vars to be used on Ansible Roles/Playbooks
    - name: 'Getting Variables from ETCD Folder'
      set_fact:
        VAR_MAP: "{{ lookup('etcd2', '/{{ REGION }}/{{ RELEASE }}') }}"

    - debug:
        var: VAR_MAP
```

Output:
```
PLAY [ETCD Variables] *********************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [Getting Variables from ETCD Folder] ****************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": {
        ...
        ...
        ...
        "CEILOMETER_API_PORT": "8777",
        "CEILOMETER_LOG": "LOG_LOCAL6",
        "CEILOMETER_TTL": "7776000",
        "CEILOMETER_USER": "ceilometer",
        "CEPH_VERSION": "0.80.8",
        "CINDER_BCK_DRIVER": "cinder.backup.drivers.ceph",
        "CINDER_CEPH_BCK_USER": "backup",
        "CINDER_CEPH_CHUNK": "134217728",
        "CINDER_DB": "cinder",
        "CINDER_DEF_VOL": "standard",
        "CINDER_ENABLE_BACKEND": "standard,ssd",
        ...
        ...
      }
}

TASK [00_entry_validation : Creating controller files] ***************************************************************************************************************************************
changed: [localhost] => (item={'key': u'ceilometer', 'value': {u'origin': u'/etc/ceilometer/ceilometer.conf', u'tmp': u'/home/test/ceilometer.conf', u'template': u'ceilometer-controller.conf.j2'}})

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
```

##### EXPECTED RESULTS
Inside of fact {{ VAR_MAP }} you will find a dictionary with all variable mapping from an ETCD folder 

##### ACTUAL RESULTS
Actually  you get a empty variable

### PR DESCRIPTION
**Pull request by jparrill**
##### SUMMARY

Fixes #24414 

By design the lookup plugin dont expect to find a ETCD folder instead of a Key, this commit allow to give the feature to return a dictionary with all key-values from a ETCD folder.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- ETCD Lookup Plugin

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 13 2017, 10:15:16) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION
To test the lookup just point to an ETCD folder instead of a Key

More info on [https://github.com/padajuan/ansible-module-etcd](https://github.com/padajuan/ansible-module-etcd)

### CODE REVIEW

**Comment by gundalow** [comment]
cc @jpmens

**Comment by gundalow** [comment]
I see you've changed the `default` how will that impact people that are already using this module, it was added in Ansible 2.1.

**Comment by jparrill** [comment]
Yeah, v1 is a bit old, if this is a problem and are all agree I could change the default version back to v1.

[EDITED]: Already updated to v1

**Comment by jparrill** [comment]
@gundalow Looks good?

**Review by gundalow — APPROVED** [review]

**Comment by calfonso** [comment]
@padajuan are you interested in becoming a maintainer of this plugin?

**Comment by jparrill** [comment]
@calfonso Yeah, that's will be great ;)

**Pull request merged**
