### PR TITLE
Look for role name in an additional key

### LINKED ISSUE #9280: Role dependencies missing version documentation for remote role support
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1, 1.7.2, 1.8 ( e8aa847 2014-10-06 )
##### Environment:

OS X 10.10
##### Summary:

Remote roles, described as  { role: "git+http://gitlab.local/ansible/git.git,master" } not working. Ansible-playbook parse it as local path.
##### Steps To Reproduce:

Create role with dependences `meta/main.yml`:

``` yaml

---
dependencies:
  - { role: "git+http://gitlab.local/ansible/git.git,master,git" }
  - { role: apt,    tags: environment }
  - { role: nginx,  tags: nginx }

```

Run ansible-playbook, see error:

```
ERROR: cannot find role in /Users/aotd/www/favorites.ansible/roles/git+http:/gitlab.local/ansible/git.git,master or /Users/aotd/www/favorites.ansible/git+http:/gitlab.local/ansible/git.git,master or /etc/ansible/roles/git+http:/gitlab.local/ansible/git.git,master
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
##### Expected Results:

Downloaded and used role from http://gitlab.local/ansible/git.git
As described in [documentation](http://docs.ansible.com/playbooks_roles.html#role-dependencies).
##### Actual Results:

```
ERROR: cannot find role in /Users/aotd/www/favorites.ansible/roles/git+http:/gitlab.local/ansible/git.git,master or /Users/aotd/www/favorites.ansible/git+http:/gitlab.local/ansible/git.git,master or /etc/ansible/roles/git+http:/gitlab.local/ansible/git.git,master
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### PR DESCRIPTION
**Pull request by mattupstate**
Given that, when using remote role dependencies, its not really expected to use the `role` key in the dependency dictionary, but rather the `scm`, `src`, `version` and `name` keys, should not the `name` key also be checked when resolving roles? Might fix #9280

### CODE REVIEW

**Comment by jaytaylor** [comment]
+1 for getting this fixed.  The docs are very misleading and specifying role dependencies is painful at present.

**Comment by jaytaylor** [comment]
I went ahead and tried using this patched version of play.py, but I am still getting the same errors WRT dependencies declared via `role: { ... }`.

``` bash
ERROR: cannot find role in /Users/jay/repos/my-playbook/roles/git+https:/github.com/mhamrah/ansible-docker or /Users/jay/repos/my-playbook/git+https:/github.com/mhamrah/ansible-docker or /Users/jay/repos/my-playbook/librarian_roles/git+https:/github.com/mhamrah/ansible-docker
```

**Comment by mattupstate** [comment]
@jaytaylor Thats because this patch expects role dependencies to be declared in one of two ways:

``` yaml
dependencies:
  # A role available on galaxy.ansible.com
  - role: Stouts.python
  # A custom remote role
  - name: chatid.consul
    src: git+git@github.com:username/repo.git
    version: master
```

**Comment by jaytaylor** [comment]
@mattupstate thanks, will adjust my usage to reflect this convention.  What is the quickest way to get the docs updated to reflect this?

**Comment by jaytaylor** [comment]
Oops - nevermind, my mistake, I didn't realize this wasn't yet live!

**Comment by amenonsen** [comment]
@mattupstate, feel like rebasing onto devel and addressing the test failures?

**Comment by mattupstate** [comment]
@amenonsen I'm afraid the merge is a bit too complex for me to resolve immediately. The structure of these modules has changed dramatically.

**Comment by mattupstate** [comment]
Seems like this is being addressed in 2.0

**Pull request closed without merging**
