### PR TITLE
Avoid merging dict and unicode

### LINKED ISSUE #12915: Passing dict variable defined in group_vars to role fails when dict merging is enabled
**Ansible version:** 1.9.4

When dict merging is enabled, passing a dict as a role parameter produces an error.

**Example:**
Consider the following Ansible project:

```
├── ansible.cfg
├── group_vars
│   └── all
├── inventory
│   └── local.ini
├── roles
│   └── demo
│       └── tasks
│           └── main.yml
└── test.yml
```

_ansible.cfg_:

```
[defaults]
hash_behaviour = merge
```

_test.yml_

```

---
- hosts: localhost
  roles:
    - role: demo
      role_arg: "{{ foo }}"
```

_group_vars/all_:

```

---
foo:
  bar: baz
```

_inventory/local.ini_:

```
localhost ansible_connection=local
```

_roles/demo/tasks/main.yml_:

```

---
- debug: var=role_arg
```

**Expected behavior:**

```
$ ansible-playbook -i inventory/local.ini test.yml 

PLAY [localhost] **************************************************************

TASK: [demo | debug var=role_arg] ********************************************* 
ok: [localhost] => {
    "var": {
        "role_arg": {
            "bar": "baz"
        }
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0 
```

**Actual behavior:**

```
$ ansible-playbook -i inventory/local.ini test.yml 

PLAY [localhost] **************************************************************

TASK: [demo | debug var=role_arg] ********************************************* 
fatal: [localhost] => failed to combine variables, expected dicts but got a 'dict' and a 'unicode'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=1    failed=0 
```

### PR DESCRIPTION
**Pull request by dagwieers**
This fixes #12915

~~Since combine_vars() is being run directly on role_params through get_inject_vars(), we have to avoid merge_hash() to complain about merging a dict with a string (i.e. jinja template).~~

### CODE REVIEW

**Comment by dagwieers** [comment]
Summary: we do exactly the same thing as is done to module_vars

@bcoca I hope this is an acceptable solution.

**Comment by dagwieers** [comment]
I documented an alternative solution in #12915 which handles untemplated strings differently, which works for our use-cases and is specific to merge_hash() only. Let me know if you prefer such a work-around for the v1.9 tree instead and I'll make a pull-request.

Backporting the changes from Ansible v2.0 is practically impossible as it would replace how roles are being handled completely.

**Comment by sivel** [comment]
~~errant request for rebase~~

**Comment by sivel** [comment]
@dagwieers apologies on that last comment, I'm going to get rid of that.  My inspection was flawed and didn't account for a submission against, stable-1.9.

**Comment by dagwieers** [comment]
This is now the fix that @jimi-c proposed in https://gist.github.com/jimi-c/a655aab495716e355694#gistcomment-1704151

**Pull request merged**
