### PR TITLE
vmware_guest: Add multiple nics management + Bug fixes

### PR DESCRIPTION
**Pull request by aperigault**
##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
- Fix var name:
function getfolder return folder_map instead of foldermap.

- Fix bug in deploy_template function:
If folder not start by /vm there is a "no folder matched the path" error

- Power on VM if state is set to poweredon

New feature : Move nic creation out of customizations + Add multiple nics management

### CODE REVIEW

**Comment by aperigault** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3481

**Comment by gundalow** [comment]
I believe the current maintainers are @jctanner, @jcpowermac, @mtnbikenc, @chrrrles could you please review, thanks.

**Comment by nerzhul** [comment]
Please note i did a similar but more complete version here:

https://github.com/ansible/ansible/pull/19228

I didn't saw this PR, and i changed some bad design, but noticed some identical bugs and added more features

**Comment by aperigault** [comment]
@nerzhul I read your PR. There is good things but I'm not agree with your nic management. For my use case I need to add nics only with a vlan id args. I think we need to manage nics and customizations separately.

**Comment by nerzhul** [comment]
vlan id is not used everytime, but could be an improvement, i'm working on idempotency and creating VM from scratch whereas the original version you modify only used templates

**Comment by aperigault** [comment]
The vlan_id feature is an improvement already include in my PR. The goal is to add nics (with vlan_id for example or with network_name) with a minimum informations. Your PR need too many informations to add a nic.

**Comment by nerzhul** [comment]
@aperigault i agree it's not useful, i only kept the origin module compatibility, i also think there is too many PR, only have the switch name or the vlan id is sufficient

**Comment by jctanner** [comment]
@dav1x can you review this please?

**Comment by dav1x** [comment]
Tested and works great @jctanner

**Comment by gundalow** [comment]
Looks like this needs a rebase.

**Review by jctanner — APPROVED** [review]

**Comment by jctanner** [comment]
@aperigault please rebase your branch.

**Comment by aperigault** [comment]
@jctanner Rebased !

**Comment by angystardust** [comment]
@aperigault can you please add a configuration example with 2 nics? thanks

**Comment by aperigault** [comment]
@angystardust I added an example with two nics. One with network_name and one with network_vlan. You need to define one of these.

**Comment by angystardust** [comment]
Thanks a lot @aperigault.
How about the ip customization instead? Can I do that with multiple ips? How can I distinguish between the first nic and the second one?

**Comment by dav1x** [comment]
@angystardust the differentiation is the VM Network name (or port group). I have code that will set multiple IP addresses once this PR is merged. It's based on this code.

**Comment by nerzhul** [comment]
@aperigault why not merge your change into #19228 instead of doing the same thing twice.

#19228 has many interesting change the only missing change which is in this PR is the vlan ID support

this would permit a better feature integration as i pass many times to optimize the module and add more features, and you too on network.

The add mode on disk is non idempotent it's not good for ansible.

**Comment by aperigault** [comment]
@nerzhul I will retest your branch and do a PR in your branch.

**Comment by nerzhul** [comment]
@aperigault thanks :)

**Comment by aperigault** [comment]
@dav1x @jctanner @nerzhul I merged my changes in nerzhul PR #19228 
I think we need to merge this quickly because there is a lot of good changes that break all others PR

**Pull request closed without merging**
