### PR TITLE
route53: diff support

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This adds basic diff support to the route53 module:

```.diff
TASK [Configure Route53 IPs] ***************
--- before
+++ after
@@ -8,9 +8,9 @@
     "region": null,
     "ttl": "300",
     "type": "AAAA",
-    "value": "2a01:1:2::3",
+    "value": "2a01:4:5::6",
     "values": [
-        "2a01:1:2::3"
+        "2a01:4:5::6"
     ],
     "weight": null,
     "zone": "y.z."

changed: [localhost] => (item=AAAA x.y.z)
```

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
route53

### CODE REVIEW

**Review by tremble — CHANGES_REQUESTED** [review]
Just one minor comment: The 'diff' value we return should probably be documented (and at least minimally tested), especially since there's currently nothing returned.

**Comment by felixfontein** [comment]
I've created a PR to document it there: #64888

**Review by tremble — APPROVED** [review]

**Comment by tremble** [comment]
That seems reasonable

**Comment by felixfontein** [comment]
#64888 has been merged, so `diff` return value docs are there now ;)

**Review by jillr — APPROVED** [review]
rebuild_merge

**Comment by felixfontein** [comment]
The failed test was completely unrelated (https://app.shippable.com/github/ansible/ansible/runs/152645/83/console). Restarted and will merge once it passes.

**Comment by felixfontein** [comment]
@tremble @jillr thanks a lot for reviewing and handling this! :)

**Pull request merged**
