### PR TITLE
iptables: support wait parameter

### PR DESCRIPTION
**Pull request by ilpianista**
##### SUMMARY
Support `--wait` command for `iptables`.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
iptables

##### ANSIBLE VERSION
2.7.0

##### ADDITIONAL INFORMATION
I got the following error while trying to execute 2 iptables rules simultaneously on the same host (it's declared twice in the inventory):

```
failed: [host] (item=80) => {"changed": false, "cmd": "/sbin/iptables -t filter -A INPUT -p tcp -m tcp --destination-port 80", "item": "80", "msg": "Another app is currently holding the xtables lock. Perhaps you want to use the -w option?", "rc": 4, "stderr": "Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n", "stderr_lines": ["Another app is currently holding the xtables lock. Perhaps you want to use the -w option?"], "stdout": "", "stdout_lines": []}
```

A workaround for this, could be the use of the `--wait` option in the `iptables` command.

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
LGTM :+1:

**Comment by LinusU** [comment]
'shipit'

**Comment by ilpianista** [comment]
I integrated the hint from #59067 with the version check from #38106

**Comment by ilpianista** [comment]
This should also close #59002

**Comment by ilpianista** [comment]
@LinusU ping. You marked this as 'shipit' and then nothing happened, but I improved it so, may you please take a second look at this?

**Comment by Akasurde** [comment]
Thanks for the contribution.

**Comment by abhiTamrakar** [comment]
@Akasurde Would it be ported to 2.8.x as well.

**Pull request merged**
