### PR TITLE
Update yum.py

### PR DESCRIPTION
**Pull request by biohazd**
adding explanation why you must use "shell: yum clean all" and why it won't be included in the yum module as per https://github.com/ansible/ansible/pull/31450#issuecomment-352889579

+label: docsite_pr

##### SUMMARY
adding explanation why you must use "shell: yum clean all" and why it won't be included in the yum module as per https://github.com/ansible/ansible/pull/31450#issuecomment-352889579

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
yum

##### ANSIBLE VERSION
All

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by maxamillion** [comment]
@biohazd I'm +1 to the change, but would you mind adding some context just in case people don't know what that means at face value? ... maybe something like `If you need to clear yum cache and metadata use ....`

**Comment by mkrizek** [comment]
cc @acozine

**Comment by biohazd** [comment]
thanks, let me update the wording.

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by acozine** [comment]
Don't know why the bot didn't merge this one. But since it didn't, I will!

**Pull request merged**
