### PR TITLE
Add "modularity" support to the DNF ansible module.

### PR DESCRIPTION
**Pull request by james-antill**
##### SUMMARY
Add "modularity" support to the DNF ansible module.

Allows the user to install/remove/upgrade/enable/disable Fedora modules.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
modules/packaging/os/dnf

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### ADDITIONAL INFORMATION
This should be reviewed by @ignatenkobrain as he owns the module.

### CODE REVIEW

**Comment by igor-raits** [comment]
IMO until API of DNF is stable we should not use it..

**Comment by james-antill** [comment]
When do you think that'll be? We kind of want this to be available around F28 GA ... I can completely understand that the API we'll have for F30 or F31 might be completely different, but we need to ship some ansible playbooks that can install modules before then (just means we'll need some fun compat. code and maybe changes on the ansible side too).

We could also easily change the default for modularity and use "modularity: true" for playbooks for certain OSes, I guess.

**Comment by maxamillion** [comment]
@ignatenkobrain @james-antill any update on this in terms of DNF API stabilization, $other? I am planning a refactor of this module's code and want to wrap up any open PRs asap.

**Comment by maxamillion** [comment]
Also as a side note, I'm not sure this should be added to the `dnf` module but possibly be a separate Ansible module. I'm open to discussion on the topic though.

**Comment by maxamillion** [comment]
Turns out that the modularity/appstream components are considered core dnf functionality so I'm good with this being included whenever we can get a stable DNF API for it and an updated patch. Thank you for your work!

**Comment by justwheel** [comment]
Just curious where this one left off at, or if it's possible to use Fedora Modularity with Ansible. I'd love to see this make it into Ansible and it would simplify some of my existing Ansible workflow with Fedora 29+.

**Comment by james-antill** [comment]
The DNF API changed. Following https://bugzilla.redhat.com/show_bug.cgi?id=1627296 says that callers should now do: https://github.com/rpm-software-management/dnf/pull/1254/commits/6490375472b20a0172e6bafe758582c1e9a788b3

**Comment by maxamillion** [comment]
oh sorry, actually this is [already in Ansible as of 2.7.3](https://github.com/ansible/ansible/pull/48905) but I didn't update this issue ticket. Apologies.

resolved_by_pr https://github.com/ansible/ansible/pull/48753

**Comment by maxamillion** [comment]
In retrospect, I should have just revisited this PR but it fell off the map. That's on me, apologies.

**Pull request closed without merging**
