### PR TITLE
Add domainname to ansible facts

### PR DESCRIPTION
**Pull request by srgvg**
As per https://groups.google.com/d/msg/ansible-project/yvBDjxKBefw/COh2td8FGssJ

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks very much. 

A few thoughts:

(A) 

Probably should be "domain".

(B)

There's a chance the fqdn call might return something with no dots maybe?  

From the Python docs:

"The first name which includes a period is selected. In case no fully qualified domain name is available, the hostname as returned by gethostname() is returned."

So it seems there is a small chance it could return just "localhost" in some cases and the array is going to have less elements.

I can take a look.

Thanks!

**Comment by srgvg** [comment]
I'll leave (A) up to you. 'domainname' seemed more to the point to me. As per hostname(1) on could even argue about 'dnsdomainname' (as opposed to NIS domainname).

(B) I believe I checked for that: if socket.getfqdn() returns only one element, the code will return an empty string for the domainname, which seems appropriate

> > > '.'.join('myhostname'.split('.')[1:])
> > >   ' '

**Comment by mpdehaan** [comment]
(A) more of a personal preference to not run words together :)  ...
hostname is kind of a unix word already ... kind of :)

(B) So it does, my mental python compiler is off!  Good deal.   Sorry for
confusion!

**Comment by jpmens** [comment]
I personally would favor `domain` because I (sometimes) associate `domainname` with NIS. :-)

**Comment by srgvg** [comment]
On 28 October 2012 19:45, JP Mens notifications@github.com wrote:

> I personally would favor domain because I (sometimes) associate domainnamewith NIS. :-)

In respect for your age, I'm willing to concede.

Serge

**Comment by mpdehaan** [comment]
NIS is like gopher, right?  :)

-- Michael

**Comment by jpmens** [comment]
The cheek! 

And no, Michael: you're much too young to understand.

**Comment by sfromm** [comment]
Looks good to me.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request closed without merging**
