### PR TITLE
yum module fixups - for no repoquery

### PR DESCRIPTION
**Pull request by skvidal**

### CODE REVIEW

**Comment by mpdehaan** [comment]
in queue for testing. expected to be busy tonight so this might get merged in tomorrow or so. Thanks!

**Comment by mpdehaan** [comment]
see also #873

**Comment by skvidal** [comment]
I added the code form 873 to my latest tree - I'll update the PR shortly.

**Comment by skvidal** [comment]
updated - let's try this one.

**Comment by mpdehaan** [comment]
tonight was not as crazy as expected, merged, thanks.

I tweaked an alias where it was not accepting "name=" and also fixed #871 -- still returns the same data, just isn't recorded as a failure

**Pull request merged**
