### PR TITLE
Clarify when and how to enable ANSIBLE_DEBUG

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
Had some feedback that it wasn't clear where and how to enable `ANSIBLE_DEBUG`, so try and clarify that.

##### ISSUE TYPE
 - Docs Pull Request

##### ANSIBLE VERSION
```
2.4
```

### CODE REVIEW

**Comment by gundalow** [comment]
Lotus1211 has said
> Cool , looks good now :)

**Comment by acozine** [comment]
+1 for incremental improvement

**Comment by abadger** [comment]
cherrypicked for 2.4.4

**Comment by dharmabumstead** [comment]
Please don't merge documentation PRs until I've had a chance to review/edit. Thanks.

**Pull request merged**
