### PR TITLE
Testing Ansible core

### PR DESCRIPTION
**Pull request by digitalsimboja**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mkrizek** [comment]
!needs_collection_redirect

**Comment by digitalsimboja** [comment]
@mkrizek 

> !needs_collection_redirect

Please point me to the location of the Build log. 
Thanks

**Comment by webknjaz** [comment]
> Please point me to the location of the Build log.

Go to the [`Checks` tab](https://github.com/ansible/ansible/pull/75638/checks) or scroll down to [Checks on the `Conversation` tab](https://github.com/ansible/ansible/pull/75638#issue-comment-box) and click on `Details`. From there you can click on things like `View more details on Azure Pipelines`, or `3 errors / 0 warnings`, or other links. And that should take you to the external CI pages on a service called `Azure Pipelines`. Navigate inside to see the logs of different jobs.

**Comment by digitalsimboja** [comment]
> > Please point me to the location of the Build log.
> 
> Go to the [`Checks` tab](https://github.com/ansible/ansible/pull/75638/checks) or scroll down to [Checks on the `Conversation` tab](https://github.com/ansible/ansible/pull/75638#issue-comment-box) and click on `Details`. From there you can click on things like `View more details on Azure Pipelines`, or `3 errors / 0 warnings`, or other links. And that should take you to the external CI pages on a service called `Azure Pipelines`. Navigate inside to see the logs of different jobs.
> 
> For example, this page https://dev.azure.com/ansible/ansible/_build/results?buildId=23965&view=results visualizes all the jobs with their dependencies and statuses but you can navigate to the concrete logs by clicking on them.

Ohh! My mistake. I did not click the error links when I saw the list of errors. Thanks for the quick response.

**Comment by nitzmahone** [comment]
looks like this might be a bogus PR- closing

**Pull request closed without merging**
