### PR TITLE
[stable-2.15] runtime-metadata sanity test: do not fail deprecation version checks if galaxy.yml has empty `version`

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backpot of #83831.

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by felixfontein** [comment]
CI failure seems unrelated.

**Comment by mariolenz** [comment]
> CI failure seems unrelated.

Maybe close the PR and open it again a few minutes later? I often do this to trigger a new clean CI run.

**Comment by felixfontein** [comment]
@mattclay thanks!

**Comment by mariolenz** [comment]
Thanks @felixfontein and @mattclay!

**Pull request merged**
