### PR TITLE
[WIP] see if switching to [void] instead of | Out-Null has any effect …

### PR DESCRIPTION
**Pull request by jhawkesworth**
…on module speed.

##### SUMMARY

possibly a tiny speedup, 

Not a fix, might be an optimization

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

win_copy
##### ANSIBLE VERSION

```
ansible 2.5.0 (win_less_piping_experiment 350da50df4) last updated 2017/11/01 17:42:32 (GMT +100)
  config file = None
  configured module search path = [u'/home/jon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jon/ansible-dev/lib/ansible
  executable location = /home/jon/ansible-dev/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION

WIP not for merge.

related to WWG discussion.  setup only has 1 | Out-Null that could be changed, so decided to try win_copy which has 12 occurrences.
TODO add measure-command to benchmark.

```

```

### CODE REVIEW

**Comment by dagwieers** [comment]
@jhawkesworth I fixed some typos in the syntax.

**Comment by dagwieers** [comment]
Looking at the various places we use `Out-Null` it seems *powershell.py* and *winrm.py* are useful to do as well, before we compare.

[dag@moria ansible.git]$ grep -rc '| Out-Null' lib/ansible | grep -v 0$
lib/ansible/modules/windows/win_unzip.ps1:3
lib/ansible/modules/windows/setup.ps1:1
lib/ansible/modules/windows/win_file.ps1:1
lib/ansible/modules/windows/win_defrag.ps1:3
lib/ansible/modules/windows/win_scheduled_task.ps1:1
lib/ansible/modules/windows/win_copy.ps1:12
lib/ansible/modules/windows/win_path.ps1:5
lib/ansible/modules/windows/win_psexec.ps1:3
lib/ansible/modules/windows/win_package.ps1:4
lib/ansible/modules/windows/win_domain_controller.ps1:1
lib/ansible/modules/windows/async_wrapper.ps1:6
lib/ansible/modules/windows/win_disk_image.ps1:2
lib/ansible/modules/windows/win_domain_group.ps1:4
lib/ansible/modules/windows/win_pagefile.ps1:2
lib/ansible/modules/windows/win_mapped_drive.ps1:2
lib/ansible/modules/windows/win_hotfix.ps1:1
lib/ansible/modules/windows/win_tempfile.ps1:1
lib/ansible/modules/windows/win_wait_for.ps1:1
**lib/ansible/plugins/connection/winrm.py:4**
**lib/ansible/plugins/shell/powershell.py:21**

**Comment by jborean93** [comment]
Just an FYI in case you aren't already aware, while you can cast to void like `[void](cmdlet)` like you have already done. You can also do `cmdlet > $null` or `$null = cmdlet` and it achieves the same thing with a similar timeframe. I'm personally a fan of `cmdlet > $null` as you don't have to enclose the cmdlet in brackets but won't enforce one and just wanted to let you know.

**Comment by dagwieers** [comment]
@jborean93 I don't mind either way, I simply fixed what was already there. Doing `cmdlet > $null` is fine by me, if it is identical.

**Comment by jborean93** [comment]
I'm curious if we do save any time, I think we will save something but think it's going to be a small.

**Comment by jhawkesworth** [comment]
@dagwieers and @jborean93 Thanks for your code changes and suggestions, I will have a bit of a play with this and see if it gains us anything.

Jon

**Comment by jhawkesworth** [comment]
I'm going to close this one, the variation between test runs on my machine was huge, I couldn't demonstrate anything was faster.

**Pull request closed without merging**
