### PR TITLE
Fix for with_ini when used with YAML parameters.

### PR DESCRIPTION
**Pull request by Yannig**
##### SUMMARY

Lookup ini is not working with current example in Ansible documentation.
Fix the bug in the lookup plugin and add a new test in integration test.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

lookup ini

##### ANSIBLE VERSION

```
ansible 2.5.0 (fix-with-ini 95b77fdb9d) last updated 2017/12/31 08:09:24 (GMT +200)
  config file = /home/yannig/.ansible.cfg
  configured module search path = [u'/home/yannig/dev/common/playbooks/library']
  ansible python module location = /home/yannig/dev/ansible/lib/ansible
  executable location = /home/yannig/dev/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 23 2017, 15:37:09) [GCC 6.3.0 20170406]
```

##### ADDITIONAL INFORMATION

Create a playbook **test.yml** with the following content:

```yaml
- name: "test"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Test ini lookup"
      debug: var=item
      with_ini:
        - .*
        - section: section1
        - file: test.ini
        - re: true
```

You will need a file **test.ini** with the following content:

```ini
[section1]
a=1
b=2
[section2]
a=1
b=2
c=3
```

Launch this playbook (**ansible-playbook test.yml**).

What you get:

```
[WARNING]: Unable to find 'ansible.ini' in expected paths.

fatal: [localhost]: FAILED! => {"msg": "Invalid filename: 'None'"}
msg:
Invalid filename: 'None'
        to retry, use: --limit @/home/yannig/tmp/test.retry
```

Expected result:

```
ok: [localhost] => (item=1) => {
    "changed": false, 
    "item": "1"
}
ok: [localhost] => (item=2) => {
    "changed": false, 
    "item": "2"
}
```

### CODE REVIEW

**Comment by bcoca** [comment]
this looks like it breaks backwards compatibility, I would have just fixed the docs instead

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
CI failure in Python 3.x unit tests:

```
self = <units.plugins.lookup.test_ini.TestINILookup testMethod=test_parse_parameters>

    def test_parse_parameters(self):
        for testcase in self.old_style_params_data:
            # print(testcase)
            params = _parse_params(testcase['term'])
>           self.assertEqual(params, testcase['expected'])
E           AssertionError: Lists differ: ['keyA', 'file=/path/to/file', 'section=sectionA'] != ['keyA', 'section=sectionA', 'file=/path/to/file']
E           
E           First differing element 1:
E           'file=/path/to/file'
E           'section=sectionA'
E           
E           - ['keyA', 'file=/path/to/file', 'section=sectionA']
E           + ['keyA', 'section=sectionA', 'file=/path/to/file']

test/units/plugins/lookup/test_ini.py:68: AssertionError
```

The RHEL failure is unrelated.

**Comment by holser** [comment]
I have tested this pull requests locally. It works. However, the patch needs to be rebased. @Yannig If you don't have time to work on this patch please allow me to create own pull request to finish the work. Thank you in advance.

**Comment by Yannig** [comment]
@holser go ahead :)

**Comment by holser** [comment]
Work restored in https://github.com/ansible/ansible/pull/49481

**Comment by sivel** [comment]
Work will continue in #49481

**Pull request closed without merging**
