### PR TITLE
Rewrite of Na_ontap_job_schedule and new options

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Rewrite of na_ontap_job_schedule to use NetAppModule
New options to set schedule for (hours, day, month), from just minutes. 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_job_schedule

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]

**Review by beeankha — APPROVED** [review]
Everything seems OK to me, looks like more examples were added and also a test for the module was created.  👍

**Comment by thedoubl3j** [comment]
ping @carchi8py for rebase. ping @gundalow

**Review by lonico — APPROVED** [review]
shipit

**Review by beeankha — APPROVED** [review]
Everything passed when I tested locally.

**Review by gundalow — APPROVED** [review]

**Pull request merged**
