### PR TITLE
ovirt_vms: Add high_availability_priority to ovirt_vms

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

This PR add new parameter `high_availability_priority` to `ovirt_vms` module.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_vms

##### ANSIBLE VERSION

```
2.4.2
```

##### ADDITIONAL INFORMATION

```yaml
- name: Create VM with HA prio 50
  ovirt_vms:
    name: rhel7
    template: rhel7
    cluster: Default
    high_availability: true
    high_availability_priority: 50
```

### CODE REVIEW

**Comment by machacekondra** [comment]
Fixes: https://github.com/ansible/ansible/issues/35268#issuecomment-360069252

**Comment by machacekondra** [comment]
Fixes: https://github.com/ansible/ansible/issues/35268

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
shipit

**Review by mwperina — APPROVED** [review]
shipit

**Pull request merged**
