### PR TITLE
Remove kustodian from postgres and opennebula

### PR DESCRIPTION
**Pull request by kustodian**
I currently don't have time to follow the changes in Postgresql and OpenNebula modules.

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @Andersson007

**Review by Andersson007 — APPROVED** [review]
@Akasurde thanks for mentioning me!
@kustodian thank you much for the participation in our WG !
You helped a lot with that modules,
there were very detailed reviews from you for 2.8, 2.9 that helped us to prevent many bugs and made the modules' initial state much better!
Very sad but understand..
(would be really happy to see you again later)
Thank you!

**Comment by kustodian** [comment]
Thanks for the kind words. I'll still be around, I just can't be as active
as you are :-)

Feel free to mention me on issues if you think I can be of some help, if I
don't hop by myself.

**Comment by Andersson007** [comment]
@kustidian , ok, glad to hear! Thanks!

**Pull request merged**
