### PR TITLE
Better status

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

fixes recent change and makes it backward compatible for modules that relied exclusively on rc instead of failed.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

task  executor
##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Review by nitzmahone — APPROVED** [review]

**Comment by dagwieers** [comment]
This will not work for modules that return a non-zero return code, but succeed anyway.

This is undoing everything we needed for win_robocopy, win_chocolatey and various others. This is the reason why some of the modules avoid using `rc`, but deliberately were using something else (exit_code, return_code, return_value, etc...)

https://github.com/ansible/ansible/issues/24652
https://github.com/ansible/ansible/pull/25950
https://github.com/ansible/ansible/pull/24867

**Comment by nitzmahone** [comment]
It does work for modules that opt-in to the new failure behavior by explicitly including `failed: false` or `failed: true` in their return dicts, and preserves backwards compatibility for modules that don't. We can (relatively) easily audit what's happening in modules we ship, but the change as it was could potentially (and silently) break a lot of custom modules.

**Comment by bcoca** [comment]
@dagwieers you are misreading it, IF a module sets 'failed', 'rc' is never looked at. 

The intent of your change  "avoid rc overriding failed status" is still there, what this does is still allow backwards compatibility for modules that did NOT return 'failed' at all and solely relied on 'rc'.

I removed the changes from basic.py as other core team members considered this redundant, but kept 'failed=True' in fail_json.

The last big change is in the tests, `|failed` was still checking `rc`, now it ignores it.

**Comment by dagwieers** [comment]
I am not misreading you, this will fail win_robocopy, win_chocolatey, and others. The module returns rc=3010 and should succeed, not fail.

**Comment by bcoca** [comment]
the module should return `failed=False` in that case

**Comment by dagwieers** [comment]
I disagree, the module calls Exit-Json, and not Fail-Json.As it should. Reverting this is is wrong, the absence of failed always meant that it succeeded. That should not be different if rc is non-zero.

The old behaviour was incorrect, handling return codes should be done by the module, not core.

**Comment by dagwieers** [comment]
I think it is ill-fated to roll back the changes we discussed and approved in a core meeting.

It was put on the agenda again, but you already went forward and merged it anyway.

**Comment by bcoca** [comment]
After discussion in core the only part that was incorrect of the old behaviour was 'rc' overriding 'failed', but if only one exists we use that one.  If both exist 'failed' is now the 'winner'.  

The 'rc' behaviour predates those modules and others depend on it, so if they want to control their status, they should use 'failed'.

**Pull request merged**
