### PR TITLE
Pluribus Networks network cli terminal and cliconf plugins

### PR DESCRIPTION
**Pull request by rajaspachipulusu17**
##### SUMMARY

Terminal and cliconf plugins for connection: network_cli for Pluribus Networks switches.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
network cli plugins.
##### ADDITIONAL INFORMATION
ansible-playbook 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@rajaspachipulusu17 Thanks for the PR. There are several failures in Pluribus space - https://app.shippable.com/github/ansible/ansible/runs/113607/5/console

**Comment by Akasurde** [comment]
> The test `ansible-test sanity --test docs-build` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/docs-build.html)] failed with 1 error:
> 
> ```
> docs/docsite/rst/plugins/cliconf.rst:44:0: toc-tree-glob-pattern-no-match: toctree glob pattern 'cliconf/*' didn't match any documents
> ```
> [click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

@rajaspachipulusu17 lib/ansible/plugins/cliconf/netvisor.py is missing with doc section like other cliconf plugins. Something like - https://github.com/ansible/ansible/blob/c2cb82ec148875070320f56954e99f0cb48ac338/lib/ansible/plugins/cliconf/aireos.py#L22

**Comment by rajaspachipulusu17** [comment]
@Akasurde i have fixed the errors. 

It required manual review since PR has more that 50 files. Changes are common to most of the files. 


Thanks,
Rajas

**Comment by Akasurde** [comment]
cc @ganeshrn

**Review by ganeshrn — APPROVED** [review]

**Comment by ganeshrn** [comment]
@rajaspachipulusu17 Please add a doc PR for the netvisor platform Refer:
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/network/user_guide/platform_index.rst
https://github.com/ansible/ansible/tree/devel/docs/docsite/rst/network/user_guide

**Pull request merged**
