### PR TITLE
Complete re-work to work with current nova, other features

### PR DESCRIPTION
**Pull request by CaptTofu**
Hi there! Another shot - and I had decided to completely revamp it to be like the rax dynamic inventory plugin (and gave attribution)

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'd appreciate a write up of what changes you were intending to add, what new features there are, and what old features are removed.

We'll also have to get some OpenStack folks on the list to help review.

stopping by ansible-devel is probably appropriate, but maybe ansible-project for the volume.

Thanks!

**Comment by CaptTofu** [comment]
Michael,

Yesterday, I found out Monty et al are working on replacing heat with Ansible and are doing work on the a new heat module as well as the existing nova module and are interested in what I’ve done with the nova_facts module I wrote as well as the dynamic inventory plugin work. They also have a list of goodies they want to add and next week when I’m in Seattle will discuss with them.

I’ll work on a quick write-up about what I’ve done so far.

Regards,

Patrick

**Comment by emonty** [comment]
On first pass, this looks mostly good, but I haven't dug in in anger. I will say that adding support for OS_ env vars is really nice- although there is a if not config_file; sys.exit still in there, and it's entirely possible that this could 100% be successfully used without the config file present. I'll dig and and try to review more of this more closely.

**Comment by CaptTofu** [comment]
Changes:
- moved code that was formerly in main body into clear, concise module methods
- created connection module method and connect properly
- added "--private" flag so that one can specify "please use the private IP (fixed IP) of the instance as ansible_ssh_host
- added ability of plugin to use OS_x ENV for connection parameters, if set, and if nova.ini is not found. If nothing found, error out.
- added try/catch to connection
- added sane defaults for connection
- added slugify and to_dict for building up return data (per rax modules)

**Comment by CaptTofu** [comment]
- Allow specification of multiple regions and have it process each

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
