### PR TITLE
Add pluck filter

### PR DESCRIPTION
**Pull request by yvbeek**
##### SUMMARY
Add pluck filter to simplify extracting information from a JSON structure. This filter is a bit easier to use and more concise than the `map` filter. It also replaces a few situations where you would have to use the `json_query` filter (that requires the `jmespath` python library).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
filter_plugin

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/devops/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Example YAML structure:
```
sites:
  - name: default
    template: default

  - name: development
    template: dev
    upstream: 10.0.0.100
    domains:
      - { host: dev.mydomain.com }

  - name: production
    template: prod
    upstream: 10.0.1.100
    domains:
      - { host: prod.mydomain1.com, cert: mydomain1.com }
      - { host: prod.mydomain2.com, cert: mydomain2.com }
      - { host: prod.mydomain3.com, cert: mydomain3.com }

```

Let's say we've loaded the YAML above into a variable called `config` and we want to extract some information:
```
- set_fact:
     templates: "{{config|pluck('sites.template')|list}}"
     certs: "{{config|pluck('sites.domains.cert')|list}}"
     hosts: "{{config|pluck('sites.domains.host')|list}}"

# Results:
# templates = ["default", "dev", "prod"]
# certs = ["mydomain1.com", "mydomain2.com", "mydomain3.com"]
# hosts = ["dev.mydomain.com", "prod.mydomain1.com", "prod.mydomain2.com", "prod.mydomain3.com"]
```

With the `map` filter this would be a lot more complicated, because it would break when one of the entries doesn't have a `domains` property.

You can use the pluck filter in many scenarios. For example, extracting the file paths of the `find` module:
```
- find:
     paths: files/config
     file_type: directory
     register: result

- debug: msg={{result|pluck('files.path')|list}}
```

You can also provide an array for the `keypath` argument:

```
- debug: msg={{result|pluck(['files','path'])|list}}
```

### CODE REVIEW

**Comment by yvbeek** [comment]
Not sure what is wrong: `Run 65193 status is UNSTABLE.`

**Comment by bcoca** [comment]
isn't this pretty much the `selectattr` filter?

**Comment by yvbeek** [comment]
@bcoca `selectattr` is more of a filter function, this one is a recursive selector.
See http://www.oznetnerd.com/jinja2-selectattr-filter/

I've added the results of the function to my first example.

**Comment by sivel** [comment]
-1 from me.  I'm not a huge fan of this approach. Should the existing jinja2 filters not suffice, we already have `json_query` which can closely match this already.

**Comment by yvbeek** [comment]
@sivel The `json_query` filter requires external dependency `jmespath`.

I thought that the community might appreciate this filter as an easy helper between `map` and `json_query`.

Looking at my `sites` example, it is quite difficult to extract the `cert` property from all domains, `json_query` feels like overkill to do a simple action like that.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this PR because as stated above this seems to overlap with existing functionality.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
