### PR TITLE
cache group ancestors names

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

possible improvement for #36431

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

inventory
##### ANSIBLE VERSION

```
2.5/2.6
```

### CODE REVIEW

**Comment by AlanCoding** [comment]
Just checked it out, I'm hitting this traceback

```
$ time NUMBER_GROUPS=26 ansible-playbook -i scripts/connections/dag_max.py debugging/hello_world.yml -vvv
ansible-playbook 2.6.0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible-playbook
  python version = 2.7.11 (default, Oct 17 2016, 14:59:40) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
No config file found; using defaults
Parsed /Users/alancoding/Documents/repos/ansible-inventory-file-examples/scripts/connections/dag_max.py inventory source with script plugin
ERROR! Unexpected Exception, this is probably a bug: 'Group' object has no attribute '_ancestors_cache'
the full traceback was:

Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible/cli/playbook.py", line 104, in run
    loader, inventory, variable_manager = self._play_prereqs(self.options)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible/cli/__init__.py", line 804, in _play_prereqs
    inventory = InventoryManager(loader=loader, sources=options.inventory)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible/inventory/manager.py", line 145, in __init__
    self.parse_sources(cache=True)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible/inventory/manager.py", line 212, in parse_sources
    self._inventory.reconcile_inventory()
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible/inventory/data.py", line 118, in reconcile_inventory
    if group.name != 'all' and not group.get_ancestors():
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible/inventory/group.py", line 196, in get_ancestors
    if self._ancestors_cache is None:
AttributeError: 'Group' object has no attribute '_ancestors_cache'

real	0m1.014s
user	0m0.875s
sys	0m0.126s
```

**Comment by bcoca** [comment]
@AlanCoding weird it had passed tests, fixed the issue with missing property, try again

**Comment by AlanCoding** [comment]
I don't know why, but this doesn't seem to be making the particular example I had go any faster. My patience wore out at the following points for `ansible-inventory`:

```
running for 18 groups

real	0m39.852s
user	0m29.208s
sys	0m10.481s
```

And for running `ansible-playbook`:

```
running for 25 groups
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

real	0m44.690s
user	0m44.094s
sys	0m0.425s
```

The profiling looks pretty similar still too

screen shot 2018-02-26 at 2 57 29 pm

**Comment by bcoca** [comment]
closed in favor of #37039

**Comment by AlanCoding** [comment]
For the record, this remains an option that I would expect to speed up the loading a great deal. When I tested it earlier, I think the speed was just driven by some other constraints (which may be lifted after the other PR).

**Pull request closed without merging**
