### PR TITLE
docker_image: improve tagging examples

### LINKED ISSUE #50310: Docker (Re)Tag local images
##### SUMMARY
Ability to use docker tag

```
ansible --version
ansible 2.7.5
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/lukas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /home/lukas/.local/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```
##### ISSUE TYPE
I want to execte via ansible (not shell module), commands like such one:
`docker tag myimage:88 myimage:latest`

##### COMPONENT NAME
I think the right place is the module docker_image
##### ADDITIONAL INFORMATION
Possible scenario
1. You Push your Images (with Jenkins Build ID als Docker Tag) in your private docker registry
2. Ansible make docker login with the module docker_login
3. Ansible pull the image via docker_image
4. Ansible make a docker (re)tag from the pulled image
5. You restart your docker container, you need no always changes in your unit-file or smth. else.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Improves examples where images are tagged. Fixes #50310.

CC @cryptolukas

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docker_image

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
@gundalow thanks for reviewing and merging!

**Comment by cryptolukas** [comment]
thanks both of you that you accept my recommendation :)

**Comment by felixfontein** [comment]
@cryptolukas well, thanks for your recommendation :) There's still a lot to improve in the `docker_image` documentation, so if you have some more ideas, feel free to mention them ;-)

**Comment by cryptolukas** [comment]
I come back to you when have one.

At the moment I prepare a CD from scratch with Ansible and Jenkins, with Docker. A lot of work still before me. :)

**Pull request merged**
