### PR TITLE
Fix strat inv (#58982)

### PR DESCRIPTION
**Pull request by bcoca**
* Fix strategy functions that update inventory

* added tests

(cherry picked from commit a7b14ec1becb947cc290deebe309ef06a12d1f7e)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

strategy

### CODE REVIEW

**Comment by abadger** [comment]
Waiting on discussion from sdoran about what to do about this.

**Comment by samdoran** [comment]
I don't think we should hold up this backport in order to redesign the interface since that is a bigger project. This fixes a legitimate bug.

**Comment by s-hertel** [comment]
shipit. I think changing the interface is probably too invasive to backport and I'm happy to work on it this/next week for the 2.9-2.10 timeframe after I finish cleaning up 59743.

**Comment by abadger** [comment]
@shertel and @sdoran have committed to looking at the unaddressed API problems here.  Will merge this backport for 2.8.4.

**Pull request merged**
