### PR TITLE
[ON HOLD] Fix ovirt.ovirt collection name -> ovirt.ovirt_collection

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The `ovirt.ovirt` collection is actually called `ovirt.ovirt_collection`: https://galaxy.ansible.com/ovirt/ovirt_collection

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml
lib/ansible/config/routing.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
**Don't merge** before oVirt/ovirt-ansible-collection#14 is resolved.

**Comment by tadeboro** [comment]
The routing table entries for oVirt also need to be adjusted. Currently, they still point to community.general collection.

**Comment by felixfontein** [comment]
@tadeboro sorry for the confusion, the routing table already was adjusted. The modules and module_utils are spread over multiple collections.

**Comment by mnecas** [comment]
@felixfontein this PR can be closed, I renamed the `ovirt.ovirt_collection` to `ovirt.ovirt` and deprecated the old one.

**Comment by felixfontein** [comment]
I'll create a PR later to update the dependency in community.general.

**Pull request closed without merging**
