### PR TITLE
apt module: Add support for installing .deb packages

### PR DESCRIPTION
**Pull request by lorin**
Support installing .deb packages from the local filesystem.

```
apt: deb=/tmp/mypackage.deb
```

This change modifies the install() function so that it returns results instead of calling
exit_json() and fail_json directly, so that it can be reused by the new deb_install 
function to install package dependencies.

### CODE REVIEW

**Comment by zbal** [comment]
+1

**Comment by jeremymturner** [comment]
This would be a great feature. Can't wait until it's available!

**Comment by jsmartin** [comment]
Love this idea... one suggestion -- what if it could also pull the deb from a url and then install it?  Then it could be very similar in compatibility with the yum module.

**Comment by zbal** [comment]
There was this feature in the original PR but it's a wacky approach as u
may not want to download a 200mb deb file every time then check for idem
potency. You can have a look at it and see if it fits ur needs.

Cheers,

Vincent

On Monday, March 10, 2014, jsmartin notifications@github.com wrote:

> Love this idea... one suggestion -- what if it could also pull the deb
> from a url and then install it? Then it could be very similar in
> compatibility with the yum module.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/5910#issuecomment-37153164
> .

## 

Vincent Viallet
Operations Director - ChinaNetCloud - www.chinanetcloud.com

tel : (0086) 137 9522 1272
mail : vincent.viallet@gmail.com
skype: balou_fr

**Comment by jctanner** [comment]
@lorin thank you!

**Pull request merged**
