### PR TITLE
Vmware guest iteritems

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

module_utils/vmware.py

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Fixes an issue reported in #19821.

cc: @nerzhul @jctanner

### CODE REVIEW

**Comment by dagwieers** [comment]
@mattclay @gundalow Again Shippable errors in unrelated code, quite frustrating. I suggest everyone follows the same PR process so that code is *always* being tested before being merged.

**Comment by dav1x** [comment]
Awesome!

**Comment by nerzhul** [comment]
shipit

**Comment by dav1x** [comment]
shipit

**Comment by dagwieers** [comment]
Don't mind the Shippable output...

**Comment by jctanner** [comment]
@dagwieers thank you!

**Comment by mattclay** [comment]
@dagwieers For once, this was an unrelated failure that wasn't the result of an untested change. It was due to an unexpected (and unexplained) interaction between unit tests. The tests run in isolation passed, but failed together. I've fixed the issue and am working on isolating unit tests better to avoid this in the future.

**Comment by dagwieers** [comment]
@mattclay Yesterday we had another issue that caused failures on unrelated code. https://github.com/ansible/ansible/pull/21059#issuecomment-277721581

I know this isn't easy and I know you are doing your best to avoid this and you can only do so much. It's just so frustrating sometimes to have to check Shippable output for false failures, and knowing that all new PRs are affected too. Don't know what the solution would be. Maybe a shippable_broken for ansibot ?

**Pull request merged**
