### PR TITLE
Added basic support for hash_behaviour=merge in roles

### PR DESCRIPTION
**Pull request by gmiroshnykov**
Dict vars passed to roles are now properly merged instead of simply overriding dict vars that are coming from vars_files.

This pull request probably needs more eyes, I'm not sure my overall approach to vars handling is good enough. Any suggestions are welcome!

Also, sorry for unintentional whitespace cleanup.
You can view the diff with less noise here:
https://github.com/ansible/ansible/pull/3114/files?w=1

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks good, in queue for testing shortly and inclusion in 1.2...

Thanks!

**Comment by gmiroshnykov** [comment]
Oh, I thought I missed the deadline for 1.2 :)
Thanks!

**Comment by mpdehaan** [comment]
Just now getting around to merging.

can you please submit this without merge commits?

A good tip is to start a new branch for each new feature

Also use "git pull --rebase" vs git pull, and "git rebase" rather than "git merge"

**Comment by gmiroshnykov** [comment]
Done.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
