### PR TITLE
Added js documentation generation 

### PR DESCRIPTION
**Pull request by mavimo**
This is the first step to add JS documentation generation in ansible, need to add html/css/js to make it work.

Please python code review (I'm a python n00b :) )

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!  I'll review this shortly, but looks good at first glance.

Is there a corresponding pull request to add the static files around this to the 'ansible-docs' project?

(Note we have a version of jQuery and bootstrap on ansible.cc and I will probably change it to make it use those to avoid the extra download)

**Comment by mavimo** [comment]
@mpdehaan I'm using AngularJS but I can try change to use jQuery + jQuery.tmpl, but some extra code need to be downloaded. I think we can use angularJS directlry from google CDN (//ajax.googleapis.com/ajax/libs/angularjs/1.0.2/angular.min.js) is just 76kb and maybee user aready have it on their local cache.

**Comment by mpdehaan** [comment]
All of that from the CDN should be fine, yeah.

**Comment by mpdehaan** [comment]
Can this please be integrated with the existing module formatter script?  It would result in less to maintain, it could be another --template mode or something and also make it act slightly differently.

**Comment by mavimo** [comment]
I can integrate, but I prefer separate it because have a different functionality, do not format documentation in different format (module_format do it and export json) but aggregate all this information in a single file with some js code to make it usable in web page. Maybe this script can be move in ansible-docs project.. and ansible export a json file for each module and ansible-docs aggregate it.

What approach do you prefer? Move script in docs or aggregate?

**Comment by mpdehaan** [comment]
Having a template for a JSON file and then having it simply aggregrated as
a directory of JSON files into one larger one sounds great.

**Comment by mavimo** [comment]
Update `module_formatter` to generate JSON files (`--type json`) and JS file (`--type js`). Also changed Makefile to automatically generate JS docs.

**Comment by mpdehaan** [comment]
I'm seeing merge conflicts around this one, can you please rebase and resubmit (preferably as a single squashed commit)?   Thanks!

**Comment by mavimo** [comment]
See https://github.com/ansible/ansible/pull/1272

**Pull request closed without merging**
