### PR TITLE
Add Windows example of raw command

### PR DESCRIPTION
**Pull request by jvandermeulen**
Perform shutdown of Windows OS using Microsoft.PowerShell.Management module

##### SUMMARY

Add first example for Windows boxes

##### ISSUE TYPE

- Docs Pull Request

##### ANSIBLE VERSION

```paste below

```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jborean93** [comment]
This isn't something we want as shutting down a host can lead to other issues with Ansible. Happy to show another PowerShell example but not one that shutdowns the server.

**Review by dagwieers — APPROVED** [review]
Thanks for the contribution. It is good to have a Windows example, and ~Stop-Computer is a useful example at that~. I slightly modified the example and did some more cleanup to the docs.

**Comment by dagwieers** [comment]
@jvandermeulen Since @jborean93 objects to the example, I replaced it with an invocation of `Get-WmiObject -Class Win32_UserAccount`.

Although something like that would work as well with the `win_shell` module.

**Comment by jvandermeulen** [comment]
@dagwieers Excellent idea!

**Pull request merged**
