### PR TITLE
Add GetMemoryInventory command to Systems category in redfish facts module

### PR DESCRIPTION
**Pull request by xmadsen**
##### SUMMARY

This pull request creates a GetMemoryInventory Systems function in redfish_facts. It gathers details about memory DIMMs in the system, and omits any that are marked Absent.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

redfish_facts

### CODE REVIEW

**Review by billdodd — COMMENTED** [review]
@xmadsen - Thanks for yet another PR.

Since you last added anything to the redfish_facts module, a change was made to get inventory data from all the systems present in the service. To update your PR to use this new model, it should just take a few short steps:

1.   add a `get_multi_memory_inventory()` method - this will be a very short wrapper function; see `get_multi_cpu_inventory()` for an example.
2. add a `systems_uri` param to your `get_memory_inventory()` method
3. in `get_memory_inventory()`, change the use of `self.systems_uri` to just `systems_uri`
4. in redfish_facts.py, change the call to `rf_utils.get_memory_inventory()` to call `rf_utils.get_multi_memory_inventory()` instead

Have a look at `get_cpu_inventory()` and `get_multi_cpu_inventory()` as an example to see the pattern.

**Review by billdodd — APPROVED** [review]
@xmadsen - Thanks for making the updates. I reviewed the code ran some tests. Looks good.

shipit

**Comment by billdodd** [comment]
Of course, right after I approved, I thought of something else: It would be good to include a GetMemoryInventory example in the EXAMPLES docstring so users will know it is available.

**Comment by xmadsen** [comment]
Added it! 

@samerhaj

**Comment by xmadsen** [comment]
@billdodd do you need to shipit again? or ansibot just didn't catch it to put a tag on this PR

**Comment by billdodd** [comment]
I'll add one again to be sure, but I think the label hasn't been added due to the requirement to get ship-its from two maintainers.

**Review by billdodd — APPROVED** [review]
Still looks good after the EXAMPLES addition.

shipit

**Comment by jose-delarosa** [comment]
I'll take a look today.

**Comment by jose-delarosa** [comment]
Looks good. One small thing, in line 900, update comment from CPU to Memory DIMMs:

`# Get a list of all CPUs and build respective URIs`

Not a showstopper of course, so maybe fix in a future PR?

shipit

**Comment by gundalow** [comment]
@xmadsen Thank you for this PR, looks like there has been a lot of activity with the  `remote_management` modules recently which is great, though that does mean a rebase is needed, after you do that I'll merge.

**Comment by xmadsen** [comment]
@gundalow this should be all good now 👍

**Comment by samerhaj** [comment]
Looks good. Shipit!

**Review by billdodd — APPROVED** [review]
Approving again after updates and rebase.

shipit

**Comment by gundalow** [comment]
Great work all, thank you!

**Pull request merged**
