### PR TITLE
Add a sensu_client module

### PR DESCRIPTION
**Pull request by dmsimard**
##### SUMMARY
This provides a sensu_client module in order to be able to dynamically
configure a Sensu client.

It takes a different approach than the existing Sensu modules such as
sensu_check but is hopefully a much more flexible and simple way of
handling configurations.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
sensu_client

##### ANSIBLE VERSION
Ansible 2.4

### CODE REVIEW

**Comment by dmsimard** [comment]
@dmizelle @andsens: FYI

**Comment by dmsimard** [comment]
This is a different approach than what ``sensu_check`` and ``sensu_subscription`` are currently doing and I would like to eventually refactor them both to largely simplify them and their maintenance.

For ``sensu_check`` and ``sensu_subscription``, instead of configuring every check/subscription inside the same file, the checks would live in ``/etc/sensu/conf.d/checks/{{ name }}``.json, same for subscriptions in ``/etc/sensu/conf.d/subscriptions/{{ name }}``.json.

It would work the same for an eventual ``sensu_handler`` module that I would create.

**Comment by andsens** [comment]
Impressive work @dmsimard. I skimmed the code and it looks good. For the rest I suppose you have the tests to rely on :-)  
Definite ACK on the `conf.d/checks/{{ name }}.json` variant. That'd be much easier to maintain, especially when you manually want to verify/edit something.

**Comment by dmsimard** [comment]
Did some minor tweaks and rebased and now it's failing documentation tests.. not sure why yet. I'll look tomorrow.
```
$ ansible-doc sensu_client -vvvv
ansible-doc 2.4.0
  config file = None
  configured module search path = [u'/home/dmsimard/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dmsimard/dev/ansible/.tox/py27/lib/python2.7/site-packages/ansible
  executable location = /home/dmsimard/dev/ansible/.tox/py27/bin/ansible-doc
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
No config file found; using defaults
Traceback (most recent call last):
  File "/home/dmsimard/dev/ansible/.tox/py27/lib/python2.7/site-packages/ansible/cli/doc.py", line 162, in run
    text += self.get_man_text(doc)
  File "/home/dmsimard/dev/ansible/.tox/py27/lib/python2.7/site-packages/ansible/cli/doc.py", line 372, in get_man_text
    desc = " ".join(doc['description'])
TypeError: sequence item 0: expected string, AnsibleMapping found

ERROR! module sensu_client missing documentation (or could not parse documentation): sequence item 0: expected string, AnsibleMapping found
```

**Comment by dmsimard** [comment]
This is once again ready for review after some minor changes. Let me know if this works. I am almost ready to submit a ``sensu_handler`` module with the same approach.

**Comment by dmsimard** [comment]
Updated commit: Added support for check mode and moved argument validation to "required_if".

**Comment by dmsimard** [comment]
@andsens I don't think this needs anything else to land, let the bot know if he can shipit or something like that :D

**Comment by timlnx** [comment]
shipit

**Comment by tbielawa** [comment]
[shipit]

**Comment by andsens** [comment]
shipit

**Pull request merged**
