### PR TITLE
Flatten the directory hierarchy of modules

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Flatten the directory hierarchy of modules

With the reduction in modules, having nested directories is more hassle than it is worth.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
many

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by nitzmahone — APPROVED** [review]

**Comment by bcoca** [comment]
cc @acozine @samccann  jic, since list_ pages for modules might be impacted

**Review by mattclay — CHANGES_REQUESTED** [review]
The unit tests for modules should also be flattened to match.

**Comment by gundalow** [comment]
What's the advantage of these changes?

**Comment by sivel** [comment]
> The unit tests for modules should also be flattened to match.

This is done.

**Review by mattclay — APPROVED** [review]

**Comment by jctanner** [comment]
!needs_collection_redirect

**Comment by samccann** [comment]
Generated locally and the docs look good - this removes the subheadings on the list_of pages that had only one or two items under each.

**Comment by samccann** [comment]
When I generate (make webdocs) locally, I get duplicated entries here:

image

Not sure what's causing that?

**Comment by sivel** [comment]
@samccann Technically, they are are different, although the list is the same.  I'll follow up elsewhere, but the first is the category, the 2nd is all, which are now the same.

**Pull request merged**
