### PR TITLE
Adds facts for duplex and speed for Linux network devices.

### PR DESCRIPTION
**Pull request by jsmartin**

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks fine to me.

Just a refactoring note, but we should probably assign the path to a variable rather than calculating it twice, i.e.

duplex_path = os.path.join(...)

**Comment by jsmartin** [comment]
Cool. This gets merged and you will re-factor later or you want me to do that now?

**Comment by jsmartin** [comment]
Was considering adding facts for the output ethtool -g and ethtool -k to this, would that still be accepted?

**Comment by jsmartin** [comment]
I'm noticing this is failing with bonded interfaces.  In the case that eth0 and eth1 bonded to bond0, bond0 will have unreadable duplex/speed settings that result in : 

```
fatal: [riak3] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1383841996.79-275129482267960/setup", line 3200, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1383841996.79-275129482267960/setup", line 2190, in main
    data = run_setup(module)
  File "/root/.ansible/tmp/ansible-1383841996.79-275129482267960/setup", line 2131, in run_setup
    facts = ansible_facts()
  File "/root/.ansible/tmp/ansible-1383841996.79-275129482267960/setup", line 2122, in ansible_facts
    facts.update(Network().populate())
  File "/root/.ansible/tmp/ansible-1383841996.79-275129482267960/setup", line 1353, in populate
    interfaces, ips = self.get_interfaces_info(ip_path, default_ipv4, default_ipv6)
  File "/root/.ansible/tmp/ansible-1383841996.79-275129482267960/setup", line 1415, in get_interfaces_info
    interfaces[device]['speed'] = int(open(os.path.join(path, 'speed')).read().strip())
IOError: [Errno 22] Invalid argument
```

working on a fix that will test for os.path.exists(os.path.join(path, 'bonding'), and if it exists, not attempt to set these facts.

**Comment by jsmartin** [comment]
Adding a conditional, but it's starting to get gnarly.  It seems like there should be some general test function with exception catching to see if some of the proc files are actually readable.  As shown above, attempts to read files in proc can result in IOError: [Errno 22] Invalid argument.

**Comment by jsmartin** [comment]
So did some more testing.. In some virtual environments, I still get the same exception.. So I really do think catching that "IOError: [Errno 22] Invalid argument" is going to be the best way around that.  Do you have a preference for where that should occur?

**Comment by mpdehaan** [comment]
Hi James, sorry for the late response on this one -- I'm guessing there _MAY_ be interest in a more detailed network facts module of some kind, but the number of users needing this may also be low, in which case they may be content to parsing a few commands with register.

I'm going to close this one for now as I want to control the level of work done by the setup module (and the volume of detail returned).

**Pull request closed without merging**
