### PR TITLE
ansible-test pssa update and new rules

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
This bumps the PSSA version to 1.20.0 which introduces new rules including an optional rule to check for consistent indentation in PowerShell modules. The current proposal is to set the indentation to 4 spaces and the pipeline style to indent on first pipeline like

```powershell
foo |
    bar |
    baz
```

Will need to get consensus at the next Windows working group to see if this is acceptable. Might also bring up the [AvoidLongLines](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/Rules/AvoidLongLines.md) rule and see if we want to enable that.

Reliant on https://github.com/ansible/base-test-container/pull/5 and https://github.com/ansible/default-test-container/pull/71.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible-test pslint

### CODE REVIEW

**Comment by briantist** [comment]
personally, I prefer 4 space indent, and first-line hanging indent for pipelines (as shown in example).

For line length, I think the rest of Ansible uses 160 chars? we should be consistent with that, imo. Isn't it already enforced, even for Windows modules? or am I mistaken?

**Comment by jborean93** [comment]
> For line length, I think the rest of Ansible uses 160 chars? we should be consistent with that, imo. Isn't it already enforced, even for Windows modules? or am I mistaken?

I thought it was but the rule was only added in 1.20.0 so unless we already have something that just checks any file regardless of the extension I'm not sure what else would check it. Will have to investigate further.

**Review by nitzmahone — APPROVED** [review]
Looks like there's a bug in the inline dictionary validator and/or suggestor where it's skipping a leading space but injecting a trailing space, eg `@{foo = 'bar' }`, but we should probably just merge as-is, and if they fix it later, we can do another one of these to clean it up and enforce it properly. v1.20 doesn't seem to complain either way, but `-Fix` changes it. So at least we won't be forcing people to use a broken format, and we still get the other benefits of the new rules.

**Comment by jborean93** [comment]
I've opened a bug for that problem https://github.com/PowerShell/PSScriptAnalyzer/issues/1742. PSSA accepts both `@{ foo = 'bar' }` and `@{foo = 'bar' }`. While annoying you can still keep things consistent using the first format `@{ foo = 'bar; }`. This is only really problematic if using `-Fix` to automatically apply the suggested fix.

**Pull request merged**
