### PR TITLE
Add 'stripext' filter plugin.

### PR DESCRIPTION
**Pull request by cmhamill**
Removes file extension, if any, from input string.

### CODE REVIEW

**Comment by jimi-c** [comment]
You're missing a comma at the end of that line.

**Comment by mpdehaan** [comment]
I'm guessing we'd rather surface splitext (the native function) and you could get the last attribute off of it.

Further, when adding a new filter plugin it does need to be documented so people can find it :)

**Comment by cmhamill** [comment]
D'oh.  All better.

**Comment by amenonsen** [comment]
This PR is now obsolete and can be closed (splitext is included in filters/core.py in devel and also documented).

**Comment by bcoca** [comment]
closing as per above

**Pull request closed without merging**
