### PR TITLE
cloud/ovirt: minor fix on documentation

### PR DESCRIPTION
**Pull request by tareqalayan**
##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### SUMMARY

```

```

### CODE REVIEW

**Comment by tareqalayan** [comment]
@machacekondra just a documentation minor addition, please review

**Comment by tareqalayan** [comment]
@machacekondra

**Comment by machacekondra** [comment]
Looks good to me, thank a lot!

**Comment by machacekondra** [comment]
@ryansb shipit

**Pull request merged**
