### PR TITLE
Unification of default value for option update_cache

### PR DESCRIPTION
**Pull request by sergeymavrin**
##### SUMMARY

Unification of default value for option update_cache

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by mkrizek** [comment]
See:
* https://github.com/ansible/ansible/pull/81543
* https://github.com/ansible/ansible/pull/80810

**Comment by jborean93** [comment]
The default here isn't `False` but not set. This is a complex scenario where there's a tertiary set of options, not set, `True`, or `False`. The docs probably need to be made clearer about this as today it indicates the default is `False` which is only somewhat true.

**Comment by sergeymavrin** [comment]
@jborean93 not set value will be interpreted as False. In this case - there is no difference - not set or False. But when reading documentation and want to find fast answer - very difficult to find it out. It's a documentation and mostly you don't need to reed the description of the option - you already know what option makes, but forget the defaults. In case of update_cache option - you have to read the whole cell of the table.
I just tried to make documentation more clear for humans, not robots )

**Comment by jborean93** [comment]
> @jborean93 not set value will be interpreted as False. In this case - there is no difference - not set or False

That isn't true, there are areas where it explicitly checks for `False` rather than `Falsey` values. For example https://github.com/ansible/ansible/blob/cb8cb8936aee5049939fdac57f407a3a6c8b21bc/lib/ansible/modules/apt.py#L1283. I don't fully understand the code myself but it definitely acts as a tertiary like value

* Unset/None (default)
  * `apt-get update` is run
  * Does not call [apt.cache.Cache.update](https://apt-team.pages.debian.net/python-apt/library/apt.cache.html#apt.cache.Cache.update)
* `False`
  * `apt-get update` is not run
  * Does not call [apt.cache.Cache.update](https://apt-team.pages.debian.net/python-apt/library
* `True`
  * `apt-get update` is run
  * Does call [apt.cache.Cache.update](https://apt-team.pages.debian.net/python-apt/library

I have no idea what the difference is between calling `apt-get update` as the command vs the `Cache.update()` function through the `apt` library but that's what the code does.

Ultimately the docs are pretty vague and most likely needs expanding but setting the default here to `False` is not correct unless the code itself changes. Unfortunately I don't know `apt` too well so I can't really give much help there sorry.

**Comment by sergeymavrin** [comment]
I'm looking into code and cannot see the difference between None and True - in both situation is called
`module.run_command(['apt-get', 'update'], check_rc=True)`
But when not set (None on function module.params.get('update_cache') with NoneType class) it's not really update cache. Can you explain such behavior?

**Comment by jborean93** [comment]
The line https://github.com/ansible/ansible/blob/cb8cb8936aee5049939fdac57f407a3a6c8b21bc/lib/ansible/modules/apt.py#L1283

```python
if module.params.get('update_cache') is False:
    module.warn("Auto-installing missing dependency without updating cache: %s" % apt_pkg_name)
else:
    module.warn("Updating cache and auto-installing missing dependency: %s" % apt_pkg_name)
    module.run_command(['apt-get', 'update'], check_rc=True)
```

The if check here will only skip running `apt-get update` if `update_cache` is `False`. So when it's not set (`None`) or explicitly set to`True` then `apt-get update` will be running here.

**Comment by sergeymavrin** [comment]
Yes, I have wrote the same, my question was - why when None - it's not updating cache, dn when True - updating, though in both cases
`module.run_command(['apt-get', 'update'], check_rc=True)`
is called

**Comment by s-hertel** [comment]
The why is at least partially backwards compatibility. The description for `update_cache` is not accurate if the APT Python bindings are missing, so that should be improved. The module can't run without python-apt, so making the default for update_cache False could break existing playbooks that don't set `update_cache` but rely on the current behavior.

This behavior was added in https://github.com/ansible/ansible-modules-core/commit/0313c517e96d2308f71982750265163670198023 initially, doesn't look like there's a PR for context about why. Then this was improved later, to only update the cache if `update_cache` was not explicitly set to False in https://github.com/ansible/ansible/pull/56549.

**Comment by Akasurde** [comment]
Closing this as per above comment.

**Pull request closed without merging**
