### PR TITLE
Set default XMPP message type to 'chat'.

### PR DESCRIPTION
**Pull request by neuroid**
This enables sending messages to partychat-like services (e.g. [im.partych.at](http://partychapp.appspot.com/)).
This commit also fixes handling of 'to' argument for non-chatroom recipients.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I would think this probably needs an example and more explanation about when to use this parameter maybe?

**Comment by neuroid** [comment]
The `chat` type is more of a sensible default. It should work with all standard-compliant clients and services. Honestly, I can't think of any good use cases of setting `type` to a different value. The only thing that comes to mind is a misbehaving client or some specific service.

It might make sense to not expose a `type` option and just use `chat`. But some people might find it useful.

**Comment by bcoca** [comment]
You currently don't need to specify type as the module should figure it out
itself by looking at the to= field. I currently set it to 'groupchat' when
sending to a room (this is my normal use case). It is left unset otherwise,
the default should be 'normal'.

The difference between 'normal' and 'chat' seems to be that normal opens
new window at every message, chat keeps the same window.  I only tested
this in finch, the RFC leaves a lot of implementation details up to the
clients so millage might vary.

It might make more sense to default to 'headline' as both 'normal' and
'chat' are intended for bidirectional communication and headline is meant
for 1 way.

http://xmpp.org/rfcs/rfc3921.html

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by neuroid** [comment]
I couldn't get `headline` to work with Pidgin (it might be because I'm using Google's XMPP servers). Also, `normal` doesn't work with http://partychapp.appspot.com/. It seems that `chat` is a good default (i.e. allows sending messages to a broad number of clients/services without tweaking the module).

(Partychat is my normal use case)

**Comment by bcoca** [comment]
then agreed, just set the default to chat, leaving the groupchat for when
sending to a room, since the rest seem to break. No need to give a user the
option then when they don't really work.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
merged, thanks!

@bcoca couldn't tell if that fulfills any questions of yours, if not, let me know.

**Comment by bcoca** [comment]
its is 'fine', the standard doesn't require it, but most clients seem to
depart from the RFC, unless someone complains this should stay as default.

On Sat, Aug 3, 2013 at 2:29 PM, Michael DeHaan notifications@github.comwrote:

> merged, thanks!
> 
> @bcoca https://github.com/bcoca couldn't tell if that fulfills any
> questions of yours, if not, let me know.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3659#issuecomment-22059251
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by RPiyush** [comment]
If we have to send a message we set:
[message addAttributeWithName:@"type" stringValue:@"chat"];

my messages sent successfully but now i want to send buddy request from myApp,
so what type i have to set??

**Pull request merged**
