### PR TITLE
Add testcases for github_issue

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
test/integration/targets/github_issue/aliases
test/integration/targets/github_issue/tasks/main.yml
test/integration/targets/github_issue/vars/main.yml

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Review by dagwieers — APPROVED** [review]
LGTM

**Review by pdellaert — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@calfonso @pdellart @dagwieers Thanks for review and merge.

**Pull request merged**
