### PR TITLE
[WIP] Switch to argparse

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY

Optparse is deprecated, all versions of python we use controller side have argparse support.

Additionally this gives us easy integration with argcomplete which we already use in ansible-test for command and option completion.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
cli

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

To test argcomplete functionality, follow roughly the same instructions as ansible-test:

```
eval "$(register-python-argcomplete ansible)"
eval "$(register-python-argcomplete ansible-playbook)"
...
```

This change was made as minimally invasive as possible.  We can extend functionality later.  Currently to support only changes to the parser, I've effectively aliased a `args` positional argument to `self.args` so that the existing API still works the same.

In the future, we can rework the assumptions of how optparses `parse_args` worked, where it returned a tuple of `options, args`

### CODE REVIEW

**Comment by bcoca** [comment]
need to change https://github.com/ansible/ansible/blob/devel/docs/bin/generate_man.py as it relies on optparse to generate the man pages.

**Comment by sivel** [comment]
> need to change https://github.com/ansible/ansible/blob/devel/docs/bin/generate_man.py as it relies on optparse to generate the man pages.

Thanks, I failed to grep the source outside of `bin` and `lib`

**Comment by gundalow** [comment]
+10000000000 for completion

**Comment by sivel** [comment]
There's something I may need to figure out.  The commands with subparsers, `ansible-galaxy` and `ansible-vault` run into an interesting situation with arguments.

The following works:

```
ansible-vault -vvvvvv encrypt  --vault-password-file vault-password /tmp/tmp.DJbPfCPGc5/test_file
```

The following fails:
```
ansible-vault encrypt -vvvvvv --vault-password-file vault-password /tmp/tmp.DJbPfCPGc5/test_file
```

That is because the `-v` argument belongs to `self.parser` and not to the subparser.

subparsers can take a `parents`, where I could do `parents=[self.parser]`, however that makes all the subparser commands available to the active subparser, and that isn't what we want.

Example of what that would allow:

```
ansible-vault view view something.yml
```

**Comment by sivel** [comment]
I may just add `-v` to those subparsers explicitly.  That seems to make sense, and doesn't duplicate much.  That is really the only arg that doesn't work properly

**Comment by bcoca** [comment]
I might be asking something obvious ... but why change the parsing library? what do we gain?

**Comment by sivel** [comment]
I roughly described that in the initial description.  `optparse` is deprecated as of 2.7/3.2, and can be eventually removed.  optparse is rarely used these days, and argparse has more functionality and is debatably more powerful.  This future proofs us, and uses something people are going to be more used to.

We also have to do less manual stuff to get the parser working.  optparse doesn't generate good help docs for subparsers, so we were hand writing out usage docs.

Also we get easy auto complete.

**Comment by bcoca** [comment]
well,the script i point at above autogenerates the man pages to avoid the manual part.

I understand the future proofing, but I don't see an immediate benefit as most seem to be features we don't use or have already worked out/into optparser.

**Comment by sivel** [comment]
Man pages, and `-h` are completely different.  For me, I nearly never use man pages.  I almost exclusively use `-h`.

**Comment by bcoca** [comment]
`-h` was already covered by argparse, the only 'manual parts' were the prolog and epilog .. which you cannot really derive from options

**Comment by sivel** [comment]
We were manually specifying `usage` in `-h` for every command, which isn't needed with argparse, but was done so due to the fact that `-h` in optparse wasn't giving us something useful..

**Comment by gundalow** [comment]
Tab completion is a big selling for me me personally

**Comment by bcoca** [comment]
@sivel, any plans to try to get this into 2.5? i would want a change this important to go in as early as possible to workout all the kinks

**Comment by sivel** [comment]
I'll attempt to give it some time, and get back here.

Looks like I've got some merge conflicts, so it may take a bit of work.

**Comment by bcoca** [comment]
you also have more command line utilities and a dependency for document generation (manpage and html)

**Comment by sivel** [comment]
With argparse not in py2.6, and this PR being as out of date as it is, I'm going to close for now.  Maybe we'll re-evaluate for ansible 2.7.

**Pull request closed without merging**
