### PR TITLE
Add the ability to fill ansible_host with VM private IP

### PR DESCRIPTION
**Pull request by fernandezcuesta**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
azure_rm

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY
When SSH access to VMs are proxied by a jumpbox, but these VMs still have an assigned public IP address (for example, web servers listening on SSH only from a private network), `azure_rm.py` should fill `ansible_host` value to the private IP address instead of the public one.
~Additionally a small refactoring was done and style corrections done to comply to PEP8.~

### CODE REVIEW

**Comment by jctanner** [comment]
@chouseknecht can you review this please?

**Comment by thiagocaiubi** [comment]
Any update on this?

**Comment by calfonso** [comment]
@fernandezcuesta could you rebase this before we finish a review on it? Thanks!

**Comment by fernandezcuesta** [comment]
opening a new PR, just made a mess out of it

**Comment by fernandezcuesta** [comment]
follow-up in #27692

**Comment by thiagocaiubi** [comment]
Hey @calfonso, could you review the new PR please?

**Comment by calfonso** [comment]
@thiagocaiubi it's a closed PR

**Comment by thiagocaiubi** [comment]
@calfonso the new PR is still open https://github.com/ansible/ansible/pull/27692

References:
https://github.com/ansible/ansible/pull/18541#issuecomment-319910003
https://github.com/ansible/ansible/pull/18541#issuecomment-319913111

**Comment by calfonso** [comment]
@thiagocaiubi waiting for a review on #27692

**Pull request closed without merging**
