### PR TITLE
Updated release and maintenance page

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Update the release and maintenance page

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docs release and maintenance

##### ANSIBLE VERSION
```
devel
```

### CODE REVIEW

**Comment by dagwieers** [comment]
@jborean This one is related #42178, most people will end up on an old version of this document so we ought to forward them to the devel one.

**Comment by gundalow** [comment]
Assigning to @acozine so she can decide how to proceed with this

**Comment by jborean93** [comment]
@dagwieers I don’t think it is related. The [devel](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html) page is showing the outdated information as this was never updated.

Agree this would be an issue once merged and someone goes to a differently versioned page but this still needs to be in place.

**Comment by dagwieers** [comment]
@jborean93 It is related in the sense that it is about a similar problem. Users ending up with wrong/old information. It's a solution in two parts, (1) updating the new information (2) guiding users away from outdated copies. It doesn't mean this PR is useless, to the contrary.

**Comment by dagwieers** [comment]
@jborean93 The only reason to put it to your attention is that I cannot fix it. It requires carefully put redirects so it doesn't need to be managed every release.

**Comment by jborean93** [comment]
@dagwieers yep that's fair enough, I believe there is some work or planning some work to try and fix this but not really sure myself.

**Pull request merged**
