### PR TITLE
New Module na_elementsw_cluster_config

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
New Module na_elementsw_cluster_config -- Configure Clusters in ElementSW

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
- na_elementsw_cluster_config

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]
shipit

**Review by thedoubl3j — APPROVED** [review]
module looks good, CI is looking good. lgtm

**Comment by thedoubl3j** [comment]
> module looks good, CI is looking good. lgtm

a question regarding this though as I am not familiar, would users need to remove things by chance? I am only seeing enable features and or read features. Just wondering

**Comment by lonico** [comment]
> > module looks good, CI is looking good. lgtm
> 
> a question regarding this though as I am not familiar, would users need to remove things by chance? I am only seeing enable features and or read features. Just wondering

@thedoubl3j  The cluster is created or deleted separately (there is another module).  The idea is that the default values are good enough (simplicity) but they can be tweaked if needed.

**Comment by thedoubl3j** [comment]
@lonico gotcha, just wondering. trying to simplify things where we can. :+1:

**Comment by gundalow** [comment]
Thanks for this PR.
I'm wondering why this isn't part of https://docs.ansible.com/ansible/devel/modules/na_elementsw_cluster_module.html

**Comment by lonico** [comment]
> Thanks for this PR.
> I'm wondering why this isn't part of https://docs.ansible.com/ansible/devel/modules/na_elementsw_cluster_module.html

Creating a cluster is a special operation for ElementSw.   
It's really bootstrapping, and creating the system so that it is available for further configuration.
So we would like to keep this module to a minimum.   We actually found a bug in na_elementsw_cluster, as it handles password differently, so na_elementsw_cluster will need to use a different template than all other na_elementsw modules.

**Comment by gundalow** [comment]
@lonico Thank you for the info in https://github.com/ansible/ansible/pull/52373#issuecomment-475696040 combining these would generally be good, though I understand the reasons you've mentioned.

This is something we all need to be mindful when designing other modules.

Merging

**Pull request merged**
