### PR TITLE
Remove changelog entries related to content that has migrated to collections

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Remove changelog entries related to content that has migrated to collections

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
many many many

##### ADDITIONAL INFORMATION

The changelog entries being removed in this PR relate to content that has migrated to collections.

And more specifically these changelogs only have a 1:1 with where the content was migrated to.

This will be an iterative process, and more changelog fragments will be removed later.

The attached JSON contains the changelog fragment data, and the associated collections. This can be used by the collection owner to pull in their respective changelog data.

[changelog.json.txt](https://github.com/ansible/ansible/files/4394217/changelog.json.txt)

### CODE REVIEW

**Comment by sivel** [comment]
bot_skip

**Comment by sivel** [comment]
Ok, I think I have all the logic fixed in my correlation code. Ready for review.

**Comment by sivel** [comment]
These are now all changelogs which do not have a core component relating to the commits associated with the changelog fragment.

**Comment by sivel** [comment]
To get a list of files deleted in this PR from the CLI:

`git diff-tree --no-commit-id --name-only -r 5c7746e`

Use the attached `changelog.json.txt` to retrieve the associated changelogs.

**Comment by felixfontein** [comment]
To make it easier to find all these PRs: #68565 #68567 #68570 #68618

**Comment by felixfontein** [comment]
@sivel some more fragments which can probably go:
```
39295-grafana_dashboard.yml
51595-adds-win32_diskdrive-object-to-win_disk_facts.yaml
56033-win_iis_webapplication-add-authentication-options.yml
56966-win_format-allocation-unit-size.yml
58225-win_partition-maximum-partition-size.yml
61227-win_iis_webapplication-apppool-change.yml
61227-win_iis_webapplication-apppool-change.yml
61570-netcli-put-get.yaml
62218-fix-to-entrust-api.yml
63418-docker_node_info-errors.yml
63565-postgresql_user_allow_user_name_with_dots.yml
64559-hcloud-inventory-missing-compose-variables.yaml
64585-mysql_dont_mask_mysql_connect_errors_from_modules.yml
64954_virtualization_podman.yml
65138-Windows_Multidomain_support.yml
netbox-add-cache.yaml
vmware_httpapi_fix.yml
vmware-module_fragments-group.yml
win_become-shared-token.yaml
win_command-encoding.yaml
win_credential-wildcard.yaml
win_disk_facts-Set-output-array-order-by-disk-number.yml
win_disk_facts-Set-output-array-order-by-disk-number.yml
win_format-Idem-not-working-if-file-exist-but-same-fs.yml
win_unzip-paths.yaml
```

**Pull request merged**
