### PR TITLE
VMware: Refactor vmware_host_facts

### LINKED ISSUE #39265: vmware_host_facts: 'NoneType' object has no attribute 'summary'
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_host_facts

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /Users/phemmer/git/c14n-platform/ansible.cfg
  configured module search path = [u'/Users/phemmer/git/c14n-platform/library']
  ansible python module location = /Users/phemmer/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /Users/phemmer/ansible-2.5/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

```

##### CONFIGURATION

```
CACHE_PLUGIN_CONNECTION(/Users/phemmer/git/c14n-platform/ansible.cfg) = /tmp/ansible-cache
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/phemmer/git/c14n-platform/ansible.cfg) = [u'/Users/phemmer/git/c14n-platform/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/Users/phemmer/git/c14n-platform/ansible.cfg) = ['profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/Users/phemmer/git/c14n-platform/ansible.cfg) = [u'/Users/phemmer/git/c14n-platform/filter_plugins']
DEFAULT_FORKS(/Users/phemmer/git/c14n-platform/ansible.cfg) = 10
DEFAULT_HOST_LIST(/Users/phemmer/git/c14n-platform/ansible.cfg) = [u'/Users/phemmer/git/c14n-platform/localhost.ini']
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/phemmer/git/c14n-platform/ansible.cfg) = [u'/Users/phemmer/git/c14n-platform/lookup_plugins']
DEFAULT_MODULE_PATH(/Users/phemmer/git/c14n-platform/ansible.cfg) = [u'/Users/phemmer/git/c14n-platform/library']
DEFAULT_ROLES_PATH(/Users/phemmer/git/c14n-platform/ansible.cfg) = [u'/Users/phemmer/git/c14n-platform/roles']
DEFAULT_VARS_PLUGIN_PATH(/Users/phemmer/git/c14n-platform/ansible.cfg) = [u'/Users/phemmer/git/c14n-platform/vars_plugins']
RETRY_FILES_ENABLED(/Users/phemmer/git/c14n-platform/ansible.cfg) = False
```

##### OS / ENVIRONMENT

OS-X 10.12.6
vSphere 6.5

##### SUMMARY

Attempting to use the `vmware_host_facts` module errors with `AttributeError: 'NoneType' object has no attribute 'summary'`

##### STEPS TO REPRODUCE

```yaml
    vmware_host_facts:
      hostname: '{{vsphere_host}}'
      validate_certs: false
      username: '{{vsphere_user}}'
      password: '{{vsphere_password}}'
```

##### EXPECTED RESULTS

no error

##### ACTUAL RESULTS

```
Using module file /Users/phemmer/ansible-2.5/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_host_facts.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: phemmer
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/phemmer/.ansible/tmp/ansible-tmp-1524622902.49-163489786567676 `" && echo ansible-tmp-1524622902.49-163489786567676="` echo /Users/phemmer/.ansible/tmp/ansible-tmp-1524622902.49-163489786567676 `" ) && sleep 0'
<127.0.0.1> PUT /Users/phemmer/.ansible/tmp/ansible-local-98035IJ9ktm/tmpfKLeea TO /Users/phemmer/.ansible/tmp/ansible-tmp-1524622902.49-163489786567676/vmware_host_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/phemmer/.ansible/tmp/ansible-tmp-1524622902.49-163489786567676/ /Users/phemmer/.ansible/tmp/ansible-tmp-1524622902.49-163489786567676/vmware_host_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/phemmer/ansible-2.5/bin/python /Users/phemmer/.ansible/tmp/ansible-tmp-1524622902.49-163489786567676/vmware_host_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/phemmer/.ansible/tmp/ansible-tmp-1524622902.49-163489786567676/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py", line 155, in <module>
    main()
  File "/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py", line 150, in main
    data = all_facts(content)
  File "/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py", line 133, in all_facts
    ansible_facts.update(get_cpu_facts(host))
  File "/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py", line 60, in get_cpu_facts
    'ansible_processor': host.summary.hardware.cpuModel,
AttributeError: 'NoneType' object has no attribute 'summary'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py\", line 155, in <module>\n    main()\n  File \"/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py\", line 150, in main\n    data = all_facts(content)\n  File \"/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py\", line 133, in all_facts\n    ansible_facts.update(get_cpu_facts(host))\n  File \"/var/folders/xk/jhvsfjg14zqfgtwvm0kpsy61p_63g5/T/ansible_t2xrmq/ansible_module_vmware_host_facts.py\", line 60, in get_cpu_facts\n    'ansible_processor': host.summary.hardware.cpuModel,\nAttributeError: 'NoneType' object has no attribute 'summary'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* Updated documentation
* Error handling in find_obj
* Updated return facts example

Fixes: #39265

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/vmware.py
lib/ansible/modules/cloud/vmware/vmware_host_facts.py

##### ANSIBLE VERSION

```
2.6devel
```

### CODE REVIEW

**Comment by phemmer** [comment]
So I no longer get the the `object has no attribute` error, but I now get:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find host system."}
```

I am running this against vCenter, which according to the updated module should give me the first host.

**Comment by Akasurde** [comment]
@phemmer Yes, according to update it should return the first host from the given vCenter connection. I am sure why it is not getting host system objects from your vCenter (whereas it is working on mine). Could you please check if there are any ESXi host system(s) in the given vCenter ? If there are any, try getting facts of one of the host system with respective username and password.

**Comment by phemmer** [comment]
Our network firewall doesn't allow me to contact the ESXi hosts directly, so I can't do that. However I wrote up some quick python code to test, and it works fine:

```
>>> service_instance = connect.SmartConnectNoSSL(...)
>>> content = service_instance.RetrieveContent()
>>> cv = content.viewManager.CreateContainerView(content.rootFolder, [vim.HostSystem], True)
>>> print cv.view[0].name
wfc2esx01.chewy.local
```

**Comment by phemmer** [comment]
Nevermind, i'm an idiot. When I tested with the python code, I was using my personal credentials. Ansible is using dedicated credentials, which apparently doesn't have permission to list hosts. Sorry about that. It works fine :-)

**Comment by Akasurde** [comment]
@phemmer Do you think we can merge this with your settings? 
needs_info

**Comment by Akasurde** [comment]
@pdellaert @dericcrago Could you please review this ?

**Comment by phemmer** [comment]
> Do you think we can merge this with your settings?

My settings?

**Comment by Akasurde** [comment]
I mean your setup and testing.

**Comment by phemmer** [comment]
Oh, yes. This solves the issue I was experiencing. So for me, it's good to merge.

**Comment by Akasurde** [comment]
@woshihaoren Could you please review this ?

**Review by pdellaert — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
rebuild_merge

**Comment by Akasurde** [comment]
@pdellaert Thanks for the review. @phemmer Thanks for testing this PR.

**Pull request merged**
