### PR TITLE
Implement docker support for synchronize module.

### PR DESCRIPTION
**Pull request by Yannig**
##### ISSUE TYPE

Feature Pull Request
##### COMPONENT NAME

action plugin for module synchronize: support for docker connection
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [ ]
```
##### SUMMARY

This pull request implements synchronize support on container type connection

You can take a look at https://github.com/ansible/ansible-container/issues/226 or https://github.com/ansible/ansible/issues/16306 for more details.

Before:

```
fatal: [robert]: FAILED! => {"changed": false, "failed": true, "msg": "synchronize uses rsync to function. rsync needs to connect to the remote host via ssh or a direct filesystem copy. This remote host is being accessed via docker instead so it cannot work."}
```

After:

```
ansible -i hosts -m synchronize -a "src=/tmp/test dest=/tmp/test" robert
robert | SUCCESS => {
    "changed": false, 
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsh='docker exec -i' --out-format='<<CHANGED>>%i %n%L' \"/tmp/test\" \"robert:/tmp/test\"", 
    "msg": "", 
    "rc": 0, 
    "stdout_lines": []
}
```

Note : you need rsync installation on your docker container.

### CODE REVIEW

**Comment by Yannig** [comment]
@amenonsen any feedback regarding this PR?

**Comment by chouseknecht** [comment]
This is working well in Ansible Container testing, and we really, really need it. Merging.

**Comment by Yannig** [comment]
Great :)

**Comment by omgjlk** [comment]
Playing with this, it does not work if you do not specify a user. What happens is that the rsync execution gets created with a literal `-u None`:

```
            "rsync_opts": [
                "--rsh='/usr/bin/docker exec -u None -i'"
            ],
```

Which is because https://github.com/ansible/ansible/pull/18145/files#diff-b6aae93451e66b991ccbd1b9e1ababb0R357 doesn't protect against `user` being None, which is the instantiated value. Setting a user via `ansible_user` works around this, but makes it awkward if trying to make a task that works with both `docker` and `ssh` connections.

**Comment by Yannig** [comment]
Got it. I'll submit a patch during this week to fix this.

**Comment by omgjlk** [comment]
@Yannig I've already done that, and it's been merged.

**Comment by Yannig** [comment]
Cool :)

**Pull request merged**
