### PR TITLE
Adding ec2-related module example to examples/playbooks

### PR DESCRIPTION
**Pull request by lwade**

### CODE REVIEW

**Comment by lwade** [comment]
Removed the merge, whoops.

**Comment by mpdehaan** [comment]
What do you mean by removed the merge?

Diff looks good to me.  Did you mean removed in previous merge?

In any event, thanks, just let me know and we'll apply this.

**Comment by lwade** [comment]
Yeah, a previous commit I didn't want in this pull request (removed it).  This is good to go now :)

**Comment by mpdehaan** [comment]
Great, thanks, glad to have this in there.

**Pull request merged**
