### PR TITLE
ssh port not working as the if clause is wrong

### PR DESCRIPTION
**Pull request by toshywoshy**
The ssh port always results in port 22 as the if clause is never executed, this means that hosts on non-standard ssh port cannot be accessed

### CODE REVIEW

**Comment by bcoca** [comment]
That sets the port to None, i believe the issue is elsewhere setting the connection port to 22 always.

**Comment by toshywoshy** [comment]
I think I found it now : If the remote_port is set in ansible.cfg, this overrides all other settings in the original version and only port 22 can be used, if no remote port the code works
I my opinion and given that the documentation and backward compatibility should allow a general port to be defined in ansible.cfg and override the port if this port is 'None' on the specific host level
As per documentation it should be possible to set a general remote_port and set a specific host port, the patch allows the traditional and new options

**Comment by bcoca** [comment]
The patch just does this:

```
'Port=None'
```

**Comment by halberom** [comment]
probably related to #11616

**Comment by bcoca** [comment]
closing this in favor of #11616

**Pull request closed without merging**
