### PR TITLE
nmcli: implement vlan connections

### LINKED ISSUE #2045: nmcli: Creating VLANs doesn't work on latest centos
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nmcli
##### ANSIBLE VERSION

```
# latest head of 2016-04-16
ansible 2.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

`CentOS Linux release 7.2.1511 (Core)`
##### SUMMARY

Adding VLANs not working
##### STEPS TO REPRODUCE

```
- name: Configure VLANs
  nmcli: type=vlan conn_name="name" ip4="192.168.2.1/16" vlanid="13" ifname="enp0s1" autoconnect=yes state=present
```
##### EXPECTED RESULTS

OK
##### ACTUAL RESULTS

Output:

``` bash
changed: [myserver] => (item={u'conn_name': u'name', u'vlanid': u'13', u'ip4': u'192.168.2.1/16'}) =>
```

``` json
{
  "stderr": "Usage: nmcli [OPTIONS] OBJECT { COMMAND | help }\n\nOPTIONS\n  -t[erse]                                   terse output\n  -p[retty]                                  pretty output\n  -m[ode] tabular|multiline                  output mode\n  -f[ields] <field1,field2,...>|all|common   specify fields to output\n  -e[scape] yes|no                           escape columns separators in values\n  -n[ocheck]                                 don't check nmcli and NetworkManager versions\n  -a[sk]                                     ask for missing parameters\n  -w[ait] <seconds>                          set timeout waiting for finishing operations\n  -v[ersion]                                 show program version\n  -h[elp]                                    print this help\n\nOBJECT\n  g[eneral]       NetworkManager's general status and operations\n  n[etworking]    overall networking control\n  r[adio]         NetworkManager radio switches\n  c[onnection]    NetworkManager's connections\n  d[evice]        devices managed by NetworkManager\n  a[gent]         NetworkManager secret agent or polkit agent\n\n",
  "state": "present",
  "item": {
    "vlanid": "13",
    "ip4": "192.168.2.1\/16",
    "conn_name": "name"
  },
  "invocation": {
    "module_name": "nmcli",
    "module_args": {
      "vlanid": "13",
      "vlandev": null,
      "updelay": null,
      "type": "vlan",
      "stp": "yes",
      "state": "present",
      "slavepriority": "32",
      "priority": "128",
      "mtu": null,
      "mode": "balance-rr",
      "miimon": null,
      "maxage": "20",
      "master": null,
      "mac": null,
      "ip6": null,
      "ip4": "192.168.2.1\/16",
      "ingress": null,
      "ifname": "enp0s1",
      "hellotime": "2",
      "gw6": null,
      "gw4": null,
      "forwarddelay": "15",
      "flags": null,
      "egress": null,
      "downdelay": null,
      "dns6": null,
      "dns4": null,
      "conn_name": "name",
      "autoconnect": "yes",
      "arp_ip_target": null,
      "arp_interval": null,
      "ageingtime": "300"
    }
  },
  "conn_name": "name",
  "changed": true,
  "Connection": "Connection store of Type vlan is being added"
}
```

### PR DESCRIPTION
**Pull request by powo**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

nmcli

##### ANSIBLE VERSION

```
ansible 2.2.0.0

```

##### SUMMARY

Fixes [#2045](https://github.com/ansible/ansible-modules-extras/issues/2045) (at least partially) ... documentation of nmcli module states parameters for creating vlan interfaces but it hasn't been implemented yet.

TODO / still open: 

- repeated execution always reports "changed", and would apply `nmcli con mod ...` even if nothing needs to be changed

### CODE REVIEW

**Comment by powo** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3686

**Comment by gundalow** [comment]
@alcamie101 What are your thoughts on this?

**Comment by gundalow** [comment]
Hi,
A number of files have been git moved from `modules/network` to `modules/net_tools`, which has effected this PR. Please rebase this PR to pull in that change.

**Comment by powo** [comment]
Oh :-( ... looks like the attempt to rebase screwed something up ... any help is appreciated

**Comment by gundalow** [comment]
@powo Not the first, and not the last person to hit this.

Backup you change (outside of your gitrepo) then have a look at docs.ansible.com/ansible/dev_guide/developing_rebasing.html

**Comment by jctanner** [comment]
bot_skip

**Comment by Akasurde** [comment]
@powo Are you still working on this ? If not, let me know I will take over this PR.

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible/ansible/pull/35343 

@powo Thanks for your interest and contribution.

**Pull request closed without merging**
