### PR TITLE
Allow update certificates with same alias

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
The current module checks if the alias already exists in the keystore and, if true, doesn't import the certificate. In some cases we might want to update an existing certificate with the same alias.
This change provides the functionality to check if the to-be-imported certificate is the same as the already existing in the keystore comparing the SHA1 fingerprint.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
modules/system/java_cert.py

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```

### CODE REVIEW

**Comment by jctanner** [comment]
cc @haad @alxgu

**Comment by haad** [comment]
lgtm shipit

**Comment by haad** [comment]
@alxgu can you check this ?

**Comment by haad** [comment]
shipit

**Comment by haad** [comment]
bot_status

**Comment by hudecof** [comment]
I really missing this feature. I'm using it to import LE certificate for  java based software.
+1

**Comment by marcjay** [comment]
What's holding up this PR now? It looks good to me?

**Comment by haad** [comment]
shipit

**Comment by haad** [comment]
we need a confirmation from one other maintainer here to merge it into release.

**Comment by marcjay** [comment]
@haad Great, thanks, fingers crossed another maintainer stops by soon... 🤞

**Comment by marcjay** [comment]
Is there a way we can poke another maintainer to take a look @haad ? Would love to see this merged

**Comment by alxgu** [comment]
shipit

**Pull request closed without merging**
