### PR TITLE
Ericsson add feature

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/network/eric_eccli/eric_eccli.py
lib/ansible/modules/network/eric_eccli/eric_eccli_command.py
lib/ansible/plugins/action/eric_eccli_command.py
lib/ansible/plugins/cliconf/eric_eccli.py
lib/ansible/plugins/doc_fragments/eric_eccli.py
lib/ansible/plugins/terminal/eric_eccli.py
test/units/modules/network/eric_eccli

##### ADDITIONAL INFORMATION

Running  commands to configure and manage ERICSSON device by ansible.  

```paste below

```

### CODE REVIEW

**Comment by Cheng912** [comment]
@NilashishC @Qalthos @ganeshrn @gdpak @justjais @rcarrillocruz @trishnaguha 
Hi, Dear module maintainer, although all checks have finished and Details display 0 failed and 0 errors!, but why is fail? I'm very confused with this condition. Cloud you eliminate my confusion? Thanks.

**Comment by samdoran** [comment]
Setting options to an empty string exposed a bug in our module validation code. I have a PR to fix that but until it is merged, here are sanity test failures:

```
ERROR: Found 18 validate-modules issue(s) which need to be resolved:
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E305 DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got 'Ericsson IPOS OAM team (@cheng.you@ericsson.com)'
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E322 Argument 'authorize' is listed in the argument_spec, but not documented in the module documentation
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E322 Argument 'provider' is listed in the argument_spec, but not documented in the module documentation
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E331 Argument 'options' in argument_spec['provider'] must be a dictionary/hash when used
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'authorize' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'commands' in argument_spec defines type as 'list' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'interval' in argument_spec defines type as 'int' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'port' in argument_spec defines type as 'int' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'provider' in argument_spec defines type as 'dict' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'retries' in argument_spec defines type as 'int' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'ssh_keyfile' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'timeout' in argument_spec defines type as 'int' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E337 Argument 'wait_for' in argument_spec defines type as 'list' but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E338 Argument 'auth_pass' in argument_spec uses default type ('str') but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E338 Argument 'host' in argument_spec uses default type ('str') but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E338 Argument 'match' in argument_spec uses default type ('str') but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E338 Argument 'password' in argument_spec uses default type ('str') but documentation doesn't define type
ERROR: lib/ansible/modules/network/eric_eccli/eric_eccli_command.py:0:0: E338 Argument 'username' in argument_spec uses default type ('str') but documentation doesn't define type
```

**Comment by mattclay** [comment]
This PR appears to be a duplicate of https://github.com/ansible/ansible/pull/57353

**Comment by mattclay** [comment]
Closing since this PR was opened by a now deleted user.

**Pull request closed without merging**
