### PR TITLE
Cloudfront.py module

### PR DESCRIPTION
**Pull request by wilvk**
##### SUMMARY

This module allows the following cloudfront actions:

- create distribution
- update distribution
- delete distribution
- duplicate distribution
- validate distribution
- create streaming distribution
- update streaming distribution
- delete streaming distribution
- duplicate distribution
- validate distribution
- create origin access identity
- delete origin access identity
- update origin access identity
- create a batch of invalidations
- tag a resource
- untag a resource
- generate a pre-signed cloudfront url from a PEM private key

I saw this as a gap item as the cloudfront_facts.py module already exists but not cloudfront.py.

Each action has a set of valid parameters that an be used in conjunction. These are illustrated in the examples section.

This PR also renames the class for cloudfront_facts.py as CloudfrontFactsManager as CloudfrontManager is more appropriate for this module.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

./lib/ansible/modules/cloud/amazon/cloudfront.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 652b4d220a) last updated 2017/04/30 23:12:22 (GMT +1100)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by willthames — CHANGES_REQUESTED** [review]
`create_streaming_distribution` and `delete_streaming_distribution` and the other similarly named parameters are of concern - we should be stating the desired state of streaming_distribution (`present` or `absent`).

**Comment by willthames** [comment]
This feels like it should probably be multiple modules.

**Comment by willthames** [comment]
The use of  `tag_resource` and `untag_resource` is problematic - just provide a `tags:` parameter and update tags accordingly

**Comment by wilvk** [comment]
Thanks for the feedback @willthames ! I'll get onto those changes:
- consolidate `tag` and `untag` into just `tags:`
- use `status` parameter instead of `create_distribution` `delete_distribution` `update_distribution` `duplicate_distribution` `validate_distribution` etc.
- could possibly be multiple modules but not sure how it should be split - distribution and streaming_distribution have dependencies/common methods. Am open to suggestions, however..

**Comment by wilvk** [comment]
@willthames closing this PR and have migrated content to #24292 as I made a dog's breakfast of this one with the rebase and comment history.

**Pull request closed without merging**
