### PR TITLE
Make FreeIPA inventory work

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
hostgroup details are moved to hostgroup_show command output. Adjust FreeIPA inventory as per change.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
contrib/inventory/freeipa.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by alikins** [comment]
@Akasurde 

Patch looks good to me, but wanted to verify if this could cause compat issues.

> hostgroup details are moved to hostgroup_show command output. Adjust FreeIPA inventory as per change.

is hostgroup_show new freeipa API?  Would it break against older versions?

If the freeipa version matters:
   - I'm not sure it matters if it requires a new version, as it isn't clear to me what versions of freeipa the inventory script is expected to work with.
  - I also have no idea what versions are common

If the freeipa version doesnt matter, LGTM.

**Comment by Akasurde** [comment]
@alikins 

`hostgroup_show` is not new API. I have tested this API with latest 4.5 and 4.3. I need to check with 3.* versions.

I will test it with FreeIPA 3.* version. If there are any changes required, I will add version check in this script.

**Comment by Akasurde** [comment]
@alikins 

Here is output for IPA version 3.0 

```
[root@ipaserver01-v30 ~]# ipa ping
------------------------------------------
IPA server version 3.0.0. API version 2.49
------------------------------------------
[root@ipaserver01-v30 ~]# python freeipa.py --list
{
 "_meta": {
  "hostvars": {
   "sample1.testrelm.test": {},
   "sample2.testrelm.test": {}
  }
 },
 "sample1": {
  "hosts": [
   "sample1.testrelm.test"
  ]
 },
 "sample2": {
  "hosts": [
   "sample2.testrelm.test",
   "sample1.testrelm.test"
  ]
 }
}
```

Here is output for IPA version 4.5 (Latest) (Fedora 25)

```
[root@ipaserver01-v45 ~]# ipa ping
-------------------------------------------
IPA server version 4.5.0. API version 2.227
-------------------------------------------
[root@ipaserver01-v45 ~]# python freeipa.py --list
{
 "_meta": {
  "hostvars": {
   "ipaserver01-v45.testrelm.test": {},
   "ipaserver02-v45.testrelm.test": {}
  }
 },
 "ipaservers": {
  "hosts": [
   "ipaserver01-v45.testrelm.test",
   "ipaserver02-v45.testrelm.test"
  ]
 }
}
```

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@alikins Do I need to anything else to get this PR rolling ?

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@alikins Do I need to anything to get this PR rolling?

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@alikins Ping for review.

**Comment by Akasurde** [comment]
@alikins Do I need to do anything to get this PR rolling ?

**Comment by Akasurde** [comment]
@Nosmoht Could you please review this PR?

**Comment by calfonso** [comment]
rebuild_merge

**Comment by Akasurde** [comment]
@calfonso Thanks for review and merge.

**Comment by rgroten** [comment]
Hey @Akasurde, I found we can achieve the same result to fix hostgroup membership in freeipa 4.4 by adding a parameter to hostgroup_list(**all=True**)

This method runs about 4X quicker in my test

```
[rgroten@rgroten-fed ansible (master)] $ diff scripts/ansible-list-hosts.py scripts/ansible-list-hosts-tmp.py
7a8
> from distutils.version import StrictVersion
36c37,38
<     result = api.Command.hostgroup_find(all=True)['result']
---
>     ipa_version = api.Command.env()['result']['version']
>     result = api.Command.hostgroup_find()['result']
41a44,47
>
>         if StrictVersion(ipa_version) >= StrictVersion('4.0.0'):
>             hostgroup_name = hostgroup['cn'][0]
>             hostgroup = api.Command.hostgroup_show(hostgroup_name)['result']

[rgroten@rgroten-fed ansible (master)] $ time scripts/ansible-list-hosts-tmp.py --list

real    0m17.543s
user    0m3.171s
sys     0m1.112s
[rgroten@rgroten-fed ansible (master)] $ time scripts/ansible-list-hosts.py --list

real    0m4.173s
user    0m2.410s
sys     0m0.097s
```


I don't know if **all=True** would work on ipa version 3.x, it works on 4.2 and 4.4 for sure.

**Comment by Akasurde** [comment]
@rgroten Cool. Can you please open a PR with this change with IPA version check?

**Comment by rgroten** [comment]
Sure thing @Akasurde thanks

**Pull request merged**
