### PR TITLE
minor fixes to apt

### LINKED ISSUE #22124: Error when separate apt tasks
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

No changes 

##### OS / ENVIRONMENT

Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-59-generic x86_64)

Both hosts and servers 

##### SUMMARY

Running 3 separate  atp actions failes on the third 

##### STEPS TO REPRODUCE

```yaml
```

https://gist.github.com/varazir/ba960bd117b9ee0e37e7810d3bacb10f

##### EXPECTED RESULTS

To remove unused dependency packages, 
Merging the 3 tasks it works fine. 

##### ACTUAL RESULTS

See Gist 

```

```

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

apt
##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

fixes #22124

Alternate to #22149, fixes a couple of underlying issues with the options not being validated correctly

### CODE REVIEW

**Review by resmo — APPROVED** [review]

**Comment by snowsky** [comment]
@resmo try this:
Use this playbook and then run "apt-get autoremove":
```
- hosts: localhost
  tasks:
    - apt:
        autoremove: yes
```
It shows no change:
```
PLAY RECAP ************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
Then the command 'apt-get autoremove' still show some packages:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  linux-headers-4.4.0-59 linux-headers-4.4.0-59-generic linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic linux-image-4.4.0-34-generic linux-image-4.4.0-59-generic linux-image-4.4.0-62-generic
0 upgraded, 0 newly installed, 7 to remove and 24 not upgraded.
After this operation, 341 MB disk space will be freed.
Do you want to continue? [Y/n]
```

**Comment by snowsky** [comment]
I see where the problem is now. Will put up a PR soon.

**Comment by resmo** [comment]
@snowsky ok, let me know when ready

**Comment by snowsky** [comment]
@resmo I created the other PR to address this, #22232, please review it.

**Pull request merged**
