### PR TITLE
Allow setup of docker remote connections

### PR DESCRIPTION
**Pull request by ThomasSteinbach**
This PR replaces #13356, because I switched to a new branch. Sorry for inconvenience.

This pull request is a proposal for solving issue #13294. Maybe the changes in the `play_context.py` are not compliant to the current standard of this file and should be seen as a proposal. My intention was to introduce the ability to set the connection command and additional connection arguments independent of the connection type (ssh, local, docker, ...). Besides solving issue #13294 the changes within the `connection/docker.py` show the use of the two new variables in the play_context.

I hope those changes will be merged in the one or another form. I rely hardly on them and currently there is no other possibility to deploy playbooks to remote Docker daemons. Here an example how to use the Docker connection remotely:

_inventory_

```
mycontainer ansible_connection=docker ansible_connections_args="--tlsverify --tlscacert=/path/to/ca.pem --tlscert=/path/to/client-cert.pem --tlskey=/path/to/client-key.pem -H=tcp://myserver.org:4243"
```

### CODE REVIEW

**Comment by abadger** [comment]
@bcoca, I see you commented on the feature idea ticket.  Did you want to evaluate this pull request?

**Comment by bcoca** [comment]
i might want to fold ansible_ssh_args to ansible_connection args, like we do with host and user.

**Comment by ThomasSteinbach** [comment]
So what should I do that this PR could be shipped? Should I either use the `ansible_ssh_args` within the docker connection, so that it would be commonly renamed to another name later? Or should I rename the `ansible_ssh_args` to `ansible_connection_args` in the whole source?

By the way, there is not directly a `ansible_ssh_args` in the source. There are:
- _ssh_args
- ansible_ssh_common_args (internally _ssh_common_args)
- ansible_sftp_extra_args
- ansible_scp_extra_args
- ansible_ssh_extra_args

Which one would you fold with?

**Comment by amenonsen** [comment]
You shouldn't touch ssh_args (not an inventory variable but the configuration file setting, which I believe should be deprecated, but that's another discussion). You should also not touch ansible_{ssh,scp,sftp}_extra_args. I would not object to changing ansible_ssh_common_args to ansible_connection_args, though that change would need to be explained in the documentation. I also wonder if ansible_connection_options isn't a better name given the widening of the scope, but I don't have a strong preference.

**Comment by bcoca** [comment]
agreed, i was thinking of ansible_connection_args/ansible_connection_extra_args to fold in the ssh args if present, but not sure at this point. Others would prefer to not have a global in these cases and stick to the connection specific ones. ansible_host would work for the remote host, but other args might requrie an ansible_docker_x which the connection plugin can request (we did this for winrm).

Since i scheduled this for 2.1 we have more time to figure out the optimal state, so I might merge this in 'as is' and we can modify before 2.1 to whatever we end up deciding. For now most of us in core are concentrating on 2.0 and I don't want to distract them with future features right now (but will soon).

**Comment by ThomasSteinbach** [comment]
So is this PR ready for beeing shipped? Or is there anything I should change?

**Comment by Yannig** [comment]
This PR is quite interesting. Any chance to get it merged?

**Comment by ThomasSteinbach** [comment]
Hi @Yannig , maybe you want to take part on the discussion [Docker Connector for use with remote hosts](https://groups.google.com/forum/#!topic/ansible-project/u9-GbZ43HUA) to see this or a better PR merged?

And maybe @smashwilson , @dusdanig , @berlic too, as you were active participants to the docker modules in the past days.

**Comment by ThomasSteinbach** [comment]
Hi everybody,
I spent again some effort into merging the latest ansible/devel state into this PR. Additionally I cleaned up the code for better alignment with the existing _docker.py_ and _play_context.py_ code. So if you compare the code of the PR with the two files from ansible/devel, you will see that it just allows to add additional options to the docker command. For instance the options for a docker remote connection. Here an example:

```
- name: create jenkins container
  docker:
    name: myjenkins
    image: jenkins

- name: add container to inventory
  add_host:
    name: myjenkins
    ansible_connection: docker
    ansible_docker_extra_args: "--tlsverify --tlscacert=/path/to/ca.pem --tlscert=/path/to/client-cert.pem --tlskey=/path/to/client-key.pem -H=tcp://myserver.net:4243"
    ansible_user: jenkins
  changed_when: false

- name: create nescessary directories in /var/jenkins_home
  delegate_to: myjenkins
  file:
    path: "/var/jenkins_home/users/admin"
    state: directory
```

I would like to see the shipment of the PR rather sooner than later, as it is no big change in the behavior of ansible but difficult to keep the PR up to date in the very active code ( _docker.py_ and _play_context.py_). I created the PR in December last year and since then we (my company, friends and myself) are using the feature successfully. However, a lot of bugfixes in the Ansible code itself force me to keep the PR updated with the official ansible/devel branch.

Additionally I would like to update my article [The Marriage of Ansible and Docker](https://bildung.xarif.de/xwiki/bin/Articles/The+Marriage+of+Ansible+and+Docker), as Ansible 2.0 is a big deal in the approach of how to play with Docker together. A lot of people are consulting me regarding the article and ask how to deploy to Docker containers. Everytime I have to stall them with the prospect, that with Ansible 2.x there will be a much cleaner approach to do that. But currently that does not work remotely.

And finally, to partly reveal a secret, it would help me to finish my 'Ansible Contiuous Integration Server' project, which will be released open source soon. It will check roles, then playbooks and then deploy the playbooks in a very easy fashion. I also plan to host a free instance for testing roles and playbooks describing bugs in Ansible, such that you can see which bugfixes are really working and not and also inform when old bugs are introduced again.

(I earlyest can reply to further comments on April, as I will spend the next days on holidays)

**Comment by abadger** [comment]
@ThomasSteinbach Thanks for updating and continuing to poke at this!  @bcoca and I talked about this and decided to merge this in.  We _are_ interested in the generic inventory variable approach but decided we can implement that a little later and deprecate the relevant inventory variables when we do so.

**Comment by ThomasSteinbach** [comment]
Cool, that was quick now - and my easter present :)

**Comment by Yannig** [comment]
Sweet !

**Pull request merged**
