### PR TITLE
explain source of EC2 inventory error

### PR DESCRIPTION
**Pull request by alexlo03**
addresses part of https://github.com/ansible/ansible/issues/10840
@edrozenberg 

I ran into this while creating a more limited IAM role for some users.

Before
RDS: `ERROR: Inventory script (ec2.py) had an execution error: Forbidden`
EC2: `ERROR: Inventory script (ec2.py) had an execution error: Error connecting to AWS backend.
You are not authorized to perform this operation.`
ElastiCache: `ERROR: Inventory script (ec2.py) had an execution error: Forbidden`

After
RDS: `ERROR: Inventory script (ec2.py) had an execution error: ERROR: "Forbidden", while: getting RDS instances`
EC2: `ERROR: Inventory script (ec2.py) had an execution error: ERROR: "Error connecting to AWS backend.
You are not authorized to perform this operation.", while: getting EC2 instances`
ElastiCache: `ERROR: Inventory script (ec2.py) had an execution error: ERROR: "Forbidden", while: getting ElastiCache clusters`

Thanks

### CODE REVIEW

**Comment by alexlo03** [comment]
@bcoca rebased

**Comment by alexlo03** [comment]
Desc updated to include ElastiCache

**Comment by amenonsen** [comment]
@alexlo03 your patch looks reasonable but I just can't get over the punctuation while reading «operation.", while:». Is there any chance you could make this say something like

```
EC2: `ERROR: Inventory script (ec2.py) had an execution error while getting EC2 instances: ERROR: "Error connecting to AWS backend. You are not authorized to perform this operation."
```

or something like that?

**Comment by alexlo03** [comment]
@amenonsen I can reword it but not exactly to your spec.  `ERROR: Inventory script (ec2.py) had an execution error:` is coming from above this module so that colon is coming in.  I could make it
`ERROR: Inventory script (ec2.py) had an execution error: while getting EC2 instances. ERROR: "Error connecting to AWS backend. You are not authorized to perform this operation."`

**Pull request merged**
