### PR TITLE
Updated and improved the documentation (examples)

### PR DESCRIPTION
**Pull request by lwade**
The ec2 module documentation was in a bad way, so this update improves with better examples.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Since you are updating this (FYI), the new way to do things is to put them in EXAMPLES.  This allows easier playbook formatting without having to nest YAML in YAML.

**Comment by mpdehaan** [comment]
another tip/style thing:

As some of these contain pretty long lines, it might be helpful to break this up using:

```
some_module: >
   asdf=foo
   jkl=bar
```

etc

or better:

```
some_module:
    asdf: foo
    jkl: bar
```

**Comment by lwade** [comment]
Ok got it, would you like me to make these changes to modules now? Can this be merged with the aim of updating all the ec2-related modules at a later date?

**Comment by mpdehaan** [comment]
I went ahead and merged this.

Please also note the EXAMPLES syntax is the new preferred way of doing docs in modules, I have yet to replace all previous occurances but is easier than putting playbooks in the DOCUMENTATION yaml itself (since they are also YAML!)

**Pull request merged**
