### PR TITLE
openssl_pkcs12: fix crash due to wrong path used for loading key in check mode

### LINKED ISSUE #56792: openssl_pkcs12 'Error while deserializing key'
##### SUMMARY
After recently upgrading to ansible 2.8 and switching to python3.6 creating a PFX certificate via openssl_pkcs12 module is no longer working.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module: openssl_pkcs12

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /opt/ansible/infrastructure/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/opt/ansible/infrastructure/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/opt/ansible/infrastructure/ansible.cfg) = -F ssh.config -o ControlMaster=auto -o ControlPersist=60s
COMMAND_WARNINGS(/opt/ansible/infrastructure/ansible.cfg) = False
DEFAULT_BECOME(/opt/ansible/infrastructure/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/opt/ansible/infrastructure/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/opt/ansible/infrastructure/ansible.cfg) = root
DEFAULT_FORKS(/opt/ansible/infrastructure/ansible.cfg) = 20
DEFAULT_HOST_LIST(/opt/ansible/infrastructure/ansible.cfg) = ['/opt/ansible/infrastructure/hosts']
DEFAULT_REMOTE_USER(/opt/ansible/infrastructure/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/opt/ansible/infrastructure/ansible.cfg) = ['/opt/ansible/infrastructure/roles']
DEFAULT_SCP_IF_SSH(/opt/ansible/infrastructure/ansible.cfg) = True
DEFAULT_TIMEOUT(/opt/ansible/infrastructure/ansible.cfg) = 60
DISPLAY_SKIPPED_HOSTS(/opt/ansible/infrastructure/ansible.cfg) = False
HOST_KEY_CHECKING(/opt/ansible/infrastructure/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible/infrastructure/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Docker container based on centos, with ansible installed via pip3

##### STEPS TO REPRODUCE

If you take a certificate created with the openssl_certificate module and it's private key created via openssl_key and attempt to generate a PFX certificate via openssl_pkcs12 it fails.

```
- name: Generate PFX certificate
  openssl_pkcs12:
    action: export
    path:                  "certs/test.pfx"
    friendly_name:         "test"
    privatekey_path:       "keys/test.key"
    privatekey_passphrase: "secret"
    certificate_path:      "certs/test.crt"
    ca_certificates:       "certs/ca.crt"
    state: present
```

##### EXPECTED RESULTS

Generate a PFX certificate containing the cert specified.  This was working on ansible 2.7.10 and python2.  

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_openssl_pkcs12_payload_xtwamtua/__main__.py", line 411, in main
    if not pkcs12.check(module, perms_required=False) or module.params['force']:
  File "/tmp/ansible_openssl_pkcs12_payload_xtwamtua/__main__.py", line 284, in check
    return _check_pkey_passphrase()
  File "/tmp/ansible_openssl_pkcs12_payload_xtwamtua/__main__.py", line 231, in _check_pkey_passphrase
    self.privatekey_passphrase)
  File "/tmp/ansible_openssl_pkcs12_payload_xtwamtua/ansible_openssl_pkcs12_payload.zip/ansible/module_utils/crypto.py", line 149, in load_privatekey
    raise OpenSSLObjectError('Error while deserializing key: {0}'.format(e))

failed: [127.0.0.1] (item={'key': 'ad02', 'value': {'cn': 'ad02.red.loc', 'dns': 'ad02.red.loc', 'key_usage': 'Digital Signature', 'extended_key_usage': 'TLS Web Server Authentication', 'pfx': 'true', 'passphrase': 'true'}}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "export",
            "attributes": null,
            "backup": false,
            "ca_certificates": "/opt/ansible/certrepo/ca/ca.crt",
            "certificate_path": "/opt/ansible/certrepo/red.loc/certs/ad02.crt",
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "friendly_name": "ad02",
            "group": null,
            "iter_size": 2048,
            "maciter_size": 1,
            "mode": "0400",
            "other_certificates": [
                "/opt/ansible/certrepo/ca/ca.crt"
            ],
            "owner": null,
            "passphrase": null,
            "path": "/opt/ansible/certrepo/red.loc/certs/ad02.pfx",
            "privatekey_passphrase": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "privatekey_path": "/opt/ansible/certrepo/red.loc/keys/ad02.key",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "unsafe_writes": null
        }
    },
    "item": {
        "key": "ad02",
        "value": {
            "cn": "ad02.red.loc",
            "dns": "ad02.red.loc",
            "extended_key_usage": "TLS Web Server Authentication",
            "key_usage": "Digital Signature",
            "passphrase": "true",
            "pfx": "true"
        }
    },
    "msg": "Error while deserializing key: [('PEM routines', 'get_name', 'no start line')]"
}
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #56792.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssl_pkcs12

### CODE REVIEW

**Comment by Shaps** [comment]
shipit

**Review by resmo — APPROVED** [review]
shipit

**Comment by resmo** [comment]
manual merge due to changelog fragment blocks automerge.

**Comment by felixfontein** [comment]
@Shaps @resmo thanks for reviewing and merging!

**Comment by finnje** [comment]
@felixfontein thanks for the quick turnaround!  Works like a champ now :)

**Pull request merged**
