### PR TITLE
Add better error messages and checking to known_hosts

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Add better error messages to explain why things are failing.

Add integration tests to test some failure scenarios.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
`known_hosts.py`

##### ANSIBLE VERSION

```
2.6
```

### CODE REVIEW

**Comment by mcv21** [comment]
Do we really need to specifically handle one particular form of incorrect user input?

**Comment by samdoran** [comment]
I spent a few hours fighting with this module the other day due to passing in a comma separated list in the `name` field, so I figured it would be better to explain why it's failing and save others some pain. The key will accept the comma separated list of names, but `ssh-keygen` only accepts a single name when validating. And it's failure give no indication that that is the problem.

**Comment by mcv21** [comment]
fair enough!

**Comment by samdoran** [comment]
rebuild_merge

**Pull request merged**
