### PR TITLE
Apt force

### PR DESCRIPTION
**Pull request by jeremysmitherman**
Per request in https://github.com/ansible/ansible/pull/533?_nid=60321013#issuecomment-6810704 I've redone these changes in a feature branch without the merges in the history.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not an expert in apt parameters (mostly use CentOS myself), please first resubmit this as a single commit and then bring this up on the mailing list so folks can review and I can see whether some of the other Debian folks are ok with changes, then you can resubmit and I'll take it.

Thanks!

**Comment by mpdehaan** [comment]
Also please do not assign booleans in function calls like this:

force=force == 'yes'

makes things hard to read.

**Comment by mpdehaan** [comment]
I see you've fixed that one above, so it looks like a case of just having the previous versions in the history and needing to do the squash commit.  Generally we want the history to be good and usually reasonably atomic, so we want to avoid commits with syntax errors in them and so forth too.

I think the main thing I want the list to agree with is the confold stuff, which I'm not qualified to make a decision on.

**Comment by jeremysmitherman** [comment]
I'm not sure about what you are asking about the force-confold.  If you are asking it's purpose it pretty much has to be there or it'll fire up a prompt in cases where updates would overwrite the configuration file.

**Comment by mpdehaan** [comment]
It appears you've just now added it, which is why I'm curious.

I'd still like the list to take a look before I merge this, and the patch still needs to be squashed first.

**Comment by jeremysmitherman** [comment]
Ahh, that's why I was confused.  I didn't add the force-confold, it was already there.

**Pull request closed without merging**
