### PR TITLE
mail: Fix new breakage on python 2.7 (backport)

### LINKED ISSUE #48785: Mail module is failing in ansible 2.7.2
##### SUMMARY
Some weeks ago i saw the version 2.7.0 affected by an issue (#46673)  while using the mail module.
So i downgraded the local ansible to 2.6.5 where it was working fine.
After the backport for the smtp thing was done in 2.7.1, mail was working also.
Today i did an upgrade to 2.7.2 and see another/new smtp issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mail module

##### ANSIBLE VERSION
```
ansible --version
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/.ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]

```

##### CONFIGURATION
(nothing changed - default)
```

```

##### OS / ENVIRONMENT
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```
```
cat /etc/apt/sources.list.d/ansible-ubuntu-ansible-cosmic.list 
deb http://ppa.launchpad.net/ansible/ansible/ubuntu cosmic main
```
##### STEPS TO REPRODUCE
Install the latest version of ansible 2.7.2 from ppa

```
- name: Send mail a user
  local_action:
     module: mail
             host='{{ mail_host }}'
             port='{{ mail_port }}'
             username='{{ admin_mail_username }}'
             password='{{ admin_mail_password }}'
             from="{{ admin_mail_name }} <{{ admin_mail_address }}>"
             to="{{ name }} {{ surname }} <{{ externalmail }}>"
             bcc="<{{ admin_maillist }}>"
             charset="utf-8"
             secure="starttls"
             subject='Account {{ username }}'
             body='{{ lookup('template', './roles/mailtoNewExternalUser/templates/email_template.j2') }}'

```

##### EXPECTED RESULTS
Mail will be send.

##### ACTUAL RESULTS
If fails

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_mail_payload_uUtWub/__main__.py", line 263, in main
    code, smtpmessage = smtp.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 318, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 366, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: timed out

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attach": [], 
            "bcc": [
                "<admins@domain.tld>"
            ], 
            "body": "Hello World", 
            "cc": [], 
            "charset": "utf-8", 
            "from": "Frank Nord <fnord@domain.tld>", 
            "headers": [], 
            "host": "smtp.domain.tld", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 587, 
            "secure": "starttls", 
            "sender": "Frank Nord <fnord@domain.tld>", 
            "subject": "Account User", 
            "subtype": "plain", 
            "timeout": 60, 
            "to": [
                "Some User <suser@domain.tld>"
            ], 
            "username": "fnord"
        }
    }, 
    "msg": "Unable to Connect smtp.domain.tld:587: Connection unexpectedly closed: timed out", 
    "rc": 1
}

```

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Once again the mail module was broken on python 2.7.
This fixes the issue and adds an integration test to avoid future regressions.

This is a backport of #49197 

This fixes #48785

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mail

### CODE REVIEW

**Review by gundalow — APPROVED** [review]
Thank you for adding the integration test

**Comment by mattclay** [comment]
Please wait to open backport PRs until the devel PR has been merged. That way we don't waste CI cycles or review time on PRs that may not be ready yet. Also, it avoids issues where a backport is merged to a stable branch even if it hasn't/won't be merged to devel.

**Comment by dagwieers** [comment]
That is what I assumed, still yesterday I was told I could do it.

**Comment by abadger** [comment]
Merged for 2.7.5.

**Pull request merged**
