### PR TITLE
[docs][2.12] stub out porting guides and point to devel

### PR DESCRIPTION
**Pull request by samccann**
##### SUMMARY

Porting guides only maintained in devel so stub out those in 2.12 and point up to devel.

Part of  #75883
##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs/docsite/rst/porting_guides/porting_guide_2.10.rst
docs/docsite/rst/porting_guides/porting_guide_3.rst
docs/docsite/rst/porting_guides/porting_guide_4.rst
docs/docsite/rst/porting_guides/porting_guides.rst

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ariordan-redhat** [comment]
Should we stub out `core_porting_guides.rst` also?

**Review by ariordan-redhat — COMMENTED** [review]
Do we need to update `core_porting_guides.rst` also?

**Comment by samccann** [comment]
We haven't in the past so I'm inclined to leave it that way for now. It's extra work and we don't get a lot of hits on those at this point, but I could be convinced otherwise. :-) What do you think?

**Review by ariordan-redhat — APPROVED** [review]
Looks good to me

**Pull request merged**
