### PR TITLE
Fix #7711

### LINKED ISSUE #7711: File module fails to make relative symlinks
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 0073b34653) last updated 2014/06/10 02:55:50 (GMT -500)
##### Environment:

Running from OSX 10.7
Remote is Debian stable
##### Summary:

The file module errors on relative links.
##### Steps To Reproduce:

Make /tmp/foo/foo
Try to symlink /tmp/bar/bar to ../foo/foo
##### Expected Results:

For the link to succeed.
##### Actual Results:

```
failed: [default] => {"failed": true, "gid": 1000, "group": "vagrant", "mode": "0777", "owner": "vagrant", "path": "/tmp/bar/bar", "size": 10, "src": "../foo/foo", "state": "link", "uid": 1000}
msg: src file does not exist, use "force=yes" if you really want to create the link: /tmp/bar/foo
```

### PR DESCRIPTION
**Pull request by dmage**
Fix relative symlinks creation in file module.

### CODE REVIEW

**Comment by jimi-c** [comment]
cc @bcoca. If I remember correctly, this is similar to a different proposed fix, which also broke some corner cases (which we need to add integration tests for as well).

**Comment by bcoca** [comment]
I just compiled the list of around 12 tickets that relate to this same
issue, making tests for every case and then we can hopefully close this
issue
​

**Comment by jimi-c** [comment]
@bcoca excellent.

**Comment by mpdehaan** [comment]
Very very very nice.   Let us know the list :)

**Comment by bcoca** [comment]
So here is the list of all symlink related issues I've found, I looked over
all of them and checked against the test cases and only found 2 tests
missing:

1369, 2964, 3203, 3229, 4459, 5004, 5139, 5947, 6182, 6576, 7254, 7515,
7627, 7657, 7711
​

**Comment by jimi-c** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request merged**
