### PR TITLE
ipa_user bugfix: Have krbPasswordExpiration work properly

### LINKED ISSUE #42018: ipa_user: krbpasswordexpiration is not valid in IPA
##### SUMMARY

I recently ran across the need to change the password expiration for the first time, so I decided to use `krbpasswordexpiration` that was added in #32369. 

Well, it turns out we missed something pretty big during the review process: there is no `krbpasswordexpiration` in the FreeIPA API; it is actually `krbprincipalexpiration`.

screen shot 2018-06-27 at 2 30 46 pm

EDIT: FreeIPA, version: 4.5.4

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ipa_user

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel 1401fa74cc) last updated 2018/06/26 16:35:59 (GMT -500)
  config file = None
  configured module search path = ['/Users/fxfitz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/fxfitz/dev/ansible/lib/ansible
  executable location = /Users/fxfitz/.pyenv/versions/3.6.5/bin/ansible
  python version = 3.6.5 (default, May 29 2018, 20:18:53) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- name: Set a password expiration
  ipa_user:
    ipa_host: localhost
    ipa_user: admin
    ipa_pass: super_secret_password
    state: present
    name: mr_awesome
    givenname: Mister
    sn: Awesome
    mail: mister@awesome.com
    password: some_special_password
    krbpasswordexpiration: 20200119235959
```

##### EXPECTED RESULTS

I expected to set the password expiration to 20200119235959.

##### ACTUAL RESULTS

```
fatal: [freeipa]: FAILED! => {"changed": false, "msg": "response user_mod: Unknown option: krbpasswordexpiration"}
```

### PR DESCRIPTION
**Pull request by fxfitz**
##### SUMMARY

`krbPasswordExpiration` was not being set properly in the FreeIPA API.

Fixes #42018 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ipa_user

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (issue_42018_bugfix f8eb2d184c) last updated 2018/06/28 09:12:24 (GMT -500)
  config file = None
  configured module search path = [u'/Users/fxfitz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/fxfitz/dev/ansible/lib/ansible
  executable location = /Users/fxfitz/.pyenv/versions/ansible/bin/ansible
  python version = 2.7.15 (default, May 29 2018, 20:16:38) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### ADDITIONAL INFORMATION

When I was working on this, I found out that by default one cannot modify this attribute.  An permission needs to be created that gives write access to this attribute on a user.

See bug report for more information.

### CODE REVIEW

**Comment by fxfitz** [comment]
Additionally, the `password` and `krbpasswordexpiration` are now mutually exclusive.  This is because whenever one *sets* the password, it immediately expires the password.  So to get the desired outcome, I felt like it was best to ensure password/password_expiration were used separately.

**Comment by fxfitz** [comment]
Ideally we should get this fix backported to the next 2.5.x release.

**Review by achinthagunasekara — APPROVED** [review]

**Comment by fxfitz** [comment]
@Akasurde Any thoughts on this one?

**Comment by Akasurde** [comment]
@fxfitz Could you please paste me the scenario where I can test this ? As I am able to set krbpasswordexpiration with and without this patch. Let me know if I am missing anything. 
I am using FreeIPA 4.6.4. 

Also, on FreeIPA 4.5.3, this throws a error - 

```
"msg": "response user_add: Unknown option: krbpasswordexpiration"
```

**Comment by fxfitz** [comment]
@Akasurde I'm experiencing this on FreeIPA 4.5.4; I don't have a test setup ready to try with 4.6.x.

I put *most* of the information on how to reproduce in https://github.com/ansible/ansible/issues/42018, but to summarize, this task triggers the following response:

```
- name: Set a password expiration
  ipa_user:
    ipa_host: localhost
    ipa_user: admin
    ipa_pass: super_secret_password
    state: present
    name: mr_awesome
    givenname: Mister
    sn: Awesome
    mail: mister@awesome.com
    krbpasswordexpiration: 20200119235959
```

I would expect the new password expiration date to be set to `20200119235959`, but instead I received this error:

`fatal: [freeipa]: FAILED! => {"changed": false, "msg": "response user_mod: Unknown option: krbpasswordexpiration"}`

In the API explorer, you can see that (at least in 4.5.x), `krbPasswordExpiration` isn't an attribute on the object, which is why I needed to use `setattr`. Any way you could check on 4.6.x?

**Comment by Akasurde** [comment]
Yes, `krbpasswordexpiration` is added in 4.6.

**Comment by gundalow** [comment]
What's needed to help this get moving?

**Pull request closed without merging**
