### PR TITLE
base64 filter docs: _input is not a positional argument

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
_input is the test/filter input, not a positional argument.

CC @bcoca

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
b64encode
b64decode

### CODE REVIEW

**Comment by bcoca** [comment]
Yes it is,  ` x |filter` is equivalent of `filter(x)`, both are valid forms of passing 'first positional parameter' to jinja filters.

**Comment by felixfontein** [comment]
That is not true in Jinja2. A task with `{{ b64encode('a') }}` fails with `The task includes an option with an undefined variable. The error was: 'b64encode' is undefined`.

**Comment by samccann** [comment]
@bcoca Do you agree or disagree after @felixfontein comment? Not sure if I can merge this PR yet or not.

**Comment by bcoca** [comment]
disagree

**Comment by felixfontein** [comment]
Even if that argument would be valid (and I still strongly disagree): then why is `_input` marked as positional in exactly two out of 17 filters?

**Comment by bcoca** [comment]
just means 15 need to be updated

**Comment by samccann** [comment]
Feels like a bit of an impasse. Are there others who can weigh in on this one?

**Comment by bcoca** [comment]
well, we have 2 kinds of arguments, positional (depends on the position in which they are passed) and named (passed as name=value) ... i don't expect anyone to say _input is a named argument ...

**Comment by felixfontein** [comment]
I would say that filters and tests have *three* kinds of argument: positioal, named (keyword), and input. Of the third kind, there is always exactly one argument.

**Comment by bcoca** [comment]
they are ALL input parameters, this classification is about the manner of input, positional or named .. they are both already 'input'

**Comment by felixfontein** [comment]
In a CS sense, as an (abstract) function, they are all input parameters, that's definitely true. Then let me reformulate: 

> I would say that filters and tests have *three* kinds of argument: positioal, named (keyword), and filter input. Of the third kind, there is always exactly one argument.

Note that the Jinja documentation itself does not even call the filter input an argument, it only calls all the other ones arguments: https://jinja.palletsprojects.com/en/3.1.x/templates/#filters:

> Filters that accept arguments have parentheses around the arguments, just like a function call. For example: `{{ listx|join(', ') }}` will join a list with commas (`str.join(', ', listx)`).

**Comment by briantist** [comment]
I agree with @felixfontein on this one, a third "input" type makes sense in this context. That argument, of which there can only be one, is "positional" in some sense of the word, but that is not a helpful designation because it can only be used in a single, _special_ position that no other "positional" argument can. You can call it position `-1` I guess but that is not a helpful thing for documentation.

---

This is kind of an aside/tangent, but it reminds me a bit of piping in PowerShell; you can mark any (one) parameter as being able to be supplied via the "pipeline". PowerShell is more flexible than jinja2 in this case, since the parameter can always be supplied as a named or positional parameter too (depending on its settings), but pipeline input is still a special case that deserves to be called out that way. 

Example:
```powershell
function Test-Pipeline { 
    [CmdletBinding()] 
    param(
        [Parameter(ValueFromPipeline)] 
        [String]
        $param
    ) 
    
    echo $param 
}
```

`PS> Get-Help Test-Pipeline -Full`

```
NAME
    Test-Pipeline

SYNTAX
    Test-Pipeline [[-param] <string>] [<CommonParameters>]


PARAMETERS
    -param <string>

        Required?                    false
        Position?                    0
        Accept pipeline input?       true (ByValue)
        Parameter set name           (All)
        Aliases                      None
        Dynamic?                     false
        Accept wildcard characters?  false

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).


INPUTS
    System.String
```

`PS> 'hello' | Test-Pipeline`

**Comment by felixfontein** [comment]
Oh noes, GitHub sometimes really is too clever. This should not have been closed, the "fixes" in that PR wasn't intended on doing this...

**Comment by samccann** [comment]
@bcoca What's the haps on this one? Is this subject do debate so to speak (and if so, do we need a few more voices here)?

**Pull request closed without merging**
