### PR TITLE
Backport PR #67339 - Fix proxysql module cursor_class

### LINKED ISSUE #67337: proxysql module DictCursor ignored
##### SUMMARY
proxysql  is using `mysql_driver.cursors.DictCursor` for the cursor_class when it must be `'DictCursor'` based on the latest changes in mysql_utils

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxysql module

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bube/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/xxxx/.ansible_secret
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

confirmed on el7 but must affect all

```
$ pip freeze | grep -i mysql
MySQL-python==1.2.5
PyMySQL==0.9.3
```

##### STEPS TO REPRODUCE

```yaml
- hosts: proxysql
  gather_facts: yes
  vars:
    login_username: EDIT
    login_passwd: EDIT
    proxysql_global_variables:
      mysql:
       moni tor_username: proxymonitor
       monitor_password: ProxyMonitor1!
  tasks:
    - name: set global variables for mysql-%
      proxysql_global_variables:
        login_user: "{{login_username }}"
        login_password: "{{ login_passwd }}"
        variable: "mysql-{{ item.key }}"
        value: "{{ item.value }}"
        load_to_runtime: no
      with_dict: "{{ proxysql_global_variables.mysql | default({}) }}"
```

##### EXPECTED RESULTS
Succeed updating variables

##### ACTUAL RESULTS

```paste below
TASK [set global variables for mysql-%] **********************************************************************************************************************************************************************************************************************
Wednesday 12 February 2020  13:11:18 +0000 (0:00:01.319)       0:00:01.382 ****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: tuple indices must be integers, not str
failed: [ProxySQL1] (item={'value': u'proxymonitor', 'key': u'monitor_username'}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "monitor_username", "value": "proxymonitor"}, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_proxysql_global_variables_payload_GgMcQ7/ansible_proxysql_global_variables_payload.zip/ansible/modules/database/proxysql/proxysql_global_variables.py\", line 266, in <module>\n  File \"/tmp/ansible_proxysql_global_variables_payload_GgMcQ7/ansible_proxysql_global_variables_payload.zip/ansible/modules/database/proxysql/proxysql_global_variables.py\", line 231, in main\n  File \"/tmp/ansible_proxysql_global_variables_payload_GgMcQ7/ansible_proxysql_global_variables_payload.zip/ansible/modules/database/proxysql/proxysql_global_variables.py\", line 122, in check_config\nTypeError: tuple indices must be integers, not str\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### PR DESCRIPTION
**Pull request by maxbube**
##### SUMMARY

Backport Fixes #67337

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
proxysql

##### ADDITIONAL INFORMATION

Backport of #67339  
fix to issue #67337

```paste below

```

### CODE REVIEW

**Comment by maxbube** [comment]
Hey @felixfontein here is the #67339 backport.

**Review by felixfontein — APPROVED** [review]

**Review by Andersson007 — APPROVED** [review]

**Review by markuman — APPROVED** [review]
LGTM

**Comment by kuntalFreshBooks** [comment]
any timeline when we can expect the fix?

**Comment by markuman** [comment]
@kuntalFreshBooks it's already merged. with the next ansible release 2.9.6 it should be fixed.

**Comment by felixfontein** [comment]
2.9.6 has been released 9 hours ago (https://groups.google.com/forum/#!topic/ansible-announce/BmLjWuiJObg).

**Pull request merged**
