### PR TITLE
openssl_certificate: fix state=absent

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
`state=absent` doesn't work.

Needed for #54294.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssl_certificate

### CODE REVIEW

**Comment by felixfontein** [comment]
The failing tests are unrelated to the PR (problem with installing packages on OpenSUSE).

**Comment by resmo** [comment]
shipit

**Comment by felixfontein** [comment]
Looks like I completely forgot adding a changelog fragment while trying to figure out what went wrong with the tests...

**Comment by felixfontein** [comment]
(Failing CI is still not related to this PR. Restarting probably also won't help, this has been happening since somewhen yesterday and seems to affect package installing on OpenSUSE in general.)

**Comment by MarkusTeufelberger** [comment]
Yeah, if it is of any consolation in the meantime, I looked through the code and it looks good...

shipit

**Comment by felixfontein** [comment]
@resmo @MarkusTeufelberger thanks for reviewing!
@mkrizek thanks for merging!

**Pull request merged**
