### PR TITLE
docker_container: fix port order in docs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes docs error introduced in #66382.

CC @desimaniac @Andersson007 

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by Andersson007** [comment]
waiting for @desimaniac 's feedback

**Comment by desimaniac** [comment]
@Andersson007 Looks good, thank you!

**Review by Andersson007 — APPROVED** [review]
LGTM

**Review by desimaniac — APPROVED** [review]

**Comment by felixfontein** [comment]
@desimaniac @Andersson007 thanks a lot for reviewing! I'll merge once the tests pass (that's mainly a formality; will take some time since the "nightly" tests are currently running).

**Pull request merged**
