### PR TITLE
Add check_opts to ansible-pull

### PR DESCRIPTION
**Pull request by opoplawski**
##### SUMMARY
I want to run ansible-pull with --diff.

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/cli/pull.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by bcoca** [comment]
That you add the command line options does not mean they do anything. Also this is a conflict as `-C` is used already by pull for `--checkout`

**Comment by opoplawski** [comment]
Hmm, that is unfortunate.  Is there any interest in supporting this or should I just drop this effort?  If it's worth doing, how do we handle the -c conflict?

**Comment by bcoca** [comment]
i can see the use for this, not sure on how to handle the conflict

**Comment by mattclay** [comment]
CI failure due to:

```
2017-02-01 22:14:57 + ansible-pull -d /tmp/ansible-testing-2yF0QhA20m -U https://github.com/ansible-test-robinro/pull-integration-test -vvvvvv
2017-02-01 22:14:57 ERROR! Unexpected Exception: option -C/--checkout: conflicting option string(s): -C
2017-02-01 22:14:57 the full traceback was:
2017-02-01 22:14:57 
2017-02-01 22:14:57 Traceback (most recent call last):
2017-02-01 22:14:57   File "/root/ansible/bin/ansible-pull", line 102, in <module>
2017-02-01 22:14:57     cli.parse()
2017-02-01 22:14:57   File "/root/ansible/lib/ansible/cli/pull.py", line 88, in parse
2017-02-01 22:14:57     help='branch/tag/commit to checkout.  ' 'Defaults to behavior of repository module.')
2017-02-01 22:14:57   File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
2017-02-01 22:14:57     self._check_conflict(option)
2017-02-01 22:14:57   File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
2017-02-01 22:14:57     option)
2017-02-01 22:14:57 OptionConflictError: option -C/--checkout: conflicting option string(s): -C
```

Full logs here: https://app.shippable.com/runs/58925af49e41480f00eea557/37/console

**Comment by Akasurde** [comment]
Fixed via https://github.com/ansible/ansible/pull/37645. Thanks for the contribution.

**Pull request closed without merging**
