### PR TITLE
Remove govcsim

### PR DESCRIPTION
**Pull request by mariolenz**
##### SUMMARY
We're trying to get rid of govcsim in `community.vmware`.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/platforms/vmware_guidelines.rst

cc @goneri

### CODE REVIEW

**Comment by samccann** [comment]
@mariolenz in general, this doc should probably move into the `community.vmware` collection along with https://docs.ansible.com/ansible/latest/scenario_guides/guide_vmware.html.  Is that something you'd be able to do at some point?

**Comment by samccann** [comment]
Should have said - it's basically moving the files into the collection `docs/docsite/rst` directory - https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html#docs-directory
Then ``antsibull-doc` will bring it back to docs.ansible.com in the `community.vmware` collection page so it's easier for people to find them right there with the collection.

**Comment by mariolenz** [comment]
@samccann Could you please help me? I understand that the file goes into `docs/docsite/rst/` in the collection, maybe renamed to just `dev_guide.rst`. And then I'll have to change `extra-docs.yml`:

```
---
sections:
  - title: Scenario Guide
    toctree:
      - scenario_guide
  - title: Developer Guide
    toctree:
      - dev_guide
```

Like this? Would this be correct?

**Comment by felixfontein** [comment]
@mariolenz that's correct. You might need to adjust labels in that file though, so they start with the correct prefix.

**Comment by samccann** [comment]
I think the steps to migrate a guide to a collection are :

1. migrate to your collection docs/docsite/rst folder.
2. update anchors to use collection name and namespace to ensure they are unique. `ansible_collections.community.vmware.docsite.dev_guide` for example.
3. Test the docs locally w brian's script or Add `antsibull-docs lint-collection-docs` to CI to verify the docs.
4. republish collection and verify the docs show up on devel the next day.
5. stub out the old guide with a :ref: link to the new one. on ansible/ansible)

**Comment by mariolenz** [comment]
@felixfontein @samccann Could you please have a look at ansible-collections/community.vmware#1294? I hope that's the correct way to do it.

**Comment by mariolenz** [comment]
@samccann I'll close this PR for now. I'll open a new one when ansible-collections/community.vmware#1294 is merged (and released) to remove the `community.vmware` Developer Guide completely.

BTW, I think you might be interested in ansible-community/community-topics#91.

**Pull request closed without merging**
