### PR TITLE
Declare support for Python 3.9 in the metadata

### PR DESCRIPTION
**Pull request by webknjaz**
##### SUMMARY

We run unit tests against Python 3.9 in the CI so we need to add a corresponding Trove classifier to the metadata.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME

setup.py

##### ADDITIONAL INFORMATION

N/A

### CODE REVIEW

**Comment by relrod** [comment]
It's minor, but might as well add a changelog entry for it?

**Comment by nitzmahone** [comment]
IIRC @mattclay suggested waiting on this until we actually have an integration target that's testing the controller and module APIs against 3.9...

**Comment by mattclay** [comment]
As @nitzmahone mentioned, I'd prefer to wait until we have integration tests running on Python 3.9. That is being worked on in https://github.com/ansible/ansible/pull/72861, which is adding Fedora 33 to the test matrix.

**Comment by webknjaz** [comment]
@relrod do you want to cherry-pick this commit to your branch?

**Comment by relrod** [comment]
Will do.

**Pull request closed without merging**
