### PR TITLE
[obsolete] new rds_instance module - split of RDS module

### PR DESCRIPTION
**Pull request by michael-dev2rights**
##### SUMMARY

This PR contains an old version of the new rds_instance module. It is in fact a reworking of https://github.com/ansible/ansible/pull/25646 and https://github.com/ansible/ansible/pull/19772

This is preserved until I rebuild the interface to the module in PR #29032.  Once that interface is tested and working then I will close this PR.  In case of having problems migrating from this PR to the new one contact me in either the new PR or the #ansible-aws IRC channel.  

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

rds_instance module

##### ANSIBLE VERSION

```
ansible 2.4.0 (mdd_rds_split_instance b81ee48144) last updated 2017/07/10 15:03:32 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mikedd/dev/ansible/ansible-add-modules/library']
  ansible python module location = /home/mikedd/dev/ansible/ansible-add-modules/lib/ansible
  executable location = /home/mikedd/dev/ansible/ansible-add-modules/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

This is a _two time_ updated version of https://github.com/ansible/ansible/pull/19772 from Willthames which contains fixes as well as widely extended integration test cases which have been moved into the new integration testing framework and so would work within CI.  

> Split the existing rds module into three separate modules, and make the modules idempotent (remove the command argument).
>  The new modules are expected to be almost entirely backward compatible with the old module, other than the command change - it should be easy to update existing code to use the new modules.
> The new modules are entirely boto3 - support for boto has been dropped for the new modules.

Willthames stated that he's not going to have much time to work on this (though hopefully he'll be able provide a little support and e.g. review the code) so I'm now proposing to put this forward myself as a separate PR

##### KNOWN ISSUES

* This has not been tested for working with all states of the RDS - #19751 might apply equally here - the situation is likely better than existing RDS modules and retry will work once the RDS has stabilised
* The test suite (coming in a separate PR) takes a really long time and state transitions are very slow, however the run has been completed.

### CODE REVIEW

**Comment by aioue** [comment]
@michael-dev2rights would like to encourage you to add `--check` and `--diff` support for these new modules as per the [AWS Working Group Best Practices](https://github.com/ansible/community/blob/master/group-aws/bestpractices.md).

**Comment by mikedlr** [comment]
@aioue thanks for the suggestion;  I will be unlikely to add these to the pull request before it gets merged first time for the simple reason that I don't want to put too much investment until it's 100% clear that the split is agreed and implemented.  If someone (are you able?) put in a pull request to my branch with appropriate tests and an implementation of the feature then I would definitely try to merge that.  

If you aren't able, for whatever reason including time, implement the feature yourself, please could you consider raising a separate issue, possibly listing all of the AWS modules where these features are missing.  `@`mention me on the issue and I will try to look at it once the merge is complete.

**Comment by ardentperf** [comment]
@michael-dev2rights I just did some testing of this PR with aurora and it doesn't seem to work yet. I believe that aurora requires a whole different call from the boto libraries (need to look closer at boto though) - i suspect you need to call a "create cluster" function instead of "create instance" (the RDS api works this way so i suspect boto will too).  Also, note that last november they announced a PostgreSQL-compatible edition of aurora which is currently in preview. [ https://aws.amazon.com/about-aws/whats-new/2017/04/announcing-open-preview-of-amazon-aurora-with-postgresql-compatibility/ ]

Something we might consider is whether it would be appropriate to split out the aurora engine (soon to be engines) from the rds_instance module into a different module called rds_cluster.  This would better mirror amazon's published APIs, which use different semantics for aurora (you create a cluster which may contain multiple instances):

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html

The publicly available aurora postgresql preview documentation also reflects that it will likely use this same (existing) aurora semantics & API:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_AuroraPostgreSQL.html

The re-worked rds code here looks good. Looking forward to getting some clarity on this split!

**Comment by aioue** [comment]
@mikedlr I am not able to make these check mode & diff changes, or I would. Lacking both the time & python skill here. I'm proud of my historically accepted PRs however!

`If you aren't able, for whatever reason including time, implement the feature yourself, please could you consider raising a separate issue, possibly listing all of the AWS modules where these features are missing. @mention me on the issue and I will try to look at it once the merge is complete.`

Here are the AWS modules I've tested (not a complete list) that do not have `check` mode, and implicitly, diff mode. `--diff` is important, as some modules have upwards of 20 args.. binary chopping the args to see what has changed, then the args args, then the ar... you see where this is going.

`--check` and `--diff ` are enormously useful to new Ansible users, and I think this will cause a plateau in users if not addressed (migrating to Ansible is impossible if each task you write could ruin your existing production infra, inscrutably).

Some, not all, AWS modules that do not support `--check` and `--diff`:
https://github.com/ansible/ansible/issues?q=is%3Aissue+is%3Aopen+check+mode+author%3Aaioue

**Comment by michael-dev2rights** [comment]
@aioue great list thanks; the clear list tickets are really appreciated.  I totally agree about getting all of the proper features implemented.   I notice you have been making some PRs for these features.  If you drop by the [AWS working group](https://github.com/ansible/community/tree/master/group-aws) IRC channel then we may well be able to support you through some of your doubts about fixing the python code.

**Comment by mikedlr** [comment]
@aioue if you look in https://github.com/ansible/ansible/pull/30746 you can find a version of rds_instance which implements check mode.  Diff will hopefully come later.  Your testing of this will be very much appreciated.

**Comment by aioue** [comment]
@mikedlr that's great news. Unfortunately I've moved project and am unable to commit time for testing at present.

**Pull request closed without merging**
