### PR TITLE
fix for handling commands that return no data or error

### LINKED ISSUE #22001: Problem with nxos_facts on ansible 2.3
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report
bug report
##### COMPONENT NAME

nxos_facts
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel ebc2716be7)
```

##### OS / ENVIRONMENT

centOs 6.9
##### SUMMARY

So for some reasons when I have invalid input on command next step of the module behaviour generation of the error and process iterrupted. Commands which have not "invalid input" works fine, but no output about them in module.
##### STEPS TO REPRODUCE

```yaml
---

- name: Collect NXOS facts
  hosts: test-routers
  gather_facts: false
  connection: local

  tasks:

    - name: NX-OS Facts
      nxos_facts:
        gather_subset: all
#        gather_subset:
#             - "!interfaces"
        provider: "{{ cli }}"

```

##### EXPECTED RESULTS

I want the output from good commands
Expect output of good commands about nx-os facts
##### ACTUAL RESULTS

```
[17:10]root@dnetapp01:/etc/network/scripts/databases/playbook_ansible$ ansible-playbook 1_nxos_facts.yml -vvv
Using /etc/ansible/ansible.cfg as config file
SSH password:

PLAYBOOK: 1_nxos_facts.yml **********************************************************************************************************************************************************
1 plays in 1_nxos_facts.yml

PLAY [Collect NXOS facts] ***********************************************************************************************************************************************************
META: ran handlers

TASK [NX-OS Facts] ******************************************************************************************************************************************************************
task path: /etc/network/scripts/databases/playbook_ansible/1_nxos_facts.yml:10
Using module file /etc/network/scripts/ansible/lib/ansible/modules/network/nxos/nxos_facts.py
<10.255.252.2> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.255.252.2> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.255.252.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "echo /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642" && echo ansible-tmp-1488208234.33-150228641643642="e cho /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642" ) && sleep 0'
<10.255.252.2> PUT /tmp/tmppgpQyw TO /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/nxos_facts.py
<10.255.252.2> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/ /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/nxos_facts.py && sleep 0'
<10.255.252.2> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/nxos_facts.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1488208234.33-1502 28641643642/" > /dev/null 2>&1 && sleep 0'
fatal: [10.255.252.2]: FAILED! => {
"changed": false,
"failed": true,
"invocation": {
"module_args": {
"gather_subset": [
"all"
],
"host": "10.255.252.2",
"password": "xxx",
"port": null,
"provider": {
"auth_pass": "xxx",
"authorize": true,
"host": "10.255.252.2",
"password": "xxx",
"port": null,
"ssh_keyfile": null,
"timeout": null,
"transport": "cli",
"use_ssl": null,
"username": "xxx",
"validate_certs": null
},
"ssh_keyfile": null,
"timeout": null,
"transport": "cli",
"use_ssl": null,
"username": "xxx",
"validate_certs": null
}
},
"msg": "show system resources | json\r\r\n ^\r\n% Invalid command at '^' marker.\r\n\rn7k-1-vdc-agg# "
}
to retry, use: --limit @/etc/network/scripts/databases/playbook_ansible/1_nxos_facts.retry

PLAY RECAP **************************************************************************************************************************************************************************
10.255.252.2 : ok=0 changed=0 unreachable=0 failed=1


```

### PR DESCRIPTION
**Pull request by privateip**
This patch addresses a problem in nxos_facts where certain commands are
not supported or return no data, the module would raise an exception.
With this patch, the nxos_facts module will now print a warning for any
commands that return no data and not populate the facts.

fixes #22001

### CODE REVIEW

**Comment by olex777** [comment]
Yes, this is works, thank you

**Comment by olex777** [comment]
Oops, error is dissapeared but for some reasons collected only configuration. When I try to collect hardware I have such an output:
TASK [NX-OS Facts] *****************************************************************************************************************************************************************
task path: /etc/network/scripts/databases/playbook_ansible/1_nxos_facts.yml:10
Using module file /etc/network/scripts/ansible/lib/ansible/modules/network/nxos/nxos_facts.py
<10.255.252.2> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.255.252.2> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.255.252.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1488358400.92-38505273453111 `" && echo ansible-tmp-1488358400.92-38505273453111="` echo /root/.ansible/tmp/ansible-tmp-1488358400.92-38505273453111 `" ) && sleep 0'
<10.255.252.2> PUT /tmp/tmpiZn_vn TO /root/.ansible/tmp/ansible-tmp-1488358400.92-38505273453111/nxos_facts.py
<10.255.252.2> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1488358400.92-38505273453111/ /root/.ansible/tmp/ansible-tmp-1488358400.92-38505273453111/nxos_facts.py && sleep 0'
<10.255.252.2> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1488358400.92-38505273453111/nxos_facts.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1488358400.92-38505273453111/" > /dev/null 2>&1 && sleep 0'
ok: [10.255.252.2] => {
    "ansible_facts": {
        "ansible_net_all_ipv4_addresses": [],
        "ansible_net_all_ipv6_addresses": [],
        "ansible_net_filesystems": [
            "bootflash:"
        ],
        "ansible_net_gather_subset": [
            "hardware",
            "default",
            "interfaces",
            "legacy"
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "!config"
            ],
            "host": "10.255.252.2",
            "password": "xxxx",
            "port": null,
            "provider": {
                "auth_pass": "xxx",
                "authorize": true,
                "host": "10.255.252.2",
                "password": "xxx",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "xxx",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "xxx",
            "validate_certs": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************
10.255.252.2               : ok=1    changed=0    unreachable=0    failed=0

What's wrong?

**Comment by privateip** [comment]
My suspicion is you have warnings disabled.  This patch will print a warning for any commands it is unable to execute.  Can you confirm if you have disabled warnings?

**Comment by olex777** [comment]
Where could I see whether warnings disable or not? And how I could enable them if they are disable?

**Comment by olex777** [comment]
So what in the end we have with this issue?

**Pull request merged**
