### PR TITLE
moved modules listing to utils.py, get modules list at playbook level so...

### PR DESCRIPTION
**Pull request by abondis**
... we dont repeat the listing on each task
- search takes -M into account instead of always using default path

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm getting numerous errors when rebasing this one, including a undefined value for pathsep and other things.   Can you please rebase this?

**Comment by mpdehaan** [comment]
also run "make test" and make sure it passes... yours may be fine but I think it has been developed on top of some stale code and that has led to problems in merging.

**Comment by abondis** [comment]
did make test fail ? because it was ok on mine, i even removed /usr/share/ansible to make sure it was working as desired.
I'm going to rebase and try again, thanks.

**Comment by abondis** [comment]
is it better this way or should i push to a new branch ?
sorry for the mess ...

**Comment by mpdehaan** [comment]
You should probably just push a new branch.   Starting one branch per feature/pull-request is always a very good idea

```
git checkout -b newbranch
git pull --rebase origin/devel
```

etc

Another good thing to do is always use squash merges, so when you are done, like:

```
git checkout -b newbranch-squashed
git merge --squash newbranch
# and submit the pull request from there
```

That allows me to review everything in one commit

I also saw something where it looked like you were using os.pathsep.  The delimiter between module paths is ":", not "/".   This needs to be fixed too.

**Comment by mpdehaan** [comment]
Let me fix this one.

**Pull request closed without merging**
