### PR TITLE
gitlab_project: don't ignore errors

### LINKED ISSUE #36495: Ansible gitlab module should fail if importing the repo of url_import is failing
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

gitlab_project

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.2 (Maipo)

##### SUMMARY

I have this task which creates a GIT repo:
```yaml
- name: Create Git repo
  gitlab_project:
    server_url: "http://myhost.com/gitlab"
    validate_certs: True
    login_user: "my_git_user }}"
    login_password: "{{ my_git_password }}"
    name: "{{ my_repo_name }}"
    group: "{{ my_repo_group }}"
    public: True
    visibility_level: 20
    issues_enabled: False
    wiki_enabled: True
    snippets_enabled: True
    import_url: "http://myhost.com/gitlab/gitrepothatdoesnotexist.git"
    state: present
```

Then ansible succeeds in the step, but when I go to the gitlab web interface at the URL of the created git repo, it throws an error like:

" Import repository
The repository could not be imported.

Error importing repository http://myhost.com/gitlab/gitrepothatdoesnotexist.git into my_git_repo - Cloning into bare repository '[REPOS PATH]/mygitrepo.git'...
fatal: repository 'http://myhost.com/gitlab/gitrepothatdoesnotexist.git' not found

"

##### STEPS TO REPRODUCE

```yaml
- name: Create Git repo
  gitlab_project:
    server_url: "http://myhost.com/gitlab"
    validate_certs: True
    login_user: "{{ my_git_user }}"
    login_password: "{{ my_git_password }}"
    name: "{{ my_repo_name }}"
    group: "{{ my_repo_group }}"
    public: True
    visibility_level: 20
    issues_enabled: False
    wiki_enabled: True
    snippets_enabled: True
    import_url: "http://myhost.com/gitlab/gitrepothatdoesnotexist.git"
    state: present
```

##### EXPECTED RESULTS

Gitlab should show an error when you visit the URL of the created repo.

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
`gitlab_project`: report encountered errors. Fixes #36495.

Report failures of `createprojectuser`/`createproject` methods.

Unit test provided.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
gitlab_project

##### ANSIBLE VERSION
```
ansible 2.6.0 (devel 076ea07bb5) last updated 2018/02/26 02:30:43 (GMT +200)
```

##### ADDITIONAL INFORMATION

Remote pair programming fix, thanks to @mscherer for being the observer.

### CODE REVIEW

**Comment by dj-wasabi** [comment]
shipit

**Comment by pilou-** [comment]
Good day! @akasurde, could you please review this pull request (as a namespace maintainer) ?

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by resmo** [comment]
If this should be in 2.5, let me know or file a new PR with (git cherry-pick -x) against branch stable-2.5

**Pull request merged**
