### PR TITLE
template, copy: archive, (m/a)time support added, file: (m/a)time support added

### PR DESCRIPTION
**Pull request by rdolejsi**
template, copy: added support for archive parameter to retain permissions, ownership and timestamps of the source(s) on the destination(s).

template, copy, file: added support for mtime, atime - setting access/mod datetime of the destination(s) in unix touch format HHMMDDhhmi[.ss].

Please note: mtime, atime suport addition is a side-effect of archive and cannot be split in separate pull request.

### CODE REVIEW

**Comment by rdolejsi** [comment]
The template archive option is a crucial one when iterating and templating directory structure which includes executable scripts, configurations with diverse access rights, etc.

**Comment by rdolejsi** [comment]
This is a replacement request for the closed pullreq #9143 (no changes, update to current HEAD).

This is a half of the patch, complementary to modules-core pullreq http://github.com/ansible/ansible-modules-core/pull/102. Both pullreqs are required.

**Comment by amenonsen** [comment]
Since the other half of this PR to ansible-modules-core has been closed, this should be closed too. Pity, this seems like a nice feature.

**Comment by sivel** [comment]
@rdolejsi,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by sivel** [comment]
@rdolejsi,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by rdolejsi** [comment]
Closing this pull request in favor of creating a new one once ported to Ansible 2.1+ devel tree.

**Pull request closed without merging**
