### PR TITLE
Allow to define OpenStack SecurityGroup rules matching any protocol

### PR DESCRIPTION
**Pull request by atosatto**
##### SUMMARY

Allows to use the `any` keyword to define secury group rules matching all the protocols.

```
# Allow any connection from  'bar' 
- os_security_group_rule:
    security_group: 'foo'
    protocol: 'any'
    remote_group: 'bar'
```

This is very useful when creating security groups in a loop.
Indeed,

```
- os_security_group_rule:
    security_group: 'foo'
    protocol: None
    remote_group: 'bar'
```

does not work!
I've chosen the 'any' keyword since it is consistent with OpenStack Horizon.

This issue is related to PR #23707 since both are needed to strongly support the definition of security groups rules in a loop. 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
os_security_group_rule

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

A more extensive example of the use case in which supporting the `any` keyword would be really helpful is provided by the following snippet.

```
  - name: Create the Security Group '{{ os_security_group_name }}' (OpenStack)
    os_security_group:
      name: "{{ os_security_group_name }}"
      description: "{{ os_security_group['description'] | default(os_security_group_name) }}"
      state: "present"

  - name: Create the ingress rules having 'remote_ip_prefix' of the Security Group '{{ os_security_group_name }}' (OpenStack)
    os_security_group_rule:
      security_group: "{{ os_security_group_name }}"
      protocol: "{{ group_rule['protocol'] }}"
      port_range_min: "{{ group_rule['port_range_min'] }}"
      port_range_max: "{{ group_rule['port_range_max'] }}"
      remote_ip_prefix: "{{ group_rule['remote_ip_prefix'] }}"
      direction: "ingress"
    with_items: "{{ os_security_group_ingress_rules | selectattr('remote_ip_prefix', 'defined') | list }}"
    loop_control:
      loop_var: group_rule

  - name: Create the ingress rules having 'remote_group' of the Security Group '{{ os_security_group_name }}' (OpenStack)
    os_security_group_rule:
      security_group: "{{ os_security_group_name }}"
      protocol: "{{ group_rule['protocol'] }}"
      port_range_min: "{{ group_rule['port_range_min'] }}"
      port_range_max: "{{ group_rule['port_range_max'] }}"
      remote_group: "{{ group_rule['remote_group'] }}"
      direction: "ingress"
    with_items: "{{ os_security_group_ingress_rules | selectattr('remote_group', 'defined') | list }}"
    loop_control:
      loop_var: group_rule

  - name: Create the egress rules having 'remote_ip_prefix' of the Security Group '{{ os_security_group_name }}' (OpenStack)
    os_security_group_rule:
      security_group: "{{ os_security_group_name }}"
      protocol: "{{ group_rule['protocol'] }}"
      port_range_min: "{{ group_rule['port_range_min'] }}"
      port_range_max: "{{ group_rule['port_range_max'] }}"
      remote_ip_prefix: "{{ group_rule['remote_ip_prefix'] }}"
      direction: "egress"
    with_items: "{{ os_security_group_egress_rules | selectattr('remote_ip_prefix', 'defined') | list }}"
    loop_control:
      loop_var: group_rule

  - name: Create the egress rules having 'remote_group' of the Security Group '{{ os_security_group_name }}' (OpenStack)
    os_security_group_rule:
      security_group: "{{ os_security_group_name }}"
      protocol: "{{ group_rule['protocol']  }}"
      port_range_min: "{{ group_rule['port_range_min'] }}"
      port_range_max: "{{ group_rule['port_range_max'] }}"
      remote_group: "{{ group_rule['remote_group'] }}"
      direction: "egress"
    with_items: "{{ os_security_group_egress_rules | selectattr('remote_group', 'defined') | list }}"
    loop_control:
      loop_var: group_rule
```

### CODE REVIEW

**Comment by atosatto** [comment]
Ehi @rcarrillocruz have you had any chance to look at this PR?

**Comment by atosatto** [comment]
ready_for_review

**Review by Thingee — APPROVED** [review]
👍

**Comment by mnaser** [comment]
@atosatto Could you rebase this and also, what happens if you just omit the protocol?

**Comment by Thulium-Drake** [comment]
This was fixed with #59055

Can be closed :)

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Pull request closed without merging**
