### PR TITLE
Allow local plays to execute when --ask-sudo-pass is used on the command line

### PR DESCRIPTION
**Pull request by ludovicc**
When mixing a local play with remote plays using sudo and --ask-sudo-pass on the command line, I get an error 'sudo with password is presently only supported on the paramiko (SSH) connection type'. But sudo is not used in the local play, and I force it with sudo: False in the play.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Change this to a one-line if and I'll take it:

if self.runner.sudo and sudoable and self.runner.sudo_pass:

**Comment by ludovicc** [comment]
Done. It was more logical to have nested ifs.

**Comment by mpdehaan** [comment]
Dang it, I read it wrong, you were correct originally because the cmd = was being assigned later.

The consequences of code review too early in the morning.

Revert this and I'll apply it -- sorry for confusion and extra work.

**Comment by ludovicc** [comment]
Reverted!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
