### PR TITLE
win_package - Test to solve quotes issues

### LINKED ISSUE #40973: win_package fails to uninstall a package whose registry UninstallString is quoted
##### SUMMARY
win_package fails to uninstall a package whose registry UninstallString is quoted.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_package

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gtyler/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Running Ansible from Windows 10 under Windows Subsystem for Linux using the Ubuntu distribution.
Managing Windows Server 2016 Datacenter.

##### STEPS TO REPRODUCE

1. Install Doxygen 1.8.14 from http://www.stack.nl/~dimitri/doxygen/download.html on the target machine.
2. Execute a playbook that uninstalls this package.

```yaml
- name: Uninstall Doxygen
  win_package:
    product_id: 'doxygen_is1'
    state: absent
```

##### EXPECTED RESULTS

Package is uninstalled.

##### ACTUAL RESULTS

Task fails and package is not uninstalled.

```
fatal: [MACHINENAME]: FAILED! => {
    "changed": false,
    "msg": "failed to run uninstall process (\"\\\"C:\\Program Files\\doxygen\\system\\unins000.exe\\\"\"): Exception calling \"SearchPath\" with \"1\" argument(s): \"Could not locate the following executable \\.exe\"",
    "reboot_required": false,
    "restart_required": false
}
```

##### OTHER NOTES

* If you execute the Powershell command `Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\doxygen_is1`, you'll note that the UninstallString property has the path to the uninstaller surrounded in double-quotes like so: `"C:\Program Files\doxygen\system\unins000.exe"`.
* The uninstaller works correctly from the Windows Add/Remove Programs control panel.

### LINKED ISSUE #58044: win_package "failed to run uninstall process"
##### SUMMARY
Win_Packag fails to uninstall package

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_package

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]

```

##### OS / ENVIRONMENT
Running Ansible from Linux Debian 9

##### STEPS TO REPRODUCE
1. Install VLC media player from https://get.videolan.org/vlc/3.0.7.1/win64/vlc-3.0.7.1-win64.exe on the target machine or execute this playbook:
```
- name: "Installation"
  hosts: "windows"
  tasks:
          - name: "Install VLC"
            win_package:
                    path: https://get.videolan.org/vlc/3.0.7.1/win64/vlc-3.0.7.1-win64.exe
                    product_id: 'VLC media player'
                    arguments: /S /L=1036
                    state: present
```
2. Execute a playbook that uninstalls this package
```
- name: "Uninstall VLC"
  hosts: "windows"
  tasks:
          - name: "Uninstall VLC"
            win_package:
                    product_id: 'VLC media player'
                    arguments: '/S'
                    state: absent
```

##### EXPECTED RESULTS
Package is uninstalled
##### ACTUAL RESULTS

```
root@IF010-PREPA:/home# ansible-playbook -i /home/windows.yml /home/dpackage.yml -vvvv
ansible-playbook 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/windows.yml as it did not pass it's verify_file() method
script declined parsing /home/windows.yml as it did not pass it's verify_file() method
Parsed /home/windows.yml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: dpackage.yml ***********************************************************************
Positional arguments: /home/dpackage.yml
become_method: sudo
inventory: (u'/home/windows.yml',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in /home/dpackage.yml

PLAY [Uninstall VLC] *************************************************************************

TASK [Gathering Facts] ***********************************************************************
task path: /home/dpackage.yml:1
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<192.168.6.22> ESTABLISH WINRM CONNECTION FOR USER: Etudiant-Admin on PORT 5985 TO 192.168.6.22
EXEC (via pipeline wrapper)
ok: [192.168.6.22] => {
    "ansible_facts": {
        "ansible_architecture": "64 bits", 
        "ansible_bios_date": "03/23/2018", 
        "ansible_bios_version": "1.8.3", 
        "ansible_date_time": {
            "date": "2019-06-19", 
            "day": "19", 
            "epoch": "1560937817,20787", 
            "hour": "09", 
            "iso8601": "2019-06-19T07:50:17Z", 
            "iso8601_basic": "20190619T095017205872", 
            "iso8601_basic_short": "20190619T095017", 
            "iso8601_micro": "2019-06-19T07:50:17.205872Z", 
            "minute": "50", 
            "month": "06", 
            "second": "17", 
            "time": "09:50:17", 
            "tz": "Romance Standard Time", 
            "tz_offset": "+02:00", 
            "weekday": "Wednesday", 
            "weekday_number": "3", 
            "weeknumber": "24", 
            "year": "2019"
        }, 
        "ansible_distribution": "Microsoft Windows 10 Professionnel", 
        "ansible_distribution_major_version": "10", 
        "ansible_distribution_version": "10.0.18362.0", 
        "ansible_domain": "", 
        "ansible_env": {
            "ALLUSERSPROFILE": "C:\\ProgramData", 
            "APPDATA": "C:\\Users\\Etudiant-Admin\\AppData\\Roaming", 
            "AutInstLog": "C:\\ProgramData\\Siemens\\Automation\\Logfiles\\Setup", 
            "COMPUTERNAME": "IF010-PREPA", 
            "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe", 
            "CommonProgramFiles": "C:\\Program Files\\Common Files", 
            "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files", 
            "CommonProgramW6432": "C:\\Program Files\\Common Files", 
            "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData", 
            "EQ_LIBRARY_PATH": "C:\\gcc\\x86_64-w64-mingw32\\lib", 
            "HOMEDRIVE": "C:", 
            "HOMEPATH": "\\Users\\Etudiant-Admin", 
            "LOCALAPPDATA": "C:\\Users\\Etudiant-Admin\\AppData\\Local", 
            "LOGONSERVER": "\\\\IF010-PREPA", 
            "NUMBER_OF_PROCESSORS": "4", 
            "NewEnvironment1": "120;C:\\Program Files (x86)\\Schneider Electric\\Advantys\\Bin", 
            "OS": "Windows_NT", 
            "OneDrive": "C:\\Users\\Etudiant-Admin\\OneDrive", 
            "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL", 
            "PROCESSOR_ARCHITECTURE": "AMD64", 
            "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel", 
            "PROCESSOR_LEVEL": "6", 
            "PROCESSOR_REVISION": "9e09", 
            "PROMPT": "$P$G", 
            "PSExecutionPolicyPreference": "Unrestricted", 
            "PSModulePath": "C:\\Users\\Etudiant-Admin\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", 
            "PT7HOME": "C:\\Program Files\\Cisco Packet Tracer 7.0", 
            "PUBLIC": "C:\\Users\\Public", 
            "Path": "C:\\Program Files (x86)\\SIEMENS\\S7-PCT\\bin;C:\\Program Files\\Common Files\\Siemens\\Automation\\Simatic OAM\\bin;C:\\Program Files (x86)\\Common Files\\Siemens\\Sqlany;C:\\Program Files (x86)\\Siemens\\Step7\\S7bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\gcc\\bin;C:\\gcc\\libexec\\gcc\\x86_64-pc-mingw32\\6.2.0;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin\\;C:\\Program Files\\IVI Foundation\\VISA\\Win64\\Bin\\;C:\\Program Files (x86)\\Druide\\Antidote 9\\Application\\Bin64\\;C:\\Program Files (x86)\\Druide\\Antidote 9\\Application\\Bin32\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\PKWARE\\pkzipc;c:\\Program Files (x86)\\Microsoft SQL Server\\90\\Tools\\binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\80\\Tools\\Binn\\;C:\\Program Files\\PuTTY\\;C:\\Program Files (x86)\\Common Files\\ALPI SHARED;C:\\Program Files (x86)\\Common Files\\Alpi Shared;C:\\Program Files\\Common Files\\Alpi Shared;C:\\Program Files (x86)\\Common Files\\ALPI Shared\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\PKWARE\\pkzipc;C:\\Users\\Etudiant-Admin\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files (x86)\\Nmap", 
            "ProgramData": "C:\\ProgramData", 
            "ProgramFiles": "C:\\Program Files", 
            "ProgramFiles(x86)": "C:\\Program Files (x86)", 
            "ProgramW6432": "C:\\Program Files", 
            "QUARTUS_ROOTDIR": "C:\\altera\\13.0\\quartus", 
            "S7TMP": "C:\\Program Files (x86)\\Siemens\\Step7\\S7Tmp", 
            "SOPC_KIT_NIOS2": "C:\\altera\\13.0\\nios2eds", 
            "SQLANY": "C:\\Program Files (x86)\\Common Files\\Siemens\\Sqlany", 
            "Simatic_OAM": "C:\\Program Files\\Common Files\\Siemens\\Automation\\Simatic OAM", 
            "Simatic_OAM_DATA": "C:\\ProgramData\\Siemens\\Automation\\Simatic OAM", 
            "SystemDrive": "C:", 
            "SystemRoot": "C:\\WINDOWS", 
            "TEMP": "C:\\Users\\ETUDIA~1\\AppData\\Local\\Temp", 
            "TMP": "C:\\Users\\ETUDIA~1\\AppData\\Local\\Temp", 
            "USERDOMAIN": "IF010-PREPA", 
            "USERDOMAIN_ROAMINGPROFILE": "IF010-PREPA", 
            "USERNAME": "Etudiant-Admin", 
            "USERPROFILE": "C:\\Users\\Etudiant-Admin", 
            "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox", 
            "VXIPNPPATH": "C:\\Program Files (x86)\\IVI Foundation\\VISA", 
            "VXIPNPPATH64": "C:\\Program Files\\IVI Foundation\\VISA", 
            "windir": "C:\\WINDOWS"
        }, 
        "ansible_fqdn": "IF010-PREPA.", 
        "ansible_hostname": "IF010-PREPA", 
        "ansible_interfaces": [
            {
                "connection_name": "Ethernet 2", 
                "default_gateway": "192.168.6.254", 
                "dns_domain": "ad.univ-angers.fr", 
                "interface_index": 18, 
                "interface_name": "Intel(R) Ethernet Connection (5) I219-LM", 
                "macaddress": "8C:EC:4B:85:D7:5B"
            }
        ], 
        "ansible_ip_addresses": [
            "192.168.6.22", 
            "fe80::5153:6c74:6758:a9d1"
        ], 
        "ansible_kernel": "10.0.18362.0", 
        "ansible_lastboot": "2019-06-19 09:04:25Z", 
        "ansible_machine_id": "S-1-5-21-3515748753-4277541506-1945889785", 
        "ansible_memtotal_mb": 16248, 
        "ansible_nodename": "IF010-PREPA.", 
        "ansible_os_family": "Windows", 
        "ansible_os_name": "Microsoft Windows 10 Professionnel", 
        "ansible_os_product_type": "workstation", 
        "ansible_owner_contact": "", 
        "ansible_owner_name": "Utilisateur Windows", 
        "ansible_powershell_version": 5, 
        "ansible_processor": [
            "GenuineIntel", 
            "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz", 
            "GenuineIntel", 
            "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz", 
            "GenuineIntel", 
            "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz", 
            "GenuineIntel", 
            "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz"
        ], 
        "ansible_processor_cores": 4, 
        "ansible_processor_count": 1, 
        "ansible_processor_threads_per_core": 1, 
        "ansible_processor_vcpus": 4, 
        "ansible_product_name": "OptiPlex 7050", 
        "ansible_product_serial": "5Y8WNR2", 
        "ansible_reboot_pending": false, 
        "ansible_swaptotal_mb": 0, 
        "ansible_system": "Win32NT", 
        "ansible_system_description": "", 
        "ansible_system_vendor": "Dell Inc.", 
        "ansible_uptime_seconds": 2754, 
        "ansible_user_dir": "C:\\Users\\Etudiant-Admin", 
        "ansible_user_gecos": "", 
        "ansible_user_id": "Etudiant-Admin", 
        "ansible_user_sid": "S-1-5-21-3515748753-4277541506-1945889785-1002", 
        "ansible_virtualization_role": "NA", 
        "ansible_virtualization_type": "NA", 
        "ansible_win_rm_certificate_expires": "2022-06-16 18:25:38", 
        "ansible_windows_domain": "WORKGROUP", 
        "ansible_windows_domain_member": false, 
        "ansible_windows_domain_role": "Stand-alone workstation", 
        "gather_subset": [
            "all"
        ], 
        "module_setup": true
    }, 
    "changed": false
}
META: ran handlers

TASK [Uninstall VLC] *************************************************************************
task path: /home/dpackage.yml:4
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/windows/win_package.ps1
Pipelining is enabled.
<192.168.6.22> ESTABLISH WINRM CONNECTION FOR USER: Etudiant-Admin on PORT 5985 TO 192.168.6.22
EXEC (via pipeline wrapper)
fatal: [192.168.6.22]: FAILED! => {
    "changed": false, 
    "msg": "failed to run uninstall process (\"\\\"C:\\Program Files\\VideoLAN\\VLC\\uninstall.exe\\\"\" /S): Exception lors de l'appel de « SearchPath » avec « 1 » argument(s) : « Could not find file '\\.exe'. »", 
    "reboot_required": false
}

PLAY RECAP ***********************************************************************************
192.168.6.22               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
##### OTHER NOTES
-I can put the path on the uninstaller's files:
```
- name: "Uninstall VLC"
  hosts: "windows"
  tasks:
          - name: "Uninstall VLC"
            win_package:
                    product_id: 'VLC media player'
                    arguments: '/S'
                    path: 'C:\Pogram Files\VideoLAN\VLC\uninstall.exe'
                    state: absent
```
But there still is an error:
```
fatal: [192.168.6.22]: FAILED! => {"changed": false, "msg": "the file at the local path C:\\Pogram Files\\VideoLAN\\VLC\\uninstall.exe cannot be reached", "reboot_required": false}
```

### PR DESCRIPTION
**Pull request by ShachafGoldstein**
##### SUMMARY
Fixes: #58044
Fixes: #40973

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_package.ps1

### CODE REVIEW

**Comment by nitzmahone** [comment]
Not sure if you were intending to try and get this merged, but I don't think we'd actually want to do it this way- lots of ways "just remove all the quotes" can fail. If anything, we probably need to expose some of the cmdline parsing stuff to take that apart properly, or at least just remove quotes only from the ends of the strings...

**Comment by ShachafGoldstein** [comment]
> Not sure if you were intending to try and get this merged, but I don't think we'd actually want to do it this way- lots of ways "just remove all the quotes" can fail. If anything, we probably need to expose some of the cmdline parsing stuff to take that apart properly, or at least just remove quotes only from the ends of the strings...

correct but from all the examples I saw, the only place vendors put the `"` is around the EXE full name and all the parameters are without `"`", I can make it strip just the EXE quotes with some string manipulation and indexes if you prefer

**Comment by nitzmahone** [comment]
Just poking around in the code, I actually think this might be a bug related to the Argv-ToString call on quoted non-list args... There are already two layers of command-line parsing going on by actual command-line parsers (Argv-ToString and the one inside Run-Command), so adding another layer is not the right thing to do (especially since this PR in its current form just strips all quotes, which will break anything of any complexity involving other quoted args or escaped quotes).

The more proper solution here is probably to not coerce $uninstall_arguments` to a list in the non-msiexec case, and skip the Argv-ToString call if it's already a string. That way, we can remain oblivious to any quoting in use and leave that to a proper command-line parser.

There may also be a related bug if the Msiexec string is quoted, or if MsiExec were an absolute path (right now we're just checking if it starts with 'MsiExec'), but I'm not sure if some installers set that manually or not (IIRC Windows Installer always puts those in unquoted and not path-qualified).

**Comment by ShachafGoldstein** [comment]
I fixed it to only strip the EXE quotes in the last commit but I also saw all the parsing and this was the best immediate way to handle the issues coming.

Maybe we could rewrite this part of the module or the relevant functions to be smarter in the parsing but I'm not sure how long that will take

**Comment by jborean93** [comment]
So I was looking into this a bit more and it looks like @nitzmahone is right and we don't want to use `Argv-ToString` at all when reading the UninstallString key. I don't think it's a bug in `Argv-ToString` per say as it's just escaping an already escaped command line but there's no sane way to detect this. So we should just not escape values from the `UninstallString` property.

I was looking at some examples on my test host and I found the value in this string is typically;

* Just the path to the uninstall executable that may **or** may not be quoted
* A path to the uninstall executable with extra arguments added to the end that is quoted if needed
* A string that starts with `MsiExec.exe` but we already handle this scenario

Considering this value is used by the Control Panel interface to uninstall a program manually I would be happy to just use these values as they are. The only exception to this rule would be the first scenario where the value is just the path to an executable and is not quoted. We would have to do something like the following to make sure it is quoted.

```
if (Test-Path -LiteralPath $UninstallString -ItemType Leaf) {
    $UninstallString = "`"$UninstallString`""
}
```

This checks if the raw value is just the path to a file and we manually quote it if that's true. It shouldn't be true for an already quoted path as `"` is not a valid char for a filepath.

We would still need to escape `arguments` passed in from Ansible if it's a list but the value returned from here is just appended to the `UninstallString` value.

On a side note, when looking at the packages I had installed I found a few of them had a registry property `QuietUninstallString`. This had the actual arguments required to silently uninstall a package which would be quote useful for `win_package`. It would be a good idea to check for that value and use that instead if `arguments` has not already been provided by the user. This allows us to maintain backwards compatibility when someone has manually specified the uninstall arguments vs someone who just specified the package_id.

**Comment by doxxx** [comment]
I agree with @jborean93, this is not the right fix. Essentially, we want to take the uninstall string and execute it as-is. Probably the easiest way to do that would be to use:

```powershell
Invoke-Expression "& $UninstallString"
```

**Comment by jborean93** [comment]
We do not want to do `Invoke-Expression` to call an executable, we have a module util that is designed to run executables.

**Comment by jborean93** [comment]
The PR https://github.com/ansible/ansible/pull/66931 improves the uninstall string checking in the registry to handle paths that are quoted. It is not able to handle paths that are;

* Path to an executable that is not quoted (but needs to be)
* Path to an executable that is quoted
* Path to an executable that is not quoted and has additional arguments
* Path to an executable that is quoted and has additional arguments
* All of the above but the path contains env vars like `%SystemRoot%`

When implementing the above I found all of those use cases on my system so hopefully that covers the majority out there.

**Pull request closed without merging**
