### PR TITLE
Added test cases for lineinfile.

### PR DESCRIPTION
**Pull request by dorfsmay**
Created test cases for lineinfile. I have added splitting TestRunner.py to my todo list, but I've got a few other things I want to add first.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!

I think we have some test functions to generate paths in the input and output path, that we could use.

Also my preference is that we could break this up into more than one testing function that described the test

test_lineinfile_insert_before_regex etc

**Comment by dorfsmay** [comment]
> I think we have some test functions to generate paths in the input and output
> path, that we could use.

Ah! I see them now. I'll change my code.

What is the "test_data" directory? Is it for test artifacts? Or where we 
should store our test data?

> Also my preference is that we could break this up into more than one testing
> function that described the test
> 
> test_lineinfile_insert_before_regex etc

All the tests for the other modules are organised with one function per 
module, with a bunch of test cases within that function.

What are you looking for here? One function per test? So adding 9 functions?

**Comment by dorfsmay** [comment]
I have modified it to use the _get_test and _get_stage methods. I cannot split them in several functions, because the tests rely on being run in order. I haven't used nose before, but I know that the default python unittest doesn't guarantee the order in which it runs the test methods, and from what I can tell, it runs them in alphabetical order.

**Comment by mpdehaan** [comment]
tests shouldn't require being run in order.  You should write them so they don't have to be.

**Comment by mpdehaan** [comment]
ok, understand what you were saying there, that's fine, testing now...

**Comment by mpdehaan** [comment]
merged in, pushing shortly, thanks!

**Pull request closed without merging**
