### PR TITLE
openssl_pkcs12: privatekey_path and friendly_name are not always required together

### LINKED ISSUE #51703: openssl_pkcs12: cannot create archive without a private key
##### SUMMARY
When attempting to create a pkcs12 archive to use as a java truststore, I am unable to do so without the private key.

Looking at the documentation, I don't think that this is an intended use, so this may be more in the realm of a feature request.

##### ISSUE TYPE
- Bug Report
- Feature Request

##### COMPONENT NAME
`openssl_pkcs12`

##### ANSIBLE VERSION

```paste below
2.7.4
```

##### STEPS TO REPRODUCE
```yaml
    - name: Generate pkcs12 formatted truststore
      openssl_pkcs12:
        action: export
        path: "/tmp/truststore.p12"
        friendly_name: "Sampletruststore"
        ca_certificates: "/tmp/ca.pem"
        passphrase: "password"
```

##### EXPECTED RESULTS
A pkcs12-formatted truststore with the included certificate authority would exist at `/tmp/truststore.p12`.

##### ACTUAL RESULTS
It errors out with this, when the `friendly_name` parameter is included.
```paste below
"parameters are required together: privatekey_path, friendly_name"
```

Then with `friendly_name` removed, I receive the following:
```
"Friendly_name is required"
```

### PR DESCRIPTION
**Pull request by Shaps**
##### SUMMARY
Removed the privatekey_path -> friendly_name constraint, as there are cases where they are not both required.

Added updated openssl_pkcs12 integration tests to be in line with other openssl_* modules; 
Added test for exporting a file with no private key. 

Fixes #51703 and Issue 1 in #46047

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssl_pkcs12

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
Looks good! You need a changelog fragment, though :)

**Review by felixfontein — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
shipit

**Comment by gundalow** [comment]
@Shaps @felixfontein Thank you. Merged into `devel`

**Comment by felixfontein** [comment]
@Shaps thanks for fixing this!
@gundalow thanks for merging!

**Pull request merged**
