### PR TITLE
Update sl_vm.py

### PR DESCRIPTION
**Pull request by bankabanka**
Updated the list of datacenters to include new datacenters.

+label: docsite_pr

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
`lib/ansible/modules/cloud/softlayer/sl_vm.py`

##### ANSIBLE VERSION

```
2.7
```

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by bankabanka** [comment]
@mcltn what would be the timeframe to get this merged?

**Comment by gundalow** [comment]
@mcltn Hi, could you please review this. Thanks in advance

**Review by mcltn — APPROVED** [review]
Thanks for adding these. We should look into getting this list form the API as well for future datacenters.

**Comment by gundalow** [comment]
@bankabanka Thank you for this PR, your first I believe.

It does take us a while to get these review and merged, though that's now been done, thanks to @mcltn 

Backport so we updates the docs in 2.7 will be done via https://github.com/ansible/ansible/pull/46109

Thanks again!

**Pull request merged**
