### PR TITLE
Allow deleting all values of LDAP attribute

### PR DESCRIPTION
**Pull request by kwohlfahrt**
Allows specifying no values, to delete an attribute completely.

##### SUMMARY
Allows deleting an attribute completely, without knowing its current value. In my case, I wanted to ensure `olcRootDN` and `olcRootPW` were removed from a DB config.

This is done by not specifying a `value` for the attribute, in combination with `state: absent`.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ldap_attr module

##### ANSIBLE VERSION
```
ansible 2.5.0
```

##### ADDITIONAL INFORMATION

As an aside, I'm not sure `compare_s` can raise `ldap.NO_SUCH_ATTRIBUTE`, at least I wasn't able to make it do so [[ref](https://www.ldap.com/the-ldap-compare-operation)].

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
@jtyr could you please comment on this?

**Comment by jtyr** [comment]
I went quickly through the code and have noticed that you make the `values` parameter optional but you don't check if it's set for the `state` which requires it. Please could you add such check?

**Comment by kwohlfahrt** [comment]
This check was in `LdapAttr.__init__`, which checked that the state is absent if the values is None. 

It was strange that the state is set in this `__init__`, but then never used (instead, the state is checked again in `main()` and used to select the appropriate method). I have moved the check to the `add` and `exact` methods instead, and removed the redundant attribute. This removes a possible error if the wrong method is called.

**Comment by kwohlfahrt** [comment]
@jtyr are there any other issues?

**Comment by kwohlfahrt** [comment]
I am closing the PR, as it seems the functionality has been implemented for some time. There is a small bug in the documentation - it suggests that `values: ""`, deletes an attribute, this should be `values: []`.

**Pull request closed without merging**
