### PR TITLE
Add nonunique option to user module, translating to the -o/--non-unique ...

### PR DESCRIPTION
**Pull request by srgvg**
Add nonunique option to user module, translating to the -o/--non-unique option to useradd and usermod.

I tested this on Linux (Ubuntu). I'm not 100% sure if the OS specific subclasses should be implemented in the same way though.

### CODE REVIEW

**Comment by rrtj3** [comment]
Looks good for Solaris.

**Comment by mpdehaan** [comment]
This parameter should be named non_unique, other than that, it looks totally fine to me.   update it and I'll merge it in. Thanks!

**Comment by srgvg** [comment]
option renamed

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
