### PR TITLE
Fix version comparison

### LINKED ISSUE #17495: docker-py version is checked incorrectly
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker integration (but not the docker module) (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/docker_common.py#L154)
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

OS X, El Cap
##### SUMMARY

docker-py just bumped its version to `1.10`. This is the code that checks the version:

```
  154         if docker_version < MIN_DOCKER_VERSION:
  155             self.fail("Error: docker-py version is %s. Minimum version required is %s." % (docker_version,
  156      
```

This is how python compares strings:

```
>>> "1.5" < "1.7"
True
>>> "1.9" < "1.7"
False
>>> "1.10.1" < "1.7"
True
>>> "1.10.1" < "1.7.0"
True
>>> "1.10" < "1.7.0"
True

```
##### STEPS TO REPRODUCE

1. Install latest docker-py on target machine.
2. Run any docker command: 

```
docker_service:
   ...
```
##### EXPECTED RESULTS

Run docker
##### ACTUAL RESULTS

```
fatal: [demos]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.1. Minimum version required is 1.7.0."}
```

### PR DESCRIPTION
**Pull request by chouseknecht**
##### ISSUE TYPE

Bugfix Pull Request
##### COMPONENT NAME

docker_common.py 
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 39aa740531) last updated 2016/09/10 03:03:19 (GMT -400)
  lib/ansible/modules/core: (detached HEAD bf5b3de83e) last updated 2016/09/09 21:43:17 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f83aa9fff3) last updated 2016/09/09 21:43:17 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fixes #17495 
- Use LooseVersion to check min version 
- Default docker_api_version to 'auto' which causes client to match server version.

### CODE REVIEW

**Comment by Navdeepuniyal** [comment]
Do not change the Default docker_api_version to 'auto', using LooseVersion only will resolve the issue.

**Comment by awartoft** [comment]
When will this be released ?

**Comment by mcwayliffe** [comment]
Would be nice to see this merged into 2.1 stable.

**Comment by jaccoh** [comment]
Why wasnt this merged into 2.1.2.0?

**Comment by gesellix** [comment]
still fails for me with Ansible 2.1.2.0.

**Pull request merged**
