### PR TITLE
Fix os_coe_cluster id/uuid retrieval

### PR DESCRIPTION
**Pull request by brtkwr**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

os_coe_cluster

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@sshnaidm Do you think we should move this PR to https://opendev.org/openstack/ansible-collections-openstack? Thanks.

**Comment by sshnaidm** [comment]
> @sshnaidm Do you think we should move this PR to https://opendev.org/openstack/ansible-collections-openstack? Thanks.

Yes, please, it would be great.

**Comment by Akasurde** [comment]
@brtknr Could you please raise a PR against opendev.org/openstack/ansible-collections-openstack? Thanks. You can check general openstack development guidelines [here](https://docs.openstack.org/infra/manual/developers.html)

needs_info

**Review by Akasurde — CHANGES_REQUESTED** [review]
As per last comment.

**Comment by brtknr** [comment]
Ok I have uploaded a PS to opendev: https://review.opendev.org/#/c/709734/. Closing this.

**Pull request closed without merging**
