### PR TITLE
[WIP] Add `Get-WMIObject Win32_Product` trick to docs

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

win_package

##### ANSIBLE VERSION

v2.3

##### SUMMARY

More simple way to get product id's from Windows. Life-saver !

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Probably fine for well behaved installers but looks like it can cause reconfiguration calls for everything you have installed: https://gregramsey.net/2012/02/20/win32_product-is-evil/

**Comment by trondhindenes** [comment]
I consider the "Win32_Product is evil" thing to be a bit of an edge case. As far as I know, Win32_Product is still the "official" way to enumerate software installed on the local computer. I don't see any problems adding this to docs. There will always be edge cases (and crappy software installers) but it shouldn't be Ansible's job to especially cater for these. imho.

**Comment by trondhindenes** [comment]
lgtm

**Comment by jhawkesworth** [comment]
Fair enough, I don't want to downvote, could always elaborate the docs if it starts to cause issues.

I would have merged but abadger1999 pointed out that this is 'core' in meta so I'll leave it to @nitzmahone for final say.

**Comment by dagwieers** [comment]
Hold off for now, I noticed the other day that the Id's I copied did not work and was different in the Windows Registry, so I am not sure this advice (I read on one of the tickets) is 100% correct. Or maybe I simply mis-copy&pasted it.

And I think I want this to an additional not with some more background.

**Comment by trondhindenes** [comment]
I came up with this snippet instead, should be short enough to fit in the documentation:

`ls "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\"| ForEach-Object {$obj = "" | select id, name;$obj.name = $_.GetValue("DisplayName");$obj.Id=$_.PsChildName;$obj}`

**Comment by trondhindenes** [comment]
@dagwieers I think we either should close this PR or update it with the snippet, as far as I can see it's the most correct way of getting the actual id's that win_package needs. I also am getting mixed result from wmi.

**Pull request closed without merging**
