### PR TITLE
Add an only_if option to vars_prompt to make prompts conditional

### PR DESCRIPTION
**Pull request by dagwieers**
Sometimes you may want to allow variables through host_vars or inventory, but prompt for a value if it is not set or if the value does not conform to something specific. This option allows you to specify when you want to offer a prompt.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you share what this would look like in a playbook?

**Comment by dagwieers** [comment]
This is a real-world sample of our example. We have 4 modules: esx_facts, ilo_facts, esx_boot and ilo_boot. The first two provide us important information about the system (uuid, macaddress). The second two allow us to boot our own media (ISO or PXE). We generate a custom ISO, kickstart files and pxelinux info in separate tasks but for brevity I omitted chunks.

Based on inventory information coming from an enterprise Configuration Management Database (cmdb) we decide which tasks are being run, but this should also be reflected in the passwords we ask on the command line. For security reasons we cannot hardcode password information.

``` yaml
  vars_prompt:
    - name: esxpassword
      prompt: "Enter password for ${esxlogin}"
      private: True
      only_if: "'${cmdb_hwtype}'.startswith('VMWare ')"
    - name: ilopassword
      prompt: "Enter password for ${ilologin}"
      private: True
      only_if: "'${cmdb_hwtype}'.startswith('HP ')"

  tasks:
  ### Get iLO facts
  - local_action: ilo_facts hostname='${cmdb_ilo_address}' login='${ilologin}' password='${ilopassword}' match='${inventory_hostname_short}'
    only_if: " ( '${cmdb_status}' == 'to-be-staged' and '${cmdb_model}'.startswith('HP ') )"

  ### Get ESX facts
  - local_action: esx_facts hostname='${cmdb_esx_address}' login='${esxlogin}' password='${esxpassword}' vmname='${inventory_hostname_short}'
    only_if: " ( '${cmdb_status}' == 'to-be-staged' and '${cmdb_model}'.startswith('VMWare ') )"
```

If we could make play's conditional, it would make our lives easier, since we could make a separate play for each installation methode (ESX or iLO, in the future maybe KVM or hyperv).

**Comment by dagwieers** [comment]
Maybe a more simple example to show this particular use-case is:

``` yaml
vars_prompt:
  - name: ipaddress
    prompt: "Enter ipaddress for ${inventory_hostname_short}"
    only_if: "not is_set('${ipaddress}')"
```

When ipaddress is not set by host_vars/hostname, prompt for it.

**Comment by mpdehaan** [comment]
Yeah /true/ conditional plays are problematic unless it was just a
shorthand to add an implied only_if to every task and vars_prompt.   I'm
not against that.  The output might look a little gross, but it would
work.    It would just be syntactic sugar more or less.

Unrelated code thing -- I'd like to see the duplication of "is_set"
eliminated between here and elsewhere, how about an eval function in utils
that always adds it where we can share between the two?

--Michael

**Comment by dagwieers** [comment]
I suggested this earlier (above), so if you say "go", I will update the feature branch.

**Comment by mpdehaan** [comment]
Nice example.

Unrelated, and not neccessarily needing to be part of this, I am also kinda
wondering if we should have a "only_if_unset" ... as if 'isset' is a common
pattern, which it seems to be, this might be nice:

only_if_set: $ipaddress
only_if_unset: $ipaddress

Not just here, but also in the normal case.   I kinda hate the look of the
raw python in the otherwise mostly clean YAML where we can avoid it.

It's kind of boilerplate that I can't actually remember, which makes it
something I think we should strive to reduce.

**Comment by dagwieers** [comment]
I do want to have conditional plays, especially for my first use-case although I think it would be better if tasks/plays are not shown if that particular task/play does not have any hosts associated with it. Which is typical in our case when we provision a single machine (or e.g. 5 VMware systems), however I can see how this can confuse people.

**Comment by dagwieers** [comment]
Problem is that only_if_set and only_if_unset do not cover all use-cases, and as such will not replace only_if. So I think it's not a good idea to complicate things even more.

```
only_if: "is_set('${ipaddress}')"
```

Is not _that_ ugly. But I don't like the use of quoting above and would prefer:

```
only_if: is_set(${ipaddress))
```

Or even

```
only_if: is_set($ipaddress)
```

Couldn't we add quotes automatically to "${...}" sequences if it is a string or something like that ?

**Comment by mpdehaan** [comment]
Less directives sounds good.

I agree about quoting too -- if we can do that in a backwards compatible way, I would definitely take a patch to make quoting less required with only_if.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
