### PR TITLE
Inventory hostname patterns can be alpha ranges, e.g. host[a:f].

### PR DESCRIPTION
**Pull request by njharman**
Updated docs, tests.

### CODE REVIEW

**Comment by mpdehaan** [comment]
since this is now doing ascii enumeration, have you tested to make sure it can still do host[0:100] ?

Reading over the code it looks like this _may_ not be handled, and the tests before are only testing small ranges of hosts, so we would want something that assured crossing the single to multi-digit barrier still worked, and also that 0 prefixing still worked.

**Comment by njharman** [comment]
There's actually two code paths, one for alpha and one for numbers. I believe there is a zero prefixing test. I'll check, add multi digit, and resubmit pull request on Monday.

**Comment by mpdehaan** [comment]
Good deal!

-- Michael

**Comment by njharman** [comment]
Gonna (try to) squash commits and request new pull

**Pull request closed without merging**
