### PR TITLE
Factor primitives for F5 modules

### PR DESCRIPTION
**Pull request by Etienne-Carriere**
Factor the standard elements for all F5 Big IP modules : 
- F5 standard arguments 
- F5 login method

### CODE REVIEW

**Comment by srgvg** [comment]
cc @mhite

**Comment by mhite** [comment]
Presuming this is preparation work for moving common elements into a shared library now that Ansible supports it?

**Comment by Etienne-Carriere** [comment]
My only small goal was to factor login functions for F5 . I am not aware of shared library concept in Ansible . Do you have an example that I can use as an example ? 

Thanks

**Comment by Etienne-Carriere** [comment]
Yes, I plan to factor, in a first phase, the login phase and the associated parameters. Perhaps there will be more elements to factor in the future

**Pull request merged**
