### PR TITLE
Small fix from "installed" to "present"

### PR DESCRIPTION
**Pull request by AgileinOrange**
Testing a small commit, but it is a real change.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

N/A
##### ADDITIONAL INFORMATION
First, pull request, hope it works...

```paste below

```

### CODE REVIEW

**Comment by caphrim007** [comment]
@wojtek0806 please review this with the f5-networks repo code and advise on changes.

**Comment by wojtek0806** [comment]
@HerontheCLI I would like the changes done to the F5 module reverted back as they are not inappropriate to the module function. Present and Installed states have two distinct functionalities for that module and that change would break stable interface.

**Comment by dagwieers** [comment]
For swdepot, this is already taken care of in #51106

**Review by gundalow — DISMISSED** [review]
Hi @HerontheCLI Thanks for this PR

Could you please revert the changes to
lib/ansible/modules/network/f5
lib/ansible/modules/packaging/os/swdepot.py

**Comment by acozine** [comment]
Looks like that Windows module actually does not use `state: present` - see https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_updates.py and https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_updates.ps1#L16.

**Pull request merged**
