### PR TITLE
allow for vault enterprise namespaces

### PR DESCRIPTION
**Pull request by drewmullen**
SUMMARY
vault included a namespace feature for Enterprise users to segment vault into 'mini vaults'. this feature allows users to include a namespace in a hashi_vault lookup() call.

design:
pass namespace as parameter to Client class object, gets included as a header

users must upgrade to latest hvac, 0.7.0 and vault 0.11+ enterprise. to avoid issues, we test to see if namespace was passed as a param; if it has been, include it in the hvac Client object creation, if its not passed, do not include. if param is passed and user doesnt meet requirements, AnsibleError is thrown

ISSUE TYPE
Feature Pull Request

COMPONENT NAME
hashi_vault

### CODE REVIEW

**Comment by drewmullen** [comment]
@abadger any idea why im getting a failure here? https://github.com/ansible/ansible/commit/748ea39ecd99bcb476dc460bfdd054567ef2bfc6
`"msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."`


@smueller18 same question https://github.com/ansible/ansible/commit/00bab2d24d398844afaf8d6756c5e7a15bbc56cc

`docker.errors.APIError: 500 Server Error: Internal Server Error ("failed to allocate gateway (172.3.28.2): Address already in use")`

**Comment by smueller18** [comment]
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("failed to allocate gateway (172.3.28.2): Address already in use")
```
This is a weird behaviour. I checked many full builds in the last days, but It seems that this error in your CI build is an outlier. Earlier and later builds have no errors with the docker_network tests. I know too less about the underlaying CI build system and have no idea how I could debug the given szenario. But according to the build logs, an exclusive docker hosts is provisioned for testing docker_network module. So I cannot imagine why the network address should already be in use. Maybe @felixfontein or @DBendit have some hints?

**Comment by felixfontein** [comment]
CC @mattclay as he knows a lot more about the CI system.

@smueller18 I think this can only happen in one of two instances:

1. An earlier run of the test died and the network wasn't cleaned up; this should only happen in case the test run was interrupted (or the instance of the `docker_network` module used was horribly broken, but there hasn't been any such change to it recently) so that the test role didn't finish (it contains cleanup code). I don't know what happens if running tests are cancelled;

   @mattclay is it possible that cancelling interrupts the role and doesn't run cleanup? And if that happens, is it possible that the same CI node is used for another test (without "cleaning up" docker in some way first)?

2. Two `docker_network` tests are running on the same CI node simulatenously, or are somehow else using the same docker daemon. @mattclay is this possible?

**Comment by felixfontein** [comment]
About the SQL problem: I think someone already mentioned this on #ansible-devel (just looked it up: @drewmullen on Dec 27, what a surprise :-) ). The problem seems to be related to `"ERROR: Test target "mysql_db" has changed the test environment!"` at the end of the log:
```
10:09      "program_versions": {
10:09          "": [
10:09 -            "3.7.1 (default, Nov  5 2018, 14:07:04)",
10:09 -            "[GCC 8.2.1 20181011 (Red Hat 8.2.1-4)]",
10:09 -            "pip 18.0 from /usr/lib/python3.7/site-packages/pip"
10:09 +            "2.7.15 (default, Oct 15 2018, 15:26:09)",
10:09 +            "[GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]",
10:09 +            "pip 18.1 from /usr/lib/python2.7/site-packages/pip"
10:09 +        ],
```
Considering that `setup_mysql_db` installes `python3-PyMySQL` since it detects Python 3, which does not provide PyMySQL for Python 2 (which maybe is the interpreter used?!), this could be the cause for this problem.

**Comment by felixfontein** [comment]
Ok, I debugged the MySQL problem a bit more. Installing `mariadb-server` on Fedora 29 seems to install Python 2 **and makes it the default Python interpreter!** That seems to screw up the test. (Does `setup_mysql_db` has to be marked as `destructive`? Won't fix this problem, though...)

I guess this problem has been "introduced" in 6a09db51311f0557a783ca80c3c1b8e260998a60 (#49634) when `fedora25` was replaced by `fedora29` (until including `fedora28`, the default Python seems to have been Python 2) (CC @jborean93). No idea why this wasn't a problem back then, though... Maybe the `mariadb-server` package changed since then? (There was a change to the package on [Dec 10](https://apps.fedoraproject.org/packages/mariadb-server/changelog), but it doesn't look related.) Someone who knows more about Fedora might be able to find out more, or have an idea how to fix this :)

**Comment by felixfontein** [comment]
There's issue #50386 to track the MySQL problems. Also, the mysql_db tests are now marked as unstable, so they shouldn't cause failures anymore.

(CC @gundalow)

**Comment by felixfontein** [comment]
The mysql_user and mysql_variables tests have been disabled as well. Maybe you're lucky if you trigger a re-run of the tests now.

**Comment by drewmullen** [comment]
ive got to close this and reopen it... never initially branched from devel so i have no way to catch up on the new commits to rebase my change

**Pull request closed without merging**
