### PR TITLE
Included firmware component ID in get_firmware_inventory()

### PR DESCRIPTION
**Pull request by prabhakarpujeri**
##### SUMMARY
this patch includes firmware inventory component ID. which is unique to each component.
this ID will help in parsing firmware for example 
Dell publish firmware release catalog http://downloads.dell.com/catalog/Catalog.xml.gz  and firmware id will help in checking latest firmware in dell.com 
 
output with this patch
{
                        "Id": "Installed-159-1.6.8",
                        "Name": "BIOS",
                        "Version": "1.6.8"
},

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/remote_management/redfish

ANSIBLE VERSION
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 18:36:25) [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]

### CODE REVIEW

**Comment by jose-delarosa** [comment]
This if from my colleague, I'll take a look.

**Comment by jose-delarosa** [comment]
@prabhakarpujeri, I tested the patch, looks OK, but can you please rearrange the dict entries so they look like this:
```
...
{
   "Name": "BIOS",
   "Version": "1.6.8",
   "Id": "Installed-159-1.6.8"
},
{
   "Name": "Power Supply.Slot.2",
   "Version": "00.1B.53",
   "Id": "Installed-101094-00.1B.53"
},
...
```
Having the name first will make it easier to spot an entry when looking at the JSON output.

Thanks.

**Comment by prabhakarpujeri** [comment]
@jose-delarosa  json key and value  are sorted  automatically. i don't know how to do that

**Comment by jose-delarosa** [comment]
@billdodd @tomasg2012 Can you verify if other OEMs have the Id entry too? Or for that matter, can you verify if this [playbook](https://github.com/dell/redfish-ansible-module/blob/master/playbooks/inventory/get_firmware_inventory.yml) is vendor-agnostic? Would like to know before applying a patch that might be OEM-specific.

**Comment by billdodd** [comment]
@jose-delarosa The "Id" property is typical and common in resources like this that are members of a resource collection. But it isn't a required property. So I think it is good and valuable to include it in the output if present, but be sure to not get a KeyError exception if it isn't present.

And similarly for the "Version" property - it is typical to be present, but not required.

For both of those properties, should check for presence before referencing. Or do something like a get() with a default value like `data.get('Id', 'N/A')` and `data.get('Version', 'N/A')` .

**Comment by jose-delarosa** [comment]
@prabhakarpujeri To be consistent with the other functions, perhaps something like this (only relevant code included):
```
    firmware_results = []
    properties = ['Id', 'Name', 'Version']

    for device in data[u'Members']:
        firmware = {}
        ...
        if "Installed" in d:
            ...
            for property in properties:
                if property in data:
                    firmware[property] = data[property]
            firmware_results.append(firmware)
    result["entries"] = firmware_results
```
This adds more code, but checks to make sure Key exists before trying to retrieve it. Or can do what Bill suggested.

**Comment by gundalow** [comment]
bot_status

**Comment by jose-delarosa** [comment]
@prabhakarpujeri Please let us know if you are planning on resubmitting with suggestions. Those updates need to be made anyway (check to verify if properties Key exists), so let me know if you want to do them, else I can submit at a later point. Thank you for your submission.

**Comment by abadger** [comment]
needs_revision
needs_info

**Comment by samerhaj** [comment]
Please note that "Id", while a standard property, the value is very OEM specific and should not be used by common code other than for display purposes. The current code is using "Id" to filter installed FW components. We opened an issue on this (See #49832 )

So we will need more than "Id" to display proper FW Inventory.  Suggest including "SoftwareId" and "Status.State" properties in the output since those are key in identifying the FW component, per the standard schema definition.

**Comment by billdodd** [comment]
Assuming folks are happy with my PR #51028 for issue #49832, I don't think this PR (#47490) is needed any longer.

**Comment by samerhaj** [comment]
Thanks @billdodd. I just reviewed PR #51028 and it looks good! I think we can discard this PR

**Comment by jose-delarosa** [comment]
@prabhakarpujeri, can you please close this PR, follow https://github.com/ansible/ansible/pull/51028 and go from there? Thank you for your contribution.

**Comment by prabhakarpujeri** [comment]
closing this PR

**Pull request closed without merging**
