### PR TITLE
add a member to team_mysql

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add me to team_mysql

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by pratikgadiya12** [comment]
shipit

**Comment by Andersson007** [comment]
@bmalynovytch is it OK for you?

**Comment by bmalynovytch** [comment]
> @bmalynovytch is it OK for you?

Sorry I missed the notification in time

**Comment by Andersson007** [comment]
@bmalynovytch, nps :)

**Pull request merged**
