### PR TITLE
lineinfile work

### PR DESCRIPTION
**Pull request by Tinche**
Reworked the lineinfile module slightly, adding the backrefs parameter to explicitly enable the use of backreferences. Additional unit tests and documentation.

### CODE REVIEW

**Comment by mpdehaan** [comment]
thanks for resubmitting this, much appreciated!   Testing shortly.

**Comment by Tinche** [comment]
Any specific issues holding this up that I can address?

**Comment by mpdehaan** [comment]
Working on many things (primarily ansible commander!), if something is not instantly merged, it is not neccessarily a sign of anything :)

Testing now, thanks!

**Comment by mpdehaan** [comment]
merged in, thanks very much!

BTW, if you can, please don't reformat code in future commits -- it breaks git history attribution for one.   I let it go here since I wanted the fix, so just something for next time.

Once again, thanks for the fix on this and the extra docs/tests!

**Comment by Tinche** [comment]
Sorry about that, I'll keep it in mind in the future.

**Pull request merged**
