### PR TITLE
Broken link fixed.

### LINKED ISSUE #51433: Broken Link in intro_dynamic_inventory.html
##### SUMMARY
Link on [intro_dynamic_inventory.html](https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html) is broken.

image

##### ISSUE TYPE
- Documentation Report

##### OS / ENVIRONMENT
Browser: Chrome 71

### PR DESCRIPTION
**Pull request by sbulage**
##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by sbulage** [comment]
@acozine FYI.

**Comment by sbulage** [comment]
@acozine you can review and merge it.

**Comment by sbulage** [comment]
@acozine review please

**Comment by acozine** [comment]
Thanks @sbulage!

**Pull request merged**
