### PR TITLE
Removes modules from TOC, speeding up build time and reducing doc dis…

### PR DESCRIPTION
**Pull request by dharmabumstead**
…k space requirements.

##### SUMMARY

Removes the module topics from the TOC. This dramatically reduces build time (from >2 hours to under 8 minutes on my Macbook Pro) and disk space. This PR also restores links to the module maintenance topic in the user guide.

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by dharmabumstead** [comment]
This should fix https://github.com/ansible/ansible/issues/38288

**Comment by dharmabumstead** [comment]
screen shot 2018-04-04 at 8 09 27 pm
screen shot 2018-04-04 at 8 08 44 pm

**Comment by abadger** [comment]
Looks good to me.  Merged to devel!  Thanks @dharmabumstead, awesome work!

**Comment by timlnx** [comment]
Nice!

**Pull request merged**
