### PR TITLE
Update vendored distro

### LINKED ISSUE #77928: Failed to get Debian minor version
### Summary

This is a follow up to issue #74481, which was closed, but the fix doesn't address the problem described in this issues.
Here a  (slightly modified) copy of my comment on the above issue:

PR #74721 doesn't solve the problem reported in issue #74481.
This PR adds a new `ansible_distribution_minor_version` fact.
But issue #74481 is about the `ansible_distribution_version` fact sometimes doesn't include the minor version.

Here a list of `ansible_distribution_version` facts gathered for my Debian hosts:
6.0.8
7.6
7.7
7.11
8
8.2
8.10
8.11
9.6
9.12
9.13
10
11

You see that for Debian 8 `ansible_distribution_version` is sometimes with and without the minor version.
From Debian 10 the fact doesn't include the minor version.

For CentOS `ansible_distribution_version` always include the minor version:
7.4
7.5
7.6
7.8
7.9
8.3
8.4
8.5

To make `ansible_distribution_version` consistent between distributions the minor version should be added to this fact for Debian hosts.

### Issue Type

Bug Report

### Component Name

lib/ansible/modules/setup.py

### Ansible Version

```console
ansible [core 2.12.6]
```

### Configuration

```console
NA
```

### OS / Environment

Debian

### Steps to Reproduce

NA

### Expected Results

NA

### Actual Results

```console
NA
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by netsandbox**
##### SUMMARY

Update vendored distro

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/distro/_distro.py

##### ADDITIONAL INFORMATION

While distro 1.7.0 [dropped Python 2.7 support](https://github.com/python-distro/distro/blob/master/CHANGELOG.md#170-20220215), they still maintain a `python2.7-support` branch, where they back port selected changes.

The vendored distro can be updated with:

```shell
curl https://raw.githubusercontent.com/python-distro/distro/python2.7-support/distro.py \
  -o lib/ansible/module_utils/distro/_distro.py
```

Fixes #77928

### CODE REVIEW

**Comment by sivel** [comment]
We maintain our own set of changes on top of upstream distro.  Here are those changes against 1.6.0 that should be replicated into our vendored copy:

<details>
<summary>Patch...</summary>
<p>

```diff
--- distro.py	2022-10-26 12:13:35.000000000 -0500
+++ _distro.py	2022-10-25 15:52:27.000000000 -0500
@@ -11,6 +11,10 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
+#
+# A local copy of the license can be found in licenses/Apache-License.txt
+#
+# Modifications to this code have been made by Ansible Project
 
 """
 The ``distro`` package (``distro`` stands for Linux Distribution) provides
@@ -27,8 +31,6 @@
 <https://bugs.python.org/issue1322>`_ for more information.
 """
 
-import argparse
-import json
 import logging
 import os
 import re
@@ -85,6 +87,7 @@
 #: * Value: Normalized value.
 NORMALIZED_OS_ID = {
     "ol": "oracle",  # Oracle Linux
+    "opensuse-leap": "opensuse",  # Newer versions of OpenSuSE report as opensuse-leap
 }
 
 #: Translation table for normalizing the "Distributor ID" attribute returned by
@@ -133,6 +136,56 @@
 )
 
 
+#
+# Python 2.6 does not have subprocess.check_output so replicate it here
+#
+def _my_check_output(*popenargs, **kwargs):
+    r"""Run command with arguments and return its output as a byte string.
+
+    If the exit code was non-zero it raises a CalledProcessError.  The
+    CalledProcessError object will have the return code in the returncode
+    attribute and output in the output attribute.
+
+    The arguments are the same as for the Popen constructor.  Example:
+
+    >>> check_output(["ls", "-l", "/dev/null"])
+    'crw-rw-rw- 1 root root 1, 3 Oct 18  2007 /dev/null\n'
+
+    The stdout argument is not allowed as it is used internally.
+    To capture standard error in the result, use stderr=STDOUT.
+
+    >>> check_output(["/bin/sh", "-c",
+    ...               "ls -l non_existent_file ; exit 0"],
+    ...              stderr=STDOUT)
+    'ls: non_existent_file: No such file or directory\n'
+
+    This is a backport of Python-2.7's check output to Python-2.6
+    """
+    if 'stdout' in kwargs:
+        raise ValueError(
+            'stdout argument not allowed, it will be overridden.'
+        )
+    process = subprocess.Popen(
+        stdout=subprocess.PIPE, *popenargs, **kwargs
+    )
+    output, unused_err = process.communicate()
+    retcode = process.poll()
+    if retcode:
+        cmd = kwargs.get("args")
+        if cmd is None:
+            cmd = popenargs[0]
+        # Deviation from Python-2.7: Python-2.6's CalledProcessError does not
+        # have an argument for the stdout so simply omit it.
+        raise subprocess.CalledProcessError(retcode, cmd)
+    return output
+
+
+try:
+    _check_output = subprocess.check_output
+except AttributeError:
+    _check_output = _my_check_output
+
+
 def linux_distribution(full_distribution_name=True):
     # type: (bool) -> Tuple[str, str, str]
     """
@@ -628,7 +681,7 @@
 
         def __get__(self, obj, owner):
             # type: (Any, Type[Any]) -> Any
-            assert obj is not None, "call {} on an instance".format(self._fname)
+            assert obj is not None, "call {0} on an instance".format(self._fname)
             ret = obj.__dict__[self._fname] = self._f(obj)
             return ret
 
@@ -1145,7 +1198,7 @@
         with open(os.devnull, "wb") as devnull:
             try:
                 cmd = ("lsb_release", "-a")
-                stdout = subprocess.check_output(cmd, stderr=devnull)
+                stdout = _check_output(cmd, stderr=devnull)
             # Command not found or lsb_release returned error
             except (OSError, subprocess.CalledProcessError):
                 return {}
@@ -1183,7 +1236,7 @@
         with open(os.devnull, "wb") as devnull:
             try:
                 cmd = ("uname", "-rs")
-                stdout = subprocess.check_output(cmd, stderr=devnull)
+                stdout = _check_output(cmd, stderr=devnull)
             except OSError:
                 return {}
         content = self._to_str(stdout).splitlines()
@@ -1217,7 +1270,7 @@
             if isinstance(text, bytes):
                 return text.decode(encoding)
         else:
-            if isinstance(text, unicode):  # noqa
+            if isinstance(text, unicode):  # noqa pylint: disable=undefined-variable
                 return text.encode(encoding)
 
         return text
@@ -1350,36 +1403,13 @@
     logger.setLevel(logging.DEBUG)
     logger.addHandler(logging.StreamHandler(sys.stdout))
 
-    parser = argparse.ArgumentParser(description="OS distro info tool")
-    parser.add_argument(
-        "--json", "-j", help="Output in machine readable format", action="store_true"
-    )
-
-    parser.add_argument(
-        "--root-dir",
-        "-r",
-        type=str,
-        dest="root_dir",
-        help="Path to the root filesystem directory (defaults to /)",
-    )
-
-    args = parser.parse_args()
-
-    if args.root_dir:
-        dist = LinuxDistribution(
-            include_lsb=False, include_uname=False, root_dir=args.root_dir
-        )
-    else:
-        dist = _distro
+    dist = _distro
 
-    if args.json:
-        logger.info(json.dumps(dist.info(), indent=4, sort_keys=True))
-    else:
-        logger.info("Name: %s", dist.name(pretty=True))
-        distribution_version = dist.version(pretty=True)
-        logger.info("Version: %s", distribution_version)
-        distribution_codename = dist.codename()
-        logger.info("Codename: %s", distribution_codename)
+    logger.info("Name: %s", dist.name(pretty=True))
+    distribution_version = dist.version(pretty=True)
+    logger.info("Version: %s", distribution_version)
+    distribution_codename = dist.codename()
+    logger.info("Codename: %s", distribution_codename)
 
 
 if __name__ == "__main__":
```

</p>
</details>

Based on the above, it looks like `json` and `argparse` code should be removed, and since we no longer support Py2.6 we don't need the `_my_check_output` compat code.  And the shebang can be removed.  Making those adjustments, to some extent should also allow the ignores that were added to be removed, since we don't vendor an unmodified copy.

**Comment by netsandbox** [comment]
Wouldn't it be smarter and easier for future updates to add a unmodified copy?

**Comment by bcoca** [comment]
@netsandbox easier, yes, smarter .. idk, but those changes were made for a reason. For example, the shebang is removed to avoid  CI and packaging checks that would constantly rewrite it or warn about it.

**Comment by bcoca** [comment]
not sure, those are deps we already have so should not be a big issue .. just that we don't expect anyone tor un as script from there

**Comment by netsandbox** [comment]
I have now removed the shebang and the relevant test/sanity/ignore.txt line,
and also have re-added the license and modification comments.

In the commit message I have now added details about the commit of the vendored distro.

If other modifications are needed just drop me a short line.

**Review by bcoca — APPROVED** [review]

**Review by nitzmahone — APPROVED** [review]
Only thing that looks weird to me is the `amazon`->`amzn` key swap they did upstream, but at a glance it looks like we already canonicalize that elsewhere to `Amazon`, so LGTM

**Pull request merged**
