### PR TITLE
Fix ec2_instance eventual consistency when wait: false

### LINKED ISSUE #51662: ec2_instance: Instance creation faces Eventual Consistency and fails
##### SUMMARY

Sometime when using the `ec2_instance` modules, the action will fail with the following issue:

```
An exception occurred during task execution.
To see the full traceback, use -vvv.
The error was: ClientError: An error occurred (InvalidInstanceID.NotFound)
when calling the DescribeInstances operation:
The instance ID 'i-03b15aaed2b78982b' does not exist
```

This is due to https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

  - ec2_instance

##### ANSIBLE VERSION

  - devel

##### CONFIGURATION

 - N/A

##### OS / ENVIRONMENT

 - N/A

##### STEPS TO REPRODUCE

 - As it is not really ansible dependent but Amazon's it is hard to get a deterministic reproducer.

##### EXPECTED RESULTS

 - No exception, things keep working as normal

##### ACTUAL RESULTS

```
An exception occurred during task execution.
To see the full traceback, use -vvv.
The error was: ClientError: An error occurred (InvalidInstanceID.NotFound)
when calling the DescribeInstances operation:
The instance ID 'i-03b15aaed2b78982b' does not exist
```

### PR DESCRIPTION
**Pull request by Shaps**
##### SUMMARY
As very well described in #51662, when `wait: false` is specified, the module may fail because the instance ids are not yet propagated. 

Fixes #51662

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ec2_instance

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by Shaps** [comment]
cc @willthames

**Review by willthames — APPROVED** [review]

**Comment by willthames** [comment]
The code looks good, I haven't yet run the test suite though.

**Review by Spredzy — APPROVED** [review]
LGTM. Haven't had run the test either - but so far I can't reproduce the issue with this patch in.

It was flaky, so I'll update/feel a new ticket if I see it spawning, but as per the content of this PR I don't see how it can happen.

Thanks @Shaps !

**Comment by Spredzy** [comment]
shipit

**Comment by willthames** [comment]
I'm still wrestling with the test suite (there seem to be a lot of issues accumulated with the testing-policies, not blaming this individual change), I think I'm nearly there - I'll ship once this passes tests.

Thanks for confirming it fixes your issue though, that's definitely a great start!

**Comment by Shaps** [comment]
@willthames happy to fix the 2 linter issues, just let me know if you want both the `instances` and `failure_reason` to be printed out or just the reason, for this error:
```
lib/ansible/modules/cloud/amazon/ec2_instance.py:1489:33: too-many-format-args Too many arguments for format string
```
[L1489](https://github.com/ansible/ansible/blob/1b9e031030367a9a3ed1751e1b7a84389ffce4e4/lib/ansible/modules/cloud/amazon/ec2_instance.py#L1489)

**Comment by willthames** [comment]
@Shaps prefer both I think

**Pull request merged**
