### PR TITLE
Add 2 CLI options --list-tasks-json and --list-tasks-with-path

### PR DESCRIPTION
**Pull request by cquon**
##### SUMMARY
I would like to add a couple of CLI options to "ansible-playbook" to help with some integration:

Reasoning:
For some integration, we would like to have a unique way to identify every task in an ansible playbook, however, the names/action are not guaranteed to be unique across playbooks / files, but by integrating the file name and line number there will be a unique identifier.  In addition, with a JSON output it is easier to traverse than a raw string.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/cli/playbook.py
lib/ansible/executor/playbook_executor.py
lib/ansible/playbook/play.py
lib/ansible/playbook/task.py

##### ANSIBLE VERSION

```
ansible --version
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.0 (devel b94340656a) last updated 2017/04/20 17:48:37 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cquon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION
Currently there only exists a --list-tasks:

Existing Help Menu (ansible-playbook --help):
  --list-tasks          list all tasks that would be executed

Desired Help Menu:

  --list-tasks          list all tasks that would be executed
  --list-tasks-json     list all tasks that would be executed in JSON format
  --list-tasks-with-path
                        list all tasks that would be executed along with its
                        absolute path and line number

```
ansible-playbook --list-tasks playbook.yml
playbook: playbook.yml

  play #1 (localhost): This is play 1	TAGS: []
    tasks:
      common : aaa	TAGS: []
      common : bbb	TAGS: []
      common : ccc	TAGS: []
      common : ddd	TAGS: []
      common : eee	TAGS: []
      Set fact upgrade_flow as false	TAGS: []
      debug	TAGS: []
      Set fact upgrade_zones	TAGS: []

  play #2 (localhost): This is play 2	TAGS: []
...

ansible-playbook --list-tasks-with-path playbook.yml

playbook: playbook.yml

  play #1 (localhost): This is play 1	TAGS: []	PATH: /tmp/ansible/playbooks/playbook.yml:4]
    tasks:
      common : aaa	TAGS: []	PATH: [/tmp/ansible/playbooks/roles/common/tasks/main.yml:4]
      common : bbb	TAGS: []	PATH: [/tmp/ansible/playbooks/roles/common/tasks/main.yml:8]
      common : ccc	TAGS: []	PATH: [/tmp/ansible/playbooks/roles/common/tasks/main.yml:14]
      common : ddd	TAGS: []	PATH: [/tmp/ansible/playbooks/roles/common/tasks/main.yml:20]
      common : eee	TAGS: []	PATH: [/tmp/ansible/playbooks/roles/common/tasks/main.yml:26]
      Set fact upgrade_flow as false	TAGS: []	PATH: [/tmp/ansible/playbooks/aws-configure-infra-nodes.yml:15]
      debug	TAGS: []	PATH: [/tmp/ansible/playbooks/aws-configure-infra-nodes.yml:20]
      Set fact upgrade_zones	TAGS: []	PATH: [/tmp/ansible/playbooks/aws-configure-infra-nodes.yml:22]

  play #2 (localhost): This is play 2  TAGS: []	PATH: [/tmp/ansible/playbooks/playbook.yml:5]
...


ansible-playbook --list-tasks-json playbook.yml
{
  "playbook_dir": "tmp/ansible/playbooks",
  "plays": [
    {
      "tasks": [
        {
          "action": "fail",
          "_ds": {
            "_data_source": "/tmp/ansible/playbooks/roles/common/tasks/main.yml",
            "_line_number": 4
          },
          "name": "aaa",
          "tags": []
        },
        {
          "action": "set_fact",
          "_ds": {
            "_data_source": "/tmp/ansible/playbooks/roles/common/tasks/main.yml",
            "_line_number": 8
          },
          "name": "bbb",
          "tags": []
        },
        {
          "action": "set_fact",
          "_ds": {
            "_data_source": "/tmp/roles/common/tasks/main.yml",
            "_line_number": 14
          },
          "name": "ccc",
          "tags": []
        },
        {
          "action": "set_fact",
          "_ds": {
            "_data_source": "/tmp/roles/common/tasks/main.yml",
            "_line_number": 20
          },
          "name": "ddd",
          "tags": []
        },
        {
          "action": "set_fact",
          "_ds": {
            "_data_source": "/tmp/ansible/playbooks/roles/common/tasks/main.yml",
            "_line_number": 26
          },
          "name": "eee",
          "tags": []
        },
        {
          "action": "set_fact",
          "_ds": {
            "_data_source": "/tmp/ansible/playbooks/aws-configure-infra-nodes.yml",
            "_line_number": 15
          },
          "name": "Set fact upgrade_flow as false",
          "tags": []
        },
        {
          "action": "debug",
          "_ds": {
            "_data_source": "/tmp/ansible/playbooks/aws-configure-infra-nodes.yml",
            "_line_number": 20
          },
          "name": "",
          "tags": []
        },
        {
          "action": "set_fact",
          "_ds": {
            "_data_source": "/tmp/ansible/playbooks/aws-configure-infra-nodes.yml",
            "_line_number": 22
          },
          "name": "Set fact upgrade_zones",
          "tags": []
        }
      ],
      "_ds": {
        "_data_source": "/tmp/ansible/playbooks/aws-configure-infra-nodes.yml",
        "_line_number": 4
      },
      "name": "This is a master playbook to invoke all the playbooks which configure the infra nodes in aws",
      "tags": []
    },
    {
      "tasks": [
        {
         ...
        }
    ]
          "_ds": {
        "_data_source": "/tmp/playbook.ymll",
        "_line_number": 5
      },
      "name": "This is play 2",
      "tags": []
 },
...
  "playbook": "playbook.yml"
}

```

### CODE REVIEW

**Comment by bcoca** [comment]
I would prefer to not add these options, I'm looking into making the 'listing' display part of callbacks so in the future a plugin could take care of making the formating the way you want it.

**Comment by cquon** [comment]
Hi Brian,

Thanks for the input.  If you have any more detail/pointers on this is it something I can work on?  Or do you know when this plugin ability will available?

Thanks,
Corey

**Comment by bcoca** [comment]
Hopefully soon, https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst look under 'globalize callbacks'

**Comment by mattclay** [comment]
The test `ansible-test compile --python 2.6` failed with the following error:

```            
lib/ansible/cli/playbook.py:299:20: SyntaxError: return {k: v for k, v in dict.items() if v is not None}
```    

The test `ansible-test sanity --test pep8` failed with the following error:

```
lib/ansible/cli/playbook.py:115:161: E501 line too long (201 > 160 characters)
```

**Comment by calfonso** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. Our reasons for this are:

We are planning on revamping callbacks to make this configurable rather than hard-coded, additional arguments.

However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

https://groups.google.com/forum/#!forum/ansible-devel
In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by jctanner** [comment]
related roadmap item for the callback changes https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst#globalize-callbacks

**Pull request closed without merging**
