### PR TITLE
ps-lint: ignore rules that are not relevant to Ansible (#46376)

### PR DESCRIPTION
**Pull request by jborean93**
(cherry picked from commit ba638f40cfc1c7677c93f06aec70134eb0fd7066)

##### SUMMARY
Backport of https://github.com/ansible/ansible/pull/46376#issuecomment-426786266

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test pslint

##### ANSIBLE VERSION
```paste below
2.7
```

### CODE REVIEW

**Comment by abadger** [comment]
@jborean93 Could you add a changelog entry for this so I can merge it to stable-2.7?

**Comment by mattclay** [comment]
@abadger The changes are purely test related, so I don't think they warrant a changelog entry.

**Comment by abadger** [comment]
Talked to jborean... the changes in the module code is the equivalent to the special pylint comments which disable special tests.  (like ```# pylint:disable=W305```).  Technically, it is in runtime code but in practice, the only thing it affects is tests.  So yeah, I agree, this doesn't need a changelog entry.

**Comment by abadger** [comment]
Merged for the 2.7.1 release.

**Pull request merged**
