### PR TITLE
fixes #569 apt module problems on old versions of apt-python 

### LINKED ISSUE #569: apt module breaks on older versions of debian
There's a bug with the apt-python module on older versions of debian when you try to update the cache.

I've got what I think is a good patch to fix it.

### PR DESCRIPTION
**Pull request by goozbach**
(namely debian 5.0)

### CODE REVIEW

**Comment by goozbach** [comment]
hold off on merging, Still some errors. Tracking them down.

**Comment by goozbach** [comment]
Ok should be good to go.  I would however, like to see someone test this on a couple of other debian/ubuntu hosts prior to merging it.

**Comment by mpdehaan** [comment]
the warnings module is not available in all versions of Python, so you're going to have to detect the version of the app library and call things as appropriate.

I believe it was added in python 2.5.    Can you test this on 2.4 and resubmit once you are sure it works?

Thanks!

**Comment by goozbach** [comment]
Warnings worked just as coded on python 2.4 from CentOS 5.0

**Comment by mpdehaan** [comment]
maybe it's python 2.3 I was thinking about then.  The docs say 2.4 and later now, so that seems ok.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
