### PR TITLE
Remove `docs` and `examples` directories

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Remove `docs` and `examples` directories.

Also remove `hacking/build_library/` and `hacking/build-ansible.py`, which are now obsolete with the removal of `docs`.

##### ISSUE TYPE

Docs Pull Request

##### COMPONENT NAME

docs

### CODE REVIEW

**Review by samccann — APPROVED** [review]
DaWGs meeting agrees we are ready to go with this. Thanks

**Comment by bartowl** [comment]
Please note, that there are a LOT of resources in Internet that references files like https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

By removing examples you made them dead links!

**Comment by vijayreddiar** [comment]
This was shocking, we were referring this link for WinRM configuration and our automation started failing.

https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

**Comment by harrisonfoundry** [comment]
We need this too https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

**Comment by oraNod** [comment]
Hi everyone. The examples folder has moved to https://github.com/ansible/ansible-documentation/tree/devel/examples

This change is part of a larger restructure of the Ansible community documentation. Our decision was to take the opportunity to move the examples when we created the `ansible/ansible-documentation` repository. This will give us the chance to review and improve this content on behalf of the community.

If you have a resource dependency, we recommend that you modify any urls that reference the devel branch to use a tested commit SHA. This will help avoid broken links.

For example, this url is 404: https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

You can update the url and replace `devel` with a SHA that you have tested, for example: https://raw.githubusercontent.com/ansible/ansible/38e50c9f819a045ea4d40068f83e78adbfaf2e68/examples/scripts/ConfigureRemotingForAnsible.ps1

If you would rather continue using the devel version of the resource, please modify any urls to use the new ansible/ansible-documentation repository. However, please keep in mind that future changes are likely to take place and urls might break again.

We would appreciate hearing more from you about how you use the examples. Please feel free to leave a comment in the [GitHub issue to evaluate and simplify the examples folder](https://github.com/ansible/ansible-documentation/issues/34).

For your reference, this is the Ansible community topic related to the new documentation repository: https://github.com/ansible-community/community-topics/issues/243

**Pull request merged**
