### PR TITLE
new module: panos_match_rule

### PR DESCRIPTION
**Pull request by ivanbojer**
##### SUMMARY
Test for match against a security rule on PAN-OS devices or Panorama management console.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_match_rule

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb  6 2017, 11:22:10) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by jborean93** [comment]
@ivanbojer are you able to rebase your PR by following the docs at http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by jtschichold** [comment]
:shipit:

**Comment by gundalow** [comment]
Rebase needed.
Also this needs unit tests adding

**Comment by ivanbojer** [comment]
Rebase done! The unit tests require PANOS device externally accessible which we cannot do at this time due to security constraints.

**Comment by gundalow** [comment]
Hi,
I should have added some more details
integration tests: Test the integration between the module and the PANOS device
unit test: Use mocking, and therefore don't require access to a PANOS object.

Have a look at the unit tests for the other network platforms in https://github.com/ansible/ansible/tree/devel/test/units/modules/network

The cutoff for 2.4 modules is today (Tuesday 29th August) so it's unlikely these modules get in.

For advice on writing the tests, and general Ansible Network discussion please feel free to join `#ansible-network` on Freenode IRC.

**Comment by ivanbojer** [comment]
Didn't make it for 2.4

**Comment by gundalow** [comment]
@ivanbojer This could still be done for Ansible 2.5.

If you need any help feel free to join `#ansible-network` on Freenode, or we can discuss on this PR.

Not that discussions on PRs will be slower as I get a lot of GitHub email.

**Pull request closed without merging**
