### PR TITLE
ACI: Rewrite construct_url framework

### LINKED ISSUE #43422: aci_interface_policy_leaf_policy_group query with lag_type "link" returns "link" and "node" policy_groups
##### SUMMARY
When using the ansible module aci_interface_policy_leaf_policy_group and doing a query against APIC with lag_type set to "link" the module returns policy groups with lagT=link and also with lagT=node. The correct behaviour would be only to return lagT=link, like specified with the module parameter lag_type.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aci_interface_policy_leaf_policy_group

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.6.1
```

##### STEPS TO REPRODUCE
```yaml
- name: query all Leaf Port-Channel Port Policy Groups of type leaf
  aci_interface_policy_leaf_policy_group:
    <<: *aci_login
    lag_type: link
    state: query
  register: pg_link_apic

- debug:
     msg: '{{ pg_link_apic }}'
```

##### EXPECTED RESULTS
The correct behaviour would be to return only lagT=link, like specified with the module parameter lag_type.

##### ACTUAL RESULTS
Policy groups with lagT=link and/or lagT=node are returned.

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This functionality was not considered when the module was written, but
there's no reason why it shouldn't be supported.

We had to rework the query string construction and object filtering.
This new functionality allows to filter on arbitrary keys and supports
None values.

This PR also fixes various issues with the existing framework, including
querying specific objects using construct_url_4 (i.e.
aci_epg_to_contract and aci_static_binding_to_epg)

This fixes #43422

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
aci_interface_policy_leaf_policy_group

##### ANSIBLE VERSION
v2.7

### CODE REVIEW

**Comment by dagwieers** [comment]
@jmcgill298 Can you review these changes ? I haven't updated all integration tests yet, but most will work out of the box.

**Comment by jmcgill298** [comment]
LGTM as long as the integration tests pass

**Comment by dagwieers** [comment]
@jmcgill298 @brunocalogero @schunduri @rsmeyers @smnmtzgr @nilloBE I think this is ready to be merged, but would appreciate more testing.

**Comment by dagwieers** [comment]
bot_skip

**Comment by dagwieers** [comment]
In all my tests the rewrite worked or fixed known issues. So I am going to merge it now.
Please test or let me know if you encounter a regression or change in behaviour you were not expecting.

**Pull request merged**
