### PR TITLE
ENH: add 'strict' argument to template module, fail on use of undefined var

### PR DESCRIPTION
**Pull request by ghost**
I was missing this in recent work, would have saved me some time.

Example play:

```

---
- hosts: local
  connection: local
  gather_facts: no
  tasks:
    -  local_action: template src=template dest=rendered strict=yes
```

template

```
{{ undefined_var }} {{inventory_hostname}}
```

console output with `strict=yes`

```
PLAY [local] ****************************************************************** 

TASK: [template src=t dest=./o strict=yes] ************************************ 
src=template dest=output strict=yes
fatal: [127.0.0.1] => {'msg': "'undefined_var' is undefined", 'failed': True}
fatal: [127.0.0.1] => {'msg': "'undefined_var' is undefined", 'failed': True}
```

Not sure where the double error message is coming from, glad to address
given a pointer.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This is all good except for the way "strict" is handled, which assumes it will always recieve string arguments and ignores complex arguments, etc.   What we want to do is add the "strict" parameter to the argument spec of copy instead.

Can you take care of this? 

Thanks!

**Comment by ghost** [comment]
Sorry, lost you. Perhaps I misunderstood the machinery in place around modules,
but It looked like the docstring spec is parsed in order to do validation, and there's
a "choices" key added there that specifies `strict` as accepting "yes"/"no". why aren't
string arguments enough? Also, what's the benefit of adding `strict` to copy if it's meant 
to alter the behaviour of the template module, what does a "strict" copy mean?

This was put together quickly to solve an issue I had, possibly I'm missing the larger 
context of ansible modules.

**Comment by mpdehaan** [comment]
Like this:
- template:
   src: blarg
   dest: blarg
   strict: yes

In this case, module args is not _exactly_ a string.

There is another PR to make this a global configurable behavior though, which is _I think_ the way we'd want to do it.

**Comment by ghost** [comment]
FIne, sounds good.

**Pull request closed without merging**
