### PR TITLE
Fix apt module not respecting check mode with certain options

### PR DESCRIPTION
**Pull request by tsipinakis**
##### SUMMARY

* Fix apt-mark marking packages as manually installed in check mode
* Fix apt updating the cache in check mode

There is some minor refactoring taking place to make the cache update code more readable (at least in my opinion). Feedback on that is greatly appreciated.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

apt module

### CODE REVIEW

**Review by mkrizek — APPROVED** [review]

**Review by resmo — APPROVED** [review]
code looks good to me, but I'd like to see some integration tests cases for automated testing this case

**Comment by maxamillion** [comment]
needs_revision

**Comment by maxamillion** [comment]
@tsipinakis it appears the test cases are failing on Ubuntu 14.04 LTS

**Comment by maxamillion** [comment]
waiting_on_contributor

**Comment by tsipinakis** [comment]
I've run out of  ideas on how to test for a cache update. My current approach is to add a broken source entry with the assumption that the apt module will crash if it tries to update but it looks like `python-apt` validates the sources when opening the cache so it fails either way.

Any clues?

**Comment by Jo-Jo0** [comment]
Hey there,
I'm really struggeling with the problem of packages beeing marked manual in check mode. Is there a way to get at least the part that fixes check mode in the apt module merged? I would love to get this fixed, so that we can use ansible in the desired way here.
Hit me up, if I can help you in any way with this.
Would fix https://github.com/ansible/ansible/issues/66413

**Comment by s-hertel** [comment]
@tsipinakis Thanks for working on this. This has been fixed by #45575 a little differently, and now has tests for updating the cache/marking packages as manually installed. I opened a pull request to backport it to 2.13 #78530

**Pull request closed without merging**
