### PR TITLE
Make sudo handle incorrect passwords better

### PR DESCRIPTION
**Pull request by phred**
Ansible would stall waiting for the command output which would never
come when the sudo password was wrong. The simple solution here was
to have ansible execute a simple 'echo' command and look for its
output BEFORE attempting to run any other sudo commands. Given the
difficulty with detecting a successful sudo (since sudo exec's the
command and doesn't provide any other status indicator) and the
messiness of detecting the 'Sorry, try again' prompt (would need
to stuff bytes back into the stream if the output isn't 'Sorry',
kind of a mess), using a simple echo command seems the best solution.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Sorry, having various problems grokking this patch.

I would like to get an explanation in English of how this works for one.   The test vs real command part is somewhat confusing to me.

This also sets this "sudo_ok" flag and doesn't use it, it's always in the same state.  What was the intent there?

"x and y or x" is also a bit unclear, please break that out so it's more clear what your intent is.

Can you explain further?

Thanks!

**Comment by phred** [comment]
To be clear: the problem I'm solving is "when I type my sudo password incorrectly I get no feedback from ansible and it appears to hang."

When you open the SSH channel and run the sudo command, there's no easy way of knowing whether sudo failed or succeeded — on failure, it will prompt again, (up to 3 times or so, then it exits), and on success it will exec() the command and sudo's return status is the same as the executed command.

My solution was "try using sudo to run a simple echo command, if we can read its output then we know we've got the right password, so go ahead and run the intended command."  That's what the `if not sudo_ok` block does — if we don't know whether the password's correct, then up above we did, e.g., `exec_command("sudo echo 'abcdefg OK'")`, so now we're going to loop and wait for the output to make sure that it matches the expected "abcdefg OK".  If we get more than "abcdefg OK" in the output, then sudo's likely printed "Sorry, try again" and the new password prompt, so it raises an exception.

If we get the expected "abcdefg OK" output from sudo, then we know we've got the correct password, so the method calls itself with `sudo_ok` set to `True`, which skips the check during the next execution.

Regardless of the implementation, the real problem that needs to be solved is: fail elegantly and provide feedback when there's a bad sudo password.

Now, the problems I see with my approach:
1. The `sudo_ok` flag is a bit hacky.
2. I've pretty much copied the previous "wait for output" loop, and it makes the whole function a lot longer and more repetitious then it ought to be and obscures the intent.
3. The sudo test will be run on every single command run, which is needless overhead.  Needs to be checked at most once per server per tool run.

What do you think about having a `sudo_ok` or `sudo_password_ok`flag on `ParamikoConnection` to run the test only once per connection?  It'd also be a lot clearer if I factored out the "wait for output" loop to a utility function.

Using a decorator to wrap the "exec_connection" function also occurred to me but it doesn't look like you're using that part of Python.

**Comment by mpdehaan** [comment]
ok so there is no reason to run the echo command if you can assume every module is going to return a JSON hash, you can see if a "{" is returned or not, right?

maybe take a crack at that and remove the sudo_ok flag and extra command execution to do something like that.

**Comment by phred** [comment]
OK, thanks, will do that.

**Comment by mpdehaan** [comment]
per latest IRC discussion we are thinking it should just double prompt for the password because how do you tell a hang from a really long command, etc.

So I think that's probably what we should do.    Join #ansible if you like.

**Comment by phred** [comment]
Yeah, per our brief discussion on IRC yesterday I'm happy leaving this as-is until we have better verbosity/logging settings.  Showing the command run and remote output would immediately let me know what I did wrong.

And I have a scenario where double-prompting still would fail: I use a password manager that places the password on my system clipboard for about 60 seconds,after which it blanks the clipboard.  I usually copy/paste the password into my SSH session to sudo.  However, if the password's expired off the clipboard then I could conceivably paste a blank line twice and not know it since there's no indication of the number of characters I've typed in the password.

Anyway, let's leave as is for now. :-) 

## 

Fred Alger

**Comment by boxed** [comment]
Is this fixed in the development branch now or is the sudo password input handling still broken?

**Comment by mpdehaan** [comment]
Ansible still will require a valid sudo password, however sudo support is operational and significantly evolved since this ticket was opened (note the number).   Much has changed in the last year.

**Pull request closed without merging**
