### PR TITLE
azure_rm_virtualmachine: Create the vm with os disk

### PR DESCRIPTION
**Pull request by smile37773**
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
azure_rm_virtualmachine

### CODE REVIEW

**Comment by Fred-sun** [comment]
@yungezz @zikalino @MyronFanQiu Please take a review this PR when you're free! Thanks a lot!

**Comment by zikalino** [comment]
I just researched more in the documentation.

We should use "create_option" set to "Attach"

https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_03_01.models.osdisk?view=azure-python

**Comment by smile37773** [comment]
> I just researched more in the documentation.
> 
> We should use "create_option" set to "Attach"
> 
> https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_03_01.models.osdisk?view=azure-python

ok!

**Comment by zikalino** [comment]
and then with option "Attach" I think you should use "vhd".

**Comment by zikalino** [comment]
I actually see in the code that it's possible to specify "vhd", and it's used here when creating VM:

https://github.com/ansible/ansible/blob/7c728118e63b740d47cd59bf3443b11ea264b9b8/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py#L1272

However create option is always fixed:

https://github.com/ansible/ansible/blob/7c728118e63b740d47cd59bf3443b11ea264b9b8/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py#L1274

**Comment by zikalino** [comment]
I also wonder if we can attach managed disk by id.

Currently user can only specify managed_disk_type and managed disk is just created.
But the structure also has "id" member which could be probably used with "Attach"

**Comment by smile37773** [comment]
> I also wonder if we can attach managed disk by id.
> 
> Currently user can only specify managed_disk_type and managed disk is just created.
> But the structure also has "id" member which could be probably used with "Attach"

ok,i will try. but i don't think it may be successful because there is no example in https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#create-a-platform-image-vm-with-unmanaged-os-and-data-disks.

**Comment by zikalino** [comment]
azure cli has examples:

   Create a VM by attaching to a managed operating system disk.
        az vm create -g MyResourceGroup -n MyVm --attach-os-disk MyOsDisk --os-type linux

and option

    --attach-os-disk               : Attach an existing OS disk to the VM. Can use the name or ID of
                                     a managed disk or the URI to an unmanaged disk VHD.

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@yungezz @zikalino Please review this PR when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
ping to review

**Comment by Fred-sun** [comment]
@mybayern1974 @haiyuazhang review_need

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang review_need!

**Comment by Fred-sun** [comment]
@smile37773 Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Pull request closed without merging**
