### PR TITLE
update author 

### PR DESCRIPTION
**Pull request by mikeeaton83**
##### SUMMARY
Updating author to non-work account

### CODE REVIEW

**Comment by michaeldeaton** [comment]
happy for this change :)

**Review by gundalow — COMMENTED** [review]
Do you need to update BOTMETA.yml as well? I thought your old account was listed in that as well.

**Comment by michaeldeaton** [comment]
I thought it was in there too but I can’t find it. I searched the entire devel branch for ‘if-meaton’ and don’t see it anywhere
    	
    	

    	
    
  




On Tue, Feb 19, 2019 at 7:10 PM +0000, "John R Barker" <notifications@github.com> wrote:












@gundalow commented on this pull request.



Do you need to update BOTMETA.yml as well? I thought your old account was listed in that as well.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Thanks, merged!

**Pull request merged**
