### PR TITLE
Optional Use of urllib3 for SNI verification

### PR DESCRIPTION
**Pull request by sivel**
##### ISSUE TYPE

Feature Pull Request
##### ANSIBLE VERSION

```
v2.1
```
##### SUMMARY

This change adds optional support to `urls.py` to utilize `urllib3.contrib.pyopenssl` for SNI verification.

If the deps are not installed, things work as they do now, except the error message mentions that if installed, you can do SNI verification on older python versions.

To activate this functionality, the following python modules would need to be installed:
1. urllib3 or requests with urllib3 vendored (although urllib3 is listed as the dep)
2. pyopenssl
3. ndg-httpsclient
4. pyasn1

### CODE REVIEW

**Comment by sivel** [comment]
This addresses the concern from https://github.com/ansible/ansible-modules-core/issues/3355 where SNI would not be achievable on RHEL6 or any OS with Python 2.6 or an older version of Python 2.7 such as Ubuntu.

**Comment by sivel** [comment]
Adhoc command for testing:

```
ansible all -i localhost, -c local -m uri -a 'url=https://sni.velox.ch return_content=True'
```

In the return on a success you should also see:

```
Great! Your client </strong>[ansible-httpget] <strong> \nsent the following TLS server name indication extension\n
```

**Comment by sivel** [comment]
This has received a +1 from both @jimi-c and @abadger on IRC.

**Comment by abadger** [comment]
+1 -- I know you were hesitating to add more tests because it would add deps while testing.  There's no problem with that.  We have lots of deps for testing only (database modules, for instance).  Might want to install and uninstall the deps as part of testing since the deps are optional, though.

**Comment by sivel** [comment]
> Might want to install and uninstall the deps as part of testing since the deps are optional, though.

Cool, I'll handle that.

**Comment by sivel** [comment]
After hours of trying to figure out how to handle the deps across all of our docker images correctly, I have integration tests as part of the `uri` module, that test the variances in SNI verification.

Of note, I moved `test_uri` into destructive tests, as it is now installing and uninstalling packages.

I also am not running the "urllib3" tests on ubuntu1204 as there is no `python-urllib3` and that made things too messy trying to handle it.  We still get full tests on other older pythons with other OSes/versions such as CentOS6 and Ubuntu14.04.

**Comment by abadger** [comment]
Looks good to merge!

**Comment by sivel** [comment]
Ok, merging.

**Pull request merged**
