### PR TITLE
minor become/runas cleanup

### PR DESCRIPTION
**Pull request by nitzmahone**
##### SUMMARY
* removed/blobified unused PInvoke stuff
* added try/finally around impersonation to ensure RevertToSelf is called in all cases
* added a few explanatory comments

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
powershell.py

##### ANSIBLE VERSION
2.5.0

### CODE REVIEW

**Comment by nitzmahone** [comment]
@jborean93 - a few things around the original review from #32485, let me know if you disagree with any of this or have questions (especially the try/finally around RevertToSelf- I *think* that's always the right thing to do, and it worked when I tested under every scenario I could think of).

**Comment by nitzmahone** [comment]
If not for damned 32bit OS support, we could get a lot more aggressive with the blobification on those structs :)

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
rebuild_merge

**Comment by nitzmahone** [comment]
test failures appear to be transient and unrelated, merging

**Pull request merged**
