### PR TITLE
Adds a new module, ec2_iam_role.

### PR DESCRIPTION
**Pull request by scottanderson42**
This module can create and delete IAM roles, policies, and instance profiles for association with an instance, either via instance creation or with a launch configuration.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you expand out the JSON in the example rather than using the lookup plugin?  (i.e. inline data structures?)

We can show both but I think it would be useful to show ways of doing this without the JSON.

Thanks!

**Comment by scottanderson42** [comment]
I need to change how the parms are read due to the issue with JSON being parsed in complex args vs. non-complex; I'll get back to this.

**Comment by scottanderson42** [comment]
All set, thanks for the feedback.

**Comment by jimbydamonk** [comment]
This looks good. +1, I could really use this.

**Comment by terretta** [comment]
In documentation section, this has "module: ec2_asg", presume "ec2_iam_role" instead?

If missing region, instead of asking to supply region, fails in get_existing_role
    existing_role = connection.get_role(role_name)
AttributeError: 'NoneType' object has no attribute 'get_role'

**Comment by mpdehaan** [comment]
cc @jsmartin - is this something you might be interested in testing out?

I'm also a bit curious if we can edit things as well as create/delete them.

We would want to change the name of the module in the docs stub, but we can take care of that, as @terretta mentions above.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Pull request closed without merging**
