### PR TITLE
digital_ocean_floating_ip: check if fip is already assigned

### LINKED ISSUE #63175: digital_ocean_floating_ip is not idempotent
##### SUMMARY
`digital_ocean_floating_ip` is not idempotent, this is important.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
digital_ocean_floating_ip

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /Users/XXX/XXX/ansible.cfg
  configured module search path = ['/Users/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXX/XXX/.env/lib/python3.7/site-packages/ansible
  executable location = /Users/XXX/XXX/.env/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### STEPS TO REPRODUCE
1. Run the tasks below. Droplet gets created with a Floating IP assigned.
2. Run the tasks once again, the playbook fails on the second step.

```yaml
- name: "Creating a droplet..."
  digital_ocean_droplet:
    state: present
    name: "{{ name }}"
    oauth_token: "{{ token }}"
    size: "{{ size }}"
    region: "{{ egion }}"
    image: "{{ image }}"
    wait_timeout: 300
    unique_name: true
    ipv6: true
    ssh_keys: "{{ ssh_key }}"
  register: digital_ocean_droplet

- name: "Create a Floating IP"
  digital_ocean_floating_ip:
    state: present
    oauth_token: "{{ token }}"
    droplet_id: "{{ digital_ocean_droplet.data.droplet.id }}"
  register: digital_ocean_floating_ip
```

##### EXPECTED RESULTS
Ansible detects that a Floating IP is already assigned to the droplet and returns `success` with the data included.

##### ACTUAL RESULTS

```paste below
TASK [cloud-digitalocean : Create a Floating IP] ***********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating floating ip [422: Droplet is already assigned to another floating IP.]", "region": null}
```

### PR DESCRIPTION
**Pull request by jackivanov**
##### SUMMARY
We need to ensure that there is no floating ip assigned to the droplet already before trying to create a new one. Fixes #63175

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
digital_ocean_floating_ip

### CODE REVIEW

**Comment by abadger** [comment]
@jackivanov Hi, fixes need to be applied to the devel branch first and then backported to the other open branches after they are merged there.  That way we have less risk of regressions.  Could you retarget this against the devel branch?

**Comment by Akasurde** [comment]
@jackivanov Are you re-opening the PR with devel as target ? Let me know thanks,

**Comment by pmarques** [comment]
Sorry for the late reply @jackivanov I was off for a while.

**Comment by pmarques** [comment]
I assume this needs to be rebased, I believe only the last commit 8344d5c11837842a2beb4a41893b83237982d7e6 is needed for the PR

**Pull request closed without merging**
