### PR TITLE
Support iterating over dicts in loop

### LINKED ISSUE #51615: Directly support iterating over dicts in "loop"
##### SUMMARY

The `loop` keyword should implicitly call `dict2items` if its argument is a dict instead of a list.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

loop

##### ADDITIONAL INFORMATION

In several of my playbooks I use `with_dict` to iterate over dictionary literals (as opposed to looping over dicts that are defined elsewhere). I'd like to move to the new `loop` setup to get out ahead of `with_` being deprecated some day in the future, but for this specific case, it makes the tasks more verbose for no real benefit.

Suggestion: Instead of bombing out with an error about expecting a list, `loop` should iterate over the items of a dict if one is passed to it. In other words, it should implicitly call `dict2items`.

```yaml
# Before
- name: Some task
  lineinfile: ...
  with_dict:
    item1: foo
    item2: bar

# After
- name: Some task
  lineinfile: ...
  loop: "{{ items|dict2items }}"
  vars:
    items:
      item1: foo
      item2: bar
```

Here, the "vars" block and the filter expression make the playbook noisier but don't add any functionality.

Suggestion:

```yaml
- name: Some task
  lineinfile: ...
  loop:
    item1: foo
    item2: bar
```

To be clear, I'm not suggesting getting rid of the ability to call filters other than `dict2items` if you want something other than the default iteration order or the default mapping to `item.key` and `item.value`. The explicit syntax would still be available when finer control is required, so the change I'm suggesting doesn't remove any functionality. The proposal is just to replace the current behavior (playbook bombs out with an error if you feed a dict to `loop`) with default behavior that is likely to be what people would expect.

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes #51615

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

loops

### CODE REVIEW

**Comment by willthames** [comment]
Will this break any existing code? Just wondering if doing loop with a dict currently fails, or just loops over the keys?

**Comment by mkrizek** [comment]
> Will this break any existing code? Just wondering if doing loop with a dict currently fails, or just loops over the keys?

Currently doing loop with a dict fails.

**Comment by bcoca** [comment]
-1 as `loop: dict|list` and many other filters make this trivial to do and the main reason for `loop` existing in the first place is removing all the "magic" inherit in `with_` constructs.

**Comment by bcoca** [comment]
-1 as `loop: dict|list` and many other filters make this trivial to do and the main reason for `loop` existing in the first place is removing all the "magic" inherit in `with_` constructs.

**Comment by sivel** [comment]
We denied another PR a few months ago to add this exact functionality:  https://github.com/ansible/ansible/pull/53042

This was decided by the team during triage, and subsequently closed.

Based on this, I believe we should not add this functionality, and the associated issue should be closed as "wontfix".

**Comment by mkrizek** [comment]
Closed as per https://github.com/ansible/ansible/pull/53042#issuecomment-469842324.

**Pull request closed without merging**
