### PR TITLE
Feature added - OS disk created date field

### PR DESCRIPTION
**Pull request by sujiar37**
##### SUMMARY
Helpful to get to know the VM creation date by referring with the OS disk information details. It would be useful if people looking for filtering inventories through VM creation date.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
azure_rm.py

##### ANSIBLE VERSION
2.6

##### ADDITIONAL INFORMATION
This feature helps to track finding VM creation date as well as, it brings out importing inventories with respective to the user input date from AWX / Ansible Tower

### CODE REVIEW

**Review by sujiar37 — COMMENTED** [review]
added ','

**Comment by Fred-sun** [comment]
before it been fixed, we can use ansible-playbook to get the os disk create date, as beloww:
```e.g.
 ansible-playbook test.yml -vvv
  - name: read VM info
    azure_rm_virtualmachine: 
      resource_group: myRG 
      name: myVM 

result:
                        "disks": [
                            {
                                "name": "myVM", 
                                "statuses": [
                                    {
                                        "code": "ProvisioningState/succeeded", 
                                        "displayStatus": "Provisioning succeeded", 
                                        "level": "Info", 
                                        "time": "2018-07-23T02:46:16.89851Z"
                                    }
                                ]
                            }
                        ],

**Comment by yuwzho** [comment]
Hi @sujiar37 Thanks for your contribution. I think the inventory should list the critical information of the VM, for more detail should run the facts module to get the details. Otherwise, to many API call will result in a long wait user experience.

**Comment by Fred-sun** [comment]
@sujiar37 Thanks for your contribution, Could you help solve the conflicting file? another, what do you think of @yuwzho views? Thanks!

**Comment by sujiar37** [comment]
@Fred-sun @yuwzho Thanks for your response. I agree with your comments because it still using an api to get that info.

I revert the changes now. Basically, we contributed this feature to find out what all are the new VM's deployed in Azure on an each / any past days basis. It would be helpful and much easier to import necessary servers into AWX / Ansible Tower directly instead of going through the playbook level of execution. Adding to that , we implemented this feature already and we can import inventory's through passing a parameter like 

```
azure_vm_filter_by_days : 1 / any past days
```

**Comment by Fred-sun** [comment]
@sujiar37 Thanks for your contribution, Could you review according with ansibot suggestion . Thanks!

**Comment by Fred-sun** [comment]
@sujiar37 Thanks for you update, could you help to solve the problems mentioned in comment? Another, If you finish change, I will push to review. Thanks!

**Pull request closed without merging**
