### PR TITLE
Filter: add wrap.py

### PR DESCRIPTION
**Pull request by hyperized**
##### SUMMARY
I needed a quote filter and would love to share.

Example usage:

```
mylist:
  - hello
  - world
var: mylist | wrap('"') | join(', ')
```
results in:
`"hello", "world"`

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/filter/quote.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.2.0
  config file = ~/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION
Test script:
```
---
- hosts: localhost
  vars:
    myvar: world
    mylist:
      - firstitem
      - seconditem
  tasks:
    - debug:
        var: myvar | wrap("'")
    - debug:
        var: myvar | wrap('"')
    - debug:
        var: mylist | wrap_list("'")
    - debug:
        var: mylist | wrap_list('"')
```
results in:
```
PLAY [localhost] **********************************************************************************

TASK [debug] **************************************************************************************
ok: [localhost] => {
    "myvar | wrap(\"'\")": "'world'"
}

TASK [debug] **************************************************************************************
ok: [localhost] => {
    "myvar | wrap('\"')": "\"world\""
}

TASK [debug] **************************************************************************************
[u'firstitem', u'seconditem']
"'"
ok: [localhost] => {
    "mylist | wrap_list(\"'\")": [
        "'firstitem'",
        "'seconditem'"
    ]
}

TASK [debug] **************************************************************************************
[u'firstitem', u'seconditem']
'"'
ok: [localhost] => {
    "mylist | wrap_list('\"')": [
        "\"firstitem\"",
        "\"seconditem\""
    ]
}

PLAY RECAP ****************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by mattclay** [comment]
@hyperized Please include an integration test for this filter.

**Comment by mattclay** [comment]
@hyperized Can you check the email address used on your commits? It's not registered to your GitHub account.

**Comment by hyperized** [comment]
@mattclay It is now, thanks for pointing that out. I'll fix the integration tests in a little bit.

**Comment by hyperized** [comment]
@mattclay fixed, rebased and ready to merge :)

**Comment by hyperized** [comment]
Added the docs too.

**Review by dharmabumstead — APPROVED** [review]
Docs update OK. Thanks @hyperized.

**Comment by hyperized** [comment]
@dharmabumstead and maybe @gundalow is this OK to merge or do I need to improve something?

**Comment by gundalow** [comment]
How about expanding the existing quote to take an optional character (`map quote`)?

You should really not need tom ake a 'list version' of a filter, they should just be usable with map/select/reject

**Comment by hyperized** [comment]
There's no real need for this filter :)

**Pull request closed without merging**
