### PR TITLE
Fixed problem with with_items variables not working in name field of include_role.

### PR DESCRIPTION
**Pull request by ppluciennik**
Partial fix for #19305.

### CODE REVIEW

**Comment by broferek** [comment]
This is a feature we really expect here. 

I just tested the fix in our dev server and it works perfectly.

I can pass a list of roles from a fact set in a previous role and loop over the list of roles.

Would be really appreciated to have it in 2.3.X

**Comment by Atem18** [comment]
When I try it I sometimes have the following error. Does someone know why ?
```
TASK [Execute role for each services] ******************************************
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
RuntimeError: dictionary changed size during iteration
```

**Comment by oybed** [comment]
I've verified that this also fixes this issue for me ... can we please get this added to the next version of Ansible, please? I've only tested the fix with Ansible 2.3, but I have found that the same problem still exists in 2.4 as well and hence need this fix for that version as well.

**Comment by mkrizek** [comment]
#19305 was fixed in https://github.com/ansible/ansible/pull/33386 therefore I am going to close this one, thanks for your contribution @ppluciennik!

**Comment by weworkryan** [comment]
@mkrizek  This issue still occurs. Probably needs this pull request

**Pull request closed without merging**
