### PR TITLE
adds stub API docs in a single file

### PR DESCRIPTION
**Pull request by acozine**
##### SUMMARY
Creates a location for future API docs. Eliminates the last errors on `make webdocs` without removing the links we already have in place.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs.ansible.com

##### ANSIBLE VERSION
2.8

### CODE REVIEW

**Comment by acozine** [comment]
Since this is the last error in our ignore list, `docs-build.py` can get some extra cleanup beyond just removing the one line. I'll tackle this tomorrow. @abadger are the other changes more or less what you had in mind as stub docs for the API?

**Review by mattclay — APPROVED** [review]

**Comment by abadger** [comment]
Yep, that looks like what i was imagining

**Comment by dagwieers** [comment]
I think this is the wrong approach if we do not intend to add the documentation shortly. We'll end up with documentation with fake references to empty sections. Which is worse than not having the references at all (until proper anchors exist).

Adding a reference only when something is actually documented is the right approach IMO. This PR poses a big risk to become bit-rotted, because any incentive to write the documentation is now gone, and we have 'dangling' references to nothing.

**Review by samccann — APPROVED** [review]

**Comment by acozine** [comment]
@dagwieers thanks for the input - either way we risk bit-rot and an ongoing gap in the documentation. But removing the links also removes all incentive to create API docs. In fact, it adds a disincentive, since the person who creates the docs would have to reinstate those links as well as create the materials they link to. My main goal here is to eliminate the build errors, but I hope this approach will keep the API docs in view and spur us to  complete them soon.

**Comment by dagwieers** [comment]
Well,

- the person who creates the docs will have to reinstate links anywhere else in the documentation anyway, which is the normal thing to do when you add documentation and wants to reference it in the right places (this is true for new stuff/anchors too) So a proper grep and a few edits is all it takes.
- most of the existing documentation does not have references to the current stubs either
- the current stub document is a very specific list of stuff that *is* referenced at the moment, but
  - it does not represent the normal flow of that document when you would be starting the documentation from scratch
  - it does not represent the most important or a complete set of stuff we would be documenting ideally
  - chances are whoever starts to document this will start from the current template, rather than think out of the box to how this document would look like ideally

So I don't think we are doing ourselves a great service by keeping the references and adding a stub document. It may feel as if we are making a step forward, but I think we are taking a few back overall.

And this is all assuming we consider the API docs to be the most important thing to document next, which I doubt is true. The API docs are a moving target and I think there are plenty of things we should be doing first anyway.

Is there a foreseen date for finishing the API documentation ? And will this include only the stub anchors, or will it be a more comprehensive API documentation ?

**Comment by acozine** [comment]
@dagwieers excellent questions. We plan to auto-generate documentation for the API from the code, similar to what we do for the module docs, so the stub document will disappear once that's ready. And yes, we'll document more broadly, not just the anchors included in the current stub. As to timing, I don't have a good answer for you. I agree it's not our top priority, but we're making progress overall. And thank you for all your contributions to that progress!

**Pull request merged**
