### PR TITLE
Option to skip update even if given ec2_key has changed

### PR DESCRIPTION
**Pull request by philsch**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ec2_key module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
A flag `replace` was added to the ec2_key module. If the flag is set to `False` an existing AWS EC2 Key will not be replaced, if `key_material` has changed. The default behaviour of the module is not changed.

### CODE REVIEW

**Comment by willthames** [comment]
This probably needs more justification - I think I understand the reason for the change but might be worth explicitly spelling it out, particularly in the commit message.

**Comment by philsch** [comment]
Hi @willthames 

There are two motivations behind this feature request:

1. If a Key is replaced and EC2 instances already launched using the old key, the system is in an inconsistent state. The EC2 details page shows that the Key "exampleKey" is used.. In the Key Pairs section this label can be found, but it's not the correct Key anymore. If this scenario happens by accident, loss of access to an EC2 machine can happen in worst case. So it would be nice to have a way to **protect keys** from overwrite.
2. At the moment there is no way to find out if a Key is already existing and make other tasks dependant on that. With this feature it would be possible to always call the module and check the returned `changed` flag. Example program flow: 
```
1. Generate new SSH Key
2. Run ec2_key with replace=False
3a: If not changed -> no further action
3b: If changed -> make the generated SSH key persistent e.g. using CredStash
```

**Review by ryansb — CHANGES_REQUESTED** [review]
Typically for this purpose we use a name like `force` for the option, not `replace`.

**Comment by philsch** [comment]
ready_for_review

**Comment by philsch** [comment]
Seems like Ansibot is not reacting on `ready_for_review`, however changed the flag to `force` @ryansb :)

**Comment by willthames** [comment]
@philsch thanks for that detail, but that should be in the commit message, not just in a comment in a PR.

I'm happy enough with the functional change but I'd really like a better commit message.

**Comment by philsch** [comment]
@willthames squashed and added details to the commit message.

**Comment by willthames** [comment]
Thanks @philsch for that

**Comment by willthames** [comment]
shipit

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
Thanks @philsch, and @willthames for reviewing.

**Pull request merged**
