### PR TITLE
docker modules: default config path is $HOME/.docker/config.json, not $HOME/docker/config.json

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See https://github.com/docker/docker-py/blob/master/docker/utils/config.py#L7

(Browsing the git history also shows that this was probably always the case.)

Thanks to @pmossakx for reporting #53857.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
lib/ansible/plugins/doc_fragments/docker.py

### CODE REVIEW

**Comment by felixfontein** [comment]
The failed (unstable) CI run is unrelated to this PR.

**Comment by WojciechowskiPiotr** [comment]
shipit

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
@WojciechowskiPiotr thanks for reviewing!

**Pull request merged**
