### PR TITLE
Fix incorrectly calling wrapper scripts with Python

### PR DESCRIPTION
**Pull request by bertptrs**
##### SUMMARY

This patch changes the subprocess call that normally starts the `ansible-connection` process. On POSIX-systems (MacOS & Linux mostly) it should no longer explicitly execute the script with the current Python interpreter, instead relying on the script's shebang line to call the right interpreter.

This solves an issue running Ansible on NixOS, where the `ansible-connection` is actually a bash wrapper script (due to complicated reasons that are very specific to NixOS) but it also applies to other set-ups where the shebang line is intentionally overwritten, such as virtualenvs.

For non-POSIX systems I left the existing behaviour unchanged as I am not as well versed in the specifics. I suspect the first part of this function can be replaced with `shutil.which` still, but that is for future improvement.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

Task runner

##### ADDITIONAL INFORMATION

The ansible connection wrapper looks as follows, for v2.10. Newer versions follow a similar pattern, this is just what I had lying around right now.

```console
$ nix-shell -p ansible
$ cat $(which ansible-connection)
#! /nix/store/j206pskg2yzyla1cnfrb9kb5n5bfvjgm-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/685kq8pyhrvajah1hdsfn4q7gm3j4yd4-python3-3.8.5/bin:/nix/store/79hga0bkbv6vwx33y085w6irk5g5pq13-python3.8-ansible-2.10.0/bin:/nix/store/gldd4hfn0szqipf3rzzwbcgkllnlkhkf-python3.8-setuptools-47.3.1/bin:/nix/store/75rpy5zs256y9sm1gnakrhy1pq6qgigi-python3.8-netaddr-0.7.19/bin:/nix/store/hh6jmj6i26xhwl45ssvan4y94l7nrbyy-python3.8-jmespath-0.10.0/bin:/nix/store/5gbl9dr1vhl745w2psrj7ll1fpad5lbk-python3.8-chardet-3.0.4/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/79hga0bkbv6vwx33y085w6irk5g5pq13-python3.8-ansible-2.10.0/bin/.ansible-connection-wrapped"  "$@"
```

### CODE REVIEW

**Comment by bertptrs** [comment]
One of the tests on CI has failed but I'm not sure how it's related to these changes. Is it a flake?

**Comment by bcoca** [comment]
please note that one reason we specifically use the same interpreter is because ansible-connection must instantiate Ansible classes and plugins in the same way that the core Ansible engine does. It is not advisable to change the execution to use the shebang.

**Comment by samdoran** [comment]
This is definitely not something we should change. Using the shebang rather than `sys.executable` means Ansible could end up using the incorrect Python interpreter to run `ansible-connection`.

The actual problem in the code here is assuming that `ansible-connection` is Python code that can be executed by `sys.executable`. 

Would it be possible to change the wrapper script in NixOS to Python?

**Comment by bertptrs** [comment]
> Would it be possible to change the wrapper script in NixOS to Python?

I am not a NixOS dev but I deem the chances unlikely. The system is strung together with small bash wrappers that configure the environment to have other software (such as python) deal with the unusual directory structure it mandates, and I doubt that this would be worthy of a special case.

For the concrete problem with NixOS, the original reason I started on this issue, would you accept a PR sniffs the binary for a potential shebang line, and depending on that either use the python interpreter or just call the binary and hope for the best? NixOS' architecture ensures that the interpreter would be the same so it would work, and it wouldn't affect any scenario that isn't already broken in the current situation.

**Comment by samdoran** [comment]
> For the concrete problem with NixOS, the original reason I started on this issue, would you accept a PR sniffs the binary for a potential shebang line, and depending on that either use the python interpreter or just call the binary and hope for the best?

This seems like a very bespoke fix only for NixOS. I don't think a fix that targeted would be accepted. I will let others chime in.

**Comment by bcoca** [comment]
I agree with @samdoran, if someone is hijacking our CLI tools and substituting them, its not up to use to 'fix' it when they do this improperly

**Comment by bcoca** [comment]
closing as per above

**Pull request closed without merging**
