### PR TITLE
Add rudimentary wait for os_zone

### LINKED ISSUE #54680: Module os_zone does not respect wait variable
##### SUMMARY
Even though it is documented in the [documentation of the os_zone module](https://docs.ansible.com/ansible/latest/modules/os_zone_module.html) (I guess because it is a standard OpenStack module variable) it does not respect the `wait` variable.

This may be an issue with openstacksdk but since other OS modules implement wait themselves I am not sure about this. Anyhow, I've created a pull request for this (https://github.com/ansible/ansible/pull/54391) which adds a rudimentary `wait` functionality to the module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_zone

##### ANSIBLE VERSION
```paste below
ansible 2.7.6
  config file = None
  configured module search path = [u'/home/sprietl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
IMHO not relevant

##### OS / ENVIRONMENT
* Ubuntu 16.04
* openstacksdk 0.23.0

##### STEPS TO REPRODUCE

Btw. `wait` is not explicitly set because documentation says that default value is `yes|true`.

Example Playbook:
```yaml
- name: "delete zone"
  os_zone:
    auth: "{{ os_auth }}"
    state: absent
    name: "{{ item.name }}"
  loop: "{{ os_zones }}"

- name: "create zone"
  os_zone:
    auth: "{{ os_auth }}"
    state: present
    name: "{{ item.name }}"
    zone_type: "{{ item.type }}"
    email: "{{ item.email }}"
    description: "{{ item.description | default('') }}"
    ttl: "{{ item.ttl | default(3600) }}"
  loop: "{{ os_zones }}"

- name: "Create record sets"
  os_recordset:
    auth: "{{ os_auth }}"
    state: present
    zone: "{{ item.0.name }}"
    name: "{{ item.1.name }}.{{ item.0.name }}"
    recordset_type: "{{ item.1.type }}"
    records: "{{ item.1.records }}"
    description: "{{ item.1.description | default('') }}"
    ttl: "{{ item.1.ttl | default(omit) }}"
  loop: "{{ query('subelements', os_zones, 'record_sets', {'skip_missing': True}) }}"
```

Example configuration:
```yaml
os_zones:
  - name: "my-domain."
    type: "primary"
    email: "hostmaster@my-domain.com"
    description: "a zone"
    record_sets:
      - name: "myhost"
        type: "A"
        records:
          - "1.2.3.4"
```

##### EXPECTED RESULTS

(pseudo output)

```paste below
TASK [delete zone]
changed: []

TASK [create zone]
changed: []

TASK [Create record sets] 
changed: []
```

##### ACTUAL RESULTS

(pseudo output)

```paste below
TASK [delete zone]
changed: []

TASK [create zone]
ok: [] # it says ok here because zone still exists (but in PENDING/DELETING state)

TASK [Create record sets] 
fatal: [zone does not exist]
```

### PR DESCRIPTION
**Pull request by ederst**
##### SUMMARY
This adds a rudimentary wait functionality for the os_zone module.

It will wait for:
* Zone not in OpenStack API when choosing `absent`
* Zone `status` being `AVAILABLE` in OpenStack when choosing `present`

Before the `os_zone` module did not wait for changes to be applied. Thus, this could lead to errors when for example trying to add record sets in subsequent tasks, or when deleting and recreating zones (`PENDING` and/or `DELETING` state counted as `present`).

Fixes: https://github.com/ansible/ansible/issues/54680

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
os_zone

##### ADDITIONAL INFORMATION

Before deleting, creating, and adding record sets could lead to the following behavior with an already existing zone (pseudo task output):

```paste below
TASK [delete zone]
changed: []

TASK [create zone]
ok: [] # it says ok here because zone still exists (but in PENDING/DELETING state)

TASK [Create record sets] 
fatal: [zone does not exist]
```
However, with this change the following should happen:

```paste below
TASK [delete zone]
changed: []

TASK [create zone]
changed: []

TASK [Create record sets] 
changed: []
```

### CODE REVIEW

**Comment by ederst** [comment]
ready_for_review

**Comment by ederst** [comment]
bot_status

**Comment by ederst** [comment]
+label affects_2.7

**Review by mnaser — APPROVED** [review]
shipit

thanks!!!

**Comment by ederst** [comment]
bot_status

**Comment by ederst** [comment]
shipit

**Comment by ederst** [comment]
bot_status

**Review by cloudnull — APPROVED** [review]
shipit

**Pull request merged**
