### PR TITLE
New GCP Module: gcp_iam_service_account_facts

### PR DESCRIPTION
**Pull request by rambleraptor**
##### SUMMARY

New GCP Module: gcp_iam_service_account_facts

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
gcp_iam_service_account_facts

##### ANSIBLE VERSION
```
2.8
```

##### ADDITIONAL INFORMATION
```
This was generated by [Magic Modules](https://github.com/googlecloudplatform/magic-modules)
```

### CODE REVIEW

**Comment by rambleraptor** [comment]
shipit

**Comment by rambleraptor** [comment]
bot_status

**Comment by rambleraptor** [comment]
bot_status

**Comment by jctanner** [comment]
@rambleraptor not sure if you noticed, but the `automerge: automerge ci_stale test failed` from the status output was indicating that this PR's tests were last run >7 days ago. If a PR is in a shipit state (or supershipit) then the bot will restart the tests. If the tests pass and the PR is automergeable, the bot will then merge it. That's why you had a delay between the removal of "stale_ci" and when it was finally merged.

**Comment by rambleraptor** [comment]
That’s good to know. Thanks!

**Pull request merged**
