### PR TITLE
docs/: PEP8 compliance

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
- Make PEP8 compliant

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

docs/

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Rebase then I'll merge

**Comment by dagwieers** [comment]
@gundalow Rebased. Thanks !

**Comment by dagwieers** [comment]
@gundalow Please merge. Or provide feedback to what is the problem. I hate to spend my time resolving conflicts every day.

**Comment by dagwieers** [comment]
Shippable stalls at WAITING (however is green if you click through). Close and re-open.

**Review by gundalow — APPROVED** [review]

**Pull request merged**
