### PR TITLE
Addition to the ecs_service module to also set the health_check_grace_period_seconds param

### PR DESCRIPTION
**Pull request by stefanhorning**
Needs newer boto3 though.

##### SUMMARY
Addition for the ecs_service module to allow health_check_grace_period_seconds and passing it through to boto3 (should work from boto3 1.6.0).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ecs_service

### CODE REVIEW

**Review by willthames — CHANGES_REQUESTED** [review]
This will fail if people aren't using newer boto3 (botocore, I assume) but don't need to set health check grace period. 

This change *must* be made backwards compatible. Three situations:

* boto3 < 1.6.0, health_check_grace_period not set - work as previously
* boto3 > 1.6.0, this should all work fine whether or not health_check_grace_period is set
* boto3 < 1.6.0, health_check_grace_period set - fail with a message saying that the user needs to update boto3 (botocore?) to use this setting

**Comment by willthames** [comment]
See also #38965 and #36035 (https://ansible.sivel.net/pr/byfile.html is very helpful)

**Comment by willthames** [comment]
@jeffreykoetsier @stefanhorning  @FabianPonce my point about backward compatibility is valid for all three PRs - I remembered while writing the feedback here that I'd written the same kind of message just recently. 

We also have a policy that feature improvements should have tests. There is an ECS test suite (it's hidden under ecs_cluster), it would be good if we could have tests that the backward compatibility works (although that is quite hard to do!). I may be able to provide the test suite though if you can provide the backward compatibility

**Comment by stefanhorning** [comment]
You are right and I was hesitant to even open a PR for this, until I stumbled across other modules already requiring new boto3 versions in Ansible 2.5 (perticalarly the elb_target_group module).

Is there a policy on this that applies for all modules? As most AWS modules (I have seen) don't state a boto version they need in the docs, not do they check for the boto(3) version in use.

**Comment by willthames** [comment]
@stefanhorning that's a fair question. See https://github.com/ansible/ansible/pull/39085#issuecomment-383961774 for our most recent discussions on this. 

I don't know how old this change is, if it's more than a year old, it might be fine to add this into 2.6 if we do declare a minimum version > 1.6.0

**Comment by stefanhorning** [comment]
I see. Thanks for all the infos. I guess this PR can be closed then as there is already two others open for the same change.

**Pull request closed without merging**
