### PR TITLE
Added support for chain and direct rule manipulation

### PR DESCRIPTION
**Pull request by fzoske**
##### ISSUE TYPE
 - Feature Pull Request
##### COMPONENT NAME
system/firewalld.py
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY

Added support for chain and direct rule manipulation.

```

```

### CODE REVIEW

**Comment by fzoske** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3524

**Comment by maxamillion** [comment]
👍 

shipit

**Comment by fzoske** [comment]
ready_for_review

**Comment by maxamillion** [comment]
👍 
shipit

**Pull request closed without merging**
