### PR TITLE
Fix ignore diff lines issue for lines in ios, eos, nxos

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

*  Pass `diff_ignore_lines` while creating
   candidate and running configuration object

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
2.6
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by yaplej** [comment]
This now fixes my issue.
Fixes #30562

**Comment by mattclay** [comment]
@ganeshrn Is this a backport of a fix in devel?

**Comment by ganeshrn** [comment]
The code in devel is changed for modules and the issue is fixed as part of other [refactor](https://github.com/ansible/ansible/issues/39056) which can't be cherry-picked to stable-2.6 hence raised a new PR for stable-2.6

**Comment by yaplej** [comment]
@ganeshrn 
I found a problem and I think its related to https://github.com/ansible/ansible/pull/43924.  

When you use  diff_ignore_lines: and replace: block those lines are excluded from diff but also excluded from the executed configuration when non-diff_ignore_lines: detect a difference.

Lines excluded in difference should not be excluded from config if replace: block is set.

**Comment by ganeshrn** [comment]
@yaplej That's right, `diff_ignore_lines` options should be used only when processing running config and not candidate config. Since @mattclay has merged this PR I have added the change in different PR. Can you test with the changes in PR https://github.com/ansible/ansible/pull/43889 applied on the latest stable-2.6 branch or refer https://docs.ansible.com/ansible/2.6/dev_guide/testing.html#how-to-test-a-pr for testing PR branch

@mattclay Sorry for the confusion.

**Pull request merged**
