### PR TITLE
New module: Add module to defragment Windows local volumes (windows/win_defrag)

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This module performs defragmentation on local Windows volumes.

This module requires PR #23131 for list parameter support.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

win_defrag

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by jborean93** [comment]
Looks good, I'm curious do you need to defragment your drives, I thought Windows has been doing it automatically since Vista/Server 08?

shipit

**Comment by dagwieers** [comment]
@jborean93 I thought so too, but managing about 60 computers at an elementary school, running this does make a difference. Especially on systems with limited free space (or likely had limited free space over some period in the past). So I assume the implementation tries to limit fragmentation on-the-go, but if that's not possible fragmentation still happens. I can't really say.

We are now using this as part of a clean-up script that removes Chocolatey, nuget, ansible, ... caches and then running win_defrag (outside of school hours). It is possible the effect is no longer that big as the first run we did though. (These systems were Windows 7/Windows8 systems that were upgraded to Windows 10, maybe that's related too.)

**Comment by jborean93** [comment]
@dagwieers thanks for the info, you should add an optional parameter that will play the traditional defrag sound http://hultbergs.org/defrag/ :)

**Review by nitzmahone — APPROVED** [review]

**Comment by nitzmahone** [comment]
Thanks!

**Pull request merged**
