### PR TITLE
Enable adjacent collections for ansible-doc

### PR DESCRIPTION
**Pull request by bcoca**
Adds --playbook-dir option, so it will also get adjacent 'other plugins' dirs

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ansible-doc

### CODE REVIEW

**Comment by s-hertel** [comment]
I have to use a fully qualified path to get docs for plugins, is that expected?

**Comment by bcoca** [comment]
yes

**Comment by s-hertel** [comment]
This is nice to have, found a bug in collection docs.

**Comment by bcoca** [comment]
next, read collection docs:
 ``` ansible-doc -t collection jctanner.cloud_stuff ```

**Review by nitzmahone — APPROVED** [review]
LGTM, nice quick fix

**Pull request merged**
