### PR TITLE
New Windows Module: win_file_compression

### PR DESCRIPTION
**Pull request by mhunsber**
##### SUMMARY

Adding a module for setting NTFS compression on folders/subfolders. This is shown as the `Compressed` flag in the file attributes, which you can get by using `win_stat`.

I named it `win_compact` so that it doesn't get confused with zip compression. The name is based on the command line tool, [compact](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/compact), but I use the CIM command instead, since PowerShell calls are preferred over command calls.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

win_compact
##### ADDITIONAL INFORMATION

if you have the folder structure:
```
My Folder
| file1
| file2
└ anotherfolder
  | anotherfile1
  | anotherfile2
```

```yaml
win_compact:
  path: My Folder
  compressed: yes
  recurse: no
```
will compress My Folder, file1, and file2.
```yaml
win_compact:
  path: My Folder
  compressed: yes
  recurse: yes
```
will compress My Folder, file1, file2, anotherfolder, anotherfile1, and anotherfile2

### CODE REVIEW

**Comment by mcassaniti** [comment]
Can I suggest a name change to win_ntfs_compress? I know that makes for a rather long module name, but it is obvious for functionality. Otherwise it looks fine.

**Comment by jborean93** [comment]
Add to potential candidates, `win_file_compression`. Technically the file system needs to support compression and it's not just NTFS, although I'm not aware of any other filesystems that do support this.

**Comment by chopraaa** [comment]
Yep, it's just NTFS.

**Comment by mhunsber** [comment]
I like **win_file_compression**. I would have went with **win_ntfs_compress** since I didn't add the functionality to compress single files, but I think I could add that using either [`CIM_LogicalFile`](https://docs.microsoft.com/en-us/windows/desktop/cimwin32prov/cim-logicalfile) or [`CIM_DataFile`](https://docs.microsoft.com/en-us/windows/desktop/cimwin32prov/cim-datafile). Both have the (Un)CompressEx methods. The recurse option could just be ignored if *path* is a file

**Comment by mhunsber** [comment]
Okay, I went with **win_file_compression**. I also made it so you can un/compress single files if `path` is file.

I also changed the way it checks for whether or not it needs to perform a change. Before, it always looped through the subfolders until it found one that did not match the compressed state. Now, you can set the `force` parameter to false in case the folder structure is really large, and it will only check compressed state of `path`. I figured if there is reason to compress a folder, there are likely a lot of files/folders, and looping through them all could take a while. Also, there aren't many ways a child item would be compressed/uncompressed when the parent isn't.

**Comment by mcassaniti** [comment]
Wouldn't it make more sense to not loop through folders based on the `recurse` parameter when checking what folders to apply compression to? Using `force` is not intuitive, especially when you've got a `recurse` parameter.

**Comment by mhunsber** [comment]
recurse is an option for the (un)compress methods, which get called on the parent directory. The force option changes how much effort the module puts in to deciding if the (un)compress method needs to be called.
It's almost like `recurse` would be better named `apply_recursively` and `force` would be `check_recursively`.

To make the case for the extra option, if you're unsure if `path` is compressed, but know that it's contents are all the same state, you would use both `recurse` and `force=no` because you don't want to have to check every single subfolder and file if the parent folder does happen to be compressed. But if the parent folder isn't compressed, you want to make sure that change is applied to all children.

If you can think of a better UI, I'm for it. I know the force option is a bit unintuitive. Possibly make the recurse option a string with choices like "top directory only", "apply recursively" and "check recursively".

**Comment by mhunsber** [comment]
@ShachafGoldstein I haven't heard any feedback on this in a while. Is there something you need from me still? Thanks.

**Comment by ShachafGoldstein** [comment]
Since it's a new module and then freeze for 2.9 is imminent, it needs @jborean93 or @nitzmahone

**Comment by jborean93** [comment]
@mhunsber I hope you don't mind but I've slightly tweaked the code with the following:

* The biggest change was using `compressed: bool` to `state: absent|present` to better align with Ansible modules. It still acts the same as before though
* Added `-Force` to `Get-Item` so this works for hidden files and folders, also added a test
* Remove more explicit mentions of NTFS to actually checking if the file system supports it or not https://github.com/ansible/ansible/pull/56475/files#diff-15ce63ee001039819b9cdf6f29e96777R44
* Removed uneeded duplicate dir/file loop into just the 1 which loops all files and directories https://github.com/ansible/ansible/pull/56475/files#diff-15ce63ee001039819b9cdf6f29e96777R83
    * This also saves us another `Get-Item` check as we use `EnumerateFileSystemInfos` on the directory object which already gives us the Attributes required
* Use the builtin dependency for ansible-test to create the temp folder. This just makes it cleaner when ensuring the dir is removed on exit

**Review by jborean93 — APPROVED** [review]
Really sorry for the delay but thank you for working on this and sticking through it. Still unsure what the whole collections result in 2.10 will be but whether the Windows modules go, this will follow it.

**Pull request merged**
