### PR TITLE
Add EC2 instance "termination protection" support and "source_check_dest" changeability

### PR DESCRIPTION
**Pull request by amandolo**
Another EC2 option useful during provisioning.

### CODE REVIEW

**Comment by jimi-c** [comment]
Can you modify the termination protection on an instance after its created? If so, it looks like your patch only modifies the setting when they're created.

**Comment by amandolo** [comment]
I modified the module to permit changes to "termination_protection" and "source_dest_check" after instance creation (when STATE is "running" or "stopped").

The EC2 module has these behaviours:
- state "present/absent" only create/terminate instances
- state "running/stopped" change instances state and change some options (for now only termination_protection, source_dest_check).

**Comment by analytically** [comment]
+1

**Comment by zytek** [comment]
+1

**Comment by szibis** [comment]
+1

**Comment by jimi-c** [comment]
When testing this, I got the following API error:

<pre>
You may only modify the sourceDestCheck attribute for VPC instances
</pre>

So it appears this can only be True when the instance is on a VPC. Also, it appears that some additional commits have snuck into this branch, so we cannot merge this as it stands. Could you please correct the above issue and flatten the relevant commits into a single commit? Thanks!

**Pull request closed without merging**
