### PR TITLE
Added IAM role support

### PR DESCRIPTION
**Pull request by lwade**
Per issue #3532

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks...

Does this need a bit more documentation on when to set it or not, and how to use it?

**Comment by lwade** [comment]
Yes, I'll make a note to add a section on the AWS pages.

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by maludwig** [comment]
Can you give an example of how to Launch a new Instance with a given IAM Role? This doesn't seem very clear to me.

**Comment by maludwig** [comment]
I FIGURED IT OUT, took forever, but I figured it out and it's actually embarrassingly easy:

```
instance_profile_name: ROLE_NAME
```

To get the "profile name", go to IAM, click Roles, click your Role, and look for:

```
ARN arn:aws:iam::123456789:instance-profile/ROLE_NAME
```

**Comment by elnur** [comment]
Is there a way to create an instance profile via Ansible tho?

**Pull request merged**
