### PR TITLE
Fix broken links after docs restructure

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY
Correct paths in multiple `:doc:` links
Ensure references are correct
Add missing references where possible

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docs

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel e10e0d42d8) last updated 2018/04/09 21:15:12 (GMT +1000)
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/will/src/ansible/lib/ansible
  executable location = /Users/will/src/ansible/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION
See e.g. the bottom of http://docs.ansible.com/ansible/latest/plugins/callback.html for an example of the types of failures this addresses.

### CODE REVIEW

**Review by dharmabumstead — CHANGES_REQUESTED** [review]
Thanks for the PR, @willthames. Many of these were addressed in https://github.com/ansible/ansible/pull/37382. We are switching to use 'refs' instead of 'doc' links.

**Comment by willthames** [comment]
No worries @dharmabumstead, I'll further adjust this to reflect that.

What are your thoughts on `:attr:`, `:py:meth:` - they all seem to create spurious warnings and without the code base in the docs, aren't ever going to achieve much.

**Comment by willthames** [comment]
I've updated this PR to use ref links but need to fully test all the references work as expected. 

It would be good if the plugin/module reference disambiguation work was resolved before this otherwise this will typically be linking to plugins whether or not modules were preferred.

**Comment by willthames** [comment]
@dharmabumstead ready_for_review

I can't seem to see the plugins generated docs under rst any more - where have they gone?

**Comment by acozine** [comment]
@willthames thanks for all the work that went into this PR. These changes have been made in other PRs, so I'm going to close this one to clean the slate. We're close to eliminating the last build errors in `make webdocs` - if you have time and interest, I'd welcome help with the last stubborn holdouts, including ways to address the `:attr:` links.

**Pull request closed without merging**
