### PR TITLE
Replace launchpad.net/api with api.launchpad.net @ apt_repository module

### PR DESCRIPTION
**Pull request by DomenickD3**
##### SUMMARY

See: https://help.launchpad.net/API and https://help.launchpad.net/API/Hacking
launchpad.net is the web endpoint
api.launchpad.net is the web services (api) endpoint

When using the `apt_repository` module with molecule, and setting up/tearing down my test environment frequently, I intermittently ran into issues with the web endpoint. Namely, in some cases, the endpoint will return 0 bytes of data (presumably if the data is cached). The api endpoint seems to return the full object even if it is 'not modified'. The result of 0 bytes of data being returned was a `JSONDecodeError` when attempting to add a ppa repository.

```yaml
- name: Add ansible repository
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
    update_cache: true
    state: present
```

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

before:
```python-traceback
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1697388928.1372871-71804-82371821093402/AnsiballZ_apt_repository.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1697388928.1372871-71804-82371821093402/AnsiballZ_apt_repository.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1697388928.1372871-71804-82371821093402/AnsiballZ_apt_repository.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.apt_repository', init_globals=dict(_module_fqn='ansible.modules.apt_repository', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py", line 765, in <module>
  File "/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py", line 709, in main
  File "/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py", line 540, in add_source
  File "/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py", line 482, in _get_ppa_info
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fatal: [ubuntu]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1697388928.1372871-71804-82371821093402/AnsiballZ_apt_repository.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1697388928.1372871-71804-82371821093402/AnsiballZ_apt_repository.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1697388928.1372871-71804-82371821093402/AnsiballZ_apt_repository.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.apt_repository', init_globals=dict(_module_fqn='ansible.modules.apt_repository', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 765, in <module>\n  File \"/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 709, in main\n  File \"/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 540, in add_source\n  File \"/tmp/ansible_ansible.builtin.apt_repository_payload_kckl7er1/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 482, in _get_ppa_info\n  File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

after:
```yaml
changed: [ubuntu] => {
    "changed": true,
    "diff": [],
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": null,
            "install_python_apt": true,
            "mode": null,
            "repo": "ppa:ansible/ansible",
            "state": "present",
            "update_cache": true,
            "update_cache_retries": 5,
            "update_cache_retry_max_delay": 12,
            "validate_certs": true
        }
    },
    "repo": "ppa:ansible/ansible",
    "sources_added": [
        "/etc/apt/sources.list.d/ppa_ansible_ansible_jammy.list"
    ],
    "sources_removed": [],
    "state": "present"
}
```

### CODE REVIEW

**Comment by webknjaz** [comment]
This matches the traceback found in your CI @ https://dev.azure.com/ansible/ansible/_build/results?buildId=92843&view=logs&j=d907cba1-93bb-59aa-5a16-c17b92c8382e&t=0148a3be-67ae-5c60-841a-73bf0e52783e&l=589:
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 133, in <module>
  File "<stdin>", line 125, in _ansiballz_main
  File "<stdin>", line 73, in invoke_module
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 765, in <module>
  File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 709, in main
  File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 540, in add_source
  File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 482, in _get_ppa_info
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by webknjaz** [comment]
I tried making a query manually and it succeeded with HTTP 200 OK and legit JSON payload:
```console
$ curl -s 'https://launchpad.net/api/1.0/~ansible/+archive/ubuntu/ansible' | python -m json.tool
{
    "self_link": "https://launchpad.net/api/1.0/~ansible/+archive/ubuntu/ansible",
    "web_link": "https://launchpad.net/~ansible/+archive/ubuntu/ansible",
    "resource_type_link": "https://launchpad.net/api/1.0/#archive",
    "owner_link": "https://launchpad.net/api/1.0/~ansible",
    "name": "ansible",
    "displayname": "ansible",
    "reference": "~ansible/ubuntu/ansible",
    "distribution_link": "https://launchpad.net/api/1.0/ubuntu",
    "private": false,
    "suppress_subscription_notifications": false,
    "dependencies_collection_link": "https://launchpad.net/api/1.0/~ansible/+archive/ubuntu/ansible/dependencies",
    "description": "Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications\u2014 automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.\n\nhttp://ansible.com/\n\nIf you face any issues while installing Ansible PPA, file an issue here:\nhttps://github.com/ansible-community/ppa/issues",
    "signing_key_fingerprint": "6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367",
    "require_virtualized": true,
    "authorized_size": 2048,
    "external_dependencies": null,
    "publishing_method": "Local",
    "repository_format": "Debian",
    "publish": true,
    "relative_build_score": 0,
    "http_etag": "\"5469048df5b63089f291f5b00f7d4b55b23411f7-e13735f100f108cf12cd62c5ecbb38f27d8cddae\""
}
```

**Comment by webknjaz** [comment]
Can it be that the web service is just unstable and returns something like HTTP 500 with HTML payload sometimes?

**Comment by webknjaz** [comment]
@DomenickD3 do you know of any documented difference between the API endpoints? Does one have caching problem and the other doesn't? Do we process "cache still valid" cases incorrectly? Should we skip abort refreshing cache on zero bytes? Are there any HTTP headers indicating the cache-control state? Is the HTTP response status 304? Do you have a dump of the full HTTP request and response?
I'm not convinced that merely changing the URL would fix the issue. Any thoughts on this?

**Comment by DomenickD3** [comment]
@webknjaz I confirmed via print statement debugging that when the error occurs, that the response that gets read is 0 bytes. I don't know of any documented differences between the API endpoints. I asked a question in their IRC but didn't get any response within 30 mins before I had to leave.

Can you test something for me?

If you access from your browser (I am using chrome btw):
https://launchpad.net/api/1.0/~ansible/+archive/ansible
... and refresh once (or maybe a few times?)

Do you  see (on subsequent requests):
"This XML file does not appear to have any style information associated with it. The document tree is shown below."

Some of the response headers I see are the following (note 200 response, content length is 0)
```
Status Code: 200 OK
Remote Address: 185.125.189.222:443
Content-Length: 0
```

Now access https://api.launchpad.net/1.0/~ansible/+archive/ansible
Refresh as many times as you want. If the data is cached you will see 304 not modified, but the payload will still be returned.

```
Status Code: 304 Not Modified
Remote Address: 185.125.189.225:443
```

I can collect more information later, but can you verify what you see when you test the above? (obviously browser will be different than whatever python is doing, but the symptom here looks similar to what I observed)

**Comment by webknjaz** [comment]
@DomenickD3 so, when using Firefox, it consistently returns XML for both endpoints when I hit F5.

**Comment by DomenickD3** [comment]
noteworthy I also see it working consistent for Firefox. Could you test in Chrome?


btw (just to clarify) the CI you linked earlier is not for my build it is for a previous one, 
I found the CI for my build and that test is not erroring:
https://dev.azure.com/ansible/ansible/_build/results?buildId=92893&view=logs&j=d907cba1-93bb-59aa-5a16-c17b92c8382e&t=0148a3be-67ae-5c60-841a-73bf0e52783e&l=376

re:

> This matches the traceback found in your CI @ https://dev.azure.com/ansible/ansible/_build/results?buildId=92843&view=logs&j=d907cba1-93bb-59aa-5a16-c17b92c8382e&t=0148a3be-67ae-5c60-841a-73bf0e52783e&l=589:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 133, in <module>
>   File "<stdin>", line 125, in _ansiballz_main
>   File "<stdin>", line 73, in invoke_module
>   File "/usr/lib/python3.8/runpy.py", line 207, in run_module
>     return _run_module_code(code, init_globals, run_name, mod_spec)
>   File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 765, in <module>
>   File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 709, in main
>   File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 540, in add_source
>   File "/tmp/ansible_apt_repository_payload_eo2jfn8c/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 482, in _get_ppa_info
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

**Comment by DomenickD3** [comment]
@webknjaz check this out

There is a "disable cache" toggle in developer tools. Notice that the 2nd screenshot has the toggle selected(at the top right). It seems that for launchpad.net when caching is enabled, 0 bytes can be returned. When caching is turned off, the request succeeds each time. For api.launchpad.net, the request will succeed with or without caching turned on.

**launchpad.net**
with caching:
image

without caching :
image

------------------------
**api.launchpad.net**
with caching(works):
image

**Comment by DomenickD3** [comment]
found this:
https://bugs.launchpad.net/launchpad/+bug/2039251

Added a comment there

**Comment by webknjaz** [comment]
> btw (just to clarify) the CI you linked earlier is not for my build it is for a previous one,

Yes, that one is coming from our nightly CI runs.

**Comment by webknjaz** [comment]
> found this: [bugs.launchpad.net/launchpad/+bug/2039251](https://bugs.launchpad.net/launchpad/+bug/2039251)
> 
> Added a comment there

Oh, nice, it looks like they're going to deploy a fix soon, and they confirmed that the endpoints are identical, so this is not a bug to fix in Ansible, but something Canonical will address on their side….

**Comment by cjwatson** [comment]
I believe this is now fixed properly in Launchpad, so you shouldn't need to work around it.  (That said, I think `api.launchpad.net` is stylistically slightly better for callers that aren't Launchpad's own web UI; I'd just suggest framing it as something other than a bug-fix.)

**Comment by DomenickD3** [comment]
Thanks @cjwatson 

@webknjaz if I rework the description here (or open a new PR) to use the api.launchpad.net endpoint, is that something we would be willing to merge?

**Comment by webknjaz** [comment]
@DomenickD3 sure, just add a non-bug changelog fragment + maybe include a link to the explanation in a code comment.

@cjwatson thanks for the fix and the input!

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
