### PR TITLE
Add support for virtual packages in apt module

### PR DESCRIPTION
**Pull request by Ernest0x**
Virtual packages in apt repos are provided from other 'providing'
packages. With this commit, ansible's apt module is taught to
to install these packages, if the name of a virtual package is
given as the package to be installed.

### CODE REVIEW

**Comment by dhozac** [comment]
So this adds all providing packages to the transaction. I'm not really familiar with how Debian uses these things, but in RPM-world, virtual provides are used to make e.g. postfix and sendmail both capable of fulfilling a dependency on an MTA. Installing every MTA in this case seems somewhat counter-intuitive to me. What are they used for here? What would be the expected use-case?

**Comment by mpdehaan** [comment]
I second the question.

A use case would be much appreciated if you can spare one.

Thanks!

**Comment by Ernest0x** [comment]
This has been useful for installing 'libsomelib-dev' packages, in which case debian has 'libsomelib-dev' as a virtual package provided by a real 'libsomelib0-dev' or 'libsomelib1-dev' package (0 and 1 or any other number here being the library major version number). Since this seems not to be useful or appropriate in other cases, maybe this behaviour should only be applied on '-dev' packages? I' m not a debian packaging expert, so, if there is any Debian dev/maintainer in the community, perhaps he could shed some light on that.

**Comment by mpdehaan** [comment]
Can the packages still be installed explicitly by name?

It seems like we may just want to require people to name the packages in
this case.

**Comment by mpdehaan** [comment]
I think I'm going to close this because you could just list the packages by name.

**Pull request closed without merging**
