### PR TITLE
Wrong file used as module #22268

### PR DESCRIPTION
**Pull request by snowsky**
##### ISSUE TYPE

 - Bugfix Pull Request

##### ANSIBLE VERSION

```
ansible 2.3 with SHA 7018aa3
```

##### SUMMARY

Take a look at #22268 

```

```

### CODE REVIEW

**Comment by sivel** [comment]
This fix disallows for the fact that modules can be written in any language and need not include only .py or .ps1.  In fact we support binaries without any file extension at all.  Enumerating a list of file extensions we support is not possible.

Instead, I recommend looking at the list of files of patterns we exclude as part of inventory for an idea on how to ignore backup or temp files.

**Comment by snowsky** [comment]
@sivel thanks for the reply. I agree. I used [this page ](http://docs.ansible.com/ansible/dev_guide/developing_modules.html)for reference. What have been excluded are .pyc and .pyo:
```
                # HACK: We have no way of executing python byte
                # compiled files as ansible modules so specifically exclude them
                ### FIXME: I believe this is only correct for modules and
                # module_utils.  For all other plugins we want .pyc and .pyo should
                # bew valid
                if full_path.endswith(('.pyc', '.pyo')):
                    continue
```
Any thoughts?

**Comment by snowsky** [comment]
@sivel the failure is not related to the patch. Could you please take a look?

**Comment by abadger** [comment]
This change would break use cases such as custom, non-python modules with documentation (which has to live in a .py file).  Example: I have a module written in perl called mymodule.pl.  I want to document it so that other people at my workplace can use ansible-doc mymodule to find out about it.  So I create the mymodule.py file with the documentation.  With this change, ansible will then find the .py file with the documentation and attempt to use it as the module instead of mymodule.pl.

@sivel's note about adding additional excludes is the right way to proceed on this.  @snowsky you've found the right section of code... If you want to add "~" as an invalid extension for modules that would be fine to me.  Please also update the FIXME comment to say that "I believe the .pyo and .pyc are only correct for modules".  If you're not interested in working on this now (I realize it's been a long time since this was opened) just let us know and someone else might take up work on it.

**Comment by snowsky** [comment]
Please @samdolan follow up, thanks.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this PR because as stated above this would break core functionality in Ansible.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourageopen dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
