### PR TITLE
Fix file to support '=' in args and remove superflous call in get_url

### PR DESCRIPTION
**Pull request by jpmens**

### CODE REVIEW

**Comment by jpmens** [comment]
How do I get rid of all that "Merge branch" stuff ... ?

**Comment by mpdehaan** [comment]
Prevention:  Alias "git pull" to "git pull --rebase" and don't use "git merge, ever".   Also, always use one branch per topic.

Cure:  Always work on a seperate branch.   to submit a pull request, switch away from your working branch to another branch and do "git merge --squash" to compress everything to one commit.

I noticed "  urlfilename = url_filename(url)

63      
- ```
     actualdest = "%s/%s" % (dest, url_filename(url))
  ```
  
  63  
- ```
     actualdest = "%s/%s" % (dest, urlfilename)
  ```
  
  "

Looks like that part of the commit doesn't do anything, and we just need the change to the file module.  I can take care of that and will leave this open to remind me to do it.

**Comment by jpmens** [comment]
Michael: you say "never use git merge" but below I should `git merge --squash`. Really merge?

The fix on line 63 removes a superflous call to url_filename(url)

**Comment by mpdehaan** [comment]
yes.

git merge devel should be "git rebase devel"

Also don't do "git pull" do "git pull --rebase"

That's where the merge commits get in there.

**Comment by mpdehaan** [comment]
closing this, submit a squashed merge version of this and I'll apply it.

**Pull request closed without merging**
