### PR TITLE
new module: manage Cisco ACI contexts with idempotency and check-mode support [network/aci/aci_context]

### PR DESCRIPTION
**Pull request by jmcgill298**
##### SUMMARY

The module is used to manage Contexts in Cisco ACI.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

modules/network/aci/aci_context.py

##### ANSIBLE VERSION

```
#ansible --version
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ntc/ansible-modules/']
  ansible python module location = /home/jmcgill/ans23/local/lib/python2.7/site-packages/ansible
  executable location = /home/jmcgill/ans23/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jmcgill298** [comment]
shipit

**Comment by dagwieers** [comment]
bot_status

**Review by dagwieers — APPROVED** [review]
LGTM. As I already reviewed this in https://github.com/datacenter/aci-ansible

**Comment by dagwieers** [comment]
The integration tests require ACI infrastructure, but we are going to add them as soon as possible in a form acceptable to this project. Working on it.

**Comment by dagwieers** [comment]
@privateip @devarshishah3 @jedelman8 @calfonso Your feedback is appreciated.

As this module is one of the first modules in a larger set, so any feedback we can take into account for the other modules and is greatly appreciated.

**Review by schunduri — APPROVED** [review]

**Comment by schunduri** [comment]
shipit

**Comment by dagwieers** [comment]
bot_status

**Comment by dagwieers** [comment]
shipit

**Pull request merged**
