### PR TITLE
acme_certificate: improve documentation

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Makes the documentation less Let's Encrypt specific (#39737), and improves formatting in general. Also removes "experimental" warning for ACME v2.

##### ISSUE TYPE
Docs Pull Request

##### COMPONENT NAME
acme_certificate

##### ANSIBLE VERSION
```
2.6.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
I noticed two problems with the generated documentation (https://docs.ansible.com/ansible/devel/modules/acme_certificate_module.html):
1. `C(...)` and `I(...)` behave identical (italics) in the module description, but differently (code and italics) when describing parameters.
2. The choices for parameter `acme_version` are `1` and `2` (integers), but they are printed as `yes` (which is totally wrong!) and `2`!

**Comment by resmo** [comment]
shipit

**Comment by felixfontein** [comment]
@resmo thanks for merging!
How should we proceed with the docs generation errors? Should I open a new ticket for that? Or is there something we can do to improve the situation?

**Comment by felixfontein** [comment]
I think I've tracked the problems down; I've opened a ticket in #40012.

**Pull request merged**
