### PR TITLE
redirecting the conjur lookup plugin to correct collection

### PR DESCRIPTION
**Pull request by anshulbehl**
##### SUMMARY

Pointing the plugin to correction cyberark collection.

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by izgeri** [comment]
cc @cyberark-bizdev this looks correct to me, can you please also verify?

**Comment by cyberark-bizdev** [comment]
> cc @cyberark-bizdev this looks correct to me, can you please also verify?

Yes, it looks correct to me too. I will approve.

**Review by cyberark-bizdev — APPROVED** [review]

**Review by izgeri — APPROVED** [review]

**Comment by izgeri** [comment]
@anshulbehl what else is needed to get this merged and released? if there's anything we (CyberArk) can do to help, please let us know.

**Comment by anshulbehl** [comment]
@izgeri Once this gets merged I will remove the file from community.general collection as well. That should be it.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged.
As `stable-2.10` has already been branched you need to create a backport to ansible/ansible:stable-2.10

**Comment by izgeri** [comment]
@anshulbehl is creating the backport something that you can help with?

**Comment by anshulbehl** [comment]
#70143 is the backport pull request

**Pull request merged**
