### PR TITLE
vmware inventory fixes and features

### PR DESCRIPTION
**Pull request by bcoca**
added environment variables as config overrides for vmware inventory
fixed vmware properties, was getting parent's properties
cache now actually works
removed tags, they were not the ones i was looking for
renamed cache defaults fixed ini file to match
avoid several tracebacks you got if misconfigured

this is a resubmit of #8138 (incorporating feedback), trying to update that branch brought in other unwanted commits

### CODE REVIEW

**Comment by kleppy** [comment]
Made an edit to line 91 to get it to work for me. 
                'vmware_name' : host.name,

# 'vmware_parent': host.parent.name,

```
            'vmware_parent': host.parent_name,
           }
```

Tested against VCenter Version 5.1.0 Build 1465747 .

**Comment by mpdehaan** [comment]
cc @lukesneeringer @cchurch

**Comment by mpdehaan** [comment]
(note to team:  we need to make sure cache controls are effectively leveraged/disabled like ec2 in Tower's usage)

**Comment by bcoca** [comment]
@kleppy, weird, it used to work with my 5.1 (we just decommissioned it so I
cannot test).

I'll add a test and use one or the other on success, probably update it
tonight.
​

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
