### PR TITLE
mount: Check if src exists before mounted

### LINKED ISSUE #59183: mount module should fail when src doesn't exist when state is mounted
##### SUMMARY
If `src` doesn't exist in `mount` module when `state` is `mounted`, it still proceeds. It adds the entry to /etc/fstab like it would when `state` is `present`. But because it's `mounted` the task should fail.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
```

##### CONFIGURATION

```paste below
no output
```

##### OS / ENVIRONMENT

Debian 10

##### STEPS TO REPRODUCE

```yaml
- mount:
    src: /pathdoesnotexist
    path: /mnt
    opts: discard,nofail,defaults
    fstype: ext4
    state: mounted
```

##### EXPECTED RESULTS

It should give an error saying that `src` doesn't exist.

##### ACTUAL RESULTS

```paste below
ok: [5.6.7.8] => {
  "changed": false,
    "dump": "0",
    "fstab": "/etc/fstab",
    "fstype": "ext4",
    "invocation": {
        "module_args": {
            "backup": false,
            "boot": true,
            "dump": null,
            "fstab": null,
            "fstype": "ext4",
            "opts": "discard,nofail,defaults",
            "passno": null,
            "path": "/mnt",
            "src": "/pathdoesnotexist",
            "state": "mounted"
        }
    },
    "name": "/mnt",
    "opts": "discard,nofail,defaults",
    "passno": "0",
    "src": "/pathdoesnotexist"
}
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes: #59183

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/system/mount.py

### CODE REVIEW

**Review by jtyr — APPROVED** [review]
LGTM

**Comment by Tomorrow9** [comment]
Hi @Akasurde, if I mount a network path then it will always return path not exist error. Thanks.

**Comment by Akasurde** [comment]
@Tomorrow9 Could you please provide me the playbook to reproduce this ? Thanks.

**Comment by mscherer** [comment]
@Akasurde this precise task fail: https://github.com/gluster/gluster.org_ansible_configuration/blob/master/roles/cert_syncer/tasks/main.yml#L37

The error message look like this:

    fatal: [proxy02.int.rht.gluster.org]: FAILED! => {"changed": false, "msg": "Unable to mount 172.24.1.183:certificates as it does not exist"}

**Pull request merged**
