### PR TITLE
Fix errors with long output and simplified p.poll handling

### PR DESCRIPTION
**Pull request by lberruti**
Related to #5832

### CODE REVIEW

**Comment by jctanner** [comment]
@lukyanov any chance you could test this? You are the only one so far who seems to have a testcase that can consistently reproduce the issue. If you can, it would be great to know more about your environment too, so that we can build our own testcase and prevent future regressions.

**Comment by mpdehaan** [comment]
I should also point out multi-line if/else comments need to be expressed over multiple lines for readability.

**Comment by lukyanov** [comment]
The fix works! Errors not found :) Thanks.

**Comment by lukyanov** [comment]
Any chances to merge it into devel?

**Comment by jctanner** [comment]
@lberruti this is still cutting off stdout in some instances.

https://github.com/jctanner/ansible-tests/blob/master/misc/TestSSH.py

```
for i in $(seq 1 100); do rm *.pyc ; nosetests -v ; done;
```

25% of the time, the test fails.

**Pull request closed without merging**
