### PR TITLE
postgresql_user: Add role_grant, role_revoke parameters to set / change role membership of users; add comment parameter

### PR DESCRIPTION
**Pull request by Andersson007**
postgresql_user: Add role_grant, role_revoke parameters to set / change role membership of users.
Add comment parameter to set comment on user

The postgresql_user module allows to set privileges on tables or databases during user creation or altering but there is no possibility to define membership at the same time that would be quite convenient and useful.

To implement this, following parameters have been added:
* role_grant: _rolename_ Grant membership in role to user.
* role_revoke: _rolename_ Revoke membership in role from user.

This is an important possibility to add comment on role when create it, for this the following option has been added:
* comment: _Comment text here_

### CODE REVIEW

**Comment by Andersson007** [comment]
bot_status

**Comment by Andersson007** [comment]
It also fixes documentation for https://github.com/ansible/ansible/issues/15794

**Comment by Andersson007** [comment]
shipit

**Comment by Andersson007** [comment]
ready_for_review

**Comment by dagwieers** [comment]
Always, always, always do `git pull --rebase` !

**Comment by Andersson007** [comment]
Thank you for advice! I'll try.

**Pull request closed without merging**
