### PR TITLE
Added Windows facts for licensing and activation

### PR DESCRIPTION
**Pull request by rhydian76**
##### SUMMARY
Added facts for Windows licensing.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/windows/setup.ps1

##### ADDITIONAL INFORMATION
Windows facts for Licensing information:
ansible_winlicense_edition - e.g. Windows Server Standard
ansible_winlicense_channel - e.g. MAK or KMS
ansible_winlicense_partprodkey - Partial product key
ansible_winlicense_status - e.g. Licensed/Activated, Unlicensed, OOB Grace period license.

### CODE REVIEW

**Comment by dagwieers** [comment]
We already have a module **win_product_facts** with specific information about Windows.
This is a separate module because the information was deemed too sensitive to put in the default facts.

Not sure if this belongs better in **win_product_facts**, or should be available by default.

**Review by dagwieers — APPROVED** [review]
Apart from where this should go, the additions LGTM.

**Comment by rhydian76** [comment]
Thats a fair comment. However these changes don't expose any sensitive information I believe. Only license status of the server, a small part of the product key and license type.

**Comment by jhawkesworth** [comment]
Thanks for your PR but I am -1 on adding this into default facts, which are already much slower than I would like so would prefer this in win_product_facts.  I could be persuaded that they belong in default facts if you can share a use case which would be convoluted using a different facts module.

**Comment by rhydian76** [comment]
I will change this to be part of the win_product_facts module and submit a new PR.

**Pull request closed without merging**
