### PR TITLE
Moving samples/ out of project root into test/

### PR DESCRIPTION
**Pull request by dagwieers**
##### Issue Type:

- Feature Pull Request
##### Summary:

Since samples/ is used for v2 testing, it fits better into the existing test/ structure.

This helps a bit to remove some of the clutter in the project root.

### CODE REVIEW

**Comment by bcoca** [comment]
~~don't them make more sense under examples?~~ v2 testing, nvmd

**Comment by bcoca** [comment]
cc @jimi-c are these still relevant?

**Comment by jimi-c** [comment]
They're not really relevant and can probably just be nuked instead, unless there's anything we want to  turn into integration tests.

**Comment by dagwieers** [comment]
Even better.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
