### PR TITLE
module nagios.py: added 'acknowledge' action

### PR DESCRIPTION
**Pull request by tgoetheyn**
##### SUMMARY

Adds the option "acknowledge" to the module actions.
This way the module can be used to acknowledge open host & service problems in nagios

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

nagios
##### ADDITIONAL INFORMATION

based on the existing nagios module

```paste below

```

### CODE REVIEW

**Comment by tgoetheyn** [comment]
Fixed the sanity error

**Comment by tgoetheyn** [comment]
@tbielawa 
Is it ok for you if I also add a "SCHEDULE_FORCED_SVC_CHECK" to the module?
We use this to "reset" service problems for passive event , so it still fits in the purpose of the module

> The nagios module has two basic functions: scheduling downtime and toggling alerts for services or hosts.

Or will this make the module to bloated?

**Comment by tgoetheyn** [comment]
I took my change and added it because i really need this function in my organization.
Hope you like it ;-)

**Comment by willemdh** [comment]
Nice addition @tgoetheyn ! When could this pr get merged pls? :)

**Comment by manzarek123** [comment]
merge it plz :)

**Comment by tgoetheyn** [comment]
cannot rebase because i managed to delete the forked repo :-(

created net PR #59922

**Pull request closed without merging**
