### PR TITLE
docker_login: Hide password from response

### LINKED ISSUE #32869: If logged in, docker_login will return the current password in results
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_login

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/foo/Documents/Repos/foo/ansible/ansible.cfg
  configured module search path = [u'/Users/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_RETRIES(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = 3
DEFAULT_HOST_LIST(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = [u'/Users/foo/Documents/Repos/foo/ansible/inventory']
DEFAULT_ROLES_PATH(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = [u'/Users/foo/Documents/Repos/foo/ansible/roles']
HOST_KEY_CHECKING(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS Sierra connecting to Ubuntu 16.04.03 and Docker Server Version: 17.09.0-ce

##### SUMMARY

If already logged in to the Docker Hub on the target machine, running a docker_login task with the wrong credentials will return the actual password in the results.

##### STEPS TO REPRODUCE

1. Run the playbook below, entering the correct password when prompted
2. Run the playbook below, entering the wrong password when prompted

__NOTE that this only seems to work the first run after logging in successfully. Subsequent runs will return `"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"`__

```yaml
---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: hub_username
      prompt: "Enter your Docker Hub username"
      private: no
    - name: hub_email
      prompt: "Enter your Docker Hub email address"
      private: no
    - name: hub_password
      prompt: "Enter your Docker Hub password"
      private: yes
  tasks:
  - name: login to Docker Hub
    docker_login:
      username: "{{ hub_username }}"
      email: "{{ hub_email }}"
      password: "{{ hub_password }}"
    register: login_results
  - debug: 
      var: login_results
```

##### EXPECTED RESULTS

Failed login attempt

##### ACTUAL RESULTS

```
changed: [node1] => {
    "changed": true,
    "failed": false,
    "invocation": {
        "module_args": {
            "api_version": null,
            "cacert_path": null,
            "cert_path": null,
            "config_path": "~/.docker/config.json",
            "debug": false,
            "docker_host": null,
            "email": "<redacted>",
            "filter_logger": false,
            "key_path": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "reauthorize": false,
            "registry_url": "https://index.docker.io/v1/",
            "ssl_version": null,
            "state": "present",
            "timeout": null,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null,
            "username": "<redacted>"
        }
    },
    "login_result": {
        "email": "<redacted>",
        "password": "<redacted>",
        "serveraddress": "https://index.docker.io/v1/",
        "username": "<redacted>"
    }
}
```

__NOTE that if one adds `reauthorize: yes`, this issue is not present.__

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes: #32869

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/docker/docker_login.py

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@lachlancooper Could you please review this ?

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Comment by ntwrkguru** [comment]
@Akasurde Sort of fixed. It does, indeed, no longer echo the password, however it still shows `failed: false` even when an incorrect password is used.

Here is when an incorrect password is used after successfully logging in. Notice that `changed: true` is correct (it did change the password locally), but it should also fail as the credentials are incorrect. Seems that the logic to fail is looking at whether or not the module was successful in writing to `~/.docker/config.json` but doesn't actually attempt to authenticate to the Hub API. Realizing that there is no state involved in a Hub login, I feel the module should attempt auth anytime the play is executed.

```
TASK [debug] *****************************************************************************************************************************************
ok: [localhost] => {
    "login_results": {
        "changed": true, 
        "failed": false, 
        "login_result": {
            "email": "xxx@xxx.xxx", 
            "serveraddress": "https://index.docker.io/v1/", 
            "username": "xxx"
        }
    }
}
```

**Pull request merged**
