### PR TITLE
Extend interfaces_file to handle sources-directory

### LINKED ISSUE #37808: interfaces_file doesn't understand source-directory
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

interfaces_file

##### ANSIBLE VERSION

```
ansible 2.6.0 (interfaces_file_source_directory 60751bce19) last updated 2018/03/22 19:44:17 (GMT -600)
  config file = /home/schallee/devel/ansible/src/ansible.cfg
  configured module search path = [u'/home/schallee/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/schallee/devel/ansible/src/lib/ansible
  executable location = ./bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```

##### CONFIGURATION

ANSIBLE_SSH_CONTROL_PATH_DIR(/home/schallee/devel/ansible/src/ansible.cfg) = ~/.ssh/controls
CACHE_PLUGIN(/home/schallee/devel/ansible/src/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/schallee/devel/ansible/src/ansible.cfg) = cache
CACHE_PLUGIN_TIMEOUT(/home/schallee/devel/ansible/src/ansible.cfg) = 3600
COMMAND_WARNINGS(/home/schallee/devel/ansible/src/ansible.cfg) = True
DEFAULT_FORKS(/home/schallee/devel/ansible/src/ansible.cfg) = 10
DEFAULT_GATHERING(/home/schallee/devel/ansible/src/ansible.cfg) = smart
DEFAULT_STDOUT_CALLBACK(/home/schallee/devel/ansible/src/ansible.cfg) = debug
DEPRECATION_WARNINGS(/home/schallee/devel/ansible/src/ansible.cfg) = True

##### OS / ENVIRONMENT

Debian Stretch amd64

##### SUMMARY

interfaces_file does not handle source-directory keyword. It supports "source-dir" which is not documented but not "source-directory" which is.

https://manpages.debian.org/stretch/ifupdown/interfaces.5.en.html

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  tasks:
    - name: parse interfaces file
      interfaces_file:
      register: interfaces_output

```
Eample interfaces file triggering the issue:

```
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

allow-hotplug eth0
iface eth0 inet dhcp

```

##### EXPECTED RESULTS

Interface file is successfully parsed.

##### ACTUAL RESULTS

```
TASK [parse interfaces file] ***************************************************
fatal: [knothole]: FAILED! => {
    "changed": false
}

MSG:

misplaced option source-directory /etc/network/interfaces.d
 in line 3

```

### PR DESCRIPTION
**Pull request by schallee**
##### SUMMARY

Fixes #37808 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

interfaces_file

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /home/schallee/devel/ansible/ansible.cfg
  configured module search path = [u'/home/schallee/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]


```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by hryamzik** [comment]
LGTM

**Review by obourdon — APPROVED** [review]

**Comment by obourdon** [comment]
However I do not think that this change is complete because as a user I would expect that parsing such a configuration will also populate the ifaces dictionary with underlying elements

**Comment by obourdon** [comment]
@gundalow thanks for final review and merge

**Comment by obourdon** [comment]
@ansibot can someone add the shipit flag to this PR please

**Comment by obourdon** [comment]
@ansibot may be the stale_ci label is still valid, I do not see relationship between this PR and doc building issues

**Comment by gundalow** [comment]
There was an issue that got introduced into devel during the test update. I've triggered a rerun of CI which should pass.

**Comment by obourdon** [comment]
@gundalow many thanks for your help

**Pull request merged**
