### PR TITLE
Added ansible_ssh_pass mention to the Inventory & Patterns documentation chapter

### PR DESCRIPTION
**Pull request by Tinche**
As per https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/ZFxkx4wbY9g.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Yes, though putting the password in the inventory file is so sufficiently scary that I'd recommend we not suggest people do it.

I can possibly see it being useful for external inventory sources in limited scenarios, but here, I wouldn't want to encourage that.  That variable ends up in hostvars and it's just not good IMHO.

**Comment by Tinche** [comment]
Educating your users on what is a good idea and what isn't is fine. Having undocumented, potentially useful features is iffy. I was interested in this feature and found out about it through a Google search that turned up a pull request.

**Comment by jpmens** [comment]
This _should_ really be documented together with a BIG FAT warning, of course.

**Comment by dwt** [comment]
+1 There are cases where it's useful. (Some of our servers have a rescue mode where a random password is generated by our hoster. If we want to automate that, we need to save that password somewhere temporarily to login via ssh there.

**Pull request closed without merging**
