### PR TITLE
rhevm: Refactor & fix validate-modules issues

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:

* Adding parameter types
* Fix validate-modules issue
* Improve parameter types and resulting changes

This PR needs to be verified and tested by maintainer(s).

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
rhevm

### CODE REVIEW

**Comment by dagwieers** [comment]
The CI failure is related to an undocumented parameter that I added.

**Comment by dagwieers** [comment]
bot_skip

**Comment by dagwieers** [comment]
We have a fix for the sanity tests for this issue at: #52497

**Comment by dagwieers** [comment]
@gundalow This code has not been refactored. The only change is turning a string into a proper integer, which at best is a fix.

**Review by mwperina — APPROVED** [review]
Looks good to me

**Comment by dagwieers** [comment]
@gundalow Can this one be merged ?

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
rebuild_merge

**Comment by dagwieers** [comment]
That won't work because the tests are expected to fail.

> The CI failure is related to an undocumented parameter that I added.

**Comment by gundalow** [comment]
Only CI failure is

> lib/ansible/modules/cloud/misc/rhevm.py:0:0: E309 version_added for new option (password) should be '2.8'. Currently StrictVersion ('0.0')

Merging

**Pull request merged**
