### PR TITLE
Add Pure Storage Volume module

### PR DESCRIPTION
**Pull request by sdodsley**
SUMMARY

Storage module for Pure Storage FlashArray device. Module to create/delete/modify volumes

ISSUE TYPE

New Module Pull Request
COMPONENT NAME

purefa_volume
ANSIBLE VERSION

ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pureuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

### CODE REVIEW

**Comment by sdodsley** [comment]
@gundalow As requested separate PR for each remaining module

**Comment by sdodsley** [comment]
@gundalow  : Can you review, please?

**Comment by drew-russell** [comment]
@sdodsley The examples include `fa_api_token` but the variable name is just `api_token` in the utils module so in its current state it will error out. 

In regards to the `state` variable I personally am not a big fan of it. I know its common across different modules but I personally prefer something like `action` instead. To me state just does not mess well with the infrastructure world. That being said, its not a deal breaker at all.

I would also include some more information around what modify does in the documentation. Or even break that into its own state/action. That way there is a clear delineation around creating and modifying the volume. 

*Edit*

Another thing I forgot to mention was around the `size` variable. I know you have it as not being required and set to 1G by how often do people actually create a 1G volume? I can see that causing issues. What if you include something with `required_if` from the module utils that says "if state = present, size must be defined"?

**Comment by sdodsley** [comment]
@drew-russell  Fixed the documentation typo. I see what you say about the `state `v. `action`, but that as you say, not a show-stopper.
As to the `size `parameter of 1G, we have to set an arbitrary value somewhere as the default. Why not 1G??

**Comment by drew-russell** [comment]
@sdodsley You don't have to give size an arbitrary value if you include `required_if = [('state', 'present', ('size'))]` in your main function (after argument spec).

This is basically saying "only require the size field if the user puts the state to present (i.e creates)". With this in place they won't have to include size in the delete option since its not required then.

**Comment by sdodsley** [comment]
@drew-russell size is not a required parameter in create or delete. If they create without the size option then they get an arbitrary value of 1G. There is no need to specify size with delete - that just makes no sense. The documentation makes that clear I thought.

**Comment by drew-russell** [comment]
@sdodsley Understood. I'm saying that we should make `size` required through, `required_if` instead of giving it a default value. I can't think of any situation where someone would want to create a 1G volume so it should be avoid as a default.

**Comment by sdodsley** [comment]
@drew-russell As requested I've added the `required_if`

**Comment by drew-russell** [comment]
shipit

**Review by pchauncey — APPROVED** [review]
Really nice job, I can see this getting a ton of use. I have two suggestions, both I think are optional, so I'd leave them up to you:

1. Consider adding something like the below to the `DOCUMENTATION` section.  Maybe this is covered in another pull, but I didn't find it:
```
requirements:
  - purestorage
```

2. Why not just throw a module error if we can't parse `size` and are statically setting `bytes = 0` on lines 116 and 118?  I get that we're not going to end up resizing a volume to 0, but I think the user should know that something didn't go well with parsing of a play.

**Comment by pchauncey** [comment]
shipit

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel` this will be released in `2.4.0`

**Pull request merged**
