### PR TITLE
azure - added storage account module

### PR DESCRIPTION
**Pull request by matlockx**
Added an windows azure storage module + inventory command to list storages.
A storage account is needed for the normal azure module to create a vm. The name of the storage account must therefore be provided in the azure module. This module can be combined with the azure module to create at first a storage account and then create a vm.

### CODE REVIEW

**Comment by jimi-c** [comment]
Thanks, I did notice the lack of that when testing the original azure module. We'll get this into testing as soon as possible.

**Comment by mpdehaan** [comment]
"--list-storages" should be "list storage", as storages is not a word.

Also it appears there are options in the inventory script already that ansible can't use, like --list-images that probably do not belong.

If these are returned as group_vars variables, then they should be returned by default, as ansible can't read them otherwise as it will never pass those flags.

**Comment by mpdehaan** [comment]
In all, this is a relatively large patch that also makes some changes like removing the LOCATIONS array, and I'd be interested in why.

Rather than take this one wholesale, I would ask that you break this up into smaller commits with individual commit messages explaining each step.   

Changes to the azure module should probably be in a seperate pull request than the inventory module, as well as the change to add the storage module.

The name "azure_s" for the storage module is also not sufficient, I'd expect "azure_storage", and similarly, in docs, Azure should be capitalized.   "deletes a storage" also doesn't quite seem complete, does it mean an account, a volume, etc?

**Comment by matlockx** [comment]
Location array is not gone I moved it to module utils like the ec2 approach because it is needed in more than one module. 
Azure_s is A typo. Don't know how I missed that since everything else is called azure_storage a you proposed. 
So based on your comment I will:
Split it up into the parts  azure_storage module, azure module and the inventory. 
Luckily I also have the good news that the guys from the azure SDK made a new release which fixes a critical http redirect problem so I will add that version dependency to the azure module too.

**Comment by matlockx** [comment]
New pull request based on mentioned improvements created: #7966

**Pull request closed without merging**
