### PR TITLE
Backport/2.7/47695 - pamd fixes

### PR DESCRIPTION
**Pull request by shepdelacreme**
##### SUMMARY

Backport of pamd module fixes in #47695 

- update regex to allow leading dash and retain EOF newline for #47418
- fix state: updated idempotence for #47083
- fix state: args_present idempotence for #47197
- add changelog fragment

(cherry picked from commit ef690e9)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

pamd

##### ANSIBLE VERSION

```paste below
stable-2.7
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by juliedavila** [comment]
shipit

**Comment by abadger** [comment]
```action``` needs to be re-added to the return value for 2.7.x.  It's a playbook-visible backwards incompatibility so it shouldn't be backported to a released version of ansible.

**Comment by shepdelacreme** [comment]
Ah ok...I was under the impression that since this module is in `status: preview` it is `unstable` and the API (parameters, return, etc) may change. Is that an incorrect assumption of what preview means?

**Comment by abadger** [comment]
API parameters may change between major releases (2.6.x => 2.7.x), even without a deprecation notice if the status is preview (although we discourage that, especially if the module is popular ;-).  Within a major release series (2.7.x), the API needs to stay backwards compatible.  That way users can anticipate playbook breakage on major release boundaries, not on bugfix upgrades.

**Comment by shepdelacreme** [comment]
Ah ok makes sense! I will add that back in and update the changelog fragment shortly!

**Comment by abadger** [comment]
Merged for the 2.7.2 release

**Pull request merged**
