### PR TITLE
Making hacking/env-setup init git submodules

### PR DESCRIPTION
**Pull request by msabramo**
This is more convenient than manually doing it.

```
$ source hacking/env-setup
Submodule 'lib/ansible/modules/extras' (https://github.com/ansible/ansible-modules-extras.git) registered for path 'lib/ansible/modules/extras'
Cloning into 'lib/ansible/modules/extras'...
remote: Counting objects: 18879, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 18879 (delta 8), reused 10 (delta 3)
Receiving objects: 100% (18879/18879), 5.23 MiB | 607.00 KiB/s, done.
Resolving deltas: 100% (12569/12569), done.
Checking connectivity... done.
Submodule path 'lib/ansible/modules/extras': checked out 'e64751b0eb44c8ada6a6047eaf2303d98f8f505b'
Submodule 'v2/ansible/modules/core' (https://github.com/ansible/ansible-modules-core.git) registered for path 'v2/ansible/modules/core'
Cloning into 'v2/ansible/modules/core'...
remote: Counting objects: 19202, done.
remote: Total 19202 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (19202/19202), 5.45 MiB | 601.00 KiB/s, done.
Resolving deltas: 100% (12765/12765), done.
Checking connectivity... done.
Submodule path 'v2/ansible/modules/core': checked out 'cb69744bcee4b4217d83b4a30006635ba69e2aa0'
Submodule 'v2/ansible/modules/extras' (https://github.com/ansible/ansible-modules-extras.git) registered for path 'v2/ansible/modules/extras'
Cloning into 'v2/ansible/modules/extras'...
remote: Counting objects: 18879, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 18879 (delta 8), reused 10 (delta 3)
Receiving objects: 100% (18879/18879), 5.23 MiB | 601.00 KiB/s, done.
Resolving deltas: 100% (12569/12569), done.
Checking connectivity... done.
Submodule path 'v2/ansible/modules/extras': checked out '8a4f07eecd2bb877f51b7b04b5352efa6076cce5'

Setting up Ansible to run out of checkout...

PATH=/Users/marca/dev/git-repos/ansible/bin:/Users/marca/.rvm/gems/ruby-2.1.2/bin:/Users/marca/.rvm/gems/ruby-2.1.2@global/bin:/Users/marca/.rvm/rubies/ruby-2.1.2/bin:/Users/marca/go/bin:/Users/marca/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.6/bin:/Library/Frameworks/Python.framework/Versions/2.5/bin:/Library/Frameworks/Python.framework/Versions/2.4/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Library/Frameworks/Python.framework/Versions/3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:/Users/marca/.rvm/bin
PYTHONPATH=/Users/marca/dev/git-repos/ansible/lib:
MANPATH=/Users/marca/dev/git-repos/ansible/docs/man:

Remember, you may wish to specify your host file with -i

Done!

$ bin/ansible-playbook --version
ansible-playbook 1.8 (devel 116109468c) last updated 2014/11/23 09:27:41 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 19b328c4df) last updated 2014/11/23 09:44:44 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD e64751b0eb) last updated 2014/11/23 09:48:22 (GMT -700)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/23 09:48:34 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/23 09:48:45 (GMT -700)
  configured module search path = None
```

### CODE REVIEW

**Comment by srgvg** [comment]
I disagree. What if I want to test a setup with local, uncommitted changes?

Updating the submodules is part of updating the whole tree. If you want to automate this, have some own shell script or bash alias for that. (I use `alias upansible='cd /home/serge/src/ansible/ansible && git co devel && git up && git rebase  && git submodule update --init --recursive'`)

**Comment by msabramo** [comment]
I don't understand the case that you're talking about, probably because I'm fairly new to contributing to ansible. But I will take your word for it. 

Though I wonder if your case is something that would be more typically done by someone who's more experienced? If yes, I would say that perhaps it's better to optimize for the more common case or the case that lets novices start contributing as easily as possible. The more experienced folks are better equipped to create scripts or aliases to handle their use cases. Novices don't understand how things fit together and are likely to get confused or frustrated by something that doesn't work out of the box. 

My 2 cents.

**Comment by msabramo** [comment]
I'm curious if folks have found that putting the modules in git submodules has been helpful for whatever motivated it (my guess is so that PRs could be dealt with separately and prioritized differently)?

They add some complexity, which we can see here. But I'm guessing that it's justified by making it easier for reviewers?

**Comment by srgvg** [comment]
The case is, say you do a modification to a module. Before committing that change, you obviously need to test it. Testing means running the hacking script. If that script does a submodule update, that will break with that local uncommitted change. being experienced or not doe not change that use case.

**Comment by msabramo** [comment]
Hmmm I guess I was thinking that one would run the `hacking` script just once, when you first start hacking on ansible. But I guess that is not true.

**Comment by msabramo** [comment]
@srvg: I wonder if the change that I just pushed in e1008be addresses your concern?

``` diff
diff --git a/hacking/env-setup b/hacking/env-setup
index b20515e..13c07c1 100755
--- a/hacking/env-setup
+++ b/hacking/env-setup
@@ -25,10 +25,11 @@ PREFIX_MANPATH="$ANSIBLE_HOME/docs/man"
 [[ $PATH != ${PREFIX_PATH}* ]] && export PATH=$PREFIX_PATH:$PATH
 [[ $MANPATH != ${PREFIX_MANPATH}* ]] && export MANPATH=$PREFIX_MANPATH:$MANPATH

-$GIT submodule update --init lib/ansible/modules/core
-$GIT submodule update --init lib/ansible/modules/extras
-$GIT submodule update --init v2/ansible/modules/core
-$GIT submodule update --init v2/ansible/modules/extras
+for dir in {lib,v2}/ansible/modules/{core,extras}; do
+    if [ ! -d $dir ]; then
+        $GIT submodule update --init $dir
+    fi
+done

 # Print out values unless -q is set
```

Now it will skip the git submodule stuff if the directories already exist.

**Comment by srgvg** [comment]
That might make a bit more sense, though not sure if that belongs here. Perhaps you await for upstream feedback.

**Comment by mpdehaan** [comment]
I think this would be a good discussion for ansible-devel list about how to make this easy - I like the idea of it helping out more, but I don't want to hurt some other use cases either.  Can you stop by the list and discuss there?

Thanks!

**Comment by msabramo** [comment]
@mpdehaan: Good point. Probably worthy of discussion. Posted it at https://groups.google.com/forum/#!topic/ansible-project/QWr8xITNKfU

**Pull request closed without merging**
