### PR TITLE
fixed/extended module package/zypper

### PR DESCRIPTION
**Pull request by berendt**
- Introduced new parameter no_recommends to be able to install
  and updated packages without installing recommend packages.
- Made disable_gpg_check usable with updating packages.
- Changed SuSE to SUSE in the description, because that's the
  correct name of the company. Have a look at
  http://en.wikipedia.org/wiki/SUSE for verification.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I realize this is a late response to this one -- we have had quite a backlog.   Our general standard here is to not have negative versions of package variables, thus "no_recommends" should be "recommends".

If you can update this, we'll happily merge it.

Sorry for the delay -- we have had a very large backlog.

**Comment by mpdehaan** [comment]
Didn't mean to close this, GitHub seems to have hid my "unclose" button...

**Comment by mpdehaan** [comment]
I am not sure what's up here, if you would like to resubmit we'll take it -- sorry!

**Comment by berendt** [comment]
@mpdehaan I changed no_recommends to recommends and opened a new pull request (#6753).

**Pull request closed without merging**
