### PR TITLE
only validate extensions when using dir loading

### LINKED ISSUE #18223: include_vars will only include *.yml, *.yaml, and *.json files but isn't documented as a breaking change
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Action plugins, specifically include_vars action plugin
##### ANSIBLE VERSION

I'm using 2.2 RC3

```
$ ansible --version
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

#17207 introduced a requirement that include_vars will only include files with .yaml, .yml, and .json extensions. This breaks some of our existing playbooks that have YAML-formatted vars files without a .yml or .yaml extension.

Further, this isn't documented as a breaking change.
##### STEPS TO REPRODUCE

Should be trivial to reproduce
##### EXPECTED RESULTS

Load vars files without the specific set of extensions
##### ACTUAL RESULTS

```
TASK [include_vars] ************************************************************
task path: foo.yml:8
fatal: [localhost]: FAILED! => {
    "ansible_facts": {}, 
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "my_vars_files_without_extension"
        }, 
        "module_name": "include_vars"
    }, 
    "message": "my_vars_files_without_extension does not have a valid extension: yaml, yml, json"
}
```

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

include_vars

##### ANSIBLE VERSION

```
2.2/2.3
```

##### SUMMARY

Fixes regression caused by addition of directory loading feature

fixes #18223

### CODE REVIEW

**Comment by abadger** [comment]
Looks good.  Merged to devel and cherry-picked to stable-2.2 for the 2.2.1 release.  Changelog entry created for 2.2

**Comment by onnos** [comment]
As noted in https://github.com/ansible/ansible/issues/18223, this is not fixed for vaulted files. Looks good otherwise!

**Comment by alikins** [comment]
@onnos What failures are you seeing with vaulted files?

**Comment by onnos** [comment]
@alikins It appears I got confused, I can only get this to fail on 2.2.0, the bugfix actually works. All good!

**Pull request merged**
