### PR TITLE
fixing bug in storage account sample

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY

Sample is invalid and fails

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
azure_rm_storageaccount

##### ANSIBLE VERSION
2.6

### CODE REVIEW

**Comment by samdoran** [comment]
I do not believe this change is correct. The `tags` field is a dict, not a list. 

needs_info

**Comment by zikalino** [comment]
@samdoran precisely. it was a list in a sample, I have changed it to dict, which is correct.

**Comment by samdoran** [comment]
Ah, you're correct! I read the diff backwards. Apologies.

**Comment by zikalino** [comment]
@samdoran no problem, thank you for merging :-)

**Pull request merged**
