### PR TITLE
Add os disk size property

### LINKED ISSUE #38883: azure_rm_managed_disk cannot update existing os disk
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_managed_disk

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Ubuntu 16.04.4

##### SUMMARY

We have been using 'azure_rm_virtualmachine' to create vm. After stopping the machine we would like to increase created os disk size using azure_rm_managed_disk, but updating task is failing:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the managed disk: Azure Error: PropertyChangeNotAllowed\nMessage: Changing property 'creationData' is not allowed.\nTarget: creationData"}
```
##### STEPS TO REPRODUCE

1. Create vm instance with azure_rm_virtualmachine
2. Stop the instance (creating the machine with azure_rm_virtualmachine and 'started' parameter set to 'no' doesn't work.)
3. Update created os disk with azure_rm_managed_disk

```yaml

- name: "Create VM"
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    virtual_network_name: "{{ virtual_network_name }}"
    network_interface_names: "{{ network_interface_name }}"
    storage_account_name: "{{ storage_account_name }}"
    name: "{{vm_name}}"
    vm_size: "{{ vm_size_sku }}"
    image:
      offer: "{{ os_image_offer }}"
      sku: "{{ os_image_sku }}"
      publisher: "{{ os_image_publisher }}"
      version: "{{ os_image_version }}"
    managed_disk_type: Standard_LRS
    started: no

- name: "Power off the machine"
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{vm_name}}"
    allocated: no

- name: "Increase disk size"
  azure_rm_managed_disk:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group_name }}"
    disk_size_gb: "{{ azure_disk_size }}"
    managed_by: "{{ vm_name }}"

```

##### EXPECTED RESULTS

We expect that the task will update existing disk.

##### ACTUAL RESULTS

```
"msg": "Error creating the managed disk: Azure Error: PropertyChangeNotAllowed\nMessage: Changing property 'creationData' is not allowed.\nTarget: creationData"
```

### PR DESCRIPTION
**Pull request by spmp**
##### SUMMARY
Add `os_disk_size` option to `azure_rm_virtualmachine.py`. Fix #38883 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```
2.6.0
```

##### ADDITIONAL INFORMATION
Tests are not included, please include.
@zikalino thank you for offering to help this PR through.

### CODE REVIEW

**Comment by spmp** [comment]
If anyone needs push rights to my fork in order to merge this PR please let me know so I can add you.

**Comment by zikalino** [comment]
@spmp could you also add documentation for the new property?

**Comment by yuwzho** [comment]
@spmp Since you add a new option in the existing module, would you mind add documentation and integration test for it. You can refer our [develop guideline](https://github.com/VSChina/ansible/wiki/2-CONTRIBUTING#feature-pull-request) for more details.

**Comment by spmp** [comment]
Added `accept_terms`, documentation and tests. See #38973

**Comment by spmp** [comment]
There is potentially an issue with tests; In order to test `accept_terms` an image with a plan (i.e paid) is required. Does your build bot have an Azure account which allows this? There could be a cost involved with every test

**Comment by spmp** [comment]
Also, there is a new Python dependency `azure-mgmt-marketplaceordering` which should be added to the list when doing `pip install ansible[azure]`

**Comment by zikalino** [comment]
@spmp could you add me to your repo? I could just complete this PR and get it merged.

**Comment by spmp** [comment]
@zikalino I added you aaaaaages ago 8) Just awaiting your response: https://github.com/spmp/ansible/invitations

**Comment by spmp** [comment]
aaaaarg! have been rebasing for ages, I think someone else needs to do this for me sorry, I am creating chaos 8(

**Comment by yuwzho** [comment]
duplicate_of #38883

**Comment by spmp** [comment]
Closing as replaced by #43695

**Comment by spmp** [comment]
Closing as replaced by #43695

**Pull request closed without merging**
