### PR TITLE
fixes for PTY handling

### LINKED ISSUE #3877: OSError: [Errno 24] Too many open files -- when running from OSX 10.7
It seems some recent changes has introduced this regression, this occurs on OSX 10.7, bumping up the limits by "ulimit -n 2048" works around the problem. There might just be some file descriptors/pipes not being closed. You could limit the loop (wherever its happening) for the subprocesses to be just 1024?

I might poke around if I have time. For now the above is a bug report!

<pre>
TASK: [clone {{host_group}} code - private head] ******************************
fatal: [10.0.1.200] => Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 368, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 455, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 612, in _executor_internal_inner
    tmp = self._make_tmp_path(conn)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 736, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/__init__.py", line 671, in _low_level_exec_command
    rc, stdin, stdout, stderr = conn.exec_command(cmd, tmp, sudo_user, sudoable=sudoable, executable=executable)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py", line 165, in exec_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 703, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1120, in _get_handles
    errread, errwrite = self.pipe_cloexec()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1153, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

FATAL: all hosts have already failed -- aborting
</pre>

### PR DESCRIPTION
**Pull request by akerl**
This should fix #3877.

All credit for the patch goes to @cayblood; I just tested to confirm it works and opened it as a PR.

### CODE REVIEW

**Comment by leth** [comment]
This patch probably needs some minor cleanup, it was a hacky quick fix just to prove where the bug was, i.e. leaking the master or slave file handles.
In particular the exception handling in the finally block is super-excessive.

It might be sufficient to close `slave` after starting the subprocess, as `master` is probably closed later when `stdin` is closed.

**Comment by akerl** [comment]
Attempting to clean up now; stand by :)

**Comment by akerl** [comment]
That should be a bit better. I'm running my play through now, I'll confirm once it's run through successfully with that code.

**Comment by akerl** [comment]
Confirmed; looks good to me

**Comment by leth** [comment]
That's a lot nicer now :)

**Comment by cayblood** [comment]
Incidentally, @leth wrote the original patch. I just submitted it ;-)

**Comment by jcftang** [comment]
in relation to https://github.com/ansible/ansible/issues/3877 this patch seems to work for me as well on my mac

**Comment by jimi-c** [comment]
Thanks, I will most likely be merging this in today for inclusion in the 1.3.2 update.

**Comment by jcftang** [comment]
FYI, I tested on osx 10.7

**Comment by jimi-c** [comment]
This has been merged into the devel and 1.3.2 branches. Thanks!

**Pull request merged**
