### PR TITLE
New facts module for AWS EC2 VPC Endpoints

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY

Retrieves AWS VPC endpoints details using AWS methods. Requires Boto3.
Filter options can be found http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpoints.html

##### ISSUE TYPE
 - New Module Pull Request
 
##### COMPONENT NAME
ec2_vpc_endpoint_facts

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 4e8e366739) last updated 2017/04/12 09:11:50 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ~/src/ansible/lib/ansible
  executable location = ~/src/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

### CODE REVIEW

**Comment by willthames** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/1428 by willthames (not original author)

**Comment by jctanner** [comment]
!needs_revision

**Review by s-hertel — APPROVED** [review]

**Comment by s-hertel** [comment]
shipit

**Comment by s-hertel** [comment]
shipit

**Review by ryansb — APPROVED** [review]

**Pull request merged**
