### PR TITLE
Fix typo in document docker_swarm_service

### PR DESCRIPTION
**Pull request by aniejek**
##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY
mount property doesn't have property mode, but type

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docker_swarm_service

### CODE REVIEW

**Comment by hannseman** [comment]
Thanks!

I found some more places where the wrong option is referred:

https://github.com/ansible/ansible/pull/67991/files#diff-253fc84097c1396ec822be3f92c4dff2L315
https://github.com/ansible/ansible/pull/67991/files#diff-253fc84097c1396ec822be3f92c4dff2L328
https://github.com/ansible/ansible/pull/67991/files#diff-253fc84097c1396ec822be3f92c4dff2L351
https://github.com/ansible/ansible/pull/67991/files#diff-253fc84097c1396ec822be3f92c4dff2L357

Would you like to push fixes for these as well?

**Comment by felixfontein** [comment]
Please note that the ansible/ansible repository is currently in lockdown. Most modules will be migrated to collection repositories over the next weeks. PRs will need to be moved, but there will be a migration tool for that. More info will follow over the next weeks.

It's still OK to use PRs here to polish the changes, but these PRs won't be merged here. So please be patient :)

**Comment by aniejek** [comment]
@hannseman sure

**Comment by felixfontein** [comment]
The [community.general](https://github.com/ansible-collections/community.general/) collection is the new place where the [docker_* modules](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/cloud/docker) live. The repositority is not done yet (CI isn't working properly in all cases etc.), but if you don't mind that not everything is yet perfect, you can already create a PR there.

For testing, it makes sense to checkout `community.general` into a folder `ansible_collections/community/general`. Then you can point the environment variable `ANSIBLE_COLLECTIONS_PATHS` to the directory containing `ansible_collections`, and use the modules by their new name `community.general.docker_*`. That should already work with Ansible 2.9.

Once the PR is there and works, it can be merged and then backported to stable-2.9 here, and then end up in the next 2.9.x release.

**Comment by Akasurde** [comment]
@aniejek Are you working on this? If yes, please migrate this PR to [`community.general`](https://github.com/ansible-collections/community.general) since `docker_*` modules migrated there.

Thanks.

needs_info

**Comment by felixfontein** [comment]
Fixed in community.general. Thanks for reporting this @aniejek

close_me

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible-collections/community.general/pull/608

@aniejek Thanks for the contribution.

**Pull request closed without merging**
