### PR TITLE
Set /etc/hosts alias to match hostname

### PR DESCRIPTION
**Pull request by filipenf**
Issue: #5748

On debian based systems we need to change the /etc/hosts file to reflect the host name alias

### CODE REVIEW

**Comment by filipenf** [comment]
If hostname changes are not reflected to /etc/hosts one may start getting errors like this:  http://stackoverflow.com/questions/21003910/linux-and-unknownhostexception-for-a-java-program

**Comment by mpdehaan** [comment]
# Revision Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We'd like to see a few things tweaked if you don't mind.  If you can help resolve these items, we'd greatly appreciate it:
- (A) the code using the with statement in python needs to be changed, as it's not 2.4 complaint.  We still have to support python 2.4 on some older legacy platforms for modules, even though Ansible's main program does take 2.6+ and the "with" is fine there.
- (B) Should it be that the NamedTemporaryFile is unlinked after the copyfile, or that the copyfile is replaced with a rename to not leave the named temporary file around?

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-devel - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-project - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by filipenf** [comment]
I rolled back the use of with clause.

I don't believe we would have any problem with NamedTemporaryFile because by default it automatically deletes the file. Anyway I changed the intent becomes explicit.

If there's something else please let me know.

**Comment by mmoya** [comment]
Hi @filipenf. I'm not sure if you considered idempotence here. AFAICS _/etc/hosts_ gets rewritten everytime the module is run.

My solution so far have been this (note it's 127.0.**1**.1):

```
---
- name: set hostname facts
  set_fact:
    full_hostname="{{ inventory_hostname}}"
    short_hostname="{{ inventory_hostname.split('.', 1)[0] }}"

# " lovely lonely double-quote for fixing vim highlighting

- name: set hostname
  hostname:
    name={{ short_hostname }}

- name: add hostname to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line='127.0.1.1 {{ full_hostname }} {{ short_hostname }}'
    regexp='^127\.0\.1\.1'
    insertafter='^127\.0\.0\.1'
    state=present
```

and it works as expected, ie:

```
$ hostname
foo
$ hostname -f
foo.bar.guz
```

**Comment by filipenf** [comment]
@mmoya Your suggestion is somewhat equal to what I'm using currently. The thing is that this shouldn't be necessary because it is only required for debian systems. I believe modules should behave the same way in different systems.

About being idempotent: The file is rewritten every time modifying only the 127.0.0.1 line. It is possible to check if the line is equal the value we want before updating it, do you want me to change?

**Comment by dooblem** [comment]
This is what I used to change the fqdn AND hostnames of my hosts:

```
cat /etc/ansible/hosts
1.2.3.4 fqdn=test.example.com
```

The playbook:

```
- hosts: 1.2.3.4
  vars:
    ansible_fqdn_new: "{{ fqdn | default(ansible_fqdn) }}"
    ansible_hostname_new: "{{ ansible_fqdn_new.split('.', 1)[0] }}"
  tasks:
  - fail: msg="Bad FQDN"
    when: ansible_fqdn == ansible_hostname
  - replace: dest=/etc/hosts regexp='(\s+){{ ansible_fqdn }}(\s+.*)?$' replace='\1{{ ansible_fqdn_new }}\2' backup=yes
  - replace: dest=/etc/hosts regexp='(\s+){{ ansible_hostname }}(\s+.*)?$' replace='\1{{ ansible_hostname_new }}\2'
  - hostname: name={{ ansible_hostname_new }}

```

**Comment by mmoya** [comment]
@filipenf In this cases I used to generate a tempfile, check md5/whatever sums and only update the target files if sums differs. Seems like a big deal for just a tiny change but writing to a temp file is more reliable in face of write errors (you don't break the target file). Besides, access and modification times are preserved. My 2¢.

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by Jmainguy** [comment]
Can you reopen this PR in the new repo? Looks like there is still a bit of interest into this. One idea raised on irc today was to make a edit_hosts= option to the module so it only edits /etc/hosts of edit_hosts=true

**Comment by akatch** [comment]
+1

**Comment by kiranos** [comment]
+1

**Comment by craigmarvelley** [comment]
+1

**Comment by dk-dkopen** [comment]
-1 as it is - see below + although I myself use ubuntu and have to do this, i'm fine doing it myself with a short lineinfile (unlike /etc/hostname where it's clear and simple) rather than something rushed for such an important file.

Something like @mmoya suggested - note that Ubuntu by default structures it as:
127.0.0.1 localhost
127.0.1.1   myhostname

I would say this feature should:
- match the way it's set up by a fresh default Ubuntu (or otherwise) system deployment
- be careful not to change anything else in /etc/hosts or cause any unexpected side effects
- should be optional and disabled by default
- should only write file when actually changed
- ensure that ansible_fqdn ends up picking up the hostname thus specified

Issues with current pull request:
- replaces ALL lines that .startswith('127.0.0.1') which could corrupt it if you have further aliases to 127.0.0.1 down the file
- rewrites regardless of whether or not file changed

But, given all the trouble of specifying, implementing, testing and vetting, I'm not sure I'd consider this worthwhile as such.

Maybe a separate "hosts" module to fully express /etc/hosts would be better?
(as an alternative / in general)
More in line with keeping it simple, specific and modular.

**Comment by akatch** [comment]
My interest in making this change to the hostname module is simply that,
in my opinion, a module designed to change the hostname should make ALL
changes needed to update the hostname.  Updating the hostname should not
require a separate lineinfile task (as it does now, for certain types of
systems) to ensure all applications are able to resolve the new
hostname.  For instance, without editing the hosts file, Tomcat will
throw a fit and refuse to start because it can't resolve the local
hostname.

I would agree that changing all instances of 127.0.0.1 might not be a
great idea.  The module could instead change all instances of 127.0.1.1
or use a different address in the 127/8 subnet.  No matter how it is
done, though, fully updating the hostname shouldn't require an
additional task.  Just my $.02.

**Comment by romanr** [comment]
What is the status of this change/pull request? From conversation I understand it went to another old repo or something? This pull request appears to be merged to ansible "develop" branch and tags 1.7.2.
Yet when using 1.7.2 my /etc/hosts is not updated when setting hostname.
So it's not in 1.7.2, but ticket is Closed?

**Comment by Jmainguy** [comment]
@romanr I dont see a reference to a new PR, so as far as I can tell this is still closed. If someone else wants to open a new PR against the new repo's, it would gather some attention for sure.

**Comment by er1c** [comment]
+1

**Pull request closed without merging**
