### PR TITLE
Skip confirmation prompts in gluster_volume (#22402)

### PR DESCRIPTION
**Pull request by nrwahl2**
##### SUMMARY
Skip confirmation prompts in gluster_volume (#22402)

`gluster_volume` was failing to stop volumes due to an interactive confirmation prompt. I've appended `--mode=script` the `module.run_command` for `run_gluster`.

Source: https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.2/html/installation_guide/chap-using_the_gluster_command_line_interface

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
modules/system/gluster_volume.py

##### ANSIBLE VERSION
```
ansible 2.4.0 (issue/22402 bd8ab912e8) last updated 2017/08/27 17:40:28 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/reid/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/reid/git/ansible/lib/ansible
  executable location = /home/reid/git/ansible/bin/ansible
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### ADDITIONAL INFORMATION
N/A; see issue.

### CODE REVIEW

**Comment by nrwahl2** [comment]
whoa.... just a minute.

**Comment by nrwahl2** [comment]
That ought to be better.

**Comment by samdoran** [comment]
Merged to devel for inclusion in 2.4. Thank you!

**Comment by nrwahl2** [comment]
Closes #22402 

Edit: Hmm, that's not gonna work. One of these days I'll be a real member who can close issues when I'm done ;)

**Pull request merged**
