### PR TITLE
git archive in ansible-galaxy fails for non-default-branch versions

### PR DESCRIPTION
**Pull request by ghost**
Trying to install a branch that is not the default (typically 'master') via ansible-galaxy fails because `git archive` cannot handle remote branches. Introducing a `git checkout` solves this problem by pulling the remote branch onto the local machine.

My concrete example was:

``` yaml
# galaxy.yml
- src: https://github.com/thefinn93/ansible-tlsdate.git
  version: rename-service
```

which caused:

```
- executing: git clone https://github.com/thefinn93/ansible-tlsdate.git ansible-tlsdate
- executing: git archive --prefix=ansible-tlsdate/ --output=/tmp/tmpOLH2Y4.tar rename-service
- command git archive --prefix=ansible-tlsdate/ --output=/tmp/tmpOLH2Y4.tar rename-service failed
  in directory /tmp/tmpTlAMNS
- ansible-tlsdate was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
```

### CODE REVIEW

**Comment by sivel** [comment]
Btw, I believe you can also already use `remotes/origin/branch` as the version.

**Comment by ghost** [comment]
That may be a useful workaround ^_^ Still, it requires the author of `galaxy.yml` to be aware of the internal workings of `ansible-galaxy` (e.g. that the repo is checked out and archived), which I find unsatisfactory. I'd say specifying repo src and branch name should work out of the box ;-)

**Comment by FlorentCoppint** [comment]
Your commit fixes the issue for me.
When will it be merged to Ansible ?

**Comment by ghost** [comment]
Ask the gods :-P For the time being I'm using the workaround suggested by sivel...

**Comment by tjanez** [comment]
I would close this in favour of #10620.

**Comment by ghost** [comment]
I haven't tried it, but looking at the diff that seems reasonable :+1:

**Comment by amenonsen** [comment]
Right, this should now be closed in favour of #10620.

**Comment by amenonsen** [comment]
Closing per above comment since #13203 was merged.

**Pull request closed without merging**
