### PR TITLE
module_utils/manageiq: add find_collection_resource_or_fail

### PR DESCRIPTION
**Pull request by elad661**
##### SUMMARY
This pull request adds a small method `find_collection_resource_or_fail` to the manageiq module utils.
the method tries to find a collection resource in ManageIQ, and calls module.fail_json if the resource was not found.

It is needed for the following pull requests:
https://github.com/ansible/ansible/pull/31233
https://github.com/ansible/ansible/pull/32354

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module_utils/manageiq.py

##### ANSIBLE VERSION

```
ansible 2.5.0
```

### CODE REVIEW

**Comment by elad661** [comment]
cc: @yaacov @cben

**Review by yaacov — APPROVED** [review]
LGTM 👍

**Comment by yaacov** [comment]
shipit

**Review by zgalor — APPROVED** [review]
:+1: LGTM 
shipit

**Comment by cben** [comment]
shipit

**Pull request merged**
