### PR TITLE
Handle TimeoutError for Python 2

### LINKED ISSUE #49811: module_utils/basic.py: "NameError: global name 'TimeoutError' is not defined" (Python 2)
##### SUMMARY
Using Python 2: exception `NameError: global name 'TimeoutError' is not defined` (since #49449, [here](https://github.com/ansible/ansible/blob/63279823a77320b8cdf7f69d61af6eddaa5ebf33/lib/ansible/module_utils/basic.py#L2834))

```
fatal: [host]: FAILED! => {
  "changed": false,
  "module_stderr": "Shared connection to 192.168.254.24 closed.\r\n",
  "module_stdout": "Traceback (most recent call last):\r\n
                                File \"/root/.ansible/tmp/ansible-tmp-1544588562.3201482-74290310182346/AnsiballZ_command.py\", line 113, in <module>\r\n
                                  _ansiballz_main()\r\n
                                File \"/root/.ansible/tmp/ansible-tmp-1544588562.3201482-74290310182346/AnsiballZ_command.py\", line 105, in _ansiballz_main\r\n
                                  invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n
                                File \"/root/.ansible/tmp/ansible-tmp-1544588562.3201482-74290310182346/AnsiballZ_command.py\", line 48, in invoke_module\r\n
                                    imp.load_module('__main__', mod, module, MOD_DESC)\r\n
                                File \"/tmp/ansible_command_payload_K3xSwT/__main__.py\", line 294, in <module>\r\n
                                File \"/tmp/ansible_command_payload_K3xSwT/__main__.py\", line 266, in main\r\n
                                File \"/tmp/ansible_command_payload_K3xSwT/ansible_command_payload.zip/ansible/module_utils/basic.py\", line 2834, in run_command\r\n
                              NameError: global name 'TimeoutError' is not defined\r\n",
   "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1
}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/module_utils/basic.py

##### ANSIBLE VERSION
```paste below
devel
```

##### OS / ENVIRONMENT
Python 2.6

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes: #49811

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/basic.py

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @pilou-

**Review by bcoca — APPROVED** [review]

**Comment by pilou-** [comment]
@bcoca: with Python3, should not bot `TimeoutError` and `socket.timeout` be caught ?

**Comment by bcoca** [comment]
@pilou-  basically that is what this PR does by equating the names, either fix is fine with me

**Review by bcoca — CHANGES_REQUESTED** [review]
Actually, we should import from `ansible.module_utils.facts.timeout ` as I'm looking for our internal timeout specifically, not the socket one

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/49824

**Comment by Akasurde** [comment]
superseded by #49824 Thanks @pilou- @bcoca

**Pull request closed without merging**
