### PR TITLE
Added function to convert camelCase to snake_case for powershell

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
We need an easy way to convert camelCase strings and/or dicts that contains keys in camelCase format to the Ansible preferred snake_case.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module_utils/powershell.ps1

##### ANSIBLE VERSION
```
ansible 2.4.0 (powershell-camel-converter 121b37c5a1) last updated 2017/06/29 08:44:55 (GMT +1000)
  config file = None
  configured module search path = [u'/home/jborean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jborean/dev/ansible/lib/ansible
  executable location = /home/jborean/dev/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION
Ultimate this should be moved into it's own util file as we wish to save space on powershell.ps1 but until the work in the background to handle this is done we need to have it in module_utils/powershell.ps1.

Will be used in https://github.com/ansible/ansible/pull/25869, https://github.com/ansible/ansible/pull/25902 and others that may need it.

### CODE REVIEW

**Comment by nitzmahone** [comment]
Good excuse for me to ship the PS module_utils loader in 2.4, because if we ship this in here, it might arguably need to stay there forever. :D

**Comment by jborean93** [comment]
Further changes to accommodate this PR https://github.com/ansible/ansible/pull/25015

**Comment by jborean93** [comment]
Hey @nitzmahone I've made some more changes to now move this across to `Ansible.ModuleUtils.PowerShellCamelConversion.psm1` and have added some tests.

**Review by nitzmahone — COMMENTED** [review]
Looks great- only concern I have is the granularity of shared module utils code... I could see this cutting both ways: do we want very small granular things like this to be their own file, or have larger collections of utility stuff like "Ansible.ModuleUtils.StringUtils" or something like that? We might want to do some contrived perf testing before making a decision, as it's (more or less) final. I'm particularly worried about the dynamic module creation overhead (under pipelining) vs the file size. I *suspect* that we're probably better off with smaller files to a certain point, but probably good to make this decision with a little data.

**Review by nitzmahone — APPROVED** [review]

**Comment by nitzmahone** [comment]
(shippable failures were transient and unrelated to this code)

**Pull request merged**
