### PR TITLE
azure: add public_ip_per_vm parameter for azure_rm_virtualmachinescaleset

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
##### SUMMARY
* add `public_ip_per_vm` parameter for azure_rm_virtualmachinescaleset module, to match Azure CLI `az vmss create --public-ip-per-vm` parameter
* remove call to non-existing `self.create_default_vnet()` method, and print an error message instead

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
cloud / azure / azure_rm_virtualmachinescaleset

### CODE REVIEW

**Comment by andreasgerstmayr** [comment]
CI reports `Tests aborted after exceeding the 50 minute time limit.` - is this a flake or related to my commit? The `public_ip_per_vm` shouldn't change anything (if not explicitly enabled).

The removal of the call to `create_default_vnet` changes the error from a Python exception to a proper error message - this could affect this test, but shouldn't get a timeout.

**Comment by Fred-sun** [comment]
@andreasgerstmayr CI fail may not be the problem with this module, may it be the environment or the resource occupation at that time that caused the timeout? Can you re-trigger CI verify(Close and open again)? Thank you very much!

**Comment by Fred-sun** [comment]
review_need

**Comment by Fred-sun** [comment]
@mybayern1974 @haiyuazhang review_need

**Comment by Fred-sun** [comment]
@andreasgerstmayr  In order to get the review as soon as possible, please help to solve the conflict files when you have time. Thank you very much!

**Comment by Fred-sun** [comment]
@andreasgerstmayr Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by andreasgerstmayr** [comment]
Done: https://github.com/ansible-collections/azure/pull/79

**Pull request closed without merging**
