### PR TITLE
Integration tests for rabbitmq_user module

### PR DESCRIPTION
**Pull request by ar7z1**
##### SUMMARY

In this PR I've added integration tests for [rabbitmq_user](http://docs.ansible.com/ansible/latest/rabbitmq_user_module.html) module.
As in #35315, I run tests only on Ubuntu 14.04 for simplicity.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

rabbitmq_user

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/art/.ansible.cfg
  configured module search path = [u'/Users/art/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@ar7z1 Thanks for your contribution.

@mattclay +1 from me. Can you take a look ?

**Comment by mattclay** [comment]
@ar7z1 Thanks for the tests. I understand wanting to simplify testing by limiting the distributions used for running tests. Covering one distribution is certainly better than none. However, Ubuntu 14.04 has only a little more than a year of support left. To extend the useful life of this test, could you use Ubuntu 16.04 instead?

**Comment by ar7z1** [comment]
@mattclay I've fixed `setup_rabbitmq` to support Ubuntu 16.04, but there was a problem with systemd.
Script
```yaml
- service: name=rabbitmq-server state=started
```
have failed with "Failed to connect to bus: No such file or directory" error. This is a known issue: https://github.com/moby/moby/issues/2296. The only fix is to run docker container with `--privileged`.

I've added a [workaround](https://github.com/ansible/ansible/pull/35421/commits/63728c86975a46a3aa8775df59ce07f7d0d85141#diff-be8ceac5c7fa35e81939365027e1cb52R29) for this issue: I start `rabbitmq-server` via `/etc/init.d/` script. And it [works](https://app.shippable.com/github/ansible/ansible/runs/53006/24/console)! :-)

**Comment by mattclay** [comment]
@ar7z1 Much better! Thank you.

**Comment by ar7z1** [comment]
@mattclay Should I do something else in this PR?

**Comment by mattclay** [comment]
@ar7z1 Thanks for the tests!

**Pull request merged**
