### PR TITLE
update copyright year

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Updating copyright year

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
- na_ontap_lun.py 

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by jamescassell — CHANGES_REQUESTED** [review]
This file was not updated in 2019. Doesn't make sense to update the copyright.

**Review by lonico — APPROVED** [review]
shipit

**Comment by lonico** [comment]
@carchi8py if the file was not updated in 2019, should this be changed to 2018 ?

**Review by lonico — APPROVED** [review]
shipit

**Comment by acozine** [comment]
Thanks @carchi8py for your attention to detail.

We use the original year created for copyright statements for code. See https://github.com/ansible/ansible/issues/45989#issuecomment-423635622. So I'm going to close this PR. The copyright notices are fine as they are.

**Pull request closed without merging**
