### PR TITLE
Add proxy support of apt_key module.

### PR DESCRIPTION
**Pull request by cocoy**
Example passing env variables and used by apt_key:

<pre>
vars:
    env:
       http_proxy: "http://http-proxy.local:3128"
       https_proxy: "http://http-proxy.local:3128"
tasks: 
    - name:  install ceph apt-key 
      apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present 
      environment: $env
</pre>

### CODE REVIEW

**Comment by mpdehaan** [comment]
Use of the "environment:" keyword as discussed on the mailing list provides proxy support to all modules.

Not quite documented as it's a 1.1 development feature, but needs to be done soon.

See https://groups.google.com/group/ansible-project/browse_thread/thread/bd5afa9f8752e8f9

**Comment by dhozac** [comment]
Only if the modules use it, like this makes apt_key do. This looks good to me, but I need to test some.

**Comment by mpdehaan** [comment]
Right, right, my fault for not reading the actual diff.

**Comment by dhozac** [comment]
So it seems to me that urllib2 will use ProxyHandler by default, so there's no need for any code change here. Do you (@cocoy) have anything to suggest the contrary?

**Comment by cocoy** [comment]
Oh I see. urllib2 use ProxyHandler by default indeed. I't just settting the environment variable as specified my @mpdehaan on the mailing list.

**Pull request closed without merging**
