### PR TITLE
Add support for role defaults. Lowest precedence variables per role.

### PR DESCRIPTION
**Pull request by benosman**
This is a pull request based on this topic:

https://groups.google.com/d/msg/ansible-project/vZlI6sB1kRU/ChpDNz-cwXsJ

> We are open to inserting something like a 
> 
> roles/foo/defaults/main.yml
> 
> If somebody can send me a _nice_ patch and it might get in sooner :)

It works by collecting all the defaults files for roles, and then one by one populating a default_vars dict. Then when complete, this dict is merged with the the playbooks vars, but with those vars taking priority.

My intention was to make anything set in these defaults overrideable by any other variable setting method. Hopefully this is the case.

### CODE REVIEW

**Comment by srgvg** [comment]
How about vars/defaults.yml, as to not proliferate the number of directories in roles/ ?

Also, mentioning as somehow related, if I'm not mistaken, roles look only at vars/main.yml now. There was the idea to have roles look at all files in vars/ so to be able to structure things, and I think Michael was open to that idea.

**Comment by jimi-c** [comment]
Yes, this patch may be unnecessary now with the way I implemented role dependencies. If a role now has a vars/main.yml file, that file is read and fed into the role compilation directly so it will always see values as they are set in that file (or when they have been specified in the role inclusion/dependency).

Could you give the role dependencies a try and see if that accomplishes what you're trying?

**Comment by benosman** [comment]
@jimi1283 

I had been working on this before your recent patch, and while I did merge my changes with your update, i do need to study your new code to see how it impacts this pull request. I think when using role dependencies it may not work fully now.

However, cool as your new dependency feature is, i think there is a nuance to what i want to achieve with this. My primary aim is to be able to set the defaults for a role, which can then be easily overridden in a play or more ideally, by inventory variables.

My use case is to create an open source library of roles with sensible defaults. Then,those variables can be overriden in the playbook, or ultimately via the api in the drupal based gui i'm creating.

**Comment by benosman** [comment]
@sergevanginderachter 

i like that idea personally to use defaults.yml - and possibly load in other files inside the vars folder. Do you have a reference for a topic or issue where Michael mentioned he was open to it?

**Comment by srgvg** [comment]
After some search, seems there's a ticket for that: #2958

**Comment by benosman** [comment]
@sergevanginderachter  - Thank you

**Comment by jimi-c** [comment]
@smoothify defaults for a role would now be vars/main.yml, and would not be overridden by inventory-scope variables or other roles any more with my patch. So I think that case is taken care of.

If so, do you want to close this and resubmit the "multiple files in vars" as a different PR?

**Comment by benosman** [comment]
Sorry, I didn't mean to add the multiple files commit to this pull request. I pushed to the wrong branch. That definitely needs its own PR.

@jimi1283 
i actually _want_ the defaults to be overriden by the inventory scope variables, so that certain hosts / groups can override specific settings.

I did wonder if the vars should be loaded in  _build_role_dependencies(), i've noticed now that in the new code, main.yml loaded both in that method and globally. So I need to spend some more time working out how the precedence should work.

**Comment by jimi-c** [comment]
@smoothify the way it's done now is definitely the way it should be. Inventory (group/host vars) have the lowest precedence and are overridden by variables set in roles vars/main.yml. Those in turn are overriden by variables set when the role is included/added to dependencies.

**Comment by resmo** [comment]
I also liked the idea to "default" a role and overwrite vars in groups/hosts vars.  so something like role/foo/vars/defaults.yaml would be very useful or good practice for sharing roles.

**Comment by benosman** [comment]
@jimi1283 

Its precisely due to that behavior that I, and a few others want this defaults system. 

As mentioned in the OP, i created this pull request in response to Michael saying:

>    We are open to inserting something like roles/foo/defaults/main.yml

https://groups.google.com/d/msg/ansible-project/vZlI6sB1kRU/ChpDNz-cwXsJ

**Comment by mpdehaan** [comment]
Answering some questions now that I've gotten around to this.

I do not want to do this as vars/defaults because we will in the future want to load all variables in vars/\* and that makes the name defaults special.

I like roles/x/defaults/main.yml better as it makes it very clear where defaults are set and also allows breaking up things into more files if need be when we do the above.

(Yes, I'm cognizant this makes more directories but it is also makes it super explicit/obvious if the role is defining any defaults or not too, so seems ok/good)

**Comment by mpdehaan** [comment]
@jimi1283 -- yes this is different than role dependencies and is something we talked about and want to implement.   Haven't had time to test the patch but the idea is for the role being able to provide defaults even lower than inventory values, which is pretty useful for sharing roles that may have sensible defaults.

group_vars/all is good for most people but not so much for trading roles since it is kind of tied to inventory.

**Comment by resmo** [comment]
absolutely agree with @mpdehaan in comment https://github.com/ansible/ansible/pull/3891#issuecomment-23064945. 

Would like to see this feature very soon in ansible.

**Comment by gregbuehler** [comment]
Roles are somewhat useless if you can't override default variables with the inventory variables. This is one of the main issues preventing my organization from using Ansible more.

**Comment by mpdehaan** [comment]
@gregbuehler -- comments not appreciated.  They are hardly useless, they are just an abstraction on top of something already in Ansible and this question is not unique to roles.  That being said, this is in queue for testing.

**Comment by gregbuehler** [comment]
@mpdehaan I guess we just have different views of what roles are trying to accomplish. In my view roles have less value and limit my organization's adoption of Ansible.

Defaults mean I can make one role called `apache` with sensible defaults rather than have to repeat myself and make roles like `apache-customer1-site1`, `apache-customer1-site2`, `apache-customer2-site1`, etc.

Does global scope on roles, variable name conflicts, and confusing inheritance issues sound familiar? Puppet had this exact problem and solved it with parameterized classes. Of specific interest is [Parameterized Classes: Why, and Some History](http://docs.puppetlabs.com/guides/parameterized_classes.html#why-and-some-history). We don't have to do this the hard way, we can learn from others mistakes.

**Comment by jimi-c** [comment]
I believe I have this working now, with default role vars being overridden by inventory variables (host and group):

https://github.com/jimi1283/ansible/tree/smoothify-defaults

**Pull request merged**
