### PR TITLE
Template handler name

### LINKED ISSUE #15505: Variable is not expanded in handler name
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A

##### COMPONENT NAME
playbook

##### SUMMARY

Variables are not expanded in handler names.

Starting from some point variables are being expanded in task names: #3103, #11605, I expect that it should work in handler names too.

Tricky part may be here: handler name is handler identifier.
##### STEPS TO REPRODUCE

Run following playbook:

```

---
- hosts: localhost
  vars:
    service_instance: "worker3"

  tasks:
  - name: configure {{ service_instance }}
    debug: msg="Writing {{ service_instance }} configuration..."
    notify:
      - restart {{ service_instance }}
    changed_when: True

  handlers:
    - name: restart {{ service_instance }}
      debug: msg="Restarting {{ service_instance }}..."
```

##### EXPECTED RESULTS

Handler named with variable in it should have it expanded:

```
RUNNING HANDLER [restart worker3] *******************************
```
##### ACTUAL RESULTS

```
$ ansible-playbook playbook.yaml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [configure worker3] *******************************************************
ok: [localhost] => {
    "msg": "Writing worker3 configuration..."
}

RUNNING HANDLER [restart {{ service_instance }}] *******************************
ok: [localhost] => {
    "msg": "Restarting worker3..."
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0  
```

### LINKED ISSUE #17922: Ansible 2.3.0 (devel) and several earlier versions do not populate variables in handler names.
##### ISSUE TYPE
- Bug Report (same as #15713 and #14082)
##### COMPONENT NAME
- Handlers and variable interpolation
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 9962245b92) last updated 2016/10/06 09:55:33 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 0ee774ff15) last updated 2016/10/06 09:55:59 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 5cc72c3f06) last updated 2016/10/06 09:55:59 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
ansible-playbook 2.2.0.0 (stable-2.2 be6396d5e9) last updated 2016/10/05 17:40:02 (GMT -400)
  lib/ansible/modules/core: (detached HEAD a6b8215e62) last updated 2016/10/05 17:45:10 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d42975e068) last updated 2016/10/05 17:45:11 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
derek@derek-HP-EliteOne-800-G1-AiO:~$ ansible-playbook play.yaml 
 [WARNING]: provided hosts list is empty, only localhost is available
```

```
ansible-playbook 2.1.2.0 (stable-2.1 a7d0cc6e61) last updated 2016/10/05 17:42:07 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 4602021670) last updated 2016/10/05 17:43:21 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d312f34d9b) last updated 2016/10/05 17:43:22 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
derek@derek-HP-EliteOne-800-G1-AiO:~$ ansible-playbook play.yaml 
 [WARNING]: provided hosts list is empty, only localhost is available
```

```
ansible 2.1.2.0 (detached HEAD 29f2f26278) last updated 2016/10/06 11:25:15 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 17ee1cfaf9) last updated 2016/10/06 11:30:32 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d312f34d9b) last updated 2016/10/06 11:30:32 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
derek@derek-HP-EliteOne-800-G1-AiO:~$ ansible-playbook --connection=local play.yaml
 [WARNING]: Host file not found: /etc/ansible/hosts
```

```
ansible 2.1.1.0 (detached HEAD 780c363482) last updated 2016/10/06 11:32:54 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 242368e99b) last updated 2016/10/06 11:32:58 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 14887a9ea8) last updated 2016/10/06 11:32:58 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```

```
ansible 2.0.0.2 (stable-2.0.0.1 3b5d7400de) last updated 2016/10/06 11:11:52 (GMT -400)
  lib/ansible/modules/core: (detached HEAD ce6619bf5d) last updated 2016/10/06 11:11:55 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 29af26884e) last updated 2016/10/06 11:11:55 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No change.
##### OS / ENVIRONMENT
- Ansible manager: Lubuntu 16.04.1
- Ansible worker: Ubuntu Server 16.04.1
- Python 2.7.12
##### SUMMARY

Ansible 2.1.2.0, 2.1.1.0, and branches devel, stable-2.2, stable-2.1, and stable-2.0.0.1 do not resolve variable references in handler names.
##### STEPS TO REPRODUCE
- See #15713.
##### EXPECTED RESULTS
- See #15713.

Ansible 2.1.0.0 produces the correct result: 

```
derek@derek-HP-EliteOne-800-G1-AiO:~$ ansible --version
ansible 2.1.0.0 (detached HEAD b599477242) last updated 2016/10/06 11:36:36 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 04a871d007) last updated 2016/10/06 11:36:38 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b5fa2b3416) last updated 2016/10/06 11:36:38 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
derek@derek-HP-EliteOne-800-G1-AiO:~$ ansible-playbook --connection=local play.yaml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [bogus task with notify for someapp] **************************************
changed: [localhost]

RUNNING HANDLER [restart someapp] **********************************************
ok: [localhost] => {
    "msg": "some bogus module call in handler someapp"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   

```

Ansible 2.0.2.0 on branch stable-2.0 produces the correct result: 

```
derek@derek-HP-EliteOne-800-G1-AiO:~$ ansible --version
ansible 2.0.2.0 (stable-2.0 26078418e9) last updated 2016/10/06 11:13:05 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 1e68326ea6) last updated 2016/10/06 11:13:07 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 4eb177e545) last updated 2016/10/06 11:13:07 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
derek@derek-HP-EliteOne-800-G1-AiO:~$ ansible-playbook --connection=local play.yaml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [bogus task with notify for someapp] **************************************
changed: [localhost]

RUNNING HANDLER [restart someapp] **********************************************
ok: [localhost] => {
    "msg": "some bogus module call in handler someapp"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   

```
##### ACTUAL RESULTS

Results for Ansible 2.1.2.0, 2.1.1.0, and branches devel, stable-2.2, stable-2.1, and stable-2.0.0.1:

```
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [bogus task with notify for someapp] **************************************
changed: [localhost]

RUNNING HANDLER [restart {{ appname }}] ****************************************
ok: [localhost] => {
    "msg": "some bogus module call in handler someapp"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   

```

### LINKED ISSUE #19898: Ansible 2.2.0.0: Variables in handler names not populated
**Issue Type:** Bug Report, Regression from #15713

**Component Name:** handlers

**Ansible Version:** 2.2.0.0

**Environment:** OS X 10.11.6

**Summary:** Under Ansible 2.2.0.0, Jinja variables contained in a handler `name` are no longer populated. Under Ansible 1.9.x and 2.1.1.0, they were populated. Here's a quick example:

**Steps To Reproduce:**
1. Write this content to `playbook.yml`:
   
   ``` yml
   ---
   - hosts: localhost
     connection: local
     vars:
       appname: someapp
     handlers:
     # The following line, when the handler is executed, does not populate {{ appname }}
     - name: restart {{ appname }}
       debug:
         msg: some bogus module call in handler {{ appname }}
     tasks:
     - name: bogus task with notify for {{ appname }}
       command: ls
       notify: restart {{ appname }}
   ```
2. Run the playbook: `ansible-playbook --connection=local playbook.yml`

**Expected Results:** In the output of the playbook run, any mention of `{{ appname }}` should not appear, but replaced with `someapp`, per the given variables.

**Actual Results:**

```
  [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [bogus task with notify for someapp] **************************************
changed: [localhost]

RUNNING HANDLER [restart {{ appname }}] ****************************************
ok: [localhost] => {
    "msg": "some bogus module call in handler someapp"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

Note that in the `RUNNING HANDLER` line, the Jinja template syntax is printed literally, rather than being populated with the variable that clearly exists, since it's populated elsewhere. This is a regression from [1.9.x](https://github.com/ansible/ansible/issues/14082) and [2.1.1.0](https://github.com/ansible/ansible/issues/16922#issuecomment-251805585).

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/15505
Fixes https://github.com/ansible/ansible/issues/17922
Fixes https://github.com/ansible/ansible/issues/19898

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
handlers

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by bcoca** [comment]
won't notifying fail since the handler name used does not exist until you run handlers? 

or is this only meant to work with `listen:`?

**Comment by mkrizek** [comment]
I *think* they are notified by their `uuid`, so notifying shouldn't fail, no? Anyway, the following works:
```yaml
- hosts: localhost
  gather_facts: no
  vars:
    hname: handler1
  tasks:
    - name: "task to notify {{ hname }}"
      debug:
        msg: "notifying {{ hname }}"
      changed_when: true
      notify: "{{ hname }}"

  handlers:
    - name: "{{ hname }}"
      debug:
        msg: "{{ hname }} called"
```

There might be a case where it fails I am not aware of.

**Comment by bcoca** [comment]
No, it gets looked up by either `name` or `listen` keywords, THEN it is stored by uuid.  

The thing is that the current code change is  templating at runtime, this is too late, something else is probably already templating at definition time and this change will only affect display. 

Tested your example in devel and it 'works' it just doesn't display the templated name.
```< RUNNING HANDLER [{{ hname }}] >```

In either case, the variable scope matters, host specific vars for example, won't work.

So this change seems fine, its only display purposes, not 'matching' nor 'definition', though i would look to see if you can get the already templated name (needed to trigger handler) vs having to 're template it'

**Comment by mkrizek** [comment]
The already templated name does not seem to be stored, it's templated on the lookup [1] and matched with `result['_ansible_notify']` (= `task.notify` which is already templated in `TaskExecutor` on `post_validate`). So unsure if I can get it (without making this change bigger and more risky).

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/__init__.py#L369

**Pull request merged**
