### PR TITLE
Create a short license for PSF and MIT.

### PR DESCRIPTION
**Pull request by abadger**
Modify selectors, six, and urls.py (match_hostname) to use the short license

##### SUMMARY
Short licenses for PSF and MIT code.  We have a little bit of these from libraries that we are bundling (six and selectors2)

##### ISSUE TYPE
 - Feature Pull Request

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION
@nitzmahone Look good to you?

### CODE REVIEW

**Comment by sivel** [comment]
Should we really be modifying the files that we vendor?  My feeling is no.  We should leave vendored files untouched.

**Comment by abadger** [comment]
@sivel.. Hmmm... I somewhat agree.  For selectors, I added the license information (I don't think we should have a bare file... So I think adding it is a good idea.)  For urls.py, I had to add that too (the code was extracted by us from the stdlib.  In the future I'd like to move that to its own file).  For six, Benjamin does have the complete license in six.py.  I'm conflicted there, though.  Every module uses six indirectly through basic.py so shaving off a little here and a little there does make a difference in how much data gets transferred.

**Comment by sivel** [comment]
In the end, I'll be fine.  I just wanted to voice my opinion.

For selectors, that makes sense then.  I understand the goal with six, but I'd question how much space that really saves when zipped.  I doubt remote disk space is our concern, but more transfer size.

**Comment by abadger** [comment]
Yeah, it's all about transfer size. Just used command line zip on six.py and the size difference is about 600 bytes.  I'm really not sure whether to worry about it or not.  Going to omit modifying six.py for now.  We can think about it at some later time if we get in the mood to really optimize what's happening (likely we'd explore things like remote cache at that time instead of making files shorter so it's probably premature to be worrying about this now).

**Pull request merged**
