### PR TITLE
Fix user_agent string not getting set

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Fix an issue where the `user_agent` string is not being correctly set.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
module_utils/pure.py

### CODE REVIEW

**Review by genegr — APPROVED** [review]
shipit

**Comment by sile16** [comment]
shipit

**Review by sile16 — APPROVED** [review]

**Review by genegr — APPROVED** [review]
shipit

**Review by rdeenik — APPROVED** [review]
shipit

**Comment by bcoca** [comment]
!bot_status

**Pull request merged**
