### PR TITLE
Ignore non-existing Ansible role paths when running ansible-galaxy list

### LINKED ISSUE #30943: ansible-galaxy list -p roles lists local roles plus shows help string
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/javl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
default configuration, --only-changed has empty output.

##### OS / ENVIRONMENT
Ubuntu 16.04 64 bit

##### SUMMARY
The command ```ansible-galaxy list -p roles``` outputs list of roles in the roles directory PLUS help string PLUS complains about missing directory:

```bash
$ ansible-galaxy  list -p roles
- pyenv, 0.0.3
- api, (unknown version)
- api_data, (unknown version)
- rabbitmq, (unknown version)
- tumf.systemd-service, 1.9
Usage: ansible-galaxy list [role_name]

Options:
  -h, --help            show this help message and exit
  -c, --ignore-certs    Ignore SSL certificate validation errors.
  -p ROLES_PATH, --roles-path=ROLES_PATH
                        The path to the directory containing your roles. The
                        default is the roles_path configured in your
                        ansible.cfgfile (/etc/ansible/roles if not configured)
  -s API_SERVER, --server=API_SERVER
                        The API server destination
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit

 See 'ansible-galaxy <command> --help' for more information on a specific
command.
ERROR! - the path /usr/share/ansible/roles does not exist. Please specify a valid path with --roles-path
```

### PR DESCRIPTION
**Pull request by azaghal**
##### SUMMARY
Instead of hard-failing during `ansible-galaxy list` in case of invalid paths (non-existing or non-directory) specified via `ANSIBLE_ROLES_PATH`, `roles_path`, or `--roles-path`, ignore the missing paths, and only produce a warning if not a single of the specified paths are valid.

This would make the command behave in similar way to some other `ansible-galaxy` commands (which do not verify existence of all the directories), and will avoid spurious errors since by default Ansible might reference a bunch of directories that do not exist after its installation (for example the one in `/usr/share/ansible/roles` if user installs via `pip`).

Some debugging output and warning is still introduced to make things easier to figure out in case of misconfiguration.

Fixes #30943

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
Implemented against `devel` branch (where same issue exists). Listing tested released version where issue was confirmed.

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/branko/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/branko/.virtualenvs/ansible-galaxy/lib/python2.7/site-packages/ansible
  executable location = /home/branko/.virtualenvs/ansible-galaxy/bin/ansible
  python version = 2.7.14 (default, Jan  9 2018, 13:22:35) [GCC 6.4.0]
```

##### ADDITIONAL INFORMATION

**Before change:**
`ansible-galaxy list`
```
Usage: ansible-galaxy list [role_name]

Options:
  -h, --help            show this help message and exit
  -c, --ignore-certs    Ignore SSL certificate validation errors.
  -p ROLES_PATH, --roles-path=ROLES_PATH
                        The path to the directory containing your roles. The
                        default is the roles_path configured in your
                        ansible.cfgfile (/etc/ansible/roles if not configured)
  -s API_SERVER, --server=API_SERVER
                        The API server destination
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit

 See 'ansible-galaxy <command> --help' for more information on a specific
command.
ERROR! - the path /usr/share/ansible/roles does not exist. Please specify a valid path with --roles-path
```

**After change:**
`ansible-galaxy list` (EMPTY OUTPUT)
```
```

`ANSIBLE_ROLES_PATH=/this/does/not/exist ansible-galaxy list`
```
 [WARNING]: - Could not locate a single valid role path (/this/does/not/exist).Check your ANSIBLE_ROLE_PATHS environment variable, ansible.cfg configuration file, or --roles-path parameter.
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@azaghal Could you please rebase this ?

**Comment by azaghal** [comment]
Hm... Is it just me, or my PR has become somewhat redundant in the meantime (changeset e4dbabbef2ad7ab5241a72732236bec1d150a2f4 seems to be the one)? Should the PR simply be discarded/closed?

**Comment by Akasurde** [comment]
@azaghal This is fixed via #39044, so I will close this. Please feel free to re-open if problem persists.

**Comment by azaghal** [comment]
Thanks for letting me know :)

**Pull request closed without merging**
