### PR TITLE
New network/panos module: panos_facts

### PR DESCRIPTION
**Pull request by traittinen**
##### SUMMARY

New module for getting device facts from Palo Alto Networks firewall.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

panos_facts

##### ADDITIONAL INFORMATION

Example usage:
```paste below
    - name: Get facts
      panos_facts:
        host: "{{ pan_host }}"
        username: "{{ pan_user }}"
        password: "{{ pan_pw }}"
        gather_subset: all
```

### CODE REVIEW

**Comment by Qalthos** [comment]
cc @abenokraitis

**Comment by traittinen** [comment]
@shinmog  any comments?

**Review by shinmog — APPROVED** [review]
This could have been simplified a bit by using pandevice, but this lgtm otherwise :)

**Comment by shinmog** [comment]
@traittinen 

Can you open a PR against [ansible-pan](https://github.com/PaloAltoNetworks/ansible-pan) to add this code there as well?

**Review by shinmog — CHANGES_REQUESTED** [review]
Actually, in light of #52355 this really shouldn't be merged anymore.  Please open a PR against PaloAltoNetworks/ansible-pan and add this new module there instead.

**Comment by traittinen** [comment]
Closing because of #52355.

**Pull request closed without merging**
