### PR TITLE
win_copy: allow src to have invalid windows chars

### LINKED ISSUE #31336: The win_copy module in 2.4.0.0 fails if src contains a ":" character
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_copy

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /opt/ansible24/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible24/venv/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible24/bin/ansible
  python version = 2.7.9 (default, May  7 2017, 21:48:55) [GCC]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Linux control machine managing Windows hosts.

##### SUMMARY
We store managed Windows files on the Linux control machine using paths that contain c:, d: etc which allows simple copying. This works fine with ansible < 2.4.0.0 but stops working in 2.4.0.0. Details below.

##### STEPS TO REPRODUCE
```
mkdir -p /tmp/c:/temp
echo 42 > /tmp/c:/temp/test.txt
ansible target -m win_copy -a 'src=/tmp/c:/temp/test.txt dest=c:/temp/test.txt'
```

##### EXPECTED RESULTS
Copy should work, just like it did in ansible before 2.4.0.0.

##### ACTUAL RESULTS
Copy fails with an error "Get-AnsibleParam: Parameter 'src' has an invalid path '/tmp/c:/temp/test.txt' specified.".

```
target | FAILED! => {
    "changed": false, 
    "checksum": "34973274ccef6ab4dfaaf86599792fa9c3fe4689", 
    "dest": "c:/temp/test.txt", 
    "failed": true, 
    "msg": "Get-AnsibleParam: Parameter 'src' has an invalid path '/tmp/c:/temp/test.txt' specified.", 
    "operation": "file_copy", 
    "original_basename": "test.txt", 
    "size": 3, 
    "src": "/tmp/c:/temp/test.txt"
}
```
##### ANALYSIS
Copying files using win_copy fails if the source path (on the control host running Linux) contains a ":" character. Disabling the $src parameter validation in win_copy.ps1 (i.e removing -type 'path' from the Get-AnsibleParam call) allows the copy to work. This is our temporary workaround, but this will probably cause a number of other problems.

The root cause seems to lie in the Get-AnsibleParam function in ansible/module_utils/powershell/Ansible.ModuleUtils.Legacy.psm1. The check "Test-Path -IsValid" is where we believe it fails. For example, running "Test-Path -IsValid /tmp/c:/test.txt" in powershell returns $False.

The win_copy module has been greatly improved since 2.3.0.0. I am guessing the Test-Path -IsValid code was never reached in the previous versions, maybe because $src was left empty since it is not really needed on the remote end for a normal copy? I tried "transplanting" the 2.3.0.0 win_copy.ps1 module into 2.4.0.0, but got the same error, which is why I think there has been a change of how the parameters are supplied during the invocation of the win_copy module.

I am not quite sure of the best way to fix this in the code. We need to somehow make sure that win_copy.ps1 never tries to validate a path that actually references something on the control machine.

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Fixes https://github.com/ansible/ansible/issues/31336, allows the src to be set to a file that contains invalid Windows characters as it can be renamed when it is copied.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_copy

##### ANSIBLE VERSION
```
2.5
```

### CODE REVIEW

**Review by nitzmahone — CHANGES_REQUESTED** [review]
LGTM other than the file with a colon will break on Windows checkouts- probably better to have the test create that file on the fly... Good to merge after that change.

**Comment by jhawkesworth** [comment]
Not tested but the code changes look good.

**Comment by jborean93** [comment]
Code has been changed to generate the file with a `:` in the name for the test to avoid check out issues on Windows.

**Comment by jborean93** [comment]
Changes have been cherry-picked to stable-2.4 for the 2.4.1 release https://github.com/ansible/ansible/commit/cb39aed465f0aa2182f3e6db0ef2c7be2c9aadfa

**Pull request merged**
