### PR TITLE
cloudformation: Fixed bug in module_fail. Consistent error handling.

### PR DESCRIPTION
**Pull request by jsmartin**
Had to close last pull request.. my repo got wonky.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this.

If I can share, there are some minor style fixes on stuff like this:

```
 def boto_exception(err):
 # generic error message handler
     <CODE>
```

inline comments should be intended at the same level as the line of code they are commenting, like so:

```
 def boto_exception(err):
      # generic error message handler
      <CODE>
```

Basically the comment is about the body of the function, so it gets indented.   OR better, use docstrings:

```
def boto_exception(err):
    ''' generic error message handler '''
     <CODE>
```

Similarly, comments about blocks of code shouldn't go against the left margin but should align with the code they are commenting, so...

```
# if the state is present and the stack already exists, we try to update it
# AWS will tell us if the stack template and parameters are the same and
# don't need to be updated.
      if update:
```

Should be:

```
   # if the state is present and the stack already exists, we try to update it
   # AWS will tell us if the stack template and parameters are the same and
   # don't need to be updated.
   if update:
```

finally, and I don't really enforce this everywhere, so it's not required:

 result = {'changed': False, 'output': 'Stack not found.' }

can be written cleaner as

```
 result = dict(changed=False, output="Stack not found.")
```

Since that helps avoid extra quoting as well as some curly braces.   I'd also probably be inclined to just say ''msg" here so the string more or less corresponds with reporting elsewhere in the app when there's some string explanation about something.

Sorry if this appears pedantic, if I accept it blind and tweak it, I have to retest on my end, so it's easier if I pass comments along.

Thanks!

**Comment by jsmartin** [comment]
Oh boy, just created more work for myself.  :).  That post may be a good reference for module authors, maybe have it in the docs?  Will have an update shortly.

**Comment by jsmartin** [comment]
Ok, hopefully that'll do it.  Note that I've made a slight change to the module -- the wait_for option never actually did anything, so I took it out.  Also, the stack_outputs no longer include the stack name and region since that information is redundant.

**Comment by mpdehaan** [comment]
I need to go through and update module development docs in the near future, I can include some style things then too... I'd ignore that for now, thanks for the update, merging this in now.

Much appreciated!

**Pull request merged**
