### PR TITLE
add logrotate config

### PR DESCRIPTION
**Pull request by copperlight**
Adds a logrotate config to the existing sample ansible-pull playbook.

### CODE REVIEW

**Comment by mpdehaan** [comment]
It seems misleading to set a variable for the logfile when it's not given to ansible that it can choose it's logfile.  It can't.   People will change it and be confused.

So make this /not/ take a variable for the logfile location and I'll take it.

Thanks!

**Comment by copperlight** [comment]
The location of the ansible-pull.log file is controlled by the >> redirect in the cronjob, so if you change this location, the logfile will go to a new location, say /var/log/ansible-pull.log versus /var/log/ansible/ansible-pull.log.

The logfile variable is templated out in both the cron.d and logrotate.d files.

I can strip the variable, but then the logrotate.d file ends up being a straight file-copy and the cron.d file loses one variable out of the template.  Is this what you are looking for?

**Comment by mpdehaan** [comment]
If it is redirecting and not logging directly that is fine.

I don't understand what you are saying with the other part but it does not
seem important.

In queue for review.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
