### PR TITLE
maven_artifact.py - add support for version ranges by using spec

### PR DESCRIPTION
**Pull request by pjrm**
##### SUMMARY
This PR allows to specify which versions of maven packages we want to download by using constraints.
The simple use case is when we want to download all patch versions released, but making sure that we don't download a major one.

Also I saw that other person have asked for this feature on [#20003](https://github.com/ansible/ansible/issues/20003)

The syntax supported for this module was based on this [page](https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges).

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
maven_artifact.py

### CODE REVIEW

**Comment by turb** [comment]
Excellent, this is a needed one. Thank you!

It will need some extended testing, with several version patterns and several repositories. I am not familiar with unit testing with Ansible, but I think some unit tests on the regexps would be great too. I don't think the sanity test should be disabled.

To what extent do you think the [Maven Specification](https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges) is implemented?

**Comment by pjrm** [comment]
Hi @turb,

Thanks for the reply.

Yes, I agree with you. I will try to find out how unit testings are done in Ansible, I have done some, but for sure it will be missing some cases.
Regarding the disabling of sanity test, I have done that because it failed from CI verification (you can see the ansibot comment, asking to remove it).

About the extent of Maven Specification, I'm not sure about it, but probably the first six ranges are implemented.

**Comment by pjrm** [comment]
I have added unit tests for this new feature. But I'm having troubles on CI.

Can anyone help me figure out why only Python 2.7 is having a timeout on unit testings? 
Other python versions pass without a problem.

Thank you

**Comment by turb** [comment]
I'll try to find some time to test this, cc @tumbl3w33d

**Comment by turb** [comment]
Finally had some time to test this one. I have 3 things so far.

**Dep**
One thing is it now requires the `semantic_version` python module. Maybe load it only if `version_by_spec` is set?


**Failure with pattern**
I tried with this:
```
---
- name: TEST
  hosts: <redacted>

  tasks:
    - name: test
      maven_artifact:
        group_id: org.apache.maven
        artifact_id: maven-artifact
        version_by_spec: "(,1.0]"
        repository_url: <redacted>
        dest: /tmp/tata.jar
```

And it failed with:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'patch'
fatal: [<redacted>]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_maven_artifact_payload_g_dbg_/__main__.py\", line 639, in <module>\n  File \"/tmp/ansible_maven_artifact_payload_g_dbg_/__main__.py\", line 620, in main\n  File \"/tmp/ansible_maven_artifact_payload_g_dbg_/__main__.py\", line 453, in download\n  File \"/tmp/ansible_maven_artifact_payload_g_dbg_/__main__.py\", line 371, in find_uri_for_artifact\n  File \"/tmp/ansible_maven_artifact_payload_g_dbg_/__main__.py\", line 352, in find_version_by_spec\nAttributeError: 'NoneType' object has no attribute 'patch'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Maybe it should fail with a specific error message if the pattern is not supported?


**Version publication**

If `version_by_spec` is set, `dest` is the `/tmp/mydir` directory and `artifact_id` is `commons-io` it writes into `/tmp/mydir/commons-io-None.jar`. In this case, the version should be appended.

**Comment by pjrm** [comment]
Thank you for the feedback @turb 

Regarding the first point, it's a good idea. I changed the behavior to fail if the semantic_version package is not installed and version_by_spec is defined.

The second one is an error means that the module didn't find any version that matches the spec version selected.

The last one is related with the previous one, and now the module is raising errors for "No version found with this spec version: {0}" and "The spec version ({0}) is not supported!".

**Comment by turb** [comment]
> Thank you for the feedback @turb
> 
> Regarding the first point, it's a good idea. I changed the behavior to fail if the semantic_version package is not installed and version_by_spec is defined.

Just tested it, looks good.

> 
> The second one is an error means that the module didn't find any version that matches the spec version selected.
> 

Great. It seems a heading "(" is added to the message, though.

> The last one is related with the previous one, and now the module is raising errors for "No version found with this spec version: {0}" and "The spec version ({0}) is not supported!".

The problem I pointed out is, if `dest` is a directory, the module is supposed to drop the artifact with `NAME-VERSION.EXTENSION`. The thing is, with `version-by-spec`, `VERSION` is set to `None` (e.g. `/tmp/mydir/myartifact-None.jar`), which is a bit ugly.

Either we can get the version, or set it to something related to the spec (normalized?), or set it to a constant/remove it.

I don't know which one is best for users. The challenge with the first one is we should then publish the resulting version in order to allow the users to manipulate the file later in their code.

@tumbl3w33d an opinion on this one?

**Comment by tumbl3w33d** [comment]
I agree that `None` in the filename is the worst solution and should not be considered an option.

Normalizing from the spec feels a little awkward too, but might still be better than nothing at all. An exactly determined version is preferable, obviously.

Apart from that - great work from the two of you. :+1:

**Comment by pjrm** [comment]
> Great. It seems a heading "(" is added to the message, though.

Thanks, I removed it to prevent misleading errors.

> The problem I pointed out is, if dest is a directory, the module is supposed to drop the artifact with NAME-VERSION.EXTENSION. The thing is, with version-by-spec, VERSION is set to None (e.g. /tmp/mydir/myartifact-None.jar), which is a bit ugly.

You're right. I thought that None was because of the bug that I had previously (when no version was matched). I fixed it right now and only works when the keep_name variable is set to true (this apply when using version also).

Testing example:
`{
    "ANSIBLE_MODULE_ARGS": {
        "_ansible_tmpdir": "/tmp",
        "artifact_id": "junit",
        "group_id": "junit",
        "keep_name": true,
        "version_by_spec": "[3.7, 4.0)",
        "dest": "/tmp/"
    }
}`

The output of this is:
`{"state": "file", "dest": "/tmp/junit-3.8.2.jar", "changed": false, ...}`

I agree that `None` on filename shouldn't be considered at all. 
Showing the version selected is better than normalizing spec version, with this users can see which version was selected by the module. However, this only works when `keep_name` value is set to true, if it's false (by default) and a folder is specified, it will have the `-None`. 
I left in this way because when using the latest, the problem is the same. 

@turb users can use the register directive to see the path where the file was saved, and with this, they can get the filename when using this option.

Thanks for the feedback @turb and @tumbl3w33d .

**Comment by turb** [comment]
> You're right. I thought that None was because of the bug that I had previously (when no version was matched).
> I fixed it right now and only works when the keep_name variable is set to true (this apply when using version also). If `keep_name` value is set to false (by default) and a folder is specified, it will have the `-None`.
> Should we change this behavior? I left in this way because when using `latest` it's the same output.

Well, nobody reported this one, but I think having `xxx-None.jar` with `latest` is definitely not the expected behaviour. I believe @tumbl3w33d would agree.

So yes, if you could fix this, it would be awesome.

> @turb users can use the register directive to see the path where the file was saved, and with this, they can get the filename when using this option.

Tested with `keep_name: true`, that's perfect.

**Comment by pjrm** [comment]
> Well, nobody reported this one, but I think having xxx-None.jar with latest is definitely not the expected behaviour. I believe @tumbl3w33d would agree.

> So yes, if you could fix this, it would be awesome.

Makes sense, and reading better the documentation, I think it's supposed to have only the artifact name when `keep_name: false`.

Let give me an example, based on example before, junit:
`keep_name: true` -> the filename should be junit-3.8.2.jar
`keep_name: false` -> the filename should be junit.jar

I apply changes on the module to behave like this.

Do you agree with this @turb and @tumbl3w33d ?

**Comment by turb** [comment]
Looks like the right thing.

**Comment by pjrm** [comment]
I have pushed the changes described.

Could you validate if anything else is needed?

Thanks

**Comment by tumbl3w33d** [comment]
When I try
``` yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - maven_artifact:
        version_by_spec: "[4.0]"
        artifact_id: corda
        group_id: net.corda
        dest: /tmp/
        keep_name: yes
```
then I receive `ValueError: Version string lacks a numerical component: 'corda-3.0'`. What am I doing wrong?

Besides, there should be at least one example added and the documentation should contain a link to the [spec doc](https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges).

**Comment by pjrm** [comment]
Thank you for that example. You're doing well, and the issue is that the project is not using the correct syntax of maven versioning.

If you look at the maven-metadata.xml (http://repo1.maven.org/maven2/net/corda/corda/maven-metadata.xml), you'll find:

`<metadata>
<groupId>net.corda</groupId>
<artifactId>corda</artifactId>
<versioning>
<latest>4.0</latest>
<release>4.0</release>
<versions>
<version>corda-3.0</version>
<version>0.7</version>`

The version `corda-3.0` don't respect the default specification `<major>.<minor>.<revision>([ -<qualififer> ] | [ -<build> ])`.

I will try to find a way to ignore these malformed versions and will add an example in the docs on how to use this option.

**Comment by pjrm** [comment]
I found a solution to ignore mal formed versions. 

Also added more info in the docs and an example.

@tumbl3w33d could you take a look? Thank you

**Comment by pjrm** [comment]
ready_for_review

**Review by tumbl3w33d — CHANGES_REQUESTED** [review]
Looks great, however, there's a little bug yet
``` yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - maven_artifact:
        version: latest
        artifact_id: spring-core
        group_id: org.springframework
        dest: /tmp/
        keep_name: yes
```
results in
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to download artifact org.springframework:spring-core:jar:jar:5.1.8.RELEASE because of HTTP Error 404: Not Foundfor URL http://repo1.maven.org/maven2/org/springframework/spring-core/5.1.8.RELEASE/spring-core-5.1.8.RELEASE-jar.jar"}
```
Guess you see the issue in the filename. :)

**Comment by pjrm** [comment]
Good catch! Fixed, hopefully the last one :)

**Comment by tumbl3w33d** [comment]
shipit

**Comment by turb** [comment]
Great! shipit

**Comment by gundalow** [comment]
rebuild_merge

@pjrm Thank you for this feature
@tumbl3w33d @turb Thank you as always for your reviews.

**Pull request merged**
