### PR TITLE
[WIP] Adding DigitalOcean API methods to helper function

### PR DESCRIPTION
**Pull request by vatsalparekh**
##### SUMMARY

Adding DigitalOcean API methods to existing helper function

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

`lib/ansible/module_utils/digital_ocean.py`
##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```
The `dopy` library is not actively maintained for latest updates, so it makes sense to have helper class have the latest functionality
```

### CODE REVIEW

**Comment by BondAnthony** [comment]
+label digital_ocean

**Comment by BondAnthony** [comment]
@vatsalparekh question about the create method. Would it make more sense to create a new `digital_ocean_droplet` module and include this code in that module? Operations for creating droplets would only be specific to that droplet instead of all the digital_ocean_* modules.

**Comment by BondAnthony** [comment]
@vatsalparekh are you still working on this or can it be closed?

**Comment by vatsalparekh** [comment]
@BondAnthony yes I want to work on this

**Comment by Akasurde** [comment]
@vatsalparekh are you still working on this ? needs_info

**Comment by vatsalparekh** [comment]
@Akasurde Not working right now

**Pull request closed without merging**
