### PR TITLE
Remove uses of assert in production code

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Running python with optimizations will remove assert statements allowing unexpected behavior throughout the code base.

This PR removes the use of assert statements, replacing them with simple `if` statements, that will raise a new `AnsibleAssertionError` that inherits from both `AnsibleError` and `AssertionError`.  This should maintain backwards compatibility throughout the codebase where `AssertionError` may be used.

In modules, we raise `AssertionError`.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by gundalow** [comment]
Do we need something in https://github.com/ansible/ansible/tree/devel/test/sanity to detect this?

**Comment by sivel** [comment]
We probably do.  I did some quick checks to see if pylint could handle this on it's own, and it didn't look like it.

I'll take a stab at it later.  I'll have to improve my search I used to detect it for removal, as it picks up docs and such for the `assert` module.

**Review by dagwieers — APPROVED** [review]

**Comment by sivel** [comment]
Ok, I fixed a couple of issues I had converting assertions to if statements.  I've also added a code-smell called `no-assert` and associated docs to go along with it.

Seems there is one test failure, but unrelated.

**Comment by sivel** [comment]
By the way, the no-assert script was written in python, because the regex was too complicated to work with grep, potentially BSD grep.  Since I do all of my dev on Mac it wasn’t super feasible to implement the test with grep.

**Comment by mattclay** [comment]
@sivel Implementing the sanity test in Python is a good thing. Eventually I would like to convert most, if not all, of the sanity tests to Python, either as part of ansible-test or as pylint plugins. Having the initial implementation of the tests in Python should make that easier.

**Comment by BondAnthony** [comment]
LGTM for the Digital Ocean module.

**Review by mattclay — APPROVED** [review]

**Comment by sivel** [comment]
rebuild_merge

**Comment by sivel** [comment]
rebuild_merge

**Comment by sivel** [comment]
rebuild_merge

**Pull request merged**
