### PR TITLE
Add regex (search, match, regex) jinja2 filters. Fixes #3725

### LINKED ISSUE #3725: add a regex Jinja2 filter
Folks would like to do

```
foo | search(some_regex)
```

in expressions from Jinja2 and re.search does not work.

Need to test if foo.search is already avail in regular templates and then it may just be a matter of importing in playbooks to enable foo.search

### PR DESCRIPTION
**Pull request by sivel**

### CODE REVIEW

**Comment by sivel** [comment]
Pull request updated to merge in the current state of 'devel' due to changes made in the files affected by this request.

**Comment by dmac** [comment]
+1, this would be really great to have.

**Comment by mpdehaan** [comment]
Hi @sivel,

Can you please submit these without merge commits?

Use "git pull --rebase" vs "git pull" and "git rebase" vs "git merge"

Generally speaking, we don't allow merge commits in pull requests as they cause review problems.

(You may also want to squash merge at the same time)

Thanks!

**Comment by sivel** [comment]
@mpdehaan My branch has been squashed.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
