### PR TITLE
Add typetalk notification module

### PR DESCRIPTION
**Pull request by tksmd**
Here I added typetalk ( chat service like hipchat or campfire ) notification plugin. It only depends on standard modules like urllib, urllib2 and json.

I'm already using this plugin in my environment and hope it merged into core. And this is my first time to send pull request to this project and if there's something I should do more, please let me know. Thanks.

### CODE REVIEW

**Comment by dragon3** [comment]
:+1:

**Comment by ikikko** [comment]
I want to use this module ! :+1:

**Comment by shoito** [comment]
:+1:

**Comment by mpdehaan** [comment]
This has been merged into the development branch (1.6) -- thank you!  Sorry about the delay, there's been quite the backlog!

**Comment by tksmd** [comment]
Thanks! :smile: :smile: :smile:

**Pull request merged**
