### PR TITLE
ansible-galaxy - optimise some paths and use fake galaxy int tests

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
* Optimise a few paths in the ansible-galaxy API handler to avoid unecessary redirects.
* Fix up error messages when using an invalid token with Galaxy
* Actually send sha256 hash in form data instead of sha1 (need to double check with Galaxy team)
* Stop unnecessary checks on the Galaxy token file if it is not set
* Fix up pagination of versions when talking to Automation Hub

This adds the [fallaxy-test-container](https://github.com/ansible/fallaxy-test-container) which mocks both Galaxy (v2) and Automation Hub (v3). It does not implement the full API but the calls that ansible-galaxy makes when publishing and installing a collection.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-galaxy

### CODE REVIEW

**Comment by bmbouter** [comment]
I tested this PR against pulp_ansible's viewsets to receive uploads and this PR breaks uploads for pulp_ansible. I confirmed the v2.9.5 tag does not break it with my source checkout. I need to look at the break closer, but I wanted to share what I found already.

**Comment by jborean93** [comment]
Just as an FYI the changes in this PR have veen tested against both Automation Hub and Galaxy

### Automation Hub

```
(ansible-py37) jborean:~/dev/jborean/test$ ansible-galaxy collection publish jborean-test-1.0.0.tar.gz -s ci_automation_hub -vvv
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly
changing source of code and can become unstable at any point.
ansible-galaxy 2.10.0.dev0
  config file = /home/jborean/dev/jborean/test/ansible.cfg
  configured module search path = ['/home/jborean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jborean/dev/ansible/lib/ansible
  executable location = /home/jborean/dev/ansible/bin/ansible-galaxy
  python version = 3.7.6 (default, Jan 13 2020, 17:44:56) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Using /home/jborean/dev/jborean/test/ansible.cfg as config file
Publishing collection artifact '/home/jborean/dev/jborean/test/jborean-test-1.0.0.tar.gz' to ci_automation_hub https://ci.cloud.redhat.com/api/automation-hub/
Collection has been published to the Galaxy server ci_automation_hub https://ci.cloud.redhat.com/api/automation-hub/
Waiting until Galaxy import task https://ci.cloud.redhat.com/api/automation-hub/v3/imports/collections/c1bcb469-08ec-4c6e-8053-51d305a5a674/ has completed
Galaxy import message: INFO - Getting doc strings via ansible-doc
Galaxy import message: INFO - Finding content inside collection
Collection has been successfully published and imported to the Galaxy server ci_automation_hub https://ci.cloud.redhat.com/api/automation-hub/

# Just used a random collection to install from proper Automation Hub not testing
(ansible-py37) jborean:~/dev/jborean/test$ ansible-galaxy collection install azure.azcollection -s automation_hub -vvv
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly
changing source of code and can become unstable at any point.
ansible-galaxy 2.10.0.dev0
  config file = /home/jborean/dev/jborean/test/ansible.cfg
  configured module search path = ['/home/jborean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jborean/dev/ansible/lib/ansible
  executable location = /home/jborean/dev/ansible/bin/ansible-galaxy
  python version = 3.7.6 (default, Jan 13 2020, 17:44:56) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Using /home/jborean/dev/jborean/test/ansible.cfg as config file
Found installed collection alikins.collection_ntp:0.1.182 at '/home/jborean/.ansible/collections/ansible_collections/alikins/collection_ntp'
Found installed collection alikins.collection_inspect:0.0.38 at '/home/jborean/.ansible/collections/ansible_collections/alikins/collection_inspect'
Found installed collection alikins.collection_reqs_test:2.1113.55 at '/home/jborean/.ansible/collections/ansible_collections/alikins/collection_reqs_test'
Found installed collection google.cloud:0.0.7 at '/home/jborean/.ansible/collections/ansible_collections/google/cloud'
Found installed collection ansible.windows:1.0.0 at '/home/jborean/.ansible/collections/ansible_collections/ansible/windows'
Found installed collection ktdreyer.koji_ansible:0.0.0-git.222+7fb2d32f at '/home/jborean/.ansible/collections/ansible_collections/ktdreyer/koji_ansible'
Process install dependency map
Processing requirement collection 'azure.azcollection'
Collection 'azure.azcollection' obtained from server automation_hub https://cloud.redhat.com/api/automation-hub/
Starting collection install process
Installing 'azure.azcollection:0.0.2' to '/home/jborean/.ansible/collections/ansible_collections/azure/azcollection'
Downloading https://cloud.redhat.com/api/automation-hub/v3/artifacts/collections/azure.azcollection.0.0.2 to /home/jborean/.ansible/tmp/ansible-local-94435keffkhri/tmpfhkbxxqr
```

### Galaxy

```
(ansible-py37) jborean:~/dev/jborean/test$ ansible-galaxy collection publish jborean93-test-1.0.0.tar.gz -s galaxy -vvv
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly
changing source of code and can become unstable at any point.
ansible-galaxy 2.10.0.dev0
  config file = /home/jborean/dev/jborean/test/ansible.cfg
  configured module search path = ['/home/jborean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jborean/dev/ansible/lib/ansible
  executable location = /home/jborean/dev/ansible/bin/ansible-galaxy
  python version = 3.7.6 (default, Jan 13 2020, 17:44:56) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Using /home/jborean/dev/jborean/test/ansible.cfg as config file
Opened /home/jborean/.ansible/galaxy_token
Publishing collection artifact '/home/jborean/dev/jborean/test/jborean93-test-1.0.0.tar.gz' to galaxy https://galaxy-dev.ansible.com/api/
Collection has been published to the Galaxy server galaxy https://galaxy-dev.ansible.com/api/
Waiting until Galaxy import task https://galaxy-dev.ansible.com/api/v2/collection-imports/75987/ has completed
Galaxy import process has a status of waiting, wait 2 seconds before trying again
Galaxy import process has a status of waiting, wait 3 seconds before trying again
Galaxy import message: INFO - Starting import: task_id=75987, artifact_id=76001
Galaxy import message: INFO - Import completed with 0 warnings and 0 errors
Collection has been successfully published and imported to the Galaxy server galaxy https://galaxy-dev.ansible.com/api/


(ansible-py37) jborean:~/dev/jborean/test$ ansible-galaxy collection install jborean93.test -s galaxy -vvv
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly
changing source of code and can become unstable at any point.
ansible-galaxy 2.10.0.dev0
  config file = /home/jborean/dev/jborean/test/ansible.cfg
  configured module search path = ['/home/jborean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jborean/dev/ansible/lib/ansible
  executable location = /home/jborean/dev/ansible/bin/ansible-galaxy
  python version = 3.7.6 (default, Jan 13 2020, 17:44:56) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Using /home/jborean/dev/jborean/test/ansible.cfg as config file
Found installed collection jborean93.windows:2.1.12 at '/home/jborean/.ansible/collections/ansible_collections/jborean93/windows'
Found installed collection alikins.collection_ntp:0.1.182 at '/home/jborean/.ansible/collections/ansible_collections/alikins/collection_ntp'
Found installed collection alikins.collection_inspect:0.0.38 at '/home/jborean/.ansible/collections/ansible_collections/alikins/collection_inspect'
Found installed collection alikins.collection_reqs_test:2.1113.55 at '/home/jborean/.ansible/collections/ansible_collections/alikins/collection_reqs_test'
Found installed collection google.cloud:0.0.7 at '/home/jborean/.ansible/collections/ansible_collections/google/cloud'
Found installed collection ansible.windows:1.0.0 at '/home/jborean/.ansible/collections/ansible_collections/ansible/windows'
Found installed collection ktdreyer.koji_ansible:0.0.0-git.222+7fb2d32f at '/home/jborean/.ansible/collections/ansible_collections/ktdreyer/koji_ansible'
Process install dependency map
Opened /home/jborean/.ansible/galaxy_token
Processing requirement collection 'jborean93.test'
Collection 'jborean93.test' obtained from server galaxy https://galaxy-dev.ansible.com/api/
Starting collection install process
Installing 'jborean93.test:1.0.0' to '/home/jborean/.ansible/collections/ansible_collections/jborean93/test'
Downloading https://galaxy-dev.ansible.com/download/jborean93-test-1.0.0.tar.gz to /home/jborean/.ansible/tmp/ansible-local-91656jzfevhy6/tmp8ykhc7_6
```

When you get a chance are you able to investigate why pulp might be failing. From my perspective these changes are fine with Automation Hub and Galaxy.

**Comment by bmbouter** [comment]
@jborean93 thank you for filing [the bug against pulp_ansible](https://pulp.plan.io/issues/6239). The fix has been merged to pulp_ansible already so +1 to merging this.

**Comment by jborean93** [comment]
Backport PR to stable-2.9 https://github.com/ansible/ansible/pull/67874

**Pull request merged**
