### PR TITLE
Add backupdir option

### PR DESCRIPTION
**Pull request by obourdon**
##### SUMMARY
This option allows the backup file to be moved into another location

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
interfaces_file

##### ANSIBLE VERSION
```
ansible 2.6.0 (work e2aa1155ba) last updated 2018/04/19 09:51:12 (GMT +200)
  config file = None
  configured module search path = [u'/Users/olivierbourdon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/olivierbourdon/Documents/WORK/OpenNext/TECH/CODE/ANSIBLE/0-REF-ansible/lib/ansible
  executable location = /Users/olivierbourdon/Documents/WORK/OpenNext/TECH/CODE/ANSIBLE/0-REF-ansible/bin/ansible
  python version = 2.7.14 (default, Sep 22 2017, 00:06:07) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### ADDITIONAL INFORMATION

None

### CODE REVIEW

**Comment by hryamzik** [comment]
LGTM

**Comment by obourdon** [comment]
@hryamzik thanks for the review. Posted a small modification in the doc section to comply with CI rules

**Comment by obourdon** [comment]
@gundalow same review request for this one please. Many thanks

**Comment by obourdon** [comment]
@gundalow same review request for this one please. Many thanks

**Comment by obourdon** [comment]
@gundalow could this please be merged ? Many thanks in advance

**Comment by obourdon** [comment]
@core @coreteam any volunteers to review and merge please ?

**Comment by bcoca** [comment]
`backup` is a general feature across several modules, which return the path in `backup_file`. I would not add a backupdir, but build a solution that moves backups to central location based on the return info in `backup_file`.

**Review by bcoca — CHANGES_REQUESTED** [review]
Even if we looked at adding this as an option, it would have to apply to all modules that allow for the existing `backup` facility.

**Pull request closed without merging**
