### PR TITLE
add user-agent to Azure API calls

### PR DESCRIPTION
**Pull request by xscript**
##### SUMMARY

- Add Ansible `user-agent` back in Azure API calls. It was removed in this [commit](https://github.com/ansible/ansible/commit/d1b611a730387ae0a9a31060d60281150a60ddba#diff-2b622fe76a39bb9004ac394693b03853L600).
- Minor refactor for required package version check.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`azure_rm_common`

##### ANSIBLE VERSION

```
ansible 2.5.0 (user-agent 7f350f6ed0) last updated 2017/10/18 15:14:09 (GMT +800)
  config file = None
  configured module search path = [u'/Users/kevinzha/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kevinzha/workspace/ansible/lib/ansible
  executable location = ./bin/ansible
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
FYI @haroldwongms @nitzmahone @tstringer

**Comment by xscript** [comment]
Could anybody help me understand below error? I saw other places using this way in Ansible.
```
lib/ansible/module_utils/azure_rm_common.py:29:0: ModuleNotFoundError: No module named 'ansible.release'
```

**Comment by xscript** [comment]
Hi @haroldwongms @nitzmahone @tstringer , please help take a look at this PR. Thanks very much!

**Review by nitzmahone — APPROVED** [review]

**Comment by xscript** [comment]
@nitzmahone Thanks very much!
Just have one more question:
Does Ansible have any page for release schedule planning? The [Milestones page](https://github.com/ansible/ansible/milestones) doesn't include any dates. I'd really like to understand the release schedules to accommodate our PRs.

**Pull request merged**
