### PR TITLE
Added argument --private-ips

### PR DESCRIPTION
**Pull request by Repox**
I needed this argument for avoiding connecting via the WAN IP for a dynamic inventory.

### CODE REVIEW

**Comment by jimi-c** [comment]
Typically we discourage the addition of parameters for inventories outside of --list and --host, since there is no real way to trigger those via Ansible's internal inventory API. Instead, these kinds of options should be added to the INI configuration read in by the inventory scripts, though I do see the DO script has several options already.

**Comment by Repox** [comment]
I see your point. I've updated the script so that it initially will take the configuration option from the .ini file.
Would you prefer I remove the parameter?

**Comment by jimi-c** [comment]
I think it's fine if it stays, since it's also now configurable via the INI. Thanks!

**Comment by Repox** [comment]
Is this something that will be merged at some point? Otherwise I'll close it.

**Comment by bennojoy** [comment]
@Repox sorry for delay , we have been a bit busy with the v2 stuffs, we will definitely get to this asap.

**Comment by amenonsen** [comment]
This looks pretty reasonable, but I have no way to test it. Anyone using the DO inventory want to try it out?

@Repox any chance you could rebase this to apply to current devel?

**Comment by amenonsen** [comment]
This still looks sensible, but it needs to be rebased (easy) and tested (which I'm not in a position to do). If anyone using the DO inventory script wants to do both things and confirm that it works, I would like to merge this. Otherwise this PR can be closed.

**Comment by amenonsen** [comment]
I'm closing this PR now, since it hasn't been updated, but please feel free to open a new one if you get a chance to update your patch.

Since this is a really busy project, we don't always see comments on closed tickets, but if you want to reopen discussion on this subject, please feel free to do so on the development mailing list:

```
* https://groups.google.com/forum/#!forum/ansible-devel
```

Thanks again for your contribution to Ansible.

**Pull request closed without merging**
