### PR TITLE
add role_attr_flags parameter to postgresql_user

### PR DESCRIPTION
**Pull request by inertialbit**
Pass role_attr_flags a list of comma separated role
attributes when creating or updating a user.

### CODE REVIEW

**Comment by mpdehaan** [comment]
past the 0.8 feature freeze date, so this is on deck for review when 0.9 starts (after Friday) ... stay tuned

**Comment by inertialbit** [comment]
sounds good. i should mention it's only been tested on python 2.7 & ubuntu 12. thanks!

**Comment by mpdehaan** [comment]
@lorin  -- you're my default person to ping postgresql questions to, thoughts?

**Comment by lorin** [comment]
Looks fine to me. Based on this change proposal, I suspect that inertialbit knows more about postgres than I do.

**Comment by mpdehaan** [comment]
merging, thanks!

**Pull request merged**
