### PR TITLE
mysql_replication module added

### PR DESCRIPTION
**Pull request by banyek**
Module to manage MySQL server replication through ansible.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks pretty good now, thanks!

I see some indentation issues around line 305 that need to be cleaned up.  Can you also add an EXAMPLES section like some of the other modules have?   ack -a "EXAMPLES" in the library directory to see what I am suggesting.

Then I think we are finally good to merge this.

Thanks!

**Comment by banyek** [comment]
I hope these were the indentation issues what you mentioned. 
Also added the EXAMPLES section.

**Comment by nicolas-g** [comment]
What's the status with this merge ? :)

**Comment by jimi-c** [comment]
@nicolas-g getting to it, there's a pretty big backlog of issues I'm working through at the moment. I will get to it soon I hope.

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by banyek** [comment]
yeeah :)

**Pull request merged**
