### PR TITLE
nxos: merge nxapi/cli tests - config, bgp_neighbor, command, bgp_af

### PR DESCRIPTION
**Pull request by newswangerd**
##### SUMMARY

There is a lot of duplicate code in the nxos integration tests because we have separate files for nxapi and cli tests. Most of the time, these files are identical save for changing the provider argument from {{ nxapi }} to {{ cli }}.

This PR creates a new common directory in all of the nxos tests where common tests can be stored. CLI and NXAPI tests will both load the tests in this directory and simply pass the correct connection parameters to the test. CLI tests will still load the tests from the cli/ directory (when present) and NXAPI will still load tests from nxapi/.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- nxos_bgp_af
- nxos_bgp_neighbor
- nxos_command
- nxos_config

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jborean93** [comment]
cc @GGabriele @jedelman8 @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha

**Review by mattclay — CHANGES_REQUESTED** [review]
Please remove the unnecessary `test/integration/-` file.

**Comment by newswangerd** [comment]
Removed the file. Not sure how it got in there.

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
@newswangerd I approved the removal of the extra file. I haven't reviewed the other changes.

**Review by trishnaguha — APPROVED** [review]

**Pull request merged**
