### PR TITLE
added environment variables as config overrides for vmware inventory

### PR DESCRIPTION
**Pull request by bcoca**
so now this can be configured through exporting env variables like other inventory scripts.

### CODE REVIEW

**Comment by mpdehaan** [comment]
We do need env var configuration but it is very important that this be a predictable variable name (particularly for tower).  Could this be VMWARE_USER, etc?

**Comment by mpdehaan** [comment]
cc @lukesneeringer

**Comment by bcoca** [comment]
I can add both, since i need multiple configs with diff users/servers I
need the 'variety'. I'll update PR tonight

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by lukesneeringer** [comment]
Hi @bcoca,
First of all, thank you for your patch! :-)

I'm thinking through the thing with the environment variable names, and something still doesn't sit right with me about the current implementation. Having the script name on disk be used for the environment variables, while this is done sometimes (e.g. for bash autocomplete), is unusual. I guess I don't mind that much, since 99% of users will just use `VMWARE_*`, but as it stands I'm worried about getting in a weird situation where a variable "magically" takes and the user doesn't know why.

My original thought was to ask you to change the precedence order, so we check `VMWARE_*` first, then we check `{scriptname}-*` second.

After thinking about it more, though, I think what I'd prefer would be that if you need the multiple environment variables, that they be faux-namespaced one more level.

So:
- first, check `VMWARE_{scriptname}_HOST`
- second, check `VMWARE_HOST`
- third, check the INI file

Essentially, I'm asking you to change `{scriptname}_HOST` to `VMWARE_{scriptname}_HOST` (and same for `USER` and `PASSWORD`), and leave everything else about your implementation the same. Essentially that makes it so that there's really no way that anyone stumbles on that by accident. It also makes it very clear if we have a situation where we apply similar functionality to other dynamic inventory scripts. (I'm not sure whether we will do that, but I want to be thinking as if we might.)

Would that be okay with you?

**Comment by bcoca** [comment]
no problem, I'm just a lazy typist, I'll push and update tonight.​

**Pull request closed without merging**
