### PR TITLE
Facts dev upstream

### PR DESCRIPTION
**Pull request by ndswartz**
##### SUMMARY
Added the following facts:

    storage system segment size
    cache block size capabilities
    workload tags
    storage array hosts
    host groups
    list of mapped volumes for each initiator

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

netapp_e_facts

##### ADDITIONAL INFORMATION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/swartzn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/swartzn/ansible-dev/lib/ansible
  executable location = /home/swartzn/ansible-dev/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

### CODE REVIEW

**Comment by thedoubl3j** [comment]
@ndswartz I am not seeing any testing for this at all, could we get some coverage on this?

**Comment by ndswartz** [comment]
@thedoubl3j Added unit test coverage

**Comment by thedoubl3j** [comment]
thank you @ndswartz reviewing now

**Review by thedoubl3j — APPROVED** [review]
lgtm, thanks for adding some coverage.

**Comment by thedoubl3j** [comment]
rebuild_merge

**Review by anshulbehl — APPROVED** [review]

**Pull request merged**
