### PR TITLE
Add Thruk as Grafana Datasource

### PR DESCRIPTION
**Pull request by rverchere**
##### SUMMARY

Add Thruk as a Grafana Datasource

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Updates the grafana_datasource module

##### ADDITIONAL INFORMATION
Replaces the following commands:

```bash
grafana-cli plugins install sni-thruk-datasource
```

This will install this datasource plugin: https://grafana.com/plugins/sni-thruk-datasource

### CODE REVIEW

**Comment by rrey** [comment]
Hi @rverchere,

Can you add an example in the module documentation ?
In your patch you only allow additional content for the datasource name, but nothing for the datasource creation query ?

**Comment by rverchere** [comment]
Hi @rrey,

> Can you add an example in the module documentation ?

Done

> In your patch you only allow additional content for the datasource name, but nothing for the datasource creation query ?

There is no specific requirement for the thruk datasource, only URL is mandatory (https://grafana.com/grafana/plugins/sni-thruk-datasource).

**Comment by seuf** [comment]
There is so many data-source plugins in Grafana. Maybe we should allow any string for `ds_type`.
The problem is that some data sources are requiring additional fields.
The Thruk datasource does not require additional fields, so it's ok for me.

ship_it

**Comment by rverchere** [comment]
> There is so many data-source plugins in Grafana. Maybe we should allow any string for `ds_type`.

I totally agree!

**Review by seuf — APPROVED** [review]

**Comment by seuf** [comment]
LGTM

**Comment by gundalow** [comment]
Hi @rverchere Thank you for this PR.

We are changing the GitHub repositories that make up the Ansible Release and Grafana is one of the first we are spinning out into its own repo: https://github.com/ansible-collections/grafana

It seems like this PR has been approved by one of the Grafana Maintainers, thanks @rrey & @seuf. 
So the next step if you are able to is creating a fresh PR against https://github.com/ansible-collections/grafana/blob/master/plugins/modules/grafana_datasource.py

We hope that these smaller Repositories (and the Collections they contain) will allow us to release changes sooner to users like yourself, rather than having to wait for the twice-yearly Ansible Major release.

If you have any questions, please do shout out.

**Comment by rverchere** [comment]
> Hi @rverchere Thank you for this PR.

Hi @gundalow !
 
> We are changing the GitHub repositories that make up the Ansible Release and Grafana is one of the first we are spinning out into its own repo: https://github.com/ansible-collections/grafana
> 
> It seems like this PR has been approved by one of the Grafana Maintainers, thanks @rrey & @seuf.
> So the next step if you are able to is creating a fresh PR against https://github.com/ansible-collections/grafana/blob/master/plugins/modules/grafana_datasource.py

Done here : https://github.com/ansible-collections/grafana/pull/23

> We hope that these smaller Repositories (and the Collections they contain) will allow us to release changes sooner to users like yourself, rather than having to wait for the twice-yearly Ansible Major release.

Good news!

**Comment by gundalow** [comment]
Closing this PR, as the feature improvement is now being done in the Grafana Collection.
Thank you

**Pull request closed without merging**
