### PR TITLE
Added inventory plugin for hosts from ~/.ssh/config

### PR DESCRIPTION
**Pull request by t0mk**
Inventory script that lets you use the aliases from ~/.ssh/config

### CODE REVIEW

**Comment by mpdehaan** [comment]
Merged, thank you!

**Comment by aaronbauman** [comment]
Thanks for this script - very promising as I have a ton of static remotes defined in ssh_config

Looks like it's choking on multi-aliases from my ssh config.
Do you think it will be possible to support multi-aliases (I can work on a patch if so), or do I need to re-think ssh config?

**Comment by aaronbauman** [comment]
Here's the error I'm getting:

```
FAILED => Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/ansible-2.0.0-py2.6.egg/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.6/dist-packages/ansible-2.0.0-py2.6.egg/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.6/dist-packages/ansible-2.0.0-py2.6.egg/ansible/runner/__init__.py", line 900, in _executor_internal_inner
    actual_private_key_file = os.path.expanduser(actual_private_key_file)
  File "/usr/lib/python2.6/posixpath.py", line 251, in expanduser
    if not path.startswith('~'):
AttributeError: 'list' object has no attribute 'startswith'
```

Sorry if this is not the appropriate place to post all this info.

**Comment by aaronbauman** [comment]
OK, this actually seems like a bug with handling of identityfile in ssh config.
Created a proper pull request here: https://github.com/ansible/ansible/pull/11013

**Pull request merged**
