### PR TITLE
Update ansible.cfg

### LINKED ISSUE #64569: Provided ansible.cfg contains outdated, non-working sample configs
##### SUMMARY
Some of the examples in the provided ansible.cfg are incomplete or outdated.
For example: the `sudo_flags` in the defaults section doesn't do anything, while `become_flags` does work, it only works when in the `privilege_escalation` section, but an example is missing from that section.
I suspect there are other things missing/incorrect in the config file that could be updated to better reflect sane defaults.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`ansible.cfg`

##### ANSIBLE VERSION

```paste below
ansible 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/awheeler/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_CONTROL_PATH(/home/awheeler/it-ansible-repo/ansible.cfg) = %(directory)s/%%h-%%r
DEFAULT_BECOME_METHOD(/home/awheeler/it-ansible-repo/ansible.cfg) = sudo
DEFAULT_CALLBACK_WHITELIST(/home/awheeler/it-ansible-repo/ansible.cfg) = [u'profile_tasks', u'dense']
DEFAULT_FORKS(/home/awheeler/it-ansible-repo/ansible.cfg) = 5
DEFAULT_HOST_LIST(/home/awheeler/it-ansible-repo/ansible.cfg) = [u'/home/awheeler/it-ansible-repo/hosts']
DEFAULT_MANAGED_STR(/home/awheeler/it-ansible-repo/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/home/awheeler/it-ansible-repo/ansible.cfg) = [u'/usr/share/ansible', u'/etc/ansible/modules']
DEFAULT_POLL_INTERVAL(/home/awheeler/it-ansible-repo/ansible.cfg) = 15
DEFAULT_ROLES_PATH(/home/awheeler/it-ansible-repo/ansible.cfg) = [u'/home/awheeler/it-ansible-repo/roles', u'/home/awheeler/it-ansible-repo/librarian_roles', u'/etc/ansible/librarian_roles']
HOST_KEY_CHECKING(/home/awheeler/it-ansible-repo/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/awheeler/it-ansible-repo/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/awheeler/it-ansible-repo/ansible.cfg) = /home/awheeler/.ansible-retry
TRANSFORM_INVALID_GROUP_CHARS(/home/awheeler/it-ansible-repo/ansible.cfg) = never
```

##### OS / ENVIRONMENT
CentOS 6/7 

##### STEPS TO REPRODUCE

Uncomment `sudo_flags` in the provided ansible.cfg, and change the `sudo_flags` to include -E, to preserve environment.

```
ansible -m shell localhost -a 'env'
ansible -m shell localhost -a 'env' -b
```

##### EXPECTED RESULTS
The output env should be pretty much the same between the two commands

##### ACTUAL RESULTS

Because the `sudo_flags` are ignored, most of the env variables are missing from the second command.

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

- clean out old options that are now deprecated
- clean up formatting of comments a bit
- add become plugin examples

Fixes #64569

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

`examples/ansible.cfg`

### CODE REVIEW

**Comment by samdoran** [comment]
I could use some input on what the values in this document should contain. In the past, it was a mix of default values and examples of possible values. I tried to change most things to be the default value just commented out unless explicitly noted.

I'm not sure what is considered a better/less confusing example config: default options commented out, or possible examples. We've had a lot of confusion about that in the past since some people thought the commented out values were the default values rather than example values.

**Comment by cbudz** [comment]
Hi @samdoran, since https://docs.ansible.com/ansible/latest/reference_appendices/config.html provides default values for config options, I'd recommend that source stand as the the listing for default values and point to it, as you've done, and only provide example values in this doc. Anything not within the context of an example, like [privilege escalation] I would add some example context to or simply remove.

**Comment by acozine** [comment]
Thanks @samdoran for the clean-up! This is much better than it was.

**Comment by awheeler** [comment]
Thanks @samdoran , this looks so much better!

**Pull request merged**
