### PR TITLE
module mongodb_user fix roles default value (#46443)

### PR DESCRIPTION
**Pull request by jorijinnall**
##### SUMMARY
Fixes issue #46443 

Add default value for the parameter "roles"

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mongodb_user module

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0 (jori_fix_46443 51667a5753) last updated 2018/10/05 11:30:00 (GMT +200)
  config file = None
  configured module search path = ['/Users/jdelannoye/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jdelannoye/Projects/Ansible/ansible/lib/ansible
  executable location = ./bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:13:53) [Clang 8.0.0 (clang-800.0.42.1)]
```

### CODE REVIEW

**Review by pilou- — APPROVED** [review]
LGTM (not tested). This fix should be backported.

**Comment by maxamillion** [comment]
This should probably get a changelog snippet since it alters default behavior.

**Comment by pilou-** [comment]
@jorijinnall changelog are located in `changelogs/fragments` directory, the related documentation is available [here](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html?#changelogs).

**Comment by maxamillion** [comment]
This was discussed in `#ansible-devel` on freenode and the consensus was that the change would incur negative impact on users as well as providing new/different (potentially more permissive) permissions than expected. Therefore, instead of updating the module, this should simply be a documentation change so that the docs reflect what the module is actually doing.

**Comment by jorijinnall** [comment]
@maxamillion Thanks for having a look to this PR. Do you recommend to close this PR and open a new one with the change you recommend, or just change this current PR ?

Thanks

**Comment by maxamillion** [comment]
@jorijinnall just changing this one should be fine, we'll squash the commits upon merge.

**Comment by jorijinnall** [comment]
@maxamillion  done

**Comment by jorijinnall** [comment]
rebase done

**Comment by maxamillion** [comment]
needs_revision

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by jorijinnall** [comment]
@maxamillion is this one can be merged or do you expect me something ?

**Comment by maxamillion** [comment]
@jorijinnall the bot was supposed to merge it, apologies.

**Comment by maxamillion** [comment]
bot_status

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by maxamillion** [comment]
rebuild_merge

**Pull request merged**
