### PR TITLE
Testing Pull Requests, submodule testing addition to docs

### PR DESCRIPTION
**Pull request by juliedavila**
Simple but helpful addition to the documentation for testing submodule pull requests

### CODE REVIEW

**Comment by amenonsen** [comment]
This looks OK, but again, I'd prefer to see a single sentence saying you need to cd into the right module directory before doing the fetch/checkout rather than duplicating the block.

**Comment by bcoca** [comment]
actually for testing i would use a local 'library' directory adjacent to play, so as not to have to deal with root permissions nor backing out changes for the ansible installation that might even be shared.

**Comment by juliedavila** [comment]
Ha! Completely forgot about this PR. I'll update it later on.

**Comment by amenonsen** [comment]
ping @defionscode

**Pull request closed without merging**
