### PR TITLE
New module postgresql_membership: Add or remove PostgreSQL roles from groups

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Adds or removes PostgreSQL roles from groups (other roles)

Implements role membership https://www.postgresql.org/docs/current/role-membership.html.

Users are roles with login privilege.
Groups are PostgreSQL roles usually without LOGIN privelege.

Common use case:
1) add a new group (groups) by postgresql_user module
2) grant them desired privileges by postgresql_privs module
3) add desired PostgreSQL users to the new group (groups) by this module

##### ISSUE TYPE
- New Module Pull Request

##### MAIN OPTIONS
- groups [group, source_role, source_roles]: The list of groups (roles) that need to be granted to or revoked from I(target_roles).
- target_roles [target_role, users, user]: The list of target roles (groups will be granted to them).
- fail_on_role: If yes, fail when group or target_role doesn't exist. If no, just warn and continue.

##### EXAMPLES
```
- name: Grant role read_only to alice and bob
  postgresql_membership:
    group: read_only
    target_roles:
    - alice
    - bob
    state: present

- name: Revoke role read_only and exec_func from bob. Ignore if roles don't exist
  postgresql_membership:
    groups:
    - read_only
    - exec_func
    target_role: bob
    fail_on_role: no
    state: absent
```
##### RETURNS
```
queries:
    description: List of executed queries.
    returned: always
    type: str
    sample: [ "GRANT \"user_ro\" TO \"alice\"" ]
granted:
    description: Dict of granted groups and roles.
    returned: if I(state=present)
    type: dict
    sample: { "ro_group": [ "alice", "bob" ] }
revoked:
    description: Dict of revoked groups and roles.
    returned: if I(state=absent)
    type: dict
    sample: { "ro_group": [ "alice", "bob" ] }
state:
    description: Membership state that tried to be set.
    returned: always
    type: str
    sample: "present"
```
##### OUTPUT EXAMPLE
```
    "changed": true, 
    "granted": {
        "group1": [
            "user1"
        ], 
        "group2": [
            "user1"
        ]
    }, 
    "groups": [
        "group1", 
        "group2"
    ], 
    "queries": [
        "GRANT \"group1\" TO \"user1\"", 
        "GRANT \"group2\" TO \"user1\""
    ], 
    "state": "present", 
    "target_roles": [
        "user1"
    ]
```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by tcraxs** [comment]
shipit

**Comment by Andersson007** [comment]
@tcraxs , thanks for the review!

**Comment by Andersson007** [comment]
@kustodian , hi, if you are interested in this functionality, would be better if you look at it.
Seems quite useful for me and my production.
The common case is just to add or remove new roles to / from other roles ("groups") like user_rw or user_ro, etc. to grant them suitable permissions.
I didn't add this options to postgresql_user or postgresql_privs because that's more atomic (like the Unix way) and simplier to operate small simple modules than big and complex.
Thank you for support!

**Comment by Andersson007** [comment]
@antoinell , could you please look at this one?

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@Andersson007 @tcraxs Thank you for your continued great work. 

Merged into `devel` for release in Ansible 2.8

**Comment by Andersson007** [comment]
thanks all !

**Pull request merged**
