### PR TITLE
Update lvol.py to better handle %PVS options when creating/resizing lvols.

### PR DESCRIPTION
**Pull request by balonik**
##### SUMMARY
Updating lvol.py to better handle %PVS options when creating/resizing lvols.

- Adds idempotency when the module is called N+ times and %PVS is used in `size`.
- Making the module inline with LVM2 man pages (lvcreate/lvextend), specifically with the description of `-l|--extents` option and sentence 'The suffix %VG denotes the total size of the VG, the suffix %FREE the remaining free space in the VG, and the suffix %PVS the free space in the specified PVs'.
- This update makes `pvs` option mandatory when %PVS is used in `size`, because it calculates requested size by adding size of specified PVS in `pvs` (to be inline with the above point).
- Fixing errors like `"msg": "Unable to resize lv_var_cache_pulp to 100%PVS", "rc": 5)` when module is called N+ times, because it calculated size of VG and not only subset of PVS.

##### ISSUE TYPE

- Feature Pull Request
- Bugfix Pull Request

##### COMPONENT NAME

lvol

##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### ADDITIONAL INFORMATION

```
Before applied changes same task 2 times:
- lvol: lv=lv_var_cache_pulp size=100%PVS pvs=/dev/sdc shrink=no state=present vg=vg_pulp
- lvol: lv=lv_var_cache_pulp size=100%PVS pvs=/dev/sdc shrink=no state=present vg=vg_pulp

will result in:
TASK [create_lvm : lvol] *****************************************************************************
ok: [server] => (item={'key': u'lv_var_cache_pulp', 'value': {u'path': u'/var/cache/pulp', u'pvs': u'/dev/sdc', u'mount': True, u'vg_name': u'vg_pulp', u'size': u'100%PVS'}})
TASK [create_lvm : lvol] *****************************************************************************
failed: [server] (item={'key': u'lv_var_cache_pulp', 'value': {u'path': u'/var/cache/pulp', u'pvs': u'/dev/sdc', u'mount': True, u'vg_name': u'vg_pulp', u'size': u'100%PVS'}}) => {"changed": false, "err": "  WARNING: No free extents on physical volume \"/dev/sdc\".\n  No specified PVs have space available.\n", "failed": true, "item": {"key": "lv_var_cache_pulp", "value": {"mount": true, "path": "/var/cache/pulp", "pvs": "/dev/sdc", "size": "100%PVS", "vg_name": "vg_pulp"}}, "msg": "Unable to resize lv_var_cache_pulp to 100%PVS", "rc": 5}
```

### CODE REVIEW

**Review by pdellaert — CHANGES_REQUESTED** [review]
Please rebase your branch to the latest devel release your PR removes a bunch of changes in the `vmware_guest` module

**Comment by pdellaert** [comment]
needs_rebase

**Comment by balonik** [comment]
oh my, I did forget to switch branch ...

**Comment by pdellaert** [comment]
Just wondering why you are making changes on `vmware_guest`, while this PR is about a totally different module?

If you want to make changes to a VMware module, please do so in a different branch and do a PR for that and keep them split, otherwise, there will be a lot of confusion

**Comment by balonik** [comment]
@pdellaert I know, sorry, Lost track of what branch I have locally.
Please close this PR, I'll start a new one properly. Thanks!

**Pull request closed without merging**
