### PR TITLE
iptables lock issue

### PR DESCRIPTION
**Pull request by akamac**
##### SUMMARY
When adding multiple rules in a loop it is possible to get lock error.
-w switch fixes this:

`--wait        -w [seconds]    wait for the xtables lock`

##### ISSUE TYPE

 - Bugfix Pull Request
##### COMPONENT NAME
iptables module
##### ANSIBLE VERSION
`ansible 2.6.0 (fix c1aac04495)`
##### ADDITIONAL INFORMATION
Added -w as default parameter.

### CODE REVIEW

**Comment by sebastiendarocha** [comment]
Actually, older versions of iptables are incompatible with this option. I think Debian 7 is in this case.

I agree with you, this option important. Maybe we could check the version of iptables, or try without "-w" if  the command fails ?

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/60448/3/tests

**Comment by akamac** [comment]
@mattclay Seems to be unit tests should be fixed to reflect the new `-w` switch.

**Comment by mattclay** [comment]
@akamac Yes, the unit tests will need to be updated as part of this PR.

**Comment by bcoca** [comment]
consider making this a module option, I would not accept  it in it's current state as it is both backwards incompatible with older iptables and changes the default behaviour of the module.

needs_info

**Comment by Akasurde** [comment]
Closing in favor of https://github.com/ansible/ansible/pull/47877

**Pull request closed without merging**
