### PR TITLE
Cache plugin instances so they can be reused

### PR DESCRIPTION
**Pull request by dhozac**
This primarily facilitates e.g. callback plugins logging to databases or other cases where you do some one-time-setup.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Just skimming so haven't tried to read this further, but is the intent of this to cache the module or the class instance?

It seems we wouldn't want to cache the class instance, ex:

https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/local.py

Where it holds on to a instance of Runner, etc.

**Comment by dhozac** [comment]
Modules were already being cached. This indeed is an instance cache. However, the key into the cache includes all the initialization parameters, so different runners will get different instances.

**Comment by mpdehaan** [comment]
I am a bit concerned about the weight of a runner instance over a large
playbook with a large number of forks.

What if we let each module optionally feature a "plugin_cache_key"
function, and if present, that returns the key for cache purposes.

Then the connection plugins would choose to not define this function.

sidenote -- Due to the way multiprocessing is used a plugin accessing the
database is going to open (N forks) levels of connections, but I think
that's ok

**Comment by dhozac** [comment]
It's repr'd, so it's just the string `<ansible.runner.Runner object at 0xXXXX>`.

**Comment by mpdehaan** [comment]
Right, but what's the string?  :)

**Comment by mpdehaan** [comment]
From discussion on IRC I really don't want to cache multiple copies of Runner memory when attached to plugins, etc.

**Pull request closed without merging**
