### PR TITLE
win_tempfile: Added integration tests

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Adding integration tests for the win_tempfile module.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_tempfile

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 6a3ce18e4b) last updated 2017/05/25 20:15:42 (GMT +1000)
  config file = /mnt/c/dev/module-tester/ansible.cfg
  configured module search path = [u'/home/jordan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/dev/linux-ansible/lib/ansible
  executable location = /mnt/c/dev/linux-ansible/bin/ansible
  python version = 2.7.13 (default, Apr 13 2017, 08:16:29) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by jborean93** [comment]
@dagwieers for some reason it didn't tag this as Windows or you as a maintainer, are you able to have a look in your spare time?

**Comment by gundalow** [comment]
The bot doesn't currently inspect the test directory to work out module

**Comment by jhawkesworth** [comment]
Hmm, odd ci failure on this one.

0 <ec2-13-58-203-221.us-east-2.compute.amazonaws.com> WINRM CLOSE SHELL: 1CD446D3-591D-46BA-A31C-18387DC25DD8
2017-06-13 09:24:30 fatal: [windows-2008-R2_SP1]: FAILED! => {
2017-06-13 09:24:30     "changed": false, 
2017-06-13 09:24:30     "failed": true, 
2017-06-13 09:24:30     "msg": "Get-AnsibleParam: Argument state needs to be one of absent,directory,file,touch but was absent'."
2017-06-13 09:24:30 }
2017-06-13 09:24:30 fatal: [windows-2008-SP2]: FAILED! => {
2017-06-13 09:24:30     "changed": false, 
2017-06-13 09:24:30     "failed": true, 
2017-06-13 09:24:30     "msg": "Get-AnsibleParam: Argument state needs to be one of absent,directory,file,touch but was absent'."
2017-06-13 09:24:30 }

Not sure why it would only occur on 2008s.  Is there a way they could be running different versions of powershell.ps1?

**Comment by jborean93** [comment]
This looked like a failure with the CI side to me, didn't have time last night to look into it more but it definitely works locally for me. Was going to close and reopen to test it again.

Aha found the error, was a stray `'` at the end of absent. No idea why only 2008 was affected and why it was working locally.

**Comment by jhawkesworth** [comment]
Thanks for fixing up.

ci is happy and this PR only adds tests, so merging.

**Pull request merged**
