### PR TITLE
AWS parameter cleanup/standardization

### PR DESCRIPTION
**Pull request by bpennypacker**
This standardizes the implementation, documentation, etc. of aws_secret_key, aws_access_key, region, ec2_url, etc. parameters.  

This pull request replaces https://github.com/ansible/ansible/pull/3739.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for the cleanup @bpennypacker 

@lwade can you help take a look at the above and see if you are ok with it from Eucalytpus purposes and other general things?

Thanks!

**Comment by jimi-c** [comment]
@bpennypacker looks like you'll need to rebase this, and you also have a merge commit in the above.

**Comment by lwade** [comment]
This looks good.  Minor note on the S3 module, missing a documentation aliases line for the aws_secret_key:

```
   aws_access_key:
    description:
      - AWS access key. If not set then the value of the AWS_ACCESS_KEY environment variable is used.
    required: false
    default: null
```

**Comment by bpennypacker** [comment]
Rebased these commits to https://github.com/ansible/ansible/pull/3832

**Pull request closed without merging**
