### PR TITLE
Citrix NetScaler module

### PR DESCRIPTION
**Pull request by dominis**
This module provides basic access to the netscaler's REST API. You can enable/disable services/servers easily. We're using it in our rolling deploy playbooks.

### CODE REVIEW

**Comment by dhozac** [comment]
Interesting. Is there a reason the uri module doesn't work for you?

**Comment by mpdehaan** [comment]
@dominis -- fantastic, thanks you!   Will be merged shortly.

@dhozac -- the URL module is a non-abstracted interface, very low level, it's a hammer, this is a scalpel.   People want to work in much higher level abstractions, and I want that too :)   Playbooks should be readable, and stuff like this is absolutely amazing to have in them, to just see "that's my load balancer" versus "I must properly construct this packet".

**Comment by dominis** [comment]
@mpdehaan thanks

@dhozac Is there any reason we need any modules apart from the shell one? The current version is just a basic wrapper I intend to extend it with features like pre and post validation, connection counting, warmup support, etc.

**Comment by mpdehaan** [comment]
Hey Nandor, can you shoot me your email address?  Had a great conversation
with someone yesterday about this and want to fill you in.

michael@ansibleworks.com

**Comment by mpdehaan** [comment]
Merged, thank you!

**Pull request merged**
