### PR TITLE
Remove ansible-test --tox delegation option.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Remove ansible-test --tox delegation option.

Use the --venv option instead.

This option was only available when running from source to test the ansible/ansible repository.

This will have no effect on testing collections or running from an installed version of Ansible.

Also update docs to reference the --venv option instead of the --tox option.

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

ansible-test

### CODE REVIEW

**Review by gundalow — APPROVED** [review]
Docs changes look good.
Not sure if you want any further review, feel free to merge if you are happy.

**Review by samccann — APPROVED** [review]
Docs portion lgtm

**Comment by chillancezen** [comment]
hi matt, 
seems the test does not work with python 2.7, could you help to have a look?

```
#source  hacking/env-setup
#ansible-test units --python 2.7  --venv
ERROR: No usable virtual environment support found.
```

thanks,
Link

**Comment by mattclay** [comment]
@chillancezen Can you open an issue and provide additional details on your environment so I can try to reproduce what you're seeing? It would be helpful to know which distro you're testing on, which SHA you're running from and the full version of the `python` you're using to run ansible-test. Also, run ansible-test with the `-v` option and include that output in the issue.

**Pull request merged**
