### PR TITLE
Fix terminal prompt re in ios and iosxr to match newline

### PR DESCRIPTION
**Pull request by bdowling**
##### SUMMARY

The regex in a number of network cli terminal modules is relatively weak in how few characters it needs to match, which sometimes causes it to detect prompts where it shouldn't, in descriptions, in show output, etc.  It is further weakened however because it **optionally** matches the start of the line (by `[\r\n]?`) which of course makes it a lot easier to find the rest of the simple pattern in other places.

This PR fixes that for ios and iosxr.  You may wish to fix this on other modules as well, but as I do not have those device types I did not make the change as I cannot test.
```
lib/ansible/plugins/terminal/aireos.py:    re.compile(br"[\r\n]?[\w]*\(.+\)?[>#\$](?:\s*)$"),
lib/ansible/plugins/terminal/aruba.py:     re.compile(br"[\r\n]?[\w]*\(.+\) ?#(?:\s*)$"),
lib/ansible/plugins/terminal/bigip.py:     re.compile(br"[\r\n]?(?:\([^\)]+\)){,5}(?:>|#) ?$"),
lib/ansible/plugins/terminal/bigip.py:     re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#) ?$"),
lib/ansible/plugins/terminal/dellos10.py:  re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:#) ?$"),
lib/ansible/plugins/terminal/dellos6.py:   re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#) ?$"),
lib/ansible/plugins/terminal/dellos9.py:   re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#) ?$"),
lib/ansible/plugins/terminal/enos.py:      re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#) ?$"),
lib/ansible/plugins/terminal/eos.py:       re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#) ?$"),
lib/ansible/plugins/terminal/junos.py:     re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#) ?$|%"),
lib/ansible/plugins/terminal/sros.py:      re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#|\$) ?$"),
lib/ansible/plugins/terminal/vyos.py:      re.compile(br"[\r\n]?[\w+\-\.:\/\[\]]+(?:\([^\)]+\)){,3}(?:>|#) ?$"),
```
* which of these are not like the others ? ;) ... I know DRY humor *

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

network_cli
ios
iosxr

##### ANSIBLE VERSION

```
ansible 2.5.0 (fix_ios_re 228fcaac6d) last updated 2018/01/08 17:07:04 (GMT +000)
```

### CODE REVIEW

**Comment by bdowling** [comment]
Oh, also, I removed the [user@host] shell style prompt regex from here, I've never known a network device to provide such a prompt. :)

**Comment by bdowling** [comment]
All of these other places with `[\r\n]?` occurs may be loosely coupled to this issue as well..  The password prompts in particular should be tightly matched to a newline, ios was fixed in #34723 

```
lib/ansible/plugins/terminal/enos.py:                       cmd[u'prompt'] = to_text(r"[\r\n]?password: $",
lib/ansible/plugins/terminal/eos.py:                        cmd[u'prompt'] = to_text(r"[\r\n]?password: $", errors='surrogate_or_strict')   
lib/ansible/plugins/terminal/dellos10.py:                   cmd[u'prompt'] = to_text(r"[\r\n]?password: $", errors='surrogate_or_strict')
lib/ansible/plugins/terminal/asa.py:                        cmd[u'prompt'] = to_text(r"[\r\n]?password: $", errors='surrogate_or_strict')
lib/ansible/plugins/terminal/ironware.py:                   cmd[u'prompt'] = to_text(r"[\r\n]?password: ?$", errors='surrogate_or_strict')
lib/ansible/plugins/terminal/dellos9.py:                    cmd[u'prompt'] = to_text(r"[\r\n]?password: $", errors='surrogate_or_strict')
lib/ansible/plugins/terminal/mlnxos.py:                     cmd[u'prompt'] = to_text(r"[\r\n]?password: $",
lib/ansible/plugins/terminal/dellos6.py:                    cmd[u'prompt'] = to_text(r"[\r\n]?password:$", errors='surrogate_or_strict')
lib/ansible/module_utils/network/dellos9/dellos9.py:        r"[\r\n]?\[confirm yes/no\]:\s?$",
lib/ansible/module_utils/network/dellos9/dellos9.py:        r"[\r\n]?\[y/n\]:\s?$",
lib/ansible/module_utils/network/dellos9/dellos9.py:        r"[\r\n]?\[yes/no\]:\s?$"
lib/ansible/module_utils/network/dellos6/dellos6.py:        r"[\r\n]?\[confirm yes/no\]:\s?$",
lib/ansible/module_utils/network/dellos6/dellos6.py:        r"[\r\n]?\[y/n\]:\s?$",
lib/ansible/module_utils/network/dellos6/dellos6.py:        r"[\r\n]?\[yes/no\]:\s?$"
lib/ansible/module_utils/network/dellos10/dellos10.py:      r"[\r\n]?\[confirm yes/no\]:\s?$",
lib/ansible/module_utils/network/dellos10/dellos10.py:      r"[\r\n]?\[y/n\]:\s?$",
lib/ansible/module_utils/network/dellos10/dellos10.py:      r"[\r\n]?\[yes/no\]:\s?$"
```

**Comment by gundalow** [comment]
The `[user@host]` shell style prompt regex were added by @privateip when the files were originally created, so I'd like to check with him

**Comment by privateip** [comment]
For the referenced platforms this change is fine imho.  There are other platforms that support [user@host] (namely Arista if you drop into bash) that the regex was built for.

**Review by privateip — APPROVED** [review]

**Comment by ganeshrn** [comment]
@bdowling Thank you.

**Pull request merged**
