### PR TITLE
Gce fixes

### PR DESCRIPTION
**Pull request by fcuny**
A bunch of improvement to the GCE module.

### CODE REVIEW

**Comment by jctanner** [comment]
@erjohnso any chance you could review this PR?

@franckcuny can you squash all the commits down to one?

**Comment by erjohnso** [comment]
@jctanner - Ack, I can review.  I'll get to this today sometime.

**Comment by fcuny** [comment]
@jctanner I can, before merging. I can also do it before if it's easier for Eric to review.

@erjohnso to give you some context, I wanted to simplify the process of using auth. keys, where the credentials can be passed to the module, like for the ec2 module. Having a secret.py file in the PYTHONPATH was kind of annoying for my use case.

And I'm more than happy to rework the change if needed.

Thanks!

**Comment by erjohnso** [comment]
@franckcuny - squashing now would be great and will make it easier to review/test.

And, THANK YOU!  This is long overdue and, while it was quick/easy for initial development, has been a big pain for real world use.

**Pull request closed without merging**
