### PR TITLE
Updates intro to dynamic inventory page

### PR DESCRIPTION
**Pull request by andreamtp**
##### SUMMARY
Included Foreman to the list of the inventory script 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
intro_dynamic_inventory

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

### CODE REVIEW

**Comment by acozine** [comment]
Thanks @andreamtp for this update. It looks like the list of inventory scripts has quite a few other omissions, and the headings on this page don't match our heading guidelines (see https://github.com/ansible/ansible/issues/35520 for more info and other PRs that fix header syntax). Do you want to take on a larger fix for this page?

**Comment by bcoca** [comment]
why not change the list to a url to the repo folder?

**Comment by acozine** [comment]
@bcoca I like that idea

**Review by s-hertel — APPROVED** [review]
Looks good

**Review by bcoca — APPROVED** [review]

**Review by gundalow — APPROVED** [review]

**Pull request merged**
