### PR TITLE
Added 'validate' feature to copy and template modules,

### PR DESCRIPTION
**Pull request by bcoca**
Optionally makes copy or template fail if validate fails

This PR covers previous #2512 and #2513

### CODE REVIEW

**Comment by mpdehaan** [comment]
So I see the example added to copy (well, spelling error, but anyway) and the code added to copy.  

Where is the code needed for template?

**Comment by bcoca** [comment]
IIRC (my memory doesn't go back well over 2 weeks) template just lets copy
take care of the actual implementation, it is done before copying the file
into place.

It needs to be verified on the target server as ansible 'master' might not
have the software for verification installed (i.e. nginx), so the file
always gets copied to the target.

**Comment by mpdehaan** [comment]
Correct.    Makes sense, thanks!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
