### PR TITLE
archive: Exclude explicit paths from file walk, return 'excluded' list

### LINKED ISSUE #34316: archive module 'exclude_path' documentation is very misleading
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
archive

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /Users/rsteinfeldt/Documents/discovery-ansible/ansible.cfg
  configured module search path = [u'/Users/rsteinfeldt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rsteinfeldt/Documents/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/rsteinfeldt/Documents/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### OS / ENVIRONMENT
OS X 10.12.x

##### STEPS TO REPRODUCE
Suppose I have a directory structure that looks like this, and the following playbook:
```
/tmp
/tmp/foo
/tmp/bar.txt
/tmp/dir/
/tmp/dir/stuff_in_dir.txt

```yaml
- name: Create archive
  archive:
    path:
        - /tmp
    dest: /myarchive.tar.gz
    exclude_path:
        - /tmp/bar.txt
```

##### EXPECTED RESULTS
I would expect bar.txt to be excluded from the created archive, as per http://docs.ansible.com/ansible/latest/archive_module.html : "Remote absolute path, glob, or list of paths or globs for the file or files to exclude from the archive"

##### ACTUAL RESULTS
bar.txt is included in the archive anyway. From the testing I've done, it appears that the ONLY thing ```exclude_path``` entries do is to explicitly remove-after-the-fact top level listings that were declared with wildcards in ```path```.

So I can do this:

```yaml
- name: Create archive
  archive:
    path:
        - /tmp/*
    dest: /myarchive.tar.gz
    exclude_path:
        - /tmp/bar.txt
```

NOW bar.txt isn't included in the archive I create, but its top level is not /tmp/*, it simply is 'foo', 'bar.txt', 'dir/', etc.

The way the documentation is written for the archive module, it's very easy for someone to assume that exclude_paths works the way ```tar cfvz --exclude tmp/bar.txt /tmp``` would, because it's never explained that ```exclude_path``` only operates against the list explicitly provided in ```path```. What it doesn't say is the bigger problem over what it *does* say: I'd suggest wording more like this.

exclude_path (added in 2.4): One remote absolute path or glob; or a list of absolute paths or globs, to exclude from adding to the archive, tested only against the list expanded in the ```path``` variable. File or directory names which do not appear in the list or expanded globs from ```path``` will have no effect.

### PR DESCRIPTION
**Pull request by bendoh**
##### SUMMARY
Fixes #34316 

Previously, only files which were specified for exclusion would actually be excluded if they were found to match a glob of files to _include_ in the archive; If the files specified for exclusion were  within the tree of a _directory_ that was specified for inclusion in the archive, they would be incorrectly included.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
archive

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = None
  configured module search path = [u'/Users/bdoherty/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /Users/bdoherty/vc/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### CODE REVIEW

**Comment by kimegede** [comment]
This seems more likely to be what I would expect. Will continue using a _raw_ `command`.

**Comment by bendoh** [comment]
!needs_revision ready_for_review

**Comment by epu** [comment]
Hi, I noticed this says checks have passed. What is required to merge?

**Comment by lexpierce** [comment]
Can this get attention? It is a roadblock for a few of our playbooks being truly idempotent.

**Comment by bendoh** [comment]
Yes, I'd like to get this through, too. I've rebased it and the checks pass.

ready_for_review

**Comment by danihodovic** [comment]
Any update on this?

**Comment by gundalow** [comment]
If people could test this and include some sample tasks of how they tested that will give us the confidence to merge.

**Pull request closed without merging**
