### PR TITLE
FortiManager Web Application Firewall Security Profile

### PR DESCRIPTION
**Pull request by ftntcorecse**
##### SUMMARY
This module allows users to manage web application firewall security profiles on a FortiManager

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
fmgr_secprof_waf.py

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cse/PycharmProjects/JPMC_FOS/ansible/lib/ansible/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
``

##### ADDITIONAL INFORMATION
<!--- Include additional information to help people understand the change here -->
<!--- A step-by-step reproduction of the problem is helpful if there is no related issue -->

<!--- Paste verbatim command output below, e.g. before and after your change -->
```paste below

```

### CODE REVIEW

**Comment by mattclay** [comment]
Closing and re-opening PR to try resolving CI issues.

**Comment by mattclay** [comment]
@ftntcorecse CI is still failing. Can you push a new commit or close this PR and open a new one?

**Comment by Ghilli3** [comment]
Hi All, I will close this PR and re-submit a new PR

**Comment by ftntcorecse** [comment]
Closing PR and re-submitting code

**Pull request closed without merging**
