### PR TITLE
postgresql_merge: New module to merge database content

### PR DESCRIPTION
**Pull request by tdtrask**
##### SUMMARY
I am using Ansible to manage VoIP routers running Kamailio, where the dialplan configuration is maintained in a Postgresql database. I did not want to use shell scripts to manage the database content when I could create an Ansible module instead.

The postgresql_merge module takes database content as list of database entries in Values expression format (see https://www.postgresql.org/docs/current/static/queries-values.html) and ensures that the content of the database matches. (I'm actually using a Jinja2 template for the database content) I modeled the module functionality after the SQL MERGE / UPSERT statement, which unfortunately is not implemented for Postgresql. For Postgresql version 9.5 or newer I use the INSERT ON CONFLICT method and for older versions of Postgresql I update entries in a loop. To ensure correctness, I lock the table - I realize this could kill performance on a table that has lots of updates, but it should not affect us because those types of tables are not good candidates for being managed by Ansible. In order to determine which entries match which rows for updating, the module must know which fields can be used to identify a row. This info can be passed in as a list of fields or the module will attempt to determine the primary key or single unique constraint. I also added an option to delete any non-matching rows from the table. This is not a standard feature of SQL MERGE, but is necessary for idempotency. The other options are standard for specifying the database and table.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
postgresql_merge

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION
The first entry must contain the column names. The second entry must contain any necessary type casts to specify the column type. The example in the code demonstrates both of these requirements. The date_prod column requires a type cast to specify that it is a date and not a normal text string:
```
    entries:
        - "code,title,did,date_prod,kind"
        - "'UA502','Bananas',105,'1971-07-13'::date,'Comedy'"
```
Here is how to use the module with a .csv file and Jinja2:
```
      entries: "{{ lookup('template', 'entries.csv') | regex_findall(\"(?:'[^']*'|.)+\")}}"
```

### CODE REVIEW

**Comment by Andersson007** [comment]
@tdtrask hello, thank you for this PR.
However, I'm not sure that it's useful in this implementation.

In general, the idea is good but I suggest you to implement something like postgresql_copy module
that will be used for COPY FROM / COPY TO command (and you can add 'entries' parameter there to upload entries from a playbook directly as a addition possibility).

There are a lot of parameters that will be realized like COPY ... FROM '...' (format csv, delimiter ',', NULL 'NULL') etc.).

So, @gundalow or @dagwieers , IMO, **this PR should be closed**. I added the idea about postgresql_copy module to the working group (really very useful feature).

@tdtrask you can inform us if you want to implement it by message here https://github.com/ansible/community/issues/435.
We can help you by advise, if needed. Thank you! (if you really want to do it, don't wait while anybody else will be first)

**Comment by dagwieers** [comment]
Closing this issue as requested. Feel free to add comments with feedback or clarifications.

**Comment by tdtrask** [comment]
@Andersson007 I would like to point out that MERGE and COPY are different features. I agree that a full implementation of COPY would be very useful, but it does not cover the MERGE functionality. According to the Postgresql documentation: "COPY FROM copies data from a file to a table (appending the data to whatever is in the table already)." So, COPY would allow for appending data only. The MERGE command, on the other hand, can INSERT rows plus DELETE and UPDATE existing rows.

**Comment by Andersson007** [comment]
@tdtrask , could you give me a reference to the current official documentation about this feature, please? I can't find something modern.

**Pull request closed without merging**
