### PR TITLE
Add server mode

### PR DESCRIPTION
**Pull request by skorokithakis**
Thus is a preliminary commit, for review, of an implementation of server mode. This spawns an HTTP server and runs the playbook whenever a specified URL is hit.

Please don't merge yet, there's some cleanup that needs doing, as well as the addition of a separate thread. Please do provide feedback, though.

### CODE REVIEW

**Comment by skorokithakis** [comment]
This should be good to merge now.

**Comment by skorokithakis** [comment]
Bump?

**Comment by skorokithakis** [comment]
I've been using this on production and it works well, by the way.

**Comment by colthreepv** [comment]
ansible devs does not seem interested in that or the issue, but... +1 :+1:

**Comment by skorokithakis** [comment]
That's too bad, it's been a lifesaver for me. Literally every source code tool has webhooks, and this stops Ansible from polling all day.

**Comment by jimi-c** [comment]
Hi! Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program. Without trying to be overly confrontational, our primary reason for this is the lack of security in this mode of operation. Since this would most likely be running as root, or as a user with privilege escalation capability for most users, the potential for abuse is way too high. Beyond that, as you note it is quite easy to add in the capability to execute a hook action with source control, which could be purposed to run Ansible from the system hosting the source code repository. We believe this would be a better solution, which would continue to leverage the security of the transport modes we use in Ansible today.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by skorokithakis** [comment]
You are, indeed, correct. I've spend a few minutes refactoring the code into its own package, which I've called "Captain Webhook":

https://pypi.python.org/pypi/captainwebhook

Instructions are:

```
pip install captainwebhook
cptwebhook -k SomeLongRandomKey "ansible-pull yourrepo"
```

And it does pretty much exactly the same thing as this PR, only it can be generalized to any task.

**Comment by bcoca** [comment]
i was using tcpserver to do the same thing (part of ucspi)

## 

Brian Coca

**Comment by skorokithakis** [comment]
@bcoca, that definitely works, but it runs the program on any connection, so it doesn't have authentication, or returning a valid HTTP response, or not running the command while the previous one is still running (unless I'm mistaken).

**Comment by bcoca** [comment]
all that can be easily layered on top, i did not use http but a simple
key/value protocol on the ucscpi-ssl version, it is normally a lot less
overhead than http.

## 

Brian Coca

**Pull request closed without merging**
