### PR TITLE
Add an URI splitting filters

### PR DESCRIPTION
**Pull request by ilpianista**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
uri_filter

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### SUMMARY
Adds an URI filter useful to fetch hostname, path, port or scheme from an URI.

### CODE REVIEW

**Comment by jctanner** [comment]
This is just my opinion, but I think the filters should be prefixed with something to imply they are for URIs only. 

For example ...

uri_hostname
uri_path
uri_port
uri_scheme

**Comment by samdoran** [comment]
Please refactor this to behave more like the [`ipaddr`](http://docs.ansible.com/ansible/latest/playbooks_filters.html#ip-address-filter) filter to accept parameters rather than having several individual filters. 

Here's an example of how the `ipaddr` filter accepts parameters.

```
{{ '192.0.2.1/24' | ipaddr('address') }}
```

You can also look at the `ipaddr` filter code [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/ipaddr.py)

**Review by dharmabumstead — APPROVED** [review]
Doc update OK with a minor edit.

**Comment by abadger** [comment]
+1 to merge

**Comment by samdoran** [comment]
I came up with a different way of doing this. Will submit a new PR and close this one in the near future. Please don't merge this.

**Comment by samdoran** [comment]
Superseded by #28537

**Pull request closed without merging**
