### PR TITLE
Clean up OpenStack inventory to use a cleaner interface

### PR DESCRIPTION
**Pull request by emonty**
We introduced a cleaner interface point in shade, so that group logic can live in ansible (since it's ansible specific) and metadata munging can live in and be functionally tested in shade. Consume it.

### CODE REVIEW

**Comment by emonty** [comment]
This depends on https://review.openstack.org/#/c/175891/ being merged and released. Will ping when it is.

**Comment by bcoca** [comment]
is this not backwards compatible?

**Comment by emonty** [comment]
@bcoca it should be backwards compatible - this is mostly shifting some code reuse around. However, i just found a regression, so let me address that real quick before we merge it.

**Comment by emonty** [comment]
@bcoca I'm going to come back to this and do the filtering we talked about. I can't set labels in this repo, but consider this "needs_revision"

**Comment by emonty** [comment]
This should work now. I know the current one is used in Tower - we should get the Tower folks to make sure this still works for them. I'd love to get this in before 2.0 releases. @bcoca @gregdek @robynbergeron

**Pull request merged**
