### PR TITLE
crypto: Fix known issues in modules

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This fixes a few issues reported by 'validate-modules'.

This PR fixes:
- Using snail_title names in arg_spec
- Add parameter types
- Split up descriptions over multiple items

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
openssl crypto modules

### CODE REVIEW

**Review by thomwiggers — APPROVED** [review]
LGTM

**Comment by MarkusTeufelberger** [comment]
Great finds, thanks! :-)

**Comment by thomwiggers** [comment]
LGTM 

(because new commit)

**Comment by MarkusTeufelberger** [comment]
shipit

**Pull request merged**
