### PR TITLE
postgresql: remove depricated ensure_libs function

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Removed ensure_libs function.

This function is used by one module:
1. It has been changed in postgresql_db to ensure_required_libs, that's used by default in other modules by connect_to_db function, and removed from there
2. Also removed from module_utils/postgres.py
3. The test file for this function has been removed too

+label: postgresql
+label: database

##### ISSUE TYPE

- Feature Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
related to [#55799](https://github.com/ansible/ansible/pull/55799) and [#56381](https://github.com/ansible/ansible/pull/56381)

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
@andytom , @tcraxs , let's remove ensure_libs and related code at all :)

**Comment by andytom** [comment]
LGTM

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko could you look at this short patch, please

**Comment by Andersson007** [comment]
@chamini2 , hey, could you please look at this patch?

**Review by chamini2 — APPROVED** [review]

**Comment by chamini2** [comment]
LGTM

**Comment by Andersson007** [comment]
@chamini2 , thank you for reviewing!

**Comment by Andersson007** [comment]
Thanks all!

**Pull request merged**
