### PR TITLE
Use proper pseudo-tty's instead of pipes when using subprocess

### LINKED ISSUE #1662: Ansible SSH output gives: tcgetattr: Invalid argument
When using the raw module, and even in some cases with the command module we get output that starts with `tcgetattr: Invalid argument`.

I can reproduce this out put by doing something like: `ssh localhost ssh -tt -q localhost date` and this error is related to the pseudo-terminal we requested.

So I was wondering why we request a pseudo-terminal since this is not an interactive session.

If pseudo-terminals however are needed, it somehow seems that we request a pseudo-terminal even when stdin is not in fact a terminal: `ssh -tt -q localhost date < <(echo blah)`

### PR DESCRIPTION
**Pull request by dagwieers**
This change avoids the "tcgetattr: Invalid argument" error by making sure the ssh we start does have a proper pseudo-tty.

We could also check whether our current terminal is a proper terminal (by doing a tcgetattr ourselves) but I don't think this adds anything.

This closes #1662 (if all use-cases have been tested: sudo, passwd)

### CODE REVIEW

**Comment by dagwieers** [comment]
I tested the fix now, using sudo and with asking password on the command line and both worked fine with the fix.

You can test yourself (before and after) by reproducing it using a double ssh:

`ssh localhost ssh -tt localhost ansible-playbook -v -c ssh -l system1,system2 playbook.yml`

Notice that the second ssh _will_ show you the tcgetattr error, but inside Ansible no such error appears when using the fix.

**Comment by mpdehaan** [comment]
interesting.   per the docs this appears to be Linux specific though, so I would strongly prefer something that filters out the tcgetattrs if we can do that

see top of:

http://docs.python.org/2/library/pty.html

If not, a PR that uses this method if the module is available would be ok

**Comment by dagwieers** [comment]
What's weird though is that `os.openpty()` supports _some Unix flavors_ but they hint at using the pty module for a more portable solution. BTW Why do you close the PR if we're still working to improve it. It is quite demotivating...

**Comment by mpdehaan** [comment]
I only keep pull requests open if I'm going to apply them, you shouldn't
take it personally.  In this case, the docs state the module is Linux only.

I do realize github allows updating pull requests, but this is my personal
organization system and my goal is to have as few open pull requests and
tickets as possible.

**Comment by madduck** [comment]
Just to keep things linked: #3309

**Pull request closed without merging**
