### PR TITLE
added module to enable/disable Apache2 modules

### PR DESCRIPTION
**Pull request by berendt**
This module uses a2enmod or a2dismod to enable or disable
Apache2 modules.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks pretty solid but I would not have this part in there twice, as this will do interesting things (remove the first one)

```
+#<<INCLUDE_ANSIBLE_MODULE_COMMON>>
```

**Comment by berendt** [comment]
Not sure why I added the line two times. Just removed the first one...

**Comment by jctanner** [comment]
@berendt can you make use of the module.get_bin_path method to make sure the commands being called exist and are properly pathed?

**Comment by mpdehaan** [comment]
Merged, thanks!

**Pull request closed without merging**
