### PR TITLE
Use v4 for airbrake deploy notices

### PR DESCRIPTION
**Pull request by phumpal**
##### SUMMARY
The Airbrake v2 deploy endpoint has been [deprecated](https://airbrake.io/docs/legacy-xml-api/#tracking-deploys).

This PR updates the `airbrake_deployment` module to be compatible w/the v4 deploy endpoint

- https://airbrake.io/docs/api/#deploys-v4
- https://airbrake.io/docs/features/deploy-tracking/

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
airbrake_deployment

##### ADDITIONAL INFORMATION
To notify Airbrake of a deploy using the v4 endpoint requires the Airbrake

- project_id
- project_key

and expects `POST` data in json format.

Examples below assume project id and key are valid.

**Before**
```
cat > test_old.yml <<EOF
- hosts: localhost

  tasks:
    - name: notify airbrake about deploy
      airbrake_deployment:
        repo: https://github.com/phumpal/ansible
        token: 'toinfinityandbeyond'
        environment: 'production'
        user: '{{ lookup("env", "DEPLOY_USER") or lookup("env", "USER") }}'
        revision: '012345'
EOF

ansible-playbook -c local test_old.yml -vvvv

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "environment": "production",
            "repo": "https://github.com/phumpal/ansible",
            "revision": "012345",
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url": "https://api.airbrake.io/deploys.txt",
            "user": "phumpal",
            "validate_certs": true
        }
    }
}
```
**After**
```
cat > test.yml <<EOF
- hosts: localhost

  tasks:
    - name: notify airbrake about deploy
      airbrake_deployment:
        repo: https://github.com/phumpal/ansible
        project_id: '123456'
        project_key: 'toinfinityandbeyond'
        environment: 'production'
        user: '{{ lookup("env", "DEPLOY_USER") or lookup("env", "USER") }}'
        revision: 'f06196ff4a'
EOF

ansible-playbook -c local test.yml -vvvv

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "environment": "production",
            "project_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "repo": "https://github.com/phumpal/ansible",
            "revision": "f06196ff4a",
            "url": "https://api.airbrake.io/api/v4/projects/",
            "user": "phumpal",
            "validate_certs": true
        }
    }
}
```

### CODE REVIEW

**Comment by phumpal** [comment]
The default value for `url` has changed. AFAICT that seems to be the test issue.

Not sure how to proceed.

**Comment by shanedroid** [comment]
thanks @phumpal am using this now monkey-patched in place to avoid the frequent errors that could often occur with relying on the older v2 version:

```
**
2020-03-27 23:29:59,428 p=58694 u=$USER n=ansible | TASK [track deployment in airbrake] ******************************************************************************************************************************************************************************************************
2020-03-27 23:29:59,428 p=58694 u=$USER n=ansible | fatal: [$HOST]: FAILED! => {
    "changed": false
}
MSG:
HTTP result code: -1 connecting to https://api.airbrake.io/deploys.txt
```

**Comment by phumpal** [comment]
Not sure who to ping to get this reviewed / assist moving it forward. Sorry to bug you @sivel

**Comment by phumpal** [comment]
> using this now monkey-patched in place to avoid the frequent errors

Thanks @shanedroid. Do you have any more info regarding the deploy failures (stack trace, wireshark, etc)? Disclosure, I work at Airbrake.

Hey @ansibot can we get someone to review?

**Comment by sivel** [comment]
This module has since been moved to https://github.com/ansible-collections/community.general

As such it would have to be migrated to be considered for merge.

**Comment by shanedroid** [comment]
@phumpal - it happened very infrequently during a deploy playbook's execution the task for notifying airbrake v2 API of the deploy would sometimes timeout with `HTTP result code: -1 connecting to https://api.airbrake.io/deploys.txt`  anytime I have attempted to get more verbose logs or debug of it happening, it works fine on subsequent attempts or when checking manually from cli, I had always chalked this up to latency/timeouts for `https://airbrake.io/deploys.txt` and started looking to see if we could use v4 instead, found your PR using that without any issues for over a week now

**Comment by phumpal** [comment]
Great, thanks for the feedback @shanedroid. 

The v2 api is very, very old and while still technically available is no longer supported. If you have any other issues please don't hesitate to reach out to our support team support@airbrake.io.

**Pull request closed without merging**
