### PR TITLE
adding module for ibm dmgr

### PR DESCRIPTION
**Pull request by tdavison784**
##### SUMMARY
This merge is for adding a module for starting and stopping ibm dmgr profile. The module supports ansible-doc and ansible dry run. ibm_manager is an idempotent module.

No fixes for this merge. This is my first merge attempt.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
ibm_manager

##### ADDITIONAL INFORMATION

This PR is  to merge in new code to the ansible project. This code is related to the IBM Websphere Application Server  (WAS) Deployment manager profile. This module will take care of starting and stopping the Dmgr profile. 

This module is one of many that will I will be attempting to merge into ansible to support full stack creation and management for IBM WAS platform.

### CODE REVIEW

**Comment by nmajin** [comment]
I think this repo was heading in a good direction with IBM WebSphere modules, might want to give this a review: https://github.com/amimof/ansible-websphere

**Comment by tdavison784** [comment]
@nmajin Thanks for the info, I have seen this repo before but at the time didn't appear to be to actively maintained. I have quite a few modules available for various IBM related tasks: https://github.com/tdavison784/ibmAnsibleModules

This is my first merge/contribution request so started with the ibm_dmgr module. Will the other existing repo have any interference with a possible merge of my available modules into ansible?

**Comment by tdavison784** [comment]
Hi Mark, thanks for the info. I can review this yes, but wondering how that
repo affects a merge with this requested module? I have five modules in
total that I am looking to get merged into ansible but this was my first
module/attempt at contributing.

Thanks!
Tom

**Comment by tdavison784** [comment]
Hi everyone,

Is there any more triage going on with this merge that I can assist with on my module end? Just want to keep this moving forward :)

**Comment by tdavison784** [comment]
@nmajin Can I do anything to keep this moving forward? What are our current hold ups?

**Comment by nmajin** [comment]
> @nmajin Can I do anything to keep this moving forward? What are our current hold ups?

I don't have the option to merge this PR in, it will need to be one of the project owners I believe.

**Comment by tdavison784** [comment]
@AlanCoding @MatrixCrawler @RickS-C137 @Slezhuk @agmezr @berendt @fleu42 @getjack @ghjm @hogarthj @inetfuture @jainnikhil30 @jhoekx @jladdjr @john-westcott-iv @jtyr @kdelee @lekum @matburt @mattupstate @n0trax @nerzhul @oboukili @ramondelafuente @robinro @rooftopcellist @ryanpetrello @samcarpentier @scottanderson42 @sermilrod @steamx @stearz @stpierre @tarka @tastychutney @wbrefvem @wwitzel3

**Comment by tdavison784** [comment]
Hey name space maintainers, any thing I can do to get this module merged into ansible-devel branch?

**Comment by tdavison784** [comment]
ready_for_review

**Comment by tdavison784** [comment]
@AlanCoding @MatrixCrawler @RickS-C137 @Slezhuk @agmezr @berendt @fleu42 @getjack @ghjm @hogarthj @inetfuture @jainnikhil30 @jhoekx @jladdjr @john-westcott-iv @jtyr @kdelee @lekum @matburt @mattupstate @n0trax @nerzhul @oboukili @ramondelafuente @robinro @rooftopcellist @ryanpetrello @samcarpentier @scottanderson42 @sermilrod @steamx @stearz @stpierre @tarka @tastychutney @wbrefvem @wwitzel3


How do we get this to move forward? A merge req should not take this long or the whole process needs a mass re-work.

**Pull request closed without merging**
