### PR TITLE
contribute docker-machine inventory

### PR DESCRIPTION
**Pull request by briceburg**
##### SUMMARY
A contributed docker-machine inventory script.  Polls available docker machines and creates Ansible inventory, including docker engine connection information.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
contrib/inventory/docker-machine.py

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /dex/home/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION
```
Example Output:
{
  "_meta": {
    "hostvars": {
      "node-a": {
        "ansible_host": "172.16.0.8",
        "ansible_port": 22,
        "ansible_private_key_file": "/home/acme/.docker/machine/machines/node-a/id_rsa",
        "ansible_user": "root",
        "docker_engine_host": "tcp://172.16.0.8:2376",
        "docker_engine_tlscacert": "/home/acme/.docker/machine/machines/node-a/ca.pem",
        "docker_engine_tlscert": "/home/acme/.docker/machine/machines/node-a/cert.pem",
        "docker_engine_tlskey": "/home/acme/.docker/machine/machines/node-a/key.pem"
      },
      "node-b": {
        "ansible_host": "172.16.0.9",
        "ansible_port": 22,
        "ansible_private_key_file": "/home/acme/.docker/machine/machines/node-b/id_rsa",
        "ansible_user": "root",
        "docker_engine_host": "tcp://172.16.0.9:2376",
        "docker_engine_tlscacert": "/home/acme/.docker/machine/machines/node-b/ca.pem",
        "docker_engine_tlscert": "/home/acme/.docker/machine/machines/node-b/cert.pem",
        "docker_engine_tlskey": "/home/acme/.docker/machine/machines/node-b/key.pem"
      }
    }
  },
  "node-a": {
    "hosts": [
      "node-a"
    ]
  },
  "node-b": {
    "hosts": [
      "node-b"
    ]
  }
}
```

### CODE REVIEW

**Comment by sivel** [comment]
This inventory does not implement `--host`, so it should be including the `_meta` key in the output.

**Comment by briceburg** [comment]
@sivel great -- thanks for looking. I'll implement and make the pep8 + python 2.6 compat fixes as well.

**Comment by briceburg** [comment]
@sivel I have updated the script to output the below. Do you recommend any changes? I'm not sure if the engine connection info should be stored under hostvars or group vars. Thanks!

```json
{
  "_meta": {
    "hostvars": {
      "node-a": {
        "ansible_host": "172.16.0.8",
        "ansible_port": 22,
        "ansible_private_key_file": "/home/acme/.docker/machine/machines/node-a/id_rsa",
        "ansible_user": "root",
        "docker_engine_host": "tcp://172.16.0.8:2376",
        "docker_engine_tlscacert": "/home/acme/.docker/machine/machines/node-a/ca.pem",
        "docker_engine_tlscert": "/home/acme/.docker/machine/machines/node-a/cert.pem",
        "docker_engine_tlskey": "/home/acme/.docker/machine/machines/node-a/key.pem"
      },
      "node-b": {
        "ansible_host": "172.16.0.9",
        "ansible_port": 22,
        "ansible_private_key_file": "/home/acme/.docker/machine/machines/node-b/id_rsa",
        "ansible_user": "root",
        "docker_engine_host": "tcp://172.16.0.9:2376",
        "docker_engine_tlscacert": "/home/acme/.docker/machine/machines/node-b/ca.pem",
        "docker_engine_tlscert": "/home/acme/.docker/machine/machines/node-b/cert.pem",
        "docker_engine_tlskey": "/home/acme/.docker/machine/machines/node-b/key.pem"
      }
    }
  },
  "node-a": {
    "hosts": [
      "node-a"
    ]
  },
  "node-b": {
    "hosts": [
      "node-b"
    ]
  }
}
```

**Comment by gundalow** [comment]
Hi,
This PR seems to have gotten stuck, so we are going to close it. We like to include community contributions, so this is a difficult call for us. Here's why we're closing this one:
* Given the discussion in https://github.com/ansible/community/issues/408#issuecomment-443874857
* It was created from an old version of the code
* We want to clear out the backlog so it's easier to find bug fixes
* There haven't been any comments or other activity in a long time

If you're the PR author, and you want to start the conversation back up, please:
* reopen the PR and
* rebase the branch

If you're a community member, and you want to see this change merged, please:
* Create a new PR and 
* Reference this author in the git commit & PR and
* Reference this PR in the new PR

If you've like to help with the Docker modules please comment on the [Docker Agenda/Task List](https://github.com/ansible/community/issues/408)


How to rebase a branch: https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html
How to communicate with the Ansible community: https://docs.ansible.com/ansible/devel/community/communication.html
How to contribute to Ansible: https://docs.ansible.com/ansible/devel/community/index.html

needs_info

**Pull request closed without merging**
