### PR TITLE
facts caching: fix missing json in jsonfile caching

### PR DESCRIPTION
**Pull request by resmo**

### CODE REVIEW

**Comment by bcoca** [comment]
json should be available from utils import, no need to do it again here

**Comment by resmo** [comment]
this is what I thought, but json.load failed without this import. weird.

**Comment by bcoca** [comment]
rechecking/retesting as I tested this when i took the json line out

**Comment by bcoca** [comment]
hmm, I cannot reproduce the error on current devel, what ansible version? OS? exact error?

**Comment by abadger** [comment]
json.load() is being used in both redis.py and jsonfile.py inside of get() so it should be throwing an error without a json import inside of those modules.  In addition to merging, I switched the preferred json implementation to simplejson because of the large speed boost and also restored the input to the redis caching.

https://github.com/ansible/ansible/commit/5ed7a55990e446b0f4a214e3e7228e3483390635

If you wanted to make use of the json module imported ansible.utils you'd have to make use of it similar to this:

``` python
from ansible.utils import json
json.load(f)
```

But it's not good style to do that unless you're making a choice of a default for your whole codebase.  If that's the intent, then we should move the import to a new file which is just used for these choices instead of the very cluttered utils and also make sure that all of our json usage is importing from the new module instead of import json directly.  These changes would make it obvious to others what we're doing and what the right choice to import from are.

**Comment by abadger** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by resmo** [comment]
@abadger thx for the explanation!

**Pull request merged**
