### PR TITLE
If host_key_checking is disabled, do not call .not_in_host_file() and code cleanup

### PR DESCRIPTION
**Pull request by laroche**

### CODE REVIEW

**Comment by laroche** [comment]
These changes:
- do not call .not_in_host_file(host) is host_key_checking is disabled
- simple code cleanup in lib/ansible/runner/connection_plugins/paramiko_ssh.py
- use the integer= param from get_config() instead of casting the return value
- use a one-line/inline implementation of mk_boolean()

best regards,

Florian La Roche

**Comment by mpdehaan** [comment]
Ok so this pull request contains different concepts in the same pull request.

The integer change above needs to be submitted separately, so it can be reviewed and merged separately.   A good way to handle this on github is to use a different branch for each topic (aka "topic branches").

There are also code style problems here that need to be fixed, "dounlocking" should be "do_unlocking", or more rightly "should_unlock".

Where you are going to iterate over your own commits and refine them, this is a good reason to commit a squashed commit of just the changes you need to make.

While I agree with the code cleanup above in not needing to lock if we know we aren't going to ask the question, it would be helpful to know if you encountered a specific problem that required this code change as it was not mentioned in the defect.  Otherwise the locking seems _mostly_ tame as SSH is going to do some minor locking around updating the host file anyway, and this puts this more in the "refactoring" category.

Let me know.  Thanks!

**Comment by laroche** [comment]
Currently if you disable host_key_checking, your known_hosts file is parsed
anyway, with the above change this is skipped completely.

best regards,

Florian La Roche

**Comment by mpdehaan** [comment]
Sorry for late response, as the above was not addressed in my previous comments for two months I am going to close this one.

I realize also we shouldn't have missed this and should have also responded already.

I'm fine with a pull request that disables _just_ this parsing in that case, but I am not fine with the other changes being intermixed and the removal of the utility function.

Given that, I'm going to close this one -- if you don't care to implement this without moving the function around, etc ("more compact code"), and feel this is still an issue that affects you, you are welcome to open a bug ticket.

In any event, sorry for the delay in the response.

Thanks!

**Pull request closed without merging**
