### PR TITLE
EXOS documentation updates

### PR DESCRIPTION
**Pull request by sb1975**
##### SUMMARY

Adds a complete step guide to using CLI on EXOS with Ansible

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by justjais** [comment]
cc. @LindsayHill

**Comment by LindsayHill** [comment]
I am -1 on this change. Docs as written won’t work for all setups (eg due to use of `venv` here). 

I also think that generic setup belongs elsewhere in the Ansible documentation. This section should be specific to the network OS, possibly with links to more generic setup info.

**Comment by LindsayHill** [comment]
Was on mobile earlier, so just to add to this:

* This is too site-specific - e.g. things like `ansible_python_interpreter = ~/ansible/venv/bin/python` are very specific to an installation with a virtualenv named `venv`, in the user's home directory. Same with inventory + ansible.cfg. To me, that is generic Ansible setup information that is customised to each site. It belongs somewhere else in the Ansible docs.
* The docs already show example `group_vars/exos.yml`, it doesn't need to be repeated.
* I think the more general tutorial-style information should be in one place, not repeated for each platform. It is covered in places like [here](https://docs.ansible.com/ansible/devel/network/getting_started/index.html). It may be that updates are needed there, if things are not clear.

For more detailed vendor-specific tutorials, it is better in vendor-maintained docs, or user-contributed blogs, etc. I think [this repo](https://github.com/extremenetworks/ansible-extreme) would be a good place for this sort of content. The repo maintainers would welcome a PR showing examples of using EXOS with Ansible. (I am one of the maintainers there)

**Review by LindsayHill — CHANGES_REQUESTED** [review]
See posted comments - I think this belongs in a different repo, e.g. github.com/Extremenetworks/ansible-extreme.

**Comment by acozine** [comment]
Thanks @sb1975 for submitting content for the Ansible documentation. I agree that this page isn't the right place for this example - I hope you'll open a fresh PR with this content on the repo @LindsayHill suggested: https://github.com/extremenetworks/ansible-extreme.

**Pull request closed without merging**
