### PR TITLE
Update na_ontap_export_policy_rule to allow multiple rules to be set at once. 

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Update na_ontap_export_policy_rule to allow multiple rules to be set at once. 
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_export_policy_rule.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]
shipit

**Review by lonico — APPROVED** [review]
shipit

**Review by resmo — APPROVED** [review]
LGTM

**Review by thedoubl3j — APPROVED** [review]
lgtm, thanks for the tests. shipit

**Comment by lonico** [comment]
close #51445

**Comment by lonico** [comment]
close #51441

**Comment by thedoubl3j** [comment]
@lonico this PR address those issues?

**Comment by lonico** [comment]
@thedoubl3j yes it does

**Pull request merged**
