### PR TITLE
Documentation typo fixes

### PR DESCRIPTION
**Pull request by AMDmi3**
Fix some typos in documentation

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged thanks. Please do use the issue template in the future, it helps ansibot add the correct labels.

**Comment by AMDmi3** [comment]
Thank you!

**Comment by abadger** [comment]
cherrypicked for 2.4.2beta3

**Comment by dharmabumstead** [comment]
Please don’t merge documentation PRs until the doc team has reviewed them. Thanks.

**Pull request merged**
