### PR TITLE
win_msi: deprecated in favour of win_package

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Deprecated win_msi in favour of win_package after recent rewrite.

##### ISSUE TYPE
 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME
win_msi

##### ANSIBLE VERSION
```
2.4
```

### CODE REVIEW

**Review by nitzmahone — APPROVED** [review]

**Comment by dagwieers** [comment]
I am not in favor of this just yet. I still had use-cases for **win_msi** that I haven't tested with the new **win_package**. I don't think we can deprecate something when the new replacement module was refactored and not widely tested. You risk telling people to move to something that isn't working for them yet.

**Comment by dagwieers** [comment]
Right, got merged while I was typing that...

**Comment by jborean93** [comment]
win_msi has been on the downhill for a while now and the unofficial statement was to avoid using it as there are a few issues there. While win_package is "new" I still think making people avoid using win_msi is a good thing to have. They should have stopped using it a few releases ago.

**Comment by dagwieers** [comment]
Except that **win_package** wasn't working a few releases ago, and we haven't been able to verify in the wild that the **win_package** version we released now actually works for these use-cases (since it was merged just yet). So users might find themselves trapped in a situation where Ansible is warning them to move away from **win_msi**, while they actually cannot at this moment.

IMO we should have waited one release with this, but ultimately it was your call :-)

**Comment by jborean93** [comment]
Bring on the RC's I say, I had it open for a few days/weeks and got as much feedback as I could. At some point we need to make a release and get people to test it outside of just a PR.

**Comment by nitzmahone** [comment]
We've been talking about deprecating `win_msi` for 3 releases now- let's just do it. If there are bugs we need to fix in win_package that could block migration, bring 'em on- we have two releases to sort them out. If there are missing features that `win_msi` has (I don't believe there are), let's talk specifics.

**Comment by dagwieers** [comment]
@jborean93 I am not against putting **win_package** into a release, to the contrary, the sooner the better.

My concern is with deprecating **win_msi** in the same move, without knowing all the details from the refactored **win_package** *(Users do not test open PRs actively, so it doesn't matter if ithe PR was open for days or weeks. If it would have been in the devel branch for weeks, that would be a whole new ball game :-))*

I don't think it is a good practice to do it like this despite our deepest desires. We'll find out soon enough though.

**Comment by dagwieers** [comment]
Ok, I somehow understood from this change that people would be getting nagged by some deprecation warning in **win_msi**. So ignore my above rants, if it's just documentation, my only concern is that we are removing **win_msi** in 2 releases and not the default 4 releases.

And most users may not have seen the documentation changes and will be confronted with the removal of win_msi when it hits v2.6 I guess. Not ideal either.

**Pull request merged**
