### PR TITLE
EC2 dynamic inventory: new downcase_facts and normalize_groups options

### PR DESCRIPTION
**Pull request by mpeters**
This adds a new `downcase_facts` option to the ec2.ini configuration for EC2 dynamic inventories (that was discussed on ansible-project mailing list). It defaults to False (the current behavior) so it has to be explicitly enabled. So old configurations without the setting should work just fine. 

It also adds a new `normalize_groups` option that will convert any hyphens into underscores to make it easier to use group names as variables.

### CODE REVIEW

**Comment by mpdehaan** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by mpeters** [comment]
I've rebased this and it should be possible to do a clean merge now.

**Comment by mpdehaan** [comment]
Please take a look at the above and see all the merge commits in the history, I think you may need to start a new branch or something.

**Comment by mpeters** [comment]
This has bad merge commits in its tree. A better branch/pr exists at https://github.com/ansible/ansible/pull/8628

**Pull request closed without merging**
