### PR TITLE
Add nsenter connection plugin

### PR DESCRIPTION
**Pull request by kvaps**
##### SUMMARY
This PR adds new nsenter connection plugin (https://github.com/kvaps/ansible-nsenter)

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
plugin

##### ADDITIONAL INFORMATION

This plugin might be useful for running playbooks natively on hosts from the docker and kubernetes containers.
Eg. you can rollout Daemonset with ansible and configure the host nodes via nsenter plugin.

Just try this:

```bash
docker run -ti --rm --pid=host --privileged kvaps/ansible-nsenter \
  ansible -m copy -a 'content="hello world!" dest=/tmp/123' node
```

```bash
cat /tmp/123
hello world!
```

### CODE REVIEW

**Comment by kvaps** [comment]
ready_for_review

**Comment by kvaps** [comment]
ready_for_review

**Comment by bmillemathias** [comment]
What's missing here to have someone review that ?

**Comment by bmillemathias** [comment]
bot_status

**Comment by Shrews** [comment]
Hi!

Thank you very much for your submission to Ansible. It sincerely means a lot to us that you've taken the time to contribute.

Per recent announcements at AnsibleFest Atlanta 2019, going forward we are no longer accepting new one off modules/plugins, or modules/plugins that create a new category.

However, we recommend looking into providing this functionality through Ansible Galaxy via Ansible Collections. You can find more information about collections at https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html.

You may want to consider proposing this plugin to the [community.general](https://github.com/ansible-collections/community.general) collection.

Thank you once again for this and your interest in Ansible!

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
