### PR TITLE
change file to better reflect its usage

### PR DESCRIPTION
**Pull request by mattyjones**
##### SUMMARY

The pagerduty module filename is changed to better reflect its usage and as a first step to aid in the organization of the pagerduty modules when new functionality is added.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

pagerduty

##### ANSIBLE VERSION

ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/matt.jones/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/matt.jones/.local/lib/python2.7/site-packages/ansible
  executable location = /home/matt.jones/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

##### ADDITIONAL INFORMATION

I have several new features to add to the pagerduty module and each is a specific filename, pagerduty_users, pagerduty_teams, etc. I would like to create a specific folder **pagerduty** nested under monitoring to store these to keep the directory structure clean. Per conversations in IRC as well as the docs this is allowed as it is only two deep from the modules directory.

### CODE REVIEW

**Comment by mattyjones** [comment]
Looking at one of the errors in the failing test:

`ERROR: lib/ansible/modules/monitoring/pagerduty_maintenance_window.py:0:0: E307 version_added should be 2.8. Currently 1.2 (75%)`

I am unsure on the policy for a rename and can't seem to find anything in the docs or in previous examples. I would think that because this is just a rename it should stay at the original version, though I do understand why this is getting picked up and failing.

`ERROR: lib/ansible/modules/monitoring/pagerduty_maintenance_window.py:0:0: E324 Value for "default" from the argument_spec ('0') for "minutes" does not match the documentation (None) (75%)`

The docs for this are on line [66](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/pagerduty.py#L66) and the dict defining it on line [227](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/pagerduty.py#L227). Unless I am missing something obvious, I can't see the issue.

`ERROR: lib/ansible/modules/monitoring/pagerduty_maintenance_window.py:0:0: E312 No RETURN provided (75%)`

I can add this in as I know it is in the spec, more curious how it has passed w/o it before and if this would be an ask.

When I have fixed these issues and any others I will squash these all down to a single commit per the documentation.

**Comment by mattyjones** [comment]
@mattclay I am lost as to why this is failing now. I tried to do a squash, not sure why this is happening. I can close this and open a new pr if needed with just a single commit.

**Comment by mattclay** [comment]
The CI failure is unrelated to this PR. I'm working on a fix.

**Comment by mattyjones** [comment]
@jborean93 What are the next steps. Should I try and get some community by-in I am unsure as the labels `core-review` and `support:core` are still on the project.

Thanks!

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
