### PR TITLE
Add several DNS-related facts by parsing /etc/resolv.conf

### PR DESCRIPTION
**Pull request by reedloden**
Parse /etc/resolv.conf for DNS-related facts such as current nameservers, domain, search path, sortlist, and any options.

### CODE REVIEW

**Comment by reedloden** [comment]
@mpdehaan I don't think this should have been closed. I'm not touching a module (just the built-in facts), and this code is still in the main 'ansible' repo.

**Comment by jimi-c** [comment]
Hi @reedloden, I'll reopen this. Thanks!

**Comment by srgvg** [comment]
+1 @jimi-c

**Comment by amenonsen** [comment]
Looks great to me, especially because it still applies. I think this should be merged.

**Comment by reedloden** [comment]
@amenonsen, would love to see this merged (I still very much want this for my own Ansible usage), so let me know if there's anything I need to do to help with that.

One question I have is whether I need to update just `lib/ansible/module_utils/facts.py` or also the old `v1/ansible/module_utils/facts.py` as well. Not sure how v1 vs. v2 is being treated.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
