### PR TITLE
Adding NetApp approvers

### PR DESCRIPTION
**Pull request by schmots1**
##### SUMMARY

Adding NetApp approvers

##### ISSUE TYPE

 - Approver pull request

##### COMPONENT NAME
BOTMETA.yml

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by maxamillion** [comment]
cc @hulquest @lmprice @broncofan @amit0701

**Comment by amit0701** [comment]
shipit

**Comment by hulquest** [comment]
shipit

**Comment by lmprice** [comment]
shipit

**Pull request merged**
