### PR TITLE
Added Ansible UTM Info Module for network interface address entities.

### PR DESCRIPTION
**Pull request by maunzCache**
##### SUMMARY
This PR will add a new utm info module which allows the management of network interface address entries of the Sophos UTM. This module integrates with the existing utm_utils .

##### ISSUE TYPE
* New Module Pull Request

##### COMPONENT NAME
* module/web_infrastructure/sophos_utm/utm_network_interface_address.py
* module/web_infrastructure/sophos_utm/utm_network_interface_address_info.py

### CODE REVIEW

**Comment by getjack** [comment]
@stearz @RickS-C137 Please help out reviewing :)

**Comment by RickS-C137** [comment]
shipit

**Comment by RickS-C137** [comment]
+1

**Comment by getjack** [comment]
> +1

Please do a proper review.

**Review by MatrixCrawler — APPROVED** [review]

**Comment by MatrixCrawler** [comment]
shipit

**Pull request merged**
