### PR TITLE
DC virtual interface - support DC gateway

### PR DESCRIPTION
**Pull request by angegar**
##### SUMMARY
The current module aws_direct_connect_virtual_interface does not currently support the
create of a virtual interace linking a direct connect gateway with a connection.

This commit add the ability to do it.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
aws_direct_connect_virtual_interface

This my firt contribution to ansible module so please be indulgent ;)

### CODE REVIEW

**Comment by mtraynham** [comment]
Any change this could be resolved and merged for 2.8?

**Comment by angegar** [comment]
Hi, sorry i was not active on this, i will try to fix it this week.

**Comment by mattclay** [comment]
bot_status

**Review by s-hertel — APPROVED** [review]
This looks good to me. Since this is a feature it should have some tests - https://github.com/ansible/community/blob/master/group-aws/integration.md#policy

Do you have a playbook you tested the feature with when developing? That could be put into the test/integration/targets directory.

**Comment by angegar** [comment]
I don't know anything for now about ansible tests, I just use this code as lib in my deployment.

- name: Create a Direct Connect Virtual interface
  aws_direct_connect_virtual_interface:
    state: present
    name: dcvi
    connection_id: "{{ dcc.connection.connection_id }}"
    direct_connect_gateway_id: "{{ dcg.results[0].direct_connect_gateway_id }}"
    public: no
    bgp_asn: 12345

**Pull request closed without merging**
