### PR TITLE
Added a use_proxy option to get_url.

### PR DESCRIPTION
**Pull request by dorfsmay**
Re-submitting with only the use_proxy option, and no proxy option, as per discussion in pull request # 2267

### CODE REVIEW

**Comment by dhozac** [comment]
Doesn't

```
- action: get_url url=http://... dest=/...
  environment:
    http_proxy: ""
```

do the same thing? That is also far more versatile as it works with all the modules that uses proxies.

**Comment by dorfsmay** [comment]
On 2013-03-02 02:36, Daniel Hokka Zakrisson wrote:

> Doesn't
> 
> |- action: get_url url=http://... dest=/...
>    environment:
>      http_proxy: ""
> |
> 
> do the same thing? That is also far more versatile as it works with all the
> modules that uses proxies.

I see get_url as ansible's own curl/wget... and as such I think it should have 
more options such as ignoring proxy, list of proxy etc... But at the very 
least, I think we should add something to get_url documentation about the fact 
that it uses <protocol>_proxy when setup in the environment, and how to change 
it. I've just noticed that this is now mentioned in the advanced playbook page 
(wow, this must have been added very recently), but somebody running into the 
issue is more likely to look at the get_url doc than the advanced page.

**Comment by mpdehaan** [comment]
We should crosslink to the environment variable documentation, yes....

**Comment by dorfsmay** [comment]
On 2013-03-02 09:41, Michael DeHaan wrote:

> We should crosslink to the environment variable documentation, yes....

So no more use_proxy option?
Somebody's adding the bit of docs, or should I?

## 

Yves.                                                  http://www.SollerS.ca/
                                  Unix/Linux and Python specialist in Calgary.
                                                        http://blog.zioup.org/

**Comment by mpdehaan** [comment]
I was fine with the use_proxy (default=yes) option if you think you need it.

You can add the doc to 'notes' to see the advanced playbooks docs on
'environment' to configure the proxy setup if not already set in your
environment.

**Comment by dorfsmay** [comment]
Added a commit to "Clarified that proxy can be changed via an variable."

**Comment by mpdehaan** [comment]
I think that should say "if C(no) it will not use a proxy" :)

**Comment by dorfsmay** [comment]
> I think that should say "if C(no) it will not use a proxy"

yes, I mean no... Anyway, fixed!

**Comment by mpdehaan** [comment]
Merged, thanks!

**Pull request merged**
