### PR TITLE
use the stat module instead of find to check file existence

### LINKED ISSUE #57825: paths for the task “check if the backup file-1 exist” (backup.yaml) should not be a file name
##### SUMMARY
The argument of **paths** in task: "check if the backup file-1 exist" should be directory name rather than a file name in backup.yaml which is located at test/integration/targets/xxx_config/tests/... 

Yaml Extraction:
```
- name: check if the backup file-1 exist
  find:
    paths: "{{ role_path }}/backup_test_dir/{{ inventory_hostname_short }}/backup.cfg"
  register: backup_file
  connection: local
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
backup.yaml in test/integration/targets/ 
!component =lib/ansible/
##### ANSIBLE VERSION

```
ansible 2.9.0.dev0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
The task should be correctly processed.

##### ACTUAL RESULTS
There is a message for the task: 
```
...was skipped as it does not seem to be a valid directory or it cannot be accessed
```

### PR DESCRIPTION
**Pull request by Quanta-Switch**
##### SUMMARY

Fixes #57825

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

backup.yaml in test/integration/targets/
!component =lib/ansible/
##### ADDITIONAL INFORMATION
N/A

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
I'm working on the junos failures at: https://github.com/ansible/ansible/pull/57966

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
we had an outage in our cloud provider, running tests again.

**Comment by pabelanger** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by pabelanger** [comment]
okay, we've landed both iosxr and junos fixes, another recheck to confirm our testing is stable.

**Comment by pabelanger** [comment]
recheck

**Comment by chiuhsiapeng** [comment]
I am trying withdraw the second commit #b56fdebcda because this is not for this PR.

**Pull request closed without merging**
