### PR TITLE
VMware: set extra configs for virtual machine

### LINKED ISSUE #32004: vmware_guest is not setting "customvalues" against vSphere 6.5
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/spollock/ansible/fs-vmw-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]


```

##### OS / ENVIRONMENT

Running local on mac OSX
Running against vSphere 6.5 and ESXi 6.5

##### SUMMARY

customvalues are not added, vSphere responds with : " A specified parameter was not correct: key"

##### STEPS TO REPRODUCE

```yaml
- name: Set a custom value
  vmware_guest:
    validate_certs: no
    hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    datacenter: "{{ vcdatacenter }}"
    cluster: "{{ vccluster }}"
    resource_pool: "k{{ vctargetkit }}"
    uuid: 422bf5cb-b3b2-69ab-4053-21bcf7390d23
    name: 1201-pollockkit
    customvalues:
      - key: remotedisplay.vnc.port
        value: "7601"
    #state: poweredoff
  delegate_to: localhost
```

##### EXPECTED RESULTS

Should have set the customvalue for remotedisplay.vnc.port

##### ACTUAL RESULTS

Nothing, error message below

Note: this can be entered manually into vSphere under advanced parameters and it works fine.

```
"msg": "Failed to set custom value for key='remotedisplay.vnc.port' and value='7601'. Error was: (vmodl.fault.InvalidArgument) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'A specified parameter was not correct: key',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   invalidProperty = u'key'\n}"
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This fixes implementation of extra config for virtual machine.

Fixes: #32004

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
rebuild_merge

**Comment by darioems** [comment]
This problem affects the ansible 2.4 of production as well. Could this PR be applied in 2.4? Tks.

**Comment by Akasurde** [comment]
cc @abadger 

re: 2.4

**Comment by abadger** [comment]
Feel free to merge to temp-staging-post-2.4.3 for inclusion in 2.4.4

**Comment by darioems** [comment]
Hello @Akasurde ... Do you to merge to  temp-staging-post-2.4.3? Tks

**Comment by Akasurde** [comment]
@darioems I backported [this](https://github.com/ansible/ansible/pull/36521) to include in 2.4.4

**Comment by aperigault** [comment]
Sorry i'm late but I don't understand why you replace CustomValue by extraConfig.
This is not the same think. This PR break usage of Custom values !!!

**Comment by Akasurde** [comment]
@aperigault I don't know what to say!!! BTW, There is a new module PR [`vmware_guest_attribute`](https://github.com/ansible/ansible/pull/38114) which achieve custom value functionality. Please provide your feedback and comments on new PR.

**Comment by aperigault** [comment]
@Akasurde Oh thank you. I know that vmware naming is a little confusing, but customvalues is really the good ansible option name to configure extra parameters ?
BTW I see use cases to use the new vmware_guest_attribute module so I will test it.

**Comment by Akasurde** [comment]
@aperigault Yes. The VMware naming is very confusing. It would be great if you could test and provide your valuable feedback on vmware_guest_attribute and vmware_guest_attribute_def modules.

**Pull request merged**
