### PR TITLE
VMware: new module: vmware_guest_customization_facts

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This module gathers facts about customization specification created
for virtual machine.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest_customization_facts.py
test/integration/targets/vmware_guest_customization_facts/aliases
test/integration/targets/vmware_guest_customization_facts/tasks/main.yml

##### ANSIBLE VERSION

```
2.6devel
```

### CODE REVIEW

**Review by pdellaert — COMMENTED** [review]
Missing Windows stuff on workspace, domain, ..., is this expected?

**Comment by Akasurde** [comment]
@pdellaert Could you please review this again ? Thanks.

**Review by pdellaert — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
rebuild_merge

**Pull request merged**
