### PR TITLE
Improve module docs return values

### LINKED ISSUE #36867: Network facts return documentation
##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
N/A
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Documentation does not explain that return values are nested under `ansible_facts`

##### STEPS TO REPRODUCE

N/A

```yaml
N/A
```

##### EXPECTED RESULTS

I expected to have to register the results and then access the key/value pairs directly under my register value.
Expected:
```yaml
- ios_facts:
    register: "facts_data"

- debug:
    var: ios_facts.ansible_net_config
```
The above debug var actually requires `ios_facts.ansible_facts.ansible_net_config`, but is also not needed as the facts module adds the key/value pairs to hostvars. The Ansible way would be to just use `ansible_net_config`.

Suggest adding documentation that explains the return values are part of `ansible_facts` and how `ansible_facts` behaves:
```
"Common return values are documented here Return Values, the following are the fields are returned as part of ansible_facts, which do not require registering returns and automatically added to hostvars:
```

Suggest updating examples to include an example of using the return data:
```
- name: GATHER CONFIG DATA
  ios_facts:
    gather_subset:
      - "config"

- name: ENSURE OUTPUT DIRECTORY EXISTS
  file:
    state: "direcotry"
    path: "./project/output/configs"

- name: WRITE BACKUP TO FILE
  copy:
        content: "{{ ansible_net_config }}"
        dest: ""./project/output/configs/{{ inventory_hostname }}.cfg"
```
##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Currently the 5 columns shown doesn't make optimal use of the screen estate, especially for facts modules with a lot of "complex"data this is a problem.

This relates to #36901 

**Before (facts module)**
screenshot from 2018-03-02 13-47-01

**After (facts module)**
screenshot from 2018-03-06 00-32-26

**Before (normal module)**
screenshot from 2018-03-02 13-50-13

**After (normal module)**
screenshot from 2018-03-02 13-49-30

Both examples look much better (actually usable) on smartphones and tablets. For normal screens the improvement is less compelling, but nevertheless more pleasing IMO

One more thing we improved for Return Values. The returned facts are now in a separate section and has a short description explaining how these values can be accessed without the need to register it explicilty

This fixes #36867

##### ISSUE TYPE
 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME
module docs

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Review by dharmabumstead — APPROVED** [review]
Looks great! Thanks @dagwieers

**Comment by dagwieers** [comment]
So with the latest updates we include **Returned Facts** in a separate section:

screenshot from 2018-03-06 00-32-26

**Comment by dagwieers** [comment]
@gundalow @dharmabumstead I think this is ready to be merged. Can you re-review ?

**Comment by dagwieers** [comment]
So is this going in v2.5 or not ?

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged to `devel` as Scott has approved .

**Pull request merged**
