### PR TITLE
Adding New Model onyx_qos for Configuring QoS on Onyx Switches

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Adding New Model onyx_qos for Configuring QoS on Onyx Switches

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/onyx/onyx_qos.py
test/units/modules/network/onyx/fixtures/show_qos_interface_ethernet.cfg
test/units/modules/network/onyx/test_onyx_qos.py

##### ADDITIONAL INFORMATION

```
ansible 2.8.0a1.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev8/lib/ansible
  executable location = /.autodirect/mtrswgwork/anasb/ansible_dev8/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

### CODE REVIEW

**Comment by anasbadaha** [comment]
Hi @samerd,

Please take a look on this PR and approve it if you don't have farther comments.

Thanks

**Review by samerd — CHANGES_REQUESTED** [review]
Thanks Anas.
excellent module.
However, I have few minor comments:
1- rewrite_dscp and rewrite_pcp, should be both disabled by default
2- regarding the "no" commands, although your commands are working, I prefer to put the no before the qos, instead before the interface
NO_REWRITE_PCP_CMD = "interface {0} {1} no qos rewrite pcp"
NO_REWRITE_DSCP_CMD = "interface {0} {1} no qos rewrite dscp"

**Comment by anasbadaha** [comment]
Hi @samerd ,

I have fixed all your comments, please approve if it's OK for you.

Thanks

**Review by samerd — APPROVED** [review]

**Comment by samerd** [comment]
@justjais 
please review and merge if OK with you

**Comment by anasbadaha** [comment]
Hi @justjais,

Can you please merge this PR if it is OK for you?

Thanks

**Review by ganeshrn — APPROVED** [review]

**Comment by ganeshrn** [comment]
rebuild_merge

**Comment by ganeshrn** [comment]
@anasbadaha The PR has merge commit. Please rebase it.

**Comment by anasbadaha** [comment]
Hi @ganeshrn

I have rebased it, please merge!

Thanks

**Comment by ganeshrn** [comment]
@anasbadaha Thank you!

**Comment by samerd** [comment]
Thanks so much @ganeshrn

**Pull request merged**
