### PR TITLE
Enable test for lookups on python 3

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

test of lookups on python 3

### CODE REVIEW

**Comment by mscherer** [comment]
The failure is the following:

```
Unexpected templating type error occurred on ({{ lookup('password', output_dir + '/lookup/password_with_salt encrypt=sha256_crypt') }}): salt must be unicode, not bytes
```

On "create a password (with salt) file" ( https://github.com/ansible/ansible/blob/devel/test/integration/targets/lookups/tasks/main.yml#L104 )

**Comment by mscherer** [comment]
So the issue is linked to https://bitbucket.org/ecollins/passlib/src/530cffc97945a940d15af42e226543ae3a018035/passlib/utils/handlers.py?at=default#handlers.py-1382 

Using to_native instead of to_bytes just seems to break something else in the test suit.

**Comment by mscherer** [comment]
So it seems that depending on the salt, it can or cannot be unicode (or bytes), since some salt have the HasSalt and some have the HasRawSalt mixin. For example, fhsp, scram, pbkdf2 would take a 'bytes' for salt, while other would take 'unicode', unless if running on python 2. 

So my understanding is that we would need to convert depending on the type of algo being used, and that's slightly annoying.

**Comment by abadger** [comment]
Does seem a little hacky but we're just working around the limitations of the library so it seems like a good fix.  Thanks!

**Pull request merged**
