### PR TITLE
add kubernetes beta resources to clustering/kubernetes module

### PR DESCRIPTION
**Pull request by ediskandarov-cur**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

kubernetes

``` yaml
- name: Create kubernetes cloud logging Daemon Set (logstash)             
  kubernetes:                                                             
    api_endpoint: 127.0.0.1:8080                                          
    insecure: yes                                                         
    inline_data: "{{ lookup('template', 'logstash-daemonset.yaml.j2' ) }}"
```
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add ability to operate on kubernetes resources from `apiVersion: extensions/v1beta1`

Before

```
TASK [kube-master/cloud-logging : Create kubernetes cloud logging Daemon Set (logstash)] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_x0OjsW/ansible_module_kubernetes.py\", line 399, in <module>\r\n    main()\r\n  File \"/tmp/ansible_x0OjsW/ansible_module_kubernetes.py\", line 373, in main\r\n    module.fail_json(\"invalid resource kind specified in the data: '%s'\" % kind)\r\nTypeError: fail_json() takes exactly 1 argument (2 given)\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

After

```
TASK [kube-master/cloud-logging : Create kubernetes cloud logging Daemon Set (logstash)] ***
ok: [localhost]
```

### CODE REVIEW

**Comment by ediskandarov-cur** [comment]
related PR https://github.com/ansible/ansible-modules-extras/pull/2762

**Review by nmec — APPROVED** [review]
Tested and confirmed working as expected. shipit.

**Comment by j4k** [comment]
:shipit: shipit.

**Comment by grumpydude** [comment]
This does appear that the follow line results in failures in certain cases:

`"horizontalpodautoscaler": "/apis/extensions/v1beta1/namespaces/{namespace}/horizontalpodautoscalers",
`

However, when updated to the correct API, then these failures go away:

`"horizontalpodautoscaler": "/apis/autoscaling/v1/namespaces/{namespace}/horizontalpodautoscalers",`

**Comment by calfonso** [comment]
@toidi we need this to get one more community reviewer to apply a 'shipit' then it'll be good to go.

**Comment by ediskandarov-cur** [comment]
@calfonso just let it rot

**Comment by erjohnso** [comment]
shipit

LGTM - sorry for the laggy response @toidi!

**Pull request merged**
