### PR TITLE
FreeIPA/RHIdM API dynamic inventory script & plugin

### PR DESCRIPTION
**Pull request by Aethylred**
A dynamic inventory script that uses the FreeIPA API with HTTPS authentication. No Kerberos required. Requires the python_freeipa module.

##### SUMMARY
Adds a dynamic inventory script that uses the FreeIPA/RHIdM API with HTTPS authentication.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Dynamic Inventory Script

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION
Requires the `python_freeipa` module.

### CODE REVIEW

**Comment by Akasurde** [comment]
@Aethylred Thanks for the PR. Any specific reason not to use existing FreeIPA dynamic inventory located [here](https://github.com/ansible/ansible/blob/devel/contrib/inventory/freeipa.py).

cc @fxfitz @flo-renaud @Nosmoht What do you think ?

needs_info

**Comment by Aethylred** [comment]
@akasurde this method doesn’t require Kerberos being preauthenicated for the user populating the inventory, it just used plain ordinary Ansible variables.

Setting up Kerberos in an Ansible AWX docker image is not fun where this solution is just code.

...and maybe I should update freeipa.py too to handle nested groups correctly and populate the hostvars...

**Comment by Akasurde** [comment]
cc @pilou-

**Comment by bcoca** [comment]
2 things:
 - we are not taking any new inventory scripts, we would prefer inventory plugins instead
 - even if we were taking new ones, instead of competing scripts we would want you to modify the existing one to allow both modes of operation instead of introducing competing one.

**Comment by Aethylred** [comment]
>we would want you to modify the existing one to allow both modes of operation instead of introducing competing one

I could do this but it will result in a script that requires a module it doesn't use for the 'other' mode.
- `freeipa.py` uses `ipalib` which requires Kerberos authentication of the user running the script to provide authentication token and point the script at the IPA server
- `freeipa-api.py` uses `python_freeipa` to use HTTPS authentication from environment variables

I could put the import statements into if blocks, but that's a thing I'd normally avoid. I am trying to make the script work with the minimum additions to your Python environment. So that lead me to a new script, rather than adapt the existing one.

> we are not taking any new inventory scripts, we would prefer inventory plugins instead

I'm working on that too, but I need to test it, which requires building Ansible, while the inventory scripts can be tested by dropping them into an Inventory Source in AWX.

**Comment by bcoca** [comment]
You can drop any new plugin into any dir and use:
```ANSIBLE_INVENTORY_PLUGINS=/mypath ansible-playbook -i ... ```

plugin paths are configurable to make it easy for you to use/develop custom ones, there are also the adjacent to play (some in role) plugins dirs and by default ` ~/.ansible/plugins/<plugin>` dirs are also available.

**Comment by Aethylred** [comment]
Thanks for that, it'd been helpful that 'How to test plugins' was part of the documentation here: https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html

**Comment by Aethylred** [comment]
Please stand by.

Just about have a combined inventory script, and I think I've figured out how to convert it into a plugin.

**Comment by Aethylred** [comment]
Now for the plugin.

**Comment by Aethylred** [comment]
Ok I think thats done. All methods should produce an identical inventory, listing groups, with child groups, and populated `hostvars` for each `host` in `_meta`

## Dynamic Inventory Script
- dynamic inventory script works when run as a user with Kerberos authentication
- dynamic inventory script works when run with:
-- correct command line arguments
-- correct environment variables set either from the command line or Ansible variables

## Inventory Plugins
- has to be whitelisted in an `ansible.cgf` somewhere
- works with an appropriate inventory YAML file
- Kerberos version requires the user/role/process to have a valid Kerberos ticket*

\* um... I don't have a sensible method for that... I suspect it's one of the reasons the original ipalib based dynamic inventory script wasn't converted into a plugin.

**Comment by Aethylred** [comment]
I suspect I'm going to have to decorate it with linter exception comments because of the conditional imports.

**Comment by Aethylred** [comment]
I'm going to wait for the tests to complete, then rebase and reduce this to two or three commits.

**Comment by Aethylred** [comment]
I'm having trouble clearing the tests because I rebased on top of devel, which was a mistake.

Trying again from https://github.com/ansible/ansible/pull/41766

**Pull request closed without merging**
