### PR TITLE
Fix for OpenBSD

### PR DESCRIPTION
**Pull request by stemid**
It's not a solution but it's a workaround for us who are trying to use ansible on OpenBSD. Nothing was being done about [this issue](https://github.com/ansible/ansible-modules-core/issues/278) so this workaround helped me at least.

### CODE REVIEW

**Comment by rvalente** [comment]
Nice!

**Comment by bcoca** [comment]
you have merge commit in your PR, you might want to fix that and push again

**Comment by stemid** [comment]
@bcoca How do I do that?

**Comment by bcoca** [comment]
use git rebase and/or cherry-pick to get a clean branch, then just force push to the shared branch the PR is based on

**Comment by stemid** [comment]
@bcoca Ok I tried following [https://robots.thoughtbot.com/keeping-a-github-fork-updated](this guide) and have now pushed it to my fork repo.

**Comment by bcoca** [comment]
so it is more messed up now than before, I just cherry picked your commit as it seems less work at this point. Closing ticket, it won't appear as 'merged' but the code has been merged.

**Pull request closed without merging**
