### PR TITLE
[WIP] Integration test for digital_ocean_tag module

### PR DESCRIPTION
**Pull request by kbreit**
##### SUMMARY
DigitalOcean modules don't have many integration tests associated with them. A PR was merged the other day to add two and this is a third focused on the digital_ocean_tag module. It only tests creation and deletion of tags since the facts module is currently broke.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
digital_ocean_tag

### CODE REVIEW

**Comment by gundalow** [comment]
@kbreit Hi, what would be needed to get this moving again?

**Comment by kbreit** [comment]
@gundalow Ugh, a rebase included a lot of other commits which I didn't want included. How do you suggest I back that out?

To answer your question directly, some of the modules are broken and are pending fixes. I changed some of the integration tests to not test those bugs, so we can at least get the tests working and pushed. I need to back out the rebase commits first though. Also, where's the best place for me to document how to run these tests? It isn't obvious, to me at least, where the API key should be configured, for example.

**Comment by gundalow** [comment]
+1 to small gradual improvements on the testing side.

The `aci` tests don't run in Shippable so they have an aliases file like: https://github.com/ansible/ansible/blob/devel/test/integration/targets/aci_ap/aliases

And the test ensures the relevant paramaters are set: https://github.com/ansible/ansible/blob/devel/test/integration/targets/aci_ap/tasks/main.yml

**Comment by kbreit** [comment]
Closing since I am using #49169 instead.

**Pull request closed without merging**
