### PR TITLE
Add pipelining to podman connection plugin

### PR DESCRIPTION
**Pull request by jordemort**
##### SUMMARY

This PR adds pipelining support to the podman connection plugin.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

`plugins/connection/podman.py`

##### ADDITIONAL INFORMATION

All that was missing here was to pass `in_data` over to `_podman`, and to set `has_pipelining` to `True`. cc @TomasTomecek

### CODE REVIEW

**Comment by Ansible912** [comment]
@jordemort hi,I am sorry to bother you, and  I am same to you as a contributor. All checks have passed for our submitted code, but how to merge it to devel branch or  waiting repository manager merges it?

**Comment by jordemort** [comment]
@Ansible912 I'm new here myself, I don't know how they do things

**Comment by TomasTomecek** [comment]
Wow, what a simple fix. Actually, while trying this out, I discovered an issue that if `podman mount` fails, ansible continues execution. https://github.com/ansible/ansible/pull/57584

@Ansible912 @jordemort we need to wait for someone with commit access to approve and merge (to devel), e.g. @abadger or @mattclay or @sivel 

could this fix land in 2.8.z?

**Review by TomasTomecek — APPROVED** [review]
LGTM, tested locally using a simple playbook (didn't observe almost any speed-up since the playbook was really trivial)

**Comment by jordemort** [comment]
@TomasTomecek The buildah plugin has the same problem, which I fixed in https://github.com/ansible/ansible/pull/57552 along with doing all the other stuff, but if you think it's worthwhile / could be backported to a 2.8.x, I could split that off into a separate PR similar to this one. Probably wouldn't want to do all of 57552 in a patch release but the pipelining fix is just one line.

**Comment by felixfontein** [comment]
You need to add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to) to this PR before it can be merged. Whether this qualifies as a bugfix (then it can be backported to 2.8.x) or a new feature (then it has to wait for 2.9) has to be decided by the release manager, i.e. @abadger.

**Comment by jordemort** [comment]
@felixfontein I have added a changelog fragment (and rebased on top of latest devel)

**Comment by jordemort** [comment]
The CI job seems to be having trouble finding my commit

**Comment by felixfontein** [comment]
@jordemort that unfortunately happens sometimes (usually when GitHub's servers don't sync fast enough). But it looks @mattclay already restarted the CI run.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@jordemort thanks for implementing this! Feel free to create a [backport PR](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs) for stable-2.8. I don't know if it will be accepted/merged, but trying doesn't hurt :) It's best to explain the situation in the PR description, so help the release manager understand the situation.

**Pull request merged**
