### PR TITLE
load files once

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

avoid unnecessary reloading of config file and vars plugins 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

config/variable manager

##### ANSIBLE VERSION

```
2.4-2.6
```

### CODE REVIEW

**Comment by sivel** [comment]
Was lib/ansible/plugins/callback/default.py accidentally included in this PR?

**Comment by bcoca** [comment]
yes, yes it was

**Comment by alikins** [comment]
That seems to reduce the openat('ansible.cfg') down to 1.

And down to one vars_loader.all() per host per task instead of 5 per host per task.

**Comment by alikins** [comment]
vars_loader.all(), filter_loader.all(), and test_loader.all()  are each called once for every host-task.

Is test_loader.all() and filter_loader.all() expected to do that?  I know they have some inherit weirdness due to really being jinja plugins but not sure what is expected. I suppose it makes sense since test/filter/vars are template focused.

**Comment by bcoca** [comment]
yes, they need to be called every time.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/58500/36/tests

**Pull request merged**
