### PR TITLE
fix win_unzip and win_share Powershell cmdlets output invalid JSONs

### LINKED ISSUE #42554: Improper Windows modules cmdlets output handling
##### SUMMARY
win_share and win_unzip fail due to MODULE_STDOUT containing invalid JSON - prefixed with what looks like the output of some cmdlets during the execution of the module.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`win_share`, `win_unzip`

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
RHEL 7.5 (Maipo)

##### STEPS TO REPRODUCE
Use `win_unzip` and `win_share` several times to manage the same file/directory - MODULE_STDOUT will sometimes contain invalid JSON strings.

##### EXPECTED RESULTS
Modules finish successfully

##### ACTUAL RESULTS
The module returns an invalid JSON on MODULE_STDOUT, although according to `failed` and `rc` fields the module did finish successfully. The error is coming from parsing the stdout of the Powershell script which contains an invalid JSON string.

For example:
```
MODULE_STDOUT:

False False True {"changed":false,"actions":[]}
```

See full `-vvvvvv` output: https://pastebin.com/4zqMX0sn

### PR DESCRIPTION
**Pull request by avishefi**
##### SUMMARY
Fixes #42554 - Powershell cmdlets for `win_unzip` and `win_share` make modules return STDOUT invalid JSON strings.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_unzip
win_share

##### ANSIBLE VERSION

Affects 2.5 and 2.6

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by schwartzmx** [comment]
lgtm shipit

**Review by jborean93 — APPROVED** [review]
Looks good to me, while you don't have to change it, for future references using `| Out-Null` is a more expensive operation than doing either

```
[void]Some-Cmdlet
Some-Cmdlet > $null
```

They achieve the same thing as `Some-Cmdlet | Out-Null` but don't take as long.

https://stackoverflow.com/questions/5260125/whats-the-better-cleaner-way-to-ignore-output-in-powershell

**Comment by jborean93** [comment]
Backport PR to stable-2.6 https://github.com/ansible/ansible/pull/42721

**Comment by avishefi** [comment]
@jborean93 thanks for the feedback and backporting it to 2.6

**Pull request merged**
