### PR TITLE
cloud: ovirt: import VM from external source

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

This PR add support to import VM from VMware, XEN and KVM.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_vms

##### ANSIBLE VERSION

```
2.3.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jctanner** [comment]
shipit

**Comment by machacekondra** [comment]
@mwperina

**Comment by machacekondra** [comment]
@ryansb

**Comment by machacekondra** [comment]
shipit

**Pull request merged**
