### PR TITLE
Split "all" into three subsections so that Travis can split tests

### PR DESCRIPTION
**Pull request by gundalow**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /home/johnb/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Experimentation with parallel builds with Travis

Will no doubt need some work before it can go live

This should allow Travis to run tests via the "Matrix" function

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible/15176)

### CODE REVIEW

**Comment by gundalow** [comment]
The statistics from Travis really don't make sense the elapsed time is sometimes less than the longest test time.

**Comment by jimi-c** [comment]
Travis reports the total time used, which is obviously much greater than the actual time as things generally run in parallel.

**Comment by gundalow** [comment]
I need to look at this more before before we merge this. Raised so people can look.

**Comment by jimi-c** [comment]
@bob-smith sure, I'm also not sure it's speeding things up and may actually be slowing them down somewhat. The reason being that there is some overhead to Travis starting up the worker and configuring things (installing packages and pulling/starting up the docker container). However when run as one big blob as we do currently, that overhead is limited to just once as opposed to 4 times as this PR does.

**Comment by gundalow** [comment]
As per agreement with @jimi-c this was useful investigation though not the right solution for the moment.

https://github.com/ansible/community/issues/47 has other details about Travis Performance

**Pull request closed without merging**
