### PR TITLE
Add support for RSA/DSA SSH host key detection in setup module for OS/X

### PR DESCRIPTION
**Pull request by jpmens**
Tested on 10.6.8

### CODE REVIEW

**Comment by mpdehaan** [comment]
queued for 0.8, that wouldn't be a tab or non-four space indent, would it?  :)

**Comment by jpmens** [comment]
I swear it ain't a TAB!!!

**Comment by jpmens** [comment]
I may have broken this pull request... (replaced 8spaces by 4, rebased, squashed, and pushed -f). I see things ok here, but I don't know if I've broken the pull request.

**Comment by mpdehaan** [comment]
looks fine to me, merged, thanks!

**Pull request merged**
