### PR TITLE
New Pure Storage FlashArray module to enable/disable Remote Assist

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
New Pure Storage FlashArray module to enable/disable Remote Assist

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
modules/storage/purestorage/purefa_ra.py

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

### CODE REVIEW

**Review by sile16 — CHANGES_REQUESTED** [review]
Disabling doesn't work, this should  == 'enabled'  instead
Line 83: if array.get_remote_assist_status()['status'] != 'enabled'

**Review by sile16 — APPROVED** [review]

**Comment by sile16** [comment]
shipit

**Comment by gundalow** [comment]
@sdodsley Thank you for the PR
@sile16 Thanks for the review

**Comment by gundalow** [comment]
New module, no need to backport

**Pull request merged**
