### PR TITLE
[stable-2.10] systemd - fix issue with capbpf and newer kernel (#72337)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Backport of #72337 for Ansible 2.10.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/systemd.py`

### CODE REVIEW

**Comment by jsf9k** [comment]
I'm currently suffering with this systemd bug in my Ansible role CI test setup, so I'm looking forward to this PR getting merged.  Thanks for creating this one, @samdoran!

**Comment by jsf9k** [comment]
Is there something else that needs to happen before this PR can be merged?  I am waiting with bated breath, since this issue is harpooning my CI setup.

**Comment by sivel** [comment]
@jsf9k 2.10.3 was just released on November 2, and we are roughly on a 4 week release schedule for .z releases.  This backport was created after we had done the RC1 release for 2.10.3, so it didn't make it in. 

However, due to the various holidays coming up, 2.10.4 is scheduled for release on Dec 14.  We may get this merged before Dec 7 (2.10.4rc1) however it won't be in any release until then.

**Comment by jsf9k** [comment]
Thanks for the explanation @sivel!

**Comment by favadi** [comment]
In the mean time, anyone facing this issue with ansible 2.10 can copy the [systemd.py](https://github.com/ansible/ansible/blob/62b0567e84f46dfc8ba5737aa08a0cc207db619e/lib/ansible/modules/systemd.py) file from this PR to `library/systemd.py` inside playbook folder as an workaround.

**Comment by mpolden** [comment]
This fix doesn't seem to handle templated units. For example if you try to control a service called `wg-quick@wg0`, then this change will call `systemctl list-unit-files 'wg-quick@wg0*'` which won't match anything because the unit file is called `wg-quick@.service`.

I added the following workaround to my local `library/systemd.py`:
```
unit_file, sep, _ = unit.partition("@")
unit_file += sep
(rc, out, err) = module.run_command("{systemctl} list-unit-files '{unit_file}*'".format(systemctl=systemctl, unit_file=unit_file))
is_systemd = unit_file in out
```

**Pull request merged**
