### PR TITLE
ansible stdin

### PR DESCRIPTION
**Pull request by bcoca**
ansible now takes module arguments from stdin 
ansible-playbook now takes playbooks from stdin

I wrote this hack a while back, I still use them once in a while with generated playbooks and as a quick way to pass existing scripts to ansible for execution.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not sure I follow this or want it.  If stdin is NOT a tty, it does
a read to determine the /default/ options to a module?

**Comment by mpdehaan** [comment]
The playbook tempfile stuff seems a bit odd too, if I must say.  I
don't think I'm going to take this one but am interested in the
discussion.

**Comment by bcoca** [comment]
The playbook hack is ugly, but I didn't see a simple way to do this w/o
making stdin a special case through a lot of the code. I put this out there
mostly to get feedback on a better approach that doesn't involve a lot of
rewriting. I tried passing /dev/stdin but this had detection and slupring
(EOF) errors.

Also, the current implementation doesn't clean up the file if there are any
errors.

**Comment by mpdehaan** [comment]
Show me what kinds of commands you are trying to make possible?

**Comment by bcoca** [comment]
I don't use these options much anymore, but IRC there was expressed
interest in having STDIN. These are examples of what I used to do:

ansible -m shell targethost < existing_script

gen_config playbook_skel.yml <user> <host> <db>|ansible-playbook -K

The first was a quick way to use legacy scripts (similar to piping to ssh),
the second generated playbooks for ephemeral instances (mostly dev/test), I
have since ported it to a 'pre' playbook that generates it and runs
ansible-playbook on it.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
script module should already solve (A)

can see some use for (B)

**Comment by bcoca** [comment]
I agree A is redundant, it was the easier to implement nicely and can
easily be removed from branch.

B has its uses (though I create my own intermediate playbooks now) but the
current implementation is fragile, the only other way I saw required a bit
of playbook refactoring. Any suggestions to avoid this?

**Comment by mpdehaan** [comment]
No time to look ATM, will think about it.

We can leave this open so we don't forget.

**Comment by mpdehaan** [comment]
actually closing as I need to keep my queue short.  I am open to playbooks reading from stdin though if you want to resubmit just that.   Be careful though as all the --list-hosts and --list-tags and everything must also work in that case.

You may just wish to code up a wrapper script instead?

**Pull request closed without merging**
