### PR TITLE
NEW MODULE: docker_image module for building docker images + Docker > 0.7 support

### PR DESCRIPTION
**Pull request by softzilla**
##### Issue Type:

Feature Pull Request
New Module Pull Request
##### Ansible Version:

ansible 1.5
##### Environment:

OS X 10.9.1
##### Summary:

To docker module added 0.7 features: 
- host to container port binding
- container linking 

Adds new docker_image module to build, check and remove images from host image storage
##### Steps To Reproduce:

Start docker container, bind internal container port 800 to docker interface (172.17.42.1) and port 80, link with PostgreSQL container (path ports and volumes from one container to another): 

```
- name: "Start new app container"
  docker:
    image: "my/app"
    name: "app1"
    links:
      - service_postgresql:db
    port_bindings:
      - 8000:172.17.42.1:80
    state: present
  tags:
    - deploy
    - start
```

For image building:

```
 - name: "Create image"
    docker_image: path="/path/to/build/dir" name="my/app" state="present"
```

For more examples see module docs
##### Expected Results:

N/A
##### Actual Results:

N/A

### CODE REVIEW

**Comment by joshuaconner** [comment]
Whoa, did the `docker` module changes get pulled in to devel already? The `docker_image` module looks good to me, but the `docker` module changes don't have updated documentation, are incompatible with #5639, and don't support all of the Docker 0.7 features. (It's certainly not the end of the world, but I - not impartially, obviously - prefer the #5639 changes.)

**Comment by rgbkrk** [comment]
Weird, I noticed the same thing (I started going ahead and using it on a Docker 0.8 deployment anyway). It does seem like it might have been merged manually at some point.

/cc @jiffyclub

**Comment by softzilla** [comment]
@joshuaconner thanx, for pointing to your pull request. I agree, #5639 looks better. 

I have also added option to define volumes, links, ports defined as YAML lists. 

```
docker:
  ... skip ...
  links:
    - postgresql:db
    - redis
```

Thats looks better in my opinion than string parameter. What you think about it?

So, what the practice? Close pull request and make new one for docker_image only?

**Comment by softzilla** [comment]
Need update to docker_py 3.0/ docker API 1.8, 1.9

**Comment by softzilla** [comment]
#6178 replace this request

**Pull request closed without merging**
