### PR TITLE
win_iis_webapppool: Use Get-AnsibleParam to retrieve parameter

### LINKED ISSUE #22805: win_iis_webapppool improvements don't set attributes correctly
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_iis_webapppool

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0.0 (stable-2.3 b73a1be03a) last updated 2017/03/20 17:27:07 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Control host: Ubuntu 16.04
Target host: Windows Server 2012

##### SUMMARY
Attributes aren't set correctly, should have been fixed in #20680 but wasn't. Used test playbook from @deekayen as mentioned in the PR. 

##### STEPS TO REPRODUCE
``` yaml
- hosts: all

  tasks:
    - name: "Install IIS."
      win_feature:
        name: "Web-Server"
        state: present
        restart: no
        include_sub_features: no
        include_management_tools: yes

    - name: "Create application pool with defaults."
      win_iis_webapppool:
        name: "GitHubPull20680_basic"
        state: started
      register: win_iis_webapppool_defaults

    - debug:
        var: win_iis_webapppool_defaults

    - name: "Create application pool with alternate settings."
      win_iis_webapppool:
        name: "GitHubPull20680_changes"
        state: started
        attributes: "autoStart:false|processModel.identityType:SpecificUser|processModel.userName:{{ user_iis_username }}|processModel.password:{{ user_iis_password }}|managedRuntimeVersion:v2.0|enable32BitAppOnWin64:true|managedPipelineMode:Classic"
      register: win_iis_webapppool_changes

    - debug:
        var: win_iis_webapppool_changes
```

##### ACTUAL RESULTS

```
TASK [Gathering Facts] ***********************************************************************************************
ok: [test]

TASK [Install IIS.] **************************************************************************************************
ok: [test]

TASK [Create application pool with defaults.] ************************************************************************
ok: [test]

TASK [debug] *********************************************************************************************************
ok: [test] => {
    "changed": false,
    "win_iis_webapppool_defaults": {
        "attributes": {},
        "changed": false,
        "info": {
            "attributes": {
                "CLRConfigFile": "",
                "applicationPoolSid": "S-1-5-82-2845532531-3417813578-2234105921-2210852024-1136530100",
                "autoStart": true,
                "enable32BitAppOnWin64": false,
                "enableConfigurationOverride": true,
                "managedPipelineMode": "Integrated",
                "managedRuntimeLoader": "webengine4.dll",
                "managedRuntimeVersion": "v4.0",
                "name": "GitHubPull20680_basic",
                "passAnonymousToken": true,
                "queueLength": 1000,
                "startMode": "OnDemand",
                "state": "Started"
            },
            "name": "GitHubPull20680_basic",
            "state": "Started"
        }
    }
}

TASK [Create application pool with alternate settings.] **************************************************************
ok: [test]

TASK [debug] *********************************************************************************************************
ok: [test] => {
    "changed": false,
    "win_iis_webapppool_changes": {
        "attributes": {},
        "changed": false,
        "info": {
            "attributes": {
                "CLRConfigFile": "",
                "applicationPoolSid": "S-1-5-82-2090956821-3273997103-1055353093-2979566528-3870201199",
                "autoStart": true,
                "enable32BitAppOnWin64": false,
                "enableConfigurationOverride": true,
                "managedPipelineMode": "Integrated",
                "managedRuntimeLoader": "webengine4.dll",
                "managedRuntimeVersion": "v4.0",
                "name": "GitHubPull20680_changes",
                "passAnonymousToken": true,
                "queueLength": 1000,
                "startMode": "OnDemand",
                "state": "Started"
            },
            "name": "GitHubPull20680_changes",
            "state": "Started"
        }
    }
}

PLAY RECAP ***********************************************************************************************************
test                 : ok=6    changed=0    unreachable=0    failed=0
```

### PR DESCRIPTION
**Pull request by virtuald**
- Fixes #22805

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Thanks for tracking this down.

The code change itself looks good, but I think you have made it against 2.3 rc branch. - Unfortunately I think it is still the case that this project only accepts pull requests based of devel - any fixes like this are then cherry picked into the release branches.  I just went looking and found it is documented that PRs must be against devel although its in an odd place in the documentation here: https://docs.ansible.com/ansible/dev_guide/developing_test_pr.html#finding-a-pull-request-and-checking-it-out-on-a-branch

Sorry, I know this a faff but please can you branch off devel and create a pull request off that?

**Comment by virtuald** [comment]
Changed the base branch and rebased.

**Comment by virtuald** [comment]
Also, FWIW, it appears that the processModel parameters can be set via the attributes. Haven't confirmed that it actually *works*, but it shows up in the property page in the IIS configuration UI.

**Comment by virtuald** [comment]
@jhawkesworth anything else that needs to be done here?

**Comment by jhawkesworth** [comment]
Looks good, thanks for doing the git-fu to move to devel.
Next thing is testing, which I am trying to do now.

**Comment by jhawkesworth** [comment]
tested, works for me on s2012r2.

shipit

**Comment by virtuald** [comment]
Awesome, thanks!

**Comment by abadger** [comment]
Merged to devel and cherry-picked to stable-2.3.

**Pull request merged**
