### PR TITLE
ec2_snapshot: updated docs

### PR DESCRIPTION
**Pull request by ghost**
Included snapshot_tags in the module's documentation. The actual functionality was previously added by another contributor per c900254ed0700d1183c667b883df16795873440b.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Just reading through this -- we usually don't require inline JSON as it's somewhat hostile to the user, so we may want to adapt this into an example where we can show it expanded out as a dictionary in the YAML.

**Comment by atlashealth** [comment]
How's this look?

**Comment by mpdehaan** [comment]
Perfect, looking at merging now, thanks!

**Comment by mpdehaan** [comment]
Merged, thanks!  Apologies on the delay, this will be live in the next docs push.

**Pull request closed without merging**
