### PR TITLE
postgresql modules: explicit defaults for bool params

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql modules: explicit defaults for bool params

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/postgresql/postgresql_copy.py```
```lib/ansible/modules/database/postgresql/postgresql_query.py```
```lib/ansible/modules/database/postgresql/postgresql_sequence.py```
```lib/ansible/modules/database/postgresql/postgresql_table.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by felixfontein — COMMENTED** [review]
I verified (by inspecting the code which uses these options) that the defaults do not affect the module's behavior.

I would be a lot more happy though if I would know that the tests also ran. (I checked, they didn't.) They didn't, because https://github.com/ansible/ansible/blob/devel/test/integration/targets/postgresql/aliases only lists some modules, but none of the modules modified here. @Andersson007 can you update the aliases file (maybe in another PR, which should be backported)?

**Comment by felixfontein** [comment]
Please rebase this PR so that #61647 is incorporated (and tests are run).

**Review by felixfontein — APPROVED** [review]
Now that all tests ran (and passed), this LGTM.

**Comment by felixfontein** [comment]
@Andersson007 thanks for implementing this! Can you create backport PRs to stable-2.8 and stable-2.9?

**Comment by Andersson007** [comment]
@felixfontein , thank you for reviewing and merging! You probably prevented problems in the future, thanks!

**Comment by Andersson007** [comment]
About the backports - sure!

**Pull request merged**
