### PR TITLE
Rename modules from plural to singular

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

See [proposal for details](https://github.com/ansible/proposals/issues/10)

This is a first batch just to see if this way of doing things is acceptable.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
ec2_vpc_dhcp_option
openstack
ovirt

##### ANSIBLE VERSION

```
2.4
```

cc @abadger

### CODE REVIEW

**Comment by machacekondra** [comment]
This break backward compatibility, so I would prefer to not merge.

**Comment by bcoca** [comment]
@machacekondra it currently does not, that is what the symilnks are for, eventually when the deprecation period is passed, it will.

**Comment by abadger** [comment]
@samdoran Have to fix the test failures (by changing the filenames in the legacy skip file for pep8 to the new filenames but other than that, this looks correct.

**Comment by samdoran** [comment]
Think I got it right this time. 🤞

**Comment by abadger** [comment]
+1

**Review by gundalow — COMMENTED** [review]
1) Some of the AWS functions are actually plural, e.g.
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html (options, not options)

2) Deprecated modules start with `_`, not sure if it's worth renaming them.

**Comment by mykaul** [comment]
1. It broke oVirt CI...
2. What does it mean for backward compatibility?
3. I'm not sure why you'd use singular in some of the modules, tbh. What happened to 'Existing modules which use plural should get aliases to singular form.' in the proposal?

+ @machacekondra

**Comment by machacekondra** [comment]
Following oVirt modules still needs rename:

```
ovirt_host_networks.py
ovirt_hosts_facts.py
ovirt_hosts.py
ovirt_mac_pools.py
ovirt_networks_facts.py
ovirt_networks.py
ovirt_nics_facts.py
ovirt_nics.py
ovirt_permissions_facts.py
ovirt_permissions.py
ovirt_quotas_facts.py
ovirt_quotas.py
ovirt_scheduling_policies_facts.py
ovirt_snapshots_facts.py
ovirt_snapshots.py
ovirt_storage_connections.py
ovirt_storage_domains_facts.py
ovirt_storage_domains.py
ovirt_tags_facts.py
ovirt_tags.py
ovirt_templates_facts.py
ovirt_templates.py
ovirt_users_facts.py
ovirt_users.py
ovirt_vmpools_facts.py
ovirt_vmpools.py
ovirt_vms_facts.py
ovirt_vms.py
```

**Comment by samdoran** [comment]
@mykaul Symlinks to the new singular names from the existing plural names do exist. You should be able to use either name. Is something in CI not following symlinks?

As for backwards compatibility, the symlinks will be removed in 2.8 and a warning is emitted until then.

Naming is always controversial. `*_facts` modules will remain plural and those where the service or tool name is plural. All others will be singular.

**Comment by mykaul** [comment]
On Tue, Aug 15, 2017 at 4:29 PM, Sam Doran <notifications@github.com> wrote:

> @mykaul <https://github.com/mykaul> Symlinks to the new singular names
> from the existing plural names do exist. You should be able to use either
> name. Is something in CI not following symlinks?
>

wget did not follow...

**Comment by samdoran** [comment]
@mykaul If you're downloading the modules directly, I can see how this would be an issue. The old filename no longer exists — it is now a symlink with an underscore prefix. Even if the old name was a symlink, GitHub does not redirect symlinks (that I can tell from my brief testing).

For the next batch of renaming, I'll coordinate with you to let you know the new file names. That's the only way I can think to make this relatively painless.

**Pull request merged**
