### PR TITLE
[backport/2.8/63280] acl: fix module failure if there're spaces in a path (#63280)

### PR DESCRIPTION
**Pull request by decayofmind**
##### SUMMARY

ACL module will fail if there are spaces in a path.

Backport of https://github.com/ansible/ansible/pull/63280

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/files/acl.py

### CODE REVIEW

**Comment by mattclay** [comment]
@decayofmind Tests are not passing for this backport. Can you take a look?

**Comment by decayofmind** [comment]
> @decayofmind Tests are not passing for this backport. Can you take a look?

@mattclay Is there a way we can rerun tests?

**Comment by mattclay** [comment]
@decayofmind I've restarted the tests.

**Comment by mattclay** [comment]
@decayofmind Tests are still failing.

**Comment by decayofmind** [comment]
@mattclay thx for rerunning them, I'll try to solve the issue in next few days.

**Comment by decayofmind** [comment]
@mattclay Sorry for the delay.

The problem here is quite interesting:
Ansible 2.8 uses `~/ansible_testing/` as a value for `output_dir` and since `test_file` contains whitespace we need to apply `| quote` in integration test for it to pass. Single quotes in a shell will leave the tilde symbol in a resulting path as is (unexpanded). This is why tests are failing.

In Ansible 2.9 the `output_dir` has no tilde, so tests are passing.

Could you please advise how I should proceed?

Adding an `expanduser` filter before a `quote` filter will solve the issue for Ansible 2.8, but changes in backports shouldn't vary from the origin. Or can they?

**Comment by mattclay** [comment]
@decayofmind Go ahead and add your proposed fix to the tests as another commit. Once tests pass this can be merged and included in the next 2.8 release.

**Comment by decayofmind** [comment]
@mattclay all good now

**Comment by mattclay** [comment]
@decayofmind Thanks. This won't make it into 2.8.9, but should be able to be included in 2.8.10 in about 3 weeks.

**Pull request merged**
