### PR TITLE
Add run_command to module_common and update modules, part deux

### PR DESCRIPTION
**Pull request by sfromm**
Related to issue #1738. Moves the handling of running system commands into module_common.  The main difference from #1846 is that shell=(True|False) is gone.  If you provide a list, shell=False.  If you provide a string, shell=True.  As usual, comments welcome.  :-)

### CODE REVIEW

**Comment by dhozac** [comment]
Looks great to me!

**Comment by sfromm** [comment]
Looks like something got merged and this won't apply cleanly.  Closing this PR and will pull in the commit in question.

**Comment by mpdehaan** [comment]
Ok some minor things

'fail_on_rc_non_zero' should be something a bit shorter and easier to remember, like 'check_rc'.

Also any arguments should really be named, like

def run_command(self, args,  check_rc=True, close_fds=True, executable=None, shell=False, **kwargs)

This allows getting rid of all of the string/kwargs checking logic and working with regular booleans in the code.

So probably more like:

def run_command(self, args,  check_rc=False, close_fds=True, executable=None, shell=False)

I really like how this helps clean up all of the modules.

**Comment by sfromm** [comment]
I just applied the change, but can easily update it as needed.

On Sun, Jan 13, 2013 at 8:39 AM, Michael DeHaan notifications@github.comwrote:

> Ok some minor things
> 
> 'fail_on_rc_non_zero' should be something a bit shorter and easier to
> remember, like 'check_rc'.

I like check_rc beter, much more succinct.  I'll fix that in a moment.

> Also any arguments should really be named, like
> 
> def run_command(self, args, check_rc=True, close_fds=True,
> executable=None, shell=False, **kwargs)
> 
> This allows getting rid of all of the string/kwargs checking logic and
> working with regular booleans in the code.
> 
> So probably more like:
> 
> def run_command(self, args, check_rc=False, close_fds=True,
> executable=None, shell=False)
> 
> The reason I opted to do `run_command(self, args, **kwargs)` was so that
> you didn't have to provide all the arguments if you only needed to specify
> one of them (eg `check_rc`).

sf

**Comment by dhozac** [comment]
That is also true for keyword arguments though, so @mpdehaan's version would allow the same. I agree it's a lot cleaner.

**Comment by sfromm** [comment]
Fair enough.  I'll simplify the method too.

sf

**Pull request closed without merging**
