### PR TITLE
Windows Facts: add WinSystemLocale

### PR DESCRIPTION
**Pull request by sbaerlocher**
##### SUMMARY
Add the system locale language of Windows to the facts of Ansible for the Windows operating system.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Windows Setup Facts

##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by jborean93** [comment]
`Get-WinSystemLocale` was only added in Server 2012+ which does not make it a good candidate to add to the base facts for Windows. We still need to come up with a good way of dealing with Windows facts without bloating the base facts anymore than they have already become.

If you do need these values I would recommend creating a custom facts module where it can pull in more datetime/region settings than just the system locale.

**Comment by sbaerlocher** [comment]
A specification which is the basic system language simplifies many things. Especially in countries where there are several official languages that need to be supported, because there are different language-related differences under Windows.

One of these differences is the Windows Firewall group "Remote Desktop". In the de-DE version it is called "Remotedesktop" and in the en-US version it is called "Remote Desktop".

**Comment by jborean93** [comment]
I'm not saying this isn't a good thing to have, I'm saying the approach to add it into the normal `setup.ps1` module along with using `Get-WinSystemLocale` is the wrong way to go about doing it due to the reasons I listed. If you want to get this feature into Ansible I would say create another PR which adds a facts module that returns some datetime/local/region info about a host. It will need to work on all supported hosts unless it is difficult to get the information. Have a look at `win_region` to see how it get's around this restriction on older hosts.

**Comment by sbaerlocher** [comment]
I understand.
Then a new module should be created which is called in the tasks as follows:
```yml
- win_info:
  register: region
```
 which then returns the values datetime/local/region in the register.

Is this correct?

**Comment by dagwieers** [comment]
To be honest, I do think the system's locale should be part of the default facts. On older systems there must be an easy way to get this information as well, no ? So it should not be very hard to come up with something that works well on all systems.

**Comment by sbaerlocher** [comment]
In older systems this information can be found in the "systeminfo".  But I didn't succeed in getting just this information out of there.

**Comment by sbaerlocher** [comment]
Thank @joehomeskillet
The following command should also output the language in older systems.
```(Get-WmiObject -Class Win32_OperatingSystem).MUILanguages | Select -Index 0```

If that's okay, I'd do a new PR.

**Comment by dagwieers** [comment]
Beware that the deadline for getting new features/modules accepted in [Ansible v2.5 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_5.rst), it is set to either 2018-01-15 or 2018-01-31. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to [the Windows Working Group meeting agenda](https://github.com/ansible/community/issues/195) to get it resolved.

**Comment by dagwieers** [comment]
Beware that the deadline for getting new features/modules accepted in [Ansible v2.6 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_6.rst#release-schedule), it is set to either 2018-05-17 or 2018-05-25. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to [the Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

**Comment by sbaerlocher** [comment]
This PR can also be closed. Does anyone have an objection?

**Comment by jhawkesworth** [comment]
No objection to closing from me.

**Comment by dagwieers** [comment]
I still would like to have a way to expose this information to users. Either by default, or alternatively from another _facts module (win_product_facts ?).

And there's also a difference between the system locale, the user's locale (and possibly the locale of the login window). I have had troubles setting all of them to our country's locale. New users always ended up with a Dutch (instead of Flemish) locale. Also keyboard settings for each where problematic :-/

**Comment by ShachafGoldstein** [comment]
Should be revived as with default user locale, system locale facts?

**Comment by ShachafGoldstein** [comment]
What about `MUILanguages` under `Win32_OperatingSystem`?

**Comment by jhawkesworth** [comment]
I think we should close this one.  If there is a reliable way to get the system and user locale and add it into facts then it would be best done in a separate PR.  I am not volunteering to create that PR but this module couldn't be merged as it stands as it will only work on later windows versions.

**Comment by sbaerlocher** [comment]
At the moment I am again facing the same problem that I need the system language of Windows. I can sit down as soon as I have free recurrences and write a new independent facts module. What features should it disregard from system and user language?

**Comment by gundalow** [comment]
Is anybody able to work on this? Seems like there is a demand for it.

**Comment by sbaerlocher** [comment]
@gundalow What are the requirements? What information should the module provide? in this PR I have only implemented `Get-WinSystemLocale`.

**Comment by nitzmahone** [comment]
I'd agree that this is a good candidate for the default facts module, we just need it in a way that will (ideally) provide the correct value on all Windows versions Ansible supports, or at least fail gracefully (eg by setting the value to `UNKNOWN`) on systems we can't get the value from.

**Comment by nitzmahone** [comment]
Since there are tons of values that are available and are platform/version/config dependent, we'd probably want a generic `ansible_locale` dictionary or something that can be populated with values like:
`system_language: en-US`
`system_encoding: UTF8`

The basic ones are cheap and simple to get on most systems, so that makes sense to put in the default facts module, but if we're getting nutty and pulling things like user keyboard layouts and stuff, I'd agree that it should probably go into something like a `win_region_facts` module instead.

PS- the works-on-all-versions implementation of Get-WinSystemLocale is
`([cultureinfo]([int]::Parse($win32_os.Locale, 515))).Name  # 515 == NumberStyles.HexNumber`
(assuming this was going under the `platform` section of the current `setup.ps1`)

**Comment by gundalow** [comment]
@sbaerlocher Hi, do the above comments from @nitzmahone make sense?

**Comment by jborean93** [comment]
Now that the Ansible migration has occurred the setup file is located at https://github.com/ansible-collections/ansible.windows under [plugins/modules/setup.ps1](https://github.com/ansible-collections/ansible.windows/blob/master/plugins/modules/setup.ps1). While we have a tool to try and migrate these PRs they won't work with PRs with conflicts. Feel free open a new PR with the changes discussed in this PR on that repo to continue with this work.

**Pull request closed without merging**
