### PR TITLE
Update ce_evpn_global to fix bugs

### PR DESCRIPTION
**Pull request by yanzhangi**
##### SUMMARY

Modify the configured query statement and replace get_config with exec_command

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

ansible/lib/ansible/modules/network/cloudengine/ce_evpn_global.py

```paste below

```

### CODE REVIEW

**Review by yuandongx — APPROVED** [review]
+1

**Comment by hwDCN** [comment]
LGMT

**Comment by hwDCN** [comment]
+1

**Review by yuandongx — APPROVED** [review]
LGTM

**Pull request merged**
