### PR TITLE
point at corresponding version

### LINKED ISSUE #54736: Make "See Also" links point to the same version the user is on
##### SUMMARY
As a user, I expect the version of the documentation to remain the same as I navigate from one module to another. If I'm browsing the 2.7 documentation and click on a link to a module, I expect to see the 2.7 version of the docs for that module.

Right now the links in the `See Also` section of the module documentation are hard-coded to point to the `latest` version of other modules. 

Redirect the user consistently using the `ansible_version` variable.

See https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/doc.py#L595 for an example of the problem.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docs.ansible.com 
See Also section
possibly other sections as well

##### ANSIBLE VERSION
all versions

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

### PR DESCRIPTION
**Pull request by bcoca**
modules were always pointing at latest

fixes #54736
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME

ansible-doc

### CODE REVIEW

**Comment by acozine** [comment]
CI failures seem unrelated to the changes. Kicking off a new run.

**Comment by acozine** [comment]
I published this branch to the test site and went to compare the old/bad/wrong behavior in prod against the new/good/correct behavior introduced by this PR . . . and now I can't replicate the bug. In the module docs, the `seealso` links point to the same version as the originating page. It's odd, I don't quite know what to think, but I'm going to leave this PR open until Monday.

**Comment by bcoca** [comment]
@acozine  you would have to use stable branches to reproduce the issue:
using 'stable-2.8' I run `ansible-doc copy` and I get:
```
SEE ALSO:
      * Module assemble
           The official documentation on the assemble module.
           https://docs.ansible.com/ansible/latest/modules/assemble_module.html
```
which is 'correct' for now, but once 2.9 is released .. it won't be

with PR i get 
```
SEE ALSO:
      * Module assemble
           The official documentation on the assemble module.
           https://docs.ansible.com/ansible/2.8/modules/assemble_module.html
```
which should 'always' be true

**Comment by akatch** [comment]
I'm curious as to why the condtional on `description` existing for the item was removed in this change. Can you elaborate?

**Comment by bcoca** [comment]
that was existing, i just refactored the 'common parts' out of it

**Comment by akatch** [comment]
Got it. shipit

**Pull request merged**
