### PR TITLE
Add the azure_rm_azurefirewall_info module

### PR DESCRIPTION
**Pull request by smile37773**
##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
azure_rm_azurefirewall_info.py

### CODE REVIEW

**Comment by Fred-sun** [comment]
@yungezz @zikalino @yuwzho @MyronFanQiu Please take a review when you're free! Thanks a lot!

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@yungezz @MyronFanQiu @zikalino

**Comment by Fred-sun** [comment]
@yungezz @zikalino review_need

**Review by zikalino — APPROVED** [review]

**Pull request merged**
