### PR TITLE
Replace absolute imports by relative

### PR DESCRIPTION
**Pull request by davidfischer-ch**

### CODE REVIEW

**Comment by bcoca** [comment]
what does this fix?

**Comment by davidfischer-ch** [comment]
Make it more easy to switch to Python 3.

Fix a recursive import:

```
lib/ansible/utils/__init__.py -> import of display() is moved into the methods using it.
```

Exanple code that failed before:

```
from ansible.callbacks import AggregateStats, PlaybookCallbacks, PlaybookRunnerCallbacks
from ansible.playbook import PlayBook
from ansible.utils import VERBOSITY
```

**Comment by davidfischer-ch** [comment]
[WARNING] I found some mistakes not covered by unit-tests. Work in progress!

**Comment by davidfischer-ch** [comment]
Still faulty because I import callbacks and it is also a callbacks variable ... Work in progress.

**Comment by mpdehaan** [comment]
We're not interested in moving to python 3 anytime soon.

RHEL is quite the priority and it is still possible to access python2 on systems where /usr/bin/python is python3 by using the ansible_python_interpreter variable.

**Comment by davidfischer-ch** [comment]
Why do you close this ?

Because it does break nothing in the unit-tests and it does make the code more Python 3 ready at no cost for you ...

**Pull request closed without merging**
