### PR TITLE
YUM: Ensure we have enough values to split

### LINKED ISSUE #56800: yum list exception if not working plugins
##### SUMMARY
Yum module fails if repoquery return unexpected response. Follows #26968

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

yum

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
  config file = /home/adrian/ansible.cfg
  configured module search path = [u'/home/adrian/modules']
  ansible python module location = /home/adrian/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/adrian/.venv/bin/ansible
  python version = 2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.3 (Maipo)
RPM version 4.11.3
Repoquery version 0.0.11

##### STEPS TO REPRODUCE

```yaml
- name: Yum expire-cache
  yum:
    list: kernel
    expire-cache: true
```

That task executes the following command:
```
/bin/repoquery --show-duplicates --plugins --quiet --qf '%{name}|%{epoch}|%{version}|%{release}|%{arch}|%{repoid}' kernel
```
In the response there are some "errors" for some plugins (in stdout):
```
Plugin "product-id" can't be imported
Plugin "search-disabled-repos" can't be imported
Plugin "subscription-manager" can't be imported
kernel|0|3.10.0|123.el7|x86_64|rhel-7-server-rpms
kernel|0|3.10.0|123.1.2.el7|x86_64|rhel-7-server-rpms
kernel|0|3.10.0|123.4.2.el7|x86_64|rhel-7-server-rpms
```

That erroneous lines reach [pkg_to_dict](https://github.com/ansible/ansible/blob/8fe9618c8406c8e7ba30cea7a77e6fa6f16059ec/lib/ansible/modules/packaging/os/yum.py#L766) raising an exception:
```
    n, e, v, r, a, repo = pkgstr.split('|')
ValueError: need more than 1 value to unpack
```

### PR DESCRIPTION
**Pull request by adrianlzt**
Avoid raising an exception if pkgstr does not complains with expected
value.

##### SUMMARY

Fixes #56800 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/packaging/os/yum.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by mkrizek — COMMENTED** [review]
Commented in the issue this is trying to fix. I am not sure this is the correct fix. We should probably prevent 'incorrect data' getting into `pkg_to_dict` in the first place.

**Comment by mkrizek** [comment]
Hrm, so we get `Plugin "subscription-manager" can't be imported` from `repoquery` even with `--quiet`. Not sure I have a better idea so LGTM.

cc @maxamillion

**Comment by kfattig** [comment]
Any update on this PR? It's causing intermittent issues for us.

In our case some machines return messages like this to stdout:
```bash
-bash-4.2# yum list updates
Plugin "package_upload" can't be imported
Plugin "product-id" can't be imported
Plugin "search-disabled-repos" can't be imported
Plugin "subscription-manager" can't be imported 
```

Which doesn't match the '|' pattern that split is looking for, so it blows up. Running 'yum list updates' works fine, so I don't think these messages should cause a failure.

Before finding this PR I made the same change locally and it seems to fix our issues. I understand that it's a little crude but do not have a better suggestion, as it seems there's no way to suppress that output.

**Comment by maxamillion** [comment]
rebuild_merge

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
I agree with @mkrizek, it's heuristic but I can't think of anything better and a lot of how we deal with yum outputs is rather heuristic anyways so I'm good with it. :+1:

**Pull request merged**
