### PR TITLE
aix_ipsec.py added

### PR DESCRIPTION
**Pull request by flynn1973**
##### SUMMARY
Manages the ipsec filter rules on AIX.
This module just deals with individual rules. If you need advanced
 chaining of rules the recomended way is to template the ipsec restore
 file.
##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
aix_ipsec

##### ADDITIONAL INFORMATION

Examples:
```yaml
# Make sure ipsec is started
- name: Make sure ipsec is started
  aix_ipsec:
    state: started
# Make sure ipsec is stopped
- name: Make sure ipsec is stopped
  aix_ipsec:
    state: stopped
# flush all ipsec rules
- name: Flush ipsec rules
  aix_ipsec:
    state: flushed
# Add a rule before the deny rule for interface en0
- name: Add permit rule for en0 from ip 4.3.2.1/32 port 1234 to any port at ip 1.2.3.4/32
  aix_ipsec:
    state: present
    action: 'permit'
    destination_address: '1.2.3.4'
    destination_mask: '255.255.255.255'
    destination_port_operation: 'any'
    destination_port: '0'
    source_address: '4.3.2.1'
    source_mask: '255.255.255.255'
    source_port_operation : 'eq'
    source_port: '1234'
    intf: 'en0'
# Add a rule from ip 4.3.2.1/32 that equals port 1234 to ip 1.2.3.4/24 equals port 1234 at the end of the rules.
- name: Add permit rule for port 1234
  aix_ipsec:
    state: present
    action: 'permit'
    destination_address: '1.2.3.4'
    destination_mask: '255.255.255.0'
    destination_port_operation: 'eq'
    destination_port: '1234'
    source_address: '4.3.2.1'
    source_mask: '255.255.255.255'
    source_port_operation : 'eq'
    source_port: '1234'
# remove a rule
- name: Remove Rule
  aix_ipsec:
    state: absent
    action: 'permit'
    destination_address: '1.2.3.4'
    destination_mask: '255.255.255.255'
    destination_port_operation: 'any'
    destination_port: '0'
    source_address: '4.3.2.1'
    source_mask: '255.255.255.255'
    source_port_operation : 'eq'
    source_port: '1234'
    intf: 'en0'
```

### CODE REVIEW

**Comment by molekuul** [comment]
@flynn1973 Hi, this module was not ready just for a pull request, that why I didn't do that before.
please contact me about your fork of my AIX-ansible-modules role, where you found this module.

Kind regards,

Joris Weijters

**Comment by d-little** [comment]
Should this PR be closed as non-functional in its current state?  Or are we hoping to update and merge this particular PR eventually?

@flynn1973  @molekuul

**Comment by flynn1973** [comment]
i use this module on a daily basis and it works perfectly well.

**Comment by flynn1973** [comment]
ready_for_review

**Pull request closed without merging**
