### PR TITLE
Sets permission on ansible files properly when sudo'ing to non-root

### PR DESCRIPTION
**Pull request by lorin**
When sudo'ing as a non-root user, the ansible files will be chown'd
to the non-root user.

Fix for #700.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I would like to see if this can be done in one hop, since hops are somewhat expensive

so like chown && chmod && exec all in one command line call

a function to decide how to build the arguments line is probably desirable, rather than one that actually does it.

**Comment by mpdehaan** [comment]
I'm going to attempt a varation on this...should have something shortly

**Comment by mpdehaan** [comment]
I've been thinking about this after trying it, and I do not like the idea of using /tmp as we have a commitment to security, and the idea that you can log in as root temporarily to chmod/chown is NOT a guarantee, many users do not have root access.

The workaround of setting ANSIBLE_REMOTE_TEMP to a location where the user and sudo_user both have access seems to be the best solution, and "/tmp" MAY be an acceptable value for that, but another directory is a better choice.  We would be well advised to document this better in the FAQ, which needs to get more technical anyway, I will make a note of it.

**Comment by mpdehaan** [comment]
see mailing list thread, but /tmp seems to be the best solution

What you had was using root to change permissions, which breaks people who have it set so they can't login via root ssh -- which actually was the original reason for the sudo feature :)

Anyway, the /tmp solution seems to be a very good one, and I don't think it's vulnerable to anything other than the files being readable for a short interval.

**Comment by lorin** [comment]
I responded on the mailing list, with some additional details about my use case.

As far as I know, the proposed change works fine for users who can't ssh as root, as long as they can sudo to root. I tested it on Ubuntu (which doesn't allow root ssh, but allows sudo to root).

**Comment by mpdehaan** [comment]
The /tmp fix should work even if you cannot become root.

**Comment by lorin** [comment]
Yeah, using /tmp sounds fine to me. As long as it's clearly specified in the docs that the files will be briefly readable. Especially since, for this particular use case (configuring postgresql), it's likely that the file will contain passwords.

**Comment by mpdehaan** [comment]
Yeah, I thought about HMAC'ing the module args and passing in the decrypt string when you execute the command, but I'm really not the person you want trying to do that correctly, and at that point you have greater problems.

**Pull request closed without merging**
