### PR TITLE
Check nfs_version properly

### PR DESCRIPTION
**Pull request by ghost**
original commit: https://github.com/machacekondra/ovirt-ansible-roles/commit/63f81d20dba82c0be4103de6c80f9de84ed6aaa8

##### SUMMARY

This change checks the nfs version properly for an ovirt storage connection check. At the moment a check will end up in the error message: "The type 'str' isn't valid for attribute 'nfs_version', it must be 'NfsVersion'"

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

module: ovirt_storage_connection

### CODE REVIEW

**Review by machacekondra — APPROVED** [review]
Thanks a lot ! shipit

**Comment by machacekondra** [comment]
Just please fix the indentation:

```lib/ansible/modules/cloud/ovirt/ovirt_storage_connection.py:137:16: E121 continuation line under-indented for hanging indent
```

**Review by mnecas — APPROVED** [review]
shipit

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
shipit

**Comment by GarretSchumann** [comment]
Sorry, do you need me to do anything?

**Comment by mnecas** [comment]
@GarretSchumann nope the shipit is only for bot which should merge it

**Pull request merged**
