### PR TITLE
Added Ansible UTM Info Module for proxy location entities.

### PR DESCRIPTION
**Pull request by maunzCache**
##### SUMMARY
This PR will add a new utm info module which allows the management of proxy location entries of the Sophos UTM. This module integrates with the existing utm_utils .

##### ISSUE TYPE
* New Module Pull Request

##### COMPONENT NAME
* module/web_infrastructure/sophos_utm/utm_proxy_location_info.py

### CODE REVIEW

**Comment by getjack** [comment]
@stearz @RickS-C137 Please help out reviewing :)

**Review by MatrixCrawler — APPROVED** [review]

**Comment by MatrixCrawler** [comment]
shipit

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/blob/e0538610bf984496497b983175f365b6ff5c8ed1/.github/BOTMETA.yml#L1346

Should that include @stearz @RickS-C137?

**Comment by gundalow** [comment]
Also I see we are pinging `@example` could you please update https://github.com/ansible/ansible/pull/51739#issuecomment-460634325 to include the right person & GitHub ID

https://github.com/ansible/ansible/blob/e0538610bf984496497b983175f365b6ff5c8ed1/lib/ansible/modules/web_infrastructure/sophos_utm/utm_network_interface_address.py#L20

**Comment by getjack** [comment]
> Also I see we are pinging `@example` could you please update [#51739 (comment)](https://github.com/ansible/ansible/pull/51739#issuecomment-460634325) to include the right person & GitHub ID
> 
> [ansible/lib/ansible/modules/web_infrastructure/sophos_utm/utm_network_interface_address.py](https://github.com/ansible/ansible/blob/e0538610bf984496497b983175f365b6ff5c8ed1/lib/ansible/modules/web_infrastructure/sophos_utm/utm_network_interface_address.py#L20)
> 
> Line 20 in [e053861](/ansible/ansible/commit/e0538610bf984496497b983175f365b6ff5c8ed1)
> 
>      - Juergen Wiebe (@example)

I wrongly included that user in one PR and none of my colleagues noticed that so i begged my colleague to create a github account be he's ill at the moment.

**Comment by gundalow** [comment]
@getjack OK, should I mergethis PR as is, then in a follow up PR you can update BOTMETA and `utm_network_interface_address.py`?

**Pull request merged**
