### PR TITLE
Fixes #25402 - bad handshake failure

### LINKED ISSUE #25402: get_url: bad handshake failure, with ansible 2.3.1.0, python 2.7.12
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```ini
[defaults]
log_path = ./ansible.log
pipelining = True
host_key_checking = False
command_warnings = True
retry_files_enabled = False
```

##### OS / ENVIRONMENT
OS: Ubuntu 16.04.2 LTS (Xenial Xerus)
Python: 2.7.12
OpenSSL: 1.0.2g  1 Mar 2016

Possibly relevant python modules:

* pyOpenSSL==17.0.0
* ndg-httpsclient==0.4.2
* pyasn1==0.2.3
* pyasn1-modules==0.0.7
* idna==2.5
* pyOpenSSL==17.0.0
* urllib3==1.21.1
* requests==2.17.3

##### SUMMARY
Trying to download a vagrant binary (from https://releases.hashicorp.com/vagrant/) using the `get_url` module fails with the following error (wrapped by me):

```
Failed to validate the SSL certificate for releases.hashicorp.com:443.
Make sure your managed systems have a valid CA certificate installed.
You can use validate_certs=False if you do not need to confirm the servers identity
but this is unsafe and not recommended.

Paths checked for this platform:

/etc/ssl/certs,
/etc/pki/ca-trust/extracted/pem,
/etc/pki/tls/certs,
/usr/share/ca-certificates/cacert.org,
/etc/ansible.

The exception msg was:

(\"bad handshake: Error([
  ('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert protocol version')
],)
```

##### STEPS TO REPRODUCE

```console
$ ansible localhost -m get_url -a 'url=https://releases.hashicorp.com/vagrant/ dest=/tmp/download'
```

##### EXPECTED RESULTS

I should work. If you run it with `validate_certs=false`, it _does_ work:

```console
$ ansible localhost -m get_url -a 'url=https://releases.hashicorp.com/vagrant/ dest=/tmp/download validate_certs=false'

 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS => {
    "changed": false, 
    "dest": "/tmp/download", 
    "gid": 1000, 
    "group": "duncan", 
    "mode": "0664", 
    "msg": "file already exists", 
    "owner": "duncan", 
    "size": 3123, 
    "state": "file", 
    "uid": 1000, 
    "url": "https://releases.hashicorp.com/vagrant/"
}
```

##### ACTUAL RESULTS

```console
$ ansible localhost -m get_url -a 'url=https://releases.hashicorp.com/vagrant/ dest=/tmp/download' -vvvv

No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/basics/get_url.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: duncan
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/duncan/.ansible/tmp/ansible-tmp-1496782045.65-131654390911415 `" && echo ansible-tmp-1496782045.65-131654390911415="` echo /home/duncan/.ansible/tmp/ansible-tmp-1496782045.65-131654390911415 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpzQtKr2 TO /home/duncan/.ansible/tmp/ansible-tmp-1496782045.65-131654390911415/get_url.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/duncan/.ansible/tmp/ansible-tmp-1496782045.65-131654390911415/ /home/duncan/.ansible/tmp/ansible-tmp-1496782045.65-131654390911415/get_url.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/duncan/.ansible/tmp/ansible-tmp-1496782045.65-131654390911415/get_url.py; rm -rf "/home/duncan/.ansible/tmp/ansible-tmp-1496782045.65-131654390911415/" > /dev/null 2>&1 && sleep 0'
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": false, 
            "checksum": "", 
            "content": null, 
            "delimiter": null, 
            "dest": "/tmp/download", 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "force_basic_auth": false, 
            "group": null, 
            "headers": null, 
            "http_agent": "ansible-httpget", 
            "mode": null, 
            "owner": null, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "sha256sum": "", 
            "src": null, 
            "timeout": 10, 
            "tmp_dest": "", 
            "unsafe_writes": null, 
            "url": "https://releases.hashicorp.com/vagrant/", 
            "url_password": null, 
            "url_username": null, 
            "use_proxy": true, 
            "validate_certs": true
        }
    }, 
    "msg": "Failed to validate the SSL certificate for releases.hashicorp.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: (\"bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert protocol version')],)\",)."
}
```

### PR DESCRIPTION
**Pull request by aurelienmaury**
##### SUMMARY

This is a patch candidate for the #25402 issue.

This modifies the PROTOCOL floor value in `urls.py`, so that modules like `get_url` could validate certificates for website accepting only TLSv1_2 and no less.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
`module_utils/urls.py`

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### ADDITIONAL INFORMATION

* BEFORE
```
ansible -m get_url -a "url=https://releases.hashicorp.com dest=/tmp/hashicorp_index.html" localhost
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Failed to validate the SSL certificate for releases.hashicorp.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: (\"bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert protocol version')],)\",)."
}
```

* AFTER
```
ansible -m get_url -a "url=https://releases.hashicorp.com dest=/tmp/hashicorp_index.html" localhost
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS => {
    "changed": true,
    "checksum_dest": null,
    "checksum_src": "afdac380532e75798fa0afc46d06d3cd0a9e6b84",
    "dest": "/tmp/hashicorp_index.html",
    "gid": 0,
    "group": "root",
    "md5sum": "e978f533ad1eefc5110b6354760e12f5",
    "mode": "0644",
    "msg": "OK (7998 bytes)",
    "owner": "root",
    "size": 7998,
    "src": "/tmp/tmpRL_auy",
    "state": "file",
    "status_code": 200,
    "uid": 0,
    "url": "https://releases.hashicorp.com"
}
```

### CODE REVIEW

**Comment by aurelienmaury** [comment]
Hi @nitzmahone sorry to bother, but I think there is a lack with this PR's labels: like stated in the description, it clearly affects 2.3, I have not even tested with 2.4.

**Comment by alikins** [comment]
possibly related to https://github.com/ansible/ansible/issues/31998 ?

**Comment by jctanner** [comment]
@aurelienmaury the bot uses the version of the "devel" branch at time of submission to flag the "affects_x.x" labels for PRs. Your PR would not have been merged into the 2.3 branch unless a backport had been requested or you submitted the PR against the 2.3 branch.

**Comment by sivel** [comment]
This will need more branches.  Mac does not include `ssl.PROTOCOL_TLSv1_2`.

```
python -c 'import ssl; ssl.PROTOCOL_TLSv1_2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
```

So although it has `HAS_SSLCONTEXT` `v1_2` doesn't exist.

**Comment by abadger** [comment]
@aurelienmaury We can't use this verbatim as ```ssl.PROTOCOL_TLSv1_2``` wasn't available until python-2.7.9 (we need to support python-2.6.x in his code).  If you have ideas on rectifying that, it would be great to hear.  I'm spending a little time looking as well but I can't guarantee I'll come up with a solution.

**Comment by abadger** [comment]
@aurelienmaury Okay, I think I've tracked down a better way to fix this.  See the code in PR https://github.com/ansible/ansible/pull/32053 if you'd care to test out my fix.

**Pull request closed without merging**
