### PR TITLE
grafana_datasource: use the Ansible helpers to get basic auth header

### LINKED ISSUE #49147: grafana_datasource fails with python3
##### SUMMARY

When using Python3 with Ansible, the grafana_datasource module raises a `TypeError: a bytes-like object is required, not 'str'`  exception.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_datasource.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /Users/remirey/dev/engie/da-backend/deploy/ansible/ansible.cfg
  configured module search path = ['/Users/remirey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/remirey/.virtualenvs/engie/lib/python3.7/site-packages/ansible
  executable location = /Users/remirey/.virtualenvs/engie/bin/ansible
  python version = 3.7.1 (default, Nov  6 2018, 18:49:54) [Clang 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_GATHERING(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = explicit
DEFAULT_HASH_BEHAVIOUR(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = replace
DEFAULT_MANAGED_STR(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = Please do not change this file directly since it is managed by Ansible and will be overwritten
DEFAULT_REMOTE_USER(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = centos
HOST_KEY_CHECKING(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/remirey/dev/da-backend/deploy/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
OSX 10.12.6

##### STEPS TO REPRODUCE

```yaml
    - name: Create MySQL datasource
      grafana_datasource:
        name: "{{ grafana_datasources.mysql.name }}"
        grafana_url: "{{ grafana_base_url }}"
        grafana_user: "{{ grafana_users.admin.login }}"
        grafana_password: "{{ grafana_users.admin.password }}"
        org_id: "{{ grafana_organization_id }}"
        ds_type: "mysql"
        url: "{{ database_credentials_secret.host }}"
        database: "{{ database_name }}"
        user: "{{ database_credentials_secret.username }}"
        password: "{{ database_credentials_secret.password }}"
```

##### EXPECTED RESULTS
No errors

##### ACTUAL RESULTS

```
TASK [Create MySQL datasource] ***********************************************************************************************************************************************************************
Monday 26 November 2018  18:38:27 +0100 (0:00:00.386)       0:00:01.453 *******
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/Users/remirey/.ansible/tmp/ansible-tmp-1543253907.275441-99514604312595/AnsiballZ_grafana_datasource.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/Users/remirey/.ansible/tmp/ansible-tmp-1543253907.275441-99514604312595/AnsiballZ_grafana_datasource.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/Users/remirey/.ansible/tmp/ansible-tmp-1543253907.275441-99514604312595/AnsiballZ_grafana_datasource.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/remirey/.ansible/tmp/ansible-tmp-1543253907.275441-99514604312595/AnsiballZ_grafana_datasource.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/Users/remirey/.virtualenvs/engie/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/Users/remirey/.virtualenvs/engie/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/var/folders/nx/br96pdj13gd30xmz81_fpsw00000gn/T/ansible_grafana_datasource_payload_lo8baeic/__main__.py\", line 541, in <module>\n  File \"/var/folders/nx/br96pdj13gd30xmz81_fpsw00000gn/T/ansible_grafana_datasource_payload_lo8baeic/__main__.py\", line 523, in main\n  File \"/var/folders/nx/br96pdj13gd30xmz81_fpsw00000gn/T/ansible_grafana_datasource_payload_lo8baeic/__main__.py\", line 376, in grafana_create_datasource\nTypeError: a bytes-like object is required, not 'str'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### PR DESCRIPTION
**Pull request by rrey**
##### SUMMARY

Module was not using the helpers, so an error occured in python3.

Fixes #49147

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

grafana_datasource.py

##### ADDITIONAL INFORMATION

Pushing for stable-2.7 because the module code changed a lot on devel and now use url_argument_spec() heper function.

### CODE REVIEW

**Comment by kbreit** [comment]
lgtm

**Comment by abadger** [comment]
The code and justification for why this is not going in devel look good.  This does need a changelog fragment before merging, though.  Please add one and then I'll get it merged. https://docs.ansible.com/ansible/latest/community/development_process.html?highlight=backport#backport-pull-request-process

**Comment by rrey** [comment]
@abadger I added the changelog portion
It is now mergeable

**Comment by abadger** [comment]
Thanks.  Merged for the 2.7.10 release :-)

**Pull request merged**
