### PR TITLE
[2.7] docker_container: fix various idempotency problems and non-working options

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This is a backport of #45905 to `stable-2.7`. It fixes various problems with idempotency and fixes some non-working options. It also includes basic idempotency tests for all options which modify container state. This PR also integrates #45747, which adds integration tests for `docker_container` in the first place (@gundalow suggested on IRC to include it with the backport PRs).

Note: there will be a merge conflict once #45769 is merged (or vice versa), since code was added at the same position. I can rebase once one of the PRs has been merged.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.7.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
40c51b858c211994cd81806eef149db1be780705 removes a regression test for the fix in backport PR #45769.

**Comment by abadger** [comment]
@felixfontein I've merged  #45769  and github is telling me this will merge without conflicts.  Is it safe to do so or do you need to rebase first?

**Comment by felixfontein** [comment]
@abadger Apparently git managed to resolve this by itself; though it organized the code slightly different than it is in `devel`. That shouldn't matter for functionality, but anyway I rebased and made sure it is as in `devel` :)
Once the tests pass it should be safe to merge.

**Comment by felixfontein** [comment]
(And once this is merged I'll also create backports for #46594 and #46595, which depend a lot on code changed in this PR.)

**Comment by mattclay** [comment]
needs_rebase

**Comment by felixfontein** [comment]
Restarting tests.

**Comment by mattclay** [comment]
@felixfontein The PR needs to be rebased to resolve a conflict first.

**Comment by felixfontein** [comment]
@mattclay I noticed (just a little after trying to retrigger the tests..)

**Comment by abadger** [comment]
Merged for the 2.7.1 release

**Pull request merged**
