### PR TITLE
Clarifiy the usage of env_file in the docker_container module

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Clarified the usage of `env_file` and provided an example of the same.

This is a new version of #42211, without merge commits. @ntwrkguru, the original author, agreed to have it resubmitted here.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.6.3
```

### CODE REVIEW

**Review by kassiansun — APPROVED** [review]

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
@kassiansun I guess you also have to shipit this :)

**Comment by kassiansun** [comment]
shipit

**Comment by felixfontein** [comment]
@kassiansun Thanks!

Actually, should I ping you when I see that a shipit from you would help to get something merged? Or do you want to find the PRs yourself?

**Comment by kassiansun** [comment]
Feel free to ping me if you find something I can help :)

**Pull request merged**
