### PR TITLE
cloud: ovirt: support add/remove tag from vms/hosts

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

This PR add a support to attach/detach a single tag from VMs or hosts.
More information can be found in https://github.com/ansible/ansible/issues/25746

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_tags

##### ANSIBLE VERSION

```
2.3.0
```

##### ADDITIONAL INFORMATION

```

```
This PR add two new states to `ovirt_tags` module. It's `attached` and `detached`.
The `attached` state will just attach the tag to the VMs/hosts, where the tag is not assigned, keeping the rest of the tags placed.

The `detached` state will just detach the tag from the VMs/hosts, where the tag is assigned, keeping the rest of the tags placed.

```yaml
# Attach a tag to VM 'vm1', keeping the rest already attached tags on VM:
- ovirt_tags:
    name: mytag
    state: attached
    vms:
      - vm3

# Detach a tag from VM 'vm1', keeping the rest already attached tags on VM:
- ovirt_tags:
    name: mytag
    state: detached
    vms:
      - vm3
```

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina @ryansb @julienvey

**Comment by julienvey** [comment]
Hi @machacekondra 

This solution looks better than what I initially thought we should do in #25746 . Great !

**Review by mwperina — APPROVED** [review]
👍

**Comment by machacekondra** [comment]
shipit

**Pull request merged**
