### PR TITLE
Add ovh_dns_zone_record module

### PR DESCRIPTION
**Pull request by hedii**
##### SUMMARY

This is a new module to manage OVH dns zone records.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

ovh_dns_zone_record

##### ADDITIONAL INFORMATION

It has ovh python package as a requirement.

### CODE REVIEW

**Comment by pascalheraud** [comment]
This module seems dupplicate of https://github.com/ansible/ansible/pull/48668

**Comment by gundalow** [comment]
@hedii Are you OK to close this PR and work on getting https://github.com/ansible/ansible/pull/48668 reviewed an merged?
@pascalheraud Thank you for spotting this

**Comment by hedii** [comment]
@gundalow yes, I close

**Comment by pascalheraud** [comment]
@gundalow is there any chance to get those PRs merged ? 
I have another OVH related PR waiting for review https://github.com/ansible/ansible/pull/34837

Cheers.

**Pull request closed without merging**
