### PR TITLE
Add Python 3.5 to tox.ini and Travis

### PR DESCRIPTION
**Pull request by mgedmin**

### CODE REVIEW

**Comment by abadger** [comment]
My tox and  travis experience is mostly trial and error but this change looks logical and the output looks like it is a good change.  I'm going to merge it.

Looking hard at the output I noticed that the integration tests are using the wrong version of python (probably the system version, python2.7, each time instead of the specific version that we're trying to test).  However, that seems to be happening before your changes as well so i'll open a separate issue for that until someone has a chance to look into it.

**Comment by abadger** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by mgedmin** [comment]
> Looking hard at the output I noticed that the integration tests are using the wrong version of python (probably the system version, python2.7, each time instead of the specific version that we're trying to test). 

On Travis, yes.  I noticed that while I was preparing this PR, and I was going to submit a fix once this one got merged.

I think it should be pretty simple to fix, using [something like this](https://github.com/pypa/pip/blob/develop/.travis.yml#L14-L15).

**Comment by mgedmin** [comment]
> i'll open a separate issue for that 

BTW did you open an issue?  I couldn't find it, but maybe by search powers are too puny.

**Pull request merged**
