### PR TITLE
PEP-8 fix: always compare with None using 'is' or 'is not'.

### PR DESCRIPTION
**Pull request by blair**
http://www.python.org/dev/peps/pep-0008/

  Comparisons to singletons like None should always be done with is or
  is not, never the equality operators.

  Also, beware of writing if x when you really mean if x is not None
  -- e.g. when testing whether a variable or argument that defaults to
  None was set to some other value. The other value might have a type
  (such as a container) that could be false in a boolean context!

### CODE REVIEW

**Comment by mpdehaan** [comment]
I actually disagree with the advice about "if not x", it's usually
true that you know what the value is and it's clearer.

This only really applies if you are overriding **cmp**

Generally I like to see "if x" and "if not x" everywhere -- far easier
to read, and the issue of testing for "" vs False or None doesn't
really come up... those values are all correctly False.

For this reason I'm declining this PR.

**Comment by mpdehaan** [comment]
Note github ate my formatting, expand to see the whole comment.

I sincerely appreciate the interest and the attention to detail, but stylistically this is not an improvement, nor do we have that risk with the above code.

I would consider changes to simply the None tests as I mentioned above.

Thanks!

**Comment by blair** [comment]
So to confirm, you would take a patch replacing

'if x == None' with 'if not x' and 'if x != None' with 'if x'?

**Comment by mpdehaan** [comment]
I would!

**Pull request closed without merging**
