### PR TITLE
Update playbooks_intro.rst

### PR DESCRIPTION
**Pull request by alberttwong**
##### SUMMARY

Updated yaml examples to include the syntactically correct YAML.    All YAML files should start with "---" and end with "...".

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by bcoca** [comment]
that is not a requirement, you only need that if you have multiple YAML documents in a file, which we do not support.

**Comment by alberttwong** [comment]
@bcoca It's in the EX407 cert test.   I didn't get 100% unless I did this.

**Comment by sivel** [comment]
Regardless of what is in the cert, it's definitely not required in order for ansible to operate.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by alberttwong** [comment]
@sivel That may be true it's not required for ansible to operate but we should be giving the best examples that is syntactically correct.   Anyhow, this POV isn't listed anywhere on ansible docs website so I'm submitting this PR as a help to the community at large and to any of the cert testers.  I feel that I've done my best effort to contribute.

**Comment by bcoca** [comment]
@alberttwong, I appreciate the effort, but I don't think that adding redundant 'document separators' is a best example to give users, both `---` and `...` are not needed nor required in YAML being fed into Ansible, I actually remove them when I edit examples that have them.

**Comment by tima** [comment]
@alberttwong We'll be taking this up with the Red Hat ertification exams team.

**Pull request closed without merging**
