### PR TITLE
Use atexit to logout after zabbix module run

### LINKED ISSUE #58459: Zabbix modules are leaving open sessions behind themselves
##### SUMMARY
Issue was first reported for zabbix_proxy module in #58066 and fix was proposed in #58393. 

However, this problem is present in all other zabbix_* modules too.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action
zabbix_group_info
zabbix_group
zabbix_host_info
zabbix_hostmacro
zabbix_host
zabbix_maintenance
zabbix_map
zabbix_mediatype
zabbix_screen
zabbix_template

##### ANSIBLE VERSION
```paste below
ansible 2.9.0.dev0
  config file = None
  configured module search path = [u'/home/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/root/dedefi-ansible-fork/lib/ansible
  executable location = /home/root/dedefi-ansible-fork/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### STEPS TO REPRODUCE
Run any zabbix module and then query Zabbix server database:
```bash
mysql> select * from sessions;
```

##### EXPECTED RESULTS
Zabbix module logouts first when exiting or throwing error.

##### ACTUAL RESULTS
Lots of opened sessions present in Zabbix server database.

```paste below
+----------------------------------+--------+------------+--------+
| sessionid                        | userid | lastaccess | status |
+----------------------------------+--------+------------+--------+
| fc4f10f67c6a8f76b8461e42fe07843c |      1 | 1561639244 |      0 |
| 965c13c7d37519837d40197300a4f431 |      1 | 1561639331 |      0 |
| 7a4871bd5dd34df9862d2505e49891d0 |      1 | 1561639383 |      0 |
| 4a3b398f85c93322916f9120c60c754a |      1 | 1561639630 |      0 |
| bddcc072fdfa3fb2f55ff3ab627bbf8a |      1 | 1561639838 |      0 |
| 874767447dcb381dc33bad41595b5d8d |      1 | 1561639931 |      0 |
| adc9d0d28469c33750340030b158b8d3 |      1 | 1561639932 |      0 |
| 941600e03959dfb484f2ecbdddfe23b8 |      1 | 1561639933 |      0 |
| 054dbde03f8b1bbc56115baa2594135a |      1 | 1561639934 |      0 |
| 206814f513e89412fa73f1f3ba79e241 |      1 | 1561640419 |      0 |
| f77e2bfac3e192a05ac9d8cc36b51c08 |      1 | 1561640420 |      0 |
| d8c471a2eaa38d1e5a692af357a6beca |      1 | 1561640421 |      0 |
| 935265d95a380586ded138e9148396a5 |      1 | 1561640422 |      0 |
| 03363aa51844d8dcfa912bc57a8c7050 |      1 | 1561640882 |      0 |

```

### PR DESCRIPTION
**Pull request by okgolove**
##### SUMMARY

Run zbx.logout() after every run.
Fixes #58459

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

zabbix_action
zabbix_group_info
zabbix_group
zabbix_host_info
zabbix_hostmacro
zabbix_host
zabbix_maintenance
zabbix_map
zabbix_mediatype
zabbix_screen
zabbix_template

### CODE REVIEW

**Comment by okgolove** [comment]
Hi @D3DeFi! I checked atexit.register() and it works properly: sessions have status **1** in a DB.

**Review by D3DeFi — APPROVED** [review]
Thank you for diving into this! Looks good

shipit

**Comment by okgolove** [comment]
I'm think someone from replied maintainers is needed.

**Comment by D3DeFi** [comment]
Yep. Always 2 module maintainers are required to vote if no core maintainer shows up. Ansibot haven’t mentioned me, because you have already done that. One more required.

@rubentsirunyan feel free to review and vote when you have time

**Review by rubentsirunyan — APPROVED** [review]
Thank you @okgolove!
shipit

**Comment by D3DeFi** [comment]
bot_status

**Comment by D3DeFi** [comment]
shipit

**Comment by D3DeFi** [comment]
bot_status

**Comment by D3DeFi** [comment]
@rubentsirunyan try now pls. It seems that it did not registered our votes previously

**Comment by rubentsirunyan** [comment]
shipit

**Comment by D3DeFi** [comment]
thank you all :)

**Pull request merged**
