### PR TITLE
[WIP] Integration tests for the 'default' callback plugin

### PR DESCRIPTION
**Pull request by agaffney**
##### SUMMARY
Integration tests for the `default` callback plugin

This commit also fixes an issue with the display of 'changed' tasks when
hiding 'ok' tasks that was found in the course of creating these tests.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
`lib/ansible/plugins/callback/default.py`

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (callback_default_integration_test 09c79d7d57) last updated 2018/08/12 21:34:40 (GMT -500)
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by agaffney** [comment]
FYI, @mattclay

**Comment by agaffney** [comment]
This is semi-dependent on #44068

**Comment by mattclay** [comment]
@agaffney Unless you really want to verify the ANSI sequences used in the output, it would be easier to maintain (and read) if you ran the tests with color output disabled.

**Comment by agaffney** [comment]
Closing this and moving work to #44068

**Pull request closed without merging**
