### PR TITLE
Add support for tox (http://tox.testrun.org/) and Travis CI (http://travis-ci.org/)

### PR DESCRIPTION
**Pull request by msabramo**
Passing Travis CI build for my fork: http://travis-ci.org/#!/msabramo/ansible/builds/1823490

To add support for Travis CI to your own GitHub repo, follow the instructions at http://about.travis-ci.org/docs/user/getting-started/ and then accept this pull request.

Sample tox output:

```
~/dev/git-repos/ansible$ tox
GLOB sdist-make: /Users/marca/dev/git-repos/ansible/setup.py
py26 sdist-reinst: /Users/marca/dev/git-repos/ansible/.tox/dist/ansible-0.6.zip
py26 runtests: commands[0]
test_complex_exclude (TestInventory.TestInventory) ... ok
test_complex_vars (TestInventory.TestInventory) ... ok
test_script (TestInventory.TestInventory) ... ok
test_script_all (TestInventory.TestInventory) ... ok
test_script_combined (TestInventory.TestInventory) ... ok
test_script_norse (TestInventory.TestInventory) ... ok
test_script_restrict (TestInventory.TestInventory) ... ok
test_script_vars (TestInventory.TestInventory) ... ok
test_simple (TestInventory.TestInventory) ... ok
test_simple_all (TestInventory.TestInventory) ... ok
test_simple_combined (TestInventory.TestInventory) ... ok
test_simple_exclude (TestInventory.TestInventory) ... ok
test_simple_norse (TestInventory.TestInventory) ... ok
test_simple_port (TestInventory.TestInventory) ... ok
test_simple_restrict (TestInventory.TestInventory) ... ok
test_simple_ungrouped (TestInventory.TestInventory) ... ok
test_simple_vars (TestInventory.TestInventory) ... ok
test_yaml (TestInventory.TestInventory) ... ok
test_yaml_all (TestInventory.TestInventory) ... ok
test_yaml_change_vars (TestInventory.TestInventory) ... ok
test_yaml_combined (TestInventory.TestInventory) ... ok
test_yaml_host_vars (TestInventory.TestInventory) ... ok
test_yaml_list_vars (TestInventory.TestInventory) ... ok
test_yaml_multiple_groups (TestInventory.TestInventory) ... ok
test_yaml_norse (TestInventory.TestInventory) ... ok
test_yaml_port (TestInventory.TestInventory) ... ok
test_yaml_restrict (TestInventory.TestInventory) ... ok
test_yaml_ungrouped (TestInventory.TestInventory) ... ok
test_yaml_vars (TestInventory.TestInventory) ... ok
test_parse_kv_basic (TestUtils.TestUtils) ... ok
test_template_basic (TestUtils.TestUtils) ... ok
test_template_unicode (TestUtils.TestUtils) ... ok
test_template_varReplace_iterated (TestUtils.TestUtils) ... ok
test_template_whitespace (TestUtils.TestUtils) ... ok
test_varLookup_list (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative2 (TestUtils.TestUtils) ... ok
test_varReplace_alternative (TestUtils.TestUtils) ... ok
test_varReplace_alternative_greed (TestUtils.TestUtils) ... ok
test_varReplace_caps (TestUtils.TestUtils) ... ok
test_varReplace_invalid_list (TestUtils.TestUtils) ... ok
test_varReplace_list (TestUtils.TestUtils) ... ok
test_varReplace_list_nolist (TestUtils.TestUtils) ... ok
test_varReplace_list_oob (TestUtils.TestUtils) ... ok
test_varReplace_middle (TestUtils.TestUtils) ... ok
test_varReplace_multiple (TestUtils.TestUtils) ... ok
test_varReplace_nested (TestUtils.TestUtils) ... ok
test_varReplace_nested_int (TestUtils.TestUtils) ... ok
test_varReplace_nested_list (TestUtils.TestUtils) ... ok
test_varReplace_notcomplex (TestUtils.TestUtils) ... ok
test_varReplace_simple (TestUtils.TestUtils) ... ok
test_varReplace_unicode (TestUtils.TestUtils) ... ok

----------------------------------------------------------------------
Ran 52 tests in 0.996s

OK
py27 sdist-reinst: /Users/marca/dev/git-repos/ansible/.tox/dist/ansible-0.6.zip
py27 runtests: commands[0]
test_complex_exclude (TestInventory.TestInventory) ... ok
test_complex_vars (TestInventory.TestInventory) ... ok
test_script (TestInventory.TestInventory) ... ok
test_script_all (TestInventory.TestInventory) ... ok
test_script_combined (TestInventory.TestInventory) ... ok
test_script_norse (TestInventory.TestInventory) ... ok
test_script_restrict (TestInventory.TestInventory) ... ok
test_script_vars (TestInventory.TestInventory) ... ok
test_simple (TestInventory.TestInventory) ... ok
test_simple_all (TestInventory.TestInventory) ... ok
test_simple_combined (TestInventory.TestInventory) ... ok
test_simple_exclude (TestInventory.TestInventory) ... ok
test_simple_norse (TestInventory.TestInventory) ... ok
test_simple_port (TestInventory.TestInventory) ... ok
test_simple_restrict (TestInventory.TestInventory) ... ok
test_simple_ungrouped (TestInventory.TestInventory) ... ok
test_simple_vars (TestInventory.TestInventory) ... ok
test_yaml (TestInventory.TestInventory) ... ok
test_yaml_all (TestInventory.TestInventory) ... ok
test_yaml_change_vars (TestInventory.TestInventory) ... ok
test_yaml_combined (TestInventory.TestInventory) ... ok
test_yaml_host_vars (TestInventory.TestInventory) ... ok
test_yaml_list_vars (TestInventory.TestInventory) ... ok
test_yaml_multiple_groups (TestInventory.TestInventory) ... ok
test_yaml_norse (TestInventory.TestInventory) ... ok
test_yaml_port (TestInventory.TestInventory) ... ok
test_yaml_restrict (TestInventory.TestInventory) ... ok
test_yaml_ungrouped (TestInventory.TestInventory) ... ok
test_yaml_vars (TestInventory.TestInventory) ... ok
test_parse_kv_basic (TestUtils.TestUtils) ... ok
test_template_basic (TestUtils.TestUtils) ... ok
test_template_unicode (TestUtils.TestUtils) ... ok
test_template_varReplace_iterated (TestUtils.TestUtils) ... ok
test_template_whitespace (TestUtils.TestUtils) ... ok
test_varLookup_list (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative2 (TestUtils.TestUtils) ... ok
test_varReplace_alternative (TestUtils.TestUtils) ... ok
test_varReplace_alternative_greed (TestUtils.TestUtils) ... ok
test_varReplace_caps (TestUtils.TestUtils) ... ok
test_varReplace_invalid_list (TestUtils.TestUtils) ... ok
test_varReplace_list (TestUtils.TestUtils) ... ok
test_varReplace_list_nolist (TestUtils.TestUtils) ... ok
test_varReplace_list_oob (TestUtils.TestUtils) ... ok
test_varReplace_middle (TestUtils.TestUtils) ... ok
test_varReplace_multiple (TestUtils.TestUtils) ... ok
test_varReplace_nested (TestUtils.TestUtils) ... ok
test_varReplace_nested_int (TestUtils.TestUtils) ... ok
test_varReplace_nested_list (TestUtils.TestUtils) ... ok
test_varReplace_notcomplex (TestUtils.TestUtils) ... ok
test_varReplace_simple (TestUtils.TestUtils) ... ok
test_varReplace_unicode (TestUtils.TestUtils) ... ok

----------------------------------------------------------------------
Ran 52 tests in 0.874s

OK
_________________________________________________________________________ summary __________________________________________________________________________
  py26: commands succeeded
  py27: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Nice.

I'm not going to keep these in tree, but you're welcome to host them in another repo or something and tell the list about them.

**Comment by lorin** [comment]
If they were in the tree, we'd get unit tests run automatically on every pull request. Is there an easy way to automate that functionality some other way?

**Comment by msabramo** [comment]
Travis CI is the easiest way I know to accomplish that. 

If it were me, I'd probably also add the tox.ini and then change the tests Makefile target to call tox instead of nosetests. Then `make tests` tests against both 2.6 and 2.7 which most people probably wouldn't think to do otherwise.

**Comment by mpdehaan** [comment]
I really don't see the point in supporting test framework of the week here.   We have /some/ unit and integration level tests, I'd like to see those expanded first.

**Comment by lorin** [comment]
Travis isn't a test framework, it's a CI framework, like Jenkins. Have you taken a look at the proposed config file at  https://github.com/msabramo/ansible/commit/7877199debb74f85768705ba64d69d1d58934a00

**Comment by mpdehaan** [comment]
(A) I was referring to tox.

And (B) no time.

**Comment by msabramo** [comment]
Tox also isn't a test framework. It just runs the tests that you tell it to run (unittest, nose, py.test, custom scripts, whatever) in all of the Python versions that you specify. At its core it basically creates virtualenvs and installs and runs stuff in them. 

It amplifies the value of whatever tests you have, by encouraging people to run their tests with multiple Python versions. So you are more likely to quickly discover a change that breaks compatibility in versions that people aren't in the habit of using. 

As far as time, I don't see this taking much time, since I provided the `tox.ini`. I guess there might be a little bit of tweaking the `tox.ini` on occasion, so I guess that's what you're referring to. I personally think the benefits outweigh the time investment but that's totally your call to make. The only reason I replied was just in case you were misunderstanding what tox is (maybe you thought that it's a framework that changes the way you write tests). Ultimately if you don't want it in your tree, that's your choice of course and I will stop talking about it.

**Comment by mpdehaan** [comment]
I'm aware of what tox is.

Not interested.

**Comment by lorin** [comment]
If the problems with this proposal is the addition of tox and travis taking too long to set up, I can submit a new pull request that just has the travis support, and instructions for how to enable the repo so that travis will poll it and run the tests. It takes about 5 minutes to set this up.

**Comment by lorin** [comment]
Submitted pull request #1716 for travis only.

**Comment by mpdehaan** [comment]
I really don't care about travis and don't want the file in the root
directory.

**Pull request closed without merging**
