### PR TITLE
Adding hdfs file module and hdfsbase module_utils

### PR DESCRIPTION
**Pull request by yassineazzouz**
##### ISSUE TYPE
 - Feature Pull Request
 - New Module Pull Request

##### COMPONENT NAME
hdfsfile

##### ANSIBLE VERSION
```
ansible 2.3.0
```

##### SUMMARY
The following is a hdfs file module and a library functions in module_utils to create similar hdfs modules. I have been working on multiple hdfs modules for a while and they helped a lot to automated much of my operational tasks on large scale hadoop clusters specially when working with multiple clusters deployments. I would be very happy to share them and make them part of the ansible core modules. The modules are well tested and I believe they are stable enough to be part of ansible.
For the scope of this PR pushed one module : hdfsfile module. hdfsfile acts exactly like the file module on a hdfs filesystem, the usage and arguments are exactly the same, with some additional parameters for hdfs authentication.
```
- hosts: localhost
  vars:
    nameservices:
      - urls: "http://localhost:50070"
        mounts: "/"
  tasks:
    - name: Create HDFS user home directory
      hdfsfile:
        authentication: "none"
        state: "directory"
        path: "/user/ansible"
        owner: "ansible"
        group: "supergroup"
        mode: "0700"
        nameservices: "{{nameservices | to_json}}"
```
I tried to keep the code clean and well documented please let me know what you think.  
Thanks,

### CODE REVIEW

**Comment by bcoca** [comment]
we only take 1 module per PR, for your first submission I would concentrate on 1 module and once that one has been iterated and it is clear what we look for, you can submit the rest.

**Comment by yassineazzouz** [comment]
Hi @bcoca ,
Should I keep the same pull request and reduce it to one module  or I can make new one ? Actually the modules share some code in module utils, so I can modify the PR to keep the shared code along with one module. Is that ok ? 
Thanks,

**Comment by bcoca** [comment]
Yes, keep the common code, you can also keep PR, this is the one time you can 'force push' with git.

**Comment by yassineazzouz** [comment]
Hi @bcoca ,

I modified the pull request to keep one module : hdfsfile. It is a module that does exactly the same thing as the file module on a hdfs file system. I also kept the module utils for hdfs as a base that can be used for other hdfs modules.

Thanks,

**Comment by yassineazzouz** [comment]
Hi @bcoca ,

Based on the code adjustments I had to do, I guess you were absolutely right about the fact that I needed to commit one module at a time :). The checks are really good, I had to do some adjustments to support all python versions (my development was more Python 2.7), I did some additional tests on python 2.4, 3.1 and 3.5. It looks good to me. Please let me if you think there is anything else I need to fix :).

Thanks,

**Comment by timoninmaxim** [comment]
Hello!
Now I'm looking for a module for managing files in hdfs and this module does exactly what I need. Is there any info about the module? Could I help to speed up it?

**Comment by Akasurde** [comment]
@yassineazzouz Are you still working on this ? Thanks

needs_info

**Pull request closed without merging**
