### PR TITLE
fix camel_dict_to_snake_dict() ignore_list bug

### PR DESCRIPTION
**Pull request by omonnig**
SUMMARY
camel_dict_to_snake_dict() ignore_list functionality does not work for JSON keys below the top level. When working with IAM objects, the camel to snake conversion corrupts IAM Policy statements.

ISSUE TYPE
Bug Report
COMPONENT NAME
ansible/lib/ansible/module_utils/common/dict_transformations.py function: camel_dict_to_snake_dict()

ANSIBLE VERSION
  ansible 2.8.1
  config file = None
  configured module search path = ['/Users/xxxxxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
CONFIGURATION
no output
OS / ENVIRONMENT
System Version:	macOS 10.14.5 (18F132) Kernel Version:	Darwin 18.6.0 Boot Volume:	Macintosh HD Boot Mode:	Normal

STEPS TO REPRODUCE
camel_dict_to_snake_dict() ignore_list functionality does not work for JSON keys below the top level

The attached files illustrate the behavior and the code required to fix. I intend to submit a pull request in the near future.

EXPECTED RESULTS
The attached file test-fixed.py outputs the correct values - all JSON keys below AssumeRolePolicyDocument are not modified.

ACTUAL RESULTS
The attached file test-issue.py outputs the incorrect values - all JSON keys below AssumeRolePolicyDocument are not converted to snake dict from camel dict.

All files in this gist:
https://gist.github.com/omonnig/a3c5ad8ba495ca4e93e651ac588f0aa0

### CODE REVIEW

**Comment by omonnig** [comment]
I have additional AWS IAM modules to commit that are dependent upon this bug being fixed.  Thanks!

**Comment by samdoran** [comment]
cc @jillr @willthames

**Comment by willthames** [comment]
Thanks @omonnig - I'd also suggest it might be worth adding a test case or two to test/units/module_utils/common/test_dict_transformations.py  (I didn't realise we didn't have tests for camel_dict_to_snake_dict or snake_dict_to_camel_dict, only the underlying functions they rely upon)

**Comment by s-hertel** [comment]
@omonnig Changing this would break things relying on the current behavior. `ignore_list` was mainly implemented as a way to not convert the top level `tags` for a resource, and was not recursive intentionally. I recently added some tests for the expectation in https://github.com/ansible/ansible/pull/72028. `camel_dict_to_snake_dict` should take a resource dict, rather than a resource dict nested in a message and list of resources. For your example (and to follow the pattern of other AWS info modules that return multiple resources) you should do something like:
`output = {'msg': [camel_dict_to_snake_dict(role, ignore_list=ignore) for role in test_json['msg']['Roles']]}`

If you have further questions please stop by IRC or the mailing list:

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
