### PR TITLE
uri module enforces Headers in camel-case (explicit the documentation)

### PR DESCRIPTION
**Pull request by axel3rd**
##### SUMMARY

Origin: [adapter-aws-lambda-serverless #62](https://github.com/probot/adapter-aws-lambda-serverless/issues/62).

`uri` module enforce headers written in camel-case, even if filled otherwise (and written as filled in the debug logs).

The documentation should explicit that, avoiding tricky troubleshooting.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

uri

##### ADDITIONAL INFORMATION

Proof:

1. Create a [Python server which dump request](https://gist.github.com/phrawzty/62540f146ee5e74ea1ab) which listen on 8000 port
1. Write simple playbook and execute it
```paste below
- name: Test
  hosts: localhost
  tasks:
  - name: Headers Proof
    uri:
      url: http://localhost:8000
      headers:
        X-SoMe-HeADer: FaKe-VaLue
```

Output produced:
```shell
Host: localhost:8000
X-Some-Header: FaKe-VaLue
Connection: close
User-Agent: ansible-httpget
```

### CODE REVIEW

**Comment by sivel** [comment]
This is an implementation detail of how python transmits headers.  We have no control over this behavior, and since it is an implementation detail which could change, and the RFC states that headers are case insensitive, I don't think this isn't something we should document.

**Comment by axel3rd** [comment]
@sivel : I understand the point of view. 

But for avoid some lost of time in this kind of troubleshooting (They are written not modified in `-vvv` logs ^^), having a word about that somewhere could help IMO.

Perhaps adding a *note* could be relevant ?

https://github.com/ansible/ansible/blob/11f1177e6c5b823ca8acbd8877b2ce91afddc382/lib/ansible/modules/uri.py#L195-L198

```
 notes: 
   - The dependency on httplib2 was removed in Ansible 2.1. 
   - The module sends all the HTTP headers in camel-case. 
   - The module returns all the HTTP headers in lower-case. 
   - For Windows targets, use the M(ansible.windows.win_uri) module instead. 
```

?

**Comment by sivel** [comment]
The problem is that the behavior is dictated by Python, and it's not considered a feature, it's an implementation detail. The behavior is not mentioned at all in the Python docs.  Get python to commit to it being a feature, and documenting the behavior, and I'd be open to accepting docs that point to that and convey it here.

Basically what I am saying, is that until python commits to that behavior being stable and documents it, we shouldn't either, because it should not be relied on as stable, and could change.

**Comment by axel3rd** [comment]
I will try to manage this strategy/documentation point in Python ecosystem.

**Comment by jborean93** [comment]
Closing as per the above, please reopen the PR if you get any response back from the CPython team.

**Comment by axel3rd** [comment]
For history: Python bug [issue43331](https://bugs.python.org/issue43331) / PR [24661](https://github.com/python/cpython/pull/24661).

**Pull request closed without merging**
