### PR TITLE
fix typo.

### PR DESCRIPTION
**Pull request by argsno**
##### SUMMARY
Fix a typo in bin/ansible comments.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
bin/ansible

##### ANSIBLE VERSION
devel branch

##### ADDITIONAL INFORMATION
Minor typo in docs. Apologies for such a small PR.

### CODE REVIEW

**Review by Akasurde — APPROVED** [review]
shipit

**Comment by Akasurde** [comment]
Can you format patch according ansibot suggestion ?

**Comment by argsno** [comment]
@Akasurde  OK

**Comment by bcoca** [comment]
you seem to have an extra commit here

**Pull request merged**
