### PR TITLE
Add guide for Packet host

### PR DESCRIPTION
**Pull request by t0mk**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

- docs/docsite/rst/guide_packet.rst

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel db8fd95d68) last updated 2017/02/06 13:52:33 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

This PR adds a Detailed Guide for the Packet host (https://packet.net). It showcases using modules and dynamic inventory.

It looks like this:
http://imgur.com/a/cDAyQ

Correctness of a small part of this guide is dependent on https://github.com/ansible/ansible/pull/21069.

### CODE REVIEW

**Comment by dsieczko** [comment]
I'm with Packet - looks good to me!

**Review by gundalow — CHANGES_REQUESTED** [review]
Hi
Can you please use the headings as details on this page
http://openalea.gforge.inria.fr/doc/openalea/doc/_build/html/source/sphinx/rest_syntax.html#headings

I know we haven't been that consistent with out existing docs, though we are trying to fix that.

**Comment by t0mk** [comment]
@gundalow thanks for the review, I am ready to fix it. But I don't understand what should be the top-level heading for the guide.

What should be the top-level heading of the guide in terms of the doc that you've linked? "part", "chapter", or "section"? I assume it's not "section" because that's the current top-level heading (just like in the existing guides).

**Comment by gundalow** [comment]
@t0mk sure, the wording in that guide isn't totally clear.

Basically

```
*****
Title
*****


subtitle
########

subsubtitle
***********

subsubsubtitle
===========

etc
```


So in your case

```
***************************************
Using Ansible with the Packet host
***************************************

Introduction
##########

```
Number of `*` and `#` may not be correct in the above example, but you get the idea

**Comment by t0mk** [comment]
@gundalow thanks, but those instructions are still quite ambiguous. According to 
https://docs.python.org/devguide/documenting.html#sections

The "#" is for parts, "*" for chapters and "=" for sections; leftmost highest in the hierarchy.

I fixed it in the same way as in this tutorial in the official python docs:
https://raw.githubusercontent.com/python/cpython/master/Doc/tutorial/inputoutput.rst

.. having the title of the guide as "chapter" (with asterisks and overline) and the sub-headings as "sections" (with equal signs). I hope it's OK.

**Comment by t0mk** [comment]
ready_for_review

**Comment by t0mk** [comment]
@gundalow, are the ReSTructured Text headings fine now? You were not happy with the heading syntax in this submitted guide. I fixed it in commit
https://github.com/ansible/ansible/pull/21346/commits/7bd0492181a61eccc37b817e833830e6cd9278b4

The headings with fixed syntax can be seen in the diff of this PR:
https://github.com/ansible/ansible/pull/21346/files#diff-e1f425ed754f58f3bb2c3c6f46b186ae 

I never really understood the ReST heading syntax, but did my best. My reasoning is explained in
https://github.com/ansible/ansible/pull/21346#issuecomment-284427664

**Comment by vielmetti** [comment]
I'd like to see this merged in, thanks.

**Comment by gundalow** [comment]
Closing and reopening to retrigger CI

Note to self: for `devel` & `stable-2.3`

**Comment by gundalow** [comment]
Looks like there are some rst issues
```
rstcheck --report warning --ignore-substitutions version,versiondev docs/docsite/rst/guide_packet.rst docs/docsite/rst/guides.rst

docs/docsite/rst/guide_packet.rst:199:0: (bash) `tomk@work $ ssh -i id_rsa core@<one_of_the_servers_ip>'
docs/docsite/rst/guide_packet.rst:199:0: (bash) syntax error near unexpected token `newline'
docs/docsite/rst/guide_packet.rst:285:0: (json) Expecting property name enclosed in double quotes: line 53 column 1 (char 1735)
```

**Comment by t0mk** [comment]
Thanks for reopening this. I will fix the rst problem.

**Comment by t0mk** [comment]
@gundalow it's fixed. Please let me know if there's something else I can do to make this merged!

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel` and cherry picked into `stable-2.3` https://github.com/ansible/ansible/commit/c84a3325311d6128065ca3fb4326d42490db60e9

Soon we will have versioned documentation, which is why I've backported this into `stable-2.3`

**Comment by dharmabumstead** [comment]
Awesome work - thanks @t0mk and @gundalow!

**Comment by t0mk** [comment]
Great! When do you think I can see the regenerated docs on docs.ansible.com?

**Comment by gundalow** [comment]
@t0mk @dsieczko It's live http://docs.ansible.com/ansible/guide_packet.html

Thanks for adding this.

**Comment by vielmetti** [comment]
I'm running 2.3.0.0 from Homebrew on my Mac, and get this error:

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:46:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

```
emv$ ansible-playbook 2a-playbook.yml 
 [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [create ubuntu 2a device] ***************************************************

TASK [Gathering Facts] ***********************************************************
ok: [localhost]

TASK [packet_sshkey] *************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "packet required for this module"}
	to retry, use: --limit @/Users/emv/src/vielmetti/ansible-2a/2a-playbook.retry

PLAY RECAP ***********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```

It's possible this issue needs to be separate with the Homebrew crew, but thought I'd report it here to make sure that if there's an error message that needs to be added to the docs it can be.

**Comment by vielmetti** [comment]
My problem was that I had too many versions of Python on my machine, and the one that had "pip install" was different from the one that ran ansible-playbook. Not any problem with this code.

**Comment by gundalow** [comment]
If there are any bugs please create a fresh issue and `@mention` the people above. 

This PR is now closed as its been merged

**Pull request merged**
