### PR TITLE
Revert "Doc notes 4"

### PR DESCRIPTION
**Pull request by yuandongx**
Reverts ansible/ansible#64349
##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by hwDCN** [comment]
shipit

**Comment by hwDCN** [comment]
bot_status

**Comment by hwDCN** [comment]
-label: needs_info

**Comment by xuxiaowei0512** [comment]
-label: needs_info

**Comment by xuxiaowei0512** [comment]
bot_status

**Pull request merged**
