### PR TITLE
apt_key: implemented option to receive key from keyserver

### LINKED ISSUE #4810: apt_key module to behave like apt-key
Hi, 

as mentionned on the mailing list, it would it be great for apt_key module to behave like apt-key. For instance, adding a "keyserver" parameter, because sometimes there is no url to download from. This line is valid (and fully working) under my ubuntu :

``` bash
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 3D3B6BD098080A60
```

It would be great to write something similar in ansible :

``` yaml
- name: Download collectd public key for apt
  apt_key: keyserver=http://keyserver.ubuntu.com
  id=3D3B6BD098080A60 state=present
```

Today, I have to write this:

``` yaml

- name: Download collectd public key for apt
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x3D3B6BD098080A60
  state=present
```

BTW, my ansible version is :

``` bash
$ ansible --version
ansible 1.3.1
```

(related to #4544)

### PR DESCRIPTION
**Pull request by resmo**
This closes #4810 and #5485. 

Implementation is straight forward, works for me. Would appreciate feedback.

### CODE REVIEW

**Comment by sbocahu** [comment]
Cool. However: Long IDs are accepted by apt-key --recv, but apt-key list shows short, capitalized hex format only. Other formats (long & lowercase) should be checked correctly by the module as well.

Also, key_present() seems to not be used at all, and could be removed.

**Comment by astorije** [comment]
Any news/ETA about integrating this PR to Ansible?

**Comment by resmo** [comment]
I rebased, fixed merge conflicts with current devel branch. @zecrazytux this problem is general problem and not only related to this PR. Could you please file a new bug?

I do not remove key_present() in this PR because not related to the change, this should also be cleaned up in the new bug mentioned before.

**Comment by sbocahu** [comment]
This is already implemented, see mpdehaan's last comment on #5485
id=KEYID keyserver=KEYSERVER

**Comment by mpdehaan** [comment]
# Revision Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We'd like to see a few things tweaked if you don't mind.  If you can help resolve these items, we'd greatly appreciate it:
- this PR seems to conflict with the current upstream codebase and may need a "git pull --rebase"
- please let me know what you think of the current keyserver parameter handling on 1.7/1.8 and whether this is resolveable already or changes are still warranted.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by mpdehaan** [comment]
Hi!

We believe that commits in Ansible 1.6 should resolve this question or problem for you.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
