### PR TITLE
[WIP] psrp - persistent connection tests

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Test branch of https://github.com/ansible/ansible/pull/41729 that tries out persistent connections.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
psrp

##### ANSIBLE VERSION
```
devel
```

### CODE REVIEW

**Comment by mcassaniti** [comment]
Any movement here? I wasn't sure if persistent connections would be enabled by default or not with the PSRP connection module.

**Comment by jborean93** [comment]
@mcassaniti unfortunately no. The base psrp connection plugin has been merged into devel but we've been unable to identify why this persisted branch takes a longer time to run compared to a non persisted connection. I'm still hopefully to get it working and get some other speed improvements but right now psrp is based on a non-persisted connection process.

**Comment by mcassaniti** [comment]
@jborean93 Thank you very much for the feedback.

**Comment by jborean93** [comment]
This didn't lead anywhere, closing.

**Pull request closed without merging**
