### PR TITLE
K8s dynamic collected changes

### PR DESCRIPTION
**Pull request by fabianvf**
##### SUMMARY

merging of https://github.com/ansible/ansible/pull/39632 and https://github.com/ansible/ansible/pull/40635

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by maxamillion** [comment]
@fabianvf CI is angry, please make it happy :)

```
lib/ansible/modules/storage/glusterfs/gluster_volume.py:0:0: E322 "volume" is listed in the argument_spec, but not documented in the module
```

**Comment by maxamillion** [comment]
Just kidding, that failure is unrelated. I got my wires crossed.

**Comment by fabianvf** [comment]
@maxamillion Current failures look like issues installing supervisor, unrelated to this PR

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by maxamillion** [comment]
CI has been angry because of issues not related to this PR, but should be fixed now. Let's try again.

rebuild_merge

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
nevermind, the CI keeps failing on something completely unrelated. merging

**Comment by maxamillion** [comment]
nevermind, the CI keeps failing on something completely unrelated. merging

**Pull request merged**
