### PR TITLE
Remove unused import from azure dyn inventory

### PR DESCRIPTION
**Pull request by pmarques**
##### SUMMARY

Remove unused import from azure_rm dynamic inventory

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

contrib/inventory/azure_rm.py

##### ADDITIONAL INFORMATION

The module is importing a package that is not used and not installed by default.

### CODE REVIEW

**Comment by yuwzho** [comment]
shipit

**Review by zikalino — APPROVED** [review]

**Comment by zikalino** [comment]
shipit

**Comment by yuwzho** [comment]
bot_status

**Comment by yuwzho** [comment]
shipit

**Comment by yuwzho** [comment]
bot_status

**Comment by yuwzho** [comment]
bot_broken

**Comment by zikalino** [comment]
shipit

**Review by yuwzho — APPROVED** [review]

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
