### PR TITLE
Added support for generating OTP tokens using filters

### PR DESCRIPTION
**Pull request by rosmo**
##### SUMMARY
Adds two new filters: secret|totp_token() and secret|hotp_token(at=0). Requires PyOTP and complains if it's not installed.

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/filter/otp.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by rosmo** [comment]
I think a better place this would be Galaxy, but I don't think it supports filters.

**Comment by bcoca** [comment]
The would work in a role within a filter_plugins directory

**Comment by rosmo** [comment]
Yeah, but no one will find it if I just stick it in some random repository and might be discouraged to use 2FA.

**Comment by rosmo** [comment]
Ahh, now I understand, you mean a dummy role in Galaxy? That's a good solution!

**Comment by bcoca** [comment]
still, this might merit inclusion here, just not sure what the use case is as ansible cannot really currently use 2FA

**Comment by rosmo** [comment]
I haven't tried but I thought you could use "environment" to set AWS_SECURITY_TOKEN to use 2FA authentication with Amazon modules (and other modules).

**Comment by bcoca** [comment]
how would you handle token expiration and reauthentication requests? <= this is the big problem that prevents us from adding this everywhere.

**Comment by jctanner** [comment]
bot_status

**Comment by jstoja** [comment]
@jctanner Any idea for this PR?

**Comment by jctanner** [comment]
@jstoja No I don't have any plans to move this forward. The author needs to rebase and push it over the line by putting it on a community meeting agenda, or someone else needs to take over the work.

**Comment by gundalow** [comment]
Given https://github.com/ansible/ansible/pull/12272#issuecomment-139379544

> how would you handle token expiration and reauthentication requests? <= this is the big problem that prevents us from adding this everywhere.

I think this should be closed

**Pull request closed without merging**
