### PR TITLE
Module to maintain the DNS entry for a hostname using nsupdate+nslookup.

### PR DESCRIPTION
**Pull request by adq**
Hi, me again I'm afraid :)

This module maintains the DNS forward and reverse entries for a hostname using nsupdate + nslookup.

### CODE REVIEW

**Comment by jpmens** [comment]
Have you seen this https://github.com/jpmens/ansible-m-dnsupdate ?

**Comment by jpmens** [comment]
No offence, and please pardon my saying so, but nslookup sucks (it can lie) and embedding that into an Ansible module, well, no.

At the very least, you should replace that with `dig`.

**Comment by adq** [comment]
hey no offence, if nslookup sucks, it sucks :) 

Is that module going into the core ansible?

**Comment by jpmens** [comment]
It wasn't taken at the time, for being too specialized, but you can, of course, drop it into your own library/ ;-)

**Comment by jpmens** [comment]
BTW, other than the use of `nslookup`, what I like about this is it uses external binary `nsupdate` instead of requiring dnspython, which IMO makes it more suitable for Ansible core.

**Comment by adq** [comment]
Cool: will port it to use dig then!

**Comment by jpmens** [comment]
Another BTW: your `dnsserver` parameter is required, but shouldn't be. RFC 2136 updates the MNAME (i.e. the master server specified in a zone's SOA record.)

**Comment by jpmens** [comment]
Another nit (sorry: I'm not really paying enough attention). Documentation needs updating that you're adding/deleting PTR RR for the A as well.

I'd like to suggest you make this a bit more granular: allow update of any RRtype. Thus a thought. _ends_ ;-)

**Comment by adq** [comment]
Hi, I've updated it to use dig and changed the docs.

Those are good points about turning it into a generic DNS update module, and the dnsdomain being non-optional... However, both of those are outside my use case and I don't have the time to develop something more general right now. Maybe later though.

**Comment by mpdehaan** [comment]
Stylistically, ansible arguments should be with_underscores not withoutspaces and functions should be with_underscores and not inCamelCase

@jpmens any further comments

I am somewhat inclined to _not_ include this in core, without understanding the underlying use cases or playbooks this is used in, and what DNS servers this works with and those it does not.

I'm open to education, however.

**Comment by jpmens** [comment]
This module ought to work with servers which support Dynamic DNS Updates (RFC 2136). Currently that's BIND, Knot, YADIFA, and since a few days, PowerDNS.

Admittedly, and @mpdehaan we had this discussion a while back, it's probably not going to be used by a lot of people, that was IIRC the quintescense, when we made https://github.com/jpmens/ansible-m-dnsupdate

**Comment by jimi-c** [comment]
This looks good, however there is one programming error:

<pre>
         module.fail_json(msg="Failed to query DNS", rc=rc, err=err)
 
     if len(out.split('\n')) > 0:
-        return out.split('\n').strip()
+        return out.strip().split('\n')
 
     return None
 
</pre>

Also, this module should check first to see if the requested DNS/rDNS match what is being requested, and only change it if it is different. As it stands right now, this module is not idempotent.

Please fix the above issues and resubmit when it's ready. Thanks!

**Pull request closed without merging**
