### PR TITLE
Add parent_groups and child_groups magic variables

### PR DESCRIPTION
**Pull request by oboukili**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

```
lib/ansible/inventory/__init__.py
lib/ansible/vars/__init__.py
lib/ansible/vars/hostvars.py
```
##### ANSIBLE VERSION

```
ansible 2.3.0 (f/more_magicvars 8236e0aabe) last updated 2016/10/13 17:06:07 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 275fa3f055) last updated 2016/10/13 16:43:43 (GMT +200)
  lib/ansible/modules/extras:  not found - use git submodule update --init lib/ansible/modules/extras
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added parent_groups and child_groups magic variables to access direct children/parents groups.
Those lists were already exposed in the group class.

**Example inventory**

```
[toplevel:children]
somesublevel
anothersublevel

[somesublevel:children]
bottomlevel

[anothersublevel:children]
bottomlevel

[bottomlevel]
localhost
```

**Example playbook**

```

---
- hosts: toplevel
  connection: local
  gather_facts: false
  tasks:
    - debug: var=child_groups['toplevel']
    - debug: var=parent_groups['toplevel']

- hosts: somesublevel
  connection: local
  gather_facts: false
  tasks:
    - debug: var=child_groups['somesublevel']
    - debug: var=parent_groups['somesublevel']

- hosts: anothersublevel
  connection: local
  gather_facts: false
  tasks:
    - debug: var=child_groups['anothersublevel']
    - debug: var=parent_groups['anothersublevel']

- hosts: bottomlevel
  connection: local
  gather_facts: false
  tasks:
    - debug: var=child_groups['bottomlevel']
    - debug: var=parent_groups['bottomlevel']
...
```

**ansible-playbook output:**

```
PLAY [toplevel] ****************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "child_groups['toplevel']": [
        "somesublevel", 
        "anothersublevel"
    ]
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "parent_groups['toplevel']": [
        "all"
    ]
}

PLAY [somesublevel] ************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "child_groups['somesublevel']": [
        "bottomlevel"
    ]
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "parent_groups['somesublevel']": [
        "toplevel"
    ]
}

PLAY [anothersublevel] *********************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "child_groups['anothersublevel']": [
        "bottomlevel"
    ]
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "parent_groups['anothersublevel']": [
        "toplevel"
    ]
}

PLAY [bottomlevel] *************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "child_groups['bottomlevel']": []
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "parent_groups['bottomlevel']": [
        "somesublevel", 
        "anothersublevel"
    ]
}
```

### CODE REVIEW

**Comment by alexandrezfs** [comment]
worksforme

**Comment by mwerlen** [comment]
:+1: Works for me on Fedora 23.

**Comment by gundalow** [comment]
Rebase needed

**Comment by gdepuille** [comment]
@gundalow rebase done.

**Comment by oboukili** [comment]
@gdepuille could you do the rebase? I would need this PR to be merged in hte very near future :) (or you could transfer the PR back to me if you wish!)
Cheers,

**Comment by bcoca** [comment]
A few of things things:
- First, new 'magic vars' should be `ansible_` namespaced.
- Also, groups can be both parent and child at the same time, one or neither, I'm not sure how useful this information is.
- Inventory suffered a major refactor in 2.4, you should not need to do this in the core code as an inventory plugin should suffice.

**Comment by oboukili** [comment]
The rationale behind this PR was to be able to lessen the playbooks/roles maintenance overhead.
Let me illustrate:

with an inventory such as this:
```
[mycompanyapps:children]
appA
appB

[appA]
somenode

[appB]
somenode
someothernode
```

Consider this simple app deploy playbook with the PR feature:
```
- name: Deploy company apps.
  hosts: mycompanyapps
  become: true
  tasks:
    - name: deploy apps
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ child_groups['mycompanyapps'] }}"
```

If you want to add an appC, you won't have to modify the playbook.

and now the same playbook without the feature:
```
- name: Deploy company apps.
  hosts: mycompanyapps
  become: true
  tasks:
    - name: deploy appA
      package:
        name: appA
        state: latest
      when: 'appA' in group_names
    - name: deploy appB
      package:
        name: appB
        state: latest
      when: 'appB' in group_names
```
you would have to maintain the playbook on every change.
Now this was a really simple playbook, but this becomes quickly tedious when you have a large ansible base code for deploys.

About the child/parent/child+parent/none group inclusion, I totally agree, I just wanted to have more options for the future.

Anyways let me check 2.4 inventory features, maybe they will be enough :)

**Comment by bcoca** [comment]
pertaining the example given, a simpler approach would be adding a `packages` variable to each child group.
```
   - name: deploy apps
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ packages }}"
```

**Comment by oboukili** [comment]
been there :( ! 
In this particular case, when you have a host which is part of two child groups (like in the inventory above) which both expose a "package" list variable, those two vars will overlap! 
And I don't really want to enable the 'hash merge' behavior globally...
Tried several combine() jinja filters solutions but all come down to be able to fetch these "packages" group_vars without having to point at specific host (through a hypothetical "group_vars" magic variable, which currently does not exist).

I still daily use the following ugly workaround (breaks everytime the group is empty):
```
- set_fact:
  package: "{{ hostvars[groups['appA'][0]]['AppA_package'] }}"
```

**Comment by alexandrezfs** [comment]
We also would like this kind of feature. We currently have complex groups inventory hierarchies which is impossible to manage with simple vars in the inventory.

**Comment by mattclay** [comment]
CI failures due to syntax errors:

```
lib/ansible/inventory/__init__.py:1:8: SyntaxError: self._parent_groups_dict_cache = {}
lib/ansible/vars/__init__.py:1:16: SyntaxError: variables['child_groups']  = self._inventory.get_child_groups_dict()
```

**Comment by oboukili** [comment]
@gdepuille can you transfer back to me this PR ownership? I'll handle it.

**Comment by gdepuille** [comment]
@oboukili I've just added you with writing rights on the forked repository. 
Can you feedback to me if you encountered some problems to push on this one.
If you don't know what to do, I've some kind of features in minds ;-)
Thank you. See you later.

**Comment by oboukili** [comment]
thanks @gdepuille ! I'll let you know asap (ps: it feels weird to be back!)

**Comment by calfonso** [comment]
@oboukili Are you interested in changing this PR to be an inventory plugin, based upon the comment from @bcoca? 

"Inventory suffered a major refactor in 2.4, you should not need to do this in the core code as an inventory plugin should suffice."

needs_info

**Comment by gdepuille** [comment]
@calfonso @oboukili I've searched some informations / documentations on Ansible documentation website about inventory plugin. My search has a failed result.
It's possible to send to me and @oboukili some information about this major feature ? Do you have an implementation sample ?

**Comment by calfonso** [comment]
@bcoca When you get a moment, could you provide more info on this? Thanks!

needs_info

**Pull request closed without merging**
