### PR TITLE
Issue #848: Closing stdin after we read from stdout

### PR DESCRIPTION
**Pull request by SleeplessAnnoyedNerd**
Hi Michael,

the pull request for Issue #848. :)

Since it's my first one and I'm more of a Mercurial user please bear with me if I did something (completely) wrong.

Thanks,
Dietmar

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi, thanks for this.   In the future, please submit seperate topics on different pull requests, using a different branch for each.

Closing stdin is different than the JSON change, and it can often occur that I'm ready to merge one thing and not the other.

I'll let this go this time though :) ... reviewing shortly

See also:  https://help.github.com/articles/using-pull-requests/

**Comment by SleeplessAnnoyedNerd** [comment]
HI Michael,

thanks.

Stupid mistake on my side. Unfortunately I haven't thought of that implication. :(
Thanks for bending the rules this time. 

Thanks,
Dietmar

**Comment by mpdehaan** [comment]
ok, all merged in, I made a few small changes, namely in "baby JSON mode", a "=" won't start the line, it will just be in the line.

Thanks!

**Comment by SleeplessAnnoyedNerd** [comment]
Hi Michael,

you're (very) welcome.

"=" ... thanks for fixing that!

Thanks,
Dietmar

**Pull request merged**
