### PR TITLE
Typo: authentification to authentication (repeat 9a13d56)

### PR DESCRIPTION
**Pull request by Ikuyadeu**
##### SUMMARY

Repeating previous typo changes.

Related #66120

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/net_tools/netcup_dns.py

##### ADDITIONAL INFORMATION

This PR repeats the same changes with  previous changes  that were made by @Akasurde (Link: https://github.com/ansible/ansible/commit/9a13d56b266a8180726d561d64076c4bf8f95fb9#diff-8f60df5685f83b8659a1106d36591e93L209)

### CODE REVIEW

**Comment by nbuchwitz** [comment]
shipit

**Comment by nbuchwitz** [comment]
Thanks for noticing  & PR

**Comment by Akasurde** [comment]
@Ikuyadeu Thanks for the contribution. @nbuchwitz Thanks for the review.

**Comment by Ikuyadeu** [comment]
@Akasurde Thank you for review!

**Pull request merged**
