### PR TITLE
Update ce_vrf_af to fix bugs

### PR DESCRIPTION
**Pull request by yanzhangi**
##### SUMMARY

Add some update statements

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible/modules/network/cloudengine/ce_vrf_af.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by hwDCN** [comment]
+1

**Review by yuandongx — APPROVED** [review]
A suggestion, more detailed description of the submitted PR.Please.

**Comment by xuxiaowei0512** [comment]
+1

**Comment by xuxiaowei0512** [comment]
rebuild_merge

**Comment by hwDCN** [comment]
bot_status

**Comment by hwDCN** [comment]
bot_status

**Pull request merged**
