### PR TITLE
Move tower_common tests with tower_organization.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Move tower_common tests with tower_organization.

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

tower_organization integration tests

### CODE REVIEW

**Comment by AlanCoding** [comment]
We are trying to remove these with https://galaxy.ansible.com/awx/awx replacing them.

These tests are mirrored in https://github.com/ansible/test-playbooks/tree/master/tower_modules, and we are running them actively in CI for that collection. The tests, along with the collection, have underwent significant changes since they were forked. My desired solution is not to make any changes, but to delete all of them. The deprecation PR https://github.com/ansible/ansible/pull/62924 was modified to use the `migrated_to:` flag, but I am still unclear on the exact expectations to fully tombstone them, because I didn't have any examples from other content at the time, although maybe I can look back into that now.

**Comment by mattclay** [comment]
@AlanCoding This change is to facilitate the ansible-base migration, as it allows the migration script to properly recognize the association of these tests to the Tower modules.

**Review by AlanCoding — APPROVED** [review]

**Comment by AlanCoding** [comment]
Revised, to be less conflicting https://github.com/ansible/ansible/pull/67233

**Comment by AlanCoding** [comment]
Let me know if there's anything else I can do to mark this content's destination for the migration.

**Pull request merged**
