### PR TITLE
azure_rm_deployment_facts fails to fetch the facts for the templates specified inline

### PR DESCRIPTION
**Pull request by sparampalli**
##### SUMMARY

azure_rm_deployment_facts module fails to get the facts for ARM deployment when a template is defined inline in azure_rm_deployment module of the playbook. So modified the code to check if template is inline or not based on that get the right value.

Fixes#57989
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

azure_rm_deployment_facts
##### ADDITIONAL INFORMATION

Create the ARM stack using azure_rm_deployment and then try to get the facts of this deployment.
azure_rm_deployment:
resource_group:
auth_source: credential_file
deployment_mode: complete
location:
name:
profile: default
subscription_id:
state: present
**template:
Specify the template here**

```paste below
**Before the change -**
fatal: [localhost]: FAILED! => {
"changed": false,
"module_stderr": "Traceback (most recent call last):\n File "/Users/psrikantha/.ansible/tmp/ansible-tmp-1560846234.11-254137282894546/AnsiballZ_azure_rm_deployment_facts.py", line 114, in \n _ansiballz_main()\n File "/Users/psrikantha/.ansible/tmp/ansible-tmp-1560846234.11-254137282894546/AnsiballZ_azure_rm_deployment_facts.py", line 106, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File "/Users/psrikantha/.ansible/tmp/ansible-tmp-1560846234.11-254137282894546/AnsiballZ_azure_rm_deployment_facts.py", line 49, in invoke_module\n imp.load_module('main', mod, module, MOD_DESC)\n File "/var/folders/l8/nzzx3fy16xg9zkv36kc_mkdh0000gn/T/ansible_azure_rm_deployment_facts_payload_b1lp_g/main.py", line 243, in \n File "/var/folders/l8/nzzx3fy16xg9zkv36kc_mkdh0000gn/T/ansible_azure_rm_deployment_facts_payload_b1lp_g/main.py", line 239, in main\n File "/var/folders/l8/nzzx3fy16xg9zkv36kc_mkdh0000gn/T/ansible_azure_rm_deployment_facts_payload_b1lp_g/main.py", line 153, in init\n File "/var/folders/l8/nzzx3fy16xg9zkv36kc_mkdh0000gn/T/ansible_azure_rm_deployment_facts_payload_b1lp_g/ansible_azure_rm_deployment_facts_payload.zip/ansible/module_utils/azure_rm_common.py", line 325, in init\n File "/var/folders/l8/nzzx3fy16xg9zkv36kc_mkdh0000gn/T/ansible_azure_rm_deployment_facts_payload_b1lp_g/main.py", line 160, in exec_module\n File "/var/folders/l8/nzzx3fy16xg9zkv36kc_mkdh0000gn/T/ansible_azure_rm_deployment_facts_payload_b1lp_g/main.py", line 176, in get\n File "/var/folders/l8/nzzx3fy16xg9zkv36kc_mkdh0000gn/T/ansible_azure_rm_deployment_facts_payload_b1lp_g/main.py", line 233, in format_response\nAttributeError: 'NoneType' object has no attribute 'get'\n",
"module_stdout": "",
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"rc": 1
}

**After the change-**
ARM facts were displayed correctly for the cases of inline templates.
```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@sparampalli Thank you for submit this PR. Please fixes the CI fail when you're free! Thank a lot!

**Comment by Fred-sun** [comment]
kindly ping

**Comment by sparampalli** [comment]
@Fred-sun , can you please let me know what action I am supposed to do here?

**Comment by Fred-sun** [comment]
@sparampalli Need you to rebase PR, fix the conflict! Thanks!

**Comment by Fred-sun** [comment]
kindly ping

**Comment by sparampalli** [comment]
done. Plz check.

**Comment by Fred-sun** [comment]
@sparampalli Please retrigger CI check when you're free! Thanks a lot!

**Comment by sparampalli** [comment]
Done

**Comment by Fred-sun** [comment]
> @sparampalli this PR contains the following merge commits:
> 
> 28b9f69
> 9f11ee6
> 
> Please rebase your branch to remove these commits.
> click here for bot help

Also need you help rebase this PR！ Thanks a lot!

**Comment by Fred-sun** [comment]
@sparampalli Please help rebase the PR! Thank you very much!

**Comment by Fred-sun** [comment]
@sparampalli Would you please help rebase the PR ？ Thank you very much!

**Comment by sparampalli** [comment]
Hi Fred,

I will do it today. Sorry was very much occupied with a release.

Thanks,
P Srikantha

**Comment by Fred-sun** [comment]
@sparampalli Thanks for your update! when you finish changed, I will push for review!

**Comment by Fred-sun** [comment]
@sparampalli kindly ping!

**Comment by Fred-sun** [comment]
@sparampalli kindly ping!

**Comment by Fred-sun** [comment]
@sparampalli Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Pull request closed without merging**
