### PR TITLE
Improve NetBSD support

### PR DESCRIPTION
**Pull request by jeffrizzo**
- add NetBSD Network support to the FreeBSD/Darwin support
- Fix the Makefile so "gmake tests" can work on NetBSD
- Add a basic implementation of NetBSDHardware to retrieve some hardware facts.
- set "ansible_architecture" in a way that makes more sense when machine name and processor name are different.

Tested on NetBSD 5.1, NetBSD 6.0(amd64 and evbarm), FreeBSD 9.0 and MacOS 10.8.2.

### CODE REVIEW

**Comment by jeffrizzo** [comment]
A misunderstanding of how github 'pull requests' work caused me to allow additional commits on here than what I originally intended;  however, they are all bits I would have requested to have included anyway.

**Comment by sfromm** [comment]
Per discussion on irc, please replace tab characters with spaces.  Also, can you break out ef42bce to a separate pull-request so that it can be evaluated independently?  

Regarding the remainder of the netbsd fact support, can you ping the list to see if others can test your changes?

**Comment by jeffrizzo** [comment]
Happy to break it out;  unfortunately, I'm still a bit of a github newb - what's the best way to do that in the way everyone else is expecting?

**Comment by bcoca** [comment]
I had the same problem initially, github's workflow is a bit of odds to
what I was used to. What works for me in this case is to create 2 new
'cherry-picked' branches locally and push to 2 new branches on github and
submit 2 new PRs from those.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jeffrizzo** [comment]
Great, thanks.  I'll do this.

**Pull request closed without merging**
