### PR TITLE
include_role error with with_items (2.3.0 devel) #21285

### LINKED ISSUE #21285: include_role error with with_items (2.3.0 devel)
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
ansible 2.3.0 (devel 59306e2aef) last updated 2017/02/11 12:44:45 (GMT +000)

##### OS / ENVIRONMENT
N/A

##### SUMMARY
include_role fails to execute when used with_items (similar to issue #17966)

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
    - include_role:
        name: '{{ item }}'
      with_items:
        - role1
        - role2
```

##### EXPECTED RESULTS
include_role loops over list and updates item variable

##### ACTUAL RESULTS
```
TASK [include_role] 
ERROR! 'item' is undefined
```

### PR DESCRIPTION
**Pull request by snowsky**
##### SUMMARY

Fixes #21285 

##### ISSUE TYPE
 - Bugfix Pull Request

##### ANSIBLE VERSION

```
It seems this applies to the versions after 2.0.
```

##### ADDITIONAL INFORMATION

```
The role name didn't expand correctly if it is in a loop. This fix will see if there is loop var in role name, if there is it will replace the variable with correct loop var value.
```

### CODE REVIEW

**Comment by snowsky** [comment]
The error is not related to this PR. I'll retest it.

**Comment by snowsky** [comment]
The error message is not related to the PR:
```
2017-03-30 13:00:20 Run command: docker run --detach ansible/ansible:httptester
2017-03-30 13:00:37 Run command: docker run --detach --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=false --link e796353d922031119fa708809afb1c078a0444bf7d1111361f8b1df2ed8a130f:ansible.http.tests --link e796353d922031119fa708809afb1c078a0444bf7d1111361f8b1df2ed8a130f:sni1.ansible.http.tests --link e796353d922031119fa708809afb1c078a0444bf7d1111361f8b1df2ed8a130f:sni2.ansible.http.tests --link e796353d922031119fa708809afb1c078a0444bf7d1111361f8b1df2ed8a130f:fail.ansible.http.tests --env HTTPTESTER=1 ansible/ansible:ubuntu1604py3
2017-03-30 13:00:37 Run command: docker exec -i 6de974a3cf1bf4728d83b3d13408753e180bf2c3924c490e986107c5009bab4e dd of=/root/docker.sh bs=65536
2017-03-30 13:00:37 Run command: docker exec 6de974a3cf1bf4728d83b3d13408753e180bf2c3924c490e986107c5009bab4e /bin/bash /root/docker.sh
2017-03-30 13:00:37 /root/docker.sh: line 14: cannot create temp file for here-document: No such file or directory
2017-03-30 13:00:37 Run command: docker rm -f e796353d922031119fa708809afb1c078a0444bf7d1111361f8b1df2ed8a130f
2017-03-30 13:00:52 Run command: docker rm -f 6de974a3cf1bf4728d83b3d13408753e180bf2c3924c490e986107c5009bab4e
2017-03-30 13:00:57 ERROR: Command "docker exec 6de974a3cf1bf4728d83b3d13408753e180bf2c3924c490e986107c5009bab4e /bin/bash /root/docker.sh" returned exit status 1.
```

**Comment by jbilbro** [comment]
I have tried installing these two files on my Ansible 2.3 install on my Ansible Tower 3.1.3 server.  When trying to execute a job template, it fails immediately when trying to update from SCM.  If I revert these two files everything works fine (other than you know, include_roles failing to take a variable).


`TASK [Set the git repository version] ******************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'NAMESPACE_FACTS'
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}`

**Comment by halberom** [comment]
The include_role module example docs should probably be updated to include an example of this.  Also, how does this impact the (currently working) alternative logic of `with_` on a role?, as shown by the example
```
- name: Use role in loop
  include_role:
    name: myrole
  with_items:
    - '{{ roleinput1 }}'
    - '{{ roleinput2 }}'
  loop_control:
    loop_var: roleinputvar
```
for example, if I do this
```
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - include_role:
        name: "{{ item.name }}"
      with_items: 
        - { name: test2, message: 'foo' }
      loop_control:
        loop_var: rolevar
```
it (your pull request) doesn't work.  `'item' is undefined`

and finally, i thought dynamic role names weren't allowed for security reasons - too easy to modify what might be run based on some overriding var.

**Comment by mgvazquez** [comment]
I tested this PR locally in my env with the ansible-2.4.2.0 and work perfectly.
Please, review it and merge it as soon as possible. This is e great feature to implement.
PD: Sorry about my lack of expression in English language

**Comment by mkrizek** [comment]
#21285 was fixed in https://github.com/ansible/ansible/pull/33386 therefore I am going to close this one, thanks for your contribution @snowsky!

**Pull request closed without merging**
