### PR TITLE
[WIP] Replace Foreman and Katello all encompassing modules with specific mo…

### PR DESCRIPTION
**Pull request by ehelms**
…dules

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

foreman
katello

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

This begins to deprecate the "all in one" Foreman and Katello modules in favor of direct and specific modules targeted at entities that live within Foreman or Katello. This starts by adding the necessary modules to be able to create an Organization, Product and Repository while also adding supporting to upload content into a Katello repository.

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to PEP 8 issues:

```
2017-02-17 13:56:29 ERROR: PEP 8: lib/ansible/modules/remote_management/foreman/foreman_organization.py:94:1: W293 blank line contains whitespace (current)
2017-02-17 13:56:29 ERROR: PEP 8: lib/ansible/modules/remote_management/foreman/katello_product.py:109:1: W293 blank line contains whitespace (current)
2017-02-17 13:56:29 ERROR: PEP 8: lib/ansible/modules/remote_management/foreman/katello_repository.py:128:21: E126 continuation line over-indented for hanging indent (current)
2017-02-17 13:56:29 ERROR: PEP 8: lib/ansible/modules/remote_management/foreman/katello_repository.py:135:1: W293 blank line contains whitespace (current)
```

You can run this test locally with `make pep8`.

**Comment by bcoca** [comment]
FYI, to deprecate a module you need to rename it with a leading underscore (_) and add a deprecation entry into the documentation, mostly detailing which other module(s)  to use instead

**Comment by ehelms** [comment]
This is still a WIP that I am working on updating. The goal is to replace the large module with individual modules per entity and action. Once I have parity and document the deprecation I'll open this up to be considered for merge.

**Comment by gundalow** [comment]
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:25980)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eNK0x-002ld3-4z
	for greg@biomassiv.es; Fri, 08 Dec 2017 08:52:35 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=o4kyONpC7lvOjV6Elo2t2OCacec=; b=vJ4z6j+4NX4ReMtL
	nuwUo7cNqxgzJAQ7jNZIRkMLueyS3ABO8lX/bQCH2qYys0ALCzd0UQo4hljf46kn
	ofCl8AVNi4QSiNSm5HafzwNuQCgC2AwO3YzS5Dfbg2CWVEFTpfEsM4LSrVaA+5Il
	nJ04U2bVDvYOpiweiMGPKYiy7pc=
Received: by filter0255p1iad2.sendgrid.net with SMTP id filter0255p1iad2-14463-5A2AA70C-2B
        2017-12-08 14:51:56.637681314 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0020p1iad2.sendgrid.net (SG) with ESMTP id e59ov9SFToOg7_5ChT3cRw
	for <greg@biomassiv.es>; Fri, 08 Dec 2017 14:51:56.586 +0000 (UTC)
Date: Fri, 08 Dec 2017 14:51:56 +0000 (UTC)

**Pull request closed without merging**
