### PR TITLE
Allow for multiple LIFS instead of 1 at a time

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Allow for multiple LIFS instead of 1 at a time

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_cluster_peer.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]
shipit

**Review by thedoubl3j — APPROVED** [review]
lgtm, looks like we are missing unit tests for this though. just wanted to get it on your radar

**Comment by carchi8py** [comment]
@thedoubl3j good catch (i forgot to double check which unit test exist in 2.8 in our internal repo vs github, i'm missing quite a few). I'll upload this one now the other one now.

**Review by lonico — APPROVED** [review]
shipit

**Review by thedoubl3j — APPROVED** [review]
thanks for getting those in @carchi8py, lgtm. shipit

**Pull request merged**
