### PR TITLE
Update collection routing

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Summary PR for all collection routing updates for moves tracked at https://github.com/ansible-collections/overview/issues/128.

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/config/ansible_builtin_runtime.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @gundalow @dmsimard @dericcrago

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
Three collections are currently missing from this PR:
- dellemc.openmanage
- infoblox.nios_modules
- kubernetes.core

For the first two, it depends on whether they are added to Ansible 3.0.0 or not. The review deadline for new collections is today ([January 27th](https://hackmd.io/y7BBcweNR3aRVLuMbKkDxw#Proposed-Schedule-for-Ansible-30)). If any of these collections will be included, we can start the process of moving the content that they share with community.general to the new collection for community.general 2.0.0. If they are not included, the content will stay in community.general until at least version 3.0.0.

For kubernetes.core it still seems not to be clear how the move from community.kubernetes to kubernetes.core will actually be done. Until that isn't decided, it doesn't make sense to update any reference (especially since kubernetes.core is probably not contained in Ansible 3.0.0 as long as it is unclear what happens).

**Review by nitzmahone — APPROVED** [review]

**Comment by nitzmahone** [comment]
@felixfontein happy to merge this (and a 2.10 backport) whenever- just let me know when it's locked

**Comment by briantist** [comment]
@felixfontein there's a change to the hashi_vault redirect but it's not in the changelog, maybe also kubevirt?

**Comment by felixfontein** [comment]
Discussion from IRC: let's wait until February 2nd to see what the situation for dellemc.openmanage and infoblox.nios_modules will be. The situation for kubernetes.core probably won't get resolved anytime soon (https://github.com/ansible-community/ansible-build-data/issues/57#issuecomment-768616048).

**Comment by felixfontein** [comment]
I'll add redirects for the DellEMC modules in community.general that are in dellemc.openmanage once ansible-community/ansible-build-data#58 has been merged. (In case infoblox.nios_modules is accepted for Ansible 3.0.0, I'll also add redirects.) I think once the February 2nd deadline passed, we can get this merged.

I think it's best if the kubernetes.core / community.kubernetes maintainers decide and organize by themselves when/if they want redirects added in ansible-core 2.11 (create your own PR) or later (talk to @nitzmahone first) - CC @jillr @tima @geerlingguy.

**Comment by felixfontein** [comment]
@gundalow @nitzmahone I think this is now ready. Can you take another look?

**Comment by felixfontein** [comment]
@gundalow @nitzmahone feature freeze is coming up in a few days (Friday?), so this should get merged before then :)

**Review by nitzmahone — APPROVED** [review]

**Comment by nitzmahone** [comment]
Sorry, GitHub notifications + GMail summaries are a bad combo (the last thing I saw on this was pushing new commits)- merging...

**Comment by felixfontein** [comment]
@gundalow @nitzmahone thanks for reviewing and merging!

**Pull request merged**
