### PR TITLE
[stable-2.15] Use of constant for 644 permission variable

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
(cherry picked from commit dd44449b6ec454a46426a020608fe3763287101f)

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by Akasurde** [comment]
This Backport PR is required for backporting https://github.com/ansible/ansible/pull/82761 to 2.15

**Comment by sivel** [comment]
The same here, just backport https://github.com/ansible/ansible/pull/82761 and update to use an explicit mode.

**Pull request closed without merging**
