### PR TITLE
Sanity checks: test for print statement

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This adds a sanity test which checks for `print()` calls in module_utils and modules.

I'm adding this since `print()` calls accidentally ended up in lib/ansible/module_utils/aws/elbv2.py and caused strange module crashes (fixed in #65021 and #65183). This could have been prevented if such a test would have existed earlier.

CC @jillr @s-hertel @willthames

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible-test

### CODE REVIEW

**Review by gundalow — APPROVED** [review]
Excellent idea, thank you.

**Comment by jillr** [comment]
In case I'm not around when we discuss this in triage, LGTM - thanks @felixfontein!

**Comment by felixfontein** [comment]
Rebased (and updated ignore.txt) to remove conflicts due to #65437 being merged.

**Comment by mattclay** [comment]
@felixfontein Is there a reason why this couldn't be added to the existing blacklist plugin?

Also, I just noticed that the blacklist plugin path filter needs to be updated to support collections:

https://github.com/ansible/ansible/blob/88d8cf8197c53edd3bcdcd21429eb4c2bfbf0f6a/test/lib/ansible_test/_data/sanity/pylint/plugins/blacklist.py#L53

**Comment by felixfontein** [comment]
@mattclay no, I don't think so. The main reason is that I didn't knew that the blacklist plugin does that as well :) I'll change the PR accordingly.

**Comment by felixfontein** [comment]
@mattclay I've adjusted the PR to extend the blacklist plugin instead. Tests pass, and the ignore list is two entries shorter :)

**Comment by mattclay** [comment]
@felixfontein If you have time, would you mind opening another PR to fix the path filter, so it works for collections as well?

**Review by mattclay — APPROVED** [review]

**Comment by felixfontein** [comment]
@mattclay are `/module_utils/` and `/plugins/modules/` the correct substrings to look for for that?

**Comment by felixfontein** [comment]
I created a PR for that (#65475).

**Review by s-hertel — APPROVED** [review]

**Comment by felixfontein** [comment]
@gundalow @jillr @mattclay @s-hertel @jborean93 thanks a lot for reviewing and merging!

**Pull request merged**
