### PR TITLE
Add initial version of hpilo modules

### PR DESCRIPTION
**Pull request by haad**
ISSUE TYPE

    Feature Pull Request

SUMMARY

Modules for remote_management of hp based servers with ilo module. These modules are based on original version developed by dag@wieers.com in ansible-provisioning repo.

### CODE REVIEW

**Comment by dagwieers** [comment]
@haad I would prefer that the initial PR is made by the person from HP that is maintaining them in ansible-provisioning now.

PS Can you tell me what you changed ?

**Comment by haad** [comment]
@dagwieers that sounds good I have updated them to current ansible commit rules.  How would you like to merge any potential differences ? Should I close this issue and make a PR on ansible-provisioning ?

You can check diffs here [1]

[1] https://gist.github.com/haad/a798a0335de2f2ddc3846957565c010a

**Comment by dagwieers** [comment]
@haad I was thinking about this yesterday. I'd rather make the PR myself (so blame works ;-)), add HP developer as a maintainer, and maybe at that point your changes can be committed. At that point ansibot should assign those things to HP and me. Let me contact the HP developer first and see if that is fine with him.

PS The problem I have is that I switch from $CUSTOMERX to $CUSTOMERY and I don't always have access to hardware. On top of that the compatibility between iLO releases is as important as well.
PS2 I also would like to see hponcfg support add, so I will submit that one as well.

**Comment by haad** [comment]
@dagwieers You can take mine changes now and create initial PR with them if you want I'm fine with that too. As I can't guarantee that I will have time in future to push this further.

**Comment by mattclay** [comment]
@haad CI failure due to:

```
2017-01-15 21:56:38 iteritems has been removed in python3.  Alternatives:
2017-01-15 21:56:38     for KEY, VALUE in DICT.items():
2017-01-15 21:56:38     from ansible.module_utils.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-01-15 21:56:38     from ansible.compat.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-01-15 21:56:38 ./lib/ansible/modules/remote_management/hpilo/hpilo_facts.py:        for cpu, details in memory_details_summary.iteritems():
```

**Comment by haad** [comment]
@dagwieers should I close this one ? as you plan to do another PR

**Comment by dagwieers** [comment]
@haad You can also reuse it for doing your own changes. I plan to commit the version from ansible-provisioning as-is so you can add your changes as yourself. And then, if you don't mind, I would like to make you maintainer as well. The people working at HP (or HPE) that heavily used the hpilo module no longer work there. Apparently the whole team left...

PS I haven't had the time to do this yet, this weekend FOSDEM, now Cfgmmgmtcamp. I hope to do this this week though.

**Comment by haad** [comment]
@dagwieers wouldn't be better to just review this PR ? as I will probably will have to do same changes as I have already done here. So let's just review this PR and merge it. I'm fine with maintaining them.

**Comment by dagwieers** [comment]
@haad The three modules have been upstreamed (just in time for v2.3). Can you test the modules upstream ? And check what changes you had prepared.

If you'd be willing to maintain them,  you have some responsibilities (like answering bug-reports and reviewing pull-requests) but also some power/control (give direction to how these modules evolve, and shipit powers for other modules in this namespace). See: https://github.com/ansible/ansibullbot/pull/396

**Comment by haad** [comment]
@dagwieers yeah while I'm on current project I can be a maintainer.

**Pull request closed without merging**
