### PR TITLE
Improve error reporting when parsing an ini file.

### PR DESCRIPTION
**Pull request by sontek**
If an executable bit is removed from a hosts file that is a python script
the inventory will be parsed as ini and the output isn't very helpful
in debugging why this would be the case.

This changes the error:

```
ansible.errors.AnsibleError: Invalid ini entry: sys - need more than 1 value to unpack
```

to this:

```
ansible.errors.AnsibleError: Invalid ini entry in /path/to/scripts/hosts/nova.py:20. Line was: 'import sys'. Expected format is 'variable=value'
```

### CODE REVIEW

**Comment by msabramo** [comment]
This is a much, much better error. :+1:

```
❯ ansible-playbook -i hosts/ playbook.yml
ERROR: Invalid ini entry: sys - need more than 1 value to unpack

❯ git checkout improve_error_reporting
M   lib/ansible/modules/core
Switched to branch 'improve_error_reporting'
Your branch is up-to-date with 'sontek/improve_error_reporting'.

❯ ansible-playbook -i hosts/ playbook.yml
ERROR: Invalid ini entry in hosts/nova.py:20. Line was: 'import sys'. Expected format is 'variable=value'
```

:+1:

**Comment by mpdehaan** [comment]
I'm not positive that's the only way this error could be raised though, which is I think why we shouldn't assume it's the case.

**Comment by sontek** [comment]
@mpdehaan Are you sure?  The code is this:

```
try:
    (k,v) = t.split("=", 1)
except ValueError, e:
```

You think there will be a time a `ValueError` is raised when calling `split('=', 1)` on a string that might not be because of the string not being `key=value`?

**Comment by msabramo** [comment]
The `try/except` is round a single line that does a `split`. It looks pretty clear that if `ValueError` is raised then something was wrong with that line.

Printing the file and line number is way better than `need more than 1 value to unpack`.

**Comment by sontek** [comment]
@mpdehaan Could I get more details on what other things might cause this `ValueError` that would prevent this PR from being accepted?  I'm willing to improve the code if you can provide more details but with my knowledge of Python and the string split command I can't think of any other reasons a `ValueError` may be raised.

**Comment by msabramo** [comment]
I can only think of one other way to get a `ValueError` from `split` -- using an empty separator:

``` python
>>> (k,v) = t.split("", 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: empty separator
```

but that doesn't apply here of course, because the separator is hard-coded to `"="`.

The original `ValueError` comes from https://github.com/python/cpython/blob/master/Python/ceval.c#L3806. The "empty separator" case comes from https://github.com/python/cpython/blob/master/Objects/stringlib/split.h#L154.

I don't see any other way that a `ValueError` could be raised.

**Comment by sontek** [comment]
@mpdehaan Ping, just want to follow up on this. Any more details on why this close would greatly help me modify the code to meet your requirements.

cc @jimi-c @abadger

**Comment by msabramo** [comment]
:+1:

This seems like a great change. Not sure if it still applies in 2.0, but the error message is much more helpful.

**Comment by msabramo** [comment]
Please reopen

**Comment by jimi-c** [comment]
@msabramo, @amenonsen has been working on this quite a bit, so it probably doesn't apply anymore. You might want to check out the latest devel and see if it's still an issue, and if so ping him about it (his nick is `crab` in #ansibe-devel on Freenode).

**Pull request closed without merging**
