### PR TITLE
ACI Encap pool: New module for support layer2 encap pools

### PR DESCRIPTION
**Pull request by jmcgill298**
##### SUMMARY

Add new network/aci module to support L2 Encap pools (vlan, vxlan, vsan)

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

aci_encap_pool
##### ANSIBLE VERSION

```
2.4.1
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jmcgill298** [comment]
This does not include updates in https://github.com/ansible/ansible/pull/33756, merging that request will require a small update to this request.

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/33756 has been merged, so I believe an update is required here.

**Comment by jmcgill298** [comment]
@gundalow thank you, I will update now

**Comment by gundalow** [comment]
Do we have unit tests for ACI?
I know we don't have the ability to run the ACI integration tests (though thanks for adding them)

**Comment by jmcgill298** [comment]
I have only worked on integration tests and use an available APIC for testing.

**Comment by dagwieers** [comment]
We will add unit tests to our list. It would be nice to have when doing some refactoring of the library in the future. But integration tests at this point seem much more useful.

**Comment by gundalow** [comment]
Wonder if we can get ACI integrated into DCI. It does concern me that we don't have any automated tests for any of the ACI modules. Feel free to poke me on IRC/NTC about this

**Comment by dagwieers** [comment]
There is a department at Cisco responsible for this which was already in contact with @privateip , it does bother me that this item is open for more than 6 months with no clear status or progress. cc: @schunduri

**Review by gundalow — APPROVED** [review]

**Review by dagwieers — APPROVED** [review]
LGTM

**Pull request merged**
