### PR TITLE
Fixing domain to authorization matching for ACME v2.

### LINKED ISSUE #37557: letsencrypt: problem with authorization to domain matching
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION
```
2.5.0rc3
```

##### SUMMARY
The code matching authorizations with identifiers (i.e. domains) is wrong: it assumes that two arrays correspond to each other, which they in general do not. This bug happens when wildcard and non-wildcard certificates are mixed and when more than one domain is used. So `example.com`, `*.example.com` in one certificate is OK, but `example.org`, `*.example.com` in one certificate triggers this bug. (Asking for `*.example.com`, `example.org` does work; the ACME v2 server apparently puts wildcard domains first and then non-wildcard domains, and otherwise keeps the order from input.)

##### STEPS TO REPRODUCE
Use the Let's Encrypt ACME v2 endpoint to obtain a certificate for domains `examle.com, *.example.com, example.org, *.example.org`, for example (with DNS challenges). Obtaining the certificates will always complain that the wrong TXT entries are provided.

##### EXPECTED RESULTS
Get a valid wildcard certificate (assuming the challenges are set up correctly).

##### ACTUAL RESULTS
Get an error of the form `Authorization for ******** returned in********:  CHALLENGE: ********-01 DETAILS: Incorrect TXT record "********" (and 1 more) found at ********.********;`.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #37557.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION
```
2.5.0rc3
```

##### ADDITIONAL INFORMATION
This fix is for devel, but backporting to stable-2.5 should be trivial.

### CODE REVIEW

**Comment by felixfontein** [comment]
I've tested this one extensively, by creating certificates with different combinations of wildcard and non-wildcard domains (in randomized order) and it seems to work fine. The only errors I got were spurious DNS-related errors (stuff like staging server got NXDOMAIN, but *not* wrong TXT record content).

**Comment by resmo** [comment]
shipit

**Comment by felixfontein** [comment]
@resmo Thanks for handling this! Since this is really an ugly bug: is it be possible to get this into stable-2.5 before 2.5 final is released?

**Comment by resmo** [comment]
@felixfontein created the backport PR https://github.com/ansible/ansible/pull/37572 but can not make any guaranties, it will be in 2.5.0.

**Comment by felixfontein** [comment]
@resmo thanks a lot!

**Pull request merged**
