### PR TITLE
2.11 ONLY Track Infoblox contents movement from community.general to own collection

### PR DESCRIPTION
**Pull request by Vaishnavi-infoblox**
##### SUMMARY
Track changes for Infoblox from community.general to its own collection.

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by thedoubl3j** [comment]
hey @Vaishnavi-infoblox you guys wouldn't be removing entries, rather updating them for where they will exist as infoblox takes them. botmeta is tracking the existence of all content found in core and where it moved to. so rather than removing the entry completely, it would look something like: 
```
  $modules/net_tools/nios/:	
    maintainers: sganesh-infoblox	
    labels:	
    - networking	
    - infoblox
    migrated_to: infoblox.$collection_name
```

**Comment by gundalow** [comment]
Please see https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration for details of what the three PRs should be?

**Review by mattclay — DISMISSED** [review]
The test files should not be altered.

**Review by thedoubl3j — COMMENTED** [review]
once @mattclay issues are addressed, I think this is in good shape

**Comment by Vaishnavi-infoblox** [comment]
Hi, Any update on this PR merge?

**Review by thedoubl3j — COMMENTED** [review]
lgtm, looks like it does need a rebase though, ping @mattclay @gundalow

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Looks like a rebase is needed

**Comment by gundalow** [comment]
Could you please raise PR2 and PR3 from this section https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration

**Comment by gundalow** [comment]
@Vaishnavi-infoblox  https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html should help with rebasing

**Comment by gundalow** [comment]
@Vaishnavi-infoblox Can you please rebase this PR?

**Comment by gundalow** [comment]
@Vaishnavi-infoblox https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html should help with rebasing

**Review by gundalow — CHANGES_REQUESTED** [review]
The items on https://github.com/infobloxopen/infoblox-ansible/issues/7 haven't been completed by the `ansible 2.10 collection freeze date`, so this can't be merged.

**Comment by gundalow** [comment]
@Vaishnavi-infoblox If you could rebase this we can merge into `devel` though NOT into `stable-2.10`

**Comment by Vaishnavi-infoblox** [comment]
Hi @gundalow,

I have re based this PR. Please review.

**Comment by Akasurde** [comment]
This PR is no longer valid.

**Pull request closed without merging**
