### PR TITLE
cloud: ovirt: Add option to import SD

### PR DESCRIPTION
**Pull request by KKoukiou**
##### SUMMARY
With this patch I added the option in the ovirt_storage_domains module to import a preconfigured SD.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ovirt module

### CODE REVIEW

**Comment by machacekondra** [comment]
This is actually already part of : 

https://github.com/ansible/ansible/pull/26568

**Comment by KKoukiou** [comment]
@machacekondra I didn't notice it. I am closing the PR, thanks!

**Comment by KKoukiou** [comment]
Looks like this PR https://github.com/ansible/ansible/pull/26568 supports importing only block storage domains. The same is needed to be supported for file storage domains, aka nfs.

Is it in the plan to be implemented to should I resend some patch for that?

**Comment by machacekondra** [comment]
No plans AFAIK, it would be cool if u can send a patch.

**Pull request closed without merging**
