### PR TITLE
AnsibleModule now correctly reads param values with '"'.

### PR DESCRIPTION
**Pull request by bradobro**
Splitting param strings only on first =

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged, thanks

**Comment by jpmens** [comment]
Nitpicking, but is there any way that this can support argument _values_ of `key=value`? Testing possibilities of `get_url` module, I run:

```
./hacking/test-module library/get_url url=http://localhost/~jpm/plain.cgi?name="JP Mens" dest=/tmp/r
```

with the following result:

```
Traceback (most recent call last):
  File "/Users/jpm/.ansible_module_generated", line 380, in <module>
    main()
  File "/Users/jpm/.ansible_module_generated", line 186, in main
    dest = dict(required=True),
  File "/Users/jpm/.ansible_module_generated", line 292, in __init__
    (self.params, self.args) = self._load_params()
  File "/Users/jpm/.ansible_module_generated", line 355, in _load_params
    (k, v) = x.split("=", 1)
ValueError: need more than 1 value to unpack
```

Would be nice to have, but certainly not vital. (And if I _could_ patch it, I _would_ :-)

**Comment by jpmens** [comment]
Ignore this for the get_url module: I've had some coffee now.

```
name="JP%20Mens"
```

of course.

Still maybe for others?

**Comment by mpdehaan** [comment]
i think brad's patch broke you, will look

**Comment by mpdehaan** [comment]
Yeah will look, it should only split on the spaces I would hope

**Comment by bradobro** [comment]
Not sure what's wrong there. My quick tests under Python 2.7.3 look correct:

```
>>> for x in shlex.split('url=http://localhost/~jpm/plain.cgi?name="JP Mens" dest=/tmp/r'):
...    print x.split("=",1)
... 
['url', 'http://localhost/~jpm/plain.cgi?name=JP Mens']
['dest', '/tmp/r']
```

Will look at it some more. Could you shoot me copy of your revamped get_url, jp?

**Comment by bradobro** [comment]
What version of Python are you running, JP? I'm puzzled here. Looks like shlex.split() is producing a string a string without a "=". 

A bit more test code:

``` python
import shlex, pprint


def parse_params(args):
    ''' execpt for return, copied from module_common.py'''
    items   = shlex.split(args)
    params = {}
    for x in items:
        (k, v) = x.split("=",1)
        params[k] = v
    # ADDED items to return for example only
    return (params, items, args)        

params_quoted_space = 'url=http://localhost/~jpm/plain.cgi?name="JP Mens" dest=/tmp/r'
params_escaped_space = 'url=http://localhost/~jpm/plain.cgi?name="JP%20Mens" dest=/tmp/r'

for args in params_quoted_space, params_escaped_space:
    p,i,a = parse_params(args) 
    pprint.pprint( (a,i,p) )
```

Seems to parse correctly: (my labels hand added to the output)

```
input = 'url=http://localhost/~jpm/plain.cgi?name="JP Mens" dest=/tmp/r',
shlexed = ['url=http://localhost/~jpm/plain.cgi?name=JP Mens', 'dest=/tmp/r'],
parsed = {'dest': '/tmp/r', 
               'url': 'http://localhost/~jpm/plain.cgi?name=JP Mens'})

('url=http://localhost/~jpm/plain.cgi?name="JP%20Mens" dest=/tmp/r',
 ['url=http://localhost/~jpm/plain.cgi?name=JP%20Mens', 'dest=/tmp/r'],
 {'dest': '/tmp/r', 'url': 'http://localhost/~jpm/plain.cgi?name=JP%20Mens'})
```

**Comment by jpmens** [comment]
Brad, thanks for your help on this: I'm running Pythong 2.6.1 on OS/X, and your two tests above pass here, so the args splitting seems to be fine. I'll carry on looking elsewhere.

**Comment by bradobro** [comment]
Thanks for working on it. Good luck. Let me know if you need another eye on
it.

This makes me think it'd be a good thing to have some unit tests for
module_common.py, at least for the arg parsing. Maybe once we get out
incorporated it won't matter so much.

--Brad Olson (from phone)
On Jul 22, 2012 2:36 AM, "JP Mens" <
reply@reply.github.com>
wrote:

**Pull request merged**
