### PR TITLE
VMware: vmware_guest_tools_wait module returns vmware tools facts only

### LINKED ISSUE #60258: VMware: require vmware_guest_tools_wait module return more tools specific facts not vm facts
##### SUMMARY

This module can return the facts of VMware tools installed in guest OS, like: tools installed or not, tools running status, installed tools version, installed Open VM tools or VMware tools MSI install in Window or TAR install in Linux, the history of the tools install(need to test), etc.
Now, it returns VM facts we can get it from vmware_guest_facts module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest_tools_wait
##### ADDITIONAL INFORMATION

For example,
```yaml
    "tools_facts": {
        "changed": false,
        "failed": false,
         "instance": {
             "hw_name": "dw_win10_64_test",
             "hw_power_status": "poweredOn",
             "hw_product_uuid": "42284ad6-f28c-f582-1ab9-xxxx",
             "hw_version": "vmx-14",
             "instance_uuid": "50283c1f-4a0a-0ef9-e0cf-xxxx",
             "hw_guest_full_name": "Microsoft Windows 10 (64-bit)",
             "hw_guest_id": "windows9_64Guest",
             "guest_tools_status": "guestToolsRunning",
             "guest_tools_version": "10346",
             "guest_tools_version_release": "10.3.10",
             "guest_tools_install_type": "guestToolsTypeMSI", 
             ...
            }
    }
         
```

### PR DESCRIPTION
**Pull request by Tomorrow9**
##### SUMMARY

Let this module only return VMware tools related info and guest info, which will be more useful for user to check result. And VM facts can be gathered using vmware_guest_facts module.
Also add the check of VM power status and VMware tools installed status before waiting for tools running.

Fixes #60258
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

vmware_guest_tools_wait

##### ADDITIONAL INFORMATION

Will only return VMware tools related guest info and tools info.
```paste below
ok: [localhost] => {
    "tools_facts": {
        "changed": true, 
        "failed": false, 
        "instance": {
            "vm_guest_fullname": "Microsoft Windows 10 (64-bit)", 
            "vm_guest_hostname": "DESKTOP-CR5CAD6", 
            "vm_guest_id": "windows9_64Guest", 
            "vm_hw_version": "vmx-14", 
            "vm_ipaddress": "10.10.10.10", 
            "vm_name": "dw_test_vm", 
            "vm_tools_install_status": "toolsOk", 
            "vm_tools_install_type": "guestToolsTypeMSI", 
            "vm_tools_last_install_count": 0, 
            "vm_tools_running_status": "guestToolsRunning", 
            "vm_tools_upgrade_policy": "manual", 
            "vm_tools_version": 10341, 
            "vm_tools_version_status": "guestToolsCurrent"
        }
    }
}
```

### CODE REVIEW

**Comment by Tomorrow9** [comment]
Hi @Akasurde @goneri @jillr, would you please review this change? Thanks.

**Review by jillr — CHANGES_REQUESTED** [review]
I don't disagree with the intent, however this will change the data being returned by this module which could be a breaking change for users if they are depending on these facts.  It would probably be better to deprecate this module and create a new one with the new behaviour.

It would also be nice to get tests for the new behaviour that we can run on the worldstream environment (as govcsim does not support VMware tools status reporting we do not have many tests for this module now).

**Comment by Tomorrow9** [comment]
> I don't disagree with the intent, however this will change the data being returned by this module which could be a breaking change for users if they are depending on these facts. It would probably be better to deprecate this module and create a new one with the new behaviour.
> 
> It would also be nice to get tests for the new behaviour that we can run on the worldstream environment (as govcsim does not support VMware tools status reporting we do not have many tests for this module now).

Ok, I see, it makes sense. So maybe a new module for getting vmware tools related info "vmware_guest_tools_info" can be created for this request. Thanks.

**Comment by Tomorrow9** [comment]
Submit a new PR #62860 for this. Thanks.

**Comment by Tomorrow9** [comment]
So I'll close this PR.

**Pull request closed without merging**
