### PR TITLE
PEP8 fixes for smartos module

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/smartos/imgadm.py
lib/ansible/modules/cloud/smartos/smartos_image_facts.py
lib/ansible/modules/cloud/smartos/vmadm.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by jasperla** [comment]
shipit

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
ready_for_review

**Comment by abadger** [comment]
Reviewed, looks good.

rebuild_merge

**Comment by abadger** [comment]
Merged to devel for 2.4.0.

**Comment by Akasurde** [comment]
@jasperla @abadger Thanks for review and merge.

**Pull request merged**
