### PR TITLE
yum: fix disable_excludes in repoquery fallback

### LINKED ISSUE #53134: Yum module does not properly disable excludes
##### SUMMARY
When using the yum module with the `disable_excludes=all` option it does not appear to properly disable the excludes and will still fail to find packages specified.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```
yum
```

##### ANSIBLE VERSION
```paste below
$ ansible --version
ansible 2.7.7
  config file = /home/MYUSER/ansible-playbooks/ansible.cfg
  configured module search path = [u'/home/MYUSER/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
Default ansible.cfg file

Tested on ansible 2.7.7 and 2.7.8

##### OS / ENVIRONMENT

Source and target OS are CentOS 7.6

##### STEPS TO REPRODUCE

Add `exclude=kernel*` to `/etc/yum.conf` then run the following task on a target system. An error will appear about being unable to find the kernel package.

```yaml
    - name: Upgrade kernel (CentOS)
      yum:
        disable_excludes: all
        name: "kernel-3.10.0-957.5.1.el7"
        state: present
        update_cache: true
```

##### EXPECTED RESULTS

I expect the kernel to get updated appropriately, or a specific version to be installed if specified otherwise along with the appropriate dependencies.

##### ACTUAL RESULTS

When providing a specific kernel version the following error occurs.

```paste below
FAILED! => {"changed": false, "msg": "No package matching 'kernel-3.10.0-957.5.1.el7' found available, installed or updated", "rc": 126, "results": ["No package matching 'kernel-3.10.0-957.5.1.el7' found available, installed or updated"]}
```
I need to actually run the following to do what I expect and a version number should be specified. But you can do the same by swapping install for update.

```yaml
    - name: Upgrade kernel (CentOS)
      command: "yum --disableexcludes=all install -y kernel-3.10.0-957.5.1.el7"
```

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes #53134

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

yum

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
@mkrizek code looks good, could probably use an integration test case though if we can recreate the scenario in which the fallback code needs to be executed.

**Comment by mkrizek** [comment]
@maxamillion recreating the scenario should require installing `rhn` yum plugin and excluding a package in `yum.conf`. I'll try to hack that into an integration test.

**Comment by mkrizek** [comment]
@maxamillion hrm, so this won't be that simple. Enabling `rhnplugin` gives me:
```
up2date_client.up2dateErrors.SSLCertificateFileNotFound: ERROR: can not find RHNS CA file: /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
```

I don't think it's worth adding the test. FWIW user confirmed the PR fixes the bug in the original issue. Any ideas?

**Comment by maxamillion** [comment]
@mkrizek I'm sorry, I don't follow why we need to involve rhn, the RHEL tests are done against ec2 instances which rely on RHUI. Alternatively, we could test this functionality against the CentOS docker containers in a block or with a conditional `include_tasks`. I'm open to which ever.

**Comment by mkrizek** [comment]
@maxamillion The incorrect behavior is triggered only when the `rhn` plugin is installed on the remote host - https://github.com/ansible/ansible/pull/53552/files#diff-b3479be3ff6d2becf34cc47a760ccfd4R1552 - that's when `repoquery` is used (for whatever historical reason/corner case).

**Comment by maxamillion** [comment]
@mkrizek ahhh ok, now I follow. 👍 

rebuild_merge

**Comment by mkrizek** [comment]
@maxamillion  Cool, thanks for the review!

**Pull request merged**
