### PR TITLE
Added zfs module

### PR DESCRIPTION
**Pull request by johanwiren**
Added a zfs module that handles file systems, volumes and snapshots.

Tested on FreeBSD 9.0

### CODE REVIEW

**Comment by mpdehaan** [comment]
Nice! in queue for review probably this weekend.

Thanks!

**Comment by bcoca** [comment]
will start testing on 8.0-8.2

**Comment by johanwiren** [comment]
Great!

**Comment by bcoca** [comment]
I can delete, create and change properties on mount, snapshots, all looks
good.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by johanwiren** [comment]
Nice, thanks for testing.

**Comment by mpdehaan** [comment]
merged, thanks everyone!

**Pull request merged**
