### PR TITLE
Fix CSRF handling in jenkins modules #61712

### LINKED ISSUE #61712: Jenkins Improved CSRF protection breaks some Ansible modules
##### SUMMARY

With Jenkins [2.192](https://jenkins.io/changelog/) and [LTS 2.176](https://jenkins.io/changelog-stable/) comes [SECURITY-626: Improved CSRF protection](https://jenkins.io/doc/upgrade-guide/2.176/#SECURITY-626).
This change breaks all scripts and utilities that have been using CSRF tokens (crumbs), including Ansible modules `jenkins_script` and `jenkins_plugin`: when trying to use one of these modules with Jenkins versions given above or newer, these modules fail with the message presented in "ACTUAL RESULTS" below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

jenkins_script
jenkins_plugin

##### ANSIBLE VERSION

```paste below
ansible 2.7.13
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/media/vbox/clients/enovos/ansible2/ansible.cfg) = True
ANSIBLE_PIPELINING(/media/vbox/clients/enovos/ansible2/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/media/vbox/clients/enovos/ansible2/ansible.cfg) = False
RETRY_FILES_ENABLED(/media/vbox/clients/enovos/ansible2/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 16.04.3 LTS x64

##### STEPS TO REPRODUCE

```yaml
# From examples in module docs
- name: Obtaining a list of plugins
  jenkins_script:
    script: 'println(Jenkins.instance.pluginManager.plugins)'
    user: admin
    password: admin
```

##### EXPECTED RESULTS

The task completes without error.

##### ACTUAL RESULTS

```paste below
fatal: [hostname]: FAILED! => {"changed": false, "msg": "HTTP error 403 HTTP Error 403: No valid crumb was included in the request", "output": ""}
```

### PR DESCRIPTION
**Pull request by plastikat**
##### SUMMARY

Fixes #61712.

In the context of [SECURITY-626](https://jenkins.io/doc/upgrade-guide/2.176/#SECURITY-626), the official upgrade guide suggests either using an API token instead of CSRF token (crumb) or retaining a session ID. Since the former potentially requires much more changes, the latter approach looks better. Please read individual commit *full* comments for more details.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

web_infrastructure

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jtyr** [comment]
I prefer PR #61672 because it's less invasive.

**Comment by plastikat** [comment]
I agree that #61672 is more generic and elegant. I did not dig that deep into Ansible internals, just tried to fix the modules.
One drawback though: #61672 does not fix `jenkins_script` module so far.

**Comment by hogarthj** [comment]
I do like the approach taken in the commit referenced in #61672 more ... but it does need a core change of course. There's no active API change though so it might be possible to select for backport.

I see no reason why a similar approach couldn't be taken for jenkins_script and it should be pretty trivial to adapt.

**Comment by plastikat** [comment]
> I see no reason why a similar approach couldn't be taken for jenkins_script

Neither do I. I already asked the author of #61672 if he could do it.

**Comment by plastikat** [comment]
Closing in favor of #61673.

**Pull request closed without merging**
