### PR TITLE
Additional network support for Cloudstack

### PR DESCRIPTION
**Pull request by PatTheSilent**
##### SUMMARY
Additional network support for Cloudstack

Add a `get_physical_network` method to Cloudstack module utilities.
Add a new `cs_physical_network` module - resubmit of #25647
Add a new `cs_traffic_type` module

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
module_utils/cloudstack.py
cs_physical_network
cs_traffic_type

##### ADDITIONAL INFORMATION
`get_physical_network` copies the logic of `get_network` from the same class. 
#25647 resubmitted - rebased with adaptation to new APIs
`cs_traffic_type` - new module providing support for Cloudstack Traffic Types

### CODE REVIEW

**Review by dpassante — APPROVED** [review]
Thanks for the contribution! Looks good to me.
Looking forward to your next PRs.

**Comment by dpassante** [comment]
shipit

**Comment by resmo** [comment]
code looks good, however, we should avoid having unused code. Please submit this with the one of the mentioned modules/improvements you want to contribute.

**Comment by resmo** [comment]
needs_info

**Comment by PatTheSilent** [comment]
@resmo I get the point. This will make this PR slightly more complicated. I wanted to avoid that so initially submitted only the `get_physical_network` bit, but that might not have been the best take.
I needed to add both `cs_physical_network` and `cs_traffic_type` because of a dependency between them.

**Comment by PatTheSilent** [comment]
@resmo @dpassante I'll close this PR and reorganize this slightly...

**Pull request closed without merging**
