### PR TITLE
Fix setup.py to work with 'pip install -e .'

### PR DESCRIPTION
**Pull request by leth**
This should allow you to install ansible in editable mode.

Caveat: If you already have the ansible 'modules' installed it will favour those over the ones from the 'editable' package.

### CODE REVIEW

**Comment by jctanner** [comment]
@leth thank you!

Tested with:

```
$ virtualenv piptest
$ source piptest/bin/activate
$ git clone https://github.com/ansible/ansible
$ cd ansible
$ pip install  -U -e .
$ ansible --version
ansible 1.5 (leth-editable_install 38681350e0) last updated 2013/12/16 14:11:33 (GMT -400)
```

**Comment by jlaska** [comment]
I'm unable to access any modules after testing ansible from within a virtualenv

```
# ansible-doc -l
```

UPDATE ...

When I test with a fresh virtualenv, things seem to work.

```
# virtualenv /tmp/my_virt_env
# source /tmp/my_virt_env/bin/activate
# pip install -U -e git+https://github.com/ansible/ansible.git@devel#egg=ansible
# ansible-doc ping
> PING

  A trivial test module, this module always returns `pong' on
  successful contact. It does not make sense in playbooks, but it is
  useful from `/usr/bin/ansible'

# Test 'webservers' status
ansible webservers -m ping
```

When I'm testing by installing from the sdist created tarball, things seem to be working still.

```
# virtualenv /tmp/my_virt_env
# source /tmp/my_virt_env/bin/activate
# pip install dist/ansible-1.5.tar.gz 
> PING

  A trivial test module, this module always returns `pong' on
  successful contact. It does not make sense in playbooks, but it is
  useful from `/usr/bin/ansible'

# Test 'webservers' status
ansible webservers -m ping
```

I suspect the problems I've experienced may be caused by a virtualenv created prior to this patch.  Verifying ...

**Comment by jctanner** [comment]
@leth this seems to have broken the ability to actually use ansible from the virtualenv ...

```
(piptest)jtanner@u1304:~$ ansible-doc ping
module ping not found in /usr/share/ansible

(piptest)jtanner@u1304:~$ ansible -i "localhost," localhost -c local -m ping
localhost | FAILED => module ping not found in /usr/share/ansible
```

If you can fix the library path, open a new PR please.

**Comment by leth** [comment]
@jctanner Are you still set up to reproduce this issue?

Could you post some more info on your environment when this is failing:

```
which -a ansible-doc
which -a ansible-playbook
pip --version
virtualenv --version
Does something like virtualenv/share/ansible exist? It might be virtualenv/usr/share/ansible.
```

Modules will not load from the editable install if `<virtualenv>/share/ansible` exists; I couldn't think of a better compromise at the time. Perhaps if this is causing the issue we'll be able to find a better solution.

**Comment by holmboe** [comment]
@leth I am seeing the same result as @jctanner inside a virtualenv.

``` bash
(ansible)nn@wink:~/venvs/ansible git:wink$ which -a ansible-doc
/home/nn/venvs/ansible/bin/ansible-doc
(ansible)nn@wink:~/venvs/ansible git:wink$ which -a ansible-playbook
/home/nn/venvs/ansible/bin/ansible-playbook
(ansible)nn@wink:~/venvs/ansible git:wink$ pip --version
pip 1.2.1 from /home/nn/venvs/ansible/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg (python 2.7)
(ansible)nn@wink:~/venvs/ansible git:wink$ virtualenv --version
1.8.4
(ansible)nn@wink:~/venvs/ansible git:wink$ ls -ld share/ansible/
drwxrwxr-x 18 nn nn 4096 jan 30 13:39 share/ansible/
(ansible)nn@wink:~/venvs/ansible git:wink$ ansible --version
ansible 1.4.4
```

**Comment by holmboe** [comment]
I had to configure `library` in the `ansible.cfg`.

``` ini
library        = /home/nn/venvs/ansible/share/ansible
```

Sorry for the noise.

**Comment by leth** [comment]
@holmboe:
If I understand correctly, my changes were reverted, so unless you've re-introduced them somehow, you might not have them.

That config change shouldn't have been necessary with my changes to `lib/ansible/constants.py`.

However @jctanner indicated that things weren't working for him.
If you feel like looking into it further, that file is a good place to start looking.

**Pull request merged**
