### PR TITLE
Added possibility to filter hosts from a group, with a regex

### PR DESCRIPTION
**Pull request by gregorg**
Added the possibility to filter hosts in a group with a regex.
I suggest to use yet another special char after groupname: ~

Usage in group pattern: group~filterpattern

For example:
ansible group~server-0[1236] -m ping
ansible web~proxy -m ping
ansible web~(proxy|frontend) -m ping

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi,

This is interesting.

In the interest of making things consistent, I think this is more or less what is supplied with --limit, as if it were specifiable in a playbook, instead of the command line, like so:

   hosts: webservers
   limit:  server[0:123]

Of course, it's not possible to specify --limit in the play now, but it should be.

(Hosts is an OR criteria, and then it must also (AND) be in the limit group)

Your example becomes a little tricky because limit accepts host ranges, in [start:end] format, so character classes are perhaps a problem for it.

I general, I _think_ what we want to do is make it work exactly like you specified the --limit on the command line, and if the --limit was ALSO set on the command line AND in the playbook, it would limit _further_.   

Does this make sense?

**Comment by gregorg** [comment]
Hi,

true, it could be handled by --limit, however the good in my version is that it is quick to filter, and ~ is commonly used for regex. I'm switching from my current tool to ansible, and I'm often using a syntax to do commands on limited generated hosts list.

So, it's the way I used it, to quickly do something on some hosts.

You suggest to merge this tips to --limit, and add --limit to the CLI, right ? If so, --limit could start with a ~ to set it to a regex filter ?
Then, I think il should be good to add --limit syntax to CLI , and a ~ for a regex filter like that:
ansible web[0:123] -m ping
ansible web~proxy-0[123] -m ping

What do you think about that ?

**Comment by mpdehaan** [comment]
I think we're mostly on the same page now.

(A) 

one correction...

--limit is already in the CLI

(B)

Currently it uses shell globs.  I would suspect the only thing we'd want to accept is the string _starting_ with "~" and if found it could use regexes instead of shell globs

(C)

If we add this in one place where we take shell globs, we should make it work everywhere, which means making a match function in utils.

(D)

I also suggested that, per your usage, we maybe make the plumbing behind --limit accessible to individual plays in the YAML as well as the CLI, but it seems per the above we want to do B&C first.

**Comment by mpdehaan** [comment]
Also note, we're past the feature freeze for 0.9 (releasing Friday), so this is in queue for 1.0 (next approximately monthly release)

**Comment by gregorg** [comment]
A: I realize that just after posting, sorry.
B&C : ok I will submit a new patch for that.

**Comment by mpdehaan** [comment]
great, I will close this one so we don't merge it accidentally.   Thanks!

**Pull request closed without merging**
