### PR TITLE
Compile role with parents in the task's dependency chain

### LINKED ISSUE #39543: include_role is excluded when another role is excluded from playbook via a when
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- include_role

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dave/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dave/ansible_issue/venv/lib/python2.7/site-packages/ansible
  executable location = /home/dave/ansible_issue/venv/bin/ansible
  python version = 2.7.11 (default, May 10 2017, 23:48:20) [GCC 4.8.4]

```

##### CONFIGURATION

- No configuration changes

##### OS / ENVIRONMENT

- Running from: Ubuntu 16.04
- Managing: Ubuntu 16.04

##### SUMMARY

The use of `include_role` gives a change in behaviour between ansible 2.3.2.0 and 2.5.2 where a playbook's roles are `role_a` and `role_b` but `role_b` is conditionally excluded using a `when` statement.

- `role_a` includes `role_x` using `include_role`
- `role_b` has a `meta` dependency on `role_a`

In 2.3.2.0, `role_x` would be executed when processing `role_a` from the playbook. But in 2.5.2.0, `role_x` is never executed as it appears that the fact that `role_b` is excluded causes `role_a` never to run `role_x` at all.

##### STEPS TO REPRODUCE

Run the `run.sh` script.

Folder structure:

```
.
├── playbook.yml
├── roles
│   ├── role_a
│   │   └── tasks
│   │       └── main.yml
│   ├── role_b
│   │   ├── meta
│   │   │   └── main.yml
│   │   └── tasks
│   │       └── main.yml
│   └── role_x
│       └── tasks
│           └── main.yml
└── run.sh

```

run.sh 
```
ansible-playbook -vvvv -i "localhost," -c local playbook.yml
```

playbook.yml
```
---

- hosts: localhost
  roles:
    - { role: role_a }
    - { role: role_b, when: some_variable | default(false) }
```

roles/role_a/tasks/main.yml
```
---

- debug:
    msg: "start of `role_a` before including `role_x`"

- include_role: 
    name: "role_x"

- debug:
    msg: "end of `role_a` after including `role_x`"
```

roles/role_b/meta/main.yml
```
---

dependencies:
- { role: role_a }
```

roles/role_b/tasks/main.yml
```
---

- debug:
    msg: "Not expecting to see this as `role_b` is conditionally excluded"
```

roles/role_x/tasks/main.yml
```
---

- debug: 
    msg: "Should see this as it's included by `role_a`"

```

##### EXPECTED RESULTS

Expected that `role_x` should be included as it's included by `role_a` using `include_role`.  It appears that this worked fine pre-ansible 2.4.  The expected results below are the output from running against ansible 2.3.2.0.  

```
Using /etc/ansible/ansible.cfg as config file
Set default localhost to localhost
Loading callback plugin default of type stdout, v2.0 from /home/dave/ansible-issue/venv/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: playbook.yml **********************************************************************************************************
1 plays in playbook.yml

PLAY [localhost] ****************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************
Using module file /home/dave/ansible-issue/venv/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dave
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dave/.ansible/tmp/ansible-tmp-1525149586.82-91168693697018 `" && echo ansible-tmp-1525149586.82-91168693697018="` echo /home/dave/.ansible/tmp/ansible-tmp-1525149586.82-91168693697018 `" ) && sleep 0'
<localhost> PUT /tmp/tmp4lLLCI TO /home/dave/.ansible/tmp/ansible-tmp-1525149586.82-91168693697018/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/dave/.ansible/tmp/ansible-tmp-1525149586.82-91168693697018/ /home/dave/.ansible/tmp/ansible-tmp-1525149586.82-91168693697018/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/dave/.ansible/tmp/ansible-tmp-1525149586.82-91168693697018/setup.py; rm -rf "/home/dave/.ansible/tmp/ansible-tmp-1525149586.82-91168693697018/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [role_a : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_a/tasks/main.yml:3
ok: [localhost] => {
    "msg": "start of `role_a` before including `role_x`"
}

TASK [role_x : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_x/tasks/main.yml:3
ok: [localhost] => {
    "msg": "Should see this as it's included by `role_a`"
}

TASK [role_a : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_a/tasks/main.yml:9
ok: [localhost] => {
    "msg": "end of `role_a` after including `role_x`"
}

TASK [role_x : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_x/tasks/main.yml:3
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [role_b : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_b/tasks/main.yml:3
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

```

##### ACTUAL RESULTS

`role_x` is completely excluded when running ansible 2.5.2

```
ansible-playbook 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dave/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dave/ansible-issue/venv/lib/python2.7/site-packages/ansible
  executable location = /home/dave/ansible-issue/venv/bin/ansible-playbook
  python version = 2.7.11 (default, May 10 2017, 23:48:20) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Set default localhost to localhost
Parsed localhost, inventory source with host_list plugin
Loading callback plugin default of type stdout, v2.0 from /home/dave/ansible-issue/venv/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: playbook.yml **********************************************************************************************************
1 plays in playbook.yml

PLAY [localhost] ****************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************
task path: /home/dave/ansible-issue/playbook.yml:3
Using module file /home/dave/ansible-issue/venv/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dave
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dave/.ansible/tmp/ansible-tmp-1525149343.05-259629280602103 `" && echo ansible-tmp-1525149343.05-259629280602103="` echo /home/dave/.ansible/tmp/ansible-tmp-1525149343.05-259629280602103 `" ) && sleep 0'
<localhost> PUT /home/dave/.ansible/tmp/ansible-local-9168yYaYW2/tmpcFzN2D TO /home/dave/.ansible/tmp/ansible-tmp-1525149343.05-259629280602103/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/dave/.ansible/tmp/ansible-tmp-1525149343.05-259629280602103/ /home/dave/.ansible/tmp/ansible-tmp-1525149343.05-259629280602103/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/dave/.ansible/tmp/ansible-tmp-1525149343.05-259629280602103/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/dave/.ansible/tmp/ansible-tmp-1525149343.05-259629280602103/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [role_a : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_a/tasks/main.yml:3
ok: [localhost] => {
    "msg": "start of `role_a` before including `role_x`"
}

TASK [role_a : include_role] ****************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_a/tasks/main.yml:6

TASK [role_x : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_x/tasks/main.yml:3
skipping: [localhost] => {
    "skip_reason": "Conditional result was False"
}

TASK [role_a : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_a/tasks/main.yml:9
ok: [localhost] => {
    "msg": "end of `role_a` after including `role_x`"
}

TASK [role_b : debug] ***********************************************************************************************************
task path: /home/dave/ansible-issue/roles/role_b/tasks/main.yml:3
skipping: [localhost] => {
    "skip_reason": "Conditional result was False"
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0 

```

### LINKED ISSUE #47023: Loss of variable value when include role depth exceed 3
##### SUMMARY

Loss of variable value when include role depth exceed 3
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

roles
templating

##### ANSIBLE VERSION

```
2.7.0

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 18.04 running ansible, to pilot an ubuntu 16.04 server

##### STEPS TO REPRODUCE

i made these roles to reproduce and isolate this : 

Role A : 
- defaults : 
```
---
  myvariable: " value set in role A, evaluated in {{ role_name }} - defaults"
```
- tasks : 
```
---

  - name: "myvariable in {{ role_name }}"
    debug:
      msg: "{{ myvariable }}"

  - include_role:
      name: Role_B

```
Role B : 
- tasks : 
```
---

  - name: "myvariable in {{ role_name }}"
    debug:
      msg: "{{ myvariable }}"

  - include_role:
      name: Role_C

```
- vars :
```
---
  myvariable: " value set in role B, evaluated in {{ role_name }} - vars"

```

Role C : 
- tasks : 
```
---

  - name: "myvariable in {{ role_name }}"
    debug:
      msg: "{{ myvariable }}"

  - include_role:
      name: Role_D

```
Role D : 
- tasks : 
```
---

  - name: "myvariable in {{ role_name }}"
    debug:
      msg: "{{ myvariable }}"

  - include_role:
      name: Role_E

```
Role E : 
- tasks : 
```
---

  - name: "myvariable in {{ role_name }}"
    debug:
      msg: "{{ myvariable }}"

```

##### EXPECTED RESULTS

myvariable keep it's value through include_role : 
**value set in role B, evaluated in Role_E - vars** would be fine
**value set in role A, evaluated in Role_E - defaults** is not correct

##### ACTUAL RESULTS

```PLAY [test-server] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************
ok: [test-server]

TASK [Role_A : myvariable in Role_A] ************************************************************************************************************************************************************************
ok: [test-server] => {
    "msg": " value set in role A, evaluated in Role_A - defaults"
}

TASK [include_role : Role_B] ********************************************************************************************************************************************************************************

TASK [Role_B : myvariable in Role_B] ************************************************************************************************************************************************************************
ok: [test-server] => {
    "msg": " value set in role B, evaluated in Role_B - vars"
}

TASK [include_role : Role_C] ********************************************************************************************************************************************************************************

TASK [Role_C : myvariable in Role_C] ************************************************************************************************************************************************************************
ok: [test-server] => {
    "msg": " value set in role B, evaluated in Role_C - vars"
}

TASK [include_role : Role_D] ********************************************************************************************************************************************************************************

TASK [Role_D : myvariable in Role_D] ************************************************************************************************************************************************************************
ok: [test-server] => {
    "msg": " value set in role B, evaluated in Role_D - vars"
}

TASK [include_role : Role_E] ********************************************************************************************************************************************************************************

TASK [Role_E : myvariable in Role_E] ************************************************************************************************************************************************************************
ok: [test-server] => {
    "msg": " value set in role A, evaluated in Role_E - defaults"
}

PLAY RECAP **************************************************************************************************************************************************************************************************
test-server                : ok=6    changed=0    unreachable=0    failed=0   


```

### LINKED ISSUE #51660: include_role erroneously skipped when including role is a dependency of a conditionally skipped role
##### SUMMARY
The role test_1 uses include_role on test_2. When the role test_3, which depends on test_1, is a conditional (skipped) role in the playbook, the role test_2 is erroneously skipped.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/suberjus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Description:    Ubuntu 16.04.5 LTS

##### STEPS TO REPRODUCE

directory structure
```
├── roles
│   ├── test_1
│   │   └── tasks
│   │       └── main.yml
│   ├── test_2
│   │   └── tasks
│   │       └── main.yml
│   └── test_3
│       ├── meta
│       │   └── main.yml
│       └── tasks
│           └── main.yml
└── test.yml
```
./test.yml
```
---
- hosts: localhost
  roles:
    - test_1
    - role: test_3
      when: false
```
./roles/test_1/tasks/main.yml
```
---

- debug:
    msg: 'test_1'

- include_role:
    name: test_2

```
./roles/test_2/tasks/main.yml
```
---
- debug:
    msg: 'test_2'

```
./roles/test_3/meta/main.yml
```
---
dependencies:
  - test_1

```
./roles/test_3/tasks/main.yml
```
---
- debug:
    msg: 'test_3'

```

##### EXPECTED RESULTS

I expect the role test_1 to executed fully, including test_2, and test_3 should be skipped.
```
PLAY [localhost] ************************************************************************

TASK [Gathering Facts] ******************************************************************
ok: [localhost]

TASK [test_1 : debug] *******************************************************************
ok: [localhost] => {
    "msg": "test_1"
}

TASK [include_role : test_2] ************************************************************

TASK [test_2 : debug] *******************************************************************
ok: [localhost] => {
    "msg": "test_2"
}

TASK [test_3 : debug] *******************************************************************
skipping: [localhost]

PLAY RECAP ******************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

The role test_1 runs; however the included role test_2 is erroneously skipped. test_3 is skipped as expected.

```paste below
PLAY [localhost] ************************************************************************

TASK [Gathering Facts] ******************************************************************
ok: [localhost]

TASK [test_1 : debug] *******************************************************************
ok: [localhost] => {
    "msg": "test_1"
}

TASK [include_role : test_2] ************************************************************

TASK [test_2 : debug] *******************************************************************
skipping: [localhost]

TASK [test_3 : debug] *******************************************************************
skipping: [localhost]

PLAY RECAP ******************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Ensure the parent roles are part of the task's dependency chain before inheriting from them.

Fixes #51660
Fixes #39543
Fixes #47023

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by s-hertel** [comment]
I noticed my initial approach also fixed #75304, so after digging quite a lot (I was afraid it might have unintended side effects) I put it back. It changes 3 things:
1. roles inherit from parents in the current task dep chain (before could inherit from roles outside of it: #39543)
2. role parents are of any depth (before were ignored beyond depth of 3: #47023)
3. the order of the role parents reflects the task dep chain

I can change the changelog fragment section from `bugfixes` to `breaking_changes` if others think that's a good idea, but since the original behavior is unintuitive and subtle I doubt this would break anything that isn't accidentally relying on it.

As a side note, since compiling the role no longer uses the role attr `_parents`, all associated `_parents` code can be removed without changing any built-in behavior. The only other place it was used is `Role.set_loader`, which is dead code: it's called from `Block.set_loader` if the block doesn't have a parent - which only occurs when the PlayIterator is instantiated and the setup_task is created or when noop tasks are created - neither of which have an associated role.

**Comment by bcoca** [comment]
and that case should be fixed by having the 'play' be the parent for the gather_facts block

**Comment by s-hertel** [comment]
> and that case should be fixed by having the 'play' be the parent for the gather_facts block

Not sure if there's something to fix here. The setup block has a `_play` attr, and the parent parameter is `parent_block`, which seems type-specific. I  think I phrased that last part badly though, trying again:

The only other place it was used is Role.set_loader, which is dead code: it's called from Block.set_loader if the block doesn't have a parent but does have a role.
The noop task blocks and the PlayIterator's setup_task block are the only places blocks have no parents, but also have no role associated.

**Review by sivel — APPROVED** [review]

**Comment by s-hertel** [comment]
rebuild_merge

**Comment by samdoran** [comment]
Coverage is currently busted in `devel`. You can re-run with `ci_complete` if you want, but avoid running with coverage until it gets fixed.

**Pull request merged**
