### PR TITLE
Pass CSRF token along with Jenkins POST requests

### PR DESCRIPTION
**Pull request by varadharajan**
##### SUMMARY
The `jenkins_script` module currently does not pass on CSRF crumb along with the POST request and hence the module would fail on servers where CSRF protection is enabled. This PR fixes it by determining whether CSRF protection is enabled or not, and then passes on the token accordingly.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
jenkins_script

##### ANSIBLE VERSION
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/varadharajan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

##### ADDITIONAL INFORMATION
More information [here](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Script+Console#JenkinsScriptConsole-RemoteaccesswithCSRFprotectionenabled)

### CODE REVIEW

**Comment by varadharajan** [comment]
CC @gundalow

**Comment by gundalow** [comment]
@varadharajan Thanks for the PR, I just merged this, it was written by someone else

@hogarthj could you please remove this within the few days so we can include the fixed version in the 2.3.0 release?


Note to mergers: This mode was added in 2.3, so will need merging into `devel` and `stable-2.3`

**Comment by hogarth-sv** [comment]
@gundalow sorry, what do you need me to do?

@varadharajan thanks for investigating this and the patch, it was on my todo list to add CSRF crumbs in the future and you just solved it for me :)

**Comment by varadharajan** [comment]
@hogarthj  You're welcome and Thanks for this module. It just saved me few hours of work :)

**Comment by hogarth-sv** [comment]
@varadharajan Don't know if you've seen it yet, but this was my article about using it after I wrote it - you might be able to crib a couple of easy scripts and save some time :)

https://www.hogarthuk.com/?q=node/16

I'm using it against Bitbucket Data Centre here and it works beautifully :)

Oh and if you need to work with a dict or list I can confirm that passing in a dict to an arg in jenkins_script via:
```
- name: do stuff
  jenkins_script:
    script: "{{ my_script }}"
    args:
      dict_type: "{{ my_dict | to_json }}"
```

and then in the groovy doing:
```
import groovy.json.JsonSlurper

def my_dict_as_text = '''
${my_dict}
'''

def imported_dict = new JsonSlurper().parseText(my_dict_as_text)
```

works to get more complicated data structures in than just a basic string replacement if a simple basic variable

**Comment by gundalow** [comment]
@hogarthj Just review. If this needs to be fixed in Ansible 2.3 it needs to be reviewed and merged within the next 24 hours

**Comment by hogarth-sv** [comment]
Tested both with and without CSRF protection enabled.

Got the expected failure with CSRF enabled without this update.

With this update plugin worked with CSRF enabled.

shipit

**Comment by hogarth-sv** [comment]
@gundalow don't think ansibot listens to me

**Comment by gundalow** [comment]
hogarthj  is the maintainer (bot has now been updated), so merging

**Comment by gundalow** [comment]
Merged into `devel` and `stable-2.3` https://github.com/ansible/ansible/commit/d6a8f10a70829e3efc7c8966622bf888c6c7793f

So this will be part of `2.3.0`

**Pull request merged**
