### PR TITLE
Add Source Mage GNU/Linux facts

### PR DESCRIPTION
**Pull request by vaygr**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

- `lib/ansible/module_utils/facts.py`

##### ANSIBLE VERSION

```2.2.0.0```

##### SUMMARY

Add facts for SMGL, after [adding Sorcery support](https://github.com/ansible/ansible/pull/19072) to Ansible.

### CODE REVIEW

**Comment by vaygr** [comment]
`service_mgr` fact is in a [separate PR](https://github.com/ansible/ansible/pull/19231) responsible for the init system support.

**Comment by robinro** [comment]
@vaygr Please consider also creating a testcase for this in https://github.com/ansible/ansible/blob/devel/test/units/module_utils/test_distribution_version.py

Overall I'm not sure it's a good idea to add this change, but would recommend to use lsb_release versioning instead, since it is standardized between different distributions and adding specialized code for lesser-known distributions is a lot harder to maintain.

**Comment by bcoca** [comment]
@vaygr please clean your history, you have a merge commit

**Comment by vaygr** [comment]
accidental force push has auto-closed this PR.

**Comment by vaygr** [comment]
@bcoca sorry about that, done.

**Pull request merged**
