### PR TITLE
Azure Inventory: Use tenant in UserPassCredentials if set.

### PR DESCRIPTION
**Pull request by hoffmann**
If you have multiple Tenants you need to set the tenant in https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py otherwise the azure_rm.py call will fail.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible/contrib/inventory/azure_rm.py

##### ANSIBLE VERSION

```
2.2.1.0
```

##### SUMMARY
If you have multiple Tenants you need to set the tenant in https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py otherwise the azure_rm.py call will fail.

```
$ python azure_rm.py
Traceback (most recent call last):
  File "azure_rm.py", line 802, in <module>
    main()
  File "azure_rm.py", line 799, in main
    AzureInventory()
  File "azure_rm.py", line 442, in __init__
    self.get_inventory()
  File "azure_rm.py", line 507, in get_inventory
    self._load_machines(virtual_machines)
  File "azure_rm.py", line 510, in _load_machines
    for machine in machines:
  File "/Users/ph/.virtualenvs/pydata/lib/python2.7/site-packages/msrest/paging.py", line 60, in __iter__
    for i in self.next():
  File "/Users/ph/.virtualenvs/pydata/lib/python2.7/site-packages/msrest/paging.py", line 92, in next
    self._response = self._get_next(self.next_link)
  File "/Users/ph/.virtualenvs/pydata/lib/python2.7/site-packages/azure/mgmt/compute/operations/virtual_machines_operations.py", line 626, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidAuthenticationTokenTenant
Message: The access token is from the wrong issuer XXXX'. It must match the tenant 'XXX' associated with this subscription. Please use the authority (URL) 'XXX' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
```

### CODE REVIEW

**Comment by jctanner** [comment]
cc @nitzmahone @jborean93

**Comment by trstringer** [comment]
This looks good to me.

**Comment by calfonso** [comment]
rebuild_merge

**Comment by samdoran** [comment]
rebuild_merge

**Pull request merged**
