### PR TITLE
Add docker_container_facts module

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Allows to retrieve facts on a docker container. Allows to determine whether it exists, and if it does, provides the output of `docker inspect` (obtained via API) in the result.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
docker_container_facts

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
Tests will fail until #48061 is merged.

**Comment by DBendit** [comment]
LGTM

**Comment by gundalow** [comment]
@felixfontein Thank you for the PR
@DBendit Thanks for the review.

Merged into `devel` for release in Ansible 2.8

**Comment by felixfontein** [comment]
@DBendit thanks for your review!
@gundalow thanks again for merging!

**Pull request merged**
