### PR TITLE
Add missing gcp modules to module defaults

### PR DESCRIPTION
**Pull request by mollux**
##### SUMMARY

the module defaults for GCP aren't up-to date with the current GCP modules, breaking the module defaults functionality for a lot of `gcp_*` modules.

* In PR #60172 the GCP Facts modules were changed to Info Modules. 
But the module defaults weren't updated, and still refer to the to the removed `gcp_*_facts` modules instead of `gcp_*_info`.
* Not all existing GCP modules are present in the module defaults

This PR changes all the `gcp_*_facts` references into `gcp_*_info`, and adds the missing `gcp_*` modules to the module defaults for GCP

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

module defaults for GCP

##### ADDITIONAL INFORMATION

Following playbooks throws an error about missing arguments, despite the fact that they are present in the `module_defaults`

```yaml

- name: Setup GCP components
  hosts: localhost
  connection: local
  gather_facts: no
  module_defaults:
    gcp_compute_instance_info:
      zone: europe-west1-b
    group/gcp:
      project: project-name-123456
      auth_kind: serviceaccount
      service_account_file: "../credentials.json" 
      scopes:
        - https://www.googleapis.com/auth/compute
  tasks:
    - name: load instance info
      gcp_compute_instance_info:
        filters:
          - name=test-instance-1
      register: test_instance

```

```yaml
- name: Setup GCP components
  hosts: localhost
  connection: local
  gather_facts: no
  module_defaults:
    group/gcp:
      project: project-name-123456
      auth_kind: serviceaccount
      service_account_file: "../credentials.json" 
      scopes:
        - https://www.googleapis.com/auth/compute
  tasks:
    - name: create an instance
      gcp_filestore_instance:
        name: test_object
        zone: us-central1-b
        tier: PREMIUM
        file_shares:
        - capacity_gb: 2660
          name: share1
        networks:
        - network: default
          modes:
          - MODE_IPV4
        state: present
```

```paste below

PLAY [Setup GCP components] ******************************************************************************************************************************************************************************************************************

TASK [load instance info] ********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "missing required arguments: zone, auth_kind"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
```
PLAY [Setup GCP components] ******************************************************************************************************************************************************************************************************************

TASK [create an instance] *********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "missing required arguments: auth_kind"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by mollux** [comment]
!component =lib/ansible/config/manager.py

**Comment by mollux** [comment]
bot_status

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@rambleraptor Can you check once and let me know? CI failures are not related to this change. Thanks in advance.

**Review by rambleraptor — APPROVED** [review]
Looks good!

**Comment by Akasurde** [comment]
@mollux Thanks for the contribution. @rambleraptor Thanks for the review.

**Pull request merged**
