### PR TITLE
new module: azure_rm_rediscache

### PR DESCRIPTION
**Pull request by yungezz**
##### SUMMARY

add new module azure_rm_rediscache

##### ISSUE TYPE

- New Module Pull Request

##### ANSIBLE VERSION

```paste below
ansible 2.8
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@nitzmahone @zikalino

**Comment by yungezz** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@nitzmahone @zikalino Could you help review this PR? yungezz request review from youi

**Comment by Fred-sun** [comment]
@zikalino Could you can review this PR and push this PR to merged? Thanks!

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
