### PR TITLE
LB backend pool support for Azure NIC module

### LINKED ISSUE #29607: azure_rm_networkinterface cannot create interface if virtual network is in different resource group
From @amz on 2016-10-06T09:59:42Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

azure_rm_networkinterface module
##### ANSIBLE VERSION

ansible 2.1.2.0
  config file = /home/amz/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### SUMMARY

Cannot create network interface to connect to virtual network in other resource group.
##### STEPS TO REPRODUCE

Create task:

```
- name: Create a network interface with minimal parameters
  azure_rm_networkinterface:
      name: "interfaceName"
      resource_group: "ansibleManaged"
      virtual_network_name: "sharedNetwork"
      subnet_name: default
      location: "northeurope"
```

##### EXPECTED RESULTS

Create network interface. Virtual Network in ARM are restricted to region no to resource group. It should be possible to access Virtual Network in same region.
##### ACTUAL RESULTS

Interface creation task faile because it can't find virtual network in 

```
TASK [azure : Create a network interface with minimal parameters] **************
task path: /home/amz/ansible/roles/azure/tasks/create_azure.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: amz
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441 `" && echo ansible-tmp-1475747675.66-52569430125441="` echo $HOME/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpguR_EI TO /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/azure_rm_networkinterface
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/ /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/azure_rm_networkinterface && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'LANG=pl_PL.UTF-8 LC_ALL=pl_PL.UTF-8 LC_MESSAGES=pl_PL.UTF-8 python /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/azure_rm_networkinterface; rm -rf "/home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"ad_user": null, "append_tags": true, "client_id": null, "location": "northeurope", "name": "interfaceName", "open_ports": null, "os_type": "Linux", "password": null, "private_ip_address": null, "private_ip_allocation_method": "Dynamic", "profile": null, "public_ip": true, "public_ip_address_name": null, "public_ip_allocation_method": "Dynamic", "resource_group": "ansibleManaged", "secret": null, "security_group_name": null, "state": "present", "subnet_name": "default", "subscription_id": null, "tags": null, "tenant": null, "virtual_network_name": "sharedNetwork"}, "module_name": "azure_rm_networkinterface"}, "msg": "Error: fetching subnet default in virtual network sharedNetwork - The Resource 'Microsoft.Network/virtualNetworks/sharedNetwork' under resource group 'ansibleManaged' was not found."}

```

Copied from original issue: ansible/ansible-modules-core#5172

### PR DESCRIPTION
**Pull request by siaomingjeng**
##### SUMMARY

azure_rm_networkinterface:
1. Support creating Azure network interface using subnet from a different resource group (Fixes #29607);
2. Support load balancer backend address pool. (mentioned in #2586)

azure_rm_loadbalancer:
1. Add support to use private ip as frontend
2. Fix tags did not work
3. Add inbound NAT rule support
4. Add support for naming frontend, backend, rule and inbound NAT rule
5. Support get private IP from a subnet which is in a different resource group

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/raymond/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### ADDITIONAL INFORMATION
EXAMPLES = '''
    - name: Create a network interface in a resource_group with the subnet from a different resource group and a load balancer backend pool.
      azure_rm_networkinterface:
            name: nic001
            resource_group: Testing
            subnet_resource_group: Testing2
            virtual_network_name: vnet001
            subnet_name: subnet001
            load_balancer: loadbalancer001
            load_balancer_backend_pool: backend001

  Final Testing Ansible Version:
    ansible 2.5
    ansible 2.4.1

### CODE REVIEW

**Comment by kyliel** [comment]
@siaomingjeng , could you please rebase it? 
@yuwzho , please help review the code. Something may help on the case you working on for LB.

**Comment by siaomingjeng** [comment]
@kyliel can you explain a bit about the conflicts?  I am not clear why? 
This is my first time contribution. 
Thanks very much

**Comment by zikalino** [comment]
@siaomingjeng i think you have to rebase your pr. pls follow this document to do this:
http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

**Comment by yuwzho** [comment]
duplicate_of #35592

**Pull request closed without merging**
