### PR TITLE
add azure service principle objectid lookup plugin

### PR DESCRIPTION
**Pull request by yungezz**
##### SUMMARY

add azure service principal objectId lookup plugin.

when user using azure_keyvault module to grant access policy to service principal, need to pass in service principal object_id. while azure credential azure_client_id is service principal application id. So user will need a lookup plugin to lookup object_id from service principal application id.

##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
ansible 2.7
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by yungezz** [comment]
ready_for_review

**Comment by yungezz** [comment]
@mattclay  @nitzmahone  this pr is to add azure service principal object id lookup plugin. I separate it out from original keyvault bug fixing pr https://github.com/ansible/ansible/pull/38084 per Jordan's suggestion. Pls help to review. thanks.

**Comment by mattclay** [comment]
@yungezz Can you please include an integration test for this lookup plugin?

**Comment by nitzmahone** [comment]
So the biggest issue with merging this as-is is that it only supports one of the many various ways we allow authentication. With the "inventory cloud" thing we're hoping to do in 2.7, the authentication would be completely abstracted from the content (as it should be), so it could be either a no-args "get current service principal object ID" lookup, or a more generic lookup of various types of object IDs. So we probably want to hold off on this until the inventory cloud thing is working- otherwise supporting all the various authtypes will make usage of the lookup awful with all the args it will require.

**Comment by yungezz** [comment]
@nitzmahone thanks for the comments. the 'inventory cloud' sounds great. While before that is ready, we'll need this lookup plugin to unblock azure_rm_keyvaultkey and azure_rm_keyvaultsecret bug fixing. Testing need this lookup plugin to get service principal object_id. As you know, user cannot use azure_rm_keyvaultkey and azure_rm_keyvaultsecret now because of known bugs. Can we get this merged, at least it works at current situation. Once inventory cloud ready, we'll do azure service principal support on it. Any comments?

**Comment by yungezz** [comment]
please check https://github.com/ansible/ansible/pull/38084 for usage of this plugin.

**Comment by yungezz** [comment]
@mattclay  test added

**Comment by mattclay** [comment]
If we can't wait for this to be merged as a lookup plugin, it could be added to the [library](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#embedding-modules-and-plugins-in-roles) for the test role that needs it as a way to unblock work there. Then update those tests to use this plugin in this PR.

**Comment by yungezz** [comment]
@mattclay  @nitzmahone  need your input  on how to proceed this PR. I want  to merge this lookup plugin now, reason is that  with this lookup plugin, i can unblock azure_rm_keyvaultkey/secrets bug fixing. For cloud as inventory  @nitzmahone  mentioned, we can support azure after it's ready.  Pls let us know your thoughts. Looking forward to your review.

**Comment by yungezz** [comment]
@mattclay @nitzmahone

**Comment by yungezz** [comment]
close this PR,  discussed with @nitzmahone  @jborean93  on where to put this lookup plugin. Matt and  Jordan suggested put this lookup plugin directly into test to unblock bug fxing of key vault module. The reason of not putting this plugin into  lookup folder is as below quoted from Matt.
```
With the "inventory cloud" thing we're hoping to do in 2.7, the authentication would be completely abstracted from the content (as it should be), so it could be either a no-args "get current service principal object ID" lookup, or a more generic lookup of various types of object IDs. 
```

So close this PR, and put the lookup plugin into test at PR #41683

**Pull request closed without merging**
