### PR TITLE
Azure acs module (azure_rm_acs.py)

### PR DESCRIPTION
**Pull request by julienstroheker**
##### SUMMARY

- Adding the the azure_rm_acs module

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- azure_rm_acs.py
##### ANSIBLE VERSION

```
ansible 2.4.0 (az-acs e37e15468b) last updated 2017/08/18 00:14:15 (GMT +000)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible/lib/ansible
  executable location = /app/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/34501/39/tests

**Comment by julienstroheker** [comment]
@mattclay it seems your subscription has some limitations : 

```
{ "code": "QuotaExceeded", "message": "Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 0, Additional requested: 22." }, { "code": "QuotaExceeded", "message": "Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 0, Additional requested: 22." }
```

Do you want me to try to reduce the number & size of the Vms?

Thanks

**Comment by mattclay** [comment]
@julienstroheker Yes, please use the smallest number and size of VMs necessary to run the tests.

**Comment by julienstroheker** [comment]
Ok, I'll try

**Comment by julienstroheker** [comment]
Cannot run the Integration test back to back (not enough resources)... 
Have to wait that the resource group is deleted.

**Comment by mattclay** [comment]
@julienstroheker The integration test should use block/always to ensure that the resources used during the test are removed when the test ends. This will help free up resources even if the test fails. There's no guarantee the cleanup will succeed, but making sure it will run even on test failure is an improvement.

**Comment by mattclay** [comment]
CI failure in integration test `test/integration/targets/azure_rm_acs/tasks/main.yml:45 / [localhost] azure: azure_rm_acs : Assert the ACS instance is well scaled that=[u'results.changed', u'results.state.agent_pool_profiles.count == 2']`:

```
{
    "assertion": "results.state.agent_pool_profiles.count == 2", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```

**Comment by julienstroheker** [comment]
Got the quota limits issue. Will retry in few minutes
```
'[\r\n  {\r\n    \"code\": \"QuotaExceeded\",\r\n    \"message\": \"Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 10, Additional requested: 4.\"\r\n  },\r\n  {\r\n    \"code\": \"QuotaExceeded\",\r\n    \"message\": \"Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 10, Additional requested: 4.\"\r\n  }\r\n]'"
```

**Comment by mattclay** [comment]
We probably need to increase our quotas for the test account. However, looking at this test, I'm not sure why we're hitting the limit for a single test run.

@tstringer Any ideas?

**Comment by julienstroheker** [comment]
I think the limitation is per Region, so if this test is the running at the same time that you already have resources deployed (by another test) it will reach the limitations faster. 
In the last cases, there is already 10 CPU consumed by something else (other CI test?) and this test tries to deploy 4 more, since the limit is 10, it failed.

I will try to deploy in another region and see if it pass.

**Comment by julienstroheker** [comment]
Seems the problem in different region :(

**Comment by trstringer** [comment]
@julienstroheker @mattclay that's really odd. 10 seems really low 🤔  To confirm, Matt, can you run the following against the subscription? `$ az vm list-usage -l eastus --query "[?localName == 'Total Regional Cores'].{name:localName,current:currentValue,limit:limit}"`

What's even more peculiar, is what's using these 10 cores in your subscription (for that region)? Perhaps hop onto the portal and see what's going on there?

**Comment by mattclay** [comment]
@tstringer Yes, the limit is 10. Thanks for the command to query that.

@julienstroheker There isn't anything else using cores in the test account. So the only usage should be from multiple runs from this test. If the test fails part way through, it doesn't remove the resources it created, which means they'll be in use for about 1 hour until an automated cleanup pass removes them (out-of-band from CI). The test should be updated to use block/always to make sure that it always cleans up on exit.

**Comment by julienstroheker** [comment]
@mattclay Thanks for the info.
Just to be sure, QQ about the `block/always`, this setting will remove the resource group created by the test by it self or it will use the `state: absent` option from the module ?
Thanks

**Comment by mattclay** [comment]
@julienstroheker Just use `state: absent` for any resources created during the test. You shouldn't try to remove the resource group that was created before the test started.

**Comment by mattclay** [comment]
@julienstroheker Here's an example of a test using block/always for cleanup:

https://github.com/ansible/ansible/blob/devel/test/integration/targets/ec2_key/tasks/main.yml

**Comment by julienstroheker** [comment]
@mattclay the problem with the `state: absent` on this resource is the API for the delete function works like this : 

> Deletes the specified container service in the specified subscription and resource group. The operation does not delete other resources created as part of creating a container service, including storage accounts, VMs, and availability sets. All the other resources created with the container service are part of the same resource group and can be deleted individually.

As mentioning it is only removing the container service resource and not the other such as VMs, availability set, storage, etc...

https://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.containerservice.v2017_01_31.operations.html#azure.mgmt.compute.containerservice.v2017_01_31.operations.ContainerServicesOperations.delete

**Comment by mattclay** [comment]
Any resources created during the test, even indirectly, should be cleaned up in the always block.

**Comment by julienstroheker** [comment]
@tstringer any ideas how I can do that ? Since we discuted about it during the hackfest ?

**Comment by haroldwongms** [comment]
I understand we want to clean up from integration tests.  However, the way the API works for ACS, only the ACS object is deleted and not the associated cluster resources.  Is there a way to skip the integration tests or run them manually to avoid this issue?

**Comment by mattclay** [comment]
@haroldwongms Why not clean up the resources at the end of the integration test?

**Comment by nitzmahone** [comment]
rebuild_merge

**Pull request merged**
