### PR TITLE
Update nclu.py

### PR DESCRIPTION
**Pull request by permitanyany**
Added NCLU BGP Unnumbered Example
+label: ansible/ansible#40323

##### SUMMARY
Adding NCLU BGP Unnumbered Example

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
nclu

##### ANSIBLE VERSION
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']

##### ADDITIONAL INFORMATION
PR ansible/ansible#40323
PR ansible/community#311

### CODE REVIEW

**Comment by ericpulvino** [comment]
Looks good.

**Comment by IPvSean** [comment]
@ericpulvino @permitanyany 

there is a new requirement for all submitted PRs for the contest (and in general for networking doc PRs) to provide playbook output.  Since this is a new rule, and Cumulus VX is widely available and easy to use, I will go ahead and test the 5 PRs submitted by @permitanyany 

here is a simple playbook using your https://github.com/CumulusNetworks/cldemo-vagrant
```
cumulus@oob-mgmt-server:~$ cat test.yml
---
- name: test playbook for cumulus
  hosts: leaf01
  gather_facts: false
  tasks:
    - name: Add two EBGP neighbors using BGP Unnumbered
      nclu:
        commands:
            - add bgp neighbor swp51 interface remote-as external
            - add bgp neighbor swp52 interface remote-as external
        commit: true
```

The first thing I noticed is that on a clean install, BGP (and FRR for that matter) will actually fail with a bad error->

```
cumulus@oob-mgmt-server:~$ ansible-playbook test.yml

PLAY [test playbook for cumulus] ***************************************************************************************************************************************************************************

TASK [Add two EBGP neighbors using BGP Unnumbered] *********************************************************************************************************************************************************
fatal: [leaf01]: FAILED! => {"changed": false, "failed": true, "msg": "Failed on line add bgp neighbor swp51 interface remote-as external"}
	to retry, use: --limit @/home/cumulus/test.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
leaf01                     : ok=0    changed=0    unreachable=0    failed=1
```

Manually I did this on the leaf01 switch->

```
cumulus@leaf01:~$ net add bgp autonomous-system 65000
```

The playbook then works->
```
cumulus@oob-mgmt-server:~$ ansible-playbook test.yml

PLAY [test playbook for cumulus] ***************************************************************************************************************************************************************************

TASK [Add two EBGP neighbors using BGP Unnumbered] *********************************************************************************************************************************************************
changed: [leaf01]

PLAY RECAP *************************************************************************************************************************************************************************************************
leaf01                     : ok=1    changed=1    unreachable=0    failed=0
```

Are you guys OK with this behavior? (i.e. assuming BGP is on?)  I think you probably would want to change the example to this->

```
    - name: Add two EBGP neighbors using BGP Unnumbered
      nclu:
        commands:
            - add bgp autonomous-system 65000
            - add bgp neighbor swp51 interface remote-as external
            - add bgp neighbor swp52 interface remote-as external
        commit: true
```

or at least adding a comment

e.g.
```
# For full BGP Unnumbered configuration please see https://docs.cumulusnetworks.com/display/DOCS/Border+Gateway+Protocol+-+BGP
- name: Add two EBGP neighbors using BGP Unnumbered
  nclu:
    commands:
        - add bgp neighbor swp51 interface remote-as external
        - add bgp neighbor swp52 interface remote-as external
    commit: true
```

You can see an example of module documentation containing comments on the AWS  ec2 module http://docs.ansible.com/ansible/latest/modules/ec2_module.html

**Comment by IPvSean** [comment]
tagging https://github.com/ansible/community/issues/311, @permitanyany can you update this PR to reflect you are submitting against issue 311?

**Comment by permitanyany** [comment]
That makes sense, let me update the example to include the AS number.

**Comment by IPvSean** [comment]
@acozine this one is good to go now!

**Comment by acozine** [comment]
Thanks @IPvSean for following up, and thanks @permitanyany for contributing to better docs!

**Pull request merged**
