### PR TITLE
Reworked BSD networking for setup

### PR DESCRIPTION
**Pull request by nigelm**
Reworked the inheritance so that everything is now a direct descendant of Network and so can be found by the existing code for new().

Split the code that parses ifconfig so that variants can just replace the parser for a single
ifconfig item.

### CODE REVIEW

**Comment by nigelm** [comment]
As before, I am only testing on FreeBSD and OS X/Darwin.  I am sure if people want to use/care about the other platforms they can extend this...

**Comment by mpdehaan** [comment]
In queue for review, thanks!

**Comment by mpdehaan** [comment]
@bcoca as I know you use BSD, can you help test this?  I can help take a look on OS X.

There were also some other folks interested in OS X facts so I can see that being useful, though we probably end up needing other OS X facts that would imply not treating it as a BSD so much.

**Comment by bcoca** [comment]
mostly looks good, small things like:
- using 8.8.8.8 instead of 0.0.0.0 (default vs specific route)

those can be improved with subsequent patches though, this does 99% of the base work needed to get network facts

**Comment by mpdehaan** [comment]
Please submit this squashed without the itersubclasses parts in the commit that are not used.

**Comment by nigelm** [comment]
Was about to submit a squashed version, but found that devel already has it merged...

**Comment by mpdehaan** [comment]
yeah, it's all good.

sorry for the confusion.

**Pull request closed without merging**
