### PR TITLE
Mount state mounted live

### LINKED ISSUE #48134: Ability to temporarily mount a filesystem without altering /etc/fstab
##### SUMMARY
Ability to perform temporary mounts without altering /etc/fstab.  Currently anything done with the mount module needs to manipulate /etc/fstab.

Additional parameter is needed to perform temporary mounts, such as with an ISO image that would be unmounted later in a play.  Currently this can't be done with the mount module, as altering the /etc/fstab is required.  Maybe call it "modify_fstab" and have it be a boolean.   Currently the only way to achieve this is via the command module using direct mount/unmount commands.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mount, fstab

##### ADDITIONAL INFORMATION
To mount an ISO image temporarily for pulling in data, but not make an entry in /etc/fstab.

```yaml
- name: Mount an ISO Temporarily
  mount:
    src: /path/to/my/iso.iso
    path: /path/to/mount/my/iso
    fstype: iso9660
    opts: ro
    modify_fstab: no
    state: mounted

- name: Unmount an ISO
  mount:
    path: /path/to/unmount/my/iso
    modify_fstab: no
    state: unmounted
```

### PR DESCRIPTION
**Pull request by bbyhuy**
##### SUMMARY

Implement a "mounted_live" state to enable mounting without unnecessarily modifying fstab.

Fixed #48134

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

mount
##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bbyhuy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

Debug PR. Not done yet.

```paste below

```

### CODE REVIEW

**Comment by jamescassell** [comment]
how about `immediate` and `permanent` kind of like the firewalld module?

**Comment by bbyhuy** [comment]
@bcoca @sivel @abadger 
From meeting notes looks like you guys prefer to go with a new sep. module entirely? I don't mind either way.

**Comment by sivel** [comment]
@bbyhuy yes, I expected someone to reply here, or the parent issue.  However the decision is that we leave `mount` as is but we create 2 new modules.  A `fstab` module to just manage `fstab` and a `mount2` module, that only does mount/unmount without touching `fstab`.

Both new modules should preferably be implemented at the same time.

**Comment by bbyhuy** [comment]
@sivel alright, i'll close out this PR and start fresh on a new branch for mount2.

**Pull request closed without merging**
