### PR TITLE
ec2_group: rules can't reference containing group fix #5309

### LINKED ISSUE #5309: ec2_group module: rules can't reference containing group
In order to reference the containing group in rules that specify the group_id parameter, one must do the following:

```
- ec2_group:
    ...
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: sg
- ec2_group:
    ...
    rules:
      - proto: all
        group_id: "{{ sg.group_id }}"
```

which is not idempotent.  I propose that the rule group_id parameter accept the special keyword "this" as a means of referencing the group that contains it.  Pull request forthcoming...

### PR DESCRIPTION
**Pull request by dhml**
Per discussion in https://groups.google.com/forum/#!topic/ansible-devel/WE0ckSTdjFI .

### CODE REVIEW

**Comment by dhml** [comment]
Forgot to reference the issue in the commit log message: #5309

**Comment by aboyett** [comment]
+1

Tested this pull request against ansible 1.4.4 successfully.

**Comment by jctanner** [comment]
@dhml looks good, thanks!

**Comment by bpesics** [comment]
+1

**Pull request merged**
