### PR TITLE
Add support for address_family in Interfaces_file

### PR DESCRIPTION
**Pull request by jocelynj**
##### SUMMARY
This implements a solution for issue #44233, by adding an optional parameter address_family to modify the correct iface part in code like this:
```
iface vmbr0 inet static
        address  $IPV4
...
iface vmbr0 inet6 static
        address  $IPV6
```

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
interfaces_file

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jocelyn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = ./bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION
This adds option address_family, and some tests to check if it is working correctly.

For example, the following yaml code will change only the inet part of the above interfaces file extract:
```yaml
interfaces_file:
  iface: eth0
  address_family: inet
  option: address
  value: 192.168.0.42
  state: present
```

### CODE REVIEW

**Comment by hryamzik** [comment]
LGTM

Thanks @jocelynj!

**Comment by jocelynj** [comment]
I've fixed a minor bug when running the module in my own playbook, that wasn't found by the test as it is with the "post-up" option.

**Comment by hryamzik** [comment]
LGTM

**Comment by jocelynj** [comment]
I'm fine with the current branch, and it is working in my playbook, with the new address_family option.

Do I have anything more to do?

Thanks!

**Comment by hryamzik** [comment]
LGTM

**Comment by jocelynj** [comment]
I've rebased the branch on devel, and I resolved some conflicts.

**Comment by hryamzik** [comment]
LGTM

**Pull request merged**
