### PR TITLE
Update Files

### PR DESCRIPTION
**Pull request by szb512**
This will fix cherrypicker.

- Feature Pull Request

Cherrypicker

Reverted a pull request on my branch to revert commits made on that pull request.

### CODE REVIEW

**Comment by szb512** [comment]
Not possible.

**Comment by Fred-sun** [comment]
@yungezz Please help review this PR when you're available! Thanks!

**Comment by yuwzho** [comment]
ship for the azure image: test/integration/targets/azure_rm_storageblob/files/Ratings.png

**Comment by mattclay** [comment]
@szb512 Thanks for your interest in contributing to Ansible. This PR contains only changes unrelated to the description. Please feel free to open a new PR if you have changes you'd like to propose. If you need assistance opening a PR, I recommend asking for help on IRC in the #ansible-devel channel on Freenode.

**Pull request closed without merging**
