### PR TITLE
Module for appending windows environment Path variable User, System, Process level

### PR DESCRIPTION
**Pull request by Rajeshkumar90**
ISSUE TYPE

New Module Pull Request
COMPONENT NAME

Append value to Path Variable

ANSIBLE VERSION

ansible 2.1.2.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides

SUMMARY

Set an path environment variable for all level (User,Machine)

win_append_path_var:
pathvalue: 'C:\Program Files\Java\bin'
level: machine

Expexcted Result : In System env, Path variable should contain the above mentioned value

Expand an path environment variable for the current users

win_append_path_var:
pathvalue: '%JAVA_HOME%\bin'
level: user
Expexcted Result : In User env, Path variable should contain the above mentioned value in expanded format(C:\Program Files\Java\jdk1.8.0_112\bin)

Validation :

Checks path variable is present or not based on input for given level (User & machine)
Creates path variable with given value for given level(User & machine)
It will not add the value if it is already present in the path variable for given level(User & machine)
Validates User value with value available in "Path" Environment variable for given Level(User,Machine)and append the value to it if path value is not available.
Expands User value with value available in "Path" Environment variable for given Level(User,Machine)and append the value to it if path value is not available.
Creates new Path variable if it is not available for given Level(User,Machine) and append the value to it

Reference 

https://github.com/ansible/ansible-modules-extras/pull/3534

### CODE REVIEW

**Comment by Rajeshkumar90** [comment]
'ready for review'

**Comment by jhawkesworth** [comment]
Thank you for going to the trouble to prepare this pull request.

I can't see any problems with the code but I still don't think this module should be part of ansible.
As explained on https://github.com/ansible/ansible-modules-extras/pull/3534, you can set the entire path using win_environment and if you need to retrieve the current path you can do so by gathering facts.  

So I am -1 on this being merged.

**Comment by Rajeshkumar90** [comment]
You have to still get the whole system path from Path variable and add it along with the path that needs to be added, this could be error prone as there’s always chance that something can be missed or wrongly updated risking the whole PATH. My module will read the existing PATH and will append it with the path that is provided along with the module without developer needing to worry about existing contents of the path variable.

**Comment by nitzmahone** [comment]
@Rajeshkumar90 I agree that a module for managing paths (especially on machines where you don't necessarily want to overwrite the existing path) is a very important tool for Ansible. It's been in-flight on my personal TODO pile for a long time, but I hadn't gotten around to finishing it because there are a lot of nuances to managing Windows paths correctly. Given the consequences of munging a path incorrectly (the machine could be left in an unmanageable state), I think it's important that we catch as many of those nuances as possible, as well as have integration tests that ensure all the functionality is working properly. Mine was a lot further along in catching those nuances, so hope you don't mind that I just finished mine up and PR'd as a core module (https://github.com/ansible/ansible/pull/20073)...

**Comment by jhawkesworth** [comment]
Since ansible 2.3 will include core-supported win_path module, I think this should be closed off now.

I feel bad that both modules that @Rajeshkumar90 has created recently haven't been able to be merged.  I guess the best way to avoid this happening again is to check on ansible-devel google group before starting on new modules, in order to avoid duplicating effort.

**Pull request closed without merging**
