### PR TITLE
fix traceback gathering network facts on Solaris containers (4567)

### PR DESCRIPTION
**Pull request by ghost**
Stops a traceback from happening when gathering facts(network interfaces) on Solaris containers.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Jon,

Thanks for submitting this.

Generally speaking, we don't like to see try/except statements that don't catch a specific type of exception int he code.

For instance, you might want:

```
# except IndexError:
```

Also, we like it when try/except statements are around the smallest block of code possible.

Can you identify the failing line and shrink that up any?

Thanks!

**Comment by ghost** [comment]
Hi, 

Would the below be better?

```
def merge_default_interface(self, defaults, interfaces, ip_type):
    if not 'interface' in defaults.keys():
        return
    try:
        ifinfo = interfaces[defaults['interface']]
        # copy all the interface values across except addresses
        for item in ifinfo.keys():
            if item != 'ipv4' and item != 'ipv6':
                defaults[item] = ifinfo[item]
            if len(ifinfo[ip_type]) > 0:
                for item in ifinfo[ip_type][0].keys():
                    defaults[item] = ifinfo[ip_type][0][item]
    except KeyError:
        pass
```

**Comment by mpdehaan** [comment]
It would be if it were narrowed down to where you would expect the key error.

It would be even better if since you are looking for a key error if there was a:

 if not 'foo' in bar:
      return # or pass, or continue, etc, as needed

Basically exception handling as last resort.

In either case, the above try block is still a bit wide so it is not clear when looking through the code where it is trying to avoid a missing value.

**Comment by mpdehaan** [comment]
cc @ruv- any updates?

i would still like an explicit code check versus the exception handling if we can swing it.  It's unclear which line triggers the possible exception right now.

Thanks!

**Comment by jctanner** [comment]
I think I might have figured out what the error is ...

```
GATHERING FACTS *************************************************************** 
fatal: [example2.lab.net] => failed to parse: Traceback (most recent call last):
  File "/export/jtanner/.ansible/tmp/ansible-1383779109.53-249971114060239/setup", line 3196, in <module>
    main()
  File "/export/jtanner/.ansible/tmp/ansible-1383779109.53-249971114060239/setup", line 2186, in main
    data = run_setup(module)
  File "/export/jtanner/.ansible/tmp/ansible-1383779109.53-249971114060239/setup", line 2127, in run_setup
    facts = ansible_facts()
  File "/export/jtanner/.ansible/tmp/ansible-1383779109.53-249971114060239/setup", line 2118, in ansible_facts
    facts.update(Network().populate())
  File "/export/jtanner/.ansible/tmp/ansible-1383779109.53-249971114060239/setup", line 1558, in populate
    self.merge_default_interface(default_ipv4, interfaces, 'ipv4')
  File "/export/jtanner/.ansible/tmp/ansible-1383779109.53-249971114060239/setup", line 1735, in merge_default_interface
    ifinfo = interfaces[defaults['interface']]
KeyError: 'e1000g0'
```

**Comment by jctanner** [comment]
A simpler patch:

```
diff --git a/library/system/setup b/library/system/setup
index 1813c60..c546a9f 100755
--- a/library/system/setup
+++ b/library/system/setup
@@ -1732,6 +1732,8 @@ class GenericBsdIfconfigNetwork(Network):
     def merge_default_interface(self, defaults, interfaces, ip_type):
         if not 'interface' in defaults.keys():
             return
+        if not defaults['interface'] in interfaces:
+            return
         ifinfo = interfaces[defaults['interface']]
         # copy all the interface values across except addresses
         for item in ifinfo.keys():
```

**Pull request closed without merging**
