### PR TITLE
[2.12] Use correct markup in documentation

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #76545 to stable-2.12.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Review by samccann — APPROVED** [review]

**Comment by felixfontein** [comment]
Added backport of #76698.

**Comment by felixfontein** [comment]
@samccann @nitzmahone thanks for reviewing and merging this and #76575!

**Pull request merged**
