### PR TITLE
openssh_keypair: make sure public key has same permissions as private key

### LINKED ISSUE #61411: openssh_keygen does not set permissions correctly on public key
##### SUMMARY
In the openssh_keypair module, `set_fs_attributes_if_different` is not called on the public key, so the owner and group do not get set on the .pub file containing the public key.

I haven't tested it or reasoned about the code, but this may only occur when trying to run the task when the public key already exists.

<https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssh_keypair.py#L231>
In this line, file_args only receives the private key file location.

Additionally, there are "isPublicKeyValid" and "isPrivateKeyValid", and in the private key one we can see here <https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssh_keypair.py#L254> that we check the permissions for the private key, but there is no corresponding check in the public key.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openssh_keypair

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = <path_inside_home_directory>/ansible.cfg
  configured module search path = ['<home_directory>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(<path_inside_home_directory>/aws-remote-work/ansible.cfg) = ['<path_inside_home_directory>/aws-remote-work/hosts']

```

##### OS / ENVIRONMENT

host: Linux host-machine 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
remote: Linux remote-machine 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux

##### STEPS TO REPRODUCE

I am running the playbook with --become, so that it's executing as root

```yaml
- name: create ssh keypair in user home directory
  openssh_keypair:
    path: "/home/{{user_name}}/.ssh/my_ssh_key"
    type: ecdsa
    owner: "{{user_name}}"
    group: "users"
    mode: "u=rw,g=,o=" 
```

##### EXPECTED RESULTS

my_ssh_key should have permissions like
`-rw------- 1 user_name  users`
my_ssh_key.pub should have the same permissions:
`-rw------- 1 user_name  users`

##### ACTUAL RESULTS

only the private key has the correct permissions, and the public key has permissions
`-rw-r--r-- 1 root root`

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #61411.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssh_keypair

### CODE REVIEW

**Comment by felixfontein** [comment]
I think this is worth a small discussion whether this is a regular bugfix (which should be backported to stable-2.8) or a breaking change bugfix, which should maybe not be backported (and only included in stable-2.9).

The situation described in #61411 is definitely bad: you don't want to have the public key file be owned by the Ansible user when the private key is owned by someone completely different. I think the main problem are the permissions: users potentially want the private key to have very strict permissions, while the public key should be available to a larger audience.

I think it is still better to use the same settings for both keys, simply because these files are kept right to each others and users also get that when running `ssh-keygen` manually. And since I don't want to add extra options to handle different access rights for the public key :)

Any opinions on this?

**Comment by felixfontein** [comment]
Note to self: if/when #61659 gets merged, this patch should be adjusted to use that feature.

**Comment by MarkusTeufelberger** [comment]
Since that other PR might still take a while, let's check this one in for now.

**Comment by MarkusTeufelberger** [comment]
shipit

**Comment by felixfontein** [comment]
Also it is not clear whether the other PR will be backported (it could be interpreted as a new feature and not backported). So it's better to get this done first and backported, so that the problem is solved.

**Comment by felixfontein** [comment]
@MarkusTeufelberger thanks for reviewing this!

**Pull request merged**
