### PR TITLE
Replace file handling with context managers in files-modules and pars…

### PR DESCRIPTION
**Pull request by atombrella**
### SUMMARY
Reduced part (or inspiration from) of #63840. No semantic changes are in this PR. 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
core.

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
Looks good (and safe) to me.

**Comment by atombrella** [comment]
@felixfontein Any reason why this has not been merged yet? Is a changelog fragment needed?

**Comment by felixfontein** [comment]
@atombrella all PRs which do user-facing changes need a changelog fragment. Also, this one and #65227 need core approval since they affect core-supported things.

Right now the repo is in lockdown, nothing will be merged anyway until later this month. (See timeline: https://github.com/ansible-collections/overview#timeline)

**Comment by Akasurde** [comment]
@atombrella Could you please rebase this PR? `ini_file` moved to [`community.general`](https://github.com/ansible-collections/community.general) so you might want to raise a PR against this repo.

needs_info

**Comment by atombrella** [comment]
@Akasurde I updated this PR. Not sure if it requires a change log entry/stub.

**Comment by atombrella** [comment]
@jborean93 There's also this one.

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
