### PR TITLE
Fix variable injection in pause module args. Closes #1209

### LINKED ISSUE #1209: Unable to pass variable to pause module
While having in playbook:

```
  vars:
    sleep_time: 15
  tasks:
    - name: test pause module ${sleep_time}
      action: pause seconds=${sleep_time}
```

I got output from ansible:

```
TASK: [test pauser module 15] *********************
fatal: [s-host] => Traceback (most recent call last):
  File "/home/user/GIT/ansible/lib/ansible/runner/__init__.py", line 227, in _executor
    exec_rc = self._executor_internal(host)
  File "/home/user/GIT/ansible/lib/ansible/runner/__init__.py", line 276, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port)
  File "/home/user/GIT/ansible/lib/ansible/runner/__init__.py", line 360, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject)
  File "/home/user/GIT/ansible/lib/ansible/runner/action_plugins/pause.py", line 68, in run
    self.pause_type, pause_params)
TypeError: not enough arguments for format string


FATAL: all hosts have already failed -- aborting
```

### PR DESCRIPTION
**Pull request by timlnx**
You can has ${variables} in pause module args!

Closes #1209

### CODE REVIEW

**Comment by dhozac** [comment]
I would think template on args before splitting the string would work better, as you might want to use extra-vars to provide the pause unit as well as value. You might also consider using utils.parse_kv to check the arguments instead.

**Comment by mpdehaan** [comment]
I agree with dhozac.  Rather than doing this in the pause module, we should template the line in the code that decides to call the BYPASS_HOST_LOOP stuff.

**Comment by timlnx** [comment]
On Wed, Oct 3, 2012 at 8:48 PM, Michael DeHaan notifications@github.com wrote:

> I agree with dhozac. Rather than doing this in the pause module, we should
> template the line in the code that decides to call the BYPASS_HOST_LOOP
> stuff.
> 
> —
> Reply to this email directly or view it on GitHub.

Right on. That approach would simplify things for every action module
too. Neato!

## 

--Tim Bielawa
http://lnx.cx

**Comment by timlnx** [comment]
Debate's over, back to c0ding!

>  You might also consider using utils.parse_kv to check the arguments instead.

+1 to this

I think that would simplify the overall logic in the pause module. The
only change would be that users would need to define their prompt
message as a "quoted string".

> I would think template on args before splitting the string would work
> better, as you might want to use extra-vars to provide the pause unit as
> well as value.

I don't agree that using extra args would be the best approach,
assuming I'm understanding it correctly from scanning the code.

'extra-args' is the 'user', 'vars', 'gather_facts' type part, right?
If so, here's why I don't agree: I have multiple current use-cases
where that approach would be an inhibitor. `pause` tasks are
definitely not a one-per-play type item.

Looked at this again:

> we should template the line in the code that decides to call the BYPASS_HOST_LOOP stuff.

I'll just be honest and say that I have no idea what you intended to
mean by that.

You mean here?

> p = self.action_plugins.get(self.module_name, None)
> if p and getattr(p, 'BYPASS_HOST_LOOP', None):
>     self.host_set = hosts
> 
> # ...

I'm just want to make sure I understand you both correctly on this.
Are you suggesting to apply `utils.template()` to Runner's
`self.module_args` **before** calling any of Runners `_executor()`
or `parallel_exec()` methods? As in:

> self.module_args = utils.template(self.basedir, self.module_args, inject)
> 
> p = self.action_plugins.get(self.module_name, None)
> if p and getattr(p, 'BYPASS_HOST_LOOP', None):
>     self.host_set = hosts
> 
> # ...

I guess we could. Assuming I'm understanding you both correctly, that
would require moving the `inject.update()` type code into the
`run()` method. Please advise/clarify.

## 

--Tim Bielawa
http://lnx.cx

**Comment by mpdehaan** [comment]
What @dhozac was saying I think is that by parsing it in the right way, it doesn't matter where the variables come from. 

Normally this templating step happens in _executor_internal_inner in the host loop.  In this case, it's a bit odd because there isn't one, so I imagine something akin to self.module_args = utils.template(self.module_args, ...) would be acceptable, provided that actually works.

(I'm unwilling to accomodate any refactoring at this point in the release, so it would have to be specific to the BYPASS_HOST_LOOP pathway)

**Comment by timlnx** [comment]
@mpdehaan I think you pointed out the issue precisely here. This is moving from 'please fix' to 'lets refactor' territory. 

Focusing back on the original issue report, I have updated my pause_variables branch.

Now it uses parse_kv() on a template()ized version of module_args.

The `run()` logic has been simplified quite a bit. Here's my test playbook:

```
---                                                         
- hosts: [lnx.cx]                                           
  vars:                                                     
      pause_msg: "this pause brought to you by: cowsay"     
      pause_num: 42                                         
  gather_facts: false                                       
  user: tbielawa                                            
  tasks:                                                    
      - action: pause                                       
        name: ${pause_msg}                                  
      - action: pause seconds=${pause_num}                  
        name: test pause for ${pause_num} seconds           
      - action: pause prompt="${pause_msg}"                 
        name: test pause with "${pause_msg}" prompt
```

And here's the results:

```
<tbielawa>@(griddle)[~/Projects/ansible] 23:50:04  (pause_variables⚡)
$ ansible-playbook ./test.yaml

PLAY [lnx.cx] *********************

TASK: [this pause brought to you by: cowsay] *********************
[lnx.cx]
Press enter to continue:
ok: [lnx.cx]

TASK: [test pause for 42 seconds] *********************
(^C-c = continue early, ^C-a = abort)
[lnx.cx]
Pausing for 42 seconds
ok: [lnx.cx]

TASK: [test pause with "this pause brought to you by: cowsay" prompt] *********************
[lnx.cx]
this pause brought to you by: cowsay:
ok: [lnx.cx]

PLAY RECAP *********************
lnx.cx                         : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by mpdehaan** [comment]
yeah, template there seems fine after all because it is an action module it can be special.

Merged, thanks!

**Pull request merged**
