### PR TITLE
ios_facts: Report space of file systems

### PR DESCRIPTION
**Pull request by paneu**
##### SUMMARY

It would be a good feature for the ios_facts module to report the total and free space of the file systems instead of just the names. Therefore, this change converts ansible_net_filesystems from a list of strings into a dict.
As this breaks the existing interface of ios_facts and introduces inconsistency with regards to the other *_facts modules, I am very keen on hearing your feedback. If you have any objections or concerns, please let me know.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (ios-facts-fs c7b78bf25e) last updated 2018/06/22 19:24:49 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/paul/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/paul/ansible-dev/ansible/lib/ansible
  executable location = /home/paul/ansible-dev/ansible/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
```

##### ADDITIONAL INFORMATION

Before:
```
...
            "ansible_net_filesystems": [
                "bootflash:"
            ],
...
```
After:
```
...
            "ansible_net_filesystems": {
                "bootflash:": {
                    "spacefree_kb": 6453180.0,
                    "spacetotal_kb": 7712692.0
                }
            },
...
```

### CODE REVIEW

**Comment by paneu** [comment]
To give you an idea on why I would find this useful, I thought of the case of distributing files (e.g. software images) to devices. A convenient way to check whether the device holds enough free space before attempting to transfer the file would make the process somewhat more robust. If this could be implemented in one way or another, this would be very cool.

**Comment by gundalow** [comment]
`ios_facts` was added in Ansible 2.2, so there will be lots of people using this module and `ansible_net_filesystems` using it as a `list`

**Comment by Qalthos** [comment]
To add on to that, if you want to add this as a new key instead of changing an existing key, that would probably be acceptable.

**Comment by paneu** [comment]
Thanks for your input. Do you have any preference on what the name could be like?

**Comment by paneu** [comment]
I have modified the PR to use a new key instead of modifying the existing one. I opted to name this in a generic fashion to keep the key extensible in the future (semantically).

**Review by Qalthos — APPROVED** [review]
No particular opinion on name, looks good

**Pull request merged**
