### PR TITLE
Pep8 fixes for ejabberd_user and jboss

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* PEP8 Fixes
* Refactor code

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/web_infrastructure/jboss.py
lib/ansible/modules/web_infrastructure/ejabberd_user.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Review by resmo — APPROVED** [review]
code LGTM

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
bump for review

**Comment by Akasurde** [comment]
@resmo Thanks for review.

**Pull request merged**
