### PR TITLE
Fix typo in pg server ping

### PR DESCRIPTION
**Pull request by monkz**
##### SUMMARY
Fix typo in docs

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
lib/ansible/modules/database/postgresql/postgresql_ping.py

### CODE REVIEW

**Comment by tcraxs** [comment]
shipit

**Comment by Andersson007** [comment]
shipit

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
@monkz thank you, please add a change log fragment for backporting to 2.8

**Comment by Andersson007** [comment]
@monkz , it’s been merged automatically, ok, I’ll do a backport by myself

**Comment by monkz** [comment]
I assume backporting was done. I don't chase attributions for these kind of fixes. Thank you for merging.

**Comment by Andersson007** [comment]
@monkz , I meant something like https://github.com/ansible/ansible/pull/56842. Without backporting the typo will be fixed only in 2.9 release.
I've done it for 2.8 too by the PR above. If interesting look at [this](https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy)
Thank you for this PR!
FYI: we have [PostgreSQLWG](https://github.com/ansible/community/wiki/PostgreSQL) and [pinboard](https://github.com/ansible/community/issues/435). If you'd like to participate in postgres-specific support but don't know what to do, just let me know

**Comment by Andersson007** [comment]
@tcraxs , thank you for reviewing

**Pull request merged**
