### PR TITLE
Adding ldap_entry module

### PR DESCRIPTION
**Pull request by jtyr**
##### ISSUE TYPE

New Module Pull Request
##### COMPONENT NAME

`ldap_entry`
##### ANSIBLE VERSION

For Ansible 2.3
##### SUMMARY

This PR is adding a new module that allows to add/change/remove LDAP entries. The module is based on the code from Peter Sagerson who gave me the [permission](https://bitbucket.org/psagers/ansible-ldap/pull-requests/2/adding-params-option-and-other-minor/diff#comment-16809629) to publish it.

### CODE REVIEW

**Comment by jtyr** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2952

**Comment by jtyr** [comment]
@drybjed @jangrewe I have moved this PR from the obsolete [ansible-modules-extras](https://github.com/ansible/ansible-modules-extras/pull/2952) project to here and would like to ask you to comment with the magic word ":boat:it" to allow this module to be merged.

**Comment by jangrewe** [comment]
⛵️it

**Comment by jtyr** [comment]
@jangrewe Thanks for your prompt response. Please could you use the actual word "shipit" instead of the emoji? ;o) I think the Ansible Bot could have a problem to interpret the word based on emoji ;o)

**Comment by jangrewe** [comment]
shipit

;-)

**Comment by drybjed** [comment]
shipit

**Comment by resmo** [comment]
thanks!

**Pull request merged**
