### PR TITLE
Add win iis logs

### PR DESCRIPTION
**Pull request by crossan007**
##### SUMMARY
IIS logging is cumbersome to manage.   This module provides a clean way to manage the available properties.  Manages the IIS log configuration either per-site, or server wide

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
win_iis_logs

_This is still a work-in-progress_ and I'm open to input on the interface / public methods.

### CODE REVIEW

**Comment by jborean93** [comment]
@crossan007 are you aware of how to run the sanity checks locally? The test error explains the command used that failed which you can run locally. I would also recommend you add `--docker default` which runs the tests in a Docker container that already has all the requirements installed so you don't have to do that yourself.

For example, to run the pslint and yamllint tests you can do

```
ansible-test sanity --test pslint --test yamllint --docker default
```

**Comment by crossan007** [comment]
variable scope warning probably related to this: https://github.com/PowerShell/PSScriptAnalyzer/issues/827

**Comment by dagwieers** [comment]
During the [next Windows WG meeting](https://github.com/ansible/community/issues/420) on 2019-01-29 we will review and decide on the inclusion of this module in Ansible v2.8. Your presence in the meeting could be helpful.

*If there's anything you wanted to improve/fix, please do so before the meeting.*

**Comment by nitzmahone** [comment]
After some discussion at the Windows Working Group module review, we're a little nervous to take on more IIS modules into the core distribution right now, especially given the state of the other IIS modules we already have. This would be a good candidate for the new collections feature that's coming in Ansible 2.8, which would allow these modules to be hosted on galaxy.ansible.com and easily installed/upated by users on their Ansible controller.

**Comment by jhawkesworth** [comment]
Since collections exist now - see https://galaxy.ansible.com/docs/contributing/creating_collections.html I think perhaps we should close this one if that's ok with you @crossan007 ?

**Comment by jborean93** [comment]
Closing due to the reluctance of adding and maintaining more IIS modules Feel free to include this in a collection and distribute it through Galaxy.

**Pull request closed without merging**
