### PR TITLE
Removed byte flag when opening the new JKS file.

### LINKED ISSUE #50698: java_keystore fails on Python 3 (bytes/str issue)
##### SUMMARY
java_keystore fails with "TypeError: a bytes-like object is required, not 'str'" when run with Python 3.5 as ansible_python_interpreter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
java_keystore

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = None
  configured module search path = ['/home/r2d2/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/r2d2/setup/.venv/lib/python3.5/site-packages/ansible
  executable location = /home/r2d2/setup/.venv/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
```
(No output)

##### OS / ENVIRONMENT
Target OS: Ubuntu 16.04.5 LTS

##### STEPS TO REPRODUCE
```yaml
  - name: 'Write Wildfly keystore'
    java_keystore:
      name: tau-wildfly
      certificate: "{{ tau_certificate_chain[0] }}"
      private_key: "{{ tau_private_key }}"
      password: changeit
      dest: '{{ tau_wildfly_keystore }}'
      owner: '{{ tau_user }}'
      group: '{{ tau_group }}'
      mode: 'u=rw,go='
```

##### EXPECTED RESULTS
Task runs and creates/updates keystore

##### ACTUAL RESULTS

```paste below
TASK [tau_common/server-keys : Write Wildfly keystore] *************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a bytes-like object is required, not 'str'
fatal: [REDACTED]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/usr/lib/python3.5/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.5/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 626, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/tmp/ansible_java_keystore_payload_ky7c0l_e/__main__.py\", line 290, in <module>\n  File \"/tmp/ansible_java_keystore_payload_ky7c0l_e/__main__.py\", line 286, in main\n  File \"/tmp/ansible_java_keystore_payload_ky7c0l_e/__main__.py\", line 261, in process_jks\n  File \"/tmp/ansible_java_keystore_payload_ky7c0l_e/__main__.py\", line 193, in create_jks\n  File \"/tmp/ansible_java_keystore_payload_ky7c0l_e/__main__.py\", line 172, in create_tmp_certificate\n  File \"/tmp/ansible_java_keystore_payload_ky7c0l_e/__main__.py\", line 167, in create_file\nTypeError: a bytes-like object is required, not 'str'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

### PR DESCRIPTION
**Pull request by teodorkostov**
##### SUMMARY

Fixes #50698

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`java_keystore`

<!--- ```paste below

``` -->

### CODE REVIEW

**Comment by Mogztter** [comment]
LGTM

@terusus Could you please confirm that it's working with both Python 2+ and Python 3+ ?

**Comment by terusus** [comment]
Hey @Mogztter. I initially checked that it works with python 3.7.2. Now I also confirmed that it works file with python 2.7.15 as well.

Does something else have to be done?

**Comment by Mogztter** [comment]
Perfect, thanks! 👍
No it's good to go, a core maintainer will review it and merge it.

I wonder if we could add an "integration" test but I've never done it.

**Comment by gundalow** [comment]
@terusus Thank you for this patch
@Mogztter Thank you for guidance and review

This is an improvement, so we will get this merged.
Integration tests would be great, though no reasons to hold this PR up.

If you'd like this fixed in Ansible 2.7 could you please raise a backport PR including a changelog/fragment by following https://docs.ansible.com/ansible/devel/community/development_process.html#making-your-pr-merge-worthy (once this PR has been merged by the Bot)

**Comment by gundalow** [comment]
rebuild_merge

**Pull request merged**
