### PR TITLE
New `dpkg_reconfigure` module

### PR DESCRIPTION
**Pull request by sbocahu**
Reconfigures Debian packages that are managed by Debconf.

### CODE REVIEW

**Comment by mpdehaan** [comment]
As I really don't like the way the signature of this module works (file arguments, long forms, etc) and I generally do NOT see other CMS tools working this way (they would use files and so on instead, because dpkg configuration is something of a mess), I am inclined to not take this into core at this time.

**Comment by gw0** [comment]
Oh... To me it looks pretty decent compared to what various automated install scripts are doing (eg. OpenStack on Debian: http://anonscm.debian.org/gitweb/?p=openstack/openstack-auto-builder.git;a=blob_plain;f=preseeder).

**Comment by sbocahu** [comment]
@gw0 if you are interested: I'm creating a repository for extra modules where you can find dpkg_reconfigure: https://github.com/zecrazytux/ansible-library-extra

**Comment by bcoca** [comment]
I was looking forward to this in core, may I take a stab at reworking this
to pass Micheal's criteria?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by sbocahu** [comment]
Not sure what are these criteria but I'ld appreciate if you could do this, @bcoca

**Comment by mpdehaan** [comment]
I think I was just hesistant whether dpkg-reconfigure was a good practice
versus template files and the way we usually manage things.

Haven't seen this done in other systems.

I also really don't like the idea of using the file lookup plugin to pass
arguments.

**Comment by bcoca** [comment]
One thing that I think most people don't realizae, dpkg-reconfigure does
not just update config files, it updates databases, symlinks, accepts
licenses, changes file names, permissions and many things depending on the
app. So just using template/copy is not enough this can translate to a full
playbook of actions many of which can change during app upgrades.

My plan was to update it to be able to do smart with_items lists like
apt/yum modules do so the interface is a bit nicer, but it should still be
able to use lookup plugins life file, either inline or through with_items.

**Comment by srgvg** [comment]
+1 @bcoca 
dpkg-reconfigure is quite a key component in Debian based systems.

**Comment by ghost** [comment]
:+1:

A simple case I ran into that required dpkg-reconfigure and couldn't be done with just templates is setting the timezone. `dpkg-configure tzdata`

**Comment by gw0** [comment]
Other essential things that require more work without `dpkg-reconfigure`:
- `ca-certificates` (creating hundred of symlinks is problematic)
- `locales` (can be done by a template and a command under notify)
- updating alternatives (default tools to run for each task)?

**Pull request closed without merging**
