### PR TITLE
[backport 2.7] Fixed lvol ValueError with float size.

### PR DESCRIPTION
**Pull request by hvtuananh**
This is backport for stable-2.7 of #36811 and #53096

### CODE REVIEW

**Comment by abadger** [comment]
This does not look like a good way to fix this.  Involving the locale subystem has both performance drawbacks and feels fragile as it depends on the python and C locale subsystems both doing the same string formatting.  Looking at the original bug, it looks like the proper way to fix this would be to set the locale to "C" prior to running the logical volume commands.

You can set environment variables either per-call like this: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt_key.py#L223

or globally so that every call to run_command uses the specified env vars like this: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py#L1029

**Comment by hvtuananh** [comment]
@abadger Thank you for the feedback. The original bug is that the lvol module strips off everything after the decimal point `.` so float becomes integer. 

I'll prepare a patch to address this. Would you be able to review it?

**Comment by abadger** [comment]
Yep.

**Comment by hvtuananh** [comment]
@abadger Thank you! PR created: https://github.com/ansible/ansible/pull/53096

**Comment by abadger** [comment]
Merged for the 2.7.9 release.

**Pull request merged**
