### PR TITLE
add missing integration tests for postgresql_schema module

### PR DESCRIPTION
**Pull request by tcraxs**
##### SUMMARY
Module postgresql_schema
* Add CI tests for module postgresql_schema

### CODE REVIEW

**Comment by Andersson007** [comment]
@tcraxs , I do the same in parallel ;) I added a return values. That allows us to make better tests. Don't be in a hurry

**Comment by Andersson007** [comment]
I'll publish it in the next few days. I don't mind if you implement CI tests. You might just see some from mine.

**Review by Andersson007 — CHANGES_REQUESTED** [review]
Good job!
IMO, we should also check at least:
1. check_mode: yes (see the example test file that I sent to you)
2. check result.queries == [ bla bla bla ] for each test
3. state: absent
4. owner: ...
5. cascade_drop: yes
6. maybe something else ;)

**Comment by tcraxs** [comment]
@Andersson007 please review if you like.

Following checks included:
* create schema in checkmode
* create schema
* drop schema
* create schema with owner
* drop schema with owner
* drop schema cascade (with existing table)

**Comment by Andersson007** [comment]
@tcraxs , I looked at it, LGTM
please, add drop schema in check_mode. Seems, that will enough

**Comment by tcraxs** [comment]
> @tcraxs , I looked at it, LGTM
> please, add drop schema in check_mode. Seems, that will enough

Added one more test for DROP SCHEMA in check_mode=yes

**Review by Andersson007 — APPROVED** [review]
shipit

**Comment by gundalow** [comment]
@tcraxs @Andersson007 Great work, merged

**Comment by Andersson007** [comment]
@gundalow , thank you for merge!
@tcraxs , we shouldn't stop ;)

**Pull request merged**
