### PR TITLE
Fix non-signature authentication (backport 2.8)

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Apparently everyone is using signature authentication these days.

This is a backport of #56038

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ACI modules

### CODE REVIEW

**Comment by dagwieers** [comment]
@abadger Ayy reason why this was not taken for a release candidate ?
It may break for existing Cisco ACI users.

**Comment by smnmtzgr** [comment]
@abadger thats an important change. ACI modules will be broken if we don't merge this.

**Comment by smnmtzgr** [comment]
@dagwieers and @abadger since Ansible 2.8.0 is available now... can we get this fix into Ansible 2.8.1 ?

**Comment by dagwieers** [comment]
@smnmtzgr I hope so. I don't know why this was not accepted for the v2.8.0 release. I only found out that v2.8.0 was released because I read the release announcement.

**Comment by abadger** [comment]
We only took blockers into the release candidates and no one nominated this.  It probably should have been taken to a meeting to get some attention on it and an official ruling as to whether it should block release or not as soon as it was submitted.  it will get into 2.8.1... I'm going through the queue and merging things now.

**Comment by abadger** [comment]
Merged for the 2.8.1 release.

**Comment by dagwieers** [comment]
Thanks @abadger !

**Pull request merged**
