### PR TITLE
Add 2.9 in doc version dropdown

### LINKED ISSUE #61888: Docs version picker choices
##### SUMMARY
Currently the documentation version picker includes stable versions and "latest" but it does not include 2.9 which is in beta. I feel the latest builds of beta versions should be included as well.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/

##### ANSIBLE VERSION
devel

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes: #61888

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/conf.py

### CODE REVIEW

**Review by gundalow — CHANGES_REQUESTED** [review]
2.9 hasn't been released yet, so I'm not sure if this is right.

Also once 2.9 has been released, does this need backporting to every `stable-2.*` branch that we currently have on docs.ansible.com?

**Comment by samccann** [comment]
This is part of our standard docs release checklist item now. See #56539 for what we did during 2.8 for an example.
...and yes, parts of this get backported, especially as we now have a banner to say which versions are no longer maintained. 
As for when we publish 2.9 docs, I see someone did that already? That said, I disagree with the early publishing with no indication that this is Beta.  I added this to the DaWGs meeting agenda for Tuesday to discuss.

**Review by samccann — CHANGES_REQUESTED** [review]
Please hold off on this PR for now, as per comments.

**Comment by acozine** [comment]
At any given time, we maintain 3 releases plus `devel` - currently those releases are 2.6, 2.7, and `latest`=>2.8. When 2.9 is released, we will add 2.9 as `latest`, list 2.8 as `2.8`, and sunset 2.6 in the version-changer. Until then, the 2.9 docs are available, but unofficial. We don't want to highlight them in the version-changer.

**Pull request closed without merging**
