### PR TITLE
Shows that this is a hacking-ansible shell in the prompt

### PR DESCRIPTION
**Pull request by vegitron**
This is my fix for issue #5560.

### CODE REVIEW

**Comment by bcoca** [comment]
i have a heavily customized prompt ( I know others that do also), this is
best put in  your own .profile/.shellrc than in ansible .

**Comment by vegitron** [comment]
Well, my shell being ansible-enabled is an occasional event. Having the ansible environment variables set isn't always appropriate. 

In the pull request, the change to the prompt is behind the check for -q.  I would also be fine with adding another flag to suppress this.

**Comment by lichesser** [comment]
I think this isn't something which every ansible user ~~wants~~ needs. You can modify your own prompt settings to allow this. If you are a bash user you could e.g. but this in your `~/.bashrc`

```
# Original prompt
# PS1='\u@\h:\w\$ '

# new prompt
PS1='${HACKING_DIR:+${ANSIBLE_HOME:+"[ansible-shell] "}}\u@\h:\w\$ '
```

Which prepends `[ansible-shell]` to your prompt only in the case `$HACKING_DIR` and `$ANSIBLE_HOME` are defined in the environment

**Comment by vegitron** [comment]
The perspective I'm taking on this is making it easier for someone new, while making it possible for experts to opt-out.

Nobody _needs_ hacking/env-setup - they can just modify their .bashrc files.  But it makes things easier, and I would say that changing the shell does as well, especially for people who aren't modifying their .bashrc files to have ansible enabled in every shell.

FWIW, this notion of changing the prompt is taken from virtualenv, so it isn't novel.

**Comment by mpdehaan** [comment]
I agree with @lichesser, it is easy for people to modify their setup if they want to, and I don't believe we would be popular for modifying shell prompts without asking.

**Comment by vegitron** [comment]
OK, thanks for considering it.

**Pull request closed without merging**
