### PR TITLE
snapshot_policy modify, plus new options

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Allow user to modify a snapshot policy
Add new options

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_snapshot_policy.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — COMMENTED** [review]
We need to hold on this PR until we submit the latest changes to netapp.py.
(One of the changes removes the sorting of lists, and this PR would fail if lists are sorted).

**Comment by carchi8py** [comment]
This PR requires #59151 to be merged in first.

**Review by lonico — APPROVED** [review]
shipit

**Review by thedoubl3j — APPROVED** [review]
new params covered, lgtm. shipit

**Pull request merged**
