### PR TITLE
Dynamic inventory for Packet host (https://packet.net)

### PR DESCRIPTION
**Pull request by t0mk**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
contrib/inventory/packet_net.py, contrib/inventory/packet_net.ini

##### ANSIBLE VERSION

```
ansible 2.3.0 (packet-inventory 886055e393) last updated 2017/01/25 15:47:51 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Dynamic inventory script for the Packet host (https://packet.net) based on #17820. I improved it a bit and re-submitted because 
- The previous PR seems to rot.
- I would really like to see the dynamic inventory for Packet merged.

The code is taken from @dipinhora's previous PR (#17820). I improved a few things, and chaned the environment variable for the API auth token, so that it's compatible with the modules for Packet, merged in #19005.

### CODE REVIEW

**Comment by gundalow** [comment]
If people could test this and respond with "s h i p i t" (without spaces) that would be great

**Comment by t0mk** [comment]
In order to test this, you should have some devices in the Packet cloud running, and then you can do:

```bash
pip install packet-python
git clone https://github.com/ansible/ansible
cd ansible
git fetch origin pull/20635/head:pr-20635
git checkout pr-20635
cd contrib/inventory
# export your packet API token as PACKET_API_TOKEN
export PACKET_API_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
./packet_net.py --list
# if you changed something recently enough, you might want to refresh the cache
./packet_net.py --list --refresh-cache
```

**Comment by vielmetti** [comment]
Worked for me once I ran `pip install packet-python` to pull in the necessary dependencies. Tested on Packet 2A server.

shipit

**Comment by t0mk** [comment]
Thanks, @vielmetti, good point with installing the pip package. I will add it to the test howto comment above :).

**Comment by vielmetti** [comment]
@gundalow do you need more information?

**Review by gundalow — APPROVED** [review]
shipit

**Comment by gundalow** [comment]
If you are happy I'll merge

**Comment by vielmetti** [comment]
Looks good to me! Please merge. Thanks!

**Comment by t0mk** [comment]
Great!

If you merge this, you can close #17820.

**Comment by gundalow** [comment]
Merged, thanks for the testing

**Pull request merged**
