### PR TITLE
New module to support traceroute command in IOS

### PR DESCRIPTION
**Pull request by Tachashi**
##### SUMMARY
- Added new module `ios_traceroute`
- This module provides building traceroute command and parsing the output on devices running Cisco IOS.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
ios_traceroute.py

##### ADDITIONAL INFORMATION
Sample playbook and result
https://github.com/Tachashi/ansible_ios_traceroute_module

### CODE REVIEW

**Comment by justjais** [comment]
@Tachashi can u check and fix the `assert` zuul failure

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
@Tachashi apologies for reviewing this late. And changes LGTM, can you plz update the doc version to `2.10` as `2.9` is released now.

**Comment by Tachashi** [comment]
@ justjais
Thanks for your reply. I'll update the version!

**Comment by justjais** [comment]
@Tachashi `ios_traceroute` integrations tests are failing, ref: https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_79/59679/9e9143e43b9b58d9fa08e7d29d2210255b567d37/third-party-check/ansible-test-network-integration-ios-python27/e0e7f94/controller/ara-report/reports/f07c6222-72b1-4385-bbf3-9d4c8511daa3.html.

Can u plz check and fix the failure and update the PR.

**Comment by Tachashi** [comment]
Shippable errors below look like the problem of  `ios_argument_spec`.

```
lib/ansible/modules/network/ios/ios_traceroute.py:0:0: doc-default-does-not-match-spec: Argument 'port' in argument_spec found in provider defines default as (None) but documentation defines default as (22)
lib/ansible/modules/network/ios/ios_traceroute.py:0:0: doc-default-does-not-match-spec: Argument 'timeout' in argument_spec found in provider defines default as (None) but documentation defines default as (10)
```

**Comment by jctanner** [comment]
!waffling ci_verified

**Comment by Akasurde** [comment]
@Tachashi Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to [`cisco.ios`](https://github.com/ansible-collections/cisco.ios). Could you please migrate this PR to the above-mentioned repo? 

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks,

needs_info

**Comment by Akasurde** [comment]
Hi @Tachashi, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/cisco.ios<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
