### PR TITLE
VMware: vmware.py refactor

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* Remove unused `find_entity_child_by_path` API
* Remove unused `fetch_file_from_guest` API as this has separate module
  vmware_guest_file_operation
* Remove unused `push_file_to_guest` API as this has separate module
  vmware_guest_file_operation
* Refactor exception variables
* Change GPL License boilerplate to one-liner

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/vmware.py

##### ANSIBLE VERSION

```
2.6devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@pdellaert Could you please review this ?

**Comment by Akasurde** [comment]
@jctanner @tchernomax @jamesmarshall24 @karniemi @thorus90 Can someone please review this ?

**Comment by thorus90** [comment]
This fails for me with pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission), but so does it since 2.5.0a. This is the first time testing a pull request, so I followed http://docs.ansible.com/ansible/latest/dev_guide/testing.html#how-to-test-a-pr and I don't know if I did it correctly. Sry

**Comment by Akasurde** [comment]
@thorus90 NoPermission issue is different than this PR. I guess user which you have specified in Playbook does not have permission which required. I am not sure which property or what permission is missing (as I was unable to reproduce the issue with the permission you have provided).

**Review by mkrizek — COMMENTED** [review]
I don't know how to run it, but code changes look good to me :+1:

**Comment by Akasurde** [comment]
@mkrizek APIs are obsolete so removed. And rest is change in license boilerplate.

**Comment by Akasurde** [comment]
@mkrizek Thanks for the review.

**Pull request merged**
