### PR TITLE
Rel240/fix nxos pim interface

### PR DESCRIPTION
**Pull request by mikewiebe**
##### SUMMARY
**NOTE:** This fix is a must have for 2.4

This fix resolves multiple idempotence issues with `nxos_pim_interface`, increases the level of integration test coverage and fixes a unit test defect.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_pim_interface

##### ANSIBLE VERSION
```
ansible 2.5.0 (rel240/fix_nxos_pim_interface 5297c791fd) last updated 2017/09/11 22:12:52 (GMT -400)
  config file = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### ADDITIONAL INFORMATION
This fix resolves multiple idempotence issues with `nxos_pim_interface`, increases the level of unit test coverage and fixes a unit test defect.

### CODE REVIEW

**Review by trishnaguha — APPROVED** [review]

**Comment by trishnaguha** [comment]
@mikewiebe will you please rebase? 
Thank you.

**Comment by Qalthos** [comment]
For some reason this is broken on nxapi, where instead of reporting `dr-priority: 10`, it reports `no-dr-priority: false`, and I cannot fathom why

**Comment by mikewiebe** [comment]
@Qalthos That is strange.  I just verified again and all tests pass across all of my targets including a physical `n7k` running image version `D1`

Possibly a titanium issue?

**Comment by gundalow** [comment]
Discussion on Thursday 14th Sept with NXOS team this may be an `I5(1)` vs `I5(3)`

@mikewiebe to test against `I5(1)`

**Comment by mikewiebe** [comment]
@Qalthos and @gundalow 

I verified this works on I5(1) on both physical and virtual testbeds.

Here are the virtual testbed results:
```shell
PLAY RECAP **************************************************************************************************************************************************************************************************************************************
n9k.example.com   : ok=69   changed=19   unreachable=0    failed=0   

```

**Comment by Qalthos** [comment]
Right, I can't reproduce anymore either, merging

**Pull request merged**
