### PR TITLE
Adds the ipaddress compat library backport from Python 3.x

### PR DESCRIPTION
**Pull request by caphrim007**
##### SUMMARY

This library is a backport (to 2.x versions of Python) of the code
that is found in the mainline versions of Python 3.x. It is being
included so that networking vendors, and others, can make use of it
without needing to add a python module dependency to their own modules.

A separate dependency would add to user burden of satisfying those
dependencies before using some Ansible modules.

In a previous core meeting, this was approved. Naming of the directory
it is found in was up for debate, but "compat" was the first directory
to have some sort of concensus.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

compat/ipaddress.py

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  5 2018, 03:32:06) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION

Adds unit tests for the ipaddress compat file.
    
The only change made to this from the upstream file is that I changed
the "ipaddress" import statement to reference the path to Ansible's
copy instead of using the relative "import ipaddress" string used
in the original file.

```

```

### CODE REVIEW

**Comment by mattclay** [comment]
bot_status

**Comment by clementtrebuchet** [comment]
Lo

**Comment by caphrim007** [comment]
@clementtrebuchet what?

**Comment by caphrim007** [comment]
I'm aware of the failures. waiting on core team for guidance on whether they should be fixed or not as this is a backported file and not necessarily "part" of ansible.

**Comment by caphrim007** [comment]
@abadger mentioned in IRC

"""
Yes, I think it's better to stay close to upstream rather than modifying the code to satisfy the tests.
""

**Pull request merged**
