### PR TITLE
New Module: zabbix user

### PR DESCRIPTION
**Pull request by rubentsirunyan**
##### SUMMARY
Created a new module for interacting with Zabbix users.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
zabbix_user

##### ADDITIONAL INFORMATION
[API documentation](https://www.zabbix.com/documentation/4.0/manual/api/reference/user/object)

### CODE REVIEW

**Comment by D3DeFi** [comment]
Hi Ruben. This is unfortunate coincidence, but addition of zabbix_user module was submitted & reviewed some time ago (#56815). I do like your work very much (as always), but I guess it would be unfair to close the other PR as it was submitted first. Will you be up to maybe reviewing it and casting your suggestions to it?

Btw, you can always check if there is not something open before starting work on a module or issue [here](https://ansible.sivel.net/pr/byfile.html).

Only thing missing in the other PR is a single shipit vote from another module or core maintainer to merge it. This has been an irritating problem for me for the past year as I seem to be the last active maintainer of zabbix modules. 

I am mentioning this, because I wanted to ask you if you would be interested in becoming a maintainer for the whole zabbix module namespace alongside me. Your work has been very helpful lately and you seem to be quite active. 

What do you say, are you up to it? And don't worry if you are missing some knowledge about ansible repository or work flows, I am learning on the go as well :)

**Comment by rubentsirunyan** [comment]
Oops. I thought I searched for an open PR before starting to work on this :) Whatever, I will review the other PR and see if we can port something useful from here :)

> I am mentioning this, because I wanted to ask you if you would be interested in becoming a maintainer for the whole zabbix module namespace alongside me.

If it does not require some regular activity (besides [this](https://docs.ansible.com/ansible/latest/community/maintainers.html#maintainer-responsibilities)) then of-course I am up for it. I just want to be sure that I can find enough time for this activity.

**Comment by D3DeFi** [comment]
> Oops. I thought I searched for an open PR before starting to work on this :) Whatever, I will review the other PR and see if we can port something useful from here :)

Thank you!

> If it does not require some regular activity (besides [this](https://docs.ansible.com/ansible/latest/community/maintainers.html#maintainer-responsibilities)) then of-course I am up for it. I just want to be sure that I can find enough time for this activity.

I wouldn't say it requires regular activity. I either address issues/PRs as they come or leave them hanging for a week or longer depending on how much free time I have in that moment. Really no pressure here as it is an open source and no one can require you to work full time on this.

I've had months when there was nothing to do at all. Mostly, it is just reviewing other contributor's patches :) At first, ansibot will spam you with every open issue/PR at the moment, most of which I've already addressed, because they are waiting for a second module/core maintainer shipit vote. 

And ofc you wouldn't be doing this alone! :)

**Comment by rubentsirunyan** [comment]
Ok, then let's start :)

**Comment by D3DeFi** [comment]
Awesome. Closing this as agreed upon. I am sorry tho.

duplicate_of 56815

**Pull request closed without merging**
