### PR TITLE
RSA 1024 to RSA 4096

### PR DESCRIPTION
**Pull request by stylersnico**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME
- ConfigureRemotingForAnsible.ps1
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Small change to use 4096 bits RSA keys as default for this script (especially for win servers managed over the Internet).
- Debian's guide to key creation currently recommends 4096 bit keys.
- Fedora's archive keys are all 4096 bit keys.
- BSI recommends at least 3072 bits key for 2017 - 2021.
- RSA 4096 is fully supported by Ansible and Windows Servers and safer.

Also, I propose to use a 3-year certificate, so you don't have to renew all your certs every year. 
This is generally the lifetime of a server (we keep them for 3 to 5 years in my job).

Finally, I think that this is a good idea to use the new `Microsoft Enhanced Cryptographic Provider v1.0` with ECDSA keys for this script but, I'm a dick in PS and I don't know how to do this.

### CODE REVIEW

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
@stylersnico Please rebase !

@nitzmahone Can this be merged ?
I am disappointed we missed the v2.3 deadline for this one.

**Comment by resmo** [comment]
@stylersnico reminder, please rebase.

**Comment by stylersnico** [comment]
@resmo & @dagwieers Sorry for the delay. It's done

**Comment by stylersnico** [comment]
-> https://github.com/ansible/ansible/pull/23684

**Pull request closed without merging**
