### PR TITLE
Fix iosxr integration test socket issue

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

Add task retry logic to workaround for socket close
issue from iosxr test instance

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

 test/integration/targets/prepare_iosxr_tests/tasks/main.yml

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
https://logs.zuul.ansible.com/40/61240/59fa7d3dcc51cc49c0740b69c29771df8466464c/third-party-check/ansible-test-network-integration-iosxr-python37/c88e887/controller/ansible-debug.html#l95669
Above failure seems to be a network/iosxr instance issue and not related to `Socket is closed` issue.
```
2019-08-24 09:11:18,658 p=zuul u=7566 | TASK [iosxr_user : Collection of users (SetUp)] ********************************
2019-08-24 09:11:18,745 p=zuul u=8412 | <38.108.68.233> attempting to start connection
2019-08-24 09:11:18,746 p=zuul u=8412 | <38.108.68.233> using connection plugin netconf
2019-08-24 09:12:44,053 p=zuul u=7579 | persistent connection idle timeout triggered, timeout value is 100 secs.
See the timeout setting options in the Network Debug and Troubleshooting Guide.
2019-08-24 09:12:44,159 p=zuul u=7579 | shutdown complete
2019-08-24 09:12:58,424 p=zuul u=8315 | persistent connection idle timeout triggered, timeout value is 100 secs.
See the timeout setting options in the Network Debug and Troubleshooting Guide.
2019-08-24 09:12:58,630 p=zuul u=8315 | shutdown complete
2019-08-24 09:12:58,702 p=zuul u=7566 | fatal: [iosxr-6.1.3]: FAILED! => 
  msg: |-
```

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request closed without merging**
