### PR TITLE
module for parsing cloudformation files

### PR DESCRIPTION
**Pull request by sjmiller609**
##### SUMMARY

New module 'cloudformation_parse' - sometimes a user may want to parse a cloudformation file before deploying it. You can't parse yaml cloudformation with normal yaml parsing because the built-in functions cannot be parsed without special yaml handling (e.g. !Ref). This will also work for json cloudformation.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

cloudformation_parse

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION
cfn-flip is used for parsing the cloudformation files. This python module is supported by amazon https://github.com/awslabs/aws-cfn-template-flip

### CODE REVIEW

**Review by ryansb — COMMENTED** [review]
I think this might be better suited as a lookup plugin. That way users could do:

```
set_fact: '{{ lookup("cloudformation_parse", "myfile.yml") }}' 
```
Then that will return the full dict, and they can pipe it to `json_query` to grab specific pieces if they need it, or add other values.

**Comment by sjmiller609** [comment]
@ryansb I agree with your point

**Comment by ryansb** [comment]
Great, you can look at some of the existing lookups, such as `env` https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/env.py to see what to inherit from/how to take args.

**Comment by sjmiller609** [comment]
@ryansb Thanks Ryan for the example

**Comment by sjmiller609** [comment]
@ryansb Let me know what you think. Thanks

**Comment by sjmiller609** [comment]
I'm going to close and re-open to get the ball rolling

**Pull request closed without merging**
