### PR TITLE
Add postgresql_db and postgresql_use checkmode.

### PR DESCRIPTION
**Pull request by cocoy**
Checks user if exists first.

### CODE REVIEW

**Comment by dhozac** [comment]
This has a number of whitespace issues. Make sure you use 4 spaces instead of tabs everywhere.

**Comment by mpdehaan** [comment]
@cocoy, can you fix this one up?   Thanks!

**Comment by mpdehaan** [comment]
Merged, still had a few space things I fixed up.

**Comment by mpdehaan** [comment]
Thanks!

**Pull request merged**
