### PR TITLE
Allow inventory to be a directory containing other inventories

### PR DESCRIPTION
**Pull request by dhozac**
Supports both scripts and hosts files, mixing and matching as users see fit. Processes them in lexicographical and blends all records, allowing later inventories to override variables set in previous ones.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Very very nice.  In queue for testing!

**Comment by mpdehaan** [comment]
One possible gotcha, if you have host_vars and group_vars in this setup and sometimes use "-i dir" and other times "-i path/to/file/inside/dir" it might be confusing where host_vars should be.

Not sure what is the best course in that case.

**Comment by dhozac** [comment]
Maybe they should always be inside of the directory, that way it should work most of the time for most people, while keeping everything together. I've added a commit that enables this.

**Comment by mpdehaan** [comment]
Perfect.

**Comment by mpdehaan** [comment]
While with a default inventory setup this seems generally operational for the non-directory case, attempting to run the unit tests results in me getting a lot of tracebacks.

Here is one of them:

# 

## FAIL: test_command (TestRunner.TestRunner)

Traceback (most recent call last):
  File "/home/mdehaan/ansible/test/TestRunner.py", line 123, in test_command
    result = self._run('command', [ "/bin/echo", "hi" ])
  File "/home/mdehaan/ansible/test/TestRunner.py", line 76, in _run
    assert "localhost" in results['contacted']
AssertionError: 
    # when using nosetests this will only show up on failure
    # which is pretty useful
    print "RESULTS=%s" % {'dark': {'localhost': {'msg': 'Traceback (most recent call last):\n  File "/home/mdehaan/ansible/lib/ansible/runner/__init__.py", line 297, in _executor\n    exec_rc = self._executor_internal(host)\n  File "/home/mdehaan/ansible/lib/ansible/runner/__init__.py", line 318, in _executor_internal\n    host_variables = self.inventory.get_variables(host)\n  File "/home/mdehaan/ansible/lib/ansible/inventory/__init__.py", line 269, in get_variables\n    self._vars_per_host[hostname] = self._get_variables(hostname)\n  File "/home/mdehaan/ansible/lib/ansible/inventory/__init__.py", line 279, in _get_variables\n    for updated in map(lambda x: x.run(host), utils.plugins.vars_loader.all(self)):\n  File "/home/mdehaan/ansible/lib/ansible/utils/plugins.py", line 119, in all\n    yield getattr(self._module_cache[path], self.class_name)(_args, *_kwargs)\nAttributeError: \'module\' object has no attribute \'VarsModule\'\n', 'failed': True}}, 'contacted': {}}

> >  assert "localhost" in {'dark': {'localhost': {'msg': 'Traceback (most recent call last):\n  File "/home/mdehaan/ansible/lib/ansible/runner/**init**.py", line 297, in _executor\n    exec_rc = self._executor_internal(host)\n  File "/home/mdehaan/ansible/lib/ansible/runner/__init__.py", line 318, in _executor_internal\n    host_variables = self.inventory.get_variables(host)\n  File "/home/mdehaan/ansible/lib/ansible/inventory/__init__.py", line 269, in get_variables\n    self._vars_per_host[hostname] = self._get_variables(hostname)\n  File "/home/mdehaan/ansible/lib/ansible/inventory/__init__.py", line 279, in _get_variables\n    for updated in map(lambda x: x.run(host), utils.plugins.vars_loader.all(self)):\n  File "/home/mdehaan/ansible/lib/ansible/utils/plugins.py", line 119, in all\n    yield getattr(self._module_cache[path], self.class_name)(_args, *_kwargs)\nAttributeError: \'module\' object has no attribute \'VarsModule\'\n', 'failed': True}}, 'contacted': {}}['contacted']
> >     return {'dark': {'localhost': {'msg': 'Traceback (most recent call last):\n  File "/home/mdehaan/ansible/lib/ansible/runner/__init__.py", line 297, in _executor\n    exec_rc = self._executor_internal(host)\n  File "/home/mdehaan/ansible/lib/ansible/runner/__init__.py", line 318, in _executor_internal\n    host_variables = self.inventory.get_variables(host)\n  File "/home/mdehaan/ansible/lib/ansible/inventory/__init__.py", line 269, in get_variables\n    self._vars_per_host[hostname] = self._get_variables(hostname)\n  File "/home/mdehaan/ansible/lib/ansible/inventory/__init__.py", line 279, in _get_variables\n    for updated in map(lambda x: x.run(host), utils.plugins.vars_loader.all(self)):\n  File "/home/mdehaan/ansible/lib/ansible/utils/plugins.py", line 119, in all\n    yield getattr(self._module_cache[path], self.class_name)(_args, *_kwargs)\nAttributeError: \'module\' object has no attribute \'VarsModule\'\n', 'failed': True}}, 'contacted': {}}['contacted']['localhost']

**Comment by mpdehaan** [comment]
So question is, did you run the tests?

Or are my tests just different?

**Comment by dhozac** [comment]
I did run the tests, but not after the basedir change. It seemed like it should have been a no-op change, but it turns out we didn't actually allow for vars_plugins before, and the path it was using was incorrect, leading to the errors... Should all be fixed now (also rebased).

**Comment by mpdehaan** [comment]
great, trying now...

**Comment by mpdehaan** [comment]
works great, merged in, thanks!

**Comment by kbroughton** [comment]
(for issue etiquette, wasn't sure if I should tack this on here, or create a new issue and link to it)

folder inventory + vars_plugins does not work

I believe the problem is caused by the changed mentioned above
"Maybe they should always be inside of the directory, that way it should work most of the time for most people, while keeping everything together. I've added a commit that enables this."

With the directory structure below, I would expect to be able to run the following, but the vars_plugin folder never gets searched.  It seems that this makes vars_plugins incompatible with dynamic inventory, or any other situation where an inventory folder is used.

[ansible_deploy_vars] ansible-playbook -i inventory site.yml

├── ansible_deploy_vars
 |     |------- site.yml
│   ├── inventory
│   │   ├── ec2.py
│   │   ├── ec2_hosts_all
│   │   └── ec2_hosts_test
│   └── vars_plugins
│       └── myplugin.py

My hacky solution is to put vars_plugins inside inventory.  It's hacky because my real situation is that i have several different repos with ansible canonical project structure glued together with roles_path in .ansible.cfg.  Each project should be self contained with simple site.yml and hosts/inventory files but then is over-ridden by a master config repo where I'd like to run all playbooks from. So this solution requires adding symlinks all over the place to the real myplugin.py.

I'd like to understand the concern over michael's test scenario better 
"use "-i dir" and other times "-i path/to/file/inside/dir"
and see if there is a way to allow directory inventory to work with the canonical structure
ansible_project
|- hostvars/
|- groupvars/
|- vars_plugins/
|- site.yml
|- roles/

Otherwise, the documentation should be modified to reflect the conflict between the above and invontory-as-directory.  http://docs.ansible.com/developing_plugins.html#vars-plugins

**Pull request merged**
