### PR TITLE
IOS-XR: Handle lowercase in version info

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- To avoid https://github.com/ansible/ansible/issues/59549 in IOS-XR

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
cliconf/iosxr.py

### CODE REVIEW

**Review by justjais — APPROVED** [review]
lgtm +1

**Comment by NilashishC** [comment]
Looks like Zuul is failing because of infra issue.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
