### PR TITLE
support keyring module for sudo passwords

### PR DESCRIPTION
**Pull request by akvadrako**
As discussed in https://github.com/ansible/ansible/issues/2182

I did want to make the key name configurable, which would be easy in argparse, but a hack in optparse, so I left that out.

### CODE REVIEW

**Comment by dhozac** [comment]
This breaks specifying the default for ask_sudo_pass in the configuration file. Should be an easy fix...

**Comment by akvadrako** [comment]
OK, I'll look at that. I didn't notice because I always use -K, since I don't always want to use sudo (but I do always need to supply a password).

**Comment by mpdehaan** [comment]
asking for the password should happen only in /usr/bin/ansible and playbook CLI programs, not core.   The core should just use what was passed in.

Also I see this has some stray prints in the code that should not be there.

It seems if this is going to be useful we should also add the keyring module to the list of RPM dependencies, but should also make sure it is in EPEL first.

**Comment by akvadrako** [comment]
Hi -

it _is_ only in the CLI programs; it's near the option parsing code.

Stray prints like? The Makefile fix was so pyflakes runs on this module - why shouldn't that be there?

I don't understand the comment about EPEL. This is for the workstation, not the server.

On Feb 24, 2013, at 16:01, Michael DeHaan <notifications@github.com<mailto:notifications@github.com>> wrote:

asking for the password should happen only in /usr/bin/ansible and playbook CLI programs, not core. The core should just use what was passed in.

Also I see this has some stray prints in the code that should not be there.

It seems if this is going to be useful we should also add the keyring module to the list of RPM dependencies, but should also make sure it is in EPEL first.

**Comment by mpdehaan** [comment]
Hmm, correct.

Needs to be taken out of the constructor code though.

the A and <function call> part makes debugging weird.

**Comment by mpdehaan** [comment]
"This is for the workstation, not the server."

That doesn't matter.

if you install Ansible on Linux, shouldn't it pull in keyring if you have
it?

**Comment by akvadrako** [comment]
OK - I have moved it out of the constructor. I do think the way I did it is cleaner and is supports configuring DEFAULT_SUDO_PASS - but it's inconsistent with how some other options are passed.

Sorry - I misunderstood your comment about RPM - I thought you meant "to be useful" we must have an RPM dependency. I have added dependencies to RPM and debian packages.

**Comment by mpdehaan** [comment]
Thanks.

what was the reason for the pyflakes change?   I see that one under "remove stray print" as a commit, though that's not what is in that particular commit.

**Comment by mpdehaan** [comment]
re af769edde2bc2ec107aa4eabec0bcfe2940a2b6d

**Comment by mpdehaan** [comment]
looks like python-keychain is not in EPEL 6.

So the RPM is going to need a conditional to only include it on Fedora, perhaps.

**Comment by akvadrako** [comment]
Ah :) Again I misunderstood - I thought by stray print you meant "foot/hand print" - like a little change that should not be in the pull request. The print statement is there on purpose to be consistent; when there is no key in the keychain getpass() writes to stdout.

It's keyring, not keychain; I keep making that mistake too:

> download.fedora.redhat.com/pub/fedora/epel/6/x86_64/python-keyring-0.7-1.el6.noarch.rpm

**Comment by mpdehaan** [comment]
ok, sounds reasonable.

You need to revert the change to the make target unless there's a reason for it.

**Comment by akvadrako** [comment]
That commit was reverting it.

**Comment by mpdehaan** [comment]
Ok, in queue for testing, thanks!

**Comment by mpdehaan** [comment]
If I don't have a password set in my keyring, it gives me "Please set a password for your keyring" without a colon or anything, which is a little confusing.

Similarly, "Please input your password for the keyring" doesn't have any colons after it. 

This is a little jarring seeing the normal "ask sudo password" has a nice colon after it and it's clear you are supposed to input something. 

Any chance this can be tweaked to fix the command line prompts?

**Comment by akvadrako** [comment]
that is part of the keyring code, but looking at the source, it has colons after it.

Which version of keyring do you have?

**Comment by mpdehaan** [comment]
I installed whatever was available in CentOS 6.

**Comment by akvadrako** [comment]
So that's 0.7; current is 1.2.2. We could do a few things:
- enable keyring via a config option
- enable only when a newer version (>1.0) is detected, which they can install with easy_install
- enable only when the non-builtin keyring is detected

**Comment by mpdehaan** [comment]
Great!

I think I like the config option approach, with the instructions also being
in the config file about where you should get it from, and we can also
mention that it the documentation.  Otherwise people will wonder why it
isn't loading.

That would be great.  I want the feature, the output on the old 0.7 is just
(unfortunately) frustrating.

I suspect we would like to make this work for both --ask-pass and
--ask-sudo-pass too, and use service keys like "ansible-pass-<hostname>"
and "ansible-sudo-<hostname>" ?

**Comment by akvadrako** [comment]
I'll implement the config file and also see about using it for ssh passwords - it shouldn't be hard but it's not something I would ever use.

But I don't want ansible-sudo-<hostname> since we have centralised authentication and my password is the same on every machine.

On Mar 2, 2013, at 16:45, Michael DeHaan <notifications@github.com<mailto:notifications@github.com>> wrote:

Great!

I think I like the config option approach, with the instructions also being
in the config file about where you should get it from, and we can also
mention that it the documentation. Otherwise people will wonder why it
isn't loading.

That would be great. I want the feature, the output on the old 0.7 is just
(unfortunately) frustrating.

I suspect we would like to make this work for both --ask-pass and
--ask-sudo-pass too, and use service keys like "ansible-pass-<hostname>"
and "ansible-sudo-<hostname>" ?

**Comment by mpdehaan** [comment]
Still, not everyone's password _is_ the same on every machine.   And most
of those people are using keys.

So that seems like it should be another option.

[ssh-connection]
use_python_keyring=0/1
keyring_password_per_machine=0/1

It also seems like it would need some way to be able to invalidate the key
if it was incorrect... how's that work?

That might be a deal breaker.

**Comment by akvadrako** [comment]
On Mar 2, 2013, at 17:07, Michael DeHaan notifications@github.com wrote:

> Still, not everyone's password _is_ the same on every machine. And most 
> of those people are using keys. 

Yes, but using SSH keys doesn't affect sudo. All this stuff is possible but it's no longer simple and way more than I need - just one sudo password.

**Comment by mpdehaan** [comment]
No, the comment about SSH keys was just to say that people typically use
that to avoid password issues :)

It sounds like there are too many permutations here and you may be best by
just making your own copy of /usr/bin/ansible (or
/usr/bin/ansible-playbook) with those modifications in it?

**Comment by akvadrako** [comment]
Currently, ansible doesn't allow per-host sudo passwords, so why is it required to add that support in this patch?

Also, SSH keys are unrelated to sudo passwords.

So I have made the changes so keychain is a config option and it's also used for SSH ask-pass.

**Comment by mpdehaan** [comment]
It has been requested that --ask-pass be per host.  Thus in moving forward
and adding new features, we need to consider those kinds of requests.

That being said, I think just handling sudo and the one password is
sufficient for now, since it's still configurable.  We can go with that.

**Comment by mpdehaan** [comment]
We'll have to document how you invalidate the keyring too.

Pointers?

**Comment by akvadrako** [comment]
I think if ask-pass was per-host it would be easy to add keyring support, but I would never use SSH passwords so I don't can't imagine the use case and happy to leave support or revert it.

Each keyring implementation handles invalidation in it's own way. Perhaps it's an idea for the keyring wiki: https://bitbucket.org/kang/python-keyring-lib/wiki/Home

**Comment by mpdehaan** [comment]
Yeah, I never use passwords either.

It doesn't seem to be manageable if you do.

**Comment by jkleckner** [comment]
Regarding the version of python-keyring, this security note provides some reason to want versions >= 0.9.2.
  http://www.ubuntu.com/usn/usn-1634-1/

**Comment by mpdehaan** [comment]
Doesn't seem like we got a solution on this one that fulfills all of the requirements, you could run with a modified ansible wrapper script if you want...

**Pull request closed without merging**
