### PR TITLE
Update setup.yml

### LINKED ISSUE #35509: add ocfs2 support for module filesystem
SUMMARY
add ocfs2 support for module filesystem

ISSUE TYPE
• Feature Idea

COMPONENT NAME

filesystem

ANSIBLE VERSION
since ansible 1.9

### PR DESCRIPTION
**Pull request by lchantre**
#35509 add ocfs2 support for module filesystem

Test for Fix  #35509

 - Feature Pull Request

module filesystem

ansible version dev

### CODE REVIEW

**Comment by pilou-** [comment]
There is no need to create a pull-request per update, please move all the updates in #35551. Don't hesitate to ask if some guidance about Git or GitHub usage would be useful.

**Comment by lchantre** [comment]
Hello,
I don't know how to move all the updates in #35551

**Comment by pilou-** [comment]
I commented there: https://github.com/ansible/ansible/pull/35551#issuecomment-361999788. Let me known if this doesn't work.

**Comment by Akasurde** [comment]
Closed via 4f86bec97770ba7d03f92ef45c01227dc22d9934

**Pull request closed without merging**
