### PR TITLE
os_user_role: add support for named domain

### LINKED ISSUE #49859: os_user_role: add support for named domain
##### SUMMARY
It would be useful for the `os_user_role` module to support a name in addition to an UUID in the `domain` option.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
os_user_role

##### ADDITIONAL INFORMATION
Here's an example playbook using this feature:

```yaml
- name: "Give MY_USER admin rights on project MY_PROJECT"
  os_user_role:
    cloud: default
    interface: internal
    state: present
    user: "MY_USER"
    role: "admin"
    project: "MY_PROJECT"
    domain: "MY_DOMAIN"
```

It currently fails with the following error:

```
The full traceback is:
  File "/tmp/ansible_o9LI1L/ansible_module_os_user_role.py", line 182, in main
    cloud.grant_role(role, **kwargs)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 10601, in grant_role
    project, domain)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 10559, in _get_grant_revoke_params
    self.get_domain(domain)['id']
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 10011, in get_domain
    error_message=error_msg)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 328, in get
    return self.request(url, 'GET', **kwargs)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/openstack/_adapter.py", line 164, in request
    return _json_response(response, error_message=error_message)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/openstack/_adapter.py", line 95, in _json_response
    exceptions.raise_from_response(response, error_message=error_message)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/openstack/exceptions.py", line 212, in raise_from_response
    http_status=http_status, request_id=request_id

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_timeout": null, 
            "auth": null, 
            "auth_type": null, 
            "availability_zone": null, 
            "cacert": null, 
            "cert": null, 
            "domain": "MY_DOMAIN", 
            "group": null, 
            "interface": "internal", 
            "key": null, 
            "project": "MY_PROJECT", 
            "region_name": null, 
            "role": "admin", 
            "state": "present", 
            "timeout": 180, 
            "user": "MY_USER", 
            "verify": null, 
            "wait": true
        }
    }, 
    "msg": "Failed to get domain MY_DOMAIN: Client Error for url: http://x.x.x.x:5000/v3/domains/MY_DOMAIN, {\"error\": {\"message\": \"Could not find domain: MY_DOMAIN.\", \"code\": 404, \"title\": \"Not Found\"}}"
}
```

### PR DESCRIPTION
**Pull request by ctrlaltdel**
Fixes #49859.

##### SUMMARY
Add support for named domain option in os_user_role.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
os_user_role

### CODE REVIEW

**Comment by mnaser** [comment]
shipit

**Comment by scanepa** [comment]
Please, please merge this PR.

**Comment by gtema** [comment]
shipit

**Comment by gtema** [comment]
recheck

**Pull request merged**
