### PR TITLE
Added Jira search function to Ansible Module

### PR DESCRIPTION
**Pull request by pertoft**
##### SUMMARY
Added Jira JQL Search support updated docs and  error handling and Jira Operations update

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
modules/web_infrastructure/jira.py

##### ADDITIONAL INFORMATION

```
(venv) pto:ansible pto$ ansible-playbook jira-test.yml
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************************

TASK [Get CMDB issue] ******************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "cmdb_issue": {
        "changed": true,
        "failed": false,
        "meta": {
            "issues": [],
            "maxResults": 10,
            "startAt": 0,
            "total": 0
        }
    }
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

(venv) pto:ansible pto$
```

### CODE REVIEW

**Comment by pertoft** [comment]
Fixes bug #68313

**Comment by pertoft** [comment]
Sorry for all the spamming... First time im contributing to an ansible project.
The local docker test tools is not wokring on macos

**Comment by pertoft** [comment]
Module has been copied to collections and I have opened another pull request: https://github.com/ansible-collections/community.general/pull/22

**Comment by pertoft** [comment]
I have added the fragment - please let me know if this is how it was intended?

**Comment by Andersson007** [comment]
closed via https://github.com/ansible/ansible/pull/68336
close_me

**Comment by Andersson007** [comment]
close_me

**Pull request closed without merging**
