### PR TITLE
Cron support

### PR DESCRIPTION
**Pull request by dsummersl**
I've put together a plugin with support for cron. It supports the following parameters:
- name: description of the cron job
- user: which user to install the cron jobs under.
- job: the cron job itself (ie, "0 12 \* \* \* somjob.sh")
- state: absent|present

The library puts a comment "#Ansible: <name>" on the line prior to the cron job which it uses to find/update/remove jobs. Perhaps thats overly complex but I figured it provides some flexibility with other jobs already setup for a user in some other way (package installs perhaps?).

### CODE REVIEW

**Comment by mpdehaan** [comment]
A few things:

Pull requests need to be submitted as squash commits for review -- aka just one commit

Merge commits should never appear in a pull request

Reference to puppet (in the tests) shouldn't be there.

Tests and references to vagrant shouldn't be there, ansible does not depend on vagrant or require people to understand it -- it is virtualization type agnostic

Any cron module should not require any magic "ansible" lines, it should be able or add any cron job.  I think Puppet did a pretty good job identifying the required parameters for managing cron here, so you may want to take a look at:

http://docs.puppetlabs.com/references/latest/type.html#cron

Just supporting the basics would be ok.

If the module completely rewrites the cron file that would probably be ok, but it should probably also support the backup option as copy/template/others do.

**Comment by mpdehaan** [comment]
further, modelling the nature of cron, so that I can say "hour=4" and so on versus the native cron spaces and asterisks syntax is something we really need to have.   No one wants to remember what all the spaces in the cron lines are.  If they wanted to, they could just fake out a .d directory and use the assemble module

**Comment by dsummersl** [comment]
I'll revisit this tomorrow and try to get another pull request out tomorrow...Sorry about the vagrant patches I kinda got a mess of accidental commits in that branch; I'll try to clean those up before the next pull request.

**Comment by mpdehaan** [comment]
not a problem.

thanks!

**Pull request closed without merging**
