### PR TITLE
fix failure on re-run as reported in https://github.com/ansible/ansible/issues/41536

### LINKED ISSUE #41536: Typo in win_domain module
##### SUMMARY
As also reported in this [thread](https://groups.google.com/forum/?hl=no#!topic/ansible-project/FDODw6B8njY) running the win_domain module a second time fails due to a typo in the module.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_domain

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /Users/lars/.ansible.cfg
  configured module search path = [u'/Users/lars/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:14) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT
Windows Server 2016 is the target

##### STEPS TO REPRODUCE
```yaml
- name: Ensure domain exists
  register: domain_result
  win_domain:
    dns_domain_name: opencore.com
    safe_mode_password: foobar
```

Then run two times.

##### EXPECTED RESULTS
I expect it to work not only on the first but also on subsequent runs

##### ACTUAL RESULTS

```
fatal: [ad]: FAILED! => {"changed": false, "module_stderr": "Exception calling \"Run\" with \"1\" argument(s): \"Exception calling \"Invoke\" with \"0\" argument(s): \"The running command \r\nstopped because the preference variable \"ErrorActionPreference\" or common parameter is set to Stop: The specified \r\nargument 'InstallDNS' was not recognized.\r\n\"\"\r\nAt line:65 char:5\r\n+     $output = $entrypoint.Run($payload)\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : ScriptMethodRuntimeException\r\n \r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

The problem seems to be this https://github.com/ansible/ansible/blob/v2.5.4/lib/ansible/modules/windows/win_domain.ps1#L74 where it says _InstallDNS_ it should say _InstallDns_ according to this documentation: https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsforest?view=win10-ps

I also checked in devel and the issue is the same

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### SUMMARY

Fixes #41536

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_domain
##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jborean93** [comment]
@jhawkesworth are you able to create a changelog fragment at https://github.com/ansible/ansible/tree/devel/changelogs/fragments. I am very curious as to how this module works under the covers as parameters are not usually case sensitive (this would be a first for me) but if it fixes the issue I don't see why we can't merge.

**Comment by lfrancke** [comment]
I did not know that it isn't case sensitive. In that case my suggestion doesn't make much sense....and it works on the first run. On the other hand it says that this parameter is invalid. Very weird...

**Comment by jborean93** [comment]
@lfrancke my guess is that this cmdlet doesn't follow the normal cmdlet binding and dynamically inspects are based on the current status. I'm a bit curious as I believe I've run this multiple times without any issues. Do you have any custom modules loaded that could be overriding the inbuilt one?

**Comment by lfrancke** [comment]
No custom modules, no. It's a pretty minimal. I posted the full minimal file that triggers this in the bug. Nothing out of the ordinary I'm afraid.

**Comment by jborean93** [comment]
These changes are implemented and including a changelog in https://github.com/ansible/ansible/pull/41993

**Pull request closed without merging**
