### PR TITLE
Update Docsite edit

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
A small update to the Docsite edit template so that @ansibot does not ask for the issue type.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
plugin.rst.j2

##### DETAILED INFORMATION
Before:
```
<!--- Your description here -->

+label: docsite_pr
```

After:
```
##### SUMMARY
<!--- Your description here -->


##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr
```

### CODE REVIEW

**Comment by dagwieers** [comment]
Idea: We could also introduce a new "ISSUE TYPE", something like "Docsite edit" that @ansibot would support.

**Comment by samccann** [comment]
Some questions -

Why the limit to only modules? Assuming we want this, wouldn't it also apply to plugins etc?
Also, there is another 'edit on github' up in the top right-hand corner that should probably work the same if we are changing things?

**Comment by dagwieers** [comment]
@samccann I don't know why plugins were added, but the template wasn't used. I fixed it now.

I also fixed the breadcrumbs link now. Thanks !

**Comment by dagwieers** [comment]
Any news ?

**Review by gundalow — APPROVED** [review]

**Comment by samccann** [comment]
Hey @dagwieers -it all seems to work as expected now.

...but... (cuz there's always a but...) - the top right link for 'edit on github' doesn't work on plugin pages. This isn't related to your fix (it's broken online as well) - any chance you know where to look for that possible problem?  No worries if not. I figured I'd ask just in case you've already poked around that content and might find a quick fix...

This is a sample page with the problem - https://docs.ansible.com/ansible/latest/plugins/connection/funcd.html

**Pull request merged**
