### PR TITLE
Add processor_vcpu fact for Darwin

### LINKED ISSUE #30688: ansible_processor_vcpus  is not reported on Darwin
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible/module_utils/facts/hardware/darwin.py

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = ['/Users/af/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/af/virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /Users/af/virtualenvs/ansible/bin/ansible
  python version = 3.6.2 (default, Sep 20 2017, 12:41:21) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
macOS Sierra 10.12.6

##### SUMMARY
ansible_processor_vcpus is not reported on darwin. This is because the get_cpu_facts in the darwin modules only reports processor type and count:

It should be possible on Darwin to obtain the number of cores and vcpus (typically cores * 2 to include threads) by reading the following values from sysctl respectively:

https://github.com/ansible/ansible/blob/62f49120cd1c0e7af9d71b8da14b0bc9b21b05ed/lib/ansible/module_utils/facts/hardware/darwin.py#L73

hw.logicalcpu: 4
hw.physicalcpu: 2

On  my laptop:

$ sysctl hw | egrep '(logical|physical)cpu:'
hw.logicalcpu: 4
hw.physicalcpu: 2

##### STEPS TO REPRODUCE
```
$ ansible -m setup all | grep processor
        "ansible_processor": "Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz",
        "ansible_processor_cores": "2",
```

##### EXPECTED RESULTS
```
$ ansible -m setup all | grep processor
        "ansible_processor": "Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz",
        "ansible_processor_cores": "2",
        "ansible_processor_vcpus": "4",
```

##### ACTUAL RESULTS
```
$ ansible -m setup all | grep processor
        "ansible_processor": "Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz",
        "ansible_processor_cores": "2",
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix adds fact related to vcpu in Darwin's setup.

Fixes: #30688

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/facts/hardware/darwin.py

##### ANSIBLE VERSION
```
2.5devel
```

### CODE REVIEW

**Comment by mscherer** [comment]
shipit

**Comment by mscherer** [comment]
You just need to rebase, the failure is a transient one due to a remote service

**Comment by mscherer** [comment]
shipit

**Comment by samdoran** [comment]
shipit

**Comment by alikins** [comment]
LGTM , shipit

(Was this working previously or is this new?)

**Comment by samdoran** [comment]
I didn't go back very far to check, but this wasn't working in `devel` or `2.3`, so I'd say it's new.

**Comment by Akasurde** [comment]
@samdoran Would you like to have this in 2.3 or 2.4 branch ?

**Comment by samdoran** [comment]
@Akasurde Probably wouldn't hurt but not a terribly important backport.

**Pull request merged**
