### PR TITLE
add backup= option to copy. makes a backup of the file on the target

### PR DESCRIPTION
**Pull request by skvidal**
in a file named: $filename.YYYY-MM-DD@HH:MM~

backup=False is default

### CODE REVIEW

**Comment by skvidal** [comment]
updated patch - includes case where destination does not yet exist.

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by jpmens** [comment]
If I read the diff correctly, @skvidal has implemented this such that a file is backed up every time it's copied, which is good.

Would it be a good idea to implement a "backup=once-only" option? I'm in a position where I want to overwrite files (using copy or template) but I really just need a one-time backup. (More don't hurt but those need cleaning up sometime...)

Maybe Seth can think up something cool ...? ;-)

**Comment by jpmens** [comment]
Oh, this is for `copy` only. Seth: feel like making this for `template` as well? :)

**Comment by skvidal** [comment]
I don't know what a one-time backup would be good for. Do you just want the original file and nothing else? If so then issue a command like:

action: command "cp file1 file1.orginalbackup" creates=file1.originalbackup

then just disable the backup for the copy/template/file action.

that's a onetime backup and doesn't require any special code to look for backups.

as to templates I've not remotely looked at what that would require - if you'd like to give it a shot I think that'd be just fine - but I'm a bit strapped on time right now.

**Comment by couvares** [comment]
Is there any reason not to implement this for get_url as well?  If not, I may take a stab at it.

**Comment by mpdehaan** [comment]
no reason not to, go for it!

**Comment by rabb1t** [comment]
Guys, I faced with a problem when backed up a file. It rewrites twise when using 'with_item' construction in playbook and I'm loosing my original file. See my playbook example to reproduce the problem:

lineinfile: dest=/etc/nsswitch.conf regexp="^${item}" insertafter="^#${item}" line="${item} files winbind" backup=yes
with_items:
 -- passwd
 -- group

My ansible version is:
ansible 1.0

(sorry for bad english)

**Pull request merged**
