### PR TITLE
incidental_setup_mysql_db: Fix mysql_packages for Debian integration tests

### PR DESCRIPTION
**Pull request by aminvakil**
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
incidental_setup_mysql_db

### CODE REVIEW

**Comment by samdoran** [comment]
The goal with incidental tests is to [remove them, not update them](https://github.com/ansible/ansible/blob/03320466995a91f8a4d311e66cdf3eaee3f44934/hacking/shippable/README.md#incidental-code-coverage). They only exist because they cover code paths by accident (incidentally). If you would like to help out with removing incidental tests, that would be great.

**Comment by sivel** [comment]
These specific tests have been removed as of today.

**Comment by aminvakil** [comment]
> The goal with incidental tests is to [remove them, not update them](https://github.com/ansible/ansible/blob/03320466995a91f8a4d311e66cdf3eaee3f44934/hacking/shippable/README.md#incidental-code-coverage). They only exist because they cover code paths by accident (incidentally). If you would like to help out with removing incidental tests, that would be great.

I wanted to fix these tests for debian, didn't know it has been planned to be removed.

**Pull request closed without merging**
