### PR TITLE
Add nextcloud_app module

### PR DESCRIPTION
**Pull request by mejo-**
The module `nextcloud_app` is meant to manage apps in a Nextcloud instance. It supports to install/upgrade, enable/disable or query the status of Nextcloud apps.

##### SUMMARY
Adds the new module `nextcloud_app`

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
nextcloud_app

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

### CODE REVIEW

**Comment by alikins** [comment]
(ansibot)
!component =lib/ansible/modules/cloud/nextcloud_app.py

**Comment by mejo-** [comment]
Any opinions? Do you consider the module worth including?

**Comment by j-be** [comment]
Dude, this is awsome! Finally I can add the apps I need after I upgraded nextcloud from my playbook instead of going through the web-ui.

Even better: it contains functionallity I'd like to see exposed as standalone, like the `occ_command` so that one could more easily implement his/her own stuff (in my case maintanence mode control for my backup-playbook and upgrade).

So my suggestion would be to pull out some stuff and create a hierarchy like:

nextcloud_command
* nextcloud_app
* nextcloud_maintanence
* nextcloud_my_fancy_custom_stuff

I think this could already be achieved with your module as well, though I see it as a bit counterintuitive to have `nextcloud_app` as a base module to inherit from.

Does that sound reasonable? I'd be happy to help, though it would be my first contribution to ansible modules, so my code will definetly need some review.

**Comment by mejo-** [comment]
Thanks @j-be for your comments. I agree with you that additional nextcloud modules would be helpful.

> So my suggestion would be to pull out some stuff and create a hierarchy like:

Unfortunately I don't know a way to share code between Ansible modules except moving the code to the core Ansible library. If you find a way to write a parent module `nextcloud_command` and use that one in subsequent `nextcloud_*` modules, that would be awesome and much appreciated :)

Just to let you know, I ship the module as part of my [`ansible-role-nextcloud`](https://gitlab.com/mejo-/ansible-role-nextcloud).

**Comment by mejo-** [comment]
Did anyone of the Ansible maintainers find time to look into the module yet? Would be awesome to get it merged into Ansible anytime soon.

**Comment by j-be** [comment]
Yeah... I ran into the same issue. I don't fully understand currently how Ansible module inheritance in a way we would need it here would work. As a workaround I currently extracted some portions of your code to a dedicated `module_utils` file and use that in my modules. Apart from your `app` (which is just staright-away awesome) I have `command` for arbitrary commands and `maintenance` to control nextcloud's maintenance mode.

I ran into some problems where `--output=json` is not accepted by some nextcloud commands and I am still thinking on how to cleanly solve that. That is the reason why I did not yet release my stuff to the public and do not consider it ready for production, but I do plan to do so and I'll definitely will let @mejo-  know.

**Comment by mejo-** [comment]
Is there a chance that this module will be included in Ansible anytime soon?

**Comment by tterranigma** [comment]
@mejo- I have some suggestions about the module

- _Read `nextcloud_path` from the environment_: Eg, `ANSIBLE_NEXTCLOUD_OCC_PATH`. This way the user will not have to specify this information all the time.
- _Search for occ in $PATH_: Maybe the user has already added the `occ` executable to their PATH and the module can get it from there. If it fails, fallback to the environment variable. If that fails too, fail execution
- _Drop `nextcloud_path`: That would be available from the `occ` path above.
- _Document why `app_store_url` is useful.
- _Drop `state: latest` and read it from `version`_: `version` could have a default value of `latest`. If given (and `state: enabled`) install the latest.
- _Rename `platfrom` to `nextcloud_version`_: I think it makes more sense this way.

**Pull request closed without merging**
