### PR TITLE
Common files for QNOS network modules

### PR DESCRIPTION
**Pull request by Quanta-Switch**
##### SUMMARY
These files are common files for adding individual qnos module later.
These files are based on the corresponding ios_xxx files.
This PR is based on 'add new platform for managing Quanta Switches #59569'
##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
lib/ansible/config/base.yml
lib/ansible/modules/network/qnos/__init__.py
test/units/modules/network/qnos/__init__.py
test/units/modules/network/qnos/qnos_module.py

##### ADDITIONAL INFORMATION

```paste below
ansible_network_os=qnos
ansible_connection=network_cli
```

### CODE REVIEW

**Comment by pabelanger** [comment]
This seems to need a rebase

**Comment by ganeshrn** [comment]
@chiuhsiapeng This PR has a merge commit. Please refer the steps here https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html to resolve the issue.

**Review by ganeshrn — APPROVED** [review]

**Comment by samccann** [comment]
@quantasw Yikes, looks like this fell through the cracks. Unfortunately we are no longer accepting new content submissions into the Ansible project, but instead you should create an Ansible Content Collection and publish it on Ansible Galaxy. 

Developing a Collection: https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#developing-collections

Creating a Galaxy namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html

Hope this helps!

**Comment by casper-wu** [comment]
@samccann The purpose of closing this PR is that our PR is not fitting your SPEC or PR request method is changed to use "Ansible-galaxy"?

**Comment by samccann** [comment]
Hi @casper-wu - This PR was closed because yes, going forward, ansible/ansible is not accepting new modules. All new content needs to be within a collection and uploated to Ansible galaxy.

**Pull request closed without merging**
