### PR TITLE
Change the command plugin to pretty print results

### PR DESCRIPTION
**Pull request by keir**
The current behaviour of the shell and command modules is
difficult to read. This adds a slightly smarter printing
mechanism. For example, with this commit applied, the output of a
command with verbose enabled looks similar to:

changed: [companyprod5] =>
    cmd         swap_to_staging.sh
    end         2013-01-22 21:59:28.003997
    stdout

```
    git branch -D staging_old...
    git checkout -b staging_old...
    git branch -D staging...
    git checkout -b staging staging-web-tag...
    Last commit on the branch:
    commit 540a643b26b1764e4e3a32db83c85addfbeca78e
    Author: John Smith <jsmith@company.com>
    Date:   Tue Jan 22 02:45:24 2013 +0000

        Revert accidental deletion.

        Reviewers: jane

        Reviewed By: jane

        Differential Revision: https://phabricator.company.com/D5531

changed     True
start       2013-01-22 21:59:27.987241
delta       0:00:00.016756
stderr
rc          0
```

A feature of note is that the stdout is indented in a block to
make it clear that the output from 'stdout' is the indented block.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks pretty clean, thanks, I'll check it out and let you know what I think -- a few initial thoughts.

(A) I would remove the inner functions for clarity since we do not explicitly need closures, and this makes the code a bit more readable with having smaller functions, and also makes things a bit more reusable.

(B) This should also be applied to the output of the 'script' module, and possibly 'raw'.

**Comment by keir** [comment]
(A) I made the functions inner functions because they weren't used anywhere, but I can promote them to toplevel. Should they stay in the same file? Do you have a preference for where they should go?
(B) I can do that.

**Comment by mpdehaan** [comment]
(A) same file is fine.

Another thing I noticed was that if you run /usr/bin/ansible it doesn't print out the same way.  It probably should for consistency, but then again, maybe people don't want the indented whitespace there, so this is probably doing the right thing.

If we are going to pretty print this, the other thing I question is if we should just attempt to pretty print everything, keys sorted.

And if so, maybe that should be a configurable option.

I think we should explore that.  It's definitely more verbose, so I suspect not everyone would want it the same way, but I like that it is there.

**Comment by keir** [comment]
I'm open to pretty printing everything; but that suggests we should move the functionality into a different file then trawl the rest of the code for places it should get called.

Any preferences for the location?

**Comment by mpdehaan** [comment]
Let's make it work first (configurable everywhere) and we can see and tweak
how itw works.   Refactoring is pretty easy to move it to other files.

**Comment by cliffano** [comment]
Since this pull request has been closed, has pretty print been included in Ansible? I can't find any info in --help.

**Comment by keir** [comment]
I haven't had the time to refactor the change as requested by Michael to
get it upstreamed. We are still using it in production at work though.

**Pull request closed without merging**
