### PR TITLE
Adds support for VPC subnets to ELB

### PR DESCRIPTION
**Pull request by jimbydamonk**
Adds support through boto for VPC subnets.
- name: Create ELB  
  local_action:
    module: ec2_elb_lb
    state: present
    name: 'New ELB'
    security_group_ids: 'sg-123456, sg-67890'
    region: us-west-2
    subnets: 'subnet-123456, subnet-67890'
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  Or of you have created the through ec2-vpc and register a vpc variable
  - name: Create ELB  
    local_action:
    module: ec2_elb_lb
    state: present
    name: 'New ELB'
    security_group_ids: 'sg-123456, sg-67890'
    region: us-west-2
    subnets: "{{ vpc.subnets | join(',',  attribute='id') }}"  
    listeners:
    - protocol: http
      load_balancer_port: 80
      instance_port: 80

### CODE REVIEW

**Comment by juliedavila** [comment]
+1

Question though, how would you detach subnets? I noticed you followed the same pattern as zones, but zones has the argument "purge_zones", is there not a need for "purge_subnets"?

**Comment by evanccnyc** [comment]
+1 here as well. need this for a current project I am working on

**Comment by jimbydamonk** [comment]
@nousdefions This well set the subnets to be whatever you set subnets to be. I didn't see the  need for a purge_subnets but it would not be too hard to change the functionality to match the zones.

**Comment by juliedavila** [comment]
It would be a "nice to have" feature. Essentially you could just copy the purge_zones code with subnet variables. 

PS: To be honest you beat me to the pull request by about an hour when you first submitted, lol. Nice work!

**Comment by jimbydamonk** [comment]
I will get to this first thing in the morning (Or tonight if I have a chance)

**Comment by jimbydamonk** [comment]
Done !

**Comment by evanccnyc** [comment]
Nicely done. Do you need any testing for this? I would be happy to try it out if you need people to test.

**Comment by juliedavila** [comment]
you Sir are a scholar and a gentleman

**Comment by jimbydamonk** [comment]
@evanccopengeo I tested in a bit last night, but it could always use more eyes. 
@nousdefions Not a problem.

**Comment by juliedavila** [comment]
Line 123 in the examples section, you accidentally included "zones" immediately underneath "subnets" and then listed subnet IDs under zones. 

```
subnets: 
zones:
  - subnet-abcd1234 
  - subnet-1a2b3c4d
```

Other than that, I have tested both the purge and add functions and it works perfect!

**Comment by jimbydamonk** [comment]
Oh right. I will remove those from the examples. Thanks!

**Comment by evanccnyc** [comment]
Any update on getting this checked in?

**Comment by juliedavila** [comment]
Was wondering the same thing. I merged it locally.

**Comment by juliedavila** [comment]
@mpdehaan, input?

**Comment by mpdehaan** [comment]
This is currently in the P2 queue, we are looking at closing out P2 issues before moving on to hit P3s. at which time we're making a sweep through P3's for ones we want to promote and pull in.

As this is 13 days old it is still "pretty new" (note a tremendous amount of incoming PRs to sort) so may need to be ok with not making this current release, but depending on time it may have a shot.  Stay tuned, if not, it's next in line.

**Comment by stevenscg** [comment]
Another +1 vote. Ready to test it on a current project.

**Comment by colstrom** [comment]
+1 from me too. This would fill a hole in my VPC provisioning that relies on manual action.

**Comment by juliedavila** [comment]
You can merge it to your local ansible install manually Chris

**Comment by colstrom** [comment]
As a temporary fix, that works. As long as I know there are plans to merge it. I'd prefer not to rely on a patch to build things out unless I know it will be included in ansible (eventually).

**Comment by jimsmith** [comment]
+1 for me also. I have our VPC setup and looking to move away aggressively from manual actions - be good if this can be merged in as VPC has been standard (default) AWS for a rather long time now and the existing ec2_elb doesn't support VPC and internet-facing scheme.
:)

**Comment by coop** [comment]
In the AWS environment that I'm trying to automate on each application deploy we want to spin up a new ELB + LC + ASG and being able to assign the ELB to the existing VPC is a must (so I love this feature). After trying out this module I can't quite figure out how to pass the VPC's subnets through to the ELB without having to manually know the subnet IDs in advance. This is the code that I'm using:

``` yaml
# ansible/roles/environment/tasks/vpc.yml
- name: vpc | create
  local_action:
    module: ec2_vpc
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    cidr_block: 10.0.0.0/16
    region: us-east-1
    resource_tags:
      team: payments
    state: present
    internet_gateway: True
    subnets:
      - cidr: 10.0.0.0/24
        az: us-east-1a
    route_tables:
      - subnets:
          - 10.0.0.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
  register: vpc
```

``` yaml
# ansible/roles/environment/tasks/elb.yml
- name: elb | create
  local_action:
    module: ec2_elb_lb
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    name: payments-tango-green
    purge_listeners: True
    purge_zones: True
    region: us-east-1
    state: present
    zones:
      - us-east-1a
    subnets: {{ vpc.subnets }}
  register: elb
```

The problem that I'm having is that `vpc.subnets` isn't an array, it looks like:

``` sh
TASK: [environment | debug var=vpc] *******************************************
ok: [localhost] => {
    "item": "",
    "vpc": {
        "changed": false,
        "invocation": {
            "module_args": "",
            "module_name": "ec2_vpc"
        },
        "item": "",
        "subnets": [
            {
                "az": "us-east-1a",
                "cidr": "10.0.0.0/24",
                "id": "subnet-5c2c0f74",
                "resource_tags": {}
            }
        ],
        "vpc": {
            "cidr_block": "10.0.0.0/16",
            "dhcp_options_id": "dopt-421c0b20",
            "id": "vpc-6ac5080f",
            "region": "us-east-1",
            "state": "available"
        },
        "vpc_id": "vpc-6ac5080f"
    }
}
```

What I really want is a `map` function to take the subnets dictionary and return all the ids but I can't find documentation on doing that. Do you have any ideas on how the vpc and elb modules would interact?

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by colstrom** [comment]
@coop Would something like this work for you?

```
subnets: "{{ vpc.subnets | join(',' attribute='id') }}"
```

**Comment by coop** [comment]
@colstrom that. is. amazing. I had no idea something like that was possible.

**Pull request merged**
