### PR TITLE
[2.7] ACME: improve error handling

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #49266: improves error handling for ACME modules.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/acme.py

### CODE REVIEW

**Comment by resmo** [comment]
shipit

**Comment by felixfontein** [comment]
I think I found a little problem; as opposed to `get()`, `pop()` does not return `None` if the key isn't there, but raises an exception. I'll create a PR for that later (with some other small things), which can then be added to this PR once its merged.

**Comment by felixfontein** [comment]
(That `pop()` doesn't return `None` becomes interesting if there's a connection problem, like when you specified something for `acme_directory` which can't be connected to. Probably it will also blow up if you get a 204, or empty response in general. That shouldn't happen with ACME, though, so it's not critical, but it's still ugly if the module dies with a stacktrace if it can't connect...)

**Comment by abadger** [comment]
Merged for the 2.7.5 release.

**Comment by felixfontein** [comment]
@abadger thanks for merging!

**Pull request merged**
