### PR TITLE
win_updates: Small checkmode cleanup

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Harmonizing the checkmode usage in windows modules

### CODE REVIEW

**Comment by dagwieers** [comment]
This relies on ansible/ansible#20141

**Comment by dagwieers** [comment]
@jhawkesworth @nitzmahone ready_for_review

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by dagwieers** [comment]
@mattclay @jhawkesworth @nitzmahone @trondhindenes @JimFicarra @dav1x @jctanner Please review and test this.

**Review by nitzmahone — COMMENTED** [review]
Just at a glance, this doesn't appear to do the right thing. I'm basically smuggling the raw args dict into the scheduled job to avoid needing to rebuild/translate it- by renaming the arg in the argspec, it no longer matches what's in the original dict, so check mode is not respected. You'd have to diddle it in the arg dict, which is what I was trying to avoid.

**Pull request closed without merging**
