### PR TITLE
add shell (fnmatch) style pattern support for the apt module

### PR DESCRIPTION
**Pull request by mvo5**
This branch adds support to install multiple packages via fnmatch style patterns in the "apt" module.

Our use-case is that for a university lab we want to install all r-cran-\* packages and this seems to be the simplest way of doing it. The alternative would be to have a "apt_facts" module that exposes the apt cache information maybe? I'm happy to explore that option if you prefer it, but the approach in this branch looks simpler to understand in a playbook.

Feedback welcome!

Thanks,
 Michael

### CODE REVIEW

**Comment by mpdehaan** [comment]
Happy to test this, though may I request list comprehensions rather than lambda/filter?

Makes things a bit more readable IMHO and also will help us out when these are later deprecated, should we want to make Python 3 versions.

I'd like to avoid apt_facts if possible.

**Comment by mvo5** [comment]
Thanks, I updated the code now to avoid the lambda/filter.

To test you can e.g. run
$ ansible -m apt -a pkg='apt*' test-host
and it should try to install a bunch of apt releated pkgs

With "pkg='apt*:i386'" on a modern amd64 ubuntu you should get a bunch of i386 packages that match the pattern.

**Comment by mpdehaan** [comment]
Looks like this needs to be rebased due to changes in the apt module, can you take care of that?

Thanks!

**Comment by mvo5** [comment]
I update the branch now. Please let me know if more is needed.

**Comment by mvo5** [comment]
Hm, I did a git merge instead of a git rebase, let me see if I can fix this, otherwise I will push a new branch. Sorry for that.

**Comment by mpdehaan** [comment]
Yeah you may be able to fix with a force push, but I'm not sure.

I will let you resubmit this one.  Thanks!

**Comment by uvizhe** [comment]
This commit breaks the ability to install the latest version of package using :
apt: pkg=foo=*
which is valid apt-get action:
apt-get install foo=*

**Comment by mvo5** [comment]
@uvizhe apt: pkg=foo will install the latest already, no? unless you use a special /etc/apt/preferences policy of course.

**Comment by uvizhe** [comment]
@mvo5 sure pkg=foo installs the latest. But when you specify package version in variable and you don't know which is the latest this (foo=*) is the only possibility AFAIK. You can't leave variable empty since "apt: pkg=foo=" is illegal in Ansible.

**Comment by mvo5** [comment]
On Fri, Oct 18, 2013 at 04:40:09AM -0700, uvizhe wrote:

> @mvo5 sure pkg=foo installs the latest. But when you specify package version in variable and you don't know which is the latest this (foo=*) is the only possibility AFAIK. You can't leave variable empty since "apt: pkg=foo=" is illegal in Ansible.

Aha, thanks. Now I understand your use case. I think that "apt:
pkg=foo=newest"  (or candidate or installed) depending on what you
kind will work. This works on the apt commandline and I don't see why
it would not work with the ansible module (can't test right now as I'm
traveling). 

Cheers,
 Michael

**Comment by uvizhe** [comment]
@mvo5 thanks! This magically works!

**Pull request closed without merging**
