### PR TITLE
Feature: os_image: Add tags parameter (issue #30923)

### LINKED ISSUE #30923: os_image does not include "tag" parameter
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os_image

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

default configuration

##### OS / ENVIRONMENT

N/A

##### SUMMARY

when running os_image module, there isn't an option to add a tag to an image.
when running the command through openstack CLI the option is available.
I did not find any other way to tag an image through ansible except running openstack CLI from a shell/command task.
##### STEPS TO REPRODUCE

```
  - name: upload custom image to glance
    os_image:
      filename: "myfile.qcow2"
      name: "test_image"
      disk_format: "qcow2"
      container_format: "bare"
      tag: "experiment"
```

##### EXPECTED RESULTS

image is created in glance with the tag  "experiment"

##### ACTUAL RESULTS

Not possible as this parameter does not exist

```

```

### PR DESCRIPTION
**Pull request by vooon**
##### SUMMARY

Fixes #30923. That PR adds `tags` property to `os_image` module.
`tags` should be a list of strings, if leave default (None) then no changes in tags will be made.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
os_image

##### ADDITIONAL INFORMATION

Tags assignment done a bit quirky way, because passing tags directly to update_image_parameters do not work as expected.
Glance (v18.0.0) always returns Bad Request when i tried to pass tags directly to create or update.

Tested with two versions of OpenStack SDK: 0.27.0, 0.33.0

Both have same result. So i switched to `cloud.image.add_tag()` / `.remove_tag()`
which is works ok, but then always fails inside [resource.add_tag()](https://github.com/openstack/openstacksdk/blob/709f2157863e21176486dbd45220825008e58d0b/openstack/resource.py#L1831).

Signed-off-by: Vladimir Ermakov <vooon341@gmail.com>

### CODE REVIEW

**Review by jamescassell — CHANGES_REQUESTED** [review]
Should support check mode.

**Comment by vooon** [comment]
@jamescassell can you please explain what needs to be done?
Because i don't see any support for module.check_mode in os_image nor in module_utils.openstack.

**Comment by jamescassell** [comment]
> @jamescassell can you please explain what needs to be done?
> Because i don't see any support for module.check_mode in os_image nor in module_utils.openstack.

Fair enough.  os_image should support check_mode, but apparently does not.  That doesn't have to be addressed in this PR.  (I didn't actually check if it supports check_mode because most modules do support it.)

**Review by jamescassell — APPROVED** [review]
shipit

**Review by cloudnull — APPROVED** [review]
shipit

**Comment by vooon** [comment]
ready_for_review

**Review by cloudnull — APPROVED** [review]
shipit

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by vooon** [comment]
@sshnaidm than you for information, and sorry for late response.
Sent for review: https://review.opendev.org/#/c/705343/

**Pull request closed without merging**
