### PR TITLE
[WIP] Galaxy list should not exit on invalid rolespaths if there other valid roles paths

### PR DESCRIPTION
**Pull request by alikins**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

lib/ansible/cli/galaxy.py
##### ANSIBLE VERSION

```
ansible 2.3.0 (galaxy_list_again 5777d831b0) last updated 2016/10/14 16:27:51 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 275fa3f055) last updated 2016/10/12 14:06:23 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 3e1ea76a75) last updated 2016/10/13 11:34:41 (GMT -400)
  config file = /home/adrian/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

'ansible-galaxy list' would fail if any of the paths in rolespaths was invalid (missing or not a dir) even if there were other valid paths.

So this changes list to gather all the failures, then warn if there are still valid roles paths or to exit if there are no valid roles paths.

And a fair amount of refactoring while isolating the various steps in 'list' from each other.

```
```

### CODE REVIEW

**Comment by calfonso** [comment]
@alikins I believe this was solved in a different manner, can this be closed?

**Comment by jctanner** [comment]
cc @s-hertel did you work on something similar to this?

**Comment by jctanner** [comment]
<s> I think I may have fixed this or created the desired behavior in https://github.com/ansible/ansible/commit/af2ce7725b1db4253ef0a14a2eba4a1c640ae2d7 https://github.com/ansible/ansible/pull/17487 </s>

@alikins perhaps I'm confused though because your patch affects "list" rather than "install"

Yeah, I see this is still a problem. https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/galaxy.py#L477-L497

**Comment by alikins** [comment]
shrug

**Pull request closed without merging**
