### PR TITLE
New module icinga2 service

### PR DESCRIPTION
**Pull request by knaapjvd**
##### SUMMARY

This new module compliments the icinga2_host module, allowing for service object provisioning for hosts objects

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
icinga2_service

##### ADDITIONAL INFORMATION

EXAMPLE = 
```
- name: Add a service to a host to icinga
  icinga2_service:
    url: "https://icinga2.example.com"
    url_username: "ansible"
    url_password: "a_secret"
    state: present
    name: "{{ ansible_fqdn }}!nrpe"
    display_name: "NRPE"
    check_command: "nrpe"
    variables:
        nrpe_port: "5667"

- name: Same service but with host/service
  icinga2_service:
    url: "https://icinga2.example.com"
    url_username: "ansible"
    url_password: "a_secret"
    state: present
    host: "{{ ansible_fqdn }}"
    service: "nrpe"
    display_name: "NRPE"
    check_command: "nrpe"
    variables:
        nrpe_port: "5667"
```

RETURN =
```
name:
    description: The name used to create, modify or delete the service
    type: string
    returned: always
data:
    description: The data structure used for create, modify or delete of the service
    type: dict
    returned: always
```

### CODE REVIEW

**Comment by Hatsikki** [comment]
shipit

**Comment by t794104** [comment]
shipit

**Comment by t794104** [comment]
shipit

**Comment by knaapjvd** [comment]
Is there a way to progress this request?

**Comment by knaapjvd** [comment]
@Akint @ApsOps @D3DeFi @K-DOT @NickatEpic @RedWhiteMiko @Sedward @abulimov @akomic @andsens @brian-brazil @bwhaley @cove @dj-wasabi @dmsimard @dstoflet @eikef @ethanculler @harrisongu @hkariti @kavu @logan2211 @martinwangjian @mcodd @n0ts @nate-kingsley @nerzhul @orgito @rubentsirunyan @seuf @skornehl @smbambling @sookido @stympy @suprememoocow @t794104 @tbielawa @tsalle @woz5999

Hi,

I'm broadcasting this to you, the contributors of monitoring modules for Ansible, which is probably very much Not Done, sure. But, would any of you be so kind as to provide feedback/approval?

This module is in use at the company I work for and has successfully provisioned 5000+ services on 300+ hosts. Having it picked up by Ansible would help us because we would no longer need to provide it separately.

**Comment by andsens** [comment]
@knaapjvd you are correct, this is probably very much Not Done.

**Comment by knaapjvd** [comment]
I do apologise. What would have been the correct course of action?

**Comment by orgito** [comment]
> I do apologise. What would have been the correct course of action?

Check the errors from the tests. Make sure you fix everything the tests are complaining about.

**Comment by knaapjvd** [comment]
Yes, I believe that was completed. Ansibot was no longer showing errors on my last commits and the flag for community review was added.
If there is work remaining, please let me know.

**Comment by Hatsikki** [comment]
shipit

**Comment by t794104** [comment]
shipit

**Pull request closed without merging**
