### PR TITLE
ansible smtp mail add username and password

### PR DESCRIPTION
**Pull request by bhcopeland**
Ansible lacks smtp username and password.

### CODE REVIEW

**Comment by jimi-c** [comment]
Why are you removing SSL in the second patch?

**Comment by bhcopeland** [comment]
Because originally it had no logic associated to it. I've added it back in with logic and included STARTTLS. Hope this is okay.

**Comment by jimi-c** [comment]
Rather than checking the port, it may be better to do this:

<pre>
        try:
            smtp = smtplib.SMTP_SSL(host, port=int(port))
            if smtp.has_extn('STARTTLS'):
                smtp.starttls()
        except ssl.SSLError:
            smtp = smtplib.SMTP(host, port=int(port))
        smtp.ehlo()
        if username and password:
            try:
                smtp.login(username, password)
            except smtplib.SMTPAuthenticationError:
                module.fail_json(msg="Authentication to %s:%s failed, please check your username and/or password" % (host, port))
</pre>

This would require an `import ssl` at the top too (for the error catching).

**Comment by bhcopeland** [comment]
ok, thanks for that, this is true. I had to tweak it since I couldn't get it to work with your example. Changed it a little bit, tested it and it seems to work fine now.

**Comment by bhcopeland** [comment]
is this okay?

**Comment by jimi-c** [comment]
@bhcopeland yes, the only thing holding this up is it appears there's a second PR (https://github.com/ansible/ansible/pull/6667) for the same functionality, which I didn't notice until recently. We'll have to figure out which one is the better implementation, so I'll let you know.

**Comment by bhcopeland** [comment]
okay thanks. Have committed version_added as well, the benefit of this pull request is the ability to use smtp in ssl/tls and starttls. Which I need in ansible to work with our infrastructure. When sending username and password across the internet, I'd only do it securely. Although, unsecure does also work :-).

**Comment by mattmakai** [comment]
+1 for username and password fields on mail module, either from this PR or PR #6667. ran into this yesterday

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
