### PR TITLE
Update `Unknown error` to specific error message

### LINKED ISSUE #49713: redfish_facts results an Unknown error
##### SUMMARY

Hello `Ansible` community! 
When executing a simple [playbook](https://github.com/dnuka/automate/blob/master/ansible/redfish_101.yaml) with [redfish_facts](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/redfish/redfish_facts.py) module, results `Unknown error`

<pre><font color="#DC322F">fatal: [HOST]: FAILED! =&gt; {</font>
<font color="#DC322F">    &quot;changed&quot;: false,</font>
<font color="#DC322F">    &quot;invocation&quot;: {</font>
<font color="#DC322F">        &quot;module_args&quot;: {</font>
<font color="#DC322F">            &quot;baseuri&quot;: &quot;http://127.0.0.1:8000/&quot;,</font>
<font color="#DC322F">            &quot;category&quot;: [</font>
<font color="#DC322F">                &quot;Manager&quot;</font>
<font color="#DC322F">            ],</font>
<font color="#DC322F">            &quot;command&quot;: [</font>
<font color="#DC322F">                &quot;all&quot;</font>
<font color="#DC322F">            ],</font>
<font color="#DC322F">            &quot;password&quot;: &quot;VALUE_SPECIFIED_IN_NO_LOG_PARAMETER&quot;,</font>
<font color="#DC322F">            &quot;username&quot;: &quot;foo&quot;</font>
<font color="#DC322F">        }</font>
<font color="#DC322F">    },</font>
<font color="#DC322F">    &quot;msg&quot;: &quot;Unknown error&quot;</font>
<font color="#DC322F">}</font>
</pre>

I'm unable to debug/improve my [playbook](https://github.com/dnuka/automate/blob/master/ansible/redfish_101.yaml) with an error like `Unknown error`. So, I think it would be great if we could improve this to much more verbose error message.

Thanks :)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_facts

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
python version = 3.7.1 (default, Oct 21 2018, 08:03:53) [GCC 8.2.0]
```

### PR DESCRIPTION
**Pull request by warusadura**
##### SUMMARY

Outputs the Exception received rather than just 'Unknown error'

before:
``fatal: [HOST]: FAILED! => {"changed": false, "msg": "Unknown error"}``

after:
``fatal: [HOST]: FAILED! => {"changed": false, "msg": "invalid literal for int() with base 10: ''"}``

fixes: #49713 
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

redfish_facts

### CODE REVIEW

**Review by billdodd — APPROVED** [review]
@dnuka - Thanks for your PR! I reviewed the changes and they look good.

shipit

**Comment by warusadura** [comment]
@billdodd Thank you :)

**Comment by jose-delarosa** [comment]
@dnuka, can you please edit the Summary section above and add a "before" and "after" of what the output looks like? Thanks.

**Comment by warusadura** [comment]
@jose-delarosa Done :)

**Comment by jose-delarosa** [comment]
Thanks. Looks good.

shipit

@billdodd Do you mind pinging the core team again to merge? Afterwards, I will submit a PR to move module_utils.py to modules/remote_management/redfish/ since there aren't any other open/active PRs pending. Thank you.

**Review by billdodd — CHANGES_REQUESTED** [review]
@dnuka - I asked the core folks to merge the change and one of them pointed out that they prefer the use of to_text() over str() to better deal with differences in py2 and py3 native string types. Can you please update to use to_text()? For an example, see:

https://github.com/ansible/ansible/blob/13f2b293053814a917159d93bce11551ed4c7795/lib/ansible/modules/source_control/git.py#L271

https://github.com/ansible/ansible/blob/13f2b293053814a917159d93bce11551ed4c7795/lib/ansible/modules/source_control/git.py#L285-L289

**Comment by warusadura** [comment]
@billdodd 
thank you for the suggestion. I got in to some trouble when pushing the new changes. I just followed the same way as usual with the Gerrit system. `git commit -a --amend` then(without git review) `git push -u origin issue/49713` and ended up with,
```
! [rejected]              issue/49713 -> issue/49713 (non-fast-forward)
error: failed to push some refs to 'https://github.com/dnuka/ansible.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
then followed some online tutorials and ended up with a messy repo. any idea how to resolve this :)
Thanks.

**Comment by billdodd** [comment]
No, I'm afraid I'm not very good at dealing with rejected commits.

Since the changes are pretty small/simple, I might suggest you just close this PR and then make a fresh repo and branch, make and test the changes again and then submit a new PR.

**Comment by warusadura** [comment]
@billdodd 
Thank you :) will do that.

**Comment by warusadura** [comment]
@billdodd @jose-delarosa 
new PR #50129

**Pull request closed without merging**
