### PR TITLE
Diff mode returns yaml diffs in yaml callback plugin

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY
Improve readability of diffs when using yaml stdout callback

Addresses https://github.com/ansible/ansible/pull/45645#issuecomment-431659159

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/callback/yaml

### CODE REVIEW

**Comment by willthames** [comment]
cc @towolf

**Comment by gundalow** [comment]
bot_status

This should be `support:core`
```
  lib/ansible/plugins/callback/__init__.py:
    support: core
```

**Comment by gundalow** [comment]
bot_status

**Review by Xaroth — APPROVED** [review]

**Review by Shaps — APPROVED** [review]

**Comment by Shaps** [comment]
shipit

**Comment by gundalow** [comment]
Merged into `devel` for release in Ansible 2.8

@willthames @Shaps @Xaroth Thank you!

**Pull request merged**
