### PR TITLE
Updates to the parameters of win_feature

### PR DESCRIPTION
**Pull request by trondhindenes**
Added updates to the parameters of win_feature to keep it aligned with the corresponding PowerShell cmdlet (add-windowsfeature). Some code optimization in the script to keep it simple hen dealing with multiple variables.

### CODE REVIEW

**Comment by cchurch** [comment]
:+1:

**Comment by jimi-c** [comment]
@trondhindenes one very minor thing - we typically prefer to split up long variable names with underscores so they're more readable. For instance, `includesubfeatures` should be `include_sub_features` or perhaps just `sub_features`. Could you clean that up, and we'll get this merged in ASAP? Thanks!

**Comment by trondhindenes** [comment]
Gotcha. I managed to delete this branch locally, so I'll close this PR and submit a new one.

**Comment by trondhindenes** [comment]
Closing this, new PR #8068

**Pull request closed without merging**
