### PR TITLE
Small fix for running using Invoke-Expression

### LINKED ISSUE #20512: ConfigureRemotingForAnsible.ps1 fails when called from github with Invoke-Expression
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ConfigureRemotingForAnsible.ps1

##### ANSIBLE VERSION

```
2.1.2
```

##### OS / ENVIRONMENT

Windows Server 2012
Windows Server 2016

##### SUMMARY
Run this in a powershell console 

```
Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
```

The error is:

*New-EventLog : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:124 char:47
     New-EventLog -LogName Application -Source $EventSource
                                                                              ~~~~~~~~~~~~
     CategoryInfo          : InvalidData: (:) [New-EventLog], ValidationMetadataException
     FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.NewEventLogCommand*

And points to the problem, $MyInvocation.MyCommand.Name is an empty string when called like this

```
$EventSource = $MyInvocation.MyCommand.Name
If ($EventSource -eq $Null)
{
    $EventSource = "Powershell CLI"
}
```

so the above could be easily changed to 

```
$EventSource = $MyInvocation.MyCommand.Name
If ([String]::IsNullOrEmpty($EventSource))
{
    $EventSource = "Powershell CLI"
} 
```

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ConfigureRemotingForAnsible.ps1

##### ANSIBLE VERSION

v2.3

##### SUMMARY

A small fix suggested by a user for running ConfigureRemotingForAnsible.ps1

This fixes #20512

### CODE REVIEW

**Comment by dagwieers** [comment]
@mattclay @trondhindenes @cchurch @mrcrilly @Cryptophobia @nitzmahone @dav1x ready_for_review

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
Apparently closing and re-opening doesn't trigger CI.

**Comment by mattclay** [comment]
@dagwieers It seems that Shippable is having trouble with CI for select users, preventing CI from triggering PRs. You're one of the impacted users. I've reported the issue to Shippable. However, until it's fixed, it looks like any PR you open will not have CI.

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
@dagwieers It appears that Shippable has resolved the issue blocking CI for your user.

**Comment by dagwieers** [comment]
@mattclay I thought it was a general issue at Shippable, hadn't noticed it was working for others.

**Comment by dagwieers** [comment]
@nitzmahone @gundalow @dav1x @jhawkesworth @jctanner Can we please get this one merged ?

This is a no-brainer.

**Pull request merged**
