### PR TITLE
opensuse image for travis tests

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

2.1.0, devel
##### SUMMARY

Run the test suite also on openSUSE leap 42.1

Before merging, someone from ansible/core needs to:
- build the docker image over at ansible/ansible
- correct the docker image used in run_tests (i.e. remove the `if` line (L14) that points to my dockerhub repo)

Future ToDos:
- mysql, postgresql: disabled for now, need some fixes to use the suse-specific start/... scripts, I would leave this for some future time or someone who can do this more easily than me

### CODE REVIEW

**Comment by robinro** [comment]
This is still work in progress, because not all tests pass yet.

**Comment by sivel** [comment]
I've marked as `needs_revision` since it is still a WIP and such.  Let us know once you are complete.

**Comment by sivel** [comment]
Also, just as a note, we will need to build and push the docker image, and then get the image name changed to use the "official" image.

**Comment by robinro** [comment]
@sivel switching the image path to ansible/ansible:opensuseleap is just removing one line in the diff
I'll let you know when the tests pass so you can build an 'official' image

**Comment by robinro** [comment]
this needs some other merges first, I'll keep track of the state in the first post

**Comment by gundalow** [comment]
Hi,
I'm updating the Docker images to speed up deb/rpm builds in https://github.com/ansible/ansible/pull/15692 once integrated it would be great if you could add the the relevant changes into this new OS image.

Give me a shout if you need a hand with any of this (gundalow on freenode).

**Comment by robinro** [comment]
Excluding the databases everything should be there now.

**Comment by robinro** [comment]
replaced by #15936

**Pull request closed without merging**
