### PR TITLE
add return_access_keys param to azure_rm_storageaccount_facts

### PR DESCRIPTION
**Pull request by PascalVA**
##### SUMMARY
I have added the param **return_access_keys** to **azure_rm_storageaccount_facts** similar to other azure modules _(postgres, redis, cosmosdb)_. I have also changed the method name **get_connectionstring** to **get_acocunt_keys** to be more descriptive of what it is actually doing. The function itself has also been updated to return a dict of key-value pairs instead of just a list.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
azure_rm_storageaccount_facts

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@yungezz @MyronFanQiu @zikalino

**Comment by Fred-sun** [comment]
@yungezz @zikalino review_need

**Comment by Fred-sun** [comment]
@PascalVA Please fix the CI fail when you're free! When you finish changed, I will push for review! Thanks a lot!

**Comment by Fred-sun** [comment]
@PascalVA Can you help rebase this PR to repair CI fail? when you finish change, I will push for review and merge! Thank you very much!

**Comment by Fred-sun** [comment]
@PascalVA Kindly ping!

**Comment by PascalVA** [comment]
@Fred-sun Sorry for the delay, I have rebased on devel and you should be able to merge now

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang ready_for_review!

**Comment by Fred-sun** [comment]
@PascalVA Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Pull request closed without merging**
