### PR TITLE
added support for icmp-blocks and icmp-block-inversion

### PR DESCRIPTION
**Pull request by badstreff**
##### SUMMARY
Adds support for the firewalld module to manage icmp-block and icmp-block-inversion settings.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 06b66a81d0) last updated 2018/09/16 18:04:54 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/afurbee/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/afurbee/Projects/ansible/lib/ansible
  executable location = /home/afurbee/Projects/ansible/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### ADDITIONAL INFORMATION
Below is a quick test playbook demonstrating the functionality. When using icmp-block-inversion the state must be disabled if you wish to actually disable the setting, it is not sufficient to only set the setting to false, this is consistent with the way the existing masquerade param works.
```paste below
---
- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: firewalld test 1
      firewalld:
        zone: public
        icmp_block_inversion: true
        permanent: true
        state: enabled
    - name: firewalld test 2
      firewalld:
        zone: public
        icmp_block_inversion: true
        state: enabled
    - name: firewalld test 3
      firewalld:
        zone: public
        icmp_block_inversion: false
        permanent: true
        state: disabled
    - name: firewalld test 4
      firewalld:
        zone: public
        icmp_block_inversion: false
        state: disabled
    - name: firewalld test 5
      firewalld:
        zone: public
        icmp_block: echo-request
        permanent: true
        state: enabled
    - name: firewalld test 6
      firewalld:
        zone: public
        icmp_block: echo-request
        permanent: true
        state: disabled
```

### CODE REVIEW

**Comment by badstreff** [comment]
any update on this? I see it was removed from 'needs_triage' but am unsure what that means? Just wanting to make there isn't something we are waiting on me for

**Comment by maxamillion** [comment]
@BadStreff sorry for the lag time on this, thank you for the PR!

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by badstreff** [comment]
@maxamillion No problem, thanks for taking the time to go over it! Also, howdy from SHSU ;)

**Comment by maxamillion** [comment]
@BadStreff howdy! :)

**Pull request merged**
