### PR TITLE
docker_container: make condition less specific

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This condition seems to cause problems with newest docker.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
This fixes the problem with docker tests on `devel` and `stable-2.7`.

**Comment by felixfontein** [comment]
Only unrelated tests seem to fail.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Only failures are in AWS and Windows which are unrelated.

**Comment by gundalow** [comment]
@felixfontein thank you for investigating and the quick fix!

**Comment by felixfontein** [comment]
2.7 backport in #48593

**Pull request merged**
