### PR TITLE
os_server apply security groups on instance creation

### LINKED ISSUE #56259: os_server security groups not working on creation
##### SUMMARY
When creating a OpenStack instance with security groups, security groups are added but it doesn't work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
/cloud/openstack/os_server.py

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /Users/josemgom/local/ansible/myproject/ansible.cfg
  configured module search path = [u'/Users/josemgom/local/ansible/myproject/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible-2.7.1-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE
Give the following

```
    - name: "Create Box {{ box_name }}"
      when: boxEnabled == "True" and type == "TEST"
      register: box
      os_server:
        meta: "{{ diskSchema }}"
        state: present
        name: "{{ box_name }}"
        flavor: "{{ flavor }}”
        image: corp:centos-7.4
        terminate_volume: yes
        boot_from_volume: yes
        api_timeout: 300
        security_groups: ["default", "ssh"]
        nics:
          - port-name: "{{ box_name }}_APP"
          - net-name: "{{ openstack_nfs_network }}"
        key_name: '{{ box_name | regex_replace("\." ,"-") }}'

```

##### EXPECTED RESULTS
OpenStack instance is created with the security groups and rules are applied correctly. I.e. With the security group ssh I should be able to connect using ssh.

##### ACTUAL RESULTS
OpenStack instance is created with the security groups and I can’t connect using ssh.

Workaround 1: Join OpenStack, remove the group and add it again.
Workaround 2: Create the instance without security groups and add it after creation calling again to os_server module.

### PR DESCRIPTION
**Pull request by acalm**
##### SUMMARY

Fixes #56259 
Also did some minor renaming of functions, added diff and minor re-org
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

os_server

### CODE REVIEW

**Review by jamescassell — COMMENTED** [review]
LGTM, though I haven't tested it

**Comment by acalm** [comment]
@josemgom would you mind testing if this works for you?

**Comment by josemgom** [comment]
> @josemgom and @gtema would you mind testing if this works for you?

Sure, I will test it and I will provide feedback as soon as possible.

**Comment by acalm** [comment]
@josemgom that's weird, I've tried it both openstacksdk 3.14.1, 3.18.0 and python 2, 3. It might be openstack, however this change solved my problems on Queens.
What version are you running of openstack and openstacksdk?
Also, can you double check that the pr was actually checked out? (I miss this from time to time)

**Comment by josemgom** [comment]
> @josemgom that's weird, I've tried it on both openstacksdk 3.14.1, 3.18.0 and python 2, 3. It might be openstack, however this change solved my problems on Queens.
> 
> What version are you running of openstack and openstacksdk?
> Also, can you double check that the pr was actually checked out? (I miss this from time to time)

Yes, it is weird. I checked and I am working with your branch which contains the fix.

More details about my environment:
Openstack Version: Pike
openstacksdk==0.24.0
python-openstackclient==3.14.0
ansible==2.9.0.dev0

I tried to create a server with the openstack cli providing both security groups and works fine.

**Comment by acalm** [comment]
I cannot reproduce the referenced issue any longer, this PR does contain some cleanups though so it might be an OK merge anyhow

**Comment by acalm** [comment]
closing this pr since I cannot reproduce the bug any longer, I.E the issue is most probably related to config/version in either openstack or the openstack python module(s). Will create a separate PR with suggested improvements from this pr

**Pull request closed without merging**
