### PR TITLE
Added RETURN information

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Just that.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by jpmens** [comment]
@ansibot if @dagwieers adds documentation to my stuff, you shipit without asking. #kthxbai ;-)

**Comment by jpmens** [comment]
Since it probably won't grok that, I'll do this again: shipit

**Comment by jpmens** [comment]
shipit

**Comment by dagwieers** [comment]
@jpmens Haha, and then Shippable fails :-)

**Comment by jpmens** [comment]
@dagwieers I saw it failed before I commented. ;-)

**Comment by dagwieers** [comment]
@jpmens So your shipit only works if there's no more additional commits. Since Shippable failed I amended my commit and your shipit lost all its value to ansibot...

bot_status

**Comment by jpmens** [comment]
shipit

**Pull request merged**
