### PR TITLE
show version brief does not work on iosxr virtual

### LINKED ISSUE #37294: iosxr facts - incompatible show version command
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- iosxr_facts.py
- iosxr.py

##### ANSIBLE VERSION

```
ansible 2.4.+ 
ansible 2.5.0rc2

```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

show command for gathering facts in IOS-XR are wrong set:
ios-xr will report a error receiving "show version brief"
correct command should be "show version"

Following packages should be corrected:
/usr/local/lib/python2.7/dist-packages/ansible/plugins/cliconf/iosxr.py

class Cliconf(CliconfBase):

    def get_device_info(self):
        device_info = {}

        device_info['network_os'] = 'iosxr'
        reply = self.get(b'show version brief')  <- wrong
        reply = self.get(b'show version')  <- correct

and accordingly:
/usr/local/lib/python2.7/dist-packages/ansible/modules/network/iosxr_1/iosxr_facts.py

class Default(FactsBase):

    def commands(self):
        return(['show version brief'])  <- wrong
        return(['show version'])  <- correct

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by gdpak**
fixes #37294 
show version brief does not work on virtual iosxr. This breaks all iosxr module when tested against virtual iosxr as it is used in connection plugin time to collect device info.
'show version' is superset of 'show version brief' but it's output can grow linearly in case number of package on system installed increase. On testing slow connection, command execution time was increased to >2 time compared to 'show version brief'.
So trimming o/p on device using unix head utility gives comparable performance as of 'show version brief' . With this fix collecting all facts took ~14 sec compared to 13.5 seconds in case of 'brief'

'brief' is actually first 18 lines of 'show version' . Increased it to 20 lines just in case cisco further adds some changes to this command.

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/58405/3/tests

Integration test failures are unrelated.

**Comment by gdpak** [comment]
Ran manually iosxr_facts and it passes 

TASK [iosxr_facts : debug] *************************************************************************************************************************************
ok: [iosxr02] => {
    "msg": "END cli/not_hardware_facts.yaml on connection=local"
}

PLAY RECAP *****************************************************************************************************************************************************
iosxr02                    : ok=32   changed=0    unreachable=0    failed=0

**Review by ganeshrn — APPROVED** [review]
lgtm

**Comment by mirochon** [comment]
just to let you know that show version brief is not working not just on virtual but any IOSXR device starting with 6.3.2. Hope this fix is in next release of ansible.

**Comment by Gaurav-Pande** [comment]
This issue is still active in iosxr virtual 6.1.2, due to which no isoxr-config modules can be run successfully in the latest ansible 2.5.0.

**Comment by gdpak** [comment]
This has been back ported to stable-2.5 and will be available from 2.5.3 onwards

**Pull request merged**
