### PR TITLE
Autodetect more than github repository, using a more generic heuristic (...

### PR DESCRIPTION
**Pull request by mscherer**
... see #8937 )

### CODE REVIEW

**Comment by willthames** [comment]
I'm really not a fan of the magic URLs as it is (I originally used git and hg autodetection to work out the type of the repo, but @mpdehaan said that was too magic - I think this is too much magic - and I would have said so about the github.com special case too).

If you are going to do this, my recommendation is to make it DRY and have a function called `guess_scm_from_url` or similar and use it in all code paths that rely on this detection.

**Comment by mscherer** [comment]
Yeah, I was also not fan of having duplicated code path, especially since it took me 5 minutes to see why it was not working as intended by doing half of the modification. I will try to provides a better PR, (with tests for example) if that's ok on the feature point of view.

**Comment by willthames** [comment]
Inferring that repos that end in `.git` are git repos seems reasonable to me. 

Definitely room for improvement in abstracting common code from `role_spec_parse` and `role_yaml_parse`, especially as they're both accumulating similar magic. 

Whether this gets in is not a decision I can make - it is often worth discussing new features in ansible-devel mailing list to avoid spending too much effort on something that isn't wanted.

**Comment by amenonsen** [comment]
@mscherer are updates here following the discussing with @willthames?

**Comment by mscherer** [comment]
Not really. I guess i can close this PR since I totally forgot the context, and the original bug is closed.

**Pull request closed without merging**
