### PR TITLE
Allow to run tests for f5.bigip_monitor_tcp_half_open when no f5-sdk …

### PR DESCRIPTION
**Pull request by fredericlepied**
…is present

Fixes: bug #27034

Introduced by https://github.com/ansible/ansible/commit/278fa552f80f8252a59ff52139d25b4cf088ec18

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

modules/network/f5/bigip_monitor_tcp_half_open.py

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fred/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fred/external/ansible/.tox/py27/lib/python2.7/site-packages/ansible
  executable location = /home/fred/external/ansible/.tox/py27/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by caphrim007** [comment]
@fredericlepied thanks for finding that

This class is technically included in the module_utils/f5_utils.py, can we instead just try to include that in the test file instead of re-def'ing the class here?

for example, immediately after this line

https://github.com/ansible/ansible/blob/devel/test/units/modules/network/f5/test_bigip_monitor_tcp_half_open.py#L47

add this

`from ansible.module_utils.f5_utils import iControlUnexpectedHTTPError`

**Comment by fredericlepied** [comment]
@caphrim007 ok no problem to do it this way but no code will be tested at all. Submitting the new way.

**Comment by caphrim007** [comment]
@fredericlepied that's ok, if any part of the F5 dependencies is missing then I'd prefer to just skip everything because it would require a lot of skipifs otherwise

**Comment by caphrim007** [comment]
I'll fix up the other tests if you're nearing your end of day

**Comment by fredericlepied** [comment]
@caphrim007 np updating the other tests too.

**Comment by caphrim007** [comment]
shipit

**Pull request merged**
