### PR TITLE
ansible supports ZTE's  Operating System os-release

### PR DESCRIPTION
**Pull request by Sasocai**
Signed-off-by: CaiJiYan <cai.jiyan@zte.com.cn>

 SUMMARY
adds support for NewStart

 ISSUE TYPE
 Feature Pull Request

 COMPONENT NAME
  lib/ansible/module_utils/facts/system/distribution.py

### CODE REVIEW

**Review by gundalow — COMMENTED** [review]
Hi,
Thanks for adding support for ZTE to Ansibe's facts systems.

We have some unit tests for this in `test/units/module_utils/test_distribution_version.py`

You can run them locally by running the following command from your checkout
`bin/ansible-test units -v --docker default test/units/module_utils/test_distribution_version.py`

**Review by samdoran — CHANGES_REQUESTED** [review]
We also need an entry in `OS_FAMILY_MAP` in the `Distribution` class. Please add unit tests with example data from `/etc/cgsl-release`. Look at `test/units/module_utils/test_distribution_version.py` for examples. You can run `hacking/tests/gen_distribution_version_testcase.py` to generate test data.

**Comment by Sasocai** [comment]
test/units/module_utils/test_distribution_version.py add 

TESTSETS = [
    {
        "platform.dist": [
            "",
            "",
            ""
        ],
        "input": {
            "/etc/cgsl-release": "NewStart Carrier Grade Server Linux Core release 5.05\n",
            "/etc/os-release": (
                "NAME=\"NewStart CGS Linux Core\"\nVERSION=\"5.05\"\nID=\"ZTEOS\"\nID_LIKE=\"centos rhel fedora\"\nVERSION_ID=\"5.05\"\n"
                "PRETTY_NAME=\"NewStart Carrier Grade Server Linux Core 5.05\"\nANSI_COLOR=\"0;31\"\nCPE_NAME=\"cpe:/o:centos:centos:7\"\n"
                "HOME_URL=\"https://www.gd-linux.com/\"\nBUG_REPORT_URL=\"https://www.gd-linux.com/\""
            ),
            "/etc/system-release": "NewStart Carrier Grade Server Linux Core release 5.05\n"
        },
        "name": "NewStart 5.05",
        "result": {
            "distribution_release": "Carrier Grade Server Linux Core",
            "distribution": "NewStart",
            "distribution_major_version": "5",
            "os_family": "RedHat",
            "distribution_version": "5.05",
        }
    },
gen_distribution_version_testcase.py add
filelist = [
    '/etc/cgsl-release',

run  gen_distribution_version_testcase.py
[root@localhost tests]# python gen_distribution_version_testcase.py
{
    "platform.dist": [
        "zteos",
        "5.05",
        ""
    ],
    "input": {
        "/etc/os-release": "NAME=\"NewStart CGS Linux Core\"\nVERSION=\"5.05\"\nID=\"ZTEOS\"\nID_LIKE=\"centos rhel fedora\"\nVERSION_ID=\"5.05\"\nPRETTY_NAME=\"NewStart Carrier Grade Server Linux Core 5.05\"\nANSI_COLOR=\"0;31\"\nCPE_NAME=\"cpe:/o:centos:centos:7\"\nHOME_URL=\"http://www.gd-linux.com/\"\nBUG_REPORT_URL=\"http://www.gd-linux.com/\"\n",
        "/etc/cgsl-release": "NewStart Carrier Grade Server Linux Core release 5.05 \n",
        "/etc/system-release": "NewStart Carrier Grade Server Linux Core release 5.05 \n"
    },
    "name": "NewStart 5.05",
    "result": {
        "distribution_release": "Carrier Grade Server Linux Core",
        "distribution": "NewStart",
        "distribution_major_version": "5",
        "os_family": "RedHat",
        "distribution_version": "5.05"
    }
}

**Comment by Akasurde** [comment]
@Sasocai Are you still working on this, let us know ? Thanks, needs_info

**Pull request closed without merging**
