### PR TITLE
[inventory/azurerm] Add precedence when reading settings

### PR DESCRIPTION
**Pull request by thiagocaiubi**
##### SUMMARY

First load all settings from azure_rm.ini file if it exists then load all settings from environment variables. The latest overrides the first.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
contrib/inventory/azure_rm.py

### CODE REVIEW

**Comment by yuwzho** [comment]
@nitzmahone what's the latest story of the inventory plugin? Still need to modify the `azure_rm`?

**Comment by Fred-sun** [comment]
Hi @nitzmahone This PR has open one year, Does this need to modify the azure_rm as @yuwzho said? if you have other view, Please update your point or next step plan. Thanks!

**Comment by yungezz** [comment]
duplicate with PR https://github.com/ansible/ansible/pull/20365.

**Comment by Fred-sun** [comment]
@yungezz if this PR duplicate with other PR, could we can close this PR?

**Comment by Fred-sun** [comment]
@nitzmahone Thanks for your contribution, Could you help update the comments? Thanks !

**Comment by Fred-sun** [comment]
@thiagocaiubi Thanks for your contribution, Could you help confirm the PR ready for review or not?

**Comment by Fred-sun** [comment]
@thiagocaiubi Thanks for your contribution, Could you help confirm the PR ready for review or not?

**Comment by Fred-sun** [comment]
@thiagocaiubi Thanks for your contribution, Could you help confirm the PR ready for review or not?

**Comment by Fred-sun** [comment]
@thiagocaiubi Thanks for your contribution, Could you help confirm the PR ready for review or not?

**Pull request closed without merging**
