### PR TITLE
Added module to handle rabbit policies [1]

### PR DESCRIPTION
**Pull request by retr0h**
Used quite a bit of the existing rabbit modules provied by @chrishoffman.

[1] https://www.rabbitmq.com/parameters.html

### CODE REVIEW

**Comment by chrishoffman** [comment]
This looks good, thanks for doing this.  This looks good to me.  I haven't specifically tested it, maybe in a few days.

**Comment by mpdehaan** [comment]
Rabbit policies:
- rabbits like vegetables
- be careful not to breed too many rabbits
- it is usually ok to hug them and pet them and call them George
- do not pick rabbits up by their ears

**Comment by mpdehaan** [comment]
params should take type=dict such that you can do this:

 rabbitmq_policy:
    tags: 
        asdf: 1234
        ha: foo

and even

  rabbitmq_policy:  tags="asdf=1234 ha=foo"

Which is way easier than quoting JSON.

This means you can remove some of the JSON code from the tag handling as well.

**Comment by mpdehaan** [comment]
version_added should be set to 1.5

**Comment by jctanner** [comment]
@retr0h thank you!

**Pull request merged**
