### PR TITLE
Refactor get_snapshot API

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix refactors get_snapshots_by_name_recursively API for vmware_guest
and vmware_guest_snapshot modules.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/vmware.py
lib/ansible/modules/cloud/vmware/vmware_guest.py
lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by mattclay** [comment]
CI failure due to a `maximum recursion depth exceeded` error in pylint on Python 3.6. I'll restart the CI run to see if it will pass on the second run.

**Comment by mattclay** [comment]
CI failed again with `maximum recursion depth exceeded`. I've restarted it again to see if the newer test container resolves the issue.

**Comment by mattclay** [comment]
CI is still choking on pylint. I'm investigating.

**Comment by mattclay** [comment]
I've reproduced the `pylint` error locally. We should be able to work around it with an alternative implementation for `get_snapshots_by_name_recursively` such as:

```python
def get_snapshots_by_name_recursively(snapshots, snapshot_name):
    snap_obj = []
    remaining_snapshots = list(snapshots)
    while remaining_snapshots:
        snapshot = remaining_snapshots.pop()
        if snapshot.name == snapshot_name:
            snap_obj.append(snapshot)
        else:
            remaining_snapshots += snapshot.childSnapshotList
    return snap_obj
```

NOTE: This does change the order in which snapshots are returned. I don't know if the order is important or not.

**Comment by mattclay** [comment]
@Akasurde Is the workaround I described acceptable?

**Comment by Akasurde** [comment]
I will close this as I am working on more refactoring of same module.

**Pull request closed without merging**
