### PR TITLE
Added the ability to assign networks by name in the Rackspace module

### PR DESCRIPTION
**Pull request by phillipuniverse**
This is a bit different than the rest of the Rackspace module where everything had to go by ID (like flavors and images). I personally find that a bit pedantic because I always have to go hunting for the IDs and in some cases view page sources (although I suppose I could just leverage the API). Instead, I simply allow networks to be referenced by name with special, reserved names for 'public' and 'private'.

It's pretty trivial to change to reference these by id instead so just let me know if I should update this. I also wasn't sure how to do tests for this, but I tested locally and it works ok on my end.

### CODE REVIEW

**Comment by mpdehaan** [comment]
The deep list comprehension will make debugging confusing if there is a traceback.

Can you please unroll this and assign using a basic for loop if need be?

results = []

and so on?

**Comment by phillipuniverse** [comment]
I do Java development 9-5, so I was just enjoying the stay in Python-land. It's way more fun over here!! :)

Unrolled, all better?

**Comment by sivel** [comment]
@phillipuniverse I am in the middle of a huge refactor of the `rax` module (See #4577)

Additionally, we also have a pull request for `rax_network` in the pipeline now (See #4603).

I'll make sure to implement this functionality in the refactor, which will also have to take into account the output provided by the `rax_network` module, but I don't think I will be able to merge your commit in due to the huge changes that have already been made.

**Comment by phillipuniverse** [comment]
@sivel awesome, thanks for the update. I added this mainly because I had a specific itch I needed to scratch, but happy that more expansive work is going into this. Hopefully by the time this all said and done it will be on par with the AWS modules, especially since the Rackspace APIs are as good as AWS.

I'll go ahead and close this pull request and will follow the other referenced pulls closely. Will be happy to test out functionality as it gets completed!

**Pull request closed without merging**
