### PR TITLE
Support nested JSON decoding in AnsibleJSONDecoder

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Support nested JSON decoding in AnsibleJSONDecoder

cc @AlanCoding 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/parsing/ajson.py

##### ANSIBLE VERSION

```paste below
2.8
2.7
2.6
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by bcoca — APPROVED** [review]

**Comment by AlanCoding** [comment]
I know it's not in the Ansible issue queue, but this is to address https://github.com/ansible/awx/issues/2226

**Comment by bcoca** [comment]
should we add a test to prevent regression?

**Comment by AlanCoding** [comment]
Tested with

```
ansible-playbook debugging/hostvars_print.yml -i scripts/vault/bug2226/awx.py --ask-vault-pass
```

And it decrypts "MyPassword" in all 3 use examples

 - top-level value
 - nested in a dict
 - nested in a list

**Review by AlanCoding — APPROVED** [review]

**Comment by sivel** [comment]
> should we add a test to prevent regression?

It wouldn't be a bad idea, but I may not have time to add tests until next week.

**Comment by bcoca** [comment]
@sivel @AlanCoding we can merge this now and add tests later, specially since you seem to have test cases already.

**Comment by sivel** [comment]
@bcoca I've pushed tests using the reproducer data structure provided by @AlanCoding

**Pull request merged**
