### PR TITLE
changed capitals vSphere

### PR DESCRIPTION
**Pull request by servisan**
##### SUMMARY

Changed VSphere to vSphere in comment

### CODE REVIEW

**Review by goneri — CHANGES_REQUESTED** [review]
Thanks for cleaning up the code comments. Could you also add an entry for vSphere in the nomenclature section here:

https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/platforms/vmware_guidelines.rst#nomenclature

**Comment by goneri** [comment]
I see the same typography in:

- lib/ansible/modules/cloud/vmware/vsphere_file.py
- contrib/inventory/vmware_inventory.py

**Comment by goneri** [comment]
Please, merge https://github.com/ansible/ansible/pull/62976 https://github.com/ansible/ansible/pull/62977 and https://github.com/ansible/ansible/pull/62978 in this PR.

**Review by dagwieers — APPROVED** [review]
LGTM

**Pull request merged**
