### PR TITLE
Add hostname_variable to ec2 inventory script

### PR DESCRIPTION
**Pull request by hkariti**
Use it to override the inventory name set for ec2 hosts with an ec2 variable.

### CODE REVIEW

**Comment by willthames** [comment]
Looks good to me.

I don't think there's any reason why the same approach taken for `hostname_variable` couldn't also be applied to `destination_variable` and `vpc_destination_variable`, so might be worth making a method out of the tag extraction and applying to all three.

**Comment by hkariti** [comment]
Not sure, because these options should be addressable values

**Comment by willthames** [comment]
If the tag_Name happens to be in DNS, then it will be addressable. If I understand your meaning correctly.

**Comment by mpdehaan** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

~  
~  
~

**Comment by hkariti** [comment]
Rebased. Also added the patch to add_rds_instance, but I don't have rds instances to didn't test

**Comment by micxer** [comment]
Is there any progress in merging this? I would have good use for this feature as well, as I have an upcoming use case, where I need to set variables based on the host, it would be nice to be able to use the name of an instance as hostname in Ansible and not the IP address. I fiddled with `destination_variable` and `vpc_destination_variable` but didn't get there. AFAIK these are only intended to let Ansible find out how to connect the instances.

**Comment by bennojoy** [comment]
@micxer  this capabilty has been added via 9825 , are you testing with latest devel ?

**Comment by hkariti** [comment]
@bennojoy #9825 requires that the tag be also the value that's given to ssh. So, for example you have to have the hostname in /etc/hosts, or have the full dns resolvable name in the aws tag.

**Comment by micxer** [comment]
@bennojoy just try it and it works. However that's not, what I tried to achieve. I want ansible to connect to the machine using the IP oder public DNS or whatever that works, but the ansible_hostname should match a given tag, i.e. the Name tag.

So I can have `server1` and `server2` for file names in `host_vars` and not the IP addresses and run `ansible --limit server1`.

**Comment by amenonsen** [comment]
@bennojoy did you get a chance to look at this again in light of the comments above?

**Comment by davidvasandani** [comment]
+1. Would love to have this.

**Comment by amenonsen** [comment]
ping @bennojoy

**Comment by magnetik** [comment]
Same use case as others. With current implementation we are using the tag name as destination variable, and running a custom script to populate the ssh config with the right "fake" hostname to the real DNS hostname

**Comment by amenonsen** [comment]
@hkariti I read your patch, and it seems simple enough, and several people have said they would find it useful. Do you feel like rebasing once more, by any chance?

**Comment by hkariti** [comment]
Rebased. I noticed that there's also support for elasticcache clusters in the inventory script. I don't know how these work, so I didn't try to add support for them (didn't know if that even made sense).

**Comment by amenonsen** [comment]
Looks good, thanks. Merged.

**Pull request merged**
