### PR TITLE
Move pkg needed on ubuntu 12.04 install from note to instructions

### PR DESCRIPTION
**Pull request by jaimegago**

### CODE REVIEW

**Comment by jaimegago** [comment]
FWIW I've needed that package when installing on an ubuntu precise 12.04 vagrant box (ubuntu/precise64 on vagrant cloud) 

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
```

**Comment by mpdehaan** [comment]
Notice this installs both, is "software-properties-common" still a package on the older boxes?

**Comment by jaimegago** [comment]
yup it is

```
vagrant@vagrant-ubuntu-precise-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise


vagrant@vagrant-ubuntu-precise-64:~$ sudo apt-get install software-properties-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libxfixes3 libxcomposite1 xfonts-encodings x11-xkb-utils xserver-xorg-core xserver-common libgl1-mesa-dri xfonts-utils libxfont1 xfonts-base libfontenc1 libxdamage1
  libxrandr2 libxkbfile1 libllvm3.0
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  software-properties-common
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 8,450 B of archives.
After this operation, 132 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ precise-updates/main software-properties-common all 0.82.7.7 [8,450 B]
Fetched 8,450 B in 0s (23.0 kB/s)
Selecting previously unselected package software-properties-common.
(Reading database ... 85629 files and directories currently installed.)
```

**Comment by jaimegago** [comment]
here are the options I can think of:
1)change the note to "apt-add-repository lives in package software-properties-common or python-software-properties depending on the version" 
2)have an "if then" in the doc with the commands required to find out in which package apt-add-repository lives
3)we just leave both (as in this PR) since both packages are available on both ubuntu 12 and 14
4)have the ppa repo done install manually

After some reflexion I think I need to change this PR to 1 or 2, I don't think it's acceptable to have folks install unnecessary packages. We shouldn't though remove this though I'm quite confident there are plenty out there stuck on ubuntu 12.

**Pull request merged**
