### PR TITLE
Try to load action plugin from the same collection as the module

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

~~I feel like I've sugggested this before.~~

This now specifically targets network action plugins and does so without modifying the collections list

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

task_executor

### CODE REVIEW

**Comment by pabelanger** [comment]
Okay, this looks to have fix our jobs running on ansible.netcommon.  We likely want some sort of test here too,  and cores input. Thanks for working on it.

**Review by ganeshrn — CHANGES_REQUESTED** [review]
Updating the collection list might cause some unwanted side effects. Instead, why not update the action plugin name (module_prefix) to FQ action plugin name (with dot notation) and check if it is present in the collection if not fallback to action plugin name without dot notation.

**Comment by Qalthos** [comment]
> why not update the action plugin name (module_prefix) to FQ action plugin name (with dot notation) and check if it is present in the collection if not fallback to action plugin name without dot notation.

I knew there was something I was missing. PR is updated, and looks far less questionable as a result. Thanks!

**Comment by bcoca** [comment]
cc @nitzmahone  as he is probably best suited to verify this is the best way to do this

**Review by nitzmahone — APPROVED** [review]
There are several circumstances where this won't work properly (eg module subdirs, dependent collections), but if it gets things working for networking for now, I guess it's fine... This *really* needs to be rethought long-term in order to be properly extensible without creating config-dependent content. I have several ideas, but they're not going to happen for 2.10.

**Review by ganeshrn — APPROVED** [review]
Thanks!

**Comment by pabelanger** [comment]
check experimental

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
check experimental

**Comment by pabelanger** [comment]
check experimental

**Pull request merged**
