### PR TITLE
New module aireos_command

### PR DESCRIPTION
**Pull request by jmighion**
##### SUMMARY

New module `aireos_command` for issuing commands to Cisco WLC network devices.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

aireos_command

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (ciscowlc_command 151050602a) last updated 2017/07/18 10:10:01 (GMT -700)
  config file = /Users/james/.ansible.cfg
  configured module search path = [u'/Users/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/james/Documents/work/git/ansible/lib/ansible
  executable location = /Users/james/Documents/work/git/ansible/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### CODE REVIEW

**Comment by jmighion** [comment]
Devel broke. Retrying.

**Comment by bcoca** [comment]
Just mild bikeshedding, the module might be better named `cisco_wlc_command`.

**Comment by jmighion** [comment]
Agreed. Changing to `cisco_wlc_command`.

**Comment by dagwieers** [comment]
Well, my modules used to be called **cisco_imc_rest** and **cisco_aci_rest**, but @privateip told me to simply call it **imc_rest** and **aci_rest**. I guess this is similar for other Cisco families: **asa_command**, **ios_command**, **ioxsr_command** , **nxos_command**, etc...

**Comment by bcoca** [comment]
cc @privateip, @rcarrillocruz

**Comment by jmighion** [comment]
Should I just drop the 'cisco' part of the name to leave the module name at `wlc_command` or change it to the OS name, which I think is AireOS so `aire_command`?

**Comment by dagwieers** [comment]
Not nitpicking here, but looking at the existing list, I see:
- aos
- dellos6, dellos9, dellos10
- eos
- ios
- junos
- nxos
- panos
- sros
- vyos

So maybe `aireos_` is a better name than `aire_` ?

**Comment by jmighion** [comment]
Doh. Good point. Will change to `aireos_command` later today.

**Comment by jmighion** [comment]
Shippable failed building out an env. Closing and reopening to restart shippable.

**Review by ganeshrn — APPROVED** [review]

**Comment by jmighion** [comment]
Shippable failed building out an env. Closing and reopening to restart shippable.

**Comment by ganeshrn** [comment]
@jmighion Merged. Thank you!

**Pull request merged**
