### PR TITLE
Accept interfaces without address family or method

### LINKED ISSUE #30768: interfaces_file: need more than 1 value to unpack
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

interfaces_file
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/bwatson/Projects/[removed]/ansible.cfg
  configured module search path = [u'/Users/bwatson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bwatson/Projects/[removed]/venv/lib/python2.7/site-packages/ansible
  executable location = /Users/bwatson/Projects/[removed]/venv/bin/ansible
  python version = 2.7.12 (default, Jun 29 2016, 14:05:02) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### OS / ENVIRONMENT

Host: OS X Python 2.7.12
Target: Cumulus Linux 3.1.1
##### SUMMARY

Using the interfaces_file task causes an error: ValueError: need more than 1 value to unpack
##### STEPS TO REPRODUCE

Install ansible 2.4.0, run the example task shown in interfaces_file documentation.

```yaml
---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - interfaces_file:
        dest: /etc/network/interfaces
        iface: eth1
        option: mtu
        value: 8000
        backup: yes
        state: present
      register: eth1_cfg
```

##### EXPECTED RESULTS

I would expect the mtu for eth1 to be changed to 8000.
##### ACTUAL RESULTS

An error is raised and the task fails. (This happens for any option. I tested multiple)

```
$ ansible-playbook interfaces_test.yml -i 172.20.116.11, -u admin -vv
ansible-playbook 2.4.0.0
  config file = /Users/bwatson/Projects/[removed]/ansible.cfg
  configured module search path = [u'/Users/bwatson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bwatson/Projects/[removed]/venv/lib/python2.7/site-packages/ansible
  executable location = /Users/bwatson/Projects/[removed]/venv/bin/ansible-playbook
  python version = 2.7.12 (default, Jun 29 2016, 14:05:02) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Using /Users/bwatson/Projects/[removed]/ansible.cfg as config file

PLAYBOOK: interfaces_test.yml ***************************************************************************************************
1 plays in interfaces_test.yml

PLAY [all] **********************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************
ok: [172.20.116.11]
META: ran handlers

TASK [interfaces_file] **********************************************************************************************************
task path: /Users/bwatson/Projects/[removed]/interfaces_test.yml:17
fatal: [172.20.116.11]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 172.20.116.11 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_GxJ8k1/ansible_module_interfaces_file.py\", line 385, in <module>\r\n    main()\r\n  File \"/tmp/ansible_GxJ8k1/ansible_module_interfaces_file.py\", line 366, in main\r\n    lines, ifaces = read_interfaces_file(module, dest)\r\n  File \"/tmp/ansible_GxJ8k1/ansible_module_interfaces_file.py\", line 177, in read_interfaces_file\r\n    return read_interfaces_lines(module, f)\r\n  File \"/tmp/ansible_GxJ8k1/ansible_module_interfaces_file.py\", line 211, in read_interfaces_lines\r\n    iface_name, address_family_name, method_name = words[1:4]\r\nValueError: need more than 1 value to unpack\r\n", "msg": "MODULE FAILURE", "rc": 0}

PLAY RECAP **********************************************************************************************************************
172.20.116.11              : ok=1    changed=0    unreachable=0    failed=1
```

### PR DESCRIPTION
**Pull request by bobbywatson3**
##### SUMMARY

Interfaces do not require address family or method to be set. Without this patch, this module cannot parse inventory files that don't have the address family or method set.
fixes #30768 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
interfaces_file

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
```

##### ADDITIONAL INFORMATION

Example interfaces file that triggers bug:
```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto br0
iface br0
```

Error seen before change
```
TASK [Add interface option] ************************************************************************
fatal: [172.x.x.x]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.x.x.x closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_vhT1bm/ansible_module_interfaces_file.py\", line 385, in <module>\r\n    main()\r\n  File \"/tmp/ansible_vhT1bm/ansible_module_interfaces_file.py\", line 366, in main\r\n    lines, ifaces = read_interfaces_file(module, dest)\r\n  File \"/tmp/ansible_vhT1bm/ansible_module_interfaces_file.py\", line 177, in read_interfaces_file\r\n    return read_interfaces_lines(module, f)\r\n  File \"/tmp/ansible_vhT1bm/ansible_module_interfaces_file.py\", line 211, in read_interfaces_lines\r\n    iface_name, address_family_name, method_name = words[1:4]\r\nValueError: need more than 1 value to unpack\r\n", "msg": "MODULE FAILURE", "rc": 0}
```
After change:
```
TASK [Add interface option] ************************************************************************
ok: [172.x.x.x]
```

### CODE REVIEW

**Comment by hryamzik** [comment]
Awesome, looks good for me. I'd also like to see tests for this case but that's not a show stopper.
shipit

**Comment by bobbywatson3** [comment]
Is this waiting on anything to be merged?

**Comment by hryamzik** [comment]
CC @gundalow

**Comment by gundalow** [comment]
Waiting for Shippable to run (currently `stale_ci`) then I'll merge & cherry-pick into `stable-2.5`

**Comment by hryamzik** [comment]
Thanks man!

**Comment by gundalow** [comment]
Merged into `devel` and cherry picked into `stable-2.5`
https://github.com/ansible/ansible/commit/8e7b25025d4a1611c241d80b3af9896e162909b6

**Pull request merged**
