### PR TITLE
ec2_group add rule description fix

### LINKED ISSUE #47904: ec2_group ruleset applies rules improperly
##### SUMMARY
ec2_group changes has some condition where it encounters an issue comparing rule sets, recreating the rules (successfully), and says ok, but *fails* to properly recreate the ruleset as expected.

In our case, we have the plays in the attached gists -- if you run group1, followed by group2 (in our case), after group2, it will say it changed, and it does... but it does *not* apply *all* of the changes... which can leave you in a VERY bad / precarious state.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = None
  configured module search path = ['/home/marc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/marc/.local/lib/python3.7/site-packages/ansible
  executable location = /home/marc/.local/bin/ansible
  python version = 3.7.0 (default, Aug 30 2018, 14:32:33) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/marc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(/home/marc/projects/ansible/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/marc/projects/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/marc/projects/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/marc/projects/ansible/ansible.cfg) = -o ForwardAgent=yes -o StrictHostKeyChecking=no
ANSIBLE_SSH_RETRIES(/home/marc/projects/ansible/ansible.cfg) = 2
DEFAULT_CALLBACK_WHITELIST(/home/marc/projects/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/marc/projects/ansible/ansible.cfg) = 25
DEFAULT_LOG_PATH(/home/marc/projects/ansible/ansible.cfg) = /home/marc/projects/ansible/log/ansible.log
DEFAULT_ROLES_PATH(/home/marc/projects/ansible/ansible.cfg) = ['/home/marc/projects/ansible/roles']
DEFAULT_TRANSPORT(/home/marc/projects/ansible/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(/home/marc/projects/ansible/ansible.cfg) = /home/marc/sekrits
INVENTORY_ENABLED(/home/marc/projects/ansible/ansible.cfg) = ['aws_ec2', 'host_list', 'script', 'yaml', 'ini']
RETRY_FILES_ENABLED(/home/marc/projects/ansible/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/marc/projects/ansible/ansible.cfg) = /home/marc/projects/ansible/retries
```

##### OS / ENVIRONMENT

Environment:  AWS EC2 Security Groups

##### STEPS TO REPRODUCE
https://gist.github.com/Daemoen/1e6e79b1676ed22f27327e790ec05e69

##### EXPECTED RESULTS
ec2 group applies any differences without breaking

##### ACTUAL RESULTS
Play requires you run it 2x to get to the consistent state.  The first execution leaves you in an *incomplete* state, the second execution completes the state.

---
I have some screenshots and even verbose logs, but of course, because this is ec2, I cannot post them publically.  Ping me in channel or on here for more info as needed.

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY

ec2_group should not remove security group rules that
have their rule descriptions updated.

Update descriptions first, then do the comparison of whether
or not groups should be removed.

Fixes #47904

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 96a20e0780) last updated 2018/11/03 10:51:34 (GMT +1000)
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/will/src/ansible/lib/ansible
  executable location = /Users/will/src/ansible/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:47:18) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

##### ADDITIONAL INFORMATION
Should be backported to 2.6 and 2.7

### CODE REVIEW

**Comment by willthames** [comment]
This might not be the most elegant fix but it's the simplest fix I could think of to update the descriptions and then reset the group information to know what rules need adding or purging.

**Comment by Daemoen** [comment]
Have just applied the patch to our instance, we should know how it operates in the next few executions.  Will follow up as we have more feedback.

**Comment by Daemoen** [comment]
Have been running this in our environment for several days now, and it seems to be working ok.

**Comment by Daemoen** [comment]
I moved to the other fix about a week and a half ago.

**Comment by jborean93** [comment]
Looks like https://github.com/ansible/ansible/pull/48443 is meant to fix this issue but with a smaller changeset.

**Comment by jborean93** [comment]
@willthames I believe this is no longer needed now that 48443 has been merged

**Comment by s-hertel** [comment]
Closing as per above.

**Pull request closed without merging**
