### PR TITLE
Added merge_dicts Jinja2 filter

### PR DESCRIPTION
**Pull request by AndreiPashkin**
Added a new simple filter for merging dicts manually and not in-place.
Ther was [the discussion on mailing list](https://groups.google.com/forum/#!msg/ansible-project/XS1FNBKVUCw/giQwl8QMw_QJ).

ps.
Should I have to add the docs section?

### CODE REVIEW

**Comment by jirutka** [comment]
+1

**Comment by jimi-c** [comment]
Yes, this also needs to be added to the docs. Be sure to include the version added information (see other entries there for examples). Thanks!

**Comment by AndreiPashkin** [comment]
How can I know in which version this feature will be released?

**Comment by sivel** [comment]
Assume for the time being that it is 1.7.  If it doesn't make it into 1.7 you will just need to bump it at a later date.

**Comment by jimi-c** [comment]
Or we will fix it when we merge it in.

**Comment by AndreiPashkin** [comment]
I've added 1.7

**Comment by darkk** [comment]
Is the merge intentionally shallow?

`hash_behaviour=merge` produced deep merge, so [POLA](http://en.wikipedia.org/wiki/Principle_of_least_astonishment) implies that filter `merge_dicts` should provide deep merge too instead of shallow one.

Actually, I've already implemented `merge_hash` filter, so I wonder what is the correct way to contribute it:
- create another pull request with merge_dict filter
- rename my `merge_hash` to `merge_deep`, but it leads to two different merge filters in ansible that may be confusing

**Comment by jirutka** [comment]
@darkk The best solution would be IMHO merge these two filters and use a parameter to choose between deep (default), or shallow merge. Maybe something like `foo | merge_hash(deep=false)` for shallow merge.

**Pull request closed without merging**
