### PR TITLE
Temporary fix for cryptography issues.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Temporary fix for cryptography issues.

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

ansible / ansible-test

### CODE REVIEW

**Comment by jbhasemeier** [comment]
how do i get this ansible package? seems like pypi is behind?

**Comment by mattclay** [comment]
@jbhasemeier `ansible-base` pre-release 2.10.6rc1 is available on PyPI with this change. However, this fix is only for `ansible-test`. If you're experiencing issues with using Ansible itself, you will need to resolve the issue in the environment in which you are installing Ansible.

**Comment by sshnaidm** [comment]
@mattclay can it be ported to 2.9 as well?

**Comment by mattclay** [comment]
@sshnaidm Here's a fix for stable-2.9: https://github.com/ansible/ansible/pull/73618

**Pull request merged**
