### PR TITLE
Add overwrite option to include_vars action plugin

### PR DESCRIPTION
**Pull request by pfink**
##### SUMMARY
The additional option `overwrite` allows users to define whether include_vars should or should not overwrite existing variables. Default is `yes` to keep the module backwards compatible. Example use case: A user wants to use include_vars while he wants to make sure that already existing variables (e.g. defined in group_vars) are not getting overwritten by this include. Or from a vice-versa perspective: A role developer wants to ensure that users of his role can overwrite all variables that are getting included without having to change the role.

Probably there are many more use cases as this option makes the use of include_vars much more flexible.

See also ansible/proposals#21

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
include_vars

##### ANSIBLE VERSION
2.4

### CODE REVIEW

**Comment by bcoca** [comment]
This makes incorrect assumptions, the default is not 'overwrite' it is 'whatever hash_behaviour is set to'.

**Comment by pfink** [comment]
@bcoca: I'm not sure what you intend to say with that. You mean the option should have another name? Independent of the hash_behaviour, include_vars currently overwrites anything that is defined within the included var file (only exception: set_fact / extra_vars). The hash_behaviour is only applicable to variables of type `dict` and just determines what happens with those variables' dictionary elements that are _not_ in the included var file (in mode `replace` they'll get deleted, in mode `merge` they'll stay).

My implementation does neither change anything to the current default behaviour of the include_vars module nor does it has any impact to the hash_behaviour. But if `overwrite` is set to `no`, hash_behaviour gets irrelevant as the dictionaries neither get replaced or merged, they will (and should in this case) just stay untouched.

**Comment by bcoca** [comment]
ah, the code only touches the 'directory path' ... which i see as a bug as it ignores hash_behaviour, it should be using `combine_vars` as it loads each file.

**Comment by pfink** [comment]
what?! Now I'm completely confused. I think my option and the hash_behaviour are two completely different things.

- the `overwrite` option I added is to define if already existing variables should be changed at all (no matter if they're dictionaries or not)
- `hash_behaviour` defines how to deal with a special type of variables (dictionaries) if they're changed

**Comment by bcoca** [comment]
all variables are in the 'main' dictionary, so it would work on these also

**Comment by pfink** [comment]
I think the current implementation is correct. If include_vars would `replace` the main directory, this is not something anyone would want as it would delete all variables except of those just included ;)

**Comment by pfink** [comment]
P.S.: Is it possible to restart the CI process (rebuild)? I think it failed due to a temporary infrastructure issue that has nothing to do with my change...

**Comment by pfink** [comment]
I renewed this PR by reimplementing it against the current devel branch as well as adding docs and an integration test. Hope we can make progress here soon!

**Comment by kustodian** [comment]
I like this change and I don't see a problem with naming the parameter `overwrite`, but what I would suggest is to add a note in the docs of this parameter about `hash_behaviour`. If the devs still don't like the name of the parameter, you could always rename it to something like `skip_defined`, because it actually does skip defined vars.

**Comment by pfink** [comment]
@kustodian: What kind of note about hash_behavior would you expect in the docs of this option? From my point of view, this option and hash_behavior are not really related as they deal with different issues.

**Comment by kustodian** [comment]
It's not a completely different issue, because if `include_vars` includes a dictionary, it will actually be replaced or merged depending on the `hash_behaviour` setting. So if you call the parameter `overwrite`, it could actually mean that it always does a replace.

Now that I think about it, it's better to just add a general note, unrelated to the `overwrite` parameter, because I didn't know that this module actually obeyed `hash_behaviour`. It could be something like:
```
Including dictionaries will obey the C(hash_behaviour) setting. Check out
U(https://docs.ansible.com/ansible/latest/installation_guide/_config.html#default-hash-behaviour).
```

**Comment by pfink** [comment]
I agree, but this should be subject of a seperate PR, shouldn't it?

**Comment by kustodian** [comment]
You're probably right. I'll ping the devs tomorrow to see if we can get this merged faster.

**Comment by liquidat** [comment]
@kustodian Have you talked to the devs? Anything new about this PR?

**Comment by winggundamth** [comment]
Any update on this?

**Comment by gilesw** [comment]
+1 from me I asked for this same feature in another thread:-

https://github.com/ansible/ansible/issues/25384

Seems to be a common use case. A lot of the hard work writing ansible roles is supporting all the different combinations of versions and distributions. I think the reason people give up and write version specific roles or drop support for older versions is because of this.

**Comment by MrBones757** [comment]
Is there any update on this? I have also encountered a situation where this functionality would be useful. (looping over a task file with include_vars inside, that includes multiple files that contain the same variable name with different values)

**Comment by gilesw** [comment]
Any news on this one?

**Comment by ciis0** [comment]
Hello,

I rebased the PR for 2.11.

Unsure about the failing test, I do not see why it's failing, it's just saying `Command exited with status 1 after 74.23290514945984 seconds.` [(cf.)](https://dev.azure.com/ansible/ansible/_build/results?buildId=5936&view=logs&j=566b2aa1-0df1-542e-79cc-ee624381bdce&t=3bf3ae38-9b58-5096-1c0a-6630f7a7dd83&l=6587), but I don't see the reason.

**Comment by nitzmahone** [comment]
Closing, since the merged `hash_behaviour` to include_vars should cover most of this.

**Pull request closed without merging**
