### PR TITLE
Pamd fixes

### PR DESCRIPTION
**Pull request by kevensen**
##### SUMMARY
A comma was missing from the regex.  This addresses issue #28096.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION
```
ansible 2.4.0 (pamd-fixes 71f1c5c647)
```

### CODE REVIEW

**Comment by Cerebus** [comment]
Didn't work for me.  When I directly invoke on a file with this line:
```
account         required        pam_access.so
```
using the following json:
```JSON
{
    "ANSIBLE_MODULE_ARGS": {
        "name": "pam-file",
        "type": "account",
        "control": "required",
        "module_path": "pam_access.so",
        "module_arguments": "listsep=,",
        "state": "args_present"
    }
}
```
pamd.py returns:
```JSON
{"invocation": {"module_args": {"control": "required", "new_module_path": null, "name": "pam-file", "dest
": "/etc/pam.d/pam-file", "module_path": "pam_access.so", "new_type": null, "state": "args_present", "new
_control": null, "path": "/etc/pam.d", "type": "account", "module_arguments": ["listsep=", ""]}}, "change
d": true, "ansible_facts": {"pamd": {"changed": true, "result": {"change_count": 2, "added_arg_1": "", "a
dded_arg_0": "listsep=", "action": "args_present", "to_rule_0": "account   \trequired\tpam_access.so list
sep=", "to_rule_1": "account   \trequired\tpam_access.so listsep= "}}}}
```
and the file is changed to:
```
account         required        pam_access.so listsep=
```

**Comment by kevensen** [comment]
@Cerebus I think it's Ansible that's stripping off the comma.  By the time the "module_args" makes it to the module, the comma is already gone.  I'll investigate further.

**Comment by kevensen** [comment]
@Cerebus I figured it out.  The "module_args" takes a list which you can present as a comma delimited string.  Python/Ansible is treating that comma as an empty-ish list.  I recommend the following instead.

```yaml
---
- hosts: pamd-hosts
  vars:
    ansible_user: admin
    ansible_become: true
  tasks:
  - pamd:
      name: crond
      type: account
      control: required
      module_path: pam_access.so
      module_arguments:
      - listsep=,
      state: args_present
```

**Comment by Cerebus** [comment]
@kevensen That works as a workaround for now.  Should this remain as a bug or closed w/ a documentation change?

**Comment by kevensen** [comment]
@Cerebus I did have to make a code change.  Please leave this open and I'll make a change to the documentation.

**Comment by kevensen** [comment]
Messed up pull request.

**Pull request closed without merging**
