### PR TITLE
VMware: added support for tags in vmware_inventory script

### LINKED ISSUE #36915: VMware: VMWare inventory - Add tag
##### ISSUE TYPE
Feature

##### COMPONENT NAME
contrib/inventory/vmware_inventory.py

##### ANSIBLE VERSION
devel

##### SUMMARY

Hello,

Is it possible to add tag for vmware_inventory.py instead of custom field ? Custom field will are outdated.
For tags : https://code.vmware.com/apis/191/vsphere-automation

Thank you.

### PR DESCRIPTION
**Pull request by remil1000**
* tags feature added in vSphere 6.5 (edit: first thought it was introduced with 6.0)
  * enabled using env VMWARE_INCLUDE_TAGS or config include_tags
  * hosts get a dict of tags name with tag values as array
  * hosts get grouped by tags prefixed by vmware_tag_

##### SUMMARY

Tags were added in vSphere 6 and may replace custom fields in the near future

This PR tries to implement a way of collecting those tags and group hosts by common tags value

Fixes #36915

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

contrib dynamic inventory script

##### EXAMPLE

environment variable: `VMWARE_INCLUDE_TAGS=True`
or configuration file in `[vmware]` section: `include_tags = True`

Hosts are grouped using their tags prefixed with vmware_tag_:

```json
{
        "all": {  },
        "guest": {  },
        "vmware_tag_Managed_by_ansible": {
                "hosts": [
                        "hostname1.domain.tld"
                ]
        },
        "vmware_tag_Managed_by_terraform": {
                "hosts": [
                        "hostname1.domain.tld"
                ]
        },
        "vmware_tag_Domain_domain.tld": {
                "hosts": [
                        "hostname1.domain.tld",
                        "hostname2.domain.tld"
                ]
        }
}
```

With a given host having extra tags key looking like:

```json
"hostname1.domain.tld": {
        "name": "hostname1",
        "tags": {
                "Domain": [
                        "domain.tld"
                ],
               "Managed_by": [
                        "ansible",
                        "terraform"
                ]
        }
}
```

### CODE REVIEW

**Comment by rajmechi** [comment]
hey @remil1000  i am trying to play with the vmware tags but getting below error when i try to run https://github.com/ansible/ansible/blob/807181806bdda6519e43ca9d0044a5b3ebda5019/contrib/inventory/vmware_inventory.py 

./vmware_inventory.py --list --debug
2018-09-05 19:20:18.679692 cache path is /root/.ansible/tmp/ansible-vmware.cache
2018-09-05 19:20:18.679750 server isxxxxx
2018-09-05 19:20:18.679773 username isxxxxxx
2018-09-05 19:20:18.679797 cert validation is False
2018-09-05 19:20:18.679810 max object level is 1
2018-09-05 19:20:18.679825 lower keys is True
2018-09-05 19:20:18.679843 skip keys is ['declaredalarmstate', 'disabledmethod', 'dynamicproperty', 'dynamictype', 'environmentbrowser', 'managedby', 'parent', 'childtype', 'resourceconfig']
2018-09-05 19:20:18.679862 host filters are ['{{ runtime.powerstate == "poweredOn" }}']
2018-09-05 19:20:18.679880 groupby patterns are ['{{ guest.guestid}}', '{{ "templates" if config.template else "guests"}}']
2018-09-05 19:20:18.679895 groupby exclude strings are ['']
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./vmware_inventory.py", line 906, in <module>
    print(VMWareInventory().show())
  File "./vmware_inventory.py", line 151, in __init__
    self.do_api_calls_update_cache()
  File "./vmware_inventory.py", line 191, in do_api_calls_update_cache
    self.tags = self.get_tags()
  File "./vmware_inventory.py", line 241, in get_tags
    tag_name = tag_value['name'].replace(" ", "_")
KeyError: 'name'

INI File:
[vmware]
server=xxxxxxxxx
username=xxxxxx
password=xxxxxxxx
validate_certs=False
alias_pattern={{ config.name }}


using
ansible 2.6.3
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5

any help is appreciated

**Comment by remil1000** [comment]
Hi @rajmechi , thanks for the interest

Is your vcenter providing the REST API entrypoint and the cis/tagging API ? not sure of the exact version needed, I know 6.5+ do provide it and I've been mainly testing this on 6.5 and 6.7
tags API is under /rest/com/vmware/cis/tagging/tag but you can also check using the API explorer under https://vcenter-hostname.domain.tld/apiexplorer and search for cis API and then tagging

If you can't find it on your Vcenter, could you run the following Python script and provide the output ? (redact parts if needed) 

[rest_tags_api_test.txt](https://github.com/ansible/ansible/files/2356312/rest_tags_api_test.txt)

**Comment by rajmechi** [comment]
hi @remil1000
i am using vCenter 6. and I can't access https://vcenterurl/apiexplorer ( looks like API's are not enabled)

output of your script:
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
rest status code: 200
{"value":{"resources":{"method":"GET","href":"https://vcenterURL/rest/com/vmware/vapi/rest/navigation/resource","metadata":{"method":"GET","href":"https://vcenterURL/rest/com/vmware/vapi/metadata/metamodel/service/operation/id:com.vmware.vapi.rest.navigation.resource/id:list"}},"components":{"method":"GET","href":"https://vcenterURL/rest/com/vmware/vapi/rest/navigation/component","metadata":{"method":"GET","href":"https://vcenterURL/rest/com/vmware/vapi/metadata/metamodel/service/operation/id:com.vmware.vapi.rest.navigation.component/id:list"}}}}
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
auth status code: 200
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{u'type': u'com.vmware.vapi.std.errors.unauthenticated',
 u'value': {u'messages': [{u'args': [],
                           u'default_message': u'This method requires authentication.',
                           u'id': u'vapi.method.authentication.required'}]}}
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{u'localizableMessages': [{u'defaultMessage': u'Not found.',
                           u'id': u'com.vmware.vapi.rest.httpNotFound'}],
 u'majorErrorCode': 404,
 u'name': u'com.vmware.vapi.rest.httpNotFound'}
[root@ansiblelab ~]# vim vcenter.py

**Comment by remil1000** [comment]
@rajmechi 
Sorry for the misleading first comment then (I've edited it);
it looks like REST API and tags support is only available in 6.5+ so you would need to first upgrade to test this

**Comment by rajmechi** [comment]
Thanks @remil1000  for working on this issue.

**Comment by generalconsensus** [comment]
This works perfectly for what I need. Please merge this!

**Comment by jdavis-douglas-co-us** [comment]
Is there any traction to commit this anytime soon?  Want+++

**Comment by mdicerbo** [comment]
Any news about this commit? Very usefull!

**Comment by jdavis-douglas-co-us** [comment]
Please merge this. I've been running it for a few months now and can't live without it. We are moving away from custom attributes to tags and this added code was key. Thanks @remil1000 !!!

**Comment by sivel** [comment]
We are no longer accepting feature additions to contrib inventory scripts. The contrib inventory scripts are deprecated in favor of the newer inventory plugins.

**Comment by sivel** [comment]
Please test the new https://docs.ansible.com/ansible/latest/plugins/inventory/vmware_vm_inventory.html plugin

Information on using inventory plugins can be found at https://docs.ansible.com/ansible/latest/plugins/inventory.html

If this functionality needs added to that new plugin, we would be willing to review a change there, instead of this contrib inventory script.

**Comment by jdavis-douglas-co-us** [comment]
If the plugins had at least the same features the existing contrib scripts had then maybe more people might try them. At present the plugins are a bit feature weak - IMHO.

**Comment by goneri** [comment]
Hi @remil1000, thank you for the PR, I'm sorry it cannot be merged. https://docs.ansible.com/ansible/latest/plugins/inventory/vmware_vm_inventory.html  comes with a `with_tags` parameter. Is this enough for your use-case?

needs_info

**Comment by remil1000** [comment]
Hi @goneri and thank you for the follow up,

I don't have access to a running vcenter/vsphere environment to test anymore (changed job) but by looking at the description and the code it looks like it may be what I was looking for.

@jdavis-douglas-co-us , @mdicerbo , @generalconsensus were you able to test this ?

If there is a need for more features I could take a look, I have some free time in the next coming weeks; the only issue is I'm not sure on how to get access to a working Vsphere/VCenter 6.5+ environment

**Comment by MrBones757** [comment]
Hi all,
@remil1000 @goneri 
I've updated this script to include any changes that exist in devl as there was some sort of issue comparing vm objects..

Ill supply a version of the code i used (updated with changes in devel) attached.
I also added raw tagging rather than prefix_caregory_tag for my own use - not sure if this is desired.

Only issue i found was that i get *alot* of urllib errors for some reason.. might just be my runtime environment.

@sivel 
This contrib script still seems to be used in awx/tower for vmware dynamic inventory. (that's how i stumbled across this pull request). Not sure what the plan for migrating to the inventory plugins is there, so in the meantime is this the right place for this contribution or should i create a PR against AWX? 

(apologies for txt - cant upload py)
[vmware_inventory.txt](https://github.com/ansible/ansible/files/4077738/vmware_inventory.txt)

**Comment by Akasurde** [comment]
The inventory script is superseded by the inventory plugin. Please use [`vmware_vm_inventory`](https://github.com/ansible-collections/vmware/blob/master/plugins/inventory/vmware_vm_inventory.py) inventory plugin instead of `vmware_inventory`.

Thanks for the contribution.

**Pull request closed without merging**
