### PR TITLE
Followup tweaks to module EXAMPLES, per comments in #29039

### PR DESCRIPTION
**Pull request by cben**
##### SUMMARY
Followup tweaks to module EXAMPLES, per comments in #29039

- Dropped `hosts:`,  `tasks:` play boilerplate from EXAMPLES string, should be just individual tasks.
  https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#examples-block

- Demonstrate url with port in one of the EXAMPLES

 ##### ISSUE TYPE
 - Docs Pull Request

 ##### COMPONENT NAME
manageiq_provider module

### CODE REVIEW

**Comment by cben** [comment]
@pavelzag @yaacov @zgalor please review
(diff ignoring whitespace: https://github.com/ansible/ansible/pull/30248/files?w=1)

**Review by yaacov — APPROVED** [review]
LGTM :+1:

+1 for the no whitespaces link :-)

**Comment by yaacov** [comment]
shipit

**Review by zgalor — APPROVED** [review]
shipit

**Pull request merged**
