### PR TITLE
Remove shebangs from core Python modules.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Remove shebangs from core Python modules. 

The shebangs in core Python modules are unused, due to one of the following:

* Docs only module.
* New-style Python module.

Since they are unused they can be safely removed.

The `validate-modules` sanity test in `ansible-test` has been updated to allow new-style Python modules to omit the shebang. If the shebang does exist, it must continue to pass the existing checks.

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

ansible
ansible-test

### CODE REVIEW

**Comment by nkadel** [comment]
Would it make it more acceptable to strip the header with an individual commit for each file altered?

**Comment by nkadel** [comment]
Should there be a similar pull request for the .py files under https://github.com/ansible/ansible/tree/devel/test ? I'd not gotten the "test" scripting to work under RHEL 7 myself,.

**Comment by mattclay** [comment]
@nkadel No need for additional commits. We usually squash PRs to a single commit when merging. As for changes to test related files, that's out-of-scope for this PR. While some of the tests have embedded Ansible modules in them, many of the scripts there are not modules and this change would not apply to them.

**Review by nitzmahone — APPROVED** [review]

**Comment by mattclay** [comment]
@nkadel As for running tests on RHEL 7, you'll either need to install Python 3.8 to be able to run `ansible-test`, or run it from another system with Python 3.8+ and target a separate RHEL 7 system when running integration tests (this doesn't work for unit or sanity tests). In either case, no changes to the shebangs are required, as `ansible-test` handles injecting the correct `python` into the path when tests are executed.

**Comment by nkadel** [comment]
For RHEL 7, the only wokring python 3.8 is in SCLO. I took a shot at backporting the RHEL 8 python38 package to RHEL 7. It wasn't pretty. I'm afraid that, for RHEL 7 or EPEL 7, it will need to stay on ansible-core 2.11 for the foreseeable futue.

Unless, perhaps the python 3.8 requirements for ansible 2.12 can be reverted?

**Comment by mattclay** [comment]
The controller minimum Python requirement for 2.12 will not be changing. Also, the minimum supported Python version on the controller is expected to be bumped every 2 ansible-core releases (once a year), to keep pace with new Python releases.

**Pull request merged**
