### PR TITLE
Docker: names, update port mapping support, add `publish_all_ports` flag, add container links

### PR DESCRIPTION
**Pull request by joshuaconner**
This builds on #5301, but adds updated port-mapping support and the `publish_all_ports` flag. It also supports container links. LMK if you have any questions!

### CODE REVIEW

**Comment by mpdehaan** [comment]
So I need to evaluate if too much is getting blended into one module here.

This is on my list to dig into in the coming weeks.

**Comment by joshuaconner** [comment]
FWIW the module as it stands is basically an idempotent version of the `docker run` command from the Docker CLI and this PR just adds/fixes some of the possible command args, though it's using the Docker python bindings to do it. Good luck!

**Comment by keybits** [comment]
+1 for including this. As @joshuaconner says it's just adding support for the arguments available to `docker run`.

**Comment by joshuaconner** [comment]
(Updated with suggestions from #5956.)

**Comment by joshuaconner** [comment]
This should be good to go again!

**Comment by joshuaconner** [comment]
This has been rolled into #6171, closing!

**Pull request closed without merging**
