### PR TITLE
[WIP] Add `--separate-gvars` option for inventory --list

### PR DESCRIPTION
**Pull request by ryansb**
This display option doesn't change the interpretation of the variables
or precedence, but displays group variables on the associated group
instead of flattening and repeating the variable on each host in the
group.

[DON'T MERGE THIS]

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ansible-inventory

##### ANSIBLE VERSION

```
ansible 2.5.0 (efficient-gvars-display 6d367da6c2) last updated 2018/01/24 14:53:13 (GMT -400)
  config file = /home/ryansb/code/scratch/ec2_inv/ansible.cfg
  configured module search path = [u'/home/ryansb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ryansb/code/ansible/lib/ansible
  executable location = /home/ryansb/code/ansible/bin/ansible
  python version = 2.7.12 (default, Sep 27 2016, 18:08:33) [GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
```

##### ADDITIONAL INFORMATION

One option for #30877

```

```

### CODE REVIEW

**Comment by ryansb** [comment]
Before this change, groups are shown only with their children and vars are flattened:

```
{
    "_meta": {
        "hostvars": {
            "test1": {
                "group_var1": "on_all_hosts", 
                "last_var": "MYVALUE"
            }, 
            "test2": {
                "group_var1": "on_all_hosts", 
                "var1": "only_on_test2"
            }, 
            "test4": {
                "ansible_host": "127.0.0.1", 
                "g2_var2": "only_on_host4", 
                "group_var1": "on_all_hosts"
            }
        }
    }, 
    "all": {
        "children": [
            "last_group", 
            "other_group", 
            "ungrouped"
        ]
    }, 
    "last_group": {
        "hosts": [
            "test1"
        ]
    }, 
    "other_group": {
        "hosts": [
            "test4"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "test2"
        ]
    }
}
```

After this change, vars defined at group-level are shown on the appropriate group:

```
{
    "_meta": {
        "hostvars": {
            "test1": {}, 
            "test2": {
                "var1": "only_on_test2"
            }, 
            "test4": {
                "ansible_host": "127.0.0.1"
            }
        }
    }, 
    "all": {
        "children": [
            "last_group", 
            "other_group", 
            "ungrouped"
        ], 
        "vars": {
            "group_var1": "on_all_hosts"
        }
    }, 
    "last_group": {
        "hosts": [
            "test1"
        ], 
        "vars": {
            "last_var": "MYVALUE"
        }
    }, 
    "other_group": {
        "hosts": [
            "test4"
        ], 
        "vars": {
            "g2_var2": "only_on_host4"
        }
    }, 
    "ungrouped": {
        "hosts": [
            "test2"
        ]
    }
}
```


Both of these output examples come from the same source inventory, the YAML example:

```
all: # keys must be unique, i.e. only one 'hosts' per group
  hosts:
    test1:
    test2:
      var1: only_on_test2
  vars:
    group_var1: on_all_hosts
  children:   # key order does not matter, indentation does
    other_group:
      vars:
        g2_var2: only_on_host4
      hosts:
        test4:
          ansible_host: 127.0.0.1
    last_group:
      hosts:
        test1 # same host as above, additional group membership
      vars:
        last_var: MYVALUE
```

**Comment by bcoca** [comment]
he, this was 'on my list' .... but a few things, there are 2 'group vars', one that is provided by inventory directly and another that is provided by the 'vars plugins', I'm not sure if we should merge those or keep separate.

Also to eliminate redundancy you cannot use vars manager to get the 'host vars' in this case, you need to partially reproduce it's logic here, but only the parts for inventory and vars plugins, with the same question for host_vars/ as we had for group_vars/ above.

bikeshedding: was thinking --optimized or --source-layout as its not just '--group vars'.

**Comment by gundalow** [comment]
Close or perhaps @bcoca to take this over?

**Comment by bcoca** [comment]
we already implemented --export which supersedes this

**Pull request closed without merging**
