### PR TITLE
Add kubevirt_rs module

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

This PR add new `kubevirt_rs` module to manage Kubevirt replica sets.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

kubevirt_rs

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by pkliczewski — COMMENTED** [review]
The module looks good. Should we push some tests as well?

**Review by pkliczewski — APPROVED** [review]

**Comment by pkliczewski** [comment]
shipit

**Comment by machacekondra** [comment]
shipit

**Comment by gundalow** [comment]
Merged into `devel`, thanks!

**Pull request merged**
