### PR TITLE
add integration test for ansible-pull

### PR DESCRIPTION
**Pull request by robinro**
- this test includes the behavior described in #13688 and #13681
- it runs a minimal playbook and checks for correct use of inventory and limit

### CODE REVIEW

**Comment by robinro** [comment]
@bcoca 
This adds integration tests for ansible-pull, so we get some reproducibility and documentation of our discussion around #13681 and #13688 

Your pull-request in #14251 fails with this tests, while #14242 works for me.

**Comment by robinro** [comment]
to run the new tests do `cd test/integration; make pull`

**Comment by bcoca** [comment]
i don't think your tests are correct, the fail for me with both patches, in any case i would setup something in ansible's repo, already made a mistake with having 3rd party repos in galaxy (fixing that is on my list).

Though i might just use this PR and modify it to use an ansible/ repo, so i'm keeping it open for now.

**Comment by bcoca** [comment]
adding test 'as is' but will change to use local repo (optionally with ansible/remote one if tag supplied)

**Pull request merged**
