### PR TITLE
win_file: Add check-mode support

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

win_file

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Also a small cleanup

### CODE REVIEW

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by dagwieers** [comment]
This relies on Windows aliases support in #20599 (this explains the CI errors)

**Comment by gundalow** [comment]
needs_revision
Integration tests are failing on all Windows versions with `"msg": "Missing required argument: path"`

**Comment by dagwieers** [comment]
@gundalow It relies on Windows aliases support in #20599 (this explains the CI errors)

Can you rebuild, #20599 has been merged !

**Comment by dagwieers** [comment]
@mattclay @jhawkesworth @nitzmahone @trondhindenes @JimFicarra Please review and test this.
I need two more shipits :-)

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
