### PR TITLE
add azure_rm_keyvaultkey_info module

### PR DESCRIPTION
**Pull request by yungezz**
##### SUMMARY

add azure_rm_keyvaultkey_info module

##### ISSUE TYPE

- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by zikalino — CHANGES_REQUESTED** [review]
in general looks good, but I think we shouldn't merge _facts any longer but _info, so we should wait until this is established.

**Comment by Fred-sun** [comment]
@yungezz existing  conflicting files, Please resolve when you're available! Thanks!

**Comment by Fred-sun** [comment]
@yungezz Please finished PR update when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
@yungezz Please help finished the PR changed when you're free, and push for review. Thanks a lot!

**Comment by yungezz** [comment]
ready_for_review

**Review by zikalino — APPROVED** [review]
looks good

**Pull request merged**
