### PR TITLE
Fix junos_facts test (#57065)

### PR DESCRIPTION
**Pull request by danielmellado**
##### SUMMARY
This change is a backport from devel branch which fixes some issues some
issues on junos_facts tests.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
junos_facts

##### ADDITIONAL INFORMATION
backported from devel

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
There will be no results posted here, but we did run this job on zuul.a.c, and the patch worked as expected

**Comment by pabelanger** [comment]
We are not posting right now, because the testing isn't passing yet.

**Comment by abadger** [comment]
Thanks!

Merged for the 2.8.1 release.

**Pull request merged**
