### PR TITLE
Add identifier option to apache2_module

### LINKED ISSUE #32690: Apache Enable Module fails if already enabled for php53
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apache2_module

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.venv/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/ubuntu/.venv/ansible/bin/ansible
  python version = 3.6.3 (default, Oct  6 2017, 08:44:35) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
No extra configuration.

##### OS / ENVIRONMENT
Ubuntu 16.04 host managing Ubuntu 16.04 nodes (Linux containers).

##### SUMMARY
When using apache2_module to enable php53 module, apache2_module fails. De facto it enables the module, but (I suppose) during check afterwards - it fails.

The problem is probably that:
1. to enable / disable php53 module the "php53" name is used
2. in the putput of apache2ctl -M the "php5" name is used:

$ a2/enmod / a2dismod php53
$ apache2ctl -M
[...]
 php5_module (shared)

##### STEPS TO REPRODUCE

```yaml
- name: "Enable Apache PHP 5.3 module"
  become: yes
  apache2_module: name=php53 state=present force=True
  notify:
  - restart apache2
```

##### EXPECTED RESULTS
apache2_module to correctly identify that the php53 module is already enabled, and then not fail.

##### ACTUAL RESULTS

```
fatal: [10.90.44.158]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "force": true,
            "ignore_configcheck": false,
            "name": "php53",
            "state": "present"
        }
    },
    "msg": "Failed to set module php53 to enabled: Module php53 already enabled\n",
    "rc": 0,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Module php53 already enabled\n",
    "stdout_lines": [
        "Module php53 already enabled"
    ]
}
```

### PR DESCRIPTION
**Pull request by robinro**
##### SUMMARY

Add a new option `identifier` to apache2_module.

Fixes #32690

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
apache2_module

##### ANSIBLE VERSION
devel

##### ADDITIONAL INFORMATION
There is a convention connecting the name passed to a2enmod and the one
appearing in apache2ctl -M. Not all modules follow this convention and
we have added a growing list of implicit conversions, see
https://github.com/ansible/ansible/blob/ba99e44b423f64227b94e0f201c4c340a989dc11/lib/ansible/modules/web_infrastructure/apache2_module.py#L145-L161

As a better long-term solution this adds an "identifier" option to be
able to set both strings explicitly.

### CODE REVIEW

**Comment by robinro** [comment]
This provides a better workaround (or even fix) for https://github.com/ansible/ansible/issues/33669.

**Review by resmo — APPROVED** [review]
shipit

**Comment by n0trax** [comment]
@robinro nice idea with the identifier option.
Can you be so kind and add an example with the new option?

**Comment by resmo** [comment]
@robinro could you add an example in the example section with the new argument?

**Comment by robinro** [comment]
Thanks @n0trax for the example.

@resmo This should now be ready for a merge.

**Pull request merged**
