### PR TITLE
eos_config: extend sessions support validation

### LINKED ISSUE #19586: eos_config: fails on earlier EOS versions due to session-config
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
I believe this is unchanged in 2.3 from my quick read of the source, I have not however tested it.
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
EOS 4.14.12M 

##### SUMMARY
EOS config attempts to use a configuration session in a way that isnt supported on older EOS versions. Specifically the "show session-config diffs" command doesnt always exist.

##### STEPS TO REPRODUCE
On older versions of EOS specifically tested against 4.14.12M this play will fail
```yaml
---
- name: Change the password
  eos_config:
    provider: "{{ cli }}"
    force: true
    lines:
      - "username admin privilege 15 role network-admin secret 0 {{ secret_password }}"
```
##### EXPECTED RESULTS
Successful run of the play

##### ACTUAL RESULTS
```
fatal: [<removed>]: FAILED! => {
    "changed": false,
    "commands": [
        "configure session ansible_1482233620",
        "show session-config diffs",
        "end"
    ],
    "failed": true,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": false,
            "backup": false,
            "before": null,
            "config": null,
            "defaults": false,
            "force": true,
            "host": <removed>,
            "lines": [
                "username admin privilege 15 role network-admin secret 0 <removed>",
            ],
            "match": "none",
            "parents": null,
            "password": <removed>
            "port": null,
            "provider": {
                "host": <removed>
                "password": <removed>
                "transport": "cli",
                "username": <removed>
            },
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "use_ssl": true,
            "username": <removed>,
            "validate_certs": true
        }
    },
    "msg": "matched error in response: show session-config diffs\r\n% Invalid input\r\n<removed>(config-s-ansibl)#"
}
```

### PR DESCRIPTION
**Pull request by Zanthras**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
eos

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY

Fixes #19586

As there is no way of checking ahead of time if session support is complete, I extended the supports_sessions method to attempt all needed aspects of sessions and clean up after the test.

As it was cleaner I moved session generated into the method and made it return the session id for use.

```
before:
TASK [test EOS configs] ***************************************************
fatal: [switch1]: FAILED! => {"changed": false, "commands": ["configure session ansible_1484078362", "show session-config diffs", "end"], "failed": true, "msg": "matched error in response: show session-config diffs\r\n% Invalid input\r\nswitch2(config-s-ansibl)#"}

after:
TASK [test EOS configs] ***************************************************
changed: [switch1]
 [WARNING]: The current version of EOS on the remote device does not support configuration sessions.  The commit
argument will be ignored
```

### CODE REVIEW

**Comment by mattclay** [comment]
bot_status

**Comment by gundalow** [comment]
Rebase needed

**Comment by gundalow** [comment]
Hi, could you please rebase this PR?

**Comment by rcarrillocruz** [comment]
Moving to 2.4.0 milestone. 
Waiting from comitter to rebase, plus this is not a bugfix but an enhancement.

**Comment by calfonso** [comment]
@Zanthras just checking in on this PR, are you planning on rebasing to get this merged?

**Comment by gundalow** [comment]
@Zanthras Would you be able to rebase this?

**Comment by calfonso** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. Our reasons for this are:

No response in months.

However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

https://groups.google.com/forum/#!forum/ansible-devel
In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
