### PR TITLE
added default datacenter ha-datacenter and set wait_for_ip_address to…

### PR DESCRIPTION
**Pull request by dav1x**
… default False - closes 21074

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
ansible --version

ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY

Attempt to use vmware_guest with a direct ESXi host without specifying a datacenter. You get an error.

If you install a fresh install of ESXi the default datacenter will always be:

govc ls
/ha-datacenter/vm
/ha-datacenter/network
/ha-datacenter/host
/ha-datacenter/datastore

The default setting for datacenter should be ha-datacenter.

```
---
- name: create vm
  hosts: localhost
  tasks:
    - vmware_guest:
        hostname: "10.x.x.165"
        username: "root"
        password: "***"
        validate_certs: False
        name: "testvm"
        validate_certs: False
        #datacenter: "ha-datacenter"
        #wait_for_ip_address: False
        state: present      
```

### CODE REVIEW

**Comment by nerzhul** [comment]
!needs_rebase
shipit

**Comment by dav1x** [comment]
should be up2date now. Thanks @nerzhul !

**Comment by nerzhul** [comment]
seems you merge instead of rebase :(

**Comment by nerzhul** [comment]
shipit

**Comment by dagwieers** [comment]
If the description clearly stated: "This closes #21074" the issue would automatically close.
Now there is no relation to it.

shipit

**Comment by nerzhul** [comment]
bot_status

@jctanner when the merge will occur ?

**Comment by rollerwhrtn** [comment]
@dav1x - There was a conflict when using both Required=True and setting the Default for the datacenter arg in vmware_guest: 
`fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Module alias error: internal error: required and default are mutually exclusive for datacenter"
}`
Submitted a pull request for the fix, by setting required=False. #21492

**Pull request merged**
