### PR TITLE
Facts: Do not fail if Ansible can not run local facts due to user rights

### LINKED ISSUE #52427: Playbooks can not be executed if local facts cannot be executed by all users
##### SUMMARY
When attempting to collect facts if there are local facts files not owned by the user running ansible or the playbook the playbook fails if the files do not have rights for all users. 

This happens because the code at this moment only checks if the files can be executed and then runs the script or if there are no rights for execution, tries to read the file as a json.

This is an issue for several reasons:

- Any user can avoid playbooks from being executed on the host by placing a file in the /etc/ansible/facts.d file without execution rights or belonging to an UID not present in the server.
- Facts may be exposing security information that maybe should not be accessible by all users, so it makes sense to restrict access and execution by using unix users and groups.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

setup module is affected

##### ANSIBLE VERSION

```ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/acampesino/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/acampesino/ansible-orginal/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible
  executable location = /home/acampesino/ansible-orginal/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```
Tested too in computers from my workplace, but cannot provide verbose from them for legal reasons versions tested there:
```
ansible 2.4
ansible 2.7
ansible 2.8
```

##### CONFIGURATION

```paste below

```

##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

This are the files I created on  /etc/ansible/facts.d/

``(ansible-orginal) acampesino@acampesino:~/ansible_tests$ ls -l /etc/ansible/facts.d/
total 12
-rw-r----- 1 root root       199 feb 17 13:20 other.fact
-rwxr-x--- 1 root acampesino  39 feb 17 12:19 test.fact
-rwxr----- 1 root root        42 feb 17 11:12 znew.fact
```
- other.fact is a simple json file.
- test.fact and znew.fact are simple scripts that just echo a simple json

<!--- Paste example playbooks or commands between quotes below -->

This is the detail of the files:

```(ansible-orginal) acampesino@acampesino:~/ansible_tests$ for file in $(ls /etc/ansible/facts.d/); do echo $file; sudo cat /etc/ansible/facts.d/$file;done
other.fact
 {
            "codename": "bionic",
            "description": "Ubuntu 18.04.1 LTS",
            "id": "Ubuntu",
            "major_release": "18",
            "release": "18.04"
        }
        
test.fact
#!/bin/bash
echo '{ "empty" : "test"}'
znew.fact
#!/bin/bash
echo '{ "result" : "empty" }'
```

##### EXPECTED RESULTS

I will expect the playbook to run, and if the fact is not available for the user, just post that information into the facts json. I managed to get the expected result by branching devel and modifying 
**ansible_tests/lib/ansible/module_utils/facts/system/local.py**

``` ansible -m setup -i 'localhost,' -a 'filter=ansible_local' all -k -vvv
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/acampesino/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/acampesino/ansibleenv/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible
  executable location = ../ansibleenv/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
No config file found; using defaults
SSH password: 
Parsed localhost, inventory source with host_list plugin
META: ran handlers
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> (0, b'/home/acampesino\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434 `" && echo ansible-tmp-1550433673.96448-136308369411434="` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434 `" ) && sleep 0'"'"''
<localhost> (0, b'ansible-tmp-1550433673.96448-136308369411434=/home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434\n', b'')
Using module file /home/acampesino/ansibleenv/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible/modules/system/setup.py
<localhost> PUT /home/acampesino/.ansible/tmp/ansible-local-13635xu2oum90/tmpzu62nf01 TO /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434/AnsiballZ_setup.py
<localhost> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 '[localhost]'
<localhost> (0, b'sftp> put /home/acampesino/.ansible/tmp/ansible-local-13635xu2oum90/tmpzu62nf01 /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434/AnsiballZ_setup.py\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'chmod u+x /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434/ /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (0, b'', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 -tt localhost '/bin/sh -c '"'"'/usr/bin/python /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (0, b'\r\n{"invocation": {"module_args": {"filter": "ansible_local", "gather_subset": ["all"], "fact_path": "/etc/ansible/facts.d", "gather_timeout": 10}}, "ansible_facts": {"ansible_local": {"test": {"empty": "test"}, "other": "error loading fact - please check content", "znew": "error loading fact - please check content"}}}\r\n', b'Shared connection to localhost closed.\r\n')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'rm -f -r /home/acampesino/.ansible/tmp/ansible-tmp-1550433673.96448-136308369411434/ > /dev/null 2>&1 && sleep 0'"'"''
<localhost> (0, b'', b'')
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_local": {
            "other": "error loading fact - please check content",
            "test": {
                "empty": "test"
            },
            "znew": "error loading fact - please check content"
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_local",
            "gather_subset": [
                "all"
            ],
            "gather_timeout": 10
        }
    }
}
META: ran handlers
META: ran handlers
```

##### ACTUAL RESULTS

```(ansible-orginal) acampesino@acampesino:~/ansible_tests$ ../ansible-orginal/bin/ansible -m setup -i 'localhost,'  -a 'filter=ansible_local' all -k -vvv
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/acampesino/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/acampesino/ansible-orginal/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible
  executable location = ../ansible-orginal/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
No config file found; using defaults
SSH password: 
Parsed localhost, inventory source with host_list plugin
META: ran handlers
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> (0, b'/home/acampesino\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936 `" && echo ansible-tmp-1550432459.9194748-143150622851936="` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936 `" ) && sleep 0'"'"''
<localhost> (0, b'ansible-tmp-1550432459.9194748-143150622851936=/home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936\n', b'')
Using module file /home/acampesino/ansible-orginal/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible/modules/system/setup.py
<localhost> PUT /home/acampesino/.ansible/tmp/ansible-local-12948grjgfuah/tmp6eeysray TO /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py
<localhost> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 '[localhost]'
<localhost> (0, b'sftp> put /home/acampesino/.ansible/tmp/ansible-local-12948grjgfuah/tmp6eeysray /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'chmod u+x /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/ /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (0, b'', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 -tt localhost '/bin/sh -c '"'"'/usr/bin/python /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (1, b'\r\n{"exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_setup_payload_lkDXkZ/ansible_setup_payload.zip/ansible/module_utils/basic.py\\", line 2845, in run_command\\n    cmd = subprocess.Popen(args, **kwargs)\\n  File \\"/usr/lib/python2.7/subprocess.py\\", line 394, in __init__\\n    errread, errwrite)\\n  File \\"/usr/lib/python2.7/subprocess.py\\", line 1047, in _execute_child\\n    raise child_exception\\n", "cmd": "/etc/ansible/facts.d/znew.fact", "failed": true, "rc": 13, "invocation": {"module_args": {"filter": "ansible_local", "gather_subset": ["all"], "fact_path": "/etc/ansible/facts.d", "gather_timeout": 10}}, "msg": "[Errno 13] Permission denied"}\r\n', b'Shared connection to localhost closed.\r\n')
<localhost> Failed to connect to the host via ssh: Shared connection to localhost closed.
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'rm -f -r /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/ > /dev/null 2>&1 && sleep 0'"'"''
<localhost> (0, b'', b'')
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_setup_payload_lkDXkZ/ansible_setup_payload.zip/ansible/module_utils/basic.py", line 2845, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

localhost | FAILED! => {
    "changed": false,
    "cmd": "/etc/ansible/facts.d/znew.fact",
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_local",
            "gather_subset": [
                "all"
            ],
            "gather_timeout": 10
        }
    },
    "msg": "[Errno 13] Permission denied",
    "rc": 13
}
```

### PR DESCRIPTION
**Pull request by ACampesinin**
##### SUMMARY

Fixes #52427 

I decided to check the rights over each facts file in order to know if it is runable by the user running the playbook. In order to do that it considers:

1. If file is owned by the user
2. If file is owned by any of the user groups.
3. If the file can be executed by anyone
4. If the file can be read by anyone
5. If none of the above, the local fact output is a message saying that fact is not readable by the user.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

setup module

##### ADDITIONAL INFORMATION

Check the bug report: https://github.com/ansible/ansible/issues/52427

**Before my change**
```<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> (0, b'/home/acampesino\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936 `" && echo ansible-tmp-1550432459.9194748-143150622851936="` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936 `" ) && sleep 0'"'"''
<localhost> (0, b'ansible-tmp-1550432459.9194748-143150622851936=/home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936\n', b'')
Using module file /home/acampesino/ansible-orginal/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible/modules/system/setup.py
<localhost> PUT /home/acampesino/.ansible/tmp/ansible-local-12948grjgfuah/tmp6eeysray TO /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py
<localhost> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 '[localhost]'
<localhost> (0, b'sftp> put /home/acampesino/.ansible/tmp/ansible-local-12948grjgfuah/tmp6eeysray /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'chmod u+x /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/ /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (0, b'', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 -tt localhost '/bin/sh -c '"'"'/usr/bin/python /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (1, b'\r\n{"exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_setup_payload_lkDXkZ/ansible_setup_payload.zip/ansible/module_utils/basic.py\\", line 2845, in run_command\\n    cmd = subprocess.Popen(args, **kwargs)\\n  File \\"/usr/lib/python2.7/subprocess.py\\", line 394, in __init__\\n    errread, errwrite)\\n  File \\"/usr/lib/python2.7/subprocess.py\\", line 1047, in _execute_child\\n    raise child_exception\\n", "cmd": "/etc/ansible/facts.d/znew.fact", "failed": true, "rc": 13, "invocation": {"module_args": {"filter": "ansible_local", "gather_subset": ["all"], "fact_path": "/etc/ansible/facts.d", "gather_timeout": 10}}, "msg": "[Errno 13] Permission denied"}\r\n', b'Shared connection to localhost closed.\r\n')
<localhost> Failed to connect to the host via ssh: Shared connection to localhost closed.
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'rm -f -r /home/acampesino/.ansible/tmp/ansible-tmp-1550432459.9194748-143150622851936/ > /dev/null 2>&1 && sleep 0'"'"''
<localhost> (0, b'', b'')
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_setup_payload_lkDXkZ/ansible_setup_payload.zip/ansible/module_utils/basic.py", line 2845, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

localhost | FAILED! => {
    "changed": false,
    "cmd": "/etc/ansible/facts.d/znew.fact",
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_local",
            "gather_subset": [
                "all"
            ],
            "gather_timeout": 10
        }
    },
    "msg": "[Errno 13] Permission denied",
    "rc": 13
}```

**After my change **
```ansible -m setup -i 'localhost,' -a 'filter=ansible_local' all -k -vvv
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/acampesino/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/acampesino/ansibleenv/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible
  executable location = ../ansibleenv/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
No config file found; using defaults
SSH password: 
Parsed localhost, inventory source with host_list plugin
META: ran handlers
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> (0, b'/home/acampesino\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568 `" && echo ansible-tmp-1550434706.6798608-248529026743568="` echo /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568 `" ) && sleep 0'"'"''
<localhost> (0, b'ansible-tmp-1550434706.6798608-248529026743568=/home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568\n', b'')
Using module file /home/acampesino/ansibleenv/lib/python3.6/site-packages/ansible-2.8.0.dev0-py3.6.egg/ansible/modules/system/setup.py
<localhost> PUT /home/acampesino/.ansible/tmp/ansible-local-14805rku9912w/tmpil9v8wxp TO /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568/AnsiballZ_setup.py
<localhost> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 '[localhost]'
<localhost> (0, b'sftp> put /home/acampesino/.ansible/tmp/ansible-local-14805rku9912w/tmpil9v8wxp /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568/AnsiballZ_setup.py\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'chmod u+x /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568/ /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (0, b'', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 -tt localhost '/bin/sh -c '"'"'/usr/bin/python /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568/AnsiballZ_setup.py && sleep 0'"'"''
<localhost> (0, b'\r\n{"invocation": {"module_args": {"filter": "ansible_local", "gather_subset": ["all"], "fact_path": "/etc/ansible/facts.d", "gather_timeout": 10}}, "ansible_facts": {"ansible_local": {"test": {"empty": "test"}, "other": {"run_error": "facts non readable by running user"}, "znew": {"run_error": "facts non readable by running user"}}}}\r\n', b'Shared connection to localhost closed.\r\n')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/home/acampesino/.ansible/cp/8a5a4c6a60 localhost '/bin/sh -c '"'"'rm -f -r /home/acampesino/.ansible/tmp/ansible-tmp-1550434706.6798608-248529026743568/ > /dev/null 2>&1 && sleep 0'"'"''
<localhost> (0, b'', b'')
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_local": {
            "other": {
                "run_error": "facts non readable by running user"
            },
            "test": {
                "empty": "test"
            },
            "znew": {
                "run_error": "facts non readable by running user"
            }
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_local",
            "gather_subset": [
                "all"
            ],
            "gather_timeout": 10
        }
    }
}
META: ran handlers
META: ran handlers
```

### CODE REVIEW

**Review by bcoca — CHANGES_REQUESTED** [review]
a much simpler fix is to catch the os/io error and add a module.warn about the file and continue processing

**Review by bcoca — CHANGES_REQUESTED** [review]
change is too complex, just capture ioerror/oserror from get_file_content and emit a module.warn

**Comment by ACampesinin** [comment]
I tried to makeit simplier but deciding first if it can be executed or read by user and then just run or execute, returnging warnings using the warn module when issues or problems to read appear.

This approac allows the file to be read or executed even if the user does not own it and the file has no execution rights for the owner.

Hope this approach shuits

**Review by ACampesinin — COMMENTED** [review]
Changed the code in mi latest commit, with a section for checks and a single section for running.

**Comment by s-hertel** [comment]
Thanks for working on this. The issue issue has been fixed in #73804 by just handling the exceptions (and also included tests for the bug).

**Pull request closed without merging**
