### PR TITLE
VMware: Update example connection details when using dvswitch

### PR DESCRIPTION
**Pull request by UnknownGnome**
##### SUMMARY

Update examples to specify vcenter connection details when using dvswitch.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

vmware_vmkernel.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alongchamps** [comment]
LGTM

**Comment by adarobin** [comment]
@UnknownGnome is there a reason you haven't updated all of the examples?  I'm guessing that you're trying to highlight one of the things called out in the notes - "You can only create the VMKernel adapter on a vDS if authenticated to vCenter and not if authenticated to ESXi."

**Review by alongchamps — APPROVED** [review]

**Comment by UnknownGnome** [comment]
@adarobin Yes. The other examples work with esxi credentials because they are updating standard switches. The dvswitch examples do not work unless using vCenter credentials. 
After I submitted this pull request, I saw that ckotte mentioned in his pull request that he needed to update the examples. 
First pull request - forgive me if it's done improperly.

**Review by adarobin — APPROVED** [review]
LGTM

**Comment by acozine** [comment]
Thanks @UnknownGnome for contributing your experience back to the Ansible community.

**Pull request merged**
