### PR TITLE
CLI: ansible-doc shows lists of modules & module docs on command-line

### PR DESCRIPTION
**Pull request by jpmens**
Addresses issues raised in #1660

### CODE REVIEW

**Comment by jpmens** [comment]
## Examples

### ansible-doc -l

```
[...]
supervisorctl        Manage the state of a program or group of programs running v
svr4pkg              Manage Solaris SVR4 packages                                
template             Templates a file out to a remote server.                    
user                 Manage user accounts                                        
virt                 Manages virtual machines supported by libvirt               
wait_for             Waits for a given port to become accessible on a server.... 
yum                  Manages packages with the `yum' package manager             
```

### ansible-doc yum

```
> YUM

  Will install, upgrade, remove, and list packages with the `yum'
  package manager.

Options (= is mandatory):

- disablerepo
        `repoid' of repositories to disable for the install/update
        operation These repos will not persist beyond the transaction
        Multiple repos separated with a ','

- enablerepo
        Repoid of repositories to enable for the install/update
        operation. These repos will not persist beyond the transaction
        multiple repos separated with a ','

- list
        various non-idempotent commands for usage with
        `/usr/bin/ansible' and `not' playbooks. See examples.

= name
        package name, or package specifier with version, like
        `name-1.0'.

- state
        whether to install (`present', `latest'), or remove (`absent')
        a package. (Choices: present, latest, absent)

Notes:

        yum name=httpd state=latest
        yum name=httpd state=removed
        yum name=httpd enablerepo=testing state=installed
```

### ansible-doc -s yum

```

- name: Manages packages with the `yum' package manager
  action: yum
      state=                 # whether to install (`present', `latest'), or remove (`absent
      disablerepo=           # `repoid' of repositories to disable for the install/update o
      list=                  # various non-idempotent commands for usage with `/usr/bin/ans
      name=                  # package name, or package specifier with version, like `name-
      enablerepo=            # Repoid of repositories to enable for the install/update oper
```

**Comment by jpmens** [comment]
man page & Makefile stuff not there yet; will add if this is taken.

**Comment by mpdehaan** [comment]
in queue for review in 1.0

**Comment by jpmens** [comment]
This was built as an 0.9 killer-feature ...
make that "designed to be" ...

**Comment by mpdehaan** [comment]
Can you get the manpages and Makefile stuff (and any packaging changes)
today?

Nothing is really going to be tested on Friday, it's just going out.

**Comment by jpmens** [comment]
Yes I can, and will do as soon as you say this code is okay. :)

**Comment by mpdehaan** [comment]
I'd say go ahead and then update the pull request, I'll probably review
code a bit later.

**Comment by jpmens** [comment]
Added stuff to Makefile and setup.py. Added man page.
Tested with `make sdist` and install on virgin machine. Looks ok to me.

**Comment by mpdehaan** [comment]
Looks much better.   A few things:

(A)

I noticed this when doing "ansible-doc -s template":
- name: Templates a file out to a remote server.
  action: template
      dest=                  # Location to render the template to on the remote machine.
      src=                   # Path of a Jinja2 formatted template on the local server. Thi
      backup=                # Create a backup file including the timestamp information so 
      others=                # all arguments accepted by the [file] module also work here

Basically the descriptions are getting clipped.   What I would do is either NOT trim it at 80 characters (easier) or look into using the textwrap module or something with the descriptions (probably a mess, due it being YAML).

(B)

Here's another thing that I'd like to have it fixed so people don't get confused --  it seems that the --module-path argument might not be working 100%:

```
ansible-doc -s fake -M /tmp

module fake not found in /home/mdehaan/ansible/library
```

In fact,if I feed in a bogus module path, it still works, so it looks like the CLI parameter is not wired up.

(C)

It also seems the version provided to "-V" isn't coming from the regular place as ansible versions, since it is showing the short form.  Basically this should do the same version output as the rest of ansible.  

Getting close... this is very nice to have, and also a lot clearer now that it gives usage messages when you don't know it requires arguments.

**Comment by dhozac** [comment]
B looks expected, line 131 should be something like

```
    for i in options.module_path.split(os.pathsep):
        utils.plugins.module_finder.add_directory(i)
```

It seems to use module_docs in some places, and utils.module_docs in others. Would be less confusing to only use one of those.

-l probably shouldn't list every file, ignoring ~, .bak, .rpm*, would probably be a good idea.

**Comment by jpmens** [comment]
A) I was trimming on purpose, sort of just as a reminder to the person using the 'snippet'. Now uses full length (even though those long lines look ugly to me)

B) fixed, thanks to @dhozac. Also: ignoring a few extensions though seems strange to me as I keep only modules in modules dirs -- probably reason it didn't occur to me ;-)

C) version stuff fixed

**Comment by jpmens** [comment]
ansible-doc is mentioned in 0.9 release Changelog, but this PR hasn't been merged...
Just checked 0.9.tar file and it contains a slightly older version of ansible-doc

On purpose? (Just trying to understand :-)

**Comment by mpdehaan** [comment]
Not on purpose, this is my fault.   We'll get it for 1.0.

**Comment by mpdehaan** [comment]
BTW, looks like this PR needs a rebase?

**Comment by jpmens** [comment]
Why? I did this just like I did all the others ...
There's just one commit in here, as far as I can tell.

**Comment by mpdehaan** [comment]
Because it takes me time to crank out a .1 dot release, and it's a Saturday?

**Comment by jpmens** [comment]
Sorry @mpdehaan: I don't understand.
Gotta go now. Shall try and do whatever has to be done next week, after reading up on how to do a rebase on a PR ...

**Comment by mpdehaan** [comment]
There is actually nothing wrong with your PR.

I'm not sure why it's it didn't get merged back, I likely did something
wrong somewhere.   I'm just hoping to avoid another release unless we have
some bugs that warrant a 0.9.1.

**Comment by jpmens** [comment]
New PR in https://github.com/ansible/ansible/pull/1718 will merge cleanly against current devel

**Comment by mpdehaan** [comment]
closing this as it's in the other ticket now, thanks!

**Pull request closed without merging**
