### PR TITLE
Let's also drop usernames and passwords.

### PR DESCRIPTION
**Pull request by jjshoe**

### CODE REVIEW

**Comment by jjshoe** [comment]
previously: /etc/apt/sources.list.d/bob_qwerty_s3_amazonws_com_my_repo.list
now: /etc/apt/sources.list.d/s3_amazonaws_com_my_repo.list

bob/qwerty being the user pass.

**Comment by jjshoe** [comment]
WARNING: I should note that this fix WILL result in changes being reported for anyone who:

1) Upgrades to the version of ansible this gets released in

AND

2) Runs ansible

AND

3) Uses username and passwords with apt

This change will NOT notify the users in any way that they have a file that anyone can read on disk named with their apt credentials.

**Comment by jjshoe** [comment]
I wouldn't merge this until some discussion happens over here: https://github.com/ansible/ansible/issues/6908

**Comment by mpdehaan** [comment]
So this is good but the ticket in question mentions a bit more that needs to be dealt with -- apologies on duplicate efforts -- though there's a bit more to be done.

Let's continue this discussion on that ticket.

**Pull request closed without merging**
