### PR TITLE
WIP: vmware_guest: Adds idempotence test for vm creation with portgroup

### PR DESCRIPTION
**Pull request by wilmardo**
##### SUMMARY
Ran into issue #38605 I saw no test case. Added one to come one step closer to fixing the issue (TDD).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

### CODE REVIEW

**Comment by wilmardo** [comment]
Does this test run on Shippable? It has an alias but this this should break at the moment.

**Comment by Akasurde** [comment]
> Does this test run on Shippable? It has an alias but this should break at the moment.

No, It is currently commented [here](https://github.com/ansible/ansible/blob/bac19c330196b02b1cdb80a706dadd782d82602d/test/integration/targets/vmware_guest/tasks/main.yml#L25).

**Comment by Akasurde** [comment]
@wilmardo Any news? Do you need any help for me ? Thanks.

**Comment by wilmardo** [comment]
@Akasurde Help is certainly welcome in #38605 ([comment](https://github.com/vmware/govmomi/commit/92ce42442f2948da39bfef201c6bb10186790098)) since I am really stuck there.

I see that your [issue ](https://github.com/vmware/govmomi/issues/979) over at govmomi has been closed. I will push an update with the test enabled, fingers crossed 🤞

**Comment by wilmardo** [comment]
Hmm, the last commit builds nicely but that shouldn't be the case since I ran into #38605. Some path isn't tested, will try to add more parameters to the network field to invoke the non idempotent behavior.

**Comment by wilmardo** [comment]
Does somebody know why this issue doesn't act up on the CI? Is this a difference between the vcsim and baremetal or something unique about our cluster?

Earlier debugging revealed that the module isn't idempotent for me due this part [(link)](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py#L1318):

```python
if nic.device.deviceInfo.summary != network_name:
    nic.device.deviceInfo.summary = network_name
    nic_change_detected = True
````
The debugger reveals this:
```
nic.device.deviceInfo.summary = DVSwitch: 50 33 04 57 f9 21 ef 8e-02 73 43 30 b8 b1 ff b0`
network_name = dv-PROD-RD
````
Which indeed isn't equal so `nic_changed_detected` gets set to True

https://github.com/ansible/ansible/issues/38605#issuecomment-459739899

**Comment by wilmardo** [comment]
Closing and reopening to trigger CI

**Comment by mattclay** [comment]
bot_status

**Comment by wilmardo** [comment]
Back to WIP since there seems to be something reworked for creating the VMs in VCSIM. I will look into this but not today :)

**Pull request closed without merging**
