### PR TITLE
haproxy drain mode fixes #37591

### LINKED ISSUE #37591: HAProxy Drain mode then MAINT not working as expected.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

haproxy
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Ubuntu 16.04
##### STEPS TO REPRODUCE

```  - name: drain mode
    haproxy:
      state: disabled
      host: 'web01'
      socket: /var/run/haproxy/admin.sock
      backend: 'my_backend'
      wait: yes
      drain: yes
      wait_interval: 1
      wait_retries: 60
```

##### EXPECTED RESULTS
ansible has to put web01 in DRAIN Mode, check every second "current session" and when session equal to 0, ansible has to put web01 in MAINT.

##### ACTUAL RESULTS

it always stay in DRAIN 

```
PLAY [haproxy02] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [haproxy02]
TASK [drain mode] **************************************************************
fatal: [haproxy02]: FAILED! => {"changed": false, "msg": "server my_backend/web01 not status 'DRAIN' after 60 retries. Aborting."}
        to retry, use: --limit @/etc/ansible/playbooks/drain-mode-haproxy.retry

PLAY RECAP *********************************************************************
haproxy02                  : ok=1    changed=0    unreachable=0    failed=1
```

Show stat from socket : 
```
my_backend,web01,0,0,0,0,,0,0,0,,0,,0,0,0,0,DRAIN,1,1,0,0,9,225,62500,,1,19,1,,0,,2,0,,0,L7OK,200,19,0,0,0,0,0,0,0,,,,0,0,,,,,-1,HTTP content check matched,,0,0,0,0,
```

Documentation : 
```
# Place server in drain mode, providing a socket file.  Then check the server's
# status every minute to see if it changes to maintenance mode, continuing if it
# does in an hour and failing otherwise.
- haproxy:
    state: disabled
    host: '{{ inventory_hostname }}'
    socket: /var/run/haproxy.sock
    backend: www
    wait: yes
    drain: yes
    wait_interval: 1
    wait_retries: 60
```

I'm using a PHP script doing the same action, look like something is  misunderstood by developper, DRAIN to MAINT is not automatic feature in HAPROXY, you have to send 2 socket commands.

Thanks

Guldil

### PR DESCRIPTION
**Pull request by jorijinnall**
##### SUMMARY
This pull request fixes #37591
This fixes include fix for #30833 as it is needed to start the module

I propose to change a little bit the behaviour :

drain should be used only with the state disabled
we explicitly say that it overrides shutdown_connection parameters. So at the end of the waiting period, we switch to MAINT status

##### ISSUE TYPE
- Bugfix Pull Requet

##### COMPONENT NAME
haproxy.py

##### ADDITIONAL INFORMATION
I tested drain behaviour with a VM and Haproxy installed with web server as backend
```
ansible 2.8.0.dev0 (jori_fix_37591 cb4168c272) last updated 2018/10/04 22:46:24 (GMT +200)
  config file = None
  configured module search path = ['/Users/jdelannoye/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jdelannoye/Projects/Ansible/ansible/lib/ansible
  executable location = ./bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:13:53) [Clang 8.0.0 (clang-800.0.42.1)]
```

### CODE REVIEW

**Review by ravibhure — APPROVED** [review]
+1

**Comment by RyanW19** [comment]
Any update on this PR being approved? Facing the exact issue which this PR resolves. An update would be appreciated

**Comment by elafontaine** [comment]
+1

**Review by ghislainbourgeois — COMMENTED** [review]
I do not think the server will be put in maintenance mode following those changes, as the command to disable the server is only executed in an `elif`. I think this requires more changes, around the `act()` method and the `wait_for_status()` method.

**Pull request closed without merging**
