### PR TITLE
updates eos modules to use socket

### PR DESCRIPTION
**Pull request by privateip**
* updates eos modules to use persistent connection socket
* removes split eos shared module and combines into one
* adds singular eos doc frag (eos_local to be removed after module updates)

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to unit test errors such as this:

```
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/modules/network/eos/test_eos_system.py:32: in <module>
2017-02-09 14:41:27     from ansible.modules.network.eos import eos_system
2017-02-09 14:41:27 lib/ansible/modules/network/eos/eos_system.py:160: in <module>
2017-02-09 14:41:27     from ansible.module_utils.eos import load_config, get_config
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 _______ ERROR collecting test/units/modules/network/eos/test_eos_user.py _______
```

**Comment by gundalow** [comment]
```
2017-02-09 14:41:27 ==================================== ERRORS ====================================
2017-02-09 14:41:27 _____________ ERROR collecting test/units/module_utils/test_eos.py _____________
2017-02-09 14:41:27 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/module_utils/test_eos.py'.
2017-02-09 14:41:27 Hint: make sure your test modules/packages have valid Python names.
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/module_utils/test_eos.py:29: in <module>
2017-02-09 14:41:27     from ansible.module_utils import eos
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 ______ ERROR collecting test/units/modules/network/eos/test_eos_banner.py ______
2017-02-09 14:41:27 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_banner.py'.
2017-02-09 14:41:27 Hint: make sure your test modules/packages have valid Python names.
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/modules/network/eos/test_eos_banner.py:26: in <module>
2017-02-09 14:41:27     from ansible.modules.network.eos import eos_banner
2017-02-09 14:41:27 lib/ansible/modules/network/eos/eos_banner.py:111: in <module>
2017-02-09 14:41:27     from ansible.module_utils.eos import load_config, run_commands
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 _____ ERROR collecting test/units/modules/network/eos/test_eos_command.py ______
2017-02-09 14:41:27 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_command.py'.
2017-02-09 14:41:27 Hint: make sure your test modules/packages have valid Python names.
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/modules/network/eos/test_eos_command.py:28: in <module>
2017-02-09 14:41:27     from ansible.modules.network.eos import eos_command
2017-02-09 14:41:27 lib/ansible/modules/network/eos/eos_command.py:134: in <module>
2017-02-09 14:41:27     from ansible.module_utils.eos import run_commands, eos_argument_spec
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 ______ ERROR collecting test/units/modules/network/eos/test_eos_config.py ______
2017-02-09 14:41:27 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_config.py'.
2017-02-09 14:41:27 Hint: make sure your test modules/packages have valid Python names.
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/modules/network/eos/test_eos_config.py:31: in <module>
2017-02-09 14:41:27     from ansible.modules.network.eos import eos_config
2017-02-09 14:41:27 lib/ansible/modules/network/eos/eos_config.py:224: in <module>
2017-02-09 14:41:27     from ansible.module_utils import eos
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 _______ ERROR collecting test/units/modules/network/eos/test_eos_eapi.py _______
2017-02-09 14:41:27 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_eapi.py'.
2017-02-09 14:41:27 Hint: make sure your test modules/packages have valid Python names.
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/modules/network/eos/test_eos_eapi.py:32: in <module>
2017-02-09 14:41:27     from ansible.modules.network.eos import eos_eapi
2017-02-09 14:41:27 lib/ansible/modules/network/eos/eos_eapi.py:200: in <module>
2017-02-09 14:41:27     from ansible.module_utils.eos import run_commands, load_config
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 ______ ERROR collecting test/units/modules/network/eos/test_eos_system.py ______
2017-02-09 14:41:27 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_system.py'.
2017-02-09 14:41:27 Hint: make sure your test modules/packages have valid Python names.
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/modules/network/eos/test_eos_system.py:32: in <module>
2017-02-09 14:41:27     from ansible.modules.network.eos import eos_system
2017-02-09 14:41:27 lib/ansible/modules/network/eos/eos_system.py:160: in <module>
2017-02-09 14:41:27     from ansible.module_utils.eos import load_config, get_config
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 _______ ERROR collecting test/units/modules/network/eos/test_eos_user.py _______
2017-02-09 14:41:27 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_user.py'.
2017-02-09 14:41:27 Hint: make sure your test modules/packages have valid Python names.
2017-02-09 14:41:27 Traceback:
2017-02-09 14:41:27 test/units/modules/network/eos/test_eos_user.py:26: in <module>
2017-02-09 14:41:27     from ansible.modules.network.eos import eos_user
2017-02-09 14:41:27 lib/ansible/modules/network/eos/eos_user.py:166: in <module>
2017-02-09 14:41:27     from ansible.module_utils.eos import get_config, load_config
2017-02-09 14:41:27 lib/ansible/module_utils/eos.py:39: in <module>
2017-02-09 14:41:27     from ansible.module_utils.network_common import exec_command
2017-02-09 14:41:27 E   ImportError: cannot import name exec_command
2017-02-09 14:41:27 !!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!
2017-02-09 14:41:27 ====================== 2 skipped, 7 error in 2.85 seconds ======================
```

**Comment by mattclay** [comment]
CI failure due to unit test errors:

```
2017-02-10 01:10:02 ==================================== ERRORS ====================================
2017-02-10 01:10:02 ______ ERROR collecting test/units/modules/network/eos/test_eos_config.py ______
2017-02-10 01:10:02 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_config.py'.
2017-02-10 01:10:02 Hint: make sure your test modules/packages have valid Python names.
2017-02-10 01:10:02 Traceback:
2017-02-10 01:10:02 test/units/modules/network/eos/test_eos_config.py:31: in <module>
2017-02-10 01:10:02     from ansible.modules.network.eos import eos_config
2017-02-10 01:10:02 lib/ansible/modules/network/eos/eos_config.py:210: in <module>
2017-02-10 01:10:02     from ansible.module_utils.eos import supports_sessions, run_commands
2017-02-10 01:10:02 E   ImportError: cannot import name supports_sessions
2017-02-10 01:10:02 !!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by mattclay** [comment]
CI failure due to import failure in unit tests:

```
2017-02-10 15:07:22 ==================================== ERRORS ====================================
2017-02-10 15:07:22 ______ ERROR collecting test/units/modules/network/eos/test_eos_config.py ______
2017-02-10 15:07:22 ImportError while importing test module '/root/src/github.com/ansible/ansible/test/units/modules/network/eos/test_eos_config.py'.
2017-02-10 15:07:22 Hint: make sure your test modules/packages have valid Python names.
2017-02-10 15:07:22 Traceback:
2017-02-10 15:07:22 test/units/modules/network/eos/test_eos_config.py:27: in <module>
2017-02-10 15:07:22     from ansible.modules.network.eos import eos_config
2017-02-10 15:07:22 lib/ansible/modules/network/eos/eos_config.py:210: in <module>
2017-02-10 15:07:22     from ansible.module_utils.eos import supports_sessions, run_commands
2017-02-10 15:07:22 E   ImportError: cannot import name supports_sessions
```

**Comment by gundalow** [comment]
Same comments as on https://github.com/ansible/ansible/pull/21231

**Pull request merged**
