### PR TITLE
win_shortcut: Clean up parameter handling

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_shortcut

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Minor changes.

### CODE REVIEW

**Comment by dagwieers** [comment]
ready_for_review

**Comment by dagwieers** [comment]
shipit

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by jhawkesworth** [comment]
nice cleanup.

shipit

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
bot_status

**Pull request merged**
