### PR TITLE
add the dependency markupsafe

### PR DESCRIPTION
**Pull request by larsborn**
this dependency seems to be missing

### CODE REVIEW

**Comment by sivel** [comment]
I believe markupsafe is a dependency of jinja2, we should not need to be explicit about it.

https://github.com/mitsuhiko/jinja2/blob/master/setup.py#L75

**Comment by larsborn** [comment]
hm that's odd. I just installed ansible on a fresh raspbian machine with the following commands

```
aptitude install python-pip
pip install ansible
```

and got the error, that markupsafe is missing. As I understand pip, this should not happen, right? Even more odd:

```
pip install markupsafe
```

solved the problem.

**Comment by abadger** [comment]
Did jinja2 come from raspbian package or did the pip install ansible install jinja2?

**Comment by larsborn** [comment]
Since 

```
aptitude search jinja2
```

does not show any installed jinja2 package, I assume that

```
pip install ansible
```

installed jinja2. How can I be of more help?

**Comment by amenonsen** [comment]
I guess this PR can be closed now, since there has been no further correspondence.

**Comment by bcoca** [comment]
This then seemed like a pip issue of not pulling down the dependencies from jinja2. Testing on debian/ubuntu downloads markupsafe when you install jinja and again when you install ansible and the dependency resolution pulls in jinja2 and it's dependencies, including markupsafe. 

So this is either a problem with pip and raspian or the raspian version of pip not downloading the whole dependency tree.

I tried getting raspian on qemu but most of the links on the guides are dead and i'm not going to spend the time to cross compile a custom arm kernel. I suggest opening an issue with the raspian packagers about pip not pulling in dependencies correctly.

As for this issue i'm closing it for now, feel free to open a new one and point to this one if there is something that points to Ansible not stating it's dependencies correctly, but I do not think that is the case right now.

**Comment by larsborn** [comment]
sounds reasonable :)

**Pull request closed without merging**
