### PR TITLE
nsupdate: Use provided TSIG key for all queries

### PR DESCRIPTION
**Pull request by andreaso**
##### SUMMARY

In addition to signing update queries also use the TSIG key to sign
lookup queries. By doing that we allow a hidden master to not only to
be looked down network wise, but also TSIG wise.

A bonus benefit of threating update queries and lookup queries more
the same is that will allow for all queries to be refactored into a
shared helper method. Currently we have a bit too much duplicated code
within the module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
nsupdate

### CODE REVIEW

**Comment by andreaso** [comment]
@nerzhul: Thoughts?

**Comment by andreaso** [comment]
@Akasurde, @resmo: Any interest in taking a look at this PR?

**Comment by t3hpr1m3** [comment]
I just hacked this together locally, and found this before submitting a PR.  Any way this can be merged?

**Comment by andreaso** [comment]
@t3hpr1m3: Take it then that you have tried out the PR changes, that they work well for you, etc?

@Akasurde, @nerzhul, @resmo: Any chance for a review, and hopefully a _shipit_, from any of you?

**Comment by t3hpr1m3** [comment]
@andreaso I have, and everything still works as intended (including the modifications).

**Review by resmo — APPROVED** [review]
LGTM

**Pull request merged**
