### PR TITLE
Integration tests for route53_zone

### PR DESCRIPTION
**Pull request by prasadkatti**
##### SUMMARY
Integration tests for route53_zone

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
`route53_zone`

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by prasadkatti** [comment]
@mattclay - This PR needs some permissions to be granted to the CI account.

I have 'AmazonRoute53FullAccess' policy attached to the IAM user I use for developing this testsuite. I don't know the specific permissions that are needed for this. :(

**Comment by prasadkatti** [comment]
@mattclay - Hi. Any update on this?

**Comment by mattclay** [comment]
@prasadkatti It's currently in our [backlog](https://github.com/ansible/ansible/labels/needs_ci_update) of AWS tests which require CI permissions updates.

**Review by s-hertel — APPROVED** [review]

**Comment by prasadkatti** [comment]
@s-hertel - Thanks for fixing some of the tests.

**Comment by s-hertel** [comment]
Thanks for adding them!

**Comment by prasadkatti** [comment]
@s-hertel  - I have identified a few more test cases that can be added here. But since, you have already approved the PR, I am not sure what the protocol is. Should I wait for this to be merged in as-is and then add the new tests in a separate PR?

**Comment by prasadkatti** [comment]
Hi. Can we merge this PR in? I am planning to work on migrating route53_zone to boto3 in the next couple of weeks and it would help if this was already merged in.

**Comment by prasadkatti** [comment]
Closing this as the tests have already been added in #36641

**Pull request closed without merging**
