### PR TITLE
junos scp module

### PR DESCRIPTION
**Pull request by GIC-de**
##### SUMMARY
The `junos_scp` module transfers files via SCP from or to remote devices running Junos. 

Example Usage:
```
  - name: upload file to device
    junos_scp:
        src: /tmp/test.text
        provider: "{{ provider }}"
```

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
- `lib/ansible/modules/network/junos/junos_scp.py`

##### ANSIBLE VERSION
```
ansible 2.3.2.0
```

### CODE REVIEW

**Comment by gundalow** [comment]
@GIC-de As of Ansible 2.4 all Network modules require tests, Can you please add a unit and integration test for this. Thanks in advance.

**Comment by gundalow** [comment]
New functionality freeze for Ansible 2.5 is 15th Jan. If you need assistance with any of this feel free to reach us in `#ansible-network` on Freenode IRC.

**Comment by GIC-de** [comment]
I need help with the failed sanity check. Locally the test was working but it failed in your environment. The error is confusing because this part of the code (`import ansible.mudle_utils.junos...`) is 100% equal to the existing modules like `junos_package`.

**Comment by gundalow** [comment]
Our CI (Shippable) rebase PRs before running tests. I believe you are seeing this as in the `devel` branch'`module_utils` has been reorganized. 

I believe you need to rebase this PR. After that you will nerd something like `module_utils.networking.{platform}`

**Comment by gundalow** [comment]
http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

**Comment by ganeshrn** [comment]
@GIC-de After rebase you need to update import statement as `ansible.module_utils.network.junos.junos`
Reference: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/junos/junos_command.py#L175

**Review by ganeshrn — APPROVED** [review]

**Comment by gundalow** [comment]
rebuild_merge

**Review by gundalow — APPROVED** [review]

**Pull request merged**
