### PR TITLE
Adding daemontools module

### PR DESCRIPTION
**Pull request by bcoca**
works with DJB version but can be subclassed to add features
for encore, s6, runit, etc. Then introduce the distro='classname'
parameter to switch between them.

Signed-off-by: Brian Coca <briancoca+dev@gmail.com>

### CODE REVIEW

**Comment by mpdehaan** [comment]
Should this be part of the service module?

I worry that a module named 'svc' seems confusing.

**Comment by bcoca** [comment]
It can go either way, same could be said for superviserctld.

svc is the name of the command line tool daemontools and derivatives use to
control the system, I'm open to any name that would both be informational
and avoids confusion.

**Comment by jimi-c** [comment]
I do see your point about supervisorctl, and I see why you named it svc after doing some reading on daemontools, however I think that the module should be renamed regardless of the underlying command. Making it `daemontools` would seem to be more appropriate.

**Comment by bcoca** [comment]
the only reason i didn't call it daemontools is because there are many
derivatives that use the same tool names but are called differntly (ie
runnit, encore). But I'm fine with the rename.

**Comment by hynek** [comment]
JFTR, it seems to me that nowadays runit is the by far most used derivative so it would be great if that would have been taken into account from the begin on. IOW please don’t make it awkward to use in the common case or findable only for people who know its pedigree. :)

**Comment by bcoca** [comment]
@Hynek, I personally know mostly people that use daemontools or encore, I
know of runit and others like s6 so I constructed the module to be easy to
subclass for each particular derivative.

If you are currently using runit and can give me some feedback on
missing/broken features I'll be happy to update the module but I don't have
it setup for testing so it can be a longinsh dev cycle.

**Comment by bcoca** [comment]
so to confirm, rename to daemontools and resubmit?

**Comment by mpdehaan** [comment]
go for it!

**Comment by grembo** [comment]
@bcoca Did you ever resubmit?

**Comment by bcoca** [comment]
No, I haven't had the time, it is very messy to integrate into service
module and as a separate module it has been meeting my needs well, giving
me little incentive to work on it.

**Pull request closed without merging**
