### PR TITLE
allow invoking clis through keywords

### PR DESCRIPTION
**Pull request by bcoca**
allows for invoking `ansible-playbook` as `ansible playbook`, etc

### CODE REVIEW

**Comment by sivel** [comment]
What happens if you have host called "playbook", "vault", "doc", etc...?

Normal running of the Ansible command allows use of a positional arg which is the hostname.

```
ansible playbook -i hosts -m ping
```

The above in the past would allow you to run against a host called "playbook".  This change introduces a reserved list of hosts/limits at this point which could be unexpected

Also the use of `.find` isn't very pythonic.

**Comment by bcoca** [comment]
Yes, this will break adhoc with hosts named doc, playbook and vault (or any other new command line names), the find i can change to `'-' in ...`.

**Comment by tima** [comment]
+1. More of this please.

**Comment by bcoca** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. 

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
