### PR TITLE
Add module to manage Go packages

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Add module to manage Go packages

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/packaging/language/go.py

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by sivel** [comment]
@kenorb have you had the opportunity to test this module?

**Comment by sivel** [comment]
@kenorb just checking in to see if you have had a chance to try this module and see if it meets your needs.

**Comment by kenorb** [comment]
Sorry for delay. Didn't, keep forgetting, busy life, changing laptops, losing laptops, changing OSes, travelling. I'll back to _Docker_ next week and I hope I manage to test it. Pinned this tab to not forget.

**Comment by ccauet** [comment]
Any status update on this?

**Comment by sivel** [comment]
@ccauet No. No one has reviewed the functionality of this PR to indicate whether it meets their needs. Would you mind trying it?

**Comment by ccauet** [comment]
@sivel 

> Would you mind trying it?

Means? Install ansible branch by hand and testing the module?

**Comment by sivel** [comment]
How you test it is up to you.  You can install the branch for this PR, or simply download the file from this PR and place it in a directory called `library` adjacent to your playbook where you use it.

**Comment by ccauet** [comment]
> ...or simply download the file from this PR and place it in a directory called library adjacent to your playbook where you use it.

That's a good hint.

**Comment by sivel** [comment]
Due to lack of reviews, this module has instead been published to https://galaxy.ansible.com/sivel/toiletwater

**Pull request closed without merging**
