### PR TITLE
Add Icinga2 module to manipulate hosts

### PR DESCRIPTION
**Pull request by tux-00**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
icinga2_host

##### ANSIBLE VERSION
```
ansible 2.3.0 (icinga2_module 565e83d687) last updated 2017/01/03 19:44:23 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
This module allows to add or modify an host in Icinga2 using the API.

The module bypass the ca cert to request the API.

### CODE REVIEW

**Comment by nerzhul** [comment]
Please note Icinga2 repository API is deprecated, for this reason i'm not sure this module is useful

**Comment by tux-00** [comment]
The module only use the API. What is depracated is the "icinga2 repository" command.

**Comment by nerzhul** [comment]
Okay thanks for the clarification

**Comment by nerzhul** [comment]
duplicate_of #31720
duplicate_of #19826

**Comment by tux-00** [comment]
Maybe we can close this PR as @t794104 is going to merge #31720

**Comment by nerzhul** [comment]
I agree to close this PR @tux-00 , go ahead :)

**Pull request closed without merging**
