### PR TITLE
Feature: file info on templates accessible to Jinja2 templates

### PR DESCRIPTION
**Pull request by jpmens**
This was requested recently on IRC (and on the mailing-list?), and I find it very useful for tracing where a templated file originates from and when it was last modified.

Consider the following template:

``` jinja2

# {{ template_path }} on {{ template_host }}, modified on {{ template_mtime }} by {{ template_uid }}

hello
```

This will now render into something like this:

```
# templ.in on box.example.com, modified on 2012-10-02 11:50:08 by jpm

hello 
```

### CODE REVIEW

**Comment by tonk** [comment]
Hello JP,

It's me who requested this and I second this. For debugging and tracking this is a VERY nice to have.

Unfortunately I am not fluent enough in Python to code it myself.

**Comment by tonk** [comment]
Tried it with the patch applied and I really like what I'm seeing.

Would it be possible to make the time/date format configurable through ansible.cfg? If not, I settle for this.

**Comment by jpmens** [comment]
Sure, we could do that. I was actually thinking of offering ISO timestamps only...

Let's see what @mpdehaan says about this. :)

BTW: maybe I should prefix these variables with a `_` so as to try to not clobber variables users would typically set.

**Comment by jpmens** [comment]
Some people may not want/need this, of course. Thinking a bit further, how about `ansible.cfg` has an optional setting (something like `template_vars = /path/to/abc.py`) which, if set, causes that to be loaded as a module and augments whatever is in `util.py`'s vars?

utils.py would then:

``` python
    try:
        plugin = imp.load_source('xx', '/path/to/abc.py')
        extravars = plugin.template_vars(path)
        vars.update(extravars)
    except:
        pass
```

That allows people to (e.g.) set the timestamps however they want, and also include whatever else they wish. Instead of `vars.update()` (which could clobber existing variables) we could add variables only if they aren't yet in `vars`.

**Comment by mpdehaan** [comment]
I would extend this by making an additional variable that summarizes all of these facts.

$ansible_managed

that is a shortcut to all of that in one string.   This keeps templates and documentation much simpler.   We can mention $ansible_managed in the module doc notes section for template.

I disagree that we need a template_vars binary file at this time, that's an over complication for now, what we need to is just make a timestamp_format config file setting and use that via the usual constants.py logic.   However let's not do this now and get this all merged in first.

**Comment by jpmens** [comment]
Added $ansible_managed; good idea, thanks.

**Comment by mpdehaan** [comment]
Great, merging.... I would also lead in this string with "Ansible managed:" :)

will tweak if I remember

**Comment by jpmens** [comment]
I'd prefer no lead-in, but whatever.

**Comment by jpmens** [comment]
@tonk FYI: this feature is now part of Ansible; thanks for the idea.

**Comment by mpdehaan** [comment]
it's like viral advertising for extremely poor people

**Comment by tonk** [comment]
I cannot remember seeing things evolve that fast, Wow, what a service.
It still works as JP started it?

**Comment by jpmens** [comment]
Unchanged except for the addition of `$ansible_managed` (or `{{ ansible_managed }}` which summarizes all new variables. We'll do the time-format thing some time later. Perhaps. :)

**Comment by mpdehaan** [comment]
yeah I don't think it's urgent.   thanks!

**Comment by jpmens** [comment]
I take it all back, @mpdehaan: It **should** report `Ansible managed:`.

**Pull request merged**
