### PR TITLE
Update win_package.py

### PR DESCRIPTION
**Pull request by dexpl**
##### SUMMARY

Replaced wrong registry paths with correct ones (HKLM:\, not HKLM:).

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @dexpl for the Ansible documentation fix!

**Comment by samccann** [comment]
@dexpl  - just noticed this microsoft document does not include the colon in its sample:

https://support.microsoft.com/en-us/help/247501/how-to-manually-remove-programs-from-the-add-remove-programs-list

HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall

I'm inclined to open another PR to remove the colon unless you know of a reason to keep it?

**Comment by dexpl** [comment]
> I'm inclined to open another PR to remove the colon unless you know of a reason to keep it?

I think I know a good reason to keep it: win_reg_stat module correctly processes 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall' but fails with both colonless HKLM and HKEY_LOCAL_MACHINE. Not sure whether win_reg_stat should work over the latter one though.

**Comment by dexpl** [comment]
> HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall

And yes, reg.exe accepts such paths OK, so maybe win_reg_stat should too?

**Comment by samccann** [comment]
Thanks @dexpl - seems like the documentation is correct anyway. Not sure who could answer your question on whether the module code should accept the alternatives, though..

**Comment by ShachafGoldstein** [comment]
The colon comes from the use of powershell providers to handle registry paths, it is required when using powershell commands. If a module uses other binaries it might take the path without the colon (pre powershell times)

**Comment by samccann** [comment]
Thanks @ShachafGoldstein for the explanation!

**Pull request merged**
