### PR TITLE
Fixes #47256 - added include=all_parameters and removed the redundant…

### LINKED ISSUE #47256: [RFE] Improve Foreman Dynamic Inventory by Leveraging include=all_parameters
##### SUMMARY
Newer versions of Foreman allow for include=all_parameters, which allows us to pull parameters back in the initial API calls and parse in memory.  This prevents from having to make several subsequent API calls back to the Foreman API to pull all_parameters.  This isn't awful for small environments, but it doesn't scale well for large environments (currently testing against 1500 hosts in Foreman and it takes 3 mins).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/plugins/inventory/foreman.py

##### ADDITIONAL INFORMATION
See summary above.

This same concept should be applied to facts as well.  Currently, include=facts is not implemented in the Foreman API.

### PR DESCRIPTION
**Pull request by scottd018**
… API call which was used to pull in all_parameters

##### SUMMARY
added include=all_parameters to the base API call and removed the redundant call to the /api/v2/hosts/<ID> endpoint

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by ekohl** [comment]
Could you have a look at implementing this in lib/ansible/plugins/inventory/foreman.py?

**Comment by scottd018** [comment]
@ekohl Looking at it right now

**Comment by scottd018** [comment]
@ekohl submitted a separate pull request for this at https://github.com/ansible/ansible/pull/59455 ....apologies for the newb-ness here if I did this wrong.

**Comment by Akasurde** [comment]
Hi @scottd018, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/theforeman/foreman-ansible-modules<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br>

**Pull request closed without merging**
