### PR TITLE
Add testsuite for vmware_maintenancemode

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
test/integration/targets/vmware_maintenancemode/tasks/main.yml
test/integration/targets/vmware_maintenancemode/aliases

##### ANSIBLE VERSION
```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@mattclay We will need latest changes of vcenter-simulator to run these tests. Could you please re-spin vcenter-simulator docker image ?

**Comment by Akasurde** [comment]
ready_for_review

**Review by dagwieers — APPROVED** [review]
Nobody can be against more integration tests. LGTM

**Comment by Akasurde** [comment]
@dagwieers Thanks for review and merge.

**Comment by mattclay** [comment]
@Akasurde The updated vcenter-simulator was causing vmware test failures, so I've pinned the simulator to the previous version in https://github.com/ansible/ansible/pull/31210. Since this test requires the newer simulator it has been disabled. We can switch to a newer version of the simulator (and re-enable this test) once the tests are passing on the new simulator.

**Pull request merged**
