### PR TITLE
Optionally fail task on undefined variables

### PR DESCRIPTION
**Pull request by lorin**
This patch introduces a new configuration option called `error_on_undefined_vars`, which defaults to false.

If this option is set to true, then a task which has unevaluated variables in its arguments will fail instead of running. Output looks like this:

```
TASK: [set rabbitmq password] *************************************************
fatal: [10.20.0.7] => Undefined variables: rabbitmq_user, rabbitmq_password
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this.   I like this idea of having this capability.

The check for undefined variables seems a little sketchy for me because it looks for "{{" where it should be doing Jinja2 things at the last possible instant to see if Jinja2 expressions cause undefined errors.

The example.cfg should also mention this as this is what the RPM lays down so people don't have to look in the code to figure out what the variables are.   It should be off by default to coincide with current behavior.

It should also be made to work for templates at the same time so we don't accept a patch half implemented.   

Aka there can't be a "in the future", they need to come together :)

I also do not want a command line switch added, seems unneeded.

**Comment by lorin** [comment]
I'm happy to make these changes, but I'm having a hard time figuring out where the final Jinja2 template evaluation happens. Is it in Runner._executor_internal_inner?

**Comment by mpdehaan** [comment]
Yes, it should be these:

```
  # render module_args and complex_args templates
    module_args = template.template(self.basedir, module_args, inject)
    complex_args = template.template(self.basedir, complex_args, inject)
```

normal.py or low_level_execute_command doesn't do any templating so that should be "last touch".

Would be reasonably easy to figure out I'd think with some old-school print based debugging and putting a 'print hi' in the template function and another print before and after the call to the template function you think is it :)

So we'd want to add a "fail_on_undefined=boolean" flag I'd think, to these functions.

Template module should be easier to track down (template.py)

Thanks!

**Comment by lorin** [comment]
(Not ready yet, just bringing it up to date with devel).

**Comment by lorin** [comment]
This is now ready for review, now does checks against templated arguments and use of the template module.

**Comment by ipauldev** [comment]
FYI, I also added similar functionality, I believe here: https://github.com/ipauldev/ansible You could have a look and see if it's of any help. Good luck!

**Comment by mpdehaan** [comment]
@lorin -- off topic, but please do not tweak whitespace in future patches, makes it harder to read the diffs.  Thanks!

**Comment by mpdehaan** [comment]
Also, try to avoid merge commits in the history.

Use git pull --rebase and git rebase vs git pull and git merge.

**Comment by mpdehaan** [comment]
manually merged w/ squash commit, thanks!  glad to see this!

**Comment by lorin** [comment]
@mpdehaan Noted.

**Pull request closed without merging**
