### PR TITLE
docker module_docs_fragment should also be community supported and maintained by $team_docker

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
It is currently support:core and not maintained by $team_docker.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
@DBendit I can include you into $team_docker if you are interested.

**Comment by DBendit** [comment]
@felixfontein Go for it. It'll give me good motivation to figure out the rest of the modules :)

**Comment by felixfontein** [comment]
@DBendit cool! Done :)

**Review by DBendit — APPROVED** [review]
LGTM

**Review by dagwieers — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@dagwieers thanks for merging!
@DBendit welcome to the team! ;)

**Pull request merged**
