### PR TITLE
ACI: Change RETURN output as discussed

### LINKED ISSUE #35304: aci: Decide on default RETURN values and parameter to influence
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
aci modules

##### ANSIBLE VERSION
v2.5

##### SUMMARY
Currently our dedicated ACI modules return quite some internal information that probably does not need to be exposed. Depending on how the module is being used, different information is shared:

```markdown
|---------------|-------------------|---------|---------|-------------------|
|               |      present      | modify  |         |      absent       |
|               |first run|  again  |existing |  query  |first run|  again  |
| return key    | CM | NM | CM | NM | CM | NM |one |all | CM | NM | CM | NM |
|---------------|----|----|----|----|----|----|----|----|----|----|----|----|
| attempts      | 1  | 1  | 1  | 1  | 1  | 1  | 1  | 1  | 1  | 1  | 1  | 1  |  <-- Added by task executor ?
| changed       |yes |yes | no | no |yes |yes | no | no |yes |yes | no | no |
| config        | X  | X  | {} | {} | X  | X  |    |    |    |    |    |    |  <-- INFO
| error_code    |    | 0  |    |    |    | 0  |    |    |    | 0  |    |    |  <-- Remove
| error_text    |    |Succ|    |    |    |Succ|    |    |    |Succ|    |    |  <-- Remove
| existing      | [] | [] | X  | X  | X  | X  | X  | X  | X  | X  | [] | [] |  <-- INFO
| filter_string | X  | X  | X  | X  | X  | X  | "" | "" | X  | X  | X  | X  |  <-- DEBUG
| imdata        |    | [] |    |    |    | [] |    |    |    | [] |    |    |  <-- Remove
| method        |POST|POST|GET |GET |POST|POST|GET |GET |DELE|DELE|GET |GET |  <-- DEBUG
| path          | X  | X  | X  | X  | X  | X  | X  | X  | X  | X  | X  | X  |  <-- DEBUG
| proposed      | X  | X  | X  | X  | X  | X  |    |    | {} | {} | {} | {} |  <-- INFO
| response      | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK |  <-- DEBUG
| state         |abse|abse|abse|abse|abse|abse|abse|abse|abse|abse|abse|abse|  <-- Added by task executor ?
| status        |200 |200 |200 |200 |200 |200 |200 |200 |200 |200 |200 |200 |  <-- DEBUG
| totalCount    |    |"1" |    |    |    |"0" |    |    |    |"1" |    |    |  <-- Remove
| url           | X  | X  | X  | X  | X  | X  | X  | X  | X  | X  | X  | X  |  <-- DEBUG
|---------------|----|----|----|----|----|----|----|----|----|----|----|----|

  CM means check-mode (so Ansible does not make a real change, it pretends it did)
  NM means normal-mode
  X means that a proper data-structure is returned.
```

So the above table shows grave differences and inconsistencies:
- The keys `imdata` and `totalCount` are useless, we should get rid of it. (leftover from aci_rest)
- The keys `attempts` and `state` are new and seem to be added by the task executor. Seems unfortunate.
- The keys `error_code` and `error_text` are useless too, we should report errors, but through a proper failure.
- The keys `filter_string`, `method`, `response`, `status` and `url` relate to lower level HTTP calls and should only be shown when specifically asked for (DEBUG)

So what remains to be discussed are the keys `config`, `existing` and `proposed`.
- Key `config` holds the configuration we are pushing
  - Only when we expect a change to be needed, otherwise it is empty
  - On remove it's missing (bad design --> needs fixing)
- Key `existing` holds the configuration (pre-change)
  - It is empty [] when no values exist, which is fine
- Key `proposed` holds the configuration we are *proposing* (in comparison)
  - It is missing when doing a query (bad design --> needs fixing)

Now, in my opinion, the modules should not expose `config`, `existing` and `proposed` for 2 reasons:
- Ansible users expect to get the resulting state (post-change) in results, not the existing state (pre-
change)
  - We currently do not expose the resulting state, this requires another lookup
  - The actual changes are available when using --diff
- Having more than one dictionary with (possible extended output) may be confusing users, especially as the JSON output is returned in a single blob

We could add a new parameter (e.g. `return_output: info`) that influences the resulting output so that `config`, `existing` and `proposed` is returned to the user for troubleshooting purposes or advanced use maybe ? (INFO)

Here is an example of the most comprehensive output.

__TASK [aci_tenant : Change description of tenant again (normal mode)] ***********__
```json
{
    "attempts": 1, 
    "changed": true, 
    "config": {
        "fvTenant": {
            "attributes": {
                "descr": "Ansible test tenant"
            }
        }
    }, 
    "error_code": 0, 
    "error_text": "Success", 
    "existing": [
        {
            "fvTenant": {
                "attributes": {
                    "descr": "", 
                    "dn": "uni/tn-ansible_test", 
                    "name": "ansible_test", 
                    "nameAlias": "", 
                    "ownerKey": "", 
                    "ownerTag": ""
                }
            }
        }
    ], 
    "failed": false, 
    "filter_string": "?rsp-prop-include=config-only", 
    "imdata": [], 
    "invocation": {
        "module_args": {
            "certificate_name": null, 
            "description": "Ansible test tenant", 
            "host": "sandboxapicdc.cisco.com", 
            "method": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "private_key": null, 
            "protocol": "https", 
            "state": "present", 
            "tenant": "ansible_test", 
            "timeout": 30, 
            "use_proxy": false, 
            "use_ssl": true, 
            "username": "admin", 
            "validate_certs": false
        }
    }, 
    "method": "POST", 
    "path": "api/mo/uni/tn-ansible_test.json", 
    "proposed": {
        "fvTenant": {
            "attributes": {
                "descr": "Ansible test tenant", 
                "name": "ansible_test"
            }
        }
    }, 
    "response": "OK (30 bytes)", 
    "state": "absent", 
    "status": 200, 
    "totalCount": "0", 
    "url": "https://sandboxapicdc.cisco.com/api/mo/uni/tn-ansible_test.json"
}

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:
- A cleanup of RETURN values for all ACI modules
- Add parameter `output_level` to influence RETURN detail
- Support ANSIBLE_DEBUG or `--debug` option
- Remove path information from output (to avoid magic `state: absent` result)
- Add RETURN documentation to all modules

This fixes #35304  

##### ISSUE TYPE
 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME
aci modules

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by jmcgill298** [comment]
@dagwieers my only hesitation is using `current`. I personally would not be confident if that meant before or after task execution.

**Comment by dagwieers** [comment]
@jmcgill298 My proposal was `existing` vs `original`. I am still open for better suggestions.

**Comment by jmcgill298** [comment]
I thought `before` and `after` were clear and concise

**Comment by dagwieers** [comment]
@jmcgill298 The problem with `before` and `after` is that I want to have the **resulting** configuration to be returned with the same key for both changes as well as queries.

And I don't want to return `after` for a query... So the `after` key really should be something that also fits the output of a query. `current` and `existing` fulfilled this requirement.

**Pull request merged**
