### PR TITLE
Ec2 instance fix sg

### LINKED ISSUE #54174: ec2_instance cannot add or remove addition security groups
##### SUMMARY
I have an existing ec2 instance where I would like to add an addition security group.  
When I add one more security group, `ec2_instance` doesn't notify any change.

```
TASK [try to modify the ec2 instance] ********************************************************************************************************************************************************
ok: [localhost]
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`ec2_instance`

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = None
  configured module search path = ['/home/m/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/m/.local/lib/python3.7/site-packages/ansible
  executable location = /home/m/.local/bin/ansible
  python version = 3.7.2 (default, Mar 20 2019, 08:51:28) [GCC 8.2.0]

```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$ 

```

##### OS / ENVIRONMENT

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Pop!_OS 18.10"
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  
  vars_prompt:
    - name: ec2_template
      prompt: Which ec2 template file?
      private: no
      default: mbtest190321.my.instance.de

  vars_files:
    - "vars/{{ ec2_template }}.yml"

  tasks:

    ###################################
    #
    # check if instance exists already
    ###################################
    - name: check if instance already exists
      include_role:
        name: start_stop_terminate
        tasks_from: find_instance_id

    ###################################
    # if exists     when: instance.instances | count == 1
    # try update using ec2_instance module
    ###################################
    - name: try to modify the ec2 instance
      ec2_instance:
        state: present
        name: "{{ ec2_template }}"
        instance_ids: "{{ instance.instances[0].instance_id }}"
        security_groups: "{{ security_group }}"
        cpu_credit_specification: "{{ cpu_credit_specification }}"
        ebs_optimized: "{{ ebs_optimized }}"
        detailed_monitoring: "{{ detailed_monitoring }}"
        purge_tags: no
      when: instance.instances | count == 1
```

```yml
---
instance_type: t2.medium
cpu_credit_specification: standard
ebs_optimized: no
detailed_monitoring: no
security_group: 
  - default
  - something_other
```

##### EXPECTED RESULTS

cc @ryansb  

In case of `instance.instances[0].security_groups != security_groups` it should apply the changes.

```
TASK [try to modify the ec2 instance] ********************************************************************************************************************************************************
changed: [localhost]
```

Basically is must be `aws ec2 modify-instance-attribute --groups <list of {{security_groups}} --instance-id <instance_id>`

##### ACTUAL RESULTS

No changes are detected and nothing happen.

### PR DESCRIPTION
**Pull request by jokajak**
##### SUMMARY

This fixes the issue below, where security groups were not changed if the instance already existed.

Rebase of https://github.com/ansible/ansible/pull/55712 for devel

Fixes #54174

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ec2_instance

##### ADDITIONAL INFORMATION
Rebase of https://github.com/ansible/ansible/pull/55712 for devel

### CODE REVIEW

**Comment by jokajak** [comment]
@briantist I'm not very good with python or AWS so I don't know if I'll be able to address your testing concerns.

**Comment by briantist** [comment]
> @briantist I'm not very good with python or AWS so I don't know if I'll be able to address your testing concerns.

Since this is a rebase of #55712 , I'll repost my comment here too. 

I think tests should be added for combining the SG changes with state changes as part of any PR that adds the functionality. You've already added and fixed up the tests here so hopefully that's doable by just adding more tests with `state:` set to account for these possibilities.
[(My comment on the other PR)](https://github.com/ansible/ansible/pull/55712#issuecomment-580532461)

---
Also FYI in local testing I've found that changing the SGs doesn't happen consistently if you also set `state`, depending on what the current and desired state is. Omitting the state option works regardless of the instance's current state.

❌ = SGs don't get updated | ✅ = SGs do get updated
---|---


Current State | Desired State | Behavior
---|---|---
Stopped | Stopped | ❌
Stopped | Started | ❌
Started | Stopped | ❌
Started | Started | ✅

**Comment by jokajak** [comment]
@briantist it looks like this issue affects more than just the security groups. Based on https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_instance.py#L1612 I'd say that no changes can be made to existing instances when state is configured to anything other than `present`. Specifically the `module.exit_json` call as part of state changes.  The reason the `started`/`started` test worked is that it doesn't trigger the `handle_existing` state check.
Meanwhile https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_instance.py#L1461 doesn't even check for whether other attributes are changed.

Given the existing state of the codebase I don't think these new tests are valid.

**Comment by jokajak** [comment]
Per https://groups.google.com/forum/#!msg/ansible-devel/6UAfogEDtG8/wMTgxBGWCgAJ this is on hold and will likely be recreated in the collection.

**Pull request closed without merging**
