### PR TITLE
Refactor and fix the slaac filter.

### PR DESCRIPTION
**Pull request by chrko**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

```
ansible 2.2.0 (slaac_fix_and_include_prefix 707622ccf2) last updated 2016/08/05 16:44:53 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 24db4de245) last updated 2016/08/05 16:41:56 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD db979dde74) last updated 2016/08/05 16:41:56 (GMT +200)
  config file = /home/christian/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

The implementation of the slaac filter doesn't work (and may have never worked; introduced in cf7744f2f131708acd67c1312f622a3d4e639455 #11394). It calls a method on string instead of the corresponding `netaddr`-Class, see [lib/ansible/plugins/filter/ipaddr.py @ cf7744f](https://github.com/ansible/ansible/commit/cf7744f2f131708acd67c1312f622a3d4e639455#diff-52b5d47bc5ffb759787765a1aae56df7R603) L603 vs L606.

This implementation tries to do be more a wrapper to the existing functions instead of reinventing the wheel. Only respecting the RFC requires the code around the lines L635-L644.

While developing a fix for the slaac filter I also tried another approach. This will be a separate pull request.

Due to this pull request #11658 will be obsolete.

### CODE REVIEW

**Comment by chrko** [comment]
I have rebased the pull request. Now there is no more randomly failed build.

**Comment by calfonso** [comment]
@chrko We are catching up on PRs and we're interested in getting this one merged, if you could rebase it first then we'll get it reviewed. Thanks!

**Comment by chrko** [comment]
Ok, I will so this the following week. Thank you for the notification!

**Comment by chrko** [comment]
Yeah. Checked it again. The main bug got fixed by #17551.
I'll probably create a new pull request to extend the behaviour of the slaac filter to meet the requirements of the RFC. (Assume always a 64bit prefix or treat everthing else than an 64-bit ipv6 network as an error).
#16979 is also obsolete now.

**Pull request closed without merging**
