### PR TITLE
VMware: Refactor vmware_vmkernel module

### LINKED ISSUE #35491: getting error while creating vmkernel interface using vmware_vmkernel module
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_vmkernel

##### ANSIBLE VERSION

```
2.4.2.0 and dev 2.5
```

##### SUMMARY
 I am using below playbook to create vmware vmkernel interface on ESXIhost under my virtual switch.All parameters i am specifyinh here are right and i am able to create interface through vsphere webclient with same parameter values.

but when i run my playbook i get error as  "msg": "A specified parameter was not correct: "

Below is stack trace for the same.

##### STEPS TO REPRODUCE

```yaml
---

with dev ansible 2.5


- hosts: 127.0.0.1
  connection: local
  tasks:
    -  name: Add Management vmkernel port using dhcp network type
       local_action:
         module: vmware_vmkernel
         hostname: 10.243.1.43
         username: root
         password: PASSW0RD
         vswitch_name: vSwitch1
         portgroup_name: test1
         vlan_id: 0
         network:
           type: 'dhcp'
         enable_mgmt: True
         enable_vmotion: True
         validate_certs: no

with ansible 2.4.2.0

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add Management vmkernel port (vmk1)
      local_action:
        module: vmware_vmkernel
        hostname:  10.243.1.43
        username:  root
        password:  PASSW0RD
        vswitch_name:  vSwitch1
        portgroup_name:  test1
        vlan_id: 0
        ip_address:  10.243.9.1
        subnet_mask:  255.255.255.0
        enable_mgmt:  True
        enable_vmotion:  True
        validate_certs:  no
```

##### EXPECTED RESULTS

```
    expect vmkernel interface getting added
```
##### ACTUAL RESULTS

```
  The full traceback is:
  File "/tmp/ansible_EMdqRm/ansible_module_vmware_vmkernel.py", line 236, in main
    changed = pyv.create_vmkernel_adapter()
  File "/tmp/ansible_EMdqRm/ansible_module_vmware_vmkernel.py", line 186, in create_vmkernel_adapter
    host_network_config_result = host_network_system.UpdateNetworkConfig(config, "modify")
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "enable_ft": null, 
            "enable_mgmt": true, 
            "enable_vmotion": true, 
            "enable_vsan": null, 
            "hostname": "10.243.1.43", 
            "ip_address": null, 
            "mtu": null, 
            "network": {
                "ip_address": null, 
                "subnet_mask": null, 
                "type": "dhcp"
            }, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "portgroup_name": "test1", 
            "subnet_mask": null, 
            "username": "root", 
            "validate_certs": false, 
            "vlan_id": 0, 
            "vswitch_name": "vSwitch1"
        }
    }, 
    "msg": "A specified parameter was not correct: "
}
```

```
 "msg": "A specified parameter was not correct: "
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes: #35491

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/vmware.py
lib/ansible/modules/cloud/vmware/vmware_portgroup.py
lib/ansible/modules/cloud/vmware/vmware_vmkernel.py

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@tchernomax @pdellaert Could you please review this patch ?

**Comment by law** [comment]
Tested.  Works great for me, even pulled my bacon out of the fire this weekend.  As far as I'm concerned, "ship it"!

**Comment by Akasurde** [comment]
@law Thanks for testing this patch. Merging this as a lot of people required this feature ASAP.

**Comment by law** [comment]
Thanks for writing this patch.   You saved me from having to apply a half-dozen portgroups, vmKernel interfaces, and vSwitch definitions to 50+ hosts by hand!

**Pull request merged**
