### PR TITLE
Adds support for snapshots and extra persistent disks to the gce modules

### PR DESCRIPTION
**Pull request by clconway**
ansible-devel thread:
https://groups.google.com/d/topic/ansible-devel/ZuNnnZiDI9Q/discussion

Note: the first two commits on this branch are from another PR:
https://github.com/ansible/ansible/pull/6823

@erjohnso

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you please add the "version_added" field for all of the new attributes in the docs section?

Thank you!

**Comment by clconway** [comment]
Hi, @mpdehaan. What's the correct value for version? 1.6?

**Comment by clconway** [comment]
Assuming the answer to the above is "1.6": done.

**Comment by erjohnso** [comment]
@clconway - thank you!!

**Comment by bings** [comment]
Hi when will this be merged? Really need this... thanks!

**Comment by erjohnso** [comment]
@mpdehaan - I believe this is ready to merge (actually has been, my bad for not saying so earlier!)

**Comment by clconway** [comment]
Ping?

**Comment by mpdehaan** [comment]
Merging this now, missed prior notifications, I'll update the version_added to say 1.7

**Comment by mpdehaan** [comment]
Thanks @clconway - I've mentioned to @erjohnso that if you guys want something merged and are wondering on status, shooting me an email is good anytime.

Much appreciated!

**Pull request merged**
