### PR TITLE
Remove redundant get_sudorule_diff logic

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/identity/ipa/ipa_sudorule.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Nosmoht** [comment]
_shipit_

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
Closing and re-opening for removing stale_ci

**Comment by Akasurde** [comment]
Resolved by another PR. Closing this.

**Pull request closed without merging**
