### PR TITLE
Netbox Inventory enchancement - add Device and VM Interface information

### PR DESCRIPTION
**Pull request by mkeetman**
##### SUMMARY
This PR implements a new extractor method which includes the inventory information if requested.  Additionally, it makes a second request to gather all device/vm IP addresses and attaches them as a list to the interface object

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Netbox inventory plugin

##### ADDITIONAL INFORMATION
The inventory extraction is quite expensive and slow. The Netbox API doesn't appear to lend itself to easy access to this information (except requesting each interface individually)

This PR supersedes #54285 which had gotten out of hand due to my inexperience.

### CODE REVIEW

**Review by FragmentedPacket — APPROVED** [review]
Tested and looks good.

**Comment by FragmentedPacket** [comment]
shipit

**Comment by Akasurde** [comment]
@mkeetman Thanks for the contribution. This is implemented via https://github.com/netbox-community/ansible_modules/pull/98

**Comment by Akasurde** [comment]
Hi @mkeetman, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/netbox-community/ansible_modules<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
