### PR TITLE
New action plugin that will include a vars dir.

### PR DESCRIPTION
**Pull request by linuxdynasty**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

include_vars_dir
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

New action plugin that will include a vars dir.
This plugin allows you to include an entire directory and its nested directories of variable files.
Features..
- Ignore by default *.md, *.py, and *.pyc
- Ignore any list of files.
- Only include files nested by depth (default=unlimited)
- Match only files matching (valid regex)
- Sort files alphabetically and load in that order.
- Sort directories alphabetically and load in that order.

```
    - name: include all yml files in vars/all and all nested directories
      include_vars_dir:
        dir: 'vars/all'

    - name: include all yml files in vars/all and all nested directories and save the output in test.
      include_vars_dir:
        dir: 'vars/all'
        name: test

    - name: include all yml files in vars/services
      include_vars_dir:
        dir: 'vars/services'
        depth: 1

    - name: include only bastion.yml files
      include_vars_dir:
        dir: 'vars'
        files_matching: 'bastion.yml'

    - name: include only all yml files exception bastion.yml
      include_vars_dir:
        dir: 'vars'
        ignore_files: 'bastion.yml'
```

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible/17195)

### CODE REVIEW

**Comment by bcoca** [comment]
so group_vars are part of inventory and not meant to be included through include directives, you should not use them as examples as it might confuse users. The proper directory for variable inclusion is 'vars'.

**Comment by linuxdynasty** [comment]
@bcoca I will update the doc string to reflect vars.

**Comment by linuxdynasty** [comment]
Test is failing but not due to this PR

**Comment by mattclay** [comment]
@linuxdynasty Tests have been restarted and all are now passing.

**Comment by linuxdynasty** [comment]
Closing this PR in favor of #17207

**Pull request closed without merging**
