### PR TITLE
Update documentation and more closely mirror old behavior

### PR DESCRIPTION
**Pull request by fabianvf**
##### SUMMARY

- Replace old references to openshift_raw and k8s_raw with k8s
- Update tests
- Search for given kind in `kind`, `name`, `singularName` and `shortNames`, to match previous behavior

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

k8s

### CODE REVIEW

**Comment by fabianvf** [comment]
@jimi-c

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/66972/67/console

**Comment by maxamillion** [comment]
@fabianvf the change looks good, just make the bot happy and I think we're good to go here.

**Comment by maxamillion** [comment]
shippable FreeBSD `user` test failures are unrelated.

**Comment by maxamillion** [comment]
shipit

**Pull request closed without merging**
