### PR TITLE
avoid conflicting with bsd packaging

### PR DESCRIPTION
**Pull request by bcoca**
this way we'll use the module shebang defaults

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

implicit localhost
##### ANSIBLE VERSION

```
>=2.5
```

### CODE REVIEW

**Comment by abadger** [comment]
-1.  As bcoca explained it to me, this is to enable platform packagers to rewrite the shebang lines in our modules when they ship them in a package.  They believe this will optimize the user experience for them because their users won't have to set ansible_python_interpreter for localhost (on these platforms, sys.executable is not set to the path to python).

This is not an okay strategy for them to be using as it can break our rewriting of the shebang line for ansible_*_interpreter .  The most likely scenario I can see which would break this is if they rewrite the shebang line to account for python3 on their platform ```#!/usr/bin/python3```.  That will make all of our documentation and community knowledge which tells people to change ansible_python_interpreter invalid (those users would have to change ansible_python3_interpreter to set it to a different python interpreter instead... even if it is to set it to a python2 interpreter.)

If they want to change the defaults the right way for them to do that is to change the hardocded default that we have here.  I, change line 95 from
``` patch
-                py_interp = '/usr/bin/python'
+                py_interp = '/path/to/this/platforms/python'
```
It's a simpler patch for them as they can change one line in one file instead of all the shebangs in every module we ship.

If we want to give them a way to set this without patching, the right answer is to provide configuration options for default values of ansible_python_interpreter (or default values on implicit localhost).  I don't believe we should go that route, though, as we already have inventory to do that.  Adding a configuration value in this case would just be adding additional ways to change the same value which is going to lead to confusion.

**Comment by bcoca** [comment]
That is not only reason, this should not be hardcoded and just use the module shebang, otherwise if we change it ourselves in the future this might still cause errors.

this was set to match our modules, which it would if unset, no need to hard code it.

**Comment by abadger** [comment]
Okay, bcoca explained that this overrides the all group's vars which makes sense.  However, that points out that a previous fix to implicit localhost broke all group's vars handling as well.
You can see that the current code does the wrong thing if you have inventory like this:
```
[all:vars]
ansible_python_interpreter=/bin/false
```
```ansible -i inventory -m ping localhost ``` should error in this case but it succeeds.

I think the code should look like this:
```
    def _create_implicit_localhost(self, pattern):

        if self.localhost:
            new_host = self.localhost
        else:
            new_host = Host(pattern)

            new_host.address = "127.0.0.1"
            new_host.implicit = True

            # set localhost defaults
            all_vars = self.groups['all'].get_vars()
            py_interp = all_vars.get('ansible_python_interpreter', sys.executable)

            if not py_interp:
                # sys.executable is not set in some cornercases. see issue #13585
                display.warning('Unable to determine python interpreter from sys.executable. Using /usr/bin/python   default. '
                                'You can correct this by setting ansible_python_interpreter for localhost')

            new_host.set_variable("ansible_python_interpreter", py_interp)
            new_host.set_variable("ansible_connection", all_vars.get('ansible_connection', 'local'))        
            self.localhost = new_host
            
        return new_host
```

Which restores setting of the defaults from the all group if they're set there.

**Comment by bcoca** [comment]
it is not wrong, it purposefully overrides the all group when sys.executable is present as the implicit localhost specifically was not in inventory and expected to 'just work' using connection: local and the same interpreter as Ansible itself.

**Comment by abadger** [comment]
That's bad magic.  I set things in all:vars because I want every host to obey them.  implicit localhost should not be a hidden exception to that rule.

**Comment by bcoca** [comment]
Except that breaks current assumptions, if the localhost is not in inventory (like, when we create the implicit) it is supposed to work as a local execution with the current python. 

For example, most people will be surprised if `hosts: localhost` users winrm due to their 'managed machines' being windows (all.yml: ansible_connecion: winrm) but localhost being unix flavored.

**Comment by abadger** [comment]
Which they also will be if they are using a platform where the default /usr/bin/python has been overriding all but this PR would stop it from doing so.

**Pull request closed without merging**
