### PR TITLE
Use low-level package objects in the apt module to check installed state

### LINKED ISSUE #3421: apt module says ok when package initialy ko
I was installing a package using ansible on debian system. Install went wrong and package was in an intermediate state : 
 dpkg -l | grep -v ^ii
 iU  haproxy-mbs                        1.4.23-mbs1                  haproxy 1.4.23 - MBS
apt module returns failed state, which is good : 
 tst-ha01                   : ok=6    changed=2    unreachable=0    failed=1

When I reran my playbook, I got this : 
 tst-ha01                   : ok=7    changed=2    unreachable=0    failed=0  
But package is still in the same state (iU)

ansible 1.2-2 is installed on archlinux, installing packages on debian 6 (squeeze).

### PR DESCRIPTION
**Pull request by jimi-c**
Packages which are half-installed are not adequately represented by
the .is_installed field of the apt.package.Package object. By using the
lower-level apt_pkg.Package object (which provides the .current_state
field), we can check for a partially-installed state more accurately.

Fixes #3421

### CODE REVIEW

**Comment by mpdehaan** [comment]
Code looks good to me.

Just would want to make sure here it's supported consistently on older Debian systems, Ubuntu 12.04 and new Ubuntu in case it's not part of the main "API".   Thoughts?

**Comment by jimi-c** [comment]
This was tested on 12.04, but I can build a 10.04 box to test on as well. The above is still part of the API and appears to have not changed in a while (it was the higher level Package object that changed around 0.8.x).

**Comment by mpdehaan** [comment]
10x is pretty old and/or I've never head anyone running that.

I'm more interested in possible Debian combinations people may be running and also rather new Ubuntues (Ubuntui?)

Needs to work with any possible Debians people are already using.

**Comment by srgvg** [comment]
FYI 10.04 is a LTS release which still is supported by Canonical atm. We for one are still running boxes with that version.

**Comment by mpdehaan** [comment]
Ok. We still need to test on Debians and new Ubuntu alike.

Can you please help test on your platform Serge?

**Comment by srgvg** [comment]
Sure; as per https://github.com/ansible/ansible/issues/3421#issuecomment-24303958 I already tested the patch, but I'll make sure I target some 10.04 boxes; not sure if I did that.

**Comment by srgvg** [comment]
checked ubuntu 
- 10.04 
- 10.10
- and previously 12.04

with ansible 1.3 (issue_3421_apt_pkg_iU 0d408ff295) last updated 2013/09/12 10:43:46 (GMT +200)
- update cache
- install/remove packages
- (re)install half installed iU packages

no problem whatsoever, so +1

**Comment by jimi-c** [comment]
Thanks @sergevanginderachter!

**Pull request merged**
