### PR TITLE
win_iis_webapplication: added additional parameters

### PR DESCRIPTION
**Pull request by anbsmile**
##### SUMMARY
Feature #34994

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_iis_webapplication

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

```

### CODE REVIEW

**Comment by jborean93** [comment]
@anbsmile are you able to change the PR so the new option takes in a dictionary and not a key like `win_iis_webapppool` does http://docs.ansible.com/ansible/latest/win_iis_webapppool_module.html. We are trying to move away from that string form as it brings in a lot of complexity when it comes to escaping values that are used as the differenciator and will be ultimately removed from the modules that support both the dict and string values.

**Comment by dagwieers** [comment]
Beware that the deadline for getting new features/modules accepted in [Ansible v2.6 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_6.rst#release-schedule), it is set to either 2018-05-17 or 2018-05-25. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to [the Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

**Comment by dagwieers** [comment]
Beware that the deadline for getting new features/modules accepted in [Ansible v2.7 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_7.rst#release-schedule), it is set to either 2018-08-23 or 2018-08-30. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to the [Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

**Comment by jhawkesworth** [comment]
It looks like we haven't heard from @anbsmile  for over a year.
I think we should close this one as there are merge conflicts and the format of the module parameter being added needs to change.

**Comment by jborean93** [comment]
Really sorry about letting this one fall to the wayside. If you still wish to get this change into Ansible then please feel free to open a new PR that has been rebased against devel and ping me for a review.

Closing due to merge conflict and the age of the PR.

**Pull request closed without merging**
