### PR TITLE
csvfile lookup plugin can now handle properties file.

### PR DESCRIPTION
**Pull request by Yannig**
This change allow to lookup into a java properties file using the csvfile lookup plugin.
For more information, take a lookup at the playbook test/integration/test_lookup_properties.yml which show how to use this new capability.

### CODE REVIEW

**Comment by bcoca** [comment]
I'm not sure this is the proper place, properties files are closer to ini format than to csv format

**Comment by Yannig** [comment]
Thanks for your feedback. There's no ini module isn't it ? I can create a new one and handle both type of files ?

**Comment by Yannig** [comment]
There's now a new ini lookup plugins that can handle both type : ini and properties file.

Here's is the result of the playbook example :

```
ansible-playbook test/integration/test_lookup_properties.yml 

PLAY [Lookup test] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [read properties value] ************************************************* 
ok: [localhost]

TASK: [debug var={{item}}] **************************************************** 
ok: [localhost] => (item=test1) => {
    "item": "test1",                                                                                                                                                            
    "var": {                                                                                                                                                                    
        "test1": "Text associated with value1"                                                                                                                                  
    }
}
ok: [localhost] => (item=test2) => {
    "item": "test2", 
    "var": {
        "test2": "Same for value2"
    }
}
ok: [localhost] => (item=test_dot) => {
    "item": "test_dot", 
    "var": {
        "test_dot": "Properties with dot"
    }
}
ok: [localhost] => (item=field_with_space) => {
    "item": "field_with_space", 
    "var": {
        "field_with_space": "another space"
    }
}

TASK: [read ini value] ******************************************************** 
ok: [localhost]

TASK: [debug var={{item}}] **************************************************** 
ok: [localhost] => (item=value1_global) => {
    "item": "value1_global", 
    "var": {
        "value1_global": "Text associated with value1 and global section"
    }
}
ok: [localhost] => (item=value2_global) => {
    "item": "value2_global", 
    "var": {
        "value2_global": "Same for value2 and global section"
    }
}
ok: [localhost] => (item=value1_section1) => {
    "item": "value1_section1", 
    "var": {
        "value1_section1": "Another value for section1"
    }
}

TASK: [Reading unknown value] ************************************************* 
fatal: [localhost] => Failed to template {{lookup('ini', 'value2           section=section1 file=lookup.ini')}}: Unexpected error in during lookup: No option 'value2' in section: 'section1'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/drayan/test_lookup_properties.retry

localhost                  : ok=5    changed=0    unreachable=1    failed=0   
```

**Comment by bcoca** [comment]
very nice, could you rebase into a single commit?

**Pull request closed without merging**
