### PR TITLE
Adding Support For EVPN in BGP Module

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Adding Support for EVPN in onyx_bgp for onyx switches

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/onyx/onyx_bgp.py
test/units/modules/network/onyx/fixtures/onyx_bgp_show.cfg
test/units/modules/network/onyx/test_onyx_bgp.py

##### ADDITIONAL INFORMATION

```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev8/lib/ansible
  executable location = /.autodirect/mtrswgwork/anasb/ansible_dev8/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

### CODE REVIEW

**Review by samerd — CHANGES_REQUESTED** [review]
Thanks @anasbadaha 
looks great.
However, I have two small comments:
1- All regular expressions started with: ^\s.*router
should be changed to: ^\s*router

2- in function _generate_bgp_cmds
when checking: if curr_as_num != as_number:
you should also check if the vrf has been changed, then you have to remove the bgp and create a new one.

**Comment by anasbadaha** [comment]
Hi @samerd ,

I have fixed your comments related to function _generate_bgp_cmds and added a unit test for it as well.
Regarding Regex comment I saw it is working perfect and this will be more strong to Put .* after space in order to avoid changes in cli response.
Please approve it if it is Ok for you now.
Thanks

**Review by samerd — APPROVED** [review]
Excellent Job @anasbadaha 
Thanks

**Comment by anasbadaha** [comment]
Hi @justjais,

Can you please merge this PR if it is OK for you?

Thanks

**Review by ganeshrn — APPROVED** [review]
lgtm

**Comment by ganeshrn** [comment]
rebuild_merge

**Pull request merged**
