### PR TITLE
Digital Ocean firewall facts

### PR DESCRIPTION
**Pull request by BondAnthony**
##### SUMMARY

Creation of Digital Ocean firewall facts module

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/digital_ocean/digital_ocean_firewall_facts.py
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (feature/do-firewall-facts 09e216d6c6) last updated 2018/10/06 17:56:46 (GMT -400)
  config file = /Users/abond/Dev/github/ansible.cfg
  configured module search path = ['/Users/abond/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/abond/Dev/github/ansible/lib/ansible
  executable location = /Users/abond/Dev/github/ansible/bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:14:27) [Clang 9.0.0 (clang-900.0.39.2)]

```

### CODE REVIEW

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by pmarques** [comment]
LGTM

shipit

**Review by pmarques — APPROVED** [review]

**Comment by gundalow** [comment]
Thank you for the PR and to all that reviewed. Merged into `devel` for release in Ansible 2.8.

**Comment by BondAnthony** [comment]
Thank you all! I will have a second PR soon that adds support for managing the firewalls.

@gundalow I need to spend some time creating tests for these modules also.

**Pull request merged**
