### PR TITLE
Feature vars prompt confirm crypt

### PR DESCRIPTION
**Pull request by mgwilliams**
Example:

``` yaml
  vars_prompt:
    foo: {prompt: "enter foo", encryption: "md5_crypt", confirm: true, salt_size: 7, salt: "foo"}
    bar: {prompt: "enter bar", encryption: "sha512_crypt", confirm: false, salt: "foo"}
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ok, some more questions... this is much better state of course but I still want some tweaks.

(1) I infer "salt size" as what to use if the salt is NOT supplied, which contradicts with the example above.   Salt and salt_size should be mutually exclusive, right?   Not sure why both are listed together above, I think it presumably should be an error to specify both.

(2)  I still like "encrypt" (not as a boolean) as a name versus "encryption".   It's like a command, encrypt it this way.   Plus saves  horizontal space.

(3)  We're going to start requiring functionality start adding tests to ensure things don't break later.  At least some of the reusable logic should be moved into utils.py, possibly do the try/except logic there and then just use the playbook to read parameters in and call the function.   Then add tests to TestUtils.py for a couple invocations, showing usage with salt, salt_size (seperately) and a couple of encyrption algorithms.

(4)  For documentation purposes and my curiousity, under what versions of Python is the support for this NOT available?   (Because of the try/except logic, it seems you were coding for that).

**Comment by mgwilliams** [comment]
> (1) I infer "salt size" as what to use if the salt is NOT supplied, which
> contradicts with the example above.   Salt and salt_size should be mutually
> exclusive, right?   Not sure why both are listed together above, I think it
> presumably should be an error to specify both.

They are mutually exclusive. Sorry for any confusion.

> (2)  I still like "encrypt" (not as a boolean) as a name versus
> "encryption".   It's like a command, encrypt it this way.   Plus saves
>  horizontal space.

OK, will change back.

(3)  We're going to start requiring functionality start adding tests to
ensure things don't break later.  At least some of the reusable logic
should be moved into utils.py, possibly do the try/except logic there and
then just use the playbook to read parameters in and call the function.
Then add tests to TestUtils.py for a couple invocations, showing usage with
salt, salt_size (seperately) and a couple of encyrption algorithms.

Will try to put something together, may need more clarification.

(4)  For documentation purposes and my curiousity, under what versions of

> Python is the support for this NOT available?   (Because of the try/except
> logic, it seems you were coding for that).

passlib is not in stdlib, it must be installed separately if you want to
use encryption (confirm works without it, of course)

**Comment by mpdehaan** [comment]
Happy to help explain test infra -- thanks

I see, gotcha.

**Comment by mgwilliams** [comment]
encryption -> encrypt done

**Comment by mpdehaan** [comment]
things have shifted a bit in 0.5, can you see about taking these changes and making them work with 0.5?

**Comment by mpdehaan** [comment]
This is now merged in per #821!  Works great!   Thanks @flowroute and @cocoy

**Pull request closed without merging**
