### PR TITLE
removal of chdir in controller

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

core

### CODE REVIEW

**Review by nitzmahone — APPROVED** [review]
woot

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Was asked to have network-integration tests run by zuul, that was the reason for my comment.

**Review by Qalthos — APPROVED** [review]
This shouldn't have any ill effects on network as far as I can tell

**Pull request merged**
