### PR TITLE
Pull request for issues #1841 and #1840

### PR DESCRIPTION
**Pull request by grzn**
For #1840, I did a nasty thing to get around the setuptools sandbox. Your comments?
For #1841, please review each commit separately so you'll understand which files I moved, and which I changed - as I moved the files from bin/ to lib/ansible/scripts and creates other ones in bin/

Just throw me your comments and I'll adjust the code...

Thanks,
Guy

### CODE REVIEW

**Comment by dhozac** [comment]
I see no reason to move all the scripts around. Getting easy_install to work only needs a 3 line change to constants.py. Requiring setuptools in an additional dependency for no gain whatsoever.

So, what's the benefit of any of this?

**Comment by grzn** [comment]
It is for buildout, we talked about it yesterday

**Comment by mpdehaan** [comment]
Thanks this is a MUCH nicer patch and a lot easier to review.  Thank you.   Yeah I have no problem with most of this.

Can you add some comments about why fool_setuptools_sandbox is there and how it actually works?  I didn't understand this part.   (Also, just to make sure all the bases are covered, does this cause problems anywhere else, i.e. have you tested a pip install, building the RPM, building the deb, etc)?

**Comment by mpdehaan** [comment]
Daniel, FYI -- this does not require setuptools, it uses it if available.

**Comment by mpdehaan** [comment]
@grzn, please add comments about the fool_setuptools stuff if you would like this applied ... I'll look at testing afterwards.    Thanks!

**Comment by mpdehaan** [comment]
Upon further thinking about this I am really not comfortable with some of this extra layer, especially things starting with "_" and so on.

Seems straightforward to just have the main scripts.

**Pull request closed without merging**
