### PR TITLE
library/cloud/ec2_group: Enable egress rules

### PR DESCRIPTION
**Pull request by randomvariable**
This pull request enables egress rules in similar fashion to https://github.com/ansible/ansible/pull/6416 . However, this includes a new parameter for egress rules, 'rules_egress' rather than having to declare the type.
In addition, default and non-declared rules will be removed as is currently the case for ingress rules.

### CODE REVIEW

**Comment by mpdehaan** [comment]
So we have three of these now, #6602 #6416 and #6598 

Obviously there's a lot of duplicate effort here, but can you all please get together and sort out which one of these you prefer and define any changes that need to be made?

**Comment by mmoya** [comment]
I'm in favor of tweaking this one, he submitted first. What I not like that much is having everything in one big commit but hey, that's @mpdehaan decision at the end.

Would like to know @randomvariable opinion on issue covered by  3156df9931e3eabb1f3a7dccf02a73e35d97c228 and the _group description_ when creating the depended-on group (see 649fcd3e1cc72c480a1c87c6985a319488f64afa) .

I not sure what #6416 does WRT the default _ALLOW ALL_ egress rule if the user declares such rule in the playbook (see [this comment](https://github.com/ansible/ansible/pull/6416#issuecomment-37756446)) .

**Comment by randomvariable** [comment]
Happy to go with @mmoya's pull request. Seems cleaner than my attempt that creates a class to dedup some code. In addition, anything to reduce the number of tasks that need to be written is a good thing.

I don't believe #6416 allows an ALLOW ALL egress rule to be declared. Re-reading the security group after creation seems like a good bet.

**Comment by mpdehaan** [comment]
Sounds like you two may need to flip a coin and we may want to close out #6416.

Awaiting further resolution :)

**Comment by mmoya** [comment]
Well, @randomvariable already gave green light to #6602.

**Comment by randomvariable** [comment]
Yup. Am closing this request in favour of @mmoya's.

**Comment by mpdehaan** [comment]
Thanks!  If you want to submit a PR on top (merging shortly) that is welcome!

**Pull request closed without merging**
