### PR TITLE
Stable vmWare VM disk creation (vsphere_guest only)

### LINKED ISSUE #19326: vsphere_guest unable to add additional disks
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vsphere_guest

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
Python 2.7.5
Vsphere 6.0
```

##### SUMMARY

Issue encountered when running a playbook using vsphere_guest module to add new disk on a running VM. The VM is created via template and has single disk (disk1). I can add more space on disk1 but the module fail if I need to attach new disk (disk2 as an example.) Below is my example.
```
vm_disk:
           disk1:
               size_gb: 31
               type: thin
               datastore: VM-Datastore-1
           disk2:
               size_gb: 10
               type: thin
               datastore: VM-Datastore-1
```

##### STEPS TO REPRODUCE

```
running the playbook: ansible-playbook tasks/add_disks.yml -vvvv
```
https://gist.github.com/mikecali/83d4fc1a5e34c9ea35b86eb225f7f905

##### ACTUAL RESULTS

he playbook should add attach disk2 on the running VM  (RHEL-jmt)

```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: add_disks.yml ********************************************************
1 plays in tasks/add_disks.yml

PLAY [Reconfigure VM Filesystem] ***********************************************

TASK [Reconfigure Reconfigure VM Filesystem] ***********************************
task path: /home/mikecali/mike-personal/vm_disk_add/tasks/add_disks.yml:26
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/cloud/vmware/vsphere_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mikecali
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1481678610.17-273194120531311 `" && echo ansible-tmp-1481678610.17-273194120531311="` echo $HOME/.ansible/tmp/ansible-tmp-1481678610.17-273194120531311 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpE14O0U TO /home/mikecali/.ansible/tmp/ansible-tmp-1481678610.17-273194120531311/vsphere_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/mikecali/.ansible/tmp/ansible-tmp-1481678610.17-273194120531311/ /home/mikecali/.ansible/tmp/ansible-tmp-1481678610.17-273194120531311/vsphere_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/mikecali/.ansible/tmp/ansible-tmp-1481678610.17-273194120531311/vsphere_guest.py; rm -rf "/home/mikecali/.ansible/tmp/ansible-tmp-1481678610.17-273194120531311/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "cluster": null, 
            "esxi": {
                "datacenter": "ALABS-Wellington", 
                "hostname": "172.17.203.4"
            }, 
            "force": true, 
            "from_template": null, 
            "guest": "RHEL-jmt", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "power_on_after_clone": true, 
            "resource_pool": null, 
            "snapshot_to_clone": null, 
            "state": "reconfigured", 
            "template_src": null, 
            "username": "administrator@vsphere.local", 
            "validate_certs": false, 
            "vcenter_hostname": "172.17.203.6", 
            "vm_disk": {
                "disk1": {
                    "datastore": "VM-Datastore-1", 
                    "size_gb": 31, 
                    "type": "thin"
                }, 
                "disk2": {
                    "datastore": "VM-Datastore-1", 
                    "size_gb": 10, 
                    "type": "thin"
                }
            }, 
            "vm_extra_config": {
                "mem.hotadd": true, 
                "vcpu.hotadd": true
            }, 
            "vm_hardware": {
                "memory_mb": "1024", 
                "num_cpus": "1", 
                "osid": "RH7", 
                "scsi": "paravirtual"
            }, 
            "vm_hw_version": null, 
            "vm_nic": {
                "nic1": {
                    "network": "VM Network", 
                    "network_type": "standard", 
                    "type": "vmxnet3"
                }
            }, 
            "vmware_guest_facts": null
        }, 
        "module_name": "vsphere_guest"
    }, 
    "msg": "Error reconfiguring vm: Invalid configuration for device '0'., [{'size_gb': 10, 'type': 'thin', 'datastore': 'VM-Datastore-1'}]"
}
```

### PR DESCRIPTION
**Pull request by noroutine**
Stable vmWare VM disk creation (vsphere_guest only)
    
        * Create more than 15 disks during reconfigure and creation
        * Allow to specify SCSI controller and unit
        * Create needed SCSI controllers automatically
        * Fix disk ordering
    
    04 Jan 2018:
        * rebased against latest 2.5
        * cleaned up code to have less duplicates
        * relaxed restriction to specify esxi hostname for vm creation
          VM can now be created in resource pool from scratch
        * removed buggy restriction to require force together with state

##### SUMMARY

Comprehensive fix for creating large arrays on vsphere. Unfortunately only for old module for now.

Background:
For large disk configurations in vm_disk field, the module failed to create disk arrays when vm was created from scratch or reconfigured, when more than 15 disks where requested. Additionally the disks where created in wrong order. Wrong here means, module uses dictionary sort and disk 10 is created as as 'Hard disk 2' for example, while natural sort should be used in the process.

While I saw several fixes merged already which try to fix the issue, none of them addressed two other, namely having predictable SCSI controller and lun setting and creating disks in predictable for human  order

This pull request is supposed to fix all three issues, by introducing extra parameters: **controller** and **unit** in disk dict. This fix works for both creating from scratch or reconfiguring later

The fix falls back gracefully for simple setups with < 16 disks, and allows to omit these parameters for first 15 disks, however user still can specify them and they will be honored. For disk1 till disk15, the controller is assumed to be 0 if missing and unit number is assumed to be disk id - 1 for disk1 to disk7 and disk id for disk8 to disk15

Limitations:
Unfortunately, as it appears vsphere doesn't allow to predictably name hard disks via API and enforces it's own numbering. This means the disk ids should appear in the dict without gaps. Means you can't create disk 15 without creating first 14 disks, otherwise numbers will not match anymore and subsequent task runs may fail or behave unpredictably.

Disk numbering in vsphere begins with 1, so there should be no disk0 entry in the vm_disk. This might break for users who have it, since before vsphere created it as 'Hard disk 1', enforcing it. With this fix, disk id in vm_disk dict is used to actually match the disk in vm, so requirement for the number is much stricter.

Fixes #19326 I suppose, however there were already several patches for that version merged anyway

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

vsphere_guest

##### ANSIBLE VERSION

```
ansible 2.5.0 (vsphere_guest_disk_fix 107bd8b233) last updated 2018/01/05 01:04:01 (GMT +200)
  config file = None
  configured module search path = [u'/home/tomcat/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/data/external/ansible/ansible/lib/ansible
  executable location = /opt/data/external/ansible/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```

##### ADDITIONAL INFORMATION

Way to reproduce the problem would involve playing with quite some playbooks and some screenshots, so instead of pasting tons of yaml, here is general guidance and important piece of boring code for copy:

- Create any vm with disk array that has more than 15 disks via playbook
or
- Create small vm and add disks during reconfiguring

- Observe the disk numbers assigned by vsphere are not matching dict specified for disks above 10
- Observe error when reconfiguring for more than 15 disks

I'll simply paste the tedious piece for anyone who will test this

```
  vm_disk:
    disk1:
      size_gb: 20
      type: thin
      datastore: "{{ vsphere_datastore }}"
    disk2:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 1
      unit: 0
    disk3:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
    disk4:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
    disk5:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
    disk6:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
    disk7:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
    disk8:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 1
      unit: 1
    disk9:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 1
      unit: 2
    disk10:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 1
      unit: 3
    disk11:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 1
      unit: 4
    disk12:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 2
      unit: 1
    disk13:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 3
      unit: 1
    disk14:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 3
      unit: 2
    disk15:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 3
      unit: 3
    disk16:
      size_gb: 10
      type: thin
      datastore: "{{ vsphere_datastore }}"
      controller: 3
      unit: 4
```

### CODE REVIEW

**Comment by noroutine** [comment]
Removed natsort dependency and fixed trailing spaces

**Comment by noroutine** [comment]
Added some comment to vm_disk docs about numbering and warning about number gaps

**Review by digennarot — COMMENTED** [review]
very good quality, please commit !

**Comment by noroutine** [comment]
Similar functionality in vmware_guest is work in progress, can you advise if it's best to have it in one pull request or in a separate one? I estimate it will be ready in two weeks

Thanks

**Comment by noroutine** [comment]
@digennarot can you review one more time? :)

**Comment by Akasurde** [comment]
Thanks for the PR. Closing this PR since `vsphere_guest` is removed in 2.9 version.

**Pull request closed without merging**
