### PR TITLE
add oVirt provider to ManageIQ module

### PR DESCRIPTION
**Pull request by snecklifter**
##### SUMMARY
This commit adds oVirt/RHEV capability to the ManageIQ remote
management module.

Currently the manageiq remote management module only supports OpenShift and AWS. This adds oVirt/RHEV capability. Aside from required parameters like the provider type, name and type of connection, only API hostname, userid and password are required and therefore this should be a trivial commit. ie. Functionality already exists within the module to support oVirt/RHEV.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
modules/remote_management/manageiq

##### ADDITIONAL INFORMATION
An example of the current calls using the uri module:

```
- name: Create RHEV Provider
  uri:
    url: "{{ miq_endpoint }}"
    method: POST
    user: "{{ vault_cfme_user }}"
    password: "{{ vault_cfme_password }}"
    body: 
      type: "ManageIQ::Providers::Redhat::InfraManager"
      name: "{{ rhev_provider_name }}"
      hostname: "{{ rhev_provider_endpoint }}"
      credentials:
        userid: "{{ vault_rhev_user }}"
        password: "{{ vault_rhev_password }}"
    status_code: 200
    body_format: json
    validate_certs: no
```

### CODE REVIEW

**Comment by snecklifter** [comment]
@yaacov @cben 

I'm not sure if ovirt would be better than oVirt for the provider type?

This code is much easier to work (unless I'm missing something!) with than the original so hopefully a fairly trivial addition?

**Review by yaacov — APPROVED** [review]
LGTM

**Comment by yaacov** [comment]
shipit

**Comment by yaacov** [comment]
> I'm not sure if ovirt would be better than oVirt for the provider type?

We use capital letters, so I like `oVirt` better.

> This code is much easier to work 

Thanks :-)

**Comment by cben** [comment]
:+1:
shipit

**Review by zgalor — APPROVED** [review]
:+1: 
shipit

**Pull request merged**
