### PR TITLE
Add GPL License header to freeipa inventory file.

### PR DESCRIPTION
**Pull request by abednarik**
##### SUMMARY

Add GPL License header to freeipa inventory file

#24341

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

contrib/inventory/freeipa.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.0 (apt_download_only 4def437187) last updated 2017/05/03 14:32:40 (GMT +000)
  config file =
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

### CODE REVIEW

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by sivel** [comment]
Per the referenced issue, I believe we will need sign off from each of the authors mentioned before we can license this file as GPL.

As far as the ticket states, you are not an original author of that file.

**Comment by Akasurde** [comment]
OK.

**Comment by gundalow** [comment]
@mscherer
@erinn
@bcoca
@gedmin
@rgroten
@mattclay

Can you please sign off on this change, thanks in advance.

**Review by mattclay — APPROVED** [review]

**Review by rgroten — APPROVED** [review]

**Comment by mscherer** [comment]
Sure, I am fine for GPL.

**Comment by abednarik** [comment]
Hi

 Still pending approval from 3 contributos. Please @bcoca , @erinn and @mgedmin can you approve this one?

Thanks and sorry to bother.

**Review by mgedmin — APPROVED** [review]
:+1: for GPL

**Comment by erinn** [comment]
GPL is fine.

**Comment by abednarik** [comment]
Friendly reminder to not leave this PR open.

Thanks

**Comment by bcoca** [comment]
approve license change

**Comment by calfonso** [comment]
rebuild_merge

**Comment by abednarik** [comment]
thanks.

**Pull request merged**
