### PR TITLE
Add a missed command

### PR DESCRIPTION
**Pull request by it-praktyk**
##### SUMMARY
To prepare the local development environment used to perform integration tests of Windows modules is required to install additional Python packages. The pull request contains the missed command to accomplish that.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
a Windows module development documentation

### CODE REVIEW

**Review by nitzmahone — CHANGES_REQUESTED** [review]
Rather than duplicating setup instructions, I'd prefer to just say something along the lines of "you need to have a Windows host that's configured for WinRM connectivity and your control system needs to be configured to successfully connect to it per our end-user instructions"...

**Comment by it-praktyk** [comment]
@jborean93 started that list which is currently incomplete without the command that I would like to add.

How tests can be performed is not obvious and that step-by-step instruction, IMHO, decrease a barrier to develop Ansible modules for Windows.

BTW, Duplicating? So where is it the original one instruction? Maybe can we just link to it?

**Comment by nitzmahone** [comment]
Should just be an RST `L()` directive to point at `docs/docsite/rst/user_guide/windows_winrm.rst`

**Comment by it-praktyk** [comment]
@nitzmahone, it was much more complicated. But, at least, I learned something new :-)

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Thanks @it-praktyk for the changes.

**Comment by acozine** [comment]
Thanks @it-praktyk for adding an anchor to the `windows_winrm` page and linking to it. I'm not sure if you found our documentation on how to do this, which is at https://docs.ansible.com/ansible/devel/dev_guide/style_guide/index.html#internal-navigation. You've gotten us closer to our goal of at least one anchor for every rST page!

**Comment by it-praktyk** [comment]
Nope, I didn't read that part of the documentation. And to be honest it was not easy to find how should I link that. I try to propose improvements to the documentation about creating documentation itself soon.

**Pull request merged**
