### PR TITLE
new strategy "host_pinned"

### LINKED ISSUE #39374: new strategy like "free" but uninterrupted execution per host
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

plugins/strategy/atomic

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/tim/test/ansible/ansible.cfg
  configured module search path = ['/home/tim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tim/conda/envs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/tim/conda/envs/ansible/bin/ansible
  python version = 3.6.5 | [...] | (default, Apr 13 2018, 12:47:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/tim/test/ansible/ansible.cfg) = True
```
(Output of ``ansible-config dump --only-changed``)

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I would like to have a strategy that executes playbooks in such a way that once the play for a host is started, it will run to completion without "its" worker being snatched for plays of other hosts.
In the following, I will call the desired strategy "atomic".

This is closely related to the behaviour of the "free" strategy, so let's have a look at the execution order of tasks when run with the free strategy.

As a guiding example, consider a playbook with three tasks, "stop" followed by "update" (which takes some time), followed by "start", run on an inventory with three hosts "A", "B" and "C" with ``--forks 1``.

In this setup, I would like the "atomic" strategy to have all tasks for host A will be executed before any task for host B (there is only 1 fork!), so the order will be
1. A stop
2. A update
3. A start
4. B stop
5. B update
6. B start
7. C stop
8. C update
9. C start

In contrast to the behaviour described above, the "free" strategy will execute in this order:

1. A stop
2. B stop
3. C stop
4. A update
5. B update
6. A start
7. C update
8. B start
9. C start

Here, A's play is interrupted by tasks for B and C.
There is no waiting of host B for a new slot that would be opened once host A is done with the play (and C waiting for B's slot).

With two workers ``--forks 2``, I expect an execution order for "atomic" like the following (parallel execution as unordered list):
1. - A stop
   - B stop
2. - A update
   - B update
3. - A start
   - B start
4. - C stop
5. - C update
6. - C start

Whereas the "free" strategy will execute in an order that is more like the following:

1. - A stop
   - B stop
2. - C stop
   - A update
3. - B update
   - A start
4. - B start
   - C update
5. - C start

We observe that "C stop" is executed much earlier than expected, so that from C's perspective the play isn't executed as fast as possible and it did not wait for a slot (from A or B) to open up.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - add_host: name="{{ item }}"
      no_log: yes
      loop: [A, B, C]

- hosts: all
  gather_facts: no
  strategy: free
  tasks:
    - name: stop
      local_action:
        module: shell
        cmd: "date -u +\"stop {{ inventory_hostname }} %H:%M:%S.%N\""
      register: msg

    - debug: msg="{{ msg.stdout }}"
    - name: update
      local_action:
        module: shell
        cmd: "date -u +\"updating {{ inventory_hostname }} %H:%M:%S.%N\" ; sleep 2 ; date -u +\"updated {{ inventory_hostname }} %H:%M:%S.%N\""
      register: msg

    - debug: msg="{{ msg.stdout }}"

    - name: start
      local_action:
        module: shell
        cmd: "date -u +\"start {{ inventory_hostname }} %H:%M:%S.%N\""
      register: msg

    - debug: msg="{{ msg.stdout }}"
```

Output of play with ``--forks 1``
```
$ ansible-playbook test.yml --forks 1
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************

TASK [add_host] ****************************************************************
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)

PLAY [all] *********************************************************************

TASK [stop] ********************************************************************
changed: [A -> localhost]
changed: [B -> localhost]
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "stop A 07:02:44.174029962"
}
ok: [B] => {
    "msg": "stop B 07:02:44.436160558"
}

TASK [update] ******************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "stop C 07:02:44.690951127"
}

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "updating A 07:02:45.028612055\nupdated A 07:02:47.031238359"
}

TASK [update] ******************************************************************
changed: [B -> localhost]

TASK [start] *******************************************************************
changed: [A -> localhost]

TASK [update] ******************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "start A 07:02:49.625430719"
}

TASK [debug] *******************************************************************
ok: [B] => {
    "msg": "updating B 07:02:47.366121959\nupdated B 07:02:49.367728418"
}
ok: [C] => {
    "msg": "updating C 07:02:49.882540427\nupdated C 07:02:51.885279434"
}

TASK [start] *******************************************************************
changed: [B -> localhost]
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [B] => {
    "msg": "start B 07:02:52.251900634"
}
ok: [C] => {
    "msg": "start C 07:02:52.496086386"
}

PLAY RECAP *********************************************************************
A                          : ok=6    changed=3    unreachable=0    failed=0
B                          : ok=6    changed=3    unreachable=0    failed=0
C                          : ok=6    changed=3    unreachable=0    failed=0
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

Output of play with ``--forks 2``:
```
$ ansible-playbook test.yml --forks 2
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************

TASK [add_host] ****************************************************************
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)

PLAY [all] *********************************************************************

TASK [stop] ********************************************************************
changed: [B -> localhost]
changed: [A -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "stop A 07:16:45.489372102"
}
ok: [B] => {
    "msg": "stop B 07:16:45.489355132"
}

TASK [stop] ********************************************************************
changed: [C -> localhost]

TASK [update] ******************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "stop C 07:16:45.736580915"
}

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "updating A 07:16:45.811320486\nupdated A 07:16:47.813289791"
}

TASK [update] ******************************************************************
changed: [B -> localhost]

TASK [start] *******************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
ok: [B] => {
    "msg": "updating B 07:16:45.969581878\nupdated B 07:16:47.971922983"
}

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "start A 07:16:48.204427216"
}

TASK [start] *******************************************************************
changed: [B -> localhost]

TASK [debug] *******************************************************************
ok: [B] => {
    "msg": "start B 07:16:48.523619978"
}

TASK [update] ******************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "updating C 07:16:48.132759023\nupdated C 07:16:50.135063889"
}

TASK [start] *******************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "start C 07:16:50.444562398"
}

PLAY RECAP *********************************************************************
A                          : ok=6    changed=3    unreachable=0    failed=0
B                          : ok=6    changed=3    unreachable=0    failed=0
C                          : ok=6    changed=3    unreachable=0    failed=0
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

---

Originally, I considered this a documentation bug or behavioural bug, but @jimi-c proposed in #39376 that this would be better suited as a novel strategy, so I'll try my best at a new PR. :-)

I'll see to commit a new PR.

Thanks,
Tim

PS: I changed this description from a bug report to a feature idea. I hope that's ok.

### PR DESCRIPTION
**Pull request by backbord**
##### SUMMARY

Fixes #39374.

With this change, the novel "host_pinned" strategy takes the number of workers into consideration and does not queue tasks for more of the remaining hosts than the number of workers allows.
This copies the behavior of the "free" strategy but processes each host as fast as possible (from the host's perspective) and only move on to a next host, once a slot has been cleared by a previous host (when its play ended).

This is not thoroughly tested yet: what happens when there a play fails and stuff like that is not clear to me and I would love to have someone have a look.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

plugins/strategy/host_pinned

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/tim/test/ansible/ansible.cfg
  configured module search path = ['/home/tim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tim/conda/envs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/tim/conda/envs/ansible/bin/ansible
  python version = 3.6.5 | [...] | (default, Apr 13 2018, 12:47:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### ADDITIONAL INFORMATION

I bet that there is a nicer way to implement this change in behavior but with my limited understanding of the ansible sources, I wasn't able to come up with any.

Here's the example playbook from the issue -- but with ``strategy: host_pinned`` -- and the outputs when running it with ``--forks 1`` and ``--forks 2``.

We can see that the execution order is as I expected in the issue.

```
- hosts: localhost
  gather_facts: no
  tasks:
    - add_host: name="{{ item }}"
      no_log: yes
      loop: [A, B, C]

- hosts: all
  gather_facts: no
  strategy: host_pinned
  tasks:
    - name: stop
      local_action:
        module: shell
        cmd: "date -u +\"stop {{ inventory_hostname }} %H:%M:%S.%N\""
      register: msg

    - debug: msg="{{ msg.stdout }}"
    - name: update
      local_action:
        module: shell
        cmd: "date -u +\"updating {{ inventory_hostname }} %H:%M:%S.%N\" ; sleep 2 ; date -u +\"updated {{ inventory_hostname }} %H:%M:%S.%N\""
      register: msg

    - debug: msg="{{ msg.stdout }}"

    - name: start
      local_action:
        module: shell
        cmd: "date -u +\"start {{ inventory_hostname }} %H:%M:%S.%N\""
      register: msg

    - debug: msg="{{ msg.stdout }}"
```

Output with ``--forks 1``
```
$ ansible-playbook test.yml --forks 1
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************

TASK [add_host] ****************************************************************
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)

PLAY [all] *********************************************************************

TASK [stop] ********************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "stop A 10:40:40.777419378"
}

TASK [update] ******************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "updating A 10:40:41.093571044\nupdated A 10:40:43.096332765"
}

TASK [start] *******************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "start A 10:40:43.415098160"
}

TASK [stop] ********************************************************************
changed: [B -> localhost]

TASK [debug] *******************************************************************
ok: [B] => {
    "msg": "stop B 10:40:43.732071569"
}

TASK [update] ******************************************************************
changed: [B -> localhost]

TASK [debug] *******************************************************************
ok: [B] => {
    "msg": "updating B 10:40:44.028223362\nupdated B 10:40:46.031274418"
}

TASK [start] *******************************************************************
changed: [B -> localhost]

TASK [debug] *******************************************************************
ok: [B] => {
    "msg": "start B 10:40:46.350271560"
}

TASK [stop] ********************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "stop C 10:40:46.667895294"
}

TASK [update] ******************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "updating C 10:40:46.986292242\nupdated C 10:40:48.989297153"
}

TASK [start] *******************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "start C 10:40:49.312367792"
}

PLAY RECAP *********************************************************************
A                          : ok=6    changed=3    unreachable=0    failed=0
B                          : ok=6    changed=3    unreachable=0    failed=0
C                          : ok=6    changed=3    unreachable=0    failed=0
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

Output with ``--forks 2``
```
$ ansible-playbook test.yml --forks 2
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************

TASK [add_host] ****************************************************************
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)
changed: [localhost] => (item=None)

PLAY [all] *********************************************************************

TASK [stop] ********************************************************************

TASK [stop] ********************************************************************
changed: [B -> localhost]
changed: [A -> localhost]

TASK [debug] *******************************************************************

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "stop A 10:41:14.245874598"
}

TASK [update] ******************************************************************
ok: [B] => {
    "msg": "stop B 10:41:14.245864747"
}

TASK [update] ******************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
changed: [B -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "updating A 10:41:14.545606954\nupdated A 10:41:16.548323883"
}

TASK [start] *******************************************************************
ok: [B] => {
    "msg": "updating B 10:41:14.560199761\nupdated B 10:41:16.562108792"
}

TASK [start] *******************************************************************
changed: [A -> localhost]

TASK [debug] *******************************************************************
changed: [B -> localhost]

TASK [debug] *******************************************************************
ok: [A] => {
    "msg": "start A 10:41:16.858244476"
}

TASK [stop] ********************************************************************
ok: [B] => {
    "msg": "start B 10:41:16.870863799"
}
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "stop C 10:41:17.161668699"
}

TASK [update] ******************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "updating C 10:41:17.471128177\nupdated C 10:41:19.473225676"
}

TASK [start] *******************************************************************
changed: [C -> localhost]

TASK [debug] *******************************************************************
ok: [C] => {
    "msg": "start C 10:41:19.798542125"
}

PLAY RECAP *********************************************************************
A                          : ok=6    changed=3    unreachable=0    failed=0
B                          : ok=6    changed=3    unreachable=0    failed=0
C                          : ok=6    changed=3    unreachable=0    failed=0
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

----

#### Notes and Questions

1. Functionality.
   @jimi-c proposed to inspect if the ``_queue_task()`` function could be modified to return ``False`` if all workers are busy and thus to minimise duplicated functionality.

   I tried modifying ``_queue_task()`` to return False when all workers are busy and (a new) parameter flag ``block`` is set to False.
   However, in the "free" strategy, ``_queue_task()`` is never called when all hosts are blocked, so I think that I do need to rely on ``get_pending_results()`` to carry the information about when workers are free again.
   I.e., I think that I need to know about the two states "all workers busy, may not queue a task" and "not all workers busy anymore, may queue a task" without having to try to queue a task to get the state change information.
   Perhaps you have an idea and can advise?

2. Code duplication.
   I was hesitant about copying the "free" strategy and adding the minor changes for the novel behavior to it due to much lines of code being duplicated (and potential bug fixes would to free would be required to be applied to the new strategy as well).
   Therefore, I added an instance variable as a switch to the "free" strategy.
   The novel strategy "host_pinned" consists of a couple of lines subclassing the "free" strategy and using the switch to change the behaviour.
   Do you consider this a valid approach or what kind of code do you prefer in your code basis?

3. Naming.
   At first, I called the new strategy "per_host" and now settled on "host_pinned", but I'm not a native speaker and I think that "per_host" might not read/sound as nice as the existing strategies "linear" or "free" do and both "per_host" and "atomic" could be misleading.
   What do you think? Do you have a idea for a better name? :)
   Edit: Settled for "host_pinned". Thanks for the suggestions.

4. Authorship and Maintenance.
   As a first time contributor to ansible I don't have experience with how to do it right the first time.
   I consider the proposed code change and novel strategy to be quite limited and minor.
   It fully relies on the "free" strategy and I didn't want to claim authorship in "host_pinned" as I think of it as merely being a dwarf on the shoulders the ansible code base. :)

   Oh, btw: as most of my colleagues, I love how simple and yet customizable ansible proves itself in everyday use! Thank you for this amazing piece of software!

Thanks for your time,
Tim

PS:
- Original PR was !39376 where @jimi-c proposed to add a novel strategy.
- @jimi-c, sorry for the many notifications this might create. :)

Edit: rename from "atomic" to "streamlined"
Edit: rename from "streamlined" to "host_pinned"

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to traceback in integration tests:

```
2018-05-02 14:15:11 Traceback (most recent call last):
2018-05-02 14:15:11   File "/root/ansible/bin/ansible-playbook", line 118, in <module>
2018-05-02 14:15:11     exit_code = cli.run()
2018-05-02 14:15:11   File "/root/ansible/lib/ansible/cli/playbook.py", line 122, in run
2018-05-02 14:15:11     results = pbex.run()
2018-05-02 14:15:11   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 159, in run
2018-05-02 14:15:11     result = self._tqm.run(play=play)
2018-05-02 14:15:11   File "/root/ansible/lib/ansible/executor/task_queue_manager.py", line 268, in run
2018-05-02 14:15:11     strategy = strategy_loader.get(new_play.strategy, self)
2018-05-02 14:15:11   File "/root/ansible/lib/ansible/plugins/loader.py", line 397, in get
2018-05-02 14:15:11     obj = obj(*args, **kwargs)
2018-05-02 14:15:11   File "/root/ansible/lib/ansible/plugins/strategy/free.py", line 53, in __init__
2018-05-02 14:15:11     super(StrategyModule, self).__init__(self, tqm)
2018-05-02 14:15:11 TypeError: __init__() takes exactly 2 arguments (3 given)
```

**Comment by backbord** [comment]
Hi @mattclay,

thanks for the pointer!
That was a very beginner mistake I made there. Sorry.

I fixed it and managed to add some basic tests for strategy "atomic" by just copying the tests I found where strategy "free" is referenced.

I'm still in the process of figuring out how to run the complete test suite on my machine, so I hope CI will be more satisfied with the change now. :)

Thanks,
Tim

**Comment by backbord** [comment]
Hi,
only the tests for [freebsd/11.1/1](https://app.shippable.com/github/ansible/ansible/runs/63556/27/tests)
```
{
    "assertion": "'Failed to validate the SSL certificate' in result.msg or ( result.msg is match('hostname .* doesn.t match .*'))", 
    "changed": false, 
    "evaluated_to": false
}
```
and [osx/10.11/2](https://app.shippable.com/github/ansible/ansible/runs/63556/36/tests)
```
{
    "assertion": "'Error validating the server' in url_invalid_cert.msg or ( url_invalid_cert.msg is search('hostname .* doesn.t match .*'))", 
    "changed": false, 
    "evaluated_to": false
}
```
are failing and I don't know what (if anything) I can do about that.
Do you have a suggestion?

To me, the failures do seem unrelated to this PR.

Thanks,
Tim

**Comment by mattclay** [comment]
I've restarted CI for this PR.

**Comment by backbord** [comment]
Oh no, I think I did something wrong. I just wanted to update my fork to the current state of devel. Dang it.

**Comment by backbord** [comment]
good bot!
that was exactly the info that I needed. phew.

**Comment by mattclay** [comment]
The unrelated errors have been fixed. I've restarted CI for this PR.

**Comment by backbord** [comment]
Hi @mattclay,
I think I need your help again.
I've rebased the PR against the most up-to-date devel branch, but still (as with a previous run) get the following errors from CI.

Do you reckon that they stem from my changes? I'm having trouble seeing how my changes might have caused them.

[centos6/1](https://app.shippable.com/github/ansible/ansible/runs/63990/28/tests)
```
"msg": "Status code was -1 and not [200]: Connection failure: connection was closed before a valid response was received: ", 
```
[centos7/1](https://app.shippable.com/github/ansible/ansible/runs/63990/29/tests)
```
{
"changed": false, 
"msg": "Failure talking to yum: Cannot find a valid baseurl for repo: base/7/x86_64"
}
```

The only files in "test" that contain "strategy: " are the following.
```
test/integration/targets/blocks/main.yml:  strategy: "{{test_strategy|default('linear')}}"
test/integration/targets/blocks/main.yml:  strategy: "{{test_strategy|default('linear')}}"
test/integration/targets/includes/test_include_atomic.yml:  strategy: atomic
test/integration/targets/includes/test_include_free.yml:  strategy: free
```
To my understanding, these tests have nothing to do with the failures above.

What am I not seeing? :)

**Comment by backbord** [comment]
Cool. After rebasing again to the most up-to-date devel branch, no tests failed.
However, [freebsd/11.1/1](https://app.shippable.com/github/ansible/ansible/runs/64295/27/console) marks the build as failed.
```
2018-05-08 09:06:07 ERROR: Command "ssh -tt -q -i test/cache/id_rsa -o BatchMode=yes -o ServerAliveCountMax=4 -o ServerAliveInterval=15 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 ec2-user@ec2-34-200-221-184.compute-1.amazonaws.com su -l root -c ''"'"'rm -rf /tmp/results && cp -a ansible/test/results /tmp/results && chmod -R a+r /tmp/results'"'"''" returned exit status 255.
```

**Comment by mattclay** [comment]
I've restarted CI for this PR.

**Comment by backbord** [comment]
So I rebased again.
Now, [linux/ubuntu1404/1](https://app.shippable.com/github/ansible/ansible/runs/64499/33/tests) is failing with this message:
```
 failure: '/usr/bin/apt-get dist-upgrade --auto-remove' failed: Extracting templates from packages: 96%Extracting templates from packages: 100% mysql stop/waiting invoke-rc.d: initscript udev, action "restart" failed. dpkg: error processing package udev (--configure): subprocess installed post-installation script returned error exit status 1 mysql start/running, process 6537 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message Errors were encountered while processing: udev E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Is there anything I can do to make this work except rebasing and pushing the same commits over and over again? :)

**Comment by mattclay** [comment]
Closing and re-opening a PR will trigger a re-run of CI.

**Comment by backbord** [comment]
Do you agree that these are spurious failures?

If so, what else can I do to help this PR?
Are there questions to address or is this PR merely awaiting the checks to succeed and there's nothing else to do for me?

From my perspective, getting the spuriously failing checks to resolve is some item to tick, but it isn't really related to what this PR is about since the fix 90ea415d3d0c7b11d390dd6991e53376cffe1372.

**Comment by mattclay** [comment]
@backbord The last test failures I saw do look unrelated. Hopefully tests will pass on the next run.

Aside from the tests passing, this PR will require review from the Ansible Core Team. Much of the team is traveling this week for Red Hat Summit and PyCon, so getting reviews may take longer than usual.

You may want to add it to the agenda for the Ansible Project Meetings for discussion:

https://github.com/ansible/community/issues/308

**Comment by backbord** [comment]
@mattclay Thanks for the quick response and the info.

I'll check out the link and see what I can do.

**Comment by backbord** [comment]
"All checks have passed" yeah!

**Comment by backbord** [comment]
(rebased)

**Comment by willthames** [comment]
I think I'd call this "batch" rather than "atomic" as you're acting on a batch of hosts at a time. I'm surprised there isn't already a way to do this, but I can definitely see the use case.

**Comment by willthames** [comment]
Also, for what you're trying to achieve, this is a very minimal change, well done!

**Comment by backbord** [comment]
Hi @willthames,

thank you for having a deeper look and the feedback!

I do like the name "batch".
However, in the context of processing order of playbooks, I'm concerned that it might be interpreted as being related to the "batch size" which can be configured using [``serial``](https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#rolling-update-batch-size), e.g. meaning that "completion of the play for all hosts of the current batch triggers the play for the next batch" which doesn't fully reflect the strategy's behavior.
I have to add that I'm not a native speaker, so please let me know if you share my concern or if "batch" is the better name for the strategy and I'll gladly rename it. :)

**Comment by bcoca** [comment]
my  bikeshed: 'streamlined'

**Comment by backbord** [comment]
ooh, I do like 'streamlined'

**Comment by abadger** [comment]
To bikeshed a little more, though... streamlined is a bad name because it is a generic positive adjective rather than a description of its functionality.  If I had a strategy named "faster", people would be left wondering, "Why wouldn't I always want to run the faster strategy? Why isn't linear/free just made faster than they already are?"

The best name would have something to do with when the strategy is appropriate to use (the debug strategy is a good example of this.) Something like host_at_a_time or batch satisfies that.  If we can't settle on a name like that, at least pick something which doesn't inspire people to use it all the time, even when it is inappropriate to their use-case.

**Comment by backbord** [comment]
Hi @abadger, thanks for your message. I agree.
"by_host", which was one of your suggestions in the meeting, seems like a good name to me.
Renaming it from "atomic" to "streamlined" came from the thought that it might be "vague enough for users to read the documentation" (like with "linear" or "free" -- which I did misunderstand as "as fast as possible per host").
For my thoughts on "batch" please see [above](https://github.com/ansible/ansible/pull/39602#issuecomment-397060974). Perhaps I don't have the right understanding of what "batch" means.

That being said, I value the opinion of core team members very much and will happily change the name to something that is considered well-fitting. :)
Please let me know.

**Comment by bcoca** [comment]
well, linear and free are not well named .... (really lockstep and nowait)

**Comment by mavit** [comment]
Perhaps this could be called `free_host_first`, and `free` could become an alias for `free_task_first`?

**Comment by bcoca** [comment]
good news, we had vote on name, `host_pinned` got most votes ... also @alikins had some comments on implementation he'll probably post shortly

**Comment by backbord** [comment]
@bcoca, those are good news -- thanks! I've renamed and updated the PR accordingly.

**Comment by bcoca** [comment]
merged via #44586, i resolved the conflict manually

**Pull request closed without merging**
