### PR TITLE
Update foreman maintainers

### PR DESCRIPTION
**Pull request by ares**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ares** [comment]
@webknjaz this is a follow up of your suggestion from #55437, current maintainers for Foreman callbackare @ekohl @xprazak2 and myself, please let me know if I need to do some other steps as well

**Comment by ekohl** [comment]
This doesn't cover `$plugins/callback/foreman.py` and its tests. Probably also good to add `$plugins/inventory/foreman.py`. Given they're very different paths it feels like a `$team_foreman` would make sense.

**Comment by jctanner** [comment]
cc @ehelms pleack ack this

**Comment by ehelms** [comment]
This seems to only cover the modules which are deprecated. I think the updates @ekohl suggested need to be made first.

**Review by webknjaz — APPROVED** [review]

**Comment by ares** [comment]
oh I misunderstood the file format, now I introduced foreman_team and put the same maintainers to the foreman.py callback

**Comment by ekohl** [comment]
Do you want to include `$plugins/inventory/foreman.py` as well?

**Comment by ares** [comment]
oh yeah, makes sense for sure, updated

**Review by ekohl — APPROVED** [review]

**Pull request merged**
