### PR TITLE
file: must fail in check_mode when path and owner/group don't exist

### LINKED ISSUE #67307: file module fails in check mode if directory exists but user or group does not.
##### SUMMARY
In check mode, when using the file module to create a directory, if the directory already exists but the requested owner or group do not, the module will fail. I encountered this when running a playbook in check mode that creates a new user and changes the ownership of an existing directory.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
file

##### ANSIBLE VERSION
```
ansible 2.9.3
  config file = /home/nepeta/wip/lockss-playbook/ansible.cfg
  configured module search path = ['/home/nepeta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Fedora 31 host

##### STEPS TO REPRODUCE
Run the following playbook in check mode (`ansible-playbook demo.playbook.yml -C`):

```yaml
# demo.playbook.yml---

- hosts: localhost
  tasks:
    - name: Create user.
      user:
        name: notauser
        state: present

    - name: Task succeeds in check mode.
      file:
        path: /notadirectory
        state: directory
        owner: notauser

    - name: Task fails in check mode.
      file:
        path: /usr
        state: directory
        owner: notauser
```

##### EXPECTED RESULTS
I expect the module to skip the lookup of the user or group if it doesn't exist and to report the task as changed.

##### ACTUAL RESULTS
```
TASK [Create user.] ***********************************************************************************************************************
changed: [localhost]

TASK [Task succeeds in check mode.] *******************************************************************************************************
changed: [localhost]

TASK [Task fails in check mode.] **********************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  gid: 0
  group: root
  mode: '0755'
  msg: 'chown failed: failed to look up user notauser'
  owner: root
  path: /usr
  secontext: system_u:object_r:usr_t:s0
  size: 4096
  state: directory
  uid: 0
```

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes: https://github.com/ansible/ansible/issues/67307
This PR doesn't solve the issue but the issue reports wrong behavior.
See my comment under the description. 

When we run ```file``` module in check_mode and ```owner/group``` doesn't exist at the same time,
it returns ```True``` but if we run the module in the actual mode it fails (**and it's expected**). See examples in the issue.
I consider that it must fail in both cases, otherwise, it behaves wrong successfully passing this check when ```owner/group``` and the ```path``` don't exist.

When there is no check_mode, the module goes to ```lib/ansible/module_utils/basic.py``` and uses ```set_owner_if_different``` and ```set_group_if_different``` methods.
The functions I added to file.py use the same logic for check owner/group exists or not.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
```lib/ansible/modules/files/file.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by resmo — APPROVED** [review]
LGTM

**Comment by nepella** [comment]
@Andersson007: You've closed and re-opened this pull request four times; also, it still hasn't been merged. Is this what you intended?

**Comment by Andersson007** [comment]
@nepella i close and reopen this to relaunch CI tests in order to remove ```stale_ci``` label. Otherwise, the pr look abandoned. Hope anybody from core team review it eventually

**Comment by Shrews** [comment]
Code lgtm as it is. Though I do wonder if we should consider moving the owner/group check methods to module_utils/basic.py so that it can be used elsewhere potentially. What say you, @bcoca ?

**Comment by Andersson007** [comment]
@Shrews if eventually the PR is merged as it is (i very hope), i'll try to find places where it can be used as well. If i find, we can move it to module_utils/basic.py

**Comment by Andersson007** [comment]
@nepella @Shrews lack of `shipit` doens't let it to become merged:)

**Comment by Andersson007** [comment]
@mattclay it's waiting again despite all checks have been passed well (i tried to rerun via /rebuild several times during the last week)

**Comment by mattclay** [comment]
@Andersson007 I've restarted the tests.

**Comment by mkrizek** [comment]
!waffling stale_ci

**Comment by Andersson007** [comment]
i madehttps://github.com/ansible/ansible/pull/69640 instead

**Pull request closed without merging**
