### PR TITLE
Support auto_remove in docker_container

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Support `auto_remove` so that when the containers process exits, the container will be deleted

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by sivel** [comment]
I'm not positive we can really add this.  This requires `docker>=2.0`, and errors with `docker-py`.

I suppose we could add logic around only passing in `auto_remove` when `HAS_DOCKER_PY_2`.  I'll look at what that looks like.

**Comment by chouseknecht** [comment]
Looks good to me. Tested with the following simple task:

```
- name: Container present
    docker_container:
      name: mycontainer
      state: started
      image: "ubuntu:14.04"
      auto_remove: yes
      command: sleep 60s
```
The new parameter doesn't break the module's idempotent-ness.

**Comment by chouseknecht** [comment]
I am noticing that the if the image (in this case ubuntu:14.04) does not already exist, the modules fails with the following error:

```
"msg": "Error pulling image ubuntu:14.04 - 'module' object has no attribute 'get_config_header'"
```

I expect the module to pull the image, which I thought it used to do. I don't believe this is an issue introduced here. But I'm investigating...

**Comment by sivel** [comment]
Basic idempotency test:

```yaml
---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: ./pex/docker.pex

  tasks:
    - docker_container:
        name: alpine1
        image: alpine
        command: sleep 300

    - docker_container:
        name: alpine1
        image: alpine
        command: sleep 300
      register: alpine1_idem
      failed_when: alpine1_idem|changed

    - docker_container:
        name: alpine2
        image: alpine
        command: sleep 300
        auto_remove: true

    - docker_container:
        name: alpine2
        image: alpine
        command: sleep 300
        auto_remove: true
      register: alpine2_idem
      failed_when: alpine2_idem|changed
```

Run:

```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ ansible-playbook -v docker_container.yml
[SNIP]
PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0
```

**Comment by chouseknecht** [comment]
Seems to be a personal problem on my end. Running the following fixed it:

```
pip uninstall docker docker-py
pip install docker
```
That left me with the following installed:

```
$ pip list | grep docker

docker (2.2.1)
docker-pycreds (0.2.1)
```

Now if the image is missing, it automagically gets pulled.

**Comment by chouseknecht** [comment]
Yep, your idempotency test checks out.

**Comment by chouseknecht** [comment]
@sivel, Thanks for contributing this! Nice job.

**Comment by sivel** [comment]
> I expect the module to pull the image, which I thought it used to do. I don't believe this is an issue introduced here. But I'm investigating...

I do not experience that issue.

I just attempted after removing all my images:

```
$ docker rm -f `docker ps -aq`
$ docker rmi `docker images -q`
```

It was able to pull it successfully, and execute my playbook.

I've tried with both `docker==2.2.0` and `docker==2.2.1` and neither produced that error.

**Comment by sivel** [comment]
Thanks!

**Pull request merged**
