### PR TITLE
Added ec2_cloudwatch module to create and destroy CloudWatch alarms

### PR DESCRIPTION
**Pull request by brafales**
As discussed on the mailing list given that none of the current ec2 modules support it

### CODE REVIEW

**Comment by mpdehaan** [comment]
@pas256 any chance I can get you to take a look at this real quick?  Thank you!

**Comment by mpdehaan** [comment]
Also note there was an alarm module for AWS that was just merged, so I think this is probalby a more of a question of consolidation with #6540?  Let me know your thoughts @brafales and @willthames and @Zeekin

Thanks!

**Comment by brafales** [comment]
Both modules are very similar. The one that was merged in fact does some more stuff in checking and updating existing alarms and only reporting the status of `changed` when the alarm has actually been changed.
Only thing I'm not sure about is the parameters required attributes. Haven't played much with `boto` but although some of the parameters there are optional, missing them will not let you create the alarm (i.e, `statistic`, `namespace`, `metric` and so on). @Zeekin what are your thoughts about this?
Happy to drop this request in favour of the other merge as it was done before mine and is more complete.

**Comment by willthames** [comment]
@brafales - the reason that the parameters are optional is that the same module copes with creation and deletion - and the parameters aren't required for deletion. 

In #6419 we deal with a similar issue for `ec2_asg` by having an `enforce_required_arguments` method that is only used for creation of auto scaling groups - something similar could be done here if required.

**Comment by brafales** [comment]
I haven't thought about this scenario, it makes sense.

**Comment by pas256** [comment]
Yeah, I think #6540 has it covered - I love a module that can clean up after itself.

**Comment by Zeekin** [comment]
@brafales with regards to the optional parameters, I think @willthames has explained the reasoning - also worth noting if parameters change between creates on an existing alarm, it will apply any 'updates' to the alarm's parameters; not all parameters are required to perform an 'update'.

**Comment by brafales** [comment]
Yes, feel free to close this one :)

**Pull request closed without merging**
