### PR TITLE
Commit the yum_secure module

### PR DESCRIPTION
**Pull request by sbernier**
##### ISSUE TYPE
 - New Module Pull Request
##### COMPONENT NAME
Module name is yum_secure
##### ANSIBLE VERSION
```
2.1.1.0
```

##### SUMMARY
 Ansible supports sudo at the framework level, but it assumes unrestricted sudo permissions.
 We have to operate environments where sudo is restricted to certain commands only, hence Ansible at the framework level doesn’t help us.
 We have introduced sudo capabilities directly into a new yum module, in order to support restricted sudo and manage to deploy our solution.

What do you think of the solution, is there any other alternatives?

We are working with Ansible version 2.1 so we would need this functionality on this specific version.

### CODE REVIEW

**Comment by jctanner** [comment]
@sbernier couldn't we solve this issue by allowing a "yum_path" parameter in the yum+dnf modules?

needs_info

**Comment by abadger** [comment]
I understand the niche this is trying to fill but I don't believe it's general enough to fit into the official tree.  It's probably also not something we want because of code duplication.  Here's my thinking on generality, which is the larger of the two issues:

* The only thing that will work here is passwordless sudo.  If the user has password-sudo or uses su, doas, or another method of escalating privileges, they are out of luck.
* This method only works for the modified yum module.  A site might also need priivileges to query certain facts on the machine, configure a datadase, etc.  The changes here don't make those things possible.

@jctanner's idea is interesting as it isn't directly about privileges and therefore these problems don't really apply to it, yet it still allows for what you want to achieve.  It feels better than the approach here but I'm not sure whether I'm onboard with it or not... we've obviously never needed it for other purposes (the detection of where yum is installed works just fine).  Maybe in the brave new dnf-driven world, people who install the real yum package somewhere locally would appreciate it?

**Comment by sbernier** [comment]
I agree with your points, that the solution is not enough generic.
The idea here was to show a solution for our case of restricted sudo permissions.
The Ansible user will be restricted to only yum command and systemctl commands.
He will have the ability to become another user for files creation on the system.
But nothing much than that.

This approach was our main idea to solve the issue.

**Comment by abadger** [comment]
I'm going to close this ticket now as we won't be able to take this module into the core.  You should be able to use it locally at your site or you could try to implement and submit jctanner's idea of a yum_path that we use instead of trying to autodetect the yum to use (and that would, in turn, allow you to put "sudo yum" in as the path argument.)  Note that we wouldn't be able to take the change into ansible-2.1.x (or 2.2.x) as it is a new feature and so would only be included in new major release (2.3, 2.4, etc depending on when the change was merged).  Thanks!

**Pull request closed without merging**
