### PR TITLE
Proposing fix for Issue #4324; adding support for su

### PR DESCRIPTION
**Pull request by angstwad**
For Issue #4324, this adds support for `su`.
- add su support to `bin/ansible`
- su support added into the `runner.Runner` class
- ssh conn plugin updated to allow su-able commands
- necessary helper functions added into ansible.utils module
- add su support to `bin/ansible-playbook` and
- add relevant su support to playbook code in lib
- resolve issues where remote /tmp dir has improper permissions; ensure chmod issues are handled in situations where the su user is not root

Tests ran ok:

```
Ran 93 tests in 41.325s

OK (SKIP=1)
```

**The glaring omission here is lack of hostvars support**.  This does not incorporate su-ing via hostvars.  Basically, I'm soliciting feedback on this -- like, should we implement this support and how...or is this even the right direction to take for adding su support in Ansible.   Perhaps you know what I mean.

Hey, did you guys know that the Ansible codebase is complex and has tons of stuff going on?  Of course you did!  But I didn't, not until I worked on su, so here's hoping my proposed PR here is good enough.  ;)  Thanks, dudes.

### CODE REVIEW

**Comment by mpdehaan** [comment]
So we're currently in the process of testing ssh_alt.py (patch incoming) so we will have to move this over to the new one.   This is ticket https://github.com/ansible/ansible/pull/5226 -- I'll merge this and we may want to get your changes merged over there as this will be the new ssh.py soon

cc @jeromew @jtanner @jimi-c

**Comment by angstwad** [comment]
I'm not sure how you want to proceed at this point until you've got ssh_alt fully merged in, since we're (in some cases) touching the same areas of the codebase, so we'll have some merge conflicts.  

I'm thinking there's not much I can do until ssh_alt's latests changes in pr #5247 are merged in and tested.  Otherwise, I'll be trying to hit a moving target on my PR. What do you think?

**Comment by angstwad** [comment]
I suffered in merge conflict hell on this PR with some of the committed and reverted changes on the devel branch -- I rebased and ran into some major issues.   I'll open this up in a new PR once I've ironed out all the issues.

**Comment by jctanner** [comment]
@angstwad sorry about that, we were really focused on ssh_alt. If you need any help/guidance, please shoot an email to the ansible-devel list.

Numerous people have asked for something to do sudo without sudo (su), so I know this will be a popular feature.

**Comment by jeromew** [comment]
sorry about the conflict it is never funny when scm tools reach their limits ; clearly the 2 changesets overlap.
I don't know if I can be of some help but I think it would be better to wait until @mpdehaan decides on the next step regarding ssh_alt.

I see 3 possibilities :
1/ ssh_alt.py replaces ssh.py : simple but risky since we haven't had many testers

2/ ssh_alt.py replaces ssh.py but with "has_pipelininig: False", maybe configurable. It should fallback to the current behavior

3/ we keep ssh_alt.py and ssh.py in sync until further notice

Just my 2c but I think unfortunately those 2 PR (ssh_alt & su) are hard to push forward simultaneously.

If you need I can take a look with you since we both scratched our heads on those zones of the code ;-)

**Comment by angstwad** [comment]
Hey jeromew -- don't worry about it, no big deal.  I rebased between a merged pull request and a revert, which caused the issue.  Sometimes these things don't work as we'd like.  I was able to fix it by creating patches of my commits and applying them on fresh branch off the ansible/devel branch, with a little cleanup of the merge conflicts.

You're right, they'll be a bit difficult to push forward simultaneously.  My take on the issue is to continue testing, maintaining both in parallel, until such a time that the functionality is deemed stable enough. 

And again, you're right: we should team up on these areas since we worked so closely with this part of the codebase (which, I might add, is by no means trivial)

I've reopened the pull request above if you're interested in checking it out.

**Comment by angstwad** [comment]
@jctanner Don't worry about it -- it's not your fault.  I was just frustrated by working through the code base for so many hours only to have these weird artifacts bubbling up when I was rebasing before shipping the code back into this PR.  It was my fault -- I was being a bit liberal with my rebases, and had some bad timing.  I've reopened the issue in a new PR above.  

Thanks, guys.

**Pull request closed without merging**
