### PR TITLE
Added json flag to command, which will cause command to attempt to parse...

### PR DESCRIPTION
**Pull request by zonk1024**
... stdout and expose it to register.

example:

  tasks:
- name: grab json
  local_action: command /home/ubuntu/i_output_json json=true
  register: ioj_output
- name: debug ioj_output
  debug: msg='${item}'
  with_items: ${ioj_output.json}

### CODE REVIEW

**Comment by mpdehaan** [comment]
This is past our 6/3 feature freeze for the 6/10 release, so I will look at reviewing/merging this shortly after the 6/10 release.   Thanks!

**Comment by zonk1024** [comment]
Thank you!

I've been playing with it a bit, and one handy thing I've found for my use case is the ability to import the data from the ec2.py inventory script... although you have to massage the data a little through a shell call.
- name: grab massaged output
  local_action: "shell hosts/ec2.py | tr -s ' ' | tr -d '\n'"
  register: massaged
- name: parse massaged
  local_action: "command echo '{{ massaged.stdout }}' json=true"
  register: ec2
- name: debug ec2 data
  local_action: "debug msg='{{ ec2.json }}'"
- name: debug ec2 SOME_TAG servers
  local_action: "debug msg='{{ ec2.json.tag_SOME_TAG_ }}'"

Good times. Hope someone else can use this.

**Comment by mpdehaan** [comment]
Well, the inventory script should be used as an inventory script and it's all handled for you.... was that why you needed this?

Just curious, thanks!

**Comment by zonk1024** [comment]
No.  I wanted to be able to fire off python scripts that return json and use those values within Ansible.  I just thought the ec2.py thing was kind of nifty, and I wanted to try to post an example of it doing something. Since everyone has the ec2.py script...

**Comment by mpdehaan** [comment]
Noticed the exception raising in this needs to be module.fail_json(...) versus the general exception raising.

**Comment by mpdehaan** [comment]
Not seeing any update on this one, so I'm going to close this.  I think this might be better handled by the executable facts.d implementation in 1.3 in many cases.

**Pull request closed without merging**
