### PR TITLE
Unit test fmgr script fix

### PR DESCRIPTION
**Pull request by Ghilli3**
##### SUMMARY

Fixing an issue with the deprecated 'make test' system.  The current unit tests work fine with the current tox tests.

Issue: https://github.com/ansible/ansible/issues/35725

Adding @gundalow 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

test_fmgr_script.py

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 57e11c4bf5) last updated 2018/02/07 10:31:23 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cse/PycharmProjects/foobar_provisioning/lib/ansible/modules']
  ansible python module location = /home/cse/PycharmProjects/foobar_provisioning/lib/ansible
  executable location = /home/cse/PycharmProjects/foobar_provisioning/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
Hi,
Could you please redo this without the new module so I can cherry-pick the unit test fix into `stable-2.5`

**Comment by Ghilli3** [comment]
Hi @gundalow - Sorry, I'm not sure what you are asking for?  Shall I create a new branch without the new module for you to cherry-pick?

**Comment by gundalow** [comment]
Correct

**Comment by Ghilli3** [comment]
Hi @gundalow - I have made a new PR with the single fix for the scripting module.   Please let me know if you need me to do anything else or have any questions.  Thanks!

https://github.com/ansible/ansible/pull/36273

**Comment by gundalow** [comment]
The fix for the unit tests has been made and merged. I'm going to close this. Please raise a fresh PR for the new module

**Pull request closed without merging**
