### PR TITLE
docker_* modules: updating argument_spec

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
I found out a couple of days that `argument_spec` allows to specify list element types for `type == 'list'`, and recursive argument specs for `type == 'dict'`. In this PR I made the adjustments for `type == 'list'` for the docker_* modules. I also found about `suboptions` in the `DOCUMENTATION` part and added that one as well when I added an argument_spec for a `dict` option.

Note that for `type == 'list'`, the value for `elements` is ignored (except when it is `'dict'`). I hope that will change at some point, though (see #48473).

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docker_container
docker_image
docker_image_facts
docker_network
docker_service
docker_swarm

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
Ok, there's one big disadvantage: when specifying `options` for `type == 'dict'`, the default (when nothing is specified) is a `dict` with all names present, but with values `None`. That's what is failing the tests here.

I'll take another look tomorrow.

**Review by kassiansun — APPROVED** [review]
shipit

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@felixfontein Thank you for this PR
@kassiansun Thank you for the review

**Comment by felixfontein** [comment]
@kassiansun thanks for reviewing!
@gundalow thanks for merging!

I won't backport this right now; I think it should be ok, but maybe it has some surprising side-effects. So let's keep this a bit on `devel` and maybe backport it to 2.7 later.

**Pull request merged**
