### PR TITLE
new module: IRC notification

### PR DESCRIPTION
**Pull request by jpmens**
jmbp-584

### CODE REVIEW

**Comment by bcoca** [comment]
_removes notification/orc from branch as next pull will return upgraded
version_

Brian Coca

**Comment by jpmens** [comment]
@bcoca I beg your pardon? I don't understand ...

**Comment by bcoca** [comment]
sorry, in a bad attempt of humour I became unclear.

You beat me too it, so I removed my draft of same module, most likely
better off with your implementation.

**Comment by jpmens** [comment]
Unsure. Michael says 'use library', but I can't find one that doesn't suck. I think the socket stuff is ok b/c it doesn't require external modules.

**Comment by bcoca** [comment]
he, I was also using the socket, there is a good python lib for xmpp but
not for irc (or I suck at googling for it).

**Comment by mpdehaan** [comment]
works for me, all merged in, thanks!

**Pull request merged**
