### PR TITLE
azure: implement plan parameter for azure_rm_virtualmachinescaleset

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
##### SUMMARY
add plan parameter for azure_rm_virtualmachinescaleset module (required for third-party billing plans), similar to #32401

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
cloud / azure / azure_rm_virtualmachinescaleset

### CODE REVIEW

**Comment by Fred-sun** [comment]
@andreasgerstmayr Thanks for your contribution this PR!

**Comment by Fred-sun** [comment]
@haiyuazhang @mybayern1974 Please take a review this PR when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@andreasgerstmayr  In order to get the review as soon as possible, please help to solve the conflict files when you have time. Thank you very much!

**Comment by Fred-sun** [comment]
@andreasgerstmayr  kindly ping

**Comment by Fred-sun** [comment]
@andreasgerstmayr Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by andreasgerstmayr** [comment]
looks like this feature already got implemented in the mean time: https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_virtualmachinescaleset.py#L532

**Pull request closed without merging**
