### PR TITLE
consul_kv: add a 'read_only' state

### PR DESCRIPTION
**Pull request by oboukili**
##### SUMMARY
- Added a 'read_only' state to consul_kv module to provide a 'remote' alternative to the 'local' consul_kv lookup plugin. This change should not break any existing behavior.
- (Also did a little code cleaning)

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/clustering/consul_kv.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'../../../../library']
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
           
```

##### ADDITIONAL INFORMATION
Some examples:

```
 - name: Retrieve a single value, plain and simple.
    consul_kv:
      key: some/value
      state: read_only
    register: my_consul_value

  - name: Output the value.
    debug:
      var: my_consul_value.data.Value

  - name: Recurse through a path and retrieve all associated values.
    consul_kv:
      key: some/path
      state: read_only
      recurse: true
    register: my_consul_values

  - name: Output the values.
    debug:
      var: item.Value
    with_items: "{{ my_consul_values.data }}"
```

### CODE REVIEW

**Review by sgargan — APPROVED** [review]
lgtm shipit!

**Comment by lhoss** [comment]
so this finally goes into 2.4, nice !
( but seems to be a merge conflict though )

ps: too bad an earlier PR achieving (mostly) the same feature did not make it (probably due to the infamous migrating from 'ansible-modules-extra'): 
* https://github.com/ansible/ansible-modules-extras/pull/3371/files
* related: https://github.com/ansible/ansible-modules-extras/issues/3355

This read call would also help in implementing a '--diff' feature on our own (*highly* useful IMO), though having implemented this *directly* inside the module would have multiple advantages.
Any chance of adding this @sgargan  or getting it merged if we contribute this functionality ?
UPDATE: Here's the Feature issue: https://github.com/ansible/ansible/issues/28278

**Comment by oboukili** [comment]
Stale PR it seems...I don't know why the source has become an "unknown repository". Should I make a new PR?

**Comment by colin-nolan** [comment]
I realise now that I essentially created a duplicate of this in #37837 when addressing an issue raised in #37224. I noticed this PR's title when looking at existing PRs but I thought that a `read_only` state implied a key would be made "readonly" opposed to the operation being only a read.

I am now a little split on which of the 2 solutions is more "Ansibley". The drawback of this one is that it's essentially abusing the `state` property as we're not setting the state of the key to `read_only`. I also don't think that failing if the key is missing is the best idea: as I developer, I'd rather get some sort of `None` value than having to handle an error. My solution has the drawback that the read functionality is less explicit - no key value implies a read.

**Comment by colin-nolan** [comment]
There was also a fix for this created by @sgargan: https://github.com/ansible/ansible-modules-extras/pull/3371! His fix is almost exactly the same as mine in https://github.com/ansible/ansible/pull/37837. I can only assume that the move from [ansible/ansible-modules-extras](https://github.com/ansible/ansible-modules-extras/) back to this repository prevented this functionality from been added 16 months ago!

**Comment by colin-nolan** [comment]
Another fix using an "obtain" state was PR'd before: https://github.com/ansible/ansible-modules-extras/pull/3638.

**Comment by oboukili** [comment]
lost interest

**Pull request closed without merging**
