### PR TITLE
Add to_text conversion to raw_data

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

This PR fixes str/bytes troubles when using Python3

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- scaleway_dynamic_inventory

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (fix_unicode f318cb32d5) last updated 2018/08/06 14:49:04 (GMT +200)
  config file = None
  configured module search path = [u'/Users/sieben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sieben/workspace/ansible/lib/ansible
  executable location = /Users/sieben/workspace/ansible/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

### CODE REVIEW

**Comment by remyleone** [comment]
@pilou- Could this be merged?

**Comment by pilou-** [comment]
@sieben I am using Python 3.6 but I wasn't able to reproduce this error and never encounter this backtrace. Could you provide a way to reproduce this error ?

**Comment by remyleone** [comment]
I think it was created using this: 

```
---
plugin: scaleway
regions:
  - par1
  - ams1
tags:
  - harelay
```

**Comment by remyleone** [comment]
I think that `response.read()` will give bytes

**Comment by remyleone** [comment]
Could this be merged? I think it only adds protection and additional checks.

**Comment by pilou-** [comment]
I am not willing to approve this one because:
1. I am unable to reproduce it
2. there is no backtrace provided in the description
3. existing code from other modules doesn't use try/execpt around `response.read()`

**Pull request closed without merging**
