### PR TITLE
etcd3: Enable deleting of whole prefixes

### PR DESCRIPTION
**Pull request by vfauth**
##### SUMMARY
- Add the possibility to delete whole ranges of keys using a prefix.
- Made the 'value' parameter optional when 'state!=present'.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
etcd3

##### ANSIBLE VERSION

```
2.5.1
```

### CODE REVIEW

**Comment by gundalow** [comment]
Thanks for tidying up some of the code issues please remove `lib/ansible/modules/clustering/etcd3.py E326` from `test/sanity/validate-modules/ignore.txt`

**Review by evrardjp — APPROVED** [review]

**Comment by evrardjp** [comment]
👍

**Comment by maxamillion** [comment]
Thank you for the pull request, could you pleas add some [integration tests](https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html) to exercise the new functionality added? Also, please include a [changelog fragment](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs). Otherwise the changes look good.

**Comment by maxamillion** [comment]
needs_revision

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
