### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by whoami-anoint**
SUMMARY

Updated the Ansible documentation to improve readability, organization, and visual appeal. Made changes to the content structure, added headings, and enhanced the formatting with badges and images. Additionally, fixed broken links and ensured consistency throughout the document.
ISSUE TYPE

Docs Pull Request

COMPONENT NAME
README.rst

The changes were made to enhance the overall user experience and make it easier for readers to navigate and understand the Ansible documentation. The updated .rst file is now more visually appealing and user-friendly. The modifications include:

    Added badges for PyPI version, documentation, build status, chat, code of conduct, mailing lists, license, and CII Best Practices.
    Structured the content with appropriate headings and subheadings.
    Fixed broken links and updated URLs to ensure they point to the correct resources.
    Made formatting improvements for better readability.
    Ensured consistency in terminology and style throughout the document.
```

### CODE REVIEW

**Comment by samccann** [comment]
Thanks @whoami-anoint for this PR. Since we are splitting 'core' documentation from the Ansible project documentation, can you update any docs urls to use https://docs.ansible.com/ansible-core/devel/index.html set of docs instead please?

**Review by whoami-anoint — COMMENTED** [review]
It's better now than before

**Comment by webknjaz** [comment]
The readme is now in markdown and this PR is no longer relevant.

**Comment by samccann** [comment]
Thanks @whoami-anoint for the work you've done here and sorry your work got caught in the middle of another significant update to this file (see https://github.com/ansible/ansible/pull/81217).

**Pull request closed without merging**
