### PR TITLE
Add run_once as a valid TaskInclude keyword

### PR DESCRIPTION
**Pull request by jimmymccrory**
##### SUMMARY

run_once is a valid keyword for task includes that was missing from the VALID_INCLUDE_KEYWORDS list.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/playbook/task_include.py
##### ANSIBLE VERSION

```paste below
2.8
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by bcoca — CHANGES_REQUESTED** [review]
<strike>so while 'run_once' works on `include_tasks `it does not work correctly.

It always runs the include itself AND the included tasks as they had `run_once: true`, it should not do both, the included_tasks should only run with `run_once: true` if this is set on the `apply` or otherwise, but not on the `include_tasks` itself.</strike>

nvmd, my testing was flawed, they do act differently, but probably in a way user can be surprised, w/o the `apply` it will run the tasks only once and apply results ONLY to the first host while skipping other hosts

**Comment by bcoca** [comment]
```yaml
- hosts: all
  gather_facts: false
  vars:
    lola: untouched
  tasks:
    - include_tasks: test.yml
      run_once: true
      args:
        apply:
            run_once: true

    - debug: var=lola

- hosts: all
  gather_facts: false
  vars:
    lola: untouched
  tasks:
    - include_tasks: test.yml
      run_once: true

    - debug: var=lola
```
test.yml
```
- set_fact: lola=wiseman
```
^ there should be a difference in this run between, but both sets of include/set_fact/debug result in the same.

**Review by sivel — APPROVED** [review]
@bcoca and I have discussed this a bit, and although the behavior could be considered confusing by some, it seems to agree with how we expect the run_once keyword to work in conjunction with include_tasks.

To clarify further, I have added integration tests to this PR that are to be used as baseline documentation as to their interaction.

**Comment by sivel** [comment]
I'm temporarily holding on merging this.  This may open a can of worms that I hoped to avoid, such as also allowing `delegate_to`, which in the general case I'm not sure makes sense.

**Review by bcoca — APPROVED** [review]

**Pull request merged**
