### PR TITLE
WIP Try to fix mysql_user support REQUIRE NONE to remove a REQUIRE SSL "GRANT"

### PR DESCRIPTION
**Pull request by Alexander198961**
##### SUMMARY
https://github.com/ansible/ansible/issues/29811
COMPONENT NAME
mysql_user

ANSIBLE VERSION
ansible 2.5.0

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/70456/34/tests

**Comment by Alexander198961** [comment]
mysql set field ssl_type: ANY when REQUIRESSL and set empty filed when REQUIRE none

**Comment by Alexander198961** [comment]
@Jmainguy  can you pls review ?

**Comment by gundalow** [comment]
@Alexander198961 Would you be able to rebase?

We have a [MySQL Working Group](https://github.com/ansible/community/wiki/mysql) that's working through the backlog of MySQL PRs.

As this PR include tests I think it should be easy to get in.

**Comment by Alexander198961** [comment]
Ok I will do

**Comment by Alexander198961** [comment]
I will open another one and will resolve conflict

**Pull request closed without merging**
