### PR TITLE
WIP: VMware: suboption args

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
1. Hardware

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
2.7-devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@dagwieers  As per our discussion on last PR, I am starting this subargument in vmware_guest.

**Comment by dagwieers** [comment]
@Akasurde Why did you close this ?

**Comment by Akasurde** [comment]
I think we need more testing done for vmware_guest before starting to work on this.

**Comment by dagwieers** [comment]
What kind of testing ? More integration tests ?

Because the earlier we test this in the devel branch, the more people can report experiences, and we can fix those regressions. Especially since it doesn't really change how the module behaves, but only how parameters are being interpreted.

Unless you want to move it to v2.8 instead ?

**Pull request closed without merging**
