### PR TITLE
openbsd_pkg: add upgrade argument.

### PR DESCRIPTION
**Pull request by eest**
Running the module with the argument "upgrade=yes" invokes an upgrade of
all installed packages.

While here clean up some comments.

Functionality requested by @qbit.

### CODE REVIEW

**Comment by jimi-c** [comment]
I have somewhat refactored this PR into this branch: https://github.com/jimi-c/ansible/compare/eest-openbsd_pkg-upgrade 

My reasoning here was to make the functionality more like that of yum, which allows a system-wide update by using `name=*`, so I thought it would make more sense to follow that convention. @eest if you could give this a test I'd appreciate it, as well as any further thoughts on this.

**Comment by eest** [comment]
I really like the different approach of your diff as it makes the argument handling simpler.

I have a few pointers though:
- On line 333 you make the "changed" variable contain the result of a match, this seems to break when passed to module.exit_json() at the end (if a match was found):

```
 192.168.1.103 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1395944613.95-272318174184974/openbsd_pkg\", line 1568, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1395944613.95-272318174184974/openbsd_pkg\", line 398, in main\r\n    module.exit_json(**result)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1395944613.95-272318174184974/openbsd_pkg\", line 1308, in exit_json\r\n    print self.jsonify(kwargs)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1395944613.95-272318174184974/openbsd_pkg\", line 1295, in jsonify\r\n    return json.dumps(data)\r\n  File \"/usr/local/lib/python2.7/json/__init__.py\", line 231, in dumps\r\n    dictionaries will be sorted by key.\r\n  File \"/usr/local/lib/python2.7/json/encoder.py\", line 201, in encode\r\n    return encode_basestring_ascii(o)\r\n  File \"/usr/local/lib/python2.7/json/encoder.py\", line 264, in iterencode\r\n    self.skipkeys, self.allow_nan)\r\n  File \"/usr/local/lib/python2.7/json/encoder.py\", line 178, in default\r\n    else:\r\nTypeError: <_sre.SRE_Match object at 0x81e2ae58> is not JSON serializable\r\n", 
    "parsed": false
}
```

... and if a match was not found 'null' is returned instead:

```
$ ansible -i hosts -c ssh -u root -m openbsd_pkg -a 'name=* state=latest' 192.168.1.103
192.168.1.103 | success >> {
    "changed": null, 
    "name": "*", 
    "state": "latest"
}
```

Can we skip that change for now? It seems more like general cleanup, and also, if we change that one instance there are a lot of other places that need similar treatment to make the module behave in a consistent way. I think that might be suited for a separate PR.
- Given that this removes the need of a new argument, we can probably remove some logic by using "required=True" for both the name and state argument again.

**Comment by eest** [comment]
Err, it seems i messed up a push pretty badly there, trying to figure out how to fix that.

**Comment by eest** [comment]
See diff for my idea how to simplify the logic when using required=True, I have not done anything about the "changed" problem yet. To be clear this has not been fully tested yet either because of that.

**Comment by eest** [comment]
@jimi-c: Any input on this? :)

**Comment by jimi-c** [comment]
@eest sorry, I will try to get to reviewing this sometime this upcoming week. Thanks!

**Comment by eest** [comment]
@jimi-c: I'm guessing you are busy with other stuff :).

To get this thing on the road i have now reverted the "changed" stuff from your diff per the problem report above. I have also performed a complete testing run of the current state of the code and am OK with this going in.

Would be happy if this would get merged soon.

**Comment by jimi-c** [comment]
@eest yes, just working through P2 issues now, so we'll get this in queue for testing as soon as possible.

**Comment by eest** [comment]
@jimi-c: Just an update: Given PR #8991 it would be nice if the merging of this patch could be done soon so we dont end up making changes via the other PR that makes the patches incompatible.

**Comment by eest** [comment]
... and now i noticed someone has introduced merge conflicts already. I will try to look into this tonight.

**Comment by eest** [comment]
I have now performed a rebase of the branch. The conflicts were caused by changes to the EXAMPLES text, so I am still OK with this going in.

**Comment by eest** [comment]
Closing this PR. Changes will be handled in PR ansible/ansible-modules-extras#3.

**Pull request closed without merging**
