### PR TITLE
docker_swarm_service: Specify choices on update_order

### PR DESCRIPTION
**Pull request by hannseman**
##### SUMMARY

Specify choices on update_order:
* stop-first
* start-first
https://docs.docker.com/engine/reference/commandline/service_create/

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

docker_swarm_service

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
The choices have been there in the past, but were removed in #45674 (more precisely this commit: https://github.com/ansible/ansible/pull/45674/commits/63641a91e18d3aa0d7bc92af69e885b18c75c5f1). I'm not sure why we removed the `choices` there as well; @dariko do you remember (it was your PR)? (Removing the default value makes sense.)

**Comment by hannseman** [comment]
@felixfontein though I checked if they were present in 2.7. I’ll remove the changelog.

**Review by jwitko — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@hannseman thanks for fixing this!
@gundalow @jwitko thanks for reviewing!

**Pull request merged**
