### PR TITLE
Use loop instead of obsolete with_items in example

### PR DESCRIPTION
**Pull request by bmillemathias**
##### SUMMARY
Use loop instead of obsolete with_items in example

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION
ansible 2.5 upward

### CODE REVIEW

**Comment by resmo** [comment]
LGTM

**Review by resmo — APPROVED** [review]

**Comment by acozine** [comment]
Per discussion today, we don't want to change all the `with_*` examples to `loop` at the moment. I'm going to merge this change, which shows the most straightforward type of loop.

**Comment by bmillemathias** [comment]
Hello @acozine 
To which discussion are you refering to ? I wanted to replace with_* examples by loop examples in the modules, so if you have the minutes I can read them. 

thanks

**Comment by sivel** [comment]
@bmillemathias a few things to note:

1. `with_` syntax has not been deprecated, and `loop` is not yet a full replacement for `with_`
1. Generally speaking, any use of `with_` that is covered in the [2.5 porting guide](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#migrating-from-with-x-to-loop) is generally OK to switch over to loop.
1. Any `with_` statement, that requires using `lookup` within `loop` should _**not**_ be converted
1. We are still deciding what UX changes can be made to `loop`, to enable `loop` to _**eventually**_ replace `with_`, but `with_` syntax will likely have a longer deprecation cycle than usual (4 releases now, `with_` might get something like 6)
1. You need to be careful when switching `with_items` to a straight `loop`, as `with_items` performed implicit flattening.  `with_list` and `loop` are equivalent.  `with_items` may require use of `loop` + `flatten` to match the exact outcome.

**Pull request merged**
