### PR TITLE
Add an example for the debugging module

### PR DESCRIPTION
**Pull request by remyleone**
+label: docsite_pr

##### SUMMARY

Could we add examples in this section? I think there is room for confusion depending on how the JSON is formatted for instance.

##### ISSUE TYPE

- Docs Pull Request

References:

https://docs.ansible.com/ansible/2.3/dev_guide/developing_modules_general.html
you can also pipe your JSON to python: `echo "{ ... }" | python path/to/your/module.py`

### CODE REVIEW

**Comment by remyleone** [comment]
I've tried to use a JSON that stay on a single line but it still does not work :( @acozine

**Comment by acozine** [comment]
@remyleone I think some examples here would be a great idea - thanks for starting this PR.

I'm not sure what trouble you ran into (did you remove some commits that were failing CI?). If I can help jump-start this effort, or debug any rST/docs-build issues, please reach out on #ansible-docs on freenode IRC.

**Comment by samccann** [comment]
Hi @remyleone - did you intend to add more examples here or is this ready for review and merge?

**Comment by remyleone** [comment]
ready for review if you are :)

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks for the docs patch!

**Pull request merged**
