### PR TITLE
Module zabbix_maintenance to create maintenance windows in zabbix

### PR DESCRIPTION
**Pull request by abulimov**
Hello. I've wrote simple module to create and remove maintenance windows in Zabbix. It uses zabbix-api python module.

With this module you can, for example, set your hosts to maintenance mode before rolling update, and delete maintenance window after update.

### CODE REVIEW

**Comment by gregbuehler** [comment]
+1

**Comment by mpdehaan** [comment]
Just thinking aloud, do we want to just call this one "zabbix" and try to make the API signature somewhat resemble the nagios module, or no?

(Haven't reviewed yet, just asking devil's advocate questions).

**Comment by abulimov** [comment]
I've called it zabbix_maintenance because Zappix API is very reach, and in the future there could be, for example, zabbix_host module to create new hosts in Zabbix from Ansible. About module api signature - i've thought about unification with nagios module, but nagios module is able to manage downtime and silence checks, while this zabbix_maintenance module is made for manipulating Zabbix manintenance window for host/group of hosts. So we can't call actions "disable_alert" or "silence", because in Zabbix we are not silencing or disabling alerts. Zabbix can be configured to keep sending alerts while in mainenance mode. And in Zabbix we can disable some triggers for particular host, but this module does not do it.

**Comment by cove** [comment]
@abulimov fyi, we'll be submitting a zabbix_host like module in the next couple of weeks, we're just finishing it up and testing right now.

**Comment by cove** [comment]
@mpdehaan @abulimov  re: separate vs. combined modules for Zabbix; I'd agree with abulimov's approach of separate modules, otherwise I think we'd end up with a module with a lot of args and it could be confusing which ones go with which mode the module is in... in the same sense there isn't one aws or gce module for example. my 2c anyway...

**Comment by abulimov** [comment]
@cove, zabbix_host module will be great. I hope we'll finally get a full set of zabbix modules to set up complete monitoring environment with Ansible.

**Comment by cove** [comment]
@abulimov we've submitted our host and group modules in #6034.

**Comment by jctanner** [comment]
@abulimov and @cove any updates here or is this in the final state?

**Comment by jimi-c** [comment]
As noted in #6034, we'll wait until you guys come to a consensus on param names and update your PRs. Thanks!

**Comment by mpdehaan** [comment]
Hi folks, if you can comment on this and #6034 that would be appreciated.  Otherwise this one may get closed soon -- though we would welcome resubmission should things get resolved and figured out.

Thank you!

**Comment by abulimov** [comment]
Well, this module is complete, and we have a consensus with @cove about param names, so I hope this is the final state of this module.

**Comment by cove** [comment]
@mpdehaan @abulimov Sorry the delays here are on my end, we should be able to get this wrapped up by end of next week.

**Comment by mpdehaan** [comment]
Seems to have been no activity on this for a while, curious if any further info is available else we will close this in the next sweep.

**Comment by abulimov** [comment]
I don't know what prevents my module from being merged. It's been in production for 6 month now, and I have no problems with it so far.

**Comment by cove** [comment]
I think the thought was that we'd commit this module and the other zabbix modules all at the same time, so if any changes needed to be made between all of them, such as adjustments to the interfaces for consistency, that we wouldn't break any playbooks using an older version. 

I've been OOO for a few weeks, but will be back next week, and will commit some fixes to the other modules. Then maybe we can get all the zabbix modules wrapped up, it's taken a lot longer than I expected honestly.

**Comment by mpdehaan** [comment]
This is now merged for 1.8 devel, apologies on the time windows as we have been prioritizing a giant queue based on some heuristics that didn't favor merging some easy things like this, which we're now correcting.  Happy to have this in and thanks all for working on it!

**Comment by mpdehaan** [comment]
GitHub didn't pick up the merge, so closing this one manually.  Thanks!

**Pull request closed without merging**
