### PR TITLE
Fix interface method change

### LINKED ISSUE #38692: interfaces_file changing method is not possible
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
interfaces_file
##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 43cbcbcc75) last updated 2018/03/15 23:05:39 (GMT +200)
  config file = /home/gt0015/.ansible.cfg
  configured module search path = ['/home/gt0015/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /data/development/ansible/src/lib/ansible
  executable location = /data/python/envs/ansible/bin/ansible
  python version = 3.6.4 (default, Mar 25 2018, 13:14:42) [GCC 8.0.1 20180222 (Red Hat 8.0.1-0.16)]
```

##### CONFIGURATION
```
[default]
stdout_callback = full_skip
display_skipped_hosts = False
```
##### OS / ENVIRONMENT
From: 
```
Linux t470p.homegrown-lan 4.16.0-0.rc7.git0.1.fc28.x86_64 #1 SMP Mon Mar 26 15:01:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
To:  
``` 
Linux rpi-1 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
```
##### SUMMARY
Changing the method of an iface (dhcp, manual, static) not possible.
When looking at modules output the option that should be set is `method`.
```
        "ifaces": {
            "eth0": {
                "address": "192.168.178.111",
                "address_family": "inet",
                "allow-hotplug": "wlan0",
                "down": [],
                "method": "static",
                "netmask": "255.255.255.0",
                "post-up": [],
                "pre-up": [],
                "up": []
            },
```
##### STEPS TO REPRODUCE
```yaml
- hosts: rpi
  become: true
  tasks:
      - debug: msg="{{ ip }}"
      - interfaces_file: 
            iface: "{{ iface }}"
            option: "address"
            value: "{{ ip }}"
      - interfaces_file:
            iface: "{{ iface }}"
            option: "netmask"
            value: "255.255.255.0"
      - interfaces_file:
            iface: "{{ iface }}"
            option: "method"
            value: "static"
      - interfaces_file:
        register: result
      - debug: msg="{{ result }}"
```
inventory file:
```
[rpi]
rpi-1 ip=192.168.178.111 iface=eth0
```
##### EXPECTED RESULTS
```
iface eth0 inet static
    address 192.168.178.111
    netmask 255.255.255.0
```
##### ACTUAL RESULTS
```
# allow-hotplug eth0
iface eth0 inet dhcp

allow-hotplug wlan0
address 192.168.178.111
netmask 255.255.255.0
method static
```
allow-hotplug issue seems already referenced in #37846

### PR DESCRIPTION
**Pull request by obourdon**
##### SUMMARY
Fixes [#38692](https://github.com/ansible/ansible/issues/38692)

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
interfaces_file

##### ANSIBLE VERSION
```
ansible 2.6.0 (work e2aa1155ba) last updated 2018/04/19 09:51:12 (GMT +200)
  config file = None
  configured module search path = [u'/Users/olivierbourdon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/olivierbourdon/Documents/WORK/OpenNext/TECH/CODE/ANSIBLE/0-REF-ansible/lib/ansible
  executable location = /Users/olivierbourdon/Documents/WORK/OpenNext/TECH/CODE/ANSIBLE/0-REF-ansible/bin/ansible
  python version = 2.7.14 (default, Sep 22 2017, 00:06:07) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### ADDITIONAL INFORMATION
Before:
```
iface eth0 inet dhcp
    address 192.168.178.111
    netmask 255.255.255.0
   method static
```

After:
```
iface eth0 inet static
    address 192.168.178.111
    netmask 255.255.255.0
```

### CODE REVIEW

**Comment by hryamzik** [comment]
@obourdon  great, thanks! Can I also ask you to add related tests?

**Comment by obourdon** [comment]
@hryamzik please review, thanks

**Comment by hryamzik** [comment]
LGTM

Except I'd love to see tests for this case.

**Comment by obourdon** [comment]
@hryamzik oops deeply sorry about forgetting the tests, will add them in another PR as this one seems to have been merged already

**Pull request merged**
