### PR TITLE
Make --step easier to use

### PR DESCRIPTION
**Pull request by amenonsen**
##### SUMMARY
1. Switch to default 'y'
2. Less verbose/duplicated task banner output
3. Display the task banner after templating
4. Ignore keystrokes while a step is running

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.5.0 (easy-step acec9fc9ef) last updated 2017/09/14 07:31:30 (GMT +550)
  config file = None
  configured module search path = [u'/home/ams/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ams/build/ansible/lib/ansible
  executable location = /home/ams/build/ansible/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### ADDITIONAL INFORMATION

Before:
```
Perform task: TASK: platforms/aws : Translate platform-specific variables names (N)o/(y)es/(c)ontinue: 

Perform task: TASK: platforms/aws : Translate platform-specific variables names (N)o/(y)es/(c)ontinue: ****************************************************************************************
Perform task: TASK: platforms/aws : Set ip_addresses to [] (N)o/(y)es/(c)ontinue: 

Perform task: TASK: platforms/aws : Set ip_addresses to [] (N)o/(y)es/(c)ontinue: *************************************************************************************************************
Perform task: TASK: platforms/aws : Set private IP address (N)o/(y)es/(c)ontinue: 

Perform task: TASK: platforms/aws : Set private IP address (N)o/(y)es/(c)ontinue: *************************************************************************************************************
Perform task: TASK: platforms/aws : Set public IP address if available (N)o/(y)es/(c)ontinue: 

Perform task: TASK: platforms/aws : Set public IP address if available (N)o/(y)es/(c)ontinue: *************************************************************************************************
Perform task: TASK: platforms/aws : Add private_ip to the address list (N)o/(y)es/(c)ontinue: 

Perform task: TASK: platforms/aws : Add private_ip to the address list (N)o/(y)es/(c)ontinue: *************************************************************************************************
Perform task: TASK: platforms/aws : Add public_ip to the address list (N)o/(y)es/(c)ontinue: 

Perform task: TASK: platforms/aws : Add public_ip to the address list (N)o/(y)es/(c)ontinue: **************************************************************************************************
Perform task: TASK: platforms/aws : Set primary IP address (N)o/(y)es/(c)ontinue: 

Perform task: TASK: platforms/aws : Set primary IP address (N)o/(y)es/(c)ontinue: *************************************************************************************************************
```
After:
```
TASK: platforms/aws : Translate platform-specific variables names
(Y)es/(n)o/(c)ontinue: n

TASK: platforms/aws : Set ip_addresses to []
(Y)es/(n)o/(c)ontinue: n

TASK: platforms/aws : Set private IP address
(Y)es/(n)o/(c)ontinue: n

TASK: platforms/aws : Set public IP address if available
(Y)es/(n)o/(c)ontinue: n

TASK: platforms/aws : Add private_ip to the address list
(Y)es/(n)o/(c)ontinue: n

TASK: platforms/aws : Add public_ip to the address list
(Y)es/(n)o/(c)ontinue: n

TASK: platforms/aws : Set primary IP address
(Y)es/(n)o/(c)ontinue: n
```

### CODE REVIEW

**Comment by dagwieers** [comment]
I like these improvements, the only thing I would change is to remove the newline between tasks. The reason for me is that there's no value in that empty line and it uses precious screen estate. The only important information for the user (in every iteration) are the last 2 lines, not the previous lines. So the newline does not add any value when interactively processing `--step`.

**Comment by amenonsen** [comment]
@dagwieers Thanks for the review. I've eliminated the ``\n``.

It would have been nicer still to have something like this:
```
TASK [abc] ************************************************************************************************************************************************************************************
(Y)es/(n)o/(c)ontinue: n
TASK [bcd] ************************************************************************************************************************************************************************************
(Y)es/(n)o/(c)ontinue: y
```
but the banner is displayed by the output callback, and it would have required more surgery to do something like that than I felt was justified for ``--step``.

**Comment by dagwieers** [comment]
Yup, that was my other consideration. Hooking it into the callback plugin.
It shouldn't be that hard though ?

**Comment by amenonsen** [comment]
You're right, it isn't. I just need to move the ``_take_step`` call a little further down. Testing now.

**Comment by dagwieers** [comment]
Let me know if I can help.

**Comment by amenonsen** [comment]
Looks like it works.
```
TASK [abc] ************************************************************************************************************************************************************************************
(Y)es/(n)o/(c)ontinue: y
ok: [localhost] => {
    "inventory_hostname": "localhost"
}
```

**Review by dagwieers — APPROVED** [review]
LGTM

**Comment by maxamillion** [comment]
My only concern is changing the default from `(N)o` to `(Y)es` but otherwise +1

**Comment by amenonsen** [comment]
@maxamillion The default of 'n' means that you have to type 'y' and hit enter for every task that you want to execute. I tend to execute many more tasks than I skip when debugging using --step, but I'm sure others may have different experiences.

I had failed to consider that changing the default may also negatively affect people who use --step without reading the prompt or the output too closely, but do so on playbooks where a task being executed unintentionally would cause severe problems.

As an experiment, I changed the code so that the initial default remains 'n', but we remember whatever the last selection was, and that becomes the default for the next step. In other words, you can type 'y<enter>' once and then keep hitting enter to execute subsequent tasks. Then you can select 'n<enter>' for a particular task, and just hitting enter would skip subsequent tasks.

However, I must admit that this change of behaviour could also be a problem for people who are dependent on 'n' being the persistent default.

I am extremely uninterested in adding a configuration option to select the behaviour of --step, as has been suggested, so I am closing this PR instead.

**Pull request closed without merging**
