### PR TITLE
Add some python packages too

### PR DESCRIPTION
**Pull request by miekg**
When starting from scratch those packages must be installed too.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Those are things the deb requires, but are they needed to build it?

Note: I'm largely a CentOS user, so forgive my ignorance.

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [ansible] Add some python packa..." ]

> Those are things the deb requires, but are they needed to build it?

yep, the configure step barfs when those pythons pkgs are not found.

 Regards,

## 

```
Miek Gieben                                               http://miek.nl
```

**Comment by mpdehaan** [comment]
Done!

**Comment by mpdehaan** [comment]
this will be on the docsite the next time I do a rebuild, which should be soon

**Pull request merged**
