### PR TITLE
vca_vapp: Connecting app network to vApp and VM after vApp creation

### LINKED ISSUE #19538: vmware/vca_vapp: network not attached to Vapp during creation
_From @kaneda-fr on May 10, 2016 7:58_

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

cloud/vmware/vca_vapp.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0 (stable-2.1 2c8715178f)
```
##### OS / ENVIRONMENT

OSX El Capitan: Darwin  15.4.0 Darwin Kernel Version 15.4.0
##### SUMMARY

When creating anew vApp and and passing an existing omg VDC network name, the app is created without attaching the network .

Looking into pyvcloud vckoudair.py, the function create_vapp seems to do nothing with the network_name, so we may need to add instruction to attach network after the VApp creation.
##### STEPS TO REPRODUCE

```
- hosts: localhost
  connection: local
  vars:
  tasks:
   - vca_vapp:
       state: deployed
       operation: noop
       org: 'sita_cloud_eng_0003'
       vdc_name: 'VDC_IAAS_CLOUD_ENG_0003'
       vapp_name: 'Test_API'
       catalog_name: "Public catalog"
       template_name: CentOS_6.5_64bits
       vm_name: VM-CentOS-Seb
       vm_cpus: 2
       vm_memory: 2096
       username: xxx
       password: yay
       api_version: 5.6
       host: zzz
       service_type: vcd
       network_name: VDCNET
       network_mode: pool
       gateway_name: EG_CLOUD_ENG_0003

     register: myvm

   - debug: var=myvm
```
##### EXPECTED RESULTS

Network passed as option via network_name should be attached to Vapp during creation
##### ACTUAL RESULTS

Network passed as option via network_name is not attached at Vapp creation.

_Copied from original issue: ansible/ansible-modules-extras#2203_

### PR DESCRIPTION
**Pull request by kaneda-fr**
Attaching network to VAPP and VM and returning assigned VM ip as fact vm_ip.

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME

modules/cloud/vmware/vca_vapp.py 

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Connecting app network to vApp and VM after vApp creation
Returning the IP assigned to the VM as fact 'vm_ip'

Only works if network_mode is set to  'pool' or 'dhcp'.

Fixes #19538 

```

```

### CODE REVIEW

**Comment by Nosmoht** [comment]
I was just testing with this patch. Works great if pyvcloud version is 16. I tested also with 18.2.2 and 18.2.1 where it does not work. So maybe there should be a hint to have pyvcloud==16 installed.

Good work @kaneda-fr 

_shipit_

**Comment by Akasurde** [comment]
@kaneda-fr Can you please rebase this branch and address above comment ?

**Comment by kaneda-fr** [comment]
@Nosmoht I have fixed it in a branch rebased on 2.4
https://github.com/kaneda-fr/ansible/tree/rebase-2.4
let me know if that would work for you.

**Comment by Akasurde** [comment]
@kaneda-fr Take a look, I modified some of things. Let me know if it looks good to you.

**Comment by kaneda-fr** [comment]
Thanks @Akasurde, looks good and will test it.

Also there is an issue with latest VCD API where network_mode must be set to 'bridged' when calling module.vca.create_vapp.

**Comment by Akasurde** [comment]
@kaneda-fr Any news ?

**Comment by kaneda-fr** [comment]
@Akasurde removed a duplicate check on task status and also updated the parameters for vca.create_vapp that requires network_mode as 'bridged' rather than the IP allocation method.
Looks like in the recent VCD versions they are some check enforced at VCD level on that parameters.

I have tested ok against VCD 8.20 and do not have access against older version to test that change.

**Comment by Akasurde** [comment]
rebuild_merge

**Comment by Akasurde** [comment]
rebuild_merge

**Comment by Akasurde** [comment]
@mattclay I unable to understand why CI job was cancelled. Could you please help me with this?

**Comment by mattclay** [comment]
@Akasurde I'm investigating. I'm seeing this behavior on another PR as well.

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Comment by Akasurde** [comment]
@kaneda-fr Thanks for the contribution and patience.

**Comment by kaneda-fr** [comment]
@Akasurde Thanks a lot !

**Pull request merged**
