### PR TITLE
Backports related to network-integration testing for Cisco IOS

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Backports needed to fix ios network-integration tests.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test, ios network-integration

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now ea99a5f437596e1ee54c3eb450150b5c83019c82

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now eb07a005c03fe13bf910d21033e5871db7f5d5f9

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 33ac67b5923c594ad62b1fd824c0a57347878bc3

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 4fe57decb27de346969e162dde44606714e8f719

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 384122e2f6c45e7d7bd278f8a85661e88182e08f

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now a1c419afee69e8b1d312dfcf8dc1eea42787f5db

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 4e2b279f913a4ff7be01b6830494655c71bc7f1c

**Comment by pabelanger** [comment]
This has also made all of our network-integration testing for IOS green, confirming everything worked as expected.

**Comment by pabelanger** [comment]
recheck

**Comment by abadger** [comment]
Merged for the 2.8.2 release.

**Pull request merged**
