### PR TITLE
junos_facts: Add Hardware facts.

### PR DESCRIPTION
**Pull request by dteach**
##### SUMMARY
This PR mirrors one of the facts returned in the junos-eznc library, "has_2RE".  This fact is useful when making a decision whether or not to enable high-availability concept like Graceful Routing Engine Switchover, or Non-Stop Routing.
This PR also adds useful information about the installed hardware modules, and more specifically the operational status of the routing engine(s).  This info could be used for a number of reasons. For example, identifying hardware that's no longer supported, providing serial numbers for a module RMA,  CPU load monitoring before an upgrade.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

/modules/network/junos/junos_facts.py

##### ANSIBLE VERSION

```
ansible 2.5.0 (add_RE_facts 915878db90) last updated 2017/09/13 10:59:50 (GMT -700)
  config file = /mnt/ch/repos/git/ansible/ansible.cfg
  configured module search path = [u'/home/dteach/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/ch/repos/git/ansible/lib/ansible
  executable location = ./bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

# before
```
dteach@is-ansible junos_ansible]$ ansible-playbook playbooks/site.yml --check -l cc-bdr1-gw.net.uoregon.edu -vvvv
Using /opt/junos_ansible/ansible.cfg as config file
statically included: /opt/junos_ansible/playbooks/roles/juniper/tasks/ztp.yml
statically included: /opt/junos_ansible/playbooks/roles/juniper/tasks/get_facts.yml
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: site.yml *****************************************************************************************************************************************************************************************
1 plays in playbooks/site.yml

PLAY [all] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<cc-bdr1-gw.net.uoregon.edu> ESTABLISH LOCAL CONNECTION FOR USER: dteach
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'echo ~ && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home13/dteach/.ansible/tmp/ansible-tmp-1505328334.05-125787784935802 `" && echo ansible-tmp-1505328334.05-125787784935802="` echo /home13/dteach/.ansible/tmp/ansible-tmp-1505328334.05-125787784935802 `" ) && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> PUT /tmp/tmpE0vSh0 TO /home13/dteach/.ansible/tmp/ansible-tmp-1505328334.05-125787784935802/setup.py
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'chmod u+x /home13/dteach/.ansible/tmp/ansible-tmp-1505328334.05-125787784935802/ /home13/dteach/.ansible/tmp/ansible-tmp-1505328334.05-125787784935802/setup.py && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '/usr/bin/python /home13/dteach/.ansible/tmp/ansible-tmp-1505328334.05-125787784935802/setup.py; rm -rf "/home13/dteach/.ansible/tmp/ansible-tmp-1505328334.05-125787784935802/" > /dev/null 2>&1 && sleep 0'
ok: [cc-bdr1-gw.net.uoregon.edu]
META: ran handlers

TASK [juniper : template bootstrap configuration for zero touch provisioning] ******************************************************************************************************************************
task path: /opt/junos_ansible/playbooks/roles/juniper/tasks/ztp.yml:1
skipping: [cc-bdr1-gw.net.uoregon.edu] => {
    "changed": false,
    "skip_reason": "Conditional result was False",
    "skipped": true
}

TASK [juniper : get junos facts] ***************************************************************************************************************************************************************************
task path: /opt/junos_ansible/playbooks/roles/juniper/tasks/get_facts.yml:2
<cc-bdr1-gw.net.uoregon.edu> using connection plugin netconf
<cc-bdr1-gw.net.uoregon.edu> socket_path: /home13/dteach/.ansible/pc/ea3dbdecc5
open_session() returned 0 ok
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/junos/junos_facts.py
<cc-bdr1-gw.net.uoregon.edu> ESTABLISH LOCAL CONNECTION FOR USER: dteach
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'echo ~ && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home13/dteach/.ansible/tmp/ansible-tmp-1505328336.39-130057322933903 `" && echo ansible-tmp-1505328336.39-130057322933903="` echo /home13/dteach/.ansible/tmp/ansible-tmp-1505328336.39-130057322933903 `" ) && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> PUT /tmp/tmpwDovC9 TO /home13/dteach/.ansible/tmp/ansible-tmp-1505328336.39-130057322933903/junos_facts.py
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'chmod u+x /home13/dteach/.ansible/tmp/ansible-tmp-1505328336.39-130057322933903/ /home13/dteach/.ansible/tmp/ansible-tmp-1505328336.39-130057322933903/junos_facts.py && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '/usr/bin/python /home13/dteach/.ansible/tmp/ansible-tmp-1505328336.39-130057322933903/junos_facts.py; rm -rf "/home13/dteach/.ansible/tmp/ansible-tmp-1505328336.39-130057322933903/" > /dev/null 2>&1 && sleep 0'
ok: [cc-bdr1-gw.net.uoregon.edu] => {
    "ansible_facts": {
        "ansible_net_filesystems": [
            "/dev/ad0s1a",
            "devfs",
            "/dev/md0",
            "/dev/md1",
            "/dev/md2",
            "/dev/md3",
            "/dev/md4",
            "/dev/md5",
            "/dev/md6",
            "/dev/md7",
            "/dev/md8",
            "/dev/md9",
            "/dev/md10",
            "/dev/md11",
            "/dev/md12",
            "/dev/md13",
            "/dev/md14",
            "/dev/md15",
            "/dev/md16",
            "/dev/md17",
            "/dev/md18",
            "/dev/md19",
            "/dev/md20",
            "/dev/md21",
            "/dev/md22",
            "/dev/md23",
            "/dev/md24",
            "/dev/md25",
            "/dev/md26",
            "/dev/ad0s1e",
            "procfs",
            "/dev/ad1s1f",
            "/var/jails/rest-api",
            "/var/jail",
            "/var/log",
            "devfs",
            "/var/jail/etc",
            "/var/jail/run",
            "/var/jail/tmp",
            "/var/tmp",
            "devfs",
            "/dev/md27",
            "/dev/md28",
            "/dev/md29",
            "/dev/md30",
            "/dev/md31",
            "/dev/md32",
            "/dev/md33",
            "/dev/md34",
            "/dev/md35",
            "/dev/md36",
            "/dev/md37",
            "/dev/md38"
        ],
        "ansible_net_gather_subset": [
            "hardware",
            "default"
        ],
        "ansible_net_hostname": "cc-bdr1-gw",
        "ansible_net_memfree_mb": 8723312,
        "ansible_net_memtotal_mb": 16741064,
        "ansible_net_model": "ex9208",
        "ansible_net_serialnum": "JN125F148RFB",
        "ansible_net_version": null
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "config_format": "text",
            "gather_subset": [
                "hardware"
            ],
            "host": null,
            "password": null,
            "port": null,
            "provider": {
                "config_format": "text",
                "host": "cc-bdr1-gw.net.uoregon.edu",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 22,
                "ssh_keyfile": "~/.ssh/nts-netconf_rsa",
                "timeout": 300,
                "transport": null,
                "username": "nts-netconf"
            },
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": null,
            "username": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************************
cc-bdr1-gw.net.uoregon.edu : ok=2    changed=0    unreachable=0    failed=0
```
# after
```
(11:48 dteach@teach ansible) > ansible-playbook ~/ansible/playbooks/site.yml -i ~/ansible/inventory/hosts --vault-password-file=~/.vault_pass.txt  --diff --check -l cc-bdr1-gw.net.uoregon.edu -vvvv
ansible-playbook 2.5.0 (add_RE_facts 915878db90) last updated 2017/09/13 10:59:50 (GMT -700)
  config file = /mnt/ch/repos/git/ansible/ansible.cfg
  configured module search path = [u'/home/dteach/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/ch/repos/git/ansible/lib/ansible
  executable location = ./bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Using /mnt/ch/repos/git/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /mnt/ch/repos/git/is_nts/junos_ansible_dteach/inventory/hosts inventory source with ini plugin
statically imported: /mnt/ch/repos/git/is_nts/junos_ansible_dteach/playbooks/roles/juniper/tasks/ztp.yml
statically imported: /mnt/ch/repos/git/is_nts/junos_ansible_dteach/playbooks/roles/juniper/tasks/get_facts.yml
Loading callback plugin default of type stdout, v2.0 from /mnt/ch/repos/git/ansible/lib/ansible/plugins/callback/__init__.py

PLAYBOOK: site.yml *****************************************************************************************************************************************************************************************
clear: <built-in method clear of dict object at 0x7f1bccb197f8>
copy: <built-in method copy of dict object at 0x7f1bccb197f8>
fromkeys: <built-in method fromkeys of type object at 0x906f00>
get: <built-in method get of dict object at 0x7f1bccb197f8>
has_key: <built-in method has_key of dict object at 0x7f1bccb197f8>
items: <built-in method items of dict object at 0x7f1bccb197f8>
iteritems: <built-in method iteritems of dict object at 0x7f1bccb197f8>
iterkeys: <built-in method iterkeys of dict object at 0x7f1bccb197f8>
itervalues: <built-in method itervalues of dict object at 0x7f1bccb197f8>
keys: <built-in method keys of dict object at 0x7f1bccb197f8>
pop: <built-in method pop of dict object at 0x7f1bccb197f8>
popitem: <built-in method popitem of dict object at 0x7f1bccb197f8>
setdefault: <built-in method setdefault of dict object at 0x7f1bccb197f8>
update: <built-in method update of dict object at 0x7f1bccb197f8>
values: <built-in method values of dict object at 0x7f1bccb197f8>
viewitems: <built-in method viewitems of dict object at 0x7f1bccb197f8>
viewkeys: <built-in method viewkeys of dict object at 0x7f1bccb197f8>
viewvalues: <built-in method viewvalues of dict object at 0x7f1bccb197f8>
1 plays in /home/dteach/ansible/playbooks/site.yml

PLAY [all] *************************************************************************************************************************************************************************************************
Trying secret FileVaultSecret(filename='/home/dteach/.vault_pass.txt') for vault_id=default

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
Using module file /mnt/ch/repos/git/ansible/lib/ansible/modules/system/setup.py
<cc-bdr1-gw.net.uoregon.edu> ESTABLISH LOCAL CONNECTION FOR USER: dteach
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'echo ~ && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dteach/.ansible/tmp/ansible-tmp-1505328530.78-274389183967727 `" && echo ansible-tmp-1505328530.78-274389183967727="` echo /home/dteach/.ansible/tmp/ansible-tmp-1505328530.78-274389183967727 `" ) && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> PUT /tmp/tmpC3cTNs TO /home/dteach/.ansible/tmp/ansible-tmp-1505328530.78-274389183967727/setup.py
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'chmod u+x /home/dteach/.ansible/tmp/ansible-tmp-1505328530.78-274389183967727/ /home/dteach/.ansible/tmp/ansible-tmp-1505328530.78-274389183967727/setup.py && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '/usr/bin/python /home/dteach/.ansible/tmp/ansible-tmp-1505328530.78-274389183967727/setup.py; rm -rf "/home/dteach/.ansible/tmp/ansible-tmp-1505328530.78-274389183967727/" > /dev/null 2>&1 && sleep 0'
ok: [cc-bdr1-gw.net.uoregon.edu]
META: ran handlers

TASK [juniper : template bootstrap configuration for zero touch provisioning] ******************************************************************************************************************************
task path: /mnt/ch/repos/git/is_nts/junos_ansible_dteach/playbooks/roles/juniper/tasks/ztp.yml:1
skipping: [cc-bdr1-gw.net.uoregon.edu] => {
    "changed": false,
    "skip_reason": "Conditional result was False",
    "skipped": true
}

TASK [juniper : get junos facts] ***************************************************************************************************************************************************************************
task path: /mnt/ch/repos/git/is_nts/junos_ansible_dteach/playbooks/roles/juniper/tasks/get_facts.yml:2
<cc-bdr1-gw.net.uoregon.edu> using connection plugin netconf
<cc-bdr1-gw.net.uoregon.edu> socket_path: /home/dteach/.ansible/pc/c4eb1dbd53
Using module file /mnt/ch/repos/git/ansible/lib/ansible/modules/network/junos/junos_facts.py
<cc-bdr1-gw.net.uoregon.edu> ESTABLISH LOCAL CONNECTION FOR USER: dteach
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'echo ~ && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dteach/.ansible/tmp/ansible-tmp-1505328533.28-281471058063826 `" && echo ansible-tmp-1505328533.28-281471058063826="` echo /home/dteach/.ansible/tmp/ansible-tmp-1505328533.28-281471058063826 `" ) && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> PUT /tmp/tmpXgbgoQ TO /home/dteach/.ansible/tmp/ansible-tmp-1505328533.28-281471058063826/junos_facts.py
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c 'chmod u+x /home/dteach/.ansible/tmp/ansible-tmp-1505328533.28-281471058063826/ /home/dteach/.ansible/tmp/ansible-tmp-1505328533.28-281471058063826/junos_facts.py && sleep 0'
<cc-bdr1-gw.net.uoregon.edu> EXEC /bin/sh -c '/usr/bin/python /home/dteach/.ansible/tmp/ansible-tmp-1505328533.28-281471058063826/junos_facts.py; rm -rf "/home/dteach/.ansible/tmp/ansible-tmp-1505328533.28-281471058063826/" > /dev/null 2>&1 && sleep 0'
ok: [cc-bdr1-gw.net.uoregon.edu] => {
    "ansible_facts": {
        "ansible_net_filesystems": [
            "/dev/ad0s1a",
            "devfs",
            "/dev/md0",
            "/dev/md1",
            "/dev/md2",
            "/dev/md3",
            "/dev/md4",
            "/dev/md5",
            "/dev/md6",
            "/dev/md7",
            "/dev/md8",
            "/dev/md9",
            "/dev/md10",
            "/dev/md11",
            "/dev/md12",
            "/dev/md13",
            "/dev/md14",
            "/dev/md15",
            "/dev/md16",
            "/dev/md17",
            "/dev/md18",
            "/dev/md19",
            "/dev/md20",
            "/dev/md21",
            "/dev/md22",
            "/dev/md23",
            "/dev/md24",
            "/dev/md25",
            "/dev/md26",
            "/dev/ad0s1e",
            "procfs",
            "/dev/ad1s1f",
            "/var/jails/rest-api",
            "/var/jail",
            "/var/log",
            "devfs",
            "/var/jail/etc",
            "/var/jail/run",
            "/var/jail/tmp",
            "/var/tmp",
            "devfs",
            "/dev/md27",
            "/dev/md28",
            "/dev/md29",
            "/dev/md30",
            "/dev/md31",
            "/dev/md32",
            "/dev/md33",
            "/dev/md34",
            "/dev/md35",
            "/dev/md36",
            "/dev/md37",
            "/dev/md38"
        ],
        "ansible_net_gather_subset": [
            "hardware",
            "default"
        ],
        "ansible_net_has_2RE": true,
        "ansible_net_hostname": "cc-bdr1-gw",
        "ansible_net_memfree_mb": 8722896,
        "ansible_net_memtotal_mb": 16741064,
        "ansible_net_model": "ex9208",
        "ansible_net_modules": [
            {
                "clei_code": "IPM8M00BRB",
                "description": "EX9208-BP3",
                "model_number": "EX9208-CHAS3-S",
                "name": "Midplane",
                "part_number": "750-053634",
                "serial_number": "ACRG9732",
                "version": "REV 37"
            },
            {
                "description": "Front Panel Display",
                "model_number": null,
                "name": "FPM Board",
                "part_number": "760-064013",
                "serial_number": "CAGX8700",
                "version": "REV 02"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 0",
                "part_number": "740-063046",
                "serial_number": "QCS1640U077",
                "version": "Rev 01"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 1",
                "part_number": "740-063046",
                "serial_number": "QCS1640U016",
                "version": "Rev 01"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 2",
                "part_number": "740-063046",
                "serial_number": "QCS1640U004",
                "version": "Rev 01"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 3",
                "part_number": "740-063046",
                "serial_number": "QCS1640U060",
                "version": "Rev 01"
            },
            {
                "clei_code": "IPUCBF5CAC",
                "description": "RE-S-EX9200-1800X4",
                "model_number": "EX9200-RE",
                "name": "Routing Engine 0",
                "part_number": "740-049603",
                "serial_number": "9016006732",
                "version": "REV 05"
            },
            {
                "clei_code": "IPUCBF5CAC",
                "description": "RE-S-EX9200-1800X4",
                "model_number": "EX9200-RE",
                "name": "Routing Engine 1",
                "part_number": "740-049603",
                "serial_number": "9009153453",
                "version": "REV 05"
            },
            {
                "clei_code": "IPUCBJXCAB",
                "description": "EX9200-SF2",
                "model_number": "EX9200-SF2",
                "name": "CB 0",
                "part_number": "750-062852",
                "serial_number": "CAFF8987",
                "version": "REV 07"
            },
            {
                "clei_code": "IPUCBJXCAB",
                "description": "EX9200-SF2",
                "model_number": "EX9200-SF2",
                "name": "CB 1",
                "part_number": "750-062852",
                "serial_number": "CAFF8990",
                "version": "REV 07"
            },
            {
                "clei_code": "IPU3BADHAC",
                "description": "EX9200-2C-8XS",
                "model_number": "EX9200-2C-8XS",
                "name": "FPC 0",
                "part_number": "750-064568",
                "serial_number": "CAGT7948",
                "version": "REV 07"
            },
            {
                "clei_code": "IPU3BADHAC",
                "description": "EX9200-2C-8XS",
                "model_number": "EX9200-2C-8XS",
                "name": "FPC 1",
                "part_number": "750-064568",
                "serial_number": "CAGT7929",
                "version": "REV 07"
            },
            {
                "description": "Enhanced Left Fan Tray",
                "model_number": "FFANTRAY-MX480-HC-S",
                "name": "Fan Tray"
            }
        ],
        "ansible_net_routing_engines": {
            "0": {
                "cpu_background": "0",
                "cpu_idle": "84",
                "cpu_interrupt": "1",
                "cpu_system": "11",
                "cpu_temperature": "27 degrees C / 80 degrees F",
                "cpu_user": "5",
                "last_reboot_reason": "Router rebooted after a normal shutdown.",
                "load_average_fifteen": "0.00",
                "load_average_five": "0.03",
                "load_average_one": "0.04",
                "mastership_priority": "master (default)",
                "mastership_state": "master",
                "memory_buffer_utilization": "16",
                "memory_dram_size": "16349 MB",
                "memory_installed_size": "(16384 MB installed)",
                "model": "RE-S-EX9200-1800X4",
                "serial_number": "9016006732",
                "slot": "0",
                "start_time": "2017-04-27 12:25:03 PDT",
                "status": "OK",
                "temperature": "30 degrees C / 86 degrees F",
                "up_time": "138 days, 23 hours, 23 minutes, 51 seconds"
            },
            "1": {
                "cpu_background": "0",
                "cpu_idle": "100",
                "cpu_interrupt": "0",
                "cpu_system": "0",
                "cpu_temperature": "27 degrees C / 80 degrees F",
                "cpu_user": "0",
                "last_reboot_reason": "Router rebooted after a normal shutdown.",
                "load_average_fifteen": "0.00",
                "load_average_five": "0.00",
                "load_average_one": "0.00",
                "mastership_priority": "backup (default)",
                "mastership_state": "backup",
                "memory_buffer_utilization": "10",
                "memory_dram_size": "16349 MB",
                "memory_installed_size": "(16384 MB installed)",
                "model": "RE-S-EX9200-1800X4",
                "serial_number": "9009153453",
                "slot": "1",
                "start_time": "2017-09-13 10:24:59 PDT",
                "status": "OK",
                "temperature": "31 degrees C / 87 degrees F",
                "up_time": "1 hour, 23 minutes, 43 seconds"
            }
        },
        "ansible_net_serialnum": "JN125F148RFB",
        "ansible_net_version": null
    },
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "config_format": "text",
            "gather_subset": [
                "hardware"
            ],
            "host": null,
            "password": null,
            "port": null,
            "provider": {
                "host": "cc-bdr1-gw.net.uoregon.edu",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 22,
                "ssh_keyfile": "/home/dteach/.ssh/nts-netconf_rsa",
                "timeout": 300,
                "transport": null,
                "username": "nts-netconf"
            },
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "username": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************************
cc-bdr1-gw.net.uoregon.edu : ok=2    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests:

```
>       fixture_data[path] = data
E       UnboundLocalError: local variable 'data' referenced before assignment

test/units/modules/network/junos/junos_module.py:62: UnboundLocalError
```

**Review by ganeshrn — COMMENTED** [review]
Can you please add a unit test case to test new facts added as part of this PR [here](https://github.com/ansible/ansible/blob/devel/test/units/modules/network/junos/test_junos_facts.py
).

**Comment by dteach** [comment]
ready_for_review

**Review by ganeshrn — APPROVED** [review]
Looks good.

**Comment by ganeshrn** [comment]
Thank you!

**Pull request merged**
