### PR TITLE
IOS-XR: Add [iosxr_lag_interfaces] resource module

### PR DESCRIPTION
**Pull request by NilashishC**
Depends-On: https://github.com/ansible/ansible/pull/61313
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Add iosxr_lag_interfaces resource module
- Targets model -https://github.com/ansible-network/resource_module_models/pull/31

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
iosxr_lag_interfaces.py

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
> Build failed (third-party-check pipeline) integration testing with
> Ansible.
> 
> * [ansible-test-network-integration-iosxr-python27 ](https://dashboard.zuul.ansible.com/t/ansible/build/5675bb0b250140088a1f56ceeeb0ac63) : FAILURE in 1h 27m 13s
> * [ansible-test-network-integration-iosxr-python35 ](https://dashboard.zuul.ansible.com/t/ansible/build/516c261f3bc245fdbe7d8dd3a20aaf58) : FAILURE in 1h 38m 26s
> * [ansible-test-network-integration-iosxr-python36 ](https://dashboard.zuul.ansible.com/t/ansible/build/22a40ae35bcf4e3c9c68265e59605977) : FAILURE in 1h 30m 26s
> * [ansible-test-network-integration-iosxr-python37 ](https://dashboard.zuul.ansible.com/t/ansible/build/d83f6823f05f4217a117427f540f7090) : FAILURE in 1h 52m 25s

All tests for iosxr_lag_interfaces are passing. The failure is for iosxr_interfaces and is consistent.
Fixed by #61313

**Comment by justjais** [comment]
recheck

**Review by ganeshrn — APPROVED** [review]

**Pull request merged**
