### PR TITLE
Delete unused module_utils/cloudengine.py

### PR DESCRIPTION
**Pull request by QijunPan**
##### SUMMARY

Delete unused cloudengine.py and new module_utils/ce.py had merged
rename cloudengine.py to ce.py.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

Deleted: lib/ansible/module_utils/cloudengine.py and new module_utils/ce.py had merged
Rename: lib/ansible/utils/module_docs_fragments/ce.py (from lib/ansible/utils/module_docs_fragments/cloudengine.py)

##### ANSIBLE VERSION

```
ansible 2.4
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
This appears to be confusing our CI, where we trace Python imports

I wonder if the delete needs to be done as a single PR

```
2017-05-26 02:33:17 Analyzing python module_utils imports...
2017-05-26 02:33:23 WARNING: No imports found which use the "ansible.module_utils.cnos_devicerules" module_util.
2017-05-26 02:33:23 WARNING: No imports found which use the "ansible.module_utils.cnos_errorcodes" module_util.
2017-05-26 02:33:23 WARNING: No imports found which use the "ansible.module_utils.f5_cli" module_util.
2017-05-26 02:33:23 WARNING: No imports found which use the "ansible.module_utils.openshift_common" module_util.
2017-05-26 02:33:23 WARNING: No imports found which use the "ansible.module_utils.splitter" module_util.
2017-05-26 02:33:23 Processed 71 python module_utils in 5 second(s).
2017-05-26 02:33:23 Traceback (most recent call last):
2017-05-26 02:33:23   File "test/runner/ansible-test", line 628, in <module>
2017-05-26 02:33:23     main()
2017-05-26 02:33:23   File "test/runner/ansible-test", line 85, in main
2017-05-26 02:33:23     args.func(config)
2017-05-26 02:33:23   File "/root/src/github.com/ansible/ansible/test/runner/lib/executor.py", line 742, in command_compile
2017-05-26 02:33:23     changes = get_changes_filter(args)
2017-05-26 02:33:23   File "/root/src/github.com/ansible/ansible/test/runner/lib/executor.py", line 955, in get_changes_filter
2017-05-26 02:33:23     commands = categorize_changes(paths, args.command)
2017-05-26 02:33:23   File "/root/src/github.com/ansible/ansible/test/runner/lib/classification.py", line 46, in categorize_changes
2017-05-26 02:33:23     dependent_paths = mapper.get_dependent_paths(path)
2017-05-26 02:33:23   File "/root/src/github.com/ansible/ansible/test/runner/lib/classification.py", line 137, in get_dependent_paths
2017-05-26 02:33:23     return self.get_python_module_utils_usage(path)
2017-05-26 02:33:23   File "/root/src/github.com/ansible/ansible/test/runner/lib/classification.py", line 161, in get_python_module_utils_usage
2017-05-26 02:33:23     return sorted(self.python_module_utils_imports[name])
2017-05-26 02:33:23 KeyError: u'ansible.module_utils.cloudengine'
```

**Comment by QijunPan** [comment]
I'll try to delele the unused module ```lib/ansible/module_utils/cloudengine.py``` as a single PR

**Comment by QijunPan** [comment]
I think I have a problem with my operation. I have to close it.  sorry.

**Comment by gundalow** [comment]
Rebase needed

**Comment by gundalow** [comment]
May have to wait two weeks till we can fix the ansible-test issue

**Comment by QijunPan** [comment]
I had rebased it. but CI check failed. maybe  I have to wait.

**Comment by mattclay** [comment]
CI is now passing.

**Comment by pilou-** [comment]
This pull-request looks good to me.

@gundalow this pull-request will allow to use `ce` fragment in all other `ce` module: could this pull-request be merged ?

**Pull request merged**
