### PR TITLE
fix yes/no to true/false in loop documents etc

### PR DESCRIPTION
**Pull request by akira6592**
##### SUMMARY

 I fixed `yes`/`no` to  `true`/`false` in some documents.

According to https://github.com/ansible-community/community-topics/issues/116.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

Some documents

##### ADDITIONAL INFORMATION

```paste below
N/A
```

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM

**Comment by samccann** [comment]
Thanks @akira6592 for the Ansible docs fix!

**Comment by akira6592** [comment]
@samccann Thank you for merge!

**Pull request merged**
