### PR TITLE
docker_container: add port range and IPv6 support for published_ports

### LINKED ISSUE #43177: docker_container binds to 0.0.0.0 instead of localhost
##### SUMMARY

docker_container binds to 0.0.0.0 instead of localhost

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible-playbook 2.6.1
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.5/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

```yaml
- name: "Start Docker Registry Server"
  docker_container:
    name: "registry"
    recreate: yes
    image: registry:2
    ports:
      - "localhost:5000:5000"
      - "localhost:5001:5001"
    restart: yes
    restart_policy: "always"
```

##### EXPECTED RESULTS
registry container should be bound to localhost

##### ACTUAL RESULTS

`ps -ef` shows registry container bound to 0.0.0.0 and `nc` confirms this.

```
root      3720  2147  0 23:20 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5001 -contain
root      3734  2147  0 23:20 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5000 -contain
```

##### WHAT WORKS
This configuration correctly binds to localhost
```yaml
- name: "Start Docker Registry Server"
  docker_container:
    name: "registry"
    recreate: yes
    image: registry:2
    init: yes
    network_mode: "bridge"
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
    restart: yes
    restart_policy: "always"
```

```
root      4914  2147  0 23:25 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 5001 -conta
root      4927  2147  0 23:25 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 5000 -conta
```

### LINKED ISSUE #44668: docker_container `published_ports`  needs more control options
##### SUMMARY
Per #21091 #21093 #21094 , there're several issues with `published_ports` parameter:

- [ ] It does not accept a single port, per #21093 
- [ ] It does not accept 'all' option, per #21091, which is supported by `docker --publish-all`
- [ ] It does not accept port range, per #21094 
- [ ] ipv6 support, per #38909 

These issues need to be verified first, and future patch can be submitted to fix them all. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adds support for port ranges and IPv6 addresses for `published_ports`. Fixes #44668, fixes #43177.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
Currently includes #46594 and #46595. Will be removed once these are merged.

**Review by kassiansun — APPROVED** [review]

**Comment by kassiansun** [comment]
shipit

**Comment by felixfontein** [comment]
Rebased after #46594 and #46595 were merged.

**Comment by felixfontein** [comment]
Again rebased after #46598 got merged.

@kassiansun Can you take another (quick) look? I think it should be fine (and the tests still run through, I think), but another pair of eyes never hurts :)

**Comment by kassiansun** [comment]
shipit

**Comment by felixfontein** [comment]
@kassiansun @gundalow Thanks for reviewing and merging!

**Pull request merged**
