### PR TITLE
Move verify up so approle and other methods work as intended.

### PR DESCRIPTION
**Pull request by piffey**
##### SUMMARY
Real simple fix to take care of https://github.com/ansible/ansible/issues/38536

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
hashi_vault lookup plugin

##### ANSIBLE VERSION
```
ansible 2.5.0
ansible 2.6.0 (devel 450cfa8) last updated 2018/04/10 07:54:25 (GMT -700)
```

##### ADDITIONAL INFORMATION
Real simple change so hvac.Client works as intended everywhere.

### CODE REVIEW

**Comment by robinovitch61** [comment]
Can we merge this please if it works?

Edit: confirmed this does work great! Nice work @piffey . Saved me a huge headache.

**Comment by mshkrebtan-tf** [comment]
Thanks @piffey! Works for me, too!

**Comment by abadger** [comment]
rebuild_merge

**Comment by abadger** [comment]
rebuild_merge

**Comment by abadger** [comment]
Failures are unrelated.  merging to devel.

**Pull request merged**
