### PR TITLE
Idempotence problems with win_nssm's app_parameters

### PR DESCRIPTION
**Pull request by strangeman**
Fix for https://github.com/ansible/ansible/issues/20625

I added useful info about changes in AppParameters, removed extra space for one 'noname' parameter and removed quotes for named parameters.

### CODE REVIEW

**Comment by trondhindenes** [comment]
Not sure what to do about this one vs #21290 - @jhawkesworth what do you think?

**Comment by jhawkesworth** [comment]
@trondhindenes I haven't ever really liked the way this module forces you use key/val for app_parameters, but I think I prefer this to having a whole new module parameter (provided it actually lets you specify complete app parameters including spaces and quote (") characters as needed).
I think this PR needs documentation update though to say you can use the 
"_": "some long string of parameters" syntax and perhaps some examples.

Would be great to have this though, I'd love to be able to remove the following from one of my playbooks:

```
- name: set the app startup parameters in the nssm service manager so it can run solr
  win_regedit:
    key: HKLM:\System\CurrentControlSet\Services\{{ solr_service_name }}\Parameters
    value: AppParameters
    data: -server -cp "C:\solr-{{ solr_version }}\server\lib\*;C:\solr-{{ solr_version }}\server\lib\ext\*;C:\solr-{{ so
lr_version }}\server\solr-webapp\webapp\WEB-INF\lib\*" -Xms{{ solr_memory_size }} -Xmx{{ solr_memory_size }} -Duser.time
zone=UTC -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepG
C -XX:+UseParNewGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=6
4m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CM
SParallelRemarkEnabled -XX:+ParallelRefProcEnabled -verbosC:gc -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCDateSt
amps -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -DzkClientTimeout=15000 -D
zkHost={{ zk_hosts }} -Xss256k -Xloggc:"C:\solr-{{ solr_version }}\server\logs\solr_gc.log" -Dlog4j.configuration="file:
///C:\solr-{{ solr_version }}\server\resources\log4j.xml" -DSTOP.PORT=7983 -DSTOP.KEY= {{solr_stop_key}} -Djetty.port=8983 -Dsolr
.solr.home="{{ solr_home }}" -Dsolr.install.dir="C:\solr-{{ solr_version }}" -Djetty.home="C:\solr-{{ solr_version }}\se
rver" -Djava.io.tmpdir="C:\solr-{{ solr_version }}\server\tmp" -Dhost={{ ansible_hostname|lower }} -Dpkiauth.ttl=30000 -
jar .\start.jar "--module=http"
```

**Comment by jhawkesworth** [comment]
@strangeman -I merged https://github.com/ansible/ansible/pull/21290 do you want to keep this open now?

**Comment by jhawkesworth** [comment]
@strangeman  please can you rebase your PR so it can be considered again?  Instructions for doing this are here: https://docs.ansible.com/ansible/dev_guide/developing_rebasing.html

**Comment by strangeman** [comment]
@jhawkesworth all done! :)

**Comment by dagwieers** [comment]
What is needed to get this go forward ? Do we need this in v2.3 ?

cc: @nitzmahone

**Comment by jhawkesworth** [comment]
Not proven, but I wonder if existing playbooks might be broken by replacing the 

-                    $singleLineParams = $singleLineParams + "$key ""$val"""
in this PR 
with 

+                    $singleLineParams = $singleLineParams + "$key $val"

Increasingly I think the app parameters hash wasn't a good choice, although that's definitely best dealt with in a separate PR (not sure how exactly).

**Comment by nitzmahone** [comment]
Unfortunately, this module needs a much bigger change to the way args are handled- while your change ostensibly fixes the problem, it introduces a few others. Rather than playing whack-a-mole, we'd prefer to wait for someone to take on the larger rewrite...

**Pull request closed without merging**
