### PR TITLE
Implement the 'always_run' task keyword which allows one to execute a task even in check mode

### PR DESCRIPTION
**Pull request by stoned**
This is nearly the same as #3405 but independent of #3389.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks reasonably straightforward, though I suspect some folks are going to be expect the line to be templated (it always happens), so something to look into possibly.

Also looks like this needs a rebase given recent changes, can you take care of this?

Also can we do this without Python properties?  I tend to like things to be more explicit.

Thanks!

**Comment by stoned** [comment]
Sure I can look into making always_run: templated.
And of course a rebase is implied.
As for the runner check property it is a lazy trick to avoid changing the 10 or so references to it.
I suppose I could change all of them to a new runner method like check_mode() or noop_mode().

**Comment by stoned** [comment]
I have another implementation ready: the new always_run clause is fed to check_conditional() and a new Runner.noop() method is introduced to check if a runner should really execute its task wrt to check mode and always_run clause (no more property usage).
But this implementation would need PR #3645 to be sorted out before I could make it into a PR.

**Comment by stoned** [comment]
New implementation pushed, see PR #3733

**Pull request closed without merging**
