### PR TITLE
Add gc_deployment module (google cloud)

### LINKED ISSUE #34457: new module for managing deployment manager in Google Cloud
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
google

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/pschiffe/work/websignal/infra/ansible/ansible.cfg
  configured module search path = [u'/home/pschiffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Fedora release 27 (Twenty Seven)

##### SUMMARY
Create a new module to manage deployment manager in the Google Cloud Platform. API:
https://cloud.google.com/deployment-manager/docs/reference/latest/

### PR DESCRIPTION
**Pull request by tomas-mazak**
##### SUMMARY
Add module to manage Google Cloud Deployment Manager deployments. Fixes #34457.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
gc_deployment

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tomas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tomas/.virtualenvs/gcp/lib/python3.6/site-packages/ansible
  executable location = /home/tomas/.virtualenvs/gcp/bin/ansible
  python version = 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0]
```

##### ADDITIONAL INFORMATION
This module, unlike other GCP modules doesn't use `apache-libcloud` unfortunately, as it seems libcloud does not support Deployment Manager. Official google python api library is used instead.

### CODE REVIEW

**Comment by tomas-mazak** [comment]
@GwenaelPellenArkeup @bennojoy @dohoangkhiem @erjohnso @GoogleCloudPlatform @Nitaco @rambleraptor @robwagner33 @supertom @walbert947 

Bump. Any chance of getting this up/down-voted? Cheers!

**Comment by lubo** [comment]
@tomas-mazak I didn't know you've implemented this module, so I've implemented my own version too. Pretty much the only difference between our modules is that my module uses previews in order to determine whether a deployment was changed or not. Why did you choose to only compare the configs?

**Comment by tomas-mazak** [comment]
@lubo , I think using previews is probably a better idea. I'm only using config diff for simplicity. Could you please link your module? Or the PR if there's one?

**Comment by lubo** [comment]
@tomas-mazak https://gist.github.com/lubo/4d594e80ffe532d17c594717ae3c9a6c It's not ready for merge into Ansible, but I was definitely going to send a PR one day before knowing about your PR.

There are several minor differences that I like better in my module (such as config is dict, not string). Would be great if we could work their differences out and combine the modules.

Let me know what you think.

**Comment by tomas-mazak** [comment]
@lubo , the reason why I have config as a string is that GCP preserves the YAML as-is, including comments ... you can't do that with dict ... also, like this you can easily load the whole YAMLs from template using lookup (see examples of my module) ... using `to_yaml` filter you can easily pass a dict too

**Comment by tomas-mazak** [comment]
@GwenaelPellenArkeup @bennojoy @dohoangkhiem @erjohnso @GoogleCloudPlatform @Nitaco @rambleraptor @robwagner33 @supertom @walbert947 bump

Any opinions? Can this be merged?

**Comment by lubo** [comment]
@tomas-mazak Are you not going to implement any feature from my module?

**Comment by tomas-mazak** [comment]
> @tomas-mazak Are you not going to implement any feature from my module?

Hey @lubo, not now. The module works for me and I don't want to spend time on it before I hear from the maintainers, what didn't happen since I raised this in June, sadly...

**Comment by rambleraptor** [comment]
ship_it

This looks fine with me! I don't have merge access on this, so I can't actually get this shipped into ansible.

I just wanted to give some context on why I was hesitant on a DM module. The goal of the new gcp_* modules was to do the same tasks as DM: an idempotent, declarative model of GCP resources. Since they're establishing the same goal, a DM module seemed a little unnecessary.

That being said, the community comes first! I definitely don't want to block this if there are community members that will find it useful. Google won't be able to contribute any cycles to helping maintain this module, but we can help the community brainstorm fixes.

Thanks again for the PR!

**Comment by LorenzoFernando** [comment]
Hello @GwenaelPellenArkeup @bennojoy @dohoangkhiem @erjohnso @GoogleCloudPlatform @nitaco @rambleraptor @robwagner33 @supertom @walbert947

Can this **approved** commit be merged? Cloud Deployment Manager is of great use to many infrastructure management professionals, and the addition of this module will ease our efforts to use that great tool. Thank you!

**Comment by Akasurde** [comment]
@tomas-mazak Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/google.cloud. Could you please migrate this PR to the above-mentioned repo? 

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks,

needs_info

**Pull request closed without merging**
