### PR TITLE
Enable plugins for jinja2 tests

### PR DESCRIPTION
**Pull request by quixoten**
##### Issue Type:

Feature Pull Request
##### Summary:
- Move boolean filters to `test_plugins/core.py` and enable users to write their own test plugins.
- Register all test plugins additionally as filter plugins to retain backwards compatibility.

Supersedes #8235
Discussed but never resolved [here](https://groups.google.com/forum/#!topic/ansible-devel/Oa6XSffcHJg)

### CODE REVIEW

**Comment by mintern** [comment]
Note that I originally followed the approach you have here -- splitting out test filters into a separate module -- in https://github.com/ansible/ansible/pull/8217 and it was soundly rejected (the relevant message: https://groups.google.com/forum/#!msg/ansible-devel/Oa6XSffcHJg/a5MivA4pEaEJ). #8235 was a response to that, involving a much smaller changeset. That one seemed to be on the track to acceptance, but then it languished.

**Comment by chandru9279** [comment]
+1 for Ansible to have test-plugins as separate category of plugins. Comparable to filter,shell,callback etc plugin categories

**Comment by jimi-c** [comment]
I will work to get this into devel, which will require a bit of effort due to the changes in organization/etc. involved with the v2 work.

**Comment by elzibubble** [comment]
+1 for Ansible providing test plugins.

**Comment by amenonsen** [comment]
@jimi-c are you still working on this? (I ask because the v2 label has been removed.)

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
