### PR TITLE
snow: Fix token reference in basic authentication

### LINKED ISSUE #59299: snow_record: 'NoneType' object has no attribute 'generate_token'
##### SUMMARY
With addition of OAuthClient in snow_* modules, I am getting following error - 
```
Traceback (most recent call last):
  File "/Users/akasurde/.ansible/tmp/ansible-tmp-1563543375.7458959-114877035679906/AnsiballZ_snow_record.py", line 125, in <module>
    _ansiballz_main()
  File "/Users/akasurde/.ansible/tmp/ansible-tmp-1563543375.7458959-114877035679906/AnsiballZ_snow_record.py", line 117, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/akasurde/.ansible/tmp/ansible-tmp-1563543375.7458959-114877035679906/AnsiballZ_snow_record.py", line 51, in invoke_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_snow_record_payload_brr2thzt/__main__.py", line 339, in <module>
  File "/tmp/ansible_snow_record_payload_brr2thzt/__main__.py", line 335, in main
  File "/tmp/ansible_snow_record_payload_brr2thzt/__main__.py", line 205, in run_module
  File "/tmp/ansible_snow_record_payload_brr2thzt/ansible_snow_record_payload.zip/ansible/module_utils/service_now.py", line 57, in login
AttributeError: 'NoneType' object has no attribute 'generate_token'
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.9
```

##### CONFIGURATION

```paste below
Nothing specific
```

##### OS / ENVIRONMENT

MacOS Mojave

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - snow_record:
        instance: "instance_id"
        password: "password"
        username: admin
        data:
          short_description: "Description"
          priority: 2
        state: present
```

##### EXPECTED RESULTS

Playbook should be successful.

##### ACTUAL RESULTS

```paste below
Traceback (most recent call last):
  File "/Users/akasurde/.ansible/tmp/ansible-tmp-1563543375.7458959-114877035679906/AnsiballZ_snow_record.py", line 125, in <module>
    _ansiballz_main()
  File "/Users/akasurde/.ansible/tmp/ansible-tmp-1563543375.7458959-114877035679906/AnsiballZ_snow_record.py", line 117, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/akasurde/.ansible/tmp/ansible-tmp-1563543375.7458959-114877035679906/AnsiballZ_snow_record.py", line 51, in invoke_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_snow_record_payload_brr2thzt/__main__.py", line 339, in <module>
  File "/tmp/ansible_snow_record_payload_brr2thzt/__main__.py", line 335, in main
  File "/tmp/ansible_snow_record_payload_brr2thzt/__main__.py", line 205, in run_module
  File "/tmp/ansible_snow_record_payload_brr2thzt/ansible_snow_record_payload.zip/ansible/module_utils/service_now.py", line 57, in login
AttributeError: 'NoneType' object has no attribute 'generate_token'
```

### PR DESCRIPTION
**Pull request by n3pjk**
##### SUMMARY
Basic authentication does not use tokens, only OAuth. ServiceNowClient constructor code had indent issue which attempted to initialize token regardless of authentication method.

Fixes #59299

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
service_now.py

##### ADDITIONAL INFORMATION
See #59299 for repro instructions.

### CODE REVIEW

**Comment by n3pjk** [comment]
@Akasurde I rebased the branch, didn't see the changes from #59297 so I manually added all of those changes into this branch as well.  The checks were cancelled, not sure why.  There's no feedback from the console to go on.  Any suggestions?

**Comment by Akasurde** [comment]
@n3pjk I restarted the CI and now it is PASSED for this change. Let me know once you are ready for the change. Thanks.

**Comment by n3pjk** [comment]
@Akasurde If this patch fixes basic auth, there should be no errors referencing tokens when using basic auth, then this is ready to go.  I have retested and OAuth is working correctly.  We just need basic retested.

**Comment by Akasurde** [comment]
@n3pjk Basic Auth works for me. Let me know once you are ready to merge this. Thanks.

**Comment by n3pjk** [comment]
In that case, it's ready to merge!

**Pull request merged**
