### PR TITLE
uri module: Allow multiple status_code codes as comma separated list

### PR DESCRIPTION
**Pull request by E-M**
This allows to provide multiple, comma separated list of status_code

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks like status_code needs to specify "type='list"" in the argument_spec section.

(This current check looks like it might rely on a string match)

**Comment by E-M** [comment]
Any progress here?

**Comment by risaacson** [comment]
Hey @E-M,

It has been a few months since you made your PR for this feature and the uri module has changed during that time. Notably GH-4476 was merged and that stomps directly on your PR. In that merge it forced the return to be a int.

Are you able to take a look at this and bring the PR up to date?

-r

**Comment by mpdehaan** [comment]
I'm going to close this one due to lack of updates, but should you wish to update it, that would be welcome as a new pull request.

Sorry for the confusion in this one!

**Pull request closed without merging**
