### PR TITLE
Qtree was not idempotent 

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
- Qtree was not idempotent 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_qtree.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — COMMENTED** [review]
should this be marked as a bug fix!

**Comment by Wangxou** [comment]
@carchi8py 
Hi, do your code merged? I am similar with your label and status, I don't know what to do later or waiting all the time ?

**Review by lonico — APPROVED** [review]
shipit

**Comment by thedoubl3j** [comment]
@lonico I do believe that it should be labeled a bug fix as no new feature was added but I am reviewing now.

**Review by thedoubl3j — APPROVED** [review]
adding back sanity tests +1 and technically not a new feature in a sense but more of a fix in my eyes. lgtm

**Pull request merged**
