### PR TITLE
meraki_network - Added proper response documentation

### PR DESCRIPTION
**Pull request by kbreit**
##### SUMMARY
Improved response documentation on `meraki_network` module.

##### ISSUE TYPE
 - Docs Pull Request

##### ANSIBLE VERSION
```
2.7
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by dagwieers** [comment]
Not sure why this PR has not been labeled *owner_pr* ?

**Comment by IPvSean** [comment]
Hey @kbreit are you aware of the gamification exercise? https://github.com/ansible/community/issues/311

I know you are the module writer, but since this is a DOC pr, this PR once it keep accepted would get you 1/5 the way there :) . Just in case you had any other doc updates you up your sleeve :)

**Comment by kbreit** [comment]
@IPvSean I am not aware of it but I am now!

I definitely have a bunch of other documentation PRs coming through. Documentation is something I'm refining with time, including a scenario guide so I expect I'll have more coming through soon. Thanks for the heads u.

**Review by dagwieers — APPROVED** [review]
LGTM

**Pull request merged**
