### PR TITLE
namespace facts

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

facts

##### ANSIBLE VERSION

```
2.3
```

### CODE REVIEW

**Comment by mscherer** [comment]
So, I think I understand the feature, but I am curious on the use case.

**Comment by abadger** [comment]
I like it.  We'd need to decide whether to deprecate or just leave it as an option forwever.

**Comment by bcoca** [comment]
@mscherer it avoids collisions with existing vars by making sure all facts are restricted to `ansible_facts`.

**Comment by mscherer** [comment]
What is annoying is that suddenly, it reduce the reuse of roles. We had the discussion with my teammate on hash_behaviour, because if he turn it on for ansible, then I can't reuse some of his role. the same go for that feature, so I wonder if we can do something to prevent and/or avoid that.

For example, could we activate/desactivate it on a per role basis, etc ?

**Comment by bcoca** [comment]
That issue is solved via https://github.com/ansible/proposals/issues/35

**Comment by mscherer** [comment]
The proposal #35 may not solve the issue. If I have a role that expect facts to be in their own namespace and another that don't, I can't use both of them, because the setting applie only for setup.

**Comment by bcoca** [comment]
it allows each role to merge it's own config params

**Review by dharmabumstead — APPROVED** [review]
Doc update approved with minor edit. Thanks.

**Pull request merged**
