### PR TITLE
Convert docker cmd output to native, early

### PR DESCRIPTION
**Pull request by retr0h**
(cherry picked from commit ccd170cbdd32c0b0896a8bc289ab8583031a2827)

##### SUMMARY

This PR updates the docker connection plugin to support python3

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

plugins/connection/docker.py

##### ANSIBLE VERSION

2.2

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
Closing & re-opening to trigger CI

**Comment by gundalow** [comment]
The `stable-2.2` branch may only be for security updates now, need to check

**Comment by gundalow** [comment]
@retr0h Something is looking strange with the Shippable CI results.

I wonder if a rebase would help?
http://docs.ansible.com/ansible/dev_guide/developing_rebasing.html

**Comment by retr0h** [comment]
@gundalow I rebased but there seems to be an issue still.  The test which fails is:

```
2017-06-15 17:08:19 TASK [test_git : update to revision by specifying the refspec] *****************
2017-06-15 17:08:19 fatal: [testhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force 2cfde3668b8bb10fbe2b9d5cec486025ad8cc51b", "failed": true, "msg": "Failed to checkout 2cfde3668b8bb10fbe2b9d5cec486025ad8cc51b", "rc": 128, "stderr": "fatal: reference is not a tree: 2cfde3668b8bb10fbe2b9d5cec486025ad8cc51b\n", "stdout": "", "stdout_lines": []}
```

**Comment by gundalow** [comment]
The `stable-2.2` branch is only for security patches now, so I'll close this PR.

From your cherry-pick I can see that this has been fixed in Ansible 2.3. I'd suggest upgrading to that release at your earliest convenience.

**Comment by retr0h** [comment]
👍

**Pull request closed without merging**
