### PR TITLE
Guidance for pycrypto install on Mac OSX

### PR DESCRIPTION
**Pull request by NathanDotTo**
See #12454.

Regards

Nathan

### CODE REVIEW

**Comment by amenonsen** [comment]
Why is this three separate commits?

**Comment by NathanDotTo** [comment]
Hi

This is three separate commits as I added clarification about why the dependency was there after the first “git add”, so I had to add and commit again, and I also spotted another part of the install documentation that could benefit from the same guidance as I reviewed my changes.

Regards

Nathan

> On 28 Sep 2015, at 17:04, Abhijit Menon-Sen notifications@github.com wrote:
> 
> Why is this three separate commits?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Nathan John Sowatskey
Programmable Infrastructure, DevOps and SDN
nathan@nathan.to
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net
Google: nathanjohnsowatskey@gmail.com
Skype: nathan_sowatskey
Twitter: NathanDotTo
https://u1890311.ct.sendgrid.net/wf/click?upn=I8d8wtfIjxeRpasNC075ZdoV4WtpL0CRyE9EjXuOhGQncSh2pZGdm-2BGbx9dZnM26_s5UH8bhnBaopYjthcNSRceSUPd-2Bo6-2Fr8rkl9lAAPsDJWSjsiWEZo0RjCb9LkHzGaG58-2FkwXmp7lf-2BI6HCBNo-2BEK2rfGUfKuLWY-2FyrCqpRdWv5nO7jT2OH6RcuxvSxLJNRJLMncU1zK1IyhbQOU8ZdL8PvsZzWf7yaOKATK34-2BuupNJnmm4NDE2reuazfXp-2BcFkq-2B2CYDemai9jUIYZ-2F57Ux0oAqWX461Nm35s-2BQww-2BRjCvkHk-2FHopq0n0zQ64vk0gZoeWGjPOw7TmBDuV5EAYM8j2R28-2F7SmV29cYqOMWWUzCuU70DIYpi-2FD0SRUWFFKNgkRFePdVHPul-2BGDYyfnVQ-3D-3D

**Comment by bcoca** [comment]
this should actually be a note

```
.. note:  If you have issues with the "pycrypto" package install on Mac OSX, which is included as a dependency for PyYAML, then you may need to try "CC=clang sudo -E pip install pycrypto".
```

**Comment by sivel** [comment]
Why is pycrypto being listed as a dep of PyYAML?  To my knowledge pycrypto is included as a dep for paramiko.

**Comment by bcoca** [comment]
@sivel, good catch, had totally missed that

**Comment by NathanDotTo** [comment]
Thanks Matt. The install trace makes it look like pycrypto is a depndency of PyYAML.

I have updated the commit.

Regards

Nathan

> On 28 Sep 2015, at 21:38, Matt Martz notifications@github.com wrote:
> 
> Why is pycrypto being listed as a dep of PyYAML? To my knowledge pycrypto is included as a dep for paramiko.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Nathan John Sowatskey
Programmable Infrastructure, DevOps and SDN
nathan@nathan.to
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net
Google: nathanjohnsowatskey@gmail.com
Skype: nathan_sowatskey
Twitter: NathanDotTo
http://www.kipling.org.uk/poems_if.htm

**Comment by NathanDotTo** [comment]
Also spotted comment about making this a note, so I have done that also.

Regards

Nathan

**Comment by bcoca** [comment]
I did not realize we had it x2, now I'm thinking just making it a footnote and make a ref to it in both paragraphs.

**Comment by NathanDotTo** [comment]
Happy to make it a footnote, could you provide a clue for the footnote syntax please?

Many thanks

Nathan

**Comment by bcoca** [comment]
footnote: 
`.. [1] If you have issues with the "pycrypto" package install on Mac OSX, which is included as a dependency for paramiko, then you may need to try "CC=clang sudo -E pip install pycrypto".`

ref:

```
 ... mytext [1]_
```

**Comment by NathanDotTo** [comment]
OK, how does that look?

Regards

Nathan

**Comment by bcoca** [comment]
awesome, thanks

**Pull request merged**
