### PR TITLE
Allow multiple users to use ec2 inventory scripts

### PR DESCRIPTION
**Pull request by willthames**
Move the ec2 cache files from a shared /tmp location to the
user's ansible tmp directory.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Good idea.

Might want to use an os.makedirs instead of if ~/.ansible didn't exist?

**Comment by willthames** [comment]
@mpdehaan good point. Fixed.

**Comment by pas256** [comment]
At first I wasn't too sure about moving the cache files out of `/tmp`, but thinking about it, the only situation that might cause an issue is if ansible was run by something like a `www-data` or `tomcat` user that has a weird home directory, but since no one should be doing that, I think it will be fine.

**Comment by willthames** [comment]
In such an instance you could always change ec2.ini - it's only a configuration file. This change was really more about the change to ec2.py to allow using ~ in the directory path (and thus make it usable by everyone on the system) - but I do think it's a more sensible default.

**Comment by jctanner** [comment]
@willthames looks good, thank you!

**Pull request merged**
