### PR TITLE
WIP: Allow loading of role/tasks/main.yaml for collections

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY

Allow users to create a collection role using tasks/main.yaml

Note, before merging this we need to write tests.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible_collections

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 32a42aa5b93b0c42e50851e59d22cbdba28838eb

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 7feec7064d789b77fd3e18ac7d64609e2211b5c5

**Comment by bcoca** [comment]
this is trading one incompatibility for another, now roles with main.yml wont load (which is the majority)

in any case, roles are perfectly valid w/o any form of `tasks/main(,.yml,.yaml)` so the test itself is suspect

**Comment by pabelanger** [comment]
@bcoca Yup, agree. I just want to show it is working. Now to figure out how to support both, and write some tests

**Comment by sivel** [comment]
I believe @nitzmahone is currently working on this.  Please check in with him before going to far in your work.  I will leave this open for now, in case I am wrong :)

**Pull request closed without merging**
