### PR TITLE
Tablespace module for PostgreSQL

### PR DESCRIPTION
**Pull request by giorgio-v**
This module implements creation and deletion of a tablespace. It is
derived (i.e. copied) from `postgresql_db`.
- library/database/postgresql_tablespace:

Signed-off-by: giorgio-v giorgio@refactor.it

### CODE REVIEW

**Comment by giorgio-v** [comment]
Any news on this? If it’s not deemed useful I can close it, no problem.

**Comment by mpdehaan** [comment]
We've got a bit of a backlog.  Don't assume lack of comment meants lack of interest.

I have noticed from our automatic scanner that this pull request has merge commits in it.  As a general rule, we don't accept merge commits in contributions.  If you would like this in, can you please resubmit this?

A good tip is to always use git pull --rebase vs git pull, or git rebase vs git merge, and always start a new branch for each topic.

**Comment by giorgio-v** [comment]
Cool, I didn’t want to add more stuff to the backlog.

Regarding the merge issue, should I close this PR and reopen it with a new branch?

**Comment by jctanner** [comment]
@giorgio-v yes, a new pull request would be appreciated.

**Comment by dankeder** [comment]
I would like to use this module, but it seems it's lost in the void. Can somebody possibly re-open this PR so it's not buried forever? Or if @giorgio-v is reading this - can you please rebase the branch and create a new pull-request? Or at least let me know whether I can take it over, rebase it and create the PR.

Thanks.

**Comment by giorgio-v** [comment]
I’m reading it but right now I don’t have the time to work on it.

**Comment by bivald** [comment]
:+1:

**Pull request closed without merging**
