### PR TITLE
added tags to ec2_vol

### PR DESCRIPTION
**Pull request by preyk-work**

### CODE REVIEW

**Comment by lwade** [comment]
Thanks @preyk-work.  This should basically be the same chunk of code as found in the ec2 module.  I'll look to review this first thing on Monday for inclusion.  

First step towards the module being idempotent, would like to get this done by May.  It's quite likely that at the moment we'd want to add something which would remove the tagging option for those using Eucalyptus and other platforms (no tagging support in Eucalyptus until a release in May).

**Comment by lwade** [comment]
Sorry, behind on this one. Will look at it as soon as I can.

**Comment by lwade** [comment]
Good for inclusion, thanks @preyk-work

**Comment by mpdehaan** [comment]
ok please submit this without merge commits and I'm happy to review.

always do 'git pull --rebase' not 'git pull' and 'git rebase' not 'git merge' and you will be ok.

**Comment by pattu777** [comment]
can anybody link me to some documentation... I am using ansible 1.3.1 and it seems this feature is absent.

**Pull request closed without merging**
