### PR TITLE
VMware: Python 3 related TypeError

### LINKED ISSUE #54118: VMware: Python 3 related TypeError
##### SUMMARY
TypeError within the vmware_guest module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Private/ansible-1/lib/ansible
  executable location = /home/user/Private/ansible-1/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
ArchLinux

##### STEPS TO REPRODUCE
Specify a hostname (guest customization) with an invalid character listed here: `'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'` and the guest_id needs to contain `win`.

##### EXPECTED RESULTS
Working and not crashing :p

##### ACTUAL RESULTS
The module fails with the python exception `self.params['name'].translate(None,string.punctuation): ** raised TypeError: translate() takes exactly one argument (2 given)`.

The function call `default_name = self.params['name'].translate(None, string.punctuation)` (line 1599) needs to be changed to also work with python 3.7.2

[in Python 3](https://docs.python.org/3/library/stdtypes.html#str.translate)
[in Python 2](https://docs.python.org/2/library/string.html#string.translate)

### PR DESCRIPTION
**Pull request by agowa**
##### SUMMARY
TypeError within the vmware_guest module

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ADDITIONAL INFORMATION
Fixes #54118 (and also remove white spaces from the hostname)

### CODE REVIEW

**Comment by kobayashi** [comment]
That must be working but a little bit complicated.
Why not just replace to `default_name = self.params['name'].translate(str.maketrans('', '', string.punctuation)`?

**Review by jillr — CHANGES_REQUESTED** [review]
Could you please try to simplify this code?  @kobayashi had a good suggestion to consider.

**Comment by Akasurde** [comment]
@Tomorrow9 Could you please comment on this change ? Thanks.

**Comment by agowa338** [comment]
I reverted the suggested implementation of @kobayashi, as that causes incompatibility with python2

**Comment by kobayashi** [comment]
Yes, my suggestion only focused on python3. @agowa338 's original is better for compatibility.
Thank you for the suggestion. :shipit:

**Review by goneri — APPROVED** [review]

**Pull request merged**
