### PR TITLE
Allow using action/local_action on includes and imports

### LINKED ISSUE #28822: local_action: include_role fails with 'this is probably a bug'
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
local_action: iclude_role

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel b35f39479b) last updated 2017/08/30 15:12:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Repos/ansible/lib/ansible
  executable location = /home/user/Repos/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

You cannot have a task that runs a role as local_action.

A workaround is `delegate_to: 127.0.0.1`.

##### STEPS TO REPRODUCE

```
.
├── playbook.yml
└── roles
    └── test
        └── tasks
            └── main.yml
```

* playbook.yml
```yaml
---

- name: Local action include role
  hosts: all
  tasks:
    - name: Trigger bug
      local_action: include_role name=test
```
* main.yml
```yaml
---

- debug: msg="will not be printed"
```

##### EXPECTED RESULTS

Ansible should execute the role and print the message 'will not be printed'
##### ACTUAL RESULTS

```
$ ansible-playbook -i "localhost," -c local playbook.yml -vvv
ansible-playbook 2.4.0 (devel b35f39479b) last updated 2017/08/30 15:12:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Repos/ansible/lib/ansible
  executable location = /home/user/Repos/ansible/bin/ansible-playbook
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
Parsed localhost, inventory source with host_list plugin

PLAYBOOK: playbook.yml ************************************************************************
1 plays in playbook.yml

PLAY [Local action include role] **************************************************************

TASK [Gathering Facts] ************************************************************************
Using module file /home/user/Repos/ansible/lib/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608 `" && echo ansible-tmp-1504099569.5-119095676611608="` echo /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608 `" ) && sleep 0'
<localhost> PUT /tmp/tmpnGFBA0 TO /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/ /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/setup.py; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1504099569.5-119095676611608/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Trigger bug] ****************************************************************************
task path: /home/user/Test/ansible-block/playbook.yml:6
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7fbe3cf06ad0>): TASK: Trigger
bug is not JSON serializable

ERROR! Unexpected Exception, this is probably a bug: 'Task' object has no attribute 'get_block_list'
the full traceback was:

Traceback (most recent call last):
  File "/home/user/Repos/ansible/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/home/user/Repos/ansible/lib/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/home/user/Repos/ansible/lib/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/home/user/Repos/ansible/lib/ansible/executor/task_queue_manager.py", line 289, in run
    play_return = strategy.run(iterator, play_context)
  File "/home/user/Repos/ansible/lib/ansible/plugins/strategy/linear.py", line 318, in run
    blocks, handler_blocks = new_ir.get_block_list(play=iterator._play, variable_manager=self._variable_manager, loader=self._loader)
AttributeError: 'Task' object has no attribute 'get_block_list'
```

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Allow using action/local_action on includes and imports. Fixes #28822

Using action or local_action on includes and imports doesn't work.  This is due to `playbooks/helpers.py` doing things like `if 'include_role' in task_ds:` which fails because the `task_ds` may look like:

```
{'local_action': {'module': 'include_role', 'name': 'foo'}}
```

or

```
{'local_action': 'include_role name=foo'}
```

This PR uses mod_args to determine the action in a more robust way.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/playbooks/helpers.py

##### ANSIBLE VERSION

```
2.4
2.5
2.6
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by bcoca** [comment]
i think we should go in opposite direction and make sure that the 'action' gets set correctly and compare to that.

There are things that should never workd i.e `action: module={{varwithimport_tasksvalue}}`, but the rest should work with `action/local_action` even if the 'local' part is irrelevant.

**Comment by sivel** [comment]
> i think we should go in opposite direction and make sure that the 'action' gets set correctly and compare to that.

I did specifically mention that I didn't think that was worthwhile.  We could, but it would involve a much larger refactor.

Right now we have a lot of code that just does `if "include" in task_ds:`.  Because at this point we haven't actually parsed the task ds.  That happens later, after we determine if it is one of these special cases.

We have at least 3 variants we would have to support:

* `if "include" in task_ds:`
* `if task_ds.get('module') == "include":` <- this one would need wrapped in a try/except for when the value is not a dict
* Some parser to pull validate `local_action: include foo.yml`

I think we would end up either having to create a new parser, that is separate from `Task`, and effectively parse the task ds 2 times, or move parsing much farther forward.

**Comment by bcoca** [comment]
modargsparser does this already, we might just want to refactor it to allow for 'external use'

**Comment by sivel** [comment]
@bcoca I've updated the code to use `ModuleArgsParser`, my only concern is that without much more refactoring, we will end up calling `ModuleArgsParser` 2 times for the same task in some scenarios.

**Pull request merged**
