### PR TITLE
Add packet project module

### PR DESCRIPTION
**Pull request by nurfet-becirevic**
##### SUMMARY
This PR adds a module for creating/removing project resources in the Packet host (https://packet.net).

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
cloud/packet/packet_project

##### ADDITIONAL INFORMATION
A "project" in the packet host is what "tenant" is in the Openstack - a grouping entity for allocated resources.

Same thing in Terraform is https://www.terraform.io/docs/providers/packet/r/project.html

Based on #27113 packet_project by @t0mk which needs to be closed without merging.

### CODE REVIEW

**Comment by baldwinSPC** [comment]
shipit

**Comment by medberry** [comment]
shipit

**Comment by t0mk** [comment]
shipit

**Comment by gundalow** [comment]
rebuild_merge

@nurfet-becirevic Thank you for this PR
@baldwinSPC @medberry @t0mk Thank you for the reviews

**Pull request merged**
