### PR TITLE
hostname: Add check_mode and diff support

### PR DESCRIPTION
**Pull request by kustodian**
##### SUMMARY
Add support for check_mode and diff to the `hostname` module

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`hostname` module

##### ANSIBLE VERSION
```
ansible 2.4.0
```

##### ADDITIONAL INFORMATION
`hostname` module didn't have support for check_mode, so it just skipped during check_mode. It also didn't report a diff what it actually changed. Here is the new output when `ansible-playbook` is run with `--check --diff`:
```
TASK [hostname] **********************
--- before
+++ after
@@ -1 +1 @@
-hostname = c7
+hostname = new-c7

changed: [c7]

```

### CODE REVIEW

**Review by dagwieers — APPROVED** [review]
shipit

**Comment by gundalow** [comment]
Looks sensible, thanks for this.

Since you have this PR open, could you please update
```
from ansible.module_utils.basic import *
from ansible.module_utils.facts import *
```
Thanks in advance

**Comment by kustodian** [comment]
@gundalow imports should now be fixed.

**Review by gundalow — APPROVED** [review]
Thanks. I'll merge into `devel` once shippable has run

**Comment by gundalow** [comment]
@kustodian Thanks :)

cc @alikins @saito-hideki Could we please get a final review from you? Thanks in advance

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
cc @alikins @saito-hideki Could we please get a final review from you? Thanks in advance

**Comment by kustodian** [comment]
Closing this, because @alikins implemented separately and it's now merged.

**Pull request closed without merging**
