### PR TITLE
Use a dedicated directory for the mongodb modules

### PR DESCRIPTION
**Pull request by Lujeni**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
mongodb

##### SUMMARY
- Use a dedicated directory for mongodb stuff.
- https://github.com/ansible/ansibullbot/pull/397

### CODE REVIEW

**Comment by gundalow** [comment]
CI is failing as the path to `mongodb_user.py` in `test/sanity/pep8/legacy-files.txt` needs updating

**Review by gundalow — CHANGES_REQUESTED** [review]
`test/sanity/pep8/legacy-files.txt` needs updating as well

**Comment by sivel** [comment]
The failures for `version_added` are erroneous. This is due to `validate-modules` seeing these as new modules because they were moved.  I don't have any immediate solution to resolve this in `validate-modules`.  Although we should look into a solution.  And may involve the change detection notifying `validate-modules` as such.

This error will not occur after merge.

**Review by gundalow — APPROVED** [review]

**Comment by mattclay** [comment]
@Lujeni The module validator has been updated to understand moved modules thanks to @sivel. CI is now passing.

**Comment by mattclay** [comment]
@Lujeni It looks like there's a mistake in the changes from ansible/ansibullbot#397 -- it doesn't match the changes in this PR. This PR uses `database/mongodb/` and the other used `database/database/`.

**Comment by Lujeni** [comment]
Thanks @mattclay, i need eyes ! (https://github.com/ansible/ansibullbot/pull/407)

**Pull request merged**
