### PR TITLE
Call set_play_context for stdout_callback plugin

### PR DESCRIPTION
**Pull request by diafour**
##### SUMMARY

TaskQueueManager used individual loop over callback plugins for calling set_play_context.
But stdout_callback was not included and never has set_play_context called.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
executor/TaskQueueManager

##### ANSIBLE VERSION
```
2.6 devel
```

##### ADDITIONAL INFORMATION
```
class CallbackModule(CallbackBase):
   CALLBACK_TYPE = 'stdout'

    def set_play_context(self, play_context):
        self._play_context = play_context
        # I was never called before this PR
```

### CODE REVIEW

**Comment by diafour** [comment]
Improvements of https://github.com/ansible/ansible/pull/35910 after conversation.

**Comment by mkrizek** [comment]
cc @jimi-c @bcoca

**Comment by bcoca** [comment]
I really need to remove this method, it is not good for callbacks to get a reference to the play context object.

**Comment by diafour** [comment]
@bcoca i was trying to get connection type in my stdout callback but now it seems a bad solution.
Should i close this PR?

**Comment by bcoca** [comment]
The task object itself should have the connection type used, i need to check if that is still the case.

**Comment by jimi-c** [comment]
Hi, this appears to have been resolved by https://github.com/ansible/ansible/pull/35910.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request closed without merging**
