### PR TITLE
fix loading host/group vars when inventory is directory and using --limit

### LINKED ISSUE #13557: host_vars do not get fully loaded when using 'inventory' directory and --limit
##### Issue Type:
- Bug Report
- Bugfix Pull Request
##### Ansible Version:
- 1.9.4
##### Ansible Configuration:

```
[defaults]
inventory=inventory
```
##### Environment:

```
./inventory/g
./host_vars/h1
./host_vars/h2
./playbook.yml
```
##### Summary:

host_vars are not loaded when using inventory directory and --limit flag
##### Steps To Reproduce:

```
#./inventory/g
h1
h2
```

```
#./host_vars/h1

---
key: h1
```

```
#./host_vars/h2

---
key: h2
```

```
#./playbook.yml

---

- name: test host_vars includes
  gather_facts: no
  hosts: all
  tasks:
    - debug: var=hostvars['h1'].key
    - debug: var=hostvars['h2'].key
```

```
ansible-playbook playbook.yml -l h1
```
##### Expected Results:

```
PLAY [test host_vars includes] ************************************************

TASK: [debug var=hostvars['h1'].key] ******************************************
ok: [h1] => {
    "var": {
        "hostvars['h1'].key": "h1"
    }
}

TASK: [debug var=hostvars['h2'].key] ******************************************
ok: [h1] => {
    "var": {
        "hostvars['h2'].key": "h2"
    }
}

PLAY RECAP ********************************************************************
h1                         : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [test host_vars includes] ************************************************

TASK: [debug var=hostvars['h1'].key] ******************************************
ok: [h1] => {
    "var": {
        "hostvars['h1'].key": "h1"
    }
}

TASK: [debug var=hostvars['h2'].key] ******************************************
ok: [h1] => {
    "var": {
        "hostvars['h2'].key": "{{hostvars['h2'].key}}"
    }
}

PLAY RECAP ********************************************************************
h1                         : ok=2    changed=0    unreachable=0    failed=0
```

### PR DESCRIPTION
**Pull request by xytis**
fixes #13557

### CODE REVIEW

**Comment by bcoca** [comment]
what problem/case are you trying to solve with this?

**Comment by xytis** [comment]
Sorry, was filling up the bug report :)

**Comment by xytis** [comment]
This PR might break such workflow:

```
./playbook.yml
./hostgroup1/host_vars/...
./hostgroup1/inventory
./hostgroupX/...
```

```
ansible-playbook playbook.yml -i hostgroup1
```

**Comment by xytis** [comment]
As far as I debugged, the issue is related to the fact that ansible tries to search the `dirname` for string `inventory/` which is `inventory/`to load up host_vars. The reason why having inventory in directory format works in the first place seems like a hotfix, which rechecks part of hosts when basedir is considered to be changed.

Are there any similar issues which involve inventory loading sequence in v2 ?

**Comment by abadger** [comment]
Merged to stable-1.9.  Will be in 1.9.5 when that's released.

**Comment by abadger** [comment]
Reverted as it was causing https://github.com/ansible/ansible/issues/15093  Looking for another fix.

**Pull request merged**
