### PR TITLE
Add --download-only support for packaging/apt module.

### LINKED ISSUE #23220: [Feature Request] apt module: add state "downloaded"
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
apt module, potentially other package managing modules

##### ANSIBLE VERSION
n/a

##### OS / ENVIRONMENT
Debian and derivatives

##### SUMMARY
Add option to download packages locally without installing them.

##### STEPS TO REPRODUCE
Emulating the user experience of:

    apt-get -d / apt-get download / apt-get --download-only [package1 package2]

Example:

```yaml
tasks:
  - name: Download all latest packages, but don't install yet
    apt:
      update_cache: yes
      only_upgrade: yes
      state: downloaded
```

##### EXPECTED RESULTS

After setting this flag, the specified package(s) can be installed later without requiring a download from the repository server(s).

##### ACTUAL RESULTS

Currently, this functionality of apt-get is not exposed in the apt module.

### PR DESCRIPTION
**Pull request by abednarik**
##### SUMMARY

Add --download-only option to apt module

Fixes #23220

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/packaging/os/apt.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.0 (apt_download_only 4def437187) last updated 2017/05/03 14:32:40 (GMT +000)
  config file =
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION

- Example playbook

```
---

- name: Test PR for Ansible
  hosts: servers
  become: True

  tasks:
    - name: Download a package only
      apt:
        name: yasat
        state: present
        download_only: true
```

- Output

```
TASK [Download a package only] ***************************************************************************************************************************************************
changed: [ansibledev_ubuntu14] => {"cache_update_time": 1493814974, "cache_updated": false, "changed": true, "stderr": "", "stderr_lines": [], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  yasat\n0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.\nNeed to get 106 kB of archives.\nAfter this operation, 606 kB of additional disk space will be used.\nGet:1 http://archive.ubuntu.com/ubuntu/ trusty/universe yasat all 526-1 [106 kB]\nFetched 106 kB in 1s (68.0 kB/s)\nDownload complete and in download only mode\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  yasat", "0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.", "Need to get 106 kB of archives.", "After this operation, 606 kB of additional disk space will be used.", "Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe yasat all 526-1 [106 kB]", "Fetched 106 kB in 1s (68.0 kB/s)", "Download complete and in download only mode"]}

PLAY RECAP ***********************************************************************************************************************************************************************
ansibledev_ubuntu14        : ok=2    changed=1    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by abednarik** [comment]
Hello

 Anything incorrect or pending here? Please, feel free to let me know.

Thanks.

**Comment by abednarik** [comment]
Friendly reminder to not leave this PR open.

Thanks

**Comment by abednarik** [comment]
If someone can provide an update in this Pr I will much appreciate that.

Thanks.

**Comment by yom** [comment]
Thumbs up for this feature, I'm dying to see "apt-get --download-only" implemented in Ansible !

**Comment by abednarik** [comment]
IF there is still some interest on this, I can do a rebase and review  it again. Please let me know, otherwise is fine to close it.

Cheers.

**Comment by taylorreece** [comment]
@abednarik I'm definitely interested in this; thanks!

**Comment by abednarik** [comment]
Ok. I will  review this one today and rebase, to see if we can get some feedback.

Cheers.

**Comment by clofresh** [comment]
I'm interested in this feature as well. My use case is to download apt packages to a docker volume so that future installs won't have to download them over and over again.

**Comment by relrod** [comment]
Closing in favor of #61500.

**Pull request closed without merging**
