### PR TITLE
Create a common EC2 connection argument spec for EC2 modules

### PR DESCRIPTION
**Pull request by willthames**
##### Issue Type:

Feature Pull Request
##### Ansible Version:

Based on:
ansible 1.5 (devel a0f91f2aaa) last updated 2014/02/05 20:43:12 (GMT +1000)
##### Environment:

N/A
##### Summary:

Refactor the currently well-factored ec2 modules (i.e. those that already use ec2_connect) to 
have a common argument spec. The idea is that new modules can use this spec without duplication
of code, and that new functionality can be added to the ec2 connection code (e.g. security 
token argument)
##### Steps To Reproduce:

N/A
##### Expected Results:

No actual change in functionality
##### Actual Results:

No apparent actual change in functionality of the modules I've tested

### CODE REVIEW

**Comment by willthames** [comment]
It's also tempting to similarly extract the docstrings for the common EC2 connection variables but I'm not sure if that will still work with Sphinx. Another alternative would be a common page for just the EC2 variables. Otherwise adding e.g. security_token will need additional documentation for all modules that use it.

**Comment by jctanner** [comment]
@willthames I would prefer to use the same pattern as the rax modules, where the argument spec is updated for unique parameters.

```
    argument_spec = rax_argument_spec()
    argument_spec.update(
        dict(
            comment=dict(),
            email=dict(),
            name=dict(),
            state=dict(default='present', choices=['present', 'absent']),
            ttl=dict(type='int', default=3600),
        )
    )
```

**Comment by sivel** [comment]
Here is a ticket I had created to see about how to share DOCUMENTATION #5753 

It was closed pretty quickly as it was more of a question and should have been directed to the mailing list, but @mpdehaan mentioned he believes that the DOCUMENTATION should be repeated in each module and not shared.

**Comment by willthames** [comment]
@jctanner - yeah, doing it that way would work for me too. Haven't really had much cause to look at the rax modules so far, so I'll see how they do it.

**Comment by willthames** [comment]
@sivel - did the question get asked on list? I'm in agreement with you, the number of common arguments is only going to increase. Anyway, I'll defer that bit for now and concentrate on the argument spec!

**Comment by willthames** [comment]
@jctanner - this is now almost identical to the rax approach.

**Comment by jctanner** [comment]
@willthames thank you!

**Pull request merged**
