### PR TITLE
Adding module win_dns_a

### PR DESCRIPTION
**Pull request by Daniel-Sanchez-Fabregas**
##### SUMMARY

This module adds a DNS A record to Active Directory.
The main use case is to add non-windows computers to Active Directory
DNS through a bridge windows computer.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

win_dns_a

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = ~/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.local/share/virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = ~/.local/share/virtualenvs/ansible/bin/ansible
  python version = 3.6.4 (default, Feb  8 2018, 14:42:51) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
```

##### ADDITIONAL INFORMATION
Example of use:
```
  - name: Add linux computer DNS A record in Active Directory using a windows machine
    win_dns_a:
      computer_name: dns_controller.example.com
      zone_name: example.com
      name: linux_server.example.com
      ipv4_address: 192.168.0.1
      state: present
    delegate_to: windows_brigde.example.com

  - name: Remove linux computer DNS A record in Active Directory using a windows machine
    win_dns_a:
      computer_name: dns_controller.example.com
      zone_name: example.com
      name: linux_server.example.com
      state: absent
    delegate_to: windows_brigde.example.com
```

### CODE REVIEW

**Comment by angystardust** [comment]
Great addition @Daniel-Sanchez-Fabregas! Do you think it's possible to also add an option to create the relative PTR entry? Or maybe it would be better to have a different module (win_dns_ptr) for this task :thinking:

**Comment by angystardust** [comment]
Am I wrong or this module rely on the [xDnsServer DSC](https://github.com/PowerShell/xDnsServer) to be installed on the bridge machine?
In this case, please notice what they say on the README.md:

> xDnsARecord {Will be removed in a future release}

you should instead use the `xDnsRecord` resource with the `Type` option set to `A`

**Comment by Daniel-Sanchez-Fabregas** [comment]
I'm adapting to release a win_dns_ptr module @angystardust

I'm using [`Get-DnsServerResourceRecord`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserverresourcerecord), `Add-DnsServerResourceRecordA` and `Remove-DnsServerResourceRecord` not really sure too if this is affected for this and for compatibility with PowerSell 2.0

Have to take a look to `xDnsRecord`

**Comment by dagwieers** [comment]
So I think this module should be renamed to **win_domain_dns_a** as all modules influencing AD start with **win_domain_**.

**Comment by nwsparks** [comment]
Why is it just limited to A records? I think if a module is added for managing DNS records, it should be able to perform actions on any record type.

**Comment by steaksauce-** [comment]
On the subject of @nwsparks and @dagwieers comments, maybe `win_domain_dns` with a warning about `CURRENTLY SUPPORTS THE FOLLOWING RECORDS: [A]` and change this to WIP with the understanding that support for all records will be included?

**Comment by Daniel-Sanchez-Fabregas** [comment]
@dagwieers will rename the module to **win_domain_dns_a**
@nwsparks I tried to cover my use case creating A and PTR and it got complex.
I remembered `Simple is better than complex` and decided to split it in two modules.
It's done and I will make a new pull request with a `win_domain_dns_ptr` module.
Not sure how to uncomplex it as it is now, don't know if `xDnsARecord`vs `xDnsRecord` will simplify it because I'm a little lost there.

**Comment by angystardust** [comment]
@Daniel-Sanchez-Fabregas my understanding is that you're using powershell module. `xDnsRecord` is a DSC module instead. You can find what DSC is here: https://docs.microsoft.com/en-us/powershell/dsc/overview
Fundamentally DSC module it's just a wrapper around the powershell module so I think it's better to implement this module as you're already doing in this module using directly the powershell module. @dagwieers do you agree?

**Comment by dagwieers** [comment]
Well, the other consideration I had was related to DSC. If there's already a perfectly fine DSC resource for managing this, I don't think there's a need for a dedicated Ansible module.

In that case (and I don't know if the DSC resource is at all viable) I would add specific examples using the DSC resource to: https://docs.ansible.com/ansible/devel/user_guide/windows_dsc.html#examples

I wouldn't mind if the example-section would be greatly extended with more concrete DSC examples.

**Comment by varunchopra** [comment]
@dagwieers You're assuming that hosts have PowerShell 5, but they mostly don't so a dedicated module would still help.

**Comment by nitzmahone** [comment]
Since Windows DNS servers don't *have* to be backed by AD, I'd probably vote for `win_dns_a_record` as the right module name, assuming we want to keep it restricted to just A records.

If you look at some of the stuff that was done with Azure DNS/AWS Route 53, there was a more generic approach that works for lots of record types. The Azure one also accepts a list of records. I think that's probably a more scalable approach than duplicating all the boilerplate for every record type, and also allows for things like "auto-create the right PTR record" options for A/AAAA and others. It makes the overall module code a little more complex, but also allows for faster operation if dealing with more than one record and streamlines integration testing somewhat (single module vs N, if you take it to its logical conclusion). If we go that route, then just `win_dns_record` is probably the right name, even if the initial implementation only supports A records. So something like:
```
win_dns_record:
  zone_name: blar.com
  server: mydns.blar.com
  records:
  - type: A
    ip_address: 1.2.3.4
    # idempotence is tricky here; how do we deal with existing records?
    create_ptr_record: true
```

**Comment by angystardust** [comment]
@Daniel-Sanchez-Fabregas `create_ptr_record` as a parameter of the module would be great!

**Comment by angystardust** [comment]
You're prefecly right @dagwieers but we should also consider these facts:
- the DNS dsc resources are contained in the [xDnsServer](https://github.com/PowerShell/xDnsServer) as mentioned in the ansible [windows dsc documentation page](http://docs.ansible.com/ansible/devel/user_guide/windows_dsc.html#custom-dsc-resources)...

> DSC resources developed by Microsoft that start with x, means the resource is experimental and comes with no support.

- currently the xDnsServer only supports ARecord and CName record types. There's a PR to add [support for PTR record](https://github.com/PowerShell/xDnsServer/pull/60) but it seems nobody cares to merge it anytime soon. 

So, in the end, I think that in the mid-term it's better to have a native powershell module but I absolutely agree with you about extending the DSC example section in the official documentation.

**Comment by angystardust** [comment]
no news on this new module @Daniel-Sanchez-Fabregas ?

**Comment by Daniel-Sanchez-Fabregas** [comment]
Sorry I was busy. Now I'm trying to finish # 35954 and looking at `win_dsc` module with `xDnsServer` before returning to this.

**Comment by angystardust** [comment]
Hi @Daniel-Sanchez-Fabregas no hope to push this module for the 2.6 timeframe?
as suggested by @dagwieers, the code-freeze is near :(
https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_6.html

**Comment by Daniel-Sanchez-Fabregas** [comment]
Sorry, no advance here.

**Comment by dagwieers** [comment]
Beware that the deadline for getting new features/modules accepted in [Ansible v2.7 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_7.rst#release-schedule), it is set to either 2018-08-23 or 2018-08-30. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to the [Windows Working Group meeting agenda](https://github.com/ansible/community/issues/294) to get it resolved.

**Comment by dagwieers** [comment]
During the [next Windows WG meeting](https://github.com/ansible/community/issues/420) on 2019-01-29 we will review and decide on the inclusion of this module in Ansible v2.8. Your presence in the meeting could be helpful.

*If there's anything you wanted to improve/fix, please do so before the meeting.*

**Comment by jborean93** [comment]
Hi @Daniel-Sanchez-Fabregas are you still interested in continuing with this module. We would like to see some sort of DNS module for Windows and would be interested in making changes to this for the 2.8 release. The two things we are looking for is to make it more generic around the various record type similar to the [azure_rm_dnsrecordset](https://docs.ansible.com/ansible/latest/modules/azure_rm_dnsrecordset_module.html) module as well as some integration tests.

**Comment by Daniel-Sanchez-Fabregas** [comment]
>  The two things we are looking for is to make it more generic around the various record type similar to the [azure_rm_dnsrecordset](https://docs.ansible.com/ansible/latest/modules/azure_rm_dnsrecordset_module.html) module 

My use case is less ambitious than `azure_rm_dnsrecordset` module. I only need A, PTR and CNAME. With all PTR paired to a A, and A could have multiple IP.

I hope that it don't make it too complex (time developing consuming).

> as well as some integration tests.

Which of the [integration tests](https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html#windows-tests) in the source code could be similar to what we are looking for  this module?

**Comment by jborean93** [comment]
> Which of the [integration tests](https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html#windows-tests) in the source code could be similar to what we are looking for this module?

While definitely not the newest tests I think [win_iis_webapppool](https://github.com/ansible/ansible/tree/devel/test/integration/targets/win_iis_webapppool/tasks) may be similar to what you are looking you. It installs a feature and cleans up afterwards, you could also look at the [win_rds](https://github.com/ansible/ansible/tree/devel/test/integration/targets/win_rds) tests as well.

Tests can be time confusing but they are really quite necessary for maintaining a module. Without them a simple change could have consequences not thought off in a review. While it would be nice, you don't have to test every single scenario, really just the key ones.

**Comment by Daniel-Sanchez-Fabregas** [comment]
I'm abandoning this PR for #52317 (Except said otherwise)

**Pull request closed without merging**
