### PR TITLE
nxos_telemetry replaced state

### PR DESCRIPTION
**Pull request by mikewiebe**
This PR replaces https://github.com/ansible/ansible/pull/61799

##### SUMMARY
Adds `state: replaced` for `nxos_telemetry` resource module.

NOTE: Includes both unit and integration tests.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
nxos_telemetry

### CODE REVIEW

**Comment by mikewiebe** [comment]
This is a copy and paste from the comment originally by @abadger left in https://github.com/ansible/ansible/pull/61799

---- 

I was asked to take a look at whether this could go into 2.9.x or if it must be targetted at 2.10. This is a new feature and we are several weeks past the feature freeze so it would usually be too late.

However, this release cycle we've already had to make exceptions for other features targeting isolated areas of the code to merge after feature freeze. At worst, this feature would break nxos_telemetry (a new module which no one would be using yet) and nxos_facts (unfortunately, a module which is probably in wide use already). Several people have reviewed the code that would be used by nxos_facts to mitigate the risk from that code.

If this can be finished and the backport PR opened by end of day Wednesday, September 18th so that I can merge it to stable-2.9 no later than Thursday, before I cut rc1, then I'll let this in.

**Comment by mikewiebe** [comment]
Just a reminder that the backport will need a changelog fragment

**Comment by abadger** [comment]
Everything I noted has been fixed in this version.  @trishnaguha is nxos your area to approve and make sure it gets backported in time?

**Review by trishnaguha — APPROVED** [review]

**Comment by trishnaguha** [comment]
@abadger @mikewiebe @ikhan2010 The backport PR is opened https://github.com/ansible/ansible/pull/62406.

**Pull request merged**
