### PR TITLE
added new module "ovirt"

### PR DESCRIPTION
**Pull request by vincentvdk**
I added a new module "ovirt" that allows Ansible to manage an oVirt platform. Currently it only has support to manage the lifecycle of a VM/Instance like stop, start, restart, create from template and create an entire VM from scratch defining HD, memory, cpu, ..
I'm planning on adding more functionality later like registering machines as hypervisor nodes.

### CODE REVIEW

**Comment by jlaska** [comment]
Not sure if it's helpful, but I was also interested in building a module that acts as a wrapper around the oVirt REST API (https://github.com/jlaska/ansible-rhevm-all-in-one/blob/master/library/ovirt_api). I'm still fleshing out the documentation and examples, but this would allow access to the full oVirt REST API, without need for additional glue around ovirtsdk.

**Comment by vincentvdk** [comment]
I personally think that the oVirt SDK allows some cleaner and more readable code. The module has already some functionality and has been tested ( though by me ).
If I'm not mistaken your rest based module also requires some libraries?

**Comment by jlaska** [comment]
Thanks for your feedback!

> I personally think that the oVirt SDK allows some cleaner and more readable code.

Don't get me wrong, the oVirt SDK is great.  I use that extensively already (see https://github.com/jlaska/ansible-rhevm-all-in-one/blob/master/files/ovirt-cli.py).  The trouble I run into is that it requires a lot of glue code to add a wrapper around the existing wrapper.  That seemed like wasted coding, IMO.  My sense is the oVirt SDK is useful as a library when performing specific functions.  If the goal is to build a module that provides a more general level of access to the full range of oVirt functionality, exposing the REST API seems like a better choice (less code).  As currently implemented, the REST API approach provides json response data back to the ansible playbook to allow for variable registration and conditional execution. 

I don't object to the proposed module.  Perhaps it could be renamed to indicate what level of oVirt functionality you are exposing (e.g. ovirt_vm)? 

>  If I'm not mistaken your rest based module also requires some libraries?

Regarding dependencies, yes, the REST API approach requires the python requests module.  However, this is a much smaller footprint than ovirt-engine-sdk (and deps).

**Comment by vincentvdk** [comment]
Hi, 

I think using the oVirt SDK is quite straight forward and allows you to easy implement new things. I also find the documentation better, but that is my personal feeling.

> I don't object to the proposed module. Perhaps it could be renamed to indicate what level of oVirt functionality you are exposing (e.g. ovirt_vm)?

My goal is to add as much functionality in the same module. Currently it has the most basic but also most used used functions (VM lifecycle).

**Comment by mpdehaan** [comment]
Merged, thank you!  Sorry for the delay on the backlog!

**Comment by jlaska** [comment]
@vincentvdk apologies, I didn't circle back on this thread.  I discussed the module philosophy with mpdehaan a while back and now agree with your approach.  A specific ovirt module is more declarative and requires less REST knowledge than a generic REST api module.  Thanks for the contribution!

**Comment by vincentvdk** [comment]
@mpdehaan no problem. Thanks for merging!
@jlaska : cool. I don't know if you're using oVirt/RHEV but maybe we can add more functionality later on..

**Pull request merged**
