### PR TITLE
inventory now errors for invalid group/host names

### LINKED ISSUE #45493: YAML inventory - Unable to use integers for group
##### SUMMARY

Unable to create a group name with only integers.  Rename the group to include letters and the playbook executes.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

YAML inventory with ansible-playbook
##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules/ntc-ansible', u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/callbacks']
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks', 'dense', 'selective']
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/.ansible/tmp/ansible-local-3040QMmQt_
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/modules/ntc-ansible', u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04.1 LTS
##### STEPS TO REPRODUCE

Create a group with just numbers, inventory example below

```yaml
---
all:
  children:
    sites:
      children:
        1234:
          hosts:
            switch1:
            switch2:
            switch3:
```

##### EXPECTED RESULTS

Playbook to run

##### ACTUAL RESULTS

Playbook does not execute.

```paste below
ansible-playbook 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules/ntc-ansible', u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
Using /etc/ansible/ansible.cfg as config file
Parsed /home/ansible/inventory/hosts.yml inventory source with yaml plugin
ERROR! Unexpected Exception, this is probably a bug: expected string or buffer
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 112, in run
    hosts = CLI.get_host_list(inventory, self.options.subset)
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 828, in get_host_list
    if len(inventory.list_hosts()) == 0:
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 557, in list_hosts
    result = [h for h in self.get_hosts(pattern)]
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 352, in get_hosts
    hosts = self._evaluate_patterns(patterns)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 397, in _evaluate_patterns
    that = self._match_one_pattern(p)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 449, in _match_one_pattern
    hosts = self._enumerate_matches(expr)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 529, in _enumerate_matches
    matching_groups = self._match_list(self._inventory.groups, pattern)
  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 323, in _match_list
    if pattern.match(item):
TypeError: expected string or buffer
```

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
also made yaml inventory slightly smarter

fixes #45493

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

inventory
##### ANSIBLE VERSION

```paste below
2.x
```

### CODE REVIEW

**Comment by s-hertel** [comment]
LGTM

**Comment by mattclay** [comment]
CI failure in the `callback_default` integration test. The expected output likely needs to be updated:

https://app.shippable.com/github/ansible/ansible/runs/83473/57/console

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by mattclay** [comment]
This change is causing integration tests to fail:

https://app.shippable.com/github/ansible/ansible/runs/93931/87/tests
https://app.shippable.com/github/ansible/ansible/runs/93931/93/tests

Specifically these tests:

ansible-test integration inventory_foreman --docker -v
ansible-test integration inventory_vmware_vm_inventory --docker -v

These tests aren't included in the smoke tests, which is why the issue wasn't detected during testing of this pull request.

**Pull request merged**
