### PR TITLE
validate-modules for plugins: do some more schema validations so that some issues that are currently reported for modules are also reported for plugins

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Issues that are now reported for plugins and not just modules:
- `required: true` and a docs default;
- `elements` present without `type=list`
- `elements` not present with `type=list` (this isn't used by the config manager to my knowledge, but it is printed in the documentation and thus helpful to end-users)
- check values of `default` and `choices` to make sure they actually match `type`

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible-test sanity test validate-modules

### CODE REVIEW

**Comment by felixfontein** [comment]
Some of the issues reported are because `default` or `choices` values are integers or floats, while `type=str`. Whether this is a real problem that should be fixed is debatable. I think it's better to fix them so that the YAML (and thus the ansible-doc JSON output) has them in the correct type.

**Comment by felixfontein** [comment]
Actually for non-modules and `choices`, it is important that the type is correct, since the config manager does not convert the choices values.

(If wanted I can restrict the type checks to non-modules.)

**Comment by briantist** [comment]
seems like a good idea to me.. I would like to be able to test it with my own collection but unfortunately I haven't been able to use the test containers in devel locally in docker for a while now (seems like they now require your local host to have systemd or something like that; it's hard to tell since the containers just prematurely exit).

**Review by jborean93 — APPROVED** [review]

**Comment by felixfontein** [comment]
@jborean93 thanks for reviewing and merging this one as well!

**Pull request merged**
