### PR TITLE
VMware: Add support for datastore cluster

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Review by pdellaert — APPROVED** [review]
shipit

**Comment by qmarc** [comment]
Hey Guys, I have been trying to test code changes but it does not appear to be working for me. To give you a quick idea of our architecture we are using clustered vSphere hosts and clustered Datastores, the VM Template exists in the same Datastore cluster as we are deploying/cloning our VM to using vmware_guest. 

To test the code I did the following:

1. Created a library folder beneath my playbooks folder, my structure looks like:
> - environments
>      - dev
>      - test
>      - prod
> - playbooks
>       deploy-cluster.yml
>     - library
>          vmware_guest_cluster.py
> - roles

2. I renamed your python script as above, and renamed my YAML references to it.

I have removed some portions of the below YAML to highlight the parts of interest, but this is how I am running the module:

```yaml
- vmware_guest_cluster:
   name: "new-server-name"
   hostname: "vcenter_host.mydomain.com.au.local"
   esxi_hostname: ""
   datacenter: "DAP"
   validate_certs: false
   state: "poweredon"
   template: "windows-2016-core-1709"
   folder: "/Prod/Example & Path/ClusterLoc"
   wait_for_ip_address: yes

   disk:
   - size_gb: "100"
     type: "thin"
     datastore: "clustered_datastore_name"
     autoselect_datastore: "true"

   - size_gb: "100"
     type: "thin"
     datastore: "clustered_datastore_name"
     autoselect_datastore: "true"

   - size_gb: "100"
     type: "thin"
     datastore: "clustered_datastore_name"
     autoselect_datastore: "true"
 delegate_to: localhost
```

I keep getting the following error, which by the way I was getting before testing the new Module:
`Failed to create a virtual machine : Unable to access the virtual machine configuration: Unable to access file [DATASTORE-NAME-IN-CLUSTER] windows-2016-core-1709/windows-2016-core-1709.vmtx`

Is there anything wrong with my example, any pointers would be awesome?

**Comment by Akasurde** [comment]
@qmarc Thanks for testing this feature. Could you please open a new issue, so that we can track the issue easily ? Also, I see there is no value for esxi_hostname. Did you redact it or you are not specifying this value ?

**Comment by qmarc** [comment]
Thanks @Akasurde I have been doing more testing on this today, my findings were that testing this pull-request was kind of redundant because its in the stable-2.5 branch and I am currently using Ansible 2.5.2, so I was using it anyway. so switching back to the pre-packaged version of the Module provided me with a different error message `Failed to create a virtual machine : Incompatible device backing specified for device '0'.`.

This error suggested a configuration issue, I had provisioned the machines in a subnet using DHCP, however because my other environments are currently using static IP's, and I wanted to reuse the same `vmware_guest` YAML by simply not providing values for the IP and subnet variables but still having the properties `ip` and `netmask` present in `vmware_guest` i.e:

```YAML
#### environments/prod/group_vars/all ####
....
vcentre_esxi_host:      # Left empty to allow for ESXI clustering
adapter1_ipv4_address:  # Left empty for DHCP dynamic IP addressing
subnet_mask:            # Left empty for DHCP dynamic IP addressing
....

#### task-guest-static.yml ####
- vmware_guest:
    esxi_hostname: "{{ vcentre_esxi_host }}"
    networks:
    - name: "{{ adapter1_net }}"
      ip: "{{ adapter1_ipv4_address }}"
      gateway: "{{ default_gateway }}"
      netmask: "{{ subnet_mask }}"
```

This causes the `Incompatible device`  error, removing those properties allowed my automation to run (with `datastore: <my-clustered-datastore-name>` and `autoselect_datastore: true`). So now I can successfully deploy to a DRS enabled clustered datastore (using 2.5.2 version of `vmware_guest`).

Although as per the [Unable to Clone VMware VM Template #27062](https://github.com/ansible/ansible/issues/27062) I am also getting the `Unable to access the virtual machine configuration: Unable to access file [DATASTORE-NAME]`, with this pull-request or using the `vmware-guest` from the main branch I still have to supply a ESXI hostname to allow a VM to be provisioned. Which leads into your question, about the EXSI host. To allow VM's to be provisioned on any ESXI host, this property existed in the `vmware_guest` feature however as described with the `ip` and `netmask` variable is simply empty.

Conclusion, Datastore clustering does indeed work! However I hope my issues provided some value to others who have been getting pretty high level error messages that are difficult to determine the actual nature of the problem.

**Pull request merged**
