### PR TITLE
Support setting persistent command timeout per task basis

### LINKED ISSUE #42200: Cannot set command timeout per task with network_cli
##### SUMMARY
When attempting to run a command that may take more then 10 seconds, a comamnd timeout error is returned.

The [Network Debug Troubleshooting documentation](https://docs.ansible.com/ansible/2.5/network/user_guide/network_debug_troubleshooting.html) notes the following:

```
Option 2: Increase command timeout per task basis. All network modules support a timeout value that can be set on a per task basis. The timeout value controls the amount of time in seconds before the task will fail if the command has not returned.
```

This appears to be referring to the old provider method and not to the network_cli connection method. The [network_cli documentation](https://docs.ansible.com/ansible/2.5/plugins/connection/network_cli.html) notes a variable of 'persistent_command_timeout' but it doesn't look like there's an option to set this on a per-task basis (unlike what the troubleshooting documentation notes).

From testing, it appears that this can only be configured globally, either via ansible.cfg or via an environment variable prior to running a playbook.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

network_cli

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /home/MYUSER/ansible/playbooks/CiscoASA/ansible.cfg
  configured module search path = [u'/home/MYUSER/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
 DEFAULT_CALLBACK_WHITELIST(/home/MYUSER/ansible/playbooks/CiscoASA/ansible.cfg) = ['profile_tasks', 'timer']
 DEFAULT_LOG_PATH(/home/MYUSER/ansible/playbooks/CiscoASA/ansible.cfg) = /home/MYUSER/ansible.log
 DEFAULT_STDOUT_CALLBACK(/home/MYUSER/ansible/playbooks/CiscoASA/ansible.cfg) = yaml
 HOST_KEY_CHECKING(/home/MYUSER/ansible/playbooks/CiscoASA/ansible.cfg) = False
 PERSISTENT_CONNECT_TIMEOUT(/home/MYUSER/ansible/playbooks/CiscoASA/ansible.cfg) = 30
 RETRY_FILES_ENABLED(/home/MYUSER/ansible/playbooks/CiscoASA/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
CentOS Linux release 7.5.1804 (Core)
```

##### STEPS TO REPRODUCE

```yaml
        - name: Fetch access-lists
          connection: network_cli
          become_method: enable
          become: yes
          asa_command:
            commands: "show access-list"
          register: show_acls
```

Adding 'timeout' or 'persistent_command_timeout' gives the following warning:
```
 [WARNING]: Ignoring invalid attribute: timeout
```

##### EXPECTED RESULTS

The command to wait until the specified timeout before failing

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: timeout trying to send command: show access-list
fatal: [lab_asa]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_5zlxcI/ansible_module_asa_command.py", line 200, in <module>
        main()
      File "/tmp/ansible_5zlxcI/ansible_module_asa_command.py", line 170, in main
        responses = run_commands(module, commands)
      File "/tmp/ansible_5zlxcI/ansible_modlib.zip/ansible/module_utils/network/asa/asa.py", line 124, in run_commands
      File "/tmp/ansible_5zlxcI/ansible_modlib.zip/ansible/module_utils/connection.py", line 149, in __rpc__
    ansible.module_utils.connection.ConnectionError: timeout trying to send command: show access-list
  module_stdout: ''
  msg: MODULE FAILURE
  rc: 1
```

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

Fixes #42200

*  Add variable `ansible_command_timeout` to `persistent_command_timeout`
   option for `network_cli` and `netconf` connection plugin so that the
   command_timeout can be set per task basis while using `connection=network_cli`
   or `connection=netconf`
   eg:
   ```
   - name: run command
     ios_command:
       commands:
       - show version
     vars:
      ansible_command_timeout: 40
   ```

* Modify `ansible-connection` to read command_timeout value from
  connection plugin options.

* Add `ansible_command_timeout` to `persistent_command_timeout`
  option in `persistent` to support `connection=local` so that
  it is backward compatibilty

* To support `connection=local` pass the timeout value as variables
  from persistent connection to `ansible-connection` instead of sending
  it in playcontext
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

bin/ansible-connection
plugins/action/aruba.py
plugins/action/asa.py
plugins/action/bigip.py
plugins/action/bigiq.py
plugins/action/ce.py
plugins/action/cnos.py
plugins/action/dellos10.py
plugins/action/dellos6.py
plugins/action/dellos9.py
plugins/action/enos.py
plugins/action/eos.py
plugins/action/ios.py
plugins/action/iosxr.py
plugins/action/ironware.py
plugins/action/junos.py
plugins/action/dellos10.py
plugins/action/net_base.py
plugins/action/nxos.py
plugins/action/sros.py
plugins/action/vyos.py
plugins/connection/netconf.py
plugins/connection/network_cli.py

##### ANSIBLE VERSION

```
2.7
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by Qalthos — CHANGES_REQUESTED** [review]
Looks good, but can you add some tests? Say setting `ansible_command_timeout: 1`and running `show run` or equivalent to smoke tests

**Comment by gundalow** [comment]
We have an existing issue https://github.com/ansible/ansible/issues/39022 for improving documentation for timeouts

**Comment by ganeshrn** [comment]
@Qalthos Added test case

ready_for_review

**Review by Qalthos — APPROVED** [review]

**Comment by guest088** [comment]
@ganeshrn I can see this pull request has been merged into the devel branch but it doesn't seem to work for me when using the latest code from the devel branch. I still encounter command timeouts that are less than the value I specified for the ansible_command_timeout and/or persistent_command_timeout properties. From what I can determine, the SSH socket timeout is only set once within network_cli.py (self._ssh_shell.settimeout(self.get_option('persistent_command_timeout'))) and that's when first establishing the connection. After the connection has been established, it becomes a persistent connection and is reused and I can't see where the socket timeout is ever modified when specified per task.

**Pull request merged**
