### PR TITLE
Fix Grafana dashboard overwriting

### PR DESCRIPTION
**Pull request by jqueuniet**
##### SUMMARY
Fix Grafana dashboard overwriting when specifying uid by Ansible module

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`grafana_dashboard`

##### ADDITIONAL INFORMATION
Currently, you can't overwrite a Grafana dashboard if you rely on an uid passed by Ansible module. The issue comes from the dashboard creation, which doesn't keep this uid and lets the Grafana API generate a random one. Any following `grafana_dashboard` call will fail with the following error, as it tries to recreate an already existing dashboard. 

 ```
~/src/ansible/hacking/test-module -m grafana_dashboard.py -a "grafana_url='http://mygrafana.test' grafana_password=XXXXXXXXXXXXX uid=1860 state=present overwrite=yes path=/tmp/dashboards/1860.json message='test edit'"
* including generated source, if any, saving to: /home/johann/.ansible_module_generated
* ansiballz module detected; extracted module source to: /home/johann/debug_dir
***********************************
RAW OUTPUT

{"failed": true, "msg": "error : Unable to create the new dashboard 1860 : 412 - {'url': 'http://mygrafana.test/api/dashboards/db', 'content-length': '96', 'content-type': 'application/json', 'date': 'Thu, 10 Jan 2019 13:22:33 GMT', 'connection': 'close', 'msg': 'HTTP Error 412: Precondition Failed', 'body': b'{\"message\":\"A dashboard with the same name in the folder already exists\",\"status\":\"name-exists\"}', 'status': 412}.", "invocation": {"module_args": {"grafana_url": "http://mygrafana.test", "grafana_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "uid": "1860", "state": "present", "overwrite": true, "path": "/tmp/dashboards/1860.json", "message": "test edit", "url": "http://mygrafana.test", "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "use_proxy": true, "validate_certs": true, "url_username": "admin", "org_id": 1, "client_cert": null, "client_key": null, "grafana_api_key": null, "slug": null, "force_basic_auth": true}}}


***********************************
PARSED OUTPUT
{
    "failed": true,
    "invocation": {
        "module_args": {
            "client_cert": null,
            "client_key": null,
            "force_basic_auth": true,
            "grafana_api_key": null,
            "grafana_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "grafana_url": "http://mygrafana.test",
            "message": "test edit",
            "org_id": 1,
            "overwrite": true,
            "path": "/tmp/dashboards/1860.json",
            "slug": null,
            "state": "present",
            "uid": "1860",
            "url": "http://mygrafana.test",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "admin",
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "error : Unable to create the new dashboard 1860 : 412 - {'url': 'http://mygrafana.test/api/dashboards/db', 'content-length': '96', 'content-type': 'application/json', 'date': 'Thu, 10 Jan 2019 13:22:33 GMT', 'connection': 'close', 'msg': 'HTTP Error 412: Precondition Failed', 'body': b'{\"message\":\"A dashboard with the same name in the folder already exists\",\"status\":\"name-exists\"}', 'status': 412}."
}
```

This PR adds the Ansible module uid to the creation payload if specified and allows updating to find the correct dashboard.

Any previously created dashboard will either have to be recreated to ensure the playbook is followed, or the playbook modified to use the current randomly-generated uid.

Additionally, the comparison made for the updating decision was flawed as it used the complete API response body and didn't sanitize the API dashboard from local metadata, ensuring the comparison would always fail and the dashboard would always be updated, even with similar data.

### CODE REVIEW

**Review by orthanc — COMMENTED** [review]
Not a graphana user so haven't tetsted but have reviewed the code and the change looks good and definatly looks like it would fix the issue mentioned in the PR description.

**Comment by kbreit** [comment]
cc @kbreit

**Comment by winem** [comment]
Did a few tests with grafana and different dashboards. It worked fine and there were no issues or deviations from the expected behaviour.

**Review by seuf — APPROVED** [review]

**Comment by seuf** [comment]
LGTM

**Comment by Sh4d1** [comment]
Any news on this PR being merged?

**Comment by Sh4d1** [comment]
@seuf @orthanc ?

**Comment by seuf** [comment]
I don't have permissions to merge this pull requests..

**Review by jorijinnall — APPROVED** [review]
Code looks good to me

**Comment by jorijinnall** [comment]
shipit

**Comment by rrey** [comment]
bot_status

**Comment by rrey** [comment]
@jqueuniet can you rebase this PR ? We may have the proper permissions now.

**Comment by jqueuniet** [comment]
Thanks for the notice, I'll take a look.

**Comment by jqueuniet** [comment]
It looks like this PR is no longer necessary, @seuf closed the bug with PR #63342

**Pull request closed without merging**
