### PR TITLE
Initial pass at consolidating community content [work in progress]

### PR DESCRIPTION
**Pull request by dharmabumstead**
##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dharmabumstead for this, helps a lot. @gundalow if you can get this merged into devel, I can start hacking away at more PRs in keeping with the spirit of https://github.com/ansible/community/issues/169, and then we can look at backporting at some point.

**Review by gundalow — APPROVED** [review]

**Comment by dharmabumstead** [comment]
Please note that I haven't actually *removed* the existing community content - just started porting it over to the new structure.

**Comment by gregdek** [comment]
Yeah, I'm comfortable hacking away the existing community content and moving to the new structure with incremental commits over the next day or two and then request a big backport of the finished content.

So who pushes the big green button? :)

**Comment by dharmabumstead** [comment]
I went ahead and pushed the big green button. These changes aren't surfaced on the main index yet. Hack away!

**Comment by gregdek** [comment]
w00t! :)

**Pull request merged**
