### PR TITLE
add 'required' to vars_prompt

### PR DESCRIPTION
**Pull request by simobasso**

### CODE REVIEW

**Comment by bcoca** [comment]
I like the idea, thinking that there might be a better name, also you have several spurious whitespace changes on unrelated lines.

**Comment by simobasso** [comment]
Thx @bcoca!

we have two option:
- change name, stop.
- reverse the logic (ex. name: allow_empty, default: yes)

what do you prefer?

**Comment by amenonsen** [comment]
"Avoid empty prompt" is a completely misleading description for this feature. What it does is control whether empty inputs to a prompt are allowed or not. `allow_empty` would be all right, but I would prefer `required` with a default of `False`.

**Comment by simobasso** [comment]
done

**Comment by bcoca** [comment]
an assert/fail task at the top of the play would serve same purpose.

**Review by dharmabumstead — CHANGES_REQUESTED** [review]
Please change to 'You can also prevent an empty prompt by including the 'required' parameter:'

**Comment by dharmabumstead** [comment]
Closing due to inactivity. Please feel free to reopen.

**Pull request closed without merging**
