### PR TITLE
Added support for defining the ServerSelection attribute in win_updates.ps1

### LINKED ISSUE #51188: win_updates: add server selection option to variables
##### SUMMARY
win_updates module is missing an option to supply the ServerSelection option to the update searcher session.  Adding this option would allow the update engine to use non-default update sources if desired.  A great use case is for managed Windows systems where the default update source is locally forced to either WSUS or SCCM repositories and admins want to force a scan against the online Windows Update repository instead.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_updates, specifically within the Microsoft.Update.Session object created as $searcher.

##### ADDITIONAL INFORMATION
Microsoft ServerSelection reference: https://msdn.microsoft.com/en-us/library/ee897380.aspx

The code update may look similar to the block below, presuming an integer variable from Ansible is mapped to $serverselection.  Tested successfully in a local clone/edit of the stock win_updates.ps1 module.

```
        if ($serverselection -in 0..3) {
            Write-DebugLog -msg "Setting Windows Update searcher to use alternate update source (ServerSelection: $serverselection)..."
            try {
                $searcher.ServerSelection = $serverselection
            } catch {
                $result.failed = $true
                $result.msg = "Failed to update Windows Update search source: $($_.Exception.Message)"
                return $result
            }
       }

```

### PR DESCRIPTION
**Pull request by swickera**
##### SUMMARY
Added support for defining the ServerSelection attribute of the update searcher session, which allows specifying non-default update server sources.

Fixes #51188

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
win_updates

##### ADDITIONAL INFORMATION
This is useful if targeted systems have Windows Updates defaulted to WSUS or SCCM sources and we want to instead force searches to the online Windows Update catalog (ServerSelection = 2).  Reference - https://msdn.microsoft.com/en-us/library/ee897380.aspx

The Ansible command output remains identical to the stable release, however if the log_path parameter is also specified, content of the log file will indicate if the optional serverselection parameter was specified and used.  Sample log file output below; the before scenario shows logs from a system using SCCM as a default update source and our WSUS server does not have approved updates as SCCM handles that for us (result is no updates available), this output matches the previous output of the module.  The after output shows the alternate update source being specified and the search against Microsoft's update catalog reveals outstanding updates are available.

Before
```
<...>
2019-01-23 10:22:19Z Starting scheduled job (PS4+ method)
2019-01-23 10:22:20Z Waiting for job completion...
2019-01-23 10:22:22Z Creating Windows Update session...
2019-01-23 10:22:22Z Create Windows Update searcher...
2019-01-23 10:22:22Z Search criteria: (IsInstalled = 0 AND CategoryIds contains 'CD5FFD1E-E932-4E3A-BF74-18BF0B1BBD83') 
2019-01-23 10:22:22Z Searching for updates to install in category Ids CD5FFD1E-E932-4E3A-BF74-18BF0B1BBD83...
2019-01-23 10:22:26Z Found 0 updates
2019-01-23 10:22:26Z Creating update collection...
2019-01-23 10:22:26Z Calculating pre-install reboot requirement...
2019-01-23 10:22:26Z Check mode: exiting...
2019-01-23 10:22:26Z Return value:
{
    "updates":  {

                },
    "found_update_count":  0,
    "changed":  false,
    "reboot_required":  true,
    "installed_update_count":  0,
    "filtered_updates":  {

                         }
}
<...>
```
After
```
<...>
2019-01-23 10:23:07Z Starting scheduled job (PS4+ method)
2019-01-23 10:23:07Z Waiting for job completion...
2019-01-23 10:23:10Z Creating Windows Update session...
2019-01-23 10:23:10Z Create Windows Update searcher...
2019-01-23 10:23:10Z Setting Windows Update searcher to use alternate update source (serverselection: 2)...
2019-01-23 10:23:10Z Search criteria: (IsInstalled = 0 AND CategoryIds contains 'CD5FFD1E-E932-4E3A-BF74-18BF0B1BBD83') 
2019-01-23 10:23:10Z Searching for updates to install in category Ids CD5FFD1E-E932-4E3A-BF74-18BF0B1BBD83...
2019-01-23 10:23:14Z Found 2 updates
2019-01-23 10:23:14Z Creating update collection...
2019-01-23 10:23:14Z Adding update a9116f8a-d10a-4692-bbd3-b8e53ce48827 - 2019-01 Preview of Quality Rollup for .NET Framework 3.5, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2 for Windows 8.1 and Server 2012 R2 for x64 (KB4481490)
2019-01-23 10:23:14Z Adding update 7f796bb7-0a54-4b27-9289-8973797915e0 - 2019-01 Preview of Monthly Quality Rollup for Windows Server 2012 R2 for x64-based Systems (KB4480969)
2019-01-23 10:23:14Z Calculating pre-install reboot requirement...
2019-01-23 10:23:14Z Check mode: exiting...
2019-01-23 10:23:14Z Return value:
{
    "updates":  {
                    "7f796bb7-0a54-4b27-9289-8973797915e0":  {
                                                                 "title":  "2019-01 Preview of Monthly Quality Rollup for Windows Server 2012 R2 for x64-based Systems (KB4480969)",
                                                                 "id":  "7f796bb7-0a54-4b27-9289-8973797915e0",
                                                                 "installed":  false,
                                                                 "kb":  [
                                                                            "4480969"
                                                                        ]
                                                             },
                    "a9116f8a-d10a-4692-bbd3-b8e53ce48827":  {
                                                                 "title":  "2019-01 Preview of Quality Rollup for .NET Framework 3.5, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2 for Windows 8.1 and Server 2012 R2 for x64 (KB4481490)",
                                                                 "id":  "a9116f8a-d10a-4692-bbd3-b8e53ce48827",
                                                                 "installed":  false,
                                                                 "kb":  [
                                                                            "4481490"
                                                                        ]
                                                             }
                },
    "found_update_count":  2,
    "changed":  false,
    "reboot_required":  true,
    "installed_update_count":  0,
    "filtered_updates":  {

                         }
}
<...>
```

### CODE REVIEW

**Comment by swickera** [comment]
Additional reference: https://docs.microsoft.com/en-us/windows/desktop/api/wuapicommon/ne-wuapicommon-tagserverselection

**Comment by jborean93** [comment]
@swickera unfortunately I'm going to have to close this PR as it's targeted towards the stable-2.7 branch. We accept PRs to the devel branch then backport if it's a bugfix. Please let me know if you need help during this process but this should be as simple as creating a new PR to target devel.

**Comment by swickera** [comment]
@jborean93 I'll give it another shot, thanks for the note!

**Comment by swickera** [comment]
https://github.com/ansible/ansible/pull/51305

**Pull request closed without merging**
