### PR TITLE
BOTMETA: Use label network

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Rename label from 'networking' to 'network
  (so auto-labeling works based on directory)
- Simplify entries that only defined maintainers

This requires:
- Renaming the `networking` label to `network`
- Update the badges on the Wiki to use `network`

And cleans up:
- Remove special exceptions in @ansibot triage
- Rename test entries using `networking` and `$team_networking`

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gundalow** [comment]
Needs review by Networking Team
Will also need to update links on wiki, etc

**Review by gundalow — CHANGES_REQUESTED** [review]
On hold as we are fighting some Bot issues at the moment
Needs review by network team

**Comment by ikhan2010** [comment]
@gundalow I don't see any issues, but I will bring this up in our team meeting and confirm with the team to make sure everyone is aware and don't have any concerns.

**Comment by ikhan2010** [comment]
@gundalow we are good with this change.

**Review by gundalow — APPROVED** [review]

**Pull request closed without merging**
