### PR TITLE
Update azure_rm_resource.py

### PR DESCRIPTION
**Pull request by shannawaz**
##### SUMMARY

Examples of usage will help end customer. Added example on how to use  body

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@shannawaz Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by Fred-sun** [comment]
@shannawaz Can you help resolve conflicting files when you have time? Thank you very much!

**Comment by shannawaz** [comment]
Let me know how I can resolve the merge conflict.

**Review by shannawaz — COMMENTED** [review]
Removed extra space

**Comment by Fred-sun** [comment]
@shannawaz Thank you very much for your interest in Ansible. This repo is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure
Please re-submit this PR in the above repository and closed this. Thank you very much!

**Pull request closed without merging**
