### PR TITLE
Add support for tmpfs to docker_container.

### PR DESCRIPTION
**Pull request by wrouesnel**
##### SUMMARY
Adds support for `tmpfs` parameter to the `docker_container` module, allowing tmpfs filesystems to be deployed with docker containers. This makes `read_only` much more usable.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.4.0 (add_tmpfs_support_to_docker_container a24478c38e) last updated 2017/06/15 22:39:45 (GMT +1100)
  config file = None
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible-work/ansible/lib/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]
```
##### ADDITIONAL INFORMATION
Adds support for `tmpfs` similar to the use of volume mounts. The parameter is supplied as a list of strings in the command line format.

Example playbook:
```
docker_container:
  name: testcontainer
  image: ubuntu:xenial
  tmpfs:
  - /test1:suid,exec
  - /test2:suid,exec
  - /test3
  interactive: true
  command: /bin/bash
  state: started
```

### CODE REVIEW

**Comment by wrouesnel** [comment]
@kassiansun Pinging you since you last added a missing feature to the `docker_container` module

**Comment by kassiansun** [comment]
@wrouesnel I will take a look at it as soon as possible.

**Review by kassiansun — APPROVED** [review]
LGTM

**Comment by wrouesnel** [comment]
Ooh, this shouldn't be merged yet - an existing bug in the docker_container module has been exposed by it: see #25974

EDIT: As noted by @kassiansun , this behavior is intentional and consistent with `tmpfs` management for this PR, so this should be good to be merged.

**Comment by chouseknecht** [comment]
@wrouesnel 

This doesn't appear to be idempotent. If I start a container with the following:

```
- name: Start foobar, again
    docker_container:
      state: started
      name: foobar
      image: 'centos:7'
      command: ['sleep', '1d']
      tmpfs:
      - /run:rw,noexec,nosuid,size=65536k
```

I would expect that running the same task a second time would result in no change. Instead, it destroys and recreates the container.

**Review by chouseknecht — APPROVED** [review]

**Comment by JoshuaSeidel** [comment]
@chouseknecht can this please be merged into the 2.4 branch for the next release?

**Pull request merged**
