### PR TITLE
docker_swarm_service: Add read_only option

### PR DESCRIPTION
**Pull request by hannseman**
##### SUMMARY

Add `read_only` option.

https://docs.docker.com/engine/reference/commandline/service_create/#options

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

docker_swarm_service

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
ah wait.

**Comment by felixfontein** [comment]
Just saw something :) `read_only` needs a `version_added: 2.8`.

**Comment by hannseman** [comment]
Always miss that one! Don't get that error when running the sanity-checks locally with `test/runner/ansible-test sanity --python=2.7 docker_swarm_service`.

**Comment by felixfontein** [comment]
Yep, that part of the sanity checks doesn't seem to work locally...

BTW, have you seen the test failures?
 - https://app.shippable.com/github/ansible/ansible/runs/112514/43/tests
 - https://app.shippable.com/github/ansible/ansible/runs/112514/44/tests

**Review by felixfontein — APPROVED** [review]
shipit

**Comment by jwitko** [comment]
needs_rebase

**Comment by gundalow** [comment]
rebuild_merge

Thanks all!

**Comment by felixfontein** [comment]
Also thanks from me! :)

**Pull request merged**
