### PR TITLE
Adding ovirt_event_facts Module (#51760)

### PR DESCRIPTION
**Pull request by nasx**
##### SUMMARY

Submitting module ovirt_event_facts to list events in oVirt/RHV (original request is #51760)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

ovirt_event_facts

##### ADDITIONAL INFORMATION
This PR was split from #51761.

### CODE REVIEW

**Comment by machacekondra** [comment]
shipit

**Review by mwperina — APPROVED** [review]
shipit

**Comment by machacekondra** [comment]
bot_status

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
@Akasurde @gundalow Can you please merge?

**Review by machacekondra — COMMENTED** [review]
Can you please update this module with same comments as in https://github.com/ansible/ansible/pull/52982/files ?

**Comment by nasx** [comment]
> Can you please update this module with same comments as in https://github.com/ansible/ansible/pull/52982/files ?

@machacekondra done.

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
@mwperina Please review.

**Comment by machacekondra** [comment]
@Akasurde @gundalow Can you please merge?

**Comment by mwperina** [comment]
shipit

**Comment by machacekondra** [comment]
@Akasurde @gundalow Can you please merge?

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
bot_status

**Comment by mwperina** [comment]
Abhijeet/John could you please merge?

@Akasurde @gundalow

**Comment by gundalow** [comment]
Thanks everybody, merged into `devel` for release in Ansible 2.8

FYI I review label/shipit ~ weekly, so as long as the label gets added, like it did https://github.com/ansible/ansible/pull/52984#event-2173716763 we should all be good

**Pull request merged**
