### PR TITLE
botmeta: cloudstack: new team member

### PR DESCRIPTION
**Pull request by resmo**
##### SUMMARY
join me to welcome @rhtyd to the cloudstack team!

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

botmeta

##### ANSIBLE VERSION

```paste below
2.8
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by yadvr** [comment]
Thanks @resmo is there a quick guide on how ansible community/contribution works? Or, is it that somebody will contact one of the maintainers in case of any bugs, features etc.?

**Comment by Akasurde** [comment]
@rhtyd Please go through this doc - https://docs.ansible.com/ansible/latest/community/maintainers.html. Thanks and welcome.

**Comment by yadvr** [comment]
Thanks @Akasurde

**Comment by acozine** [comment]
Thanks @rhtyd for stepping up as a maintainer!

**Comment by dpassante** [comment]
Welcome @rhtyd !

**Pull request merged**
