### PR TITLE
[2.8] Fix nagios module to recognize if file exists and is fifo pipe

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #58569 to stable-2.8. Fixes bug in nagios module.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
nagios

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @Klaas-

**Review by Klaas- — APPROVED** [review]
I tested it on ansible 2.8 on fedora 30

**Comment by abadger** [comment]
Merged for the 2.8.3 release.

**Comment by felixfontein** [comment]
@Klaas- thanks again for fixing this!
@abadger thanks for merging!

**Pull request merged**
