### PR TITLE
Hetzner dedicated server firewall info module

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The _info counterpart to #65399.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
hetzner_firewall_info

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @resmo @LKaemmerling

**Review by resmo — APPROVED** [review]
shipit

**Comment by Shaps** [comment]
shipit

**Comment by felixfontein** [comment]
@resmo @Shaps thanks a lot for reviewing! @amenonsen thanks a lot for merging!

**Pull request merged**
