### PR TITLE
Add launch type to ecs task

### PR DESCRIPTION
**Pull request by ezmac**
##### SUMMARY

Adds launch_type support to ecs_task

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ecs_task

##### ADDITIONAL INFORMATION
Requires a little more permission in the ecs trust policy.

### CODE REVIEW

**Comment by ezmac** [comment]
ready_for_review

**Comment by willthames** [comment]
This looks good to me - I'll run the test suite over it later and get this merged if all goes well.

**Comment by willthames** [comment]
I've added a trivial patch to this to allow ecs:StopTask and ecs:StartTask

rebuild_merge

**Comment by willthames** [comment]
bot_status

**Comment by willthames** [comment]
force push was just to remove an unnecessary commit I made adding a secondary changelog fragment that was already there.

**Pull request merged**
