### PR TITLE
now nolog can be set in ansible.cfg and play levels also

### PR DESCRIPTION
**Pull request by bcoca**
just expanding on existing functionality.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Probably should be no_log in the config file too, to match.

Also when new config options are added we need to add a section to intro_configuration.rst with a "version_added" note.

**Comment by mpdehaan** [comment]
Looking at code I thought we did most of this, we will need to check.

**Comment by kustodian** [comment]
It would be great if this pull request makes it into 1.6.

**Comment by bcoca** [comment]
would be great if it made it into 1.7 or do i need to bump again?

**Comment by mpdehaan** [comment]
In queue.  large queue.  Another popular suggestion is to make no_log disable callback output of data items, which I need to research if we did that already or not :)

**Comment by mpdehaan** [comment]
also looks like this may be due for a rebase, sneaky branches

**Comment by bcoca** [comment]
rebased and squashed and rebased

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

The above change was made by us via a different commit, so we are going to close this issue. Since our version did not add the no_log option to the ansible.cfg, feel free to resubmit that portion as a new PR.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request closed without merging**
