### PR TITLE
changed 'vars_prompt' syntax to support prompt text and (non-)private in...

### PR DESCRIPTION
**Pull request by Ernest0x**
...put setting

An example of the new syntax:

<pre>vars_prompt:
 - name: 'secret_variable_name"
   prompt: "Enter secret value: "
   private: "yes"
 - name: "nonsecret_variable_name"
   prompt: "Enter non-secret value: "
   private: "no"</pre>

### CODE REVIEW

**Comment by mpdehaan** [comment]
A few things:

(A) in playbooks, using the boolean True is generally something that should be accepted.   Not so in module parameters, but it works that way for sudo already.   It is probably true that it should also be nice and try to accept 'yes', but that's another story.   

(B) mgw had a previous patch set (approximately around release 0.3) that would add encryption support, which was highly useful.   If we addd this, we should put that back in at this time as well.   Here is the pull request about that:  https://github.com/ansible/ansible/pull/359 .  Things have changed a lot around sense then, but the main idea is being able to support optional password encryption.

(C) in data access, use "foo.get('keyname', default)" versus "pop", as we don't actually want to remove those values.

(D) the following check seems to only check the first letter:

  if not ((vname[0].isalpha() or vname[0] == '_') and vname.replace('_','').isalnum()):

And should probably display which of the variables was invalid

(E)  We shouldn't break backwards compatibility, such that if vars_prompt is listed as a list of simple strings, it should continue to work the same way it previously worked.    Treat that as the name if that happens.

**Comment by mpdehaan** [comment]
feel free to ask questions on this pull request, I'm going to close it and let you resubmit it.

(F) example playbooks using vars_prompt should probably be updated to show an example of this (examples/playbooks, grep for vars_prompt)

thanks!

**Comment by Ernest0x** [comment]
Take a look at: https://github.com/Ernest0x/ansible/commit/a9bea4e06d5c635655a15d17c47172a97a9ad402

I have addressed all your points, except (B) for which I am not sure about what has to be done.
The check on (D) seems ok to me (and works ok too on some tests I have done). The first operand of 'and' checks for first letter and the second checks that all characters are alphanumeric or underscores.

If you think that it is ok to resubmit for a pull request, let me know.

**Comment by mpdehaan** [comment]
Looks pretty good, I'd like to trim up the error messaging a bit and test some so this in queue to merge a bit later.

Thanks!

**Comment by Ernest0x** [comment]
Nice.
I have created a new branch with just the related changes as you suggested on IRC. So I' m closing this pull request, and submitting a request for the new branch.

**Pull request closed without merging**
