### PR TITLE
Clarify description of 'state' in the package module

### PR DESCRIPTION
**Pull request by ndokos**
##### SUMMARY
Change `i.e`  (id est = that is) to `e.g.` (exempli gratia = for example).

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bcoca** [comment]
i wrote it to mean 'in other words', so not sure the change is correct

**Comment by ndokos** [comment]
Do you mean that `latest` is the *only* other possibility? If so, `i.e.` is correct but the sentence is somewhat misleading, since it mentions `otherr states`: an explicit disclaimer that it is the only other possibility would be clearer.

**Comment by acozine** [comment]
Would changing this to:
`Other states (for example, C(latest)) depend on the underlying package module.`
clarify the meaning?

**Comment by bcoca** [comment]
'latest' is really only other 'common state' all others are module specific and will break with package unless that module is used exclusively

**Review by bcoca — APPROVED** [review]

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @ndokos for working through the wording here.

**Pull request merged**
