### PR TITLE
aci_epg: Add support for Preferred Group Membership

### LINKED ISSUE #34896: aci_epg module needs to support PreferredGroup
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
aci_epg

##### ANSIBLE VERSION
```
[root@ansible-server ~]# ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
[root@ansible-server ~]#
```

##### CONFIGURATION

[root@ansible-server ~]# ansible-config dump --only-changed
[root@ansible-server ~]#

##### OS / ENVIRONMENT
Ansible server on CentOS 7.3 and ACI version 3.0 or 3.1

##### SUMMARY

Since ACI 2.3 it is possible to configure EPGs to be part of a Preferred Group. This is a new attribute of the fvAEPg object. EPGs that are part of the Preferred Group can communicate without contracts. This is very convenient for migration scenarios as well as customers that implement ACI for network automation but not for policy.

##### EXPECTED RESULTS

The module should have a new option to configure.

preferred_group: yes, no

The object to configure is:

fvAEPg.attributes.prefGrMemb and the option is "include" or "exclude".

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Add support for Preferred Group Membership

This fixes #34896 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
aci_epg

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by dagwieers** [comment]
@jmcgill298 I implemented this as a boolean as was requested, but am wondering whether it's not safer to map it directly to the values ACI is using. At least if somehow a third option is introduced in the future, we don't get into troubles...

**Comment by nilloBE** [comment]
I will test this asap.

I do not have strong feelings about boolean or using ACI values. At the moment it is include/exclude, which is a binary decision. At the moment there are no plans to change this in upcoming committed releases.

**Comment by spidernik84** [comment]
Tested to be working with ACI 3.0 (2k)

**Comment by dagwieers** [comment]
Another concern, how will this play out on older ACI versions (v2.2 and older) ?

Since this parameter is optional, there is no problem, but using it will probably result in errors.
And since we don't know the ACI version (otherwise another round-trip is needed) we can't be smart about it.

Theoretically we already have this problem with other modules as we don't control feature-compatibility in any of our modules. So we have to be careful and in testing we should be testing all functionality against every (supported) ACI version. Not impossible, but a huge undertaking.

**Comment by spidernik84** [comment]
Good point. I have no ACI 2.0 at hand, unfortunately, for testing.
Would it be an anti-pattern to specify the ACI version in some var, and assume a default?

**Comment by dagwieers** [comment]
Well, there's a tendency to add gather_facts support to network equipment, but that's a means to get (useful) information into the hands of people writing playbooks to make decisions within playbooks. It's hardly an option to then ask playbook-writers to feed that information back into modules to ensure proper functioning.

So the only option we have to make this work smoothly is to make every module (that needs this) do an additional call to ACI to request the version. Unfortunately, we first have to get an overview of recently added functionality (e.g. starting from v2.0 ?) so we can look at what modules are impacted.

And then we should probably start documenting what functionality comes with what version (by adding notes to the parameters in the documentation). That would be the first step.

**Comment by nilloBE** [comment]
Thanks @spidernik84 for testing and thanks @dagwieers for the comments. That reminds me I have to look into the APIC HW for automated testing. That will also help to test with multiple modules. For now, indeed documentation is the only thing that we can control. Preferred Group was added in 2.3 "officially".

**Comment by dagwieers** [comment]
Now that "officially" worries me ;-)

**Comment by dagwieers** [comment]
So I am going to merge this as a boolean. We always have the option to change the interface and allow a third option and keep backward compatibility for Ansible booleans. So we shouldn't be too worried.

Thanks everyone !

**Pull request merged**
