### PR TITLE
Add tojson filter to jinja environment used by the template module.

### PR DESCRIPTION
**Pull request by tima**
A couple of weeks ago I wrote to the mailing list looking for a way to generate a report about the hosts using Ansible. With the introduction of the delegate_to and this one-line change the the jinja environment I figured out a way to do this by looking at Flask.

```
- name: facts dumper
  hosts: nodes
  tasks:
    name: dump facts
    action: template src=/path/to/hostvars.j2 dest=/path/to/dump/facts/$inventory_hostname
    delegate_to: localhost
```

/path/to/hostvars.j2 would contain:

```
{{ hostvars[inventory_hostname]|tojson|safe }}
```

This passes the hostvars struct to a filter that is just an alias to json.dumps and write that to the dest. 

Thinking about it now I suppose this would have made something work by creating two plays -- one that runs on all nodes and another locally that does a json dump of hostvars. I'd have one big file as opposed to one for each host.

While this is a pretty specific use case, I could see having json encoding support within ansible templates something that could come in handy.

### CODE REVIEW

**Comment by mpdehaan** [comment]
yeah, there are probably other useful filters/modules to expose as well.  Not sure what all those might be.

merged, thanks!

**Comment by mpdehaan** [comment]
Just noticed this, but this really should be "to_json" to be consistent with the rest of the API.   Mind changing it?

**Comment by tima** [comment]
Sorry. Busy day. 

I'll change it. I just ran with what Flask did and didn't consider Ansible's standard.

**Comment by mpdehaan** [comment]
Yeah, I'm probably being super picky, but it's easier when I don't have to guess underscores from method to method.

Thanks!

**Pull request merged**
