### PR TITLE
fixes bug on user expiration always changing

### LINKED ISSUE #13235: User module - `expires` option always fires changed
##### Issue Type:

Bug Report

##### Component Name:
user

##### Ansible Version:

1.9.4
##### Ansible Configuration:

N/A, no significant changes.
##### Environment:

CentOS 7
##### Summary:

The `user` module will always fire 'changed' when the `expires` option is set. 
##### Steps To Reproduce:

Use the `expires` option when creating a user. 
##### Expected Results:

Run the playbook for the first time. The user is created with an expiration date, and 'changed' is fired. 

Run the playbook a second time. Nothing has changed, and 'changed' is not fired. 
##### Actual Results:

Run the playbook for the first time. The user is created with an expiration date, and 'changed' is fired. 

Run the playbook a second time. Nothing has changed, and 'changed' is fired.

### PR DESCRIPTION
**Pull request by StefanKaerst**
##### SUMMARY

expiry time of user account will now be changed only if its different

fixes #13235

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

user module
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/mnt/ramdisk/ansible/lib/ansible/modules/']
  python version = 2.7.13 (default, Mar 22 2017, 12:31:17) [GCC]
```

##### ADDITIONAL INFORMATION

add expires parameter to user module and run it twice. it always changes the expiry time of user(s) because the expiry time of existing users will not be taken into account. I changed ansible user module to read an existing expiry time and save it as time object (in full days)

```
knoedel@section61:/mnt/ramdisk> cd ansible; git checkout devel; cd -
Already on 'devel'
Your branch is up-to-date with 'origin/devel'.
/mnt/ramdisk
knoedel@section61:/mnt/ramdisk> sudo ansible/hacking/test-module --check -m ansible/lib/ansible/modules/system/user.py -a "name=ansible expires=864000"
* including generated source, if any, saving to: /root/.ansible_module_generated
* ansiballz module detected; extracted module source to: /root/debug_dir
***********************************
RAW OUTPUT

{"comment": "tralala", "shell": "/bin/bash", "group": 100, "name": "ansible", "changed": true, "state": "present", "invocation": {"module_args": {"comment": null, "ssh_key_bits": 0, "update_password": "always", "non_unique": false, "force": false, "skeleton": null, "ssh_key_passphrase": null, "createhome": true, "uid": null, "home": null, "append": false, "ssh_key_type": "rsa", "ssh_key_comment": "ansible-generated on section61", "group": null, "system": false, "state": "present", "shell": null, "expires": 864000.0, "ssh_key_file": null, "groups": null, "move_home": false, "password": null, "name": "ansible", "seuser": null, "remove": false, "login_class": null, "generate_ssh_key": null}}, "home": "/home/ansible", "move_home": false, "append": false, "uid": 1003}


***********************************
PARSED OUTPUT
{
    "append": false, 
    "changed": true, 
    "comment": "tralala", 
    "group": 100, 
    "home": "/home/ansible", 
    "invocation": {
        "module_args": {
            "append": false, 
            "comment": null, 
            "createhome": true, 
            "expires": 864000.0, 
            "force": false, 
            "generate_ssh_key": null, 
            "group": null, 
            "groups": null, 
            "home": null, 
            "login_class": null, 
            "move_home": false, 
            "name": "ansible", 
            "non_unique": false, 
            "password": null, 
            "remove": false, 
            "seuser": null, 
            "shell": null, 
            "skeleton": null, 
            "ssh_key_bits": 0, 
            "ssh_key_comment": "ansible-generated on section61", 
            "ssh_key_file": null, 
            "ssh_key_passphrase": null, 
            "ssh_key_type": "rsa", 
            "state": "present", 
            "system": false, 
            "uid": null, 
            "update_password": "always"
        }
    }, 
    "move_home": false, 
    "name": "ansible", 
    "shell": "/bin/bash", 
    "state": "present", 
    "uid": 1003
}
knoedel@section61:/mnt/ramdisk> sudo ansible/hacking/test-module --check -m ansible/lib/ansible/modules/system/user.py -a "name=ansible expires=864000"
* including generated source, if any, saving to: /root/.ansible_module_generated
* ansiballz module detected; extracted module source to: /root/debug_dir
***********************************
RAW OUTPUT

{"comment": "tralala", "shell": "/bin/bash", "group": 100, "name": "ansible", "changed": true, "state": "present", "invocation": {"module_args": {"comment": null, "ssh_key_bits": 0, "update_password": "always", "non_unique": false, "force": false, "skeleton": null, "ssh_key_passphrase": null, "createhome": true, "uid": null, "home": null, "append": false, "ssh_key_type": "rsa", "ssh_key_comment": "ansible-generated on section61", "group": null, "system": false, "state": "present", "shell": null, "expires": 864000.0, "ssh_key_file": null, "groups": null, "move_home": false, "password": null, "name": "ansible", "seuser": null, "remove": false, "login_class": null, "generate_ssh_key": null}}, "home": "/home/ansible", "move_home": false, "append": false, "uid": 1003}


***********************************
PARSED OUTPUT
{
    "append": false, 
    "changed": true, 
    "comment": "tralala", 
    "group": 100, 
    "home": "/home/ansible", 
    "invocation": {
        "module_args": {
            "append": false, 
            "comment": null, 
            "createhome": true, 
            "expires": 864000.0, 
            "force": false, 
            "generate_ssh_key": null, 
            "group": null, 
            "groups": null, 
            "home": null, 
            "login_class": null, 
            "move_home": false, 
            "name": "ansible", 
            "non_unique": false, 
            "password": null, 
            "remove": false, 
            "seuser": null, 
            "shell": null, 
            "skeleton": null, 
            "ssh_key_bits": 0, 
            "ssh_key_comment": "ansible-generated on section61", 
            "ssh_key_file": null, 
            "ssh_key_passphrase": null, 
            "ssh_key_type": "rsa", 
            "state": "present", 
            "system": false, 
            "uid": null, 
            "update_password": "always"
        }
    }, 
    "move_home": false, 
    "name": "ansible", 
    "shell": "/bin/bash", 
    "state": "present", 
    "uid": 1003
}


knoedel@section61:/mnt/ramdisk> sudo chage -l ansible
Last password change                                    : Jun 02, 2017
Password expires                                        : never
Password inactive                                       : never
Account expires                                         : Jan 11, 1970
Minimum number of days between password change          : 0
Maximum number of days between password change          : 99999
Number of days of warning before password expires       : 7

knoedel@section61:/mnt/ramdisk> cd ansible; git checkout issue_13235; cd -
Switched to branch 'issue_13235'
Your branch is up-to-date with 'origin/issue_13235'.
/mnt/ramdisk
knoedel@section61:/mnt/ramdisk> sudo ansible/hacking/test-module --check -m ansible/lib/ansible/modules/system/user.py -a "name=ansible expires=864000"
* including generated source, if any, saving to: /root/.ansible_module_generated
* ansiballz module detected; extracted module source to: /root/debug_dir
***********************************
RAW OUTPUT

{"comment": "tralala", "shell": "/bin/bash", "group": 100, "name": "ansible", "changed": false, "state": "present", "invocation": {"module_args": {"comment": null, "ssh_key_bits": 0, "update_password": "always", "non_unique": false, "force": false, "skeleton": null, "ssh_key_passphrase": null, "createhome": true, "uid": null, "home": null, "append": false, "ssh_key_type": "rsa", "ssh_key_comment": "ansible-generated on section61", "group": null, "system": false, "state": "present", "shell": null, "expires": 864000.0, "ssh_key_file": null, "groups": null, "move_home": false, "password": null, "name": "ansible", "seuser": null, "remove": false, "login_class": null, "generate_ssh_key": null}}, "home": "/home/ansible", "move_home": false, "append": false, "uid": 1003}


***********************************
PARSED OUTPUT
{
    "append": false, 
    "changed": false, 
    "comment": "tralala", 
    "group": 100, 
    "home": "/home/ansible", 
    "invocation": {
        "module_args": {
            "append": false, 
            "comment": null, 
            "createhome": true, 
            "expires": 864000.0, 
            "force": false, 
            "generate_ssh_key": null, 
            "group": null, 
            "groups": null, 
            "home": null, 
            "login_class": null, 
            "move_home": false, 
            "name": "ansible", 
            "non_unique": false, 
            "password": null, 
            "remove": false, 
            "seuser": null, 
            "shell": null, 
            "skeleton": null, 
            "ssh_key_bits": 0, 
            "ssh_key_comment": "ansible-generated on section61", 
            "ssh_key_file": null, 
            "ssh_key_passphrase": null, 
            "ssh_key_type": "rsa", 
            "state": "present", 
            "system": false, 
            "uid": null, 
            "update_password": "always"
        }
    }, 
    "move_home": false, 
    "name": "ansible", 
    "shell": "/bin/bash", 
    "state": "present", 
    "uid": 1003
}

```

### CODE REVIEW

**Comment by StefanKaerst** [comment]
bot_status

**Comment by ghost** [comment]
bot_status

**Comment by Akasurde** [comment]
@StefanKaerst Could you please rebase this branch ? 

needs_info

**Comment by ghost** [comment]
I'll work on this asap, sry!

**Comment by willthames** [comment]
I've rebased this as it was showing up as a change against almost every file in ansible.

There were a few merge conflicts, which I fixed along the way - hopefully this still works as it did before.

**Comment by samdoran** [comment]
Closing as this was resolved in #38885.

**Pull request closed without merging**
