### PR TITLE
Update windows_faq.rst

### PR DESCRIPTION
**Pull request by IvhaniMaselesele**
##### SUMMARY
Add Ansible to path
Update path
Check version

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by nitzmahone** [comment]
Bigger picture- since WSL now includes numerous distros, and there's nothing WSL-specific about the installations anyway, we should probably just put a link to the https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html page and call it a day. 

cc @acozine

**Comment by IvhaniMaselesele** [comment]
@nitzmahone fair enough.

Just one thing to note, the WSL docs use pip to install and specifically does this for the current user. I suppose there was a reason for this.

Will this not be a problem when using the instructions distro specific instructions?

**Comment by Akasurde** [comment]
@IvhaniMaselesele Are you still working on this? Thanks,

needs_info

**Comment by IvhaniMaselesele** [comment]
Nope, i'll close the PR.

**Comment by Akasurde** [comment]
@IvhaniMaselesele Thanks for the contribution.

**Pull request closed without merging**
