### PR TITLE
Do not install/update the zip package in the unarchive integration test. Issue #28476

### PR DESCRIPTION
**Pull request by pcahyna**
This test is non-destructive, so it is not supposed to do that. See #28476
##### ISSUE TYPE
 - Bugfix Pull Request

### CODE REVIEW

**Comment by dagwieers** [comment]
Well, we have to install the software otherwise we cannot test the module. It's quite simple. And that's why Shippable now fails for you.

@mattclay Please advise.

**Comment by mattclay** [comment]
@pcahyna The test must install zip in order to work. Instead of eliminating the installation of zip, the test can be marked destructive.

Do this by adding the `destructive` alias to `test/integration/targets/unarchive/aliases`.

**Comment by pcahyna** [comment]
How do the hg and svn test work? They don't seem to install hg or svn and the testing documentation says that "The tests will assume things like hg, svn, and git are installed and in path." This matches my experience: without hg or svn installed they fail. Why can't the unarchive test be treated similarly?

**Comment by dagwieers** [comment]
@pcahyna Are you saying that we shouldn't be testing anything in Shippable ? Because I really don't understand where this is going.

I bet one of the things that matter is that **unarchive** is a core module, whereas **hg** is a community modules. **git** is a core module too, but git is basically a given in our test framework :-) **subversion** is a core module too apparently.

**Comment by mattclay** [comment]
All of our integration tests are moving towards installing their own dependencies instead of expecting them to be already present in the test environment, but we haven't updated all of our tests yet. The fact that many dependencies are pre-installed in the docker containers we use for integration tests should be considered an optimization.

After thinking about this more, I not sure that simply installing a dependency is enough to consider the test destructive. If we do we're going to end up with many more of our existing tests being marked destructive due to the requirement that they install their own dependencies, making the distinction less useful.

One thing we could change on this test is to use `present` instead of `latest`. I don't think it's necessary that the test use the latest version of the `zip` package on a given platform.

I would certainly consider uninstalling a package destructive behavior, but that's not something we're doing for this test currently.

**Comment by nrwahl2** [comment]
At this point it sounds like a documentation issue. According to the user:

```
The documentation for the integration tests (test/integration/README.md) says:

    Non-destructive Tests

    These tests will modify files in subdirectories, but will not do things that install or remove package
    s or things
    outside of those test subdirectories.

    Destructive Tests

    These tests are allowed to install and remove some trivial packages.
```

Unfortunately I can't even find the README.md at that path...

**Comment by mattclay** [comment]
That documentation has moved to: `docs/docsite/rst/dev_guide/testing_integration.rst`

I'll add discussion of what qualifies as destructive to the agenda for the Testing Working Group.

**Comment by bcoca** [comment]
would this be solved with a cleanup task for requiresments? with `state=absent` IF  `state=present` resulted in `changed=True`

**Comment by bcoca** [comment]
or we can just 'skip' tests with unmet requirements when 'non-destructive'

**Comment by gundalow** [comment]
@nrwahl2 Where did you see the reference to `test/integration/README.md`?

**Comment by nrwahl2** [comment]
The user's issue report

**Comment by pcahyna** [comment]
@nrwahl2 yes, because I was using Ansible 2.3 where the file exists. See https://github.com/ansible/ansible/pull/28520#issuecomment-324213748 for up to date location.

**Comment by pcahyna** [comment]
Let me explain why I like the current definition of non-destructive. I want to use those tests to test a distribution package. This includes checking whether the provided dependencies are sufficient (and catch bugs like https://bugzilla.redhat.com/show_bug.cgi?id=1465586). If the tests install packages in the middle of execution, they lose their usefulness for that.

**Comment by pcahyna** [comment]
@dagwieers 
> Are you saying that we shouldn't be testing anything in Shippable ?

No. I am saying that if the hg and svn tests do not need to install packages, the unarchive test could work the same way. (There is the question whether one should change the hg and svn tests to behave like the unarchive one rather than vice-versa, of course.)

**Comment by mattclay** [comment]
@pcahyna Thanks for bringing this to our attention. https://github.com/ansible/ansible/pull/28893 updates many of the tests which are destructive to now indicate that. I'm sure I missed some, so I'm planning on adding an automated sanity test in the future to check for obviously destructive tests.

We're also planning on changing the default at some point to be destructive, requiring tests to be marked non_destructive instead.

**Pull request closed without merging**
