### PR TITLE
Update ce_stp to fix bugs

### PR DESCRIPTION
**Pull request by yanzhangi**
##### SUMMARY

Modify the configured query statement and replace get_config with exec_command

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

ansible/lib/ansible/modules/network/cloudengine/ce_stp.py

```paste below

```

### CODE REVIEW

**Review by yuandongx — APPROVED** [review]
+1

**Comment by hwDCN** [comment]
+1

**Comment by hwDCN** [comment]
bot_status

**Comment by xuxiaowei0512** [comment]
bot_status

**Comment by hwDCN** [comment]
bot_status

**Comment by hwDCN** [comment]
bot_status

**Pull request merged**
