### PR TITLE
Idempotency for net_get/net_put modules

### PR DESCRIPTION
**Pull request by gdpak**
- cherry-pick #42307 from devel to 2.6

##### SUMMARY
1) Make modules net_get and net_put idempotent. Contents of remote file are compared with new file being put or get. As network os do not support remote hash checking, file need to fetched locally for hash comparisons. If contents are same, changed=0 is returned.
2) It was discussed to rename arg 'mode' value 'template' as 'text' as it sounds more generic

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

net_get
net_put

##### ANSIBLE VERSION

```
2.6
```

### CODE REVIEW

**Comment by gdpak** [comment]
Integration test
ansible-test  network-integration --inventory /tmp/inventory_deepak ios_file -vvv
TASK [ios_file : debug] **********************************************************************************************************************************************************************
task path: /macos/ansible/test/integration/targets/ios_file/tests/cli/net_put.yaml:77
ok: [csr01] => {
    "msg": "END ios cli/net_put.yaml on connection=network_cli"
}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************
csr01                      : ok=28   changed=7    unreachable=0    failed=0

**Review by Qalthos — CHANGES_REQUESTED** [review]
This introduces Python 3 issues with text handling. I have a PR to fix this in devel

**Comment by gdpak** [comment]
@Qalthos cherry-picked your fix from devel. Sanity-tested with python 3 also after merging -

vagrant@ubuntu-xenial:/macos/ansible$ ansible-test  network-integration --inventory /tmp/inventory_deepak ios_file -vvv
Run command: /usr/bin/python -V
<snip>
ansible-playbook 2.6.1.post0 (backport/2.6/42307 523caae8d6) last updated 2018/07/12 06:59:55 (GMT +000)
  config file = /macos/ansible/test/integration/network-integration.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /macos/ansible/lib/ansible
  executable location = /macos/ansible/bin/ansible-playbook
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
<>
PLAY RECAP ********************************************************************************************************************************
csr01                      : ok=28   changed=7    unreachable=0    failed=0

**Review by Qalthos — APPROVED** [review]

**Comment by mattclay** [comment]
@gdpak What commits from devel are backported by this PR? The changes in this PR don't completely line up with those in https://github.com/ansible/ansible/pull/42307.

**Comment by gdpak** [comment]
@mattclay It also has #42622 as came up during code review.

**Comment by mattclay** [comment]
@gdpak That doesn't appear to include all of the changes. For example, where did this come from?

https://github.com/ansible/ansible/pull/42401/files#diff-fe0d84bd245af0d6314fc59c3e9466bcR46

**Comment by gdpak** [comment]
@mattclay ah..I got the confusion . It had diffs from #41476 as it was precursor for #42307.

**Comment by mattclay** [comment]
This backport appears to include new features, as it adds the `mode` parameter. Only bug fixes should be backported to stable branches.

**Comment by mattclay** [comment]
Closing this backport since it contains both a bug fix (making the module idempotent) and a new feature (templating and the new `mode` module parameter). The fix for making the module idempotent is OK to backport in a new PR.

**Pull request closed without merging**
