### PR TITLE
Fix LXC and KVM creation for Proxmox 6.0 

### LINKED ISSUE #59340: proxmox_kvm not working with proxmox 6.0
##### SUMMARY
proxmox_kvm fails on proxmox 6.0 with the following error:
"authorization on proxmox cluster failed with exception: invalid literal for float(): 6.0-4"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxmox_kvm

##### ANSIBLE VERSION
```paste below
ansible 2.8.2
  config file = /mnt/e/git/Ansible/playbooks/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.5/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING(/mnt/e/git/Ansible/playbooks/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/mnt/e/git/Ansible/playbooks/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_BECOME(/mnt/e/git/Ansible/playbooks/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/mnt/e/git/Ansible/playbooks/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/mnt/e/git/Ansible/playbooks/ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/mnt/e/git/Ansible/playbooks/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/mnt/e/git/Ansible/playbooks/ansible.cfg) = ['/mnt/e/git/Ansible/hosts.ini']
DEFAULT_MANAGED_STR(/mnt/e/git/Ansible/playbooks/ansible.cfg) = Ansible managed - DO NOT EDIT MANUALLY! Changes will be overwritten.
DEFAULT_ROLES_PATH(/mnt/e/git/Ansible/playbooks/ansible.cfg) = ['/mnt/e/git/Ansible/roles/internal', '/mnt/e/git/Ansible/roles/external']
DEFAULT_SCP_IF_SSH(/mnt/e/git/Ansible/playbooks/ansible.cfg) = True
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /root/vault.pass
HOST_KEY_CHECKING(/mnt/e/git/Ansible/playbooks/ansible.cfg) = False
RETRY_FILES_ENABLED(/mnt/e/git/Ansible/playbooks/ansible.cfg) = False
```
##### EXPECTED RESULTS
proxmox_kvm should be able to authenticate

##### ACTUAL RESULTS
proxmox_kvm can't authenticate

### PR DESCRIPTION
**Pull request by zorgzerg**
##### SUMMARY
With version 6 of proxmox, the proxmox.version.get()['version'] return something like 6.0-4 instead of something like 5.0. The cast as a float is not possible anymore, but the variable PVE_MAJOR_VERSION should only contain the first number of the version string. So I split the line with the "-" separator and get first part. 

Fixes #59340

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

proxmox.py
proxmox_kvm.py

### CODE REVIEW

**Review by UnderGreen — APPROVED** [review]

**Comment by UnderGreen** [comment]
:shipit:

**Comment by jocelynj** [comment]
I've applied this fix locally, and I confirm that it makes it possible to create LXC containers with Promox 6

**Review by limakzi — APPROVED** [review]

**Comment by limakzi** [comment]
@jocelynj In my opinion, #59356 has better variable type mapping.
What do you think?

**Comment by jocelynj** [comment]
@limakzi: you're right about the change in file proxmox_kvm.py. Setting `PVE_MAJOR_VERSION` from the first part of `proxmox.version.get()` looks better.

But we also need the changes from this pull-request to fix file proxmox.py.

I'm wondering if the best way to continue would be to remove the changes on proxmox_kvm.py from this PR, and merge #59356 for this file instead. @zorgzerg: Can you modify this PR?

**Comment by zorgzerg** [comment]
@jocelynj
Sure. It's done

**Comment by jocelynj** [comment]
@zorgzerg: the new branch seems wrong :(

What I expect is a single commit with only the changes in proxmox.py file. Here, we have 5 different commits. If you need help, I can open a new pull-request with this single commit.

**Comment by zorgzerg** [comment]
@jocelynj

So good?

**Comment by jocelynj** [comment]
@zorgzerg: yes, it is better, thanks. You could even "merge" the two commits together so that git history is clearer.

**Comment by zorgzerg** [comment]
@jocelynj I created new PR with one commit
https://github.com/ansible/ansible/pull/61358

**Pull request closed without merging**
