### PR TITLE
Introduces a gce_route module

### PR DESCRIPTION
**Pull request by nkakouros**
##### SUMMARY
Introduces a new module for Google Cloud Engine, gce_route that creates, deletes and 'updates' routes

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
gce_route

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nikos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]
```

##### ADDITIONAL INFORMATION
In this module, I have emulated updating routes by deleting existing ones and creating new ones. Updating is not natively supported by Google Cloud. 

I have been using the module for around a month without any issues.

### CODE REVIEW

**Comment by erjohnso** [comment]
Thanks for this @tterranigma (and all the other contributions you're working on!).  I *really* hate to suggest this, but before we go too much further with libcloud, I'd like us to consider using `google-api-python-client` instead (see that last [comment](https://github.com/ansible/ansible/pull/27194#issuecomment-320120693) I made on your other work).

Would you be open to pulling out libcloud on this?

**Comment by nkakouros** [comment]
I will try to have a look at `google-api-python-client` when I manage some time off.

**Comment by nkakouros** [comment]
So, this is a first attempt to rewrite the module using `google-api-python-client`. I really liked it more that `libcloud`. Here are some things I would like feedback on/help with:

- I had to silence pylint at one place (line 303). The error seemed to me like false positive. Could someone have an extra look at them?
- I have used `execute_api_client_req` in several places, but not everywhere. Should I?
- When inserting or updating a route, I return the `globalOperation` resource in the module's output. Is this a bad idea?
- I have changed the `gce.py` module to return the response to a delete request when running the request through `execute_api_client_req`. I needed that to have a way to detect change when `state: absent`, without messing with exceptions.

**Comment by nkakouros** [comment]
I will soon be having some time to spend on gce ansible modules in the coming weeks until Christmas. If someone could comment on this PR it would be great so that I don't repeat the same "mistakes" on the other modules.

**Comment by nkakouros** [comment]
ready_for_review

**Comment by nkakouros** [comment]
With the magic-modules, is this PR irrelevant? Should I close it?

**Pull request closed without merging**
