### PR TITLE
Add option allowing the user to specify a custom cowpath

### PR DESCRIPTION
**Pull request by Bachmann1234**
This allows the user to use custom cowsay implementations without shadowing common cowsay paths

##### SUMMARY
I added a config variable to enable users to specify their own cowsay path. Or to allow them to use their own cowsay implementation. I intend to use this config variable to use https://github.com/erkin/ponysay as my cow provider 
screen shot 2017-12-03 at 2 30 45 pm

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
display

##### ANSIBLE VERSION

```
ansible 2.5.0 (custom_cowsay 8a9844c0d7) last updated 2017/12/03 14:33:18 (GMT -400)
  config file = None
  configured module search path = ['/Users/bachmann/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bachmann/code/ansible/lib/ansible
  executable location = /Users/bachmann/code/ansible/venv/bin/ansible
  python version = 3.6.2 (default, Jul 17 2017, 16:44:45) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

### CODE REVIEW

**Comment by Bachmann1234** [comment]
The output above is with the following environment variables set
```
set -x ANSIBLE_COW_SELECTION ""
set -x ANSIBLE_COWPATH "/usr/local/bin/ponysay"
```

**Comment by Bachmann1234** [comment]
I've also learned https://github.com/possatti/pokemonsay is a thing

**Comment by Bachmann1234** [comment]
Howdy @jborean93 I noticed the triage has been removed. Does that mean this is being considered? Should I rebase to make the CI no longer stale?

**Comment by jborean93** [comment]
@Bachmann1234 removing from triage just means we looked at the PR and make sure the tags were correct. `stale_ci` means that a CI hasn't run in x amount of days (unsure of the amount), you can close and reopen a PR to trigger a new CI build.

To get some traction on this I would recommend going on IRC to #ansible-devel and/or put this PR on the weekly agenda meeting. The agenda is here https://github.com/ansible/community/issues/286.

**Comment by Bachmann1234** [comment]
thanks @jborean93 ill find some time to at least ask about this.

**Comment by Bachmann1234** [comment]
Oh. Nice. Alrighty! Thanks

**Comment by gundalow** [comment]
@Bachmann1234 Notice we are changing the env in https://github.com/ansible/ansible/pull/34063

**Pull request merged**
