### PR TITLE
paramiko transport appears to hang if it gets a sudo lecture

### PR DESCRIPTION
**Pull request by d3matt**
- bring paramiko transport closer to ssh transport in how it deals with prompt

### CODE REVIEW

**Comment by deggis** [comment]
+1 for this. Spent some time finding the same thing.

**Comment by alikins** [comment]
Looks reasonable to me.

@jimi-c Looks like this was intended to get merge. Did it get missed?

**Comment by bcoca** [comment]
@amenonsen can you give sanity check?

**Comment by jimi-c** [comment]
Merged, looks sane to me (though it does not fully implement the state machine that ssh.py does).

Thanks!

**Pull request merged**
