### PR TITLE
New module: manage 1&1 roles (cloud/oneandone/oneandone_role)

### PR DESCRIPTION
**Pull request by aajdinov**
##### SUMMARY
Adding a new cloud module to support oneandone role management.

##### ISSUE TYPE

 - New Module Pull Request
 - Feature Pull Request

##### COMPONENT NAME
 - oneandone_role cloud module
 - oneandone module_util

##### ANSIBLE VERSION
```
ansible 2.6.0 (oneandone_users ad143452d7) last updated 2018/02/14 22:52:46 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Below is the output from one of the test playbooks utilizing the new module:
```
PLAY [localhost] ****************************************************************

TASK [Gathering Facts] *******************************************************
ok: [localhost]

TASK [Create a role] ***********************************************************
changed: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

```

### CODE REVIEW

**Comment by aajdinov** [comment]
@samdoran @resmo 

Is there anything else that needs to be done for these remaining 3 PRs to get merged?

**Comment by aajdinov** [comment]
ready_for_review

**Comment by aajdinov** [comment]
@resmo 
Hello René, is there anything I can do to speed up the merging process for the remaining remaining three PRs (new modules: manage 1&1 resources)

**Comment by Akasurde** [comment]
@edevenport @resmo Could you please review this ? Thanks

**Pull request closed without merging**
