### PR TITLE
Add integration tests for group_by precedence.

### PR DESCRIPTION
**Pull request by direvus**
##### SUMMARY
Test that, when a group is created with group_by, variables from the
corresponding group_vars/ file are correctly pulled in, and override
variables specified in group_vars/all.

See ansible/ansible#8664.

This is a rebase of PR ansible/ansible#8702, which having been ignored for almost 12 months, no longer applies cleanly.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
group_by

##### ANSIBLE VERSION
Not relevant

##### ADDITIONAL INFORMATION
Please note that I have not verified that the new test passes in this rebase.  It was passing in the original PR, but I couldn't get the tests to run at all in current 'devel', I figure it is currently in flux and broken.

### CODE REVIEW

**Comment by amenonsen** [comment]
I wish there were a different tag than `feature_pull_request` to apply to new tests.

Anyway, I think this looks good. I haven't been able to run the tests either, but from inspection it seems like the changes are reasonable. Maybe this should be merged, and any problems fixed up later when the tests are in better shape. (I'll fix it if nobody else does.)

**Comment by direvus** [comment]
So, this trivial test addition PR, for a test that @srvg specifically asked me to provide, has now been left to rot for 2.5 years, and I'm losing interest in dealing with the bot spam to rebase and reformat it every few months.

I understand that ansible is a very busy project and triage is necessary, but this is getting silly.

**Comment by mattclay** [comment]
@direvus Thanks for the tests. I've rebased, updated and merged them in #23262.

**Comment by direvus** [comment]
That's great, thanks very much @mattclay

**Pull request closed without merging**
