### PR TITLE
NXOS: Integration tests to Ansible (part 3)

### PR DESCRIPTION
**Pull request by rahushen**
##### SUMMARY

Added integration tests for
* nxos_file_copy
* nxos_igmp
* nxos_igmp_interface
* nxos_igmp_snooping
* nxos_ntp_auth
* nxos_ntp_options

##### ISSUE TYPE

 - IT Pull Request

##### ANSIBLE VERSION

```
ansible 2.4.0 (commit_it_rahushen3 72bf8d5ac5) last updated 2017/09/05 17:02:13 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

### CODE REVIEW

**Comment by gundalow** [comment]
```
Software
  loader:    version N/A
  kickstart: version 7.3(0)D1(1)
  system:    version 7.3(0)D1(1)
  kickstart image file is: bootflash:///titanium-d1-kickstart.7.3.0.D1.1.bin
  kickstart compile time:  1/11/2016 16:00:00 [02/11/2016 10:30:12]
  system image file is:    bootflash:///titanium-d1.7.3.0.D1.1.bin
  system compile time:     1/11/2016 16:00:00 [02/11/2016 13:08:11]


Hardware
  cisco NX-OSv Chassis ("NX-OSv Supervisor Module")
  QEMU Virtual CPU version 2.0 with 3064860 kB of memory.
  Processor Board ID TM3E6AB9DAB

  Device name: switch
  bootflash:    3184776 kB

```

**nxos_igmp_interface backtrace**
```
TASK [nxos_igmp_interface : put interface in L3 and enable PIM] **********************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/targets/nxos_igmp_interface/tests/common/sanity.yaml:16
<nxos01> connection transport is cli
<nxos01> using connection plugin network_cli
<nxos01> socket_path: /home/johnb/.ansible/pc/7b6586159a
Using module file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/modules/network/nxos/nxos_config.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312684.79-60821748637640 `" && echo ansible-tmp-1505312684.79-60821748637640="` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312684.79-60821748637640 `" ) && sleep 0'
<nxos01> PUT /tmp/tmpbg8_WT TO /home/johnb/.ansible/tmp/ansible-tmp-1505312684.79-60821748637640/nxos_config.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1505312684.79-60821748637640/ /home/johnb/.ansible/tmp/ansible-tmp-1505312684.79-60821748637640/nxos_config.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1505312684.79-60821748637640/nxos_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1505312684.79-60821748637640/" > /dev/null 2>&1 && sleep 0'
changed: [nxos01] => {
    "changed": true, 
    "commands": [
        "interface Ethernet2/1", 
        "no switchport", 
        "ip pim sparse-mode"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "after": null, 
            "backup": false, 
            "before": null, 
            "commands": [
                "no switchport", 
                "ip pim sparse-mode"
            ], 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "force": false, 
            "host": null, 
            "intended_config": null, 
            "lines": [
                "no switchport", 
                "ip pim sparse-mode"
            ], 
            "match": "none", 
            "parents": [
                "interface Ethernet2/1"
            ], 
            "password": null, 
            "port": null, 
            "provider": {
                "host": null, 
                "password": null, 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_ssl": null, 
                "username": null, 
                "validate_certs": null
            }, 
            "replace": "line", 
            "running_config": null, 
            "save": false, 
            "save_when": "never", 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }, 
    "updates": [
        "interface Ethernet2/1", 
        "no switchport", 
        "ip pim sparse-mode"
    ]
}

TASK [nxos_igmp_interface : Configure igmp interface with non-default values] ********************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/targets/nxos_igmp_interface/tests/common/sanity.yaml:26
<nxos01> connection transport is cli
<nxos01> using connection plugin network_cli
<nxos01> socket_path: /home/johnb/.ansible/pc/7b6586159a
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/basic.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/nxos.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/_text.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/pycompat24.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/six/__init__.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/connection.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/network_common.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/urls.py
Using module file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/modules/network/nxos/nxos_igmp_interface.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312691.84-207545402433772 `" && echo ansible-tmp-1505312691.84-207545402433772="` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312691.84-207545402433772 `" ) && sleep 0'
<nxos01> PUT /tmp/tmphbAMCx TO /home/johnb/.ansible/tmp/ansible-tmp-1505312691.84-207545402433772/nxos_igmp_interface.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1505312691.84-207545402433772/ /home/johnb/.ansible/tmp/ansible-tmp-1505312691.84-207545402433772/nxos_igmp_interface.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1505312691.84-207545402433772/nxos_igmp_interface.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1505312691.84-207545402433772/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_yy5GlH/ansible_module_nxos_igmp_interface.py", line 701, in <module>
    main()
  File "/tmp/ansible_yy5GlH/ansible_module_nxos_igmp_interface.py", line 562, in main
    if get_interface_mode(interface, intf_type, module) == 'layer2':
  File "/tmp/ansible_yy5GlH/ansible_module_nxos_igmp_interface.py", line 268, in get_interface_mode
    mode = str(interface_table.get('eth_mode', 'layer3'))
AttributeError: 'list' object has no attribute 'get'

fatal: [nxos01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_yy5GlH/ansible_module_nxos_igmp_interface.py\", line 701, in <module>\n    main()\n  File \"/tmp/ansible_yy5GlH/ansible_module_nxos_igmp_interface.py\", line 562, in main\n    if get_interface_mode(interface, intf_type, module) == 'layer2':\n  File \"/tmp/ansible_yy5GlH/ansible_module_nxos_igmp_interface.py\", line 268, in get_interface_mode\n    mode = str(interface_table.get('eth_mode', 'layer3'))\nAttributeError: 'list' object has no attribute 'get'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

TASK [nxos_igmp_interface : Configure igmp interface with default value] *************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/targets/nxos_igmp_interface/tests/common/sanity.yaml:73
<nxos01> connection transport is cli
<nxos01> using connection plugin network_cli
<nxos01> socket_path: /home/johnb/.ansible/pc/7b6586159a
Using module file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/modules/network/nxos/nxos_igmp_interface.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312696.53-217578909912409 `" && echo ansible-tmp-1505312696.53-217578909912409="` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312696.53-217578909912409 `" ) && sleep 0'
<nxos01> PUT /tmp/tmpbC5KaG TO /home/johnb/.ansible/tmp/ansible-tmp-1505312696.53-217578909912409/nxos_igmp_interface.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1505312696.53-217578909912409/ /home/johnb/.ansible/tmp/ansible-tmp-1505312696.53-217578909912409/nxos_igmp_interface.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1505312696.53-217578909912409/nxos_igmp_interface.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1505312696.53-217578909912409/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_JJqp1c/ansible_module_nxos_igmp_interface.py", line 701, in <module>
    main()
  File "/tmp/ansible_JJqp1c/ansible_module_nxos_igmp_interface.py", line 562, in main
    if get_interface_mode(interface, intf_type, module) == 'layer2':
  File "/tmp/ansible_JJqp1c/ansible_module_nxos_igmp_interface.py", line 268, in get_interface_mode
    mode = str(interface_table.get('eth_mode', 'layer3'))
AttributeError: 'list' object has no attribute 'get'

fatal: [nxos01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_JJqp1c/ansible_module_nxos_igmp_interface.py\", line 701, in <module>\n    main()\n  File \"/tmp/ansible_JJqp1c/ansible_module_nxos_igmp_interface.py\", line 562, in main\n    if get_interface_mode(interface, intf_type, module) == 'layer2':\n  File \"/tmp/ansible_JJqp1c/ansible_module_nxos_igmp_interface.py\", line 268, in get_interface_mode\n    mode = str(interface_table.get('eth_mode', 'layer3'))\nAttributeError: 'list' object has no attribute 'get'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

TASK [set_fact] **********************************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/nxos.yaml:32
ok: [nxos01] => {
    "ansible_facts": {
        "failed_modules": [
            "nxos_igmp_interface"
        ], 
        "test_failed": true
    }, 
    "changed": false, 
    "failed": false
}

```




**targets/nxos_igmp_snooping/tests/common/sanity.yaml**

```
TASK [nxos_igmp_snooping : Configure igmp snooping with non-default values] **********************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/targets/nxos_igmp_snooping/tests/common/sanity.yaml:6
<nxos01> connection transport is cli
<nxos01> using connection plugin network_cli
<nxos01> socket_path: /home/johnb/.ansible/pc/7b6586159a
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/basic.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/nxos.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/_text.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/pycompat24.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/six/__init__.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/connection.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/network_common.py
Using module_utils file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/module_utils/urls.py
Using module file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/modules/network/nxos/nxos_igmp_snooping.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312769.11-39882501186942 `" && echo ansible-tmp-1505312769.11-39882501186942="` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312769.11-39882501186942 `" ) && sleep 0'
<nxos01> PUT /tmp/tmpLyElkc TO /home/johnb/.ansible/tmp/ansible-tmp-1505312769.11-39882501186942/nxos_igmp_snooping.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1505312769.11-39882501186942/ /home/johnb/.ansible/tmp/ansible-tmp-1505312769.11-39882501186942/nxos_igmp_snooping.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1505312769.11-39882501186942/nxos_igmp_snooping.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1505312769.11-39882501186942/" > /dev/null 2>&1 && sleep 0'
changed: [nxos01] => {
    "changed": true, 
    "commands": [
        "ip igmp snooping link-local-groups-suppression", 
        "ip igmp snooping group-timeout never", 
        "ip igmp snooping report-suppression", 
        "ip igmp snooping v3-report-suppression", 
        "ip igmp snooping"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "group_timeout": "never", 
            "host": null, 
            "link_local_grp_supp": true, 
            "password": null, 
            "port": null, 
            "provider": {
                "host": null, 
                "password": null, 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_ssl": null, 
                "username": null, 
                "validate_certs": null
            }, 
            "report_supp": true, 
            "snooping": true, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "v3_report_supp": true, 
            "validate_certs": null
        }
    }
}

TASK [nxos_igmp_snooping : assert] ***************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/targets/nxos_igmp_snooping/tests/common/sanity.yaml:17
ok: [nxos01] => {
    "changed": false, 
    "failed": false, 
    "msg": "All assertions passed"
}

TASK [nxos_igmp_snooping : Check Idempotence - Configure igmp snooping with non-default values] **************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/targets/nxos_igmp_snooping/tests/common/sanity.yaml:21
<nxos01> connection transport is cli
<nxos01> using connection plugin network_cli
<nxos01> socket_path: /home/johnb/.ansible/pc/7b6586159a
Using module file /home/johnb/git/ansible-inc/ansible-workspace-4/lib/ansible/modules/network/nxos/nxos_igmp_snooping.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312774.66-129868754268563 `" && echo ansible-tmp-1505312774.66-129868754268563="` echo /home/johnb/.ansible/tmp/ansible-tmp-1505312774.66-129868754268563 `" ) && sleep 0'
<nxos01> PUT /tmp/tmpGlUM9q TO /home/johnb/.ansible/tmp/ansible-tmp-1505312774.66-129868754268563/nxos_igmp_snooping.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1505312774.66-129868754268563/ /home/johnb/.ansible/tmp/ansible-tmp-1505312774.66-129868754268563/nxos_igmp_snooping.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1505312774.66-129868754268563/nxos_igmp_snooping.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1505312774.66-129868754268563/" > /dev/null 2>&1 && sleep 0'
changed: [nxos01] => {
    "changed": true, 
    "commands": [
        "ip igmp snooping link-local-groups-suppression", 
        "ip igmp snooping report-suppression"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "group_timeout": "never", 
            "host": null, 
            "link_local_grp_supp": true, 
            "password": null, 
            "port": null, 
            "provider": {
                "host": null, 
                "password": null, 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_ssl": null, 
                "username": null, 
                "validate_certs": null
            }, 
            "report_supp": true, 
            "snooping": true, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "v3_report_supp": true, 
            "validate_certs": null
        }
    }
}

TASK [nxos_igmp_snooping : assert] ***************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/nxos-prs/pr29030/test/integration/targets/nxos_igmp_snooping/tests/common/sanity.yaml:25
fatal: [nxos01]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

```

**Review by gundalow — CHANGES_REQUESTED** [review]
Fails locally

**Review by Qalthos — CHANGES_REQUESTED** [review]
Hold back the ~nxos_igmp_interface,~ nxos_igmp_snooping, ~and nxos_ntp_options~ tests and we can merge this. The other tests should ideally get put in separate PRs and linked to related issues (like #27484)

**Comment by rahushen** [comment]
@Qalthos ... IT PRs were opened before I had fixes for the modules. I'm getting an all pass on all my platforms for these tests across my test matrix. Is this a failure on titanium ? Can you provide me a diff that'll fix the failures for igmp_snooping. I can test and commit to PR.

**Comment by Qalthos** [comment]
Looks like you found it yourself, #30439 seems to be the issue, we'll get back to this when that's closed.

**Comment by trishnaguha** [comment]
cherry-picked to 2.4, will be out with 2.4.2 release

**Pull request merged**
