### PR TITLE
new lookup-plugin: lsearch (linear search in text file)

### PR DESCRIPTION
**Pull request by jpmens**
This plugin will search a given text file for a key and return the string found or a configurable default. The general syntax of the plugin is

```
lookup('lsearch', "key file=/path/to/file.txt")
lookup('lsearch', "key2 file=/path/to/other.txt default=ENOENT")
```

Example:
### Playbook

``` yaml

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - action: debug msg="{{ lookup('lsearch', 'dos file=input.txt')  }}"
  - action: debug msg="{{ lookup('lsearch', 'tres file=other.txt')  }}"
  - action: debug msg="{{ lookup('lsearch', 'enoent file=input.txt')  }}"
  - action: template src=lsearch-template.in dest=/tmp/out.file.{{ item }}
    with_items:
     - a
     - b
     - c
     - d
```
### input.txt

```

uno:    One
dos     Two
tres    Three means 3
dos     Two #2
tres    TRESSS
#blu             kdkdkd
a       AAAAAAAAAAAAAAAAAAAA
b       BBBBBBBBBBBBBBBBBBBB
d       DDDDDDDDDDDDDDDDDDDD
quatro  Vier
```
### Template

``` jinja2

quatro is: {{ lookup('lsearch', 'quatro file=input.txt') }}
doing item: {{item}}

{# Build param consisting of key and file= #}
{% set param = ' '.join(( item, "file=input.txt", "default=OhNo!")) %}

param  is: {{ param }}
result is: {{ lookup('lsearch', param) }}

{% set val = lookup('lsearch', param)  %}
value is:  {{ val }}
```
### run

```

PLAY [127.0.0.1] **************************************************************

TASK: [debug msg="Two"] *******************************************************
ok: [127.0.0.1] => {
    "msg": "Two"
}

TASK: [debug msg=""] **********************************************************
ok: [127.0.0.1] => {
    "msg": ""
}

TASK: [debug msg=""] **********************************************************
ok: [127.0.0.1] => {
    "msg": ""
}

TASK: [template src=lsearch-template.in dest=/tmp/out.file.{{item}}] **********
changed: [127.0.0.1] => (item=a)
changed: [127.0.0.1] => (item=b)
changed: [127.0.0.1] => (item=c)
changed: [127.0.0.1] => (item=d)

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=4    changed=1    unreachable=0    failed=0
```
### out.file.a

```

quatro is: Vier
doing item: a


param  is: a file=input.txt default=OhNo!
result is: AAAAAAAAAAAAAAAAAAAA

value is:  AAAAAAAAAAAAAAAAAAAA
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you give a example of this being used in a real world context to let me understand if this might be applicable to core and how it might be documented?

I know we have search in here already using the regex (as a filter plugin), though I'm curious why just using the regex search isn't enough.

Also I think the name "lsearch" is a little confusing.

**Comment by jpmens** [comment]
We have a bunch of templates that contain a value which is different on
a per-host basis. Instead of populating the template with a bunch of {%
if %} I wanted to replace that with a lookup function that obtains the
value based on ansible_hostname. (As in the 'template' above.)

I don't think any of the other plugins satisfy this use-case elegantly.

As for the name, 'lsearch' means linear search; I expect there'll be
others sometime. :-)

**Comment by jpmens** [comment]
Forgot the example template: here we have a connection-specific string which differs per/host, but this is just an example.

``` jinja2

# {{ ansible_managed }}
dbname: s1
connection: tcp://{{ lookup('lsearch', inventory_hostname) }}/
...
```

**Comment by resmo** [comment]
If I understand this correctly: This makes life easier for different variables values handled in a single file as key:value store. 

It looks to me like kind of a "stored config" mechanism. If I think further, using a key value database, like redis would also be interesting.

**Comment by jpmens** [comment]
There is already a redis lookup plugin.

**Comment by mpdehaan** [comment]
"If I understand this correctly: This makes life easier for different variables values handled in a single file as key:value store."

I don't understand this sentence myself :)

I'm not sure we want to encourage using flat files in unstructured formats as a KV store, so I'm tempted to not merge this plugin.

vars_files seems like it would a better way to go and then just extract a particular key.

Perhaps this should be discussed on ansible-devel ?

**Comment by jpmens** [comment]
Taken to ansible-devel.

**Comment by mpdehaan** [comment]
Closing per list discussion about wanting to support defined formats and storage systems -- I think I'd take a csv and tsv one though.

See conversation on https://groups.google.com/forum/#!topic/ansible-devel/zkfuMmU81ZY

**Pull request closed without merging**
