### PR TITLE
Add securestr parameter type

### PR DESCRIPTION
**Pull request by ksubileau**
##### SUMMARY
Added securestr parameter type to Get-AnsibleParam to get a SecureString object more easily.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

`Ansible.ModuleUtils.Legacy.psm1`

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### ADDITIONAL INFORMATION

```
$params = Parse-Args $args
$Password = Get-AnsibleParam -obj $params -name "password" -type "securestr"
$Password.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    SecureString                             System.Object
```

### CODE REVIEW

**Comment by samdoran** [comment]
cc @nitzmahone @jborean93

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/72546/8/tests

**Comment by ksubileau** [comment]
Hi @mattclay 
Looking at this failure and its error message, it doesn't seem to be related to my changes.
There is also the same failure in a previous run : https://app.shippable.com/github/ansible/ansible/runs/71611/8/tests

**Comment by ksubileau** [comment]
I did a little more work to introduce this new parameter type into the existing code base. I also cleaned some parts of code and removed some PSLint exclusions because the corresponding rules are now satisfied with this refactoring.
Now, except for a specific usage or when it's not possible to use a `SecureString`, it should be less necessary to add the `PSAvoidUsingConvertToSecureStringWithPlainText`, `PSAvoidUsingPlainTextForPassword` or `PSAvoidUsingUserNameAndPassWordParams` exclusions for a module code, as it's possible to directly get a `SecureString` parameter or to use the new `Create-PSCredential` function.

**Comment by jhawkesworth** [comment]
Not sure why the tests are failing.

I like the idea of adding this but am unsure about adding powershell-specific module parameter types.

The background here is that there is a desire to create within ansible a declarative argument specification, so that the controller part of ansible can be made aware of module parameters and can then apply logic to them.  One possible use of this would be to allow the controller to be aware of sensitive data and not display it for individual module parameters (rather than the existing `no_log` which applies to the whole of module.

I recall a similar discussion about hashtables (problematic because powershell preserves insertion order but not all python versions do, and you would need to use odict structures in yaml.

My first thought would be to have a more generic name, maybe 'password' or 'hidden' or 'sensitive' which would be implmented as secure string for powershell modules and ... something else for python modules ( I guess it would be possible to implement a similar algorithm in python).

However I am not sure whether this would make achieving declarative argument specification harder to achieve.

I am going to suggest discussing this at the windows working group.

**Comment by ksubileau** [comment]
I think the tests are failing because of a known bug fixed in #42330

That's a good point to have a generic name so that this can be also implemented in python and that we keep a common interface. That said, we can also consider 'securestr' as already being a generic term...

**Comment by jborean93** [comment]
It was decided at the latest WWG to not go ahead with this PR, the notes for the meeting are here https://meetbot.fedoraproject.org/ansible-windows/2018-07-10/ansible_windows_working_group.2018-07-10-20.00.log.html.

In the end we decided not to go ahead with this for 2 reasons

* It gives a false sense of security where the type is expected to be secure where we are converting an existing string to a secure string
* There is no Python equivalent right now and extends the gap between the 2

We appreciate the time and effort that @ksubileau has put into this and hope to see future contributions from him.

**Pull request closed without merging**
