### PR TITLE
Remove redundant get_obj method

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix removes redundant get_obj method in favor of
find_datacenter_by_name API. Also, strict checking for
datacenter object.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest_find.py

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by nerzhul** [comment]
shipit

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@dagwieers  Can you please review this ?

**Pull request merged**
