### PR TITLE
Allow template files to be vaulted

### LINKED ISSUE #18702: Feature: Ansible Vault Template Module Support
##### ISSUE TYPE
- Feature Idea

##### ANSIBLE VERSION
N/A

##### COMPONENT NAME
vault

##### SUMMARY
I know the copy module was updated to support ansible-vault encrypted files. Is it possible to extend the ansible-vault coverage to include template files that are copied over. This can be done by decrypting the file on the ansible host, creating the template and then transferring it over.

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY

This PR allows template source files to be vaulted.

Fixes https://github.com/ansible/ansible/issues/18702

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
action/template.py

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

Nothing special, create a template, vault encrypt it, use it as the `src` with the `template` module.

### CODE REVIEW

**Comment by bcoca** [comment]
~~might want to support this from start #22739~~ nvmd, don't see how it would make sense for template.

**Comment by sivel** [comment]
All green

**Comment by jhawkesworth** [comment]
Nice feature.  Can't make any useful observations about the code but it might be worth tweaking the docs here to mention templates too http://docs.ansible.com/ansible/playbooks_vault.html#what-can-be-encrypted-with-vault

**Comment by sivel** [comment]
I've updated the docs with the current action plugins/modules that support this.  Eventually, we'll probably need a more comprehensive way to document that, but the number of modules is still somewhat small.

**Comment by jhawkesworth** [comment]
Doc change works for me.  Flying the flag for windows users, its likely win_copy and almost certain that win_template could be added to the list of modules too.

**Comment by jhawkesworth** [comment]
^ Not worth holding up merge for though.

**Comment by sivel** [comment]
@bcoca does everything look good to you?

**Comment by sivel** [comment]
Closing and opening to re-trigger CI

**Comment by bcoca** [comment]
@jhawkesworth  strictly speaking, 'modules' should never be able to support this, only action plugins. Otherwise we would be sending vault secrets to the target machines ... don't want that.

**Comment by sivel** [comment]
@bcoca are you good with merging this?

**Pull request merged**
