### PR TITLE
Fix the default url of get_xml function.

### PR DESCRIPTION
**Pull request by lemonlatte**
Related to issue #6764, this a minor patch on `virt` module. This enables a user to configure uri in get_xml function.

### CODE REVIEW

**Comment by mpdehaan** [comment]
So previously this function was calling the "open" call to do a bit more error checking up front -- that all being said the code was quite old, but this seems to remove the error checking -- so if there is an error talking to the VM it may just traceback.

Can I ask what testing was done with invalid connections or VM names and what results you received?

Thanks!

**Comment by lemonlatte** [comment]
Do you mean that how I find this invalid connection?

**Comment by lemonlatte** [comment]
Sorry, I misunderstood what you meaning.
Error messages come from class `LibvirtConnection`. I just reuse the existed connection method in it.

The error messages are:
- name error

``` shell
~/.v/a/ansible_test > ansible -m virt -a "command=get_xml name=test_fail uri=qemu:///system" -i hosts T2_02                                       10:57:58 04/01/2014
172.16.10.199 | FAILED >> {
    "failed": true,
    "msg": "Domain not found: no domain with matching name 'test_fail'"
}
```
- uri error

``` shell
~/.v/a/ansible_test > ansible -m virt -a "command=get_xml name=test_fail uri=qemu:///system_fail" -i hosts T2_02                                  10:58:07 04/01/2014
172.16.10.199 | FAILED >> {
    "failed": true,
    "msg": "internal error unexpected QEMU URI path '/system_fail', try qemu:///system"
}
```

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
