### PR TITLE
Added DIY callback plugin

### LINKED ISSUE #14367: Show aggregated playbook execution recap at the bottom of play recap
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
N/A

##### SUMMARY
Currently if you run a playbook with many hosts `PLAY RECAP`, as Ansible calls it, e.g. looks like this:

```
PLAY RECAP ******************************************************************** 
           to retry, use: --limit @site.retry

backup-01                   : ok=18   changed=1    unreachable=0    failed=0   
backup-02                   : ok=0    changed=0    unreachable=1    failed=0   
server-01                   : ok=18   changed=1    unreachable=0    failed=0   
server-02                   : ok=18   changed=1    unreachable=0    failed=0   
server-03                   : ok=18   changed=1    unreachable=0    failed=0   
server-04                   : ok=18   changed=1    unreachable=0    failed=0   
server-05                   : ok=18   changed=1    unreachable=0    failed=0   
server-06                   : ok=18   changed=1    unreachable=0    failed=0   
server-07                   : ok=18   changed=1    unreachable=0    failed=0   
server-08                   : ok=18   changed=1    unreachable=0    failed=0   
server-09                   : ok=18   changed=1    unreachable=0    failed=0   
server-10                   : ok=18   changed=1    unreachable=0    failed=0   
server-11                   : ok=18   changed=1    unreachable=0    failed=0   
server-12                   : ok=18   changed=1    unreachable=0    failed=0   
server-13                   : ok=18   changed=1    unreachable=0    failed=0   
server-14                   : ok=18   changed=1    unreachable=0    failed=0   
server-15                   : ok=18   changed=1    unreachable=0    failed=0   
server-16                   : ok=18   changed=1    unreachable=0    failed=0   
server-17                   : ok=18   changed=1    unreachable=0    failed=0   
server-18                   : ok=18   changed=1    unreachable=0    failed=0   
server-19                   : ok=18   changed=1    unreachable=0    failed=0   
server-20                   : ok=18   changed=1    unreachable=0    failed=0   
server-21                   : ok=18   changed=1    unreachable=0    failed=0   
server-22                   : ok=18   changed=1    unreachable=0    failed=0   
server-23                   : ok=18   changed=1    unreachable=0    failed=0   
server-24                   : ok=18   changed=1    unreachable=0    failed=0   
server-25                   : ok=18   changed=1    unreachable=0    failed=0   
server-26                   : ok=18   changed=1    unreachable=0    failed=0   
server-27                   : ok=18   changed=1    unreachable=0    failed=0   
server-28                   : ok=18   changed=1    unreachable=0    failed=0   
server-29                   : ok=18   changed=1    unreachable=0    failed=0   
server-30                   : ok=18   changed=1    unreachable=0    failed=0   
server-31                   : ok=18   changed=1    unreachable=0    failed=0   
server-32                   : ok=18   changed=1    unreachable=0    failed=0   
server-33                   : ok=18   changed=1    unreachable=0    failed=0   
server-34                   : ok=18   changed=1    unreachable=0    failed=0   
server-35                   : ok=18   changed=1    unreachable=0    failed=0   
server-36                   : ok=18   changed=1    unreachable=0    failed=0   
server-37                   : ok=18   changed=1    unreachable=0    failed=0   
server-38                   : ok=18   changed=1    unreachable=0    failed=0   
server-39                   : ok=18   changed=1    unreachable=0    failed=0   
server-40                   : ok=18   changed=1    unreachable=0    failed=0   
server-41                   : ok=18   changed=1    unreachable=0    failed=0   
server-42                   : ok=18   changed=1    unreachable=0    failed=0   
server-43                   : ok=18   changed=1    unreachable=0    failed=0   
server-44                   : ok=18   changed=1    unreachable=0    failed=0   
server-45                   : ok=18   changed=1    unreachable=0    failed=0   
server-46                   : ok=18   changed=1    unreachable=0    failed=0   
server-47                   : ok=18   changed=1    unreachable=0    failed=0   
server-48                   : ok=18   changed=1    unreachable=0    failed=0   
server-49                   : ok=18   changed=1    unreachable=0    failed=0   
server-50                   : ok=18   changed=1    unreachable=0    failed=0   
server-51                   : ok=18   changed=1    unreachable=0    failed=0   
server-52                   : ok=18   changed=1    unreachable=0    failed=0   
server-53                   : ok=18   changed=1    unreachable=0    failed=0   
server-54                   : ok=18   changed=1    unreachable=0    failed=0   
server-55                   : ok=18   changed=1    unreachable=0    failed=0   
server-56                   : ok=18   changed=1    unreachable=0    failed=0   
server-57                   : ok=18   changed=1    unreachable=0    failed=0   
server-58                   : ok=18   changed=1    unreachable=0    failed=0   
server-59                   : ok=18   changed=1    unreachable=0    failed=0   
server-60                   : ok=18   changed=1    unreachable=0    failed=0   
server-61                   : ok=18   changed=1    unreachable=0    failed=0   
server-62                   : ok=18   changed=1    unreachable=0    failed=0   
server-63                   : ok=18   changed=1    unreachable=0    failed=0   
server-64                   : ok=18   changed=1    unreachable=0    failed=0   
server-65                   : ok=18   changed=1    unreachable=0    failed=0   
server-66                   : ok=18   changed=1    unreachable=0    failed=0   
server-67                   : ok=18   changed=1    unreachable=0    failed=0   
server-68                   : ok=18   changed=1    unreachable=0    failed=0   
server-69                   : ok=18   changed=1    unreachable=0    failed=0   
server-70                   : ok=18   changed=1    unreachable=0    failed=0   
server-71                   : ok=18   changed=1    unreachable=0    failed=0   
server-72                   : ok=18   changed=1    unreachable=0    failed=0   
server-73                   : ok=18   changed=1    unreachable=0    failed=0   
server-74                   : ok=18   changed=1    unreachable=0    failed=0   
server-75                   : ok=18   changed=1    unreachable=0    failed=0   
server-76                   : ok=18   changed=1    unreachable=0    failed=0   
server-77                   : ok=18   changed=1    unreachable=0    failed=0   
server-78                   : ok=18   changed=1    unreachable=0    failed=0   
server-79                   : ok=18   changed=1    unreachable=0    failed=0   
server-80                   : ok=18   changed=1    unreachable=0    failed=0
```

Even though Ansible displays these host in colors (green, orange and red), the problem with this display is that you can only see a limited number of lines (on my resolution and font size I can see about 64 lines), so if there are a lot of hosts, you have to scroll up to be able to see how things went.

In the example above host `backup-02` is unreachable and if I didn't scroll up, I would probably miss that. I also had situations where I executed `site.yml` (which includes all playbooks) and in some plays all hosts failed, so Ansible stopped further execution and since the hosts that failed were on top, I haven't realized that the execution didn't go over all hosts.

I would also like to note that `to retry, use: --limit @site.retry` is very easy to miss.

I would recommend that at the bottom of this recap Ansible prints an aggregated summary which you cannot miss, either sums of all `ok`/`changed`/`unreachable`/`failed` tasks:

```
Task recap:
ok= 1441    changed=79    unreachable=1    failed=0
```

or just count the number of hosts that are `ok`/`changed`/`unreachable`/`failed`:

```
Host recap:
ok=1   changed=84    unreachable=1    failed=0 
```

I like the host recap more, since you can easily see how many hosts were ok, changed, etc.

Of course color them the same like before, `ok` in green, `changed` in orange and `unreachable`/`failed` in red.

### LINKED ISSUE #32584: Alternative message: FAILED - RETRYING:
Is it possible to display a user friendlier message when looping waiting for a resource to become available than standard: **FAILED - RETRYING**?
If you want to display output of Ansible process to a user not used to Ansible - this sounds as there is something wrong - when it is actually just part of the planned waiting for a resource to become available after initialization?

If my task name is: "Waiting for server to start - usually takes 1-2 minutes"

Then I would like to customize to:
**RESOURCE NOT AVAILABLE YET - RETRYING:** Waiting for server to start - usually takes 1-2 minutes (43 Retries left)
Or just simply:
**RETRYING:** Waiting for server to start - usually takes 1-2 minutes (43 Retries left)
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.3.0.0
configured module search path = Default w/o overrides
python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by theque5t**
##### SUMMARY
Customize the output via templating

##### ISSUE TYPE
* Feature Pull Request

##### COMPONENT NAME
DIY Callback Plugin

##### ADDITIONAL INFORMATION
Example use case: [ansible-playbook-execute](https://github.com/theque5t/ansible-playbook-execute)
Tested on the following Python versions: 
* 2.7.15rc1
* 3.5.8
* 3.6.7

Tested on the following Ansible versions: 
* 2.10.0.dev0
* 2.9.2
* 2.8.5

Fixes #14367 
Fixes #32584

### CODE REVIEW

**Comment by theque5t** [comment]
bot_status

**Comment by theque5t** [comment]
ready_for_review

**Comment by theque5t** [comment]
ready_for_review

**Review by jamescassell — APPROVED** [review]
I like the concept, but did not actually test it.

**Comment by theque5t** [comment]
bot_status

**Comment by theque5t** [comment]
@jamescassell Thank you, much appreciated. In case you and others are interested in testing, I've copied the example from the plugin documentation down below. 

**ansible.cfg**
```
  # Enable plugin
  [defaults]
  stdout_callback=diy

  [callback_diy]
  # Output when playbook starts
  playbook_on_start_msg="diy output(via ansible.cfg): playbook example: {{ ansible_callback_diy.playbook.file_name }}"
  playbook_on_start_msg_color=yellow

  # Comment out to allow default plugin output
  # playbook_on_play_start_msg="PLAY: starting play {{ ansible_callback_diy.play.name }}"

  # Accept on_skipped_msg or ansible_callback_diy_runner_on_skipped_msg as input vars
  # If neither are supplied, omit the option
  runner_on_skipped_msg="{{ on_skipped_msg | default(ansible_callback_diy_runner_on_skipped_msg) | default(omit) }}"

  # Newline after every callback
  # on_any_msg='{{ " " | join("\n") }}'
```
**playbook.yml**
```yaml
  ---
  - name: "default plugin output: play example"
    hosts: localhost
    gather_facts: no
    tasks:
      - name:  default plugin output
        debug:
          msg: default plugin output

  - name: override from play vars
    hosts: localhost
    gather_facts: no
    vars:
      green: "\e[0m\e[38;5;82m"
      yellow: "\e[0m\e[38;5;11m"
      bright_purple: "\e[0m\e[38;5;105m"
      cyan: "\e[0m\e[38;5;51m"
      green_bg_black_fg: "\e[0m\e[48;5;40m\e[38;5;232m"
      yellow_bg_black_fg: "\e[0m\e[48;5;226m\e[38;5;232m"
      purple_bg_white_fg: "\e[0m\e[48;5;57m\e[38;5;255m"
      cyan_bg_black_fg: "\e[0m\e[48;5;87m\e[38;5;232m"
      magenta: "\e[38;5;198m"
      white: "\e[0m\e[38;5;255m"
      ansible_callback_diy_playbook_on_play_start_msg: "\n{{green}}diy output(via play vars): play example: {{magenta}}{{ansible_callback_diy.play.name}}\n\n"
      ansible_callback_diy_playbook_on_task_start_msg: "diy output(via play vars): task example: {{ ansible_callback_diy.task.name }}"
      ansible_callback_diy_playbook_on_task_start_msg_color: cyan
      ansible_callback_diy_playbook_on_stats_msg: |+2
                CUSTOM STATS
        ==============================
        {% for key in ansible_callback_diy.stats | sort %}
        {% if ansible_callback_diy.stats[key] %}
        {% if key == 'ok' %}
        {% set color_one = lookup('vars','green_bg_black_fg') %}
        {% set prefix = '      ' %}
        {% set suffix = '     ' %}
        {% set color_two = lookup('vars','green') %}
        {% elif key == 'changed' %}
        {% set color_one = lookup('vars','yellow_bg_black_fg') %}
        {% set prefix = '   ' %}
        {% set suffix = '   ' %}
        {% set color_two = lookup('vars','yellow') %}
        {% elif key == 'processed' %}
        {% set color_one = lookup('vars','purple_bg_white_fg') %}
        {% set prefix = '  ' %}
        {% set suffix = '  ' %}
        {% set color_two = lookup('vars','bright_purple') %}
        {% elif key == 'skipped' %}
        {% set color_one = lookup('vars','cyan_bg_black_fg') %}
        {% set prefix = '   ' %}
        {% set suffix = '   ' %}
        {% set color_two = lookup('vars','cyan') %}
        {% else %}
        {% set color_one = "" %}
        {% set prefix = "" %}
        {% set suffix = "" %}
        {% set color_two = "" %}
        {% endif %}
        {{ color_one }}{{ "%s%s%s" | format(prefix,key,suffix) }}{{ color_two }}: {{ ansible_callback_diy.stats[key] | to_nice_yaml }}
        {% endif %}
        {% endfor %}

    tasks:
      - name: custom banner with default plugin result output
        debug:
          msg: "default plugin output: result example"

      - name: override from task vars
        debug:
          msg: "example {{ two }}"
        changed_when: true
        vars:
          white_fg_red_bg: "\e[0m\e[48;5;1m"
          two: "{{ white_fg_red_bg }}    2    "
          ansible_callback_diy_playbook_on_task_start_msg: "\ndiy output(via task vars): task example: {{ ansible_callback_diy.task.name }}"
          ansible_callback_diy_playbook_on_task_start_msg_color: bright magenta
          ansible_callback_diy_runner_on_ok_msg: "diy output(via task vars): result example: \n{{ ansible_callback_diy.result.output.msg }}\n"
          ansible_callback_diy_runner_on_ok_msg_color: "{{ 'yellow' if ansible_callback_diy.result.is_changed else 'bright green' }}"

      - name: suppress output
        debug:
          msg: i should not be displayed
        vars:
          ansible_callback_diy_playbook_on_task_start_msg: ""
          ansible_callback_diy_runner_on_ok_msg: ""

      - name: using alias vars (see ansible.cfg)
        debug:
          msg:
        when: False
        vars:
          ansible_callback_diy_playbook_on_task_start_msg: ""
          on_skipped_msg: "diy output(via task vars): skipped example:\n\e[0m\e[38;5;4m\u25b6\u25b6 {{ ansible_callback_diy.result.task.name }}\n"
          on_skipped_msg_color: white

      - name: just stdout
        command: echo some stdout
        vars:
          ansible_callback_diy_playbook_on_task_start_msg: "\n"
          ansible_callback_diy_runner_on_ok_msg: "{{ ansible_callback_diy.result.output.stdout }}\n"

      - name: multline output
        debug:
          msg: "{{ multiline }}"
        vars:
          ansible_callback_diy_playbook_on_task_start_msg: "\ndiy output(via task vars): task example: {{ ansible_callback_diy.task.name }}"
          multiline: "line\nline\nline"
          ansible_callback_diy_runner_on_ok_msg: |+2
            some
            {{ ansible_callback_diy.result.output.msg }}
            output

          ansible_callback_diy_playbook_on_task_start_msg_color: bright blue

      - name: indentation
        debug:
          msg: "{{ item.msg }}"
        with_items:
          - { indent: 1, msg: one., color: red }
          - { indent: 2, msg: two.., color: yellow }
          - { indent: 3, msg: three..., color: bright yellow }
        vars:
          ansible_callback_diy_runner_item_on_ok_msg: "{{ ansible_callback_diy.result.output.msg | indent(item.indent, True) }}"
          ansible_callback_diy_runner_item_on_ok_msg_color: "{{ item.color }}"
          ansible_callback_diy_runner_on_ok_msg: "GO!!!"
          ansible_callback_diy_runner_on_ok_msg_color: bright green

      - name: using lookup and template as file
        shell: "echo {% raw %}'output from {{ file_name }}'{% endraw %} > {{ file_name }}"
        vars:
          ansible_callback_diy_playbook_on_task_start_msg: "\ndiy output(via task vars): task example: {{ ansible_callback_diy.task.name }}"
          file_name: diy_file_template_example
          ansible_callback_diy_runner_on_ok_msg: "{{ lookup('template', file_name) }}"

      - name: 'look at top level vars available to the "runner_on_ok" callback'
        debug:
          msg: ''
        vars:
          ansible_callback_diy_playbook_on_task_start_msg: "\ndiy output(via task vars): task example: {{ ansible_callback_diy.task.name }}"
          ansible_callback_diy_runner_on_ok_msg: |+2
            {% for var in (ansible_callback_diy.top_level_var_names|reject('match','vars|ansible_callback_diy.*')) | sort %}
            {{ green }}{{ var }}:
              {{ white }}{{ lookup('vars', var) }}

            {% endfor %}
          ansible_callback_diy_runner_on_ok_msg_color: white

      - name: 'look at event data available to the "runner_on_ok" callback'
        debug:
          msg: ''
        vars:
          ansible_callback_diy_playbook_on_task_start_msg: "\ndiy output(via task vars): task example: {{ ansible_callback_diy.task.name }}"
          ansible_callback_diy_runner_on_ok_msg: |+2
            {% for key in ansible_callback_diy | sort %}
            {{ green }}{{ key }}:
              {{ white }}{{ ansible_callback_diy[key] }}

            {% endfor %}
```

**Comment by theque5t** [comment]
bot_status

**Comment by theque5t** [comment]
bot_status

**Comment by theque5t** [comment]
Re-submitted as ansible-collections/community.general#432

**Pull request closed without merging**
