### PR TITLE
minor fixes to s3 module

### PR DESCRIPTION
**Pull request by bennojoy**
Minor bug fixes for the S3 module.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Benno,

Can you please provide more information on pull request comments.

What was the problem that this defect fixed?

Also, the comment in source control should be better.   At least "minor fixes for the S3 module".

Thanks!

**Comment by bennojoy** [comment]
@mpdehaan 

 Sorry for the short description.
The fixes in this PR includes a proper module.exit_json for creation of a bucket, otherwise the opreration would have just failed.
The dest parameter is optional in the module but it does a "dest = os.path.expanduser(module.params.get('dest'))" before checking if the dest variable is set, which causes all action to fail which doesnt need dest.
The module would fail with a module_fail_json() if a bucket already exists, changed that to module_exit_json wiht changed=False.

Regards,
Benno

**Comment by mpdehaan** [comment]
Hi Benno,

Looks good.

On line 408, you should be returning changed= and not Changed=.

Can you update this?

Thanks!

**Comment by bennojoy** [comment]
@mpdehaan 

Thanks, updated with the change.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
