### PR TITLE
Refactor: vault_password is an inventory parameter

### PR DESCRIPTION
**Pull request by srgvg**
Use inventory.vault_password instead of passing it through every function.

```
modified:   ../../lib/ansible/inventory/__init__.py
modified:   ../../lib/ansible/inventory/vars_plugins/noop.py
modified:   ../../lib/ansible/playbook/__init__.py
modified:   ../../lib/ansible/playbook/play.py
modified:   ../../lib/ansible/runner/__init__.py
modified:   ../../lib/ansible/runner/action_plugins/add_host.py
modified:   ../../lib/ansible/runner/action_plugins/group_by.py
modified:   ../units/TestPlayVarsFiles.py
```

[Review on Reviewable](https://reviewable.io/reviews/ansible/ansible/9050)

### CODE REVIEW

**Comment by amenonsen** [comment]
I can't imagine very well a use case for setting the vault password in the inventory, but in terms of not passing it around everywhere internally it certainly looks like a worthwhile cleanup. @srvg, any plans to rebase this to apply to current devel? (I don' t think the commit message should list changed files, though, but rather some rationale for the change.)

**Comment by srgvg** [comment]
This not about setting the vault password in the "inventory", from a user perspective, but keeping it as a variable of the Python object, and hence avoiding theneed to pass it around several functions.

That said, looking at a posible rebase, I see some things changed, and I'm not sure this is still relevant. Perhaps @jimi-c can comment?

**Comment by bcoca** [comment]
i'm not sure inventory is the proper place for it, play_context, variable_manager or dataloader seem better options

**Comment by srgvg** [comment]
Well, it was a patch on v1. I have nu clue about v2 code yet :) This might very likely already have been adressed by now.

**Comment by amenonsen** [comment]
@srvg nope, it's still relevant to v2 even if the exact details have changed.

**Comment by sivel** [comment]
@srvg,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by sivel** [comment]
@srvg,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by sivel** [comment]
@srvg,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by amenonsen** [comment]
Closing per above comment. (I still think this would be a worthwhile internal cleanup, if anyone else wants to work on it and resubmit.)

**Pull request closed without merging**
