### PR TITLE
sshkey module revised

### PR DESCRIPTION
**Pull request by bradobro**
Michael, 

I've revised my sshkey module per your advice, though later than promised.

Done: took out OOP.
Done: renamed param: ensure -> state

Notice: I haven't settled on a prettier way to include the key. Looking for advice on that because I know variable includes was under discussion. Not sure what best practices seem to you. IMHO, I think it would be nice to let people use the ugly way (literal string key) if they want, but I'm not militant about that.

Notice: The OOP is gone, but I did put param reading in a function. I tried to keep it simple, but wanted to find a non-dense way to leverage structured exception handling.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I can't take the merge commits. 

Please use git pull --rebase always and not git pull or git fetch + git merge, they won't happen again.

You will want to start a new topic branch and cherry pick the relevant commits over and then resubmit

**Comment by mpdehaan** [comment]
always also keep one branch per feature

**Comment by bradobro** [comment]
I'll have to read up on that--we're a Mercurial shop. Git's great, but thinks a little differently. I'll have to figure out how to squash the commits.

**Comment by mpdehaan** [comment]
squash commits are not so much a concern -- that's a different thing but it definitely helps the review along too!

**Pull request closed without merging**
