### PR TITLE
crypto modules: updating argument_spec

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
I found out a couple of days that `argument_spec` allows to specify list element types for `type == 'list'`, and recursive argument specs for `type == 'dict'`. In this PR I made the adjustments for `type == 'list'` for the crypto modules.

There are a couple of `type == 'dict'` values, but I didn't touch one of them because:
  1. for `openssl_csr` and `openssl_certificate`, it is used for `issuer` and `subject`, where possible values could change with newer OpenSSL versions (I think);
  2. for `acme_certificate`, it is used for `data`, which is passed in from a previous run;
  3. for `acme_challenge_cert_helper`, it is used for `challenge_data`, which essentially comes from the ACME server.

Since the `options=dict(...)` specs for `type == 'dict'` do not allow to specify "allow more key/value pairs to be present", and in all these cases there is no final maximal list of key/value pairs (to my knowledge), I don't think we can use that here.

Finally, note that for `type == 'list'`, the value for `elements` is ignored (except when it is `'dict'`), so this whole change isn't doing much (right now). I hope that will change at some point, though (see #48473).

Also, if in future the documentation is partially extracted from `argument_spec` (#45805), so having that information here definitely won't hurt.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
acme_account
certificate_complete_chair
openssl_certificate
openssl_csr
openssl_pkcs12

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
Pinging @MarkusTeufelberger @gdelpierre as authors of affected modules.

**Comment by MarkusTeufelberger** [comment]
In the future I'd rather get rid of (most of) these list parameters and only have "issuer", "subject", "extensions" etc, since having named OIDs with list parameters is a bit limiting in the certificate case - x509 certificates allow more types of OIDs than what might be initially expected and some of these are not even understood by openssl.

For this change here, I don't have any objection, thanks for improving these modules!

**Comment by MarkusTeufelberger** [comment]
shipit

**Comment by felixfontein** [comment]
@MarkusTeufelberger I agree, it would be nice to rework the interface. Thanks for reviewing!

**Pull request merged**
