### PR TITLE
Contributing new module to manage HUAWEI data center CloudEngine switch

### PR DESCRIPTION
**Pull request by JackyGao2016**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

cloudengine/ce (network module)

##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']

```

##### SUMMARY

Contributing HUAWEI CloudEngine switch ansible module.
HUAWEI CloudEngine switch is for data center network.
This is the first time HUAWEI contributes network module code.

```
(1) ce_command:

# ansible -m ce_command -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 commands="display device"' localhost --connection local
localhost | SUCCESS => {
    "changed": false, 
    "stdout": [
        "Device status:\n--------------------------------------------------------------------------------\nSlot  Card   Type                     Online   Power Register     Alarm     Primary        \n--------------------------------------------------------------------------------\n2     -      CE7850-32Q-EI            Present  On    Registered   Normal    Master         \n      FAN1   FAN-40EA-F               Present  On    Registered   Abnormal  NA             \n      PWR1   PAC-600WA-F              Present  On    Registered   Normal    NA             \n--------------------------------------------------------------------------------"
    ], 
    "stdout_lines": [
        [
            "Device status:", 
            "--------------------------------------------------------------------------------", 
            "Slot  Card   Type                     Online   Power Register     Alarm     Primary        ", 
            "--------------------------------------------------------------------------------", 
            "2     -      CE7850-32Q-EI            Present  On    Registered   Normal    Master         ", 
            "      FAN1   FAN-40EA-F               Present  On    Registered   Abnormal  NA             ", 
            "      PWR1   PAC-600WA-F              Present  On    Registered   Normal    NA             ", 
            "--------------------------------------------------------------------------------"
        ]
    ], 
    "warnings": []
}
```

### CODE REVIEW

**Comment by JackyGao2016** [comment]
HUAWEI data center CloudEngine switch introduce:
http://e.huawei.com/us/products/enterprise-networking/switches/data-center-switches

Huawei CloudEngine  switch ansible module repository: 
https://github.com/HuaweiSwitch/CloudEngine-Ansible/tree/master/library

**Comment by krzysztof-magosa** [comment]
Your code uses Python 2.7 features while Ansible requires code to be 2.4 compliant.

**Comment by JackyGao2016** [comment]
We have tried to pass shippable test case.
Would you like to review the first module of  HUAWEI data center CloudEngine switch? 
Thanks :)

**Comment by JackyGao2016** [comment]
We will PULL REQUEST with clean log

**Pull request closed without merging**
