### PR TITLE
Added icinga service module

### PR DESCRIPTION
**Pull request by t794104**
SUMMARY

This module (icinga2_service) allows the use of the Icinga2 REST API (https://www.icinga.com/docs/icinga2/latest/doc/12-icinga2-api/) to manage the services of a host in Icinga2.

ISSUE TYPE

    New Module Pull Request

COMPONENT NAME

    icinga2_service

ANSIBLE VERSION

    2.6.0

ADDITIONAL INFORMATION

modules done
 - icinga2_host (manage host to monitor)

modules to follow are
 - icinga2_service (manage services to monitor)

All 3 modules together will make it possible for a playbook to make sure the host(s) are monitored, they are down while running the playbook (no alarms are send) and manage the services that need to be monitored.

Please let me know if I can improve / help this along in any way.

### CODE REVIEW

**Comment by nerzhul** [comment]
@t794104 did you plan to add icinga2_apply_service module ? it's far more better than standalone services :)

**Comment by t794104** [comment]
' Apply'  as in 1 service which applies to multiple servers ? the API does not work like that (as far as i can see). Plus i think it's not the 'ansible'  way of writing tasks. I'm configuring 1 host and added  1 (or more) services for that host. 

Ansible will take care that all hosts in the same group using the same role will get the icinga services so no apply is needed... or so i think.

**Comment by nerzhul** [comment]
@t794104 yeah it's possible apply service cannot be done over API as it's not a "apply service" object, it's a runtime object creation into icinga.
Advantage of the apply service method (in template form) is to auto generate sensor based on host facts extracted from ansible to icinga2, or from host groups (i will provide a patch to the missing groups attribute in hosts asap)

**Comment by t794104** [comment]
It's a advantage and a disadvantage; a apply rule could affect more then needed. 
In our case we use these modules in playbooks that do not install Icinga itself. But install applications on servers. So we only want to add/update Icinga for the servers / application that are installed in the playbook nothing more.

**Comment by t794104** [comment]
shipit

**Comment by t794104** [comment]
bot_status

**Comment by t794104** [comment]
@nerzhul do you have time too check this module ?

there is a 'force_check' parameter that forces a check when creating / modifying a service. If it works crooreclty i'll be adding the same to the icinga2_host module.

**Comment by knaapjvd** [comment]
Ship it?

**Comment by t794104** [comment]
Will make a new one with up too date repo

**Pull request closed without merging**
