### PR TITLE
maven_artifact: adding AWS STS session token support

### PR DESCRIPTION
**Pull request by mrcrilly**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`maven_artifect`

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
Without being able to supply and use the AWS STS session token, AWS STS temporary credentials cannot be used with this module. Without providing the session token, STS users will not be able to download protected artifacts.

This PR fixes the issue by introducing the STS session token, should it be supplied to the module, to the boto3 client at the time of instantiation. It does so without introducing a blank session token to the boto3 client, using an expanded `dict`, to avoid unknown edge cases with regards to a blank session token.

### CODE REVIEW

**Comment by tumbl3w33d** [comment]
LGTM, however, I have no experience with AWS, so I can't tell if it's gonna work. Would be great if @ryansb could have a look.

**Comment by tumbl3w33d** [comment]
shipit

**Comment by turb** [comment]
;@mrcrilly I can now join @tumbl3w33d to merge it. Just have to rebase and solve conflicts

**Comment by gundalow** [comment]
@mrcrilly 
Thank you for your PR.
As part of reviewing the backlog of PRs we are looking at PRs older PRs that haven't been updated in a while

Given that:
* Needed a rebase since end of 2017
* This is a feature rather than a bug fix

Therefore I'm going to close this.

If you or anyone else wants to continue with this work then please do feel free to create a fresh PR and `@mention` the previous reviewers in here.

**Pull request closed without merging**
