### PR TITLE
Added force as an option for apt module

### PR DESCRIPTION
**Pull request by jeremysmitherman**

### CODE REVIEW

**Comment by mpdehaan** [comment]
thanks, this will be reviewed for 0.6 shortly

**Comment by mpdehaan** [comment]
logic seems fine, but there are a couple of style problems that we want to avoid to keep the code more maintainable

please break out the one line if / else and the place where you do "force=force == 'yes'" and I'll apply this

**Comment by jeremysmitherman** [comment]
Ok, I've made the requested updates.  Let me know if this isn't what you meant.

**Comment by jeremysmitherman** [comment]
Oops, hey this is broken.  I'm fixing it up.

**Comment by jeremysmitherman** [comment]
Ok, fixed and tested.

**Comment by mpdehaan** [comment]
merge commits shouldn't be in the history -- you should probably start a new branch and be sure to use rebase.

You may want to alias git pull to "git pull --rebase"

This will also allow all of this to be folded into one commit.

**Pull request closed without merging**
