### PR TITLE
Serviceguard

### PR DESCRIPTION
**Pull request by sandrich**
##### SUMMARY
New modules to control a HP ServiceGuard cluster. It comes with 3 modules.

I hope it is ok to put them all in one PR. If not let me know.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
serviceguard_facts - Delivers cluster facts
serviceguard_pkg - Controls cluster packages
serviceguard_node - Controls cluster node

##### ADDITIONAL INFORMATION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/chris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Oct  2 2018, 09:18:58) [Clang 10.0.0 (clang-1000.11.45.2)]
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/107749/42/tests

**Comment by sandrich** [comment]
This will not work except there is a service guard cluster installed. 

Do I need to change the aliases?

**Comment by mattclay** [comment]
Add the `unsupported` alias to the tests then, so they won't run in CI.

**Comment by sandrich** [comment]
I will split it into 3 different modules

**Pull request closed without merging**
