### PR TITLE
Add dhcp support for vmware_vmkernel

### PR DESCRIPTION
**Pull request by Abdul-Anshad-A**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_vmkernel

##### ANSIBLE VERSION
ansible 2.3.0

##### SUMMARY
Added option for STATIC/DHCP IP address during vmkernel port creation.

## Add vmkernel port with static IP address

```
- vmware_vmkernel:
     hostname: esxi_hostname
     username: esxi_username
     password: esxi_password
     validate_certs: False
     vswitch_name: vswitch_name
     portgroup_name: portgroup_name
     vlan_id: vlan_id
     ip_address:
        type: static
        address: ip_address
        subnet_mask: subnet_mask
     enable_mgmt: False
```

## Add vmkernel port with DHCP IP address

```
- vmware_vmkernel:
     hostname: esxi_hostname
     username: esxi_username
     password: esxi_password
     validate_certs: False
     vswitch_name: vswitch_name
     portgroup_name: portgroup_name
     vlan_id: vlan_id
     ip_address:
        type: dhcp
     enable_mgmt: False
```

### CODE REVIEW

**Comment by Abdul-Anshad-A** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3370

**Comment by dericcrago** [comment]
nesting the ip settings under the ip_address dict will break backwards compatibility, right? have you considered making the ``address_type`` a top level arg, defaulting it to 'static', then using ``required_if`` to specify the extra args if ``type == 'static'``?

```python
# example
required_if=[('address_type', 'static', ['ip_address', 'netmask'])]
```

**Comment by jctanner** [comment]
@Abdul-Anshad-A any response to dericcrago's question?

needs_info

**Comment by Akasurde** [comment]
@Abdul-Anshad-A Are you still working on this ? Let me know if not, then I can take over this PR.

**Comment by Akasurde** [comment]
superseded by #33664

**Comment by Abdul-Anshad-A** [comment]
I didn't get a chance to take a look at this due to other commitments.

Thank you for taking this up @Akasurde

**Comment by Akasurde** [comment]
@Abdul-Anshad-A Thanks for your time and contribution. We look forward for your valuable contribution and help to Ansible Project.

**Pull request closed without merging**
