### PR TITLE
yum: Add --security tag to list option

### LINKED ISSUE #73858: [RFE]  yum module cannot list the security update
### Summary

A customer is trying to make a list for security updates like `yum --security list updates`.

However the `security` option is not effective for the `list` option.  For example, 

```
- name: list packages for security updates
  yum:
    list: updates
    security: yes
  register: list_of_updates
```

### Issue Type

Feature Idea

### Component Name

yum

### Additional Information

```yaml (paste below)

```

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
Fixes #73858 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
yum

### CODE REVIEW

**Comment by mkrizek** [comment]
Can you add tests?

**Comment by aminvakil** [comment]
> Can you add tests?

@mkrizek I shall try using unit tests for this functionality, right? Then it should take longer as it's harder for me, but I guess that's inevitable, as I don't think there is an appropriate way to test this via integration tests.

I would appreciate your input on this before getting to work on it.

**Comment by mkrizek** [comment]
I am not sure what we get with unit tests over integrations tests. Unless `rpmfluff` supports creating security packages that we can test against I am not sure we can do much to test the functionality.

cc @relrod

**Comment by aminvakil** [comment]
I was thinking of something like this: https://github.com/ansible/ansible/commit/c1da427a5ec678f052fd2cd4885840c4d761946a#diff-a29eea227bf63d973dd0d26e5be6821d6939845266f93dbde9aee500e571b656


To make sure this task:
```
- yum:
    list: updates
    security: yes
```
results in
```
yum list updates --security
```

**Comment by relrod** [comment]
> I am not sure what we get with unit tests over integrations tests. Unless `rpmfluff` supports creating security packages that we can test against I am not sure we can do much to test the functionality.

A package being a security update or not is a property of the repodata (particularly the `updateinfo`) of the repo it belongs to, rather than the package itself, so I don't think `rpmfluff` can do much here. Usually the way I've been handling tests like this is by manually creating one-off test yum repos and uploading them to our ansible-test s3 bucket. It's not ideal because it precludes people without access to the bucket from generating those kinds of tests, but it's the cleanest solution I've come up with for testing repos that need specific metadata like this.

**Pull request closed without merging**
