### PR TITLE
Logical bug fix in setup module, Incorrectly marking virtual devices as physical.

### PR DESCRIPTION
**Pull request by kavink**
```
Fixing logical error in detecting virtual device.

So In my Centos 5.9 machine, if there is RAID mount ansible will crash, as it cannot find scheduler file. The reason being, this should be a virtual device as there is no "device" folder under e.g. /sys/block/md0/

Here is the crash:

[kk@u1 ansible]$ ansible q3 -m setup -k -u root --tree=/tmp/facts
SSH password:
q3 | FAILED => failed to parse: /sys/block/md0
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1360629441.14-171498703486275/setup", line 1797, in ?
    main()
  File "/root/.ansible/tmp/ansible-1360629441.14-171498703486275/setup", line 1050, in main
    data = run_setup(module)
  File "/root/.ansible/tmp/ansible-1360629441.14-171498703486275/setup", line 1000, in run_setup
    facts = ansible_facts()
  File "/root/.ansible/tmp/ansible-1360629441.14-171498703486275/setup", line 990, in ansible_facts
    facts.update(Hardware().populate())
  File "/root/.ansible/tmp/ansible-1360629441.14-171498703486275/setup", line 312, in populate
    self.get_device_facts()
  File "/root/.ansible/tmp/ansible-1360629441.14-171498703486275/setup", line 439, in get_device_facts
    m = re.match(".*?(\[(.*)\])", scheduler)
  File "/usr/lib64/python2.4/sre.py", line 129, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Kavin, you've got some other stray commits in here.  Make sure you do "git pull --rebase" vs "git pull" and "git merge".

I'll look at cherry-picking the relevant commits though, just something to check out next time.

**Comment by mpdehaan** [comment]
Looks like this was applied on top of the get_devices patch, I'll take a look at making the same changes to the setup module...

**Comment by mpdehaan** [comment]
Ok, took a look at the latest upstream setup module stuff and it already has the virtual later on down as a "1", can you perhaps check it out from a fresh clone and see if you are still having problems, and if so apply on top of that?

Sorry for the confusion!

**Comment by kavink** [comment]
I just checked upstream , it seems incorrect and does not work. 

The default should be "1" , and when it detects its a physical device sets it to "0"

https://github.com/ansible/ansible/pull/2052/files

if re.search("device", folder):
       -  virtual = 1
      +  virtual = 0

Should i redo the pull request ?

**Pull request closed without merging**
