### PR TITLE
ec2_group_facts: Fail correctly when boto3 is not installed

### PR DESCRIPTION
**Pull request by stevekuznetsov**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
`ec2_group_facts`

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@Sodki

**Comment by Sodki** [comment]
shipit

**Comment by stevekuznetsov** [comment]
@bcoca rebased this on current `devel`.

ready_for_review

**Comment by willthames** [comment]
ready_for_review

**Comment by willthames** [comment]
shipit

**Comment by stevekuznetsov** [comment]
@bcoca is anything else necessary for this to go in?

**Comment by stevekuznetsov** [comment]
Why has the bot removed the `shipit` label?

**Comment by stevekuznetsov** [comment]
This commit is super simple and totally necessary -- why is it still in limbo almost two months later?

**Comment by Sodki** [comment]
shipit

**Comment by stevekuznetsov** [comment]
@willthames @bcoca ping

**Pull request merged**
