### PR TITLE
Refactor CLI prompt mode check for network plugins (#63945)

### PR DESCRIPTION
**Pull request by ganeshrn**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/441
##### SUMMARY

* Refactor CLI prompt mode check for network plugins

*  Move the CLI prompt mode check logic from action plugin
   to the controller side with the cliconf plugins.

*  This refactor also allows the network modules
   to initialise the persistent connection with remote device
   only when it is required.

* Fix review comments

(cherry picked from commit c27e47327f902dddf0b93767e387cacdfc12e11f)
(cherry picked from commit ee3f8d28a4c77a8fe90bd37ff9ab8312bb52a873)
(cherry picked from commit e19b94f43b62c011a07ba65db276ed54fb3f1082)

devel:
https://github.com/ansible/ansible/pull/63945
https://github.com/ansible/ansible/pull/64697
https://github.com/ansible/ansible/pull/63014

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

cli/scripts/ansible_connection_cli_stub.py
module_utils/network/common/cfg/base.py
module_utils/network/junos/config/interfaces/interfaces.py
module_utils/network/nxos/argspec/interfaces/interfaces.py
module_utils/network/nxos/config/interfaces/interfaces.py
plugins/action/aireos.py
plugins/action/aruba.py
plugins/action/asa.py
plugins/action/ce.py
plugins/action/cnos.py
plugins/action/dellos10.py
plugins/action/dellos6.py
plugins/action/dellos9.py
plugins/action/enos.py
plugins/action/eos.py
plugins/action/ios.py
plugins/action/iosxr.py
plugins/action/ironware.py
plugins/action/junos.py
plugins/action/nxos.py
plugins/action/vyos.py
plugins/cliconf/init.py
plugins/cliconf/aireos.py
plugins/cliconf/aruba.py
plugins/cliconf/ce.py
plugins/cliconf/cnos.py
plugins/cliconf/dellos10.py
plugins/cliconf/dellos6.py
plugins/cliconf/dellos9.py
plugins/cliconf/enos.py
plugins/cliconf/eos.py
plugins/cliconf/ios.py
plugins/cliconf/iosxr.py
plugins/cliconf/ironware.py
plugins/cliconf/junos.py
plugins/cliconf/nxos.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Review by danielmellado — APPROVED** [review]
LGTM, Thanks for this ganesh!

**Pull request merged**
