### PR TITLE
pamd: fix issue with trailing commas in module_arguments 

### LINKED ISSUE #28096: pamd eats trailing comma in module_arguments
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION
```
ansible 2.3.1.0
config file =
configured module search path = Default w/o overrides
python version = 2.7.13 (default, March 13 2017, 20:56:15) [GCC 5.4.0]
```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If module_arguments has a trailing comma, the resulting line in the module stack has an empty string.

##### STEPS TO REPRODUCE
pam_access.so requires the argument "listsep=," in order to parse Active Directory groups properly, as they often contain spaces (e.g., "Domain Users").  pamd is unable to add this argument correctly; quoted strings and escape sequences have no effect. 

For example, attempting this task on Ubuntu fails:

```yaml
- name: Ensure specific arguments are present in a rule
  pamd:
    name: common-account
    type: account
    control: required
    module_path: pam_access.so
    module_arguments: "listsep=,"
    state: args_present
```

##### EXPECTED RESULTS
The task should add "listsep=," to the pam_access.so line.

##### ACTUAL RESULTS
pamd adds "listsep= ".

Sorry, verbatim output not available; source is on a closed network.

### LINKED ISSUE #28225: pamd broke /etc/pam.d/su file after task
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pamd

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
But I use latest version from https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/pamd.py
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7.3
##### SUMMARY

pamd broke /etc/pam.d/su file after task
##### STEPS TO REPRODUCE

```yaml
  - name: Disable switch for domain users
    pamd:
      name: su
      type: auth
      control: sufficient
      module_path: pam_rootok.so
      new_type: auth
      new_control: required
      new_module_path: pam_succeed_if.so
      module_arguments: 'uid < 40000'
      state: before
```

##### EXPECTED RESULTS

Good /etc/pam.d/su file:
```
#%PAM-1.0
auth            required        pam_succeed_if.so uid < 40000
auth            sufficient      pam_rootok.so
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth           sufficient      pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
#auth           required        pam_wheel.so use_uid
auth            substack        system-auth
auth            include         postlogin
account         sufficient      pam_succeed_if.so uid = 0 use_uid quiet
account         include         system-auth
password        include         system-auth
session         include         system-auth
session         include         postlogin
session         optional        pam_xauth.so
```
##### ACTUAL RESULTS

Bad /etc/pam.d/su file:

```
#%PAM-1.0
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth           sufficient      pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
#auth           required        pam_wheel.so use_uid
auth            required        pam_succeed_if.so uid < 40000
auth            sufficient      pam_rootok.so
auth            substack        system -auth
auth            include postlogin

account         sufficient      pam_succeed_if.so uid = 0 use_uid quiet
account         include system -auth

password        include system -auth

session         include system -auth
session         include postlogin
session         optional        pam_xauth.so
```
Spaces in system-auth module name.

### PR DESCRIPTION
**Pull request by kevensen**
##### SUMMARY

Fixes #28225 and fixes #28096.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION

```
ansible 2.4.0 (pamd-fixes b76fe18799) last updated 2017/08/16 10:40:01 (GMT -400)
  config file = /etc/ansible/ansible.cfg
```

### CODE REVIEW

**Comment by kevensen** [comment]
shipit

**Comment by hargut** [comment]
It would be very helpful if the PR could be merged, since this bug might lead to loosing system access after running an ansible role which uses pamd.

If the role touches sshd/login one could be in trouble after updating from 2.3.x to 2.4.x and running a role which did work properly before.

**Comment by kevensen** [comment]
@hargut Thanks for your input.  

Any and all, please let me know if this PR needs further work.

**Comment by resmo** [comment]
shipit

**Pull request merged**
