### PR TITLE
add option to ansible-vault to read new password from file for rekey

### PR DESCRIPTION
**Pull request by amenonsen**
The --new-vault-password-file option works the same as
--vault-password-file but applies only to rekeying (when
--vault-password-file sets the old password). Also update the manpage
to document these options more fully.

### CODE REVIEW

**Comment by amenonsen** [comment]
Updated to resolve conflicts after #11336 was merged.

**Comment by amenonsen** [comment]
I've pushed a second commit that fixes a problem I discovered later: an overly-strict `len(self.args)` check was defeating the good intentions of all but the create subcommand to handle multiple file arguments. I've tested that the second commit does fix the problem, e.g. `ansible-vault rekey a.yml b.yml c.yml` just works.

**Comment by amenonsen** [comment]
I see @bcoca cherry-picked the bugfix, so I've rebased and dropped that commit from this PR.

**Comment by abadger** [comment]
Thanks crab!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
