### PR TITLE
parted module

### PR DESCRIPTION
**Pull request by bennojoy**
This PR adds support for parted module, which can be used to add partitions to physical disks. partitions can be gpt, msdos. the partitions can be on a specified device or on any uninitialized disks.

### CODE REVIEW

**Comment by mpdehaan** [comment]
In queue for review!

Could benefit from increased whitespace between some lines and comments, and I'm noticing some tabs or inconsistent indentation in there.

When we declare dicts, we also want to use the "dict()" constructor in most places of the code because it's clear with respect to quoting.

I'm also curious how it works when a disk name isn't specified (as per examples)?

We should also pass variables to functions rather than using globals if possible.

imports should happen towards the top of the file.

Those are just a few initial notes/questions.

Thanks!

**Comment by bennojoy** [comment]
Hi Michael,

If the disk name is not specified, then the module searches for any disk
that is not initialized and creates the partition on that disk, this would
be beneficial for cloud instances when attached with a external disk and
the use doesnt exactly know the device name.

Regards,
Benno

**Comment by risaacson** [comment]
Hey Benno,

Just trolling through the issues and this one popped up and I am surprised that it hasn't been covered.

From reading the code and your most recent comment I have a concern though. Having the default behavior be to shotgun format all of the unformatted disks could cause more problems than what it is worth. Default behavior like this fits the cloud closely but could be dangerous in a traditional enterprise environment.

What about having the default behavior if a device was not specified to fail (or more likely to pass through as when no new disks are found) but to continue if a boolean of next_disk or all_disks is defined? This way there is a little bit more control over the process.

Good job on the module though. I have some people that I will bring this up to whose lives it could make easier.

-r

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Pull request closed without merging**
