### PR TITLE
Fix include_role variable exposure

### LINKED ISSUE #21890: include_role does not expose variables to rest of playbook
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT
OS: CentOS7, but shouldn't matter.

##### SUMMARY
When including a role using include_role its vars do not become available to the rest of the playbook. This does work when using the regular roles definition.

##### STEPS TO REPRODUCE
A minimal test-case lives here: https://github.com/wouterhund/demo-ansible-include_role-bug/blob/master/bad-playbook.yml https://github.com/wouterhund/demo-ansible-include_role-bug/blob/master/roles/testrole/vars/main.yml

The actual code that triggers the issue:

```yaml
---
- hosts: localhost

  tasks:
    - include_role:
        name: testrole
    - debug: msg="{{some_var}}"
```

`roles/testrole/vars/main.yml`
````yaml
---
some_var: "Hello world!"
````

##### EXPECTED RESULTS
I would expect `good-playbook.yml` and `bad-playbook.yml` from the linked github to work identically, however `bad-playbook.yml` fails. I expect variables defined within an included role to be made available to the rest of the playbook.

For the example above I'd expect it to pass and display "Hello world!"

##### ACTUAL RESULTS
```
» ansible-playbook -vvvv bad-playbook.yml                                                                                                                1 ↵
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: bad-playbook.yml *****************************************************
1 plays in bad-playbook.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009 `" && echo ansible-tmp-1487936470.27-110880382737009="` echo ~/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp017eF_ TO /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/ /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/setup.py; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1487936470.27-110880382737009/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [testrole : debug] ********************************************************
task path: /home/vagrant/demo-ansible-include_role-bug/roles/testrole/tasks/main.yml:2
ok: [localhost] => {
    "msg": "Hello world!"
}

TASK [debug] *******************************************************************
task path: /home/vagrant/demo-ansible-include_role-bug/bad-playbook.yml:7
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'some_var' is undefined\n\nThe error appears to have been in '/home/vagrant/demo-ansible-include_role-bug/bad-playbook.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n        name: testrole\n    - debug: msg=\"{{some_var}}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}
	to retry, use: --limit @/home/vagrant/demo-ansible-include_role-bug/bad-playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

### PR DESCRIPTION
**Pull request by kiorky**
##### SUMMARY
This fixes #21890 where include_role doesnt bring for the play the variables from underlying roles
I m splitting this PR in multiple more scopped PRS before closing it.
SEE:
- #35167
- #32565
- #35164 
- #35166
- #35163

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0 (devel fec360551b) last updated 2017/11/04 03:08:01 (GMT +200)
  config file = /home/kiorky/projects/mc/x/x/local/corpusops.bootstrap/hacking/vagrant/ansible.cfg
  configured module search path = [u'/home/kiorky/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kiorky/projects/mc/corpusops/corpusops.bootstrap/venv/src/ansible/lib/ansible
  executable location = /home/kiorky/projects/mc/corpusops/corpusops.bootstrap/venv/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by kiorky** [comment]
cc @regilero

**Comment by kiorky** [comment]
ready_for_review

**Comment by jmehnle** [comment]
So close to the finish line! :-) @kiorky, can you please fix up the remaining issues (failing pep8 test, merge conflicts)?

**Comment by kiorky** [comment]
the merge conflict appeared just recently, the pep8 and other things were already fixed for a very long time.
Let me rebase the PR.

**Comment by kiorky** [comment]
rebase pushed, let's see CI.

**Comment by kiorky** [comment]
See, @jmehnle ;-)

**Comment by kiorky** [comment]
Failure seems really unrelated ...
@bcoca why there isnt any update status on the PR, what is missing for you to start review ?

**Comment by kiorky** [comment]
cc @jimi-c

**Comment by kiorky** [comment]
Closed as splitted to
- #35131
- #35107 
- #35132 
- #35133
- #35134

**Pull request closed without merging**
