### PR TITLE
Docs: fix related to platform content #79794

### LINKED ISSUE #79794: Change the note on AAP page to link to cloud options
### Summary

The note on[ this page](https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/reference_appendices/tower.rst#L8) is outdated. It should instead say something like:
"  Red Hat Ansible Automation Platform is available on multiple cloud platforms. See `Ansible on Clouds <https://access.redhat.com/documentation/en-us/ansible_on_clouds/2.x.>`_. for details.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/reference_appendices/tower.rst

### Ansible Version

```console
$ ansible --version
2.15
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by prasadpatil49**
##### SUMMARY

Fixes #79794

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs/docsite/rst/reference_appendices/tower.rst

##### ADDITIONAL INFORMATION

Added reference of  ansible on cloud product documentation

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM

**Comment by oraNod** [comment]
@prasadpatil49 Thanks for the docs fix. I think it's fine but I have a housekeeping question for @samccann

@samccann What do you think about labelling PRs like this one that link or reference downstream? I also wonder about having ansible on clouds in the git history.

**Comment by samccann** [comment]
@oraNod - We could ask the core team for a label I suppose.  As for ansible on clouds in the git history etc - The original note was a specific request from RH marketing so I felt it best to just update the old note. It's not the first or only instance of mentioning downstream components in the docs. As you see, we have an entire AAP page (and an AH page etc). Not to mention marketing advertisements in the lower-left corner... and marketing banner requests ..etc etc.

**Comment by oraNod** [comment]
> @oraNod - We could ask the core team for a label I suppose. As for ansible on clouds in the git history etc - The original note was a specific request from RH marketing so I felt it best to just update the old note. It's not the first or only instance of mentioning downstream components in the docs. As you see, we have an entire AAP page (and an AH page etc). Not to mention marketing advertisements in the lower-left corner... and marketing banner requests ..etc etc.

Yes, there's a lot of downstream AAP content in community. My intent would be to improve how that gets into the docs and be a bit stricter about clearly separating downstream and community. Maybe it's just my own opinion but this feels like we're mixing the streams too much.

**Comment by oraNod** [comment]
Thanks @prasadpatil49

**Pull request merged**
