### PR TITLE
add test manipulation ability to Singleton

### PR DESCRIPTION
**Pull request by nitzmahone**
##### SUMMARY

* add set/get/clear staticmethods to Singleton metaclass so tests can inspect/manipulate Singleton state without worrying about name munging, etc
* add tests for Singleton itself
* update tests that were manipulating Singleton state to use new methods on the metaclass instead

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
singleton.py

### CODE REVIEW

**Comment by sivel** [comment]
I have mixed feelings on this.  I didn't really want someone being able to easily reset the singleton. Name munging was important, to prevent people from doing this.

In the end though it was really just lack of ease due to obscurity.

**Comment by nitzmahone** [comment]
A middle ground might be to move this functionality to test infrastructure- I just don't like seeing the direct sampling/manipulation of the munged Singleton values sprinkled all over the tests...

**Comment by abadger** [comment]
yeah, I agree, I don't think this should be part of production API since it destroys the concept of the class.  Putting it into test infrastructure will consolidate the code to a single location while keeping it away from being used in non-test code.

**Comment by nitzmahone** [comment]
handled other ways, closing

**Pull request closed without merging**
