### PR TITLE
Fix/ansible debug add host loop

### LINKED ISSUE #84157: ANSIBLE_DEBUG with add_host in a loop tracebacks
### Summary

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        name: foo
      loop:
        - 1
```

```
ANSIBLE_DEBUG=1 ansible-playbook playbook.yml
```

```pytb
Traceback (most recent call last):
  File "/Users/sivel/venvs/ansibledev/bin/ansible-playbook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/cli/playbook.py", line 240, in main
    PlaybookCLI.cli_executor(args)
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/cli/__init__.py", line 659, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/cli/playbook.py", line 156, in run
    results = pbex.run()
              ^^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/executor/playbook_executor.py", line 190, in run
    result = self._tqm.run(play=play)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/executor/task_queue_manager.py", line 348, in run
    play_return = strategy.run(iterator, play_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/plugins/strategy/linear.py", line 231, in run
    results.extend(self._wait_on_pending_results(iterator))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/plugins/strategy/__init__.py", line 826, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/plugins/strategy/__init__.py", line 172, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/plugins/strategy/__init__.py", line 700, in _process_pending_results
    all_task_vars = combine_vars(found_task_vars, item_vars)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivel/projects/ansibledev/ansible/lib/ansible/utils/vars.py", line 91, in combine_vars
    result = a | b
             ~~^~~
TypeError: unsupported operand type(s) for |: 'VarsWithSources' and 'dict'
```

This is an extension of what was fixed in https://github.com/ansible/ansible/pull/79764

### Issue Type

Bug Report

### Component Name

lib/ansible/utils/vars.py

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

N/A

### Steps to Reproduce

See above

### Expected Results

No TB

### Actual Results

```console
TB
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by dangoncalves**
##### SUMMARY

While processing loop item in _process_pending_results (in StrategyBase), we retrieve all_task_vars if task is add_host or add_group and merging them with item_vars. We want to avoid using merge operator in this case.

Fixes #84157

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by Akasurde** [comment]
@dangoncalves Thanks for the contribution. Could you please change the base branch for this PR to `devel`? PRs are merged in `devel` and then backported to subsequent releases.

**Comment by mattclay** [comment]
I switched this PR to the `devel` branch to get it out of the backport merge queue. However, this results in a large number of unrelated commits showing up, so I'm closing this PR.

@dangoncalves If you're still interested on working on this issue, please open a new PR against the `devel` branch.

**Comment by dangoncalves** [comment]
Hello @mattclay and @Akasurde,

As explained on [the original issue](https://github.com/ansible/ansible/issues/84157), this issue does not appears on devel. What is the process to merge it on relevant branches?

**Comment by mattclay** [comment]
@dangoncalves What is the relationship between this PR and the linked issue? That issue is focused on the following code:

https://github.com/ansible/ansible/blob/95e3af3e0f6a054988591913a46c95b6aff94cb5/lib/ansible/utils/vars.py#L87

However, this PR makes changes to the base strategy plugin instead.

**Comment by dangoncalves** [comment]
@mattclay the traceback on the issue takes origin in the strategy plugin (just look a few lines above). In this file, at line 700, there is a call to `combine_vars` with 2 parameters `item_vars` and `found_task_vars` which have these types:
```python
type(item_vars)
<class 'dict'>
type(found_task_vars)
<class 'ansible.vars.manager.VarsWithSources'>
``` 
As you can see these variables are incompatible with merge operator. This PR fix that.

**Comment by mattclay** [comment]
@dangoncalves The change in this PR breaks the hash merge feature by removing the usage of `combine_vars`, rather than fixing the implementation of `combine_vars` as suggested in https://github.com/ansible/ansible/issues/84157#issuecomment-2432970848

**Pull request closed without merging**
