### PR TITLE
docker: rename docker_*_facts -> docker_*_info

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
It has been decided that [`_facts` modules should always return `ansible_facts`](https://meetbot.fedoraproject.org/ansible-meeting/2019-03-05/ansible_core_irc_public_meeting.2019-03-05-19.01.log.html#l-118), and that [`_facts`-like modules which don't return `ansible_facts` should be called `_info`](https://meetbot.fedoraproject.org/ansible-meeting/2019-03-19/ansible_core_irc_public_meeting.2019-03-19-19.05.log.html#l-118). Since most docker_*_facts modules have just been added to Ansible for 2.8, this is the perfect time to adjust to the new names :)

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docker_*_facts
docker_*_info

### CODE REVIEW

**Comment by felixfontein** [comment]
This module actually doesn't add any new module, but renames a bunch of modules.

**Comment by felixfontein** [comment]
What I haven't done so far is adjusting return values to not contain `_facts`. I'm not sure whether renaming them would be a good idea. Any opinions on this? Also, I'd suggested to get this merged quickly if no big issues show up, so we can fix potential small issues later (and separately), as this PR definitely won't automerge (since it's docs, and it's revision_needed because ansible thinks it contains several new modules).

ready_for_review

**Comment by WojciechowskiPiotr** [comment]
I don't mind renaming the returned value as long as it is made for all modules including existing.

**Comment by WojciechowskiPiotr** [comment]
shipit

**Comment by felixfontein** [comment]
Here's an overview of existing return value names for all docker_* volumes:
- docker_compose
  - **service_facts** *(new name in 2.8)*
  - actions
- docker_config
  - config_id
- docker_container_info *(new module for 2.8)*
  - exists
  - container
- docker_container
  - container
- docker_host_info *(new module for 2.8)*
  - can_talk_to_docker
  - **host_facts**
  - volumes
  - networks
  - containers
  - images
  - disk_usage
- docker_image_info
  - images
- docker_image
  - image
- docker_login
  - login_results
- docker_network_info *(new module for 2.8)*
  - exists
  - network
- docker_network
  - network
- docker_node_info *(new module for 2.8)*
  - nodes
- docker_node *(new module for 2.8)*
  - **node_facts**
- docker_prune *(new module for 2.8)*
  - containers
  - containers_space_reclaimed
  - images
  - images_space_reclaimed
  - networks
  - volumes
  - volumes_space_reclaimed
  - builder_cache_space_reclaimed
- docker_secret
  - secret_id
- docker_stack *(new module for 2.8)*
  - stack_spec_diff
- docker_swarm_info *(new module for 2.8)*
  - can_talk_to_docker
  - docker_swarm_active
  - docker_swarm_manager
  - **swarm_facts**
  - nodes
  - services
  - tasks
- docker_swarm
  - **swarm_facts**
  - actions
- docker_swarm_service
  - swarm_service
  - changes
  - rebuilt
- docker_volume_info *(new module for 2.8)*
  - exists
  - volume
- docker_volume
  - volume

The only name ending in `_facts` which isn't new (of some kind) is the return value of docker_swarm, i.e. that one we can't really rename. For the others, except `docker_swarm_info` (which should have a close enough return name to `docker_swarm` if possible), I'll create new PRs for potential renaming once this is merged.

**Comment by dariko** [comment]
shipit

**Comment by gundalow** [comment]
bot_status

Not sure where needs revision is coming from

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
@WojciechowskiPiotr @dariko thanks for reviewing!
@gundalow thanks for merging!

**Pull request merged**
