### PR TITLE
Expand the user home folder in the key_file argument of the git module

### LINKED ISSUE #7533: git module key_file= option doesn't interpret the ~/ as $HOME
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Ubuntu 12.04
##### Summary:

git module key_file= option doesn't interpret the ~/ as $HOME
##### Steps To Reproduce:

```
- git: repo=ssh://git@bitbucket.org/xxx/yyyy.git dest=~/compile key_file=~/.ssh/bitbucket_app -vvvv
```
##### Expected Results:

read the keyfile and checkout from git :) 
##### Actual Results:

```
<localhost> REMOTE_MODULE git repo=ssh:********@bitbucket.org/xxx/yyy.git dest=~/compile key_file=~/.ssh/bitbucket_app
failed: [localhost] => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "item": "", "rc": 128}
stderr: Warning: Identity file ~/.ssh/bitbucket_app not accessible: No such file or directory.
```

### PR DESCRIPTION
**Pull request by astorije**
This fixes #7533 by using `expanduser` and `abspath`.

Let me know if you have any comment or suggestion, and please be gentle with me: this is my first contribution to this awesome piece of software :)

### CODE REVIEW

**Comment by astorije** [comment]
@mpdehaan, since this PR doesn't have big consequences and is basically a one-liner, is there any chance it can get P2 flag instead of P3? Not pushing anything though :) Thanks!

**Comment by perehonchuk** [comment]
Please merge it :)

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by astorije** [comment]
@mpdehaan Since this PR has been opened a few months ago, I noticed last week that I needed to update it to merge the latest changes. I will re-submit this PR very soon once it is done, I expect to do that before the end of the week. Considering this is just a one-liner, I hope it will be merged soon after.

**Pull request closed without merging**
