### PR TITLE
🏗 Support BuildRequests

### LINKED ISSUE #52887: OpenShift build operations as standalone module
##### SUMMARY
With the current `k8s` module, it is not possible to request new image builds on OpenShift due to  underlying APIs in the openshift-rest-client (see https://github.com/openshift/openshift-restclient-python/issues/245). Since these interactions are not aligned to Kubernetes/OpenShift standard "CRUD" operations, a separate module to handle these special object interactions is required in order to manage builds via Ansible. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* `k8s`
* `k8s_scale` (as a reference)

Most typical configuration management of OpenShift can be handled by the core `k8s` module. However, for build operations, that module is incomplete (or rather, it cannot manage build operations as standard resource definitions). Similar to `k8s_scale`, an `openshift_build` module is in order. 

AFAIK, there's no corresponding object types in plain Kubernetes. Alternatives exist which do leverage running image creation inside a pod (https://github.com/GoogleContainerTools/kaniko) but I consider that outside the scope of this feature.

##### ADDITIONAL INFORMATION
In order to manage a complete application lifecycle on OpenShift, the ability to trigger (create) and wait on (read) individual instantiations of builds is required. For our particular use case, the workflow goes like this:

1. Create/update an OpenShift `BuildConfig` via a standard resource definition (rendered from a Jinja template) and the core `k8s` module:

    ```yaml
    - name: Apply changes to BuildConfig
      k8s: 
        src: "../rendered/build/{{ app_to_build }}-buildconfig.yml"
        namespace: "{{ target_namespace }}"
        state: present
    ```
2. Create a `BuildRequest`, which starts an individual build based off of the `BuildConfig`. Currently, this is accomplished via `oc start-build` on the command line or `POST /oapi/v1/namespaces/{{ target_namespace }}/buildconfigs/{{ target_buildconfig }}/instantiate`. **This is currently not possible via k8s module** due to issue linked above. [Further details via OpenShift docs](https://docs.openshift.com/container-platform/3.9/rest_api/oapi/v1.BuildConfig.html#Post-oapi-v1-namespaces-namespace-buildconfigs-name-instantiate). We're using a workaround with the `uri` module to simulate an HTTP POST that an `oc start-build` would perform against the API.
   
    ```yaml
    - name: Create BuildRequest to start a new build
       uri:
         url: "{{ target_url }}/oapi/v1/namespaces/{{ target_namespace }}/buildconfigs/{{ target_buildconfig }}/instantiate"
         method: POST
         return_content: yes
         status_code: 201
         body: "{{ lookup('file', '{{ target_buildconfig }}-buildrequest.yml') | from_yaml | to_nice_json }}"
         body_format: json
         headers: 
           Authorization: "Bearer {{ kubernetes.auth.api_key }}"
       register: buildrequest_response
    ```

   Template
    ```yaml
    apiVersion: v1
    kind: BuildRequest
    metadata:
      name: {{ target_buildconfig }}
    triggeredBy:
      - message: "Manually triggered via Ansible"
    dockerStrategyOptions: {}
    sourceStrategyOptions: {}
    ```

3. Using `k8s_facts` or `k8s`, verify a build completes.

   ```yaml
    - name: Check build completion status
      k8s:
        api_version: "build.openshift.io/v1"
        kind: "Build"
        name: "{{ buildrequest_response.json.metadata.name }}"
        namespace: "{{ target_namespace }}"
      register: new_build_status
      retries: 20
      delay: 15
      until: new_build_status.result.status.phase == 'Complete'
    ````
4. Create/update `DeploymentConfig`/`Deployment` or any other standard Kubernetes/OpenShift pod rollout object to consume the new image. 
5. Repeat ad nauseam for additional namespaces/clusters as part of a deployment pipeline, insert integration testing via CI, etc. 

For additional context, please see linked issue. 
https://github.com/openshift/openshift-restclient-python/issues/245

### PR DESCRIPTION
**Pull request by tumido**
##### SUMMARY
Add support for `BuildRequest` in `k8s`. 
Fixes: #52887 

##### ISSUE TYPE
- Bugfix/Feature Pull Request

##### COMPONENT NAME
Module: `k8s`

##### ADDITIONAL INFORMATION
Slight modification in `create_project_request` allows for creating any type of request if the subresource mapping is specified in `execute_module` when looking up the resource (this may be simplified if support for other subresources is needed).

Tasks like the one bellow are now supported:
```
- name: Test play
  hosts: localhost
  connection: local
  tasks:
  - name: Trigger a build
    k8s:
      namespace: <NAMESPACE>
      state: present
      definition:
        kind: BuildRequest
        apiVersion: build.openshift.io/v1
        metadata:
          name: <BUILD_CONFIG_NAME>
```

(`ProjectRequest` is not broken by this, however I couldn't locate any tests for this logic. If needed and you can point me to any existing tests, I can extend those to cover this new scenario as well.)

cc @chouseknecht @fabianvf

### CODE REVIEW

**Comment by Akasurde** [comment]
@geerlingguy Do you think this would go into https://github.com/ansible-collections/kubernetes/tree/master/plugins?

**Comment by tumido** [comment]
Should I open the PR against the ansible-collections instead/as well? It seems to be the same codebase, it should be straightforward to cherry pick.

**Comment by geerlingguy** [comment]
@tumido / @Akasurde - Anything relating to the k8s modules (besides major bug fixes) should be filed against the Kubernetes collection at this point.

**Comment by tumido** [comment]
@geerlingguy :+1:  Thanks, I'll file it against that repo then.

**Pull request closed without merging**
