### PR TITLE
Fixes #3539 "win_robocopy does not return changed properly"

### LINKED ISSUE #3539: Bug in Conditional Include
Hi,

I know that when using conditionals on an include, 'All the tasks get evaluated, but the conditional is applied to each and every task'.  However this breaks when some of that tasks register variables and other tasks in the group use those variable.

Example:

main.yml:

```
- include: extra.yml
  when: do_extra is defined
```

extra.yml:

```
- name: check if we can do task A
  shell: check_if_task_A_possible
  register: A_possible
  ignore_errors: yes

- name: task A
  shell: run_task_A
  when: A_possible.rc == 0
```

Now if you run main.yml and 'do_extra' is not defined, the run will fail on 'task A'  because when the 'when' condition is evaluated, the variable A_possible will not exist.

It is not sufficient to just add the top-level include conditional above the other because right now it looks like the two conditions are compounded and tested together which will still fail because A_possible is not defined.  I think you would have to run the file level conditional before the task level ones to keep this from happening.

### PR DESCRIPTION
**Pull request by sherlockmatt**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_robocopy

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /ansible/ansible_config
  configured module search path = Default w/o overrides
```

##### SUMMARY

Fixes #3539 "win_robocopy does not return changed properly":
Remove the win_robocopy object from $result. This brings the code in line with the documentation, and correctly sets the changed attribute.

BEFORE:
```
ok: [x.x.x.x] => (item=path/to/file.ext) => {
    "changed": false,
    ...
    "win_robocopy": {
        "changed": true
    },
    ...
```

AFTER:
```
changed: [x.x.x.x] => (item=path/to/file.ext) => {
    "changed": true,
    ...
```

I can't copy and paste from my ansible machine so I've manually typed a shortened output. It should still be enough to get the point though.

Also worth noting that this doesn't fix #3498, that will still need to be merged.

### CODE REVIEW

**Comment by sherlockmatt** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3540

**Comment by blakfeld** [comment]
shipit

**Comment by mattduguid** [comment]
We are hitting this issue, can you please confirm where I can find the version its fixed in so that I can confirm we are on it. In the mean time have worked around it with "failed_when: false" Thanks MD

**Comment by sherlockmatt** [comment]
It's definitely in 2.3, I'm not sure about 2.2. Check in the top of the file to see if the $result array contains another array or not. If there's a sub-array inside $result, then you're on the old version.

That's the best I can do, hopefully that helps :)

**Comment by mattduguid** [comment]
I can confirm this is fixed in 2.3.1.0, thanks

**Pull request merged**
