### PR TITLE
Add support for generic $XXXX() to call $LOOKUP(xxxx,....)

### PR DESCRIPTION
**Pull request by jpmens**
Attempt to generalize `$LOOKUP(aaa,...)` as `$AAA(...)` as discussed on IRC and in #1578

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not sure I'm comfortable with matching any $UPPERCASESTRING followed by parens.   It would seem better to programatically build the regex out of all possible module names, and match only those.

**Comment by jpmens** [comment]
This is way over my capabilities ... 
I can iterate over `utils.plugins.lookup_loader.all()` but I can't find the module names:

``` python
for jp in utils.plugins.lookup_loader.all():
       print jp.class_name
```

throws an exception. Anybody have a hint how I can obtain the names of the lookup plugins?

**Comment by mpdehaan** [comment]
Likely x.**class**.name or **name**, not looking at docs right now

I really should email the list about how to use the debugger, will do that!

-- Michael

**Comment by jpmens** [comment]
Thanks for the debugger info, but exceeds my current capabilities. Now, if @dhozac were around, he'd probably fix this in a jiffy...

**Comment by mpdehaan** [comment]
There is a secret lab in Siberia that is working on cloning him for this
purpose.

**Comment by jpmens** [comment]
Closing this because @dhozac thankfully seems to have a Pull Request which does this.

**Pull request closed without merging**
