### PR TITLE
Add ability to define Resource Group for Security Group for Azure NIC creation

### PR DESCRIPTION
**Pull request by marc-sensenich**
##### SUMMARY

Allows for the creation of Network Interfaces in Azure with references to Network Security Groups in a different Resource Group

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

`azure_rm_networkinterface`

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by marc-sensenich** [comment]
ready_for_review

**Comment by yuwzho** [comment]
duplicate_of #38643

**Comment by marc-sensenich** [comment]
@yuwzho missed that one, thank you!

**Comment by yuwzho** [comment]
@marc-sensenich you r welcome. Different implementation from yours. Current behvaior is the security group accept both `<str> name`, `<str> resource id` or a `dict` which contains `resource group` and `name` property to identify a NSG from other resource group. 

We (MS ansible team and RedHat team) arrived this aggrement a few days earlier, and want to apply to all the resource reference. 😄

**Pull request closed without merging**
