### PR TITLE
ansible-pull

### PR DESCRIPTION
**Pull request by sfromm**
Related to issue #158.  As discussed there, this is a bit problematic because it may run a play 3 times.  This is because it resets the host_list in lieu of using override_hosts.  The latter would run all plays against any given host.  That would require a host-specific git repository instead of one that is generic to one's entire site.

Comments/Feedback welcome.  :-)

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ok, so ansible pull can be greatly simplified.  It shouldn't be an ansible script, but just a bash script, and this gets rid of your concern about running it 3 times I'm pretty sure.   You could transfer the ansible host file as part of the process so the host knows what groups it is in, right?

ansible_pull.sh is the result of a template that basically does:

rm -rf gitdir
cd gitdir
git clone foo # into gitdir
ansible-playbook foo/local.yml --connection=local > /var/log/wherver 2>&1 

Thoughts?

**Comment by jkleint** [comment]
I'd imagine more folks have NFS set up than git.  It'd be nice to pull from a file instead of a repo.  I'm guessing NFS is better suited for being hammered by thousands of nodes than git (which is generally over ssh).  Maybe you could have an ansible-pull-git, ansible-pull-nfs, ansible-pull-bittorrent... (Hey, Facebook does it!)

**Comment by mpdehaan** [comment]
meh.

Version controlling your manifests for auditing purposes is an important practice to follow. 

Also, it's not true that git is generally done over SSH for read only access, it works fine over http:// or git:// and that's the way most people do it.

**Comment by sfromm** [comment]
jkleint, if not using git, you can just run _ansible-playbook -c local /path/to/playbook.yml_.  

mpdehaan, various thoughts:
- One nitpick: trashing the git directory every run would create a lot of work.  One repository of mine has quite a bit of history and would take a fair amount of time to clone every N minutes.
- A bash script is certainly doable.  I thought doing it in python would allow more logging flexibility.  However, the logging I'm still thinking about should probably go somewhere in callbacks.py.
- The problem of how many times a playbook may run against a host partly depends on whether one can expect an 'authoritative' inventory file on all nodes.  If you can, this problem goes away.  I was operating under the impression that it may not be there, which led to my attempt to (sort of) recreate it locally using host_list.  If the ansible-pull.yml playbook is updated to force the inventory file to all hosts _or_ if it is present in the repository, this problem becomes a moot point.

I'll update my patches and resubmit.

**Comment by mpdehaan** [comment]
(A) Point, git clone on a LARGE repo is slow, true.  That being said, my concern was what happens if we want it to be super reliable, and something goes wrong in the pull and requires a merge.  I wanted it to always suck down successfully.   Maybe some force options are sufficient, I don't know.

(B) I was hoping it wouldn't be something else using the Runner API to maintain in the Ansible codebase.  I'm fine with basic Python, but I don't think it needs to use Ansible's git module?  Maybe I shouldn't care though...

(C)  The inventory file can probably just be up to date with respect to the last time you ran the "configure ansible pull" playbook

**Comment by sfromm** [comment]
Regarding A) I seem to recall some options for pull that would reconcile a conflict one way or other.  Regarding B, I rather liked the idea of using ansible's git module to do the work.  What if it were upgraded to handle such a conflict?

Regarding C, agreed.

**Comment by sfromm** [comment]
Okay, I partly take back point B.  git pull has a --ff or --no-ff option.  The man page says:

```
   --ff, --no-ff
       Do not generate a merge commit if the merge resolved as a
       fast-forward, only update the branch pointer. This is the default
       behavior of git-merge.

       With --no-ff Generate a merge commit even if the merge resolved as
       a fast-forward.
```

That would still be helpful in this case.  There are other things you can do such as _--strategy=ours_ for merging that would always prefer the local version.

**Comment by mpdehaan** [comment]
I think we always want the remote.     My attention is too divided to
take this on ATM but here's the Puppet VCS repo type, which is a
feature request I put in while working for PL --
https://github.com/puppetlabs/puppet-vcsrepo -- the implementation is
not super clear, but there may be some lessons to be had from it.
but use your judgement of course.

On Tue, May 1, 2012 at 6:11 PM, Stephen Fromm
reply@reply.github.com
wrote:

**Comment by mpdehaan** [comment]
also, I really really really only want to do git :)

**Comment by sfromm** [comment]
Updated ansible-pull.  Not a bash script, but not far removed.  Let me know.  :-)

**Comment by mpdehaan** [comment]
nice, will review in the next day or so.   thanks!  nice work!

**Pull request merged**
