### PR TITLE
PostgreSQL modules: move params mapping from main to connect_to_db() function Backport/2.8/55799

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
PostgreSQL modules: move params mapping from main to connect_to_db() function
Backporting of [#55799](https://github.com/ansible/ansible/pull/55799)

##### ISSUE TYPE

- Backport Pull Request

### CODE REVIEW

**Comment by abadger** [comment]
Several comment:

* This looks like it changes connect_to_db()'s API in an incompatible manner (kw is no longer sent).  That's something we try not to put into an already-released Ansible because there could be other, third-party modules which are relying on the API.  We shouldn't break those in a minor release.  (It would be nice to do a deprecation cycle... I think that we have documented a deprecation cycle as the official way to do module_utils incompatible changes but I'm not sure how closely we follow that.)

* I'm also not sure if this is a better API.  It replaces an explicit parameter with extracting the parameters from module.params in the module_utils function.  that is a little magical.  In other places we've been trying to make module_utils less reliant on being passed an AnsibleModule, keeping the unrelated functionality properly abstracted from each other.  It also feels better to be explicit and have the parameter parsing be closer to the calling code.
  * Perhaps a compromise would be a new function whose sole purpose is to pull the postgres keyword args appropriate for the connection out of a dictionary.  Then the caller could call this new function, passing in module.params.  The filtered dictionary that is returned could then be passed to the connect_to_db() function.
    * I think that would both be a better, more explicit API, and remove the need to change the connect_to_db() function in a backwards incompatible way.

If you want an exception, you can ask at the public IRC meeting for committers to discuss and make a decision on whether this can be backported (Tuesdays and Thursdays): https://github.com/ansible/community/blob/master/meetings/README.md#tuesdays

**Comment by Andersson007** [comment]
@abadger , thank you for the suggestion!
I'd like to clarify some points.
- it is my function that was added recently, then moved to module_utils by [#55514](https://github.com/ansible/ansible/pull/55514) and changed several times.
- I agree with you about that passing connection params to connect_to_db probably is more explicit but in the other hand it is more complex then just to pass the module object.
Moreover, connect_to_db uses module.fail_json and module.warn, not only module.params, so it looks to me like an excessive step (extract connection options anywhere else and pass to connect_to_db).
New developers don't need to think about connection api at all, needs just to pass the module object similarly as in the other modules.
If a potential new developer wants to know what's going on, he always may look at the connect_to_db, it does the same things as earlier in the modules.

- I could add comments near
```
    db_connection = connect_to_db(module, autocommit=True)
    cursor = db_connection.cursor(cursor_factory=DictCursor)
```
that will explain something like (meaning) "the connection parameters are passed by a module object and handled into connect_to_db..." I think it's clear enough

**Comment by abadger** [comment]
For (1), yep, but they're now in a stable release of Ansible.  So changing the API *should* go through a deprecation cycle (We've made that policy but I don't know that we've enforced it on community modules in the past) and *must not* change incompatibly during the course of that release.

For bullet (2), there are several ideas you bring forth.
* Complexity.  If you create the new function, then complexity is only marginally impacted.  The code becomes something like:
``` python
pg_connect_vars = postgres.get_connect_vars(module.params)
connect_to_db(module, pg_connect_vars)
```
  New developers don't need to think about what is in pg_connect_vars unless they are curious, just as in your API.

* module already passed: We need to stop merging new module_utils APIs that do that.  It's bad because AnsibleModule becomes a god object and because we want to divorce the APIs from dependency on an AnsibleModule environment.  For our own code, we're moving to a different standard (see the activity around the module_utils/common directory for where that work is being performed) where the module's toplevel functions will know about the AnsibleModule but module_utils and the more backend functionality will be standard python functions.  errors will be propogated back to the toplevel functions by exceptions rather than invoking fail_json() so deeply in the guts of otherwise generic code.  Even some of fail_json() and exit_json()'s functionality will be moved out of AnsibleModule to operate more like the python stdlib's warning module.

**Comment by Andersson007** [comment]
@abadger , thank you for the detailed explanation! now it's clear to me, I'll try to solve this ASAP

**Comment by Andersson007** [comment]
@abadger , please, look at [#58067](https://github.com/ansible/ansible/pull/58067)

**Comment by Andersson007** [comment]
@abadger , I cherry-picked this one with [#58067](https://github.com/ansible/ansible/pull/58067), then fixed  conflixts.
Waiting for you review :)

**Comment by abadger** [comment]
Looks good, thanks @Andersson007!

Merged for 2.8.2

**Comment by Andersson007** [comment]
@abadger , thanks for good experience and merging!

**Pull request merged**
