### PR TITLE
rabbitmq_bindings rewrite

### PR DESCRIPTION
**Pull request by hyperized**
##### SUMMARY
I attempted to rewrite this module to cover some small issues:

- Use of global variables
- Add easy support for the potential additional HTTP status codes.
- PEP-8 compliance
- inconsistency between '#' and '~' routing key defaults

I also like to try out improvements such as:

- use of format()
- simplify decision tree
- use of objects

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
rabbitmq_binding.py

##### ANSIBLE VERSION
```
n/a
```

##### ADDITIONAL INFORMATION
I could use feedback on this.
I'm not sure if injecting the module into the object is the right choice.

### CODE REVIEW

**Comment by hyperized** [comment]
anyone

**Comment by resmo** [comment]
LGTM

**Comment by towolf** [comment]
@hyperized  We started testing Ansible 2.6.3 and rabbitmq_binding breaks with `rabbitmq-server 3.5.1`.

**Comment by towolf** [comment]
```
ailed: [10.106.80.142] (item={u'destination': u'my_queue', u'name': u',my_exchange', u'routing_key': u'#'}) => changed=false 
  details: '{"error":"Object Not Found","reason":"\"Not Found\"\n"}'
  item:
    destination: my_queue
    name: my_exchange
    routing_key: '#'
  msg: Unexpected reply from API
  status: 404
```

**Comment by towolf** [comment]
@hyperized [you removed the second parameter `safe=''` from `urllib_parse.quote`](https://github.com/ansible/ansible/commit/f210bbec5052e953771820a0e0db07dc1793d6e6#diff-d33fa8ead78fe967669bddbe3e490f6fL151). This make the `/` again "safe". But it isn't. The default vhost is `/`, and this url is invalid:
`http://localhost:15672/api/bindings///e/`

it should be `http://localhost:15672/api/bindings/%2F/e/`


https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote

**Pull request merged**
