### PR TITLE
fix docker_login doc example

### PR DESCRIPTION
**Pull request by gbour**
- Docs Pull Request

+label: docsite_pr

##### SUMMARY
docker_login example do not match parameters (`registry` should be `registry_url`)

##### COMPONENT NAME
docker_login

### CODE REVIEW

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @gbour for the Ansible documentation fix!

**Comment by felixfontein** [comment]
`registry` is an alias of `registry_url`, so the example was perfectly valid.

**Comment by samccann** [comment]
ah sorry about that @felixfontein . I've was a bit too eager to get the docs PR backlog down before devel froze today...I didn't notice it was an alias.

**Comment by gbour** [comment]
Hi @felixfontein, sorry I didn't saw the alias either

**Comment by felixfontein** [comment]
@gbour no worries, the docs are still correct :)

**Pull request merged**
