### PR TITLE
Pile 'o fixes for set_fact, missing filters, broken defaults, and nonworking test setup.

### PR DESCRIPTION
**Pull request by ferringb**
These fixes were previously sent broken down into individual topics, although they had a common initial base; per a request on one of them, all of this should be collapsed down, thus doing so here.

With these changes, the following now properly fail if in undefined var mode.
- hosts: all
  task:
  - debug: msg="missing filter is missing {{ansible_inventory_hostname|missing_filter}}"
  - set_fact: this_now_fails="{{ undefined_var }}"

Note; these fixes _require_ the first two revs in this PR:
1) first fixes defaults so that integer values are always integers.  This breaks later test code, and is broken for users who make a forgivable typo ('1' is effectively the same as 1 in ansible.cfg for ssh timeout for example)
2) Runner.**init** was tweaked so it binds the defaults it access at runtime, rather than at parse/compile time.  The previous tests for undefined var behaviour were working by luck, despite trying to adjust those settings at testing time; the new tests I added require the behaviour to work fully, hence having to fix this.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Actually the request was to split them :)

The "stop ignoring missing filters" patch and the int casts are all different.   If one requires the other, this is an EXCELLENT reason to fix on multiple branches.

I also don't understand "For the set_fact action, the passed in data is directly fed back
into (effectively) host vars- without enforced rendering (meaning
undefined vars slide past) since enforcement doesn't occur for module_args."

Why should the set fact module ever return something that needs to be templated again?  That's really not supported.   Rather, what should happen is it is templated, and set_fact then saves the result that is passed to it.

I am also not comfortable with this block:

"        # Update variables from the defaults; this is implemented this way to allow the code
-        # to match the current constants (which may change due to code, or due to tests manipulating it).
-        for key in ('host_list', 'module_name', 'module_args', 'forks', 'timeout', 'pattern',
-           'remote_user', 'remote_pass', 'private_key_file', 'sudo_pass', 'transport', 'sudo_user',
-           ('error_on_undefined_vars', 'undefined_var_behavior')):
-           if isinstance(key, tuple):
-              key, src = key
-           else:
-              src = key
-           if locals()[key] is None:
-              locals()[key] = getattr(C, 'DEFAULT_%s' % src.upper())"

getattr is a hack and we shouldn't be doing stuff like this, and I also don't understand what you mean here. 

I am fine with the missing filter patch and the int one -- and this is exactly why it should be split up into four pull requests so we can take that without manually cherry picking on our end.

Thanks!

cc @jimi1283

**Comment by jimi-c** [comment]
@mpdehaan I had asked that they be merged if the later commits required the previous ones to be functional. That way there weren't separate pull requests that included all of the patches.

**Comment by ferringb** [comment]
On Fri, Aug 23, 2013 at 8:40 PM, Michael DeHaan notifications@github.comwrote:

> Actually the request was to split them :)
> 
> The "stop ignoring missing filters" patch and the int casts are all
> different. If one requires the other, this is an EXCELLENT reason to fix on
> multiple branches.
> 
> I think there is some miscommunication going on here; I get the feeling the
> commit messages/PR requests I wrote detailing this were glossed over.  As I
> mentioned, the int fix is _required_ for both missing filter, and set fact;
> additionally, the int fix is effectively it's own topic since that fix
> should go in now (it's obvious) while the other fixes may involve some
> argument.  This is why there were multiple pull requests, and why I've been
> asking for clarification from y'all how you want this handled going forward.

If y'all prefer broken out topic branches for each fix (which I suggest),
I'll keep doing that; in this case I was told to collapse this shit down,
so I jumped through the hoop and did so.  Y'alls project, I'm just trying
to do whatever keeps people happy to land my fixes and continue w/ my
evaluation of ansible. :)

I also don't understand "For the set_fact action, the passed in data is

> directly fed back
> into (effectively) host vars- without enforced rendering (meaning
> undefined vars slide past) since enforcement doesn't occur for
> module_args."
> 
> Honestly, this part is a bit fucky, but it's accurate- I also tried to
> explain this in the commit message.  Think through the following task:
- set_fact: my_var="{{ undefined_var }}"

If invoked in an environment that treats missing vars as an error, /why in
the hell doesn't that fail/ ?  It should, yet it doesn't.  That is a bug- I
think that bug derives from the attempt to ignore undefined vars for a
tasks naming/module_args, but the cause there I've not fully ran down.
 That issue _does_ need fixing, but isn't addressed by this patch series.
 Per the commit message, this particular quirk is actually addressed via
tightening up what action plugins are allowed to return.

Why should the set fact module ever return something that needs to be

> templated again? That's really not supported. Rather, what should happen is
> it is templated, and set_fact then saves the result that is passed to it.
> 
> You're touching on why I wrote this specific patch.  I don't think /any/
> action plugin should be returning templated code.  It's just too much a
> potential source of gotchas/bugs, since any returned template code is quite
> likely going to require the original injected vars at the time of it's
> definition- meaning a later rendering is likely to fail or get the wrong
> data. That's obviously open to debate, but I suspect y'all agree with me-
> it's not desirable magic, and it makes it a bitch to track down the
> original source of an error.

As such, this patch; ensure that all returned content from an action is
fully rendered.  This cuts off the potential for stupid behaviour from
action plugins, while also duct-taping the set_fact issue so it properly
fails /now/.  The actual module_args issue I mentioned above still needs
addressing/investigation, but this particular patch suppress the user
visible buggy behaviour while removing a separate class of potential
gotchas.

It's subtle, but I think the dual approach here is best; feel free to argue
that point however. :)

I am also not comfortable with this block:

> " # Update variables from the defaults; this is implemented this way to
> allow the code
> - # to match the current constants (which may change due to code, or
>   due to tests manipulating it).
> - for key in ('host_list', 'module_name', 'module_args', 'forks',
>   'timeout', 'pattern',
> - 'remote_user', 'remote_pass', 'private_key_file', 'sudo_pass',
>   'transport', 'sudo_user',
> - ('error_on_undefined_vars', 'undefined_var_behavior')):
> - if isinstance(key, tuple):
> - key, src = key
> - else:
> - src = key
> - if locals()[key] is None:
> - locals()[key] = getattr(C, 'DEFAULT_%s' % src.upper())"
> 
> getattr is a hack and we shouldn't be doing stuff like this, and I also
> don't understand what you mean here.
> 
> Respectfully, you're incorrectly calling it a hack because you've not
> considered the other options available here.  Either you move those
> settings into a dictionary and access them w/in runner via that (which
> sucks fairly badly from a code standpoint), or you go the overly verbose
> approach of the following for each default:

if host_list is None:
  host_list = C.DEFAULT_HOST_LIST
if module_name is None:
  module_name = C.DEFAULT_MODULE_NAME

# etc.

...or you use the perfectly valid/pythonic getattr and do it via a for
loop.  Y'all want the verbose form that's fine, it's your code, I just used
a minor bit of advanced python here instead.  Alternatives welcome
obviously, but I'm pretty sure I covered the potential implementations
here- this is the least evil of the 3 in my view.

Y'all are hitting a variant of the "never use mutable arguments as a
default" python gotcha.  Take a look at
https://github.com/ansible/ansible/blob/devel/test/TestPlayBook.py#L272 ;
that's trying to change the defaults at runtime for testing reasons.  That
code _does_ change the value in the module, but if you look at
https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L141
,
Runner.**init** _binds_ the value of DEFAULT_UNDEFINED_VAR_BEHAVIOUR at the
time of the **init** being parsed.  Meaning that test codes attempt to
manipulate undefined vars doesn't actually change what Runner uses.  Whoops.

If in doubt, I suggest sticking some prints into the pathways I'm talking
about, or a 'import pdb;pdb.set_trace()'.  It's dead obvious if you poke at
things as it's executing that this is occurring exactly as I described it.

If you want test code to be able to manipulate defaults, then either you
need to reload the python environment in full for each test that
manipulates defaults (which is wasteful/whacked to say the least), or you
need to do the same fix I did here- specifically, moving the accessing of
the defaults to runtime rather than parse time.  Implementation of that can
be argued, but there is no other sane way to allow test code to manipulate
defaults without doing something along the lines of what I did there.

Meanwhile, holding off on splitting up the PRs here, updating, etc, till
y'all respond with what you want here.

**Comment by mpdehaan** [comment]
"If y'all prefer broken out topic branches for each fix (which I suggest),
I'll keep doing that; in this case I was told to collapse this shit down,
so I jumped through the hoop and did so"

Yes, they need to be broken out.   James gave you some slightly incorrect advice on those, which we've talked about.

Different topics must be in different commits.

I really do not have the bandwidth to discuss four seperate issues in one thread and then decide on them, so this is a little TL/DR to me.   

Please keep issues and discussions seperate and it's a lot easier to manage.

**Pull request closed without merging**
