### PR TITLE
Allow adhoc to execute includes and imports

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Allow adhoc to execute includes and imports

I thought I submitted this a while ago, but seem not to have done so.

Addresses https://github.com/ansible/proposals/issues/131

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/cli/adhoc.py

##### ANSIBLE VERSION

```
2.7
```

##### ADDITIONAL INFORMATION
include_tasks:

```
$ ansible localhost -m include_tasks -a include_me.yml
localhost | SUCCESS => {
    "changed": false,
    "include": "include_me.yml",
    "include_variables": {}
}
localhost | SUCCESS => {
    "msg": "here"
}
```

import_tasks:

```
$ ansible localhost -m import_tasks -a include_me.yml
localhost | SUCCESS => {
    "msg": "here"
}
```

include_role:
```
$ ansible localhost -m include_role -a name=bob
localhost | SUCCESS => {
    "changed": false,
    "include_variables": {
        "name": "bob"
    }
}
localhost | SUCCESS => {
    "msg": "bob"
}
```

import_role:

```
$ ansible localhost -m import_role -a name=bob
localhost | SUCCESS => {
    "msg": "bob"
}
```

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by clayg** [comment]
I came to this through a reference on ansible/proposals#131 - i'm not sure if this is what I'm looking for?  Where is the current documentation?

**Comment by bcoca** [comment]
@clayg there is no specific documentation, you can just execute them like you execute any other module with adhoc: `ansible -m include_role -a 'name=rolname' myhosts`

**Comment by ChristianCiach** [comment]
This worked with Ansible 2.7, but it broken with 2.8 for me:

```
$ ansible all -i hosts.yml -m include_role -a "myrole"

ERROR! 'async_val' is not a valid attribute for a IncludeRole

The error appears to be in 'None': line 0, column 0, but may
be elsewhere in the file depending on the exact syntax problem.

(could not open file to display line)
```

**Comment by sivel** [comment]
This was re-fixed in cd95843ea5f1bff40225b0430cfbb379cbe53661

**Pull request merged**
