### PR TITLE
oc module- Fixing description & removing example command

### PR DESCRIPTION
**Pull request by chrrrles**
Noticed formatting errors on http://docs.ansible.com/ansible/latest/oc_module.html -- also removing oc/oadm command examples

##### SUMMARY
Fixing docstring in oc module - also removing example openshift commands for creating cluster-admin service account.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
cluster/oc

##### ANSIBLE VERSION

```
latest
```

##### ADDITIONAL INFORMATION
see http://docs.ansible.com/ansible/latest/oc_module.html

### CODE REVIEW

**Comment by chrrrles** [comment]
note - I removed the example command because (I am guessing...) most Openshift admins should know how to create service accounts with assigned roles.  Also, it could encourage users to assign `cluster-admin` level access where it may not be needed.

**Comment by kevensen** [comment]
shipit

**Comment by samdoran** [comment]
shipit

**Comment by kevensen** [comment]
Any chance we can back port this to 2.4?

**Comment by samdoran** [comment]
@kevensen Cherry-picked into `stable-2.4` for inclusion with 2.4.1.

Apologies for messing up the description. That was totally my fault!

**Pull request merged**
