### PR TITLE
removed deprecated config/env vars

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

general cleanup of long ago deprecated configs

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

config
##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in the `pull_limit_inventory` integration test:

https://app.shippable.com/github/ansible/ansible/runs/16615/32/console

**Comment by bcoca** [comment]
@mattclay are the tests using the deprecated configs for inventory?

**Comment by bcoca** [comment]
new warning seems to indicate we are passing a bad host pattern
` [WARNING]: Could not match supplied host pattern, ignoring: 1da24ef044ab`

**Comment by mattclay** [comment]
I see that warning even when the tests pass: https://app.shippable.com/github/ansible/ansible/runs/16542/39/console

**Comment by mattclay** [comment]
@bcoca: Here's the problem: https://github.com/ansible-test-robinro/pull-integration-test/blob/master/ansible.cfg#L2

We should fork that into the ansible org and fix it there.

**Comment by mattclay** [comment]
Either that or use a locally created repository, if that's supported.

**Comment by mattclay** [comment]
I've rewritten the `ansible-pull` integration tests. As a result, this PR now passes tests.

**Pull request merged**
