### PR TITLE
don't modify dictionary while iterating over items()

### LINKED ISSUE #51159: ec2_group fails when rule references self in diff mode
##### SUMMARY
ec2_group when there is a rule referencing the group being created by name and you are using `--diff`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION

```
ansible 2.7.5
  config file = None
  configured module search path = ['/home/benb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible
  executable location = /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 11:21:55) [GCC 8.2.0]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT
ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    region: us-west-2
    security_group_name: ansible
    security_group_description: ansible bug report
    security_group_rules:
      - proto: all
        group_name: '{{ security_group_name }}'
    security_group_rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: '0.0.0.0/0'

  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_name }}"
        rules: "{{ security_group_rules }}"
        rules_egress: "{{ security_group_rules_egress }}"
        region: "{{ region }}"

```

##### EXPECTED RESULTS
The security group should be created

##### ACTUAL RESULTS
```paste below
ansible-playbook 2.7.5
  config file = None
  configured module search path = ['/home/benb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible
  executable location = /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/bin/ansible-playbook
  python version = 3.7.1 (default, Oct 22 2018, 11:21:55) [GCC 8.2.0]
No config file found; using defaults
setting up inventory plugins
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet yaml requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet ini requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet auto requirements, check plugin documentation if this is unexpected
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: create.yml **********************************************************************************************************************************************************************************************
1 plays in create.yml

PLAY [Create] *****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
task path: /home/benb/test/ansibug/create.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: benb
<127.0.0.1> EXEC /bin/sh -c 'echo ~benb && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935 `" && echo ansible-tmp-1548122420.382775-114730363972935="` echo /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935 `" ) && sleep 0'
Using module file /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /home/benb/.ansible/tmp/ansible-local-21774ed79v12w/tmpjyadmg3f TO /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/ /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/bin/python3.7 /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Create security group] **************************************************************************************************************************************************************************************
task path: /home/benb/test/ansibug/create.yml:20
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: benb
<127.0.0.1> EXEC /bin/sh -c 'echo ~benb && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763 `" && echo ansible-tmp-1548122421.1312113-173032039199763="` echo /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763 `" ) && sleep 0'
Using module file /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible/modules/cloud/amazon/ec2_group.py
<127.0.0.1> PUT /home/benb/.ansible/tmp/ansible-local-21774ed79v12w/tmp1jyt800w TO /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/ /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/bin/python3.7 /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 1182, in <module>\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 1174, in main\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 955, in get_diff_final_resource\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 938, in get_final_rules\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
	to retry, use: --limit @/home/benb/test/ansibug/create.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

### PR DESCRIPTION
**Pull request by bengerman13**
##### SUMMARY
Fixes #51159 
The current code loops over the items of a dict, and deletes some of them, which raises a `RuntimeError: dictionary changed size during iteration` in python3

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_group
##### ADDITIONAL INFORMATION

```
# create.yml
---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    region: us-west-2
    security_group_name: ansible
    security_group_description: ansible bug report
    security_group_rules:
      - proto: all
        group_name: '{{ security_group_name }}'
    security_group_rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: '0.0.0.0/0'

  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_name }}"
        rules: "{{ security_group_rules }}"
        rules_egress: "{{ security_group_rules_egress }}"
        region: "{{ region }}"
```

Before:
```ansible-playbook -c local -i localhost, --diff create.yml -vvvv
$ 
ansible-playbook 2.7.5
  config file = None
  configured module search path = ['/home/benb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible
  executable location = /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/bin/ansible-playbook
  python version = 3.7.1 (default, Oct 22 2018, 11:21:55) [GCC 8.2.0]
No config file found; using defaults
setting up inventory plugins
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet yaml requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet ini requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet auto requirements, check plugin documentation if this is unexpected
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: create.yml **********************************************************************************************************************************************************************************************
1 plays in create.yml

PLAY [Create] *****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
task path: /home/benb/test/ansibug/create.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: benb
<127.0.0.1> EXEC /bin/sh -c 'echo ~benb && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935 `" && echo ansible-tmp-1548122420.382775-114730363972935="` echo /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935 `" ) && sleep 0'
Using module file /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /home/benb/.ansible/tmp/ansible-local-21774ed79v12w/tmpjyadmg3f TO /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/ /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/bin/python3.7 /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/benb/.ansible/tmp/ansible-tmp-1548122420.382775-114730363972935/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Create security group] **************************************************************************************************************************************************************************************
task path: /home/benb/test/ansibug/create.yml:20
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: benb
<127.0.0.1> EXEC /bin/sh -c 'echo ~benb && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763 `" && echo ansible-tmp-1548122421.1312113-173032039199763="` echo /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763 `" ) && sleep 0'
Using module file /home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/site-packages/ansible/modules/cloud/amazon/ec2_group.py
<127.0.0.1> PUT /home/benb/.ansible/tmp/ansible-local-21774ed79v12w/tmp1jyt800w TO /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/ /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/bin/python3.7 /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/benb/.ansible/tmp/ansible-tmp-1548122421.1312113-173032039199763/AnsiballZ_ec2_group.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/home/benb/.local/share/virtualenvs/ansible-platform-RSodV-hf/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 1182, in <module>\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 1174, in main\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 955, in get_diff_final_resource\n  File \"/tmp/ansible_ec2_group_payload_31kbpu83/__main__.py\", line 938, in get_final_rules\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
	to retry, use: --limit @/home/benb/test/ansibug/create.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  
```
after:
```
$ ansible-playbook -c local -i localhost, --diff create.yml 

PLAY [Create] ***********************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create security group] ********************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0   

```

### CODE REVIEW

**Comment by bengerman13** [comment]
I'd like to write a test for this, but I'm not sure if there's a way to write a test that will run in diff mode - any pointers there would be great :smiley:

**Comment by samdoran** [comment]
This approach is good. Please add unit tests for this. You can find existing tests here `units/modules/cloud/amazon/test_ec2_group.py`.

If you need more help on the tests, stop by #ansible-devel or Freenode.

**Comment by s-hertel** [comment]
@bengerman13 Hi, also feel free to reach out on #ansible-aws. It looks like you have a task that reproduces this problem, so you could add that into the existing integration test suite. Here's an example of how to test diff mode for integration tests https://github.com/ansible/ansible/blob/devel/test/integration/targets/ec2_group/tasks/main.yml#L301-L309.

**Comment by bengerman13** [comment]
tests added (thanks for the help @samdoran and @s-hertel!)

**Comment by samdoran** [comment]
@bengerman13 Please create a changelog fragment. See [this fragment](https://github.com/ansible/ansible/blob/stable-2.7/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

**Review by samdoran — APPROVED** [review]

**Comment by jillr** [comment]
Issue should be resolved by  #56903

**Pull request closed without merging**
