### PR TITLE
Add get_available_hash_algorithms()

### PR DESCRIPTION
**Pull request by muffl0n**
As described in ansible/ansible-modules-core#141 it would be handy to have the get_available_hash_algorithms() that was developed there to be included in module_utils.

This PR adds the method get_available_hash_algorithms(). Additionally it does some refactoring to ease the use of digest_from_file:
- You just need to call digest_from_file() with the name of the algorithm instead of the function itself
- digest_from_file() also does a self.fail_json() when the requested algorithm is not available

I tested the changes as good as I could. But I'm sure that I missed some corner cases, so feel free to critize. :)

### CODE REVIEW

**Comment by abadger** [comment]
Unfortunately this changes the signature of digest_from_file().  Maybe we can make this a small wrapper around digest_from_file() (or vice versa if that works better).

**Comment by muffl0n** [comment]
Yeah, I already thought that this could be a problem. Maybe we could just do some check with `hasattr(algorithm, 'digest')`?

**Comment by abadger** [comment]
@muffl0n That would work for me... Implementation-wise, use the callable() function to perform that check instead of checking for `__call__` (I think somethings (from C?) don't implement **call**).

**Comment by muffl0n** [comment]
I already edited the code in my comment from checking for `__call__` to `digest` because right now digest_from_file() get's called with an object that does not have `__call__` but `digest`.
E.g.:

```
     def sha1(self, filename):
         ''' Return SHA1 hex digest of local file using digest_from_file(). '''
        return self.digest_from_file(filename, _sha1())
```

```
>>> from sha import sha as _sha1
>>> type(_sha1())
<type '_hashlib.HASH'>
>>> dir(_sha1())
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'block_size', 'copy', 'digest', 'digest_size', 'digestsize', 'hexdigest', 'name', 'update']
```

**Comment by abadger** [comment]
Sounds good.  Maybe check for hexdigest() since that's the function we actually use.

**Comment by muffl0n** [comment]
Good hint! Thank you! I changed the code accordingly.

**Comment by abadger** [comment]
Looks good except that we lose the ValueError exception in the md5 method().  Some modules are depending on that behaviour.  Since I'm going to a conference and won't be available to review this again, I'll merge and then fix that.

**Comment by abadger** [comment]
@muffl0n I ended up changing things a little more than I thought I would.  Instead of keeping it a method that has to do work everytime the method is called I changed it back to storing values in a dict at the toplevel: https://github.com/ansible/ansible/commit/00b1a2c8651b7a2772cfbaec465c8d03e857402c

That should make things slightly quicker since the dict will only be populated onload, not everytime the function is called.

I don't think that changes your get_url code at all so I'll look at merging that as well.

**Comment by abadger** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by muffl0n** [comment]
Thanks for the merge! 
The additional changes look reasonable. I was already thinking about the possibility to just determine the algorithms once. Your solution looks much better than the one I was thinking about. :)

**Pull request merged**
