### PR TITLE
Update system/ufw.py for ufw v0.35

### LINKED ISSUE #21297: Add support for comments in UFW
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ufw

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### SUMMARY
UFW supports comments since version 0.35. Would be great to support this in the ufw module.

Note: This is a resubmission of ansible/ansible-modules-extras#2065 since issues have been moved to the new repo.

### PR DESCRIPTION
**Pull request by gaddman**
Updating ufw.py to support changes made in ufw version 0.35

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
ufw.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### SUMMARY
Adding support for rule comments in ufw, which fixes #21297. Requires ufw version >=0.35
Adding new location of rules file since ufw v0.35, fixing #21296.
```
$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
Anywhere                   ALLOW       10.0.0.0/8                 # Allow connections from LAN
```

### CODE REVIEW

**Comment by gaddman** [comment]
Couple of notes:

- Tested with ufw version 0.35 and it's all good. Tested with version 0.34 and it will error with "Invalid token 'comment'" (as expected). It would be nice to check the ufw binary version first, but I'm not sure that implementing that within the module is appropriate - maybe it should be done in a helper module?
- I'm not sure if the way I'm using the string comment is correct/secure. Should it be cleaned/made safe somehow?

**Review by ovcharenko — APPROVED** [review]
shipit

**Comment by ovcharenko** [comment]
shipit

**Comment by ovcharenko** [comment]
@gaddman please add contributor_review tag for this pull request or it will wait forever in pending state.

**Comment by gaddman** [comment]
I think I need to be a contributor in order to add tags?

**Comment by gaddman** [comment]
rebased as required by ansibot, but I seem to have lost the commits for the version check from @tacid and the rules location fix I'd done earlier.

@ovcharenko - maybe it's easier to just use the PR developed by @tacid ? Unless there's a way to revert what I've done.

**Comment by ovcharenko** [comment]
@gaddman you may follow http://www.ocpsoft.org/tutorials/git/use-reflog-and-cherry-pick-to-restore-lost-commits/ to restore whatever was lost. Just review before pushing.

**Comment by ovcharenko** [comment]
@gaddman it is still missing UFW version check you had before...

**Comment by gaddman** [comment]
OK, I've got it sorted now - integrated the version check, comments, and rules location.

@tacid - I've tested this OK on my system, maybe you can on yours as well?

**Comment by tacid** [comment]
That's OK
But I've diffed it against my production module version - here is the difference (unified)
```patch
--- ufw.py.1    2017-06-14 14:53:30.209405432 +0300
+++ ufw.py      2017-06-10 19:18:19.288278064 +0300
@@ -21,10 +21,9 @@
 # You should have received a copy of the GNU General Public License
 # along with Ansible.  If not, see <http://www.gnu.org/licenses/>.

-ANSIBLE_METADATA = {'metadata_version': '1.0',
-                    'status': ['preview'],
-                    'supported_by': 'community'}
-
+ANSIBLE_METADATA = {'status': ['preview'],
+                    'supported_by': 'community',
+                    'version': '1.0'}

 DOCUMENTATION = '''
 ---
@@ -54,7 +53,7 @@
     description:
       - Change the default policy for incoming or outgoing traffic.
     required: false
-    aliases: ['default']
+    alias: default
     choices: ['allow', 'deny', 'reject']
   direction:
     description:
@@ -130,7 +129,7 @@
     description:
       - Add a comment to the rule. Requires UFW version >=0.35.
     required: false
-    version_added: "2.4"
+    version_added: "2.3"
 '''

 EXAMPLES = '''
@@ -199,7 +198,7 @@
     - 172.16.0.0/12
     - 192.168.0.0/16

-# Deny access to udp port 514 from host 1.2.3.4 and include a comment:
+# Deny access to udp port 514 from host 1.2.3.4:
 - ufw:
     rule: deny
     proto: udp
@@ -257,7 +256,7 @@
             to_port   = dict(default=None,  aliases=['port']),
             proto     = dict(default=None,  aliases=['protocol'], choices=['any', 'tcp', 'udp', 'ipv6', 'esp', 'ah']),
             app       = dict(default=None,  aliases=['name']),
-            comment   = dict(default=None, type='str')
+            comment   = dict(default=None)
         ),
         supports_check_mode = True,
         mutually_exclusive = [['app', 'proto', 'logging']]
@@ -317,6 +316,8 @@
     ufw_bin = module.get_bin_path('ufw', True)

     # Save the pre state and rules in order to recognize changes
+    # The 'show added' command wasn't available until v0.33, so check the rules files directly
+    # Location of rules changed to /etc/ufw/ in v0.35
     (_, pre_state, _) = module.run_command(ufw_bin + ' status verbose')
     (_, pre_rules, _) = module.run_command("grep '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules")
```

**Comment by gundalow** [comment]
Regarding the above diff `metadata_version` is correct

**Comment by gundalow** [comment]
What's left to do here, seems close from the comments?
any `shipits` get reset to zero after a commit, so if you are happy please state that again

bot_status

**Comment by ovcharenko** [comment]
shipit

**Comment by ovcharenko** [comment]
@gundalow Thanks!

**Comment by gundalow** [comment]
Thanks everyone for the PR, reviews and testing.

**Pull request merged**
