### PR TITLE
Fixing nxos_ntp

### LINKED ISSUE #19652: nxos_ntp: module fails if no NTP config is present
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_ntp

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 69c14bd003) last updated 2016/12/22 11:23:02 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No special config

##### OS / ENVIRONMENT
NX-OS version 7.0(3)I2(4)

##### SUMMARY
Trying to add a new NTP server with no servers present results in a failure.

##### STEPS TO REPRODUCE
Trying to run this simple playbook, hosts n9k-tor group has host 192.168.2.11

```yaml
---

- name: gather int data
  hosts: n9k-tor 
  connection: local
  gather_facts: no


  tasks:

    - nxos_ntp:
        host: "{{ inventory_hostname }}"
        transport: cli 
        username: ***
        password: ****
        use_ssl: yes
        validate_certs: False
        server: 10.20.30.40 
        state: present

```

##### EXPECTED RESULTS
Server is added

##### ACTUAL RESULTS
The following error occurs:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_B58nks/ansible_module_nxos_ntp.py", line 635, in <module>
    main()
  File "/tmp/ansible_B58nks/ansible_module_nxos_ntp.py", line 578, in main
    existing, peer_server_list = get_ntp_existing(address, peer_type, module)
  File "/tmp/ansible_B58nks/ansible_module_nxos_ntp.py", line 454, in get_ntp_existing
    peer_list = get_ntp_peer(module)
  File "/tmp/ansible_B58nks/ansible_module_nxos_ntp.py", line 403, in get_ntp_peer
    command, module, command_type='cli_show_ascii')[0]
IndexError: list index out of range

fatal: [192.168.2.11]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "nxos_ntp"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_B58nks/ansible_module_nxos_ntp.py\", line 635, in <module>\n    main()\n  File \"/tmp/ansible_B58nks/ansible_module_nxos_ntp.py\", line 578, in main\n    existing, peer_server_list = get_ntp_existing(address, peer_type, module)\n  File \"/tmp/ansible_B58nks/ansible_module_nxos_ntp.py\", line 454, in get_ntp_existing\n    peer_list = get_ntp_peer(module)\n  File \"/tmp/ansible_B58nks/ansible_module_nxos_ntp.py\", line 403, in get_ntp_peer\n    command, module, command_type='cli_show_ascii')[0]\nIndexError: list index out of range\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0

```
##### QUICK FIX
I have discovered that changing lines 402-403 from
```
    ntp = execute_show_command(
command, module, command_type='cli_show_ascii')[0]
```
to
```
    ntp1 = execute_show_command( 
                command, module, command_type='cli_show_ascii')
    if len(ntp1) > 0:
      ntp = ntp1[0]
    else:
      return []

```
appears to fix the issue, but since I am quite new to programming, I am not sure whether it brakes any other functionality and how to test that properly.

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_ntp

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Fixes #19652

### CODE REVIEW

**Comment by gundalow** [comment]
If you are happy with this I'll merge into `devel`

**Comment by gundalow** [comment]
@GGabriele Rebase needed

**Comment by privateip** [comment]
needs_rebase

**Review by Qalthos — APPROVED** [review]

**Comment by Qalthos** [comment]
shipit

**Pull request merged**
