### PR TITLE
Backport of 65310: postgresql_owner: use query_params with cursor

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Backport of #65310 : postgresql_owner: use query_params with cursor

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/postgresql/postgresql_owner.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
https://github.com/ansible/ansible/pull/65034 needs to be merged before...
waiting for merging https://github.com/ansible/ansible/pull/65034

**Review by kostiantyn-nemchenko — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko thank you!

**Comment by tcraxs** [comment]
LGTM

**Comment by Andersson007** [comment]
@tcraxs thank you!

**Pull request merged**
