### PR TITLE
Introduce exception AnsibleFilterError and use it in Jinja filters.  Ign...

### PR DESCRIPTION
**Pull request by stoned**
...ore this exception when trying to find the name of a task for display (callback) purpose.

### CODE REVIEW

**Comment by stoned** [comment]
Without a workaround or something like the proposed pullup, a playbook like to following failed with "ERROR: |failed expects a dictionary"

```
  ---
  - name: test failed
    hosts: all
    sudo: no
    gather_facts: no
    tasks:
      - shell: 'true'
        register: a_var
      - debug: msg="{{a_var|failed}}"
```

**Comment by stoned** [comment]
`* like the following fails...`

**Comment by mpdehaan** [comment]
Is the following still ok?

```
when: a_var | failed 
```

?

**Comment by stoned** [comment]
Yes it still ok.

**Comment by stoned** [comment]
I mean it is still ok.

**Comment by mpdehaan** [comment]
Ok, good deal.   That would be more of a situation if it were
non-operational.

Thanks!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
