### PR TITLE
Fix proxysql module cursor_class

### LINKED ISSUE #67337: proxysql module DictCursor ignored
##### SUMMARY
proxysql  is using `mysql_driver.cursors.DictCursor` for the cursor_class when it must be `'DictCursor'` based on the latest changes in mysql_utils

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxysql module

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bube/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/xxxx/.ansible_secret
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

confirmed on el7 but must affect all

```
$ pip freeze | grep -i mysql
MySQL-python==1.2.5
PyMySQL==0.9.3
```

##### STEPS TO REPRODUCE

```yaml
- hosts: proxysql
  gather_facts: yes
  vars:
    login_username: EDIT
    login_passwd: EDIT
    proxysql_global_variables:
      mysql:
       moni tor_username: proxymonitor
       monitor_password: ProxyMonitor1!
  tasks:
    - name: set global variables for mysql-%
      proxysql_global_variables:
        login_user: "{{login_username }}"
        login_password: "{{ login_passwd }}"
        variable: "mysql-{{ item.key }}"
        value: "{{ item.value }}"
        load_to_runtime: no
      with_dict: "{{ proxysql_global_variables.mysql | default({}) }}"
```

##### EXPECTED RESULTS
Succeed updating variables

##### ACTUAL RESULTS

```paste below
TASK [set global variables for mysql-%] **********************************************************************************************************************************************************************************************************************
Wednesday 12 February 2020  13:11:18 +0000 (0:00:01.319)       0:00:01.382 ****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: tuple indices must be integers, not str
failed: [ProxySQL1] (item={'value': u'proxymonitor', 'key': u'monitor_username'}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "monitor_username", "value": "proxymonitor"}, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_proxysql_global_variables_payload_GgMcQ7/ansible_proxysql_global_variables_payload.zip/ansible/modules/database/proxysql/proxysql_global_variables.py\", line 266, in <module>\n  File \"/tmp/ansible_proxysql_global_variables_payload_GgMcQ7/ansible_proxysql_global_variables_payload.zip/ansible/modules/database/proxysql/proxysql_global_variables.py\", line 231, in main\n  File \"/tmp/ansible_proxysql_global_variables_payload_GgMcQ7/ansible_proxysql_global_variables_payload.zip/ansible/modules/database/proxysql/proxysql_global_variables.py\", line 122, in check_config\nTypeError: tuple indices must be integers, not str\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### PR DESCRIPTION
**Pull request by maxbube**
##### SUMMARY

Fixes #67337 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
proxysql

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by cezmunsta** [comment]
This also affects 2.9, code breaks after 2.8.8

**Comment by maxbube** [comment]
+label affects_2.9

**Comment by gundalow** [comment]
@cezmunsta Have you tested this PR, does it solve the issue?

> This also affects 2.9, code breaks after 2.8.8

Once merged into `devel`, @maxbube can you please raise a backport PR for the stable-2.9 branch, https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

**Comment by felixfontein** [comment]
CC @Andersson007 since this might be related to #61832.

**Comment by cezmunsta** [comment]
> CC @Andersson007 since this might be related to #61832.

This is indeed the cause - code was not searched properly as the ProxySQL module passes the class and not a string.

**Comment by cezmunsta** [comment]
I wonder if it would be better to fix the MySQL utils module instead, rather than the ProxySQL module:
```
--- a/lib/ansible/module_utils/mysql.py
+++ b/lib/ansible/module_utils/mysql.py
@@ -85,7 +85,7 @@ def mysql_connect(module, login_user=None, login_password=None, config_file='',
         if autocommit:
             db_connection.autocommit(True)
 
-    if cursor_class == 'DictCursor':
+    if cursor_class in [mysql_driver.cursors.DictCursor, 'DictCursor']:
         return db_connection.cursor(**{_mysql_cursor_param: mysql_driver.cursors.DictCursor}), db_connection
     else:
         return db_connection.cursor(), db_connection
```

**Review by Andersson007 — APPROVED** [review]
@felixfontein thanks for mentioning!

@maxbube thank you for fixing this!
The main problem was (and is) that we don't have CI tests for proxysql modules.. i'm going to implement them ASAP.
@cezmunsta you're suggestion is good but i'm afraid it might be painful to go through all ci tests that will be launched by changing mysql.py (a lot unstable results usually happen).
LGTM
shipit

**Comment by Andersson007** [comment]
@felixfontein can we merged it?

**Comment by felixfontein** [comment]
There should be a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to) before this is merged.

I think switching completely to the string option (like in this PR) is fine. BTW, did someone check whether there are more modules which use the `mysql` module_utils (and which might use `cursorclass`)?

(What would be nice if there is something in module_utils which complains if `cursor_class` is neither `'DictCursor'` nor `None`. But that can also be added later.)

**Comment by maxbube** [comment]
Hi @felixfontein Ive sent a new commit adding the changelog fragment. It seems the only 2 modules are using mysql mode_utils `mysql` and `proxysql`, mysql is ok and this PR fixes proxysql.

**Comment by Andersson007** [comment]
```changelogs/fragments/67337-fix-proxysql-mysql-cursor:0:0: extension must be one of: .yml, .yaml```

**Comment by maxbube** [comment]
> @cezmunsta Have you tested this PR, does it solve the issue?
> 
> > This also affects 2.9, code breaks after 2.8.8
> 
> Once merged into `devel`, @maxbube can you please raise a backport PR for the stable-2.9 branch, https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

@gundalow if get merged I will do it

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@maxbube thanks a lot for fixing this! If you need help with the backport, just ask here!
@cezmunsta @Andersson007 thanks a lot for helping with this!

**Comment by kuntalFreshBooks** [comment]
when can we expect this fix to be available..

**Pull request merged**
