### PR TITLE
docker_container: deprecate trust_image_content

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The `trust_image_content` option is not used by the module (no idea if it ever was used...). Let's get rid of it.

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by felixfontein** [comment]
I went through the repository's history; the option was introduced in bc3391f1f9205348757ec0f71fb27f783df3936d, when the module was added, and hasn't been used even back then.

**Review by tremble — APPROVED** [review]
+1 doesn't appear to be used anywhere

**Comment by felixfontein** [comment]
@zhongjun2 it's not used there, listing it there only makes sure that the module doesn't think that the option belongs to a container property. It has to be removed from that list only when the option is removed (i.e. in Ansible 2.14).

**Comment by felixfontein** [comment]
@zhongjun2 @tremble thank you very much for your reviews!

**Pull request merged**
