### PR TITLE
openssl_*: add backup option

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Add a backup option to various openssl_* modules.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
openssl_certificate
openssl_csr
openssl_dhparam
openssl_pkcs12
openssl_publickey

### CODE REVIEW

**Comment by felixfontein** [comment]
I found a bug: `state=absent` doesn't work for `openssl_certificate`.

**Comment by felixfontein** [comment]
`state=absent` is also broken for `openssl_dhparam`.

**Comment by felixfontein** [comment]
The bugs will be fixed by #54296 and #54298.

**Comment by felixfontein** [comment]
The failing tests are unrelated to the PR (problem with installing packages on OpenSUSE).

**Comment by felixfontein** [comment]
Currently includes essentially #54353.

**Comment by felixfontein** [comment]
The "big fat warning" now looks like this:
privatekey-warning
I hope this is clear enough (and not too annoying).

**Comment by felixfontein** [comment]
ready_for_review

**Comment by Shaps** [comment]
Looks good. 
shipit

**Comment by Shaps** [comment]
shipit

**Comment by felixfontein** [comment]
@Shaps @resmo thanks for reviewing and merging!

**Pull request merged**
