### PR TITLE
add local IP address to ansible-pull limit hosts

### PR DESCRIPTION
**Pull request by tedder**
##### Issue Type:
- Feature Pull Request
##### Ansible Version:

```
ansible 2.1.0 (devel 61b7567ed6) last updated 2016/03/13 20:25:09 (GMT -700)
```
##### Summary:

current "--limit" options give the hostnames but not the host IP address. using a standard pattern to get this. at worst, it'll return 127.0.0.1, which is entirely fine.

This is especially helpful on EC2 hosts with various ec2.cfg settings.
##### Example output:

```
<!-- Paste verbatim command output here if necessary -->
```

### CODE REVIEW

**Comment by tedder** [comment]
@jimi-c James- I thought this was going to be in 2.1, but RC1 was cut today?

**Comment by robinro** [comment]
@tedder what is your take on #15110? It is similar, but asks for all IPs instead of just one.

**Comment by tedder** [comment]
Robin: I haven't tested it but I like the concept.

**Comment by jimi-c** [comment]
@tedder the milestone is a goal, not a guarantee, sorry for the incorrect impression there. When 2.1 final is released, we'll bump everything in the older milestone to the new one and try and get as much as we can in.

**Comment by tedder** [comment]
wait, what, somehow I closed this. Can you help, @jimi-c / @gregdek?

**Comment by tedder** [comment]
Aha. Huh, cleaning up my repo means the changes went away (since I didn't branch it). Never mind, I guess, we'll go with the other PR that accomplishes this (or I'll just keep using my own way).

**Comment by gregdek** [comment]
Yep. The vagaries of Github.

**Pull request closed without merging**
