### PR TITLE
Add nxos_lldp module

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

*  Implementation for nxos_lldp module
*  Integration test for nxos_lldp module

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

nxos_lldp
##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by trishnaguha — APPROVED** [review]

**Comment by mikewiebe** [comment]
@trishnaguha and @ganeshrn Why did we add a module just for enabling `feature lldp`?  We already have `nxos_feature` to enable nxos features.  Does this provide something that `nxos_feature` does not? 

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_feature.py

**Comment by trishnaguha** [comment]
@mikewiebe `net_lldp` enables/disables lldp service on network devices. http://docs.ansible.com/ansible/latest/net_lldp_module.html. nxos_lldp is implemented so that net_lldp can be used in platform agnostic way. We plan to implement net*_ modules for all platforms.

**Comment by mikewiebe** [comment]
@trishnaguha Interesting.  Thanks for the response.  Do you have a writeup on the strategy and plan to implement these net_* modules?  Will net_lldp simply make use of nxos_lldp for nxos platforms?  If this is the case, I would like to understand why the existing nxos_feature module could not be used instead.

**Comment by trishnaguha** [comment]
@mikewiebe So net_* modules are simply the plugins which calls the underlying implementation modules for specific platform.
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/net_lldp.py is just a plugin. The module doesn't have any code https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/protocol/net_lldp.py in there. It simply triggers {{ platform }}_lldp module, the platform that you specify in `network_os` or `ansible_network_os`.

For example:
```
- name: del user for eos
  net_user: &eos_task
    name: test1
    state: absent
    provider: "{{ eapi }}"
  network_os: eos

- name: enable lldp for nxos
  net_lldp: &nxos_task
    state: present
  network_os: nxos
```

Here `&eos_task` triggers `eos_user` module since the `network_os` is eos.
`&nxos_tasks` triggers `nxos_lldp` module since the `network_os` is nxos.

**Pull request merged**
