### PR TITLE
ensure facts marked as unsafe (#55326)

### PR DESCRIPTION
**Pull request by bcoca**
dont rely on plugin layer to do so

(cherry picked from commit aa8d23b42f82dd48c5929f7c62e71f2a93861103)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

core

### CODE REVIEW

**Comment by abadger** [comment]
Merged for 2.8.0rc1

**Comment by abadger** [comment]
Wait, doesn't this need to say that alpha1 and beta1 had insecure behaviour?

**Comment by bcoca** [comment]
@abadger I would argue for the fix in this PR all previous version of Ansible had 'insecure behaviour' as it allowed action plugins to pass 'non AnsibleUnsafe unsafe data'. 

I did create #55460 specifically for the issue we detected in alpha/beta and that has specific wording.

**Comment by abadger** [comment]
Yes, this one has already been merged.  i do not think #55460 should be merged.  I think the changelog presently in #55460 should be merged with/replace the changelog here.  Further, i think the code wrapping facts in action/__init__.py should be removed.  This is all if i understand correctly that this code ensures that the wrappingv is always performed by wrapping in the calling code.

**Pull request merged**
