### PR TITLE
FortiOS modules for 2.9 - 1

### PR DESCRIPTION
**Pull request by migumun**
##### SUMMARY
This PR contains an update to fortios modules that includes all of the changes requested for 2.9.
This is the first group of 20 modules.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

fortios_antivirus_heuristic
fortios_antivirus_profile
fortios_antivirus_quarantine
fortios_antivirus_settings
fortios_application_custom
fortios_application_group
fortios_application_list
fortios_application_name
fortios_application_rule_settings
fortios_authentication_rule
fortios_authentication_scheme
fortios_authentication_setting
fortios_dlp_filepattern
fortios_dlp_fp_doc_source
fortios_dlp_fp_sensitivity
fortios_dlp_sensor
fortios_dlp_settings
fortios_dnsfilter_domain_filter
fortios_dnsfilter_profile
fortios_endpoint_control_client

### CODE REVIEW

**Comment by danielmellado** [comment]
Hi @mamunozgonzalez, thanks for your PR! Could you please remove E337 ignore for your modules at test/sanity/validate-modules/ignore.txt ? Thanks!

**Review by danielmellado — COMMENTED** [review]
Let's get the violations fixed! I left some comment there which should work as a start-up ;)

**Comment by mamunozgonzalez** [comment]
Closing PR as proper rebase from old forked repo cannot be done properly (local old branch was already pushed to forked repo and this prevented a proper rebase).

**Comment by mamunozgonzalez** [comment]
New PR is: https://github.com/ansible/ansible/pull/60469

**Pull request closed without merging**
