### PR TITLE
Add a binary rust example module

### PR DESCRIPTION
**Pull request by webknjaz**
##### SUMMARY

I've figured that we could have additional binary module example :)

##### ISSUE TYPE

 - New Module Pull Request
 - Module Example Pull Request

##### COMPONENT NAME

test/integration/targets/binary_modules/library/rust/src/main.rs

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```diff
-PLAY RECAP *********************************************************************
-testhost_binary_modules    : ok=11   changed=0    unreachable=0    failed=0
+PLAY RECAP *********************************************************************
+testhost_binary_modules    : ok=22   changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by webknjaz** [comment]
@mattclay we'll need to put the binary of this module into S3

**Comment by abadger** [comment]
This doesn't seem to add any value here.  In the context of testing binary modules,. Go lang, rust, C are all the same to Ansible.  It also adds more dependencies to building completely from source.

This seems more like something that belongs in an examples repository.  (@tima was working on something along those lines at one point.  There's also the ansible for rubyists repository as an older example)

**Comment by webknjaz** [comment]
@abadger are you talking about repo with playbook examples? Also, it doesn't add build deps in CI as those tests use binaries cached in S3.

**Comment by jborean93** [comment]
I think he is saying there is now a new dependency to create these binary modules if we needed to make changes. Considering we don't care about the code for a compiled binary just that Ansible executes it correctly, I don't see what benefits we get by adding another binary test. If anything the tests take longer and add further complexity.

**Comment by abadger** [comment]
Yep, what jborean said.  I think tima's work was both the lightbulb and ansible-examples repos.  They're both focused on playbooks right now but might have room for a series of lessons on writing modules (including on on writing modules in compiled languages).

Here's the ansible-for-rubyists repo which is probably the closest we have to what you're doing currently: https://github.com/ansible/ansible-for-rubyists

**Comment by webknjaz** [comment]
Hey @tima, are you okay with adding this to ansible-examples or lightbulb?

**Comment by mattclay** [comment]
This should definitely be in external examples rather than added to tests. As @abadger and @jborean93 stated, this doesn't give us anything in our tests we don't already have.

**Comment by webknjaz** [comment]
@dfederlein advised to move it to:
https://github.com/ansible/ansible-examples/tree/master/rust-module-hello-world

**Comment by dfederlein** [comment]
Thanks @webknjaz we're happy to see that in the examples and will incorporate it into our demonstrations of module production n various languages.

**Pull request closed without merging**
