### PR TITLE
Fix handling of inventory and credential options for tower_job_launch

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY
- Fixed issue #25017,#37567
- Add example for prompt on launch
- Add integration test for prompt on launch
- inventory and credential variables are option(only need to set when a job template turned on `prompt on launch` option), both of them unnecessary to specify when `prompt on launch` is turned off
- Rebased and recreated PR #41497

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - tower_job_launch.py

##### ANSIBLE VERSION

```
Devel
```

##### ADDITIONAL INFORMATION

None

### CODE REVIEW

**Comment by AlanCoding** [comment]
shipit

**Comment by rooftopcellist** [comment]
shipit

**Comment by gundalow** [comment]
@saito-hideki Thank you for this bug fix
@AlanCoding @rooftopcellist Thank you for the reviews.

Merged into `devel` for release in Ansible 2.8

**Comment by saito-hideki** [comment]
This PR fixed the following issue of tower-cli as well:

- https://github.com/ansible/tower-cli/issues/666

**Pull request merged**
