### PR TITLE
ovirt_network: ovirt fix getting labels

### LINKED ISSUE #51422: ovirt_network fails to label a new network
##### SUMMARY
ovirt_network fails to label a new network

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ovirt_network

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.6 (Maipo)

##### STEPS TO REPRODUCE

```yaml
[root@rhv43-engine ~]# rpm -qa ansible
ansible-2.7.6-1.el7ae.noarch
[root@rhv43-engine ~]# cat add_net.yml
---
- hosts: localhost
  tasks:
  - ovirt_auth:
     state: present
     username: admin@internal
     password: 123456
     url: https://ovirt-43.virt/ovirt-engine/api
     insecure: true

  - ovirt_network:
     auth: "{{ ovirt_auth }}"
     data_center: Default
     label: a_label_1
     name: network_1
     vlan_tag: 1
     vm_network: true
     state: present
     clusters:
     - name: Default
```

##### EXPECTED RESULTS

```
[root@rhv43-engine ~]# ansible-playbook -vvv add_net.yml 
ansible-playbook 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: add_net.yml ************************************************************************************************************************
1 plays in add_net.yml

PLAY [localhost] *****************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
task path: /root/add_net.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1548752942.41-89999053895044 `" && echo ansible-tmp-1548752942.41-89999053895044="` echo /root/.ansible/tmp/ansible-tmp-1548752942.41-89999053895044 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12899qkguoT/tmpCag4AP TO /root/.ansible/tmp/ansible-tmp-1548752942.41-89999053895044/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1548752942.41-89999053895044/ /root/.ansible/tmp/ansible-tmp-1548752942.41-89999053895044/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1548752942.41-89999053895044/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1548752942.41-89999053895044/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [ovirt_auth] ****************************************************************************************************************************
task path: /root/add_net.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1548752942.92-115886788202150 `" && echo ansible-tmp-1548752942.92-115886788202150="` echo /root/.ansible/tmp/ansible-tmp-1548752942.92-115886788202150 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_auth.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12899qkguoT/tmpfsGBF9 TO /root/.ansible/tmp/ansible-tmp-1548752942.92-115886788202150/AnsiballZ_ovirt_auth.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1548752942.92-115886788202150/ /root/.ansible/tmp/ansible-tmp-1548752942.92-115886788202150/AnsiballZ_ovirt_auth.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1548752942.92-115886788202150/AnsiballZ_ovirt_auth.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1548752942.92-115886788202150/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "ansible_facts": {
        "ovirt_auth": {
            "ca_file": null, 
            "compress": true, 
            "headers": null, 
            "insecure": true, 
            "kerberos": false, 
            "timeout": 0, 
            "token": "4CSuj36kD2p9IoLmH1qJTRilousCYsrciO2wDMYdpKA2Zb38upO3BAIO6UPNbq52YLXv3vIq_ybPoY2khIkANA", 
            "url": "https://ovirt-43.virt/ovirt-engine/api"
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "ca_file": null, 
            "compress": true, 
            "headers": null, 
            "hostname": null, 
            "insecure": true, 
            "kerberos": false, 
            "ovirt_auth": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "timeout": 0, 
            "token": null, 
            "url": "https://ovirt-43.virt/ovirt-engine/api", 
            "username": "admin@internal"
        }
    }
}

TASK [ovirt_network] *************************************************************************************************************************
task path: /root/add_net.yml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1548752943.36-12876329904685 `" && echo ansible-tmp-1548752943.36-12876329904685="` echo /root/.ansible/tmp/ansible-tmp-1548752943.36-12876329904685 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_network.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12899qkguoT/tmphYPpkk TO /root/.ansible/tmp/ansible-tmp-1548752943.36-12876329904685/AnsiballZ_ovirt_network.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1548752943.36-12876329904685/ /root/.ansible/tmp/ansible-tmp-1548752943.36-12876329904685/AnsiballZ_ovirt_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1548752943.36-12876329904685/AnsiballZ_ovirt_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1548752943.36-12876329904685/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "diff": {
        "after": {}, 
        "before": {}
    }, 
    "id": "e24241f1-45f8-418c-aa69-73dcec9789ec", 
    "invocation": {
        "module_args": {
            "clusters": [
                {
                    "name": "Default"
                }
            ], 
            "comment": null, 
            "data_center": "Default", 
            "description": null, 
            "fetch_nested": false, 
            "label": "a_label_1", 
            "mtu": null, 
            "name": "network_1", 
            "nested_attributes": [], 
            "poll_interval": 3, 
            "state": "present", 
            "timeout": 180, 
            "vlan_tag": 1, 
            "vm_network": true, 
            "wait": true
        }
    }, 
    "network": {
        "cluster": {
            "href": "/ovirt-engine/api/clusters/32895324-1b6c-11e9-8eee-525400a283a5", 
            "id": "32895324-1b6c-11e9-8eee-525400a283a5"
        }, 
        "comment": "", 
        "data_center": {
            "href": "/ovirt-engine/api/datacenters/32876410-1b6c-11e9-975e-525400a283a5", 
            "id": "32876410-1b6c-11e9-975e-525400a283a5"
        }, 
        "description": "", 
        "display": false, 
        "href": "/ovirt-engine/api/clusters/32895324-1b6c-11e9-8eee-525400a283a5/networks/e24241f1-45f8-418c-aa69-73dcec9789ec", 
        "id": "e24241f1-45f8-418c-aa69-73dcec9789ec", 
        "mtu": 0, 
        "name": "network_1", 
        "required": true, 
        "status": "operational", 
        "stp": false, 
        "usages": [
            "vm"
        ], 
        "vlan": {
            "id": 1
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

```paste below
[root@rhv43-engine ~]# ansible-playbook -vvv add_net.yml
ansible-playbook 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: add_net.yml ************************************************************************************************************************
1 plays in add_net.yml

PLAY [localhost] *****************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
task path: /root/add_net.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1548752938.79-91120147256785 `" && echo ansible-tmp-1548752938.79-91120147256785="` echo /root/.ansible/tmp/ansible-tmp-1548752938.79-91120147256785 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12799AyDDhK/tmppnkKKb TO /root/.ansible/tmp/ansible-tmp-1548752938.79-91120147256785/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1548752938.79-91120147256785/ /root/.ansible/tmp/ansible-tmp-1548752938.79-91120147256785/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1548752938.79-91120147256785/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1548752938.79-91120147256785/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [ovirt_auth] ****************************************************************************************************************************
task path: /root/add_net.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1548752939.26-211617088526759 `" && echo ansible-tmp-1548752939.26-211617088526759="` echo /root/.ansible/tmp/ansible-tmp-1548752939.26-211617088526759 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_auth.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12799AyDDhK/tmpuvBsSp TO /root/.ansible/tmp/ansible-tmp-1548752939.26-211617088526759/AnsiballZ_ovirt_auth.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1548752939.26-211617088526759/ /root/.ansible/tmp/ansible-tmp-1548752939.26-211617088526759/AnsiballZ_ovirt_auth.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1548752939.26-211617088526759/AnsiballZ_ovirt_auth.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1548752939.26-211617088526759/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "ansible_facts": {
        "ovirt_auth": {
            "ca_file": null, 
            "compress": true, 
            "headers": null, 
            "insecure": true, 
            "kerberos": false, 
            "timeout": 0, 
            "token": "KHoPZMEpfPKmWgeG56sEmpzv9ZpOdmzp2Sp7JU8X7TocQCsyOh9yyJUHkZetvdmQxiJ7KVsf4RTS8pBeI81YVA", 
            "url": "https://ovirt-43.virt/ovirt-engine/api"
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "ca_file": null, 
            "compress": true, 
            "headers": null, 
            "hostname": null, 
            "insecure": true, 
            "kerberos": false, 
            "ovirt_auth": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "timeout": 0, 
            "token": null, 
            "url": "https://ovirt-43.virt/ovirt-engine/api", 
            "username": "admin@internal"
        }
    }
}

TASK [ovirt_network] *************************************************************************************************************************
task path: /root/add_net.yml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1548752939.72-10004957182454 `" && echo ansible-tmp-1548752939.72-10004957182454="` echo /root/.ansible/tmp/ansible-tmp-1548752939.72-10004957182454 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_network.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-12799AyDDhK/tmpmtgqUw TO /root/.ansible/tmp/ansible-tmp-1548752939.72-10004957182454/AnsiballZ_ovirt_network.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1548752939.72-10004957182454/ /root/.ansible/tmp/ansible-tmp-1548752939.72-10004957182454/AnsiballZ_ovirt_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1548752939.72-10004957182454/AnsiballZ_ovirt_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1548752939.72-10004957182454/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_network_payload_6vDsZN/__main__.py", line 265, in main
    ret = networks_module.create(search_params=search_params)
  File "/tmp/ansible_ovirt_network_payload_6vDsZN/ansible_ovirt_network_payload.zip/ansible/module_utils/ovirt.py", line 589, in create
    self.post_create(entity)
  File "/tmp/ansible_ovirt_network_payload_6vDsZN/__main__.py", line 150, in post_create
    self._update_label_assignments(entity)
  File "/tmp/ansible_ovirt_network_payload_6vDsZN/__main__.py", line 156, in _update_label_assignments
    labels = [lbl.id for lbl in self._connection.follow_link(entity.network_labels)]
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 790, in follow_link
    service = self.service(path)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 731, in service
    return self.system_service().service(path)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 26614, in service
    return self.data_centers_service().service(path[12:])
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 6093, in service
    return self.data_center_service(path[:index]).service(path[index + 1:])
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 5643, in service
    return self.networks_service().service(path[9:])
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 5896, in service
    return self.network_service(path[:index]).service(path[index + 1:])
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 5772, in service
    raise Error('The path \"%s\" doesn\'t correspond to any service' % path)
Error: The path "networklabels" doesn't correspond to any service

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "clusters": [
                {
                    "name": "Default"
                }
            ], 
            "comment": null, 
            "data_center": "Default", 
            "description": null, 
            "fetch_nested": false, 
            "label": "a_label_1", 
            "mtu": null, 
            "name": "network_1", 
            "nested_attributes": [], 
            "poll_interval": 3, 
            "state": "present", 
            "timeout": 180, 
            "vlan_tag": 1, 
            "vm_network": true, 
            "wait": true
        }
    }, 
    "msg": "The path \"networklabels\" doesn't correspond to any service"
}
	to retry, use: --limit @/root/add_net.retry

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

### PR DESCRIPTION
**Pull request by mnecas**
##### SUMMARY

There was some issue with self._connection.follow_link(), so I created fix but don't know what caused it to fail.

Fixes #51422

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ovirt

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gundalow** [comment]
@dominikholler hi, does this PR resolve the issue you reported in https://github.com/ansible/ansible/issues/51422?

**Comment by dominikholler** [comment]
yes, this fixes #51422

**Comment by gundalow** [comment]
@dominikholler Thank you for confirming
@mnecas Could you please add a `changelog/fragment`, then we can get this merged https://docs.ansible.com/ansible/devel/community/development_process.html#making-your-pr-merge-worthy

**Comment by gundalow** [comment]
rebuild_merge

**Pull request merged**
