### PR TITLE
Make sure VARS_CACHE for hosts are updated with the play vars too

### LINKED ISSUE #6979: 1.5.4 :: Precedence issue for variables in arrays and group_vars/all
Hello,
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.4
##### Environment

:: host :: ArchLinux / Debian 7
:: managed :: N/A or any
##### Summary:

Just got issue with variables built on value of other variable defined in global vars (group_vars/all) and then overrided in playbook
Overriden variable value is OK, but array items are not OK - they are still using old-global value
##### Steps To Reproduce:

Part of group_vars/all file:

``` yaml
webserver_root: '/var/www'
webserver_user: 'nginx'
```

Example playbook for debug on local box:

``` yaml
- name: 'Test precedence in array'
  hosts: 127.0.0.1
  connection: local

  vars:

    webserver_root: '/data/www'

    instances:
      - name: "dev"
        docroot: "{{webserver_root}}/dev"
      - name: "stage"
        docroot: "{{webserver_root}}/stage"

  tasks:
   - name: 'debug webserver_root'
     debug: msg="{{ webserver_root }}"

   - name: 'debug instances/items'
     debug: msg="{{ item.docroot }}"
     with_items: instances

   - name: 'debug instances single item'
     debug: msg="{{ instances[0].docroot }}"
```
##### Expected Results:

1.5.3 output is OK and expected: http://pastebin.com/6Nx4QYpf
##### Actual Results:

For 1.5.4 output is: http://pastebin.com/rnk8u5EX
As you see, `items` and `instances[0]` use old value of `webserver_root`

I hope that problem is understandable :)

### PR DESCRIPTION
**Pull request by jimi-c**
Fixes #6979

### CODE REVIEW

**Comment by bcoca** [comment]
doesn't this change precedence?
​

**Comment by jimi-c** [comment]
@bcoca it changes precedence back to what it was pre-1.5.4. Without the above patch, hostvars are currently taking precedence over those defined in `vars:` and `vars_files:`.

**Comment by bcoca** [comment]
ah, so, on purpose, never mind me then.​

**Comment by jimi-c** [comment]
This was merged in via the CLI, github just isn't reflecting it, so closing manually.

**Pull request closed without merging**
