### PR TITLE
Feature libssh2

### PR DESCRIPTION
**Pull request by mgwilliams**
libssh2 is an alternate transport to paramiko, use --connection libssh2 
main feature is a modest (~30%) speed increase per operation, potential improvements include ssh-agent forwarding
requires pylibssh2>=1.0.2

### CODE REVIEW

**Comment by mpdehaan** [comment]
this is a very good patch, though ... dang it ... libssh2 won't even compile against the version I have on CentOS yet.

See detailed emali to the list on this subject.

Hate this happened, was looking forward to having this, though if we can't get it working on CentOS so much (old libssh2 C module?) and agent auth support was only added last month + not having a very good response time on the github issue queue, I'm not sure it's ready.

**Comment by mgwilliams** [comment]
I had started to think this myself. Maybe we just let it die for now.

On Wed, May 30, 2012 at 9:30 PM, Michael DeHaan <
reply@reply.github.com

**Comment by mpdehaan** [comment]
ah cool... I was getting excited about this so I'm glad you concur.

Maybe we can do the message bus thing soon enough as an optional option.   And there are still some tweaks that can be made, for sure.

**Comment by mgwilliams** [comment]
The message bus would need to be self-installing to be very useful.

On Wed, May 30, 2012 at 9:41 PM, Michael DeHaan <
reply@reply.github.com

**Comment by mpdehaan** [comment]
Actually not so much, but ansible can install yum/apt packages over SSH so I don't see this being a big deal.

**Pull request closed without merging**
