### PR TITLE
Backport/2.6/51661

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Backport fix for MySQL server update.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_mysqlserver

### CODE REVIEW

**Comment by abadger** [comment]
This backport is failing tests:
```
AttributeError: 'AzureRMServers' object has no attribute 'mysql_client'\n"
```

There must be something more that needs to be changed on the stable-2.6 branch before this can be applied.

See the shippable tests for more information on the test failure.

**Review by abadger — CHANGES_REQUESTED** [review]
Cannot merge while tests are failing.

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino CI verify fail, Please recheck this PR when you're available! Thanks!

**Comment by abadger** [comment]
@zikalino Once 2.8.0 comes out, 2.6 will move to only getting updates for security issues.  If you want this in 2.6.x, please fix it up ASAP.  Thanks.

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino CI verify fail.  Please update! Thanks!

**Comment by zikalino** [comment]
not essential for 2.6 and too many incompatibilities to resolve. closing.

**Pull request closed without merging**
