### PR TITLE
[2.7] docker_swarm: fix minimal API version

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #49691: fix minimal API version for docker_swarm (see #48657).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_swarm

### CODE REVIEW

**Review by DBendit — APPROVED** [review]
LGTM

**Comment by abadger** [comment]
@felixfontein This neds a changelog fragment before merging to stable-2.7.5

**Comment by felixfontein** [comment]
@abadger sorry, I completely forgot about that. Thanks for noticing that!

**Comment by DBendit** [comment]
Changelog fragment looks good

shipit

**Comment by abadger** [comment]
Merged for 2.7.5

**Pull request merged**
