### PR TITLE
[2.8] Add cookie handling from issue #61672

### PR DESCRIPTION
**Pull request by aliaksandr-dounar-epam**
##### SUMMARY
This commit modifies the signature of `fetch_url` so that a cookie jar can be
specified allowing multiple calls to operate with the same session.  It uses
a similar construct to the `Request` class to initialise the cookie jar if
it is not provided.

The jenkins_plugin module is modified to create a cookie jar if CSRF is
enabled.  This cookie jar is then submitted with every call to fetch_url.
Also changed is to submit the crumb in the request headers rather than
in the data field.

This has been tested with Jenkins 2.176.

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Review by goneri — CHANGES_REQUESTED** [review]
Please, add a .yaml extension to your changelog fragment.

**Comment by aliaksandr-dounar-epam** [comment]
Hi, @goneri - added, thanks.

**Comment by abadger** [comment]
@aliaksandr-dounar-epam Is there a backport of this for 2.9 as well?  I looked for it just now and couldn't find one.  We need to make sure the change goes there as well otherwise people upgrading from 2.8 to 2.9 will experience a regression.

**Comment by aliaksandr-dounar-epam** [comment]
Hi, @abadger! Good point. I've created the same PR for Ansible 2.9 stable branch: https://github.com/ansible/ansible/pull/63323

**Comment by abadger** [comment]
Merged for the 2.8.6 release

**Pull request merged**
