### PR TITLE
Added a git commit module

### PR DESCRIPTION
**Pull request by toshywoshy**
Added a git commit module, the original git module only allows git-clone and git-checkout, my module does commit related functions such as git-push, git-stash, git-add and git-commit

### CODE REVIEW

**Comment by srgvg** [comment]
@toshywoshy looks like your PR's history is b0rked, you'd better rebase and issue a clean PR from a feature branch

**Comment by mpdehaan** [comment]
I'm also a bit curious how you are using this one.

Can you share details?

**Comment by toshywoshy** [comment]
based on @sergevanginderachter I will put in a new pull request and maybe add some documentation

**Comment by srgvg** [comment]
@toshywoshy BTW you don't need to make a new PR, just rebase locally and force push it. Though you might want to use a feature branch to not block your local devel branch.

**Comment by toshywoshy** [comment]
ok, getting out the pr was too tricky, anyway will redo the pull request and added documentation to the module

**Pull request closed without merging**
