### PR TITLE
Adds 'groups' field into ec2 plugin

### PR DESCRIPTION
**Pull request by mynameisdaniil**
It's now possible to map EC2 instance to multiple security groups

### CODE REVIEW

**Comment by mynameisdaniil** [comment]
I think it should be obvious why one may need this feature (and I was surprised to found out about impossibility to map instance to multiple groups, so I decided to fix this)

**Comment by mynameisdaniil** [comment]
Now, one can do this:
(the old way)
local_action:
    module: ec2
    keypair: mykey
    instance_type: c1.medium
    image: emi-40603AD1
    wait: yes
    **group:** webserver
    count: 3

(the new one)
local_action:
    module: ec2
    keypair: mykey
    instance_type: c1.medium
    image: emi-40603AD1
    wait: yes
    **groups:** [default, sshable, system-servers, and-so-forth]
    count: 3

**Comment by mpdehaan** [comment]
We should be able to just set the "group" type in the argument spec to "type=list" and then it will automatically split things on "," and also accept real lists, which avoids adding the extra parameter.

Can you look into testing this?

Thanks!

**Comment by mynameisdaniil** [comment]
Thanks fo the reply. I'll take a look.

**Comment by mynameisdaniil** [comment]
As far as I can see we can't just do "type=list" but we don't need it cause we dealing with yaml and yaml parser is doing all work for us. So we can check type of 'group' field and make decisions based on that type.

**Comment by mpdehaan** [comment]
I think you should still set type='list' unless it causes problems.

This is what allows you to specify comma delimited strings and not pure lists, which people will definitely try to do.

groups=a,b,c  # etc

**Comment by mynameisdaniil** [comment]
Finally did it:
group = dict(type='list')
It wasn't working for the first time you said about it, but it works now. All past day I was using it in real project.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
