### PR TITLE
snmp inventory plugin

### LINKED ISSUE #41443: Inventory plugin for snmp discovery
##### SUMMARY

When operators want to discover their existing network it is very common to rely on snmp.
Today this process must be done outside of ansible in order to create an inventory that can be used by Ansible.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

onesixtyone

##### ANSIBLE VERSION

```
 ansible --version
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

This applies to any version of Ansible.

##### STEPS TO REPRODUCE

Create the onesixtyone.yml with the inventory plugin configuration, specifying the following:

```YAML
plugin: onesixtyone
strict: False
communities:
  - public
addresses:
  - 172.16.96.168
  - 172.17.229.188
  - 172.16.126.174
  - 172.17.20.242
```

```yaml
- name: "Discovery of ios devices using snmp inventory plugin to gather facts"
  hosts: ios

  tasks:
    - ios_facts:


- name: "Discovery of nxos devices using snmp inventory plugin to gather facts"
  hosts: nxos

  tasks:
    - nxos_facts:
```

##### EXPECTED RESULTS

Inventory plugin discover the network devices using snmp queries to sysDescr, and group devices based on platform:

```PYTHON
    def _match_platform(self, text):
        ''' Matches platforms against text in sysDescr
        '''
        platforms = {
            'asa': re.compile(r'^Cisco\sAdaptive\sSecurity\sAppliance'),
            'ios': re.compile(r'^Cisco\sIOS\sSoftware'),
            'iosxr': re.compile(r'^Cisco\sIOS\sXR\sSoftware'),
            'nxos': re.compile(r'^Cisco\sNexus\sOperating\sSystem'),
            'dellos': re.compile(r'^Dell\sApplication\sSoftware'),
            'junos': re.compile(r'^JUNOS'),
            'aruba': re.compile(r'^Aruba\sOperating\sSystem\sSoftware'),
            'eos': re.compile(r'^Arista')
        }
```

##### ACTUAL RESULTS

```
 ansible-inventory -i inventory --list -vvvv
ansible-inventory 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-inventory
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/root/inventory/onesixtyone.yaml did not meet host_list requirements, check plugin documentation if this is unexpected
/root/inventory/onesixtyone.yaml did not meet script requirements, check plugin documentation if this is unexpected
command: ['/bin/onesixtyone', '-c', '/tmp/tmpwrYYWZ', '-i', '/tmp/tmpVcaeZb', '-w', '10'])
output (line): Scanning 4 hosts, 1 communities
output (line): 172.16.96.168 [public] Cisco IOS Software [Gibraltar], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.10.1b, RELEASE SOFTWARE (fc1)  Technical Support: http://www.cisco.com/techsupport  Copyright (c) 1986-2018 by Cisco Systems, Inc.  Compiled Wed 12-Dec-18 02
platform: ios
host: ip-172-16-96-168.eu-central-1.compute.internal
Parsed /root/inventory/onesixtyone.yaml inventory source with auto plugin
{
    "_meta": {
        "hostvars": {
            "ip-172-16-96-168.eu-central-1.compute.internal": {
                "ansible_host": "172.16.96.168", 
                "ansible_network_os": "ios", 
                "snmp_community": "public", 
                "snmp_sysdesc": "Cisco IOS Software [Gibraltar], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.10.1b, RELEASE SOFTWARE (fc1)  Technical Support: http://www.cisco.com/techsupport  Copyright (c) 1986-2018 by Cisco Systems, Inc.  Compiled Wed 12-Dec-18 02"
            }
        }
    }, 
    "all": {
        "children": [
            "ios", 
            "ungrouped"
        ]
    }, 
    "ios": {
        "hosts": [
            "ip-172-16-96-168.eu-central-1.compute.internal"
        ]
    }, 
    "ungrouped": {}
}
```

### PR DESCRIPTION
**Pull request by victorock**
Inventory Plugin for discovery of network devices using snmp

##### SUMMARY

New inventory plugin to discover devices and group them accordingly, based on value of sysDescr.
fixes #41443

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

snmp

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel e3fb86ca8f) last updated 2018/06/12 14:37:24 (GMT +200)

```

##### ADDITIONAL INFORMATION

> Documentation

```YAML
    name: "snmp"
    plugin_type: "inventory"
    version_added: "2.7"
    authors:
      - "Victor da Costa <@victorock>"

    short_description: "Uses snmpv2 query to find devices."

    description:
      - "Use sysDescr to find hosts and group them by platform."
      - "Platforms: asa, ios, iosxr, nxos, dellos, junos, aruba and eos."

    extends_documentation_fragment:
      - constructed
      - inventory_cache

    requirements:
      - pysnmp library
      - netaddr library

    options:
        network:
            description: "CIDRs to scan, separated by comma."
            type: string
            default: "192.168.0.0/24"
        port:
            description: "SNMP Port"
            type: integer
            default: 161
        exclude:
            description: "CIDRs to exclude from the scan, separated by comma."
            type: string
            default: None
        community:
            description: "The SNMP communities to query, separated by comma."
            type: string
            default: "public"

    notes:
        - "Convenient way to generate inventory from existing networks"
        - "TODO: async, snmpv3, platforms++"
```

> Example of snmp.config

```YAML
plugin: snmp
community: mycommunity, public, idontknow
networks: 192.168.99.99/27, 192.168.100.0/23
exclude: 192.168.100.1/32, 192.168.100.2/32
port: 161
```

> ansible.cfg

```INI
[inventory]
enable_plugins = snmp, host_list, script, yaml, ini

```

### CODE REVIEW

**Comment by victorock** [comment]
@webknjaz could you please check why this building is failing?
Looks like a shippable issue...

**Comment by webknjaz** [comment]
It looks like CI failed to talk to Fedora repo, I've restarted failed jobs.

**Comment by victorock** [comment]
@webknjaz Thnx

**Comment by webknjaz** [comment]
@victorock are you going to add some testing around this module?

**Comment by victorock** [comment]
@webknjaz i can, just need to know where it should go...
i've not found any examples in integration tests...

**Comment by webknjaz** [comment]
oh, I guess it's a bit hard in this case, since you don't have actual network devices in CI. unless you can emulate them. we normally have docker containers simulating some parts of systems the modules are supposed to talk to. If you can do something similar - go for it. if not, we can accept this as is.

**Comment by webknjaz** [comment]
> victorock wants to merge 4 commits into ansible:devel from unknown repository

it looks like you removed your fork, which means you won't be able to update this PR anyway

**Comment by bcoca** [comment]
@webknjaz its fine, you just need to recreate branch with same name

**Comment by victorock** [comment]
@bcoca @webknjaz i can close and create a new PR, if you want...

**Comment by victorock** [comment]
@bcoca if you have any ideas about how to build tests for this...

**Comment by bcoca** [comment]
setup snmp service? emulate snmp for several machines? install snmp on existing test targets and use that?

**Comment by victorock** [comment]
Looking for examples (from Ansible CI) that i could use as guideline...do you have any?
I was thinking about overriding the sysDescr in snmpd.conf and spawn different containers to simulate the list of platforms...

**Comment by webknjaz** [comment]
@victorcoder can you do that with containers?

Here's an example of how we wrap running of a simulator container for an integration test: https://github.com/ansible/ansible/blob/devel/test/runner/lib/cloud/foreman.py

And then you can have a playbook (or a role) with your tests, like this: https://github.com/ansible/ansible/tree/devel/test/integration/targets/foreman_inventory

Will this help you?

**Comment by vcastellm** [comment]
@webknjaz a lot, thank you! 😄 and sure @victorock will be happy too 😄

**Comment by ganeshrn** [comment]
@victorock If it helps vyos integration tests run with Shippable CI

**Comment by maxamillion** [comment]
@victorock Is there still a desire to work on this? It's lacking a branch at the moment and is candidate for being closed but don't want to close if there's still a desire to add this functionality. Thank you!

needs_info

**Pull request closed without merging**
