### PR TITLE
yum: docs: name is not required

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Mentioned in https://github.com/ansible/ansible/issues/30088#issuecomment-381220711

Either name or list is required
https://github.com/ansible/ansible/blob/af35983/lib/ansible/modules/packaging/os/yum.py#L1394

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME
yum

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by kustodian** [comment]
shipit

**Comment by resmo** [comment]
shipit

**Review by resmo — APPROVED** [review]

**Comment by Akasurde** [comment]
@kustodian @resmo thanks for the review.

**Pull request merged**
