### PR TITLE
add option to specify the size of the ebs volume for new ec2 instances

### PR DESCRIPTION
**Pull request by jarv**
@lwade or anyone else who uses ec2 this is a small addition I made to the ec2 module if you think it might be useful in core.

### CODE REVIEW

**Comment by lwade** [comment]
Hey @jarv, this is certainly useful.  Do you think you can add a chunk in the docs to clarify that this should only be used with EBS-backed images?

**Comment by jarv** [comment]
@lwade  added a note in the description, let me know if you think there needs to be any additional clarification before merging.

**Comment by mpdehaan** [comment]
Looks like this needs to specify type='int' or otherwise cast the parameter in case things are passed in as key=value options.

Otherwise, looks good to me.

**Comment by lwade** [comment]
@jarv, looks good.

**Comment by jarv** [comment]
updated for type='int'

**Comment by jarv** [comment]
@mpdehaan I believe this is ready to merge.

**Comment by electroniceagle** [comment]
I've merged this pull locally, and am hitting this error.  Not sure if it is related to it being a CentOS instance.  Looking at the code now to see if I can figure out what is going on.

```
TASK: [ec2-fresh-centos-instance | Launch an instance] ************************ 
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: InvalidBlockDeviceMapping: logicalType cannot be modified on root device

FATAL: all hosts have already failed -- aborting
```

**Comment by electroniceagle** [comment]
Yeah, seems like CentOS uses /dev/sda sim linked to /dev/xvde.  This change worked, but obviously breaks Ubuntu.  Although, I still haven't been able to resize the filesystem in CentOS...

```
diff --git a/library/cloud/ec2 b/library/cloud/ec2
index 3d55add..1a9fa84 100644
--- a/library/cloud/ec2
+++ b/library/cloud/ec2
@@ -405,7 +405,7 @@ def create_instances(module, ec2):
         dev_sda1 = boto.ec2.blockdevicemapping.EBSBlockDeviceType()
         dev_sda1.size = root_ebs_size
         bdm = boto.ec2.blockdevicemapping.BlockDeviceMapping()
-        bdm['/dev/sda1'] = dev_sda1
+        bdm['/dev/sda'] = dev_sda1
     else:
         bdm = None

```

**Comment by jarv** [comment]
Given that this only works for Ubuntu I am thinking we should close it, I can try to add centos support but I don't have time unfortunately to look at it right now.

**Comment by electroniceagle** [comment]
I'll reopen this when I get a chance, but best approach for me was to add an optional root_ebs_name argument to allow CentOS to work.

```
diff --git a/library/cloud/ec2 b/library/cloud/ec2
index c1fbf57..fe0d4fb 100644
--- a/library/cloud/ec2
+++ b/library/cloud/ec2
@@ -168,7 +168,7 @@ options:
     description:
       - the private ip address to assign the instance (from the vpc subnet)
     required: false
-    defualt: null
+    default: null
     aliases: []
   instance_profile_name:
     version_added: "1.3"
@@ -199,6 +199,13 @@ options:
       required: false
       default: null
       aliases: []
+  root_ebs_name:
+    version_added: "1.4"
+    desription:
+      - device name of the ebs backend, only applicable when the instance has an ebs backed root
+      required: false
+      default: null
+      aliases: []

 requirements: [ "boto" ]
 author: Seth Vidal, Tim Gerla, Lester Wade, John Jarvis
@@ -426,12 +433,13 @@ def create_instances(module, ec2):
     private_ip = module.params.get('private_ip')
     instance_profile_name = module.params.get('instance_profile_name')
     root_ebs_size = module.params.get('root_ebs_size')
+    root_ebs_name = module.params.get('root_ebs_name')

     if root_ebs_size:
         dev_sda1 = boto.ec2.blockdevicemapping.EBSBlockDeviceType()
         dev_sda1.size = root_ebs_size
         bdm = boto.ec2.blockdevicemapping.BlockDeviceMapping()
-        bdm['/dev/sda1'] = dev_sda1
+        bdm[root_ebs_name] = dev_sda1
     else:
         bdm = None

@@ -680,6 +688,7 @@ def main():
             instance_ids = dict(type='list'),
             state = dict(default='present'),
             root_ebs_size = dict(default=None, type='int'),
+            root_ebs_name = dict(default='/dev/sda1', ),
         )
     )
```

**Comment by billumina** [comment]
Is this available in any release?

**Comment by jarv** [comment]
@billumina it isn't unfortunately. I'm using a forked version in our own repo since my proposed change only works on ubuntu images. There was a proposed patch for it to work in centos as well but I haven't tested it.

**Comment by electroniceagle** [comment]
Actually, this feature works now with the volumes support in ansible 1.6.

```
- name: get latest ubuntu ami for $region
  shell: ubuntu-ami-locator --itype {{ itype }} --region {{ region }} --suite {{ suite }} --virttype {{ virttype }}
  register: ami

# This needs to use "module" notation because group might be a YAML list
- name: Launch an instance
  local_action:
    module: ec2
    keypair: '{{ keypair }}'
    ec2_access_key: '{{ ec2_access_key }}'
    ec2_secret_key: '{{ ec2_secret_key }}'
    region: '{{ region }}'
    group: '{{ security_group }}'
    instance_type: '{{ instance_type }}'
    image: '{{ ami.stdout }}'
    wait: yes
    count: 1
    volumes:
        - device_name: /dev/sda1
          volume_size: '{{ root_ebs_size }}'
```

**Pull request closed without merging**
