### PR TITLE
 Added GPL header to vmware_inventory.py

### PR DESCRIPTION
**Pull request by Shaps**
##### SUMMARY
Added GPL header to vmware_inventory

Addresses #24343 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_inventory.py

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (gpl_header_vmware_inventory c519c6f091) last updated 2017/05/10 13:20:09 (GMT +000)
  config file =
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /vagrant/lib/ansible
  executable location = /vagrant/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by gundalow** [comment]
@cgar
@hryamzik
@mattclay
@rafstef
@nerzhul
@jctanner

We need you to all sign off on this.

**Review by mattclay — APPROVED** [review]

**Review by nerzhul — APPROVED** [review]

**Review by cgar — APPROVED** [review]

**Comment by nerzhul** [comment]
ship_it

**Comment by Akasurde** [comment]
@hryamzik
@rafstef
@jctanner

We need you to all sign off on this.

**Comment by calfonso** [comment]
rebuild_merge

**Pull request merged**
