### PR TITLE
Adding support for macros {$ANSIBLE_HOST} and {$ANSIBLE_PORT}, provid…

### PR DESCRIPTION
**Pull request by tuxick**
…ing meta data

##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
ansible 2.3.2.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by D3DeFi** [comment]
Unfortunately, your contribution can no longer be merged to [ansible/ansible](https://github.com/ansible/ansible). The way how community content is being shipped within Ansible is [changing](https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#collections) as of right now with the preparations for Ansible 2.10. 

All development regarding Zabbix content has been moved to a separate [ansible-collections/community.zabbix](https://github.com/ansible-collections/community.zabbix) repository. Please resubmit your PR against the new repository with the changes we have requested in the previous comments and reviews (if any).

This separation now allows us to address your contribution much quicker than before. We are giving each contributor a few weeks (roughly a month) notice to move his/hers PRs to a new repository.

After a month, we will try to migrate all leftover PRs by ourselves, but author information may get lost in this way.

Sorry for the inconvenience and thank you for the understanding.

close_me

**Comment by D3DeFi** [comment]
Oh boi, this one old :)

@tuxick, we've adopted orphaned zabbix inventory script in the above mentioned collections repo. If you are still up for it, your contributions now won't end up in a /dev/null.

**Comment by D3DeFi** [comment]
bot_status

close_me

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.zabbix.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
