### PR TITLE
add os_routers_info module

### PR DESCRIPTION
**Pull request by bverschueren**
##### SUMMARY
introduce new os_routers_info module

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
os_routers_info

### CODE REVIEW

**Comment by csmart** [comment]
Thanks. I did some basic testing and it worked well.

**Review by cloudnull — APPROVED** [review]
shipit

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Review by sshnaidm — CHANGES_REQUESTED** [review]
Because we moved Openstack Ansible modules to Openstack repositories, please submit all changes from openstack modules to Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack Thanks for your contribution and sorry for inconvienience.

**Comment by bverschueren** [comment]
duplicated this to https://review.opendev.org/703927

**Pull request closed without merging**
