### PR TITLE
remove query/q

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

retract as current implementation is not working as intended and its too late in the cycle to rework.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

query
##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by sivel** [comment]
I'm not sure I understand what is not working as intended.  To my knowledge, `query` is working as intended, or at least my intention.

**Comment by sivel** [comment]
I'm not sure I understand what is not working as intended.  To my knowledge, `query` is working as intended, or at least my intention.

**Comment by bcoca** [comment]
@sivel as author i never intended it to be tied to wantlist, it should be more flexible about types it takes and returns.

**Comment by sivel** [comment]
I'm still a little confused.  `wantlist` does not force returning a list.  `wantlist=True` actually means, "don't try to join elements with commas".

So `wantlist=True` should allow the lookup to return any datatype without being munged.

I still don't understand what exactly is not working.

As with everyone, we ask "what is not working?".  I still haven't seen an example of what is not working.

**Comment by bcoca** [comment]
As it depends on lookup, currently it can only return a list, wantlist is used to force lookup to not return a string. 

As for a non-working example, try to use create a plugin that you can call from query and NOT return a list.

**Comment by sivel** [comment]
> As it depends on lookup, currently it can only return a list, wantlist is used to force lookup to not return a string

As I just mentioned, that is incorrect.  `wantlist` doesn't force a list.  Nor does `_lookup`.

```
    - assert:
        that:
          - q('passthrough', None) == None
          - q('passthrough', 'bob') == 'bob'
          - q('passthrough', {}) == {}
          - q('passthrough', 1) == 1
```

```
class LookupModule(LookupBase):
    def run(self, terms, **kwargs):
        return terms[0]
```

That works.  As you can see, the lookup can return any data type it wants.  There is no enforcement there.

As I mentioned `wantlist=True` does not have anything to do with lists.  It really means "don't join elements with commas".

`q` is tied to `terms` being a list, but that isn't necessarily a bad thing.  The lookup can chose to handle that however it wants.

**Comment by bcoca** [comment]
ah, yes, my bad, i was testing with plugin that was itself modified to always return lists. In any case the input is still a problem. Lookup works 'better' in this case as it does not require pythonisms to pass in vars instead of having to force feed lists/dicts inline:

```
query('plugin', mylist)
```
will actually take mylist as a single item while

```
lookup('plugin', mylist)
```
will actually correctly use it as a full list.

**Pull request merged**
