### PR TITLE
mysql_replication module added

### PR DESCRIPTION
**Pull request by banyek**
I've finished a module for ansible, it is called as
'mysql_replication' and of course you can manage mysql replication
features with that.
It can operate in different ways, you can check replication master's
status, replication slave's status, you can change replication
parameters, and stop / start slaves. The documentation is speaks for
itself I guess

### CODE REVIEW

**Comment by nicolas-g** [comment]
by the PR being close does that mean the mysql_replication module won't be included in Ansible ?

**Comment by banyek** [comment]
I have put it back again, just I made an another module (mysql_replication) and wanted to make a pull request for that too. So, I've closed the pull request, made the two branches, and created the pull req's to the both of the modules.

**Comment by banyek** [comment]
https://github.com/ansible/ansible/pull/3701
https://github.com/ansible/ansible/pull/3702

**Comment by banyek** [comment]
I have put it back again, just I made an another module (mysql_replication)
and wanted to make a pull request for that too. So, I've closed the pull
request, made the two branches, and created the pull req's to the both of
the modules.

2013/7/30 Nicolas G. notifications@github.com

> by the PR being close does that mean the mysql_replication module won't be
> included in Ansible ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3280#issuecomment-21797048
> .

## 

"Before enlightenment, I chopped wood and carried water. After
enlightenment, I chopped wood and carried water"

**Comment by nicolas-g** [comment]
cool , so is that ready to be merged with next Ansible 1.3 release ?

**Comment by banyek** [comment]
I don't know, maybe ask the ansible guys :)

2013/7/30 Nicolas G. notifications@github.com

> cool , so is that ready to be merged with next Ansible 1.3 release ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3280#issuecomment-21798301
> .

## 

"Before enlightenment, I chopped wood and carried water. After
enlightenment, I chopped wood and carried water"

**Comment by nicolas-g** [comment]
haha, will do. 

By the way how can I use your module if i's not part of the standard Ansible ? do you have any documentation somewhere ?

**Comment by mpdehaan** [comment]
We have quite a queue to go through for 1.3, and this is in that queue, so
yes!

Stay tuned!

To use non core modules, easiest is to just drop into a ./library directory
alongside your top level playbooks.

**Comment by banyek** [comment]
Just put it under library/database/ and you can start using it. Docs can be found inline, and on ops.kinja.com

**Comment by nicolas-g** [comment]
I'm still not able to figure out how to use your module, I couldn't find it anywhere in your github account and also there is no documentation on ops.kinja.com apart from http://ops.kinja.com/mysql-replication-module-for-ansible-514258316 .

Regards,
Nicolas.

**Comment by banyek** [comment]
You can contact me on banyek 'at' gawker.com. I'll help you, if you asks.

**Comment by Bairagi** [comment]
This may help (ignore the template variables), u can also change the hosts:
https://gist.github.com/Bairagi/9577125

**Pull request closed without merging**
