### PR TITLE
VMware: set product information to VM

### PR DESCRIPTION
**Pull request by ckurdekar**
PR to set the Product Information and ovf transport mode to the VM.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ADDITIONAL INFORMATION
Modified vmware_guest to set product information and to set ovf transport mode

```paste below

```

### CODE REVIEW

**Comment by gundalow** [comment]
@ckurdekar Hi, PRs should be made against the `devel` branch. 
Once code is merged we create backport PRs for bug fixes only into the `stable-2.x` branch

**Comment by ckurdekar** [comment]
> @ckurdekar Hi, PRs should be made against the `devel` branch.
> Once code is merged we create backport PRs for bug fixes only into the `stable-2.x` branch

done, PR raised against devel

**Comment by Akasurde** [comment]
@ckurdekar Thanks for the PR.

**Comment by mattclay** [comment]
Closing and re-opening to update CI.

**Comment by ckurdekar** [comment]
@mattclay Can you help me to understand failure cause for https://app.shippable.com/github/ansible/ansible/runs/113025/108/tests... have introduced 2 new properties, one is setting default value of transport mode if not provided and another is optional to set Product Information to VM if provided. Is setting default transport mode causing this failure

**Comment by ckurdekar** [comment]
@mattclay Are you going to take this PR for further validations?

**Comment by Akasurde** [comment]
@ckurdekar Thanks for the PR. We discussed about this PR in IRC meeting (25 March 2019) to move this feature to its own module rather than adding it to `vmware_guest`. Let us know if sounds OK to you so that we can take further steps for this. 

Thanks.

needs_info

**Comment by ckurdekar** [comment]
> @ckurdekar Thanks for the PR. We discussed about this PR in IRC meeting (25 March 2019) to move this feature to its own module rather than adding it to `vmware_guest`. Let us know if sounds OK to you so that we can take further steps for this.
> 
> Thanks.
> 
> needs_info

Okay, are you going to create any new module to allow to set product information and allow to set OVF transport mode?

**Pull request closed without merging**
