### PR TITLE
Added a proxy and a use_proxy option to get_url

### PR DESCRIPTION
**Pull request by dorfsmay**
Note that I did not create the default behaviour of using the environment variable, this is a default in urllib2, and this happens with the current ansible get_url module, which is giving us troubles right now, hence this new option.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I don't like this behavior.

It should always always use the environment proxy settings if set, if that requires changes to the way urllib is being invoked, we should make those changes.

**Comment by mpdehaan** [comment]
See also this thread:  https://groups.google.com/group/ansible-project/browse_thread/thread/bd5afa9f8752e8f9

**Comment by dorfsmay** [comment]
On 2013-03-01 18:36, Michael DeHaan wrote:

> I don't like this behavior.
> 
> It should always always use the environment proxy settings if set.

curl, wget etc... all provide options to disable automatic proxies.
Why should get_url not be able have the same option?

## 

Yves.                                                  http://www.SollerS.ca/
                                  Unix/Linux and Python specialist in Calgary.
                                                        http://blog.zioup.org/

**Comment by mpdehaan** [comment]
use_proxy defaulting to yes is one thing, and I'm fine with that.

having to pass what proxy to use when we already have an environment keyword is another thing

you should not have to specify what proxy to use in the ansible module when we have a generic facility for it.

**Comment by dorfsmay** [comment]
On 2013-03-01 18:57, Michael DeHaan wrote:

> use_proxy defaulting to yes is one thing, and I'm fine with that.
> 
> having to pass what proxy to use when we already have an environment keyword
> is another thing
> 
> you should not have to specify what proxy to use in the ansible module when we
> have a generic facility for it.

These are two separate options. I can split it in two commits if you prefer, 
or even completely remove the second one:

-use_proxy= defaults to yes, so if you don't set it, the behaviour is exactly 
the same as it is currently (it will use the environment variable if present 
on the target host). It's only use is to disable that behaviour.

-since the logic was close enough, I simply added proxy= in case somebody 
needed to specify a proxy.

**Comment by mpdehaan** [comment]
On Fri, Mar 1, 2013 at 11:57 PM, Yves Dorfsman notifications@github.comwrote:

> On 2013-03-01 18:57, Michael DeHaan wrote:
> 
> > use_proxy defaulting to yes is one thing, and I'm fine with that.
> > 
> > having to pass what proxy to use when we already have an environment
> > keyword
> > is another thing
> > 
> > you should not have to specify what proxy to use in the ansible module
> > when we
> > have a generic facility for it.
> 
> These are two separate options. I can split it in two commits if you
> prefer,
> or even completely remove the second one:
> 
> -use_proxy= defaults to yes, so if you don't set it, the behaviour is
> exactly
> the same as it is currently (it will use the environment variable if
> present
> on the target host). It's only use is to disable that behaviour.

Ok, I'll take a pull request for the use_proxy=no, default yes part.
 That's fine.

We want to use the environment keyword to specify the proxy if not already
set, versus the "proxy=" though.

Can you update this to just include the first part?

**Comment by dorfsmay** [comment]
> Ok, I'll take a pull request for the use_proxy=no, default yes part.
> That's fine.
> 
> We want to use the environment keyword to specify the proxy if not already
> set, versus the "proxy=" though.
> 
> Can you update this to just include the first part?

Fair enough. I'll close this one and re-submit with only the first part.

**Comment by dorfsmay** [comment]
Closing. Resubmitting the use_proxy part in pull request # 2273.

**Pull request closed without merging**
