### PR TITLE
[2.9] Fix ansible-test change detection traceback.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #68519 to stable-2.9.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test

### CODE REVIEW

**Comment by felixfontein** [comment]
All PRs this depended on have been merged. I rebased to latest stable-2.9 so the other commits are gone.

@nitzmahone @mattclay @relrod this is ready now :)

**Comment by mattclay** [comment]
This backport has been reverted since it was contributing to tracebacks in CI.

**Comment by mattclay** [comment]
See https://app.shippable.com/github/ansible/ansible/runs/168736/1/console for failures.

**Comment by felixfontein** [comment]
@mattclay it could be that https://github.com/ansible/ansible/pull/69377/commits/f55015754f7a1482ce8dd73656c864f1a56c8e4b (from https://github.com/ansible/ansible/pull/69377) fixes the problem.

**Comment by felixfontein** [comment]
At least with current stable-2.9, change detection for collections does not work. (Import analysis is erroring: `ERROR: Cannot determine path for module_utils import: ansible_collections.community.crypto.crypto.pyopenssl_support`)

**Comment by mattclay** [comment]
@felixfontein Yes, backports to resolve the change detection issues are still needed. My primary concern yesterday was fixing CI so that we could continue with the release.

**Pull request merged**
