### PR TITLE
Supports new systemctl output message for chroot

### PR DESCRIPTION
**Pull request by lcastelli**
The message generated by systemctl has been updated in https://github.com/systemd/systemd/commit/9321e23c40f3dc6bd785105ce882cbad6447a1c6, which requires a corresponding change in the systemd module.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/systemd.py`
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by samdoran** [comment]
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and integration tests. See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

**Comment by lcastelli** [comment]
I've added the changelog fragment now. Sorry I'm not familiar with the integration test infrastructure, and I'm not sure how to test this. For the record, integration testing this requires a proper chroot setup, with systemd installed in the chroot. If you have some pointers on how to set such test up, that would be appreciated.

**Comment by samdoran** [comment]
Integration tests for this module are located in `test/integration/targets/systemd`. The integration tests are (mostly) Ansible roles that get run on each system in the test matrix.

Most systems in the test matrix are Docker containers. The only exceptions are FreeBSD, macOS, and RHEL, which are virtual machines.

Adding new integration tests would really mean just adding Ansible tasks to the existing test role. This could include the necessary steps for creating a chroot environment. Note that since these test containers are used by multiple tests, any changes made to the test container should also be rolled back at the end. This can be done using handlers.

The only problem I found is that none of the distributions in our test matrix have a new enough version of systemd to test this. What system are you using that that has systemd >= 246?

It still may be worthwhile to add the tests so that when we do get a system with systemd >= 246, this will be tested.

**Comment by lcastelli** [comment]
Thanks for the pointers, I have now added some test for this. Rather than setting up a chroot, I simply set the SYSTEMD_OFFLINE environment variable, which has the same effect as far as systemd is concerned. As part of that I also noticed that ansible currently fails if that variable is set, so I fixed that too.

The new systemd version has been recently shipped in Arch-Linux.

**Review by samdoran — APPROVED** [review]

**Comment by samdoran** [comment]
Please create a [backport PR](https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs) against `stable-2.9` and `stable-2.10` for this to be included in previous versions.

**Pull request merged**
