### PR TITLE
Fix "canonical" typo in win_host examples

### PR DESCRIPTION
**Pull request by jamesmarshall24**
##### SUMMARY

Fix canonical typo in examples documentation for 2.9

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

win_hosts

### CODE REVIEW

**Comment by gundalow** [comment]
Already fixed in Collection https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_hosts.py so it's right to merge directly into stable-2.9

**Comment by acozine** [comment]
Backport of https://github.com/ansible-collections/community.windows/pull/63.

**Review by samccann — APPROVED** [review]

**Comment by acozine** [comment]
rebuild_merge

**Comment by acozine** [comment]
Ah, I don't think the rebuild_merge works for backports.

**Pull request merged**
