### PR TITLE
inventory and indentation

### PR DESCRIPTION
**Pull request by skvidal**

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged, thanks.  Curious why that got missed on test coverage.

**Comment by jhoekx** [comment]
For me, this breaks inventory in tests and real-life.

Inventory.groups should be a list, so get_group() should return a list?
If it's a dict, where does that one come from in your case?

**Comment by mpdehaan** [comment]
jhoekx is correct, this breaks tests.

reverted and pushed

**Comment by mpdehaan** [comment]
get_groups does return a list.   I am suspecting there is a change to one of the other files maybe that didn't get committed?  I'm actually fine with it returning a list.

**Comment by skvidal** [comment]
found it

```
def _groups_from_override_hosts(self, list):
    # support for playbook's --override-hosts only
    all = Group(name='all')
    for h in list:
        all.add_host(Host(name=h))
    return dict(all=all) 
```

that returns groups as a dict:
if

```
 if host_list:   
        if type(host_list) == list:
            self.groups = self._groups_from_override_hosts(host_list)
```

**Comment by mpdehaan** [comment]
Ok, so _groups_from_override_hosts needs to be changed to return just the list then.  Cool.

**Pull request merged**
