### PR TITLE
New module: pkgutil (for Solaris)

### PR DESCRIPTION
**Pull request by dermute**
Pkgutil is a package management utility for Solaris, which works with 3rd party repositories (like OpenCSW).
I wrote this module based on svr4pkg and added an installation option called "latest".

It is fully tested and working with the latest version 2.6.5 of pkgutil.

I hope you like it. For more information about pkgutil visit http://pkgutil.net/

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you point me to some information about how widely used pkgutil is?

**Comment by dermute** [comment]
As Sunfreeware has been shutdown for free usage, OpenCSW is the only big repository for custom software packages. And OpenCSW uses pkgutil. I think everybody who wants to use a wide range of custom packages is using OpenCSW atm. But I dont know exactly....

**Comment by rrtj3** [comment]
I use pkgutil and would use this module.

On Sat, Aug 10, 2013 at 3:28 AM, Alexander Winkler <notifications@github.com

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request closed without merging**
