### PR TITLE
added missing resource_group description in return value

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Added missing documentation piece.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
azure_rm_postgresqlserver_facts

##### ANSIBLE VERSION
2.7

### CODE REVIEW

**Comment by yuwzho** [comment]
In this facts module, the resource_group is required? So there is no way to get all resources in the subscription?

https://github.com/ansible/ansible/blob/60055aa825748196441e2011bbcc2c96fc2f9017/lib/ansible/modules/cloud/azure/azure_rm_postgresqlserver_facts.py#L144-L148

**Comment by zikalino** [comment]
@yuwzho it's actually returned, so I added to the documentation. actually, I will add list() as well, as it's available from the api.

**Comment by yuwzho** [comment]
@zikalino My concern is that there is no `list_all()` interface in this facts module

**Comment by yuwzho** [comment]
shipit

**Review by yuwzho — APPROVED** [review]

**Pull request merged**
