### PR TITLE
ce_snmp_target_host: update to fix bug: None has no 'lower()' function.

### PR DESCRIPTION
**Pull request by yuandongx**
##### SUMMARY

update to fix bug: None has not 'lower()' function.

##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
##### ADDITIONAL INFORMATION

line 496:
None has no  'lower()' function.It will be a string or None, however!

```paste below

```

### CODE REVIEW

**Comment by akatch** [comment]
Is this issue in reference to an existing bug? More specifically, *should* None have a lower() function?

**Comment by xuxiaowei0512** [comment]
> Is this issue in reference to an existing bug? More specifically, _should_ None have a lower() function?

None can not lower.

**Comment by resmo** [comment]
please add a doc fragement https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

**Comment by zhongjun2** [comment]
shipit

**Comment by xuxiaowei0512** [comment]
bot_status

**Comment by xuxiaowei0512** [comment]
bot_status

**Comment by hwDCN** [comment]
bot_status

**Comment by hwDCN** [comment]
shipit

**Comment by hwDCN** [comment]
bot_status

**Review by yuandongxx — APPROVED** [review]
shipit

**Comment by xuxiaowei0512** [comment]
shipit

**Comment by hwDCN** [comment]
shipit

**Comment by hwDCN** [comment]
bot_status

**Comment by resmo** [comment]
unsure why this isn't automerged even tagged so, giving the bot a hand.

**Comment by xuxiaowei0512** [comment]
@resmo There may be some thing wrong about bot.
And thank you so much!

**Pull request merged**
