### PR TITLE
Improve perf of azure_rm_virtualmachinescalesetinstance_info

### LINKED ISSUE #62639: azure_rm_virtualmachinescalesetinstance_info is very slow for VMSS with large number (100s) of instances
##### SUMMARY

The performance of azure_rm_virtualmachinescalesetinstance_facts is very poor for VMSS with large number (100+) of instances

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachinescalesetinstance_info

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/arviadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/arviadmin/env/lib/python3.6/site-packages/ansible
  executable location = /home/arviadmin/.local/bin/ansible
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

##### STEPS TO REPRODUCE

1. Create an Azure Virtual Machine Scale set with 500 instances
2. Run the playbook below to get information for the VMSS instances

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - azure_rm_virtualmachinescalesetinstance_facts:
     resource_group: "some_rg"
     vmss_name: "somevmss"
    register: vmss_facts
  - debug:
     var: vmss_facts
```

##### EXPECTED RESULTS

Azure CLI takes ~ 20 seconds to list equivalent information.

##### ACTUAL RESULTS

Ansible module takes ~ 3 minutes to return

```paste below

```

### PR DESCRIPTION
**Pull request by arvindshmicrosoft**
Fixes #62639 by getting instance_view in single call

##### SUMMARY

The root cause of the slowness described in the associated issue is that earlier this module would call virtual_machine_scale_set_vms.get_instance_view repeatedly in a loop, making the module an O(n) cost operation. This PR improves the performance by expanding the instance_view information when listing the VMSS instances, thereby eliminating the need to query that at a per-instance level.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_virtualmachinescalesetinstance_info

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by arvindshmicrosoft** [comment]
Hello @Fred-sun is there anything I can do to help speed up the PR review?

**Comment by Fred-sun** [comment]
@mybayern1974 @yungezz All checks have passed, please take a review and push the PR for merged. Thank you very much!

**Comment by Fred-sun** [comment]
@mybayern1974 There are few changes in this PR, please help review and promote the merger as soon as possible. Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang review_need

**Comment by Fred-sun** [comment]
@arvindshmicrosoft Thank you for your contribution. Because of the current situation, the community staff is busy with other urgent cases and cannot review for the time being. As soon as they have time, I will notify the review and merger as soon as possible. Thank you very much!

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by pmoust** [comment]
Could we get some 👀 here @mybayern1974 @yungezz ?

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang

**Comment by arvindshmicrosoft** [comment]
Hello again @Fred-sun @gavinfish @haiyuazhang thanks for your efforts to review and approve other PRs from me and our team. Is there anything we can do to help for this one? It provides quite a performance improvement for larger VMSS, hence the keenness to get this merged.

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang Please help review and push for the PR merge when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
@arvindshmicrosoft Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by arvindshmicrosoft** [comment]
@Fred-sun ok you mean raise a new PR (and issue) in that repo? I am willing to do so, but I do hope that there will be some traction on these once they move to a different repo. This PR is close to **6 months old**. I don't want to rant here but I assume you can understand my feelings.

**Pull request closed without merging**
