### PR TITLE
Reenable 'test' label for test related pull requests

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
Reenable `test` label for test related pull requests

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

##### ANSIBLE VERSION
```
2.5.0
```

##### ADDITIONAL INFORMATION
See:
- https://github.com/ansible/ansible/pull/29660#issuecomment-335157115
- https://github.com/ansible/ansibullbot/issues/764

### CODE REVIEW

**Comment by bcoca** [comment]
@pilou- I believe you want test_pull_requests instead, we don't really want multiple labels for the same thing. 

cc @mattclay  to correct me if im wrong.

**Comment by pilou-** [comment]
I agree, we don't want multiple labels for the same thing :)
`test` label was chosen, see https://github.com/ansible/ansibullbot/issues/764#issuecomment-334536006.

**Comment by bcoca** [comment]
^ we had discussion in core meeting which iirc ended up in the reverse of that ticket.

Also we might want to add 'test issues' in the future for reporting bugs with tests and keep the parity with features & bugs.

**Comment by pilou-** [comment]
Then `is:pr label:test` or `is:issue label:test` could be used, one label could be used on issues and pull requests, that's not a problem.

ping @gundalow

**Comment by mattclay** [comment]
In the Testing Working Group we agreed to go with a single `test` label:

https://meetbot.fedoraproject.org/ansible-meeting/2017-10-05/testing_working_group.2017-10-05-17.00.html

I don't recall this being discussed in the core meeting.

**Pull request merged**
