### PR TITLE
Add a config option for rackspace inventory cache

### PR DESCRIPTION
**Pull request by matburt**
Adding a config and environment variable option for tuning the cache age
check in the rackspace inventory module

### CODE REVIEW

**Comment by sivel** [comment]
Can you please update rax.ini to include a description of this as well as an example configuration to follow what already exists?

**Comment by matburt** [comment]
Done!  Thanks!

**Comment by sivel** [comment]
Cool.  Looks good.

**Comment by sivel** [comment]
Merged, thanks!

**Pull request merged**
