### PR TITLE
Windows: Path integration tests

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
These integration tests were used for testing the exact behaviour of
Ansible for YAML-style syntax and key=value syntax.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

Windows integration tests

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests with:

```
{
    "changed": false, 
    "failed": true, 
    "hint": "Beware that you may have special characters included like \\t or \\v.", 
    "msg": "Get-AnsibleParam: Parameter 'src' has an invalid path 'https://ansible.com/' specified."
}
```

**Comment by mattclay** [comment]
The failure is in the win_shortcut test: 

https://app.shippable.com/github/ansible/ansible/runs/27678/9/tests

**Comment by dagwieers** [comment]
@mattclay Yup, the fix for that one is in PR #26488, @nitzmahone was going to merge that one.

**Comment by dagwieers** [comment]
shipit

**Comment by jhawkesworth** [comment]
since #24678 has been merged, closing and opening to re-trigger CI

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
