### PR TITLE
Add module cpm_user to read, create, edit and delete users on WTI devices

### PR DESCRIPTION
**Pull request by syncpak**
##### SUMMARY
Added Western Telematic Inc. (WTI) module allowing communication with WTI OOB and PDU devices via RESTful calls and http/https
Add module cpm_user to read, create, edit and delete users on WTI devices

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
cpm_user

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (cpm_metering 9d9b9cb2f5) last updated 2018/08/21 15:45:19 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kenp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kenp/ansible/lib/ansible
  executable location = /home/kenp/ansible/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by syncpak** [comment]
@dmobergIT, @mattsene, @vientiane Here is the module for modifying users. If you need playbook examples user these: https://github.com/syncpak/playbooks/tree/master/cpm_user
You can reach me here @syncpak or @wtinetworkgear or by emailing service@wti.com and mention Ansible, thanks

**Comment by dmobergIT** [comment]
I can add and delete users, would you be confidant enough for this to be used on all our units ?

**Comment by syncpak** [comment]
Hi @dmobergIT, as far as the underlying RESTful calls that the modules makes i am 100% they are good, they have been in production since 2017. As far as this Ansible module itself, we have tested it in house and its works, but the Ansible maintainers run tight ship, I am sure there will be changes to this module (its our first). So I would wait for a wide deployment of testing. Just FYI, look at the[ power metering lookup](https://github.com/ansible/ansible/pull/44491). (shameless plug)

**Comment by mmorrisdev** [comment]
The way I am reading this module, it works on both your DSM and VMR line of products ?

**Comment by dmobergIT** [comment]
Also what "Access Level:" do I need to be if I want to edit/add/delete users ? read users ?

**Comment by syncpak** [comment]
@mmorrisdev, yes this module works with our DSM, CPM and VMR line. basically any device we have shipped in the last 5 years. The other [lookup plugin called cpm_metering](https://github.com/ansible/ansible/pull/44491) since it reports the power/current will only work with our CPM and VMR power units.

**Comment by syncpak** [comment]
@dmobergIT, to Add, Edit and Delete (adduser, edituser or deleteuser) the "Access Level" on your "cpm_username" parameter needs to have Administrator rights. To read user information (getuser) your "cpm_username" parameter needs to have either SuperUser or Administrator rights. If your try to do these with insufficient access levels, your HTTP return code will be 401. You can read the underlying RESTful[ information here](https://ftp.wti.com/pub/TechSupport/Restful_WTI/current/api/api.html#).

**Comment by mattsene** [comment]
Do the users created apply to all the login services of the box? i.e. SSH, Web, and even , gulp,  telnet.

**Comment by syncpak** [comment]
@mattsene, Yes the user is created globally, but when you create the user, please set the appropriate user_accessssh, user_accessserial, user_accessweb, user_accessapi depending on what service you want them to have access to. Plus the user_accesslevel can be set to allow different properties tied to that account.  If you have any other questions you can get me at service@wti.com

**Comment by mattsene** [comment]
When I create the user is it immediately enabled or is there a period of time before the user takes affect ?

**Comment by dmobergIT** [comment]
Everything so far has worked great. I have created, edited, deleted users. How many deployments do you thing would be OK with this code not checked in ?

**Comment by syncpak** [comment]
@dmobergIT you may want to delay, when the community folks do look it i am sure there will be changes.

**Comment by syncpak** [comment]
Hi @samdoran , we have a module (this one) and another lookup plugin (https://github.com/ansible/ansible/pull/44491), i know it was kind of late into the cycle considering the cut off is Friday. Can we save these or roll them over until the next release? How would that work? Thanks

**Comment by samdoran** [comment]
@syncpak I'm going to go ahead and merge this so it will make the cutoff, but we need to change the `str()` uses before final release to ensure this works properly with Python 2 and 3.

See [General Guidelines](https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html?highlight=to_native#general-guidelines) for background.

**Comment by syncpak** [comment]
@samdoran that is fantastic! If i change the `str()` to `to_text()` that is acceptable ?

**Comment by samdoran** [comment]
@syncpak A few things on the argument strings:

1) Rather than using `+` use Python's string formatting, either `%` or `.format()`. Using the `+` operator is slower since it results in one operation for each string that is concatenated.

2) In this case, use `to_native()` rather than `str()`, which will use the correct native string type for the Python version.

**Comment by syncpak** [comment]
@samdoran Thanks, i created a pull request (https://github.com/ansible/ansible/pull/45044) with the changes.

**Pull request merged**
