### PR TITLE
Optionally unarchive a file already on the remote machine

### PR DESCRIPTION
**Pull request by pib**
Simple change to the unarchive action to allow unarchiving of a file that's already on the remote machine, perhaps one that was downloaded via get_url, for example.

### CODE REVIEW

**Comment by pib** [comment]
Whoops, this needs some fixes.

**Comment by mpdehaan** [comment]
Can you please share an example so I can understand this better?

I don't understand how a machine can be already on a remote machine :)

**Comment by pib** [comment]
Sorry, that was a typo. I've fixed it now.

Essentially, I'm doing two tasks like so:

```
- name: Downloading foo.tar.gz
  get_url: dest=/tmp/foo.tar.gz url=http://foo.com/foo.tar.gz

- name: Unpacking foo.tar.gz to /opt/foo
  unarchive: src=/tmp/foo.tar.gz dest=/opt/foo copy=no
```

Without the `copy=no`, it would look on the machine I'm running the playbook from, rather than on the remote machine where it just downloaded to.

**Comment by mpdehaan** [comment]
Thanks, that makes sense.

**Comment by klemmster** [comment]
:+1: 
I was missing that feature too, today.

**Comment by risaacson** [comment]
@pib Thanks for your PR on this. I did some work to make it current and to fix some bugs. I am going to close out this PR as soon as I merge mine in the morning. I merged your changes into a local branch to make sure that you get the credit for the work. Thanks again!

**Pull request merged**
