### PR TITLE
Add dynamic winrm support for openstack windows hosts

### PR DESCRIPTION
**Pull request by morphje**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
contrib/inventory/openstack.py 

##### ANSIBLE VERSION
ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### SUMMARY
This pull request started out to fill out the ansible_password for windows hosts. I use my pass lookup (see https://github.com/morphje/ansible_pass_lookup) for this functionality, but i gathered that i could use fill the ansible_password with the lookup, so that my password store would be accessed with the dynamic inventory. This way my passwords are protected with gpg

To make this pull request more generic, I added a way to create your own lookups and i added the other winrm variables to it too, like the admin user. All you have to do is to ensure the windows hosts are in a group called windows. This has to be set within the properties of the machine (eg. #openstack server set --property groups=windows,foo,bar test44)

You can substitute the lookup to anything, like credstash or even csv *brrrr*
You can change the winrm_password_lookup_var to id (uuid from openstack) or interface_ip in case you have those keys to differentiate your hosts in your database. the name key would probably be most logical. Be sure to escape the curly braces with double braces ( {{ becomes {{{{ )

clouds.yml 
```
---
ansible:
  use_hostnames: true
  winrm_password_lookup_string: "{{{{ lookup('pass', 'content/hosts/{}/administrator') }}}}"
  winrm_password_lookup_var: name
  winrm_admin_user: ansible
  winrm_ignore_certificate: True
clouds:
  content:
    auth:
      auth_url: https://identity.openstack.private/v2.0
      project_name: projectid/projectname
      username: user@openstack
      password: xxx
```
output from openstack python client show the properties
```
openstack --os-cloud content server show test44
+--------------------------------------+------------------------------------------------------------------------+
| Field                                | Value                                                                  |
+--------------------------------------+------------------------------------------------------------------------+
...
| properties                           | groups='windows,foo,bar'                                               |
```
output from openstack dynamic inventory script
```
root@ansible:~/ansible# ./openstack.py --list | grep ansible_
        "ansible_connection": "winrm",
        "ansible_password": "{{ lookup('pass', 'content/hosts/test44/administrator') }}",
        "ansible_ssh_host": "10.0.0.14",
        "ansible_user": "ansible",
        "ansible_winrm_server_cert_validation": "ignore",
```
Output from playbook:
```
ansible-playbook -i openstack.py testwindows.yml

PLAY [test44] ******************************************************************

TASK [setup] *******************************************************************
ok: [test44]

TASK [win_ping test machine] ***************************************************
ok: [test44]

PLAY RECAP *********************************************************************
test44                     : ok=2    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by morphje** [comment]
also showing an example with something else then the hostname
clouds.yml:
```
---
ansible:
  use_hostnames: true
  winrm_password_lookup_string: "{{{{ lookup('pass', 'content/hosts/{}/administrator') }}}}"
  winrm_password_lookup_var: interface_ip
  winrm_admin_user: ansible
  winrm_ignore_certificate: True
clouds:
  content:
    auth:
      auth_url: https://identity.openstack.private/v2.0
      project_name: projectid/projectname
      username: user@openstack
      password: xxx
```
showing output from openstack.py, note the ip address in the lookup:
```
./openstack.py --list | grep ansible_
        "ansible_connection": "winrm",
        "ansible_password": "{{ lookup('pass', 'content/hosts/10.0.0.14/administrator') }}",
        "ansible_ssh_host": "10.0.0.14",
        "ansible_user": "administrator",
        "ansible_winrm_server_cert_validation": "ignore",
```

**Comment by morphje** [comment]
This pull request is still open, what steps are remaining in order to go forward with this pull request?

**Comment by morphje** [comment]
bot_status

**Comment by gundalow** [comment]
@morphje 
Thank you for your PR.
As part of reviewing the backlog of PRs we are looking at PRs older PRs that haven't been updated in a while

Given that:
* PR hasn't been touched since 2017
* This is a feature rather than a bug fix

Therefore I'm going to close this.

If you or anyone else wants to continue with this work then please do feel free to create a fresh PR and `@mention` the previous reviewers in here.

If you are interested in OpenStack then `#openstack-ansible-sig` on Freenode is a good place to hang out.

**Pull request closed without merging**
