### PR TITLE
New module to trigger build in Jenkins

### PR DESCRIPTION
**Pull request by muffl0n**
##### Issue Type:

New Module Pull Request
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

This module allows the user to trigger a job in Jenkins. Nothing more, nothing less. :)
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

### CODE REVIEW

**Comment by mpdehaan** [comment]
I've seen a lot of Jenkins triggering ansible, but the other way around is a bit unexpected.

Can you share a bit about the use case and how you are using this in your environment?

**Comment by muffl0n** [comment]
We are using SVN to store the config files for our tomcats. When committing to this SVN project a deployment to our staging servers get's triggered in Jenkins. The job in Jenkins does some basic syntax checking and then uses rsync to mirror these files to all known servers.

When installing a new staging-server with ansible we start the tomcat at the very end. But before the tomcat can be started the config files need to be mirrored to the newly installed server. So we trigger this job in Jenkins before starting the tomcat.

PS: We don't want to do an explicit checkout via the subversion module because we don't want to skip the logic used in the Jenkins job.

**Comment by mpdehaan** [comment]
So using Jenkins for a way of rigging up job dependencies.  Interesting.

**Comment by mpdehaan** [comment]
Ok, so this is a cool idea, but I want to contain module sprawl.   Can you perhaps add an addition to the documentation of the uri module to show how to do this with the uri module?  If so, we don't need a module for Jenkins specifically, as it contains much of the logic in common.

**Comment by muffl0n** [comment]
Sound's reasonable! I mistook the description of uri "Interacts with webservices" and didn't think about using it to just call an url.
I will test and report on monday when I'm back at the office.

**Comment by mpdehaan** [comment]
Excellent, thank you!

**Comment by muffl0n** [comment]
Works with force_basic_auth=yes and status_code=201. See #6775

**Comment by muffl0n** [comment]
I'm closing this because the same goal can be achieved with module "uri".

**Pull request closed without merging**
