### PR TITLE
device operations are recursive if serialized

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Fixes: 
- #35721
- #33760

(cherry picked from commit 0bb3c4379c04f923f63c1cbc879c4f2e69174b9a)

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/vmware.py

##### ANSIBLE VERSION

```
Stable-2.4
```

### CODE REVIEW

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Comment by Akasurde** [comment]
bot_broken

**Comment by Akasurde** [comment]
@mattclay Can you please help me understand this CI error ?

**Comment by mattclay** [comment]
@Akasurde I'm investigating.

**Comment by mattclay** [comment]
@Akasurde The failure is due to the release of coverage 4.5. I'm working on a fix.

**Comment by merloon** [comment]
shipit

**Comment by mattclay** [comment]
The CI issue should be fixed now. I've restarted CI for this PR.

**Comment by Akasurde** [comment]
@mattclay Thanks a lot for looking into this. 

@abadger Could you please add this to 2.4 backport list ?

**Comment by abadger** [comment]
Should this throw an error if it is unable to encode?  ```to_text(Foo,
errors='surrogate_or_strict')```

If not, feel free to merge to stable-2.4.  we're currently not in a freeze
for that branch.

**Comment by Akasurde** [comment]
@abadger I don't think this is necessary as VMware returns localised version of message. I will merge this PR then. Thanks for information.

@mattclay @merloon @abadger Thanks for review.

**Comment by abadger** [comment]
Did you mean to say it *does not* return localized messages?  If it returns
localized messages, then it can return not-utf8 which is where we have to
decide whether to throw an error or munge the output.

**Pull request merged**
