### PR TITLE
Move AWS guidelines to collection

### PR DESCRIPTION
**Pull request by mariolenz**
##### SUMMARY
`amazon.aws` specific stuff shouldn't be part aof ansible-core.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/ansible_index.rst
docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
docs/docsite/rst/dev_guide/developing_modules_checklist.rst
docs/docsite/rst/dev_guide/platforms/aws_guidelines.rst

##### ADDITIONAL INFORMATION
Superseds #77608

### CODE REVIEW

**Comment by mariolenz** [comment]
@samccann I had to remove `amazon.aws` from developing_modules_best_practices and developing_modules_checklist. Otherwise, the CI fails.

Could you live with this?

**Comment by samccann** [comment]
@mariolenz Thanks for doing this! Can you put back the old file as just a stub page please? That way anyone with a bookmark of it can find the new location.

**Comment by mariolenz** [comment]
@samccann I have added aws_guidelines.rst again as a stub page.

**Comment by mariolenz** [comment]
@samccann What do you say, is this PR OK now?

**Review by samccann — APPROVED** [review]

**Pull request merged**
