### PR TITLE
Storagepool dev upstream

### PR DESCRIPTION
**Pull request by ndswartz**
##### SUMMARY
Refactored module for better maintainability and cleaned up documentation for more clarity.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

netapp_e_storagepool
##### ADDITIONAL INFORMATION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/swartzn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/swartzn/ansible-dev/lib/ansible
  executable location = /home/swartzn/ansible-dev/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

### CODE REVIEW

**Comment by thedoubl3j** [comment]
getting eyes on this now @ndswartz . this needs a rebase which should also kick off the CI as well. can't merge until then

**Review by thedoubl3j — COMMENTED** [review]
still need to fix some CI issues but everything else looks good. Tests added and docs updated.

**Comment by ndswartz** [comment]
@thedoubl3j I've resolved the CI issues. Thanks

**Review by thedoubl3j — APPROVED** [review]
CI fixed, test coverage looks good. lgtm. shipit

**Pull request merged**
