### PR TITLE
add support for regex to vars lookup plugin

### PR DESCRIPTION
**Pull request by abedwardsw**
##### SUMMARY
I would like to be able to lookup all variables matching a pattern

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vars lookup plugin

##### ADDITIONAL INFORMATION
See the test cases for sample usage.   Let me know if there are any concerns.

### CODE REVIEW

**Comment by abedwardsw** [comment]
hi, first time contributor here, everything looks good to be merged, could someone merge this request or provide feedback on what else is needed?   change is small and test cases were added.

thanks

**Review by jamescassell — APPROVED** [review]
Looks great! Any chance of adding the capability of returning the list of var names that were matched, or returning a dictionary of varname, value?

**Comment by abedwardsw** [comment]
hey @jamescassell I could do that but maybe later in a separate PR?  as this request has been open for a month it would be nice to get it merged.   To be clear on your request, you would prefer to have the option to return a dict instead of a list?  makes sense, just want to ensure i'm clear on it.

**Comment by jamescassell** [comment]
If you have time to show up for an IRC meeting, you can add it to the core team agenda to discuss: https://github.com/ansible/community/issues/450

I'd love to see this merged in time for 2.8.

**Comment by jamescassell** [comment]
A dictionary seems most flexible to me, but others might have differing opinions.

**Comment by abedwardsw** [comment]
hey @jamescassell  I do agree with you that dict is better, the issue is though that the vars plugin already has the ability to pass in multiple variables to lookup at the same time and currently already  returns a list in this case.   So if we defaulted to return a dict we would break backward compatibility.   That is why I see the "dict" option as a separate enhancement request and shouldn't block this PR.  I still think we need to keep list behaviour for backward compatibility.

I'll see if I have time to add another input option ie..  "wantdict: true" or something like that (if you have suggestions let me know), but it would be nice to keep this as a separate PR so we can move forward with this change in the event I don't have time to add it.

**Comment by abedwardsw** [comment]
@jamescassell I ended up having some extra time and added support to return dict instead of list.  As mentioned, leaving list as default for backward compatibility.  would be great if you can help get this merged.  thanks

**Review by jamescassell — APPROVED** [review]
Awesome! Thanks for implementing that. I'll bring it up at the core meeting for discussion. You should show up if you have time. I expect minor bike shedding on the option names, but I don't foresee any objection to the feature.

**Comment by bcoca** [comment]
https://docs.ansible.com/ansible/devel/plugins/lookup/varnames.html

**Comment by abedwardsw** [comment]
@bcoca  wish I knew that one existed.. ;-) . but still I think there's value in my updates as the vars plugin returns the actual contents of the variables instead of just the variable names.  No?

**Comment by bcoca** [comment]
chain them, preferable to add a clunky interface to vars `lookup('vars', lookup('varnames'), 'regex'))`

**Comment by abedwardsw** [comment]
ok.  

ps.  this is fairly discouraging to a new contributor.  I noticed this PR was started before [yours](https://github.com/ansible/ansible/pull/51621).   How can I avoid this situation in the future?   should I go onto the devel irc and confirm with you my plan prior to starting any work?

even yesterday @jamescassell asked me to add further enhancements further resulting in wasted effort 👎

**Comment by bcoca** [comment]
@abedwardsw sorry, also no need to close this yet, its just my opinion above, no one has unilateral veto here.

It is also a big project, a lot of left/right hand issues, we don't always know what everyone else is doing. 

I had my lookup more or less coded since I added the 'vars' one, i just only recently remembered to create a PR. 

I had always planned to do this to finally be able to deprecate the undocumented `vars` variable which we stopped using in 2.3 but keep around due to many users having found it and use it for what both these lookups provide. I'm not a fan of removing features (even if undocumented) w/o an alternative (within reason https://xkcd.com/1172/) .

**Comment by jamescassell** [comment]
@abedwardsw , this was discussed at the Core Meeting today: https://meetbot.fedoraproject.org/ansible-meeting/2019-03-05/ansible_core_irc_public_meeting.2019-03-05-19.01.log.html#l-212

The general feeling was that the functionality of this PR can be achieved using a combo of the existing 'vars' lookup and the new 'varnames' lookup.  I didn't realize the 'varnames' lookup was a thing until @bcoca mentioned it above.  Sorry I wasted your time in asking to add that (as it turns out, duplicate) functionality here.

Could you check whether the vars + varnames lookups will meet your needs that this PR solves?

**Comment by abedwardsw** [comment]
hey @jamescassell  thanks for that.   I guess the only functionality that can't be achieved by the varnames is the returning of "dict" which you asked for.  So i guess it's to you whether this is needed or not.    For my needs chaining the plugins together should work fine.

It would also be useful if you could post some guidance (or discuss at the next meeting) on how to avoid this duplicated effort situation for other newbies.  Maybe new enhancement tickets should go first to a review board before being worked on so that we have documented agreement ahead of time in a given issue?  or core committers keep an eye on PR's to ensure no duplicates before they work on new features?  It would be great from a newbies point of view to ensure that effort is not wasted and to ensure the PR will be merged.   I realize this is quite difficult given the number of outstanding PR's.

**Comment by jamescassell** [comment]
I get this error when I try to use vars with varnames:
`An unhandled exception occurred while running the lookup plugin 'vars'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Invalid setting identifier, "[u'mycomplex', u'myfalse', u'mybare']" is not a string, its a <type 'list'>`

Here's my playbook:
```yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    mybare: true
    myfalse: false
    mycomplex: "{{ mybare or myfalse }}"
  tasks:
  - debug:
      msg: bare
    when: mybare
  - debug:
      msg: complex
    when: mycomplex
  - debug:
      msg: "{% set myvars=q('varnames', '^my') %}{{ myvars | zip(lookup('vars', myvars)) }}"
```

**Comment by bcoca** [comment]
my examples were approximations, not working versions, this one does work:
```yaml
- hosts: localhost
  gather_facts: no
  vars:
    mybare: true
    myfalse: false
    mycomplex: "{{ mybare or myfalse }}"
  tasks:
  - debug:
      msg: bare
    when: mybare
  - debug:
      msg: complex
    when: mycomplex
  - debug:
      msg: "{{ (myvars | zip(lookup('vars', *myvars)))|to_dict }}"
    vars:
      myvars: "{{q('varnames', '^my')}}"
```

**Comment by jamescassell** [comment]
Thanks for that! What is the *var syntax? Is that jinja or underlying python?  (I've not seen it in playbooks before)

**Comment by bcoca** [comment]
@jamescassell  you could always use `vars:` keywords at play/block/role/task levels,  they are just YAML and you can use jinja2 templates as the values,  same as you can define vars in vars_files/host_vars/group_vars/etc

**Comment by jamescassell** [comment]
It's unrelated to this issue, but you can't directly use jinja in a vars: attribute. My question was specifically to the '*myvars' syntax in your example above.

**Comment by sivel** [comment]
`*myvars` is a python-ism, inherited by jinja2.  It is called argument unpacking.  Basically turning a list into discrete arguments.

**Comment by jamescassell** [comment]
Thanks for the explanation! The to_dict filter does not exist for me, nor a dict dict filter, which I tried based on the existence of a list filter.

**Comment by bcoca** [comment]
and no `vars:` is not templatable, but the value of vars IN `vars:` is

the dict|to_dict filter seems to be local (i wrote one day and installed locally and forgot), other solution (while i submit dict filter PR):

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    mybare: true
    myfalse: false
    mycomplex: "{{ mybare or myfalse }}"
  tasks:
  - debug:
      msg: bare
    when: mybare
  - debug:
      msg: complex
    when: mycomplex
  - set_fact:
      mydict: "{{ mydict|default({}) | combine({item[0]: item[1]}) }}"
    loop: "{{ (myvars | zip(lookup('vars', *myvars)))|list}}"
    vars:
      myvars: "{{q('varnames', '^my')}}"

  - debug: var=mydict
~

```

**Comment by sivel** [comment]
There is a `dict()` global function`.  

```
dict(myvars | zip(lookup('vars', *myvars)))
```

**Comment by bcoca** [comment]
ah , missed that ...

**Comment by jamescassell** [comment]
when I try the dict() global, I get `Unexpected templating type error occurred on ({{ dict(myvars | zip(lookup('vars', *myvars)))}}): <lambda>() takes exactly 0 arguments (1 given)`

**Comment by bcoca** [comment]
``` yaml
  - debug: msg="{{ dict(myvars | zip(lookup('vars', *myvars)))}}"
    vars:
      myvars: "{{q('varnames', '^my')}}"
```
produces
```
ok: [localhost] => {
    "msg": {
        "mybare": true,
        "mycomplex": true,
        "myfalse": false,
        "myvars": [
            "mybare",
            "myfalse",
            "mycomplex",
            "myvars"
        ]
    }
}
```

**Comment by jamescassell** [comment]
I copy/pasted that exactly.  Is it a py2 vs py3 thing?  (I've been trying on CentOS 7)  I can try on Fedora 29 tonight.

**Comment by jamescassell** [comment]
@bcoca would be good to have your PR for a 'dict' filter, at least for python-2.7 reasons.

This works on Fedora 29, but fails on RHEL 7:
`ansible localhost -m debug -a "msg=\"{% set myvars = q('varnames', '^ansible_') %}{{ dict(myvars | zip(q('vars', *myvars))) }}\""`

Error on RHEL 7 is:
`"msg": "Unexpected templating type error occurred on ({% set myvars = q('varnames', '^ansible') %}{{ dict(myvars | zip(q('vars', *myvars))) }}): <lambda>() takes exactly 0 arguments (1 given)"`

**Comment by sivel** [comment]
It's not a python 2 problem, it is a jinja2 < 2.8 thing.

https://github.com/pallets/jinja/commit/6179c02

Before jinja2.8 the `dict` function could only take `key=value` args, instead of working like a real dict constructor.

**Comment by jamescassell** [comment]
Any chance of the earlier jinja getting backported to RHEL 7?  Otherwise, can we add the dict filter?

**Comment by jamescassell** [comment]
@abedwardsw thanks for all your work on this PR, and sorry for the misunderstanding wrt the `varnames` plugin geting merged before this one.  I think that since #54057 has been merged, this one can be closed since its functionality can be reproduced with the `vars` `varnames` and 'dict is dick' features/bugfixes.

**Pull request closed without merging**
