### PR TITLE
win_stat: Add stat.isreg support

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes the following changes:
- Adds stat.isreg support (cfr. the stat module)
- ~Always returns stat.isdir, stat.islnk, stat.isreg, stat.isshared~

This relates to #27723

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_stat

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by jborean93** [comment]
I'm fine with the new value `isreg` being added but I don't agree with returning the extra values  even if the path does not exist. My issue with that is that `stat` does not function like it and it would be good to have similar functionality between the modules. On the other hand I don't feel too strongly about it so happy to go along if others disagree.

**Comment by dagwieers** [comment]
@jborean93 I agree that we may not want to have it behave differently than the **stat** module. So maybe we should propose to also change the behaviour of the **stat** module. The benefit is that in most cases you would not need to check if a path existed if you are only interested to know if it is a regular file.

I'll remove the controversial part from this PR.

**Comment by dagwieers** [comment]
@jborean93 Ready to be merged now.

**Comment by jborean93** [comment]
LGTM, thanks.

**Pull request merged**
