### PR TITLE
feature/copy-vault: Add vault support to copy action plugin

### PR DESCRIPTION
**Pull request by cambell-prince**
This PR allows the copy task to support copying encrypted vault files as described in #7298 (at least with respect to the copying of files).  The implementation is the same as that used in the [copyv action plugin](https://github.com/saygoweb/ansible-plugin-copyv) developed for Ansible v1.9.2

### CODE REVIEW

**Comment by bcoca** [comment]
nice, this was on my wishlist, but I was going to approach it as a general function available to all action plugins, not just copy.

**Comment by cambell-prince** [comment]
@bcoca This feature seems like a 'data interpreting' kind of feature, so using the loader which is passed around all plugins seems like an ok option.  If you're ok with that approach, this PR could be improved by hiding the vault implementation within the loader and having a public method or two on the loader that would implement this functionality.  The loader is then available as a general service to all action plugins.

**Comment by bcoca** [comment]
I was debating doing it that way or adding vaullib as an additional thing to pass through, this is a bit tangential to loader (which needs to be vault aware also) but  it is also very convenient there ....

**Comment by cambell-prince** [comment]
I've had a look at playbook.py, and to pass an instance of VaultLib through to action plugins would seem to require that the VaultLib is constructed in playbook.py and passed through via yet another parameter in the PlayExecutor and made available in the PlayContext.  However, the PlayExecutor is already passed in a passwords dictionary.  These passwords are stored in the PlayContext which is already available to all the action plugins.  I'm thinking that it would be ok to add the vault password to the password dictionary that is already passed to the PlayExecutor and available in the PlayContext.

If that's an acceptable way to go, let me know and I'll implement that and post a new PR.

**Comment by bcoca** [comment]
yes, play_context seems the 'right place' to put the vault password and i'm thinking it should also work for the vaultlib instance if we don't want to overload data loader. let me sync with other core team members before you do any work to make sure we all agree.

**Comment by datamint** [comment]
Looking forward for this to be merged. Would this work also with unarchive? Vaulted files should really be transparent once running a playbook, copying and unzipping seem like the most common scenarion and will cut a good 30% of a playbook I'm writing.

**Comment by namero999** [comment]
Looking forward for this to be merged. Would this work also with unarchive? Vaulted files should really be transparent once running a playbook, copying and unzipping seem like the most common scenarios and would cut a good 30% of a playbook I'm writing.

My specific use case is that I have a folder with a nested structure which contains certificates and sensible configuration files. Therefore the best thing for me is to tar/gz the whole folder, encrypt it with vault, and then unarchive it on the remote hosts. The current workaround is really cumbersome, so this feature (with unarchive support) would be amazing.

**Comment by bcoca** [comment]
@cambell-prince after some discussion, we are fine on having a new method in data loader that deals with transparently decrypting files, something action/lookup plugins could use.

`get_file_path(path)` +> returns original path or path to temp file of decrypted file (i suck at namging, just a bad example)

**Comment by bcoca** [comment]
closing this in favor of #14079

**Pull request closed without merging**
