### PR TITLE
doc: Update pscx examples

### PR DESCRIPTION
**Pull request by simon04**
PSCX is no longer distributed via Chocolatey: https://chocolatey.org/packages/pscx#comment-3762408157

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Would be nice to also update http://docs.ansible.com/ansible/latest/win_unzip_module.html to show getting PSCX from Gallery too, since that seems to be prefered distribution method now.

**Comment by simon04** [comment]
Thanks for the hint. Done → 7a7a286b7da7b8d0b371313cf7e9017d5daa96a1.

**Comment by schwartzmx** [comment]
lgtm 
shipit

**Comment by jborean93** [comment]
Thanks @simon04

**Pull request merged**
