### PR TITLE
Add a plugin that permit to use ansible for lxc system, using libvirt

### PR DESCRIPTION
**Pull request by mscherer**
Using -c lxc and the domain name as hostname, this permit to manage a whole
range of container, provided they are managed and created by libvirtd.

### CODE REVIEW

**Comment by jimi-c** [comment]
My primary issue with this is that it seems to be local only, and won't connect to other systems running lxc, which might confuse users. But if you're doing lxc+ssh what would this get you beyond just using ssh for the connection?

Really, this doesn't appear to be lxc-specific and could support xen or kvm just as easily?

**Comment by mscherer** [comment]
Yes, that's local only, modelled after the chroot and local connexion. ( and my next idea was to add jail after chroot, and then see if we could not refactor the 2 a bit ).

Doing with ssh is not needed, you can just ssh inside the lxc and that's all. My use case is a system running lots of containers, but without ssh so this reduce : 
- ressources used
- attack surface

IE, they can be fully managed from the main host. And for various reasons ( like lxc being separated from chroot when it come to process running, because lxc can be backed by a lvm or something else, and private mount point and so one  ), we cannot use the same approach than chroot ( ie, directly modifying the filesystem ).

And no, it doesn't work for xen/qemu, since you cannot execute a arbitrary command in the virtualisation domain. And we cannot modify the disk when the system is running. It could work with guestfish for online system, but I am not sure there is a usecase.

**Comment by Schnouki** [comment]
This would be very useful for me too. Right now I have to do ssh with ProxyCommand and manage the ssh host key on the containers, which is quite annoying. A lxc connection would be much better.

**Comment by mpdehaan** [comment]
yeah there are too many people that will want to run a cluster of these, so just being able to manage them on the local system is not something I think we want to maintain.

**Comment by mpdehaan** [comment]
I'm being unreasonable here I think, there's no reason we can't think about this.

**Comment by mpdehaan** [comment]
An example here is someone may want to use ansible in development or on a home setup, and we shouldn't restrict innovation in that area because it might not make sense in production.

In fact, running ansible from ansible in production could actually be a thing in some places :)

**Comment by mscherer** [comment]
Another option is simply use it on the server hosting the lxc. IE, using ansible-pull, cron and running the playbook from the main host. 

The idea of chaing ansible is interesting, I guess we could imagine a ansible module that run ansible, and return the output in json into a specific format suitable for the first ansible. And this would permit to scale in a interesting way ( ie, in a tree like fashion ), but maybe with some caveats ( I imagine that fetch/copy module  would have a difficult time to cope with this )

**Comment by mscherer** [comment]
In fact, thinking of it, I think it should be named "libvirt-lxc' rather than lxc, or a different name, as I expect people to think it would be compatible with the lxc user space, while this is not the case ( ie, both use the same underlying kernel feature, but lxc is just the userspace implementation, and libvirt-lxc reuse the name, and this is confusing )

Any opinion on the name ?

**Comment by jimi-c** [comment]
We're going to go ahead and merge this in, but it will be named `libvirt_lxc`.

**Comment by jimi-c** [comment]
Thanks!

**Pull request merged**
