### PR TITLE
Add Pure Storage Host Group module

### PR DESCRIPTION
**Pull request by sdodsley**
SUMMARY

Add host group module for Pure Storage FlashArray device. Module to create/modify/delete host groups.

ISSUE TYPE

New Module Pull Request
COMPONENT NAME

purefa_hg
ANSIBLE VERSION

ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pureuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

### CODE REVIEW

**Comment by sdodsley** [comment]
@gundalow As requested separate PR for each remaining module

**Comment by sdodsley** [comment]
@gundalow  : Can you review, please?

**Comment by gundalow** [comment]
@sdodsley Updated needed as per https://github.com/ansible/ansible/pull/26355#issuecomment-318917488

Rest looks sensible

**Review by gundalow — APPROVED** [review]

**Comment by sdodsley** [comment]
:shipit:

**Comment by gundalow** [comment]
Merged, and will be released in Ansible 2.4.0

**Pull request merged**
