### PR TITLE
#5089 hack-fix assemble module

### PR DESCRIPTION
**Pull request by EspadaV8**
Follow on from #5057 and #5089

Needs a review, but it's working for me at the moment

@bcoca thoughts?

### CODE REVIEW

**Comment by mpdehaan** [comment]
So per previous post, could you share what happened to you after applying Brian's patch that led you to think there was still a problem?  Not saying it's not there, but basically missing "steps to reproduce".

I'm mainly asking about fda44a7f e2d0317 and eed32ea

The diff parts are to enable --diff so you would fetch the file via "slurp" (see other modules that do diff) in order to support --diff, and this looks like it _may_ not support diff.

**Comment by mpdehaan** [comment]
I missed comments on #5089 BTW, though that may not quite answer all of the above.

**Comment by EspadaV8** [comment]
I'm not back in the office until Monday and don't have a dev machine available until then, but once I do I'll create a minimal vagrant use case.

da44a7f -  resultant is used on lines 83, 93 and 96 but hasn't been defined, and so throws an error

Sorry, screaming baby. Back later. . .

**Comment by EspadaV8** [comment]
e2d0317 - I'm not sure that this is needed, but the copy module needs the agruments updated - https://github.com/ansible/ansible/blob/e2d03173d2bbd3106916b38a092c894c160b7d92/lib/ansible/runner/action_plugins/assemble.py#L90 - so I assumed that the file module would as well

eed32ea - dest_contents is defined on line 78 - https://github.com/ansible/ansible/blob/eed32ea70ce7fcd850f10ef174c48daad91407a7/lib/ansible/runner/action_plugins/assemble.py#L78 - which will only happen when the 2 previous if statements are true, which doesn't alwasy happen, however, both of the return statements assume that is has been defined.

**Comment by EspadaV8** [comment]
I've created a very simple example - https://github.com/EspadaV8/ansible-assemble-test

It just tries to combine a bunch of random data in 10 files into a single file on the remote. As it stands it will fail with 

```
NameError: global name 'resultant' is not defined
```

Applying da44a7f will get it a bit further, but fail with

```
UnboundLocalError: local variable 'dest_contents' referenced before assignment
```

Applying eed32ea will allow a bit more progress, but will then fail with 

```
msg: unsupported parameter for module: remote_src
```

Finally, applying 7b01c831 after this will allow the module to finish completely and the file `/tmp/combined` will be on the remote server.

**Comment by jctanner** [comment]
@EspadaV8 thank you!

**Comment by EspadaV8** [comment]
:confused: Was all this okay? If everyone is happy with it that's fine, I just thought some of it was... wrong? I'm sure that lines 93 and 95 should have the before=... set, I'm just not sure what they should be set to (rather than just not returning them).

I have just this second noticed an issue with line 99 too, xfered isn't used by that code path and will throw an undefined error

**Comment by jctanner** [comment]
@EspadaV8 it was working for me against existing tests and your testcase. If you can give me additional testcases, I'll try to fix those.

**Pull request merged**
