### PR TITLE
Add source interface and use-vrf features

### PR DESCRIPTION
**Pull request by NilashishC**
##### SUMMARY
- Adds features mentioned in #43089 
- With this PR, _nxos_logging_ will support configuring `vrf` and `source-interface` for logging
- Added tests

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
nxos_logging.py

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by e2-team** [comment]
@NilashishC Thanks for your help. I will test it today and give you a feedback!

**Comment by e2-team** [comment]
I have tried the playbook and works fine, but once it's implemented if the configuration is OK, it's showing that it changed. Is there some check of the config that's not working?
Thanks

**Comment by NilashishC** [comment]
@e2-team Hi. Thanks for your feedback. Could you share the playbook you are running? I had put in tests to make sure that idempotency is preserved.

The new features can be implemented in the following way:

```
- name: Configure Remote Logging
  nxos_logging:
    dest: server
    remote_server: <enter_server_ip>
    facility_level: <enter_facility_level>
    facility: <enter_facility_type>
    use_vrf: <enter_vrf_type>
    state: present
```    
```
- name: Configure Source Interface For Logging
  nxos_logging:
    interface_type: mgmt
    interface: 0
```

I have also added examples in this PR for the new features.

**Comment by e2-team** [comment]
Hi @NilashishC, 

Here is my playbook: 
`  tasks:
  - name: Configure syslog in Nexus
    nxos_logging:
       dest: server
       remote_server: "{{ server }}"
       name: "{{ server }}"
       dest_level: 5
       use_vrf: management
       interface_type: mgmt
       interface: 0
    when: ansible_network_os == 'nxos'
`
And here is the results that I have:

`ansible-playbook syslog.yml -u admin -k -l host
SSH password: 

PLAY [all] **************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************
ok: [host]

TASK [Configure syslog in Nexus] ****************************************************************************************************************************************************************
changed: [host]

PLAY RECAP **************************************************************************************************************************************************************************************
host               : ok=2    changed=1    unreachable=0    failed=0   `


Am I missing or misconfiguring something? Should I do it in 2 task as you show?
I will try the way that you show me and be back with you.

Regards.
Exequiel

**Comment by NilashishC** [comment]
Hi @e2-team. For idempotency to be preserved, the candidate config should be in the same format as the running config. The `source-interface` and `remote logging` configurations come up in two different lines in running-config. 

Hence, to ensure that your tasks are idempotent, you need to use two separate tasks for configuring them like I mentioned in the previous comment. 

Also, I see that you're using the _name_ parameter in your task for configuring `remote logging`, which is not necessary and having that in the task will also result in it not being idempotent.

**Comment by e2-team** [comment]
Hi @NilashishC thanks for your comments, I understand now. Will change the playbook and test it

**Comment by e2-team** [comment]
I have checked and split the task and worked like a charm!
The final config I did to work was:

  - name: Configure syslog in Nexus - Part1/2
    nxos_logging:
       dest: server
       remote_server: "{{ server }}"
       facility_level: 5
       use_vrf: management
       state: present
    when: ansible_network_os == 'nxos'

  - name: Configure syslog in Nexus - Part2/2
    nxos_logging:
       interface_type: mgmt
       interface: 0
    when: ansible_network_os == 'nxos'

 Thanks for your help!!!

**Review by trishnaguha — APPROVED** [review]

**Pull request merged**
