### PR TITLE
added docs about in template overrides

### PR DESCRIPTION
**Pull request by bcoca**
small documentation better than no documentation
Signed-off-by: Brian Coca bcoca@tablethotels.com

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you show what it would look like with more than one param or where to find what you can set?

**Comment by bcoca** [comment]
Yes,

I was planning on writing a more complete version tonight, I will just
resubmit then.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
good for now, merged, thanks!

**Comment by bcoca** [comment]
sorry, changing jobs has really cut into my time, I should get to this soon.

On Sun, Mar 17, 2013 at 10:21 AM, Michael DeHaan
notifications@github.comwrote:

> good for now, merged, thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/2387#issuecomment-15023402
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Pull request merged**
