### PR TITLE
[vmware_guest] Add video card support

### LINKED ISSUE #31810: VMware: Define video memory settings
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_guest

##### SUMMARY
It is currently not possible to set the video memory of the guest OS from ansible.
It would be much appreciated to be able to do that instead of doing it manually deployement.

### PR DESCRIPTION
**Pull request by ochurlaud**
##### SUMMARY
This change allows configuring video cards: one can set the 3d support, the video memory and the number of displays.

It currently only works for new VM (no edition).

Fixes #31810 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

### CODE REVIEW

**Comment by Akasurde** [comment]
@ochurlaud Could you please add an integration test for this change ? You can take a look at [vmware_guest](https://github.com/ansible/ansible/blob/devel/test/integration/targets/vmware_guest/tasks/) tests.

**Comment by ochurlaud** [comment]
@Akasurde: I'm not sure of how it works: there is no simple example for, say, memory or cpu numbers.

Also, i'm not able to update a video card settings with this change, only to create it

**Comment by Akasurde** [comment]
@ochurlaud Any news ?

**Comment by ochurlaud** [comment]
Still waiting for an answer to my questions

**Comment by pdellaert** [comment]
Hi @ochurlaud,

You can create a new test file, similar to this: https://github.com/ansible/ansible/blob/devel/test/integration/targets/vmware_guest/tasks/cdrom_d1_c1_f0.yml 

This one contains tests for cdrom creation/modification and uses the vCenter Simulator that's available govmomi. 

Running tests is best described here: https://docs.ansible.com/ansible/latest/dev_guide/testing.html

**Comment by ochurlaud** [comment]
Rebased and added what I understood as being tests

**Comment by ochurlaud** [comment]
No idea why it canceled: I spent a lot of time rebasing, I need help again.

@pdellaert ? @Akasurde ?

Thx

**Comment by ochurlaud** [comment]
I completely messed up with this branch. I open a new pull request from there #41047

**Pull request closed without merging**
