### PR TITLE
Adding support for A10 Networks

### PR DESCRIPTION
**Pull request by mischapeters**
Adding support for slb server, slb service-group, slb virtual-server

### CODE REVIEW

**Comment by mpdehaan** [comment]
Excellent, could you perhaps post this on ansible-project?  I'd like to see if we could get some other A10 users to help test and I know we have a lot of folks there with that hardware.

**Comment by mischapeters** [comment]
It would be great if others can test it. There is still some stuff to add, things like health checks, ssl templates, source-nat, etc. But I wanted to get the first version out.
Is there a way to subscribe to the mailinglist? I have only found a Google Group.

**Comment by mpdehaan** [comment]
The google group is in fact also a mailing list.

email ansible-project+subscribe@googlegroups.com and you should get a confirmation email

**Comment by mischapeters** [comment]
Any change this will be added to 1.7?

**Comment by wyyang** [comment]
I tried to tests it in my environment. I get the following errors:

msg: received exception: "<"urlopen error [Errno 1] _ssl.c:492: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version">"

Seems related to a bug in openssl that was never patched. Have anyone else seen similar errors?

**Comment by mischapeters** [comment]
What does your playbook look like? And what version of OpenSSL are you using?

**Comment by wyyang** [comment]
My playbook
- hosts: discovery
  user: root
  serial: 1 # update 1 webservers at a time
  gather_facts: False
  vars:
    ax_admin: xxxx
    ax_pass: xxxx
  
  pre_tasks:
  - debug:
    msg: "{{ inventory_hostname }}"
  - name: disable the server in a10
    local_action:
      a10_server
      host={{ item }}
      username={{ ax_admin }}
      password={{ ax_pass }}
      server_name={{ inventory_hostname }}
      server_status=disable
    delegate_to: "{{ item }}"
    with_items: groups.ax3400
  
  tasks:
  - name: show hostname
    shell: hostname

OpenSSL version: 
openssl-1.0.1e-16.el6_5.14.x86_64

**Comment by mischapeters** [comment]
One thing that I forgot, which ACOS version are you running?

**Comment by wyyang** [comment]
```
  64-bit Advanced Core OS (ACOS) version 2.7.0-P3, build 86 (Jun-17-2013,05:40)
  Firmware version: 2.9
  aFleX version: 2.0.0
  aXAPI version: 2.0, 1.2, 1.1, 1.0
```

**Comment by mischapeters** [comment]
aXAPI 2.0 is not fully JSON.
The module for A10 requires aXAPI version 2.1, which is part of ACOS 2.7.1.
Do you have a way to upgrade to 2.7.1-P5-SP2? This is the latest release of 2.7.1.

**Comment by mischapeters** [comment]
@wyyang Have you been able to get this working?

**Comment by wyyang** [comment]
Not really. The a10 load balancers are in production with a very busy site.
We do not plan to upgrade the firmware any time soon.

**Comment by mischapeters** [comment]
That is to bad. The aXAPI in 2.7.0 is to limited to provide support for Ansible.

**Comment by mischapeters** [comment]
@wyyang if you have a hypervisor running you can also download a trail version of the vThunder, that way you can test it without breaking anything in production.

**Comment by mischapeters** [comment]
Thanx Michael

**Comment by mpdehaan** [comment]
Hi everyone, 

Just wanted to provide a quick update - I'm waiting on a few +1s saying folks have this working in their environment before merging this, but I'd really really love to have it.

Please keep us updated, the mailing list may also get a bit quicker activity on this one.

Thanks!

**Comment by mischapeters** [comment]
I am working with some customers to get this done. I have one pull request and some slight modifications I need to push. So hopefully will have some :+1: 's soon. :)

**Comment by giganteous** [comment]
I've tested basic enabling / disabling of existing servers, which is the bread and butter for most ansible recipe's. By al means: :+1: .

**Comment by mischapeters** [comment]
@mpdehaan is a single +1 enough? Not sure if there will be more at the moment as there is a dependency on v2.1 of the API. Which is only available in the later releases of ACOS.

**Comment by jimi-c** [comment]
@mischapeters I'm reviewing these now.

**Comment by mischapeters** [comment]
@jimi-c Thanx!

**Comment by jimi-c** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release. 

I did end up rewriting these to quite a degree to bring them in-line with how our other modules work in regards to idempotent actions - rather than add one sub-object at a time (like ports to a virtual server) everything is created in one shot now and any changes to the play results in an update. I also moved a lot of common code to a new utility snippet and removed the direct use of urllib2 calls in favor of our fetch_url library (which offers a lot of features). Be

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jzhao29** [comment]
hi Eric/Mischa:

I tried the module a10_server in my lab, I got the "No authentication methods available" error message. Can you please help?

[john.zhao@john-rhel-central ~]$ ansible-playbook a10_rserver.yml -vvv
Using /home/john.zhao/ansible.cfg as config file

PLAYBOOK: a10_rserver.yml ******************************************************
1 plays in a10_rserver.yml

PLAY [create a realserver] *****************************************************

TASK [debug] *******************************************************************
task path: /home/john.zhao/a10_rserver.yml:8
ok: [vfto5adc60] => {
    "msg": "vfto5adc60"
}

TASK [Create a realserver] *****************************************************
task path: /home/john.zhao/a10_rserver.yml:10
<vfto5adc60> ESTABLISH CONNECTION FOR USER: john.zhao on PORT 22 TO vfto5adc60
fatal: [vfto5adc60]: UNREACHABLE! => {"changed": false, "msg": "No authentication methods available", "unreachable": true}
 [WARNING]: Could not create retry file 'a10_rserver.retry'.         [Errno 2] No such file or directory: ''

PLAY RECAP *********************************************************************
vfto5adc60                 : ok=1    changed=0    unreachable=1    failed=0   

[john.zhao@john-rhel-central ~]$
[john.zhao@john-rhel-central ~]$ cat a10_rserver.yml 
---
- name: create a realserver 
  hosts:  vfto5adc60 
#  connection: local
  gather_facts: no

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"
    - name: Create a realserver
      a10_server:  
        host={{inventory_hostname}}
        username=xxxxx
        password=xxxxx
        server_name=realserver1
        server_ip=192.168.1.23 
[john.zhao@john-rhel-central ~]$ 

VFTO5ADC60-Active-vMaster[2/1]#sh ver
AX Series Advanced Traffic Manager AX3400
  Copyright 2007-2016 by A10 Networks, Inc.  All A10 Networks products are
  protected by one or more of the following US patents:

      64-bit Advanced Core OS (ACOS) version 2.7.2-P9, build 78 (Oct-01-2016,20:47)
        Booted from Hard Disk primary image
      
      Serial Number: AX34041112500007
      Firmware version: 2.10
      aFleX version: 2.0.0
      aXAPI version: 2.1

**Comment by jzhao29** [comment]
[john.zhao@john-rhel-central ~]$ cat a10_rserver.yml 
---
- name: create a realserver 
  hosts:  vfto5adc60 
#  connection: local
  gather_facts: no

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"
    - name: Create a realserver
      a10_server:  
        host={{inventory_hostname}}
        username=xxxxx
        password=xxxxx
        server_name=realserver1
        server_ip=192.168.1.23

**Comment by jzhao29** [comment]
$ cat a10_rserver.yml 
---
- name: create a realserver 
  hosts:  vfto5adc60 
  gather_facts: no

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"
    - name: Create a realserver
      a10_server:  
        host={{inventory_hostname}}
        username=xxxxx
        password=xxxxx
        server_name=realserver1
        server_ip=192.168.1.23

**Comment by jzhao29** [comment]
$cat a10_rserver.yml
---
- name: create a realserver
  hosts:  vfto5adc60
  gather_facts: no

  tasks:
     - debug:

**Comment by jzhao29** [comment]
_$ cat a10_rserver.yml 
---
- name: create a realserver 
  hosts:  vfto5adc60 
  gather_facts: no

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"
    - name: Create a realserver
      a10_server:  
        host={{inventory_hostname}}
        username=xxxxx
        password=xxxxx
        server_name=realserver1
        server_ip=192.168.1.23_

**Comment by jzhao29** [comment]
$ cat a10_rserver.yml 
---
- name: create a realserver 
  hosts:  vfto5adc60 
  gather_facts: no

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"
    - name: Create a realserver
      a10_server:  
        host={{inventory_hostname}}
        username=xxxxx
        password=xxxxx
        server_name=realserver1
        server_ip=192.168.1.23

**Pull request merged**
