### PR TITLE
fix Include role: exposed/shared vars

### PR DESCRIPTION
**Pull request by kiorky**
##### SUMMARY
include_role included vars are totally losen from next tasks, roles play access making include_role pretty unusable to DRY code.
This PR fixes it; see #21890 and all linked bug.

This PR is a part of my initial PR #32565  which i splitted up.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
2.4
devel
```

##### ADDITIONAL INFORMATION
I added targets/include_role integration test to show the bug in action
expected test run
```
testhost                   : ok=16   changed=9    unreachable=0    failed=0
```
before the fix
```
TASK [test_include_role : noop task] ******************************************************************************************************************************************************************************************************************************************
changed: [testhost] => {"changed": true, "cmd": "echo from role", "delta": "0:00:00.099395", "end": "2018-01-20 17:32:41.982486", "rc": 0, "start": "2018-01-20 17:32:41.883091", "stderr": "", "stderr_lines": [], "stdout": "from role", "stdout_lines": ["from role"]}

TASK [command] ****************************************************************************************************************************************************************************************************************************************************************
fatal: [testhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'testinc_defvar1' is undefined\n\nThe error appears to have been in '/srv/corpusops/corpusops.bootstrap/venv/src/ansible/test/integration/targets/include_role/include_role.yml': line 11, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      register: testa\n    - shell: echo {{testinc_defvar1}}\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'testinc_defvar1' is undefined"}
        to retry, use: --limit @/srv/corpusops/corpusops.bootstrap/venv/src/ansible/test/integration/targets/include_role/include_role.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
testhost                   : ok=5    changed=3    unreachable=0    failed=1

NOTICE: To resume at this test target, use the option: --start-at include_role
ERROR: Command "./runme.sh -v" returned exit status 2.
```

- related PRs: #35167 #35166 #35165 #35164 #35163

### CODE REVIEW

**Comment by kiorky** [comment]
cc @pilou- , reopening of #35131 against devel

**Comment by pilou-** [comment]
@kiorky the failure is unrelated to this PR, there is no need to rerun CI.
[Error](https://app.shippable.com/github/ansible/ansible/runs/51581/13/console) is:
```
2018-01-22 09:38:24 TASK [yum : verify that yum failed] ********************************************
2018-01-22 09:38:24 fatal: [testhost]: FAILED! => {"failed": true, "msg": "The conditional check 'yum_result.rc == 1' failed. The error was: error while evaluating conditional (yum_result.rc == 1): 'dict object' has no attribute 'rc'"}
2018-01-22 09:38:24 	to retry, use: --limit @/root/ansible/test/integration/yum-5zf9GA.retry
```
I proposed a fix for yum integration tests there: #35177.

ping @mattclay

**Comment by pilou-** [comment]
@mattclay : another CI run fails on NPM integration tests ([logs](https://app.shippable.com/github/ansible/ansible/runs/51594/32/console)):
```
2018-01-22 10:51:51 TASK [npm : Download NPM] ******************************************************
2018-01-22 10:53:17 fatal: [testhost]: FAILED! => {"attempts": 1, "changed": false, "failed": true, "msg": "Failure downloading https://nodejs.org/dist/v8.0.0/node-v8.0.0-linux-x64.tar.gz, ('The read operation timed out',)"}
```
 how could I append NPM tarballs to `ansible-ci-files.s3.amazonaws.com` ([mentioned there](https://github.com/ansible/community/wiki/Testing%3A-progress-tracker#tests-that-use-external-dependencies-and-therefore-are-occasionally-unstable)) ?

**Comment by duck-rh** [comment]
It works very well, thanks a lot :-)

**Comment by kiorky** [comment]
@pilou- i noticed it quicklly in the morning, i though it was a temporary download error, so that's why i retriggered a ci build.

**Comment by pilou-** [comment]
@samdoran should the tests included in this PR added to [import_include](https://github.com/corpusops/ansible/tree/230e440f1867c808c5467e3d66f40f8633cb5125/test/integration/targets/include_import) target ?

**Comment by samdoran** [comment]
Yes, please put the tests in the import/include target. We grouped all the import/include tests in a single target to make it easy to share resources between those tests as well as testing with different strategies for completeness.

**Comment by kiorky** [comment]
!ready_for_review

**Comment by kiorky** [comment]
ready_for_review

**Comment by pilou-** [comment]
@kiorky could you move the tests, reusing the existing target ?

**Comment by pilou-** [comment]
Do not hesitate to come and discuss on #ansible-fr channel on Freenode :)

**Comment by petewilcock** [comment]
:+1: on this, *very* keen to see this fix get into mainline asap :)

**Comment by sivel** [comment]
A note here.  This is not really fixing a bug. The expectation here is that vars should not be exposed by default.

There was never a feature implemented to expose these.  This would need to be done as a feature, potentially utilizing the `private` argument.

We have recently added a deprecation warning for use of the `private` argument, as it was erroneously documented but never implemented, and ignored.

I'll also mention it looks like this PR is doing too much for trying to implement such a feature.

**Comment by kiorky** [comment]
@sivel i think you didnt read at all the PR, and the tied bugs.

Do you looked at how many bugs are tied to this PR ?

This is not tied at all with ``private`` but **fixing** ``include_role`` that make included variables **undefined** after the ``include_role`` call, see tests which are reproducers of the bug...
One year later, bug is still there, as the PR...

CF #21890, no one is speaking of private, but reusing variables from included roles via ``include_role``...

cc @regilero 

And yes, it's a bug, and not a "FEATURE"

**Comment by sivel** [comment]
My comment is still correct. The expected behavior is that variables will not be exposed by include_role, and they should not by default be accessible by the play before or after.  At this time the expectation is that include_role is isolated.

This would need to be a toggle to allow those vars to be exposed. Hence, the mention of private.

**Comment by kiorky** [comment]
Then include_role is just useless and in total contradiction with roles usage...

**Comment by kiorky** [comment]
And BTW, defaults vars from roles included by ``include_role`` is not documented here, meaning that at least, naturally like with import*, variables that are in an includedrole (eg: defaults/main.yml) should be available after the include_role statement.

image

**Comment by cognifloyd** [comment]
I would like to be able to expose vars from roles I import/include (import_role/include_role) in the remainder of the play. Either a blanket include-all-vars or an option/arg on import/include _role that allows me to give a list of vars that should be automatically exported.

**Comment by kiorky** [comment]
> I would like to be able to expose vars from roles I import/include (import_role/include_role) in the remainder of the play. Either a blanket include-all-vars or an option/arg on import/include _role that allows me to give a list of vars that should be automatically exported.

Totally agree, ``include_role`` would in @sivel spirit just be unatural and not proper for what it is designed: Reusing stuff.

Adapting a documentation for what's is currently implemented rather to fix to do what it should do is not a solution.

**Comment by wouterh-dev** [comment]
My expectation is that `include_role` should function identically to a role being referenced within a playbook's role block.

**Comment by petewilcock** [comment]
+1 having `include_role` behave differently from a top-level `role` block cannot be intended behaviour.

**Comment by kiorky** [comment]
So i just rebased and on my fork i maintain patches for 2.4, 2.5 & 2.6

**Comment by sivel** [comment]
Superseded by https://github.com/ansible/ansible/pull/41330

**Pull request closed without merging**
