### PR TITLE
win_setup: Add Product ID and Product Key in facts

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
So this is actually a very nice way to get product key information from systems collected centrally, in your facts cache.

Especially with systems that have been upgraded from Windows 7 or Windows 8 to Windows 10 may not have a valid Windows 10 product license key printed anywhere, it was a digital license.

If you ever have to reinstall the system, you may recover the system from the recovery partition, or the original media, but cannot upgrade to Windows 10 for free. By collecting the product key, one can always reinstall her free Windows upgrade.

This was one of my priorities for https://github.com/crombeen/ansible so that the Windows product license key would become part of our automatically collected inventory in CSV format.

My only question is, do we want this to be part of the default facts, as it may be considered confidential information. Or should we make a special **win_product_key_facts** ?

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_setup

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by dagwieers** [comment]
I don't know if this routine works well on 64bit (DigitalProductID64 ?) or older Windows systems. From my tests I can tell that for a bunch of Windows 10 systems that were upgraded from Windows 7 and Windows 8 the same digital key seems to have been used during the upgrade. Similar sets of systems have the same key, which is a surprise to me.

Please verify this routine on your Windows system and compare the output to the product key on the sticker that comes with the system,

**Comment by dagwieers** [comment]
So after verifying those generated Product Keys it seems that these are widely used (and available on the Internet) and seem related to OEM installations specifically. So those keys are correct after all.

**Comment by dagwieers** [comment]
So for Windows 10 systems that were upgraded (my use-case) this seems less relevant, but for other Windows systems this could be useful. Since it seems a product key may also be stored in the ~BIOS/UEFI~ ACPI I'd like to also look at retrieving that information.

**Update:** Now implemented as well.

**Comment by jborean93** [comment]
@dagwieers, are you able to turn this into a separate facts module. @nitzmahone and I have been discussing it and think it shouldn't be part of the main facts process.

**Comment by nitzmahone** [comment]
I'm also +1 for a separate facts module- it's a pretty niche thing, but nice-to-have in a pinch. If you can get it in before 2.5 community freeze on 7 Feb, I'll commit to making sure it gets merged for 2.5.

**Comment by dagwieers** [comment]
@jborean93 @nitzmahone I don't disagree with doing this in a separate module. I will do what's necessary

BTW Someone inadvertently shipped it :-/ I'll undo it.

**Pull request merged**
