### PR TITLE
Refactor vmware_guest_facts

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This fix adds refactoring to vmware_guest_facts module.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest_facts.py

##### ANSIBLE VERSION
```
2.5devel
```

### CODE REVIEW

**Review by daxlab — APPROVED** [review]

**Comment by Akasurde** [comment]
ready_for_review

**Review by nerzhul — APPROVED** [review]
shipit

**Review by dagwieers — APPROVED** [review]
shipit

**Comment by Akasurde** [comment]
@dagwieers Could you please merge this?

**Comment by Akasurde** [comment]
rebuild_merge

**Pull request merged**
