### PR TITLE
Updated Ansible PPA Instructions

### PR DESCRIPTION
**Pull request by sethbergman**
##### SUMMARY

Updated 
~~sudo apt-add-repository --yes --update ppa:ansible/ansible~~
to
sudo add-apt-repository ppa:ansible/ansible

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY

The command for adding a PPA didn't work, so I decided to send in a PR with the correct syntax.
https://launchpad.net/~ansible/+archive/ubuntu/ansible

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```bash
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt install ansible
```

### CODE REVIEW

**Comment by sivel** [comment]
In what way did this not work?  What OS are you using?  This command works without issue for me on Ubuntu 18.04.

**Comment by sethbergman** [comment]
I'm using Linux Mint 19.3 "Tricia", or bionic is the base code name for this release just like Ubuntu 18.04. I'm not sure of all of the idiosyncrasies between the two but the command reports that the `--update` flag can't be used in conjunction with the `apt-add-repository` command.

**Comment by sethbergman** [comment]
@sivel was I able to answer your question? Let me know if there is anything else you need. Thanks!

**Comment by Akasurde** [comment]
Superseded by https://github.com/ansible/ansible/pull/72893

**Comment by Akasurde** [comment]
@sethbergman Thanks for the contribution.

**Pull request closed without merging**
