### PR TITLE
Add pulp_repo module for interacting with repositories on a pulp server.

### PR DESCRIPTION
**Pull request by sysadmind**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

pulp_repo
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

This adds a module for working with pulp repos. http://www.pulpproject.org/. I added this under packaging/os because it seemed like the most relevant location for this module although it is not explicitly an os packaging module like others in this directory.

I created a class that lines up with a pulp server and added methods for getting and setting repo properties. I chose this design because it closely resembles the actual design of pulp and keeps the code logically separated into small methods. 

```
ok: [L-Pulp101.localdomain]

```

This is a migration from https://github.com/ansible/ansible-modules-extras/pull/1961

### CODE REVIEW

**Comment by sysadmind** [comment]
My apologies @Nebelwolf @Nosmoht @dvanallen @jtyr. Seems that I had to move my PR to this repo as the modules have been merged back into core. If you could comment on this PR instead, I would appreciate it. @jtyr I have updated my module after your most recent feedback.

**Comment by Nosmoht** [comment]
I've tested with the same code as [here](https://github.com/ansible/ansible-modules-extras/pull/1961#issuecomment-256421363).

```
ansible 2.3.0 (pulp f267ed5720) last updated 2016/12/07 22:09:20 (GMT +200)
  config file = /home/tkrah/workspace/vagrant/pulp/ansible.cfg
  configured module search path = Default w/o overrides
```

Tested to:
- create repos --check
- create repos
- create repos --check
- remove repos --check
- remove repos
- remove repos --check

All steps working fine. Module documentation looks good. Source code looks good too.
Well done @sysadmind.

shipit

**Comment by coreaut** [comment]
I tested it with creating and updating repos. 
Also with importer_ssl_client_cert and importer_ssl_client_key options.
Everything went fine.

shipit :boat:

**Comment by jtyr** [comment]
@sysadmind You probably need to rebase your branch against the current devel branch to allow this to be merged.

**Comment by sysadmind** [comment]
Thanks for the heads up @jtyr. These changes should be in line with upstream now.

**Comment by sysadmind** [comment]
@bcoca I'm not sure why this is marked as needs_rebase. I rebased after all of the forced updates and this is a clean PR on top of current devel with a single commit.

**Comment by abadger** [comment]
Merged to devel.  Thanks !

**Pull request merged**
