### PR TITLE
Dockerfile for testing on opensuse42.2

### LINKED ISSUE #18645: Run integration tests on openSUSE leap 42.2
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
integration tests

##### ANSIBLE VERSION
devel

##### SUMMARY
So far the integration tests run on openSUSE leap 42.1. Recently 42.2 was published and the tests should also cover the new version. Probably testing on the 2 most recent releases is a good idea, since typically support for the non-enterprise releases includes only the latest 2 versions.

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
integration test

##### ANSIBLE VERSION
devel

##### SUMMARY
Adds dockerfile for integration tests on opensuse 42.2 and adds it to the tests. This is based on the opensuse 42.1 dockerfile.

Fixes #18645

As stated there I'd suggest to always have the 2 latest versions of opensuse as part of the test suite.

### CODE REVIEW

**Comment by robinro** [comment]
For the tests to pass the image has to be built and pushed to dockerhub.

I built/ran the new image locally and it passes all tests

```
docker build test/utils/docker/opensuse42.2 -t ansible/ansible:opensuse42.2
make integration IMAGE=ansible/ansible:opensuse42.2
```

**Comment by robinro** [comment]
@gundalow @mattclay You commented on the issue, maybe one of you can look at this and merge it?

**Comment by mattclay** [comment]
@robinro Please submit the Dockerfile changes separately from the changes to the test configuration. I'll need to merge the Dockerfile changes first and then build the images. Once that's done I can rebuild the PR for the test changes and merge it once it passes.

**Comment by robinro** [comment]
@mattclay Split off the shippable part to #19828 and left only the dockerfiles here.

**Pull request merged**
