### PR TITLE
WIP: scaleway_security_group: add unit test

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY

Add test for `scaleway_security_group`

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
scaleway_security_group

##### ANSIBLE VERSION
```paste below
2.8
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by remyleone** [comment]
I've tried using it as follow:

```
$ python3 -m pytest test/units/modules/cloud/scaleway/test_scaleway_security_group.py
============================================================ test session starts ============================================================
platform darwin -- Python 3.7.0, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
rootdir: /Users/sieben/workspace/ansible, inifile: tox.ini
plugins: testinfra-1.14.1, pythonpath-0.7.2, json-0.4.0, cov-2.5.1, pylama-7.4.3, devpi-server-4.5.0
collected 2 items

test/units/modules/cloud/scaleway/test_scaleway_security_group.py EE                                                                  [100%]

================================================================== ERRORS ===================================================================
_________________________________ ERROR at setup of test_without_required_parameters[patch_ansible_module0] _________________________________
file /Users/sieben/workspace/ansible/test/units/modules/cloud/scaleway/test_scaleway_security_group.py, line 14
  @pytest.mark.parametrize('patch_ansible_module', [{}], indirect=['patch_ansible_module'])
  @pytest.mark.usefixtures('patch_ansible_module')
  def test_without_required_parameters(capfd, mocker):
file /Users/sieben/workspace/ansible/test/units/modules/conftest.py, line 13
  @pytest.fixture
  def patch_ansible_module(request, mocker):
E       fixture 'mocker' not found
>       available fixtures: Ansible, Command, Facter, File, Group, Interface, Iptables, LocalCommand, MountPoint, Package, PipPackage, Process, PuppetResource, Salt, Service, Socket, Sudo, Supervisor, Sysctl, SystemInfo, TestinfraBackend, User, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, host, json_environment, json_report_path, mock_fetch_url, monkeypatch, patch_ansible_module, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/sieben/workspace/ansible/test/units/modules/conftest.py:13
______________________________ ERROR at setup of test_scaleway_security_group[patch_ansible_module0-testcase0] ______________________________
file /Users/sieben/workspace/ansible/test/units/modules/cloud/scaleway/test_scaleway_security_group.py, line 80
  @pytest.mark.parametrize('patch_ansible_module, testcase', TEST_CASES, indirect=['patch_ansible_module'])
  @pytest.mark.usefixtures('patch_ansible_module')
  def test_scaleway_security_group(mocker, capfd, mock_fetch_url, testcase):
file /Users/sieben/workspace/ansible/test/units/modules/conftest.py, line 13
  @pytest.fixture
  def patch_ansible_module(request, mocker):
E       fixture 'mocker' not found
>       available fixtures: Ansible, Command, Facter, File, Group, Interface, Iptables, LocalCommand, MountPoint, Package, PipPackage, Process, PuppetResource, Salt, Service, Socket, Sudo, Supervisor, Sysctl, SystemInfo, TestinfraBackend, User, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, host, json_environment, json_report_path, mock_fetch_url, monkeypatch, patch_ansible_module, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/sieben/workspace/ansible/test/units/modules/conftest.py:13
========================================================== 2 error in 0.26 seconds ==========================================================
```

**Comment by remyleone** [comment]
I'm all for having more tests :) Maybe document a way to start those tests in the comments at the top of the file

**Comment by pilou-** [comment]
@Sieben, the test run without any error in the CI (build status of the [related build](https://app.shippable.com/github/ansible/ansible/runs/87067) is `SUCCESS`).

On my laptop, I use this command:
```
$ ansible-test units -v --python 3.6 test/units/modules/cloud/scaleway/
```

Documentation about `ansible-test` is available in the developer guide:
- https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html
- https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#unit-tests

**Comment by gundalow** [comment]
What's left for this WIP PR?

**Comment by pilou-** [comment]
@gundalow goal of this PR was to demonstrate how to write unit tests for scaleway modules.

It seems I didn't convince scaleway module authors, legacy/unsupported integration tests are used instead.

**Pull request closed without merging**
