### PR TITLE
"allow_no_value=True" for ini_file module

### PR DESCRIPTION
**Pull request by nicocesar**
I use init_file to edit my.cnf that has values that are only keys. 

Could you please update this? 

Thanks,
Nico

### CODE REVIEW

**Comment by mpdehaan** [comment]
Merged, thanks!

**Comment by mpeters** [comment]
This seems to break ini_file on python < 2.7. See #8430

**Comment by nicocesar** [comment]
Maybe checking  sys.version_info  will make the trick... I'll do a pull request in short

**Comment by mpdehaan** [comment]
revert applied.  I'll happily take updates to allow this to work on newer versions.  Thanks @nicocesar

**Pull request merged**
