### PR TITLE
Lots of PEP8 fixes

### PR DESCRIPTION
**Pull request by LordAro**
##### SUMMARY

So I was at a bit of a loose end, then I spotted legacy-files.txt. Then several hours passed and I'd edited a few hundred files.

Fixes PEP8 issues with lots of module files

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
Many

##### ADDITIONAL INFORMATION
I could probably go further, with not too much more effort...

### CODE REVIEW

**Comment by s-hertel** [comment]
Hi @LordAro. A problem with doing mass pep8 fixes is the fact that it would cause conflicts in many other existing pull requests without adding anything of value to the way the code functions.

In the original PEP, https://www.python.org/dev/peps/pep-0008/ , one of the good reasons to break PEP8 that they mention is because the code in question predates the introduction of the guideline and there is no other reason to be modifying that code.

**Comment by LordAro** [comment]
@s-hertel Yeah, it's not ideal, but I figure it's got to be done at some point and "normal" PRQs aren't likely to do it themselves. I've split the PRQ up into vaguely logical sections (and it's pretty trivial to split it further if you like), and I'm happy to rebase this in preference to other PRQs when necessary

Incidentally, with a fresh venv/pip install, I can't reproduce the above errors, are there version differences or something?

EDIT: Actually, those numbers don't actually seem to apply to those files. zabbix_maintenance.py isn't even 380 lines long...

**Comment by ryansb** [comment]
Actually there is a track record of PRs that fix a bug also cleaning up PEP8 in the files that are affected. Take https://github.com/ansible/ansible/commit/d6e1f029901b65b9e11450acee733e3e523b468f for example: the code needed to be changed, and in the "leave code cleaner than you found it" spirit, PEP8 fixes were also introduced. 

Ultimately, the goal isn't to follow PEP8, and while we appreciate your effort in editing these 260+ files we don't merge cosmetic-only PEP8 fixes.

**Comment by LordAro** [comment]
Well I guess that's fair enough, and I'm probably not going to convince you otherwise

Still, to salvage *some* work from this - there are 3 files in the list that are already PEP8 compliant -

    lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py 
    lib/ansible/modules/cloud/ovirt/_ovirt_affinity_groups.py
    lib/ansible/modules/cloud/openstack/_os_server_actions.py

Might as well get them removed before someone breaks them in amusing ways

@ryansb @s-hertel (hilight because closed issue)

**Comment by s-hertel** [comment]
@LordAro It looks like pep8 isn't being run on deprecated/renamed files with shippable. Manually checking, it doesn't look like these currently pass pep8.
_ec2_vpc_dhcp_options:
```
(python3.5.2) shertel-OSX-2:ansible shertel$ pep8 -r --max-line-length 160 --ignore=E305,E402,E722,E741 lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:238:1: E302 expected 2 blank lines, found 1
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:287:9: E123 closing bracket does not match indentation of opening bracket's line
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:315:43: E201 whitespace after '['
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:315:65: E202 whitespace before ']'
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:318:49: E201 whitespace after '['
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:318:82: E202 whitespace before ']'
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:325:36: E201 whitespace after '['
lib/ansible/modules/cloud/amazon/_ec2_vpc_dhcp_options.py:339:86: E231 missing whitespace after ':'
```

**Comment by LordAro** [comment]
@s-hertel well that's just even more confusing :p maybe bug/something to make it more obvious?

**Pull request closed without merging**
