### PR TITLE
Infoblox inventory Plugin

### PR DESCRIPTION
**Pull request by willtome**
##### SUMMARY
Implement Infoblox inventory script as a plugin

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Infoblox Inventory Script

### CODE REVIEW

**Comment by bmillemathias** [comment]
Hi @willtome 

as now ansible was split, do you consider to request this feature into collection [community.general](https://github.com/ansible-collections/community.general) ?

Best

**Comment by willtome** [comment]
@bmillemathias I believe this has been migrated to [infobloxopen](https://github.com/infobloxopen/infoblox-ansible/blob/master/ansible_collection/infoblox/nios_modules/plugins/inventory/nios_inventory.py). I'll defer to the Infoblox team. 

cc: @vaishnavi-infoblox @abenokraitis

**Comment by bmillemathias** [comment]
> @bmillemathias I believe this has been migrated to [infobloxopen](https://github.com/infobloxopen/infoblox-ansible/blob/master/ansible_collection/infoblox/nios_modules/plugins/inventory/nios_inventory.py). I'll defer to the Infoblox team.

thanks can you close this PR ?

Best

**Comment by abenokraitis** [comment]
Yes, all Infoblox content was migrated by Ansible to the community collection, but is being migrated again by Infoblox to their external GitHub where the inventory plugin is being picked up.

**Comment by Akasurde** [comment]
Hi @willtome, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
