### PR TITLE
Adding mysql firewall rule module

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Adding MySQL firewall rule module

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
azure_rm_mysqlfirewallrule

##### ANSIBLE VERSION
2.7

### CODE REVIEW

**Comment by Fred-sun** [comment]
@zikalino I try to test this PR, It can create MySQL fire rule( have idempotence). Three is no change when deleted the rule by ansible. need you help to fix. Thanks!
```e.g.

PLAY [for 45074 PR test] *****************************************************************

TASK [Gathering Facts] *******************************************************************
ok: [127.0.0.1]

TASK [Create or update Firewall Rulle] ***************************************************
 [WARNING]: Azure API profile latest does not define an entry for MySQLManagementClient

ok: [127.0.0.1]

TASK [delete Firwall rulle] **************************************************************
ok: [127.0.0.1]

PLAY RECAP *******************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0

**Comment by zikalino** [comment]
@Fred-sun I have tested this and I think you did something wrong, because it's covered in integration tests.

**Comment by Fred-sun** [comment]
@zikalino After I run ansible to delete rules, The rules still exist on azure portal( login azure portal check). But I can use azure portal to delete the rules. Thanks!

**Comment by Fred-sun** [comment]
@zikalino Do you reproduced this ? can't deleted firewallrule by use azure_rm_mysqlfirewallrule module. Thanks!

**Comment by zikalino** [comment]
@Fred-sun no, I don't have your playbook

**Comment by Fred-sun** [comment]
@zikalino My test yml as below:
```e.g.
---
- name: for 45074 PR test
  hosts: localhost
  connection: local
  tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        name: myRG
        location: westeurope

    - name: Create (or update) MySQL Server
      azure_rm_mysqlserver:
        resource_group: myRG
        name: fredtestserver01
        sku:
          name: GP_Gen4_2
          tier: GeneralPurpose
          capacity: 2
        location: westeurope
        #location: eastus
        storage_mb: 1024
        enforce_ssl: True
        version: 5.6
        admin_username: azureuser
        admin_password: Password@0329

    - name: Create or update Firewall Rulle
      azure_rm_mysqlfirewallrule:
        resource_group: myRG
        server_name: fredtestserver01
        name: rule1
        start_ip_address: 10.0.0.17
        end_ip_address: 10.0.0.20
      register: output

    - name: delete Firwall rulle
      azure_rm_mysqlfirewallrule:
        resource_group: myRG
        server_name: fredservertest01
        name: rule1
        state: absent

**Comment by zikalino** [comment]
@Fred-sun The reason it doesn't work is because you have different name of the server in the last task.

Pls compare:
server_name: fred**testserver**01
server_name: fred**servertest**01

**Comment by Fred-sun** [comment]
@zikalino Thanks Sir, It's my mistake. I retest and get successful result. Now,  It can be review by others or merged?

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
