### PR TITLE
postgresql_privs: add support a type parameter option for types

### LINKED ISSUE #62432: postgresql_privs module should support Altering permissions on database object type TYPES
##### SUMMARY
postgresql_privs module should support a type parameter option for TYPES to allow Grant/Revoke of usage permissions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_privs

##### ADDITIONAL INFORMATION
Types is supported in for assigning default privs, but we dont have parity for the ability to modify permissions of existing TYPES objects, GRANT USAGE ON TYPE schema.obj TO role;

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_privs: add support a type parameter option for types
fixes https://github.com/ansible/ansible/issues/62432

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/postgresql/postgresql_privs.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by TJEvans — APPROVED** [review]

**Review by TJEvans — CHANGES_REQUESTED** [review]
Thanks again for this update, its adds great additional functionality, but I believe it currently only supports the Public schema.

The request that inspired this involved a Grant on a Type obj that specified the schema,  "GRANT USAGE ON TYPE citus.shard_transfer_mode TO servicename".  

Because the pg_catalog.pg_type flattens the Types in typname, the get_type_acls query would not return the correct ACLs for the Type when Obj is specified using syntax Schema.Name and its unclear to me whether the module would error if provided a Schema input with the TYPE type.

**Comment by Andersson007** [comment]
@TJEvans , thanks! Will see
I'll mention you when it's solved

**Comment by Andersson007** [comment]
@TJEvans see the last three commits (two last are about a typo and comment)

**Comment by Andersson007** [comment]
ready_for_review

**Comment by TJEvans** [comment]
This seems to cover all the bases for my request,  Thanks again!
shipit

**Review by tcraxs — APPROVED** [review]
Works for me, good work!

shipit

**Comment by Andersson007** [comment]
@TJEvans @tcraxs thanks for reviewing and approving!

**Pull request merged**
