### PR TITLE
remidate Windows debugging documentation

### PR DESCRIPTION
**Pull request by jn-bedag**
##### SUMMARY
Using $complex_args is not working (anymore?). We need to set $params directly.

##### ISSUE TYPE
 - Docs Pull Request

### CODE REVIEW

**Comment by jborean93** [comment]
This still works fine for me, are you able to share more info as to what is happening?

**Comment by jn-bedag** [comment]
If I follow the current documentation, I get the following error:

```
PS C:\Users\Administrator> .\win_iis_webapppool.ps1
WARNING: The names of some imported commands from the module 'Ansible.ModuleUtils.Legacy' include unapproved verbs that might make them less discoverable. To find the commands
with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Get-Content : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Administrator\Ansible.ModuleUtils.Legacy.psm1:290 char:31
+         $params = Get-Content $arguments[0] | ConvertFrom-Json
+                               ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Content], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by jn-bedag** [comment]
Sorry for this, I had a buggy Ansible.ModuleUtils.Legacy.psm1
Some lines were commented.

**Comment by jn-bedag** [comment]
btw: I know that we are debugging here but still, thats the problem with "global" variables.
$params = $complex_args should not be set in the function, if we don't pass the variable to the function. Makes troubleshooting even harder :)

regards
jn

**Pull request closed without merging**
