### PR TITLE
[2.9] Fixed argument spec for multiple modules

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

This change contains fixes for argument spec and respective datatypes.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Backport of https://github.com/ansible/ansible/pull/65496

(cherry picked from commit 96df2bdcf360b3130a5c33eae13c0d066765a355)

##### ISSUE TYPE 
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/spec_fix.yml
lib/ansible/modules/cloud/amazon/cloudformation.py
lib/ansible/modules/cloud/amazon/redshift.py
lib/ansible/modules/cloud/ovirt/ovirt_permission_info.py
lib/ansible/modules/database/aerospike/aerospike_migrations.py
lib/ansible/modules/monitoring/librato_annotation.py
lib/ansible/modules/monitoring/logicmonitor_facts.py
lib/ansible/modules/monitoring/pagerduty_alert.py
lib/ansible/modules/network/aci/aci_access_port_to_interface_policy_leaf_profile.py
lib/ansible/modules/network/aci/aci_contract_subject_to_filter.py
lib/ansible/modules/network/icx/icx_logging.py
lib/ansible/modules/remote_management/manageiq/manageiq_alerts.py
lib/ansible/modules/storage/netapp/na_ontap_autosupport.py
lib/ansible/modules/storage/netapp/na_ontap_vscan_scanner_pool.py
lib/ansible/modules/storage/netapp/netapp_e_syslog.py
lib/ansible/modules/storage/netapp/netapp_e_volume.py

### CODE REVIEW

**Comment by cben** [comment]
The fixes LGTM but t I don't know ansible's backport policy.
Hypothetically, could this break some existing playbooks, e.g. omitting a `required` param that previously wasn't enforced (and the module somehow functioned) but now will be enforced?
Or a number passed where type='str' wasn't enforced but now will be?

**Comment by Akasurde** [comment]
> The fixes LGTM but t I don't know ansible's backport policy.
> Hypothetically, could this break some existing playbooks, e.g. omitting a `required` param that previously wasn't enforced (and the module somehow functioned) but now will be enforced?
> Or a number passed where type='str' wasn't enforced but now will be?

This backport only contains changes that are `required=False` and `type=str`  . These values are the default values of the module argument. So change will not affect any existing playbooks. Let me know.

**Comment by cben** [comment]
Ah, cool 👍 
shipit
(but i'm not a core reviewer, probably doesn't count)

**Comment by Akasurde** [comment]
> Ah, cool 👍
> shipit
> (but i'm not a core reviewer, probably doesn't count)

Every shipit counts 👍

**Review by mwperina — APPROVED** [review]
+1

**Comment by lonico** [comment]
We moved to collections.   So changes to this repo are mostly moot.

**Pull request merged**
