### PR TITLE
Rename ConfigureRemotingForAnsible.ps1 to Enable-WinRM.ps1

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

ConfigureRemotingForAnsible.ps1

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Make the script somewhat short, but provide a symlink for people referring to the old script.

### CODE REVIEW

**Comment by dagwieers** [comment]
As discussed with @nitzmahone

**Comment by sivel** [comment]
I know a symlink is being created with this, but that does not solve the problem of someone downloading the raw file via github.  Some users may be retrieving this file via HTTP, and retrieving the symlink via Github raw will leave them with a file that just reads `Enable-WinRM.ps1`

If we really need to rename it, I'd suggest not symlinking, and instead changing `ConfigureRemotingForAnsible.ps1` so that when executed it informs of the deprecation of that file, and mentions where to grab the new one.

**Comment by mattclay** [comment]
@dagwieers As noted by @sivel, and now verified by tests, we can't safely rename this file:

```
2017-01-06 18:42:20 Run command: test/sanity/code-smell/configure-remoting-ps1.sh
2017-01-06 18:42:20 The file "ConfigureRemotingForAnsible.ps1" is missing or is not a regular file.
2017-01-06 18:42:20 It is required by external automated processes and should not be moved or renamed.
2017-01-06 18:42:20 ERROR: Command "test/sanity/code-smell/configure-remoting-ps1.sh" returned exit status 1.
```

We could make the new name a symlink to the old, however.

**Comment by mattclay** [comment]
@dagwieers: We can't replace the old script, that will still break existing users.

Looks like I need a more robust test. :)

**Comment by dagwieers** [comment]
I don't agree, it would mean nothing can be changed, ever because someone could be referencing it.
Obviously we don't want to change things for fun, and maybe now it the time to organize it for the future.

I don't like the name at all. And we'd like to reference it from the vmware_guest module examples because there is a convenient way to automatically enable WinRM on cloned VMs. But I like to keep things concise. It doesn't need the "ForAnsible" in it, nor is it very clear that Remoting means WinRM.

**Comment by mattclay** [comment]
If we change it, we will break existing automated processes. It's not a question of if, it's only a matter of how many people will be affected. The file is widely used, as can be seen here:

https://github.com/ansible/ansible/graphs/traffic

**Comment by mattclay** [comment]
I also do not like the name, but I really don't want to break existing users.

**Comment by mattclay** [comment]
If we need a better name to reference, and a symlink to the old file won't do, we could have a copy of the file with a new name and the test could be updated to ensure the files are identical.

**Comment by dagwieers** [comment]
I cannot access that link. But most people access the link go through the website (I know I do every time).
Do the stats tell who is getting it through the link, or going directly ?
Then again I am not sympathetic with people automatically accessing that file, so breaking an insecure setup people are using is not such a bad idea ;-)

**Comment by dagwieers** [comment]
I'd not bother with the past too much, but make the future better so we don't have to ever move/rename it again.

**Comment by dagwieers** [comment]
I will look into a small wrapper script that gives a warning and downloads/run the new script.
I think that's best.

**Comment by mattclay** [comment]
@dagwieers The page provides stats for the last 2 weeks and shows 969 "views" and 522 "unique visitors" during that time period for the file.

**Comment by mattclay** [comment]
The warning isn't helpful for automated processes as nobody will see it.

You can add the new script, and we can stop referring to the old script in the documentation, but we need to give it time for people to stop using the old file first. We shouldn't be making changes to the old script -- it doesn't hurt anything to leave the deprecated copy in place.

**Comment by dagwieers** [comment]
Yes, it hurts because it doesn't help us move people to the new location. People will be using the old version forever more. Whereas a message, incl. attempted download and execute may help some to move as well.

The real solution would be a proper HTTP redirect (and thus a website) :-)

**Comment by mattclay** [comment]
What is the harm in allowing users to continue using the existing script?

If it's important to change the name of the script (I'm not convinced of the value), adding a new script will solve that problem. We can revisit the presence of the original script after a few releases to see if usage has declined.

On a side-note, if we do have a new script name, I'm not so sure it belongs in `examples/scripts/`. Perhaps `contrib/scripts/` would be more appropriate? @nitzmahone?

**Comment by bcoca** [comment]
we can add a big deprecation warning to the old one (in docs AND execution), add it to gitignore after that and in 2-4 versions remove it.

**Comment by bcoca** [comment]
contrib/!

**Comment by nitzmahone** [comment]
While I also hate the name (and location) of this particular script, I know a lot of people (myself and ansible-test included) are using the raw GH blob URL baked into UserData and other such things (especially since [I told them to do it that way](http://blog.rolpdog.com/2015/09/manage-stock-windows-amis-with-ansible.html)). 

I wasn't aware that symlinks don't work for raw GH content download when @dagwieers and I were talking about this. Given the way that UserData works (eg, seeing error output from UserData failures is nearly impossible), anything we do that moves or neuters this script will just outright break people, quite possibly in production (though relying on a raw GH link to keep your prod system working seems like a poor choice)... 

I think we might need a more careful approach to this rather than just ripping off the bandaid. :)

**Comment by dagwieers** [comment]
@nitzmahone Relying blindly on a script that lives on Internet (for running as Administrator on systems !) seems a worse offence than breaking its reference once though.

In fact the more I think about it, we are doing everyone a favor in breaking the reference ! Maybe we should break it on purpose more often ! Or add a backdoor ? Anyone ? (If that didn't scare anyone, what will ?)

BTW That was a joke :-)

**Comment by dagwieers** [comment]
Alright, as soon as #19909 is merged, I will do another attempt at getting the damn thing renamed ;-)

**Comment by Cryptophobia** [comment]
@dagwieers @nitzmahone @mattclay @bcoca : Breaking this script and renaming it for existing users is the worst thing we can do right now... In my company, we have user data scripts in AWS like @mattclay mentioned, and this is one of the scripts we get directly from your repo. The expectation is that we can always find the latest version of this script on your highly-active and updated GitHub Ansible repo rather than keeping some non-updated version in one of our private GitHub Enterprise repos.

Users expect resilience from you and renaming things is the worst form of resilience. An example: Last week we had to change all our user-data scripts to check for 201 status codes instead of 202 when sending jobs after upgrading to the latest Ansible Tower 3.0 API because some nerd complained that 202 is not the valid status code for "creating" jobs into the Ansible Tower API. Technically that is correct, but it created the following headaches: We had to change about 100 automation workflows and user-data for 50+ environment launch configurations...

Renaming and deprecating is a backwards incompatible change that can piss off users if not announced and somehow communicated far in advance.

I would vote not to do this renaming at all or to keep both files and to have them in sync all the time like @mattclay mentioned.

**Comment by bcoca** [comment]
I understand expecting resilience, but that should be on a 'shipped' product, not  a public development repo.

That said, I'm not in favor of changing this in a way that breaks your fetching of the script.

**Pull request closed without merging**
