### PR TITLE
Hostinfo dynamicinventory

### PR DESCRIPTION
**Pull request by AZaugg**
Created dynamic inventory for CMDB tool hostinfo

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not entirely sure of the rate of deployment of hostinfo so am unsure if we want to include this in core.  More information about how widely it is deployed would be useful to make the case for this.

Also, a few cleanup things - Can you please add copyright header information as per the other inventory scripts, and also modify functionNamesInCamelCase to be with_underscores, as suggested in our coding guidelines document https://github.com/ansible/ansible/blob/devel/CODING_GUIDELINES.md

Thank you!

**Comment by AZaugg** [comment]
I agree, hostinfo does not have a large user foot print at present

**Comment by BigAl** [comment]
This would be a handy feature. any chance to get it merged?

**Comment by dwagon** [comment]
As one of the hostinfo developers this would be a really cool feature :)

**Pull request closed without merging**
