### PR TITLE
change shebang from #!/usr/bin/python to #!/usr/bin/env python.

### PR DESCRIPTION
**Pull request by shirou**
This change enables to work on other os such as FreeBSD.

### CODE REVIEW

**Comment by mpdehaan** [comment]
You need to read the documention about the ansible_python_interpreter variable and how that works to select different pythons on different hosts.

We don't want to rely on the usr path, nor can we assume 'python' is the 2.X python.

**Comment by shirou** [comment]
Sorry, I haven't read that. I understand but ansible does not work on my FreeBSD 8.1R machine.

```
<myhost.example.com> EXEC /bin/sh -c ' /usr/bin/python /home/blah/.ansible/tmp/ansible-1367415798.66-40971013338719/ping; rm -rf /home/blah/.ansible/tmp/ansible-1367415798.66-40971013338719/ >/dev/null 2>&1'
myhost.example.com | FAILED >> {
    "failed": true,
    "msg": "/usr/bin/python: not found\n",
    "parsed": false
}
```

Should I repost on the Issues?

**Comment by bcoca** [comment]
run gmake, it will find the correct python

On Wed, May 1, 2013 at 9:51 AM, shirou notifications@github.com wrote:

> Sorry, I haven't read that. I understand but ansible does not work on my
> FreeBSD 8.1R machine.
> 
> <myhost.example.com> EXEC /bin/sh -c ' /usr/bin/python /home/blah/.ansible/tmp/ansible-1367415798.66-40971013338719/ping; rm -rf /home/blah/.ansible/tmp/ansible-1367415798.66-40971013338719/ >/dev/null 2>&1'myhost.example.com | FAILED >> {
>     "failed": true,
>     "msg": "/usr/bin/python: not found\n",
>     "parsed": false
> }
> 
> Should I repost on the Issues?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/2822#issuecomment-17282221
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
damn enter!

full msg this time:

run gmake, it will find the correct python on the master, set
ansible_python_interpreter: /usr/local/bin/python in group_vars/all if all
your hosts are FreeBSD or you can do group_vars/FreeBSD if you want to
group them in the inventory that way.

On Wed, May 1, 2013 at 9:58 AM, Brian Coca briancoca@gmail.com wrote:

> run gmake, it will find the correct python
> 
> On Wed, May 1, 2013 at 9:51 AM, shirou notifications@github.com wrote:
> 
> > Sorry, I haven't read that. I understand but ansible does not work on my
> > FreeBSD 8.1R machine.
> > 
> > <myhost.example.com> EXEC /bin/sh -c ' /usr/bin/python /home/blah/.ansible/tmp/ansible-1367415798.66-40971013338719/ping; rm -rf /home/blah/.ansible/tmp/ansible-1367415798.66-40971013338719/ >/dev/null 2>&1'myhost.example.com | FAILED >> {
> >     "failed": true,
> >     "msg": "/usr/bin/python: not found\n",
> >     "parsed": false
> > }
> > 
> > Should I repost on the Issues?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/2822#issuecomment-17282221
> > .
> 
> ## 
> 
> Brian Coca
> Stultorum infinitus est numerus
> 
> 0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
> Pedo mellon a minno

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by shirou** [comment]
Thank you. it works using this iventory host file.

```
[targets]
myhost.example.com  ansible_python_interpreter=/usr/local/bin/python
```

**Pull request closed without merging**
