### PR TITLE
Update win_domain_group_membership.py

### PR DESCRIPTION
**Pull request by thefaftek**
##### SUMMARY
Adding notes regarding a computer object and fixing a typo!

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY
Adding notes regarding a computer object and fixing a typo!

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
 win_domain_group_membership

##### ADDITIONAL INFORMATION
No change in output

### CODE REVIEW

**Comment by thefaftek** [comment]
I noticed this got flagged for affects_2.9. Any chance this can get pulled into 2.8 since it's just a doc fix for clarification?

**Comment by acozine** [comment]
@thefaftek thank you for contributing to the Ansible docs!

Our bot is marking all PRs `affects_2.9` because the current `devel` branch is 2.9 - we are currently backporting docs changes to `stable-2.8` after merging as well.

I don't entirely understand the line you added here. Should I add the `$` to the beginning or the end of the computer object, and what does the format look like? `server01.mydomain.com$`? An example might help me suggest refinements to that line.

**Comment by jborean93** [comment]
@acozine the `$` is a suffix and already as an example at https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain_group_membership.py#L85-L90. Just need the clarification that it should do onto the end. The value is the [sAMAccountName](https://docs.microsoft.com/en-us/windows/desktop/ADSchema/a-samaccountname) attribute for the AD object of the member.

**Comment by thefaftek** [comment]
@acozine My apologies for the lack of an example. I've added a second commit with an example attached and clarifying that this needs to be as a suffix. Thanks for getting back so fast on this one!

**Comment by acozine** [comment]
Thanks @thefaftek and @jborean93!

**Pull request merged**
