### PR TITLE
better handle appending \n on stderr

### LINKED ISSUE #39007: Dynamic inventory errors in 2.5.1
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lib/ansible/plugins/inventory/script.py

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = None
  configured module search path = [u'/Users/BR0kEN/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 10 2018, 00:01:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
Standard.

##### OS / ENVIRONMENT
```
Darwin Macintosh.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```

##### SUMMARY
The dynamic inventory (Python) script fails with an unknown error right after starting the process.

##### STEPS TO REPRODUCE

```bash
ANSIBLE_VERBOSITY=4 ansible-playbook 'test.yml' -c 'local' -i 'localhost,' -i 'inventory'
```

`test.yml`

```yaml
---
- hosts: all
  gather_facts: no

  tasks:
    - debug: msg=12
```

`inventory`

```python
#!/usr/bin/env python
import sys
import json
INVENTORY = {}

print(json.dumps(INVENTORY))
sys.exit(0)
```

##### EXPECTED RESULTS

```
ansible-playbook 2.5.1
  config file = None
  configured module search path = [u'/Users/BR0kEN/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Mar 10 2018, 00:01:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
No config file found; using defaults
setting up inventory plugins
Set default localhost to localhost
Parsed localhost, inventory source with host_list plugin
Parsed /usr/local/share/cikit/lib/inventory inventory source with script plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.5.1/libexec/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yml *****************************************************************************************************************************************************************************************
1 plays in /usr/local/share/cikit/scripts/test.yml
^C
PLAY [all] *************************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug] ***********************************************************************************************************************************************************************************************
task path: /usr/local/share/cikit/scripts/test.yml:7
ok: [localhost] => {
    "msg": "12"
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
ansible-playbook 2.5.1
  config file = None
  configured module search path = [u'/Users/BR0kEN/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Mar 10 2018, 00:01:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
No config file found; using defaults
setting up inventory plugins
Set default localhost to localhost
Parsed localhost, inventory source with host_list plugin
 [ERROR]:

Parsed /usr/local/share/cikit/lib/inventory inventory source with script plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.5.1/libexec/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yml *****************************************************************************************************************************************************************************************
1 plays in /usr/local/share/cikit/scripts/test.yml
^C
PLAY [all] *************************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug] ***********************************************************************************************************************************************************************************************
task path: /usr/local/share/cikit/scripts/test.yml:7
ok: [localhost] => {
    "msg": "12"
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
1 bash 2018-04-19 15-40-22

However, the `ANSIBLE_VERBOSITY=4 ansible-playbook 'test.yml' -c 'local' -i 'localhost,'` command (without dynamic invetory) works as expected.

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

fixes #39007

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

inventory/script
##### ANSIBLE VERSION

```
2.5-2.6
```

### CODE REVIEW

**Comment by jladdjr** [comment]
@bcoca - saw that this is going into `devel`. Is this being back-ported to 2.5.1 as well?

**Comment by bcoca** [comment]
@jladdjr 2.5.2 at earliest, 2.5.1 was already released

**Comment by thaumos** [comment]
@bcoca has this been cherry-picked into stable-2.5?

**Comment by BR0kEN-** [comment]
@bcoca Why is this not in 2.5.2?

**Comment by jladdjr** [comment]
@bcoca - I was also wondering the same thing. In case this hasn't been communicated, this is considered a breaking change to Tower and should be shipped ASAP.

**Comment by bcoca** [comment]
because it was scheduled for next week initially and i had scheduled merging a bunch of backports for this Friday, the sudden change in release date meant I would not have time to do so. Expect it for 2.5.3

**Pull request merged**
