### PR TITLE
A few more typos

### PR DESCRIPTION
**Pull request by dagwieers**
I came across another typo, and fixed similar ones in the docs.

### CODE REVIEW

**Comment by bcoca** [comment]
you have updated submodule refs, which i dont think we want.

**Comment by dagwieers** [comment]
Fixed.

**Comment by bcoca** [comment]
er .. now you has merge conflict?

**Comment by dagwieers** [comment]
Sigh, that's because the previous typo was on the same line and was merged now. That's how I found out about these new types of typo. Let me replay it on a clean tree.

**Comment by dagwieers** [comment]
I am completely lost now, sigh.

**Comment by dagwieers** [comment]
Hurray !

**Pull request merged**
