### PR TITLE
Use a pty for local connections when the command is sudoable

### LINKED ISSUE #38696: become_method: su fails with ansible_connection: local
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

local

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = ['/home/jotik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.5/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.5/ansible
  python version = 3.5.5 (default, Apr  2 2018, 22:33:24) [GCC 7.3.0]
```

##### CONFIGURATION

`ansible-config dump --only-changed` output is empty.

##### OS / ENVIRONMENT

Gentoo Linux.

##### SUMMARY

Using become method su fails with local connection.

##### STEPS TO REPRODUCE

```
echo localhost > inv
ansible -i inv localhost -a whoami -K --connection=local --become --become-method=su
```

##### EXPECTED RESULTS

`whoami` being executed as `root`, returning "root" in stdout.

##### ACTUAL RESULTS

The command fails with `privilege output closed while waiting for password prompt:`.

```
~/ansible_local_su_bug $ ansible -i inv localhost -a whoami -K --connection=local --become --become-method=su
SU password: 
localhost | FAILED | rc=-1 >>
privilege output closed while waiting for password prompt:


~/ansible_local_su_bug $
```

```
~ $ mkdir ansible_local_su_bug && chdir ansible_local_su_bug
~/ansible_local_su_bug $ echo localhost > inv
~/ansible_local_su_bug $ ansible -i inv localhost -a whoami -K --connection=local --become --become-method=su -vvvvansible 2.5.0
  config file = None
  configured module search path = ['/home/jotik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.5/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.5/ansible
  python version = 3.5.5 (default, Apr  2 2018, 22:33:24) [GCC 7.3.0]
No config file found; using defaults
SU password: 
setting up inventory plugins
Set default localhost to localhost
Parsed /home/jotik/ansible_local_su_bug/inv inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib64/python3.5/site-packages/ansible/plugins/callback/minimal.py
META: ran handlers
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jotik
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jotik/.ansible/tmp/ansible-tmp-1523567762.0106394-152209289126646 `" && echo ansible-tmp-1523567762.0106394-152209289126646="` echo /home/jotik/.ansible/tmp/ansible-tmp-1523567762.0106394-152209289126646 `" ) && sleep 0'
<localhost> PUT /home/jotik/.ansible/tmp/ansible-local-12318bjqsne6c/tmpok_b39ij TO /home/jotik/.ansible/tmp/ansible-tmp-1523567762.0106394-152209289126646/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/jotik/.ansible/tmp/ansible-tmp-1523567762.0106394-152209289126646/ /home/jotik/.ansible/tmp/ansible-tmp-1523567762.0106394-152209289126646/command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'su  root -c '"'"'/bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rgyjwrrxuygittyidokoladkllivbzop; /usr/bin/python /home/jotik/.ansible/tmp/ansible-tmp-1523567762.0106394-152209289126646/command.py'"'"'"'"'"'"'"'"''"'"' && sleep 0'
localhost | FAILED | rc=-1 >>
privilege output closed while waiting for password prompt:


~/ansible_local_su_bug $ /bin/sh -c 'su  root -c '"'"'/bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rgyjwrrxuygittyidokoladkllivbzop; /usr/bin/python /home/jotik/.ansible/tmp/ansible-tmp-1523567762.0106394-152209289126646/command.py'"'"'"'"'"'"'"'"''"'"' && sleep 0'
Password: 
BECOME-SUCCESS-rgyjwrrxuygittyidokoladkllivbzop

{"changed": true, "delta": "0:00:00.001274", "end": "2018-04-13 00:16:12.591236", "stdout": "root", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "_raw_params": "whoami", "removes": null, "stdin": null, "chdir": null, "warn": true}}, "cmd": ["whoami"], "rc": 0, "start": "2018-04-13 00:16:12.589962", "stderr": ""}
~/ansible_local_su_bug $
```

### PR DESCRIPTION
**Pull request by jimi-c**
Fixes #38696

### CODE REVIEW

**Comment by jimi-c** [comment]
!bot_skip

**Comment by abadger** [comment]
Is there a drawback to using a pty?  If not, then we should use it always.  That way there's less code paths where a bug can make something break.  (If there is a drawback, then perhaps we want to add a comment to be more restrictive in the future (only use it for the become methods where it's required).

**Comment by jimi-c** [comment]
I believe using a pty consumes file handles (could be wrong), but didn't want to impinge on the number of files further if we didn't have to.

**Comment by abadger** [comment]
This looks good to me... Of course, there's lots of other connection plugins that might benefit from this as well (the chroot family for instance).

**Comment by mattclay** [comment]
CI failure due to timeouts: https://app.shippable.com/github/ansible/ansible/runs/62296/59/console

The connection_local integration test is hanging at:

`TASK [remove remote file with unicode filename and content] ********************`

**Comment by bcoca** [comment]
rebase, tests and changelog would be nice

**Comment by bcoca** [comment]
closing in favor of rebased version

**Pull request closed without merging**
