### PR TITLE
refactors ansible-connection to use cli

### PR DESCRIPTION
**Pull request by privateip**
##### SUMMARY
* moves ansible-connection into cli module
* replaces ansible-connection with symlink to ansible
* adds PERSISTENT_CONNECT_CONTROL_PATH to constants

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
bin/ansible-connection
bin/ansible-connection
lib/ansible/cli/connection.py
lib/ansible/constants.py

##### ANSIBLE VERSION
2.4.0

### CODE REVIEW

**Comment by gundalow** [comment]
Difficult to tell what's changed here I wonder if doing a `git mv` would highlight what's changed to make it easier to review?

Is this for 2.3, if so please add milestone

**Comment by privateip** [comment]
This PR is for 2.4.  

This is step one in refactoring `ansible-connection` to using `ansible.cli.connection` and then linking back to `bin/ansible`.   There is no functional changes short of making `ansible-connection` more consistent with other executables

**Comment by abadger** [comment]
What are the benefits of this?  Having ansible-connection as a separate script had the following benefits to me:

* Smaller attack surface for someone looking to compromise ansible-connection
* ansible-connection doesn't really share concepts with the core of Ansible so the less that it needs the better
* Less memory usage if it doesn't have to pull in code that it's not going to end up using (it has a use for what, 5% of the code in CLI?  Less?)

These aren't big costs but htey do exist.  If there's a benefit, the benefit could easily outweigh this cost but I'd like to know that the benefit is there.

**Comment by privateip** [comment]
@abadger the reason for this PR is consistency in implementation.  By integrating with `ansible.cli` we get more consistency by way of return codes and execution.  To your more specific points:

* I don't believe this changes the attack vector one way or the other.
* I completely disagree with your statement that ansible-connection doesn't share concepts with core any more or less than other executable that we shipping.  I would like to better understand why you think this and see if we can bridge this divide
* This is a fair point given that the whole reason for the change is to introduce more consistency in the executable path.

**Pull request closed without merging**
