### PR TITLE
Update meraki_network.py

### PR DESCRIPTION
**Pull request by ericdost**
Fix examples from status to state

+label: docsite_pr

##### SUMMARY

Fix examples from status to state

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

meraki_network
##### ANSIBLE VERSION

```paste below
N/A
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by kbreit** [comment]
@ericdost Thanks for the PR. Copy and paste error apparently.

**Comment by kbreit** [comment]
shipit

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
@ericdost Thanks for the PR!

@kbreit will you take care of the backports to stable-2.6 (if necessary) and stable-2.7?

**Comment by kbreit** [comment]
@felixfontein Yes. The backports are on my todo for today or tomorrow.

**Pull request merged**
