### PR TITLE
ELB enhancements

### PR DESCRIPTION
**Pull request by ferrants**
- connection draining
- cross AZ load balancing

### CODE REVIEW

**Comment by analytically** [comment]
:+1:

**Comment by szesch** [comment]
:+1:

**Comment by jsmartin** [comment]
This option seems very clean.  It's more explicit than https://github.com/ansible/ansible/pull/8496, but may introduce more and more attribute settings and module options as they become available.

**Comment by jimi-c** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request merged**
