### PR TITLE
win_reg_stat: Clean up parameter handling

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_reg_stat

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Only minor changes.

### CODE REVIEW

**Comment by jborean93** [comment]
I take it you don't need to add the warnings to the return result?

shipit

**Comment by dagwieers** [comment]
I didn't see any warnings. But if you would need to "escalate" warnings, we now have `Add-Warning` and `Add-DeprecationWarning` functions that will add the required entry as part of the call. So it shouldn't be needed in the standard $result hash.

PS We also ensured that empty warnings in the output is properly cleaned up, so it's not a real problem anymore ;-)

**Comment by jhawkesworth** [comment]
shipit

**Comment by jhawkesworth** [comment]
bot_status

**Comment by dagwieers** [comment]
ready_for_review

**Pull request merged**
