### PR TITLE
Backport 2.9: Setup virtualization_facts - add RHV and oVirt type

### PR DESCRIPTION
**Pull request by mnecas**
##### SUMMARY

Backport of https://github.com/ansible/ansible/pull/72876

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
LGTM

**Comment by mnecas** [comment]
Hi @relrod,
what is the status of this?
Could we get it merged?

**Comment by relrod** [comment]
@mnecas I talked this one over with the other RMs a few days ago -- the change in behavior isn't something that we are comfortable backporting since this will break people relying on the current values (especially for `oVirt`). And 2.9 is now entering its security-only phase so we are only taking security fixes going forward. But the concern holds for the 2.10 backport too. I think this is a good patch to include in 2.11 (which it already is), but we don't think it should be backported because it's a breaking change.

**Comment by relrod** [comment]
Closing per above, and due to 2.9 now being security-only.

**Comment by sivel** [comment]
Re-opening, and approving for merge.

**Pull request merged**
