### PR TITLE
vmware_guest - Apply fix to allow the root resource pool of a cluster to be chosen

### LINKED ISSUE #28394: vmware_guest: No way to specify the root resource pool of a cluster
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/app/automation/ansible_library']
  python version = 2.7.13 (default, Feb  8 2017, 06:30:30) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

```

##### CONFIGURATION
No major changes.

##### OS / ENVIRONMENT
Vsphere 6.0

##### SUMMARY
In our environment, we generally want all VM's to sit at the root resource pool of the cluster.  However, in some clusters, we do have a single resource pool, that we do not want to put the general population of VM's into.  When the module sees the single resource pool, it chooses it, and there is no way to specify that I do not want that to occur.

I have hacked around this.  I believe the right fix might be a new option, resource_pool_is_root: bool.  I couldn't easily implement, because that module has now wildly diverged from 2.3.  Below is my hack:

        # set the destination datastore for VM & disks
        (datastore, datastore_name) = self.select_datastore(vm_obj)
        if self.params['resource_pool'] == 'root' and self.params['cluster']:
            cluster = self.cache.get_cluster(self.params['cluster'])
            if not cluster:
                self.module.fail_json(msg="Failed to find a cluster named %(cluster)s" % self.params)
	    resource_pool = cluster.resourcePool
        else:
            resource_pool = self.select_resource_pool(hostsystem)

##### STEPS TO REPRODUCE
Build a vm in a cluster with a single resource pool.

##### EXPECTED RESULTS
Be allowed to place the VM in the root pool

##### ACTUAL RESULTS
VM is forced into the child pool.

### PR DESCRIPTION
**Pull request by garbled1**
##### SUMMARY

vmware_guest - Apply fix to allow the root resource pool of a cluster to be chosen. Fixes #28394

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
ansible 2.5.0 (vmware_guest_rp 8f0395c383) last updated 2017/09/30 21:06:12 (GMT +000)
  config file = None
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/ansible/lib/ansible
  executable location = /home/ec2-user/ansible/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### ADDITIONAL INFORMATION

This adds the option resource_pool_cluster_root (bool), which allows one when specifying a cluster, to force the VM into the root resource pool of that cluster.

```
- name: Create a VM from a template
  vmware_guest:
    hostname: 192.0.2.44
    username: administrator@vsphere.local
    password: vmware
    validate_certs: no
    folder: /testvms
    name: testvm_2
    state: poweredon
    cluster: thecluster
    resource_pool_cluster_root: True
    template: template_el7
    disk:
    - size_gb: 10
      type: thin
      datastore: g73_datastore
    hardware:
      memory_mb: 512
      num_cpus: 1
      scsi: paravirtual
    networks:
    - name: VM Network
      mac: aa:bb:dd:aa:00:14
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy
```

### CODE REVIEW

**Comment by garbled1** [comment]
Looking at the code prior to my change, and the way the test is structured, I believe this would have failed with the in-tree module as well, because get_resource_pool would still return a module failure with no esxi_hostname or resource_pool argument supplied.

**Comment by Akasurde** [comment]
@garbled1 Could you please write integration test for this change ?

**Comment by Akasurde** [comment]
@garbled1 I can see another PR https://github.com/ansible/ansible/pull/31257 is also doing something similar.

**Comment by garbled1** [comment]
Closing, this branch is too mangled to continue.  Will open new pr

**Pull request closed without merging**
