### PR TITLE
Use ansible_host in synchronize module

### LINKED ISSUE #13073: synchronize uses deprecated ansible_ssh_host variable
Synchronize module doesn't work for me.

http://docs.ansible.com/ansible/intro_inventory.html states that ansible_ssh_host is deprecated.
The synchronize module tries to use this deprecated variable with fallback to the inventory_hostname. Neither works for me:
- ansible_ssh_host is not defined, I use ansible_host.
- inventory_hostname is an alias that is not resolvable with dns.

I think the module should try ansible_host first, then ansible_ssh_host for legacy inventories and fall back to inventory_hostname.

Thanks!

### PR DESCRIPTION
**Pull request by joernheissler**
Fixes #13073

### CODE REVIEW

**Comment by jimi-c** [comment]
@ianzd while this does fix the issue, and should probably be merged, I believe part of the underlying issue is that we're not setting all of the alternate values (if not otherwise set) when filling in missing variables (done in PlayContext). We probably want to fix that as well.

**Comment by abadger** [comment]
We took a look at the code in playcontext and realized that hostvars aren't part of this merging so (at least for now) we do think that having synchronize try multiple variable names is hte way to go.

**Comment by abadger** [comment]
@joernheissler Thanks for fixing this!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by abadger** [comment]
Cherry-picked to the stable-2.0 branch

**Pull request merged**
