### PR TITLE
Make example work: "Import Zabbix Temlate"

### PR DESCRIPTION
**Pull request by geekq**
+label: docsite_pr

##### SUMMARY
Fix non-working example for zabbix_template module.

It was a small typo, but it was hard to find, why the ansible module execution failed.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME

zabbix_template

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/d0e01962/.ansible.cfg
  configured module search path = [u'/home/d0e01962/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/d0e01962/.local/lib/python2.7/site-packages/ansible
  executable location = /home/d0e01962/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]

**Comment by D3DeFi** [comment]
good catch, thank you
shipit

**Comment by D3DeFi** [comment]
bot_status

**Comment by D3DeFi** [comment]
shipit

**Comment by eikef** [comment]
shipit

**Comment by eikef** [comment]
bot_status

**Comment by D3DeFi** [comment]
So this will probably require opening a new PR and closing this one as it seems somehow bugged. @eikef  what do you think?

**Pull request merged**
