### PR TITLE
ansible plugin ne commit, it can support Huawei route devices to automatically delivery feature configurations in batches

### PR DESCRIPTION
**Pull request by liqingkai2017**
…ch delivery configuration

##### ISSUE TYPE

 - New Module Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by liqingkai2017** [comment]
as we do this the first time, we need helps to complete the whole process

**Comment by gundalow** [comment]
1) For new platforms we are moving away from top-level or `provider` credentials. Instead new modules should be created to use the `network_cli` connection framework, please see https://github.com/ansible/community/blob/master/group-network/network_dev_network_cli.rst

2) I think `ne_` is way too generic

3) One module per PR, please see http://docs.ansible.com/ansible/dev_guide/developing_modules_in_groups.html

4) `_template` modules are deprecated, you should use a `_config` module instead
 
5) `__init__.py` files should be empty

6) Since Ansible 2.4 all new Network modules MUST have tests that run in our CI pipeline (GitHub/Shippable). This generally means unit tests must be added, please see
https://github.com/ansible/ansible/tree/devel/test/units/modules/network
http://docs.ansible.com/ansible/devel/dev_guide/testing_units.html

Please feel free to join `#ansible-network` on Freenode IRC for assistance

**Review by gundalow — CHANGES_REQUESTED** [review]
Updates needed

**Comment by gundalow** [comment]
From Ansible 2.6 we will only be accepting new Network platforms (groups of modules for a specific network OS) that use `network_cli`

Although this module is a candidate for Ansible 2.5 we'd still like to see it updated to use `network_cli`  and NOT `provider`. Although a bit of code will be required now, this will mean no changes to the user interface to the module, and therefore make users of these modules life's a lot easier.

We have some developer documentation on how to create a platform that only uses `network_cli` https://github.com/ansible/community/blob/master/group-network/network_dev_network_cli.rst which includes a forked version of `ios_command` which demonstrates this.

The user facing documentation for `network_cli` can be found at https://github.com/gundalow/ansible/blob/docs-network-use-cases/docs/docsite/rst/network_getting_started.rst


If you need any assistance with this please feel free to join us in `#ansible-network` on Freenode IRC

**Comment by mattclay** [comment]
bot_status

**Comment by mattclay** [comment]
CI failure in "other" tests: https://app.shippable.com/github/ansible/ansible/runs/45733/1/tests

The bot usually posts these test failures as comments.

**Comment by liqingkai2017** [comment]
@gundalow  as the documents write : 
1. Any new network CLI platforms added in Ansible 2.6 MUST:
be developed to support network_cli.
NOT use top-level nor provider: (as they are both being deprecated)
2. Network platforms that already existed in Ansible 2.5 (or earlier):
should be updated to support network_cli
MUST continue to support provider until Ansible 2.9 (at the earliest)

Does it mean we should provide two modules that one supports network_cli as the new specification and the other supports  provider as the old modules?
And now the stable version is 2.4，which version can we contribute our modules to ansible，2.5 version or later？

**Comment by gundalow** [comment]
@liqingkai2017 
New modules only go into `devel` branch, which will become Ansible 2.5.0

Create new modules for `devel` (2.5) which only use `network_cli`, using the guides in my earlier comment.
You do not need to support `provider:`

Feel free to join `#ansible-network` on Freendode IRC

**Comment by liqingkai2017** [comment]
@gundalow  We have  a problem in developing our ne_command plugin with the new network_cli connection framework and we need some help:

  as the example ios.py write :
        connection = Connection(module._socket_path)
        response = connection.get(command, prompt, answer)

we got a mistake : socket_path must be a value
can you tell us what can we do to make it ok

**Comment by liqingkai2017** [comment]
@gundalow  
As the document write:
NOT use top-level nor provider: (as they are both being deprecated)

Without  top-level or provider what way can we get the host ip、port、username、password and parameters like this

As the problem happened ,we think the key may be the process how we can get the host name from the playbook or adhoc,and with the host name to get host information from /etc/ansible/hosts, and then send to the AnsibleModule class, create a socket connection process

Can you describle the detailed process  in network_cli connection framework for us , and it is better to give us a playbook example and AdHoc example ,and base on the example we can do a debugging to see the process clearer and better 

Thanks a lot !

**Comment by gundalow** [comment]
Hi,
Have a look at the examples linked from https://github.com/ansible/community/blob/master/group-network/network_dev_network_cli.rst If you have further question feel free to join us in `#ansible-network` on Freenode IRC.

**Comment by yangting2** [comment]
@gundalow 
As the document write:
Have a look at the examples linked from https://github.com/ansible/community/blob/master/group-network/network_dev_network_cli.rst 
After building the environment,  example  playbook is not good enough to make the wrong MSG report: "unable to connect to socket", whether there is a module on the devel branch that has  be developed to support network_cli.  , like ce_command or ce_vlan.

**Comment by yangting2** [comment]
@gundalow 
When I use python2.7.13 and ansible2.4.2.0 to send the plug-in command that I developed,
the issuing of a single command can be executed normally,for example,"ansible -m test -a 'host=10.136.XX.XX port=22 username=ywx353660 password=Root@123 operation=get' localhost --connection local";
but,the error occurs "Error: The ncclient library is required." when I send the command by playbook,
My plug-in relies on ncclient,but I`ve installed ncclient-0.5.3 on Linux,
What is the reason for this? How should I do to solve it?

**Comment by zhaoxing1229** [comment]
@gundalow @yangting2
hi
I had the same problem with yangting, when I send commands by playbook.
Then I have tried to send the single command "ping" by playbook, it was OK.
But we don't know why the error occurs and how to solve the problem.

**Comment by zhaoxing1229** [comment]
@gundalow @yangting2

Is the problem related to  ncclient or playbook ?

**Comment by gundalow** [comment]
1) ensure that ncclient is installed along side the correct version of Python
`ansible-playbook --version` will tell you if Python 2 or 3 is being used.
If Ansible is using Python 2, though ncclient was installed using `pip3` it will not be available.

2) The  `ping` module will only work of Python is available on the remote device, which may not be the case for network switches.

**Comment by yangting2** [comment]
@gundalow 
hi
i checked the version of pip and ansible-playbook ,as follows ,

LFG1000012890:/ # ansible-playbook --version
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible-2.4.0.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.13 (default, Sep 13 2017, 15:45:26) [GCC 4.3.4 [gcc-4_3-branch revision 152973]]
LFG1000012890:/ # pip -V 
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
LFG1000012890:/ # pip2 -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
LFG1000012890:/ # pip3 -V
If 'pip3' is not a typo you can run the following command to lookup the package that contains the binary:
    command-not-found pip3
-bash: pip3: command not found

Pip3 is not installed  ,pip and play-book versions are consistent, is there any other reason for this problem ? only playbook failed to make a mistake that import ncclient failed, ad-hoc commad is ok , thanks

**Comment by gengxu0727** [comment]
@gundalow 
I had the same problem with yangting, and i used the same version of pip and ansible as yangting commented 3 days ago.
Pip3 is not installed ,pip and play-book versions are consistent, is there any other reason for this problem ? 
Please help us, thanks.

**Comment by liqingkai2017** [comment]
@gundalow  As the 2.5 version installing package has not been  available on GitHub currently , I check the 2.4 version already has cliconf code, is that mean network_cli is already available in  2.4 version?Can  I develop network_cli  plugins directly in the 2.4 version , and then use the 2.4 version to debug and test？

**Pull request closed without merging**
