### PR TITLE
ios_ntp: Switch interface to GigabitEthernet0/1 for tests

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Update ios_ntp tests with known good interface

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test ios_ntp integration

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 5432706af3f803e4791dfd66bc4ca5d058e75988

**Review by danielmellado — APPROVED** [review]
LGTM, Thanks Paul!

**Review by trishnaguha — COMMENTED** [review]
Instead of hard coding the interface in the test, can we get it from `prepare_ios_tests` like done in `ios_interface` https://github.com/ansible/ansible/blob/devel/test/integration/targets/ios_interface/tests/cli/basic.yaml#L6

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now fc0223aee74fb0a124dcac74a72af0c99ed3d94f

**Comment by NilashishC** [comment]
LGTM with the non hard coded interfaces.

**Review by NilashishC — APPROVED** [review]

**Review by trishnaguha — APPROVED** [review]

**Review by justjais — APPROVED** [review]

**Pull request merged**
