### PR TITLE
Table fixing

### PR DESCRIPTION
**Pull request by abadger**
##### SUMMARY
Fix tables which were formerly hardcoded
    
Tables had hardcoded line breaks to workaround a bug in the
read-the-docs theme.  Change those so that they now flow according to
the browser size.
    
Also switch away from grid tables to the simpler to create and read
simple tables

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION
This is built on top of https://github.com/ansible/ansible/pull/60171  which should be merged first.

### CODE REVIEW

**Comment by abadger** [comment]
Here's how the old table renders: https://docs.ansible.com/ansible/devel/network/user_guide/platform_eos.html   and the new table:  https://toshio.fedorapeople.org/ansible/new-platform-eos.png   There are a few minor differences which could be addressed if desired (I tried to lay out the new table to be better than the old one but some things can be made more similar to the old table if desired.)  The bigger question is whether the rst representation of the table is better this way or as the old grid table.  https://github.com/ansible/ansible/pull/60177/files#diff-8c76f8c42cd85480778c6033ce50e8c3

The new, simple table, should be easier to edit as it doesn't have the plethora of lines to keep lined up.  However, the old, grid table, might have an advantage when there are so many multi-line entries?  Please let me know which rst format we should use for this and similar tables :-)  Either way, I can now tweak the rendered form to take advantage of the new stylesheet elements.

**Comment by acozine** [comment]
Looks good. I tested messing up the whitespace, and Sphinx fails spectacularly, so it's easy to tell when you've done something wrong. And tables will be easier to edit without all the dashes and plus signs and so on. We should add something to the style guide about tables, pointing out the `|br|` and other ansible-specific formatting.

**Comment by abadger** [comment]
Okay, this PR is now ready for review.  It fixes the hardcoded line lengths in all tables in network/user_guide and changes them all from grid tables to simple tables.

**Comment by acozine** [comment]
Tested again with the rebased branch. The Settings by Platform section looks odd.

In current devel: https://docs.ansible.com/ansible/devel/network/user_guide/platform_index.html#settings-by-platform

With this branch:
Screen Shot 2019-08-13 at 3 52 51 PM

**Comment by abadger** [comment]
Yeah... that's a feature but I don't know if it's good.  the table used to have "fake footnotes".  They weren't a link, just the ascii ```[*]``` next to each netwok which was Maintained by the Ansible Network Team and then a line after the table which said ```[*] Maintained by the Ansible Network Team```.

I changed the "fake footnote" into a real footnote and that yields the format that you noticed.  It is meaningful, but now both you and I found that we struggled with what that meaning is.  What it's saying is "This is footnote 1.  It is referenced in 8 different places.  (1,2,3,4,5,6,7,8) are links to each of those places".

Would it be better if we used symbol-footnotes here instead of numbered-footnotes?  Then the citation at the bottom would render as ```†(1,2,3,4,5,6,7,8)```?

**Comment by abadger** [comment]
Doh!  You can only do manually specified numeric footnote, not symbolic footnotes.  So that won't work.... I can emulate a footnote with a link.... Perhaps that will look best (we won't have the backlink but the backlink is what we think looks odd, right?)

**Comment by abadger** [comment]
Here's the new look for the footnotes:

footnote

**Comment by acozine** [comment]
The best of both worlds! This allows the user to click on the dagger symbol and find out immediately what it means, and it's comprehensible to someone who's just reading the line at the bottom.

**Pull request merged**
