### PR TITLE
fix warning message "Ran out of time waiting for sg-xxx"

### PR DESCRIPTION
**Pull request by BitPan**
##### SUMMARY

 Fix issue #42661 - ec2_group "Ran out of time waiting for sg-xxx IpPermissions" if protocol set to numeric value 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_group module

##### ADDITIONAL INFORMATION

The current ec2_group module throws a warning message "Ran out of time waiting for sg-xxx IpPermissions..." when it performs any update on an existing security group.

I believe this error is because wait_for_rule_propagation() function is comparing the **current** security group state with incorrect **desired** state.

The list named_tuple_ingress_list and named_tuple_egress_list was supposed to represent the desired ingress and egress security group permissions, but they got modified in function update_rule_descriptions()

Deep copy the origin list named_tuple_ingress_list and named_tuple_egress_list to new variable desired_ingress and desird_egress to help maintain the desired ingress & egress security group permissions.

```
# named_tuple_ingress_list and named_tuple_egress_list do not 
# represents the desired security group permissions that user wants
security_group = wait_for_rule_propagation(module, group, named_tuple_ingress_list, named_tuple_egress_list, purge_rules, purge_rules_egress)
```

### CODE REVIEW

**Comment by lathama** [comment]
Any chance you could squash your commits?

**Comment by BitPan** [comment]
> Any chance you could squash your commits?

Done :)

**Review by jwitko — APPROVED** [review]
LGTM!  

Thank you very much for looking into this.

**Review by s-hertel — APPROVED** [review]

**Comment by s-hertel** [comment]
rebuild_merge

**Comment by s-hertel** [comment]
Thanks @BitPan!

**Comment by s-hertel** [comment]
@BitPan Please feel free to open a backport PR for 2.7  https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process.

**Pull request merged**
