### PR TITLE
Digitalocean public private ip

### PR DESCRIPTION
**Pull request by prutseltje**
##### SUMMARY

When creating a DigitalOcean droplet with private networking the module output value of ip_address contains the droplets private IP

Output code snippet:
```
"ip_address": "10.128.32.196",
    "kernel": null,
    "locked": false,
    "memory": 8192,
    "name": "test.domain.org",
    "networks": {
        "v4": [
            {
                "gateway": "10.128.1.1",
                "ip_address": "10.128.32.196",
                "netmask": "255.255.0.0",
                "type": "private"
            },
            {
                "gateway": "162.243.37.1",
                "ip_address": "162.243.37.240",
                "netmask": "255.255.255.0",
                "type": "public"
            }
        ],
        "v6": []
    },
    "next_backup_window": null,
    "region": {
```
I have added the following module output if available:
 - public_ipv4_address
 - private_ipv4_address
 - public_ipv6_address
 - private_ipv6_address

Output code snippet: 
```
"ip_address": "10.128.4.146",
    "kernel": null,
    "locked": false,
    "memory": 2048,
    "name": "test.domain.org",
    "networks": {
        "v4": [
            {
                "gateway": "10.128.1.1",
                "ip_address": "10.128.4.146",
                "netmask": "255.255.0.0",
                "type": "private"
            },
            {
                "gateway": "192.241.177.1",
                "ip_address": "192.241.177.65",
                "netmask": "255.255.255.0",
                "type": "public"
            }
        ],
        "v6": [
            {
                "gateway": "2604:A880:0000:1010:0000:0000:0000:0001",
                "ip_address": "2604:A880:0000:1010:0000:0000:28EC:D001",
                "netmask": 64,
                "type": "public"
            }
        ]
    },
    "next_backup_window": null,
    "private_ipv4_address": "10.128.4.146",
    "public_ipv4_address": "192.241.177.65",
    "public_ipv6_address": "2604:A880:0000:1010:0000:0000:28EC:D001",
    "region": {
```

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

digitalocean

##### ANSIBLE VERSION

```
ansible 2.2.3.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by BondAnthony** [comment]
Hey @prutseltje thanks for the contribution!  I do have one question around the change to the v4 addresses. I understand why you would be pulling the ipv6 addresses out but why duplicate ipv4 addresses? Both public and private addresses can be found in the response today.

Public ipv4 can be found at `droplet.ip_address` and the private ipv4 can be found at `droplet.private_ip_address`.

**Comment by prutseltje** [comment]
If you add a private network to the droplet, the private ip is used in the droplet.ip_address field, and the public IP is not.

**Comment by BondAnthony** [comment]
@prutseltje you sure about that?

Here is the response of a droplet I just created.
```
            "ip_address": "67.205.178.113", 
            "kernel": null, 
            "locked": false, 
            "memory": 512, 
            "name": "Test01", 
            "networks": {
                "v4": [
                    {
                        "gateway": "10.136.0.1", 
                        "ip_address": "10.136.28.235", 
                        "netmask": "255.255.0.0", 
                        "type": "private"
                    }, 
                    {
                        "gateway": "67.205.176.1", 
                        "ip_address": "67.205.178.113", 
                        "netmask": "255.255.240.0", 
                        "type": "public"
                    }
                ], 
                "v6": [
                    {
                        "gateway": "2604:A880:0400:00D0:0000:0000:0000:0001", 
                        "ip_address": "2604:A880:0400:00D0:0000:0000:4619:4001", 
                        "netmask": 64, 
                        "type": "public"
                    }
                ]
            }, 
            "next_backup_window": null, 
            "private_ip_address": "10.136.28.235", 
            "region": {

```

Here is the play being executed:
```
    - digital_ocean:
        state: present
        command: droplet
        name: Test01
        api_token: key
        size_id: 512mb
        region_id: nyc1
        image_id: centos-6-x64
        wait_timeout: 500
        ipv6: yes
        private_networking: yes
      register: droplet

```

**Comment by prutseltje** [comment]
I have just created a droplet and here is my output:

```
            "ip_address": "10.128.25.248",
            "name": "testnode1",
            "networks": {
                "v4": [
                    {
                        "gateway": "10.128.25.1",
                        "ip_address": "10.128.25.248",
                        "netmask": "255.255.0.0",
                        "type": "private"
                    },
                    {
                        "gateway": "162.243.18.1",
                        "ip_address": "162.243.18.130",
                        "netmask": "255.255.255.0",
                        "type": "public"
                    }
                ],
                "v6": []
            },
            "next_backup_window": null,
            "region": {
                "available": true,
```
OS and package info:

OSX                    10.12.4
ansible                2.3.1.0
dopy                   0.3.5

**Comment by BondAnthony** [comment]
@prutseltje I believe this might be an issue with your dopy version. Could you update that to 0.3.7 and try again? Since your on an old version of OSX you will probably also need to update six to at least 1.10.0. Try to update dopy and test first before updating six.

**Comment by prutseltje** [comment]
@BondAnthony Upgrading dopy to 0.3.7 solves my issue with the public ip_address.
Do you want me to update the pr to only add the ipv6 address to the output?

**Comment by BondAnthony** [comment]
@prutseltje Yes could please update the pr to only include the ipv6 addresses. I think what you have here will help users who are searching for ipv6 addresses. Just a heads up I'm working to remove `dopy` as a dependency to these modules.

**Comment by prutseltje** [comment]
@BondAnthony, I have removed the IPV4 addresses

**Review by BondAnthony — APPROVED** [review]
shipit

Thank you @prutseltje for the contribution.

**Comment by BondAnthony** [comment]
bot_status

**Comment by BondAnthony** [comment]
@Akasurde could you please review this.

**Comment by BondAnthony** [comment]
@pmarques could I get a second `shipit` on this module so we can merge the code.

**Comment by pmarques** [comment]
LGTM

shipit

**Comment by thomwiggers** [comment]
If this is labelled automerge, I guess the bot is stuck. 

bot_broken

**Comment by gundalow** [comment]
rebuild_merge

**Comment by BondAnthony** [comment]
I think the bot is still having issues with this PR.

bot_broken

**Comment by Akasurde** [comment]
Closing and Re-opening to trigger CI.

**Pull request merged**
