### PR TITLE
Fix to tags issue for container registry facts module

### LINKED ISSUE #58129: azure_rm_containerregistry_facts does't accept tags
##### SUMMARY
When using azure_rm_containerregistry_facts, if I specify tags, it fails with a dictionary error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_containerregistry_facts

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/val/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/z/.local/lib/python2.7/site-packages/ansible
  executable location = /home/z/.local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

WSL (Ubuntu 18.04 under  Windows)

##### STEPS TO REPRODUCE

1. Create the playbook below
2. Run it. See it fail.
3. Remove the tags directive.
4. Run it. See it pass.

```yaml
- name: Get facts for registry
  azure_rm_containerregistry_facts:
    resource_group: mygroup
    name: myacr
    tags:
      - a:b
```

##### EXPECTED RESULTS
Tags directive should be accepted.

##### ACTUAL RESULTS

```paste below
TASK [my_test : Get facts for registry] ***************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Tags must be a dictionary of string:string values."}
```

### PR DESCRIPTION
**Pull request by mmyyrroonn**
##### SUMMARY

Fixes #58129
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_containerregistry_facts
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@yungezz @zikalino Please take a review this PR when you're available! Thank you very much!

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@yungezz @zikalino Please take a review this when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
@MyronFanQiu Please resolve the conflicting files and push for review! Thanks a lot!

**Comment by Fred-sun** [comment]
@MyronFanQiu

**Comment by Fred-sun** [comment]
@MyronFanQiu Please help rebase this PR when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Can you help me look at this conflicting file? Check the file, just change a bit, also did not hint at any conflict! Thank you very much!

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang review_need!

**Review by gavinfish — APPROVED** [review]
shipit

**Pull request closed without merging**
