### PR TITLE
Added AIX CA certs search paths

### LINKED ISSUE #69721: Add AIX default CA certs path to module_utils/urls.py
##### SUMMARY

Adding the AIX standard capath to the CA certs search folders

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- Playbook module: uri
- get_ca_certs in class SSLValidationHandler
- At line: https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/module_utils/urls.py#L833

##### ADDITIONAL INFORMATION

Problems:
- The **uri** Ansible playbook module fails to GET https in AIX
- Missing the AIX standard CA certs locations 

Solution:
We will have better support for the uri Ansible module under AIX managed host
By adding:
```python
        elif system == u'AIX':
            paths_checked.append('/var/ssl/certs')
            paths_checked.append('/opt/freeware/etc/ssl/certs')
```
Those cert paths are part of the package **ca-certificates** downloadable from the IBM Official [AIX Toolbox for Linux® Applications site](https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha#C)
 

```yaml
- name: GET https page
  uri:
    url: https://www.google.com
    method: GET
    return_content: yes
    validate_certs: yes
  register: get_replay
```
Before the change:
```
TASK [users-access : GET https page] *******************************************************************
fatal: [myserver]: FAILED! => {
    "changed": false,
    "content": "",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                200
            ],
            "timeout": 30,
            "unix_socket": null,
            "unsafe_writes": null,
            "url": "https://www.google.com",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>",
    "redirected": false,
    "status": -1,
    "url": "https://www.google.com"
}
```
After the change:
```
TASK [users-access : GET https page] *******************************************************************
ok: [myserver] => {
    "accept_ranges": "none", 
    "alt_svc": "h3-27=\":443\"; ma=2592000,h3-25=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
    "cache_control": "private, max-age=0", 
    "changed": false, 
    "connection": "close", 
    "content": ".....",
    "content_type": "text/html; charset=ISO-8859-1", 
    ...
    ...
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "body": null, 
            "body_format": "raw", 
            "client_cert": null, 
            "client_key": null, 
            "content": null, 
            "creates": null, 
            "delimiter": null, 
            "dest": null, 
            "directory_mode": null, 
            "follow": false, 
            "follow_redirects": "safe", 
            "force": false, 
            "force_basic_auth": false, 
            "group": null, 
            "headers": {}, 
            "http_agent": "ansible-httpget", 
            "method": "GET", 
            "mode": null, 
            "owner": null, 
            "regexp": null, 
            "remote_src": null, 
            "removes": null, 
            "return_content": true, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "status_code": [
                200
            ], 
            "timeout": 30, 
            "unix_socket": null, 
            "unsafe_writes": null, 
            "url": "https://www.google.com", 
            "url_password": null, 
            "url_username": null, 
            "use_proxy": true, 
            "validate_certs": true
        }
    },
    "msg": "OK (unknown bytes)",
    "p3p": "CP=\"This is not a P3P policy! See g.co/p3phelp for more info.\"",
    "redirected": false,
    "server": "gws",
    "set_cookie": "...",
    "status": 200,
    "transfer_encoding": "chunked",
    "url": "https://www.google.com",
    "vary": "Accept-Encoding",
    "x_frame_options": "SAMEORIGIN",
    "x_xss_protection": "0"
```

### PR DESCRIPTION
**Pull request by amirm-hrl**
##### SUMMARY
Added the AIX CA certs folders
This PR add a more native TLS support when using the **url** tasks on managed AIX hosts

Fixes #69721 
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- Effect playbook module: uri
- change **get_ca_certs** of class SSLValidationHandler in `module_utils/urls.py`

##### ADDITIONAL INFORMATION
AIX store the root CA certs in the folders `/var/ssl/certs` and `/opt/freeware/etc/ssl/certs`
Currently the `module_utils/urls.py` doen't contain any AIX CA certs search paths
This PR will add support for the AIX default CA certs folders.

* AIX root CA certs are installed using the RPM package **ca-certificates** downloadable from the IBM Official [AIX Toolbox for Linux® Applications site](https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha#C)

To see the problem, a simple uri task will fail on aix:
```yaml
- name: GET https page
  uri:
    url: https://www.google.com
    method: GET
    return_content: yes
    validate_certs: yes
  register: get_replay
```

Before the change:
```
TASK [users-access : GET https page] *******************************************************************
fatal: [myserver]: FAILED! => {
...
...
    "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>",
    "redirected": false,
    "status": -1,
    "url": "https://www.google.com"
}
```

After the change:
```
TASK [users-access : GET https page] *******************************************************************
ok: [myserver] => {
...
...
    "msg": "OK (unknown bytes)",
    "p3p": "CP=\"This is not a P3P policy! See g.co/p3phelp for more info.\"",
    "redirected": false,
    "server": "gws",
    "set_cookie": "...",
    "status": 200,
}
```

### CODE REVIEW

**Comment by mattclay** [comment]
We should be able to test this in CI, but there are a few things blocking that:

1. AIX is disabled due to infrastructure issues. This should be fixed soon.
2. The get_url and uri tests are skipped on AIX. There are likely multiple reasons for that, one being that the SSH port forwarding used to connect back to the http-test-container isn't implemented in ansible-test for AIX yet.

**Comment by sivel** [comment]
> We should be able to test this in CI,

I agree. This would probably be a good time to get it working and tested in CI.  Which will also require changes to `test/integration/targets/prepare_http_tests/`

**Comment by amirm-hrl** [comment]
@sivel - Do you know if the AIX CI servers have the **ca-certificates** package (from the IBM [AIX Toolbox for Linux® Applications site](https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha#C)) installed on them?

If not, we should probably create the `/var/ssl/certs` folder before downloading the `ansible.http.tests/cacert.pem` to it, (in `test/integration/targets/prepare_http_tests/tasks/default.yml`)

**Review by amirm-hrl — COMMENTED** [review]
I'm ready to marge

**Comment by mattclay** [comment]
@amirm-hrl AIX tests are currently disabled. Once they've been restored we can see what else may be needed to get this working in the tests.

**Comment by jborean93** [comment]
I've pushed a commit that rebases the code and removes the test as we are no longer testing against AIX.

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
