### PR TITLE
use ConfigObj instead of ConfigParser in ini_file

### PR DESCRIPTION
**Pull request by berendt**
To make it possible to manage the DEFAULT section with ini_file
I changed the config file reader/writer from ConfigParser to
ConfigObj.

Details are available in issue #1682.

### CODE REVIEW

**Comment by jpmens** [comment]
That doesn't look like a solution to me, b/c it needs an additional module:

```
Python 2.7.3 (default, Jul  8 2013, 14:57:33)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.24)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from configobj import ConfigObj, ConfigObjError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named configobj
>>>
```

**Comment by berendt** [comment]
Why not? With ConfigObj it's possible to add/edit/delete the section DEFAULT without problems. And because the problem is that it's not possible to add/edit/delete the section DEFAULT using ConfigObj is a solution for this problem.

Why is it a problem that an additional module is needed?

**Comment by jpmens** [comment]
Agree that ConfigObj may be better, but I'd have to install ConfigObj on all nodes, wouldn't I?

**Comment by berendt** [comment]
Probably. Have not yet looked inside the deployment methods of Ansible. I thought that the entry "requirements: [ configobj ]" in the DocString will automatically deploy configobj on the target nodes.

If it's a problem to use an additional module in ini_file could we introduce a new module, for example inifile? Because of OpenStack I really need to modify the DEFAULT sections inside a lot of INI files and I don't want to maintain modules in an external repository.

**Comment by jpmens** [comment]
`requirements` in the docstring is just a comment.

**Comment by mpdehaan** [comment]
It would be better to rewrite the module to just make it work, however needed. 

The additional dependency however isn't good.   Consider replacing "DEFAULT" through various magic to "[THIS_IS_NOT_NAMED_DEFAULT]" ?  :)

**Comment by berendt** [comment]
The module can't be rewritten. Not using DEFAULT as section name is a limitation of ConfigParser. The section in OpenStack has to be named DEFAULT and I don't want to work with lineinfile or something else.

I'll provide the alternative implementation using ConfigObj at https://github.com/berendt/ansible_extensions, if anybody else want to use DEFAULT sections...

**Comment by sheldonh** [comment]
Thanks, berendt. It's a shame ansible can't do OpenStack configs out of the box, but great that you've made a work-around available.

**Pull request closed without merging**
