### PR TITLE
Added redis config module (slave and flush)

### PR DESCRIPTION
**Pull request by slok**
Sorry for the delay, busy weeks :/

Here is the unified version of the other 2 pull requests: #3334 and #3344

Hope all is ok :)

### CODE REVIEW

**Comment by mpdehaan** [comment]
As "action" is already a keyword in ansible, can we make this called "command" or something similar?

Otherwise looks good, thanks!

**Comment by slok** [comment]
Oh, sorry. No problem :D I will change that right now!

**Comment by slok** [comment]
Done! :)

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
