### PR TITLE
Fixing state=present for jenkins_plugin module (#52051)

### PR DESCRIPTION
**Pull request by jtyr**
(cherry picked from commit 5f4840aaa821da4026f35b8798860a4234ac35da)

##### SUMMARY
This is backport of the PR #52051.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
`jenkins_plugin`

##### ADDITIONAL INFORMATION
@gundalow please merge.

### CODE REVIEW

**Comment by abadger** [comment]
This will need a changelog fragment to be merged into the stable-2.7 branch.

**Comment by gundalow** [comment]
@jtyr Thanks for creating backports, no need to `@mention` anyone on backports.

https://docs.ansible.com/ansible/devel/community/development_process.html#making-your-pr-merge-worthy has details on changelog. For future bugfixes you can include in the changelog in the original PR to devel

**Comment by jtyr** [comment]
@gundalow Changelog artefakt added.

**Comment by abadger** [comment]
Merged for the 2.7.9 release.

**Pull request merged**
