### PR TITLE
win_shortcut: Fail when command is not absolute path

### LINKED ISSUE #24494: win_shortcut: Using a relative src= can cause error
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_shortcut

##### ANSIBLE VERSION

v2.3+

##### SUMMARY

When using a task like this:
```yaml
- name: Create putty shortcut
  win_shortcut:
    src: 'putty.exe'
    dest: '%Public%\Desktop\PuTTY.lnk'
    icon: '%ProgramFiles%\PuTTY\putty.exe,0'
```

The following error occurs:
```
fatal: [windows-2012]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "
        Exception setting \"TargetPath\": \"The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))\"
        At line:89 char:9
        +         $ShortCut.TargetPath = $src
        +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : CatchFromBaseAdapterSetValueTI", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

This is fixed by using an absolute path:
```yaml
- name: Create putty shortcut
  win_shortcut:
    src: '%ProgramFiles%\PuTTY\putty.exe'
    dest: '%Public%\Desktop\PuTTY.lnk'
    icon: '%ProgramFiles%\PuTTY\putty.exe,0'
```

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
What was missing from the existing code was a check to see if the $src was an absolute path.

This fixes #24494

This PR also includes:
- Reworked integration tests (add check-mode support and return values)
- Reworked documentation and examples

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_shortcut

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Code looks fine but maybe add to the documentation that if the src is a path, it should be absolute?  We allow relative windows paths elsewhere (win_copy $dest for example).

**Comment by jhawkesworth** [comment]
Thanks, like the updated tests too.

**Comment by jhawkesworth** [comment]
@dagwieers - just checking to see if this is good to go.
Not sure what your #ansible-windows comment 'hmm, need to quote this error msg: https://github.com/ansible/ansible/pull/26533/files#diff-2923d6895a6a561b9ad59b6803ac9961R144' meant though.  Quoting looks ok there to me - maybe you fixed already?

If you really want to split hairs could make the all Fail-Json calls use -obj and -message like L86 but that's the only (tiny) thing I can see here.

**Comment by dagwieers** [comment]
Yeah, I fixed it. These days I prefer to quote variables in an error-string, like:
```powershell
Fail-Json -obj $result -message "The destination path '$dest' does not exist"
```
I was referring to one instance where I forgot ;-)

PS Also fixed the `Fail-Json` call, I prefer doing `-obj` and `-message` now too.

**Comment by dagwieers** [comment]
@nitzmahone @jborean93 @jhawkesworth Can we merge this ?

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
@nitzmahone @jborean93 @jhawkesworth Can we merge this ?

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
