### PR TITLE
Support require x509 privilege

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
##### SUMMARY
Allows granting the special REQUIRE X509 privilege. Similar to REQUIRE SSL but more restrictive as it requires both server and client certificate validation.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mysql_user

### CODE REVIEW

**Comment by jpmens** [comment]
If this is added, we could consider adding support for `REQUIRE SUBJECT` as well:

```
GRANT ALL ON db.* TO 'jane'@'%'  REQUIRE SUBJECT '/CN=jjolie@example.org';
```

**Comment by Jorge-Rodriguez** [comment]
@jpmens, I'm more than happy to update the PR with `REQUIRE SUBJECT`

**Comment by rwky** [comment]
REQUIRE CIPHER and ISSUER would be good so then we have everything https://mariadb.com/kb/en/library/securing-connections-for-client-and-server/#requiring-tls

**Comment by Andersson007** [comment]
@Jorge-Rodriguez hey!
Could you please move this PR to https://github.com/ansible-collections/community.general
Then:
1. add a changelog fragment https://github.com/ansible-collections/community.general to ./changelogs directory
2. add CI tests if you can
3. mention me there for review

Thanks in advance!

**Comment by Jorge-Rodriguez** [comment]
I'm currently AFK, but I can get this done when I come back in May.

Cheers,
Jorge

**Comment by Andersson007** [comment]
@Jorge-Rodriguez nice

**Comment by Jorge-Rodriguez** [comment]
This PR has been moved to ansible-collections.

**Comment by nerijus** [comment]
Where was it moved? Could you please show URL?

**Comment by Jorge-Rodriguez** [comment]
https://github.com/ansible-collections/community.general/pull/369

**Pull request closed without merging**
