### PR TITLE
cloud: ovirt: add host engine options to ovirt_hosts

### LINKED ISSUE #20966: Missing deployment of Hosted Engine in ovirt_hosts module
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
oVirt host module
https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/ovirt/ovirt_hosts.py

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

In 4.1 we no longer could add additional hosts to hosted engine environment with command of
"hosted-engine --deploy" we should do it thru the GUI/API
but in this ovirt_hosts module we missing the deployment of Hosted Engine option.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ovirt_hosts

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This patch adds an option to deploy and undeploy host as hosted engine in oVirt.
This fixes: https://github.com/ansible/ansible/issues/20966

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina

**Review by mwperina — APPROVED** [review]
Looks good to me, thanks! 👍

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
@ryansb

**Review by ryansb — APPROVED** [review]

**Pull request merged**
