### PR TITLE
add (un)silence_nagios and command actions to the nagios module

### PR DESCRIPTION
**Pull request by skvidal**
also fix a typo with the check_mode check

this just adds a raw command action, changes the default requirements for running an action and fixes up the notification formatting for the above.

### CODE REVIEW

**Comment by skvidal** [comment]
I'd also like to loop @tbielawa into this for review since he wrote the original one.

**Comment by timlnx** [comment]
Will check this out this weekend.

**Comment by timlnx** [comment]
Doc string says command is `required: true` but `AnsibleModule` says `command=dict(required=False, default=None),`

**Comment by timlnx** [comment]
I can confirm that silence_nagios and unsilence_nagios work as advertised!

**Comment by timlnx** [comment]
I can confirm that the command action works as advertised.

+1 once the documentation typo is corrected.

**Comment by mpdehaan** [comment]
is there a pull request to fix the docs?

**Comment by skvidal** [comment]
command is required if action=command.

it can't be required in the command dict() b/c it is not required in EVERY case.

Same as host is not required for silence_nagios but it is for every other action.

How should this be fixed?

**Comment by mpdehaan** [comment]
Is there actually a problem?   I'm deferring to you guys here :)

**Comment by mpdehaan** [comment]
cricket.

@skvidal @tbielawa -- you guys agree this is good to merge or is something still outstanding?

Thanks!

**Comment by timlnx** [comment]
Ship it

**Comment by mpdehaan** [comment]
go-go-gadget-merge-button

merged, thanks!

**Pull request merged**
