### PR TITLE
Allow wait_for_ip_address=yes when powering on a guest that already exists

### PR DESCRIPTION
**Pull request by lparkes**
##### SUMMARY

I have a  playbook that runs something like this:

- vmware_guest: state=poweredoff ...
- template: dest=/var/lib/tftpd/pxelinux.cfg/01-{{ ...mac_address.. }}
- vmware_guest: state=poweredon wait_for_ip_address=yes
- file: dest=/var/lib/tftpd/pxelinux.cfg/01-{{ ...mac_address.. }} state=absent
- wait_for: port=22 host={{ the guest's IP address }}

As things stand at the moment, wait_for_ip_address is ignored when powering on a guest that already exists, and so my playbook deletes the custom PXELinux configuration before the guest has booted far enough to have read it.

It seems to me that wait_for_ip_address should be honoured any time state=poweredon is used.

I did think about refactoring to pull the original call to wait_for_vm_ip() up out of deploy_vm(), but that looked like more complicated than was wise for an initial stab at this module.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = None
  configured module search path = [u'/Users/lloyd/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lloyd/software/ansible/lib/ansible
  executable location = /Users/lloyd/software/ansible/bin/ansible
  python version = 2.7.12 (default, Sep  3 2016, 11:44:23) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### ADDITIONAL INFORMATION

There are no changes to Ansible's ouput as such, but the following task simply takes longer to run with my patch because it waits for the guest to report its IP address with VMware tools.
```
  - name: Power on VM
    vmware_guest:
      hostname: "{{ vmware_api }}"
      username: "{{ vmware_user }}"
      password: "{{ vmware_pw }}"
      datacenter: Downstairs
      name: testvm_2
      state: poweredon
      wait_for_ip_address: yes
    register: poweron
```

### CODE REVIEW

**Review by dav1x — APPROVED** [review]
lgtm

**Comment by Akasurde** [comment]
@lparkes Could you please write an integration test for this change?

**Comment by lparkes** [comment]
Maybe. Which vCenter simulator is used with the integration tests? The old VCSA 5.5 one, the newer Go one, or some other one that I haven't found yet? There seems to be a bug with vCenter 5.5 (but not vCenter 6.5) whereby the IP address isn't passed back through pyvmomi, which makes automatic verification of the wait_for_ip option impossible.

I have no idea how well the simulator will work with the wait_for_ip functionality, but if you tell me which simulator to use, I'll go and find out.

**Comment by Akasurde** [comment]
@lparkes Sorry for the delay. We have a newer vCenter simulator used in the integration tests. You can check documentation [here](https://github.com/ansible/community/wiki/VMware%3A-govcsim). I am also not sure wait_for_ip functionality but it will be good to have an integration test for this change. 

Let me know if you need any help on this.

**Pull request closed without merging**
