### PR TITLE
Declare Framework::Ansible classifier for PyPI

### PR DESCRIPTION
**Pull request by moreati**
##### SUMMARY

https://github.com/pypa/trove-classifiers/pull/61 added Ansible as a
classifier for projects on PyPI. This allows Python projects, and their
distributions (e.g. ansible-lint) to declare they use, enhance, or
otherwise involve Ansible.

PyPI projects can be filtered by this classifier, <https://pypi.org/search/?c=Framework+%3A%3A+Ansible>,

Signed-off-by: Alex Willmer <alex@moreati.org.uk>

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @abadger @gundalow

**Comment by mkrizek** [comment]
Can you add a changelog https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#changelogs?

**Review by webknjaz — APPROVED** [review]
I've been rejecting similar PRs in the past thinking that the frameworks themselves shouldn't be using their own trove classifiers, reserving this to the plugins/extensions using those frameworks.
But now I've checked the stats of several Python frameworks (including ones I maintain) and it seems like only part of those follow this. Also, I've tried googling for opinions and talked to a pip maintainer and it seems like there's no formal or informal rule for this.
Here's my findings:

| Framework | Has classifier |
| --------- | -------------- |
| [aiohttp] | ✘[^1] |
| [Cheroot] | ✓[^2] |
| [CherryPy] | ✓[^2] |
| [Django] | ✓ |
| [Flask] | ✓ |
| [robotframework] | ✓ |
| [tornado] | ✘ |
| [tox] | ✓ |
| [Twisted] | ✘ |
| [Zope] | ✓ |

With this research, I now think it could be reasonable to merge this PR.

[^1]: I rejected a PR a few months ago.
[^2]: Been there since 8 years ago.

[aiohttp]: https://pypi.org/p/aiohttp
[Cheroot]: https://pypi.org/p/Cheroot
[CherryPy]: https://pypi.org/p/CherryPy
[Django]: https://pypi.org/p/Django
[Flask]: https://pypi.org/p/Flask
[robotframework]: https://pypi.org/p/robotframework
[tornado]: https://pypi.org/p/tornado
[tox]: https://pypi.org/p/tox
[Twisted]: https://pypi.org/p/Twisted
[Zope]: https://pypi.org/p/Zope

**Review by mattclay — COMMENTED** [review]
@moreati What benefit would adding this provide to users? If they're looking for projects related to Ansible, it seems unlikely that they need help finding `ansible-core`, or would in any way find it useful to have it appear in their search results.

**Comment by moreati** [comment]
> What benefit would adding this provide to users?

Having it on `ansible` (what I intended) would speed up adoption/bootstrap by
- helping users discover such a classifier exists, and that such a search is possible
- promoting awareness among developers, and encouraging its use by example.

I agree that having it on `ansible-core` (probably what this patch currently does) is less useful, but perhaps desirable in addition.

**Comment by samccann** [comment]
@moreati : @mattclay  - should this PR be merged or closed? It's not really clear and it's been lingering for some time... Thanks!

**Comment by mattclay** [comment]
@moreati After discussing this with others on the Ansible Core Team, we've decided this isn't something we want to add. We don't see any value in having this classifier on `ansible-core`, and we don't want to encourage anyone to package Ansible collections as Python packages.

**Pull request closed without merging**
