### PR TITLE
Reinstate code of conduct to the community TOC; add links to code of …

### PR DESCRIPTION
**Pull request by dharmabumstead**
…conduct to a few conspicuous spots in the community guide.

##### SUMMARY

Fixes issue #38057.

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by gregdek — APPROVED** [review]
I heartily approve of all changes. Thanks @dharmabumstead!

**Comment by abadger** [comment]
We want to cherry-pick this to stable-2.5 for the 2.5.2 release.

**Comment by dharmabumstead** [comment]
This is currently live in the devel docs; is in the queue to be backported to stable-2.5 tomorrow.

**Comment by abadger** [comment]
cherry-picked to stable-2.5

**Pull request merged**
