### PR TITLE
copy: ensure _original_basename is set: fixes #47050

### LINKED ISSUE #47050: Copy module fails to create destination directory with remote_src as per documentation
##### SUMMARY
The documentation for `copy` states that if `dest` ends with a `/`, it will be created if doesn't exist yet. It's not the case though if `remote_src` is set to `yes`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
(no changes)

##### OS / ENVIRONMENT
Linux box 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
**This works:**
```yaml
- copy:
      src: "/etc/skel/.profile"
      dest: '/etc/skel-new/'
      directory_mode: 0755
```

**This doesn't:**
```yaml
- copy:
      src: "/etc/skel/.profile"
      remote_src: yes
      dest: '/etc/skel-new/'
      directory_mode: 0755
```
```
fatal: [10.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "Destination directory /etc/skel-new does not exist"}
```

##### EXPECTED RESULTS
The behaviour is the same with or without `remote_src`, or the difference is at least documented.

### PR DESCRIPTION
**Pull request by memo42**
##### SUMMARY

It seems that the _original_basename is not set in this case and therefore the folder is not created when it should be. Therefore only using _original_basename where it is needed when it is set solves this issue.

Fixes #47050
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

copy
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (47050 abdf7762bc) last updated 2018/10/17 21:41:06 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible/lib/ansible
  executable location = /tmp/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION

```paste below
before:
TASK [copy] ******************************************************************************************************************************************
fatal: [vagrant]: FAILED! => {"changed": false, "msg": "Destination directory /etc/skel-new does not exist"}
	to retry, use: --limit @/home/mo/hska_ansible/deploy_aaa.retry

after:
TASK [copy] ******************************************************************************************************************************************
changed: [vagrant]

```

### CODE REVIEW

**Comment by jborean93** [comment]
It would be great if you could add a test case for this scenario. The copy module is quite complex and having a test case run on every change would make sure that this scenario never reverts back to the failure state.

**Review by abadger — COMMENTED** [review]
Move the comment to the appropriate level as well, please.

**Comment by abadger** [comment]
With a test and a change log entry this looks good to me.  We'll want to backport it to 2.7.

You can look at https://github.com/ansible/ansible/tree/devel/changelogs/fragments for examples of how to construct a changelog

**Comment by gundalow** [comment]
@memo42 Would you be able to add a test and `changelog/fragment/` for this?

**Comment by memo42** [comment]
Thanks for the nudge and sorry for the delay.
I added a test and a changelog fragment. I hope everything is as it should be.

**Comment by memo42** [comment]
@abadger @gundalow does that test work for you? Do you need anything else to be able to merge this?

**Review by jamescassell — APPROVED** [review]
shipit

**Comment by njvrzm** [comment]
Just ran into this bug today. Any chance the fix will be merged soon?

**Comment by abadger** [comment]
rebuild_merge

**Pull request merged**
