### PR TITLE
Corrected Null Object and JSON Serialization Errors

### PR DESCRIPTION
**Pull request by johnny-b-goode**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible/contrib/inventory/azure_rm.py

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
The following changes were made to make the dynamic inventory script for Microsoft Azure more robust.

I was encountering the following error:
ansible-error-01s

I believe this is the issue described in #17727 as well.

I found this problem to be the result of Azure returning virtual machines that did not have an os_profile defined. I added checks for various objects and refactored the code slightly to correct this error and prevent further issues of this type.

I then began receiving a new error:
ansible-error-03s

I found this problem to be due to the [azure.mgmt.compute.models.ProtocolTypes](https://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.compute.models.html#azure.mgmt.compute.models.ProtocolTypes) being an Enum, and the json.dumps method not being able to serialize it. I implemented a very generic [Encoder](https://docs.python.org/2/library/json.html#encoders-and-decoders) to provide generic serialization of Enums.

Note that this probably will not de-serialize well, if at all, but I feel that any attempt to standardize serialization and de-serialization should be left to the maintainers. In the event such a standard is agreed upon, the implementation can easily be removed or corrected.

### CODE REVIEW

**Comment by abadger** [comment]
these changes make the script incompatible with python2 (enum is first present in python-3.4).  (The ternary makes it incompatible with python-2.6... but we need to find out what the enum story is before knowing if that will be a problem as well).  @nitzmahone do you know if this API only works with python-3.4+?  Or do we need to do something else here?

**Comment by johnny-b-goode** [comment]
The Azure SDK uses an enum (see link to azure.mgmt.compute.models.ProtocolTypes in initial PR), but according to https://azure-sdk-for-python.readthedocs.io/en/latest/index.html the Azure SDK supports Python versions 2.7.x, 3.3.x, 3.4.x, 3.5.x and 3.6.x.

According to https://azure-sdk-for-python.readthedocs.io/en/latest/installation.html the azure-mgmt-compute package is in preview, so perhaps the use of enum within the Azure SDK is a mistake?

**Comment by paprickar** [comment]
@johnny-b-goode  When i use the the azure_rm.py with your changes i get following error:
`
Exception: One-time registration of Microsoft.Compute failed - Azure Error: AuthorizationFailed
Message: The client '%CLIENT_ID%' with object id '%OBJECT_ID%' does not have authorization to perform action 'Microsoft.Compute/register/action' over scope '/subscriptions/%SUBSCRIPTON_ID%
`

Do you got any idea how to solve it?

FYI:
If i am Contributor or Owner for a subscription it seems to work

**Comment by johnny-b-goode** [comment]
@paprickar I have seen similar problems before and they were related to the permissions for the user account being used by the script. That it works when using an account with Contributor or Owner permissions seems to confirm this.

**Comment by paprickar** [comment]
But with the "original" azure_rm.py READ permissions seems to be enough so i guess it must be related to your commit (it seems you use the Azure API in a way which need more permissions?)

**Comment by johnny-b-goode** [comment]
@paprickar The way in which the API is used did not change with this commit, however, this PR is several months old so if you started with a newer version of Ansible there may be some differences.

**Comment by jborean93** [comment]
Hi, this PR is quite old and requires a rebase for it to continue. As we cannot replicate the issue in the latest iteration of the script I am going to close the PR. If you believe this is in error please re-open the script and let us know how we can reproduce it.

**Pull request closed without merging**
