### PR TITLE
distribution: Add Amazon Linux distribution facts

### LINKED ISSUE #73742: The ansible_distribution_version fact does not return correct value for Amazon Linux
ansible 2.7 -> "ansible_distribution_version": "2018.03"
ansible 2.8 and above -> "ansible_distribution_version": "N/A"

**ISSUE TYPE**
 Bug Report

**COMPONENT NAME**
facts , https://github.com/nir0s/distro

**ANSIBLE VERSION**
devel

**CONFIGURATION**
N/A

**OS / ENVIRONMENT**
Amazon
 
**STEPS TO REPRODUCE**
ansible localhost -m setup | grep ansible_distribution_version

**Expected results**
"ansible_distribution_version": "2018.03"

**Actual results** 
 "ansible_distribution_version": "NA"

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

* Update Amazon Linux Distribution facts gathering logic
* Update tests

Fixes: #73742

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/73742_amazon_distribution.yml
lib/ansible/module_utils/facts/system/distribution.py
test/units/module_utils/facts/system/distribution/fixtures/amazon_linux_2.json
test/units/module_utils/facts/system/distribution/fixtures/amazon_linux_2016.03.json
test/units/module_utils/facts/system/distribution/fixtures/amazon_linux_2018.03.json
test/units/module_utils/facts/system/distribution/fixtures/amazon_linux_2_karoo.json

### CODE REVIEW

**Comment by bcoca** [comment]
have we checked that for previous amazon linux versions a os-release file won't contradict the old pathway?

**Comment by Akasurde** [comment]
> have we checked that for previous amazon linux versions a os-release file won't contradict the old pathway?

Yes, Older version like Amazon Linux 2 and 2 (Karoo) is tested with this change and works fine. I also added tests for these distro.

**Comment by kbrahmbh** [comment]
Is it possible backport the fix to ansible-2.8 and further?

**Comment by Akasurde** [comment]
Ansible 2.8 is for critical security fixes. We can backport to 2.9 and 2.10. Please see https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html

**Comment by kbrahmbh** [comment]
Thank you Abhijeet for your help. Yes, please lets back port it to 2.9 and 2.10 if not already done. I can upgrade my ansible to 2.9 and above. Thanks again for your help.

**Comment by Akasurde** [comment]
Backport 2.9 - https://github.com/ansible/ansible/pull/73846
Backport 2.10 - https://github.com/ansible/ansible/pull/73845

**Pull request merged**
