### PR TITLE
modules/postgresql_users: Adds user connection limit option to the mo…

### PR DESCRIPTION
**Pull request by drrtuy**
##### SUMMARY
Added user connection limit feature to the module. The feature was [requested](https://github.com/ansible/ansible-modules-core/issues/1570) long ago and had been forgoten while merging modules repo with the main repo. 
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
postgresql_user
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel cd2581705e) last updated 2017/04/30 12:04:23 (GMT +300)
  config file = 
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

### CODE REVIEW

**Comment by nerzhul** [comment]
Nice addition, can you review the build ?

**Comment by drrtuy** [comment]
What is the status of the PR?

**Comment by matburt** [comment]
shipit

**Comment by nerzhul** [comment]
conflict, please rebase

**Pull request closed without merging**
