### PR TITLE
fixes for handling of different return codes from robocopy in win_robocopy module

### LINKED ISSUE #19959: win_robocopy throw a exception when return_code is not 1||2||4
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_robocopy module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/tessa/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

when win_robocopy return_code is not 1||2||4 ,$change is not been set. it will throw a exception on the code below:

```
Set-Attr $result.win_robocopy "changed" $changed
```

##### STEPS TO REPRODUCE

```yaml
  - win_robocopy:
      src: D:\\tmp\\temp\\TMP.ClientAgent\\0.0.0.1\\Software\\Service\\
      dest: D:\\tmp\\deploy\\services\\TMP.ClientAgent\\0.0.0.1\\
      recurse: true
      purge: true
```

and content in src and dest are the same . win_robocopy.return_code will be 0.

##### EXPECTED RESULTS

```
ok: [10.0.200.141] => {"changed": false, "msg": "No files copied."}
```

##### ACTUAL RESULTS
```
fatal: [10.0.200.141]: FAILED! => {"changed": false, "failed": true, "msg": "The variable '$changed' cannot be retrieved because it has not been set."}
```

### PR DESCRIPTION
**Pull request by pwae**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_robocopy

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel cba66dfedc) last updated 2017/01/07 07:15:12 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
Original fix was at ansible/ansible-modules-extras#3515 by @twistyWater
This is a copy of that.
it handles any additional return codes per the documentation at http://ss64.com/nt/robocopy-exit.html

Fixes #19959 - win_robocopy throw a exception when return_code is not 1||2||4

Before:
```
fatal: [i-0b1e67779f91f8xxx]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "win_robocopy"
    },
    "msg": "The variable '$changed' cannot be retrieved because it has not been set."
}
```

After:
```
ok: [i-0b1e67779f91f8xxx] => {
    "changed": false,
    "invocation": {
        "module_name": "win_robocopy"
    },
    "win_robocopy": {
        "changed": true,
        "dest": "C:\\Windows\\system32\\WBEM\\Framework\\root\\",
        "flags": null,
        "msg": "Some Extra files or directories were detected. No files were copied.",
        "output": [
            "",
            "-------------------------------------------------------------------------------",
            "   ROBOCOPY     ::     Robust File Copy for Windows                              ",
            "-------------------------------------------------------------------------------",
            "",
            "  Started : Saturday, January 7, 2017 12:35:22 AM",
            "   Source : \\\\10.x.x.x\\Misc\\EnterpriseLibrary\\",
            "     Dest : C:\\Windows\\system32\\WBEM\\Framework\\root\\",
            "",
            "    Files : *.*",
            "\t    ",
            "  Options : *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30 ",
            "",
            "------------------------------------------------------------------------------",
            "",
            "\t                   8\t\\\\10.x.x.x\\Misc\\EnterpriseLibrary\\",
            "\t*EXTRA Dir        -1\tC:\\Windows\\system32\\WBEM\\Framework\\root\\Amazon\\",
            "",
            "------------------------------------------------------------------------------",
            "",
            "               Total    Copied   Skipped  Mismatch    FAILED    Extras",
            "    Dirs :         1         0         0         0         0         1",
            "   Files :         8         0         8         0         0         0",
            "   Bytes :   253.2 k         0   253.2 k         0         0         0",
            "   Times :   0:00:00   0:00:00                       0:00:00   0:00:00",
            "   Ended : Saturday, January 7, 2017 12:35:22 AM",
            ""
        ],
        "purge": false,
        "recurse": true,
        "return_code": 2,
        "src": "\\\\10.x.x.x\\Misc\\EnterpriseLibrary"
    }
}
```

### CODE REVIEW

**Comment by blakfeld** [comment]
ship_it shipit

**Comment by twistyWater** [comment]
Can someone clarify why my PR was not merge and we had to copy it here?

**Comment by blakfeld** [comment]
I'm not entirely sure. I was under the impression that PRs from the old modules repos were supposed to get migrated over, but that doesn't appear to be the case?

**Comment by jhawkesworth** [comment]
It is up to contributors to move their pull requests.  I believe it wasn't possible to automatically move pull requests and retain original ownership of the contributions.

**Comment by bcoca** [comment]
@pwae it is preferable to keep attribution of the original author, you can create a branch and add his commit and then add your subsequent changes as another commit.

**Comment by pwae** [comment]
@twistyWater no idea. it was lost, and i simply moved it here as i also needed the fix - might be best if you re-apply your PR to here?
otherwise i will pick this up in the next day or so.

**Comment by twistyWater** [comment]
It's ok with me, I won't move the PR

**Pull request merged**
