### PR TITLE
Use different hostname strategy for RHEL >= 7. Fixes 7763

### PR DESCRIPTION
**Pull request by rmarchei**
fixes issue #7763

### CODE REVIEW

**Comment by jimi-c** [comment]
Why have you duplicated the `get_distribution()` into this module? That should be removed and the one from module_utils used instead.

**Comment by rmarchei** [comment]
It is `get_distribution_version()`, similar to `get_distribution()` (that's why I copied part of the code) but it returns the version of the OS (like 6.5, 7, etc)

**Comment by jimi-c** [comment]
I see, however that should still be in `module_utils/basic.py` and not in the module itself.

**Comment by rmarchei** [comment]
perfect! I'm changing it right now

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
