### PR TITLE
Add support for using IP addresses in target groups

### PR DESCRIPTION
**Pull request by wimnat**
##### SUMMARY
Add support for using IP addresses in target groups. (functionality added by Network LBs)

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
elb_target_group

##### ANSIBLE VERSION
```
2.5
```

##### ADDITIONAL INFORMATION
@s-hertel @willthames

### CODE REVIEW

**Comment by richardj-bsquare** [comment]
This is pretty much a dupe of my pull request https://github.com/ansible/ansible/pull/30965

**Comment by willthames** [comment]
@richardj-bsquare there is definitely a large overlap. The docs for this PR are a little more thorough, and it takes the new parameter into account as something that can't be modified.

One compromise might be to merge #30965 first and then rebase this PR on that.

**Comment by wimnat** [comment]
@richardj-bsquare why don't you just cherry pick my commit on to your branch and I'll close this

**Comment by ryansb** [comment]
This merges the fix originally provided by wimnat as well as @richardj-bsquare's PR #30965

**Pull request merged**
