### PR TITLE
Fix #13860 by setting rc variable properly when using remote fish shell

### LINKED ISSUE #13860: 2.0 - Unarchive results in dest must be an existing dir with fish shell
Problem occurs after upgrading to 2.0.0. Running on Ubuntu 14.04.3 LTS. Running with `ansible_shell_type=fish` as both remote as local machine use fish shell.

```
- name: deploy the meteor project
  become: no
  unarchive: src=local/meteor-streamline-tunnel.tar.gz dest={{ meteor_streamline_tunnel_home }}
  notify: restart meteor-streamline-tunnel
```

```
fatal: [vps]: FAILED! => {"changed": false, "failed": true, "msg": "dest '/home/ksmets/apps/meteor-streamline-tunnel' must be an existing dir"}
```

The directory exists, and has the right ownership and permissions. Task runs fine using 1.9.4.

Verbose log:

```
<vps.ksmets.be> ESTABLISH SSH CONNECTION FOR USER: None
<vps.ksmets.be> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ksmets/.ansible/cp/ansible-ssh-%h-%p-%r -tt vps.ksmets.be ' umask 22 ; and mkdir -p ( echo $HOME/.ansible/tmp/ansible-tmp-1452716498.04-22763226015839 ) ; and echo ( echo $HOME/.ansible/tmp/ansible-tmp-1452716498.04-22763226015839 ) '
<vps.ksmets.be> ESTABLISH SSH CONNECTION FOR USER: None
<vps.ksmets.be> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ksmets/.ansible/cp/ansible-ssh-%h-%p-%r -tt vps.ksmets.be 'rc=flag; [ -r /home/ksmets/apps/meteor-streamline-tunnel ] ; or rc=2; [ -f /home/ksmets/apps/meteor-streamline-tunnel ] ; or rc=1; [ -d /home/ksmets/apps/meteor-streamline-tunnel ] ; and rc=3; python -V 2>/dev/null ; or rc=4; [ x"$rc" != "xflag" ] ; and echo "${rc}  "/home/ksmets/apps/meteor-streamline-tunnel ; and exit 0; (python -c '"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'/home/ksmets/apps/meteor-streamline-tunnel'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"' 2>/dev/null) ; or (python -c '"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'"'"'/home/ksmets/apps/meteor-streamline-tunnel'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"' 2>/dev/null) ; or (echo '"'"'0  '"'"'/home/ksmets/apps/meteor-streamline-tunnel)'
fatal: [vps]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/home/ksmets/apps/meteor-streamline-tunnel", "src": "local/meteor-streamline-tunnel.tar.gz"}, "module_name": "unarchive"}, "msg": "dest '/home/ksmets/apps/meteor-streamline-tunnel' must be an existing dir"}
```

### PR DESCRIPTION
**Pull request by ksmets**
Set the rc variable properly when using remote fish shell. This fixes issue #13860.

### CODE REVIEW

**Comment by bcoca** [comment]
using #14006 to avoid the issue, but might still merge this for those that only have fish available and not /bin/sh (yes, we have had cases)

**Comment by ksmets** [comment]
This pull request does't work with `become` as this always executes as command in /bin/sh environment. Your fix solves  #13860 and #13490, when I don't specify ansible_shell_type=fish.

**Comment by bcoca** [comment]
merged the issue, but still keeping this as we need to work also when fish is the only shell

**Comment by bcoca** [comment]
FYI, become should use the 'executable' setting, which can be set to fish also

**Comment by bcoca** [comment]
@ksmets  I ended up taking this a bit farther and making the checksum changes in #14319, let me know if that works for you

**Comment by ksmets** [comment]
Hi,

I tried your pull request with setting `executable=/usr/bin/fish` in `ansible.cfg` and `ansible_shell_type=fish` in inventory file, but even `ansible -m setup all` results in

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ksmets/.virtualenvs/ansible-fix/local/lib/python2.7/site-packages/ansible-2.1.0-py2.7.egg/ansible/executor/process/worker.py", line 115, in run
    self._shared_loader_obj,
  File "/home/ksmets/.virtualenvs/ansible-fix/local/lib/python2.7/site-packages/ansible-2.1.0-py2.7.egg/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/ksmets/.virtualenvs/ansible-fix/local/lib/python2.7/site-packages/ansible-2.1.0-py2.7.egg/ansible/executor/task_executor.py", line 421, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/ksmets/.virtualenvs/ansible-fix/local/lib/python2.7/site-packages/ansible-2.1.0-py2.7.egg/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/home/ksmets/.virtualenvs/ansible-fix/local/lib/python2.7/site-packages/ansible-2.1.0-py2.7.egg/ansible/plugins/action/__init__.py", line 433, in _execute_module
    environment_string = self._compute_environment_string()
  File "/home/ksmets/.virtualenvs/ansible-fix/local/lib/python2.7/site-packages/ansible-2.1.0-py2.7.egg/ansible/plugins/action/__init__.py", line 170, in _compute_environment_string
    return self._connection._shell.env_prefix(**final_environment)
  File "/home/ksmets/.virtualenvs/ansible-fix/local/lib/python2.7/site-packages/ansible-2.1.0-py2.7.egg/ansible/plugins/shell/fish.py", line 43, in env_prefix
    return ' '.join(['set -lx %s %s;' % (k, pipes.quotes(text_type(v))) for k,v in env.items()])
AttributeError: 'module' object has no attribute 'quotes'

fatal: [vps]: FAILED! => {"failed": true, "stdout": ""}
```

**Comment by abadger** [comment]
Needs to be `pipes.quote` rather than `pipes.quotes`.

**Comment by ksmets** [comment]
When using pipes.quote it works perfectly.

**Comment by bcoca** [comment]
fixed PR

**Comment by bcoca** [comment]
bad rebase, needs good one

**Comment by ksmets** [comment]
@bcoca how do I rebase properly?

**Comment by mattclay** [comment]
@ksmets Rebasing instructions here: https://docs.ansible.com/ansible/dev_guide/developing_rebasing.html

**Comment by mckerrj** [comment]
Closed for lack of activity

**Pull request closed without merging**
