### PR TITLE
Fixed idempotency issues within zabbix_template module

### LINKED ISSUE #48337: zabbix_template: result is always 'changed'
##### SUMMARY
Result is always 'changed' when imported same template.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_template.py

##### ANSIBLE VERSION
2.6.4

##### OS / ENVIRONMENT
Ubuntu 18.04.1 LTS

##### STEPS TO REPRODUCE

```yaml
- name: test zabbix_template
  local_action:
    module: zabbix_template
    server_url: "{{ zabbix.server.url }}"
    login_user:     "{{ zabbix.server.login.user }}"
    login_password: "{{ zabbix.server.login.pass }}"
    state: present
    template_name: Template TEST Web
    template_groups: Templates
    template_json:
      zabbix_export:
        templates:
        - templates: []
          description: 'TEST'
          template: Template TEST Web
          groups:
          - name: Templates
          name: "[Custom Template] TEST Web"
        version: '3.0'
        groups:
        - name: Templates
```

##### EXPECTED RESULTS
```
TASK [test zabbix_template] ********************************************
ok: [test]
```

##### ACTUAL RESULTS

```paste below
TASK [test zabbix_template] ********************************************
changed: [test]
```

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
Module zabbix_template didn't properly implement idempotency checks. Fixes #48337. 

Result always ended up being `changed=True` when user used `link_templates`, `macros` or `template_json` options.

This patch requires #45229 to be merged to be able to fix idempotency for cases when there are linked templates defined in `template_json` itself (see "Create template 00_temp2 new" in my example below).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_template.py

##### ADDITIONAL INFORMATION

Possible to test with something like this:
* Example inventory  ([full test stack setup](https://github.com/D3DeFi/zbx-ansible-dev))
```ini
zbx-dev-node001 zbx_version=2.2
zbx-dev-node002 zbx_version=3.0
zbx-dev-node003 zbx_version=4.0
```
* Example playbook
```yaml
- hosts: all
  vars:
   # These values are just examples, use your own
    zbx_server_url: 'https://{{ ansible_host }}'
    zbx_user: 'Admin'
    zbx_password: 'zabbix'

    zbx_icmp_template:
      2.2: 'Template ICMP Ping'
      3.0: 'Template ICMP Ping'
      4.0: 'Template Module ICMP Ping'

  tasks:
    - block:
        - name: Create template 00_temp1 new
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: False
            template_name: 00_temp1
            template_groups: Templates
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp1 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: False
            template_name: 00_temp1
            template_groups: Templates
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Create template 00_temp2 new
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: False
            template_name: 00_temp2
            template_groups: Templates
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp2
                    name: 00_temp2
                    templates:
                      - name: '{{ zbx_icmp_template[zbx_version] }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '1234'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '2.0'
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp2 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: False
            template_name: 00_temp2
            template_groups: Templates
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp2
                    name: 00_temp2
                    templates:
                      - name: '{{ zbx_icmp_template[zbx_version] }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '1234'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '2.0'
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Create template 00_temp2 changed
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: False
            template_name: 00_temp2
            template_groups: Templates
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp2
                    name: 00_temp2
                    templates:
                      - name: '{{ zbx_icmp_template[zbx_version] }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '12345'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '2.0'
          register: res

        - assert:
            that:
              - "res.changed == True"

      delegate_to: localhost
```

Verified, that this fix works with all LTS zabbix-server releases (2.2, 3.0 and 4.0)

### CODE REVIEW

**Comment by resmo** [comment]
Looks good to me, could you add a changelog fragment? Ping me if you need more infos how to do that.

**Comment by D3DeFi** [comment]
@resmo thank you very much for all of your help, I've went ahead and added changelog fragment for my other PR as well, hope it is not a problem to have it in this PR tho (I will make sure my future PRs will all have changelogs) 

This PR should be ok to merge now

**Comment by D3DeFi** [comment]
squashed commits, should be ready to go

**Review by resmo — APPROVED** [review]
LGTM

**Comment by D3DeFi** [comment]
shipit

**Pull request merged**
