### PR TITLE
ec2_group: add integration test for port ranges

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Failing shippable because the fix is in #27145. This is a follow-up tests pull request.

The rules option 'ports' should work with ranges and ports provided as strings since bd05c65. It was broken, so I've ~fixed it and~ added a test. Edit: #27145 is a better fix, since from_ports and to_ports provided as strings is also fixed.

Traceback before:
```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/by/k8_fbl593dlctgqmwq5wzl2c0000gn/T/ansible_k319ukpf/ansible_module_ec2_group.py", line 763, in <module>
    main()
  File "/var/folders/by/k8_fbl593dlctgqmwq5wzl2c0000gn/T/ansible_k319ukpf/ansible_module_ec2_group.py", line 644, in main
    module, rule, "ipv4")
  File "/var/folders/by/k8_fbl593dlctgqmwq5wzl2c0000gn/T/ansible_k319ukpf/ansible_module_ec2_group.py", line 417, in authorize_ip
    IpPermissions=[ip_permission])
  File "/Users/shertel/Workspace/ansible/venv/python3.5.2/lib/python3.5/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/shertel/Workspace/ansible/venv/python3.5.2/lib/python3.5/site-packages/botocore/client.py", line 573, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/shertel/Workspace/ansible/venv/python3.5.2/lib/python3.5/site-packages/botocore/client.py", line 628, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/shertel/Workspace/ansible/venv/python3.5.2/lib/python3.5/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter IpPermissions[0].FromPort, value: 10, type: <class 'str'>, valid types: <class 'int'>
Invalid type for parameter IpPermissions[0].ToPort, value: 10, type: <class 'str'>, valid types: <class 'int'>
```

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ec2_group.py
test/integration/targets/ec2_group/tasks/main.yml

##### ANSIBLE VERSION
```
2.4.0
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests:

```
Traceback (most recent call last):
  File "/tmp/ansible_qSO6u8/ansible_module_ec2_group.py", line 763, in <module>
    main()
  File "/tmp/ansible_qSO6u8/ansible_module_ec2_group.py", line 644, in main
    module, rule, "ipv4")
  File "/tmp/ansible_qSO6u8/ansible_module_ec2_group.py", line 417, in authorize_ip
    IpPermissions=[ip_permission])
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 573, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 628, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter IpPermissions[0].ToPort, value: 8192, type: <type 'str'>, valid types: <type 'int'>, <type 'long'>
Invalid type for parameter IpPermissions[0].FromPort, value: 8192, type: <type 'str'>, valid types: <type 'int'>, <type 'long'>
```

**Comment by s-hertel** [comment]
This will pass shippable once #27145 is merged. Not going to rebase on top of it because it is also rebasing on top of another PR. Will rebase once both of those are merged.

**Comment by willthames** [comment]
Closing and reopening to rerun tests

**Comment by willthames** [comment]
Rebased, will wait for tests.

**Comment by willthames** [comment]
More tests merged, yay!

**Pull request merged**
