### PR TITLE
systemd - account for templated unit files when searching for service

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Related to issue #71528 and PR #72337

Very good find by @mpolden (https://github.com/ansible/ansible/pull/72347#issuecomment-730626228).

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/systemd.py`

### CODE REVIEW

**Comment by hferreira23** [comment]
@samdoran, I'm running Ansible 2.9.16rc and this still seems to be an issue.

I have a template service called docker_compose@.service. 

The following playbook fails if the target is an Ubuntu 20.04 fully updated (for some reason it works well on Debian Buster stable)

`---
- name: test restart
  hosts: <target_host>
  become: true
  gather_facts: false
  tasks:
    - name: systemd docker compose base
      systemd:
        name: "docker-compose@base"
        state: restarted
        enabled: yes
        daemon_reload: yes`

Error:

`fatal: [<target_host>]: FAILED! => {"changed": false, "msg": "Unable to enable service docker-compose: Failed to enable unit: Unit file docker-compose.service does not exist.\n"}`

Happy to open a separate issue if you want.

**Comment by samdoran** [comment]
@hferreira23 What is the output of `systemctl show docker-compose@base`? I think I see the bug but just want to verify.

**Comment by hferreira23** [comment]
@samdoran check below.

```
Type=simple
Restart=always
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=15min
TimeoutStopUSec=15min
TimeoutAbortUSec=15min
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestampMonotonic=0
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=1733383
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=success
ReloadResult=success
CleanResult=success
UID=[not set]
GID=[not set]
NRestarts=0
OOMPolicy=stop
ExecMainStartTimestamp=Fri 2020-12-11 01:01:58 WET
ExecMainStartTimestampMonotonic=610366824545
ExecMainExitTimestampMonotonic=0
ExecMainPID=1733383
ExecMainCode=0
ExecMainStatus=0
ExecStartPre={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose down -v ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPre={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose rm -fv ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPre={ path=/bin/bash ; argv[]=/bin/bash -c docker volume ls -qf "name=base_" | xargs docker volume rm ; ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPre={ path=/bin/bash ; argv[]=/bin/bash -c docker ps -aqf "name=base_*" | xargs docker rm ; ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPre={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose pull ; ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPreEx={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose down -v ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPreEx={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose rm -fv ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPreEx={ path=/bin/bash ; argv[]=/bin/bash -c docker volume ls -qf "name=base_" | xargs docker volume rm ; flags=ignore-failure ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPreEx={ path=/bin/bash ; argv[]=/bin/bash -c docker ps -aqf "name=base_*" | xargs docker rm ; flags=ignore-failure ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPreEx={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose pull ; flags=ignore-failure ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStart={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose up ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartEx={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose up ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStop={ path=/usr/bin/docker ; argv[]=/usr/bin/docker image prune -f ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStop={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose down -v ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStopEx={ path=/usr/bin/docker ; argv[]=/usr/bin/docker image prune -f ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStopEx={ path=/usr/local/bin/docker-compose ; argv[]=/usr/local/bin/docker-compose down -v ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system-docker\x2dcompose.slice
ControlGroup=/system.slice/system-docker\x2dcompose.slice/docker-compose@base.service
MemoryCurrent=13557760
CPUUsageNSec=[not set]
EffectiveCPUs=
EffectiveMemoryNodes=
TasksCurrent=5
IPIngressBytes=[no data]
IPIngressPackets=[no data]
IPEgressBytes=[no data]
IPEgressPackets=[no data]
IOReadBytes=18446744073709551615
IOReadOperations=18446744073709551615
IOWriteBytes=18446744073709551615
IOWriteOperations=18446744073709551615
Delegate=no
CPFailed to parse bus message: Invalid argument
UAccounting=no
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
CPUQuotaPeriodUSec=infinity
```

**Comment by samdoran** [comment]
@hferreira23 Thanks for confirming. I will open a PR.

**Pull request merged**
