### PR TITLE
Add missing openstack modules to BOTMETA

### PR DESCRIPTION
**Pull request by emonty**
These got missed in the earlier migration.

### CODE REVIEW

**Comment by mattclay** [comment]
@emonty Is there a PR to remove these modules from https://github.com/ansible-collections/community.general/?

**Comment by emonty** [comment]
@mattclay https://github.com/ansible-collections/community.general/pull/15

**Comment by sshnaidm** [comment]
@emonty I think *_facts module were deprecated and renamed to *_info ones? Why do we need them in BOTMETA? @gundalow can you comment, please?

**Comment by felixfontein** [comment]
I guess they are needed if someone is still using the `_facts` names in their playbooks.

**Comment by sshnaidm** [comment]
I thought BOTMETA is just for docs, so we don't need old module names there. Would be happy if someone clarifies or confirms that.

**Comment by gundalow** [comment]
What ever modules were in ansible/ansible:devel before the cut must be in `botmeta.yml` & `routing.yml

**Comment by emonty** [comment]
Let's hold on this one for another bit - we're going to do a few more renames openstack-side and then I'll update this one.

**Comment by sivel** [comment]
Hello!

This pull request was submitted against the `temp-2.10-devel` base branch.  That branch has been protected, and development has been moved back to the `devel` branch.

To update this pull request, you will need to follow these steps:

1. Rebase your branch against the `devel` branch of `ansible/ansible`
1. Force push to your git remote
1. Change the target branch by using the `Edit` button for the pull request title, and select `devel` from the `base` dropdown.
1. Close and then re-open the pull request so that CI will re-run against the new base branch.

needs_info

**Comment by mattclay** [comment]
@emonty Feel free to re-open this (or a new PR) after rebasing and redirecting to devel.

**Pull request closed without merging**
