### PR TITLE
Use explicit keyword for plugin config

### PR DESCRIPTION
**Pull request by bcoca**
Still falls back to automap, but that should be deprecated and removed in the future.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

config

### CODE REVIEW

**Comment by bcoca** [comment]
cc @acozine this adds the previously specced, but unused 'keyword' to plugin docs

**Comment by felixfontein** [comment]
antsibull-docs part: https://github.com/ansible-community/antsibull/pull/329

**Review by sivel — APPROVED** [review]
This should get a changelog.  Other than that, I think we can proceed with merging.

**Pull request merged**
