### PR TITLE
Deprecating old cumulus modules

### PR DESCRIPTION
**Pull request by isharacomix**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
`modules/network/cumulus/cl_*`

##### SUMMARY

Deprecating legacy `cl_*` modules in favor of the new `nclu` module.

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
Can you please update `CHANGELOG.md` to add these modules into the deprecated list. Other than that, it looks good.

**Comment by isharacomix** [comment]
Changelog updated. Will Ansible actually take care of the removal in 2.5 or will we need to do the PR ourselves when the time comes?

**Comment by gundalow** [comment]
That's a good question. We *should* review the CHANGELOG.md and spot it, though that's a manual process.

**Comment by gundalow** [comment]
I'm just checking if anything else needs to be done, I'll document the process.

**Comment by gundalow** [comment]
You need to rename the files as well so they start with an `_`, e.g:
`git mv cl_bond.py _cl_bond.py

**Review by gundalow — CHANGES_REQUESTED** [review]
Rename files to start with `_`

**Comment by gundalow** [comment]
http://docs.ansible.com/ansible/dev_guide/developing_modules_checklist.html#deprecating-and-making-module-aliases

**Comment by isharacomix** [comment]
I renamed them, and shippable is yelling at me about the version in which they were added. I'm also getting some documentation complaints that I didn't get before (maybe the documentation rules changed?)

Can you help me interpret the output and decide how to proceed? I don't mind redoing the docstrings if that's what the issue is.

```2017-02-24 19:30:30 ============================================================================
2017-02-24 19:30:30 lib/ansible/modules/network/cumulus/_cl_license.py
2017-02-24 19:30:30 ============================================================================
2017-02-24 19:30:30 ERROR:307:version_added should be 2.3. Currently 2.1
2017-02-24 19:30:30 ERROR:208:module_utils imports should import specific components, not "*". line 145
2017-02-24 19:30:30 ERROR:107:Imports should be directly below DOCUMENTATION/EXAMPLES/RETURN/ANSIBLE_METADATA. line 145
2017-02-24 19:30:30 ```

**Comment by mattclay** [comment]
@isharacomix It's a problem with the module validator. We're working on a fix.

**Comment by mattclay** [comment]
@isharacomix CI is now passing.

**Review by gundalow — APPROVED** [review]

**Pull request merged**
