### PR TITLE
fix legacy PEP8 violations in zabbix_*, remove test exception for them

### PR DESCRIPTION
**Pull request by eikef**
##### SUMMARY
This PR fixes PEP8 errors in the zabbix_*-module-namespace and removes the test exceptions for them. This has come up in a previous PR (#25969) as a hindrance for PRs (since if code is touched which "inadvertently" fixes PEP8 errors, the test suite will fail because the exception is no longer necessary).

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
zabbix_*

##### ANSIBLE VERSION
2.5.0

### CODE REVIEW

**Comment by resmo** [comment]
shipit

**Comment by eikef** [comment]
shipit

**Comment by resmo** [comment]
shipit

**Review by D3DeFi — APPROVED** [review]

**Comment by D3DeFi** [comment]
shipit

**Pull request merged**
