### PR TITLE
fix seport default mismatch

### LINKED ISSUE #28653: seport: Mismatch in default value of attribute state between code and docs
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

seport

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/ansible/roles/mariadb/tests/cluster/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]
```

##### SUMMARY

The [docu of module seport](http://docs.ansible.com/ansible/latest/seport_module.html) describes that the default value of attribute state is __default__. This default is not used within the code which results in an error if the attribute is omited.

##### STEPS TO REPRODUCE

```ini
[mysql]
mysql.example.com
```

```yaml
---
- hosts: mysql
  tasks:
  - name: Ensure SELinux port
      seport:
        ports: 4567
        proto: tcp
        setype: mysqld_port_t
```

##### EXPECTED RESULTS

Tasks runs without an error

##### ACTUAL RESULTS

```shell
failed: [mysql.example.com] (item={u'setype': u'mysqld_port_t', u'port': 4444, u'proto': u'tcp'}) => {"failed": true, "item": {"port": 4444, "proto": "tcp", "setype": "mysqld_port_t"}, "msg": "missing required arguments: state"}
```

```

```

### PR DESCRIPTION
**Pull request by Nosmoht**
##### SUMMARY

Fixes #28653 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

sport

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/ansible/roles/mariadb/tests/cluster/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by nrwahl2 — CHANGES_REQUESTED** [review]
When setting options in your `argument_spec` and your doc string, you should use only one of `required` or `default`. This makes sense when you think about it because if you're required to specify a value, there will never be a default.

This is specified in the sanity testing documentation: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/testing/sanity/required-and-default-attributes.rst

Also, the default value for `required` is `False`, so it does not need to be specified unless it's `True`.

Finally, make sure you update your documentation string at the top of the module to reflect any changes you make to the `argument_spec` options :)

**Comment by bcoca** [comment]
As @nrwahl2 points out, when an option is required, `default` is redundant. so the fix should really be removing `default` from the docs.

**Comment by nrwahl2** [comment]
@bcoca It seems like `state: 'present'` being the default is the norm for Ansible (e.g., yum module). I'd personally go with this route, but with the `required` parameter removed from the docs and the argument spec.

**Comment by Nosmoht** [comment]
I hope to understood your comments correctly and made changes according to it.

**Review by nrwahl2 — APPROVED** [review]
Looks good to me.

**Comment by bcoca** [comment]
@nrwahl2 actually the norm should be the opposite (yum module is bad example to follow)

**Comment by nrwahl2** [comment]
Noted, thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Review by nrwahl2 — CHANGES_REQUESTED** [review]
Rescinding my approval. See bcoca's notes.

**Comment by Akasurde** [comment]
superseded by #52384

**Comment by Akasurde** [comment]
@Nosmoht Thanks for the contribution.

**Pull request closed without merging**
