### PR TITLE
pfsense_aggregate module

### PR DESCRIPTION
**Pull request by opoplawski**
##### SUMMARY

This is initial work on a pfsense module with various tasks to allow configuring of pfSense boxes.  This is in the very initial stages and we are looking for feedback on the design and implementation.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
pfsense

##### ADDITIONAL INFORMATION

pfsense stores its configuration in an XML config file: /cf/conf/config.xml.  Normally configuration is done via a PHP web interface.  This module manipulates the config.xml file directly, then runs some php commands to get the pfsense code to reload the XML config file and apply any needed changes.

We are also developing this module here: https://github.com/opoplawski/ansible-pfsense

### CODE REVIEW

**Comment by opoplawski** [comment]
I'm using the ipaddress module to validate ip addresses.  Is this okay or should something else be used to validate those?

**Comment by opoplawski** [comment]
I will rework this as a single initial module request, but perhaps a couple of questions could be decided here first (in addition to the ipaddress question above):
- Does this belong in the network module namespace?
- Should the multiple module_utils files be combined into a singe file or is it okay as is?
- Is the approach taken with the pfsense_aggregate module reasonable?  Because aliases and rules are so connected (e.g. changing an alias name will require changing the alias name reference in the rules as well) it seems necessary - but the arguments currently seem unconventional.

**Comment by opoplawski** [comment]
> The test `ansible-test sanity --test pylint` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/pylint.html)] failed with 1 error:
> 
> ```
> test/units/modules/pfsense/pfsense_module.py:33:4: bare-except No exception type(s) specified
> ```

@f-bor This seems to be the last sanity test failure - can you please make a fix for that?

Also, the python 2.6 tests are failing for two reasons:

-     @unittest.expectedFailure -> AttributeError: 'module' object has no attribute 'expectedFailure'

and indeed, no other ansible tests appear to use that.

- TypeError: write() got an unexpected keyword argument 'xml_declaration'

I did find one other use of xml_declaration in ansible - in the xml module.  So I'm not really sure how to address this as it seems ansible is already violating python 2.6 compatibility here.

**Comment by Qalthos** [comment]
This should be moved into `modules/networking/pfsense` instead of `modules/pfsense`

**Comment by opoplawski** [comment]
Okay, we are now down to one (rather large) module - pfsense_aggregate.  But that is the one I'm most interested in feedback on.

**Comment by f-bor** [comment]
@Qalthos In a few words, the idea behind this module is to use other pfsense modules code to push all aliases and rules at once. It also handles purge parameters to delete everything that is not explicitly defined anymore. Since pfsense is not providing a CLI, we can't just push a big configuration file to a device to achieve quite the same job.

We have also started to write a lookup plugin (which is not include in this PR), designed to work with pfsense_aggregate. You have to supply a file describing your network topology and security. The plugin determines and generates accordingly what is required on each firewall. It allows to easily manage a fleet of firewalls sharing same network elements.

**Comment by mattclay** [comment]
bot_status

**Comment by maxamillion** [comment]
Alright, this was discussed in the Security Automation Working Group as well as with the Ansible Community Team. At this time these modules should be allowed in Core and will be moved to the Community Collection (name pending) later in the migration process.

I'm good with it, LGTM. +1 for tests

shipit

**Comment by opoplawski** [comment]
The timing of this couldn't be more funny, as I just basically gave up on this and started working on a collection for it: https://galaxy.ansible.com/pfsensible/core

In any case, I'll bring this PR up to date with our current repository.  Thanks for taking a look at this.

**Comment by opoplawski** [comment]
Of course, now I've probably included too many modules again (some are pretty green).  Let me know though how we should proceed.

**Comment by Akasurde** [comment]
@opoplawski Do you think we should close this PR since we have [collection](https://github.com/pfsensible/core) for pfsense?

For posterity - Link to pfsense collection in Galaxy - https://galaxy.ansible.com/pfsensible/core

**Comment by opoplawski** [comment]
I think so.  We'll possibly pursue inclusion into community modules later if that becomes a thing.

**Comment by Akasurde** [comment]
@opoplawski Thanks for the confirmation. Look forward to have a big community around pfsense and Ansible.

**Pull request closed without merging**
