### PR TITLE
apt_key lists all keys in uppercase

### PR DESCRIPTION
**Pull request by jjshoe**
allow for a little user error

### CODE REVIEW

**Comment by jimi-c** [comment]
Just for future reference, you've created a feature branch for this, so you could just add your fix using `git commit --amend` on that branch and then `git push --force` to overwrite the previous commit on github. That will automatically update the PR without having to create a second one.

I'm assuming #7020 can be closed?

**Comment by jjshoe** [comment]
Yes, it can be, I was trying to update the PR but made a giant mess.

**Comment by andreasf** [comment]
Please also address #7018, as the fix for that would be in the same line

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
