### PR TITLE
mysql_replication: add master_delay parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
mysql_replication: add master_delay parameter

instead of https://github.com/ansible/ansible/pull/56767

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```mysql_replication```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
ready_for_review

**Review by bmalynovytch — APPROVED** [review]
LGTM
shipit

**Review by resmo — APPROVED** [review]
shipit

**Pull request merged**
