### PR TITLE
ansible-test integration: support "docker" and "lxd" connections

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

Adds a new `--connection` flag to `ansible-test integration` that uses
an alternative inventory (`inventory-docker` or `inventory-lxd`) this
allows us to run integration tests under an alternative transport, which
can be very useful.

Using a connection other than `local` also disables `inject_command()`
which depends on modules running on the same machine as `ansible-test`
executor, which isn't the case in `lxd` and `docker` transports.

Finally, using a connection other than `local` removes the need to run
`ansible-test` as root for `needs/root/` tests.

I've been wanting to add a test to my PR #26922 and I had troubles finding an elegant way to do so. Adding a `synchronize_lxd` target? Adding a synchronize test to `connection_lxd`? Both these solutions feel inelegant and wrong. The proper way seems to piggyback on existing tests by adding a new mode under which we run them.

This is a WIP because there are still problems with many tests, notably with `~` interpretation with `output_dir`. I also need to write the documentation for this new flag, but I seek early feedback from @mattclay before I continue working on this further.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION

```
ansible-playbook 2.4.0 (synchronize-lxd-transport 7d6eaf33ec) last updated 2017/07/17 16:21:27 (GMT -400)
  config file = None
  configured module search path = [u'/home/vdupras/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vdupras/src/ansible/lib/ansible
  executable location = /home/vdupras/.local/bin/ansible-playbook
  python version = 2.7.12 (default, Jun  9 2017, 11:18:57) [GCC 5.4.0]
```

##### ADDITIONAL INFORMATION

Example run:

```
$ ./test/runner/ansible-test integration --connection docker ping
Running ping integration test role
 [WARNING]: The `junit_xml` python module is not installed. Disabling the `junit` callback plugin.


PLAY [testhost] ***********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
                                                                                                                                                        [0/369]
TASK [Gathering Facts] ****************************************************************************************************************************************
ok: [testhost]

TASK [ping : ping the test] ***********************************************************************************************************************************
ok: [testhost]

TASK [ping : assert the ping worked] **************************************************************************************************************************
ok: [testhost] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}

TASK [ping : ping with data] **********************************************************************************************************************************
ok: [testhost]

TASK [ping : assert the ping worked with data] ****************************************************************************************************************
ok: [testhost] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}

TASK [ping : ping with data=crash] ****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: boom
fatal: [testhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lScyN4/ansible_mod
ule_ping.py\", line 93, in <module>\n    main()\n  File \"/tmp/ansible_lScyN4/ansible_module_ping.py\", line 83, in main\n    raise Exception(\"boom\")\nExcept
ion: boom\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
...ignoring

TASK [ping : assert the ping failed with data=boom] ***********************************************************************************************************
ok: [testhost] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}

PLAY RECAP ****************************************************************************************************************************************************
testhost                   : ok=7    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by s-hertel** [comment]
cc @mattclay

**Comment by mattclay** [comment]
There are two different use cases for environments such as lxd, docker, etc.:

1. Running tests from within these environments. The tests and modules all run within a single container (docker, lxd, etc.), either using a local or ssh connection. This is natively supported by ansible-test with the `--docker` option. I'd like to add lxd and others at some point. Without native support, you can still do this by simply running ansible-test from within the desired environment.

2. Running connection sensitive tests against these environments. The tests run locally but the modules run in the remote environment. Examples are the `connection_*` tests such as `connection_ssh`. These tests are created only for scenarios known to be affected by connection type. We don't need to be running all tests over every connection type.

A `synchronize_lxd` test would fall under the second category. It is specifically for testing the interactions between synchronize and lxd. Being explicit means the test can run automatically against the desired environment (when available) without requiring any additional setup or options.

Creating that test as a script based test (runme.sh) instead of a role would permit re-using the existing synchronize test, as well as adding any additional tests required. The test should start the needed container, run the tests, then remove the container when finished. 

There are a few things lacking in ansible-test to make this work more smoothly:

1. Having `needs/lxd`, `needs/docker`, etc. aliases that will automatically skip tests when those connections are not available. 
2. Having a way to tell ansible-test that the `synchronize_lxd` test is dependent on both the synchronize module and the lxd connection plugin.

Fortunately neither of these is required to implement the test.

**Comment by ghost** [comment]
@mattclay so you would consider the `synchronize_lxd` test approach the most fitting in the case of #26922 ? Alrighty then, I'll do that.

**Comment by mattclay** [comment]
@hsoft Yes. Having tests dedicated to module + connection combinations which are known to require additional testing is the right way to go. Both a `synchronize_lxd` and `synchronize_docker` test would be appropriate.

Hopefully you can leverage the existing tests for those and then augment them with any additional tests to cover scenarios specific to lxd or docker that aren't covered by the standard tests. Of course if the additional tests would benefit the normal synchronize test, then go ahead and put them there and we can just run the same test set for different connection types.

**Pull request closed without merging**
