### PR TITLE
Elliptic curve tests for crypto modules

### LINKED ISSUE #32626: Support elliptic curves in the crypto modules
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

openssl_privatekey
openssl_publickey (?)
openssl_csr (?)

##### SUMMARY

Many applications now support elliptic curve certificates and keys. It would be helpful to also be able to generate elliptic curve keys in Ansible.

This will probably require a major refactor as pyOpenSSL doesn't support this in the 'normal' API, you'd probably need to use  the`openssl._util.lib` C interface. Using the `cryptography` library is quite possibly a lot nicer.

##### DESIRED FUNCTIONALITY

```yaml
- openssl_privatekey:
    type: ec
    curve: secp256k1
    path: some/path.pem
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Add ECC tests for openssl_certificate, openssl_csr and openssl_publickey, to demonstrate that they already support elliptic curves. Fixes #32626.

CC @thomwiggers @MarkusTeufelberger @Spredzy

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
openssl_certificate
openssl_csr
openssl_publickey

### CODE REVIEW

**Comment by thomwiggers** [comment]
Seems fine.

shipit

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
I guess this is one of the cases where being namespace maintainers doesn't help... @MarkusTeufelberger @Spredzy we really need your help here :)

**Comment by MarkusTeufelberger** [comment]
oh, sorry!

shipit

**Comment by felixfontein** [comment]
@MarkusTeufelberger no problem :) And thanks for your review!
@thomwiggers also thanks for your review!
@resmo thanks for merging!

**Pull request merged**
