### PR TITLE
Update user roles to NetAppModule format

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Update User roles to NetApp Module Format

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
* na_ontap_user_roles

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]

**Review by schmots1 — APPROVED** [review]
shipit

**Review by thedoubl3j — APPROVED** [review]
example update and adding module_utils import, lgtm.

**Comment by angystardust** [comment]
Thanks a lot for the `query` feature, @carchi8py!
I'll test this tomorrow ;)

**Review by lonico — APPROVED** [review]
shipit

**Comment by lonico** [comment]
close #44710

**Pull request merged**
