### PR TITLE
unified boolean function

### LINKED ISSUE #17815: unify the lists of strings/values that are booleans (ie, 'yes','on','true','TRUE','y','1', etc)
- Bug Report
##### COMPONENT NAME

N/A
##### ANSIBLE VERSION

```
ansible 2.2.0 (skip_test_aws_on_no_boto d16715bad3) last updated 2016/09/29 13:25:16 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 7808f42aff) last updated 2016/09/29 09:37:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 881d2f95a8) last updated 2016/09/29 09:37:49 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides


```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

We have multiple places where we define what strings or values that map to booleans. 
We should unify them and verify their usage where possible.

**examples:**

``` yaml
utils.boolean.py: def booleans()
ansible.module_utils.basic: BOOLEANS
lib/ansible/constants.py:33: BOOL_TRUE = frozenset([ "true", "t", "y", "1", "yes", "on" ])
lib/ansible/plugins/action/set_fact.py:47
lib/ansible/modules/core/network/nxos/nxos_interface.py:294 BOOLEANS_TRUE = ['yes', 'on', '1', 'true', 'True', 1, True]
lib/ansible/plugins/action/net_template.py:31:BOOLEANS = ('true', 'false', 'yes', 'no')
```
- Gundalow - tweaked formatting

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

also optimized boolean function
fixes #17815

### CODE REVIEW

**Comment by alikins** [comment]
Looks reasonable to me.

(I might have gone with to_boolean() since we dont use mk_* elsewhere, but shrug, doesnt matter much...)

**Comment by bcoca** [comment]
i kept original name, fine with renaming

**Comment by alikins** [comment]
maybe exit early for bool types?

``` python
def mk_boolean(value):
    if isinstance(value, bool):
        return value

    if value is None:
        return False

    ret = str(value).lower() in BOOL_TRUE
    return ret
```

**Comment by alikins** [comment]
But whichever works, as long as everything uses it. LGTM.

**Comment by bcoca** [comment]
it does exit early, that is what the first `if` does

**Pull request merged**
