### PR TITLE
Subversion

### PR DESCRIPTION
**Pull request by dsummersl**
Support for subversion - I've tested it by hand at this point, but I'd like to add tests to nose...

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks pretty good.

initial review notes of things to fix:
- logger code needs to be removed
- try/except pass when making a directory looks suspicious... seems like it should only try to create the directory if it does not exist and fail if it cannot create it.
- throwing away non-tracked files seems like a bad idea, perhaps the reset pathway should go away?  What if someone had a config file in that directory?   If anything, maybe the reset should be configurable?
- "fell through the bag" is kind of a weird/informal message.   Just giving the before and after version and changed=False should be enough.

Anyway, pretty solid... fix these up, I'll do some testing, and we can take it.

FWIW, I don't think we really need tests in nose as the unit tests would then depend on SVN, nor are these very subject to change.  I pulled the git ones out because they hit the public internet to find repos.

**Comment by dsummersl** [comment]
Just committed some more changes:
removed logging
removed the try/except block. It isn't needed for svn co.
Yes, that is a weird message :) Took it out.

I modeled the revert logic to match the git plugin. But...I don't like the idea of it throwing away local changes either...maybe I should make a 'force' option that, when set, throws things away if there are local modifications and otherwise throws off an error if it encounters local changes?

**Comment by mpdehaan** [comment]
Yeah, git reset does not delete local files.

It's ok if it has a force, doing it by default would surprise people.   

You also shouldn't set message to blank when there is no message, just leave it out.

Take care of that and I'll apply it, thanks!   Nice to see this!

**Comment by dsummersl** [comment]
Maybe my branch is out of date or something b/c the git plugin I've been looking at is doing a 'git reset --hard' which definitely throws out modified files (not untracked ones though)...

Either way I'm happy to wrap subversion's with a force option that defaults to false. If you want I could do the same thing to git's.

Any interest in a cron plugin?

**Comment by mpdehaan** [comment]
Hmm, does it?  It might.   I suspect peopel would call git and then
template anyway.   TBH, I don't use it :)

If you want to do that to git that seems good.

Cron?  Absolutely.   That would be great.

**Comment by mpdehaan** [comment]
Still wanting the removal of the blank "msg" and then I'll apply this.   Add force= if you want first or later, just let me know.

**Comment by dsummersl** [comment]
I did the following:
- cleaned up the msg field.
- added the force option as discussed to both git and subversion: note that since git already defaulted to overwriting local changes on updates, I defaulted to 'force=true' for both libraries so that they behave the same way...let me know if you'd rather it default the other way around. I just figured it would make less people unhappy if they already expected overwrites...
- added test cases for subversion and git.

Question about testing. For my own testing I setup a vagrantfile and modified my own TestRunner so that it did all testing on vagrant sandboxed ubuntu (setup with the vagrant-ansible plugin of course :) ). I didn't commit this with these changes - Would that be something you'd be interested in having committed in a separate patch? I would think it would be a good direction to go for testing different platforms...

**Comment by mpdehaan** [comment]
Great, thanks, I think default forcing seems ok, we can make a note of it.

I don't really want tests that depend on vagrant as many of us run different virtualization technology -- or in fact already develop on a VM (I typically use a vmware fusion box running CentOS inside OS X...).

I'm making a note to update the rst documentation in the ansible/ansible.github.com project -- if you beat me to it, that would be fine :)

Thank you, glad to see this!

**Pull request merged**
