### PR TITLE
Updated shebang from #!/bin/bash to #!/usr/bin/env bash (more flexible)

### PR DESCRIPTION
**Pull request by Maroloccio**

### CODE REVIEW

**Comment by bcoca** [comment]
I get the $() vs `` and most bashism changes, but why remove all the double quotes?

**Comment by Maroloccio** [comment]
Which shells exactly are meant to be supported by this script?

**Comment by bcoca** [comment]
bash in general, primarily linux/OS X/BSD, but probably solaris and AIX variants also

**Comment by Maroloccio** [comment]
Bash "in general"? Explain. For Bash, the removal of quotes is correct. Solaris and AIX are OSs, not shells.. What do you mean?

**Comment by abadger** [comment]
I've merged the commits that I am comfortable with:
- shebang to env
- backticks to $()
- Adding more quoting

I do not like the other changes as they could potentially affect portability.  Since there was a complaint that there are other non-posix constructs in env-setup already I created an alternate PR to get rid of the one that was noted on IRC: https://github.com/ansible/ansible/pull/9975

**Comment by abadger** [comment]
As discussed on IRC, removed shebang line: https://github.com/ansible/ansible/commit/245f934629250ff071d419d45ed670fb79490789

**Comment by abadger** [comment]
Okay, I think there's general agreement among the committers that our ideal target for this script is posix compatibility.  If we can feasibly make changes to increase posix compatibility we'll add those.  If there's changes that decrease posix compatibility that can feasibly be done in a different manner we'll ask that they be done in that other manner.

I think that we've cherry-picked all of the changes that make things clearer and do not affect the target of being posix compatible so I'll close this issue now.

Thanks for pointing out these issues and looking for a statement on what we're trying to target.

# Partially Merged

Hi!

We've merged portions of this that we thought were inline with what we're trying to achieve with the code.  the changes will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
