### PR TITLE
jenkins and codebuild patches

### PR DESCRIPTION
**Pull request by jdnrg**
codebuild able to setup triggers on branches
jenkins able to get the config out of a job

##### SUMMARY
Small patches to make things usable
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
jenkins
aws code build

##### ADDITIONAL INFORMATION

We want to be able to trigger code build changes from git commits
We want to be able to extract the config of a jenkins job via ansible

### CODE REVIEW

**Comment by jdnrg** [comment]
The actual hook code is not ready to submit as a patch because it only creates the webhook and does not support the other operations. This just allows the source version to be specified.

**Comment by stefanhorning** [comment]
I think it would be better to have two PRs here, one per module. As outside the your personal use-case those modules are completely unrelated and even in different domains (Jenkins, AWS). 
This would also allow independent reviews on each of them, by people that are experts in those different domains. 
Also when you extend module features please make sure to also extend the documentation section to document them and if applicable also add integration tests. See `test/integration/targets/aws_codebuild` for example.

**Comment by jdnrg** [comment]
Alright I will do that, thank you.

**Comment by jdnrg** [comment]
Will split into two PRS.

**Comment by stefanhorning** [comment]
Thanks

**Pull request closed without merging**
