### PR TITLE
Avoid recursively checking JSON inventory for Unicode

### PR DESCRIPTION
**Pull request by towolf**
Both python-json and simplejson always return unicode strings when using
their loads() method on unicode strings. This is true at least since
2009. This makes checkign each substring unnecessary.

This commit makes parsing of large dynamic inventory at least 2 seconds
faster.

Related to issue #13956

cf: https://github.com/towolf/ansible-large-inventory-testcase

### CODE REVIEW

**Comment by abadger** [comment]
This looks generally good but I have the feeling we should be transforming even higher up.  What about doing it at these two places instead:

https://github.com/ansible/ansible/pull/13993/files#diff-a4d695beaa410b22bfeb22749cdaa210R61
https://github.com/ansible/ansible/pull/13993/files#diff-a4d695beaa410b22bfeb22749cdaa210L64

Also use the to_unicode() function from ansible.utils.unicode.

Not sure if we want to error out if we encounter non-utf8 input.  For stdout I guess we do since it is supposed to be proper json (and json is always supposed to be encoded utf-8 AFAIK).  So you can do self.data = to_unicode(stdout, errors='strict')  Probably need to catch the exception if that fails to decode and give an error message similar to the ones in _parse()

For stderr, I think we're only using that to construct an error message so we don't need to throw an error (we're already inside of an error condition).  so probably using to_unicode(stderr)   (which does errors='replace' by default) is fine there.

**Comment by towolf** [comment]
Moved the conversion to the place you suggested.

**Comment by jimi-c** [comment]
This has my +1, just want @abadger to give it a review as well.

**Comment by abadger** [comment]
+1 from me.  @towolf Would you be comfortable squashing the commits? https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes  If not one of us can do that before we merge.  (just trying to spread the work around ;-)

**Comment by towolf** [comment]
Done.

**Comment by abadger** [comment]
Merged to devel and stable-2.0.  It should be in the 2.0.1 release.  Thanks!

**Pull request merged**
