### PR TITLE
win_credential: new module to manage credentials

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Add a new PowerShell module that can be used to manage credentials in the Windows Credential manager.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
win_credential

### CODE REVIEW

**Comment by dagwieers** [comment]
I am torn about the name as we aren't managing credential managers, but credentials. So somehow I prefer **win_credential** over **win_credential_manager**. Not sure if that makes any sense though :-)

**Comment by jborean93** [comment]
No that makes sense, I'm happy to go with whatever but will see if anyone else has any thoughts before making the change. I think @nitzmahone potentially suggested `win_credential_cache` or something along those lines.

@jhawkesworth do you have any thoughts on this?

**Comment by dagwieers** [comment]
We already have some other Windows modules that have similar names, so maybe I am splitting hairs here.
- win_audit_policy_system
- win_certificate_store
- win_disk_management

In some of these cases one could say e.g. "we manage the Windows Certificate Store" which probably is true as well. So I guess it boils down to whether we are managing some existing infrastructure/product (where potential alternatives exist, or could become prevalent), or instead some more generic OS property.

**Comment by jborean93** [comment]
Ok so I'm going to change this to just `win_credential`. This is a fairly obscure part of Windows so it will be rare to have a conflict in the future.

As for the examples you gave

> win_audit_policy_system

This actually changes the system's audit policy settings, whereas there's another module that changes the audit (SACL) values for a file

> win_certificate_store

This manages certificates in a store, I agree I'm splitting hairs here but I do see the potentially for having a `win_certificate` or `win_certificate_csr` to actually create certs instead of just managing the ones in the store

> win_disk_management

Hasn't been merged and I believe it was decided to split this up into things like `win_disk`, `win_partition` and so on.

**Comment by jborean93** [comment]
Have pushed a commit that renames the module to `win_credential`

**Pull request merged**
