### PR TITLE
[2.9] Backport cron module regression fix

### LINKED ISSUE #71213: Cron module in ansible 2.9.12 removes all old content (regression)
##### SUMMARY
The cron module in ansible 2.9.12 removes all previous content from the crontab (or cron file). It is highly likely that the problem was originally introduced in: https://github.com/ansible/ansible/commit/5ce47646add41077872b9cd9e0e8a24874995aae#r41381859.

Pull request https://github.com/ansible/ansible/pull/71207 fixes this issue and to adds a test case to prevent this from happening again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- cron:
    user: root
    cron_file: 'test'
    state: 'present'
    name: 'one'
    job: 'echo one'
- cron:
    user: root
    cron_file: 'test'
    state: 'present'
    name: 'two'
    job: 'echo two'

```

##### EXPECTED RESULTS

Two cronjobs

##### ACTUAL RESULTS

Only the last cronjob is added

### LINKED ISSUE #71216: cron module removes all jobs for each task
##### SUMMARY

Adding multiple `cron` tasks results in only the last one remaining in the `cron_file`. This problem doesn't seems to exist in 2.9.12, but not 2.9.11.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`cron`

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.12
  config file = /home/cwalker/.ansible.cfg
  configured module search path = ['/home/cwalker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/pyenv/lib64/python3.6/site-packages/ansible
  executable location = /tmp/pyenv/bin/ansible-playbook
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/home/cwalker/.ansible.cfg) = 60
DEFAULT_HOST_LIST(/home/cwalker/.ansible.cfg) = ['/home/cwalker/hosts']
DEFAULT_REMOTE_USER(/home/cwalker/.ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/cwalker/.ansible.cfg) = ['/home/cwalker/required-roles', '/home/cwalker/roles', '/etc/ansible/roles']
HOST_KEY_CHECKING(/home/cwalker/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEL Linux 7.8

##### STEPS TO REPRODUCE

Using the below playbook.

```ansible-playbook -K -i localhost,  -c local /tmp/test.yml```

```yaml
---
- hosts: all
  become: true

  tasks:

  # Cron Change
    - cron:
        name: "First Entry"
        user: "root"
        minute: "30"
        hour: "6"
        cron_file: testing
        job: "/bin/true"

    - cron:
        name: "Second Entry"
        user: "root"
        minute: "40"
        hour: "5"
        cron_file: testing
        job: "/bin/false"
```

##### EXPECTED RESULTS

I would expect both the `First Entry` and `Second Entry` crons to be in `/etc/cron.d/testing`.

##### ACTUAL RESULTS

Only the last entry was there.

```% cat /etc/cron.d/testing
#Ansible: Second Entry
40 5 * * * root /bin/false
```

```paste below
BECOME password:

PLAY [all] ********************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: [localhost]

TASK [cron] *******************************************************************************************************************
changed: [localhost]

TASK [cron] *******************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### LINKED ISSUE #71217: cron module in 2.9.12 fails Idempotence.
##### SUMMARY

After upgrading to ansible 2.9.12, idepodence for the cron module fails.  It now returns 'changed` every time it's run, and updates the files.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

  ```YAML
cron:
    name: foo
    minute: "*/30"
    user: foo
    job: /usr/local/bin/foo
    cron_file: cron-foo
```
##### ANSIBLE VERSION

```paste below
2.9.12
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

MacOS

##### STEPS TO REPRODUCE

run Ansible-playbook twice.  2nd time any cron commands execute again, despite no changes.

```yaml
cron:
    name: foo
    minute: "*/30"
    user: foo
    job: /usr/local/bin/foo
    cron_file: cron-foo
```

##### EXPECTED RESULTS

The cron module should be Idempodent.

##### ACTUAL RESULTS

```paste below
    TASK [ansible-consul : Run foo every half-hour via cron] *************
    changed: [ubuntu-2004]
```
☝️ that happens if I run it multiple times.  all other non-cron tasks are fine.

### LINKED ISSUE #71226: cron: task does not correctly add env vars anymore
##### SUMMARY
cron: task does not correctly add env vars anymore

##### ISSUE TYPE
- Bug Report (regression in 2.9.12)

##### COMPONENT NAME
ansible core

##### ANSIBLE VERSION
2.9.12

##### STEPS TO REPRODUCE
Try to add a CRON entry with argument env:

Example: https://gitlab.com/ae-dir/ansible-ae-dir-server/-/blob/master/tasks/cron.yml#L4

##### EXPECTED RESULTS
Env vars are added to crontab entry (like in ansible 2.9.11).

##### ACTUAL RESULTS
Env vars are missing in crontab entry.

### PR DESCRIPTION
**Pull request by relrod**
##### SUMMARY

Change:
- Backport of #71207

Test Plan:
- CI

Tickets:
- Fixes #71213
- Fixes #71217
- Fixes #71216
- Fixes #71226
- Refs #71207

Signed-off-by: Rick Elrod <rick@elrod.me>

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
cron module

### CODE REVIEW

**Comment by oxivanisher** [comment]
This is super important! In my case, this bug removed backup jobs from cron which is pretty much a worst case ...

**Comment by dchandekstark** [comment]
This is a serious regression. Please merge the fix into 2.9 ASAP!

**Comment by Lin-Buo-Ren** [comment]
This regression wiped our production hosts' crontabs today, hope this helps.

**Comment by jzielke84** [comment]
Seriously 12 days and still no merge while repository packages only offer 2.9.12 and you have to use pip to manually make a rollback to avoid any more damage?

**Comment by Lin-Buo-Ren** [comment]
Escalate the PR by giving a :+1: reaction to the top thread may help...probably?

**Comment by relrod** [comment]
@jzielke84 Yes, "seriously." We do releases on (roughly) a 3 week cadence. This will go in the next release, due next week.

**Comment by jzielke84** [comment]
@relrod At least it would be nice if you keep the ability for users to rollback versions from the official repository. This would make things easier.

**Comment by dchandekstark** [comment]
Is there not a process to yank or hot fix a release with such a major regression?  Waiting until the next scheduled release does not inspire confidence that this issue is taken seriously.

**Pull request merged**
