### PR TITLE
Ansible interpreters

### PR DESCRIPTION
**Pull request by bcoca**
Add multiple interpreter overrides through ansible_{bin}_interpreter variables, expanding the ansible_python_interpreter feature

### CODE REVIEW

**Comment by dhozac** [comment]
basename is too simplistic, it won't work for the existing modules using /usr/bin/env python. Should probably check if env is the basename and if so use the next argument.

**Comment by bcoca** [comment]
If the module is using env it shouldn't need an override.

Brian Coca

**Comment by dhozac** [comment]
... except if you want to use python26 because python is 2.4.

**Comment by bcoca** [comment]
Ah, need to think about that, might need to make env a special case.

This patch still works as previous python only var so it can go through ,as
is, while I add env support in a follow-up.

Brian Coca

**Comment by dhozac** [comment]
No, previously it would replace it with the python interpreter if python was in the shebang at all. This would break the wait_for, group and authorized_key modules for anyone who needs ansible_python_interpreter, as well as potential local modules.

**Comment by mpdehaan** [comment]
@bcoca, let me know if you don't follow, but that is basically correct.

One thing people want to do is set ansible_python_interpeter to things like /foo/bin/mypython so the executatable name in the shebang line isn't always the one you want to use.

It instead needs to get the value of the ansible_(python)_interpreter variable in the shebang ends in "python", if it ends in Ruby, it needs to look at ansible_ruby_interpreter, etc.

**Comment by bcoca** [comment]
damn, you are absolutely correct, I'll patch that and resubmit.

Brian Coca

**Comment by bcoca** [comment]
Micheal,

some modules have parameters passed to the shebang, do we want to keep
those?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001

**Comment by mpdehaan** [comment]
yeah, it should preserve anything that's there.

**Comment by mpdehaan** [comment]
Python modules passing "-tt" is probably a good thing, BTW.

**Comment by bcoca** [comment]
some are but it is inconsistent, as is the use of env. 

In any case, I need to re-factor the code and change to loop over ansible_bin_interpreter variables and take the 1st match, then run a substitution that factors s/(#!)(\S+)(._)/\1binvars[\2]\3/ to substitute and if basename=env then it changes to something like s/(#!)\S+\s+(\w)(._)/\1binvars[\2]\3/, if that makes sense

**Comment by mpdehaan** [comment]
modules should NOT be using env so we can fix all of those.

as for parameters, I think you can just split on whitespace and include
everything after the 0th token.

**Comment by bcoca** [comment]
If we remove env from modules this patch can go as is (I would still like
to add back any command line options).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001

**Comment by bcoca** [comment]
modules with env:
authorized_keys
group
wait_for

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001

**Comment by mpdehaan** [comment]
I'm fine with that.   Let's just make it so that if the command line has "/env" in it it does not ever modify the line, and we should remove the env usage for those three modules.

Thanks!

**Comment by mpdehaan** [comment]
and yeah, command line options are important (required before I can take this), particularly if someone was doing "perl -w" instead of "use warnings".

**Pull request closed without merging**
