### PR TITLE
Add shelvefile lookup plugin

### PR DESCRIPTION
**Pull request by lekum**
Add lookup plugin to read string values of keys from a [shelve](https://docs.python.org/2/library/shelve.html#module-shelve) file.

Usage example:

```

---
- hosts: localhost
  vars:
    book: "{{ lookup('shelvefile', 'file=book.db key=current_book_name') }}"
    page: "{{ lookup('shelvefile', 'file=book.db key=current_book_page') }}"
    author: "{{ lookup('shelvefile', 'file=book.db key=current_book_author') }}"

  tasks:
    - name: Print my current reading
      debug: msg="I'm on page {{ page }} of '{{ book }}' by {{ author }}"
```

### CODE REVIEW

**Comment by bcoca** [comment]
lookup plugins have changed, this won't work with the current version.

we are preparing docs to show how to create plugins that will work with both 1.x and 2.x versions of ansible.

**Comment by lekum** [comment]
It's based upon the code of the [file lookup](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/file.py) of the `devel` branch. Where can I found the actual plugins that work with the `devel` version?

**Comment by bcoca** [comment]
look at the current version of the file lookup, it is pretty different than it was

**Comment by lekum** [comment]
Which one is the current one?

```
./v1/ansible/runner/lookup_plugins/file.py
./lib/ansible/plugins/lookup/file.py
```

**Comment by bcoca** [comment]
v1/ is there only for testing, that is dead code that will be removed, so of course, the other one

**Comment by lekum** [comment]
I changed it according to the new file lookup plugin

**Comment by lekum** [comment]
Is there anything I could do to help with this?

**Pull request merged**
