### PR TITLE
Unify terms and UI between 1Password lookups and facts module

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Unify the terms and interface used for logging in to 1Password  between the facts module and lookup plugins.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`onepassword.py`
`onepassword_raw.py`
`onepassword_facts.py`

##### ANSIBLE VERSION

```paste below
2.7
```

### CODE REVIEW

**Comment by Rylon** [comment]
Quick question about error messages @samdoran in the module docs I added recommendation for using the module with `no_log: true`, but the issue there is that also hides error messages raised by the module, such as "item not found in 1Password".

Can you think of a better way to protect from accidentally logging secrets, whilst allowing error messages to come through?

**Comment by samdoran** [comment]
Unfortunately, no. We don't currently have a mechanism for marking facts as sensitive/`no_log`, only input parameters (which I added to `master_password` and `secret_key`, so that's something 😃).

We should probably add documentation that these items are set as Ansible facts, which are subject to caching.

**Comment by samdoran** [comment]
But normally the returned data is not logged to the console, so running without `-v` will still show errors and hide returned facts.

**Comment by samdoran** [comment]
@Rylon Have you had a chance to look this over? What do you think?

**Comment by Rylon** [comment]
Hi @samdoran I just had a look through now, and it all looks good to me! One additional thing I just thought of though, I notice you removed the 1Password CLI version from the docs (v0.5.1) and I remembered I had added that there to give users a clue which version we had tested with. Perhaps we can do something better here. This would be just in case the CLI 'signature' changes substantially between versions and we're unable to parse it properly.

Otherwise, looks good to me!

**Comment by samdoran** [comment]
@Rylon Thank you for the feedback. I did remove the version number from the docs since those things don't age well. But it's probably a good idea to leave it in there. I'll put it back.

**Review by Rylon — APPROVED** [review]
Nice, looks good!

**Pull request merged**
