### PR TITLE
Chocolatey module for windows packagement

### PR DESCRIPTION
**Pull request by petemounce**
Building on @trondhindenes spike, here is a module that supports windows package management via [Chocolatey](http://chocolatey.org).

It 
- can install, uninstall, pick versions, force, and use different (named) sources.
- is intelligent enough to know when a change has occurred
- bootstraps itself onto the victim machine if chocolatey (or the web platform installer source) is required

Known issues so far
- It does not correctly parse chocolatey command stdout when a package is successfully installed after dependencies
- It doesn't time commands
- It doesn't write a log file to the victim machine (which would be really handy for debugging, since the output would be easier to read than it is in ansible's JSON back on the control node)
- **I haven't written any tests for it yet**

### CODE REVIEW

**Comment by wozz** [comment]
I keep getting out of memory errors or "Process is terminated due to StackOverflowException."

Is there a specific setting you need to configure to make this work?  I read that MaxMemoryPerShellMB may need to be increased, but perhaps I'm not overriding the default setting properly.

**Comment by petemounce** [comment]
It was not necessary for me to do that on windows 2012 r2, in AWS with a
t2.medium.

##

**Comment by cchurch** [comment]
There is a [hotfix](http://support.microsoft.com/kb/2842230) mentioned [here](https://github.com/ansible/ansible/pull/8345#issuecomment-52074837) that has fixed that issue for me when running against Windows 2008 servers.

**Comment by wozz** [comment]
The hotfix seems to fix that issue.  Now I get a parsing error if chocolatey is not installed yet.  The output from the chocolatey install script is being parsed as the output of the module.  Some of the output can be suppressed by overloading "Write-Host", but the output from 7zip still shows up.

**Comment by trondhindenes** [comment]
chocolatey is super-tricky since it has a lot of unstructured chatter that needs capturing. We might not be able to get away with a "clean" module for this.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
