### PR TITLE
win_chocolatey_pin: pin a chocolatey package

### PR DESCRIPTION
**Pull request by sbaerlocher**
##### SUMMARY

With this module it is possible to pin a package in chocolatey and unpinned.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
win_chocolatey_pin

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by sbaerlocher** [comment]
ready_for_review

**Comment by mattclay** [comment]
@sbaerlocher Add a `test/integration/targets/win_chocolatey_pin/aliases` file with the contents:

```
shippable/windows/group4
```

This will cause the integration test to run in CI.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/88558/24/console

The task to install Firefox is hanging until the Windows test VM is deleted due to excessive run time:

```
06:57 TASK [win_chocolatey_pin : ensure firefox is installed] ************************
53:23 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectTimeout: HTTPSConnectionPool(host='ec2-18-217-166-38.us-east-2.compute.amazonaws.com', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd66497a210>, 'Connection to ec2-18-217-166-38.us-east-2.compute.amazonaws.com timed out. (connect timeout=30)'))
53:23 fatal: [windows-2008]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

I don't know why it's failing, but I recommend that you pick the smallest possible application to install with the test to minimize test overhead.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/88665/28/tests

**Comment by dagwieers** [comment]
During the [next Windows WG meeting](https://github.com/ansible/community/issues/420) on 2019-01-29 we will review and decide on the inclusion of this module in Ansible v2.8. Your presence in the meeting could be helpful.

*If there's anything you wanted to improve/fix, please do so before the meeting.*

**Comment by jborean93** [comment]
I have worked on this and found the functionality better fit into the existing `win_chocolatey` module. The PR to add that can be found at https://github.com/ansible/ansible/pull/53157. Thanks for working on the original work @sbaerlocher sorry we couldn't get this merged in but we still appreciate the work you've done.

**Pull request closed without merging**
