### PR TITLE
cloud: ovirt: Fix upgraded state of the ovirt_hosts module

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

When the host is being upgraded in oVirt the state of the host can be MAINTENANCE not only 'UP', this PR add and possibility upgrade host in MAINTENANCE state.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ovirt_hosts

##### ANSIBLE VERSION

```
2.3.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina

**Comment by machacekondra** [comment]
@masayag @ryansb

**Comment by machacekondra** [comment]
shipit

**Review by masayag — APPROVED** [review]

**Review by mwperina — APPROVED** [review]
👍

**Pull request merged**
