### PR TITLE
2.14: Use FAs with inheritance only when applicable (#80026)

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Backport of #80026 

(cherry picked from commit 6c3d2a4e51df560e350d1ca3d6a039bf0e05f2ab)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`FieldAttribute`s

### CODE REVIEW

**Comment by perlun** [comment]
Any status updates on this one @mkrizek? :thinking: 2.14.3 still exhibits the problem. I am stuck on Ansible 2.13.4 because this is a critical problem for our use case.

**Comment by sivel** [comment]
@perlun this will be included in the upcoming 2.14.4 release.  2.14.4rc1 is scheduled for today, and the GA for March 27.

**Comment by perlun** [comment]
@sivel Wonderful, greatly appreciated! :bow:

**Pull request merged**
