### PR TITLE
Add support for --copy-links in synchronize

### PR DESCRIPTION
**Pull request by 42wim**
Add support for --copy-links which copies the item that the link points to, rather than the symlink

### CODE REVIEW

**Comment by jctanner** [comment]
@42wim There is an indentation problem in this patch, please revise it ...

```
fatal: [el6.lab.net] => failed to parse:   File "/root/.ansible/tmp/ansible-1386275002.24-237053202620606/synchronize", line 202
    if links == "no":
    ^
IndentationError: unexpected indent
```

**Comment by 42wim** [comment]
indentation is fixed now

**Comment by jctanner** [comment]
@42wim sorry for the delay on getting back to this, but I don't want to change the type for "links" from bool to a string. It would force the users to input "yes/no" instead of True/False/0/1 etc where they might already have their playbooks coded for the later. Let's move this new behavior to a separate parameter that can override the link parameter if needs be, but does not alter it's type or inputs.

**Comment by 42wim** [comment]
ok, changed it to an extra copy_links parameter

**Comment by jctanner** [comment]
@42wim thanks!

**Pull request merged**
