### PR TITLE
Added basic support for SSL when using IRC

### PR DESCRIPTION
**Pull request by ahamilton55**
I've added basic support for connecting to an IRC server with SSL. Nothing fancy but it works.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you update the "version_added" field to say 1.7, which is the active development version, and also rebase this, as I've recently accepted some other changes into the IRC module that are causing conflicts?

Should be straightforward I'd hope.

Thanks very much!

**Comment by ahamilton55** [comment]
Okay I rebased and then bumped the version number.

**Comment by ahamilton55** [comment]
Both patches seem to be the same except for the argument that gets added and used by the user. Either one will work for me I'd just like to get this merged because I have another commit after this one.

**Comment by ahamilton55** [comment]
@mpdehaan Any thing else needed for this?

**Comment by jimi-c** [comment]
# Cleanup Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We do require submissions to be free of merge and other non-related commits, which cause difficulties in reviewing and merging code, and also affect the history of the source tree. To resolve this problem, it may be helpful to create a new branch and cherry-pick commits onto it.
- In general, always start a "topic branch" named after each thing you would like to contribute
- use "git pull --rebase" vs "git pull" to stay in tune with upstream, as well as "git rebase" vs "git merge"
- if you have things broken out over many commits, consider submitting just one squashed commit that keeps the history concise

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  

We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by ahamilton55** [comment]
@jimi-c: Okay this was updated to use a single commit.

**Comment by jimi-c** [comment]
Thanks, looks good now.

**Comment by jimi-c** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
