### PR TITLE
[2.8] docker_* modules: improve error message when docker-py is missing

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #57914 to stable-2.8. Improves error messages when docker-py is missing. Now includes the `missing_required_lib()` output.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/docker/common.py

### CODE REVIEW

**Comment by WojciechowskiPiotr** [comment]
shipit

**Comment by felixfontein** [comment]
I included a backport of #58253 (test-only follow-up to the PR backported here).

**Comment by WojciechowskiPiotr** [comment]
shipit as long as you can backport two PR's in single one :)

**Comment by felixfontein** [comment]
That shouldn't be a problem, as these are closely related (and in fact the second PR should have been a part of the first PR).

**Comment by abadger** [comment]
Merged for the 2.8.2 release.

**Pull request merged**
