### PR TITLE
Adding a new filter plugin that can encrypt and decrypt values using AWS KMS service.

### PR DESCRIPTION
**Pull request by achinthagunasekara**
##### SUMMARY

Adding a new filter plugin that can encrypt and decrypt values using AWS KMS service.
This filter plugin can be used to encrypt values using the AWS KMS service and store them within your repository, then decrypt then when you want to use them.

E.G.

In `my_role\defaults\main.yml`
```
encrypted_value: >-
  {{ abcd123abcd13 abcd123abcd13abcd12abcd13
  abcd123abcd13abcd123abcd13abcd123ab1d1312
  abcd123abcd13abcd123abcd13abcd123ssdsas12
  sadsdsasd | aws_kms_decrypt(KEY_ARN) }}
```

In `my_role\tasks\main.yml`

```
- debug:
    msg: "Decrypted value is {{ encrypted_value }}"
```

Same can be done for encrypting values.

E.G

In `my_role\tasks\main.yml`

```
- debug:
    msg: "Encrypted value is {{ 'abc123abc123abc123' | aws_kms_encrypt(KEY_ARN) }}"
```

##### ADDITIONAL INFORMATION

* https://aws.amazon.com/documentation/kms/
* https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html

### CODE REVIEW

**Comment by bcoca** [comment]
since this is querying an external service it makes more sense as a lookup

**Comment by achinthagunasekara** [comment]
@bcoca reason I picked filter is that it was more like filtering the encrypted value get a decrypted value... I guess lookup also makes sense.

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
+label ready_for_review

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
@bcoca @jborean93 I tried making this PR as ready_for_review.
Is there anything else I need to do to have it reviewed? I'm new to the process :)

Thanks

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
@bcoca @jborean93 I tried making this PR as ready_for_review.
Is there anything else I need to do to have it reviewed? I'm new to the process :)

Thanks

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
ready_for_review

**Comment by achinthagunasekara** [comment]
ready_for_review

**Pull request closed without merging**
