### PR TITLE
remove dangling file ':'

### PR DESCRIPTION
**Pull request by srgvg**

### CODE REVIEW

**Comment by mpdehaan** [comment]
this patch does not do what the commit says, can you review?

**Comment by srgvg** [comment]
I'm confused. I see the problem, but I don't understand what git magic happend here. Looking....

**Comment by srgvg** [comment]
I just 'git rm'-ed that : file. And that commit has other remove content than the content of that file in your HEAD (https://github.com/ansible/ansible/blob/devel/:)

**Comment by srgvg** [comment]
"github bug", @mpdehaan fixed it in the mean time

**Pull request closed without merging**
