### PR TITLE
Module for creating/updating/deleting a domain record in Digital Ocean

### PR DESCRIPTION
**Pull request by manicminer**
Decided to use python-digitalocean (https://github.com/koalalorenzo/python-digitalocean) as dopy (https://github.com/devo-ps/dopy) seems unmaintained

### CODE REVIEW

**Comment by jimi-c** [comment]
We already have a module for this, though it does appear that yours adds more options. Why not extend the functionality of the existing module?

Also, while it appears it's been a few months since the last commit, but I wouldn't call it abandoned quite yet. Our other digital ocean modules require dopy, so at this point I don't think we'd want to switch the underlying libraries without migrating all of them.

**Comment by manicminer** [comment]
Hi jimi-c, thanks very much for your comments. There is an existing module 'digital_ocean_domain' which can essentially create zones in Digital Ocean's DNS platform, however this module extends on that to create individual DNS records within a zone.

Usage might look something like this:

``` YAML
- digital_ocean_domain: state=present name=example.com ip=1.2.3.4
                        client_id={{ digital_ocean_client_id }}
                        api_key={{ digital_ocean_api_key }}
- digital_ocean_domain_record: state=present domain=example.com
                               name=blah
                               record_type=A
                               data=1.2.3.5
                               client_id={{ digital_ocean_client_id }}
                               api_key={{ digital_ocean_api_key }}
```

I had thought about combining the functionality into the existing module, but thought that the invocation would get overcomplicated with many records?

**Comment by manicminer** [comment]
Oh, and I had thought about changing the other DO modules to use python-digitalocean as well - dopy has some long outstanding pull requests and is currently incompatible with the DO API for the DomainRecord entity, making it unfeasible to use it for my new module.

**Comment by jimi-c** [comment]
Ok, I guess I misunderstood what the current module does? It seemed like it created an A record for a given system but yours allowed other record types whereas yours allowed other record types.

Regarding dopy, I think it would be best to standardize on a single python library, having to install multiple libraries for similar functions is not a good user experience, but maybe that means re-writing the existing DO modules? Definitely not a trivial task.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by davisonio** [comment]
@tombamford Are you going to submit this into the core or extras repository? I think that this module would be a great addition.

**Pull request closed without merging**
