### PR TITLE
Update validate-modules

### PR DESCRIPTION
**Pull request by sivel**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
test/sanity/validate-modules

##### ANSIBLE VERSION

```
v2.3
```

##### SUMMARY

* Validates ANSIBLE_METADATA
* Ensures imports happen after documentation vars
* Some pep8 cleanup

Ref: https://github.com/ansible/proposals/issues/50

### CODE REVIEW

**Comment by sivel** [comment]
This uncovers some additional issues in modules.  So we shouldn't merge immediately.

**Comment by sivel** [comment]
@mattclay All modules have been updated to pass, and this PR is green.

**Comment by jtyr** [comment]
This change is introducing bad programming practice in more than 100 modules. Every Python code should have imports should be on the top of the file.

**Comment by abadger** [comment]
I've reviewed the metadata changes, +1.  Skimmed the ansible-validate changes which looked good but I didn't dive in too deeply (figured mattclay would  be looking over those changes more than me).

**Review by mattclay — APPROVED** [review]

**Pull request merged**
