### PR TITLE
Sx5 868 pr keycloak authentication

### PR DESCRIPTION
**Pull request by elfelip**
##### SUMMARY
Keycloak authentication module

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
keycloak_authentication

##### ADDITIONAL INFORMATION
module: keycloak_authentication
short_description: Configure authentication in Keycloak
description:
    - This module actually can only make a copy of an existing authentication flow, add an execution to it and configure it.
    - It can also delete the flow.
version_added: "2.9"
options:
    realm:
        description:
            - The name of the realm in which is the authentication.
        required: true
    alias:
        description:
            - Alias for the authentication flow
        required: true
    providerId:
        description:
            - providerId for the new flow when not copied from an existing flow.
        required: false
    copyFrom:
        description:
            - flowAlias of the authentication flow to use for the copy.
        required: false
    authenticationExecutions:
        description:
            - Configuration structure for the executions
        required: false
    state:
        description:
            - Control if the authentication flow must exists or not
        choices: [ "present", "absent" ]
        default: present
        required: false
    force:
        type: bool
        default: false
        description:
            - If true, allows to remove the authentication flow and recreate it.
        required: false
extends_documentation_fragment:
    - keycloak

### CODE REVIEW

**Review by rrey — CHANGES_REQUESTED** [review]
Hi !
I think this PR contains things that are unrelated to the PR. (The keycloak_group stuff for example).

**Comment by elfelip** [comment]
> Hi !
> I think this PR contains things that are unrelated to the PR. (The keycloak_group stuff for example).

Hello Rémi. This pull request is pretty old. Do you want me to do a rebase of my branch and create a new PR?

**Comment by rrey** [comment]
Hi @elfelip !

If you rebase on devel and clean the PRs from what is not related to the PR I can help with a review.

I always push for integration tests as well, there is nothing on the repo for Keycloak but we can initiate something!

**Comment by Akasurde** [comment]
Hi @elfelip, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
