### PR TITLE
postgresql modules: use query parameters with cursor objects

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql modules: use query parameters with cursor objects

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/postgresql/postgresql_set.py```
```lib/ansible/modules/database/postgresql/postgresql_slot.py```
```lib/ansible/modules/database/postgresql/postgresql_subscription.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by kostiantyn-nemchenko — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Comment by kostiantyn-nemchenko** [comment]
Thank you @Andersson007

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko thank you for active participation!

**Pull request merged**
