### PR TITLE
FactCache updates

### PR DESCRIPTION
**Pull request by sivel**
- The get method of a dict does not internally call `__getitem__`, so add a get method that does

Currently `utils.update_hash` uses `FactCache.get()` which does not internally utilize the `__getitem__` method, so it is always returning `{}`
- When trying to update subkeys of self.SETUP_CACHE make sure to use utils.update_hash

These are just a few missed from 3ba0ea064df78387f0898a680c6936bd14a20d9c

### CODE REVIEW

**Comment by sivel** [comment]
Actually, this doesn't seem to be the full fix for the 'memory' FactCache plugin.  It works for a memcached plugin I am working on, but not for memory.  Still looking, to see if I can figure out the issue there too.

**Comment by mpdehaan** [comment]
Looks like we don't want this as this no longer defers the implementation of getitem to the plugin.

I'm looking at the email on the thread now.

**Comment by mpdehaan** [comment]
Can you share an example of where this causes a problem with a playbook?

**Comment by sivel** [comment]
The following playbook suffers from the issue

``` yaml
---
- hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
  - set_fact:
      foo: bar

  - command: echo test
    register: echo

  - debug: var=foo

  - debug: var=echo
```

In both cases, `foo` and `echo` are not interpreted:

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [set_fact ] *************************************************************
ok: [127.0.0.1]

TASK: [command echo test] *****************************************************
changed: [127.0.0.1]

TASK: [debug var=foo] *********************************************************
ok: [127.0.0.1] => {
    "foo": "{{ foo }}"
}

TASK: [debug var=echo] ********************************************************
ok: [127.0.0.1] => {
    "echo": "{{ echo }}"
}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=5    changed=1    unreachable=0    failed=0
```

This is straight off of devel:

`ansible-playbook 1.5 (devel 3ba0ea064d) last updated 2014/01/07 12:21:30 (GMT -500)`

This happens with the default 'memory' fact cache plugin.

I also experience this with my memcached plugin, which you can see at https://github.com/sivel/ansible/compare/memcached-factcache

The fix in this pull request resolves the issue with my memcached plugin, but does not fix the issue with the memory plugin.  I haven't figured out why yet, but I can see that with the following debug, these vars are indeed in the value from utils.update_hash:

``` diff
diff --git a/lib/ansible/utils/__init__.py b/lib/ansible/utils/__init__.py
index d32506e..e4114c2 100644
--- a/lib/ansible/utils/__init__.py
+++ b/lib/ansible/utils/__init__.py
@@ -963,6 +963,7 @@ def update_hash(hash, key, new_value):

     value = hash.get(key, {})
     value.update(new_value)
+    print value
     hash[key] = value
```

**Comment by mpdehaan** [comment]
So top part is good, but I think setitem is still called for the bottom part.

**Comment by mpdehaan** [comment]
We have reset to before this commit so shouldn't be a probelm.

We want to do some refactoring before I think we're ready for this.

**Pull request closed without merging**
