### PR TITLE
ec2_launch_template: Fix integration tests

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY
Fix integration tests for ec2_launch_template
- Update AWS Policy to allow tests to run
- Update metadata so that prep modules are pulled into the test container
- Ignore security_token if it's not defined.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/ec2_launch_template.py

##### ADDITIONAL INFORMATION

See also #55775

### CODE REVIEW

**Review by s-hertel — APPROVED** [review]

**Comment by gundalow** [comment]
@tremble Thank you!
Merged into `devel` for release in Ansible 2.10

**Comment by gundalow** [comment]
rebuild_merge

**Comment by tremble** [comment]
@gundalow Thanks for looking, should this have auto-merged?

**Comment by gundalow** [comment]
@tremble thanks merged now. Occasionally the Bot will miss a notification, though it has caught up.

If you'd like this fix included in 2.9 please create a backport PR against `stable-2.9` including a changelog/fragment file.

**Pull request merged**
