### PR TITLE
NEW MODULE: dnsmadeeasy

### PR DESCRIPTION
**Pull request by briceburg**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you give me some idea of how widely used this service is?

First I've heard of it.

**Comment by briceburg** [comment]
Michael,

IMO they're best of class when it comes to hosted DNS. Excellent pricing,
interface, and infrastructure (including IP AnyCast). I'm not
sure how many people use them but will inquire over Twitter.

**Comment by briceburg** [comment]
Michael,

They are a strong service and very worth looking into. I didn't know of them until I needed a provider that was NOT route53 and NOT my registrar or service provider.

from DNSMadeEasy support:

Brice,

You see Evernote on the top of the Ansible page http://www.ansibleworks.com/ (in the Customers and Users section)?

$ dig ns evernote.com

; <<>> DiG 9.9.2 <<>> ns evernote.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58190
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;evernote.com. IN NS

;; ANSWER SECTION:
evernote.com. 86400 IN NS ns7.dnsmadeeasy.com.
evernote.com. 86400 IN NS dns1.nettica.com.
evernote.com. 86400 IN NS dns2.nettica.com.
evernote.com. 86400 IN NS dns3.nettica.com.
evernote.com. 86400 IN NS dns4.nettica.com.
evernote.com. 86400 IN NS dns5.nettica.com.
evernote.com. 86400 IN NS ns5.dnsmadeeasy.com.
evernote.com. 86400 IN NS ns6.dnsmadeeasy.com.

**Comment by mpdehaan** [comment]
That will do nicely :)

**Comment by mpdehaan** [comment]
merged, thank you!

**Pull request merged**
