### PR TITLE
[2.7] docker_* modules: updating argument_spec

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #48491: updating `argument_spec` for docker_* modules.

Marked as WIP because it should be tested more. The devil is in the detail...

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docker_container
docker_image
docker_image_facts
docker_network
docker_service
docker_swarm

### CODE REVIEW

**Comment by felixfontein** [comment]
Looks like parts of the module validation code was only added recently (#46720), and is not yet part of `stable-2.7`.

**Comment by abadger** [comment]
@felixfontein  I've opened a backpotr for #46720  Once I get that merged, is there anything else you want to test before the backport gets merged?

**Comment by felixfontein** [comment]
@abadger thanks for creating and merging that backport! I've rebased this PR against current `stable-2.7`, and now it works fine (there was another problem, I forgot some code due to some refactoring while a new feature was added in `devel`, but that's now fixed as well).

I checked again that this code should not cause behavior changes (the problematic places are the suboptions in docker_container and docker_network), but it looks like there should be no problem: the idempotency code ignores `None` values (now also for docker_network), and the docker-py code which the values are fed into doesn't distinguish between `None` and "not specified". So everything should really be fine. :)

**Comment by abadger** [comment]
Merged for the 2.7.3 release.

**Comment by felixfontein** [comment]
@abadger thanks for merging!

**Pull request merged**
