### PR TITLE
Fix ssl_version default value.

### LINKED ISSUE #42897: Docker modules error with Ansible 2.6 and later with TLS config
##### SUMMARY
If docker is in TLS mode, all ansible docker modules finished with an error : 
```
FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: 'module' object has no attribute 'PROTOCOL_1.0'"}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker modules

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
```
Linux ip-172-31-3-125 4.4.0-1062-aws #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Test
    docker_container:
      state: "present"
      docker_host: "tcp://localhost:2376"
      cert_path: "/etc/docker/certs/cert.pem"
      key_path: "/etc/docker/certs/key.pem"
      cacert_path: "/etc/docker/certs/ca.pem"
      tls_verify: true
      image: tomcat
      name: test
```

##### EXPECTED RESULTS
Container is running.

##### ACTUAL RESULTS
```
FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: 'module' object has no attribute 'PROTOCOL_1.0'"}
```

The full traceback is:
```
  File "/tmp/ansible_EQHIVy/ansible_modlib.zip/ansible/module_utils/docker_common.py", line 184, in __init__
    super(AnsibleDockerClient, self).__init__(**self._connect_params)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 158, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 183, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
```

### PR DESCRIPTION
**Pull request by tbouvet**
##### SUMMARY
Fixes #42897 

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
docker

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
Remove ssl default value. SSL module checks the version.

### CODE REVIEW

**Comment by samdoran** [comment]
Please create a changelog fragment. See [fragments](https://github.com/ansible/ansible/tree/stable-2.6/changelogs/fragments) for examples.

**Comment by samdoran** [comment]
Please create a [backport PR](https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process) for this to be included in previous versions.

**Comment by tbouvet** [comment]
@samdoran Thanks ! Backport PR is done : https://github.com/ansible/ansible/pull/43242

**Comment by samdoran** [comment]
Thank you! The backport will be merged shortly before the next 2.6 release.

**Pull request merged**
