### PR TITLE
Backport/2.9/65369

### PR DESCRIPTION
**Pull request by krisvasudevan**
##### SUMMARY
Fixes for #64034, #56301

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

nios_fixed_address
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@krisvasudevan Thanks for the contribution. Could you please follow the [guide](https://docs.ansible.com/ansible/latest/community/development_process.html?backporting-merged-prs#backporting-merged-prs) and re-create this PR. Thanks.

**Comment by krisvasudevan** [comment]
@Akasurde  I did use that document to create this request. Could you please elaborate on what the issue is?

**Comment by Akasurde** [comment]
You are using `upstream/devel` as base branch instead of `upstream/stable-2.9`. That's how it got these many files in the given PR.

**Comment by sugitk** [comment]
@krisvasudevan 
Do you have a plan to recreate this backport PR for stable-2.9?

**Pull request closed without merging**
