### PR TITLE
r_package 

### PR DESCRIPTION
**Pull request by evandam**
##### SUMMARY

Created an `r_package` module for managing packages for the R language.

This is meant to mimic other packaging modules like `pip` as closely as possible to stay consistent, with some slight changes that come with the R language, like changing the repo to install from, and specifying a custom directory to save packages to.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

r_package
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (r_pkg b9a261f811) last updated 2018/11/04 13:20:19 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/evan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/evan/ansible-devel/lib/ansible
  executable location = /home/evan/ansible-devel/bin/ansible
  python version = 3.6.6 (default, Sep 12 2018, 18:26:19) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### ADDITIONAL INFORMATION

R must first be installed on the system to use this module. For Ubuntu/Debian, `apt install r-base` should be enough to get started. By default, installs must be done by root, but specifying a `lib` allows you to install to any directory (ex: a home directory).

Example playbook `testmod.yml`:
```yml
- hosts: localhost
  become: true
  tasks:
  - name: Install dplyr
    r_package:
      name: dplyr
      state: present
      executable: /usr/bin/R
  - name: Force dplyr to be reinstalled
    r_package:
      name: dplyr
      force: true
  - name: Try to install dplyr again
    r_package:
      name: dplyr
      state: present
  - name: Install dplyr from the cloud CRAN mirror to your home lib
    r_package:
      name: dplyr
      repo: https://cloud.r-project.org/
      lib: "/tmp"
  - name: Uninstall dplyr from /tmp
    r_package:
      name: dplyr
      state: absent
      lib: "/tmp"
  - name: Install h2o from source
    r_package:
      name: h2o
      type: source
      repo: http://h2o-release.s3.amazonaws.com/h2o/latest_stable_R
```
Setup and run:
```bash
sudo apt install -y r-base
ansible-playbook -K testmod.yml
```

```paste below
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [localhost]

TASK [Install dplyr] ********************************************************************************************************************************************************************
changed: [localhost]

TASK [Force dplyr to be reinstalled] ****************************************************************************************************************************************************
changed: [localhost]

TASK [Try to install dplyr again] *******************************************************************************************************************************************************
ok: [localhost]

TASK [Install dplyr from the cloud CRAN mirror to your home lib] ************************************************************************************************************************
changed: [localhost]

TASK [Uninstall dplyr from /tmp] ********************************************************************************************************************************************************
changed: [localhost]

TASK [Install h2o from source] **********************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ******************************************************************************************************************************************************************************
localhost                  : ok=7    changed=5    unreachable=0    failed=0    skipped=0

```

### CODE REVIEW

**Comment by rgelber** [comment]
Could you build another definition to handle package versions? 

Example:
- hosts: localhost
  become: true
  tasks:
  - name: Install dplyr
    r_package:
      name: dplyr
      version: 2.3.1
      state: present

**Comment by evandam** [comment]
@rgelber, I was thinking about this and would definitely like to accomodate it. However, this requires first installing the devtools package before we could run commands like `install_version`. Would it be reasonable to just go with the assumption that the machine already has devtools first?

**Comment by rgelber** [comment]
@evandam, I know I would greatly appreciate a version control feature! Haha. That's how I found this PR in the first place! With that said, I'm sure most others would enjoy some sort of version control feature as well. Anyhow, you could update this python script to execute a check when someone tires to use the "version" parameter in ansible then during a playbook run notify the user that the "version" parameter will only work if devtools has been installed.

**Comment by evandam** [comment]
@rgelber, good point - definitely worth having! I'm not much of an R programmer but the most recent code I pushed (ignoring my mangled git rebase) should allow for specifying a version, along with `state: latest`. 

Also worth figuring out what kinds of extra options are worth including, like `lib.loc`, installing from GitHub, etc.

**Pull request closed without merging**
