### PR TITLE
Adding new module netconf_set

### PR DESCRIPTION
**Pull request by wisotzky**
##### SUMMARY
Provides a module to simplify NETCONF edit-config operation. This module is aligned with the module attributes used in the new netconf-get and netconf-rpc.

It is seen as reasonable candidate to deprecate the current netconf-config module.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
netconf_set

##### ANSIBLE VERSION
```
2.6.0
```

##### ADDITIONAL INFORMATION
```
Changes introduced compared to the existing "netconf_config" module:
- streamlined attributes (no control, which datastore to use)
- refactored to only use connection=netconf (same as other netconf modules)
- option to dry-run, to be used for auditing
- option to save a backup
- option to include differences in the result
- provide content in YAML/JSON or XML format (with xmlns control)
- align lock-option with other modules
```

### CODE REVIEW

**Comment by wisotzky** [comment]
This PR is to fulfill the requirements on `netconf-config` as discussed in [Issue 104](https://github.com/ansible/proposals/issues/104).

It does **NOT** contain the proposed `copy` and `delete` operations, as I don't agree on the strategy combining it all in one single module. Ability to specify the target datastore has been removed, as the new module will now only select candidate or running based on the nodal capabilities. If there is a need, to do specific changes just to running even candidate is supported, users may use the arbitrary netconf_rpc module, providing full/flexible access.

**Comment by wisotzky** [comment]
Please note, there is currently a bug with the option `validate`. This is unlikely related to this Ansible module but to the underlying NETCONF connector infrastructure. Needs to be revisited.

**Comment by wisotzky** [comment]
@ganeshrn @gundalow @privateip 

How to proceed on this one? Have you tried this out against Cisco/Juniper nodes? Or shall the code be really merged with the existing `netconf_config` module. As discussed earlier, using `netconf_get` and `netconf_set` make it technical more reasonable.

I am presenting at a conference week after next week, and would like to setup a demo/tutorial for those new NETCONF modules in Ansible. I would appreciate to have finalized view on `netconf_set`.

Once I am back from my travels, I will do some prototyping around RESTCONF and gNMI modules. Just for curiosity would be good to understand, if there is any attempt made in Ansible to provide dedicated connectors for this, like `connection=restconf` and `connection=gnmi`.

**Comment by ganeshrn** [comment]
@wisotzky As mentioned in issue https://github.com/ansible/ansible/issues/40650 we are discussing on idea of developing a `netconf` role in [ansible-network](https://github.com/ansible-network) and distribute it using [ansible galaxy](https://galaxy.ansible.com/ansible-network/). 

The role will have specific modules for each required Netconf operation and the tasks within role will achieve end to end functionality. So user who want more finer control and are well aware of Netconf can use this role. imo this module best fits in `netconf` role. 

@privateip Thoughts/Suggestions?

>  if there is any attempt made in Ansible to provide dedicated connectors for this, like connection=restconf and connection=gnmi

grpc connection type support is in our roadmap, for restconf there are no such plans as of now.

**Comment by wisotzky** [comment]
> grpc connection type support is in our roadmap

From my understanding, gRPC just defines transport/protocol specifics - while the actual API is defined in the .proto files. In contrast, OpenConfig gNMI defines the API - while gNMI 0.6 is the current version defined by google.

I'm not sure, how easy it is to build a program gRPC module - which is good enough to deal with different .proto's. Reasoning is, that in python you would need to build python files from proto files (called *_pb2.py). Also there is some effort to be spend to transform proto specific data type structures from/to python. So likely it is much easier to look into specific gRPC-based APIs (like gNMI) and to give it a start from there.

> for restconf there are no such plans as of now.

Technically the existing `uri` module can be used. But likely it is better for playbook authors to have something specific to RESTCONF. This would allow to provide more visibility, for example to set the `changed` attribute appropriately. It would be a good working assumption, to provide the same modules and attributes as for NETCONF - such as `restconf_set`, `restconf_get` and `restconf_rpc`.

**Comment by wisotzky** [comment]
> As mentioned in issue #40650 we are discussing on idea of developing a netconf role in ansible-network and distribute it using ansible galaxy.

I would still believe there is a value, of providing the base functionality (set, get, rpc) as part of regular Ansible modules. My pull request for a new Ansible module `netconf_set` is just the natural, streamlined evolution of the current `netconf_config` module. As discussed, if we don't want to have another overlapping module or naming "..._config" is desired as for other networking modules - I can also merge the code with the existing `netconf_config` module.

> The role will have specific modules for each required Netconf operation and the tasks within role will achieve end to end functionality. So user who want more finer control and are well aware of Netconf can use this role.

Following this logic, this would be best fit for dedicated NETCONF related tasks, like `copy-config`, `lock`, `unlock`, `get-schema`, `delete-config`, ... Those operations are tight into the specifics of rfc6241 - and playbook authors using them, need to understand those NETCONF fundamentals.

> imo this module best fits in netconf role.

Not really... My proposal for `netconf_set` is a different beast. It is focussing on changing the device configuration - with options to dry run/audit and backup the current configuration. It elegantly combines multiple NETCONF requests - so the playbook author does not need to care about NETCONF protocol specifics. So it perfectly does NOT belong into a netconf role as you've proposed.

**Comment by ganeshrn** [comment]
>  It is really focussing on changing the device configuration - with options to dry run/audit and backup the current configuration.

If the dry run ability you mentioned in your comment is related to `mode ` option in this PR, in that case, this option is not required in first place. Ansible inherently supports dry run https://docs.ansible.com/ansible/2.4/playbooks_checkmode.html. The logic of handling the dry run and diff needs to be added in the module. Other features like backup are subset of what is mentioned in [netconf proposal](https://docs.ansible.com/ansible/2.4/playbooks_checkmode.html)

**Comment by wisotzky** [comment]
@ganeshrn 

Thanks for providing those references to the common `dry run` and `diff` behavior. I was not aware about this. Could you please provide me a reference to a network module, which has implemented this options? I am happy to update this module accordingly.

I am still wondering, if this `--check` option is good enough. As I've mentioned, you could also use this for auditing to check if the desired configuration is in place (together with other checks, such as operational states and statistics).

> Other features like backup are subset of what is mentioned in netconf proposal

That's the reason, I've added this to the new module...

As I've mentioned, according to your proposal a lot of attributes are renamed/changed in `netconf_config`. This leads to a significant increase of complexity when we want to continue the existing functionality/attributes for compatibility. So that's why I still do believe, that my `netconf_set` is the better option.

**Comment by ganeshrn** [comment]
> As I've mentioned, according to your proposal a lot of attributes are renamed/changed in netconf_config. This leads to a significant increase of complexity when we want to continue the existing functionality/attributes for compatibility. So that's why I still do believe, that my netconf_set is the better option.

Adding a new module with enhancement over existing module just because deprecating options in current module increases code complexity is not the right approach for Ansible module development. Hence we cannot accept this module which duplicates functionality of existing module

I agree that deprecating certain option will slightly increase the complexity but it won't make module unmaintainable. The right approach here is to add enhancement to existing module while refactoring it in such a way that deprecated  code is easier to remove in future.

The module in this PR covers most of the functionality described in [proposal #104](https://github.com/ansible/proposals/issues/104) and even more. The only options left out are `copy` and `delete` which imo are very easy to support in `netconf_config`  module itself.

Based on above discussion I suggest you to raise a PR to enchance `netconf_config` itself and deprecate required options. 
If you don't have cycles for this, I will work on `netconf_config` refactor and you can review and test the PR in your enviornment.

**Comment by wisotzky** [comment]
Okay, let me work on this... Will get back to you soon!
/wiso

**Comment by ganeshrn** [comment]
Fixed by https://github.com/ansible/ansible/pull/44379

**Pull request closed without merging**
