### PR TITLE
aws_ssm_parameter_store - Make the module idempotent

### PR DESCRIPTION
**Pull request by nathanwebsterdotme**
##### SUMMARY
Changes to make the module idempotent.  Currently, a new version of the parameter will be stored every time the playbook is ran, even if nothing has changed which isn't idempotent and causes unnecessary versions to be created.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
aws_ssm_parameter_store

##### ANSIBLE VERSION
```
ansible 2.5.0b1 (stable-2.5 a7a03bbf4a) last updated 2018/02/15 17:54:35 (GMT +100)
```

##### ADDITIONAL INFORMATION

Before:
```
⇒  ansible-playbook -vv current_module.yml

PLAYBOOK: current_module.yml ***********************************************************************************************************************************************************************************
1 plays in current_module.yml

PLAY [Current Module] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]
META: ran handlers

TASK [Manage keys in AWS Parameter store] **********************************************************************************************************************************************************************
changed: [localhost] => (item={'name': 'test_name', 'value': 'test_value', 'description': 'test_description', 'string_type': 'String', 'overwrite': 'true'}) => {"changed": true, "item": {"description": "test_description", "name": "test_name", "overwrite": "true", "string_type": "String", "value": "test_value"}, "response": {"ResponseMetadata": {"HTTPHeaders": {"content-length": "13", "content-type": "application/x-amz-json-1.1", "date": "Thu, 15 Feb 2018 18:04:34 GMT", "x-amzn-requestid": "adbd1448-127a-11e8-b547-ff682365b6d1"}, "HTTPStatusCode": 200, "RequestId": "adbd1448-127a-11e8-b547-ff682365b6d1", "RetryAttempts": 0}, "Version": 1}}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0




⇒  ansible-playbook -vv current_module.yml

PLAYBOOK: current_module.yml ***********************************************************************************************************************************************************************************
1 plays in current_module.yml

PLAY [Current Module] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]
META: ran handlers

TASK [Manage keys in AWS Parameter store] **********************************************************************************************************************************************************************
changed: [localhost] => (item={'name': 'test_name', 'value': 'test_value', 'description': 'test_description', 'string_type': 'String', 'overwrite': 'true'}) => {"changed": true, "item": {"description": "test_description", "name": "test_name", "overwrite": "true", "string_type": "String", "value": "test_value"}, "response": {"ResponseMetadata": {"HTTPHeaders": {"content-length": "13", "content-type": "application/x-amz-json-1.1", "date": "Thu, 15 Feb 2018 18:04:39 GMT", "x-amzn-requestid": "b112f5cb-127a-11e8-bdee-8f7444e0535d"}, "HTTPStatusCode": 200, "RequestId": "b112f5cb-127a-11e8-bdee-8f7444e0535d", "RetryAttempts": 0}, "Version": 2}}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

After:
```
⇒  ansible-playbook -vv working_idempotence.yml

PLAYBOOK: working_idempotence.yml ******************************************************************************************************************************************************************************
1 plays in working_idempotence.yml

PLAY [Working SSM Idempotence] *********************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]
META: ran handlers

TASK [Manage keys in AWS Parameter store] **********************************************************************************************************************************************************************
changed: [localhost] => (item={'name': 'test_name', 'value': 'test_value', 'description': 'test_description', 'string_type': 'String', 'overwrite': 'true'}) => {"changed": true, "item": {"description": "test_description", "name": "test_name", "overwrite": "true", "string_type": "String", "value": "test_value"}, "response": {"ResponseMetadata": {"HTTPHeaders": {"content-length": "13", "content-type": "application/x-amz-json-1.1", "date": "Thu, 15 Feb 2018 18:00:09 GMT", "x-amzn-requestid": "105e5e50-127a-11e8-8efa-3745e3a9736d"}, "HTTPStatusCode": 200, "RequestId": "105e5e50-127a-11e8-8efa-3745e3a9736d", "RetryAttempts": 0}, "Version": 1}}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0



⇒  ansible-playbook -vv working_idempotence.yml

PLAYBOOK: working_idempotence.yml ******************************************************************************************************************************************************************************
1 plays in working_idempotence.yml

PLAY [Working SSM Idempotence] *********************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]
META: ran handlers

TASK [Manage keys in AWS Parameter store] **********************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'test_name', 'value': 'test_value', 'description': 'test_description', 'string_type': 'String', 'overwrite': 'true'}) => {"changed": false, "item": {"description": "test_description", "name": "test_name", "overwrite": "true", "string_type": "String", "value": "test_value"}, "response": {}}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by mikedlr** [comment]
I'd propose making the idempotent behaviour default.  Starting a discussion on Freenode / #ansible-devel.  Please join if you want input.  I will report back the result.

**Comment by mikedlr** [comment]
This was taken to #ansible-devel and those present agreed that there should be a default to update idempotently and a flag on the module with the three options never/changed/always, for example

```
overwrite_value: never|changed|always
```

@samdoran could you please do it that way rather than making the idempotent action a thing that has to be explicitly asked for.  

```
14:26:04 M<mikedlr> I'm looking at sdoran's PR -  https://github.com/ansible/ansible/pull/36252 - for aws_ssm_parameter_store to make it idempotent.  
14:26:27 M<mikedlr> Although it's a bit of an interface change, I'd like to propose that idempotent behaviour should be made the default.
14:26:41 M<mikedlr> let's deprecate the 'overwrite' argument and, perhaps, create a 'no_update' argument instead which would not update an existing value.
14:27:01 M<mikedlr> since it's a new module in preview during 2.5, the best time to make interface changes is now, before 2.6.
14:27:52 M<mikedlr> sdoran: would you be okay changing it like that? 
14:28:38 M<mikedlr> ryansb / shertel / willthames are you okay with us announcing the overwrite argument as deprecated?
14:40:06 S<@sdoran> I’m in favor of it.
14:40:31 S<@sdoran> And since it’s in preview, changing the interface is ok at this point.
14:41:58 S<@sdoran> Rather than `no_update`, how about `update` or `force`?
14:43:59 → jchristi[m] joined  ⇐ ShekharReddy and @akasurde quit  
14:58:24 M<mikedlr> so default is: update if changed;  if I do 'force: true' it will update no matter what.  The question is how to do "don't update if there is already a value"?
14:59:08 M<mikedlr> sdoran: that's useful in password lookups (which is basically what the parameter store is often to be used for) to set a password if there is none, but keep the current one if already set.  
15:00:20 M<mikedlr> might be better  'update: if_changed' (default) and 'update: force' and 'update: never' as alternative options?
15:01:02 M<mikedlr> BTW; I'm planning to copy any paste this conversation to the ticket;  if anyone objects please tell.  
15:12:34 R<@ryansb> update_existing: false might be a good flag for the old behavior
15:12:37 R<@ryansb> sound reasonable?
15:14:24 M<mikedlr> ryansb: the current behavior is apparently to update no matter creating many (identical) versions of the same parameter - n.b. ssm parameter store records version history
15:14:48 R<@ryansb> hm, is there a limit on max version
15:14:50 M<mikedlr> so that would really be "update_existing: force" or something 
15:15:28 M<mikedlr> ryansb: almost certainly.  do you think that means we can call it a bug and fix it in this version ;-) ?? 
15:16:34 M<mikedlr> max history for parameter - 100 past values
15:17:28 M<mikedlr> not sure what happens when you hit the limit - overwrite or block updates??
15:17:59 M<mikedlr> https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_ssm
15:20:13 R<@ryansb> hm. Time for Science
15:20:17 R<@ryansb> Lemme test
15:29:55 R— @ryansb waits for playbook to make a jillion versions of a secret
15:33:52 R<@ryansb> hm, so old versions just silently disappear
15:34:30 R<@ryansb> so the limit isn't a hard "you must delete one old one" type limit like IAM Policy Versions
15:34:49 R<@ryansb> anyway, go ahead and paste this convo on the PR, and I'll review it as well
15:42:02 M<mikedlr> so ryansb / sdoran in that case I think that it's not bad enough to break the code freeze, but I think that it's bad enough to change in the next version. 
15:42:26 R<@ryansb> still need to review it, but yes that's likely
15:42:41 M<mikedlr> silently deleting is bad because it can hide a password change from the past 
15:43:24 R<@ryansb> so if we *only* overwrite when the value is different
15:43:28 M<mikedlr> so again there are three options - 1) never update 2) update if changed 3) always update 
15:43:50 R<@ryansb> you would lose less, because then you'd have to actually alter the value 100 times
15:43:54 R<@ryansb> not just run Ansible 100 times
15:44:19 M<mikedlr> I think 2 should be default and both 1 and 3 should be available and so an update argument allowing each of never/changed/always would be the idea. 
15:44:59 M<mikedlr> it also becomes obviously a deliberate/ malicious thing rather than an easily explained tool fault 
15:50:28 R<@ryansb> what's obviously malicious?
15:51:35 M<mikedlr> if you give 100 different passwords or if you run 100 times with update: forced then you are more clearly trying to clear your history and it looks suspicious.
15:51:47 R<@ryansb> I see, yeah
15:51:53 M<mikedlr> if you just run ansible 100 times setting the password to the correct one, that's normal.  
15:52:18 R<@ryansb> in my experience with the policies & such, 5 versions is pretty much all you should need of different things
15:52:38 R<@ryansb> 100-secret history is a bit gratuitous
15:52:49 R<@ryansb> so if you're exhausting it, I'd argue you probably aren't using it right
15:52:55 R<@ryansb> or there's a malicious something up
15:53:40 M<mikedlr> we use write only password values;  you might do that giving some staff access to the encrypted but not unencrypted values.  
15:54:34 M<mikedlr> then they could set the password to one they know, log in to a system they should only have automated access to, do bad things , then revert the password to the normal one
15:55:22 R<@ryansb> hm. so in that case, the history shows you something is going on
15:55:32 M<mikedlr> if there's only five entries then they just set the password five times and it looks like a reasonable "trying to understand what ansible was doing" session.
15:56:05 M<mikedlr> if there are 100 entries and they overwrite them all then the history certainly suggests you should look a bit more carefully.
15:56:58 M<mikedlr> I guess that's the reason why the secret history is longer than, say, the IAM policy history.
15:57:54 M<mikedlr> ryansb: agreed on the never/changed/always naming or do you have a better one?  
15:58:14 R<@ryansb> so like a flag
15:58:26 R<@ryansb> `overwrite_value: never|changed|always`
15:58:33 R<@ryansb> on the module
15:58:41 M<mikedlr> yes; 
15:58:57 M<mikedlr> with a default to "changed"
15:59:16 R<@ryansb> Yeah, I'm good with that
16:00:33 M<mikedlr> I think in the end I prefer overwrite_value to update_existing as a name for the flag.  
16:01:43 R<@ryansb> whatever you think is clearer, I'm not married to either
16:02:22 M<mikedlr> sdoran is doing the PR so he gets to choose :-) 
```

**Comment by nathanwebsterdotme** [comment]
@samdoran @mikedlr changes done

**Comment by lukaszciechanowicz** [comment]
+1

@samdoran @mikedlr this one is required for us as well. Would be cool if we can get this done.

**Review by s-hertel — APPROVED** [review]

**Pull request merged**
