### PR TITLE
Date and Time filters.

### PR DESCRIPTION
**Pull request by sgargan**
##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME
filters

##### ANSIBLE VERSION

1.9

##### OS / ENVIRONMENT

All 

##### SUMMARY

Filters for manipulating dates and times in conditionals and variable expansions. The filters allow the parsing and comparison of dates and times along with simple date arithmetic based around python's timedelta. See the accompanying test file for examples.

### CODE REVIEW

**Comment by bcoca** [comment]
my only issue with this is the lack of timezone handling

**Comment by sgargan** [comment]
Brian,

You can pass in any formatter you like to parse the values and could use
this to parse out any timezone information available. Timezone handling is
fairly basic in the datetime library, as is the date arithmetic and I was
trying to avoid depending on a library like dateutil which has better
support. The filters could possibly run as is for basic use cases and
delegate to something like dateutil for better arithmetic and timezone
support. What do you think?

If you can suggest what you'd like to see them manipulate timezones I'll
definitely add it.

**Comment by bcoca** [comment]
pytz is the library that handles them correctly as python's datetime punts on correctly handling tzdata ... but I might just be over thinking this.

**Comment by amenonsen** [comment]
Sounds good. I like the idea of being able to do date manipulations without shelling out to date(1). I would certainly want some kind of TZ conversion/handling included. But I'm not going to review this in detail because there is no documentation.

**Comment by sivel** [comment]
@sgargan,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by einarc** [comment]
I've been using this and the first thing I've noticed is that it cannot handle the fields of ansible_date_time fact out of the box. It errors out on this line:
_convert_dateTime:

Line 117:

       raise errors.AnsibleFilterError("Date/time filters expect strings " \
                                   "not '%s' like '%s' " % (date_type, date))

**Comment by einarc** [comment]
Here's a simple test:
```
- name:  Calculate date
  set_fact: schedule_date="{{ansible_date_time.iso8601|string|in_future(1, "d")}}"
  ignore_errors: true

- debug: var=schedule_date 

- name:  Calculate Schedule date - hardcoded
  set_fact: schedule_date={{'2017-07-05T21:17:04Z'|in_future(1, "d")}}
  ignore_errors: true
```

Here's the output:
```


8057
TASK [deployNEW : Calculate Schedule date] *****************15:04:52
8058
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Date/time filters expect strings not '<class 'ansible.vars.unsafe_proxy.AnsibleUnsafeText'>' like '2017-07-05T22:04:40Z' "}
8059
...ignoring
8060
8061
TASK [deployNEW : debug] *******************************************************15:04:52
8062
ok: [localhost] => {
8063
    "schedule_date": "VARIABLE IS NOT DEFINED!"
8064
}
8065
8066
TASK [deployNEW : Calculate Schedule date - hardcoded] ************15:04:52
8067
ok: [localhost]
8068
8069
TASK [deployNEW : debug] *******************************************************15:04:52
8070
ok: [localhost] => {
8071
    "schedule_date": "2017-07-06 21:17:04"
8072
}
```

Your code is failing to detect ansible_date_time.iso8601 even though the format is listed under common_formats array.

IMHO it'll be better to get rid of the validation altogether as you can't possibly predict all possibilities and let the algorithm weed things out. Even if you're trying to save cycles by using validation of inputs, is better to say you're sorry than to ask for permission, as a manner of speaking.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.


Closing this since much of the functionality has already been implemented in parallel and we still need something that is more timezone aware. Please evaluate the current filters and see if you are interested in adding to it incrementally in a more targeted fashion.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourageopen dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
