### PR TITLE
Add tag verification test

### PR DESCRIPTION
**Pull request by pixelrebel**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

This tests the PR https://github.com/ansible/ansible-modules-core/pull/2654

### CODE REVIEW

**Comment by robinro** [comment]
@pixelrebel Thanks for the test!

Some suggestions:
- add gpg version dependence to not run on too old gpg version. Centos6 is 2.0.14. Implementation could be like the `git --version` call/when statements
- use a smaller example repository, git/git is quite large and it would be nice to have fast tests. Some separate repo with just 1 commits would do it.

**Comment by pixelrebel** [comment]
Hi @robinro, thanks for the suggestions.  I've addressed your second suggestion, but I'm not sure how to implement the gpg version dependence.  Can you please elaborate?

**Comment by robinro** [comment]
Use something like
https://github.com/pixelrebel/ansible/blob/57cbf0e27d5d3345a1ca31696cd3aa98196a4e6e/test/integration/roles/test_git/tasks/main.yml#L263
to only run `verify_commit` on git versions that support it

**Comment by pixelrebel** [comment]
Not familiar with shippable, the error states:
`It appears this job is running on Shippable instead of Travis.
Please rebase the branch used for this pull request.`

Tried rebasing, but that didn't help.  Suggestions?

**Comment by robinro** [comment]
your commits here are not rebased, you have to pull the new devel branch first

assuming you have a remote `origin` pointing to your repo and `ansible` pointing to the main one:

```
git checkout devel
git pull ansible devel # should be fast-forward
git checkout amc-pr2654
git rebase devel
git push -f
```

**Comment by pixelrebel** [comment]
@robinro Can you please offer some guidance on these four failures? The first set seems to be like gpg isn't installed (though I test for a minimum version).  The second set seems like ansible is not using my feature. 
787.11-12

```
2016-06-22 08:05:57 TASK [test_git : Import Jamie Evans GPG key] ***********************************
2016-06-22 08:05:57 fatal: [testhost]: FAILED! => {"changed": false, "cmd": "gpg --keyserver pgp.mit.edu --recv-key 61107C8E", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

787.13,16

```
2016-06-22 08:08:36 TASK [test_git : Import Jamie Evans GPG key] ***********************************
2016-06-22 08:08:36 changed: [testhost] => {"changed": true, "cmd": ["gpg", "--keyserver", "pgp.mit.edu", "--recv-key", "61107C8E"], "delta": "0:00:00.136265", "end": "2016-06-22 08:05:52.066719", "rc": 0, "start": "2016-06-22 08:05:51.930454", "stderr": "gpg: keyring `/root/.gnupg/secring.gpg' created\ngpg: keyring `/root/.gnupg/pubring.gpg' created\ngpg: requesting key 61107C8E from hkp server pgp.mit.edu\ngpg: /root/.gnupg/trustdb.gpg: trustdb created\ngpg: key 61107C8E: public key \"Jamie Evans <jamie@pixelrebel.com>\" imported\ngpg: no ultimately trusted keys found\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)", "stdout": "", "stdout_lines": [], "warnings": []}
2016-06-22 08:08:36 
2016-06-22 08:08:36 TASK [test_git : Copy ownertrust] **********************************************
2016-06-22 08:08:36 changed: [testhost] => {"changed": true, "checksum": "4cd2f9537b06d428b5796ee2e7f6662a2b1544b4", "dest": "/tmp/ownertrust-git.txt", "gid": 0, "group": "root", "md5sum": "22285cb590c34c25d4307885b8c050a6", "mode": "0644", "owner": "root", "size": 44, "src": "/root/.ansible/tmp/ansible-tmp-1466582752.31-279567870194170/source", "state": "file", "uid": 0}
2016-06-22 08:08:36 
2016-06-22 08:08:38 TASK [test_git : Import ownertrust] ********************************************
2016-06-22 08:08:38 changed: [testhost] => {"changed": true, "cmd": ["gpg", "--import-ownertrust", "/tmp/ownertrust-git.txt"], "delta": "0:00:00.033786", "end": "2016-06-22 08:05:52.704147", "rc": 0, "start": "2016-06-22 08:05:52.670361", "stderr": "gpg: inserting ownertrust of 6", "stdout": "", "stdout_lines": [], "warnings": []}
2016-06-22 08:08:38 
2016-06-22 08:08:38 TASK [test_git : Clone signed repo and verify tag] *****************************
2016-06-22 08:08:38 fatal: [testhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to verify GPG signature of commit/tag \"v0.0\"", "rc": 1, "stderr": "error: v0.0: cannot verify a non-commit object of type tag.\n", "stdout": "", "stdout_lines": []}
```

**Comment by robinro** [comment]
@pixelrebel 

I don't know why the first error happens. You can run the docker image manually and execute your command by hand to get more information:
`docker run -it ansible/ansible:fedora-rawhide /bin/bash`

Regarding the second error:
Since your PR to add tag verification is not merged yet, these tests won't pass on shipable. Try to run them locally with both PRs merged and make sure they pass there. Once your ansible-modules-core PR is merged, the tests should be rerun and turn green.

**Comment by pixelrebel** [comment]
Thanks @robinro.  Looks like the first problem was that gpg wasn't installed and I incorrectly assumed `version_compare` could evaluate an empty string.  That's now fixed.  

I think I've taken it as far as I can, let me know if anything else is needed to proceed with the merge.

**Comment by abadger** [comment]
Thanks @pixelrebel for the tests and @robinro for prompting me to look at merging this.  I rebased and merged the tests to go along with the fix to the module itself.  The changes are in the devel and stable-2.2 branches.  It will either make it into 2.2.0 or 2.2.1 depending on whether we need to make a 2.2.0rc3 for any major bugs.

**Pull request closed without merging**
