### PR TITLE
Fix WebRequest init failing in win_get_url when Credentials are specified

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
The implementation uses a mix of WebClient subclass and WebRequest, and the CheckModified-File function attempts to set the Credentials property on an uninitialized instance probably a leftover from refactoring. 

The change simply uses the correct variable name to initialize the Credentials property on the WebRequest instance.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_get_url

##### ANSIBLE VERSION
```
ansible 2.6.0dev0 (devel 39cc8ff7e7) last updated 2018/05/23 23:15:43 (GMT -400)
  config file = /Users/gnadaban/.ansible.cfg
  configured module search path = [u'/Users/gnadaban/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gnadaban/dev/src/github/ansible/lib/ansible
  executable location = /Users/gnadaban/dev/src/github/ansible/bin/ansible
  python version = 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### ADDITIONAL INFORMATION

Actual output:

```
TASK [downloads : Download binaries] *****************************************************************************************************************************************************
failed: [localhost] (item={u'src': u'http://<artifactory_url_redacted>/NDP451-KB2858728-x86-x64-AllOS-ENU.exe', u'name': u'dotnet451.exe'}) => {"changed": false, "item": {"name": "dotnet451.exe", "src": "http://<artifactory_url_redacted>/NDP451-KB2858728-x86-x64-AllOS-ENU.exe"}, "module_stderr": "The property 'Credentials' cannot be found on this object. Verify that the property exists and can be set.\r\nAt line:67 char:13\r\n+             $extWebClient.Credentials = $credentials\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : PropertyNotFound\r\n \r\n\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

Expected output:
```
TASK [downloads : Download binaries] *****************************************************************************************************************************************************
ok: [localhost] => (item={u'src': u'http://<artifactory_url_redacted>/NDP451-KB2858728-x86-x64-AllOS-ENU.exe', u'name': u'dotnet451.exe'})
```

Reproduce with Credential specified, eg.:
```
- name: Download with auth
  win_get_url:
    url: "{{source}}"
    dest: "{{dest}}"
    url_username: "{{username}}"
    url_password: "{{password}}"
```

### CODE REVIEW

**Comment by ghost** [comment]
ready_for_review

**Comment by ghost** [comment]
@dagwieers This case is tricky to test as it requires an URL that expects authentication. However, the fix is very straightforward the underlying cause being a typo.

**Comment by jborean93** [comment]
Thanks @gyorgynadaban for finding and fixing this, this must have been my mistake when I added the FTP auth stuff as that had a previous issue.

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Backport PR for stable-2.5 https://github.com/ansible/ansible/pull/40642

**Comment by ghost** [comment]
@jborean93 No worries, it's my pleasure. ;)
Thanks for the quick turnaround!

**Pull request merged**
