### PR TITLE
Update mattermost.py

### PR DESCRIPTION
**Pull request by jgoos**
##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### SUMMARY

```

```

### CODE REVIEW

**Comment by sivel** [comment]
Commit messages should indicate what change was being made, as opposed to just "update mattermost.py".

Additionally, including a description of what the change is, directly in the pull request description (per the template) is also preferable.

**Comment by bjolivot** [comment]
As it's my mistake, I rewrote a full PR, thanks @jgoos :) 
duplicate_of #22017

**Comment by bjolivot** [comment]
could be closed
close_me

**Comment by jgoos** [comment]
@sivel thanks for the feedback, I'll do that next time

**Pull request closed without merging**
