### PR TITLE
Fix sanity checks in OpenStack docs fragment

### PR DESCRIPTION
**Pull request by ruizink**
##### SUMMARY
Fix sanity checks in OpenStack docs fragment

All OpenStack module PRs are failing sanity checks because they inherit from OpenStack docs fragment (see this [failed run](https://app.shippable.com/github/ansible/ansible/runs/55801/1/console)).
This PR makes the docs consistent with the implementation under  `lib/ansible/module_utils/openstack.py`, thus, fixing the sanity checks.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
OpenStack documentation fragment

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### ADDITIONAL INFORMATION
When running sanity checks against any OpenStack module, the test fails because of the inherited OpenStack documentation fragment.

Example of sanity checks failing against the `os_server_metadata` module from #19113:
```
test/sanity/validate-modules/validate-modules --format json --arg-spec lib/ansible/modules/cloud/openstack/os_server_metadata.py
```
Result:
```
{
    "lib/ansible/modules/cloud/openstack/os_server_metadata.py": {
        "warning_traces": [],
        "errors": [
            {
                "msg": "Value for \"default\" from the argument_spec (None) for \"auth_type\" does not match the documentation (u'password')",
                "column": 0,
                "line": 0,
                "code": 324
            },
            {
                "msg": "argument_spec for \"verify\" defines type=\"bool\" but documentation does not",
                "column": 0,
                "line": 0,
                "code": 325
            },
            {
                "msg": "Value for \"default\" from the argument_spec (None) for \"api_timeout\" does not match the documentation (u'None')",
                "column": 0,
                "line": 0,
                "code": 324
            },
            {
                "msg": "Value for \"default\" from the argument_spec (None) for \"key\" does not match the documentation (u'None')",
                "column": 0,
                "line": 0,
                "code": 324
            },
            {
                "msg": "Value for \"default\" from the argument_spec (None) for \"cert\" does not match the documentation (u'None')",
                "column": 0,
                "line": 0,
                "code": 324
            },
            {
                "msg": "Value for \"default\" from the argument_spec (None) for \"cacert\" does not match the documentation (u'None')",
                "column": 0,
                "line": 0,
                "code": 324
            },
            {
                "msg": "argument_spec for \"wait\" defines type=\"bool\" but documentation does not",
                "column": 0,
                "line": 0,
                "code": 325
            },
            {
                "msg": "Value for \"choices\" from the argument_spec ([]) for \"wait\" does not match the documentation ([u'yes', u'no'])",
                "column": 0,
                "line": 0,
                "code": 326
            }
        ],
        "traces": [],
        "warnings": []
    }
}
```
Expected result:
```
{}
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @mattclay @gundalow

**Comment by gundalow** [comment]
@ruizink Nice, thanks for looking at this. If you can remove the lines specified above from `test/sanity/validate-modules/ignore.txt` as they now pass that should resolve the issues.

Once fixed we will cherry-pick this into `stable-2.5`

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Thanks, merged into `devel` and cherry-picked into `stable-2.5` in https://github.com/ansible/ansible/pull/36733

**Comment by Akasurde** [comment]
@ruizink Thanks for contribution @gundalow Thanks for merge and cherry-pick.

**Pull request merged**
