### PR TITLE
Fix junos integration zuul CI failures

### PR DESCRIPTION
**Pull request by ganeshrn**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/netconf/__init__.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Review by pabelanger — APPROVED** [review]
Great, thanks

**Comment by danielmellado** [comment]
LGTM, let's unlock junos CI

**Review by danielmellado — APPROVED** [review]

**Review by trishnaguha — APPROVED** [review]

**Pull request merged**
