### PR TITLE
Fixes #5159 `file` module: Don't catch `SystemExit`

### LINKED ISSUE #5159: Incorrect output from `file` module when --check is used on absent directories
**How to reproduce:**
First create a directory on some random host:

``` bash
$ ansible test-host -i ansible.hosts -m file -a 'path=/tmp/randompath state=directory'
mymachine.domain.se | success >> {
    "changed": true, 
    "gid": 1007, 
    "group": "jens", 
    "mode": "0755", 
    "owner": "jens", 
    "path": "/tmp/randompath", 
    "size": 4096, 
    "state": "directory", 
    "uid": 1007
}
```

Then check if the directory would have been deleted (note `--check`):

``` bash
$ ansible test-host -i ansible.hosts --check -m file -a 'path=/tmp/randompath state=absent'
mymachine.domain.se | FAILED => failed to parse: {"changed": true}
{"msg": "rmtree failed", "changed": false}
```

**Expected output:**

``` bash
$ ansible test-host -i ansible.hosts --check -m file -a 'path=/tmp/randompath state=absent'

mymachine.domain.se | success >> {
    "changed": true
}
```

I have pull request for this that I'll submit separately.

### PR DESCRIPTION
**Pull request by JensRantil**
This fixes issue #5159.

### CODE REVIEW

**Comment by jctanner** [comment]
@JensRantil it would be nice to include the content of "e" in the exit message.

**Comment by JensRantil** [comment]
> @JensRantil it would be nice to include the content of "e" in the exit message.

@jctanner Good point. Absolutely. Is there a standard keyword for that? Will I need to translate `e` to a string before setting it as a parameter to `module.exit_json(...)`?

Also, maybe `module.fail_json(...)` is a better function to call?

**Comment by jctanner** [comment]
You can cast e to a string:

```
module.exit_json(msg="rmtree failed: %s" % str(e))
```

Yes, fail_json would be a better way to exit if there is a true exception.

**Comment by JensRantil** [comment]
@jctanner Fixed. Holler if you have any other corrections.

**Comment by jctanner** [comment]
@JensRantil thank you!

Tested with:

```
# prepatch, delete dir check
jtanner@u1304:~/issues/5159-file-directory-exception$ ansible -i inventory localhost --check -m file -a 'path=/tmp/foo state=absent'
localhost | FAILED => failed to parse: {"changed": true}
{"msg": "rmtree failed", "changed": false}

# directory owned by jtanner, remove as root
jtanner@u1304:~/issues/5159-file-directory-exception$ ansible -i inventory localhost --check -m file -a 'path=/tmp/foo state=absent'

localhost | success >> {
    "changed": true
}

# directory owned by root, delete as jtanner
jtanner@u1304:~/issues/5159-file-directory-exception$ ansible -i inventory localhost  -c local -m file -a 'path=/tmp/foo state=absent'
localhost | FAILED >> {
    "failed": true,
    "msg": "rmtree failed: [Errno 1] Operation not permitted: '/tmp/foo'"
}
```

**Pull request merged**
