### PR TITLE
Fix typo in huaweicloud utils

### PR DESCRIPTION
**Pull request by zhongjun2**
##### SUMMARY
minor typo fix

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/hwc_utils.py

##### ANSIBLE VERSION
ansible 2.8

### CODE REVIEW

**Comment by TommyLike** [comment]
shipit

**Comment by zhongjun2** [comment]
bot_status

**Comment by gundalow** [comment]
BOTMETA tester says:
```yaml
{
  "lib/ansible/module_utils/hwc_utils.py": {
    "assign": [
      "TommyLike",
      "edisonxiang",
      "freesky-edward",
      "niuzhenguo",
      "zengchen1024",
      "zhongjun2"
    ],
    "authors": [],
    "committers": [],
    "deprecated": false,
    "ignore": [],
    "labels": [
      "ansible",
      "cloud",
      "huawei",
      "hwc_utils",
      "lib",
      "module_utils"
    ],
    "maintainers": [
      "TommyLike",
      "edisonxiang",
      "freesky-edward",
      "niuzhenguo",
      "zengchen1024",
      "zhongjun2"
    ],
    "metadata": {},
    "name": "hwc_utils",
    "namespace": null,
    "namespace_maintainers": [],
    "notify": [
      "TommyLike",
      "edisonxiang",
      "freesky-edward",
      "niuzhenguo",
      "zengchen1024",
      "zhongjun2"
    ],
    "repo_filename": "lib/ansible/module_utils/hwc_utils.py",
    "subtopic": null,
    "supershipit": [],
    "support": "community",
    "supported_by": "community",
    "topic": null
  }
}
```
We can see owner_pr has been set, that's it

**Comment by gundalow** [comment]
bot_status

**Comment by gundalow** [comment]
Not sure why the bot isn't working correctly. Will investigate more later.

@zhongjun2 @TommyLike Thank you for the fix and review. Merged into `devel`

**Pull request merged**
