### PR TITLE
Add support to using list variables in the notify: keyword

### PR DESCRIPTION
**Pull request by lberruti**
```
vars:
    handlers_list:
      - foo
      - bar
tasks:
    - name: template configuration file
      template: src=template.j2 dest=/etc/foo.conf
      notify: '{{handlers_list}}'
```

Expected:
TASK: [template configuration file]

---

changed: [deb7.inter.nos]

NOTIFIED: [foo]

---

changed: [deb7.inter.nos]

NOTIFIED: [bar]

---

changed: [deb7.inter.nos]

Without this:
TASK: [template configuration file]

---

changed: [deb7.inter.nos]
ERROR: change handler (['foo', 'bar']) is not defined

### CODE REVIEW

**Comment by timruffles** [comment]
Nice feature - consistent alongside `with_items`

**Comment by pierrefevrier** [comment]
Hi, here is a nice feature I'd love to be integrated in master since I need it (I'm working for a telecommunication french operator). When do you plan to integrate this great addon ? Thanks by advice :)

**Comment by mpdehaan** [comment]
# Information Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We have some questions we'd like to know about before we can get this request queued up.   If you can help answer them, we'd greatly appreciate it:
- can you explain why there are multiple levels of template calls here (3, including the one in the loop)?   The template code does know how to be recursive, so this appears redundant to us.   Perhaps there is a reason we are not following.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by lberruti** [comment]
You are right! No need to multiple template calls. Now is fixed.

**Comment by lberruti** [comment]
Now It should work on devel.
@jimi-c Please, can you review my f9ed91f? It's related to 9a0f8f01.

**Comment by Gerst20051** [comment]
:+1:

**Comment by lberruti** [comment]
### Integration tests for notify with variable list.

```
make test_notify -C test/integration
```

It checks notifications with scalar and dict variables.
It tests the notification resolution use the correct priority on resolution of the variables.

### Improved the handler name resolution.

The variables combination in the handler name resolution has been
improved.

The "flag handler" block has been moved from run_task to
run_task_internal.
As a consequence, we can use all variables (by using
runner.get_inject_vars) in the handler name resolution (template
handler_name).

This should ensure correctness on variables resolution / precendence
(vars defined with extra_vars, role_vars, module_vars, host_vars, etc.)
when template handler_name.

This commit passes:

```
make tests
make test_notify -C test/integration
```

**Comment by lberruti** [comment]
Obsolete pr: v2 already supports. Closing.
Please see #11501 for integration tests.

**Pull request closed without merging**
