### PR TITLE
windows client support

### PR DESCRIPTION
**Pull request by shlomozippel**
Windows support for ansible client. The tests all pass on linux, but I only ran sanity tests on windows

### CODE REVIEW

**Comment by mpdehaan** [comment]
in queue for review for 1.1 (code basically feature frozen as we are
releasing 1.0 Friday)

thanks!

**Comment by mpdehaan** [comment]
Sorry to have not merged this quite yet, been busy :) ... planning on merging all outstanding pull requests this Saturday.

**Comment by shlomozippel** [comment]
No worries, take your time! Let me know if you want me to rebase before you
actually merge

**Comment by mpdehaan** [comment]
Quick question -- I don't particularly care for the imp load source stuff, nor do I like seeing ansible-playbook.py in the bin directory where it would mess with tab completion.

Can't we move the ansible playbook code into something like lib/ansible/cli for both (using git mv) and just import as normal from there?

**Comment by shlomozippel** [comment]
Hey - I am totally with you on both issues, but couldn't think of a better
way to solve (without touching the original ansible/ansible-playbook
scripts).

It still boils down to the problem on windows: multiprocessing doesn't work
on windows when attempted from a file without a .py extension. The best
solution would be to copy ansible -> ansible.py when installing on windows
and leave it as 'ansible' on other platforms.

Not sure which parts of the code you want to giv mv, or where you want to
import it from after.

Also, keep in mind that the windows-only .py files are conditionally
installed on windows only so they wont mess up tab completion on real OSs

**Comment by mpdehaan** [comment]
Can you point me to a bug about the 'windows doesn't work without the
python extension' parts?

**Comment by shlomozippel** [comment]
Below is simple code that shows the problem. imp.find_module doesn't work
with files with no extension. Renaming to test.py causes it to work. This
is why my first version simply duplicated the 'ansible.py' script, and the
second version used the imp.load_source hack - in both cases I simply
needed the functionality of the ansible script in a file with a .py
extension.

import multiprocessing

def worker():
    print 'Worker'
    return

if **name** == '**main**':
    p = multiprocessing.Process(target=worker)
    p.start()

---

c:\Projects\Test>c:\python27\python.exe test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python27\lib\multiprocessing\forking.py", line 373, in main
    prepare(preparation_data)
  File "c:\python27\lib\multiprocessing\forking.py", line 482, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named test

**Comment by mpdehaan** [comment]
per recent conversations, I am not sure we want to support this at this time.   Instructions to run under cygwin or equivalent may be more useful.

I appreciate the effort that went into this.

**Pull request closed without merging**
