### PR TITLE
postgresql_privs: bugfix of 27327 - incorrect views handling

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_privs: bugfix of [#27327](https://github.com/ansible/ansible/issues/27327), incorrect views handling

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by andytom** [comment]
LGTM, shipit

**Comment by Andersson007** [comment]
@andytom , thank you for reviewing!

**Comment by Andersson007** [comment]
@Akasurde , could you please look at this one

**Review by Akasurde — APPROVED** [review]
shipit

**Comment by Akasurde** [comment]
@Andersson007 Thanks for the contribution. @andytom Thanks for the review.

**Comment by Andersson007** [comment]
@Akasurde @andytom thanks!

**Pull request merged**
