### PR TITLE
Fix KeyError exceptions in GetLogs command

### LINKED ISSUE #59797: redfish_facts: GetLogs can raise KeyError
##### SUMMARY

The GetLogs command can raise a KeyError if any of the properties it tries to read are not present. The properties being gathered are not required, so it should not be an error condition for them to be absent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_facts.py
redfish_utils.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = $HOME/.ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/Development/git/ansible/lib/ansible
  executable location = $HOME/Development/git/ansible/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:26:36) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
[no output]
```

##### OS / ENVIRONMENT

Applies to Redfish OOB controllers.

##### STEPS TO REPRODUCE

Run the GetLogs commands against a Redfish service that does not include one or more of these properties in the `LogServices` resources:

- `Description` 
- `Name`
- `Created`
- `Message`
- `Severity`

```yaml
---
- hosts: myhosts
  connection: local
  name: Get Manager Logs
  gather_facts: False

  vars:
    datatype: Logs

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get Manager Logs
    redfish_facts:
      category: Manager
      command: GetLogs
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
```

##### EXPECTED RESULTS

Playbook runs without error

##### ACTUAL RESULTS

```paste below
redfish_utils.py, line 316, in get_logs KeyError: 'Created'
```

### PR DESCRIPTION
**Pull request by billdodd**
##### SUMMARY

Updated code in get_logs() to avoid KeyError exceptions for missing properties.

Fixes #59797 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

redfish_facts.py
redfish_utils.py

##### ADDITIONAL INFORMATION

**Before:**

```paste below
$ ansible-playbook -i myinventory.yml playbooks/manager/get_manager_logs.yml 

PLAY [Get Manager Logs] ********************************************************

TASK [Define output file] ******************************************************
included: $HOME/Development/DMTF/Ansible/playbooks/manager/create_output_file.yml for mockup-localstorage

TASK [Define timestamp] ********************************************************
ok: [mockup-localstorage]

TASK [Define file to place results] ********************************************
ok: [mockup-localstorage]

TASK [Create dropoff directory for host] ***************************************
 [WARNING]: Platform darwin on host mockup-localstorage is using the discovered
Python interpreter at /usr/bin/python, but future installation of another
Python interpreter could change this. See https://docs.ansible.com/ansible/deve
l/reference_appendices/interpreter_discovery.html for more information.

ok: [mockup-localstorage]

TASK [Get Manager Logs] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: u'Created'
fatal: [mockup-localstorage]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"$HOME/.ansible/tmp/ansible-tmp-1564593915.783411-52210883464624/AnsiballZ_redfish_facts.py\", line 125, in <module>\n    _ansiballz_main()\n  File \"$HOME/.ansible/tmp/ansible-tmp-1564593915.783411-52210883464624/AnsiballZ_redfish_facts.py\", line 117, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"$HOME/.ansible/tmp/ansible-tmp-1564593915.783411-52210883464624/AnsiballZ_redfish_facts.py\", line 54, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/26/d5906nfx0rv7mgclxymgp5rw0000gn/T/ansible_redfish_facts_payload_71z4Tm/__main__.py\", line 395, in <module>\n  File \"/var/folders/26/d5906nfx0rv7mgclxymgp5rw0000gn/T/ansible_redfish_facts_payload_71z4Tm/__main__.py\", line 388, in main\n  File \"/var/folders/26/d5906nfx0rv7mgclxymgp5rw0000gn/T/ansible_redfish_facts_payload_71z4Tm/ansible_redfish_facts_payload.zip/ansible/module_utils/redfish_utils.py\", line 308, in get_logs\nKeyError: u'Created'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
mockup-localstorage        : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```

**After:**

```paste below
$ ansible-playbook -i myinventory.yml playbooks/manager/get_manager_logs.yml 

PLAY [Get Manager Logs] ********************************************************

TASK [Define output file] ******************************************************
included: $HOME/Development/DMTF/Ansible/playbooks/manager/create_output_file.yml for mockup-localstorage

TASK [Define timestamp] ********************************************************
ok: [mockup-localstorage]

TASK [Define file to place results] ********************************************
ok: [mockup-localstorage]

TASK [Create dropoff directory for host] ***************************************
 [WARNING]: Platform darwin on host mockup-localstorage is using the discovered
Python interpreter at /usr/bin/python, but future installation of another
Python interpreter could change this. See https://docs.ansible.com/ansible/deve
l/reference_appendices/interpreter_discovery.html for more information.

ok: [mockup-localstorage]

TASK [Get Manager Logs] ********************************************************
ok: [mockup-localstorage]

TASK [Copy results to output file] *********************************************
changed: [mockup-localstorage]

PLAY RECAP *********************************************************************
mockup-localstorage        : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### CODE REVIEW

**Comment by billdodd** [comment]
ready_for_review

**Comment by mraineri** [comment]
It would be good to make changes to copy over other LogEntry properties, but skip over legacy related properties (EntryCode, SensorType, and SensorNumber).

**Comment by mraineri** [comment]
shipit

**Comment by gundalow** [comment]
rebuild_merge

Thanks all

**Pull request merged**
