### PR TITLE
Update digital_ocean_droplet.py

### PR DESCRIPTION
**Pull request by sahsu**
here's new term of `ssh_keys` from `SSH key (numeric) ID` and in fact it's fingerprint. correctly term so people can easily know how to do it.

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sahsu** [comment]
> The test `ansible-test sanity --test yamllint` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/yamllint.html)] failed with 1 error:
> 
> ```
> lib/ansible/modules/cloud/digital_ocean/digital_ocean_droplet.py:10:19: unparsable-with-libyaml: while scanning a plain scalar - found unexpected ':'
> ```
> 
> [click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

it should be fixed.

**Review by gundalow — APPROVED** [review]
Thanks!

**Comment by gundalow** [comment]
rebuilt_merge

**Comment by acozine** [comment]
rebuild_merge

**Pull request merged**
