### PR TITLE
Adds percent filter.

### PR DESCRIPTION
**Pull request by jsmartin**
```
- hosts: localhost
  tasks:
  - debug: msg="{{ 99 |percent(15) }}"
```

```
TASK: [debug msg="14.85"] *****************************************************
ok: [localhost] => {
    "msg": "14.85"
}
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
When adding a new filter, it's needed to also add documentation about the new filter and the version_added information for the filters section.  Can you add this?

Thanks!

**Comment by jsmartin** [comment]
Added docs.

**Comment by sivel** [comment]
Slightly curious as to why a filter is actually needed here.

Something like the following requires no additional code added to ansible and is actually shorter to type than invoking a filter:

```
- debug: msg="{{ 99 * 0.15 }}"
```

The above produces the same results.

**Comment by jsmartin** [comment]
Absolutely, that works as well.  Maybe the percent filter is redundant.  Probably easier to find in a search, but we could just add some docs show the above example.

**Comment by jimi-c** [comment]
Based on the above discussion I'm going to go ahead and close this. @jsmartin if you want, you can send a docs PR to add any documentation you feel would be helpful. Thanks!

**Pull request closed without merging**
