### PR TITLE
Improved and fixed the expiration options in system/user module

### PR DESCRIPTION
**Pull request by ppanczyk**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
user module

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 5475f3ee64) last updated 2017/01/24 07:26:49 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
I have done four changes. The first two are related to and based on [PR 2426 in ansible-modules-core](https://github.com/ansible/ansible-modules-core/pull/2426):
1. In exactly the same way as davidmaitland, I added option 'never' to be accepted as expire parameter.
2. In slightly different way, I implemented checking current expiry time. The difference is that David was expecting users to provide epoch time with midnight in UTC - any other value caused subsequent runs to return state "changed", even if nothing had been modified. My implementation calculates the value that is expected to be in the shadow file (days since 1.01.1970, in case of Linux), instead of comparing the epoch times themselves. Value returned by the module is still the epoch time, but recalculated to UTC midnight of the provided date.
3. I fixed time conversions - the reverse to time.gmtime() is not time.mktime() (which expects local time), but calendar.timegm(), as written in [Python doc](https://docs.python.org/2/library/time.html).
4. The implementation of account expiration on FreeBSD was probably buggy. I know that it's a feature PR, not bug PR, however I had to reimplement that functionality anyway. As [FreeBSD pw's manual](https://www.freebsd.org/cgi/man.cgi?pw(8)) says, "-e" parameter (both for useradd and usermod) expects either a date in format "dd-mmm-yy[yy]", or a UNIX timestamp. The relative format (currently implemented in the module) is "-e +nd," not just "-e n" (where n is a number of days from now). Correct implementation was even more simple than on Linux, as the timestamps could be used directly.

The change was tested using playbook presented below. Tests were performed on Debian, CentOS and FreeBSD.
```
---
- hosts: all
  tasks:
  - name: "create test user"
    user:
      name: testuser
      password: [...]
      groups: sudo
      append: yes
      expires: 1485300600
    register: user
  - debug:
      var: user
```
Before the change:
```
PLAY [all] ****************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************
ok: [jessie]

TASK [create test user] ****************************************************************************************************************************************************
changed: [jessie]

TASK [debug] **************************************************************************************************************************************************************************************
ok: [jessie] => {
    "user": {
        "append": true, 
        "changed": true, 
        "comment": "", 
        "group": 1021, 
        "groups": "sudo", 
        "home": "/home/testuser", 
        "move_home": false, 
        "name": "testuser", 
        "password": "NOT_LOGGING_PASSWORD", 
        "shell": "/bin/sh", 
        "state": "present", 
        "stderr": "usermod: no changes\n", 
        "uid": 1021
    }
}

PLAY RECAP ****************************************************************************************************************************************************************************************
jessie                     : ok=3    changed=1    unreachable=0    failed=0
```
After:
```
PLAY [all] ****************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************
ok: [jessie]

TASK [create test user] ***************************************************************************************************************************************************************************
ok: [jessie]

TASK [debug] **************************************************************************************************************************************************************************************
ok: [jessie] => {
    "user": {
        "append": true, 
        "changed": false, 
        "comment": "", 
        "expires": 1485216000, 
        "group": 1021, 
        "groups": "sudo", 
        "home": "/home/testuser", 
        "move_home": false, 
        "name": "testuser", 
        "password": "NOT_LOGGING_PASSWORD", 
        "shell": "/bin/sh", 
        "state": "present", 
        "uid": 1021
    }
}

PLAY RECAP ****************************************************************************************************************************************************************************************
jessie                     : ok=3    changed=0    unreachable=0    failed=0
```

As you can see, now the module does not run usermod if there's no need to do that. The UNIX time is rounded to the midnight of the given day (in UTC).

I have read the [module checklist](http://docs.ansible.com/ansible/dev_guide/developing_modules.html#module-checklist) and I believe my modifications meet these requirements (except return value documentation, but this module currently doesn't have this at all).

### CODE REVIEW

**Review by ryansb — APPROVED** [review]

**Comment by ppanczyk** [comment]
Reading my code again, I noticed that there might be a ValueError exception in user_expires() method, if something unexpected was in the shadow file. Just in case, I handled these exceptions.

**Comment by Akasurde** [comment]
@ppanczyk Could you please rebase this branch and we can take things forward ?

needs_info

**Comment by ppanczyk** [comment]
Rebased.

**Comment by Akasurde** [comment]
@ryansb Could you please take another look ?

**Comment by gundalow** [comment]
There was an issue in devel docs which has been fixed. I've triggered a run of CI on this PR

**Comment by samdoran** [comment]
The expiration feature was added in #39758, though it was done by using a negative number rather than the string `never`. This keeps the field validation and subsequent logic in the module more straightforward as we don't have to account for polymorphism on the expiration field.

The expiration timestamp fixes were implemented in #38885.

**Pull request closed without merging**
