### PR TITLE
univention udm_user: add parameter to control password update

### PR DESCRIPTION
**Pull request by keachi**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
udm\_user

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 76d563af79) last updated 2017/01/26 16:51:07 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Passwords are set only if they where None, this PR allows to update the password always.

### CODE REVIEW

**Comment by Qalthos** [comment]
Forgive me if I'm misunderstanding, but it looks like the current implementation already always updates the password, and you are adding a parameter to only set password if None via the `on_create` parameter, which seems to be the opposite of your PR's description. Do I have that right, or is there something else going on?

**Comment by keachi** [comment]
Oh, yes, I was confused on the time I wrote the PR. You are right, with this PR it is possible to update the password if it was None (a new account was created) or if `always` is defined.

**Comment by Qalthos** [comment]
Alright, just making sure my understanding was right.

Can you add `version_added: "2.3"` to the update_password documentation?

**Comment by keachi** [comment]
sure. done. thanks for reviewing.

**Pull request merged**
