### PR TITLE
add azure_rm_mariadbdatabase

### PR DESCRIPTION
**Pull request by techknowlogick**
##### SUMMARY
add azure_rm_mariadbdatabase module
Related PR #53998

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
azure_rm_mariadbdatabase

### CODE REVIEW

**Comment by Fred-sun** [comment]
@techknowlogick Thanks for your contribution. Have you finished the change? If it is completed, I will ping the community member for review!

**Review by zikalino — APPROVED** [review]
looks good!

**Comment by zikalino** [comment]
@techknowlogick do you plan to contribute any more modules?

**Comment by techknowlogick** [comment]
@zikalino The merged modules are all that I have planned to contribute. Maybe in future I will contribute more, but I have no specific plans to do so currently. Thanks again for your assistance in getting these merged.

**Pull request merged**
