### PR TITLE
Rename memset_*_facts to memset_*_info

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Continues #56822. The modules do not return `ansible_facts`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
memset_memstore_facts
memset_server_facts

### CODE REVIEW

**Comment by felixfontein** [comment]
FYI: this PR includes no new modules, it renames one module.

**Review by acozine — APPROVED** [review]
Docs changes look good.

**Comment by glitchcrab** [comment]
shipit

**Comment by felixfontein** [comment]
@acozine @glitchcrab thanks for reviewing this!

**Pull request merged**
