### PR TITLE
docker_logout: report change on successful logout

### LINKED ISSUE #59232: Docker logout reports no change even though it did something
##### SUMMARY
`docker_login` reports no change even though it logged out.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`docker_login`

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/raphael/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Client: Ubuntu 18.04 LTS 4.18.0-24-generic, ansible 2.8.1
Server: RHE7 3.10.0-957.21.3.el7.x86_64

##### STEPS TO REPRODUCE

```yaml
- name: Pull some Docker images 
  block:
  - name: Log into Harbor (Docker registry)
    docker_login:
        registry: "{{docker_registry}}"
        username: "{{harbor_user}}"
        password: "{{harbor_password}}"
        reauthorize: yes
  - name: Pull Docker images
    loop:
      - "some_image"
      - "other_image"
    docker_image:
      name: "{{ item }}"
      state: present
      source: pull
  always:
    - name: Docker logout
      docker_login:
        registry: "{{docker_registry}}"
        state: absent
```

##### EXPECTED RESULTS

Task `Docker logout` should report changes.

##### ACTUAL RESULTS

```paste below
TASK [gears : Log into Harbor (Docker registry)] 
<snip>
changed: [<snip>] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "api_version": "auto", 
            "ca_cert": null, 
            "client_cert": null, 
            "client_key": null, 
            "config_path": "/home/<snip>/.docker/config.json", 
            "debug": false, 
            "docker_host": "unix://var/run/docker.sock", 
            "email": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "reauthorize": true, 
            "registry": "<snip>", 
            "registry_url": "<snip>, 
            "ssl_version": null, 
            "state": "present", 
            "timeout": 60, 
            "tls": false, 
            "tls_hostname": "localhost", 
            "username": "<snip>", 
            "validate_certs": false
        }
    }, 
    "login_result": {
        "IdentityToken": "", 
        "Status": "Login Succeeded"
    }
}

<snip>
TASK [gears : Pull Docker images]
ok:
<snip>

TASK [gears : Docker logout]
<snip>
ok: [<snip>] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_version": "auto", 
            "ca_cert": null, 
            "client_cert": null, 
            "client_key": null, 
            "config_path": "/home/<snip>/.docker/config.json", 
            "debug": false, 
            "docker_host": "unix://var/run/docker.sock", 
            "email": null, 
            "password": null, 
            "reauthorize": false, 
            "registry": "<snip>", 
            "registry_url": "<snip>", 
            "ssl_version": null, 
            "state": "absent", 
            "timeout": 60, 
            "tls": false, 
            "tls_hostname": "localhost", 
            "username": null, 
            "validate_certs": false
        }
    }, 
    "login_result": {}
}
```

But, on that host:

```
$ cat .docker/config.json | grep auth
	"auths": {}
```

When I remove the logout task, the login appears in that output. So logout _is_ effective.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #59232.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_login

### CODE REVIEW

**Comment by felixfontein** [comment]
@reitzig since you are using the `docker_login` module, can you test whether this works and fixes the problem for you?

**Comment by reitzig** [comment]
Just from looking at the code, this doesn't seem right. If there was no login before, "successfully" logging out should _not_ be reported as a change.

**Comment by felixfontein** [comment]
According to https://github.com/docker/cli/blob/master/cli/command/registry/logout.go#L64 the message `Not logged in to %s` when there was no login to the given registry. So if that string is not in `stdout`, the user was logged out and `Removing login credentials for %s` is printed on `stdout`.

I've updated the PR so it looks for both strings, and output a warning if none of them is found. This is hopefully also easier to understand :)

**Comment by WojciechowskiPiotr** [comment]
Why not use the `self.results['actions']` to store logout result same as for `login()`?

**Comment by felixfontein** [comment]
@WojciechowskiPiotr do you mean as in 3a871a87b2079c2f6e1b4b458ba5e5698eb48dff ?

**Comment by WojciechowskiPiotr** [comment]
> @WojciechowskiPiotr do you mean as in [3a871a8](https://github.com/ansible/ansible/commit/3a871a87b2079c2f6e1b4b458ba5e5698eb48dff) ?

Yes, but instead of setting the `self.results['changed']`. The login action itself does not set the `self.results['changed']`, so why logout should?

**Comment by felixfontein** [comment]
@WojciechowskiPiotr it indirectly does, see `update_config_file`. (It doesn't in check mode, but that's another bug.)

Anyway, every module is supposed to set `changed` when it changes something. Logout wasn't doing that, and this PR fixes this bug. So not setting `changed` is not acceptable :)

**Comment by WojciechowskiPiotr** [comment]
Right, forgot about that.

**Review by resmo — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
Thanks everyone for reviewing and merging! I've created a backport PR (#60585).

**Pull request merged**
