### PR TITLE
Clean up Vault docs in User Guide.

### PR DESCRIPTION
**Pull request by direvus**
##### SUMMARY
Proofreading pass on the User Guide Vault docs.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docsite

##### ANSIBLE VERSION

```ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/brendanjurd/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### CODE REVIEW

**Comment by samccann** [comment]
From a documentation perspective this looks fine, but I don't want to merge until someone more knowledgeable responds on the b_pkey1 line to be sure.  @gundalow @ganeshrn @bcoca - do you know if that was a stray line or if it was supposed to mean something?

**Comment by direvus** [comment]
Thanks @samccann, I think that b_pkey1 refers to the internal variable b_key1 used in the actual Vault code, e.g.,  ansible/lib/ansible/parsing/vault/__init__.py L1169.  That is, it is the first 32 bytes of the "derived key".  Elsewhere in the same doc, this item is referred to as the "cipher key", so I went with that.

The whole section could probably use a rewrite, but I didn't want to bite off too much on my first pass.

**Comment by gundalow** [comment]
@samccann I think this is good to merge and backport to `stable-2.7`
I fixed a broken link and tweaked the formatting a bit

**Review by gundalow — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @direvus for improving the Vault documentation!

**Comment by direvus** [comment]
Cheers @samccann and @gundalow !

**Pull request merged**
