### PR TITLE
Extensive improvements to bigip_pool module

### PR DESCRIPTION
**Pull request by mhite**
The scope of the bigip_pool module has been expanded to include the ability to create/delete pools and modify/update key pool attributes. Specifically, you can now create a pool, associate health monitors, set the load balancing method, ramp times, and service down action via Ansible.

### CODE REVIEW

**Comment by srgvg** [comment]
In queue for testing at my place

**Comment by srgvg** [comment]
Hi @mhite,
- you need to keep the hashbang #!/usr/bin/python, 
- which you fixed later, but you should avoid those multiple commits
- the final merge commit will not be accepteable

You should basically rebase, not merge. Mail me in private if you need help with this git stuff.

**Comment by srgvg** [comment]
Just did some first tests, creating some nodes & pools, feeded directly from out live inventory and this works nicely.

Two remarks:
- a node can have a name: this should be added to the module, (possibly being used as the key when a hosts changes ip?); as we have over 800 hosts, it's nice to be able to check on the names; so basically adding a hostname parameter? When a name is not passe, the bigip uses the ip address as name.
- not sure if this should be qualified by a bug: there is a concurrency problem when doing a playbook that e.g. runs on two hosts that should be added to the same pool: as the pool module runs concurrently, it checks twice if the pool already exists, and at first both instances get a negative answer on that; then the bothe create the pool, each adding their host node to it, but as one of them will allways be exectuted by the bigip server first, the second bails out with an error mentioning the pool already exists:

```
failed: [mkros-on-1] => {"failed": true, "item": ""}
msg: received exception: Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/Pool::create_v2()
Exception: Common::OperationFailed
    primary_error_code   : 16908390 (0x01020066)
    secondary_error_code : 0
    error_string         : 01020066:3: The requested pool (/Common/VS-mkros-on-3052) already exists in partition Common.'
changed: [mkros-on-2]
```

You might want to catch this exception at pool creation, and ignore it?

**Comment by srgvg** [comment]
Settings state = absent removes the respective node; when no nodes are left in the pool, the pool doesn't get deleted. I thought I read somewhere this was the to be expected behaviour? If not, we have no ways to remove a pool?

**Comment by mpdehaan** [comment]
Also, can you please submit this (or force push) without merge commits?

Always do git pull --rebase vs git pull, or git rebase vs git merge.

If you resubmit please reference the previous ticket number in the comments.

**Comment by mhite** [comment]
@sergevanginderachter -- I will definitely reach out to about the rebase stuff. Thanks, I suck at git. 

Also, with regards to hostname. I think a good plan is to have an actual pool_member module which will let you manipulate pool member type objects. I would leave the ability to add/remove members to a pool in the bigip_pool module for backward compatibility but want to resist making this a module for manipulating pool attributes and pool member attributes. 

Good catch on the concurrency thing. I'll catch the specific exception and deal with it rather than bombing out.

As for state=absent, if you pass:

server=lb.mydomain.com user=admin password=mysecret state=absent name=matthite-pool partition=matthite host=1.1.1.1 port=80

this delete only 1.1.1.1:80 from the pool. It does not delete the pool. Is this your natural expectation?

server=lb.mydomain.com user=admin password=mysecret state=absent name=matthite-pool partition=matthite

will delete the pool.

Keep in mind that you can delete a non-empty pool -- in other words, the pool can be deleted without deleting all its pool members. You can not delete a pool if a virtual server is associated with it.

**Comment by mhite** [comment]
@mpdehaan -- Thanks, we'll get it sorted! Not really sure how to 'undo' what I've already messed up W.R.T. the git rebase issue but hopefully Serge has some ideas!

**Comment by srgvg** [comment]
- about the pool_member module: node name & address are node parameters, which is something different than pool members (node object + port); the latter is covered by the bigip_pool module, wouldn't we just need a bigip_node module then?
- so right now the state parameter has a double meaning, for the pool as documented, or for the node, if mentioned as a parameter?

**Comment by mhite** [comment]
@mpdehaan -- With the help of Serge, I've fixed this pull request so the merge commit is gone and the intermediate (minor) commits squashed.

**Comment by mhite** [comment]
@sergevanginderachter -- Behind the scenes (deep within the bowels of the F5 iControl API), when you create a pool or call the add member method, you pass a list of members. If a member isn't already defined as a node, a node is created. The name of the node is the IP address. You can not change or modify this node name. (You can, however, change its IP address). What you can do is add a descriptions to pool members. Obviously pool member descriptions are tied to a node's membership in a pool and don't follow a node.

If you really wanted to specify an alphanumeric name for a node (rather than the autogenerated one based on the IP address), the node would have to be explicitly created before the pool creation or add_member is called. I could work some logic into this module to create a node before adding it to a pool rather than depending on the autonaming functionality that the iControl add member and create pool calls offer. However, this may be better served with a bigip_node module as you allude to. 

Let me know your thoughts on that.

As for the state parameter having double meaning: correct.

If you include pool member information, the state is applied to the pool member and not the pool. If you do not include pool member information, the state is applied to the pool.

I would like to have a pool_member module that provides a full pool member interface, and either rip out the pool member stuff from the bigip_pool module or leave what minor functionality currently exists in for backward compatibility. Depending on what @mpdehaan thinks and/or his policy, it may be perfectly acceptable to rip it out and move it to a separate module.

**Comment by mhite** [comment]
The concurrency problem also existed for not just creating the pool, but also deleting it. I've addressed this in the other commit.

**Comment by mpdehaan** [comment]
I'm ok with merging these because the existing module already had overlap and we must keep compatibility.

Please add the version_added: "1.3" attribute on all new parameters please though.

Then this looks like this is good to merge in.

Thanks!

**Comment by mpdehaan** [comment]
Another thing in the examples

(A)  don't show the usr/bin/ansible examples, just show the playbook

(B)  break up long lines like so:

```
 foo: >
    bar=2
    baz=6
```

That way the very long lines are easier to read in the docs.

Thanks!

**Comment by srgvg** [comment]
@mhite found a small bug: monitor names should also be prepended by the Partition; if allways using the default Common partition this results in just non idempotent behaviour, but when other Partition type are used, this would result in unexpected behavior.

Possible fix:

``` diff
diff --git a/plays/library/bigip_pool b/plays/library/bigip_pool
index 36ca637..a900ebc 100644
--- a/plays/library/bigip_pool
+++ b/plays/library/bigip_pool
@@ -341,7 +341,9 @@ def main():
     if monitor_type:
         monitor_type = monitor_type.lower()
     quorum = module.params['quorum']
-    monitors = module.params['monitors']
+    monitors = []
+    for monitor in module.params['monitors']:
+        monitors.extend(['/%s/%s' % (partition, monitor)])
     slow_ramp_time = module.params['slow_ramp_time']
     service_down_action = module.params['service_down_action']
     if service_down_action:
```

**Comment by mhite** [comment]
@sergevanginderachter -- You need to specify the full path to the monitor. This is the intended usage.

I think I understand what you are hitting, though. Without sessions to iControl (current behavior), the current partition would be whatever partition the account credentials were last actively switched to using the iControl set partition API call. This really only comes up if you log into the web UI with the same credentials you use for automation or if you have other scripts that don't use sessions but change the active partition.

However, if you do use sessions when setting up the API connection, the BIG-IP will default to /Common since we are using the session functionality of iControl and all sessions begin in the /Common context. The trade off is that BIG-IPs only support a limited number of sessions per hour and you will quickly exhaust that since a new API connection is setup per host (due to the design of Ansible and its interaction with modules). I recommend NOT using sessions and just specify the full path to the monitor instead of depending on it to automatically default to /Common.

The partition argument is meant to specify the location of the pool (and pool member), ie. the object whose state is being manipulated.

I will add an additional parameter to enable sessions, but the default will be off. Additionally, I will clarify this in the documentation, in addition to the other documentation fix @mpdehaan requested.

Thanks for all the feedback!

**Comment by srgvg** [comment]
Hi Matt, I'm not sure I understand the topic of those sessions.

What about let the module default the same partition for the monitor as for the module, _if_ no partition was specified with the monitor? So if no partition is specified in the monitor, a default would be applied by the ansible module, and that session thing would not kick in when talking to the bigip api?

Something like this perhaps:

```
    for monitor in module.params['monitors']:
        if '/' not in monitor:
            monitors.extend(['/%s/%s' % (partition, monitor)])
```

**Comment by srgvg** [comment]
forgot to paste this:

```
        else:
            monitors.extend(['%s' % monitor])
```

**Comment by mhite** [comment]
@sergevanginderachter -- RE: sessions, we can discuss further via IRC/email. 

I've gone ahead and incorporated a similar solution to your suggestion, although I've fixed it up to not die if someone doesn't pass a monitors param. (You would get an iteration on NoneType error.)

**Comment by mhite** [comment]
Hopefully that should wrap up all the outstanding issues/requests.

**Comment by mhite** [comment]
@mpdehaan Let me know if there are any other outstanding issues. I'm not aware of any! Wanted to make sure we got this in before 1.3 closes. Thanks.

**Comment by srgvg** [comment]
+1

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
