### PR TITLE
[stable-2.5] Migrate from MySQLdb to PyMySQL (#40123)

### LINKED ISSUE #29887: mysql_* modules are implicitly Python3 incompatible
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
* mysql_* module

##### ANSIBLE VERSION
```
ansible 2.3.2.0 / master
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Python 3 target

##### SUMMARY
mysql_* modules always depend on `MySQLdb`, which does not support Python 3.
This inherently creates incompatibility with Python 3. Raising this as bug per [Python 3 support policy](https://docs.ansible.com/ansible/latest/python_3_support.html).

Possible solutions:
* switch all mysql_* modules to use PyMySQL all the time
* allow all mysql_* modules to use whatever MySQL driver is available (MySQLdb, PyMySQL, etc)

##### STEPS TO REPRODUCE
* use mysql_* module on a target host with Python 3

##### EXPECTED RESULTS
mysql_* modules should be able to use a Python 2/3-compatible drivers, such as PyMySQL

##### ACTUAL RESULTS
```
the python mysqldb module is required
```

### PR DESCRIPTION
**Pull request by DSpeichert**
* Migrate from MySQLdb to PyMySQL
* Deduplicate driver loading and failure message
* Explain requirements
* Apply requirements docs change to proxysql too
* Add changelog.
(cherry picked from commit d34cf93f1a7f96a14da1354b8f88a90c058e3e86)

Co-authored-by: Daniel Speichert <DSpeichert@users.noreply.github.com>

##### SUMMARY
Fixes #29887

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mysql_db

##### ANSIBLE VERSION
2.5

##### ADDITIONAL INFORMATION
Backport of #40123

### CODE REVIEW

**Review by odyssey4me — APPROVED** [review]

**Comment by nitzmahone** [comment]
(*EDIT* NM, after discussing with the other RMs and looking at the code, I see you're not "migrating" but adding a new option). This doesn't seem like a great candidate for a backport, since it will break every user of this module until they swap their deps. We try really hard not to make breaking changes like that in service releases unless it's something very drastic like a REST API that's been completely shut down, where the module will be totally non-functional going forward without a change like this... I don't think this falls into that category, so I'm going to close the backport PR.

**Comment by odyssey4me** [comment]
@nitzmahone It'll try pymysql first, then fall back to the old driver: https://github.com/ansible/ansible/pull/45982/files#diff-574ce10847bde8823e28af27d7cc3839

**Comment by nitzmahone** [comment]
Right, but the test deps always install the new driver, so after this change, nothing will test the old code path.. Right?

**Comment by nitzmahone** [comment]
Looks like RHEL still runs with the old dep, so I'm :+1: to go ahead and take this for 2.5.10.

**Pull request merged**
