### PR TITLE
assemble can now use src from master/origin

### PR DESCRIPTION
**Pull request by bcoca**
Not happy with this as it is a lot of copy and paste from original assemble and template modules, but now seems to work well enough for my needs. It took me less time to hack this to setup multiple copy tasks before the assemble tasks.

let me know what I can do to improve code reuse or any other way to improve this hack.

### CODE REVIEW

**Comment by mpdehaan** [comment]
So what new capabilities or bugfixes are resident in the above?

Thanks!

**Comment by mpdehaan** [comment]
can you share example playbook lines?

**Comment by bcoca** [comment]
of course, I should have added at least one example:

```
- hosts: nginx
  tasks:
   - name: Assemble nginx from local repo
     assemble: src=files/nginx/ dest=/etc/nginx.conf remote_src=False
```

**Comment by jctanner** [comment]
@bcoca looks good, thank you!

**Pull request merged**
