### PR TITLE
Add Carp network interface info for Facts Gathering in BSD.

### PR DESCRIPTION
**Pull request by GilgOuille**
##### SUMMARY
Add the support of CARP functionnality for Bsd Facts Gathering.
We can know directly the state MASTER / BACKUP of the interface.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
facts / network / bsd

##### ADDITIONAL INFORMATION
Example output with the hadoc command : ansible -m gather_facts my-host
```
        "ansible_myif1": {
            "carp": {
                "advbase": "1",
                "advskew": "1",
                "role": "MASTER",
                "vhid": "1"
            },
```

### CODE REVIEW

**Comment by nitzmahone** [comment]
This should probably be implemented in a BSD-specific collection, closing the core request.

**Comment by HerveMARTIN** [comment]
The fact is already BSD specific, so why not improving it?

**Comment by bcoca** [comment]
There are several reasons:
 - carp is not BSD specific (it did originate on BSD but it has been ported to other OSs, including linux)
 - The long term goal is to trim down the `setup` module and create several 'facts modules' that will make for easier selection and targeting of what the user wants from 'fact gathering'
 - `gather_facts` is now an action decoupled from `setup` module (though it still defaults to using it), this is part of the pursuit of the previous point
 - `gather_facts` can now execute several modules, by default in parallel, allowing for shortening what is now currently a very long task
 - To avoid lengthening an already very long duration we would like to avoid adding more to the 'serialized' fact gathering that is not crucial to most users (most machines are not set up to do IP failover)
 - The 'default' offering should try to keep parity across OS/distros if possible, it would mean adding carp and possibly other systems like heartbeat to the other OSs/distro paths
- The core team and the ansible-core project should not be gatekeepers and maintainers for most functionality, just the core language and the bare common minimum, specially of systems most are not familiar with (I happen to have used carp and BSD a lot, but most team members have not).
- By pushing things like these to collections we can have subject matter experts be the maintainers/gatekeepers and makes it a lot easier for needed changes to go through

I can go on and I'm leaving a few things out that are still more in planning than execution phase, but I hope the above is enough to explain our reasons for rejecting this PR, it is not that we think the new facts are a bad idea or badly implemented, it is just that we need to start pushing these things out of core and into their own collections.

**Comment by HerveMARTIN** [comment]
Understood, crystal clear ! Thanks for your answer.

**Pull request closed without merging**
