### PR TITLE
 New Module: snow_record_find - Search for multiple records from ServiceNow

### PR DESCRIPTION
**Pull request by garbled1**
##### SUMMARY
Search for multiple records from ServiceNow

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/notification/snow_record_find.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (snow_record_find 48163f4a7b) last updated 2017/08/09 01:49:52 (GMT +000)
  config file = None
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/ansible/lib/ansible
  executable location = /home/ec2-user/ansible/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```

##### ADDITIONAL INFORMATION
This module allows you to search for multiple records in ServiceNow, and return specific fields.  For example, one could search a given assignment group, for open incidents, and return the list of incident numbers.

```
- name: Search for incident assigned to group, return specific fields
  snow_search_records:
    username: ansible_test
    password: my_password
    instance: dev99999
    table: incident
    query_field: assignment_group
    query_string: d625dccec0a8016700a222a0f7900d06
    return_fields:
      - number
      - opened_at

ok: [localhost] => {
    "changed": false, 
    "instance": "dev38191", 
    "invocation": {
        "module_args": {
            "instance": "dev38191", 
            "max_records": 20, 
            "order_by": "-created_on", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "query_field": "assignment_group", 
            "query_string": "d625dccec0a8016700a222a0f7900d06", 
            "return_fields": [
                "number", 
                "opened_at"
            ], 
            "table": "incident", 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    }, 
    "max_records": 20, 
    "query_field": "assignment_group", 
    "query_string": "d625dccec0a8016700a222a0f7900d06", 
    "record": [
        {
            "number": "INC0000009", 
            "opened_at": "2017-03-12 22:50:23"
        }, 
        {
            "number": "INC0000024", 
            "opened_at": "2017-03-18 23:52:52"
        }, 
        {
            "number": "INC0000028", 
            "opened_at": "2017-02-26 23:58:00"
        }, 
        {
            "number": "INC0000035", 
            "opened_at": "2017-03-16 00:32:47"
        }, 
        {
            "number": "INC0000055", 
            "opened_at": "2017-05-16 04:47:23"
        }
    ], 
    "return_fields": [
        "number", 
        "opened_at"
    ], 
    "table": "incident"
}


```

### CODE REVIEW

**Comment by garbled1** [comment]
Added some code from @joaocpinto that allows for construction of complex queries against service-now.

**Comment by Jmainguy** [comment]
Not sure I understand why this would be in the notification name space, why do you believe this would be a good place for it? @garbled1

**Comment by garbled1** [comment]
It could be anywhere in theory.  The service now record create/modify/delete module is in notification, so it makes sense that they are co-located.

My general reasoning is that opening incident tickets, updating change records, tasks etc, are more or less a form of notification.  It's not a direct notification, like emailing someone, but it is a general notification of a type.  Yes, this module has alot more power than just opening a ticket, but it is the general use case for it.

**Comment by willybarro** [comment]
I agree with @Jmainguy, and this module shouldn't even be in the notification namespace.
We could move it to "inventory" namespace, or even create a new "itsm" namespace.

@bcoca Can you chime in with your opinion about the namespace change?

--
Besides that, I have only a single comment/review item. If that question's cleared, I'm good to approve it :)

**Comment by suryasr007** [comment]
Any update on this PR?

**Comment by Akasurde** [comment]
superseded by #58410

Module available in Ansible 2.9 release.

@garbled1 Thanks for the contribution.

**Pull request closed without merging**
