### PR TITLE
Add interfaces module

### PR DESCRIPTION
**Pull request by Apsu**
This module is for configuring the /etc/network/interfaces file on Debian-based systems. It provides somewhat basic functionality, covering all of the major essential directives for general network configuration, but more advanced features can be added later (such as bridges, vlans, bonds, multiple addresses without aliasing, etc).

As a precaution against stomping unrecognized directives, the module will log anything it ignores and provides the force parameter (default=no) to prevent/allow rewriting the file if anything was ignored. That said, comments are not considered "ignored" for force purposes, and are simply tossed entirely. Caveat emptor!

### CODE REVIEW

**Comment by resmo** [comment]
you added the host module in this PR. Don't think you wanted that ;) https://github.com/Apsu/ansible/commit/1bb82d17bcc1647a25f761df6fa25f980aab451a

**Comment by sivel** [comment]
It would be really sweet if this worked like the 'hostname' module (https://github.com/ansible/ansible/blob/devel/library/system/hostname)

Then it could be a little less specific to Debian/Ubuntu and be a single module for doing this on various OSes.

Just an idea.

**Comment by Apsu** [comment]
@resmo Indeed I did, but that was before I made this branch and removed the host module for this PR, as Apsu@349fc38 shows ;P The history is a little ugly, but the result is the same. If you like, I'll rebase and collapse it so it's less confusing.

**Comment by Apsu** [comment]
@sivel That would be pretty cool! There's a lot of varieties of "interface" type files that would have to support, however. It wouldn't be a huge hurdle to tackle Debian-ish and RHEL-ish, as a start, though. The latter is fairly simple files per interface, and updown stuff is in directories or other simple files. I'll consider it for future improvement, was hoping to start simple here (despite the module's complexity :P)

**Comment by mmoya** [comment]
Hi @Apsu What about using [mkstemp](http://docs.python.org/2/library/tempfile.html#tempfile.mkstemp) for creating the temporary interfaces file? It's recommended practice even when you're not writing to world-writable dir.

And yes, collapsing the PR and removing the merge commit would be nice. I bet upstream will ask you to do that.

**Comment by bcoca** [comment]
Modules can use the atomic_move function to safely put new files into place
(use mkstemp to create a temporary working file you can pass to atomic_move
to put in the final destination).

Using a constant name for the working file (interfaces.tmp) can lead to 2
simultaneous users of the same module on the same machine stepping over
each other (hopefully this is rare in all envs, but it does happen).

**Comment by Apsu** [comment]
Went ahead and rebased the commits to clean up the history; apparently I had unintentionally merged into my working branch from the remote's same branch, hence the ugly. @mmoya @bcoca I thought of that as well, and totally meant to clean that up before the PR. Good catch! I'll switch to atomic_move and commit the change soon.

**Comment by Apsu** [comment]
Any feedback on this? Anything else to do or change before it's acceptable?

**Comment by mpdehaan** [comment]
Apologies on getting to this one -- we've had quite a backlog and have been prioritizing tickets.

Ultimately, I feel we should not accept a module that just accepts Debian systems, though I know fully this could support more.

Obviously you can continue to use this module by putting it in a "./library" module alongside your playbook or configuring it in your library path via ansible.cfg.

I'm open to inclusion if this also handles Red Hat / Fedora / CentOS / derivatives.

**Comment by drybjed** [comment]
Anybody who's interested in an alternative to this module, I have created [interfaces](https://github.com/ginas/ginas/tree/master/playbooks/roles/interfaces) role which covers management of `/etc/network/interfaces` on Debian/Ubuntu systems.

**Pull request closed without merging**
