### PR TITLE
relative paths for (include/extends) in jinja2 templates

### PR DESCRIPTION
**Pull request by stijnopheide**
See issue #1244 for details

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good to me, in queue for testing probably tonight or tomorrow.  Thanks!

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by stijnopheide** [comment]
you're welcome!

**Comment by asymmetric** [comment]
Is this supposed to make actual relative paths work? I'd like to include a template, locating it by using `../partial.conf.j2`, from within a main template. But that doesn't seem to work.

Either the partials are both in the same directory, or I need to hardcode a path relative to the playbook.

**Comment by t2d** [comment]
@asymmetric I agree. Including from a subfolder of `templates/` works, but not from `../files/`.

**Pull request closed without merging**
