### PR TITLE
Fixing broken imports and get_exception for ipa

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

* Fix imports 
* Remove get_exception

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
/lib/ansible/modules/identity

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @abadger 
Let me know if you need anything.

**Comment by abadger** [comment]
Thanks @Akasurde the only problem I see with these changes are the lack of a Copyright header on some of these files.  (see what I wrote in https://github.com/ansible/ansible/pull/27629#discussion_r130912263 ).

If you have better information about some of these modules (for instance, you were the original author), feel free to use your info rather than Ansible Project if you'd like.

**Comment by abadger** [comment]
Looks good.  I'll merge once shippable is done testing.

**Comment by abadger** [comment]
Merged to devel for 2.4.0 release

**Comment by Akasurde** [comment]
@abadger Thanks for review and merge.

**Pull request merged**
