### PR TITLE
rhn_channel module

### PR DESCRIPTION
**Pull request by vincentvdk**
I made the necessary changes as commented on the mailing list. I also fixed an error when removing an non existing channel on the host.

### CODE REVIEW

**Comment by rrtj3** [comment]
I'm glad to see this module here. Sure beats using Redhat's website to change a boxes channels! 

Is there any reason you don't make username/password options to pass in? As it stands I think anyone who wants to use the module has to edit it first.

**Comment by rrtj3** [comment]
Coolio!

**Comment by mpdehaan** [comment]
Please go through this and review for comments and so on.

I see one that says "    - Username and password are currently hardcoded in the main
      section" 

but then I read the code, and it's not hard coded.

**Comment by mpdehaan** [comment]
Thanks for making updates, BTW.

Would others like to help test?

**Comment by vincentvdk** [comment]
Removed the info regarding user/pwd

**Comment by rrtj3** [comment]
I can give this a test tonight. Looking over it I noticed that you say the default rhn url is: https://rhn.redhat.com/rpc/api  but you don't set that as the default in the module parameters. Not necessary but it's probably also a good idea to set the other parameter types as well.

**Comment by rrtj3** [comment]
Nevermind my last comment about setting the param types on parameters. Probably no need since they're all strings and they don't/won't need to be type cast.

**Comment by vincentvdk** [comment]
The default channel is something i wanted to add, but changed it later as a required param. Thanks for testing!

**Comment by mpdehaan** [comment]
Merged, thanks, great to have this!

**Comment by mpdehaan** [comment]
BTW, I changed 'pwd' to 'password' to be more consistent with other modules, pwd should still work as an alias.

NOT tested (no RHN around right now), so let me know if that causes any issues.

Wanted to get that tweaked before people started using it.

**Comment by mpdehaan** [comment]
another thing to think about is whether or not it's possible to see what channels are installed without making the web/login request.

I'm not sure if that is possible or not...

**Comment by vincentvdk** [comment]
I'll look into that.  Awesome you merged this. Thanks!

**Pull request merged**
