### PR TITLE
[Backport 2.7] win_uri: fix body with one item in list

### PR DESCRIPTION
**Pull request by ilpianista**
##### SUMMARY
Backport of #49484 to stable-2.7.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_uri

### CODE REVIEW

**Comment by jborean93** [comment]
@ilpianista have you made any progress with trying to backport this or are you ok with just having the json as a string for older versions now that devel is fixed?

**Comment by ilpianista** [comment]
@jborean93 I did some try, but without any success.

For my use case I cannot use the json string workaround because the body is the content of another web request :-(

**Comment by jborean93** [comment]
If you are using an existing list or dict you can use the `to_json` filter to convert it to a string. This allows you to use the result of another request but send the content as a string.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/99134/22/tests

**Comment by abadger** [comment]
@ilpianista @jborean93 ping, I won't be able to merge this backport until it's passing tests.

**Comment by abadger** [comment]
Should I close this backport or is work being done on it?

**Comment by ilpianista** [comment]
@abadger I think we can close it as it requires a deep change to make it work and deep changes aren't something you want to backport usually :-)

**Pull request closed without merging**
