### PR TITLE
Add type checking for module arguments, converting as much as possible

### LINKED ISSUE #2126: Add type checking for module arguments
Allow an optional type='str', 'dict', etc. to require that a certain variable be of a certain type, performing conversion as necessary.

### PR DESCRIPTION
**Pull request by dhozac**
Converts to list from comma-separated strings, and to dicts from comma-separated, key=value strings.

Fixes #2126.

### CODE REVIEW

**Comment by mpdehaan** [comment]
It seems that if the type is 'bool' we should not have to supply choices at all, though I suspect the module formatter also needs to be updated to show this.  

I didn't check in skimming this, but we need to leave the module.boolean cast function around for backwards compatibility of modules -- though I didn't see it removed so I assume it's there.

**Comment by dhozac** [comment]
Yeah, good point. Want me to clean that up as well as part of this?

Yeah, it's still there. There's only one use of it from the core modules after this, rabbitmq_vhost seems to use it for parsing some output? It is still used internally.

**Comment by dhozac** [comment]
I think it should be fine to just remove the choices from all the bools. Error message will change from "value of %s must be one of: yes,on,1,true,1,no,off,0,false,0, got: %s" to "Boolean %s not in either boolean list", but that can be tweaked too. Doesn't seem like it should affect the docs at all.

**Comment by mpdehaan** [comment]
++ to removing choices from all the bools.

"value of %s must be a boolean" is probably good enough for the error.

yeah if you want to do that this would be great

thanks!

**Comment by dhozac** [comment]
Okay, removed choices=BOOLEANS from all the modules.

**Pull request merged**
