### PR TITLE
storage module for PowerMAX, VMAX All Flash and VMAX3 arrays.

### PR DESCRIPTION
**Pull request by rawstorage**
SUMMARY
Added new storage module for PowerMAX, VMAX All Flash and VMAX3 arrays.

ISSUE TYPE

New Module Pull Request

COMPONENT NAME

Storage Modules for PowerMAX and VMAX
Provisioning Modules
dellpmax_createsg.py
dellpmax_addvolume.py
dellpmax_createhostgroup.py
dellpmax_createhost.py
dellpmax_createportgroup.py
dellpmax_createmaskingview.py

Additional Modules are in progress and will be uploaded once they are pep8 compliant and conform to ansible style guidelines

ADDITIONAL INFORMATION

Requires install of Dell EMC PyU4V python module to function available on PyPi and PIP

### CODE REVIEW

**Comment by Akasurde** [comment]
@rawstorage Thanks for submitting this PR. If you are submitting more than 1 module in current namespace then please go through [this](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_in_groups.html) document. 

Let me know if you need any help on this. Thanks.

**Comment by rawstorage** [comment]
@akasurde, thanks for reaching out.  I've gone through this document and as far as I can see I should be meeting all of the requirements.   Is there something specific I am missing. I wasn't sure about the naming convention I used as I placed my modules in dellemc folder and called them dellpmax, would it be better to change the prefix to dellemc_pmax_createsg.py etc?  or is there something else.

**Comment by Akasurde** [comment]
@rawstorage Since  this is start of DellEMC space in storage, I would suggest to submit single module with module_utils. Once that is merged, you can apply same set of review to rest of the modules and create separate PRs. Like mention [here](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_in_groups.html#subsequent-prs). Let me know if you have any other questions. Thanks.

**Comment by rawstorage** [comment]
@Akasurde I'll close this pull request and resubmit with a single module.  I'll take time to rename the modules now as it will make it easier then if we decide to add more for other products.

**Comment by Akasurde** [comment]
@rawstorage OK. Ping me on the new PR once you are ready. Thanks.

**Pull request closed without merging**
