### PR TITLE
[WIP] Combine mysql_replication and mariadb_replication

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Since these two test roles are targeting the same module, combine the tests to avoid redundancy.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`test/integration/targets/mariadb_replication/`
`test/integration/targets/setup_mysql_replication/`

### CODE REVIEW

**Comment by Andersson007** [comment]
@samdoran , we need both because one has features that the other doesn't.
They are partially different RDBMS.
MariaDB is based on MySQL and mostly the same in the replication related part, but has several specific options. Also MySQL has related options that are not presented in MariaDB.

**Comment by samdoran** [comment]
@Andersson007 Ok. Thanks for the info. We were hoping to combine these since they seem to be exercising the same module.

**Comment by samdoran** [comment]
@Andersson007 Is there any way these tests could be combined but use conditionals to skip tasks based on the underlying DB? We'd have to detect the actual DB type and set a fact, or something like that.

**Comment by Andersson007** [comment]
@samdoran , yes, i think we can do something like:
```
# mysql -uroot -e 'select version();'
+----------------+
| version()      |
+----------------+
| 5.5.60-MariaDB |
+----------------+
```
and parse the output resp.
however it's difficult to get the whole idea for me about the certain implementation at the time because of my working schedule, hope the command above will be helpful.

In general, i understand and it's always good idea to reduce a number of tests running at the same time, but not really sure it is worth in this specific case. It seems to me that it can make the tests harder to maintain (especially for occasional developers).

**Pull request closed without merging**
