### PR TITLE
Keep hostvars from being templated

### PR DESCRIPTION
**Pull request by dhozac**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Small request.

When you send a pull request, give an example of what you are talking about, as it may not be immediately clear.

What broke before, for instance?  (And, is it a new thing, or was it always broken, etc?)

**Comment by dhozac** [comment]
hostvars was broken by the jinja2 variable templating merged last night, as it would only template the hostvars object (a copy of setup_cache), and thus not include inventory variables.

**Comment by mpdehaan** [comment]
What I am asking is for you to show me the minimal example that breaks it.

**Comment by mpdehaan** [comment]
merging this as I'll take your word for it given the other thread about broken hostvars

though it's important that you give examples of what you are trying to solve with PRs

the templating code is rapidly becoming complex and it is important that we communicate through examples.

**Pull request merged**
