### PR TITLE
Update ssh connection play_context alongside network_cli's

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

This is a modification of https://github.com/ansible-collections/ansible.netcommon/pull/135 for ansible 2.9

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

network_cli

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by samdoran** [comment]
Looks like this is still failing third party checks. Any idea what is causing those failures?

**Comment by Qalthos** [comment]
There was an issue with at least the python37 images not having libselinux-python, but I don't know if it's fixed or not

**Comment by relrod** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Pull request merged**
