### PR TITLE
use ansible json encoding/decoding to avoid errors

### LINKED ISSUE #47200: ansible-connection complaining about vaulted ansible_ssh_pass not being JSON-serializable
##### SUMMARY
After upgrading to ansible 2.7.0, `ansible-connection` is complaining about my vaulted `ansible_ssh_pass` not being JSON-serializable. Converting the password to plaintext in my `group_vars` file allows the playbook to run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

slxos_facts

##### ANSIBLE VERSION

```
2.7.0
```

##### CONFIGURATION

```
ANSIBLE_HOST_KEY_CHECKING=False
#ANSIBLE_DEBUG=True
#ANSIBLE_LOG_PATH=/tmp/playbook/log/ansible.log
ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=60
ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=30
#ANSIBLE_STDOUT_CALLBACK=json
```

##### OS / ENVIRONMENT
using ansible control in a Docker container on Debian 9

##### STEPS TO REPRODUCE
Run `slxos_facts` against any SLX device

```
---
- hosts: slx
  gather_facts: yes

  tasks:

  - name: get interface info
    slxos_facts:
      gather_subset: interfaces
    register: result

  - debug: var=result
```

##### EXPECTED RESULTS

Interface details would be gathered from my list of SLX devices.

##### ACTUAL RESULTS

```
fatal: [redacted]: FAILED! => {"msg": "Traceback (most recent call last):
  File \"/usr/bin/ansible-connection\", line 321, in <module>
    main()
  File \"/usr/bin/ansible-connection\", line 287, in main
    conn.set_options(var_options=variables)
  File \"/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py\", line 167, in __rpc__
    response = self._exec_jsonrpc(name, *args, **kwargs)
  File \"/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py\", line 144, in _exec_jsonrpc
    data = json.dumps(req)
  File \"/usr/lib/python2.7/json/__init__.py\", line 244, in dumps
    return _default_encoder.encode(obj)
  File \"/usr/lib/python2.7/json/encoder.py\", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File \"/usr/lib/python2.7/json/encoder.py\", line 270, in iterencode
    return _iterencode(o, 0)
  File \"/usr/lib/python2.7/json/encoder.py\", line 184, in default
    raise TypeError(repr(o) + \" is not JSON serializable\")
TypeError: u'***redacted***' is not JSON serializable
"}
```

```
docker run -it --rm -v $PWD:/tmp/playbook:Z --env-file ansible.env ansiblecm brcd_sflow.yml --vault-password-file vault/vault_pass -i $BRCD_ANS
```

### PR DESCRIPTION
**Pull request by bcoca**
tackle known issues with (de)serializing certain objects
related #47200

actually, the module_utils/connection needs updating to deal with this .. but that crosses boundries in the wrong direction to use parsing/ajson .. might be time to unify 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible-connection
##### ANSIBLE VERSION

```paste below
2.x
```

### CODE REVIEW

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by ericdost** [comment]
I tried to use this in my 2.7.1 implementation.  It still bombed on me.  This was the error I received:

```fatal: [ASA06]: FAILED! => {"msg": "Traceback (most recent call last):\n  File \"/usr/bin/ansible-connection\", line 324, in <module>\n    main()\n  File \"/usr/bin/ansible-connection\", line 290, in main\n    conn.set_options(var_options=variables)\n  File \"/usr/lib/python2.7/dist-packages/ansible/module_utils/connection.py\", line 167, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/ansible/module_utils/connection.py\", line 144, in _exec_jsonrpc\n    data = json.dumps(req)\n  File \"/usr/lib/python2.7/json/__init__.py\", line 244, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 207, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 270, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 184, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: u'password' is not JSON serializable\n"}```

Applying PR #48306 did work for me.

**Comment by bcoca** [comment]
@ericdost this was not meant as a fix, but prevent other similar bugs, hence 'related' not 'fixes'

**Comment by ericdost** [comment]
Ah, okay thanks.  Just an FYI, issue #47200 was closed due to the related tag.

**Pull request merged**
