### PR TITLE
update asa_config with bgp doc example

### PR DESCRIPTION
**Pull request by hemskgren**
##### SUMMARY

Add asa_config bgp doc example
+label: docsite_pr
Issue ansible/community#311

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

asa_config
##### ANSIBLE VERSION

```
2.5.4
```

##### ADDITIONAL INFORMATION

+label: docsite_pr
Issue ansible/community#311

```

```

### CODE REVIEW

**Comment by beeankha** [comment]
Hey @hemskgren , thanks so much for submitting this!  We'll be taking a look as soon as we get a chance, and will update with a comment once we're done testing.

**Comment by acozine** [comment]
Hi @hemskgren - same comment as #41255 - reach out if you have questions. Thanks!

**Comment by hemskgren** [comment]
See https://gist.github.com/hemskgren/c9b94468186201916e8ceee332513028
Playbook line 2-17 + 55-79
and output line 147-155

**Comment by IPvSean** [comment]
@hemskgren 

hate to be a stickler, the output shows the playbooks running, sending the output and it being successful but can you actually show the running configuration from your ASA (relevant config) where it actually populated the configuration as intended?  Want to verify the ASA actually accepted the configuration and what configuration it templated out.

**Comment by hemskgren** [comment]
@IPvSean is this better?  https://gist.github.com/hemskgren/c9c80ced1519327b514c60d21a01fb6b

**Comment by beeankha** [comment]
Putting playbook text directly in this thread for ease of reference:

```---
- name: modify my Cisco ASA with ansible
  hosts: "{{ devices }}"
  gather_facts: false
  connection: network_cli
  vars:
    #cli:
    host: "{{ inventory_hostname }}"
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ password }}"

  - name: configure ASA (9.2>) defult BGP
    asa_config:
      lines:
        - bgp log-neighbor-changes
        - bgp bestpath compare-routerid
      #provider: "{{ cli }}"
      parents:
        - router bgp 65002
    register: bgp
    when: bgp_defult_config is defined

  - name: configure ASA (9.2>) BGP neigbor in defult singel context mode
    asa_config:
      lines:
        - "bgp router-id {{ bgp_router_id }}"
        - "neighbor {{ bgp_neighbor_ip }} remote-as {{ bgp_neighbor_as }}"
        - "neighbor {{ bgp_neighbor_ip }} description {{ bgp_neighbor_name }}"
      #provider: "{{ cli }}"
      parents:
        - router bgp 65002
        - address-family ipv4 unicast
    register: bgp
    when: bgp_neighbor_as is defined
```
Below is text from the device config before running the playbook:
```
hemasa01(config)# sh runn | beg router bgp
router bgp 65002
 bgp log-neighbor-changes
 bgp bestpath compare-routerid
 address-family ipv4 unicast
  bgp router-id 192.168.13.1
  no auto-summary
  no synchronization
 exit-address-family
!
hemasa01(config)# no router bgp 65002
hemasa01(config)# sh runn | beg router bgp
hemasa01(config)# 
hemasa01(config)# 
hemasa01(config)# exit
```

Below is output from running the playbook:
```
christer@T400:~/github/ansible-test$ ansible-playbook -i inventory -vv  -t add_bgp asa_pr311.yml -e "username=c** password=*** devices=ASA bgp_defult_config=yes bgp_neighbor_as=65001 bgp_neighbor_ip=192.168.13.10 bgp_neighbor_name=cloudprovider bgp_router_id=192.168.13.1"
ansible-playbook 2.6.1
  config file = None
  configured module search path = [u'/home/christer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
No config file found; using defaults

PLAYBOOK: asa_pr311.yml ****************************************************************************
2 plays in asa_pr311.yml

PLAY [modify my Cisco ASA with ansible] ************************************************************
META: ran handlers
TASK [configure ASA (9.2>) defult BGP] *************************************************************
task path: /home/christer/github/ansible-test/asa_pr311.yml:56
changed: [192.168.96.1] => {"changed": true, "updates": ["router bgp 65002", "bgp log-neighbor-changes", "bgp bestpath compare-routerid"]}

TASK [configure ASA (9.2>) BGP neigbor in defult singel context mode] ******************************
task path: /home/christer/github/ansible-test/asa_pr311.yml:67
changed: [192.168.96.1] => {"changed": true, "updates": ["router bgp 65002", "address-family ipv4 unicast", "bgp router-id 192.168.13.1", "neighbor 192.168.13.10 remote-as 65001", "neighbor 192.168.13.10 description cloudprovider"]}
```

And here is the text from the device config after the playbook ran:
```
hemasa01# sh runn | beg router bgp
router bgp 65002
 bgp log-neighbor-changes
 bgp bestpath compare-routerid
 address-family ipv4 unicast
  neighbor 192.168.13.10 remote-as 65001
  neighbor 192.168.13.10 description cloudprovider
  neighbor 192.168.13.10 activate
  bgp router-id 192.168.13.1
  no auto-summary
  no synchronization
 exit-address-family
!
```

Thank you for providing this information, @hemskgren !

**Comment by hemskgren** [comment]
This BGP example is idempotent.

**Comment by acozine** [comment]
@hemskgren thanks for responding with more information. Today we merged #41253, so this PR needs to be rebased. 

Your `name` lines in this PR are excellent - detailed and descriptive. However, I see two ways they could be improved:
1. When you say `(9.2>)`, I'm not sure if you mean "greater than or equal to 9.2" or "less than or equal to 9.2".  Could you clarify? Either `(>=9.2)` or `(<=9.2)` would eliminate confusion.
2. I found a couple of typos - here's a list with Line# : wrong_spelling : right_spelling:
165 : defult : default
174 : bgp_defult_config : bgp_default_config
176 : defult/singel : default/single
Thanks!

**Comment by acozine** [comment]
Hi @hemskgren. Thanks for fixing the typos. Unfortunately you merged the `devel` branch into your branch instead of [rebasing](https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html). This makes the branch messy, and means we won't merge it back into `devel`. If you're on any of the Ansible IRC channels, you can ping me for help fixing that.

We're wrapping up the gamification exercise (https://github.com/ansible/community/issues/311) at the end of August. I hope you can fix up this PR before then! If not, though, we'll close it.

**Comment by acozine** [comment]
Thanks @hemskgren for adding to the pool of Ansible Network knowledge!

**Pull request merged**
