### PR TITLE
Remove command timeout.

### PR DESCRIPTION
**Pull request by jkleint**

### CODE REVIEW

**Comment by mpdehaan** [comment]
This diff is a lot larger than just removing the timeout, care to explain other details?
-        chan.settimeout(timeout_secs)

**Comment by jkleint** [comment]
Sure, the input and output files were being made twice, which doesn't help and may hurt, and stderr is combined whether you want it or not when using a pty, so I removed set_combine_stderr and added a comment to that effect.  I also added a comment explaining the approach to dealing with sudo that we arrived at, since it took us a few tries, implying it's a bit involved, so anyone reading the code in the future has an easier time understanding.  I had a more extensive explanation before, but it got dropped somewhere in reverting the reversions.

**Comment by mpdehaan** [comment]
Thanks for the explanation.

Somehow being dropped was me making it so it didn't fill several pages of my terminal -- so I trimmed it up a bit.

Agreed on duplicate stderr/stdout.  Not so agreed that combine_stderr being explicit is a bad thing, in case we don't always use a pty later, but that is probably ok.

Very minor style point -- please don't comment at the end of the line.   Many of us don't have giant terminal widths, commenting on the line before is better.

Will merge in, possibly with some edits, and test tonight.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
