### PR TITLE
asa_config add doc l3 interface

### PR DESCRIPTION
**Pull request by hemskgren**
##### SUMMARY

add asa_config doc example to add l3 interface
+label: docsite_pr
Issue ansible/community#311

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

asa_config
##### ANSIBLE VERSION

```
2.5.4
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by beeankha** [comment]
Hi @hemskgren , thank you for submitting this PR, especially as a first-time contributor to this repo!  We'll test your changes before merging them, but it's in the works and we'll comment further after we take a closer look.

**Comment by acozine** [comment]
Hi @hemskgren can you provide a playbook and output that show your example working against a network device? See #40369 for an example of what we're looking for. See the Validation section of ansible/community#311 for details on what we need. Thanks!

**Comment by hemskgren** [comment]
See https://gist.github.com/hemskgren/c9b94468186201916e8ceee332513028
Playbook line 2-26
and output line 95-99

**Comment by beeankha** [comment]
Thank you for providing the playbook and output, @hemskgren !  I am copying the text here for easier referencing:

```
$ more asa_pr311.yml
---
- name: modify my Cisco ASA with ansible
  hosts: "{{ devices }}"
  gather_facts: false
  connection: network_cli
  vars:
    #cli:
    host: "{{ inventory_hostname }}"
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ password }}"

  tasks:
  - name: configure ASA interface
    asa_config:
      lines:
        - description my cloud interface
        - nameif cloud13
        - security-level 50
        - ip address 192.168.13.1 255.255.255.0 standby 192.168.13.2
      #provider: "{{ cli }}"
      parents: ["interface vlan 13"]
    register: interface
```

Output is below:
```
TASK [configure ASA interface] ********************************************************************************************************
task path: /home/christer/github/ansible-test/asa_pr311.yml:16
changed: [192.168.96.1] => {"changed": true, "updates": ["interface vlan 13", "description my cloud interface", "nameif cloud13", "security-level 50", "ip address 192.168.13.1 255.255.255.0 standby 192.168.13.2"]}
```

In addition to the above, we’d also like to see what the results look like from the device to show that the playbook had the desired effect. Please reference what you provided in [41376](https://github.com/ansible/ansible/pull/41376) as an example.

**Comment by hemskgren** [comment]
Below is text from the device config before running the playbook:

```
hemasa01# sh runn interface vlan13
                            ^
ERROR: % Invalid input detected at '^' marker.
hemasa01# 
```

And here is the text from the device config after the playbook ran:

```
hemasa01# show runn interface vlan 13 
!
interface Vlan13
 description my cloud interface
 nameif cloud13
 security-level 50
 ip address 192.168.13.1 255.255.255.0 standby 192.168.13.2 
hemasa01#
```

**Comment by hemskgren** [comment]
I notise the interface example is not idempotent.

**Comment by hemskgren** [comment]
Last branch update fix the interface example to be idempotent.

**Comment by samccann** [comment]
@hemskgren we've reviewed this PR and have a couple of follow-up changes: - Please add a more descriptive name to the task, such as you did for https://github.com/ansible/ansible/pull/41253/files.  Also, please add a newline before the  "show interface update" task and use 'debug: var' instead of debug: msg'. See https://docs.ansible.com/ansible/devel/modules/debug_module.html.  

You'll also need to rebase to pick up other changes to this file.

Thanks for your help!

**Comment by acozine** [comment]
Hi @hemskgren. If you can take care of these four things, we can merge this PR:

1. Give the tasks more descriptive names
1. Add a newline between tasks
1. Use `debug:var` instead of `debug: msg`
1. [Rebase](https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html) the branch

We're wrapping up the gamification exercise (ansible/community#311) at the end of August. I hope you can fix up this PR before then! If not, though, we'll close it.

**Comment by acozine** [comment]
Well, crap, I messed up the rebase. Please don't merge until I fix this.

**Comment by samccann** [comment]
Thanks @hemskgren for helping to improve the Ansible documentation!

**Pull request merged**
