### PR TITLE
Add with_merged lookup plugin.

### PR DESCRIPTION
**Pull request by jinnko**
This new loop plugin allows the user to provide a list of arrays that will be merged in order from most general to most specific.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Sorry for the delay in responding to this, we have had a large backlog.

Can you provide an example of this being used?  This would be needed for the docs anyway, though I would also like to see if we can possibly consider renaming this one (but it might make sense anyway when I see the example).

Thanks!

**Comment by jinnko** [comment]
One of the main reasons I've needed this is to manage users through various environments, however I don't want to enable deep merging by default.

As an example I have a core set of users who are super users and have full access to all environments, while some users only have access to dev, staging, individual hosts, etc.  This can be deployed easily using with_merged as follows.

The result is that all servers get the `admin` user, while only nodes in the dev group have the `dev1` user provisioned, and the node 'pi' is the only one that gets the user `pi`.

```
$ cat roles/users/default/main.yml
---
users_default:
  admin:
    uid: 999
    name: admin
    pass: "$6$yyyyyyyy$zzzzzzzzzzzzzz"
    group: adm
    groups: sudo
    shell: /bin/zsh
```

## 

```
$ cat group_vars/dev.yml
---
users_group_vars:
  dev1:
    uid: 9991
    name: dev1
    pass: "$6$yyyyyyyy$zzzzzzzzzzzzzz"
    group: devs
    groups: sudo
    shell: /bin/zsh
```

## 

```
$ cat host_vars/pi.yml
---
users_host_vars:
  pi:
    uid: 1000
    name: pi
    pass: "$6$yyyyyyyyy$zzzzzzzzzzzzz"
    group: pi
    groups: adm,audio,cdrom,dialout,disk,lp,video
    shell: /bin/zsh
```

## 

```
$ cat roles/users/tasks/main.yml
- name: Create users
  user: uid={{ item.uid }} name={{ item.name }} group={{ item.group }} groups={{ item.groups }} shell={{ item.shell }} password={{ item.pass }}
  with_merged:
    - "{{ users_default }}"
    - "{{ users_group_vars }}"
    - "{{ users_host_vars }}"
```

**Comment by bcoca** [comment]
I think this overlaps with the filters that can merge hashes and lists, which are already usable with_items

**Comment by bcoca** [comment]
closing this in favor of existing filters that already do the same

**Comment by jinnko** [comment]
@bcoca The best info I can find for achieving this is what's listed [here](http://stackoverflow.com/a/25770383/506757).  Or do you know another way of doing this?

UPDATE 2015-08-04: I see there's [other](https://github.com/ansible/ansible/pull/11785) [as](https://github.com/ansible/ansible/pull/10489) [yet](https://github.com/ansible/ansible/pull/7872) unmerged PR's to achieve this.  Hope #11785 or similar gets merged soon.

**Pull request closed without merging**
