### PR TITLE
Add ldap lookup plugin to search and get ldap entries

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
##### SUMMARY
Add ldap lookup plugin to search and get ldap entries

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/lookup/ldap.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (feature/add_module/ldap_get de0bd50d80) last updated 2017/07/23 00:03:53 (GMT +200)
  config file = None
  configured module search path = ['/home/mouxon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mouxon/Bureau/ansible-ladp/ansible/lib/ansible
  executable location = /home/mouxon/Bureau/ansible-ladp/ansible/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

##### ADDITIONAL INFORMATION

This lookup was asked by @jtyr in PR https://github.com/ansible/ansible/pull/27195 to replace a module action.

This lookup plugin allows to request a LDAP server.
See examples :

```
  vars:
    ldap_user_admin:
        server_uri: ldap://localhost/
        bind_dn: cn=admin,dc=example,dc=com
        bind_pw: password
        dn: cn=admin,dc=example,dc=com

    ldap_users_admin:
        server_uri: ldap://localhost/
        bind_dn: cn=admin,dc=example,dc=com
        bind_pw: password
        search_base: dc=example,dc=com
        search_filter: (user_type=admin)

  tasks:
    - name: Get an user by dn entry
      debug: msg="Admin User: [{{ item.attributes.display_name }}]"
      with_items:
       - "{{ lookup('ldap', ldap_user_admin) }}"

    - name: Look for all admin user by calling with_ldap:
      debug: msg="Admin User DN: [{{ item.dn }}]"
      with_ldap: "{{ldap_users_admin}}"
```

### CODE REVIEW

**Comment by GuillaumeSmaha** [comment]
ready_for_review

**Comment by michalmedvecky** [comment]
Please merge this to some release candidate 🙏

**Comment by GuillaumeSmaha** [comment]
Any news for this PR ?

**Comment by hstock** [comment]
Anything blocking this from inclusion?

**Comment by GuillaumeSmaha** [comment]
@hstock PR is fixed for ansible 2.7

**Comment by gfdsa** [comment]
python ldap3 version 2.5
copy/pasted from the ldap.py documentation
```
    - name: Setup LDAP lookup of new account name
      set_fact:
        ldap_lookup_account:
          server_uri: "{{lookup('env','LDAP_SERVER_URI')}}"
          bind_dn: "{{lookup('env','LDAP_BIND_DN')}}"
          bind_pw: "{{lookup('env','LDAP_BIND_PW')}}"
          search_base: "{{lookup('env','LDAP_SEARCH_BASE')}}"
          search_filter: "(SAMAccountName={{sam_account_name}})"
    - name: Run the lookup
      set_fact:
        found_account: "{{ lookup('ldap', ldap_lookup_account) }}"
```
if there are results all is fine and business as usual
if the search doesn'f find any entries there is a problem:
```
Fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'ldap'. Error was a <class 'TypeError'>, original message: 'NoneType' object is not iterable"} 
```
here, on :271:
```
            for entry in entries:
                ret.append(self.get_clean_entry(entry))
```
Another issue, I am searching for a dn as per documentation, but it explodes on 
```
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'ldap'. Error was a <class 'ldap3.core.exceptions.LDAPInvalidFilterError'>, original message: invalid filter"}                                                                                                                                        
```
Because you pass an empty string to the search(). Modifying it to 
```
if self.dn:
            result = self.connection.search(
                self.dn, '(objectClass=*)', search_scope=ldap3.SUBTREE, attributes=ldap3.ALL_ATTRIBUTES)
```
"fixes" the problem
did I miss something?

**Comment by Akasurde** [comment]
Hi @GuillaumeSmaha, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
