### PR TITLE
Add Show Interface Example

### PR DESCRIPTION
**Pull request by permitanyany**
Adding Show Interface Example to demonstrate how to checkout previous config change
+label: docsite_pr
Issue https://github.com/ansible/community/issues/311

##### SUMMARY
Adding Show Interface Example to demonstrate how to checkout previous config change

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
nclu

##### ANSIBLE VERSION
ansible 2.5.2
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

##### ADDITIONAL INFORMATION
Related to Issue #311

### CODE REVIEW

**Comment by ericpulvino** [comment]
Looks good.

**Comment by IPvSean** [comment]
there is a new requirement for all submitted PRs for the contest https://github.com/ansible/community/issues/311 (and in general for networking doc PRs) to provide playbook output. Since this is a new rule, and Cumulus VX is widely available and easy to use, I will go ahead and test the 5 PRs submitted by @permitanyany

For https://github.com/ansible/ansible/pull/40731
So this is a good example! ... but I think you could make it look a lot sexier @permitanyany (tagging @ericpulvino and @plumbis for visibility to see if they like this method)

when you run the playbook in the current form->

```
TASK [Fetch Status Of Interface] **************************************************************************************
ok: [leaf01]

TASK [Print Status Of Interface] **************************************************************************************
ok: [leaf01] => {
    "output": {
        "changed": false,
        "failed": false,
        "msg": "{\"iface_obj\": {\"native_vlan\": null, \"description\": \"\", \"vlan\": null, \"lacp\": {\"rate\": \"\", \"sys_priority\": \"\", \"partner_mac\": \"\", \"bypass\": \"\"}, \"mac\": \"44:38:39:00:00:03\", \"members\": {}, \"min_links\": \"\", \"dhcp_enabled\": false, \"ip_address\": {\"allentries\": []}, \"ip_neighbors\": null, \"lldp\": null, \"asic\": null, \"mtu\": 1500, \"vlan_filtering\": false, \"counters\": {\"rx\": {\"unicast\": 0, \"broadcast\": 0, \"multicast\": 0, \"errors\": 0}, \"tx\": {\"unicast\": 0, \"broadcast\": 0, \"multicast\": 0, \"errors\": 0}}}, \"linkstate\": \"ADMDN\", \"summary\": \"\", \"connector_type\": \"Unknown\", \"mode\": \"NotConfigured\", \"speed\": \"N/A\"}\n"
    }
}
```

the way the NCLU module works is returning a standard string, but you can force it into JSON really easily like this->

```
    - name: Fetch Status Of Interface
      nclu:
        commands:
            - show interface swp1 json
      register: output

    - name: Turn the stdout string into json
      set_fact: json_output="{{output.msg | from_json }}"
      run_once: true
      delegate_to: localhost

    - name: Print Status Of Interface
      debug:
        var: json_output
```

then the output looks like this->

```
TASK [Fetch Status Of Interface] **************************************************************************************
ok: [leaf01]

TASK [Turn the stdout string into json] *******************************************************************************
ok: [leaf01 -> localhost]

TASK [Print Status Of Interface] **************************************************************************************
ok: [leaf01] => {
    "json_output": {
        "connector_type": "Unknown",
        "iface_obj": {
            "asic": null,
            "counters": {
                "rx": {
                    "broadcast": 0,
                    "errors": 0,
                    "multicast": 0,
                    "unicast": 0
                },
                "tx": {
                    "broadcast": 0,
                    "errors": 0,
                    "multicast": 0,
                    "unicast": 0
                }
            },
            "description": "",
            "dhcp_enabled": false,
            "ip_address": {
                "allentries": []
            },
            "ip_neighbors": null,
            "lacp": {
                "bypass": "",
                "partner_mac": "",
                "rate": "",
                "sys_priority": ""
            },
            "lldp": null,
            "mac": "44:38:39:00:00:03",
            "members": {},
            "min_links": "",
            "mtu": 1500,
            "native_vlan": null,
            "vlan": null,
            "vlan_filtering": false
        },
        "linkstate": "ADMDN",
        "mode": "NotConfigured",
        "speed": "N/A",
        "summary": ""
    }
}

PLAY RECAP ************************************************************************************************************
leaf01                     : ok=4    changed=0    unreachable=0    failed=0
```

if you prefer the above method can you just fix the PR? (commit to your own repo and it will auto update this), otherwise just let me know you prefer the txt output and I can get this one accepted.  It might be worth talking to @isharacomix about returning straight up json rather than text

**Comment by IPvSean** [comment]
I actually see you did this in the JSON version like this->
```
    - name: Print Status Of Interface
      debug:
        var: output["msg"]
```

I would highly recommend just showing the JSON format.  This is something only certain networking devices can do... are you sure you want plain text?  I made some comments on https://github.com/ansible/ansible/pull/40732 and it looks ready to go... my set_fact method actually is more complicated than what you had on that PR.  Why not add an OSPF example or something at your fifth PR to get more value out of it?

**Comment by permitanyany** [comment]
I added both JSON and non-JSON examples to show the various options.  For a
first time user, the debug/var/output/msg syntax might be confusing, so I
figured there would be value in showing the raw output without any
additional parameters....and then the better looking output via JSON by
just adding a few more parameters.

**Comment by IPvSean** [comment]
this one is good to go @acozine !

**Comment by acozine** [comment]
After reviewing the comments on both PRs, and given the fact that CI is failing on this PR, I'm going to close this one in favor of #40732. Thanks @permitanyany for contributing to the docs - keep 'em coming!

**Comment by acozine** [comment]
Oops, I took the wrong message away from the comments. After chatting with @IPvSean, I'm re-opening this PR. @permitanyany can you please re-base it for merging? See Ansibot's comments above for details.

**Comment by acozine** [comment]
Ping @permitanyany - all of your PRs change the same file, so each time we merge one, the others will need to be rebased - fortunately this is easy, see https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html. Reach out if you have questions. We'd like to merge these examples soon! Thanks.

**Comment by acozine** [comment]
Closing in favor of #41863.

**Pull request closed without merging**
