### PR TITLE
Adding documentaion example with multiple packages

### PR DESCRIPTION
**Pull request by ruzickap**
Adding documentation example showing how to install multiple packages like it's here: https://docs.ansible.com/ansible/latest/modules/yum_module.html
The reason is to prevent of using loop in the future.

+label: docsite_pr

### CODE REVIEW

**Review by bcoca — CHANGES_REQUESTED** [review]
this is invalid, not all package managers support direct list assignment

**Comment by ruzickap** [comment]
Actually the example above was working for me when I was testing it in Ansible 2.6.x
That's why I made this PR...

**Comment by samdoran** [comment]
@ruzickap The `package` module uses `ansible_pkg_mgr` to determine the underlying module to run. While the most popular package modules do support a list in the `name` field, some do not, such as `swupd` and `opkg`. That makes this example problematic.

**Comment by bcoca** [comment]
@ruzickap it works 'for you' but not 'for everyone' since others might be using other package managers that don't support lists.

**Comment by ruzickap** [comment]
Ok... 

It's clear now...

I'm closing this PR.

Sorry for the mess and thank you for your time.

**Comment by samdoran** [comment]
@ruzickap No problem at all. Thanks for trying to add a helpful example. Unfortunately, you picked a module with a lot of underlying complexity.

**Pull request closed without merging**
