### PR TITLE
Correct the helm state in the documentation

### LINKED ISSUE #35950: Helm state is not documented as implemented
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

`helm`

##### ANSIBLE VERSION

`ansible 2.6.0devel (devel 2fece2f148) last updated 2018/02/09 12:21:02 (GMT +200)`

##### SUMMARY

The `state` of the `helm` module is incorrectly presented to default to `installed` in the documentation. The implemented value for this however is `present`.

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

Fixes #35950

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

`helm`

##### ANSIBLE VERSION

`ansible 2.6.0devel (devel 2fece2f148) last updated 2018/02/09 12:21:02 (GMT +200)`

### CODE REVIEW

**Comment by flaper87** [comment]
shipit

**Comment by flaper87** [comment]
Thanks a lot for your patch! :cake:

**Comment by ghost** [comment]
@mkrizek @flaper87 Glad to be of service! It doesn't look like this branch has been merged however.

**Review by mkrizek — APPROVED** [review]

**Comment by ghost** [comment]
@mkrizek Thanks! :-)

**Pull request merged**
