### PR TITLE
terminal length

### PR DESCRIPTION
**Pull request by jpvrenen**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

- new parameter 'term_length'
##### ANSIBLE VERSION

```

```
##### SUMMARY

```
sending 'terminal length 0' becomes optional after connection is made (default is true, but can be disabled)
```

'terminal length 0', after connect becomes optional.

### CODE REVIEW

**Comment by privateip** [comment]
What is the use case for this proposed change?

**Comment by jpvrenen** [comment]
Hi,

I am using the 'ios_config' module for configuring switches, now I am also using it to configure ASA firewalls. The 'terminal length 0' command does not exist on ASA firewalls.

---

Van: Peter Sprygada notifications@github.com
Verzonden: vrijdag 16 september 2016 13:32
Aan: ansible/ansible
CC: jpvrenen; Author
Onderwerp: Re: [ansible/ansible] terminal length (#17609)

What is the use case for this proposed change?

##

**Comment by privateip** [comment]
Is there any reason the current asa_\* modules wont work for you instead of using the ios_\* modules?

**Comment by jpvrenen** [comment]
Ah ok sorry I am still on stable-2.1 did not check 2.2 my fault.

Thanks, Jeroen

---

Van: Peter Sprygada notifications@github.com
Verzonden: vrijdag 16 september 2016 18:56
Aan: ansible/ansible
CC: jpvrenen; Author
Onderwerp: Re: [ansible/ansible] terminal length (#17609)

Is there any reason the current asa_\* modules wont work for you instead of using the ios_\* modules?

##

**Pull request closed without merging**
