### PR TITLE
[2.7] docker_* modules: simplify idempotency comparisons, fix paused in docker_container

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backports of #47709 and #47900 and #48056 and #48059 to stable-2.7: refactoring of idempotency comparisons, add some more tests, and fix `paused` state.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/docker_commons.py
docker_config
docker_configuration
docker_secret

##### ANSIBLE VERSION
```
2.7.1
```

### CODE REVIEW

**Comment by felixfontein** [comment]
Failing test is fixed by #47762.

**Comment by abadger** [comment]
We'll need a changelog fragment for this before merging to stable-2.7

**Comment by felixfontein** [comment]
@abadger the original PR was "only" a refactoring which would be needed for future updated, so it didn't have a changelog in the first place. Since I now have the first patch which actually requires that refactoring, I've integrated it here (it also has a proper changelog). It's a backport of #47900.

**Comment by felixfontein** [comment]
The failing test should be fixed by #47608 (needs to be backported). The unstable test is #47896.

**Comment by felixfontein** [comment]
Will be extended by a backport of #48056, which improves #47900.

**Comment by felixfontein** [comment]
Also added #48059 to improve test stability.

**Comment by felixfontein** [comment]
Rebased to current `stable-2.7`.

**Comment by abadger** [comment]
Thanks @felixfontein  :-)

**Comment by abadger** [comment]
Merged for 2.7.2

**Comment by felixfontein** [comment]
Thanks for merging the last two ;)

**Pull request merged**
