### PR TITLE
Add explicit encoding to subprocess.Popen() calls.

### LINKED ISSUE #55157: Remote's stdout/stderr mangled, when encoding is other than UTF-8
##### SUMMARY
When `$LANG` contains an encoding, that's not a UTF-8, non-ASCII characters are shown by Ansible as ?-marks.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
core ?

##### ANSIBLE VERSION
```paste below
ansible 2.7.9
  config file = /mi/A/ansible.cfg
  configured module search path = ['/mi/.ansible/plugins/modules', '/opt/share/py36-ansible/plugins/modules']
  ansible python module location = /opt/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 3.6.8 (default, Mar 27 2019, 23:58:03) [GCC 4.2.1 Compatible FreeBSD Clang 7.0.1 (tags/RELEASE_701/final 349250)]
```

##### CONFIGURATION
```paste below
ALLOW_WORLD_READABLE_TMPFILES(/mi/A/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/mi/A/ansible.cfg) = -q -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%h-%p-%r
CACHE_PLUGIN(/mi/A/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/mi/A/ansible.cfg) = /tmp/afacts
DEFAULT_FORKS(/mi/A/ansible.cfg) = 61
DEFAULT_TIMEOUT(/mi/A/ansible.cfg) = 23
HOST_KEY_CHECKING(/mi/A/ansible.cfg) = False
```

##### OS / ENVIRONMENT
My usual setting for `LANG` is `uk_UA.KOI8-U`. ssh ensures, the LANG variable is forwarded to the remote servers.

##### STEPS TO REPRODUCE
Though the problem affects all Ansible utilities, it is easiest to reproduce with a simple `ansible` invocation:
`ansible -i SOMEHOST, all -a "date +%B""`

##### EXPECTED RESULTS
This is, what I expect -- the full name of the month in the specified locale:
`квітень`

Indeed, the above is what I see, if I change my `LANG` to `uk_UA.UTF-8` (and adjust xterm to decode UTF-8 as well).

##### ACTUAL RESULTS
`???????`

### PR DESCRIPTION
**Pull request by UnitedMarsupials**
Remove checks for UTF8-only -- that's an unnecessary limitation. The work is probably incomplete, but `ssh.py` can now handle non-UTF8 encodings.

will now print the date's output in whatever locale (assuming the local and remote locales match, of course).

##### SUMMARY

Instead of insisting on UTF8, add locale to all calls to `subprocess.Popen()`

Fixes:	#55157

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

The below command now prints the output in proper Ukrainian (my `LANG` is set to `uk_UA.KOI8-U`):

```paste below
	ansible -ilocalhost, -a date all
	localhost | CHANGED | rc=0 >>
	Пн  7 серп. 2023 01:16:13 EDT
```
whereas before -- with all current versions of Ansible -- the output would be garbled: `пп╣яп©. 2023 01:16:59 EDT`.

I'm sure, the work is not complete -- and I'm hoping, automated regression tests will point out the omissions to me.

### CODE REVIEW

**Comment by bcoca** [comment]
We force UTF-8 so we can make assumptions internally and manipulate strings freely, if we have to consider each possible encoding it quickly becomes an insurmountable issue.

**Comment by UnitedMarsupials** [comment]
> We force UTF-8 so we can make assumptions internally and manipulate strings freely

The internal strings, regardless of the language, are always encoded in UTF-8 -- because that's how Python-3.x stores them. But it should still be possible to have a different encoding _externally_.

My change -- once I figure out the failed test-cases -- is meant to handle just that: instead of assuming, that any external command always uses UTF8, we treat its output as encoded in whatever the locale specifies...

**Comment by bcoca** [comment]
closing as per https://github.com/ansible/ansible/issues/55157#issuecomment-1588141539

**Comment by UnitedMarsupials** [comment]
> closing as per [#55157 (comment)](https://github.com/ansible/ansible/issues/55157#issuecomment-1588141539)

That comment is, frankly, dumb. And I even explain -- right here -- why that is. If you don't understand the explanation -- ask follow-up questions. But to pretend, it does not exist, is just rude...

I would've explained it to @sivel right there on #55157, but follow-ups were disabled (for mortals) on that ticket... 

You -- and @sivel -- don't seem to "grok" encodings. The whole strings vs. bytes thing introduced in Python-3.x is just an inconvenience to you, is not it? The code is peppered with byte-to-string (and back) conversions, which reveal this poor understanding on behalf of the English-only programmers.

And it _still_ was breaking in a number of ways, was not it? Or else you wouldn't have bothered with that check of the locale, that I am removing from the `__init__.py`...

You may not know them, but there really are good reasons for people to use non-UTF8 encodings -- and millions do. Forcing us all to switch our accounts to UTF8 -- not just for Ansible, but for everything -- is a gratuitous imposition, which smacks of the infamous "This site only works with Internet Explorer".

We can discuss the merits of this PR -- perhaps, it is overly ambitious and should've concentrated on changing just the `ssh.py` -- but to dismiss the problem off hand is wrong.

**Comment by bcoca** [comment]
> That comment is, frankly, dumb. And I even explain -- right here -- why that is. If you don't understand the explanation -- ask follow-up questions. But to pretend, it does not exist, is just rude...

No pretending just a disagreement, did not mean to be rude but we don't always take the time to do thorough explanations, we cannot scale that way.

> I would've explained it to @sivel right there on https://github.com/ansible/ansible/issues/55157, but follow-ups were disabled (for mortals) on that ticket...

Followups are disabled because we don't get notifications for old closed tickets (99% of them were spam when we still had it enabled), so as to not have you make comments into the ether, we lock such old tickets so you must create new tickets, which we WILL see.

> You -- and @sivel -- don't seem to "grok" encodings. The whole strings vs. bytes thing introduced in Python-3.x is just an inconvenience to you, is not it? The code is peppered with byte-to-string (and back) conversions, which reveal this poor understanding on behalf of the English-only programmers.

The code mostly also dealt with Python 2 (some of it still does ...) and a lot of it has not been reconverted to work exclusively on Python 3 ( .... i cannot tell you how much we wish we could ...). As per poor understanding, I might be guilty of that, but I'm not an English-only programmer, I can barely handle English, as most that have interacted with me might testify to.

> And it still was breaking in a number of ways, was not it? Or else you wouldn't have bothered with that check of the locale, that I am removing from the __init__.py...

Actually no, there were not any reports I can recall. This was a preemptive change,  not reactive (something about EBCDIC , if memory serves me right).

> You may not know them, but there really are good reasons for people to use non-UTF8 encodings -- and millions do. Forcing us all to switch our accounts to UTF8 -- not just for Ansible, but for everything -- is a gratuitous imposition, which smacks of the infamous "This site only works with Internet Explorer".

I know .. having dealt with the CJK triad many times in data manipulation (they  make issues with East European Unicodes  look simple), they are most fun when you have multiple encodings in the same file/line/sentence .

> We can discuss the merits of this PR -- perhaps, it is overly ambitious and should've concentrated on changing just the ssh.py -- but to dismiss the problem off hand is wrong.

I'm not going to give you every reason, but communication over the connection plugins is already supposed to be UTF-8 (JSON standard ... even if not all JSON libraries enforce it). We mostly deal with JSON, YAML and Jinja2 so we made them conform to a uniform standard.

Also, your PR assumes something that is not always true, utilities and files in a system will not always conform to the current locale configured, this is (at least in my experience) a very bad assumption and instead of playing 'guess the encoding' we opted to enforce a uniform one.  It is fine that you disagree, but  you really don't need to get personal, our response never was.

**Comment by UnitedMarsupials** [comment]
> but I'm not an English-only programmer

I should've said Latin charset-only, I guess...

> The code mostly also dealt with Python 2

The current devel-branch insists not just on Python-3, it rejects anything below 3.11! (Meaning, I cannot use it with the stock `/usr/bin/python3` on the perfectly current releases RHEL7 and RHEL8, can I, despite RedHat being your major sponsor...)

> they are most fun when you have multiple encodings in the same file/line/sentence .

Incorrectly encoded data are a problem regardless of the encoding, aren't they?

> communication over the connection plugins is already supposed to be UTF-8

Because you -- Ansible programmers -- control both sides of that communication, you can make it use any encoding/compression you want. Consider this diagram:

| A | B | C | D |
|--------|--------|--------|--------|
| User invokes Ansible | Ansible on the control node invokes ssh to reach managed node(s) and start Python|Python on the managed node generates module-specific code and runs it|Module code (sometimes) invokes local commands|

You're talking about communications between parts B and C -- which is, indeed, internal. But that's no reason to compel UTF8 between A and B -- and that is, what you already do in devel-branch.

Worse, in order to be able to use Ansible at all, I will have to switch _everything_ I do to UTF8 -- because Ansible logs-in as _me_, and the login shell starts with the LANG set...

At the very least, you could force the LANG on the remote side to a uniform `en_US.UTF-8` -- or just be sure to remove from the environment -- before handing control over to the module-specific code.

But more importantly, it does not really matter, what the encoding is -- as long as it is *known*... And you agree with that, judging by your subsequent comments below (the 'guess the encoding part'). So, even if a local program (part D) outputs non-UTF text, Python in part C will turn it into UTF8 _automatically_ -- the programmer just needs to specify the encoding (and my PR does that) -- then feed the proper encoding to B. B will then be able to print present it to the user (part A) in the encoding preferred by him just as transparently, and without forcing the user to switch to UTF-capable fonts, etcætera...

That's how Python's encodings are meant to 

> utilities and files in a system will not always conform to the current locale configured

No opinion regarding filenames, those can really be in anything (user's own fault), but any and all utilities I ever encountered either speak English regardless of locale (like Ansible), or use the specified language (and encoding).

But if you've really dealt with such buggy utilities, then the UTF8 is also just a guess -- and they need fixing regardless, instead of pessimizing the computing experience for all users of other encodings.

If anything, I'd expect you to have bigger problems with _language_ -- not the encoding. For example, when it finds nothing to do, GNU make advises the user of that finding using the user's choice of language. The exit code is still zero, so for Ansible to discern, whether or not to set the `changed` flag, it needs to understand all languages (regardless of encoding).

So I'd understand it, if you enforced English (at least for modules invoking local programs), but the current code has no objections against, for example, `uk_UA.UTF-8`...

> instead of playing 'guess the encoding' we opted to enforce a uniform one

So much for celebrating diversity :-) Would not it be so much easier, if everybody used the same computer, same browser, drove the same car, wore the same clothes (and haircut), ate the same food, and carried the same cellular phone?

But seriously, the `locale`-module does the "guessing" for you -- what it returns is much more likely to be correct, than the hardcoded UTF8. Using it consistently -- as my PR tries to -- also removes the need for the incessant byte-to-string (and back) conversions...

> but you really don't need to get personal

This was not a _personal_ attack -- my target was the entire development team :-) The brisk dismissal of the PR -- _ignoring the explanations_ -- is what caused it...

I get the trouble with "scaling", but this problem -- with encoding -- is a large and serious one. You're "solving" it with a "cop-out"

**Comment by bcoca** [comment]
> I should've said Latin charset-only, I guess...

And while that might cover me, it still does not cover all my team members, but you like your assumptions.

> Incorrectly encoded data are a problem regardless of the encoding, aren't they?

Incorrect to you or me, but correct from the author's view as they handled conversations between different nationals. Not everything is black or white, things would be much easier if they were that simple, many times the point of view  or context decides on correctness.

> The current devel-branch insists not just on Python-3, it rejects anything below 3.11! (Meaning, I cannot use it with the stock /usr/bin/python3 on the perfectly current releases RHEL7 and RHEL8, can I, despite RedHat being your major 
sponsor...)

They pay my salary, yes, that does not mean all teams in the same company are aligned on every detail nor have the same specific objectives (we do share the big general ones). That is why we don't always see the same Python supported versions. But that was not my point, it was that the code, for a long time, supported Python2 and while the controller should be now on much more modern versions, not all the code has been changed to reflect this. We just added startup checks to remove assumptions of support and we try to avoid new code that moves in the wrong direction. We do still support Python 2.7 on the target (module/module_utils) and so must our CI.

>Because you -- Ansible programmers -- control both sides of that communication, 

Not really, we state the communication standard, but only control one side, 3rd party modules can be in any language  (I have perl, shell and binary ones). Between A and B is 'inputs to our tools', we are by far not he only tool to mandate conditions on their inputs.  C is true for the 'happy path', but not always, we have plenty of exceptions, that is why we rely on the message format being the standard, not the code executing on the remote.

UTF8 covers all languages, that I know of (diversity!), other competing Unicode standards do exist, but conversion to/from utf8 is at this point in time very common. We did not believe this to be to an onerous condition. If many users would give feedback that it is, we would reconsider (this has happened with other decisions), but as it stands now that has not happened on this issue.

As for `LANG` ... yes, many issues, see https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/locale.py#L10, this is what we use in modules to handle i18n issues when we need to make decisions based on outputs (sadly not all tools think RCs are how to communicate errors, Ansible itself has a problem in this area). But selecting the locale is not enough, you can see our modules, depending on utility we have to set different environment variables for run command (sometimes `LANG`, sometimes `LC_ALL`, sometimes something more specific)... even apt, yum and other basic utilities do not follow the 'standard' but deviate on which/what they use to handle locale and language. 

> This was not a personal attack -- my target was the entire development team

An attack still is 'personal' when directed to a group people, not just an individual, I specially take it very personal when it is against my team. Railing against a corporation or another abstract entity might be less "personal", but in the end there are always people behind it making the decisions and carrying them out. Only people can do dumb things, because were are also the only ones that have the ability to do intelligent/smart/thought out ones. 

> I get the trouble with "scaling", but this problem -- with encoding -- is a large and serious one. You're "solving" it with a bogus "cop-out", and shutting down the debate.

We close PRs, that is not the same as shutting down debates, as this conversation and hundreds of others before it prove.  Go to any of the public online meetings, the proposals repo or even just lurk  on the matrix/irc channels ... the debate never ends ...

You might consider it a cop-out, I consider it a compromise, the same way we compromise on which versions of Python we support, which distributions/OSs and versions of each we test against and even what distro/OS specific code we accept. 

We are always open to having our minds changed, calling people rude or dumb is a bad way to attempt that, not in my case, I might be both, but in general it is a bad idea.

**Comment by UnitedMarsupials** [comment]
> 3rd party modules can be in any language (I have perl, shell and binary ones).

The requirement to respect an encoding specified in the LANG (or LC_ALL) variable (if any) is hardly an imposing one for any such module-developers, and any deviation from that would simply a bug in that module.

Indeed, you do already make a harsher imposition by insisting, I quote, "All module return data must be utf-8 encoded".

But if you really are set on enforcing the above rule, just set the LANG accordingly _on the remote_ before executing the module-specific command-line. Then, once you read the module's output, you can show it to me in my choice of encoding...

Once again, it does not matter, what the encoding is, _as long as it is known_. And the knowledge is there -- Python's standard `locale`-module provides it.

> You might consider it a cop-out, I consider it a compromise

Whether it is a cop-out or not, It is not a compromise -- you're forcing me to remove LANG-customizations from `~/.tcshrc` on all of the managed hosts... This affects all the work I do -- not just Ansible. You could inject the preferred value of LANG (or LC_ALL) into the environment of just the Ansible-invoked commands, but you do not -- not currently, anyway. So I lose that valuable functionality -- and what do I gain? Sadly, you don't gain anything either...

Finally, my change makes the existing code simpler by adding the encoding-parameter to the various `subprocess.Popen()` calls. Even if that encoding were always UTF8 (rather than what `locale`-module specifies), the change would still allow you to avoid explicit bytes-to-string conversions throughout the code... Instead of reading bytes, into `b_out`, then converting that to `out`, you can read to `out` directly and achieve the same effect.  Fewer lines, fewer variables, easier to read code -- a win-win all around:

```diff

-    cmd = subprocess.Popen(invoke, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+    cmd = subprocess.Popen(invoke, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding=locale.getlocale()[1])
+    (out, err) = cmd.communicate()
-    out, err = to_text(out), to_text(err)
```

But it is not coded that way currently -- clearly, the port to Python-3 was not done by that "encoding expert", that @sivel mentions in the comments on #55157. Or, if that was him, then I'm forced to question the expertise, however impolite this makes me, once again :(

> We are always open to having our minds changed

I wonder, how this changing could possibly occur, if the tickets are closed as brusquely and briskly as they are -- because spam... Maybe, I need to start stalking you during parties...

Anyway, suppose I resolve all of the test-failures by subsequent commits -- would you consider reopening this request?

**Pull request closed without merging**
