### PR TITLE
vmware_guest: speed up VM name lookups by factor 60

### LINKED ISSUE #19064: vmware_guest is very slow
_From @aperigault on November 17, 2016 9:4_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest.py

##### ANSIBLE VERSION
```
2.2.0
```

##### SUMMARY
I have a lot of VMs and folders in my vcenter and _build_folder_map function take approximately 3 minutes to run.
Have you an idea to accelerate it ?

_Copied from original issue: ansible/ansible-modules-extras#3490_

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.3

##### SUMMARY

If your vcenter has unique VM names, there is no need to do the existing expensive lookups through the complete vCenter object store.

This change implements a new `unique_names:` option (as suggested by @jctanner) and blazingly fast finds a matching VM.

It supports the `name_match:` to find the first or last match (in case your names were not unique after all).

Quick tests shows that the time to gather facts from an existing VM dropped from 3 minutes and 8 seconds to only 4 seconds, including the connection overhead and ansible playbook overhead ! Even with `name_match: last` (worst case) it takes 11 seconds.

This relates to #19417
This fixes #19064

### CODE REVIEW

**Comment by aperigault** [comment]
@dagwieers I'm happy to see your PR ! Have you plan to accelerate task when VM do not exist ?

**Comment by dagwieers** [comment]
@aperigault Yes, it is a requirement for me. The problem was identified by @nerzhul in build_folder_map() and/or build_folder_tree(). For large environments this takes a very long time to compile. My patch simply avoids it for gathering facts.

**Comment by nerzhul** [comment]
@dagwieers your way works very well, but i think i will look at your ideas to see if we can improve the current behaviour to prevent duplicating code paths

**Comment by aperigault** [comment]
@dagwieers @nerzhul The problem is the feature to search for a relative VM path. I think this feature is useless but maybe someone use this ?
I don't know if it's the good way but you can see my patch attached.
[accelerate_vmware_guest.txt](https://github.com/ansible/ansible/files/684450/accelerate_vmware_guest.txt)

**Comment by dagwieers** [comment]
@aperigault I would prefer your fix TBH over what exists now. Neverthelessl I prefer a (unique) VM-name based approach as that is the most common case for end-users.

**Comment by aperigault** [comment]
@dagwieers PR #19937

**Comment by jctanner** [comment]
@dagwieers can we close this one in favor of https://github.com/ansible/ansible/pull/19937 ?

**Comment by dagwieers** [comment]
Not yet please. Just as a reminder to myself that I'd like to do some tests under different conditions.

But please merge #19937 already.

**Pull request closed without merging**
