### PR TITLE
Ghilli3 patch 1

### PR DESCRIPTION
**Pull request by Ghilli3**
##### SUMMARY

Adding the `__init__.py` file and changing the module name to singular instead of plural per the Ansible Module Guidelines.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
fmgr_script.py

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/mnt/hgfs/cse/Documents/DevOps/fmgr-ansible/ansible_fmgr/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by Ghilli3** [comment]
Adding __init__.py file and renaming module name

**Comment by gundalow** [comment]
@Ghilli3 Hi, the file name is still plural.

Is this a rename of an existing module, if so which?

Where is the original code from?

needs_info

**Review by gundalow — CHANGES_REQUESTED** [review]
-1 till I understand what's going on

**Comment by Ghilli3** [comment]
Hi @gundalow I will be commit changes today and in that change, the file name will be singular.

The code is new for a new module, written from within Fortinet.  Let me know if you have any further questions.

Thanks

**Pull request closed without merging**
