### PR TITLE
BOTMETA: Add hannseman as docker_swarm_service maintainer

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
I propose to add @hannseman as a maintainer for docker_swarm_service.

@hannseman: this gives you `shipit` rights on docker_swarm_service PRs, and ansibot will CC you on any PR or issue referring to docker_swarm_service. If you want this (or not), please state so in this PR.

(If you ever want to stop down from this role, you can simply say so or create a PR similar to this one. So by saying yes, you're not selling your soul or something :) )

CC @jwitko @dariko

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

### CODE REVIEW

**Comment by hannseman** [comment]
Sure! I'll give it a shot 👍

**Comment by dariko** [comment]
shipit

**Comment by felixfontein** [comment]
Awesome! :)

**Comment by felixfontein** [comment]
It might get a few days to get this merged; I've read on IRC that there's a problem with the bot and that no new BOTMETA changes should be merged. I'll bug some people on IRC on Monday with this one...

**Review by gundalow — CHANGES_REQUESTED** [review]
This is good, though as Felix said, bit issue, so adding a negative review so we don't accidently merge.

**Comment by jwitko** [comment]
shipit

**Review by jwitko — APPROVED** [review]

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Tanner said we can merge, so merging.

**Pull request merged**
