### PR TITLE
add epoch_int to date_time facts

### LINKED ISSUE #72479: ansible_date_time.epoch is inconsistent across plattforms
##### SUMMARY

The value in ansible_date_time.epoch is inconsistent, depending on the plattform. 
To use the value in strftime you need an int.
But unfortunately: 
- Linux systems return an int
- en_us Windows systems return a float and you need to use | int to use it
- de_de Windows systems return an string with a comma and using | int will cause it to be 0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.builtin.setup

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/venv-ansible/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/venv-ansible/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
##### CONFIGURATION

```paste below
DEFAULT_ASK_PASS(/home/ansible/.ansible.cfg) = False
DEFAULT_BECOME(/home/ansible/.ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/ansible/.ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/ansible/.ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/ansible/.ansible.cfg) = root
DEFAULT_HOST_LIST(/home/ansible/.ansible.cfg) = ['/home/ansible/inventory']
DEFAULT_MANAGED_STR(/home/ansible/.ansible.cfg) = This file is managed by Ansible
DEFAULT_REMOTE_USER(/home/ansible/.ansible.cfg) = ansible
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible/.ansible.cfg) = /home/ansible/ansible.vault
HOST_KEY_CHECKING(/home/ansible/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
ansible <Windows 10 Pro 20H2 de_de host> -m setup | grep -i epoch
            "epoch": "1604518347,44416",

$ ansible <Windows 2016 x64 en_us host> -m setup | grep -i epoch
            "epoch": "1604518390.00315",

$ ansible <CentOS 8 host> -m setup | grep -i epoch
            "epoch": "1604515167",
```

##### EXPECTED RESULTS

ansible_date_time.epoch should always contain an integer

https://m.xkcd.com/1179

##### ACTUAL RESULTS

see above.

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
Add `epoch_int` to setup facts which always returns epoch as an integer.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/facts/system/date_time.py

### CODE REVIEW

**Comment by sivel** [comment]
I'd be super cautious on doing this. Users may be expecting it to be a float, and may only be dealing with distros and locales where it is consistent for them.  This could be seen as a backwards incompatible change.

**Comment by aminvakil** [comment]
@sivel 
Are you OK with changing this to int and marking it as a `breaking_change` or it's not worthy at all?

**Comment by sivel** [comment]
Typically the way we approach these, is that the current key must not be changed. But add another key or keys that are more explicit, like creating `epoch_int` and `epoch_float`

**Comment by aminvakil** [comment]
rebuild_failed

**Comment by bcoca** [comment]
Does not fix the original issue for windows, that should be fixed in the collection first https://github.com/ansible-collections/community.windows

**Comment by aminvakil** [comment]
@bcoca 
Is this OK? https://github.com/ansible-collections/ansible.windows/pull/123
I couldn't find something regarding `setup` in community.windows.

**Comment by aminvakil** [comment]
I'm not interested in contributing to a product owned by a company which will stabs its users in the back anymore!
https://blog.centos.org/2020/12/future-is-centos-stream/

**Comment by aminvakil** [comment]
Reopened in https://github.com/ansible/ansible/pull/73822.

**Pull request closed without merging**
