### PR TITLE
vmware_guest: Fix "KeyError: 'changed'" (#22564)

### PR DESCRIPTION
**Pull request by jctanner**
Due to how the result-dictionary is being used, in some codepaths it would have an empty dictionary.
This then is problematic if the code expects the 'changed' key later on.

I also improved the docs a bit, by clearly marking the parameter names and URL in the documentation.
(cherry picked from commit 895664f5391fbfc00b62fa0057f432c1737cfe7e)

##### SUMMARY

backport

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest.py

##### ANSIBLE VERSION

```
2.3
```

### CODE REVIEW

**Comment by nerzhul** [comment]
ansibot reports error i think

**Comment by mattclay** [comment]
I'm looking into the module validation issue. I should have a fix for it tomorrow.

**Comment by mattclay** [comment]
CI issues have been fixed. Tests are now passing.

**Review by pchauncey — COMMENTED** [review]
LGTM, tested with ansible 2.3.0 and vSphere 6.5

**Comment by nerzhul** [comment]
shipit

**Comment by nerzhul** [comment]
bot_status

**Comment by pchauncey** [comment]
shipit

**Comment by dagwieers** [comment]
Yeah, all very nice, but I have a PR that also fixes this documentation stuff which is open for 2 weeks and doesn't get merged. #24768

Ow this one is even older, and the stable-2.3 branch... Nevermind :)

**Pull request closed without merging**
