### PR TITLE
Tweak syntax in intro docs

### PR DESCRIPTION
**Pull request by jryans**
I've cleaned up some of the formatting and capitalization as I've been reading the intro docs.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this!

This looks good but can you recheck and/or explain the getting started line 61 change?  By going to ":" instead of "::" it seems it would no longer format the code block.

Thanks again!

**Comment by jryans** [comment]
I double-checked, it's correct. 

When you use the syntax statement, like `.. code-block:: bash`, you only want `:` on the previous line or else you end up with `.. code-block:: bash` displayed in the output. You can also verify if search for other instances of `.. code-block:: bash` in the file.

**Comment by mpdehaan** [comment]
Interesting, thanks, RST can be fun :)

Merging this now, much appreciated.

**Comment by mpdehaan** [comment]
Thanks!  This will appear next time we push docs.

**Pull request merged**
