### PR TITLE
Fix author name in the documentation

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

Fix author rendering in the documentation website

https://docs.ansible.com/ansible/devel/plugins/inventory/scaleway.html

UNKNOWN author error

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

`lib/ansible/plugins/inventory/scaleway.py`

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (specify_author aab3c11413) last updated 2018/07/24 11:01:56 (GMT +200)
  config file = None
  configured module search path = [u'/Users/sieben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sieben/workspace/ansible/lib/ansible
  executable location = /Users/sieben/workspace/ansible/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@sieben Thanks for the PR. Could you please change this for all other inventory plugins as well ?

- auto
- k8s
- openshift
- openstack

**Comment by remyleone** [comment]
How should we solve this when we have many authors? That is the case for:

- openstack
- k8s

**Comment by Akasurde** [comment]
@sieben You need to rename `authors` to `author` for one or more authors in each module because if you see this line https://github.com/ansible/ansible/blob/bf544c2200cdf18332e02f08de4d01f1ecc85c8f/docs/bin/plugin_formatter.py#L491 it expects `author` in doc string. plugin_formatter is responsible for generating the rst which generates HTML docs.

**Comment by remyleone** [comment]
Thanks :) Done

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@sieben Thanks for the contribution.

**Comment by gundalow** [comment]
Thanks for both spotting and fixing this. I've created https://github.com/ansible/community/issues/359 so we can spot this during CI

**Pull request merged**
