### PR TITLE
New module: ec2_ami_search

### PR DESCRIPTION
**Pull request by lorin**
This module will retrieve the AMI of the most recent EC2 image for a given operating system. 

Currently, only Ubuntu is supported.

Example usage:

```
- name: Lauch an Ubuntu 12.04 (Precise Pangolin) EC2 instance
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Get the Ubuntu precise AMI
    ec2_ami_search: distro=ubuntu release=precise region=us-west-1 store=instance-store
    register: ubuntu_image
  - name: Start the EC2 instance
    ec2: image={{ ubuntu_image.ami }} instance_type=m1.small key_name=mykey
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Seems like this might want to be a feature in the AMI module instead or a generic module and not Ubuntu specific?

**Comment by pas256** [comment]
Ooo nice idea. Well done @lorin.

I agree it would be good to be non-Ubuntu specific, but do other distros keep a parsable list of the most recent AMIs around? As far as I can tell, this is the official CentOS list:

http://wiki.centos.org/Cloud/AWS

... which leaves a lot to be desired. I guess the issue is there is no standard for this.

I do however like this _not_ being part of the `ec2_ami` module, as it would add too much clutter (code and parameters). The `ec2_ami` module already does a lot with creating and deleting AMIs. This does have a standard (well, an API) way of doing it.

If AMI search is the generic module, then rename this to something like `ec2_ami_search`, and add a `distro` parameter. Specify that only Ubuntu is supported, and let other distros come to the party over time.

**Comment by lorin** [comment]
I agree with @pas256 that it makes sense to keep this in a separate module. I've also made his recommended changes to make it a more generic `ec2_ami_search`.

**Comment by mpdehaan** [comment]
I'm still thinking about whether we want to merge this one to core or not.

Isn't there a nice way to say "query someone's library of images and get the one with this name"

Meaning, if you are deploying a real world architecture, and the distro suddenly updates from version X to X+1, I don't think you'd want to be surprised.

**Comment by lorin** [comment]
> Meaning, if you are deploying a real world architecture, and the distro suddenly updates from version X to X+1, I don't think you'd want to be surprised.

The "release" argument refers to a specific  version, so "release=precise" means Ubuntu 12.04 ("Precise Pangolin"). The updates are just point releases (e.g., 12.04.3), it isn't going to return, say, version 12.10. 

This is particularly important for Ubuntu images on EC2 because when Canonical does a point release update, they delete the old AMI from the EC2 catalog. That means that if an Ansible user hard-codes the AMI into their playbook, it will fail when they try to run if Canonical has since refreshed the image. That's exactly the type of surprise that this module is designed to prevent.

**Comment by pas256** [comment]
> Isn't there a nice way to say "query someone's library of images and get the one with this name"

Unfortunately no. You can search for AMIs, but the search includes many fields, none of them "official". For example, say you want CentOS in us-east-1, searching for "centos" returns 654 public images. "centos6" returns 110 AMIs.

Anyone can make an AMI public. This module saves lookups that we have all had to do many times over.

**Comment by mpdehaan** [comment]
So what in here is guaranteed to be unique here?  It seems they were able to register "precise" then?

**Comment by mpdehaan** [comment]
edit: nm, I see the URL csv read in there now

**Comment by electroniceagle** [comment]
What is guaranteed to be unique here is the AMI returned is exactly the one the canonical specifies as the correct base image for that EC2 region, storage type, machine type, etc.

**Comment by pas256** [comment]
I still think this is a good idea and a helpful module, even if it is quite niche for now.

**Comment by mpdehaan** [comment]
Team:  let's rename this to ec2_ami_search (docstring had "ubuntu in it") and make sure the version_added string is there and it indicates it only supports Ubuntu for now in the "notes" but that additions are welcome to it.

**Pull request merged**
