### PR TITLE
Add test for reboot & wait_for_connection on EOS & IOS

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

This probably shouldn't live here, but it is eos-specific

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

network_cli

### CODE REVIEW

**Review by cidrblock — COMMENTED** [review]
Can you see if `network_cli in connection` works? That would make this compatible with collections...

**Review by ganeshrn — APPROVED** [review]

**Comment by NilashishC** [comment]
We were hitting [cli prompt is not identified from the last received response window: b'show running-config\r\r\n'](https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_53/64853/41fdca86a7c53652db37fd38f70e7eda8bfd0bea/third-party-check/ansible-test-network-integration-nxos-cli-python36/3f8ba84/controller/ara-report/result/30d8adb2-77d8-48b9-9b5a-0186efe782e2/) for `nxos_vrf_af`. This PR seems to [fix](https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_53/64853/41fdca86a7c53652db37fd38f70e7eda8bfd0bea/third-party-check/ansible-test-network-integration-nxos-cli-python36/c07a5cf/controller/ara-report/reports/3a425f1f-947b-4b16-ac26-64e777e7ef9e.html) it as well.

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
