### PR TITLE
added tags to example roletest playbooks

### PR DESCRIPTION
**Pull request by fdavis**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Does tags as a string work there without giving it as f,o,o ?

I have some places to fix that elsewhere...

**Comment by mpdehaan** [comment]
BTW, example shouldn't tweak param2, that seems to be a weird param :)

**Comment by fdavis** [comment]
So should it be in a list [ 'foo' ] ?
Or by fix do you mean changing others from a list to just the string?

**Comment by mpdehaan** [comment]
no problem, I will correct the docs, I am kind of picky about those.

will keep this open so I don't forget :)

**Comment by mpdehaan** [comment]
done, thanks!

**Pull request closed without merging**
