### PR TITLE
module: aws_s3 - add custom m5sum to header for comparing multipart uploads

### PR DESCRIPTION
**Pull request by mchaffe**
##### SUMMARY
Allow a custom md5 metadata header for comparison of large, multipart uploads. The current ETag header is ignored if it was generated from a multipart upload

Related #23547 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
aws_s3

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 08bffbcbaa) last updated 2017/10/05 11:13:29 (GMT -400)
  config file = None
  configured module search path = [u'/Users/gerry/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gerry/src/ansible/lib/ansible
  executable location = /Users/gerry/src/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### ADDITIONAL INFORMATION

Currently multipart uploads are rejected from comparison which means files a re-downloaded for option `overwrite: different`
https://github.com/ansible/ansible/blob/95e1d91d5d5120f5a6f219cb72064c8b91eda181/lib/ansible/modules/cloud/amazon/aws_s3.py#L281-L282

Added an option to allow for a custom metadata field to be referenced and checked instead for both `get` and `put` actions.

Example task would be:
```
- name: GET an object but don't download if the file checksums match. New in 2.0
  aws_s3:
    bucket: mybucket
    object: /my/desired/key.txt
    dest: /usr/local/myfile.txt
    mode: get
    overwrite: different
    meta_md5: md5sum
```

### CODE REVIEW

**Comment by willthames** [comment]
This change needs tests adding to test/integration/targets/aws_s3

**Comment by roadmapper** [comment]
Is there any reason why it would be a bad idea to compute the AWS S3 ETag value instead of providing it as metadata? I just tested `get` with this method and it seemed to work correctly (need to test `put`). I don't always upload files with the aws_s3 module, so remembering to put in the metadata for the proper MD5 checksum might be tricky.

https://github.com/ansible/ansible/compare/devel...roadmapper:feature/s3-checksum
```python
def keysum_compare(local_file, s3_keysum):
    if '-' in s3_keysum:  # Check for multipart, etag is not a proper MD5 sum
        parts = int(s3_keysum.split('-')[1])
        file_size = os.stat(local_file).st_size
        chunk_size = int(math.ceil(float(file_size) / parts / 1024 / 1024))
        md5s = []
        with open(local_file, 'rb') as fp:
            while True:
                data = fp.read(chunk_size * 1024 * 1024)
                if not data:
                    break
                hash = hashlib.md5(data)
                md5s.append(hash)

        # can this happen?
        if len(md5s) == 1:
            return s3_keysum == '{}'.format(md5s[0].hexdigest())

        digests = b''.join(m.digest() for m in md5s)
        digests_md5 = hashlib.md5(digests)
        local_keysum = '{}-{}'.format(digests_md5.hexdigest(), len(md5s))
        return s3_keysum == local_keysum
    else:
        local_keysum = hashlib.md5(dest).hexdigest()
        return s3_keysum == local_keysum
```

**Comment by ryansb** [comment]
I'd agree - it's preferable to have it generate the md5 than to have to calculate it elsewhere and pass it through. For multipart uploads, I remember the etag not being a single md5sum but an md5 of several individual parts.

**Comment by s-hertel** [comment]
I'd also prefer that approach @roadmapper.

**Comment by s-hertel** [comment]
Fixed in f20af4b9097edc4ff3136f93c74049e7a43cf6be.

**Pull request closed without merging**
