### PR TITLE
Fix if the route table changed to none

### LINKED ISSUE #49419: azure_rm_subnet fails when existing subnet had route_table
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* azure_rm_subnet
##### ANSIBLE VERSION

```paste below
ansible 2.7.4
  config file = None
  configured module search path = [u'$HOME/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible
  executable location = $HOME/.virtualenvs/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Try to execute the module against an existing subnet with route_table defined

```yaml
      - azure_rm_subnet:
          name: "{{ network.subnet }}"
          virtual_network_name: "{{ network.vnet }}"
          resource_group: "{{ network.group }}"
          address_prefix_cidr: "{{ network.cidr }}"
# make sure subnet exists and has a routing table defined

```

##### EXPECTED RESULTS

Subnet should not be created. `changed` value depends on whether defined `route_table` matches the existing route_table (probably should modify existing route_table if not.)

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "No handlers could be found for logger \"keyring.backend\"\nTraceback (most recent call last):\n  File \"/home/yfried/.ansible/tmp/ansible-tmp-1543756742.69-22661400925495/AnsiballZ_azure_rm_subnet.py\", line 261, in <module>\n    _ansiballz_main()\n  File \"/home/yfried/.ansible/tmp/ansible-tmp-1543756742.69-22661400925495/AnsiballZ_azure_rm_subnet.py\", line 251, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/yfried/.ansible/tmp/ansible-tmp-1543756742.69-22661400925495/AnsiballZ_azure_rm_subnet.py\", line 119, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 348, in <module>\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 344, in main\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 208, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/ansible_azure_rm_subnet_payload.zip/ansible/module_utils/azure_rm_common.py\", line 308, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 259, in exec_module\nUnboundLocalError: local variable 'route_table' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

```

### PR DESCRIPTION
**Pull request by yuwzho**
##### SUMMARY

Fixes #49419

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below
2.7.0
```

### CODE REVIEW

**Comment by gundalow** [comment]
@jerrynn @Fred-sun could you please test this PR and confirm if it fixes your issue in https://github.com/ansible/ansible/issues/49419

**Comment by Fred-sun** [comment]
@gundalow I have tried but fail, fail info same with report. Thanks!
@yuwzho  could you help recheck it? Thanks!
```e.g.
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/fred/.ansible/tmp/ansible-tmp-1544006820.25-276246544239643/AnsiballZ_azure_rm_subnet.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/fred/.ansible/tmp/ansible-tmp-1544006820.25-276246544239643/AnsiballZ_azure_rm_subnet.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/fred/.ansible/tmp/ansible-tmp-1544006820.25-276246544239643/AnsiballZ_azure_rm_subnet.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_subnet_payload_TL_IYA/__main__.py\", line 386, in <module>\n  File \"/tmp/ansible_azure_rm_subnet_payload_TL_IYA/__main__.py\", line 382, in main\n  File \"/tmp/ansible_azure_rm_subnet_payload_TL_IYA/__main__.py\", line 228, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_TL_IYA/ansible_azure_rm_subnet_payload.zip/ansible/module_utils/azure_rm_common.py\", line 310, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_TL_IYA/__main__.py\", line 279, in exec_module\nUnboundLocalError: local variable 'route_table' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
	to retry, use: --limit @/home/fred/task/49419/1.retry

**Comment by yuwzho** [comment]
@Fred-sun Please re-test

**Comment by Fred-sun** [comment]
Thanks yuwzhou, I have tested and got success result, Please review the test result. 
@gundalow Please help re-review this and push for merged. Thanks! 
```e.g.
TASK [Create subnet with router table] ***************************************************************************
changed: [localhost]

TASK [debug] *****************************************************************************************************
ok: [localhost] => {
    "output01": {
        "changed": true, 
        "failed": false, 
        "state": {
            "address_prefix": "10.0.1.0/24", 
            "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG04/providers/Microsoft.Network/virtualNetworks/mynetwork01/subnets/mysubnet01", 
            "name": "mysubnet01", 
            "network_security_group": {
                "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/cleanupservice/providers/Microsoft.Network/networkSecurityGroups/rg-cleanupservice-nsg123", 
                "name": "rg-cleanupservice-nsg123", 
                "resource_group": "cleanupservice"
            }, 
            "provisioning_state": "Succeeded", 
            "route_table": {
                "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG04/providers/Microsoft.Network/routeTables/foobar", 
                "name": "foobar", 
                "resource_group": "myRG04"
            }
        }
    }
}

TASK [update the subnet without router table] ********************************************************************
changed: [localhost]

TASK [debug] *****************************************************************************************************
ok: [localhost] => {
    "output": {
        "changed": true, 
        "failed": false, 
        "state": {
            "address_prefix": "10.0.1.0/24", 
            "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG04/providers/Microsoft.Network/virtualNetworks/mynetwork01/subnets/mysubnet01", 
            "name": "mysubnet01", 
            "network_security_group": {
                "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/cleanupservice/providers/Microsoft.Network/networkSecurityGroups/rg-cleanupservice-nsg123", 
                "name": "rg-cleanupservice-nsg123", 
                "resource_group": "cleanupservice"
            }, 
            "provisioning_state": "Succeeded", 
            "route_table": {}
        }
    }
}

PLAY RECAP *******************************************************************************************************
localhost                  : ok=8    changed=2    unreachable=0    failed=0    skipped=0

**Review by zikalino — APPROVED** [review]

**Pull request merged**
