### PR TITLE
added gcp_kms filters filter plugin

### PR DESCRIPTION
**Pull request by ericsysmin**
##### SUMMARY
new filter to permit encrypt and decrypt via gcp_kms

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
gcp_kms_encrypt
gcp_kms_decrypt

##### ADDITIONAL INFORMATION
Allows encryption and decryption against GCP KMS

```paste below
vars:
  encrypted_myvar: "{{ var | b64encode | gcp_kms_encrypt(auth_kind='serviceaccount',
    service_account_file='gcp_service_account_file', projects='default',
    key_ring='key_ring', crypto_key='crypto_key') }}"
  decrypted_myvar: "{{ encrypted_myvar | gcp_kms_decrypt(auth_kind='serviceaccount',
    service_account_file=gcp_service_account_file, projects='default',
    key_ring='key_ring', crypto_key='crypto_key') }}"
```

### CODE REVIEW

**Comment by ericsysmin** [comment]
@rambleraptor can you do the community review?

**Comment by rambleraptor** [comment]
This looks great! Thanks for the PR

shipit

**Comment by rambleraptor** [comment]
@gundalow can you take a look at this?

**Comment by kustodian** [comment]
This looks great. Just a thing I was looking for.

Would you be able to add environment variables as a fallback, so that it's easier to work with the filter? You can check which vars exist in [gcp_utils.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/gcp_utils.py#L190).

**Comment by ericsysmin** [comment]
> This looks great. Just a thing I was looking for.
> 
> Would you be able to add environment variables as a fallback, so that it's easier to work with the filter? You can check which vars exist in [gcp_utils.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/gcp_utils.py#L190).

You can make the changes you want.

**Comment by rambleraptor** [comment]
Hi, can I get somebody to look at this?

**Comment by PedDavid** [comment]
@ericsysmin I'm trying to use this filter but it's failing with the following message:
`"msg": "Please install the requests library"`

I've already installed the library, through pip but I think filters are not using it for some reason (modules do find it).
Any hint about this?

**Comment by caphrim007** [comment]
@PedDavid in my experience this happens because the ansible being used was installed with a different python install than what is being used remotely.

For example, if you use ansible in a virtualenv, and you pip installed'd requests in the system python but did not specify the ansible_python_interpreter for your host (or vice versa).

Do you have an example play that repro's the issue?

**Pull request merged**
