### PR TITLE
Changing LBName used by same task inside azure_rm_loadbalancer

### LINKED ISSUE #58933: azure_rm_loadbalancer intergration test target causing resource leakage on azure cloud
##### SUMMARY
azure_rm_loadbalancer intergration test target causing resource leakage on azure cloud
The specific task to create lb with multiple options is for some reason causing resource leakage on azure cloud account used for ansible-ci testing

The exact reason is still unknown but I want to try to make sure it can get fixed with same task doing operation on two separate lb instead on named ^lbname

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_loadbalancer integration test

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abehl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
Running ansible-ci on azure_rm_loadbalancer integration target causes this
In this case PublicIP is is tried to be deleted while LB attached to it
```

##### EXPECTED RESULTS

Systematic deletion of LB > PublicIP should happen and allow LB and PublicIP to be deleted

##### ACTUAL RESULTS

```paste below
Public IP address /subscriptions/6d22db98-3e5f-4ab9-bdf9-2f911a2775f7/resourceGroups/ansible-core-ci-prod-a50bbaf0-0315-4286-815e-2c877e8d4b64-1/providers/Microsoft.Network/publicIPAddresses/pipa26c0a5f585 can not be deleted since it is still allocated to resource /subscriptions/6d22db98-3e5f-4ab9-bdf9-2f911a2775f7/resourceGroups/ansible-core-ci-prod-a50bbaf0-0315-4286-815e-2c877e8d4b64-1/providers/Microsoft.Network/loadBalancers/lbc26c0a5f581/frontendIPConfigurations/frontendipconf0. 
```

### PR DESCRIPTION
**Pull request by anshulbehl**
fixes ansible#58933

### CODE REVIEW

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
@anshulbehl This will need to be backported to the stable branches once merged to avoid problems caused by the nightly runs on those branches.

**Comment by mattclay** [comment]
@anshulbehl Backports for stable-2.7 and stable-2.6 are also needed to avoid any issues caused by the nightly runs on those branches.

**Comment by anshulbehl** [comment]
@mattclay Checked the stable 2.7 and 2.6, the task to recreate the LB is not there in those branches, I would argue that the issue doesn't even exists on those. let me know what you think?

**Comment by mattclay** [comment]
@anshulbehl In that case backports won't be needed. Thanks for checking.

**Pull request merged**
