### PR TITLE
Merge varFind and varLookup

### PR DESCRIPTION
**Pull request by dhozac**
This allows escaping variables by doing \$foo.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Due to the relative (and neccessary) complexity of the code, can you explain what "varFindLimitSpace" is meant to do?   I'm having a bit of difficulty inferring from the function name -- Ideally we'd probably want this in the comments too.

Another thing I'm wondering is whether varReplaceWithItems can be eliminted, or maybe be done as two steps?

**Comment by dhozac** [comment]
It limits the variable search space, i.e. ${hostvars.{node}.var} will first limit it to hostvars, then node, then var.

Not in any kind of sane way. It could template things out as strings and then use eval to get it back into a data structure form, but that seems nuts, and would likely break rather often. I'm not sure what two steps you might be referring to.

**Comment by mpdehaan** [comment]
"${hostvars.{node}.var} "

I am having difficulty understanding what that syntax would do.

Did you mean ${node} ?

**Comment by dhozac** [comment]
No, the {} is the escape for dots, as node names typically include them.

**Comment by mpdehaan** [comment]
Ok, I'll merge to a private branch and read over this shortly.  Thanks!

**Pull request merged**
