### PR TITLE
[2.7] docker_swarm: backport of various bugfixes and extended/improved integration tests

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #52825, #52893, #52895, ~~#52946~~, #52976, #53005, #53003, #53039 and #53035 to `stable-2.7`. This is a sequence of new/extended/improved integration tests (now covering most options, mostly except swarm joining and node removing as that requires more than one node in a swarm cluster) and bugfixes found while working on the tests.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docker_swarm

### CODE REVIEW

**Comment by felixfontein** [comment]
I had to remove the use of `DifferenceTracker` (not available in stable-2.7) from the backport of #52895; I removed the debug output lines removed by #52946 in the same edit, so a cherry-pick of #52946 is no longer needed.

**Comment by felixfontein** [comment]
CC @WojciechowskiPiotr @tbouvet

**Comment by felixfontein** [comment]
Also included a backport of #53083 (small docs change).

**Comment by abadger** [comment]
Merged for the 2.7.9 release.

**Comment by felixfontein** [comment]
@abadger thanks for merging this!

**Pull request merged**
