### PR TITLE
Add a basic guide describing Vagrant and Ansible

### PR DESCRIPTION
**Pull request by tgerla**
This adds to the docs a basic guide describing how to use Ansible and Vagrant together. I tried not to duplicate a lot of Vagrant documentation, but instead just get users started and then link to the Vagrant docs for the details.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this.

Some thoughts / questions.

Is there a way we can document for how to rerun the configuration against the existing instance to check what the playbook does if run a second time?  

Are there other flags in the Vagrant config people may be interested in or that we should document?

Do we need to include some instructions about making sure Ansible is installed, or is hacking/env-setup enough or not, etc?   Multi-tier apps?

**Comment by tgerla** [comment]
Sure, I added a couple of sections talking about re-running configurations with "vagrant provision", and an Ansible installation link. I don't want to duplicate a lot of Vagrant docs but I called out a couple of particularly useful Vagrant config bits.

Regarding multi-tier apps, this is really something I want to address, but right now Vagrant doesn't handle it very well. If you have a multi-machine setup, Vagrant runs ansible-playbook once for each, with a separate inventory. This is something I plan on bringing up with Vagrant. It would be excellent if the provisioning were run just once at the end for all machines.

**Comment by mpdehaan** [comment]
Thanks, I've merged this in.  This will go really well with the Rax guide as that evolves and the upgraded EC2 guide, etc. I suspect since we have a lot of Vagrant users they'll also add things as we go along.

This isn't pushed yet, but we'll update later.

(Since this does create a new page, I assume we've added the neccessary glue to our website gizmo?)

**Comment by tgerla** [comment]
Yep, I added the glue. Thanks!

**Pull request merged**
