### PR TITLE
Add Zabbix inventory plugin

### PR DESCRIPTION
**Pull request by gregbuehler**
This adds http://www.zabbix.com/ as an inventory source.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Greg,

This looks very good, can you standardize this on a 4 space indent across the file and test the updates?  I think it is ready to merge after this.

Since you are using zabbix, I would also be interested if any zabbix monitoring modules made sense?  It would be nice to have it available for rolling update type support like we have with nagios and other modules too.

Thanks!

**Comment by gregbuehler** [comment]
Hi mpdehaan,

I guess a monitoring plugin for Zabbix would be a separate pull request if/when I need that support unless somebody else does that.

This is basically just to circumvent static inventory creation for a large existing deployment.

Thanks!

**Comment by resmo** [comment]
hi @gregbuehler 

I wanted to get started with a zabbix module, did you already start? Can I help? :)

**Comment by gregbuehler** [comment]
@resmo The most I have done is reading the Nagios module. I'd say have at it!

**Comment by resmo** [comment]
@gregbuehler I just rebased your 2 commits into one. Hoping for the merge. Thanks for your work.

**Comment by resmo** [comment]
@jimi1283 can be closed. already merged in #3883.

**Comment by jimi-c** [comment]
Closed, thanks!

**Pull request closed without merging**
