### PR TITLE
Backport/2.7/46623

### PR DESCRIPTION
**Pull request by amuraleedhar**
##### SUMMARY

Cherry-pick #46623 to 2.7.2
This changes are pertaining to adding support for Bacon switch from Lenovo. Rule files are updated an documentation as well.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
lib\ansible\modules\network\cnos\cnos_backup.py
lib\ansible\modules\network\cnos\cnos_bgp.py
lib\ansible\modules\network\cnos\cnos_conditional_command.py
lib\ansible\modules\network\cnos\cnos_conditional_template.py
lib\ansible\modules\network\cnos\cnos_config.py
lib\ansible\modules\network\cnos\cnos_factory.py
lib\ansible\modules\network\cnos\cnos_facts.py
lib\ansible\modules\network\cnos\cnos_image.py
lib\ansible\modules\network\cnos\cnos_interface.py
lib\ansible\modules\network\cnos\cnos_portchannel.py
lib\ansible\modules\network\cnos\cnos_reload.py
lib\ansible\modules\network\cnos\cnos_save.py
lib\ansible\modules\network\cnos\cnos_showrun.py
lib\ansible\modules\network\cnos\cnos_rollback.py
lib\ansible\modules\network\cnos\cnos_template.py
lib\ansible\modules\network\cnos\cnos_vlag.py
lib\ansible\modules\network\cnos\cnos_vlan.py
lib\ansible\modules\network\enos\enos_config.py
lib\ansible\modules\network\enos\enos_facts.py
lib\ansible\module_utils\network\cnos\cnos_devicerules.py

##### ANSIBLE VERSION
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/sheru/ansible/lib/ansible
  executable location = /home/ansible/sheru/ansible/bin/ansible

##### ADDITIONAL INFORMATION
Back porting as switch is released early from 2.8

### CODE REVIEW

**Comment by mattclay** [comment]
Closing and re-opening to restart CI.

**Comment by abadger** [comment]
@Qalthos Could you confirm whether this is a bugfix or a feature?  (bugixes are eligible for backporting but features need to wait for the next major release [2.8])

**Comment by Qalthos** [comment]
@amuraleedhar abadger is correct, the documentation changes are fine, and fixing the argspecs to reflect the changes to the module that already exist are fine. But adding support for new hardware is a feature, and we should not accept this for 2.7 as-is.

Remove the changes to devicerules, the cnos doc_fragment, and the test READMEs, and update the changelog fragment to match the changes, and this will probably be okay.

**Comment by amuraleedhar** [comment]
Done.  Removed the changes to devicerules, the cnos doc_fragment, and the test READMEs, and update the changelog fragment to match the changes, and this will probably be okay.

**Review by Qalthos — APPROVED** [review]

**Comment by abadger** [comment]
Merged for the 2.7.5 release.  Thanks!

**Pull request merged**
