### PR TITLE
Linode inventory script improvements

### PR DESCRIPTION
**Pull request by NickBall**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
contrib/inventory/linode.py

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/nick/dev/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

- Changes to make this inventory script consistent with the other inventory scripts
-- Add _meta/hostvars to inventory output with instance details
-- Add a "linode" global host group containing all the hosts

*Before*
```
nick@gizmo:~/tmp/benchmark/ansible$ ./inventory/linode.py --list
{
  "64841": [
    "sawyer"
  ], 
  "2002301": [
    "lima"
  ], 
  "2316311": [
    "monitor"
  ], 
  "": [
    "sawyer", 
    "lima", 
    "monitor"
  ], 
  "fremont": [
    "sawyer", 
    "lima", 
    "monitor"
  ]
}
```

*After*
```
nick@gizmo:~/tmp/benchmark/ansible$ ./inventory/linode.py --list
{
  "64841": [
    "sawyer"
  ], 
  "2002301": [
    "lima"
  ], 
  "2316311": [
    "monitor"
  ], 
  "": [
    "sawyer", 
    "lima", 
    "monitor"
  ], 
  "_meta": {
    "hostvars": {
      "lima": {
        "alert_bwin_enabled": true, 
        "alert_bwin_threshold": 10, 
        "alert_bwout_enabled": true, 
        "alert_bwout_threshold": 10, 
        "alert_bwquota_enabled": true, 
        "alert_bwquota_threshold": 80, 
        "alert_cpu_enabled": true, 
        "alert_cpu_threshold": 90, 
        "alert_diskio_enabled": true, 
        "alert_diskio_threshold": 10000, 
        "ansible_host": "173.255.0.01", 
        "ansible_ssh_host": "173.255.0.1", 
        "api_id": 2002301, 
        "backup_weekly_daily": 0, 
        "backup_window": 0, 
        "create_dt": "2016-06-16 18:49:26.0", 
        "datacenter_city": "fremont", 
        "datacenter_id": 3, 
        "display_group": "", 
        "label": "lima", 
        "private_ip": "192.168.0.2", 
        "public_ip": "173.255.0.1", 
        "status": 1, 
        "total_hd": 24576, 
        "total_ram": 2048, 
        "total_xfer": 2000, 
        "watchdog": true
      }, 
      "monitor": {
        "alert_bwin_enabled": true, 
        "alert_bwin_threshold": 10, 
        "alert_bwout_enabled": true, 
        "alert_bwout_threshold": 10, 
        "alert_bwquota_enabled": true, 
        "alert_bwquota_threshold": 80, 
        "alert_cpu_enabled": true, 
        "alert_cpu_threshold": 90, 
        "alert_diskio_enabled": true, 
        "alert_diskio_threshold": 10000, 
        "ansible_host": "104.200.0.13", 
        "ansible_ssh_host": "104.200.0.13", 
        "api_id": 2316311, 
        "backup_weekly_daily": 0, 
        "backup_window": 0, 
        "create_dt": "2016-09-22 21:16:49.0", 
        "datacenter_city": "fremont", 
        "datacenter_id": 3, 
        "display_group": "", 
        "label": "monitor", 
        "private_ip": "192.168.1.2", 
        "public_ip": "104.200.0.13", 
        "status": 1, 
        "total_hd": 24576, 
        "total_ram": 2048, 
        "total_xfer": 2000, 
        "watchdog": true
      }, 
      "sawyer": {
        "alert_bwin_enabled": true, 
        "alert_bwin_threshold": 5, 
        "alert_bwout_enabled": true, 
        "alert_bwout_threshold": 5, 
        "alert_bwquota_enabled": true, 
        "alert_bwquota_threshold": 80, 
        "alert_cpu_enabled": true, 
        "alert_cpu_threshold": 90, 
        "alert_diskio_enabled": true, 
        "alert_diskio_threshold": 1000, 
        "ansible_host": "74.207.1.2", 
        "ansible_ssh_host": "74.207.1.2", 
        "api_id": 64841, 
        "backup_weekly_daily": 0, 
        "backup_window": 7, 
        "create_dt": "2014-09-20 06:08:10.0", 
        "datacenter_city": "fremont", 
        "datacenter_id": 3, 
        "display_group": "", 
        "label": "sawyer", 
        "private_ip": "192.168.2.8", 
        "public_ip": "74.207.1.2", 
        "status": 1, 
        "total_hd": 49152, 
        "total_ram": 4096, 
        "total_xfer": 3000, 
        "watchdog": true
      }
    }
  }, 
  "fremont": [
    "sawyer", 
    "lima", 
    "monitor"
  ], 
  "linode": [
    "sawyer", 
    "lima", 
    "monitor"
  ]
}

```

### CODE REVIEW

**Comment by s-hertel** [comment]
cc/ @InTheCloudDan @rwaweber @zbal @gsong 

Would somone review this, please?

**Comment by rwaweber** [comment]
@s-hertel Yeah, I can take a look at it tonight.

**Comment by InTheCloudDan** [comment]
I just pulled it and it works, the only question I have with it is should it be an additional flag to get the meta information? It makes the output a lot more verbose by default.

@s-hertel is there any way for us to get added to these PRs by ansibot automatically?

**Comment by rwaweber** [comment]
> should it be an additional flag to get the meta information

I don't think so, convention with other inventory(DO, EC2) utilities seems to include the `"_meta"` key by default.

However, on that same vein, I'd like to see a flag added for toggling pretty printing, since all calls of `json_format_dict` seem to be hardcoded as `True`. @InTheCloudDan, what do you think?

**Comment by rwaweber** [comment]
@NickBall Would you wanna update the branch for the linty things [here](https://github.com/ansible/ansible/pull/19329#issuecomment-319175847)?

**Comment by NickBall** [comment]
@rwaweber, lint issues fixed, nice to see this PR back from the dead :-). Thanks!

**Comment by rwaweber** [comment]
Thanks, LGTM! 

I think that this probably isn't the place to take care of my nit with the way that we call json_format_dict. I'll probably get my own PR drafted since I'm the one raising issue with it. 😜

**Comment by rwaweber** [comment]
bot_status

**Comment by rwaweber** [comment]
shipit

**Comment by InTheCloudDan** [comment]
shipit

**Comment by s-hertel** [comment]
Thanks so much everyone :)

**Pull request merged**
