### PR TITLE
XenServer: Documentation improvements and fixes for XenServer related modules

### PR DESCRIPTION
**Pull request by bvitnik**
- More info added to module docs.
 - Fixed errors and typos in module docs.
 - Added parameter types to module docs.
 - Some error messages are fixed and/or changed to be more helpful.
 - Some code comments changed and added.
 - Updated unit tests that test changed error messages.
 - Improved module examples.

##### SUMMARY
A number od small documentation changes.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
xenserver
xenserver_guest
xenserver_guest_facts
xenserver_guest_powerstate

##### ADDITIONAL INFORMATION
Only doc related changes, no code changes.

### CODE REVIEW

**Comment by bvitnik** [comment]
Note: CI seems to be failing randomly. Will close and reopen PR later.

**Comment by bvitnik** [comment]
bot_status

**Comment by bvitnik** [comment]
@Akasurde Thanks for taking this PR for review. CI looks OK now.

**Review by Akasurde — APPROVED** [review]

**Comment by bvitnik** [comment]
@Akasurde Can I get one "shipit" here :) ?

**Pull request merged**
