### PR TITLE
ISSUE-22382 Added ansible_ssh_private_key for paramiko_ssh

### PR DESCRIPTION
**Pull request by Dirrk**
##### SUMMARY

For more detailed information please see here https://github.com/ansible/ansible/issues/22382.
> When defining hosts, I would like to be able to use an ssh private key that is stored securely using ansible-vault.

I chose to add a variable `ansible_ssh_private_key` that allows the user to define the ssh key as a string instead of a file.  This route seemed the best because it allows both dynamic / hard coded inventory to take advantage of it.  This approach was also the easiest to add without affecting other modules.

edit:  I have updated the PR to now work with the ssh and paramiko_ssh connection plugins.  I am open to other ways to solve the ssh plugin implementation because currently it copies vaults method of creating a temporary copy and then cleaning it up.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

plugin/connections/ssh

##### ANSIBLE VERSION

```
ansible 2.4.0 (ISSUE-22382 18bf22eba9) last updated 2017/03/18 10:23:18 (GMT -400)
  config file = /Users/drada/workspace/code/ansible/test/develop/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

Please see the issue linked here https://github.com/ansible/ansible/issues/22382
hosts
```
ansibletest
```

host_vars/ansibletest.yml
```yaml
ansible_host: 192.168.244.10
ansible_user: vagrant
ansible_connection: paramiko_ssh
ansible_ssh_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  SUPERSECUREKEYHERE
  -----END RSA PRIVATE KEY-----
```

run.yml
```yaml
 - name: testing
   hosts: all
   tasks:
     - name: run setup
       setup:
```

Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ansibletest" do |ansibletest|
    ansibletest.vm.box = "ubuntu/trusty64"
    ansibletest.vm.hostname = "ansibletest"
    ansibletest.vm.network :private_network, ip: "192.168.244.10"
    ansibletest.vm.provider "virtualbox" do |v|
        v.memory = 512
    end
  end
end
```

Before:
```
[drada@Dereks-MacBook-Pro develop] ansible-playbook -i hosts run.yml

PLAY [testing] ************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
fatal: [ansibletest]: UNREACHABLE! => {"changed": false, "msg": "Authentication failed.", "unreachable": true}
	to retry, use: --limit @/Users/drada/workspace/code/ansible/test/develop/run.retry

PLAY RECAP ****************************************************************************************************************************
ansibletest                : ok=0    changed=0    unreachable=1    failed=0
```

After:
```
[drada@Dereks-MacBook-Pro develop] git checkout ISSUE-22382
Switched to branch 'ISSUE-22382'
Your branch is up-to-date with 'origin/ISSUE-22382'.
[drada@Dereks-MacBook-Pro develop] ansible-playbook -i hosts run.yml

PLAY [testing] ************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [ansibletest]

TASK [run setup] **********************************************************************************************************************
ok: [ansibletest]

PLAY RECAP ****************************************************************************************************************************
ansibletest                : ok=2    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by sivel** [comment]
I have a thought, that hasn't been tested or fully thought out, but I wonder whether using `os.mkfifo` might be better than a temp file?

If there is an exception (maybe even KeyboardInterrupt) between creating the file, and deleting it, we are leaving these keys on the filesystem.

**Comment by Spoon4** [comment]
what about this feature ?

**Comment by getong** [comment]
Anything new?

**Comment by cmcornejocrespo** [comment]
Really looking forward to having this feature add. Any updates on this????

**Comment by Geethree** [comment]
Indeed. Eagerly watching this issue.

**Comment by webknjaz** [comment]
@Dirrk thanks for starting this PR. I'm thinking of picking it up. I've got a prototype for ssh connection plugin using agent in here:
https://github.com/webknjaz/mrgall-ansible/blob/4de2774/connection_plugins/ssh.py#L410-L450
I think I'll push changes right into your branch updating this PR. I hope you don't have any objections.

**Comment by Meera94** [comment]
eagerly awaiting this feature. @webknjaz what is the status of the feature?

**Comment by agh** [comment]
Seems like this would be super cool, combined with `ansible-vault encrypt_string`.

**Comment by getong** [comment]
Quite a long time, it is almost two years.

**Comment by nurdie** [comment]
I'm also waiting on this.
I'd love to be able to pass hashicorp vault keys straight in to ansible_ssh_private_key

**Comment by mkkeffeler** [comment]
same here for cyberark conjur! this would be very useful

**Comment by tziska2** [comment]
This would be a highly useful fix for a problem we have been facing.

**Pull request closed without merging**
