### PR TITLE
Remove ansible.utils.py3compat

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY

Remove `ansible.utils.py3compat` as it is no longer needed.

Note that we hardcoded `utf-8` encoding in our use of this `os.environ` compat, but `os.environ` uses `sys.getfilesystemencoding`.  However, since we require `sys.getfilesystemencoding()` to be `utf-8` now, via checks in `ansible.cli` this is equivalent.

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by webknjaz** [comment]
Can any of this be seen as [public API](https://www.hyrumslaw.com)? Do we need deprecations?

**Comment by sivel** [comment]
> Can any of this be seen as [public API](https://www.hyrumslaw.com)? Do we need deprecations?

I checked every collection on galaxy, and there is no use of it.

**Comment by jborean93** [comment]
There might be roles that use this module util, I think it would be safer to do the normal deprecation cycle just in case.

**Comment by sivel** [comment]
@jborean93 can you check the last commit and let me know what you think?

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Looks good to me.

**Pull request merged**
