### PR TITLE
[WIP] Optionally use packaging.version if available, falling back to LooseVersion where not

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY

Optionally use packaging.version if available, falling back to LooseVersion where not

Alternate implementation from https://github.com/ansible/ansible/pull/34427

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

various

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by sivel** [comment]
bot_skip

**Comment by alikins** [comment]
We could add our own version_compare util module to share the try/except import Version stuff.

Maybe something like https://github.com/ansible/ansible/commit/cf33a7b59ad15403cfa208013e6cd3037eb9cc2b

(That only includes updating lib/ansible/galaxy/role.py as an example, the rest of the code would need updates as well)

**Comment by alikins** [comment]
The main downside with the version_compare.py approach is that the behavior of the module (and therefore any compares that use) could change depending on what dependencies are installed. That could potentially make debugging/troubleshooting more difficult. 

Though I guess that is true for any conditional imports including this branch as well.

**Comment by sivel** [comment]
I just wanted to share this approach.  I've added this topic to the core meeting agenda.

**Comment by mattclay** [comment]
CI failure in integration tests due to traceback:

```
Traceback (most recent call last):
  File "/tmp/ansible_cXtc1i/ansible_module_git.py", line 1185, in <module>
    main()
  File "/tmp/ansible_cXtc1i/ansible_module_git.py", line 1065, in main
    git_version_used = git_version(git_path, module)
  File "/tmp/ansible_cXtc1i/ansible_module_git.py", line 908, in git_version
    return Version(rematch.groups()[0])
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/packaging/version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pip._vendor.packaging.version.InvalidVersion: Invalid version: '2.7.4 (Apple Git-66)'
```

The `openssl_privatekey` tests are also failing on all platforms, here's one of them:

https://app.shippable.com/github/ansible/ansible/runs/49849/22/tests

**Comment by sivel** [comment]
We won't be pursuing this now.  We'll handle issues with py3 and LooseVersion on a case by case basis for now.

**Pull request closed without merging**
