### PR TITLE
Escaping backticks again.

### PR DESCRIPTION
**Pull request by aquach**
more escaping :+1:

### CODE REVIEW

**Comment by aquach** [comment]
Wait, I'm running into a problem when escaping. It'll output something like `db_name._` rather than `db_name`._. Let me work on it a bit.

**Comment by sebslomski** [comment]
Is there a fix for this issue? It's still not working.

**Comment by aquach** [comment]
It got too hairy and I chose not to keep trying to fix it. Escaping is
always a nasty thing. I ended up renaming our db names to identifiers that
don't need back ticks.

**Comment by sebslomski** [comment]
Do you have a fix/idea for something like this?

```
   - name: link zip lib
     command: ln -s /usr/lib/\`uname -i\`-linux-gnu/libz.so /usr/lib/
```

**Comment by aquach** [comment]
My fix was exclusively for the mysql module, not for running commands. You
could probably do the example you provided if you change command to shell.

**Pull request closed without merging**
