### PR TITLE
OVH: Add new module ovh api

### PR DESCRIPTION
**Pull request by YoannAtOVH**
##### SUMMARY

Add new module ovh_api to interact with API and support the specific authentication and hearders of the provider OVH

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

ovh_api

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by YoannAtOVH** [comment]
@pascalheraud is possible for you to review this PR ? thanks.

**Comment by pascalheraud** [comment]
Hello
I think there is already a similar module currently in developmen : https://github.com/ansible/ansible/pull/65566

**Comment by YoannAtOVH** [comment]
Agree, but this PR have been open before and ready to merge, don't you ?

**Comment by YoannAtOVH** [comment]
@pascalheraud so how to choose between this one and the other PR ?

**Comment by AsLY4** [comment]
@pascalheraud sorry for the Up!

**Pull request closed without merging**
