### PR TITLE
Fixes #38941 - Don't update cpu/memory allocation in configspec on no change

### LINKED ISSUE #38941: vmware_guest: valid request fails with "Access to resource settings is restricted"
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
  config file = None
  configured module search path = [u'/home/app021/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION

Default.

##### OS / ENVIRONMENT

Ubuntu Server 17.10
ESXi 6.0.0/vCenter Server 6.0.0

##### SUMMARY
When ESXi/vCenter is configured in particular way, valid change in vm configuration fails. 
Same change works with Ansible 2.4.x.
##### STEPS TO REPRODUCE

ESXi must allow direct access, and resource allocation must be controlled by vCenter (so it is not possible to change it on ESXi, must be changed on vCenter)
Run vmware_guest module to change vm properties other than resource allocation (cpu/mem in this case). Use ESXi address/credentials to connect, **NOT** vCenter ones. Example playbook listed below.
It also fails same way when module is called directly with ansible args:
python /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py ansible_args.json
(Example Ansible args also pasted below)

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - vmware_guest:
        username: root
        password: apassword
        hostname: <esxi address>
        name: "a-vm-name"
        hardware:
          memory_mb: 4096
          num_cpus: 6
        state: present
```

```
{
    "ANSIBLE_MODULE_ARGS": {
        "datacenter": "ha-datacenter",
        "hardware": {
            "memory_mb": "4096",
            "num_cpus": "4"
        },
        "hostname": "<esxi address>",
        "name": "a-vm-name",
        "password": "apassword",
        "state": "present",
        "username": "root"
    }
}
```

##### EXPECTED RESULTS

Configuration is changed properly. It works this way with Ansible 2.4
##### ACTUAL RESULTS

Fails with:

```
 "Access to resource settings on the host is restricted to the server that is managing it: '<vcenter address>'."
```
This is caused by adding empty `vim.ResourceAllocationInfo()` and `vim.ResourceAllocationInfo()` to `vim.vm.ConfigSpec()` used for requesting change in cpu/mem, even though there is no resource configuration specified in vmware_guest call. 
It is empty request but it seems to trigger permission check anyway, failing whole request.
I have altered the code by removing empty requests and it works.

### PR DESCRIPTION
**Pull request by piotrplazienski**
##### SUMMARY
Fixes #38941
Memory and CPU reservations are written to configspec only if there is change. This prevents permission check from happening when not needed.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 1d97e38ca1) last updated 2018/05/07 10:54:16 (GMT +200)
  config file = None
  configured module search path = [u'/home/app021/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/app021/wave/ansible/lib/ansible
  executable location = /home/app021/wave/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION

Same as in issue - after change configuration is changed properly.

### CODE REVIEW

**Comment by Akasurde** [comment]
@piotrplazienski Thanks for the PR. Could you please add integration test for this change ? You can find tests [here](https://github.com/ansible/ansible/tree/devel/test/integration/targets/vmware_guest)

**Comment by piotrplazienski** [comment]
@Akasurde, unfortunately it is not possible, as vcsim does not support reservation. It is even commented out in existing integration tests: [source](https://github.com/ansible/ansible/blob/devel/test/integration/targets/vmware_guest/tasks/create_d1_c1_f0.yml#L49)
I have run reservation tests manually, and it works.

**Comment by Akasurde** [comment]
@piotrplazienski OK. Thanks. Changes looks good to me.

@dericcrago @pdellaert Could you please review this?

**Review by pdellaert — APPROVED** [review]
LGTM, nice improvement :)

**Comment by Akasurde** [comment]
@piotrplazienski Thanks for the PR. @pdellaert Thanks for the review.

**Pull request merged**
