### PR TITLE
refactor asa_config to use persistent connections

### PR DESCRIPTION
**Pull request by privateip**
this refactoring should solve a number of issues around using
asa_config.

* #25319
* #19183

### CODE REVIEW

**Comment by ogenstad** [comment]
@privateip, did you look at my PR #27218 regarding asa_config?

**Comment by privateip** [comment]
@ogenstad yeah i realized after i did this last night that I didn't need to.  I"m going to get this cleaned up today

**Comment by privateip** [comment]
@ogenstad can you rebase this PR?  I can then get it merged and we can get moving forward with getting this cleaned up.  Thanks

**Comment by privateip** [comment]
closing this PR in favor of #27218 which is already merged

**Pull request closed without merging**
