### PR TITLE
VMware: check for ESXi server while creating user

### LINKED ISSUE #32465: Cant create or edit user with "vmware_local_user_manager" module
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_local_user_manager

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /var/lib/rundeck/ansible/ansible.cfg
  configured module search path = [u'/var/lib/rundeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### SUMMARY

everytime i try to create or edit a user using the "vmware_local_user_manager" module, i receive the following error.
```
The full traceback is:
  File "/tmp/ansible_miBA9L/ansible_module_vmware_local_user_manager.py", line 98, in process_state
    local_account_manager_states[self.state][self.check_local_user_manager_state()]()
  File "/tmp/ansible_miBA9L/ansible_module_vmware_local_user_manager.py", line 136,
▽
in state_create_user
    self.content.accountManager.CreateUser(account_spec)

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "hostname": "vsphere server,
            "local_user_description": null,
            "local_user_name": "test2",
            "local_user_password": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "username": "rundeck",
            "validate_certs": false
        }
    },
    "msg": "'NoneType' object has no attribute 'CreateUser'"

```
Im not sure where/how i can specify, create user, update existing user, list user, etc.

Can you provide a syntax example on listing users, adding users, or editing users?

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - name: Add local user to ESXi
      local_action:
          module: vmware_local_user_manager
          hostname: vsphere server
          username: foo
          password: bar
          validate_certs: false
         # state: present
          local_user_name: test2
```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This fix check for ESXi server instance before proceeding
with managing local user. Also, adds integration tests for
this change.

Fixes: #32465

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_local_user_manager.py
test/integration/targets/vmware_local_user_manager/aliases
test/integration/targets/vmware_local_user_manager/tasks/main.yml

##### ANSIBLE VERSION
```
2.5devel
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/44914/47/tests

**Comment by Akasurde** [comment]
@mattclay tests are failing due to older version of vcsim, I will comment tests till we have latest vcsim in docker.

**Comment by mattclay** [comment]
@Akasurde Do we just need to rebuild the docker image to pull in the latest simulator?

**Comment by Akasurde** [comment]
@mattclay vcsim is quite unstable. I have local setup of vcsim once we have stable vcsim, we will rebuild docker image.

**Comment by Akasurde** [comment]
@mattclay Sorry. Could you please rebuild docker image for vcsim and let us see - if it works else we will stick to the current stable version ?

**Comment by mattclay** [comment]
@Akasurde I've rebuilt the simulator. You'll need to update the [image SHA](https://github.com/ansible/ansible/blob/devel/test/runner/lib/cloud/vcenter.py#L46) in your PR to:

`sha256:13c001e2deed03229f727956c012098b33e5c17b35a9e6cb7c03c8b6a83fdf2`

**Comment by Akasurde** [comment]
depends upon https://github.com/vmware/govmomi/issues/947

**Comment by Akasurde** [comment]
@mattclay govmomi#947 is fixed. Could you please rebuild image and let me know - I will debug onwards?

**Comment by mattclay** [comment]
I've started the build on Docker Hub: https://hub.docker.com/r/ansible/ansible/builds/bpx3wqh5kkcxtclrbdztxpw/

**Comment by mattclay** [comment]
@Akasurde The updated SHA is: sha256:005faa7442cd164b2a6087b069227fe1979068f420366cc49c57625bcf8f6ebe

**Comment by Akasurde** [comment]
I updated it already. Thanks.

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Review by pdellaert — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@pdellaert Thanks for your valuable review.

**Pull request merged**
