### PR TITLE
Make SSH binary path a configurable variable

### PR DESCRIPTION
**Pull request by sahand-mozaffari**
##### SUMMARY
Add SSH binary path to the list of configuration variables and make the existing code respect its value.

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
contrib/inventory/openvz.py
examples/ansible.cfg
lib/ansible/constants.py
lib/ansible/executor/task_executor.py
lib/ansible/plugins/connections/ssh.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by semekh** [comment]
Is there anything preventing this PR from getting merged? It's a bit inconvenient to symlink and/or replace binaries while using ansible.

**Comment by bcoca** [comment]
can you explain the use case? Ansible expects ssh to be in the local PATH on the master machine, which is the case in every OS I can think of.

**Comment by semekh** [comment]
So, we've got this pseudo-ssh thing (we call it `docker-ssh`) which basically makes it possible to ssh into docker containers without running an ssh daemon. The good thing about this approach is that any ssh-compatible provisioning tool will easily be able to support provisioning docker containers. (e.g. in particular, we're aware of the ansible docker connection plugin, and it lacks support for some of ssh functionalities like agent forwarding)
So, if you want to provision a container, you'll just specify it as a regular host (e.g. `root@containerId` instead of `root@hostIp`) and change your ssh binary path to `docker-ssh`.

**Comment by jody-frankowski** [comment]
@SeMeKh how is it superior to overriding with PATH? Which I think is the way most people will expect to override binary paths with. Is it to make the setting persistent?

**Comment by tsreid** [comment]
I would also like to see this feature added. It would allow us to build tooling for test where we know the explicit version of SSH being used in the testing. It would also make it easier for us to deploy newer versions of SSH for Ansible to leverage but not affect everything else.

**Comment by Merovius** [comment]
I would also like to see this happen. My usecase is hooking into the ssh execution to dynamically generate an ssh-config, known_hosts file and more fitting my dynamic inventory. Configuring the ssh binary command is superior, because I can use a local path to a script which then does all the setup, generates the necessary config and exec's ssh with the right arguments. This makes the instrumentation-repo self-contained and usable without extra setup.

**Comment by bmalynovytch** [comment]
My two cents: I manage multiple platforms with Ansible for multiple customers for whom I have different ssh keys and configurations, managed by an ssh wrapper, called via an alias.
The alias, by the way, also wraps "caffeinate" (Mac OS X native command to prevent the computer from going to sleep while running long deployments).
There is a real need to be able to either way configure (through ansible.cfg / env / etc ...) the "ssh" command.

**Comment by thaumos** [comment]
This has been implemented.

http://docs.ansible.com/ansible/intro_configuration.html#ssh-executable

**Comment by abadger** [comment]
This was implemented in Ansible-2.2 as ANSIBLE_SSH_EXECUTABLE: http://docs.ansible.com/ansible/intro_configuration.html#ssh-executable

**Pull request closed without merging**
