### PR TITLE
Make sure postgresql tests are run for all postgres_* modules

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Right now, most modules are not listed in test/integration/targets/postgresql/aliases.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
test/integration/targets/postgresql/aliases

### CODE REVIEW

**Comment by Andersson007** [comment]
@felixfontein thanks! Would be cool to see it merged asap! I will remember to add new modules to this file, thank you

**Comment by felixfontein** [comment]
I interpret that as a shipit :)

**Comment by felixfontein** [comment]
Can you create backports to stable-2.9 and stable-2.8 (that probably needs a few less names in `aliases`)?

**Comment by Andersson007** [comment]
@felixfontein , sure, I’ll do it on Monday

**Comment by mattclay** [comment]
@felixfontein Is there a reason for most of these modules to be tested using a single test target instead of having a dedicated target for each?

**Comment by felixfontein** [comment]
@mattclay I don't know, better ask that @Andersson007. I just wanted to make sure that the tests are actually triggered when a module which is tested by them is changed.

**Comment by Andersson007** [comment]
hello @mattclay and @felixfontein , i think there are some reasons for doing this using a single target because it was made in this way seems a long time ago and now some tests probably depend on the other.
It could be painful to split them but on the other hand i agree it would be, at least, much faster and convenient to work with split tests.
@mattclay If you asked becouse you'd like to do it, ok, welcome :) if it is a suggestion - thank you for the idea, i should try to split them :) it would be really cool. I should look at this in detail and evaluate how painful it might be :)

**Pull request merged**
