### PR TITLE
Fixed vault id in variable encryption example

### PR DESCRIPTION
**Pull request by sadv1r**
##### SUMMARY
Fixes wrong variable name in docs

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docsite

### CODE REVIEW

**Comment by samdoran** [comment]
Changing the example output makes the following text incorrect. The simplest change is to just change the command.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @sadv1r for the Ansible docs fix!

**Pull request merged**
