### PR TITLE
Add section to aws devel guidelines about module_defaults

### PR DESCRIPTION
**Pull request by jillr**
##### SUMMARY
Ensure contributors know their new module will need to be added to the module_defaults list.

It might be useful to add a general dev guide section about supporting module_defaults but I couldn't decide the right place to do so.  Maybe `developing_modules_in_groups.rst`?

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/platforms/aws_guidelines.rst

### CODE REVIEW

**Review by gundalow — COMMENTED** [review]
Yay for docs. What would be the equivalent in Collections?

**Comment by jillr** [comment]
@gundalow AFAIK module defaults isn't moving out of minimal/base
https://github.com/ansible-collection-migration/ansible-minimal/blob/devel/lib/ansible/config/module_defaults.yml
I could be wrong?

**Comment by gundalow** [comment]
If I ads a new AWS module in a collection that wants to take advantage of this feature, what/where do I need to update?

**Comment by bcoca** [comment]
currently, you would need to update the file in core

**Comment by s-hertel** [comment]
The collections issue is being tracked by https://github.com/ansible/ansible/issues/59864

**Comment by gundalow** [comment]
Thanks,so I guess this is food to merge as is?

**Comment by tremble** [comment]
For what my opinion's worth, it'd be better to have **something** documented so that modules that are added this side of the split have the right thing done.

**Comment by s-hertel** [comment]
Agreed

**Comment by s-hertel** [comment]
Thanks @jillr!

**Pull request merged**
