### PR TITLE
Add filter dict

### PR DESCRIPTION
**Pull request by giner**
Add dict filter which returns a single key-value pair from two arguments. Useful for generating complex dictionaries without using loops.

Example 1

```
- hosts: localhost
  gather_facts: false
  vars:
    myvar: myvalue
  tasks:
  - debug:
      msg: "{{ myvar | dict('thatsmyvar') }}"

OUTPUT:
ok: [localhost] => {
    "msg": {
        "thatsmyvar": "myvalue"
    }
}
```

Example 2

```
- hosts: localhost
  gather_facts: false
  vars:
    myservers:
    - server1
    - server2
  tasks:
  - debug:
      msg: "{{ myservers | map('dict', 'server') }}"

OUTPUT:
ok: [localhost] => {
    "msg": [
        {
            "server": "server1"
        },
        {
            "server": "server2"
        }
    ]
}
```

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

core

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bcoca** [comment]
https://jinja.palletsprojects.com/en/2.11.x/templates/#dict

**Comment by giner** [comment]
@bcoca, Unfortunately function cannot be used as a filter

**Comment by mattclay** [comment]
We're not sure if we want this in core, or if it should be in a collection. Could you bring this up in the core IRC meeting for further discussion? You can add it to the agenda here: https://github.com/ansible/community/issues?q=is%3Aopen+label%3Ameeting_agenda+label%3Acore

**Comment by sivel** [comment]
I think if we do accept this functionality in general, it should be renamed.  I can see potential issues of naming it `dict`. Plus it's not exactly a direct mapping to what the `dict` function/global does either.  More like `dict_kv` or something...

**Comment by mattclay** [comment]
Closing per the discussion in the Public Ansible Project Meeting today. As discussed, we recommend proposing this filter (with a different name) in the `community.general` collection.

**Comment by giner** [comment]
PRed to community.general collection https://github.com/ansible-collections/community.general/pull/1264

**Pull request closed without merging**
