### PR TITLE
base64 filter: Added ability to specify encoding

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Specify the encoding of the string when converting to and from bytes before/after being base64'd

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
filters
b64encode
b64decode

##### ANSIBLE VERSION
```
devel
```

### CODE REVIEW

**Comment by mattclay** [comment]
The unrelated errors have been fixed. I've restarted CI for this PR.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/63913/36/console

The other failures are unrelated.

**Comment by jborean93** [comment]
Thanks @mattclay, looks like testing out surrogate pairs is a bust due to the differences in handling between OS installs and Python versions. I'll just remove that as it is isn't critical we test that here.

**Comment by jborean93** [comment]
Errors are due to uri on Centos and are unrelated to the changes here.

**Pull request merged**
