### PR TITLE
V2 slack callback plugin

### PR DESCRIPTION
**Pull request by sivel**
This PR supersedes https://github.com/ansible/ansible/pull/8955 and https://github.com/ansible/ansible/pull/12889 

Of note here, because we don't have the ability to look into the playbook and play objects like before, I'm using `CLI.base_parser` to get some of that data.  I'm not super happy with that solution, although it does get me that data.  I'm open to suggestions.  However, this is working well for us as is.

cc @bcoca

### CODE REVIEW

**Comment by bcoca** [comment]
so I understand why you want the CLI stuff, but I think that does not belong inside this plugin, we might want to make it part of the base or just pass that info to callbacks in general.

**Comment by sivel** [comment]
I think we are in agreement there.  I'm just not sure of what the best approach is.

**Comment by bcoca** [comment]
so here i show a simpler method of getting the same info https://gist.github.com/bcoca/5c70c475b132113d82b1, now all callbacks have access to the `options` object.

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/13412 <= now added to the 'defaults'

**Comment by sivel** [comment]
I've updated this PR to use `self._options` which due to #13412 not being merged yet, is handled in this callback itself.

@bcoca let me know what you think so far.

**Comment by EpiqSty** [comment]
Hello!

I have tried to use this callback module, but got :

` [WARNING]: Could not submit message to Slack: HTTP Error 404: Not Found`

error

Can you please advise, what else can be wrong here?

```
$ source .slack 
$ more .slack
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/aaa/bbb/ccc
export SLACK_WEBHOOK_URL
$ grep slack ansible.cfg 
callback_whitelist = slack
```

Thanks!

**Comment by EpiqSty** [comment]
I've got the reason of 404 error. Seem's that 
+        SLACK_CHANNEL     (optional): Slack room to post in. Default: #ansible
is not optional - as we have not special #ansible channel in our slack , we use another channel for testing deploys notification.
So callback start sending messages to slack only after specifying another channel via env.
It seem's strange, because  SLACK_WEBHOOK_URL at fact issued to some default channel, but if it's not #ansible - you will get such 404 error.

**Pull request merged**
