### PR TITLE
Migrate Scaleway tests to integration tests

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

Migrate all tests to test/integration 

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by sieben** [comment]
@mattclay Could you review and merge?

**Comment by sieben** [comment]
@pilou- What do you think about it?

**Comment by sieben** [comment]
@mattclay Would it be possible to have for me and other members of Scaleway the right to be autonomous about merging code (including tests) concerning Scaleway?

**Comment by mattclay** [comment]
@sieben The tests all need `unsupported` added to their aliases files. The bot metadata also needs to be updated:

https://github.com/ansible/ansible/blob/c5991b970f42e8ea3fce7ef534e3c863f13fc954/.github/BOTMETA.yml#L1377-L1379

**Comment by sieben** [comment]
@mattclay fixed. Do you need something else?

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
bot_status

**Pull request merged**
