### PR TITLE
Add example for setting OSPF RID

### PR DESCRIPTION
**Pull request by benpiper**
+label: docsite_pr
Issue ansible/community#311

SUMMARY
Add example for setting OSPF RID

ISSUE TYPE
Docs Pull Request
COMPONENT NAME
nclu

ANSIBLE VERSION
ansible 2.5.2

ADDITIONAL INFORMATION
Issue ansible/community#311

### CODE REVIEW

**Comment by beeankha** [comment]
Hi @benpiper , thank you so much for your PR, especially as a first-time contributor to this repo!  We'll be taking a look as soon as we get a chance, and will update with a comment once we're done testing.

**Comment by acozine** [comment]
Hi @benpiper can you rebase this PR and also provide a playbook and output that put the example through its paces? See https://github.com/ansible/ansible/pull/40369 for an example of what we're looking for. See the Validation section of https://github.com/ansible/community/issues/311 for details on what we need. Thanks!

**Comment by beeankha** [comment]
@benpiper , just pinging to see if you could rebase + provide the info requested above by @acozine .  If we don't hear back from you by the end of this month (July 2018), we'll close this PR out.

**Comment by acozine** [comment]
Since we haven't heard from you, we're closing this PR. Feel free to re-open it and include the validation steps if you still want this example merged. Thanks again for contributing!

**Pull request closed without merging**
