### PR TITLE
VMware: add new module: vmware_host_package_facts

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_host_package_facts.py
test/integration/targets/vmware_host_package_facts/aliases
test/integration/targets/vmware_host_package_facts/tasks/main.yml

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@pdellaert @tchernomax Could you please review this ?

**Comment by Akasurde** [comment]
ready_for_review

**Review by tchernomax — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@tchernomax Thanks for review.

**Pull request merged**
