### PR TITLE
Checkpoint host facts

### PR DESCRIPTION
**Pull request by rcarrillocruz**
##### SUMMARY

Checkpoint host facts

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

checkpoint_host_facts

### CODE REVIEW

**Comment by rcarrillocruz** [comment]
merging per @ganeshrn ok

**Comment by zenware** [comment]
@rcarrillocruz hey could you help me understand how this works?
I'm curious because I'm thinking about implementing something vaguely similar to support other devices and I just happened to come across this clean looking implementation.

What has me confused is this code
```
connection = Connection(module._socket_path)
```

I looked up in ansible.module_utils.{basic,connection} to see the implementation of both AnsibleModule and Connection, and in the constructor for AnsibleModule `self._socket_path = None` and in the constructor for Connection `if socket_path is None: raise AssertionError(...`

So in my mind this should just error out?

I haven't actually executed it as a test against a live device or otherwise, that's just my expectation though. I'm not even really seeing a way for the AnsibleModule._socket_path to be configured to something else,

Anyway, thanks for your time on this project even if you don't get to my question 👍

**Comment by justjais** [comment]
@zenware Checkpoint module is based out of ansible `httpapi` connection plugin, so if u want to implement something similar for other platform then u'll have to write `httpapi` plugin for the respective platform.
For Checkpoint, u can find the `httpapi` plugin implementation in [this](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/httpapi/checkpoint.py#L32) file.
So, when `checkpoint_*` module is called via httpapi connection plugin it executes `httapi` plugin `__init__` code (ref: [code](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/httpapi.py#L194)) which in turns calls platform specific httpapi implementation and thus makes connection.

Hope this helps.

**Comment by zenware** [comment]
@justjais interesting, thank you for the explanation. I stumbled upon the HttpApi documentation yesterday and started trying to figure out how that worked, and your reply is very helpful!

**Pull request merged**
