### PR TITLE
apt_repository: autoinstall python-apt if not available

### PR DESCRIPTION
**Pull request by trevorah**
This is almost identical to the apt issue (#4079) and its corresponding fix (#4617)

### CODE REVIEW

**Comment by lorin** [comment]
+1, this would be a great enhancement.

**Comment by resmo** [comment]
+1

**Comment by jctanner** [comment]
@trevorah can you rework this based on the way it was implemented in the yum module?

https://github.com/ansible/ansible/blob/devel/library/packaging/yum#L158-L167

I prefer explicit calls and return code checks over wrapping everything in a try/except block.

**Comment by trevorah** [comment]
@jctanner sure, give me a sec...

**Comment by resmo** [comment]
@trevorah and also in the `apt`-module as well. plz :)

**Comment by trevorah** [comment]
@jctanner do you mean something like this?

**Comment by mpdehaan** [comment]
Pretty much.

Now that module.run_command does not use the shell by default this should be modified to split this up into two commands instead of using "&&", or alternatively pass use_unsafe_shell=True to run command.

Also since module_utils/urls has the "fetch_url" code we can also remove the dependency on pycurl at the same time.

**Comment by jctanner** [comment]
@trevorah thank you!

I remove the pycurl functions since they're no longer needed per: 7af8a33def34519de5ca390c47bdbd432d7b7ee2

If you'd like to do the same for the apt module, I would be happy to review.

**Comment by trevorah** [comment]
@jctanner no problem, glad I could help! Sorry for the delay btw, python isn't my first language.

**Comment by gdevenyi** [comment]
This change disagrees with http://docs.ansible.com/intro_installation.html#managed-node-requirements

Was this going to be documented at some point? I ran an ansible check on some systems only to find it install packages _WITHOUT ASKING_

**Pull request merged**
