### PR TITLE
VMware: Handle KeyError while moving VM from suspended to poweredon

### PR DESCRIPTION
**Pull request by pgbidkar**
##### SUMMARY
FIx issue https://github.com/ansible/ansible/issues/64613

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vmware_guest.py

### CODE REVIEW

**Comment by pgbidkar** [comment]
moved fix from vmware_guest.py to vmware.py.
If user passed force:True argument while changing power state from suspended to powerOn, this issue is not seen. 

if force argument is not passed, then  set_vm_power_state() method returns from line without initialising result['instance'] causing key error from vmware_guest.py

Thanks

**Review by goneri — APPROVED** [review]
Looks good to me. It may be also nice to update the test-suite to avoid a similar issue in the future.

**Comment by jacksonp2008** [comment]
Thumbs up!

**Comment by Akasurde** [comment]
@pgbidkar Thanks for the contribution. @jacksonp2008 @goneri Thanks for the review and test.

**Pull request merged**
