### PR TITLE
Migrate onyx modules from community.network to mellanox.onyx

### PR DESCRIPTION
**Pull request by samerd**
Signed-off-by: Samer Deeb <samerd@mellanox.com>

##### SUMMARY

Migrate onyx modules from community.network to mellanox.onyx

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by gundalow — APPROVED** [review]
Thanks. Once this has been merged can you please raise a backport PR fo the `stable-2.10` branch

**Comment by felixfontein** [comment]
I'm not really sure how this works, but I think there also need to be redirects for:
1. the plugins (terminal and cliconf);
2. the docs fragment;
3. Python import redirects for module_utils.

I have really no idea whether a redirect is needed for the action plugin, or whether that's covered by the module...

**Comment by samdoran** [comment]
Do we need to merge this or does the PR only need to exist in community.network?

needs_info

**Comment by gundalow** [comment]
> Do we need to merge this or does the PR only need to exist in community.network?
> 
> needs_info

@samdoran yup, this is needed here as well

ansible-base should redirect to mellanox.onyx
community.network should redirect to mellanox.onyx

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@samerd Thank you, can you please create a backport PR against the `stable-2.9` branch for this.

**Comment by felixfontein** [comment]
@samerd @gundalow no backport to stable-2.9 needed, but one to stable-2.10.

**Comment by gundalow** [comment]
Woops, yes that's what I mean. Thanks Felix

**Comment by samerd** [comment]
thanks @gundalow , @felixfontein 
I will create a new PR ASAP

**Comment by felixfontein** [comment]
@samerd @gundalow @samdoran lib/ansible/config/ansible_builtin_runtime.yml still redirects multiple onyx files to community.network (cliconf, module_utils, terminal, doc fragment). These also have to be redirected to mellanox.onyx.

**Comment by gundalow** [comment]
@samerd could you please raise a follow up PR? Once that's merged into devel, it will need backporting to `stable-2.10`.

**Comment by samerd** [comment]
> @samerd could you please raise a follow up PR? Once that's merged into devel, it will need backporting to `stable-2.10`.

added PR #70394

**Pull request merged**
