### PR TITLE
New PowerState Module - Issue 23260

### PR DESCRIPTION
**Pull request by imjoseangel**
##### SUMMARY

Adds Feature for #23260

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

win_powerstate

##### ADDITIONAL INFORMATION

Includes hibernate and suspend options for Windows Clients and Shutdown for all Windows Types. Be aware that the shutdown option is not idempotent, changes and other ideas are welcomed.

```paste below
PLAY [Run Windows Command] **********************************************************************************************************************************

TASK [Confirm port 5986 is open on the host] ****************************************************************************************************************
ok: [we-s-vm-server]
ok: [we-s-vm-client]

TASK [Get Ansible Facts] ************************************************************************************************************************************
ok: [we-s-vm-server]
ok: [we-s-vm-client]

TASK [Try to Suspend host] **********************************************************************************************************************************
ok: [we-s-vm-server]
changed: [we-s-vm-client]

TASK [assert win_powerstatesuspend_result (Windows Client) for suspend state] *******************************************************************************
skipping: [we-s-vm-server]
ok: [we-s-vm-client] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert win_powerstatesuspend_result (Windows Server) for suspend state] *******************************************************************************
ok: [we-s-vm-server] => {
    "changed": false,
    "msg": "All assertions passed"
}
skipping: [we-s-vm-client]

TASK [Try to Hibernate host] ********************************************************************************************************************************
ok: [we-s-vm-server]
changed: [we-s-vm-client]

TASK [assert win_powerstatehibernate_result (Windows Client) for suspend state] *****************************************************************************
skipping: [we-s-vm-server]
ok: [we-s-vm-client] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [assert win_powerstatehibernate_result (Windows Server) for suspend state] *****************************************************************************
ok: [we-s-vm-server] => {
    "changed": false,
    "msg": "All assertions passed"
}
skipping: [we-s-vm-client]

TASK [Force Shutdown to host] *******************************************************************************************************************************
changed: [we-s-vm-server]
changed: [we-s-vm-client]

TASK [Confirm port 5986 is closed on the host] **************************************************************************************************************
fatal: [we-s-vm-server]: FAILED! => {"changed": false, "elapsed": 21, "msg": "timed out waiting for ping
...ignoring
fatal: [we-s-vm-client]: FAILED! => {"changed": false, "elapsed": 21, "msg": "timed out waiting for ping
...ignoring

TASK [assert shutdown state] *****************************************************************************
ok: [we-s-vm-server] => {
    "changed": false,
    "msg": "All assertions passed"
}
ok: [we-s-vm-client] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP **************************************************************************************************************************************************
we-s-vm-client             : ok=9    changed=3    unreachable=0    failed=0    skipped=2    rescued=0    ignored=1   
we-s-vm-sever             : ok=9    changed=1    unreachable=0    failed=0    skipped=2    rescued=0    ignored=1 
```

### CODE REVIEW

**Comment by jborean93** [comment]
Question About This One
=======================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

   * The main issue is that this module is not idempotent and can never be, once you shut down a host you cannot shut it down again, or even run any other task
   * Because of the above our usual stance for these types of actions is to just use `win_command` or `win_shell` to do what needs to be done
   * The fact that the tests are trying to suspend or hibernate the host but it doesn't happen also indicates a further problem with using those commands as the further actions should be failing
   * In Ansible 2.8 we added a new feature called collections, this is still a preview but ultimately it is designed for people to more easily distribute their Ansible content outside of Ansible. This would be a good candidate for something like this

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by imjoseangel** [comment]
@jborean93 Totally agree with your comments. What is the reason of keeping issue #23260 opened?

**Comment by jborean93** [comment]
@imjoseangel: sorry I wasn’t aware there was an issue that was open. I’ve closed this to hopefully avoid confusing anyone in the future. Feel free to ping myself or ask in IRC if you wanted to clarify any other feature requests

**Comment by imjoseangel** [comment]
Thank you!!!

**Pull request closed without merging**
