### PR TITLE
Define, when possible, the ansible_inventory_basedir variable

### PR DESCRIPTION
**Pull request by stoned**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Questions

(A) under what situations would the inventory basedir be None?   I imagine that's only when passing in inventory as a list, but wanted to make sure there might not be other cases I am missing.  If so, I'm fine with it as coded.

(B) can you update the "magic variables" section of docsite/rst/playbooks2.rst to indicate this variable is available?

(C) seeing we have $inventory_hostname, I think a shorter form would be "$inventory_dir" versus "$ansible_inventroy_basedir".   Mind updating things?

Thanks!

**Comment by stoned** [comment]
On Sun, Mar 17, 2013 at 3:11 PM, Michael DeHaan notifications@github.comwrote:

> (A) under what situations would the inventory basedir be None? I imagine
> that's only when passing in inventory as a list, but wanted to make sure
> there might not be other cases I am missing. If so, I'm fine with it as
> coded.
> 
> Yes I believe Inventory.basedire() only returns None when the inventory had
> been created with a host list

(B) can you update the "magic variables" section of

> docsite/rst/playbooks2.rst to indicate this variable is available?
> 
> Sure.
> 
> (C) seeing we have $inventory_hostname, I think a shorter form would be
> "$inventory_dir" versus "$ansible_inventroy_basedir". Mind updating things?

No I don't mind. I'll change this.

**Comment by stoned** [comment]
Done. I have "force pushed" a squashed commit with the variable renaming and its mention in docsite/rst/playbooks2.rst

**Comment by mpdehaan** [comment]
Don't like "additionally" and prefer "thus"  ? :)

**Comment by stoned** [comment]
sounds better to my ears but I may be wrong :-} I guess I could revert that.

**Comment by stoned** [comment]
New "force pushed" squashed commit with fixed documentation.

**Pull request merged**
