### PR TITLE
nxos module fixes cherry-pick

### PR DESCRIPTION
**Pull request by trishnaguha**
(cherry picked from commit 578ae3b238d54da99122838df01b5d4aafceab34)
(cherry picked from commit bc6e015a8671097ea51545bead34c25e6c8f390e)
(cherry picked from commit f1cc5a928c50ef524408e74f79d1071518d28ca3)

### CODE REVIEW

**Comment by trishnaguha** [comment]
The CI failed for some other reason on shippable for `rhel` and `freebsd`. This failure can be ignored for this PR.
https://app.shippable.com/github/ansible/ansible/runs/37062/8/console.

**Comment by abadger** [comment]
This run it failed 3.6 unittests due to DNS being flakey in shippable right now: https://app.shippable.com/github/ansible/ansible/runs/37100/summary/console

The previously unrelated failing tests have passed so I'm going to merge this.

**Comment by abadger** [comment]
Merge to stable-2.4 for the 2.4.0rc3 release

**Comment by trishnaguha** [comment]
Thanks!

**Pull request merged**
