### PR TITLE
now uses get_bin_path for lvg executables

### LINKED ISSUE #3713: lvg module needs additional PATH environment to work with -K (sudo)
When running this example task:

``` yaml
- name: remove legacy store volume group if present
  lvg: vg=store state=absent
  environment: 
    PATH: $PATH:/sbin
```

using the following command:

```
ansible-playbook lvm.yml -i development -K 
```

You get the following response:

```
failed: [hostname] => {"err": "/bin/sh: vgs: command not found\n", "failed": true, "rc": 127}
msg: Failed executing vgs command.
```

If you update the task with additional PATH information, like this:

``` yaml
- name: remove legacy store volume group if present
  lvg: vg=store state=absent
  environment: 
    PATH: $PATH:/sbin
```

It then works.  After consulting with the IRC channel, it seems that this is a bug in the module.  The response was "it should call get_bin_path first for path information and then call run_command" (though I am not entirely clear on what that means).

### PR DESCRIPTION
**Pull request by bcoca**
should fix #3713  w/o needing setting path in enviornment: as a work around
Signed-off-by: Brian Coca <briancoca+dev@gmail.com>

### CODE REVIEW

**Comment by mpdehaan** [comment]
Stylistic request:

```
+                        rc,_,err = module.run_command("%s %s"%(pvcreate_cmd,current_dev))
```

Can this be changed to:

```
+                        rc,_,err = module.run_command("%s %s" % (pvcreate_cmd, current_dev))
```

Thanks!

**Comment by bcoca** [comment]
i tried to change as little as possible, followed the original style, but
yes, much more readable.

i'll update branch

On Wed, Jul 31, 2013 at 11:09 PM, Michael DeHaan
notifications@github.comwrote:

> Stylistic request:
> - rc,_,err = module.run_command("%s %s"%(pvcreate_cmd,current_dev))
> 
> Can this be changed to:
> - rc,_,err = module.run_command("%s %s" % (pvcreate_cmd, current_dev))
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3722#issuecomment-21911755
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by sfromm** [comment]
one small bug.  at line 213, module.run_command() has a flawed call to vgextend:

```
rc,_,err = module.run_command("vgextend %s %s"%(vgextend_cmd, vg, devs_to_add_string))
```

Looks like it should be:

```
rc,_,err = module.run_command("%s %s %s" % (vgextend_cmd, vg, devs_to_add_string))
```

**Comment by bcoca** [comment]
thnx, fixing

On Thu, Aug 1, 2013 at 12:21 AM, Stephen Fromm notifications@github.comwrote:

> one small bug. at line 213, module.run_command() has a flawed call to
> vgextend:
> 
> rc,_,err = module.run_command("vgextend %s %s"%(vgextend_cmd, vg, devs_to_add_string))
> 
> Looks like it should be:
> 
> rc,_,err = module.run_command("%s %s %s" % (vgextend_cmd, vg, devs_to_add_string))
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3722#issuecomment-21913727
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
merged, thank you!

**Pull request merged**
