### PR TITLE
decouple dig lookup for simple DNS from dns.resolver library

### PR DESCRIPTION
**Pull request by caio2k**
This commit decouples dig from dns.resolver for simple lookup (which potentially is the most used usage).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
plugins/lookup/dig.py 

##### ANSIBLE VERSION
devel

##### SUMMARY
Potentially the *most wanted usecase* for dig lookup plugin is to just resolve an example.com/A using system's DNS. The plugin depends on dns.resolve python library which is not available by default in many distros. However, for the supposed *most wanted usecase* this dependency is not strictly necessary.
This patch adds support to fallback *sockets* python module for the  *most wanted usecase*, module which is present by default in many distros.

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to PEP 8 issues:

```
2017-02-23 14:45:05 ERROR: PEP 8: lib/ansible/plugins/lookup/dig.py:191:1: W293 blank line contains whitespace (legacy)
2017-02-23 14:45:05 ERROR: PEP 8: lib/ansible/plugins/lookup/dig.py:198:1: W293 blank line contains whitespace (legacy)
2017-02-23 14:45:05 ERROR: PEP 8: lib/ansible/plugins/lookup/dig.py:207:1: W293 blank line contains whitespace (legacy)
2017-02-23 14:45:05 ERROR: PEP 8: lib/ansible/plugins/lookup/dig.py:211:1: W293 blank line contains whitespace (legacy)
```

The PEP 8 tests can be run locally with `make pep8`.

**Comment by samdoran** [comment]
Can you please rebase and remove the merge commit?

cc @jpmens

**Comment by jpmens** [comment]
In times of IPv6 this hardly seems worth while in particular since Python's `socket` documentation states:

> `gethostbyname()` does not support IPv6 name resolution, and `getaddrinfo()` should be used instead for IPv4/v6 dual stack support.

In my opinion this should not be merged like this.

**Comment by samdoran** [comment]
needs_info
bot_status

**Comment by jpmens** [comment]
Over a year with no news? Close and be done with it.

**Pull request closed without merging**
