### PR TITLE
active directory dynamic inventory plugin

### PR DESCRIPTION
**Pull request by junaidali**
##### SUMMARY
Active directory is popular AAA (Authentication, Authorization & Accounting) service used by organizations especially within a Microsoft Windows environment. It stores computer object information which can be used as Ansible inventory source. Computer objects are typically organized using a hierarchical folder like structure (organizational units) for management purposes. This Ansible dynamic inventory plugin can pull computers from specific organizational units. It also supports Active directory security groups for given computer objects and adds the Ansible inventory host to respective inventory host groups. This plugin is designed to be scalable and uses python generator pattern to efficiently query very large active directories. 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
active_directory dynamic inventory plugin

##### ADDITIONAL INFORMATION
The plugin file (active_directory.py) includes detail documentation on how to use the plugin. Below is a short example

Create a new file active_directory.yml with below contents, make sure to replace the username, password, domain_controllers and organizational_units fields as appropriate
```
plugin: "active_directory"
username: "DOMAIN\\USERNAME"
password: "PASSWORD"
domain_controllers:
  - 'dc.ansible.local'
organizational_units:
  - "DC=ansible,DC=local" 
import_computer_groups: yes
```

Enable the plugin by creating a new ansible.cfg file in the same folder as the active_directory.yml file with below contents
```
[inventory]
enable_plugins = host_list, script, yaml, ini, auto, active_directory
```

To view the list of computers returned by this plugin run below command
```
ansible-inventory -i active_directory.yml --graph
```

It should return the list of computers as below (sample)
```
@all:
  |--@computers:
  |  |--computer-002
  |  |--computer-003
  |  |--computer-004
  |  |--computer-005
  |--@domain_computers:
  |  |--computer-002
  |  |--computer-003
  |  |--computer-004
  |  |--computer-005
  |--@ungrouped:
```

### CODE REVIEW

**Comment by jamescassell** [comment]
Would be great to support using the active Kerberos TGT for AD authentication and transport encryption.

Worked also be great to gather DC info from DNS.

**Comment by Akasurde** [comment]
@junaidali Thanks for the contribution. Could you please migrate this PR to [`community.general`](https://github.com/ansible-collections/community.general) since the community modules/plugins are migrated to this repo. Thanks.

**Comment by Akasurde** [comment]
needs_info

**Comment by Akasurde** [comment]
Hi @junaidali, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
