### PR TITLE
[WIP] Allow subspec to be used in required_* and mutually_exclusive

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Add `dotted_accessor` that allows subspec to be used in `required_*` and `mutually_exclusive` across subspec boundaries

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/basic.py

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by sivel** [comment]
[WIP] due to needing testing and tests.

**Comment by sivel** [comment]
Example module that showcases this:

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
# (c) 2018, Matt Martz <matt@sivel.net>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec={
            'sub': {
                'type': 'dict',
                'options': {
                    'foo': {
                        'type': 'bool'
                    },
                    'bar': {
                        'type': 'bool'
                    },
                    'baz': {},
                    'qux': {}
                }
            },
            'top1': {
                'type': 'bool',
            },
            'top2': {},
        },
        mutually_exclusive=[['sub.foo', 'sub.bar']],
        required_one_of=[['sub.foo', 'sub.bar']],
        required_if=[('sub.foo', True, ['sub.baz']), ('top1', True, ['top2'])],
        required_together=[['sub.bar', 'sub.qux']]
    )
    return module.exit_json(**module.params)


if __name__ == '__main__':
    main()
```

**Comment by caphrim007** [comment]
@sivel Tested this on my own module and it seems to be working correctly.

**Comment by sivel** [comment]
Some notes here.  This adds extra functionality on top of what you can already achieve for validating sub options.  If you want to do this between keys on a single suboption, this is already allowed:

https://github.com/ansible/ansible/blob/2f36b9e5ce0ec41a822752845d3b7c4afdf7eee9/test/units/module_utils/basic/test_argument_spec.py#L102-L121

However, if you want to compare between a top level key, and some nested sub key, this is not currently achievable, but is achievable with this PR.  Such as the theoretical situation:

```python
mutually_exclusive=[['username', 'provider.username']],
```

**Pull request closed without merging**
