### PR TITLE
New filter get_number_list

### PR DESCRIPTION
**Pull request by stbka**
This filter should return a list of numbers. For instance I use that list in a with_nested loop.
I have added some documentation as well.

### CODE REVIEW

**Comment by sivel** [comment]
Sounds like would be better called `range`

**Comment by stbka** [comment]
Yes, indeed. Although the parms are a bit different.
I have changed it.

**Comment by jhawkesworth** [comment]
Erm.. isn't there already a 'range' function in jinja2
http://jinja.pocoo.org/docs/dev/templates/#list-of-global-functions
Having 2 things with the same name could get confusing.

**Comment by bcoca** [comment]
this overlaps with ansible's sequence lookup

**Comment by bcoca** [comment]
closing this as it overlaps both with jinja2's range and ansible's sequence

**Comment by stbka** [comment]
As far as I know you cannot use jinja2's range function in tasks/playbooks and ansible's sequence is not combinable with a with_nested loop.

Here's my usecase:

solrCollection_shards_per_host is a number

``` yml
---
- name: set fact
  set_fact:
    listShardsPerHost="{{solrCollection_shards_per_host|range}}"

- name: do something
  ...
  with_nested:
    - "{{solrCollections}}"      # should be something like [ coll1, coll2, coll3 ]
    - "{{listShardsPerHost}}" # should be something like [1, 2, 3, 4]
```

**Comment by bcoca** [comment]
you mean this?:

```
- name: do something
  ...
  with_nested:
    - "{{solrCollections}}"
    - "{{lookup('sequence', 'count=4'}}"
```

**Comment by stbka** [comment]
Yes, this looks great! Did not know the lookup-sequence feature.
Works for me.

Thank you.

**Pull request closed without merging**
