### PR TITLE
openssl_certificate: make sure extensions are present when they are queried by assertonly

### LINKED ISSUE #38733: openssl_certificate only asserts present extensions, ignoring absent ones
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openssl_certificate

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/remote/egolov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### CONFIGURATION
virgin

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`openssl_certificate` can assert certain parameters of a certificate, but fails to do so if that specific parameter is not set at all. for example a certificate w/o a subjectAltName entry (at all), will not be marked as not having a subjectAltName of "bad.example.com".

by looking at the code, this issue should be present with keyUsage, extendedKeyUsage and subjectAltName extensions

##### STEPS TO REPRODUCE

1. create a cert w/o a subjectAltName (e.g. `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes`)
2. run the playbook (the embedded cert is for `my.example.com` with no SubjAltName)

```
- hosts: localhost
  gather_facts: False
  tasks:
    - copy:
        dest: /tmp/test.crt
        content: |
          -----BEGIN CERTIFICATE-----
          MIIFjDCCA3SgAwIBAgIJAKhDDrNMN9nQMA0GCSqGSIb3DQEBCwUAMFsxCzAJBgNV
          BAYTAlhYMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQg
          Q29tcGFueSBMdGQxFzAVBgNVBAMMDm15LmV4YW1wbGUuY29tMB4XDTE4MDQxMzEz
          MTUxOVoXDTE5MDQxMzEzMTUxOVowWzELMAkGA1UEBhMCWFgxFTATBgNVBAcMDERl
          ZmF1bHQgQ2l0eTEcMBoGA1UECgwTRGVmYXVsdCBDb21wYW55IEx0ZDEXMBUGA1UE
          AwwObXkuZXhhbXBsZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
          AQDaVyG49pIVFTB2/GhU5CVRaDCKO9uPIZGM42gtWgmFzYqptncSujuo1G0g/b7L
          Xpc52OTvwrrQh1SbGaOmCakJ9q2a5qu5qN7NtX7XnBjpYZ5gUOFu14vKg6E3Kh8Z
          hpH8P9YCteetLccqbXOD9dsbO4S1ORNrlnan2UdH2sFQaAeFzTcUwwvH9MfOr91L
          ABTkEKu6b+5Hp0WsHNwLNQnh0iXiWl/9KcDrtY6Uy9QSJkhk2f0TRQo2ADn14cWU
          Kr3IR6NrBJJ/9+hz3Vn4u77xXD9DehXqcf59Rg40MP7CBZp5gX+iwHftyVHjsLiM
          oTT7dLfNog5keCxzyf5E52yIamXYwZjEVQPTxK4DztQ0KzCz9GALW+TmduiNoFtZ
          9+Z0mdkTmH+5/G61ABoTlHvAodQkWJvh8qImnqLWZerfYB4w+1qlyWvldyvwZYzt
          cqYPudL02DzOgJWzSgkqKjtGUXAc2ZA1Ibp8zmXMSPr+CfQIuPw/+sI7rmF5Jvtz
          0T4gG8MZGYavBILpTVdqsdXxJc+VGNkIOPn+Y5OLxdUY1nwPQ5w7+rwUhsoIZE5l
          rjQgXUf+kt3GGV+LVAnLYx0pVacg+hPNI/AV9EK74Oqt4GTeCSJthkpG7yXGwrEF
          OaIqqDtuBK4huQQJv58FjBtrxFCGLIz8gMjwK63UhDVXswIDAQABo1MwUTAdBgNV
          HQ4EFgQUCrAjj26bDv6Z9ZteON+jqVf8lygwHwYDVR0jBBgwFoAUCrAjj26bDv6Z
          9ZteON+jqVf8lygwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEA
          1lXnN36/xZ7vNiFh6lp2rJx2CFZlbPx/y6Im9TpCOqtMyWFU9ccEYSk9PPvbQAGc
          o7P7ZlkKGunvVgw/aonTKpu6C8RfkEJ9NTnnbORbe5RriGtdjIzKYUUbE75tbKAs
          m+bX8bB+N3zDpNdrLhlf+mIOs8EnfVeeedxBbi4/NtJOabrHNGTn7zY/T4UvNEzt
          V8+NKDSr10VzUCpOx49pOqKd3WPF1r05zk0jkcRo6+bVElUN+tIka1G4t3Unvl0r
          aKEwqhQcS04N2r1Nb5mMrb5U3NoZonsaCiMiBSvuGl/Xd03JcBDOLP6pQ0lVItTB
          fD3ybbrSfjK92yuIL8AlRCh+z76D756M9WvrIJfLEZCs3E9X4zI+AlAIOnxzDjH7
          SkqpRmFek3nZDO1gIFZcqUJ29GMNowM70FCt5tx0pYuEL5fnd1oLHojvCdBdAjJ1
          nKcSyPrMrwnzJpjLzMZOjZ8/XscfvXRFz6GKjl44DpBhjN+dYBVs20yGznR60dWH
          7gCE3uLfjRNbbw3a2WK0E8Xhd4sBQ0o7VQHUzRzwmrGN5xVV++nfrB0kWcuCnCNt
          7t1mMHXDe01VxVVH2e3FtntCWS2SB554mxpM9Gg++cRr14nkZ3lyvJFbDouRTq7/
          F93nSz9OZMWt5Go00vcVHn9L/4aGRgZG7gX9OqgTOjM=
          -----END CERTIFICATE-----
    - openssl_certificate:
        path: /tmp/test.crt
        provider: assertonly
        subject_alt_name:
          - bad.example.com

```

##### EXPECTED RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Invalid subjectAltName component (got [], expected all of ['bad.example.com'] to be present)"}
```
##### ACTUAL RESULTS

```
PLAY [localhost] **********************************************************************

TASK [copy] ***************************************************************************
ok: [localhost]

TASK [openssl_certificate] ************************************************************
ok: [localhost]

PLAY RECAP ****************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #38733.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssl_certificate

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Looks good to me.

shipit

**Review by resmo — APPROVED** [review]
shipit

**Comment by resmo** [comment]
merging because of doc fragments prevent for automerge.

**Comment by felixfontein** [comment]
@MarkusTeufelberger @resmo thanks for reviewing and merging!

**Pull request merged**
