### PR TITLE
Add executable option to all SCM modules

### PR DESCRIPTION
**Pull request by skyl**
I did each SCM module in a separate commit. If we don't want to take this entire PR, we could break it up into separate ones and take only git or git&svn ...

A question about module_common and imports. I think that none of these modules should `import os` and should rely on module_common for `os`? OTOH, the seemingly unused tempfile import `import tempfile`; can we remove this in all the SCM modules or is there a reason that it is there (and should be in all of these modules?).

### CODE REVIEW

**Comment by mpdehaan** [comment]
excellent, thanks for modifying this and adding them to everything!

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by skyl** [comment]
Thanks :dancer: Hopefully this works out. I was just hacking out with my feelings. For posterity, I hope that we can unit test all the modules in the future ( https://groups.google.com/forum/#!topic/ansible-project/EH6_aYb0d4A ). Then, a simple refactoring like this can be done with less uncertainty. When the framework for testing modules is sorted out, I wouldn't at all mind putting in some time to cover these and others.

**Comment by mpdehaan** [comment]
Integration tests are more appropriate.

**Comment by skyl** [comment]
RIght, that's fine. But, are we still talking about tests which inherit from `unittest.TestCase`? If so, the nomenclature gets a little fuzzy. Yeah, they're integration tests in that they don't follow the strict rules of unit tests. But, they are subclasses of unittest.TestCase? Or, are we talking about a whole different way of having automated tests?

Do you want me to make a PR out of https://github.com/skyl/ansible/commit/11aabb6edb88a89f0a7399d9a70bb7c8ec42eda6 (and add some more source_control tests in this pattern)
 or add some bzr/hg/subversion tests directly in TestRunner.py? Or, is the whole test directory going to be obliterated in a grand refactor?

**Comment by mpdehaan** [comment]
Nope.

Please do not write live module tests via the unit test framework.

**Comment by mpdehaan** [comment]
we're not changing the existing unit tests, but those should be small
pieces for code.

integration tests test live units, especially modules that perform live
network activity.

I'm not happy with the current unit test structure and don't want to see it
grow to start doing integration tests in the present form.

**Pull request merged**
