### PR TITLE
Fix bug preventing wait_condition from being respected when using apply

### PR DESCRIPTION
**Pull request by fabianvf**
##### SUMMARY

Passes condition on when using apply

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

k8s
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by willthames — APPROVED** [review]
Test suite passes for me. Would be good to have a test that would have caught this bug.

**Comment by willthames** [comment]
This will need backporting to 2.9 now that we're frozen

**Comment by fabianvf** [comment]
@willthames yeah I updated the tests in #61466 (which is where I pulled this commit from), I can pull that specific test update out as well

**Comment by gundalow** [comment]
Given tests are in progress in https://github.com/ansible/ansible/pull/61466 I think this OK to merge

Once merged please create a backport (inc changelog/fragment) for `stable-2.9`

**Comment by fabianvf** [comment]
bot_status

**Pull request merged**
