### PR TITLE
proxmox: support version 6

### PR DESCRIPTION
**Pull request by morph027**
##### SUMMARY

Proxmox VE Version 6 Release slightly changed it's API regarding the version string (original issue: https://github.com/swayf/proxmoxer/issues/79). This fix picks up the new version scheme and still supports the old one.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

proxmox

### CODE REVIEW

**Review by pvanhemmen — APPROVED** [review]
This required fix works as expected and makes the proxmoxer module compatible with the actual Proxmox 6.x stable release.

**Comment by J4RF** [comment]
Is this ever going to be merged?

**Comment by morph027** [comment]
Huh, guess i should do some rebasing ...

**Comment by morph027** [comment]
hm, by looking at current devel, it looks like @mrdrogdrog fixed this in 38193f6b60caa2e3725cb987376a80074821a950 already....

**Pull request closed without merging**
