### PR TITLE
postgresql_set: improve CI tests

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_set: improve CI tests
1. improve formatting
2. add additional checks by SQL queries

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
postgresql_set

### CODE REVIEW

**Comment by Andersson007** [comment]
+label: postgresql

**Comment by Andersson007** [comment]
+label postgresql

**Comment by Andersson007** [comment]
I need to go. All is OK,  I'll rebase it tomorrow

**Comment by Andersson007** [comment]
ready_for_review

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@Andersson007 thanks for improving the tests!

**Comment by Andersson007** [comment]
@felixfontein , thank you for reviewing and merging!

**Pull request merged**
