### PR TITLE
Update azure_rm_resource.py

### PR DESCRIPTION
**Pull request by tgadiev**
##### SUMMARY
Example creating azure sas tokens for downloading private blob files

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
azure_rm_resource

##### ADDITIONAL INFORMATION
Example to create SAS token to download a file from blob storage by https temporary URL.

### CODE REVIEW

**Comment by tgadiev** [comment]
ready_for_review

**Comment by tgadiev** [comment]
@zikalino did you have a chance to take a look?

**Comment by tgadiev** [comment]
@zikalino any comments?

**Comment by tgadiev** [comment]
@zikalino gentle reminder :)

**Comment by tgadiev** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@haiyuazhang @gavinfish review_need

**Comment by Fred-sun** [comment]
ready_for_review

**Review by gavinfish — COMMENTED** [review]
https://github.com/Azure-Samples/ansible-playbooks maybe a better place to hold this. :thinking:

**Comment by Fred-sun** [comment]
> https://github.com/Azure-Samples/ansible-playbooks maybe a better place to hold this. 🤔

Yes, it is better to update here. 

@tgadiev Can you update according to the above comments? Thank you very much!

**Comment by tgadiev** [comment]
@Fred-sun Do you suggest to create a separate playbook with the given code there?

**Comment by Fred-sun** [comment]
Yes, if there are multiple tasks in a module, create a separate script just like any other module. Thank you very much!

**Comment by acozine** [comment]
@tgadiev thank you for contributing examples! 

I'm going to close this PR, since you've agreed that the Azure-Samples/ansible-playbooks repo is a better location for this information. Happy Automating!

**Pull request closed without merging**
