### PR TITLE
postgresql: move CI tests of *_owner, *_info, *_ping, *_query to separate targets

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql: move CI tests of *_owner, *_info, *_ping, *_query to separate targets

label: postgresql

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
postgresql_ping
postgresql_owner
postgresql_info
postgresql_query
postgresql_copy - only changed formatting and a comment

### CODE REVIEW

**Review by kostiantyn-nemchenko — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko thank you for reviewing! it makes passing tests much faster

**Comment by gundalow** [comment]
@Andersson007 @kostiantyn-nemchenko Thank you!

**Comment by Andersson007** [comment]
@gundalow , thank you for merging!

**Pull request merged**
