### PR TITLE
Replacement for apt_repository.

### PR DESCRIPTION
**Pull request by sashka**
1. Debian Squeeze is supported out of box now.
2. Repository type "deb" or "deb-src" should be explicitly specified.
3. If a source had beed added it must be possible to remove it.
4. PPA can be only used against Ubuntu hosts.

### CODE REVIEW

**Comment by omgjlk** [comment]
I don't have functional testing input, however since this does build upon the work that was already here, I don't think removing the reference to the original author is right. Also the license should stay in place, all source files should be licensed.

You've also got some pep8 issues going on, overly long lines and whatnot. It'd be prudent to pass it through flake8 or some other utility that checks for such things.

**Comment by sashka** [comment]
@j2sol Adding and removing the original author is up to @mpdehaan. I've just replaced whole file and used just the same file name.

Flake8 and PEP8 were used too, but my corporate standard is pretty relaxed about line width in code, which is supposed to be rarely read. So it is also up to @mpdehaan.

**Comment by mpdehaan** [comment]
I agree with @j2sol that credit should be given to the original author since the code was adapted from it.     Removal of the GPL license header is also bad, this needs to be replaced.

The list comprenensions are very hard to read, and lambda operations should be able to be completely phased out in favor of named functions and list comprehensions.  I'm not sure why you say "it's not business critical" in the comments.  We favor readability and hackability strongly over keeping things concise, and all of this code, to someone, is business critical.

Language like "it should fail" in the documentation is unclear.  Do you mean it _will_ fail?  I would change "should to when".

I would like to see the code issues cleaned up with the list comprehensions and lambdas, the GPL license header restored, the original author credited.

Given previous review comments were favorable,this is about ready, so just some minor things to fix.

You may force push this branch as I don't really want the "this is not business critical" comments in the git history, nor the removal of the license header.

**Comment by kwbr** [comment]
I finally found some time to test the apt_repository. I am very satisfied to not have to install another package (python-software-properties) to manage my apt configuration.                                                                                                                                             

I did not find a problem. I tested adding and removing. I use it like this:                                                                                    

```
- name: Common | Setup empty sources.list                                                                                                                      
  template: src=sources.list.j2 dest=/etc/apt/sources.list                                                                                                     
  tags: common                                                                                                                                                 

- name: Common | Add security repository                                                                                                                       
  apt_repository: repo='deb http://security.debian.org/ wheezy/updates main contrib non-free'                                                                  
  tags: common
```

**Comment by sashka** [comment]
Forced push made this PR a mess. :(
I'll close this and open another one. Sorry.

**Comment by sashka** [comment]
Please review forced commit at #3783.
Sorry for inconvenience.

**Pull request closed without merging**
