### PR TITLE
Feature/dataloader factory

### PR DESCRIPTION
**Pull request by jmikedupont2**
##### SUMMARY
Allow user to override the dataloader class. 
This is useful for the ability to do macro expansions on the text itself at load time.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible.parser.dataloader.DataLoader

##### ADDITIONAL INFORMATION
Extends the dataloader by a static factory method which looks for new configuration items that allow users to override the dataloader module and class, dynamically loads the module and class.
Also the usages of the dataloader class are changed to use factory.

### CODE REVIEW

**Comment by jmikedupont2** [comment]
Bot status

**Comment by jmikedupont2** [comment]
bot_statua

**Comment by jmikedupont2** [comment]
bot_status

**Comment by sivel** [comment]
What problem is this attempting to solve?  I honestly do not see us accepting this.  It would drastically affect the way ansible operates, and doesn't follow typical ansible patterns.

**Comment by jmikedupont2** [comment]
The goal is to hook in at loadtime and do preprocessing and there do static
macro expansion. I am have a patch that uses this to expand templates for
tasks at load time. https://github.com/jmikedupont2/functional-ansible.
This could be done via a plugin architecture as well by adding a loader
plugin. The idea of overloading classes factory could be useful for task
and playbooks  on the other hand. In the end I would like to be able to
hook in at the controller level after all variable loading is done. I will
be looking more into this. I think a compiler plugin architecture with
stages would be the best option.

**Comment by sivel** [comment]
We have discussed this amongst the core devs, and we are not ready to accept a feature like this right now, or potentially ever.  Dynamically expansion of playbooks is outside of the scope of functionality that we desire for Ansible.

We believe that allowing users to replace the data loader class is dangerous, and would create playbooks that are not portable.

We recommend creating roles or tasks files and using `include_role` or `include_tasks` to achieve similar goals, without changing the playbook DSL.

Additionally, concern has been raised about this implementation abusing the data loader to achieve this goal.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible-devel on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

**Comment by jmikedupont2** [comment]
That is fine with me. There are non intrusive methods to achive the same
functionailty. I was on irc on sunday but no one was there. Thanks for the
long mail. You can close this pr.

**Pull request closed without merging**
