### PR TITLE
aci_domain_to_encap_pool: Add domain to encap pool

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
A new ACI module to bind a domain to an encap pool.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
aci_domain_to_encap_pool

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by dagwieers** [comment]
cc @rsmeyers @nilloBE Please test and review !

**Comment by rsmeyers** [comment]
Please change name to aci_domain_to_vlan_pool

**Comment by jmcgill298** [comment]
looks like the module is designed to support more than vlan encap pools, naming it vlan_pool would be confusing to the end users. I would suggest keeping a universal module and a separate module if you really only want to support vlan pools

**Comment by rsmeyers** [comment]
You will normally only link a domain to a vlan pool...., if needed we can make a seperate one for vxlan if the use case is there, it doesn't make sense to call it encap pool

**Comment by dagwieers** [comment]
@rsmeyers In an earlier document you named it **aci_domain_to_vlan** instead of **aci_domain_to_vlan_pool**. I don't mind whatever you prefer most.

The new proposal is at #34402

**Comment by dagwieers** [comment]
Merging, integration tests and examples follow...

**Pull request merged**
