### PR TITLE
Clarify developing modules documentation

### PR DESCRIPTION
**Pull request by bpsuntrup**

### CODE REVIEW

**Comment by bcoca** [comment]
as mentioned in the bug ticket, this should not be needed as it is a requirement of ansible itself

**Comment by bpsuntrup** [comment]
Hi bcoca,

The reason this particular addition seems necessary is because the module development page doesn't assume the user has ansible installed to begin with. If ansible's being installed were a prerequisite to the tutorial, there would be no reason to perform the Git clone.

It seems to me that if installing Jinja2 would be off topic, then so would the Git clone. They seem to me to go together. Putting them together simply clarifies the documentation, especially for new users.

Thanks,
bpsuntrup

**Comment by bcoca** [comment]
There are installation instructions for ansible from git, those already state the dependencies.

**Comment by bpsuntrup** [comment]
Hi bcoca,

Here is a permalink to the particular section I'm talking about: http://docs.ansible.com/ansible/developing_modules.html#testing-modules. You can see how in context, asking a user to ensure Jinja2 is installed seems to flow better, especially for a new user just trying to follow the tutorial. For such users, a hiccup in the flow could cause them to question whether the documentation is up to date, especially so with wording such as "You should see output that looks something like this: ... If you did not, you might have a typo in your module, so recheck it and try again."

Good, clear, flowing documentation is essential for the success of ansible, as it not only serves as a faithful reference, but is one of the first impressions new potential users interact with.

Thank you,
bpsuntrup

**Comment by bcoca** [comment]
a link to how to use ansible from check out (instructions already in the install tutorial) seems more relevant here.

**Comment by bpsuntrup** [comment]
I agree. Perhaps a link to http://docs.ansible.com/ansible/intro_installation.html#running-from-source would be best here.

**Comment by bcoca** [comment]
agreed

**Pull request merged**
