### PR TITLE
Add valid plugin types to -t blurb in ansible-doc --help

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY
Add valid plugin types to -t blurb in ansible-doc --help

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/cli/doc.py

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/.local/lib/python2.7/site-packages/ansible
  executable location = /home/adrian/.local/bin/ansible
  python version = 2.7.14 (default, Feb 17 2018, 10:42:17) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by bcoca** [comment]
I  should have just made single list as a constant and reuse

**Comment by alikins** [comment]
> I should have just made single list as a constant and reuse

Or enumerate them somewhere (ansible.plugin.loader.* ?) and build the help list and
the make case/switch like bits in DocCLI.run() into a map lookup.

Updated the branch to have a variation of that.

Should the plugin types list things like 'netconf' or 'cliconf' or 'action' that could be documented in the future?  (could a custom plugin provide it's own docs, or does the plugin docs stuff need to be tweaked for each plugin type)

**Comment by bcoca** [comment]
fine with enumeration, netconf/cliconf might add docs, dont know enough, action plugins dont make sense as module already document them.

any custom plugin can provide docs as long as it is a supported 'type'

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/58615/49/console

> 2018-03-21 16:46:05 + ansible-doc -t netconf -l
> 2018-03-21 16:46:05 ERROR! ncclient is not installed

**Comment by bcoca** [comment]
closing via #47055

**Pull request closed without merging**
