### PR TITLE
Update Netbox inventory plugin: add region grouping, interfaces&vlans gathering, slug and group name prefix length

### LINKED ISSUE #60124: Update Netbox inventory plugin add region grouping, optional interfaces&vlans gathering, slug and prefix length
##### SUMMARY

Add sites groups as children in their respective region groups
Add 1 value to choose the length of the group name prefix (before the '_') and 1 to "minify" the suffix part (using slugs (or lowercase and change special chars (space, -) to underscore))
Add interfaces per host and vlans per site

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Netbox inventory plugin

##### ADDITIONAL INFORMATION

Grouping by regions add sites as children of the group but currently add hosts too.
Interfaces and vlan gathering works, maybe not perfectly optimized?

Similar to use_slugs in nornir netbox inventory plugin
https://github.com/nornir-automation/nornir/blob/develop/nornir/plugins/inventory/netbox.py

For interfaces gathering, the following is a good example :
https://github.com/openfibernet/ansible-netbox-inventory/blob/master/netbox.py
or #59725

```yaml
plugin: netbox
api_endpoint: https://netbox:443
validate_certs: False
config_context: True
token: xxx
vlans: True
interfaces: True
use_slugs: True
substr_group: 8
group_by:
  - device_roles
  - device_types
  - sites
  - platforms
  - tags
  - regions
query_filters:
  - role: SWA
  - platform: ios-xe
```

```
ansible-inventory --graph
@all:
  |--@platform_ios-xe:
  |  |--3850-SWA01
  |--@device_r_SWA:
  |  |--3850-SWA01
  |--@device_t_WS-C3650-48PD-S:
  |  |--3650-SWA01
…
  |--@device_t_WS-C3850-12X48U-S:
  |  |--3850-SWA01
…
  |--@regions_AMR:
  |  |--@sites_US-PHX:
  |  |--@sites_USATL04:
  |  |  |--3850-SWA01
  |  |--@sites_USPHX03:
  |  |  |--3650-SWA01
  |--@regions_APAC:
  |  |--@sites_INBLR01:
  |  |  |--3850-SWA01-1
  |--@regions_EMEA:
  |  |--@sites_CHZRH04:
  |--@tags_uat:
  |  |--3850-SWA01-1
  |--@ungrouped:

```

If a site is not assigned to a region, the plugin may fail

### PR DESCRIPTION
**Pull request by Yannis100**
##### SUMMARY

Add region grouping, optional interfaces&vlans gathering, slug, and group name prefix length

Fixes #60124

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

Netbox inventory plugin

##### ADDITIONAL INFORMATION

```yaml
plugin: netbox
api_endpoint: https://netbox:443
validate_certs: False
config_context: True
token: xxx
vlans: True
interfaces: True
use_slugs: True
substr_group: 8
group_by:
  - device_roles
  - device_types
  - sites
  - platforms
  - tags
  - regions
query_filters:
  - role: SWA
  - platform: ios-xe
```

```
ansible-inventory --graph
@all:
  |--@platform_ios-xe:
  |  |--3850-SWA01
  |--@device_r_SWA:
  |  |--3850-SWA01
  |--@device_t_WS-C3650-48PD-S:
  |  |--3650-SWA01
…
  |--@device_t_WS-C3850-12X48U-S:
  |  |--3850-SWA01
…
  |--@regions_AMR:
  |  |--@sites_US-PHX:
  |  |--@sites_USATL04:
  |  |  |--3850-SWA01
  |  |--@sites_USPHX03:
  |  |  |--3650-SWA01
  |--@regions_APAC:
  |  |--@sites_INBLR01:
  |  |  |--3850-SWA01-1
  |--@regions_EMEA:
  |  |--@sites_CHZRH04:
  |--@tags_uat:
  |  |--3850-SWA01-1
  |--@ungrouped:

```

### CODE REVIEW

**Comment by Yannis100** [comment]
I have to include #59028 changes
Let me know if you have any interest in my changes to be implemented, there are still some logics to be enhanced in my code (slug where missing, etc.)
I was wondering why values in vars like config_context, sites, manufacturers and so on, were contained in [] brackets; they can have only 1 value and we have to add [0] every time we want to access them. I know that changing this means a lot of people will have to adapt their templates/playbooks but I don't get why it was done like this in the first place

**Comment by DouglasHeriot** [comment]
I'm very keen to see this merged. I've merged it against devel to get #59028 config_context fixes.
https://github.com/hillsong/ansible/tree/region-group-netbox

Should I open my own new pull request, or @Yannis100  will you update yours?

**Comment by DouglasHeriot** [comment]
I'm also keen to see caching (#57644) included in this. Should it remain a separate pull request, or brought into this one?

I wonder if the inventory and lookup plugins (#59611) should be moved to a separate collection so improvements can be merged in separate to the Ansible core release cycle?
https://github.com/FragmentedPacket/netbox_modules

**Comment by Yannis100** [comment]
Hi @DouglasHeriot 
Thanks for your interest and comment

I still have some uncommited changes so I might include #59028 #57644 #59662 and then commit everything but it might take some days as I won't have time before next Tuesday

**Comment by Yannis100** [comment]
I included #59028 #57644 #59662
But I included a breaking change for config-context, removing the outer brackets (still wondering why an array is used for single value variables like sites, etc.)
New tests and a changelog entry still has to be written

**Comment by s-hertel** [comment]
FYI, including other pull requests in this manner loses attribution of the original author in addition to making it difficult to review the changes happening in the PR. When possible, please add 1 feature per PR if they are not closely linked or dependent on one another.

**Comment by Yannis100** [comment]
Yeah, sorry, didn't want to steal other people work, it was more a "preemptive rebase" (probably a bad one) assuming the other "small" changes will be merged before this one

**Comment by Yannis100** [comment]
I'm having trouble rebasing my branch with origin/devel
I'll try to recreate the branch from scratch and include my changes in a single commit with _use_slug_ variable checking when missing

For unit tests, I'll have to dive in the source code, and it will take a couple of days/weeks

**Pull request closed without merging**
