### PR TITLE
VMware: Handle slash in network name in vmware_guest module

### LINKED ISSUE #64399: Slash in network name causes vmware_guest module to return Network ... does not exist
##### SUMMARY

We are using the vmware_guest module to deploy a VM Template on a vCenter cluster. When we specify a virtual network name that contains a slash in it (e.g. 0123-network-name-10.0.0.0/22), Ansible returns "Network '0123-network-name-10.0.0.0/22' does not exist. This problem does not occur with network names that do not contain slashes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ansible running within AWX 9.0.0
Target vCenter environment - vCenter 6.7.0 build 14070654

##### STEPS TO REPRODUCE

Create a playbook with a single task in it to deploy and customize a VMware Template using the vmware-guest module. Specify a virtual network name with a "/" in it.

```yaml
- name:  Clone a virtual machine from Linux template and customize
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    state: present
    folder: "{{ vm_folder }}"
    template: "{{ template }}"
    name: "{{ vm_name }}"
    cluster: "{{ vm_cluster }}"
    networks:
      - name: "{{ vm_network }}"
        dvswitch_name: "dvSwitch"
    hardware:
      num_cpus: "{{ vm_hw_cpus }}"
      memory_mb: "{{ vm_hw_mem }}"
    wait_for_ip_address: True
    customization_spec: "{{ vm_custspec }}"
  delegate_to: localhost
```

##### EXPECTED RESULTS

Expect vmware_guest to launch or update the VM specified by vm_name variable with the parameters specified.

##### ACTUAL RESULTS

```paste below
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
PLAY [EDF VMware Deployment playbook] ******************************************
TASK [Gathering Facts] *********************************************************
ok: [localhost]
TASK [deployvm : Clone a virtual machine from Linux template and customize] ****
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Network '0123-network-name-10.0.0.0/22' does not exist."}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
 ```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Encode slash in network name to work with vSphere API.

Fixes: #64399

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE 
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/64399_vmware_guest.yml
lib/ansible/module_utils/vmware.py
lib/ansible/modules/cloud/vmware/vmware_guest.py

### CODE REVIEW

**Review by pgbidkar — COMMENTED** [review]
LGTM.
How about adding one integration test with '/' in network name, while cloning and customization?

**Comment by sky-joker** [comment]
Hi @Akasurde

`\` and `%` are also valid strings and are URL encoded as follows.

| symbol | encode |
|--------|--------|
| \      | %5c    |
| %      | %25    |

Is it okay if these are not implemented in vmware_guest module?

**Comment by Akasurde** [comment]
> Hi @Akasurde
> 
> `\` and `%` are also valid strings and are URL encoded as follows.
> symbol 	encode
> \ 	%5c
> % 	%25
> 
> Is it okay if these are not implemented in vmware_guest module?

yes sure.

**Review by pgbidkar — APPROVED** [review]
LGTM

**Review by Andersson007 — APPROVED** [review]
CI tests are presented, so
shipit

**Pull request merged**
