### PR TITLE
Output version string when --version is passed using optparse's version ...

### PR DESCRIPTION
**Pull request by willthames**
Simple change to add --version argument to ansible

### CODE REVIEW

**Comment by mpdehaan** [comment]
Needed to do this for a while, thanks!

Ideally if running from git it would be nice to include the git SHA info -- I'll make a note to see about adding that later.

**Comment by willthames** [comment]
I'd have liked to have added the branch as well, but the pure python solution was the simplest for now. 

One solution I considered was to have lib/ansible/version.py that could be overwritten by make, but I don't know enough about extracting the git information. Also, given that I go a while between running make in dev, if baked in through make it could well be out of date. I'll have a think about it too, if I come up with anything I'll let you know.

**Comment by willthames** [comment]
That first sentence of the second paragraph should really be split in two - 'I considered a version.py that could be overwritten by make. I don't know enough right now about extracting the git information for a better solution that I'm sure is possible'

**Comment by mpdehaan** [comment]
Seeing we don't require a make install -- in order to keep it accurate -- it would probably have to find if "/bin/ansible (or playbook), basically sys.argv[0], has a .git directory a level up and then run a git command.   That might not always include the git info, but it would be pretty close.

Somewhat non-trivial.

**Pull request merged**
