### PR TITLE
Initial commit of cpm_interface_config

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Initial commit of cpm_interface_config allowing the configuration of Ethernet ports of WTI OOB and PDU type units.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
cpm_interface_config

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by dmobergIT** [comment]
Why would I be getting this return value?
{
"status": {"code": "1","text": "invalid command"}
}

**Comment by bcc79man** [comment]
After I set the Ethernet port IP address I cant talk to the device any more?

**Comment by wtinetworkgear** [comment]
@dmobergIT It looks like you have an older firmware that does not support this API, what version of the WTI firmware are you running ? The newest firmware can be found here at no charge: https://www.wti.com/t-firmware-upgrade.aspx or if you have any trouble email us at support@wti.com

**Comment by wtinetworkgear** [comment]
@bcc79man After you set the IP address with this module, you will get a response from the WTI box, then 10 seconds later the IP address of the interface you configured will change, your next query to the WTI device should be using the new IP address you just defined.

**Pull request closed without merging**
