### PR TITLE
vmware_guest: Fix undefine variable in rename feature

### PR DESCRIPTION
**Pull request by aperigault**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
2.2.1
```

##### SUMMARY
All is in subject

### CODE REVIEW

**Comment by nerzhul** [comment]
shipit

**Comment by nerzhul** [comment]
oh i fixed it too in #20971 , we will see who will be merged first

**Comment by jctanner** [comment]
@aperigault why wouldn't the user want to wait for the template task to complete?

**Comment by aperigault** [comment]
@jctanner Because we can't. According to pyvmomi doc (and after tests) MarkAsTemplate no return result.

**Comment by nerzhul** [comment]
yeah, template marking is just a simple push call :(

**Comment by dagwieers** [comment]
shipit

**Pull request merged**
