### PR TITLE
Vars specified via CLI have the highest priority.

### PR DESCRIPTION
**Pull request by alopropoz**
Issue ansible/ansible#1324

### CODE REVIEW

**Comment by mpdehaan** [comment]
past the 0.8 feature freeze date, so this is on deck for review when 0.9 starts (after Friday) ... stay tuned

**Comment by mpdehaan** [comment]
merged, thanks!   Will push this when I get back on acceptable computer network!

**Comment by mpdehaan** [comment]
nm, I can web merge this.  Good to go.

**Comment by cheeming** [comment]
This was reverted at d585fe83bcadc5038e0e6ae8f2e22904a35db90f (FYI for those who are wondering about this)

**Pull request merged**
