### PR TITLE
Aws ec2 legacy settings

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
add all the cruft on #53458

##### ISSUE TYPE
- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by AlanCoding** [comment]
I might as well link where I've attempted to do this at:

https://github.com/ansible/awx/pull/3266/files#diff-131ca73c9ddeed5719e3ac78360883cc

This PR here won't selectively redact based on the group name. In that diff, if replace_dash=False, then we get group names like:

 - tag_user_defined_tag_used_to_have_dashes_but_now_does_not
 - us-east-1

It was requested to replace dashes, but the dash in the region name was not replaced. The tie-in to keyed groups construction makes that very difficult to image that it would be handled with legacy settings like this.

I would also like Ansible core to be able to lose code related to `ec2_*` var construction.

**Comment by s-hertel** [comment]
Sorry, I'm not following your train of logic. :-/ Region doesn't replace dashes to be compatible with the script.

And hm.... Are you on the right branch?
Here's what I'm getting with replace_dash_in_groups = False behavior:
Script:
```
  |--@tag_tag-with-hyphens_value_with_colons:
  |--@type_t2_micro:
  |--@us-east-1:
  |--@us-east-1e:
  |--@vpc_id_vpc-00ae247fabc41dd04:
```
Plugin:
```
  |--@tag_tag-with-hyphens_value_with_colons:
  |--@type_t2_micro:
  |--@us-east-1:
  |--@us-east-1e:
  |--@vpc_id_vpc-00ae247fabc41dd04:
```

Here's with replace_dash_in_groups = True behavior:
Script:
```
  |--@tag_tag_with_hyphens_value_with_colons:
  |--@type_t2_micro:
  |--@us-east-1:
  |--@us-east-1e:
  |--@vpc_id_vpc_00ae247fabc41dd04:
```
Plugin:
```
  |--@tag_tag_with_hyphens_value_with_colons:
  |--@type_t2_micro:
  |--@us-east-1:
  |--@us-east-1e:
  |--@vpc_id_vpc_00ae247fabc41dd04:
```

Also the legacy host vars wouldn't have any impact on your `compose` option. Any host vars you composed would win/overwrite the legacy host vars.

**Comment by s-hertel** [comment]
I'll reopen this if people are interested in the abstraction for a simpler config file for users but people can achieve the same results via their config.

**Comment by s-hertel** [comment]
I'll reopen this if there is interest in the abstraction for a simpler config file but people can achieve the same results via their config.

**Pull request closed without merging**
