### PR TITLE
Better documentation, removed runfcgi, added createcachetable

### PR DESCRIPTION
**Pull request by tastychutney**
Merges the changes you made as well.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Great, thanks!

BTW, when you say it will make a virtualenv, it will only do that if you ask for one, right?

**Comment by tastychutney** [comment]
No, if it doesn't find one it makes one. If you think it needs a "nocreate" or "create" I can add it. And actually I'm not sure why I do that at all now that I think about it. It should probably just fail.

What do you think?

**Comment by mpdehaan** [comment]
If you don't specify 'virtualenv' could it just not do it?

**Comment by tastychutney** [comment]
Oh! Right, if there's no virtualenv param it doesn't create one. But if there is a virtualenv param but no virtualenv at that location, it will create one.

I think I did that because I glommed the code from pip. It seems more like a pip thing to do than a django-manage thing.

**Comment by mpdehaan** [comment]
Sounds reasonable to me.    We should tweak the doc so that is maybe a bit
more obvious, as it seems to imply it will always make one.

**Comment by tastychutney** [comment]
How's this?
- This module will create a virtualenv if the virtualenv parameter is specified and a virtualenv does not already exist at the given location.

If good I'll push it and issue another pull request. This is all good feedback.

**Comment by mpdehaan** [comment]
Sounds great, much appreciated!

**Pull request merged**
