### PR TITLE
Sorry wrong project, please delete

### PR DESCRIPTION
**Pull request by DigitalDrifta**
Sorry wrong project, please delete

### CODE REVIEW

**Comment by jhawkesworth** [comment]
you can delete this yourself I think if you are logged in to github.

by the way, like the idea of adding source parameter to win_feature - definitely useful.

**Comment by DigitalDrifta** [comment]
Thanks i tried but I can only edit, not remove it altogether. I've never contributed before so still finding my legs. The code is done, I'm going to try commit it now.

**Comment by srgvg** [comment]
Not deleting, just close this PR

**Comment by DigitalDrifta** [comment]
Sorry I messed up, closing.

**Pull request closed without merging**
