### PR TITLE
modules/xbps: various changes

### PR DESCRIPTION
**Pull request by CameronNemo**
##### SUMMARY

xbps is the package manager for void linux.

Commit summary:
* one small bugfix
* another refactor
* the last a feature/fix to support changes in xbps behavior, along with some docs

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

xbps

##### ADDITIONAL INFORMATION

Please see commit messages.

### CODE REVIEW

**Comment by CameronNemo** [comment]
Meant to mark this branch WIP as I have yet to complete my testing and review, please do not merge. Feel free to review the code for style and bugs, though.

**Comment by CameronNemo** [comment]
Completed my review and fixed the missing version_added tag.

**Comment by the-maldridge** [comment]
Looks  good so far, I'd like this to sit open for a little while while we test it against the recently updated version of xbps, then I'll merge.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. As of March 23 this module is no longer maintained in this repository, and has been migrated to https://github.com/ansible-collections/community.general

I see you have submitted the pull request at the above repository, so I am going to proceed with closing this pull request.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
