### PR TITLE
[2.9] mysql_user: Fix idempotence when long grant lists are used

### PR DESCRIPTION
**Pull request by apollo13**
(cherry-picked from commit https://github.com/ansible-collections/community.general/commit/8d203225d35d1db952bfee89ad72572bc96fe845)

Backport of https://github.com/ansible-collections/community.general/pull/58

### CODE REVIEW

**Comment by Andersson007** [comment]
rebuild_failed

**Comment by Andersson007** [comment]
@apollo13 i hope it'll be merged ASAP. If you see `stale ci label`, just put rebuild_failed (like i did above)

**Comment by felixfontein** [comment]
I don't think there's a need to rebuild backports when `stable_ci` shows up. But usually backports don't lie around for that long.

**Pull request merged**
