### PR TITLE
Documentation updates for zabbix_maintenance.py

### PR DESCRIPTION
**Pull request by richlv**
clarify that removal happens by name - while expected, it's good to be explicit

##### SUMMARY
be more explicit about removal

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
zabbix_maintenance

##### ANSIBLE VERSION
latest

### CODE REVIEW

**Comment by eikef** [comment]
shipit

**Comment by eikef** [comment]
@D3DeFi mind having a look as well? :)

**Comment by D3DeFi** [comment]
It is always ok to be more specific! :)

**Comment by D3DeFi** [comment]
shipit

**Pull request merged**
