### PR TITLE
Fixed inefficient regex.

### PR DESCRIPTION
**Pull request by lonerr**

### CODE REVIEW

**Comment by jimi-c** [comment]
Your new regex has an error in it, you're missing a `\` before the first `w`.

**Comment by mpdehaan** [comment]
This appears to be a bugfix, not a feature request, so changing tags @jimi-c 

can you please share instructions how to get into this scenario where it becomes a problem?

Thanks!

**Comment by lonerr** [comment]
@jimi-c you are right, sorry for my carelessness :(
What i suppose to do? Close this pull request and create the new one?

**Comment by lonerr** [comment]
@mpdehaan , my real case:
Using diff mode with 'template' module on file /etc/services (~2500 lines, ~87KB) ansible-playbook performed about 40 seconds on my laptop. After this patch applied - about 1 second.

Simple test case for regex:
[lonerr@neon ~]% time python -c "import re; re.match(r'._\w+=\w+._',''.join('x' for x in xrange(65536)))"
real    0m23.890s
user    0m23.798s
sys 0m0.043s

[lonerr@neon ~]% time python -c "import re; re.search(r'\w=\w',''.join('x' for x in xrange(65536)))"
real    0m0.039s
user    0m0.027s
sys 0m0.010s

**Comment by jimi-c** [comment]
@lonerr you can just update the patch with `git commit --amend` and then re-push the branch with `--force`. Github will then update the PR in place and I can merge it in (after testing of course).

**Comment by lonerr** [comment]
Thanks @jimi-c ! Done.

**Comment by jimi-c** [comment]
Now that I look at this, there are a additional problems. Using `\w=\w` will probably catch any = in the middle of a string, and isn't much better than doing `if '=' in ...`. I've tested the following out and it seems to be just as quick while properly identifying things that will most likely be a k=v pair:

<pre>
$ time python -c "import re; test='A'*65536+' foo=bar '+'A'*65536; print len(test); print re.match(r'^.*\b(\w+=\w+)\b', test).groups()"131081
('foo=bar',)
real    0m0.011s
user    0m0.010s
sys 0m0.000s
$ time python -c "import re; test='A'*65536+' foo=bar'; print len(test); print re.match(r'^.*\b(\w+=\w+)\b', test).groups()"
65544
('foo=bar',)
real    0m0.009s
user    0m0.005s
sys 0m0.003s
$ time python -c "import re; test='foo=bar '+'A'*65536; print len(test); print re.match(r'^.*\b(\w+=\w+)\b', test).groups()"
65544
('foo=bar',)
real    0m0.011s
user    0m0.007s
sys 0m0.003s
</pre>

So go ahead and update your PR with what I have above: `r'^.*\b\w+=\w+\b'` and we can test that.

**Comment by lonerr** [comment]
Hmm, @jimi-c , could you provide an example of string that mistakenly matched with r'\w=\w' and not matched with 'r'^.*\b\w+=\w+\b'  ?

**Comment by jimi-c** [comment]
As it stands, `\w=\w` won't match anything except for a simple string like `a=b`. For example:

<pre>
python -c "import re; test='foo=bar'; print len(test); print re.match(r'(\w=\w)', test).groups()"
7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'groups'
</pre>

So you need to use the `+` to capture more characters, however that's what was making it slow, since it had to traverse the whole string. Anchoring it to the start of the line as well as requiring the word boundary around it seems to help with that though as shown by my tests above.

**Comment by lonerr** [comment]
Hmm, do you feel the difference between re.match and re.search?

[lonerr@neon ~]% python -c "import re; test='foo=bar'; print len(test); print re.search(r'(\w=\w)', test).groups()"
7
('o=b',)

I will clarify my question: could you provide an example of string that mistakenly matched with re.search(r'\w=\w') and not matched with re.match('r'^.*\b\w+=\w+\b') ?

**Comment by lonerr** [comment]
Hi, @jimi-c !
I'll be glad to hear your answer to the last question.

**Comment by jimi-c** [comment]
@lonerr sorry, been a busy week :)

Hrm, I wasn't aware that .search() would treat that differently than .match(), I guess it implies a word boundary for a match? In that case, the original is fine when using just search().

**Comment by lonerr** [comment]
re.match implies '^' at line beginning, in other words re.match('foo') is roughly equivalent to re.search('^foo').
And re.search('\w=\w') is "minimum one alphanumeric character followed by equivalence sign and minimum one alphanumeric character in any position of line".
In my opinion it is a necessary and sufficient condition.

**Comment by amenonsen** [comment]
This PR can be closed, there's no regex in _filter_leading_non_json_lines any more.

**Comment by jimi-c** [comment]
@amenonsen I believe we need to add it back in, so I'll leave this open for now.

**Comment by amenonsen** [comment]
OK, in that case, @lonerr, do you feel like revising this PR to add the regex test to devel?

**Comment by amenonsen** [comment]
Note that the function has moved to `lib/ansible/plugins/action/__init__.py` now; see also PR #7815.

**Comment by lonerr** [comment]
This pull request can be closed since the refactored version of filter_leading_non_json_lines() has no more regex at all.

**Pull request closed without merging**
