### PR TITLE
Extend ec2 module to support spot instances

### PR DESCRIPTION
**Pull request by josephtate**
This is a patch to be considered as a response to #2846

### CODE REVIEW

**Comment by jctanner** [comment]
@josephtate two things:

1) We need a "version_added:" for each new parameter set in the module docs
2) The create_instances function is getting really long. Can you refactor your patch to add some more functions and maybe even look into moving code to lib/ansible/module_utils/ec2.py ? Just a thought.

**Comment by josephtate** [comment]
Unfortunately, with no unit tests available for this module, I'm hesitant to make a significant refactoring attempt. There's not much I could do anyway besides deepen the call stack. Boto is not very well abstracted, and there's just enough difference in launching a normal instance and a spot instance that there isn't a good code-reuse opportunity.

**Comment by jimi-c** [comment]
I have this code somewhat cleaned up and merged with devel. We will most likely be refactoring this heavily before merging it.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
