### PR TITLE
Remove more whitelist and blacklist occurances

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Thanks to @aminvakil for pointing some of these out on IRC!

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
lib/ansible/config/base.yml                
lib/ansible/inventory/manager.py           
lib/ansible/modules/iptables.py            
lib/ansible/plugins/inventory/auto.py      
lib/ansible/plugins/inventory/ini.py       
lib/ansible/plugins/inventory/script.py    
lib/ansible/plugins/inventory/yaml.py      
lib/ansible/plugins/vars/host_group_vars.py
lib/ansible/utils/encrypt.py               
lib/ansible/vars/plugins.py

### CODE REVIEW

**Comment by acozine** [comment]
Thanks @felixfontein and @aminvakil!

**Comment by felixfontein** [comment]
CC @bcoca

**Review by briantist — APPROVED** [review]
nice, thank you for this

**Review by bcoca — APPROVED** [review]

**Review by samccann — APPROVED** [review]

**Comment by felixfontein** [comment]
@aminvakil @acozine @briantist @bcoca @samccann thanks for reviewing and merging!

**Pull request merged**
