### PR TITLE
Add NETCONF support for SROS devices

### PR DESCRIPTION
**Pull request by wisotzky**
##### SUMMARY
Support Nokia SROS devices for connection=netconf

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Plugin: NETCONF

##### ANSIBLE VERSION
```
2.6.0
```

### CODE REVIEW

**Review by ganeshrn — APPROVED** [review]
Looks good. Please add an entry in Botmeta file [here](https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml#L1045) for sros plugin and add your Github id against it, so that you will get notified in case of any issues raised related to this file.
```
  lib/ansible/plugins/netconf/sros.py:
    maintainers: wisotzky
    labels: networking
```

**Comment by ganeshrn** [comment]
Please rebase your branch. Here are the steps to follow http://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html

**Comment by ganeshrn** [comment]
bot_status

**Comment by ganeshrn** [comment]
@wisotzky Your last commit in this PR has a merge commit
https://github.com/ansible/ansible/commit/d07a78af0465b08e0c90322ca96e20c79ab03b11

Please rebase your branch to remove the merge commit so that we can go ahead and merge this PR.

**Comment by wisotzky** [comment]
@ganeshrn 
Could you please check, if it is okay now?

**Comment by ganeshrn** [comment]
The PR still has merge commit, in the `Commits` section please check your last commit.
In order to remove merge commit please follow the steps given here 
http://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html

**Comment by wisotzky** [comment]
@ganeshrn 
Just did the rebase as described...
Let's see if it works now.

**Comment by ganeshrn** [comment]
@wisotzky The merge conflict is resolved now. Thank you!

**Pull request merged**
