### PR TITLE
Pamd Module

### PR DESCRIPTION
**Pull request by kevensen**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

pamd
##### ANSIBLE VERSION

```
ansible 2.3.0.0
```
##### SUMMARY

While lineinfile and replace are very useful, I felt that a module specific to updating pam.d services was necessary.

### CODE REVIEW

**Comment by kevensen** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2640

**Review by gundalow — APPROVED** [review]
Looks good to me,  though an extra set of eyes on this would be good. 

@alikins I see you looked at the previous PR, are you happy with this now?

**Comment by alikins** [comment]
LGTM

**Comment by kevensen** [comment]
Thanks guys!  Just a quick question.  Out of curiosity, is this going in the extras or core modules?

**Comment by gundalow** [comment]
@kevensen Neither!
As of 2.3 we've dropped the concept of `ansible-modules-core` and `ansible-modules-extras`.
This module will be shipped with Ansible 2.3

**Pull request merged**
