### PR TITLE
Fix root volume security style options for NetApp ONTAP SVM module

### PR DESCRIPTION
**Pull request by timuster**
##### SUMMARY

Fixes supported options for security-style of SVM root volumes.

##### ISSUE TYPE

 - Bugfix Pull Request
 
##### COMPONENT NAME

na_cdot_svm

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```

### CODE REVIEW

**Comment by timuster** [comment]
@hulquest @lmprice Can you guys please help review this? Thanks!

**Comment by hulquest** [comment]
LGTM.  Maybe you can explain offline to me why cifs was removed but not critical to the PR.
shipit

**Comment by lmprice** [comment]
Simple; LGMT
shipit

**Comment by timuster** [comment]
@hulquest The ONTAPI documentation states that valid options are "unix" for NFS, and "ntfs" for CIFS. Although I had a logic in there earlier to take either parameters in the 2 cases, we decided to stick with "unix" and "ntfs" specifically to keep it consistent with the official documentation.

**Pull request merged**
