### PR TITLE
Adding env to allow cron jobs with environment variables

### PR DESCRIPTION
**Pull request by djatlantic**

### CODE REVIEW

**Comment by mpdehaan** [comment]
we typically do commas for list seperation and then we could do type=list in the argument spec.

Will that work?

Also, yes, please update this to 4 space indents.

Thanks!

**Comment by aiwilliams** [comment]
:+1:

**Comment by vpetersson** [comment]
+1

**Comment by vcastellm** [comment]
+1

**Comment by AnneTheAgile** [comment]
1.Is the merge conflict here because @djatlantic somehow did not git merge the fix for changing to 4 spaces ?  //edit 2014-09-29Mon : No more conflict note appears here - I'm  not sure if that is due to its being closed with the reorg of the git repo?
2.This ticket would include the desired MAIL_TO functionality of #5466 .
3.Is that the only issue barring approval? 
3b.The doc could use an update - doublequotes should surround the two variables, and change to 'Create'. I could do that if we like the fix.

```
#creat a cron with env
- cron: name="djstellar_getmodels" job="/home/djstellar/bin/getmodels.sh > /dev/null 2>&1" env=MAILTO=ops@gmail.com,SHELL=/bin/bash hour=1 minute=9
```

//AnneTheAgile ; update; reorg, added [3], [3b]

**Comment by DavidWittman** [comment]
:+1: I need this.

**Comment by mdesjardins** [comment]
+1 I need this too!

**Comment by jimsmith** [comment]
+1 I need this also.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Comment by AnneTheAgile** [comment]
I'm  unclear if there is/not a merge conflict any more. Also as much upvoted, maybe it can be accepted on the new repo. I mentioned it here; https://github.com/ansible/ansible-modules-core/issues/50

**Pull request closed without merging**
