### PR TITLE
K8s inventory plugin

### PR DESCRIPTION
**Pull request by chouseknecht**
##### SUMMARY
Adding `k8s` and `openshift` inventory plugin 

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/plugins/inventory/k8s.py
lib/ansible/plugins/inventory/openshift.py

##### ANSIBLE VERSION
```
ansible 2.5.0 (feature/k8s-inventory bec8ebe9fb) last updated 2018/01/16 05:21:05 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/chouseknecht/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chouseknecht/projects/ansible/lib/ansible
  executable location = /Users/chouseknecht/projects/ansible/bin/ansible
  python version = 2.7.14 (default, Nov 14 2017, 23:24:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
```

### CODE REVIEW

**Comment by chouseknecht** [comment]
@maxamillion @flaper87 @samdoran @jcpowermac @fabianvf @rcarrillocruz 

I think this is in a good place. Would appreciate any feedback.

I'm testing with the following `ansible.cfg`:

```
[defaults]
remote_tmp = /tmp

[inventory]
enable_plugins = k8s, openshift
```

I'm just using the default `~/.kube/config`, and active context against a local minishift instance. 

So my simple `k8s.yml` contains:

```
plugin: k8s
connections: []
```

And for `openshift.yml`, I have the following:

```
plugin: openshift
connections: []
```

Here's a test playbook. You'll need to changes `hosts` on the second and third plays to a group `_pods` that works for your environment.

```
- name: Test inventory
  hosts: localhost
  gather_facts: no

  tasks:
  - name: View the inventory
    debug:
      msg: '{{ groups }}'

- name: Test labels
  hosts: awx_pods
  gather_facts: no

  tasks:
  - name: Set labels fact
    set_fact:
      host_labels: '{{ labels }}'
    when: "'name_postgresql' in labels"

  - debug:
      var: host_labels
    when: "'name_postgresql' in labels"

  - name: Labels should have 4 values
    assert:
      that: "host_labels | count == 4"
    when: "'name_postgresql' in labels"

- name: Test container connection
  hosts: awx_pods
  gather_facts: no

  tasks:
  - raw: ls -l /var
    when: container_ready
    register: output

  - assert:
      that: "output.stdout_lines | count > 1"
    when: container_ready
```

Run the above using either plugin. So for `openshift`, you would do the following:

```
ansible-playbook  --inventory=openshift.yml test.yml
```

**Comment by chouseknecht** [comment]
@smarterclayton 

It adds labels to all the returned objects, to enable selecting by label. But just realized, I'm adding labels to the object as `key_value` strings. Wondering if they can be added as a dict(), and be more usable. Experimenting...

**Comment by chouseknecht** [comment]
@smarterclayton

Pushed a change. Now all structured data is handled as such, and not as strings. For example, with labels, you can now do the following:

```
- name: Test labels
  hosts: awx_pods
  gather_facts: no

  tasks:
  - name: Show labels
    debug:
      var: labels
    when: "'name' in labels"

  - name: Show labels for a single container
    debug:
      var: labels
    when: labels.name == 'postgresql'

  - name: Check label count for a given container
    assert:
      that: 'labels | count == 4'
    when: labels.name == 'postgresql'
```

**Comment by chouseknecht** [comment]
[Ansible Inventory plugin](https://trello.com/c/HpB8vxwH/17-ansible-inventory-plugin)

**Comment by maxamillion** [comment]
I think this is great :+1:

**Comment by flaper87** [comment]
LGTM 🥞

**Comment by flaper87** [comment]
shipit

**Pull request merged**
