### PR TITLE
docker_swarm_service: Add stop_signal option

### PR DESCRIPTION
**Pull request by hannseman**
##### SUMMARY

Add `stop_signal` option.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

docker_swarm_service

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
rebuild_merge

**Comment by gundalow** [comment]
@hannseman Thank you for this feature
@felixfontein Thank you for the continued reviews.
Merged this feature into `devel` for release in Ansible 2.8

**Pull request merged**
