### PR TITLE
Adjust text for validate. Put all the text in one spot.

### PR DESCRIPTION
**Pull request by jjshoe**

### CODE REVIEW

**Comment by jimi-c** [comment]
Two minor notes:
1. comment from old code: '# AWS only documentation fragment'
2. would it also be better to move the required and default fields into this? Making them consistent across the different modules would be nice as well.

**Comment by jjshoe** [comment]
@jimi-c I looked at version_added, I knew that changed. I'll look into the required/default fields and get them moved in if appropriate. Whoops on copying in the aws only document fragment piece.

**Comment by jjshoe** [comment]
@jimi-c All cleaned up and good to go!

**Comment by mpdehaan** [comment]
This diff appears to remove the body of the "validate" documentation but doesn't remove the actual keys from each entry or the "version_added" parts of the doc.

Can you update this?

Thanks!

**Comment by jjshoe** [comment]
@mpdehaan "version_added" can not be removed, as the version in which validate was added is different among modules.

**Pull request closed without merging**
