### PR TITLE
Add link to all module and plugin indexes

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The indexes are already there (https://docs.ansible.com/ansible/latest/collections/index_module.html, https://docs.ansible.com/ansible/latest/collections/index_lookup.html, ...), but right now impossible to find since nobody links to them.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docsite

### CODE REVIEW

**Comment by felixfontein** [comment]
I think we need antsibull to generate this 'index of indexes', since the devel build doesn't include all plugin types (since it only covers ansible/ansible, and not the collections).

**Comment by felixfontein** [comment]
For a better solution, something like https://github.com/ansible-community/antsibull/pull/220 is needed.

**Comment by acozine** [comment]
This is a great addition! Having the all-modules index back will be fantastic, and yes, we should link to it from the main TOC.

Looking at this PR, it's obvious what the `all_plugins.rst` file is. However, without that context I'm afraid Future Me is going to spend cycles on "what is this thing, again?". Can we either rename the file or move it or both? 

The most logical spot for it would be in the `collections/` folder, maybe as `plugins_by_type.rst`? That would mean changing the .gitignore entry. Another option would be to leave it in the root `rst/` directory and call it `index_of_all_plugin_index_pages.rst`. What do others think?

**Comment by samccann** [comment]
If possible, I also like the idea of moving it under /collections.

**Comment by felixfontein** [comment]
I can't figure out how to properly add a file in collections/. Does anyone have an idea how to get that working?

**Comment by acozine** [comment]
@felixfontein you did what i would have done, not sure why it's failing. I'll bang on it for a bit, see if I can get it working.

**Comment by felixfontein** [comment]
@abadger thanks for fixing this!

**Comment by abadger** [comment]
My pleasure :-)

**Review by samccann — APPROVED** [review]

**Comment by felixfontein** [comment]
@acozine @samccann @abadger thanks a lot for reviewing, getting this to work, and merging! :)

**Pull request merged**
