### PR TITLE
postgresql_db: add support for tablespaces

### PR DESCRIPTION
**Pull request by m4ci3k2**
##### SUMMARY
Add support for specifying tablespace in `postgresql_db` module, both for creation and moving of existing databases.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
postgresql_db

##### ANSIBLE VERSION
```
devel
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/59763/25/tests

> test/integration/targets/postgresql/tasks/main.yml:111 / [testhost] testhost: postgresql : assert that=[u"result.stdout_lines[-1] == 'CREATE TABLESPACE'"]

> failure: The conditional check 'result.stdout_lines[-1] == 'CREATE TABLESPACE'' failed. The error was: error while evaluating conditional (result.stdout_lines[-1] == 'CREATE TABLESPACE'): list object has no element -1

```
{
"msg": "The conditional check 'result.stdout_lines[-1] == 'CREATE TABLESPACE'' failed. The error was: error while evaluating conditional (result.stdout_lines[-1] == 'CREATE TABLESPACE'): list object has no element -1"
}
```

**Comment by Andersson007** [comment]
Hello, @m4ci3k2 . Thank you for this PR.
Could you fix conflicts, add tests, etc, for this?
If yes, cool. After that we can review it.
If you can't do it for any reasons, please, let us know.
We'll be waiting for your answer till Monday-Tuesday, thank you!

**Comment by m4ci3k2** [comment]
Okay, I was overwhelmed by other things previously, but I'll take care of it in the coming week.

**Comment by Andersson007** [comment]
@m4ci3k2 , cool, waiting for fixing

**Comment by Andersson007** [comment]
needs_info

**Comment by kenytux** [comment]
Hello,
Did you if the add support for tablespaces in postgresql_db will be added in 2.8?

**Comment by Andersson007** [comment]
@kenytux , hello, I think, no, it will not. Hope it will completed to 2.9. It depends on the author.
Or maybe I'll do it by another PR (but i didn't look at the code and logic, waiting when conflicts will be fixed)

**Comment by Andersson007** [comment]
@kenytux , i took a quick glance, the logic seems OK.
@m4ci3k2 , if you came across any difficulties to solve conflicts, just create a new PR insted, it's not big. Then we'll look at it in detail :)

**Comment by kenytux** [comment]
@Andersson007 Hello, so I can use it as an external library?

**Comment by Andersson007** [comment]
@kenytux , sorry, I don't really understand what do you mean.
Probably it will be in release 2.9. The following release (2.8, going to be released in May) in the feature freeze now

**Comment by kenytux** [comment]
@Andersson007 I mean, actually I need to create a Postgresql DB in a specific tablespace. So I can use the postgresql_db.py of https://github.com/m4ci3k2/ansible/tree/postgres_db_tablespace.
I just need to put it in library folder of my workspace, do I'm right?

**Comment by Andersson007** [comment]
@kenytux , in short, yes, it’s possible

**Comment by kenytux** [comment]
@Andersson007 Thank you very much!!!!

**Comment by Andersson007** [comment]
@kenytux , welcome:) hope it will be released in 2.9

**Comment by kenytux** [comment]
Hello @Andersson007

I used it after some modifications and it worked.

Do you want me to send you the file postgresql_db.py?

**Comment by Andersson007** [comment]
@kenytux , hello. Yes:) might be useful. aaklychkov at mail dot ru , thank you

**Comment by dagwieers** [comment]
Closed as requested by @Andersson007

**Comment by Andersson007** [comment]
Yep, thank you

**Pull request closed without merging**
