### PR TITLE
Change backup naming

### PR DESCRIPTION
**Pull request by vshkolin**
Discussion is here: https://groups.google.com/d/msg/ansible-project/zYO3sKW1oMM/OgKPoJKPDXUJ

### CODE REVIEW

**Comment by jctanner** [comment]
@vshkolin what is the expected workflow with this, when the remote user is not root or unprivileged?

**Comment by vshkolin** [comment]
What is the expected with current backup naming scheme, when user is not root or sudo-ed?
For example, user bob want to change file /somedir/bob.cfg, where /somedir is root.root 755, and bob.cfg is bob.bob 640? Classic scheme will try to make backup file /somedir/bob.cfg.timestamp~ :)

New scheme (backup file in separate tree) can resolve this problem. The best way is some option in config file, or in playbook, or some inventory "magic" variable, that can set basepath for backup tree. When user is not root, he will set this path to some subdirectory into his $HOME.

I do not know, how to add new options to ansible's config parser, etc. I use root access, and my solution is good for me.  If you need non-root access with new naming scheme, you can add backup basepath option yourself.

**Comment by mpdehaan** [comment]
Thanks for comments.

We still need to think about this one but are leaving it open for now.  

Thanks!

**Comment by mpdehaan** [comment]
My current long term plan on backups is for the module to return a special "files_to_backup" array, fetch them, and remove them, keeping them centrally or on a configured backup server.  As such I think we shouldn't evolve the backup system in favor of that approach.

This is however not an especially near term objective.

**Comment by vshkolin** [comment]
It is not so good.

If new configuration file will be wrong, and link between managed server and backup server will be terminated, we have no chance to repair old file locally; we can't do "diff oldfile newfile", etc. One error in new file can destroy many servers :)

I think, that the backup files must be present on managed server. Later, this tree can be copied to backup server by standard daily backup procedure (bacula, rsync etc).
Moving backups to another server will make unneeded "cross-reference". More cross-references - more complexity while restoring. I use "local backup tree" long time and it is very useful.

Can you merge my patch and add the "backup tree base" option into the ansible config? It is less hardy, then implement "files_to_backup" array. You can add this array later, in accordance of your long tern plans.

**Pull request closed without merging**
