### PR TITLE
Introduce module mvn_get to download Maven artifacts

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by srgvg** [comment]
@jirutka seems this module is missing to implement authentication?
I wanted to test it on a private Nexus repository, which needs this.

**Comment by markhobson** [comment]
I'm not sure that the Maven artifact coordinate parsing is correct here. From the syntax in the [Maven docs](http://maven.apache.org/pom.html#Maven_Coordinates) I'd suggest:

```
@@ -144,11 +144,13 @@ class Artifact(object):
             ArtifactError(None, "invalid Maven coordinates: %s" % input)
         g, a, v, c, t = parts[0], parts[1], None, None, None
         if len(parts) >= 3:
-            v = parts[-1]
+            v = parts[2]
         if len(parts) >= 4:
             t = parts[2]
+            v = parts[3]
         if len(parts) >= 5:
             c = parts[3]
+            v = parts[4]
         return Artifact(g, a, v, c, t)
```

This would interpret `name` as:
- `g:a`
- `g:a:v`
- `g:a:t:v`
- `g:a:t:c:v`

**Comment by jirutka** [comment]
It is correct, the result should be the same as yours. `parts[-1]` selects the last item of the array and as you see in Maven docs, version number is always the last item (if present).

**Comment by markhobson** [comment]
You're right, apologies for the noise. Might be worth detailing the various artifact coordinate syntaxes in the docs as it's not immediately obvious.

**Comment by willthames** [comment]
A minor nit, but should this be in packaging rather than networking?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by jirutka** [comment]
@srvg FYI, I’ve added support for HTTP Basic authentication in https://github.com/ansible/ansible-modules-extras/pull/243.

**Pull request closed without merging**
