### PR TITLE
Add rax_network module

### PR DESCRIPTION
**Pull request by claco**
Based on the refactor work @sivel is doing, adding a rax_network module
to create/delete networks in the Rackspace Public Cloud.

See: https://github.com/ansible/ansible/issues/4577

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!  This looks good to me.

@sivel are you ok with this given other attempts to standardize Rackspace module things?   Something we are doing with other cloud modules is looking to make sure authentication is the same across all of them, so wanted to get your review.

as a oneminor code thing, I always prefer

   {'id': network.id,
-                    'label': network.label,
-                    'cidr': network.cidr} 

be written more simply as:

```
dict(
   id =network.id,
   label = network.label,
   cidr = network.cidr
)
```

Which prevents the same from cargo-culting over to other files.

Also, I think we should remove "state=deleted" as it's redundant with absent, but that's all I see at basic review.

Do the examples need to show how this might be used to together with the standard rax module to leverage the network?  (Or perhaps we want to start the rackspace guide for the guides section of the docs?)

Thanks very much, glad to see these modules expanding!

**Comment by claco** [comment]
Yeah, it's kind of intertwined in this: https://github.com/ansible/ansible/issues/4577#issuecomment-26652250

I'm assuming the when the rax module gets refactored, it will actually take network ids. :-)

**Comment by sivel** [comment]
Here are a few things I'd like to see:
1. The return from the module should have a key/attribute of `networks` instead of `instances`.
2. Instead of using `\` for line continuations, the lines should be wrapped in `()`
3. Remove state 'deleted'

Other than that I think it looks good.

The auth code is a match for what it was pre refactor, and there have only been slight changes.

In general I think we should hold off on merging this to wait for the refactor, which is getting close, assuming it pleases everyone.

I think a quick example how to use it with the rax module is a good idea.

**Comment by mpdehaan** [comment]
@sivel -- +1 on your end?

I think we should definitely start (I've mentioned this) a rax guide alongside the Amazon one, and in that case that might be the best place to put the dovetailed example.

I'm ok with it starting slowly so maybe we do that now and just show how to use inventory, the provisioning module, and networking?

**Comment by sivel** [comment]
@mpdehaan I'm good with this.  LGTM.

As far as the rax guide, I'll start that shortly.

**Comment by jctanner** [comment]
@sivel and @claco thank you!

**Comment by claco** [comment]
@sivel Much like https://github.com/ansible/ansible/pull/4864

Should I change the type: in this module to network_type?

**Comment by sivel** [comment]
I believe that publicly it should be exposed as "type" if it makes sense.  Internally, it should be addressed with a more appropriate name.  In my work on CBS stuff, externally it is exposed as "type", internally it is referenced as "volume_type".

Just my 2 cents.  My previous reference was to not use variable names that override that of built in function names within python.  The module/yaml attributes don't concern me as much, and should just use what makes the most sense.

In general I don't like seeing variables within python named things like "type", "file", "json" as it can be confusing to someone who expects those to be python builtins or standard python modules.

**Pull request merged**
