### PR TITLE
Add AzureRMStorageAccount StorageV2 kind backport

### LINKED ISSUE #38455: azure_rm_storageaccount module doesn't support new recommended 'kind' of storage in Azure
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_storageaccount

##### ANSIBLE VERSION
I'm using ansible 2.4.3.0, but I checked the devel branch and StorageV2 kind is not available there either.
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/<redacted>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
azure_rm_storageaccount module doesn't support new 'kind' of storage account provided by Azure. 

The old one was renamed from 'Storage' to 'StorageV1' and a new kind 'StorageV2' was introduced. V2 is recommended by Microsoft to be used instead of V1. At the moment ansible creates StorageV1 kind when 'Storage' is specified in 'kind:' attribute and the storage account needs to be upgraded to V2 using Azure CLI as described on https://docs.microsoft.com/en-us/azure/storage/common/storage-account-options

##### STEPS TO REPRODUCE
Create a storage account in Azure using
```yaml
azure_rm_storageaccount:
  name: 'MyStorage'
  resource_group: 'MyRG'
  type: 'Standard_LRS'
  kind: 'StorageV2'
```

##### EXPECTED RESULTS
Storage account creation succeeds and the 'Account kind' in Azure Portal account overview shows 
```
Account kind:
StorageV2 (general purpose v2)
```

##### ACTUAL RESULTS
Account creation ends with the following error:
```
<...> "msg": "value of kind must be one of: Storage,BlobStorage, got: StorageV2"
```

### PR DESCRIPTION
**Pull request by robsonpeixoto**
(cherry picked from commit 2796be1132d7a1ace13e055c0c56b54f61e3949c)

close #38455

### CODE REVIEW

**Comment by yuwzho** [comment]
@mattclay

**Comment by Fred-sun** [comment]
@mattclay Could you help take a look this PR? Thanks!

**Comment by Fred-sun** [comment]
@robsonpeixoto Thanks for the contribution, Could you help confirm this PR ready for review or not? Thanks!

**Comment by Fred-sun** [comment]
@mattclay Could you help take a look this PR? Thanks!

**Comment by robsonpeixoto** [comment]
The PR is ready for review, @Fred-sun

**Comment by Fred-sun** [comment]
@robsonpeixoto Thanks for the contribute, I will test and push to review. Thanks!

**Comment by Fred-sun** [comment]
@yuwzho @mattclay Could you help to review this PR? Thanks!

**Comment by robsonpeixoto** [comment]
@Fred-sun it's only a backport of this commit https://github.com/ansible/ansible/commit/2796be1132d7a1ace13e055c0c56b54f61e3949c

**Comment by Fred-sun** [comment]
@yuwzho @mattclay Could you help to review this PR and push to next step forward? Thanks!

**Pull request merged**
