### PR TITLE
VMware: change type of state in vmware_host_ipv6

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_host_ipv6.py

##### ANSIBLE VERSION

```paste below
2.8-devel
```

### CODE REVIEW

**Comment by ckotte** [comment]
@Akasurde Shouldn't you replace type with `type: str` instead of deleting it entirely?

**Comment by pdellaert** [comment]
@ckotte , as other strings do not require the type, i think we can just safely remove it

**Review by pdellaert — APPROVED** [review]
LGTM

**Comment by ckotte** [comment]
@Akasurde @pdellaert 
> @ckotte , as other strings do not require the type, i think we can just safely remove it

Looks like the core team want the type for all options: https://github.com/ansible/ansible/pull/47271#discussion_r226381898.

**Pull request merged**
