### PR TITLE
postgresql_query: fix UTF-8 support in SQL files

### LINKED ISSUE #65367: postgresql_query doesn't support non-ASCII characters in SQL files with Python3
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/roman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Local:

```
NAME=Fedora
VERSION="31 (Workstation Edition)"
```

Remote:
```
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
```

All managed hosts are RHEL 8 (Python3 only):

hosts.yml:
```
all:
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
```

##### STEPS TO REPRODUCE

main.yml:

```yaml
- name: "Copy files with scheme"
  copy:
    src: "scheme.sql"
    dest: "/tmp/scheme.sql"
    mode: '0600'

- name: "Create scheme"
  postgresql_query:
    login_user: "{{ postgresql_user }}"
    login_password: "{{ postgresql_password }}"
    login_host: "{{ postgresql_host }}"
    db: "{{ postgresql_database }}"
    path_to_script: "/tmp/scheme.sql"
```

scheme.sql:
```
INSERT INTO test(id, name) VALUES(1,  'Данные'); -- use non-ASCII
```

##### EXPECTED RESULTS

scheme.sql applied.

##### ACTUAL RESULTS

```paste below
"msg": "Cannot read file '/tmp/scheme.sql' : 'ascii ' codec can't decode byte 0xd0 in position 4342: ordinal not in range(128)"}  
```

### PR DESCRIPTION
**Pull request by rtsisyk**
##### SUMMARY
    
Fix UTF-8 support when reading of `path_to_file` argument on Python 3.

Fixes #65367

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

postgresql_query

##### ADDITIONAL INFORMATION

See  #65367

### CODE REVIEW

**Review by Andersson007 — CHANGES_REQUESTED** [review]
@rtsisyk hey! Thank you for the fix!
We need two more things:
1. Changelog fragment, see [here](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs).
You can find examples in ```changelogs/fragments/``` of the source tree
2. CI tests, see the existing tests there ```test/integration/targets/postgresql_query/tasks/```. Just add yours analogically

Waiting for you feedback!

**Comment by rtsisyk** [comment]
OK, I will add tests and update the changelog!

**Comment by Andersson007** [comment]
@rtsisyk hey, hope you're well? :)
if there are some problems or you just have no time to complete this, i could do it, no problem

**Comment by Andersson007** [comment]
@rtsisyk i can't reproduce the situation.. i used a query containing "SELECT * FROM blabla WHEN story = 'Данные'" and it doesn't fail

**Comment by Andersson007** [comment]
probably it is because of python 2

**Comment by Andersson007** [comment]
close_me

**Pull request closed without merging**
