### PR TITLE
Better OpenStack Cloud Support

### PR DESCRIPTION
**Pull request by tnoff**
Example's here:
https://github.com/tylernorth/ansible-openstack-playbooks

### CODE REVIEW

**Comment by mpdehaan** [comment]
This is going to suck, but these submitted together present a bit of a review conundrum.  Would you mind stopping by ansible-devel to discuss in a larger forum?

Much appreciated!

**Comment by tnoff** [comment]
@mpdehaan Yeah no problem! What do you mean stop by ansible-devel?

**Comment by mpdehaan** [comment]
ansible-devel is our development mailing list and google group.  

https://groups.google.com/forum/#!forum/ansible-devel

**Comment by tnoff** [comment]
https://groups.google.com/forum/#!topic/ansible-devel/QcmPDonY0iA

**Comment by tnoff** [comment]
Closing to break up into smaller commits

**Pull request closed without merging**
