### PR TITLE
VMware: vmware inventory enhancements

### LINKED ISSUE #54339: VMware: VMware inventory plugin group by Folder
##### SUMMARY
Currently the vmware inventory plugin groups all virtual machines by operating system, which is most of the time useless for enterprise environments or for cloud providers with multiple tenants.
Therefore an additional option for the `vmware.yaml` that allows to group by folder/resource group/attribute/vm-name-prefix would be very helpful.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_vm_inventory

### LINKED ISSUE #55135: vmware dynamic inventory naming collision
##### SUMMARY
Possible name collision within the vmware dynamic inventory plugin

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/plugins/inventory/vmware_vm_inventory.py

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Private/ansible-1/lib/ansible
  executable location = /home/user/Private/ansible-1/bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

VMware vCenter
ArchLinux

##### STEPS TO REPRODUCE

Currently the inventory name is the vmname concatenated with it's uuid. But neither the name nor the uuid is guaranteed to be unique (both can be set arbitrarily). The only thing that is unique, is the full folder path including the vm name. Within a single folder, it is not allowed (and not possible) to have two vms with identical name.
Also special chars are not escaped properly. VMware allows any character within vm names, folder names, ... This causes even trouble within VMwares own PowerCLI api (the powershell one)

##### ADDITIONAL RESSOURCES
https://pubs.vmware.com/esx254/admin/wwhelp/wwhimpl/common/html/wwhelp.htm?context=admin&file=esx25admin_vms.4.27.html
https://kb.vmware.com/s/article/1002403
https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.ConfigInfo.html
https://kb.vmware.com/s/article/1541

https://www.vmware.com/support/orchestrator/doc/vco_vsphere55_api/html/VcVirtualMachineConfigInfo.html here look at the description of instanceUuid, it says:
> including those that may share the same SMBIOS UUID

##### ALTERNATIVE IMPLEMENTATION
switch .uuid to .instanceUuid, that is unique, but does not provide any meaningful information to human readers.

### LINKED ISSUE #66042: vmware_vm_inventory - Not working for a single vCenter
##### SUMMARY
When trying to use vmware_vm_inventory to pull in a dynamic inventory, it works on 3 out of 4 vCenters that are configured the same way.  There is room for human error, but all vcenters are configured by way of powershell scripts.  I have verified the same user account and vcenter permissions for all 4 vcenters.  I just want to see if anyone else has seen this or could give some insight of what to look for.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_vm_inventory

##### ANSIBLE VERSION
```paste below
ansible 2.9.1
  config file = /opt/ansible_code/scripts/inventory-vmware/ansible.cfg
  configured module search path = [u'/home/svc_ops_lnx_ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/ansible-2.9.1-pyvmomi/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```ini
HOST_KEY_CHECKING(/opt/ansible_code/scripts/inventory-vmware/ansible.cfg) = False
INVENTORY_ENABLED(/opt/ansible_code/scripts/inventory-vmware/ansible.cfg) = [u'vmware_vm_inventory']
```

##### OS / ENVIRONMENT

OS: CentOS 7.6.1810
VMware vCenter Version: 6.7.0.30000

##### STEPS TO REPRODUCE
The issue can be reproduced by issuing the following command, however, this is only happening on a single vCenter.  Same user account, same vCenter version, and same permissions across the board have been verified, however, on this one vcenter, it failes with:
```
[WARNING]:  * Failed to parse /opt/ansible_code/scripts/inventory-vmware/plugin-vcenter01.vmware.yml with vmware_vm_inventory plugin: 429 Client Error: Too Many
Requests for url: https://vcenter01/api

  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/ansible/plugins/inventory/vmware_vm_inventory.py", line 359, in parse
    cacheable_results = self._populate_from_source(source_data, using_current_cache)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/ansible/plugins/inventory/vmware_vm_inventory.py", line 430, in _populate_from_source
    attached_tags = tag_association.list_attached_tags(vm_dynamic_id)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/com/vmware/cis/tagging_client.py", line 1412, in list_attached_tags
    'object_id': object_id,
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 266, in native_invoke
    method_result = self.invoke(ctx, method_id, data_val)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 202, in invoke
    ctx)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/vmware/vapi/security/client/security_context_filter.py", line 102, in invoke
    self, service_id, operation_id, input_value, ctx)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/vmware/vapi/provider/filter.py", line 76, in invoke
    service_id, operation_id, input_value, ctx)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 79, in invoke
    response = self._do_request(VAPI_INVOKE, ctx, params)
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 127, in _do_request
    http_response.data.raise_for_status()
  File "/opt/ansible/ansible-2.9.1-pyvmomi/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

[WARNING]: Unable to parse /opt/ansible_code/scripts/inventory-vmware/plugin-vcenter01.vmware.yml as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available
```

This is the command to actually reproduce the issue:
```yaml
ansible-inventory -i plugin-vcenter01.vmware.yml --list --export -y --output inventory-vmware_vcenter01.yml --vault-password-file=vault_password_file -vvvv
```

##### EXPECTED RESULTS
An inventory file in yaml to be created 

##### ACTUAL RESULTS
Incomplete inventory is created: 

```yaml
all:
  children:
    ungrouped: {}
```

### LINKED ISSUE #66767: Groups in vmware_vm_inventory plugin don't work
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_vm_inventory

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /datas/ansible/logs/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/datas/ansible/roles']
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'vmware_vm_inventory']

```

##### OS / ENVIRONMENT

CentOS 7.5

##### STEPS TO REPRODUCE

```yaml
plugin: vmware_vm_inventory
strict: false
hostname: 'vsrv-vc-dmz'
username: 'login'
password: 'password'
validate_certs: false
groups:
  cluster_dmz: true
properties:
- 'name'
- 'guest.ipAddress'
- 'guest.hostName'
with_tags: true

```

##### EXPECTED RESULTS

Create a group name cluster_dmz with all host from that inventory in.

##### ACTUAL RESULTS

```paste below
no group created with:
ansible-inventory -i inv_dmz.vmware.yml --graph
```

### PR DESCRIPTION
**Pull request by dacrystal**
##### SUMMARY
This pull request added a number of important features to vmware_vm_inventory plugin.
- [x] **[feat]** Allowed encrypted username/password. Until #67823 is merged.
- [x] **[feat]** Allowed `properties` to accept any path level (e.g `config`)
- [x] **[feat]** Property option can be set to value of ‘all’. To query all VM properties.
- [x] **[feat]** Added `hostnames`. To make `inventory_hostname` configurable. #55137, Fixes #55135, #63939
- [x] **[feat]** Added `with_sanitized_property_name`. To sanitized property name and transform it to snake case for better templating.
- [x] **[feat]** Added `with_nested_properties`. To transform properties to nested dictionary.
- [x] **[feat]** Added `with_path` option. To support group by path hierarchy. Related #52782 #55576, - Fixes #54339, #54339
- [x] **[feat]** Added Contractable options. Fixes #66767, #65678, #66411
- [x] **[perf]** Improved properties query performance. Fixes #66042, #56786
- [x] **[refactor]** Refactored cache code.
- [x] **[bug]** Fixed `_login_vapi` that make fail for vcsim.
- [x] **[test][refactor]** Refactored `inventory_vmware_vm_inventory` test target.
- [x] **[test][feat]** Added a number of test cases. 
- [x] **[test][bug]** Fixed bug where ansible-test with —debug fail 
- [ ] Set defaults values of `options` that follow ansible standard/best practices. currently, are set for compatibility with 2.9.

Related pull request: 
- #55576, #52782, #55137;

Fixes:
- #55135, #63939; `hostnames` option 
- #54339; `with_path` option 
- #66767; `groups` option 
- #65678; `compose` option
- #66411; `keyed_groups` option
- #66042, #56786; (possibly); due to improved properties query performance

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/vmware_vm_inventory.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@dacrystal Thanks for the contribution. As you may be knowing that VMware modules and plugins are no longer reside in ansible/ansible repo and VMware collection is created [here](https://github.com/ansible-collections/vmware). All further development of VMware plugins and modules will be done in ansible-collection/vmware repo. 

Would you please raise this PR against https://github.com/ansible-collections/vmware repo. 

Let me know.

**Comment by dacrystal** [comment]
@Akasurde Sure, I will PR against ansible-collection/vmware repo

**Comment by AlanCoding** [comment]
this is going to conflict hard with some stuff I already merged into the collection, please `@` my username so I can have a look when it's moved there. Thanks

**Comment by dacrystal** [comment]
@AlanCoding sure I'll mention you. My plan is to merge this PR code on top of ansible-collection/vmware and ensure all functionally are met.

Also this PR fixes the serialization issue you mentioned in (ansible-collections/vmware/pull/58) including YAML and TOML. So I'm not expecting a major conflict in terms of functionality. It have been tested with every possible properties using ( **properties: ALL** ).

**Comment by dacrystal** [comment]
Moved to  ansible-collections/vmware#80

**Pull request closed without merging**
