### PR TITLE
add state absent/present to action template

### LINKED ISSUE #29781: template and copy modules should have state parameter
From @Vladimir-csp on 2016-06-12T09:45:24Z
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

copy
template
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

As was suggested in https://github.com/ansible/ansible/issues/6929, I am opening new issue on this matter
Please add 'state' parameter for template and copy modules, so items could be removed with the same task by using condition or variable override.
##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

Something like this should be possible

```
- name: govern foo template
  template: src=foo dest=/etc/foo state="{% if enable_foo == true %}present{% else %}absent{% endif%}"
```

On second thought, file, copy, and template modules could be merged together into file module to make some cool things like:

```
- name: linked template
  file: template=foo.conf state=link src=../bar/bar.conf dest=/etc/foo/foo.conf
# makes link /etc/foo/foo.conf > /etc/bar/bar.conf,
# templates  /etc/foo/foo.conf  from foo.conf effectively writing to  /etc/bar/bar.conf.
```
##### ACTUAL RESULTS

```

```

Copied from original issue: ansible/ansible-modules-core#3934

### PR DESCRIPTION
**Pull request by tchernomax**
##### SUMMARY

add 'state' parameter to template action module.

semi fix https://github.com/ansible/ansible/issues/29781

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

template action module

### CODE REVIEW

**Comment by tchernomax** [comment]
ready_for_review

I don't think tests fail because of my changes. Can someone confirm or/and relaunch the tests ?

**Comment by tchernomax** [comment]
ready_for_review

**Comment by sivel** [comment]
We have previously discussed that we do not want state functionality in the template module. Instead using the file module should be used to remove a file.

Duplicate of https://github.com/ansible/ansible/issues/68842

**Comment by tchernomax** [comment]
```
tchernomax   I would like to know why exactly "we do not want state functionality in the template module"
and if I can make you change your mind

bcoca	you can try, the main reason is that we don't think it belongs there nor in copy, thoese modules have a very specific purpose and removing files is not one of them, that is what the file module is for
otherwise why are not ALL modules that create/modify/manipulate a file providing this also?

sdoran	We suffer from a number of "kitchen sink" modules that do too much and supporting them over time is problematic as they have become quite complex.
We prefer modules that do a small set of things very well and focus on that.
```

**Comment by jamescassell** [comment]
FWIW, I'd find this useful, to allow "install/uninstall" w/ the same set of tasks, but opposite state for each module involved... works for many other modules.

But perhaps such tasks are better delegated to the package manager.

**Pull request closed without merging**
