### PR TITLE
[2.8] Move idrac_* modules one level up

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #59698 to stable-2.8. This fixes that the modules do not show up in the index (https://docs.ansible.com/ansible/latest/modules/list_of_remote_management_modules.html#dellemc), since they are one level too far down.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
idrac_firmware
idrac_server_config_profile

### CODE REVIEW

**Comment by felixfontein** [comment]
This PR doesn't add new modules, it just moves module files. ansibot just gets a bit confused by this :)

**Comment by rajeevarakkal** [comment]
we are good with this

**Comment by abadger** [comment]
Merged for the 2.8.4 release.

**Comment by felixfontein** [comment]
Thanks everyone!

**Pull request merged**
