### PR TITLE
gcp: documentation update

### LINKED ISSUE #44404: gcp_compute plugin does not work
##### SUMMARY
gcp_compute plugin does not work. always an error that no matching inventory plugin is working

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gcp_compute

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /Users/jesusch/.ansible.cfg
  configured module search path = [u'/Users/jesusch/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION
DEFAULT_HOST_LIST(/Users/jesusch/.ansible.cfg) = [u'/Users/jesusch/ansible/inventory']
DEFAULT_ROLES_PATH(/Users/jesusch/.ansible.cfg) = [u'/Users/jesusch/ansible/roles']
HOST_KEY_CHECKING(/Users/jesusch/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/jesusch/.ansible.cfg) = False

##### OS / ENVIRONMENT
Darwin Bjorns-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

##### STEPS TO REPRODUCE
Configured GCP plugin as described in https://docs.ansible.com/ansible/2.6/scenario_guides/guide_gce.html

```yaml
---
plugin: gcp_compute
projects:
  - google.com:myProject-1337
filters: null
auth_kind: serviceaccount
service_account_file: /Users/jesusch/Downloads/myProject-1337-somehash.json
```

##### EXPECTED RESULTS
ansible-inventory --list -i inventory/myproject.gcp.yml should list my GC hosts and its metadata

##### ACTUAL RESULTS
```
ANSIBLE_DEBUG=1 ansible-inventory --list -i inventory/myproject.gcp.yml
 40804 1534774235.58981: starting run
 40804 1534774235.68904: Added group all to inventory
 40804 1534774235.68913: Added group ungrouped to inventory
 40804 1534774235.68919: Group all now contains ungrouped
 40804 1534774235.70007: Loading InventoryModule 'host_list' from /usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/host_list.py
 40804 1534774235.70106: assigned :doc
 40804 1534774235.70117: assigned :plainexamples
 40804 1534774235.70164: Loading InventoryModule 'script' from /usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/script.py
 40804 1534774235.70398: assigned :doc
 40804 1534774235.70418: Loaded config def from plugin (inventory/script)
 40804 1534774235.70446: Loading InventoryModule 'yaml' from /usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/yaml.py
 40804 1534774235.70576: assigned :doc
 40804 1534774235.70584: assigned :plainexamples
 40804 1534774235.70603: Loaded config def from plugin (inventory/yaml)
 40804 1534774235.70668: Loading InventoryModule 'ini' from /usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py
 40804 1534774235.70865: assigned :doc
 40804 1534774235.70874: assigned :plainexamples
 40804 1534774235.70911: Loading InventoryModule 'auto' from /usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/auto.py
 40804 1534774235.70965: assigned :doc
 40804 1534774235.70971: assigned :plainexamples
 40804 1534774235.70984: Examining possible inventory source: /Users/jesusch/git/ansible/inventory/myproject.gcp.yml
 40804 1534774235.70992: Attempting to use plugin host_list (/usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/host_list.py)
 40804 1534774235.70998: /Users/jesusch/git/ansible/inventory/myproject.gcp.yml did not meet host_list requirements
 40804 1534774235.71004: Attempting to use plugin script (/usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/script.py)
 40804 1534774235.71764: /Users/jesusch/git/ansible/inventory/myproject.gcp.yml was not parsable by script
 40804 1534774235.71790: Attempting to use plugin yaml (/usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/yaml.py)
 40804 1534774235.72000: Loading data from /Users/jesusch/git/ansible/inventory/myproject.gcp.yml
 40804 1534774235.72153: /Users/jesusch/git/ansible/inventory/myproject.gcp.yml was not parsable by yaml
 40804 1534774235.72162: Attempting to use plugin ini (/usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py)
 40804 1534774235.72316: set inventory_file for ---
 40804 1534774235.72330: set inventory_dir for ---
 40804 1534774235.72335: Added host --- to inventory
 40804 1534774235.72343: Added host --- to group ungrouped
 40804 1534774235.72386: /Users/jesusch/git/ansible/inventory/myproject.gcp.yml was not parsable by ini
 40804 1534774235.72393: Attempting to use plugin auto (/usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/auto.py)
 40804 1534774235.72421: Loading data from /Users/jesusch/git/ansible/inventory/myproject.gcp.yml
 40804 1534774235.77925: Loading InventoryModule 'gcp_compute' from /usr/local/lib/python2.7/site-packages/ansible/plugins/inventory/gcp_compute.py
 40804 1534774235.79347: assigned :doc
 40804 1534774235.79357: assigned :plainexamples
 40804 1534774235.79887: Loading ModuleDocFragment 'constructed' from /usr/local/lib/python2.7/site-packages/ansible/utils/module_docs_fragments/constructed.py
 40804 1534774235.79947: Loading ModuleDocFragment 'inventory_cache' from /usr/local/lib/python2.7/site-packages/ansible/utils/module_docs_fragments/inventory_cache.py
 40804 1534774235.80017: Loaded config def from plugin (inventory/gcp_compute)
 40804 1534774235.80042: Loading data from /Users/jesusch/git/ansible/inventory/myproject.gcp.yml
 40804 1534774236.20005: auto failed to parse /Users/jesusch/git/ansible/inventory/myproject.gcp.yml
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* Update example about dynamic inventory
* minor typo fixes in gcp_utils
* Additional information about enabling inventory plugin in ansible.cfg

partially fixes: #44404

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/scenario_guides/guide_gce.rst
lib/ansible/module_utils/gcp_utils.py

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @rambleraptor

**Review by chad-autry — APPROVED** [review]
Looks good for the issues you're attempting to address. I'd approve the changes going in.

To continue on with possible issues around the page as a whole, I believe there is an additional omission that authorizing the plugin does not authorize SSH to the instances. You still need to manage ssh keys somehow, which I've actually found quite difficult with GCE. In particular the final lines of the page "Note that use of the “add_host” module above creates a temporary, in-memory group. This means that a play in the same playbook can then manage machines in the ‘new_instances’ group, if so desired." implies to me that you should just be able to start running any module against the machine, when in fact I'm fairly sure you can't (Note: I've never tried creating instances with Ansible, just managing manually created instances)

**Review by samccann — APPROVED** [review]
fixed one little nit.

**Comment by ppuschmann** [comment]
Hi @samccann , hi @chad-autry ,

this documentation-update is also needed on Ansible 2.7.x.
How can we bring the updates to the live webpage?

**Pull request merged**
