### PR TITLE
Shortens Scenario Guides, incorporates vmware guide

### PR DESCRIPTION
**Pull request by acozine**
##### SUMMARY
Supersedes #53569.

Divides the Scenario Guides into 3 groups: cloud, network, and virtualization/containerization.
Incorporates VMware content into Scenario Guides section.
Removes unused VMware pages from the VMware guide.
Updates main TOC and left nav bar for cleaner navigation.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs.ansible.com: vmware guide, other Scenario Guides (for cloud platforms, network technologies, and virtualization/containerization solutions).

### CODE REVIEW

**Review by gundalow — COMMENTED** [review]
1) Will need http://docs.testing.ansible.com/ansible/latest/scenario_guides/ to redirect to http://docs.testing.ansible.com/ansible/latest/scenario_guides/guides.html
As we don't have an `index.rst` in there

**Review by gundalow — APPROVED** [review]
Looks good. Once this has been merged please remind me to update `BOTMETA.yml`

**Comment by acozine** [comment]
Temporarily published to http://docs.testing.ansible.com/ansible/latest/index.html

**Comment by acozine** [comment]
@gundalow hmmm, we don't have a page called `index.html` for the scenario guides section now. I retained the `guides.html` page in this PR because that page exists now (https://docs.ansible.com/ansible/latest/scenario_guides/guides.html), so keeping it will help with version-switching. 

I don't know how hits the `guides.html` page gets now. To navigate to the missing `index.html` page now, you have to type in the URL.

**Comment by gundalow** [comment]
I don't think we need `index.html`, a server side redirect to `guides.html` should be fine

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
After merging we need to update `BOTMETA` to add labels to the VMware section

**Pull request merged**
