### PR TITLE
plugins/test/: PEP8 compliancy

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
- Make PEP8 compliant

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

plugins/test/

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by dagwieers** [comment]
Shippable git errors. Close and re-open.

**Comment by dagwieers** [comment]
Close and re-open failed to trigger Shippable. Trying it again.

**Comment by dagwieers** [comment]
@gundalow Can you rerun Shippable, closing and re-opening seems to fail to redo Shippable run in this weird case.

**Comment by gundalow** [comment]
Shippable has been retriggered

**Pull request closed without merging**
