### PR TITLE
ec2_vol: name_tag option added which can set Name tag

### PR DESCRIPTION
**Pull request by berenddeboer**
I see this branch pulled in my FreeBSD portinstall as well, apologies!! Please only get the ec2_vol change from this.

Obviously it would be nice if you could set random tags, but I'm not comfortable enough with Python to write that quickly. But setting the Name tag is already very useful I think.

### CODE REVIEW

**Comment by lwade** [comment]
I see no issue with merging the ec2_vol changes (with a PR re-submission I expect, minus the other bits), this will be useful until we have tag-based idempotency for the module.  When we have the latter, the implementation is likely to change.

**Comment by berenddeboer** [comment]
Indeed, this is a temporary fix until full tagging works. But this at least lets me find my disks.

**Comment by berenddeboer** [comment]
BTW, what do you mean with: "with a PR re-submission I expect, minus the other bits".

Is that something I should do?

**Comment by mpdehaan** [comment]
@lwade can you follow up on this one?

Thanks!

**Comment by mpdehaan** [comment]
Misread this earlier 

@berenddeboer -- 

Yes, we need just the part resubmitted that is related to the topic.

Thanks!

**Pull request closed without merging**
