### PR TITLE
Update github url

### PR DESCRIPTION
**Pull request by blindphaze**
Replace git@github.com:ansible/ansible.git with https://github.com/ansible/ansible.git for working checkouts

### CODE REVIEW

**Comment by bcoca** [comment]
any reason on the protocol change?

**Comment by blindphaze** [comment]
Unless I am confused on how ssh would work on github for cloning (I am assuming you would have to allow my ssh key in order for me to access the files over ssh).  It is due to the following:

$ git clone git@github.com:ansible/ansible.git --recursive
Cloning into 'ansible'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bcoca** [comment]
You just need a key in your github account (also required to create pull requests), we would only need to allow it in the ansible account for writes.

**Comment by blindphaze** [comment]
Heh, well now I feel like an idiot.  Sorry about the wasted time!

**Pull request closed without merging**
