### PR TITLE
Auto inclusion of vaulted files in group_vars and host_vars

### PR DESCRIPTION
**Pull request by ponysmith**
Adds vaulted files to the autoloaded files in `group_vars` and `host_vars`.  Files follow the naming conventions `<hostname>.vault.yml` for vault files in `host_vars` and `<groupname>.vault.yml` for vault files in `group_vars`.

### CODE REVIEW

**Comment by bcoca** [comment]
im not sure this is needed, you can already keep vaulted files in group/host vars and they will automatically be loaded, you can put multiple files in a <groupname or hostname>/ directory, with plain yaml and vaulted side by side.

**Comment by sivel** [comment]
I agree with @bcoca the fact that inside of `host_vars` and `group_vars` you can have directories with the names of hosts or groups that can then hold multiple YAML files including vaulted files makes this already possible.

**Comment by abadger** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:
- Using directories for your host_vars and group_vars you can already do the same thing that this Pull Request implements.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by ponysmith** [comment]
Hi @abadger ... thanks for the response.  I guess I was unaware of how to accomplish this with the current usage of the host_vars and group_vars directories.  I'll post to the google group and see what solutions people have.

**Pull request closed without merging**
