### PR TITLE
Remove check for commercial types in scaleway_compute

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

Instances types are not static and new ones are going to be added to scaleway_compute
In addition suggestions for fixing typo errors might be available in the payload of a reply in case of error

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

scaleway_compute

### CODE REVIEW

**Comment by sieben** [comment]
@pilou- Could you review?

**Comment by sieben** [comment]
@Anthony25 @abarbare Could you review and ship if it looks good?

**Comment by Anthony25** [comment]
LGTM

**Comment by abarbare** [comment]
ship it

**Comment by resmo** [comment]
@abarbare please use it in one word "shipit" and on a single line

shipit

**Pull request merged**
