### PR TITLE
Module for setting/changing timezone config

### PR DESCRIPTION
**Pull request by ex-nerd**
Module for manipulating /etc/localtime

### CODE REVIEW

**Comment by sivel** [comment]
The scope seems a bit limited here, and likely may result in issues later.  For example on RHEL, if you simply update /etc/localtime without updating /etc/sysconfig/clock, when gcc or tzdata is updated, the timezone will be reverted to the value in /etc/sysconfig/clock.  I imagine that Debian based distors may suffer from a similar issue if /etc/timezone is not updated

I think this should extend past simply updating /etc/timezone and also update the underlying files used by the system in determining the timezone during update scenarios.

I might also add some sort of warning about using symlinks.  If you use a symlink and /usr is on a separate partition, the timezone won't be available during boot time.  Historically, it was recommended that symlinks not be used here.  However newer systems, such as those that use systemd, cannot boot with /usr on a separate partition.

**Comment by ex-nerd** [comment]
Sounds good.  I'll poke around a bit more.  Anyone happen to know if the BSD family has anything similar, and/or what the specifics are for Debian-based linux?

**Comment by sivel** [comment]
As far as Debian based (Ubuntu in this case), we perform the following in tasks currently:

```
- name: Update /etc/timezone
  copy:
    content: |
      America/Chicago

    dest: /etc/timezone
    group: root
    owner: root
    mode: 0644

- name: Reconfigure tzdata
  command: dpkg-reconfigure -f noninteractive tzdata
```

That second task is actually a handler, but simplified for pasting here.  I can't help much with BSD.

**Comment by ex-nerd** [comment]
Looking at the hostname plugin as an example, it looks like I have a bit of rewriting to do to make this thing properly compliant with ansible cross-distro standards.  I wish this stuff was better-documented.  I'll re-submit when things are cleaned up better.

**Pull request closed without merging**
