### PR TITLE
rename azure _facts module to _info module

### PR DESCRIPTION
**Pull request by yungezz**
##### SUMMARY

rename azure _facts module to _info module
- azure_rm_applicationsecuritygroup_facts.py
- azure_rm_virtualnetworkpeering_facts.py
- azure_rm_webapp_facts.py

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@yungezz There is a conflict file in this PR, please help to solve it when you are free. Thank you very much!

**Comment by felixfontein** [comment]
You might want to include something like
```.py
    if module._name == 'azure_rm_applicationsecuritygroup_facts':
        module.deprecate("The 'azure_rm_applicationsecuritygroup_facts' module has been renamed to 'azure_rm_applicationsecuritygroup_info'", version='2.13')
```
in the renamed modules' code, so that the user is informed that they have to adjust the module's name.

Also, you should adjust the names of the module in the tests. The `azure_rm_networkinterface` integration tests still use `azure_rm_applicationsecuritygroup_facts`, for example.

(Finally: ansibot treats module rename PRs incorrectly as new module PRs. You can ignore the resulting errors/warnings because of multiple new PRs. Such PRs need to be merged manually, though.)

**Comment by zikalino** [comment]
@felixfontein thanks for reminding and info :-)
we plan to rename all the modules before Ansible 2.9

**Comment by MyronFanQiu** [comment]
@yungezz There is a conflict file in this PR, please help to solve it when you are free. Thank you very much!

**Comment by Fred-sun** [comment]
@yungezz

**Comment by felixfontein** [comment]
You have to update the module name in test/sanity/validate-modules/ignore.txt as well, that should remove all sanity check errors.

**Comment by MyronFanQiu** [comment]
@felixfontein Thanks!

**Comment by MyronFanQiu** [comment]
@yungezz The CI is fixed except for an unstable error of the `azure_rm_mysqlserver`. In the previous CI test, this task passed. So just close-reopen this issue could solve the CI.

**Comment by felixfontein** [comment]
I restarted the failed CI run, close-reopen shouldn't be necessary.

Please also note my first comment here: https://github.com/ansible/ansible/pull/56502#issuecomment-498111856

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz The PR show exist conflicts, but I don't see the cause of the conflict. Could you take a look this and promote to merge? Thank you very much!

**Comment by felixfontein** [comment]
I think this can now be closed, since all `_facts` modules have been renamed?

**Comment by Fred-sun** [comment]
@yungezz   Ping to close! Thanks a lot!

**Pull request closed without merging**
