### PR TITLE
Bump antsibull-docs version in docs-build sanity test

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Also update all dependencies to the latest versions.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
docs-build sanity test

### CODE REVIEW

**Comment by felixfontein** [comment]
Next to a markup processing code refactoring this adds support for semantic markup for roles. (#80305 adds semantic markup role support to ansible-doc.)

**Comment by samccann** [comment]
Verified on test - http://docs.testing.ansible.com/ansible/devel/collections/sensu/sensu_go/agent_role.html#ansible-collections-sensu-sensu-go-agent-role
...of course nothing is using the role semantic markup yet :-)

**Review by samccann — APPROVED** [review]

**Comment by mattclay** [comment]
@felixfontein Can you re-run the script using Python 3.9? There are a few version specific requirements (importlib-metadata and zipp) that are being removed.

**Review by mattclay — APPROVED** [review]

**Comment by felixfontein** [comment]
@samccann @mattclay thanks a lot for testing, reviewing, and merging!

**Pull request merged**
