### PR TITLE
Use HTTPS instead of legacy HTTP for ansible.com

### PR DESCRIPTION
**Pull request by ypid**
Related to: https://github.com/ansible/ansible/issues/16869

### CODE REVIEW

**Comment by ypid** [comment]
ping

**Comment by gundalow** [comment]
@dharmabumstead This looks good to me, can you check and merge

**Comment by gundalow** [comment]
@ypid Could you please rebase then we can get this merged.

**Comment by ypid** [comment]
@gundalow, @dharmabumstead Done, can you merge to avoid further rebasing :wink: ?

**Review by gundalow — APPROVED** [review]

**Review by dharmabumstead — APPROVED** [review]

**Pull request merged**
