### PR TITLE
add a '*' option for name to state=latest to do a global update

### PR DESCRIPTION
**Pull request by skvidal**
yum: state=latest name='*'

will do a global update

### CODE REVIEW

**Comment by sfromm** [comment]
How about making _all_ synonymous with _*_, ie: `yum: state=latest name=all`?  I think I would remember _all_ better than _*_.  Or is _all_ a reserved word?

**Comment by skvidal** [comment]
I was trying to not make it a 'word' b/c a word can be a package name b/c someone somewhere is a moron and named a package _all_ to be cutsie.

**Comment by a-yiorgos** [comment]
Thank you!

**Comment by sfromm** [comment]
@skvidal unfortunately, that makes sense.  I recommend adding an example to `EXAMPLES` and a blurb to the description for `name` that \* will behave like `yum -y update`.  Thoughts?

**Comment by skvidal** [comment]
I'll add an example and blurb.

**Comment by skvidal** [comment]
not sure what happened here - it wouldn't let me push w/o this. I can remake this branch and PR if that would fix it.

**Comment by jfchevrette** [comment]
+1 for adding the use of _all_. Other modules also do this (nagios for one). _all_ is much more elegant and don't think we should deprive ansible of this for the sole reason that there might by stupid sysadmins out there using this as a package name.

**Comment by mpdehaan** [comment]
I will cherry pick this shortly and can make it do both.

**Comment by mpdehaan** [comment]
cherry pick complete, I'll consider the all alias later.

Wish I could get more of these, sir :)

**Comment by srgvg** [comment]
+1

**Pull request closed without merging**
