### PR TITLE
Remove deprecated get_exception API

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
several

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration test: https://app.shippable.com/github/ansible/ansible/runs/48769/24/tests

**Comment by Akasurde** [comment]
Failing tests are irrelevant to changes. Re-triggering CI.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/51030/26/tests

The same failure occurred after a re-run of CI, so it appears to be related.

**Comment by abadger** [comment]
Looks good.  This is awesome! 

+1 to merge.

**Comment by maxamillion** [comment]
+1 to merge

**Comment by Akasurde** [comment]
@maxamillion @bcoca @abadger @mattclay Thanks.

**Pull request merged**
