### PR TITLE
mysql_db: add master_data parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
mysql_db: add master_data parameter

Fixes: https://github.com/ansible/ansible/pull/19123

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/mysql/mysql_db.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
CC @bmalynovytch

**Review by bmalynovytch — APPROVED** [review]
LGTM :+1:
shipit

**Comment by Andersson007** [comment]
@bmalynovytch thank you!

**Pull request merged**
