### PR TITLE
Add digital ocean domains

### PR DESCRIPTION
**Pull request by mgregson**
Also breaks the digital ocean module into three modules - one for managing droplets, one for managing SSH keys, and one for managing domains.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm starting to not like the 'command' pattern here and wondering if these should be broken into seperate modules like digital_ocean_domain and so on, seeing the inputs are very different.

**Comment by mpdehaan** [comment]
Also note:  I'm ok about breaking compatibility with 1.3 here if need be.

**Comment by mgregson** [comment]
I'm not particularly fond of the way this module works either, but I didn't want to rewrite the whole thing as my first contribution. If we're on the same page about splitting each "command" into distinct actions here I'll gladly do it.

Should the old action be kept around for a minor version or so to give people time to update their playbooks before support is dropped?

**Comment by mgregson** [comment]
@mpdehaan I've kept backwards compatibility by reverting digital_ocean back to its original state.  I've added three new modules: digital_ocean_domain, digital_ocean_droplet, digital_ocean_ssh encompassing the functionality of the three "command" modes from my previous patch.

**Comment by mgregson** [comment]
@mpdehaan Anything I need to do to move this along?

**Comment by mpdehaan** [comment]
Yeah, this is in queue to look at and consider when we get time.

Right now our focus is on closing bug tickets and then we'll start attacking the feature queue again.   Overwhelming community volume at this point :)

Stay tuned!

**Comment by mgregson** [comment]
Is there any work for me to do here?

**Comment by jctanner** [comment]
@mgregson my only concern would be the naming for "digital_ocean_ssh ". It reads more like a connection plugin than something that adds an ssh key. Could you change it to digitial_ocean_sshkey or perhaps something more descriptive?

**Comment by mgregson** [comment]
@jctanner The action should now be named digital_ocean_sshkey.

**Comment by jctanner** [comment]
@mgregson thank you!

**Pull request merged**
