### PR TITLE
Fix for setting values using gconftool-2

### LINKED ISSUE #23670: gconftool2 fails on value: "google-chrome %s"
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gconftool2

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
macOS 10.12.4 managing OpenSUSE Leap 42.2

##### SUMMARY
Cannot change a GNOME configuration value "firefox %s" to "google-chrome %s"

##### STEPS TO REPRODUCE

```yaml
- gconftool2:
    key: "/desktop/gnome/url-handlers/https/command"
    value_type: "string"
    value: "google-chrome %s"
    state: present
```

##### ACTUAL RESULTS
```
<linux.local> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=~/.ansible/cp/f9f5234dc1 -tt linux.local '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1492459444.36-157557468549298/gconftool2.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1492459444.36-157557468549298/" > /dev/null 2>&1 && sleep 0'"'"''
<linux.local> (0, '\r\n{"msg": "gconftool-2 failed with error: No value to set for key: `%s\'\\n", "failed": true, "invocation": {"module_args": {"direct": false, "value": "google-chrome %s", "config_source": null, "state": "present", "value_type": "string", "key": "/desktop/gnome/url-handlers/https/command"}}}\r\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data ~/.ssh/config\r\ndebug3: kex names ok: [curve25519-sha256@libssh.org]\r\ndebug3: kex names ok: [curve25519-sha256@libssh.org,ecdh-sha2-nistp256]\r\ndebug1: ~/.ssh/config line 32: Applying options for linux.local\r\ndebug3: kex names ok: [curve25519-sha256@libssh.org,ecdh-sha2-nistp256]\r\ndebug3: kex names ok: [ecdh-sha2-nistp384]\r\ndebug3: kex names ok: [curve25519-sha256@libssh.org]\r\ndebug1: ~/.ssh/config line 96: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 83781\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to linux.local closed.\r\n')
fatal: [linux.local]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "config_source": null,
            "direct": false,
            "key": "/desktop/gnome/url-handlers/https/command",
            "state": "present",
            "value": "google-chrome %s",
            "value_type": "string"
        }
    },
    "msg": "gconftool-2 failed with error: No value to set for key: `%s'\n"
}
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Miscallenous fixes added to make gconftool-2 work.

Fixes #23670

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/system/gconftool2.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by gundalow** [comment]
@kevensen I believe you created this module, could you please review

**Comment by kevensen** [comment]
LGTM.

**Comment by gundalow** [comment]
Merged into `devel` and cherrypicked into `stable-2.3` (So this will be part of 2.3.1)

https://github.com/ansible/ansible/commit/27073dd9bd053270323e13649a255bd58c861b64

**Comment by Akasurde** [comment]
@gundalow @kevensen Thanks.

**Pull request merged**
