### PR TITLE
contrib/inventory/ec2.py can read AWS credentials from ec2.ini

### PR DESCRIPTION
**Pull request by pwnall**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

The EC2 external inventory uses boto, which reads AWS credentials from a few hard-coded paths relative to the user's home directory.

This PR adds the ability to read AWS credentials from the `ec2.ini` file that accomplishes the EC2 inventory script. The advantage of this approach is that AWS credentials can be specified inside the Ansible project.

For example, I use a playbook to perform a MFA (multi-factor authentication) and generate an ec2.ini that contains the obtained AWS credentials, as well as a few other settings derived from the playbook. I don't want to have to modify any files outside my Ansible project.

I think this capability would be useful to others, and I hope you will consider merging it. Thank you very much for all your work on Ansible!

### CODE REVIEW

**Comment by bcoca** [comment]
@defionscode

**Comment by juliedavila** [comment]
I'd like to see a disclaimer that supplying credentials in the ini is not recommended. Also, it would be good to show a note that profiles are not supported with ini credentials as they are in boto or aws config files.

**Comment by pwnall** [comment]
@defionscode I think I addressed your concerns. Can you please take another look?

In case you're wondering, I'm using this feature in conjunction with [sts_session_token](https://github.com/ansible/ansible-modules-extras/pull/1988) to generate an inventory file that contains MFA (multi-factor-auth) credentials. The generated file is `.gitignore`d, and protected by the same permission bits as SSH keys used to log into machines.

**Comment by amenonsen** [comment]
I don't like this feature at all. Letting credentials proliferate outside the places they're conventionally expected to be is just asking for trouble, and having a warning that says "don't do the exact thing I just added code to support" is a pretty weak protection against mistakes. But I guess I was a bit too late in expressing my reservations.

**Comment by juliedavila** [comment]
@amenonsen I don't either. Internally we decided to okay this, given a disclaimer, as other cloud inventory scripts allow for the storage of credentials within their configs.

**Comment by ozbillwang** [comment]
@amegianeg  & @defionscode & @bcoca 

What happen for this commit, seems it has been merged to ansible coding, but I can see at least two people don't like it, and now plus me. 

We should never use ec2.ini for real AWS key, which is really bad idea. Remember file`ec2.ini` has to be saved to version control (git/svn) when using with `ec2.py`. 

For MFA, the reason by @pwnall is wrong as well.  `~/.aws/config` supports to enable MFA directly. 

Second, because of this commit, it conflicts my commits (#15451) which can fix the issue #15215.

We should vote to rollback @pwnall's commit.

**Comment by pwnall** [comment]
@SydOps I think you missed "I don't want to have to modify any files outside my Ansible project." in my PR description. From a single user's perspective, `~/.aws/config` is global state. In some cases, changing this global state is undesirable. My project was designed so that it can be `git cloned`ed into a directory, and then its commands can be executed without changing anything outside that directory.

Also, in my setup, `ec2.ini` is generated dynamically when a MFA token is obtained. The file is in `.gitignore` so it will not end up in the repository. Asides from the MFA aspect, dynamically generating the file lets me restrict the inventory to regions that I care about, even though the set of regions I care about changes every few days.

Last, there is nothing in my PR preventing you from following the golden path of statically generating an `ec2.ini` and checking it in. This makes me think that your real issue with my PR is that it conflicts with your changes. I think that a more constructive approach would be to ask for help rebasing your commit. If you squash your commits and clean up your code (at the very least, I'd revisit `Not get profile properly`), and then ask nicely, I can try to help you rebase.

**Comment by ozbillwang** [comment]
@pwnall 

First `~/.aws/config and ~/.aws/credentials` are standard for aws cli, `~/.boto` is standard for python/boto. Your way is creating new non-standard way which no one supports in other place. Is it worth to be added here to increase the script complexity and maintainability?

Second, `~/.aws/config` is flexible to support different projects with different profiles, your idea is only for your own project as shortcut, it is not for other, again it is wrong way to put key/password in ec2.ini, not in `~/.aws/config and ~/.aws/credentials`. 

Third, `ec2.ini` should be checked in, can not be ignored. It is very important to customise dynamics inventory result. Do you have to manually share your own `ec2.ini` to other developers in your team, and keep updating to your team separately, when this file need be changed?

So my recommends, you should spend time to study the usage about `~/.aws/config and ~/.aws/credentials` on how to manage your projects in proper way, and play with `ec2.ini` a lot that how many different results you can get with changing it.

**Comment by ozbillwang** [comment]
@defionscode , @bcoca & @amegianeg 

We need review the change in `ec2.py` again. The feature @pwnall added didn't give big improvement for ansible which is only for his own project, but my change for assume_role is higher priority which gives a big help for `enterprise level` requirement and it is `must-have` feature for ec2 dynamic inventory.

**Pull request merged**
