### PR TITLE
contrib: PEP8 compliancy

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
- Make PEP8 compliant

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

contrib/

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by sivel** [comment]
Be aware that I skipped these files in my pass due to missing GPLv3 headers:

https://github.com/ansible/ansible/issues/24341
https://github.com/ansible/ansible/issues/24342
https://github.com/ansible/ansible/issues/24343

I recommend holding off on this change, or hold off on merging, until we can resolve the above issues, otherwise we require additional sign offs.

**Comment by dagwieers** [comment]
@sivel PEP8 changes are changes that are non-copyrightable in nature.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Rebase then I'll merge

**Comment by dagwieers** [comment]
Rebased !

**Pull request merged**
