### PR TITLE
Grafana auth header python2/3 compatibility issue.

### PR DESCRIPTION
**Pull request by markchalloner**
##### SUMMARY

* Fix Python 3 compatibility for grafana_dashboard lookup plugin.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
grafana_dashboard

### CODE REVIEW

**Comment by seuf** [comment]
I think it should be easier for users to give a folder name instead of a folder id.
The folder should be created with an other module. There is already a pull requests for a grafana_folder module : https://github.com/ansible/ansible/pull/48315

**Comment by markchalloner** [comment]
Does #63342 (or another commit) fix the Python 3 compatibility issue in [lib/ansible/plugins/lookup/grafana_dashboard.py](https://github.com/ansible/ansible/pull/50816/files#diff-71f033f2b292b7240c23de0c1119c376R127)?

**Comment by rrey** [comment]
@markchalloner the line you fixed in your patch is still present on devel, so I guess the problem is still here.

But I think you should use the `basic_auth_header` function from `ansible.module_utils.urls` which already deals with python2/3 compatibility for us.

so the code would be something like:

```
from ansible.module_utils.urls import basic_auth_header
[...]

headers['Authorization'] = basic_auth_header(self.grafana_user, self.grafana_password)
```

**Comment by markchalloner** [comment]
@rrey. Thanks, that's done.

**Comment by rrey** [comment]
ship_it

@markchalloner the CI fails for reason that are not related to your code. You can re-trigger the CI by opening/closing the PR.
Once the CI is ok, the patch should be merged.

**Comment by rrey** [comment]
rebase_merge

**Comment by rrey** [comment]
ship_it

**Comment by till** [comment]
@gundalow Can we get your help here as well?

**Comment by rrey** [comment]
@markchalloner can you close/open again to trigger the CI ?

**Comment by rrey** [comment]
bot_status

**Comment by rrey** [comment]
ship_it

**Comment by rrey** [comment]
bot_status

**Comment by felixfontein** [comment]
This needs a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to).

**Comment by rrey** [comment]
@markchalloner can you add the changeling fragment ? We are very close from merge.

**Comment by Akasurde** [comment]
@markchalloner Thanks for the contribution.

**Pull request merged**
