### PR TITLE
don't ask for vars_prompt if host group is empty

### PR DESCRIPTION
**Pull request by cocoy**
Please review.

### CODE REVIEW

**Comment by mpdehaan** [comment]
see #3461 

(making a link)

**Comment by mpdehaan** [comment]
I'm a little uncomfortable with the size of this patch so am leaving this open for now.

**Comment by cocoy** [comment]
@mpdehaan  I can re-submit a clean patch. Seems some lines are really mixed up.

**Comment by cocoy** [comment]
hmm, nm i tried cleaning it up but almost the same diff's :)

**Comment by mpdehaan** [comment]
might just be an issue of github diffs not being so good.  

I'll take a look at this when I have a bit more time to review.

Thanks!

**Comment by jimi-c** [comment]
Could you please rebase this? Thanks!

**Comment by jimi-c** [comment]
Unfortunately there have been a lot of changes in this area of the playbook in regards to roles, so I'm not sure that this can be merged cleanly at all. Could you resubmit this based on the current development branch? Thanks!

**Pull request closed without merging**
