### PR TITLE
Flexible hostname for Scaleway Dynamic Inventory

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

Using IP address is more common to index servers. This PR changes the key to index machines from scaleway id to its public IP.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- Scaleway dynamic inventory

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.7.0.dev0 (key_ip 251266f80b) last updated 2018/06/18 18:30:36 (GMT +200)
  config file = None
  configured module search path = [u'/Users/sieben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sieben/workspace/ansible/lib/ansible
  executable location = /Users/sieben/workspace/ansible/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

### CODE REVIEW

**Comment by remyleone** [comment]
Could you tell me how could we handle machines that got only private IP? What about IPv6 addresses? What are other plugins doing typically?

**Comment by s-hertel** [comment]
In the aws_ec2 inventory plugin this is a configurable option. 
```
plugin: aws_ec2
regions:
  - us-east-1
hostnames:
  - tag:CustomDNSName
  - dns-name
  - private-ip-address
  - ...
```
`hostnames` is a list in order of precedence, it checks each, until it finds an attribute that exists for the new host. If none of the possible hostnames exist for the new host then it doesn't add it to inventory. You could implement something similar for scaleway, defaulting your hostnames to a list of what you think is reasonable precedence.

I'm assuming this is causing a traceback right now because the key doesn't exist. But if it isn't causing a traceback, a workaround could be using the `compose` features to change the ansible_host. In the aws_ec2 inventory plugin this would look like:
```
plugin: aws_ec2
regions:
  - us-east-1
compose:
  # if the new host has a 'private_ip_address' variable set ansible_host with it
  ansible_host: private_ip_address
```
Compose won't change the hostname listed with ansible-inventory --graph (inventory_hostname), but it will change the IP ansible connects to.

**Comment by remyleone** [comment]
@s-hertel Thanks a lot for the explanation. I've started building a similar feature.

**Comment by remyleone** [comment]
@pilou- @maxamillion Could you take a look? I think the dynamic inventory in scaleway starts to be way more useful with this :)

**Comment by remyleone** [comment]
Is this error normal: https://app.shippable.com/github/ansible/ansible/runs/72262/34/console

**Review by s-hertel — APPROVED** [review]
This looks great to me. It would be good if someone using scaleway could test it - @pilou- are you able to?

**Comment by remyleone** [comment]
Could it be backported to 2.6 ?

**Comment by mhalano** [comment]
I tested using "ansible-inventory" command and worked great. The only question is why I can use 'ping' module to a IPv6 address, but this question doesn't  seems related to this pull request. The only problem is in this part of code:
```
...
                - public_ipv4
            choices:
                choices:
                  - public_ipv4
                  - private_ipv6
...
```
You repeated "choices:" two times, which avoid the possible values to field to appear on help.

**Comment by remyleone** [comment]
@mhalano fixed

**Comment by maxamillion** [comment]
rebuild_merge

**Review by maxamillion — APPROVED** [review]

**Comment by remyleone** [comment]
@maxamillion What could we could do to get it merge. I don't think the build fails because of my MR.

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by remyleone** [comment]
@maxamillion I've rebased and pushed again. I hope I will get lucky with the CI this time.

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by remyleone** [comment]
The CI is happy :) could this get merged and backported?

**Comment by mhalano** [comment]
@sieben I think this change is big and not security related, so I wouldn't a good idea to backport that. My $0.02.

**Comment by maxamillion** [comment]
I think this would be a feature and not so much "bugfix" or "security" so I'm not sure it's a candidate for backport, but if there's a reason this falls under one of those categories and I'm simply lacking perspective, I'm open to discussion on the topic.

**Comment by sklemmer** [comment]
@maxamillion Why do you think that this is not a bugfix? Currently the inventory is unusable in version 2.6 as ansible tries to connect using the server id.

**Comment by s-hertel** [comment]
@sklemmer This added a new option. Sometimes features and bugfixes overlap. If you need this on an older version you can add the corrected plugin code in your plugin path and make sure it is enabled if you need the functionality now (the same idea as putting custom/modified modules in your `library` directory for Ansible to use). Or else as a workaround I'd suggest either using an additional config file for the `constructed` plugin to be paired with your 2.6 inventory plugin to correct the hostname (see my suggestion here https://github.com/ansible/ansible/pull/41658#issuecomment-398128220) where your constructed config would contain something along the lines of:
```
plugin: constructed
compose:
  # if the new host has a 'private_ip_address' variable set ansible_host with it
  ansible_host: private_ip_address
```
You can use `ansible-inventory -i yourscalewayconfig.yml -i yourconstructedconfig.yml --list` to check that your ansible_host host vars are set the the correct value. (Note you'll need to make sure either the constructed inventory plugin or the auto inventory plugin is also enabled).

**Pull request merged**
