### PR TITLE
redirecting the conjur lookup plugin to correct collection (#70106)

### PR DESCRIPTION
**Pull request by anshulbehl**
(cherry picked from commit 33e25504ac1211559e47ba35b6163b502e7dbc32)

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by anshulbehl** [comment]
@izgeri

**Comment by gundalow** [comment]
Can you please add this to community.general's meta/runtime.yml as well

**Comment by anshulbehl** [comment]
@gundalow https://github.com/ansible-collections/community.general/pull/570

Let me know if file removal is needed as well in the above pull request

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@anshulbehl Thanks, Can you please `git cherry-pick -x 2a4f4dd ` this into `stable-2.10` as well

**Comment by thedoubl3j** [comment]
@gundalow is this pr not a backport to 2.10? 
```
ansible:stable-2.10 from anshulbehl:backport/2.10/70106
```

**Comment by gundalow** [comment]
It is I was confused as I had a merge buttonm
Maybe I should give up.

**Comment by anshulbehl** [comment]
no worries, thanks @gundalow for merging

**Comment by thedoubl3j** [comment]
it was the right thought, I was just confused on whether you wanted it to go further back and you were just on autopilot with other PRs saying it needs to go to 2.10 after landing in devel ;)

**Pull request merged**
