### PR TITLE
Cygwin support in setup module

### PR DESCRIPTION
**Pull request by grlee**
Added basic checks to setup module for cygwin.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for the work here.

Cygwin is not a supported platform for Ansible, when we do Windows, we'll be doing it a much more native way but I don't want to encourage Cygwin as it takes us down a "fun" path -- this has been discussed on the mailing list several times.

Sorry about the confusion!

**Comment by grlee** [comment]
Makes sense.

George Lee
grlee@alum.mit.edu

**Comment by sontek** [comment]
I'll have to find the mailing lists that discuss this, but since I've found multiple pull requests for this I thought I'd comment.

We use ansible to provision Linux hosts only.  No OSX, FreeBSD, Windows, etc... but the people who manage these hosts could be on any platform (including windows!).  We have no problem installing ssh clients, cygwin, etc on the client machine as long as the end solution is that we can target Linux.

Is there a reason you don't want to support this specific use case?

**Comment by sontek** [comment]
cc @mpdehaan

**Pull request closed without merging**
