### PR TITLE
Remove uneeded call to super.__init__ in LoopControl.

### PR DESCRIPTION
**Pull request by atombrella**
##### SUMMARY

Cleaning up more code.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by atombrella** [comment]
There's also a case in `PyVmomiHelper`, but that's a third-party module.

**Comment by bcoca** [comment]
this is needed, specifically in view of #62207 or similar when we get the templating and validation into the standard way all playbook objects work.

**Comment by atombrella** [comment]
@bcoca It's not intuitive why this is needed. It's overriding an `__init__` function without adding extra functionality.

**Comment by atombrella** [comment]
`ready_for_review`

**Comment by atombrella** [comment]
This project does not use Java, so I still believe it's wrong to be so explicit with `super`. Anyway, I'm closing to get the PR count down.

**Pull request closed without merging**
