### PR TITLE
Replace some more FQCNs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Follow-up to #71824. While checking the backports (#72457, #72458) I found a few more locations that should be adjusted.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
core

### CODE REVIEW

**Comment by felixfontein** [comment]
Useful regexp: `grep -RE "['\"](debug|import_playbook|import_role|import_tasks|include|include_role|include_tasks|include_vars|meta|set_fact|command|shell|script|raw|setup|gather_facts)['\"]"`

**Review by bcoca — APPROVED** [review]

**Comment by felixfontein** [comment]
@bcoca tests passed.

**Review by mattclay — CHANGES_REQUESTED** [review]
Changelog needed.

**Review by mattclay — APPROVED** [review]

**Comment by felixfontein** [comment]
@bcoca @mattclay thanks for reviewing and merging! :)

**Pull request merged**
