### PR TITLE
Treat vars/ and defaults/ in roles like group_vars/ by slurping in al…

### PR DESCRIPTION
**Pull request by jjshoe**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

core
##### SUMMARY

Enable top level vars and defaults files to be "included" automatically. If you have the following:
`
role/
  bob/
    defaults/
      vault_password.yml
`
you would have to `include_vars: ../defaults/vault_password.yml` in your tasks file. With this change you won't have to. It ONLY sucks in files at the first level.

WARNING:

This COULD be "breaking" for people who include different vars based on variables in the top level vars dirs.

### CODE REVIEW

**Comment by jjshoe** [comment]
Talking with @bcoca I MUST use an option to enable this behavior. Currently taking suggestions on the option name.

**Comment by alikins** [comment]
@jjshoe could you provide an example of when/where this would be used?

**Comment by calfonso** [comment]
@jjshoe Still interested in making the suggested change from @bcoca ? If not, please close this PR; otherwise, update the PR and then bring it to the community meeting. Thanks!

**Comment by maxamillion** [comment]
Closing as no response in over a year, please feel free to reopen if you'd like to follow up on this.

**Pull request closed without merging**
