### PR TITLE
New json file module.

### PR DESCRIPTION
**Pull request by miguelcnf**
Same as #7614 only moved to a proper branch.

As written in the doc section this module will add, update or delete a specific key on a given json file.
It allows to manage json files without having to use templates, much like the ini_file module.

Miguel

### CODE REVIEW

**Comment by svisser** [comment]
Some thoughts:
- It may be good to add an action to validate a JSON file. I want to prevent deployment of an invalid JSON file (which is manually edited, I know) so I now have the following but that's admittedly ugly:

``` yaml
- name: Check whether file is JSON
  connection: local
  command: python -c "import json; json.loads(open('{{ playbook_dir }}/path/to/file.json').read());"
  register: json_validation
  failed_when: "'Traceback' in json_validation.stderr"
```

**Comment by miguelcnf** [comment]
@svisser added a validate action:

```
- name: validate json
  json: name="/path/to/file.json" validate="yes"
```

You'll be able to run it as the above and if needed register the proper return code.

**Comment by svisser** [comment]
This looks great!

One thing: the file object in `validate_json_file` isn't closed as in the other functions. How about reusing `read_json_file` so that the file object is closed?

**Comment by svisser** [comment]
Actually reusing `read_json_file` is not such a good idea as you no longer have access to `f` then. So it would need to be solved by adding a `finally:` in `validate_json_file`.

**Comment by miguelcnf** [comment]
You're right, as I was passing a string with `.read()` into `json.loads` unlike in the other methods where I had the file object passed into `json.load` I missed closing up the file.

Let me fix that in a minute.

**Comment by svisser** [comment]
This is better but if the file fails to be opened then `f` is undefined when running the `finally` block. That'll lead to a `NameError` being raised.

**Comment by miguelcnf** [comment]
I think that should cover all the cases.

Changed `finally` to an `else` block to only execute if no exceptions are raised.

**Comment by svisser** [comment]
We're getting there but I just noticed you're not calling the `close` function, you're only accessing it.

**Comment by miguelcnf** [comment]
That has bitten me in the back before. Thanks for noticing!

**Comment by svisser** [comment]
Although I can't really use this module yet, I was playing around with the `get_key` method and it seems I can make it fail by doing:

``` python
>>> def get_key(my_dict, key):
...     return reduce(lambda d, k: d.get(k, {}), key.split('.'), my_dict)
...
>>>
>>> d = {}
>>> d['a'] = {}
>>> d['a']['b'] = 'c'
>>> d
{'a': {'b': 'c'}}
>>> get_key(d, 'a.b.c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in get_key
  File "<stdin>", line 2, in <lambda>
AttributeError: 'str' object has no attribute 'get'
```

I think the behaviour of `get_key` also has implications for empty dictionaries (which are valid in JSON). If I do:

``` python
>>> d['d'] = {}
>>> d
{'a': {'b': 'c'}, 'd': {}}
>>> get_key(d, 'd')
{}
```

then the `delete_key` function won't allow me to delete the key `'d'` because the value is considered False. It's made a bit worse by the fact that JSON also allows `null` (`None`) so `get_key` needs to distinguish between a value that is there (some of which can be falsey, such as `None`, `{}` and `""`) and a value that is really not there.

**Comment by svisser** [comment]
Interesting project that may be relevant here: https://github.com/stefankoegl/python-json-patch

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
