### PR TITLE
Add fallback check for IAM role temp creds

### LINKED ISSUE #39196: aws_ec2 inventory plugin doesn't find/use server IAM role
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

aws_ec2.py 

(aws_ec2.py / all.aws_ec2.yml)

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/inventory']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['aws_ec2', 'host_list', 'virtualbox', 'yaml', 'constructed']

##### OS / ENVIRONMENT

ubuntu 16.04 (ansible host)
ubuntu 16.04 (target host)

##### SUMMARY

Ansible server has IAM role that works with dynamic inventory script (ec2.py / ec2.ini). Switching dynamic inventory source to aws_ec2 plugin (aws.ec2.py / all.aws_ec2.yml) fails with WARNING message "Insufficient boto credentials found". 

##### STEPS TO REPRODUCE

```
inventory_test.yml
---
- hosts: "{{ target }}"
  remote_user: ansible
  become: yes
  tasks:
    - name: test connection
      ping:
      remote_user: ansible

all.aws_ec2.yml

plugin: aws_ec2
regions: # populate inventory with instances in these regions
  - us-east-1
filters:
  
# ignores 403 errors rather than failing
strict_permissions: False
hostnames:
  - tag:Name
  - private-ip-address    

```

##### EXPECTED RESULTS

Expect ansible to find/use server IAM role to return test-instance with aws_ec2 inventory plugin for playbook execution

##### ACTUAL RESULTS

Ansible warns of "Insufficient boto credentials found" and prompts to place credentials in inventory configuration file or environment variables. 

Ansible output warns : Insufficient boto credentials found. Please provide them in your inventory
configuration file or set them as environment variables.

```
ansible-playbook -e "target=test-instance" inventory_test.yml -vvvv
ansible-playbook 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
 [WARNING]:  * Failed to parse /etc/ansible/plugins/inventory/all.aws_ec2.yml with aws_ec2 plugin: Insufficient boto credentials found. Please provide them in your inventory
configuration file or set them as environment variables.

  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 264, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/aws_ec2.py", line 505, in parse
    self._set_credentials()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/aws_ec2.py", line 444, in _set_credentials
    raise AnsibleError("Insufficient boto credentials found. Please provide them in your "

 [WARNING]:  * Failed to parse /etc/ansible/plugins/inventory/all.aws_ec2.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory

  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 264, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/aws_ec2.py", line 505, in parse
    self._set_credentials()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/aws_ec2.py", line 444, in _set_credentials
    raise AnsibleError("Insufficient boto credentials found. Please provide them in your "

 [WARNING]:  * Failed to parse /etc/ansible/plugins/inventory/all.aws_ec2.yml with constructed plugin: Incorrect plugin name in file: aws_ec2

  File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 264, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/yaml.py", line 103, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')

 [WARNING]: Unable to parse /etc/ansible/plugins/inventory/all.aws_ec2.yml as an inventory source

 [WARNING]: Unable to parse /etc/ansible/plugins/inventory as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: inventory_test.yml *************************************************************************************************************************************************************
1 plays in inventory_test.yml
 [WARNING]: Could not match supplied host pattern, ignoring: test-instance


PLAY [test-instance] *********************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *******************************************************************************************************************************************************************************

```

### PR DESCRIPTION
**Pull request by jsutter55**
Add fallback check for IAM role temp creds

##### SUMMARY

Fixes #39196
Add fallback check for IAM role temp creds

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

aws_ec2.py

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by cliles** [comment]
@ryansb - Will you please see this gets cherrypicked to 2.5?

**Comment by ryansb** [comment]
This PR adds the file at the top level - please check out the repo, then add your changes in-place so this PR passes CI properly.

**Comment by ryansb** [comment]
Right now this can't be merged at all

**Comment by jsutter55** [comment]
@ryansb / @cliles 

CI Tests were still failing after checkout/update. 
Opened a new PR with fresh fork to clean things up and CI checks have passed here: 

https://github.com/ansible/ansible/pull/40240

**Pull request closed without merging**
