### PR TITLE
Update playbooks_lookups.rst add example with using encrypt

### PR DESCRIPTION
**Pull request by lied**
Add a sample for using password lookup with a system user account and option encrypt

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this!

(Note to self - probably want to move this down a bit and tweak the language some after merging)

**Comment by mpdehaan** [comment]
Somewhat concerned we should just stress usage of vault here.

This will generate a SHA and use the SHA everywhere, but doesn't really get the original back out.   Maybe something we should deprecate (having shoud not have merged originally)

**Comment by lied** [comment]
For me and my team it is working quite good :-)

**Comment by amenonsen** [comment]
I think this PR should just be closed now. It's a trivial five-line patch, but really all it adds to the other existing examples of lookup('password', ...) is the encrypt= parameter. It's not worth keeping around for a year or more, especially given the concerns @mpdehaan expressed (which I agree with, FWIW).

**Comment by gregdek** [comment]
Agreed, we'll pass on this patch. Thanks @lied for the submission, and sorry it's taken so long for a decision here.

**Pull request closed without merging**
