### PR TITLE
add azure_rm_cdnprofile and azure_rm_cdnprofile_facts

### PR DESCRIPTION
**Pull request by yungezz**
##### SUMMARY

add new  modules:  azure_rm_cdnprofile and azure_rm_cdnprofile_facts.

##### ISSUE TYPE

 - New Module Pull Request

##### ANSIBLE VERSION

```
ansible 2.7
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by yungezz** [comment]
hi @mattclay , as you know, CDN creation test failed in this integration test https://app.shippable.com/github/ansible/ansible/runs/82246/77/console, I've checked with service team, the CI subscription need to register CDN provider by following this guideline https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-supported-services#portal, pls note provider to registered is `Microsoft.Cdn`.

**Comment by yungezz** [comment]
Hi @mattclay , could you pls help to do the registration as above? thanks.

**Comment by yungezz** [comment]
hi @mattclay , could you help on the configuration change as mentioned above? thanks.

**Comment by mattclay** [comment]
@yungezz I've registered the `Microsoft.Cdn` provider.

**Comment by yungezz** [comment]
Thank you @mattclay ! will rebase the PR.

**Comment by yungezz** [comment]
ready_for_review

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
