### PR TITLE
fix py3 scope for unique filter errors, enable filters integration tests on rhel8 beta

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller <admiller@redhat.com>

##### SUMMARY

fix py3 scope for unique filter errors, enable filters integration tests on rhel8 beta

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/plugins/filter/mathstuff.py
test/integration/targets/filters/aliases

### CODE REVIEW

**Review by sivel — APPROVED** [review]

**Comment by abadger** [comment]
+1.  If this needs to be backported, it will need a changelog.

**Review by bcoca — APPROVED** [review]

**Comment by Akasurde** [comment]
related with https://github.com/ansible/ansible/issues/48969

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by jborean93** [comment]
@maxamillion are you able to backport this all the way back to stable-2.5. This also blocked the Fedora 29 integration tests so thanks for fixing it up.

**Comment by maxamillion** [comment]
@jborean93 Ansible 2.5.x is currently in the "Security Fixes Only" phase of it's lifecycle, is there motivation to deviate from the standard release process on this?

**Comment by jborean93** [comment]
@maxamillion usually I wouldn’t but we need this fix in place to support the Fedora 29 container in ansible-test which goes all the way back to whatever is still supported.

**Comment by abadger** [comment]
So we talked about this general issue today in #core_internal and came up with this conclusion:

> abadger1999 [9:59 AM]
> In critical and security stages, the emphasis for testing should be on regressions.  If 2.5's unique filter plugin didn't work on f30 to begin with, then we shouldn't be fixing that once 2.5 is in security fixes only stage.  But that means that we have to do something so that testing of that filter plugin on f30 is disabled... which could be "We didn't support f30 to begin with so we don't have to do it now" or it could be more targeted "We didn't support that filter plugin on f30 to begin with so we don't have to do so now" or it could be more broad "We didn't support f30 to begin with so we don't have to do it now".... we just have to figure out what we think our policy should be and merge changes according to that policy.
> nitzmahone [10:04 AM]
> Fair points... I guess I'd still opt for "test on platforms we build" by default, and if there are failures for new platforms on security-only branches, we can decide case-by-case if we disable individual tests vs disabling the entire platform. @mattclay - opinions?
> abadger1999 [10:06 AM]
> <nod> Yeah, I'm okay with that.  I just want us to do it with our eyes open and a plan in mind.
> mattclay [10:06 AM]
> @abadger1999 It depends how much backporting is needed for the tests to pass. If the backports are test fixes only, I'd go all the way to 2.5. If they include bug fixes, I'd go back to 2.6.
> @abadger1999 If the bug fixes are non-trivial I'd probably stop at backporting to 2.7.


So to follow that plan, this would be backported all the way to 2.6.  2.5 would need to have the relevant tests disabled on Fedora 29 instead.

**Comment by maxamillion** [comment]
@jborean93 @abadger so I just looked at backporting this, it's not applicable in 2.7, 2.6, or 2.5 ... this issue was introduced in a 2.8 devel change. :)

**Comment by jborean93** [comment]
Backporting is a moot point then :)

**Pull request merged**
