### PR TITLE
ansible-test - split controller/target testing

### LINKED ISSUE #73674: ansible-test - using --explain with --docker causes stacktrace
##### SUMMARY

At this time I've only tested with:
- devel via `hacking/env-setup` (so Python 2)
- units

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-test

##### ANSIBLE VERSION

```paste below
ansible 2.11.0.dev0 (devel 5078a0baa2) last updated 2021/02/20 09:52:15 (GMT -400)
  config file = None
  configured module search path = [u'/home/briantist/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/briantist/code/ansible/ansible.core/lib/ansible
  ansible collection location = /home/briantist/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/briantist/code/ansible/ansible.core/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
  jinja version = 2.11.2
  libyaml = False
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(env: ANSIBLE_CALLBACK_WHITELIST) = [u'profile_tasks']
DEFAULT_FORKS(env: ANSIBLE_FORKS) = 30
```

##### OS / ENVIRONMENT

Ubuntu 18.04 via WSLv2

##### STEPS TO REPRODUCE

```
ansible-test --docker default -e
```

##### EXPECTED RESULTS

full explain output

##### ACTUAL RESULTS

```paste below
Run command: docker images quay.io/ansible/default-test-container:3.1.0 --format '{{json .}}'
Assuming Docker is available on localhost.
Run command: docker run --detach --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=false --security-opt seccomp=unconfined --volume /var/run/docker.sock:/var/run/docker.sock ...
Run command: docker rm -f test_id
Traceback (most recent call last):
  File "/home/briantist/code/ansible/ansible.core/bin/ansible-test", line 28, in <module>
    main()
  File "/home/briantist/code/ansible/ansible.core/bin/ansible-test", line 24, in main
    cli_main()
  File "/home/briantist/code/ansible/ansible.core/test/lib/ansible_test/_internal/cli.py", line 181, in main
    delegate(config, *delegate_args)
  File "/home/briantist/code/ansible/ansible.core/test/lib/ansible_test/_internal/delegation.py", line 139, in delegate
    return delegate_command(args, exclude, require, integration_targets)
  File "/home/briantist/code/ansible/ansible.core/test/lib/ansible_test/_internal/delegation.py", line 159, in delegate_command
    delegate_docker(args, exclude, require, integration_targets)
  File "/home/briantist/code/ansible/ansible.core/test/lib/ansible_test/_internal/delegation.py", line 342, in delegate_docker
    ssh_keys_sh = get_ssh_key_setup(SshKey(args))
  File "/home/briantist/code/ansible/ansible.core/test/lib/ansible_test/_internal/manage_ci.py", line 374, in get_ssh_key_setup
    ssh_key_type=ssh_key.KEY_TYPE,
  File "/home/briantist/code/ansible/ansible.core/test/lib/ansible_test/_internal/util_common.py", line 61, in substitute
    kvp = dict((k, cmd_quote(v)) for k, v in kwargs.items())
  File "/home/briantist/code/ansible/ansible.core/test/lib/ansible_test/_internal/util_common.py", line 61, in <genexpr>
    kvp = dict((k, cmd_quote(v)) for k, v in kwargs.items())
  File "/usr/lib/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'NoneType' object is not iterable
```

### LINKED ISSUE #74818: ansible-test returns 0 even when no suitable interpreters were found and no tests were run
### Summary

`ansible-test units` command looks for several Python interpreter versions to run tests with. If it finds none that it knows, it doesn't run any tests, but it still returns 0 as if everything was ok. It should return an error in this case.

This is important for example in CI, where such issue can cause false successes. Even though the tests/code is broken, the CI will be green just because no suitable Python interpreter was found. This happened to us recently, where Ansible 2.9 looks for interpreters upto Python 3.8, but we only had Python 3.9 installed, and this caused tests to "succeed" even when they shouldn't.

### Issue Type

Bug Report

### Component Name

ansible-test

### Ansible Version

```console
$ ansible --version

ansible 2.9.22
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/venv/lib64/python3.9/site-packages/ansible
  executable location = /root/venv/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 00:00:00) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed

(empty)
```

### OS / Environment

Fedora 33

### Steps to Reproduce

* Make sure you have only Python versions not recognized by `ansible-test`, e.g. Python 3.9 and Ansible 2.9.22.
* `cd $HOME/.ansible/collections/some_namespace/some_collection`
* `ansible-test units`

### Expected Results

The `ansible-test units` command should return a nonzero code.

### Actual Results

```console
The `ansible-test units` command returns 0.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### LINKED ISSUE #74840: ansible-test with remote machines
### Summary

I am trying to write integration tests for a collection, but we need a specific OS that is not available as a docker image on ansible-test.

Is there a way to specify an inventory file with `ansible-test integration` so we can use our own remote machines with the specifications that we need to run our collection.

### Issue Type

Feature Idea

### Component Name
ansible-test

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Overhaul ansible-test to support a separate controller and target host for integration tests.

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

ansible-test

##### ADDITIONAL INFORMATION

Follow-up changes will be required. Updates to some tests will also be required. Changelog entries are also needed.

Resolves https://github.com/ansible/ansible/issues/74840
Resolves https://github.com/ansible/ansible/issues/73674
Resolves https://github.com/ansible/ansible/issues/74818

### CODE REVIEW

**Comment by felixfontein** [comment]
When running unit tests (in collections) with this branch, installing images fails since the pypi proxy isn't correctly set up. (This doesn't happen in ansible/ansible since everything's already installed in the default container.) More precisely, in `configure_pypi_proxy` the call to `get_container_database(args)` returns `{}`.

**Comment by felixfontein** [comment]
Also, when trying to run this locally (both collection and ansible/ansible)  (example command is `ansible-test integration --truncate 0 --color -v --controller docker:default,python=3.8 --target docker:default,python=3.8`), the SSH daemon in the target container never seems to start up. (Interesting differnce: in ansible-core this fails with `SSH connection to controller required by tests. Checking the connection.`, in a collection it starts ansible-playbook and that fails with `fatal: [testhost]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"172.17.0.3\". Make sure this host can be reached over ssh: ssh: connect to host 172.17.0.3 port 22: Connection refused\r\n", "unreachable": true}`.)

**Comment by felixfontein** [comment]
One problem I noticed with `--remote`: it looks like not the system's Python (3) is used for the remote, but 3.8 (at least for FreeBSD and RHEL). This causes some tests to fail which install Python libraries via system packages (which then aren't around for Python 3.8).

Also it seems that on macOS 11.1, `which brew` no longer works.

**Comment by vbotka** [comment]
> ..., but 3.8 (at least for FreeBSD ... ) This causes some tests to fail which install Python libraries via system packages (which then aren't around for Python 3.8).

This shouldn't happen on FreeBSD. Python 3.8 is the default

```sh
shell> cat /usr/ports/Mk/bsd.default-versions.mk | grep -i python
	PGSQL PHP PYTHON PYTHON2 PYTHON3 RUBY RUST SAMBA SSL TCLTK VARNISH
PYTHON_DEFAULT?=	3.8
PYTHON2_DEFAULT?=	2.7
PYTHON3_DEFAULT?=	3.8
```

If you have trouble installing 3.8 packages switch to "latest", e.g.

```sh
shell> cat /etc/pkg/FreeBSD.conf
freebsd {
    mirror_type = "srv";
    signature_type = "fingerprints";
    fingerprints = "/usr/share/keys/pkg";
    enabled = true;
    url = "pkg+http://pkg.FreeBSD.org/${ABI}/latest";
}
```

**Comment by felixfontein** [comment]
@vbotka that's not correct for FreeBSD 12.2 and 13.0 used in Ansible's CI. That one is using Python 3.7 without this branch, but Python 3.8 with this branch.

(You can see that by grepping for `Message from python3` in the CI logs; for example the community.crypto logs without this branch are https://dev.azure.com/ansible/b711c73a-dc70-4ed2-bdab-4f8346a649ce/_apis/build/builds/24120/logs/814 and https://dev.azure.com/ansible/b711c73a-dc70-4ed2-bdab-4f8346a649ce/_apis/build/builds/24120/logs/794, and with this branch are https://dev.azure.com/ansible/b711c73a-dc70-4ed2-bdab-4f8346a649ce/_apis/build/builds/24111/logs/378 and https://dev.azure.com/ansible/b711c73a-dc70-4ed2-bdab-4f8346a649ce/_apis/build/builds/24111/logs/379 - the latter both fail with `pkg: No packages available to install matching 'py38-cryptography' have been found in the repositories`, while the former work fine, as `py37-cryptography` is apparently already installed.)

**Comment by vbotka** [comment]
> @vbotka that's not correct for FreeBSD 12.2 and 13.0 used in Ansible's CI. That one is using Python 3.7 without this branch, but Python 3.8 with this branch.

The py38-* packages are available publicly. The repos, you use, are not in sync if you can't get them. I've never used FreeBSD on Azure. I don't know what Azure policy is in providing FreeBSD repos. If they ignore it you have to get them on your own.  I can help you with the installation of the [build](https://ansible-freebsd-poudriere.readthedocs.io/en/latest/) server if you have the power. Let me know.

**Comment by mattclay** [comment]
@felixfontein Thanks for pointing out the issue with `which brew`. That occurs because `/usr/local/bin` is no longer added to `PATH` by `ansible-test` on macOS. That's something that may warrant changing to the previous behavior.

**Comment by samccann** [comment]
Hey @mattclay - this seems like a huge PR, but only has two tiny edits to some .rst files (aka docs). Is it all that simple for the end user/developer, or are you anticipating adding more docs to this PR?

**Comment by felixfontein** [comment]
> @felixfontein Thanks for pointing out the issue with `which brew`. That occurs because `/usr/local/bin` is no longer added to `PATH` by `ansible-test` on macOS. That's something that may warrant changing to the previous behavior.

The same issue will probably happen in ansible/ansible in test/integration/targets/setup_gnutar/tasks/main.yml, 

> @felixfontein Using Python 3.8+ on the controller is expected since it is the minimum version supported. The current behavior in this PR when running on a single host with no Python version specified is to use the controller Python version for the target as well. On FreeBSD and RHEL this results in a Python other than the default system version being used for the target. That behavior is something that could be changed, and is something I've been considering.

I think it's a good idea to change it, since testing modules on FreeBSD and RHEL with the default Python version better reflects how most modules will be used 'in the wild'. (And cloud/network/... modules can always add `context/controller` to `aliases`.)

**Comment by felixfontein** [comment]
79d64e644ce87ca9e320cc220e961d2c21f91e33 fixed the macOS problems for me. CI in community.general now passes (again) on all macOS instances.

**Comment by mattclay** [comment]
@samccann Yes, it is a huge PR. Docs would be good, but will most likely be written after this PR is merged, since there are still issues with tests and functionality to be worked through.

**Comment by felixfontein** [comment]
I've now tried this PR with seven collections. The current things that fail are (as already mentioned above):
1. Python 2.6 unit tests fail;
2. On RHEL and FreeBSD VMs, the system Python isn't used on the target (this leads to Python libs not available in the Python used which were installed as system packages).

The work I had to do was mostly:
1. Replace `output_dir` by `remote_tmp_dir` (and including [setup_remote_tmp_dir](https://github.com/ansible/ansible/tree/devel/test/integration/targets/setup_remote_tmp_dir));
2. Look at all `lookup("file", ...)` and replace all that load data from the target with [slurp](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/slurp_module.html);
3. Also grep for `role_path`, which is sometimes used to let the target work on files that are only on the controller. They need to be copied with `copy`, preferably to `remote_tmp_path`.

**Comment by vbotka** [comment]
> 1. Python 2.6 unit tests fail;
> 2. On RHEL and FreeBSD VMs, the system Python isn't used on the target (this leads to Python libs not available in the Python used which were installed as system packages).

Since 2020-01-01 is [Python 2.7 EOL](https://devguide.python.org/devcycle/#end-of-life-branches). Why do you test 2.*?

Python 3.5 will be EOL 2020-09-30. No need to test FreeBSD with EOL branches. See [Upstream Branch Support](https://wiki.freebsd.org/Python/PortsPolicy#Upstream_Branch_Support).

**Comment by mattclay** [comment]
@felixfontein The issue with the PyPI proxy has been fixed with commit a2bd5700eb278df4285d88542b8970120e4a384d

**Comment by mattclay** [comment]
@felixfontein Are you still having issues with the SSH daemon in containers not starting? If so, can you provide more details on your environment, particularly your docker host?

**Comment by mattclay** [comment]
@felixfontein With the most recent changes, the issues you were seeing with FreeBSD and RHEL should be resolved. The target Python version is now selected from supported versions independently of the controller Python version.

**Pull request merged**
