### PR TITLE
openssl_*: proper mode support

### LINKED ISSUE #48656: openssl_privatekey can't create files which only have read permissions
##### SUMMARY
openssl_privatekey module can not create read-only keys (mode 0444 or less)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_privatekey

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /home/m3adow/.ansible.cfg
  configured module search path = ['/opt/ansible/lib/python3.5/site-packages/ansible/modules']
  ansible python module location = /opt/ansible/lib/python3.5/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.5.1 (default, Sep 15 2016, 08:33:29) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### CONFIGURATION
```
ACTION_WARNINGS(default) = True
AGNOSTIC_BECOME_PROMPT(default) = False
ALLOW_WORLD_READABLE_TMPFILES(default) = False
ANSIBLE_COW_PATH(default) = None
ANSIBLE_COW_SELECTION(default) = default
ANSIBLE_COW_WHITELIST(default) = ['bud-frogs', 'bunny', 'cheese', 'daemon', 'default', 'dragon', 'elephant-in-snake', 'elephant', 'eyes', 'hellokitty', 'kitty', 'luke-koala', 'meow', 'milk', 'moofasa', 'moose', 'ren', 'sheep', 'small', 'stegosaurus', 'stimpy', 'supermilker', 'three-eyes', 'turkey', 'turtle', 'tux', 'udder', 'vader-koala', 'vader', 'www']
ANSIBLE_FORCE_COLOR(default) = False
ANSIBLE_NOCOLOR(default) = False
ANSIBLE_NOCOWS(default) = False
ANSIBLE_PIPELINING(default) = False
ANSIBLE_SSH_ARGS(default) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(default) = None
ANSIBLE_SSH_CONTROL_PATH_DIR(default) = ~/.ansible/cp
ANSIBLE_SSH_EXECUTABLE(default) = ssh
ANSIBLE_SSH_RETRIES(default) = 0
ANY_ERRORS_FATAL(default) = False
BECOME_ALLOW_SAME_USER(default) = False
CACHE_PLUGIN(default) = memory
CACHE_PLUGIN_CONNECTION(default) = None
CACHE_PLUGIN_PREFIX(default) = ansible_facts
CACHE_PLUGIN_TIMEOUT(default) = 86400
COLOR_CHANGED(default) = yellow
COLOR_CONSOLE_PROMPT(default) = white
COLOR_DEBUG(default) = dark gray
COLOR_DEPRECATE(default) = purple
COLOR_DIFF_ADD(default) = green
COLOR_DIFF_LINES(default) = cyan
COLOR_DIFF_REMOVE(default) = red
COLOR_ERROR(default) = red
COLOR_HIGHLIGHT(default) = white
COLOR_OK(default) = green
COLOR_SKIP(default) = cyan
COLOR_UNREACHABLE(default) = bright red
COLOR_VERBOSE(default) = blue
COLOR_WARN(default) = bright purple
COMMAND_WARNINGS(default) = True
DEFAULT_ACTION_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/action', '/usr/share/ansible/plugins/action']
DEFAULT_ALLOW_UNSAFE_LOOKUPS(default) = False
DEFAULT_ASK_PASS(default) = False
DEFAULT_ASK_SUDO_PASS(default) = False
DEFAULT_ASK_SU_PASS(default) = False
DEFAULT_ASK_VAULT_PASS(default) = False
DEFAULT_BECOME(default) = False
DEFAULT_BECOME_ASK_PASS(default) = False
DEFAULT_BECOME_EXE(default) = None
DEFAULT_BECOME_FLAGS(default) =
DEFAULT_BECOME_METHOD(default) = sudo
DEFAULT_BECOME_USER(default) = root
DEFAULT_CACHE_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/cache', '/usr/share/ansible/plugins/cache']
DEFAULT_CALLABLE_WHITELIST(default) = []
DEFAULT_CALLBACK_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/callback', '/usr/share/ansible/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(default) = []
DEFAULT_CLICONF_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/cliconf', '/usr/share/ansible/plugins/cliconf']
DEFAULT_CONNECTION_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/connection', '/usr/share/ansible/plugins/connection']
DEFAULT_DEBUG(default) = False
DEFAULT_EXECUTABLE(default) = /bin/sh
DEFAULT_FACT_PATH(default) = None
DEFAULT_FILTER_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter']
DEFAULT_FORCE_HANDLERS(default) = False
DEFAULT_FORKS(/home/m3adow/.ansible.cfg) = 25
DEFAULT_GATHERING(default) = implicit
DEFAULT_GATHER_SUBSET(default) = ['all']
DEFAULT_GATHER_TIMEOUT(default) = 10
DEFAULT_HANDLER_INCLUDES_STATIC(default) = False
DEFAULT_HASH_BEHAVIOUR(default) = replace
DEFAULT_HOST_LIST(default) = ['/etc/ansible/hosts']
DEFAULT_HTTPAPI_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/httpapi', '/usr/share/ansible/plugins/httpapi']
DEFAULT_INTERNAL_POLL_INTERVAL(default) = 0.001
DEFAULT_INVENTORY_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/inventory', '/usr/share/ansible/plugins/inventory']
DEFAULT_JINJA2_EXTENSIONS(default) = []
DEFAULT_JINJA2_NATIVE(default) = False
DEFAULT_KEEP_REMOTE_FILES(default) = False
DEFAULT_LIBVIRT_LXC_NOSECLABEL(default) = False
DEFAULT_LOAD_CALLBACK_PLUGINS(default) = False
DEFAULT_LOCAL_TMP(default) = /home/m3adow/.ansible/tmp/ansible-local-11654o_r_4kci
DEFAULT_LOG_FILTER(default) = []
DEFAULT_LOG_PATH(default) = None
DEFAULT_LOOKUP_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup']
DEFAULT_MANAGED_STR(default) = Ansible managed
DEFAULT_MODULE_ARGS(default) =
DEFAULT_MODULE_COMPRESSION(default) = ZIP_DEFLATED
DEFAULT_MODULE_LANG(default) = {{ CONTROLLER_LANG }}
DEFAULT_MODULE_NAME(default) = command
DEFAULT_MODULE_PATH(/home/m3adow/.ansible.cfg) = ['/opt/ansible/lib/python3.5/site-packages/ansible/modules']
DEFAULT_MODULE_SET_LOCALE(default) = False
DEFAULT_MODULE_UTILS_PATH(default) = ['/home/m3adow/.ansible/plugins/module_utils', '/usr/share/ansible/plugins/module_utils']
DEFAULT_NETCONF_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/netconf', '/usr/share/ansible/plugins/netconf']
DEFAULT_NO_LOG(default) = False
DEFAULT_NO_TARGET_SYSLOG(default) = False
DEFAULT_NULL_REPRESENTATION(default) = None
DEFAULT_POLL_INTERVAL(default) = 15
DEFAULT_PRIVATE_KEY_FILE(default) = None
DEFAULT_PRIVATE_ROLE_VARS(default) = False
DEFAULT_REMOTE_PORT(default) = None
DEFAULT_REMOTE_USER(default) = None
DEFAULT_ROLES_PATH(default) = ['/home/m3adow/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
DEFAULT_SCP_IF_SSH(default) = smart
DEFAULT_SELINUX_SPECIAL_FS(default) = ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p']
DEFAULT_SFTP_BATCH_MODE(default) = True
DEFAULT_SQUASH_ACTIONS(default) = ['apk', 'apt', 'dnf', 'homebrew', 'openbsd_pkg', 'pacman', 'pip', 'pkgng', 'yum', 'zypper']
DEFAULT_SSH_TRANSFER_METHOD(default) = None
DEFAULT_STDOUT_CALLBACK(default) = default
DEFAULT_STRATEGY(default) = linear
DEFAULT_STRATEGY_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/strategy', '/usr/share/ansible/plugins/strategy']
DEFAULT_SU(default) = False
DEFAULT_SUDO(default) = False
DEFAULT_SUDO_EXE(default) = sudo
DEFAULT_SUDO_FLAGS(default) = -H -S -n
DEFAULT_SUDO_USER(default) = None
DEFAULT_SU_EXE(default) = su
DEFAULT_SU_FLAGS(default) =
DEFAULT_SU_USER(default) = None
DEFAULT_SYSLOG_FACILITY(default) = LOG_USER
DEFAULT_TASK_INCLUDES_STATIC(default) = False
DEFAULT_TERMINAL_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/terminal', '/usr/share/ansible/plugins/terminal']
DEFAULT_TEST_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/test', '/usr/share/ansible/plugins/test']
DEFAULT_TIMEOUT(default) = 10
DEFAULT_TRANSPORT(default) = smart
DEFAULT_UNDEFINED_VAR_BEHAVIOR(default) = True
DEFAULT_VARS_PLUGIN_PATH(default) = ['/home/m3adow/.ansible/plugins/vars', '/usr/share/ansible/plugins/vars']
DEFAULT_VAULT_ENCRYPT_IDENTITY(default) = None
DEFAULT_VAULT_IDENTITY(default) = default
DEFAULT_VAULT_IDENTITY_LIST(default) = []
DEFAULT_VAULT_ID_MATCH(default) = False
DEFAULT_VAULT_PASSWORD_FILE(default) = None
DEFAULT_VERBOSITY(default) = 0
DEPRECATION_WARNINGS(default) = True
DIFF_ALWAYS(default) = False
DIFF_CONTEXT(default) = 3
DISPLAY_ARGS_TO_STDOUT(default) = False
DISPLAY_SKIPPED_HOSTS(default) = True
ENABLE_TASK_DEBUGGER(default) = False
ERROR_ON_MISSING_HANDLER(default) = True
GALAXY_IGNORE_CERTS(default) = False
GALAXY_ROLE_SKELETON(default) = None
GALAXY_ROLE_SKELETON_IGNORE(default) = ['^.git$', '^.*/.git_keep$']
GALAXY_SERVER(default) = https://galaxy.ansible.com
GALAXY_TOKEN(default) = None
HOST_KEY_CHECKING(default) = True
INJECT_FACTS_AS_VARS(default) = True
INVALID_TASK_ATTRIBUTE_FAILED(default) = True
INVENTORY_ANY_UNPARSED_IS_FAILED(default) = False
INVENTORY_ENABLED(default) = ['host_list', 'script', 'yaml', 'ini', 'auto']
INVENTORY_EXPORT(default) = False
INVENTORY_IGNORE_EXTS(default) = {{(BLACKLIST_EXTS + ( '~', '.orig', '.ini', '.cfg', '.retry'))}}
INVENTORY_IGNORE_PATTERNS(default) = []
INVENTORY_UNPARSED_IS_FAILED(default) = False
LOCALHOST_WARNING(default) = True
MAX_FILE_SIZE_FOR_DIFF(default) = 104448
NETCONF_SSH_CONFIG(default) = None
NETWORK_GROUP_MODULES(default) = ['eos', 'nxos', 'ios', 'iosxr', 'junos', 'enos', 'ce', 'vyos', 'sros', 'dellos9', 'dellos10', 'dellos6', 'asa', 'aruba', 'aireos', 'bigip', 'ironware', 'onyx', 'netconf']
PARAMIKO_HOST_KEY_AUTO_ADD(default) = False
PARAMIKO_LOOK_FOR_KEYS(default) = True
PERSISTENT_COMMAND_TIMEOUT(default) = 10
PERSISTENT_CONNECT_RETRY_TIMEOUT(default) = 15
PERSISTENT_CONNECT_TIMEOUT(default) = 30
PERSISTENT_CONTROL_PATH_DIR(default) = /home/m3adow/.ansible/pc
PLAYBOOK_VARS_ROOT(default) = top
PLUGIN_FILTERS_CFG(default) = None
RETRY_FILES_ENABLED(default) = True
RETRY_FILES_SAVE_PATH(/home/m3adow/.ansible.cfg) = /tmp/m3adow-ansible-retries
SHOW_CUSTOM_STATS(default) = False
STRING_TYPE_FILTERS(default) = ['string', 'to_json', 'to_nice_json', 'to_yaml', 'ppretty', 'json']
SYSTEM_WARNINGS(default) = True
TAGS_RUN(default) = []
TAGS_SKIP(default) = []
TASK_DEBUGGER_IGNORE_ERRORS(default) = True
USE_PERSISTENT_CONNECTIONS(default) = False
VARIABLE_PRECEDENCE(default) = ['all_inventory', 'groups_inventory', 'all_plugins_inventory', 'all_plugins_play', 'groups_plugins_inventory', 'groups_plugins_play']
YAML_FILENAME_EXTENSIONS(default) = ['.yml', '.yaml', '.json']
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux 6.10, probably affects all Linux versions

##### STEPS TO REPRODUCE
Small playbook:
```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Create test private key
      openssl_privatekey:
        path: "/tmp/testkey.pem"
        mode: 0444
```
##### EXPECTED RESULTS
Private Key is created with mode 0444

##### ACTUAL RESULTS
Empty file created, error `[Errno 13] Permission denied: '/tmp/testkey.pem'`
Full Output:
```
TASK [Create test private key] ***********************************************************************************************************************
task path: /home/m3adow/tmp/ansible/mode_test.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: m3adow
<127.0.0.1> EXEC /bin/sh -c 'echo ~m3adow && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/m3adow/.ansible/tmp/ansible-tmp-1542187965.482906-6128038229065 `" && echo ansible-tmp-1542187965.482906-6128038229065="` echo /home/m3adow/.ansible/tmp/ansible-tmp-1542187965.482906-6128038229065 `" ) && sleep 0'
Using module file /opt/ansible/lib/python3.5/site-packages/ansible/modules/crypto/openssl_privatekey.py
<127.0.0.1> PUT /home/m3adow/.ansible/tmp/ansible-local-1272517qp_4di/tmp_6u1z4py TO /home/m3adow/.ansible/tmp/ansible-tmp-1542187965.482906-6128038229065/AnsiballZ_openssl_privatekey.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/m3adow/.ansible/tmp/ansible-tmp-1542187965.482906-6128038229065/ /home/m3adow/.ansible/tmp/ansible-tmp-1542187965.482906-6128038229065/AnsiballZ_openssl_privatekey.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/opt/ansible/bin/python3 /home/m3adow/.ansible/tmp/ansible-tmp-1542187965.482906-6128038229065/AnsiballZ_openssl_privatekey.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/m3adow/.ansible/tmp/ansible-tmp-1542187965.482906-6128038229065/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_openssl_privatekey_payload_wbj9kjfh/__main__.py", line 291, in main
    private_key.generate(module)
  File "/tmp/ansible_openssl_privatekey_payload_wbj9kjfh/__main__.py", line 204, in generate
    raise PrivateKeyError(exc)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "cipher": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": null,
            "mode": 292,
            "owner": null,
            "passphrase": null,
            "path": "/tmp/testkey.pem",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "size": 4096,
            "src": null,
            "state": "present",
            "type": "RSA",
            "unsafe_writes": null
        }
    },
    "msg": "[Errno 13] Permission denied: '/tmp/testkey.pem'"
}
        to retry, use: --limit @/tmp/m3adow-ansible-retries/mode_test.retry
```

I suspect the problem to be this line: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssl_privatekey.py#L193
The mode is set before the key is written, probably to prevent any possibility of an information leak. But if the mode is set to read-only, which is a common mode for Private Keys, to prevent accidental overwrites, the second `open()` can't write to it anymore.

### LINKED ISSUE #53476: String mode parameter for openssl_pkcs12
##### SUMMARY
The openssl_pkcs12 module is not accepting a string for the mode parameter.
I get a python error when executing the openssl_pkcs12 task that includes *mode* as a string value.

Also appears to be related to PR #50035. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_pkcs12

Problem appears to be in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssl_pkcs12.py around line 202-204 and 267.

##### ANSIBLE VERSION
FIrst observed on ansible 2.7.4. Recreated on dev branch (details below).
```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/psparks/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/psparks/glproj/ansible/lib/ansible
  executable location = /home/psparks/glproj/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
No changes to the default config.   
```paste below

```

##### OS / ENVIRONMENT

Running on CentOS 7.

##### STEPS TO REPRODUCE
Run ansible-playbook with the following playbook.

```yaml
---
- hosts: localhost
  tasks:
  - name: Create private key
    openssl_privatekey:
      path: "./bugdemo.key"
  - name: Create CSR
    openssl_csr:
      path: "./bugdemo.csr"
      privatekey_path: "./bugdemo.key"
      common_name: bugdemo.com
  - name: Create certificate
    openssl_certificate:
      path: "./bugdemo.pem"
      privatekey_path: "./bugdemo.key"
      csr_path: "./bugdemo.csr"
      provider: selfsigned

  - name: demo bug
    openssl_pkcs12:
      state: present
      action: export
      path: "./bugdemo.p12"
      friendly_name: bugdemo
      passphrase: "password"
      privatekey_path: "./bugdemo.key"
      certificate_path: "./bugdemo.pem"
      mode: "0400"
```

##### EXPECTED RESULTS

Expected playbook to complete successfully with bugdemo.p12 created.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i hosts issue.yml
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.23) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)

PLAY [localhost] *************************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [localhost]

TASK [Create private key] ****************************************************************************
changed: [localhost]

TASK [Create CSR] ************************************************************************************
changed: [localhost]

TASK [Create certificate] ****************************************************************************
changed: [localhost]

TASK [demo bug] **************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Shared connection to localhost closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/psparks/.ansible/tmp/ansible-tmp-1551985290.79-191699757902245/AnsiballZ_openssl_pkcs12.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/psparks/.ansible/tmp/ansible-tmp-1551985290.79-191699757902245/AnsiballZ_openssl_pkcs12.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/psparks/.ansible/tmp/ansible-tmp-1551985290.79-191699757902245/AnsiballZ_openssl_pkcs12.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_openssl_pkcs12_payload_aqhpGf/__main__.py\", line 391, in <module>\r\n  File \"/tmp/ansible_openssl_pkcs12_payload_aqhpGf/__main__.py\", line 357, in main\r\n  File \"/tmp/ansible_openssl_pkcs12_payload_aqhpGf/__main__.py\", line 267, in generate\r\nTypeError: an integer is required\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *******************************************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Refactors result file writing by using a helper method in `module_utils/crypto.py`. This fixes #53476, and ~~hopefully~~ also fixes #48656.

~~First version doesn't handle openssl_certificate to avoid screwing up #53924.~~

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/crypto.py
openssl_certificate
openssl_csr
openssl_privatekey
openssl_publickey
openssl_pks12

### CODE REVIEW

**Comment by felixfontein** [comment]
Unstable CI will be fixed by #54088, i.e. everything else works (so far).

**Comment by felixfontein** [comment]
ready_for_review

**Comment by Shaps** [comment]
Looks good to me. 
shipit

**Comment by felixfontein** [comment]
@Shaps thanks for reviewing!

**Comment by felixfontein** [comment]
@mkrizek thanks for merging!

**Pull request merged**
