### PR TITLE
doc_fragments: Clean up parameter types (database)

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:
- Parameter types added
- Copyright format fixes
- Short license statement
- Description fixes (only for a few files, then I stopped :-))

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
database module_utils

### CODE REVIEW

**Comment by Andersson007** [comment]
lgtm
type: path - looks good ;) I didn't know it before.

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
shipit

**Comment by dagwieers** [comment]
cc @gundalow @acozine

**Review by bmalynovytch — APPROVED** [review]

**Comment by bmalynovytch** [comment]
+label shipit

**Review by gundalow — APPROVED** [review]

**Pull request merged**
