### PR TITLE
warn when name is overloaded as both host and group

### LINKED ISSUE #6545: Ansible inventory allows groups to have same name as hosts
##### Issue Type

Bug Report
##### Ansible Version:

ansible 1.6 (devel 9da26da335) last updated 2014/03/18 11:15:04 (GMT +1000)
##### Environment:

N/A
##### Summary:

If you define a group containing another group without the :children, then the intended group is a host, but will also become a group when defining its contents. 

The net result is that the host that should inherit characteristics of several layers of parents will not inherit those characteristics as the definitions will be:

grandparent -> parent(host)
parent(group) -> host

rather than
grandparent -> parent -> host

I believe that it should not be possible to define a group with the same name as a host (or at least a warning suggesting it might not be what you want should happen)
##### Steps To Reproduce:

See https://gist.github.com/willthames/9614054 
##### Expected Results:

See https://gist.github.com/willthames/9614054
##### Actual Results:

See https://gist.github.com/willthames/9614054

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
added small optimization to base group comparisson
fixes #6545

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

inventory

##### ANSIBLE VERSION

```
2.3
```

### CODE REVIEW

**Comment by mscherer** [comment]
Look fine to me

**Comment by alikins** [comment]
dont have any tests to run, but code looks good to me.

**Comment by alikins** [comment]
testing with hosts file:

``` ini
localhost ansible_connection=local
swoop ansible_host=192.168.1.35
foo ansible_connection=local

[foo]
swoop

recursive_group
[recursive_group]
recursive_group

[localhost]
localhost

all
[all]
all

[ungrouped]
all

# from https://gist.github.com/willthames/9614054

[group-a:children]
group-b

# here group-c is actually a host because of the missing :children
[group-b]
group-c

# as a result, host-c is also a host, but doesn't belong to group-b (or group-a)
[group-c]
host-c

[group-b:vars]
group_b_var=group-b
```
Gives me:

```
[fedora-25:ansible (pr-22519 %)]$ ansible-playbook -i test_hosts -vvv ping.yml  --list-hosts
Using /home/adrian/.ansible.cfg as config file
 [WARNING]: Found both group and host with same name: all

 [WARNING]: Found both group and host with same name: foo

 [WARNING]: Found both group and host with same name: localhost

 [WARNING]: Found both group and host with same name: group-c

 [WARNING]: Found both group and host with same name: recursive_group

```

Which looks right on first glance.

**Comment by webevt** [comment]
Now, when using docker.py dynamic inventory (https://github.com/ansible/ansible/blob/devel/contrib/inventory/docker.py), ansible issues a bunch of warnings, for each existing container, e.g.:

>  [WARNING]: Found both group and host with same name: nginx
>  [WARNING]: Found both group and host with same name: web
>  [WARNING]: Found both group and host with same name: elk-logstash
>  [WARNING]: Found both group and host with same name: https://10.20.1.2:2376
>  [WARNING]: Found both group and host with same name: mysql

**Comment by mixja** [comment]
When I use Ansible to target cloud environments rather than traditional "hosts" I have to use a pattern where the group name and host name are the same.  

This warning is annoying - what is the purpose?

**Comment by rubal033** [comment]
Is it possible to suppress these warning for the cloud environment or by fliping a flag in the configurations?

**Comment by jmenga** [comment]
I have raised #32283 to provide an ansible.cfg setting to suppress these warnings

**Pull request merged**
