### PR TITLE
Fix for #28699 to support GovCloud ARNs

### LINKED ISSUE #28699: lambda role doesn't accept AWS GovCloud ARNs
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible/lib/ansible/modules/cloud/amazon/lambda.py

##### ANSIBLE VERSION
ansible 2.3.2.0

##### CONFIGURATION
standard

##### OS / ENVIRONMENT
AWS Ubuntu 16.04
Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

AWS GovCloud (us-gov-west-1)

##### SUMMARY

Attempting to set the role to either just the role name or the full ARN fails the lambda deployment or update because AWS can't find the specified role.

Looking in the lambda.py module, the code assumes the region partition to ever only be 'aws'.  However, the us-gov-west-1 region partition is 'aws-us-gov'.

##### STEPS TO REPRODUCE

```
    tasks:
        - name: Deploy hello world
            lambda:
            name: "run_hello_world"
            runtime: "python27"
            s3_bucket: "my_bucket"
            s3_key: "my_key"
            role: "hello_world_role"

        - name: Deploy hello world Again
            lambda:
                name: "run_hello_world"
                runtime: "python27"
                s3_bucket: "my_bucket"
                s3_key: "my_key"
                role: "arn:aws-us-gov:iam::1234567890:role/hello_world_role"
```

##### EXPECTED RESULTS
Lambda function to be created 

##### ACTUAL RESULTS

```
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "An error occurred (ValidationException) when calling the UpdateFunctionConfiguration operation: 1 validation error detected: Value 'arn:aws:iam::1234567890:role/arn:aws-us-gov:iam::1234567890:role/hello_world_role' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws|aws-us-gov):iam::\\d{12}:role/?[a-zA-Z_0-9+=,.@\\-_/]+"}
```

### PR DESCRIPTION
**Pull request by jmal98**
##### SUMMARY
Fixes #28699 if you are using the lambda module in a GovCloud region

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lambda

### CODE REVIEW

**Comment by s-hertel** [comment]
It looks like there's a more thorough PR open to handle this - https://github.com/ansible/ansible/pull/28704. Do you mind testing that branch?

**Comment by jmal98** [comment]
> It looks like there's a more thorough PR open to handle this - #28704. Do you mind testing that branch?

@s-hertel is that PR's changes compatible with the current dev branch given it's age?  If so, I may be able to give it a try later in the week.

As a side note, instead of using a regex approach for validation, why not use a simple method of checking the prefix and then using it as is?  Especially since the ARN format is pretty stable and doubtful of changing.

https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-arns

**Comment by jillr** [comment]
@jmal98 Looks like the patch does rebase cleanly and integration tests pass for me so you should be able to test with it.  New partitions certainly aren't added often, but it does happen (aws-cn for example).  Any time we can avoid hard-coding a value it's one less bug folks might run into down the road if Amazon does change something.

**Comment by tremble** [comment]
resolved_by_pr #28704

**Pull request closed without merging**
