### PR TITLE
Ovirt modules pep8 fixes

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

cloud/ovirt/*.py

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

This patches fixes various pep8 issues.

### CODE REVIEW

**Comment by machacekondra** [comment]
Shipit

**Comment by machacekondra** [comment]
@ryansb @mwperina

**Review by mwperina — APPROVED** [review]
:+1:

**Comment by machacekondra** [comment]
Looks like something went wrong with git, I've recreated the PR here: https://github.com/ansible/ansible/pull/19141.

**Pull request closed without merging**
