### PR TITLE
Add examples and language to better showcase the 'parents' parameter in multiple network modules

### PR DESCRIPTION
**Pull request by tyler-8**
##### SUMMARY

The parents parameter isn't well showcased in the examples or documentation. I added two more examples that show slightly more complex ways to use it.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
>>> ansible.__version__
'2.5.0'
```

### CODE REVIEW

**Comment by tyler-8** [comment]
Failures appear to be from https://github.com/ansible/ansible/commit/bc6b1ca17b4ebe6223d5bab5aca2395194925bed and https://github.com/ansible/ansible/commit/dab0661cc75516b0c9317f84c9c1187bc03a7215

**Comment by tyler-8** [comment]
-label feature_pull_request

**Comment by gundalow** [comment]
May make sense to add similar examples to the other `_config` modules

**Comment by tyler-8** [comment]
Certainly do not disagree. I don't have a lot of familiarity with the other `_config` modules' OSes that use `parents` though.  At the very least, perhaps the addition of "`or hierarchy`" would help with the other modules?

**Comment by gundalow** [comment]
@tyler-8 "or hierarchy" sounds good. Would you be able to add that?

**Comment by tyler-8** [comment]
@gundalow That should be all of them :)

**Comment by tyler-8** [comment]
Okay looks like everything is cleaned up now.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@tyler-8 Thank you for this. Merged into `devel` and cherry-picked into `stable-2.5` https://github.com/ansible/ansible/commit/3f475054fa151022491614d7004fe8cba4b88290

**Pull request merged**
