### PR TITLE
Add user & group option to find module

### PR DESCRIPTION
**Pull request by jylenhof**
##### SUMMARY
During my work, we put bad uid and bad gid for a user, so I needed to do a playbook remidiation to change uid & gid of a user... And need to change files belonging to them, but user & group option don't exist in find module.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
find

##### ANSIBLE VERSION
2.6.0

### CODE REVIEW

**Comment by jylenhof** [comment]
Will solve #38737

**Comment by maxamillion** [comment]
Thank you for the pull request, could you pleas add some [integration tests](https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html) to exercise the new functionality added? Also, please include a [changelog fragment](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs). Otherwise the changes look good. 👍

**Comment by jylenhof** [comment]
If I understand, you want some tests added in 
 ansible/test/integration/targets/find/tasks/main.yml ?

If I have time will try to do it... But I'm quite occupied right now at work (maybe more pull request about git module... Will make an issue to see if anyone working on it before working on it)

**Comment by maxamillion** [comment]
@jylenhof yes please, add test cases to `test/integration/targets/find/tasks/main.yml` that exercise the functionality added here.

**Comment by samdoran** [comment]
Closing due to inactivity.

**Pull request closed without merging**
