### PR TITLE
Test hosts defined in multiple groups in different files

### PR DESCRIPTION
**Pull request by g-k-r**
The test now works identical to calling ansible directly as mentioned in #5749

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm confused because the first patch here seems to add comments, and the third patch seems to change the way the test is being run.

Is the intent to just not add a new test covering a different scenario?

**Comment by g-k-r** [comment]
the first patch is needed because inventory_dir was not being parsed successfully

the third patch overwrites the implementation of the test introduced in the second patch, so it behaves identical to the ansible executable

I do not know whether the inventory.get_group call should be investigated though and offered to add a test specifically for get_group

**Comment by mpdehaan** [comment]
I'm not comfortable with the test changing above.

Perhaps it should add a new test, but changing the test from form A to form B effectively removes the test of the first form.

**Comment by mpdehaan** [comment]
Closing per the above.

**Comment by g-k-r** [comment]
@mpdehaan do i understand correctly that you'd rather have two tests to also expose the inventory.get_group behaviour ? note that in any case it is a new test, and not a change of an existing one (in branch: devel).

**Pull request closed without merging**
