### PR TITLE
vmware_guest: option to enable nested virtualization

### PR DESCRIPTION
**Pull request by jglf**
##### SUMMARY
Add an option to the vmware_guest module to enable nested virtualization

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
2.4.0 0.0.devel

##### ADDITIONAL INFORMATION
Tested on vcenter 6.0

### CODE REVIEW

**Comment by Akasurde** [comment]
@jglf Could you please add testcase for this change ?

**Comment by jglf** [comment]
I haven't had time lately to look into adding testcases but will try to.

**Comment by Akasurde** [comment]
@jglf Could you please rebase and add integration tests so we can take it forward ?

**Comment by Akasurde** [comment]
@jglf Thanks for your contribution.

**Pull request merged**
