### PR TITLE
[passwordstore] Add dependencies to Dockerfiles

### PR DESCRIPTION
**Pull request by 3onyc**
##### SUMMARY
This pull request updates the dockerfiles with the required dependencies for CI to pass on #25843

Required for #25843 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
plugin / lookup / integration tests

##### ANSIBLE VERSION
devel/HEAD

### CODE REVIEW

**Comment by samdoran** [comment]
cc @mattclay @gundalow

**Comment by 3onyc** [comment]
Before I forget, also check Current Issues on #25843 as at least one of those would involve changes herfe

**Comment by mattclay** [comment]
This should be merged after https://github.com/ansible/ansible/pull/25843 has been merged, as explained in my [comment](https://github.com/ansible/ansible/pull/25843#issuecomment-316889824) there.

**Comment by mattclay** [comment]
The distribution specific test containers have moved: https://github.com/ansible/distro-test-containers

**Comment by mattclay** [comment]
I'm still working on migrating everything over to the new containers. The next time I add additional packages to optimize the containers I'll be sure to include the `pass` package.

**Pull request closed without merging**
