### PR TITLE
New Module: vsphere_fetch - download files from datastores

### PR DESCRIPTION
**Pull request by garbled1**
##### SUMMARY

New Module: vsphere_fetch - download files from datastores

Allows you to easily download arbitrary files from a vmware datastore.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vsphere_fetch.py

##### ANSIBLE VERSION

```
ansible 2.5.0 (vsphere_fetch c068fa8836) last updated 2017/09/30 14:45:57 (GMT +000)
  config file = None
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/ansible/lib/ansible
  executable location = /home/ec2-user/ansible/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```

##### ADDITIONAL INFORMATION

```
- name: Fetch a file to the ansible server
  vsphere_fetch:
    host: vhost
    login: vuser
    password: vpass
    src: some/remote/file
    datacenter: DC1 Someplace
    datastore: datastore1
    dest: /some/local/file
  transport: local
- name: Fetch a file to the managed node, set mode and ownership
  vsphere_fetch:
    host: vhost
    login: vuser
    password: vpass
    src: other/remote/file
    datacenter: DC2 Someplace
    datastore: datastore2
    dest: /other/local/directory/
    owner: root
    group: root
    mode: 0644
  delegate_to: other_system

```

### CODE REVIEW

**Comment by dagwieers** [comment]
So I think the name should be vcenter_fetch, the older module named vsphere_copy was named because back then all the "vSphere" modules (using pysphere) were called vsphere_something. So we should rename vsphere_copy to vcenter_copy IMO.

**Comment by garbled1** [comment]
I don't disagree with the better convention, but as far as re-naming the vsphere_copy module, would the idea be to supply a symlink or something so old playbooks would still work?

(side note, I also have a slight fix to vsphere_copy I'm going to request a pull for soon that adds state: absent and deals with zero-byte files properly)

**Comment by jjahns** [comment]
I would go so far as to say since the folder name is "vmware" to make sure all modules prefix with vmware. Unless there is a reason why we shouldn't.

As for vsphere_copy rename - can't we just deprecate this module in lieu for vmware_copy so we don't have a problem with existing playbooks calling it? This way you can transition releases off of it.

/J

**Comment by dagwieers** [comment]
The stuff that only works with vCenter is better named vcenter_something. There are more examples.

We could move those modules if necessary, but I don't think that's needed. Check the [amazon](https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/cloud/amazon) directory.

**Comment by garbled1** [comment]
Regarding the rename of this module, and potentially vsphere_copy, I have one minor concern.  If the convention for vmware_* vs vcenter_* is the use of pyvmomi, then in order to fix issue #27893 , we will most likely need to use pyvmomi to get the esxi host behind the datastore to perform the efficient copy.  (I've been staring at doing this one in the future perhaps).  This will mean both _fetch and _copy (or _file or whatever) will use that library. Does that change the naming convention again?

**Comment by dagwieers** [comment]
@garbled1 No, the *vcenter_* prefix to me is related to *this module manages resources on vCenter*. Whereas **vmware_guest** works with ESXi as well, without vCenter. Just like any other Ansible module, the name reflects the technology/product and the managed object. So it's not related to the use of pyvmomi specifically. (See: https://github.com/vmware/ansible-modules-extras-gpl3)

If it works with ESXi as well, then yes, it probably should be named **vmware_copy** rather than **vcenter_copy**.

PS We probably should have this discussion during a VMware Working Group meeting to get consensus.

**Comment by jjahns** [comment]
@dagwieers I'd counter this. There are modules that only hit vCenter, and are prefixed with vmware.

If the plan is to change the naming convention across all the modules, then yes we should discuss further.

But lets not discourage. Copy/fetch has a use case here.

**Comment by dagwieers** [comment]
@jjahns Yes, unfortunately everything was prefixed *vmware_*. And we'd better fix that soon than later, instead of adding a new *vsphere_* module and making things worse.

PS Not sure what you are countering, or who is discouraging anything. The usefulness of copy/fetch is not at stake here. (Besides, I wrote **vsphere_copy**, why would I not see the use case ?)

**Comment by dagwieers** [comment]
@garbled1 When I looked at this, there was no way to manage files on datastores using vSphere or the vCenter API. Maybe that has changed ?

**Comment by jjahns** [comment]
@dagwieers I just want to be careful taking a hard line stance without agreement. I've seen it happen too many times. The discourage comment was a generalization.

I agree - if we want to standardize naming - lets open up a discussion.

**Comment by jjahns** [comment]
@dagwieers And with that - I will defer to whatever is decided.

**Comment by dagwieers** [comment]
@jjahns https://github.com/ansible/community/issues/233#issuecomment-334086741

Everybody with an interest, please join the next meeting on Monday !

**Comment by jjahns** [comment]
@dagwieers Will try to make it. Not sure if the VMW guys working on those modules have an official stance on standardization. I'll inquire on it. That's a different team than mine.

**Comment by dagwieers** [comment]
@jjahns Since they have an interest in merging these modules, I expect they prefer to keep the module names (for themselves, but also for their users). But I am open to other ideas as well.

So the official way to rename modules, is to deprecate them ('_' prefix), and symlink them in Github. That provides a convenient upgrade path to whatever we decide.

**Comment by jjahns** [comment]
@dagwieers Valid point. I don't think you need my input here. I go with the flow. That team's modules probably require some minor revision to make them compliant for merging. I won't get in the way of the process.

**Comment by jjahns** [comment]
@garbled1 After our discussion, this looks like we can name the module "vmware_datastore_fetch"

Do you object?

**Comment by garbled1** [comment]
I agree.  I will make the edits to this branch, if that works.

**Comment by dagwieers** [comment]
Why **vmware_datastore_fetch** and not just **vmware_fetch** ? It's not like we call the existing **fetch** module **filesystem_fetch**.

If you want to follow the Ansible conventions closely, it should actually be **vmware_file_fetch** because fetch is an operation on files, not on datastores (the module describes the object it manages, files in this case).

But I think it has no purpose, **copy** and **fetch** are known modules that relate to files, and what else is there to copy to/fetch from vmware, other than files from datastores ?

**Comment by dagwieers** [comment]
Did someone confirm that with the same implementation you can copy and fetch files from both vCenter as well as ESXi ? I had assumed that the implementation (and module parameters) would be sufficiently different to support the fact that a different module would be easier for users. (So vcenter_fetch vs esxi_fetch, rather than a single vmware_fetch).

For vCenter a different combination of parameters would be needed than for ESXi (e.g. datacenter, cluster, datastore), and the values would be different (folder would be a file system folder, rather than a datacenter/datastore folder.

**Comment by garbled1** [comment]
So, for esxi, I can confirm that the existing vsphere_copy module, as exists in the tree works just fine on esxi.  You have to change the values you feed to it slightly, ie, datacenter=ha-datacenter,  and hostname is the esxi host, but it just works.  To do efficient copy, there will need to be some rewrite and fiddling, but there will not ever be a need for a second module.

As for the naming, the rational discussed during the meeting is that the modules operate on datastores, regardless of how they get to it (esxi, vcenter, magic).  and the name vmware_datastore_copy/fetch/file makes it obvious what is going on there.  When I look at those three names, I feel I know immediately what occurs. 

However, at this point, I would just like a decision made on this.  I like vmware_datastore_X, and we had consensus from the people present at the last WG meeting on that name, but I don't particularly care.  I'm just stuck in a holding pattern now waiting on a thing to name these so I can get them fixed up and re-submitted.

**Comment by garbled1** [comment]
According to: https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.wssdk.pg.doc_50%2FPG_ChC_Http_Access.21.3.html

It is possible to muck with the configuration files of an ESXI host directly with url access. This is different than placing files on a datastore, as you are basically reconfiguring the esxi host itself. or downloading logs.  In theory one might want a vmware_esxi_copy/fetch/delete set of modules to do this?  Apparently you can also stash files in /tmp on an esxi, presumably to install drivers?

**Comment by jjahns** [comment]
I don't know if that is still supported (the docs you linked are 5.0).

As of 6.5.0 you can use the fetch, copy, template, get_url modules directly onto the ESXI host if SSH is opened. But if SSH is not opened, you have to resort to other means at doing file operations.

If you make this module "vmware_fetch" it assumes that you can get any file, not just files on datastores, off of vCenter or ESXI. "vmware_datastore_fetch" implicitly implies that we are grabbing something off of the datastore, and its possible to make that compatible with both ESXI and vCenter, but for first iteration, vCenter is fine.

If this module is expanded to cover all files, via API call or some other means that is not SSH, then it can be renamed and the old module deprecated.

**Comment by Akasurde** [comment]
@garbled1 Are you still working on this ? needs_info

**Pull request closed without merging**
