### PR TITLE
Refactor module to use subclasses like user module.

### PR DESCRIPTION
**Pull request by eest**
- Basically the moving parts from the original service module arranged in
  subclasses.
- General structure and helper methods comes from the user module.
- Less forgiving to unsupported platforms: it requires a subclass per platform.
  (This makes it easier to work on one platform without having to think about.
  what other platform might be affected in unexpected ways).
- Now has basic OpenBSD support.
- Solaris support needs to be added.

Thanks to @dhozac for general advice and Linux testing.
Thanks to @bcoca for clearing up some FreeBSD questions.

---

Please review this, as far as I know it has been tested on Ubuntu 12.04, OpenBSD 5.2, FreeBSD 8.2 Fedora 15 and CentOS.

There are still some problems with the FreeBSD enable stuff, but it seems to be the same problems in the old version of the module and I'm looking into it.

Also, this version breaks Solaris support. I wanted to take a look at adding a proper subclass making it work, but the form that was needed to be filled in to get hold of the installation media stopped me from doing so :(. Maby @romeotheriault could take a look if the rework is considered good enough?

### CODE REVIEW

**Comment by rrtj3** [comment]
Hi @eest, I looked it over and it looks great to me. What a breath of fresh air compared to what it was becoming before. Thanks for your work on this. I wouldn't worry about whatever little solaris support it may have had before. Once this gets merged I'll quickly add Solaris SMF support. 

Not suggesting you do this, just thinking aloud here, but I hope going forward that the different linux distro users create subclasses for their distros . I think it would be much clean to have them each on their own.

**Comment by rrtj3** [comment]
> Not suggesting you do this, just thinking aloud here, but I hope going forward that the different linux distro users        create subclasses for their distros . I think it would be much clean to have them each on their own.

Should have said distros that use different 'init' type systems. e.g upstart, systemd, init, etc..

**Comment by mpdehaan** [comment]
On Sun, Nov 18, 2012 at 2:23 AM, Romeo Theriault
notifications@github.comwrote:

> Not suggesting you do this, just thinking aloud here, but I hope going
> forward that the different linux distro users create subclasses for their
> distros . I think it would be much clean to have them each on their own.
> 
> Should have said distros that use different 'init' type systems. e.g
> upstart, systemd, init, etc..

Well, sort of

It should subclass based on the detected init system type, not neccessarily
by distribution.

**Comment by eest** [comment]
@mpdehaan: I'm not sure I understand what you are saying. Should the init-system detection be added before this can be merged? Is it even close to what you were looking for?

**Comment by mpdehaan** [comment]
I'm not asking for you to do anything at this point, I'm saying ignore
Romeo's addition.

This is probably fine, but we need to test it first, so it's in queue.

**Comment by rrtj3** [comment]
> I'm not asking for you to do anything at this point, I'm saying ignore
> Romeo's addition.

Not sure why you'd ignore it. It sounds to me like we're on the same page.

I said:

> Should have said distros that use different 'init' type systems. e.g
>  upstart, systemd, init, etc..

You said:

> Well, sort of
> It should subclass based on the detected init system type, not neccessarily
> by distribution.

**Comment by mpdehaan** [comment]
re: your earlier comment

**Comment by mpdehaan** [comment]
ugh, I totally mangled history for this in github when I fixed some attribution issues.  Do you mind trying to rebase this and resubmitting?  you may need to check out the repo again. 

Very sorry!   I bet you can just copy the user module you have now on top of the new checkout.

**Comment by eest** [comment]
@mpdehaan: I'm looking at it now, unfortunately the module has been patched since my PR. I will have to try and incorporate those fixes as well.

**Pull request closed without merging**
