### PR TITLE
Allow vault to operate from stdin/to stdout (i.e. plaintext never hits the disk)

### PR DESCRIPTION
**Pull request by amenonsen**
This is something I've mentioned on IRC a few times, but not submitted as a PR before. With this, and the semi-related #11767, it's possible to automate various vault operations without ever leaking plaintext to disk, even in the form of temp files.

### CODE REVIEW

**Comment by bcoca** [comment]
So instead of making these command line options, i would just trigger this when stdin/stdout are not a tty.  We already do this detection for vars_prompt/pause avoidance, using color on the terminal or using the pager in ansible-doc

**Comment by amenonsen** [comment]
I've added a commit that sets `self.options.read_from_stdin` or `.write_to_stdout` based on whether stdin and stdout `isatty()` or not. As discussed on IRC, I'd prefer to be able to continue to explicitly specify the behaviour on the command-line in some cases. @abadger approved of the idea, so here it is.

**Comment by amenonsen** [comment]
After some discussion on IRC between @abadger and @bcoca and myself, I started to implement a version that allowed `ansible-vault encrypt input.yml --output output.yml` as well as `cat input.yml|ansible-vault encrypt --output output.yml` and the equivalents for decryption. Unfortunately, this would be a very intrusive change because of the way the code is now.

So here's an implementation that adds a new `ansible-vault filter` subcommand that _always_ reads from stdin and always writes to stdout. Backwards compatibility, easy to document, no ambiguity, and a simpler change to review as well.

What do you think of this?

**Comment by abadger** [comment]
@amenonsen I like the feature but I do think it belongs in encrypt/decrypt rather than a separate subcommand.  Mind if I give it a shot?

**Comment by amenonsen** [comment]
See #12112 instead for the requested implementation.

**Pull request closed without merging**
