### PR TITLE
get_url: PEP8, imports, cosmetics

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
- Make PEP8 compliant
- Ensure imports are specific
- Few cosmetic changes (sort lists, casing, punctuation)

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by jpmens** [comment]
shipit

**Comment by mattclay** [comment]
CI failure in integration tests. Here's one example:

```
{
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_6Gafzj/ansible_module_get_url.py\", line 485, in <module>\n    main()\n  File \"/tmp/ansible_6Gafzj/ansible_module_get_url.py\", line 335, in main\n    dest_is_dir = os.path.isdir(dest)\nNameError: global name 'os' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Review by gundalow — CHANGES_REQUESTED** [review]
Missing os import

**Comment by dagwieers** [comment]
@gundalow It seems that one was coming in with the "import *" :-(

**Comment by dagwieers** [comment]
Shippable error. Close and reopen.

**Comment by dagwieers** [comment]
Close and re-open ?

**Review by gundalow — APPROVED** [review]

**Review by gundalow — APPROVED** [review]

**Pull request merged**
