### PR TITLE
Fix style for maven_artifact documentation

### PR DESCRIPTION
**Pull request by switchboardOp**
##### SUMMARY
Removed unnecessary bullets from the synopsis under DOCUMENTATION.
Previously there were bullets beginning each line with no respect to the start or end of sentences.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
##### ADDITIONAL INFORMATION
N/A this is just a Docs change.

### CODE REVIEW

**Comment by tumbl3w33d** [comment]
Hi @switchboardOp, could you please squash your commits into one? Then we'll be good to go.

**Comment by tumbl3w33d** [comment]
needs_revision

**Comment by switchboardOp** [comment]
@tumbl3w33d - I squashed 'em.

**Comment by tumbl3w33d** [comment]
shipit

**Comment by switchboardOp** [comment]
ready_for_review

**Comment by switchboardOp** [comment]
shipit

**Comment by switchboardOp** [comment]
Thanks @bcoca ... my first merge to a legit open source project!
Closing this PR.

**Pull request merged**
