### PR TITLE
Add digital_ocean_domain_record to manage specific DNS records in digital_ocean.

### PR DESCRIPTION
**Pull request by dopry**
depends on 
https://github.com/devo-ps/dopy/pull/11 
or https://github.com/devo-ps/dopy/pull/9
or https://github.com/devo-ps/dopy/pull/5

### CODE REVIEW

**Comment by mpdehaan** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:
- this seems to depend on three changes to dopy that are not yet taken upstream
- dopy seems to be growing unmaintained given those are low numbered tickets that have not had a response, so we need to have a discussion about what to do about this on the mailing list

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always neccessary.

Thank you once again for this and your interest in Ansible!

**Comment by dopry** [comment]
@mpdehaan, I'm actively talking to the guys at devo.ps to get the fixes to dopy merged and pushed to pypi. If that is your only concern, I should be able to get that done in short order. The library is stable except this feature, which they don't use and is incorrectly documented on the digital ocean developer site.  I'm happy to release and maintain the module independently, but wanted to offer it back to you guys. I'll ping you when the upstream dopy issues are resolved.

**Comment by zbal** [comment]
The latest dopy library has been pushed over to pypi. @dopry give it a shot and see if it fixes your issues.

**Comment by dopry** [comment]
Awesome Thanks! I'll test tomorrow and get back to you.

On Tue, Aug 19, 2014 at 9:36 PM, Vincent Viallet notifications@github.com
wrote:

> The latest dopy library has been pushed over to pypi. @dopry
> https://github.com/dopry give it a shot and see if it fixes your issues.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/pull/8509#issuecomment-52724089.

## 

Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101

**Comment by dopry** [comment]
this has been moved to https://github.com/ansible/ansible-modules-core/pull/900

**Pull request closed without merging**
