### PR TITLE
Allow comment for na_ontap_svm

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Allow comment for na_ontap_svm

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
- na_ontap_svm.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]
shipit

**Review by JohnLieske — APPROVED** [review]
Looks good!

**Comment by gundalow** [comment]
rebuild_merge

**Comment by lonico** [comment]
close #50802

**Pull request merged**
