### PR TITLE
ssh connection plugin: Make comments more verbose

### PR DESCRIPTION
**Pull request by tyll**
Explain _communicate() more.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Note when testing -- this pull request says "explain communicate more" but also adds a ".close()"--  so it's not just docs, despite the description.

**Comment by tyll** [comment]
It only changes the comment to be before stdin.close() instead of being in the same line

**Comment by mpdehaan** [comment]
Oh ok, good deal, thanks for pointing out.

**Comment by mpdehaan** [comment]
merged, thank you!

**Pull request merged**
