### PR TITLE
Properly JSON encode AnsibleUnsafe, using a pre-processor

### LINKED ISSUE #47295: Unsafe values not marked as unsafe by JSON encoder, ansible-inventory
##### SUMMARY
Unsafe host variables are returned as safe variables when passed via `ansible-inventory`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/lib/ansible/parsing/ajson.py

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.11 (default, Oct 17 2016, 14:59:40) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT
N/A, applies on control machine

##### STEPS TO REPRODUCE
The full file structure is provided at: https://github.com/AlanCoding/Ansible-inventory-file-examples/tree/master/issues/AWX1954

```yaml
ansible-inventory -i issues/AWX1954/hosts.ini --list --export
```

Where related file contents are:

```
tree issues/AWX1954/
issues/AWX1954/
├── README.md
├── group_vars
│   └── all.yml
├── host_vars
│   └── hello_world.yml
├── hosts.ini
├── playbook_dir
│   └── run.yml
├── premature_templating.retry
├── premature_templating.yml
└── run.yml
```

```
cat issues/AWX1954/hosts.ini
hello_world ansible_connection=local
```

```
cat issues/AWX1954/host_vars/hello_world.yml 
host_var_unsafe: !unsafe '{#NOTACOMMENT#}'
```

To reproduce this directly, for purposes of unit tests:

```python
from ansible.parsing.ajson import AnsibleJSONEncoder
from ansible.parsing.yaml.loader import AnsibleLoader
import json

data = "host_var_unsafe: !unsafe '{#NOTACOMMENT#}'"
python_dict = AnsibleLoader(data).get_single_data()
print(type(python_dict['host_var_unsafe']))
print(json.dumps(python_dict, sort_keys=True, cls=AnsibleJSONEncoder))
```

##### EXPECTED RESULTS
Inside of the output from `ansible-inventory`, I expect to find

```json
host_var_unsafe: {
  "__ansible_unsafe": "{#NOTACOMMENT#}"
}
```

The python script should print content that also contains this syntax.

##### ACTUAL RESULTS

```json
ansible-inventory -i issues/AWX1954/hosts.ini --list --export
{
    "_meta": {
        "hostvars": {
            "hello_world": {
                "ansible_connection": "local", 
                "host_var_unsafe": "{#NOTACOMMENT#}"
            }
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ], 
        "vars": {
            "awx1954_comment": "{#NOTACOMMENT#}", 
            "awx1954_dict": {
                "comment": "{#NOTACOMMENT#}", 
                "expression": "{{NOTANEXPRESSION}}", 
                "statement": "{%NOTASTATEMENT%}", 
                "zabbix": "net.if.out[{#IFNAME}]"
            }, 
            "awx1954_expression": "{{NOTANEXPRESSION}}", 
            "awx1954_statement": "{%NOTASTATEMENT%}", 
            "awx1954_zabbix": "net.if.out[{#IFNAME}]"
        }
    }, 
    "ungrouped": {
        "hosts": [
            "hello_world"
        ]
    }
}
```

Specifically, `"host_var_unsafe": "{#NOTACOMMENT#}"`, although all the other group variables should also be marked as unsafe. The python script outputs:

```
<class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'>
{"host_var_unsafe": "{#NOTACOMMENT#}"}
```

This finding was originally reported at:

https://github.com/ansible/awx/issues/1954#issuecomment-430459962

by @jbartko, but there is also a distracting bug in those reproduction steps, where a templating error causes the playbook failure. No templating should be happening, because there are no safe host or group variables in this inventory.

Note, that if you test `isinstance(python_dict['host_var_unsafe'], AnsibleUnsafe)` in the script, it returns `True`. Because of that, we can say the problem isn't the logic here:

https://github.com/ansible/ansible/blob/b2ac74546121f6e3d6bffa7689f49d53698f511d/lib/ansible/parsing/ajson.py#L57-L59

The problem is more fundamental, in that this logic is never called. Sanity check - `isinstance(python_dict['host_var_unsafe'], basestring)` returns `True`.

Overriding the behavior of the python JSON encoder for string types is extremely unpleasant, so I decline from submitting a patch myself, because I believe the solution will require relatively fundamental reworking.

Also, note:

```
ansible-inventory -i issues/AWX1954/hosts.ini --list --export --yaml
```

Produces the bug as well. Although the specifics are extremely different, this also suggests that the YAML representer is not routing the representation logic correctly because Ansible unsafe objects are string-like.

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Properly JSON encode AnsibleUnsafe, using a pre-processor. Fixes #47295

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/parsing/ajson.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sivel** [comment]
cc @AlanCoding

**Comment by AlanCoding** [comment]
It looks like this is making some progress, in particular, I see variables marked unsafe in `ansible-inventory` output.

However, the full-full cycle seems to still not be working. I put my materials in https://github.com/AlanCoding/Ansible-inventory-file-examples/tree/master/issues/AWX1954. Most important is to run the playbook `issues/AWX1954/test_unsafe.yml`

```yaml
---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
    - debug:
        msg: "{{ awx1954_expression }}"
```

#### Testing devel

Before I get into any of that, here is running `devel` with the example inventory / vars in those materials.

```
ansible-playbook -i issues/AWX1954/hosts.ini issues/AWX1954/test_unsafe.yml

PLAY [all] ******************************************************************************************************************************************************

TASK [debug] ****************************************************************************************************************************************************
ok: [hello_world] => {
    "msg": "{{NOTANEXPRESSION}}"
}

PLAY RECAP ******************************************************************************************************************************************************
hello_world                : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Now, if I make the variable `awx1954_expression` no-longer-unsafe, via:

```diff
diff --git a/issues/AWX1954/group_vars/all.yml b/issues/AWX1954/group_vars/all.yml
index 5e92dc5..7b95e19 100644
--- a/issues/AWX1954/group_vars/all.yml
+++ b/issues/AWX1954/group_vars/all.yml
@@ -5,5 +5,5 @@ awx1954_dict:
   zabbix: !unsafe net.if.out[{#IFNAME}]
 awx1954_comment: !unsafe '{#NOTACOMMENT#}'
 awx1954_statement: !unsafe '{%NOTASTATEMENT%}'
-awx1954_expression: !unsafe '{{NOTANEXPRESSION}}'
+awx1954_expression: '{{NOTANEXPRESSION}}'
 awx1954_zabbix: !unsafe net.if.out[{#IFNAME}]
\ No newline at end of file
```

And run it again, I get:

```
ansible-playbook -i issues/AWX1954/hosts.ini issues/AWX1954/test_unsafe.yml

PLAY [all] ******************************************************************************************************************************************************

TASK [debug] ****************************************************************************************************************************************************
fatal: [hello_world]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'NOTANEXPRESSION' is undefined\n\nThe error appears to be in '/Users/alancoding/Documents/repos/ansible-inventory-file-examples/issues/AWX1954/test_unsafe.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug:\n      ^ here\n"}

PLAY RECAP ******************************************************************************************************************************************************
hello_world                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

Okay, fair enough. I believe that's expected and perfectly cool behavior.

#### Testing This

We want the unsafe vars expression in JSON (in the example materials, they are expressed in YAML), but it's also important that they are processed by Ansible into the native unsafe objects. Otherwise what's the point?

Here is testing this branch (with the original `!unsafe` version of `awx1954_expression`):

```
ansible-playbook -i issues/AWX1954/hosts.ini issues/AWX1954/test_unsafe.yml

PLAY [all] ******************************************************************************************************************************************************

TASK [debug] ****************************************************************************************************************************************************
ok: [hello_world] => {
    "msg": {
        "__ansible_unsafe": "{{NOTANEXPRESSION}}"
    }
}

PLAY RECAP ******************************************************************************************************************************************************
hello_world                : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Our requirement is a little more complicated, where we would like to dump with `ansible-inventory`, re-create a new script with the output from that, and then use this secondary inventory in the above command. That command is actually demonstrating that the YAML loading isn't working quite right. Anyway, it's likely that both cases would get fixed together.

**Comment by sivel** [comment]
@AlanCoding I have to admit, other than the callback incorrectly displaying `__ansible_unsafe`, I'm not sure I understand what additional problems you are having with YAML loading. As of now this PR is only dealing with JSON encoding and decoding.

Is it possible you could describe your YAML loading issue?

**Comment by AlanCoding** [comment]
What I was saying in my last example is that `"msg": "{{NOTANEXPRESSION}}"` is expected, as in the first example. This is a basic nuts & bolts example of how the user expects unsafe variables to work. For an unsafe string variable, it should echo the string, and it should not render the jinja2 template syntax.

Looks like the commit you just pushed fixed that.

```
ansible-playbook -i issues/AWX1954/hosts.ini issues/AWX1954/test_unsafe.yml

PLAY [all] **************************************************************************************************************************************************************************

TASK [debug] ************************************************************************************************************************************************************************
ok: [hello_world] => {
    "msg": "{{NOTANEXPRESSION}}"
}

PLAY RECAP **************************************************************************************************************************************************************************
hello_world                : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

(ran that on your updated branch)

**Comment by sivel** [comment]
Ok, great! I knew it was a problem yesterday, but hadn't attempted resolving it until this morning.

As of now, the ability to properly encode `AnsibleUnsafe` is limited to `ansible-inventory`, but I can add more later, now that the functionality is hidden behind and argument.

**Review by AlanCoding — APPROVED** [review]
Mainly reviewing via test cases of interest, and not really the code.

1) that current behavior passing in YAML host_vars is unchanged
2) that ansible-inventory dump, reprocessing, and using in ansible-playbook via a script that outputs JSON representation from ansible-inventory gives the same behavior as from (1), which is the AWX use case

With this evidence, I expect this will allow successful import of unsafe variables in AWX.

**Comment by sivel** [comment]
I'm looking at the possibility of moving the encoder/decoder to `module_utils`, but not sure if and what I'll do there.

The decoder has dependencies on `AnsibleVaultEncryptedUnicode` and `wrap_var`, so I'd need to create some way to inject those, as they would not be importable.  This could give us a BSD license, and allow for more flexible use of our JSON encoder and decoder.  However, this might be too much work at this point.

**Comment by AlanCoding** [comment]
You can just do what I did in that ansible-runner PR

```python
class AnsibleJSONEncoderLocal(json.JSONEncoder):
    '''
    The class AnsibleJSONEncoder exists in Ansible core for this function
    this performs a mostly identical function via duck typing
    '''

    def default(self, o):
        if getattr(o, 'yaml_tag', None) == '!vault':
            encrypted_form = o._ciphertext
            if isinstance(encrypted_form, bytes):
                encrypted_form = encrypted_form.decode('utf-8')
            return {'__ansible_vault': encrypted_form}
        elif isinstance(o, (datetime.date, datetime.datetime)):
            return o.isoformat()
        return super(AnsibleJSONEncoderLocal, self).default(o)
```

The data is coming from Ansible itself, so I'm not worried about some object just accidentally happening to have a misleading `yaml_tag`. In fact, I would prefer that you did this, because it would make our logic less susceptible to regressions.

**Comment by sivel** [comment]
> You can just do what I did in that ansible-runner PR

The encoder is the easy part.  To move the decoder along with the encoder will be complicated, if possible at all.

**Comment by AlanCoding** [comment]
oh right, that makes sense.

**Comment by sivel** [comment]
TODO: Get sign off for licensing change

**Comment by bcoca** [comment]
you have my permission

**Comment by sivel** [comment]
@mattclay you made modifications to `lib/ansible/parsing/ajson.py` do I have your permission to relicense under BSD-2-Clause?

**Comment by mattclay** [comment]
@sivel You have my permission.

**Comment by sivel** [comment]
And for the record, I'm the 3rd person had edited that file, so now were good. :)

**Review by bcoca — APPROVED** [review]

**Pull request merged**
