### PR TITLE
Add  dynamic Ansible inventory, based on information from Chef Server

### PR DESCRIPTION
**Pull request by UnderGreen**
##### SUMMARY
This Ansible inventory plugin generates groups based on chef_environment attribute.
With --host option it is possible to gel all information about node, which you can get with "knife node show NODE -l".
sen

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
plugins/inventory/chefserver.ini 
plugins/inventory/chefserver.py 

##### ANSIBLE VERSION
N/A

### CODE REVIEW

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
@UnderGreen CI failure for python 3.5:

```
2017-01-28 07:41:16 Run command: python3.5 -m compileall -fq -x /.tox/ .
2017-01-28 07:41:23 *** Error compiling './plugins/inventory/chefserver.py'...
2017-01-28 07:41:23 Sorry: TabError: inconsistent use of tabs and spaces in indentation (chefserver.py, line 60)
```

**Comment by jctanner** [comment]
@UnderGreen any chance you could fix the pep8 issues here?

**Comment by jimi-c** [comment]
Hi @UnderGreen, due to the fact that there has been no follow-up on this PR in quite a while, and also due to the fact that we recently enhanced the way we handle inventory plugins, we are going to close this for now. If you are still interested in submitting this (as there have been a few requests for this), we would be happy to consider it if it's updated to correct the issues noted above as well as being written for the new inventory plugin system.

Thanks!

**Pull request closed without merging**
