### PR TITLE
Fixes #35308

### LINKED ISSUE #35308: azure_rm_mysqldatabase integration test fails
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

azure_rm_mysqldatabase

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 8ea0bfe9a3) last updated 2018/01/24 10:27:23 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Shippable

##### SUMMARY

The `azure_rm_mysqldatabase` integration test fails and has been [disabled](https://github.com/ansible/ansible/commit/ebe925405c9b450488e42f46e3c009868a22dc76) in CI.

CI failure: https://app.shippable.com/github/ansible/ansible/runs/52072/53/tests

The error is `failure: Error creating the MySQL Server instance: Azure Error: StorageMbTooLow Message: The storage size of 2048 MB does not meet the minimum required storage of 51200 MB.`

##### STEPS TO REPRODUCE

Run the `azure_rm_mysqldatabase` on Shippable or locally with `ansible-test`:

`ansible-test integration azure_rm_mysqldatabase --docker -v`

##### EXPECTED RESULTS

Tests pass.

##### ACTUAL RESULTS

Tests fail.

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Fixes #35308 and similar issues with PostgreSQL

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
azure_rm_mysqlserver
azure_rm_mysqldatabase
azure_rm_postgresqlserver
azure_rm_postgresqldatabase

##### ANSIBLE VERSION
```
2.4.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by zikalino** [comment]
shipit

**Comment by yuwzho** [comment]
shipit

**Comment by zikalino** [comment]
@mattclay could you help merge it?
This fixes test issues and reenables tests for MySQL and PostgreSQL

I don't quite understand why out 2 shipits don't work here....

**Comment by zikalino** [comment]
@jborean93 could you check this?

**Comment by mattclay** [comment]
bot_status

**Pull request merged**
