### PR TITLE
[cloud] Bugfix for aws_s3 empty directory creation

### LINKED ISSUE #32144: S3 module stopped working in 2.4.1
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aws_s3 module

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /home/jwitkowski/throtle-ansible/ansible.cfg
  configured module search path = [u'/home/jwitkowski/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/ansible
  executable location = /home/jwitkowski/throtle-ansible-venv/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The same ansible code that worked in v2.3.2 to create S3 buckets no longer works in 2.4.1.  There is nothing fancy or tricky being done and I've tried to switch the module from the old "s3:" to the new "aws_s3:" to no avail.

##### STEPS TO REPRODUCE
```yaml
---
- name: Apply Service Roles to Instance
  hosts: local
  gather_facts: True
  vars:
    s3_buckets: ["test-bucket"]
    s3_iam_users: [ { name: "testUser", bucket: "test-bucket" } ]
    s3_path_suffixes: ['Download','Upload']
  environment:
    AWS_DEFAULT_REGION: "{{ region }}"
    AWS_ACCESS_KEY_ID: "{{ aws_access }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret }}"
  tasks:
    - name: S3 | Create AWS S3 buckets
      s3:
        bucket: "{{ item.0 }}"
        mode: create
        object: "{{ s3_path_prefix }}/{{ item.1.dir|default(item.1.name) }}/{{ item.2 }}/"
      with_nested:
        - "{{ s3_buckets }}"
        - "{{ s3_iam_users }}"
        - "{{ s3_path_suffixes }}"

    - name: S3 | Create AWS IAM user for S3
      iam:
        iam_type: user
        name: "{{ item.name }}"
        state: present
        access_key_state: create
      register: s3_user_creation
      with_items: "{{ s3_iam_users }}"

    - name: S3 | Attach Bucket policy to user
      iam_policy:
        iam_type: user
        iam_name: "{{ item.name }}"
        policy_name: "s3_partner_{{ item.name }}"
        state: present
        policy_json: "{{ lookup('template', 'vars/templates/s3_iam_policy.j2') }}"
      with_items: "{{ s3_iam_users }}"

    - debug:
        msg:
          - "***** SECRET KEY IS ONLY GIVEN ONCE *****"
          - "PLEASE TAKE NOTE:"
          - "    AWS_ACCESS_KEY: {{ item.user_meta.access_keys[0].access_key_id }}"
          - "    AWS_SECRET_KEY: {{ item.user_meta.access_keys[0].secret_access_key }}"
          - "*****************************************"
      with_items: "{{ s3_user_creation.results }}"
      when: item.user_meta is defined and s3_user_creation.changed
```

##### EXPECTED RESULTS
In ansible 2.3.2 the above runs without issue and creates the IAM user, bucket policy, and attaches the policy to the user with no issues.

##### ACTUAL RESULTS
in ansible 2.4.1 latest release:
```
Using module file /home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/ansible/modules/cloud/amazon/_s3.py
<localhost> EXEC /bin/sh -c 'AWS_DEFAULT_REGION=us-east-1 AWS_ACCESS_KEY_ID=AWS_SECRET_ACCESS_KEY= python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_aqikeG/ansible_module_s3.py", line 830, in <module>
    main()
  File "/tmp/ansible_aqikeG/ansible_module_s3.py", line 796, in main
    create_dirkey(module, s3, bucket, dirobj)
  File "/tmp/ansible_aqikeG/ansible_module_s3.py", line 378, in create_dirkey
    bucket = s3.Bucket(bucket)
  File "/home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/botocore/client.py", line 553, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'S3' object has no attribute 'Bucket'

failed: [localhost] (item=[u'throtle-data', {u'bucket': u'throtle-data', u'name': u'testing'}, u'Download']) => {
    "changed": false,
    "failed": true,
    "item": [
        "throtle-data",
        {
            "bucket": "throtle-data",
            "name": "testing"
        },
        "Download"
    ],
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_aqikeG/ansible_module_s3.py\", line 830, in <module>\n    main()\n  File \"/tmp/ansible_aqikeG/ansible_module_s3.py\", line 796, in main\n    create_dirkey(module, s3, bucket, dirobj)\n  File \"/tmp/ansible_aqikeG/ansible_module_s3.py\", line 378, in create_dirkey\n    bucket = s3.Bucket(bucket)\n  File \"/home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/botocore/client.py\", line 553, in __getattr__\n    self.__class__.__name__, item)\nAttributeError: 'S3' object has no attribute 'Bucket'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
Using module file /home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/ansible/modules/cloud/amazon/_s3.py
<localhost> EXEC /bin/sh -c 'AWS_DEFAULT_REGION=us-east-1 AWS_ACCESS_KEY_ID=AWS_SECRET_ACCESS_KEY= python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_AGetjO/ansible_module_s3.py", line 830, in <module>
    main()
  File "/tmp/ansible_AGetjO/ansible_module_s3.py", line 796, in main
    create_dirkey(module, s3, bucket, dirobj)
  File "/tmp/ansible_AGetjO/ansible_module_s3.py", line 378, in create_dirkey
    bucket = s3.Bucket(bucket)
  File "/home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/botocore/client.py", line 553, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'S3' object has no attribute 'Bucket'

failed: [localhost] (item=[u'throtle-data', {u'bucket': u'throtle-data', u'name': u'testing'}, u'Upload']) => {
    "changed": false,
    "failed": true,
    "item": [
        "throtle-data",
        {
            "bucket": "throtle-data",
            "name": "testing"
        },
        "Upload"
    ],
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_AGetjO/ansible_module_s3.py\", line 830, in <module>\n    main()\n  File \"/tmp/ansible_AGetjO/ansible_module_s3.py\", line 796, in main\n    create_dirkey(module, s3, bucket, dirobj)\n  File \"/tmp/ansible_AGetjO/ansible_module_s3.py\", line 378, in create_dirkey\n    bucket = s3.Bucket(bucket)\n  File \"/home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/botocore/client.py\", line 553, in __getattr__\n    self.__class__.__name__, item)\nAttributeError: 'S3' object has no attribute 'Bucket'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

```

### PR DESCRIPTION
**Pull request by ryansb**
##### SUMMARY

Closes #32144 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

aws_s3

##### ANSIBLE VERSION

```
ansible 2.5.0 (s3-empty-dir-fix a5dfb6744a) last updated 2017/10/25 16:37:02 (GMT -400)
  config file = None
  configured module search path = [u'/home/ryansb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible/lib/ansible
  executable location = /tmp/ansible/bin/ansible
  python version = 2.7.12 (default, Sep 27 2016, 18:08:33) [GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
```

##### ADDITIONAL INFORMATION

```
---
- name: Apply Service Roles to Instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    s3_buckets: ["ryansb-test-bucket"]
    s3_iam_users: [ { name: "testUser", bucket: "test-bucket" } ]
    s3_path_suffixes: ['Download','Upload']
    s3_path_prefix: 'bar'
  tasks:
    - s3_bucket:
        name: "{{ item }}"
      with_items: "{{ s3_buckets }}"
    - name: S3 | Create AWS S3 buckets
      s3:
        bucket: "{{ item.0 }}"
        mode: create
        object: "{{ s3_path_prefix }}/{{ item.1.dir|default(item.1.name) }}/{{ item.2 }}/"
      with_nested:
        - "{{ s3_buckets }}"
        - "{{ s3_iam_users }}"
        - "{{ s3_path_suffixes }}"
```

### CODE REVIEW

**Comment by ryansb** [comment]
@mattclay it seems like these tests aren't running in shippable yet.

**Comment by mattclay** [comment]
The tests have the wrong alias which is why they're being skipped: https://github.com/ansible/ansible/blob/11153df0a10daa1e3fac234ef5b3d89deef3d256/test/integration/targets/aws_s3/aliases#L2

I'll add a sanity check to catch this in the future (and fix the alias at the same time, assuming it isn't fixed by the time I submit my PR).

**Review by willthames — APPROVED** [review]
LGTM, good to merge once tests run and pass.

**Comment by ryansb** [comment]
@mattclay added the proper group & the additional integration tests pass now.

**Review by s-hertel — APPROVED** [review]

**Pull request merged**
