### PR TITLE
ec2_group: fix regression for targets that are a list containing strings and lists

### LINKED ISSUE #45580: ec2_group rules cidr_ip dosent' accept list of lists
##### SUMMARY

In Ansinble 2.6 This module in the cidr_ip parameter, fails when passed a list of other vars that are also a list.
This was working in 2.5 just fine, and also in previous version I think 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_group
##### ANSIBLE VERSION

```paste below
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gabriel.diaz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Just a custom vault file

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core)
##### STEPS TO REPRODUCE

Run the following playbook with ansible 2.5:

```bash
$ ansible --version
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gabriel.diaz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
[gabriel.diaz@ansible-dev2-qa-38f11:~/devops/ansible_v2]$ ansible-playbook -vvv dashboard.yml -e "region=sa-east-1 account=dev2 youse_environment=qa"
```

```yaml
---
- name: example playbook
  hosts: "{{ hosts }}"
  vars:
    officevpn:
      - 10.40.0.0/21
    partners:
      - 180.0.7.0/25
  tasks:
    - name: test
      ec2_group:
        name: example2
        description: an example2 EC2 group
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports: 5665
            cidr_ip:
              - 172.16.1.0/24
              - 172.16.17.0/24
              - "{{ officevpn }}"
              - "{{ partners }}"
 
```

It will run fine:
```
TASK [test] ***********************************************************************************************************************************************************************************************************************************************************************
task path: /home/gabriel.diaz/devops/ansible_v2/z_testing.yml:19
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/amazon/ec2_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: gabriel.diaz
<127.0.0.1> EXEC /bin/sh -c 'echo ~gabriel.diaz && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781208.76-56674509948283 `" && echo ansible-tmp-1536781208.76-56674509948283="` echo /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781208.76-56674509948283 `" ) && sleep 0'
<127.0.0.1> PUT /home/gabriel.diaz/.ansible/tmp/ansible-local-16257fW7Mx1/tmpM5rx70 TO /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781208.76-56674509948283/ec2_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781208.76-56674509948283/ /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781208.76-56674509948283/ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781208.76-56674509948283/ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781208.76-56674509948283/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "description": "an example2 EC2 group",
    "group_id": "sg-0ae4c6d06903613ba",
    "group_name": "example2",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "an example2 EC2 group",
            "ec2_url": null,
            "group_id": null,
            "name": "example2",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "purge_tags": true,
            "region": "sa-east-1",
            "rules": [
                {
                    "cidr_ip": [
                        "172.16.1.0/24",
                        "172.16.17.0/24",
                        [
                            "10.40.0.0/21"
                        ],
                        [
                            "187.50.107.0/25"
                        ]
                    ],
                    "ports": 5665,
                    "proto": "tcp"
                }
            ],
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "tags": null,
            "validate_certs": true,
            "vpc_id": "vpc-11db5c75"
        }
    },
    "ip_permissions": [
        {
            "from_port": 5665,
            "ip_protocol": "tcp",
            "ip_ranges": [
                {
                    "cidr_ip": "172.16.17.0/24"
                },
                {
                    "cidr_ip": "10.40.0.0/21"
                },
                {
                    "cidr_ip": "172.16.1.0/24"
                },
                {
                    "cidr_ip": "187.50.107.0/25"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "to_port": 5665,
            "user_id_group_pairs": []
        }
    ],
    "ip_permissions_egress": [
        {
            "ip_protocol": "-1",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "user_id_group_pairs": []
        }
    ],
    "owner_id": "760223459084",
    "tags": {},
    "vpc_id": "vpc-11db5c75"
}
```

if we run the same playbook  after update Ansible:
```bash
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gabriel.diaz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

It will break
```
TASK [test] ***********************************************************************************************************************************************************************************************************************************************************************
task path: /home/gabriel.diaz/devops/ansible_v2/z_testing.yml:19
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: gabriel.diaz
<127.0.0.1> EXEC /bin/sh -c 'echo ~gabriel.diaz && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781295.95-200790050988223 `" && echo ansible-tmp-1536781295.95-200790050988223="` echo /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781295.95-200790050988223 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/amazon/ec2_group.py
<127.0.0.1> PUT /home/gabriel.diaz/.ansible/tmp/ansible-local-16546VGAfxp/tmpXU09PJ TO /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781295.95-200790050988223/ec2_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781295.95-200790050988223/ /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781295.95-200790050988223/ec2_group.py && sleep 0'

▽
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781295.95-200790050988223/ec2_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/gabriel.diaz/.ansible/tmp/ansible-tmp-1536781295.95-200790050988223/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_NjkQGc/ansible_module_ec2_group.py", line 1021, in <module>
    main()
  File "/tmp/ansible_NjkQGc/ansible_module_ec2_group.py", line 940, in main
    module, client, rule, name, group, groups, vpc_id)
  File "/tmp/ansible_NjkQGc/ansible_module_ec2_group.py", line 557, in get_target_from_rule
    return 'ipv4', validate_ip(module, rule['cidr_ip']), False
  File "/tmp/ansible_NjkQGc/ansible_module_ec2_group.py", line 709, in validate_ip
    split_addr = cidr_ip.split('/')
AttributeError: 'list' object has no attribute 'split'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NjkQGc/ansible_module_ec2_group.py\", line 1021, in <module>\n    main()\n  File \"/tmp/ansible_NjkQGc/ansible_module_ec2_group.py\", line 940, in main\n    module, client, rule, name, group, groups, vpc_id)\n  File \"/tmp/ansible_NjkQGc/ansible_module_ec2_group.py\", line 557, in get_target_from_rule\n    return 'ipv4', validate_ip(module, rule['cidr_ip']), False\n  File \"/tmp/ansible_NjkQGc/ansible_module_ec2_group.py\", line 709, in validate_ip\n    split_addr = cidr_ip.split('/')\nAttributeError: 'list' object has no attribute 'split'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

##### EXPECTED RESULTS

Should work, or documentation should inform that this is no loger supported

##### ACTUAL RESULTS

Showed in example

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Fix targets that may be a list containing strings and lists which worked prior to 2.6. Also added diff mode support for lists of targets containing strings and lists.

Fixes #45580 
This should probably be backported (but will not cp cleanly since diff mode has been added)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION
```
2.8
```

### CODE REVIEW

**Comment by GaboFDC** [comment]
Hello, I reported #45580
Thanks for the quick work on this.
From what I saw in the description, after this being added to 2.8, it will probably be backported (if possible)
So I'm just wondering if is there any estimated on how much time will this take?
I'm not hurrying things up, I just wanna know the estimated time, since this affects my migration from 2.5 to 2.6 I wanna know if i should wait for the backport to be ready, or make some workaround or something else.

**Comment by s-hertel** [comment]
Hi, @GaboFDC. I believe the next 2.6.x release is (probably) September 27th. For a workaround, you could override Ansible 2.6's ec2_group by adding the fixed ec2_group.py to a `library` directory relative to your playbook (the path is also configurable).

**Comment by s-hertel** [comment]
/me separated commits to make cherry-picking to 2.6 easier

**Comment by s-hertel** [comment]
Separated commits to make cherry-picking to 2.6 easier.

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
Before backport, we also need to add a changelog fragment. Otherwise, LGTM and the tests pass on my end

**Comment by s-hertel** [comment]
I had to rebase to re-separate my commits because I had missed a line in the initial commit (to backport) that was still modifying diff mode. Also added changelog and I renamed the new test file to `multi_nested_target` since `multi_target` doesn't explain the bug well. Integration tests still passing for me, no overall code change.

**Pull request merged**
