### PR TITLE
Check login_token for user before any operations

### LINKED ISSUE #23033: When using - gitlab_user_module - Auth token is not checked and error message is garbage
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

https://docs.ansible.com/ansible/gitlab_user_module.html

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = ./ansible.cfg
  configured module search path = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609
```

##### SUMMARY

When using gitlab_user_module - module with an expired gitlab token, there is seemingly no check performed to see if the token exists or even has any permissions. As such when it gets to trying to creating a user it starts spewing python errors about data types rather than a real error message about the authentication token being bad. 

##### STEPS TO REPRODUCE

```example.yaml

- hosts: host1
   gather_facts: no
   tasks:
     - name: Create Gitlab User
       gitlab_user:
         server_url: "https://{{ gitlab_url }}"
         validate_certs: false
         login_token: "{{ gitlab_token }}"
         name: "{{ etckeeper_username }}"
         username: "{{ etckeeper_username }}"
         password: "{{ etckeeper_password }}"
         email: blackhole@email.com
         group: "{{ group_name }}"
         sshkey_name: "etckeeper_key"
         sshkey_file: "{{ etckeeper_ssh-rsa_key }}"
         state: present
  delegate_to: localhost
 
```

##### EXPECTED RESULTS
Error saying authentication token is expired or bad. 

##### ACTUAL RESULTS

```
TASK [etckeeper_install : Create Gitlab User] *************************************************************************************************************************************
task path: /home/user/ansible_test/roles-dev/etckeeper_install/tasks/configure.yml:27
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/source_control/gitlab_user.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-klqjckwtlzoeoaouulmnuumwdfbrsqdj; /usr/bin/python'"'"' && sleep 0'
fatal: [bios -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_vIiKET/ansible_module_gitlab_user.py\", line 359, in <module>\n    main()\n  File \"/tmp/ansible_vIiKET/ansible_module_gitlab_user.py\", line 347, in main\n    if not user.existsUser(user_username) and state == \"absent\":\n  File \"/tmp/ansible_vIiKET/ansible_module_gitlab_user.py\", line 226, in existsUser\n    for user in found_user:\nTypeError: 'bool' object is not iterable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix adds extra check if user is authorized or not while
using login_token.

Fixes #23033

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/source_control/gitlab_user.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by dj-wasabi** [comment]
shipit

**Comment by Jmainguy** [comment]
I have not tested, but the logic looks good to my eyeballs

**Comment by bjolivot** [comment]
great work :)
shipit

**Comment by Akasurde** [comment]
@gundalow @bjolivot @Jmainguy @dj-wasabi Thanks.

**Pull request merged**
