### PR TITLE
Fixed mysql_user idempotency for long privilege lists. (Fixes #68044)

### LINKED ISSUE #68044: mysql_user not idempotent for long grant lists
##### SUMMARY
`mysql_user` is not idempotent for long grant lists (ie an example):
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for replication_admin@%                                                                                                                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT SELECT, RELOAD, SHUTDOWN, PROCESS, FILE, SUPER, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER ON *.* TO `replication_admin`@`%` |
| GRANT BACKUP_ADMIN,CLONE_ADMIN,PERSIST_RO_VARIABLES_ADMIN,SYSTEM_VARIABLES_ADMIN ON *.* TO `replication_admin`@`%` WITH GRANT OPTION                |
| GRANT INSERT, UPDATE, DELETE ON `mysql`.* TO `replication_admin`@`%` WITH GRANT OPTION                                                              |
| GRANT ALL PRIVILEGES ON `mysql_innodb_cluster_metadata`.* TO `replication_admin`@`%` WITH GRANT OPTION                                              |
| GRANT ALL PRIVILEGES ON `mysql_innodb_cluster_metadata_bkp`.* TO `replication_admin`@`%` WITH GRANT OPTION                                          |
| GRANT ALL PRIVILEGES ON `mysql_innodb_cluster_metadata_previous`.* TO `replication_admin`@`%` WITH GRANT OPTION                                     |
+-----------------------------------------------------------------------------------------------------------------------------------------------------+
```
You can see that on the second line the grants are not split by `, ` but just `,`. This means https://github.com/ansible/ansible/blob/35996e57abba1f40abb493379d5cbe2dd90e65c3/lib/ansible/modules/database/mysql/mysql_user.py#L572 fails (it also only take one db line into account)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = None
  configured module search path = ['/home/florian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/florian/.local/pipx/venvs/ansible/lib64/python3.7/site-packages/ansible
  executable location = /home/florian/.local/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### STEPS TO REPRODUCE

Pullrequest with integration test: https://github.com/ansible/ansible/pull/68045

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by apollo13**
##### SUMMARY
Fixes #68044

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
mysql_user

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by Andersson007 — CHANGES_REQUESTED** [review]
LGTM @apollo13 thanks for fixing this!
one more thing - a changelog fragment https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs

**Comment by apollo13** [comment]
Done, shipable seems to have a flaky job :/

**Comment by apollo13** [comment]
Closing in favor of ansible-collections/community.general#58

**Comment by Andersson007** [comment]
thank you!

**Pull request closed without merging**
