### PR TITLE
Deprecate STRING_CONVERSION_ACTION

### PR DESCRIPTION
**Pull request by mkrizek**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`lib/ansible/config/base.yml`

### CODE REVIEW

**Comment by mattclay** [comment]
This should go through a deprecation cycle before being removed.

**Comment by sivel** [comment]
I just checked the `ansible==6.4.0` package to see if there were any collections using this, and unfortunately there are

```
ansible_collections/community/crypto/plugins/plugin_utils/action_module.py
119:        self._string_conversion_action = C.STRING_CONVERSION_ACTION
448:        allow_conversion = opts.get(self._string_conversion_action, True)
463:            if self._string_conversion_action == 'error':
466:            elif self._string_conversion_action == 'warn':

ansible_collections/community/sops/plugins/plugin_utils/action_module.py
119:        self._string_conversion_action = C.STRING_CONVERSION_ACTION
448:        allow_conversion = opts.get(self._string_conversion_action, True)
463:            if self._string_conversion_action == 'error':
466:            elif self._string_conversion_action == 'warn':
```

**Comment by felixfontein** [comment]
I was about to say, I didn't see a deprecation for this, and then I saw Matt's comment :)

The ironic part is that line 119 stores the value of the constant for code that is only run for ansible-base 2.10 / Ansible 2.9; for ansible-core 2.11+, `ArgumentSpecValidator` is used instead of the vendored code. I'll change that so that the constant is only read for these versions as well...

**Comment by felixfontein** [comment]
I created new releases of community.crypto and community.sops which no longer rely on this constant being present (except for ansible-base 2.10 / Ansible 2.9, where this isn't a problem). I would still prefer if this isn't backported to stable-2.13 or before, or if possible even not to stable-2.14, since sometimes users are a lot slower to upgrade collections than ansible-core.

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
