### PR TITLE
Enables 'force basic auth' -feature globally

### PR DESCRIPTION
**Pull request by woltage**
Small refactor which helps modules to use force_basic_auth param, when calling fetch_url method.

With this patch get_url -module gets force_basic_auth feature too. See PR of the core modules too.

### CODE REVIEW

**Comment by misho-kr** [comment]
While waiting for this PR to be merged, here is a docker image **ansible-force-basic-auth** based on official ansible image that has these code changes integrated:

https://registry.hub.docker.com/u/misho1kr/ansible-force-basic-auth/

**Comment by woltage** [comment]
Any progress?

**Comment by bcoca** [comment]
needs a rebase

**Comment by woltage** [comment]
@bcoca: I rebased it and it's ready for merge.

**Pull request merged**
