### PR TITLE
Auth0 modules

### PR DESCRIPTION
**Pull request by haad**
ISSUE TYPE

    Feature Pull Request

SUMMARY

Add modules for managing auth0 domains/users.

### CODE REVIEW

**Comment by mattclay** [comment]
@haad CI failure due to:

```
2017-01-15 22:11:51 iteritems has been removed in python3.  Alternatives:
2017-01-15 22:11:51     for KEY, VALUE in DICT.items():
2017-01-15 22:11:51     from ansible.module_utils.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-01-15 22:11:51     from ansible.compat.six import iteritems ; for KEY, VALUE in iteritems(DICT):
2017-01-15 22:11:51 ./lib/ansible/modules/remote_management/hpilo/hpilo_facts.py:        for cpu, details in memory_details_summary.iteritems():
```

**Comment by mattclay** [comment]
@haad I'm guessing those `hpilo` files were intended for a different PR (#20273).

**Comment by mattclay** [comment]
CI failure due to PEP 8 indentation issues:

```
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:123:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:127:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:131:15: E126 continuation line over-indented for hanging indent (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:138:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:141:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:145:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:146:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:148:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:149:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:152:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:155:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user.py:157:7: E111 indentation is not a multiple of four (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user_facts.py:85:15: E126 continuation line over-indented for hanging indent (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user_facts.py:90:7: E121 continuation line under-indented for hanging indent (current)
2017-02-05 13:03:17 ERROR: PEP 8: lib/ansible/modules/web_infrastructure/auth0_user_facts.py:99:7: E111 indentation is not a multiple of four (current)
```

**Comment by mattclay** [comment]
CI failure in module validation:

```
2017-02-25 14:14:22 ============================================================================
2017-02-25 14:14:22 lib/ansible/modules/web_infrastructure/auth0_user.py
2017-02-25 14:14:22 ============================================================================
2017-02-25 14:14:22 ERROR:203:requests import found, should use ansible.module_utils.urls instead
2017-02-25 14:14:22 
2017-02-25 14:14:22 ============================================================================
2017-02-25 14:14:22 lib/ansible/modules/web_infrastructure/auth0_user_facts.py
2017-02-25 14:14:22 ============================================================================
2017-02-25 14:14:22 ERROR:203:requests import found, should use ansible.module_utils.urls instead
```

**Comment by haad** [comment]
I know about this. What is proper way to import requests library in a ansible module ?

**Comment by mattclay** [comment]
Is there a reason you can't use `ansible.module_utils.urls` instead of `requests`?

**Comment by haad** [comment]
As there are already modules using requests in a tree I would prefer to keep it as it is. Rather than to rewrite it to use ansible url utils.

**Comment by mattclay** [comment]
New modules should use `ansible.module_utils.urls`. Existing modules using `requests` are permitted until they can updated. The rationale for using `ansible.module_utils.urls` is here:

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L92

**Pull request closed without merging**
