### PR TITLE
Bigip pool

### PR DESCRIPTION
**Pull request by jmcgill298**
##### SUMMARY

Update F5 bigip_pool to fix 2 bugs:
1. module raises error when len(monitors) = 1, but should only require monitor_type when C(monitors) > 1
2. module did not properly handle the existing values of monitor.
  * parameters use "monitors" but F5 GET returns "monitor", so comparison was not being made
  * F5 GET returns a trailing space that is not accounted for in the list to string conversion.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

bigip_pool
##### ANSIBLE VERSION

```
2.4.0.0
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
  F5 versoin = BIG-IP 12.1.1 Build 0.0.184
```

##### ADDITIONAL INFORMATION

```
choices: ['and_list', 'm_of_n', 'single']
  *Add support for Monitory Type "single"

updatables = [
    'quorum', 'monitor', 'service_down_action', 'description',
    'lb_method', 'slow_ramp_time', 'reselect_tries', 'host', 'port'
]
  * Change "monitors" to "monitor" which is used by both self.want and self.have.
  * Remove "monitor_type" from updatables as that seems to be an attribute based on how many monitors are configured and if quorum is used. This is also not returned in GET request for the existing configuration, which causes idempotency issues when doing a diff.

if monitor_list is not None and len(monitor_list) == 1:
    pass
  * Add check for monitor_list being a len of 1 to meet expectations outlined in docstring that states C(monitor_type) is only required of C(monitor_list) is greater than 1.

if self._values['monitor']:
    result = self._values['monitor']
  * Add check for monitor value which is returned by the GET request.
  * In addition to returning the correct value for the self.have, this bypasses the list to string conversion that is not needed for the existing configuration.

if monitor_type == 'm_of_n':
    ...
else:
    ...
  * Reverse the order to allow for monitory_types "single" and "and_list", and None to use the same logic.

try:
    # python 2
    if isinstance(attr2, unicode):
        attr2 = attr2.strip()
except:
    # python 3
    if isinstance(attr2, str):
        attr2 = attr2.strip()
  * Strip empty white space, which is present for existing monitor(s)

'and_list', 'm_of_n', 'single'
  * add "single" option to argument_spec
```

### CODE REVIEW

**Comment by jmcgill298** [comment]
@itdependsnetworks @caphrim007 Initial PR to provide fixes to bigip_pool module. Two issues I had using this today were:
1) The module did not support monitor_type of single
2) The module was not idempotent because existing monitor_type is not returned and therefore None, and monitors is returned as monitor by the API and therefore monitors is also None. I also noticed that the API returns a trailing space that needed to be removed for accurate comparison.

**Comment by caphrim007** [comment]
@jmcgill298 would you please raise this issue and PR here https://github.com/F5Networks/f5-ansible and additionally verify if the module at the aforementioned repository does not already meet your needs?

**Comment by jmcgill298** [comment]
@caphrim007 The F5 module is considerably different from these, so the changes are not identical in the F5 repo request

https://github.com/F5Networks/f5-ansible/pull/339

**Comment by caphrim007** [comment]
@jmcgill298 that's fine. the f5-ansible bigip_pool will be upstreamed as part of F5's normal upstream process now that the ansible development window is open again.

**Comment by mattclay** [comment]
CI failure in unit tests (in addition to already noted sanity test failure):

```
>       assert results['monitors'] == ['/Common/http', '/Common/tcp']
E       KeyError: 'monitors'

test/units/modules/network/f5/test_bigip_pool.py:455: KeyError
```

**Comment by caphrim007** [comment]
@mattclay please close this. we're handling it in the f5-ansible repository.

**Pull request closed without merging**
