### PR TITLE
Move redudant check_ip_addr method to common ce

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/ce.py
lib/ansible/modules/network/cloudengine/ce_aaa_server_host.py
lib/ansible/modules/network/cloudengine/ce_acl.py
lib/ansible/modules/network/cloudengine/ce_acl_advance.py
lib/ansible/modules/network/cloudengine/ce_bgp_af.py
lib/ansible/modules/network/cloudengine/ce_bgp_neighbor.py
lib/ansible/modules/network/cloudengine/ce_bgp_neighbor_af.py
lib/ansible/modules/network/cloudengine/ce_info_center_global.py
lib/ansible/modules/network/cloudengine/ce_sflow.py
lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py

##### ANSIBLE VERSION

```
2.4 devel
```

### CODE REVIEW

**Comment by gundalow** [comment]
@QijunPan Could you please take a look at this when you get a chance, thanks

**Comment by QijunPan** [comment]
I think it's OK， thanks.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel`, thanks

**Comment by Akasurde** [comment]
@gundalow @QijunPan Thanks

**Pull request merged**
