### PR TITLE
Added nova_facts

### PR DESCRIPTION
**Pull request by CaptTofu**
Hi there! So, I needed nova_facts as well as docker_facts (another pull request). works perfectly and pep8-a-steptic

### CODE REVIEW

**Comment by mpdehaan** [comment]
So my usual question when all fact modules come up that I must ask - can we source these variables easily from the inventory script and avoid needing the facts module?

**Comment by CaptTofu** [comment]
Michael,

Me and others on Monty’s team discussed this a few weeks ago and as useful as the dynamic inventory plugin is, it’s so much easier to have access to them using a facts module from within a playbook so as to have a means to do some useful things. Also, we may not always run plays to manage a fleet of instances using the inventory plugin hence where this facts module comes in handy. The others I’ve CC’d can also explain where it’s useful to them.

Thanks,

Patrick

**Comment by emonty** [comment]
I agree with @mpdehaan for the most part - doing things as host_vars in the inventory is 1000000 times better, and if you are using nova_inventory, then this is completely and utterly pointless. However, there are times when you aren't using nova_inventory but the facts that nova_inventory would have injected into host_vars would still be useful for you. As a specific example, in our Infra systems, we're still using puppet (tons of existing code, migrating off all at once would be super painful) We're stepping one piece at a time towards using nova_inventory, but at the moment, we're using a local inventory module that queries the puppet cert list for machines. For us there, being able to call nova_facts without having to migrate fully to nova_inventory could be helpful.

I'd _actually_ like to take a pass through and make the  metadata reading that's used in nova_inventory librified so that the host_vars and the facts module produce exactly the same thing - but I haven't gotten around to that - I figured I'd get to that once the inventory patch landed.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
