### PR TITLE
added datetime type to argspec fix#31017

### PR DESCRIPTION
**Pull request by Jeyanthinath**
Adding datetime option to argspec

##### ISSUE TYPE
 - Feature Pull Request
issue - #31017

##### COMPONENT NAME
module_utils/basic.py

##### ANSIBLE VERSION
```
ansible 2.5.0 (argspec_datetime ca99ff80dd) last updated 2017/09/30 20:42:18 (GMT +550)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jeyanthinath/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jeyanthinath/Documents/git/ansible/lib/ansible
  executable location = /home/jeyanthinath/Documents/git/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by sivel** [comment]
dateutil is not in the standard library, and it’s import here is not protected by a try/except.

Additionally since this is going to be core functionality, it can’t rely on a non standard library module.

I’d recommend requiring a specific date format.  The best bet is one that matches YAML date format parsing.

http://yaml.org/type/timestamp.html

**Comment by Jeyanthinath** [comment]
@sivel but in this approach , I feel only now `datetime.datetime` format can be supported instead of simple string. This will give extra efforts to the end-user !

**Comment by sivel** [comment]
I understand your concern, unfortunately as I mention, a solution requiring no 3rd party modules will be required.  Likely you’ll need to implement the regex from that doc I mention and create a date time from the match using datetime.datetime

**Comment by bcoca** [comment]
@Jeyanthinath I agree with @sivel here, we don't want to force all targets that have modules using this feature to also require extra libraries.

**Comment by sivel** [comment]
This is the exact regex from pyyaml: https://github.com/yaml/pyyaml/blob/master/lib/yaml/constructor.py#L292-L332

We can't rely on pyyaml remotely either, as pyyaml isn't a minimum dependency for targets.

**Comment by Jeyanthinath** [comment]
@sivel can you review my changes

**Comment by sivel** [comment]
I do have a few concerns/questions.  The code in pyyaml is licensed as MIT.  The code in basic.py is licensed BSD.

I don't know whether it is permitted to simply copy and paste the code from pyyaml into ansible.module_utils.basic

Also, and this is a question for @bcoca what are our plans for importable type functions?  I know we can already specify a callable as the type.  Is it feasible that we continue adding these as string types that get mapped to a callable, or should we think about making new filters callables by default, and having the modules import them?

Also, we may need to have some questions surrounding the legality above.

**Comment by bcoca** [comment]
IANAL, so we'll have to find one to answer the license legality issue.

as for 'callable' i was under the impression that we were removing that type.

**Comment by sivel** [comment]
> as for 'callable' i was under the impression that we were removing that type

Interesting, because I know we were looking to add types that we didn't consider part of the core features, that may or may not require 3rd party libraries, specifically around network modules.  And that was the recommended approach we gave the other user.  I am fine either way, I was just making sure we didn't grow that class too much. (https://github.com/ansible/ansible/pull/17731)

**Comment by mattclay** [comment]
CI failure in integration tests. Most appear to be due to syntax errors reported by the sanity tests:

```
lib/ansible/module_utils/basic.py:192:376: SyntaxError: ur'''^(?P[0-9][0-9][0-9][0-9])
```

**Comment by Jeyanthinath** [comment]
@sivel I also looked have the same license concern ! Shall I rewrite the entire code of my own instead of using that pyyaml code ?

@mattclay I will check on this and update , but ironically code is running for me :thinking: , May be I am missing something over there

**Comment by mattclay** [comment]
@Jeyanthinath The syntax errors are on Python 3.x only, so make sure you're testing that.

**Comment by Jeyanthinath** [comment]
@mattclay as Licensing concern pointed out by @sivel , shall I re-write the code from scratch to support those ? or is it ok to go with the code from pyyaml library ?

**Comment by sivel** [comment]
It's likely going to take a while to get legal verification about inclusion.

I'd advise great care if you do plan to rewrite.

**Comment by sivel** [comment]
I've contacted the FSF, and confirmed that the BSD license (the license of basic.py) and the MIT license are compatible, and that you can copy part or whole of a MIT licensed file into a BSD licensed file, but must retain the copyright notice of the MIT file.  You will need to reference in the docstring the copyright of that function, as well as site where it came from.

Someone from Red Hat may need to validate this as well.  I suppose effectively it's on them ultimately.

**Comment by abadger** [comment]
@sivel, yep, the ideas in https://github.com/ansible/ansible/pull/17731 are still the plan.  Talked to bcoca on slack to clarify that.

**Comment by maxamillion** [comment]
Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are that we don't currently see enough demand for this functionality to justify the level of complexity that this introduces along with the potential legal ramifications.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
