### PR TITLE
Update AWS guides with new SDK and Python requirements

### PR DESCRIPTION
**Pull request by jillr**
##### SUMMARY

The 2.0 collection releases will introduce new Python requirements and a new SDK support policy

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/platforms/aws_guidelines.rst
docs/docsite/rst/scenario_guides/guide_aws.rst

### CODE REVIEW

**Comment by jillr** [comment]
cc @tremble

**Review by Akasurde — APPROVED** [review]
LGTM

**Review by tremble — APPROVED** [review]
LGTM

**Review by samccann — APPROVED** [review]

**Comment by acozine** [comment]
Changes incorporated into https://github.com/ansible-collections/amazon.aws/pull/362/files.

**Pull request merged**
