### PR TITLE
New module to setup network object.

### PR DESCRIPTION
**Pull request by grastogi23**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

avi.avi_network

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = [u'/home/grastogi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/grastogi/ansible2.3/local/lib/python2.7/site-packages/ansible
  executable location = /home/grastogi/ansible2.3/bin/ansible
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

##### SUMMARY

New module to setup network object.

```

```

### CODE REVIEW

**Comment by khaltore** [comment]
shipit

**Comment by ericsysmin** [comment]
shipit

**Comment by ericsysmin** [comment]
shipit

**Comment by khaltore** [comment]
shipit

**Comment by gundalow** [comment]
Closing and reopening to retrigger CI as we've extended module validation rules.

**Review by gundalow — APPROVED** [review]

**Pull request merged**
