### PR TITLE
Fix author (and test ansibot)

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Check if ansibot fails on email-addresses in author lists.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
route53.py

##### ANSIBLE VERSION
v2.8

### CODE REVIEW

**Review by willthames — APPROVED** [review]

**Comment by dagwieers** [comment]
bot_status

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
> Check if ansibot fails on email-addresses in author lists.

I'm not sure where's the test. From this description, I'd assume that you add email somewhere and see test failing, but I see you doing vice versa.

**Comment by dagwieers** [comment]
@webknjaz The test is in looking how ansibot would respond, yesterday and after it is fixed. We would expect both people to be notified.

**Comment by dagwieers** [comment]
bot_status

**Comment by dagwieers** [comment]
bot_status

**Comment by dagwieers** [comment]
So it now correctly assigns @bpennypacker @jimbydamonk as maintainers.
I am going to merge and close this.

**Pull request merged**
