### PR TITLE
Azure_RM_VirtualMachine new functionality

### PR DESCRIPTION
**Pull request by eliotstocker**
Pull Request

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Module: azure_rm_virtualmachine

##### ANSIBLE VERSION
```
ansible 2.2.3.0-1
```

##### SUMMARY
######WinRM Configuration:
Add the new option ‘win_rm’ into the azure_rm_virtualmachine module to allow creation of WinRM listeners on the newly created VM, this allows to start configuring with ansible strait away after creation is complete.

I have added four variables,
Boolean: 'SSL' - to enable the HTTPS listener (port 5986), if not set only an HTTP listener will be created (port 5985)
String: 'certificate' - url to a certificate in your ARM Keyvault (required if SSL is true)
String: 'vault' - id of keyvault in ARM (Required if SSL is true)
String: 'store' - store name on windows server (optional, but default is set to 'My' which should work for the most part)

when using this method you must connect to he remote machine using NLTM, so you must set your host transport like so:
ansible_winrm_transport: ntlm

######Auto Logon Configuration
Add the new option ‘auto_logon’ into azure_rm_virtualmachine module to allow the local machine to log directly into a particular user on boot, this allow to run GUI applications etc after boot.

Only two variables are needed for this functionality:
String: ‘user’ - the username you wish to auto login to on boot
String: ‘password’ - the password of the defined user

######Security Group Configuration
Add the new option ‘security_group’ into azure_rm_virtualmachine module to allow new NICs created to be added to a specified security group, this removes an unnecessary step from the deployment, and effectively fixes the issue that Security groups are not removed when removing a server and related items.

This variable accepts a string with just the name of the requested Network Security Group, this security group should be in the same region as the NIC and VM

######Image URI configuration
add the new option 'image.uri' into azure_rm_virtualmachine module to allow the use of custom images that are not searchable etc. Just the URI as a string as returned from the Azure CLI, API or Portal

### CODE REVIEW

**Comment by nitzmahone** [comment]
I think we need some of this functionality (WinRM listener config in particular), but I'm a little nervous to add it like this at the top level without some thought to the other things that need to go in (general use of VM extensions, and if/how we want to support them). This module has the potential to *very* quickly turn into the tire fire that is `ec2.py`, and I'd like to avoid that if at all possible. The NIC modification stuff in particular seems like it's headed down a slippery slope. I was on the fence about whether to do "automatic" resource creation at all when we created this module anyway (rather than requiring use of explicit modules to stand up all the necessary objects), and if we start adding knobs to adjust all those automatically-created resources, this thing's going to look a lot worse than EC2 in a big hurry.

**Comment by eliotstocker** [comment]
I completely understand your concerns, of course this is mostly to add the functionality that we need, would you feel more comfortable if i were to refactor in to two or three separate pull requests, where each added functionality's merits and problems can be discussed separately?

**Comment by yuwzho** [comment]
@nitzmahone How this PR going? Need go ahead to merge or close it?

**Comment by Fred-sun** [comment]
Hi @eliotstocker This PR has open more than one years, there is a conflict file in the PR, Could you help update the PR status , resolve the conflict and update next step plan, Thanks !

**Comment by Fred-sun** [comment]
Hi @nitzmahone , This PR has pen more than one years and there is a conflict file , Can we follow @yuwzho's advice to merge or close it ? Please confirm it, Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker Could you help to resolve the conflicting files? It also need you update the comment? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for your contribution, Could you help update the comments? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for your contribution, Could you help to resolve the conflict and update the comments? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for your contribution, Could you help to resolve the conflict and update the comments? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for your contribution, Could you help to resolve the conflict and push to next step forward? Thanks!

**Comment by Fred-sun** [comment]
@nitzmahone Could you help to confirm that how this PR going? Need go ahead to merge or close it? It has no updated more than one years? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for the contribution, Are you still here? Could you help to resolve the conflicting files? Thanks.

**Comment by eliotstocker** [comment]
I'll take a look this weekend and resolve the issues where I can

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for the contribution. do you have resolved the issues? if yes, I will push others to review and merge? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker kindly ping

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for the contribution, any update for this PR? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for the contribution, Are you still pay attention on this PR? Could you help to resolve the conflicting files? Thanks!

**Comment by Fred-sun** [comment]
@eliotstocker

**Comment by Fred-sun** [comment]
@eliotstocker Thanks for your contribution, This PR seems really old and have conflict with devel branch.  Are you still there? If there is no response in 7 days, we may close this one and triage our bandwidth to support such thing. Thanks!

**Comment by Fred-sun** [comment]
@yuwzho

**Comment by eliotstocker** [comment]
im afraid i currently dont have time to get this back up to date, closing, will reopen if/when i have the time to work on it

**Pull request closed without merging**
