### PR TITLE
[docs] fix erroneous example in inventory

### PR DESCRIPTION
**Pull request by dminca**
##### SUMMARY

After initializing a list in both Python2/Python3 with below elements,
I've tested the indexing and realised that the examples provided in the
documentation are **erroneous**.

Also, I've **added** another example in addition to loop through maximum 3 nodes.

As a result, update the examples with correct values in order to avoid
any future confusion.

##### ISSUE TYPE

 - Docs Pull Request

##### ANSIBLE VERSION

```
ansible 2.4.2.0                                                                                                    
  config file = None                                                                                               
  configured module search path = [u'/home/dminca/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                        
  executable location = /usr/bin/ansible                                                                           
  python version = 2.7.14 (default, Feb 17 2018, 10:42:17) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]                  
```

##### ADDITIONAL INFORMATION

Tests issued in the Python interpreter prove that the examples in documentation were erroneous:

```python
In [1]: webservers = ['cobweb', 'webbing', 'weber']
                                                               
In [5]: webservers[0:1]
Out[5]: ['cobweb']     

In [9]: webservers[1:2]
Out[9]: ['webbing']    

In [7]: webservers[2:3]
Out[7]: ['weber']      
```

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Code only update, so merging

**Comment by abadger** [comment]
Since the intent was to show slicing syntax, we probably wanted to change it like this:

```
    webservers[0:2]     # == webservers[0],webservers[1]
                        # == cobweb,webbing
```

**Comment by dminca** [comment]
I didn't knew that was the intent, I just fixed the output :smile: 

Anyway, if it makes difference I'll just include that as well in another PR :+1:

**Comment by gundalow** [comment]
@dminca That would be great, thanks

**Pull request merged**
