### PR TITLE
Two erlang modules

### PR DESCRIPTION
**Pull request by dmajere**
Hello, i'm using ansible for erlang continuous integration/deployment, so i've made a couple of modules for it.
Take a look at them, please. If you think its ok with them, i'd be very pleased if you get them into core, so everyone could use them

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Dimtry,

At first glance these look pretty good so they are in queue for review.  

One thing you will want to update is code like:

```
 +            cmd = '{command} --{param}'.format(command=cmd, param=param)
```

Our modules need to support running on python 2.4 systems, so you will want to instead use formatting like:

```
 cmd = "%s -- %s" % (foo, bar)
```

It looks like maybe the module should just say it doesn't support check mode so that can be removed.

Do you have a playbook that we could look at and use for possible testing?

Thanks!

**Comment by dmajere** [comment]
erlang_rpc:

for  test you'll need erlang installed on your testing machine.
1. start erlang node with some name 

``` bash
root@test:~# erl -name test@127.0.0.1
Erlang R16B02 (erts-5.10.3) [source-b44b726] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Eshell V5.10.3  (abort with ^G)
(test@127.0.0.1)1>
```

Testing erlang:get_cookie function

``` bash
ansible localhost -m erlang_rpc -a "node=test@127.0.0.1 module=erlang method=get_cookie"

localhost | success >> {
    "changed": true,
    "cmd": "erl -noshell -name 'ansible_13@127.0.0.1' -eval \"io:format(\\\"~p~n\\\", [rpc:call('test@127.0.0.1', 'erlang', 'get_cookie', [])]).\" -s erlang halt ",
    "out": "'DZADHIJQSBDLZVGKMYAN'\n"
}
```

Testing erlang:set_cookie/2 function

``` bash
ansible localhost -m erlang_rpc -a "node=test@127.0.0.1 module=erlang method=set_cookie 
args=\'test@127.0.0.1\',cookie"

localhost | success >> {
    "changed": true,
    "cmd": "erl -noshell -name 'ansible_28@127.0.0.1' -eval \"io:format(\\\"~p~n\\\", [rpc:call('test@127.0.0.1', 'erlang', 'set_cookie', ['test@127.0.0.1',cookie])]).\" -s erlang halt ",
    "out": "true\n"
}
```

Check if it really changed

``` bash
ansible  -m erlang_rpc -a "node=test@127.0.0.1 module=erlang cookie=cookie method=set_cookie args=\'test@127.0.0.1\',cookie"
localhost | success >> {
    "changed": true,
    "cmd": "erl -noshell -name 'ansible_83@127.0.0.1' -setcookie 'cookie' -eval \"io:format(\\\"~p~n\\\", [rpc:call('test@127.0.0.1', 'erlang', 'set_cookie', ['test@127.0.0.1',cookie])]).\" -s erlang halt ",
    "out": "true\n"
}
```

erlang_rebar:

For this module you could try something like this

```

- name: Clone Project
  git:
                repo={{ git_repository }}
                version={{ git_branch }}
                update=yes
                force=yes
                dest={{ project_path }}
- name: Cleaning
  erlang_rebar:
                app_path={{ project_path }}
                command=clean
- name: Getting Deps
  erlang_rebar:
                app_path={{ project_path }}
                command=get_deps
- name: Compiling
  erlang_rebar:
                app_path={{ project_path }}
                command=compile
- name: Generating Release
  erlang_rebar:
                app_path={{ project_path }}
                command=generate
```

of course, you'll need erlang project that is ready for making release

**Comment by rgrinberg** [comment]
What's the status of this PR? This seems like a very useful module.

**Comment by lukyanov** [comment]
I vote for erlang_rpc.

**Comment by mpdehaan** [comment]
Sorry for the very late reply on this.

As these modules mostly just shell out to command line tools, I think we are apt to not include them in core.

We'd be looking for change detection, possibly check mode, and a bit more business logic to warrant the inclusion.

This is to not say these cannot be useful, however!

**Pull request closed without merging**
