### PR TITLE
postgresql_user: add comment parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_user: add comment parameter

The task is typical.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/postgresql/postgresql_user.py```

### CODE REVIEW

**Review by andytom — COMMENTED** [review]
I'm not sure why the test is failing some kind of encoding issue? but the change LGTM.
shipit

**Comment by Andersson007** [comment]
@andytom , thank you! I guess it is because of centos6's postgresql default version. maybe it is too old

**Comment by Andersson007** [comment]
```
"COMMENT ON ROLE \"hello.user.with.dots\" IS E'comment1'"
```
yes, it puts E before the text in single quotes..

**Comment by Andersson007** [comment]
i faced it several times. I could have put the ```or``` statement into CI but, IMO, it doesn't make sense, i restricted the tests by postgres version (9.4+)

**Comment by Andersson007** [comment]
ready_for_review

**Comment by andytom** [comment]
shipit

**Comment by Andersson007** [comment]
@andytom thanks for approving!

**Comment by tremble** [comment]
bot_status

**Pull request merged**
