### PR TITLE
format error messages from module_utils.basic nicer

### PR DESCRIPTION
**Pull request by evgeni**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module_utils

##### SUMMARY
* lists are printed as a string, separated by a comma and a space
* require_if tells if is_one_of was True or False

### CODE REVIEW

**Comment by calfonso** [comment]
@evgeni interested in rebasing this PR and we'll finish the review?

**Comment by abadger** [comment]
Rebased.  We've been having unrelated timeouts on one set of python3 tests.  But if we can manage to avoid that....

rebuild_merge

**Comment by mattclay** [comment]
I've restarted CI since there were quite a few failures in integraion tests, and at least some of them were not related to this PR: https://app.shippable.com/github/ansible/ansible/runs/39147

**Comment by mattclay** [comment]
CI failures occurred again. Most appear related to this PR. Here's one:

https://app.shippable.com/github/ansible/ansible/runs/39432/24/tests

**Comment by mattclay** [comment]
CI failure in integration tests:

https://app.shippable.com/github/ansible/ansible/runs/39546/47/tests
https://app.shippable.com/github/ansible/ansible/runs/39546/49/tests

The OS X test failure is unrelated and can be ignored.

**Comment by mattclay** [comment]
Another CI failure due to formatting changes:

https://app.shippable.com/github/ansible/ansible/runs/39752/45/tests

The FreeBSD failure is unrelated.

**Comment by gundalow** [comment]
`targets/ec2_group/tasks/main.yml:19` needs updating
`one of the following is required: name,group_id`

**Comment by abadger** [comment]
... many moons later....

Merged to devel!  Thanks @evgeni!

**Pull request merged**
