### PR TITLE
Apt fix 22124

### LINKED ISSUE #22124: Error when separate apt tasks
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

No changes 

##### OS / ENVIRONMENT

Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-59-generic x86_64)

Both hosts and servers 

##### SUMMARY

Running 3 separate  atp actions failes on the third 

##### STEPS TO REPRODUCE

```yaml
```

https://gist.github.com/varazir/ba960bd117b9ee0e37e7810d3bacb10f

##### EXPECTED RESULTS

To remove unused dependency packages, 
Merging the 3 tasks it works fine. 

##### ACTUAL RESULTS

See Gist 

```

```

### PR DESCRIPTION
**Pull request by bjolivot**
##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

apt.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (apt_fix_22124 ddee803d43) last updated 2017/03/01 17:31:08 (GMT +200)
  config file = /home/ben/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Change default value (None -> []) for arg package in module_spec 

Fixes #22124

### CODE REVIEW

**Comment by resmo** [comment]
Would you be able to add a integration test for this and the docs needs to be udpated as well https://github.com/bjolivot/ansible/blob/1017c258b784160adbfb67e45c21e1e333b5a506/lib/ansible/modules/packaging/os/apt.py#L38

**Comment by bcoca** [comment]
an alternate fix that does not change the docs is checking for None before looping over packages

**Comment by bcoca** [comment]
there are other issues with the module that this 'fix' does not solve, autoremove is not in 'required_one_of' yet it seems to pass the initial validation

**Comment by bjolivot** [comment]
Ok I'll change that too.
What about previous fix ? do you think it's better to revert to None and make a test before package loop ?
I'll work on it later today or tomorow

**Comment by bjolivot** [comment]
irc comment:
 <@abadger1999> bjolivot_: That works.. I'd put "smoketest" in the name... "smoketest that module without a package specified does not error"

**Comment by snowsky** [comment]
I put up a PR #22165 for this change. It seems we need to retrieve all the packages by "apt-get autoremove" command first and then passed them to packages variable.

**Comment by resmo** [comment]
Thanks for your fix, but the alternate fix #22154 has been merged.

**Pull request closed without merging**
