### PR TITLE
Add filters: getgrnam and getpwnam

### PR DESCRIPTION
**Pull request by rrauenza**
I thought these might be useful ... and the docs encouraged submissions of useful filters.

In my particular use case, I need to create a pure-ftpd passwd file but I need the uids of the users.

(Admittedly, I didn't check if the user action returned the uid as a result...)

### CODE REVIEW

**Comment by rrauenza** [comment]
Ah... and now I've learned I can add -vvvv's and see the actual return values of user: and group: that do return the gid and uid.   That doesn't exactly help all cases because one might be looping over usernames without corresponding rules to register results from.

**Comment by bcoca** [comment]
actually, filters change data, this seems more appropriate as a lookup as that is what you are really doing

**Comment by rrauenza** [comment]
Hmm -- I hadn't thought of it that way.  Oh -- especially important -- where is this filter executed -- is it executed on the target system?  Because if it isn't, then this filter is not going to do what I intended!

**Comment by bcoca** [comment]
nope, filters and lookups ONLY run on the master/controller, you can get most of this info from the target using the getent module.

**Comment by rrauenza** [comment]
Thanks!  Then I think I will close this for many reasons -- it doesn't look it up on the target system, and a lookup would be more appropriate if it did.  And getent does it, anyway.   You could also use the registered value from user or group modules, too.

**Pull request closed without merging**
