### PR TITLE
Add a User-Agent string to the API request

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

This PR adds a User-Agent header to each API request.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- scaleway_compute
- scaleway_sshkeys

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.6.0
  config file = None
  configured module search path = [u'/Users/sieben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible-2.6.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### CODE REVIEW

**Comment by sivel** [comment]
I recommend pulling the ansible version from `module.ansible_version`, where module is created by `AnsibleModule`.

**Comment by remyleone** [comment]
@sivel Done.

**Comment by remyleone** [comment]
@pilou- Could this be merged?

**Comment by pilou-** [comment]
Should not the `user-agent` header added by [`ScalewayAPI.__init__`](https://github.com/sieben/ansible/blob/b05ab0998b042ceff776910b4d18a2dcaf2aa0b9/lib/ansible/module_utils/scaleway.py#L38) when `user-agent` is missing in `headers` parameter ?

**Comment by remyleone** [comment]
Then we should also move `'Content-type': 'application/json'`? I can do it but I would prefer staying consistent about headers.

**Comment by pilou-** [comment]
Indeed, `Content-type` should be moved too. Why isn't that consistent ?

**Comment by remyleone** [comment]
I would need the module to access the `module.ansible_version` So I'm not sure about how to import this variable from the module_utils...

**Comment by remyleone** [comment]
@maxamillion do you have an opinion about it?

**Comment by remyleone** [comment]
@pilou- How could we move this PR forward?

**Comment by pilou-** [comment]
> I would need the module to access the module.ansible_version So I'm not sure about how to import this variable from the module_utils...

What about the ~~[module replacer](docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html)~~ [module replacer](http://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html?highlight=ansible_version#module-replacer) ?

**Comment by maxamillion** [comment]
@pilou- I'm not sure what you're attempting to show with that URL

**Comment by maxamillion** [comment]
@sieben I'm good with the over all change if you as the module maintainer finds value in this. As far as specific implementation, I'm fine with the changes but I'm curious to learn more about the concern @pilou- has placed because I don't fully understand yet.

**Comment by pilou-** [comment]
@maxamillion @sieben whoops, URL updated. My previous remark was about setting User-Agent header in `module_utils` rather than duplicating code.

**Comment by maxamillion** [comment]
Ah ok, yeah I agree with @pilou- ... I recently did something similar with the `firewalld` module refactor and I think that makes sense especially if that is slated to be used by many modules via module_utils.

It could even just be as simple as something like this added to `ScalewayAPI` that you call where appropriate in the other modules.
```python
@staticmethod
def get_user_agent_string(module):
    return "ansible %s Python %s" % (module.ansible_version, sys.version.split(' ')[0])
```

**Comment by remyleone** [comment]
@maxamillion @pilou- Like this?

**Comment by pilou-** [comment]
`get_user_agent_string` should be called in `ScalewayAPI` class.

**Comment by remyleone** [comment]
I've rebased and now I get this kind of error:

```
TASK [Create a server (Check)] ***************************************************************************************************************************************************************************************************************
task path: /Users/sieben/workspace/ansible/test/legacy/scaleway_compute.yml:11
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/scaleway.py
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /Users/sieben/workspace/ansible/lib/ansible/module_utils/urls.py
Using module file /Users/sieben/workspace/ansible/lib/ansible/modules/cloud/scaleway/scaleway_compute.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sieben
<127.0.0.1> EXEC /bin/sh -c 'echo ~sieben && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo Sleeping for 1s.../.ansible/tmp/ansible-tmp-1525694079.711671-72280728599280 `" && echo ansible-tmp-1525694079.711671-72280728599280="` echo Sleeping for 1s.../.ansible/tmp/ansible-tmp-1525694079.711671-72280728599280 `" ) && sleep 0'
<127.0.0.1> PUT /Users/sieben/.ansible/tmp/ansible-local-9763895eox2sl/tmpgmjz_ncl TO Sleeping for 1s.../scaleway_compute.py
fatal: [localhost]: FAILED! => {
    "msg": "failed to transfer file to Sleeping for 1s.../scaleway_compute.py: [Errno 2] No such file or directory: b'Sleeping for 1s.../scaleway_compute.py'"
}
```

**Comment by remyleone** [comment]
Pushed.

**Review by pilou- — APPROVED** [review]
LGTM

**Comment by remyleone** [comment]
@pilou- @maxamillion Could this be merged? How to move it forward?

**Comment by maxamillion** [comment]
@sieben sorry, I was at Red Hat Summit last week and was mostly offline. I've re-kicked the shippable tests to ensure we don't have stale CI and once those pass I'll merge.

**Comment by remyleone** [comment]
No problem :) I hope you had a nice weather.

Le lun. 14 mai 2018 à 16:08, Adam Miller <notifications@github.com> a
écrit :

**Pull request merged**
