### PR TITLE
Add Rackspace Cloud Block Storage module

### PR DESCRIPTION
**Pull request by claco**

### CODE REVIEW

**Comment by claco** [comment]
@sivel First pass at creating/deleting Block Storage Volumes.

Pyrax seems a little weak on update/rename glue. No attempt at snapshotting/attach/detach yet. And the status names are entertaining.

What do you think about attached/detached as state: rather than magical meanings of passing attachments: ['...'] that might not only be empty/not empty, but a different id?

**Comment by sivel** [comment]
I was actually working on this same thing today as well :)

Here has been my approach so far, but the present/absent functionality along with attaching and detaching is a little complicated, especially with all of the dependencies for being able to detach.

https://github.com/sivel/ansible/commit/52ec96c6de0aa6fb4fe1e11c87604723ce1022cd

It has to be unmounted from the server (server side), then it has to be detached from the server (have to wait on status), then you have to delete and wait on status change as well, when using `wait`.

**Comment by claco** [comment]
Yeah, that's kinda why I didn't roll it in. Seems too discrete of a process to put inside the same creation. You only attach during create, but I might actually be attaching later (like scripting moves, etc). Or really, I might not have a server yet to attach it to if I'm creating volumes before my instance, of with the perf flavor stuff, doing a scripted upsize.

In other news, queue.list() is broken. :-/

**Comment by claco** [comment]
@sivel Dropping a quick hack or attach/detach so it doesn't get lost since I needed to do that this evening. Went with something that just treats the attachment as a resource separately from server and volumes. Allows me to orchestrate them in specific ways... including moves.

**Comment by jctanner** [comment]
@claco If you could refactor this to use the module snippets per @sivel's examples in https://github.com/ansible/ansible/pull/4865 I will merge it.

**Comment by claco** [comment]
I'll get on this first thing in the morning. Thanks!

**Comment by claco** [comment]
@jctanner All refactored (both modules), squashed to a single commit and rebased.

**Comment by jctanner** [comment]
@sivel can we get your review on this?

**Comment by sivel** [comment]
Absolutely. I'll get to it in the next 24 hours or so.

**Comment by claco** [comment]
@sivel Thank you sir. Now stop looking surprised. :-)

**Comment by sivel** [comment]
My comments:

##### rax_cbs_attachments
1. Although in pyrax the argument is `mountpoint` I don't think we should name the attribute this.  It is potentially confusing.  Perhaps just `device` or `device_name`.  You can still keep the internal naming of `mountpoint`, I would just recommend at least changing the exposed attribute name.
2. `cs.servers.get` will never return a server if a name is given.  If you want to match on names, you will need to use something like `cs.servers.list(search_opts=dict(name='^%s$' % server))`.  This can be paired with a try/except around a `UUID(server)` to determine if a server ID was passed instead of a name.  The `rax` module has somewhat of an example for this, although not related to a server.
3. There is reference to `rax_clb_attachments` which should be `rax_cbs_attachments`

##### rax_cbs
1. This module accepts `wait` and `wait_timeout` attributes, but it doesn't appear there are actually any places where waiting happens.
2. There is reference to `rax_clb` which should be `rax_cbs`

**Comment by claco** [comment]
@sivel Thanks for taking a look at these. I'll have another pass at them this afternoon.

re: mountpoint: I vote device, since that's the param sent in the nova client.

**Comment by mpdehaan** [comment]
@claco -- I haven't seen any updates above from what @sivel had requested.   Can you please update this one and resubmit?  Thanks!

**Pull request closed without merging**
