### PR TITLE
Apt_repository without binary requirements of the ubuntu specific apt-add-repository

### PR DESCRIPTION
**Pull request by alezkv**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks very much.   I've asked the list Debian users to help take a look at this since this is not a module I regularly use.

**Comment by mpdehaan** [comment]
reopened -- accidentally clicked the close button :)

**Comment by esclapes** [comment]
I am trying to test this on a debian squeeze server, but got the same error both with the old and new versions of library/apt_repository

¿does ansible caches the modules in any way or am I having two installs without noticing? Probably the later, but then I don't know how to test... if I run ansible --version I get 0.8 so I guess I am using my up-to-date devel branch

This is my output when I use izhukov 3f8db55d6b94 version of the module (I am just copy-pasting the contents of  03f8db5 version of the file into library/apt_repository)... 

```
$ ansible all -i hosts/hosts -m apt_repository -a "repo='deb http://ftp.debian.org/debian/ squeeze main contrib non-free' state=present" -u root -vvv
<dd.kimsufi.com> ESTABLISH CONNECTION FOR USER: root
<dd.kimsufi.com> EXEC "$SHELL" -c 'mkdir -p /var/tmp/ansible-1348552320.93-56613459094033 && echo /var/tmp/ansible-1348552320.93-56613459094033'
<dd.kimsufi.com> REMOTE_MODULE apt_repository repo='deb http://ftp.debian.org/debian/ squeeze main contrib non-free' state=present
<dd.kimsufi.com> PUT /tmp/tmp8h3FJ8 TO /var/tmp/ansible-1348552320.93-56613459094033/apt_repository
<dd.kimsufi.com> EXEC "$SHELL" -c 'chmod u+x /var/tmp/ansible-1348552320.93-56613459094033/apt_repository'
<dd.kimsufi.com> EXEC "$SHELL" -c /var/tmp/ansible-1348552320.93-56613459094033/apt_repository
<dd.kimsufi.com> EXEC "$SHELL" -c 'rm -rf /var/tmp/ansible-1348552320.93-56613459094033/'
dd.kimsufi.com | FAILED >> {
    "failed": true, 
    "msg": "Failed to find required executable add-apt-repository"
}
```

**Comment by alezkv** [comment]
I have a stupid pull from my devel branch, sorry all.

Since new info about apt-add-repository avalible at https://groups.google.com/d/msg/ansible-project/7zFFcboPHC0/fkVSd6hOon8J
And Michael said:

> Presumably it should use the apt-add-repository code if installed.

Request is closed.

**Comment by mpdehaan** [comment]
Ansible does not cache any modules.

If you are using the config file, your module path may not be what you
expect.

(I'm not sure offhand if I made the module path output when using "-v -v
-v" but perhaps it should)

**Pull request closed without merging**
