### PR TITLE
Change to stdout

### PR DESCRIPTION
**Pull request by davehatton**
This should be ready to go now.

### CODE REVIEW

**Comment by davehatton** [comment]
sorry I didn't know if there was some nice way to collapse these into one single commit?

**Comment by mpdehaan** [comment]
If you want, you can use another branch and use "git merge --squash" to make one commit on that other branch.

**Comment by davehatton** [comment]
shall I do that and ask you to pull this again?

**Comment by mpdehaan** [comment]
sure, makes review easier on me.

**Comment by davehatton** [comment]
I've done that - thanks for the help - sorry to need so much hand holding

**Pull request closed without merging**
