### PR TITLE
To fix ios_l3_interfaces resource module round trip failure

### PR DESCRIPTION
**Pull request by justjais**
Signed-off-by: Sumit Jaiswal <sjaiswal@redhat.com>

##### SUMMARY

To fix `ios_l3_interfaces` resource module round trip failure raised in issue #61396

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ios_l3_interfaces
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
@justjais can we add a test here to confirm we don't break in the future?

**Comment by pabelanger** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by justjais** [comment]
@NilashishC have removed RTT tests from the PR and I'll create new PR for all the newly introduced resource module in a single one, need to merge this and create a backport for same in `2.9`

**Review by NilashishC — APPROVED** [review]

**Pull request merged**
