### PR TITLE
Docs: Clean up 'win_reboot' module docs

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This is part of a series of module doc cleanups.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
win_reboot

##### ANSIBLE VERSION
v2.8 and older

### CODE REVIEW

**Comment by dagwieers** [comment]
Please review. I think this would be nice to back-port too.

**Comment by dagwieers** [comment]
For my specific case where we couldn't start doing AD stuff (even 60 secs) after the system was rebooted and WinRM was available, waiting for Netlogon to start was not a help, but delaying the start of WinRM worked reliably. Although it means a reboot typically takes 150 seconds (we're talking about VMs here, so 150 seconds is a lot longer than expected, but reliability trumps speed :-)).

So these changes to the documentation are really important IMO. And I plan to write a `wait_for_event` module that can be used for optimizing wait time, in a lot of situations, not just reboots.

PS I would appreciate if someone could test the example using `test_command` on Windows. I couldn't find a good use-case for me to test.
PS2 Despite the fact that `post_reboot_delay` and `test_command` can solve the issue at hand, I don't think it is a good practice that a previous procedure/role (reboot for some task prior) influences an unrelated subsequent procedure/role (next task). So I prefer the delayed start of WinRM (system config) or an explicit `wait_for_event` (part of the next procedure) over intermingling 2 procedures/roles.

**Comment by dagwieers** [comment]
And we ought to add a section related to this, since this is pretty specific to how Windows works.

- Windows may take longer to boot because of updates (which makes reboot fail within the default timeout) *Personally, I think we need to cover for this, as this can be a real problem*
- Windows may take longer to settle because of updates
- Windows may take longer to settle than the next intended task expects

All this could mean your well-tested orchestration may fail in subtle ways you did not foresee (at the worst moment in time, e.g. when restarting your nuclear reactor ;-)).

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
> Windows may take longer to boot because of updates (which makes reboot fail within the default timeout) Personally, I think we need to cover for this, as this can be a real problem

The solution to this is to use `win_updates` with `reboot: yes`. It has some fancy code to check when updates are finished installing and I've haven't had it fail me since it was added.

I still stand by my remarks on the other point, there are so many components people could be waiting on and to have us cover them all would be quite impossible. I've only ever come across an issue with a reboot after promoting a server to a DC and all the components were still starting as WinRM came up. The solution at the time was to add a retry/until on the next task to handle any failures that may have come up.

Maybe we want to add a new module option that takes in a list of known scenarios that we've come across. We can have the win_reboot action wait for those scenarios to be finished before continuing on. This could be a simple wait for this service to be up and running, or something more complex like wait until this event is fired after a reboot.

**Comment by dagwieers** [comment]
> The solution to this is to use `win_updates` with `reboot: yes`. It has some fancy code to check when updates are finished installing and I've haven't had it fail me since it was added.

That is not a solution, as the user doesn't know when updates are being part of the reboot, and they shouldn't care. If they perform a reboot, it shouldn't fail the task (and playbook) because the shutdown or reboot takes longer than 600 seconds (default timeout). And you can't replace every **win_reboot** with **win_updates reboot=yes** because that won't do a reboot if there are no updates.

win_reboot should maybe detect that there are outstanding updates being applied during shutdown/reboot and disable timeout, or something similar to that. (Or suspend performing the updates part, if that's at all possible).

> I still stand by my remarks on the other point, there are so many components people could be waiting on and to have us cover them all would be quite impossible. I've only ever come across an issue with a reboot after promoting a server to a DC and all the components were still starting as WinRM came up. The solution at the time was to add a retry/until on the next task to handle any failures that may have come up.

Right, but I don't think it's good practice to have the next task (possibly the next role) cover for an issue with the previous task, which may or may not be a reboot. We might as well tell users to make the first task of a role a testing-loop. As a workaround that's ok, but as a solution it shouldn't count IMO.

> Maybe we want to add a new module option that takes in a list of known scenarios that we've come across. We can have the win_reboot action wait for those scenarios to be finished before continuing on. This could be a simple wait for this service to be up and running, or something more complex like wait until this event is fired after a reboot.

I think we need to offer something like this. Something that is generic and can list a set of requirements for a task or role to continue. In my view **win_wait_for_event**, **win_wait_for_process** and **win_wait_for** offer this. But the problem that **win_reboot** might fail your playbook is not covered by this.

**Comment by dagwieers** [comment]
But don't let the unsolved issues be a blocker for this PR :-)

**Comment by jborean93** [comment]
Done!

**Pull request merged**
