### PR TITLE
update facts.py for solaris and hp-ux

### PR DESCRIPTION
**Pull request by fallencliff**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

facts.py
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/yd_hzj/project/AnsibleCmdb/common/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

for solaris,  add get_dmi_facts to get product_name fact, and update memtotal_mb to integer for consistency.

for hp-ux,  use machinfo to get product_serial fact.

```

```

### CODE REVIEW

**Comment by xen0l** [comment]
I have a more feature packed version of get_dmi_facts() for Solaris, which I tried to contribute, but later I closed it (I don't remeber the reason why). I would like us to merge that version instead. The version can be found https://github.com/ansible/ansible/pull/9892. I can fix the comments and create/revive a new PR. @fallencliff would you be able to test those changes?

**Comment by fallencliff** [comment]
@xen0l , I tried ur code in solaris 5.10, it failed as below ,

# uname -a

SunOS testdb 5.10 Generic_144488-04 sun4u sparc SUNW,SPARC-Enterprise

# 

# smbios -t SMB_TYPE_BIOS

smbios: failed to load SMBIOS: System does not export an SMBIOS table

# smbios -t SMB_TYPE_SYSTEM

smbios: failed to load SMBIOS: System does not export an SMBIOS table

**Comment by xen0l** [comment]
@fallencliff thanks for the information. It seems that SPARCs do not export those information and have to be obtained differently. Will rework the get_dmi_facts(). Did the disk-related pieces work for you? The change for detecting SmartOS will be dropped as ansible already contains the logic to recognize Solarish distributions.

**Comment by fallencliff** [comment]
@xen0l ， still failed, i tried the lower-case c option ,nothing returned;

# uname -a
SunOS ngcj2 5.10 Generic_144488-04 sun4v sparc SUNW,SPARC-Enterprise-T5220
# 
# /usr/bin/kstat -C sderr
Unknown option: C
用途：
kstat [ -qlp ] [ -T d|u ] [ -c class ]
      [ -m module ] [ -i instance ] [ -n name ] [ -s statistic ]
      [ interval [ count ] ]
kstat [ -qlp ] [ -T d|u ] [ -c class ]
      [ module:instance:name:statistic ... ]
      [ interval [ count ] ]
# 
# /usr/bin/kstat -c sderr
#

**Comment by fallencliff** [comment]
@bcoca   would you take a look at this pull request

**Comment by xen0l** [comment]
@bcoca I would propose reverting this PR (at least Solaris part), because it can fail and it doesn't covers all the cases on x86 for example. It will fail on machines, which do not provide any information in prtdiag. @fallencliff have you tested this also on non-sparc machines?

**Comment by fallencliff** [comment]
@xen0l ,  no ,i did not think of the X86 solaris, so i did not test it on non-sparc machines, but i can fix it, 
@bcoca   shoud i start a new PR ? or wait for bcoca to reopen the closed PR  #18480 
i am not quite famililar with github, is there a team that i can ask to do code review before the  merge?

**Comment by xen0l** [comment]
Yesterday, I did some testing and it works on x86 (nothing gets printed, I haven't read the source code more closely). I will have a followup PR, which will merge my code with yours and hopefully to get more information relating to DMI. I also updates my changes in https://github.com/xen0l/ansible/commits/solaris-devices (I tested those changes on both sparc and x86. However, it was illumos as I don't have access to Solaris. It should work though).

**Comment by fallencliff** [comment]
@xen0l
I have access to sparc solaris 5.10, maybe also 5.9, and  hp-ux ,aix ,  i can test ur code if u need

**Pull request merged**
