### PR TITLE
Backport of https://github.com/ansible/ansible/pull/42025 to stable-2.6 for pamd

### PR DESCRIPTION
**Pull request by maxamillion**
##### SUMMARY
Backport of https://github.com/ansible/ansible/pull/42025 to fix https://github.com/ansible/ansible/issues/41179 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

pamd

### CODE REVIEW

**Comment by jamescassell** [comment]
shipit

**Comment by jbridger** [comment]
I'm using pip3 to download 2.6.0, but I'm still having this error.

I managed to view the `ansible_module_pamd.py` that is created at runtime in the `/tmp/ansible_<RANDOM_ID>` path and can see it doesn't have the changes in this commit.

As this is backported, is this fix in the latest release available via pip?

**Comment by mattclay** [comment]
@jbridger This fix will be included in Ansible 2.6.1 when it is released today.

**Comment by jbridger** [comment]
Great, thanks

**Pull request merged**
