### PR TITLE
more tests for safe_eval

### PR DESCRIPTION
**Pull request by alikins**
include test cases for 'type'

##### ISSUE TYPE

 - Bugfix Pull Request
 - Tests Pull Request

##### COMPONENT NAME

test/units/template/test_safe_eval

##### ANSIBLE VERSION

```
ansible 2.3.0 (test_safe_eval_devel2 c771056d7b) last updated 2017/01/11 16:52:43 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides


```

##### SUMMARY
test cases for template.safe_eval, related to https://github.com/ansible/ansible/pull/20155

### CODE REVIEW

**Comment by abadger** [comment]
Merged the type => type_debug rename.  I hit rebuild in shippable for this to see if it will pass tests now.

**Comment by abadger** [comment]
Still failing in shippable so did not merge.  Looks like the tests are trying to test set literal syntax but set literals are not available in python-2.6.  Need to not use literal syntax in the test_*.py file and maybe need to skip the test on python-2.6?

**Comment by gundalow** [comment]
Unit tests are failing due to this change

**Comment by alikins** [comment]
whatever

**Pull request closed without merging**
