### PR TITLE
support add repo behind proxy on ubuntu(#42534)

### LINKED ISSUE #42534: apt_repository module does not work behind proxy on ubuntu
##### SUMMARY

apt_repository is calling apt-key when adding new repo source. apt-key does not respect http_proxy env var nor Acquire::http::Proxy specified in apt conf files. However it does support proxy setting passed in from --keyserver-options parameter. Current apt_repository is missing logic to handle keyserver-options.
Therefore apt_repository will not be able to add new repo behind proxy on ubuntu
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

apt_repository
##### ANSIBLE VERSION

```
all
```

##### OS / ENVIRONMENT

target env: ubuntu
##### STEPS TO REPRODUCE

```yaml
- apt_repository:
    repo: 'ppa:git-core/ppa'
    state: absent
    validate_certs: false
    update_cache: yes
  environment:
    http_proxy: http://proxy.example.com:8080
  become: yes
```

##### EXPECTED RESULTS

repo been added
##### ACTUAL RESULTS

```
failing on apt-key command
```

### PR DESCRIPTION
**Pull request by hangsu-ma**
##### SUMMARY

Fixes #42534 
Similar reason behind https://github.com/ansible/ansible/pull/42443
apt_repository module calls apt-key to add new repo source on ubuntu.
apt-key does not respect http_proxy environment variable.
As a result, one would thought adding http_porxy env var using environment
will be sufficient, which is never the case and apt_repository will always fail
to add new repo behind proxy on ubuntu.

keyserver-options are used to pass in proxy settings for apt-key, example:
sudo apt-key adv --keyserver-options http-proxy=http://username:password@proxy.example.com:8080 --keyserver keyserver.ubuntu.com --recv-keys GPG_KEY

This fix read http_proxy environment variable and pass it on to apt-key using --keyserver-options.
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

apt_repository
##### ANSIBLE VERSION

```
all
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by hangsu-ma** [comment]
I actually have both https_proxy and no_proxy in the code, had to took them out pretty quickly, because they are not supported options, see error message below if you pass them in from --keyserver-options:
```
sudo apt-key adv --keyserver-options "http-proxy=http://username:password@proxy.example.com:8080 https-proxy=http://username:password@proxy.example.com:8080 https_proxy=http://username:password@proxy.example.com:8080 no-proxy=www.google.com no_proxy=www.google.com" --keyserver keyserver.ubuntu.com --recv-keys GPG_KEY
Executing: /tmp/apt-key-gpghome.zJ3uDH1oNy/gpg.1.sh --keyserver-options http-proxy=http://username:password@proxy.example.com:8080 https-proxy=http://username:password@proxy.example.com:8080 https_proxy=http://username:password@proxy.example.com:8080 no-proxy=www.google.com no_proxy=www.google.com --keyserver keyserver.ubuntu.com --recv-keys GPG_KEY
gpg: keyserver option 'https-proxy' is unknown
gpg: keyserver option 'https_proxy' is unknown
gpg: keyserver option 'no-proxy' is unknown
gpg: keyserver option 'no_proxy' is unknown
gpg: "GPG_KEY" not a key ID: skipping

```
below are my speculation due to the lack of documentation on keyserver-options:
* no proxy, this apt-key is hitting single URL(the key server) which is either in the proxy or outside the proxy, so no_proxy or such is needed. I guess apt-key will fail when there is a URL forward or redirect on key server that cross proxy (not sure if it's allowed by OpenPGP)
* https proxy, according to the answers on this: https://security.stackexchange.com/questions/4161/shouldnt-gpg-key-fetching-use-a-secure-connection
it's always on http protocal so https_proxy is not releveant and not supported.

**Comment by sashka** [comment]
I’d rather go the way of fixing low level tools to make them respect proxy
env vars. Otherwise every apt-related module tends to be a bundle of
workarounds for random edge cases.

**Comment by hangsu-ma** [comment]
Hi @sashka 

Agreed changing underlining system tools can fix this problem without Ansible code change. But this means an upgrade of these system package/s will be required, which might not be desired in all situations for obvious reasons.
Consider the common case where user need to install some common packages, but because their infra is behind proxy(which is very common in corp world, btw). They will have to upgrade to a newer version of their OS, this does not sound right. Also other alternative tools like Chef does not have this problem.

On the other hand, this change will fix the problem. I can see why you consider it a workaround for random edge case, but I would suggest it's a fix for an Ansible bug, which render apt_key and apt_repository modules broken for Ubuntu behind proxy. Unless there is a better approach available. 
I did some digging and listed details below, long in short, I can't see better solution atm, please let me know otherwise.

Furthermore, the changes are in Ansible implementation details and not exposed to user.  This is the precise reason one would use Ansible or an alternative for: Ansible handles the edge cases and workarounds, keep the playbook plain and simple.


some relevant information and documentations:
* https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761
* https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration-Options.html
* https://askubuntu.com/a/932370
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=162742
* https://github.com/debops/ansible-elastic_co/issues/2
* https://dev.gnupg.org/T1786


I am not openpgp expert, but what i get is 
* http_proxy is actually supported by low level tooling
* it is been ignored by default, and can be turned on by pass in honor-http-proxy

does not look like one can pass in honor-http-proxy at apt-key level.
```
root@vagrant:~# apt-key adv --keyserver-options honor-http-proxy --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
Executing: /tmp/apt-key-gpghome.R4SfNSiw6w/gpg.1.sh --keyserver-options honor-http-proxy --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
gpg: keyserver option 'honor-http-proxy' is unknown
^C
gpg: signal Interrupt caught ... exiting
root@vagrant:~# apt-key adv --honor-http-proxy --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
Executing: /tmp/apt-key-gpghome.0rxsxeRITg/gpg.1.sh --honor-http-proxy --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
gpg: WARNING: "--honor-http-proxy" is an obsolete option - it has no effect
```
Also tried to update config files in ~/.gnupg folder, didn't work.

So two other possible solution:
* enable honor-http-proxy by default for apt-key, so it will respect the proxy if exists. 
* use temp home dir for gnupg for the ansible process and use a temp conf file in which honor-http-proxy is specified

Both of them requires changes in apt-key or replace/rewrite it all together in apt_key and apt_repository modules, which sounds like overkill for me, and will also introduce future maintenance issues.
Let me know if it make any sense.

**Comment by maxamillion** [comment]
@sashka @hangsu-ma in respect to the "all apt modules have to carry a work around", would it make sense to create an `apt` focused `module_util` in order to provide a consistent solution to these kinds of situations?

**Comment by hangsu-ma** [comment]
The problem still persists on ubuntu 18.04, 19.04 and 19.10. I have tested the fixes on them as well using this [project](https://github.com/hangsu-ma/ansible-proxy-sandbox).

Just moved the change to latest code base, resulted in a force push sadly.
* fixed a NPL when no_proxy is not specified. 
* shared code between this one and https://github.com/ansible/ansible/pull/42443 are also moved into module_utils. 

[Here](https://github.com/hangsu-ma/ansible-proxy-sandbox) is a sandbox with bunch of vagrant boxes has no internet access but only a proxy, so one can work on this using a PC without needing a cooperation proxy.

**Comment by bebosudo** [comment]
I had the same issue on ubuntu 18.04; here's another version that uses less regex and more standard libraries: https://gist.github.com/bebosudo/91837eec70b3d06a9278b3c9ae5289f1
Feel free to use it if you find it useful for this PR.

**Comment by opoplawski** [comment]
Ping?  Just ran into this issue myself.

**Comment by nitzmahone** [comment]
Since apt-key is deprecated, bigger picture, we probably need to fix the underlying module to directly fetch the keys, eg: https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html - if we used fetch_url to do this, the system proxy config would be respected "for free".

**Comment by Abam** [comment]
Any plan to fix this issue ?

The apt_repository module  is still broken since 2018 (https://github.com/ansible/ansible/issues/42534).

**Pull request closed without merging**
