### PR TITLE
postgresql_user: add in_role support

### PR DESCRIPTION
**Pull request by nerzhul**
##### SUMMARY

This attribute permit a user to be part of multiple parent roles to inherit rights

Also cleanup some documentations part & refactor alter/create user parts for shared code

##### ISSUE TYPE
 - Feature Pull Request
- Docs Pull Request

##### COMPONENT NAME

postgresql_user

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

Add in_role attribute permit a user to be part of multiple parent roles to inherit rights.

Output didn't change

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/16267/12/tests

**Comment by nerzhul** [comment]
bot_info

**Comment by nerzhul** [comment]
bot_status

**Comment by Andersson007** [comment]
@nerzhul 
https://github.com/ansible/ansible/pull/53733 implements this, it has been merged recently
maybe is that enough? (atomic, flexible, etc)
I don't mind if this functionality will be also implemented in postgresql_user module.
However, IMO, better to close old unfinished PRs.
I suggest to close this one and open new if you decide to finish it.
Anyway, seems it will be easier than to fix all merge conflicts.
?

**Comment by Andersson007** [comment]
needs_info

**Pull request closed without merging**
