### PR TITLE
apk: Fix package dependency bug by checking world file

### LINKED ISSUE #34325: apk package dependencies not considered properly
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apk

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 16:23:06) [GCC 6.4.0]
```

##### OS / ENVIRONMENT
Alpine Linux 3.7.0

##### SUMMARY
If the apk plugin is used to install a package A that is already present as a dependency of package B, the /etc/apk/world file is not updated. Therefore, if the package B is uninstalled, package A is also uninstalled.

##### STEPS TO REPRODUCE
In three separate steps 1) install awall (with lua5.2 dependency), 2) install lua5.2, 3) uninstall awall.

```yaml
---
- name: test apk module
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add awall (with lua5.2 dependency)
      apk:
        name: awall
        update_cache: yes

    - name: Add lua5.2
      apk:
        name: lua5.2

    - name: Remove awall (with lua5.2 dependency)
      apk:
        name: awall
        state: absent
```

##### EXPECTED RESULTS
After running the three steps, the lua5.2 package should still be installed.

##### ACTUAL RESULTS
When uninstalling awall, the lua5.2 package is also uninstalled. See 'Purging lua5.2' in the output below.

```
localhost:~# ansible-playbook -i inventory apkdependencies.yaml -vv
ansible-playbook 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Dec 14 2017, 16:23:06) [GCC 6.4.0]
No config file found; using defaults
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: apkdependencies.yaml ***************************************************************************************************************************************************************************************************************
1 plays in apkdependencies.yaml

PLAY [test apk module] ***********************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Add awall (with lua5.2 dependency)] ****************************************************************************************************************************************************************************************************
task path: /root/apkdependencies.yaml:7
changed: [localhost] => {"changed": true, "failed": false, "msg": "installed awall package(s)", "packages": ["libxml2", "bind-libs", "bind-tools", "libmnl", "jansson", "libnftnl-libs", "iptables", "ip6tables", "ipset", "lua5.2", "lua5.2-alt-getopt", "lua5.2-cjson", "lua5.2-pc", "lua5.2-posix", "lua5.2-stringy", "xtables-addons", "awall"], "stderr": "", "stderr_lines": [], "stdout": "(1/17) Installing libxml2 (2.9.7-r0)\n(2/17) Installing bind-libs (9.11.2-r1)\n(3/17) Installing bind-tools (9.11.2-r1)\n(4/17) Installing libmnl (1.0.4-r0)\n(5/17) Installing jansson (2.10-r0)\n(6/17) Installing libnftnl-libs (1.0.8-r1)\n(7/17) Installing iptables (1.6.1-r1)\n(8/17) Installing ip6tables (1.6.1-r1)\n(9/17) Installing ipset (6.34-r0)\n(10/17) Installing lua5.2 (5.2.4-r4)\n(11/17) Installing lua5.2-alt-getopt (0.7-r8)\n(12/17) Installing lua5.2-cjson (2.1.0-r7)\n(13/17) Installing lua5.2-pc (1.0.0-r9)\n(14/17) Installing lua5.2-posix (33.4.0-r0)\n(15/17) Installing lua5.2-stringy (0.4.0-r5)\n(16/17) Installing xtables-addons (2.11-r1)\n(17/17) Installing awall (1.5.0-r0)\nExecuting busybox-1.27.2-r7.trigger\nExecuting awall-1.5.0-r0.trigger\nOK: 157 MiB in 72 packages\n", "stdout_lines": ["(1/17) Installing libxml2 (2.9.7-r0)", "(2/17) Installing bind-libs (9.11.2-r1)", "(3/17) Installing bind-tools (9.11.2-r1)", "(4/17) Installing libmnl (1.0.4-r0)", "(5/17) Installing jansson (2.10-r0)", "(6/17) Installing libnftnl-libs (1.0.8-r1)", "(7/17) Installing iptables (1.6.1-r1)", "(8/17) Installing ip6tables (1.6.1-r1)", "(9/17) Installing ipset (6.34-r0)", "(10/17) Installing lua5.2 (5.2.4-r4)", "(11/17) Installing lua5.2-alt-getopt (0.7-r8)", "(12/17) Installing lua5.2-cjson (2.1.0-r7)", "(13/17) Installing lua5.2-pc (1.0.0-r9)", "(14/17) Installing lua5.2-posix (33.4.0-r0)", "(15/17) Installing lua5.2-stringy (0.4.0-r5)", "(16/17) Installing xtables-addons (2.11-r1)", "(17/17) Installing awall (1.5.0-r0)", "Executing busybox-1.27.2-r7.trigger", "Executing awall-1.5.0-r0.trigger", "OK: 157 MiB in 72 packages"]}

TASK [Add lua5.2] ****************************************************************************************************************************************************************************************************************************
task path: /root/apkdependencies.yaml:12
ok: [localhost] => {"changed": false, "failed": false, "msg": "package(s) already installed"}

TASK [Remove awall (with lua5.2 dependency)] *************************************************************************************************************************************************************************************************
task path: /root/apkdependencies.yaml:16
changed: [localhost] => {"changed": true, "failed": false, "msg": "removed awall package(s)", "packages": ["awall", "bind-tools", "ip6tables", "ipset", "lua5.2", "lua5.2-alt-getopt", "lua5.2-cjson", "lua5.2-pc", "lua5.2-posix", "lua5.2-stringy", "xtables-addons", "bind-libs", "libxml2", "iptables", "libnftnl-libs", "libmnl", "jansson"], "stderr": "", "stderr_lines": [], "stdout": "(1/17) Purging awall (1.5.0-r0)\n(2/17) Purging bind-tools (9.11.2-r1)\n(3/17) Purging ip6tables (1.6.1-r1)\n(4/17) Purging ipset (6.34-r0)\n(5/17) Purging lua5.2 (5.2.4-r4)\n(6/17) Purging lua5.2-alt-getopt (0.7-r8)\n(7/17) Purging lua5.2-cjson (2.1.0-r7)\n(8/17) Purging lua5.2-pc (1.0.0-r9)\n(9/17) Purging lua5.2-posix (33.4.0-r0)\n(10/17) Purging lua5.2-stringy (0.4.0-r5)\n(11/17) Purging xtables-addons (2.11-r1)\n(12/17) Purging bind-libs (9.11.2-r1)\n(13/17) Purging libxml2 (2.9.7-r0)\n(14/17) Purging iptables (1.6.1-r1)\n(15/17) Purging libnftnl-libs (1.0.8-r1)\n(16/17) Purging libmnl (1.0.4-r0)\n(17/17) Purging jansson (2.10-r0)\nExecuting busybox-1.27.2-r7.trigger\nOK: 149 MiB in 55 packages\n", "stdout_lines": ["(1/17) Purging awall (1.5.0-r0)", "(2/17) Purging bind-tools (9.11.2-r1)", "(3/17) Purging ip6tables (1.6.1-r1)", "(4/17) Purging ipset (6.34-r0)", "(5/17) Purging lua5.2 (5.2.4-r4)", "(6/17) Purging lua5.2-alt-getopt (0.7-r8)", "(7/17) Purging lua5.2-cjson (2.1.0-r7)", "(8/17) Purging lua5.2-pc (1.0.0-r9)", "(9/17) Purging lua5.2-posix (33.4.0-r0)", "(10/17) Purging lua5.2-stringy (0.4.0-r5)", "(11/17) Purging xtables-addons (2.11-r1)", "(12/17) Purging bind-libs (9.11.2-r1)", "(13/17) Purging libxml2 (2.9.7-r0)", "(14/17) Purging iptables (1.6.1-r1)", "(15/17) Purging libnftnl-libs (1.0.8-r1)", "(16/17) Purging libmnl (1.0.4-r0)", "(17/17) Purging jansson (2.10-r0)", "Executing busybox-1.27.2-r7.trigger", "OK: 149 MiB in 55 packages"]}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0   
```

### PR DESCRIPTION
**Pull request by tdtrask**
Fixes: #34325

##### SUMMARY
Rather than checking if the package is installed, check to see if the package is in /etc/apk/world, where the top-level packages are defined. There is no current way to use 'apk' to distinguish packages that are installed as dependencies vs top-level.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
apk

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 16:23:06) [GCC 6.4.0]
```

##### ADDITIONAL INFORMATION
Here is the output for #34325 after the fix:
```
localhost:~# ansible-playbook -i inventory apkdependencies.yaml -vv
ansible-playbook 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Dec 14 2017, 16:23:06) [GCC 6.4.0]
No config file found; using defaults
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: apkdependencies.yaml ***************************************************************************************************************************************************************************************************************
1 plays in apkdependencies.yaml

PLAY [test apk module] ***********************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Add awall (with lua5.2 dependency)] ****************************************************************************************************************************************************************************************************
task path: /root/apkdependencies.yaml:7
changed: [localhost] => {"changed": true, "failed": false, "msg": "installed awall package(s)", "packages": ["libxml2", "bind-libs", "bind-tools", "libmnl", "jansson", "libnftnl-libs", "iptables", "ip6tables", "ipset", "lua5.2", "lua5.2-alt-getopt", "lua5.2-cjson", "lua5.2-pc", "lua5.2-posix", "lua5.2-stringy", "xtables-addons", "awall"], "stderr": "", "stderr_lines": [], "stdout": "(1/17) Installing libxml2 (2.9.7-r0)\n(2/17) Installing bind-libs (9.11.2-r1)\n(3/17) Installing bind-tools (9.11.2-r1)\n(4/17) Installing libmnl (1.0.4-r0)\n(5/17) Installing jansson (2.10-r0)\n(6/17) Installing libnftnl-libs (1.0.8-r1)\n(7/17) Installing iptables (1.6.1-r1)\n(8/17) Installing ip6tables (1.6.1-r1)\n(9/17) Installing ipset (6.34-r0)\n(10/17) Installing lua5.2 (5.2.4-r4)\n(11/17) Installing lua5.2-alt-getopt (0.7-r8)\n(12/17) Installing lua5.2-cjson (2.1.0-r7)\n(13/17) Installing lua5.2-pc (1.0.0-r9)\n(14/17) Installing lua5.2-posix (33.4.0-r0)\n(15/17) Installing lua5.2-stringy (0.4.0-r5)\n(16/17) Installing xtables-addons (2.11-r1)\n(17/17) Installing awall (1.5.0-r0)\nExecuting busybox-1.27.2-r7.trigger\nExecuting awall-1.5.0-r0.trigger\nOK: 157 MiB in 72 packages\n", "stdout_lines": ["(1/17) Installing libxml2 (2.9.7-r0)", "(2/17) Installing bind-libs (9.11.2-r1)", "(3/17) Installing bind-tools (9.11.2-r1)", "(4/17) Installing libmnl (1.0.4-r0)", "(5/17) Installing jansson (2.10-r0)", "(6/17) Installing libnftnl-libs (1.0.8-r1)", "(7/17) Installing iptables (1.6.1-r1)", "(8/17) Installing ip6tables (1.6.1-r1)", "(9/17) Installing ipset (6.34-r0)", "(10/17) Installing lua5.2 (5.2.4-r4)", "(11/17) Installing lua5.2-alt-getopt (0.7-r8)", "(12/17) Installing lua5.2-cjson (2.1.0-r7)", "(13/17) Installing lua5.2-pc (1.0.0-r9)", "(14/17) Installing lua5.2-posix (33.4.0-r0)", "(15/17) Installing lua5.2-stringy (0.4.0-r5)", "(16/17) Installing xtables-addons (2.11-r1)", "(17/17) Installing awall (1.5.0-r0)", "Executing busybox-1.27.2-r7.trigger", "Executing awall-1.5.0-r0.trigger", "OK: 157 MiB in 72 packages"]}

TASK [Add lua5.2] ****************************************************************************************************************************************************************************************************************************
task path: /root/apkdependencies.yaml:12
changed: [localhost] => {"changed": true, "failed": false, "msg": "installed lua5.2 package(s)", "packages": [], "stderr": "", "stderr_lines": [], "stdout": "OK: 157 MiB in 72 packages\n", "stdout_lines": ["OK: 157 MiB in 72 packages"]}

TASK [Remove awall (with lua5.2 dependency)] *************************************************************************************************************************************************************************************************
task path: /root/apkdependencies.yaml:16
changed: [localhost] => {"changed": true, "failed": false, "msg": "removed awall package(s)", "packages": ["awall", "bind-tools", "ip6tables", "ipset", "lua5.2-alt-getopt", "lua5.2-cjson", "lua5.2-pc", "lua5.2-posix", "lua5.2-stringy", "xtables-addons", "bind-libs", "libxml2", "iptables", "libnftnl-libs", "libmnl", "jansson"], "stderr": "", "stderr_lines": [], "stdout": "(1/16) Purging awall (1.5.0-r0)\n(2/16) Purging bind-tools (9.11.2-r1)\n(3/16) Purging ip6tables (1.6.1-r1)\n(4/16) Purging ipset (6.34-r0)\n(5/16) Purging lua5.2-alt-getopt (0.7-r8)\n(6/16) Purging lua5.2-cjson (2.1.0-r7)\n(7/16) Purging lua5.2-pc (1.0.0-r9)\n(8/16) Purging lua5.2-posix (33.4.0-r0)\n(9/16) Purging lua5.2-stringy (0.4.0-r5)\n(10/16) Purging xtables-addons (2.11-r1)\n(11/16) Purging bind-libs (9.11.2-r1)\n(12/16) Purging libxml2 (2.9.7-r0)\n(13/16) Purging iptables (1.6.1-r1)\n(14/16) Purging libnftnl-libs (1.0.8-r1)\n(15/16) Purging libmnl (1.0.4-r0)\n(16/16) Purging jansson (2.10-r0)\nExecuting busybox-1.27.2-r7.trigger\nOK: 149 MiB in 56 packages\n", "stdout_lines": ["(1/16) Purging awall (1.5.0-r0)", "(2/16) Purging bind-tools (9.11.2-r1)", "(3/16) Purging ip6tables (1.6.1-r1)", "(4/16) Purging ipset (6.34-r0)", "(5/16) Purging lua5.2-alt-getopt (0.7-r8)", "(6/16) Purging lua5.2-cjson (2.1.0-r7)", "(7/16) Purging lua5.2-pc (1.0.0-r9)", "(8/16) Purging lua5.2-posix (33.4.0-r0)", "(9/16) Purging lua5.2-stringy (0.4.0-r5)", "(10/16) Purging xtables-addons (2.11-r1)", "(11/16) Purging bind-libs (9.11.2-r1)", "(12/16) Purging libxml2 (2.9.7-r0)", "(13/16) Purging iptables (1.6.1-r1)", "(14/16) Purging libnftnl-libs (1.0.8-r1)", "(15/16) Purging libmnl (1.0.4-r0)", "(16/16) Purging jansson (2.10-r0)", "Executing busybox-1.27.2-r7.trigger", "OK: 149 MiB in 56 packages"]}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=3    unreachable=0    failed=0
```
In the second task, changed is true as the package is added as a top-level package (even though no install is done). In the third task, we see that lua5.2 is no longer purged.

Here is the output for #35062 after the fix:
```
localhost:~# ansible-playbook -i inventory apkdependencies2.yaml -vv
ansible-playbook 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Dec 14 2017, 16:23:06) [GCC 6.4.0]
No config file found; using defaults
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: apkdependencies2.yaml **************************************************************************************************************************************************************************************************************
1 plays in apkdependencies2.yaml

PLAY [test apk module] ***********************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Add awall (with lua5.2 dependency)] ****************************************************************************************************************************************************************************************************
task path: /root/apkdependencies2.yaml:7
changed: [localhost] => {"changed": true, "failed": false, "msg": "installed awall package(s)", "packages": ["libxml2", "bind-libs", "bind-tools", "libmnl", "jansson", "libnftnl-libs", "iptables", "ip6tables", "ipset", "lua5.2", "lua5.2-alt-getopt", "lua5.2-cjson", "lua5.2-pc", "lua5.2-posix", "lua5.2-stringy", "xtables-addons", "awall"], "stderr": "", "stderr_lines": [], "stdout": "(1/17) Installing libxml2 (2.9.7-r0)\n(2/17) Installing bind-libs (9.11.2-r1)\n(3/17) Installing bind-tools (9.11.2-r1)\n(4/17) Installing libmnl (1.0.4-r0)\n(5/17) Installing jansson (2.10-r0)\n(6/17) Installing libnftnl-libs (1.0.8-r1)\n(7/17) Installing iptables (1.6.1-r1)\n(8/17) Installing ip6tables (1.6.1-r1)\n(9/17) Installing ipset (6.34-r0)\n(10/17) Installing lua5.2 (5.2.4-r4)\n(11/17) Installing lua5.2-alt-getopt (0.7-r8)\n(12/17) Installing lua5.2-cjson (2.1.0-r7)\n(13/17) Installing lua5.2-pc (1.0.0-r9)\n(14/17) Installing lua5.2-posix (33.4.0-r0)\n(15/17) Installing lua5.2-stringy (0.4.0-r5)\n(16/17) Installing xtables-addons (2.11-r1)\n(17/17) Installing awall (1.5.0-r0)\nExecuting busybox-1.27.2-r7.trigger\nExecuting awall-1.5.0-r0.trigger\nOK: 157 MiB in 72 packages\n", "stdout_lines": ["(1/17) Installing libxml2 (2.9.7-r0)", "(2/17) Installing bind-libs (9.11.2-r1)", "(3/17) Installing bind-tools (9.11.2-r1)", "(4/17) Installing libmnl (1.0.4-r0)", "(5/17) Installing jansson (2.10-r0)", "(6/17) Installing libnftnl-libs (1.0.8-r1)", "(7/17) Installing iptables (1.6.1-r1)", "(8/17) Installing ip6tables (1.6.1-r1)", "(9/17) Installing ipset (6.34-r0)", "(10/17) Installing lua5.2 (5.2.4-r4)", "(11/17) Installing lua5.2-alt-getopt (0.7-r8)", "(12/17) Installing lua5.2-cjson (2.1.0-r7)", "(13/17) Installing lua5.2-pc (1.0.0-r9)", "(14/17) Installing lua5.2-posix (33.4.0-r0)", "(15/17) Installing lua5.2-stringy (0.4.0-r5)", "(16/17) Installing xtables-addons (2.11-r1)", "(17/17) Installing awall (1.5.0-r0)", "Executing busybox-1.27.2-r7.trigger", "Executing awall-1.5.0-r0.trigger", "OK: 157 MiB in 72 packages"]}

TASK [Remove lua5.2] *************************************************************************************************************************************************************************************************************************
task path: /root/apkdependencies2.yaml:12
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed to remove lua5.2 package(s)", "packages": [], "stderr": "", "stderr_lines": [], "stdout": "World updated, but the following packages are not removed due to:\n  lua5.2: awall\n\nOK: 157 MiB in 72 packages\n", "stdout_lines": ["World updated, but the following packages are not removed due to:", "  lua5.2: awall", "", "OK: 157 MiB in 72 packages"]}
	to retry, use: --limit @/root/apkdependencies2.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1  
```
In the second task, failed is true because the dependent lua5.2 package cannot be removed.

### CODE REVIEW

**Comment by tdtrask** [comment]
shipit

**Comment by abadger** [comment]
It would be great if you could get a user of this module to test it.  it's short enough that I think I can understand it but I could be mistaken because I'm unfamiliar with the packaging system.  I think that this change fixes the reported issue with package installation but breaks package removal (ie: removing a package which was installed as a dependency will not remove the package).  I think you need to have both the new and old versions of the query_package() function using the new version for package installation and the old version for package removal.

**Comment by tdtrask** [comment]
@abadger  Thank you for the review. The APK tool does not allow you to uninstall a package that is installed as a dependency. You can only uninstall top level packages. In fact, the add and del subcommands do not directly install or remove packages. What they do is add rules to the world file, which are then implemented by the package manager based upon dependencies. So, it makes sense to only look at those top level packages.

**Comment by abadger** [comment]
Okay... So, it seems like as a sysadmin I'd want "remove this package" (ie: state=absent) to either remove the package or error out. So the logic owuld be something like this pseudo code:
```
If pkg in /etc/apk/world:
    uninstall()
    if pkg_is_installed():
        fail_json('Package removed from apk/world but cannot remove package from system until dependent packages are removed')
else:
    if pkg is_installed():
        fail_json('cannot remove package until dependent packages are removed')
    else:
        exit_json('not installed')
```

But I'm not an apk/alpine linux user.  The best way to go might be to talk about it at the next irc meeting: https://github.com/ansible/community/issues/291 to get input from the other committers.

**Comment by tdtrask** [comment]
@abadger I decided to just return failed true when trying to uninstall dependent packages. If the playbook developer chooses, he can ignore the error. This seems more flexible than returning changed false, even though it doesn't match the apk tool as closely.

**Comment by abadger** [comment]
rebuild_merge

**Pull request merged**
