### PR TITLE
setup module: Replace . by _ in interface name

### PR DESCRIPTION
**Pull request by jpte**

### CODE REVIEW

**Comment by jctanner** [comment]
@jpte in testing this, I'm not actually seeing a difference in the results before and after your patch.

If I compare the regex versus simple string replace, it's doing the same thing:

```
jtanner@u1304:~/issues/5201-interface_rename$ cat testthis.py 
#!/usr/bin/python

import os
import sys
import re

def oldway(text):
    if ':' in text:
        text = text.replace(':','_')         
    return text    

def newway(text):
    to_replace = '[:\.]'
    if re.search(to_replace, text):
         text = re.sub(to_replace, '_', text)
    return text

textval = "eth0:0"
print oldway(textval)             
print newway(textval)             

jtanner@u1304:~/issues/5201-interface_rename$ python testthis.py 
eth0_0
eth0_0
```

What did this patch actually fix in your case?

**Comment by jpte** [comment]
This patch fix problem with jinja with vlan interface. Usually vlan interface has a dot (ie eth0.110) and jinja use dot to access attributes. So facts like ansible_eth0.110['ipv4']['address'] is not accessible.
Just try with: textval = "eth0.110"

**Comment by jctanner** [comment]
@jpte if we implemented this, how would a user differentiate a vlan from a secondary interface?

```
[root@el6 ~]# ifconfig -a | egrep ^eth0
eth0      Link encap:Ethernet  HWaddr 52:54:00:EB:72:6F
eth0.100  Link encap:Ethernet  HWaddr 52:54:00:EB:72:6F
eth0:0    Link encap:Ethernet  HWaddr 52:54:00:EB:72:6F
eth0:1    Link encap:Ethernet  HWaddr 52:54:00:EB:72:6F
```

**Comment by jctanner** [comment]
@jpte I'm closing this for the reason stated above. If you would like to propose a better solution for vlan interfaces, please start a thread on the ansible-devel mailing list for further collaboration.

**Pull request closed without merging**
