### PR TITLE
added bcrypt to usable hashes in password_hash filter

### LINKED ISSUE #46591: password_hash filter recognises bcrypt directly and not blowfish
##### SUMMARY
It is rather odd that to get a bcrypt hash with the password_hash filter one has to use blowfish as a hash. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
password_hash / core filter

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
```

```yaml
"{{ password | password_hash('bcrypt') }}"
statt
"{{ password | password_hash('blowfish') }}"
```

### PR DESCRIPTION
**Pull request by DerMolly**
##### SUMMARY
Fixes #46591

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by Akasurde** [comment]
@DerUser Thanks for this PR. You need to fix this first in devel version and create backport for 2.7. You can find docs for creating backport here - https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process Thanks.

**Comment by DerMolly** [comment]
@Akasurde Okay. So first I need to get a PR into devel? Like this?

**Comment by mdrose** [comment]
Is this actually necessary?

The relevant code, with context, is:

`252 def get_encrypted_password(password, hashtype='sha512', salt=None, salt_size=None, rounds=None):
253     passlib_mapping = {
254         'md5': 'md5_crypt',
255         'blowfish': 'bcrypt',
256         'sha256': 'sha256_crypt',
257         'sha512': 'sha512_crypt',
258     }       
259 
260     hashtype = passlib_mapping.get(hashtype, hashtype)`

If hashtype is set to bcrypt, it should still work, since the default passed to dict.get is hashtype.

It seems to me that passlib_mapping was made to translate common algorithm terms to the relevant attributes on the passlib.hash module. Having a mapping that maps to itself doesn't seem to serve any purpose.

Its not clear to me what is being fixed here.

**Comment by mdrose** [comment]
@DerUser
Is this really necessary?

For reference, the relevant code is as follows:
```
def get_encrypted_password(password, hashtype='sha512', salt=None, salt_size=None, rounds=None):
    passlib_mapping = { 
        'md5': 'md5_crypt',
        'blowfish': 'bcrypt',
        'sha256': 'sha256_crypt',
        'sha512': 'sha512_crypt',
    }   

    hashtype = passlib_mapping.get(hashtype, hashtype)
    try:
        return passlib_or_crypt(password, hashtype, salt=salt, salt_size=salt_size, rounds=rounds)
    except AnsibleError as e:
        reraise(AnsibleFilterError, AnsibleFilterError(str(e), orig_exc=e), sys.exc_info()[2])
```
If hashtype="bcrypt", then it will be "bcrypt", since the default to dict.get is hashtype. It doesn't require "blowfish" to be entered to get "bcrypt".

It seems to me that the purpose of passlib_mapping is to translate common algorithm names to the equivalent attributes on the passlib.hash module. Adding a bcrypt => bcrypt mapping doesn't make much sense.

I'm not sure what this is fixing.

**Comment by DerMolly** [comment]
It seems it know works.

I testes with a colleage (he was using 2.7.0 stable and I used 2.6.5). It did not work on both systems. He just tried again and it worked. Not sure where to problem was here, but hey it works.

Thanks for the help and sorry to bother

**Pull request closed without merging**
