### PR TITLE
Local chroot support

### PR DESCRIPTION
**Pull request by mmoya**
Add support for acting on a local chroot. This could be use for building a preconfigure virtual OS image starting from a raw distro bootstrap.

This feature requires running ansible as `root` and using connection `local`.

Includes two fixes for fails when `/proc` is not mounted.
## Using

Example of use with a Debian boostrap:
- `sudo deboostrap squeeze /tmp/squeeze-chroot`
- `sudo -E ansible-playbook -vvv -c local --chroot=/tmp/squeeze-chroot test.yml`

an example `test.yml` could be:

```

---
- hosts: localhost

  tasks:

     - name: echo something to temp
       shell: echo Yaaayy! >/tmp/foobar.txt

     - name: install a package
       apt: pkg=less state=latest
```

works also by setting `chroot` in the playbook, like:

```

---
- hosts: localhost
  connection: local
  chroot: /tmp/squeeze-chroot
  ...
```

In principle any playbook would work by just adding `-c local --chroot=/path/to/dir`.
## Notes

Assumptions about existence of local files created by actions should not be made. For example `test/lookup_plugings.yml` fails in `test with_sequence, fenceposts 1` because it expects a local `/tmp/seq-00` created by previous action, but the creation actually took place in the chroot (ie: the file created was `$CHROOTDIR/tmp/seq-00` instead of `/tmp/-seq00`).

### CODE REVIEW

**Comment by mpdehaan** [comment]
Slick.  I'll take a look at this this weekend.

Thanks!

**Comment by mpdehaan** [comment]
BTW, looks like you have a stray "print" in there in one place... not a big deal, but if you can update, that would be good.
-        print self.chroot

**Comment by dhozac** [comment]
Hmm. Does this not make more sense as its own connection plugin, rather than messing with local? As-is, this would prevent local_action from executing locally (i.e. outside of the chroot). A connection plugin of its own also means you could address multiple chroots at once, just like regular hosts, and lets you specify chroot locations in your inventory rather than in the playbook.

**Comment by mpdehaan** [comment]
I can see that being useful.

If you are using it to build a single image, it's a _bit_ of extra work,
but just a super tiny amount, to make a inventory file with just one
"host", or just to say -i "/path/to/chroot," on the command line.

**Comment by mmoya** [comment]
Actually I started doing this by copying `local.py` to `chroot.py` but differences were less than expected and decided to tweak `local.py`. Didn't considered having multiple chroots but it's a nice idea.

Something like `-i /path/to/chroot` is nice too. It's a pain having a separate hosts file for `localhost` only.

I'll work on these issues.

**Comment by mpdehaan** [comment]
Note when using -i with strings the trailing comma is required

**Comment by mpdehaan** [comment]
Ok, please resubmit when it works as a connection type called 'chroot'.  I am very excited to have this, but I think that would be cleaner and more consistent.  If it is a lot like the local plugin that is ok with me.

It would also mean we would not need to have 'chroot' as an option on the various objects, so it may end up actually being simpler!

**Pull request closed without merging**
