### PR TITLE
Improvements to ec2 autoscaling modules

### PR DESCRIPTION
**Pull request by willthames**
- Added desired_capacity and vpc_zone_identifier to ec2_asg
- Use ec2_argument_spec() method and then remove unnecessary
  declarations from argument_spec
- Remove AWS_REGIONS declaration
- Rename block_device_mappings to volumes to be consistent with ec2
- Remove all pep8 warnings except line length and continuation indent
- Use updated module_utils/ec2.py to add profile and security_token
  support
- Remove mandatory arguments for delete to make launchconfig deletion
  work
- Handle existing launch configurations better
- Improve output information
- Improve documentation

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks like this one now has a few conflicts, can you rebase this one?

Thank you!

**Comment by timperrett** [comment]
@mpdehaan i resolved the merge conflict and sent a PR to @willthames's fork on the branch this PR is generated from, which if merged should make this PR in turn auto-mergeable. There's a lot of noise in the PR but its just a merge with current master and resolving the one conflict.

https://github.com/willthames/ansible/pull/1

**Comment by timperrett** [comment]
That being said, this PR also does some strange things IMHO, like it requires `vpc_zone_identifier` and the documentation of requiring `instance_type` is inconsistant with the implementation. @willthames perhaps you'd like to work together on getting this module up together? I have a pressing need for this so am trying to get over the hump :-)

**Comment by willthames** [comment]
@timperrett - good point - neither vpc_zone_identifier nor desired capacity are required for boto.ec2.autoscale.group.AutoScalingGroup() so I've removed them from the list of enforced arguments. 

Let me know if there are any other issues.

**Comment by timperrett** [comment]
@willthames i sent you one more PR to fix the missing colon in a for loop, and then it should be good. at least the functionality is working as it should now :-)

**Comment by willthames** [comment]
Ok, pushed the results of fixing that.

**Comment by timperrett** [comment]
Ok cool. Ready to merge I'd say - I gave it a jolly good smoke test and it's working now (at least, it appears to be giving the expected results)

**Comment by timperrett** [comment]
@mpdehaan might it be possible to have these updates merged in? Thanks for your consideration :-)

**Comment by mpdehaan** [comment]
merged, thanks everyone!

**Pull request merged**
