### PR TITLE
ec2_ami: add integration tests

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Added integration tests for ec2_ami. There are a few things broken with launch permissions and idempotence. There is a PR to port this module to boto3 here: #28506.

##### ISSUE TYPE
 - Tests Pull Request

##### COMPONENT NAME
test/integration/targets/ec2_ami/tasks/main.yml

##### ANSIBLE VERSION
```
2.5.0
```

### CODE REVIEW

**Comment by s-hertel** [comment]
cc @willthames @wilvk Here are some cursory integration tests for ec2_ami. Going to run these on the version ported to boto3 and then I'll leave feedback on that pull request.

**Comment by willthames** [comment]
Looks like we need ec2:DescribeSubnets adding to the AWS permissions (for local testing, hacking/aws_config/ec2-policy.json already allows ec2:Describe*)

I've also had to add {Create,Delete}{Snapshot,Image} to the ec2-policy, as well as fix the RunInstances permission. I've pushed a couple of commits to your branch to reflect this.

For some reason in my tests the block isn't working (i.e. failures during `block` aren't triggering the cleanup in `always`. Need to investigate that further, I'll raise a separate issue if necessary.

**Comment by willthames** [comment]
Fixed the `block`/`always` issue by removing the `-` in front of always, which effectively made them separate blocks, so the cleanup wasn't working

**Comment by willthames** [comment]
I've squashed my commits to a single commit on top of yours.

**Comment by mattclay** [comment]
CI failure due to lack of permissions. I'm working on updating the permissions.

**Comment by s-hertel** [comment]
Thanks very much @willthames and @mattclay.

**Comment by mattclay** [comment]
Permissions have been updated. Tests are now passing.

@s-hertel I noticed that the tests are leaving behind a snapshot, yet there is a task to delete the snapshot in the always block. I'm not sure what's happening there.

**Comment by willthames** [comment]
@mattclay, I *think* that's because three snapshots are created and we might only implicitly clean up one and explicitly clean up another. I'll see if we can close that gap.

**Comment by willthames** [comment]
Ok, only two snapshots were being created and only one was being explicitly deleted. Fixed in latest version. Also made the snapshot assertions work. 

A fresh run on my machine has this leaving no snapshots behind. As such, once tests pass, I'll merge.

**Comment by mattclay** [comment]
CI failure in Python 3 integration tests:

```
Traceback (most recent call last):
  File "/tmp/ansible_e44v27uj/ansible_module_ec2_snapshot_facts.py", line 242, in <module>
    main()
  File "/tmp/ansible_e44v27uj/ansible_module_ec2_snapshot_facts.py", line 238, in main
    list_ec2_snapshots(connection, module)
  File "/tmp/ansible_e44v27uj/ansible_module_ec2_snapshot_facts.py", line 193, in list_ec2_snapshots
    snapshots = connection.describe_snapshots(SnapshotIds=snapshot_ids, OwnerIds=owner_ids, RestorableByUserIds=restorable_by_user_ids, Filters=filters)
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 575, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 630, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python3.5/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter OwnerIds, value: <map object at 0x7ff577511048>, type: <class 'map'>, valid types: <class 'list'>, <class 'tuple'>
```

**Comment by willthames** [comment]
Ah right, that'd be why @s-hertel commented that test out ;). It worked on my machine. Will have to test with python3.

Edit: ah, I see, it'll be a ec2_snapshot_facts bug with python3. I won't fix that here. I'll comment out the tests again and repush.

**Pull request merged**
