### PR TITLE
Fortinet FortiManager Device Groups Module

### PR DESCRIPTION
**Pull request by lweighall**
##### SUMMARY

This module allows the addition and deletion of both device groups and device group members within FortiManager CMDB. 

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

fmgr_device_group.py
test_fmgr_device_group.py
##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 6069ce5975) last updated 2018/02/06 19:33:23 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/ansible_ftnt/library']
  ansible python module location = /root/ansibleSource/ansible/lib/ansible
  executable location = /root/ansibleSource/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by lweighall** [comment]
Hello,

Any update on this Pull Request? Any thing I can do to help push it through?

**Comment by gundalow** [comment]
Hi,
The team is currently focusing on the final parts for  Ansible 2.5.0 and 2.5.1

New modules, once merged, will go into Ansible 2.6, so we have some time.

**Comment by mattclay** [comment]
The test `ansible-test sanity --test validate-modules` failed with 2 errors:

```
lib/ansible/modules/network/fortimanager/fmgr_device_group.py:0:0: E324 Value for "default" from the argument_spec (None) for "state" does not match the documentation ('present')
lib/ansible/modules/network/fortimanager/fmgr_device_group.py:0:0: E326 Value for "choices" from the argument_spec (['absent', 'param_absent', 'present']) for "state" does not match the documentation (['absent', 'present'])
```

The bot seems to have missed commenting on this (it will probably do so after my comment).

**Comment by lweighall** [comment]
@mattclay fixed the state parameter -- should be all good.

**Comment by maxamillion** [comment]
Hello and thank you for the pull request! I wanted to note that Ansible uses [pytest](https://docs.pytest.org/en/latest/) for it's unit tests as documented [here](https://docs.ansible.com/ansible/devel/dev_guide/testing_units.html#structuring-unit-tests). Please update your unit tests.

**Comment by lweighall** [comment]
Consolidating/Recreating this PR in a few weeks. Much has changed.

**Pull request closed without merging**
