### PR TITLE
Bump azure-pipelines-test-container to v4.0.1 @ CI

### PR DESCRIPTION
**Pull request by webknjaz**
This patch updates the test container used in CI to the new v4 that defaults to using Python 3.10 and is based on Ubuntu 22.04 Jammy[[1]].

[1]: https://github.com/ansible/azure-pipelines-test-container/pull/17

##### SUMMARY

$sbj.

##### ISSUE TYPE

- Maintenance Pull Request
- Test Pull Request

##### COMPONENT NAME

CI

##### ADDITIONAL INFORMATION

Refs:
* https://github.com/ansible/ansible/issues/80424
* https://github.com/ansible/azure-pipelines-test-container/pull/17

### CODE REVIEW

**Comment by webknjaz** [comment]
It's weird that the unit tests for Python 3.9, 3.10 and 3.11 fail with this:
> 01:21 ERROR: Ansible requires Python 3.9 or newer on the controller. Current version: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]

**Review by mattclay — DISMISSED** [review]
This PR should only update the container. Changing shebangs should be a separate discussion -- and if we decide to go that route, a separate PR.

**Comment by webknjaz** [comment]
@mattclay this seems unrelated.. Are these new Apline-related issues?
```python-traceback
00:53 --> Run command: openssl passwd -5 -stdin
00:53 Traceback (most recent call last):
00:53   File "/home/alpine/ansible/test/results/.tmp/integration/ansible-test-container-jmm0pojp-ÅÑŚÌβŁÈ/test/integration/targets/ansible-test-container/./runme.py", line 1090, in <module>
00:53     main()
00:53   File "/home/alpine/ansible/test/results/.tmp/integration/ansible-test-container-jmm0pojp-ÅÑŚÌβŁÈ/test/integration/targets/ansible-test-container/./runme.py", line 77, in main
00:53     bootstrapper.run()
00:53   File "/home/alpine/ansible/test/results/.tmp/integration/ansible-test-container-jmm0pojp-ÅÑŚÌβŁÈ/test/integration/targets/ansible-test-container/./runme.py", line 1059, in run
00:53     super().run()
00:53   File "/home/alpine/ansible/test/results/.tmp/integration/ansible-test-container-jmm0pojp-ÅÑŚÌβŁÈ/test/integration/targets/ansible-test-container/./runme.py", line 801, in run
00:53     cls.configure_root_user()
00:53   File "/home/alpine/ansible/test/results/.tmp/integration/ansible-test-container-jmm0pojp-ÅÑŚÌβŁÈ/test/integration/targets/ansible-test-container/./runme.py", line 814, in configure_root_user
00:53 __main__.SubprocessError: Command `openssl passwd -5 -stdin` exited with status: 127
00:53 >>> Standard Error
00:53 Error relocating /usr/bin/openssl: OSSL_CMP_MSG_update_recipNonce: symbol not found
00:53 WARNING: Skipping retry of test target "ansible-test-container" since it has been excluded from retries.
```

```console
01:21 TASK [Create self-signed cert] *************************************************
01:21 task path: /root/ansible/test/results/.tmp/integration/ansible-galaxy-t2prle4s-ÅÑŚÌβŁÈ/test/integration/targets/ansible-galaxy/setup.yml:35
01:21 <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
01:21 <127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
01:21 <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1685463437.7761207-1063-149882778710304 `" && echo ansible-tmp-1685463437.7761207-1063-149882778710304="` echo /root/.ansible/tmp/ansible-tmp-1685463437.7761207-1063-149882778710304 `" ) && sleep 0'
01:21 Using module file /root/ansible/lib/ansible/modules/command.py
01:21 <127.0.0.1> PUT /root/.ansible/tmp/ansible-local-952snmghg0v/tmpynab_8de TO /root/.ansible/tmp/ansible-tmp-1685463437.7761207-1063-149882778710304/AnsiballZ_command.py
01:21 <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1685463437.7761207-1063-149882778710304/ /root/.ansible/tmp/ansible-tmp-1685463437.7761207-1063-149882778710304/AnsiballZ_command.py && sleep 0'
01:21 <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.10 /root/.ansible/tmp/ansible-tmp-1685463437.7761207-1063-149882778710304/AnsiballZ_command.py && sleep 0'
01:21 <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1685463437.7761207-1063-149882778710304/ > /dev/null 2>&1 && sleep 0'
01:21 fatal: [localhost]: FAILED! => {
01:21 }
01:21 
01:21 PLAY RECAP *********************************************************************
01:21 localhost                  : ok=5    changed=3    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
```

**Comment by mattclay** [comment]
@webknjaz Yeah, that's unrelated to this PR. I didn't see that in the nightly runs, so either it's a very new failure, or intermittent (or both).

**Comment by webknjaz** [comment]
> it's a very new failure, or intermittent (or both).

I think it's the new one because it happened in two jobs and seems to be unrelated to networking..

**Comment by mattclay** [comment]
@webknjaz I restarted the failing tests and they're passing now.

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
I've converted this to a draft, so it doesn't get merged until the other branches are tested and the VM image is updated.

**Pull request merged**
