### PR TITLE
Aix efix added

### PR DESCRIPTION
**Pull request by flynn1973**
##### SUMMARY
Installs and removes AIX efixes delivered by an nfs mount.
If "name= ALL" is given, it removes all efixes installed which are not on the share, and installs all efixes which are present on the share, but not currently installed.
 If a single efix is given as a parameter, this will be installed or removed.
##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
aix_efix

##### ADDITIONAL INFORMATION
Examples:
```yaml
# Synchronize ALL efixes from the NIM_MASTER on the standard share
- name: Install All efixes
  aix_efix:
    name:
      - ALL
# Install efix IV91487s3 from the nfs_server: rn100pgpl.itc.testlab.intranet from the share: /export/nim/aix7104-03/lpp_new
- name: Install efix IV91487s3
  aix_efix:
    name:
      - IV91487s3
    nfs_server: rn100pgpl.itc.testlab.intranet
    nfs_share: /export/nim/aix7104-03/lpp_new
# Remove efix IV91487s3
- name: remove efix IV91487s3
  aix_efix:
    name:
      - IV91487s3
    state: absent



```

### CODE REVIEW

**Comment by flynn1973** [comment]
how to avoid mixing up pr's? i have no ideao why two commits ending up here, as i branch before every commit?

**Comment by molekuul** [comment]
@flynn1973 Hi, this module was not ready just for a pull request, that why I didn't do that before.
please contact me about your fork of my AIX-ansible-modules role, where you found this module.

Kind regards,

Joris Weijters

**Comment by flynn1973** [comment]
thanx for chiming in, i tried to contact you beforehand over github but there were no response. anyway, there is an aix pinboard on github, would be nice if you participate, as your modules are quite usefull.

https://github.com/ansible/community/issues/421

**Comment by molekuul** [comment]
> 
> 
> thanx for chiming in, i tried to contact you beforehand over github but there were no response. anyway, there is an aix pinboard on github, would be nice if you participate, as your modules are quite usefull.
> 
> [ansible/community#421](https://github.com/ansible/community/issues/421)

Hi @flynn1973 

can we have some contact about these module, some contain a bit of information originating from my customer, i want them to be anonymous. Some are for a specific need, like this efix module, or the aix_facts module, these are not realy usable ansible modules if your nimserversetup isn't very specific.
this makes them not general usable. I update my settings. You can find my email address in my github page.


kind regards,
Joris Weijters

**Comment by flynn1973** [comment]
of course, feel free to contact me whenever you want.

**Comment by molekuul** [comment]
> 
> 
> of course, feel free to contact me whenever you want.

how do i contact you?

**Comment by flynn1973** [comment]
i already updated my email settings.

**Comment by d-little** [comment]
Should this PR be closed, with a new 'generic' module written?  Or are we hoping to update and merge this particular PR eventually?

@flynn1973  @molekuul

**Comment by flynn1973** [comment]
what to you mean with "new generic module"? i use this module on a daily basis and it works perfectly well.

**Comment by flynn1973** [comment]
folks, please review to get it merged before collections makes things even more complicated.

**Pull request closed without merging**
