### PR TITLE
Finalize task parameter values from include actions

### PR DESCRIPTION
**Pull request by wholroyd**
This is a proposed fix to the issue described in https://github.com/ansible/ansible/issues/14135.

In summary, task parameters from include actions aren't finalized and will still reference `"{{ item }}"` even if you've assigned the value of it to another variable. This causes issues where you want to use the value from a parent with_\* loop inside a child with_\* loop. This does not change the behavior of `"{{ item }}"` being overwritten in child loops, only the behavior of other variables that happen to reference `"{{ item }}"` and shouldn't.

### CODE REVIEW

**Comment by jimi-c** [comment]
I vaguely remember a reason we specifically do not do this, though it escapes me now. During the original development of the include functionality we had originally been passing back the variables as templated during the post_validate() step of the task, which caused a problem of some kind, so I have concerns that we're going to run into that again by doing this.

**Comment by wholroyd** [comment]
I started to write some unit tests for it and think I found the issue with the implementation as to why you guys didn't do this. The outer loop doesn't advance, so you repeat the same value for N items in the loop.

I wonder if backing up `job_vars`, templating the vars, executing the loop, and then restoring the vars (updating other values from the iteration of course) would help, because on the next iteration on the parent loop, any vars based on `"{{ issue }}"` should then get evaluated correctly. Somewhere in `task_executor.py:212-251 -> _run_loop(self, items)`.

I'll play with it and I'm open to suggestions.

**Comment by wholroyd** [comment]
Here is the reworked code to remove the side effect you were probably noting above, and the one that I experienced. This is more of an issue when using with_\* loops than a task include, so nothing here targets a task include anymore. I've been able to run it on my playbooks without any issues and it was able to finally complete the tasks successfully.

**Comment by wholroyd** [comment]
The only side effect of the current set of changes is that the value of `{{ item }}` will always represent what the value is according to the outermost with_\* loop. Once I figure out how to correct that to show the current level's value, then we should be good.

**Comment by bcoca** [comment]
This might create unexpected errors for variables that do not have the data defined prior to the include:

```
- include: vlad.yml
  vars:
    later: "{{from_included_task|last}}"
```

**Comment by wholroyd** [comment]
@bcoca In this particular PR, what I've changed should only finalize task parameters on task `include` actions when used with `with_*` because loops are only temporarily evaluated for their parameters and then finalized/executed later on. With the current value of `item` being held at the `play` level, it's not known until execution - but at that point it's too late to finalize other variables making references back to `item`, especially in instances where each of those variables were meant to reference entirely different `item` values.

While I see the value of having the kind of flexibility you've pointed out, that seems like misplaced logic in this scenario. Especially when the overall effort of Ansible is to supposedly to create reusable and shareable modular code via roles, playbooks, and tasks. Using a filter of a variable from within the module (in this case, a task file) to be used later on within the same module violates modularization.

Your example should still work as expected, unless you add a `with_*` to the action.

**Comment by sivel** [comment]
Thank you very much for your submission.  We have discussed this and decided against accepting this feature.

We believe that this would adversely affect the ability to rely on much of the dynamic capabilities that includes provide.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
