### PR TITLE
Add headers parameter to the maven_artifact module

### PR DESCRIPTION
**Pull request by alucas**
##### SUMMARY

Add new parameter to the maven_artifact module to allow http headers customisation.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

maven_artifact

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by tumbl3w33d** [comment]
I tested it and it does the trick. Not sure the doc line `Can be used to SSO Authentication` is really necessary here, because those who need it for that purpose, will know anyway and all the others won't need custom headers. But that's just my 2 cents. Let's see what @turb thinks.

**Comment by Akasurde** [comment]
@alucas What do you think about @tumbl3w33d's comment ? I think @tumbl3w33d has a point. Let me know. Thanks for the contribution.

**Comment by turb** [comment]
I agree with @tumbl3w33d: the PR looks fine, only the second line comment should be removed since this param may be used for many purposes.

**Comment by alucas** [comment]
@tumbl3w33d You're right, that comment was unnecessary. So I removed it.
@Akasurde @turb Thx.

**Comment by tumbl3w33d** [comment]
shipit

**Comment by turb** [comment]
shipit

**Comment by Akasurde** [comment]
bot_status

**Comment by Akasurde** [comment]
@alucas Thanks for the contribution. @tumbl3w33d @turb Thanks for the review.

**Pull request merged**
