### PR TITLE
disable_excludes

### PR DESCRIPTION
**Pull request by lunarfs**
##### SUMMARY
we have exclude=kernel* in our yum.conf file, and want a way to install it such that ansbel only returns changed when it actually did install something therefore I have been looking at various attempts at implementing this. This implementation is inspired by 
@jfchevrette
https://github.com/ansible/ansible-modules-core/issues/3629
and 
@rm-you who did
https://github.com/ansible/ansible/pull/41506/files

add ansible option to disable_excludes on yum 3.4+

##### ISSUE TYPE

Feature Pull Request
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

```
ansible 2.6.1
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by rm-you** [comment]
Yeah, awesome! This plus the downloadonly PR will take care of the two big issues I've been looking to solve. Thanks for taking care of this piece!

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by lunarfs** [comment]
Thanks to @jfchevrette and @rm-you for getting this started, thanks tp @maxamillion  for taking the time to get this merged, it means alot to us to get this feature in. Thanks to @SaaldjorMike for pre revieving the code.

**Comment by lfrancke** [comment]
I've looked at the code and tried this on 2.7 and I can't get it to work.

I want to specify a repository (e.g. `disable_excludes: foobar`) but that fails:

    "value of disable_excludes must be one of: all, main, repoid, got: foobar"

This looks like it's too restrictive and should really allow all strings.
Unless I'm mistaken I'll submit a patch that removes the `choices` so it can be used with any string.
And...it looks like this pull request doesn't add a test for the added functionality?

**Comment by lfrancke** [comment]
I see that someone already beat me to it in #47085

**Pull request merged**
