### PR TITLE
New features request

### PR DESCRIPTION
**Pull request by ovcharenko**
New features:
- Added existing_only options to skip creating new files on receiver

### CODE REVIEW

**Comment by jsmartin** [comment]
Glad to see there's other work on this. Since you've got way more features than I do, maybe you should try to pull in the option I have for application profiles.

Also, it looks like you're pulling in a change to the synchronize module on this pull request.  Watch out for other files sneaking into the pull request. 

One last thing, the best way to get the path to the ufw command is using something like this:

ufw_bin = module.get_bin_path('ufw')

Great work!

**Comment by srgvg** [comment]
@ovcharenko I expect you'll be asked to split this in separate PR's

**Comment by ovcharenko** [comment]
I'm glad you liked it. Yes, I will merge your application profiles.

**Comment by ovcharenko** [comment]
Please take a look at https://github.com/ovcharenko/ansible/commit/1ad51b0192a2e76d2aa65e12ae42172661214ae8

**Comment by mpdehaan** [comment]
This commit now contains a lot of mixed up commits, where you need to submit a feature only on it's own branch to avoid this.

The description for this submission is also insufficient.

I'm closing this ticket.

**Pull request closed without merging**
