### PR TITLE
Add new event v2_runner_on_task_start to allow callback by host task

### PR DESCRIPTION
**Pull request by joaocpinto**
Add new event v2_runner_on_task_start to allow callback by host task

##### SUMMARY
This change exposes a new event callback on each runner task start.

The main purpose is to allow a greater control on callback plugins.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
WorkerProcess
TaskExecutor
StrategyBase

##### ANSIBLE VERSION
```
ansible 2.4.0 (runner_on_task_start_callback 4aa8dd48f5) last updated 2017/06/20 17:57:14 (GMT +100)
```

### CODE REVIEW

**Comment by joaocpinto** [comment]
Hi,

Does it makes sense to rebase this or do you think it should not be applied and we should close it?

**Comment by mkrizek** [comment]
@sivel isn't this what you did in #47684?

**Comment by sivel** [comment]
@mkrizek yes, that merged PR obsoletes this PR.

Closing.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by joaocpinto** [comment]
That's awesome :) thanks

**Pull request closed without merging**
