### PR TITLE
A module for notifications through the Slack.com platform

### PR DESCRIPTION
**Pull request by ramondelafuente**
This module can send messages through Slack.com, and supports all options
available in the "incoming webhook integration".
- text
- channel
- username
- icon_url / icon_emoji
- link_names
- parse

### CODE REVIEW

**Comment by mpdehaan** [comment]
Does Slack have a users page somewhere so we could gauge the level of updake on this service?

Thanks!

**Comment by dirtyharrycallahan** [comment]
https://slack.com/love

**Comment by ramondelafuente** [comment]
Honestly, I just signed up two days ago. Loving the **\* out of it. Took 4 hours to get everything integrated for the team (5) - then about twice that to write the module because, well... Ansible all the things.

**Comment by alirayl** [comment]
Here's our latest growth chart, which includes usage numbers: 
image.

(from https://twitter.com/SlackHQ/status/443823101491425280)

**Comment by mpdehaan** [comment]
Thanks, that's more than sufficient, I think.

We want to avoid adding modules for services that might not have enough Ansible users, but when the code is simple, these things are easy to keep in there, and it lets people browse what has integration so they can choose what services to pick.

**Comment by mpdehaan** [comment]
merged, thank you!

**Comment by alirayl** [comment]
Thank you very much! We'll figure out the appropriate way to link this up on our site as well.

**Pull request merged**
