### PR TITLE
Add $LOOKUP(<lookup plugin>,<data>) as a templating option

### PR DESCRIPTION
**Pull request by dhozac**
Also moves file and pipe to lookup_plugins, and adds lines which works like pipe but returns a list with lines split.

### CODE REVIEW

**Comment by mpdehaan** [comment]
looks good, thanks!

Looks like we may want a test for 'lines'.

**Comment by dhozac** [comment]
It would need to be a playbook test, as lines doesn't make sense with $LOOKUP, only as with_lines:. I guess they should all have playbook tests though, so I'll add some.

**Comment by mpdehaan** [comment]
Yeah constructing playbook tests are somewhat annoying.   Don't worry about
it.

It might be nice to let them operate on strings so we can do inline many
playbooks or something later.

something that takes just one line, should be ok, just to prove there are
no errors in the module

**Comment by dhozac** [comment]
Tests added.

I didn't make it do inline-playbooks, as that would require rather invasive changes in e.g. the playbook parser. I also don't think it's really necessary, the playbook tests aren't that hard to add.

**Comment by dhozac** [comment]
I also like having the test playbooks as real files, as you can then run ansible-playbook on it yourself to see if things look right before setting expected, for instance.

**Comment by mpdehaan** [comment]
Looks like we would also want to add the test for $LOOKUP(pipe, '...') (or however that works with quoting) since that's what the commit is about.   I can add docs from there once we have the example.

**Comment by dhozac** [comment]
Done.

**Comment by mpdehaan** [comment]
thanks!

**Pull request merged**
