### PR TITLE
Bugfix: passing aws profile_name if boto_profile is set when connecting to Route53

### PR DESCRIPTION
**Pull request by eonwhite**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
EC2 dynamic external inventory script (ec2.py)

##### ANSIBLE VERSION
2.2.1.0

##### SUMMARY
The current script does not respect the boto_profile option when connecting to Route53 and attempting to use a non-default profile.

This is a small bugfix to cause it to respect that option. It has been tested in production.

### CODE REVIEW

**Comment by willthames** [comment]
shipit

**Comment by eonwhite** [comment]
It looks like another version of this, accomplishing the same thing, got merged. I think my version is slightly cleaner and more in keeping with the style of the rest of the code, so I've resolved the merge conflict. However if you would like me to close the PR (since the functionality is now there), no worries -- just let me know.

**Comment by willthames** [comment]
I'd just say to close this one, it's slightly tidier but as you say, the functionality is now there

**Comment by eonwhite** [comment]
No problem, closing away.

**Pull request closed without merging**
