### PR TITLE
Plugin mysql_user: add MySQL v8 privileges to valid privs

### PR DESCRIPTION
**Pull request by UncertaintyP**
##### ISSUE TYPE

- * Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by UncertaintyP** [comment]
The failed test ( mysql_user-_rciy37a / /root/.ansible/test/tmp/mysql_user-5pef8z6s-ÅÑŚÌβŁÈ/test/integration/targets/setup_mysql_db/tasks/main.yml:84 / [testhost] testhost: setup_mysql_db : restart mysql_db service name={{ mysql_service }}, state=restarted ) failed because of

`Unable to start service mysql: Job for mysql.service failed because the control process exited with error code.\nSee \"systemctl status mysql.service\" and \"journalctl -xe\" for details.\n` :thinking:

**Review by bmalynovytch — APPROVED** [review]

**Comment by bmalynovytch** [comment]
+label shipit

**Comment by dagwieers** [comment]
@bmalynovytch You just have to type `shipit`, you cannot influence the label.

**Comment by bmalynovytch** [comment]
shipit

**Review by gundalow — APPROVED** [review]
@UncertaintyP Thank you for this update.
AFAIK the module doesn't check if these are valid for whatever version of MariaDB/MySQL is being used. It's possible that the user may get a slightly unfriendly error message, though I think that's OK

**Comment by gundalow** [comment]
@UncertaintyP Thank you for this feature
@bmalynovytch Thank you for the review
Feature merged into `devel` for release in Ansible 2.8

**Comment by UncertaintyP** [comment]
I closed it because I haven't had time to check all privileges. Why was this opened again?

**Comment by gundalow** [comment]
@UncertaintyP oh, I didn't notice it had recently been closed by you.

**Comment by bmalynovytch** [comment]
@UncertaintyP No we didn't check all of them, but your change shouldn't introduce major regressions (vs what it solves), that's why it got merged.
We plan to improve the checks to handle properly the different versions of MariaDB and MySQL.

**Pull request merged**
