### PR TITLE
New module to setup GSLB service

### PR DESCRIPTION
**Pull request by grastogi23**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

avi.avi_gslbservice

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/grastogi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

New module to setup GSLB Service object. 

```

```

### CODE REVIEW

**Comment by khaltore** [comment]
shipit

**Comment by ericsysmin** [comment]
shipit

**Comment by ericsysmin** [comment]
shipit

**Comment by ericsysmin** [comment]
shipit

**Comment by khaltore** [comment]
shipit

**Comment by gundalow** [comment]
Closing and reopening to retrigger CI as we've extended module validation rules.

**Review by gundalow — APPROVED** [review]

**Pull request merged**
