### PR TITLE
Type manipulation

### PR DESCRIPTION
**Pull request by itdependsnetworks**
##### SUMMARY

It is often convenient to change list of dicts to a dict based on a key, and vice versa. Implement a filter to perform that conversion. 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

list_to_dict
dict_to_list
##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```
    list_data = [{"proto": "eigrp", "state": "enabled"}, {"proto": "ospf", "state": "enabled"}]
    print(list_to_dict(list_data, 'proto'))
    dict_data = {'eigrp': {'state': 'enabled', 'as': '1'}, 'ospf': {'state': 'enabled', 'as': '2'}}
    print(dict_to_list(dict_data, 'proto'))

Results in:

{'eigrp': {'state': 'enabled', 'proto': 'eigrp'}, 'ospf': {'state': 'enabled', 'proto': 'ospf'}}
[{'state': 'enabled', 'as': '1', 'proto': 'eigrp'}, {'state': 'enabled', 'as': '2', 'proto': 'ospf'}]
```

### CODE REVIEW

**Comment by bcoca** [comment]
-1 these seem to be extremely specialized filters, I'm not sure how useful they are to the general user base which can already do transformations with map/zip/select.

**Comment by itdependsnetworks** [comment]
@bcoca I disagree. It takes several complicated steps to do the same in ansible currently, and I am having to explain them to other users. I have these in our internal filters so in the end, makes little difference to my day to day. 

That being said, vote with close or accept, no reason to drag it out.

**Comment by gundalow** [comment]
I believe there are frequent requests for this in the Network community (in particular NTC). 
Could a few examples be added here, I think that would show that this is needed.

**Comment by sivel** [comment]
I find the functionality of these filters to be extremely confusing.  They don't do what I would expect.

As @bcoca mentioned, I feel like these are too specific.

I would expect perhaps something like this:

`dict_to_list`:
```
in = {'foo': 'bar'}
out = [('foo', 'bar')]
```

`list_to_dict`:
```
in= [('foo', 'bar')]
out = {'foo': 'bar'}
```

I can't even think of what to call these filters due to the odd way that they work, but I can guarantee the current names are not sufficient.  I'm not fan.

-1

**Comment by itdependsnetworks** [comment]
@sivel so it makes sense to you that `list == set`?

**Comment by itdependsnetworks** [comment]
Also can we delineate between `naming` issues/`i don't need this so it's not useful issue` vs the network community may find it useful, can you demonstrate? 

To me this highlights the issues raised at ansiblefest how it is unclear what the proper procedures are to get anything into ansible. Often I hear from core members there is a difference between "what we will include" and "what we will program", however that line is muddy and undefined.

**Comment by sivel** [comment]
> @sivel so it makes sense to you that list == set?

I'm confused.  Where was a `set` mentioned?  I don't see it in your code or my comment.

I believe based on the names, that it should effectively work the way python does, when turning a dict into an iterable list via `.items()`, or back into a dict using that list.

```
>>> v = {'foo': 'bar'}
>>> v.items()
[('foo', 'bar')]
>>> dict([('foo', 'bar')])
{'foo': 'bar'}
>>>
```

The current names effectively describe the above behavior.

Your examples, while they eventually do create dicts and lists, follows a pattern that I have never seen named before.  I understand you have a goal in taking a data structure and turning into another, but the generic naming currently, indicates a much more generic feature.  Your implementation is very specific to a functionality that I've never seen anyone use before.

**Comment by sivel** [comment]
> To me this highlights the issues raised at ansiblefest how it is unclear what the proper procedures are to get anything into ansible

I'd like input from @privateip here I think and some of the other core network devs.

Why is the data structured in a way that isn't useful to begin with?  Is it output from Ansible, manipulated to look like that?  Is it direct output from a network device?

Why can't we make whatever is accepting the data, accept it in the format it's already in?

**Comment by itdependsnetworks** [comment]
Apologies, I meant tuple, not set.

**Comment by itdependsnetworks** [comment]
Can you further explain this: `Why can't we make whatever is accepting the data, accept it in the format it's already in?`

I am pretty sure I have a complete mis-understanding of what that implies. My (presumably incorrect) interpretation on this is why doesn't vendor X's API except the dict I send it, in the format I send it? or why doesn't ansible module paremeter except the list I send it?

**Comment by sivel** [comment]
Effectively I am asking, what created it and why?  And what is the reason for whatever is accepting, to not accept it in that format?

Does vendor Xs API create the value in one way, but ansible not accept it in that format?

Why is there a need for this to exist?

Is it to work around a limitation that could otherwise be addressed by updating how the module accepts the data?  Or is ansible mutating it to an otherwise useless format?

I don't understand the real need here, and want to make sure we aren't trying to fix a problem we created, by just adding more code, instead of fixing the real problem.

**Comment by itdependsnetworks** [comment]
> Effectively I am asking, what created it and why? And what is the reason for whatever is accepting, to not accept it in that format?

The need is created by taking useful data from ansible, and transforming it into X number of ways that could be useful for interactions with other systems, in and outside of ansible.

> Does vendor Xs API create the value in one way, but ansible not accept it in that format?

Yes

> Why is there a need for this to being with?


The methods for doing it without the filter are complex, but available in ansible. e.g. combination of selectattr, map, with_items, set_fact, etc... 

> Is it to work around a limitation that could otherwise be addressed by updating how the module accepts the data? Or is ansible mutating it to an otherwise useless format?

Not useless, just does not fit every case. I care that ansible got me structured data, where there was no structured data. Now I want to manipulate that data in a even more useful way.

> I don't understand the real need here, and want to make sure we aren't trying to fix a problem we created, by just adding more code, instead of fixing the real problem.

Will provide concrete examples over the next few days, but here is one recent simple example: 

```
{
    "vrfs": [
        {
            "id": 4,
            "name": "acc",
            "rd": "8:210",
            "tenant": null,
            "zone": "yellow"
        },
        {
            "id": 2,
            "name": "bsz",
            "rd": "8:401",
            "tenant": null,
            "zone": "gray"
        },
        {
            "id": 5,
            "name": "xpt",
            "rd": "8:510",
            "tenant": null,
            "zone": "red"
        }
    ]
}
```

They want to know what the `rd` is for a given `zone`. 

```
{% set vrf_dict = vrfs| list_to_dict('zone') %}
{% set zones = ["red", "gray"] %}

router bgp 8
{% for zone in zones %}
  vrf {{ zone }}
    rd {{ vrf_dict['rd'] }}
{% endfor %}

```
as opposed to something like `selectattr('vrf.zone', 'equals', zone)` then with items over, etc, etc...

**Comment by sivel** [comment]
I do think at this point someone from the network team does need to weigh in here.  Assuming that this is something that would be accepted, we still need to address naming.

**Comment by gundalow** [comment]
I think having a few examples of the problem we are trying to solve would be useful, thanks Ken for the first of those. It will help us all understand the problem we are trying to solve and allow us to put together some ideas for how to progress this. 

Once the examples are added please add this to the Network and/or Core meeting agendas. 

Once everyone is happy we will need to add docs and unit tests.

**Comment by itdependsnetworks** [comment]
Interfaces pretty much have to be lists of some sort. Since the configuration is in order of list, and there is no real easy and/or predictable way to sort them. Hopefully this pseudo code can help further illustrate the point. 

```
vars:

interfaces:
  - name: GigabitEthernet1/0/1
    mode: pc_member
    pc_master: Port-Channel100
  - name: GigabitEthernet1/0/2
    mode: access
    vlan: 100
  - name: Port-Channel100
    mode: access
    vlan: 100


tasks:

 - name: CHANGE LIST OF DICT TO DICT
   set_fact:
     interfaces_as_dict: {{ interfaces | list_of_dict('name') }}

Jinja
{% for interface in interfaces %}
interface {( interface.name )}
{% if interface.mode == 'pc_member' %}
{% set interface = interfaces_as_dict[interface.name] %}
{% endif %}
  vlan {{ interface.vlan }}
{% endfor %}

without:
{% for interface in interfaces %}
interface {( interface.name )}
{% if interface.mode == 'pc_member' %}
{% for inner_int in interfaces %}
{% if inner_int.name == interface.pc_master %}
{% interface = inner_int %}
{% endif %}
{% endfor %}
{% endif %}
  vlan {{ interface.vlan }}
{% endfor %}
```

Same data additional use case
```
With:
 - name: GET LIST OF INTERFACES IN MODE PC_MEMBER
   set_fact:
     interfaces_in_pc_member: "{{ interfaces | selectattr('pc_member', 'defined') | map(attribute('pc_member') | list }}"

 - name: ASSERT PC MEMBER DATA IS GOOD
   assert:
     that:
       - "interfaces_as_dict[item]['pc_master'] is defined"
       - "interfaces_as_dict[interfaces_as_dict[item]['pc_master']] is defined"
   with_items: "{{ interfaces_in_pc_member }}"

Without:
json_query??
```

Additionally I will quote @privateip "you can still use playbooks to translate from one data model to another prior," so the idea of data manipulation seems to be common practice within the core members, and what I have seen in the community and being on client site.

**Comment by bcoca** [comment]
you can easily add an 'order: x' field and use the `dicsort` filter, not that i see an issue in keeping it as a list of dictionaries .. which is already 'sorted'

**Comment by sivel** [comment]
An update version for `without` that doesn't jump through as many hoops as you did:

```
{% for interface in interfaces %}
interface {{ interface.name }}
{% if interface.mode == 'pc_member' %}
  vlan {{ (interfaces|selectattr('name', 'equalto', interface.pc_master)|first).vlan }}
{% else %}
  vlan {{ interface.vlan }}
{% endif %}
{% endfor %}
```

results in:

```
interface GigabitEthernet1/0/1
  vlan 100
interface GigabitEthernet1/0/2
  vlan 100
interface Port-Channel100
  vlan 100
```

**Comment by itdependsnetworks** [comment]
@bcoca no you can't since there is not logical ordering to interfaces in network devices.

E.g. 

Vl301
G1/0/1
G/1/0/2
T1/0/0
G2/0/1
Po102

Attempting to reverse that is not manageable 

Additionally I would argue that ansible should allow you to to work with the data model of your choosing, while making it as easy as possible.

@sivel so just to clarify you now agree that data models are unique, but I have not sufficiently shown a complex enough use case?

**Comment by sivel** [comment]
> @sivel so just to clarify you now agree that data models are unique, but I have not sufficiently shown a complex enough use case?

I looked at your example, and realized it could be solved with less hassle than you went through.

**Comment by itdependsnetworks** [comment]
In your example you are only grabbing the first, if there was bad data, the proposed filter would catch (one small side benefit, though admit-tingly nothing huge) the issue if there was multiple. 

Where does that leave us? Are more examples needed, what is the level of complexity needed if so, can I ever convince that this is needed, etc..

**Comment by privateip** [comment]
@sivel @itdependsnetworks chiming in a bit late here so apologizes if i re-hash something that has been discussed as i wrap my head around this.  Here are some initial thoughts / questions:

I agree with @sivel the filters seem to be doing some unnatural things to the data.  

I'm not sure what you are trying to solve with these filters, which isn't to say they are or are not needed, just trying to understand the problem you want to solve.  If I look at the example data, I see much easier ways to solve using that data structure to configure the device as opposed to using in a template, but perhaps there are other use cases not explained in the example.

@itdependsnetworks Is the goal to build a config or to configure a device?  Also, how are you generating the `vars` since that isn't coming natively from the device itself.  Couldn't you just generate the `vars` as a dict to begin with?   Just looking for some clarification here

**Comment by itdependsnetworks** [comment]
I promised some more examples to @gundalow so I haven't really pushed this.

> Is it to work around a limitation that could otherwise be addressed by updating how the module accepts the data? Or is ansible mutating it to an otherwise useless format?

> If I look at the example data, I see much easier ways to solve using that data structure to configure the device as opposed to using in a template,

I see these as being "Use our data model"

But there is no defined data model from ansible, and even if there was, why would it make sense to use that same data model in every other integration? (e.g. config templates, infoblox, netbox, etc...)

To me the point you are making is the same as saying:
> Why have a list and a dict in python, there should only be one? After all if it is just as easy to get data and iterate data as the other, why have two different data types?


@privateip I took to heart what you said at ansiblefest, there is a difference between "Red Hat will spend resources developing and Red Hat will include" 

The implication being that the barrier to entry was much lower entry if I was writing the code. But here 24 lines of code, with tests, and multiple people agreeing it serves a need (https://meetbot.fedoraproject.org/ansible-network/2017-10-11/network_working_group.2017-10-11-16.01.log.html) is taking more time to discuss than to write the code.

**Comment by itdependsnetworks** [comment]
This came up on slack today, and it is the "tool" referenced here. I think it succinctly depicts what I have been trying to say.

> I think his tool would negate the debate around which format is best to be returned.  The user could simply filter in their preferred format with out the endless stream of little changes that make us pull our hair out.

> It's a filter that makes `map` and `selectattr` hacks much simpler and easier to read IMO. - @dgjustice

**Comment by jedelman8** [comment]
Just seeing this now too, so why not chime in :) 

I do agree, the naming of this filter is deceiving, i.e. `list_to_dict` (I can take ownership in that), but in reality it's a taking a list of dictionaries that converting it to be nested dictionaries with keys equal to the values of the key passed into the filter.   Will a better name help get this merged?

Ansible has always strived to be "simple" - that's what this filter is striving to do.  Why chain 2 or 3 filters together repeatedly for the SAME operation (or require a template for data manipulation)?  
Isn't it easier to create a better abstraction?   :thinking: 

I also don't see the relevance for making this a "network" feature in Ansible.  It has implications to any technology domain. 

That said, if we're making this a network feature, we can look at any list of dictionaries for VLANs, interfaces, VRFs, etc.  Since it's a list, it's obvious we cannot programmatically ask in a *simple* way, i.e. what's the name for VLAN 10, or what attributes are on a given interface, or what neighbors are on interface Eth2...  with this filter, all of these become super easy.

And another example, Arista eAPI returns VLANs as a nested dictionary and Cisco NX-API returns a list of dictionaries.  Again, this filter easiliy converts the NX-API list of dicts to a nested dictionary rooted at whatever key we pass in, e.g. `vlan_id` in this case (or the real key Cisco returns). 

My 2c.

**Comment by bcoca** [comment]
so 'related' change, #32686 allows 'combine' to aggregate a list of dicts (even recursively) which is mostly what the first filter proposed here does.

**Comment by jedelman8** [comment]
Not really. That is what’s done as one of the values of a key value pair though.  So that’s a small subset of what’s done here but not the primary objective. 

 I actually thought this was merged. The related PR you’re referencing was opened 14 days ago and already merged. Is there any luck in getting this merged?  We can probably all save time if a decision is made one way or another.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
rebuild_merge

**Comment by sivel** [comment]
I still feel these need fundamentally renamed.

**Comment by abadger** [comment]
This was brought up at today's meeting with a large contingent weighing in that these filters, at least as named and partially, as implemented, aren't a good idea as they are implementing conversion between non-standard data values.  After the meeting we kicked it around enough that we figured out how to make something that would satisfy the use case in https://github.com/ansible/ansible/pull/28446#issuecomment-336123974 in a generic fashion.  Here's the PR for that: https://github.com/ansible/ansible/pull/33836

If there's other use cases, not satisfied by that PR (I've gotten rid of dict to list conversion, for instance, since that's not generic and not needed for the use case.  if there's a use case around that we can look at implementing something there.  However, I'm thinking that will still be a (simple) jinja2 pipeline rather than a single function) then please raise them there.

**Comment by abadger** [comment]
Oops: this is the PR: https://github.com/ansible/ansible/pull/33836

**Pull request merged**
