### PR TITLE
Added more explanation to keypair.

### PR DESCRIPTION
**Pull request by AHassanSOS**
+label: docsite_pr

##### SUMMARY
Added more explanation to key_pair.

### CODE REVIEW

**Comment by AHassanSOS** [comment]
@mattclay Could you help me?

**Comment by mattclay** [comment]
@AHassanSOS Your whitespace change has fixed the CI failure.

**Comment by AHassanSOS** [comment]
Awesome! Do I need to do anything else in order to merge it?

**Comment by AHassanSOS** [comment]
Ping! Do I need to do anything else?

**Comment by AHassanSOS** [comment]
Ping!

**Comment by AHassanSOS** [comment]
*yawn*

**Comment by jillr** [comment]
rebuild_merge

**Pull request merged**
