### PR TITLE
iam_managed_policy: add check & diff mode support, cover with unit tests

### PR DESCRIPTION
**Pull request by zyv**
##### SUMMARY
This PR adds check & diff mode support to `iam_managed_policy`, which comes in very handy, because you can then see what changes exactly are going to be applied, almost like in Terraform ;-)

On top of that, we have covered the module with unit test to make sure future changes won't break existing logic.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
iam_managed_policy

### CODE REVIEW

**Comment by zyv** [comment]
ready_for_review

/cc @marns93 @s-hertel @jillr @goneri @willthames @ryansb

**Review by marns93 — APPROVED** [review]
LGTM

**Comment by jillr** [comment]
Please add [integration tests](https://github.com/ansible/community/blob/master/group-aws/integration.mds).

**Comment by schrodervictor** [comment]
I'm currently in planning phase of the implementation to address the issue #31999 (adding support to attach/remove named managed policies to IAM users), which will most likely touch the `iam_managed_policy` module and maybe others in the `iam_*` family.

@zyv do you have plans to write the integration tests for this pull request? Do you need help?

It would be very nice to see this pull request merged before we invest a lot of work on that feature. Also, the unit test suite produced here would end up being duplicated there, if this one doesn't get merged.

**Comment by zyv** [comment]
@schrodervictor unfortunately, we don't have the resources to push this PR any further by adding the integration tests, as we are migrating to Pulumi for all our AWS needs.

It would be very sad to see this work just thrown away, so if you like it, I'd certainly very much appreciate your help. Are you a committer, so that you can just add your commits to this PR, or I should get you write access to our fork?

P.S. We have several other PRs waiting on feedback, I think integration tests might be an issue there as well. I could have a look if you have any interest in helping us to them through...

**Comment by schrodervictor** [comment]
Hi @zyv, it would be great if you can provide me write access to your fork, just for practical reasons. Of course I could simply cherry-pick your commits in my own fork, but that would imply to close this PR and open a new one. I think it's better to continue from this one in order to keep the reviews and labels already assigned by the bot.

About the other PRs you may have, I wouldn't mind to take a look, but I also have limited resources on my end. Let's see what we could do, I'd be glad to help if possible.

**Comment by zyv** [comment]
Hey @catcombo, could you please be so kind as to add @schrodervictor as a collaborator to your Ansible fork? I realised I don't have required permissions to do so :( Thanks man!

**Comment by zyv** [comment]
P.S. @schrodervictor I'm not sure whether @catcombo is on vacation or not, but I do have write access, so I'd be happy to `git am` stuff for you if you give me a `git format-patch` stack.

**Comment by schrodervictor** [comment]
@zyv and @catcombo, I don't need the write permissions immediately, as I haven't even started to write the required integration tests. For now, I can simply add your fork as an upstream and work on top of your branch, preparing the new commits. Once the permissions are given, I can just go ahead and push them.

Anyways, no rush, I also have to find time on my side for this.

**Pull request closed without merging**
