### PR TITLE
Start of aws best practices docs

### PR DESCRIPTION
**Pull request by lwade**
Disclaimer: I think the formatting is ok here (famous last words) 

This is a PR for a docs page which discusses some best practices and how-to for using Ansible with AWS. This should be a living document, we should encourage folks to add to this and share how they are using Ansible with AWS / a-n-other cloud (since majority of it is generic). I still need to add details on usage / use case for each module. I propose adding this information later once we find a place for this base document.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Going to take a look at this hopefully Monday, great to see this -- lots of interest from folks in having this kind of writeup, thanks!

**Comment by lwade** [comment]
Thanks @mpdehaan.  Long term I think much of this (and more) can be generic across "The Cloud", since many of the same concepts apply.

**Comment by mpdehaan** [comment]
Different modules for different clouds, I can see it being split up, but yeah, some of these concepts... there are probably chapters and subchapters at some point in the distant future.   Looking at this now...

**Comment by mpdehaan** [comment]
Ok, tweaked a few things -- using 1.2 syntax, added some text and so forth.

If you want to add things about the S3 module and so on that would be awesome.  I am also thinking we might want to explain the inventory module a bit more on that page, I don't know.

Thanks!

**Pull request merged**
