### PR TITLE
add link in README to build-from-source instructions

### PR DESCRIPTION
**Pull request by mdavis-xyz**
##### SUMMARY

Fix issue #55900 

Previously there was nothing in the README or the [Contributing to Ansible](https://docs.ansible.com/ansible/latest/community/development_process.html#) docs which explained how to run ansible from source. The presence of a Makefile is a bit of a red herring.

This patch just adds a link in the README to the instructions which say `source ./hacking/env-setup`.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

README

### CODE REVIEW

**Comment by jborean93** [comment]
I'll leave this up to the docs team but we already link to this page under the [Use Ansible](https://github.com/ansible/ansible/blob/devel/README.rst#use-ansible) section so not sure what exactly this adds that's already there.

**Comment by mlda065** [comment]
> we already link to this page under the Use Ansible section

Ah, I see now.

I honestly did not notice that before because that section title didn't sound relevant, since I already know how to use Ansible. 

I had a bug I wanted to fix. So I was looking through the README for any sections about development, building etc. "Use Ansible" is where I'd expect to find an explanation of hosts, roles, modules, `failed_when` etc.

Get Involved and Branch Info is where I expected to find information on how to compile from source.

I think the other part of the issue (which this PR doesn't fix) is that the "contributing to Ansible", "Ansible Community Guide" and "The Ansible Development Process" pages do not link to the build-from-source instructions. I'm not really familiar with rst, and it seems those pages have changed significantly between the devel branch and what's online, so I didn't modify those pages.

**Comment by bcoca** [comment]
@mlda065 also note that Python is 'interpreted' so no real need to 'build from source'

**Comment by acozine** [comment]
Thanks @mlda065 for letting us know about your experience and for opening a PR to improve things. Feedback like this (about expectations, etc.) is incredibly helpful in assessing how the documentation works together.  I might take a different approach to addressing your concerns in the README and push a new commit to this PR, though.

**Pull request merged**
