### PR TITLE
Restore local_nvra function

### PR DESCRIPTION
**Pull request by elventear**
Function was deleted on 5a7d2717596fe1f3feb4f024ff33bb2c09fb3208 but still referenced on the module, breaking it. Restoring the function fixes the module.

### CODE REVIEW

**Comment by mpdehaan** [comment]
thanks for this...

there are pending pull requests to the yum module that will likely be used instead of this, so this is unlikely to be needed.   I want to test first before applying though.

**Comment by mpdehaan** [comment]
see https://github.com/ansible/ansible/pull/864

**Comment by elventear** [comment]
local_nvra is still referenced within those requests, but not defined within the module itself. My impression is that the error is still going to happen. Either the function needs to be re-included or those patches need to address the requirement of that function in a different way.

**Comment by mpdehaan** [comment]
ok, thanks, will note in the other ticket

**Comment by elventear** [comment]
Tainted pull request with other commits. And also seems to have been taken care of.

**Pull request closed without merging**
