### PR TITLE
Add dict support to osx_defaults

### LINKED ISSUE #24028: [osx_defaults] Add dict/dict-add support
_From @claco on February 21, 2016 16:31_

##### Issue Type:
- Feature Idea
##### Plugin Name:

osx_defaults
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /Users/claco/Projects/claco.network/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
ask_sudo_pass = True
fact_caching = jsonfile
fact_caching_connection = ./facts
fact_caching_timeout = 86400
hash_behaviour: merge
inventory = ./inventory
roles_path = ./roles
vault_password_file = ~/.ansible_vault_password
```
##### Environment:

OSX El Cap 10.11
##### Summary:

The osx_defaults module doesn't yet support dict and dict-add methods for changing/adding defaults that are contained within values that are dicts.
##### Steps To Reproduce:

As an example, I'm configuring defaults for SizeUp on a new install. Many of the settings are container in dicts for each group of key commands. This command, for example, configures the combo code for the 'move window to lower left' command:

```
defaults write com.irradiatedsoftware.SizeUp. "Lower Left" -dict-add ComboCode 125
```

Because there is no dict/dict-add support, I have to fall back to using bash/shell commands rather than using the module.
##### Expected Results:

As an example, I would have expected to see something like this:

```
- name: Add Default Lower Left
  osx_defaults: domain=com.irradiatedsoftware.SizeUp key="Lower Left", value: {ComboCode: 125} state=present
```
##### Actual Results:

What actually happened?

```
failed: [mqr13tg8wl] => (item={u'type': u'dict', u'key': u'Lower Left', u'value': u'ComboFlags 126'}) => {"failed": tr
ue, "item": {"key": "Lower Left", "type": "dict", "value": "ComboFlags 126"}, "msg": "value of type must be one of: ar
ray,bool,boolean,date,float,int,integer,string, got: dict"}
```

_Copied from original issue: ansible/ansible-modules-extras#1705_

### PR DESCRIPTION
**Pull request by claco**
##### SUMMARY

Add support to osx_defaults for the `dict` type with support for
additions using `dict-add`.

Fixes: #24028

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

osx_defaults

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by calfonso** [comment]
@claco are you interested in being the maintainer of this module?

**Comment by ChristinWhite** [comment]
Any chance this will be merged soon without a maintainer? It would definitely improve me configuration playbook not having to resort to shell commands for these defaults.

**Comment by calfonso** [comment]
@christopherdwhite we are currently in a code freeze period for new features until 2.4 ships, which will be around next week or so. Once that is done, we can pick this up.

**Comment by ChristinWhite** [comment]
Thanks @calfonso! I hadn't realized that

**Comment by booch** [comment]
This is great, but I believe #24808 is a better overall situation.

**Comment by gundalow** [comment]
Hi,
This PR seems to have gotten stuck, so we are going to close it. We like to include community contributions, so this is a difficult call for us. Here's why we're closing this one:
* It's a feature
* It was created from an old version of the code
* We want to clear out the backlog so it's easier to find bug fixes
* There haven't been any comments or other activity in a long time

If you're the PR author, and you want to start the conversation back up, please:
* reopen the PR and
* rebase the branch

If you're a community member, and you want to see this change merged, please:
* Create a new PR and 
* Reference this author in the git commit & PR and
* Reference this PR in the new PR

How to rebase a branch: https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html
How to communicate with the Ansible community: https://docs.ansible.com/ansible/devel/community/communication.html
How to contribute to Ansible: https://docs.ansible.com/ansible/devel/community/index.html

**Comment by gundalow** [comment]
See https://github.com/ansible/ansible/pull/24808 for solution

**Pull request closed without merging**
