### PR TITLE
Setup filter argument

### PR DESCRIPTION
**Pull request by leucos**
Adds filtering option in the setup module ('filter') that takes shell style glob arguments.

Note : I couldn't test facter & ohai, so if someone has access to facter/ohai enabled hosts, please test !

### CODE REVIEW

**Comment by leucos** [comment]
I see you prefer not reassigning keys (https://github.com/ansible/ansible/blob/devel/library/setup#L1117). Want me to rework this PR ?

**Comment by mpdehaan** [comment]
Thanks!

Yes please, it also looks like the variable "filtr" is not used anywhere,
so that could be used below versus the extra lookup.

**Comment by leucos** [comment]
Yes that was the point when I made it :p

**Comment by mpdehaan** [comment]
this replace check should just happen at the very bottom of the module in just once place before we return the keys.

So make a function that does the filtering, rather than doing it in 3 places.

**Comment by leucos** [comment]
This is what I intended to do at first. But I didn't want to add another `for` loop and copy keys again. It just seemed inefficient. I suppose that if other fact gathering methods (besides ansible, ohai & facter) are planned, it could be better to put it in one place so the filtering problem is solved once for all.

However, if the module sticks to those three methods, filtering at the initial for loops is more efficient.

(EDITED for typos)

**Comment by mpdehaan** [comment]
Seriously?  We're talking about microseconds.

I'd rather have cleaner code.

Filter it in just one place.

**Comment by mpdehaan** [comment]
Looks good, thanks!

Seeing it is easy efficiency (I know, I'm being ironic) this probably should also only run the filtering code if the filter is not "*".

**Comment by leucos** [comment]
The solution would probably be more efficient only if '_' is used by itself, and suboptimal in every other case. Not sure you really want that unless you have a group of '_' lovers in ansible user base.

**Comment by mpdehaan** [comment]
Everyone is going to be using '*' every single time they run a playbook.

**Comment by leucos** [comment]
Oh well, I just need holidays :D

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
