### PR TITLE
Resubmission of dataproc module PR post repo merge

### PR DESCRIPTION
**Pull request by jbaublitz**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

gcdataproc
##### ANSIBLE VERSION

```
ansible-playbook 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This is a resubmission of a PR in ansible-modules-extras: ansible/ansible-modules-extras#3293

This module uses `google-api-python-client` to make requests as opposed to `libcloud` as `libcloud` did not support the Dataproc API at the time of writing this module. The module requires a slightly different profile of information given the switch from `libcloud` to `google-api-python-client` and the nature of the Dataproc API compared to Compute for example.

I have removed the explicit parameters (but can add them back in if this seems more like a bug than a simplification) corresponding to  `GCE_EMAIL`, `GCE_PROJECT`, and `GCE_CREDENTIALS_FILE_PATH` environment variables that are supported in the other modules.

Another note is that the `google-api-python-client` calls are asynchronous to Dataproc. I have a very ugly poll-sleep interface for synchronous calls and would be open to hearing suggestions as I am unsure whether other Google APIs support event based calls or if `libcloud` simply emulates synchronous calls in a way similar to what I do (from what I saw of the code, it seems to support the latter).

The last noteworthy design decision was to pass unvalidated data into the Google API. This is a decision I saw in parameters like `metadata` in the `gce` module and some of these parameters are so highly variable that this seems like a better task for the user in the playbooks to pick and choose based on the documentation which parts of the object to pass in as not all are required for the API. I also think that the number of parameters would be a bit excessive without this structure and not easily represented within the ansible framework.

TODOS:
1. I need to work more on documentation and welcome suggestions. One issue that I just saw is that the Google docs and the return values from the `google-api-python-client` call do not seem to match. I need to look into this and fix the documentation there.
2. I only support the creation and destruction of clusters currently. Is anyone interested in the other components of the Dataproc API for this module? One warning is that I am unsure of the ability we will have to make this idempotent.
3. Cluster destruction does not currently support synchronous operations.

```
***********************************
PARSED OUTPUT
{
    "changed": true, 
    "clusterName": "test", 
    "clusterUuid": "7cf1ff27-4c9a-465e-8106-f646739eced3", 
    "config": {
        "configBucket": "dataproc-2433fc45-780c-44a7-a05b-2aa6fa077e39-us", 
        "gceClusterConfig": {
            "networkUri": "https://www.googleapis.com/compute/v1/projects/[PROJECT]/global/networks/default", 
            "serviceAccountScopes": [
                "https://www.googleapis.com/auth/bigquery", 
                "https://www.googleapis.com/auth/bigtable.admin.table", 
                "https://www.googleapis.com/auth/bigtable.data", 
                "https://www.googleapis.com/auth/cloud.useraccounts.readonly", 
                "https://www.googleapis.com/auth/devstorage.full_control", 
                "https://www.googleapis.com/auth/devstorage.read_write", 
                "https://www.googleapis.com/auth/logging.write"
            ], 
            "zoneUri": "https://www.googleapis.com/compute/v1/projects/[PROJECT]/zones/us-central1-a"
        }, 
        "masterConfig": {
            "diskConfig": {
                "bootDiskSizeGb": 500
            }, 
            "imageUri": "https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-1-1-20161017-161942", 
            "instanceNames": [
                "test-m"
            ], 
            "machineTypeUri": "https://www.googleapis.com/compute/v1/projects/[PROJECT]/zones/us-central1-a/machineTypes/n1-standard-4", 
            "numInstances": 1
        }, 
        "softwareConfig": {
            "imageVersion": "1.1.8", 
            "properties": {
                "distcp:mapreduce.map.java.opts": "-Xmx2457m", 
                "distcp:mapreduce.map.memory.mb": "3072", 
                "distcp:mapreduce.reduce.java.opts": "-Xmx4915m", 
                "distcp:mapreduce.reduce.memory.mb": "6144", 
                "mapred:mapreduce.map.cpu.vcores": "1", 
                "mapred:mapreduce.map.java.opts": "-Xmx2457m", 
                "mapred:mapreduce.map.memory.mb": "3072", 
                "mapred:mapreduce.reduce.cpu.vcores": "2", 
                "mapred:mapreduce.reduce.java.opts": "-Xmx4915m", 
                "mapred:mapreduce.reduce.memory.mb": "6144", 
                "mapred:yarn.app.mapreduce.am.command-opts": "-Xmx4915m", 
                "mapred:yarn.app.mapreduce.am.resource.cpu-vcores": "2", 
                "mapred:yarn.app.mapreduce.am.resource.mb": "6144", 
                "spark:spark.driver.maxResultSize": "1920m", 
                "spark:spark.driver.memory": "3840m", 
                "spark:spark.executor.cores": "2", 
                "spark:spark.executor.memory": "5586m", 
                "spark:spark.yarn.am.memory": "5586m", 
                "spark:spark.yarn.am.memoryOverhead": "558", 
                "spark:spark.yarn.executor.memoryOverhead": "558", 
                "yarn:yarn.nodemanager.resource.memory-mb": "12288", 
                "yarn:yarn.scheduler.maximum-allocation-mb": "12288", 
                "yarn:yarn.scheduler.minimum-allocation-mb": "1024"
            }
        }, 
        "workerConfig": {
            "diskConfig": {
                "bootDiskSizeGb": 500
            }, 
            "imageUri": "https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-1-1-20161017-161942", 
            "instanceNames": [
                "test-w-0", 
                "test-w-1"
            ], 
            "machineTypeUri": "https://www.googleapis.com/compute/v1/projects/[PROJECT]/zones/us-central1-a/machineTypes/n1-standard-4", 
            "numInstances": 2
        }
    }, 
    "invocation": {
        "module_args": {
            "bucket": null, 
            "image_version": null, 
            "init_actions": null, 
            "master_config": null, 
            "metadata": null, 
            "name": "test", 
            "network": null, 
            "poll_interval": 1, 
            "region": "us-central1", 
            "second_worker_config": null, 
            "service_account_scopes": null, 
            "state": "present", 
            "subnetwork": null, 
            "sync": true, 
            "worker_config": null, 
            "zone": "us-central1-a"
        }
    }, 
    "metrics": {}, 
    "projectId": [PROJECT], 
    "status": {
        "state": "RUNNING", 
        "stateStartTime": "2016-10-25T19:06:32.545Z"
    }, 
    "statusHistory": [
        {
            "state": "CREATING", 
            "stateStartTime": "2016-10-25T19:04:36.149Z"
        }
    ]
}
```

/cc @ryansb @supertom

### CODE REVIEW

**Comment by peay** [comment]
Is this still being worked on?

**Comment by supertom** [comment]
@jbaublitz I sent you an email regarding this along with some [proposed changes](https://github.com/supertom/ansible/commit/13dd959a79933cbb5a0972dc3561bec9e39b35fc).  Whatcha think?

**Comment by jbaublitz** [comment]
@supertom Hey there! I missed your email in my inbox until the Github notification so I'll take a look at this soon.

**Comment by jbaublitz** [comment]
@supertom Finally getting around to looking at this. Given that the changes I see are almost all things related to the improved authentication that you worked on, I have no problem with shipping it. Should I pull your changes into my repo and then get it approved by @ryansb?

Also, @ryansb, I am working on too many projects at the moment to promptly respond to PRs so what is the process for assigning this module to another maintainer?

Thanks and sorry for the delay.

**Comment by supertom** [comment]
@jbaublitz Sure, that works for me!  @erjohnso would be able to help with finding the right maintainer.

**Comment by schwichtgit** [comment]
@jbaublitz thanks for your involvement despite your new job role!  May I recommend @rohitkum2506 to take over the PRs that you would like to pass on? Maybe you can introduce @rohitkum2506 to  @ryansb,  @supertom and  @erjohnso ?

**Comment by jbaublitz** [comment]
@schwichtgit Thank you for your interest but after careful consideration I think it would be good to remain the module maintainer for now.

@ryansb @erjohnso @supertom I am going to looking into the reason the tests failed. It appears that there are duplicate YAML keys in the docs so I will clean that (and the accidental merge - sorry about that) up and push again. Once that's all set, I think this should be good to go!

**Comment by erjohnso** [comment]
Sorry for the delay @jbaublitz - but this LGTM.  Thank you for keeping at it!

@ryansb - I think this is in good shape assuming we're fine with the one-off / transient failure.

**Comment by erjohnso** [comment]
@ryansb, iirc from our last chat, you were going to poke this one again because of the `stale_ci` label? I think it's in good shape if you agree and it would be great to get this in before module freeze.

**Comment by erjohnso** [comment]
Looks like Ryan poked CI again to get another check. Seems like some of this should be addressed @jbaublitz.

* The `notes` issue seems easy (just a doc fix).
* Need to add some boilerplate like [this for example](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gce_labels.py#L9-L11).
* Check the imports with various python versions.
* Make sure RETURN is consistent with docs/code.

I can understand if you don't have time / interest in making these changes. If that's the case, let me know and I can take a crack at fixing up these last few things.

**Comment by jbaublitz** [comment]
@erjohnso So sorry for my absence. I fixed the first two and have rebased the branch so that there are no conflicts. The last item you mentioned will unfortunately have to be verified by you because I no longer have access to dataproc for work so it appears the code passes back information directly from the API calls. Would you be willing to do that? The third item I will try to fix in my next commit tonight.

Thank you very much for your patience and let's try to get this submitted by the end of the week. This has been hanging over my head for too long.

**Comment by jbaublitz** [comment]
Hrm @erjohnso I'm looking back on the import errors and it appears the pipeline isn't installing google-api-python-client to even test if the imports work. Maybe @ryansb would know what to do to help make this pass in the pipeline. The other thing I was thinking of doing is doing a guard similar to in other GCP modules like so:

```
try:
    import googleapiclient
    HAS_GOOGLE_API_CLIENT = True
except ImportError:
    HAS_GOOGLE_API_CLIENT = False
```

and then printing out a friendly error message if the library isn't installed. How does that sound?

**Comment by jbaublitz** [comment]
I'm going to close this one for now - please `@` me here if you would like me to resume work on this.

**Pull request closed without merging**
