### PR TITLE
Allow .yaml if .yml tasks/handlers/vars are not found in a role

### PR DESCRIPTION
**Pull request by fabulops**
We discussed this briefly on irc yesterday. This patch allows:

<rolename>/tasks/main.yaml
<rolename>/handlers/main.yaml
<rolename>/vars/main.yaml

in roles. As discussed, .yml files are preferred.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks like this needs to be rebased given recent code changes...

Can you take care of this?

Thanks!

**Comment by fabulops** [comment]
Should be easy to merge my changes to what's in HEAD. Hopefully today but more likely tomorrow morning.

**Comment by fabulops** [comment]
Hmmm, looks like my rebase pulled in some of your commits too :/

Not sure if you can cherry-pick my bits or if you want me to abandon this PR and submit a fresh one with the changes. Please let me know.

**Comment by mpdehaan** [comment]
Looks like you did a merge instead of a rebase.

You can start a new branch and cherry-pick from your old one.

I would resubmit though.

Thanks!

**Pull request closed without merging**
