### PR TITLE
Added helm release updates. Fixes #32545.

### LINKED ISSUE #32545: The helm module claims to upgrade packages, but it doesn't
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
helm

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The module synopsis says "Install, upgrade, delete and list packages with the Helm package manager".
The module cannot be used to upgrade a package.

##### STEPS TO REPRODUCE
Use the module with chart.version=1, then with chart.version=2.

##### EXPECTED RESULTS
Expected the package to be upgraded when a newer chart.version was passed.

##### ACTUAL RESULTS
Nothing. Not even a warning. The task quietly passes, even though a different version was provided, than the one installed.

##### ANNOYANCE LEVEL
High.
Wasted a day debugging, reporting and working around #32513, only to find out the module does not implement the functionality it claims to provide, meaning I have to start from scratch, using helm cli.

### PR DESCRIPTION
**Pull request by wknapik**
##### SUMMARY
Adds support for upgrading installed charts. Fixes #32545.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
helm

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/d/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### ADDITIONAL INFORMATION
The helm module uses pyhelm (by the same author).

For this PR to work correctly, my 2-line PR against pyhelm needs to be merged first (https://github.com/flaper87/pyhelm/pull/4).

This PR was written quickly and without in-depth understanding of tiller/pyhelm, but it works for me.
The author of the helm module/pyhelm should be able to easily evaluate this small change.

### CODE REVIEW

**Comment by flaper87** [comment]
@wknapik looks good to me, would you mind squashing both commits into one? No need to have a separate commit for the pep8 fix.

**Comment by wknapik** [comment]
Done.

**Comment by wknapik** [comment]
@flaper87 done.

**Comment by flaper87** [comment]
shipit

**Review by ryansb — APPROVED** [review]

**Pull request merged**
