### PR TITLE
add a logger for consul_io_py to help debugging

### PR DESCRIPTION
**Pull request by deimosfr**
Hi,

To help on debugging Consul with Ansible, I added a logger. Hope this will help.

Thanks

### CODE REVIEW

**Comment by msabramo** [comment]
No longer merges cleanly.

**Comment by bcoca** [comment]
im thinking to expan this and just make all lookups debuggable

**Comment by amenonsen** [comment]
I agree that @bcoca's approach of generalising this is preferable to applying such changes piecemeal, and this should be closed. (Also, this particular diff is absolutely enormous. I found it very hard to figure out what the actual changes are and which are just formatting/indentation changes and, in fact, gave up trying.)

**Comment by deimosfr** [comment]
It looks like a big update because of the indentation which has changed. I will update it soon to get it more comprehensive.

**Comment by amenonsen** [comment]
@deimosfr Thanks for your contribution. If you get a chance to rebase and address @bcoca's suggestions as you had planned, you are welcome to resubmit a new PR. I'll close this one as it no longer applies, and hasn't been updated in a while.

**Pull request closed without merging**
