### PR TITLE
Fix the get property (#55745)

### PR DESCRIPTION
**Pull request by yuwzho**
(cherry picked from commit c7bf3e035b3cc3304b0dcafc3437ba8ea0db30b4)

### CODE REVIEW

**Comment by Fred-sun** [comment]
@yungezz @zikalino

**Comment by yuwzho** [comment]
@Fred-sun Please ignore the backport issues

**Comment by Fred-sun** [comment]
@yuwzho  Ok! Thanks!

**Comment by abadger** [comment]
Merged for the 2.8.1 release.

**Pull request merged**
