### PR TITLE
Add support for templating in vars_prompt

### PR DESCRIPTION
**Pull request by nathancahill**

### CODE REVIEW

**Comment by sudarkoff** [comment]
:+1: Thanks, @nathancahill, I was just about to do the same.

I'd add a few tests for this.

**Comment by jeromedoyle** [comment]
Any update on this or alternate method to accomplish the same effect?

**Comment by bcoca** [comment]
this probably needs to be redone as the whole system has drastically changed.

**Comment by amenonsen** [comment]
As @bcoca says, the code in devel is very different now, and achieving the object of this PR (which is slightly unclear; some examples/tests would be welcome) would need a rewrite. I don't think there's any point keeping this PR open.

**Comment by bcoca** [comment]
closing this as current 2.0 should fix  #7959 (as mentioned in that ticket).

**Pull request closed without merging**
