### PR TITLE
ec2_asg: Added a more verbose response to the module.

### PR DESCRIPTION
**Pull request by ferrants**
Now includes its settable attributes and a list of its instances

Response like:

```
TASK: [ec2_asg ] ************************************************************** 
ok: [localhost] => {"availability_zones": ["us-east-1a"], "changed": false, "desired_capacity": 1, "instances": ["i-e9038fb9"], "launch_config_name": "dx_auto-deploy_test_lc", "max_size": 2, "min_size": 1, "vpc_zone_identifier": "subnet-c9c906a8"}
```

### CODE REVIEW

**Comment by jimi-c** [comment]
Could you change the `attrs` variable name to just `attributes`? We try and keep variable names a bit more readable, especially when they're used in multiple locations as you're using them.

**Comment by ferrants** [comment]
@jimi-c - For sure. I have updated `attrs` to `attributes`

**Comment by ferrants** [comment]
@jimi-c - is there anything else you see missing in this pull request?

**Comment by ferrants** [comment]
Closing to refactor and clean up

**Pull request closed without merging**
