### PR TITLE
docker_swarm: make labels work with older docker daemon versions

### LINKED ISSUE #51175: docker_swarm init fails on consecutive runs with warnings about urllib3 and charded and KeyError regarding "Labels"
##### SUMMARY

I am building a playbook to init a swarm cluster via Ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`docker_swarm`

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /ansible-all-the-things/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Dec 29 2018, 07:19:27) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/foo/ansible-all-the-things/ansible.cfg) = [u'/foo/ansible-all-the-things/hosts.yml']
DEFAULT_SCP_IF_SSH(/foo/ansible-all-the-things/ansible.cfg) = True
DEFAULT_TRANSPORT(/foo/ansible-all-the-things/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /foo/.vault_pass.txt
HOST_KEY_CHECKING(/foo/ansible-all-the-things/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Running Ansible inside a Docker container (`FROM python:3.7-slim`)
Target OS (where this fails) is: CentOS7

```
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
```

##### STEPS TO REPRODUCE

 - put the code into a playbook
 - run it once, it works
 - run it twice, it fails 😿 

```yaml
...
- tasks:
  - name: Enable swarm mode
    docker_swarm:
      state: present
```

##### EXPECTED RESULTS

 - a single node Swarm cluster
 - a successful Ansible run

##### ACTUAL RESULTS

 - first run, works as expected (Yay!)
 - on **consecutive runs**, Ansible fails with the following:

```
fatal: [node-01]: FAILED! => {"changed": false, "module_stderr": "Shared connection to node-01 closed.\r\n", "module_stdout": "/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.2.1) doesn't match a supported version!\r\n  RequestsDependencyWarning)\r\nTraceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1548156057.5468266-261250085584743/AnsiballZ_docker_swarm.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1548156057.5468266-261250085584743/AnsiballZ_docker_swarm.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1548156057.5468266-261250085584743/AnsiballZ_docker_swarm.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_docker_swarm_payload_2QlvP8/__main__.py\", line 535, in <module>\r\n  File \"/tmp/ansible_docker_swarm_payload_2QlvP8/__main__.py\", line 530, in main\r\n  File \"/tmp/ansible_docker_swarm_payload_2QlvP8/__main__.py\", line 310, in __call__\r\n  File \"/tmp/ansible_docker_swarm_payload_2QlvP8/__main__.py\", line 333, in init_swarm\r\n  File \"/tmp/ansible_docker_swarm_payload_2QlvP8/__main__.py\", line 390, in __update_swarm\r\n  File \"/tmp/ansible_docker_swarm_payload_2QlvP8/__main__.py\", line 376, in __update_spec\r\nKeyError: 'Labels'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

```paste below

```

When I run `init` twice on the shell, this is the result:

```
[root@node-01 ~]# docker swarm init
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.
[root@node-01 ~]# echo $?
1
```

I was hoping that `docker_swarm` handles this for me.

```
[root@node-01 ~]# docker node ls
ID                           HOSTNAME                                   STATUS  AVAILABILITY  MANAGER STATUS
udvnedzjq2kgw20wrvd5mqjlx *  node-01  Ready   Active        Leader
```

My take on configuration management is that the playbook should run as often as it's triggered and in the end leave me with my expected state. If Swarm is already initialised, it should not fail.

Can I do anything to contribute to this, or provide more information? I am a little new to Python and Ansible, but I am happy to learn and help.

---

Sort of related, but maybe unrelated — the warnings about `urllib3` and `chardet`: I upgraded them to their latest releases, still not sure why the warning shows up. Should I open another bug report?

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Swarm node labels don't work with older docker daemon versions.

Fixes #51175. Supersedes #51264.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_swarm

### CODE REVIEW

**Comment by WojciechowskiPiotr** [comment]
Maybe it should be good to move `inspect_swarm` to `DockerAnsibleSwarmClient`? And difference tracker as well?

**Comment by felixfontein** [comment]
`inspect_swarm` makes sense, at least the part which calls `client.inspect_swarm()` and decodes the output. Moving the difference tracker doesn't make sense, because that's not needed for every module which uses `DockerAnsibleSwarmClient` (facts modules don't need it, for example), and modules might want to use it differently than it is used in `docker_swarm`.

Anyway, in this PR `DockerAnsibleSwarmClient` isn't available since this PR needs to be backported to 2.7.

**Comment by WojciechowskiPiotr** [comment]
> `inspect_swarm` makes sense, at least the part which calls `client.inspect_swarm()` and decodes the output. 

Ok, we will move it later when this PR gets merged

**Comment by WojciechowskiPiotr** [comment]
shipit

**Comment by gundalow** [comment]
Merged, thanks all!

**Comment by felixfontein** [comment]
@WojciechowskiPiotr thanks for reviewing!
@gundalow thanks for merging!

**Pull request merged**
