### PR TITLE
Fixing md5 check on nxos_file_copy

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_file_copy

##### ANSIBLE VERSION
```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Fix md5 sums check

### CODE REVIEW

**Comment by GGabriele** [comment]
Migrated from https://github.com/ansible/ansible-modules-core/pull/5570

**Comment by privateip** [comment]
Shouldn't this and #19556 be a single PR?

**Comment by GGabriele** [comment]
@privateip originally these two PRs were done against devel and stable-2.2, but the PR migration tool moved both against devel here

**Comment by gundalow** [comment]
@GGabriele What branch should this PR be against?
If you click "edit" at the top of the page (in the same way if you wanted to edit the title) you should be able to alter what branch this is against. If not let me know and I'll update this.

**Comment by GGabriele** [comment]
@gundalow this should be against `2.2` . If I change the branch from devel to `2.2` or `2.1` I see that modules are still referenced in `ansible-modules-core` and `ansible-modules-extra`...so, how can I open a new PR for `2.1`/`2.2`

**Comment by gundalow** [comment]
We didn't repo merge `stable-2.2`.

If this fix is more than a simple cherrypick of a devel (2.3) change  into 2.2 then a separate PR should be raised against `ansible-modules-*`

**Comment by gundalow** [comment]
@GGabriele I wonder if it's going to be cleaner for your to raise fresh PR(s) for this

**Comment by GGabriele** [comment]
@gundalow it is for sure. Closing this.

**Pull request closed without merging**
