### PR TITLE
gather_facts action plugin: Fix loading network facts modules for smart gathering

### PR DESCRIPTION
**Pull request by trishnaguha**
##### SUMMARY

fix smart gathering for network_os in gather_facts action plugin
Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>
(cherry picked from commit 5cd3be9129c81388c213bcd6b5de7741b9eee8c4)

Backport of https://github.com/ansible/ansible/pull/59856

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by abadger** [comment]
@trishnaguha The shippable test failures for this look valid.

**Comment by abadger** [comment]
@trishnaguha Ping, just a reminder that the test failures for this have to be looked at before it can be merged.

**Comment by mattclay** [comment]
@trishnaguha Are you planning on fixing the test failures with this backport, or can it be closed?

**Comment by mattclay** [comment]
Closing, since 2.8 is receiving only critical bug fixes at this point.

**Pull request closed without merging**
