### PR TITLE
VMware: Add a pointer on how to get possible values.

### PR DESCRIPTION
**Pull request by xenlo**
Describe how gitting more input on the advanced options we can play with this module.
+label: docsite_pr

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by Akasurde** [comment]
@xenlo Thanks for the PR. You can use `vmware_host_config_facts` to gather information about Advance configuration and their values. 

Output of `vmware_host_config_facts` 

```
     "hosts_facts": {
        "10.76.33.226": {
           ...
            "CBRC.DigestJournalBootInterval": 10,
            "CBRC.Enable": false,
            "COW.COWMaxHeapSizeMB": 192,
            "COW.COWMaxREPageCacheszMB": 256,
            "COW.COWMinREPageCacheszMB": 0,
            "COW.COWREPageCacheEviction": 1,
            ...
        }
    }
```

Also, add example in `vmware_host_config_manager` EXAMPLE section with this information.

**Review by dagwieers — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
rebuild_merge

**Comment by samccann** [comment]
rebuild_merge

**Pull request merged**
