### PR TITLE
Enable check mode for aws_iam_role

### PR DESCRIPTION
**Pull request by cahlchang**
##### SUMMARY
Check mode of aws/iam_role module is enabled.
If the check mode is disabled, the behavior is not changed.

Related
#26959

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
iam_role

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.5.1
  config file = /my_path/ansible.cfg
  configured module search path = ['/my_path/lib']
  ansible python module location = /usr/local/pyenv/versions/3.6.3/envs/devel/lib/python3.6/site-packages/ansible
  executable location = /usr/local/pyenv/versions/devel/bin/ansible
  python version = 3.6.3 (default, Dec 13 2017, 03:46:07) [GCC 4.8.2]
```

##### ADDITIONAL INFORMATION
There is one thing to think about.

I want to make the return value equal to the actual execution time.
However, in the check mode at the time of new creation, it is not actually created, so some parameters can not be acquired.
For example, arn.
It is possible to give it pseudo, but I can not think it is correct, so I left it.
If someone has an opinion on this, I would like to reflect it.

Normal execution
```
changed: [localhost] => {
    "arn": "my_arn",
    "assume_role_policy_document": {
        "statement": [
            {
                "action": "sts:AssumeRole",
                "effect": "Allow",
                "principal": {
                    "service": "ec2.amazonaws.com"
                }
            }
        ],
        "version": "2008-10-17"
    },
    "attached_policies": [],
    "changed": true,
    "create_date": "2018-04-19T09:16:20+00:00",
    "gid": 0,
    "group": "root",
    "iam_role": {
        "arn": "my_arn",
        "assume_role_policy_document": {
            "statement": [
                {
                    "action": "sts:AssumeRole",
                    "effect": "Allow",
                    "principal": {
                        "service": "ec2.amazonaws.com"
                    }
                }
            ],
            "version": "2008-10-17"
        },
        "attached_policies": [],
        "create_date": "2018-04-19T09:16:20+00:00",
        "path": "/",
        "role_id": "my_role_id",
        "role_name": "my_role_name"
    },
    "invocation": {
        "module_args": {
            "assume_role_policy_document": "{\"Version\": \"2008-10-17\", \"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ec2.amazonaws.com\"}}]}",
            "aws_access_key": null,
            "aws_secret_key": null,
            "create_instance_profile": true,
            "description": null,
            "ec2_url": null,
            "managed_policy": null,
            "name": "my_name",
            "path": "/",
            "profile": "my_cred",
            "purge_policies": true,
            "region": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "mode": "0755",
    "owner": "root",
    "path": "/",
    "role_id": "my_role_id",
    "role_name": "my_role_name",
    "size": 4096,
    "state": "directory",
    "uid": 0
}
```

Check mode for new creation
```
changed: [localhost] => {
    "assume_role_policy_document": {
        "statement": [
            {
                "action": "sts:AssumeRole",
                "effect": "Allow",
                "principal": {
                    "service": "ec2.amazonaws.com"
                }
            }
        ],
        "version": "2008-10-17"
    },
    "changed": true,
    "iam_role": {
        "assume_role_policy_document": {
            "statement": [
                {
                    "action": "sts:AssumeRole",
                    "effect": "Allow",
                    "principal": {
                        "service": "ec2.amazonaws.com"
                    }
                }
            ],
            "version": "2008-10-17"
        },
        "made_in_check_mode": true
    },
    "invocation": {
        "module_args": {
            "assume_role_policy_document": "{\"Version\": \"2008-10-17\", \"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ec2.amazonaws.com\"}}]}",
            "aws_access_key": null,
            "aws_secret_key": null,
            "create_instance_profile": true,
            "description": null,
            "ec2_url": null,
            "managed_policy": null,
            "name": "my_name",
            "path": "/",
            "profile": "my_cred",
            "purge_policies": true,
            "region": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "made_in_check_mode": true
}
```

Check mode when changing parameters
```
changed: [localhost] => {
    "arn": "my_arn",
    "assume_role_policy_document": {
        "statement": [
            {
                "action": "sts:AssumeRole",
                "effect": "Allow",
                "principal": {
                    "service": "ec2.amazonaws.com"
                }
            }
        ],
        "version": "2008-10-17"
    },
    "attached_policies": [],
    "changed": true,
    "create_date": "2018-04-19T09:16:20+00:00",
    "gid": 0,
    "group": "root",
    "iam_role": {
        "arn": "my_arn",
        "assume_role_policy_document": {
            "statement": [
                {
                    "action": "sts:AssumeRole",
                    "effect": "Allow",
                    "principal": {
                        "service": "ec2.amazonaws.com"
                    }
                }
            ],
            "version": "2008-10-17"
        },
        "attached_policies": [],
        "create_date": "2018-04-19T09:16:20+00:00",
        "path": "/",
        "role_id": "my_role_id",
        "role_name": "my_role_name"
    },
    "invocation": {
        "module_args": {
            "assume_role_policy_document": "{\"Version\": \"2008-10-17\", \"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ec2.amazonaws.com\"}}]}",
            "aws_access_key": null,
            "aws_secret_key": null,
            "create_instance_profile": true,
            "description": null,
            "ec2_url": null,
            "managed_policy": [
                "arn:aws:iam::aws:policy/PowerUserAccess"
            ],
            "name": "my_role_name",
            "path": "/",
            "profile": "my_cred",
            "purge_policies": true,
            "region": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "mode": "0755",
    "owner": "root",
    "path": "/",
    "role_id": "my_role_id",
    "role_name": "my_role_name",
    "size": 4096,
    "state": "directory",
    "uid": 0
}
```

Check mode when deleting
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "assume_role_policy_document": "{\"Version\": \"2008-10-17\", \"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ec2.amazonaws.com\"}}]}",
            "aws_access_key": null,
            "aws_secret_key": null,
            "create_instance_profile": true,
            "description": null,
            "ec2_url": null,
            "managed_policy": [
                "arn:aws:iam::aws:policy/PowerUserAccess"
            ],
            "name": "my_role_name",
            "path": "/",
            "profile": "my_cred",
            "purge_policies": true,
            "region": null,
            "security_token": null,
            "state": "absent",
            "validate_certs": true
        }
    }
}
```

### CODE REVIEW

**Review by s-hertel — COMMENTED** [review]
Have you tested the code path https://github.com/ansible/ansible/pull/39002/files#diff-f2b598ca64fd0e700df1d26a5b482f9dR268 in check mode when creating the role + adding managed policies? I think calling list_attached_role_policies with a role that hasn't been created yet will fail. It would be nice to have integration tests for this module.

**Comment by cahlchang** [comment]
Thanks for the review.

I have finished the test and confirmed that there is no problem.
"list_attached_role_policies" is safely handled by exception handling.
Please refer to this.
https://github.com/cahlchang/ansible/blob/27c35b43bb176e1bc8da9f2f65b3f93a7061ca9b/lib/ansible/modules/cloud/amazon/iam_role.py#L407-L417

If exception handling is not done, "botocore.errorfactory.NoSuchEntityException" is triggered.

However, adding integration test code is a very good idea.
I'd like to work on it soon. Are there any documents or reference tests on Ansible?
(I fixed the wording of a few comments)

**Review by s-hertel — APPROVED** [review]

**Comment by s-hertel** [comment]
@cahlchang Here are some general docs on running the tests: https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

For writing tests, I'd check out the way they are structured for a couple other modules, like https://github.com/ansible/ansible/tree/devel/test/integration/targets/ec2_instance and https://github.com/ansible/ansible/tree/devel/test/integration/targets/ec2_group. You can add tests for check mode by adding `check_mode: true` at the same indentation as you would for `loop` or `register`. Feel free to ping me here or on IRC (handle shertel) if you need a hand.

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
Thanks for adding this! @cahlchang when you get around to making integration tests, please mention this PR in the new one, so we know what the tests are for.

**Comment by cahlchang** [comment]
@s-hertel @ryansb 
Thank you very much!
I am very happy to have added check mode.

Thank you for telling me the way of the test code.
That is very helpful to me.
I would like to add test code and contribute.

**Pull request merged**
