### PR TITLE
ec2_asg: Add AWSRetry decorator to AWS calls

### PR DESCRIPTION
**Pull request by david-resnick**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ec2_asg
##### ANSIBLE VERSION

```
ansible 2.3.0 (ec2_asg_add_aws_retry 4867add4ad) last updated 2016/12/17 00:03:25 (GMT +300)
```
##### SUMMARY

Updated ec2_asg to use the AWSRetry.decorator.

I also fixed deleting notification topics from an autoscaling group that is being deleted.

Note that this was migrated manually from https://github.com/ansible/ansible-modules-core/pull/5242 which I wasn't able to migrate automatically.

### CODE REVIEW

**Comment by gundalow** [comment]
@linuxdynasty I see from the original PR https://github.com/ansible/ansible-modules-core/pull/5242 you were going to test this. Could you please review and add your comments here. Thanks

**Comment by gundalow** [comment]
Shippable timed out, so I've click rerun

**Review by ryansb — APPROVED** [review]
cc @linuxdynasty

**Comment by linuxdynasty** [comment]
I will check it out in the next couple of days.

**Comment by pierreant-p** [comment]
Hi, any news on this?
It feels like the decorator should be on all aws calls. We have an infrastructure with ~10 ASG, alarms metrics, and we hit the AWS ratelimit pretty often. This makes ansible pretty inconvenient to deploy a somewhat-large-ish infrastructure. The proposed fix seems quite straightforward and should be applied to all AWS api calls to make sure a module doesn't fail on this.

I think this is a long-standing issue that should be resolved very quickly.
I'm glad to help if I can. Let me know.

**Comment by s-hertel** [comment]
Hi @pierreant-p. Support for this has been merged in 6cb0666 for 2.3.

Since this module was much rewritten for 2.4 (it was ported to use boto3) it needs AWSRetry to be added again. I will cherry-pick these changes and rebase and update it for the current ec2_asg, and then close this.

**Comment by pierreant-p** [comment]
@s-hertel thx for letting me know, I'll check it out !
Glad that we're moving forward on this!

**Comment by s-hertel** [comment]
Closing this because I have opened #27598. It was too difficult to rebase this since the module was ported to boto3, but @david-resnick thanks for creating this. Being able to cherry pick your commit for the 2.3 version of retry was very helpful.

**Comment by david-resnick** [comment]
@s-hertel I'm glad it helped. Good to hear that this should finally make it into master.

**Pull request closed without merging**
