### PR TITLE
Add a hostname module, which sets system's hostname.

### PR DESCRIPTION
**Pull request by hnakamur**
I send this pull request in response to
https://groups.google.com/d/msg/ansible-project/komqS4WdqHU/cRfWiMnCR3cJ

Currently implemented on only Debian, Ubuntu, RedHat and CentOS.
Unfortunately I'm not familiar about settings hostnames on other systems.

I appreciate your feedbacks.

By the way, I searched the mailing list for prior discussions about a module to set hostname, but couldn't find them.
https://groups.google.com/forum/?hl=ja#!forum/ansible-project
@mpdehaan Could you point me to the url of the discussions?

### CODE REVIEW

**Comment by mpdehaan** [comment]
This code generally looks good but I have not tested it yet.  It will be good to have a hostname module. 

I'm ok with it doesn't set it on all platforms if it will raise an error when it can't be used on those platforms and use fail_json to explain it.

The extra syslogging should be removed as Ansible will already do that for you when a module is invoked, and we don't want any more verbosity than that.

This will also allow the "execute_command" function to be replaced with just module.run_command directly.

The "with" statement is Python 2.5 and later, so this will need to be written to not use "with" to support Python 2.4 systems.

@jimi1283 may have some other comments, this is just some initial review and some things that need to be fixed before we can accept this.

Thanks!

**Comment by hnakamur** [comment]
@mpdehaan Thanks for your initial review.
I modified the hostname module.
I tested it on CentOS 6.4 and Ubuntu 12.04.
I confirmed it raises an error on Darwin with message "hostname module cannot be used on platform Darwin".
Could you take another look?

@jimi1283 I'm looking forward to see your comments, too.

Thanks!

**Comment by mscherer** [comment]
For distribution based on systemd, the method is to call hostnamectl set-hostname 

That would work on Fedora, recent Mageia ( > 3 ) , Opensuse and Arch.

**Comment by mscherer** [comment]
In fact, looking at code, it would just work fine on those platform if you write /etc/hostname

**Comment by mpdehaan** [comment]
I'm sorry for the late reply, we have been swamped by pull requests and strategic features lately and are just now digging out :)

I'm still very interested in this one.

If you can update this to handle systemd distributions on the above that would be great as I suspect many people will be testing on those platforms.

**Comment by hnakamur** [comment]
Hi, I added a support for CentOS 5 (python 2.4), Fedora, OpenSUSE, and ArchLinux.

@mstuivenberg did test it on RHEL 5.6.
https://github.com/hnakamur/ansible-playbooks/issues/1

I tested it on Fedora 19 and OpenSUSE 12.3, but I did not test it on ArchLinux.
I tried to create a test environment for ArchLinux with vagrant boxes listed on http://www.vagrantbox.es/
https://dl.dropboxusercontent.com/u/31112574/arch64-20130801.box
https://googledrive.com/host/0B_BLFE4aPn5zUVpyaHdLanVnMTg/vagrant-archlinux-2013-8.box
but failed.

Could someone test this on ArchLinux?
Thanks.

**Comment by hnakamur** [comment]
@mstuivenberg did check this on RHEL6 at https://github.com/hnakamur/ansible-playbooks/commit/a8718f30cf0adcd4ba572908dad6c3762fdcffce#commitcomment-4496179 Thanks!

**Comment by jctanner** [comment]
Tested successfully ...

```
TASK: [hostname name="{{inventory_hostname}}"] ******************************** 
failed: [el5.lab.net] => {"failed": true}
msg: hostname module cannot be used on platform Linux (Redhat)
...ignoring
ok: [el4.lab.net] => {"changed": false, "name": "el4.lab.net"}
ok: [el6.lab.net] => {"changed": false, "name": "el6.lab.net"}
failed: [opensuse10.lab.net] => {"failed": true}
msg: hostname module cannot be used on platform Linux (Suse)
...ignoring
```

**Comment by hnakamur** [comment]
Thanks for merging!

**Comment by mstuivenberg** [comment]
Seems like it's not working with RHEL5; Submitted changes to @hnakamur for assessment;

**Comment by hnakamur** [comment]
@mstuivenberg Thanks for pull request https://github.com/hnakamur/ansible-playbooks/pull/2.
I merged it to my project and sent the same pull request to the ansible project https://github.com/ansible/ansible/pull/4868

**Comment by jiv-e** [comment]
I tried to use hostname module and I get this...
ERROR: hostname is not a legal parameter in an Ansible task or handler

Line causing the error is:
- hostname: name=test

I have Ansible 1.4. My local environment is Mac OS X and remote is Vagrant Ubuntu 12.04.3 LTS.
No tips here: http://www.ansibleworks.com/docs/modules.html#hostname

**Comment by gundalow** [comment]
@jiv-e Are you sure you've got 1.4 installed?
ansible-playbook --version

which ansible-playbook
ls <ansible-dir>/library/system/hostname

**Comment by jiv-e** [comment]
I moved this here: https://github.com/ansible/ansible/issues/5304

**Comment by chestel** [comment]
Hi @hnakamur,

I'd like to use your great hostname module on all my Linux servers. Some of them are the Amazon distro derived from Redhat. They are fundamentally the same RedHat under the covers and so I'm sure the RedHatStrategy would work fine with them.

However ansible_distribution is defined as Amazon and so returns an unimplemented_error.

Would it be appropriate to use ansible_os_family instead of ansible_distribution to determine strategy?

If so, this module would pick up support for some more distros for free.

Cheers,
Leo

**Comment by hnakamur** [comment]
Hello @chestel,

Thanks for your report.
I added a support for Amazon Linux the hostname module.
https://github.com/hnakamur/ansible/commit/47b19e9e5c0b9cfaf1c10371d3618c39142033a9

Could you test it?
If it works successfully, I will send a pull request to the ansible project.

Cheers,
Hiroaki

**Comment by dragon3** [comment]
Hi @hnakamur , @chestel 

I already send a pull request #5090 for support Amazon Linux and that was merged.
Which ansible version do you use?

**Comment by hnakamur** [comment]
Hi, @dragon3 

Thanks for letting me know a pull request #5090.
I didn't notice it and made a mistake when I fetched and merged the latest ansible source.

@chestel 
Please forget about my commit hnakamur@47b19e9 and just use the latest commit.

**Comment by chestel** [comment]
I've pulled v 1.5 and Amazon hosts now work with the hostname module.

Thank you both very much!

**Pull request merged**
