### PR TITLE
add new command CreateRaidVolume and DeleteRaidVolume in redfish_config module

### LINKED ISSUE #67726: redfish_config - Systems - CreateRaidVolume / DeleteRaidVolume
##### SUMMARY
This feature would implement a CreateRaidVolume command for the Systems category of redfish_config, to create a raid volume on raid controller. And it would also implement a DeleteRaidVolume command for the Systems category of redfish_config, to delete an unneeded raid volume from raid controller.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
redfish_config

#####ADDITIONAL INFORMATION
These 2 commands would help user to create or delete raid volume

### PR DESCRIPTION
**Pull request by panyy3**
##### SUMMARY
add CreateRaidVolume and DeleteRaidVolume in redfish_config module to create or delete raid volume.
Fixes #67726

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
redfish_config

##### ADDITIONAL INFORMATION
none

### CODE REVIEW

**Comment by rajeevkallur** [comment]
Hi, Can you put the output of these commands  after running it on a server

**Review by rajeevkallur — COMMENTED** [review]
Please paste output of these commands

**Comment by panyy3** [comment]
@rajeevkallur Output of these commands are listed as below.

1. get volume before create
Perform task as below:
    redfish_info:
      category: Systems
      command: GetVolumeInventory

Output is shown below:
    "msg": {
        "volume": {
            "entries": [
                [
                    {
                        "system_uri": "/redfish/v1/Systems/1"
                    },
                    [
                        {
                            "Controller": "ThinkSystem RAID 530-8i PCIe 12Gb Adapter",
                            "Volumes": []
                        }
                    ]
                ]
            ],
            "ret": true
        }
    }

2. create volume
Perform task as below:
    redfish_config:
      category: Systems
      command: CreateRaidVolume
      raidtype: RAID0 
      capacityGB: 20
      volumename: volume_a
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      volumeproperties:
        Oem:
          Lenovo:
            WritePolicy: WriteThrough
            AccessPolicy: ReadWrite

Output is shown below:
    "msg": {
        "changed": true,
        "failed": false,
        "msg": "Raid volume created"
    }

3. get volume after create
Perform task as below:
    redfish_info:
      category: Systems
      command: GetVolumeInventory

Output is shown below:
    "msg": {
        "volume": {
            "entries": [
                [
                    {
                        "system_uri": "/redfish/v1/Systems/1"
                    },
                    [
                        {
                            "Controller": "ThinkSystem RAID 530-8i PCIe 12Gb Adapter",
                            "Volumes": [
                                {
                                    "AccessCapabilities": [
                                        "Read",
                                        "Write"
                                    ],
                                    "BlockSizeBytes": 512,
                                    "Capacity": {
                                        "Data": {},
                                        "Metadata": {},
                                        "Snapshot": {}
                                    },
                                    "CapacityBytes": 21474836480,
                                    "Id": "15",
                                    "Linked_drives": [
                                        {
                                            "Id": "Disk.0"
                                        }
                                    ],
                                    "Name": "volume_a",
                                    "RAIDType": "RAID0",
                                    "Status": {
                                        "Health": "OK",
                                        "State": "Enabled"
                                    }
                                }
                            ]
                        }
                    ]
                ]
            ],
            "ret": true
        }
    }

4. delete volume with error volume name
Perform task as below:
    redfish_config:
      category: Systems
      command: DeleteRaidVolume
      volumename: Volume1

Output is shown below:
    {"changed": false, "msg": "Can not find volumename Volume1. volumename should be in volume name list: ['volume_a']"}

5. delete volume with correct volume name
Perform task as below:
    redfish_config:
      category: Systems
      command: DeleteRaidVolume
      volumename: volume_a

Output is shown below:
    "msg": {
        "changed": true,
        "failed": false,
        "msg": "Raid volume deleted"
    }

**Comment by billdodd** [comment]
@panyy3 FYI - Here is a link with some information about how to get this PR migrated over to the new ansible-collections/community.general repository:

https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md

I just did this recently with my open Redfish issue and PR. I did the migration manually by recreating the issue and the PR over in the new repository. I did not try to use the prmove script referenced in the link above. (It looked more complicated than just manually recreating.)
For reference, if you want to look at the issue and PR I migrated, here are the links:

Original issue: #58941 
Original PR: #68053 

New issue: https://github.com/ansible-collections/community.general/issues/493
New PR: https://github.com/ansible-collections/community.general/pull/494

**Pull request closed without merging**
