### PR TITLE
Allow wait_for to wait on non-traditional files

### LINKED ISSUE #6710: wait_for hangs on UNIX pipes
When trying to `wait_for` a pipe, it might block forever. This is because the process blocks until the other end of the pipe gets opened. A solution to this would be to use `stat` before trying to open the file.

### PR DESCRIPTION
**Pull request by hfinucane**
Use os.path.exists to check for file existence, instead of "can we open
this file for reading".

Fixes #6710

### CODE REVIEW

**Comment by jimi-c** [comment]
Edited, as it was not accurate. However, using os.path.exists() on a path that does exist but is not accessible returns False as opposed to giving some other error. If you use os.stat() instead, a proper error is raised as follows:

<pre>
>>> os.path.exists('/var/log/httpd/error.log')
False
>>> os.stat('/var/log/httpd/error.log')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 13] Permission denied: '/var/log/httpd/error.log'
</pre>

That error should be caught and fail_json used to properly alert the user as opposed to returning a false-positive/false-negative.

**Comment by hfinucane** [comment]
The semantics of the code _before_ this patch was, if it cannot access a file because of permissions, it will retry until it can (or time out). I preserved that.

Do you still want me to change it?

**Comment by jimi-c** [comment]
Yes, I think failing fast is more appropriate than waiting for it to timeout. The modifications to your patch should be fairly minimal.

**Comment by hfinucane** [comment]
Indeed. New version should return errors like
`"msg": "Failed to stat /proc/1/exe, Permission denied"`
when failing.

**Comment by jimi-c** [comment]
Looks good, we'll get it in queue for testing as soon as possible. Thanks!

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
