### PR TITLE
Letsencrypt: improving EC account key parsing for 2.5

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The tests added in #37275 showed that EC account key parsing does not work for some OpenSSL versions. This PR integrates the fix there into the `stable-2.5` branch.

Note: EC account keys seem to have problems with OSX (https://app.shippable.com/github/ansible/ansible/runs/57526/24/console; `Error Signing Data\n534:error:0606B06E:digital envelope routines:EVP_SignFinal:wrong public key type:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59/src/crypto/evp/p_sign.c:99:`). But that seems to be more complicated to fix, if it is possible after all.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION
2.5.0

### CODE REVIEW

**Comment by felixfontein** [comment]
Looks like ECC with OSX' OpenSSL seems to be broken (https://security.stackexchange.com/a/56065). I guess we can simply ignore this for now.

**Comment by felixfontein** [comment]
Passed tests against ACME v1 staging endpoint and the Pebble testing server (for ACME v2).

**Comment by resmo** [comment]
@felixfontein is there a PR against the devel branch also fixing this?

**Comment by felixfontein** [comment]
@resmo Yes, it's commit ec977988b35caacd0f13470ef62d55ec91d16de1 of #37275.

**Comment by resmo** [comment]
@felixfontein could you separate the commit for devel? The problem is, that the commit is part of a feature and it will get squshed. And it is not good practice to have backport commits merged,  not yet merged in devel.

**Comment by felixfontein** [comment]
Sure! See #37293. The commit there can also go directly to 2.5, it is the same commit as in here.

**Comment by felixfontein** [comment]
Since #37293 has been merged, how about this one @resmo?

**Comment by resmo** [comment]
Thanks for the hint. Seems I am able to merge to stable-2.5 again. merging.

**Review by resmo — APPROVED** [review]
shipit

**Comment by resmo** [comment]
Just FYI, please use `git cherry-pick -x` for backports PR, so we get a reference of the origin commit in the commit message. ;)

**Comment by felixfontein** [comment]
Ah, that's good to know. Thanks!

**Pull request merged**
