### PR TITLE
doc: add documentation for "vars" magic variable

### PR DESCRIPTION
**Pull request by tchernomax**
##### SUMMARY

Document the `vars` magic variable.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

special_variables

##### ADDITIONAL INFORMATION

This variable is define:

https://github.com/ansible/ansible/blob/c2253c8133e6b0e97c456ef38ad27b13d65fac4d/lib/ansible/vars/manager.py#L421-L424

### CODE REVIEW

**Review by angristan — APPROVED** [review]
LGTM :+1:

**Review by bcoca — CHANGES_REQUESTED** [review]
First, this is incorrect, `vars` is currently a superset of hostvars, not an equivalent. 

Second, this was not intended for direct use, it was used internally for templating, so you will get  some untemplated values when using vars.

Currently it is not in use anymore and we plan on removing it, so I would not document it at all.

**Comment by angristan** [comment]
Thanks for letting us know 🙂

**Comment by tchernomax** [comment]
> Currently it is not in use anymore and we plan on removing it, so I would not document it at all.

OK, we where actually wondering that and we thought the fastest way to know was to make this pull request.

Thanks.

I am closing this PR.

**Pull request closed without merging**
