### PR TITLE
Fix Issue #39598

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Fix Issue #49612

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/network/onyx/onyx_config.py

##### ADDITIONAL INFORMATION

```
ansible 2.8.0.dev0 (issue/39598 bcdfd1fda2) last updated 2018/12/16 12:56:33 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev8/lib/ansible
  executable location = /.autodirect/mtrswgwork/anasb/ansible_dev8/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

### CODE REVIEW

**Comment by anasbadaha** [comment]
Hi @samerd ,

I found that the issue in this bug is as the following:
when you trying to run command "configuration write" the switch mode will be in enable mode and in order to run "configuration write" command you must be in configuration mode I tried it with this solution and it's passed.

Please let me know if you have farther comments

**Review by samerd — APPROVED** [review]
Thanks Anas.
Well done.

**Comment by anasbadaha** [comment]
Hi @ganeshrn,

@samerd  approved this PR please merge it if you don't have any farther comments

**Review by samerd — CHANGES_REQUESTED** [review]
After a second review:
I think using edit_config('configuration write') will be a better solution as it added configure terminal.
another option is to add the 'configuration write' command to the list of configuration command

**Comment by anasbadaha** [comment]
Hi @samerd Please check if this fix is OK for you

**Review by samerd — CHANGES_REQUESTED** [review]
`result['changed'] = True`
This should be done whenever total_commands list is not empty, regardless of the check mode

**Comment by anasbadaha** [comment]
Done @samerd please approve

**Review by samerd — APPROVED** [review]
Thanks Anas.

**Comment by anasbadaha** [comment]
Hi @ganeshrn @samerd has approved this PR please merge it!

**Comment by anasbadaha** [comment]
Hi @ganeshrn @samerd has approved this PR as well please merge it

**Pull request merged**
