### PR TITLE
Correct the formatting for conditional example and change to use out-of-...

### PR DESCRIPTION
**Pull request by lwade**
...the-box fact.  Tested this against currently 1.3 devel snapshot to make sure its valid.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Somewhat concerned that ascii comparisons against the full string aren't smart here.

**Comment by lwade** [comment]
Ok, so pipe it through int to get a real integer for comparison?

when: ansible_os_family == 'RedHat' and ansible_distribution_version|int >= 6.3

**Comment by dmedvinsky** [comment]
I think you want to use `float` instead of `int`.

**Comment by bcoca** [comment]
Actually, neither works for version comparisons, you want something from
pytthon's distutils.version

Brian Coca

**Comment by lwade** [comment]
hey @bcoca, I'm not sure how that relates to this evaluation against this returned fact?  Are you suggesting some code changes to allow robust version comparisons?

@dmedvinsky, yup guess so re: |float.

**Comment by bcoca** [comment]
yes, add a |version might be better. as float will break with 6.1.2 vs
4.4a, for example.

On Thu, Aug 1, 2013 at 5:28 AM, Lester Wade notifications@github.comwrote:

> hey @bcoca https://github.com/bcoca, I'm not sure how that relates to
> this evaluation against this returned fact? Are you suggesting some code
> changes to allow robust version comparisons?
> 
> @dmedvinsky https://github.com/dmedvinsky, yup guess so re: |float.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3700#issuecomment-21924831
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Where is there a " | version" defined and how would it work if it is not?

I believe the lsb_release if installed breaks it into components.

**Comment by mpdehaan** [comment]
Closing this as we should use the LSB module, I will fix the formatting error right now.

**Pull request closed without merging**
