### PR TITLE
Fixing bug #1655

### LINKED ISSUE #1655: ec2_lc fails with TypeError: LaunchConfiguration:test-lc is not JSON serializable (devel branch)
Running a lc create as simple as:

```
- name: s launch configuration
  ec2_lc:
    name: test-lc
    instance_type: m3.medium
    region: us-west-2
    state: present
```

Returns:

`TASK [s_setup : s_setup : s launch configuration] *******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: LaunchConfiguration:test-lc is not JSON serializable
fatal: [localhost]: FAILED! => {"invocation": {"module_name": "ec2_lc", "module_args": {"instance_type": "m3.medium", "region": "us-west-2", "name": "test-lc", "state": "present"}}, "failed": true, "changed": false, "parsed": false}`

### PR DESCRIPTION
**Pull request by evanccnyc**
This should fix https://github.com/ansible/ansible-modules-core/issues/1655

It works in my local branch.

### CODE REVIEW

**Comment by abadger** [comment]
I'm not seeing how the loop would ever select "unicode_escape" ... Everything should be decodable via latin-1 (although mangled) and everything should be encodable via utf-8.  So between those two the loop should never progress to the unicode_escape.

Could you post the traceback so I can try to diagnose which of the calls isn't doing what I expect it to?

**Comment by evanccnyc** [comment]
```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1436903370.89-180432659703901/ec2_lc", line 2148, in <module>
    main()
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1436903370.89-180432659703901/ec2_lc", line 2144, in main
    create_launch_config(connection, module)
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1436903370.89-180432659703901/ec2_lc", line 2091, in create_launch_config
    result=result)
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1436903370.89-180432659703901/ec2_lc", line 1444, in exit_json
    print self.jsonify(kwargs)
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1436903370.89-180432659703901/ec2_lc", line 1422, in jsonify
    return json.dumps(new_data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: LaunchConfiguration:Production - test LC is not JSON serializable
```

**Comment by evanccnyc** [comment]
Any update on this?

**Comment by evanccnyc** [comment]
@abadger Have you had time to look into this? This is still broken.

**Comment by abadger** [comment]
Looked at this and talked with @evanccnyc  on IRC.  determined that jsonify is doing the right thing but there's an error in the ec2_lc module.  Trying to figure that out in https://github.com/ansible/ansible-modules-core/issues/1655

**Pull request closed without merging**
