### PR TITLE
cpm_plugs module addition

### PR DESCRIPTION
**Pull request by syncpak**
##### SUMMARY
Added a module to reboot, turn power on/off and get plug statistics for Western Telematic CPM and VMR units

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
cpm_plugs

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (cpm_plugs 5a5535f5be) last updated 2018/10/16 08:26:56 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kenp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kenp/ansible/lib/ansible
  executable location = /home/kenp/ansible/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by dmobergIT** [comment]
Hi there, on your past modules you actually included a live link that we could test it on. Could you do the same for this module ?

**Comment by mattsene** [comment]
For the plug_id can I specify more than 1 plug at a time ?

**Comment by vientiane** [comment]
If I reboot a plug, how long is it until the power comes back on ?

**Comment by actionemb** [comment]
Is there a way I can also configure the plug parameters? For instance I wanted to be able to change the plug names and the boot priority. 
The module seems to work OK on our VMR units. We also have CPMs with current monitoring. will this module also work with these units ?

**Comment by syncpak** [comment]
@mattsene For the plug_id, on this current release you can only define one plug at a time. It is not a limitation of Ansible but of the WTI RESTful API of the device. WTI is updating the API to be able to accept more than one plug number or plug name in the next WTI release. If you need more details please email service@wti.com, they can give you a release schedule or setup you up for a beta release so you can try it.

**Comment by syncpak** [comment]
@vientiane The reboot delay can be modified in the Plug Parameter menu in the WTI device. If you get to the command line and issue a /PL with will get you to the plug define menu. This also gets into the @actionemb question, yes WTI will add plug parameter configuration.

**Comment by syncpak** [comment]
@actionemb Yes this module will work on CPM and VMR units, as long as they have Power, the plug control will work. Also we will add plug configuration to this module, we need to add the functionality to the underlying API first.

**Comment by syncpak** [comment]
Hello @jborean93 , could you tell me what i am doing wrong ? On two separate occasions today shipable has given me cancelled errors. Is this something i am doing wrong ? I don't see any errors messages that my code is the problem. Thanks

**Comment by syncpak** [comment]
Hello @actionemb , @vientiane , @mattsene, @dmobergIT I am going to close this pull request and start a new one. I was going to add plug configuration to this module along with control, but it got to messy so i am going to rename this module and add another for configuration When it is up i will send a notice. Thanks

**Pull request closed without merging**
