### PR TITLE
add poldek package manager, based on pacman

### PR DESCRIPTION
**Pull request by glensc**
add support for [poldek](https://gitorious.org/poldek) package manager, based on pacman

### CODE REVIEW

**Comment by mpdehaan** [comment]
We're not going to include alternative package managers for platforms (we have yum in core), though I welcome the interest in adding this.

**Comment by glensc** [comment]
what you mean, pld-linux.org package manager is poldek, not yum

**Comment by mpdehaan** [comment]
First I've heard of this distro.

**Comment by glensc** [comment]
i don't understand the rejection, docs say i should contribute the package manager if it's missing http://ansible.cc/docs/examples.html: 

```
Currently Ansible only has modules for managing packages with yum and apt. You can install for other packages for now using the command module or (better!) contribute a module for other package managers. Stop by the mailing list for info/details.
```

so you are saying rpm based distros may be managed only by yum? meaning suse's ZYpp and mandrake's urpmi will be rejected too? yum is not functional with rpm5 what pld-linux.org is using, so enforcing yum will limit functionality

**Pull request closed without merging**
