### PR TITLE
Pylint fixes for packaging

### PR DESCRIPTION
**Pull request by Akasurde**
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### SUMMARY
Pylint fixes for apk, apt and dpkg_selections modules

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/packaging/os/apk.py
lib/ansible/modules/packaging/os/apt.py
lib/ansible/modules/packaging/os/dpkg_selections.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by sivel** [comment]
Closing and re-opening to re-trigger CI

**Comment by sivel** [comment]
Merged, thanks!

**Comment by Akasurde** [comment]
@sivel Thanks.

**Pull request merged**
