### PR TITLE
ssh pipelining + tty, use python -c

### PR DESCRIPTION
**Pull request by jeromew**
Here is a proposal for pipelining + tty. It works on my production playbook so I am fairly confident.

My hopes of a real pipeline in the TTY cases are pretty low after a lot of research. This is because python automatically enters the interactive shell mode when tty is activated and this slows things down. It is very slow because in order to make it work you have to send the code line by line, waiting for a ">>> " or a "... " prompt before sending another line. There seem to be limits on the size of the lines and is all very annoying.

This new version takes another approach by using the "python -c" flag : you can send the whole module as an argument of the python command. This works with TTY activated.

I added a requireTTY = True variable at the top so this could become either a configuration variable or something sent from another part of the code ; when requireTTY = false, the usual pipelining stuff takes place.

On the "cons" side : 
- there is a limit regarding the size of linux command line

```
$xargs --show-limits
Your environment variables take up 2820 bytes
POSIX upper limit on argument length (this system): 2092284
POSIX smallest allowable upper limit on argument length (all systems): 4096
Maximum length of command we could actually use: 2089464
Size of command buffer we are actually using: 131072
```

so 131K is the default limit (fedora19). I guess this is pretty standard but I have no idea.

now if you take the module code, the maximum byte size is 96K for m=setup. you have to add to this the module boilerplate.

now you have to take into account that this is escaped N times (sudo, sh, sh, ssh whatever), so a single quote (one ' ) gets expanded to a sort of "'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"

that's a big hit on the 131K limit, and I have experienced a problem with : user, service, setup.

in order to solve this issue, I needed to lower the number of single quotes and increase the number of double quotes which are not escaped in this case (pipe.quotes)

This is done by a tokenize/untokenize loop at the python level because I was more confident I could make it work this way than by monkey regexing the module code. It could be faster maybe to do it with regex and maybe less prone to python version differences that may exist in the tokenize/untokenize loop. A rewrite of all the modules to enfore double quotes could also be an option.

This can be considered a hack ; but it is a working hack for the TTY case :-)

I hope you will have time to review it and maybe accept it :-)

### CODE REVIEW

**Comment by jeromew** [comment]
found an interesting article on http://www.in-ulm.de/~mascheck/various/argmax/

```
And as additional limit since 2.6.23, one argument must not be longer than MAX_ARG_STRLEN (131072). 
This might become relevant if you generate a long call like "sh -c 'generated with long arguments'". 
```

**Comment by jimi-c** [comment]
If all of the code is sent via the command line, wouldn't this expose passwords and other sensitive information to `ps aux`?

**Comment by jimi-c** [comment]
After talking this over, I don't think we want to pursue this method. The chances of it breaking randomly due to disparate platforms (or even some systems) command line limits coupled with the possibility of leaking data via `ps` or other process commands mean it probably would not be suitable for production environments.

Thanks for hacking on this though, and trying to come up with a workaround for the python CLI's horrible interactive support :)

**Comment by jeromew** [comment]
ok I understand. yes I guess all the params could be seen in `ps aux`your're right.

There must be another way via 

```
cat > tmp; python tmp; rm tmp;
```

but I haven't found how to not make it lock yet. don't have time to look at that now though.

**Pull request closed without merging**
