### PR TITLE
Misc typo fixes

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/inventory/data.py
lib/ansible/modules/identity/keycloak/keycloak_client.py
lib/ansible/parsing/dataloader.py
lib/ansible/playbook/task.py
lib/ansible/plugins/inventory/ini.py
lib/ansible/utils/encrypt.py

### CODE REVIEW

**Review by gundalow — CHANGES_REQUESTED** [review]
Has this been agreed?

**Comment by Akasurde** [comment]
@gundalow @bcoca I updated PR as per discussion. This PR is now just a minor typo fix. :)

**Review by bcoca — APPROVED** [review]

**Comment by Akasurde** [comment]
@gundalow Can you please review this ? Thanks.

**Review by gundalow — APPROVED** [review]

**Comment by Akasurde** [comment]
@gundalow Thanks for the merge. @bcoca Thanks for the review.

**Pull request merged**
