### PR TITLE
support starting and stopping ec2 instances

### PR DESCRIPTION
**Pull request by otakup0pe**
This seems to be working locally for me !

### CODE REVIEW

**Comment by mpdehaan** [comment]
A bit concerned by the amount of underlying code involved and whether some of this should be abstracted or go into common sources (/module_utils/*, etc)

In any case, in queue for more detailed review.

**Comment by otakup0pe** [comment]
To be honest I was thinking the same thing. I can clean it up so the retry/wait logic is abstracted away at least. It still seems very module-specific however so should probably keep it in the ec2 module for now.

**Comment by otakup0pe** [comment]
Let me know if this is kind of what you were thinking of in terms of refactoring.

**Comment by jctanner** [comment]
@otakup0pe i think the start/stop instance functions would be nice to have inside of module_utils/ec2.py because we have need of them in the other modules. ec2_ami specifically could benefit from this.

**Comment by jctanner** [comment]
Closing this since https://github.com/ansible/ansible/pull/5275 had no merge conflicts and passed initial testing.

**Pull request closed without merging**
