### PR TITLE
Fix vault vars with jinja quotes filter with an iter

### LINKED ISSUE #24425: Single Vault Encrypted value not decrypted in jinja2 pipeline
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vault

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY
A single vault encrypted value does not get decrypted in a jinja2 pipeline.

##### STEPS TO REPRODUCE

Don't worry the below vault data is just useless strings.

```yaml
---
- hosts: localhost
  gather_facts: false
  vars:
    the_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66653436353263336535316333313533666563386463623562396234313064643430323066626538
          3234393066313964393861613431313832306439383633340a653361636537303033313137613933
          33653333633139353736636332333237613761636430356665383839663164363739323337643333
          6466313434306462370a663539346162623836626165343830666536646631616165636438646639
          6134
  tasks:
    - command: 'echo {{ the_password|string|type_debug }}'
```

This outputs:

```
"stdout": "AnsibleVaultEncryptedUnicode"
```

This is a little bit of a contrived example, but what it shows, is that if you want to do something like:

```
- command: "some_command {{ the_password|quote }}"
```

You will end up with the `$ANSIBLE_VAULT;...` string instead of the decrypted value

##### EXPECTED RESULTS
```
```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY
Fix vault vars with jinja quotes filter with an iter

When jinja process a playbook containing something like

   "{{ some_var_that_was_embedded_vault | quote }}"

the ciphertext was being used instead of the plaintext. The reason
is that the 'quote' filter (on py2) calls pipes.quote(). pipes.quote()
iterates over the string instead of using its str()/unicode().

AnsibleVaultEncryptedUnicode was using the default __iter__ which
itererates over the ciphertext.

Fix is to add a __iter__ that iterates over the plaintext.
Also adds a .replace() method since quote and a few other
filters use it.

Add integration tests.

Fixes #24425

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/parsing/yaml/objects.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (vault_unicode_iter_jinja__24425 f6a591d9d7) last updated 2017/05/10 15:04:46 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by alikins** [comment]
This kind of points to other potential problems with the not-actually-a-string AnsibleVaultEncryptedUnicode (at least without wrapping/delegating all str methods to work on self.data). Could just return a regular str directly from the yaml constructors, but that assumes we have a working vault at that point and loses some flexibility on when/where decryption happens (and passes around the plaintext more). Given the complexity of when/where/how templating, that is likely easier even if less useful.

**Comment by sivel** [comment]
Ok, I did a little testing, and there are still a lot of filters (23 in my non complete testing) this doesn't work with.  All of the ones that are commented out in the following playbook, are still failing:

```
---
- hosts: localhost
  gather_facts: false
  vars:
    vaulted_valued: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66653436353263336535316333313533666563386463623562396234313064643430323066626538
          3234393066313964393861613431313832306439383633340a653361636537303033313137613933
          33653333633139353736636332333237613761636430356665383839663164363739323337643333
          6466313434306462370a663539346162623836626165343830666536646631616165636438646639
          6134
  tasks:
    - assert:
        that:
          - vaulted_valued == 'foo bar'
          - vaulted_valued|string == 'foo bar'
          - vaulted_valued|quote == "'foo bar'"
          # - vaulted_valued|capitalize == 'Foo bar'
          - vaulted_valued|center(width=9) == ' foo bar '
          - vaulted_valued|default('monkey') == 'foo bar'
          # - vaulted_valued|escape == 'foo bar'
          - vaulted_valued|forceescape == 'foo bar'
          - vaulted_valued|first == 'f'
          - "'%s'|format(vaulted_valued) == 'foo bar'"
          # - vaulted_valued|indent(indentfirst=True) == '    foo bar'
          # - vaulted_valued.split() == ['foo', 'bar']
          # - vaulted_valued.split()|first|int(base=36) == 20328
          - vaulted_valued|join('-') == 'f-o-o- -b-a-r'
          # - vaulted_valued|last == 'r'
          # - vaulted_valued|length == 7
          - vaulted_valued|list == ['f', 'o', 'o', ' ', 'b', 'a', 'r']
          # - vaulted_valued|lower == 'foo bar'
          - vaulted_valued|map('upper')|list == ['F', 'O', 'O', ' ', 'B', 'A', 'R']
          - vaulted_valued|pprint == "'foo bar'"
          - vaulted_valued|replace('foo', 'baz') == 'baz bar'
          # - vaulted_valued|reverse == 'rab oof'
          - vaulted_valued|safe == 'foo bar'
          - vaulted_valued|select('equalto', 'o')|list == ['o', 'o']
          - vaulted_valued|slice(2)|list == [['f', 'o', 'o', ' '], ['b', 'a', 'r']]
          - vaulted_valued|sort|list == [" ", "a", "b", "f", "o", "o", "r"]
          # - vaulted_valued|title == 'Foo Bar'
          # - vaulted_valued|tojson == '"foo bar"'
          # - vaulted_valued|trim == 'foo bar'
          # - vaulted_valued|truncate(4) == 'f...'
          # - vaulted_valued|upper == 'FOO BAR'
          # - vaulted_valued|urlencode == 'foo%20bar'
          # - vaulted_valued|urlize == 'foo bar'
          # - vaulted_valued|wordcount == 2
          # - vaulted_valued|wordwrap(4) == 'foo\nbar'
          - vaulted_valued is not callable
          - vaulted_valued is equalto('foo bar')
          - vaulted_valued is iterable
          - vaulted_valued is lower
          - vaulted_valued is not none
          - vaulted_valued is string
          - vaulted_valued is not upper

          - vaulted_valued|b64encode == 'Zm9vIGJhcg=='
          - vaulted_valued|to_uuid == '0271fe51-bb26-560f-b118-5d6513850860'
          # - vaulted_valued|to_json == '"foo bar"'
          - vaulted_valued|md5 == '327b6f07435811239bc47e1544353273'
          - vaulted_valued|sha1 == '3773dea65156909838fa6c22825cafe090ff8030'
          - vaulted_valued|hash == '3773dea65156909838fa6c22825cafe090ff8030'
          # - vaulted_valued|regex_replace('foo', 'baz') == 'baz bar'
          - vaulted_valued|regex_escape == 'foo\ bar'
          # - vaulted_valued|regex_search('foo') == 'foo'
          # - vaulted_valued|regex_findall('foo') == ['foo']
          # - vaulted_valued|random(seed='foo') == ' '
          - vaulted_valued|shuffle(seed='foo') == ["o", "f", "r", "b", "o", "a", " "]
          - vaulted_valued|comment == '#\n# foo bar\n#'
```

Adding the `__deepcopy__` method in, allows all of these tests to pass.  Although, I'm unsure of the downside of `__deepcopy__` here, as you obviously chose another direction for a reason.

**Comment by alikins** [comment]
@sivel Excellent, that sort of test was on my TODO for today.

I suspect anything uses string methods not wrapped in AnsibleVaultEncryptedUnicode will fail at the moment.

> Adding the __deepcopy__ method in, allows all of these tests to pass. Although, I'm unsure of the downside of __deepcopy__ here, as you obviously chose another direction for a reason.

I'm hoping to avoid converting into a unicode early so I can pass around the AnsibleVaultEncryptedUnicode and decrypt at the last moment. Part of the way some of the planned multiple vault/passwords/secrets support was going to make use of that, but I'm not sure it's workable anymore. 

May just go ahead and wrap/delegate all the string functions and see how that works. That's a lot of boilerplate though.

**Comment by alikins** [comment]
I don't think I like the approach in this patch, and the deeper I dig the less likely it seems to ever be able to get it 100%.

Exposing a complete str/unicode interface wrapping around the encrypted strings _almost_ works. But some stuff, like regexes, seem to cause problems. Not sure why (I suspect the builtin re C lib is poking directly at internals of the string_types). 

So I probably am doing to ditch the AnsibleVaultEncryptedUnicode object and just construct regular text objects from the yaml constructor  (more or less what the __deepcopy__ change ends up doing...) And maybe revisit when I hit the next wave of vault changes.

**Comment by alikins** [comment]
I have a wip pr at https://github.com/ansible/ansible/pull/24623  that does more or less what https://github.com/ansible/ansible/pull/24461#issuecomment-301192500 mentions.

**Comment by mattclay** [comment]
CI failure in integration tests. Here's one of the failures:

```
2017-05-16 10:18:18 TASK [test_vault_embedded : assert various string ops and jinja filters work on embedded vault variables] ***
2017-05-16 10:18:18 task path: /root/ansible/test/integration/targets/vault/roles/test_vault_embedded/tasks/main.yml:29
2017-05-16 10:18:18 fatal: [testhost]: FAILED! => {
2017-05-16 10:18:18     "failed": true, 
2017-05-16 10:18:18     "msg": "The conditional check 'vaulted_valued == 'foo bar'' failed. The error was: error while evaluating conditional (vaulted_valued == 'foo bar'): 'vaulted_valued' is undefined"
2017-05-16 10:18:18 }
```

**Pull request closed without merging**
