### PR TITLE
Removed danowar2k from Wiki and now removing myself from botmeta

### PR DESCRIPTION
**Pull request by danowar2k**
##### SUMMARY
Removed myself as a solaris maintainer (no time).

##### ISSUE TYPE
Other

##### COMPONENT NAME
BOTMETA

### CODE REVIEW

**Comment by danowar2k** [comment]
What can I do now?

**Comment by danowar2k** [comment]
Can somebody merge this PR, please? I want to stop receiving bot mails :-/

**Comment by danowar2k** [comment]
The PR is merged, but I still (!) receive mentions by the bot: 
https://github.com/ansible-collections/community.general/pull/554

What else do I have to do?

**Comment by mkrizek** [comment]
@danowar2k This change only affects ansible/ansible repository. You need to make the same change in the repo you are receiving notifications from: https://github.com/ansible-collections/community.general/blob/60c9642e6b802f821e2b553390d31ba425734ac6/.github/BOTMETA.yml#L1393

FWIW this is mentioned in the bot documentation at https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#how-to-disable-notifications.

Sorry for the confusion. Let me know if you need any further help.

**Pull request merged**
