### PR TITLE
'copy' write new line at end of file if 'content' passed without newline...

### LINKED ISSUE #7855: content argument of copy module doesn't add end of line character
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

Ubuntu 14.04
##### Summary:

When using content='blah' for a file, the file will have 'blah' with no end of line character, which is generally an invalid file.
##### Steps To Reproduce:

``` yaml
- name: Add world to /tmp/hello
  copy: dest=/tmp/hello content='world'
```
##### Expected Results:

/tmp/hello:

```
world<end-of-line>
```
##### Actual Results:

/tmp/hello:

```
world
```

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #7855. Checked it by using hacking/env-setup and creating a temporary file with ad-hoc ansible.

### CODE REVIEW

**Comment by landryb** [comment]
Can this get merged ? Fwiw, salt has the same code in https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L1309 , but also added a contents_newline option (defaulting to true) allowing to disable this behaviour.

**Comment by sivel** [comment]
If this accepted, the default needs to be to not add a newline, since that is how it currently functions and how many people are already using it.  The newline would only have to be added when explicitly specified.

**Comment by landryb** [comment]
Well.. posix states that a file should end by a newline. Salt defaults to add it. Most ppl aware of this issue add a trailing \n to their content on purpose, and the PR doesnt add an extra \n in that case. So i dont see what's the issue with being 1) posix-compliant by default 2) compliant/behaviour-similar to other tools......

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by adamchainz** [comment]
This file hasn't been removed from this repo, PR should be re-opened.

**Pull request closed without merging**
