### PR TITLE
softlayer inventory include group by tags

### PR DESCRIPTION
**Pull request by acraftydev**
Addition to Softlayer inventory pluign to create groups for any tags assigned to a server. Uses a mask in the softlayer call to include all necessary info in results.

### CODE REVIEW

**Comment by Blake-** [comment]
Been using this for a while, works perfect, super useful.

**Comment by jarrodconnolly** [comment]
This is a great change, tag groups are super important for using Ansible with SoftLayer.

**Comment by superphly** [comment]
Is this going to be merged?

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
@crafty78 Rebase needed to get tests to pass on Shippable.

**Comment by acraftydev** [comment]
Ok will rebase in next week

**Comment by acraftydev** [comment]
anything else needed all tests passed?

**Comment by mattclay** [comment]
@icebourg You were the [original contributor](https://github.com/ansible/ansible/pull/7555), any thoughts?

**Comment by icebourg** [comment]
It's been long enough since I wrote this (and since I last used the SoftLayer API) I'm not sure I have anything useful to add.

**Comment by mattclay** [comment]
@jarrodconnolly, @superphly: Have either of you tested this change?

**Comment by superphly** [comment]
@mattclay I'm off that project and not using Ansible in any current projects. :(

**Comment by Blake-** [comment]
I use the heck out of this change nearly every day. No issues. I've used it on 1.9.4 and 2.1.1

**Comment by mattclay** [comment]
Merged, since this is being used by multiple users without issues. Thanks for the feedback everyone!

**Comment by mattclay** [comment]
@crafty78 I just noticed that the email address you used for the commit isn't registered to your GitHub account. Can you add that email so the commit links back to your user?

**Comment by acraftydev** [comment]
done

**Pull request merged**
