### PR TITLE
[WIP] initial commit of win_disk_image

### PR DESCRIPTION
**Pull request by nitzmahone**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
win_disk_image

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Nice, now I am wondering if it might be possible to automate installing visual studio.

**Comment by nitzmahone** [comment]
That'd definitely be an acid test- I think you might have to use the new become stuff as well to get an interactive session, as IIRC the VS installer uses DPAPI internally, which won't work under the default WinRM batch session, but if you "become yourself", it probably will.

**Comment by nitzmahone** [comment]
FWIW: I got SQL Server and Exchange installing reliably using an early prototype of the become stuff...

**Comment by wildmichael** [comment]
Sorry to hijack this pull-request.
@nitzmahone Out of curiosity: Can you give me a sample of the tasks you used to install SQL Server? I'm kind of struggling here... Also, what do you mean when you refer to the "become stuff"?

**Pull request merged**
