### PR TITLE
Add ansible template lookup plugin

### PR DESCRIPTION
**Pull request by privateip**

### CODE REVIEW

**Comment by sivel** [comment]
I'm not a huge fan of the name, it feels like this could create a lot of confusion between the existing `template` lookup and this new lookup.

I also don't fully understand the intent here.  Couldn't the existing `template` lookup achieve the same outcome?

**Comment by privateip** [comment]
@sivel no worries on the name, happy to take any suggestions for something better

This is fundamentally different than template.  Template assumes that you are document driven and this implementation is data driven.  You can accomplish the same thing with templates by nesting `if..then...else` statements but at some point that becomes unmanageable.  

This looks to address that problem by taking the approach of only templating the line when the variable (fact) is present.  Essentially this is built to assist with building data (fact) driven network device configs but is generic enough that it could be implemented for other use cases which is why the more generic name as opposed to something network specific. 

At the end of the day, it basically is implementing an Ansible specific template language instead of relying on the Jinja2 language to build templates.

**Comment by sivel** [comment]
@privateip could you provide a sample template that might be used with this lookup?

Assuming we all  agree this should be a thing and work out the naming, we'll also need some tests for this.

**Comment by privateip** [comment]
@sivel https://github.com/privateip/ansible-template-example

* [playbook](https://github.com/privateip/ansible-template-example/blob/master/make.yaml)
* [vars](https://github.com/privateip/ansible-template-example/blob/master/host_vars/veos01.yaml)
* [template](https://github.com/privateip/ansible-template-example/blob/master/templates/eos/interfaces.yaml)
* [output](https://github.com/privateip/ansible-template-example/blob/master/output.txt)

As far as tests go, I know they need to be added yet.  I figured it would be quicker to get through the bike shedding process first

**Comment by sivel** [comment]
I'm honestly not sure how to respond yet. That may be one of the weirdest things I've seen.  Almost like a pseudo playbook that generates a network template.

I'm not sure right yet how to name it, but there are a lot of conflated/duplicated names within that I'd love to see changed.

It's almost like `ansible_play_style_declarative_network_template`

**Comment by sivel** [comment]
It's been a while since I've used it, and I can't remember the terms it uses off the top of my head, but could we borrow terminology from ciscoconfparse?

It's possible it uses the same names too.

**Comment by privateip** [comment]
The keyword usage/duplication was done on purpose to simplify the learning curve.  Happy to have a discussion around that point if you feel that goal is not accomplished.

ciscoconfparse  does something completely different and thus I do not believe that is a good reference / comparison.  The template language itself is *not* network specific although I readily admit that the first and most obvious use case is most likely networking, I would assert that there are many other use cases that this could be applied to.

**Comment by sivel** [comment]
I think in the end I'm just not a fan. I don't really see the need, personally.  jinja is our templating language for better or worse, and I just fundamentally don't like the idea of trying to roll our own.  In addition this is doing all this work inside and with jinja which extends the weird feeling I have towards this.

I think I'd be happier with this being jinja macros as opposed to this being a lookup.

Maybe we should evaluate ways to bundle and inject our own macros into jinja instead.

The more I type here, I'm definitely leaning towards being in favor of jinja macros.

**Comment by privateip** [comment]
I think you are missing the point.  Jinja cannot functionally accomplish what is needed to solve this use case.  I would much rather use Jinja as well but it just wasn't built to support the use case properly without fundamental changes.

I understand you don't like this approach and thats fine but it solves a real and valid use case.  We can discuss alternatives but jinja isn't it.

**Comment by maxamillion** [comment]
I'd like to propose making this a core community meeting item for discussion on how best to move forward to satisfy the use case. Ultimately I'm curious what the group's thoughts are on it and the consensus on preferred solution.

**Comment by cognifloyd** [comment]
I don't know if I like this. The best way I can describe my reaction: serious cognitive dissonance.
In the example template files:
- those aren't tasks, and they don't use the template module, and
- task block's aren't allowed to loop! so the function of these blocks is distinctly different from standard ansible blocks which allow for failure recovery in try-except fashion

So these template-directive-things need to use other terminology--suggesting similarity is one thing, but these directives make it look like they are supposed to be the same thing, but block != block and template != template, and argh. It needs something to signal "this is different! This is not a task!" It would need something distinct so that googling will turn up the correct docs page (assuming this gets in).

As far as bikeshedding goes, here's my tongue-in-cheek suggestion:
### `yamplate`

**Comment by privateip** [comment]
closing this PR and will revisit post 2.5 release

**Pull request closed without merging**
