### PR TITLE
nova_compute update for havana

### PR DESCRIPTION
**Pull request by vadimkuznetsov**
to allow boot not only from image, but from volume, 
volume created from image, volume snapshot as well.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Seeing this adds a lot of options that are often going to be unneeded for most cases, I'd prefer to see this add a new (short?) example rather than conflating the existing example with all of those extra parameters.

**Comment by vadimkuznetsov** [comment]
My changes are backward compatible, i.e old example will work without change.
I added ability to boot from volume. That required 4 new options: source_type, source_id, volume_size, delete_on_termination. image_id is an alias of source_id. (And in boot from image case source_id is image_id.) 
netids is plain list of net ids, imho looks better then nics - list of hashes, that one need to know how to write. 
availability_zone - default value will work in single zone (most (?)) case.
Total is 6 new options. Please clarify what options you feel are unneeded. Please keep in mind in my use case I do need to boot from volumes and have ability to partition nova deployment is nice to have.

**Comment by vadimkuznetsov** [comment]
I think I pushed wrong button and closed it. That was not my intention.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thank you very much!

**Pull request closed without merging**
