### PR TITLE
Add collection support with local for supported network platforms

### PR DESCRIPTION
**Pull request by ganeshrn**
Related PR https://github.com/ansible/ansible/pull/65876

##### SUMMARY

*  The legacy behaviour of network action plugins using persistent
   the framework is to override the connection=local with the actual connection type (network_cli/netconf/httpapi) based on the value of transport option in provider.
*  After the actual connection plugin is identified try to load it from
   `ansible.netcommon` collection, if it fails to load it from ansible
   core. This is done to work with Ansible 2.10 and also maintain backward compatibility for
   Ansible 2.9 version to ensure it works with network collections.
*  To support this need to pass collection_list value to the connection
   plugins. As in case of connection=local it loads `persistent`
   connection within action plugin which in turn invokes `network_cli`
   or `netconf` connection. Similarly `network_cli` connection plugin invokes
   `terminal` and `cliconf plugins and `netconf` connection plugin invokes `netconf`
   `plugins` based on value on `ansible_network_os`.
*  Add deprecation warning for connection=local support and
   provider support for applicable platforms

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

module_utils/network/eos/eos.py
module_utils/network/ios/ios.py
module_utils/network/iosxr/iosxr.py
module_utils/network/junos/junos.py
module_utils/network/nxos/nxos.py
module_utils/network/vyos/vyos.py
plugins/action/eos.py
plugins/action/ios.py
plugins/action/iosxr.py
plugins/action/junos.py
plugins/action/net_base.py
plugins/action/netconf.py
plugins/action/nxos.py
plugins/action/vyos.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ganeshrn** [comment]
Related to PR https://github.com/ansible/ansible/pull/65876. Handles for network platforms for which collection namespace is identified.

**Review by pabelanger — APPROVED** [review]
Thanks!

**Review by Qalthos — APPROVED** [review]

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
The ios / junos failures were a result of broken code being merged. I've revert it at https://github.com/ansible/ansible/pull/66328

**Comment by ganeshrn** [comment]
ios test case failed with error
```
Traceback (most recent call last):
  File "/tmp/ansible-test-ftox0v_c/ansible/utils/jsonrpc.py", line 46, in handle_request
    result = rpc_method(*args, **kwargs)
  File "/tmp/ansible-test-ftox0v_c/ansible/plugins/cliconf/__init__.py", line 343, in copy_file
    ssh = self._connection.paramiko_conn._connect_uncached()
  File "/home/zuul/venv/lib/python3.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 368, in _connect_uncached
    raise AnsibleConnectionFailure(msg)
ansible.errors.AnsibleConnectionFailure: [Errno None] Unable to connect to port 22 on 199.204.45.114
```
Looks like intermittent enviornment issue. Retriggering CI run.

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
```
   Traceback (most recent call last):
      File "/tmp/ansible-test-rczh0n1n/ansible/module_utils/connection.py", line 197, in send
        response = recv_data(sf)
      File "/tmp/ansible-test-rczh0n1n/ansible/module_utils/connection.py", line 76, in recv_data
        d = s.recv(header_len - len(data))
    ConnectionResetError: [Errno 104] Connection reset by peer
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/home/zuul/venv/bin/ansible-connection", line 342, in <module>
        main()
      File "/home/zuul/venv/bin/ansible-connection", line 305, in main
        conn.set_options(var_options=variables)
      File "/tmp/ansible-test-rczh0n1n/ansible/module_utils/connection.py", line 181, in __rpc__
        response = self._exec_jsonrpc(name, *args, **kwargs)
      File "/tmp/ansible-test-rczh0n1n/ansible/module_utils/connection.py", line 150, in _exec_jsonrpc
        out = self.send(data)
      File "/tmp/ansible-test-rczh0n1n/ansible/module_utils/connection.py", line 201, in send
        raise ConnectionError('unable to connect to socket', err=to_text(e, errors='surrogate_then_replace'), exception=traceback.format_exc())
    ansible.module_utils.connection.ConnectionError: unable to connect to socket
```
Looks like enviornment issue for junos failure.

**Comment by ganeshrn** [comment]
recheck

**Pull request merged**
