### PR TITLE
add new test 'contains' alias in

### PR DESCRIPTION
**Pull request by watanabeshuji**
##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /Users/shuji/Projects/pioneer/iotcld/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
New jinja2 filter 'contains'.

When aws module such as rds_subnet_group.
I want to subnet id list from subnet_facts.
And filter subnet from result by tag.Name list to **list**

For example:
```
vars:
  - name: Subnet Group
     subnets:
      - PrivateSubnetA
      - PrivateSubnetB
      - PrivateSubnetC
```
task
```
    - ec2_vpc_subnet_facts:
      register: _subnet_facts
    - rds_subnet_group:
        name: "{{ name }}"
        state: present
        subnets: "{{ _subnet_facts.subnets | selectattr('tags.Name', 'defined') | selectattr('tags.Name', 'contains', subnets) |  map(attribute='id') | list }}"
```

### CODE REVIEW

**Comment by bcoca** [comment]
why not just use `in`?

**Comment by watanabeshuji** [comment]
can I use `in` ?

```
 - ec2_vpc_subnet_facts:
      register: _subnet_facts
    - rds_subnet_group:
        name: "{{ name }}"
        state: present
        subnets: "{{ _subnet_facts.subnets | selectattr('tags.Name', 'defined') | selectattr('tags.Name', 'in', subnets) |  map(attribute='id') | list }}"
```

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named 'in'
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by bcoca** [comment]
`in` as a name, sorry for the confusion, `in` is already valid in conditionals, i would keep the names the same.

**Comment by watanabeshuji** [comment]
Please comment me if I have to do.

**Comment by calfonso** [comment]
@watanabeshuji please let us know if you're interested in making the suggested change and rebasing this so we can get it reviewed and merged. Thanks!

needs_info

**Pull request closed without merging**
