### PR TITLE
standarized role/plugin paths

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME

config
##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Comment by jctanner** [comment]
if tests pass, shipit

**Comment by thaumos** [comment]
if tests pass, shipit

**Comment by pcahyna** [comment]
I think that this is a step in the right direction, thanks. But note that it apparently will not solve the last issue mentioned in https://github.com/ansible/proposals/issues/61 : the standardized paths will be overriden by user settings such as `ANSIBLE_LIBRARY` and `ANSIBLE_ROLES_PATH` or a custom .cfg file. I think it would be preferable if the user-set path were prepended to the standard paths, instead of overriding them.

**Comment by bcoca** [comment]
@pcahyna that would remove the ability of the user to restrict their usage of Ansible to a specific subset.

**Comment by pcahyna** [comment]
One question: why is /usr/share/ansible/roles in front of /etc/ansible/roles ? I think that /etc/ansible/roles should have priority over /usr/share/ansible/roles so that one can override them with local modifications (which belong to /etc, not /usr/share ). Similar system exists for udev rules and systemd units. So I propose the complete default role path to be '~/.ansible/roles:/etc/ansible/roles:/usr/share/ansible/roles'.

**Pull request merged**
