### PR TITLE
adjust docker_image push logic so that push will occur if image exists locally

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Currently, the docker_image module will not attempt to push to the repository if the image exists locally, even if `push: yes`.  This change corrects that.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
docker_image module

##### ANSIBLE VERSION
Change tested on the following:
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### ADDITIONAL INFORMATION
The problem and change are simple, but it lead me into a question of philosophy that I wasn't able to develop a strong opinion on.

The problem is that in this form, the tag_image function will always report `changed` when pushing.  The reason for this is that it's not actually possibly to reliably determine if a change was made to the remote repository purely from the output of a docker push.

I am happy to provide example output, but AWS ECR is an example of a repository that will provide unreliable responses.  The issue, I believe, is that when pushing to ECR it will check the SHA of the image you're trying to send, and if it already has a copy, it will respond "layer already exists" and not require an upload, while in the background an API change is made to make the image available to you to pull.  I've verified that after deleting an image via the ECR API, I can no longer `docker pull` that image using my credentials.  Submitting that image with `docker push` will report no changes, but the image will once again be available to pull after that.

So my question is this: is it preferable to consistently return 'changed' because we cannot actually know with confidence if a change was made, or is it preferable to trust the docker client response and report 'changed' or 'OK' based entirely on the client's interpretation of events?

I can't really come up with an example scenario where either choice would cause problems, so I think it is a largely philosophical decision.  I think it's important to be consistent, but I do not know what the "Ansible" approach would be.  The `command` and `shell` modules always return `changed` because they can't know if a change was made on the remote, but that's not an entirely equal comparison, because with this usage we can at least usually know if a change was made—just not always.

I've chosen to submit a version that always returns `changed` not necessarily because I feel strongly about it, but because it was the easier change to make.  If it's preferable to set the `changed` status based on the client data, I'm happy to update the PR.

I also made an unrelated pep8 (E241) correction on line 433.

### CODE REVIEW

**Comment by ghost** [comment]
Am I correct in interpreting that test/sanity/pep8/legacy-files.txt is a list of files that are tested for pep8, but a lack of compliance does not cause checks to fail, and since I brought this file into compliance it should no longer be part of that exclusion?

**Comment by gundalow** [comment]
@Comradephate Files in `test/sanity/pep8/legacy-files.txt` do not pass pep8.

So, as you've made `lib/ansible/modules/cloud/docker/docker_image.py` complient please remove the `lib/ansible/modules/cloud/docker/docker_image.py` line from `test/sanity/pep8/legacy-files.txt`

then Shippable should go green.

**Comment by ghost** [comment]
Would it be possible to have someone take a look at this?

**Comment by gundalow** [comment]
As agreed in 2017-12-07 Core meeting, we've done bulk pep8 fixes across all modules in `devel`.

This was done in https://github.com/ansible/ansible/pull/33682 and https://github.com/ansible/ansible/pull/33690 which have been merged into `devel`. because of this you will need to rebase your PR. Thanks in advance.

**Comment by ghost** [comment]
Rebasing seems to be incredibly messy because of how long ago I made this pull request.

I also have no reason to believe it will actually be merged after I commit additional time to doing a rebase that would have been completely unnecessary if this had been reviewed in a timely fashion.

**Comment by MarkusTeufelberger** [comment]
It is only 2 lines, squashing and rebasing shouldn't be that hard...

**Pull request closed without merging**
