### PR TITLE
Fixes #24330 yum.parse_check_update regex

### LINKED ISSUE #24330: Yum doesn't see new packages with long name
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
`modules/packaging/os/yum.py`

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Jun 24 2015, 00:41:19) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### OS / ENVIRONMENT
CentOS7
```
$ rpm -qi ansible
Name        : ansible
Version     : 2.3.0.0
Release     : 1.el7
Architecture: noarch
Install Date: Tue 18 Apr 2017 02:21:15 AM PDT
Group       : Development/Libraries
Size        : 28579660
License     : GPLv3+
Signature   : RSA/SHA256, Wed 12 Apr 2017 03:12:54 PM PDT, Key ID 6a2faea2352c64e5
Source RPM  : ansible-2.3.0.0-1.el7.src.rpm
Build Date  : Wed 12 Apr 2017 02:06:18 PM PDT
Build Host  : buildhw-09.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://ansible.com
Summary     : SSH-based configuration management, deployment, and task execution system
Description :

Ansible is a radically simple model-driven configuration management,
multi-node deployment, and remote task execution system. Ansible works
over SSH and does not require any software or daemons to be installed
on remote nodes. Extension modules can be written in any language and
are transferred to managed machines automatically.
```

##### SUMMARY
When trying to get latest version of a package on target server, ansible doesn't report any new version, even though `yum check-update` does. The package name and repository name are long and I can see (when doing print debugging) ansible gets them broken into multiple lines. I can also see the regex that is supposed to fix this isn't working correctly and puts `'\x01'` in the output instead.

##### STEPS TO REPRODUCE
One way to reproduce is to setup new CentOS7, add repository with long name and update package with long name via ansible yum module.

Since this is troublesome (I have done this in our production, but I don't expect anyone to create the same environment to test this), it is possible to just try the regex in question, located in `modules/packaging/os/yum.py::parse_check_output()` function.

```
>>> re.sub('\n[^\w]\W+(.*)', ' \1', '\n  abc')
' \x01'
```

Obviously, there should be `r` literal like so.

```
>>> re.sub(r'\n[^\w]\W+(.*)', r' \1', '\n  abc')
' abc'
```

##### EXPECTED RESULTS
Multi-line output of `yum check-update` is properly parsed by the `parse_check_output()`  function.

##### ACTUAL RESULTS
The parsing function breaks the output and omits packages with long names.

Related issues: #20608, #20043

### PR DESCRIPTION
**Pull request by ghost**
Output of `yum check-update` can contain lines with long package names and long
repository label names, which will be broken into multiple lines, which need to
be sanitized. The solution to this has been fixed and refactored in 2.3 in form
of parse_check_update(), but it still contains subtle bug, which makes such
multi-lines invisible to later logic (such packages aren't included in
parse_check_update()) output. The problem is caused by using '\1' in re.sub(),
instead of proper r'\1', which literally puts unicode symbol \1 into resulting
output.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
`modules/packaging/os/yum.py`

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Jun 24 2015, 00:41:19) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

### CODE REVIEW

**Comment by ghost** [comment]
Fixes #24330

**Comment by jctanner** [comment]
This patch seems to fix the issue with an example package:

```
[root@localhost ~]# ls -al /opt/repo
total 12
drwxr-xr-x. 3 root root  174 May  5 19:40 .
drwxr-xr-x. 6 root root   87 May  5 19:52 ..
-rw-r--r--. 1 root root 1992 May  5 19:40 foobarbazbangwizwhackzipzamwhoknewitcouldbethislong-1.0-1.x86_64.rpm
-rw-r--r--. 1 root root 2082 May  5 19:40 foobarbazbangwizwhackzipzamwhoknewitcouldbethislong-1.1-1.x86_64.rpm
drwxr-xr-x. 2 root root 4096 May  5 19:40 repodata
```

**Comment by jctanner** [comment]
@alikins you wrote the current regex in e5113262. Could you review this please?

**Comment by alikins** [comment]
patch looks right to me, and I can reproduce with a unit test using a variation of 'foobarbazbangwizwhackzipzamwhoknewitcouldbethislong' mentioned above that the pr fixes.

**Comment by alikins** [comment]
also cherry-picked to stable-2.3 as ab399146b4d6c4368cba438e57e9b9d463e3f250

**Comment by ingvagabund** [comment]
@mkopta nice!!! fixing the issue on RHEL7 as well

**Pull request merged**
