### PR TITLE
fetch: handle missing remote file gracefully

### PR DESCRIPTION
**Pull request by davehatton**
allows fetch to ignore missing files

allows a playbook like ....

---
- hosts: kvm
  user:  ansible
  sudo:  True
  
  tasks:
  - name: mirror important config files ($item)
    action: fetch src=$item dest=/data/transit/configs
    with_items:
        - /etc/passwd
        - /etc/group
        - /etc/bob
        - /etc/sysctl.conf
        - /etc/centos-release

### CODE REVIEW

**Comment by mpdehaan** [comment]
So this introduces a new call to send a remote md5 command, which has additional overhead when the command will succeed most of the time.

Would it instead be possible to just check the return code coming back from the "slurp" module and handle it?   That would eliminate the extra SSH execution in the more common case.

**Comment by davehatton** [comment]
No, the remote md5 call has always been there.

It was changed around mid June to allow it to run different md5sum commands on different OS.

The problem is that we have no way of knowing if it has failed because the md5 command isn't installed on the target or if the file doesn't exist.

The previous versions didn't care - they just fell over with an IOerror.

All I have done is to :
- introduce a test -r to make sure we only run the md5 if the file exists
- return from the remote md5=0 if we have nothing else
- check if the local file exists and if not don't worry about the md5 differences
- remove errors traps from connection/ssh and connection/paramiko so as not to error if there is nothing to collect.

**Comment by mpdehaan** [comment]
Thanks very much for the explanation, I was reading the diff too fast last night.  

Ok, so the various md5 hijinks need to be split off into utils, and I think locally it's more obvious to just do the os.path.exists, so I'll take your patch and fiddle with it a bit.

General concept looks good I just need to make some stuff more repeatable for others and the md5 stuff is getting a bit long.

Thank you!

**Comment by mpdehaan** [comment]
fixed up on devel, take a look and see if I forgot everything.

I based this fairly heavily on your patch but fixed up some things so the code's a bit cleaner. Something I have been meaning to do anyway as we will need the remote_md5 thing when we optimize the copy module (very soon, hopefuly!) to be smart about when to not transfer things.

Thanks again!

**Comment by davehatton** [comment]
thanks that looks great and much cleaner than my hack. Every day I learn a little more about python.

Some suggestions/questions?
1. I see ./librarysetup does a similar os.popen but has an additional OS level command "digest - a md5", so maybe this should be included?

lib/ansible/utils.py

cmd = "/usr/bin/md5sum %(file)s 2>/dev/null || /sbin/md5 -q %(file)s 2>/dev/null || /usr/bin/digest -a md5 -v %(file)s 2>/dev/null" % {"file": file})
1. much the same in _remote_md5 in lib/ansible/runner/__init__.py
        md5s = [
           "(%s && /usr/bin/md5sum %s 2>/dev/null)" % (test,path),
           "(%s && /sbin/md5sum -q %s 2>/dev/null)" % (test,path),
            "(%s && /usr/bin/digest -a md5 -v %s 2>/dev/null)" % (test,path)
       ]
2. ./library/copy should be altered to use then new local_md5 from lib/ansible/utils.py
3. maybe the  new local_md5 from lib/ansible/utils.py could now be altered to you the more python hashlib.md5 (or md5 for 2.4) that we discussed before?

eg (something like)

try:
    import hashlib
    HAVE_HASHLIB=True
except ImportError:
    import md5
    HAVE_HASHLIB=False

and

def md5_sum(f):
    # md5sum = os.popen("/usr/bin/md5sum %(file)s 2>/dev/null || /sbin/md5 -q %(file)s 2>/dev/null || /usr/bin/digest -a md5 -v %(file)s 2>/dev/null" % {"file": f}).read().split()[0]
    md5sum=None
    if os.path.exists(f):
        if HAVE_HASHLIB:
            md5sum=hashlib.md5(file(f).read()).hexdigest()
        else:
            md5sum=md5.new(file(f).read()).hexdigest()
    else:
        exit_kv(rc=1, failed=1, msg="file %s does not exist" % (f))

```
return md5sum
```

although that probably needs to change a little.

If you think the above is right - I'd be happy to do the patching and put a pull request if you want.

Dave

**Comment by mpdehaan** [comment]
Sure that all sounds good, a few notes:

[a]

library/setup and library/copy cannot use the utils code because we don't want to require that ansible be installed on the remotes.

It should be made a function and copied in modules that need it, yes.  hash lib with a fallback to the python 2.4 way of doing
of it is fine, but it cannot only use hash lib

[b]

yes on digest being included in the list of md5 commands

[c]

the remote md5 function _cannot_ require python since Ansible supports basic operations on devices that don't have Python, so that still needs to play shell games (ahem), but the various python local calls in the modules are free to do that, sure.

**Pull request closed without merging**
