### PR TITLE
apt: don't markmanual if apt-mark is not installed

### LINKED ISSUE #40531: apt module does not work without apt-mark
##### SUMMARY
the `apt` module does not work without the `apt-mark` binary

The issue seems to have been introduced with #37751

I believe a simple, and correct, solution is to simply not mark the package as manually installed if the apt-mark binary is missing.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

apt

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /home/user/code/services-configs/ansiblejobs/nodes/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/code/services-configs/ansiblejobs/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/user/code/services-configs/ansiblejobs/venv/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 20:19:42) [GCC 6.2.1 20161215]
```

##### CONFIGURATION

DEFAULT_SCP_IF_SSH(/home/user/code/services-configs/ansiblejobs/nodes/ansible.cfg) = True
HOST_KEY_CHECKING(/home/user/code/services-configs/ansiblejobs/nodes/ansible.cfg) = False

##### OS / ENVIRONMENT

Running on: debian stretch
Managing: Based on yocto linux

##### STEPS TO REPRODUCE

I think any usage of the apt module will fail, reading the code.

```yaml
- name: Install env definition package
  apt:
    name: '{{ env_config_package }}'
    state: latest
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  environment:
    http_proxy: http://0.proxy.example.com:3128
    https_proxy: http://0.proxy.example.com:3128
  register: env_def_update
  become: yes
```

##### EXPECTED RESULTS

I expect the package to be installed, as it was in previous versions, and not try to use the `apt-mark` binary.

##### ACTUAL RESULTS

The install fails.

```
TASK [node-env : Install env definition package] *************************************************************************************************************************************
task path: /home/user/code/services-configs/ansiblejobs/nodes/roles/node-env/tasks/main.yml:1
Using module file /home/user/code/services-configs/ansiblejobs/venv/local/lib/python2.7/site-packages/ansible/modules/packaging/os/apt.py
<10.0.2.52> ESTABLISH SSH CONNECTION FOR USER: user
<10.0.2.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/b8ff1eea37 10.0.2.52 '/bin/sh -c '"'"'echo ~user && sleep 0'"'"''
<10.0.2.52> (0, '/home/user\n', 'OpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l  25 May 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug3: /home/user/.ssh/config line 6: Including file /home/user/.ssh/config.local depth 0\r\ndebug1: Reading configuration data /home/user/.ssh/config.local\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26009\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.0.2.52> ESTABLISH SSH CONNECTION FOR USER: user
<10.0.2.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/b8ff1eea37 10.0.2.52 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492 `" && echo ansible-tmp-1526995575.81-84330305786492="` echo /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492 `" ) && sleep 0'"'"''
<10.0.2.52> (0, 'ansible-tmp-1526995575.81-84330305786492=/home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492\n', 'OpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l  25 May 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug3: /home/user/.ssh/config line 6: Including file /home/user/.ssh/config.local depth 0\r\ndebug1: Reading configuration data /home/user/.ssh/config.local\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26009\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.0.2.52> PUT /home/user/.ansible/tmp/ansible-local-259964dFg60/tmpRM8LnL TO /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492/apt.py
<10.0.2.52> SSH: EXEC scp -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/b8ff1eea37 /home/user/.ansible/tmp/ansible-local-259964dFg60/tmpRM8LnL '[10.0.2.52]:/home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492/apt.py'
<10.0.2.52> (0, '', 'Executing: program /usr/bin/ssh host 10.0.2.52, user (unspecified), command scp -v -t /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492/apt.py\nOpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l  25 May 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug3: /home/user/.ssh/config line 6: Including file /home/user/.ssh/config.local depth 0\r\ndebug1: Reading configuration data /home/user/.ssh/config.local\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26009\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nSending file modes: C0600 95200 tmpRM8LnL\nSink: C0600 95200 tmpRM8LnL\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.0.2.52> ESTABLISH SSH CONNECTION FOR USER: user
<10.0.2.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/b8ff1eea37 10.0.2.52 '/bin/sh -c '"'"'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492/ /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492/apt.py && sleep 0'"'"''
<10.0.2.52> (0, '', 'OpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l  25 May 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug3: /home/user/.ssh/config line 6: Including file /home/user/.ssh/config.local depth 0\r\ndebug1: Reading configuration data /home/user/.ssh/config.local\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26009\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.0.2.52> ESTABLISH SSH CONNECTION FOR USER: user
<10.0.2.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/b8ff1eea37 -tt 10.0.2.52 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gnkptdtucqfrjwiebzsuiatrsgvgapis; https_proxy=http://0.proxy.example.com:3128 http_proxy=http://0.proxy.example.com:3128 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492/apt.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<10.0.2.52> (1, '\r\n\r\n{"msg": "Failed to find required executable apt-mark in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "failed": true, "invocation": {"module_args": {"dpkg_options": "force-confdef,force-confold", "autoremove": false, "force": true, "force_apt_get": false, "install_recommends": null, "package": ["ibeta-config"], "autoclean": false, "name": "ibeta-config", "purge": false, "allow_unauthenticated": false, "state": "latest", "upgrade": null, "update_cache": true, "default_release": null, "only_upgrade": false, "deb": null, "cache_valid_time": 3600}}}\r\n', 'OpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l  25 May 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug3: /home/user/.ssh/config line 6: Including file /home/user/.ssh/config.local depth 0\r\ndebug1: Reading configuration data /home/user/.ssh/config.local\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26009\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 10.0.2.52 closed.\r\n')
<10.0.2.52> ESTABLISH SSH CONNECTION FOR USER: user
<10.0.2.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/b8ff1eea37 10.0.2.52 '/bin/sh -c '"'"'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1526995575.81-84330305786492/ > /dev/null 2>&1 && sleep 0'"'"''
<10.0.2.52> (0, '', 'OpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l  25 May 2017\r\ndebug1: Reading configuration data /home/user/.ssh/config\r\ndebug3: /home/user/.ssh/config line 6: Including file /home/user/.ssh/config.local depth 0\r\ndebug1: Reading configuration data /home/user/.ssh/config.local\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26009\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
fatal: [10.0.2.52]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoclean": false, 
            "autoremove": false, 
            "cache_valid_time": 3600, 
            "deb": null, 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": true, 
            "force_apt_get": false, 
            "install_recommends": null, 
            "name": "ibeta-config", 
            "only_upgrade": false, 
            "package": [
                "ibeta-config"
            ], 
            "purge": false, 
            "state": "latest", 
            "update_cache": true, 
            "upgrade": null
        }
    }, 
    "msg": "Failed to find required executable apt-mark in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}
```

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/40531

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

apt

##### ANSIBLE VERSION

```
2.5.3
devel
```

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @ecksun

**Comment by resmo** [comment]
Fix looks good to me, probably worth considering to print a warning to the user, that "apt-mark was not found, skipping package marking"

**Comment by mkrizek** [comment]
@resmo good point, fixed :+1:

**Review by resmo — APPROVED** [review]
shipit

**Comment by ecksun** [comment]
LGTM :)

**Pull request merged**
