### PR TITLE
Use six lib to import urlparse properly.

### PR DESCRIPTION
**Pull request by Yannig**
Fix a part of python 3 tests (make tests-py3, see https://github.com/ansible/ansible/issues/13553 for more details).

### CODE REVIEW

**Comment by abadger** [comment]
We can't depend on six being present on the remote machine so we
unfortunately can't do things this way at this time.  Options for the
future are to bundle six in what we send to the remote machine (will need a
better method of constructing the modules for the remote machine, something
I'm working on for 2.1) or doing the try except for the alternate locations
ourselves.  The latter is acceptable now.

**Comment by Yannig** [comment]
Thanks @abadger. I just add a new try/except block to fix this problem.

**Comment by abadger** [comment]
Thanks @Yannig !

**Comment by abadger** [comment]
Merged to devel and stable-2.0.

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
