### PR TITLE
VMware: New module vmware_vcenter_statistics

### PR DESCRIPTION
**Pull request by ckotte**
##### SUMMARY
Configure vCenter server statistics.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
vmware_vcenter_statistics

##### ANSIBLE VERSION
```
2.8-devel
```

### CODE REVIEW

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@pdellaert @dericcrago @Im0 @tchernomax Could you please review this ?

**Review by Im0 — COMMENTED** [review]
LGTM (but I've not tested yet).  One question I had was,  does VCSIM support setting statistics?  If so, should there be a test for this too?

**Comment by ckotte** [comment]
I don't know if vcsim supports vcenter configuration, but I can try..

**Comment by gundalow** [comment]
@ckotte regarding
> I don't know if vcsim supports vcenter configuration, but I can try..

This PR is currently marked as `shipit`, does it need any further testing/review given the above discussion, if so can you please eddit the summary to be `[WIP] VMware: New module vmware_vcenter_statistics` (work in progress)

**Comment by ckotte** [comment]
> This PR is currently marked as `shipit`, does it need any further testing/review given the above discussion, if so can you please eddit the summary to be `[WIP] VMware: New module vmware_vcenter_statistics` (work in progress)

The module is ready. I just added unit tests

**Comment by gundalow** [comment]
Closing/reopening as I don't see a Shippable job

**Comment by Akasurde** [comment]
@ckotte Thanks for the contribution.

**Comment by ckotte** [comment]
Please stop changing my code without asking me...

**Comment by Akasurde** [comment]
Ok. I just updated minor spelling mistakes and pep8 changes. If you don't like this then I am extremely sorry. Thanks.

**Pull request merged**
