### PR TITLE
bigip changes as requested by bcoca and abadger:

### PR DESCRIPTION
**Pull request by abadger**
- Fix to error if validate_cert is True and python doesn't support it.
- Only globally disable certificate checking if really needed.  Use
  bigip verify parameter if available instead.
- Remove public disable certificate function to make it less likely
  people will attempt to reuse that

### CODE REVIEW

**Comment by bcoca** [comment]
supersedes #13662

**Comment by abadger** [comment]
Labelled P1 only so this stays on the radar until we decide whether it needs to go to 2.0.0 or can wait until a later release.

**Comment by caphrim007** [comment]
@abadger I can verify that this patch similarly suppresses the errors I had mentioned in #13662 so +1 from me.

**Comment by abadger** [comment]
Pushed to devel and stable-2.0

**Pull request merged**
