### PR TITLE
Update docs to include directories inside group_vars

### PR DESCRIPTION
**Pull request by hkariti**
Related ansible-project thread: https://groups.google.com/forum/#!topic/ansible-project/VgGIyBhFtZM

Thought I shouldn't just complain about lack of docs...

### CODE REVIEW

**Comment by jimi-c** [comment]
Could you add a note regarding when the directory feature was added? I'm not sure when it was, but we like to make sure those are noted, just in case. Thanks!

**Comment by hkariti** [comment]
Ok, some `git checkout`-ing, and apparently it works since 1.4.0. Added a
note at the end.

**Comment by mpdehaan** [comment]
Thanks...

note:  I may want to tweak wording a bit, so not merging this immediately.  Much appreciated!

**Comment by mpdehaan** [comment]
Merged, thank you.

Apologies on the delay on this one, this will appear when we next rebuild and push docs, which should be soon.

Thanks again!

**Pull request merged**
