### PR TITLE
s3 overwrite and checksum support

### PR DESCRIPTION
**Pull request by magnusart**
Original issue: #2529

I implemented my suggestion above myself. Hope that's OK without doing a round on the mailing list. The commit message outlines what changes I have done. My first attempt at Python, so I kept my changes minimal.

I also noticed that other Ansible modules are written in a cleaner style, with several methods instead of one big monolithic main method with if statements. 

However, I did not tidy up the code to adhere to that style with this pull request. I added some additional exit points in the code where I needed to alter the flow.

So what I have here is not very clean, but in order to be explicit with what I have changed I wanted to avoid refactoring and adding features in the same pull request. 

I'd be glad to give a hand and do refactoring at a later point, to more clearly separate logic and program flow.

@lwade as I understand you are the original author of the S3 module. Please have a look as well.

### CODE REVIEW

**Comment by lwade** [comment]
Looks good, thanks very much. @pas256 and I were only talking about this the other day and it was already on the to-do.  

I'd suggest removing the "checksum" parameter entirely, since we should be doing this by default to get real truth about the key.  It seems that if a user wants to override this, they should only need to specify the "overwrite" parameter to then force a particular behaviour.

Yeah, this reads like a script and so refactoring it in future would be good.

**Comment by magnusart** [comment]
I initially thought that the checksum parameter should be left out as well. But since AWS is using the etag differently for multipart uploads I could not guarantee overwrite in that case (S3 is not saving md5 in that case). That is why I kept it in.

But then again: I agree that the checksum parameter might just be adding more moving parts than what is really nessecary. I'll remove it and overwrite will just not work for multipart uploaded files instead.

**Comment by magnusart** [comment]
There, removed checksum. Moved a small amount of code around to hopefully make the program flow a bit clearer when using overwrite.

**Comment by lwade** [comment]
Great, looks good!

Another reason why the multipart stuff is redundant (or we don't need to care about it, at the moment) is that we're not using it in the module, boto has some different methods for initiating a multipart upload.

**Comment by magnusart** [comment]
I agree. As long as the file didn't get onto s3 by some other means that uses the multipart upload. This should cover the majority of cases and the limitation of overwrite in regards to multipart upload is documented.

**Comment by mpdehaan** [comment]
We do not allow branch merges in our history.  Please use "git pull --rebase" or "git rebase" rather than "git pull" or "git merge".

I see you are also doing this on a branch named "devel", and you really should look into creating a branch per topic such that you can work on multiple things independently and pull requests don't become intermingled.

**Comment by magnusart** [comment]
Actually the intention of that merge was so that I could create a branch and continue development. My intention was to do a rebase and then create the branch, obviously that didn't pan out the way I intended.

So I'll have to do a new fork of Ansible where I do things properly and add a new pull request from that repo. I don't know how I would change the history of this pull request otherwise.

So just to be sure I get it right: if I do the pull request from a branch I create in a new forked repo that contain the same changes to S3, that will be correct?

**Comment by magnusart** [comment]
New pull request at this localtion: https://github.com/ansible/ansible/pull/2554

**Pull request closed without merging**
