### PR TITLE
win_regedit: Clean up diff support

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Cleanup Pull Request

##### COMPONENT NAME

win_regedit

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Improve diff-support by using standard naming

I started to use the variable $diff_support for the boolean that takes
care of diff output support.

### CODE REVIEW

**Comment by dagwieers** [comment]
ready_for_review

**Comment by jborean93** [comment]
Forgive my ignorance but is diff support just a human readable output of what changed, is there any particular format we should follow.

**Comment by dagwieers** [comment]
Good question, it is not always clear what the format should be in, could be any of these:

- normal diff output (best for file content using `diff.before`/`diff.after`, e.g. win_template, win_lineinfile)
- faked diff output (we fake as if a file has been diffed using `diff.prepared`, e.g. win_regedit)
- rsync-alike output (used when lots of files have been processed, e.g. unarchive, shows whether content and/or metadata has been modified one line per file)
- yaml-diff output (often used for showing changes in metadata or other structured information, not very user-friendly)

First rule is to use the same output as the python-module.
Second rule is to use common sense, i.e. what would people expect to see :-)

**Comment by dagwieers** [comment]
ready_for_review

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
