### PR TITLE
added a module to manage Apache2 sites

### PR DESCRIPTION
**Pull request by berendt**
releated to issue #7151

### CODE REVIEW

**Comment by berendt** [comment]
@kiranos Can you please test if this module is working like expected?

**Comment by kiranos** [comment]
I will test this tomorrow morning and post here with test results.

**Comment by kiranos** [comment]
Just saw the changes and a2query is not a command available in debian repo, might it be this: "apache2ctl, it the binary available in debians repo.

:~# whereis a2query
a2query:
:~# apache2ctl -v
Server version: Apache/2.2.22 (Debian)
Server built: Jan 31 2014 18:55:37
~# apache2ctl -h
Usage: /usr/sbin/apache2 [-D name] [-d directory] [-f file]
[-C "directive"] [-c "directive"]
[-k start|restart|graceful|graceful-stop|stop]
[-v] [-V] [-h] [-l] [-L] [-t] [-T] [-S] [-X]
Options:
-D name : define a name for use in directives
-d directory : specify an alternate initial ServerRoot
-f file : specify an alternate ServerConfigFile
-C "directive" : process directive before reading config files
-c "directive" : process directive after reading config files
-e level : show startup errors of level (see LogLevel)
-E file : log startup errors to file
-v : show version number
-V : show compile settings
-h : list available command line options (this page)
-l : list compiled in modules
-L : list available configuration directives
-t -D DUMP_VHOSTS : show parsed settings (currently only vhost settings)
-S : a synonym for -t -D DUMP_VHOSTS
-t -D DUMP_MODULES : show all loaded modules
-M : a synonym for -t -D DUMP_MODULES
-t : run syntax check for config files
-T : start without DocumentRoot(s) check
-X : debug mode (only one worker, do not detach)
Action '-h' failed.
The Apache error log may have more information.

**Comment by berendt** [comment]
It's available on Ubuntu 14.04. I'll check for other ways to check for enabled/disabled sites.

```
# a2query 
Usage: /usr/sbin/a2query -q -m [MODULE] -s [SITE] -c [CONF] -a -v -M -d -h 
-q              suppress any output. Useful for invocation from scripts
-m [MODULE]     checks whether the module MODULE is enabled, lists all enabled
            modules if no argument was given
-s [SITE]       checks whether the site SITE is enabled, lists all sites if no
            argument was given
-c [CONF]       checks whether the configuration CONF is enabled, lists all
            configurations if no argument was given
-a              returns the current Apache 2 module magic version
-v              returns the current Apache 2 version
-M              returns the enabled Apache 2 MPM
-d              returns the Apache 2 module directory
-h              display this help
```

**Comment by berendt** [comment]
Using `apache2ctl -t -D DUMP_VHOSTS` should be possible.

```
# apache2ctl -t -D DUMP_VHOSTS
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.2.15. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   10.0.2.15 (/etc/apache2/sites-enabled/000-default.conf:1)
```

**Comment by kiranos** [comment]
great a2query seems to be for apache 2.4 and apache2ctl for apache 2.2 from what I can gather.

**Comment by kiranos** [comment]
an os independent way could be to parse output of a2ensite/a2dissite and from grepping the output decide if the change was made or not ( bash coder:P )

**Comment by berendt** [comment]
closing this pull request because I replaced it with a clean and working pull request at #7194

**Pull request closed without merging**
