### PR TITLE
zabbix_mediatype parameter renamed in Zabbix 4.4 and onwards #64604

### PR DESCRIPTION
**Pull request by atkhan007**
##### SUMMARY
zabbix_mediatype parameter is renamed in accordance with Zabbix API parameter renaming.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_mediatype.py

##### ADDITIONAL INFORMATION
Steps to produce:
"---

name: Create Testing mediatype
zabbix_mediatype:
name: "Test script"
server_url: "https://localhost/zabbix/"
login_user: "Admin"
login_password: "zabbix"
type: 'script'
script_name: 'test_script.sh'
validate_certs: no
state: present
"

Before:
```
TASK [zabbix_server : Create Testing mediatype] ***************************************************************************
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_********_mediatype_payload_EI1rVw/ansible_********_mediatype_payload.zip/ansible/modules/monitoring/********/********_mediatype.py", line 487, in create_mediatype                                                               
  File "/usr/local/lib/python2.7/dist-packages/********_api.py", line 341, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/local/lib/python2.7/dist-packages/********_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/local/lib/python2.7/dist-packages/********_api.py", line 348, in do_request
    return self.parent.do_request(req)
  File "/usr/local/lib/python2.7/dist-packages/********_api.py", line 299, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])

fatal: [zabbix-server]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attempt_interval": 10, 
            "gsm_modem": null, 
            "http_login_password": null, 
            "http_login_user": null, 
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "login_user": "Admin", 
            "max_attempts": 3, 
            "max_sessions": 1, 
            "message_text_limit": null, 
            "name": "Test script", 
            "password": null, 
            "script_name": "test_script.sh", 
            "script_params": null, 
            "server_url": "https://localhost/********/", 
            "smtp_authentication": false, 
            "smtp_email": null, 
            "smtp_helo": "localhost", 
            "smtp_security": null, 
            "smtp_server": "localhost", 
            "smtp_server_port": 25, 
            "smtp_verify_host": false, 
            "smtp_verify_peer": false, 
            "state": "present", 
            "status": "enabled", 
            "timeout": 10, 
            "type": "script", 
            "username": null, 
            "validate_certs": false
        }
    }, 
    "msg": "Failed to create mediatype 'Test script': (u'Error -32602: Invalid params., Media type is missing parameters: name while sending {\"params\": {\"status\": \"0\", \"description\": \"Test script\", \"attempt_interval\": \"10\", \"exec_path\": \"test_script.sh\", \"maxattempts\": \"3\", \"maxsessions\": \"1\", \"exec_params\": \"\", \"type\": \"1\"}, \"jsonrpc\": \"2.0\", \"method\": \"mediatype.create\", \"auth\": \"c1e1525971dcddf5a53f74f4303d8da5\", \"id\": 2}', -32602)"     
}
```

After:
```
TASK [zabbix_server : Create Testing mediatype] ***************************************************************************
changed: [zabbix-server] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "attempt_interval": 10, 
            "gsm_modem": null, 
            "http_login_password": null, 
            "http_login_user": null, 
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "login_user": "Admin", 
            "max_attempts": 3, 
            "max_sessions": 1, 
            "message_text_limit": null, 
            "name": "Test script", 
            "password": null, 
            "script_name": "test_script.sh", 
            "script_params": null, 
            "server_url": "https://localhost/********/", 
            "smtp_authentication": false, 
            "smtp_email": null, 
            "smtp_helo": "localhost", 
            "smtp_security": null, 
            "smtp_server": "localhost", 
            "smtp_server_port": 25, 
            "smtp_verify_host": false, 
            "smtp_verify_peer": false, 
            "state": "present", 
            "status": "enabled", 
            "timeout": 10, 
            "type": "script", 
            "username": null, 
            "validate_certs": false
        }
    }, 
    "msg": "Mediatype created: Test script, ID: None"
}
```

### CODE REVIEW

**Review by D3DeFi — CHANGES_REQUESTED** [review]
Thanks for the contribution @atkhan007 . 

Based on the [documentation ](https://www.zabbix.com/documentation/3.0/manual/api/reference/mediatype/object) for older Zabbix versions. This patch would break module compatibility with older zabbix server installations. Although not explicitly written, I always try to support releases that are [currently supported](https://www.zabbix.com/life_cycle_and_release_policy). @sky-joker can you please confirm this?

I believe this patch would require adding logic similar to [something like this in zabbix_template module](https://github.com/ansible/ansible/blob/abf33196668f27503065115d84932d2807bce253/lib/ansible/modules/monitoring/zabbix/zabbix_template.py#L481). I understand that the provided example refers to very outdated zabbix version and could be removed, but it shows what I mean.

Edit: my bad, I thought that @sky-joker is module author, when it actualy is @rubentsirunyan . But feel free to state your opinion @sky-joker :)

**Comment by sky-joker** [comment]
I think module should be supported for the same period as Zabbix support period :)
So, please use `LooseVersion` to add condition handling of 4.2 or below and 4.4 higher.

**Comment by D3DeFi** [comment]
Hey @atkhan007 , will you be able to implement suggested changes?

Also, please edit description of this PR to contain - "Fixes #64604"

**Comment by D3DeFi** [comment]
Unfortunately, your contribution can no longer be merged to [ansible/ansible](https://github.com/ansible/ansible). The way how community content is being shipped within Ansible is [changing](https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#collections) as of right now with the preparations for Ansible 2.10. 

All development regarding Zabbix content has been moved to a separate [ansible-collections/community.zabbix](https://github.com/ansible-collections/community.zabbix) repository. Please resubmit your PR against the new repository with the changes we have requested in the previous comments and reviews (if any).

This separation now allows us to address your contribution much quicker than before. We are giving each contributor a few weeks (roughly a month) notice to move his/hers PRs to a new repository.

After a month, we will try to migrate all leftover PRs by ourselves, but author information may get lost in this way.

Sorry for the inconvenience and thank you for the understanding.

close_me

**Pull request closed without merging**
