### PR TITLE
ansilbe-doc list collections plugins

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
Add support for listing plugins in collections to ansible-doc

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ansible-doc

### CODE REVIEW

**Comment by geerlingguy** [comment]
Is it possible to skip listing collections? https://docs.ansible.com/ansible/latest/cli/ansible-doc.html would need to be updated if that's an option — it seems like it would be useful.

**Comment by bcoca** [comment]
I've been thinking if they should list by default or require a --collections switch, also fine with --builtin-only kind of switch

**Comment by geerlingguy** [comment]
It feels like it would be nice to just list everything by default, but be able to do `--builtin-only`.

**Comment by bcoca** [comment]
how about `-C <collection name> ` with `ansible.builtin` being a 'magic option'?

**Comment by mattclay** [comment]
@bcoca This PR caused https://github.com/ansible/ansible/issues/68530 and has been reverted. It will need to be reworked a bit to avoid the issue. It passed CI because there are no tests to cover that scenario yet.

**Pull request merged**
