### PR TITLE
spelling fixes (comments only)

### PR DESCRIPTION
**Pull request by ka7**
##### SUMMARY

patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

* lots of components :)

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
@ka7 Thanks for this (and the way you've split up the PRs based on risk). If you could please rebase this I'll merge it.

**Comment by Akasurde** [comment]
@ka7 Can you please rebase ? LGTM once this is rebased.

**Comment by Akasurde** [comment]
@ka7 Are you working on this ? If not I can take over this work.

**Comment by ka7** [comment]
Hi, feel free to take it. I has some issues with rebase...
( by the nature of the patch (spelling fixes) it's also ok if some get 
lost. it's anway just based on a limited dictionary )

**Comment by Akasurde** [comment]
@gundalow We can close this request as other PR is merged.
@ka7 Thanks for your PR.

**Pull request closed without merging**
