### PR TITLE
Add postgresql_db and postgresql_user module.

### PR DESCRIPTION
**Pull request by lorin**
Initial implementation of PostgreSQL modules for creating databases and adding users.

These implementations are based on the existing mysql_db and mysql_user modules.

Currently, the postgresql_user module can only grant all permissions on a database, fine-grained access has not been implemented yet.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good.

Before I merge this, can you include an example of how this is used, kind of like https://github.com/ansible/ansible/blob/devel/examples/playbooks/mysql.yml ?

Also if you want to send me a patch to the rst/modules file that would also be great.   

Thanks!

**Comment by mpdehaan** [comment]
merged, an examples/playbooks example would be great though if you can add them

Thanks!

**Comment by lorin** [comment]
Will do.

**Comment by mpdehaan** [comment]
I also shot an email to the list about seeing if we could make the MySQL versions and the PostgreSQL versions take the same arguments, which will also help with password filtering.  Check it out and let me know know what you think.

Then I promise I will stop requesting stuff :)   Thanks!

**Comment by lorin** [comment]
Playbook example added in https://github.com/ansible/ansible/pull/712

**Comment by lorin** [comment]
Module docs added in https://github.com/ansible/ansible.github.com/pull/154

**Pull request merged**
