### PR TITLE
make fact gathering obey play tags

### LINKED ISSUE #44251: Fact gathering is NOT ignored when play level tags don't match
##### SUMMARY

Fact gathering is NOT ignored when play level tags don't match.
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.6.2
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core)
##### STEPS TO REPRODUCE

site.yml:

```yaml
- hosts: dpc
  roles:
  - role: dpc
    become: True
  tags:
    - dpc
```
run:
ansible-playbook site.yml -i hosts --tags=abc

##### EXPECTED RESULTS

Expected was that "Gathering Facts" will be ignored.
##### ACTUAL RESULTS

```
PLAY [dpc] **************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
ok: [10.124.131.128]

PLAY RECAP **************************************************************************************************************************************************************************
10.124.131.128             : ok=1    changed=0    unreachable=0    failed=0   

```

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
fixes #44251, #21528

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

gathering
##### ANSIBLE VERSION

```
2.x
```

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by maxamillion** [comment]
shipit

**Comment by felixfontein** [comment]
@bcoca @maxamillion this breaks facts gathering for playbooks which use tags, but don't have global tags:
```.yaml
- hosts: localhost
  tasks:
  - debug: msg="test"
    tags:
    - test
```
Behavior with ansible so far (`ansible-playbook test.yml -t test`):
```
PLAY [localhost] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [debug] *************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test"
}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0   
```
Behavior with this PR:
```
PLAY [localhost] *********************************************************************************************************************************

TASK [debug] *************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test"
}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0   
```

**Comment by felixfontein** [comment]
From discussion in IRC: changing test to
```.py
        # Unless play is specifically tagged, gathering should 'always' run
        if not self._play.tags:
            setup_task.tags = ['always']
```
works for me (i.e. this test).

**Comment by felixfontein** [comment]
Will be fixed in #48294.

**Pull request merged**
