### PR TITLE
file - change warning to error when 'src' is given without 'state'

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

This has been a warning and is now an error in 2.10.
Added integration tests.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

`lib/ansible/modules/files/file.py`

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
In general LGTM
maybe better to use module.fail_json in this case instead of raising ParameterError (because it is just use ```print``` in the AnsibleModuleError class) ? I'd remove it at all, it's used in this method only and adds several extra classes for that making the code more complicated... (maybe i'm wrong but it looks unnecessary)

**Review by Andersson007 — APPROVED** [review]
anyway (i recalled that case with ```lineinfile```:)
shipit

**Review by mkrizek — APPROVED** [review]

**Comment by samdoran** [comment]
@Andersson007 I thought the same thing but I don't fully understand the reason behind using `ParameterError` in this module. I need to ask @abadger for the reasoning.

**Comment by Andersson007** [comment]
@samdoran yes, to ask is definitely a good idea

**Pull request merged**
