### PR TITLE
Unarchive typos

### PR DESCRIPTION
**Pull request by jpmens**
Fixed a few typos in module documentation

### CODE REVIEW

**Comment by jpmens** [comment]
HUH? Where did all those commits come from?!

**Comment by bcoca** [comment]
I think you were playing with my facts cache experiment

Brian Coca

**Comment by jpmens** [comment]
> I think you were playing with my facts cache experiment

I wasn't; I did my usual cycle of

```
    pull --rebase
    checkout -b
    vi
    add
    commit
    push
```

Tried it twice!

**Comment by bcoca** [comment]
This has happened to me a couple of times, I think it is a github gremlin
messing with us.

**Pull request closed without merging**
