### PR TITLE
fix: show access policies correctly

### LINKED ISSUE #68167: azure_rm_keyvault_info not show storage field for access policies
##### SUMMARY
The module azure_rm_keyvault_info not show storage field for access policies
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvault_info

##### ANSIBLE VERSION

```
ansible 2.9.6

```

##### CONFIGURATION

```
None
```

##### OS / ENVIRONMENT

ansible 2.9.6
python version = 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) [Clang 6.0 (clang-600.0.57)]
macOs Catalina 10.15.1 (19B88)

##### STEPS TO REPRODUCE

1.  Get info with the azure_rm_keyvault_info module of  a keyvault  which has a storage access policy.

```yaml
    - name: Get Key Vault by name
      azure_rm_keyvault_info:
        resource_group: "{{ rg }}"
        name: "{{ kv_name }}"
      register: _kv_info

    - name:  Show keyvault info
      debug:
        msg: "{{ _kv_info }}"
```
##### EXPECTED RESULTS
```yaml
    - access_policies:
      - object_id: xxxx
        permissions:
          certificates:
          - get
          - list
          keys:
          - encrypt
          secrets:
          - get
          storage:
          - get
          - list
```

##### ACTUAL RESULTS

```yaml
    - access_policies:
      - object_id: xxxx
        permissions:
          certificates:
          - get
          - list
          keys:
          - encrypt
          secrets:
          - get
```

### PR DESCRIPTION
**Pull request by Eugen1987**
##### SUMMARY
Return storage field for access policies

Fixes #68167

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_keyvault_info

### CODE REVIEW

**Review by gavinfish — APPROVED** [review]
shipit

**Comment by Fred-sun** [comment]
@Eugen1987 Thank you for taking the time to contribute to this PR. We will ansible 's azure module related Issue and PR is transferred to azure collection (https://github.com/ansible-collections/azure/pulls), you can transfer the Issue to azure collection repo?

**Comment by Eugen1987** [comment]
> @Eugen1987 Thank you for taking the time to contribute to this PR. We will ansible 's azure module related Issue and PR is transferred to azure collection (https://github.com/ansible-collections/azure/pulls), you can transfer the Issue to azure collection repo?

oks

**Comment by Fred-sun** [comment]
> @Eugen1987 Thank you for taking the time to contribute to this PR. We will ansible 's azure module related Issue and PR is transferred to azure collection (https://github.com/ansible-collections/azure/pulls), you can transfer the Issue to azure collection repo?
> 
> oks

Thanks for your update! Associate with [#62](https://github.com/ansible-collections/azure/pull/62)

**Pull request closed without merging**
