### PR TITLE
Explicitly mention the Linux requirement for the Ansible machine, remove...

### PR DESCRIPTION
**Pull request by tgerla**
...a vestigial heading.

### CODE REVIEW

**Comment by mpdehaan** [comment]
But you don't need Linux, you need something Unixey, right?

**Comment by mpdehaan** [comment]
cc @tgerla

**Comment by tgerla** [comment]
That's true. Maybe an explicit mention that you can't run it on Windows would be better?

**Comment by mpdehaan** [comment]
+1 to saying the control machine cannot be a Windows box.

(Windows managed nodes may obviously come later, but aren't a thing yet)

**Comment by bcoca** [comment]
I ran it successfully on windows (via cygwin) as a 'master'

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
yep, "not supported" doesn't mean "could be made to work" :)

merged in, thanks!

**Pull request merged**
