### PR TITLE
Win msi improvements

### PR DESCRIPTION
**Pull request by trondhindenes**
I basically rewrote the win_msi module. 
-This version actually checks the exit code of the install, and reports error if its anything other than zero (sucess)

-Added a few new parameters to make it easier to skip already installed software, using WMI/CIM classes rather than just a "check for existing file" like the previous version did.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thoughts @sivel ?

**Comment by sivel** [comment]
There are some spelling errors such as "exit_reasion" instead of "exit_reason".

Other than that, there are a number of places where using `Get-Attr` would shorten some code and allow for a safer way of accessing members of the custom psobject.

**Comment by mpdehaan** [comment]
Thoughts on updates @trondhindenes ?

**Comment by trondhindenes** [comment]
Sorry, been on vacation. I'll get these fixes in during the weekend.

**Comment by trondhindenes** [comment]
I have no idea what those other commits are doing here. Closing this.

**Pull request closed without merging**
