### PR TITLE
zabbix_host_facts: get list of templates

### PR DESCRIPTION
**Pull request by mindrb**
##### SUMMARY

Get list of templates among other items. It is useful because later one can edit this list using zabbix_host module.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

zabbix_host_facts
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gundalow** [comment]
bot_status

**Review by D3DeFi — APPROVED** [review]
Tested with all LTS releases of zabbix server, works fine :)

**Comment by D3DeFi** [comment]
shipit

**Comment by D3DeFi** [comment]
@RedWhiteMiko are you ok with these changes?

**Comment by RedWhiteMiko** [comment]
LGTM

**Comment by D3DeFi** [comment]
bot_status

**Comment by D3DeFi** [comment]
If I am not mistaken, labels `core_review` and `support:core` are blocking this PR from being merged. Probably related to linked PR about 'component wasn't properly found'. 

@mindrb can you please try to remove word 'module' present in `COMPONENT NAME` section in this PR's description and leave just 'zabbix_host_facts' there? When you are done, please close this PR and then reopen it to force ansibot to look once again :)

**Comment by mindrb** [comment]
@D3DeFi done

**Comment by D3DeFi** [comment]
-label core_review
+label community_review

**Comment by D3DeFi** [comment]
since this PR got your attention, can I ask for your help @gundalow? Is there any way to get it moving by ourselves or we simply just need a review from a core dev?

**Comment by resmo** [comment]
hi all, this should get merged by the bot without core members interaction. We are still investigating why it didnt and keep this open for analysis purposes. But assume this to be merged. Thanks.

**Comment by resmo** [comment]
bot_status

**Comment by resmo** [comment]
bot_status

**Comment by resmo** [comment]
looks much better know, but I still wonder why core_review labeled. however, 

rebuild_merge

**Comment by D3DeFi** [comment]
thanks @resmo ! :)

**Pull request merged**
