### PR TITLE
CLI: ansible-doc shows lists of modules & module docs on command-line

### PR DESCRIPTION
**Pull request by jpmens**
## Show listing of all modules

ansible-doc -l

```
...
ohai                  Returns inventory data from _Ohai_
pause                 Pause playbook execution
ping                  Try to connect to host and return `pong` on success.
pip                   Manages Python library dependencies.
postgresql_db         Add or remove PostgreSQL databases from a remote host.
postgresql_user       Adds or removes a users (roles) from a PostgreSQL database.
raw                   Executes a low-down and dirty SSH command
script                Runs a local script on a remote node
seboolean             Toggles SELinux booleans.
selinux               Change policy and state of SELinux
service               Manage services.
setup                 Gathers facts about remote hosts
shell                 Execute commands in nodes.
slurp                 Slurps a file from remote nodes
subversion            Deploys a subversion repository.
supervisorctl         Manage the state of a program or group of programs running via ...
svr4pkg               Manage Solaris SVR4 packages
template              Templates a file out to a remote server.
user                  Manage user accounts
virt                  Manages virtual machines supported by libvirt
wait_for              Waits for a given port to become accessible on a server.
yum                   Manages packages with the _yum_ package manager
```
## Display manual of one module

ansible-doc -m yum

```
> YUM  (/Users/jpm/Auto/pubgit/ansible/ansible/library/yum)

    Will install, upgrade, remove, and list packages with the _yum_
    package manager.

   Options:
   o disablerepo
          _repoid_ of repositories to disable for the install/update
          operation These repos will not persist beyond the
          transaction Multiple repos separated with a ',' New in
          version 0.9.
   o enablerepo
          Repoid of repositories to enable for the install/update
          operation. These repos will not persist beyond the
          transaction multiple repos separated with a ',' New in
          version 0.9.
   o list
          various non-idempotent commands for usage with
          `/usr/bin/ansible` and _not_ playbooks. See examples.
   o name
          package name, or package specifier with version, like
          `name-1.0`.
   o state
          whether to install (`present`, `latest`), or remove
          (`absent`) a package. Choices : present,latest,absent.


    yum name=httpd state=latest
    yum name=httpd state=removed
    yum name=httpd enablerepo=testing state=installed
```
## for insertion into playbook

ansible-doc -s -m yum

``` yaml
- name: Manages packages with the _yum_ package manager
  action: yum
        disablerepo=            # _repoid_ of repositories to disable for the ...
        enablerepo=             # Repoid of repositories to enable for the ...
        list=                   # various non-idempotent commands for usage with ...
        name=                   # package name, or package specifier with version, ...
        state=                  # whether to install (`present`, `latest`), or ...
```

### CODE REVIEW

**Comment by jpmens** [comment]
Solves #1572

**Comment by jpmens** [comment]
Added dep to Makefile and setup.py (both untested)
Added ansible-doc.1.in man-page, but cannot build .1 
moved ansible-doc to bin/

**Comment by jpmens** [comment]
@tonk If you have a bit of time, you might want to test this. :-)

**Comment by tonk** [comment]
I did not check the man-page, but it looks OK.

The ansible-doc program works perfectly. No problems found.

But: Is it possible (and easy to do) to output Markdown? If it's a lot of work, please leave as is and merge with the current version.

Thanks JP.

**Comment by jpmens** [comment]
Github-flavored Markdown is already supported by the module-formatter (`hacking/module-formatter.py`).

**Comment by tonk** [comment]
Yep. It works now (had to run the env-setup script). Thanks.

**Comment by tonk** [comment]
Tested a little further and I love the '-s'. Give a nice snippet of how to use it. Nice.

**Comment by mpdehaan** [comment]
testing now...

**Comment by mpdehaan** [comment]
Ok, various problems, but I very much like the idea.   The most major one is I can't get it to give me documentation on modules in my module path at all, and I am not sure why.   It lists them but will not show docs.  Here are other things I found.

need to fix:

ansible-doc with no arguments gives no usage message.    I have to do ansible-doc --help

also need to fix:

if there are any junk files in the library directory, it gives errors like this:

Traceback (most recent call last):
  File "/home/mdehaan/ansible/lib/ansible/utils/module_docs.py", line 41, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/lib64/python2.6/ast.py", line 37, in parse
    return compile(expr, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 3
     @@ -44,6 +44,7 @@
      ^
 SyntaxError: invalid syntax

need to fix:

ansible-doc -s foo

does not give any message that foo does not exist, in fact, I can't retrieve any docs for even things like yum.   This may be related to general output just not working.

need to fix:

--v/version should be consistent with ansible, not -V

need to fix:

Ansible uses --module-path not --module-dir

need to fix:

building the documentation produces an invalidly formatted manpage for "man ansible-doc"

**Comment by mpdehaan** [comment]
I am also finding the ansible-doc source hard to read because it is doing so much with Jinja2.   I think it would be possible to not use jinja2 (maybe just the textwrap module) and then print things line by line, and that would make it TONS easier to read and understand the source code.

I don't think we need to use the templating hammer here.

**Comment by mpdehaan** [comment]
Also, stylistically, no naming variables after yourself :)

"mpdfunc" doesn't tell me what it does either :)

**Comment by mpdehaan** [comment]
This is minor, but another question is it has regex substitutions for things like:

`word'

With mixed backtick and single quotes.   This is probably trying to be helpful but I am confused as to why we are trying to match on the possible series of user typos.

It seems we should just match on we expect things to contain, and shouldn't that just be M(string) etc and not explicitly try to template any punctuation the user uses?   If I say 'foo' I would expect that to render literally also and not add markup around it.

**Comment by jpmens** [comment]
Copied from module_formatter

**Comment by mpdehaan** [comment]
Yeah, then module formatter should probably not do this either.

**Comment by mpdehaan** [comment]
(also, we should try to make sure any code doesn't need to be copied, but moves into utils or similar where we need it in more than one place)

**Comment by jpmens** [comment]
not matching on; rather outputting.

**Comment by mpdehaan** [comment]
Ok, so I don't understand.

Code for outputting RST style hrefs or something?

**Comment by jpmens** [comment]
No: the printout of the doc onto stdout, like:

```
$ ansible-doc -m yum

> YUM  (/Users/jpm/Auto/pubgit/ansible/ansible/library/yum)

    Will install, upgrade, remove, and list packages with the `yum'
    package manager.

   Options (= is mandatory):
    - disablerepo
          `repoid' of repositories to disable for the install/update
          operation These repos will not persist beyond the
          transaction Multiple repos separated with a ',' New in
          version 0.9.
[...]
```

**Comment by mpdehaan** [comment]
Yeah  I was talking about the src in that last bit...

-- Michael

**Pull request closed without merging**
