### PR TITLE
Katello: Added product to the dict choices

### PR DESCRIPTION
**Pull request by arsenicks**
Following issue 48594 where product is not a recognised choice: https://github.com/ansible/ansible/issues/48594

##### SUMMARY

After reading the code to find why product wasn't recognised I realised all the logic required was there, there was even example in the documentation but in a previous commit, someone added a list of valid choice for entity. They seems to have simply forgot to add "product" to the list

This fixes the [issue 48594](https://github.com/ansible/ansible/issues/48594)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

Katello

##### ADDITIONAL INFORMATION

Following the documentation here's an example where we create a product that should work.
```
   - name: Create EPEL product
     katello:
       username: admin
       password: XXXXXXXX
       server_url: https://mykatelloserver.com
       entity: product
       params:
         name: "EPEL - Extra Packages for Enterprise Linux"
         organization: "MyOrg"
```
Here's the result we get with the current code:
"msg": "value of entity must be one of: repository, manifest, repository_set, sync_plan, content_view, lifecycle_environment, activation_key, got: product"

After the suggested changes:
```
TASK [Create EPEL product] ****************************************************************************************************************************************************************************
changed: [localhost]


$ hammer product list --organization MyOrg
---|--------------------------------------------------|-------------|--------------|--------------|-----------
ID | NAME                                             | DESCRIPTION | ORGANIZATION | REPOSITORIES | SYNC STATE
---|--------------------------------------------------|-------------|--------------|--------------|-----------
11 | EPEL - Extra Packages for Enterprise Linux      |             | MyOrg        | 0            |


```

### CODE REVIEW

**Review by ehelms — APPROVED** [review]
Please note these are being deprecated. Please see https://github.com/ansible/ansible/pull/49776/files#diff-ae0a9398b6ad9c29539adf37e0fbaea5R18

There is a larger, more comprehensive and better tested set of modules being built within the community.

**Comment by gundalow** [comment]
@arsenicks given @ehelms comment above we will not accept new features for this module.

@ehelms Could you please link to the new modules

**Comment by gundalow** [comment]
https://github.com/theforeman/foreman-ansible-modules

**Comment by Akasurde** [comment]
For posterity - https://github.com/theforeman/foreman-ansible-modules

**Comment by arsenicks** [comment]
@gundalow Thanks for your input. I know the current module will be deprecated in 2.8 but I was trying to submit this PR to fix an issue in the 2.7 release. 

I might have misunderstood, I'm a new contributor, but I though I had to submit this in the devel first so it could get accepted and merged and then I could create another PR to backport to a previous stable branch.( https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process )

Maybe this PR wasn't correct. How can I suggest this change to 2.7 then ? It's not a feature, it's looks like a bug to me and I guess the new modules will never be merged in older release right ?

Thanks for your help!

**Comment by gundalow** [comment]
@arsenicks Ah, that makes sense, @ehelms are you happy for this fix to go into `devel` (Ansible 2.8) and be backported into Ansible 2.7?

**Review by ehelms — APPROVED** [review]

**Comment by gundalow** [comment]
@ehelms Thanks for the review
@arsenicks Could you please add a `changelog/fragment` for this bug, see https://docs.ansible.com/ansible/devel/community/development_process.html#making-your-pr-merge-worthy

Then I think we can get this merged

**Comment by arsenicks** [comment]
@gundalow Thanks for the followup, I just pushed the fragment file.

As I said this is my first contribution so I really want to do things correctly! Once the PR will be merged, I will have to follow [this](https://docs.ansible.com/ansible/devel/community/development_process.html#backporting-merged-prs) procedure right ?

Have a nice day!

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@arsenicks @ehelms Thank you for this.
Merged into `devel (2.8)
@arsenicks Yes, if you could follow https://docs.ansible.com/ansible/devel/community/development_process.html#backporting-merged-prs we can get this into the next 2.7 release (~3 weeks)

**Pull request merged**
