### PR TITLE
Improved netapp module utility for E-Series.

### PR DESCRIPTION
**Pull request by ndswartz**
##### SUMMARY
Add header option to request method in NetAppESeriesModule
Add multipart formdata builder function
Fix issue with url port change

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

netapp

##### ADDITIONAL INFORMATION

```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/swartzn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/swartzn/projects/ansible/ansible/lib/ansible
  executable location = /home/swartzn/projects/ansible/ansible/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

### CODE REVIEW

**Review by thedoubl3j — APPROVED** [review]
tests updated with the changes. lgtm.

**Comment by thedoubl3j** [comment]
@ndswartz is this a bugfix or a feature PR?

**Comment by ndswartz** [comment]
@thedoubl3j Sorry, this is a feature PR

**Comment by thedoubl3j** [comment]
@lonico @carchi8py as this is universal file used across both teams, could I get a review and shipit if all looks good?

**Review by carchi8py — APPROVED** [review]
The code looks good (looks like it just touched the e-series.

After 2.9 i'm going to look at breaking the shared files into multiple files.
Today we have
Ontap
E-series
ElementSW
Cloudvolume azure
cloudvolumes aws

all sharing the same file, when they probably should have there own so we don't step on each others toes.

**Comment by thedoubl3j** [comment]
sounds good @carchi8py thanks for taking a look.

**Pull request merged**
