### PR TITLE
New module 'set' to define local variables (in scope of play)

### PR DESCRIPTION
**Pull request by dagwieers**
This module allows you to set local variables in the scope of the play.

For this we have to make sure Runner() has access to play variables so we can inject these variables during the run of a play. Previously the play variables were static at the start of Runner() but now they can change during a play. I used the same mechanism as 'ansible_facts' so if a module returns 'ansible_vars' it sets local variables.

The module also accepts complex arguments.

``` yaml
 - action: set var1="something" var2="${password}"'
 - action: set
   args:
      var1: something
      var2: ${password}
```

There was some confusion before, but this would set a variable that is the _same_ for all hosts, just as 'vars:' and 'vars_files:' would set. Limited in use.

### CODE REVIEW

**Comment by srgvg** [comment]
+1 local & global

**Comment by mpdehaan** [comment]
I'm not comfortable with always updating self.play.vars here, it doesn't even seem to require the plugin.

I think what I'd like to see is something like ansible_facts that is called "ansible_globals" and playbook code knows what to do with them, and Runner should be completely unaware about the return data.

Thoughts?

**Comment by mpdehaan** [comment]
I also agree local/global makes more sense, but that the name of the other seems slightly reversed, and this should be the 'global' one (with implementation changes mentioned above so Runner doesn't have to change).

**Comment by dagwieers** [comment]
This is not global in the sense that the variables are specific to a play (and are not 'exported' outside of the play). So you basically define a variable (possibly conditionally) in the scope of this play.

If you compare it to functions, that would be the local scope. The global scope would mean for the complete playbook. The reason I have to modify play.vars is because that's what it was meant to be. A way to add local variables to the play.

**Comment by rektide** [comment]
The referenced 'global' module isn't available anywhere is it?
https://github.com/dagwieers/ansible/blob/77683458b6546774b7d0d771c5982d1b846cc8da/library/set#L31

**Comment by dagwieers** [comment]
@rektide It's in the previous PR #2688

**Comment by dagwieers** [comment]
So now that we have settled for **set_fact** for PR #2688, what do we want with this PR ?

I can see a few possibilities:
- Setting/overriding a play variable outside of the host-loop (would be like 'vars:' and 'vars_files:')
- Setting/overriding a variable in the same scope as --extra-vars _(probably not something we would allow)_
- Setting/overriding host inventory variables _(seems quite similar to facts, probably not useful)_
- Setting/overriding register variables _(not sure where they are currently stored, as facts too ?)_

But do we really need any of this ?

**Pull request closed without merging**
