### PR TITLE
kubevirt: even more unit tests

### PR DESCRIPTION
**Pull request by mmazur**
##### SUMMARY
More tests is better.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
kubevirt

### CODE REVIEW

**Comment by pkliczewski** [comment]
+1

**Comment by mmazur** [comment]
@willthames psst, I have a few more unit tests we had laying around from pre–upstream–merge times, that I'd like to get in.

And on a related note, one or two of those are so old they're pretty much k8s tests and not kubevirt tests. Would you guys want a PR with some k8s tests?

**Comment by willthames** [comment]
@mmazur k8s tests are always welcome!

**Comment by willthames** [comment]
These tests look good, happy to merge based on @pkliczewski's +1

**Pull request merged**
