### PR TITLE
make win_xml support batch mode and it can process many requests in one task

### PR DESCRIPTION
**Pull request by zhan9san**
##### SUMMARY

make win_xml support batch mode and it can process many requests in one task

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

make win_xml support batch mode and it can process many requests in one task
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sivel** [comment]
Thank you very much for your submission.  This is an unnecessary change, which can already be achieved by using `loop` on that task to loop through and get the same result.

We are not interested at this time in accepting a feature that duplicates another more fundamental feature.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by richardcs** [comment]
I don't see the purpose of the is PR. You can achieve what you are trying to do with hash tables and loops

https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html

**Comment by zhan9san** [comment]
Hey, 
This feature is similar to Pipelining. And this idea is based on Redis Pipelining
[Redis Pipelining](https://redis.io/topics/pipelining)

It will save much time when there are a large number of win_xml tasks need to be executed in target node.

Yes, playbook_loops will do the same thing, but there will be much network-interaction time and the time of forking many processes to handle every single task.

**Comment by dagwieers** [comment]
@zhan9san Read this: https://github.com/ansible/proposals/issues/71#issuecomment-417823437

**Comment by zhan9san** [comment]
Thanks, @dagwieers .
It seems that 'dataset' is a better way. I'm waiting for it.

BTW, is there a schedule for this new feature?

**Comment by dagwieers** [comment]
No, the proposal was beaten to death. One day maybe I may have the time to work on an implementation...

**Pull request closed without merging**
