### PR TITLE
Add SSL support to Consul inventory script

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

contrib/inventory/consul_io.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add SSL support to the Consul inventory script. If a Consul cluster is behind an SSL load balancer or proxy, the current inventory script will always use `http` as the scheme. This change will derive the scheme from the cluster URL. The default scheme remains `http`.

### CODE REVIEW

**Comment by ghost** [comment]
Pinging @sgargan for a quick look.

**Review by sgargan — APPROVED** [review]
looks good thanks for adding this. Looking at the docs a description for the url is missing (my bad), any chance you could write a line to describe it?

ship it!

**Comment by ghost** [comment]
Thanks for the quick feedback! Just pushed documentation for url option.

**Comment by sgargan** [comment]
@johnnycarlin that's great thanks for adding.

**Pull request merged**
