### PR TITLE
2 new modules for mongodb

### PR DESCRIPTION
**Pull request by rhysmeister**
##### SUMMARY

2 new modules for mongodb providing some rather obvious functionality.

mongodb_replicaset - Creates a mongodb replicaset.
mongodb_shard - Creates a mongodb shard.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
mongodb_replicaset
mongodb_shard

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = None
  configured module search path = [u'/Users/rhyscampbell/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by rhysmeister** [comment]
I understand I'll have to split the two modules into separate PRs but I'd like some feedback if possible. The last issues with these modules relate to the load_mongocnf() function which is present in the other mongodb modules (not authored by myself). I based my modules on this code so inherited this issue...

lib/ansible/modules/database/mongodb/mongodb_replicaset.py:271:24: use argspec type="path" instead of type="str" to avoid use of `expanduser`
lib/ansible/modules/database/mongodb/mongodb_shard.py:215:24: use argspec type="path" instead of type="str" to avoid use of `expanduser`

`mongocnf = os.path.expanduser('~/.mongodb.cnf')`

As this isn't a user supplied variable I don't think the suggestion is appropriate. How should this be resolved?

**Comment by mattclay** [comment]
@rhysmeister You can add the module path to the list of files to ignore for that test:

https://github.com/ansible/ansible/blob/32c191ee9c886fe727780bf94eaa8c64a588bc26/test/sanity/code-smell/use-argspec-type-path.py#L14

Alternatively, updating the test to ignore expanduser on static values would be welcome:

https://github.com/ansible/ansible/blob/32c191ee9c886fe727780bf94eaa8c64a588bc26/test/sanity/code-smell/use-argspec-type-path.py#L38

If you go for the second option, please do so in a separate PR.

**Comment by rhysmeister** [comment]
@mattclay Thanks for the input. I'll take a look at these options over the weekend.

**Comment by rhysmeister** [comment]
Closing PR to resubmit modules in separate PRs.

**Pull request closed without merging**
