### PR TITLE
Add FreeIPA module for managing DNS records

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/identity/ipa/ipa_dnsrecord.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Review by resmo — APPROVED** [review]
shipit

**Comment by resmo** [comment]
thanks!

**Comment by Akasurde** [comment]
@resmo Thanks for review and merge.

**Comment by fxfitz** [comment]
Yay! Glad to see this got in! :-D

**Pull request merged**
