### PR TITLE
Support Azure IoT hub and related module

### PR DESCRIPTION
**Pull request by yuwzho**
##### SUMMARY

This PR supports:
- **azure_rm_iothub**: create, update, delete Azure IoT Hub
- **azure_rm_iotdevice**: create, update, delete Azure IoT Hub device (twin)
- **azure_rm_iotdevicemodule**: create, update, delete Azure IoT Hub device module
- **azure_rm_iothubconsumergroup**: create, delete Azure IoT Hub consumer group
- **azure_rm_iothub_facts**: Query, get Azure IoT Hub (keys, consumer group, quota_metrics, endpoint_health)
- **azure_rm_iotdevice_facts**: Query, get details of Azure IoT Hub device (twin, module)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

azure_rm_iothub

##### ADDITIONAL INFORMATION

```paste below
2.9
```

### CODE REVIEW

**Comment by yuwzho** [comment]
@mattclay Could you please help me to register the `Microsoft.Devices/IotHubs`?

**Comment by mattclay** [comment]
@yuwzho I don't see a resource provider by that name. Can you verify the name?

**Comment by yuwzho** [comment]
@mattclay Should be `Microsoft.Devices`

**Comment by mattclay** [comment]
@yuwzho I've registered `Microsoft.Devices`.

**Comment by yuwzho** [comment]
@mattclay Thanks!

**Comment by Fred-sun** [comment]
@yuwzho Do you have finished the PR changed？ ready_for_review or not?

**Comment by Fred-sun** [comment]
@yungezz @zikalino Please take a review this when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
@yungezz @zikalino review_need

**Comment by Fred-sun** [comment]
@yungezz @zikalino @MyronFanQiu Please take a review this PR when you're free! Thanks a lot!

**Review by nitzmahone — APPROVED** [review]

**Comment by Fred-sun** [comment]
review_need

**Comment by Fred-sun** [comment]
@MyronFanQiu @yungezz This PR already approved. Now this PR show exist conflicts, but I don't see the cause of the conflict. Could you take a look this and promote to merge? Thank you very much!

**Pull request merged**
