### PR TITLE
aix_facts.py added

### PR DESCRIPTION
**Pull request by flynn1973**
##### SUMMARY
- This module gathers AIX specific facts
    - It delivers the folowing ansible_facts
      oslevel, build(ING specific), lpps, filesystems, mounts, vgs, lssrc,
    - niminfo, uname, drmode(ING specific)

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
aix_facts

##### ADDITIONAL INFORMATION
Examples:
```yaml
# show the default facts
- name: show default facts
  aix_facts_py:
# show all facts
- name: show all facts
  aix_facts:
    options:
      - all
# show facts uname and build:
- name: show facts uname and build
  aix_facts:
    options:
      - uname
      - build
```

### CODE REVIEW

**Comment by bcoca** [comment]
why not make this part of standard fact gathering? https://github.com/ansible/ansible/tree/devel/lib/ansible/module_utils/facts

**Comment by flynn1973** [comment]
i tried to port it over here (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/hardware/aix.py) but could not get my head around the functionalities behind the facts gahtering stuff.
i use all the modules  from my PR's on play level on a daily basis in production, and it works well enough, at least for me.

**Comment by dagwieers** [comment]
@flynn1973 We definitely want to see this in the standard AIX facts, which would make this information available to your playbooks without the need to run this module explicitly. Unless there's a good reason to not enable this module (e.g. it being very slow).

**Comment by molekuul** [comment]
@flynn1973 Hi, this module was not ready just for a pull request, that why I didn't do that before.
please contact me about your fork of my AIX-ansible-modules role, where you found this module.

Kind regards,

Joris Weijters

**Comment by kairoaraujo** [comment]
@flynn1973 I can help you to have it as part of standard fact, as I had some contact with that before.

**Comment by flynn1973** [comment]
you are very welcome!

**Comment by dagwieers** [comment]
For this PR, I have added another action item on the AIX action list with a link to this PR so we don't forget to do this. But I am going to close this PR. Feel free to pick up that action item if you need any of these facts by default in Ansible.

PS The only reason for handing certain facts of to special modules is:
1. If these facts take a long time to be produced and/or may have a specific impact on the system
2. If these facts relate to a specific object (so you need to add specific parameters to influence the output)

**Pull request closed without merging**
