### PR TITLE
20958 Feature Request: Allow 'file' module to optionally shred directory/files #20958

### PR DESCRIPTION
**Pull request by Alexander198961**
created function which will remove all files in folder and subfolder using shred command

Implementation #27545 
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

./lib/ansible/modules/files/file.py
##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests due to a traceback under python 3:

```
Traceback (most recent call last):
  File "/tmp/ansible_6m31qyse/ansible_module_file.py", line 504, in <module>
    main()
  File "/tmp/ansible_6m31qyse/ansible_module_file.py", line 464, in main
    os.system("shred -u " + b_path)
TypeError: Can't convert 'bytes' object to str implicitly
```

CI is also failing on OS X and FreeBSD at `test/integration/targets/file/tasks/main.yml:23 / [testhost] testhost: file : check result that=[u"absent_secure_result.state=='absent'"]`:

```
{
    "assertion": "absent_secure_result.state=='absent'", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```

**Comment by mattclay** [comment]
CI failure on FreeBSD and OS X the same as before.

**Comment by Alexander198961** [comment]
@mattclay can someone review pr ?

**Comment by robinro** [comment]
@Alexander198961 It appears you pushed some unrelated commits to this branch. Please remove them again.

**Comment by evrardjp** [comment]
need_revision

**Comment by evrardjp** [comment]
This PR is in conflicting state in master branch, contains multiple changes into one PR (please separate the zypper new feature from the shred), doesn't follow the usual YAML style guide, and doesn't pass tests. Could you have a look at it, please?

**Comment by Alexander198961** [comment]
@evrardjp  I will do  this .  is it ok to have this implementation in the file ? (https://github.com/ansible/ansible/issues/20958)  . or it should move to the module ?

**Comment by evrardjp** [comment]
With the title of the PR, I would say it would make make sense to implement this in file :)

**Comment by Alexander198961** [comment]
will take a look when  have time

**Comment by evrardjp** [comment]
Thanks @Alexander198961

**Comment by bcoca** [comment]
closing due to inactivity and conflicts, reopen in new PR if you still want to contribute this feature.

**Pull request closed without merging**
