### PR TITLE
docker_image: allow proxy config

### LINKED ISSUE #53857: docker_image: ignores DOCKER_CONFIG/config.json
##### SUMMARY
I'm trying to build a Dockerfile behind proxy using docker client config.json as described [here](https://docs.docker.com/network/proxy/#configure-the-docker-client).
Ansible docker_image default path for config.json is different that the one for docker client:
[Docker docs](https://docs.docker.com/network/proxy/#configure-the-docker-client): ~/.docker/config.json
[Ansible docs](https://docs.ansible.com/ansible/latest/modules/docker_image_module.html#notes): ~/docker/config.json

Trying to use DOCKER_CONFIG doesn't solve the problem:
```
$ echo DOCKER_CONFIG=/root/.docker >> /etc/environment
$ sudo su -
$ echo $DOCKER_CONFIG
/root/.docker
```
Links don't solve the problem:
```
# config.json for non privileged user in place
$ cat /home/tester/.docker/config.json
# config.json for root as we use become
# cat /root/.docker/config.json

{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://myproxy.com:8080",
     "httpsProxy": "http://myproxy.com:8080",
     "noProxy": "127.0.0.1"
   }
 }
}

# adding a link
# ln -s .docker docker
# cat /root/docker/config.json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://myproxy.com:8080",
     "httpsProxy": "http://myproxy.com:8080",
     "noProxy": "127.0.0.1"
   }
 }
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION

```
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tester/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```
ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

$ pip list |grep docker
docker (3.7.0)

$ docker version
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:56:33 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ cat /etc/environment
http_proxy=http://myproxy.com:8080
ftp_proxy=http://myproxy.com:8080
https_proxy=http://myproxy.com:8080
no_proxy=127.0.0.1


$ env|grep -i proxy
http_proxy=http://myproxy.com:8080
ftp_proxy=http://myproxy.com:8080
https_proxy=http://myproxy.com:8080
no_proxy=127.0.0.1
```

##### STEPS TO REPRODUCE

$ cat Dockerfile
```
FROM ubuntu:16.04
RUN apt-get -y update
RUN apt install -y rsync
```
$ cat inventory
```
localhost
```

$ cat playbook.yml
```yaml
---
- hosts: localhost
  tasks:
    - become: yes
      docker_image:
        path: .
        name: aptupdate:latest
```

##### EXPECTED RESULTS

Ansible docker_image should successfully build a Dockerfile

##### ACTUAL RESULTS

Ansible docker_image skips docker client `config.json` and the Dockerfile timeouts without proxies.

```paste below
$ ansible-playbook -i inventory playbook.yml -v

PLAY [localhost] ***************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************
ok: [localhost]

TASK [docker_image] ************************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error building aptupdate - code: 100, message: The command '/bin/sh -c apt install -y rsync' returned a non-zero code: 100, logs: [u'Step 1/3 : FROM ubuntu:16.04', u'\\n', u' ---> 9361ce633ff1\\n', u'Step 2/3 : RUN apt-get -y update', u'\\n', u' ---> Running in e11b537b34fd\\n', u'Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease\\n  Could not connect to archive.ubuntu.com:80 (91.189.88.161), connection timed out [IP: 91.189.88.161 80]\\nErr:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease\\n  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.161 80]\\nErr:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease\\n  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.161 80]\\n', u'Err:4 http://security.ubuntu.com/ubuntu xenial-security InRelease\\n  Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out [IP: 91.189.88.152 80]\\n', u'Reading package lists...', u'\\n', u'\\x1b[91mW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Could not connect to archive.ubuntu.com:80 (91.189.88.161), connection timed out [IP: 91.189.88.161 80]\\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.161 80]\\nW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.161 80]\\nW: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out [IP: 91.189.88.152 80]\\nW: Some index files failed to download. They have been ignored, or old ones used instead.\\n\\x1b[0m', u'Removing intermediate container e11b537b34fd\\n', u' ---> adc7a49df695\\n', u'Step 3/3 : RUN apt install -y rsync', u'\\n', u' ---> Running in a44021974022\\n', u'\\x1b[91m\\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\\n\\n\\x1b[0m', u'Reading package lists...', u'\\n', u'Building dependency tree...', u'\\nReading state information...\\n', u'\\x1b[91mE: Unable to locate package rsync\\n\\x1b[0m', u'Removing intermediate container a44021974022\\n']"}
        to retry, use: --limit @/home/tester/playbook.retry

PLAY RECAP *********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

NOTE: adding buildargs works as expected:
```yaml
---
- hosts: localhost
  tasks:
    - become: yes
      docker_image:
        path: .
        name: aptupdate:latest
        buildargs:
          http_proxy: "{{ proxy_env.http_proxy }}"
          https_proxy: "{{ proxy_env.https_proxy }}"
          no_proxy: "{{ proxy_env.no_proxy }}"
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
When building a docker image with `docker_image`, allows to use the proxy config specified in the client config. Fixes #53857.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
docker_image

### CODE REVIEW

**Comment by jwitko** [comment]
@felixfontein forgive my ignorance here but I'm not sure I understand which part of this code actually implements the proxy information from the local config of the executing user into the container build?

**Comment by felixfontein** [comment]
It doesn't; it tells docker-py to do that by setting `use_config_proxy=True` in `APIClient.build()` ([docs](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.build.BuildApiMixin.build)). The docs say about that flag:
> `use_config_proxy` (*bool*) – If `True`, and if the docker client configuration file (`~/.docker/config.json` by default) contains a proxy configuration, the corresponding environment variables will be set in the container being built.

**Comment by jwitko** [comment]
Thank you, I understand now.

**Review by jwitko — APPROVED** [review]
LGTM

**Comment by pmossakx** [comment]
I've tested locally with below configuration:
```
$ ansible --version
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tester/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tester/pmossakx/ansible/lib/ansible
  executable location = /home/tester/pmossakx/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

$ git log --pretty=oneline --abbrev-commit -3
3ccc19d Add changelog.
60973f8 Add use_config_proxy option.
eaff384 Simplify checks.

$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

$ pip list |grep docker
docker (3.7.0)

$ docker version
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:56:33 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ cat /etc/environment
http_proxy=http://myproxy.com:8080
ftp_proxy=http://myproxy.com:8080
https_proxy=http://myproxy.com:8080
no_proxy=127.0.0.1

$ env|grep -i proxy
http_proxy=http://myproxy.com:8080
ftp_proxy=http://myproxy.com:8080
https_proxy=http://myproxy.com:8080
no_proxy=127.0.0.1

# cat /root/.docker/config.json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://myproxy.com:8080",
     "httpsProxy": "http://myproxy.com:8080",
     "noProxy": "127.0.0.1"
   }
 }
}

$ cat playbook.yml
---
- hosts: localhost
  tasks:
    - become: yes
      docker_image:
        name: aptupdate:latest
        build:
          path: .
          use_config_proxy: yes
```

and I have below error:
`buildargs.setdefault(k, v)\r\nAttributeError: 'NoneType' object has no attribute 'setdefault'`
```
$ ansible-playbook -i inventory playbook.yml -vvv

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to localhost closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/tester/.ansible/tmp/ansible-tmp-1552987450.79-3358314798076/AnsiballZ_docker_image.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/tester/.ansible/tmp/ansible-tmp-1552987450.79-3358314798076/AnsiballZ_docker_image.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/tester/.ansible/tmp/ansible-tmp-1552987450.79-3358314798076/AnsiballZ_docker_image.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_docker_image_payload_Klr581/__main__.py\", line 916, in <module>\r\n  File \"/tmp/ansible_docker_image_payload_Klr581/__main__.py\", line 911, in main\r\n  File \"/tmp/ansible_docker_image_payload_Klr581/__main__.py\", line 474, in __init__\r\n  File \"/tmp/ansible_docker_image_payload_Klr581/__main__.py\", line 502, in present\r\n  File \"/tmp/ansible_docker_image_payload_Klr581/__main__.py\", line 725, in build_image\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/build.py\", line 179, in build\r\n    buildargs.setdefault(k, v)\r\nAttributeError: 'NoneType' object has no attribute 'setdefault'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by ffdybuster** [comment]
Looks like a bug in docker-py. If you specify `use_config_proxy=True` but pass `buildargs=None` (the default value), it crashes. I'll add a fix so that if `use_config_proxy` is true, it will always pass empty `buildargs` if the user didn't specify any.

For now, you can maybe (I'm not 100% sure) fix it by specifying empty buildargs:
```.yml
---
- hosts: localhost
  tasks:
    - become: yes
      docker_image:
        name: aptupdate:latest
        build:
          path: .
          use_config_proxy: yes
          args: {}
```

**Comment by ffdybuster** [comment]
Actually, that doesn't help, you have to specify some dummy value in `args`.

**Comment by felixfontein** [comment]
@pmossakx can you try again? I've added a commit which should prevent the crash.

**Comment by pmossakx** [comment]
Yup, it's green now:
```
$ git log --pretty=oneline --abbrev-commit -4
ad5a693 Avoid docker-py crash.
3ccc19d Add changelog.
60973f8 Add use_config_proxy option.
eaff384 Simplify checks.

$ ansible-playbook -i inventory playbook.yml -vvv
{output omitted}
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "archive_path": null,
            "build": {
                "path": ".",
                "use_config_proxy": true
            },
            "buildargs": null,
            "cacert_path": null,
            "cert_path": null,
            "container_limits": null,
            "debug": false,
            "docker_host": "unix://var/run/docker.sock",
            "dockerfile": null,
            "force": null,
            "force_absent": false,
            "force_source": false,
            "force_tag": false,
            "http_timeout": null,
            "key_path": null,
            "load_path": null,
            "name": "aptupdate:latest",
            "nocache": false,
            "path": null,
            "pull": true,
            "push": false,
            "repository": null,
            "rm": true,
            "source": "build",
            "ssl_version": null,
            "state": "present",
            "tag": "latest",
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "tls_verify": false,
            "use_tls": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

$ sudo docker images aptupdate
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
aptupdate           latest              f44c2cf1681d        4 minutes ago       144MB
```

**Comment by felixfontein** [comment]
Awesome! Thanks a lot for testing :)

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
@jwitko thanks for reviewing!
@pmossakx thanks again for feedback end testing!

**Pull request merged**
