### PR TITLE
default callback plugin: Add default 'show_per_host_start' value'

### LINKED ISSUE #69954: default value 'show_per_host_start' is missing
##### SUMMARY
When enabling zuul's executor verbose status for ansible, there are a lot of traces like:
```
2020-06-08 17:33:29,930 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'(<ansible.plugins.callback.zuul_unreachable.CallbackModule object at'
2020-06-08 17:33:29,930 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b"0x7f0d248e2c10>): 'show_per_host_start'"
2020-06-08 17:33:29,930 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'Callback Exception:'
2020-06-08 17:33:29,930 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'  File "/usr/local/lib/zuul/ansible/2.9/lib/python3.7/site-packages/ansible/executor/task_queue_manager.py", line 324, in send_callback'
2020-06-08 17:33:29,930 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'    method(*new_args, **kwargs)'
2020-06-08 17:33:29,930 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'   File "/usr/local/lib/zuul/ansible/2.9/lib/python3.7/site-packages/ansible/plugins/callback/default.py", line 256, in v2_runner_on_start'
2020-06-08 17:33:29,930 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b"    if self.get_option('show_per_host_start'):"
2020-06-08 17:33:29,931 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'   File "/usr/local/lib/zuul/ansible/2.9/lib/python3.7/site-packages/ansible/plugins/callback/__init__.py", line 91, in get_option'
2020-06-08 17:33:29,931 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'    return self._plugin_options[k]'
2020-06-08 17:33:30,126 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'Using module file /usr/local/lib/zuul/ansible/2.9/lib/python3.7/site-packages/ansible/modules/system/setup.py'
2020-06-08 17:33:30,126 DEBUG zuul.AnsibleJob.output: [e: 26a6cd8eb86144b9871b4841690cca62] [build: 71bc75c1ccc448aaa064ae393fe6ae51] Ansible output: b'Pipelining is enabled.'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

!component 

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/zuul/ansible/2.9/lib/python3.7/site-packages/ansible
  executable location = /usr/local/lib/zuul/ansible/2.9/bin/ansible
  python version = 3.7.7 (default, Apr 23 2020, 14:54:40) [GCC 8.3.0]

```

##### CONFIGURATION

config per playbooks used by zuul is defined in https://opendev.org/zuul/zuul/src/branch/master/zuul/executor/server.py#L2019-L2109
no show_per_host_start config is written, but ansible source shows that a default value should be defined, see "EXPECTED RESULTS" below

##### OS / ENVIRONMENT

docker image zuul/zuul-executor image:7e5160e0f9b0

##### STEPS TO REPRODUCE

run zuul quick-start tutorial https://zuul-ci.org/docs/zuul/tutorials/quick-start.html
enable executor debug logging:
add `doc/source/examples/etc_zuul/logging.conf` 
```
[loggers]
keys=root,zuul

[handlers]
keys=console

[formatters]
keys=simple

[logger_root]
level=INFO
handlers=console

[logger_zuul]
level=DEBUG
handlers=console
qualname=zuul
propagate=0

[handler_console]
level=DEBUG
class=StreamHandler
formatter=simple
args=(sys.stdout,)

[formatter_simple]
format=%(asctime)s %(levelname)s %(name)s: %(message)s
datefmt=

```
in `doc/source/examples/etc_zuul/zuul.conf` add `log_config=/etc/zuul/logging.conf` to `[executor]`

perform steps manually or using
`ansible-playbook -v playbooks/quick-start/localtest.yaml`
when executor container is up and executor is available, run:
`docker exec examples_executor_1 zuul-executor verbose`

```yaml

```

##### EXPECTED RESULTS

default value defined in https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/default.py#L56-L60
and/or https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml updated to include default value

as described in https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/default_callback.py#L58-L68

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by g-chauvel**
Fixes #69954

##### SUMMARY

default callback plugin: Add default 'show_per_host_start' value' 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

default callback plugin
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by bcoca — CHANGES_REQUESTED** [review]
this fix is incorrect, `get_option` is the correct way to get new settings, the `COMPAT_OPTIONS` list is for settings that existed before the plugin configuration system was added and to support 3rd party addons that subclassed 'default', this is not needed `show_per_host_start`, consuming plugin should use plugin configuration instead.

**Comment by g-chauvel** [comment]
ack, thanks.

**Comment by bcoca** [comment]
fyi, created #69972 as fix .. i thought we had already deprecated this, that is why i pointed as your fix as incorrect, but now this adds the deprecation notice.

**Comment by samdoran** [comment]
Closing since this was fixed in #69972.

**Pull request closed without merging**
