### PR TITLE
convert sfromm's assemble to module-magic

### PR DESCRIPTION
**Pull request by jpmens**
also ripped out md5, replaced by module.md5()
please test.

### CODE REVIEW

**Comment by sfromm** [comment]
The following block can go away since you do expanduser in the lines above:

```
if src:
    src = os.path.expanduser(src)
if dest:
    dest = os.path.expanduser(dest
```

There are a couple lines that still call fail_json that need to be updated to module.fail_json().

You can also drop the import of json/simplejson, sys, syslog, and shlex.

**Comment by mpdehaan** [comment]
what he said :)

**Comment by mpdehaan** [comment]
merged, can make those changes later, I may do it.

**Comment by mpdehaan** [comment]
done

**Comment by jpmens** [comment]
Apologies for the sloppy work -- I hoped you guys wouldn't notice ... ;)

**Pull request merged**
