### PR TITLE
Add python-passlib to docker images.

### PR DESCRIPTION
**Pull request by pilou-**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

```
ansible 2.2.0 (integration-tests-add-python-passlib e6ba324680) last updated 2016/06/21 00:56:58 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 343c3ecfb9) last updated 2016/06/21 00:53:59 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 9392943915) last updated 2016/06/21 00:53:59 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Required by #16361.

### CODE REVIEW

**Comment by pilou-** [comment]
@mattclay it seems there was some network problem with the [shippable build 766](https://app.shippable.com/runs/576875a51e09560c000ea560):
- 766.19:  `build_ci` step, `test/utils/shippable/ci.sh` script:

> 2016-06-20 23:15:26 Get https://registry-1.docker.io/v1/repositories/ansible/ansible/tags/fedora-rawhide: dial tcp 23.23.8.46:443: i/o timeout 

How could I restart/force this build ?

**Comment by mattclay** [comment]
@pilou- I've restarted the build.

This isn't actually necessary for your PR, since Shippable doesn't do anything with the Dockerfiles. I'll need to manually trigger rebuilding of the images after this is merged. However, I just updated one of the docker images (unrelated to your changes), so this gives me a chance to make sure CI still passes on the updated image.

**Comment by mattclay** [comment]
Images are being rebuilt now.

**Comment by mattclay** [comment]
Images have been rebuilt.

**Pull request merged**
