### PR TITLE
nxos_bgp_neighbor: Add bfd support

### PR DESCRIPTION
**Pull request by chrisvanheuveln**
##### SUMMARY
- Add support for bfd state in nxos_bgp_neighbor

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- nxos_bgp_neighbor

##### ADDITIONAL INFORMATION
- Tested on platforms: `N3K,N6K,N7K,N9K`

### CODE REVIEW

**Comment by mikewiebe** [comment]
LGTM

**Review by trishnaguha — CHANGES_REQUESTED** [review]
Please look at the comment #57425 (review)

**Comment by chrisvanheuveln** [comment]
@trishnaguha T/F -> enable/disable changes are committed. Retested against all regression testbeds.

**Comment by mikewiebe** [comment]
shipit

**Review by trishnaguha — APPROVED** [review]

**Pull request merged**
