### PR TITLE
New module: Windows Azure

### PR DESCRIPTION
**Pull request by jwhitbeck**
Use this module to provision or terminate virtual machines on windows azure.

We have been happily using this in prod at our company for 5 months now so we thought we would share it with the community.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This probably should just be shorted to "azure" in the module name, as we similarly don't have "amazon_aws" or "rackspace_rax" and this could be used to spin up Linux machines.

**Comment by mpdehaan** [comment]
In queue for review, we have some other parties interested in the same thing so this is quite timely.  Thanks!

**Comment by mpdehaan** [comment]
note to us (or if you'd like to fix that would be great), version_added stuff should be updated to say 1.7 (current development release).

Current shipping release is 1.6.X

**Comment by matlockx** [comment]
I'm working on something similar but have a bit more functionality in it.pull request should follow tomorrow. Maybe you wait and then compare what to take or take this one and I try to merge mine later on.

**Comment by matlockx** [comment]
Just some points from my side,correct me if I'm wrong:
With this pr it's not possible to create multiple vms to a deployment, cause you need to call add_role from the api a far I know. 
Terminate does not clean up os vhds and not ready for multiple roles per deployment. 
Since I already implemented that I would be happy to merge that into this pr after you have accepted it.

**Comment by jwhitbeck** [comment]
@matlockx All your points are correct. We did not implement these as we did not need them. It sounds like you have a more complete azure implementation, so we are looking forward to your pr.

**Comment by matlockx** [comment]
Well, complete is relative. I don't have that neat cache and config stuff so I'd be happy to merge my changes into yours. Maybe it makes sense to do a pull request into your repo first and you merge the parts that make sense and do a new pull request to the main repo. What do you think?

**Comment by jwhitbeck** [comment]
Let's see what the ansible devs prefer. I think it would be easier to first merge our module into the main repo, and then let you merge your improvements on top of that when they are ready.

**Comment by matlockx** [comment]
k, i’m also fine with that

**Comment by mpdehaan** [comment]
We're going to merge this one after some (pending) testing review and take some modifications on top of that.  We can then explore other additions in smaller steps.

Thanks all!

**Comment by jimi-c** [comment]
While trying to create a vm using the documented example (with my own storage account name there), I'm getting the following error:

<pre>
&lt;Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"&gt;&lt;Code&gt;BadRequest&lt;/Code&gt;&lt;Message&gt;The hosted service name is invalid.&lt;/Message&gt;&lt;/Error&gt;
</pre>

Any ideas what's wrong there?

**Comment by jimi-c** [comment]
Nevermind, turns out azure does not like VM names with an underscore in it. However, now I'm getting a different error... working through it.

One thing I'm definitely noticing, the error messages are not descriptive enough. For example, when a service name already exists, all that is printed is this:

<pre>
failed: [127.0.0.1] => {"failed": true}
msg: Conflict (Conflict)
</pre>

I'll be improving those before merging this in.

**Comment by jwhitbeck** [comment]
Thanks for all the work. If you would like me to chip in, just let me know.

**Comment by jimi-c** [comment]
So the issue I'm running into right now is that after deleting a VM, it does not allow me to recreate it using the same name. I see the service appear, and it says it's deploying, however after that no new VM's start up. So I tried deleting the entire cloud service - which is now recreated, but without certificates apparently. When I try and re-run the playbook I see this:

<pre>
failed: [127.0.0.1] =&gt; {"failed": true}
msg: failed to create the new virtual machine, error was: Unknown error (Bad Request)
&lt;Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"&gt;&lt;Code&gt;BadRequest&lt;/Code&gt;&lt;Message&gt;The certificate with thumbprint XXXXXXXXXXXXXXXXX was not found.&lt;/Message&gt;&lt;/Error&gt;
</pre>

So I'm not sure if this is something going on with Azure's API or if it's something the code isn't doing correctly. The thumbprint above shows up in my Azure console under my management certificates and matches exactly, so I'm not sure what's going on there yet.

**Comment by jimi-c** [comment]
Merged! You can see my changes in the committed version. One of the areas of improvement after using this module a bit could be that rather than fail when certain errors are caught (ie, the redirect error), that the operation be retried for a short timeout, which might make it a bit more resilient. I noted a lot of these errors during testing, and just had to rerun the playbook.

**Comment by matlockx** [comment]
Hi,

Thumbprint error is because it is an async request to add the certificate
to the cloud service/deployment. We need to wait for it. I'll do a pull
request.
The conflict error comes with no information from the sdk.I'm not sure
whether it's related to the sdk or the azure api directly. Will check that.
Temporary redirects are a big problem as I already told. We can wrap it in
a retry loop but I tried that and it doesn't solve it always. Meanwhile the
guys from the sdk merged my pr to fix the problem in the sdk but I don't
know when they will do a release.
https://github.com/Azure/azure-sdk-for-python/pull/157

So what do you think shall we do:
A)wrap each sdk request into a try catch loop,  do a search in the error
message whether it's a 'temporary redirect' and do the request again then.
But this will not fix all situations. I had really long retries which
exceeded the given timeout....
B) override the method in the sdk when the sdk version is <=0.8.0 to follow
redirects.

Best
Martin

**Comment by jimi-c** [comment]
That's fine if the retry loop exceeds a timeout, we can make that configurable, but it's definitely better than the spurious failures I was seeing (somewhat consistently).

I don't think we need to override the method, we can just require the SDK version to be > 0.8.0 after they do the release to fix the issue.

**Comment by matlockx** [comment]
k, I think something like that should do the trick:

```
   def handle_temporary_redirects(f):
    count = 0
    while True:
        try:
            return f()
        except WindowsAzureError as e:
            if str(e).lower().find("temporary redirect") and count < 10:
                count += 1
                time.sleep(2)
                pass
            else:
                raise e
```

result = handle_temporary_redirects(lambda : azure_sdk_method(...))

Do you really think that it is necessary that the timeout is configurable? I would do it hard coded  for 300 seconds.

**Comment by jimi-c** [comment]
It doesn't have to be.

**Comment by matlockx** [comment]
i created a pr: #7694 which should fix most of the problems that you saw. I will add another entry in the google group to discuss how we proceed with adding new feature.

**Pull request merged**
