### PR TITLE
Azure Common Module (azure_rm_common.py)

### PR DESCRIPTION
**Pull request by haroldwongms**
Remove tags

##### SUMMARY

Provide update to handle removing of tags from Azure resources.

If Azure resource has tags and you want to remove all tags (empty list), the current update_tags method is returning false which is incorrect.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

azure_rm_common.py
##### ANSIBLE VERSION

```
ansible 2.4.0 (common 393909d0cc) last updated 2017/08/15 15:36:14 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/haroldwong/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/Users/haroldw/Documents/develop/ansible24/lib/ansible
  executable location = /mnt/c/Users/haroldw/Documents/develop/ansible24/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by nitzmahone** [comment]
I don't think this is actually the behavior you want in nearly any case- this would cause things to be completely untagged if a later task came to modify some property of any resource and forgot to specify `tags`. 

The behavior you want should already work if `tags` was actually specified as an empty dictionary...

**Comment by haroldwongms** [comment]
@nitzmahone That is a good point.  I will update to look for empty dictionary.

**Comment by haroldwongms** [comment]
@nitzmahone  made the changes to look for empty dictionary - {} to handle deleting of tags.

**Comment by nitzmahone** [comment]
I don't think that works (or if it does, it's kinda by accident)- what I'm saying is that at least by inspection, the existing code should already do the right thing if you pass an empty dict- in particular this section:
```
if isinstance(tags, dict):
  for key, value in tags.items():
    if not self.module.params['tags'].get(key):
      new_tags.pop(key)
```

**Comment by haroldwongms** [comment]
@nitzmahone You are so correct!  My mistake.  Closing PR.

**Pull request closed without merging**
