### PR TITLE
To fix iosxr_l3_interfaces module zuul tests (#61592)

### LINKED ISSUE #61540: iosxr_l3_interfaces zuul tests failing intermittently for different python run
##### SUMMARY

iosxr_l3 zuul tests failing intermittently for different python run, ref: [link](https://github.com/ansible/ansible/pull/60464#issuecomment-526153103)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_l3_interfaces
##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

zuul

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Tests should pass w/o any issues

##### ACTUAL RESULTS

Tests failing intermittently 

```paste below

```

### PR DESCRIPTION
**Pull request by pabelanger**
* fix #61540

* fix utils

(cherry picked from commit 24ad1dffc9ad18df7090cc3782fd87523449e955)

### CODE REVIEW

**Comment by justjais** [comment]
recheck

**Comment by pabelanger** [comment]
I've created an issue for iosxr_config failure: https://github.com/ansible/ansible/issues/61766

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
This is important for us to have, to help stabilize our iosxr testing on stable-2.9

**Comment by abadger** [comment]
Merged for 2.9.0beta1

**Pull request merged**
