### PR TITLE
fixed doc regarding wild card pattern on groups.

### PR DESCRIPTION
**Pull request by dorfsmay**

### CODE REVIEW

**Comment by mpdehaan** [comment]
I will first have to confirm this is true, then I will see about making sure groups are not wildcarded if they presently are.

In any event, this should not be the case.

**Comment by dorfsmay** [comment]
On 2013-03-23 09:19, Michael DeHaan wrote:

> I will first have to confirm this is true, then I will see about making sure
> groups are not wildcarded if they presently are.
> 
> In any event, this should not be the case.

Do you mind sharing your rational behind preventing group wildcarding?

I can live without it, but I do like it if it's available. I see more shops 
where host names are almost random and have no link to the apps they are 
running, as a sysadmin I actually advocate that way (hosts are just bucket to 
hold applications/services, who cares what they are named as long as they are 
unique, and whatever logical scheme you pick to name them will be brocken: 
servers will be moved from physical to virtual and the other way around, they 
will be moved from a geographical address to another, they will have their ip 
address changes, etc... random hostnames work better in the long term). But 
people use some logic for andible group names e.g.: "front-proxies", 
"back-proxies", and that's where wildcarding would make the most sense in my 
opinion.

## 

Yves.                                                  http://www.SollerS.ca/
                                  Unix/Linux and Python specialist in Calgary.
                                                        http://blog.zioup.org/

**Comment by mpdehaan** [comment]
already discussed on a the list, I think we'll leave it as it is for now.

**Comment by mpdehaan** [comment]
merged in, I can add the oxford comma later :)

**Pull request merged**
