### PR TITLE
Establish sh as the default shell plugin.

### PR DESCRIPTION
**Pull request by abadger**
This is a fix for one of the problems pointed out in #14176

### CODE REVIEW

**Comment by bcoca** [comment]
+1

**Comment by nitzmahone** [comment]
Testing now on Windows...

**Comment by nitzmahone** [comment]
Had to add the last Windows fix patch first, but tests fine with both implicit and explicit ansible_shell_type. :+1:

**Comment by abadger** [comment]
Thanks guys!  Merged to devel and stable-2.0

**Pull request merged**
