### PR TITLE
Update contributor_path.rst

### PR DESCRIPTION
**Pull request by Goodiec**
##### SUMMARY

Fixed typos to improve the contributor path documentation page.

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @Goodiec for the Ansible docs fix!

**Comment by samccann** [comment]
@Goodiec  - are you part of the community-writers group? Just curious and again, welcome to Ansible!

**Comment by Goodiec** [comment]
> @Goodiec - are you part of the community-writers group? Just curious and again, welcome to Ansible!

Thank you @samccann and no, I'm not part of the group.

**Pull request merged**
