### PR TITLE
Fix 'CyberarkPassword' object has no attribute 'delimiter'

### PR DESCRIPTION
**Pull request by mback2k**
##### SUMMARY

@Akasurde @samdoran @webknjaz

This is a very small follow up to PR #59500 to fix the following exception:
```
ERROR! Unexpected Exception, this is probably a bug: 'CyberarkPassword' object has no attribute 'delimiter'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/executor/task_queue_manager.py", line 240, in run
    play_return = strategy.run(iterator, play_context)
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/plugins/strategy/linear.py", line 282, in run
    _hosts=self._hosts_cache, _hosts_all=self._hosts_cache_all)
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/vars/manager.py", line 425, in get_vars
    all_vars['ansible_delegated_vars'], all_vars['_ansible_loop_cache'] = self._get_delegated_vars(play, task, all_vars)
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/vars/manager.py", line 523, in _get_delegated_vars
    items = wrap_var(lookup_loader.get(task.loop_with, loader=self._loader, templar=templar).run(terms=loop_terms, variables=vars_copy))
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/plugins/lookup/cyberarkpassword.py", line 179, in run
    result = cyberark_conn.get()
  File "/opt/ansible-virtualenv/lib/python3.5/site-packages/ansible/plugins/lookup/cyberarkpassword.py", line 124, in get
    '-d', self.delimiter]
AttributeError: 'CyberarkPassword' object has no attribute 'delimiter'
```

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

cyberarkpassword lookup plugin

### CODE REVIEW

**Comment by mback2k** [comment]
Unfortunately we forgot to fix the variable name at this line during the refactoring of PR #59500.

**Review by webknjaz — APPROVED** [review]

**Comment by samdoran** [comment]
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

**Comment by mback2k** [comment]
@samdoran I just added the requested changelog fragment. I can also confirm that I was able to successfully run Ansible with CyberArk AIM in production today after applying this one-line-fix.

**Comment by samdoran** [comment]
@mback2k Sounds good. Thank you for the fix.

rebuild_merge

**Comment by mback2k** [comment]
Would it be possible to include this in a patch release of 2.9, because at the moment the plugin is unfortunately completely broken without this bugfix. I am really sorry that this went into 2.9 initially.

**Comment by samdoran** [comment]
Yes, this will be backported to 2.9.

**Comment by samdoran** [comment]
CI failures are unrelated to this PR. Merging.

**Pull request merged**
