### PR TITLE
changed from hash_merge to combine vars which resets default to

### PR DESCRIPTION
**Pull request by bcoca**
overwrite and not merge hashing

fixes #10328
but not  #10327

### CODE REVIEW

**Comment by bcoca** [comment]
alternate fix for #10328

**Comment by jtyr** [comment]
I can confirm that this patch fixes the issue described in the PR #10328.

**Comment by srgvg** [comment]
(doesn't solve #10327)

**Comment by bcoca** [comment]
updated, moved group vars up and removed inventory call as it should be redundant

**Comment by srgvg** [comment]
OK, with that last commit, this solves #10327

**Comment by drybjed** [comment]
<del>Can't find any new issues, at least with the codebase I'm using.</del>

Edit: I was wrong, there's still an issue with one of my templates. [This code snippet](https://github.com/debops/ansible-ferm/blob/master/templates/etc/ferm/ferm.d/10_forward.conf.j2#L10-L32) is not rendered properly when firewall should have enabled forwarding.

**Comment by bcoca** [comment]
And serge also saw a group_by stop working as inventory vars are not added to the 'templatable' set, re-adding inventory vars.

**Comment by drybjed** [comment]
After latest change, file is templated correctly, checking the rest.

**Pull request merged**
