### PR TITLE
gitlab_user: add support to block/unblock user (#61754)

### PR DESCRIPTION
**Pull request by mjeco**
##### SUMMARY
Adds support to `gitlab_user` to block/unblock the account of a given user (#61754)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
gitlab_user

##### ADDITIONAL INFORMATION
It is currently not possible to specify `state=blocked` or `state=unblocked` to block/unblock the user's account in GitLab.
Previously, the only possible options were to create or delete the account.

### CODE REVIEW

**Comment by Akasurde** [comment]
@mjeco Thanks for the contribution. Could you please fix following - 

https://app.shippable.com/github/ansible/ansible/runs/142016/1/console

```
03:16 ERROR: Found 1 pep8 issue(s) which need to be resolved:
03:16 ERROR: lib/ansible/modules/source_control/gitlab_user.py:420:5: E303: too many blank lines (2) (50%)
```

**Comment by mjeco** [comment]
@Akasurde pep8 issue fixed.

**Comment by Lunik** [comment]
You can improve the PR by adding the option to `unblock` the user

**Comment by Shaps** [comment]
@mjeco I agree with previous comment, add a `state: unblocked` to the options. Looks good otherwise

**Comment by mjeco** [comment]
@Lunik @Shaps Thanks for the input. I will implement the "unblocked" state.

**Comment by Lunik** [comment]
@mjeco can you please rebase your PR

**Pull request closed without merging**
