### PR TITLE
filter invalid args from actions

### LINKED ISSUE #37238: remote_src=true with template causes Module (template) is missing interpreter line
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

```

##### CONFIGURATION

```
ansible-config dump --only-changed
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Linux cf9ec7d3290d 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

##### SUMMARY

Template module can't be run: `"module (template) is missing interpreter line"`
Tested on version 2.3.0, 2.4.0 and 2.4.3.0, on python 2 and 3.5, always with the same result.

##### STEPS TO REPRODUCE

Create a playbook with a template task type within it, and run the playbook.

```yaml
- name: "VM installation"
  hosts: local
  connection: local
  gather_facts: True
  tasks:
    - include_vars: config.yml
    - name: "Vault - copying server config file"
      template:
        src: "/tmp/vault/files/config.hcl"
        dest: /etc/vault/config.hcl
        remote_src: yes
        mode: 0640
        owner: vault
        group: vault
```

##### EXPECTED RESULTS

The template should have been generated.

##### ACTUAL RESULTS

```
TASK [Vault - copying server config file] ***************************************************************************************************************************************************************************************************************************************
task path: /tmp/vault/install.yml:55
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/files/template.py
fatal: [localhost]: FAILED! => {
    "msg": "module (template) is missing interpreter line"
}
```

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
creates general facility and fixes template specfically

fixes #37238

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

action plugins

##### ANSIBLE VERSION

```
2.4-2.6
```

### CODE REVIEW

**Comment by abadger** [comment]
This is wrong.  (1) It needs to be a whitelist.  (2) If we're serious about moving argspec to the action modules in the future, we do not want to create a generic facility that will be in conflict with that. 

CC @nitzmahone

**Comment by sivel** [comment]
I am in agreement with @abadger 

We should do a whitelist.  When we do the basic.py separation (based on work I have done so far) we will get arg_spec validation functionality in action plugins, since we can use "that" new class independently of a module.

**Comment by maxamillion** [comment]
@bcoca @sivel any update here?

**Comment by samdoran** [comment]
~Superseded by #44779~

**Comment by bcoca** [comment]
@samdoran related but not the same

**Pull request closed without merging**
