### PR TITLE
Fixing assigning ssl certificate to http listener in app gateway (#45…

### PR DESCRIPTION
**Pull request by zikalino**
…830)

* fixed ssl certificate reference

* modified test

(cherry picked from commit 83645963fb8eeda6dccc53a838b5a529de20de04)

##### SUMMARY
Backporting appgateway bug

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_appgateway

##### ANSIBLE VERSION
2.7

### CODE REVIEW

**Comment by Fred-sun** [comment]
@nitzmahone @bcoca Could you help review this PR? Thanks!

**Comment by abadger** [comment]
This needs a changelog entry.

**Comment by yuwzho** [comment]
#46830

**Comment by yuwzho** [comment]
#45830

**Comment by yuwzho** [comment]
@zikalino Please create a change log under [changelogs/fragments ](https://github.com/zikalino/ansible/tree/backport/2.7/45830/changelogs/fragments )

**Comment by Fred-sun** [comment]
@zikalino

**Comment by abadger** [comment]
@zikalino, this needs a changelog entry before being merged.  You can look at https://github.com/ansible/ansible/tree/stable-2.7/changelogs/fragments  for examples of hte format.

**Comment by zikalino** [comment]
@abadger added changelog, could you pls merge?

**Comment by abadger** [comment]
Merged for the 2.7.1 release.

**Pull request merged**
