### PR TITLE
fixes the the repetitions

### PR DESCRIPTION
**Pull request by wookietreiber**
##### SUMMARY

Wow, this does not seem to be an uncommon misspelling. Might be there are some left that span over two lines. I noticed the one in the git module and then used `grep -rw 'the the'` to find some more.

##### ISSUE TYPE

 - Docs Pull Request

### CODE REVIEW

**Review by schmots1 — APPROVED** [review]
shipit

**Review by mwperina — APPROVED** [review]

**Comment by mwperina** [comment]
shipit

**Review by achinthagunasekara — APPROVED** [review]

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@wookietreiber Nice spot, could you please rebase then I'll merge http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

(Don't use GitHub's UI to resolve the conflict)

**Comment by felixfontein** [comment]
@wookietreiber Sorry for introducing the conflict! We moved `lib/ansible/modules/web_infrastructure/acme_certificate.py` to `lib/ansible/modules/crypto/acme/acme_certificate.py`. Fortunately, git's three-way-merge should be able to handle this rebase without human intervention (at least it did so for me in similar cases).
And thanks for fixing this :)

**Review by felixfontein — APPROVED** [review]
shipit

**Review by resmo — APPROVED** [review]
shipit

**Pull request merged**
