### PR TITLE
WIP added deploy_helper module tests

### PR DESCRIPTION
**Pull request by ramondelafuente**
I did not know if this was required, but it seemed prudent to add tests for the deplot_helper module.
The pull request for the module is on the ansible-modules-extra's repository: https://github.com/ansible/ansible-modules-extras/pull/110

I consider this a WIP. The tests all run down here, and they cover all the module features/parameters, but I'd still like to have a second opinion.

### CODE REVIEW

**Comment by amenonsen** [comment]
This commit needs to be revised to apply to current devel, but I see that the module itself is under discussion in the `ansible-modules-extra` repository, and @gregdek said «I think we're going to try to have some explicit review-a-thons soon» so I'll assume this will be handled as part of that process.

**Comment by ramondelafuente** [comment]
Having the tests and the module in separate repositories is a hassle. I have updated the PR for the module - if that is finally OK'ed then I'll update these as well. The module has not changed so the tests should still be valid.

**Comment by ramondelafuente** [comment]
The `deploy_helper` module was merged. So this PR might still be required, right?
(I'm unclear about the policy on tests for modules in extra's)

**Comment by amenonsen** [comment]
@gregdek @robynbergeron _is_ there a policy on tests for modules in -extra?

**Comment by bcoca** [comment]
@amenonsen tests are fine (we do plan to put extra modules tests in extras repo, but not there yet)

**Comment by gregdek** [comment]
The policy, I would say, is that tests are "encouraged". The mechanism will be much clearer when the tests are all moved to the extras repo, but as @bcoca notes, that hasn't happened yet.

**Comment by ramondelafuente** [comment]
I haven't made any attempt to keep this PR up to date since the policy around it was not clear. It's almost got a beard now ;-)

**Comment by amenonsen** [comment]
@ramondelafuente any chance I could convince you to neaten up its beard :-) a bit and resubmit?

**Comment by mattclay** [comment]
Tests have been rebased, updated and merged in https://github.com/ansible/ansible/pull/23245

**Pull request closed without merging**
