### PR TITLE
Synchronize uses ~/.ssh/config like Ansible core does

### PR DESCRIPTION
**Pull request by damianmoore**
If the user has an ~/.ssh/config file with parameters for the current host, Ansible uses those to connect. Before this change, the synchronize module would fail as it would just fall back to user running the command, provided hostname, default port and no key. I believe this makes the module on par with what the user expects running the rest of Ansible.

Related issue:
https://github.com/ansible/ansible/issues/1171

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ansible uses those when using the SSH transport, but we should NOT be using paramiko code when not using paramiko, as it creates a dependency we don't wish to have.

I'm also a bit concerned about the "fall back to..." comment above and the size of this patch, , as well as what various uncommented lines added to the synchronize transport here do.   This doesn't mean I think they are wrong, it's just their purpose is not immediately obvious.

Other lines like this:

```
 if 'hostname' in ssh_cfg:
 +            dest_host = ssh_cfg['hostname']
```

Should be written:

```
dest_host = ssh_config.get('hostname', dest_host)
```

If you are talking about synchronize with the OpenSSH connection type, that seems more like this could be solved without the paramiko bits.  

Really, synchronize is intended as a "friendly" wrapper around local_action: shell rsync and in many cases if you want something very specific, that may be a good answer.

Please stop by ansible-devel if you'd like to discuss further.   Thanks!

**Comment by mpdehaan** [comment]
It's also worthwhile to mention we've had people report things before where they want the global SSH config file also read

**Comment by damianmoore** [comment]
Paramiko is already a dependency of Ansible. I can see some related code reading ~/.ssh/config with paramiko in /plugins/inventory/ssh_config.py. I'll see if I can use that function instead of the slight duplication.

I understand that synchronize should be simple but I think it is currently confusing for the user as it behaves differently from the rest of Ansible.

Lets say I am a newish user to Ansible or am just not interested in reading through the source code. I have all my hosts set up in my ~/.ssh/config and Ansible works fine. As time goes on I add more deployment steps, then I add synchronize and if fails with weird errors. I'm not trying to do anything complicated with synchronize, just a basic synchronisation. I end up trying all sorts of options before realising I have to duplicate my settings in an ansible hosts file. Using the synchronize plugin is a nicer syntax in a list of tasks compared to running custom commands.

**Comment by mpdehaan** [comment]
Sounds like we're at an impassse with this one, so I'm going to close the ticket.  I'm still up for discussion though, so stop by ansible-devel if you like.

Thanks!

**Pull request closed without merging**
