### PR TITLE
uri: load JSON for content-type: application/json

### PR DESCRIPTION
**Pull request by jpmens**
If the resource consumed by URI returns JSON, load JSON from the returned content string.

Sample playbook:

``` yaml
  - action: uri
            url="http://localhost/jp.cgi"
            dest=/tmp/ph
            return_content=true
    register: body
  - action: template src=t1.j2 dest=/tmp/t1
```

Example template:

```
name = {{ body['json']['name'] }}
```

Example CGI

``` sh
#!/bin/sh

echo "Content-type: application/json"
echo ""
echo '{ "name": "Jane Jolie", "number" : 49 }'
```

### CODE REVIEW

**Comment by rrtj3** [comment]
This is great! Thanks. I wonder if instead of:

``` python
if uresp['content_type'] == 'application/json':
```

it should be:

``` python
if uresp['content_type'].startswith('application/json'):
```

or something along those lines. The reason is I tested on JIRA and it returns this header:

Content-Type: application/json;charset=UTF-8

with the UTF-8 stuff it doesn't get picked up. Just checking if application/json is somewhere in the Content-Type header might be more flexible.. Thoughts?

**Comment by jpmens** [comment]
I agree; shall fix. 

Also, I'm thinking it would be good to merge the JSON keys into uresp; avoids a level of indirection when accessing them. There is a slight chance of clobbering your defined keys, but we can live with that maybe?

**Comment by jpmens** [comment]
Done both. I think the merged JSON looks better:

```
body {u'changed': True,
 u'connection': u'close',
 u'content': u'{ "name": "Jane Jolie", "number" : 49 }\n',
 u'content_location': u'http://localhost/jp.cgi',
 u'content_type': u'application/json',
 u'date': u'Tue, 19 Feb 2013 09:25:18 GMT',
 'invocation': {'module_args': 'url="http://localhost/jp.cgi" dest=/tmp/ph return_content=true',
                'module_name': 'uri'},
 u'name': u'Jane Jolie',
 u'number': 49,
 u'server': u'Apache/2.2.15 (CentOS)',
 u'status': u'200',
 u'transfer_encoding': u'chunked'}
```

**Comment by rrtj3** [comment]
Nice!

**Comment by mpdehaan** [comment]
Ok, so I actually disagree with this, because the caller now has to do two different things based on content type.   I would be fine if it returns a new key with the JSON also decoded, like "decoded_data" or something.

I think JSON is the only format that is likely here as there aren't many web services that speak YAML that I know of...but I would want the return types to not change based on content type, though the addition of an additional hash with the decoded results is good!

Let me know if that seems to make sense or not.

**Comment by jpmens** [comment]
The caller doesn't _have_ to do two different things; content continues to be available as a string.

Originally I had a new key with JSON decoded in it, but I feel this is easier, particularly when accessing in a Jinja2 template.

(And I don't know of web services that speak YAML, but plenty speak XML.)

**Comment by mpdehaan** [comment]
XML serialization to a data structure and getting the same XML back is kind
of tricky though :)

**Comment by mpdehaan** [comment]
Ok, so this puts every JSON key as a top level in the return.

Sorry, I misread, it's early here :)

I would be ok with it putting the whole response in a subkey called "json" rather than mingling the response with the headers.

Sound ok?

So ${result.json.foo} etc

**Comment by mpdehaan** [comment]
Sorry, did not mean to close, you can just update this PR if you want.

Let me know if that didn't make sense.

**Comment by jpmens** [comment]
Updated.

**Comment by mpdehaan** [comment]
Much appreciated, thanks!

**Pull request merged**
