### PR TITLE
Update name of ec2_vpc_dhcp_option module in docs

### PR DESCRIPTION
**Pull request by willtome**
label: docsite_pr

##### SUMMARY
Correct module name is ec2_vpc_dhcp_option

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
ec2_vpc_dhcp_option

##### ANSIBLE VERSION
2.5
```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by ryansb — APPROVED** [review]

**Review by gundalow — APPROVED** [review]
Ah, thanks for spotting and fixing this. My copy paste mistake

**Comment by acozine** [comment]
Thanks for submitting this and apologies for the length of time it's been sitting out here. @willtome can you rebase? Once the conflict is gone, I'll merge.

**Review by gundalow — APPROVED** [review]
Needs backport

**Comment by gundalow** [comment]
Looks like this has already been fixed so closing.

**Pull request closed without merging**
