### PR TITLE
setup - Minimal generic network handling via netifaces module

### PR DESCRIPTION
**Pull request by nigelm**
Gets some network information across platforms where netifaces is installed.
Less info that other mechanisms, but should work on wide variety of platforms.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Interesting, I'll think about it.

**Comment by mpdehaan** [comment]
Can we make this so that it is only used if a more OS specific way has not already been defined?  Would not want to lose detail or add the extra dependency when we don't need to.

Thanks!

**Comment by nigelm** [comment]
The last part of the change to the constructor:-

```
        if ((sc.platform == platform.system())
            or (sc.platform == 'Generic_Netifaces' 
                and HAVE_NETIFACES 
                and subclass is cls)):
```

was to only fire for netifaces if the subclass had not been otherwise set, so should make this only work if there is no better subclass.

**Comment by mpdehaan** [comment]
I would have probably done it in a wrapper function.

Generically speaking this could be like:

def foo(self,...):
    other_way = getattr(self, 'foo_other_way', None)
    if other_way:
        return other_way(...)
    # regular normal function here

**Pull request closed without merging**
