### PR TITLE
docker: add pull_latest option to pull latest image when creating container

### PR DESCRIPTION
**Pull request by discordianfish**
This option will cause ansible to pull the latest image before running a new container.

### CODE REVIEW

**Comment by iragsdale** [comment]
I have a question about the intended behavior of this module when updating to the latest version of an image. I would probably consider this a bug, but perhaps others may not.

If you pull the latest version of a given named image, the docker image that name references will change, but any existing containers launched using that name are still using the old image. If you do a "docker inspect" on those containers, they still list the image name in Config->Image, but the top level Image property correctly references the original Image ID.

The existing code compares the name given in the Ansible configuration to the Config->Image property. So, if that image is updated, the Docker module will fail to relaunch the instance with the newly updated image, because the name has not changed. If it were to instead look up the ID that image name refers to and compare it to the top-level Image property, it would correctly recreate the container.

I think that behavior is likely to be very confusing - you'll have a newly downloaded image, but no running containers will have restarted to use it. This will happen whether the image is updated via the module or updated manually. I think this COULD be considered a Docker bug, but I think they would likely call that intended behavior.

I believe the correct thing to do would be to look up the current ID for a given image name and compare that to the top-level Image property for the container when deciding whether to recreate the container.

**Comment by discordianfish** [comment]
@iragsdale Maybe I missed something, but this is not suppose to touch a running container. It will only make sure to pull the latest image _before_ creating/running a new container. If you want to upgrade your container, you still need to remove it first.

**Comment by iragsdale** [comment]
Hmm, the current code _does_ recreate the container _if_ the image it was started with is named differently than the image specified in Ansible. Seems to me that it would be confusing if it didn't do that when the tag changed - otherwise you could intend to have a set of containers running the same image but actually running different images.

Perhaps it would make sense to have a separate flag that enables/disables the restart behavior? I'm really not sure what makes the most sense semantically, and maybe this is a feature request and not a bug.

**Comment by iragsdale** [comment]
Either way the issue is not really in your PR, just potentially exposed by it. I should probably open a new issue with Ansible about the issue. :)

**Comment by iragsdale** [comment]
New issue opened - I'd consider this to be at least somewhat related: #8905.

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
