### PR TITLE
Host dev upstream

### PR DESCRIPTION
**Pull request by ndswartz**
##### SUMMARY
Add host type strings for windows, windows cluster, linux and vmware to netapp_e_host module
Fix port removal and default group.
Fix port reassignment in netapp_e_host module.
Fix port iqn and wwpn case issue

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/storage/netapp/netapp_e_host.py`

##### ADDITIONAL INFORMATION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/swartzn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/swartzn/ansible-dev/lib/ansible
  executable location = /home/swartzn/ansible-dev/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

### CODE REVIEW

**Comment by lmprice** [comment]
I ran into one of these bugs today through general use. I'd like to see this one get merged.

**Comment by anshulbehl** [comment]
@ndswartz  can you take a look at the conflicts in this PR?

**Comment by ndswartz** [comment]
@anshulbehl Fixed the confict

**Comment by anshulbehl** [comment]
@ndswartz I just checked the coverage for the file changes and it is just 50 percent. The methods valid_host_type, port_on_diff_host, create_host are not covered at all. Would it be possible for you to increase some coverage?

**Comment by ndswartz** [comment]
@anshulbehl I have updated and added the unit test. Thanks for point it out, they really need to be rewritten.

**Comment by anshulbehl** [comment]
shipit

**Pull request merged**
