### PR TITLE
Disable flakey `win_msg` integration test.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Disable flakey `win_msg` integration test.

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

win_msg integration test

##### ANSIBLE VERSION

```
ansible 2.5.0 (test-win-msg efde5da4d3) last updated 2017/11/22 14:16:07 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

### CODE REVIEW

**Comment by mattclay** [comment]
The `win_msg` integration test frequently fails due to the module returning earlier than expected. This seems to occur frequently on the first run and then succeed on the retry, as seen here:

https://app.shippable.com/github/ansible/ansible/runs/45200/8/console

The first pass reports:

```
2017-11-22 21:54:57 TASK [win_msg : Warn user and wait for it] *************************************
2017-11-22 21:54:59 changed: [windows-2012-RTM] => {"changed": true, "display_seconds": 5, "msg": "Keep calm and carry on.", "rc": 0, "runtime_seconds": 0.1514106, "sent_localtime": "Wednesday, November 22, 2017 9:54:58 PM", "wait": true}
```

The retry returns:

```
2017-11-22 21:55:04 TASK [win_msg : Warn user and wait for it] *************************************
2017-11-22 21:55:19 changed: [windows-2012-RTM] => {
2017-11-22 21:55:19     "changed": true, 
2017-11-22 21:55:19     "display_seconds": 5, 
2017-11-22 21:55:19     "msg": "Keep calm and carry on.", 
2017-11-22 21:55:19     "rc": 0, 
2017-11-22 21:55:19     "runtime_seconds": 13.7284987, 
2017-11-22 21:55:19     "sent_localtime": "Wednesday, November 22, 2017 9:55:19 PM", 
2017-11-22 21:55:19     "wait": true
2017-11-22 21:55:19 }
```

**Comment by dagwieers** [comment]
Do we already have an issue opened for this so we can look at fixing this ?

cc: @jborean93

**Comment by mattclay** [comment]
None that I'm aware of.

**Comment by dagwieers** [comment]
I'll let @jborean93 decide. I just did not want to loose the opportunity to fix the root-cause, as it may affect other users as well (maybe in corner-cases that may be harder to reproduce).

**Comment by jborean93** [comment]
I haven't seen this before and wasn't aware the tests were problematic.

**Pull request merged**
