### PR TITLE
Contributing new module to manage HUAWEI data center CloudEngine switch.

### PR DESCRIPTION
**Pull request by JackyGao2016**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

cloudengine/ce(network module)

##### ANSIBLE VERSION

```
ansible 2.3.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansible-2.1.1.0/lib/ansible/modules/core/network/cloudengine', '/home/ansible-2.1.1.0/lib/ansible/module_utils', '/home/ansible-2.1.1.0/lib/ansible/modules', '/home/ansible-2.1.1.0', '/home/ansible-2.1.1.0/lib/ansible/utils/']
```

##### SUMMARY

Add HUAWEI CloudEngine switch  ansible  module.
HUAWEI CloudEngine switch is for data center network.
This is the first time HUAWEI would like contributing module code.

```
(1) ce_command:

# ansible -m ce_command -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 commands="display device"' localhost --connection local
localhost | SUCCESS => {
    "changed": false, 
    "stdout": [
        "Device status:\n--------------------------------------------------------------------------------\nSlot  Card   Type                     Online   Power Register     Alarm     Primary        \n--------------------------------------------------------------------------------\n2     -      CE7850-32Q-EI            Present  On    Registered   Normal    Master         \n      FAN1   FAN-40EA-F               Present  On    Registered   Abnormal  NA             \n      PWR1   PAC-600WA-F              Present  On    Registered   Normal    NA             \n--------------------------------------------------------------------------------"
    ], 
    "stdout_lines": [
        [
            "Device status:", 
            "--------------------------------------------------------------------------------", 
            "Slot  Card   Type                     Online   Power Register     Alarm     Primary        ", 
            "--------------------------------------------------------------------------------", 
            "2     -      CE7850-32Q-EI            Present  On    Registered   Normal    Master         ", 
            "      FAN1   FAN-40EA-F               Present  On    Registered   Abnormal  NA             ", 
            "      PWR1   PAC-600WA-F              Present  On    Registered   Normal    NA             ", 
            "--------------------------------------------------------------------------------"
        ]
    ], 
    "warnings": []
}


(2) ce_config:

# ansible -m ce_config -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 before="undo acl 2000" parents="acl 2000" lines="rule 10 permit source 1.1.1.1 32,rule 20 permit source 2.2.2.2 32,rule 30 permit source 3.3.3.3 32,rule 40 permit source 4.4.4.4 32,rule 50 permit source 5.5.5.5 32" match=exact' localhost --connection local
localhost | SUCCESS => {
    "changed": true, 
    "updates": [
        "undo acl 2000", 
        "acl 2000", 
        "rule 10 permit source 1.1.1.1 32", 
        "rule 20 permit source 2.2.2.2 32", 
        "rule 30 permit source 3.3.3.3 32", 
        "rule 40 permit source 4.4.4.4 32", 
        "rule 50 permit source 5.5.5.5 32"
    ], 
    "warnings": []
}

(3) ce_facts:

# ansible -m ce_facts -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 gather_subset=interfaces' localhost --connection local
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_net_all_ipv4_addresses": [
            "*down: administratively down", 
            "!down: FIB overload down", 
            "^down: standby", 
            "(l): loopback", 
            "(s): spoofing", 
            "(d): Dampening Suppressed", 
            "The number of interface that is UP in Physical is 9", 
            "The number of interface that is DOWN in Physical is 8", 
            "The number of interface that is UP in Protocol is 8", 
            "The number of interface that is DOWN in Protocol is 9", 
            "Interface                   IP Address/Mask    Physical Protocol VPN           ", 
            "40GE2/0/18                  unassigned         down     down     --            ", 
            "Eth-Trunk1                  172.16.103.2/24    *down    down     --            ", 
            "Ethernet2/0/0               unassigned         up       down     --            ", 
            "LoopBack0                   4.4.4.9/32         up       up(s)    --            ", 
            "LoopBack1                   unassigned         up       up(s)    --            ", 
            "LoopBack2                   unassigned         up       up(s)    --            ", 
            "LoopBack3                   unassigned         up       up(s)    --            ", 
            "LoopBack99                  unassigned         up       up(s)    --            ", 
            "LoopBack100                 unassigned         up       up(s)    --            ", 
            "MEth0/0/0                   192.109.130.10/24  up       up       --            ", 
            "NULL0                       unassigned         up       up(s)    --            ", 
            "Tunnel100                   unassigned         down     down     --            ", 
            "Tunnel200                   unassigned         down     down     --            ", 
            "Vbdif100                    unassigned         down     down     --            ", 
            "Vlanif4001                  unassigned         down     down     js            ", 
            "Vlanif4002                  unassigned         down     down     --            ", 
            "Vlanif4003                  unassigned         down     down     js2           "
        ], 
        "ansible_net_gather_subset": [
            "interfaces"
        ], 
        "ansible_net_interfaces": [
            "", 
            "Interface                  PHY      Protocol  InUti OutUti   inErrors  outErrors", 
            "40GE2/0/1                  down     down         0%     0%          0          0", 
            "40GE2/0/2                  down     down         0%     0%          0          0", 
            "40GE2/0/3                  down     down         0%     0%          0          0", 
            "40GE2/0/4                  down     down         0%     0%          0          0", 
            "40GE2/0/5                  down     down         0%     0%          0          0", 
            "40GE2/0/6                  down     down         0%     0%          0          0", 
            "40GE2/0/7                  down     down         0%     0%          0          0", 
            "40GE2/0/8                  up       up        0.01%  0.01%          0          0", 
            "40GE2/0/9                  down     down         0%     0%          0          0", 
            "40GE2/0/10                 down     down         0%     0%          0          0", 
            "40GE2/0/11                 down     down         0%     0%          0          0", 
            "40GE2/0/12                 down     down         0%     0%          0          0", 
            "40GE2/0/13                 down     down         0%     0%          0          0", 
            "40GE2/0/14                 down     down         0%     0%          0          0", 
            "40GE2/0/15                 down     down         0%     0%          0          0", 
            "40GE2/0/16                 down     down         0%     0%          0          0", 
            "40GE2/0/17                 down     down         0%     0%          0          0", 
            "40GE2/0/18                 down     down         0%     0%          0          0", 
            "40GE2/0/19                 down     down         0%     0%          0          0", 
            "40GE2/0/20                 down     down         0%     0%          0          0", 
            "40GE2/0/21                 down     down         0%     0%          0          0", 
            "40GE2/0/22                 down     down         0%     0%          0          0", 
            "40GE2/0/23                 down     down         0%     0%          0          0", 
            "40GE2/0/24                 down     down         0%     0%          0          0", 
            "40GE2/0/25                 down     down         0%     0%          0          0", 
            "40GE2/0/26                 down     down         0%     0%          0          0", 
            "40GE2/0/27                 down     down         0%     0%          0          0", 
            "40GE2/0/28                 down     down         0%     0%          0          0", 
            "40GE2/0/29                 down     down         0%     0%          0          0", 
            "40GE2/0/30                 down     down         0%     0%          0          0", 
            "40GE2/0/31                 down     down         0%     0%          0          0", 
            "40GE2/0/32                 down     down         0%     0%          0          0", 
            "Eth-Trunk1                 *down    down         0%     0%          0          0", 
            "Eth-Trunk3                 down     down         0%     0%          0          0", 
            "Eth-Trunk17                down     down         0%     0%          0          0", 
            "Eth-Trunk100               down     down         0%     0%          0          0", 
            "Eth-Trunk112               down     down         0%     0%          0          0", 
            "Eth-Trunk115               down     down         0%     0%          0          0", 
            "Eth-Trunk116               down     down         0%     0%          0          0", 
            "Eth-Trunk117               down     down         0%     0%          0          0", 
            "Eth-Trunk118               down     down         0%     0%          0          0", 
            "Ethernet2/0/0              up       down         0%     0%          0          0", 
            "FCoE-Port1                 down     down         0%     0%          0          0", 
            "LoopBack0                  up       up(s)        0%     0%          0          0", 
            "LoopBack1                  up       up(s)        0%     0%          0          0", 
            "LoopBack2                  up       up(s)        0%     0%          0          0", 
            "LoopBack3                  up       up(s)        0%     0%          0          0", 
            "LoopBack99                 up       up(s)        0%     0%          0          0", 
            "LoopBack100                up       up(s)        0%     0%          0          0", 
            "MEth0/0/0                  up       up        0.01%  0.01%          0          0", 
            "NULL0                      up       up(s)        0%     0%          0          0", 
            "Nve1                       up       up           --     --          0          0", 
            "Nve2                       up       up           --     --          0          0", 
            "Tunnel100                  down     down         --     --          0          0", 
            "Tunnel200                  down     down         --     --          0          0", 
            "Vbdif100                   down     down         --     --          0          0", 
            "Vlanif4001                 down     down         --     --          0          0", 
            "Vlanif4002                 down     down         --     --          0          0", 
            "Vlanif4003                 down     down         --     --          0          0"
        ], 
        "ansible_net_neighbors": [
            "Local Interface         Exptime(s) Neighbor Interface      Neighbor Device     ", 
            "-------------------------------------------------------------------------------", 
            "40GE2/0/8                     101  40GE1/0/8               liubiao_130.9"
        ], 
        "execute_time": "0:00:02.352330"
    }, 
    "changed": false
}

(4) ce_netconf:

# ansible -m ce_netconf -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 rpc=get cfg_xml="<filter type=\"subtree\"><vlan xmlns=\"http://www.huawei.com/netconf/vrp\" content-version=\"1.0\" format-version=\"1.0\"><vlans><vlan><vlanId>10</vlanId><vlanif><ifName></ifName><cfgBand></cfgBand><dampTime></dampTime></vlanif></vlan></vlans></vlan></filter>" ' localhost --connection local
localhost | SUCCESS => {
    "changed": false, 
    "end_state": {
        "result": [
            "", 
            "    <vlan xmlns=\"http://www.huawei.com/netconf/vrp\" format-version=\"1.0\" content-version=\"1.0\">", 
            "      <vlans>", 
            "        <vlan>", 
            "          <vlanId>10</vlanId>", 
            "        </vlan>", 
            "      </vlans>", 
            "    </vlan>", 
            "  "
        ]
    }, 
    "execute_time": "0:00:02.806378"
}

(5) ce_vlan:

# ansible -m ce_vlan -a 'host=10.135.182.157 port=12347 username=rootDC password=Admin@123 vlan_id="50" name="WEB" state="present"' localhost --connection local
localhost | SUCCESS => {
    "changed": true, 
    "end_state": {
        "description": "VLAN 0050", 
        "name": "WEB", 
        "vlan_id": "50"
    }, 
    "end_state_vlans_list": [
        "48", 
        "49", 
        "50", 
        "51", 
        "52", 
        "53", 
        "54"
    ], 
    "execute_time": "0:00:04.110801", 
    "existing": {
        "description": "VLAN 0050", 
        "name": "", 
        "vlan_id": "50"
    }, 
    "existing_vlans_list": [
        "48", 
        "49", 
        "50", 
        "51", 
        "52", 
        "53", 
        "54"
    ], 
    "proposed": {
        "description": null, 
        "name": "WEB", 
        "vlan_id": "50"
    }, 
    "proposed_vlans_list": [
        "48", 
        "49", 
        "50", 
        "51", 
        "52", 
        "53", 
        "54"
    ], 
    "updates": [
        "vlan 50", 
        "name WEB"
    ]
}
```

### CODE REVIEW

**Comment by JackyGao2016** [comment]
HUAWEI data center switch introduce:  http://e.huawei.com/us/products/enterprise-networking/switches/data-center-switches

**Comment by privateip** [comment]
Please only one module per PR request.

**Comment by gundalow** [comment]
The first PR should contain
module_utils/cloudengine.py
cloudengine/_init_.py
lib/ansible/utils/module_docs_fragments/cloudengine.py (for common arguments, which are defined in module_utils/cloudengine.py)

and a single module.

Once that's reviewed and merged you can raise PRs for the following modules (one module per PR)

**Comment by JackyGao2016** [comment]
I will add module_docs_fragments/cloudengine.py" and raise PRs for a module.
Thanks all.

**Pull request closed without merging**
