### PR TITLE
Change yes to true to match Ansible's own recommendation

### PR DESCRIPTION
**Pull request by ghost**
##### Ansible recommends using true over yes 

https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#truthiness

`Use lowercase ‘true’ or ‘false’ for boolean values in dictionaries if you want to be compatible with default yamllint options.`

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### SUMMARY

Ansible recommends using true/false over yes/no in order to be in keeping with yaml linting--this embodies that recommendation in the documentation for become 

https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#truthiness

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
Documentation

### CODE REVIEW

**Comment by webknjaz** [comment]
> `Use lowercase ‘true’ or ‘false’ for boolean values in dictionaries if you want to be compatible with default yamllint options.`

Looks like you misinterpreted this a bit. We don't want to force people to use one thing or another.

The key part of that advice is
> **if you want to be compatible with default yamllint options.**

But if you don't enforce a specific style using `yamllint` software, feel free to use whatever communicates your intent best in every specific case.

**Comment by tjnpbc** [comment]
Yes I understand it is optional, but perhaps by using the yamllint aligned option in documentation, it would make it easier for people new to ansible to have already have adopted the preferred format.

**Comment by webknjaz** [comment]
> it would make it easier for people new to ansible to have already have adopted the preferred format.

All of the module docs use "yes" / "no" for boolean fields. For example:
https://docs.ansible.com/ansible/devel/collections/ansible/builtin/assemble_module.html#ansible-collections-ansible-builtin-assemble-module.

If we were to make the docs consistent, we'd have to use "yes" / "no" everywhere, not "true" / "false".

**Comment by webknjaz** [comment]
FWIW let's see what @acozine from the docs team has to say about this. I've requested a review from her.

**Comment by samdoran** [comment]
I believe we decided to use `yes`/`no` for booleans in Ansible docs. I agree with @webknjaz's statements above: the docs are suggesting to use `true`/`false` only if you are using `yamllint`. But in Ansible land, we prefer the more readable `yes`/`no`.

To discuss this further, please reach out on IRC:

   * IRC: #ansible-docs on irc.freenode.net

**Comment by acozine** [comment]
@tjnpbc thanks for the PR. As you can see, there is still some debate about the best usage for boolean values in Ansible. The docs do say to use yes/no `if you want to be compatible with default yamllint options,` but we do not generally recommend using yamllint with defaults. This is something we should clarify so we can be consistent moving forward. If you'd like to be part of the conversation, we will likely put this on the [Docs Working Group agenda](https://github.com/ansible/community/issues/579). For general information on the Docs Working Group, see [our wiki page](https://github.com/ansible/community/wiki/Docs).

**Pull request closed without merging**
