### PR TITLE
pids: case insensitive string comparison for process names

### LINKED ISSUE #52563: pids is returning empty list for existing running process
SUMMARY
pids returns empty list for existing process in running state.

ISSUE TYPE
- Bug Report

COMPONENT NAME
pids

ANSIBLE VERSION
ansible 2.8.0.dev0

OS / ENVIRONMENT
Windows 10 x64 
Bug is valid for all OS it is supported on.

STEPS TO REPRODUCE
1. Pass "SVCHOST.exe" <case sensitive> to pids to get the respective PIDs of the process.

EXPECTED RESULTS
[PID]

ACTUAL RESULTS
[]

### PR DESCRIPTION
**Pull request by CodeAbyss**
SUMMARY
"Fixes #52563"

ISSUE TYPE
- Bugfix Pull Request

COMPONENT NAME
pids

ADDITIONAL INFORMATION
This fix will compare the user input process name and psutil returned process name with case insensitiveness. This will make the pids component more robust and usable.

### CODE REVIEW

**Comment by Akasurde** [comment]
@CodeAbyss Thanks for the PR. There is failure in CI test case

```
03:14 The full traceback is:
03:14 Traceback (most recent call last):
03:14   File "/root/.ansible/tmp/ansible-tmp-1550575112.41-156319241715644/AnsiballZ_pids.py", line 128, in <module>
03:14     _ansiballz_main()
03:14   File "/root/.ansible/tmp/ansible-tmp-1550575112.41-156319241715644/AnsiballZ_pids.py", line 120, in _ansiballz_main
03:14     invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
03:14   File "/root/.ansible/tmp/ansible-tmp-1550575112.41-156319241715644/AnsiballZ_pids.py", line 63, in invoke_module
03:14     imp.load_module('__main__', mod, module, MOD_DESC)
03:14   File "/tmp/ansible_pids_payload_kgIbrv/__main__.py", line 74, in <module>
03:14   File "/tmp/ansible_pids_payload_kgIbrv/__main__.py", line 69, in main
03:14   File "/tmp/ansible_pids_payload_kgIbrv/__main__.py", line 56, in get_pid
03:14 AttributeError: 'NoneType' object has no attribute 'lower'
03:14 
03:14 fatal: [testhost]: FAILED! => {
03:14     "changed": false, 
03:14     "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1550575112.41-156319241715644/AnsiballZ_pids.py\", line 128, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1550575112.41-156319241715644/AnsiballZ_pids.py\", line 120, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1550575112.41-156319241715644/AnsiballZ_pids.py\", line 63, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_pids_payload_kgIbrv/__main__.py\", line 74, in <module>\n  File \"/tmp/ansible_pids_payload_kgIbrv/__main__.py\", line 69, in main\n  File \"/tmp/ansible_pids_payload_kgIbrv/__main__.py\", line 56, in get_pid\nAttributeError: 'NoneType' object has no attribute 'lower'\n", 
03:14     "module_stdout": "", 
03:14     "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
03:14     "rc": 1
03:14 }

```

**Comment by CodeAbyss** [comment]
@Akasurde It seems the tests have again generated an "AttributeError" error. Can you kindly review the code? I am not able to find the bug. I have alreday put a check 'bool(name)' in place to avoid the call to "NoneType".lower().

**Comment by Akasurde** [comment]
@CodeAbyss Want to try this - 

```python
    return [p.info['pid'] for p in psutil.process_iter(attrs=['pid', 'name']) if p.info and p.info.get('name', None) and p.info['name'].lower() == name.lower()]
```

**Review by Akasurde — APPROVED** [review]
LGTM

**Review by themr0c — APPROVED** [review]

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@CodeAbyss Can you please squash your commits to get rid of the `Thanks to @Akasurde for suggestion :)` change to `Thanks to Akasurde for suggestion :)` (without `@`)

The reason for this is GitHub will send him an email every time someone merges this

**Comment by CodeAbyss** [comment]
@gundalow I might sound naive, but I don't know how to squash the commits. I searched, but all of them are telling cmd line params for git. Can you guide me on how to do this on GitHub?

**Comment by Akasurde** [comment]
@CodeAbyss You need to following 

1. You have 5 commits

```
* 755e839e4d - (HEAD -> patch-2, CodeAbyss/patch-2) Removed Whitespaces (5 days ago) <abyss> GitHub
* 9290e7b151 - Fixed "AttributeError" for 'NoneType'.lower() (5 days ago) <abyss> GitHub
* 5966f77172 - Fixed "AttributeError" for 'None' process name (6 days ago) <abyss> GitHub
* 5818be60cf - Fixed 'AttributeError' for lower() (6 days ago) <abyss> GitHub
* 549ff8bfb4 - case insensitive string comparison for process names (6 days ago) <abyss> GitHub
```
2. git rebase -i HEAD~5  - This will rebase your branch (squashing)

```
pick 549ff8bfb4 case insensitive string comparison for process names
squash 5818be60cf Fixed 'AttributeError' for lower()
squash 5966f77172 Fixed "AttributeError" for 'None' process name
squash 9290e7b151 Fixed "AttributeError" for 'NoneType'.lower()
squash 755e839e4d Removed Whitespaces
```

3. Save your changes and amend commit message where it says name in commit message. 

4. git push origin patch-2 --force

You can read about interactive rebase here - https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history and https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by Akasurde** [comment]
@CodeAbyss Any news ? Let me know if you want me to take over this PR and get it merged. Thanks.

**Comment by CodeAbyss** [comment]
@Akasurde I have followed the steps as per your instructions & below are the details. Kindly have a look::
```
git log
commit ef523e10a86281211b602a896d58c4a4b3a37d53 (HEAD -> devel)
Author: abyss
Date:   Tue Feb 19 16:40:27 2019 +0530
    case insensitive string comparison for process names
    Fixed 'AttributeError' for lower()
    Fixed "AttributeError: 'NoneType' object has no attribute 'lower'" error for "Empty" or None strings passed as process name.
    Fixed "AttributeError" for 'None' process name
    Fixed "AttributeError" for object 'NoneType' while calling lower() on the returned process info from psutil's process_iter.
    Thanks to Akasurde for suggestion :)
    Fixed "AttributeError" for 'NoneType'.lower()
    Added check on p.info and p.info['name'] to check if they are Empty or None, and then calling lower() on them.
    The older commit message contained the mentions, so commiting new with changed commit message.
    Removed Whitespaces
    Removed whitespaces. Added them earlier to amend the previous commit message.

git push origin patch-2 --force
Everything up-to-date

git push
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 953 bytes | 476.00 KiB/s, done.
Total 7 (delta 5), reused 1 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/CodeAbyss/ansible.git
   57d85031d7..ef523e10a8  devel -> devel
```

Is that it or do I have to create a new PR?

**Pull request merged**
