### PR TITLE
ec2_instance: Added SG handling for existing instances

### LINKED ISSUE #54174: ec2_instance cannot add or remove addition security groups
##### SUMMARY
I have an existing ec2 instance where I would like to add an addition security group.  
When I add one more security group, `ec2_instance` doesn't notify any change.

```
TASK [try to modify the ec2 instance] ********************************************************************************************************************************************************
ok: [localhost]
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`ec2_instance`

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = None
  configured module search path = ['/home/m/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/m/.local/lib/python3.7/site-packages/ansible
  executable location = /home/m/.local/bin/ansible
  python version = 3.7.2 (default, Mar 20 2019, 08:51:28) [GCC 8.2.0]

```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$ 

```

##### OS / ENVIRONMENT

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Pop!_OS 18.10"
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  
  vars_prompt:
    - name: ec2_template
      prompt: Which ec2 template file?
      private: no
      default: mbtest190321.my.instance.de

  vars_files:
    - "vars/{{ ec2_template }}.yml"

  tasks:

    ###################################
    #
    # check if instance exists already
    ###################################
    - name: check if instance already exists
      include_role:
        name: start_stop_terminate
        tasks_from: find_instance_id

    ###################################
    # if exists     when: instance.instances | count == 1
    # try update using ec2_instance module
    ###################################
    - name: try to modify the ec2 instance
      ec2_instance:
        state: present
        name: "{{ ec2_template }}"
        instance_ids: "{{ instance.instances[0].instance_id }}"
        security_groups: "{{ security_group }}"
        cpu_credit_specification: "{{ cpu_credit_specification }}"
        ebs_optimized: "{{ ebs_optimized }}"
        detailed_monitoring: "{{ detailed_monitoring }}"
        purge_tags: no
      when: instance.instances | count == 1
```

```yml
---
instance_type: t2.medium
cpu_credit_specification: standard
ebs_optimized: no
detailed_monitoring: no
security_group: 
  - default
  - something_other
```

##### EXPECTED RESULTS

cc @ryansb  

In case of `instance.instances[0].security_groups != security_groups` it should apply the changes.

```
TASK [try to modify the ec2 instance] ********************************************************************************************************************************************************
changed: [localhost]
```

Basically is must be `aws ec2 modify-instance-attribute --groups <list of {{security_groups}} --instance-id <instance_id>`

##### ACTUAL RESULTS

No changes are detected and nothing happen.

### PR DESCRIPTION
**Pull request by Shaps**
##### SUMMARY
This fixes the issue below, where security groups were not changed if the instance already existed.
Added some small cleanup as well

Fixes #54174
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ec2_instance.py

### CODE REVIEW

**Review by s-hertel — COMMENTED** [review]
It would also be good for this PR if the integration tests were fixed. This should have tests added so it isn't broken in the future.

**Comment by Shaps** [comment]
@s-hertel yep, that's sensible, I'll add the tests and update

**Comment by ciniglio** [comment]
@willthames is there something that we could do to help? This issue affects my team too and I'd be happy to spend some time on it if we can help get it merged.

**Comment by Shaps** [comment]
@ciniglio I have been working in the background to make it possible for the tests to run in CI, once #56313 is merged I'll re-run the tests and we should be confident enough to merge this

**Comment by tekkno89** [comment]
Hi! Just curious on what the status is for this PR?

**Comment by LuciferOmen** [comment]
any update on this PR?

**Comment by Xyrion** [comment]
Any update here?

**Comment by briantist** [comment]
With #563313 merged, would love to know if you're able to get this working. Any update @Shaps ?

**Comment by briantist** [comment]
Also FYI in local testing I've found that changing the SGs doesn't happen consistently if you also set `state`, depending on what the current and desired state is. I actually wrote this down (on paper) and won't have it with me to confirm until next week but IIRC the issues look like this:

❌ = SGs don't get updated | ✅ = SGs do get updated
---|---


Current State | Desired State | Behavior
---|---|---
Stopped | Stopped | ❌
Stopped | Started | ❌
Started | Stopped | ❌
Started | Started | ✅

**Comment by jokajak** [comment]
> Also FYI in local testing I've found that changing the SGs doesn't happen consistently if you also set `state`, depending on what the current and desired state is. Omitting the state option works regardless of the instance's current state.
> ❌ = SGs don't get updated 	✅ = SGs do get updated
> Current State 	Desired State 	Behavior
> Stopped 	Stopped 	❌
> Stopped 	Started 	❌
> Started 	Stopped 	❌
> Started 	Started 	✅

I think that this should be tracked as a separate ticket/enhancement rather than trying to fix it under the current effort.

**Comment by briantist** [comment]
> > Also FYI in local testing I've found that changing the SGs doesn't happen consistently if you also set `state`, depending on what the current and desired state is. Omitting the state option works regardless of the instance's current state.
> > ❌ = SGs don't get updated 	✅ = SGs do get updated
> > Current State 	Desired State 	Behavior
> > Stopped 	Stopped 	❌
> > Stopped 	Started 	❌
> > Started 	Stopped 	❌
> > Started 	Started 	✅
> 
> I think that this should be tracked as a separate ticket/enhancement rather than trying to fix it under the current effort.

Since the existing module doesn't update SGs for existing instances at all, there's nowhere else to track it really, as it's a bug that only affects the code in this PR specifically.

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
