### PR TITLE
Added ignore_errors silently option

### PR DESCRIPTION
**Pull request by rgarrigue**
on_failed tweak to add ignore_errors: silently choice, that will output a short cyan message in case of a failure

### CODE REVIEW

**Comment by mpdehaan** [comment]
Testing this now, thanks!

**Comment by mpdehaan** [comment]
This is still showing full output for me with the following playbook:

```
- hosts: all

  tasks:
    - shell: /bin/false
      ignore_errors: silently
```

**Comment by rgarrigue** [comment]
Sorry for the answer delay.

Thruth is, I've only though about my own case. I'll resume work on this once I get a better grasp of git so I'm able to branch/push/whatever.

**Comment by mpdehaan** [comment]
I'm going to close this one given no updates, but am open to additions.  I also recall seeing a related item in the PR queue so this _MAY_ have another implementation already, I'll look.

Thanks!

**Comment by rgarrigue** [comment]
Sorry if that's not clear. I made another PR with an updated version and referenced this one from ther newer one. Shortly said, ok to close this one, look at #5667 instead.

**Pull request closed without merging**
