### PR TITLE
remove some instances of `state: installed` from examples

### LINKED ISSUE #47869: Change remaining examples of "state: installed" to "state: present"
##### SUMMARY
Using `state: installed` is deprecated: 

`[DEPRECATION WARNING]: State 'installed' is deprecated. Using state 'present' instead.. This feature will be removed in version 2.9. `

PR #47267 fixed many instances of this, but there are a few left - one on a Windows page:
```
[alicia@tooticky]~/git_repos/ansible/docs/docsite/rst$ grep -rl "state: installed" ./
.//user_guide/windows_usage.rst
```

and four in the module examples:
```
swdepot_module
bigip_software_install_module
nmcli_module
bigip_ucs_module
```

Update these references to use `state: present` and re-test examples.

Related to #47202.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docs.ansible.com

##### ANSIBLE VERSION
2.8

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

### PR DESCRIPTION
**Pull request by netzvieh**
##### SUMMARY

This fixes the examples in multiple modules so they use `state: present`
instead of `state: installed`.

fix Partially  #47869

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

nmcli_module
swdepot_module
async_status_module

### CODE REVIEW

**Comment by netzvieh** [comment]
The other occurences of 'state: installed' are in `bigip_ucs_module`, `bigip_software_install_module` and a `windows_usage` guide.

The `windows_usage` guide references the `windows_update_module`, which has `installed` and `searched` as possible values for `state`.

`bigip_ucs_module` differentiates between `installed` and `present` for the `state` parameter:

     When C(installed), ensures that the UCS is uploaded and installed,
        on the system. When C(present), ensures that the UCS is uploaded.

`bigip_software_installed_module` has only `installed` and `activated` as possible values.

Since those aren't in scope for the deprecation afaict, they should be able to remain.

**Comment by goneri** [comment]
This documentation also mention the `installed` state: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/playbooks_environment.rst
It would also be nice to modify it to make use of the generic `package` module instead of `apt`.

**Comment by netzvieh** [comment]
Hi @goneri, thanks for the note, I changed those and also switched to yaml syntax in the example

**Comment by acozine** [comment]
Thanks @netzvieh and @goneri for reviewing the docs so carefully. If you're interested in docs, I encourage you to join the Ansible Docs Working Group on the #ansible-docs channel of freenode IRC. See https://github.com/ansible/community/wiki/Docs for more info.

**Pull request merged**
