### PR TITLE
update play_context for reset_connection (#40866)

### PR DESCRIPTION
**Pull request by bcoca**
steps taken from lib/ansible/executor/task_executor.py

fixes: https://github.com/ansible/ansible/issues/27520
(cherry picked from commit 23fbe0ce8e942427ed602e90caa744f07f978d6c)

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

meta: reset_connection
##### ANSIBLE VERSION

```
>=2.5
```

### CODE REVIEW

**Comment by jamescassell** [comment]
Thanks for merging my fix for this!  I'm eager to see it in a release, as it is a severe bug for us.

**Comment by epu** [comment]
Looks like checks passed, patch needs merging.

**Comment by jamescassell** [comment]
Thanks for getting it merged.  I guess I should open the backport PR myself if I want to appear in the git history?

**Comment by bcoca** [comment]
nah, i cherry picked, so it kept attribution

**Comment by epu** [comment]
<3 thanks team!

**Pull request merged**
