### PR TITLE
Python3 issues in maven_artifact

### LINKED ISSUE #33761: maven_artifact Python3 Support
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/joellow/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

Generated by Packer. Nothing specific, except specifying `ansible_python_interpreter=/usr/bin/python3` as required.

##### OS / ENVIRONMENT

macOS El Capitan, managing Ubuntu 16.04 with default Python3 runtime (3.5.2)

##### SUMMARY

Cannot use `maven_artifact` with python3 on managed host.

##### STEPS TO REPRODUCE

```yaml
  maven_artifact:
    group_id: "{{ item.group_id }}"
    artifact_id: "{{ item.artifact_id }}"
    version: "{{ item.version }}"
    repository_url: <url>
    extension: hpi
    dest: "/path/to/dir/{{ item.group_id }}.{{ item.artifact_id }}-{{ item.version }}.hpi"
    group: root
    owner: root
    mode: 0644
```

##### EXPECTED RESULTS

Should succeed.

##### ACTUAL RESULTS

Error running the command on the remote. I got one error:

```
failed: [default] (item={u'group_id': u'<group_id>', u'artifact_id': u'<artifact>', u'version': u'<version>'}) => {"changed": false, "item": {"artifact_id": "<artifact>", "group_id": "<group_id>", "version": "<version>"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 499, in <module>\n    main()\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 481, in main\n    if downloader.download(artifact, b_dest):\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 350, in download\n    self._write_chunks(response, f, report_hook=self.chunk_report)\n  File \"/tmp/ansible_58_aoltx/ansible_module_maven_artifact.py\", line 368, in _write_chunks\n    total_size = response.info().getheader('Content-Length').strip()\nAttributeError: 'HTTPMessage' object has no attribute 'getheader'\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

Replacing `getheader` with `get` on line 368 in the Ansible source yields:

```
failed: [default] (item={u'group_id': u'<group_id>', u'artifact_id': u'<artifact>', u'version': u'<version>'}) => {"changed": false, "item": {"artifact_id": "<artifact>", "group_id": "<group_id>", "version": "<version>"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 499, in <module>\n    main()\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 481, in main\n    if downloader.download(artifact, b_dest):\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 350, in download\n    self._write_chunks(response, f, report_hook=self.chunk_report)\n  File \"/tmp/ansible_gs91uuvm/ansible_module_maven_artifact.py\", line 379, in _write_chunks\n    file.write(chunk)\nTypeError: write() argument must be str, not bytes\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

Replacing `open(..., 'w')` with `open(..., 'wb')` on line 348 seems to fix it.

### PR DESCRIPTION
**Pull request by abadger**
Fixes #33761

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
maven_artifact.py

##### ANSIBLE VERSION

```
devel 2.5 2.4
```

### CODE REVIEW

**Comment by tumbl3w33d** [comment]
@abadger [this](https://stackoverflow.com/questions/2665866/what-is-the-wb-mean-in-this-code-using-python) indicates, that writing in binary mode corrupts non-text files on windows. I have no experience with it, just wondered what the `wb` is for and found this.

**Comment by abadger** [comment]
@tumbl3w33d That post means the opposite:  Reading and writing in text mode will corrupt binary files on windows.

In Python2 on UNIX, there's no difference between opening a file in text or binary mode.  On Windows, opening it in text mode will translate \n into \r\n when writing files.  This is somewhat sane for text files as that's the needed Windows end-of-line behaviour.  But if you're dealing with actual binary data or you want to make sure that a text file keeps the end-of-line characters that it already had, then you need to open it in binary mode to prevent that automatic translation of newlines.

**Comment by tumbl3w33d** [comment]
Oh you're right, I got that wrong. Thanks!

**Comment by abadger** [comment]
Fix cherrypicked for 2.5.0rc2 and 2.4.4rc2

**Pull request merged**
