### PR TITLE
Amazon RDS module

### PR DESCRIPTION
**Pull request by bpennypacker**
Here's a module that provides pretty full support for creating and deleting Amazon RDS (Relational Database Service) instances.

### CODE REVIEW

**Comment by lwade** [comment]
@bpennypacker ++

**Comment by mpdehaan** [comment]
Cool!  This is in queue for review and merger when we start 1.3... which is going to start today.

Thanks!

**Comment by lwade** [comment]
@mpdehaan, with more modules coming in for additional AWS services we should probably set some module naming conventions.  E.g. aws_rds aws_ec2 etc.

**Comment by mpdehaan** [comment]
@lwade, I think we can call this rds for now, as I don't want to deal with the concept of aliased module names just yet

@bpennypacker small thing, but I am wondering if we can avoid the "action: foo action=blarg" which is redundant with "action".  Can we change the action parameter to "command" ?

Other than that, this looks good to me.

I also think there may be tab/spacing issue on this line:

```
        port = dict(required=False),
```

**Comment by bpennypacker** [comment]
Sounds like an excellent idea to me.  I don't know why I didn't consider "command" in the first place.  I'll have it updated shortly.

**Comment by mpdehaan** [comment]
Ok I merged this in.

I reformatted the code in some places and made sure to use "choices" in the EXAMPLES section rather than just spelling out the choices.

If you can help test this again post changes, that would be great.

In particular, I noticed it was using choices=BOOLEANS (old way which I am trying to remove everywhere) versus type='bool' so I fixed that, and I think the way you had it would pass a string "yes" to some Amazon functions rather than True or False. 

I don't know if boto made that nice before but you will get real booleans now.

If you need to submit any fixes on top of those changes you can just submit a pull request on top of what is now in the tree.

Thanks!

**Pull request closed without merging**
