### PR TITLE
win_get_url - Fix handling of restricted headers

### LINKED ISSUE #57880: Restricted HTTP headers can not be set on Windows
##### SUMMARY
Restricted HTTP headers can not be set on Windows like:
```
- name: Imagick .dll - download
  win_get_url:
    url: "https://windows.php.net/downloads/pecl/deps/ImageMagick-7.0.7-11-vc15-x64.zip"
    dest: "C:\\php\\imagick_dll.zip"
    timeout: 300
    headers: {"user-agent": "Mozilla/5.0"}
  changed_when: no
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_get_url

##### ANSIBLE VERSION
```
ansible 2.8.1
```
If I remember correctly, in 2.6.x version this bug was not presented.

##### CONFIGURATION
```
default
```

##### OS / ENVIRONMENT
Debian 9.9

##### STEPS TO REPRODUCE
Run the code from summary.

##### EXPECTED RESULTS
File is sucessfuly downloaded and ANY custom HTTP header can be set.

##### ACTUAL RESULTS
The most common HTTP headers can not be set, see https://stackoverflow.com/questions/239725/cannot-set-some-http-headers-when-using-system-net-webrequest . This is quite critical as some providers require HTTP headers like `User-Agent` making the `win_get_url` currently unusable.

What is the best way to overcome it and can this be hotfixed in the next stable release?

### PR DESCRIPTION
**Pull request by ShachafGoldstein**
##### SUMMARY
Fixes: #57880

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_get_url.ps1

### CODE REVIEW

**Comment by jborean93** [comment]
Thanks for doing this so quickly, one thing that would be good to have is some integration tests. It should be as simple as adding some of these special headers to https://github.com/ansible/ansible/blob/devel/test/integration/targets/win_get_url/tasks/tests_url.yml#L185. The httpbin site returns the headers as raw json which you can see by going to https://httpbin.org/headers.

**Comment by jborean93** [comment]
Fantastic looks good as usual. Are you able to raise the backport PR as well?

**Comment by jborean93** [comment]
My bad pressed the wrong button, should be all good now.

**Comment by ShachafGoldstein** [comment]
> Fantastic looks good as usual. Are you able to raise the backport PR as well?

Yeah sure

**Pull request merged**
