### PR TITLE
Adding support for clearlinux showing release number

### PR DESCRIPTION
**Pull request by josuedhg**
Signed-off-by: Josue David Hernandez <josue.d.hernandez.gutierrez@intel.com>

##### SUMMARY
variable ansible_distribution_version shows NA and must show the release number

##### ISSUE TYPE

- Feature Pull Request

##### ANSIBLE VERSION
ansible 2.8.0.dev0

```paste below

```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by josuedhg** [comment]
any update?

**Comment by gundalow** [comment]
@josuedhg Thank you for this. Merged into `devel` for release in Ansible 2.8

If there are any other clearlinux fixes feel free to `@gundalow` in the PR and I'll look at getting them merged

**Comment by josuedhg** [comment]
@gundalow I will create a backport to 2.7 for this

**Comment by josuedhg** [comment]
backported in https://github.com/ansible/ansible/pull/49571

**Pull request merged**
