### PR TITLE
[Docs] Fix old YAML style in async docs

### PR DESCRIPTION
**Pull request by major**
##### SUMMARY
Fix old YAML style in `async` docs

This patch fixes some old-style YAML in the documentation for asynchronous playbooks.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
`async`

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/home/major/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/major/.pyenv/versions/venv-2.x/lib/python2.7/site-packages/ansible
  executable location = /home/major/.pyenv/versions/venv-2.x/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### ADDITIONAL INFORMATION
```
N/A
```

### CODE REVIEW

**Comment by major** [comment]
My editor accidentally removed some unneeded white space as well -- hopefully that's not a deal breaker.

**Review by evrardjp — APPROVED** [review]
I think it's cleaner that way.

**Review by dharmabumstead — APPROVED** [review]
Approved with edits.

**Comment by dharmabumstead** [comment]
Thanks @major!

**Pull request merged**
