### PR TITLE
Zabbix inventory

### PR DESCRIPTION
**Pull request by Filippo125**
##### SUMMARY
Add capability to get vars from zabbix interfaces and inventory.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Zabbix inventory

### CODE REVIEW

**Comment by webknjaz** [comment]
@Filippo125 please rebase your change, it's out-of-sync

**Review by resmo — APPROVED** [review]
shipit

**Comment by resmo** [comment]
LGTM, @D3DeFi  your comment on that?

**Comment by D3DeFi** [comment]
don't have easy way to test this as I am not using Zabbix inventory anywhere, but code looks legit

**Comment by D3DeFi** [comment]
shipit

**Pull request merged**
