### PR TITLE
`docker pull' image instead of building if no path is given

### PR DESCRIPTION
**Pull request by hkariti**
Instead of failing, give the option to pull the image from index.docker.io.

### CODE REVIEW

**Comment by sivel** [comment]
This is great...I was working on an almost identical pull request earlier this morning.

One thing though.  Don't import json.  json is already made available by module_utils/basic.py and handles the case of importing simplejson if needed.

Also, you have mixed use of tabbed indentation and space indentation.  Make sure to use all spaces.  Lines with tabs are 134 and 136.

**Comment by mpdehaan** [comment]
Yep, please fix the tabs above and we can look at merging this in.

**Comment by hkariti** [comment]
I hope I used json right this time..

**Comment by sivel** [comment]
That import will not function in most cases.

There is no need for any import at all. JSON is already available to you without any explicit import. You can just remove that whole import line.

**Comment by hkariti** [comment]
Hm, it worked for me with the import just now. And I'm a bit uncomfortable with the json-is-available-using-magic. But if you say that's the way, alright.

**Comment by sivel** [comment]
Another issue I see here.  It looks like you added a file called `plugins/callbacks/log_json.py` to this branch and pushed it.  Please ensure that you use separate branches for separate features.

The "magic" is due to how modules are built, which I'll keep out of the conversation now, but the import at the bottom of the file enables this.

**Comment by hkariti** [comment]
Whoops. Sorry about that.

**Comment by sivel** [comment]
I've tested, and can confirm things are working as I would expect.

**Comment by sivel** [comment]
I'd like to see this for 1.5, just a heads up that there appears to be pulls to update all modules to require docker-py 0.3.0 so, this pull could require updating depending on which makes it in first.

**Comment by hkariti** [comment]
What kind of updates? Did they change the API?

**Comment by softzilla** [comment]
I have already added 0.3.0 support at #6196.

**Comment by hkariti** [comment]
Had a mess with branches, sent this again with a seperate branch as #6247.

**Pull request closed without merging**
