### PR TITLE
Rename ec2_facts to ec2_metadata_facts

### PR DESCRIPTION
**Pull request by roadmapper**
##### SUMMARY
Renames ec2_facts to ec2_metadata_facts (suggested from changes in #21532).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ec2_facts

##### ANSIBLE VERSION
```
2.4.0
```

### CODE REVIEW

**Comment by roadmapper** [comment]
@ryansb @mattclay @s-hertel For a module rename, does the CHANGELOG need to be updated with the new module name as a "new module"?

**Comment by tedder** [comment]
Will a deprecation notice/pointer remain for the old name? I can see a lot of plays being affected.

**Comment by roadmapper** [comment]
@tedder, yes. ec2_facts will be symlinked to the new ec2_metadata_facts module and the following warning will be displayed on usage of ec2_facts:
`[DEPRECATION WARNING]: The 'ec2_facts' module is being renamed 'ec2_metadata_facts'. This feature will be removed in version 2.7. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

**Comment by mattclay** [comment]
@roadmapper Yes, please add a deprecated modules section to the changelog and mention the old and new module name.

**Review by s-hertel — APPROVED** [review]

**Review by ryansb — APPROVED** [review]

**Pull request merged**
