### PR TITLE
postgresql_schema: permit to drop cascade schema

### PR DESCRIPTION
**Pull request by nerzhul**
##### SUMMARY

Add CASCADE keyword support to remove a schema with child objects

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

postgresql_schema

##### ADDITIONAL INFORMATION

```paste below
ansible 2.7.3.0
```

### CODE REVIEW

**Comment by andytom** [comment]
LGTM

**Comment by andytom** [comment]
shipit

**Comment by Dorn-** [comment]
shipit

**Comment by andytom** [comment]
bot_status

**Pull request merged**
