### PR TITLE
allow using --check on win_iis_webapppool module

### PR DESCRIPTION
**Pull request by tchia04**
##### SUMMARY

Allow using --check on win_iis_webapppool when the app pool has attributes to detect changes instead of failing

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

win_iis_webapppool

##### ADDITIONAL INFORMATION

playbook

    #############################################################
    # Creating application pools
    #############################################################
    - name: Create application pool
      win_iis_webapppool:
        name:                           '{{ item.key }}'
        state: started
        attributes:
          managedRuntimeVersion:        '{{ item.value.managedRuntimeVersion }}'
          startMode:                    '{{ item.value.startMode }}'
          processModel.loadUserProfile: '{{ item.value.processModel_loadUserProfile }}'
          processModel.identityType:    '{{ item.value.processModel_identityType }}'
      with_dict: "{{ apppools }}"

vars file
apppools:
  abc_AppPool:
    managedRuntimeVersion: v4.0
    startMode: AlwaysRunning
    processModel_loadUserProfile: True
    processModel_identityType: NetworkService

```paste below

BEFORE this fix
==============

MSG:

Failed to set attribute to Web App Pool AtTheRegister_AppPool. Attribute: processModel.identityType, Value: NetworkService, Exception: Cannot find path 'IIS:\AppPools\foobar_AppPool' because it does not exist.


PLAY RECAP *****************************************************************************************************************************************************************************
xxxxxxx               : ok=1    changed=0    unreachable=0    failed=1




AFTER this fix
==============

TASK [Create application pool] ***********************************************************************************************************************************************************
changed: [xxxxxx ] => (item={'value': {u'processModel_identityType': u'NetworkService', u'startMode': u'AlwaysRunning', u'managedRuntimeVersion': u'v4.0', u'processModel_loadUserProfile': True}, 'key': u'ThisDoesNotExist_AppPool'})


PLAY RECAP *******************************************************************************************************************************************************************************
xxxxxx : ok=4    changed=1    unreachable=0    failed=0


```

### CODE REVIEW

**Comment by ShachafGoldstein** [comment]
I might be missing something here but your addition just stops the line from ever having the -WhatIf:$check_mode be true and nothing more.

can you elaborate on the issue?

**Comment by tchia04** [comment]
I think the original implementation only works if the app pool already exists and you are adding/updating an  attribute.

In my use case, the app pool doesn't exist so I wanted to run the playbook with --dry-run and see the diff output before the actual run and the -WhatIf:$check_mode didn't work.

**Comment by ShachafGoldstein** [comment]
> I think the original implementation only works if the app pool already exists and you are adding/updating an attribute.
> 
> In my use case, the app pool doesn't exist so I wanted to run the playbook with --dry-run and see the diff output before the actual run and the -WhatIf:$check_mode didn't work.

I can't seem to replicate the problem, can you try running the failing command yourself in powershell and see what happens?

maybe try on another server/website to make sure it is recurring?

**Comment by ShachafGoldstein** [comment]
I see the problem as well, but the fix could be a check if the apppool exist instead ignoring it for all cases.

**Comment by jborean93** [comment]
I've slightly tweaked the logic a bit more to skip even checking attributes on a missing pool in check mode and added a changelog fragment so we can backport it.

**Comment by jborean93** [comment]
Backport PR to stable-2.9 https://github.com/ansible/ansible/pull/64812

**Pull request merged**
