### PR TITLE
Fixup for SuSE and openSuSE.

### PR DESCRIPTION
**Pull request by dirtyharrycallahan**
Account for differences in packages names across RHEL/CentOS
and SuSE/openSuSE.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Comment from user that I'm repasting: 

"""
blumentopf commented just now 

I think there's an issue with your solution (pull request #4689), it breaks support for Fedora and other non-RHEL distros. That's because you replaced the "%if 0%{?rhel} && 0%{?rhel} <= 5 ... %else" statement with one %if statement for RHEL > 5 and another for RHEL <= 5.
"""

**Comment by jctanner** [comment]
@dirtyharrycallahan Please revise this patch to allow for adding dependencies on non-rhel based rpm distros such as fedora. Please rebase your local branch as well, to fix the current merge conflicts with devel.

**Comment by dirtyharrycallahan** [comment]
Reading through the notifications and extending support for Fedora 19 and Ubuntu are doable. I will set up some virtual machines to test the changes. Probably have that done by Wednesday evening.

**Comment by jctanner** [comment]
@dirtyharrycallahan thank you

**Comment by jctanner** [comment]
@dirtyharrycallahan thank you!

**Pull request merged**
