### PR TITLE
[stable-2.10] virt facts: allow guest/host to have >1 virt tech (#70832)

### PR DESCRIPTION
**Pull request by carlosmmatos**
##### SUMMARY
Backport of #70832 for Ansible 2.10
(cherry picked from commit 4e55b93)

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
```
lib/ansible/module_utils/facts/virtual/base.py
lib/ansible/module_utils/facts/virtual/freebsd.py
lib/ansible/module_utils/facts/virtual/hpux.py
lib/ansible/module_utils/facts/virtual/linux.py
lib/ansible/module_utils/facts/virtual/netbsd.py
lib/ansible/module_utils/facts/virtual/openbsd.py
lib/ansible/module_utils/facts/virtual/sunos.py
lib/ansible/module_utils/facts/virtual/sysctl.py
```

### CODE REVIEW

**Comment by sivel** [comment]
As this is a new feature, and 2.10 has now been released, this cannot be backported.

**Comment by carlosmmatos** [comment]
Oh man that stinks.. so is there anyway to get some of the better virtual facts reporting in 2.11+ into 2.9 and 2.10?

**Comment by sivel** [comment]
You can create your own facts modules, or local facts scripts that retrieve this information.  A facts script can live in `/etc/ansible/facts.d` on all hosts, and will automatically be consulted when gathering facts.

**Comment by carlosmmatos** [comment]
I understand - well +1 for @relrod enhancements - but 2.11 is so far away and we are trying to get some better reporting capabilities for our [ComplianceAsCode](https://github.com/ComplianceAsCode/content) repository. Since we currently provide ansible playbooks - not sure we can wrap this functionality into it as of yet. Thanks for the comments!

**Pull request closed without merging**
