### PR TITLE
ios_logging: Adding possibility to configure loging trap

### PR DESCRIPTION
**Pull request by asand3r**
##### SUMMARY
Adding posibility to configure "logging trap".

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ios_logging

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/asand3r/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### ADDITIONAL INFORMATION
Module has no possibility to configure logging trap.
I've make some changes, adding this feature.

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests (in addition to the already noted import tests):

```
test/units/modules/network/ios/test_ios_logging.py:27: in <module>
    from ansible.modules.network.ios import ios_logging
lib/ansible/modules/network/ios/ios_logging.py:134: in <module>
    from ansible.module_utils.network_common import remove_default_spec
E   ImportError: No module named network_common
```

**Comment by asand3r** [comment]
I'm dumb. Trying to make pull request from devel to devel, but should be stable-2.4 to stable-2.4.

**Comment by mattclay** [comment]
@asand3r PRs should be made against devel. If the PR is a bug fix we can cherry pick the changes to stable-2.4.

**Comment by asand3r** [comment]
@mattclay  Hmm, maybe I still don't understand how git works, sorry. OK, could you help me? I've made some changes with one module (ios_logging) and wanna add it to Ansible. Changes has been done with 'devel' branch, which hasn't some libraries (e.g. ansible.modules.network.ios import ios_logging) what Ansibot said. What should I do?

**Comment by asand3r** [comment]
OK, sorry, I'm newby. ) Created one more pull request #33701 and I think it has been formed right.

**Comment by kedarX** [comment]
Rebase your forked repo. Libs are here now `https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/ios/ios.py`

Also, raise a PR from `your_forked_ansible_repo:your_branch` to `ansible:devel`

Read http://docs.ansible.com/ansible/latest/dev_guide/developing_modules.html

and feel to connect on #ansible-network channel on freenode IRC

**Pull request closed without merging**
