### PR TITLE
skippy callback plugin: hides banner for skipped tasks

### LINKED ISSUE #9034: wishlist: be able to hide skipped roles when using conditional roles
##### Expected Results:

All roles where the expression with 'when' is false should not be shown
at all, preferrably by a config var and perhaps a way to reverse
on the command line.
##### Actual Results: task are always shown even if the role is skipped

I think conditional roles is a great idea, it made my plays easier to write.

However, all those skipped tasks are still shown which makes it harder to see the more interesting
output from the tasks that really are used.

Would it be possible to somehow hide them, maybe a config option in ansible.cfg that could
be reversed by a command line option?
(Yes, I realize that it is also very useful to see what actually is there even if it is not used :-)

### PR DESCRIPTION
**Pull request by rakshazi**
##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME

plugins/callback/skippy.py

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Implements/fixes #9034

This modification of skippy callback plugin just hides banner for skipped tasks (original plugin prints task banner). Reasons you can read in issue.

Original developer is @varunkatta, I just updated plugin for ansible v2.2

**Output fefore**
```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [antoshka.front]

TASK [antoshka : Add 'Backup db' cronjob] **************************************

TASK [antoshka : Add 'Upload db backup' cronjob] *******************************

TASK [antoshka : Add 'Backup media' cronjob] ***********************************

TASK [antoshka : Add 'sync media' cronjob] *************************************

TASK [antoshka : Add 'sync pdf_view' cronjob] **********************************

TASK [antoshka : Add Magento cronjob] ******************************************

TASK [antoshka : Add 'ERP import' cronjob] *************************************

TASK [antoshka : Add 'ERP full import' cronjob] ********************************

TASK [antoshka : Add 'ERP warehouse stock import' cronjob] *********************

TASK [antoshka : Add 'ERP warehouse full stock import' cronjob] ****************

TASK [antoshka : Add 'ERP offers full import' cronjob] *************************

TASK [antoshka : Add 'Connector export' cronjob] *******************************

TASK [antoshka : Add 'Prom.ua export' cronjob] *********************************

TASK [antoshka : Add 'NovaPoshta Sync' cronjob] ********************************

TASK [antoshka : Add 'Clean Magento Cache' cronjob] ****************************
ok: [antoshka.front]

PLAY RECAP *********************************************************************
antoshka.front             : ok=2    changed=0    unreachable=0    failed=0   
```

**Output after**
```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [antoshka.front]

TASK [antoshka : Add 'Clean Magento Cache' cronjob] ****************************
ok: [antoshka.front]

PLAY RECAP *********************************************************************
antoshka.front             : ok=2    changed=0    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by gundalow** [comment]
@bcoca I believe you've been reasonable active on this plugin. Could you please review.

**Comment by rakshazi** [comment]
Hello!
Any update about this PR?

**Comment by gundalow** [comment]
@rakshazi Thanks for the PR. It was Thanksgiving in the US where most of our Core Engineers are so this will get looked at in the next couple of days.

**Comment by rakshazi** [comment]
@gundalow thank you! Have a nice day :)

**Comment by rakshazi** [comment]
Hello!
Any update about this PR?

**Comment by rakshazi** [comment]
@bcoca can you review this?

**Comment by rakshazi** [comment]
Hello @gundalow @bcoca
Any update on this?

**Comment by tbar74235** [comment]
So in which Version of Ansible will I have this option to get completely rid of any skipped task output?

**Comment by rakshazi** [comment]
@tbar74235 you can just copy this plugin to your project's ansible dir and use it. It works with ansible 2.x

**Comment by ParagDoke** [comment]
Thank you @rakshazi ! Looking forward to having this merged. Will patch my ansible until then.

**Comment by oboukili** [comment]
Great work there!
I have some problems however with some tasks titles not being displayed (seems it's right after some were being skipped):

```
TASK [app : Ensure app is started] *****************************************
changed: [somehost]

MISSING TASK TITLE
FAILED - RETRYING: TASK: app : Wait for 5 minutes until app healthcheck is "UP" (150 retries left).
FAILED - RETRYING: TASK: app : Wait for 5 minutes until app healthcheck is "UP" (149 retries left).
FAILED - RETRYING: TASK: app : Wait for 5 minutes until app healthcheck is "UP" (148 retries left).
FAILED - RETRYING: TASK: app : Wait for 5 minutes until app healthcheck is "UP" (147 retries left).

TASK [app : Wait for 5 minutes until app app status to be "UP"] ************
ok: [somehost]

TASK [app : Wait for app to be listening on port 80] *********************
ok: [somehost]

MISSING TASK TITLE
ok: [somehost] => (item={u'command': u'check-http.rb -u http://127.0.0.1:80/health', u'name': u'health_app', u'subscribers': [u'app']})

TASK [app : Request immediate checks execution] ****************
ok: [somehost] => (item={u'command': u'app_healthcheck', u'subscribers': [u'app']})

MISSING TASK TITLE
changed: [somehost] => (item=somestuff)
changed: [somehost] => (item=anotherstuff)

TASK [app : Ensure main pages are warmed up] *********************************
...ignoring
failed: [somehost] (item=app) => {"dest": "/tmp/app-warmup.html", "failed": true, "gid": 0, "group": "root", "item": "app", "mode": "0644", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 77712, "state": "file", "status_code": 404, "uid": 0, "url": "http://localhost:80/app"}

MISSING TASK TITLE
ok: [somehost] => (item={u'command': u'app_healthcheck', u'name': u'health_app', u'subscribers': [u'app']})

```

**Comment by sungmincs** [comment]
Any update on this PR?

**Comment by gundalow** [comment]
Closing and r-opening PR to rerun CI

**Comment by rakshazi** [comment]
@bcoca review that PR, please
PS: sorry for delay :)

**Comment by xialonglee** [comment]
Why this PR still not merge yet? I really need this, it makes ansible output cleaner and running faster.
@bcoca

**Review by bcoca — CHANGES_REQUESTED** [review]
-1, this modifies the expected default behaviour of this plugin, I'm fine if you want to submit an alternate plugin that does this or make it an optional behaviour, but not when it changes the existing one w/o any recourse other than a downgrade.

**Comment by jhawkesworth** [comment]
Suggestions for alternative names 
skippy_silent
or
skippy_no_banner

**Comment by bcoca** [comment]
bikeshedding: hide_skipped, full_skip

**Comment by rakshazi** [comment]
@bcoca returned original `skippy.py`, moved new plugin to `full_skip.py`

**Review by bcoca — APPROVED** [review]

**Pull request merged**
