### PR TITLE
Skip tasks with a with_* that is empty

### LINKED ISSUE #1408: Using with_items with an empty list should skip the task
The situation I am in is that I would like to have a list $packages with optional packages to be installed. By default this list is empty, but we would like to be able to set it on a per-group or per-host basis.

However when doing something like:

``` yaml
- name: Install additional packages
  hosts: all
  tasks:
  - action: yum pkg=$item state=installed
    with_items: ${packages}
```

This fails with a yum-module error when ${packages} is an empty list. Since only_if is evaluated per item, it is no option to use it in this case.

### PR DESCRIPTION
**Pull request by dhozac**
Fixes #1408.

### CODE REVIEW

**Comment by mpdehaan** [comment]
in queue for review/testing...

**Comment by lindes** [comment]
Did this ever go out?  I'm not seeing this behavior on ansible 1.7.1 (which I know isn't the latest), yet this issue was closed over 2 years ago (older than 1.7.1, I should think?)... ?

**Comment by jeffb-stell** [comment]
2c77cf1a49557294567bd2684cb09c403363820e went out in 1.5.0, but I am seeing with_items barfing on null values

**Comment by razvanphp** [comment]
+1 not working in Ansible 1.9.1

**Comment by ghost** [comment]
Also seeing the issue in 1.9.1

**Comment by tommymalmqvist** [comment]
+1 not working in 1.9.1

**Comment by jonashaag** [comment]
Doesn't work with 1.9.4

**Comment by robinrocky** [comment]
Is this working? I am not able to see it in 
ansible 2.0.0

**Comment by feffi** [comment]
got the same error on "when" clauses with empty arrays "[]"

**Pull request merged**
