### PR TITLE
Document does not keep up with syntax change

### PR DESCRIPTION
**Pull request by curry9999**
##### SUMMARY

- delegate_to is functionally deleted.
- Use timeout instead of delegate_to.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

lib/ansible/modules/utilities/logic/wait_for.py

##### ANSIBLE VERSION

```paste below
devel
```

### CODE REVIEW

**Comment by bcoca** [comment]
In the example, the delegate_to prevents the module from executing on the remote, removing it will execute the module on the remote machine and possibly produce an error (we are waiting for machine reboot or ssh restart, etc), while adding the delegate_to removes any connection or host issues from the equation.

**Review by bcoca — CHANGES_REQUESTED** [review]
the delegate_to is there for a good reason, we might want to update the name: to reflect the reason, but not remove the delegate_to

**Comment by acozine** [comment]
@curry9999 thank you for your interest in improving the Ansible documentation. I'm not sure what motivated this change. Did you run into a problem trying to use the original example? 

As @bcoca says, the `delegate_to` is included on purpose, so Ansible will count down the wait time on the control machine. If Ansible tries to count down the wait time on the remote machine, it can defeat the purpose of waiting - for example, if the remote machine has rebooted and you're waiting for it to come back up.

**Comment by curry9999** [comment]
Once I verified it worked fine.
Sorry to trouble you.
PR will close.

**Pull request closed without merging**
