### PR TITLE
Install EPEL using RPM from S3.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Install EPEL using RPM from S3.

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

integration tests

### CODE REVIEW

**Comment by felixfontein** [comment]
Is this mirror regularly updated?

**Comment by mattclay** [comment]
@felixfontein The RPMs were originally downloaded from https://dl.fedoraproject.org/pub/epel/ -- now we're just downloading copies of those from S3 instead. They do not appear to be regularly updated, so I'm not worried about difficulty keeping them updated.

Downloading from S3 will avoid most intermittent test failures due to issues downloading these RPMs.

**Review by felixfontein — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
Thanks for implementing this!

**Pull request merged**
