### PR TITLE
add 'description' parameter.

### PR DESCRIPTION
**Pull request by shirou**
PROPOSAL: 'description' parameter

I'd like to add a "description" parameter.
Ansible does nothing about on it. it just describing what is it.

I know YAML can have a comment and a name is good to know what this task
do. But a comment is not structured and a name can not be long because
handlers use it.

If ansible defines "description", a documentation tool such as
Sphinx can read it and produces a good document.

```

---
- hosts: all
  description: This playbook is an example for describe directive
  tasks:
    - name: create empty file
      file: path=/tmp/empty state=touch
      description: >
        This empty file is needed to later tasks,
        such as A, B, and C.
    - name: do some script
      script: /some/local/script.sh
      description:
        - a
        - b
        - c
    - script: /some/local/script.sh
      description:
        can: use map
        some: thing
        other: thing

- include: other.yml
  description:
    - include can have description also
```

I will send this proposal to the ansible-project mailing list.

### CODE REVIEW

**Comment by bcoca** [comment]
you already have 'name' at play level, why not use that?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by shirou** [comment]
When you play, 'name' is always printed. If name is very long, output becomes too messy.

**Comment by amenonsen** [comment]
I think this should be closed now. There doesn't seem to have been much support for the directive-as-comment proposal, and I don't think it's a great precedent either.

**Comment by bcoca** [comment]
closing, as stated above a comment will do the same thing as a noop directive

**Comment by shirou** [comment]
I still think some kind of text notation is requred to generate a document automatically. But also know this idea is not supported widely. So, I agree to close. 
Thank you.

**Pull request closed without merging**
