### PR TITLE
Fix GCE and scaleway VM detection

### LINKED ISSUE #38947: Google cloud VMs are not VMs in facts
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
facts

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = None
  configured module search path = ['/Users/lex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lex/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ansible
  executable location = /Users/lex/.pyenv/versions/3.6.5/bin/ansible
  python version = 3.6.5 (default, Mar 29 2018, 16:45:10) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible do not detect google cloud as virtualization

##### STEPS TO REPRODUCE
```yaml
1. Run VM (i used f1.micro) on google cloud
2. Run ansible on that node
```

##### EXPECTED RESULTS
Should be in facts:

    "ansible_virtualization_role": "guest",
    "ansible_virtualization_type": "kvm",

##### ACTUAL RESULTS
```
    "ansible_virtualization_role": "NA",
    "ansible_virtualization_type": "NA",
```

### PR DESCRIPTION
**Pull request by rlex**
##### SUMMARY

Fixes detection of GCE vms.
In current state (as of 2.7.0) you will see following facts on GCE guest:
```
    "ansible_virtualization_role": "NA",
    "ansible_virtualization_type": "NA",
```
Which makes it hard to run some condition-based roles (lm_sensors, smartd, etc)

This PR will make it look like it:
```
    "ansible_virtualization_role": "guest",
    "ansible_virtualization_type": "kvm",
```
Since GCE uses KVM as hypervisor.

This also fixes #38947

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
facts

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/Users/lex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lex/.asdf/installs/python/3.7.0/lib/python3.7/site-packages/ansible-2.8.0.dev0-py3.7.egg/ansible
  executable location = /Users/lex/.asdf/installs/python/3.7.0/bin/ansible
  python version = 3.7.0 (default, Sep 25 2018, 16:33:40) [Clang 10.0.0 (clang-1000.10.44.2)]
```

### CODE REVIEW

**Comment by rlex** [comment]
This is a trivial change. Can someone please take a look?

**Comment by rlex** [comment]
I also added scaleway check.
Baremetal scaleway machines reports "Online Labs" in sys_vendor

**Comment by gundalow** [comment]
bot_status

Not sure why this is needs_revision

**Comment by gundalow** [comment]
@rlex Thank you for this PR, can you please add a changelog, see https://docs.ansible.com/ansible/devel/community/development_process.html#making-your-pr-merge-worthy

Then we can get this merged & backported

**Comment by rlex** [comment]
@gundalow will it be bugfix or minor change?

**Comment by pilou-** [comment]
I was able to reproduce this problem with Scaleway hosts and the below confirm this patch works.

Test playbook:
```
- hosts: all
  gather_facts: yes
  tasks:
    - scaleway_server_facts:
        region: par1
      vars:
        ansible_connection: local
    - debug:
        msg: "{{ '%s %s %s'|format(commercial_type, ansible_virtualization_type, ansible_virtualization_role) }}"
      vars:
        commercial_type: "{{ scaleway_server_facts | selectattr('private_ip', 'equalto', ansible_default_ipv4.address) | map(attribute='commercial_type') | first }}"
```

* using devel branch, output is NOK (`START1` and `ARM64` hosts are VMs, `C1` is baremetal)
  ```
  ok: [host0] => {
      "msg": "C1 NA NA" # OK (kvm kernel module not loaded)
  }
  ok: [host1] => {
      "msg": "START1-M kvm host" # NOK
  }
  ok: [host2] => {
      "msg": "START1-XS kvm host" # NOK
  }
  ok: [host3] => {
      "msg": "ARM64-2GB kvm guest" # OK (because /sys/devices/virtual/dmi/id/sys_vendor contains QEMU)
  }
  ```
* using this branch, output becomes correct:
  ```
  ok: [host0] => {
      "msg": "C1 NA NA"
  }
  ok: [host1] => {
      "msg": "START1-M kvm guest" # https://www.scaleway.com/virtual-cloud-servers/ mentions that KVM is used.
  }
  ok: [host2] => {
      "msg": "START1-XS kvm guest"
  }
  ok: [host3] => {
      "msg": "ARM64-2GB kvm guest"
  }
  ```

@rlex you might want to update `test/legacy/roles/scaleway_compute/tasks/state.yml` (or another scaleway legacy test) in order to add a test.

**Review by pilou- — APPROVED** [review]
shipit - don't hesitate to update scaleway legacy test :)

**Comment by pilou-** [comment]
> @gundalow will it be bugfix or minor change?

@rlex `bugfixes` instead of `bugfix`

**Comment by rlex** [comment]
fixed

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@rlex Thank you for this. Your first Ansible PR, MERGED!.

This has been merged into `devel` for release in Ansible 2.8

**Pull request merged**
