### PR TITLE
Add return code and error output to raw module

### PR DESCRIPTION
**Pull request by dagwieers**
Since we use 'raw' heavily on equipment where 'command' and 'shell' are not working (and python may need to be installed first using raw) these improvements are necessary in order to write more complex scripts (with return code handling and separated stdout/stderr).

This patch includes the following changes:
- exec_command() now returns the return code of the command
- _low_level_exec_command() now returns a dict, including 'rc', 'stdout' and 'stderr'
- all users of the above interfaces have been improved to make use of the above changes
- all connection plugins have been modified to return rc and stderr
- fix the newline problem (stdout and stderr would have excess newlines)

In a future commit I intend to add assertions or error handling code to verify the return code in those places where it wasn't done for _low_level_exec_command().

### CODE REVIEW

**Comment by dagwieers** [comment]
To indicate the relevance of this fix, if you would run `ls | sort` to a DD-WRT router, before the patch you would get a success:

```
TASK: [raw ls / | sort] ********************* 
ok: [mist] => {"stdout": "==========================================================\r\n\n \r\n\n ____  ___    __        ______ _____         ____  _  _ \r\n\n | _ \\| _ \\   \\ \\      / /  _ \\_   _| __   _|___ \\| || | \r\n\n || | || ||____\\ \\ /\\ / /| |_) || |   \\ \\ / / __) | || |_ \r\n\n ||_| ||_||_____\\ V  V / |  _ < | |    \\ V / / __/|__   _| \r\n\n |___/|___/      \\_/\\_/  |_| \\_\\|_|     \\_/ |_____|  |_| \r\n\n \r\n\n                       DD-WRT v24-sp2\r\n\n                   http://www.dd-wrt.com\r\n\n \r\n\n==========================================================\r\n\n/bin/sh: sort: not found\r\n"}
```

With this patch you get failure:

```
TASK: [raw ls / | sort] ********************* 
failed: [mist] => {"rc": 127}
stdout: ==========================================================

 ____  ___    __        ______ _____         ____  _  _ 
 | _ \| _ \   \ \      / /  _ \_   _| __   _|___ \| || | 
 || | || ||____\ \ /\ / /| |_) || |   \ \ / / __) | || |_ 
 ||_| ||_||_____\ V  V / |  _ < | |    \ V / / __/|__   _| 
 |___/|___/      \_/\_/  |_| \_\|_|     \_/ |_____|  |_| 

                       DD-WRT v24-sp2

                   http://www.dd-wrt.com

==========================================================
/bin/sh: sort: not found
```

**Comment by dagwieers** [comment]
Fixes the excess newline problem too.

**Comment by mpdehaan** [comment]
"all connection plugins (except fireball) have been modified to return rc and stderr"

Not saying this is incorrect, but curious since you called attention to it.   What are the implications of not modifying fireball to have the same signature?

**Comment by dagwieers** [comment]
Fireball mode has been fixed now too ! I now understand how it works (and how the module is providing information to the connection plugin). I didn't know about the fireball module before.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
