### PR TITLE
initial push of digital_ocean_droplet_info module

### PR DESCRIPTION
**Pull request by itdependsnetworks**
##### SUMMARY
This adds a module to view droplets for digital ocean

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME

This module follows suit with similar digital_ocean modules to provide information without actually adjusting the state.

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pmarques** [comment]
Hi @itdependsnetworks , thanks for contributing although this is similar to this #68239  which already fixes Fixes #53371.

**Comment by itdependsnetworks** [comment]
Funny, I literally looked into this like 8 days ago, didn’t think to look again yesterday. Can I add by_name to that PR?

**Comment by pmarques** [comment]
That PR isn't mine I just reviewed the code, feel free to suggest/ask in that PR :)

**Comment by Akasurde** [comment]
Hi @itdependsnetworks, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.digitalocean<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
