### PR TITLE
ovirt: Add support to diff

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This PR contains more improvments:

 - Patch that add support to 'log' messages done by the module, and also the possibility to see what attributes of specific object was updated, by using library deepdif.

 - Patch that improves the conversion from oVirt Python object to JSON, so it now also fetches nested Python objects, not only strings.

 - It fixes the waiting of host 'reinstalled' state, because it's better to specify why specific action should wait, instead of wait always for all.

 - fix 404 for `ovirt_vms` introduces by new feature in oVirt Python SDK 4.1.

### CODE REVIEW

**Comment by bcoca** [comment]
-1 we already have several competing standards on this, there is an upcomming proposal to normalize action logging on modules, lets wait for that.

**Comment by machacekondra** [comment]
Can you point me to it, please? Maybe this does something different, than what you think.

With this patch the users of oVirt modules should see what attributes has been updated.
For example if user hotplugged memory to Virtual Machine , he will see that 'memory' attribute has changed from 1GiB to 2GiB (in return 'messages' value). Is this what the new logging will do? I doubt, because it can't be solved generally for everything I think.

**Comment by machacekondra** [comment]
@mwperina

**Comment by bcoca** [comment]
for those kind of things we already have the 'diff' key, it used to be only for files but we expanded to other modules, like user

**Comment by machacekondra** [comment]
Nice feature, I wasn't aware of that. I will change it, thanks!

**Comment by machacekondra** [comment]
So this PR add support to --diff for oVirt modules, so far only when update of some attribute is executed,
we can't handle changing state of the entity, this will come in future, as not that trivial.

**Comment by machacekondra** [comment]
@ryansb

**Comment by machacekondra** [comment]
I would welcome if that can go to 2.3 release, thank you.

**Review by mwperina — APPROVED** [review]
Looks good to me, thanks! 👍

**Comment by machacekondra** [comment]
This is how the output looks like when running update of memory for example:

```
$ ansible-playbook --check --diff examples/vm/create.yml
```

```
TASK [Create vm from template] *************************************************
--- before
+++ after
@@ -72,7 +72,7 @@
         "href": "/ovirt-engine/api/icons/f3de923a-9824-49f5-ae25-9577d46f7236", 
         "id": "f3de923a-9824-49f5-ae25-9577d46f7236"
     }, 
-    "memory": 1073741824, 
+    "memory": 2147483648, 
     "memory_policy": {
         "guaranteed": 1073741824, 
         "max": 4294967296

changed: [localhost]

PLAY RECAP *********************************************************************

```

**Review by ryansb — APPROVED** [review]

**Pull request merged**
