### PR TITLE
module: wordpress

### PR DESCRIPTION
**Pull request by dz0ny**
This module enables installing wordpress core, it's themes and plugins from ansible.

### CODE REVIEW

**Comment by sivel** [comment]
A few things to note here based on a quick glance at the module:
1. You shouldn't preferably be using urllib3 and requiring it as a dependency.  You should be using `fetch_url` as provided by `ansible.module_utils.urls` and it's associated functions/functionality
2. Perhaps it might be a better requirement to instead rely on `wp-cli` since this seems to be the community standard for performing these types of tasks
3. `version_added` needs to be bumped to `1.8`, since that would be the next upcoming release, 1.6 was released about 6 months or so ago
4. There is an API for themes too, although this could be alleviated by using `wp-cli`: `http://api.wordpress.org/themes/info/1.0/`
5. Generally speaking, unit tests should not be included in the module itself, or not even within ansible.  It is preferable to add integration tests instead

**Comment by jimi-c** [comment]
Hi @dz0ny. Thanks for the submission, though the issues @sivel has pointed out above are all definite issues. Since we're about to split the modules out from the main Ansible repo (see the ansible-project/devel groups on Google for details), I'm going to go ahead and close this, since the PR will need to be pointed at the new repo.

So, as soon as we have the new repos in place, we'd be very happy if you'd resubmit this then, with the above issues addressed.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dz0ny** [comment]
@sivel && @jimi-c thx for info

**Comment by tersmitten** [comment]
Great work. I like the fuctionality.

**Pull request closed without merging**
