### PR TITLE
Add Direct Rule support for Firewall Module (rebase of #49514)

### PR DESCRIPTION
**Pull request by roperto**
##### SUMMARY

Rebase of #49514 (previously #34027) to allow managing direct rules and chains in firewalld.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

firewalld module

##### ADDITIONAL INFORMATION
Please refer to previous pull requests for additional information.

### CODE REVIEW

**Comment by till** [comment]
@roperto can you fix the above? I will try to help to get this PR merged. If you don't have time, let me know, then I'll PR the fixes to you! :D

**Comment by roperto** [comment]
@till thanks, I fixed what I think was causing the issues -- if there is more I might need some help as my time to work on this is a bit limited

Cheers

**Comment by roperto** [comment]
@till @maxamillion I did my own testing here and it is working using CentOS 7

CI is Green

Please let me know if I can do anything else to push this forward.

Thanks

**Comment by steve-todorov** [comment]
@maxamillion ping - have you had a chance to check this PR out? :)

**Comment by opoplawski** [comment]
This would be really helpful for me.

**Comment by roperto** [comment]
This module was migrated to community modules in 4e488d8435b3b3458de08bb2e4532bfbe6318121 -- if anyone knows where it we can make a pull request there. At this stage I don't believe it will get merged anyway (we fixed a few times but no answer from upstream).

**Comment by maxamillion** [comment]
@roperto that's my fault, I let this fall through the cracks and I'm sorry. Open over in the collection repo and I'll merge.

**Comment by danielcotton** [comment]
@roperto has a PR been opened with community.general? I couldn't find it and it doesn't seem to be linked here.

**Comment by roperto** [comment]
> @roperto has a PR been opened with community.general? I couldn't find it and it doesn't seem to be linked here.

hi sorry @danielcotton i haven't had the time. if you want to rebase/make a PR there I'd appreciate, otherwise I'll try to get to it later on. Cheers

**Comment by danielcotton** [comment]
Ah no worries - I was just following the convo and was curious if there was anything further.

I don't really feel familiar enough with the codebase to raise a new PR myself, so I think I'll leave that to the experts :)

**Comment by jimi-c** [comment]
Per the above discussion, we'll go ahead and close this issue here. Anyone can feel free to move this over to the correct collection repo mentioned above.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by roperto** [comment]
No problems. If anyone can point me out where the collections git repository is I can submit there

**Comment by danielcotton** [comment]
It's [here](https://github.com/ansible-collections/community.general) (and yes, it's surprisingly difficult to find)

**Comment by jimi-c** [comment]
My apologies @roperto, I thought it was clear from the conversation above. Thanks @danielcotton for sharing that.

**Pull request closed without merging**
