### PR TITLE
add support for local/remote syslog logging

### PR DESCRIPTION
**Pull request by r1k0**
This plugin will log ansible runs/plays to a syslog server.
Thanks for this great software

### CODE REVIEW

**Comment by bcoca** [comment]
provides feature requested in #10019

**Comment by alxgu** [comment]
Possibly you could change the adress and port to be variable and configurable by/in ansible.cfg?
Thanks!

**Comment by r1k0** [comment]
yes it's doable, not sure if they'll merge it but it's a good idea. 

Will look into it 

On 2015-01-30 15:29, alxgu wrote: 

> Possibly you could change the adress and port to be variable and configurable by/in ansible.cfg?
> Thanks! 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/ansible/ansible/pull/10116#issuecomment-72208904

**Comment by r1k0** [comment]
I meant I'm not sure a plugin should have its config variable in ansible.cfg (since it's a plugin).

**Comment by alxgu** [comment]
@bcoca what it the recommended way to configure a plugin?

**Comment by bcoca** [comment]
as you have it now, there is no facility to configure the callback plugins currently, most just output to screen

**Comment by galindro** [comment]
@bcoca , I've tested this code with ansible 1.9.1 and got this error:

``` bash
# ansible-playbook rds_change_instance_type.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 210, in main
    force_handlers=options.force_handlers,
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 181, in __init__
    ansible.callbacks.load_callback_plugins()
  File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 51, in load_callback_plugins
    callback_plugins = [x for x in utils.plugins.callback_loader.all()]
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/plugins.py", line 233, in all
    yield getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
  File "/home/galindro/Dropbox/e/Bruno/sb/git_repos/infra/ansible/callback_plugins/syslog_json.py", line 29, in __init__
    self.logger.addHandler(handler)
NameError: global name 'handler' is not defined
```

This is probably happening because I don't added this piece of code, as pointed by @r1k0 

``` bash
root ~ # diff /usr/bin/ansible /usr/bin/ansible.orig
195,203d194
< 
<         import logging
<         import logging.handlers
<         ansible_logger = logging.getLogger('ansible logger')
<         ansible_logger.setLevel(logging.DEBUG)
<         handler = logging.handlers.SysLogHandler(address = ('localhost',514), facility=19)
<         ansible_logger.addHandler(handler)
<         ansible_logger.info('OK' + ' ' + str(results))
< 
root ~ # 
```

But @r1k0 says that this code must be inserted in /usr/bin/ansible, not in /usr/bin/ansible-playbook. 

@r1k0 how could I use your plugin with ansible-playbook?

**Comment by r1k0** [comment]
@galindro,
Will have a look at it tomorrow and come back to you.

**Comment by galindro** [comment]
Tks @r1k0

**Comment by r1k0** [comment]
I recall I could log using ansible with the diff but I do not advise to use it.
To log using ansible-playbook, you need to put the plugin file  under callback_plugins.

take https://github.com/ansible/ansible/blob/devel/plugins/callbacks/syslog_json.py
put it under callback_plugins
check ansible.cfg that you have a correct path for callback_plugins   = <pathtoyour own callbackpluging folder>

run ansible-playbook, check syslog server that stuff has been written.
that should  work.

**Comment by r1k0** [comment]
note that the syslog plugin has been updated to use env variables for SYSLOG_SERVER and SYSLOG_PORT

so before running ansible-playbook make sure of:
$ SYSLOG_SERVER = 1.1.1.1; SYSLOG_PORT= 514
$ export SYSLOG_SERVER; export SYSLOG_PORT

or change the plugin and harcode your values if you don't like the env vars.

**Comment by galindro** [comment]
@r1k0 I've used it exactly as you said, but it not works. As you could see in error message, when ansible-playbook executable calls ansible.callbacks.load_callback_plugins() method, the CallbackModule class trows an error on this line:

``` python
self.logger.addHandler(handler)
```

After change it to `python self.logger.addHandler(self.handler)`, the plugin worked very well.

**Comment by r1k0** [comment]
good catch
I'm still  on my old non updated plugin so I didn't have this issue.
Please fork the repo and push back that patch.
Seems like the update has not been tested before being pushed.

**Comment by galindro** [comment]
Done: https://github.com/ansible/ansible/pull/11511

I've made some improvements in message log format to facilitate parsing.

**Comment by r1k0** [comment]
thx for your feedback, I will benefit from it ^^ 
thank you

**Comment by galindro** [comment]
You're welcome
:)

**Pull request merged**
