### PR TITLE
kubevirt: enable/update tests + fix merge_dicts()

### PR DESCRIPTION
**Pull request by mmazur**
##### SUMMARY
None of the unit tests for kubevirt actually did anything. Fix that. 

Also fix the regression in `merge_dicts()` introduced by [this change](https://github.com/ansible/ansible/pull/56833#discussion_r287500476).

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
kubevirt

### CODE REVIEW

**Comment by mmazur** [comment]
@machacekondra @pkliczewski please merge

**Review by machacekondra — APPROVED** [review]
+1

**Comment by mmazur** [comment]
Just occurred to me I've put the utils unit test in the wrong location and had to repush. Please re+1.

**Comment by machacekondra** [comment]
+1

**Comment by mmazur** [comment]
bot_status

**Pull request merged**
