### PR TITLE
standardized aws_secret_key, aws_access_key, region parameters

### PR DESCRIPTION
**Pull request by bpennypacker**
Also did some other standardization/cleanup such as moving boto imports
into a try/except statement, making sure not to log aws_secret_key, etc.

### CODE REVIEW

**Comment by lwade** [comment]
Hey @bpennypacker, this looks good, thanks for the effort here.

Regarding the region lookup code:

```
# If region isn't set either as a param or environ variable then
# look up the current region via the AWS URL
if not aws_region:
    response = urllib2.urlopen('http://169.254.169.254/latest/meta-data/placement/availability-zone')
    az = response.read()
    for r in AWS_REGIONS:
        if az.startswith(r):
            aws_region = r
            break
```

This assumes that the task is being run against an instance in AWS to start with, is that correct?  Perhaps its better that we actually force people to think about region and instead make it a required parameter?  Based on previous mistakes users have made in terms of location of resource, I'd be in favour of this.

**Comment by bpennypacker** [comment]
My only concern regarding the regions is that boto itself defaults to us-east-1 if the user doesn't specify one.  We could force it to be a required ansible parameter, which would mean that it couldn't optionally be set as an environment variable.  I don't know how big a deal that would be for folks though (personally I rely on vars files for all my settings like these and my AWS keys).  If we want to allow the region to be set by an environment variable then I think we need to leave this snippet in place since it would override boto's choice of us-east-1 as the default region with the region that the playbook is being run from.  I think we'd also need to clearly document the reason for making region a required parameter in order to force the end user to be aware of it - at least with a decent comment in the module code itself.

**Comment by lwade** [comment]
I absolutely think we should force people to make a region choice, folks should be completely aware of which region they are operating in and explicitly state it in tasks.  We've seen in IRC quite a few cases where folks haven't really been sure exactly what region they are running in (new AWS users presumably), which I'd suggest is highly dangerous in itself. Also, this code snippet won't help those who are running local_actions on the Ansible server outside of AWS, for example, since there is no metadata unless you are on an instance and then we still assume they are working within the same region.  I completely agree re: documentation, we can add a specific section about regions into the AWS section.  What do you think?

**Comment by bpennypacker** [comment]
You make an excellent point.  Edit: Actually, would you prefer to make these changes?  I'm not entirely sure what the best approach to take is regarding making the region required.  This is from the ec2 module that you helped write:

```
# If we have a region specified, connect to its endpoint.
if region:
    try:
        ec2 = boto.ec2.connect_to_region(region, aws_access_key_id=aws_access_key, aws_secret_access_key=aws_secret_key)
    except boto.exception.NoAuthHandlerFound, e:
        module.fail_json(msg = str(e))
# Otherwise, no region so we fallback to the old connection method
else:
    try:
        if ec2_url: # if we have an URL set, connect to the specified endpoint
            ec2 = boto.connect_ec2_endpoint(ec2_url, aws_access_key, aws_secret_key)
        else: # otherwise it's Amazon.
            ec2 = boto.connect_ec2(aws_access_key, aws_secret_key)
    except boto.exception.NoAuthHandlerFound, e:
        module.fail_json(msg = str(e))
```

If the region is going to be required now then this whole if/then/else would change drastically, and since I don't have any experience with Eucalyptus I don't want to screw this up.

**Comment by lwade** [comment]
Also, note to self. Need to add an AWS_URL option to the ec2_elb module to
support custom endpoint for Eucalyptus ELB.

**Comment by mpdehaan** [comment]
I'm fine with making region required, the error message should be reasonably self explanatory and as confusing as AWS region handling is I think having folks think about it is a very good idea.

I'll hold on this one until you think you're ready to merge it.  Let me know.

**Comment by mpdehaan** [comment]
Can you also submit this without merge commits?

Please use git pull --rebase vs "git pull", and "git rebase" vs "git merge".  Merge commits are bad/dangerous in the history.   

Thanks!

**Comment by lwade** [comment]
Mmmm actually making region mandatory (althoough we should) won't be too good from an API perspective.  Eucalyptus and OpenStack don't support this yet so it would break stuff.  Ideally it needs to be mandatory unless EC2_URL is specified (since we can assume quite safely that you are then working against a non-AWS cloud).

**Comment by bpennypacker** [comment]
@lwade - That was my thought as well.  What I think I'll do is make both ec2_url and region optional variables as far as ansible is concerned, but then do something along the lines of:

if ec2_url:
  connect_using_url
elseif region:
  connect_to_region
else:
  error "Either ec2_url or region must be specified"

I'm going to try to get this all taken care of in the next day or two.

**Comment by bpennypacker** [comment]
Closing this pull request out and replacing it with https://github.com/ansible/ansible/pull/3808

**Pull request closed without merging**
