### PR TITLE
BUGFIX : using yaml hosts inventory, hosts in groups weren't added to…

### PR DESCRIPTION
**Pull request by pae23**
… the group 'all'

##### SUMMARY
fix "auto adding" to group "all" of hosts in groups using YAML inventory. (not listed as issue)

##### ISSUE TYPE
 - Bugfix Pull Request

##### ANSIBLE VERSION
tested on 2.3 and devel

##### ADDITIONAL INFORMATION
The problem is present at least in branches stable-2.3 too (and should be backported).

```
You can test using an host.yml file like :

test:
  hosts:
    192.168.1.1:
    192.168.1.2:
```

### CODE REVIEW

**Comment by bcoca** [comment]
also fixed in passing in #23001

**Comment by bcoca** [comment]
also, if you follow the example https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
you start with group 'all' at the top level, which makes all the hosts be part of that group.

**Comment by pae23** [comment]
I understand it's becoming as plugins in devel branch, but for <= 2.3, this is a bug : the comment at line 69 of lib/ansible/inventory/yaml.py is explicit : 

```
        # Finally, add all top-level groups as children of 'all'.
        # We exclude ungrouped here because it was already added as a child of
        # 'all' at the time it was created.
```

and on that link : https://github.com/ansible/ansible/search?utf8=%E2%9C%93&q=%22self.groups%5B%27all%27%5D.add_child_group%22&type=
we can see that the yaml implementaion is the only one affected by this bug.

**Comment by bcoca** [comment]
both patches are needed, other inventory sources can do same

**Pull request merged**
