### PR TITLE
New module: Add Bcf switch module. (network/bigswitch/bcf_switch)

### PR DESCRIPTION
**Pull request by tedelhourani**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

BCF switch module

##### ANSIBLE VERSION

```
ansible 2.4.0 (bcf 537321fa77) last updated 2017/05/03 02:13:42 (GMT -700)
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by calfonso** [comment]
@tedelhourani bumping this PR based upon the bot feedback to update a few things. We'll keep watch on this as you are able to modify the patch. Thanks for your contribution!

**Comment by tedelhourani** [comment]
@calfonso, what is the required modification of this patch? It has passed the automated tests.

**Comment by calfonso** [comment]
@tedelhourani would you mind opening another PR with a unit test for this? Also update the CHANGELOG.md and MAINTAINTERS.txt.

**Comment by tedelhourani** [comment]
@calfonso, I'll open a PR to add unittest

**Pull request merged**
