### PR TITLE
service state typo

### PR DESCRIPTION
**Pull request by 2tunnels**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
playbooks_conditionals

##### SUMMARY
service module doesn't have "running" state.

### CODE REVIEW

**Comment by resmo** [comment]
This fix is not quite correct:

There is `state: running` (alias for started) in system module https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py#L1520 but not in systemd module https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/systemd.py#L263

IMHO the systemd module should also handle `running` similar to system module.

needs_revision

**Comment by 2tunnels** [comment]
@resmo, then mby we should update service module docs?

http://docs.ansible.com/ansible/service_module.html - no "running" state here.

**Comment by bcoca** [comment]
The service module takes 'running' for backwards compatibility, but it is not documented to discourage it's use.

There is no alias in `systemd` when invoking directly (no backwards compatibility needed), but if you invoke via service action plugin, it translates `running` into `started`.

**Comment by resmo** [comment]
ok, works for me :)

**Pull request merged**
