### PR TITLE
apt module: part rewrite of the upgrade logic

### PR DESCRIPTION
**Pull request by srgvg**
apt module: part rewrite of the upgrade logic, consistently checking the executable paths (a bare install (e.g. debootstrap) might not include aptitude), adding 'safe' as an alias to yes, and adding 'full' to allow aptitude full-upgrade as an alternative to apt-get dist-upgrade

### CODE REVIEW

**Comment by sevein** [comment]
I've experienced the same problem, good idea!

**Comment by mpdehaan** [comment]
Thanks!

Can you update this to use the "get_bin_path" function in the module common code instead?

```
   def get_bin_path(self, arg, required=False, opt_dirs=[]):
```

you would want to pass "required=True"

**Comment by srgvg** [comment]
I started modiying as per your request, and got started in refactoring the upgrade module. I forced pushed a new squashed commit with the new patch and modified the PR title and description...

The module basically allowed or 2 options: aptitude safe-upgrade and apt-get dist-upgrade.
The obne option missing here was aptitude full-upgrade, as an alternative to dist-upgrade (upgrade=full).
To be consistent, I added upgrade=safe as an alias to upgrade=yes, keeping this as the default.

When runnnig in check mode it also occurred to me, one might want to see the output of what would happen, hence returning stdout in the message (maybe that should be assigned to another key?)

I also made the executed upgrade commands consistent in their use of environment vars and options.

This better be well tested by some fellow Debian/Ubuntu people.

**Comment by RaymiiOrg** [comment]
When using `upgrade=yes` without aptitude it fails as it should:

```
$ ansible vps21.sparklingclouds.nl -s -m apt -a "upgrade=yes"
vps21.sparklingclouds.nl | FAILED >> {
    "failed": true,
    "msg": "'aptitude safe-upgrade' failed: /bin/sh: 1: /usr/bin/aptitude: not found\n"
}
```

However when providing `upgrade=safe` it errors saying the parameter is not allowed:

```
$ ansible vps21.sparklingclouds.nl -s -m apt -a "upgrade=safe"
vps21.sparklingclouds.nl | FAILED >> {
    "failed": true,
    "msg": "value of upgrade must be one of: yes,dist, got: safe"
}
```

As does `full`

```
$ ansible vps21.sparklingclouds.nl -s -m apt -a "upgrade=full"
vps21.sparklingclouds.nl | FAILED >> {
    "failed": true,
    "msg": "value of upgrade must be one of: yes,dist, got: full"
}
```

The normal `apt` one still works as expected:

```
$ ansible vps21.sparklingclouds.nl -s -m apt -a "upgrade=dist"
vps21.sparklingclouds.nl | success >> {
    "changed": true
}
```

**Comment by srgvg** [comment]
It seems you are not running with my updated module:

```
"msg": "'aptitude safe-upgrade' failed: /bin/sh: 1: /usr/bin/aptitude: not found\n"
```

This error is the first thing I updated, so the module would give a nice error, instead of having the shell throw an error.

I'm pretty sure you didn't test the right update script. Can you test it by checking out my branch, and using the test module script?

```
[dvl] serge@cyberlab:~/src/ansible$ git co check4aptitude 
Switched to branch 'check4aptitude'
[chck4pttd] serge@cyberlab:~/src/ansible$ sudo hacking/test-module -m library/apt -a "upgrade=safe"
[sudo] password for serge: 
* including generated source, if any, saving to: /home/serge/.ansible_module_generated
* this will offset any line numbers in tracebacks/debuggers!
***********************************
RAW OUTPUT
{"msg": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nReading extended state information...\nInitializing package states...\nNo packages will be installed, upgraded, or removed.\n0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 0 B of archives. After unpacking 0 B will be used.\nReading package lists...\nBuilding dependency tree...\nReading state information...\nReading extended state information...\nInitializing package states...\n", "changed": false}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "msg": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nReading extended state information...\nInitializing package states...\nNo packages will be installed, upgraded, or removed.\n0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 0 B of archives. After unpacking 0 B will be used.\nReading package lists...\nBuilding dependency tree...\nReading state information...\nReading extended state information...\nInitializing package states...\n"
}

```

**Comment by RaymiiOrg** [comment]
Damn sorry. I did checkout your branch, but forgot that pip has taken over my standard install of Ansible. Problem is at my side, with the pip issue solved I don't have the errors. Excuse me.

**Comment by mpdehaan** [comment]
It seems like the upgrade default should be "no" because you might be installing a package.

Can you explain the choice of defaults there?

**Comment by RaymiiOrg** [comment]
It shouldn't matter because the upgrade and other options should be mutually exclusive.

**Comment by srgvg** [comment]
The default 'yes' is the same as before my patch, I didn't change that. As @RaymiiOrg said, upgrade keyword (upgrading the whole system) is mutually exclusive with the other main keyword "package" (acting on one or some packages); it's action is in functionality actually default "no" by not using the keyword.

Default upgrade type after the patch is actually 'safe', but I kept 'yes' as an alias for backwards compatilbilty.

**Comment by mpdehaan** [comment]
Sounds reasonable, thanks.

**Comment by mpdehaan** [comment]
Merged, thanks... we will see if anyone yells :)

**Pull request merged**
