### PR TITLE
Fixes nxos_pim_rp_address module idempotence

### LINKED ISSUE #27499: (P2) nxos_pim_rp_address is not idempotent
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_pim_rp_address

##### NXOS VERSION
All versions

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 0fb64214a4) last updated 2017/07/27 13:55:58 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook demonstrates the idempotency problem for the group_list, prefix_list and route_map properties.  Problem is present for both `cli` and `nxapi` transports.

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_pim_rp_address sanity test"

- name: "Disable feature PIM"
  nxos_feature: &disable_feature
    feature: pim
    state: disabled
    provider: "{{ connection }}"

- name: "Enable feature PIM"
  nxos_feature:
    feature: pim
    state: enabled
    provider: "{{ connection }}"

# The group_list, prefix_list and route_map properties
# are mutually exclusive, so test them independently.
- block:
  - name: Configure rp_address + group_list 
    nxos_pim_rp_address: &configgl
      rp_address: "10.1.1.20"
      #group_list: "224.0.0.0/8"
      #prefix_list: "pim_prefix_list"
      route_map: "pim_routemap"
      bidir: true 
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Check idempotence
    nxos_pim_rp_address: *configgl
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  always:
  - name: "Disable feature PIM"
    nxos_feature: *disable_feature

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_pim_rp_address sanity test"
```

### PR DESCRIPTION
**Pull request by kedarkekan**
##### SUMMARY
Fixes #27499
- Fix the idempotence for nxos_pim_rp_address module. Changed indexing to fetch correct field from params.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
modules/network/nxos

##### ANSIBLE VERSION
devel (ansible 2.5.0)

### CODE REVIEW

**Comment by mikewiebe** [comment]
@kedarX Thanks for picking this issue up.  I patched in your diffs but there is still an idempotence issue.  Here is the playbook I am using for testing.

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_pim_rp_address sanity test"

- name: "Disable feature PIM"
  nxos_feature: &disable_feature
    feature: pim
    state: disabled
    provider: "{{ connection }}"

- name: "Enable feature PIM"
  nxos_feature:
    feature: pim
    state: enabled
    provider: "{{ connection }}"

# The group_list, prefix_list and route_map properties
# are mutually exclusive, so test them independently.
- block:
  - name: Configure rp_address + group_list
    nxos_pim_rp_address: &configgl
      rp_address: "10.1.1.20"
      group_list: "224.0.0.0/8"
      #prefix_list: "pim_prefix_list"
      #route_map: "pim_routemap"
      # bidir not supported on n3k running I6 or earlier
      bidir: true
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Check idempotence
    nxos_pim_rp_address: *configgl
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: Configure rp_address + prefix_list
    nxos_pim_rp_address: &configpl
      rp_address: "10.1.1.20"
      #group_list: "224.0.0.0/8"
      prefix_list: "pim_prefix_list"
      #route_map: "pim_routemap"
      bidir: false
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_rp_address: *configpl
    register: result

  - assert: *false

  - name: Configure rp_address + route_map
    nxos_pim_rp_address: &configrm
      rp_address: "10.1.1.20"
      #group_list: "224.0.0.0/8"
      #prefix_list: "pim_prefix_list"
      route_map: "pim_routemap"
      bidir: true
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_rp_address: *configrm
    register: result

  - assert: *false

  always:
  - name: "Disable feature PIM"
    nxos_feature: *disable_feature

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_pim_rp_address sanity test"
```
**Idempotence Issue Logs**
```shell
TASK [nxos_pim_rp_address : Configure rp_address + prefix_list] ****************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:43
<n9k-109.cisco.com> connection transport is nxapi
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_pim_rp_address.py
<n9k-109.cisco.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k-109.cisco.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k-109.cisco.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223624.89-102660187384227 `" && echo ansible-tmp-1505223624.89-102660187384227="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223624.89-102660187384227 `" ) && sleep 0'
<n9k-109.cisco.com> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmpyUNBhf TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223624.89-102660187384227/nxos_pim_rp_address.py
<n9k-109.cisco.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223624.89-102660187384227/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223624.89-102660187384227/nxos_pim_rp_address.py && sleep 0'
<n9k-109.cisco.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223624.89-102660187384227/nxos_pim_rp_address.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1505223624.89-102660187384227/" > /dev/null 2>&1 && sleep 0'
changed: [n9k-109.cisco.com] => {
    "changed": true, 
    "commands": [
        "ip pim rp-address 10.1.1.20 prefix-list pim_prefix_list"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "bidir": false, 
            "group_list": null, 
            "host": "n9k-109.cisco.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "prefix_list": "pim_prefix_list", 
            "provider": {
                "host": "n9k-109.cisco.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "route_map": null, 
            "rp_address": "10.1.1.20", 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }
}

TASK [nxos_pim_rp_address : assert] ********************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:54
ok: [n9k-109.cisco.com] => {
    "changed": false, 
    "failed": false, 
    "msg": "All assertions passed"
}

TASK [nxos_pim_rp_address : Check idempotence] *********************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:56
<n9k-109.cisco.com> connection transport is nxapi
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_pim_rp_address.py
<n9k-109.cisco.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k-109.cisco.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k-109.cisco.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223625.61-230938705268577 `" && echo ansible-tmp-1505223625.61-230938705268577="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223625.61-230938705268577 `" ) && sleep 0'
<n9k-109.cisco.com> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmpIYHJGo TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223625.61-230938705268577/nxos_pim_rp_address.py
<n9k-109.cisco.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223625.61-230938705268577/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223625.61-230938705268577/nxos_pim_rp_address.py && sleep 0'
<n9k-109.cisco.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1505223625.61-230938705268577/nxos_pim_rp_address.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1505223625.61-230938705268577/" > /dev/null 2>&1 && sleep 0'
changed: [n9k-109.cisco.com] => {
    "changed": true, 
    "commands": [
        "ip pim rp-address 10.1.1.20"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "bidir": false, 
            "group_list": null, 
            "host": "n9k-109.cisco.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "prefix_list": "pim_prefix_list", 
            "provider": {
                "host": "n9k-109.cisco.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "route_map": null, 
            "rp_address": "10.1.1.20", 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }
}

TASK [nxos_pim_rp_address : assert] ********************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:60
fatal: [n9k-109.cisco.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

```

**Comment by mikewiebe** [comment]
Here are results for the `n7k` platform.  The same step fails for idempotence but in a slightly different way.
```shell
TASK [nxos_pim_rp_address : Configure rp_address + prefix_list] ****************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:44
<n7k-99.cisco.com> connection transport is cli
<n7k-99.cisco.com> using connection plugin network_cli
<n7k-99.cisco.com> socket_path: /Users/mwiebe/.ansible/pc/11b2b74560
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_pim_rp_address.py
<n7k-99.cisco.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n7k-99.cisco.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n7k-99.cisco.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225954.62-211144501477227 `" && echo ansible-tmp-1505225954.62-211144501477227="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225954.62-211144501477227 `" ) && sleep 0'
<n7k-99.cisco.com> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmpVMRu1S TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225954.62-211144501477227/nxos_pim_rp_address.py
<n7k-99.cisco.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225954.62-211144501477227/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225954.62-211144501477227/nxos_pim_rp_address.py && sleep 0'
<n7k-99.cisco.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225954.62-211144501477227/nxos_pim_rp_address.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1505225954.62-211144501477227/" > /dev/null 2>&1 && sleep 0'
changed: [n7k-99.cisco.com] => {
    "changed": true, 
    "commands": [
        "ip pim rp-address 10.1.1.20 prefix-list pim_prefix_list"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "bidir": false, 
            "group_list": null, 
            "host": null, 
            "password": null, 
            "port": null, 
            "prefix_list": "pim_prefix_list", 
            "provider": null, 
            "route_map": null, 
            "rp_address": "10.1.1.20", 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}

TASK [nxos_pim_rp_address : assert] ********************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:55
ok: [n7k-99.cisco.com] => {
    "changed": false, 
    "failed": false, 
    "msg": "All assertions passed"
}

TASK [nxos_pim_rp_address : Check idempotence] *********************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:57
<n7k-99.cisco.com> connection transport is cli
<n7k-99.cisco.com> using connection plugin network_cli
<n7k-99.cisco.com> socket_path: /Users/mwiebe/.ansible/pc/11b2b74560
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_pim_rp_address.py
<n7k-99.cisco.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n7k-99.cisco.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n7k-99.cisco.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225958.94-63979426351440 `" && echo ansible-tmp-1505225958.94-63979426351440="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225958.94-63979426351440 `" ) && sleep 0'
<n7k-99.cisco.com> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmpyTP8ws TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225958.94-63979426351440/nxos_pim_rp_address.py
<n7k-99.cisco.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225958.94-63979426351440/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225958.94-63979426351440/nxos_pim_rp_address.py && sleep 0'
<n7k-99.cisco.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1505225958.94-63979426351440/nxos_pim_rp_address.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1505225958.94-63979426351440/" > /dev/null 2>&1 && sleep 0'
changed: [n7k-99.cisco.com] => {
    "changed": true, 
    "commands": [
        "ip pim rp-address 10.1.1.20 prefix-list pim_prefix_list"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "bidir": false, 
            "group_list": null, 
            "host": null, 
            "password": null, 
            "port": null, 
            "prefix_list": "pim_prefix_list", 
            "provider": null, 
            "route_map": null, 
            "rp_address": "10.1.1.20", 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}

TASK [nxos_pim_rp_address : assert] ********************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_pim_rp_address/tests/common/sanity.yaml:61
fatal: [n7k-99.cisco.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```

**Comment by kedarkekan** [comment]
@mikewiebe thanks for testing. Couple of things:

1. Shouldn't idempotence be independently for group_list, prefix_list and route_map config (mutually exclusive)? 
2. For same RP, 7K allows config with multiple options(group_list, prefix_list & route_map); However, 9K cli parser callback seems to fail it and doesn't allow to configure new option unless previous static rp config is deleted. Something like below:

7K:
```
!Command: show running-config pim
!Time: Tue Sep 12 16:57:33 2017

version 7.3(0)D1(1)
feature pim

ip pim rp-address 10.1.1.20 route-map pim_routemap bidir
ip pim rp-address 10.1.1.20 group-list 224.0.0.0/8 bidir
```

Doesn't work on 9K:

```
switch(config)# ip pim rp-address 10.1.1.20 route-map pim_routemap bidir
Delete static group-list config for RP 10.1.1.20/32 first
```
Above playbook works with 7K (logs below). For 9K it will fail due to the way cli callback is handled.
```
TASK [nxos_pim_rp_address : Configure rp_address + prefix_list] ****************************************************************
changed: [nxos_test]

TASK [nxos_pim_rp_address : assert] ********************************************************************************************
ok: [nxos_test] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}

TASK [nxos_pim_rp_address : Check idempotence rp_address + prefix_list] ********************************************************
ok: [nxos_test]

TASK [nxos_pim_rp_address : assert] ********************************************************************************************
ok: [nxos_test] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}



TASK [nxos_pim_rp_address : debug] *********************************************************************************************
ok: [nxos_test] => {
    "msg": "END nxapi nxos_pim_rp_address sanity"
}

TASK [nxos_pim_rp_address : disable nxapi] *************************************************************************************
changed: [nxos_test]

PLAY RECAP *********************************************************************************************************************
nxos_test                  : ok=58   changed=14   unreachable=0    failed=0
```

Above playbook will work for 7K, where for 9K either you need a unique config per static RP address or else there has to be logic implemented to remove the existing config and then do new config.

**Comment by kedarkekan** [comment]
@mikewiebe @privateip Possible ways to handle this:

1. Check for hardware from (sh ver) (this will not work with virtual appliances though, both 7k & 9k displays "NX-OSv Chassis" as the hardware type).

    a. 7K: allow multiple option config on same static rp address. (works without any changes)
    b. 9K: (option 1 & 2 will need re-work on module behaviour)
        1. Identify if clash, reject the config and fail the task 
        OR
        2. Delete the existing config and apply new one.(This may not be very explicit from the 
        playbook though)
        OR
        3. Write a playbook that explicitly handles this by removing old config and applying new one in consecutive  tasks to keep it explicit to playbook reader.

2. If 9K platform's behaviour is to be followed, existing code should work fine for both 7k & 9k, provided playbook takes care of the tasks explicitly.

Thoughts ?

**Comment by mikewiebe** [comment]
@kedarX I had a chance to look through your comments and do some more testing and this is what I would suggest.

First a few observations:

1. The 'Delete static group-list config for RP 10.1.1.20/32 first' issue you see on n9k is also present on n7k running later versions (not the version you have)
2. I created a new playbook (see below) that explicitly tests removal of group_list, prefix_list and routemap before attempting to configure.  With this the test passes (I had your diffs patched in) on most platforms.
3. With the playbook from step 2 I do see an idempotence problem however when I try to remove the configuration.  Some platforms allow you to remove with the command `no  ip pim rp-address 10.1.1.20` but some require the specific group_list, prefix_list or routemap to remove.

My suggestions:

1. For now, let's go with creating a playbook (sample below) that explicitly removes each feature before attempting to test the next feature.  We can create a "smarter" module in the next release if needed.
2. I am working on a fix for observation 3 and will reply back on this PR with the diffs.
3. I would prefer you take my diffs that fix observation 2 + my new sample playbook and patch it in to your PR to be merged.

Thoughts?

**UPDATE:** I was hoping that if I modified the code to include 'group_list, prefix_list or route_map' on removal it would work across all nxos platforms but some don't like the inclusion and fail to remove the config so not sure how I am going to fix this at this point without checking platform and version info.

**Comment by mikewiebe** [comment]
**Playbook:**
```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_pim_rp_address sanity test"

- name: "Disable feature PIM"
  nxos_feature: &disable_feature
    feature: pim
    state: disabled
    provider: "{{ connection }}"

- name: "Enable feature PIM"
  nxos_feature:
    feature: pim
    state: enabled
    provider: "{{ connection }}"

# The group_list, prefix_list and route_map properties
# are mutually exclusive, so test them independently.
- block:

  # Configure -----------------------------------------------
  - name: Configure rp_address + group_list
    nxos_pim_rp_address: &configgl
      rp_address: "10.1.1.20"
      group_list: "224.0.0.0/8"
      #prefix_list: "pim_prefix_list"
      #route_map: "pim_routemap"
      # bidir not supported on n3k running I6 or earlier
      bidir: true
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Check idempotence
    nxos_pim_rp_address: *configgl
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  # Remove ------------------------------------------------
  - name: Remove rp_address + group_list
    nxos_pim_rp_address: &removegl
      rp_address: "10.1.1.20"
      group_list: "224.0.0.0/8"
      #prefix_list: "pim_prefix_list"
      #route_map: "pim_routemap"
      # bidir not supported on n3k running I6 or earlier
      bidir: true
      state: absent
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_rp_address: *removegl
    register: result
  
  - assert: *false
  
  # Configure -----------------------------------------------
  - name: Configure rp_address + prefix_list
    nxos_pim_rp_address: &configpl
      rp_address: "10.1.1.20"
      #group_list: "224.0.0.0/8"
      prefix_list: "pim_prefix_list"
      #route_map: "pim_routemap"
      bidir: false
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_rp_address: *configpl
    register: result

  - assert: *false

  # Remove ------------------------------------------------
  - name: Remove rp_address + prefix_list
    nxos_pim_rp_address: &removepl
      rp_address: "10.1.1.20"
      #group_list: "224.0.0.0/8"
      prefix_list: "pim_prefix_list"
      #route_map: "pim_routemap"
      bidir: false
      state: absent
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_rp_address: *removepl
    register: result

  - assert: *false

  # Configure -----------------------------------------------
  - name: Configure rp_address + route_map
    nxos_pim_rp_address: &configrm
      rp_address: "10.1.1.20"
      #group_list: "224.0.0.0/8"
      #prefix_list: "pim_prefix_list"
      route_map: "pim_routemap"
      bidir: true
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_rp_address: *configrm
    register: result

  - assert: *false

  # Remove ------------------------------------------------
  - name: Remove rp_address + route_map
    nxos_pim_rp_address: &removerm
      rp_address: "10.1.1.20"
      #group_list: "224.0.0.0/8"
      #prefix_list: "pim_prefix_list"
      route_map: "pim_routemap"
      bidir: true
      state: absent
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_rp_address: *removerm
    register: result

  - assert: *false

  always:
  - name: "Disable feature PIM"
    nxos_feature: *disable_feature

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_pim_rp_address sanity test"

```

**Comment by kedarkekan** [comment]
@mikewiebe 

1. As of today, the multiple config for same static RP (not idempotent, but original config task) 
   comes out as a success; even with 'Delete static group-list config for RP 10.1.1.20/32 first' from 
   the box. The node does not send a failure return code to Ansible module. (Fixed this in the patch 
   mentioned below)
2. What platform/versions do not support complete command for deletion of config? At least from 
    my local test, I see that 7K & 9K NXOSv takes complete command(partial command does not 
   delete the config).
3. Is it just the NXOS software version or the platform that has a problem of different behaviour?
4. We need a matrix of platforms and software versions and their expected behaviour, so that we 
    can enhance the module to handle those.

**For 2.4**, I believe we can have at the least following. I already have a patch for following fixes:

1. Handles cli behaviour of duplicate config for same static RP. Task will fail with following 
   message, if encountered :
   ```
   fatal: [x.x.x.x]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "bidir": true,
            "group_list": null,
            "host": "x.x.x.x",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 8080,
            "prefix_list": "pim_prefix_list",
            "provider": {
                "host": "x.x.x.x",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 8080,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "nxapi",
                "use_ssl": false,
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": true
            },
            "route_map": null,
            "rp_address": "10.1.1.20",
            "ssh_keyfile": null,
            "state": "present",
            "timeout": 10,
            "transport": "nxapi",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "use_ssl": false,
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": true
        }
    },
    "msg": "Delete static group-list config for RP 10.1.1.20 first"
   }
   ```
2. Uses complete command for deletion. (Tested and works with 7K & 9K virtual platform). This is 
     to support explicit playbook tasks for addition and deletion of config. Partials don't seem to 
     work.
3. Updated the playbook the way you have tested; explicit addition and deletion of static RP 
    config. I believe this is a better way to do, rather than module doing implicit removal of config, 
    as it may not be evident from the playbook at first glance. This can lead to unintentional 
    deletion. 

With this, 7K & 9K NXOSv works fine.

**Comment by kedarkekan** [comment]
@mikewiebe I am thinking of this:

** For 2.4 **
Fix the idempotence issue for config addition alone
Add test integration role to delete commit using nxos_command (and a documentation note)

** 2.5 **
Handle duplicate config for same static RP
Handle platform/version dependencies for deletion.

We can close 27499 and open a new feature bug to handle 2.5?

**Update:** 
I don't think a single playbook can do a justice, even with nxos_command for deletion of config.

**Comment by mikewiebe** [comment]
@kedarX 

* `2.4`
  * Agree that we should only handle idempotence issue for addition.
  * Please update https://github.com/ansible/ansible/pull/29958 to use `nxos_command` to delete
  * Once you make the updates I will test the playbook on all of my platforms.  As long as it passes then I say we can merge both this PR and the PR with the tests.

* `2.5`
  *  Agree with your proposal.
  * I will open a new bug with the relevant platform information to handle removal.

**Comment by kedarkekan** [comment]
@mikewiebe updated the PR's with necessary changes for 2.4. Kindly run the playbook from #29958 and confirm if that works. (make sure you update the config delete command in playbook per platform).

If that works, I will merge it for 2.4 by EOD Friday.

**Comment by mikewiebe** [comment]
@kedarX As we discussed during our call, please add a note to the module header comments to indicate that `absent` is not currently supported on all platforms.  I am testing your changes now.

**Comment by mikewiebe** [comment]
@kedarX I verified the changes and they look good.  See https://github.com/ansible/ansible/pull/29958 for details.

**Review by Qalthos — APPROVED** [review]

**Pull request merged**
