### PR TITLE
New module: manipulate INI-style settings

### PR DESCRIPTION
**Pull request by jpmens**
I hear the "module of the week" for _[insert the name of a different CM system here]_ is one which manipulates INI-style files. This is my contribution and includes `DOCUMENTATION`.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This is very nice.  

BTW, on the docs front, if you ever want to include a multi-line example from two different playbooks this is going to be tricky.   As a result, I'm suggesting we change this now before documenting over stuff.

+examples:
     68 
-   - code: ini_file dest=/etc/conf section=drinks option=fav value=lemonade mode=0600 backup=true
   69 
-     description: Ensure C(fav=lemonade) is in section C([drinks]) in said file

As a result, I had previously suggested we keep documentation as a SEPERATE array of docstrings.

EXAMPLES = [
""" 
example one might be YAML 
""",
""" example two might NOT be YAML
"""
]

But I really need a script that at least generates rst/ files for the MAIN module documentation as a way of testing this before we go forward with documentation.

**Comment by mpdehaan** [comment]
Thinking we can put the module reference on the main site actually, ignore my RST comment, I can still do @mavimo's bootstrap thingy for those -- generating RST tables would not be fun.   I do think we need to do EXAMPLES differently though.

**Comment by jpmens** [comment]
Not quite sure I understand, but updating this commit to include that.

**Comment by jpmens** [comment]
Done. (I hope.)

**Comment by jpmens** [comment]
Re RST: have you looked at https://github.com/jpmens/ansible-booklet, specifically `mofo.py` and the Jinja2 `templates/` ?

**Comment by jpmens** [comment]
I can have a go at that this evening if you like ... We are talking about generating e.g. `ansible-docs/rst/modules/lineinfile.rst`, right?

**Comment by mpdehaan** [comment]
Thanks -- we should merge this into the main tree under the 'hacking'
directory I think.   It does need to get renamed from mofo I am afraid :)

I am kind of unsure which way to go on docs generation and need to think
about it.

I can either make it output javascript (super easy) and adapt Mavimo's HTML
so it fits in with the docs project headers a bit, or I can do a ton of
painful work to make it output RST tables (which are REALLY REALLY NOT
FUN), or see if I can inline HTML tables inside the RST (probably easiest,
actually).

Anyway, with all of the various attributes the templates are going to be
somewhat non-trivial.

**Comment by mpdehaan** [comment]
Yeah, totally.

If there is a way to generate tables without the RST "ascii table" syntax
that would be totally fine and probably FAR easier.  I am pretty sure you
can include inline HTML in RST.

Thanks a ton for this, saves me a lot of work and will allow me to
concentrate more on squashing the github tickets queue.   Very much
appreciated.

I think we could just have the "ansible-docs" project call
../ansible/hacking/module_formatter.py --whatever-arguments as part of
"make docs", and assume you had ansible and ansible-docs checked out in the
same directory.  Seems reasonable.

**Comment by jpmens** [comment]
Done in #1101 :)

**Comment by mpdehaan** [comment]
merged thanks!

**Pull request merged**
