### PR TITLE
Add exclusive configuration mode support in IOS-XR

### LINKED ISSUE #55613: ADD "Configure Exclusive" options to IOSXR configuration modules
##### SUMMARY

IOSXR modules currently use "configure terminal" to enter configuration mode on the routers as it appears on line 62 of [(https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/plugins/cliconf/iosxr.py)]. ASR devices have the ability to enter "configure exclusive" which prevents concurrent configurations from happening.

##### ISSUE TYPE
- Feature Idea
Add the ability to choose "configure exclusive" mode, in addition to the default "configure terminal" and "configure admin"

##### COMPONENT NAME

iosxr_config
ansible/ansible/blob/stable-2.7/lib/ansible/plugins/cliconf/iosxr.py

##### ADDITIONAL INFORMATION

This would be  used to ensure no concurrent configurations can happen on the same device. Configure exclusive locks out the device during configuration to prevent other users from committing changes while the device is in exclusive mode.

```
    def configure(self, admin=False):
        prompt = to_text(self._connection.get_prompt(), errors='surrogate_or_strict').strip()
        if not prompt.endswith(')#'):
            if admin and 'admin-' not in prompt:
                self.send_command('admin')
            self.send_command('configure terminal')

Potential options:

- name: configure top level configuration
  iosxr_config:
    lines: hostname {{ inventory_hostname }}
    conf_mode: exclusive/terminal

- name: configure top level configuration
  iosxr_config:
    lines: hostname {{ inventory_hostname }}
    exclusive: yes
```

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Closes https://github.com/ansible/ansible/issues/55613
- Adds the ability to enter exclusive configuration mode

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
cliconf/iosxr.py
module_utils/iosxr.py
iosxr_config.py

### CODE REVIEW

**Review by justjais — COMMENTED** [review]
code changes lgtm, can u plz add test case to cover the scenario.

**Comment by NilashishC** [comment]
> code changes lgtm, can u plz add test case to cover the scenario.

@justjais, the changes made here would not be reflected in the list of commands present in module execution output. We can however, just add one test case with `exclusive: yes`, and check if it works properly or not. However, afaiu, we cannot determine from module execution result if we entered exclusive mode or not.

**Comment by justjais** [comment]
I understand that mode itself cannot be tested so just to check the code coverage and its proper functioning you can fire a test with exclusive mode set to true and if the result is expected that will test the exclusive functionality.

**Comment by NilashishC** [comment]
> I understand that mode itself cannot be tested so just to check the code coverage and its proper functioning you can fire a test with exclusive mode set to true and if the result is expected that will test the exclusive functionality.

Thanks! I've added a test.

**Review by justjais — APPROVED** [review]

**Pull request merged**
