### PR TITLE
FortiOS modules for 2.9 - 10

### PR DESCRIPTION
**Pull request by migumun**
##### SUMMARY
This PR contains an update to fortios modules that includes all of the changes requested for 2.9.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

fortios_user_adgrp
fortios_user_device
fortios_user_radius
fortios_user_tacacsplus
fortios_voip_profile
fortios_vpn_ipsec_concentrator
fortios_vpn_ipsec_forticlient
fortios_vpn_ipsec_manualkey
fortios_vpn_ipsec_manualkey_interface
fortios_vpn_ipsec_phase1
fortios_vpn_ipsec_phase1_interface
fortios_vpn_ipsec_phase2
fortios_vpn_ipsec_phase2_interface
fortios_vpn_ssl_settings
fortios_vpn_ssl_web_portal
fortios_waf_profile
fortios_wanopt_profile
fortios_wanopt_settings
fortios_webfilter_content
fortios_webfilter_content_header

### CODE REVIEW

**Review by NilashishC — COMMENTED** [review]
Existing sub-key `state` has been removed and added back as a top-level key in the following modules: 

fortios_user_adgrp, fortios_user_radius, fortious_user_tacacsplus, fortios_voip_profile, fortios_vpn_ipsec_concentrator, fortios_vpn_ipsec_forticlient, fortios_vpn_ipsec_manualkey, fortios_vpn_ipsec_manualkey_interface, fortios_vpn_ipsec_phase1 (npu-offload too), fortios_vpn_ipsec_phase1_interface, fortios_vpn_ipsec_phase2, fortios_vpn_ipsec_phase2_interface, fortios_vpn_ssl_web_portal, fortios_waf_profile, fortios_wanopt_profile, fortios_webfilter_content, fortios_webfilter_content_header

For fortios_vpn_ipsec_phase1 module the key `npu-offload` is completely removed.

**Comment by NilashishC** [comment]
For modules that this PR touches, but not all entries for them have been removed from ignore.txt please comment on the PR with the reason why those need to be kept.

**Comment by mamunozgonzalez** [comment]
Sure, all of the files in this PR which had an entry in ignore.txt for E336 and E337 have been removed according to instructions followed by maintainers: If these entries are not removed there would be a warning saying that the ignore is not necessary. E.g.: 

```ERROR:` test/sanity/ignore.txt:3692:1: A100 Ignoring 'E336' on 'lib/ansible/modules/network/fortios/fortios_firewall_policy.py' is `unnecessary```

On the other hand, some of the files in this PR didn't have an entry in ignore.txt (E33[6|7]) such as fortios_webfilter_content, but the reason why this file wasn't added to ignore.txt is not known, as all of the entries to ignore.txt were added by Ansible maintainers/committers.

**Comment by mamunozgonzalez** [comment]
The reason why npu-offload key is not present is bcs it was removed from FGT in the latest iteration when the modules were regenerated. It's normal that FGT removes (and adds) some attributes when the version is updated.

**Comment by mamunozgonzalez** [comment]
I'll add a deprecate note for npu-offload and a similar thing for 'state'

**Pull request merged**
