### PR TITLE
uptime.py not latest

### PR DESCRIPTION
**Pull request by Cupidazul**
##### SUMMARY
Update should be ran here, so that " ../../../../examples/scripts/uptime.py " is reparsed/updated to its newer version...

The Script "uptime.py" here:   https://docs.ansible.com/ansible/latest/dev_guide/developing_api.html#developing-api
Defers from: https://github.com/ansible/ansible/blob/devel/examples/scripts/uptime.py

new option ", verbosity=0"  is very important, without this, scripts dont run.

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ariordan-redhat** [comment]
`verbosity=0` was merged into `devel` [in PR#74438](https://github.com/ansible/ansible/pull/74438).
Requested info on whether backporting to `latest` version is valid.

**Comment by Akasurde** [comment]
@ariordan-redhat Backport for 2.11 - https://github.com/ansible/ansible/pull/75796

**Comment by Cupidazul** [comment]
> @ariordan-redhat Backport for 2.11 - #75796

Still not fixed.

GitHub:
image

Docs has no "verbosity=0" parameter:
image

**Comment by Akasurde** [comment]
@Cupidazul PR #75796 is merged, but documentation will be generated periodically. Once it is generated, changes will reflect in docs.ansible.com.

**Comment by ariordan-redhat** [comment]
docs.ansible.com has been updated: 
image
https://docs.ansible.com/ansible/latest/dev_guide/developing_api.html

Closing this PR, as it was used to flag the missing `verbosity=0`.

Thank you for your help with the Ansible docs, @Cupidazul .

**Pull request closed without merging**
