### PR TITLE
Add ec2_key module.

### PR DESCRIPTION
**Pull request by zbal**
Allow management of EC2 key pairs.

Supports:
- state present / absent
- create of key pair (generated by AWS and the private key is returned in the response)
- import of existing public key

### CODE REVIEW

**Comment by jctanner** [comment]
@zbal can you bump version added up to 1.5 please?

**Comment by zbal** [comment]
@willthames - feel free to push any additional commits as you mentioned in #5263

**Comment by zbal** [comment]
@jctanner - Any other change you'd like to see included ?

**Comment by jctanner** [comment]
@zbal thanks!

**Pull request merged**
