### PR TITLE
New user device module for Fortinet's FortiOS

### PR DESCRIPTION
**Pull request by migumun**
##### SUMMARY

Fortinet is adding Ansible support for FortiOS and FortiGate products. This module follows the same structure, guidelines and ideas given in previous approved module for a parallel feature of FortiGate (webfiltering): https://github.com/ansible/ansible/pull/37196 
In this case we are providing a different functionality: "Fortios User Device".

Please note that this will be part of other modules to come for FortiGate, including different functionalities: system, wireless-controller, firewall, webfilter, ips, web-proxy, wanopt, application, dlp spamfilter, log, vpn, certificate, user, dnsfilter, antivirus, report, waf, authentication, switch controller, endpoint-control and router. We plan to follow the same style, structure and usage as in the previous module in order to make it easier to comply with Ansible guidelines.

This PR has been updated according to suggestions and code reviews given in previous submissions of Fortinet modules.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

fortios_user_device

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0 (new_module ddbbe5dfa5) last updated 2018/09/24 14:54:57 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/magonzalez/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/magonzalez/ansible/lib/ansible
  executable location = /home/magonzalez/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

### CODE REVIEW

**Comment by trishnaguha** [comment]
@mamunozgonzalez Will you split the module and httpapi plugin in two different PRs?

**Comment by mamunozgonzalez** [comment]
> @mamunozgonzalez Will you split the module and httpapi plugin in two different PRs?

Sure, I can split into two PRs. However I had the impression from the previous long discussions we had and due to the amount of PRs already submitted that you wanted to minimize the number of PRs for Fortinet. That's the main reason why I put this two together. Are you sure you want to have this separated? Can you confirm with @gundalow ?

**Comment by mamunozgonzalez** [comment]
Btw, it seems that the last commit made Shippable to fail, but apparently I can't see a logical reason that ties the changes with the failures. Could it be due to a temporary fail in Shippable? (I have seen similar weird and random errors other times).
 If so could you trigger again the Shippable checks?
Thanks!

**Comment by trishnaguha** [comment]
@mamunozgonzalez If PRs are related, then you can have as one PR.
Since this PR has one new module and http plugin, we would prefer to have those as two separate PRs so it would be easy to review.
Thanks.

**Comment by trishnaguha** [comment]
Retriggered Shippable.

**Comment by mamunozgonzalez** [comment]
Shippable failed again, due to strange errors.
One of the errors is saying:
```17:55 ERROR: lib/ansible/modules/cloud/vmware/vsphere_copy.py:0:0: E309 version_added for new option (host) should be '2.9'. Currently None (0%)```

However this does not have anything to do with the changes in this PR. 'vsphere_copy.py' has not been modified at all.
Actually the failures that appear now didn't appear before the last commit (and the last commit only does 'imports urllib' and calls 'urllib.parse.quote' method).
Apparently it seems to be caused by something external to this PR. 
@trishnaguha , @gundalow , Can you help me investigate this?
Thanks!

**Comment by trishnaguha** [comment]
@mamunozgonzalez you can ignore this CI failure. This won't be a blocker for merging this PR. 
Please keep your module commit in this PR and open a separate PR for httpapi plugin so that the PRs can be reviewed.
Thanks!

**Comment by mamunozgonzalez** [comment]
HTTPAPI plugin moved to: https://github.com/ansible/ansible/pull/56870

**Comment by mamunozgonzalez** [comment]
@trishnaguha , I splitted the PR into two as suggested. However this new module module relies on FortiOSHandler which was introduced in the HTTPAPI plugin (https://github.com/ansible/ansible/pull/56870) and due to it, this PR is failing. It will not compile until the other HTTPAPI PR is approved and introduces the files needed.
How can we have this PR passing the tests if there are dependencies with the other HTTPAPI PR?
Thanks in advance.

**Comment by mamunozgonzalez** [comment]
hi @trishnaguha and @NilashishC , Do you know how to solve this problem about requiring files which are in other PR?

**Comment by NilashishC** [comment]
@pabelanger Is there are way right now to do `depends-on` in ansible/ansible?

**Comment by pabelanger** [comment]
yes, add:

depends-on: URL to ansible/ansible PR

in commit message

**Comment by mamunozgonzalez** [comment]
Hi @NilashishC and @pabelanger, 
 I submitted a couple of commits including "depends-on:" keyword but none of them worked (I tried the first line of the commit message and also the body). Is the syntax wrong or is something else required?

The error returned seems to be the same: It cannot find FortiOSHandler.

**Comment by NilashishC** [comment]
> Hi @NilashishC and @pabelanger,
> I submitted a couple of commits including "depends-on:" keyword but none of them worked (I tried the first line of the commit message and also the body). Is the syntax wrong or is something else required?
> 
> The error returned seems to be the same: It cannot find FortiOSHandler.

@pabelanger Could you please help out here a bit?

**Comment by pabelanger** [comment]
Because zuul.ansible.com is not running any of the testing of ansible/ansible (that is shippable) that syntax is not supported. If we had fortios jobs on zuul.ansible.com, it would work as expect.

For here, you either need to land the parent PR, or cherry-pick this one atop of it.

**Comment by mamunozgonzalez** [comment]
Please discard this PR. Due to the complications with the other related HTTPAPI plugin PR  I'll be closing this one and start over in a brand new one (that will also make use of the just merged HTTPAPI plugin).

**Comment by mamunozgonzalez** [comment]
The brand new PR with only the files required and ready to be reviewed is in:
https://github.com/ansible/ansible/pull/58291

**Pull request closed without merging**
