### PR TITLE
Fix discrepency between apt-get clean and ansible.builtin.apt: clean=…

### PR DESCRIPTION
**Pull request by ghost**
…true

currently, using apt-get clean removes /var/cache/apt/srcpkgcache.bin and /var/cache/apt/pkgcache.bin, while ansible.builtin.apt: clean=True does not. This patch serves to fix this discrepancy

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

This PR is connected with Issue #82611 

```paste below

```

### CODE REVIEW

**Review by mkrizek — CHANGES_REQUESTED** [review]
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) and add tests if possible.

**Review by yurnov — COMMENTED** [review]
Looks fine for me

**Comment by s-hertel** [comment]
This was merged in #82800 since it had tests to prevent a regression. Thanks for working on this!

**Pull request closed without merging**
