### PR TITLE
Do not set RPMDIST to '%dist' when dist is not set by the distribution.

### PR DESCRIPTION
**Pull request by dirtyharrycallahan**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Just curious...

Under what distribution did you see problems with this?

**Comment by mpdehaan** [comment]
also I am a fan of your movies but wish you would do one about software development

**Comment by dirtyharrycallahan** [comment]
SuSE/openSuSE and RHEL 5/CentOS 5 do not.
RHEL 6 and CentOS 6 should work.

ansible.spec needs a few changes to work on SuSE/openSuSE (package names) which I hope to fix as soon as I come up to speed on github.

Since I primarily use SuSE at work I would like to fix these easy things before commiting my zypp module.

++++++++++++++++++
openSuSE 12.3
++++++++++++++++++

patrickc@linux-sngq:~> rpm --eval '%{?dist}'

patrickc@linux-sngq:~>

++++++++++++++++++
SLES 11 SP2
++++++++++++++++++

patrickc@linux-y2f5:~/Desktop> rpm --eval '%{?dist}'

patrickc@linux-y2f5:~/Desktop> 

++++++++++++++++++
CentOS 6.4
++++++++++++++++++

[patrickc@localhost ~]$ rpm --eval '%{?dist}'
.el6
[patrickc@localhost ~]$

++++++++++++++++++
CentOS 5.9
++++++++++++++++++

[patrickc@localhost ~]$ rpm --eval '%{?dist}'

[patrickc@localhost ~]$ 

++++++++++++++++++
RHEL 5.9
++++++++++++++++++

[patrickc@ccm ~]$ rpm --eval '%{?dist}'

[patrickc@ccm ~]$

**Comment by mpdehaan** [comment]
Python zypper module would be great!

Will test and merge shortly.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
