### PR TITLE
Use correct length for unicode/emoji strings

### LINKED ISSUE #63105: Wide glyphs cause padded asterisks to wrap
##### SUMMARY
Wide glyphs in task names cause the asterisks in the output to wrap around to the next line. My guess is that Ansible is treating characters that take up two spaces as one. Example: 🚀 and 汉字.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /home/major/git/cki-project-experimental/aws-deployment/ansible.cfg
  configured module search path = ['/home/major/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/major/.pyenv/versions/3.7.4/envs/venv-3.7.4/lib/python3.7/site-packages/ansible
  executable location = /home/major/.pyenv/versions/venv-3.7.4/bin/ansible
  python version = 3.7.4 (default, Sep 20 2019, 07:35:42) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```
(no config changes from defaults)
```

##### OS / ENVIRONMENT
Fedora 30 with Python 3.7.4

##### STEPS TO REPRODUCE
I ran a playbook that contains emojis:

```yaml
---

- hosts: localhost
  gather_facts: no

  tasks:

    - name: "🚀 This name has emoji"
      debug:
        msg: "🚀 is a fun emoji"

    - name: "汉字 This name has Chinese characters"
      debug:
        msg: "汉字 means 'Chinese character'"
```

##### EXPECTED RESULTS

I expected the asterisks to be the same length for all lines without wrapping.

##### ACTUAL RESULTS
The output is:

```
PLAY [deployer] *****************************************************************************

TASK [🚀 This name has emoji] ****************************************************************
Thursday 03 October 2019  11:03:41 -0500 (0:00:00.025)       0:00:00.025 ****** 
ok: [localhost] => 
  msg: 🚀 is a fun emoji

TASK [汉字 This name has Chinese characters] **************************************************
Thursday 03 October 2019  11:03:41 -0500 (0:00:00.009)       0:00:00.035 ****** 
ok: [localhost] => 
  msg: 汉字 means 'Chinese character'

PLAY RECAP **********************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

### PR DESCRIPTION
**Pull request by major**
##### SUMMARY

Strings with unicode or emoji are not handled properly by default
with python. Glyphs that are 2 or 4 characters wide will have a
`len()` of 1. This causes asterisks at the end of task names to wrap
to the next line and it looks awkward.

If the `wcwidth` module is present on the system, use it to determine
the correct length of the string. This allows the asterisk padding after
task names to be the correct length without wrapping.

Fixes: ansible/ansible#63105

Signed-off-by: Major Hayden <major@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

Ansible core.

##### ADDITIONAL INFORMATION
Output before fix:

```
PLAY [deployer] *****************************************************************************

TASK [🚀 This name has emoji] ****************************************************************
Thursday 03 October 2019  11:03:41 -0500 (0:00:00.025)       0:00:00.025 ****** 
ok: [localhost] => 
  msg: 🚀 is a fun emoji

TASK [汉字 This name has Chinese characters] **************************************************
Thursday 03 October 2019  11:03:41 -0500 (0:00:00.009)       0:00:00.035 ****** 
ok: [localhost] => 
  msg: 汉字 means 'Chinese character'
```

Output after fix:

```
PLAY [deployer] *****************************************************************************

TASK [🚀 This name has emoji] ***************************************************************
Thursday 03 October 2019  14:00:10 -0500 (0:00:00.022)       0:00:00.022 ****** 
ok: [localhost] => 
  msg: 🚀 is a fun emoji

TASK [汉字 This name has Chinese characters] ************************************************
Thursday 03 October 2019  14:00:10 -0500 (0:00:00.011)       0:00:00.033 ****** 
ok: [localhost] => 
  msg: 汉字 means 'Chinese character'
```

The output looks 1 character short on the Chinese character tasks when you copy/paste here in GitHub, but it looks correct in the terminal.

### CODE REVIEW

**Comment by sivel** [comment]
FWIW, and if anyone wants to try to use ctypes to get access to wcwidth, here is some code I had written.  I don't know what state it is in, it seems to work for Py3, but I remember some issue, maybe with Py2:

https://gist.github.com/sivel/86e1cc5bdd7327ffee9f0f95d4c11dbd

**Comment by major** [comment]
Shippable shows failures on F29/F30, but it's related to a dnf/rpm issue of some sort from how it looks.

**Review by jamescassell — APPROVED** [review]
shipit

**Comment by abadger** [comment]
I have pure python code for this that we might be able to use.  Let me check if it is LGPLv2 or LGPLv2+ licensed.

**Comment by abadger** [comment]
It's LGPLv2+, so it would be compatible with Ansible: https://github.com/fedora-infra/kitchen/blob/develop/kitchen3/kitchen/text/display.py

That said, I want to see if I can resolve the issues in sivel's code.  One of the things I didn't like about my code was that I updated the combining tables from time to time.  It probably could be rewritten to simply use what's in the version of python being run on, though.  (IIRC, I embedded the tables for both speed and so that the same table would be used no matter what Python version it was run on.)

I do remember that the the wcwidth algorithm that I started with had numerous places where it didn't do the right thing.  But that was many years ago so wcwidth might have advanced to the point where it gets those things right now.

**Comment by abadger** [comment]
Okay, I have a fix for sivel's code. I put it in the comments of his gist.  @major you could take a look at it.  I think we'd want to do that initialization as early as possible.  Maybe somewhere in the cli/* code... (I'd put it in an ```__init__()``` rather than at the toplevel of the file, though, so other people can use the files in other ways).

After that, I think we should adapt the kitchen unittests for text.display.textual_width for this code and see how much wcwidth differs.  If it is still bad compared to textual_width, we may want to consider using textual_width instead.

**Comment by abadger** [comment]
Here's the two tests that could be used to test wcwidth and wcswidth:

https://github.com/fedora-infra/kitchen/blob/develop/kitchen3/tests/test_text_display.py#L48
https://github.com/fedora-infra/kitchen/blob/develop/kitchen3/tests/test_text_display.py#L81

**Comment by major** [comment]
Okay, @abadger, I'll try to get a look tomorrow. I've used kitchen in the past and it works pretty well.

Should I approach that as an optional import as well? I wasn't sure if kitchen was anywhere else in Ansible land.

**Comment by abadger** [comment]
Kitchen isn't used.  Since i wrote it, I've added some functions from there
to ansible (although later we wanted bsd license versions so they had to be
rewritten
from scratch)

I was suggesting using sivel's version, actually, and then using the
kitchen test cases to make sure it's as good as the version in kitchen.

If it wasn't as good as kitchen's version we could look into bundling that
function from kitchen rather than adding it as a dep.

**Review by sivel — CHANGES_REQUESTED** [review]
Just adding a review, so this is tracked correctly. Attached as a comment is a gist that shows how to use ctypes for interacting with wcwidth.

We would like to see this converted to use that code, instead of relying on a 3rd party lib for this functionality.

**Comment by major** [comment]
Sorry for the slow replies, folks. The `${DAYJOB}` keeps me pretty busy and I haven't had time to come back to this.

**Comment by sivel** [comment]
@major no problem, we are triage issues and PRs, and this was in that list, just wanted to make sure I recorded the requested changes appropriately.

**Comment by sivel** [comment]
Resolved by https://github.com/ansible/ansible/pull/66214

**Pull request closed without merging**
