### PR TITLE
Integration Tests only:  nxos_udld, nxos_udld_interface, nxos_vxlan_vtep_vni

### PR DESCRIPTION
**Pull request by saichint**
##### SUMMARY

IT cases for udld, udld_interface and vxlan_vtep_vni

##### ISSUE TYPE

 - IT Pull Request

##### COMPONENT NAME
- nxos_udld
- nxos_udld_interface
- nxos_vxlan_vtep_vni

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION

This PR is for adding IT cases for udld, udld_interface and vxlan_vtep_vni components. There are no code changes.

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
Needs running against our test infra then it can be merged into `devel` and cherry picked into `stable-2.4`

**Review by Qalthos — CHANGES_REQUESTED** [review]
nxos_vxlan_vtep_vni is good, but `feature udld` fails with `Invalid feature name` on our VM.

**Comment by gundalow** [comment]
```
< mikewiebe> Ah... I c.  Was it virtual n9k or virtual 7k?
<@Qalthos> 7k
< mikewiebe> Qalthos: We may have to skip it on virtual 7k since we have coverage for the physical platform.  Likely not supported on virtual, I will follow up with saichin
```

**Comment by saichint** [comment]
@Qalthos I added a case statement for skipping udld tests on n7k titanium. Can you try and check if this is fine? Thanks

**Comment by saichint** [comment]
Just hold this PR now, I will recheck and put a comment. For now I am making this [WIP]

**Comment by saichint** [comment]
@Qalthos Added proper titanium condition for udld. Done with all my changes for this PR.

**Comment by Qalthos** [comment]
Seems good but `no feature nv overlay` takes forever to finish, which kills the run for vxlan_vtep_vni. Putting a pause somewhere between 240 and 300 seconds allows the task to complete.

**Review by Qalthos — APPROVED** [review]

**Comment by saichint** [comment]
Is the "no feature nv overlay" problem happening on titanium? It works fine on all platforms in our lab without any issues. I don't have titanium with me to try it. In any case, since the test case is merely calling nxos_feature for nve as disabled, if there is any timing issues, it should be taken care in the nxos_feature code, I think, because adding timeouts in this test case will not solve anything if some other test case calls the same task. Instead of changing test cases, we should fix the nxos_feature for nve disable. If you agree, please merge this and we can open another issue for feature nve.

**Comment by gundalow** [comment]
needs_contributor

**Comment by saichint** [comment]
@Qalthos Can you respond to my query, please?

**Comment by saichint** [comment]
@Qalthos Still waiting for you to respond, please

**Review by trishnaguha — APPROVED** [review]

**Pull request merged**
