### PR TITLE
Add system/interfaces_file module maintainers information

### PR DESCRIPTION
**Pull request by obourdon**
Subject says it all

### CODE REVIEW

**Comment by obourdon** [comment]
@hryamzik

**Review by gundalow — APPROVED** [review]

**Comment by obourdon** [comment]
@hryamzik could you please approve ? Many thanks in advance

**Comment by hryamzik** [comment]
LGTM

**Comment by obourdon** [comment]
@gundalow could you please merge it, I have several additional functionality to add in further PRs.
Many thanks

**Comment by gundalow** [comment]
Merged, thanks

**Pull request merged**
