### PR TITLE
Core Docs Refactor and Redesign

### PR DESCRIPTION
**Pull request by dharmabumstead**
##### SUMMARY

Documentation refactor, as described in [Ansible issue #79](https://github.com/ansible/proposals/issues/79). 
This update:

- Moves content into more focused "guides"
- Reorganizes the table of contents 
- Adds a collapsible TOC
- Updates our CSS to a more recent customized RTD theme 
- Tweaks our doc design with independent scrolling TOC and content and consolidated fixed header
- Moves generated plugin, CLI and module content to appropriate subdirectories
- Updates links in some of the Jinja2 templates to accommodate the new directory structure 

Known issues / to do:

- Finish fixing links
- Add generated RSTs to git ignore
- Add more robust front matter
- Rewrite/edit some dodgy old content
- Further tweaks and reorg as necessary

##### ISSUE TYPE

 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

1. NOVEMBER 2017 (done) Clean up open PRs as much as possible - so we don’t cause mass merge conflicts.
2. DECEMBER 2017 (done): Move physical files - move RST files into appropriate subdirectories. Significantly, this will include moving the thousands of generated module RST files into a “modules” subdirectory, and updating the build scripts so they copy these files correctly. Also will need to generate redirects for the moved files so we don’t break existing links.
3. JANUARY 2018 (done): Move existing content into guides. 
4. FEBRUARY 2018 (in progress): Add appropriate front matter (intro, concepts, getting started) to guides.
5. FEBRUARY - MARCH 2018 (in progress): Clean up legacy material - remove colloquialisms, fix spelling and grammatical errors, correct structure, make tone consistent.

```

```

### CODE REVIEW

**Comment by abadger** [comment]
Really quick review; for something this big that's largely reorganization, I think we probably will want to look at a sample of the finished product, merge it if there's no glaring issues, and then fix anything that got forgotten/broken afterwards.

* Mentioned in slack that there's some generated pages that are being included in the git checkin.  dharmabumstead will be removing those.
* (non-blocking) In the future we may want to replace use of :doc: with :ref:  (For instance: "Now that you've read :doc:`../installation-guide/intro_installation`" from rst/user_guide/intro_getting_started.rst ) doc has to be changed whenever a file moves.  Ref matches the name that we give it so it's more stable.  However, we probably need to come up with a convention for ref names before we do that.  We could have a tutorial section, a reference section, and a developer deep dive that all talk about a feature.  The naming convention will let us link to the proper one.

Looks good!  Glad this is getting done.

**Comment by dharmabumstead** [comment]
Go to http://54.164.15.46/ansible/ to see these updates in action.

**Comment by jborean93** [comment]
When looking at the live docs, I have a few points/questions

* Do we still have the ability to set the version base don the URL, I presume we can't here because it is a single site but want to verify
* The table output for module options and return values isn't formatting correctly (tested on Chrome and Firefox)
* When looking at a single module, the whole module index nav pane on the is expanded for every module and not just the group.
* I'll be a +1 to changing the code-block background colour from the greenish shade to another colour but that's just me

I haven't looked further into it from there but the reset seems great.

**Comment by abadger** [comment]
(Not a blocker) Expander color on the sidebar should be changed.  It's hard to tell the expanders exist right now.

**Comment by dharmabumstead** [comment]
For reviewers: please read the known issues list in the PR description and see @abadger’s comment above. We want to get this new structure in place ASAP, so unless it’s a build breaker / data loss / horribly missing bit of info, we will fix it post merge. Thanks!

**Comment by varunchopra** [comment]
Everything's wonky on mobile. Can anyone confirm?

**Comment by gundalow** [comment]
Looks great, this will make docs a lot better.
Agree with @abadger only fix the really broken things, merge, then use follow up PRs.

I think these are the issues that need fixing before this gets merged:

1) Rebase

2)  On mobile (Chrome on Android) content is all in a small column. I've sent @dharmabumstead a screen shot. Though if this isn't quick to sort fix this in another PR. Wouldn't want to hold up this PR too much longer.

3) Auto generated content
Looks like some autogenerated content has been checked in, and exists in multiple places.

`./docs/docsite/rst/cli/ansible*` also exists in `./docs/docsite/rst/user_guide/`
Looking at `Makefile` these are put in `--output-dir=rst/cli/`
Though you have http://54.164.15.46/ansible/user_guide/command_line_tools.html which links to http://54.164.15.46/ansible/user_guide/ansible-playbook.html which seems like a logical place in the TOC


3.1) `docs/docsite/Makefile` change to:
```
	@echo "Cleaning up generated rst"
	-rm rst/cli/ansible-*.rst
	-rm rst/cli/ansible.rst
	-rm rst/modules/*_by_category.rst
	-rm rst/modules/list_of_*.rst
	-rm rst/modules/*_maintained.rst
	-rm rst/modules/*_module.rst
	-rm rst/modules/*_plugin.rst
	-rm rst/playbooks_directives.rst
	-rm rst/plugins/*/*.rst
	-rm rst/reference_appendices/config.rst
	-rm rst/reference_appendices/playbooks_keywords.rst
```


3.2) `.gitignore` change to:
```
# docsite stuff...
docs/api/_build/
docs/api/rst/
docs/docsite/_build
docs/docsite/*.html
docs/docsite/htmlout
docs/docsite/rst/cli/ansible-*.rst
docs/docsite/rst/cli/ansible.rst
docs/docsite/rst/modules/community_maintained.rst
docs/docsite/rst/modules/core_maintained.rst
docs/docsite/rst/modules/list_of_*.rst
docs/docsite/rst/modules/*_module.rst
docs/docsite/rst/modules/modules_by_category.rst
docs/docsite/rst/modules/network_maintained.rst
docs/docsite/rst/modules/partner_maintained.rst
docs/docsite/rst/modules/*.rst
docs/docsite/rst/playbooks_directives.rst
docs/docsite/rst/plugins_by_category.rst
docs/docsite/rst/plugins/*/*.rst
docs/docsite/rst/reference_appendices/config.rst
docs/docsite/rst/reference_appendices/playbooks_keywords.rst
docs/docsite/rst_warnings
docs/docsite/searchindex.js
docs/docsite/_static/*.gif
docs/docsite/_static/*.png
docs/docsite/_static/websupport.js
# deb building stuff...
```

3.3) Ensure the duplicate and autogenerated RST files are deleted

**Not blocking**

I don't think these block merge, though listed here so they are noted, may well be already on your list

A) Seem to have three scroll bars:
Between TOC and content - disabled when TOC isn't expanded, guess that's OK
Right of content - seems to always be disabled - I think this should be removed
Browser right most - This is OK

B) `dev_guide` TOC and layout could do with more work, though we can do that afterwards

C) `Common return values are documented here, the following are the fields unique to this {{plugin_type}}:` on each module page
Looks like this is broken in `devel`, working in `stable-2.4`. So no worse with your PR

D) Add borders back to module table.

**Comment by dharmabumstead** [comment]
Thanks for the reviews. Merging now so people can start working within the new structure, and will fix the issues on my todo list (and the mobile issue) in subsequent PRs.

**Comment by simon04** [comment]
Awesome, thanks you so much for your works on the documentation! :1st_place_medal: 

Would it make sense to update http://docs.ansible.com/ansible/latest/ since the current version dates back to 2017-10-10? For instance, the "edit on GitHub" link at http://docs.ansible.com/ansible/latest/intro_windows.html leads to a "page not found".

**Comment by gundalow** [comment]
Once 2.5.0 is release (plan next week) `/latest/` will point contain the work that @dharmabumstead has done and the "edit on GitHub" links will work again

**Pull request merged**
