### PR TITLE
New Module: add NetApp capacity pool to azure

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
New Module: add NetApp capacity pool to azure

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
- azure_rm_netapp_capacity_pool.py 

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@carchi8py Thank you for contributor this PR. Could you fix the CI fail, when you finished changed, I will push for review! Thanks a lot!

**Comment by carchi8py** [comment]
@fred-sun the fix for this is in pr #59939, i'm talking with Matt and the Redhat team on how to handle the unit test. We might just drop them.

**Comment by Fred-sun** [comment]
@carchi8py Thanks for you update! Do you mean that this PR will be closed and replaced by it?

**Comment by Fred-sun** [comment]
@carchi8py Thanks for your info, I see, when you finished change, I will push for review! Thanks a lot!

**Comment by Fred-sun** [comment]
@carchi8py You should add document for test_azure_rm_netapp_capacity_pool. Thank you very much!

**Comment by carchi8py** [comment]
Hey @Fred-sun since we were told there would be no new modules accepted in ansible after 2.9 (and this missed that window) we made this in to a collection here.

https://github.com/ansible/ansible_collections_netapp/tree/master/ansible_collections/netapp/azure

**Comment by Fred-sun** [comment]
@carchi8py I see, Thanks for your info. If we are not adding to ansible 2.9, maybe we need to turn off this PR. Thank you very much!

**Comment by Fred-sun** [comment]
> Hey @Fred-sun since we were told there would be no new modules accepted in ansible after 2.9 (and this missed that window) we made this in to a collection here.
> https://github.com/ansible/ansible_collections_netapp/tree/master/ansible_collections/netapp/azure

@carchi8py How would you like do this PR ? If a new models cannot be added after version 2.9, shall we temporarily close the PR ?

**Comment by carchi8py** [comment]
I think we can close these.

**Pull request closed without merging**
