### PR TITLE
Add the possibility to sysprep and join AD domain Windows template vmware

### PR DESCRIPTION
**Pull request by stravassac**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 2c17f9becd) last updated 2017/01/03 16:27:51 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Test on Windows 2008 R2 and 2012 R2
Add the possibility to sysprep and join AD domain Windows template vmware with this options:
windows_sysprep:
      fullName: "windows specific full name"
      orgName: "steph"
      computerName: "test_vm"
      #productId: "12134" # optional
      timeZone: 0 # integer https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx
      password: "win_pwd" # optional -> change local administrator password not necessary
      autoLogon: False
      autoLogonCount: 0
      joinDomain : "mydomain.net"
      domainAdmin: "ad_account"
      domainAdminPassword: "win_password"
      passwordPlainText: True
      guiRunOnce: ['cmd.exe /C echo first > c:\command.txt','cmd.exe /C echo second >> c:\command.txt'] # optional, autoLogon must be set to True and autoLogonCount > 0

customize flag must be set to True and one network card must be set (vmxnet3)

```

```

### CODE REVIEW

**Comment by aperigault** [comment]
duplicate_of #19866

**Comment by dagwieers** [comment]
@aperigault This is the way to do it these days:

duplicate_of #19866 

See https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md

**Comment by aperigault** [comment]
@dagwieers Thanks I'm not a github power user.

**Comment by dagwieers** [comment]
It's not really GitHub itself, but Ansible GitHub bot that works this way.
Since GitHub has quite limited access rights management, @ansibot takes care of many duties.

PS I may be wrong, but likely the module maintainer ( @nerzhul or @jctanner ) should be instructing ansibot.

**Comment by jctanner** [comment]
@dagwieers yep, only the maintainers can close out issues with "duplicate of"

**Comment by jctanner** [comment]
The code in this PR is almost identical to https://github.com/ansible/ansible/pull/19866 except for the name of the parameter. "windows_sysprep" versus "windows_custimizations" and camelcased args.

I prefer the arg spec in https://github.com/ansible/ansible/pull/19866 so closing this one in favor of that.

duplicate_of https://github.com/ansible/ansible/pull/19866

**Pull request closed without merging**
