### PR TITLE
Better document the return type of the fileglob filter

### LINKED ISSUE #33465: fileglob lookup returns a string instead of a list
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
fileglob lookup

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel eec2ab5e75) last updated 2017/12/01 22:20:10 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kustodian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kustodian/git/ansible/lib/ansible
  executable location = /home/kustodian/git/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 23 2017, 15:37:09) [GCC 6.3.0 20170406]
```

##### SUMMARY
The `fileglob` lookup plugin instead of a list, returns a string which is a list of paths joined with a comma.

##### STEPS TO REPRODUCE
Use play:
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: '{{ lookup("fileglob", "/etc/*.conf") }}'
```

##### EXPECTED RESULTS
The play above should print a list of conf files in `/etc`.

##### ACTUAL RESULTS
But it actually prints this:
```
% ansible-playbook glob.yml

PLAY [localhost] **********************************************************************************************************************************************

TASK [debug] **************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "/etc/appstream.conf,/etc/krb5.conf,/etc/debconf.conf,/etc/cowpoke.conf,/etc/resolv.conf,/etc/request-key.conf,/etc/mke2fs.conf,/etc/safe-rm.conf,/etc/ucf.conf,/etc/signond.conf,/etc/pam.conf,/etc/libaudit.conf,/etc/usb_modeswitch.conf,/etc/adduser.conf,/etc/ca-certificates.conf,/etc/popularity-contest.conf,/etc/nilfs_cleanerd.conf,/etc/ld.so.conf,/etc/hdparm.conf,/etc/pnm2ppa.conf,/etc/kerneloops.conf,/etc/fwupd.conf,/etc/libao.conf,/etc/insserv.conf,/etc/kernel-img.conf,/etc/multitail.conf,/etc/netscsid.conf,/etc/gai.conf,/etc/wodim.conf,/etc/sensors3.conf,/etc/sddm.conf,/etc/devscripts.conf,/etc/idmapd.conf,/etc/nsswitch.conf,/etc/sysctl.conf,/etc/mtools.conf,/etc/updatedb.conf,/etc/logrotate.conf,/etc/host.conf,/etc/deluser.conf,/etc/rsyslog.conf,/etc/ltrace.conf,/etc/fuse.conf"
}

```

What's very interesting is that `with_fileglob` works without any issues and this is supposed to use this lookup.

### PR DESCRIPTION
**Pull request by DaveB93**
##### SUMMARY
Add a new user friendly description of what to expect when using a fileglob filter, and how to get what you probably want with it.
Fixes #33465

As a new user, I was relying on the documentation for fileglob and based on what was there assumed it was going to return a list.  When I tried debugging I saw it wasn't the case, and worked around it by applying a split(',') filter to it, but then I found that if no files were matched, my split wasn't working, so finally googled enough things to find this issue description.  After reading the comments on that I found a much cleaner way of doing things, and decided that it should be documented. 

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
fileglob lookup

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /d/projects/development/server/scripts/ansible/ansible.cfg
  configured module search path = ['/home/BeleznayD/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.6 (default, Jun 28 2018, 10:27:26) [GCC 7.3.0]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by Akasurde** [comment]
@DaveB93 Could you please rebase this branch ? Thanks.

**Comment by gundalow** [comment]
https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html

**Comment by DaveB93** [comment]
Hi, sorry for the delay,  will do when I get to the right computer.

**Comment by gundalow** [comment]
@DaveB93 Looks like it's close, could you try http://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html again, appears there is a merge conflict in here

**Comment by gundalow** [comment]
Oh, or I'm happy to just make the update directly in a new PR and credit you

**Comment by gundalow** [comment]
Fixed in https://github.com/ansible/ansible/pull/52801 thanks again @DaveB93 for spotting this and suggesting better docs.

**Pull request closed without merging**
