### PR TITLE
win_uri: Add integration tests, new functionality...

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This is a cleanup of the win_uri module.

###### DONE
- Added check-mode support
- Add as many parameters from the **uri** module as possible
  - Added `creates`
  - Added `follow_redirects`
  - Added `maximum_redirection`
  - Added `password`
  - Added `removes`
  - Added `return_content`
  - Added `status_code`
  - Added `timeout`
  - Added `user`
  - Added `validate_certs`
- Fixed list-handling for comma-separated strings

###### TODO
- Add and improve the integration tests (copied from **uri** module)
  - Can we run testserver.py on Windows ?
  - Or implement testserver.ps1 instead ? #25420 

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

win_uri

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by blakfeld** [comment]
Fantastic changes!

**Comment by jhawkesworth** [comment]
I would have prefered the change to powershell.ps1 to be in a separate PR, just in case of the need to revert, but I can't foresee it causing problems.

ConvertTo-SnakeCase looks like it would be a good thing to have in powershell.ps1, but... another time.

If someone else reviews I'll merge this.

shipit

**Comment by blakfeld** [comment]
shipit

**Comment by dagwieers** [comment]
@jhawkesworth We don't have any integration tests at this point. I was hoping for the **uri** tests, but lacking an HTTP server there's nothing. We could add some tests against google.com testing some of the functionality, but tests against outside infrastructure is frowned upon (error-prone).

**Update:** Since it is now merged, we will do this in a separate commit.

**Pull request merged**
