### PR TITLE
Set domain_id when domain is set or project/domain is set

### LINKED ISSUE #66525: os_user_role: fails to assign role in domain only
##### SUMMARY

In an OpenStack environment with multiple domains and when using keystone (identity) API v3, the os_user_role module fails with `"Must specify either a domain or project"` when trying to assign a role to a specific domain only (e.g. `heat_domain_admin` user with `admin` role in the `heat` domain).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_user_role

##### ANSIBLE VERSION
```
ansible 2.9.3
  config file = ~/projects/openstack/ansible-openstack/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/projects/openstack/venv/ansible2.9/lib/python3.7/site-packages/ansible
  executable location = ~/projects/openstack/venv/ansible2.9/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### ENVIRONMENT

In order to reproduce this issue, on the OpenStack side (which the os_user_role module is used against):

* must be using Identity API v3
* domain `heat` must already exist
* user used for testing should not exist

##### STEPS TO REPRODUCE

```yaml
---
- name: os_user_role domain bug
  hosts: openstack_local
  vars:
    keystone_host: keystone
    openstack_admin_password: **********
    openstack_auth:
      auth_url: "https://{{ keystone_host }}:5000/v3"
      username: admin
      password: "{{ openstack_admin_password }}"
      project_name: admin
      project_domain_name: default
      user_domain_name: default
  tasks:
  - name: Create user heat_domain_admin_test in domain heat
    os_user:
      auth: "{{ openstack_auth }}"
      name: heat_domain_admin_test
      domain: heat
  - name: Assign admin role to user heat_domain_admin_test in domain heat
    os_user_role:
      auth: "{{ openstack_auth }}"
      user: heat_domain_admin_test
      domain: heat
      role: admin
```

##### EXPECTED RESULTS

User role is assigned

##### ACTUAL RESULTS

```
TASK [Assign admin role to user heat_domain_admin_test in domain heat] *******************************************************************************************************
fatal: [openstack_s2]: FAILED! => {"changed": false, "msg": "Must specify either a domain or project"}
```
The problem is the line 158: `domain_id = None` https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_user_role.py#L158 

This unconditional assignment to `None` is done after the parameter `domain` is processed.

### PR DESCRIPTION
**Pull request by valerytschopp**
##### SUMMARY

Fixes #66525

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

os_user_role

##### ADDITIONAL INFORMATION

```
TASK [Assign admin role to user heat_domain_admin_test in domain heat] *******************************************************************************************************
changed: [openstack_s2] => {"changed": true}
```

### CODE REVIEW

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by valerytschopp** [comment]
Hey @sshnaidm 
Ok, I can start a gerrit, but before I need to submit the bug in https://bugs.launchpad.net/openstack/+filebug, right? I don't find the ansible-collections-openstack project, so in which openstack project should I submit the bug?

**Comment by sshnaidm** [comment]
@valerytschopp please use storyboard for bugs: https://storyboard.openstack.org/#!/project/openstack/ansible-collections-openstack

**Comment by valerytschopp** [comment]
@sshnaidm like this https://storyboard.openstack.org/#!/story/2007184 ?

**Comment by sshnaidm** [comment]
@valerytschopp nice done! You can put in commit message in Gerrit "Story: #Number_of_Story", for example "Story: #2006847" like here: https://review.opendev.org/#/c/703381/ and it will link your patch to story.
Please be aware that this week we are in transition, so it may require rebases and reviews will be delayed.

**Review by sshnaidm — CHANGES_REQUESTED** [review]
Because we moved Openstack Ansible modules to Openstack repositories, please submit all changes from openstack modules to Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack Thanks for your contribution and sorry for inconvienience.

**Comment by valerytschopp** [comment]
Story: https://storyboard.openstack.org/#!/story/2007184

Review: https://review.opendev.org/#/c/703428/

**Comment by Akasurde** [comment]
@valerytschopp Thanks for the contribution. Closing as per above.

**Pull request closed without merging**
