### PR TITLE
Add iam_role integration test

### PR DESCRIPTION
**Pull request by cahlchang**
##### SUMMARY

Added integration test.

Related
#39002 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

iam_role

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.2
  config file = None
  configured module search path = ['/my_path/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/pyenv/versions/3.6.3/envs/devel/lib/python3.6/site-packages/ansible
  executable location = /usr/local/pyenv/versions/devel/bin/ansible
  python version = 3.6.3 (default, Dec 13 2017, 03:46:07) [GCC 4.8.2]
```

##### ADDITIONAL INFORMATION

Integration test has been added to the iam role module.

I wrote a test individually for each parameter.
I thought whether to cover more tests or whether to simplify, but I thought that this was just fine.

Thank you for your opinion.

### CODE REVIEW

**Comment by cahlchang** [comment]
@s-hertel 
Hmm ...
I seem to have no write authority for IAM used by CI.
Is there anything I can do to grant privileges to CI?
Or have you mistaken something?

**Comment by mattclay** [comment]
This is failing due to lack of permissions in CI. However, we may not be able to safely test this module in CI due to the permissions required. Thoughts @s-hertel ?

**Comment by s-hertel** [comment]
I don't think these are safe to run in CI in conjunction with the assume role permissions for other tests so I added the unsupported alias. The tests look good to me, thanks @cahlchang for adding them.

@cahlchang So people can run these locally before merging things to iam_role, the necessary permissions should be added to hacking/aws_config/testing_policies/. Do you mind doing that? Here is the policy I added for myself to get the tests to run:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "iam:CreateInstanceProfile",
                "iam:GetRole",
                "iam:ListInstanceProfilesForRole",
                "iam:PassRole",
                "iam:DetachRolePolicy",
                "iam:ListAttachedRolePolicies",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:AttachRolePolicy",
                "iam:AddRoleToInstanceProfile"
            ],
            "Resource": [
                "arn:aws:iam::448830907657:instance-profile/*",
                "arn:aws:iam::448830907657:role/*"
            ]
        }
    ]
}
```

**Review by s-hertel — CHANGES_REQUESTED** [review]
Permissions should be added to hacking/aws_config/testing_policies/ before merging. Besides that, LGTM.

**Comment by cahlchang** [comment]
@s-hertel 
Certainly, it is not safe to run this test on CI in terms of security.
I think it is right decision not to test on CI.
Thanks for examples of permissions and aliases!
The idea of moving locally seems to be very good, so I'll try on it.

**Comment by cahlchang** [comment]
I added a similar policy.
Please review whether it is the same as the way you are thinking.
I think the policy itself is fine, but the usage of "hacking/aws_policy" may be wrong.

**Comment by s-hertel** [comment]
@cahlchang A few months ago another pull request added an iam_role test suite. I don't see anything in these tests that isn't currently being tested by the iam_role test so I'm closing this. I'm sorry, this was an oversight on my part that your pull request wasn't merged long ago.

**Pull request closed without merging**
