### PR TITLE
Fixes #37209 - Added complex return value, instance

### LINKED ISSUE #37209: RDS docs don't mention the attributes "endpoint" and "instance" of the return value
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
rds

##### ANSIBLE VERSION
2.4

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The attributes "endpoint" and "instance" of the return value of the RDS module aren't documented. [The documentation](http://docs.ansible.com/ansible/latest/rds_module.html#return-values) doesn't mention either of them, even though the example code does. 

##### STEPS TO REPRODUCE
1. Go to http://docs.ansible.com/ansible/latest/rds_module.html#return-values.

##### EXPECTED RESULTS
Find documentation for "endpoint" and "instance".

##### ACTUAL RESULTS
Don't find documentation for "endpoint" or "instance".

### PR DESCRIPTION
**Pull request by lpkirby**
##### SUMMARY
Fixes #37209 - Added the instance complex return value

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

rds

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by acozine** [comment]
Interesting. When I build the docs from this branch, the Return Value entries are not alphabetized, which makes it much harder to find any particular sub-element within `instance`. Current published:
screen shot 2018-12-17 at 11 53 30 am
This branch:
screen shot 2018-12-17 at 11 54 26 am

**Comment by lpkirby** [comment]
@acozine Interesting.  I wonder if that could be a consequence of moving them under the "contains" of the instance return value.  The PR diff also looked overly complex to me.  I assumed it was just how the diff read it.  All I did was add the instance return type and then indent the rest of the values to be part of the contains section.

**Comment by Daemoen** [comment]
The changes look good, but I do have one question -- Do we define anywhere what type of return values can be expected and the format for them when using an ansible module to begin with?  It might also be nice as documentation continues to build to link bad to the dev docs with what the return types are (in this case,  string could link back to a simple description of 'utf string',  and complex could give a more detailed explanation of what/why it is complex.  Doesn't particularly apply just to this, more a generic thought, but came up because of the number of nested 'complex' return types in this.  Apart from that, it looks good, and assuming that the return values have all been verified, nice change!

**Comment by acozine** [comment]
@Daemoen good question, and thanks for adding a review to this PR. I don't think we have documentation for return value types. The closest material I know of is https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#return-block. If you want to pursue the question, I encourage you to open an issue, create a pull request with suggested additions/changes, and/or join the Ansible Documentation Working Group. For tips on making documentation contributions, see https://docs.ansible.com/ansible/devel/community/documentation_contributions.html#community-documentation-contributions. For information on the Docs Working Group, see https://github.com/ansible/community/issues/389, or just join the #ansible-docs channel on freenode IRC.

**Comment by lpkirby** [comment]
@acozine I noticed this PR had a conflict so I rebased it and fixed it.

I also noticed that the complex return value "db_subnet_groups" is not alphabetized either.  So it must be a consequence of putting all the values in a contains section of a return value.  If there is something I need to do to address this I'm happy to do it.

**Comment by acozine** [comment]
@lpkirby thanks for rebasing (and for the whole PR!). The alphabetization question has been addressed by #50315.

**Pull request merged**
