### PR TITLE
Backport fixes for k8s module 2.6

### PR DESCRIPTION
**Pull request by fabianvf**
##### SUMMARY

Backport:
- ~~https://github.com/ansible/ansible/pull/40730~~
- https://github.com/ansible/ansible/pull/42132
- https://github.com/ansible/ansible/pull/42202
- https://github.com/ansible/ansible/pull/42277
- ~~https://github.com/ansible/ansible/pull/42377~~

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

k8s

### CODE REVIEW

**Comment by fabianvf** [comment]
rebuild_merge

**Comment by fabianvf** [comment]
@maxamillion don't think the build failure is related, or if it is not sure what would cause it. Looks like it failed to find the openshift python client.

**Comment by maxamillion** [comment]
rekicking CI, network timeouts seem to be failing unrelated tests

**Comment by mattclay** [comment]
bot_status

**Comment by mattclay** [comment]
Two of the PRs being backported appear to be new features rather than bug fixes:

https://github.com/ansible/ansible/pull/40730
https://github.com/ansible/ansible/pull/42377

Normally only bug fixes are backported to stable releases.

**Comment by fabianvf** [comment]
I suppose they are features. I was really hoping #40730 could make it back, because many existing kubernetes files are multidocument yaml, which can't be read by the from_yaml. This means a large portion of existing kubernetes projects can't be easily automated in Ansible 2.6.

#42377 is a follow-up that enabled lists as well, as a stop-gap for proper support of *List kinds in the Python client.

These two PRs together fix a lot of behavior that makes the modules look broken from a user perspective, without them they may have to make significant changes to their templates to make their existing kubernetes definitions work in Ansible.

**Comment by willthames** [comment]
For #40730 we could just document the workaround for multi-document yaml

```
k8s:
  definition="{{ item }}"
loop: "{{ lookup('template', 'resource.yaml').split('\n---\n')|map('from_yaml')|select('ne', None)|list) }}"
```

**Comment by fabianvf** [comment]
@mattclay should I take those two out and bring them up at the next community meeting to discuss backporting them?

**Comment by fabianvf** [comment]
@mattclay removed the offending commits.

**Comment by fabianvf** [comment]
Failures seem unrelated, can we rekick?

**Comment by fabianvf** [comment]
ping @mattclay

**Pull request merged**
