### PR TITLE
Add rax_queue module to create/delete Rackspace Cloud Queues

### PR DESCRIPTION
**Pull request by claco**

### CODE REVIEW

**Comment by claco** [comment]
@sivel Here's another log for the fire. Mostly so the work doesn't get lost. :-)

Seems there's also a bug in pyrax at the moment where `client_id`  is required even for non-message based requests, like listing queues.

https://github.com/rackspace/pyrax/issues/244

**Comment by jctanner** [comment]
@sivel and @angstwad any comments on this?

**Comment by sivel** [comment]
I will look at this tonight or tomorrow.

**Comment by sivel** [comment]
Looks like there are some things that need changed.  First, it looks like the bug in pyrax was fixed, so I am guessing the client_id stuff can be removed from this module.  @claco can you confirm?

Second, the module needs updated to use the new rax auth stuff.  Here is a diff for that change (plus a few other small things):

``` diff
@@ -20,7 +20,7 @@
 short_description: create / delete a queue in Rackspace Public Cloud
 description:
      - creates / deletes a Rackspace Public Cloud queue.
-version_added: "1.4"
+version_added: "1.5"
 options:
   api_key:
     description:
@@ -87,14 +87,14 @@
 try:
     import pyrax
 except ImportError:
-    print("failed=True msg='pyrax required for this module'")
+    print("failed=True msg='pyrax is required for this module'")
     sys.exit(1)


 def cloud_queue(module, state, name, client_id):
     for arg in (state, name):
         if not arg:
-            module.fail_json(msg='%s is required for rax_clb' % arg)
+            module.fail_json(msg='%s is required for rax_queue' % arg)

     changed = False
     queues = []
@@ -141,49 +141,30 @@


 def main():
+    argument_spec = rax_argument_spec()
+    argument_spec.update({
+        client_id=dict(),
+        name=dict(),
+        state=dict(default='present', choices=['present', 'absent']),
+    })
+
     module = AnsibleModule(
-        argument_spec=dict(
-            api_key=dict(),
-            client_id=dict(),
-            credentials=dict(aliases=['creds_file']),
-            name=dict(),
-            region=dict(),
-            state=dict(default='present', choices=['present', 'absent']),
-            username=dict()
-        )
+        argument_spec=argument_spec,
+        required_together=rax_required_together()
     )

-    api_key = module.params.get('api_key')
     client_id = module.params.get('client_id')
-    credentials = module.params.get('credentials')
     name = module.params.get('name')
-    region = module.params.get('region')
     state = module.params.get('state')
-    username = module.params.get('username')

-    try:
-        username = username or os.environ.get('RAX_USERNAME')
-        api_key = api_key or os.environ.get('RAX_API_KEY')
-        credentials = (credentials or os.environ.get('RAX_CREDENTIALS') or
-                       os.environ.get('RAX_CREDS_FILE'))
-        region = region or os.environ.get('RAX_REGION')
-    except KeyError, e:
-        module.fail_json(msg='Unable to load %s' % e.message)
-
-    try:
-        pyrax.set_setting('identity_type', 'rackspace')
-        if api_key and username:
-            pyrax.set_credentials(username, api_key=api_key, region=region)
-        elif credentials:
-            credentials = os.path.expanduser(credentials)
-            pyrax.set_credential_file(credentials, region=region)
-        else:
-            raise Exception('No credentials supplied!')
-    except Exception, e:
-        module.fail_json(msg='%s' % e.message)
+    setup_rax_module(module, pyrax)

     cloud_queue(module, state, name, client_id)

+
+# import module snippets
 from ansible.module_utils.basic import *
+from ansible.module_utils.rax import *

+### invoke the module
 main()
```

**Comment by claco** [comment]
@sivel Thanks for that. Much like the identity module, just wanted to toss the draft work up so it didn't get lost. I'll get the PR updated this morning with this.

**Comment by claco** [comment]
@sivel @jctanner Updated with the patch + client_id removed. Yes, that's fixed in pyrax 1.6.2. Rebased.

**Comment by jctanner** [comment]
@claco thank you!

**Comment by claco** [comment]
No, thank you sir!

**Pull request merged**
