### PR TITLE
updated to describe required parameter

### PR DESCRIPTION
**Pull request by sugitk**
##### SUMMARY

according to 'state', described required parameters

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

The customer requested

### CODE REVIEW

**Comment by sugitk** [comment]
It seems my modification was wrong with Shippable.  Could anyone tell me how to fix those errors?

**Comment by acozine** [comment]
@sugitk I think it wants all lines in the `description` to start with ` - `. Try updating https://github.com/ansible/ansible/pull/56197/files#diff-dea76a894873bd8fbd3173b3a8610a11R199 to look like the other lines and see if that helps.

**Comment by acozine** [comment]
Thanks @sugitk for sharing your experience with the entire Ansible community. I added some nitpicky changes to the punctuation and will merge this now.

**Comment by sugitk** [comment]
@acozine Thank you for your review and merge!

**Pull request merged**
