### PR TITLE
adding some notes for "add_host" documentation

### PR DESCRIPTION
**Pull request by cloudsurf-digital**
Added notes for add_host documentation

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this!

BTW, noticed the caption on this is just "devel".

You should probably send pull requests on some other branch you start off devel instead as if you update later you are going to get more commits in here that might not be related to this one.

**Comment by mpdehaan** [comment]
editing caption...

**Comment by cloudsurf-digital** [comment]
Thanks Michael, i will do so in my next pull request...

**Comment by mpdehaan** [comment]
FYI:  This now has merge commits in the pull request so I can't merge it automatically.

Please make sure you create a new branch for each pull request and always use git rebase vs git merge so this does not occur.

I will cherry-pick these manually just see notes about what I mentioned above for why this happens.

Thanks!

**Comment by mpdehaan** [comment]
(A) please avoid merge commits in contributions.  Use "git pull --rebase" vs "git pull" and "git rebase" vs "git merge".

(B) I'm not sure we need the above note because it seems the point of limit to filter all host groups, even ones created here, so I am thinking we don't need to add the note.

**Pull request closed without merging**
