### PR TITLE
Toshio is now release manager for 2.8 and future 2.6

### PR DESCRIPTION
**Pull request by abadger**
##### SUMMARY
Fix Roadmap docs for Toshio taking over release management duty

In the future, we might not want to list the RM by name (since it will be a dedicated person/team who is doing RM work).

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by dagwieers** [comment]
Ok, so this information was also listed on the wiki:
https://github.com/ansible/community/wiki/RelEng

I think there's value in having a name (or GitHub handle) so you can address someone.

**Comment by abadger** [comment]
<nod> jctanner and I were thinking of an email alias or mailing list. (although that doesn't take care of having a github handle).

**Comment by dagwieers** [comment]
I guess it is not that important, PRs against a stable branch will end up with the release manager(s), and that's fine. Maybe the wiki page could include a list of people involved with Release Management (just like any other WG) instead in case people have questions or feedback.

**Comment by abadger** [comment]
Yeah, the wiki page makes the most sense to me. Maybe have future roadmaps point to the wiki page for who to contact and just keep the wiki page up to date.

**Pull request merged**
