### PR TITLE
Intentional tests from incidental_setup_mongodb, incidental_mongodb_parameter

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Related https://github.com/ansible/ansible/issues/74402

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
tests

### CODE REVIEW

**Comment by mattclay** [comment]
@mkrizek It looks like this PR has a merge conflict now.

**Comment by mkrizek** [comment]
> @mkrizek It looks like this PR has a merge conflict now.

Fixed.

**Review by mattclay — CHANGES_REQUESTED** [review]
@mkrizek The test additions look good. Can you omit the removal of the incidental tests from this PR?

Once this is merged and we have new coverage results we'll be able to remove the incidental tests if they no longer provide any unique coverage.

**Comment by mkrizek** [comment]
> @mkrizek The test additions look good. Can you omit the removal of the incidental tests from this PR?
> 
> Once this is merged and we have new coverage results we'll be able to remove the incidental tests if they no longer provide any unique coverage.

Done.

**Review by mattclay — APPROVED** [review]

**Pull request merged**
