### PR TITLE
new voss_facts module

### PR DESCRIPTION
**Pull request by LindsayHill**
##### SUMMARY

New networking module to collect facts from Extreme VOSS devices, e.g. [VSP 4000 series](https://www.extremenetworks.com/product/vsp-4000-series/)

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
voss_facts
##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (voss_facts 1e53cdc56b) last updated 2018/08/15 14:29:41 (GMT -700)
  config file = /Users/lhill/github/ansible-extreme/slxos/playbooks/ansible.cfg
  configured module search path = [u'/Users/lhill/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lhill/github/ansible/lib/ansible
  executable location = /Users/lhill/github/ansible/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### ADDITIONAL INFORMATION

Known limitation:
- This module only collects IP addresses for the default VRF. It does not collect IP addresses for other VRFs that may be configured.

Example output
```shell
(venv)lindsaysmacbook:playbooks lhill$ ansible -m voss_facts vsp200 -a "gather_subset=all"
vsp200 | SUCCESS => {
    "ansible_facts": {
        "ansible_net_all_ipv4_addresses": [
            "10.10.10.10",
            "1.1.1.1"
        ],
        "ansible_net_all_ipv6_addresses": [
            "2011:0:0:0:0:0:0:1",
            "2001:0:0:0:0:0:0:1",
            "2002:0:0:0:0:0:0:1",
            "fe80:0:0:0:251:ff:fe16:4100"
        ],
        "ansible_net_config": "Preparing to Display Configuration...\n#\n<snip># IP ECMP APPLY CONFIGURATIONS\n\n\n\n\nend",
        "ansible_net_gather_subset": [
            "hardware",
            "default",
            "interfaces",
            "config"
        ],
        "ansible_net_hostname": "VSP-8284XSQ",
        "ansible_net_interfaces": {
            "1/1": {
                "adminstatus": "down",
                "bandwidth": "0",
                "description": "serverA",
                "duplex": "full",
                "macaddress": "00:51:00:16:40:00",
                "mediatype": "10GbNone",
                "mtu": "1950",
                "operstatus": "down",
                "type": "Ethernet"
            },
            "1/10": {
                "adminstatus": "down",
                "bandwidth": "0",
                "description": "",
                "duplex": "full",
                "macaddress": "00:51:00:16:40:09",
                "mediatype": "10GbNone",
                "mtu": "1950",
                "operstatus": "down",
                "type": "Ethernet"
            },
<snip>
            "2/9": {
                "adminstatus": "down",
                "bandwidth": "0",
                "description": "",
                "duplex": "full",
                "macaddress": "00:51:00:16:40:48",
                "mediatype": "10GbNone",
                "mtu": "1950",
                "operstatus": "down",
                "type": "Ethernet"
            },
            "Clip1": {
                "ipv4": [
                    {
                        "address": "1.1.1.1",
                        "subnet": "255.255.255.255"
                    }
                ],
                "ipv6": [
                    {
                        "address": "2011:0:0:0:0:0:0:1",
                        "subnet": "128"
                    }
                ],
                "type": "Loopback"
            },
            "Vlan1": {
                "ipv4": [
                    {
                        "address": "10.10.10.10",
                        "subnet": "255.255.255.0"
                    }
                ],
                "ipv6": [
                    {
                        "address": "2001:0:0:0:0:0:0:1",
                        "subnet": "64"
                    },
                    {
                        "address": "2002:0:0:0:0:0:0:1",
                        "subnet": "64"
                    },
                    {
                        "address": "fe80:0:0:0:251:ff:fe16:4100",
                        "subnet": "64"
                    }
                ],
                "type": "VLAN"
            }
        },
        "ansible_net_memfree_mb": 618,
        "ansible_net_memtotal_mb": 1002,
        "ansible_net_model": "8284XSQ",
        "ansible_net_serialnum": "",
        "ansible_net_version": "7.0.0.0_B015"
    },
    "changed": false
}
(venv)lindsaysmacbook:playbooks lhill$
```

### CODE REVIEW

**Review by ganeshrn — APPROVED** [review]

**Comment by zchencq** [comment]
awesome! finally a network module for voss available:)

One question: is this module supposed to work with ERS switches (e.g ers 5952gts-pwr+) as well? 

Cheers,
Zhen

**Comment by LindsayHill** [comment]
@zchencq this is the second module for VOSS. `voss_command` has already been merged. 

This has only been tested against VSP systems. It has not been tested against ERS. I am not planning on doing any testing with ERS. You are welcome to do your own testing and update the code and add more test cases to cover ERS.

**Comment by zchencq** [comment]
@LindsayHill I'm currently having an issue with ERS switches by using your module. It's caused by the fact that you have to enter "Ctrl + Y" to begin with. Any ideas how to fix this (without disabling the banner)?

**Comment by LindsayHill** [comment]
Probably in plugins/terminal/voss.py, overriding `terminal_initial_prompt` and `terminal_initial_answer`. Look at some of the other vendors, such as Aruba. 

You will have to ensure it does not break VOSS integration. If it is not possible to combine these, you will need to create separate modules for ERS. I have no plans to do any testing of the VOSS modules with ERS.

**Comment by zchencq** [comment]
@LindsayHill  thanks a lot for your info. I realize that our ERS 5900 switches are actually running BOSS (instead of VOSS), not sure how big the differences are, but it's better to create separate BOSS module. Do you happen to know if Extreme has any plan to implement BOSS module (to support ERS)?

Thx

**Comment by LindsayHill** [comment]
I don’t know of anyone else working on ERS modules. I have no plans to do so.

**Pull request merged**
