### PR TITLE
adding the ability to specify roles when adding/modifying a mongo user

### PR DESCRIPTION
**Pull request by podollb**

### CODE REVIEW

**Comment by jimi-c** [comment]
Thanks, testing now.

**Comment by jimi-c** [comment]
So it looks like you're using 2.4 roles, while CentOS 6.3 (my test system) is using 2.2, which has a completely different security setup. When using this, I get the following traceback:

<pre>
fatal: [192.168.x.x] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1376340628.13-87476252191195/mongodb_user", line 1140, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1376340628.13-87476252191195/mongodb_user", line 201, in main
    if user_add(client, db_name, user, password, roles) is not True:
  File "/root/.ansible/tmp/ansible-1376340628.13-87476252191195/mongodb_user", line 118, in user_add
    db.add_user(user, password, None, roles=roles)
TypeError: add_user() takes exactly 3 non-keyword arguments (4 given)
</pre>

Since 2.2 is still supported, you may need to take this into account.

**Comment by podollb** [comment]
So in this type of situation should I specify that this new "roles" param is only supported on mongodb 2.4+ (in the docs for that param). And then handle things gracefully, with an error, if someone attempts to use it on an earlier version (catch the exception and display a proper error message).

**Comment by jimi-c** [comment]
That's pretty much how I'd do it. 

1) Only use the roles in the add_user function if they're specified
2) Detect the mongodb version and use fail_json to report back that roles are only supported on mongo 2.4+ if the version isn't high enough
3) update the docs accordingly so users know the roles option is a new mongo option

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
