### PR TITLE
Overhaul ansible-test cloud test plugins.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Overhaul ansible-test cloud test plugins.

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

ansible-test

##### ADDITIONAL INFORMATION

This PR changes how "cloud" plugins for ansible-test are able to affect the test environment:

- The command used to execute the tests can no longer be read or altered. Previously this was used to pass `-e` to ansible commands. This is no longer necessary.
- Environment variables passed to tests can only be set. Previously the dictionary of environment variables to pass to tests was accessible, so values could also be read and removed. No current plugins utilized the ability to read or remove environment variables.
- Environment variables are passed to role based tests using the `environment` play keyword. This makes the environment variables available to modules even when the `local` connection plugin is not being used. Previously environment variables were set in the environment used to invoke `ansible-playbook`, which made them available to `ansible-playbook` as well as modules executed using the `local` connection plugin.
- Environment variables are passed to script based tests as regular environment variables. This behavior has not changed.
- Ansible variables for role based tests are passed using the `vars` play keyword. Previously individual variables were passed to tests using `-e key=value` arguments.
- Ansible variables for script based tests are written to a temporary vars YAML file and passed to tests using `-e @path_to_vars_yaml_file` arguments. Previously individual variables were passed to tests using `-e key=value` arguments. Scripts can still access the vars when invoking ansible commands using `$@`.
- Module defaults can now be set by plugins at the play level. Previously this was not possible.
- Script based tests can use module defaults by passing `$@` to `ansible-playbook` and using `module_defaults: '{{ ansible_test.module_defaults }}'`.
- Script based tests can pass environment variables to modules when using connection plugins other than `local` by passing `$@` to `ansible-playbook` and using `environment: '{{ ansible_test.environment }}'`.
- Plugins can now request additional callback plugins be whitelisted when running tests. Previously this would have been done by appending to the `ANSIBLE_CALLBACK_WHITELIST` environment variable, which is no longer possible, since environment variables cannot be read.
- Plugins now default to using INI format for their configuration files. This makes working with the configuration in Python easier, as ConfigParser can be used. Previously plugins used a mix of mostly INI and JSON.
- Most plugins now load their configuration file and read the variables from there. Previously those plugins would reference the configuration file by path using an environment variable. Making these values inline removes the need to transfer the file to the remote system to make it accessible to modules.

These changes are being made to support running integration tests using connection plugins other than `local` where the controller and remote may not even be the same system.

### CODE REVIEW

**Comment by resmo** [comment]
even though it is no issue we should consider to rename this thing to a more appropriate name other than "cloud" test plugins: API test plugins?

**Comment by mattclay** [comment]
@resmo I thought of renaming it shortly after it was initially implemented, as it quickly became clear it was going to be used for more than its original purpose of testing cloud related modules. I've been working on other test infrastructure changes so I haven't wanted to work on renaming it, as it will touch code and docs in quite a few places.

**Review by jborean93 — APPROVED** [review]

**Comment by Fred-sun** [comment]
@yungezz @zikalino @yuwzho  review_need

**Review by yungezz — APPROVED** [review]

**Review by jborean93 — APPROVED** [review]

**Pull request merged**
