### PR TITLE
Add new command ClearSessions

### LINKED ISSUE #65599: redfish_command - Manager - ClearSessions
##### SUMMARY

This feature would implement a ClearSessions command for the Sessions category of redfish_command, to clear all active sessions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

redfish_command.py
redfish_utils.py

##### ADDITIONAL INFORMATION

This command would help user to clear all active sessions.

```yaml

```

### PR DESCRIPTION
**Pull request by renxulei**
##### SUMMARY

add ClearSessions in redfish_command module to clear all active sessions

Fixes #65599 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

redfish_utils.py
redfish_command.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by billdodd** [comment]
Thanks for the PR. LGTM.

shipit

**Comment by renxulei** [comment]
@jose-delarosa @mraineri @tomasg2012  Could you help to review this and merge it? Thanks!

**Comment by mraineri** [comment]
One thing we should be cautious about here is if we ever decide to incorporate Redfish Sessions into Ansible, and this command were invoked while another client is also using sessions, we'd block out the other client. This might be okay since I wouldn't expect something like this to be done regularly (probably just an administrative ability that you might need to do when something is going wrong).

I'll need to spend some time looking more in-depth at this PR, but generally the concept looks good.

**Comment by renxulei** [comment]
@mraineri Many thanks for your feedback, I understood your concern and it is reasonable.  Why I raised this PR, because on some scenarios, administrator may need to take action to kick users off from the sessions already connected. For example, one scenario as you said, something is wrong and administrator need to restore system or collect the info for investigation, he need to block possible impacts from other users' action immediately. Another is, administrator may need to change some security policy, user privilege or password, but these changes may not take effect immediately (depends on BMC implementation) until current sessions were closed. And as you said, this command should not be invoked regularly, only happen on some specific scenarios.  Please take time to consider the scenarios I listed, I think this command will be helpful, thanks!

**Comment by mraineri** [comment]
shipit

**Pull request merged**
