### PR TITLE
replaced outdate release info with checkmarks

### PR DESCRIPTION
**Pull request by samccann**
##### SUMMARY

Partially addresses #52997 
##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs.ansible.com
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by samccann** [comment]
The current table is getting wide, and has version details that aren't required anymore.  Here is the existing version:

image


And here is what this PR makes it look like now:

image

**Comment by acozine** [comment]
I like this look - the table is more readable and now we can add more connection types as necessary.

**Review by gundalow — APPROVED** [review]
Oh, that's great. Much more readable.

**Comment by samccann** [comment]
..making it wip for a day or  two to ensure the networking folks have a look before we merge

**Comment by samccann** [comment]
got network team approval so removing the wip status. this PR is ready to merge

**Pull request merged**
