### PR TITLE
AWS EMR Module

### PR DESCRIPTION
**Pull request by ferrants**
Module for managing EMR clusters. We have been using this for months and would like to contribute it back.

@mbomio FYI

### CODE REVIEW

**Comment by ferrants** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/1269

**Comment by ferrants** [comment]
in case someone

**Comment by joshmullis** [comment]
@ferrants Did you give up on getting them to merge this?  :)

**Comment by ferrants** [comment]
@joshmullis yeah, i gave up, they're too slow to merge things

**Comment by joshmullis** [comment]
Going to hit up redhat and see if they can get this on the radar to be merged sometime in the future.
Will let you know.

**Comment by ferrants** [comment]
I'll reopen this on Monday then. Thanks.

**Pull request closed without merging**
