### PR TITLE
Adding Support for NVE Protocol in onyx_protocol

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Adding Support for nve protocol in onyx_protocol

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
lib/ansible/modules/network/onyx/onyx_protocol.py
test/units/modules/network/onyx/test_onyx_protocols.py

##### ADDITIONAL INFORMATION

```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev8/lib/ansible
  executable location = /.autodirect/mtrswgwork/anasb/ansible_dev8/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

### CODE REVIEW

**Comment by anasbadaha** [comment]
Hi @samerd,

Please review the following PR and approve if it is OK for you.

Thanks

**Review by samerd — APPROVED** [review]
Thanks Anas.
looks great!

**Comment by anasbadaha** [comment]
Hi @justjais,

Can you please merge this PR if it is OK for you?

Thanks

**Review by ganeshrn — APPROVED** [review]

**Comment by ganeshrn** [comment]
@anasbadaha @samerd Thank you!

**Pull request merged**
