### PR TITLE
Track and display more info about Conditionals

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY

An attempt to make it easier to figure out why a conditional/when expression
evaluates to false. Especially for cases where the conditional/when has multiple expressions.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/playbook/conditional.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (conditional_details 2fe2301c9e) last updated 2017/05/03 12:25:36 (GMT -400)
  config file = /home/adrian/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/ansible/my-modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]


```

##### ADDITIONAL INFORMATION

Some examples of the added detail:

conditional is a list
----------------------

``` yaml
- name: when when is a list of whens with one false
  debug:
    msg: 'I was truthy.'
  when:
    - "result.changed"
    - True
    - "'blippy' == 'blippy'"
    - "result.rc <= 37"
    - "result.stdout == 'Some value that is different from stdout'"
```

output from devel:
```
TASK [conditionals_foo : when when is a list of whens with one false] **********
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:293
skipping: [testhost] => {
    "skip_reason": "Conditional result was False"
}
```

output from branch:

```
TASK [conditionals : when when is a list of whens with one false] **************
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:293
skipping: [testhost] because:
    'result.stdout == 'Some value that is different from stdout'' is False
 => {
    "changed": false, 
    "skip_reason": [
        {
            "conditional": "result.stdout == 'Some value that is different from stdout'", 
            "value": false
        }
    ], 
    "skipped": true
}
```

conditional is a list with many falses
--------------------------------------------
``` yaml
- name: when when is a list of whens with many many falses
  debug:
    msg: 'I was truthy.'
  when:
    - "True == False"
    - False
    - "'blippy' == 'sdfblippy'"
    - "result.rc >= 37"
    - "result.stdout == 'Some value that is different from stdout'"
```

devel:

```
TASK [conditionals_foo : when when is a list of whens with many many falses] ***
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:304
skipping: [testhost] => {
    "skip_reason": "Conditional result was False"
}
```

branch:

```
TASK [conditionals : when when is a list of whens with many many falses] *******
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:304
skipping: [testhost] because:
    'True == False' is False
    'False' is False
    ''blippy' == 'sdfblippy'' is False
    'result.rc >= 37' is False
    'result.stdout == 'Some value that is different from stdout'' is False
 => {
    "changed": false, 
    "skip_reason": [
        {
            "conditional": "True == False", 
            "value": false
        }, 
        {
            "conditional": false, 
            "value": false
        }, 
        {
            "conditional": "'blippy' == 'sdfblippy'", 
            "value": false
        }, 
        {
            "conditional": "result.rc >= 37", 
            "value": false
        }, 
        {
            "conditional": "result.stdout == 'Some value that is different from stdout'", 
            "value": false
        }
    ], 
    "skipped": true
}
```

conditional with with_items and defined variable checks
--------------------------------------------------------------------

``` yaml
- set_fact: skipped_bad_attribute=True
- block:
  - name: test a with_items loop using a variable with a missing attribute
    debug: var=item
    with_items: "{{cond_bad_attribute.results | default('')}}"
    register: result
  - set_fact: skipped_bad_attribute=False
  - name: assert the task was skipped
    assert:
      that:
      - skipped_bad_attribute
  when: cond_bad_attribute is defined and 'results' in cond_bad_attribute
```

devel:

```
TASK [conditionals_foo : set_fact] *********************************************
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:315
ok: [testhost] => {
    "ansible_facts": {
        "skipped_bad_attribute": true
    }, 
    "changed": false, 
    "failed": false
}

TASK [conditionals_foo : test a with_items loop using a variable with a missing attribute] ***
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:317
skipping: [testhost] => (item=)  => {
    "item": "", 
    "skip_reason": "Conditional result was False"
}

TASK [conditionals_foo : set_fact] *********************************************
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:321
skipping: [testhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [conditionals_foo : assert the task was skipped] **************************
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:322
skipping: [testhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

```

branch:
```
TASK [conditionals : set_fact] *************************************************
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:315
ok: [testhost] => {
    "ansible_facts": {
        "skipped_bad_attribute": true
    }, 
    "changed": false
}

TASK [conditionals : test a with_items loop using a variable with a missing attribute] ***
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:317
skipping: [testhost] => (item=)  => {
    "changed": false, 
    "item": "", 
    "skip_reason": [
        {
            "conditional": "cond_bad_attribute is defined and 'results' in cond_bad_attribute", 
            "value": false
        }
    ], 
    "skipped": true
}

TASK [conditionals : set_fact] *************************************************
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:321
skipping: [testhost] because:
    'cond_bad_attribute is defined and 'results' in cond_bad_attribute' is False
 => {
    "changed": false, 
    "skip_reason": [
        {
            "conditional": "cond_bad_attribute is defined and 'results' in cond_bad_attribute", 
            "value": false
        }
    ], 
    "skipped": true
}

TASK [conditionals : assert the task was skipped] ******************************
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:322
skipping: [testhost] because:
    'cond_bad_attribute is defined and 'results' in cond_bad_attribute' is False
 => {
    "changed": false, 
    "skip_reason": [
        {
            "conditional": "cond_bad_attribute is defined and 'results' in cond_bad_attribute", 
            "value": false
        }
    ], 
    "skipped": true
}

```

conditional with with_items and conditional on item and one is skipped
--------------------------------------------------------------------------------------

``` yaml
- name: test a with_items loop skipping a single item
  debug: var=item
  with_items: "{{cond_list_of_items.results}}"
  when: item != 'b'
  register: result
```

devel:
```
TASK [conditionals_foo : test a with_items loop skipping a single item] ********
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:328
ok: [testhost] => (item=a) => {
    "item": "a"
}
skipping: [testhost] => (item=b)  => {
    "item": "b", 
    "skip_reason": "Conditional result was False"
}
ok: [testhost] => (item=c) => {
    "item": "c"
}
TASK [conditionals_foo : debug] ************************************************
task path: /root/ansible/test/integration/targets/conditionals_foo/tasks/main.yml:334
ok: [testhost] => {
    "result": {
        "changed": false, 
        "msg": "All items completed", 
        "results": [
            {
                "_ansible_item_result": true, 
                "_ansible_no_log": false, 
                "_ansible_verbose_always": true, 
                "changed": false, 
                "failed": false, 
                "item": "a"
            }, 
            {
                "_ansible_item_result": true, 
                "_ansible_no_log": false, 
                "changed": false, 
                "item": "b", 
                "skip_reason": "Conditional result was False", 
                "skipped": true
            }, 
            {
                "_ansible_item_result": true, 
                "_ansible_no_log": false, 
                "_ansible_verbose_always": true, 
                "changed": false, 
                "failed": false, 
                "item": "c"
            }
        ]
    }
}
```

branch:
```
TASK [conditionals : test a with_items loop skipping a single item] ************
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:328
ok: [testhost] => (item=a) => {
    "item": "a"
}
skipping: [testhost] => (item=b)  => {
    "changed": false, 
    "item": "b", 
    "skip_reason": [
        {
            "conditional": "item != 'b'", 
            "value": false
        }
    ], 
    "skipped": true
}
ok: [testhost] => (item=c) => {
    "item": "c"
}

# NOTE: aside from the formatting from the old branch'es callback, the main diff
TASK [conditionals : debug] ****************************************************
task path: /root/ansible/test/integration/targets/conditionals/tasks/main.yml:334
ok: [testhost] => {
    "result": "{'msg': u'All items completed', 'changed': False, 'results': [{u'item': u'a', '_ansible_item_result': True, '_ansible_verbose_always': True, '_ansible_no_log': False}, {'skipped': True, '_ansible_no_log': False, 'skip_reason': ['item != 'b'' is False], '_ansible_item_result': True, 'item': u'b', 'changed': False}, {u'item': u'c', '_ansible_item_result': True, '_ansible_verbose_always': True, '_ansible_no_log': False}]}"
}
```

Note on that last 'conditionals: debug', aside from formatting diff between different verbosity levels/callbacks, the main diff is the 'skip_reason' value:

devel: "Conditional result was False"
branch:  ['item != 'b'' is False]

```

```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Nice idea.
I could have done with this when debugging a when that used with items and a regex search on each item a couple of days ago.

Just a thought - will no_log: True suppress the output (just in case conditionals contain something sensitive)?

**Comment by mattclay** [comment]
CI failure in multiple unit and integration tests, so I won't include the details here.

**Comment by gundalow** [comment]
Triggering CI

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/25874/36/tests

```
{
"failed": true, 
"msg": "The conditional check 'initial_state.rc == 0' failed. The error was: error while evaluating conditional (initial_state.rc == 0): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/root/ansible/test/integration/targets/locale_gen/tasks/locale_gen.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: debug inital_state when rc\n  ^ here\n"
}
```

**Pull request closed without merging**
