### PR TITLE
Fix ansible-test docker container IP detection.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Fix ansible-test docker container IP detection.

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

ansible-test

##### ADDITIONAL INFORMATION

Resolves issue reported in https://github.com/ansible/ansible/pull/74335

### CODE REVIEW

**Review by goneri — APPROVED** [review]

**Comment by mattclay** [comment]
@goneri Thanks for testing. I've opened a backport for stable-2.11: https://github.com/ansible/ansible/pull/74388

Do you need this backport in 2.10 or earlier?

**Comment by goneri** [comment]
Thank you @mattclay  I believe the code base is different with 2.10. I will open a backport if it's not the case.

**Comment by mattclay** [comment]
@goneri I can open the backport in 2.10. It should be the same as the one for 2.11 (which I already had to modify). Can you confirm the 2.11 backport works for you?

**Comment by mattclay** [comment]
The 2.10 backport is here: https://github.com/ansible/ansible/pull/74389

**Comment by goneri** [comment]
2.9 and 2.10 are also broken and the backports are not trivial.

**Comment by mattclay** [comment]
The 2.9 backport is here: https://github.com/ansible/ansible/pull/74390

**Pull request merged**
