### PR TITLE
Rebased branch of AWS cleanup commits

### PR DESCRIPTION
**Pull request by bpennypacker**
I've added the missing alias documentation for aws_access_key that @lwade spotted and merged all the other AWS cleanup commits into this new pull request.

### CODE REVIEW

**Comment by jimi-c** [comment]
Looks like this still isn't going to merge cleanly, could you do another rebase? Thanks!

**Comment by bpennypacker** [comment]
I'm obviously missing something here.  Why does it need to be rebased again?

**Comment by jimi-c** [comment]
Because github is indicating that it will not merge cleanly.

**Comment by bpennypacker** [comment]
I never saw any errors from github.  Is there any way for me to see what github is complaining about?  It'd be nice to have some sort of indication that can tell me if I'm doing it properly or not.

**Pull request closed without merging**
