### PR TITLE
adds private_ip param to ec2 module

### PR DESCRIPTION
**Pull request by joelsemar**
When using VPC's it is nice to be able to make use of the private subnet by assigning ip addresses to hosts directly.

apollo@ ~/ansible (devel)$ make tests
PYTHONPATH=./lib nosetests -d -v
test_configfile_and_env_both_set (TestConstants.TestConstants) ... ok
test_configfile_not_set_env_not_set (TestConstants.TestConstants) ... ok
test_configfile_not_set_env_set (TestConstants.TestConstants) ... ok
test_configfile_set_env_not_set (TestConstants.TestConstants) ... ok
test_complex_enumeration (TestInventory.TestInventory) ... ok
test_complex_exclude (TestInventory.TestInventory) ... ok
test_complex_group_names (TestInventory.TestInventory) ... ok
test_complex_intersect (TestInventory.TestInventory) ... ok
test_complex_vars (TestInventory.TestInventory) ... ok
test_dir_inventory (TestInventory.TestInventory) ... ok
Test the case when playbook 'hosts' var is a list. ... ok
test_large_range (TestInventory.TestInventory) ... ok
test_regex_exclude (TestInventory.TestInventory) ... ok
test_script (TestInventory.TestInventory) ... ok
test_script_all (TestInventory.TestInventory) ... ok
test_script_combined (TestInventory.TestInventory) ... ok
test_script_multiple_groups (TestInventory.TestInventory) ... ok
test_script_norse (TestInventory.TestInventory) ... ok
test_script_restrict (TestInventory.TestInventory) ... ok
test_script_vars (TestInventory.TestInventory) ... ok
test_simple (TestInventory.TestInventory) ... ok
test_simple_all (TestInventory.TestInventory) ... ok
test_simple_combined (TestInventory.TestInventory) ... ok
test_simple_norse (TestInventory.TestInventory) ... ok
test_simple_port (TestInventory.TestInventory) ... ok
test_simple_restrict (TestInventory.TestInventory) ... ok
test_simple_ungrouped (TestInventory.TestInventory) ... ok
test_simple_vars (TestInventory.TestInventory) ... ok
test_includes (TestPlayBook.TestPlaybook) ... ok
test_lookups (TestPlayBook.TestPlaybook) ... ok
test_one (TestPlayBook.TestPlaybook) ... ok
test_playbook_vars (TestPlayBook.TestPlaybook) ... ok
test_yaml_hosts_list (TestPlayBook.TestPlaybook) ... ok
test_assemble (TestRunner.TestRunner) ... ok
test_async (TestRunner.TestRunner) ... ok
test_command (TestRunner.TestRunner) ... ok
test_copy (TestRunner.TestRunner) ... ok
test_facter (TestRunner.TestRunner) ... SKIP
test_fetch (TestRunner.TestRunner) ... ok
test_file (TestRunner.TestRunner) ... ok
test_git (TestRunner.TestRunner) ... ok
test_large_output (TestRunner.TestRunner) ... ok
Unit tests for the lineinfile module, without backref features. ... ok
Unit tests for the lineinfile module, with backref features. ... ok
test_ping (TestRunner.TestRunner) ... ok
test_parse_kv_basic (TestUtils.TestUtils) ... ok
test_template_basic (TestUtils.TestUtils) ... ok
test_template_ds_basic (TestUtils.TestUtils) ... ok
test_template_unicode (TestUtils.TestUtils) ... ok
test_template_varReplace_iterated (TestUtils.TestUtils) ... ok
test_template_whitespace (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative2 (TestUtils.TestUtils) ... ok
test_varReplace_alternative (TestUtils.TestUtils) ... ok
test_varReplace_alternative_greed (TestUtils.TestUtils) ... ok
test_varReplace_caps (TestUtils.TestUtils) ... ok
test_varReplace_consecutive_vars (TestUtils.TestUtils) ... ok
test_varReplace_escape_dot (TestUtils.TestUtils) ... ok
test_varReplace_escaped_var (TestUtils.TestUtils) ... ok
test_varReplace_include (TestUtils.TestUtils) ... ok
test_varReplace_include_script (TestUtils.TestUtils) ... ok
test_varReplace_invalid_list (TestUtils.TestUtils) ... ok
test_varReplace_list (TestUtils.TestUtils) ... ok
test_varReplace_list_join (TestUtils.TestUtils) ... ok
test_varReplace_list_nolist (TestUtils.TestUtils) ... ok
test_varReplace_list_oob (TestUtils.TestUtils) ... ok
test_varReplace_middle (TestUtils.TestUtils) ... ok
test_varReplace_multiple (TestUtils.TestUtils) ... ok
test_varReplace_nested (TestUtils.TestUtils) ... ok
test_varReplace_nested_int (TestUtils.TestUtils) ... ok
test_varReplace_nested_list (TestUtils.TestUtils) ... ok
test_varReplace_notcomplex (TestUtils.TestUtils) ... ok
test_varReplace_simple (TestUtils.TestUtils) ... ok
test_varReplace_trailing_dollar (TestUtils.TestUtils) ... ok
test_varReplace_unicode (TestUtils.TestUtils) ... ok
test_varReplace_var_complex_var (TestUtils.TestUtils) ... ok
test_varReplace_var_part (TestUtils.TestUtils) ... ok
test_varReplace_var_partial_part (TestUtils.TestUtils) ... ok

---

Ran 78 tests in 24.829s

OK (SKIP=1)

### CODE REVIEW

**Comment by lwade** [comment]
+1.  We have a the subnet ID in now, next logical step :)

**Comment by mpdehaan** [comment]
Ok, please don't paste the test output in the ticket comment.   That appears in history...

**Comment by mpdehaan** [comment]
ok, that's just your description, but anyway, yeah, no need, just had to scroll by it.  Code looks ok, merging, thanks!

**Comment by mpdehaan** [comment]
Just looking at this, and not so much about the addition...

We need to go through the AnsibleModule constructor's argument_spec and add types where appropriate, required=True where appropriate, and defaults where appropriate...  (ack -a for "type=" in the module code for an example).

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
