### PR TITLE
Expose user_metadata to ansible

### PR DESCRIPTION
**Pull request by Asara**
##### SUMMARY
Allow access to user_metaData from softlayer to ansible

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Softlayer dynamic inventory

##### ANSIBLE VERSION
ansible 2.4.0
```

```

##### ADDITIONAL INFORMATION
Had to add the userData to the fields, and then get the value and return text instead of the extra information since there can only be 1 string of userData per server.

### CODE REVIEW

**Comment by jrosmith** [comment]
+ 1

**Comment by jrosmith** [comment]
+1

**Comment by VitaliyBSD** [comment]
+1

**Comment by 5igm4** [comment]
+1

**Comment by Asara** [comment]
Not functioning as intended.

**Comment by calfonso** [comment]
@Asara this requires a rebase and resolution to any conflicts, then we'll finish the review.

**Comment by jctanner** [comment]
Sorry, I really screwed this one up by trying to use the github UI to fix the merge conflict.

**Comment by s-hertel** [comment]
Fixed in 3b20585.

**Pull request closed without merging**
