### PR TITLE
fix do until to fail on max retries

### PR DESCRIPTION
**Pull request by bennojoy**
This pull request makes the do until feature to fail the task when the maximum retries have been reached. The docs are also updated to reflect the change.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Does this line:
-                    if result.result['attempts'] == retries and not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
-                        result.result['failed'] = True 
-                        result.result['msg'] = "Task failed as maximum retries was encountered"

Indicate the conditional ("when") is run once per do/until loop evaluation?

Since we are no longer doing "number of retries", it would be nice to move the conditional to decide whether to run the operation as all, as opposed to evaluating in a loop counter.  I'm not sure sure this makes sense though, but I figured I would ask.

The other question is have we tested this with a "with_items" operation.  The two should be usable in conjunction as people will most definitely try that.

Thanks!

**Comment by bennojoy** [comment]
@mpdehaan 

Thanks for the suggestions.

The conditional is now moved so that the check is now not done at every iteration. Also there is a separate check which decides if we should run this section of code at all.
if until is not None and result.comm_ok and "failed" not in result.result:

Also i have checked with with_items and it works fine.

**Comment by mpdehaan** [comment]
Can you please submit this as a squashed commit?

That way we won't have the intermediate non-functional commits in the history, with the broken ":" and so on.  This affects things like git bisect.

**Comment by bennojoy** [comment]
A new pr is sent with the updates. #4386

**Pull request closed without merging**
