### PR TITLE
Add installation of PPA signing key to intro_installation.rst

### PR DESCRIPTION
**Pull request by OtherSystems**
Added command to install the repository key to prevent errors

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

 docs/docsite/rst/intro_installation.rst 

##### ANSIBLE VERSION

```
n/a
```

##### SUMMARY

Added the repository key import for the Debian installation manual as without it, apt generates errors about an unknown key.

### CODE REVIEW

**Comment by ryansb** [comment]
This command is correct, and the key fingerprint matches the fingerprint of our PPA [here](https://launchpad.net/~ansible/+archive/ubuntu/ansible).

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
shipit

**Comment by bcoca** [comment]
-1 You should not need it, just need to keep the apt keys updated.

**Comment by bcoca** [comment]
If we want to add a note about 'updating the keyring packages if you are having key issues with keys' I'm not opposed, but that is normally the correct fix vs doing the key directly. Also the error is probably transitory until the next `apt update && apt upgrade` happens and these packages get updated automatically.

**Pull request merged**
