### PR TITLE
New Pure Storage FlashBlade module to manage object store buckets

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Create, delete and recover object store (S3) buckets in a Pure Storge FlashBlade

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
modules/storage/purestorage/purefb_bucket.py

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

### CODE REVIEW

**Comment by sile16** [comment]
If you set state to "absent" and run the playbook twice it will actually eradicate the bucket even though eradicate is not set.  Also, if you try to set state to absent and try also set eradicate to true it fails.

**Comment by sdodsley** [comment]
> If you set state to "absent" and run the playbook twice it will actually eradicate the bucket even though eradicate is not set. Also, if you try to set state to absent and try also set eradicate to true it fails.

Fixed both issues

**Comment by sile16** [comment]
shipit

**Comment by genegr** [comment]
shipit

**Review by sile16 — APPROVED** [review]

**Pull request merged**
