### PR TITLE
Clean up module documentation

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:
- Removal of `default: null` (and variations)
- Removal of `required: false`
- Fixing booleans and `type: bool` where required

This PR also fixed 673 validation issues from *test/sanity/validate-modules/ignore.txt*

This relates to #36901

##### ISSUE TYPE
 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME
module docs

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by gundalow** [comment]
`ansible-test sanity --test validate-modules` failing with:
```
lib/ansible/modules/network/cloudengine/ce_bfd_view.py:0:0: E322 "provider" is listed in the argument_spec, but not documented in the module
lib/ansible/modules/network/dellos10/dellos10_facts.py:0:0: E324 Value for "default" from the argument_spec (['!config']) for "gather_subset" does not match the documentation ('!config')
lib/ansible/modules/network/dellos6/dellos6_facts.py:0:0: E324 Value for "default" from the argument_spec (['!config']) for "gather_subset" does not match the documentation ('!config')
lib/ansible/modules/network/dellos9/dellos9_facts.py:0:0: E324 Value for "default" from the argument_spec (['!config']) for "gather_subset" does not match the documentation ('!config')
lib/ansible/modules/network/nxos/nxos_linkagg.py:0:0: E324 Value for "default" from the argument_spec ('on') for "mode" does not match the documentation (True)
lib/ansible/modules/network/nxos/nxos_linkagg.py:0:0: E324 Value for "default" from the argument_spec (False) for "force" does not match the documentation (None)
lib/ansible/modules/network/nxos/nxos_snapshot.py:0:0: E326 Value for "choices" from the argument_spec (['create', 'add', 'compare', 'delete', 'delete_all']) for "action" does not match the documentation (['create', 'add', 'compare', 'delete'])
lib/ansible/modules/remote_management/ucs/ucs_vlans.py:0:0: E326 Value for "choices" from the argument_spec (['yes', 'no']) for "native" does not match the documentation ([])
test/sanity/validate-modules/ignore.txt:489:1: A102 Remove since "lib/ansible/modules/cloud/misc/helm.py" passes "E325" test
test/sanity/validate-modules/ignore.txt:554:1: A102 Remove since "lib/ansible/modules/cloud/openstack/os_user_facts.py" passes "E324" test
test/sanity/validate-modules/ignore.txt:1067:1: A102 Remove since "lib/ansible/modules/network/asa/asa_acl.py" passes "E325" test
test/sanity/validate-modules/ignore.txt:1068:1: A102 Remove since "lib/ansible/modules/network/asa/asa_acl.py" passes "E326" test
test/sanity/validate-modules/ignore.txt:1069:1: A102 Remove since "lib/ansible/modules/network/asa/asa_config.py" passes "E325" test
test/sanity/validate-modules/ignore.txt:1070:1: A102 Remove since "lib/ansible/modules/network/asa/asa_config.py" passes "E326" test
test/sanity/validate-modules/ignore.txt:1185:1: A102 Remove since "lib/ansible/modules/network/enos/enos_config.py" passes "E325" test
test/sanity/validate-modules/ignore.txt:1186:1: A102 Remove since "lib/ansible/modules/network/enos/enos_config.py" passes "E326" test
test/sanity/validate-modules/ignore.txt:1274:1: A102 Remove since "lib/ansible/modules/network/iosxr/iosxr_config.py" passes "E325" test
test/sanity/validate-modules/ignore.txt:1386:1: A102 Remove since "lib/ansible/modules/network/nxos/nxos_ntp_auth.py" passes "E324" test
test/sanity/validate-modules/ignore.txt:1794:1: A102 Remove since "lib/ansible/modules/web_infrastructure/letsencrypt.py" passes "E325" test
```

Looks like a rebase maybe needed as well

**Comment by dagwieers** [comment]
Are the Zuul messages something temporary ? Because I don't think we need more comment-history madness than we already have. At least both Ansibot as Zuul should be removing irrelevant older comments to keep things tidy and useful.

PS The Details-link should probably refer to what is now put in the message, rather then go to https://zuul.openstack.org

**Comment by abadger** [comment]
@dagwieers I've reviewed and this looks fine to merge.  @dagwieers Go ahead and rebase to get rid of conflicts and then merge it to devel.

In such a large commit ones eyes do tend to glaze over somewhat but the changes are such that it's something we can fix up any inadvertant mistakes in the next devel cycle while the majority of the changes will be correct now.

**Review by gundalow — APPROVED** [review]

**Comment by dagwieers** [comment]
@abadger Oh, I only now saw your comment. Somehow missed that mail :-/ (Too much Github mails...)

**Pull request merged**
