### PR TITLE
Fix pretty_bytes for exa- and zettabytes

### PR DESCRIPTION
**Pull request by arsatiki**
Found repetition in constants of pretty_byte.

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by bcoca** [comment]
duh!, my bad, good catch ... or should I be worried you need those?

On Tue, Jul 16, 2013 at 9:42 AM, Michael DeHaan notifications@github.comwrote:

> merged, thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3548#issuecomment-21042480
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by arsatiki** [comment]
I found it com

**Comment by arsatiki** [comment]
I found it completely by accident. This issue has nothing to with NSA and I don't even work there so nothing suspicious at all!

**Pull request merged**
