### PR TITLE
Fix remote execution NameError bug in user module

### PR DESCRIPTION
**Pull request by candeira**
Bugfix was accepted into devel branch (https://github.com/ansible/ansible/pull/2061), maybe it's worth backporting it to 1.0. Here's a copy of the pull request message.

Remote execution of module "user" produced this traceback:

Traceback (most recent call last):
File "/root/.ansible/tmp/ansible-1360686502.37-80297117549296/user", line 1665, in
main()
File "/root/.ansible/tmp/ansible-1360686502.37-80297117549296/user", line 864, in main
module.fail_json(name=name, msg=err, rc=rc)
NameError: global name 'name' is not defined

Patch fixes it, and 'make tests' passes all tests but one (which is skipped).

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks like you did a git-merge instead of a git cherry pick.  This is going to be a problem.

Can you resubmit using just git-cherry pick?

You should start a branch on your end explicitly for this purpose and cherry pick just those commits to there.

**Comment by candeira** [comment]
Yes, I'm sorry. It's a bit late here.

**Comment by mpdehaan** [comment]
No problem, it's a bit early here :)

**Comment by dhozac** [comment]
Not sure it's really needed for 1.0, it's a bug in an error path, that should be unlikely to be hit.

**Comment by candeira** [comment]
dhozac, you may think of it as investment in process for a keen user and possible future contributor. Or not use the bugfix. I agree it's unlikely to be hit; I only found it because I was using the library improperly.

**Comment by mpdehaan** [comment]
It's extra safe to include, especially because it's _on_ an error path :)

We typically don't cherry-pick everything because it's a lot of effort to
maintain a release, but given we are going to include the services-fix
anyway, I have zero problems with this.

**Comment by candeira** [comment]
Thanks a lot.

**Pull request closed without merging**
