### PR TITLE
docsite: bump antsibull-docs version to 1.10.0 to support semantic markup

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Ref: https://github.com/ansible-community/community-topics/issues/53
Changelog: https://github.com/ansible-community/antsibull-docs/blob/1.10.0/CHANGELOG.rst#v1-10-0

The main new feature is semantic markup.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
docsite
docs build sanity test

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM thanks @felixfontein

**Comment by felixfontein** [comment]
@mattclay the main reason is to ensure that this will make it into ansible-core in time for the stable-2.15 branch, even if #74937 doesn't make it for whatever reason.

**Review by samccann — APPROVED** [review]
Validated on test site.

**Comment by samccann** [comment]
@mattclay are we okay to merge this now?

**Comment by felixfontein** [comment]
@oraNod @mattclay @samccann thanks a lot for reviewing and merging!

**Pull request merged**
