### PR TITLE
Fix to - nxos_lag_interfaces not idempotent

### LINKED ISSUE #67169: module nxos_lag_interfaces not idempotent when mode yes
##### SUMMARY
When using nxos_lag_interfaces with mode: yes, to configure "channel-group x mode on" (needed on Nexuses for connection of FEXes) it is not idempotent.
The output even states the mode as "True" not "yes" (see below).
I am not sure why in the Ansible module there is an option "yes" instead of "on" which is actually used on devices.

changed: [SWITCH-A] => (item={'key': 6, 'value': {u'members': [{u'member': u'Ethernet1/12', u'mode': True}, {u'member': u'Ethernet1/13', u'mode': True}]}})

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
modules/network/nxos/nxos_lag_interfaces

##### ANSIBLE VERSION
ansible 2.9.4
  config file = /home/martin/git/ansible-evpn/ansible.cfg
  configured module search path = [u'/home/martin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

##### CONFIGURATION
DEFAULT_CALLBACK_WHITELIST(/home/martin/git/ansible-evpn/ansible.cfg) = [u'timer', u'mail', u'profile_tasks']
DEFAULT_FORKS(/home/martin/git/ansible-evpn/ansible.cfg) = 10
DEFAULT_GATHERING(/home/martin/git/ansible-evpn/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/martin/git/ansible-evpn/ansible.cfg) = [u'/home/martin/git/ansible-evpn/inventory.yml']
DEFAULT_STDOUT_CALLBACK(/home/martin/git/ansible-evpn/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/home/martin/git/ansible-evpn/ansible.cfg) = /home/martin/git/ansible-evpn/group_vars/.va
HOST_KEY_CHECKING(/home/martin/git/ansible-evpn/ansible.cfg) = False
INTERPRETER_PYTHON(/home/martin/git/ansible-evpn/ansible.cfg) = auto_legacy_silent
PERSISTENT_COMMAND_TIMEOUT(/home/martin/git/ansible-evpn/ansible.cfg) = 180
PERSISTENT_CONNECT_TIMEOUT(/home/martin/git/ansible-evpn/ansible.cfg) = 180

##### OS / ENVIRONMENT
Ansible Server : Ubuntu18.04.3 LTS
Device: N9K running 9.2(3)

##### STEPS TO REPRODUCE
```
- name: Create Port-Channels
  nxos_lag_interfaces:
    config:
      - name: port-channel7
        members:
          - member: Ethernet1/15
            mode: yes
```

##### EXPECTED RESULTS
ok: [SWITCH-A]

##### ACTUAL RESULTS
changed: [SWITCH-A]

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### SUMMARY
Fixes #67169

##### ISSUE TYPE

- Bugfix Pull Request
-
##### COMPONENT NAME
nxos_lag_interfaces

##### ADDITIONAL INFORMATION

```
Modified the way on box and required configs are compared.
```

### CODE REVIEW

**Comment by NilashishC** [comment]
Thanks for the fix @GomathiselviS. Looks good to me. Before merging, could you please add the task mentioned in the issue as a test, just so that we have coverage for it?

**Review by NilashishC — APPROVED** [review]

**Comment by chrisvanheuveln** [comment]
@NilashishC Integration tests passed on 6k/7k. 👍

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
