### PR TITLE
Adds ServiceNow external inventory script

### PR DESCRIPTION
**Pull request by amittell**
##### SUMMARY

Added ServiceNow External Inventory Script 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

contrib/inventory/now.py
contrib/inventory/now.ini

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### ADDITIONAL INFORMATION

https://github.com/ServiceNowITOM/ansible-sn-inventory

```
ansible -i now.py esx_server -m ping --list-hosts                                                                                                         (master✱)
  hosts (4):
    10.196.33.175
    10.196.39.11
    10.196.39.12
    208.91.197.27
```

### CODE REVIEW

**Comment by garbled1** [comment]
Would very much like to see this added

**Comment by thaumos** [comment]
Hey @amittell, thanks for submission of this!

I'd actually like to see this submitted as an inventory plugin rather than a dynamic inventory script. 

We introduced the concept of inventory plugins in 2.4, and this feature allows for a lot more control for the end user rather than hardcoding a lot of group data into an ini/script file.

Please see [this](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/virtualbox.py) as an example!

**Comment by thaumos** [comment]
Here's some [documentation](http://docs.ansible.com/ansible/devel/dev_guide/developing_plugins.html#inventory-plugins) to back that plugin as well.

**Comment by amittell** [comment]
@thaumos do these work with Tower? All the Tower docs seem to talk about external inventory scripts with no mention of Inventory Plugins.

**Comment by wenottingham** [comment]
The inventory plugin framework was introduced in Ansible 2.4; Ansible will be moving inventory scripts to plugins, and Tower will migrate to those when they're available.

**Comment by amittell** [comment]
Would it be possible to accept this pull request as is for now then? One of my primary goals was to get this upstream to make it available for Tower users.

I'll submit an inventory plugin as a separate pull request when I get a little time to rewrite in the plugin format.

**Comment by thaumos** [comment]
Tower users are able to import this without needing it to be shipped with Ansible.  

I'd suggest just moving forward with the inventory plugin since that's what we want going forward for 2.5.

**Comment by tima** [comment]
@amittell: Thanks for your enthusiasm for getting something out there, but Ansible 2.4 and Ansible Tower 3.2 have just shipped. It is going to be sometime next year until a new feature like this would make it into either release. That gives you plenty of time to refactor your code into an inventory plugin that we are quickly moving forward with. In the meanwhile, you could release what you have to users on your own and start collecting user feedback for future iterations.

**Comment by willtome** [comment]
Written as plugin in #63912

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible/ansible/pull/63912

**Pull request closed without merging**
