### PR TITLE
add size option to the ping modules

### PR DESCRIPTION
**Pull request by Tachashi**
##### SUMMARY
Add `size` option to the `ios_ping` and `nxos_ping` modules.  
This option specify the datagram size of icmp packets.  

##### ISSUE TYPE
- Feature Pull Request  

##### COMPONENT NAME
`ios_ping` and `nxos_ping`

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Review by pabelanger — CHANGES_REQUESTED** [review]
Thanks, I'd like to see us also add integration testing to:
  https://github.com/ansible/ansible/blob/devel/test/integration/targets/ios_ping/tests/cli/ping.yaml

We currently don't have nxos_ping, but it would be super if you were to also add that.

**Comment by pabelanger** [comment]
Thanks! The ansible-test-network-integration-ios-python36 failure, is unrelated it seems. I'll be looking into it more, as it looks like we may have a race condition in our testing.

**Comment by NilashishC** [comment]
recheck

**Comment by Akasurde** [comment]
Hi @Tachashi, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/cisco.nxos<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
