### PR TITLE
Recent BSD su work introduced a failing test. Removed leading space from...

### PR DESCRIPTION
**Pull request by tima**
... the assertion that seems to be the culprit.

### CODE REVIEW

**Comment by jimi-c** [comment]
That's odd, I do not see this error when running `make tests` on my devel branch.

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by tima** [comment]
I thought this had corrected the problem I was having here but I was mistaken. The same unit test is failing. I slipped a sys.stderr.write of cmd[0] in at line 515 of TestUtils. This is what cmd[0] on my RHEL6 box reports:

```
/bin/sh -c 'su  root /bin/sh -c '"'"'echo SUDO-SUCCESS-xjpueejhpdfifwmcdfielkzthmnmwtmq; /bin/ls'"'"'' 
```

Since the failing test is looking for 'root -c "/bin/sh' that fails. Is this some sort of quirk between RHEL vs. BSD? I can fix it to work on my system, but have some concern that I will break others.

**Comment by jimi-c** [comment]
No, the command should be consistent across both platforms, so fixing it in the test should be consistent. Send us a PR whenever you're ready to have us look at it. Thanks!

**Comment by tima** [comment]
I've submitted my PR. See  #7652.

**Pull request merged**
