### PR TITLE
Modify port would remove and re-add ports on a modify which can results in an error

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
During a modify on na_ontap_net_ifgrp, port would be removed and then re-added to the ifgrp. If the ifgrp is referenced by a vlan the last port can't be removed resulting in an error. This fix prevents ports from being removed and added back to an ifgrp. We only remove or add port if they are changed. 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
* na_ontap_net_ifgrp.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]
shipit

**Review by JohnLieske — APPROVED** [review]
Looks good, tests are good.

**Review by JohnLieske — APPROVED** [review]
Screenshot from 2019-03-18 11-22-50

GTG; files look good; tests look good

**Comment by gundalow** [comment]
Thanks, merged!

**Pull request merged**
