### PR TITLE
OpenStack Modules

### PR DESCRIPTION
**Pull request by bennojoy**
This has modules for OpenStack Quantum for managing networks routers floating ip's etc..
Also has modules for nova vm management, glance image management and management of  key pairs. 
The external inventory script for nova has also been modified a bit so that if accessipv4 is not set for the vm, it checks if it has a public ip and returns that, if not returns the vm's private ip.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!   Would you mind sending the list an email to introduce people to these?

I am sure a lot of people will be excited/interested.

**Comment by mpdehaan** [comment]
cc @lorin

**Comment by lorin** [comment]
These look good, I'd like to see them included. I'm very happy to see them using the native OpenStack Python API for the implementation.

**Comment by mpdehaan** [comment]
merged, thanks @bennojoy and also thanks @lorin for taking a look at these.  

Much appreciated!

**Pull request merged**
