### PR TITLE
Include roles with tags in meta/main.yml make a role run more than neccesary

### PR DESCRIPTION
**Pull request by kiorky**
##### SUMMARY
roles may be ran more than neccessary if they are called with different tags, which is in my opnion a bug, that PR fixes it.

See associated test

This is part of the #32565 PR split.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
2.4
devel
```

##### ADDITIONAL INFORMATION
Pre (associatet PR test FAIL)

```
TASK [assert] *****************************************************************************************************************************************************************************************************************************************************************
fatal: [testhost]: FAILED! => {
    "assertion": "counter=='1'",
    "changed": false,
    "evaluated_to": false,
    "msg": "counterfail2 2"
}
        to retry, use: --limit @/srv/corpusops/corpusops.bootstrap/venv/src/ansible/test/integration/targets/include_role_cache_tags_bug/test.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
testhost                   : ok=4    changed=0    unreachable=0    failed=1

NOTICE: To resume at this test target, use the option: --start-at include_role_cache_tags_bug
ERROR: Command "./runme.sh -v" returned exit status 2.
```

Post (associatet PR test pass)
```
testhost                   : ok=18   changed=0    unreachable=0    failed=0

```
- related PRs: #35167 #35166 #35165 #35164 #35163

### CODE REVIEW

**Comment by kiorky** [comment]
!ready_for_review

**Comment by kiorky** [comment]
+label ready_for_review

**Comment by sivel** [comment]
Related to this commit https://github.com/ansible/ansible/commit/dca36c1d160

We have to evaluate whether recent changes make the addition of `tags` and `when` to uniqueness unnecessary now.

**Comment by kiorky** [comment]
So i just rebased and on my fork i maintain patches for 2.4, devel (2.7)

**Pull request closed without merging**
