### PR TITLE
ansible-test action-plugin-docs Support sidecar docs

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Fix to have ansible-test sanity --test action-plugin-docs to check for action plugin documentation inside a sidecar file rather than a Python module.

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/blob/devel/test/integration/targets/ansible-doc/runme.sh#L232

**Comment by jborean93** [comment]
The test added is specifically for the `ansible-test` sanity test `action-plugin-docs`. It is unrelated to `ansible-doc's` handling of sidecard docs. Right now `ansible-test sanity --test action-plugin-docs` will fail with a sidecar doc of an action plugin as it cannot find the `modules/$plugin.py` file.

**Comment by bcoca** [comment]
I understand the sanity/validation tests are different, just pointing to where I added the tests for sidecar in case there are holes or overlap.

**Comment by jborean93** [comment]
> Also we removed the requirement for action plugins to have a 'corresponding module' in core as it was specifically requested. I'm not sure why the validation has that requirement.

I think it's more validation requires the docs which in the past meant a `.py` file stub.

**Comment by bcoca** [comment]
That was the same reason core used to require it, we but removed as 'networking content' moved to use a single action plugin (kept undocumented) to handle the associated group of networking modules.

**Review by mattclay — APPROVED** [review]

**Comment by jborean93** [comment]
We will not backport this as it could change an existing and known behaviour in the existing releases. Potentially causing a failure due to a no longer needed sanity check.

**Pull request merged**
