### PR TITLE
BOTMETA: Move rabbitmq modules to own directory

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This makes it possible to automatically include $team_rabbitmq for new modules.

This PR also includes:
- Fixes to author fields
- Fixes to copyright statements
- Fixes to short_description

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

##### ANSIBLE VERSION
v2.8

### CODE REVIEW

**Comment by dagwieers** [comment]
bot_skip

**Comment by jctanner** [comment]
Does chrishoffman want to be notified now? I don't understand why we would take out the ingore field for his username.

**Comment by dagwieers** [comment]
@jctanner It was the wrong Github handle (choffman vs chrishoffman), beats me how this could end up there. Typo ?

https://github.com/ansible/ansible/pull/46064/files#diff-7920eca0d9e6bb899a9ef1ab76165190R23

And I assume the other user complained he was notified about stuff, so we ignored that handle.

**Comment by dagwieers** [comment]
And I assume the other user complained he was notified about stuff, so we ignored that handle.

**Comment by pilou-** [comment]
> This makes it possible to automatically include $team_rabbitmq for new modules.

Could not `$modules/messaging/rabbitmq_: $team_rabbitmq` be used instead ?

The downside of creating `modules/messaging/rabbitmq/` is that the only namespace maintainers of `messaging/rabbitmq` are the rabbitmq module authors. But there are only `rabbitmq` modules below `messaging`, then that's not a problem :)

**Comment by dagwieers** [comment]
@pilou- That would work as well, but I don't see why you wouldn't do the right thing anyway.

**Comment by pilou-** [comment]
Maybe notion of `namespace maintainers` should be redefined. Should not all the `messaging` maintainers be namespace maintainers of rabbitmq modules ? I mean: we want more maintainers not less.

**Comment by dagwieers** [comment]
@pilou- Please continue that discussion in another issue or PR. (Hint: look at $team_network for an existing situation)

**Comment by pilou-** [comment]
> Please continue that discussion in another issue or PR. (Hint: look at $team_network for an existing situation)

I don't understand

**Comment by dagwieers** [comment]
@pilou- Your discussion has nothing to do with this PR. You are talking about "messaging maintainers", but there are no "messaging maintainers" (only $team_rabbitmq), so this is a hypothetical discussion. I am not looking for hypothetical discussions, so whatever case you want to make, please look for another forum to do this.

**Comment by pilou-** [comment]
Did you miss the part where I wrote that I did not disagree with theses changes ?
> But there are only rabbitmq modules below messaging, then that's not a problem :)

**Comment by dagwieers** [comment]
@pilou- My response was to:

> Maybe notion of namespace maintainers should be redefined. Should not all the messaging maintainers be namespace maintainers of rabbitmq modules ? I mean: we want more maintainers not less.

There are no "messaging maintainers" so I don't see your point and it seems you are having a parallel discussion in this PR. If you don't agree, that's fine. No clue what the above is about though.

**Comment by acozine** [comment]
@pilou-  right now the rabbitmq is the only messaging utility with ansible modules, but that situation probably won't last forever; this change gets us ready for the future, and allows the rabbitmq maintainers to decide if they want to maintain other messaging modules, or only rabbitmq ones

**Review by gundalow — APPROVED** [review]
LGTM, Rebase then merge

**Pull request merged**
