### PR TITLE
Version_added was fixed to 2.7.

### PR DESCRIPTION
**Pull request by curry9999**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vultr/vultr_account_facts.py
lib/ansible/modules/cloud/vultr/vultr_dns_domain.py
lib/ansible/modules/cloud/vultr/vultr_dns_record.py
lib/ansible/modules/cloud/vultr/vultr_firewall_group.py
lib/ansible/modules/cloud/vultr/vultr_firewall_rule.py
lib/ansible/modules/cloud/vultr/vultr_server.py
lib/ansible/modules/cloud/vultr/vultr_ssh_key.py
lib/ansible/modules/cloud/vultr/vultr_startup_script.py
lib/ansible/modules/cloud/vultr/vultr_user.py
lib/ansible/modules/net_tools/netcup_dns.py
lib/ansible/modules/net_tools/nios/nios_aaaa_record.py
lib/ansible/modules/network/f5/bigip_firewall_address_list.py
lib/ansible/modules/network/f5/bigip_firewall_port_list.py

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Review by resmo — CHANGES_REQUESTED** [review]
all listed vultr_modules were renames and having a link with prefix `_vr_`

needs_revision

**Comment by caphrim007** [comment]
all listed bigip_ modules were renames where we created symlinks to the new files. The new files contained the version of the old file that had been symlinked.

needs_revision

**Review by caphrim007 — CHANGES_REQUESTED** [review]
bigip_ modules do not need this update. These modules are the same as the previously existing ones (bigip_security_*). They were simply renamed and a symlink to the old name was added

**Comment by sivel** [comment]
Closing this as this as described above.

**Pull request closed without merging**
