### PR TITLE
fixes(#25299) Don't fail when creating a Foreman organization

### PR DESCRIPTION
**Pull request by ehelms**
##### SUMMARY

The module would bail if the organization did not already exist and skip creating it, this should fix it.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

remote_management/foreman/foreman.py

### CODE REVIEW

**Comment by gundalow** [comment]
Added the `owner_pr` label, I've updated `MAINTAINERS.txt` so you will be notified of any issues or PRs in the future https://github.com/ansible/ansibullbot/commit/729d9ff9a912b23487715200224f2a4daededf78

**Comment by gundalow** [comment]
This looks sensible. Should this be backported into `stable-2.3`?

**Comment by ehelms** [comment]
Yes, I think that makes sense.

**Comment by resmo** [comment]
LGTM

**Comment by gundalow** [comment]
Merged into `devel`, cherry picked into stable-2.3 + CHANGELOG.md updated https://github.com/ansible/ansible/pull/25486

**Pull request merged**
