### PR TITLE
Use pkgng glob (-g) feature to allow installation of packages by wildcard

### PR DESCRIPTION
**Pull request by arkadijs**
Also solves the particular problem of installing packages that have multiple versions in the repo, but specifying the exact version would be troublesome:

$ pkg install -n dovecot
The following 2 packages will be installed:

```
Installing dovecot: 1.2.17
Reinstalling dovecot-2.2.6 (options changed)
```

$ pkg install -n dovecot-2.2.6
The following 1 packages will be installed:

```
Reinstalling dovecot-2.2.6 (options changed)
```

$ pkg install -n -g dovecot-2*
The following 1 packages will be installed:

```
Reinstalling dovecot-2.2.6 (options changed)
```

### CODE REVIEW

**Comment by jctanner** [comment]
@arkadijs I like this because it makes it easier to get packages installed, but it seems like -g will be a default parameter which may not be the behavior everyone wants. I would prefer that the code check for '*' in the package name and then append -g if found. 

If that is how pkg already works and it doesn't need special handling in the module, please let me know. Otherwise, please refactor and I'll accept this. Thanks!

**Comment by arkadijs** [comment]
Hmm, I don't see how it would change the behavior, the result will be the same in both cases. No package contain \* or ? in the name, so specifying -g won't hurt in current implementation.

On libpkg side, the pkgdb is sqlite and -g just switch it to use WHERE name GLOB... instead of WHERE name =

-i (Make the standard or the regular expression (-x) matching against pkg-name case insensitive.) is not used, so the change should be no surprise.
The `packages` table has no indices, so the speed of the query/install won't suffer.

```
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ echo "select 'select id from packages where name = ''' || name || ''';' from packages limit 10;" | sqlite3 repo-FreeBSD.sqlite > /tmp/exact.sql
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ time sqlite3 repo-FreeBSD.sqlite < /tmp/exact.sql >/dev/null

real    0m13.487s
user    0m0.885s
sys 0m3.513s
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ time sqlite3 repo-FreeBSD.sqlite < /tmp/exact.sql >/dev/null

real    0m13.062s
user    0m0.767s
sys 0m3.513s
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ echo "select 'select id from packages where name glob ''' || name || ''';' from packages limit 10;" | sqlite3 repo-FreeBSD.sqlite > /tmp/glob.sql
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ time sqlite3 repo-FreeBSD.sqlite < /tmp/glob.sql >/dev/null
real    0m13.135s
user    0m1.297s
sys 0m4.030s
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ time sqlite3 repo-FreeBSD.sqlite < /tmp/glob.sql >/dev/null

real    0m13.237s
user    0m1.228s
sys 0m4.074s
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ echo "select 'select id from packages where name glob ''' || name || '*'';' from packages limit 10;" | sqlite3 repo-FreeBSD.sqlite > /tmp/really-glob.sql
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ time sqlite3 repo-FreeBSD.sqlite < /tmp/really-glob.sql >/dev/null
real    0m14.121s
user    0m1.299s
sys 0m4.370s
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ time sqlite3 repo-FreeBSD.sqlite < /tmp/really-glob.sql >/dev/null

real    0m13.517s
user    0m1.388s
sys 0m4.028s
[vagrant@vagrant-freebsd-92 /var/db/pkg]$ 
```

(yes, its that slow)

**Comment by jctanner** [comment]
@arkadijs I misunderstood how pkg works. You are right, the initial behavior remains the same with -g.

**Comment by jctanner** [comment]
@arkadijs thank you!

**Pull request merged**
