### PR TITLE
Fix consul module service deregistration

### LINKED ISSUE #34628: consul.py: state=absent is broken
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`consul`

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 11 2017, 14:52:53) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]

```

##### CONFIGURATION

None

##### SUMMARY

Deregistration of services does not work, because the underlying `consul-python` modules uses the wrong request type (GET instead of PUT).
Upstream PR: https://github.com/cablehead/python-consul/pull/174

##### STEPS TO REPRODUCE

```yaml
ansible -m consul -a 'state=absent service_name=myservice' all
```

##### EXPECTED RESULTS

Service removed

##### ACTUAL RESULTS
Service present

#### Workaround based on @bobh66 suggestion:

Copy `consul.py` to `{{ playbook_dir }}/library` and apply the following patch:

```
@@ -343,12 +343,19 @@ def remove_service(module, service_id):
     module.exit_json(changed=False, id=service_id)
 
 
+class MyAgentService(consul.Consul.Agent.Service):
+    def deregister(self, service_id):
+        return self.agent.http.put(consul.base.CB.bool(), '/v1/agent/service/deregister/%s' % service_id)
+
+
 def get_consul_api(module, token=None):
-    return consul.Consul(host=module.params.get('host'),
+    consulClient = consul.Consul(host=module.params.get('host'),
                          port=module.params.get('port'),
                          scheme=module.params.get('scheme'),
                          verify=module.params.get('validate_certs'),
                          token=module.params.get('token'))
+    consulClient.agent.service = MyAgentService(consulClient)
+    return consulClient
```

### PR DESCRIPTION
**Pull request by alvaroaleman**
Upstream pr in the consul-python library:
https://github.com/cablehead/python-consul/pull/174

This is based on work from https://github.com/bobh

Fixes ansible/ansible#34628

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`consul.py`

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
ready_for_review

**Comment by jnogol** [comment]
Tested. Now deregistration works like a charm @alvaroaleman @gundalow

**Comment by gundalow** [comment]
rebuild_merge

**Comment by gundalow** [comment]
Does this need cherry-picking into `stable-2.5`?

**Comment by alvaroaleman** [comment]
That would be very helpful, yes

**Comment by gundalow** [comment]
Merged into `devel` and cherry-picked into `stable-2.5` in https://github.com/ansible/ansible/commit/471e75a0190aec7cf70de930d7555ebc43349c07

**Pull request merged**
