### PR TITLE
cloudstack: docs: use local_action, not connection=local

### PR DESCRIPTION
**Pull request by resmo**
##### ISSUE TYPE

- Docs Pull Request
##### COMPONENT NAME

cloudstack guide
##### ANSIBLE VERSION

```
2.3
```
##### SUMMARY

use local_action in examples as connection=local does not always work (e.g. if python3 is the default python)

### CODE REVIEW

**Comment by bcoca** [comment]
docs should not be fixed, connection=local should ALWAYS work, if not, it is a bug.

**Comment by resmo** [comment]
I should have extended it with ".. as expected in some situations"

Correct me if I am wrong, but one difference of connection=local vs local_action is that connection=local uses /usr/bin/python where local_action uses the python in your PATH. This means you get slightly more control about what python is going to be used on your local machine for local tasks.

Having a team with different OS and setups (macOS, Ubuntu, Debian) where /usr/bin/python may or may not be python3 or python2, this can be much easier to be handled by the team member individually and for all ansible projects globally than using ansible_python_interpreter. 

Further, I steamlined all my playbooks for that reason to local_action and would also cover this in the docs.

**Comment by bcoca** [comment]
No, both should use 'sys.executable' which should reflect the python chosen on install for bin/ansible. 

As they rely on the implicit localhost, if localhost is defined in the inventory that will change the behavior.

**Comment by resmo** [comment]
hmm, it seems I was confused with sourcing ./hacking/env-setup which uses the python in my PATH (which is ~/bin/python) where ansible pip installed uses /usr/bin/python, but for connection=local and local_action. 

Never mind.

**Pull request closed without merging**
