### PR TITLE
Allow subdirs in host/group_vars and vars files extensions.

### PR DESCRIPTION
**Pull request by cmhamill**
Allows directory organization:

```
host_vars/hostname.ymal
host_vars/project_foo/hostname
host_vars/project_foo/plue/hostname.yaml
group_vars/groupname.ymal
group_vars/project_bar/groupname
group_vars/project_bar/grue/groupname.yaml
```

Arbitrary levels of nesting is allowed, and the name of the var file can either be the groupname or hostname, or the groupname or hostname with any '.*' file extension (so groupname.txt and groupname.yaml are valid, but not groupname.bar.txt).

Note that if someone did something clever like having groups called 'groupname' and 'groupname.bar' and 'groupname.yaml', all those files would be loaded.

In the case of multiple files meeting those criteria, they are loaded in alphabetical sort order based on the entire path, so the following files would be loaded in the given order:

```
group_vars/alfie/groupname
group_vars/alfie/groupname.yaml
group_vars/groupname
group_vars/zed/groupname
```

I'd be more than willing to change that behavior if there are any suggestions.

### CODE REVIEW

**Comment by srgvg** [comment]
See also discussion on https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/hD1A1W5gthc

**Comment by srgvg** [comment]
Wouldn't this be a more logical sort order?

```
group_vars/groupname
group_vars/alfie/groupname
group_vars/alfie/groupname.yaml
group_vars/alfie/benedict/groupname
group_vars/alfie/benedict/groupname.yaml
group_vars/alfie/eric/groupname
group_vars/alfie/eric/groupname.yaml
group_vars/zed/groupname
```

So sorting alphabetically, dir depth wise.

Yes that's not what I said on the list, but seeing it now, made me change ideas :)

On the other hand, it might be getting too late at night for me to think aboujt this.

**Comment by srgvg** [comment]
Also, you then loop through those files in the given order, which means the (same var inthe) *_last// file gets precedence, not the *first_. Is that what you intended?

**Comment by cmhamill** [comment]
Yeah, I meant to imply that's the order they were added to the vars in memory, not that it's their precedence relationship.

I'm not positive this is the best way to do things, but it is dumb, which I like. I'd worry if there's too much logic to the, uh, logic, then folks might try and use it as a weird variable-override mechanism.

On the other hand, a dumb lexical sort might be a little too arbitrary.

I'm not sure that would be Least Surprising™ to the user in this case. I'd imagine they'd be surprised it allowed multiple conflicting vars files at all.

**Comment by cmhamill** [comment]
Also, this code will react weirdly if someone has, say, two hosts called:

```
howdy
howdy.foo
```

And then the following vars file:

```
host_vars/howdy.foo
```

The host `howdy` will end up with the variables of `howdy.foo`, in addition to any variables in `host_vars/howdy`.

**Comment by srgvg** [comment]
Indeed, I didn't pay attention to this. Wouldn't you better only strip the 'yml' extension?

I do hope there never will be a yml top level dns domain :-)

**Comment by mpdehaan** [comment]
per mailing list discussion, I am thinking this needs to be handled by an inventory plugin, and this may be confusing for end users.

I do think it would be nice if we had a way to ignore extensions of files, so that if someone tried ".yml" out of habit, it just worked, though.

**Pull request closed without merging**
