### PR TITLE
maven_artifact: raise an explicit exception if the .md5 url returns 404

### PR DESCRIPTION
**Pull request by turb**
##### SUMMARY
When the <url>.md5 returns 404, the module currently raise a "Checksum verification failed" error.

With this patch, the module will instead raise a more explicit error.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/Users/turb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

with pre2.6 `maven_artifact`

### CODE REVIEW

**Comment by turb** [comment]
@tumbl3w33d it seems this one from me has not been detected as being attached to `maven_artifact`.

**Comment by tumbl3w33d** [comment]
shipit

**Comment by AndreyZykov** [comment]
Hello guys, I found that after update ansible from 2.4 to 2.6 maven_artifact module stopped detect the artifact was changed when the target file is exist. Parameter verify_checksum is not set, so by default it's download

I've made a small investigation and found this line:
https://github.com/ansible/ansible/blame/devel/lib/ansible/modules/packaging/language/maven_artifact.py#L536
Guess it should be simply "verify_change" but not "(not verify_change)"

**Comment by turb** [comment]
@AndreyZykov that's an intended change of behaviour, see discussions in #31799 and PR #33370.

To keep the previous behavious, you may want to explicitely set `verify_checksum` to `change`.

If you think there is a bug, please open another thread.

**Comment by AndreyZykov** [comment]
@turb the problem is we still use same roles/playbooks on instances with ansible 2.4 and it doesn't support verify_checksum :(

ok, i'll open new thread, thanks!

**Pull request merged**
