### PR TITLE
Added a paragraph about unit testing.

### PR DESCRIPTION
**Pull request by dorfsmay**

### CODE REVIEW

**Comment by dorfsmay** [comment]
I made a new commit with your wording for that sentence.

**Comment by mpdehaan** [comment]
thanks!

**Comment by dorfsmay** [comment]
Anything you want me to add / change here?

**Comment by mpdehaan** [comment]
I'm a bit picky about this part, I'll write something.

**Comment by dorfsmay** [comment]
On 2013-02-23 10:39, Michael DeHaan wrote:

> I'm a bit picky about this part, I'll write something.

No problem. As long as something gets written.

## 

Yves.                                                  http://www.SollerS.ca/
                                  Unix/Linux and Python specialist in Calgary.
                                                        http://blog.zioup.org/

**Pull request closed without merging**
