### PR TITLE
docker_swarm_service: Set minimum docker-py version to 2.0.2

### PR DESCRIPTION
**Pull request by hannseman**
##### SUMMARY

Try and set minimum docker-py version to 2.0.2 as discussed in https://github.com/ansible/ansible/issues/53193. This PR also checks both `docker_api_version` and `docker_py_version` for each test case.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

docker_swarm_service

### CODE REVIEW

**Comment by felixfontein** [comment]
Looks good! Can you add a changelog? Please don't include 2.0.2 into the changelog's name, so in case we need to bump it again later, we don't have to rename the file ;)

**Comment by felixfontein** [comment]
BTW, when running the tests with docker-py 2.0.2, they stop early with:
```
TASK [create sample service] *********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "docker version is 2.0.2. Minimum version required is 3.0.0 to set endpoint_mode option."}
```

**Comment by hannseman** [comment]
I got the tests passing with docker 2.0.2. Found some issues along the way:

* Networks can only be updated when using >= docker-py 2.7
* Constraints require docker-py 2.4.0
* Healthchecks require docker-py 2.6.0

**Comment by felixfontein** [comment]
Merging the last two PRs caused some conflicts. Can you rebase?

**Comment by hannseman** [comment]
ready_for_review

**Comment by felixfontein** [comment]
With docker==2.2.0, the `secrets` tests crash:
```
TASK [secrets] ***********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/home/felix/.ansible/tmp/ansible-tmp-1551824244.4349453-189620470344759/AnsiballZ_docker_swarm_service.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/felix/.ansible/tmp/ansible-tmp-1551824244.4349453-189620470344759/AnsiballZ_docker_swarm_service.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/felix/.ansible/tmp/ansible-tmp-1551824244.4349453-189620470344759/AnsiballZ_docker_swarm_service.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/felix/.ansible/tmp/ansible-tmp-1551824244.4349453-189620470344759/AnsiballZ_docker_swarm_service.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py\", line 2302, in <module>\n  File \"/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py\", line 2285, in main\n  File \"/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py\", line 2046, in run_safe\n  File \"/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py\", line 2036, in run\n  File \"/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py\", line 1918, in create_service\n  File \"/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py\", line 1706, in build_docker_service\n  File \"/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py\", line 1532, in build_container_spec\n  File \"/usr/lib/python3.7/site-packages/docker/utils/decorators.py\", line 19, in wrapped\n    'Resource ID was not provided'\ndocker.errors.NullResource: Resource ID was not provided\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
...ignoring
```
The relevant part of the stacktrace:
```
  File "/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py", line 2302, in <module>
  File "/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py", line 2285, in main
  File "/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py", line 2046, in run_safe
  File "/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py", line 2036, in run
  File "/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py", line 1918, in create_service
  File "/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py", line 1706, in build_docker_service
  File "/tmp/ansible_docker_swarm_service_payload_etwa8cly/__main__.py", line 1532, in build_container_spec
  File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    'Resource ID was not provided'
docker.errors.NullResource: Resource ID was not provided
```

**Comment by felixfontein** [comment]
Ok, that's actually a bug in docker (the Docker Python SDK), which is fixed in 2.4.0. The problem is that `SecretReference.__init__()` uses the `@check_resource` decorator, which looks whether the argument `container` or `image` is provided, and gives that error message if not. For this reason, we had to bump the minimal version of `docker_node` and `docker_node_facts` to docker 2.4.0 (see https://github.com/ansible/ansible/pull/53129/commits/6f1ff0f872af42040274dc750ac26d9ab677d692 and https://github.com/ansible/ansible/pull/53129#issuecomment-468569940). I guess we have to bump the minimal version required for `secrets` to 2.4.0 because of this.

**Comment by felixfontein** [comment]
(https://github.com/docker/docker-py/commit/d33e9ad030effb126dea39181ef401c80c442f15#diff-b9b55625c49ce15d8458fb9501faa56c)

**Comment by felixfontein** [comment]
With docker==2.6.0, the `hosts` tests failed, because `dict((hostname, ip) for ip, hostname in hosts)` failed with `not enough values to unpack (expected 2, got 1)`. The problem is that for me, docker returned `hosts=['example.com:1.2.3.4', 'example.org:4.3.2.1']`, i.e. values separated by colons, not by spaces...

**Comment by felixfontein** [comment]
Fun fact: docker==2.7.0 returns them as `hosts=['1.2.3.4 example.com', '4.3.2.1 example.org']` (the same behavior you also saw).

**Comment by felixfontein** [comment]
Ok, I've tested the module with *all* docker versions between 2.0.2 and 3.0.0, and after that with 3.1.0 and 3.2.0 (then I gave up; from 3.2.0 on the modules gets *very* slow, probably because of `resolve_image`). I needed the following changes to make it work. (Note that the quotings are not necessary, but they eliminate warnings which will show up for 2.8.)
```.diff
diff --git a/lib/ansible/modules/cloud/docker/docker_swarm_service.py b/lib/ansible/modules/cloud/docker/docker_swarm_service.py
index aa48ad2afd..ae7cee3a44 100644
--- a/lib/ansible/modules/cloud/docker/docker_swarm_service.py
+++ b/lib/ansible/modules/cloud/docker/docker_swarm_service.py
@@ -1780,7 +1780,7 @@ class DockerServiceManager(object):
 
         hosts = task_template_data['ContainerSpec'].get('Hosts')
         if hosts:
-            hosts = [host.split(' ', 1) for host in hosts]
+            hosts = [list(reversed(host.split(':', 1))) if ':' in host else host.split(' ', 1) for host in hosts]
             ds.hosts = dict((hostname, ip) for ip, hostname in hosts)
         ds.tty = task_template_data['ContainerSpec'].get('TTY')
 
@@ -2207,7 +2207,7 @@ def main():
         hosts=dict(docker_py_version='2.6.0', docker_api_version='1.25'),
         groups=dict(docker_py_version='2.6.0', docker_api_version='1.25'),
         tty=dict(docker_py_version='2.4.0', docker_api_version='1.25'),
-        secrets=dict(docker_py_version='2.1.0', docker_api_version='1.25'),
+        secrets=dict(docker_py_version='2.4.0', docker_api_version='1.25'),
         configs=dict(docker_py_version='2.6.0', docker_api_version='1.30'),
         update_max_failure_ratio=dict(docker_py_version='2.1.0', docker_api_version='1.25'),
         update_monitor=dict(docker_py_version='2.1.0', docker_api_version='1.25'),
diff --git a/test/integration/targets/docker_swarm_service/tasks/tests/options.yml b/test/integration/targets/docker_swarm_service/tasks/tests/options.yml
index 63f519b937..e8d244f410 100644
--- a/test/integration/targets/docker_swarm_service/tasks/tests/options.yml
+++ b/test/integration/targets/docker_swarm_service/tasks/tests/options.yml
@@ -1543,7 +1543,7 @@
     name: "{{ service_name }}"
     image: alpine:3.8
     command: '/bin/sh -v -c "sleep 10m"'
-    stop_signal: 30
+    stop_signal: "30"
   register: stop_signal_1
   ignore_errors: yes
 
@@ -1552,7 +1552,7 @@
     name: "{{ service_name }}"
     image: alpine:3.8
     command: '/bin/sh -v -c "sleep 10m"'
-    stop_signal: 30
+    stop_signal: "30"
   register: stop_signal_2
   ignore_errors: yes
 
@@ -1561,7 +1561,7 @@
     name: "{{ service_name }}"
     image: alpine:3.8
     command: '/bin/sh -v -c "sleep 10m"'
-    stop_signal: 9
+    stop_signal: "9"
   register: stop_signal_3
   ignore_errors: yes
 
@@ -1866,12 +1866,12 @@
       - secrets_3 is changed
       - secrets_4 is changed
       - secrets_5 is not changed
-  when: docker_api_version is version('1.25', '>=') and docker_py_version is version('2.1.0', '>=')
+  when: docker_api_version is version('1.25', '>=') and docker_py_version is version('2.4.0', '>=')
 - assert:
     that:
     - secrets_1 is failed
     - "'Minimum version required' in secrets_1.msg"
-  when: docker_api_version is version('1.25', '<') or docker_py_version is version('2.1.0', '<')
+  when: docker_api_version is version('1.25', '<') or docker_py_version is version('2.4.0', '<')
 
 
 ###################################################################
diff --git a/test/integration/targets/docker_swarm_service/tasks/tests/resources.yml b/test/integration/targets/docker_swarm_service/tasks/tests/resources.yml
index 9dd31ed584..e35e2de4b3 100644
--- a/test/integration/targets/docker_swarm_service/tasks/tests/resources.yml
+++ b/test/integration/targets/docker_swarm_service/tasks/tests/resources.yml
@@ -87,7 +87,7 @@
     name: "{{ service_name }}"
     image: alpine:3.8
     command: '/bin/sh -v -c "sleep 10m"'
-    limit_memory: 67108864
+    limit_memory: "67108864"
   register: limit_memory_2b
 
 - name: limits.memory (change)
@@ -189,7 +189,7 @@
     name: "{{ service_name }}"
     image: alpine:3.8
     command: '/bin/sh -v -c "sleep 10m"'
-    reserve_memory: 67108864
+    reserve_memory: "67108864"
   register: reserve_memory_2b
 
 - name: reservations.memory (change)
```

**Comment by hannseman** [comment]
@felixfontein Very good testing!

**Comment by felixfontein** [comment]
Sorry for adding a conflict (probably caused by merging #53229).

**Comment by hannseman** [comment]
@felixfontein No problem!

ready_for_review

**Review by felixfontein — APPROVED** [review]
LGTM!

shipit

**Comment by felixfontein** [comment]
@hannseman thanks for the PR!
@gundalow thanks for merging!

**Pull request merged**
