### PR TITLE
re-enable non-pipelined mode for Powershell

### LINKED ISSUE #23986: Since Ansible 2.3.0, Powershell modules do not honor ANSIBLE_KEEP_REMOTE_FILES
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
2.3.0
```

##### CONFIGURATION
export ANSIBLE_KEEP_REMOTE_FILES=1

##### SUMMARY
Using Ansible 2.3.0, generated ps1 files are not longer left on the target node when setting the env var ANSIBLE_KEEP_REMOTE_FILES to "1" on Windows-based target nodes.
As far as I can see the folders in %temp% are left, but the actual files inside are deleted, except for files executed using 'script'. This makes it next to impossible to troubleshoot/debug during module development.

### PR DESCRIPTION
**Pull request by nitzmahone**
##### SUMMARY
* fixes #23986
* fixes 3rd-party Windows connection plugins that don't support pipelining (eg awsrun)

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
module_common.py

### CODE REVIEW

**Comment by Constantin07** [comment]
@nitzmahone Many thanks for you PR. I'm facing with similar issue - cannot properly manage Windows via WinRM from Linux. Is there any chance to resolve the conflict and push again?

**Comment by nitzmahone** [comment]
@Constantin07 I'm still working through ways to fix one outstanding issue (the `environment: ` keyword is broken under `script` with this fix). One way or another, this should be in Ansible 2.3.2, though. What are you running into- the packer thing, or something else?

**Comment by Constantin07** [comment]
@nitzmahone Yes, the packer thing.

**Comment by nitzmahone** [comment]
We discussed this during contributor summit- consensus was to merge/cherrypick to 2.3 as-is with the breakage, and try for a more comprehensive fix for 2.4.

**Pull request merged**
