### PR TITLE
fix termination on user/signal interrupt

### LINKED ISSUE #14346: ansible is leaking subprocesses when killed by SIGTERM
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

`/etc/ansible/ansible.cfg` contains only comments:

```
$ egrep -v '^$|^#' /etc/ansible/ansible.cfg
[defaults]
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
```
##### Environment:

ArchLinux
##### Summary:

When an `ansible` or `ansible-playbook` process is killed by a `SIGTERM` signal, one of its sub-process remains live forever.

This happens when one tries to invoke `ansible` or `ansible-playbook` from a program that has a timeout and that fires a `SIGTERM` signal to the `fork`ed/`execve`d process if it takes more time than expected to complete.
In that case, an `ansible` or `ansible-playbook` sub-process is leaked and never finishes.
##### Steps To Reproduce:

Use a basic inventory:

```
foo ansible_connection=local ansible_python_interpreter=/usr/bin/python2
bar ansible_connection=local ansible_python_interpreter=/usr/bin/python2
baz ansible_connection=local ansible_python_interpreter=/usr/bin/python2
```

Launch a command:

```
$ ansible -i inventory.ini all -m command -a "sleep 30"
```

And kill the launched `ansible` process while the `sleep 30` is running:

```
$ ps -fu $UID | grep ansible
lenaic   26628  1896 33 00:00 pts/1    00:00:01 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26633 26628 15 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26634 26628  1 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26635 26628  1 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26636 26628  1 00:00 pts/1    00:00:00 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
lenaic   26652 26634  0 00:00 pts/1    00:00:00 /bin/sh -c LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-231434939428138/command; rm -rf "/home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-231434939428138/" > /dev/null 2>&1
lenaic   26653 26635  0 00:00 pts/1    00:00:00 /bin/sh -c LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-54597535277775/command; rm -rf "/home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-54597535277775/" > /dev/null 2>&1
lenaic   26654 26636  0 00:00 pts/1    00:00:00 /bin/sh -c LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-270105586115111/command; rm -rf "/home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-270105586115111/" > /dev/null 2>&1
lenaic   26655 26652  6 00:00 pts/1    00:00:00 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-231434939428138/command
lenaic   26656 26653  6 00:00 pts/1    00:00:00 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-54597535277775/command
lenaic   26657 26654  5 00:00 pts/1    00:00:00 /usr/bin/python2 /home/lenaic/.ansible/tmp/ansible-tmp-1454713256.8-270105586115111/command
lenaic   26664  2549  0 00:00 pts/2    00:00:00 grep --color ansible

$ kill -TERM 26628
```
##### Expected Results:

Eventually, no `ansible` process remains.
It is actually what would have happened if the sent signal had been `INT` instead of `TERM`.
##### Actual Results:

Even after a long time:

```
$ ps -fu $UID | grep ansible
lenaic   26633     1 15 00:00 pts/1    00:00:21 /usr/bin/python2 /usr/bin/ansible -i inventory.ini all -m command -a sleep 30
```

`26633` was a children of the killed process. But instead of being cleaned, it has just been reaped by `init`.
##### Remarks

The reason why sub-processes are correctly cleaned when the master process is killed by `INT` and not by `TERM` is because there is [signal handling code specific to `INT`](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/playbook_executor.py#L72).

The issue is not reproducible if `ansible`/`ansible-playbook` is wrapped inside `/usr/bin/timeout` because that utility creates a process group before `fork`ing/`exec`ing and signals the whole process group when a timeout fires.

### PR DESCRIPTION
**Pull request by bcoca**
now both ansible and ansible-playbook properly terminate and reap children
fixes #14346

### CODE REVIEW

**Comment by lhuard1A** [comment]
Hi @bcoca ,

I tested this PR with two scenarios:
- The user launches `ansible all -m command -a "sleep 30"` and then, hit `Ctrl-C` before completion
- The user launches `ansible all -m command -a "sleep 30"` and then, send a `TERM` signal to the `ansible` process.

Here are my results:

#### When the user hit `Ctrl-C`:

##### Version 2.0.0.2

###### Output:

```
$ ansible -i /tmp/inventory.ini all -m command -a "sleep 30"
^C [ERROR]: User interrupted execution
```

###### Effect:

All the `ansible` processes are immediately killed.

##### With this PR `die_now`

###### Output:

```
$ PYTHONPATH=./lib/ python2 bin/ansible -i /tmp/inventory.ini all -m command -a "sleep 30"
^CProcess WorkerProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/process/worker.py", line 115, in run
    self._shared_loader_obj,
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/task_executor.py", line 421, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/action/__init__.py", line 463, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/action/__init__.py", line 524, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/connection/local.py", line 118, in exec_command
    stdout, stderr = p.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1409, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1463, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
Process WorkerProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/process/worker.py", line 115, in run
    self._shared_loader_obj,
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/task_executor.py", line 119, in run
Process WorkerProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/process/worker.py", line 115, in run
    self._shared_loader_obj,
ERROR! Unexpected Exception: can only test a child process
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/task_executor.py", line 119, in run
to see the full traceback, use -vvv
    res = self._execute()
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/task_executor.py", line 421, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/action/__init__.py", line 463, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/action/__init__.py", line 524, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/home/lenaic/doc/prog/ansible/lib/ansible/plugins/connection/local.py", line 118, in exec_command
    stdout, stderr = p.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 799, in communicate
 [ERROR]: User interrupted execution

    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1409, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1463, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
```

###### Effect:

All the `ansible` processes are immediately killed.

#### When a `TERM` signal is sent to the father `ansible` process. (The one whose PID is the PPID of the others)

##### Version 2.0.0.2

###### Output:

```
$ ansible -i /tmp/inventory.ini all -m command -a "sleep 30"
Complété
```

###### Effect:

Only the killed process disappears immediately.
All the remote processes still continue to process.
When a remote process eventually finishes, the local `ansible` process corresponding completes.
At the end, when all the remote processes have finished, a local `ansible` process remains forever.

##### With this PR `die_now`

###### Output:

```
$ PYTHONPATH=./lib/ python2 bin/ansible -i /tmp/inventory.ini all -m command -a "sleep 30"
Traceback (most recent call last):
Interrupt detected, shutting down gracefully
  File "/home/lenaic/doc/prog/ansible/lib/ansible/executor/process/result.py", line 104, in run
Interrupt detected, shutting down gracefully
Interrupt detected, shutting down gracefully
Interrupt detected, shutting down gracefully
    time.sleep(0.0001)
  File "/home/lenaic/doc/prog/ansible/lib/ansible/cli/adhoc.py", line 94, in _terminate
    raise SystemExit("Interrupt detected, shutting down gracefully")
SystemExit: Interrupt detected, shutting down gracefully
```

###### Effect:

All the local `ansible` processes are immediately killed.
All the remote processes still continue to process.
When all the remote processes eventually finish, everything is clean and no stale process remains anywhere.

### Conclusion

With this PR, in both use cases (User hitting `Ctrl-C` and `TERM` signal sent to `ansible`), all the processes spawned by `ansible` eventually finished.

However, in the case of the `TERM` signal sent to `ansible`, the remote processes were not killed and they eventually finished because it was a `sleep`, but it they were stuck, they would have remained stuck forever.

When the user hits `Ctrl-C`, there is now a stack trace which is dumped. Since this use case is supposed to be gracefully handled, it would nicer to not display it.

**Comment by fideloper** [comment]
I can't tell if Travis stalled on this build or if this PR changes something. After a seemingly successful run it ends with this:

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

In either case, this is biting me when attempting to run playbooks programmatically via `PlaybookExecutor.run()`. 

After a playbook is run, I can no longer send SIGTERM to the parent process kicking off/calling `PlaybookExecutor.run()` (it seems to get ignored, presumably because child processes are still running. Buffer needs flushing? I can't tell).

**Comment by sivel** [comment]
I am seeing what looks like a number of trace backs in the Travis build that seem to be related to this change:

```
Traceback (most recent call last):
  File "/home/travis/build/ansible/ansible/lib/ansible/executor/process/result.py", line 104, in run
    time.sleep(0.0001)
  File "/home/travis/build/ansible/ansible/lib/ansible/executor/playbook_executor.py", line 211, in _terminate
    raise SystemExit("Terminating run due to external signal")
SystemExit: Terminating run due to external signal
```

Not sure if this is the reason for the problems we are seeing with Travis not detecting that the tests are complete.

**Comment by bcoca** [comment]
@fideloper ok, so cleaned up some of the errors and controlled the verbosity, still you'll see 2 different behaviors:
- the keyboard interrupt will immediately kill all local processes (the remote will probably also die but that depends on it's state)
- the TERM signal will start a 'graceful' stop, no new tasks will run and existing ones will be allowed to finish (but won't report back).

@sivel travis issues should be fixed also

**Comment by nitzmahone** [comment]
:+1:

**Pull request merged**
