### PR TITLE
copy: Implement recursive copying if src is a directory.

### PR DESCRIPTION
**Pull request by pfalcon**
If src param to copy is a directory, all files under it are collected
and pushed one by one to target. Source dir path handled in a way
simalar to rsync: if it ends with slash, only inside contents of
directory are copied to destination, otherwise the dir itself is
copied (with all contents of course). Original idea and implementation
by https://github.com/ansible/ansible/pull/1809 . Rewritten to address
review comments and simplify/correct logic.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Note to reviewers:

very large patch, lots of things to test.

Consider SELInux policy on intermediate directories, permissions on intermediate directories, and various other things users may expect to be in place.

**Comment by mpdehaan** [comment]
@pfalcon:  Glad to see another crack at this.   Thanks!

**Comment by mpdehaan** [comment]
More things:

Also check mode, diff mode, changed reporting, etc

Folks will probably expect the same for the 'template' module, or not?   Let's get this one sorted first though.

**Comment by mpdehaan** [comment]
Also:

notifiers.

**Comment by pfalcon** [comment]
> very large patch, lots of things to test.

It's large because of identation change. I suggest checking out my branch and using git diff -b -w to ease review somewhat. Also, remembering @mpdehaan's comment for #1808 requesting squash, I didn't try to split to separate commits...

**Comment by mpdehaan** [comment]
Thanks!

**Comment by pfalcon** [comment]
Answering other questions:

> Consider SELInux policy on intermediate directories, permissions on intermediate directories

Well, I don't see any problem with that, far less impasse as Puppet hit  (based on your comments on #1808 an other related tickets). Recursive copy just creates dirs with default permissions (which is 0777 masked by umask - I wonder if Ansibel can/should be able to set umask). If user cares about specific permissions and other properties for dir(s), they should just pre-create them before recursive copy (using file state=directory).

**Comment by pfalcon** [comment]
Ah, just wanted to add to the above, that there might be idea to use "mode" param of copy action (inherited from "file") to affect permissions of directories created. But originally, "mode" is for _files_. And IMHO, trying to reuse that for directories would just lead to confusion and unexpected outcome for people.

**Comment by pfalcon** [comment]
> Also check mode, diff mode, 

I should start with saying that I don't have much experience with Ansible - i kept an eye on it for a while, but this is essentially first time I'm trying to do real-world things with it (as part of our pilot for both Ansible and Salt here at Linaro). Bottom line: I don't have much experience with check and diff mode. But my quick assessment of them was:
1. At least diff mode is fairly recent addition.
2. It appears it (at least copy module) support wasn't written by @mpdehaan, which makes it possible to think that it was just contributed, and is not a "core" Ansible feature.
3. It appears that diff implementation is rather heuristic - there're limits of files of what size will be diffed, heuristic on checking if file is binary, etc.

So, when writing this patch, I had a requirement of not regressing check/diff mode handling for one file case. Otherwise, based on the above I implemented following heuristic for recursive file case: not report any diffs for recursive files case. Note that code actually collects diffs for individual. But as I wrote, I didn't have experience with diff mode at all to understand how it works at large scale and thus how to extend it for multi-file case.

So, if there're suggestions how to handle it, based on the code provided (like, "yeah, just stuff that list of changes in result - should be good enough"), I'll be happy to do it. Otherwise, I hope this wouldn't be considered hard blocker for this patch - that part definitely can be improved over time.

**Comment by pfalcon** [comment]
> changed reporting

Changed reporting of course works. I.e., if there was at least one file changed, the action will report changed. Otherwise, changed=0.

**Comment by pfalcon** [comment]
> Folks will probably expect the same for the 'template' module, or not?

Well, my initial idea that substitutions can be handed on file by file basis. For example, because each file would have own set of subst vars. But the case I have at hand is exactly that - a small dir tree with 3-4 files, one which needs templating. So, yes, I see when recursive file templating would be both a productivity boost and make it all more seamless.

But yes, let's handle plain recursive file _copy_ first.

**Comment by pfalcon** [comment]
> notifiers

Well, I don't see explicit notifier handling in action_plugins/copy.py, nor in smoothify's original patch. So, I'd assume notifier handling happens automagically. Do you have any specific concerns?

**Comment by pfalcon** [comment]
Ok, I found a regression with the patch as it is now. It's however rooted in ambiguity of how copy action works (which of course rooted in ambiguity of how "cp" command works). So, what "file: src=files/foo dest=/bar" means? It may mean both "copy file foo into file bar" and "put file foo inside dir bar". Currently, Ansible resolves that based on target machine context. That works until "copy" gets the ability to create intermediate dirs, like required for recursive ops.

I don't know if it would be possible to apply some heuristics to avoid creating "unneeded" dirs, but I'm afraid that can only lead to more confusion. So, it would be better to require specific marking on user side that destination is a directory. One obvious way is end destination path with "/". Another is to use recurs: yes flag after all. Thoughts?

**Comment by pfalcon** [comment]
Btw, I found bug in copy plugin:

```
            if 'raw' in module_args:
                # don't send down raw=no
                module_args.pop('raw')
```

This definitely can't work, because module_args is a string. Which apparently means that raw copy is undertested (it's not documented though, so maybe it's not finished).

Another issues I hit is:

EDIT: False alarm, removed.

**Comment by pfalcon** [comment]
Ah, sorry, second part of previous msg is false alarm - will edit it out. It happens because modules_args is destructively modified in a loop now, need to fix that.

**Comment by pfalcon** [comment]
I pushed new version of the patches with bunch of issues fixed and with testcase which both tests there's no regressions for single-file case and checks that recursive behavior is sane across parameter variations.

To ease review, please use following link, which will filter whitespace differences: https://github.com/ansible/ansible/pull/4375/files?w=1

Please note that I after all added new commits as separate ones, to ease review - they can be squashed later.

**Comment by esamattis** [comment]
Any thoughts on `rsync --delete` like functionality?

I'd like to manage my nginx configuration with Ansible and I often need to delete some files from `/etc/nginx/{sites-available,sites-enabled}`.

Or do you think that adding a task that deletes the whole directory before the recursive copy task would suffice?

**Comment by jctanner** [comment]
@pfalcon thank you!

@epeli can you open a feature request for that?

**Comment by esamattis** [comment]
> @epeli can you open a feature request for that?

Sure thing! https://github.com/ansible/ansible/issues/4899

**Comment by pfalcon** [comment]
@jctanner: Thanks for merging!

@epeli: Yeah, that's one of the problem with recursive copy, and why it wasn't in Ansible for so long time - it seems easy to implement it, but then for real-world options, you may need bunch more options and features to it... Thanks for submit feature request, I hope someone will look into implementing it (you're welcome to). On my list next feature would be what was mentioned by @mpdehaan - adding recursive support for "template" action, I already see need for that.

**Pull request merged**
