### PR TITLE
Fix docs syntax highlighting errors

### LINKED ISSUE #50040: Docs code-blocks of task/playbook output should not get `err` class
##### SUMMARY
The red highlighting/boxes around the commas in the second code-block under https://docs.ansible.com/ansible/devel/user_guide/become.html#administrative-rights are `err` column spans.  The source does not specify a language for pygments, so the code-block is being read as `YAML+Jinja` per https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/conf.py#L111. 

We should be able to highlight Ansible task output without `err` highlighting.

I'm not sure at this point how difficult the fix would be. Maybe we can just choose a different lexer for those code blocks. Or maybe we need a lexer (Pygments highlighter) for Ansible output. 

Available lexers list: http://pygments.org/docs/lexers/

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docs.ansible.com

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This PR contains a couple of fixes of syntax highlighting errors reported in #50040. In most cases, the wrong lexer was used. Besides that, small problems with the Ansible output, YAML and Django lexers had to be fixed. I'll create upstream PRs for Pygments next.

Fixes #50040

CC @dagwieers @gundalow

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docs

### CODE REVIEW

**Comment by felixfontein** [comment]
Pygments Django PR: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/796/django-lexer-add-support-for-and-operators/diff
Pygments YAML PR: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/797/improve-yaml-mapping-lexing-fix-problems/diff

**Comment by felixfontein** [comment]
Both Pygments PRs have been merged for the next release, i.e. once that happens, we can throw out some of the lexers.

**Comment by gundalow** [comment]
Once Pygments has been a released do we remove the file `docs/docsite/_extensions/pygments_lexer.py`

**Comment by dagwieers** [comment]
Personally, I think we need to evolve to an Ansible lexer that:
- can distinguish between text-values and Jinja2 expressions (ie. when/until/...)
- includes yes/no booleans

That said, I am quite happy with the progress we have made. Priority should be on easy selection of docsite version. It is the number one inconvenience for our users. It should not be that hard to do IMO.

**Review by dagwieers — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@gundalow we can't remove it, since it contains the Ansible output lexer which isn't part of Pygments (yet). (For adding it to Pygments, I guess it needs to be more complete and better tested. Right now it's mostly good enough to run the output examples we have in the docs.)

**Comment by felixfontein** [comment]
@dagwieers I didn't notice that it doesn't know about all the other boolean values. That's something easy to add, though! (I guess we should add all of them, for completeness, and try to get it into Pygments.)

About `when`/`until`/...: that's a lot more tricky (and requires a huge redesign of the lexer). It would be nice to have that eventually, though.

**Comment by dagwieers** [comment]
@felixfontein I think the YAML lexer implements strict YAML 1.2, but we decided to allow both yes/no and true/false in documentation and examples. Adding all boolean values (i.e. on/off) is fine as well, since that's what Ansible does support anyway, but I doubt the strict YAML 1.2 is something they want to see changed.

**Comment by acozine** [comment]
@felixfontein thanks for doing this work - it looks great. As a next step, I think we need to document which lexers are available and when to use them. But meanwhile I'm going to merge this fix.

**Comment by felixfontein** [comment]
@acozine The plugin adds lexers `yaml`, `jinja` (alias `django`), `yaml+jinja`, and `ansible-output`. The first three are already provided by Pygments itself, but we've overridden them with some improvements. Where should we document them?

**Comment by acozine** [comment]
@felixfontein I'm thinking we could add them to the style guide, under https://docs.ansible.com/ansible/devel/dev_guide/style_guide/index.html#restructuredtext-guidelines

**Comment by webknjaz** [comment]
@felixfontein does `pygments_lexer` need to stay vendored?

**Comment by felixfontein** [comment]
@webknjaz parts of it definitely, for example `AnsibleOutputLexer` isn't in pygments (and there is no PR for it - I guess it should be more complete for that first). I'd have to check the rest, I don't remember which parts have already been integrated in pygments resp. whether something is missing.

**Comment by webknjaz** [comment]
@felixfontein

Sweet! Do you think it'd be possible to only keep the customized parts and just depend on the rest maintained somewhere else and installed by Pip?

**Comment by felixfontein** [comment]
`AnsibleYamlLexerContext`/`AnsibleYamlLexer` are equal to `YamlLexerContext`/`YamlLexer` in the current Pygments version, and `AnsibleDjangoLexer` is equal to `DjangoLexer`, and `AnsibleYamlJinjaLexer` is equal to `YamlJinjaLexer`. So yeah, we can get rid of all of them. I can create a PR for that.

Should I add a new enough pygments version to https://github.com/ansible/ansible/blob/devel/docs/docsite/requirements.txt ? Or where should I add that requirement?

**Comment by felixfontein** [comment]
(FYI: the required patches so that the code is actually equivalent are in Pygments 2.4.0 and newer.)

**Comment by webknjaz** [comment]
@felixfontein there's also a constraints file: https://github.com/ansible/ansible/blob/devel/test/runner/requirements/constraints.txt

**Pull request merged**
