### PR TITLE
Fix clone of specific SCM version

### PR DESCRIPTION
**Pull request by linkdd**
In a requirements.yml I had the following:

```

---

- src: https://mgitlab/mygroup/ansible-role-myrole.git
  scm: git
  version: somebranch
  name: myrole
```

The default branch of the repository was `develop`, and when `ansible-galaxy` was cloning the repository, the target branch wasn't fetched, resulting in a fail of the command `git archive`.

This fix adds to the clone command the option `-b <version>` for **git** and `-u <version>` for **mercurial** in order to prevent such problems.

### CODE REVIEW

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by lathama** [comment]
@mattclay This looks fine and safe. I would merge as an easy win.

**Comment by ghost** [comment]
pretty sure this code is now redundant. testing https://github.com/ansible/ansible/pull/34642 handles multiple versions/branches fine. 

Also this assumes all versions are branches. It could be a commit hash.

**Comment by lathama** [comment]
@jimi-c could you help with low hanging fruit here?

**Comment by mkrizek** [comment]
!waffling needs_revision

**Comment by bcoca** [comment]
closing as dupe of #34642

**Pull request closed without merging**
