### PR TITLE
Moving modules from lenovo to cnos

### PR DESCRIPTION
**Pull request by amuraleedhar**
##### SUMMARY
Moving the modules in lenovo folder to cnos folder.
This is done to match with the existing paradimn followed in this regard in ansible site.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

lib\ansible\modules\network\cnos\cnos_backup.py
lib\ansible\modules\network\cnos\cnos_bgp.py
lib\ansible\modules\network\cnos\cnos_command.py
lib\ansible\modules\network\cnos\cnos_conditional_command.py
lib\ansible\modules\network\cnos\cnos_conditional_template.py
lib\ansible\modules\network\cnos\cnos_factory.py
lib\ansible\modules\network\cnos\cnos_facts.py
lib\ansible\modules\network\cnos\cnos_image.py
lib\ansible\modules\network\cnos\cnos_interface.py
lib\ansible\modules\network\cnos\cnos_portchannel.py
lib\ansible\modules\network\cnos\cnos_reload.py
lib\ansible\modules\network\cnos\cnos_rollback.py
lib\ansible\modules\network\cnos\cnos_save.py
lib\ansible\modules\network\cnos\cnos_showrun.py
lib\ansible\modules\network\cnos\cnos_template.py
lib\ansible\modules\network\cnos\cnos_vlag.py
lib\ansible\modules\network\cnos\cnos_vlan.py

##### ANSIBLE VERSION
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

##### ADDITIONAL INFORMATION

This is an effort to move the lenovo modules from lenovo to cnos folder. 
These modules will therby represent the switch operating system which they support
This is the convention followed in ansible

### CODE REVIEW

**Comment by gundalow** [comment]
Hi,
Looks like the `paramiko` issues have been resolved. the `__future__` needs to be higher up, check other modules for examples

As a reminder you can run these commands locally, without having to wait for Shippable

```
source hacking/env-setup
ansible-test sanity --test pylint
ansible-test sanity --test import --python 2.7 # replacing 2.7 with whichever version of python you have locally
```

**Comment by amuraleedhar** [comment]
Please help, I am stuck on this import error of paramiko.

**Review by ganeshrn — COMMENTED** [review]
Please resolve the merge conflict. You can refer this doc http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

**Comment by amuraleedhar** [comment]
It seems I dont have permissions to do this.  It fails on message "Sync Failed to push local changes".
As I have moved files the conflicting files specified below are not accessible to me. How will I resolve this ?

**Comment by gundalow** [comment]
@privateip has some comments to make on this, in particular a cleaner way of importing `paramiko`

**Comment by amuraleedhar** [comment]
Sure, I will wait for @privateip' s comments and will make changes accordingly. 
But our long terms vision on this is to migrate everything to persistent connection. Then these whole paramiko will go off. I am waiting for work on enos to finish before starting on that. May be I could start on migration from Januvary 2018

**Comment by dkasberg** [comment]
Can this be merged now?

**Review by privateip — CHANGES_REQUESTED** [review]
@amuraleedhar why is paramiko being imported for these modules?  If these modules are CLI based, then we should be using the network_cli connection plugin and cliconf plugin to handle the connectivity to the device.  This is the only way that persistence can be supported.  I think these need to be refactored to use network_cli and cliconf before we merge them.

**Comment by amuraleedhar** [comment]
These modules were introduced prior to persistence connection came into effect. This PR is raised just to move the modules from "lenovo" folder to "cnos" folder. We have plans to migrate these modules from direct usage of paramiko to persistent connection in 2.6. This change cannot be done immediately as this involves changes in 17 modules and this invites a huge testing efforts from Lenovo QA. This can be merged as it is now or leave it till I take up migration to persistent connection in Jan 2018.

**Comment by privateip** [comment]
@amuraleedhar thanks for the background

**Review by privateip — APPROVED** [review]

**Comment by gundalow** [comment]
@amuraleedhar Please rebase and we will merge this

**Comment by gundalow** [comment]
http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

**Comment by amuraleedhar** [comment]
Rebase done, conflicts resolved. all are green, Please merge this.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged

**Pull request merged**
