### PR TITLE
Fix for Debian

### PR DESCRIPTION
**Pull request by damiadev**
+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by acozine** [comment]
Thanks @damiadev for finding and fixing this. Is https://github.com/ansible/ansible/pull/56351/files#diff-b0112cfc14039ad36c55e6bfe3e0e752R172 still accurate for Debian users?

**Comment by acozine** [comment]
Also @damiadev can you add the error message you ran into when running the example in the existing docs? This will help other users solve this problem.

**Comment by resmo** [comment]
Could not reproduce-
~~~
 $ cat /etc/debian_version 
buster/sid

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
Executing: /tmp/apt-key-gpghome.qRLnxmVecH/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
gpg: key 93C4A3FD7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
gpg: Total number processed: 1
gpg:               imported: 1
~~~

**Comment by damiadev** [comment]
> Could not reproduce.
> 
> ```
>  $ cat /etc/debian_version 
> buster/sid
> 
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
> Executing: /tmp/apt-key-gpghome.qRLnxmVecH/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
> gpg: key 93C4A3FD7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
> gpg: Total number processed: 1
> gpg:               imported: 1
> ```

Could not reproduce.

Uhmm.. I can nor reproduce now neither , may be something not working yesterday on keyserver.ubuntu.com

**Comment by acozine** [comment]
Thanks @damiadev and @resmo for the reviews! I'll close this with an incantation of support for the ubuntu keyserver.

**Pull request closed without merging**
