### PR TITLE
FreeBSD module to install packages using portinstall.

### PR DESCRIPTION
**Pull request by berenddeboer**
FreeBSD module to install or deinstall software from its ports tree.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Sorry for the late reply on this one.

@bcoca as our resident former BSD user of note, any thoughts on this particular module?

Thanks!

**Comment by bcoca** [comment]
The Freebsd side looks as good as it can get, I haven't tested but it seems
like it can do a decent job of finding out if a package is installed (as
comments say, not easy on FreeBSD).

On the ansible side:

I would make the use_packages a boolean type with BOOLEANS as options.

The module takes a list for packages, but not from with_items but as a
comma delimited string. Might be worth making it like apt and yum modules.

I would use get_bin_path() for pkg_info, pkg_delete and ports/pkg_glob(I
learnt something new!)  and not rely on path.

**Comment by berenddeboer** [comment]
with_items support would be great, but can be done later as improvement.

Agree on use_packages (don't know what that means, but sounds good, and I probably can copy code from other modules).

Don't know about get_bin_path, I suppose that's not bleeding edge, but widely supported, see a fair amount of ansible commit comments on this.

**Comment by bcoca** [comment]
Here are the examples.

For use_packages:
   dict(type='bool', choices=BOOLEANS, default='yes')

You actually use get_bin_path already in the module:
   portinstall_path = module.get_bin_path('portinstall', True)

**Comment by jctanner** [comment]
@berenddeboer can you squash this down to a single commit via a feature branch and open a new PR please?

**Comment by berenddeboer** [comment]
jctanner, have done so, see here: https://github.com/ansible/ansible/pull/4908

**Pull request closed without merging**
