### PR TITLE
[2.4] Change: set the 'canonical_url' to /latest/

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY

Original PR #49190

(cherry picked from commit 59e7a9442e0fbb9c827f6c4d58ea7aebf5b04b02)

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Review by acozine — APPROVED** [review]
This change will tell search engines that they should be pointing users to the `latest` docs rather than to `2.4`. Currently the 2.4 docs are prioritized, because they don't have a `canonical_url` set, because they are long-lived, and because there are lots of links to them elsewhere on the web.

**Review by Xaroth — APPROVED** [review]

**Review by Xaroth — COMMENTED** [review]
Does the old 'srtd' theme actually support the canonical_url option?

**Review by Xaroth — CHANGES_REQUESTED** [review]
Upon further checking:

[docs/docsite/_themes/sphinx_rtd_theme/layout.html](https://github.com/ansible/ansible/blob/devel/docs/docsite/_themes/sphinx_rtd_theme/layout.html#L38-L39)  shows the ``sphinx_rtd_theme`` implementing the canonical_url option, and it is specified in [docs/docsite/_themes/sphinx_rtd_theme/theme.conf](https://github.com/ansible/ansible/blob/devel/docs/docsite/_themes/sphinx_rtd_theme/theme.conf)

The ``srtd`` theme does neither:

[docs/docsite/_themes/srtd/layout.html](https://github.com/ansible/ansible/blob/devel/docs/docsite/_themes/srtd/layout.html) contains no mention of 'canonical'
[docs/docsite/_themes/srtd/theme.conf](https://github.com/ansible/ansible/blob/devel/docs/docsite/_themes/srtd/theme.conf) also does not mention an option like that.

**Comment by acozine** [comment]
Per @Xaroth's comment, this change will not help, because the theme in place on the 2.4 documentation does not support this setting. We will seek alternative solutions.

**Pull request closed without merging**
