### PR TITLE
Filter split list

### PR DESCRIPTION
**Pull request by bcavns01**
##### SUMMARY

This PR adds a new filter to core that allows for splitting a single list into a list of sublists of configurable size.  For example, a list of 100 dictionaries could be turned into a list containing 5 sublists of 20 dictionaries each.

I see this largely benefiting templates, and my use case was for improving readability of generated configs for Juniper switches by breaking long as-paths and prefix lists into multiple sublists; however, it could also be used for chunked processing of items in task loops.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
split_list

##### ADDITIONAL INFORMATION
Example:

    - debug:
        msg: '{{ ["a","b","c","d","e"]|split_list(3) }}'

```
TASK [debug] **********************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c"
        ],
        [
            "d",
            "e"
        ]
    ]
}

```

### CODE REVIEW

**Comment by sivel** [comment]
This can already be achieved using the jinja2 provided `slice` filter.

The only difference is knowing how many buckets you want, and not how many items per bucket.

```
- debug:
    msg: '{{ ["a","b","c","d","e"]|slice(2)|list }}'
```

```

localhost | SUCCESS => {
    "msg": [
        [
            "a",
            "b",
            "c"
        ],
        [
            "d",
            "e"
        ]
    ]
}
```

**Comment by bcavns01** [comment]
Thank you for the quick review.

If the need is to have a certain number of slices, regardless of the number of items per slice, then slice() works for sure, but if control over the number of items per slice is desired/required, then it appears that slice() does not provide a decent solution.

The closest I could get was with something a bit unwieldy like this: `lst|slice((((lst|length)/desired_slice_len)|round(method="ceil")|int))|list `

However, without your list size being constant and knowing what the length is prior to running, or doing even more gynastics, it's difficult to know if that alone will give you the desired results.

Some examples:

```
TASK [Desired slicing] ************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "List length: 5  ;  Desired slice length: 4  ;  Slices based on desired length: 2"
}

TASK [With filter chain] **********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c"
        ],
        [
            "d",
            "e"
        ]
    ]
}

TASK [With split_list] ************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c",
            "d"
        ],
        [
            "e"
        ]
    ]
}
```

```
TASK [Desired slicing] ************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "List length: 6  ;  Desired slice length: 4  ;  Slices based on desired length: 2"
}

TASK [With filter chain] **********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c"
        ],
        [
            "d",
            "e",
            "f"
        ]
    ]
}

TASK [With split_list] ************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c",
            "d"
        ],
        [
            "e",
            "f"
        ]
    ]
}
```

```
TASK [Desired slicing] ************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "List length: 7  ;  Desired slice length: 3  ;  Slices based on desired length: 3"
}

TASK [With filter chain] **********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c"
        ],
        [
            "d",
            "e"
        ],
        [
            "f",
            "g"
        ]
    ]
}

TASK [With split_list] ************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c"
        ],
        [
            "d",
            "e",
            "f"
        ],
        [
            "g"
        ]
    ]
}

```

**Comment by gundalow** [comment]
bot_status

This should be `support:core`

**Comment by gundalow** [comment]
bot_status

**Comment by bcavns01** [comment]
Respectfully bumping. :)
Any further feedback on this?

**Comment by hvhaugwitz** [comment]
What is the state of this pull request?

**Comment by bcavns01** [comment]
I'd still love to see it accepted. :D

**Comment by hvhaugwitz** [comment]
@bcavns01 It seems the built-in `batch` filter is what you want:
```
 batch(value, linecount, fill_with=None)

     A filter that batches items. It works pretty much like slice just the other way round.
     It returns a list of lists with the given number of items. If you provide a second
     parameter this is used to fill up missing items. See this example:
```
Example tasks:
```
- debug:
    msg: '{{ ["a","b","c","d","e"] | batch(4) | list }}'
- debug:
    msg: '{{ ["a","b","c","d","e","f"] | batch(4) | list }}'
- debug:
    msg: '{{ ["a","b","c","d","e","f","g"] | batch(3) | list }}'
```
Output:
```
TASK [debug] **********
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c",
            "d"
        ],
        [
            "e"
        ]
    ]
}

TASK [debug] *********
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c",
            "d"
        ],
        [
            "e",
            "f"
        ]
    ]
}

TASK [debug] ********
ok: [localhost] => {
    "msg": [
        [
            "a",
            "b",
            "c"
        ],
        [
            "d",
            "e",
            "f"
        ],
        [
            "g"
        ]
    ]
}
```

**Pull request closed without merging**
