### PR TITLE
htpasswd: Allow htpasswd to update/not update passwords

### PR DESCRIPTION
**Pull request by martingalloar**
Add option to choose if password for the user should be updated when setting state 'present' and the user was already in the file. This allows using the module for ensuring that certain users are there but not change their passwords every time.

### CODE REVIEW

**Comment by martingalloar** [comment]
Migrated from https://github.com/ansible/ansible-modules-core/pull/2427

**Review by bjolivot — COMMENTED** [review]
I would have done this differently.
If state present and no password given, check only user.
If state present and password set in module then check both user and password.

**Comment by martingalloar** [comment]
I remember there was a reason why I didn't implemented it that way, but can't find a valid scenario now while your proposal doesn't fit. Will adjust the PR ASAP!

**Comment by bmillemathias** [comment]
Hi @martingalloar 

I known it was some time ago, but are you still interested to provide the updated PR

Best.

**Comment by martingalloar** [comment]
Sorry didn't got back to this in long time, I'll take a look at the code to review the update logic.

**Pull request closed without merging**
