### PR TITLE
migrate Cisco NSO modules from community.network collection to cisco.nso

### PR DESCRIPTION
**Pull request by mamullen13316**
##### SUMMARY
Migrates Cisco NSO modules from community.network to cisco.nso namespace

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
nso_action
nso_verify
nso_query
nso_config
nso_show

##### ADDITIONAL INFORMATION
https://github.com/ansible-community/ansible-build-data/pull/41
https://github.com/CiscoDevNet/ansible-nso/issues/4
https://github.com/ansible/ansible/pull/72753

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @gundalow  @felixfontein

**Comment by felixfontein** [comment]
I think it's better to handle all migration from https://github.com/ansible-collections/overview/issues/128 in one PR. I've created #73046 for that.

**Comment by Akasurde** [comment]
@felixfontein is this still valid PR? 


needs_info

**Comment by Akasurde** [comment]
Closing as per https://github.com/ansible/ansible/pull/72892#issuecomment-749446724

**Pull request closed without merging**
