### PR TITLE
GCE Dynamic Inventory script using Google API Client library

### PR DESCRIPTION
**Pull request by maurofaccenda**
##### SUMMARY
We needed to use the beta version of the API (to be able to use labels) and figured out that Apache's libcloud (used by the current gce.py) only uses 'v1' (it is hardcoded).

So, a new script that uses Google API Client library was created from scratch. It was inspired by some of the current gce.py features, however not 100% of the features are there yet.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
contrib/inventory/gce_googleapiclient.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### CODE REVIEW

**Comment by nitzmahone** [comment]
cc @supertom - thoughts?

**Comment by supertom** [comment]
@maurofaccenda thanks for the PR!  We like the idea of being able to specify different API versions as well, and we've been asked about label support, so your timing is good.

I haven't tried this yet, but I see that you mention that it doesn't have feature-parity with the existing gce.py.  Is that something you're willing/able to add?  More specifically,
* We'd like it to use the authentication functions that we've added in module_utis/gcp.py
* It needs to produce the same output as the existing gce.py (or at least, compatible, we could discuss)
* Needs to support caching (which could probably be a lift-and-shift from the existing gce.py)

**Comment by maurofaccenda** [comment]
@supertom sure. I am willing to do that. However as I am doing that as part of my work (the customer asked explicitly to send the code upstream), it would be nice to have:

- list of changes would be the bare minimum to get it accepted upstream
- 'wish list' for some extra changes to do them afterwards.

With that, I can create the tasks on our internal issue tracker and they can prioritise the tasks accordingly with their needs.

Keep in mind that I am not Python 'fluent', so some input/help would be great.

From what you mentioned, the idea is to have it 100% (or as much as possible) compatible at some point.

**Comment by erjohnso** [comment]
Hi @maurofaccenda - just doing a weekly pass of open PRs and wanted to check in here. Are you ready for another review, or still working on feedback from @supertom?

Feel free to ping me directly too when you're ready for another pass.

**Comment by maurofaccenda** [comment]
Hi @erjohnso,

Thanks for checking out. We've done some updates but not all of his requirements are done yet.

But I believe it is good to have some feedback anyway.

What is still missing: caching and using Ansible's authentication functions.
Also, there are still some hostvars that are not being set (gce_uuid and gce_description, that I remember from the top of my head), but I believe that could be OK.

**Comment by maurofaccenda** [comment]
@erjohnso @supertom i believe it now is 'feature complete', can you confirm and see if there is anything missing to merge it?

thx

**Comment by seanmalloy** [comment]
@erjohnso and @supertom would one of you be able to provide some feedback on this pull request?

**Comment by davidebelloni** [comment]
Hi,
both gce.py and gce_googleapiclient.py seems to not support the inventory develop guidelines (http://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#inventory-plugins)
If i try to use gce_googleapiclient.py I've:

```
$ ansible all -i gce_googleapiclient.py -m ping -vvv
ansible 2.5.0
  config file = /Users/user/git/gcp/ansible-common/ansible.cfg
  configured module search path = [u'/Users/user/git/gcp/ansible-common/library']
  ansible python module location = /Users/user/Software/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/user/Software/ansible/bin/ansible
  python version = 2.7.13 (default, May 12 2017, 11:09:30) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
Using /Users/user/git/gcp/ansible-common/ansible.cfg as config file
ERROR! Unexpected Exception, this is probably a bug: 'module' object has no attribute 'InventoryModule'
the full traceback was:

Traceback (most recent call last):
  File "/Users/davidebelloni/Software/ansible/bin/ansible", line 118, in <module>
    exit_code = cli.run()
  File "/Users/davidebelloni/Software/ansible/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 114, in run
    loader, inventory, variable_manager = self._play_prereqs(self.options)
  File "/Users/davidebelloni/Software/ansible/lib/python2.7/site-packages/ansible/cli/__init__.py", line 804, in _play_prereqs
    inventory = InventoryManager(loader=loader, sources=options.inventory)
  File "/Users/davidebelloni/Software/ansible/lib/python2.7/site-packages/ansible/inventory/manager.py", line 145, in __init__
    self.parse_sources(cache=True)
  File "/Users/davidebelloni/Software/ansible/lib/python2.7/site-packages/ansible/inventory/manager.py", line 197, in parse_sources
    self._setup_inventory_plugins()
  File "/Users/davidebelloni/Software/ansible/lib/python2.7/site-packages/ansible/inventory/manager.py", line 184, in _setup_inventory_plugins
    plugin = inventory_loader.get(name)
  File "/Users/davidebelloni/Software/ansible/lib/python2.7/site-packages/ansible/plugins/loader.py", line 373, in get
    obj = getattr(self._module_cache[path], self.class_name)
AttributeError: 'module' object has no attribute 'InventoryModule'

```
Thanks

**Comment by maurofaccenda** [comment]
Hi @davidebelloni, thanks for your feedback.

When the script was developed I believe the mentioned guideline wasn't yet in place. I'll try to take some time to adhere to it.

Cheers,

**Comment by maurofaccenda** [comment]
@davidebelloni I took a closer look at the documentation you linked and it seems that it is meant for inventory plugins. This code is a Dynamic Inventory script, the conventions/guidelines are here:

http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#script-conventions

The command you've used worked for me (but I've found a couple bugs that I am fixing now).

**Comment by davidebelloni** [comment]
Hi @maurofaccenda ,
thank you for the pointer!
Usually I don't use neither inventory scripts nor inventory plugins

And thanks for the fixes ;)

**Comment by davidebelloni** [comment]
What about add service account info?

Something like this:

'gce_svc': instance['serviceAccounts'][0]['email']

**Comment by erjohnso** [comment]
👍 This LGTM

/cc @ryansb - think we could merge this, or are we in code freeze for 2.6 now?

**Comment by YogSottot** [comment]
> -h is specified ambiguously 2 times

> -h, --host HOSTNAME
> -h, --help

Also this script support only python2

> The StringIO and cStringIO modules are gone. Instead, import the io module and use io.StringIO or io.BytesIO for text and data respectively.

> In Python 3, ConfigParser has been renamed to configparser for PEP 8 compliance. 

If i try to set this

```python

# add python3 compatibility
try:
    import ConfigParser
except ImportError:
    import configparser

try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO

```
and so on...

Then i get

```bash

 [WARNING]:  * Failed to parse gce_googleapiclient_python3.py with script plugin:  
Inventory script gce_googleapiclient_python3.py had an execution error: 
Traceback (most recent call last):   
File gce_googleapiclient_python3.py, line 219, in <module>     GCAPI = GCloudAPI()  
gce_googleapiclient_python3.py, line 129, in __init__     self.credentials = GCloudAPI._get_credentials()
gce_googleapiclient_python3.py, line 177, in _get_credentials     gce_service_account_email_address = args[0] IndexError: list index out of range

 [WARNING]:  * Failed to parse gce_googleapiclient_python3.py with ini plugin:
gce_googleapiclient_python3.py:2: Error parsing host definition '"""': No closing quotation

```

With python2 it works ok

**Comment by mattclay** [comment]
@maurofaccenda New `contrib/inventory/` scripts are not being accepted. Instead, convert your inventory script to an inventory plugin. See [developing inventory](https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#inventory-plugins) for additional details. You may also want to look at the existing [gcp_compute](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/gcp_compute.py) inventory plugin.

**Comment by maurofaccenda** [comment]
@mattclay this was developed long time ago, for ansible 2.3, where the new inventory thing  wasn't in place yet. I am not sure if there is anything from this script that could be useful for the new way of creating dynamic inventory, so I guess it really doesn't make much sense for newer versions of Ansible anyway.

It could still be useful for whom uses older versions <2.5 which some distros still provide. So I am not sure if it would make sense to keep this PR or not.

Do as you please.

**Comment by maurofaccenda** [comment]
@mattclay this was developed long time ago, for ansible 2.3, where the new inventory thing  wasn't in place yet. I am not sure if there is anything from this script that could be useful for the new way of creating dynamic inventory, so I guess it really doesn't make much sense for newer versions of Ansible anyway.

It could still be useful for whom uses older versions <2.6 (I'm guessing) which some distros still provide. So I am not sure if it would make sense to keep this PR or not.

Do as you please.

**Comment by maurofaccenda** [comment]
Just in case, I've created the following repo to keep these if someone finds it useful.

https://github.com/maurofaccenda/ansible-gcp-dynamic-inventory

**Comment by mattclay** [comment]
@maurofaccenda Thanks for publishing a copy for users of older versions of Ansible. I'll go ahead and close this PR then.

**Pull request closed without merging**
