### PR TITLE
Add option to perform EC2 inventory by Amazon Machine Image (AMI) IDs.

### PR DESCRIPTION
**Pull request by JoeyGAtNi**
If only want the option to configure EC2 inventory by AMI IDs.

### CODE REVIEW

**Comment by JoeyGAtNi** [comment]
Commit 0c956de9bdeaf801de532bc6acfb244de52fb327 provides ability to configure which groups are created by the EC2 inventory script.

**Comment by mpdehaan** [comment]
Per comments on ticket #7574 let's not merge this just now so GitHub support can see what's up with the links in the other ticket showing ansible/ansible pre merge - until we get a response back.  They are usually pretty quick.

Otherwise this looks good to me and I like the feature of having more group control.

Thank you!

**Comment by mpdehaan** [comment]
GitHub has seen the bug on the reporting so this is good to go in my book.  Thanks!

**Comment by JoeyGAtNi** [comment]
Do you need anything else before merging this pull request?

**Comment by jimi-c** [comment]
@JoeyGAtNi nope we should be good, we're just working through our priority queue and will get to testing this as soon as possible. Thanks!

**Comment by bcoca** [comment]
closing through alternative PR meged

**Pull request closed without merging**
