### PR TITLE
ACME: add diff to acme_account, account_public_key to acme_account_facts, and general refactoring

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This PR:
 * refactors account initialization in module_utils/acme.py (split up convoluted `init_account` in `setup_account` and `update_account`);
 * adds diff mode to `acme_account`;
 * adds `account_public_key` to `acme_account_facts` (and `acme_account` diffs).

##### ISSUE TYPE
- Feature Pull Request

Includes commits from #49407, which I will remove once that one is merged.

##### COMPONENT NAME
lib/ansible/module_utils/acme.py
lib/ansible/modules/crypto/acme/acme_account.py
lib/ansible/modules/crypto/acme/acme_account_facts.py

##### ADDITIONAL INFORMATION
Examples (from integration tests):
``` .diff
TASK [Create it now (check mode, diff)] **********************************************************************************************************
Saturday 01 December 2018  23:20:58 +0100 (0:00:00.503)       0:00:02.909 ***** 
--- before
+++ after
@@ -1 +1,11 @@
-{}
+{
+    "contact": [
+        "mailto:example@example.org"
+    ],
+    "public_account_key": {
+        "crv": "P-256",
+        "kty": "EC",
+        "x": "mVKyEkQCMb0fFeJBVpu1oNTiUtFGxNTo_25EwZv197o",
+        "y": "0bx4wSELG2Mlnmiqr4HEsLdJqTbuPdsXSico97EZ43k"
+    }
+}

changed: [localhost]

TASK [Change email address (check mode, diff)] ***************************************************************************************************
Saturday 01 December 2018  23:20:59 +0100 (0:00:00.359)       0:00:03.989 ***** 
--- before
+++ after
@@ -1,7 +1,7 @@
 {
     "ID": "1",
     "contact": [
-        "mailto:example@example.org"
+        "mailto:example@example.com"
     ],
     "key": {
         "crv": "P-256",

changed: [localhost]

TASK [Change account key (check mode, diff)] *****************************************************************************************************
Saturday 01 December 2018  23:21:01 +0100 (0:00:00.215)       0:00:05.503 ***** 
--- before
+++ after
@@ -10,10 +10,10 @@
         "y": "0bx4wSELG2Mlnmiqr4HEsLdJqTbuPdsXSico97EZ43k"
     },
     "public_account_key": {
-        "crv": "P-256",
+        "crv": "P-384",
         "kty": "EC",
-        "x": "mVKyEkQCMb0fFeJBVpu1oNTiUtFGxNTo_25EwZv197o",
-        "y": "0bx4wSELG2Mlnmiqr4HEsLdJqTbuPdsXSico97EZ43k"
+        "x": "x0VMKGFJN0SY1sqFa7QzTm2HW6rsTdHaQOiDFdRS9UhKQ_Q_-Xl5_mRYky1V-JDO",
+        "y": "lTY593cEBFoMkDlK6qybCDa-KBdaAOIG3XlY-6hIljAoMpX9wLvV4A_HQ02P1a8g"
     },
     "status": "valid"
 }

changed: [localhost]

TASK [Deactivate account (check mode, diff)] *****************************************************************************************************
Saturday 01 December 2018  23:21:02 +0100 (0:00:00.408)       0:00:06.273 ***** 
--- before
+++ after
@@ -1,19 +1 @@
-{
-    "ID": "1",
-    "contact": [
-        "mailto:example@example.com"
-    ],
-    "key": {
-        "crv": "P-384",
-        "kty": "EC",
-        "x": "x0VMKGFJN0SY1sqFa7QzTm2HW6rsTdHaQOiDFdRS9UhKQ_Q_-Xl5_mRYky1V-JDO",
-        "y": "lTY593cEBFoMkDlK6qybCDa-KBdaAOIG3XlY-6hIljAoMpX9wLvV4A_HQ02P1a8g"
-    },
-    "public_account_key": {
-        "crv": "P-384",
-        "kty": "EC",
-        "x": "x0VMKGFJN0SY1sqFa7QzTm2HW6rsTdHaQOiDFdRS9UhKQ_Q_-Xl5_mRYky1V-JDO",
-        "y": "lTY593cEBFoMkDlK6qybCDa-KBdaAOIG3XlY-6hIljAoMpX9wLvV4A_HQ02P1a8g"
-    },
-    "status": "valid"
-}
+{}

changed: [localhost]
```

### CODE REVIEW

**Comment by resmo** [comment]
nice! ready for review?

**Comment by felixfontein** [comment]
@resmo yes, I think it should be fine!

**Comment by felixfontein** [comment]
I've tested it against the Let's Encrypt staging endpoints (both v1 and v2), so I think it should really be fine.

**Review by resmo — APPROVED** [review]
shipit

**Comment by resmo** [comment]
nice and clean as usual.

**Comment by felixfontein** [comment]
@resmo thanks for reviewing and merging! :)

**Pull request merged**
