### PR TITLE
BIGIP: removes redundant functions

### PR DESCRIPTION
**Pull request by wojtek0806**
##### SUMMARY
removes redundant functions
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/module_utils/network/f5/common.py

### CODE REVIEW

**Comment by wojtek0806** [comment]
this needs to be merged as the last PR once the rest is merged, i will rebase

**Comment by caphrim007** [comment]
@wojtek0806 you should now be able to rebase

**Comment by caphrim007** [comment]
@wojtek0806 I think your other PRs have been merged if you want to rebase this now?

**Comment by wojtek0806** [comment]
@caphrim007 resolved the issue with the 2 modules, should be good now, please review

**Review by caphrim007 — APPROVED** [review]
shipit

**Pull request merged**
