### PR TITLE
Feature: include_vars can parse .env files

### PR DESCRIPTION
**Pull request by AJamesPhillips**
##### SUMMARY
Often environment variables are stored in an "env file format" file, i.e. something that can be sourced from a bash shell.  It's often useful to having these variables inside ansible.  One example is that systemd config allows you to set environment using:  `Environment={% for key, value in ENV_RUNTIME.items() %}{{ key }}={{ value }} {% endfor %}`, you may also need to use them in templates for web server and application server config files.

This is a putative proposal.  I'd be interested to hear what others think of this use case.  There are no tests or docs yet but I'm happy to add if this feature is desired / not implemented somewhere else.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

    lib/ansible/plugins/action/include_vars.py
    lib/ansible/parsing/dataloader.py

##### ANSIBLE VERSION
Based off commit 025b52938eb449b48e6ac57254161ad4673ab79c on devel.

```
ansible 2.4.0 (include_vars_env a8986607a2) last updated 2017/06/14 15:25:28 (GMT +100)
  config file = 
  configured module search path = ['/Users/ajp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ajp/app/ansible/lib/ansible
  executable location = /Users/ajp/app/ansible/bin/ansible
  python version = 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### ADDITIONAL INFORMATION

Before:

No output given.  Something in the ansible error handling hangs due to the yaml `err_obj` (e.g. `<ansible.parsing.yaml.objects.AnsibleBaseYAMLObject object at 0x1005033c8>`) in [`raise AnsibleParserError(YAML_SYNTAX_ERROR, obj=err_obj, show_content=show_content, orig_exc=yaml_exc)`](https://github.com/ansible/ansible/blob/4befefd78c2a19c21e0252860f389d5bb7274eb0/lib/ansible/parsing/dataloader.py#L205).

After:

```
  - include_vars:
      file: "{{ role_path }}/../app/{{ ENV }}.env"
      name: ENV_RUNTIME
```

`ENV_RUNTIME` will be set to a dictionary of the parsed environment variable key/values.

### CODE REVIEW

**Comment by bcoca** [comment]
I would not tack this onto include_vars, much less data loader.

A new action plugin include_vars_from_env, or a 'format' option in include vars (defaults to YAML/JSON) would be better approaches.

**Comment by AJamesPhillips** [comment]
Thanks for the feedback @bcoca I'll adapt this to your suggestions.  I mainly wanted to know if ansible users thought this was a useful pattern.  I don't want to bloat ansible with unused / broadly useless features.

Re implementation, yes I completely agree that DataLoader is not the right place for this and there should be a format option for `include_vars`.

**Comment by bcoca** [comment]
As in the previous comment, I don't think this is a good fit for the current code, you can create a dedicated lookup or action plugin that does the same.

**Comment by AJamesPhillips** [comment]
Ok.  Thanks for the feedback.  I had tried implementing

> a 'format' option in include vars (defaults to YAML/JSON)

But I will rework as a new `include_vars_from_env` action plugin instead.

**Comment by calfonso** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us that you've taken time to contribute.

Closing this based upon the latest conversation and you can open a PR for the new implementation. 

You can stop by the development list, and we'd be glad to talk about it.

https://groups.google.com/forum/#!forum/ansible-devel
In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
