### PR TITLE
readded sudo/su vars to allow role/includes to work with passed sudo/su

### LINKED ISSUE #10550: playbook sudo: yes roles are not executed as sudo.
Issue Type:

Bug

Ansible Version:  1.9.0.1 from ppa stable.

Environment:

Linux Ubuntu 12.04 host to Linux Debian wheezy target.

Summary:

playbook roles are not executed as sudo anymore.

Steps To Reproduce:

consider the following playbook working with 1.7.2 but no more working with the 1.9.0.1:

test.yml

```
- hosts: test
  roles:
    - role: addgroups
      sudo: yes
```

roles/addgroups/tasks/main.yml

```

---
- name: add toto group
  group: name=toto state=present
```

Expected Results:

add the test group without any failure.

Actual Results:

failed: [zoo] => {"failed": true, "name": "test"}
msg: groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later

digging into the verbose mode we can observe that the addgroups role is still called with sudo with older version i.e. 1.7.2 and not any more called with sudo with 1.9.0.1

1.7.2

```
u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=hgpjwxwhvkcrvjywzmwiwhxnnamxrfln] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-hgpjwxwhvkcrvjywzmwiwhxnnamxrfln; LANG=C LC_CTYPE=C /usr/bin/python /home/test/.ansible/tmp/ansible-tmp-1427390484.81-80330223816703/group\'"
```

1.9.0.1

```
/bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /home/test/.ansible/tmp/ansible-tmp-1427392790.43-74683051810820/group
```

Cheers

### PR DESCRIPTION
**Pull request by bcoca**
should fix #10550

### CODE REVIEW

**Comment by graingert** [comment]
Any chance of a unittest for this? It's a regression that wasn't caught.

**Comment by bcoca** [comment]
Already added to v2 tree, not a regression as it was never a bug previously.

**Comment by graingert** [comment]
This is definitely a regression, as it was working in 1.8.4 and broken in 1.9.0.1...

**Comment by sivel** [comment]
A regression is defined as:

> The _reappearance_ of a bug in a piece of software that had previously been fixed.

So in this case, it's just a bug, not a regression, since it was never a bug before.

**Comment by graingert** [comment]
http://en.wikipedia.org/wiki/Software_regression

**Comment by bcoca** [comment]
this was also not an intended feature in ansible, so by either definition....

**Comment by ches** [comment]
@bcoca What part of this "was also not an intended feature in ansible"? See #3579.

Regardless of differing stances on the semantics of "regression", the 1.9.0.1 Ansible release broke my previously-working configuration runs, and I'm guessing it wasn't just @graingert and me.

Not trying to assign any blame here, just sayin' this is a pretty aggravating bug---would love to see a bugfix release bump, my team runs packaged Ansible releases and I hear an earful when I have to ask people to run from devel.

**Comment by graingert** [comment]
I now have a state:

``` yaml
- name: assert ansible==1.8.4
  assert:
    that: "ansible_version.full == '1.8.4'"
```

In my ansible tasks

**Comment by bcoca** [comment]
it will be in a 1.9.1 release

@ches, i had to remove some code that specifically guarded against that, my guess is that opinions on this 'feature' changed over time. In any case we are supporting it now as a feature.

**Pull request merged**
