### PR TITLE
[2.10] Fix various sanity errors in plugins

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #71736 to stable-2.10, with all parts removed (in second commit) that are potentially disruptive.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
...

### CODE REVIEW

**Review by relrod — APPROVED** [review]
Went through these all and they LGTM.

**Comment by relrod** [comment]
Discussed on IRC, probably best to add a changelog for the url lookup fixes.

**Comment by felixfontein** [comment]
PR with changelog fragment for `devel` is #72323.

**Comment by felixfontein** [comment]
@relrod thanks a lot for reviewing, retriggering tests and merging! :)

**Pull request merged**
