### PR TITLE
Assorted pylint fixes

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This fixes all *ansible-format-automatic-specification* pylint issues and cleans up the pylint *ignore.txt* file.

This PR also includes:
- Two other pylint issues
- Copyright statement format fixes
- One-line license statement when needed

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Various files

### CODE REVIEW

**Comment by dagwieers** [comment]
bot_skip

**Comment by dagwieers** [comment]
cc @gundalow @mattclay

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
Since we just updated our default test container (including a new version of pycodestyle) I'm going to re-run the tests before merging this.

**Comment by dagwieers** [comment]
Tests seem to ran fine.

**Comment by mattclay** [comment]
@dagwieers Thanks for cleaning up the remaining style issues.

**Pull request merged**
