### PR TITLE
WIP - Don't call v2_runner_on_ok on include/include_task

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Don't call the `v2_runner_on_ok` callback on `include` or `include_task`.
This avoids calling both `v2_runner_on_ok` and `v2_runner_on_failed` for imports that fail.

Before this change, include callbacks were:

- v2_runner_on_ok
- v2_playbook_on_include on success
- v2_runner_on_failed on failure

After this change, include callbacks are:

- v2_playbook_on_include on success
- v2_runner_on_failed on failure

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/plugins/strategy/__init__.py`

##### ANSIBLE VERSION

```
ansible 2.6.0 (no-redundant-include-callback 76c3db0ae9) last updated 2018/05/03 23:39:05 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 11:39:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION

Integration tests have been added to verify the expected callbacks are made for includes.

### CODE REVIEW

**Comment by bcoca** [comment]
since include_X are now closer to real tasks, i'm unsure if this change is correct as any successful task should trigger `on_ok`

**Comment by mattclay** [comment]
I could add `v2_runner_on_ok` just before`v2_playbook_on_include`, which would only send it on success.

**Comment by bcoca** [comment]
yes, it should do `on_ok` only when so

**Comment by mattclay** [comment]
@bcoca It looks like sending `v2_runner_on_ok` on success is going to be a problem, as we don't have the task result at the point at which we know the include succeeded.

**Comment by bcoca** [comment]
wasn't the code sending it already?

**Comment by mattclay** [comment]
The original `v2_runner_on_ok` was sent in `_process_pending_results`. However, to send `v2_runner_on_ok` only on success it would need to be sent from `_load_included_file` which is called later and does not have access to the task result.

**Comment by sivel** [comment]
I am somewhat conflicted here. The `TaskResult` created using the return by `TaskExecutor` is basically a noop since nothing has really been done at that point.

We use that result to actually do the include later.

Due to that, I don't really see a way to defer that `on_ok`. I do agree that we need it though.

I suppose we could add the task result to `IncludedFile` so that we have it in `_load_included_file`, we would just have to loop each host in `included_file._hosts` inserting into that task result for each call to `v2_runner_on_ok`, similarly to what is done with `v2_runner_on_failed`

**Comment by bcoca** [comment]
sounds ugly ... but i dont see a good alternative

**Review by jimi-c — APPROVED** [review]

**Comment by mattclay** [comment]
Closing this, since I haven't found time to revise the solution.

**Pull request closed without merging**
