### PR TITLE
Add Docker inventory plugin

### PR DESCRIPTION
**Pull request by angstwad**
This adds more Docker to Ansible.  It also fixes the feedback/issues from mpdehaan that we discusses via the devel mailing list.

Thanks, guys.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Paul,

I recall there being a previous ticket about this but I can't find it -- can you link the number here so I can see any reply to comments?  I recall having a question about multiple host support that I was unsure about.

Thanks!!!

**Comment by mpdehaan** [comment]
nm ... I do see multiple hosts I believe, nice!

**Comment by angstwad** [comment]
Yes sir, multiple host support is there.

**Comment by angstwad** [comment]
There wasn't a ticket, it was an email on the devel list.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
