### PR TITLE
[2.9] Add anchor to each parameter row

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #66895 to stable-2.9.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/_static/ansible.css
docs/templates/plugin.rst.j2
hacking/build_library/build_ansible/command_plugins/plugin_formatter.py

### CODE REVIEW

**Comment by felixfontein** [comment]
Please don't merge before checking the devel docs (once they are regenerated, i.e. from tomorrow on) :)

**Comment by acozine** [comment]
@felixfontein thanks for adding links to the parameters and for the backport - it looks okay in devel. The top black border covers over the first line, but this is better than what we had, and we can improve it moving forward.

**Comment by felixfontein** [comment]
@acozine thanks! That the header bar covers the first line is a known problem (unfortunately), it also happens for other references.

I've been playing around with CSS a bit; at least for links to sections, the following helps:
```
section [id] {
    padding-top: 50px;
    margin-top: -50px;
}
```
(This probably has to be enclosed by a media query which only defines this when the header bar is actually shown.)

This doesn't help for `<tr id='...'>` though. But we could change HTML generation for the table to insert an element which is moved up by 50 pixels with `position: relative`. I might try that over the weekend.

**Comment by felixfontein** [comment]
I've created a PR for this: #67244

**Pull request merged**
