### PR TITLE
mysql_replication: add mutually_excl block, new maintainer, seealso, change doc formatting

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY

1. marks parameters as mutually exclusive
2. adds me as a new maintainer and co-author (implemented 4 new params, going to add 1 tomorrow, added return value, added CI tests (setup and specific) from scratch for MariaDB and MySQL. I'm going to maintain this module).
3. adds seealso
4. changes doc formatting

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/mysql/mysql_replication.py```

### CODE REVIEW

**Review by Akasurde — COMMENTED** [review]
LGTM, need one more person to take a look cc @samccann @acozine

**Comment by Andersson007** [comment]
@Akasurde , thank you for reviewing!

**Review by bmalynovytch — APPROVED** [review]
LGTM 👏
shipit

**Comment by Andersson007** [comment]
@bmalynovytch thank you for reviewing and approving!

**Pull request merged**
