### PR TITLE
[postgresql_ext.py] Add option to install extension into defined sc…

### PR DESCRIPTION
**Pull request by kumpa**
##### SUMMARY

Allows to install extensions into defined schema.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
postgresql_ext

##### ANSIBLE VERSION

```paste below
2.7.1
```

### CODE REVIEW

**Comment by andytom** [comment]
There is an existing PR to solve this issue (https://github.com/ansible/ansible/pull/47279), @kumpa and @pbaisla do you want to work together on this?

**Comment by pbaisla** [comment]
@andytom Both the PRs are nearly identical and get the job done. It would be good to have either of these merged.

**Comment by kumpa** [comment]
@andytom I agree with @pbaisla.

**Comment by andytom** [comment]
@kumpa since #47279 has been merged, can we close this PR or is there something I have missed?

**Comment by kumpa** [comment]
@andytom Yes, you can close this PR. I thought it requires some actions from me. Thanks for merging.

**Pull request closed without merging**
