### PR TITLE
New attribute "submodules" to select which sub-module to update.

### PR DESCRIPTION
**Pull request by eroldan**
Replaces "recursive" functionality.
Changes error handling when doing submodule operations

### CODE REVIEW

**Comment by mpdehaan** [comment]
This behavior should probably be tweaked because we don't like giving meaningful behavior to empty strings or contrasting None with "", which both have a "truthiness" in Python as False.

```
+            - Which sub-modules will be updated. Empty string skips all.
+              If this argument is not supplied all sub-modules will be
+              updated. 
```

Can we change this to "none" skips all submodules?

(Be sure to do a case insensitive match also)

Thanks!

**Comment by mpdehaan** [comment]
(Note that will have to be applied in 1.6 timeframe as the recursive module is new in 1.6, and otherwise can't be removed)

**Comment by eroldan** [comment]
Your recommendations were done. Thanks!

**Comment by leth** [comment]
FYI: the recursive flag is currently broken -- setting to to 'no' does not prevent all sending of "--recursive" flags to git

**Comment by eroldan** [comment]
Bummer. Ansible 1.6 is released making the 'recursive' parameter written in stone :( 
Maybe I can adapt the "submodule" parameter to coexist with recursive, but I'm not very interested right now.
As others stated, the "recursive" flag is broken in 1.6 release, this fix seems ok https://github.com/ansible/ansible/pull/7033/commits

**Comment by jimi-c** [comment]
@eroldan based on the above, I'm going to go ahead and close this. If you do have further ideas to improve the functionality of the git module please let us know. Thanks!

**Pull request closed without merging**
