### PR TITLE
Set export on Config to verbose

### PR DESCRIPTION
**Pull request by renatoalmeidaoliveira**
##### SUMMARY
In the configuration export session i think that using /export verbose is better than just /export, because with export only some configurations sections are going to be missed like BGP configuration

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
routeros_facts.py

##### ADDITIONAL INFORMATION
* extract of the output with /export verbose
``` 


# software id = 
#
#
#
/interface ethernet
set [ find default-name=ether1 ] advertise=\
    10M-half,10M-full,100M-half,100M-full,1000M-full arp=enabled arp-timeout=\
    auto auto-negotiation=yes cable-settings=default disable-running-check=\
    yes disabled=no full-duplex=yes loop-protect=default \
    loop-protect-disable-time=5m loop-protect-send-interval=5s mac-address=\
    50:00:00:02:00:00 mtu=1500 name=ether1 orig-mac-address=50:00:00:02:00:00 \
    rx-flow-control=off speed=1Gbps tx-flow-control=off
set [ find default-name=ether2 ] advertise=\
    10M-half,10M-full,100M-half,100M-full,1000M-full arp=enabled arp-timeout=\
    auto auto-negotiation=yes cable-settings=default disable-running-check=\
    yes disabled=no full-duplex=yes loop-protect=default \
    loop-protect-disable-time=5m loop-protect-send-interval=5s mac-address=\
    50:00:00:02:00:01 mtu=1500 name=ether2 orig-mac-address=50:00:00:02:00:01 \
    rx-flow-control=off speed=1Gbps tx-flow-control=off
set [ find default-name=ether3 ] advertise=\ 
.....
.....
```
* Extract of Output with only /export:
```
# software id = 
#
#
#
/interface wireless security-profiles
set [ find default=yes ] supplicant-identity=MikroTik
/ip dhcp-client
add dhcp-options=hostname,clientid disabled=no interface=ether1
<END>

```

### CODE REVIEW

**Comment by heuels** [comment]
Hi @renatoalmeidaoliveira! Thank you so much for the PR and sorry for the delay. 

You also need to rename [this fixture file](https://github.com/ansible/ansible/blob/devel/test/units/modules/network/routeros/fixtures/routeros_facts/export) from `export` to `export_verbose` for the checks to pass.

**Review by heuels — APPROVED** [review]
LGTM

**Comment by heuels** [comment]
bot_status

**Comment by Akasurde** [comment]
Hi @renatoalmeidaoliveira, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.network<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
