### PR TITLE
Update k8s.py

### PR DESCRIPTION
**Pull request by weshouman**
##### SUMMARY
Add example for multi document yaml file, refer to #65178 for a common-mistake

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by willthames** [comment]
@weshouman I recommend doing it slightly differently

https://github.com/willthames/ansible-role-kube-resource/blob/master/tasks/main.yml#L66-L68

If you loop over include, then the first failure will stop the playbook run - if you loop over the task then it will only fail after all the resources are tried.

We have had outages as a result of Services changing assuming that a Deployment had changed, but the Deployment update failed, and the Service update then pointed at labels that didn't yet exist

**Comment by fabianvf** [comment]
@willthames is that something we could change the behavior of with an action plugin?

**Comment by sivel** [comment]
If a template returns a generator, as in the case of `yaml.safe_load_all` it effectively becomes unusable. jinja2 returns string representations of the python objects (without jinja2 native enabled), which means we get something like `<generator object load_all at 0x104181c80>` which we cannot dereference.

Either, like all jinja2 filters that return generators, users need to be educated to utilize the `list` filter, or the `from_yaml_all` filter needs to be updated to return a list instead of a generator.

**Comment by fabianvf** [comment]
Yeah, I think it makes sense to add as an example here just so that people who attempt to use that filter don't get surprised

**Comment by weshouman** [comment]
@willthames, one may do that if the yml file will be targeted only to ansible.

However, it's a common scenario that people have yml files written for k8s and they just want ansible to make it present without having to split it manually into ansible tasks.

Or, the yml is written for ansible but they won't to allow it to be used directly with k8s.

**Comment by weshouman** [comment]
@sivel this is the exact string that gets saved in the ```self.params['resource_definitions']``` when ```list``` filter isn't used.

**Comment by willthames** [comment]
@weshouman - no, the approach I suggest works with any valid k8s yaml file - you could pass the same multi-section YAML file to the kube_resource role or to e.g. `kubectl apply`.

It's based on the same approach you're taking, but looping an include_task over the resources is safer than looping k8s over the resources.

**Comment by willthames** [comment]
@fabianvf possibly, I haven't given it much thought as it's solved in the kube_resource role :)

**Comment by fabianvf** [comment]
@willthames yeah I say shipit, even if you replaced the task with the import role the `from_yaml_all` filter would need to be used, and I'm not sure if we should be explaining the use of that role in the module docs (though perhaps we could link to it)

**Comment by geerlingguy** [comment]
@weshouman - The Kubernetes-related modules and plugins have been moved to a new `community.kubernetes` collection, where further development and module additions (like this one) will go. Would you be willing/able to create a new PR adding this module to that project?

Collection repo: https://github.com/ansible-collections/kubernetes

Also, I would agree with @fabianvf's latest note about shipping the change as is, just because it is sorely lacking in the current docs, and it might be nice to spend some time figuring out the best way to reliably support multi-document yaml templates long-term separately (which could avoid some of the risks mentioned by @willthames earlier in this thread).

**Comment by weshouman** [comment]
@geerlingguy , that sounds pretty interesting for me, I'll give that a try on the next weekends and see what I can do

**Comment by samccann** [comment]
Thanks @weshouman for your willingness to move this work over to the new location in collections. Closing this PR.

**Pull request closed without merging**
