### PR TITLE
Improve netapp_e_hostgroup and add unit tests.

### PR DESCRIPTION
**Pull request by ndswartz**
##### SUMMARY
netapp_e_hostgroup was refactored for maintainability and improved
documentation clarity.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

netapp_e_hostgroup
##### ADDITIONAL INFORMATION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/swartzn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/swartzn/ansible-dev/lib/ansible
  executable location = /home/swartzn/ansible-dev/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

### CODE REVIEW

**Review by thedoubl3j — APPROVED** [review]
lgtm, docs look good and tests added.

**Comment by thedoubl3j** [comment]
rebuild_merge

**Comment by thedoubl3j** [comment]
looks like ansibot is having some issues @ndswartz can you close then reopen this PR so that CI will be run again on it. I will merge once CI is done since we have a stale ci label on this one

**Comment by thedoubl3j** [comment]
@ndswartz disregard, looks like ansibot caught up

**Review by thedoubl3j — CHANGES_REQUESTED** [review]
fix sanity issues

**Comment by ndswartz** [comment]
@thedoubl3j Fix sanity issues

**Review by thedoubl3j — APPROVED** [review]
CI fixed, lgtm

**Pull request merged**
