### PR TITLE
integration tests for ec2_vpc_net

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
I'm porting this module to boto3 and adding a feature to expand existing VPCs in #33105. These tests should be reviewed/merged first to ensure backwards compatibility.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
test/integration/targets/ec2_vpc_net

##### ANSIBLE VERSION
```
2.5.0
```

### CODE REVIEW

**Review by willthames — CHANGES_REQUESTED** [review]
This looks great in general - can you just update the ec2-policy.json (or merge #33122 and then update compute-policy.json) to add the DHCP permissions?

**Comment by s-hertel** [comment]
@willthames Thanks for the review, I will update compute-policy.json!

**Comment by s-hertel** [comment]
@willthames Updated the test policy, do you mind updating your review? Not mergeable yet because I'm waiting for my PR for CI permissions/clean up to be approved.

**Review by willthames — APPROVED** [review]
Tests look really good and pass for me locally against us-east-2 after rerunning setup-iam.yml

**Review by ryansb — APPROVED** [review]

**Pull request merged**
