### PR TITLE
Update azure_rm_virtualmachine.py

### PR DESCRIPTION
**Pull request by isopy**
##### SUMMARY
A lot of Azure images are not cloud-init ready and need to be prepared manually before attempting to use the custom_data option of this module. Adding a line to the description to make others aware. If, like me, they are used to working with AWS AMIs that all seem to have cloud-init baked in, this could prevent some troubleshooting as to why their custom_data scripts aren't running in Azure.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
```
lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
``` 
##### ANSIBLE VERSION
```
ansible 2.6.3
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by yuwzho** [comment]
HI @isopy Thanks for your contribution, your documentation seems contain some syntax error, would you mind fixing this? Please refer this site: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#formatting-functions to refine your doc

**Comment by isopy** [comment]
@yuwzho my apologies. first time using this type of syntax and misread the usage of of L(). This latest commit should fix it.

**Comment by Fred-sun** [comment]
@isopy Thanks for the contribution, Could you help confirm that you have finished change this PR or not? if finish, I will push to review. Thanks!

**Comment by isopy** [comment]
@Fred-sun Confirming that I’m finished changing this PR.

**Comment by yuwzho** [comment]
shipit

**Review by yuwzho — APPROVED** [review]

**Review by zikalino — APPROVED** [review]

**Pull request merged**
