### PR TITLE
Use shorter when statement in playbooks_conditionals documentation.

### PR DESCRIPTION
**Pull request by ypid**
Don’t teach bad habits.

### CODE REVIEW

**Comment by bcoca** [comment]
the example is to show how to use parenthesis in conditionals, your change make the example not match the text

**Comment by ypid** [comment]
Updated. The section is about the `when` statement so I think this change ok.

**Comment by bcoca** [comment]
I think you missed the whole point, the purpose was to show how to use parenthesis to group conditionals. Closing this.

**Comment by ypid** [comment]
Fair enough.

**Pull request closed without merging**
