### PR TITLE
Cache for _do_template call.

### PR DESCRIPTION
**Pull request by Yannig**
This PR is a proposal to fix a part of the following issue https://github.com/ansible/ansible/issues/12997

May result in nice speed improvement (4-5 times faster) when used with big hash map.

Take it with a grain of salt has it may break things...

### CODE REVIEW

**Comment by bcoca** [comment]
judging from the failing test, the cached value is not always correct

**Comment by Yannig** [comment]
Indeed :)

**Comment by bcoca** [comment]
still, keeping it open for now, discussing with core team as this does show better performance even if incorrect.

**Comment by Yannig** [comment]
Well, it's seems better now :)

**Comment by bcoca** [comment]
worth testing as fix for #12239

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by Yannig** [comment]
@jimi-c nice :)

**Pull request merged**
