### PR TITLE
[stable-2.9] systemd - fix issue with capbpf and newer kernel (#72337)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Backport of #72337 for Ansible 2.9.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/systemd.py`

### CODE REVIEW

**Comment by ktdreyer** [comment]
I applied this change to `ansible-2.9.14-1.fc32`. I don't get the generic error any more, but I get a new error message instead: `Could not find the requested service krb5kdc: host`

**Comment by ktdreyer** [comment]
The problem is that `systemctl list-units` will only display *loaded* units. When I first install the `krb5-server` package, systemd does not load the `krb5kdc.service` unit yet. I cannot list it with `systemctl list-units  'krb5kdc.*'` (or `systemctl list-units --all 'krb5kdc.*'`) until it's "loaded".

Instead of `list-units`, I can use `list-unit-files`, and that works.

**Comment by samdoran** [comment]
Hmm, that's unfortunate. `list-unit-files` took quite a bit longer to execute which is why I went with `list-units`. I'll work on another fix.

**Comment by ktdreyer** [comment]
Weird, both `list-units` and `list-unit-files` returned almost instantly on my computer. What difference where you seeing?

**Comment by samdoran** [comment]
Anecdotally `list-unit-files` took a second or two to return while `list-units` was instant. I didn't do any measuring, though.

**Comment by ktdreyer** [comment]
Ok, I do see a long delay (3 seconds) when I run `list-unit-files` with no further arguments. However, the command returns almost instantly when I specify a single service, for example: `systemctl list-unit-files chronyd.service`

**Comment by samdoran** [comment]
```
/usr/bin/time -f "%E" systemctl list-unit-files --no-pager --all
...
480 unit files listed.
0:01.11
```

```
/usr/bin/time -f "%E" systemctl list-units --no-pager --all
...
394 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
0:00.02
```

**Comment by samdoran** [comment]
I think I was planning to list everything then investigate the output before I figure out I could have `systemd` do the filtering work. And by that time I had switched to `list-units`.

**Comment by ktdreyer** [comment]
LGTM, thanks.

**Comment by samdoran** [comment]
Thank you so much for helping out with this fix.

**Pull request merged**
