### PR TITLE
[2.8] Fix return value documentation (1/2)

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #63477 to stable-2.8.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
...

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by rrey — COMMENTED** [review]
LGTM as far as I am concerned !

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
@abadger this PR contains no module, it is only that ansibot is confused because some of the modules modified here were renamed for 2.9. Also, I removed the `tests/sanityignore.txt` part from the original commit and manualy added `tests/sanity/validate-modules/ignore.txt` entries in another commit, that made "converting" them a lot simpler.

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by acozine** [comment]
No net new modules or plugins here, just revisions to existing ones. I'm going to merge this over Ansibot's confusion.

**Pull request merged**
