### PR TITLE
(2.7 cherry-pick) Cherry pick 2 fixes for openshift inventory plugin

### PR DESCRIPTION
**Pull request by AlanCoding**
Manual cherry-pick from devel to 2.7

##### SUMMARY
Details in https://github.com/ansible/ansible/pull/49154

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/k8s.py

lib/ansible/module_utils/k8s/inventory.py

##### ADDITIONAL INFORMATION
_pending manual verification with ansible-inventory_

### CODE REVIEW

**Comment by AlanCoding** [comment]
@pilou- requesting review

**Comment by AlanCoding** [comment]
I hit another bug trying to test this:

```
Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.7.2.post0-py2.7.egg/EGG-INFO/scripts/ansible-inventory", line 118, in <module>
    exit_code = cli.run()
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.7.2.post0-py2.7.egg/ansible/cli/inventory.py", line 181, in run
    results = self.dump(results)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.7.2.post0-py2.7.egg/ansible/cli/inventory.py", line 199, in dump
    results = json.dumps(stuff, cls=AnsibleJSONEncoder, sort_keys=True, indent=4)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.7.2.post0-py2.7.egg/ansible/parsing/ajson.py", line 66, in default
    value = super(AnsibleJSONEncoder, self).default(o)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {u'openshift.io/scc': u'privileged'} is not JSON serializable
```

This bug appears to not exist in devel, but it does kind of prevent fully testing _this_ bug.

**Comment by AlanCoding** [comment]
I think this might be a bad idea, because it would conflict with backporting the other changes made in devel, and those appear to resolve that above error.

**Comment by AlanCoding** [comment]
this now works via my local testing.

Up to @pilou- whether we use this, or just close it and backport the commits that change to the newer file structure.

**Comment by AlanCoding** [comment]
oh, if we do this, maybe this needs a changelog entry

https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs

**Comment by maxamillion** [comment]
@AlanCoding changelog please, but otherwise 👍

**Comment by maxamillion** [comment]
@AlanCoding also, can you `git cherry-pick -x` for posterity?

**Comment by AlanCoding** [comment]
Keep in mind that the first cherry-pick commit here is edited to the point of being unrecognizable.

The files were moved entirely, so the changes were re-applied to a different file.

**Comment by fabianvf** [comment]
shipit

**Comment by maxamillion** [comment]
shipit

**Comment by abadger** [comment]
Merged for the 2.7.5 release.

**Pull request merged**
