### PR TITLE
Dry run (--check mode) prints discrete banner at the beginning and the end of the playbook execution.

### PR DESCRIPTION
**Pull request by basos9**
##### SUMMARY
see #48787

Dry run (--check mode) should print discrete banner at the beginning and more importantly at the end of the playbook execution, in order to clarify understanding of what was actually done.

When running long playbooks it might be good practice to first execute a dry run in order to have an idea of the actual changes that will be made. Also one could accompany this mode with --diff in order to see file changes and such, for modules that support this.

In the current implementation the output of a normal (wet) and dry run is the same. Thus, it can become very confusing what was the the actual mode of a playbook when scrolling back at the playbook output, or even worse when reading a log file, if the output is logged (via ansible configuration option log_path). In this case it is impossible to understand if the run was a dry or a wet one.

Thus it is proposed to prepend and append a banner (this one being more important since it is viewed next to the playbook summary) when a playbook is run in check mode (dry run). This should also be printed to the log file.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ansible

##### ADDITIONAL INFORMATION

```paste below
$ ansible-playbook -C -i hosts test/testinc.yml 

DRY RUN ****************************************************************************************************************************

PLAY [all] *************************************************************************************************************************

TASK [Something in the way] **********************************************************************************************************
ok: [localhost] => {
    "msg": "Inside include playbook"
}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0   


DRY RUN (no changes were made) *****************************************************************************************************
```

### CODE REVIEW

**Comment by samdoran** [comment]
This is a great idea. Since check mode affects individual tasks, there should be an indicator at the task level rather than a start/stop banner.

**Comment by basos9** [comment]
Regarding the task indicator, maybe it will bloat the output since it will be repeated on every task. 

In any case the `--check` parameter is passed to the entire playbook, hence the start stop banner. It is a concept that affects the whole playbook. 

Especially the stop banner I think is very convenient, since when coming later to read the playbook output, you can first read the bottom line informing you it was a dry run, and then the playbook summary just above.

I don't know in which cases the individual task's mark would be informative. But if it is to be added it could be like this

```

DRY RUN ****************************************************************************************************************************

PLAY [all] *************************************************************************************************************************

TASK [Something in the way] [CHECK MODE] **********************************************************************************************************
ok: [localhost] => {
    "msg": "Inside include playbook"
}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0   


DRY RUN (no changes were made) *****************************************************************************************************
```

**Comment by samdoran** [comment]
It may seem noisy, but it makes more sense to indicate at the task level. Check mode is actually a task level parameter, not a play level parameter, even though you pass it in at run time. You can set `check_mode:` on any task.

An advantage to indicating check mode at the task level is long running plays with many tasks will let you know during execution that individual tasks are not making changes.

**Comment by bcoca** [comment]
Consider this:
`ansible --check play.yml`

play.yml
```
- hosts: all
  check_mode: off
...
```
So now doing the banner as suggested will be misleading as the play will NOT run in check mode.

**Comment by basos9** [comment]
So I understand that the technical cases for check mode are
1. Playbook runtime parameter (playbook dry run)
2. Play config (play check mode)
3. Role config (role  check mode)
4. Task/Block config (task check mode)

What I have considered (and used) till now is a playbook that does make changes but provides a dry run mode. Which is selected by a runtime parameter from the administrator. 

In this schenario each individual task is responsible to implement correctly the dry run by using check mode appropriately. The banner just informs the administrator of the execution mode, but still, the playbook could have a bug and do make a destructive change by executing a task with side effects in dry run. Still this is a playbook issue to be fixed. When that is done the administrator can still trust the ending banner that the last run was dry.

For a counter example it could be a command that itself implements dry run, and we run the task with check_mode = no (so it makes changes), but execute the command with dry run argument (so finally it doesn't make changes):
```yaml
  name: synchronize files
  command: "rsync {{ rsync_dry }} source dest"
  vars:
    rsync_dry: "{{ ansible_check_mode | ternary('--dry-run','') }}"
  check_mode: no
``` 

I understand that check_mode is a task mode option, but for sure there is the concept of a playbook being run in check mode versus being run in normal mode.




Now it seems there is the case of a whole play being configured as at check mode. I can not think of a use case where this is dynamic. If this is static, then it is possibly a playbook that it's job is to collect information. And maybe a playbook dry run is not applicable in this kind of playbook.


Maybe we could add all the possible banners (I still insist on the playbook level banner), 
 - playbook
 - play
 - task

```

DRY RUN ****************************************************************************************************************************

PLAY [all] [CHECK MODE] *************************************************************************************************************************

TASK [Something in the way] [CHECK MODE] **********************************************************************************************************
ok: [localhost] => {
    "msg": "Inside include playbook"
}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0   


DRY RUN (no changes were made) *****************************************************************************************************

```

**Comment by basos9** [comment]
THIS was mistakenly closed (due to a wrong operation of me and a gitlab bug).
I opened #49432 that also adds markers to TASKs and PLAYs.


Please continue the discussion there.

**Pull request merged**
