### PR TITLE
Simplified p.poll handling

### LINKED ISSUE #5570: slow ssh and ssh_alt (needs info)
The ssh/ssh_alt transport has become painfully slow, anyone else have this problem? 

Probably with 8cef210 (ssh) and 5c965a7 (ssh_alt)

Some measures (single target host, lan connection, Debian 7.2, OpenSSH_6.0p1):
- devel(ea4bb9f…) ssh 4m27.902s, ssh_alt 3m30.481s
- devel(5c965a7…^) ssh_alt 0m14.641s
- devel(8cef210…) ssh 4m29.508s
- devel(8cef210…^) ssh 0m5.732s

### PR DESCRIPTION
**Pull request by lberruti**
Fixes #5570

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks, in queue for testing!

**Comment by jctanner** [comment]
Passes all of my tests. We'll wait for other people to try this out first though, since it affects critical parts of the code.

**Comment by jctanner** [comment]
@j2sol any chance you can run this through your tests that were failing with unclosed quotes?

**Comment by mpdehaan** [comment]
@jctanner let's go forward with applying this given lack of testing above, given the linked ticket

I'm not seeing any problems, but some people are, for whatever reason.

**Comment by mpdehaan** [comment]
ticket was #5768

**Comment by jctanner** [comment]
@lberruti thank you!

**Pull request merged**
