### PR TITLE
Add check mode for ansible-galaxy collection install

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY

This doesn't fully cover https://github.com/ansible/ansible/issues/75632, but at least allows users to check what will be installed/upgraded beforehand.

##### ISSUE TYPE

- Feature Pull Request

### CODE REVIEW

**Comment by gotmax23** [comment]
I like the idea, but I'm not sure that overloading the phrase `check mode` is the best idea. Should the argument be named something else?

**Comment by s-hertel** [comment]
Feel free to suggest alternatives. I considered `--dry-run` since ansible-galaxy tries to be similar to pip, but thought it might be easier for people to find the similar name.

**Comment by s-hertel** [comment]
Really needs some direction. The issue is not very actionable, it's not clear what exactly is needed.

**Pull request closed without merging**
