### PR TITLE
ini_file: add support for lists of options/values

### PR DESCRIPTION
**Pull request by jpmens**
This patch adds support for setting/removing a bunch of options/values from an .INI file. A example play would be:

``` yaml
  - action: ini_file
                dest=/tmp/d.ini
                section='demosec'
                option=command,directory,user
                value="ls -l","/etc/someplace","JPM"
                state=present
```

which, with one invocation (instead of three!) creates the following INI file

``` ini

[demosec]
command = ls -l
directory = /etc/someplace
user = JPM
```

### CODE REVIEW

**Comment by jpmens** [comment]
I'll add a note to docs as soon as jumbo-doc-patch is applied (don't want to break that, now do I :)

**Comment by bcoca** [comment]
is there a reason that it needs to be implemented in module and not just use with_items? ie:

```
- action: ini_file
            dest=/tmp/d.ini
            section='demosec'
            option=item.option
            value=item.value
            state=present
   with_items:
        - option: command
           value: "ls -l"
        - option: direcotry
           value: "/etc/someplace"
        - option: user
           value: "JPM"
```

**Comment by jpmens** [comment]
The reason being it didn't occur to me?

OTOH, I get this

```
TASK: [ini_file dest=/tmp/d2.ini section='demosec' option={{item.section}} value={{item.value}} state=present] ***
failed: [localhost] => (item={'section': 'command', 'value': 'ls -l'}) => {"failed": true, "item": {"section": "command", "value": "ls -l"}}
msg: this module requires key=value arguments (['dest=/tmp/d2.ini', 'section=demosec', 'option=command', 'value=ls', '-l', 'state=present'])
changed: [localhost] => (item={'section': 'direcotry', 'value': '/etc/someplace'})
changed: [localhost] => (item={'section': 'user', 'value': 'JPM'})

FATAL: all hosts have already failed -- aborting
```

with a partially correct output file

``` ini

[demosec]
direcotry = /etc/someplace
user = JPM
```

The problem is the space in `ls -l`

**Comment by jpmens** [comment]
Sorry for the noise, @bcoca -- it's a quoting thing. This does it:

``` yaml

  - action: ini_file
                dest=/tmp/d2.ini
                section='demosec'
                option="{{ item.section }}"
                value="{{ item.value }}"
                state=present
    with_items:
            - section: command
              value: "ls -l"
            - section: direcotry
              value: "/etc/someplace"
            - section: user
              value: "JPM"
```

**Comment by jpmens** [comment]
Nevertheless, implemented in-module saves a few SSH and read/write round trips.

**Comment by bcoca** [comment]
he, i just pushed commit so its easier for modules to use with_items as a
list (single invocation like apt and yum), that has me now assuming that
all modules of course immediately support this (I am updating a few modules
to do so).

On Sat, Jun 15, 2013 at 4:53 PM, JP Mens notifications@github.com wrote:

> Nevertheless, implemented in-module saves a few SSH and read/write round
> trips.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3226#issuecomment-19503244
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
This does save round trips, but the syntax looks a bit odd to me (parallel arrays, etc).

Thinking about it...

**Comment by bcoca** [comment]
If you accept my commit, we can refactor this to use with items as a list.
(shamelessly upvotes his own patch)

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
I believe I did accept your commit, so I think we need to rework this one, no?  Or not?

**Comment by jpmens** [comment]
@bcoca can you give me a hint on what I'm to do? I'll gladly do it then.

**Comment by bcoca** [comment]
just add in a comment # WITH_ITEMS_WANTS_LIST in the module, then expect
your input params to be a list, the yum, apt and pkgng modules do this
already (each a bit diff).

On Wed, Jun 19, 2013 at 1:23 AM, JP Mens notifications@github.com wrote:

> @bcoca https://github.com/bcoca can you give me a hint on what I'm to
> do? I'll gladly do it then.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3226#issuecomment-19663709
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
I went ahead and merged this, the previous patch from @bcoca does not work quite yet, so we can just add it to the list of hard coded modules that tolerate with_items magic in runner/**init**.py if we want, or we can wait for that patch to be ironed out.

Thanks!

**Pull request merged**
