### PR TITLE
now correctly detects hard links

### PR DESCRIPTION
**Pull request by bcoca**
simplified check_mode
simplified other file attribute handling in link mode
made conditionals clearer

Signed-off-by: Brian Coca <briancoca+dev@gmail.com>

### CODE REVIEW

**Comment by mpdehaan** [comment]
So when filing a ticket like this it is vital you show the current and expected behavior.

Also the removal of:

```
  # set modes owners and context as needed
 -
-        file_args = module.load_file_common_arguments(module.params)
-        changed   = module.set_context_if_different(path, file_args['secontext'], changed)
-        changed   = module.set_owner_if_different(path, file_args['owner'], changed)
-        changed   = module.set_group_if_different(path, file_args['group'], changed)
-        changed   = module.set_mode_if_different(path, file_args['mode'], changed)
```

Was probably there to change the properties of the link.   Replacing it with set_file_attributes_if_different (etc) seems to imply the function itself should check if the file was a link to avoid setting properties that did not make sense.

Can you let me know how this was tested?  (SELinux, etc?)

Thanks!

**Comment by bcoca** [comment]
sorry for the omission, here it is:

Current functionality is that when the target is a hard link, it is
detected as a a 'file' and might incorrectly fail or change depending on
'force'.
The update will correctly identify it as a hard link and then check if it
actually links to the same inode as the source, successfully identifying if
it is a change or not. Other functionality should remain unchanged but the
path should be much clearer and simpler to follow.

The file_args line was redundant, already called before the if/elsif chain.
I checked the single if_different function and it has the same 4 functions
called.
I believe these were left out from a previous refactoring, this just makes
the link path closer to the rest.

I nostested and did separate playbook tests on link/hard, file and
directory, no selinux as I have yet to setup a host with it but I hope I
successfully avoided touching any of the existing functionality.

As this is the file module, I expect healthy paranoia, caution and distrust
against this patch.

There is still an issue with exists/lexists/stat returning none (absent)
when we lack permissions, but not sure on how to capture that before
actually attempting to modify the target file where we get an exception
(which will correctly show permissions issue).

**Comment by bcoca** [comment]
I forgot to include the issue that prompted this whole thing #3830

**Comment by jimi-c** [comment]
@bcoca the os library has the os.access() function, which could be used to check the permissions beforehand:

http://docs.python.org/2/library/os.html#files-and-directories

Or was there some deeper issue?

**Comment by bcoca** [comment]
possibly, just need to check on how the system call translates to see if it
will have the same issues as os.stat.

Been busy lately and haven't had the time, if you can confirm, it would be
a good test to avoid a lot of issues.

**Comment by bcoca** [comment]
I  checked, os.access has same issues as lexists/exists and stat, it is slightly better in that it can give indirect information in some cases but since in the end we'll just get a no access exception I think we are ok as is (we do capture and report the error).

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
