### PR TITLE
Ec2 facts module

### PR DESCRIPTION
**Pull request by silviud**
Gathers data from the ec2 metadata servers.

To run `ansible -m ec2_facts` you will need to have a running instance into ec2.

-silviu

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hardcoded IP addresses look kind of problematic to me.   Can we use a hostname there instead?

Also since the parameters are really URLs, perhaps we should rename them to say _url instead of _server?

Also, for those of us not using AWS can you dump out what kinds of facts you are getting when you run this?

Thanks!

**Comment by dhozac** [comment]
Are these not things that the ec2 inventory script provides already?

**Comment by dhozac** [comment]
As for the hardcoded IP address, it's the well-known internal management IP address for EC2 (and some similar things), and the suggested way of getting at this data, so I think that is fine.

**Comment by mpdehaan** [comment]
We can't assume someone is using the inventory script.

**Comment by silviud** [comment]
Hello,

How  are named the variables or any possible arguments I'm open to any
suggestions - url looks fine. (I'm not aware if there are
already same naming conventions but will be cool to have).
The ec2 inventory script provides similar data (not sure which is a subset
of the other) but into a different way.
The ec2_facts will connect from 'inside' the instance to the metadata
server - doesn't need any sort of API keys
to access this info as long as it runs from within a running instance.
The hardcoded ip is well known and all related tools (ohai for example uses
- for sure facter) use it.

Why I think is a good idea to have from a running instance these facts
available is because you can  have for example
hard coded a script that will fire up ansible-pull - inside the playbook(s)
you can take decisions based on security groups or a vpc. With this model
you don't need to update the bootstrap script - every time you hit a 'catch
all' playbook and execution is based on the ec2 facts. With a big number of
instances (ami) to maintain this becomes very easy to manage.

The module as is is functional but for sure can be improved.

-silviu

ps: In regards to the ec2 inventory script is any reason why boto is not
used to call the aws api ?

2013/1/21 Michael DeHaan notifications@github.com

**Comment by mpdehaan** [comment]
Ok, I'm fine with everything as you have it then, so I think we can merge
this.

The ec2 inventory script does actually use boto:
https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.py

The creation module uses eucatools.

**Pull request closed without merging**
