### PR TITLE
added basic slackpkg support

### PR DESCRIPTION
**Pull request by KimNorgaard**
See https://github.com/ansible/ansible/issues/3437

### CODE REVIEW

**Comment by mpdehaan** [comment]
We'll take a look at this later, though note that the 'version_added' field should say 1.6, 1.0 released a while back.

Thanks!

**Comment by KimNorgaard** [comment]
No rush. There are probably not that many slackware users out there, anyway :)

The online packaging system kind of sucks for automation as it doesn't provide usable exit codes, so one has to do silly things to work around that.

**Comment by admiralboom** [comment]
Would love to see this reviewed. Just went to see if one was already created.  Glad to see the slackpkg module has been started.

**Comment by drinchev** [comment]
I'm a slack user, so :+1:

**Comment by r1w1s1** [comment]
+1

**Comment by amenonsen** [comment]
@KimNorgaard could you please submit this PR to the `ansible-module-extras` repository? This PR (against core) should be closed.

**Comment by KimNorgaard** [comment]
Moved to https://github.com/ansible/ansible-modules-extras/pull/772

**Pull request closed without merging**
