### PR TITLE
More defaulting for EC2 inventory plugin.

### PR DESCRIPTION
**Pull request by solidsnack**
This branch adds a few defaulting rules for the EC2 inventory plugin:
- If there is no conf file, the defaults from the example `ec2.ini` are used.
- If the `regions` setting is unset, then the environment variables `AWS_REGION` and `AWS_DEFAULT_REGION` are tried (in that order), otherwise, `all` is used.

Please let me know if you'd like me to change anything and resubmit. It's been awhile since I've written much Python and I'm still learning my way around the Ansible code base.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can this:

```
+            conf = '\n'.join([ s.strip() for s in '''
+                [ec2]
+                destination_variable = public_dns_name
+                vpc_destination_variable = ip_address
+                cache_path = /tmp
+                cache_max_age = 300
+            '''.splitlines() ])
```

Be cleaned up any?  (Perhaps a docstring assigned to a variable?)

Thanks!

**Comment by solidsnack** [comment]
The config parser doesn't accept leading spaces. We could go with a left flush docstring:

```
            conf = '''
[ec2]
destination_variable = public_dns_name
vpc_destination_variable = ip_address
cache_path = /tmp
cache_max_age = 300
            '''
```

or move the line mangling elsewhere:

```
            conf = '''
                [ec2]
                destination_variable = public_dns_name
                vpc_destination_variable = ip_address
                cache_path = /tmp
                cache_max_age = 300
            '''
            stripped = '\n'.join([ s.strip() for s in conf.splitlines() ])
            config.readfp(io.BytesIO(stripped))   
```

Please let me know which you prefer and I will reformat the patch.

**Comment by mpdehaan** [comment]
I would make it global and move it to the top of the file unindented

I suspect then the strip stuff would also not be needed.

also the io.BytesIO stuff is 2.6 only so that also needs to be fixed, not sure why you can't just pass the string in?

I actually think it's ok if the config file is required.

**Comment by solidsnack** [comment]
To follow up on your comments, here is a new patch: https://github.com/solidsnack/ansible/commit/9e71a60b3fcc3acb2947fc87bcd04055adc285a3

> I would make it global and move it to the top of the file unindented
> 
> I suspect then the strip stuff would also not be needed.

That does work, yes.

> also the io.BytesIO stuff is 2.6 only so that also needs to be fixed, not sure why you can't just pass the string in?

Because `config.readfp` requires something which acts like a file pointer. I've switched to `StringIO`.

> I actually think it's ok if the config file is required.

It's not the end of the world but it doesn't really help anyone. If you change your mind I will be happy to open a new pull request with the amended patch.

**Pull request closed without merging**
