### PR TITLE
modify pause documentation to suggest using wait_for for silent pause

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Supersedes #78575

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Review by samccann — APPROVED** [review]

**Comment by mattclay** [comment]
Closing and re-opening to attempt to get CI running.

**Comment by mattclay** [comment]
@s-hertel This PR needs to be rebased to clear the out-of-date CI failures.

**Pull request closed without merging**
