### PR TITLE
Reduce number of iterations through PlayIterator

### PR DESCRIPTION
**Pull request by mkrizek**
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`lib/ansible/executor/play_iterator.py`
`lib/ansible/plugins/strategy/__init__.py`
`lib/ansible/plugins/strategy/free.py`
`lib/ansible/plugins/strategy/linear.py`

### CODE REVIEW

**Comment by Shrews** [comment]
Technically, this seems ok to me. I would like this change much better if we stopped accessing the "private" `_host_state` attribute outside of `PlayIterator`. I realize that `StrategyBase` already does it, but extending that into the free strategy code is what really makes me uncomfortable, and would set a bad precedent. It would be better, IMO, if this code and the `StrategyBase` code used some new methods to set avoid using the private attribute directly. Something along the lines of:

 - `set_state_for_host(hostname)` in free strategy and StrategyBase
 - `set_fail_state_for_host(hostname)` in StrategyBase
 - `set_run_state_for_host(hostname)` in StrategyBase

We could then easily check that proper types are being supplied (e.g., `HostState`).

**Comment by mkrizek** [comment]
> Technically, this seems ok to me. I would like this change much better if we stopped accessing the "private" `_host_state` attribute outside of `PlayIterator`. I realize that `StrategyBase` already does it, but extending that into the free strategy code is what really makes me uncomfortable, and would set a bad precedent. It would be better, IMO, if this code and the `StrategyBase` code used some new methods to set avoid using the private attribute directly. Something along the lines of:
> 
> * `set_state_for_host(hostname, state)` in free strategy and StrategyBase
> * `set_fail_state_for_host(hostname, state)` in StrategyBase
> * `set_run_state_for_host(hostname, state)` in StrategyBase
> 
> We could then easily check that proper types are being supplied (e.g., `HostState`).

I agree. In fact I was going to do that initially but in the end decided to go with the minimal fix - mostly because we use various private attributes where we should not throughout the codebase that I just continued to do so here too which is I guess what brought us to this state :-)

I was also thinking of splitting `get_next_task_for_host` into `get_next_task_for_host` and `set_state_for_host`. So `get_next_task_for_host` would always `peek`. The reason being that currently `get_next_task_for_host` is misleading as it also sets the state. But that change would be backwards incompatible so I didn't do it.

I'll create the new methods in a separate PR and once it is merged, I'll change this PR to use the new methods.

**Review by s-hertel — APPROVED** [review]
LGTM, straightforward fix. No need to call `get_next_task_for_host` when it has already been done.

**Comment by mkrizek** [comment]
@s-hertel thanks for the review!

**Comment by mkrizek** [comment]
rebuild_merge

**Pull request merged**
