### PR TITLE
[2.9] pulp_repo: renamed module tls client auth params to avoid overlaping with fetch_url

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adjusted backport of #59522 to stable-2.9.

This backport adds two new options, `feed_client_cert` and `feed_client_key`, to the module. This is fixing a problem introduced in #54315 (included in 2.8.0). There, in an effort to standardize TLS connection properties, `importer_ssl_client_cert` and `importer_ssl_client_key` were renamed to `client_cert` resp. `client_key`. The module uses `fetch_url()` to talk to an API, and thus if the user wants to specify a client certificate for a repository, the client certificate will *also* be used to communicate with the pulp.io API. Since the pulp.io does not support that, talking to the API will fail. This effectively destroyed the options.

PR #59522 fixes this by re-adding the old options (with new names, which are the names used by pulp.io now). For now, the `client_cert` and `client_key` options are kept, so that in case pulp.io in the future allows client certs for the API itself, it is still possible to use them. Until Ansible 2.14, their value will be used as a default for the new options (and a deprecation warning will be issued) if these are not specified.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
pulp_repo

### CODE REVIEW

**Comment by coreaut** [comment]
> ##### SUMMARY
> 
> Adjusted backport of #59522 to stable-2.9.
> 
> This backport adds two new options, `feed_client_cert` and `feed_client_key`, to the module. This is fixing a problem introduced in #54315 (included in 2.8.0). There, in an effort to standardize TLS connection properties, `importer_ssl_client_cert` and `importer_ssl_client_key` were renamed to `client_cert` resp. `client_key`. The module uses `fetch_url()` to talk to an API, and thus if the user wants to specify a client certificate for a repository, the client certificate will _also_ be used to communicate with the pulp.io API. Since the pulp.io does not support that, talking to the API will fail. This effectively destroyed the options.
> 
> PR #59522 fixes this by re-adding the old options (with new names, which are the names used by pulp.io now). For now, the `client_cert` and `client_key` options are kept, so that in case pulp.io in the future allows client certs for the API itself, it is still possible to use them. Until Ansible 2.14, their value will be used as a default for the new options (and a deprecation warning will be issued) if these are not specified.
> ##### ISSUE TYPE
> 
>     * Bugfix Pull Request
> 
> 
> ##### COMPONENT NAME
> 
> pulp_repo

You're talking about "pulp.io" which maybe is misleading because there is a domain like that which has nothing to do with the pulp project.
Pulp also is no cloud service, you install and manage your own server with the repos you want to distribute in your local network.

**Comment by felixfontein** [comment]
> You're talking about "pulp.io" which maybe is misleading because there is a domain like that which has nothing to do with the pulp project.
> Pulp also is no cloud service, you install and manage your own server with the repos you want to distribute in your local network.

The changelog and the deprecation message are also written like this is the case. I don't know Pulp, so I relied on them.

**Comment by coreaut** [comment]
I didn't know that this domain existed before, sorry.

**Comment by felixfontein** [comment]
I will add a backport of #65129 to this PR once that is merged.

**Review by coreaut — APPROVED** [review]
thanks shipit

**Comment by felixfontein** [comment]
@coreaut thanks again for fixing this bug; the PR is now merged for Ansible 2.9.2. I'll next create a PR to adjust the `version_added`s in `devel` accordingly; I'll ping you there.

**Pull request merged**
