### PR TITLE
VMware: return info about SCSI controller in vmware_guest_disk_facts

### PR DESCRIPTION
**Pull request by spidermila**
vmware_guest_disk_facts module added bus number of the SCSI controller to the output

##### SUMMARY

I need the vmware_guest_disk_facts module to show not only the unit_number of the disk but also the controller's bus number. This is the usual information you get in vmware management tools and it allows better identification of the disk inside of the guest OS. So I have added this to the module.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

vmware_guest_disk_facts
##### ADDITIONAL INFORMATION

See the Summary section.

```paste below
I don't have a verbatim command output. I have tested the modified module in my test environment.
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@spidermila Thanks for the PR. Could you please following CI errors = 

```
00:58 ERROR: Found 2 pep8 issue(s) which need to be resolved:
00:58 ERROR: lib/ansible/modules/cloud/vmware/vmware_guest_disk_facts.py:169:1: W293 blank line contains whitespace (100%)
00:58 ERROR: lib/ansible/modules/cloud/vmware/vmware_guest_disk_facts.py:179:1: W293 blank line contains whitespace (100%)
```

**Comment by spidermila** [comment]
I have cleaned too much. The fbabe72 commit should be better

**Comment by spidermila** [comment]
At what stage should I add the changelog fragment yaml?

**Comment by Akasurde** [comment]
> At what stage should I add the changelog fragment yaml? @Akasurde

Changelog fragment is optional and you can add it in this PR itself.

**Review by jillr — APPROVED** [review]
This works for me on esxi6.7, thanks for the patch.

**Review by Akasurde — APPROVED** [review]

**Comment by Akasurde** [comment]
@spidermila Thanks for the contribution.

**Comment by Akasurde** [comment]
@jillr Thanks for the review and testing this PR.

**Pull request merged**
