### PR TITLE
template overrides with cleansing

### PR DESCRIPTION
**Pull request by bcoca**
This should allow overriding template interpolation/execution with data sanitation based on the overriden values

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!

(bumping this up in priority since some people may be relying on this, like @bcoca, and @bcoca is also awesome)

**Comment by dave-re** [comment]
I will use to this feature. merge please!

**Comment by sairez** [comment]
+1 for this merge please!

**Comment by michalgasek** [comment]
I rely on this as well, have never used {{ }} in templates so an upgrade from 1.6.5 to 1.7.1 requires going through all templates and changing them. quite annoying although I can live with it in the name of security.

Fixing it would be very welcome though.

**Comment by abadger** [comment]
@bcoca I noticed that in addition to allowing us to change the start and end of block tokens again this PR also removes the whitelist of allowable overrides.  Was that intentional?

**Comment by bcoca** [comment]
it was, as this PR is meant to allow ALL overridable parameters, the
whitelist becomes unnecessary.

I still need to reformat and resubmit as there have been further changes to
the affected code.
​

**Comment by brendanhay** [comment]
It'd be great to get this merged as it affects our templates which interact with other smarty based templating systems and requires us to stay on `1.6.5`.

:+1:

**Comment by bcoca** [comment]
can't merge right now, I need to redo again as target files have changed,
will probably have time this weekend.​

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by bcoca** [comment]
not a module related PR, but still needs to be re-factored again for a merge

**Comment by brendanhay** [comment]
Would be geat to get an approximate ETA on this. If it's not on the visible backlog, please make it clear so we can follow through with alternatives or potentially invest in offering a PR.

**Comment by bcoca** [comment]
@brendanhay when I have time, my day job sometimes gets in the way, I hope to dedicate sometime tomorrow but don't know if I'll be able to finish it

**Comment by brendanhay** [comment]
I apologize if that came off as an expectation. I'm simply trying to approach if I should invest time in solving this internally or wait. I appreciate your time!

**Pull request closed without merging**
