### PR TITLE
Replacing old "with_items:" by "loop:"

### PR DESCRIPTION
**Pull request by ruzickap**
Replacing old "with_items:" by "loop:"

+label: docsite_pr

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by yuwzho** [comment]
shipit

**Review by yuwzho — APPROVED** [review]

**Comment by Fred-sun** [comment]
@yuwzho  @yungezz  @zikalino  This PR has been review and approved, Who can push this PR forward step?--->merge

**Comment by webknjaz** [comment]
@Fred-sun several maintainers should ship it with a comment and it'll get merged by bot

**Comment by webknjaz** [comment]
@ruzickap please leave only relevant issue type from template, otherwise it confuses bot.

**Review by samdoran — APPROVED** [review]

**Comment by samdoran** [comment]
shipit

**Pull request merged**
