### PR TITLE
Clean up import statements for nxos_rollback

### LINKED ISSUE #23531: Ansible 2.3 nxos_rollback ShellError
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

nxos_rollback

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/user/sdi-nw-fabric/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

[defaults]
retry_files_save_path = ~/retry-files
record_host_keys = False
host_key_checking = False
##### OS / ENVIRONMENT

Centos 7
##### SUMMARY

nsox_rollback throws an error

##### STEPS TO REPRODUCE

```yaml
---
- name: Get backup
  set_fact: BKUPFILE="{{lookup('pipe', 'cat ~/.BKUPFILE')}}"

- name: DEBUG
  debug: msg="{{BKUPFILE}}"

- name: Set Checkpoint
  nxos_rollback:
    checkpoint_file: "{{BKUPFILE}}"
    provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Successful run

##### ACTUAL RESULTS

```
Vault password:

PLAY [DRF_vxlan] ***********************************************************************************************************************************************************************************

TASK [checkpoint : Get backup] *********************************************************************************************************************************************************************
ok: [s-leaf]

TASK [checkpoint : DEBUG] **************************************************************************************************************************************************************************
ok: [s-leaf] => {
    "changed": false,
    "msg": "user.2017.04.12.13.57.03"
}

TASK [checkpoint : Set Checkpoint] *****************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'ShellError' is not defined
fatal: [s-leaf]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_aK1Nz9/ansible_module_nxos_rollback.py\", line 186, in <module>\n    main()\n  File \"/tmp/ansible_aK1Nz9/ansible_module_nxos_rollback.py\", line 178, in main\n    except ShellError:\nNameError: global name 'ShellError' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/user/retry-files/site.retry

PLAY RECAP *****************************************************************************************************************************************************************************************
s-leaf : ok=2    changed=0    unreachable=0    failed=1

```

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

nxos_rollback import statements are out of date. This removes unnecessary imports and adds missing ones

Fixes #23531

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

nxos_rollback

##### ANSIBLE VERSION

```
2.3.0
```

### CODE REVIEW

**Comment by dgjustice** [comment]
```
TASK [checkpoint : Set Checkpoint] *****************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'AnsibleModule' object has no attribute 'cli'
fatal: [s-leaf]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mRQrL8/ansible_module_nxos_rollback.py\", line 183, in <module>\n    main()\n  File \"/tmp/ansible_mRQrL8/ansible_module_nxos_rollback.py\", line 168, in main\n    checkpoint(checkpoint_file, module)\n  File \"/tmp/ansible_mRQrL8/ansible_module_nxos_rollback.py\", line 127, in checkpoint\n    prepare_show_command(commands, module)\n  File \"/tmp/ansible_mRQrL8/ansible_module_nxos_rollback.py\", line 120, in prepare_show_command\n    execute_commands(command, module)\n  File \"/tmp/ansible_mRQrL8/ansible_module_nxos_rollback.py\", line 109, in execute_commands\n    module.cli.add_commands(cmds, output=command_type)\nAttributeError: 'AnsibleModule' object has no attribute 'cli'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/user/retry-files/site.retry
```

**Comment by dgjustice** [comment]
I only copied over that module.  Did you change any other files, and do I need to pull a copy of your branch instead?

**Comment by Qalthos** [comment]
Well, we got past the ShellError business and got to the part that was really broken. nxos_rollback has a lot of pre-2.3 (and pre-2.2) logic in there that is now unnecessary. I believe I have cleared up the remaining issues with the module.

**Review by privateip — APPROVED** [review]

**Comment by privateip** [comment]
ship_it

**Pull request merged**
