### PR TITLE
Add NSG ruler protocol --Icmp

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Azure securitygroups now support creating rules for the ICMP protocol when creating rules via the Azure portal, So add the ICMP protocol in Ansble.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure_rm_securitygroup
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@haiyuazhang @gavinfish

**Comment by Fred-sun** [comment]
ping to reivew!

**Review by gavinfish — APPROVED** [review]
shipit

**Comment by Fred-sun** [comment]
This PR has been migrated to [#68](https://github.com/ansible-collections/azure/pull/68).

**Pull request closed without merging**
