### PR TITLE
[stable-2.9] Pull images from Quay to avoid Docker Hub limits

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

CI tests are failing in certain situations due to the new Docker Hub limits on anonymous pulls. Switch to pulling an equivalent image from Quay.io.

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

`test/integration/targets/docker_container/tasks/tests/comparisons.yml`
`test/integration/targets/docker_container/tasks/tests/image-ids.yml`
`test/integration/targets/docker_container/tasks/tests/mounts-volumes.yml`
`test/integration/targets/docker_container/tasks/tests/network.yml`
`test/integration/targets/docker_container/tasks/tests/options.yml`
`test/integration/targets/docker_container/tasks/tests/ports.yml`
`test/integration/targets/docker_container/tasks/tests/regression-45700-dont-parse-on-absent.yml`
`test/integration/targets/docker_container/tasks/tests/start-stop.yml`
`test/integration/targets/docker_container_info/tasks/main.yml`
`test/integration/targets/docker_host_info/tasks/test_host_info.yml`
`test/integration/targets/docker_network/tasks/tests/basic.yml`
`test/integration/targets/docker_prune/tasks/main.yml`
`test/integration/targets/docker_stack/files/stack_compose_base.yml`
`test/integration/targets/docker_stack/vars/main.yml`
`test/integration/targets/docker_swarm_service/tasks/main.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/configs.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/logging.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/misc.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/mounts.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/networks.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/options.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/placement.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/resources.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/restart_config.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/rollback_config.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/secrets.yml`
`test/integration/targets/docker_swarm_service/tasks/tests/update_config.yml`
`test/integration/targets/docker_swarm_service/vars/main.yml`
`test/integration/targets/docker_swarm_service_info/tasks/test_docker_swarm_service_info.yml`
`test/integration/targets/inventory_docker_machine/playbooks/test_inventory_1.yml`
test/integration/targets/k8s/tasks/waiter.yml

### CODE REVIEW

**Comment by samdoran** [comment]
@felixfontein I'm not sure if you ran into this issue with the collection testing.

**Comment by felixfontein** [comment]
@samdoran thanks for the ping! I also noticed that (see ansible-collections/community.docker#35) and wanted to clean it up over the weekend. I will probably use at least some of the same images you are using, thanks a lot already :)

**Comment by samdoran** [comment]
We are planning to create a new repo on Quay with images we use for testing.

**Comment by samdoran** [comment]
@felixfontein I ended up creating a repo on Quay that has tags for various images. https://quay.io/repository/ansible/docker-test-containers?tab=tags

It required reworking some things, but this should be the most stable thing going forward since we control it and it shouldn't change unless we make changes to it.

**Comment by felixfontein** [comment]
@samdoran cool, thanks! I'll start using them soon.

BTW, I adjusted the community.docker tests so that it is pretty simple to replace most images: https://github.com/ansible-collections/community.docker/blob/main/tests/integration/targets/setup_docker/vars/main.yml (The only images not included there are ones used in connection and inventory tests.)

**Comment by samdoran** [comment]
Oh, that's very nice. Good use of vars. 😁

**Pull request merged**
