### PR TITLE
IGNORE - Created by mistake!  ios_config module applies changes whether needed or not

### PR DESCRIPTION
**Pull request by ctjon**
##### SUMMARY

ios_config module applies changes whether needed or not

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### ADDITIONAL INFORMATION
The ios_config module exhibits bad behavior that I’m seeing when using the parents parameter.   It seems to be executing a change regardless of whether or not the config is already there and/or is identical.   
 

  - name: IOS | Apply Standardized Fabricpath Configuration

    ios_config:

      provider: "{{ provider }}"

      lines:

        - spf-interval 50 50 50

        - lsp-gen-interval 50 50 50

        - fabricpath timers linkup-delay 30

      parents: fabricpath domain default

```

```

### CODE REVIEW

**Comment by s-hertel** [comment]
@ctjon Hi, I'm not too sure whether this is intended to be submitted code or a bug report. Do you need help rebasing to get rid of the superfluous commits? Feel free to ping me on [IRC](http://webchat.freenode.net/?channels=ansible) (username shertel) or we could figure things out here.

**Comment by ctjon** [comment]
Was intended to be a bug report, opened a pull request by mistake, sorry for the hassle


—————

Chris Tjon - RHCDS
Solutions Architect - OpenStack
RedHat Inc.
602-614-6118
ctjon@redhat.com

**Comment by s-hertel** [comment]
That's no problem. Can you copy your issue into https://github.com/ansible/ansible/issues/new and we can close this one?

**Comment by ctjon** [comment]
Yes , gathering some more info first but will do asap 


—————

Chris Tjon - RHCDS
Solutions Architect - OpenStack
RedHat Inc.
602-614-6118
ctjon@redhat.com

**Pull request closed without merging**
