### PR TITLE
Expand Windows test matrix on Shippable.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Expand Windows test matrix on Shippable.

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

Shippable

##### ANSIBLE VERSION

```
ansible 2.5.0 (windows-test-matrix fa8a3cbdd2) last updated 2017/09/15 09:43:31 (GMT -700)
  config file = None
  configured module search path = [u'/Users/mclay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mclay/code/mattclay/ansible/lib/ansible
  executable location = /Users/mclay/code/mattclay/ansible/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

### CODE REVIEW

**Comment by dagwieers** [comment]
This would be a lot better for us :-)

**Comment by mattclay** [comment]
bot_skip

**Comment by mattclay** [comment]
There are two significant changes here:

1. Each Windows version will be tested by a separate Shippable node. This causes the tests to run significantly faster than testing 5 Windows versions from a single Shippable node.
1. There are now 3 Windows CI groups instead of 4. Although this means each job will have more tests to run, the performance increase from the change above more than makes up for this.

There are several effects from these changes:

1. We'll be using more Shippable nodes (15 vs 4).
1. We'll be using fewer AWS and Azure VMs (15 vs 20).
1. Nightly coverage runs should no longer time out.
1. It will be easier to spot Windows version specific CI failures.

An alternative to this was considered: Migrate to 5 CI groups and continue testing all versions from a single node. However, this would have resulted in needing 5 Shippable nodes and 25 VMs.

**Comment by mattclay** [comment]
Unstable CI result unrelated to changes.

**Comment by dagwieers** [comment]
Perfect ! Thanks for your continued work on this.

**Pull request merged**
