### PR TITLE
Add include_import tests for many top level include_tasks

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Adding tests for testing a whole lot of `include_tasks` directly in a playbook. This is similar to recent issues report, but this test still fails by running out of memory or reporting maximum recursion depth.

```
TASK [include_tasks] ******************************************************************************************************
included: /ansible/test/integration/targets/include_import/tasks/hello/tasks-file-042.yml for testhost
ERROR! Unexpected Exception, this is probably a bug: maximum recursion depth exceeded
to see the full traceback, use -vvv
NOTICE: To resume at this test target, use the option: --start-at include_import
ERROR: Command "./runme.sh" returned exit status 250.
```

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
include_tasks

##### ANSIBLE VERSION

```
2.6
```

### CODE REVIEW

**Comment by nfnty** [comment]
I'm still hitting this bug with `2.5.0`. No problems are encountered on `2.3.2.0`, which I'm still using due to this issue.

**Comment by samdoran** [comment]
@nfnty Can you provide more details? Are you using _a lot_ of top level `include_tasks` like this test is, or is it something different.

`include_*` will always have a higher memory footprint than `import_*`, and at a certain point the system will OOM. We've gotten things to the point where you should be able to handle a very large number of includes without that happening. If you're still having issues, I'd like more details.

**Comment by sivel** [comment]
I'm not sure what the memory limitation is on shippable, but looks like these tests are failing on `test/integration/targets/include_import/tasks/hello/tasks-file-039.yml`

Not sure if we just want to just limit to a lower number, or do some amount of logic to determine that.

**Comment by nfnty** [comment]
@samdoran About 50 `include_tasks` and each has about 5 sub `include_tasks`. Everything works fine on `2.3.2.0` with `include` and `static: false`. Can't change to `import_tasks` due to conditionals. Going OOM shouldn't be a problem at all. What's the reasoning behind recursing in the first place?

**Comment by sivel** [comment]
With a memory limit of 2GB tests fail on file 42.  With 1GB tests fail on file 35.

fwiw with 16GB of RAM on 2.3.2, I get almost duplicate outcome, although it fails with a recursion error at 42 includes.  The recursion error is a result of looking up the tree to resolve attributes or when serializing the object.

On 2.5 with 16GB of RAM, I can get 196 includes.

**Comment by samdoran** [comment]
@sivel I was aiming for about 4GB of memory consumption with the number I picked. I originally had 256 but that was way too high. I'll dial it down a bit, though it's unfortunate we can't really test the upper limit in Shippable to make sure we're not regressing below where we (now) are.

**Comment by sivel** [comment]
Per the info I just found out, the test nodes are limited to `3.75 GB` but it's possible that users or tests may not have access to that much.

```
12:38:12 <@sivel> mattclay: do you know what the per job memory limit is on shippable (per container)?
12:39:12 <@mattclay> sivel: The nodes are AWS c4.large so they have 3.75 GB on the docker host. I don't think there are any memory restrictions on the containers.
12:40:02 <@sivel> mattclay: thanks. Just doing some investigation into how we need to limit `include_*` tests to fit within memory constraints of the test
12:42:04 <@sivel> mattclay: do we have our own dedicated nodes, or is it possible that mutliple runs/customers could be running on an individual node at a time?
12:42:06 <@mattclay> sivel: I'd keep the memory usage well below the total available on Shippable. Users may not have as much available as the Shippable nodes.
```

**Comment by samdoran** [comment]
rebuild_merge

**Pull request merged**
