### PR TITLE
urldecode filter for Jinja2

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
We needed this in order to deconstruct correct URLs using Jinja2.
And we might as well upstream this.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
urls filters

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by sivel** [comment]
`urlencode` is already a core filter of jinja2 and should likely not be added to ansible.

http://jinja.pocoo.org/docs/dev/templates/#urlencode

**Comment by bcoca** [comment]
@dagwieers  do you want to resubmit just urldecode? diff filters? tests/docs would also be nice in that case

needs_info

**Comment by dagwieers** [comment]
@bcoca I added integration tests for urldecode, please re-review.

**Comment by dagwieers** [comment]
So the urlencode filter is missing from older Jinja2 versions (and I guess that's why we originally included it in this PR). I see that CI is failing on CentoS 6 because of an older Jinja2. Should I add it conditionally ?

**Comment by bcoca** [comment]
we've had this problem several times as the filters get added before/after Jinja2 did same, i would say make it use the Jinja2 filter if you can import it and fallback to yours otherwise .. and try to make the implementations work the same (see changes to unique filter)

**Review by bcoca — APPROVED** [review]

**Pull request merged**
