### PR TITLE
Prevent UnicodeEncodeError: 'ascii' codec can't encode characters in pos...

### PR DESCRIPTION
**Pull request by ashorin**
Prevent UnicodeEncodeError: 'ascii' codec can't encode characters in position ...: ordinal not in range(128).

I do have Unicode in configs...

### CODE REVIEW

**Comment by ashorin** [comment]
BTW, what's wrong with

```
     digest = _md5()
     digest.update(data.encode('utf-8'))
     return digest.hexdigest()
```

**Comment by jimi-c** [comment]
It was running into the exact same error regarding invalid unicode characters for utf-8. Search back through the issues to see why I attempted to correct that with StringIO.

**Comment by ashorin** [comment]
Ah, fetch module with .gz in https://github.com/ansible/ansible/issues/4014. I'll try to find a way which suits both fetch from remote host and delver template with unicode...

**Comment by ashorin** [comment]
I guess, try/except will make it work :)

**Comment by drybjed** [comment]
I just run into the same problem with template using special ASCII characters:

```
fatal: [small.nat] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 383, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 472, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 660, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/template.py", line 91, in run
    local_md5 = utils.md5s(resultant)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 413, in md5s
    digest.update(buf.read())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
```

Used template:

```
^[[1;34m ━━━━ ^[[0m  ^[[1;37m{{ console_organization_name }} ^[[1;30m/ ^[[1;34m{{ console_organization_url }}^[[0m                        
^[[1;34m ━━━━ ^[[0m                                                                                                                       
^[[1;34m ━━━━ ^[[0m  ^[[1;36m\n.\O ^[[1;30m/ ^[[1;33m\l ^[[1;30m/ ^[[1;32m\U ^[[1;30m/ ^[[1;35m\r^[[0m                                    
```

Escape characters haven't caused any problems.

**Comment by jimi-c** [comment]
Give this patch a try:

<pre>
diff --git a/lib/ansible/utils/__init__.py b/lib/ansible/utils/__init__.py
index 2ba2d2d..fd03be9 100644
--- a/lib/ansible/utils/__init__.py
+++ b/lib/ansible/utils/__init__.py
@@ -30,6 +30,7 @@ from ansible.utils import template
 import ansible.constants as C
 import time
 import StringIO
+import io
 import stat
 import termios
 import tty
@@ -408,7 +409,7 @@ def merge_hash(a, b):
 def md5s(data):
     ''' Return MD5 hex digest of data. '''
 
-    buf = StringIO.StringIO(data)
+    buf = io.BytesIO(data.encode('utf-16'))
     digest = _md5()
     digest.update(buf.read())
     return digest.hexdigest()
</pre>

**Comment by drybjed** [comment]
@jimi-c: That works. +1

**Comment by ashorin** [comment]
@jimi-c I have true utf-8 template. Your patch doesn't work in this case. While remote executable md5sum calculates md5 hash over byte values, the 'local' python calculates md5 hash over utf-16 recoded buffer. My guess is the fetch module will fail too.

Compare output from my try/except path when playbook run with --diff --check

```
ok: [authpxy3] => (item={'attrs': '', 'file': 'etc/jetty/contexts/auth-proxy.xml'}) => {"changed": false, "gid": 0, "group": "root", "item": {"attrs": "", "file": "etc/jetty/contexts/auth-proxy.xml"}, "mode": "0644", "owner": "root", "path": "/etc/jetty/contexts/auth-proxy.xml", "size": 7825, "state": "file", "uid": 0}
```

and your utf-16 one:

```
changed: [authpxy3] => (item={'attrs': '', 'file': 'etc/jetty/contexts/auth-proxy.xml'}) => {"changed": true, "item": {"attrs": "", "file": "etc/jetty/contexts/auth-proxy.xml"}}
```

**Comment by jimi-c** [comment]
I was afraid of that, I was hoping it would be smart and only encode the characters it needed to 2 bytes. The only other option I've tried is this:

<pre>
diff --git a/lib/ansible/utils/__init__.py b/lib/ansible/utils/__init__.py
index fd03be9..26e1c58 100644
--- a/lib/ansible/utils/__init__.py
+++ b/lib/ansible/utils/__init__.py
@@ -409,7 +409,12 @@ def merge_hash(a, b):
 def md5s(data):
     ''' Return MD5 hex digest of data. '''
 
-    buf = io.BytesIO(data.encode('utf-16'))
+    try:
+        buf = io.BytesIO(data)
+    except:
+        # must be a unicode object...
+        buf = StringIO.StringIO(data)
+
     digest = _md5()
     digest.update(buf.read())
     return digest.hexdigest()
</pre>

**Comment by drybjed** [comment]
With that path I again have the same error:

```
fatal: [vm0.nat] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 383, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 472, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 660, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/template.py", line 91, in run
    local_md5 = utils.md5s(resultant)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 419, in md5s
    digest.update(buf.read())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
```

**Comment by drybjed** [comment]
@jimi-c: Your suggestion on IRC worked. Current diff:

<pre>
diff --git a/lib/ansible/utils/__init__.py b/lib/ansible/utils/__init__.py
index 2ba2d2d..d825339 100644
--- a/lib/ansible/utils/__init__.py
+++ b/lib/ansible/utils/__init__.py
@@ -30,6 +30,7 @@ from ansible.utils import template
 import ansible.constants as C
 import time
 import StringIO
+import io
 import stat
 import termios
 import tty
@@ -408,7 +409,12 @@ def merge_hash(a, b):
 def md5s(data):
     ''' Return MD5 hex digest of data. '''
 
-    buf = StringIO.StringIO(data)
+    try:
+        buf = io.BytesIO(data)
+    except:
+        # must be a unicode object
+        buf = StringIO.StringIO(data.encode('utf-8'))
+
     digest = _md5()
     digest.update(buf.read())
     return digest.hexdigest()
</pre>

**Comment by ashorin** [comment]
What's the use of  StringIO here?.. Looks like excess entity. @jimi-c, I updated pull request. Try it.

**Comment by jimi-c** [comment]
@ashorin that looks pretty much the same as I was doing, just without the buffers. If others could give it a try and verify it works across a range of files, I'll merge this in.

**Comment by drybjed** [comment]
Patch works as expected. +1

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
