### PR TITLE
Iptables unit tests

### PR DESCRIPTION
**Pull request by sebastiendarocha**
##### SUMMARY
Made some tests fot the iptables modules.

Discovered a small bug when removing a chain

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
 system/iptables

##### ANSIBLE VERSION
```
ansible 2.5.0 (iptables_unit_tests 5312e98afc) last updated 2017/09/22 17:01:20 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sebastien/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sebastien/Source/ansible/lib/ansible
  executable location = /home/sebastien/Source/ansible/bin/ansible
  python version = 3.5.2 (default, Aug 18 2017, 17:48:00) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION
As a maintainer is needed, I propose myself to be a maintainer

```
test/units/modules/system$ pytest -r a  --color yes test_iptables.py::TestIptables
========================================================================================================================== test session starts ==========================================================================================================================
platform linux -- Python 3.5.2, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/sebastien/Source/ansible, inifile:
plugins: xdist-1.20.0, mock-1.6.3, forked-0.2, f5-sdk-3.0.1
collected 12 items                                                                                                                                                                                                                                                       

test_iptables.py ............

======================================================================================================================= 12 passed in 0.03 seconds =======================================================================================================================
```

### CODE REVIEW

**Comment by LinusU** [comment]
Nice! :+1:

**Comment by pilou-** [comment]
@sebastiendarocha: there are two minor problems:
1. > lib/ansible/modules/system/iptables.py:241:14: E302 DOCUMENTATION is not valid YAML

    a _plain style_ YAML string can not contains `:` ([see](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines)). Adding single-quotes around the string will fix this error:
    ```
    - 'Specifies the error packet type to return while rejecting. It implies
      "jump: REJECT"'
    ```

2. > test/sanity/pep8/legacy-files.txt:421:1: A201 Remove "lib/ansible/modules/system/iptables.py" since it passes the current rule set

    Because PEP8 errors have been fixed (in this pull request), you need to remove `lib/ansible/modules/system/iptables.py` from `test/sanity/pep8/legacy-files.txt`.

**Comment by sebastiendarocha** [comment]
Ok, thanks @pilou-, I'll give it a try tonight

I was close to find the solution for the doc, but not for the PEP8 ;-)

**Comment by mkrizek** [comment]
@sebastiendarocha can you please resolve the conflict?

@sebastiendarocha @LinusU Otherwise it looks good to me, anything else on this one before I merge? Thanks!

**Comment by LinusU** [comment]
Looks very good to me!

'ship_it'

**Comment by mkrizek** [comment]
@sebastiendarocha can you please do git rebase instead of merge? Let me know if you need help.

**Comment by sebastiendarocha** [comment]
@mkrizek Is it better like that ?

**Comment by mkrizek** [comment]
@sebastiendarocha Yes :) I'll merge after the CI passes. Thanks for the PR!

**Pull request merged**
