### PR TITLE
Fix the reversed order of return values

### PR DESCRIPTION
**Pull request by rpluem-vf**
AnsibleModule.run_command returns a tuple of return code, stdout and stderr.
The module main function of the user module expects user.create_user to
return a tuple of return code, stdout and stderr.
Fix the locations where stdout and stderr got reversed.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

user
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by samdoran** [comment]
Good catch. I'm surprised this isn't causing more issue. Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

**Comment by rpluem-vf** [comment]
Change fragment added in c171cbb59bdf57ef9bf53016c6be74c9c62235bc, further occurrences fixed in a17e252534b1d0ccf9deffe54d74c733dad38844.

**Comment by rpluem-vf** [comment]
ready_for_review

**Comment by rpluem-vf** [comment]
Is there anything I can do to move this forward?

**Comment by samdoran** [comment]
rebuild_merge

**Comment by samdoran** [comment]
Thank you for the contribution. I've been buried in some other things. Sorry it took me a while to get to merging this.

**Comment by rpluem-vf** [comment]
No problem. Thanks for taking care.

**Pull request merged**
