### PR TITLE
docker_login python3 new base64 lib fix

### PR DESCRIPTION
**Pull request by kiv-box**
##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by alikins** [comment]
What does this fix? What error does it cause? (what would someone searching issues/prs for this problem search for?)

**Comment by bcoca** [comment]
also, this is not a good fix as it can still generate exceptions, use the `to_bytes` functions instead

**Comment by rraval** [comment]
@alikins I'm running into the same error on Python 3.6.1 running Ansible 2.3.1.0:

```
Traceback (most recent call last):
  File "/tmp/ansible_f9kx96q8/ansible_module_docker_login.py", line 334, in <module>
    main()
  File "/tmp/ansible_f9kx96q8/ansible_module_docker_login.py", line 325, in main
    LoginManager(client, results)
  File "/tmp/ansible_f9kx96q8/ansible_module_docker_login.py", line 168, in __init__
    self.login()
  File "/tmp/ansible_f9kx96q8/ansible_module_docker_login.py", line 203, in login
    self.update_config_file()
  File "/tmp/ansible_f9kx96q8/ansible_module_docker_login.py", line 280, in update_config_file
    auth=base64.b64encode(self.username + b':' + self.password),
TypeError: must be str, not bytes
```

**Comment by rraval** [comment]
Ping!

How can I help move this bug along? Is there any additional information required?

**Comment by andywirv** [comment]
ansible 2.3.1.0
Python 3.6.1

Task:
```
- name: Log into private registry and force re-authorization
  docker_login:
    registry_url: docker-registry.yourdomain.co
    username: username
    password: password
```
Error:
`self.update_config_file()\r\n  File \"/tmp/ansible_6g7p808o/ansible_module_docker_login.py\", line 280, in update_config_file\r\n    auth=base64.b64encode(self.username + b':' + self.password),\r\nTypeError: must be str, not bytes\r\n"`


Isolated example of issue from [https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_login.py#L279](url)
```
import base64

def update_config_file (username, password):
    auth=base64.b64encode(username + b':' + password)
    print(auth)

update_config_file('user','pass')
```
Python2 2.7.10
```
python example.py 
dXNlcjpwYXNz

```

Python3 3.6.1
```
python3 example.py 
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    update_config_file('user','pass')
  File "example.py", line 4, in update_config_file
    auth=base64.b64encode(username + b':' + password)
TypeError: must be str, not bytes
```

Fixed version
```
import base64

def update_config_file (username, password):
    auth=base64.b64encode((username + ':' + password).encode(encoding = 'UTF-8',errors = 'strict'))
    print(auth)

update_config_file('user','pass')
```

Python2 2.7.10
```
python example.py 
dXNlcjpwYXNz
```

Python3 3.6.1
```
python3 example.py 
b'dXNlcjpwYXNz'
```

**Review by andywirv — CHANGES_REQUESTED** [review]
How about doing the string concat and then encoding everything. Being explicit about encoding error handling (I know it is default)

auth=base64.b64encode((username + ':' + password).encode(encoding = 'UTF-8',errors = 'strict'))

**Comment by andywirv** [comment]
This is already fixed in https://github.com/ansible/ansible/commit/3f67d167fe1fa98c9565241a7fa3b3f262c0720f
based on this issue
https://github.com/ansible/ansible/issues/26690

**Comment by abadger** [comment]
Closing this as it has already been fixed.

**Pull request closed without merging**
