### PR TITLE
zabbix_host: fix various idempotency problems

### PR DESCRIPTION
**Pull request by eikef**
##### SUMMARY
This PR fixes a few idempotency problems with the zabbix_host module, especially when some optional parameters (visible_name, description, inventory_mode, inventory_zabbix, proxy, tls_*) are not specified on module invocation.

It also simplifies the update procedure, eliminating needless duplication of code (half of which was missing some update logic, in any case).

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION
2.5.0

### CODE REVIEW

**Comment by angystardust** [comment]
Thanks for your effort @eikef but this patch still can't definitely fix my idempotency issue :(

**Comment by eikef** [comment]
@angystardust I had not referenced it as such :-) I'm writing an integration test suite for the zabbix_host module and fixing issues that come up. The effort is not yet done. In particular, the interface update logic has not yet been touched, nor have I yet written tests for uppercase/lowercase disparities.

**Comment by eikef** [comment]
shipit

**Comment by D3DeFi** [comment]
Hi @eikef, almost everything looks good and seems to be working except updating interfaces when `force: no` is used. I've created new host:
```yaml
<...omitted...>
        force: no
        interfaces:
          # Agent interfaces
          - type: 1
            main: 1
            useip: 0
            ip: '{{ ansible_default_ipv4.address }}'
            dns: '{{ inventory_hostname }}'
            port: 10050
```

Then, I've tried to update that host with `useip: 1` and it just throws `Invalid params., Host cannot have more than one default interface of the same type` . This seems to work when I checkout back to devel.

(edit) Noticed just now that it did changed the value for the interface. Just ansible has thrown the error I've mentioned above.

**Comment by eikef** [comment]
@D3DeFi I don't yet see how that would have changed with this PR, though it is possible. In any case, the interface update logic needs to be rewritten; I did not really touch it in this PR and it has several problems (including angystardust's idempotency problem). It's next on my list of things to look at, though. I didn't want to further convolute this PR (it changes a bunch of things already), and I wanted to get the integration tests (#33184) committed before working on it so the fixes actually get tests an regressions can be spotted more easily :)

**Comment by D3DeFi** [comment]
Problem seems to be that [this condition](https://github.com/ansible/ansible/pull/33138/files#diff-66ec95ecd607d3081871d33bc21d8d67R706) is True when force is set to no and there are interfaces passed to module as argument. New interfaces get appended with existing ones, thus creating possible duplicates.

However, I do understand what you are saying and I agree that interface logic needs to be updated. If you need any help just let me know. Imho, I've presented a very edge case and this PR is good to go.

**Comment by D3DeFi** [comment]
shipit

**Review by D3DeFi — APPROVED** [review]

**Comment by eikef** [comment]
@D3DeFi thanks for tracking that down. I'll keep it in mind for the revised update logic, which I should be able to do this week.

**Comment by eikef** [comment]
bot_status

**Comment by jctanner** [comment]
bot_status

**Pull request merged**
