### PR TITLE
Allow port override in hosts file

### PR DESCRIPTION
**Pull request by surekap**
Make ParamikoConnection capable of handling host:port syntax in hosts file to allow overriding port numbers.

### CODE REVIEW

**Comment by mpdehaan** [comment]
see comment made on commit

**Comment by surekap** [comment]
Yes. I tested it. It works with hostnames and host.domain syntax as well.

**Comment by mpdehaan** [comment]
excellent, will try things out and merge shortly

thanks!

**Comment by sfromm** [comment]
it appears 8a177ec will have a problem if someone specifies an ipv6 address in their inventory file.

**Comment by mpdehaan** [comment]
let's use some other seperator then, even though it may make less sense.

",port=" would be pretty explicit and maybe even a little future proof ?

we'll also want to document whatever we decide in the docs project

**Comment by surekap** [comment]
I personally think its best to stick to the [RFC3986](http://tools.ietf.org/html/rfc3986) standard to avoid having to learn a new syntax. According to the spec, IPv6 URLS should be enclosed in box brackets "[]". Hence: [ff:ff:ff:ff:ff:ff:ff:ff]:22 is valid syntax.

I suggest we use regexes if necessary to pull out the ipv6 address.

**Comment by mpdehaan** [comment]
Works for me.  If someone wants to make it work better with IPV6, hey can make additions on top of this patch.

I suspect quite a few people will be using hostnames anyway.

**Comment by surekap** [comment]
Or even better - the urlparse module

**Comment by mpdehaan** [comment]
sidenote, an argument for ,port= would be that it would eventually also allow per host connection preferences, eg ,connection=something_other_than_ssh

However we can still do that keeping the colon for the port, even if we did that.

**Comment by surekap** [comment]
If you want to do that, then why not use the url scheme: ssh://host:port or telnet://host:port

See my code commit - its easily possible to allow connection schemes.

------Original Message------

**Comment by mpdehaan** [comment]
Much easier to type, doesn't imply functionality that isn't there  (ssh://user:host/...) etc.   It's not a full URI.

Anyway, this is good enough for now.

**Comment by mpdehaan** [comment]
Thanks...

Sorry to continue this discussion but I see a few things.  First off, I see you have scp.py in your branch, but it's not part of the pull request.  (commit ends in 'd0' per history in your branch)

Also, can you elaborate on when sftp wouldn't work?   Is it common to have it turned off on any particular distros?  Stock Fedora/CentOS does not have this problem and it's enabled stock.   I would rather avoid maintaining our own copy of a scp wrapper library (where did this come from originally, it may be widely used enough that we don't care).

My other minor issue is I see scp.py has a GPLv2+ copyright, Ansible is GPLv3+... though first question first :)

**Comment by mpdehaan** [comment]
ok, yeah, these topics are mixed... how about we close this and you send me one pull request for the port stuff (which should be a very small patch) and we can leave the SCP stuff for a seperate discussion.  It is probably worth bringing up SCP on the mailing list.

What may have happened is you sent me a pull request for the branch, and started to do something else on the same branch... whereas maybe the SCP stuff should have been on another branch and another pull request.

Anyway, let me know if this is confusing.

I want this in and fixed, so hang in there :)

Thanks.

**Comment by surekap** [comment]
My simple case for SCP is that it makes ansible more resilient and able to depend less on external components.

I checked Debian Lenny and Squeeze and they seem to have it on, but I suspect some VM appliances or those not using OpenSSH may have issues.

I agree that we shouldn't have to maintain a new library - I sent out the link from where I got the file (original credits are intact).
http://bazaar.launchpad.net/~jbardin-deactivatedaccount/paramiko/paramiko_scp/view/head:/paramiko/scp.py

It is GPLv2+ but liberally allows repackaging as GPLv3+ at your option:

# This program is free software; you can redistribute it and/or modify

# it under the terms of the GNU General Public License as published by

# the Free Software Foundation; either version 2 of the License, or

# (at your option) any later version.

At any rate, in case you don't want a separate file/library, the nuts and bolts of scp seems minimal enough that we can inline it into connections.py (at the cost of some code complexity).

**Comment by surekap** [comment]
Created a new pull request (with just the urlparse code).

**Comment by mpdehaan** [comment]
Thanks will take a look at this probably tonight.   Much appreciated.

I would like to hold off on the SCP in the "YAGNI" case, given "I suspect some VM appliances or those not using OpenSSH may have issues" need some concerete examples first, otherwise it just introduces more test/maintaince/bitrot surface.   Further, it's not true neccessarily that it would have less external components, paramiko is still integral, and the SFTP I imagine is not a brittle component of that if the main parts are functional -- we have encountered one person with a very old openssh (2007) that had it off, but I'd rather not bend over backwards to keep that operational -- especially when running an SSH that isn't patched up has a whole numerous other load of potential security problems (not for ansible, just in general).

All the ones I'm aware of are using openssh.

Regardless, thanks very much for splitting this and glad to have you adding stuff.

**Pull request closed without merging**
