### PR TITLE
Include error exception in AnsibleError

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Use to_native instead of str

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
- lib/ansible/plugins/connection/paramiko_ssh.py
- lib/ansible/plugins/connection/zone.py
- lib/ansible/plugins/lookup/dig.py
- lib/ansible/plugins/lookup/dnstxt.py
- lib/ansible/plugins/lookup/sequence.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by alikins** [comment]
Ooof, the 'before' for some of these cases looks pretty busted indeed. This fix looks like it should help eliminate some weird/busted error handling in the future, so +1 to that.

**Comment by abadger** [comment]
```s/str(e)/to_native(e)/```.  Once that's done, this is ready to merge.

**Comment by Akasurde** [comment]
@abadger Done. ready_for_review

**Comment by gundalow** [comment]
@tkuratomi @alikins does this need backporting to stable-2.3?

**Comment by bcoca** [comment]
merged to stable-2.3

**Comment by Akasurde** [comment]
@gundalow @bcoca @abadger @alikins Thanks for comments and reviews.

**Pull request merged**
