### PR TITLE
docker_network: Integration tests for IPAM config idempotence

### PR DESCRIPTION
**Pull request by SirFerdek**
Integration tests for pull request #56901 which fixes found issues with idempotence.
As asked for by @felixfontein 🍻

##### SUMMARY
Added idempotence verifications to existing test cases for `ipam_config` and `ipam_options`. Slightly extended tests for deprecated `ipam_options` so they verify that it still in fact works just like `ipam_config`

##### ISSUE TYPE
- Integration tests Pull Request

##### COMPONENT NAME
docker_network
integration tests

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
LGTM! Thanks for updating/extending the tests!

**Review by felixfontein — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
@SirFerdek thanks for adding the test!

**Comment by SirFerdek** [comment]
@felixfontein It was a pleasure working with you :1st_place_medal: . Thanks for taking care on backporting fix into 2.8. Should we also fix even older versions if they are also impacted?

**Comment by felixfontein** [comment]
@SirFerdek thanks a lot! It was also a pleasure working with you :) About older versions: they only receive critical bug fixes (2.7.x) or even only security fixes (2.6.x) by now (see [here](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#release-status)). Also, `aux_addresses` was only added for 2.8 IIRC, so there's no need to backport it to earlier versions anyway ;)

**Pull request merged**
