### PR TITLE
How to contribute to Ansible maintained collections

### PR DESCRIPTION
**Pull request by samccann**
##### SUMMARY

List the details of how the community can contribute successfully to the collections maintained by the Ansible team.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs.ansible.com
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jctanner** [comment]
We are not considering this a blocker for 2.10 base release.

**Comment by samccann** [comment]
@jctanner was there something in this PR (label etc?) that suggested it was a 2.10 blocker? Just want to be sure I'm not mislabeling things and making more work for your team.

**Comment by jctanner** [comment]
@samccann nope not your fault. We had added it to our board and then decided otherwise after team discussion.

**Comment by jctanner** [comment]
@samccann nope not your fault. We had added it to our board and then decided otherwise after team discussion.

**Pull request merged**
