### PR TITLE
Update bundled version of distro from 1.4.0 to 1.5.0

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Includes changes we made in our version that were merged upstream (nir0s/distro#246)

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

`lib/ansible/module_utils/distro/`

### CODE REVIEW

**Review by Shrews — APPROVED** [review]
LGTM. Verified with a git diff against 1.4.0 and 1.5.0.

**Review by jimi-c — APPROVED** [review]

**Comment by abadger** [comment]
Looks fine. Note about removing argparse instead of replacing it; we were trying to collaborate on an upstream branch so that everyone who needed python2. 6 support could work together to maintain the needed changes.  Upstream was supportive of this but a little busy at the crucial time when this was taking off, though, so i was the only one who contributed to the branch.  If you still want to try making it so we aren't maintaining this alone, it's this branch https://github.com/nir0s/distro/tree/python2.6-support

**Comment by samdoran** [comment]
@abadger That's really good to know. Is there much more to do for 2.6 compatibility besides the few changes I've made here? I could think of ways to more gracefully handle argparse/optparse besides just removing it. I didn't see any other glaring Python 2.6 issues from looking through the code, but I'm sure I'm missing something.

**Comment by abadger** [comment]
I think your changes are sufficient. There wasn't a while lot needed to make it work on python 2.6

**Pull request merged**
