### PR TITLE
modules: network: ingate: Add module ig_store_edit

### PR DESCRIPTION
**Pull request by ingatesystems**
##### SUMMARY
Add Ingate network module ig_store_edit

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
ig_store_edit

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0 (add-module-ig-store-edit 943dbe79a5) last updated 2018/10/26 16:28:27 (GMT +200)
  config file = None
  configured module search path = [u'/home/erik/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /share/washi-users/erik/git/ansible/lib/ansible
  executable location = /share/washi-users/erik/git/ansible/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

### CODE REVIEW

**Review by ganeshrn — COMMENTED** [review]
This module and other ingate modules currently open seem to be the lightweight wrapper around a single api.  You can combine these into a single logical module instead of having a separate module for each api. Please refer https://docs.ansible.com/ansible/latest/dev_guide/developing_modules.html
for module development guideline

**Comment by ingatesystems** [comment]
Thanks for the feedback. I will look into the link you sent.

**Comment by ingatesystems** [comment]
Hi, I've tried to group all the functionality required for managing the configuration database into a single "logical" module called "ig_config".

**Comment by ingatesystems** [comment]
Hi, sorry to bother you but do you need more information in order to be able to proceed with this PR? Would be happy for any feedback that helps me fix any outstanding issues.

**Comment by ingatesystems** [comment]
Hi, any feedback? Should I create a new PR for the last change or is the new functionality broken somehow? Thanks Erik

**Review by ganeshrn — APPROVED** [review]
Thank you!

**Comment by ganeshrn** [comment]
rebuild_merge

**Pull request merged**
