### PR TITLE
Win_unzip: Remove all examples about other modules and streamline examples

### PR DESCRIPTION
**Pull request by Fale**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
windows/win_unzip

##### SUMMARY
Remove all examples about other modules and streamline examples

@gundalow 
@nitzmahone

### CODE REVIEW

**Comment by nitzmahone** [comment]
@Fale I think the reason those were there was to show a way to install the necessary PSCX extensions to allow decompression of non-zip archives via `win_unzip`. That said, they could be rewritten now against `win_package` to use a direct URL and be fully idempotent instead of downloading unnecessarily once PSCX is installed...

**Comment by dagwieers** [comment]
Yeah, I would leave that example in, it is very useful for end-users.

**Comment by jhawkesworth** [comment]
@Fale - shall we just close this one?  Would be good to re-write the example of installing pscx as suggested by nitzmahone but as it is you have conflicts now.

**Comment by Fale** [comment]
Yes, going to close it and eventually re-create it

**Pull request closed without merging**
