### PR TITLE
Network and cloudstack wildcard imports

### PR DESCRIPTION
**Pull request by abadger**
##### SUMMARY
Clean up wildcard imports in nxos, f5, and cloudstack.  wildcard imports confuse some static analysis tools and are not good practice.  Getting close to having these all cleaned up so that we can have pylint detect these for us automatically.

##### ISSUE TYPE
 - Bugfix Pull Request

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by abadger** [comment]
@resmo @caphrim007 If you'd care to take a look at your modules in this PR I'd appreciate it.  Switching from ```import * ``` was largely intuitive but there were a few things I did that would be good to have confirmation on.

* For Cloudstack, there were a few places where I had to import CloudStackException
* For the f5 modules
  * I switched to doing the bigsuds_found/HAS_F5SDK determination solely via the import from f5_utils
  * I got rid of a use of map + lambda.  Was trying not to have to import those to make them behave the same between py2 and py3.  In the end I left one instance of map so the code did still have to import.

**Comment by caphrim007** [comment]
@abadger I am going to tentatively +1 this. I will need to back-port those changes to the f5-ansible repo to be 100% sure, but in the meantime I would say "i approve".

Note that some of those changes will be overwritten in future PRs for 2.5 because the things that changed have been removed or replaced in the future PRs.

**Comment by abadger** [comment]
Talked with caphrim007 on IRC and we decided he'll push those changes as part of his work on the f5 modules for his tree in the 2.5 timeframe.  Removed those change from this PR and added a fix for the test_nclu unittest.

**Comment by resmo** [comment]
shipit

@abadger I am currently in the progress on streamline all modules for 2.5, eliminating the dependency of CloudStackException in all left cloudstack modules, along with pep8 fixes and other minor cleanups. But your changes LGTM.

**Comment by abadger** [comment]
Cool.  Thanks for the review @resmo !

**Pull request merged**
