### PR TITLE
ansible-test - Update PSScriptAnalyzer to 1.21.0

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Upgrade PSScriptAnalyzer in ansible-test to 1.21.0 which enables 3 new rules and includes a few bugfixes. When testing against `ansible.windows` and `community.windows` I see some of the following errors:

* `win_uri` - AvoidUsingBrokenHashAlgorithms - Can just update to use SHA256 for download checksums
* `slurp` - AvoidSemicolonsAsLineTerminators
* `win_domain` - AvoidSemicolonsAsLineTerminators
* `win_environment` - AvoidSemicolonsAsLineTerminators
* `win_path` - AvoidSemicolonsAsLineTerminators
* `win_disk_facts` - AvoidSemicolonsAsLineTerminators
* `win_dns_record` - AvoidSemicolonsAsLineTerminators
* `win_file_version` - AvoidSemicolonsAsLineTerminators
* `win_iis_virtualdirectory` - AvoidSemicolonsAsLineTerminators
* `win_iis_website` - AvoidSemicolonsAsLineTerminators
* `win_lineinfile` - AvoidSemicolonsAsLineTerminators
* `win_rabbitmq_plugin` - AvoidSemicolonsAsLineTerminators

The `AvoidSemicolonsAsLineTerminators` rule is optional but I thought it best to enable. There's an auto formatting rule to fix this with PSSA so fixing these errors won't be too hard to do but will leave it up to the WWG to decide whether we want to keep that enabled or leave it disabled.

##### ISSUE TYPE
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME
ansible-test pslint

### CODE REVIEW

**Comment by jborean93** [comment]
Will wait until https://github.com/ansible/community/issues/644#issuecomment-1262943340 is decided before trying to fix the now failing sanity tests.

**Comment by briantist** [comment]
I think the semi-colon rule is good. As before, we should try to do that bulk change as a separate commit (in main) so that we can add it to blame ignore.

**Review by nitzmahone — APPROVED** [review]
All LGTM, though when it comes time to fix the collections, I'd keep the hash algs change separate from the semicolon stuff since that's a "real" change. Luckily it looks like the hash data isn't exposed, so the upgrade should be a totally user-invisible change anyway.

**Review by nitzmahone — APPROVED** [review]
looks good- we should merge without a squash and add that commit to `.git-blame-ignore-revs` since that seems to be a thing now...

**Pull request merged**
