### PR TITLE
generate rst doc pages for command line tools

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY

This changes generate_man.py to also generate rst format documentation for the cli tools.

##### ISSUE TYPE

 - Feature Pull Request

 - Docs Pull Request

##### COMPONENT NAME

docs/bin/generate_man.py
docs/docsite/

##### ANSIBLE VERSION

```
ansible 2.4.0 (cli_rst f06a8d190e) last updated 2017/07/31 16:51:06 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by dharmabumstead — APPROVED** [review]
Docs OK with a few edits. Merge when ready. Thanks @alikins!

**Comment by alikins** [comment]
@dharmabumstead I accidentally clobbered your edits when I forced pushed to this branch, but I think I recreated them with https://github.com/ansible/ansible/pull/27530/commits/371089ad59bad1fa7e75b0f1492556056d368372 and https://github.com/ansible/ansible/pull/27530/commits/8f85950ec25d2a8e9faef0ef0d616c2204b83cd8

**Review by dharmabumstead — APPROVED** [review]

**Comment by dharmabumstead** [comment]
Thanks @alikins - merge at will.

**Comment by abadger** [comment]
With agreement from bcoca, alikins, and dharmabumstead, cherry-picked this one to stable-2.4 for 2.4.0rc2.

**Pull request merged**
