### PR TITLE
Implements multiple interpreter overrides

### PR DESCRIPTION
**Pull request by bcoca**
previous pulls were tainted cause of history rewrite and weird github caching when reusing branch names
addresses #1486

### CODE REVIEW

**Comment by dhozac** [comment]
Won't this lead to the modules using python -tt looking for ansible_python -tt_interpreter? I thought we were aiming for keeping the arguments across interpreter changes too.

**Comment by bcoca** [comment]
it shouldn't in current version, I haven't had time to get to adding
additional arguments back and test, I'll do so in subsequent commit as soon
as i can.

On Tue, Nov 27, 2012 at 3:15 PM, Daniel Hokka Zakrisson <
notifications@github.com> wrote:

> Won't this lead to the modules using python -tt looking for ansible_python
> -tt_interpreter? I thought we were aiming for keeping the arguments across
> interpreter changes too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/1697#issuecomment-10774845.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001

**Comment by dhozac** [comment]
Debug output from a yum-module run:

```
shebang = #!/usr/bin/python -tt
interpreter_config = ansible_python -tt_interpreter
ending with shebang = #!/usr/bin/python -tt
```

**Comment by bcoca** [comment]
that be a bug then, I tested a few python modules, 1 bash one, lets see if
i get time tonight to go over this.

he, just realized the 3 modules with -tt are ones I don't use (apt,ec2,yum)

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001

**Comment by dhozac** [comment]
https://github.com/dhozac/ansible/commit/31890669fc4fac8d06480763c038f074d77692c2 seems to do the right thing for me.

**Pull request merged**
