### PR TITLE
gitlab_hook: renaming module name

### PR DESCRIPTION
**Pull request by Lunik**
##### SUMMARY

Renaming `gitlab_hooks` module into `gitlab_hook`.
Module should have singular name.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

gitlab_hooks

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Lunik** [comment]
ready_for_review

**Comment by Shaps** [comment]
shipit

**Review by dagwieers — CHANGES_REQUESTED** [review]
We should also update the examples in the module docs.

**Comment by Lunik** [comment]
Should be fine now

**Comment by Shaps** [comment]
Ah, sorry, diff view didn't show that bit :) 

shipit

**Comment by resmo** [comment]
shipit

**Review by dagwieers — APPROVED** [review]

**Pull request merged**
