### PR TITLE
win_feature: Clean up and check-mode support

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_feature

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Changes include:
- Remove trailing semi-colons
- Replaced PSObjects into normal hashes
- Make use of Get-AnsibleParam and types
- Added check-mode support

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to:

```
2017-02-13 19:14:26 TASK [win_feature : check result of installing invalid feature name] ***********
2017-02-13 19:14:26 task path: /root/src/github.com/ansible/ansible/test/integration/targets/win_feature/tasks/main.yml:125
2017-02-13 19:14:26 skipping: [windows-2008-SP2] => {
2017-02-13 19:14:26     "changed": false, 
2017-02-13 19:14:26     "skip_reason": "Conditional result was False", 
2017-02-13 19:14:26     "skipped": true
2017-02-13 19:14:26 }
2017-02-13 19:14:26 fatal: [windows-2012-RTM]: FAILED! => {
2017-02-13 19:14:26     "failed": true, 
2017-02-13 19:14:26     "msg": "The conditional check 'win_feature_install_invalid_result.exitcode == 'InvalidArgs'' failed. The error was: error while evaluating conditional (win_feature_install_invalid_result.exitcode == 'InvalidArgs'): 'dict object' has no attribute 'exitcode'"
2017-02-13 19:14:26 }
2017-02-13 19:14:26 fatal: [windows-2012-R2_RTM]: FAILED! => {
2017-02-13 19:14:26     "failed": true, 
2017-02-13 19:14:26     "msg": "The conditional check 'win_feature_install_invalid_result.exitcode == 'InvalidArgs'' failed. The error was: error while evaluating conditional (win_feature_install_invalid_result.exitcode == 'InvalidArgs'): 'dict object' has no attribute 'exitcode'"
2017-02-13 19:14:26 }
2017-02-13 19:14:26 fatal: [windows-2008-R2_SP1]: FAILED! => {
2017-02-13 19:14:26     "failed": true, 
2017-02-13 19:14:26     "msg": "The conditional check 'win_feature_install_invalid_result.exitcode == 'InvalidArgs'' failed. The error was: error while evaluating conditional (win_feature_install_invalid_result.exitcode == 'InvalidArgs'): 'dict object' has no attribute 'exitcode'"
2017-02-13 19:14:26 }
```

**Comment by dagwieers** [comment]
I fail to see how this test could have worked prior to my changes. If the module failed previously, it did not return an exitcode either... Still investigating.

**Comment by mattclay** [comment]
CI failure due to integration test failure. Here's the first one:

```
win_feature-C2w9AQ / /root/src/github.com/ansible/ansible/test/integration/targets/win_feature/tasks/main.yml:125 / [windows-2008-R2_SP1] windows: win_feature : check result of installing invalid feature name that=[u'win_feature_install_invalid_result|failed', u'not win_feature_install_invalid_result|changed', u'win_feature_install_invalid_result.msg', u"win_feature_install_invalid_result.exitcode == 'InvalidArgs'"]

failure: The conditional check 'win_feature_install_invalid_result.exitcode == 'InvalidArgs'' failed. The error was: error while evaluating conditional (win_feature_install_invalid_result.exitcode == 'InvalidArgs'): 'dict object' has no attribute 'exitcode'

            {
    "failed": true, 
    "msg": "The conditional check 'win_feature_install_invalid_result.exitcode == 'InvalidArgs'' failed. The error was: error while evaluating conditional (win_feature_install_invalid_result.exitcode == 'InvalidArgs'): 'dict object' has no attribute 'exitcode'"
}
```

Link to test failure here: https://app.shippable.com/runs/58a62c4bc57e1b10004e28cc/6/tests

**Comment by dagwieers** [comment]
Yeah, and I still don't understand why that is. Makes no sense to me the error should have an exitcode as it did before.

**Comment by dagwieers** [comment]
No CI status, close and re-open.

**Comment by mattclay** [comment]
CI failure due to integration test errors:

```
2017-02-20 00:55:29 fatal: [windows-2012-RTM]: FAILED! => {
2017-02-20 00:55:29     "changed": false, 
2017-02-20 00:55:29     "failed": true, 
2017-02-20 00:55:29     "msg": "Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter' required by parameter 'WhatIf'. "
2017-02-20 00:55:29 }
```

**Comment by mattclay** [comment]
CI failure due to:

```
2017-02-20 20:39:15 TASK [win_feature : check result of installing invalid feature name] ***********
2017-02-20 20:39:15 task path: /root/src/github.com/ansible/ansible/test/integration/targets/win_feature/tasks/main.yml:125
2017-02-20 20:39:15 fatal: [windows-2012-RTM]: FAILED! => {
2017-02-20 20:39:15     "failed": true, 
2017-02-20 20:39:15     "msg": "The conditional check 'win_feature_install_invalid_result.exitcode == 'InvalidArgs'' failed. The error was: error while evaluating conditional (win_feature_install_invalid_result.exitcode == 'InvalidArgs'): 'dict object' has no attribute 'exitcode'"
2017-02-20 20:39:15 }
2017-02-20 20:39:15 fatal: [windows-2012-R2_RTM]: FAILED! => {
2017-02-20 20:39:15     "failed": true, 
2017-02-20 20:39:15     "msg": "The conditional check 'win_feature_install_invalid_result.exitcode == 'InvalidArgs'' failed. The error was: error while evaluating conditional (win_feature_install_invalid_result.exitcode == 'InvalidArgs'): 'dict object' has no attribute 'exitcode'"
2017-02-20 20:39:15 }
```

**Comment by dagwieers** [comment]
Yup, I know, no change there. No idea why either.

**Comment by dagwieers** [comment]
Alright, problem was not in the module, which explained my confusion. There was a bug in module_utils/powershell.ps1 causing Hashtable $result to not return exactly the same information than a PSObject $result.

@nitzmahone Can you confirm that what I am doing is correct here ? A bit unfortunate that it's as part of this PR, but this one was the only one with integration tests failing ! (Which says a lot about the other integration tests I guess  ;-))

**Comment by dagwieers** [comment]
This PR requires Bugfix #21697 to work correctly.

**Comment by dagwieers** [comment]
Close and re-open to trigger CI.

**Comment by dagwieers** [comment]
A weird CI error unrelated to win_feature on Windows 2008 SP2. Close and re-open.

**Comment by dagwieers** [comment]
Sigh, fails a second time with the exact same error.
Makes no sense if you see the last commit that *fails*.
https://github.com/ansible/ansible/pull/21351/commits

**Review by nitzmahone — APPROVED** [review]

**Review by nitzmahone — CHANGES_REQUESTED** [review]
The powershell.ps1 changes got picked up in here as well, they've already been merged, so it's a conflict.

**Comment by dagwieers** [comment]
@nitzmahone ready_for_review

**Comment by dagwieers** [comment]
!needs_revision

**Comment by dagwieers** [comment]
@nitzmahone Can you verify this is now OK for you ?

**Comment by dagwieers** [comment]
@nitzmahone Can you check ? Mostly Get-AnsibleParam changes and hashtable usage.
Plus whitespace cleanup.

**Comment by dagwieers** [comment]
@nitzmahone @jhawkesworth @trondhindenes @jborean93 Can someone please review this ?

**Comment by jhawkesworth** [comment]
lgtm

shipit

**Comment by dagwieers** [comment]
!needs_revision

**Comment by jborean93** [comment]
Looks good

shipit

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
