### PR TITLE
Use v1 jobs endpoint

### LINKED ISSUE #33340: kubernetes.py module fails to create Job
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/clustering/kubernetes.py

##### ANSIBLE VERSION
```
2.4
```

##### CONFIGURATION
ANSIBLE_HOST_KEY_CHECKING=false
GOOGLE_APPLICATION_CREDENTIALS=/path/to/credential_file

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Attempt to create any Kubernetes job fails until the KIND_URL endpoint is changed from:

"job": "/apis/extensions/v1beta1/namespaces/{namespace}/jobs",
 to:
 "job": "/apis/batch/v1/namespaces/{namespace}/jobs"

##### STEPS TO REPRODUCE
Running against K8S:
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-gke.0", GitCommit:"a7061d4b09b53ab4099e3b5ca3e80fb172e1b018", GitTreeState:"clean", BuildDate:"2017-10-10T18:48:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Attempt to use Ansible Kubernetes module to create a standard Job fails

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed to create the resource: HTTP Error 404: Not Found", "url": "https://35.196.250.221/apis/extensions/v1beta1/namespaces/hassan/jobs"}

kind: Job
metadata:
  name: testjob
  namespace: default
  labels:
    app: testjob
spec:
  template:
    spec:
      containers:
      - name: test
        image: centos
        command: ['sh', '-c', 'true']
      restartPolicy: Never

##### EXPECTED RESULTS
Job should get created

##### ACTUAL RESULTS
Ansible play fails

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed to create the resource: HTTP Error 404: Not Found", "url": "https://35.196.250.221/apis/extensions/v1beta1/namespaces/default/jobs"}
```

### PR DESCRIPTION
**Pull request by hassanhassoun**
##### SUMMARY
Fixes #33340

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/clustering/kubernetes.py

##### ANSIBLE VERSION
```
ansible 2.4
```

##### ADDITIONAL INFORMATION
Proposed job api endpoint works with the latest Ansible and Kubernetes versions

### CODE REVIEW

**Comment by resmo** [comment]
AFAICS the old job api was removed in 1.9. Do we need a fallback here for  kubernetes < 1.9?

**Comment by hassanhassoun** [comment]
@resmo AFAICS the old job api was removed since at least K8S v1.7, the version I had to make this change for.

**Comment by hassanhassoun** [comment]
This module is not currently structured to allow for different versions of the API, I think it's appropriate to set the endpoints based on the latest version. 

Supporting different versions of the API would be a little more than a feature request !

**Comment by fabianvf** [comment]
the `kubernetes` module is deprecated in favor of the `k8s` module in Ansible 2.6, which should support all versions of the job API present on the cluster.

**Comment by gundalow** [comment]
Given the above comment I think this can be closed

**Pull request closed without merging**
