### PR TITLE
Remove VC scaleway

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

The VC product line is going to be replaced with the START1 product line.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- scaleway_compute.py

##### ANSIBLE VERSION

```
ansible 2.7.0dev0 (remove_vc 4a2509d751) last updated 2018/05/28 14:35:23 (GMT +200)
  config file = None
  configured module search path = [u'/Users/sieben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sieben/workspace/ansible/lib/ansible
  executable location = /Users/sieben/workspace/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### ADDITIONAL INFORMATION

You should be able to test with the following command:

```
$ python ./bin/ansible-playbook -vvvvv -i /dev/null ./test/legacy/scaleway_compute.yml
```

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
shipit

**Comment by maxamillion** [comment]
@sieben - is this something that needs to be backported to Ansible 2.6? (devel is 2.7 now)

**Comment by remyleone** [comment]
Yes it should be backported. How can I do that?

Em sáb, 2 de jun de 2018 05:15, Adam Miller <notifications@github.com>
escreveu:

**Comment by maxamillion** [comment]
@sieben make a cherry-pick PR for the `stable-2.6` branch once this merges into `devel`, I'll approve and merge it.

**Comment by remyleone** [comment]
Ok feel free to merge it and I will get started with the cherry pick :)

Le lun. 4 juin 2018 à 00:41, Adam Miller <notifications@github.com> a
écrit :

**Comment by remyleone** [comment]
@maxamillion Could you merge it ?

**Comment by maxamillion** [comment]
@sieben sorry, that was on me

**Pull request merged**
