### PR TITLE
openssl_csr: ignore empty strings in altnames

### LINKED ISSUE #51429: Idempotence test failed for openssl_csr
##### SUMMARY

The idempotence test failed for openssl_csr module. I have heard about `force` mode, there is no such problem and I have some investigations, see the result below:

The module generates csr when this condition works:
```
if not self.check(module, perms_required=False) or self.force:
```
The self.force is False, so the not self.check() is True. self.check() returns the expression of:
```
return _check_subject(csr) and _check_extensions(csr) and _check_signature(csr)
```
Because of the check of the self.check() used with not, the upper expression must return True, or in our way 3xTrue:
```
>>> not(True and True and True) or False
False
```
When we debug the module we can see that the 2 of 3 returns the True and the one is False that ruins idempotence. Let's look at this:
```
def _check_subjectAltName(extensions):
    altnames_ext = next((ext for ext in extensions if ext.get_short_name() == b'subjectAltName'), '')
    altnames = [altname.strip() for altname in str(altnames_ext).split(',')]
    # apperently openssl returns 'IP address' not 'IP' as specifier when converting the subjectAltName to string
    # although it won't accept this specifier when generating the CSR. (https://github.com/openssl/openssl/issues/4004)
    altnames = [name if not name.startswith('IP Address:') else "IP:" + name.split(':', 1)[1] for name in altnames]
    if self.subjectAltName:
        if set(altnames) != set(self.subjectAltName) or altnames_ext.get_critical() != self.subjectAltName_critical:
            return False
    else:
        if altnames:
            return False

    return True
```

The False is returns from check `altnames`, if we look at them, there in my example will be: ` [""] `. And for the python interpreter it's not an empty list, so the condition is True:
```
>>> a = [""]
>>> if a: print(a)
... 
['']
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openssl_csr module
##### ANSIBLE VERSION

```paste below
2.6.x
2.7.x
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

Fedora 28
Ubuntu 16.04

##### STEPS TO REPRODUCE

Ensure that pyOpenSSL installed (pip install pyOpenSSL or OS package manager). Run twice the next playbook.

```yaml
---
- hosts: localhost
  vars:
    configuration:
      path: /tmp/cert.csr
      private_key_path: /tmp/key.pem
      force: false
  tasks:
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "{{ configuration.private_key_path }}"
        passphrase: "{{ configuration.passphrase | default(omit) }}"
        cipher: "{{ configuration.cipher | default(omit) }}"
        force: "{{ configuration.force | default(omit) }}"
        size: "{{ configuration.size | default(omit) }}"
        type: "{{ configuration.type | default(omit) }}"
        state: "{{ configuration.state | default(omit) }}"

    - name: Generate an OpenSSL Certificate Signing Request
      openssl_csr:
        path: "{{ configuration.path }}"
        privatekey_path: "{{ configuration.private_key_path }}"
        privatekey_passphrase: "{{ configuration.privatekey_passphrase | default(omit)  }}"
        common_name: "{{ configuration.common_name | default(omit)  }}"
        country_name: "{{ configuration.country_name | default(omit)  }}"
        digest: "{{ configuration.digest | default(omit)  }}"
        email_address: "{{ configuration.email_address | default(omit)  }}"
        extended_key_usage: "{{ configuration.extended_key_usage | default(omit)  }}"
        extended_key_usage_critical: "{{ configuration.extended_key_usage_critical | default(omit)  }}"
        locality_name: "{{ configuration.locality_name | default(omit)  }}"
        organization_name: "{{ configuration.organization_name | default(omit)  }}"
        organizational_unit_name: "{{ configuration.organizational_unit_name | default(omit)  }}"
        state_or_province_name: "{{ configuration.state_or_province_name | default(omit)  }}"
        subject_alt_name: "{{ configuration.subject_alt_name | default(omit)  }}"
        subject_alt_name_critical: "{{ configuration.subject_alt_name_critical | default(omit)  }}"
        version: "{{ configuration.version | default(omit)  }}"
        state: "{{ configuration.state | default(omit) }}"
```

##### EXPECTED RESULTS

PLAY [localhost] 

TASK [Gathering Facts] 
ok: [localhost]

TASK [Generate an OpenSSL private key] 
ok: [localhost]

TASK [Generate an OpenSSL Certificate Signing Request] 
ok: [localhost]

PLAY RECAP 
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

##### ACTUAL RESULTS

PLAY [localhost] 
TASK [Gathering Facts]
ok: [localhost]

TASK [Generate an OpenSSL private key] 
ok: [localhost]

TASK [Generate an OpenSSL Certificate Signing Request] 
changed: [localhost]

PLAY RECAP 
localhost                  : ok=3    changed=1    unreachable=0    failed=0 

```paste below

```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes idempotence bug described in #51429.

Fixes #51429.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssl_csr

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @MarkusTeufelberger @thomwiggers
(BTW: are you interested in also being notified about all, or at least some more of, the crypto modules when issues or PRs are created for them? If yes, I can create a PR to add you to the notify list.)

**Review by resmo — APPROVED** [review]
shipit

**Comment by gundalow** [comment]
@felixfontein Thank you for the fix
@resmo Thanks for the review.
Merged into `devel` for release in Ansible 2.8

**Comment by felixfontein** [comment]
Thanks everyone! I created a backport to stable-2.7 in #52024.

**Pull request merged**
