### PR TITLE
with_items flatten list of lists #5913

### PR DESCRIPTION
**Pull request by ko-zu**
undocumented behavior of with_items related with #5913, #1711 and 43d22b0

### CODE REVIEW

**Comment by mpdehaan** [comment]
Well, it's not for historical reasons.  Also I'm not too keen on the workaround as it requires some weird syntax.  I think we'd rather have a "with_unflattened" or something as an alternative lookup plugin that doesn't flatten, and just does the basic iterator.

**Comment by no2a** [comment]
FYI: putting an extra [] can be a workaround:

```
 - pip: name={{item[0]}} version={{item[1]}}
   with_items:
     - [[ 'eventlet', '0.15.2' ]]
     - [[ 'numpy', '1.6.2' ]]
```

**Comment by tmehlinger** [comment]
Using the same example, another (IMO, better) workaround:

```
- pip: name={{item['pkg']]}} version={{item['version']}}
  with_items:
    - pkg: eventlet
      version: 0.15.2
    - pkg: numpy
      version: 1.6.2
```

I landed here because one of my teammates just ran into this. I can't help but wonder... what was the intent and how is this supposed to be helpful?

**Comment by TamsynUlthara** [comment]
Just got bit by this one myself.

> I can't help but wonder... what was the intent and how is this supposed to be helpful?

I love Ansible, but stuff like this just leaves me scratching my head. There's no documentation of this behavior, and there's already a `with_flattened`, so why would anyone expect the basic `with_items` to flatten?

**Comment by nfnty** [comment]
This behavior is ridiculous. Can anyone explain why this isn't documented at the very least?

**Comment by nerdvegas** [comment]
Just got burned by this too, clearly a bug.

**Comment by brandond** [comment]
Here to complain as well.

**Pull request closed without merging**
