### PR TITLE
Update docker_swarm_info.py

### PR DESCRIPTION
**Pull request by teadur**
##### SUMMARY
Fixed typo in example

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
Please note that the ansible/ansible repository is currently in lockdown. Most modules are currently being migrated to collection repositories. PRs will need to be moved, but there will be a migration tool for that. More info will follow over the next weeks.

It's still OK to use PRs here to polish the changes, but these PRs won't be merged here. So please be patient :)

**Comment by felixfontein** [comment]
The [community.general](https://github.com/ansible-collections/community.general/) collection is the new place where the [docker_* modules](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/cloud/docker) live. The repositority is not done yet (CI isn't working properly in all cases etc.), but if you don't mind that not everything is yet perfect, you can already create a PR there.

For testing, it makes sense to checkout `community.general` into a folder `ansible_collections/community/general`. Then you can point the environment variable `ANSIBLE_COLLECTIONS_PATHS` to the directory containing `ansible_collections`, and use the modules by their new name `community.general.docker_*`. That should already work with Ansible 2.9.

Once the PR is there and works, it can be merged and then backported to stable-2.9 here, and then end up in the next 2.9.x release.

**Comment by bmillemathias** [comment]
Hi @teadur 

Could you rebase your branch please ?

Thanks

**Comment by felixfontein** [comment]
@bmillemathias @teadur rebase won't help, the PR needs to be recreated in the correct repository. This repository no longer contains the file it modifies.

**Comment by felixfontein** [comment]
Fixed in community.general. Thanks for reporting this @teadur

close_me

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible-collections/community.general/pull/608

@teadur Thanks for the contribution.

**Pull request closed without merging**
