### PR TITLE
Fix net_put module text file issue

### LINKED ISSUE #66059: Broken net_put text file
##### SUMMARY
On sending text file by `net_put` action plugin it crashing. This is because in commit cb67235eabdce502a84f5ce7e4b0aa6c8f45c226 function `_handle_template` has been renamed. Probably plugin work broken at this moment. Later in commit 9271b4e368d663b5c6db9a99bd4d89395c7799a2 parent of `net_put.py` has been changed which further worsened the situation. I'm temporary patched a `net_put` plugin in the following way:
```diff
--- net_put.py.orig	2019-11-28 21:26:14.162197153 +0300
+++ net_put.py	2019-11-28 21:14:24.902599333 +0300
@@ -210,3 +217,37 @@
             raise AnsibleError('ansible_network_os must be specified on this host')

         return network_os
+
+    def _handle_template(self, convert_data=True):
+        src = self._task.args.get('src')
+        working_path = self._get_working_path()
+
+        if os.path.isabs(src) or urlsplit('src').scheme:
+            source = src
+        else:
+            source = self._loader.path_dwim_relative(working_path, 'templates', src)
+            if not source:
+                source = self._loader.path_dwim_relative(working_path, src)
+
+        if not os.path.exists(source):
+            raise AnsibleError('path specified in src not found')
+
+        try:
+            with open(source, 'r') as f:
+                template_data = to_text(f.read())
+        except IOError as e:
+            raise AnsibleError("unable to load src file {0}, I/O error({1}): {2}".format(source, e.errno, e.strerror))
+
+        # Create a template search path in the following order:
+        # [working_path, self_role_path, dependent_role_paths, dirname(source)]
+        searchpath = [working_path]
+        if self._task._role is not None:
+            searchpath.append(self._task._role._role_path)
+            if hasattr(self._task, "_block:"):
+                dep_chain = self._task._block.get_dep_chain()
+                if dep_chain is not None:
+                    for role in dep_chain:
+                        searchpath.append(role._role_path)
+        searchpath.append(os.path.dirname(source))
+        self._templar.environment.loader.searchpath = searchpath
+        self._task.args['src'] = self._templar.template(template_data, convert_data=convert_data)
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/plugins/action/net_put.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/yellow/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- name: Сброс настроек MikroTik.
  net_put:
    src: ./templates/init-router.rsc
    protocol: sftp
    dest: /init.rsc
```

##### EXPECTED RESULTS

Uploading file to mikrotik.

##### ACTUAL RESULTS

Crashing of executing command.

```paste below

```

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/66059

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/302
*  Implement `_handle_template` in net_put ActionModule class

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

net_put

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ganeshrn** [comment]
Will retrigger CI since it failed due to `POST_FAILURE` and `TIMED_OUT`

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
This change, seems to now cause binary blob data to be rendered in the console, this is causing encoding errors for ARA and why the ios python27 job is failing. I think we need to either, make the error message more user friendly eg:

```
2020-01-13 15:22:26,910 p=10308 u=zuul n=ansible | fatal: [ios-15.6-2T]: FAILED! =>
  msg: |-
    template error while templating string: Missing end of comment tag. String: j@E8??X]dLK,1pb<1(x^(~-z"hl;<jd7lVg&*h1BrdIdQP!1sUd,!uw(^Q+Lb>+2?r  ?::RY00U$,B3zRi)$tmYg8[G$=EvO2ch"0mrlt\UF5mA0Yp
    X
    T/?FBGN/pfFw j;-MhS$%N:oX1_3GL
    DU$NZ,O+9p%S?eZ+,7QDj>6LZUz|7cZFt_\bfx\6xRO"6ju7nog%u]O0=}:br,Q"OcM|a&s^%
            oX$c<D;HT`2C\f_L
    PV*&Y}d[`&djHBzJ<34KQW
    -<q7ZWQr&V~&q7#(o_>aQzYaeIoHJ,`cYDu'a.`:,A{n*b%?S&>&w0FO~b%NrG1"v?[8u7Gs)JVYeZ3=NGp`"&pzjq1?dFT)
    vVm5Z)v;.dy0FL 5iSpj[=gT6
    860|:IB^K>.Q1tKNV>o(|5DW0z]q*9U<EW*4-  "txw_z]bqe)yr} ;1>S*    q4HJjla*nB`BLy2y~k4yE2:0Np'f}==!;,z#e?Jc2dpA&#(z%f0     jG`6x%m]RLNuy)bf{,/CGxJT_{g/fpE)s       H3d\J@^[|:V%J4k3BBa<]7XR$}Lc0a>yt@Pk*m_QnG+uv>z>_}>x6hB8m~aQSK`        ?c}bR5,*$c4/{+]
    +4kCI+ SSyUG,D+)dBsC/`C2FtW\$OgD,[ESy&$^#o?-,@9Z\5$ r5tQ9L_;vAx) B*qhlZoc_@2(c&h5T5?Ydp0@]`9Q\!np&5M}_Sic        P9>0fmnw;[(BdltQt[+yyE(-dSOz Sx`4Z/c}X{4zE0>O9n%(s7MsbCPL)'t4rV yC'Z08hQ#mxW#9ZF[w/ux^Vl`X.rNJo{;60H2+P=BCts#Zw/UMyFkU'xV
....
....
```

and / or update the ios_file : copy file with non-ascii characters to ios in template mode(Fail case) test with no_log to hide the output.

**Pull request closed without merging**
