### PR TITLE
os_port: add id parameter (fixes #28797)

### LINKED ISSUE #28797: OpenStack os_port should allow specifying port ID and not just name
##### ISSUE TYPE

 - Bug Report (or feature?)

##### COMPONENT NAME

os_port module

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /.../ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The os_port module has a single field that is used to identify ports, called `name`. It can take either a name or an ID. If you have only an ID, passing it to this field will result in the port being renamed by that ID.

There should be a way to specify the port ID, so that `name` does not have to be used.

A workaround is to use something like this (assuming `port_info` contains information about a single port as would be returned by `os_port_facts`):
```
os_port:
  name: '{{ port_info.name|default(port_info.id, true) }}'
  ...
```

### PR DESCRIPTION
**Pull request by angapov**
##### SUMMARY

Add id parameter for os_port module allowing to specify port not only by name but also by id.
This also fixes the issue with unexpectedly changing port name to its id.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

os_port
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /root/26635-ATTM-EDI/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by emonty — APPROVED** [review]
lgtm

**Comment by emonty** [comment]
shipit

**Comment by mattclay** [comment]
@angapov This PR needs to be rebased. It contains many commits unrelated to your changes.

It may help you to review the rebasing instructions here:

https://docs.ansible.com/ansible/2.5/dev_guide/developing_rebasing.html

**Comment by angapov** [comment]
@mattclay yep, sorry about that. Did it.

**Comment by angapov** [comment]
@mattclay can you merge that?

**Comment by mnaser** [comment]
shipit

**Review by mnaser — CHANGES_REQUESTED** [review]
Sorry for the delay.

**Comment by nabheet** [comment]
can someone please merge this pull request? I have have to copy this file to local modules to get this functionality. Was hoping to remove the local module before I present my implementation to the team/management. :-)

**Comment by odyssey4me** [comment]
I think that the ``name`` parameter can take either name or ID. There is no need for an additional parameter.

**Comment by nabheet** [comment]
Oh right! I don’t remember why I needed this module then. Let me try it again.

**Comment by JoelFeiner** [comment]
@nabheet It's because the lack of a separate name field prevents naming a port and retaining that name when later identifying it with ID -- that caused it to rename the port.

@odyssey4me It's broken! Please read the description of the problem before claiming it's not a problem. Thanks.

**Comment by odyssey4me** [comment]
@JoelFeiner Apologies, I admittedly looked at this PR and didn't read the original bug report's details.

**Comment by odyssey4me** [comment]
I don't think this patch is a suitable fix. All the os_* modules should ideally have a similar style of configuration and application. Currently they all can be used with uuid/name interchangably in the name field. If this is something that needs changing for a particular use-case, then I feel it should be done across all the modules so that it's consistent.

That said, I don't think it's needed. The underlying openstacksdk does not distinguish between name and ID either, so I think the issue here may be a localized bug in the way the argument is handled, rather than a need for a new argument.

I'll continue the conversation in the reported bug to understand the problem better and perhaps then we can figure out the right solution.

**Comment by Akasurde** [comment]
@emonty @mnaser What do you think about @odyssey4me's comment above ? Thanks 


needs_info

**Comment by mnaser** [comment]
@Akasurde i think it's a good point in this case, we shouldn't have id/name

**Comment by nabheet** [comment]
Sorry I forgot to reply back here - I am not sure I understand this use case but I don't need this PR for my use case. I was able to use the name/id interchangeably.

**Comment by Akasurde** [comment]
Since Id and name can be used interchangeably, I leaning towards closing this issue. Please let me know if this not the case. Thanks

needs_info

**Comment by JoelFeiner** [comment]
@Akasurde I don't understand why the problem keeps getting "forgotten". If you use the ID to look up a port, it shouldn't change the name. It's that simple. It's fine if the SDK allows you to look up by either. That's certainly convenient. But for God's sake, don't change the name when looking it up. That destroys information and is not at all obvious that that would happen.

**Pull request closed without merging**
