### PR TITLE
Document ssh_key options are in version 0.9

### PR DESCRIPTION
**Pull request by sfromm**
See issue #1425.

### CODE REVIEW

**Comment by mpdehaan** [comment]
got it thanks!, will be in next rebuild

**Comment by jpmens** [comment]
This is _not consistent_ with the way we indicate versions in DOCUMENTATION.

**Comment by sfromm** [comment]
@jpmens Sorry about that.  I should have double-checked DOCUMENTATION.yaml.  I made a fix, but just saw that you already submitted a PR.  Thanks!

**Comment by jpmens** [comment]
All is forgiven, @sfromm :-)
And, as you're probably aware of, `./hacking/module_formatter.py -G` is your friend -- it outputs the boilerplate.

**Pull request merged**
