### PR TITLE
Update intro_installation.rst

### PR DESCRIPTION
**Pull request by gsker**
There is no package called "apt-add-repository". Removed that line and put a note in about where that command comes from. It isn't on all my systems.

### CODE REVIEW

**Comment by gsker** [comment]
Did I do this right? It's hard for me to tell if this actually got submitted to the upstream.

**Comment by mpdehaan** [comment]
Pull request received, thanks!

**Comment by mpdehaan** [comment]
(In list of things to fact check)

**Comment by gsker** [comment]
Sorry I should have included that:
apt-add-repository is in precise here:
   http://packages.ubuntu.com/precise/all/python-software-properties/filelist
but not in trusty here:
   http://packages.ubuntu.com/trusty/all/python-software-properties/filelist

No apt-add-repository here:
   http://packages.ubuntu.com/precise/all/software-properties-common/filelist
But it is here:
   http://packages.ubuntu.com/trusty/all/software-properties-common/filelist

It's also here in wheezy (stable):
   https://packages.debian.org/wheezy/all/python-software-properties/filelist
And here in sid (unstable):
   https://packages.debian.org/sid/all/software-properties-common/filelist

**Comment by mpdehaan** [comment]
Should be fixed in current devel, instructions changed a bit since we are now also hosting our own PPA.

Thanks!

**Pull request closed without merging**
