### PR TITLE
docker_container: show warnings, fix/improve tests

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
I noticed that the `docker_container` tests don't work anymore on my machine, more specifically, the `blkio_weight` idempotency broke. I found out that container creation and updating actually returns warnings (which contained a warning that this isn't supported with my kernel), so I added a mechanism to return these warnings, and updated the tests to accept that warning too.

I also fixes some warnings appearing with the tests.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by felixfontein** [comment]
Timing stats (`profile_tasks`) from `docker_container` tests on my machine:
```
PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=541  changed=282  unreachable=0    failed=0    skipped=19   rescued=0    ignored=3   

Thursday 07 March 2019  08:26:04 +0100 (0:00:00.019)       0:07:00.475 ******** 
=============================================================================== 
dns_servers (changed order) -------------------------------------------------------------------------------------------------------------- 11.65s
dns_search_domains (different order) ----------------------------------------------------------------------------------------------------- 11.62s
entrypoint (change order idempotency) ---------------------------------------------------------------------------------------------------- 11.53s
Make sure all containers are removed ------------------------------------------------------------------------------------------------------ 3.31s
cleanup ----------------------------------------------------------------------------------------------------------------------------------- 3.30s
start helpers ----------------------------------------------------------------------------------------------------------------------------- 3.05s
cleanup ----------------------------------------------------------------------------------------------------------------------------------- 2.36s
start helpers ----------------------------------------------------------------------------------------------------------------------------- 1.95s
Stop container ---------------------------------------------------------------------------------------------------------------------------- 1.95s
cleanup ----------------------------------------------------------------------------------------------------------------------------------- 1.86s
cleanup ----------------------------------------------------------------------------------------------------------------------------------- 1.70s
published_ports -- port range (different range) ------------------------------------------------------------------------------------------- 1.69s
memory_swappiness (change) ---------------------------------------------------------------------------------------------------------------- 1.68s
log_options (more log options) ------------------------------------------------------------------------------------------------------------ 1.65s
dict (change, strict) --------------------------------------------------------------------------------------------------------------------- 1.63s
groups (more groups) ---------------------------------------------------------------------------------------------------------------------- 1.63s
exposed_ports (more ports) ---------------------------------------------------------------------------------------------------------------- 1.63s
recreate (started, recreate) -------------------------------------------------------------------------------------------------------------- 1.62s
set(dict) (change, strict) ---------------------------------------------------------------------------------------------------------------- 1.62s
mac_address (change) ---------------------------------------------------------------------------------------------------------------------- 1.58s
```
Doesn't look like there's a chance of much improvement. The `entrypoint (change order idempotency)` entry looks suspicious, but everything else is already pretty fast (or at least not obviously too slow).

**Comment by felixfontein** [comment]
Does anyone mind if I merge this? Question about the warnings: should they be prefixed with something like `Warning from docker daemon: `, or should they just be the warning send from the docker daemon without any changes?

**Comment by felixfontein** [comment]
I added a prefix `Docker warning: `.

**Comment by felixfontein** [comment]
ready_for_review

**Comment by WojciechowskiPiotr** [comment]
shipit

I think it may be good to extend the Docker warnings display to all modules, maybe part of Docker library? Enabled/Disabled by config option etc.

**Comment by felixfontein** [comment]
I don't think there is a way to easily enable them for everything. But we can add some helper functions for this. Allowing to disable them is probably ok, though I don't know who actually wants to do that (except for very specific warnings), since in general new warnings can pop up with every new docker daemon version and would explain why suddenly something stops working.

**Comment by felixfontein** [comment]
I've refactored this a little so now there's a generic function for reporting warnings from a result. By default it looks into `result['Warnings']` (with all kind of checks), but the exact path to warnings can be configured.

Adding warnings to other docker_* modules can be done in other PRs I think.

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
@WojciechowskiPiotr thanks for reviewing!
@willthames thanks for merging!

**Pull request merged**
