### PR TITLE
Deprecate module in collection: allow removal date in documentation, make validate-modules ensure version and date match

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Another follow-up to #67684. Right now, modules can only be deprecated in documentation with a removal version, which must be form a fixed set of Ansible version numbers.

This PR allows to also specify a removal date, and adds validation to make sure that date and version match the ones in meta/runtime.yml.

This also fixes that module deprecation version numbers are always compared to Ansible versions, and are in fact resticted to a fixed list of Ansible versions.

CC @nitzmahone

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ansible-test

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
I also added the last missing deprecation by date (I know of): deprecation of plugin options. And I added a changelog for deprecation by date (#68177 had none).

**Comment by felixfontein** [comment]
This PR doesn't update the docs .rst generator, since I'm not sure whether the current one is still used, resp. whether antsibull will completely replace it.

**Review by nitzmahone — APPROVED** [review]

**Review by mattclay — APPROVED** [review]

**Comment by felixfontein** [comment]
@nitzmahone @mattclay thanks a lot for reviewing and merging!

**Pull request merged**
