### PR TITLE
aci_interface_selector_to_switch_policy_leaf_profile module

### PR DESCRIPTION
**Pull request by brunocalogero**
##### SUMMARY

Created new module to add ACI Fabric access policy switch policy interface profile selector (infra:RsAccPortP).
This is a WIP, integration testing still needed.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

aci_interface_selector_to_switch_policy_leaf_profile

##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by brunocalogero** [comment]
Naming of module will most likely need revisions

**Comment by dagwieers** [comment]
cc @rsmeyers @nilloBE Please test and review !

**Comment by brunocalogero** [comment]
integration tests + examples in process of being added

**Review by dagwieers — APPROVED** [review]
LGTM

**Comment by LucRobalo** [comment]
Hello, is this module supposed to be used to create a interface selector for fex ? the option seems to be a copy paste from the static path module, can we help with this ?

**Comment by dagwieers** [comment]
@LucRobalo We accept contributions. https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general_aci.html

**Comment by LucRobalo** [comment]
Do you know how I can contact the lead for this module to check if this is the one responsible for the function? Or I can contact ramses from cisco and check with him

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rsmeyers** [comment]
Don’t think the fex use case is covered, will check Monday

**Comment by LucRobalo** [comment]
Yes clear there is a copy paste in the doc for the static path, shouldn't be too hard to cover the fex interface selector use case

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LucRobalo** [comment]
Hello Ramses,

from looking at the api inspector I see the change is on two level, the url used and the payload :

accportprof is replaced with fexprof

I don't think the variable interface_type is used, maybe it can be reused ?

Regards,

Luc

________________________________
De : Luc Robalo Marques <lrobalo_marques@hotmail.com>
Envoyé : samedi 23 février 2019 19:20
À : ansible/ansible; ansible/ansible
Cc : Mention
Objet : Re: [ansible/ansible] aci_interface_selector_to_switch_policy_leaf_profile module (#34098)

Yes clear there is a copy paste in the doc for the static path, shouldn't be too hard to cover the fex interface selector use case

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LucRobalo** [comment]
need to check the code for ACIModule but am I correct in stating that the chage required is :


aci_rn='infra/accportprof-{0}'.format(leaf_interface_profile),

->
if interface_type is "fex":
 aci_rn='infra/fexprof-{0}'.format(leaf_interface_profile)
else
  aci_rn='infra/accportprof-{0}'.format(leaf_interface_profile)

________________________________
De : Luc Robalo Marques <lrobalo_marques@hotmail.com>
Envoyé : lundi 25 février 2019 09:10
À : ansible/ansible; ansible/ansible
Cc : Mention
Objet : RE: [ansible/ansible] aci_interface_selector_to_switch_policy_leaf_profile module (#34098)

Hello Ramses,

from looking at the api inspector I see the change is on two level, the url used and the payload :

accportprof is replaced with fexprof

I don't think the variable interface_type is used, maybe it can be reused ?

Regards,

Luc

________________________________
De : Luc Robalo Marques <lrobalo_marques@hotmail.com>
Envoyé : samedi 23 février 2019 19:20
À : ansible/ansible; ansible/ansible
Cc : Mention
Objet : Re: [ansible/ansible] aci_interface_selector_to_switch_policy_leaf_profile module (#34098)

Yes clear there is a copy paste in the doc for the static path, shouldn't be too hard to cover the fex interface selector use case

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LucRobalo** [comment]
if interface_type == "fex":
        aci_rn_value='infra/fexprof-{0}'.format(leaf_interface_profile)
    else: aci_rn_value='infra/accportprof-{0}'.format(leaf_interface_profile)

    aci = ACIModule(module)
    aci.construct_url(
        root_class=dict(
            aci_class='infraAccPortP',
            aci_rn=aci_rn_value,
            module_object=leaf_interface_profile,
            target_filter={'name': leaf_interface_profile},
        ),
        subclass_1=dict(
            aci_class='infraHPortS',
            # NOTE: normal rn: hports-{name}-typ-{type}, hence here hardcoded to range for purposes of module
            aci_rn='hports-{0}-typ-range'.format(access_port_selector),
            module_object=access_port_selector,
            target_filter={'name': access_port_selector},
        ),
        child_classes=['infraPortBlk', 'infraRsAccBaseGrp'],
    )


________________________________
De : Luc Robalo Marques <lrobalo_marques@hotmail.com>
Envoyé : lundi 25 février 2019 09:10
À : ansible/ansible; ansible/ansible
Cc : Mention
Objet : RE: [ansible/ansible] aci_interface_selector_to_switch_policy_leaf_profile module (#34098)

Hello Ramses,

from looking at the api inspector I see the change is on two level, the url used and the payload :

accportprof is replaced with fexprof

I don't think the variable interface_type is used, maybe it can be reused ?

Regards,

Luc

________________________________
De : Luc Robalo Marques <lrobalo_marques@hotmail.com>
Envoyé : samedi 23 février 2019 19:20
À : ansible/ansible; ansible/ansible
Cc : Mention
Objet : Re: [ansible/ansible] aci_interface_selector_to_switch_policy_leaf_profile module (#34098)

Yes clear there is a copy paste in the doc for the static path, shouldn't be too hard to cover the fex interface selector use case

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dagwieers** [comment]
@LucRobalo Please open a new issue when you want to discuss something new. And open a PR when you have a contribution. The current issue is closed and not tracked.

**Comment by LucRobalo** [comment]
OK thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LucRobalo** [comment]
Good afternoon,

PR opened :

Pull request done derived aci_access_port_to_interface_policy_leaf_profile for fex port… #53394

Regards,

Luc

________________________________
De : Dag Wieers <notifications@github.com>
Envoyé : lundi 25 février 2019 12:49
À : ansible/ansible
Cc : LucRobalo; Mention
Objet : Re: [ansible/ansible] aci_interface_selector_to_switch_policy_leaf_profile module (#34098)


@LucRobalo<https://github.com/LucRobalo> Please open a new issue when you want to discuss something new. And open a PR when you have a contribution. The current issue is closed and not tracked.

**Pull request merged**
