### PR TITLE
returns xml as a display option to junos_command

### LINKED ISSUE #21823: junos_command: format issue (missing aliases & xml)
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
junos_command

##### ANSIBLE VERSION
```
b8d308d919c89d86dc72d4fd62335b9f948544f1
```

##### SUMMARY

Two related issues due to https://github.com/ansible/ansible/commit/02d2b753db72ef925dac61b376565a92bcd44799#diff-d466f62c4e21d273efccee8df02bb034L225 refactor

1) Missing aliases for `aliases=['format', 'output']` - which is simple enough and I'll fix shortly

2) 
However this exposes that `xml` has been missed

Code as it stands returns
`"msg": "value of display must be one of: text,json, got: xml"`

Updating choices=['text', 'json'] to include `xml` gives:
```
 [WARNING]: Removed unexpected internal key in module return: _ansible_parsed = False

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_CHppt1/ansible_module_junos_command.py", line 250, in <module>
    main()
  File "/tmp/ansible_CHppt1/ansible_module_junos_command.py", line 208, in main
    commands = parse_commands(module, warnings)
  File "/tmp/ansible_CHppt1/ansible_module_junos_command.py", line 164, in parse_commands
    commands = transform(module.params['commands'])
  File "/tmp/ansible_CHppt1/ansible_modlib.zip/ansible/module_utils/network_common.py", line 150, in __call__
  File "/tmp/ansible_CHppt1/ansible_modlib.zip/ansible/module_utils/network_common.py", line 135, in __call__
ValueError: output must be one of text, json, got xml

fatal: [vsrx01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_CHppt1/ansible_module_junos_command.py\", line 250, in <module>\n    main()\n  File \"/tmp/ansible_CHppt1/ansible_module_junos_command.py\", line 208, in main\n    commands = parse_commands(module, warnings)\n  File \"/tmp/ansible_CHppt1/ansible_module_junos_command.py\", line 164, in parse_commands\n    commands = transform(module.params['commands'])\n  File \"/tmp/ansible_CHppt1/ansible_modlib.zip/ansible/module_utils/network_common.py\", line 150, in __call__\n  File \"/tmp/ansible_CHppt1/ansible_modlib.zip/ansible/module_utils/network_common.py\", line 135, in __call__\nValueError: output must be one of text, json, got xml\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
The key line here being `ValueError: output must be one of text, json, got xml` from `module_utils/network_common.py`

### PR DESCRIPTION
**Pull request by privateip**
The display option xml as accidentially removed from the display
argument.  This patch adds xml back as an option.

fixes #21823

### CODE REVIEW

**Comment by gundalow** [comment]
So the above PR has moving things forward, though I don't believe we are returning the XML correctly

```yaml
  - name: test gt operator
    junos_command:
      commands:
        - show version
        - show interfaces fxp0
      display: xml 
    #    wait_for:
    #     - "result[1].interface-information.physical-interface.mtu gt 1500"
      provider: "{{ netconf }}"
    register: result

 - fail:
     msg: "{{ result }}"
 

```

Returns
```yaml

    "msg": {
        "changed": false, 
        "stdout": [
            "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">", 
            "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">\n    <interface-information xmlns=\"http://xml.juniper.net/junos/15.1X49/junos-interface\" junos:style=\"normal\">\n            \n            <traffic-statistics junos:style=\"brief\">\n                <traffic-statistics junos:style=\"brief\">"
        ], 
        "stdout_lines": [
            [
                "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">"
            ], 
            [
                "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">", 
                "    <interface-information xmlns=\"http://xml.juniper.net/junos/15.1X49/junos-interface\" junos:style=\"normal\">", 
                "            ", 
                "            <traffic-statistics junos:style=\"brief\">", 
                "                <traffic-statistics junos:style=\"brief\">"
            ]
        ], 
        "warnings": [
            "argument provider has been deprecated and will be removed in a future version"
        ]
    }
```


Where as, if I run those commands directly
```
nsible@vsrx01> show version 
Hostname: vsrx01
Model: vSRX
Junos: 15.1X49-D15.4
JUNOS Software Release [15.1X49-D15.4]


ansible@vsrx01> show interfaces fxp0   
Physical interface: fxp0, Enabled, Physical link is Up
  Interface index: 65, SNMP ifIndex: 1
  Type: Ethernet, Link-level type: Ethernet, MTU: 1514, Speed: 1000mbps
  Device flags   : Present Running
  Interface flags: SNMP-Traps
  Link type      : Full-Duplex
  Current address: 52:54:00:bd:29:0e, Hardware address: 52:54:00:bd:29:0e
  Last flapped   : 2016-08-17 22:31:27 UTC (27w0d 22:38 ago)
    Input packets : 624099
    Output packets: 269277

  Logical interface fxp0.0 (Index 4) (SNMP ifIndex 13)
    Flags: Up SNMP-Traps Encapsulation: ENET2
    Input packets : 624079
    Output packets: 269277
    Protocol inet, MTU: 1500
      Flags: Sendbcast-pkt-to-re, Is-Primary
      Addresses, Flags: Is-Preferred Is-Primary
        Destination: 172.26.4/24, Local: 172.26.4.28, Broadcast: 172.26.4.255

ansible@vsrx01> 

```

**Comment by privateip** [comment]
The correct command to run is `show version | display xml' or 'show interfaces fxp0 | display xml`

**Comment by gundalow** [comment]
```
show version | display xml 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <software-information>
        <host-name>vsrx01</host-name>
        <product-model>vSRX</product-model>
        <product-name>vsrx</product-name>
        <junos-version>15.1X49-D15.4</junos-version>
        <package-information>
            <name>junos</name>
            <comment>JUNOS Software Release [15.1X49-D15.4]</comment>
        </package-information>
    </software-information>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>



ansible@vsrx01> show interfaces fxp0 | display xml                                                                    
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <interface-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-interface" junos:style="normal">
        <physical-interface>
            <name>fxp0</name>
            <admin-status junos:format="Enabled">up</admin-status>
            <oper-status>up</oper-status>
            <local-index>65</local-index>
            <snmp-index>1</snmp-index>
            <if-type>Ethernet</if-type>
            <link-level-type>Ethernet</link-level-type>
            <mtu>1514</mtu>
            <speed>1000mbps</speed>
            
            <if-device-flags>
                <ifdf-present/>
                <ifdf-running/>
            </if-device-flags>
            <ifd-specific-config-flags>
            </ifd-specific-config-flags>
            <if-config-flags>
                <iff-snmp-traps/>
            </if-config-flags>
            <link-type>Full-Duplex</link-type>
            <if-media-flags>
                <internal-flags>0x4</internal-flags>
   
...

```

**Comment by gundalow** [comment]
So it seems that the secondary issue is due to truncating the data returned from the device.

**Comment by Qalthos** [comment]
Unless I'm mistaken, this still doesn't restore the documentation for the `display` argument.

**Comment by gundalow** [comment]
@Qalthos Good spot the DOCUMENTATION block needs updating (and ensure the `alias:` are listed)

**Review by gundalow — CHANGES_REQUESTED** [review]
1) DOCUMENTATION needs updating

**Comment by gundalow** [comment]
This seems to have changed the format of the data returned.

In 2.2 we could do
```
wait_for:
  - "result[1].interface-information.physical-interface.mtu gt 1500"
```

It seems like `rpc-reply` has been added back, which undoes this https://github.com/ansible/test-network-modules/commit/eb6524a657b06f0e2fb18faaff656bf1b1ea27f3#diff-c36593d4ed3515ab7e5d60038952cb17


With this PR I get
```yaml
    "msg": {
        "changed": false, 
        "stdout": [
            "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">\n    <software-information>\n        <host-name>vsrx01</host-name>\n        <product-model>vSRX</product-model>\n        <product-name>vsrx</product-name>\n        <junos-version>15.1X49-D15.4</junos-version>\n        <package-information>\n            <name>junos</name>\n            <comment>JUNOS Software Release [15.1X49-D15.4]</comment>\n        </package-information>\n    </software-information>\n    <cli>\n        <banner></banner>\n    </cli>\n</rpc-reply>", 
            "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">\n    <interface-information xmlns=\"http://xml.juniper.net/junos/15.1X49/junos-interface\" junos:style=\"normal\">\n        <physical-interface>\n            <name>fxp0</name>\n            <admin-status junos:format=\"Enabled\">up</admin-status>\n            <oper-status>up</oper-status>\n            <local-index>65</local-index>\n            <snmp-index>1</snmp-index>\n            <if-type>Ethernet</if-type>\n            <link-level-type>Ethernet</link-level-type>\n            <mtu>1514</mtu>\n            <speed>1000mbps</speed>\n            \n            <if-device-flags>\n                <ifdf-present/>\n                <ifdf-running/>\n            </if-device-flags>\n            <ifd-specific-config-flags>\n            </ifd-specific-config-flags>\n            <if-config-flags>\n                <iff-snmp-traps/>\n            </if-config-flags>\n            <link-type>Full-Duplex</link-type>\n            <if-media-flags>\n                <internal-flags>0x4</internal-flags>\n            </if-media-flags>\n            <current-physical-address junos:format=\"MAC 52:54:00:bd:29:0e\">52:54:00:bd:29:0e</current-physical-address>\n            <hardware-physical-address junos:format=\"MAC 52:54:00:bd:29:0e\">52:54:00:bd:29:0e</hardware-physical-address>\n            <interface-flapped junos:seconds=\"16490568\">2016-08-17 22:31:27 UTC (27w1d 20:42 ago)</interface-flapped>\n            <traffic-statistics junos:style=\"brief\">\n                <input-packets>632107</input-packets>\n                <output-packets>281021</output-packets>\n            </traffic-statistics>\n            <logical-interface>\n                <name>fxp0.0</name>\n                <local-index>4</local-index>\n                <snmp-index>13</snmp-index>\n                <if-config-flags>\n                    <iff-up/>\n                    <iff-snmp-traps/>\n                </if-config-flags>\n                <encapsulation>ENET2</encapsulation>\n                <traffic-statistics junos:style=\"brief\">\n                    <input-packets>632087</input-packets>\n                    <output-packets>281023</output-packets>\n                </traffic-statistics>\n                <filter-information>\n                </filter-information>\n                <address-family>\n                    <address-family-name>inet</address-family-name>\n                    <mtu>1500</mtu>\n                    <address-family-flags>\n                        <ifff-is-primary/>\n                        <ifff-sendbcast-pkt-to-re/>\n                    </address-family-flags>\n                    <interface-address>\n                        <ifa-flags>\n                            <ifaf-current-preferred/>\n                            <ifaf-current-primary/>\n                        </ifa-flags>\n                        <ifa-destination>172.26.4/24</ifa-destination>\n                        <ifa-local>172.26.4.28</ifa-local>\n                        <ifa-broadcast>172.26.4.255</ifa-broadcast>\n                    </interface-address>\n                </address-family>\n            </logical-interface>\n        </physical-interface>\n    </interface-information>\n    <cli>\n        <banner></banner>\n    </cli>\n</rpc-reply>"
        ], 
        "stdout_lines": [
            [
                "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">", 
                "    <software-information>", 
                "        <host-name>vsrx01</host-name>", 
                "        <product-model>vSRX</product-model>", 
                "        <product-name>vsrx</product-name>", 
                "        <junos-version>15.1X49-D15.4</junos-version>", 
                "        <package-information>", 
                "            <name>junos</name>", 
                "            <comment>JUNOS Software Release [15.1X49-D15.4]</comment>", 
                "        </package-information>", 
                "    </software-information>", 
                "    <cli>", 
                "        <banner></banner>", 
                "    </cli>", 
                "</rpc-reply>"
            ], 
            [
                "<rpc-reply xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\">", 
                "    <interface-information xmlns=\"http://xml.juniper.net/junos/15.1X49/junos-interface\" junos:style=\"normal\">", 
                "        <physical-interface>", 
                "            <name>fxp0</name>", 
                "            <admin-status junos:format=\"Enabled\">up</admin-status>", 
                "            <oper-status>up</oper-status>", 
                "            <local-index>65</local-index>", 
                "            <snmp-index>1</snmp-index>", 
                "            <if-type>Ethernet</if-type>", 
                "            <link-level-type>Ethernet</link-level-type>", 
                "            <mtu>1514</mtu>", 
                "            <speed>1000mbps</speed>", 
                "            ", 
                "            <if-device-flags>", 
                "                <ifdf-present/>", 
                "                <ifdf-running/>", 
                "            </if-device-flags>", 
                "            <ifd-specific-config-flags>", 
                "            </ifd-specific-config-flags>", 
                "            <if-config-flags>", 
                "                <iff-snmp-traps/>", 
                "            </if-config-flags>", 
                "            <link-type>Full-Duplex</link-type>", 
                "            <if-media-flags>", 
                "                <internal-flags>0x4</internal-flags>", 
                "            </if-media-flags>", 
                "            <current-physical-address junos:format=\"MAC 52:54:00:bd:29:0e\">52:54:00:bd:29:0e</current-physical-address>", 
                "            <hardware-physical-address junos:format=\"MAC 52:54:00:bd:29:0e\">52:54:00:bd:29:0e</hardware-physical-address>", 
                "            <interface-flapped junos:seconds=\"16490568\">2016-08-17 22:31:27 UTC (27w1d 20:42 ago)</interface-flapped>", 
                "            <traffic-statistics junos:style=\"brief\">", 
                "                <input-packets>632107</input-packets>", 
                "                <output-packets>281021</output-packets>", 
                "            </traffic-statistics>", 
                "            <logical-interface>", 
                "                <name>fxp0.0</name>", 
                "                <local-index>4</local-index>", 
                "                <snmp-index>13</snmp-index>", 
                "                <if-config-flags>", 
                "                    <iff-up/>", 
                "                    <iff-snmp-traps/>", 
                "                </if-config-flags>", 
                "                <encapsulation>ENET2</encapsulation>", 
                "                <traffic-statistics junos:style=\"brief\">", 
                "                    <input-packets>632087</input-packets>", 
                "                    <output-packets>281023</output-packets>", 
                "                </traffic-statistics>", 
                "                <filter-information>", 
                "                </filter-information>", 
                "                <address-family>", 
                "                    <address-family-name>inet</address-family-name>", 
                "                    <mtu>1500</mtu>", 
                "                    <address-family-flags>", 
                "                        <ifff-is-primary/>", 
                "                        <ifff-sendbcast-pkt-to-re/>", 
                "                    </address-family-flags>", 
                "                    <interface-address>", 
                "                        <ifa-flags>", 
                "                            <ifaf-current-preferred/>", 
                "                            <ifaf-current-primary/>", 
                "                        </ifa-flags>", 
                "                        <ifa-destination>172.26.4/24</ifa-destination>", 
                "                        <ifa-local>172.26.4.28</ifa-local>", 
                "                        <ifa-broadcast>172.26.4.255</ifa-broadcast>", 
                "                    </interface-address>", 
                "                </address-family>", 
                "            </logical-interface>", 
                "        </physical-interface>", 
                "    </interface-information>", 
                "    <cli>", 
                "        <banner></banner>", 
                "    </cli>", 
                "</rpc-reply>"
            ]
        ], 
        "warnings": [
            "argument provider has been deprecated and will be removed in a future version"
        ]
    }
}

```

**Pull request merged**
