### PR TITLE
Add version_added to route53 option 'state' - fixes #24306

### LINKED ISSUE #24306: The documentation for route53 module is ahead of time
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

route53

##### ANSIBLE VERSION

```
2.3.0.0
```

##### SUMMARY

The documentation for route53 module mentions features that are not released yet and will be available in Ansible 2.4.0.0.

##### STEPS TO REPRODUCE

Go to: http://docs.ansible.com/ansible/route53_module.html

```yaml

```

##### EXPECTED RESULTS

The documentation should cover only the features in the current stable version and not the ones that are not yet released.

##### ACTUAL RESULTS

The documentation mentions things like "state" parameter which are not available in Ansible 2.3.0.0.

```

```

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Fixes #24306

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/route53.py

##### ANSIBLE VERSION
```
2.4.0
```

### CODE REVIEW

**Comment by sivel** [comment]
I'm not sure what is the right change here.

Technically, `version_added` would imply that neither `state` nor `command` was added until 2.4.

We don't have an explicit way to describe the change in the alias, other than indicating that in the description of the argument, as opposed to using `version_added`.

See:
* https://github.com/ansible/ansible/commit/1ad55ec9de630ca543bb2a59adf44af4e6d97820

**Comment by s-hertel** [comment]
@sivel Oh. Hm. I didn't notice that. I'll close this?

**Comment by sivel** [comment]
I think we still need a doc update here.  But I think it needs to state something just like that lininfile commit I referenced.

So that it mentions that prior to 2.4, the argument was "command", not "state"

**Comment by s-hertel** [comment]
Or I could add to the description that prior to 2.4 only `command` works and remove version_added.

**Review by ryansb — APPROVED** [review]

**Pull request merged**
