### PR TITLE
Remove python-keyczar dependency

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

`python-keyczar` is no longer needed since accelerate mode has been removed

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
`ansible.spec`
`PKGBUILD`

##### ANSIBLE VERSION

```
2.6
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by abadger** [comment]
+1  Looks like we could remove keyczar from the container images as well (dockerfiles: test/utils/docker/ )

**Comment by samdoran** [comment]
I'll add that to this PR.

**Comment by mattclay** [comment]
The containers are currently shared across branches, but we don't yet have a good way to manage differing requirements. I'm going to be making some changes to how we manage the containers, including moving them out of the repo. So lets hold off on updating these for now. I'll add python-keyczar to my list to review when the containers do get updated.

**Comment by samdoran** [comment]
Sure thing. I'll put the package back in to the containers.

**Comment by samdoran** [comment]
rebuild_merge

**Pull request merged**
