### PR TITLE
Adding redhat subscription status module

### PR DESCRIPTION
**Pull request by Deathice**
##### SUMMARY
We create this module for check the redhat subscription status, if the redhat is subscribed or not.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
redhat_subsc_status

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel b53c16a831) last updated 2018/04/19 16:58:02 (GMT -600)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kevyn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kevyn/Documents/scripts/ansible/modules/ansible-1/lib/ansible
  executable location = /home/kevyn/Documents/scripts/ansible/modules/ansible-1/bin/ansible
  python version = 3.6.5 (default, Apr 12 2018, 22:45:43) [GCC 7.3.1 20180312]

```

##### ADDITIONAL INFORMATION

```
Redhat is not subscribed:

***********************************
RAW OUTPUT

{"invocation": {"module_args": {"status": true, "export_csv": null}}, "changed": false, "meta": {"status": "OK", "response": {"Subscription_status": "False"}}}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "invocation": {
        "module_args": {
            "export_csv": null, 
            "status": true
        }
    }, 
    "meta": {
        "response": {
            "Subscription_status": "False"
        }, 
        "status": "OK"
    }
}

Redhat is subscribed:

***********************************
RAW OUTPUT

{"invocation": {"module_args": {"status": true, "export_csv": null}}, "changed": false, "meta": {"status": "OK", "response": {"Subscription_status": "False"}}}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "invocation": {
        "module_args": {
            "export_csv": null, 
            "status": true
        }
    }, 
    "meta": {
        "response": {
            "Subscription_status": "True"
        }, 
        "status": "OK"
    }
}

```

### CODE REVIEW

**Comment by Deathice** [comment]
The sanity checks are solved.

Please review.

**Comment by maxamillion** [comment]
This seems better suited as a role, I don't see any real reason this needs to be a module. I'm open to discussion though.

**Comment by kahowell** [comment]
> This seems better suited as a role, I don't see any real reason this needs to be a module. I'm open to discussion though.

I agree.

Either way, it would be great to know a little more about the intended use-case. @Deathice ?

**Comment by Deathice** [comment]
Thanks for yours answers, i create this module, because the redhat_subscription module cant get the status of the current available subscription and is only used for subscribe a new server, but if the server is already subscribed?, i need create a role for get this status?.

The redhat_subscription module, can have a status argument for get this for inventory redhat subscription status:

+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Current

**Comment by maxamillion** [comment]
I still don't see the argument for the module use case here, the potential role to solve this use case can use `set_fact` to provide the status to the rest of the playbook.

**Comment by Deathice** [comment]
Ok, thansk for your answer.

Best regards.

**Comment by maxamillion** [comment]
Thank you for your submission, I earnestly do not mean to deter your contributions or any future ones but I think in the service of following the [Ansible module development guidelines](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules.html#should-you-develop-a-module) this is best suited as a role.

**Pull request closed without merging**
