### PR TITLE
Add update_policy to os_image module

### PR DESCRIPTION
**Pull request by jovial**
##### SUMMARY
Adds a new option, `update_policy`, to the os_image module. This controls the behavior when
an image with the same name already exists. The three options are delete, rename, and keep_existing.

- `delete` will ensure that only one image with that name exists
- `rename` will create a backup of the old image
- `keep_existing` replicates the behavior before `update_policy` was added

The renaming behavior is similar to using the copy module with the backup option, although we use the
image's creation timestamp as the extension. This makes it easier to differentiate the images.

The rationale is that this change will make it easier to keep the image store tidy.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
os_image

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (os-image-update-policy 231fa0d5de) last updated 2018/08/21 11:49:34 (GMT +100)                                                                         
  config file = None
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/code/ansible/lib/ansible
  executable location = /home/will/code/ansible/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### ADDITIONAL INFORMATION
Command output remains the same.

### CODE REVIEW

**Comment by mnaser** [comment]
@jovial do you think you could take sometime to fix those small listing issues?

**Comment by mnaser** [comment]
@emonty doesn't shade already kinda handle the md5sum stuff?

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by Akasurde** [comment]
Closing as per above.

**Pull request closed without merging**
