### PR TITLE
Add new command GetVolumeInventory / GetSessions / GetVirtualMedia

### PR DESCRIPTION
**Pull request by renxulei**
##### SUMMARY

Add new commands GetVolumeInventory / GetSessions / GetVirtualMedia in redfish_facts.py, new commands gather details about volume, session, and virtual media.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

redfish_utils.py
redfish_facts.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by renxulei** [comment]
@billdodd  could you help to review this PR? the code changes are exactly same with PR#55145 you reviewed before, thanks!

**Review by billdodd — COMMENTED** [review]
@renxulei I reviewed and tested the code. It looks code.

One additional request: Could you also an example for each of the 3 new commands in the EXAMPLES section of redfish_facts.py?

**Comment by renxulei** [comment]
@billdodd I added examples as you suggested, please help to review it, thanks!

**Review by billdodd — APPROVED** [review]
Thanks for adding the examples. Looks good.

shipit

**Comment by jose-delarosa** [comment]
Looks good @renxulei, thank you for your contribution.

shipit

**Comment by renxulei** [comment]
@billdodd Could you help to approve it again? I just rebased the PR according to the request of ansibot, no other changes, thanks!

**Review by billdodd — APPROVED** [review]
Re-reviewed and tested after rebase. Looks good. Thanks.

shipit

**Comment by renxulei** [comment]
@jose-delarosa @samerhaj this should be ready to go, please help to confirm it, thanks!

**Comment by jose-delarosa** [comment]
shipit

**Comment by samerhaj** [comment]
shipit

**Comment by renxulei** [comment]
@jctanner thank you to merge this.  @billdodd @jose-delarosa @samerhaj thank you all to review this.

**Pull request merged**
