### PR TITLE
Update fileglob.py

### LINKED ISSUE #45557: `fileglob` plugin docs have wrong return value
##### SUMMARY

[`fileglob` plugin's docs](https://docs.ansible.com/ansible/devel/plugins/lookup/fileglob.html) say:

```
RETURN = """
  _raw:
    description:
      - content of file(s)
"""
```

But, as I read it, this is wrong. The list of files is returned not the contents (although that could be useful, perhaps behind an option).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

fileglob

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 69bbd32264) last updated 2018/09/10 22:57:28 (GMT +200)
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### CONFIGURATION

```paste below
none
```

##### OS / ENVIRONMENT

Arch linux

### PR DESCRIPTION
**Pull request by nkakouros**
Closes #45557

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ANSIBLE VERSION

```paste below

```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
@tterranigma this is a great candidate to be backported so the existing docs are updated and not just the devel ones. There's a guide on how to do this here https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process.

**Comment by nkakouros** [comment]
@jborean93 I created a PR to backport this to 2.6. How many versions back do I have to do this for?

**Comment by samccann** [comment]
@tterranigma can you also create a pr to backport to 2.7?

**Comment by nkakouros** [comment]
@samccann Done, generally to which versions does one backport? As many as possible? Only the latest stable?

**Comment by jborean93** [comment]
@tterranigma, typically people aim for the past 2 stable releases which in this case will be stable-2.7 and stable-2.6. Technically we still accept backports to stable-2.5 until 2.8 is out but it is designed just for security fixes.

**Pull request merged**
