### PR TITLE
Add a k8s rollback module

### LINKED ISSUE #52046: k8s support Deployment(Config) rollouts and rollbacks
##### SUMMARY

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

In the same way that the [`k8s_scale` module](https://docs.ansible.com/ansible/latest/modules/k8s_scale_module.html#k8s-scale-module) allows you to scale up|down Kubernetes objects that support the scale subresource, it would be great to have a supported method for rolling out and rolling back Deployments (and DeploymentConfigs).

A specific use case that I have in mind would be to tie the configuration of the application (stored in a ConfigMap) with the version of the Deployment such that when the ConfigMap is updated (instead of deleting all of the active pods) we roll out a new version of the application.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Maybe one for `k8s_rollout` and another for `k8s_rollback`?

##### ADDITIONAL INFORMATION

```yaml
handlers:
  - name: upgrade myapp
    k8s_rollout:
      api_version: v1
      kind: Deployment
      name: myapp
      namespace: myapp-namespace

tasks:
  # Set the configmap, upgrade when changed
  - name: set configmap
    k8s:
      state: present
      definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: myapp-config
          namespace: myapp-namespace
        data:
          foo: bar
    notify: upgrade myapp
```

### PR DESCRIPTION
**Pull request by julienhuon**
##### SUMMARY
Hello,

This pull request adds a new module which allow you to rollback a kubernetes Deployment or a kubernetes DaemonSet.

This is a contribution from the french organization [Institut National de l'Audiovisuel](https://institut.ina.fr).

Fixes #52046

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
The new module is named k8s_rollback.

##### ADDITIONAL INFORMATION
Here a typical use case with deployment:

```
- name: Deploy my beautiful k8s Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'deploy.yml') }}"
    wait: true
  ignore_errors: yes
  register: deploy_result

- name: Rolling Back my less beautiful Deployment
  k8s_rollback:
    api_version: apps/v1
    kind: Deployment
    name: beautifulapp
    namespace: default
  when: deploy_result.failed
```
And here with DaemonSet:

```
- name: Deploy my beautiful k8s DaemonSet
  k8s:
    state: present
    definition: "{{ lookup('template', 'ds.yml') }}"
    wait: true
  ignore_errors: yes
  register: ds_result

- name: Rolling Back my less beautiful Deployment
  k8s_rollback:
    api_version: apps/v1
    kind: DaemonSet
    name: beautifulds
    namespace: default
  when: ds_result.failed
```

It also could rollback multiples objets if you use label_selectors or field_selectors.

Let me know if you need any further information.

Regards,
Julien

### CODE REVIEW

**Comment by resmo** [comment]
Just my 2 cents.

This module looks like an "action" (so not idempotent) and I wonder if it would make sense to integrate this into the existing k8s module with an option to enable the feature and get an idempotent behavior:

~~~yaml
- name: Deploy my beautiful k8s DaemonSet
  k8s:
    state: present
    definition: "{{ lookup('template', 'ds.yml') }}"
    wait: true
    # default would be false
    rollback_enabled: true  
~~~

**Comment by julienhuon** [comment]
> Just my 2 cents.
> 
> This module looks like an "action" (so not idempotent) and I wonder if it would make sense to integrate this into the existing k8s module with an option to enable the feature and get an idempotent behavior:
> 
> ```yaml
> - name: Deploy my beautiful k8s DaemonSet
>   k8s:
>     state: present
>     definition: "{{ lookup('template', 'ds.yml') }}"
>     wait: true
>     # default would be false
>     rollback_enabled: true  
> ```

Hi,

It's a really good idea and I wanted to do so in the first place but I assumed a different module would be more easily accepted the modifying the existing one.

If a k8s module's maintainer could tell me what he prefers I'll modify my work accordingly.

Regards,
Julien

**Comment by willthames** [comment]
I think @resmo is right about idemptotency but I'm not convinced a separate module would help.

My suggestion would be to take a generation to roll back to - I'm pretty sure this is available from the Deployment when it fails and then look up the replicaset for that generation, rather than just assuming it's the previous one.

**Comment by julienhuon** [comment]
> I think @resmo is right about idemptotency but I'm not convinced a separate module would help.
> 
> My suggestion would be to take a generation to roll back to - I'm pretty sure this is available from the Deployment when it fails - and then look up the replicaset for that generation, rather than just assuming it's the previous one.

Hi @willthames,

Thanks for the response ! When you have a failed Deployment, you only have two informations about the last applied ReplicaSet: 

```
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"nginx-deploy","namespace":"testingrollback"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.17fefekfnkenfkenf","name":"nginx","ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2020-02-16T09:47:59Z"
```
The last-applied-configuration annotation is not always here (for example if you didn't deploy with the apply method), so I just exactly did what's kubectl rollout undo is doing:

```
kubectl rollout undo deployment/nginx-deploy -n testingrollback --v 9
``` 

* get the Deployment/DaemonSet labelSelectors & generation

```
I0216 10:55:56.774381   14783 round_trippers.go:451] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.15.8 (linux/amd64) kubernetes/6c143d3" 'https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy'
I0216 10:55:56.781158   14783 round_trippers.go:471] GET https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy 200 OK in 6 milliseconds
I0216 10:55:56.781174   14783 round_trippers.go:477] Response Headers:
I0216 10:55:56.781180   14783 round_trippers.go:480]     Content-Type: application/json
I0216 10:55:56.781185   14783 round_trippers.go:480]     Content-Length: 2153
I0216 10:55:56.781189   14783 round_trippers.go:480]     Date: Sun, 16 Feb 2020 09:55:56 GMT
I0216 10:55:56.781227   14783 request.go:947] Response Body: {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"nginx-deploy","namespace":"testingrollback","selfLink":"/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy","uid":"3b3e5d2f-5d33-4223-934b-175ca1a8c5b5","resourceVersion":"1595","generation":2,"creationTimestamp":"2020-02-16T09:47:59Z","labels":{"app":"nginx"},"annotations":{"deployment.kubernetes.io/revision":"2","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"nginx\"},\"name\":\"nginx-deploy\",\"namespace\":\"testingrollback\"},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.17fefekfnkenfkenf\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n"}},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.17fefekfnkenfkenf","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":10,"progressDeadlineSeconds":600},"status":{"observedGeneration":2,"replicas":4,"updatedReplicas":1,"readyReplicas":3,"availableReplicas":3,"unavailableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2020-02-16T09:48:46Z","lastTransitionTime":"2020-02-16T09:48:46Z","reason":"MinimumReplicasAvailable","message":"Deployment has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2020-02-16T09:49:10Z","lastTransitionTime":"2020-02-16T09:47:59Z","reason":"ReplicaSetUpdated","message":"ReplicaSet \"nginx-deploy-5cc6d656d\" is progressing."}]}}
I0216 10:55:56.837904   14783 round_trippers.go:451] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.15.8 (linux/amd64) kubernetes/6c143d3" 'https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy'
I0216 10:55:56.840631   14783 round_trippers.go:471] GET https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy 200 OK in 2 milliseconds
I0216 10:55:56.840657   14783 round_trippers.go:477] Response Headers:
I0216 10:55:56.840670   14783 round_trippers.go:480]     Content-Type: application/json
I0216 10:55:56.840680   14783 round_trippers.go:480]     Content-Length: 2153
I0216 10:55:56.840689   14783 round_trippers.go:480]     Date: Sun, 16 Feb 2020 09:55:56 GMT
I0216 10:55:56.840746   14783 request.go:947] Response Body: {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"nginx-deploy","namespace":"testingrollback","selfLink":"/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy","uid":"3b3e5d2f-5d33-4223-934b-175ca1a8c5b5","resourceVersion":"1595","generation":2,"creationTimestamp":"2020-02-16T09:47:59Z","labels":{"app":"nginx"},"annotations":{"deployment.kubernetes.io/revision":"2","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"nginx\"},\"name\":\"nginx-deploy\",\"namespace\":\"testingrollback\"},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.17fefekfnkenfkenf\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n"}},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.17fefekfnkenfkenf","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":10,"progressDeadlineSeconds":600},"status":{"observedGeneration":2,"replicas":4,"updatedReplicas":1,"readyReplicas":3,"availableReplicas":3,"unavailableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2020-02-16T09:48:46Z","lastTransitionTime":"2020-02-16T09:48:46Z","reason":"MinimumReplicasAvailable","message":"Deployment has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2020-02-16T09:49:10Z","lastTransitionTime":"2020-02-16T09:47:59Z","reason":"ReplicaSetUpdated","message":"ReplicaSet \"nginx-deploy-5cc6d656d\" is progressing."}]}}
```

* get all the ReplicaSet/ControllerRevision with the labelSelectors found:

```
I0216 10:55:56.841157   14783 round_trippers.go:451] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.15.8 (linux/amd64) kubernetes/6c143d3" 'https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/replicasets?labelSelector=app%3Dnginx'
I0216 10:55:56.844401   14783 round_trippers.go:471] GET https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/replicasets?labelSelector=app%3Dnginx 200 OK in 3 milliseconds
I0216 10:55:56.844443   14783 round_trippers.go:477] Response Headers:
I0216 10:55:56.844459   14783 round_trippers.go:480]     Content-Type: application/json
I0216 10:55:56.844472   14783 round_trippers.go:480]     Content-Length: 2895
I0216 10:55:56.844483   14783 round_trippers.go:480]     Date: Sun, 16 Feb 2020 09:55:56 GMT
I0216 10:55:56.844562   14783 request.go:947] Response Body: {"kind":"ReplicaSetList","apiVersion":"apps/v1","metadata":{"selfLink":"/apis/apps/v1/namespaces/testingrollback/replicasets","resourceVersion":"2720"},"items":[{"metadata":{"name":"nginx-deploy-5cc6d656d","namespace":"testingrollback","selfLink":"/apis/apps/v1/namespaces/testingrollback/replicasets/nginx-deploy-5cc6d656d","uid":"5ee7ccab-ff59-499a-983f-2df421cc2569","resourceVersion":"1592","generation":1,"creationTimestamp":"2020-02-16T09:49:10Z","labels":{"app":"nginx","pod-template-hash":"5cc6d656d"},"annotations":{"deployment.kubernetes.io/desired-replicas":"3","deployment.kubernetes.io/max-replicas":"4","deployment.kubernetes.io/revision":"2"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"Deployment","name":"nginx-deploy","uid":"3b3e5d2f-5d33-4223-934b-175ca1a8c5b5","controller":true,"blockOwnerDeletion":true}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx","pod-template-hash":"5cc6d656d"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx","pod-template-hash":"5cc6d656d"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.17fefekfnkenfkenf","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"replicas":1,"fullyLabeledReplicas":1,"observedGeneration":1}},{"metadata":{"name":"nginx-deploy-798dcc9989","namespace":"testingrollback","selfLink":"/apis/apps/v1/namespaces/testingrollback/replicasets/nginx-deploy-798dcc9989","uid":"e064385a-7cbb-441f-929f-402371780819","resourceVersion":"1517","generation":1,"creationTimestamp":"2020-02-16T09:47:59Z","labels":{"app":"nginx","pod-template-hash":"798dcc9989"},"annotations":{"deployment.kubernetes.io/desired-replicas":"3","deployment.kubernetes.io/max-replicas":"4","deployment.kubernetes.io/revision":"1"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"Deployment","name":"nginx-deploy","uid":"3b3e5d2f-5d33-4223-934b-175ca1a8c5b5","controller":true,"blockOwnerDeletion":true}]},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx","pod-template-hash":"798dcc9989"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx","pod-template-hash":"798dcc9989"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.17","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"replicas":3,"fullyLabeledReplicas":3,"readyReplicas":3,"availableReplicas":3,"observedGeneration":1}}]}
```

* get the previous one and patch the "/spec/template" of the actual deployment with "application/json-patch+json":

```
I0216 10:55:56.859781   14783 request.go:947] Request Body: [{"op":"replace","path":"/spec/template","value":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.17","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},{"op":"replace","path":"/metadata/annotations","value":{"deployment.kubernetes.io/revision":"2","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"nginx\"},\"name\":\"nginx-deploy\",\"namespace\":\"testingrollback\"},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.17fefekfnkenfkenf\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n"}}]
I0216 10:55:56.859944   14783 round_trippers.go:451] curl -k -v -XPATCH  -H "Content-Type: application/json-patch+json" -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.15.8 (linux/amd64) kubernetes/6c143d3" 'https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy'
I0216 10:55:56.868088   14783 round_trippers.go:471] PATCH https://127.0.0.1:32768/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy 200 OK in 8 milliseconds
I0216 10:55:56.868160   14783 round_trippers.go:477] Response Headers:
I0216 10:55:56.868192   14783 round_trippers.go:480]     Date: Sun, 16 Feb 2020 09:55:56 GMT
I0216 10:55:56.868219   14783 round_trippers.go:480]     Content-Type: application/json
I0216 10:55:56.868243   14783 round_trippers.go:480]     Content-Length: 2138
I0216 10:55:56.868409   14783 request.go:947] Response Body: {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"nginx-deploy","namespace":"testingrollback","selfLink":"/apis/apps/v1/namespaces/testingrollback/deployments/nginx-deploy","uid":"3b3e5d2f-5d33-4223-934b-175ca1a8c5b5","resourceVersion":"2721","generation":3,"creationTimestamp":"2020-02-16T09:47:59Z","labels":{"app":"nginx"},"annotations":{"deployment.kubernetes.io/revision":"2","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"nginx\"},\"name\":\"nginx-deploy\",\"namespace\":\"testingrollback\"},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.17fefekfnkenfkenf\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n"}},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.17","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":10,"progressDeadlineSeconds":600},"status":{"observedGeneration":2,"replicas":4,"updatedReplicas":1,"readyReplicas":3,"availableReplicas":3,"unavailableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2020-02-16T09:48:46Z","lastTransitionTime":"2020-02-16T09:48:46Z","reason":"MinimumReplicasAvailable","message":"Deployment has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2020-02-16T09:49:10Z","lastTransitionTime":"2020-02-16T09:47:59Z","reason":"ReplicaSetUpdated","message":"ReplicaSet \"nginx-deploy-5cc6d656d\" is progressing."}]}}
```

The only moment where a separated module could be usefull is when you want to rollback to a specific version. Like here:

```
kubectl rollout undo daemonset/abc --to-revision=3
```
But I didn't implemented it for the moment. Do you want me to:

* Include my work inside the k8s module and use it like @resmo wanted ?
* Stay with a separated module and implement --to-revision ?

Regards,
Julien

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible-collections/community.kubernetes/pull/26

**Pull request closed without merging**
