### PR TITLE
Alternative to container_to_text

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

As per https://github.com/ansible/ansible/pull/68512#discussion_r399528396

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
`lib/ansible/module_utils/_text.py`

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @abadger @samdoran

**Comment by abadger** [comment]
I like that we can consolidate the common code using partial without sacrificing readability too much but i wonder how important performance is for this code.  It's a recursive function so on deeply nested data, it will get called many many times. I see that we have to go through one extra function call (partial wraps the function rather than generating a nrw function with the argument turned into a constant) and there's one extra conditional in the common case (i think strings are the common case rather than . None).  There's also an extra call to ` to_*` when the string is already of the proper type.  Are these slowdowns important? If it wasn't in a loop (the recursive call) used by every single module return I'd say no. But since it is, I'd like to know what other people think. 

@samdoran your thoughts?

**Comment by mkrizek** [comment]
For the record, I wrote this to solve another problem not realizing we already had this functionality (see https://github.com/ansible/ansible/pull/68512#discussion_r399528396) and figured I'd open this PR if anyone wanted to discuss.

> I like that we can consolidate the common code using partial without sacrificing readability too much but i wonder how important performance is for this code. It's a recursive function so on deeply nested data, it will get called many many times. I see that we have to go through one extra function call (partial wraps the function rather than generating a nrw function with the argument turned into a constant) ...

I did not realize that partial creates one extra call, TIL.

> ...and there's one extra conditional in the common case (i think strings are the common case rather than . None). 

Looking at it now I am not sure why I did that, I assume it was because I based this code on `wrap_var` function which does that, but also checks for the given object being `AnsibleUnsafe` already (your next point). I think we can remove the condition here then.

> There's also an extra call to ` to_*` when the string is already of the proper type.

Yeah, that was the one downside I was aware of and decided to sacrifice that in favor of consolidating the common code.

> Are these slowdowns important? If it wasn't in a loop (the recursive call) used by every single module return I'd say no, it does not matter. But since it is, I'd like to know what other people think.

Looking through the codebase, I see that `container_*` functions are used either just on Python 2 (`safe_eval`, native jinja concat, `_load_params`) or in:
https://github.com/ansible/ansible/blob/53b95b865f7aabfa36ebac5514d604028346d001/lib/ansible/module_utils/common/text/converters.py#L270-L283 Which as the comment there suggests happens only on "old systems using old simplejson". That seems to limit the usage of these functions.

Having said all that I am on the fence now :-) It might be interesting to `timeit`.

**Comment by mkrizek** [comment]
### devel branch
```python
In [1]: from ansible.module_utils.common.text.converters import container_to_bytes

In [2]: l = [u"café" for x in range(100)]

In [3]: %timeit container_to_bytes(l)
60.5 µs ± 3.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [4]: l = [u"café" for x in range(1000)]                                                                                                                                     

In [5]: %timeit container_to_bytes(l)
582 µs ± 15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [6]: l = [u"café" for x in range(10000)]

In [7]: %timeit container_to_bytes(l)
5.83 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [8]: l = [u"café" for x in range(100000)]

In [9]: %timeit container_to_bytes(l)
59.4 ms ± 1.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

### container_to_text-alternative branch
```python
In [1]: from ansible.module_utils.common.text.converters import container_to_bytes                                                                                             

In [2]: l = [u"café" for x in range(100)]                                                                                                                                      

In [3]: %timeit container_to_bytes(l)                                                                                                                                          
69 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [4]: l = [u"café" for x in range(1000)]                                                                                                                                     

In [5]: %timeit container_to_bytes(l)                                                                                                                                          
672 µs ± 9.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [6]: l = [u"café" for x in range(10000)]                                                                                                                                    

In [7]: %timeit container_to_bytes(l)                                                                                                                                          
6.57 ms ± 60.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [8]: l = [u"café" for x in range(100000)]                                                                                                                                   

In [9]: %timeit container_to_bytes(l)                                                                                                                                          
71.3 ms ± 2.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Pull request closed without merging**
