### PR TITLE
[WIP] Extra test and build dependencies in Docker images

### PR DESCRIPTION
**Pull request by gundalow**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

N/A
##### SUMMARY

As suggested in https://github.com/ansible/ansible/pull/15304 install the dependencies to build debs and RPMs

Also to speed up a number of the integration tests we can install the needed dependencies in the base docker image.

Previously running the integration tests using the Ansible 14.04 image on a high spec machine with SSD

```
TASK: setup_mysql_db : install mysqldb_test debian dependencies ------- 134.92s
TASK: setup_postgresql_db : install dpkg dependencies for postgresql test -- 39.58s
TASK: test_unarchive : Ensure zip is present to create test archive (apt) -- 29.42s
TASK: test_apache2_module : install apache via apt --------------------- 17.47s

```

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible/15692)

### CODE REVIEW

**Comment by bcoca** [comment]
you have several merges and what seems like unrelated commits

**Comment by gundalow** [comment]
ready_for_review

**Comment by gundalow** [comment]
WIP: I need to update to add apache, postgress, zip and apache2 and then add testingdone section to show the reduction in time

**Comment by robinro** [comment]
@gundalow Maybe it's a good idea to integrate the new images for ubuntu 16.04 and opensuse ( https://github.com/ansible/ansible/pull/15704 and https://github.com/ansible/ansible/pull/15650) in here as well. You change all Dockerfiles anyway and I would have to add the packages then afterwards.

I guess updating the official images is a manual process, so by combining the updates this only has to happen once.

**Comment by gundalow** [comment]
@robinro That's my plan :)

It's a manual process for them to be updated, but that's fine.

**Comment by gundalow** [comment]
This shaves over 100 seconds off the Ubuntu 14.04 tests as the following installs aren't needed

```
TASK: test_unarchive : Ensure zip is present to create test archive (apt) -- 46.15s
TASK: setup_mysql_db : install mysqldb_test debian dependencies -------- 41.98s
TASK: test_apache2_module : install apache via apt --------------------- 27.36s
```

I'll collect data for the other distros

**Comment by mattclay** [comment]
@gundalow: Did you test each updated Dockerfile with run_tests.sh?

I encountered test failures for ubuntu1604:

```
TASK [test_mysql_user : assert output message password was update for user2] ***
fatal: [testhost]: FAILED! => {"assertion": "user_password_old.stdout != user_password_new.stdout", "changed": false, "evaluated_to": false, "failed": true}
    to retry, use: --limit @destructive.retry
```

As well as opensuseleap:

```
TASK [test_service : enable the ansible test service] **************************
fatal: [testhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable ansible_test: rc=1 Failed to execute operation: No such file or directory\n"}
```

All of the others passed tests.

**Comment by gundalow** [comment]
Hi @mattclay thanks for looking at this. 
The issues with the failing tests are tracked by https://github.com/ansible/ansible/pull/15704 and https://github.com/ansible/ansible/pull/15650/files

This PR is just updating the the existing Docker IMAGES,  and adding two new (SUSE & 1604)

This PR will NOT enable the two new distros in run_tests.sh. That will be covered by the previously mentioned PRs,  and do doubt include some discussion around Travis performance.

**Comment by abadger** [comment]
Thanks @gundalow and @robinro!  Merged.  @mattclay or @jimi-c are going to build the images themselves.  I've pinged them to changes having been made.

**Pull request merged**
