### PR TITLE
Implement a per-task check_mode setting

### PR DESCRIPTION
**Pull request by amenonsen**
This allows an individual task to be run in check mode, so that other
tasks can be made conditional on its result.

Author: Carlos Chapi carlos@2ndQuadrant.com

### CODE REVIEW

**Comment by bcoca** [comment]
isn't this redundant with always_run?​

**Comment by amenonsen** [comment]
No, the purpose is not to run the task when --check is specified (which is what always_run does), but to run (only) one task in check mode when --check is NOT specified.

This feature was actually suggested by @mpdehaan in a long-ago thread on the mailing list (2013-08-13!) in response to my proposal for an "apt_wouldinstall" module to find out if certain modules were installed or not, without actually installing them (something for which there is unfortunately no simple command line invocation of apt-get).

**Comment by bcoca** [comment]
thanks for clarifying, nice new feature!

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
I don't recall suggesting this actually, in either case, I don't believe this should be exposed as a language keyword as I find it a little confusing.

I do recall something along the lines of saying there shouldn't be a seperate module for this.

But I'm trying to control language sprawl and this seems to be a complicated thing without a lot of applications.

Feel free to bring up a thread on ansible-devel if you'd like to discuss more.

**Pull request closed without merging**
