### PR TITLE
Extra vars (squashed)

### PR DESCRIPTION
**Pull request by mgwilliams**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks, not sure why the merge commits are there, but this is easy to review and cherry pick.  Thank you.

**Comment by mgwilliams** [comment]
Yeah, I'm not sure either... maybe because I did a pull into my master branch earlier. Trying to train myself not to do that.

**Comment by mpdehaan** [comment]
.

**Comment by mpdehaan** [comment]
As a heads up, my patch to keep module_args as a string most of the way through runner seems to have allowed simplification of the quoting stuff... so if that code looks different, that's why

Tests seem to like it, let me know if you find otherwise

**Pull request closed without merging**
