### PR TITLE
Update to Rackspace Guide

### PR DESCRIPTION
**Pull request by angstwad**
##### Issue Type:

Docs Pull Request
##### Ansible Version:

1.5
##### Environment:

N/A
##### Summary:

Spelling, grammar, layout changes, plus more examples and an orchestration chapter.  These are passing build with a make viewdocs, and look good to me.  This does need a second set of eyes for review, @sivel is cc'ed.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

### CODE REVIEW

**Comment by angstwad** [comment]
cc @sivel, please review real quick.

**Comment by mpdehaan** [comment]
ping?  Otherwise I'll zap this in soon.  Thanks!

**Comment by sivel** [comment]
@mpdehaan apologies.  We're good to go.  Merge on in.  I've got more changes to push in here soon too.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
