### PR TITLE
Add sensu_handler Ansible module

### PR DESCRIPTION
**Pull request by dmsimard**
##### SUMMARY
This provides a sensu_handler module in order to be able to dynamically
configure a Sensu handler.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
sensu_handler

##### ANSIBLE VERSION
Ansible 2.4

##### ADDITIONAL INFORMATION
This provides a new sensu_handler Ansible module which uses the same approach as ``sensu_client`` introduced [here](https://github.com/ansible/ansible/pull/27529).

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests:

```
Traceback (most recent call last):
  File "/tmp/ansible_LX5CZB/ansible_module_sensu_handler.py", line 284, in <module>
    main()
  File "/tmp/ansible_LX5CZB/ansible_module_sensu_handler.py", line 210, in main
    path = '/etc/sensu/conf.d/handlers/{}.json'.format(name)
ValueError: zero length field name in format
```

**Comment by dmsimard** [comment]
@mattclay I couldn't find that error anywhere in the shippable tests but I saw that it's a legit error for python versions lower than 2.6. It was an easy fix so I did it even though I think Ansible 2.4 drops support for older version of python,

**Comment by mattclay** [comment]
@dmsimard The failure was from the centos6 docker image (python 2.6) here:

https://app.shippable.com/github/ansible/ansible/runs/31486/12/tests

Test with: `test/runner/ansible-test integration -v sensu_handler --docker centos6`

**Comment by dmsimard** [comment]
Updated commit: Added support for check mode and moved argument validation to "required_if".

**Comment by dmsimard** [comment]
@andsens I don't think this needs anything else to land, let the bot know if he can shipit or something like that :D

**Comment by timlnx** [comment]
shipit

**Comment by andsens** [comment]
shipit

**Pull request merged**
