### PR TITLE
win_stat change return islink to islnk to match stat

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Changed win_stat to fix return value from islink to islnk to match the stat module.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_stat

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 11138abc51) last updated 2017/04/01 12:25:17 (GMT +1000)
  config file = /mnt/c/dev/test/role/ansible.cfg
  configured module search path = [u'/mnc/c/dev/test/role/library']
  python version = 2.7.12 (default, Dec 14 2016, 21:05:07) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION
To keep the windows and unix modules as close as possible this is to change the return value from islink to islnk.

### CODE REVIEW

**Comment by jborean93** [comment]
@nitzmahone @jhawkesworth @dagwieers I realised the return value islink is actually islnk in the stat module. This return value was only added in 2.3 so I'm hoping we can get this through before 2.3 is officially released.

**Comment by nitzmahone** [comment]
That's funny, I noticed that when I first looked at it and just blindly assumed it was carrying over the same behavior from the *nix module... Yeah, I'll merge/cherry-pick this first thing Monday for RC4 (or sooner if I get back in front of my workstation).

**Review by nitzmahone — APPROVED** [review]
Nice job on the test cleanup, too...

**Comment by nitzmahone** [comment]
cherry-picked to stable-2.3 for 2.3.0RC4

**Pull request merged**
