### PR TITLE
Ported git module to use common module function.

### PR DESCRIPTION
**Pull request by tima**
Just like the headings says. Tried to keep the code and comments the same as possible.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Much appreciated, thanks.

This needs to use argument_spec like the other modules, can you take a look at group/user and make it work like those?  This makes sure all argument parsing is done the same, and can make sure required parameters are present.

Updating this pull request would be fine.

**Comment by mpdehaan** [comment]
I ended up taking sfromm's since it was using argument_spec, sincere apologies on not coordinating and resulting in duplicate work.   

Testing on the git module stuff is very welcome!    Thanks!

**Comment by tima** [comment]
oh well. it wasn't a whole lot of work. just trying to contribute.

**Comment by mpdehaan** [comment]
Yep, it is much appreciated.

very sorry about that.   

I am probably going to go ahead and port the rest of them today and tomorrow so we can get ready for 0.6 release.

**Pull request closed without merging**
