### PR TITLE
Wired in Michael's usage string optparse style.

### PR DESCRIPTION
**Pull request by bradobro**
Just a quick patch to show the usage string intended for 'ansible.' (I didn't patch ansible-playbook yet but can do if you like the patch.)

### CODE REVIEW

**Comment by mpdehaan** [comment]
needs to update ansible-playbook as well as bin/ansible

**Comment by bradobro** [comment]
Will do.

**Comment by bradobro** [comment]
ansible-playbook now has usage wired in, but still shows it on stderr (ansible shows it on stdout). Should I make them consistent?

**Comment by mpdehaan** [comment]
Sure.  Stderr on both

There's no need for the deprecation comment, BTW, it's going to be available without printing a warning by default all the way through 3.2 at least, with no plans to remove it.    

See http://www.python.org/dev/peps/pep-0389/

**Comment by bradobro** [comment]
Michael,
There's no need for the deprecation comment, BTW, it's going to be
available without printing a warning by default all the way through 3.2 at
least, with no plans to remove it.

> See http://www.python.org/dev/peps/pep-0389/
> 
> That's great news. I use optparse a lot. Missed the pep. Thanks for
> pointing it out.

**Pull request merged**
