### PR TITLE
toggle missing handler errors/warnings via config

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

handlers
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

Allows user to decide if missing handler is fatal or warning

### CODE REVIEW

**Comment by alikins** [comment]
Does this fix https://github.com/ansible/ansible/issues/17848 ? if so, commit should reference it.

**Comment by alikins** [comment]
This seems like an odd thing to add a config option for, especially since it defaults to being fatal.
Whats the use case for it being fatal?

**Comment by bcoca** [comment]
@alikins left comments on the other issues as this does not really solve them but give a 'middle ground'. 

As for why it is an error, it mostly because that was the behavior since handlers were introduced, this 'broke' in 2.0 and was a bug for a while but eventually fixed. 

One of the referenced PRs was changing it into a warning but this is not a backwards compatible change, hence this PR.

**Comment by alikins** [comment]
Could there be a default handler that gets invoked if there are no specifically attached handlers?
Then the default handler could warn in this case. Or if it makes sense to be fatal, the
default handler could raise the exception.

**Comment by bcoca** [comment]
that could be a feature but beyond the scope of this PR, this implements what was discussed in the proposal but never made it into the code, as such it was an oversight that this PR remedies.

**Comment by resmo** [comment]
tested
+1

**Pull request merged**
