### PR TITLE
ad-hoc: add documentation about pattern

### LINKED ISSUE #32553: Clarify on patterns, add links
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
docs

##### ANSIBLE VERSION
latest

##### SUMMARY
documentation is lacking a bit on where full pattern functionality can be used, and a few links could be helpful

##### STEPS TO REPRODUCE
* http://docs.ansible.com/ansible/latest/intro_adhoc.html does not seem to explain that --limit for ad-hoc commands works on the initial pattern spec
* http://docs.ansible.com/ansible/latest/intro_adhoc.html and https://ansible-tips-and-tricks.readthedocs.io/en/latest/ansible/commands/#limit-to-one-or-more-hosts mention limiting here and there, but can the full pattern syntax be used ? if so, it would be great to mention that and link to http://docs.ansible.com/ansible/latest/intro_patterns.html from
* https://ansible-tips-and-tricks.readthedocs.io/en/latest/ansible/commands/#limit-to-one-or-more-hosts says "This is required when one wants to run a playbook against a host group, but only against one or more members of that group." - this does seem to be either a broken sentence, or at least a very confusing one; after some help from agaffney on IRC and testing, it seems like it could be simplified to "This allows to limit a playbook run to a more specific set of hosts or groups."

##### EXPECTED RESULTS
understanding all the functionality and having a nice link to the pattern page

##### ACTUAL RESULTS
confusion remains and link is not there

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Add details about pattern in ad-hoc commands docs

Fixes: #32553

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/user_guide/intro_adhoc.rst

### CODE REVIEW

**Comment by s-hertel** [comment]
We should probably document this in one place and share it since it applies to ansible-playbook, ansible-console, etc.

**Review by acozine — COMMENTED** [review]
We have a page on patterns: https://docs.ansible.com/ansible/devel/user_guide/intro_patterns.html#intro-patterns - I think we can shorten this section and link to the page for more details. What do you think, @Akasurde?

**Comment by Akasurde** [comment]
@acozine I made changes. Could you please take a look again? Thanks.

**Review by samccann — APPROVED** [review]

**Pull request merged**
