### PR TITLE
[2.8] docker_swarm_service: Added default value for mounts.source

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #58039 to stable-2.8.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_swarm_service

### CODE REVIEW

**Comment by davidburge1** [comment]
unsubscribe

**Comment by hannseman** [comment]
shipit

**Comment by abadger** [comment]
Merged for the 2.8.2 release

**Comment by felixfontein** [comment]
Thanks for merging these PRs!

**Pull request merged**
