### PR TITLE
Make sure a default allow out rule exists if no other egress rules do

### LINKED ISSUE #7027: Default to sane egress policy in ec2_group (change since 1.5.3->1.6)
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Mac OS X 10.7
##### Summary:

rules_egress was added to ec2_group in 1.6 (previous there was no rules_egress).  Unfortunately it defaults to nothing in it, meaning that previous ansible scripts will not allow anything out of a security group.  This breaks many security groups.
##### Steps To Reproduce:

Create a ec2_group (security group) with no rules_egress.  Watch everything get blocked going outbound.
##### Expected Results:

Should default to allowing everything outbound since thats what ansible did previously.
##### Actual Results:

Unable to access going outbound.

### PR DESCRIPTION
**Pull request by jimi-c**
Fixes #7027

### CODE REVIEW

**Comment by mmoya** [comment]
I **strongly disagree** with this. See explanation [here](https://github.com/ansible/ansible/issues/7027#issuecomment-41704388).

**Comment by jimi-c** [comment]
@mmoya this patch should only be hit if the egress rules are not specified at all, it will not add a default 0/0 out rule if other egress rules are specified. From my understanding, this was how it worked before but with the addition of the egress rules it's preventing any outbound traffic by default.

**Comment by mmoya** [comment]
You're right. I didn't put enough attention when reviewing this PR.

**Comment by jimi-c** [comment]
@mmoya no problem, let us know if you have any further questions.

**Pull request merged**
