### PR TITLE
New Memset module to request DNS reloads

### PR DESCRIPTION
**Pull request by glitchcrab**
##### SUMMARY
This PR provides a module to request a reload of [Memset's DNS infrastructure](https://www.memset.com/apidocs/methods_dns.html#dns.reload) .

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
 * memset_dns_reload

##### ANSIBLE VERSION
```
2.6
```

### CODE REVIEW

**Comment by duncan9562** [comment]
DNS reloads completed successfully!

**Comment by ghost** [comment]
works fine for me

**Comment by PebbleOfParagon** [comment]
Completes DNS reload successfully

**Comment by maxamillion** [comment]
@resmo you also assigned this for self-review but haven't updated since the initial comment, anything you'd like to see addressed?

**Review by resmo — APPROVED** [review]
LGTM

**Comment by James-MS** [comment]
Works for me!

**Pull request merged**
