### PR TITLE
Add the ability to pick a tablespace when creating a postgres database.

### LINKED ISSUE #5954: postgresql_db module tablespace parameter
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.4.4
##### Environment:

Running Ansible from Arch Linux

Managing Centos 6/Debian 7
##### Summary:

I would like to make use of this module, but I can't because I can't specify a tablespace for the database.

I noticed this pull request https://github.com/ansible/ansible/pull/4994 but it doesn't seem like the author resubmitted it and also it doesn't seem to modify the postgresql_db module to allow specifying a tablespace anyway.

If I have time i'll try to create a pull request which adds this parameter (should be pretty easy to add).

I just wanted to get this issue in in case someone else has time to do it before me.
##### Steps To Reproduce:

```
tasks:
    - name: create database
      action: postgresql_db name=database1 owner=owner1 tablespace=my_tablespace
```
##### Expected Results:

a new database is created with the specific tablespace my_tablespace
##### Actual Results:

tablespace parameter not possible

### PR DESCRIPTION
**Pull request by antoinell**
##### SUMMARY
Add support to select a tablespace when creating or updating a postgres database with the `postgresql_db` module.
Fixes #5954
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

postgresql_db

##### ADDITIONAL INFORMATION
similar to https://github.com/ansible/ansible/pull/37953
a parallel pull request #50568 has been submitted to add a module allowing to create a tablespace.

### CODE REVIEW

**Comment by nerzhul** [comment]
hello @antoinell , thanks for your commit. You should do two PR, one to modify the postgresql_db module, one to add postgresql_tablespace module.
For postgresql_db change it's fine to me

**Comment by Dorn-** [comment]
Yup, as @nerzhul said, it should be two distinct PR.
One to add the postgresql tablespace module and another to add a parameter to the db module.
I tried to add this tablespace module here: #23603  (I'll look to update it asap)

**Comment by antoinell** [comment]
Shippable tests fail on rhel 7.6.1 with this 
```
"echo \"create tablespace ansible_tablespace location '/tmp/ansible_tablespace';\" | psql -d postgres",
"ERROR:  could not set permissions on directory \"/tmp/ansible_tablespace\": Permission denied"``
```

**Comment by antoinell** [comment]
@Dorn @Nerzhul I have split the pull requests between change to the `postgresql_db` module and creation of a new `postgresql_tablespace` module in #50568 .

**Comment by Andersson007** [comment]
duplicate_of https://github.com/ansible/ansible/pull/50568

**Comment by antoinell** [comment]
can we reopen this pull request ? it was about being able to pick a tablespace when creating a database.

**Comment by Andersson007** [comment]
Sorry for closing.
Will it be difficult for you to create new one instead? (If yes, mention it in the pinboard too, please)

**Comment by Andersson007** [comment]
- make upper the first symbol of the description
- IMO, use postgtesql_db.yml for tests. Create it. We move all of postgresql tests to there later. Then include it to main.yml. I don’t insist but it’ll be better
- you can use our new module to create tablespace instead of shell ;)

**Comment by antoinell** [comment]
OK I will create a new pull request, thanks for the comments.

**Pull request closed without merging**
