### PR TITLE
aix_update_all.py added

### PR DESCRIPTION
**Pull request by flynn1973**
##### SUMMARY
update all lpp/rpm packages  in aix via system commands

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
aix_update_all

##### ADDITIONAL INFORMATION
```yaml
# Synchronize ALL packages from the NIM_MASTER in the standard share
- name: Install All packages
  aix_update_all:
# Install latest  packages from the nfs_server: rn100pgpl.itc.testlab.intranet from the share: /export/nim/aix7104-03/lpp_new
- name: Install bash 
  aix_update_all:
    nfs_server: rn100pgpl.itc.testlab.intranet
    nfs_share: /export/nim/aix7104-03/lpp_new
```

### CODE REVIEW

**Comment by molekuul** [comment]
@flynn1973 Hi, this module was not ready just for a pull request, that why I didn't do that before.
please contact me about your fork of my AIX-ansible-modules role, where you found this module.

Kind regards,

Joris Weijters

**Comment by d-little** [comment]
Should this PR be closed?  Or are we hoping to update and merge this particular PR eventually?

@flynn1973  @molekuul 
 
(My apologies for the spam on these PR's, running through a big cleanup :) )

**Comment by flynn1973** [comment]
i use this module on a daily basis and it works perfectly well.

**Comment by gforster** [comment]
shipit

**Comment by molekuul** [comment]
shipit

**Review by molekuul — APPROVED** [review]
This is a new prfectly working module for updating AIX

**Pull request closed without merging**
