### PR TITLE
Implement --diff for the copy module.

### PR DESCRIPTION
**Pull request by stoned**

### CODE REVIEW

**Comment by stoned** [comment]
FYI I have more diffs about the following matters :
- --diff and template module: do not die and output nice diff when destination is absent
- make diff header lines more explicit about what the diff is about. This gives a more readable output when producing diff for a task with multiple items (with_items).

**Comment by mpdehaan** [comment]
That sounds very good to me!

**Comment by stoned** [comment]
Should I then attach more commits to this PR  ?

**Comment by mpdehaan** [comment]
That works for me if you want.

**Comment by stoned** [comment]
And what about my proposed change of signature of utils.get_diff() ? Does it look ok ?

**Comment by mpdehaan** [comment]
Yeah, that's fine.  It's all 1.1 so nothing else could be relying on it yet
for API compat reasons.

**Comment by stoned** [comment]
Ok then two more commits are now in the branch

**Comment by mpdehaan** [comment]
merged in, this is TOTALLY AWESOME.

Well done!

**Comment by mpdehaan** [comment]
Thanks!

**Pull request merged**
