### PR TITLE
Add parameterized playbook includes

### LINKED ISSUE #1162: parameterized playbook includes?
include: playbook.yml a=2 b=3 c=4

we can do it with tasks, why not?

see also: handlers

make sure with_items also works with these includes as it now works with task includes

### PR DESCRIPTION
**Pull request by dhozac**
Also makes with_\* work with them.

Fixes #1162.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for trying this.  I've previously turned down another attempt to add this because I really wanted to refactor the way playbook loading worked first, which I think still needs to happen.   This is also why I pushed it to 1.0.  Another thing that should also happen is playbook includes should work at infinite depth.

Can you add comments detailing the logic involved, at least in a gist?

I'm curious why lookup plugins have to be invoked here and what the logic around "with" is intended to do.

Why is "varReplaceWithItems" used?  Etc.   (This is one of the more confusing functions in the new variable system about when it should be used -- more information about why it is used would definitely be good in the source)

It also _seems_ that recursive templating would set in and solve some of these problems, so variables could be passed in in raw state (like a=$b, not a=2) and evaluated later, which would be ok -- I could be wrong, but want to understand why that would be wrong.

Examples of additional functionality regarding the code around "with_" would also be helpful to see.   

Thanks!

I guess what I'm saying is I need to understand how all of these things work intimately, as as we build on new things, the code needs to read more simply and straightforwardly, and needs to have subfunctions and explain itself so other people can easily work on it.   This is especially why I had considered this needing to be in the 1.0 refactor and why I had assigned it to myself to make sure we could clean up that loading architecture to support playbooks loading playbooks loading playbooks, etc.

**Comment by mpdehaan** [comment]
(above comment updated)

**Comment by dhozac** [comment]
varReplaceWithItems keeps data structures. It doesn't stringify things unless it is needed. This allows var=$item, where $item is a dict/list/etc.

Playbook includes do work at infinite depth. The only finite depth includes are task includes, which is not touched by this at all.

If you set a=$b, where b is a dict and don't use varReplaceWithItems, ${a.subitem} will not work.

Lookup plugins add the support for with_*. Not sure how else you'd like to see that done...

I don't understand what part of the with code you're having a problem with, it just gets the plugin name and args and invokes it. What lines are you referring to?

**Comment by mpdehaan** [comment]
(A)

The question really comes up as to whether we should just be calling
utils.template instead?   That is what most of the program does when it
needs replacements.

Then we can make all the varReplace logic private.

I think that's why I'm confused with this -- in most places, the code just
calls template directly (like Runner) and not varReplaceWithItems or
varReplace.

Is there a reason we couldn't call template instead and just make all of
the varReplace logic private?

(B)

Sounds reasonable allowing a "with_" to be attached to the includes.  I
understand now.  Comments in the source would have helped make this clearer
why it was happening.

I assume you mean for things like:

```
 - include: $item
   with_items:
      - a.yml
      - b.yml
```

I don't think we have an example of that anywhere in examples/playbooks/*
and it would probably be useful to include that at least commented out
somewhere
so there's a record of it.   Perhaps in the lookups plugin example file,
even if commented out.

**Comment by dhozac** [comment]
template makes a string. It does not keep things as data structures. varReplaceWithItems really should be named template_ds or something, it should be used anywhere you don't have a string you want to convert to a string, but rather have a data structure that can contain variables. For instance

``` yaml
- include: file.yml data=$item
  with_items:
  - foo: data
    bar: $barforitem1
  - foo: data2
    bar: $barforitem2
```

template would set data to the string "{'foo': 'data', 'bar': 'data'}". varReplaceWithItems sets data to the dict.

I imagine most cases for with_\* together with includes will be like the above. I can add something to examples for it.

**Comment by mpdehaan** [comment]
On Fri, Nov 9, 2012 at 8:52 AM, Daniel Hokka Zakrisson <
notifications@github.com> wrote:

> template makes a string. It does not keep things as data structures.
> varReplaceWithItems really should be named template_ds or something, it
> should be used anywhere you don't have a string you want to convert to a
> string, but rather have a data structure that can contain variables. For
> instance
> - include: file.yml data=$item
>   with_items:
>   - foo: data
>     bar: $barforitem1
>   - foo: data2
>     bar: $barforitem2
> 
> template would set data to the string "{'foo': 'data', 'bar': 'data'}".
> varReplaceWithItems sets data to the dict.

Agreed, let's rename it then.

varReplace => _var_replace  (private)
varReplaceWithItems => template_ds

> I imagine most cases for with_\* together with includes will be like the
> above. I can add something to examples for it.

Passing in a list is pretty common too.

with_items:  $some_list_from_vars_files_or_elsewhere

**Comment by dhozac** [comment]
template_ds done, examples have to wait, have to catch a plane.

**Comment by mpdehaan** [comment]
merged, thanks... we can do examples later!

**Pull request merged**
