### PR TITLE
remove deprecated

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

module args
##### ANSIBLE VERSION

```
>=2.6
```

### CODE REVIEW

**Comment by bcoca** [comment]
failures are due to postgresql_db tests need to be rewritten

**Comment by abadger** [comment]
It's too late to get this into 2.6.x.  We can get it into devel for 2.7.0.

We should get this in at the start of the devel cycle but @nitzmahone, @jtyr, @agaffney are talking about alternatives and use cases.  If there's a use case that isn't covered by module_defaults then we should consider keeping this (possibly, as nitzmahone suggests, by tying the ability to use this with facts only being usable via namespace).

**Review by jimi-c — APPROVED** [review]

**Comment by mattclay** [comment]
Traceback in integration tests:

```
Traceback (most recent call last):
  File "/tmp/ansible_gowx0ik1/ansible_module_postgresql_db.py", line 421, in main
    db_connection = psycopg2.connect(database=maintenance_db, **kw)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  ******** authentication failed for user "postgres"
FATAL:  ******** authentication failed for user "postgres"
```

**Comment by basos9** [comment]
Hello,
Could this be re articulated please (#42192)?

Possibly add a configuration option, for developers that understand the risks, to be able to use the feature.

Nevertheless the "security implications" should be somewhere described.

Thanks

**Comment by abadger** [comment]
We had a discussion of this yesterday and decided that we will change strategies around this.  The real root of the issue revolves around facts being used in parameters (because facts come from managed machines and we don't want to make it easy for a single compromised managed machine to compromise the controller or other machines).  We will be restoring this feature before 2.7.0 with a warning about the security implications instead of a deprecation warning.  In future releases we will work on making ansible emit a warning when an unnamespaced fact is used.  This will make it obvious when a variable being used as the args for a module has been overridden by a remote machine which should mitigate the security concerns around it.  nitzmahone will be driving the work in 2.7.0.

**Pull request merged**
