### PR TITLE
Close zeromq context and socket.

### PR DESCRIPTION
**Pull request by ralphbean**
caveat -> `make tests` didn't pass when I first cloned the repo and doesn't pass now with this patch.  Not sure if that's my fault for not configuring my env correctly.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hey Ralph, thanks for taking a look at this!   Will merge shortly, I am probably going to work on fireball a bit this weekend.  (Going to add some additional security bits, the timeout kill switch, and look into multi-user stuff a bit more like making it possible to override the port)

What part of the tests are failing for you?

**Comment by ralphbean** [comment]
Hey, no problem!  With::

```
$ . ./hacking/env-setup
$ make tests
```

I get http://threebean.org/ansible-tests.txt

**Comment by mpdehaan** [comment]
IIRC, tests are trying to live-SSH to localhost using paramiko (doing
harmless things, but you're right not to trust me!) versus using the local
connection type ... I suspect your SSH key isn't in authorized_keys for
your own host or you're not running with ssh-agent.

**Comment by ralphbean** [comment]
That did it.  :)  Tests pass.

**Comment by mpdehaan** [comment]
merged, thanks.

BTW, seeing you are one of the first folks to try it, can you let me know how things went and what you think?

**Pull request merged**
