### PR TITLE
postgresql: move CI tests of *_tablespace, *_membership, *_idx to separate targets

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql: move CI tests of *_tablespace, *_membership, *_idx to separate targets

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
postgresql_idx
postgresql_tablespace
postgresql_membership

### CODE REVIEW

**Review by kostiantyn-nemchenko — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko thank you for reviewing!

**Comment by gundalow** [comment]
@Andersson007 @kostiantyn-nemchenko Thank you, merged

**Comment by Andersson007** [comment]
Thanks all!

**Pull request merged**
