### PR TITLE
run Tower CI using the latest ansible-tower-cli package

### PR DESCRIPTION
**Pull request by ryanpetrello**
##### SUMMARY
Update Tower modules CI to use the latest version of `ansible-tower-cli`

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
tower modules

##### ANSIBLE VERSION
```
ansible 2.6.0 (tower-cli-latest 829ca02de1) last updated 2018/04/25 13:53:20 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ryan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ryan/dev/ansible/lib/ansible
  executable location = /home/ryan/.local/share/virtualenvs/ansible-1IJdo_WI/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

### CODE REVIEW

**Comment by ryanpetrello** [comment]
cc @mattclay @AlanCoding @john-westcott-iv

**Review by AlanCoding — APPROVED** [review]
Correct, 3.3.0 is a full superset of 3.2.1, and the only supported release line for v2 API

**Comment by AlanCoding** [comment]
shipit

**Review by mattclay — APPROVED** [review]

**Comment by matburt** [comment]
shipit

**Comment by wwitzel3** [comment]
shipit

**Review by wwitzel3 — APPROVED** [review]

**Comment by AlanCoding** [comment]
shipit

**Comment by rooftopcellist** [comment]
shipit

**Pull request merged**
