### PR TITLE
Add 2 EBGP neighbors with template

### PR DESCRIPTION
**Pull request by permitanyany**
Add 2 EBGP neighbors using BGP Unnumbered via Template
+label: docsite_pr
+label: issue #311

##### SUMMARY
Add 2 EBGP neighbors with template

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
nclu

##### ANSIBLE VERSION
ansible 2.5.2
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

##### ADDITIONAL INFORMATION
Issue #311

### CODE REVIEW

**Comment by s-hertel** [comment]
I think you mean https://github.com/ansible/community/issues/311, right? #311 links to something else.

**Comment by permitanyany** [comment]
Sorry I was referring to this:
https://github.com/ansible/community/issues/311

**Comment by ericpulvino** [comment]
Looks clean.

**Comment by IPvSean** [comment]
there is a new requirement for all submitted PRs for the contest ansible/community#311 (and in general for networking doc PRs) to provide playbook output. Since this is a new rule, and Cumulus VX is widely available and easy to use, I will go ahead and test the 5 PRs submitted by @permitanyany

For https://github.com/ansible/ansible/pull/40733 here is the playbook
```
---
- name: test playbook for cumulus
  hosts: leaf01
  gather_facts: false
  tasks:
      - name: Add two EBGP neighbors using BGP Unnumbered via Template
        nclu:
         template: |
           {% for neighbor in range(51,53) %}
           add bgp neighbor swp{{neighbor}} interface remote-as external
           {% endfor %}
         atomic: true
```

this works (as long as bgp is already configured, similar to https://github.com/ansible/ansible/pull/40369).  Please look at my suggestions on 40369 and make sure you don't want to accept them

```
cumulus@oob-mgmt-server:~$ ansible-playbook template.yml

PLAY [test playbook for cumulus] **************************************************************************************

TASK [Add two EBGP neighbors using BGP Unnumbered via Template] *******************************************************
changed: [leaf01]

PLAY RECAP ************************************************************************************************************
leaf01                     : ok=1    changed=1    unreachable=0    failed=0
```
then checking output->
```
router bgp 65000
  coalesce-time 1000
  neighbor swp51 interface remote-as external
  neighbor swp52 interface remote-as external
```

**Comment by acozine** [comment]
@permitanyany just like #40731, this PR needs to be rebased - you can follow  https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html. Thanks for your contributions!

**Comment by acozine** [comment]
Closing in favor of #41853.

**Pull request closed without merging**
