### PR TITLE
Add integration test for group_by variable precedence.

### PR DESCRIPTION
**Pull request by direvus**
Test that, when a group is created with group_by, variables from the
corresponding group_vars/ file are correctly pulled in, and override
variables specified in group_vars/all.

See ansible/ansible#8664.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi, thanks for this.

One problem I see is this says it is checking group_by, but I don't see a call to the group_by module in the output.  Is it possible that maybe there's a file that forgot to be checked in for this one?

Thanks!

**Comment by mpdehaan** [comment]
Also I believe this is already fixed on the development branch, I'll let @jimi-c confirm.

The workaround would be to:

```
 - group_by: key=grp-{{ foo }}
 - include_vars: path/to/group_vars/grp-{{ foo }}.yml
```

**Comment by direvus** [comment]
Hi @mpdehaan,

Not sure what you mean about it not running `group_by`.  The test_group_by.yml playbook runs group_by four times, on different variations of the variable `genus`, at the top of the file.  I left those tasks alone, except to make them run group_by on all hosts, not just those in the `lamani` group, so as to provide testing coverage on hosts that are initially ungrouped in inventory.  

All my new tests do, is check that once group_by is run, the hosts have properly picked up vars for the new group from `group_vars`, and that they properly override vars picked up from `group_vars/all`.

`test_group_by` seemed like the most natural place to put the new tests, but if you'd prefer I move them to `test_var_precedence` or somewhere else, let me know.

The bug I reported in ansible/ansible#8664 is indeed already fixed in devel.  The purpose of this PR is solely to add integration testing coverage, following @sergevanginderachter's suggestion.

Thanks for posting that workaround.

**Comment by amenonsen** [comment]
@direvus any chance you could rebase this to apply to current devel? I think it's a useful test to have.

**Comment by direvus** [comment]
Hi @amenonsen, I have created a new PR against current devel as requested, see #11752.  Unfortunately I couldn't just update the original PR, as that fork no longer exists.

**Pull request closed without merging**
