### PR TITLE
Remove relative import from setup module

### PR DESCRIPTION
**Pull request by ssbarnea**
##### SUMMARY

Replaces relative import of AnsibleModule with full import.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
setup

##### ADDITIONAL INFORMATION

It should also be noted that this is the only import with `..` from the entire `lib/ansible`. There are few other such imports but only inside the tests.

### CODE REVIEW

**Comment by webknjaz** [comment]
Looks like this reveals a design flaw in `ansible-lint`, in which case I'd argue that is not a good reason for changing ansible-core and the linter should be fixed instead.
In general, I'd welcome more relative imports in the code base to challenge the corner cases and make sure that there's nothing relying on the dynamic imports happening outside the importable package context.
I recognize that jumping through several layers of parent packages may be problematic in other ways, though. But to solve that problem I'd rather implement architectural layer linting through something like `import-lint` instead.

**Review by ganeshrn — APPROVED** [review]

**Review by webknjaz — CHANGES_REQUESTED** [review]
To be clear, I'm :-1: on this because it sets a bad precedent by encouraging third-parties to implement broken import machinery, as described above and in the related issue. That ain't right.

**Comment by sivel** [comment]
This is actually there on purpose and should not be removed.

**Comment by cidrblock** [comment]
hey @sivel , for the sake of history and understanding, do you have time to explain why it was done on purpose?  The explanation would be appreciated

**Comment by webknjaz** [comment]
@cidrblock note that the lint's importer implementation is buggy regardless of the way core uses imports (which are completely legitimate on their own).

**Comment by cidrblock** [comment]
@webknjaz yeah, the call to spec_from_file_location was malformed, the real fix allows the parent of Modulespec to be set correctly.  https://github.com/python/cpython/blob/53d9cd95cd91f1a291a3923acb95e0e86942291a/Lib/importlib/_bootstrap.py#L402

Thanks!

**Pull request closed without merging**
