### PR TITLE
pacman module for arch linux

### PR DESCRIPTION
**Pull request by Cightline**
Not sure if this is the right way to do this. This is a module for pacman (Arch Linux package manager).

### CODE REVIEW

**Comment by mpdehaan** [comment]
The package parameter should be named "name" and take "pkg" as an alias, see yum for an example.

**Comment by mpdehaan** [comment]
Copyright seems incorrect?  

Also, remove the alias "pkgs" -- want to be consistent with yum/apt

**Comment by mpdehaan** [comment]
re comment "that way you can just specify "upgrade" or "update" 

how would I specify either of these?

In general, this is "state=latest" in other modules

**Comment by Cightline** [comment]
Change the email in the copyright? state=latest should trigger a update
(pacman -Syy)?

Update and upgrade should run with "pacman: update" or "pacman: upgrade"

If thats what you are wanting just let me know I'll fix it up.

**Comment by jpmens** [comment]
version_added in DOCUMENTATION string should refer to Ansible version; 0.0.1 is not quite correct :-)

**Comment by mpdehaan** [comment]
Yeah unless you have changed github handles I suspect you are not Matthew Williams :)

We do not need a way to update everything on the system in one module, but we do need to be able to say:

pacman name=httpd state=latest

as well as pacman name=httpd state=installed

Assuming that is possible... I'm not an arch user, but suspect it would be.

**Comment by mpdehaan** [comment]
The other thing we need is for the "pkg" variable to be named "name" and take "pkg" as an alias, and not take "pkgs" as an alias.

Then it should be good to go.

Also what jpmens said about the version info.

Thanks very much!

**Comment by mpdehaan** [comment]
@Afterburn, let me know if you want to update the above, if not, we can take care of it.

**Comment by Cightline** [comment]
I actually have fixed up most of it. I was planning on sending it out on
Mon/Tues

**Comment by mpdehaan** [comment]
great!

**Comment by mpdehaan** [comment]
ugh, I totally mangled history for this in github when I fixed some attribution issues.  Do you mind trying to rebase this and resubmitting?  you may need to check out the repo again. 

Very sorry!

**Pull request closed without merging**
