### PR TITLE
[WIP] git module, remove the need for a wrapper script

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
 hopefuly this makes the module less fragile and less prone to leave extra files hanging.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

git
##### ANSIBLE VERSION

```
2.4/2.5
```

### CODE REVIEW

**Comment by bcoca** [comment]
cc @robinro

**Comment by abadger** [comment]
@robinro I'd like to get this in for 2.4.1 if you have time to review it.

**Comment by robinro** [comment]
Thanks @bcoca for this PR.
In the current form this PR breaks `ssh_opts` and `key_file`.
The correspond tests require a private key with github access present and set in `test/integration/targets/git/vars/main.yml` as `github_ssh_private_key`. With that the tests (specifically the missing_hostkey.yml subsection) fail.

Besides the specific fail: As mentioned before I'd be happy to deprecate the whole wrapper setup, but I'm not sure we can do this at this.
GIT_SSH_COMMAND only works with git >= 2.3.
Setting a command with arguments is not supported in GIT_SSH (i.e git before 2.3). So removing the wrapper will break support for the ssh_opts and key_file arguments for those version, including rhel7.

Options in my view:
* stop support for ssh_opts and key_file arguments for git older than 2.3: Then this PR can be merged. 
* keep the wrapper script for older git versions (and deprecate at some later point) and use GIT_SSH_COMMAND on newer git versions. We already check for the version anyway for `--depth`.

Anyhow this choice should be part of the documentation, which still mentions a wrapper script.
Maybe we can have an integration test for ssh_opts and key_file? At least testing for invalid ssh_opts is fairly easy and ensures they are correctly passed along. I'm not up to date to the latest CI developments. Can we have a ssh-key stored in some secret store accessible to the tests?

**Comment by robinro** [comment]
I'm fine with requiring git 2.3 for `ssh_opts` and `key_file`. To me this looks like the best option, since the wrapper setup is fundamentally broken and a mess to clean up.
I opened a PR against this one to fix it and clean up the unused parts and docs, see https://github.com/bcoca/ansible/pull/7.

I'm also fine with adding the wrapper again for old versions. Since I currently don't have much time and a limited dev setup, maybe one of you @bcoca @abadger can take care of this if you prefer this solution?

Also as a quick-fix in 2.4 one could revert https://github.com/ansible/ansible/commit/f8005d27379c4d67bc86cf6af83ba1b1823bb10f, go back to the 2.3 behavior and have more time for a proper fix in 2.5.

**Comment by abadger** [comment]
Current status:  f8005d2 reverted figuring out what to do with this.  Requiring newer git is a problem and we'll have to figure out how to resolve that.  (Perhaps two code paths, one for newer git and one for older?  Or, as you're saying, in 2.5, setting expectations that the features won't work with older git.)

**Comment by bcoca** [comment]
@abadger currently thinking of adding the new var (newer git) and just  keeping the old wrapper/path and fixing remote_tmp

**Comment by alikins** [comment]
Would this resolve the case described in https://github.com/ansible/ansible/issues/38104 ?

**Pull request closed without merging**
