### PR TITLE
New lookup plugin: merged_dicts

### PR DESCRIPTION
**Pull request by telbizov**
Input:  a list of dictionaries (order in the list is important).
Output: a single dictionary containing all the unique keys from all the
input dictionaries with values from the last dictionary found in the
list.
Note:   other than the merging function it acts just like with_dict.

### CODE REVIEW

**Comment by telbizov** [comment]
Not sure if I was supposed to change the non-v1 (v2?) version of it. This is my first pull request and wasn't quite sure of the structure and/or if it would be found useful at all. Could revisit later.

**Comment by bcoca** [comment]
v1 is meant as a 'quick switch to legacy' , nothing should be updated there.

now all plugins reside under lib/ansible/plugins/

**Comment by telbizov** [comment]
OK, I'll update the pull request. Aside from that, would it be merged?

**Comment by telbizov** [comment]
I'll close this one and I'll submit a new pull request for this change once I apply it in the correct place as advised.

**Pull request closed without merging**
