### PR TITLE
Add alias to aws_s3 integration test

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
aws_s3 isn't running on pull requests

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
test/integration/targets/aws_s3/aliases

##### ANSIBLE VERSION
```
2.4.0
```

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Review by mattclay — APPROVED** [review]
This looks good. However, the IAM test permissions need to be updated before the tests will pass.

**Review by mattclay — CHANGES_REQUESTED** [review]
I just realized this test is incorrectly named. The module is `s3` but the test is `aws_s3`. Please rename the test to match the module.

**Comment by mattclay** [comment]
CI failure in integration tests on python 3:

```
2017-08-07 22:21:47 TASK [s3 : wait a few seconds before continuing] *******************************
2017-08-07 22:21:47 task path: /root/ansible/test/integration/targets/s3/tasks/main.yml:70
2017-08-07 22:21:47 Pausing for 3 seconds
2017-08-07 22:21:47 (ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
2017-08-07 22:21:47 The full traceback is:
2017-08-07 22:21:47 Traceback (most recent call last):
2017-08-07 22:21:47   File "/root/ansible/lib/ansible/executor/task_executor.py", line 125, in run
2017-08-07 22:21:47     res = self._execute()
2017-08-07 22:21:47   File "/root/ansible/lib/ansible/executor/task_executor.py", line 526, in _execute
2017-08-07 22:21:47     result = self._handler.run(task_vars=variables)
2017-08-07 22:21:47   File "/root/ansible/lib/ansible/plugins/action/pause.py", line 128, in run
2017-08-07 22:21:47     stdin = self._connection._new_stdin.buffer
2017-08-07 22:21:47 AttributeError: 'str' object has no attribute 'buffer'
2017-08-07 22:21:47 
2017-08-07 22:21:47 fatal: [localhost]: FAILED! => {
2017-08-07 22:21:47     "failed": true,
2017-08-07 22:21:47     "msg": "Unexpected failure during module execution.",
2017-08-07 22:21:47     "stdout": ""
2017-08-07 22:21:47 }
2017-08-07 22:21:47 
```

That sure looks like a bug in the pause module, which we don't have an integration test for.

**Comment by s-hertel** [comment]
Split into:
https://github.com/ansible/ansible/pull/28396 and https://github.com/ansible/ansible/pull/28398

**Pull request closed without merging**
