### PR TITLE
replaced e.message with unicode(e)

### PR DESCRIPTION
**Pull request by berendt**
BaseException.message has been deprecated as of Python 2.6

### CODE REVIEW

**Comment by jimi-c** [comment]
Is this change compatible with python 2.4?

**Comment by jctanner** [comment]
@berendt any response to @jimi-c's question?

**Comment by berendt** [comment]
Sorry, I'm busy at the moment. I'll take care next week.

**Comment by mpdehaan** [comment]
Much appreciated.

Will close this in a few days if no response.

**Comment by mpdehaan** [comment]
Closing due to lack of response.

**Pull request closed without merging**
