### PR TITLE
MySQL replication ansible module

### PR DESCRIPTION
**Pull request by banyek**
Could be check
- Master status
- Slave status

Could be set:
- Change master 

Other:
- Can stop replication thread
- Can start replication thread

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ok, just merged this into a branch to take a look -- looks good, glad to see this!

Needs to add an EXAMPLES section like the other modules so people can see an example of this being used in context.

"possible values:" in the docs should be "choices", also run the DOCUMENTATION section through yamllint.com

startslave and stopslave were not listed in choices in the documentation block.

Might also be useful to post to the mailing list to see if others would like to help test.

Thanks!

**Comment by banyek** [comment]
Hello Michael,

ok, I've made the changes in documentation section as you asked. You can check it. 

br, 
  Balazs

**Comment by mpdehaan** [comment]
choices should be a YAML list still, and not just a list of comma seperated strings, otherwise looks fine.

Can you close this one and resubmit just the new module in one new pull request (perhaps on a new branch?)  That way we don't get the commit about mysql_variables in there.

Thanks!

**Comment by banyek** [comment]
Ok, I made today the changes, and the new pull request. 
Btw. the mysql_variables to near to finish too, so I'll make an another pull request for that - maybe on next week.
I'm also planning to make a callback plugin for Atlassian HipChat.

**Pull request closed without merging**
