### PR TITLE
Added volume_tags to ec2_vol

### PR DESCRIPTION
**Pull request by lardcanoe**
Similar to instance_tags in ec2

### CODE REVIEW

**Comment by mpdehaan** [comment]
We do not want JSON parameters to modules.

The tags here really should use the complex argument support vs "from_json".

https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/AqvjT_yMsQQ

If they can just be lists, why not split them on commas also if they are a string also in addition to the above?

**Comment by mpdehaan** [comment]
closing this for now, will let you resubmit.  thanks!

**Comment by lardcanoe** [comment]
I can change to complex args, but I am having trouble determining the best way to do it when working with more than one volume at a time. My use case is I am creating up to 8 at a time for a raid set for 1 to N servers, and I want each to have a different name, and even possibly other different tags.

This works no problem, but then all volumes will have the same values for tags, which is useless.
  vars:
    volume_tags:
      Name: Hello
      Type: World

My playbook that I am using as the use case for changing the ec2_vol module.

vars:
volumes:
- { device: "/dev/sdf", size: 1}
- { device: "/dev/sdg", size: 1}
- { device: "/dev/sdh", size: 1}

tasks:
- action: ec2_facts
  register: ec2
- local_action: ec2_vol 
  instance=${ec2.ansible_facts.ansible_ec2_instance_id} 
  volume_size=${item.size} 
  device_name=${item.device}
  with_items: $volumes
  sudo: false

I'd like to change it to:

vars:
volumes:
- { device: "/dev/sdf", size: 1, volume_tags: { Name: "${ec2.ansible_facts.ansible_ec2_instance_id} - vol 1", Type: "vol type a" } }
- { device: "/dev/sdg", size: 1, volume_tags: { Name: "${ec2.ansible_facts.ansible_ec2_instance_id} - vol 2", Type: "vol type b " } }
- { device: "/dev/sdh", size: 1, volume_tags: { Name: "${ec2.ansible_facts.ansible_ec2_instance_id} - vol 3", Type: "vol type c", Other: "only this vol has this tag" } }

tasks:
- action: ec2_facts
  register: ec2
- local_action: ec2_vol 
  instance=${ec2.ansible_facts.ansible_ec2_instance_id} 
  volume_size=${item.size} 
  device_name=${item.device}
  args: { volume_tags: $item.volume_tags }
  with_items: $volumes
  sudo: false

Problems:
1. In this case, $item.volume_tags is a str, not a dict, in the args line. This a bug, feature, user error?
2. I want to specify the instance name in the tag name of each volume but I don't have access to it when defining the volume list in the var files.

**Comment by mpdehaan** [comment]
There is too much text here for me to understand exactly what the question
is.  Can you distill this?

**Pull request closed without merging**
