### PR TITLE
Add from_table filter

### LINKED ISSUE #68227: filter plugin for converting PrettyTable output.
##### SUMMARY
Add a filter for converting PrettyTable output into a list of dictionaries.
It is useful to parse the various CLI (e.g. mysql, openstack) outputs.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
from_table filter

##### ADDITIONAL INFORMATION

```yaml

```

### PR DESCRIPTION
**Pull request by r0ckpine**
##### SUMMARY

Add filter plugin to perse PrettyTable output.

Fixes #68227

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

from_table filter

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mkrizek** [comment]
!waffling core_review

**Comment by jctanner** [comment]
!waffling needs_revision

**Comment by r0ckpine** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@r0ckpine Thanks for the contribution. Please submit this PR to https://github.com/ansible-collections/community.general. Thanks.

needs_info

**Pull request closed without merging**
