### PR TITLE
New module: manage debian network interfaces file /etc/network/interfaces (system/interfaces_file)

### PR DESCRIPTION
**Pull request by hryamzik**
##### SUMMARY

This module is designed to manage interface options in Debian based systems.

Even though it doesn't currently support all the variety of options it's still very useful for network configuration changes.

It's not based on any library and it's configuration logic was copied from [C code of `ifupdown`](/wido/ifupdown/blob/master/config.c) so it reads configuration as designed and not as developers of some similar-targeted python libraries do.

This module was developed more than a year ago and [was marked with `shipit`](/ansible/ansible-modules-extras/pull/2027) but was never really added to ansible. Also mentioned at #24660.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

interfaces_file

### CODE REVIEW

**Comment by hryamzik** [comment]
OK, looks like some conventions have changed after module was approved last time. I'll write some tests before making any code changes. Currently blocked with #25333.

**Comment by alikins** [comment]
For the path, I think I would lean towards lib/ansible/modules/system/interfaces_file.py (since it is for manipulating a specific system config file vs generic file manipulation)

**Comment by hryamzik** [comment]
@alikins sounds reasonable, I'll move it to `system`.

**Comment by hryamzik** [comment]
```
lib/ansible/modules/files/interfaces_file.py:0:0: E319 RETURN.ifaces.contains: extra keys not allowed @ data['contains']. Got {'ifaces': {'description': 'interface dictionary', 'type': 'dictionary', 'returned': 'success', 'contains': {'eth0': {'description': 'Name of the interface', 'type': 'dictionary', 'returned': 'success', 'contains': {'down': {'description': 'list of C(down) scripts', 'type': 'list', 'returned': 'success', 'sample': ['route del -net 10.10.10.0/24 gw 10.10.10.1 dev eth1', 'route del -net 10.10.11.0/24 gw 10.10.11.1 dev eth2']}, 'mtu': {'description': 'other options, all velues returned as string...
```

I don't get it, is it an issue with my return structure or test isn't smart enough to understand it?

P.S.:
```yml
ifaces:
    description: interfaces dictionary
    returned: success
    type: dictionary
    contains:
      ifaces:
        description: interface dictionary
        returned: success
        type: dictionary
        contains:
          eth0:
            description: Name of the interface
            returned: success
            type: dictionary
            contains:
              address_family:
                description: interface address family
                returned: success
                type: string
                sample: "inet"
              method:
                description: interface method
                returned: success
                type: string
                sample: "manual"
              mtu:
                description: other options, all values returned as strings
                returned: success
                type: string
                sample: "1500"
              pre-up:
                description: list of C(pre-up) scripts
                returned: success
                type: list
                sample:
                  - "route add -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                  - "route add -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
              up:
                description: list of C(up) scripts
                returned: success
                type: list
                sample:
                  - "route add -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                  - "route add -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
              post-up:
                description: list of C(post-up) scripts
                returned: success
                type: list
                sample:
                  - "route add -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                  - "route add -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
              down:
                description: list of C(down) scripts
                returned: success
                type: list
                sample:
                  - "route del -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                  - "route del -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
```

**Comment by hryamzik** [comment]
My local test looks a bit defferent:
```
$ time ./test/runner/ansible-test sanity --test pep8 interfaces_file
Sanity check using pep8
ERROR: PEP 8: lib/ansible/modules/system/interfaces_file.py:54:161: E501 line too long (377 > 160 characters) (current)
ERROR: PEP 8: There are 1 issues which need to be resolved.
```

**Comment by hryamzik** [comment]
So two questions:

1. Do I have to fix inherited `contains`?
    ```
    lib/ansible/modules/files/interfaces_file.py:0:0: E319 RETURN.ifaces.contains: extra keys not allowed @ data['contains']. Got {'ifaces': {'description': 'interface dictionary', 'type': 'dictionary', 'returned': 'success', 'contains': {'eth0': {'description': 'Name of the interface', 'type': 'dictionary', 'returned': 'success', 'contains': {'down': {'description': 'list of C(down) scripts', 'type': 'list', 'returned': 'success', 'sample': ['route del -net 10.10.10.0/24 gw 10.10.10.1 dev eth1', 'route del -net 10.10.11.0/24 gw 10.10.11.1 dev eth2']}, 'mtu': {'description': 'other options, all velues returned as string...
    ```

    Here's how `yml` looks like:
    ```yml
    ifaces:
        description: interfaces dictionary
        returned: success
        type: dictionary
        contains:
          ifaces:
            description: interface dictionary
            returned: success
            type: dictionary
            contains:
              eth0:
                description: Name of the interface
                returned: success
                type: dictionary
                contains:
                  address_family:
                    description: interface address family
                    returned: success
                    type: string
                    sample: "inet"
                  method:
                    description: interface method
                    returned: success
                    type: string
                    sample: "manual"
                  mtu:
                    description: other options, all values returned as strings
                    returned: success
                    type: string
                    sample: "1500"
                  pre-up:
                    description: list of C(pre-up) scripts
                    returned: success
                    type: list
                    sample:
                      - "route add -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                      - "route add -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
                  up:
                    description: list of C(up) scripts
                    returned: success
                    type: list
                    sample:
                      - "route add -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                      - "route add -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
                  post-up:
                    description: list of C(post-up) scripts
                    returned: success
                    type: list
                    sample:
                      - "route add -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                      - "route add -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
                  down:
                    description: list of C(down) scripts
                    returned: success
                    type: list
                    sample:
                      - "route del -net 10.10.10.0/24 gw 10.10.10.1 dev eth1"
                      - "route del -net 10.10.11.0/24 gw 10.10.11.1 dev eth2"
    ```

2. Do I have to fix `ansible-test sanity --test pep8` issues? Is there any formatter that can do this automatically? And I'm not sure how to break this line:
    ```
    lib/ansible/modules/system/interfaces_file.py:50:161: E501 line too long (377 > 160 characters)
    ```

Others issues seem to be fixed.

ready_for_review

CC @gundalow @bcoca

**Comment by gundalow** [comment]
1) If you change the return to
```
type: complex
contains:
```
That should do the trick

2) For the long `description:` line you can split it into multiple lines by doing
```

options:
  someoptions:
    description:
      - This is a fairly long sentence
        See the examples!
        More detail goes here
``

**Comment by hryamzik** [comment]
Applied formatting with `autopep8 --verbose --in-place --max-line-length 160 filename`, should work fine now.

P.S. I love pep8 style....
```diff
     module = AnsibleModule(
-        argument_spec = dict(
-            dest      = dict(default='/etc/network/interfaces',required=False),
-            iface     = dict(required=False),
-            option    = dict(required=False),
-            value     = dict(required=False),
-            backup    = dict(default='no', type='bool'),
-            state     = dict(default='present', choices=['present', 'absent']),
+        argument_spec=dict(
+            dest=dict(default='/etc/network/interfaces', required=False),
+            iface=dict(required=False),
+            option=dict(required=False),
+            value=dict(required=False),
+            backup=dict(default='no', type='bool'),
+            state=dict(default='present', choices=['present', 'absent']),
         ),
```

**Comment by hryamzik** [comment]
@gundalow oops, I didn't see your label and stashed last two commits to make history more clear.

**Comment by hryamzik** [comment]
ready_for_review

**Comment by gundalow** [comment]
Closing & re-opening to retrigger CI

**Comment by gundalow** [comment]
Unit tests are failing on Python 3.5 & 3.6, see
https://app.shippable.com/github/ansible/ansible/runs/24819/4/tests

**Comment by hryamzik** [comment]
I wasn't aware ansible supports python 3, I'll take a look, thanks.

**Comment by hryamzik** [comment]
That's wired:

```diff
-     "iface": "aggi",
+     "iface": "aggi", 
```

So `json.dumps` with `sort_keys=True` and `indent=4` adds an extra space to end of lines in python 3. I can change format to one-line `json` but it doesn't make much sense. I'll try to reproduce this locally.

P.S.:

> Note Since the default item separator is ', ', the output might include trailing whitespace when indent is specified. You can use separators=(',', ': ') to avoid this.

P.P.S.: That was python 2 who added extra spaces, I've removed them, waiting for tests.

**Comment by hryamzik** [comment]
ready_for_review

**Comment by hryamzik** [comment]
@gundalow any ideas why we are stuck again?

**Comment by gundalow** [comment]
@hryamzik https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#new-modules
Need to find some people to give shipit - there is one for you

**Comment by hryamzik** [comment]
As we can see nobody responded in a month. CC @bcoca.

**Comment by EvanK** [comment]
While I'm not very familiar with debian network interface formats, it looks good (nice to see tests too)...so AFAIC: shipit

**Comment by LinusU** [comment]
I'm no expert either but it looks good 👍 

shipit

**Pull request merged**
