### PR TITLE
NEW Source Control module: git add/commit/push

### PR DESCRIPTION
**Pull request by lvrfrc87**
##### SUMMARY
New module to add `git add` `git commit` and `git push` functionalities to Ansible.

This is particularly useful for example, network automation where Ansible is used in a CI/CD pipeline for template rendering and device provisioning. With this modules, all changes done in the repo during pipeline iteration (i.e. rendered template or test results) can be pushed back into the repo. 

This module has been requested back in December 2018. See here: https://github.com/ansible/ansible/issues/50334

`https` and `ssh` git channels are both supported. 

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
```
      git_acp:
        folder_path: /Users/federicoolivieri/git/git_test_module
        user: Federico87
        token: zECE5x88MtfWz8DofZYx
        comment: Add [ test.txt, tax.txt ]
        add: [ test.txt, tax.txt ]
        branch: master
        mode: https
        url: https://gitlab.com/networkAutomation/git_test_module.git
```
```
      git_acp:
        folder_path: /Users/federicoolivieri/git/git_test_module
        comment: Add .
        branch: master
        mode: ssh
        url: git@gitlab.com:networkAutomation/git_test_module.git
```

### CODE REVIEW

**Comment by gundalow** [comment]
Hi @FedericoOlivieri 
Unfortunately, I missed you ni `#ansible-devel`
This repository `ansible/ansible` isn't accepting any more Pull request.

The source control modules are going in `community.general`

Could you please raise a new PR against https://github.com/ansible-collections/community.general/

It's amazing that you've added integration test, thank you.

If you look at the existing integration tests we have for the `git` module they create a local repository for testing. This should avoid the conflicts you are seeing, as well as the dependency on your your gitlab instance. https://github.com/ansible/ansible/blob/devel/test/integration/targets/git/tasks/setup-local-repos.yml 

In a single PR could you please
1) Create an new directory called `plugins/modules/source_control/git/`
2) Tests go into  `tests/integration/targets`
3) Update tests to use local repos

**Comment by tadeboro** [comment]
@FedericoOlivieri Do note that if you want to test push/fetch/pull operations, you will almost certainly want to set up a bare repo. Git will complain if you try to push to the repo that has something check out.

General steps for creating and population a bare git repo would be:

```
git init --bare repo.git

git clone x.git local_copy
cd local_copy
echo foo > foo.txt
git add foo.txt
git commit -m "Add foo"
git push
```

**Comment by FedericoOlivieri** [comment]
@tadeboro @gundalow Thanks for your suggestion. I will raise a new PR against `community.general`. Regarding the integration test, your suggestions are indeed valuable and I will try to draft something based on that.

However, this module aim to commit and push changes in remote via SSH and HTTPs with user and token. Testing against a local repo won't let trigger all the commands required to push changes to a remote.

**Comment by FedericoOlivieri** [comment]
New PR: https://github.com/ansible-collections/community.general/pull/57

**Pull request closed without merging**
