### PR TITLE
Fix iam_password_policy integration tests

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY
Fix iam_password_policy integration tests (part of #55775)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/iam_password_policy.py

##### ADDITIONAL INFORMATION
Fixes the broken integration tests and adds a regression test for #59102

### CODE REVIEW

**Comment by willthames** [comment]
This needs some permissions added to hacking/aws-config/testing-policies/security-policy.json I would think?

**Comment by tremble** [comment]
@willthames It does indeed, I'd been working with a custom policy.

**Comment by tremble** [comment]
@willthames policy updated, could you take another look please.

**Comment by willthames** [comment]
All tests passed locally, thanks @tremble

**Pull request merged**
