### PR TITLE
ovirt refactor uploading disk and downloading 

### LINKED ISSUE #39613: oVirt disk module uses inefficient upload function
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

oVirt
##### ANSIBLE VERSION

```
2.5.2
```

##### SUMMARY

The code (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_disk.py#L366 for example is inefficient, therefore somewhat slow.
For example, there's no need at all for transfer_service.extend() for each chunk.
See https://gerrit.ovirt.org/gitweb?p=ovirt-imageio.git;a=blob;f=examples/upload;h=225f2144d67d276275a731869a6e2f02c6190537;hb=HEAD for an example (upload, but download is very similar).

This could have an important positive performance boost.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by mnecas**
##### SUMMARY

Fixes #39613

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ovirt
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mnecas/Desktop/Projects/Redhat/ansible/lib/ansible/modules/cloud/ovirt']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by machacekondra — COMMENTED** [review]
LGTM, is it verified?

**Comment by mwperina** [comment]
Looks good to me.
Daniel, could you also please take a look?

@danielerez

**Review by mwperina — APPROVED** [review]
shipit

**Comment by machacekondra** [comment]
shipit

**Pull request merged**
