### PR TITLE
Initialise paramiko PTY from caller environment

### PR DESCRIPTION
**Pull request by madduck**
This should solve #2065. It also postpones PTY creation until we know that we actually need it (for sudo).

### CODE REVIEW

**Comment by mpdehaan** [comment]
Slick!  In queue for testing!

**Comment by mpdehaan** [comment]
Does seem like it may be a bad idea to set COLUMNS and LINES from the /local/ environment, as on my Mac right now I don't have those variables set at all.   

Is there a reason it was not ending with just chan.get_pty() ?

**Comment by madduck** [comment]
If either of the variables are unset, then defaults get used. Defaults of 0 for COLUMNS and LINES means that they won't be set. At least this is what my tests suggest.

I don't know what you mean with "not ending with just chan.get_pty()".

**Comment by mpdehaan** [comment]
I meant not passing them at all.

The code read that the default was 0, not None, so that's why I asked.
That's explicitly setting them to 0.   However, if no damage is done, then
it works :)

**Comment by madduck** [comment]
I read `paramiko.Channel.get_pty` docs to require integers as parameters. I think I tried it and `None` would get an exception.

**Comment by mpdehaan** [comment]
Works for me.  I do not doubt paramiko is weird in that regard :)

**Comment by madduck** [comment]
Section 6.2 of RFC 4254 (SSH protocol) does specify to use 0 for height/width if those values should _not_ be set.

**Comment by mpdehaan** [comment]
go RFCs, go!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
