### PR TITLE
Add module aliases back in hardcoded module_defaults list

### LINKED ISSUE #61068: module_defaults don't apply to aliased modules
##### SUMMARY

If you use module_defaults (especially on a group) but call the module by one of its aliases then it fails to pick up the defaults

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/config/module_defaults.yml

##### ANSIBLE VERSION

Triggered this against devel (because _facts was renamed to _info)

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/home/mchappel/.ansible.cfg) = [u'timer', u'profile_tasks']
HOST_KEY_CHECKING(/home/mchappel/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/mchappel/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL7

##### STEPS TO REPRODUCE
```
- name: Run ec2_asg integration tests.
  module_defaults:
    group/aws:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      security_token: "{{ security_token | default(omit) }}"
      region: "{{ aws_region }}"
  block:
    - name: Find AMI to use 
      ec2_ami_info:
        owners: 'amazon'
        filters:
          name: '{{ ec2_ami_name }}'
      register: ec2_amis
    - name: Find AMI to use 
      ec2_ami_facts:
        owners: 'amazon'
        filters:
          name: '{{ ec2_ami_name }}'
      register: ec2_amis
```
##### EXPECTED RESULTS

ec2_ami_facts and ec2_ami_info should both use the defaults.

##### ACTUAL RESULTS

ec2_ami_info uses the module_defaults, ec2_ami_facts doesn't.

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
module_defaults should keep working for previous module names

Fixes #61068

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/config/module_defaults.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
Thanks for fixing this! I wasn't aware that it doesn't work for aliases...

**Comment by felixfontein** [comment]
For OpenStack, there's at least one new module for 2.9 (os_group_info) which isn't in the module_defaults list.

**Comment by s-hertel** [comment]
@felixfontein Yeah, it was a surprise to me too, sorry for not catching it during the initial pull requests. I think I'm going to let re-syncing the list for new modules (like os_group_info) be a follow-up PR. I just replaced anything that was removed from module_defaults since it could break playbooks that were previously working.

**Review by felixfontein — APPROVED** [review]
I did a diff with the same file of stable-2.8, compared to stable-2.8 there are now only new entries and no removed ones.

shipit

**Pull request merged**
