### PR TITLE
rabbitmq_binding: Fix for bug introduced in #18437

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
##### SUMMARY
Fix property name.

Fixes bug noted in comment https://github.com/ansible/ansible/pull/18437#pullrequestreview-164598516

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
rabbitmq_binding

##### ANSIBLE VERSION
```paste below
devel
```

##### ADDITIONAL INFORMATION
ping @Akasurde @hyperized

### CODE REVIEW

**Comment by hyperized** [comment]
shipit

**Comment by Akasurde** [comment]
@Jorge-Rodriguez Your branch contains merge-commit. Could you please rebase it and let me know ? Rest LGTM.

**Comment by Jorge-Rodriguez** [comment]
Working on it, update coming along soon

**Comment by Jorge-Rodriguez** [comment]
@Akasurde done
Shippable complains, but it seems it's an unrelated error having to do with docker.

**Comment by Akasurde** [comment]
@Jorge-Rodriguez Thanks for the contribution. @hyperized Thanks for identifying bug and reviewing.

**Pull request merged**
