### PR TITLE
support for google cloud storage module

### PR DESCRIPTION
**Pull request by bennojoy**
This module adds the support for Google Cloud Storage api V1. Most of the code is taken from S3 module as GCS api V1 is compatible with S3 API's. Modifications has been made to support GCS and feature to support canned ACL's has been added.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi, thanks for this.

I am not sure we should massively abbreviate the module here.   gc_storage might be better.

There's no pull request for a gs module yet so I am confused and that in the documentation.

all the create/delete/etc code should be split into smaller functions for readability

Thanks for this, here are some review notes.

This may not be everything but is a first pass.

Variables like "keyrtn" should not be run together per coding conventions.   "key_rc" should be fine.

There is a suspicious sys.exit towards the end.  In this case, should it not use module.exit_json or module.fail_json?

FIXMEs still in code should be removed:

"# Need to research how to create directories without "populating" a key, so this should just do bucket creation for now.
-    # WE SHOULD ENABLE SOME WAY OF CREATING AN EMPTY KEY TO CREATE "DIRECTORY" STRUCTURE, AWS CONSOLE DOES THIS."

sufficient to say something isn't supported yet.

indentation issues around line 376

around line 379 the variable "sum_matches" is not used, looks to be an unneeded assignment

There are commented out exit lines around line 360
-                if overwrite is True:

Should be written as:

```
    if overwrite
```

There is no need for a sys.exit after a fail_json call because fail_json and exit_json will call sys.exit

Getting the GC access key from the enviornment seems undesriable because someone using AWX would not know the parameter could not be input that way.   Seems we should possibly require it and not do the environment part.  This may also be a consistency issue with the EC2 code.

around line 168 there is some code to check if a bucket is not None.   It does not seem the bucket could be None without raising an exception so this check does not seem to add value and probably should be removed.

Review strings for correctness such as this typo:

```
 The object's permission as been set to authenticated-read

 This option let's => This option lets

 etc
```

any concerns about checking about what version of Boto is needed?

**Comment by bennojoy** [comment]
@mpdehaan 

Sure, will work on the comments and send a PR soon.

**Comment by bennojoy** [comment]
The module has been rewritten with the fixes for comments above.

**Comment by mpdehaan** [comment]
Hi Benno,

This looks better thanks.

I have some things in here I'd like to fix but can merge and take care of these.

Taking notes though:

expiry should also be "expiration", it can have a default to "expiry" but recently fixed that for some other module.

I see some tabs or non-four space indents in here that must also be fixed.

Typo:

"+                module.fail_json(msg="Key/Bucket doesnt exist", failed=True)"

"does not" or "doesn't", 

Other typos in the documentation section:

"This url is only avaialbe"

may be some other things.

I'm merging this now and will tweak this a bit, and would appreciate help testing with mods.

Thanks!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
