### PR TITLE
Feature ignore silently

### PR DESCRIPTION
**Pull request by rgarrigue**
Hi

This is the improved version of my first attempt to make a "ignore_errors: silently" option (first one behing here: ansible#5439)

Test wise, make tests is OK. Here's my test playbook for the feature.

```
- hosts: all
  tasks:
  - command: /bin/false
    ignore_errors: silently
  - command: "{{ item }}"
    with_items:
    - echo one; /bin/false
    - echo two; /bin/false
    ignore_errors: silently

  - service: name=dbgqskjbh state=stopped enabled=no
    ignore_errors: silently
  - service: name={{item}} state=started
    with_items:
    - jhvbsqdj
    - lkjfqsbs
    - sshd
    - ssh
    ignore_errors: silently
  - name: serviceS 3 err 1 ok with_items plus name
    service: name={{item}} state=started
    with_items:
    - jhvbsqdj
    - lkjfqsbs
    - sshd
    - ssh
    ignore_errors: silently
```

I hope this is ok regarding non-merge commit, rebase etc. I forked in github, cloned localy, created a feature branch... but I don't fully understand what I'm doing with git+hub! I'ld be glad for advice on the topic if any required :-)

Cheers,
Rémy

PS: second attempt, I managed to make my pull request the reverse way X_X

### CODE REVIEW

**Comment by rgarrigue** [comment]
Up. Previous version of ansible allowed me to put a "silently" in my playbook which was assimilated to yes, so I did that waiting for this pull request to be accepted. Seems 1.6.2 is not tolerant anymore.

So is it gonna be accepted/refused somewhen, or only important contribution are deemed worth of being examined?

**Comment by amenonsen** [comment]
The code in devel has changed enough that this can't be trivially resolved. To be honest, I don't really understand the point of the original PR, especially since there's no documentation (which I personally think should be a minimum standard for patches that add new configuration options/values).

I think this PR should be closed, unless @rgarrigue wants to rework the commit and resubmit.

**Comment by bcoca** [comment]
So the code makes it easy for you to use a custom callback plugin, if you really wan't to skip skipped output you can easily add it as a plugin, no need to modify the existing code.

**Comment by rgarrigue** [comment]
It was discussed and made sense a year and a half ago. Since no one cared about cosmetic stuff, no point in discussing it further.

**Comment by bcoca** [comment]
added new callback to 2.0 called 'skippy' you can use that now to do this

**Pull request closed without merging**
