### PR TITLE
Added virt_net 'latest' state

### PR DESCRIPTION
**Pull request by cristiklein**
##### SUMMARY
Added a new state 'latest' to the virt_net module. This new state ensures that the virtual network is configured as desired by the operator. If (and only if) the XML has changed, then the network is
stopped, undefined, re-created and started, since libvirt lacks support for on-the-fly change of virtual networks. As usually, the module does not change anything that needs no change.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
virt_net

##### ANSIBLE VERSION
I tested this new module against:
```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION
I needed to ensure that a virtual network is configured according to an XML and no existing solution was satisfactory.

The 'present' state does not update the configuration of the virtual network. To ensure the virtual network is configured according to a template file, one had to always destroy the virtual network (state 'absent') and re-create it (state 'present'), which is undesirable: The VM lose network connectivity even if this was not necessary.

One could write a playbook to ensure that the network is only changed if its XML was changed, but that required 4 tasks and looked difficult to read.

### CODE REVIEW

**Review by drybjed — APPROVED** [review]
shipit

**Comment by gthieleb** [comment]
Will that feature help with race conditions, when multiple networks are defined via delegate_to when the originating template does not contain the bridge name?

main.yml:

	- name: "create additional virt networks"
  	  include: virt-additional-network.yml
	  delegate_to: "{{ host }}"

virt-additional-network.yml

	- virt_net: command=list_nets
	  register: existing

	- debug: msg="{{ existing.list_nets }}"

	- set_fact: network="{{ network | default({}) | combine({'libvirt_network_name':cidr.replace('/', '_')}) }}"

	- debug: msg="{{ network }}"

	- virt_net: command=define state=present name="{{ network.libvirt_network_name }}" xml="{{ lookup('template', 'networks/isolated.xml.j2') }}" autostart=1
	  when: not network.libvirt_network_name in existing.list_nets

	- virt_net: command=start name="{{ network.libvirt_network_name }}"
	  when: not network.libvirt_network_name in existing.list_nets

template:
	
	<network>
	  <name>{{ network.libvirt_network_name }}</name>
	  <ip address='{{ network.gateway }}' netmask='{{ network.netmask }}'>
	  </ip>
	</network>

network dict:

        "additional-routes": null, 
        "address": "192.168.72.0", 
        "function": "Admin", 
        "gateway": "192.168.72.4", 
        "inner-route": null, 
        "libvirt_network_name": "192.168.72.0_23", 
        "netmask": "255.255.254.0", 
        "outer-route": null, 
        "route": null, 
        "stage": "P", 
        "vlan": "2", 

raises:

	TASK [libvirt : virt_net]***********************************************************************************************************************************************
	changed: [vm01p999 -> localhost]
	changed: [vm94p999b -> localhost]

	TASK [libvirt : virt_n**************************************************************************************************************************************************
	fatal: [vm94p999b -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "error creating bridge interface virbr2: File exists"}
	ok: [vm01p999 -> localhost]

**Comment by cristiklein** [comment]
Hello,

I am unsure to understand what is the intention behind your script. Could
you give more details about the intended use-case?

Regards,
Cristian

2017-05-12 13:33 GMT+02:00 gthieleb <notifications@github.com>:

**Comment by gthieleb** [comment]
@cristiklein the intention is to create test vms and before that make sure that the correct networks for each vm is created. 

The usecase is to mimic datacenter networks in a libvirt nutshell. 

1. A VM's DNS name is looked up to gather the CIDR of the real world network. 
2. CIDR is used to lookup in a json file where all real world network (gateway, netmask, vlan) is collected. 
3. The playbook define the network for each VM on the libvirt host within the same playbook (using delegate_to). 
4. Name of the network is the CIDR but slash is replaced by underline.

>> 'libvirt_network_name':cidr.replace('/', '_')

Unfortunately its not possible to define and start networks in one step. So when 2 different networks are defined they have for some reason the same `virbrX` bridge. That makes starting the 2nd network fails.

**Comment by cristiklein** [comment]
I am a bit new to ansible, so please bear with me. :)

In your original playbook, I'm not sure to understand why *all* networks
are first defined, then started. The ansible emulator inside my brain tells
me that the first network should first be defined, then started, before
dealing with the second network. Am I missing something?

Also, I feel that the failure is rather a libvirt bug. Should it be libvirt
who fills in the value of the `virbrX` bridge with something previously
unused?

Finally, since the `latest` state defines (if necessary) and starts (if
necessary) a network in a single step, it might work around the error you
encounter. Would you be so kind to test and report?

2017-05-20 9:04 GMT+02:00 gthieleb <notifications@github.com>:

**Pull request closed without merging**
