### PR TITLE
Fix hostname / fqdn fact on CentOS

### PR DESCRIPTION
**Pull request by tonk**
This fixed issue #2721

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ok so partition is Python 2.5. 

Since our modules need to be Python 2.4 compliant, can you change the "partition" to just use "split" ?

**Comment by mpdehaan** [comment]
Thanks!

**Comment by tonk** [comment]
Not really the way I wanted, but it's in there, finally

**Comment by mpdehaan** [comment]
I went ahead and applied a fix to avoid the conflict commits in history.

Thanks!

**Pull request closed without merging**
