### PR TITLE
git_path option to the git module

### PR DESCRIPTION
**Pull request by skyl**
Allows a `git_path=/path/to/git` option to the git module.

### CODE REVIEW

**Comment by jimi-c** [comment]
Yes, documentation is required for all module params. Please get that added and we'll get this in queue to review. Thanks!

**Comment by skyl** [comment]
hi @jimi-c, I added the documentation. Pardon the name of the branch, btw.

**Comment by skyl** [comment]
hrm, would the version be 1.3.3 or 1.4? Should have asked.

**Comment by jimi-c** [comment]
The version_added would be 1.4.

**Comment by mpdehaan** [comment]
Not trying to hold this up, but seems like if we add git_path we should be consistent for the other SCM modules, and if we do that, the parameter should be something like "executable" or something so it could be standardized between them?

**Comment by skyl** [comment]
Sounds good, I can probably make that happen tonight. I will probably make a new branch/PR.

**Comment by skyl** [comment]
The other modules are not quite as simple. bzr hardcodes a bare "bzr" in a lot of places. The hg module (without refactoring) would require us to pass the executable path to every function to end up at the _hg_command.

I have done what I think is right and refactored the other modules to varying extents. I may issue separate pull requests b/c the level of involvement in the other modules is greater.

**Pull request closed without merging**
