### PR TITLE
mock_unfrackpath_noop: handle 'follow' parameter

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
`follow` parameter has been added to `unfrackpath` method, this pull-request update the related mock accordingly.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
test/units/mock/path.py

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0 (devel da540b5c48) last updated 2017/07/12 00:10:06 (GMT +200)
```

### CODE REVIEW

**Comment by samdoran** [comment]
@mattclay Can you verify the tests ran properly with this change?

**Comment by jimi-c** [comment]
@mattclay I went ahead and merged this. If it ends up causing problems let me know and I'll fix it.

@pilou- Thanks!

**Comment by mattclay** [comment]
@samdoran Yes, the change triggered all tests to run, as seen in the [console log](https://app.shippable.com/github/ansible/ansible/runs/28272/3/console) here:

```
2017-07-11 23:55:31 Mapping 1 changed file(s) to tests.
2017-07-11 23:55:31 test/units/mock/path.py -> units: test/units/
```

You can also see the test counts in the Test Data column showing 1800+ passing tests for each tested python version: https://app.shippable.com/github/ansible/ansible/runs/28272/3/console

**Comment by samdoran** [comment]
Thanks @mattclay!

**Pull request merged**
