### PR TITLE
Role meta install_dependencies

### PR DESCRIPTION
**Pull request by DaazKu**
##### SUMMARY

Implementation of https://github.com/ansible/ansible/issues/68196

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

role

### CODE REVIEW

**Comment by DaazKu** [comment]
ready_for_review

**Comment by sivel** [comment]
This is not the direction we want this to go. Instead please see https://github.com/ansible/proposals/issues/57

**Review by sivel — CHANGES_REQUESTED** [review]
Submitting an actual review.  In its current form we are not prepared to accept this. If you are willing please update this PR to implement https://github.com/ansible/proposals/issues/57 to utilize a `meta/requirements.yml` we will review it for potential future inclusion.

**Comment by DaazKu** [comment]
Unfortunately I don't, at the moment, the time to do another implementation that meets ansible/proposals#57.

**Pull request closed without merging**
