### PR TITLE
template: fix KeyError: 'undefined variable: 0

### LINKED ISSUE #20494: "KeyError: 'undefined variable: 0'" when using {% import %} and {% include %}
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- template expansion

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 16.04. ansible installed via pip.

~~~
$ pip list --format=legacy
ansible (2.2.1.0)
cffi (1.9.1)
configobj (5.0.6)
crit (0.0.1)
cryptography (1.7.1)
dynagen (0.9.0)
enum34 (1.1.6)
idna (2.2)
ipaddr (2.1.11)
ipaddress (1.0.18)
Jinja2 (2.9.4)
MarkupSafe (0.23)
paramiko (2.1.1)
pip (9.0.1)
protobuf (3.1.0.post1)
pyasn1 (0.1.9)
pycparser (2.17)
pycrypto (2.6.1)
python-apt (1.1.0b1)
PyYAML (3.12)
setuptools (33.1.1)
six (1.10.0)
wheel (0.29.0)
~~~

##### SUMMARY

When one template *imports* another one, and then *includes* another template, it barfs with "KeyError: 'undefined variable: 0'"

##### STEPS TO REPRODUCE

```yaml
# test.yml
- hosts: localhost
  tasks:
    - template:
        src: foo
        dest: /tmp/foo

# templates/foo
{% import 'qux' as qux with context %}
hello world
{{ qux.wibble }}
{% include 'bar' %}

# templates/bar
Goodbye

# templates/qux
{% set wibble = "WIBBLE" %}
```

##### EXPECTED RESULTS

/tmp/foo to be created with:

~~~
hello world
WIBBLE
Goodbye
~~~

##### ACTUAL RESULTS

```
TASK [template] ****************************************************************
task path: /home/ubuntu/bug/test.yml:3
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "dest": "/tmp/foo",
            "src": "foo"
        },
        "module_name": "template"
    },
    "msg": "KeyError: 'undefined variable: 0'"
}
```

##### ADDITIONAL INFO

If you change `templates/foo` to this, it works fine:

~~~
hello world
{% include 'bar' %}
~~~

And so does this:

~~~
{% import 'qux' as qux with context %}
hello world
{{ qux.wibble }}
~~~

So it appears to be something to do with the *combination* of import and include which is causing it to barf.

However if you remove the "with context", like this:

~~~
{% import 'qux' as qux  %}
hello world
{{ qux.wibble }}
~~~

then it barfs in a different way:

~~~
TASK [template] ****************************************************************
task path: /home/ubuntu/bug/test.yml:3
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "dest": "/tmp/foo",
            "src": "foo"
        },
        "module_name": "template"
    },
    "msg": "AttributeError: 'NoneType' object has no attribute 'add_locals'"
}
~~~

So there is a potentially separate issue, that 'import ... with context' works, but 'import' by itself does not, in Ansible.

The [difference](http://jinja.pocoo.org/docs/2.9/templates/#import-context-behavior) is that in the latter case, jinja2 will cache the import with the template (since it doesn't depend on any of the dynamic context in that particular expansion of the template)

Finally: this appears not to be a bug with jinja2 itself. Using jinja2 API directly runs the test case with no problem:

~~~
#!/usr/bin/python
from jinja2 import Environment, FileSystemLoader
env = Environment(
    loader=FileSystemLoader('templates'),
)
template = env.get_template('foo')
print template.render()
~~~

gives:

~~~
$ python test.py

hello world
WIBBLE
Goodbye
~~~

### PR DESCRIPTION
**Pull request by zmedico**
##### SUMMARY

For compatibility with the Context.get_all() implementation
in jinja 2.9, make AnsibleJ2Vars implement collections.Mapping.
Also, make AnsibleJ2Template.newcontext() handle dict type
for the 'vars' parameter.

See: https://github.com/pallets/jinja/commit/d67f0fd4cc2a4af08f51f4466150d49da7798729
Fixes: https://github.com/ansible/ansible/issues/20494

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

template

##### ANSIBLE VERSION

devel

##### ADDITIONAL INFORMATION

@abadger @alikins @bcoca @jimi-c

### CODE REVIEW

**Comment by abadger** [comment]
I understand the  changes to lib/ansible/template/vars.py and those look good to me.  What are the changes to lib/ansible/template/template.py for?  (Trying to understand this while @jimi-c is on PTO.  If worst comes to worst he can look at it when he gets back).

**Comment by bcoca** [comment]
AnsibleJ2Vars is the main object we use to handle variables passed in to templating and from the code discussed before, the main reason this started failing with the jinja2.9 changes

**Comment by zmedico** [comment]
> What are the changes to lib/ansible/template/template.py for? (Trying to understand this while @jimi-c is on PTO. If worst comes to worst he can look at it when he gets back).

Prior to https://github.com/pallets/jinja/commit/d67f0fd4cc2a4af08f51f4466150d49da7798729, the first argument to new_context was always an instance of AnsibleJ2Vars. Since https://github.com/pallets/jinja/commit/d67f0fd4cc2a4af08f51f4466150d49da7798729, the first argument can be a plain dict, due to these changes in compiler.py:
```diff
diff --git a/jinja2/compiler.py b/jinja2/compiler.py
index 6595d632..6b2212e6 100644
--- a/jinja2/compiler.py
+++ b/jinja2/compiler.py
@@ -866,7 +866,7 @@ def visit_Include(self, node, frame):
         if node.with_context:
             loop = self.environment.is_async and 'async for' or 'for'
             self.writeline('%s event in template.root_render_func('
-                           'template.new_context(context.parent, True, '
+                           'template.new_context(context.get_all(), True, '
                            '%s)):' % (loop, self.dump_local_context(frame)))
         elif self.environment.is_async:
             self.writeline('for event in (await '
@@ -900,7 +900,7 @@ def visit_Import(self, node, frame):
         self.visit(node.template, frame)
         self.write(', %r).' % self.name)
         if node.with_context:
-            self.write('make_module%s(context.parent, True, %s)'
+            self.write('make_module%s(context.get_all(), True, %s)'
                        % (self.environment.is_async and '_async' or '',
                           self.dump_local_context(frame)))
         elif self.environment.is_async:
@@ -918,7 +918,7 @@ def visit_FromImport(self, node, frame):
         self.visit(node.template, frame)
         self.write(', %r).' % self.name)
         if node.with_context:
-            self.write('make_module%s(context.parent, True, %s)'
+            self.write('make_module%s(context.get_all(), True, %s)'
                        % (self.environment.is_async and '_async' or '',
                           self.dump_local_context(frame)))
         elif self.environment.is_async:

```

**Comment by parasyte** [comment]
IMHO, this JS file should not have been included: https://github.com/ansible/ansible/pull/27972/files#diff-7fc0d06c94e3f4dfa10201c5e95acd36

**Comment by zmedico** [comment]
That's true, test/integration/targets/template/templates/import_as_with_context.js does look like an unused file. @alikins

**Comment by alikins** [comment]
@zmedico ah, yeah, test/integration/targets/template/templates/import_as_with_context.js isnt need. An overzealous 'git add' on my part no doubt. I'll update.

**Comment by alikins** [comment]
@zmedico @parasyte https://github.com/ansible/ansible/pull/28072 rm's the unused file

**Pull request merged**
