### PR TITLE
Supporting Authenticate FTP via get_url Module

### LINKED ISSUE #68956: get_url does not authenticate against ftp servers
##### SUMMARY
get_url does not authenticate against ftp servers

##### ISSUE TYPE
- ~Bug Report~
- Feature Idea

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Python 3.6.5
OpenSSL 1.1.0i-fips  14 Aug 2018

##### STEPS TO REPRODUCE

```yaml
---
- name: TEST
  connection: localhost
  gather_facts: false
  hosts: localhost
  tasks:
    - name: download ftp
      get_url:
        url: ftp://u205615.your-storagebox.de/mods/
        url_username: u205615-sub1
        url_password: y4N66hRjQwswrp0o
        force_basic_auth: yes
        validate_certs: no
        dest: /home/michael/test/
```

##### EXPECTED RESULTS

I expect get_url to use credentials to loginto the ftp url

##### ACTUAL RESULTS

image
Ansible ignores username and password and does an anonymous login

```paste below
PLAY [TEST] *****************************************************************************************************************************************************************************************************************************************************

TASK [download ftp] *********************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/home/michael/test/", "elapsed": 0, "gid": 100, "group": "users", "mode": "0777", "msg": "Request failed: <urlopen error ftp error: error_perm('530 Login incorrect.',)>", "owner": "michael", "size": 512, "state": "directory", "uid": 1000, "url": "ftp://u205615.your-storagebox.de/mods/"}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### PR DESCRIPTION
**Pull request by hamidyousefi**
##### SUMMARY
Supporting FTP Authentication when trying to download a file via `get_url` module.
Fixes #68956

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
get_url

##### ADDITIONAL INFORMATION
None.

### CODE REVIEW

**Review by sivel — CHANGES_REQUESTED** [review]
This method has 100% unit test coverage, and we'd like to maintain that. A such this will require unit tests.

This should also include an integration test to validate that it is _actually_ working, but this will require the need to set up an FTP server in integration tests that support auth.

Additionally this will need a changelog fragment in changelog/fragments.

**Comment by hamidyousefi** [comment]
Thanks for your comment. Let me fulfill the requirements you mentioned.

**Comment by Akasurde** [comment]
@hamidyousefi Are news?

**Comment by hamidyousefi** [comment]
I will do my best in the next few days to fulfill the necessary changes. Sorry for the delay.

**Comment by Akasurde** [comment]
@hamidyousefi no issues. I just want to make sure that you are not stuck somewhere. Thanks for the feedback.

**Comment by bcoca** [comment]
waiting_on_contributor

**Pull request closed without merging**
