### PR TITLE
Added allowerasing flag to dnf module

### PR DESCRIPTION
**Pull request by poettler-ric**
##### SUMMARY
I just added another flag to the dnf module to let the user set whether he wants to allow replacing packages in order to fulfill the requested package installation. The default is still ```False```.

The motivation was to enable me to install libvirt and zfs (zfs on linux) since Fedora made zfs-fuse (no commits since Nov 2015) a dependency for libvirt.
See:
- https://github.com/zfsonlinux/zfs/issues/6585
- https://src.fedoraproject.org/rpms/libvirt/c/e5075407b1a7bd43755dfd33b9528bab60d1123e?branch=f26

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
dnf module

##### ANSIBLE VERSION
```
ansible 2.5.0 (allowerasing 15de290d74) last updated 2017/12/20 21:56:02 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/richi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/richi/projects/ansible/lib/ansible
  executable location = /home/richi/projects/ansible/bin/ansible
  python version = 2.7.13 (default, Dec  1 2017, 09:21:53) [GCC 6.4.1 20170727 (Red Hat 6.4.1-1)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by maxamillion** [comment]
@poettler-ric I'm in the process of trying to clean up the backlog for the `yum` module PRs, is there still a desire to add this functionality?

**Comment by poettler-ric** [comment]
@maxamillion yes it is :) . I am using it every time i setup a new computer.

**Comment by maxamillion** [comment]
@poettler-ric do you mind rebasing to fix the merge conflicts?

**Comment by poettler-ric** [comment]
Will do. I am on holiday atm, so it might take a while.

**Comment by poettler-ric** [comment]
Is it true it only fails because it can't reach the IRC server?
```
Sending IRC notification
No connection returned for server: close
```

**Comment by maxamillion** [comment]
@poettler-ric I'm about to merge a major refactor of this code in (I would have on Monday but had a family emergency and ended up offline for a while), I'll patch off your original patch and port this once that is done. Also, I'm not sure what shippable was complaining about, I've re-kicked the tests.

**Comment by maxamillion** [comment]
closing in favor of https://github.com/ansible/ansible/pull/48319 which includes attribution to this being the originating patch that's been ported to the new refactor of the code.

**Pull request closed without merging**
