### PR TITLE
Adds inwx_dns module (Manage DNS records of domains at INWX)

### PR DESCRIPTION
**Pull request by NickUfer**
##### SUMMARY
This PR adds the inwx_dns module used to manage dns records of domains at INWX (german domain registrar and hosting provider).

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
inwx_dns

### CODE REVIEW

**Comment by jpmens** [comment]
Suited for a content collection?

**Comment by NickUfer** [comment]
> @jpmens Suited for a content collection?

what do you mean exactly?

**Comment by jpmens** [comment]
The new [ansible content collections](https://www.ansible.com/blog/getting-started-with-ansible-collections); avoids you having to wait for this to be accepted/merged here. :)

**Comment by NickUfer** [comment]
Thanks I will look into it :+1:

**Pull request closed without merging**
