### PR TITLE
Fix Author name according to new valid rule

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/azure/azure_rm_virtualnetworkpeering.py

### CODE REVIEW

**Comment by yungezz** [comment]
@Akasurde is this going to be a general rule across all ansible modules? and does this rule apply to existing modules  with author in email address?  we'd like to understand the process clearly, thanks.

**Comment by Akasurde** [comment]
@yungezz Based on this 75407d3e439653ef4b103c383d653df32b081821, the rule is applicable to all modules. The format for DOCUMENTATION.author should be matching 

```
author_line = re.compile(r'^\w.*(\(@([\w-]+)\)|!UNKNOWN)(?![\w.])|^Ansible Core Team$|^Michael DeHaan$')
```

That means you need to specify GitHub ID after your name, like I have mentioned in this PR. I hope this will help you. Let me know if you need additional information.

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible/ansible/pull/49229

**Comment by yungezz** [comment]
@Akasurde  thanks for sharing the info. We'd apply the rule to all new modules then. And is it necessary to update all our existing modules? @zikalino  @yuwzho  ping my colleagues for awareness.

**Pull request closed without merging**
