### PR TITLE
update cowsay to choose random cow each time

### PR DESCRIPTION
**Pull request by kvarga**
I was disappointed that the same cow was chosen each time. Random cows should give me random cows throughout the playbook. This does just that.

### CODE REVIEW

**Comment by kvarga** [comment]
@mpdehaan - What do you think?

**Comment by lwade** [comment]
This has been discussed before but it was decided it was undesirable since some of the "cows" are rather rude (thus unprofessional).  You can already override this with an env variable:  ANSIBLE_COW_SELECTION and set that to random.

**Comment by kvarga** [comment]
@lwade The ANSIBLE_COW_SELECTION is exactly what this is, except it is random each time a banner is printed.  If some of the cows are rather rude, we would want to disable them. I'm not changing the list of possible cows, but rather making it use a random cow more often.

**Comment by mpdehaan** [comment]
This makes a fair point as it does not pick 'random' unless it is set to random.

**Comment by mpdehaan** [comment]
However, I think wasting any development time testing random cows is ... not fair to my other patches in the queue.  Alas, this shall not pass and I may gut the random option in the future.

**Comment by kvarga** [comment]
Not sure how this adds anything to development time for testing? But, alas, I be at your mercy here. 
image

**Comment by mpdehaan** [comment]
our cow testing goes through a udderly rigorous usability testing process
that costs literally millions of dollars in order to ascertain the
enterprise cowsay seal of approval.

**Comment by bcoca** [comment]
how about a SFW option? that uses random while grepping out a nsfw list [
'sodomized', etc....

On Wed, Jul 31, 2013 at 4:56 PM, Michael DeHaan notifications@github.comwrote:

> our cow testing goes through a udderly rigorous usability testing process
> that costs literally millions of dollars in order to ascertain the
> enterprise cowsay seal of approval.
> 
> On Wed, Jul 31, 2013 at 4:34 PM, Kyle Varga notifications@github.comwrote:
> 
> > Not sure how this adds anything to development time for testing? But,
> > alas, I be at your mercy here.
> > [image: image]<
> > https://f.cloud.github.com/assets/505939/889534/a0e09cb0-fa20-11e2-817b-17a265f7aee9.png>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ansible/ansible/pull/3715#issuecomment-21893526>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3715#issuecomment-21895035
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Pull request closed without merging**
