### PR TITLE
Windows: Introduce Set-AnsibleFact and set reboot_pending

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This is the first implementation to allow modules to update generic system facts. We implement a new library function **Set-AnsibleFact** that can set/update system facts, regardless if other facts were already set or not.

This PR also includes all needed changes to update the **ansible_reboot_pending** system fact from all modules that return **reboot_required**.

After this, I would also like to update other Windows modules to update the system facts after making the change (at least if these changes don't need a reboot to be effective).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
powershell/

##### ANSIBLE VERSION
2.5

### CODE REVIEW

**Comment by jhawkesworth** [comment]
I like the idea of this.  Its 'magic' but its the sort of magic that generally should do what you would want (specifically keep facts up to date).  
I do wonder if win_reboot should / could perhaps (optionally?) also update facts.  If so should it do all of them (safest, most expected, but also slow.  If it is optional is there really any benefit over letting users explicitly run setup ( I suppose it would at least prompt thinking about whether it was needed).
Maybe only some facts would need updating.  Is it worth complexity of updating only facts which could change on a reboot (and potential for missing something)?  Lots to think about.

I guess it would be necessary to alias ansible_reboot_required for ansible_reboot_pending in order to keep facts from breaking (but eventually move to a consistent name).

I think if this were a general purpose thing in ansible (perhaps it already is in linux), I'd like to see some kind of documentation note that states that the module updates facts, just so it is documented that this is expected.

**Comment by trondhindenes** [comment]
Set-Fact is fairly generic. Set-AnsibleFact maybe? To lessen the chance of name collisions...

**Comment by dagwieers** [comment]
So this was discussed during the WWG meeting, and the consensus was that this belongs to a core facts redesign which would allow for updating specific facts. So that modules can reuse that infrastructure.

There is no point in creating something like this for Windows only.

**Comment by dagwieers** [comment]
I noticed that the Unix python modules do this all over the place. So I think we can go forward implementing this for Windows as well.

**Comment by mattclay** [comment]
@dagwieers  @nitzmahone @jborean93 I think the `PSUseShouldProcessForStateChangingFunctions` rule is one we're probably going to want to disable. Thoughts?

**Comment by dagwieers** [comment]
Yes, please :-) I couldn't figure out a way to disable it...

But it seems nonsense, and there's a lot of people that want to see it remove (or at least differently implemented, not just name-based).

**Comment by mattclay** [comment]
I've created a PR to add support for global ignores to pslint and ignored that rule: https://github.com/ansible/ansible/pull/35526

**Comment by jborean93** [comment]
Due to the age of the PR I am going to close this. I'm also not 100% set on the design here but I don't have any other alternatives to propose right now sorry. We can definitely revisit this in a newer PR though if you are still up to it.

**Pull request closed without merging**
