### PR TITLE
Allow empty string GCE parameters

### PR DESCRIPTION
**Pull request by ghost**
Empty strings are valid parameters when running on a GCE instance:
http://libcloud.readthedocs.org/en/latest/compute/drivers/gce.html#using-gce-internal-authorization

### CODE REVIEW

**Comment by bcoca** [comment]
cc @erjohnso

**Comment by ghost** [comment]
I rebased this off the latest devel.

**Comment by erjohnso** [comment]
LGTM

ship_it

**Comment by erjohnso** [comment]
Ooops, I meant,

shipit

**Comment by jctanner** [comment]
@jamarzka Thank you for contributing this PR. The code this was modifying has been refactored in recent times for libcloud and other GCP services per https://github.com/ansible/ansible/commit/409d95d67e5918c06417e36c59fdcbbdb39fd887#diff-b6bc17b51c779b2ac4eefcfc5504a83b

I'm going to close this since it is no longer related to the current code.

**Pull request closed without merging**
