### PR TITLE
ssha.py convert a term to a SSHA encoded password

### PR DESCRIPTION
**Pull request by prune998**
##### SUMMARY
Added a filter to encode a term into SSHA encrypted password, as required by LDAP servers

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`lib/ansible/plugins/filter/ssha.py`

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file = /Users/prune/Documents/dev/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### ADDITIONAL INFORMATION
This is used when you want to create a ldif file from a template. you can encode a string into a password by using a filter : 
```
...
ldap_password: {{ the_password|to_ssha }}
...
```

### CODE REVIEW

**Comment by onitake** [comment]
A SSHA filter seems very useful, as it will allow generating LDAP password hashes on the fly.

I think it could even be added to the `password_hash` filter, since that is meant for generating salted password hashes.
See the `get_encrypted_password` function for its implementation: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py#L269

**Comment by prune998** [comment]
we could keep talking for months, add this to another plugin, or add the plugin as is as it does seem to pass every check with success.
While the `get_encrypted_password` filter should support ssha, you sometimes want to convert something to ssha which is not a password. This is pure sementics. Maybe it was a mistake to label this filter with the `password` keyword.

I don't have time to convert a working filter to another. Feel free to add the code to the `get_encrypted_password` if you think it's best.

**Comment by onitake** [comment]
I am not an Ansible maintainer, I merely stumbled upon your PR while searching for a way to generate SSHA hashes on the fly using Ansible.

In my opinion, an `ssha` hash option in the `password_hash` filter would be a better fit than a standalone filter. It would also allow passing in a salt (for idempotency), which your filter does not support.

On the other hand, `password_hash` is usually used to generate shadow password entries, and SSHA is not compatible with that. But that's up to the Ansible developers to decide.

**Comment by JorisVanEijden** [comment]
New in version 2.7:
When`Passlib` is installed password_hash supports any crypt scheme and parameter supported by ‘Passlib’:
`{{ 'secretpassword' | password_hash('ldap_salted_sha1') }}`
`{{ 'secretpassword' | password_hash('ldap_salted_sha1', salt='somesalt', salt_size=8, relaxed=true) }}`

**Comment by prune998** [comment]
Whatever, it's been almost two year and it wasn't merged, so let it go

**Comment by onitake** [comment]
@JorisVanEijden That's great news! Thanks!

@prune998 No need to get hostile. Not getting your PR merged may be disappointing, but at least the requested functionality was added to Ansible. You (and anybody else) are free to keep using your own module if it fits better for your use case. But I think it's better to have SSHA support in `password_hash` so I'm happy with that.

**Comment by prune998** [comment]
Sorry, I'm not hostile, I'm frustrated. 
I just don't understand that it took a year and a half to get an official SSHA support while it was one click away the whole time. 
A lots of stuff change at every release and deprecating this module now that the functionality is integrated into `password_hash` does not sound a big issue to me.

Well, you can now close this PR. There's just 1700 others waiting for you :) (Isn't that a warning of the non-health of this project ? Is it related to RedHat acquisition ? Good luck guys ! )

**Comment by onitake** [comment]
Well, to be fair: You could have submitted a PR to integrate SSHA into `password_hash` yourself.
But I do agree that it can sometimes be a bit difficult to work with certain development communities, and that work on this issue has been way too slow.

On the bright side, Ansible is very easy to extend with local modules, so not having the module in the core isn't a showstopper for anyone who wants to use it.

**Comment by bcoca** [comment]
@prune998 sorry about this, the most likely case is that we didn't realize your PR already gave us this functionality and someone else had already added it to password_hash. 

As you know we have many PRs open and though we try to keep track of those offering needed functionality like this one, sometimes they fall through the cracks, which is why we hold 2 weekly public irc meetings so users/authors/maintainers can bring these things to our attention.  https://github.com/ansible/community/issues?q=is%3Aopen+is%3Aissue+label%3Ameeting_agenda
Also pinging in the #ansible-devel IRC channel and mailing lists help to get things moved along.

Again, I'm sorry this was ignored, but as stated above someone already added the functionality to the existing `password_hash` so I'm closing this PR as redundant. 

Thanks for your contribution, I'm sad we didn't get to it in a timely fashion, the filter itself seemed simple and useful.

**Comment by prune998** [comment]
tanks for the answer @bcoca

**Pull request closed without merging**
