### PR TITLE
Install example config file under /etc/ansible

### PR DESCRIPTION
**Pull request by inittab**
Just added the example config file to the package

### CODE REVIEW

**Comment by mpdehaan** [comment]
Does Debian have something like RPM's ConfigNoReplace so that if the user modifies this it will not get clobbered on upgrade?

**Comment by inittab** [comment]
Hi Michael,

Yes it does. It would even show the diff between the user modified
configuration file and the new file shipped with the package, and prompt
him/her wich one prefers.

On Tue, Mar 26, 2013 at 04:31:29PM -0700, Michael DeHaan wrote:

> Does Debian have something like RPM's ConfigNoReplace so that if the user modifies this it will not get clobbered on upgrade?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ansible/ansible/pull/2507#issuecomment-15495603

## 

Alberto Gonzalez Iniesta    | Formación, consultoría y soporte técnico
agi@(inittab.org|debian.org)| en GNU/Linux y software libre
Encrypted mail preferred    | http://inittab.com

Key fingerprint = 9782 04E7 2B75 405C F5E9  0C81 C514 AF8E 4BA4 01C3

**Comment by inittab** [comment]
Forgot to mention: No need for a configuration directive. It's the default behaviour in the package manager.

**Comment by mpdehaan** [comment]
merged then, thanks!

**Pull request merged**
