### PR TITLE
Check real user's known_hosts when sudo ansible...

### LINKED ISSUE #4834: not_in_host_file() checks wrong user's known_hosts file when ran with sudo
See https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/ssh.py#L119

When one runs ansible(-playbook) itself through sudo on the local machine, `host_file` resolves to the one in the $SUDO_USER's home folder (probably as $HOME still points to it) not the one from the user ansible is ran as.

This should reference `~$USER`?

### PR DESCRIPTION
**Pull request by srgvg**
closes #4834

### CODE REVIEW

**Comment by bcoca** [comment]
what are you trying to do?

```
    host_file = os.path.expanduser("~/.ssh/known_hosts")
    host_file =
```

os.path.expanduser(os.path.expandvars("~${USER}/.ssh/known_hosts"))

should both resolve to the same dir, unless you are forcibly persisting
USER in your systems, do you want?:
        host_file =
os.path.expanduser(os.path.expandvars("~${SUDO_USER}/.ssh/known_hosts"))

this is user invoking sudo in all cases.

**Comment by srgvg** [comment]
I am (developers are) running ansible through a wrapper script that is sudo-eable and that limits what can be run. 

Standard sudoers file (ubuntu), with just a line that adds this ability. I'm not aware I do anything to force the value of $USER. $USER resolved to the user that is sudo'ed to, while ~ keeps pointing to the home of $SUDO_USER.

If there's a better way to resolve this, I'm all open to it.

**Comment by srgvg** [comment]
For the record, I'm not sure this PR is the most elegant solution, which is why I first filed #4834.

**Comment by jctanner** [comment]
Verified with ....

```
#root user does not have known_hosts, will prompt for YES/NO
strace -fftv -e open sudo -u root  ANSIBLE_SSH_ARGS="" ansible-playbook -c ssh -i inventory site.yml  2>&1

# ansible user does have known_hosts, does not prompt for YES/NO
strace -fftv -e open sudo -u ansible  ANSIBLE_SSH_ARGS="" ansible-playbook -c ssh -i inventory site.yml  2>&1
```

**Comment by jctanner** [comment]
@sergevanginderachter thank you!

**Pull request merged**
