### PR TITLE
[stable-2.10] find - set proper default based on use_regex (#73961)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Backport of #73961 for Ansible 2.10.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/find.py`

### CODE REVIEW

**Comment by samdoran** [comment]
This depends on a backport of #70139.

**Comment by samdoran** [comment]
Depends on #73970. Might need a rebase after #73970 is merged.

**Comment by relrod** [comment]
> Might need a rebase after #73970 is merged.

How'd you know? :)

**Comment by relrod** [comment]
Actually this is a dupe of #73965, will fix conflict there.

**Pull request closed without merging**
