### PR TITLE
Allow role {tasks,handlers,vars} to use files with a .yaml extension

### PR DESCRIPTION
**Pull request by fabulops**
Let's try this again.

Roles will now import main.yaml files if main.yml files are not found first.

roles/<rolename>/tasks/main.yaml
roles/<rolename>/handlers/main.yaml
roles/<rolename/vars/main.yaml

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Adam,

This contains a bit too much code duplication for my taste (mostly worried about future maintaince) -- would it be possible to check for a list of filename extensions so the body of each is only there once?

**Comment by fabulops** [comment]
Hi Michael

I agree, the duplication smells really bad. I was trying to touch as little as possible to provide the functionality. I think the best way to go forward would be to add a utility def that provides that functionality.

Perhaps something that replaces this following construct:

```
task      = utils.path_dwim(self.basedir, os.path.join(path, 'tasks', 'main.yml'))
if os.path.isfile(task):
```

with

   task      = utils.yml_or_yaml(self.basedir, path, '<subdir>', '<filestem>'):
   if task:
        ...
        ...

where <subdir> is 'tasks', 'handlers', etc. and <filestem> is 'main' or whatever.

It would then return either the verified path to a .yml, .yaml, or None.

If this sounds reasonable, could you give me some direction on what you would like the utility def to be named and if it needs to go anywhere other than lib/ansible/utils/**init**.py. I expect it would go somewhere near path_dwim() but whatever you think is best.

Thanks,
Adam

**Comment by fabulops** [comment]
sorry, some markup got stripped there. The 3rd/4th args to yml_or_yaml should be 'subdir' and 'filestem' and the following line should read

where 'subdir' is 'tasks', 'handlers', etc. and 'filestem' is 'main' or whatever.

**Comment by mpdehaan** [comment]
This still duplicates code between the two loop bodies and is not acceptable.  Too much copy/paste between the two here.

This needs to construct a list of the two paths that might exist and load the first one.

**Pull request closed without merging**
