### PR TITLE
Added normpath filter

### LINKED ISSUE #78675: More os.path filters
### Summary

Please add more filters based on os.path, specifically: `os.path.commonpath`, `os.path.normpath`. It is cheap, but would be handy in such tasks as validation, archive management, programmatic path generation. Can replace a lot of loops and regex filters.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by shivamdurgbuns**
Signed-off-by: Shivam Durgbuns <sdurgbun@redhat.com>

##### SUMMARY
Adding new filters based on os.path: os.path.normpath
Fixes https://github.com/ansible/ansible/issues/78675

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
core

### CODE REVIEW

**Comment by bcoca** [comment]
@shivamdurgbuns sorry, messed up the pr using the github editor, can you rebase and remove my commit?

**Comment by shivamdurgbuns** [comment]
> @shivamdurgbuns sorry, messed up the pr using the github editor, can you rebase and remove my commit?

@bcoca I can see that @sivel has closed the PR, do I need to rebase it?

**Comment by sivel** [comment]
The github GUI did something amazing to resolve the merge conflict, and squashed and merged leaving only the merge commit with the change inside somehow.

You'll have to rebase and push, and create a new PR.

**Comment by shivamdurgbuns** [comment]
@sivel I have done it here https://github.com/ansible/ansible/pull/78894

**Pull request closed without merging**
