### PR TITLE
Grammatical and punctuation edits to merged pull request

### PR DESCRIPTION
**Pull request by dharmabumstead**
##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Docs Pull Request
##### ANSIBLE VERSION

```

```
##### SUMMARY

```

```

### CODE REVIEW

**Comment by bcoca** [comment]
you have a merge commit, please rebase

**Comment by docschick** [comment]
@bcoca I'm git challenged apparently, could you elaborate?  I understand from the docs for contributing that this is preferred, but it's kinda scary (at least it is to me). A little hand holding here would be awesome as we learn the right way to do it. (Please and many, many thanks.)

**Comment by bcoca** [comment]
@docschick the comment was for the author, in any case here is a short explanation:

There are 2 commits in this PR, one of them is a merge, this can cause issues when we merge again.

The easiest way to fix this is create a new branch and then cherry pick the desired commit to that, then force push that branch to github.

Another way is to use git's rebase and eliminate the offenders that way, but it can be more involved.

**Comment by bcoca** [comment]
merged

**Pull request closed without merging**
