### PR TITLE
Fix test docs filename ismount.yml -> is_mount.yml

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
While the Python function is called `ismount`, the filter has the names `mount` and `is_mount`.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
is_mount / mount test

### CODE REVIEW

**Comment by felixfontein** [comment]
The result of the wrong filename is https://docs.ansible.com/ansible/devel/collections/ansible/builtin/is_mount_test.html.

**Comment by felixfontein** [comment]
@bcoca thanks!

**Comment by samccann** [comment]
I'm not sure if this needs backporting but please open a separate PR if it does (for stable-2.14 or wherever it's needed).

**Pull request merged**
