### PR TITLE
Allow Ansible to return error with unicode within it.

### PR DESCRIPTION
**Pull request by Yannig**
Fix for https://github.com/ansible/ansible/issues/13899

### CODE REVIEW

**Comment by abadger** [comment]
@Yannig what happens if you instead wrap message with to_str()?  I think that sinve we're setting the message of an exception we're going to need the message to be "native string type" (bytes on python2 and text on python3, ie, type "str" for each one)

**Comment by Yannig** [comment]
@abadger with initial code, I get the following stacktrace:

```
Traceback (most recent call last):
  File "/home/drayan/dev/ansible/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/home/drayan/dev/ansible/lib/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/home/drayan/dev/ansible/lib/ansible/executor/playbook_executor.py", line 78, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/__init__.py", line 53, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/__init__.py", line 93, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/play.py", line 109, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/base.py", line 200, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/drayan/dev/ansible/lib/ansible/playbook/play.py", line 161, in _load_tasks
    return load_list_of_blocks(ds=ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/helpers.py", line 50, in load_list_of_blocks
    loader=loader
  File "/home/drayan/dev/ansible/lib/ansible/playbook/block.py", line 75, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/base.py", line 200, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/drayan/dev/ansible/lib/ansible/playbook/block.py", line 111, in _load_block
    use_handlers=self._use_handlers,
  File "/home/drayan/dev/ansible/lib/ansible/playbook/helpers.py", line 97, in load_list_of_tasks
    t = Task.load(task, block=block, role=role, task_include=task_include, variable_manager=variable_manager, loader=loader)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/task.py", line 132, in load
    return t.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/base.py", line 189, in load_data
    ds = self.preprocess_data(ds)
  File "/home/drayan/dev/ansible/lib/ansible/playbook/task.py", line 171, in preprocess_data
    (action, args, delegate_to) = args_parser.parse()
  File "/home/drayan/dev/ansible/lib/ansible/parsing/mod_args.py", line 308, in parse
    raise AnsibleParserError("this task '%s' has extra params, which is only allowed in the following modules: %s" % (action, ", ".join(RAW_PARAM_MODULES)), obj=self._task_ds)
  File "/home/drayan/dev/ansible/lib/ansible/errors/__init__.py", line 57, in __init__
    self.message = 'ERROR! %s\n\n%s' % (message, to_str(extended_error))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 248: ordinal not in range(128)
```

**Comment by Yannig** [comment]
@abadger you're right, using to_str(message) fix the issue :)

**Comment by abadger** [comment]
Thanks @Yannig !  Merged to devel and stable-2.0 for inclusion into 2.0.1.

**Comment by Yannig** [comment]
Nice !

**Pull request merged**
