### PR TITLE
Update outdated docs about action shorthand

### PR DESCRIPTION
**Pull request by dmedvinsky**

### CODE REVIEW

**Comment by mpdehaan** [comment]
This is welcome but incomplete and actually introduces an error, so I think the edit might need a little revision:

It says:

Rather than listing out the explicit word, "action:", like so::
-    template: src=templates/foo.j2 dest=/etc/foo.conf
-    action: template src=templates/foo.j2 dest=/etc/foo.conf

what it should do is present the one syntax and show the alternate.

The above tends to imply the alternate is the alternate.

Can you please update the pull request?  Thanks!

**Comment by dmedvinsky** [comment]
Uhm… does it?

I'm not native speaker, but I reckoned in my edition it says “Instead of explicitly specifying the `action:` keyword, you may use a shortcut in the form of putting a module name followed by a colon followed by arguments”.

I mean, I don't think it introduces an error, but it might be sort of weird to read this section after seeing a new syntax throughout the docs. Maybe a complete rewrite like

> ### Old action syntax
> 
> Prior to version 0.8 the only possible way to specify actions was:
> 
> ```
> action: template src=templates/foo.j2 dest=/etc/foo.conf
> ```
> 
> In 0.8 we introduced the shortcut of the form:
> 
> ```
> template: src=templates/foo.j2 dest=/etc/foo.conf
> ```
> 
> Here the `action` keyword is omitted, and the name of the module is simply followed by a colon and the arguments to that module. We think this is a lot more intuitive. Most of our documentation has converted over to this new format. You'll be able to use both formats forever, though.

will do? I will update the pull request when you approve.

**Comment by mpdehaan** [comment]
Yeah the old syntax about showing the alternate needed to go, I think.

Rewrite is basically what we want, though I may tweak the docs section on
this some because I have some preferences.

If you want to just leave it open I'll get to it if that works.

**Comment by dmedvinsky** [comment]
All right, thanks! You may close it or leave it, whatever works for you best. My only concern is the greatness of ansible. :smirk:

**Comment by mpdehaan** [comment]
Hey thanks, I've fixed this up and it will be rebuilt next time I push docs.

**Comment by dmedvinsky** [comment]
Thanks.

**Pull request closed without merging**
