### PR TITLE
Adding support for AWS security token.

### PR DESCRIPTION
**Pull request by dorfsmay**

### CODE REVIEW

**Comment by willthames** [comment]
There is a PR for this along with adding profiles for 'common' ec2 modules (i.e. those that already use connect_to_ec2) in #5989. 

This one has the benefit of updating all the 'non-common' modules although doesn't update the documentation for those modules.

One benefit of #5989 is that it lays the groundwork for all future changes to connection parameters that are common for all aws modules (keys, security_token, validate_certs, profile_name) and allows such connections to make better use of the common code.

**Comment by dorfsmay** [comment]
On 2014-02-23 21:39, Will Thames wrote:

> There is a PR for this along with adding profiles for 'common' ec2 modules
> (i.e. those that already use connect_to_ec2) in #5989
> https://github.com/ansible/ansible/pull/5989.
> 
> This one has the benefit of updating all the 'non-common' modules although
> doesn't update the documentation for those modules.
> 
> One benefit of #5989 https://github.com/ansible/ansible/pull/5989 is that it
> lays the groundwork for all future changes to connection parameters that are
> common for all aws modules (keys, security_token, validate_certs,
> profile_name) and allows such connections to make better use of the common code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/pull/6106#issuecomment-35857360.

Sure. Do you want to delete my pull request then?

Do you know when #5989 will be merged to trunk?
And more importantly, do you have any idea when it will be incorporated into a 
tagged version?

Thanks.

## 

Yves.

**Comment by pas256** [comment]
Yeah, close this and use #5989 instead.

Tagged releases happen about once every 2 months (not counting minor bug fixes and point releases)

**Comment by mpdehaan** [comment]
Moving this discussion over to #5989, thanks guys, sorry for duplicate efforts!

**Pull request closed without merging**
