### PR TITLE
Added `-y` flag to `query_package`

### PR DESCRIPTION
**Pull request by giorgio-v**
- library/packaging/pkgin:

Signed-off-by: giorgio-v giorgio@refactor.it

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you please share the behavior before and after this patch?

It seems "-y" if meaning yes wouldn't be needed for a list command?

**Comment by giorgio-v** [comment]
oops, my commit message was clear at all. Yes, `-y` is usually not needed but if you run `pkgin` for the first time, e.g. without a package database, it asks confirmation to build one, causing Ansible to apparently hang.

**Comment by giorgio-v** [comment]
Hi Michael,
Do you need any other details about this? Let me know.

**Comment by jctanner** [comment]
@giorgio-v thank you! 

Tested with:

```
- hosts: smartzone.lab.net
  gather_facts: False
  tasks:
    - pkgin: name=nodejs state=present
```

**Pull request merged**
