### PR TITLE
Add support for changing MAC address

### PR DESCRIPTION
**Pull request by wolfie82**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

cloud/vmware/vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /etc/ansible/modules
```
##### SUMMARY

I had a use case where the MAC address needed to be set from an external inventory.  I'm currently using cobbler for guest provisioning.  The PXE boot process relies on the MAC address and therefore needed it to be set when the guest was created.  This code change also supports the state `reconfigured`.

I found a bunch of PR's that requested this feature, but none of them landed from what I can tell.  This is a PR off the most recent implementation of vsphere_guest.

References:
#3615
#3616 (referenced)
#358 (closed due to inactivity)
#1867 (was closed)
#1291 (was closed)
#2409

### CODE REVIEW

**Comment by wolfie82** [comment]
Migrated from https://github.com/ansible/ansible-modules-core/pull/3643

**Comment by mattclay** [comment]
@patbaker82 This PR needs to be rebased. Once you do that, Shippable will re-run the tests.

**Comment by enasisnetwork** [comment]
I have merged in @patbaker82's changes into my local copy and confirmed working. Should I put in a separate PR and reference this one?

**Comment by enasisnetwork** [comment]
https://github.com/ansible/ansible/pull/25636

**Comment by jctanner** [comment]
This has been needs_rebase for quite a while and I want to deprecate vsphere_guest in favor of vmware_guest for Ansible 2.5.

**Pull request closed without merging**
