### PR TITLE
[contrib] azure_rm.py add mechanism to force use of private ip

### PR DESCRIPTION
**Pull request by sylr**
as ansible_host

Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>

##### SUMMARY

If a VM has a public ip azure_rm.py currently force ansible_host to that public ip.

##### ISSUE TYPE
 - Feature Pull Request

### CODE REVIEW

**Comment by yuwzho** [comment]
shipit

**Comment by zikalino** [comment]
shipit

**Comment by yuwzho** [comment]
bot_status

**Comment by yuwzho** [comment]
bot_broken

**Comment by yuwzho** [comment]
@nitzmahone Could you please take a look, seems the bot doesn't work

**Comment by mattclay** [comment]
Sorry I missed this earlier, but @jctanner pointed out that this PR isn't for a module. Right now the bot only auto-merges modules.

**Comment by sylr** [comment]
Can we merge this ?

**Comment by kyliel** [comment]
@jborean93 , @nitzmahone , could you please review them and merge it if no issue? Thank you.

**Comment by savishy** [comment]
TL,DR: _The fix works, can we merge it please?_

I needed this fix for my organization work, and took the modified code for `azure_rm.py` from the pull request. I can verify that the PR works properly. i.e. with 3 Azure VMs created without a public IP, the script is able to assign private IP to `ansible_host`.

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
