### PR TITLE
win_disk_facts: Adds Win32_DiskDrive object to facts

### PR DESCRIPTION
**Pull request by wilmardo**
##### SUMMARY
Adds Win32_DiskDrive object to the windows_disk_facts module

For us this is needed to get the SCSI port and target_id to get a match between the vmware_guest_facts module and the win_disk_facts module (see example). 

Design choices:

* Added it as a separate dict, I could just add it to the physical disk section but this seems nicer to me since it is a separate Windows class.
* The matching between the Win32_DiskDrive class and the MSFT_Disk class returned by the Get-Disk cmdlet is done by UniqueId of the MSFT_Disk class. This UniqueId can be of different formats ([docs](https://msdn.microsoft.com/en-us/library/windows/desktop/hh830493(v=vs.85).aspx)) and two of them match a attribute of the Win32_DiskDrive class.
* I did map all properties and documented them with the descriptions from the [Microsoft docs](https://docs.microsoft.com/en-us/windows/desktop/CIMWin32Prov/win32-diskdrive)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
win_disk_facts

##### ADDITIONAL INFORMATION

Before:
```json
    "ansible_facts": {
        "ansible_disks": [
            {
                "bootable": true,
                "bus_type": "SAS",
                "clustered": false,
                "firmware_version": "1.0 ",
                "friendly_name": "VMware Virtual disk",
                "guid": "{eb87a94f-3d4a-403a-8713-f1c5f7a1fab2}",
                "location": "SCSI0",
                "manufacturer": "VMware  ",
                "model": "Virtual disk    ",
                "number": 0,
                "operational_status": "Online",
                "partition_count": 4,
                "partition_style": "GPT",
                "partitions": [
                    {
                        "access_paths": [
                            "\\\\?\\Volume{35e6308a-03f4-4f54-8e54-ba20b9521149}\\"
                        ],
                        "drive_letter": null,
                        "gpt_type": "{de94bba4-06d1-4d40-a16a-bfd50179d6ac}",
                        "guid": "{35e6308a-03f4-4f54-8e54-ba20b9521149}",
                        "hidden": false,
                        "no_default_driveletter": true,
                        "number": 1,
                        "offset": 1048576,
                        "shadow_copy": false,
                        "size": 471859200,
                        "transition_state": 1,
                        "type": "Recovery",
                        "volumes": [
                            {
                                "allocation_unit_size": 4096,
                                "drive_type": "Fixed",
                                "health_status": "Healthy",
                                "label": "Recovery",
                                "object_id": "{1}\\\\WILMAR-TEST-123\\root/Microsoft/Windows/Storage/Providers_v2\\WSP_Volume.ObjectId=\"{b4b6b4ec-2571-11e9-9101-806e6f6e6963}:VO:\\\\?\\Volume{35e6308a-03f4-4f54-8e54-ba20b9521149}\\\"",
                                "path": "\\\\?\\Volume{35e6308a-03f4-4f54-8e54-ba20b9521149}\\",
                                "size": 471855104,
                                "size_remaining": 137564160,
                                "type": "NTFS"
                            }
                        ]
                    },
                    {
                        "access_paths": null,
                        "drive_letter": null,
                        "gpt_type": "{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}",
                        "guid": "{49dc6a22-c71a-4f73-b005-9f7f6bec6f88}",
                        "hidden": true,
                        "no_default_driveletter": null,
                        "number": 2,
                        "offset": 472907776,
                        "shadow_copy": null,
                        "size": 103809024,
                        "transition_state": 1,
                        "type": "System"
                    },
                    {
                        "access_paths": null,
                        "drive_letter": null,
                        "gpt_type": "{e3c9e316-0b5c-4db8-817d-f92df00215ae}",
                        "guid": "{65614e0b-e5b9-4ac5-a420-caa7aa47aeb0}",
                        "hidden": true,
                        "no_default_driveletter": null,
                        "number": 3,
                        "offset": 576716800,
                        "shadow_copy": null,
                        "size": 16777216,
                        "transition_state": 1,
                        "type": "Reserved"
                    },
                    {
                        "access_paths": [
                            "C:\\",
                            "\\\\?\\Volume{f077199f-8456-4c76-84f1-5312134c46ab}\\"
                        ],
                        "drive_letter": "C",
                        "gpt_type": "{ebd0a0a2-b9e5-4433-87c0-68b6b72699c7}",
                        "guid": "{f077199f-8456-4c76-84f1-5312134c46ab}",
                        "hidden": false,
                        "no_default_driveletter": false,
                        "number": 4,
                        "offset": 593494016,
                        "shadow_copy": false,
                        "size": 53092548608,
                        "transition_state": 1,
                        "type": "Basic",
                        "volumes": [
                            {
                                "allocation_unit_size": 4096,
                                "drive_type": "Fixed",
                                "health_status": "Healthy",
                                "label": "",
                                "object_id": "{1}\\\\WILMAR-TEST-123\\root/Microsoft/Windows/Storage/Providers_v2\\WSP_Volume.ObjectId=\"{b4b6b4ec-2571-11e9-9101-806e6f6e6963}:VO:\\\\?\\Volume{f077199f-8456-4c76-84f1-5312134c46ab}\\\"",
                                "path": "\\\\?\\Volume{f077199f-8456-4c76-84f1-5312134c46ab}\\",
                                "size": 53092544512,
                                "size_remaining": 35261263872,
                                "type": "NTFS"
                            }
                        ]
                    }
                ],
                "path": "\\\\?\\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}",
                "physical_disk": {
                    "allocated_size": 53687091200,
                    "bus_type": "SAS",
                    "can_pool": false,
                    "cannot_pool_reason": "Insufficient Capacity",
                    "device_id": "0",
                    "firmware_version": "1.0",
                    "friendly_name": "VMware Virtual disk",
                    "health_status": "Healthy",
                    "indication_enabled": null,
                    "manufacturer": "VMware",
                    "media_type": "Unspecified",
                    "model": "Virtual disk",
                    "object_id": "{1}\\\\WILMAR-TEST-123\\root/Microsoft/Windows/Storage/Providers_v2\\SPACES_PhysicalDisk.ObjectId=\"{b4b6b4ec-2571-11e9-9101-806e6f6e6963}:PD:{6ad3f76e-fcb9-b79d-89a6-b34435001fa1}\"",
                    "operational_status": "OK",
                    "partial": true,
                    "physical_location": "SCSI0",
                    "serial_number": "6000c298f34101b38cb2b2508926b9de",
                    "size": 53687091200,
                    "spindle_speed": 0,
                    "supported_usages": {
                        "Count": 5,
                        "value": [
                            "Auto-Select",
                            "Manual-Select",
                            "Hot Spare",
                            "Retired",
                            "Journal"
                        ]
                    },
                    "unique_id": "6000C298F34101B38CB2B2508926B9DE",
                    "usage_type": "Auto-Select"
                },
                "read_only": false,
                "sector_size": 512,
                "serial_number": "6000c298f34101b38cb2b2508926b9de",
                "size": 53687091200,
                "system_disk": true,
                "unique_id": "6000C298F34101B38CB2B2508926B9DE"
            }
        ]
    },
    "changed": false
}
```

After
```json
    "ansible_facts": {
        "ansible_disks": [
            {
                "bootable": true,
                "bus_type": "SAS",
                "clustered": false,
                "firmware_version": "1.0 ",
                "friendly_name": "VMware Virtual disk",
                "guid": "{eb87a94f-3d4a-403a-8713-f1c5f7a1fab2}",
                "location": "SCSI0",
                "manufacturer": "VMware  ",
                "model": "Virtual disk    ",
                "number": 0,
                "operational_status": "Online",
                "partition_count": 4,
                "partition_style": "GPT",
                "partitions": [
                    {
                        "access_paths": [
                            "\\\\?\\Volume{35e6308a-03f4-4f54-8e54-ba20b9521149}\\"
                        ],
                        "drive_letter": null,
                        "gpt_type": "{de94bba4-06d1-4d40-a16a-bfd50179d6ac}",
                        "guid": "{35e6308a-03f4-4f54-8e54-ba20b9521149}",
                        "hidden": false,
                        "no_default_driveletter": true,
                        "number": 1,
                        "offset": 1048576,
                        "shadow_copy": false,
                        "size": 471859200,
                        "transition_state": 1,
                        "type": "Recovery",
                        "volumes": [
                            {
                                "allocation_unit_size": 4096,
                                "drive_type": "Fixed",
                                "health_status": "Healthy",
                                "label": "Recovery",
                                "object_id": "{1}\\\\WILMAR-TEST-123\\root/Microsoft/Windows/Storage/Providers_v2\\WSP_Volume.ObjectId=\"{b4b6b4ec-2571-11e9-9101-806e6f6e6963}:VO:\\\\?\\Volume{35e6308a-03f4-4f54-8e54-ba20b9521149}\\\"",
                                "path": "\\\\?\\Volume{35e6308a-03f4-4f54-8e54-ba20b9521149}\\",
                                "size": 471855104,
                                "size_remaining": 137564160,
                                "type": "NTFS"
                            }
                        ]
                    },
                    {
                        "access_paths": null,
                        "drive_letter": null,
                        "gpt_type": "{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}",
                        "guid": "{49dc6a22-c71a-4f73-b005-9f7f6bec6f88}",
                        "hidden": true,
                        "no_default_driveletter": null,
                        "number": 2,
                        "offset": 472907776,
                        "shadow_copy": null,
                        "size": 103809024,
                        "transition_state": 1,
                        "type": "System"
                    },
                    {
                        "access_paths": null,
                        "drive_letter": null,
                        "gpt_type": "{e3c9e316-0b5c-4db8-817d-f92df00215ae}",
                        "guid": "{65614e0b-e5b9-4ac5-a420-caa7aa47aeb0}",
                        "hidden": true,
                        "no_default_driveletter": null,
                        "number": 3,
                        "offset": 576716800,
                        "shadow_copy": null,
                        "size": 16777216,
                        "transition_state": 1,
                        "type": "Reserved"
                    },
                    {
                        "access_paths": [
                            "C:\\",
                            "\\\\?\\Volume{f077199f-8456-4c76-84f1-5312134c46ab}\\"
                        ],
                        "drive_letter": "C",
                        "gpt_type": "{ebd0a0a2-b9e5-4433-87c0-68b6b72699c7}",
                        "guid": "{f077199f-8456-4c76-84f1-5312134c46ab}",
                        "hidden": false,
                        "no_default_driveletter": false,
                        "number": 4,
                        "offset": 593494016,
                        "shadow_copy": false,
                        "size": 53092548608,
                        "transition_state": 1,
                        "type": "Basic",
                        "volumes": [
                            {
                                "allocation_unit_size": 4096,
                                "drive_type": "Fixed",
                                "health_status": "Healthy",
                                "label": "",
                                "object_id": "{1}\\\\WILMAR-TEST-123\\root/Microsoft/Windows/Storage/Providers_v2\\WSP_Volume.ObjectId=\"{b4b6b4ec-2571-11e9-9101-806e6f6e6963}:VO:\\\\?\\Volume{f077199f-8456-4c76-84f1-5312134c46ab}\\\"",
                                "path": "\\\\?\\Volume{f077199f-8456-4c76-84f1-5312134c46ab}\\",
                                "size": 53092544512,
                                "size_remaining": 34879393792,
                                "type": "NTFS"
                            }
                        ]
                    }
                ],
                "path": "\\\\?\\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}",
                "physical_disk": {
                    "allocated_size": 53687091200,
                    "bus_type": "SAS",
                    "can_pool": false,
                    "cannot_pool_reason": "Insufficient Capacity",
                    "device_id": "0",
                    "firmware_version": "1.0",
                    "friendly_name": "VMware Virtual disk",
                    "health_status": "Healthy",
                    "indication_enabled": null,
                    "manufacturer": "VMware",
                    "media_type": "Unspecified",
                    "model": "Virtual disk",
                    "object_id": "{1}\\\\WILMAR-TEST-123\\root/Microsoft/Windows/Storage/Providers_v2\\SPACES_PhysicalDisk.ObjectId=\"{b4b6b4ec-2571-11e9-9101-806e6f6e6963}:PD:{6ad3f76e-fcb9-b79d-89a6-b34435001fa1}\"",
                    "operational_status": "OK",
                    "partial": true,
                    "physical_location": "SCSI0",
                    "serial_number": "6000c298f34101b38cb2b2508926b9de",
                    "size": 53687091200,
                    "spindle_speed": 0,
                    "supported_usages": {
                        "Count": 5,
                        "value": [
                            "Auto-Select",
                            "Manual-Select",
                            "Hot Spare",
                            "Retired",
                            "Journal"
                        ]
                    },
                    "unique_id": "6000C298F34101B38CB2B2508926B9DE",
                    "usage_type": "Auto-Select"
                },
                "read_only": false,
                "sector_size": 512,
                "serial_number": "6000c298f34101b38cb2b2508926b9de",
                "size": 53687091200,
                "system_disk": true,
                "unique_id": "6000C298F34101B38CB2B2508926B9DE",
                "win32_disk_drive": {
                    "availability": null,
                    "bytes_per_sector": 512,
                    "capabilities": [
                        3,
                        4
                    ],
                    "capability_descriptions": [
                        "Random Access",
                        "Supports Writing"
                    ],
                    "caption": "VMware Virtual disk SCSI Disk Device",
                    "compression_method": null,
                    "config_manager_error_code": 0,
                    "config_manager_user_config": false,
                    "creation_class_name": "Win32_DiskDrive",
                    "default_block_size": null,
                    "description": "Disk drive",
                    "device_id": "\\\\.\\PHYSICALDRIVE0",
                    "error_cleared": null,
                    "error_description": null,
                    "error_methodology": null,
                    "firmware_revision": "1.0 ",
                    "index": 0,
                    "install_date": null,
                    "interface_type": "SCSI",
                    "last_error_code": null,
                    "manufacturer": "(Standard disk drives)",
                    "max_block_size": null,
                    "max_media_size": null,
                    "media_loaded": true,
                    "media_type": "Fixed hard disk media",
                    "min_block_size": null,
                    "model": "VMware Virtual disk SCSI Disk Device",
                    "name": "\\\\.\\PHYSICALDRIVE0",
                    "needs_cleaning": null,
                    "number_of_media_supported": null,
                    "partitions": 3,
                    "pnp_device_id": "SCSI\\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\\5&1982005&0&000000",
                    "power_management_capabilities": null,
                    "power_management_supported": null,
                    "scsi_bus": 0,
                    "scsi_logical_unit": 0,
                    "scsi_port": 0,
                    "scsi_target_id": 0,
                    "sectors_per_track": 63,
                    "serial_number": "6000c298f34101b38cb2b2508926b9de",
                    "signature": null,
                    "size": 53686402560,
                    "status": "OK",
                    "status_info": null,
                    "system_creation_class_name": "Win32_ComputerSystem",
                    "system_name": "WILMAR-TEST-123",
                    "total_cylinders": 6527,
                    "total_heads": 255,
                    "total_sectors": 104856255,
                    "total_tracks": 1664385,
                    "tracks_per_cylinder": 255
                }
            }
        ]
    },
    "changed": false
}
```

Example playbook for the usage:

```yaml
---
- name: Gather disk facts from VMWare guest
  vmware_guest_disk_facts:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    datacenter: "{{ vmware_vcenter_datacenter }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"
    name: "{{ vmware_guest.name }}"
  delegate_to: localhost
  register: vmware_disk_facts

- name: Gather Windows disk facts
  win_disk_facts:

- name: Set VMware disk size
  vmware_guest_disk:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    datacenter: "{{ vmware_vcenter_datacenter }}"
    validate_certs: "{{ vmware_vcenter_validate_certs }}"
    name: "{{ vmware_guest.name }}"
    disk:
      - size_kb: "{{ win_disk_size }}"
        state: present
        datastore: "{{ item.0.value.backing_datastore }}"
        scsi_controller: "{{ item.0.value.controller_key | string | regex_search('.{1}$') }}"
        unit_number: "{{ item.0.value.unit_number }}"
  loop: "{{ vmware_disk_facts.guest_disk_facts | dict2items | product(ansible_facts.disks) | list }}"
  when:
    - item.0.value.controller_key | string | regex_search('.{1}$') == item.1.win32_disk_drive.scsi_port | string
    - item.0.value.unit_number == item.1.win32_disk_drive.scsi_target_id
    - item.1.partitions | map(attribute='drive_letter') | join(' ') is search( win_drive_letter )
  delegate_to: localhost
```

### CODE REVIEW

**Comment by wilmardo** [comment]
Back to WIP, will map the whole class and add documentation on the return :)

**Comment by wilmardo** [comment]
Added docs and mapped whole class /ready_for_review 🎉

**Comment by wilmardo** [comment]
I observed that when the SerialNumber is empty it could still match the disks on the PNPDeviceID and UniqueId when the UniqueId is Vendor Specific.
This might be an edge case for our VMWare platform so it might be better to remove.
See the output below:

Get-Disk | Select *
```powershell
DiskNumber            : 0
PartitionStyle        : GPT
ProvisioningType      : Thin
OperationalStatus     : Online
HealthStatus          : Healthy
BusType               : SAS
UniqueIdFormat        : Vendor Specific
OfflineReason         :
ObjectId              : {1}\\AUTOTEST\root/Microsoft/Windows/Storage/Providers_v2\WSP_Disk.ObjectId="{fcd77b1a-2dd1-11e
                        9-9101-806e6f6e6963}:DI:\\?\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000000#{53f56307
                        -b6bf-11d0-94f2-00a0c91efb8b}"
PassThroughClass      :
PassThroughIds        :
PassThroughNamespace  :
PassThroughServer     :
UniqueId              : SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1982005&0&000000:autotest
AdapterSerialNumber   :
AllocatedSize         : 53687091200
BootFromDisk          : True
FirmwareVersion       : 1.0
FriendlyName          : VMware Virtual disk
Guid                  : {eb87a94f-3d4a-403a-8713-f1c5f7a1fab2}
IsBoot                : True
IsClustered           : False
IsHighlyAvailable     : False
IsOffline             : False
IsReadOnly            : False
IsScaleOut            : False
IsSystem              : True
LargestFreeExtent     : 0
Location              : SCSI0
LogicalSectorSize     : 512
Manufacturer          : VMware
Model                 : Virtual disk
Number                : 0
NumberOfPartitions    : 4
Path                  : \\?\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91e
                        fb8b}
PhysicalSectorSize    : 512
SerialNumber          :
Signature             :
Size                  : 53687091200
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/Storage:MSFT_Disk
CimInstanceProperties : {ObjectId, PassThroughClass, PassThroughIds, PassThroughNamespace...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

DiskNumber            : 2
PartitionStyle        : GPT
ProvisioningType      : Fixed
OperationalStatus     : Online
HealthStatus          : Healthy
BusType               : SAS
UniqueIdFormat        : Vendor Specific
OfflineReason         :
ObjectId              : {1}\\AUTOTEST\root/Microsoft/Windows/Storage/Providers_v2\WSP_Disk.ObjectId="{fcd77b1a-2dd1-11e
                        9-9101-806e6f6e6963}:DI:\\?\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000100#{53f56307
                        -b6bf-11d0-94f2-00a0c91efb8b}"
PassThroughClass      :
PassThroughIds        :
PassThroughNamespace  :
PassThroughServer     :
UniqueId              : SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1982005&0&000100:autotest
AdapterSerialNumber   :
AllocatedSize         : 10737418240
BootFromDisk          : False
FirmwareVersion       : 1.0
FriendlyName          : VMware Virtual disk
Guid                  : {e9e47169-eac8-4bed-a8e5-e1897760673e}
IsBoot                : False
IsClustered           : False
IsHighlyAvailable     : False
IsOffline             : False
IsReadOnly            : False
IsScaleOut            : False
IsSystem              : False
LargestFreeExtent     : 0
Location              : SCSI0
LogicalSectorSize     : 512
Manufacturer          : VMware
Model                 : Virtual disk
Number                : 2
NumberOfPartitions    : 2
Path                  : \\?\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000100#{53f56307-b6bf-11d0-94f2-00a0c91e
                        fb8b}
PhysicalSectorSize    : 512
SerialNumber          :
Signature             :
Size                  : 10737418240
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/Storage:MSFT_Disk
CimInstanceProperties : {ObjectId, PassThroughClass, PassThroughIds, PassThroughNamespace...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

DiskNumber            : 1
PartitionStyle        : RAW
ProvisioningType      : Fixed
OperationalStatus     : Offline
HealthStatus          : Healthy
BusType               : SAS
UniqueIdFormat        : Vendor Specific
OfflineReason         : Policy
ObjectId              : {1}\\AUTOTEST\root/Microsoft/Windows/Storage/Providers_v2\WSP_Disk.ObjectId="{fcd77b1a-2dd1-11e
                        9-9101-806e6f6e6963}:DI:\\?\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000200#{53f56307
                        -b6bf-11d0-94f2-00a0c91efb8b}"
PassThroughClass      :
PassThroughIds        :
PassThroughNamespace  :
PassThroughServer     :
UniqueId              : SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1982005&0&000200:autotest
AdapterSerialNumber   :
AllocatedSize         : 0
BootFromDisk          : False
FirmwareVersion       : 1.0
FriendlyName          : VMware Virtual disk
Guid                  :
IsBoot                : False
IsClustered           : False
IsHighlyAvailable     : False
IsOffline             : True
IsReadOnly            : True
IsScaleOut            : False
IsSystem              : False
LargestFreeExtent     : 0
Location              : SCSI0
LogicalSectorSize     : 512
Manufacturer          : VMware
Model                 : Virtual disk
Number                : 1
NumberOfPartitions    : 0
Path                  : \\?\scsi#disk&ven_vmware&prod_virtual_disk#5&1982005&0&000200#{53f56307-b6bf-11d0-94f2-00a0c91e
                        fb8b}
PhysicalSectorSize    : 512
SerialNumber          :
Signature             :
Size                  : 53687091200
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/Storage:MSFT_Disk
CimInstanceProperties : {ObjectId, PassThroughClass, PassThroughIds, PassThroughNamespace...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties
```

Get-CimInstance -ClassName Win32_DiskDrive | Select *
```powershell
ConfigManagerErrorCode      : 0
LastErrorCode               :
NeedsCleaning               :
Status                      : OK
DeviceID                    : \\.\PHYSICALDRIVE0
StatusInfo                  :
Partitions                  : 3
BytesPerSector              : 512
ConfigManagerUserConfig     : False
DefaultBlockSize            :
Index                       : 0
InstallDate                 :
InterfaceType               : SCSI
MaxBlockSize                :
MaxMediaSize                :
MinBlockSize                :
NumberOfMediaSupported      :
SectorsPerTrack             : 63
Size                        : 53686402560
TotalCylinders              : 6527
TotalHeads                  : 255
TotalSectors                : 104856255
TotalTracks                 : 1664385
TracksPerCylinder           : 255
Caption                     : VMware Virtual disk SCSI Disk Device
Description                 : Disk drive
Name                        : \\.\PHYSICALDRIVE0
Availability                :
CreationClassName           : Win32_DiskDrive
ErrorCleared                :
ErrorDescription            :
PNPDeviceID                 : SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1982005&0&000000
PowerManagementCapabilities :
PowerManagementSupported    :
SystemCreationClassName     : Win32_ComputerSystem
SystemName                  : AUTOTEST
Capabilities                : {3, 4}
CapabilityDescriptions      : {Random Access, Supports Writing}
CompressionMethod           :
ErrorMethodology            :
FirmwareRevision            : 1.0
Manufacturer                : (Standard disk drives)
MediaLoaded                 : True
MediaType                   : Fixed hard disk media
Model                       : VMware Virtual disk SCSI Disk Device
SCSIBus                     : 0
SCSILogicalUnit             : 0
SCSIPort                    : 0
SCSITargetId                : 0
SerialNumber                :
Signature                   :
PSComputerName              :
CimClass                    : root/cimv2:Win32_DiskDrive
CimInstanceProperties       : {Caption, Description, InstallDate, Name...}
CimSystemProperties         : Microsoft.Management.Infrastructure.CimSystemProperties

ConfigManagerErrorCode      : 0
LastErrorCode               :
NeedsCleaning               :
Status                      : OK
DeviceID                    : \\.\PHYSICALDRIVE1
StatusInfo                  :
Partitions                  : 0
BytesPerSector              : 512
ConfigManagerUserConfig     : False
DefaultBlockSize            :
Index                       : 1
InstallDate                 :
InterfaceType               : SCSI
MaxBlockSize                :
MaxMediaSize                :
MinBlockSize                :
NumberOfMediaSupported      :
SectorsPerTrack             : 63
Size                        : 53686402560
TotalCylinders              : 6527
TotalHeads                  : 255
TotalSectors                : 104856255
TotalTracks                 : 1664385
TracksPerCylinder           : 255
Caption                     : VMware Virtual disk SCSI Disk Device
Description                 : Disk drive
Name                        : \\.\PHYSICALDRIVE1
Availability                :
CreationClassName           : Win32_DiskDrive
ErrorCleared                :
ErrorDescription            :
PNPDeviceID                 : SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1982005&0&000200
PowerManagementCapabilities :
PowerManagementSupported    :
SystemCreationClassName     : Win32_ComputerSystem
SystemName                  : AUTOTEST
Capabilities                : {3, 4}
CapabilityDescriptions      : {Random Access, Supports Writing}
CompressionMethod           :
ErrorMethodology            :
FirmwareRevision            : 1.0
Manufacturer                : (Standard disk drives)
MediaLoaded                 : True
MediaType                   : Fixed hard disk media
Model                       : VMware Virtual disk SCSI Disk Device
SCSIBus                     : 0
SCSILogicalUnit             : 0
SCSIPort                    : 0
SCSITargetId                : 2
SerialNumber                :
Signature                   : 0
PSComputerName              :
CimClass                    : root/cimv2:Win32_DiskDrive
CimInstanceProperties       : {Caption, Description, InstallDate, Name...}
CimSystemProperties         : Microsoft.Management.Infrastructure.CimSystemProperties

ConfigManagerErrorCode      : 0
LastErrorCode               :
NeedsCleaning               :
Status                      : OK
DeviceID                    : \\.\PHYSICALDRIVE2
StatusInfo                  :
Partitions                  : 1
BytesPerSector              : 512
ConfigManagerUserConfig     : False
DefaultBlockSize            :
Index                       : 2
InstallDate                 :
InterfaceType               : SCSI
MaxBlockSize                :
MaxMediaSize                :
MinBlockSize                :
NumberOfMediaSupported      :
SectorsPerTrack             : 63
Size                        : 10733990400
TotalCylinders              : 1305
TotalHeads                  : 255
TotalSectors                : 20964825
TotalTracks                 : 332775
TracksPerCylinder           : 255
Caption                     : VMware Virtual disk SCSI Disk Device
Description                 : Disk drive
Name                        : \\.\PHYSICALDRIVE2
Availability                :
CreationClassName           : Win32_DiskDrive
ErrorCleared                :
ErrorDescription            :
PNPDeviceID                 : SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\5&1982005&0&000100
PowerManagementCapabilities :
PowerManagementSupported    :
SystemCreationClassName     : Win32_ComputerSystem
SystemName                  : AUTOTEST
Capabilities                : {3, 4}
CapabilityDescriptions      : {Random Access, Supports Writing}
CompressionMethod           :
ErrorMethodology            :
FirmwareRevision            : 1.0
Manufacturer                : (Standard disk drives)
MediaLoaded                 : True
MediaType                   : Fixed hard disk media
Model                       : VMware Virtual disk SCSI Disk Device
SCSIBus                     : 0
SCSILogicalUnit             : 0
SCSIPort                    : 0
SCSITargetId                : 1
SerialNumber                :
Signature                   :
PSComputerName              :
CimClass                    : root/cimv2:Win32_DiskDrive
CimInstanceProperties       : {Caption, Description, InstallDate, Name...}
CimSystemProperties         : Microsoft.Management.Infrastructure.CimSystemProperties
```

**Comment by wilmardo** [comment]
Reopening to trigger ci and remove stale_ci label

**Comment by ShachafGoldstein** [comment]
Should add a changelog fragment and maybe add it to the weekly [agenda](https://github.com/ansible/community/issues/420) to a merge it

**Comment by wilmardo** [comment]
@ShachafGoldstein Thanks for the suggestions! Where is the changelog located?

**Comment by ShachafGoldstein** [comment]
https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html?highlight=changelog#creating-new-fragments

**Comment by jhawkesworth** [comment]
This looks like a nice feature to have.
Please could you fix up the test failure ( failure: The test `ansible-test sanity --test shebang` failed with 1 error:


changelogs/fragments/51595-adds-win32_diskdrive-object-to-win_disk_facts.yaml:0:0: file without shebang should not be executable).
So presumably thats a chmod ugo-x <filename> and push to fix that one.

Only other thing I can think of is that it would be nice if you could add something to the tests as well if possible
test/integration/targets/win_disk_facts/tasks/tests.yml

**Comment by wilmardo** [comment]
@jhawkesworth Thanks for the suggestions again! Fixed the test failure and added a key check in the integration test

**Comment by wilmardo** [comment]
Closing and reopening to trigger CI

**Comment by wilmardo** [comment]
Rebased against current devel :)

**Comment by wilmardo** [comment]
Rebased againt current devel again, is there anything I can do to move this forward?

**Comment by jborean93** [comment]
Sorry for the delay @wilmardo, I've rerun CI just to make sure things still pass but the changes here are ok with me.

**Pull request merged**
