### PR TITLE
Refactored implementation to make use of caching and to limit the number of connections to external cobbler server for performance.

### PR DESCRIPTION
**Pull request by pgehres**
limit the number of connections to external cobbler server for performance.
Added use of cobbler.ini file to configure settings.

Tested against Cobbler 2.4.0

### CODE REVIEW

**Comment by pgehres** [comment]
@tgerla and @mpdehaan - as promised last week. We have been using it for about a month now and about 3 weeks without any issues.  It should be completely backwards compatible.

**Comment by jimi-c** [comment]
I think you missed a file with `git add`, the above diff only contains the new INI file.

**Comment by pgehres** [comment]
Ugh, I totally missed the real file.

**Comment by pgehres** [comment]
Commit amended.  Look again :-)

**Comment by jimi-c** [comment]
Thanks, I'll review this as soon as possible.

**Comment by pgehres** [comment]
Appreciated. I "borrowed" a lot from ec2.py for the caching portions.

**Comment by mpdehaan** [comment]
Merging this on grounds that @pgehres and crew say they've been using this for months :)

If someone finds something lacking they can yell :)

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request closed without merging**
