### PR TITLE
Bugfix (#58113) and update (error verbosity) added to ssh.py 

### PR DESCRIPTION
**Pull request by galaxyus123**
##### SUMMARY
Bugfix pull request for #58133.
Also added verbosity and check for different errors that occur on sshpass.
All of these errors with error code: 1-4 and 6 are non-recoverable, this exemption raised will prevent retries that could lock accounts.

##### ISSUE TYPE
- Bugfix Pull Request
Issue #58133
https://github.com/ansible/ansible/issues/58133

##### COMPONENT NAME
_handle_error function within ssh.py
ansible/lib/ansible/plugins/connection/ssh.py

##### ADDITIONAL INFORMATION

```paste below
Before:
 # sshpass returns codes are 1-6. We handle 5 previously, so this catches other scenarios. 
 # No exception is raised, so the connection is retried. 
 elif return_tuple[0] in [1, 2, 3, 4, 6]: 
     msg = 'sshpass error:' 
     if no_log: 
         msg = '{0} <error censored due to no log>'.format(msg) 
     else: 
         msg = '{0} {1}'.format(msg, to_native(return_tuple[2]).rstrip()) 

After:

        # sshpass returns codes are 1-6. We handle 5 previously, so this catches other scenarios.
        # No exception is raised, so the connection is retried.
        elif return_tuple[0] in [1, 2, 3, 4, 6]:
            if return_tuple[0] == 1:
                msg = 'sshpass error: Invalid command line argument. Command given: {1}'
            if return_tuple[0] == 2:
                msg = 'sshpass error: Conflicting arguments given. Command given: {1}'
            if return_tuple[0] == 3:
                msg = 'sshpass error: General runtime error.'
            if return_tuple[0] == 4:
                msg = 'sshpass error: Unrecognized response from ssh (parse error).'
            if return_tuple[0] == 6:
                msg = 'sshpass error: Host public key is unknown.'
            if no_log:
                msg = '{0} <error censored due to no log>'.format(msg)
            else:
                msg = '{0} {1}'.format(msg, to_native(return_tuple[2]).rstrip())
            raise AnsibleConnectionFailure(msg)

```

### CODE REVIEW

**Comment by samdoran** [comment]
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example. Also, please add unit tests to `test/units/plugins/connection/test_ssh.py`.

**Comment by Akasurde** [comment]
@galaxyus123 Could you please rebase this branch using https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html#rebasing-a-pull-request?  Thanks.

needs_info

**Comment by Akasurde** [comment]
@galaxyus123 Are you working on this? Let us know. Thanks.

**Comment by Akasurde** [comment]
Hi @galaxyus123, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible/ansible/pull/70904/ 

@galaxyus123 Thanks for the contribution.

**Pull request closed without merging**
