### PR TITLE
added support for scheduling downtime for all services on host

### PR DESCRIPTION
**Pull request by bladypirat**
example usage: nagios: action=downtime minutes=45 service=all host=$inventory_hostname

complementary feature for scheduling downtime for host.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks @bladypirat

@tbielawa  mind helping review this one since it's nagios related?

Thanks!

--Michael

**Comment by timlnx** [comment]
I apologize for the delay in getting back to you on this

I've tested and verified the patch.

+1, ship it.

**Comment by mpdehaan** [comment]
No problem, thanks to you both.

Merged!

**Comment by bladypirat** [comment]
Thanks very much:)

On 7 December 2012 17:00, Michael DeHaan notifications@github.com wrote:

> No problem, thanks to you both.
> 
> Merged!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/1720#issuecomment-11135103.

## 

Piotr Kweclich

Możemy być tylko tym, czym jesteśmy,
niczym mniej, niczym więcej...

www.bladypirat.oz.pl

**Pull request merged**
