### PR TITLE
docker_container: don't die when kernel memory accounting is not supported by runc build

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes CI failures such as [this one](https://app.shippable.com/github/ansible/ansible/runs/111118/52/tests).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by mattclay** [comment]
@felixfontein Do you have any ideas about what might have changed to introduce this problem?

**Comment by felixfontein** [comment]
@mattclay Since the RHEL7 target is the only docker test target where the installed docker daemon is the one actually used, I guess it's caused by a new version of the docker daemon installed. I've traced the error message back to https://github.com/opencontainers/runc/pull/1939, it could be that kernel memory limit has never been possible (at least on this target), but so far runc simply ignored the parameter, and only since that PR starts erroring on it.

**Comment by felixfontein** [comment]
The test code in this PR seems to work fine; on RHEL7, the output is
```
05:51 TASK [docker_container : kernel_memory] ****************************************
05:52 fatal: [testhost]: FAILED! => {"changed": false, "msg": "Error starting container 0032b7b60836c74af5eb55b574c77dc212df881e653f7c8b899b04d975f92a80: 500 Server Error: Internal Server Error (\"OCI runtime create failed: container_linux.go:344: starting container process caused \"process_linux.go:424: container init caused \\\"process_linux.go:390: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown\")"}
05:52 ...ignoring
05:52 
05:52 TASK [docker_container : kernel_memory (idempotency)] **************************
05:52 fatal: [testhost]: FAILED! => {"changed": false, "msg": "Error starting container 0032b7b60836c74af5eb55b574c77dc212df881e653f7c8b899b04d975f92a80: 500 Server Error: Internal Server Error (\"OCI runtime create failed: container_linux.go:344: starting container process caused \"process_linux.go:424: container init caused \\\"process_linux.go:390: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown\")"}
05:52 ...ignoring
05:52 
05:52 TASK [docker_container : kernel_memory (change)] *******************************
05:53 fatal: [testhost]: FAILED! => {"changed": false, "msg": "Error starting container 0032b7b60836c74af5eb55b574c77dc212df881e653f7c8b899b04d975f92a80: 500 Server Error: Internal Server Error (\"OCI runtime create failed: container_linux.go:344: starting container process caused \"process_linux.go:424: container init caused \\\"process_linux.go:390: setting cgroup config for procHooks process caused \\\\\\\"kernel memory accounting disabled in this runc build\\\\\\\"\\\"\": unknown\")"}
05:53 ...ignoring
05:53 
05:53 TASK [docker_container : cleanup] **********************************************
05:53 changed: [testhost] => {"changed": true}
05:53 
05:53 TASK [docker_container : assert] ***********************************************
05:53 skipping: [testhost] => {"changed": false, "skip_reason": "Conditional result was False"}
```
While on CentOS7, it works as before:
```
03:54 TASK [docker_container : assert] ***********************************************
03:54 ok: [testhost] => {
03:54     "changed": false, 
03:54     "msg": "All assertions passed"
03:54 }
```

**Comment by felixfontein** [comment]
shipit

**Comment by felixfontein** [comment]
bot_status

**Pull request merged**
