### PR TITLE
New module [ufw]: this module handles Ubuntu UFW operations

### PR DESCRIPTION
**Pull request by ovcharenko**
This is an advanced version of https://github.com/ansible/ansible/pull/5048

### CODE REVIEW

**Comment by otnateos** [comment]
things need to be fixed are 
- the default_policy and state mutual exclusive status. currently i can't add default_policy because it is mutual exclusive with state, and state cannot be omitted because it is required
- adding firewall rule doesn't flag 'changed' if there is IPv4 and IPv6 involved. e.g. the result from ufw command is "Rules updated\nRules updated (v6)" which doesn't exist in the changed markers

**Comment by ovcharenko** [comment]
@otnateos thanks for testing! Although I'm not sure how did you manage to mix IPv6 and IPv4 addresses? Whenever I try this I get `ERROR: "Mixed IP versions for 'from' and 'to'"` from UFW

**Comment by otnateos** [comment]
​
@ovcharenko, sorry for not being clear, the command I used was something like
- Ufw: state=allow proto=tcp to_port=80

This was run on base ubuntu 12.04 servers installation run under VirtualBox. the following command on the guest machine returns

```
$ ufw allow 80/tcp
Rules updated
Rules updated (v6)
```

One way I use and hack your module is to do the opposite check of the 'changed_marker' to allow checking the marker against the result 'msg' like

``` python
if isinstance(changed_marker, basestring):
        result['changed'] = result['msg'] in changed_marker
    else:
        result['changed'] = any(item in result['msg'] for item in changed_marker)
```

**Comment by escaped** [comment]
some rules may have a whitespace in its name, eg. Nginx Full

Line 227 should be: cmd = cmd + ' "%s"' % (name)

**Comment by ovcharenko** [comment]
More advanced version exists at https://github.com/ansible/ansible/pull/5518

**Pull request closed without merging**
