### PR TITLE
[WIP] Move _text functions into module_utils.text.converters

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY
Move all functions in `lib/ansible/module_utils/_text.py` to `lib/ansible/module_utils/common/text/converters`.

Leave a backwards compatible import in `lib/ansible/module_utils/_text.py`.

This lays the groundwork for changing all references to `lib/ansible/module_utils/_text.py` in a future PR.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
`lib/ansible/module_utils/_text.py`
`lib/ansible/module_utils/common/text/converters.py`

##### ADDITIONAL INFORMATION
- [x] This will need to be rebased after #53687 is merged as it dovetails with that work.

### CODE REVIEW

**Comment by samdoran** [comment]
bot_skip

**Comment by mattclay** [comment]
@samdoran I recommend splitting this PR up into multiple parts to make it easier to review. Start with moving the functions and the backwards compatibility stub. Then follow up with separate PRs for migrations, keeping the migrations reasonably sized.

**Comment by samdoran** [comment]
@mattclay Sounds like a plan. Thank you for the feedback.

**Comment by Akasurde** [comment]
@samdoran Do you think we can close this in favor of https://github.com/ansible/ansible/pull/68965

**Comment by samdoran** [comment]
That's only part of the solution. #68965 changes the location. I want to change all the references as well. I will close this since modules have moved out and open a new PR when I get a chance to run `rope` again.

**Pull request closed without merging**
