### PR TITLE
Merge authentication options back into a single field to prevent losing options beyond the first

### LINKED ISSUE #57505: postgresql_pg_hba does not correctly handle multiple options
##### SUMMARY
When there are multiple authentication options and multiple hosts, only the first authentication option is retained for hosts prior to the last

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql-pg-hba-module

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /home/user/PROJECT/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/user/PROJECT/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/home/user/PROJECT/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
CACHE_PLUGIN(/home/user/PROJECT/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/PROJECT/ansible.cfg) = ./cachedir
CACHE_PLUGIN_TIMEOUT(/home/user/PROJECT/ansible.cfg) = 86400
DEFAULT_FORKS(/home/user/PROJECT/ansible.cfg) = 20
DEFAULT_GATHERING(/home/user/PROJECT/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/user/PROJECT/ansible.cfg) = [u'/home/user/PROJECT/enviroments/P1']
INVENTORY_CACHE_ENABLED(/home/user/PROJECT/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/home/user/PROJECT/ansible.cfg) = jsonfile
```

##### STEPS TO REPRODUCE

```yaml
- name: "Postgres pg_hba"
  postgresql_pg_hba:
    dest: "/var/opt/rh/rh-postgresql96/lib/pgsql/data/pg_hba.conf"
    create: "yes"
    contype: "hostssl"
    method: "cert"
    group: "postgres"
    owner: "postgres"
    options: "clientcert=1 map=mymap"
    address: "{{ item }}"
  loop: "{{ [ 'red', 'blue' ] }}"
```

##### EXPECTED RESULTS

pg_hba.conf should contain
```
hostssl	all	all	red	cert	clientcert=1 map=mymap
hostssl	all	all	blue	cert	clientcert=1 map=mymap
```

##### ACTUAL RESULTS
Only the final hostssl entry contains the map entry. Changing the order of the options consistently results in only the first option being preserved.

pg_hba.conf actually contains
```
hostssl	all	all	red	cert	clientcert=1
hostssl	all	all	blue	cert	clientcert=1 map=mymap
```

### PR DESCRIPTION
**Pull request by ECRR**
##### SUMMARY
Fixes #57505

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
postgresql_pg_hba_module

##### ADDITIONAL INFORMATION
The fields are split on whitespace, but the final options field should be able to contain spaces. This joins the options back together.

### CODE REVIEW

**Comment by Andersson007** [comment]
@ECRR thank you for the fix! We need that @sebasmannem looks at this.

2 small notes:
1. Add a changelog fragment, look at the [doc](https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy), how to implement this properly
2. Better also add integration tests for checking expected results, see test/integration/targets/postgresql/tasks/postgresql_pg_hba.yml

**Review by sebasmannem — CHANGES_REQUESTED** [review]
This is about extra auth options, like ldap auth options, and such.
Good call.
Two minor things:
1: this should also be a test case in test/integration/targets/postgresql/tasks/postgresql_pg_hba.yml
2: cols[7:] should be removed. Something like cols = cols[:7]

**Review by sebasmannem — COMMENTED** [review]
Great work @ECRR 
shipit

**Review by Andersson007 — APPROVED** [review]
shipit

**Comment by Andersson007** [comment]
!needs_revision

**Comment by Andersson007** [comment]
@ECRR thank you for the PR!
after it is merged, please, make a [backport](https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy) to 2.8

**Comment by Andersson007** [comment]
bot_status

**Pull request merged**
