### PR TITLE
hg module cleaned up

### PR DESCRIPTION
**Pull request by yeukhon**
There is no perfect code, but as far as I can tell, this revision is the cleanest at the moment.

It follows git module's implementation.
This one is newer than the preview two days ago on Google Group, by the way.

Now options are:

``` text
repo
dest
revision
purge - alias for hg clean / hg purge, defaults to no
force - alias for hg update -C, defaults to yes
```

Major changes:
1. error handling relies on hg's stderr and `module.fail_json`
2. no more health checking such as `hg verify`
3. omitted `state` option
4. changed is determined via `before != after`, or whether it's been cleaned or purged.

I created a test repo just for this: https://bitbucket.org/yeukhon/trash-hg
output: http://pastebin.com/cECqBPw4

ps: I hope the git fetch and merge didn't fail me. 

Thank you!

### CODE REVIEW

**Comment by roller** [comment]
Thanks!  This works great for me.  The change checking and force options are confirmed in good shape.

One minor loose end I currently see is that if you use the purge option, it will disable the purge extension; but only if it actually finds something to purge.  It'd be better to disable the purge option only if it was enabled by the module (and irrespective of whether it found anything to purge).

When switching from bradobro's module (which uses su for owner option), I did have to update sudoers config in order to retain my expected umask.  But I think that sort of thing is expected in the name of security and separation of concerns.

**Comment by yeukhon** [comment]
@roller

Thank you!
Let me confirm: you are saying purge extension is removed after the purge operation, even though the user already enabled it? If so, yes, I think that's a good catch. 

For what I do, I simply assume, well, no one should touch hgrc humanly. If it's done via ansible, either someone already edit the hgrc via `lineinfile` or `template`, or if they need purge via hg module, it's okay to remove that extension.

I can see the concern though: if the module advertise it will undo the change, it should be completely undo. 
I think at the moment we can ignore this and patch it later. :8ball:

**Comment by roller** [comment]
@yeukhon, yes, I think the purge thing is very minor.  My reservation is not with it undoing its own work, rather that the module is undoing something that it didn't necessarily do in the first place (but only in some circumstances -- if it found something to purge).

**Comment by yeukhon** [comment]
@roller 
Thanks! I am actually confused. Sorry.

Are you saying the undo only happens when rc == 0 even when it failed? That's the first minor bug I caught as I reread the code. Are you against me enabling purge even if there's nothing to purge?

https://github.com/yeukhon/ansible/blob/980ffde192dabe4db4779ab76f1ce61a31f731a1/library/hg#L166

**Comment by mpdehaan** [comment]
Note I have _failed_ to merge this for 1.0.   My fault.  That being said, I'm not against merging this at all.

My plan is to merge this and then let folks sort out remaining issues.

If need be we can cherry-pick for a point release.

**Comment by yeukhon** [comment]
Well, if possible, we should try to release it as soon as possible. I personally feel very bad to submit the early version :( and now people have to live with my horrible doc and implementation.

I see that you are planning to do a point release (1.1) in the future based on CHANGELOG. 
I think we can do it in a few days assuming there are bug fixes for the 1.0 release.

But thanks for considering this one.

**Comment by mpdehaan** [comment]
I would not consider 1.1 a point release, that would be like a 1.1.1

In any event, 80% of us consume the development branch directly from git, at all times.

That being said, point release is not off the table but want to wait and see if we need to slurp in any other bugfixes first

I'm merging this in now!  Thanks!

**Comment by yeukhon** [comment]
Oh. Hahaha. Thanks a lot Michael!

--edit--
Shall we update the doc at some point :p even though it's in development branch.

**Pull request merged**
