### PR TITLE
support more version for pip module

### LINKED ISSUE #9011: pip module to support version targeting, greater than, less than, etc: >=, >, <=, <
##### Issue Type:

Feature Idea / Limitation
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

pip itself supports something like this:
pip install ansible>=1.71

but the pip module in Ansible only support (http://docs.ansible.com/pip_module.html)
pip: name=ansible version=1.7.1
##### Steps To Reproduce:
- name: install Ansible
  action: pip name=ansible version>=1.7.1
##### Actual Results:

Error message:
msg: unsupported parameter for module: version>

### PR DESCRIPTION
**Pull request by kpx-dev**
Fix #9011 

@jimi-c can you help CR please.

Thanks,
Kien

### CODE REVIEW

**Comment by jimi-c** [comment]
Hi @kienpham2000, I'm not sure if putting the </> in the param name vs. the value is the correct way to go here, and I'm not clear that it would even work like this being set in the aliases for the `version` param? Right now, you can actually do something like `name="foo>=x.y.z"` without specifying the version directly and it works as expected, so I think this probably just needs an overhaul in the pip module.

**Comment by kpx-dev** [comment]
@jimi-c yea right now it only work with >=, <= but not >, < since it doesn't have equal sign. Do you know if any other modules in ansible have support for something that is not assignment? Ex: version>1.0

Right now it fails everytime here if we don't have =
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L967

Do you allow module writer to overwrite this file or modify it to support better assignment?

**Comment by jimi-c** [comment]
@kienpham2000 right, I would not expect that to work as you have it, since the parameters need the '=' to be properly parsed. Instead, if you do `name=foo>x.y.z` it should work as you expect.

My proposal to make this work with version would be to use this patch instead:

<pre>
diff --git a/library/packaging/pip b/library/packaging/pip
index 613717a..b49a797 100644
--- a/library/packaging/pip
+++ b/library/packaging/pip
@@ -150,7 +150,12 @@ def _get_full_name(name, version=None):
     if version is None:
         resp = name
     else:
-        resp = name + '==' + version
+        for op in ('>', '>=', '&lt;', '&lt;='):
+            if str(version).startswith(op):
+                resp = name + version
+                break
+        else:
+            resp = name + '==' + version
     return resp 
 </pre>

**Comment by kpx-dev** [comment]
@jimi-c I actually had similar implementation but it was failed by this:
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L967

Maybe I'll have to patch that base module to support = assignment for key

**Comment by jimi-c** [comment]
@kienpham2000 that line you highlighted is why `version<x.y.z` will not work. But with my patch above, you would instead do `version='>x.y.z'`, which would work.

**Comment by jimi-c** [comment]
To make it clearer, you could instead use the "complex arguments" syntax with my patch:

<pre>
- pip:
    name: foo
    version: ">x.y.z"
</pre>

or:

<pre>
- pip:
    name: foo
    version: ">=x.y.z"
</pre>

**Comment by kpx-dev** [comment]
@jimi-c I see now. Ok I'll patch it up with your suggestion.

**Comment by kpx-dev** [comment]
@jimi-c pushed new changes based on your feedback. I also have to create a new dummy_test package so that I can test multiple versions.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
