### PR TITLE
Adding image field to gcp_compute inventory script

### PR DESCRIPTION
**Pull request by rambleraptor**
##### SUMMARY
Adding an image field to gcp_compute inventory script.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
gcp_compute.py

##### ADDITIONAL INFORMATION
In reference to https://github.com/ansible/ansible/issues/51884

### CODE REVIEW

**Comment by AlanCoding** [comment]
I tried this, and it returned `"image": null` for all the hosts. But...

I dropped a pdb shell inside your method `_get_image`, and then tinkered...

```python
config_data = self._read_config_data('private/gce/gcp_compute.yml')  # my file
config_data['scopes'] = ['https://www.googleapis.com/auth/compute']
module = GcpMockModule(config_data)
auth = GcpSession(module, 'compute')
resp = auth.get(item['disks'][0]['source'])
print resp.json()['sourceImage']
```

This is a string like

> https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20171025

Where `centos-7-v20171025` here corresponds to `gce_image` from the old script.

You're welcome to work this into this code if you want.

A few more comments about getting this is:

 - a changelog fragment would be good to have, I definitely want to keep a backport on the table
 - since my method involves an additional request, it would slow down the plugin, so it might be something that needs explicit enablement by a new parameter in the inventory file, and this is fine with me

As an example of such a parameter, see expand_hostvars for openstack:

https://github.com/ansible/ansible/blob/af9ff07c74b53798edff132aa8f8099773e97a91/lib/ansible/plugins/inventory/openstack.py

**Comment by AlanCoding** [comment]
Here's some code for that

https://github.com/ansible/ansible/compare/devel...AlanCoding:gcp_image_request?expand=1

It takes a _really_ long time for it to run. For whatever reason, the API takes a very long time to do a request. We would probably need to change to that old approach where a request was done to list disks, instead of a separate request for each disk.

**Comment by rambleraptor** [comment]
Does the `contrib/gce.py` inventory script successfully get the image?

**Comment by AlanCoding** [comment]
Yes, I had some notes here: https://github.com/ansible/ansible/issues/51884#issuecomment-462794382

the script hits `/v1/projects/project-name/aggregated/disks?maxResults=500`, whereas the branch I linked hits the URL for the specific disk, which looks like `/v1/projects/project-name/zones/us-east1-d/disks/image-name`.

Sometimes the API is very very slow. Doing a request for each disk is almost certainly too slow. Instead, if we can use the list of disks, and then loop over and associate them to the hosts (like the script), that would be better. However, the plugin makes requests for instances in a zone-specific way, so that scoping should probably also be respected. Presumably, we would want to get the list endpoint for disks, specific to each zone (don't know what the URL for that would be). Or maybe not, I'm not sure.

**Comment by maxamillion** [comment]
@rambleraptor any update here? I'd be happy to take this over if you're no longer interested in the patch.

needs_info

**Comment by rambleraptor** [comment]
Hey @maxamillion and all. Sorry, I completely forgot about this PR. If you don't mind taking it over, that would be fantastic. Happy to provide whatever help I can!

**Comment by maxamillion** [comment]
Closing this in favor of https://github.com/ansible/ansible/pull/54468

**Comment by maxamillion** [comment]
@rambleraptor I pulled the patch to preserve credit to you for the commits made in this PR but am continuing the work in a different PR so I can work off my branch.

**Pull request closed without merging**
