### PR TITLE
temporarily disable strictmode

### PR DESCRIPTION
**Pull request by trondhindenes**
Strictmode introdoces a number of errors in various modules, for instance modules which are testing if an argument exists outside of get-attr. We need to (possibly temporarily) disable strictmode checking.

### CODE REVIEW

**Comment by jimi-c** [comment]
@trondhindenes if absolutely required, I would prefer this to be an option but really I would prefer to have the modules fixed.

**Comment by jimi-c** [comment]
cc @cchurch

**Comment by trondhindenes** [comment]
I honestly don't see the point in enabling strictmode. In my 8+ years of powershell I've never seen it used, so I wonder what the rationaly was for enabling it in the first place. If we are to enable it it will require a major refactoring of lots of modules, so just enabling it out of the blue seems a bit premature. I propose we disable it and discuss it in the groups. Until we do anything, the current devel head is very broken on Windows.

**Comment by jimi-c** [comment]
The problem was that errors were silently being ignored and it would move on rather than error out, leading to weird things happening. People wrote PERL scripts for years too without using strict mode there and it was always a crap shoot as to whether you'd run across some weird bug because of it. Reading this https://technet.microsoft.com/en-us/library/hh849692.aspx and what it allows when it's disabled leads me to believe that we should absolutely have this enabled.

**Comment by bcoca** [comment]
if a script really needs it, script mode can be turned off for that run in
the script itself, but we should really fix all current windows modules to
work under strict mode.

## 

Brian Coca

**Comment by trondhindenes** [comment]
I absolutely agree that we should discuss this. I'm just surprised that it got turned on just like that. My vote is still: We discuss it, come to a conclusion, make the necessary changes in modules, and then implement it (if that's what's decided on).

**Comment by trondhindenes** [comment]
Anyone else care to chime in on this? As far as Windows is concerned the devel branch has been broken for a week now.

**Comment by jimi-c** [comment]
@trondhindenes per our discussion, please submit PRs for any modules which have seriously broken implementations, so we can disable StrictMode on a per-module basis rather than globally. I'll go ahead and close this in the meantime, as I believe we're in agreement that StrictMode is something we should generally be using, and the core set of win_ modules for which we have integration tests are passing.

**Comment by trondhindenes** [comment]
Noted. For the record, I'm not in agreement.

**Comment by nitzmahone** [comment]
See discussion on #12497 - we'll compromise by temporarily disabling strict mode on an individual module basis (done in 2.0-stable only). Modules in devel still need real fixes- I'll try to get those in ASAP.

**Comment by dreamcat4** [comment]
Example how to temp. disable strictmode:

https://github.com/ansible/ansible-modules-extras/blob/40acb516fd5b344bb832758fc660a1d04a6b14d3/windows/win_iis_webbinding.ps1#L24-L25

**Pull request closed without merging**
