### PR TITLE
Alphabetic inventory hostname patterns.

### PR DESCRIPTION
**Pull request by njharman**
Code, docs, tests.
Also added test of large range 000-142 to verify alpha range did not break this.

per

> since this is now doing ascii enumeration, have you tested to make sure it can still do host[0:100] ?

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks...

I'm just skimming this, but which is the test that passes in the alphabetical range?

**Comment by njharman** [comment]
Alpha host ranges (Egyptian Gods) have been added to test/simple_hosts and the relevant asserts test_simple() and test_simple_all() updated.

Since the range logic is in one place, seemed best to test in one place.

**Comment by mpdehaan** [comment]
Thanks

large_range is about hosts, so I would think it should be named at least something like "large_range_hosts" so we can keep things organized.   We can worry about moving things into subdirs later.

**Comment by mpdehaan** [comment]
merged in!

**Pull request merged**
