### PR TITLE
uri module is here!

### PR DESCRIPTION
**Pull request by rrtj3**
URI module to interact with webservices. Let me know if there's anything that needs to be changed in it. I've done quite a bit of testing/work with it myself and works nicely for me.

@jpmens, I used a bit of your code from your get_url module for writing out the dest file. Hope that's ok with you :) Thanks!

### CODE REVIEW

**Comment by jpmens** [comment]
Testing.

```
$ ansible-doc -M library/ uri
ERROR: module uri missing documentation
```

Hmm. Something wrong in the DOCUMENTATION string. (As usual :-)

```
hacking/module_formatter.py -M library/ -m uri -t rst -T ~/Auto/pubgit/ansible/ansible/hacking/templates/ -v

ParserError: while parsing a block mapping
  in "<string>", line 101, column 6:
       - code: "uri: url=https://your.jir ... 
         ^
expected <block end>, but found '<scalar>'
  in "<string>", line 101, column 202:
     ... s_code=201 HEADER_Content-Type="application/json"  
                                         ^
unable to parse library/uri
*** ERROR: CORE MODULE MISSING DOCUMENTATION: uri ***
```

### Here's a diff you can apply; hope I didn't break your doc

```

--- library/uri.orig    2013-02-15 23:59:01.000000000 +0100
+++ library/uri 2013-02-16 00:02:06.000000000 +0100
@@ -105,8 +105,8 @@
     required: false
     default: 200
   HEADER_:
-    description:
-      - Any parameter starting with "HEADER_" is a sent with your request as a header. For example,
+    description: >
+        Any parameter starting with "HEADER_" is a sent with your request as a header. For example,
         HEADER_Content-Type="application/json" would send the header "Content-Type" along with your
         request with a value of "application/json".
     required: false
@@ -128,7 +128,8 @@

      description: Check that a page returns a status 200 and the word AWESOME is in the page contents.

-   - code: "uri: url=https://your.jira.server.com/rest/api/2/issue/ method=POST user=your_username password=your_pass body='$FILE(issue.json)' force_basic_auth=yes status_code=201 HEADER_Content-Type="application/json"  
+   - code: |
+           uri: url=https://your.jira.server.com/rest/api/2/issue/ method=POST user=your_username password=your_pass body='$FILE(issue.json)' force_basic_auth=yes status_code=201 HEADER_Content-Type="application/json"  
      description: "Create a JIRA issue." 

    - code: |
```

**Comment by jpmens** [comment]
```
python library/uri
Traceback (most recent call last):
  File "library/uri", line 371, in <module>
    main()
  File "library/uri", line 261, in main
    module.fail_json(msg="httplib2 is not installed")
UnboundLocalError: local variable 'module' referenced before assignment
```

Python 2.7.2

**Comment by jpmens** [comment]
Hmm. Sorry. Dead tired. Will continue early next week. (I thought httplib2 was part of core Python?) Probably not.

**Comment by rrtj3** [comment]
Thanks for the testing and diff @jpmens ! I'll apply doc fixes. Yes, httplib2 is not part of the core Python. If I can I'll move the check for it though, so it doesn't fail with the "referenced before assignment"

**Comment by rrtj3** [comment]
The two items mentioned above are now fixed.

**Comment by mpdehaan** [comment]
merged, thanks!    This is awesome!   Very cool.

(Note: I tweaked one of the examples to make it use the fail module versus uptime.)

**Pull request closed without merging**
