### PR TITLE
Fix advertise addr

### LINKED ISSUE #46326: Docker Swarm init requires advertise_addr
##### SUMMARY

The documentation indicates that the field is optional:
https://github.com/ansible/ansible/blob/83e584577a14939966bbb0e4e9d1f569a7bd90af/lib/ansible/modules/cloud/docker/docker_swarm.py#L30-L31

However the code makes it a required field:
https://github.com/ansible/ansible/blob/83e584577a14939966bbb0e4e9d1f569a7bd90af/lib/ansible/modules/cloud/docker/docker_swarm.py#L333-L334

##### ISSUE TYPE
- Documentation Report
- Bug Report

##### COMPONENT NAME
docker_swarm

##### ANSIBLE VERSION

```
❯ ansible --version
ansible 2.8.0.dev0
  config file = /Users/mike/Development/nas/ansible.cfg
  configured module search path = [u'/Users/mike/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 18 2018, 16:17:02) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```
❯ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/mike/Development/nas/ansible.cfg) = [u'/Users/mike/Development/nas/inventories/home.yml']
```

##### OS / ENVIRONMENT

Source OS: macOS Mojave 10.14
Target OS: Ubuntu 18.04

##### ADDITIONAL INFORMATION

The devel branch gave me this error message:
```
fatal: [192.168.1.38]: FAILED! => {"changed": false, "msg": "advertise_addr is required to initialize a swarm cluster."} 
```

But when I ran it manually on the server:
```
root@elbert:~# docker swarm init
Swarm initialized: current node (CENSORED) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token CENSORED 192.168.1.31:2377                                                                                                        

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
```

### PR DESCRIPTION
**Pull request by tbouvet**
##### SUMMARY
Fixes #46326

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_swarm

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/ansible/core/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
```

### CODE REVIEW

**Comment by danihodovic** [comment]
ship_it

**Comment by felixfontein** [comment]
@danihodovic you need to write shipit without _

**Comment by felixfontein** [comment]
shipit

**Comment by gundalow** [comment]
@tbouvet thank you for the fix
@danihodovic @felixfontein thank you for the reviews.

**Comment by felixfontein** [comment]
@tbouvet will you create backports?
@gundalow and thank you for merging!

**Comment by felixfontein** [comment]
Interestingly, I get the error this PR fixes in an integration test for a stable-2.7 backport: https://app.shippable.com/github/ansible/ansible/runs/91418/52/tests

**Comment by felixfontein** [comment]
I created a stable-2.7 backport in #48405. @tbouvet can you take a look if it is ok?

**Comment by tbouvet** [comment]
@felixfontein thanks.
it's ok for me.

**Pull request merged**
