### PR TITLE
Stable 2.5

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

Hit the bug sorted in the 52f79fa5a42ff97fd7b509a68dd83204149c5f14 commit and wondered if it would be back ported to the stable version 2.5. Thanks

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by gundalow** [comment]
Incorrect PR.
I've asked Akasurde if his PR should be backported.

**Comment by Akasurde** [comment]
@tiowillyto I have created a backport for Stable-2.5 - #36166

**Comment by gundalow** [comment]
@tiowillyto Fix has been cherry-picked into `stable-2.5`, thanks!

**Comment by ghost** [comment]
thanks!!

**Pull request closed without merging**
