### PR TITLE
EC2 Wait fix

### PR DESCRIPTION
**Pull request by dparalen**
Hi,

I'd like to introduce a wait timeout for instances. To make this work reliably, I had to deal with a race condition between creating and fetching instance object, too.

Thanks!

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi,can you please submit this without merge commits?

Basically use git topic branches and "git pull --rebase" versus "git merge"?

(also, @lwade, any thoughts?)

**Comment by dparalen** [comment]
> Basically use git topic branches and "git pull --rebase" versus "git merge"?
> done.

**Comment by lwade** [comment]
Hey,

I'm in favour of a more robust way of timing out and exiting upon expiry (i.e. fail : all of my instances didn't go to the running state), this looks good in this regard.  One exception however and that would be naming the parameter wait_running.  

The reason for this is that the problem we have with the reported states is that we get false-positives.  EC2 (and other cloud platforms) will report an instance as running but it may not have finished booting and be reachable via SSH.  Users familiar with the platforms will understand the differences but those new to the nitty-gritty will perhaps be perplexed by a related failure in their play since it would mean subsequent plays which target configuration of the instance would fail.  

I'll make some changes to the documentation for this bit, I don't really think we need to add _another_ wait parameter but we should encourage users to add an abitrary wait action following an instance launch.

**Comment by lwade** [comment]
#2342

**Comment by dparalen** [comment]
Maybe the ec2 action name is misleading in the first place---something like '''ec2_ami id='ami-12345678' status=running timeout=300''' could be more appropriate but that might be a matter of taste.

As far as the services not running/boot not finished I'm in favor of the '''wait_for host=... port=...''' action, too. This patch is rather about returning particular ec2 request status back to the user in a reasonable amount of time.

There's one thing, though; with cloud-init in action and/or sluggish t1.micro instances even paramiko_ssh could benefit of a retry and I'm planning to implement a patch for that. The reason is even though a service is up, the ultimate config might not yet be in place and a service restart is pending. But that's off-topic...

**Comment by lwade** [comment]
The EC2 module used to be called ec2_create, which was probably more accurate.  I'm kinda on the fence about renaming it but if we did I think ec2_run would be appropriate.

Completely agree re: wait_for, I'll add that to the doc section per #2342.

**Comment by dparalen** [comment]
lwade, should I rename the parameters wait and wait_timeout in my patch? 

Thanks!

**Comment by lwade** [comment]
Yes please, I think that's best.  That way we have wait=true wait_timeout=whateveriwant, which I think is very palatable :)

**Comment by dparalen** [comment]
> One exception however and that would be naming the parameter wait_running
> 
> > That way we have wait=true wait_timeout=whateveriwant, which I think is very palatable :)

I'm sorry, I'm kinda confused. The parameters in the patch have been named wait and wait_timeout from the beginning...

Cheers,
milan

**Comment by lwade** [comment]
Sorry, _I'm_ getting confused :P

Let's stick with your wait_timeout parameter name.  Considering it some
more and it makes just as much sense, of not more.

Thanks! Good to go!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
