### PR TITLE
Allow to specify ansible_ssh_private_key_file location related to user home directory

### PR DESCRIPTION
**Pull request by ovcharenko**
Make tests happy

### CODE REVIEW

**Comment by jctanner** [comment]
Related PR: https://github.com/ansible/ansible/pull/5001

**Comment by mpdehaan** [comment]
Hi @ovcharenko can you add your original commits to this one as well?  Then we can merge everything together.

Unfortunately the other one is closed, we can merge manually, but this would make it easier.

Thanks!

**Comment by mpdehaan** [comment]
wait, nm, I understand this replaces the other now, got it.

Can you please update your commits to change the two space indent to four though?  That's our standard.

Thanks!

**Comment by ovcharenko** [comment]
Changed 30678e0..9af44b1

**Comment by ovcharenko** [comment]
Michael,

I'm sorry, but how I can do that?

**Comment by mpdehaan** [comment]
I think I was confused because this commit solves the previous one differently, correct?

**Comment by jctanner** [comment]
@ovcharenko this new patch breaks a testcase that is not in the official unit tests yet, but is pretty critical:

```
jtanner@u1304:~/ansible-tests/remote_user$ cat inventory
localhost 
jtanner@u1304:~/ansible-tests/remote_user$ cat site-local-task.yml
# inventory > task > play > playbook

- hosts: localhost
  gather_facts: False
  remote_user: playuser
  tasks:

    - local_action: debug

    - debug: 
      remote_user: taskuser

    - debug:
```

The traceback:

```
TASK: [debug] ***************************************************************** 
fatal: [localhost] => Traceback (most recent call last):
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 629, in _executor_internal_inner
    actual_private_key_file = os.path.expanduser(delegate_info.get('ansible_ssh_private_key_file', self.private_key_file))
  File "/usr/lib/python2.7/posixpath.py", line 252, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'


FATAL: all hosts have already failed -- aborting
```

I should mention that this only passes with the ssh connection type.

**Comment by ovcharenko** [comment]
And how to reproduce this exception? That playbook worked fine for me:

$ cat inventory
localhost

 $ cat site-local-task.yml

# inventory > task > play > playbook
- hosts: localhost
  gather_facts: False
  remote_user: playuser
  tasks:
  - local_action: debug
  - debug:
    remote_user: taskuser
  - debug:

$ ansible-playbook -i inventory site-local-task.yml

PLAY [localhost] **************************************************************

TASK: [debug] *****************************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

TASK: [debug ] ****************************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

TASK: [debug ] ****************************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0

**Comment by jctanner** [comment]
@ovcharenko sorry, I believe I wasn't testing the correct patch. It was a long day yesterday =)

**Comment by jctanner** [comment]
@ovcharenko thanks for the patch and the revision!

**Comment by ovcharenko** [comment]
It really was :) In fact I found that line 629 in exception still present in my revision.
Fixed in c0ca198. New pull request?

**Comment by jctanner** [comment]
@ovcharenko yes, new PR please. I'm not seeing the exception though.

**Comment by ovcharenko** [comment]
NVM, I see that line is fine in ansible/ansible devel trunk. Something funky with my local copy.
As you said… it was long day.

**Pull request merged**
