### PR TITLE
Fix accelerated mode listen ipv6 always true

### PR DESCRIPTION
**Pull request by dramer-817**
Should be able to take value from accelerate_ipv6 option, default false

### CODE REVIEW

**Comment by mpdehaan** [comment]
We've got a boolean function we should use instead here, but noted.  We can tweak this.

**Comment by jimi-c** [comment]
@indwic Could you explain exactly what issue you were seeing with this code? The bool cast in the original code should work to convert the option to a boolean value (or the module parameter should be specified as a bool type) so the JSON loads should not be necessary.

**Comment by dramer-817** [comment]
Using bool() doesn't work for my setup, it always listen ipv6 :::5099 instead 0.0.0.0:5099, accelerate_ipv6: false doesn't affect.
It also mentioned here https://groups.google.com/forum/#!topic/Ansible-project/qlNlFQeCPaA
My ansible 1.4 installation host mac os x with python 2.7.2 and target remote centos 6.4 with python 2.6.6

**Comment by jimi-c** [comment]
Ok, could you try this patch and let me know if it fixes the issue?

<pre>
diff --git a/library/utilities/accelerate b/library/utilities/accelerate
index 4a71dd9..d5e496a 100644
--- a/library/utilities/accelerate
+++ b/library/utilities/accelerate
@@ -427,7 +427,7 @@ def main():
     module = AnsibleModule(
         argument_spec = dict(
             port=dict(required=False, default=5099),
-            ipv6=dict(required=False, default=False),
+            ipv6=dict(required=False, default=False, type='bool'),
             timeout=dict(required=False, default=300),
             password=dict(required=True),
             minutes=dict(required=False, default=30),
@@ -441,7 +441,7 @@ def main():
     timeout   = int(module.params['timeout'])
     minutes   = int(module.params['minutes'])
     debug     = int(module.params['debug'])
-    ipv6      = bool(module.params['ipv6'])
+    ipv6      = module.params['ipv6']
 
     if not HAS_KEYCZAR:
         module.fail_json(msg="keyczar is not installed (on the remote side)")
</pre>

**Comment by dramer-817** [comment]
Ok it seems work, I think I've tried that before but guess I miss that. 
It better that way, no need for my code. Thank you

**Comment by jimi-c** [comment]
Great, I'll close this and push up my changes. We will also include this in 1.4.1. Thanks!

**Pull request closed without merging**
