### PR TITLE
display, also proxy warnings and deprecations

### LINKED ISSUE #80992: Preserve context for display method called from forks
### Summary

 When we updated `Display` to proxy over the queue for dispatch by the main process in https://github.com/ansible/ansible/pull/77056, we ended up losing some context, since we only proxy the `Display.display` method, and not all methods individually.

We need to add some functionality to `Display` to preserve this context, whether that means shipping additional information across the queue, or proxying all methods instead of just `Display.display`.

This has impacts on ansible-runner, and input should be taken to evaluate the best option.

### Issue Type

Feature Idea

### Component Name

lib/ansible/utils/display.py

### Additional Information

TBD

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by bcoca**
fixes #80992

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

display

### CODE REVIEW

**Comment by briantist** [comment]
Does this also resolve https://github.com/ansible/ansible/issues/73051 ?

**Comment by bcoca** [comment]
@briantist  it does not solve it, but it removes the main blocker to solving it

**Review by s-hertel — APPROVED** [review]
Looks good to me. This will make it easy to proxy any additional methods for ansible-runner.

**Review by nitzmahone — APPROVED** [review]
In my review and testing, this makes *almost* everything "work" properly again with the current runner display callback and also (woot!) finally fixes warning de-dupe from workers...

The one thing that still doesn't preserve context properly is `debug`, so worker-initiated `debug` calls under runner still show up as `verbose` events (since `debug` eventually internally calls `display`), and the runner event PIDs are still often incorrect, but I can live with that for now, and ultimately it should probably be fixed in runner anyway.

Since runner monkeypatches `display` much later, the decorators it jams in still have some bad behavior that will break and/or do weird stuff once we kill off std handle inheritance in workers, but I think it probably makes more sense to try and fix that there.

**Pull request merged**
