### PR TITLE
add jail module, based on lxc and chroot connexion plugin

### PR DESCRIPTION
**Pull request by mscherer**
See https://github.com/ansible/ansible/pull/4064 , same idea, but for jails on freebsd 

However, it was lightly tested ( just using raw module ) as I am quite new to jails.

### CODE REVIEW

**Comment by mpdehaan** [comment]
So "lightly tested" is a bit of a concern.  

I'm generally inclined to say we can't take this one unless it manages _remote_ jails, which is the same thing we said for the LXC module.

The chroot module is of use for local image building, so it's something of a special case.

**Comment by mpdehaan** [comment]
I'm being unreasonable here I think, there's no reason we can't think about this.

**Comment by mscherer** [comment]
Well, i also pushed it as a PR to get code review and that people more interested than me in freebsd could take a look. I planned to test it a bit more, but for now, I could only test raw module for now, until i manage to setup network correctly in the jail to install python.

**Comment by mpdehaan** [comment]
Yeah we shouldn't merge this one until more than the raw module is
confirmed to work.

**Comment by mscherer** [comment]
So I tested with ping, now I got the network working and python installed in the jails, and it doesn't work because freebsd do not have python in /usr/bin/, but in /usr/local/bin ( at least on freebsd 8.4 that I installed ). 

I found https://github.com/ansible/ansible/issues/205 abut this, but this was closed without referencing to a commit. Did the change got released ?

If I fix manually the shebang of the ping module, it run fine. It copy the module, run ping, and it work fine. I am checking for fetch as well, to cover all operations.

**Comment by mpdehaan** [comment]
ansible_python_interpreter should exist for this purpose.

Also make sure you test with 'template' and 'copy' as those are also
important.

**Comment by mscherer** [comment]
Tested copy, ran fine.
Tested template, ran fine.
Tested fetch, ran fine.

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by keltia** [comment]
Not wanting to reopen this but where can I find documentation on how to use this connection plugin?  Ansibleworks site is pretty much silent (or difficult to find...), thanks.

**Comment by mscherer** [comment]
use : ansible -c jail instead of -c chroot, using this doc: https://coderwall.com/p/_lpf1g

**Pull request merged**
