### PR TITLE
azure_rm_networkinterface: fixed issue when public ip address should not be created

### LINKED ISSUE #36444: cloud:azure: error while using azure_rm_networkinterface for creating a vnic without public IP
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- azure_rm_networkinterface.py

##### ANSIBLE VERSION
```
ansible 2.5.0b1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paolomargara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/paolomargara/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/paolomargara/ansible/bin/ansible
  python version = 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
The output of "ansible-config dump --only-changed" is void.

##### OS / ENVIRONMENT
"N/A"

##### SUMMARY
- When I run a test playbook with the provided example for "Create a network interface with private IP address only (no Public IP)" I got the following error "argument ip_configurations is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"
- After changing the ip_configurations from a dict to a list to address the previous error I got the following one "Parameter 'public_ip_address_name' can not be None."

##### STEPS TO REPRODUCE
- execute the following command:
```
ansible-playbook azure-deploy-test-vnic.yml
```
With the following playbook:
```yaml
---
- hosts: localhost
  connection: local
  tasks:
  - name: Create a network interface with private IP address only (no Public IP)
    azure_rm_networkinterface:
      name: cloudnode01
      resource_group: test-resourcegroup
      virtual_network_name: test-vnet
      subnet_name: test-subnet
      ip_configurations:
          name: test-cloudnode01
          primary: True
```
Will trigger the first issue.
- Correct the playbook:
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Create a network interface with private IP address only (no Public IP)
    azure_rm_networkinterface:
      name: cloudnode01
      resource_group: test-resourcegroup
      virtual_network_name: test-vnet
      subnet_name: test-subnet
      ip_configurations:
        - name: test-cloudnode01
          primary: True
```
Will trigger the second one.
##### EXPECTED RESULTS
The provided example should work as expected.
Should be possible to add a network interface without a public IP address.

##### ACTUAL RESULTS
- In the first case:
```
...
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "append_tags": true, 
            "ip_configurations": {
                "name": "test-cloudnode01", 
                "primary": true
            }, 
            "name": "cloudnode01", 
            "os_type": "Linux", 
            "private_ip_allocation_method": "Dynamic", 
            "public_ip": true, 
            "public_ip_allocation_method": "Dynamic", 
            "resource_group": "test-resourcegroup", 
            "state": "present", 
            "subnet_name": "test-subnet", 
            "virtual_network_name": "test-vnet"
        }
    }, 
    "msg": "argument ip_configurations is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"
}
...
```
- In the second one:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py", line 595, in <module>
    main()
  File "/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py", line 591, in main
    AzureRMNetworkInterface()
  File "/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py", line 408, in __init__
    required_if=required_if)
  File "/tmp/ansible_TpE0Hc/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 332, in __init__
  File "/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py", line 516, in exec_module
    ) for ip_config in self.ip_configurations
  File "/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py", line 546, in get_or_create_public_ip_address
    poller = self.network_client.public_ip_addresses.create_or_update(self.resource_group, name, params)
  File "/home/paolomargara/ansible/local/lib/python2.7/site-packages/azure/mgmt/network/v2017_06_01/operations/public_ip_addresses_operations.py", line 212, in create_or_update
    'publicIpAddressName': self._serialize.url("public_ip_address_name", public_ip_address_name, 'str'),
  File "/home/paolomargara/ansible/local/lib/python2.7/site-packages/msrest/serialization.py", line 488, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/home/paolomargara/ansible/local/lib/python2.7/site-packages/msrest/serialization.py", line 558, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'public_ip_address_name' can not be None.

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py\", line 595, in <module>\n    main()\n  File \"/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py\", line 591, in main\n    AzureRMNetworkInterface()\n  File \"/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py\", line 408, in __init__\n    required_if=required_if)\n  File \"/tmp/ansible_TpE0Hc/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 332, in __init__\n  File \"/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py\", line 516, in exec_module\n    ) for ip_config in self.ip_configurations\n  File \"/tmp/ansible_TpE0Hc/ansible_module_azure_rm_networkinterface.py\", line 546, in get_or_create_public_ip_address\n    poller = self.network_client.public_ip_addresses.create_or_update(self.resource_group, name, params)\n  File \"/home/paolomargara/ansible/local/lib/python2.7/site-packages/azure/mgmt/network/v2017_06_01/operations/public_ip_addresses_operations.py\", line 212, in create_or_update\n    'publicIpAddressName': self._serialize.url(\"public_ip_address_name\", public_ip_address_name, 'str'),\n  File \"/home/paolomargara/ansible/local/lib/python2.7/site-packages/msrest/serialization.py\", line 488, in url\n    data = self.validate(data, name, required=True, **kwargs)\n  File \"/home/paolomargara/ansible/local/lib/python2.7/site-packages/msrest/serialization.py\", line 558, in validate\n    raise ValidationError(\"required\", name, True)\nmsrest.exceptions.ValidationError: Parameter 'public_ip_address_name' can not be None.\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Fixes #36444 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION
2.4

### CODE REVIEW

**Comment by zikalino** [comment]
ready_for_review

**Comment by yuwzho** [comment]
Fixes #36163

**Comment by jborean93** [comment]
@zikalino are you also able to update the examples for `ip_configuration` o that it shows a list of dicts and not a dict value.

Also creating a test case to cover this issue will help to make sure it doesn't regress in the future.

**Comment by zikalino** [comment]
@jborean93 i have now added tests and fixed all the samples as well

**Comment by pmargara** [comment]
There is any chance to see this fix applied prior the release of version 2.5.0?

**Comment by zikalino** [comment]
@jborean93 could you recheck this pr? updated test and actual fix

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
Backport PR to stable-2.5 is here https://github.com/ansible/ansible/pull/37762

**Pull request merged**
