### PR TITLE
Handle ec2_ami_find owner parameter using an API filter, for speed

### PR DESCRIPTION
**Pull request by bretmartin**
#### SUMMARY
This is a post-repository-merge PR for what I originally submitted in https://github.com/ansible/ansible-modules-core/pull/3938, which contains full details.

##### ISSUE TYPE
Feature Pull Request

### CODE REVIEW

**Comment by willthames** [comment]
Is there a reason you didn't use the PR mover tool linked on the repomerge details page? - it would have been good to have all the context in this PR.

This change looks reasonable enough, it would be good to run those playbooks through twice each (in case of any cache related benefits for second run) with full profiling switched on (`ANSIBLE_CALLBACK_WHITELIST=profile_tasks,timer ansible-playbook ...`) to demonstrate actual performance improvements.

**Comment by willthames** [comment]
Does this work with owner=self? It seems that filters don't handle that case, whereas the boto call does.

From http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html
> owner-alias - String value from an Amazon-maintained list (amazon | aws-marketplace | microsoft) of snapshot owners. Not to be confused with the user-configured AWS account alias, which is set from the IAM console.

From boto docs http://boto.cloudhackers.com/en/latest/ref/ec2.html#boto.ec2.connection.EC2Connection.get_all_images
> owners (list) – A list of owner IDs, the special strings ‘self’, ‘amazon’, and ‘aws-marketplace’, may be used to describe images owned by you, Amazon or AWS Marketplace respectively

**Comment by bretmartin** [comment]
Whoops, didn't mean to delete that branch and close this. I am going to try to address the issues above soon, as well.

**Comment by aioue** [comment]
Potentially improves/fixes #24886

**Comment by bretmartin** [comment]
I closed this since this module is now deprecated.

**Comment by aioue** [comment]
@bretmartin it's not marked as deprecated in the docs (http://docs.ansible.com/ansible/latest/ec2_ami_find_module.html). 

You're not thinking of `ec2_ami_search`, [which is deprecated](http://docs.ansible.com/ansible/latest/ec2_ami_search_module.html)?

**Comment by aioue** [comment]
@bretmartin tested. Takes 4 seconds instead of 47! for my task. That's a huge difference in our pipeline.

Please re-open!

**Comment by aioue** [comment]
My mistake, Docs not updated - it is going to be deprecated.

https://github.com/ansible/ansible/pull/32501

**Comment by aioue** [comment]
this fixes the self issue:
```
    if owner:
        if owner.isdigit():
            filter['owner-id'] = owner
        elif owner == 'self':
            # self not a valid owner-alias filter (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html)
            pass
        else:
            filter['owner-alias'] = owner
```

**Pull request closed without merging**
