### PR TITLE
archive: Fix check if archive is created in path to be removed (#29420)

### LINKED ISSUE #29420: Check that archives are not created within paths to be removed is unreliable
From @gonzolino on 2016-11-24T10:41:47Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

archive

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When creating an archive with remove=True the archive module checks that the archive is not created within the paths to be removed.

Since the check is done with a simple `dest.startswith(path)`, it can happen that the check reports that the archive destination is in path when `path` is a prefix of `dest`, but they are not on the same path. E.g. `path=/tmp/test` and `dest=/tmp/test.tar.gz`, here `dest` is outside of `path`, but the check would still report that the archive would be created in a path to be removed.

##### STEPS TO REPRODUCE

The following playbook contains two tasks. The first will work because `path` is not a prefix of `dest`, the second will fail because `path` is a prefix of `dest`.

```
---
- name: Test archive
  hosts: localhost
  tasks:
    - name: This will work
      archive:
        path: /tmp/test1/
        dest: /tmp/test1.tar.gz
        remove: True
    - name: This will fail
      archive:
        path: /tmp/test2
        dest: /tmp/test2.tar.gz
        remove: True
```

##### ACTUAL RESULTS

```
ansible-playbook test.yml -vvvv
No config file found; using defaults
 [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.2.0.0_1/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [Test archive] ************************************************************

TASK [setup] *******************************************************************
Using module file /usr/local/Cellar/ansible/2.2.0.0_1/libexec/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dgonzalez
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1479983438.63-62447650972295 `" && echo ansible-tmp-1479983438.63-62447650972295="` echo $HOME/.ansible/tmp/ansible-tmp-1479983438.63-62447650972295 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/_q/mrdgcdd124qf1ry_xbhzwt_x_yl1nx/T/tmp1g_Bzg TO /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983438.63-62447650972295/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983438.63-62447650972295/ /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983438.63-62447650972295/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/Cellar/ansible/2.2.0.0_1/libexec/bin/python2.7 /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983438.63-62447650972295/setup.py; rm -rf "/Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983438.63-62447650972295/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [This will work] **********************************************************
task path: /Users/dgonzalez/Documents/Thesis/repo/lab/ansible/playbooks/test.yml:5
Using module file /Users/dgonzalez/Documents/Thesis/repo/lab/ansible/playbooks/library/archive.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dgonzalez
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1479983439.38-146539138486929 `" && echo ansible-tmp-1479983439.38-146539138486929="` echo $HOME/.ansible/tmp/ansible-tmp-1479983439.38-146539138486929 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/_q/mrdgcdd124qf1ry_xbhzwt_x_yl1nx/T/tmpKGqjYA TO /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983439.38-146539138486929/archive.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983439.38-146539138486929/ /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983439.38-146539138486929/archive.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/Cellar/ansible/2.2.0.0_1/libexec/bin/python2.7 /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983439.38-146539138486929/archive.py; rm -rf "/Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983439.38-146539138486929/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "archived": [],
    "arcroot": "/tmp/test1/",
    "changed": true,
    "dest": "/tmp/test1.tar.gz",
    "expanded_paths": [
        "/tmp/test1/"
    ],
    "gid": 0,
    "group": "wheel",
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "dest": "/tmp/test1.tar.gz",
            "directory_mode": null,
            "follow": false,
            "force": null,
            "format": "gz",
            "group": null,
            "mode": null,
            "owner": null,
            "path": "/tmp/test1.tar.gz",
            "regexp": null,
            "remote_src": null,
            "remove": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "unsafe_writes": null
        },
        "module_name": "archive"
    },
    "missing": [],
    "mode": "0644",
    "owner": "dgonzalez",
    "size": 60,
    "state": "file",
    "uid": 1441367741
}

TASK [This will fail] **********************************************************
task path: /Users/dgonzalez/Documents/Thesis/repo/lab/ansible/playbooks/test.yml:10
Using module file /Users/dgonzalez/Documents/Thesis/repo/lab/ansible/playbooks/library/archive.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dgonzalez
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1479983440.0-114483211257278 `" && echo ansible-tmp-1479983440.0-114483211257278="` echo $HOME/.ansible/tmp/ansible-tmp-1479983440.0-114483211257278 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/_q/mrdgcdd124qf1ry_xbhzwt_x_yl1nx/T/tmpWLomP4 TO /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983440.0-114483211257278/archive.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983440.0-114483211257278/ /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983440.0-114483211257278/archive.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/Cellar/ansible/2.2.0.0_1/libexec/bin/python2.7 /Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983440.0-114483211257278/archive.py; rm -rf "/Users/dgonzalez/.ansible/tmp/ansible-tmp-1479983440.0-114483211257278/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "gid": 0,
    "group": "wheel",
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "dest": "/tmp/test2.tar.gz",
            "directory_mode": null,
            "follow": false,
            "force": null,
            "format": "gz",
            "group": null,
            "mode": null,
            "owner": null,
            "path": [
                "/tmp/test2"
            ],
            "regexp": null,
            "remote_src": null,
            "remove": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "unsafe_writes": null
        },
        "module_name": "archive"
    },
    "mode": "0755",
    "msg": "Error, created archive can not be contained in source paths when remove=True",
    "owner": "dgonzalez",
    "path": "/tmp/test2",
    "size": 68,
    "state": "directory",
    "uid": 1441367741
}
	to retry, use: --limit @/Users/dgonzalez/Documents/Thesis/repo/lab/ansible/playbooks/test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1
```

Copied from original issue: ansible/ansible-modules-extras#3537

### PR DESCRIPTION
**Pull request by feranwq**
##### SUMMARY

Fixes #29420
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
archive

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bendoh** [comment]
So if I'm reading this right, this addresses the situation where the archive path is missing a trailing '/' and the destination matches, like

`path=my/file/path`
`dest=my/file/path-archive`

So the current check considers `path` to be a parent `dest`, even though it isn't actually?

LGTM

shipit

**Comment by feranwq** [comment]
> So if I'm reading this right, this addresses the situation where the archive path is missing a trailing '/' and the destination matches, like
> 
> `path=my/file/path`
> `dest=my/file/path-archive`
> 
> So the current check considers `path` to be a parent `dest`, even though it isn't actually?
> 
> LGTM
> 
> shipit

right

**Comment by abadger** [comment]
rebuild_merge

**Comment by sivel** [comment]
bot_status

**Pull request merged**
