### PR TITLE
$LOOKUP(dnstxt): handle exceptions

### PR DESCRIPTION
**Pull request by jpmens**

### CODE REVIEW

**Comment by jpmens** [comment]
Replaces PR https://github.com/ansible/ansible/pull/1588 which I broke

**Comment by mpdehaan** [comment]
Thanks, much better!

The diff seems to imply there's something weird with spacing going on in the exceptions part.  Might be a tab?   Normally I don't notice 3s vs 4s vs 5s, but please fix and I'll merge this.

**Comment by jpmens** [comment]
A TAB? I wouldn't DARE!
4 beautiful spaces. Well 8, actually. Now totally de-spaced. :-)

**Comment by mpdehaan** [comment]
8 spaces is an under appreciated python artform

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
