### PR TITLE
ansible-test - disable `TCPKeepAlive` to prevent external connection failures

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY
We are seeing increasing but still intermittent failures between Azure and external instances in MacStadium and AWS.

Disable `TCPKeepAlive` in the `ssh` connection and rely completely on `ServerAlive` messages.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`test/lib/ansible_test/_internal/manage_ci.py`
`test/lib/ansible_test/_internal/util.py`
`test/lib/ansible_test/_internal/util_common.py`

##### ADDITIONAL INFORMATION
Related to #75374.

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]

**Comment by mattclay** [comment]
@samdoran Based on the test failures, it appears this does not resolve the issue.

**Comment by samdoran** [comment]
That's so odd. I wonder why it worked in my other branch? Just coincidence, I suppose.

**Comment by samdoran** [comment]
I could try the other thing we thought about doing which is increasing the `ServerAlive` frequency.

**Comment by samdoran** [comment]
I'm going to add some packet capture to the callback to see if we can get more info.

**Pull request closed without merging**
