### PR TITLE
Make private key customizable per host using ansible_ssh_private_key_file configurable as variable

### PR DESCRIPTION
**Pull request by dagwieers**
This fixes issue #1026 for @toshywoshy together with ansible_ssh_user and ansible_ssh_port.

### CODE REVIEW

**Comment by mpdehaan** [comment]
this looks like it breaks the other connection types because it adds an argument without making sure all accept _args, and *_kwargs

looking at the tree, **kwargs is accepted on local, but chroot also must be checked, and neither supports *args

**Comment by dagwieers** [comment]
AFAICT all connection types either accept **kwargs or private_key_file:

```
[dag@moria ansible]$ grep -r __init__ lib/ansible/runner/connection_plugins/*.py
lib/ansible/runner/connection_plugins/chroot.py:    def __init__(self, runner, host, port, **kwargs):
lib/ansible/runner/connection_plugins/fireball.py:    def __init__(self, runner, host, port, **kwargs):
lib/ansible/runner/connection_plugins/local.py:    def __init__(self, runner, host, port, **kwargs):
lib/ansible/runner/connection_plugins/paramiko_ssh.py:    def __init__(self, runner, host, port, user, password, private_key_file):
lib/ansible/runner/connection_plugins/ssh.py:    def __init__(self, runner, host, port, user, password, private_key_file):
```

What am I missing ?

**Comment by mpdehaan** [comment]
It seems to be missing *args in addition to kwargs:

https://github.com/dagwieers/ansible/blob/22fe6c93aefccef21615ff22df8626641139d061/lib/ansible/runner/connection_plugins/local.py

Since in one place it is called like so:
-            conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)

Now python might be cool about that and just pass it as kwargs, but I wasn't aware that it did and it seems best to be explicit.

**Comment by dagwieers** [comment]
Michael, I don't understand what you are trying to say when you mention _args and *_kwargs. I know what they are, but I don't know what exactly you would like to see.

What I mostly see is that you are bothered by the difference in the existing implementation. I just implemented it the way it already was for user/password so you are confusing me if you tell me I am doing something incorrectly.

Yes, it makes no sense that one connection type uses positional arguments and the other simply adds *_kwargs. I do have an opinion why it was done this way though (the other connection types simply don't care about user/password so *_kwargs simply makes those additional positional arguments moot).

But again, tell me what you would like to see. I have no need on a lecture that should be directed/blamed on someone before me.

**Comment by toshywoshy** [comment]
I can confirm that it works for my use case
It would allow me to drop my patch which I currently use to have paramiko read my ssh config file

**Comment by mpdehaan** [comment]
@dag, there is no lecture here other than a mutual discussion of whether the code is safe or not, which is irrespective of who submitted the PR.  Please do not take things personally as they were not intended as such.  It may very well be that it was, though if we are making constructors safe for any sort of parameterization, _args, *_kwargs, is how it should be.

I am fine with assuming the burden of testing the various options.

**Comment by mpdehaan** [comment]
Given discussion on this has resolved after our feature freeze date though, we are a little short on test time.  I would like to merge this early in the 1.2 cycle.

**Comment by mpdehaan** [comment]
testing now...

**Comment by mpdehaan** [comment]
code pushed, everything was fine, I just made the _args, *_kwargs consistent for later.

Thanks!

**Pull request closed without merging**
