### PR TITLE
Fixing nxos_feature

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_feature

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Solves #20269. Affects 2.2 as well.

### CODE REVIEW

**Comment by gundalow** [comment]
Does this need backporting to stable-2.2?

**Comment by GGabriele** [comment]
Yes

**Comment by gundalow** [comment]
@privateip Review and merge into devel & stable-2.2 please

**Comment by privateip** [comment]
needs_rebase

**Pull request closed without merging**
