### PR TITLE
Fixing tab indent on elb_target_group.py example

### PR DESCRIPTION
**Pull request by mmercer-apixio**
##### SUMMARY
Documentation update -- adding appropriate indentation in example

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
elb_target_group.py

##### ANSIBLE VERSION
stable-2.4

### CODE REVIEW

**Comment by mmercer-apixio** [comment]
The shippable failing status appears to have been associated with the pypi testing based on conversation with mattclay in dev channel

**Comment by gundalow** [comment]
Any reason this PR has been made against `stable-2.4`

Generally PRs should be done against `devel`, once merged the Core Team will cherry-pick the fix into the older `stable-x.y` branches as needed

**Comment by mmercer-apixio** [comment]
@gundalow it is already fixed in devel (and I had even commented as such in the dev channel), unfortuantely, the 2.4 docset that people are using currently shows that it hasnt / wasnt backported, and thus, one of the examples is broken.  At the time that I had inquired about it, pypi was acting up, and numerous other things were being discussed, so this is only a doc update, i didnt want to create too much ruckus getting it to be fixed

**Comment by mmercer-apixio** [comment]
Additionally, I believe the doc fix that was made doesn't actually work for 2.4 as it talks about a feature that I do not believe is included in 2.4 yet, see:
https://github.com/ansible/ansible/commit/866239e01af12ef1fe2d4c6202c5b8bd4329c01f

**Review by s-hertel — APPROVED** [review]
This looks fine to me. This fix was made on devel in a feature for 2.5 and wasn't backported.

@abadger do you want this merged to 2.4?

**Comment by abadger** [comment]
sounds good.  I'll merge it for 2.4.4

**Comment by abadger** [comment]
Thanks @mmercer-apixio for backporting and @s-hertel for reviewing :-)

**Pull request merged**
