### PR TITLE
Fix "ao" symbolic permissions (fixes #80442)

### LINKED ISSUE #80442: Symbolic file modes, "a" combined with anything else does not work.
### Summary

In a symbolic file mode, "a" if combined with something else does not work correctly.

"ao", "oa", "aa" should all be the same as "a".

I found this while doing a code review of the permission code.

### Issue Type

Bug Report

### Component Name

copy

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.0.dev0] (fix_ao_perms bab6c08993) last updated 2023/04/06 07:32:43 (GMT -600)
  config file = None
  configured module search path = ['/home/sean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sean/software/ansible-realgo/lib/ansible
  ansible collection location = /home/sean/.ansible/collections:/usr/share/ansible/collections
  executable location = bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are
modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and
can become unstable at any point.
CONFIG_FILE() = None
EDITOR(env: EDITOR) = lvim
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

Use "aa" in the USER part of a symbolic permission.

### Expected Results

Should be treated as "a"

### Actual Results

```console
These unit tests fail:

   (0o100777, u'ao=rX', 0o0555),
   (0o040777, u'ao=rX', 0o0555),
   (0o100777, u'oa=rX', 0o0555),
   (0o040777, u'oa=rX', 0o0555),
   (0o100777, u'aa=rX', 0o0555),
   (0o040777, u'aa=rX', 0o0555),
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by linsomniac**
##### SUMMARY

The "a" permission combined with anything else does not work properly

While doing a code review of the permissions I noticed a "if users == 'a'" where it should be "if 'a' in users".  This results in "a" combined with anything else not being treated as "a".  "ao", "oa", "aa", "ouag" are all treated as "a" by "chmod".

I added unit tests that demonstrated the problem, made my change, and verified that the unit tests passed.

Fixes #80442 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
copy

##### ADDITIONAL INFORMATION
I believe the summary provides all the information.

### CODE REVIEW

**Review by bcoca — CHANGES_REQUESTED** [review]
first, i would not match chmod behavior since this is misleading and could act on what is a typo or misconception of the play author.  For me this is an error and should return to the user as such as their original meaning is unclear. " did you mean all or all except group/owner/user or what?"

**Comment by linsomniac** [comment]
Fair enough, a judgement call can be made on it.

A few points to consider:

First and foremost, the docstring for _symbolic_mode_to_octal says that it follows the chmod man page.  So there's a case to be had for matching the chmod functionality.  The chmod man page says "[ugoa...]", which to me the "..." implies that, since the "ugoa" set is already mentioned, that it is allowing duplication.  It probably doesn't make sense for human input, but might for machine generated contexts ("take the current permissions string and just whack an "a" on it to get it to apply to all users").

Ideally, either we follow the existing spec, or design a new one and document it in all the appropriate places.  I'm not the person to do that, I vote for following the existing spec.

There may be some confusion in the future (I don't know, may have even been some in the past), for "this permission chmod accepts but Ansible doesn't", and the divergence from the "chmod spec" or "chmod reference implementation".

I'd also like to mention that diverging from the (or at least a) reference implementation makes things a little more difficult in some ways, specifically machine verification of the Ansible implementation.  There seem to be a few different cases open right now around the permission code, and the code is fairly complex (it originally took me ~4 hours to track down and fix the bug that led me to the code review that found this code).

I have been working on a much easier to maintain implementation and one of the ways I have been verifying that code is extensive fuzz testing of umask/stat/mode_string of my implementation vs chmod.  Matching the reference implementation makes it easier to switch implementations or automated-test the Ansible code to make shallower bugs.

I'm thinking of a world where it's unlikely the symbolic code has bugs, and the code is dramatically simpler as well.

To that end, I will say that last night I pulled out the Ansible code and ran my fuzz testing against it, and it didn't even pass the first of the million tests I had slated for it, because of this specific issue (I had already found this issue at that point, in the code review as I was pulling the code out of Ansible).  Once I fixed that though, there were many other divergences from chmod, I'm sure many off them unlikely in human crafted permissions, but it's hard to tell what might be legit corner cases, it's much easier just to say "we match the reference".

To give an idea, around 10% of the test cases I throw at the ansible code end up having divergence from chmod.  Here are a few examples:

```
umask=46 filemode=2700 modestr=uoogu=xX,og-wrrwr chmod_filemode=111 chmod_dirmode=2111 our_filemode=111 our_dirmode=111  #  DIR WRONG
umask=726 filemode=5006 modestr=ua-x,ua+,aggu+u,ogg+Xsrt,ua=xXwww,aa=rtX chmod_filemode=1555 chmod_dirmode=7555 our_filemode=1555 our_dirmode=1555  #  DIR WRONG
umask=36 filemode=4572 modestr=g=s,auao-wrt,ugag=Xrx,g-XwX,ou+r,g+stwrrr,u+x chmod_filemode=2565 chmod_dirmode=6565 our_filemode=2565 our_dirmode=2565  #  DIR WRONG
umask=100 filemode=4113 modestr=g-tt,gga=,gog+,aauo-wwX chmod_filemode=0 chmod_dirmode=4000 our_filemode=0 our_dirmode=0  #  DIR WRONG
umask=531 filemode=3451 modestr=u+xwwtXr,go+x,uog=ttt,uo+ws,agogu+t chmod_filemode=5202 chmod_dirmode=7202 our_filemode=5202 our_dirmode=5202  #  DIR WRONG
umask=513 filemode=4422 modestr=oug=xt,ooo=g,u=wtw chmod_filemode=211 chmod_dirmode=4211 our_filemode=211 our_dirmode=211  #  DIR WRONG
umask=210 filemode=6373 modestr=g+t,gaugg=u,ua+trw,aguua-xrs,=X chmod_filemode=0 chmod_dirmode=101 our_filemode=0 our_dirmode=111  #  DIR WRONG
umask=535 filemode=7411 modestr=ao-rxr,g+trxXxxt,ou=twt,u+XXx,g+,uug= chmod_filemode=1002 chmod_dirmode=7002 our_filemode=1002 our_dirmode=1002  #  DIR WRONG
umask=462 filemode=4500 modestr=oa-rx,ga-,o+x,agg-wwwx,ooau-,gaaa+Xxt,aou=w chmod_filemode=222 chmod_dirmode=4222 our_filemode=222 our_dirmode=222  #  DIR WRONG
umask=704 filemode=4205 modestr=oa=Xtttx,o-t,agg-tr chmod_filemode=111 chmod_dirmode=4111 our_filemode=111 our_dirmode=111  #  DIR WRONG
```

To give you an idea of the code simplification I'm talking about, see this URL: https://github.com/linsomniac/symbolicmode/blob/main/src/symbolicmode/__init__.py

That code implements all of the single-operator modes ("ug=rw"), the last thing I have to add is multi-operator modes ("ug=rw+x-X").  I'd like to think it's simpler than the Ansible code, though I'm still iterating on simplicity.

It also fixes some issues with the Ansible implementation, beyond those found by the fuzz testing, including:

- umask in Ansible is called in a tight loop, called for a combination of users and modes, and umask is a system call so that's fairly expensive, relatively speaking.
- I guess the others are more stylistic, such as being a more readable flow rather than jumping around between functions and definitions at the top of the file and external references like reduce and PERM_BITS, etc...

**Comment by linsomniac** [comment]
@bcoca and @s-hertel : I believe the direction that this is moving is that the resolution @bcoca requested is being implemented in #80449, and there is no further discussion around "this diverges from the chmod implementation" and "probably need to document the divergence from chmod".  In which case, we probably should just close this?

**Comment by bcoca** [comment]
closing in favor of #80449, @linsomniac thanks for reporting it and helping getting this fixed

**Pull request closed without merging**
