### PR TITLE
[stable-2.8] lineinfile - properly insert line when line exists and backrefs are enabled (#63763)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Backport of #63763 for Ansible 2.8
(cherry picked from commit 29d4d318a5)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/modules/files/lineinfile.py`

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
cc @samdoran 
This PR wasn't merged into ansible 2.8

**Comment by yuexiao-wang** [comment]
@Andersson007 Could you approve it to merge into ansible v2.8 ? Thanks
I had the same issue with ansible v2.9

**Comment by Andersson007** [comment]
@yuexiao-wang  it is not needed to be approved.
@abadger could you please look

**Comment by yuexiao-wang** [comment]
cc @abadger

**Comment by samdoran** [comment]
This will be merged before the next 2.8.x release.

**Comment by yuexiao-wang** [comment]
Thanks

**Pull request merged**
