### PR TITLE
Make all lookup plugins accept lists as arguments

### PR DESCRIPTION
**Pull request by dhozac**
This makes with_...: work with all of them, which is the API they should all conform to.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Some minor style notes:

 spaces around [ ] in arrays please.

[terms] should be [ terms ]

to make things a bit more readable, [i] is fine for indexing

[ a , b , c ]

rather than [a,b,c]

also the following is a bit hard to read:

```
 ret.extend([ f[dwim_prefix_len:] for f in glob.glob(dwimterms) if os.path.isfile(f) ])
```

It's fine to break this into multiple lines.

I am also suspecting because not many people are going to use redis and dnstext those modules should probably be outside of core.

**Comment by mpdehaan** [comment]
Also please supply more detailed descriptions in your pull requests.   I can understand examples a lot better when they are more fleshed out.   Show us specifically what works and what doesn't, and what you are changing.

**Comment by mpdehaan** [comment]
@dhozac ping -- any more detail on what this does?

**Comment by dhozac** [comment]
It ensures all lookup plugins conform to the API of accepting a string or a list as an argument, and always returning a list, which is required to be used as `with_*`.

This also means that you can do e.g.

```
with_fileglob: 
- /path/to/files/*
- /other/path/to/files/*
```

to cater to the most basic with_\* in with_\* cases.

**Comment by dhozac** [comment]
Updated to use `[ terms ]`.

**Comment by mpdehaan** [comment]
sounds good to me, thanks!

**Pull request merged**
