### PR TITLE
scaleway: Add common documentation fragment

### PR DESCRIPTION
**Pull request by Spredzy**
##### SUMMARY

Every scaleway modules will require the same base of parameters. Instead
of documenting it each and every time, we build a doc fragment that will
allow one to simply extend documentation for every new module.

```
[...]
extends_documentation_fragment: scaleway
[...]
```

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

  - scaleway

##### ANSIBLE VERSION

  - devel

##### ADDITIONAL INFORMATION

  - N/A

### CODE REVIEW

**Comment by Spredzy** [comment]
cc @sieben

**Comment by remyleone** [comment]
That's perfect and could be merged. Does that mean that I can remove those parameters from module documentation strings from now on?

**Comment by Spredzy** [comment]
@sieben if you use the `extend_documentation_fragment: scaleway`, then yes.

**Comment by remyleone** [comment]
Could this be merged for me to use it? I can open a new PR that simplify documentation string once this is merged.

**Pull request merged**
