### PR TITLE
Refactor getvm method

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix refactors getvm method and modules which are using it.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/vmware.py
lib/ansible/modules/cloud/vmware/vmware_guest.py
lib/ansible/modules/cloud/vmware/vmware_guest_facts.py
lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py

##### ANSIBLE VERSION

```
2.4devel
```

### CODE REVIEW

**Comment by jctanner** [comment]
Looks good to me. Would like for someone else in the list of maintainers to chime in as well.

**Comment by dav1x** [comment]
Looks good to me. The vmware_vm_shell works great. I wish you could return the command output instead of the PID.

**Comment by dav1x** [comment]
shipit

**Comment by Akasurde** [comment]
@jctanner @dav1x Thanks for review and merge.

**Pull request merged**
