### PR TITLE
[WIP] Docuemntation for unit testcases

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### SUMMARY

Unit tests documentation

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by sivel** [comment]
What is the purpose here? It seems that a lot of good generic documentation is being removed and replaced with very specific docs for a subset of modules.

**Comment by GomathiselviS** [comment]
This will be added as part of resource module documentation.

**Comment by netmonk** [comment]
Fix also Title :)

**Comment by samccann** [comment]
Closing in favor of #5891

**Pull request closed without merging**
