### PR TITLE
Redhat subscription proxy support

### PR DESCRIPTION
**Pull request by philipgough**
##### SUMMARY
Add support for registration through subscription manager through HTTP proxy

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module `redhat_subscription`

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Oct 11 2016, 05:24:00) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

### CODE REVIEW

**Comment by PhilipGough** [comment]
@alikins Any chance of this getting in for 2.3 or should I move the PR to 2.4 at this point?

**Comment by philipgough** [comment]
@alikins @gundalow I've updated docs to added since 2.4, anything else need to be done to progress this issue? Thanks

**Review by gundalow — APPROVED** [review]

**Comment by PhilipGough** [comment]
Rebased. Ping @alikins

**Comment by philipgough** [comment]
Rebase again, ping @jctanner could we get this change tested and merged?

**Review by mkrizek — APPROVED** [review]
LGTM :+1:

**Comment by alikins** [comment]
@PhilipGough @mkrizek Is this something we want cherry-picked/backported to the stable-2.3 branch as well?

**Comment by philipgough** [comment]
@alikins personally, I'm not overly concerned with back-porting this to 2.3. However the [linked PR with bug fix](https://github.com/ansible/ansible/pull/24179) was a cherry pick candidate that there is a request for back porting so might be worth considering

**Pull request merged**
