### PR TITLE
Adds a notification/slack module

### PR DESCRIPTION
**Pull request by zimbatm**
This module allows to send notifications to a team/channel of
https://slack.com

### CODE REVIEW

**Comment by zimbatm** [comment]
Got reviewed by a team member of slack

**Comment by coudron** [comment]
+1 This would be great to get merged in

**Comment by speier** [comment]
+1 for Slack integration, love to see get merged

**Comment by leon-storm** [comment]
+1. More or less the one thing that keeps us from using slack.

**Comment by erning** [comment]
+1

**Comment by mpdehaan** [comment]
I just merged one of these into core:  https://github.com/ansible/ansible/blob/devel/library/notification/slack ... sorry for duplicate efforts, if you find anything you would like to enhance please send a pull request!

**Pull request closed without merging**
