### PR TITLE
[2.9] mysql_user: fix overriding user passowrd to the same

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Backport of https://github.com/ansible-collections/community.general/pull/609

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
mysql_user

### CODE REVIEW

**Comment by geerlingguy** [comment]
This PR fixes an idempotence bug that appears in both the default MySQL versions in Debian 10 and Ubuntu 20.04.

**Comment by Andersson007** [comment]
@geerlingguy do you have an opportunity to test the changes on those distributions?
When i was fixing the bug, i ran my tests on CentOS 7 + mysql 8*. It should be fixed for other distributions as well because a source of the problem is mysql version 8+ but anyway would be cool to be sure that everything works ok in your roles.

**Review by nitzmahone — APPROVED** [review]

**Comment by geerlingguy** [comment]
@Andersson007 - I can confirm that it fixes the idempotence bug on Debian 10 / Ubuntu 20.04's default versions; MariaDB 10.3.

**Comment by Andersson007** [comment]
@geerlingguy nice, thanks for checking!
@nitzmahone thanks for merging!

**Pull request merged**
