### PR TITLE
fileglob_to_dict lookup plugin for returning dictionaries from fileglobs

### PR DESCRIPTION
**Pull request by ghost**
I would like to contribute a module that allows targeting a directory with a fileglob and getting back a list of dictionaries that can be used as items in a loop.

I've been using it to a target a directory of user files for passing to the user module, but it's generally useful for any directory full of files that have key/attribute pairs.

### CODE REVIEW

**Comment by mpdehaan** [comment]
We're trying to control lookup plugin sprawl so I don't think we are likely to include this in core.

Further DOCUMENTATION blocks don't get read by lookup plugins.

Stop by ansible-project if you would like to discuss, thanks!!!

**Comment by ghost** [comment]
I understand the motivations to make Ansible more support-ready.  Is there a place that I could commit it in non-core?  (ansible-modules-extras doesn't include plugins)

**Comment by bcoca** [comment]
lookups are for querying data, not a good place to put data tranformations,
you might want to use a filter for that

On Tue, Dec 9, 2014 at 10:32 AM, tristan notifications@github.com wrote:

> I understand the motivations to make Ansible more support-ready. Is there
> a place that I could commit it in non-core? (ansible-modules-extras doesn't
> include plugins)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/pull/9730#issuecomment-66300596.

## 

Brian Coca

**Comment by ghost** [comment]
Sounds good to me, thanks for the response.

**Pull request closed without merging**
