### PR TITLE
K8s lookup plugin

### PR DESCRIPTION
**Pull request by chouseknecht**
Uses the OpenShift client to drive the OpenShift lookup plugin. 

- Adds a `k8s` lookup, and an `openshift` lookup
- Allows access to all of the K8s and OpenShift APIs, not just OpenShift `v1`
- Makes the UI consistent with the K8s and OpenShift modules
- Provides the full range of API authentication options
- Prevents logging of sensitive data when performing a lookup on Secret objects.

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
shipit

**Comment by fabianvf** [comment]
[Fact plugin](https://trello.com/c/nHXOs4Xm/5-fact-plugin)

**Comment by fabianvf** [comment]
[Fact plugin](https://trello.com/c/nHXOs4Xm/5-fact-plugin)

**Comment by samdoran** [comment]
shipit

**Pull request merged**
