### PR TITLE
New module: manage Citrix Netscaler load balancer monitors configuration (network/netscaler/netscaler_lb_monitor) 

### PR DESCRIPTION
**Pull request by giorgos-nikolopoulos**
##### SUMMARY

This PR adds a new Netscaler module netscaler_lb_monitor

##### ISSUE TYPE

 - New Module Pull Request
##### COMPONENT NAME

lib/ansible/modules/network/netscaler/netscaler_lb_monitor.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (netscaler_lb_monitor c91e6e38f8) last updated 2017/06/27 17:21:20 (GMT +300)
  config file = /home/georgen/.ansible.cfg
  configured module search path = [u'/home/georgen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/georgen/repos/ansible_fork/lib/ansible
  executable location = /home/georgen/repos/ansible_fork/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### ADDITIONAL INFORMATION

Unit tests are provided.
Integration tests are provided.

```

```

### CODE REVIEW

**Comment by ghost** [comment]
good template.
I have a one question.

I tried
```
- netscaler_lb_monitor:
    nsip: "aaa"
    nitro_user: "bbb"
    nitro_pass: "ccc"
    httprequest: "HEAD /check.html"
    monitorname: "monitorname"
    respcode: ["200"]
    type: HTTP
```
but faild.

#### update(template already exist)
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "loglines": ["Applying actions for state present", "Checking if monitor exists", "Checking if monitor is identical", "Updating monitor"], "msg": "nitro exception errorcode=1093, message=Argument pre-requisite missing [validateCred, type==CITRIX-XD-DDC]"}
```
#### insert
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "loglines": ["Applying actions for state present", "Checking if monitor exists", "Adding monitor"], "msg": "nitro exception errorcode=1093, message=Argument pre-requisite missing [storefrontacctservice, type==STOREFRONT]"}
```
'type: HTTP' is not used in validateCred and storefrontacctservice.

and I successfully applied this patch.
```
1065c1065
<         validatecred=dict(type='bool'),
---
>         #validatecred=dict(type='bool'),
1104c1104
<         storefrontacctservice=dict(type='bool'),
---
>         #storefrontacctservice=dict(type='bool')
```

netscaler verison
NS11.1 49.16.nc

**Comment by giorgos-nikolopoulos** [comment]
This is a known issue.

The problem in short is that the option value is set erroneously to `False` when the option is absent from the module arguments.

This is fixed in the source repository but the fix has not been pushed yet to ansible.

Currently we have a number of open PRs for new Netscaler modules, and we don't want to overstress the ansible team with an excessive amount of open PRs.

We will push the fix to ansible in the future but in the mean time you can head to the source [repo](https://github.com/citrix/netscaler-ansible-modules) to get the fixed version.

**Comment by ghost** [comment]
@giorgos-nikolopoulos 
Thanks!

**Comment by giorgos-nikolopoulos** [comment]
This is a bump for review.

**Pull request merged**
