### PR TITLE
Add modules names to CLI_SUPPORTED_MODULES and update modules to fix bugs

### PR DESCRIPTION
**Pull request by yuandongx**
SUMMARY
CLI_SUPPORTED_MODULES is a set of which modules connection type is network_cli.

Ansible Version Info
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.9.0.dev0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]

ISSUE TYPE
Bugfix Pull Request
COMPONENT NAME
lib/ansible/modules/network/cloudengine/ce_acl.py
lib/ansible/modules/network/cloudengine/ce_acl_advance.py
lib/ansible/modules/network/cloudengine/ce_acl_interface.py
lib/ansible/modules/network/cloudengine/ce_bfd_global.py
lib/ansible/modules/network/cloudengine/ce_bfd_session.py
lib/ansible/modules/network/cloudengine/ce_bfd_view.py
lib/ansible/modules/network/cloudengine/ce_bgp.py
lib/ansible/modules/network/cloudengine/ce_bgp_af.py
lib/ansible/modules/network/cloudengine/ce_bgp_neighbor.py
lib/ansible/modules/network/cloudengine/ce_bgp_neighbor_af.py
lib/ansible/modules/network/cloudengine/ce_dldp.py
lib/ansible/modules/network/cloudengine/ce_dldp_interface.py
lib/ansible/modules/network/cloudengine/ce_evpn_bd_vni.py
lib/ansible/modules/network/cloudengine/ce_evpn_bgp_rr.py
lib/ansible/modules/network/cloudengine/ce_evpn_global.py
lib/ansible/modules/network/cloudengine/ce_facts.py
lib/ansible/modules/network/cloudengine/ce_file_copy.py
lib/ansible/modules/network/cloudengine/ce_info_center_debug.py
lib/ansible/modules/network/cloudengine/ce_info_center_global.py
lib/ansible/modules/network/cloudengine/ce_info_center_log.py
lib/ansible/modules/network/cloudengine/ce_info_center_trap.py
lib/ansible/modules/network/cloudengine/ce_interface.py
lib/ansible/modules/network/cloudengine/ce_interface_ospf.py
lib/ansible/modules/network/cloudengine/ce_ntp.py
lib/ansible/modules/network/cloudengine/ce_reboot.py
lib/ansible/modules/network/cloudengine/ce_static_route.py
lib/ansible/modules/network/cloudengine/ce_stp.py
lib/ansible/modules/network/cloudengine/ce_switchport.py
lib/ansible/modules/network/cloudengine/ce_vrf.py
lib/ansible/modules/network/cloudengine/ce_vrf_af.py
lib/ansible/modules/network/cloudengine/ce_vrf_interface.py
lib/ansible/modules/network/cloudengine/ce_vrrp.py
lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
lib/ansible/modules/network/cloudengine/ce_vxlan_global.py
lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
lib/ansible/modules/network/cloudengine/ce_vxlan_vap.py
lib/ansible/plugins/action/ce.py
lib/ansible/modules/network/cloudengine/ce_mlag_interface.py
lib/ansible/modules/network/cloudengine/ce_netstream_export.py

ADDITIONAL INFORMATION
tasks:
  - name: "Gather_subset is config"
    ce_facts:
      gather_subset: config  
<---Before modify-->
<172.101.14.11> using connection plugin network_cli (was local)
<172.101.14.11> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.101.14.11> EXEC /bin/sh -c 'echo ~root && sleep 0'
<172.101.14.11> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832 `" && echo ansible-tmp-1555571807.65-165202209042832="` echo /root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/cloudengine/ce_facts.py
<172.101.14.11> PUT /root/.ansible/tmp/ansible-local-10275HeLSGN/tmpVC5ANl TO /root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py
<172.101.14.11> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/ /root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py && sleep 0'
<172.101.14.11> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py && sleep 0'
<172.101.14.11> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ce_facts_payload_eBI4g1/__main__.py", line 411, in <module>
  File "/tmp/ansible_ce_facts_payload_eBI4g1/__main__.py", line 396, in main
  File "/tmp/ansible_ce_facts_payload_eBI4g1/__main__.py", line 327, in populate
IndexError: list index out of range

fatal: [Friend-XYS-CCM-AZ2-TP&TS-KVM-TOR-CE6850-SW1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1555571807.65-165202209042832/AnsiballZ_ce_facts.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ce_facts_payload_eBI4g1/__main__.py\", line 411, in <module>\n  File \"/tmp/ansible_ce_facts_payload_eBI4g1/__main__.py\", line 396, in main\n  File \"/tmp/ansible_ce_facts_payload_eBI4g1/__main__.py\", line 327, in populate\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

<----After-->
ok: [10.130.200.118] => {
    "ansible_facts": {
        "BIOS Version": "433",
        "Board Type": "CE5855-48T4S2Q-EI",
        "CPLD1 Version": "102",
        "MAB Version": "1",
        "PCB Version": "CEM48T4S2QP03 VER B",
        "config": [
            "#",
            "sysname 130.20",
            "#",
            "port split dimension interface 40GE1/0/1",
            "port split dimension interface 40GE2/0/1",
            "#",
            "vlan batch 100 4060 to 4062",
            "#",
            "arp static 1.1.8.2 0008-0008-0008 interface Eth-Trunk1",
            "#",
            "lldp enable",
            "#",
            "return"
        ],
        "discovered_interpreter_python": "/usr/bin/python",
        "gather_subset": [
            "default",
            "config"
        ],
        "hostname": "130.20"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "config"
            ],
            "host": "10.130.200.118",
            "password": null,
            "port": 10066,
            "provider": {
                "host": "10.130.200.118",
                "password": null,
                "port": 10066,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "rsa_user",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "rsa_user",
            "validate_certs": null
        }
    }
}

changed: [10.130.200.118] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": true,
    "end_state": {
        "arp_suppress": "disable",
        "evn_bgp": "enable",
        "evn_peer_ip": [
            "7.7.7.7"
        ],
        "evn_reflect_client": null,
        "evn_server": "disable",
        "evn_source_ip": "6.6.6.6",
        "host_collect_protocol": null
    },
    "existing": {
        "arp_suppress": "disable",
        "evn_bgp": "disable",
        "host_collect_protocol": null
    },
    "invocation": {
        "module_args": {
            "arp_collect_host": null,
            "arp_suppress": null,
            "bridge_domain_id": null,
            "evn_bgp": "enable",
            "evn_peer_ip": "7.7.7.7",
            "evn_reflect_client": null,
            "evn_server": null,
            "evn_source_ip": "6.6.6.6",
            "host": "10.130.200.118",
            "host_collect_protocol": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 10088,
            "provider": {
                "host": "10.130.200.118",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 10088,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "huawei",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "huawei",
            "validate_certs": null,
            "vbdif_name": null
        }
    },
    "proposed": {
        "evn_bgp": "enable",
        "evn_peer_ip": "7.7.7.7",
        "evn_source_ip": "6.6.6.6",
        "state": "present"
    },
    "updates": [
        "evn bgp",
        "source-address 6.6.6.6",
        "peer 7.7.7.7"
    ]
}
TASK [test the bridge_domain_id] *************************************************************************************************
task path: /usr/huawei/xuyuandong/test_playbook/test_ce_vxlan_global.yml:26
<10.130.200.118> using connection plugin netconf (was local)
<10.130.200.118> ESTABLISH NETCONF SSH CONNECTION FOR USER: huawei on PORT 10088 TO 10.130.200.118
<10.130.200.118> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.130.200.118> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1556004587.56-77734157287158 `" && echo ansible-tmp-1556004587.56-77734157287158="` echo /root/.ansible/tmp/ansible-tmp-1556004587.56-77734157287158 `" ) && sleep 0'
<10.130.200.118> Attempting python interpreter discovery
<10.130.200.118> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.9.0.dev0-py2.7.egg/ansible/modules/network/cloudengine/ce_evpn_bd_vni.py
<10.130.200.118> PUT /root/.ansible/tmp/ansible-local-54387KNgHE5/tmp81OBZ9 TO /root/.ansible/tmp/ansible-tmp-1556004587.56-77734157287158/AnsiballZ_ce_evpn_bd_vni.py
<10.130.200.118> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1556004587.56-77734157287158/ /root/.ansible/tmp/ansible-tmp-1556004587.56-77734157287158/AnsiballZ_ce_evpn_bd_vni.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1556004587.56-77734157287158/AnsiballZ_ce_evpn_bd_vni.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1556004587.56-77734157287158/ > /dev/null 2>&1 && sleep 0'
 [WARNING]: The value 100 (type int) in a string field was converted to u'100' (type string). If this does not look like what you
expect, quote the entire value to ensure it does not change.

[DEPRECATION WARNING]: Param 'transport' is deprecated. See the module docs for more information. This feature will be removed in
 version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [10.130.200.118] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": true,
    "end_state": {
        "bridge_domain_id": "100",
        "evpn": "enable",
        "route_distinguisher": null,
        "vpn_target_both": [],
        "vpn_target_export": [],
        "vpn_target_import": []
    },
    "existing": {
        "bridge_domain_id": "100",
        "evpn": "disable",
        "route_distinguisher": null,
        "vpn_target_both": [],
        "vpn_target_export": [],
        "vpn_target_import": []
    },
    "invocation": {
        "module_args": {
            "bridge_domain_id": "100",
            "evpn": "enable",
            "host": "10.130.200.118",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 10088,
            "provider": {
                "host": "10.130.200.118",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 10088,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "huawei",
                "validate_certs": null
            },
            "route_distinguisher": null,
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "huawei",
            "validate_certs": null,
            "vpn_target_both": null,
            "vpn_target_export": null,
            "vpn_target_import": null
        }
    },
    "proposed": {
        "bridge_domain_id": "100",
        "evpn": "enable",
        "route_distinguisher": null,
        "state": "present",
        "vpn_target_both": [],
        "vpn_target_export": [],
        "vpn_target_import": []
    },
    "updates": [
        "bridge-domain 100",
        "  evpn"
    ]
}

TASK [test the interface] ********************************************************************************************************
task path: /usr/huawei/xuyuandong/test_playbook/test_ce_vxlan_global.yml:31
<10.130.200.118> using connection plugin netconf (was local)
<10.130.200.118> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.130.200.118> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1556004589.29-3954101342495 `" && echo ansible-tmp-1556004589.29-3954101342495="` echo /root/.ansible/tmp/ansible-tmp-1556004589.29-3954101342495 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.9.0.dev0-py2.7.egg/ansible/modules/network/cloudengine/ce_interface.py
<10.130.200.118> PUT /root/.ansible/tmp/ansible-local-54387KNgHE5/tmpTxXDW8 TO /root/.ansible/tmp/ansible-tmp-1556004589.29-3954101342495/AnsiballZ_ce_interface.py
<10.130.200.118> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1556004589.29-3954101342495/ /root/.ansible/tmp/ansible-tmp-1556004589.29-3954101342495/AnsiballZ_ce_interface.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1556004589.29-3954101342495/AnsiballZ_ce_interface.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1556004589.29-3954101342495/ > /dev/null 2>&1 && sleep 0'
changed: [10.130.200.118] => {
    "changed": true,
    "end_state": {
        "admin_state": "down",
        "description": "12121qwq",
        "interface": "Vlanif3111"
    },
    "existing": {
        "admin_state": "up",
        "description": "12121qwq",
        "interface": "Vlanif3111"
    },
    "invocation": {
        "module_args": {
            "admin_state": "down",
            "description": null,
            "host": "10.130.200.118",
            "interface": "vlanif 3111",
            "interface_type": null,
            "l2sub": false,
            "mode": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 10088,
            "provider": {
                "host": "10.130.200.118",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 10088,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "huawei",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "huawei",
            "validate_certs": null
        }
    },
    "proposed": {
        "admin_state": "down",
        "interface": "vlanif 3111",
        "l2sub": false,
        "state": "present"
    },
    "updates": [
        "interface vlanif 3111",
        "shutdown"
    ]
}

changed: [10.130.200.118] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": true,
    "end_state": {
        "arp_suppress": "disable",
        "evn_bgp": "enable",
        "evn_peer_ip": [
            "7.7.7.7"
        ],
        "evn_reflect_client": null,
        "evn_server": "disable",
        "evn_source_ip": "6.6.6.6",
        "host_collect_protocol": null
    },
    "existing": {
        "arp_suppress": "disable",
        "evn_bgp": "disable",
        "host_collect_protocol": null
    },
    "invocation": {
        "module_args": {
            "arp_collect_host": null,
            "arp_suppress": null,
            "bridge_domain_id": null,
            "evn_bgp": "enable",
            "evn_peer_ip": "7.7.7.7",
            "evn_reflect_client": null,
            "evn_server": null,
            "evn_source_ip": "6.6.6.6",
            "host": "10.130.200.118",
            "host_collect_protocol": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 10088,
            "provider": {
                "host": "10.130.200.118",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 10088,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "huawei",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "huawei",
            "validate_certs": null,
            "vbdif_name": null
        }
    },
    "proposed": {
        "evn_bgp": "enable",
        "evn_peer_ip": "7.7.7.7",
        "evn_source_ip": "6.6.6.6",
        "state": "present"
    },
    "updates": [
        "evn bgp",
        "source-address 6.6.6.6",
        "peer 7.7.7.7"
    ]
}

TASK [test the  vni_id] **********************************************************************************************************
task path: /usr/huawei/xuyuandong/test_playbook/test_ce_vxlan_global.yml:22
<10.130.200.118> using connection plugin netconf (was local)
<10.130.200.118> ESTABLISH NETCONF SSH CONNECTION FOR USER: huawei on PORT 10088 TO 10.130.200.118
<10.130.200.118> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.130.200.118> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1556004310.25-206399494407393 `" && echo ansible-tmp-1556004310.25-206399494407393="` echo /root/.ansible/tmp/ansible-tmp-1556004310.25-206399494407393 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.9.0.dev0-py2.7.egg/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
<10.130.200.118> PUT /root/.ansible/tmp/ansible-local-53767vAtgrn/tmp0QNpCa TO /root/.ansible/tmp/ansible-tmp-1556004310.25-206399494407393/AnsiballZ_ce_vxlan_tunnel.py
<10.130.200.118> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1556004310.25-206399494407393/ /root/.ansible/tmp/ansible-tmp-1556004310.25-206399494407393/AnsiballZ_ce_vxlan_tunnel.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1556004310.25-206399494407393/AnsiballZ_ce_vxlan_tunnel.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1556004310.25-206399494407393/ > /dev/null 2>&1 && sleep 0'
 [WARNING]: The value 100 (type int) in a string field was converted to u'100' (type string). If this does not look like what you
expect, quote the entire value to ensure it does not change.

ok: [10.130.200.118] => {
    "changed": false,
    "end_state": {
        "nve_interface_name": "Nve1",
        "nve_mode": "mode-l2",
        "source_ip": null,
        "vni_peer_list_ip": [],
        "vni_peer_list_protocol": [
            {
                "protocol": "bgp",
                "vniId": "100"
            }
        ]
    },
    "existing": {
        "nve_interface_name": "Nve1",
        "nve_mode": "mode-l2",
        "source_ip": null,
        "vni_peer_list_ip": [],
        "vni_peer_list_protocol": [
            {
                "protocol": "bgp",
                "vniId": "100"
            }
        ]
    },
    "invocation": {
        "module_args": {
            "bridge_domain_id": null,
            "host": "10.130.200.118",
            "nve_mode": null,
            "nve_name": "Nve1",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "peer_list_ip": null,
            "port": 10088,
            "protocol_type": "bgp",
            "provider": {
                "host": "10.130.200.118",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 10088,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "huawei",
                "validate_certs": null
            },
            "source_ip": null,
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "huawei",
            "validate_certs": null,
            "vni_id": "100"
        }
    },
    "proposed": {
        "nve_name": "Nve1",
        "state": "present",
        "vni_id": "100"
    },
    "updates": []
}

TASK [test the  bridge_domain_id] ************************************************************************************************
task path: /usr/huawei/xuyuandong/test_playbook/test_ce_vxlan_global.yml:37
<10.130.200.118> using connection plugin netconf (was local)
<10.130.200.118> ESTABLISH NETCONF SSH CONNECTION FOR USER: huawei on PORT 10088 TO 10.130.200.118
<10.130.200.118> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.130.200.118> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1556004738.93-48991297696001 `" && echo ansible-tmp-1556004738.93-48991297696001="` echo /root/.ansible/tmp/ansible-tmp-1556004738.93-48991297696001 `" ) && sleep 0'
<10.130.200.118> Attempting python interpreter discovery
<10.130.200.118> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.9.0.dev0-py2.7.egg/ansible/modules/network/cloudengine/ce_vxlan_vap.py
<10.130.200.118> PUT /root/.ansible/tmp/ansible-local-54847YBeSzT/tmpTTTdXY TO /root/.ansible/tmp/ansible-tmp-1556004738.93-48991297696001/AnsiballZ_ce_vxlan_vap.py
<10.130.200.118> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1556004738.93-48991297696001/ /root/.ansible/tmp/ansible-tmp-1556004738.93-48991297696001/AnsiballZ_ce_vxlan_vap.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1556004738.93-48991297696001/AnsiballZ_ce_vxlan_vap.py && sleep 0'
<10.130.200.118> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1556004738.93-48991297696001/ > /dev/null 2>&1 && sleep 0'
 [WARNING]: The value 100 (type int) in a string field was converted to u'100' (type string). If this does not look like what you
expect, quote the entire value to ensure it does not change.

[DEPRECATION WARNING]: Param 'transport' is deprecated. See the module docs for more information. This feature will be removed in
 version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [10.130.200.118] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": true,
    "end_state": {
        "bind_intf_list": [],
        "bind_vlan_list": [
            "100"
        ],
        "bridge_domain_id": "100"
    },
    "existing": {
        "bind_intf_list": [],
        "bind_vlan_list": [],
        "bridge_domain_id": "100"
    },
    "invocation": {
        "module_args": {
            "bind_vlan_id": "100",
            "bridge_domain_id": "100",
            "ce_vid": null,
            "encapsulation": null,
            "host": "10.130.200.118",
            "l2_sub_interface": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pe_vid": null,
            "port": 10088,
            "provider": {
                "host": "10.130.200.118",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 10088,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "huawei",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "huawei",
            "validate_certs": null
        }
    },
    "proposed": {
        "bind_vlan_id": "100",
        "bridge_domain_id": "100",
        "state": "present"
    },
    "updates": [
        "bridge-domain 100",
        "l2 binding vlan 100"
    ]
}
META: ran handlers
META: ran handlers

### CODE REVIEW

**Comment by xuxiaowei0512** [comment]
#52937

**Comment by xuxiaowei0512** [comment]
@kpostrup
We are trying to update the code to fix this issue.
Thank you for your attention.
https://github.com/HuaweiSwitch/CloudEngine-Ansible/issues/64

**Comment by xuxiaowei0512** [comment]
bot_status

**Review by yuandongx — COMMENTED** [review]
Review and Merge, Please.

**Comment by xuxiaowei0512** [comment]
@team_networking @ansibot 
Need your review, thanks.

**Comment by xuxiaowei0512** [comment]
@ansibot

**Comment by xuxiaowei0512** [comment]
@xuyuandonggithub

**Comment by xuxiaowei0512** [comment]
@team_ansible  @team_networking
Need your review and approval.
Thanks a lot.

**Comment by xuxiaowei0512** [comment]
shipit

**Comment by xuxiaowei0512** [comment]
bot_status

**Comment by s-hertel** [comment]
After separating each bugfix into individual pull requests, each should have a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs) added.

**Comment by xuxiaowei0512** [comment]
@s-hertel 
I got it.I am going to colse this PR and recreate some PRs  and changelog fragments  for each file to fix bugs.
Thank you.

**Pull request closed without merging**
