### PR TITLE
Yum module - gpg_check param and some documentation.

### PR DESCRIPTION
**Pull request by Tinche**
Here's a little something for the yum module. Should be perfectly backwards compatible.

Sorry about all the formatting changes, my editor really likes removing whitespace.

Merge me, Michael DeHaan, you're my only hope!

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good to me!  In queue for testing.

**Comment by Tinche** [comment]
A colleague suggested a different approach, which I think is clearer: instead of a gpg_check parameter (default yes), we should introduce a skip_gpg_check parameter (defaults to no). Doing it with a gpg_check parameter might lead people to think it will force gpg checking on (which it won't, and can't easily), instead of simply not turning it off.

I'll push an additional commit this evening.

**Comment by mpdehaan** [comment]
I would suggest calling it disable_gpg_check=yes (default no)

Make it so!

Thanks

**Comment by skvidal** [comment]
A request for this patch - could you remove the commit which is just white-space changes?

**Comment by skvidal** [comment]
a second request - if we're going to start glomming on options as base level options how about a generic option that can be passed multiple times?

option=--nogpgcheck option=--skip-broken option=--setopt=exclude=somepkg

**Comment by Tinche** [comment]
@skvidal request 1: I could (would make a fresh pull request), but why? The trailing white space got automatically truncated by my Vim when saving. It's useless and pep8 will grumble about it. If you feel so strongly about it I'll get it back in.

Request 2: @mpdehaan, what say you? Not many modules do this, but for example the pip module does (parameter name extra_args). The apt module doesn't do this, and has a large number of params.

**Comment by Tinche** [comment]
In the meantime, here's what we talked about before.

**Comment by mpdehaan** [comment]
Tin, trailing whitespace edits break attribution and also confuse the
history.

I strongly prefer that patches not mangle whitespace unneccessarily.

As for multiple options, I do not think we need to support this as
something called "option" on the ansible line anyway.  Arguments in Ansible
resolve to hashes, and that kind of logic doesn't work so well with
multiple options, and makes the code get more complicated.    Taking
arbitrary options as a string to yum, though, like "options" seems
reasonable, but I'd prefer the higher level modelling of no_gpg_check for
now, so we can actually tell if it is passed in the code.

run "make pep8" vs "pep8" and I have already silenced all of the useless
 warnings from that tool and got it down to some reasonable subset -- but
even those do not matter in the end.

**Comment by Tinche** [comment]
Alright, I can see how changing the whitespace messes with the history and makes reading the incoming diff cumbersome (the bigger problem here IMO). On the other hand, trailing whitespace is basically unnecessary characters, and removing them has value (albeit maybe very small), and removing it is a pill that only needs to be taken once. A better approach is stripping them out before merging in code in the first place.

Instead of getting sidetracked into a discussion about trailing whitespace, since the changes here are pretty minimal I'll offer to make another push request with whitespace intact. Michael, when you're satisfied with the content of the pull request, just say the word if you want the whitespace back in.

As for the options thing, I agree with Michael: it seems to be to be the Ansible way to offer options individually. If someone needs skip_broken they can submit a pull request with that feature (maybe it'll be me!).

**Comment by mpdehaan** [comment]
ok, closing this, you can resubmit if you like, thanks

**Pull request closed without merging**
