### PR TITLE
Fix #23095 dynamic docker inventory setting config with environment variable

### LINKED ISSUE #23095: docker dynamic inventory script ignores DOCKER_CONFIG_FILE environment variable
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker dynamic inventory
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 097173c6f5) last updated 2017/03/29 12:35:28 (GMT -400)
  config file = /Users/milo/code/ansible-data/ansible.cfg
  configured module search path = [u'/Users/milo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

`ANSIBLE_CONFIG` points to mostly default config file, which only changes the inventory path (`inventory`) and roles path (`roles_path`) options.

Related to the `contrib/inventory/docker.py` dynamic inventory script in question for this issue, I have set the `DOCKER_CONFIG_FILE` environment variable to the absolute path of a custom docker config file which sets multiple docker hosts for use in building the dynamic inventory.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The documentation for the `docker.py` dynamic inventory script in `contrib/inventory` indicates that a docker configuration file can be specified by providing the `--config-file` cli argument or by setting the `DOCKER_CONFIG_FILE` environment variable. However, the environment variable is never checked, regardless of whether the `--config-file` option is given or not, or if the default/fallback `docker.yml` file exists or not.
##### STEPS TO REPRODUCE

* Copy the `docker.yml` example config file from `contrib/inventory/` to any directory (e.g. `/some/path/docker.yml`), and uncomment lines 64-74, e.g: 
    ```yaml
    defaults:
      host: unix:///var/run/docker.sock
      private_ssh_port: 22
      default_ip: 127.0.0.1

  hosts:
    - host: tcp://10.45.5.16:4243
      private_ssh_port: 2022
      default_ip: 172.16.3.45
    - host: tcp://localhost:4243
      private_ssh_port: 2029
    ```
* set the `DOCKER_CONFIG_FILE` environment variable to the path set above (`/some/path/docker.yml`)
* call the docker.py inventory script from the command line with `<ansible_root_dir>/contrib/inventory/docker.py --debug` and note that the debug output under `defaults:`, `hosts:`, and `auth params:` do not reflect the values set in the config file.

##### EXPECTED RESULTS

```yaml
defaults:

{
  "default_ip": "127.0.0.1", 
  "host": "unix:///var/run/docker.sock", 
  "private_ssh_port": 22
}
hosts: 

[
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "172.16.3.45", 
    "default_ssh_port": 2022, 
    "docker_host": "tcp://10.45.5.16:4243", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }, 
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "127.0.0.1", 
    "default_ssh_port": 2029, 
    "docker_host": "tcp://localhost:4243", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }
]
auth params:

  tls: False

  cacert_path: None

  timeout: 60

  default_ip: 172.16.3.45

  ssl_version: None

  tls_hostname: localhost

  docker_host: tcp://10.45.5.16:4243

  tls_verify: False

  key_path: None

  default_ssh_port: 2022

  cert_path: None

  api_version: 1.24
```
##### ACTUAL RESULTS

```yaml
defaults:

{}
hosts: 

[
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "127.0.0.1", 
    "default_ssh_port": "22", 
    "docker_host": "unix://var/run/docker.sock", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }
]
auth params:

  tls: False

  cacert_path: None

  timeout: 60

  default_ip: 127.0.0.1

  ssl_version: None

  tls_hostname: localhost

  docker_host: unix://var/run/docker.sock

  tls_verify: False

  key_path: None

  default_ssh_port: 22

  cert_path: None

  api_version: 1.24
```

### PR DESCRIPTION
**Pull request by milo-minderbinder**
##### SUMMARY

Fixes #23095 

Fixed issue preventing a caller from setting a docker configuration file (e.g. docker.yml) by specifing the config file path in the `DOCKER_CONFIG_FILE` environment variable. Previously, the cli argument parser set a default value for the `--config-file` argument which would prevent ever checking the environment variable, regardless of whether or not the `--config-file` argument even specified a valid file.
    
This commit adds a global `DEFAULT_DOCKER_CONFIG_FILE` variable, which points to the current default `docker.yml` config in the contrib/inventory directory. Now, when this script is called from the command line, the config file passed with the cli `--config-file` arg will be given the highest precedence; if it is absent, this script will then check if the `DOCKER_CONFIG_FILE` env var is set, and load the config file specified if possible. If neither the environment variable or cli argument are specified, then the script will attempt to parse the config file `docker.yml` in this script's directory (if present).  

If either the `DOCKER_CONFIG_FILE` environment variable or the `--config-file` argument are given but point to a nonexistant file, then the script will print an error message and exit with an error code.  It is *not* an error condition if the fallback `docker.yml` does not exist.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

`/contrib/inventory/docker.py` dynamic docker inventory script
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 097173c6f5) last updated 2017/03/29 12:35:28 (GMT -400)
  config file = /Users/milo/code/ansible-data/ansible.cfg
  configured module search path = [u'/Users/milo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION

with default `docker.yml` (uncomment last ten lines, as described in issue #23095)
```
DOCKER_CONFIG_FILE=/path/to/docker.yml ./contrib/inventory/docker.py --debug
```
```yaml
defaults:

{
  "default_ip": "127.0.0.1", 
  "host": "unix:///var/run/docker.sock", 
  "private_ssh_port": 22
}
hosts: 

[
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "172.16.3.45", 
    "default_ssh_port": 2022, 
    "docker_host": "tcp://10.45.5.16:4243", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }, 
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "127.0.0.1", 
    "default_ssh_port": 2029, 
    "docker_host": "tcp://localhost:4243", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }
]
auth params:

  tls: False

  cacert_path: None

  timeout: 60

  default_ip: 172.16.3.45

  ssl_version: None

  tls_hostname: localhost

  docker_host: tcp://10.45.5.16:4243

  tls_verify: False

  key_path: None

  default_ssh_port: 2022

  cert_path: None

  api_version: 1.24
```

### CODE REVIEW

**Comment by milo-minderbinder** [comment]
Any updates on this? I understand that there are plans to migrate inventory scripts like these to the new inventory plugin system, but this is a pretty simple fix and allows the script to work as described in its existing documentation.

**Review by felixfontein — APPROVED** [review]
I don't have any experience with dynamic inventories, but besides that, it looks good to me.

**Comment by felixfontein** [comment]
@akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet if anyone of you has experience with inventory scripts, please take a look at this one! (If not, also feel free ;) )

**Comment by danihodovic** [comment]
ship_it

**Comment by felixfontein** [comment]
@danihodovic you need to write it without underscore, otherwise it doesn't work.

Do you have experience with inventory scripts BTW? I'm curious because I don't, and it would be good to know who of us actually has :)

**Comment by milo-minderbinder** [comment]
> @akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet if anyone of you has experience with inventory scripts, please take a look at this one! (If not, also feel free ;) )

@akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet I can create a separate issue, but wanted to get your thoughts on [this related commit](https://github.com/milo-minderbinder/ansible/commit/c5c7bac03af6370267537572979bf14a6c1154e4) I've drafted. It relates to naming of ansible hosts & groups added by dynamic inventory scripts, and defining a set of naming conventions or verifiable rules  that group and host names should conform to. I raised the issue a while back in the Ansible dev Google group, and @bcoca indicated that the issue may be addressed with the new inventory plugins, but I didn't have time to dive into that feature at the time since it was still in design phase. Anyway, let me know if the dynamic inventory group/host naming issue still seems relevant and if I should create a separate issue & PR, or if this problem has been addressed through one of the ansible core plugins or modules. Thanks!

**Review by felixfontein — APPROVED** [review]
shipit

**Comment by bcoca** [comment]
rebuild_merge

**Comment by felixfontein** [comment]
@milo-minderbinder I asked on a ansible core public IRC meeting about your question; @bcoca said that he's sure we'll eventually end up with a docker inventory plugin, but if you want to go ahead, feel free! There's robably nobody working on one right now.

(It's probably best to create a Feature Request issue first; and if you want to work on it, indicate that there, so everyone knows that someone is working on it.)

**Comment by felixfontein** [comment]
@milo-minderbinder thank you for this PR!
@danihodovic @bcoca @samdoran and everyone else who reviewed: thanks a lot!

**Pull request merged**
