### PR TITLE
New filter getmountfrompath: retrieve corresponding mount from a given path

### PR DESCRIPTION
**Pull request by Yannig**
##### SUMMARY
This commit replace a part of the following PR: https://github.com/ansible/ansible/pull/11896/

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/filter/core.py
test/integration/test_space_available.yml

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by Yannig** [comment]
Retrieve corresponding path:

``` yaml
    - name: "Get corresponding mountpoint from a given path"
      set_fact:
        mount1:            "{{file1|getmountfrompath(ansible_mounts)}}"
        mount2:            "{{file2|getmountfrompath(ansible_mounts)}}"
    - debug: var=mount1
    - debug: var=mount2
```

Result in following result:

``` yaml
TASK [Get corresponding mountpoint from a given path] **************************
ok: [localhost]

TASK [debug var=mount1] ********************************************************
ok: [localhost] => {
    "changed": false, 
    "mount1": {
        "device": "/dev/sda1", 
        "fstype": "ext4", 
        "mount": "/", 
        "options": "rw,noatime,errors=remount-ro", 
        "size_available": 100358303744, 
        "size_total": 118014083072, 
        "uuid": "6d776313-2c09-4e73-97b3-34ab8debccf8"
    }
}

TASK [debug var=mount2] ********************************************************
ok: [localhost] => {
    "changed": false, 
    "mount2": {
        "device": "/dev/sdb7", 
        "fstype": "ext4", 
        "mount": "/home", 
        "options": "rw", 
        "size_available": 367142432768, 
        "size_total": 1897002360832, 
        "uuid": "1e803f4c-f551-4e7b-9c2e-021b539fbf75"
    }
}
```

**Comment by Yannig** [comment]
Check that there's more than 1 % of space available:

``` yaml
    - set_fact: size_available_pc="{{mount1.size_available|int / mount1.size_total|int * 100}}"
    - name: "check 1% of free space available for first file"
      assert:
        that: size_available_pc > 1
      ignore_errors: yes
```

Result in following output:

``` yaml
TASK [set_fact size_available_pc={{mount1.size_available|int / mount1.size_total|int * 100}}] ***
ok: [localhost]

TASK [check 1% of free space available for first file] *************************
ok: [localhost]
```

Check that there's more than 1K available:

``` yaml
    - name: "check 1K available for second file"
      assert:
        that: mount2.size_available > 1024
      ignore_errors: yes
```

Expected result:

``` yaml
TASK [check 1K available for second file] **************************************
ok: [localhost]
```

**Comment by Yannig** [comment]
Wondering if there's a way to retrieve the variable **ansible_mounts** variable without specifying it at each call.

Actually, the filter work this way:

``` yaml
- set_fact: mount1="{{file1|getmountfrompath(ansible_mounts)}}"
```

But I think the following should be better:

``` yaml
# Using ansible_mounts as default hash map
- set_fact: mount1="{{file1|getmountfrompath}}"
```

Anyone have an idea ?

**Comment by trinitronx** [comment]
I think this looks useful and would be great to have for a problem I'm working on now!  Seems it won't make it into the Ansible version I'm currently stuck on, but I have found the need to find a way to get space used for a given mountpoint, and to translate from human readable (e.g.: `GB`, `KB`, etc..) into bytes.

I had to settle for something like this:

```
{# Force vars to have global scope #}
{% set root_fs_max_limit = 0 -%}
{% set root_fs_size_used = 0 -%}
{% for item in ansible_mounts -%}
{% if item.mount == '/' -%}
{% set root_fs_max_limit = item.size_total -%}
{% set root_fs_size_used = item.size_total - item.size_available -%}
# Root disk:
#   size_available: {{ item.size_available }}
#   size_total:     {{ item.size_total }}
#   size_used:      {{ item.size_total - item.size_available }}
{% endif -%}
{% endfor -%}

{% if journald_system_max_use | search("K$") -%}
{% set journald_system_max_use_bytes = journald_system_max_use * (1024 ** 1) -%}
{% elif journald_system_max_use | search("M$") -%}
{% set journald_system_max_use_bytes = journald_system_max_use * (1024 ** 2) -%}
{% elif journald_system_max_use | search("G$") -%}
{% set journald_system_max_use_bytes = journald_system_max_use * (1024 ** 3) -%}
{% elif journald_system_max_use | search("T$") -%}
{% set journald_system_max_use_bytes = journald_system_max_use * (1024 ** 4) -%}
{% elif journald_system_max_use | search("P$") -%}
{% set journald_system_max_use_bytes = journald_system_max_use * (1024 ** 5) -%}
{% elif journald_system_max_use | search("E$") -%}
{% set journald_system_max_use_bytes = journald_system_max_use * (1024 ** 6) -%}
{% endif -%}
```

**Comment by Yannig** [comment]
@trinitronx I have already submited a filter to do this. You can check it here: https://github.com/ansible/ansible/pull/12074

It works this way:

``` yaml
ansible -m debug -a "msg={{'2M'|human_bytes}}" localhost
localhost | SUCCESS => {
    "changed": false, 
    "msg": "2097152"
}
```

@bcoca: what do you think about ? maybe on next version ?

**Comment by Yannig** [comment]
@trinitronx You can also use this filters using custom filters. To do this, drop the following content into **/etc/ansible/filters/custom-filters.py** (for example):

``` python
# -*- coding: utf-8 -*-
# Filtres divers en attente d'incorporation dans Ansible

from __future__ import absolute_import
from ansible import errors

import re

size_ranges = (
    (1<<80, 'Y'),
    (1<<70, 'Z'),
    (1<<60, 'E'),
    (1<<50, 'P'),
    (1<<40, 'T'),
    (1<<30, 'G'),
    (1<<20, 'M'),
    (1<<10, 'K'),
    (1, '')
)

def human_bytes(size):
    ''' Look for a size '''
    m = re.search('^\s*(\d*\.?\d*)\s*([A-Z])?', size, flags=re.IGNORECASE)
    if m is None:
        raise errors.AnsibleFilterError("human_bytes() can't interpret following string: %s" % str(size))
    try:
        num = float(m.group(1))
    except:
        raise errors.AnsibleFilterError("human_bytes() can't interpret following number: %s (original input string: %s)" % (m.group(1), size))

    unit = m.group(2)
    if unit is None:
        ''' No unit given, returning raw number '''
        return int(round(num))

    unit = unit[0].upper()

    for limit, suffix in size_ranges:
        if unit == suffix:
            break
    if unit != 'B' and limit == 1:
        raise errors.AnsibleFilterError("human_bytes() can't interpret following string: %s" % size)
    return int(round(num * limit))

def getmountfrompath(path, mounts):
    '''return the closest corresponding mount for a given path'''
    current_string_length = 0
    current_mount = None
    for mount in mounts:
        if mount['mount'].startswith('/'):
            if current_string_length < len(mount['mount']) and path.startswith(mount['mount']):
                current_string_length = len(mount['mount'])
                current_mount = mount
    return current_mount

class FilterModule(object):
    ''' On renvoie tout ça dans un objet filtre '''

    def filters(self):
        return {
            'human_bytes':      human_bytes,
            'getmountfrompath': getmountfrompath,
        }
```

Then, modify the following line into **/etc/ansible/ansible.cfg**:

``` ìni
filter_plugins     = /usr/share/ansible_plugins/filter_plugins:/etc/ansible/filters
```

You will be able to use **getmountfrompath** and a new **human_bytes** filters.

Have a nice day !

**Comment by amenonsen** [comment]
I think this would be a nice thing to have, especially if you didn't need to specify `ansible_mounts` each time.

**Comment by Yannig** [comment]
@amenonsen Agreed :)

**Comment by calfonso** [comment]
@Yannig are you interested in rebasing this PR?
needs_info

**Comment by alikins** [comment]
Too special case for filters/core.py. Looks like a good candidate for a custom filter plugin but not for filters/core.py

**Comment by Yannig** [comment]
@calfonso I fine for rebasing this but where do I put this if not in filters/core.py?

**Comment by jctanner** [comment]
@Yannig maybe just something like lib/ansible/plugins/filters/filesystem.py

**Comment by Yannig** [comment]
@jctanner thanks for your feedback. I keep you in touch

**Comment by mattclay** [comment]
The integration tests for this filter should be in the filters test target:

https://github.com/ansible/ansible/blob/devel/test/integration/targets/filters/tasks/main.yml

**Pull request closed without merging**
