### PR TITLE
os_ironic: fix broken import

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
Fix [broken import](https://github.com/ansible/community/wiki/Testing%3A-progress-tracker#fixing-broken-imports) in os_ironic module

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
os_ironic

##### ANSIBLE VERSION

```
ansible-playbook 2.4.0 (devel 7bc85f9b44) last updated 2017/07/14 11:19:12 (GMT +200)
```

### CODE REVIEW

**Review by s-hertel — APPROVED** [review]

**Review by juliakreger — APPROVED** [review]
Looks good to me

**Comment by pilou-** [comment]
This pull-request is labeled `community_review`, hence automerge is available. An automatic merge will be performed if two comments containing `shipit` (or `LGTM` or `+1`) are made by module maintainers, namespace maintainers or core team members.

@s-hertel @juliakreger could you add a `shipit` comment :) ?

**Comment by mscherer** [comment]
shipit

**Comment by s-hertel** [comment]
shipit

**Pull request merged**
