### PR TITLE
Add Description parameter in os_user

### LINKED ISSUE #18914: Openstack/os_user missing description parameter
_From @peerster on October 7, 2016 7:17_

##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

os_user.py
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When creating users in Openstack it's possible to enter a description for the user.
The module `os_user` is missing this option.
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

_Copied from original issue: ansible/ansible-modules-core#5182_

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes #18914

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/openstack/os_user.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Review by Shrews — CHANGES_REQUESTED** [review]
The 'description' field was not available until shade version 1.13.0. Could you please add a check for that?

**Comment by Akasurde** [comment]
@Shrews Sure. I will add check for that.

**Comment by Akasurde** [comment]
@Shrews Could you please take a look into update?

**Review by Shrews — CHANGES_REQUESTED** [review]
Rather than silently discarding the description, we should do what the other modules do if an unsupported parameter is supplied and exit. See the os_subnet module for an example:

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_subnet.py#L299-L302

**Comment by Akasurde** [comment]
Closing and re-opening for shippable.

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Thingee** [comment]
Hi @Akasurde, looks like there is still a request from @Shrews. Can you please address that first, thanks.

**Comment by Akasurde** [comment]
@Thingee I have implemented @Shrews's request [here](https://github.com/ansible/ansible/pull/25124/files#diff-65da81dd477171fbd396bbc611424767R228)

**Review by Shrews — APPROVED** [review]

**Comment by Shrews** [comment]
shipit

**Comment by Akasurde** [comment]
@Shrews @Thingee @bcoca Thanks.

**Pull request merged**
