### PR TITLE
Enable YAML data as playbook, and ensure that modules use #!/usr/bin/env python as hashbang

### PR DESCRIPTION
**Pull request by ed-at-work**
This is really two things rolled into a single pull request so feel free to reject it on that basis alone.

The first thing is allowing YAML data to be passed into playbook.Playbook() in addition to a file name.  this is handy for us in the tool we are building, it saves us, I think, from having to go all the way down to the Runner API to run play books programmatically.

The second thing is something that was discovered while trying to run Ansible inside a python Virtual Env-- the  use of   hardcoded /usr/bin/python path in the hash bang of module files was causing problems with some modules that rely on third-party libs (in our case it was boto-- installed in venv,  but not system-wide).

### CODE REVIEW

**Comment by sivel** [comment]
You definitely should not be updating all the modules interpreter lines like this.  It actually breaks the ability to use ansible_python_interpreter in your inventory files.

To solve that part of your issue, you should be declaring localhost with ansible_python_interpreter, similar to what is described at http://docs.ansible.com/guide_rax.html#running-from-a-python-virtual-environment-optional)

Or, if you are using Ansible 1.5 (devel), localhost is now implicit and does not require an explicit declaration.  Along with that implicit change, ansible_python_interpreter for localhost is automatically set to the python binary used to invoke ansible (sys.executable).

Also see http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

**Comment by mpdehaan** [comment]
Closing per the above, thank you @sivel for sharing the explanation.

**Comment by ed-at-work** [comment]
Thanks, forgot about that!

**Comment by ed-at-work** [comment]
I think I must be doing something weird, since I can't seem to actually use the implicit feature-- it doesn't work in my environment.  I need to do some more digging.

**Pull request closed without merging**
