### PR TITLE
[stable-2.17] debconf: set empty password value

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Fixes: #83214

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
(cherry picked from commit 79e8c4c26c85f39101dad71ae4ecf468f939583b)

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by pasnox** [comment]
Can somebody please merge this PR?
2.18 is not yet released, and everything before is broken, no debconf is just no more usable currently :(

**Comment by nitzmahone** [comment]
We usually merge PRs right before we cut RCs/releases, which is today.

**Pull request merged**
