### PR TITLE
Use context manager for mssql and postgresql modules.

### PR DESCRIPTION
**Pull request by atombrella**
##### SUMMARY
Something that wasn't included in #63840 It should be quite safe, i.e., no semantic changes.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
database, mssql, postfix, system, core.

##### ADDITIONAL INFORMATION
There are some things in the postgresql module that are less trivial to change. I'll do them in a future PR.

### CODE REVIEW

**Comment by sebasmannem** [comment]
shipit

**Review by Andersson007 — APPROVED** [review]
LGTM shipit

**Comment by Andersson007** [comment]
@atombrella thanks for the contribution!
@sebasmannem thanks for reviewing!

**Review by tcraxs — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
thanks all!

**Pull request merged**
