### PR TITLE
Fix Issue #49612

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Fix Issue #49612

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/network/onyx/onyx_mlag_vip.py
test/units/modules/network/onyx/test_onyx_mlag_vip.py

##### ADDITIONAL INFORMATION

```
ansible 2.8.0.dev0 (issue/49612 06e7eea8e8) last updated 2018/12/18 09:32:01 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev8/lib/ansible
  executable location = /.autodirect/mtrswgwork/anasb/ansible_dev8/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

### CODE REVIEW

**Comment by anasbadaha** [comment]
Hi @samerd ,

Please review this bug fix and let me know if you have farther comments.

**Review by samerd — CHANGES_REQUESTED** [review]
`
if req_ip is not None:
    if req_group is None:
           #print error group name is required when ip is given
`

**Comment by anasbadaha** [comment]
@samerd Please approve this PR

**Review by samerd — COMMENTED** [review]
`                self._module.fail_json(msg='Inorder to configure Mlag-Vip you must send '
                                           'group name param beside IPaddress')`
please change Inorder to In order

**Comment by anasbadaha** [comment]
@samerd Done Please approve!

**Review by samerd — APPROVED** [review]
Thanks Anas,
Well Done

**Comment by anasbadaha** [comment]
Hi @ganeshrn @samerd has approved this PR as well please merge it

**Review by ganeshrn — APPROVED** [review]
Thank you!

**Pull request merged**
