### PR TITLE
zabbix_api_host module added

### PR DESCRIPTION
**Pull request by fizban79**
Module for Zabbix hosts manipulation using its API.

### CODE REVIEW

**Comment by resmo** [comment]
Hi, good job!

I made a PR https://github.com/ansible/ansible/pull/8854 for a zabbix_host as well but, yours looks actually more complete. A would like to make some minor improve suggestions, let me know what you think.
1. call this module just zabbix_host
2. could you implement a environtment variable for not always have to write the username and password in every task, just like in my module https://github.com/ansible/ansible/pull/8854/files#diff-8607ec7a6ac554f96dfd3257b9846962R229
3. your host just has the agent interface added only https://github.com/fizban79/ansible/commit/86aab101c31ad2bc17f33b51fd92b0d2146dcff6#diff-1d4cff030c97f4fbd7e137f98fb04363R316, I thougt about to implement a "choice" for specify which interface you want to add [ agent, snmp, ipmi, jmx]. What do you think? and that is why I would rename the `agent_port` option to `port` 
4. I would default the IP address to `127.0.0.1`, `0.0.0.0` is not very useful.

Yours
René

**Comment by srgvg** [comment]
So we have 3 PR's for zabbix host, see also #6034 
This one also has possiility to add different interfaces, a functionality that I use.

**Comment by fizban79** [comment]
Hi, René! 

Thank you for feedback! 
You suggestions looks reasonable, i'll implement them soon.

**Comment by fizban79** [comment]
Hello, Serge! 

I've planned to implement that functionality later. But if it's necessary, I'll try to do it as soon as possible.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
