### PR TITLE
adds atomiadns module

### PR DESCRIPTION
**Pull request by sejo**
This module allows one to configure his atomiadns servers with ansible.

Signed-off-by: Jochen Maes jochen@sejo-it.be

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ok this is interesting.

I have a  few style and usage things:

So in Ansible modules and arguments, variables should be with_underscores and not CamelCase.

This should be applied to the command options as well, but arguments like nameservergroup should be name_server_group, etc on the Ansible module as well.

This module itself should be atomia_dns (so rename module and module names in the DOC yaml)

It looks like changed detection always reports 'changed' even when a change is not made.  This needs to be fixed prior to submission and can use the "get" parts of the API to do that.

 Rather than having "commands"  it seems we would want things to look more like resources

atomia_dns: type=nameserver state=present
atomia_dns: type=zone name=blarg state=absent
etc

and that might get things a little bit more like the other modules in terms of signature, versus something command based.

Do you think this would be possible?  Thanks!

**Comment by mpdehaan** [comment]
Any updates on this one?

**Comment by sejo** [comment]
Michael,

You can close it for now, sorry. I'm working on the new one with your suggestions included but due to limited free time, it might take a bit. Sorry about that.

Jochen

----- Original Message -----

> From: "Michael DeHaan" notifications@github.com
> To: "ansible/ansible" ansible@noreply.github.com
> Cc: "Jochen Maes" jochen@sejo-it.be
> Sent: Tuesday, August 6, 2013 10:14:12 PM
> Subject: Re: [ansible] adds atomiadns module (#3679)
> 
> Any updates on this one?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ansible/ansible/pull/3679#issuecomment-22207608

## 

SeJo IT BVBA
Lange Akker  23
9240  Zele
http://sejo-it.be/
http://be.linkedin.com/in/maesjoch/
+32 474 04 38  19
"ne humanus crede"

**Comment by jimi-c** [comment]
Going ahead and closing per the above. Thanks!

**Pull request closed without merging**
