### PR TITLE
filesystem.py: Fix xfs growfs

### LINKED ISSUE #33979: resizefs option in filesystem module fails with xfsprogs-4.12 (fedora 27 atomic)
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
filesystem (resizefs, xfs)

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /Users/asdf/ansible/ansible.cfg
  configured module search path = [u'/Users/asdf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
DEFAULT_PRIVATE_KEY_FILE(/Users/asdf/ansible/ansible.cfg) = /Users/jonpad/git/adsf/ansible/roles/asdf/private_keys/asdf.rsa

##### OS / ENVIRONMENT
management: Mac OS 10.12.6 (management)
Fedora 27 (Atomic Host)

##### SUMMARY
The resizefs functionality for xfs in the filesystem module worked fine on Fedora 26 (Atomic Host), is broken in Fedora 27 (Atomic Host), probably because of this change https://bugzilla.redhat.com/show_bug.cgi?id=1477192

Basically, xfs_info was deliberately changed to only work on the mount points of mounted partitions, not device names. The filesystem module expects device names as arguments, and xfs_growfs now fails with a device name.

##### STEPS TO REPRODUCE
```yaml
---

- name: Enlarge the root partition
  lvol:
    vg: fedora-atomic
    lv: root
    size: 5G

- name: Grow the root filesystem
  filesystem:
    fstype: xfs
    dev: /dev/mapper/fedora--atomic-root
    resizefs: yes
```

##### EXPECTED RESULTS
Command completes with OK.

##### ACTUAL RESULTS
```
fatal: [atomic01]: FAILED! => {"changed": false, "err": "xfs_growfs: /dev/mapper/fedora--atomic-root is not a mounted XFS filesystem\n", "failed": true, "msg": "Failed to get block count and block size of /dev/mapper/fedora--atomic-root with /usr/sbin/xfs_growfs", "rc": 1}
```

### PR DESCRIPTION
**Pull request by alxgu**
xfs needs to be mounted to be expanted.

Add function to get mountpoint of filesystem. Use this mountpoint for xfs growing.

##### SUMMARY

xfs growfs needs to be executed on a mountpoint. That will be enforced now by xfsprogs-4.12.
https://bugzilla.redhat.com/show_bug.cgi?id=1477192

Fixes #33979
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

filesystem.py

##### ADDITIONAL INFORMATION

before:
```
server1| FAILED! => {
    "changed": false,
    "cmd": "/usr/sbin/xfs_growfs -n /dev/vg00/work.tmp",
    "msg": "xfs_growfs: /dev/vg00/work.tmp is not a mounted XFS filesystem",
    "rc": 1,
    "stderr": "xfs_growfs: /dev/vg00/work.tmp is not a mounted XFS filesystem\n",
    "stderr_lines": [
        "xfs_growfs: /dev/vg00/work.tmp is not a mounted XFS filesystem"
    ],
    "stdout": "",
    "stdout_lines": []
}
```
after:
```
server1| SUCCESS => {
    "changed": false,
    "msg": "XFS filesystem is using the whole device /dev/vg00/work.tmp"
}
```
or
```
server1| SUCCESS => {
    "changed": true,
    "msg": "meta-data=/dev/mapper/vg00-work.tmp isize=512    agcount=4, agsize=32768 blks\n         =                       sectsz=512   attr=2, projid32bit=1\n         =                       crc=1        finobt=1 spinodes=0 rmapbt=0\n         =                       reflink=0\ndata     =                       bsize=4096   blocks=131072, imaxpct=25\n         =                       sunit=0      swidth=0 blks\nnaming   =version 2              bsize=4096   ascii-ci=0 ftype=1\nlog      =internal               bsize=4096   blocks=855, version=2\n         =                       sectsz=512   sunit=0 blks, lazy-count=1\nrealtime =none                   extsz=4096   blocks=0, rtextents=0\ndata blocks changed from 131072 to 134144\n"
}

```

### CODE REVIEW

**Comment by pilou-** [comment]
This error occurs when there isn't any mountpoint:
```
fatal: [testhost]: FAILED! => {"changed": false, "cmd": "/usr/sbin/xfs_growfs -n None", "msg": "xfs_growfs: path resolution failed for None: No such file or directory", "rc": 1, "stderr": "xfs_growfs: path resolution failed for None: No such file or directory\n", "stderr_lines": ["xfs_growfs: path resolution failed for None: No such file or directory"], "stdout": "", "stdout_lines": []}
```

`/usr/sbin/xfs_growfs -n None` must not be executed, an error must be raised earlier.

**Comment by alxgu** [comment]
@pilou- fixed
`srv1| FAILED! => {
    "changed": false,
    "msg": "/dev/vg00/work.tmp needs to be mounted for xfs operations"
}
`

**Comment by alxgu** [comment]
@trammel Could you test the PR?

**Comment by alxgu** [comment]
shipit

**Comment by alxgu** [comment]
shipit

**Comment by alessiofachechi** [comment]
Any news about this PR guys? Actually needed.

**Comment by kbrowder** [comment]
Any news?  Seems like this can't really make things worse right (currently resizefs doesn't work with xfs)?

**Comment by larsbu** [comment]
shipit

**Comment by alxgu** [comment]
https://github.com/ansible-collections/community.general/pull/137

**Comment by gundalow** [comment]
Fix merged into `community.general` in https://github.com/ansible-collections/community.general/pull/137#issuecomment-648133700

A backport for `stable-2.9` maybe created, checkout the above URL to see if that happens.

**Pull request closed without merging**
