### PR TITLE
vmware_guest: Small code cosmetic changes and documentation updates

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Bug fix pull request
 - Docs Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.3

##### SUMMARY

After merging the latest update, these were the few remaining differences with upstream.

(Plus the previous proposed fast match based on unique VM name which is not longer needed)

### CODE REVIEW

**Comment by dagwieers** [comment]
@nerzhul @aperigault This should be a no-brainer.

**Comment by nerzhul** [comment]
why do you removed required: False ?

**Comment by dagwieers** [comment]
Because that is the implied value. It has become redundant.
You only need to add `required: True` if it is required.
Same for aliases, if there are none, you don't have to add an empty list, etc...

**Comment by nerzhul** [comment]
shipit

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Review by nerzhul — APPROVED** [review]
shipit

**Comment by nerzhul** [comment]
bot_status

**Comment by aperigault** [comment]
shipit

**Comment by jctanner** [comment]
bot_status

**Comment by nerzhul** [comment]
shipit

**Comment by jctanner** [comment]
shipit

**Comment by dagwieers** [comment]
shipit

**Comment by jctanner** [comment]
Thanks @dagwieers

**Pull request merged**
