### PR TITLE
add support for disk_config option to cloud/rax module

### PR DESCRIPTION
**Pull request by pkit**
Just ads the ability to choose between "manual" and "auto" partitioning mode for a new server.

### CODE REVIEW

**Comment by pkit** [comment]
Hi James,
Let's just fix the Rackspace plugins, the "disk_config" or "identity_type" are new options, if we want Ansible to really support Rackspace APIs, both should be fixed.

**Comment by willkelly** [comment]
+1

**Comment by mpdehaan** [comment]
This is now merged.

Sincere apologies on the delay with the backlog!

**Comment by mpdehaan** [comment]
System seems to think this wasn't merged, but it's there, and I can see it.  Closing manually!

**Pull request closed without merging**
