### PR TITLE
documentation fix availability_zones should be required for ec2_asg

### PR DESCRIPTION
**Pull request by budlight**

### CODE REVIEW

**Comment by budlight** [comment]
Right now this attribute is required, but it might be desired to actually fix the module so that it isn't required.

**Comment by jimi-c** [comment]
The params list does not show this as being required, does it throw an error if it is not set?

**Comment by budlight** [comment]
yes it does

**Comment by jimi-c** [comment]
Ok, then go ahead and modify the param definition as well, and I'll get this merged in. Thanks!

**Comment by budlight** [comment]
It appears this is technically correct in that availability_zones OR vpc_zone_identifier is required in the boto api.  I still think that if both a vpc and availability_zones aren't set it should pass a list of all the availability_zones for that region, this is kinda messy as you have to create another boto connection object.

I'm personally not aware of how the test setup on this project works, so I haven't ran or modified the test suite at all. 

 If this pasts the existing tests it should be ready to merge.

**Comment by mpdehaan** [comment]
@jimi-c noticed this contains a code change and not just a docs update, so I'm retagging this one.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
