### PR TITLE
module_utils/f5_utils: PEP8 compliancy

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
- Make PEP8 compliant

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

module_utils/f5_utils

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by dagwieers** [comment]
Shippable issue, close and re-open.

**Comment by mattclay** [comment]
I'm not sure why Shippable is having trouble with this PR. It seems to be having issues getting the PR from GH. I suggest making a change to the commit message and force pushing to see if that fixes things.

**Comment by caphrim007** [comment]
shipit

**Comment by gundalow** [comment]
Please rebase and I'll merge

**Review by gundalow — APPROVED** [review]

**Comment by dagwieers** [comment]
Superseded by #25177

**Pull request closed without merging**
