### PR TITLE
ignore netapp tests when no libs

### PR DESCRIPTION
**Pull request by bcoca**
cc @carchi8py @gundalow 

unit tests should not require users to have all possible libs installed locally

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

tests

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Review by lonico — APPROVED** [review]

**Review by carchi8py — APPROVED** [review]
We will make similar changes to our existing unit test that we are planning to push out in the next week or so.

**Comment by abadger** [comment]
Here's the three ways to skip tests using pytest.  use the one that works the best for this code:

https://gist.github.com/abadger/280853f4ef211fe857270f9b1c8aaf41

**Comment by abadger** [comment]
Looks good now.  +1 to merge.

**Comment by abadger** [comment]
@bcoca interestingly, when I went to port other unittests to this, it appeared to fail (I'm guessing because this one isn't skipped inside of CI and the ones I ported are).

It looks like this syntax isn't supported in pytest >= 3.0.

Looks like we need to use this form now:
```
if not netapp_utils.has_netapp_lib():
    pytestmark = pytest.mark.skip("skipping as missing required netapp_lib")
```

**Comment by abadger** [comment]
I've used the new syntax in: https://github.com/ansible/ansible/pull/48960  so that shold work for us.

**Review by lonico — APPROVED** [review]

**Pull request merged**
