### PR TITLE
openssl_csr: fix idempotency problems

### LINKED ISSUE #55139: openssl_csr fails on second invocation: 'Extension' object has no attribute 'ca'
##### SUMMARY
openssl_csr fails on its second invocation when having defined the basic constraint `CA:TRUE`. The error is `_check_basicConstraints\nAttributeError: 'Extension' object has no attribute 'ca'`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_csr

##### ANSIBLE VERSION

Note: updated to the latest on `devel` as of today

```paste below
ansible 2.8.0a1.post0
  config file = /ansible/playbooks/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 23:40:30) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```paste below
DEFAULT_HOST_LIST(/ansible/playbooks/ansible.cfg) = ['/ansible/playbooks/inventories/myenv/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/ansible/playbooks/ansible.cfg) = /root/.vault_pass.txt
```

##### OS / ENVIRONMENT
Docker container on Linux

##### STEPS TO REPRODUCE

Run the following playbook twice.

```yaml
- hosts: localhost
  tasks:
    - name: "Generate root CA private key"
      openssl_privatekey:
        path: ca-key.pem
    - openssl_csr:
        path: ca.csr
        privatekey_path: ca-key.pem
        common_name: My CA
        basic_constraints:
          - CA:TRUE
        basic_constraints_critical: yes
        key_usage:
          - keyCertSign
          - digitalSignature
        key_usage_critical: yes
```

##### EXPECTED RESULTS

On the second invocation, the `openssl_csr` task should not fail.

##### ACTUAL RESULTS

First invocation:

```paste below
root@test:/ansible/playbooks# ansible-playbook reproduce.yml

PLAY [localhost] *************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************
ok: [localhost]

TASK [Generate root CA private key] ******************************************************************************************************************************
changed: [localhost]

TASK [openssl_csr] ***********************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Second invocation:

```
root@test:/ansible/playbooks# ansible-playbook reproduce.yml

PLAY [localhost] *************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************
ok: [localhost]

TASK [Generate root CA private key] ******************************************************************************************************************************
ok: [localhost]

TASK [openssl_csr] ***********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/root/.ansible/tmp/ansible-tmp-1554976577.3779902-7265526702622/AnsiballZ_openssl_csr.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1554976577.3779902-7265526702622/AnsiballZ_openssl_csr.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1554976577.3779902-7265526702622/AnsiballZ_openssl_csr.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1554976577.3779902-7265526702622/AnsiballZ_openssl_csr.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/local/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/local/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_openssl_csr_payload_agiegmf7/__main__.py\", line 924, in <module>\n  File \"/tmp/ansible_openssl_csr_payload_agiegmf7/__main__.py\", line 907, in main\n  File \"/tmp/ansible_openssl_csr_payload_agiegmf7/__main__.py\", line 441, in generate\n  File \"/tmp/ansible_openssl_csr_payload_agiegmf7/__main__.py\", line 469, in check\n  File \"/tmp/ansible_openssl_csr_payload_agiegmf7/__main__.py\", line 826, in _check_csr\n  File \"/tmp/ansible_openssl_csr_payload_agiegmf7/__main__.py\", line 803, in _check_extensions\n  File \"/tmp/ansible_openssl_csr_payload_agiegmf7/__main__.py\", line 764, in _check_basicConstraints\nAttributeError: 'Extension' object has no attribute 'ca'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes two bugs:
 1. in the pyOpenSSL backend, no normalization was done for SANs while checking idempotency (mainly a problem for IPv6 addresses);
 2. in the cryptography backend, idempotency checking of basic constraints didn't work (fixes #55139).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssl_csr

### CODE REVIEW

**Comment by felixfontein** [comment]
Meh. I'll investigate these test failures later/tomorrow.

**Comment by felixfontein** [comment]
Ok, got it. Was looking at the wrong lines...

ready_for_review

**Comment by felixfontein** [comment]
Added changelog, since `stable-2.8` has been branched and backporting to `stable-2.8` needs one.

**Review by resmo — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@resmo thanks for reviewing!
@mkrizek thanks for merging!

**Comment by felixfontein** [comment]
Created backport to stable-2.8 (#55279); no backport to stable-2.7 needed since this covers 2.8-specific changes.

**Pull request merged**
