### PR TITLE
Add support for bare git repos

### PR DESCRIPTION
**Pull request by cg-soft**
This adds a "bare" boolean parameter to the git module to create bare repos. I tested this in our own setup, but I'm not completely happy with it, mostly because I'm not sure I like the way the before/after stuff is done, and I'm also worried about the fetch refspecs for bare repos.

Consider this a discussion item. I do need bare git repo support for our environment, and we have a hacky solution in place now, but it would be great if we can have it out of the box.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ok, I may need some education here.

What's this used for?

"A "bare" repo, as the git glossary says, is a repository that does not contain a "working tree" at all. It doesn't contain the special .git sub-directory either; instead, it contains all the contents of the .git subdirectory right in the main directory itself."

I guess I'm looking to understand the underlying use case in a production deployment case to decide whether this makes sense as an option, but am completely unfamiliar with the need for this.

Help me understand perhaps?

Thanks!

**Comment by resmo** [comment]
imho, why not...

Not a every day use case, but It could be handy if you would like to sync bare repos or clone from a bare repo to a private git server (so also bare there).

**Comment by cg-soft** [comment]
We use bare repos for three purposes:
- Central repos ala "github", i.e. places where folks push into and pull from, but never edit. This saves the space taken by the workspace.
- Reference repos used by our build slaves - which is the main reason I need them, since we use ansible to manage our build farm. See also <tt>--reference</tt> in https://www.kernel.org/pub/software/scm/git/docs/git-clone.html. We may wish to expose this flag in the git modules also, even though in my case I don't need it as jenkins will do the cloning.
- Temporary repos for various data gathering or interfacing with other tools. For example, Jira uses them to crossreference git commits with the issues referenced in those commits.

**Comment by cg-soft** [comment]
It's failing the git test. It might be related to the changes I made to test whether the repo is up to date. I'll go and debug and resubmit.

<pre>
test_git (TestRunner.TestRunner) ... ERROR
</pre>

**Comment by cg-soft** [comment]
Hmmm... I fixed the bug, but I'm getting messed up via unicode hashes, like so:

<pre>
Traceback (most recent call last):
  File "/Users/christian.goetze/git/ansible/test/TestRunner.py", line 189, in test_git
    assert result['changed']
KeyError: 'changed'
-------------------- &gt;&gt; begin captured stdout &lt;&lt; ---------------------
{'invocation': {'module_name': 'git', 'module_args': 'repo="file:///tmp/gitdemo" dest=/tmp/gd'}, u'changed': True, u'after': u'821a428f12517333ad3254f3f7766b7589f273fc', u'before': None}
</pre>

Anyone encounter this?

**Comment by cg-soft** [comment]
I rebased and fixed a bunch of little things that cropped up... Now I don't appear to be able to make a new pull request...

**Comment by mpdehaan** [comment]
Closing this as a duplicate of https://github.com/ansible/ansible/pull/4570

**Pull request closed without merging**
