### PR TITLE
Remove Sphinx/Read-the-Docs plug on every doc page

### LINKED ISSUE #37021: Getting rid of Sphinx and Read-the-Docs in documentation
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
docs

##### ANSIBLE VERSION
v2.5

##### SUMMARY
Currently every documentation page has the following text in the footer:

> Ansible docs are generated from [GitHub sources](https://github.com/ansible/ansible) using [Sphinx](http://sphinx-doc.org/) using a theme provided by [Read the Docs](http://readthedocs.org).

And I don't see the relevancy of having this on every single documentation page. It's like printing on every page in a book that the book was made with e.g. LaTeX, but worse, because it includes 3 links which decreases the value of the other information in that page.

If this has any relevancy, then maybe the documentation needs an **About** section, and otherwise I would get rid of it altogether.

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
No need to have this on every page.

This fixes #37021

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docsite

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Review by dharmabumstead — APPROVED** [review]
We should leave the RTD credit in, actually...although the somewhat awkward wording needed a fix.

**Comment by dagwieers** [comment]
So explain to me why it is relevant to have:

- A link to the main Github repository
- A link to Sphinx
- A link to the Read-the-Docs "theme"

on every single page in the documentation ? See #37021

**Comment by bcoca** [comment]
I'm for removing the links, or better yet, relegating to 'about section'. People get confused and think we are hosting at RTD or they think the existing 'ansible' entry at that site is maintained buy us.

**Comment by gundalow** [comment]
What Bcoca said.

**Comment by dharmabumstead** [comment]
I am double checking the RTD license to make sure we aren't obligated to have that on every page. If not (and I suspect not, since we've modified it heavily and are using them for hosting), I don't have a problem with removing it.

**Comment by dharmabumstead** [comment]
Looks like we're OK remove. I'll be adding a colophon page to the core docs with this and other build-related issue (https://github.com/ansible/ansible/issues/37047).

**Review by dharmabumstead — APPROVED** [review]

**Comment by dharmabumstead** [comment]
Merged. Thanks @dagwieers!

**Pull request merged**
