### PR TITLE
mysql_db: add skip_lock_tables option

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
mysql_db: add skip_lock_tables option

Fixes: https://github.com/ansible/ansible/pull/33145

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/mysql/mysql_db.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by kurtdavis — APPROVED** [review]

**Review by bmalynovytch — APPROVED** [review]
LGTM
shipit

**Review by felixfontein — APPROVED** [review]

**Comment by Andersson007** [comment]
thank you guys all for reviewing and merging!

**Comment by apapsch** [comment]
As commented in a similar PR #65773:

Supporting the many options found in mysqldump results in a flurry of PRs all similar to this one, with little advantage for the module. It looks somewhat independent of mysqldump and adding many options breaks the abstraction. I propose, instead of adding many options in a trickle, just add an args argument that serves as the single loophole out of the abstraction. PR #66252 adds the args argument.

**Comment by felixfontein** [comment]
In general, having a generic argument such as `args` is not a good idea, due to idempotency checking made hard. For dumping it is probably OK though, since there is no real (sensible) idempotency checking possible anyway.

**Pull request merged**
