### PR TITLE
Add support for purging local outdated backup files

### PR DESCRIPTION
**Pull request by ksdpmx**
##### SUMMARY
Add support for purging local outdated backup files

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/basic.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by abadger** [comment]
Labelling needsinfo as it's a part of the review that will happen in the ansible-modules-core repo.  The PRs should be reviewed and merged together.

**Comment by ksdpmx** [comment]
## ISSUE TYPE

Feature Pull Request

## COMPONENT NAME

`module_utils/basic.py`

## SUMMARY

There are too many outdated backup files :/
Can be used by any backups named like `basename-YYYY-MM-DD@HH:MM:SS~`.

Block [this ansible/ansible-modules-core pr](https://github.com/ansible/ansible-modules-core/pull/2079).

**Comment by ksdpmx** [comment]
ready_for_review

**Comment by calfonso** [comment]
We are considering a better way to implement cleanup of backing up that makes it a little more flexible. We are going to close this since we are taking a different approach to solving the problem.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request closed without merging**
