### PR TITLE
Add yum cmd to install ansible

### PR DESCRIPTION
**Pull request by woernfl**
Add yum cmd to install ansible

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by woernfl** [comment]
+label docs_pull_request

**Review by daxlab — APPROVED** [review]

**Review by ryansb — APPROVED** [review]

**Comment by woernfl** [comment]
-label needs_rebase

**Comment by woernfl** [comment]
Hey @daxlab and @ryansb,

I rebased the branch some days ago. Is their some thing more I can do to help?

**Comment by dharmabumstead** [comment]
Closing this one. Feel free to rebase and reopen.

**Pull request closed without merging**
