### PR TITLE
Fix ansible_ssh_host after 339c05bb

### PR DESCRIPTION
**Pull request by dhozac**

### CODE REVIEW

**Comment by mpdehaan** [comment]
This isn't quite right, as the delegated host can set ansible_ssh_host (I KNOW!).  I'll look further and review things.

**Comment by dhozac** [comment]
Modified to actually do what was intended with the original commit.

**Comment by mpdehaan** [comment]
looks like this might not allow ansible_ssh_port if not delegating.  Working on it and looking...

**Comment by mpdehaan** [comment]
nm, looks good, thanks!   Testing to make sure...

**Comment by mpdehaan** [comment]
Ok, pushed it with some tweaks.   Closed up the width of the try/catch and possibly fixed some things in edge cases.  Anyway, check out latest and let me know what you think.  It's based on your commit + some changes on top.

Thanks!

**Pull request closed without merging**
