### PR TITLE
imc_xml: New module to manage Cisco IMC hardware

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This module provides direct access to the Cisco IMC API.
See the included examples for a glimpse of what it can do.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

imc_xml

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by dagwieers** [comment]
@gundalow After discussing with @privateip he told me to ask you to get this merged :-)

**Comment by gundalow** [comment]
Rebase and I'll merge & add you to the maintainers.

**Comment by dagwieers** [comment]
Yeah, the network is so bad now that I am not able to rebase :-(

**Comment by dagwieers** [comment]
@gundalow Go ahead now ! :-)

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Added you as a maintainer for the directory
`remote_management/imc/: dagwieers`

**Pull request merged**
