### PR TITLE
Remove pause logic form junos_netconf tests

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Replace pause with wait_for in junos_netconf tests

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
junos_netconf

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 63198e7670a3acf61ca9cb3969727afb30abcce7

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 8bbfcc3a99160b3348186a253f081f535e20106f

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Review by ganeshrn — APPROVED** [review]

**Pull request merged**
