### PR TITLE
cs_template: fix KeyError on state=extracted

### PR DESCRIPTION
**Pull request by resmo**
##### SUMMARY
Reported by @onitake : 

~~~yaml
- name: extract new templates
   cs_template:
     name: mytemplate
     state: extracted
~~~

produces:
~~~
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'isextractable'
fatal: [Linux-CentOS-6-64bit-20GB]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_cs_template_payload_8ya2tZ/__main__.py\", line 737, in <module>\n  File \"/tmp/ansible_cs_template_payload_8ya2tZ/__main__.py\", line 731, in main\n  File \"/tmp/ansible_cs_template_payload_8ya2tZ/__main__.py\", line 667, in get_result\nKeyError: 'isextractable'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
~~~

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

cs_template

##### ADDITIONAL INFORMATION

```paste below

```
needs backport to 2.7 but not 2.6

### CODE REVIEW

**Comment by resmo** [comment]
failed build unrelated, rebuild

**Comment by resmo** [comment]
ready_for_review

**Review by dpassante — APPROVED** [review]
shipit

**Comment by gundalow** [comment]
@resmo thank you for the fix
@dpassante thank you for the review.

If needed please raise a backport PR for 2.7

**Comment by resmo** [comment]
I am creating a backport for 2.7

**Comment by resmo** [comment]
backport PR for 2.7 #48742

**Pull request merged**
