### PR TITLE
Update faq.rst

### PR DESCRIPTION
**Pull request by jiteshprakashsinha**
Added link to https://access.redhat.com/solutions/5295121 in third sentence

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by bmillemathias — APPROVED** [review]

**Comment by acozine** [comment]
The solution listed in the access.redhat.com link is the same as the solution suggested in the next FAQ question ("Where did my specific module go?"). However, more information is better than less . ..

**Comment by Akasurde** [comment]
@acozine What do you want to do with this PR? let me know. Thanks.

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible/ansible/pull/73934


Thanks, @jiteshprakashsinha for the contribution.

**Pull request closed without merging**
