### PR TITLE
add executable parameter to gem module.

### PR DESCRIPTION
**Pull request by succhiello**
Just like npm module, add executable parameter for gem path (ex: /usr/lib64/fluent/ruby/bin/fluent-gem).

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you please add the "version_added: '1.4'" line in the docs under the new argument.

If you add this I can merge it.

Thanks!

**Comment by succhiello** [comment]
added!
I sent #4048 request, too.

Thanks!

**Comment by mpdehaan** [comment]
Already merged this feature in from another request (might have been yours), sorry about duplicate efforts (if not yours)!

Let me know if works for you, thanks!

**Comment by succhiello** [comment]
It works for me fine, thanks!

**Pull request closed without merging**
