### PR TITLE
Make nic_name as optional parameter

### LINKED ISSUE #25632: cloud/vmware/vmware_vswitch.py nic_name should be optional
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloud/vmware/vmware_vswitch.py

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
n/a
##### OS / ENVIRONMENT
n/a
##### SUMMARY
The vmware_vswitch module erroneously assumes that 'nic_name' is required.  It is valid (and sometimes desired) to make a vmware virtual switch that does not have any uplink nics at all - the use case is multiple isolated port-groups for isolated networking. 

After the vswitch is created, we create a port-group with VLAN 4095 (all vlans), with network policy permitting mac changes, forged transmit, and promiscuous all enabled.

In /ansible/modules/cloud/vmware/vmware_vswitch.py , we can omit this line if nic_name is not specified and the port-group is created as desired.

```python
if self.nic_name:
    vss_spec.bridge = vim.host.VirtualSwitch.BondBridge(nicDevice=[self.nic_name])
```

##### STEPS TO REPRODUCE

Run ansible-playbook against a task using the vmware_vswitch module, omitting nic_name.
```
    - name: add test_switch
      local_action:
        module: vmware_vswitch
        hostname: esxi_host
        username: esxi_username
        password: esxi_password
        switch_name: item
        mtu: 9000
        validate_certs: no
        number_of_ports: 8
        #nic_name: 'null'

```

##### EXPECTED RESULTS
I expect the vmware vswitch to be created, but without any uplink nics.

##### ACTUAL RESULTS
```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: nic_name"}
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix adds support for adding VMWare vSwitch without
any physical NICs (uplinks). This makes nic_name as
an optional parameter. Also, updated documentation and
examples to reflect these changes.

Fixes #25632

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_vswitch.py

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
YAML file
``` yaml
---
- name: Sample VMSwitch
  hosts: localhost
  tasks:
    - name: Add Sample VMSwitch
      vmware_vswitch:
        hostname: 192.168.122.68
        username: root
        password: esxi@123
        validate_certs: false
        switch_name: vmswitch_0006
```

After fix:

```
# ansible-playbook vmware_switch.yaml 

PLAY [Sample VMSwitch] *********************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Add Sample VMSwitch] *****************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```


Ad-hoc command
```
# ansible -m vmware_vswitch -a "hostname=192.168.122.68 username=root password=esxi@123 validate_certs=false nic_name= switch_name=vswitch_0007" localhost 
localhost | SUCCESS => {
    "changed": true
}
```

**Comment by jctanner** [comment]
waiting on user in #25632 to validate the fix.

@Akasurde are you interested in taking over maintenance on this module?

**Comment by Akasurde** [comment]
@jctanner Yes. sure, here is PR https://github.com/ansible/ansibullbot/pull/586

**Comment by Akasurde** [comment]
@jctanner Thanks for review.

**Pull request merged**
