### PR TITLE
Improve handling of RabbitMQ user tags

### LINKED ISSUE #50360: [rabbitmq_user] Allow tags to be a list of strings
##### SUMMARY
rabbitmq_user expects tags to a string of comma separated tags. We should be able to provide a list of strings also.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/modules/messaging/rabbitmq/rabbitmq_user.py

##### ADDITIONAL INFORMATION
Internally the string is split and converted into a list anyway. This would be useful, because the list of tags of users could be generated on the fly from the script.

```yaml
- rabbitmq_user:
    user: user1
    password: pass1
    tags: ["tag1","tag2"]
```

### PR DESCRIPTION
**Pull request by ptzianos**
- Improve documentation of rabbitmq_users tags field
- Change tags only when explicitly set
- Improve code that parses tag lists
- Add tests for user tag handling
- Allow tags to also be a list of strings

##### SUMMARY
Fixes: #50360, #50359 

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/messaging/rabbitmq/rabbitmq_user.py

##### ADDITIONAL INFORMATION

This is now possible:
```
- rabbitmq_user:
    user: user1
    password: pass1
    tags: ["tag1","tag2"]
```
These result in the tags of an existing user to be set to an empty list:
```
- rabbitmq_user:
    user: user1
    password: pass1
    tags: ""
- rabbitmq_user:
    user: user1
    password: pass1
    tags: []
```
This prevents the module from messing with the tags of an existing user:
```
- rabbitmq_user:
    user: user1
    password: pass1
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/102373/9/tests

**Comment by ptzianos** [comment]
@mattclay sorry for this, I found a tiny bug while testing on real system and I didn't update the tests accordingly. Now everything works. Rebased on latest `devel` branch also.

**Comment by ptzianos** [comment]
Rebased on latest devel

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.rabbitmq.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
