### PR TITLE
VMware: New module: vmware_portgroup_facts

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_portgroup_facts.py
test/integration/targets/vmware_portgroup_facts/aliases
test/integration/targets/vmware_portgroup_facts/tasks/main.yml

##### ANSIBLE VERSION

```
2.6devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
@pdellaert @tchernomax Could you please review this ?

**Review by pdellaert — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
rebuild_merge

**Comment by Akasurde** [comment]
@pdellaert Thanks for the review.

**Pull request merged**
