### PR TITLE
Add support for fetching Lifecycle Controller and System attributes

### PR DESCRIPTION
**Pull request by anupamaloke**
##### SUMMARY
Added support for fetching Lifecycle Controller and System attributes for iDRAC

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
idrac_redfish_info

##### ADDITIONAL INFORMATION

'GetManagerAttributes' should return all the manager attributes for PowerEdge servers. However, at present, 'GetManagerAttributes' command only returns the iDRAC attributes. LifecycleController and System attributes are not returned. This PR adds support for also returning the LC and system attributes.

###### _BEFORE THE CHANGE_
```paste below
ok: [192.168.1.1] => {
    "redfish_facts": {
        "entries": {
            "ADGroup.1.Domain": "",
            "ADGroup.1.Name": "",
            "ADGroup.1.Privilege": 0,
            ...<TRUNCATED FOR BREVITY>
        }
    }
}

```

###### _AFTER THE CHANGE_
```
ok: [192.168.1.1] => {
    "redfish_facts": {
        "entries": [
            {
                "Attributes": {
                    "ADGroup.1.Domain": "",
                    "ADGroup.1.Name": "",
                    "ADGroup.1.Privilege": 0,
                    ...<TRUNCATED FOR BREVITY>
                },
                "Id": "iDRACAttributes"
            },
            {
                "Attributes": {
                    "ServerTopology.1.AisleName": "",
                    "ServerTopology.1.DataCenterName": "",
                    "ServerTopology.1.RackName": "",
                    "ServerTopology.1.RackSlot": 1,
                    "ServerTopology.1.RoomName": "",
                    ...<TRUNCATED FOR BREVITY>
                },
                "Id": "SystemAttributes"
            },
            {
                "Attributes": {
                    "LCAttributes.1.AutoBackup": "Disabled",
                    "LCAttributes.1.AutoDiscovery": "Off",
                    "LCAttributes.1.AutoUpdate": "Disabled",
                    ...<TRUNCATED FOR BREVITY>
                },
                "Id": "LCAttributes"
            }
        ]
    }
}

```

### CODE REVIEW

**Comment by anupamaloke** [comment]
bot_status

**Review by billdodd — COMMENTED** [review]
Thanks for the PR! LGTM

shipit

**Comment by anupamaloke** [comment]
@billdodd, thanks a lot!
@mraineri, appreciate if you could also take a look at this PR.

**Comment by tomasg2012** [comment]
shipit

**Pull request merged**
