### PR TITLE
Add get_dmi_facts in setup for FreeBSD systems using dmidecode

### PR DESCRIPTION
**Pull request by dalevizo**

### CODE REVIEW

**Comment by mpdehaan** [comment]
For this:

   DMI_DICT = {
    +                'bios_date': 'bios-release-date',
    +                'bios_version': 'bios-version',
    +                'form_factor': 'chassis-type',
    +                'product_name': 'system-product-name',
    +                'product_serial': 'system-serial-number',
    +                'product_uuid': 'system-uuid',
    +                'product_version': 'system-version',
    +                'system_vendor': 'system-manufacturer'
    +                }

This can be written more simply using Python's dict constructor.

   DMI_DICT = dict(
       bios_date='bios-release-date', 
       bios_version='bios-version',
       ...
   )

**Comment by mpdehaan** [comment]
This part can also be simplified:

```
     try:
 +                        json.dumps(thisvalue)
 +                    except UnicodeDecodeError:
 +                         thisvalue = "NA"
 +
 +                    self.facts[k] = thisvalue
 +                else:
+                    self.facts[k] = 'NA'
```

instead of assigning "thisvalue", just assign self.facts[k] the value directly.

**Comment by dalevizo** [comment]
Ok I'll try it but keep in mind that I just copied the existing function from class LinuxHardware with just one change

**Comment by jctanner** [comment]
@dalevizo thank you!

**Pull request merged**
