### PR TITLE
Add ontap version to gather facts

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Add ontap version to gather facts. 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
* na_ontap_gather_facts

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]

**Review by schmots1 — APPROVED** [review]
shipit

**Review by beeankha — APPROVED** [review]
I tested locally and it passed!

**Review by schmots1 — APPROVED** [review]
shipit

**Comment by lonico** [comment]
close #50932

**Pull request merged**
