### PR TITLE
Bump antsibull version from 0.40.1 to 0.41.0 and ansible sphinx theme version to fix HTML generation in return value tables

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Follow-up PR to #76675. Most important change in antsibull 0.40.2 is https://github.com/ansible-community/antsibull/pull/387 which fixes broken HTML in return value tables. While most browsers simply ignored it and rendered the result fine, lynx wouldn't render the result.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs build

### CODE REVIEW

**Comment by felixfontein** [comment]
The Sphinx theme also generates invalid HTML; will be fixed by https://github.com/ansible-community/sphinx_ansible_theme/pull/44.

**Comment by felixfontein** [comment]
Ok, the generated HTML should be correct (or at least have a lot less errors than before). But now that we waited so long, we can also wait another week until https://github.com/ansible-community/community-topics/issues/61 is resolved, and include a new antsibull release. That one will also support the new `keyword` feature and remove email addresses from author lines.

I think it's worth the wait. @samccann what do you think?

**Comment by samccann** [comment]
Sounds good to me yes. That way I can test whatever has been fixed before updating the requirements files etc to start using the new antsibull version.

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
I did check the [W3C validator](https://validator.w3.org/) and Lynx on the resulting pages (concretely: http://docs.testing.ansible.com/ansible/devel/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup) and they were still not happy. Commit 3030dbb58f958237085a902e3a44e0ab0731e0bc removes one further warning from the validator (if you want to see why this was a warning and what kind of abysses can open up: https://www.howtocreate.co.uk/SGMLComments.html#doubledash).

Lynx is still complaining because there's a `<select>` outside a `<form>`: https://github.com/ansible-community/sphinx_ansible_theme/blob/master/sphinx_ansible_theme/version_chooser.html#L16 From the HTML 5 standard (https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element, https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-owner, https://html.spec.whatwg.org/multipage/forms.html#form-associated-element) it does not look to me that this is actually a HTML 5 requirement. I'll create an issue in the theme's repo for that where we can discuss whether to fix it (and if yes, how).

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
@felixfontein thanks!

**Comment by felixfontein** [comment]
@samccann thanks for testing, reviewing and merging :)

**Pull request merged**
