### PR TITLE
Purestorage content migration botmeta

### PR DESCRIPTION
**Pull request by anshulbehl**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by gundalow — COMMENTED** [review]
Missing
```
lib/ansible/plugins/doc_fragments/purestorage.py
lib/ansible/module_utils/pure.py
```

**Comment by anshulbehl** [comment]
@gundalow These files are left orphaned, the module_util is now divided into two files of separate usage and I cannot find doc_fragment in any of their collection

**Comment by gundalow** [comment]
> @gundalow These files are left orphaned, the module_util is now divided into two files of separate usage and I cannot find doc_fragment in any of their collection

That sounds like a bug in the collection. The docs_fragments should be in their collection and not in ansible-base

**Review by gundalow — CHANGES_REQUESTED** [review]
Docs fragments need adding.

**Pull request merged**
