### PR TITLE
add check mode support to pkgng module

### PR DESCRIPTION
**Pull request by abelbabel**
Could it be that easy or do I have missed something?

### CODE REVIEW

**Comment by jimi-c** [comment]
Typically with check mode, if it's enabled you want to return the status that would be returned if it had actually done something. So in your case, you might want to have else clauses, where you just return exit_json with the changed= set to True or False (depending on whether something would be changed or not) and a message (msg field). Take a look at `library/system/service` for examples.

**Comment by abelbabel** [comment]
@jimi-c 
Thanks for your comments!
Don't you think that your first point is fulfilled already? I thought that it checks if it runs in check mode and only if it does not run in check mode then it does system-modifying things. And exit_json will remain the same in both cases.

**Comment by mpdehaan** [comment]
-                cached          = dict(default="no", required=False, choices=["yes","no"]),

This should actually be:
-                cached          = dict(default=False, type='bool')

(and thus will convert other type of near booleans)

Sorry for the delay in getting to this one, we've been attacking the bug queue first and will soon switch back into feature pull request mode.

**Comment by jctanner** [comment]
@abelbabel seems to work well, thank you!

**Pull request merged**
