### PR TITLE
Fix typo in postgresql_privs.py

### PR DESCRIPTION
**Pull request by sfilipov**
##### SUMMARY
Fix typo in postgresql_privs.
Change 'default_prives' to 'default_privs'

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### COMPONENT NAME
postgresql_privs

##### ADDITIONAL INFORMATION
None

### CODE REVIEW

**Comment by andytom** [comment]
shipit

**Review by Andersson007 — APPROVED** [review]
shipit

**Comment by Andersson007** [comment]
@sfilipov thanks for fixing this! @andytom , thank you for reviewing!

**Comment by Andersson007** [comment]
@sfilipov , would you like to backport it to 2.8, etc?

**Comment by Andersson007** [comment]
@sfilipov , if no, no problem, i could do it

**Comment by sfilipov** [comment]
@Andersson007 no worries I can do it in an hour or two.
Which ones should I backport to? 2.6, 2.7 and 2.8?

**Comment by Andersson007** [comment]
@sfilipov , where the typo is :) max to 2.6

**Pull request merged**
