### PR TITLE
first_found lookup_plugin - replaces first_available_file

### PR DESCRIPTION
**Pull request by skvidal**
- useful in tasks/playbook inclusion
- task-specific inclusion

allows searching paths and files

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hmm, we probably should not remove anything, (people like that we do not), though I can see it to be useful to document this more prominently than first_available_file.

The question remains though, if we can make it work such that the same "API" for it works, i.e. if you feed it a list and the list is just all strings, can it be made to work in the same way in that case, so it's a drop in replacement too?  That seems difficult though, with the "paths" option added.

**Comment by skvidal** [comment]
the paths option is optional. Given that the lookup_plugin api is 'here take this list which might just be a string, maybe' it's a bit hard to be too clever.

anyone have any suggestions?

**Comment by dhozac** [comment]
Looks like it should just be a matter of

```
if isinstance(term, dict):
    # get filelists and pathlists into total_search
else:
    total_search = [term]
```

and it should be able to replace first_available_file.

**Comment by skvidal** [comment]
first_available_file only exists on copy and template right?

Could we leave it and deprecate it for with_first_found: blah

**Comment by skvidal** [comment]
deprecate and leave it in place, I mean.
just note it as deprecated in the docs.

**Comment by dhozac** [comment]
Yeah, of course, it can't be removed.

**Comment by mpdehaan** [comment]
Yeah +1 on the above patch suggestion.

And no, we can't remove it, but we should be able to maybe make first available file (MAYBE) call into this code. 

If not, that's ok.

And yes, I like the idea of differntiating based on it being a dict or not.

**Comment by skvidal** [comment]
Do you want me to squash this into two commits?

**Comment by mpdehaan** [comment]
We're ok.  Don't worry about it.  That's usually something I only care
about when they start to get hard to review.

**Comment by skvidal** [comment]
okay - then this is ready to merge, I think.

**Comment by mpdehaan** [comment]
merged, thanks, if you want to add something to the docsite that will be good if not I'll catch it later.

**Comment by rektide** [comment]
is this the first lookup plugin that will never return more than one result?

**Comment by rektide** [comment]
is this the first lookup plugin that will never return more than one result?

**Comment by mpdehaan** [comment]
On Wed, Mar 20, 2013 at 8:24 PM, rektide notifications@github.com wrote:

> is this the first lookup plugin that will never return more than one
> result?

Probably.

I like that the logic is generalized.

**Comment by skvidal** [comment]
@rektide I'm not sure I understand your question. It is supposed to return a single item, isn't it? it is FIRST found - not more than that.

Maybe I'm missing something and I don't get what you're looking for.

If you look in the top of the plugin's .py file you'll see some detailed examples of how I wanted to use it.
If that doesn't match your use case, tell me what you think it needs, so I can understand if this is the right place for it.

**Pull request merged**
