### PR TITLE
Assemble module

### PR DESCRIPTION
**Pull request by sfromm**
This adds a module that concatenates (ie. assembles) a file from
fragments in a directory in alphabetical order.  It chains the file
module afterward to fix up ownership and permission.  This also adds
tests for the assemble module with fragments in assemble.d.

See issue #80.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Nice.  in queue for merging.

Japanese translates to "No can be extremely" per Google?

**Comment by sfromm** [comment]
On Tue, 2012-06-12 at 17:59 -0700, Michael DeHaan wrote:

> Nice.  in queue for merging.
> 
> Japanese translates to "No can be extremely" per Google?

Chinese.  :)

I would translate it as 'nothing that is nothing is not nothing'.  A
play off a line from the dao de jing, 道 可 道 非 常 道.

sf

**Comment by mpdehaan** [comment]
merged, thanks, will open a ticket to add to the docs project

**Comment by mpdehaan** [comment]
hey so found a bug, on python 2.6, using md5 raises a warning about how md5 is deprecated and you should use hashlib, and that breaks parsing.

It looks like we need to trap that warning in a way that is compatible with older python, "with warnings" is probably not it.   So some logic to wrap the imports and use hashlib or md5 as appropriate will be required.

**Comment by sfromm** [comment]
That's fun.  I don't recall seeing such an error on python-2.7 (fedora17).  Anyways, I'll take a look and send a fix.

**Comment by mpdehaan** [comment]
Maybe the deprecation warning was also deprecated!

**Comment by sfromm** [comment]
El sigh.  :-/

**Pull request merged**
