### PR TITLE
remove ansible_facts added by mistake

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Removed ansible_facts which is returned but not documented in these modules.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_appserviceplan_facts
azure_rm_mariadbconfiguration_facts
azure_rm_mysqlconfiguration_facts

### CODE REVIEW

**Comment by yuwzho** [comment]
azure_rm_appserviceplan_facts.py is added in 2.7, should we remove the ansible_facts here?

**Comment by zikalino** [comment]
@yuwzho it's returned empty and undocumented, so it a kind of doesn't exist from user perspective

**Review by yuwzho — APPROVED** [review]

**Comment by yuwzho** [comment]
shipit

**Comment by bcoca** [comment]
if your module does NOT return `ansible_facts` it should not be named `_facts`

**Pull request merged**
