### PR TITLE
make default strategy configurable

### LINKED ISSUE #14939: Add strategy modification to cli
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible --version
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

None
##### Environment:

OS X El Capitan
##### Summary:

Allow strategy to be modified by a cli flag. This will help editing playbook files to change the strategy of a run.
##### Steps To Reproduce:

```
ansible-playbook play.yml --strategy linear|free|serial
```
##### Expected Results:

Run using a specific strategy

### PR DESCRIPTION
**Pull request by gawel**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

- ansible core

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0 (configurable_default_strategy 22b2befb87) last updated 2016/11/07 13:28:28 (GMT +200)
```

##### SUMMARY

This PR allow to change the default strategy used by ansible.

It use the standard way to define a constants and use this constant as the strategy option's default

This PR will also fix #14939 since it allow to change the strategy via the ```ANSIBLE_STRATEGY``` env var

### CODE REVIEW

**Comment by gawel** [comment]
All tests pass. Looks like the only failure on shippable is related to a broken environment.

**Comment by bcoca** [comment]
I would also update examples/ansible.cfg

**Comment by gawel** [comment]
Updated. It would be great to see that change in 2.2.0 too.

**Comment by bcoca** [comment]
@gawel sorry, we don't backport features, only bugfixes.

**Comment by j00bar** [comment]
Ansible Container would love to have this too.

**Comment by gawel** [comment]
@bcoca Too bad I'll have to wait. But that's totally understandable.

**Pull request merged**
