### PR TITLE
win_user: Clean up parameter handling and $result hash

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_user

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Changes include:
- Use of Get-AnsibleParam and parameter types/validateset
- Removed parameter validation
- Replace $result PSObject with normal hash

### CODE REVIEW

**Comment by dagwieers** [comment]
This PR requires PR #21377 to work.

**Review by nitzmahone — APPROVED** [review]

**Comment by nitzmahone** [comment]
Code looks good to merge, but failing at least one test

**Comment by dagwieers** [comment]
Yes, this PR requires PR #21377 to be merged. So close and re-open and fingers crossed :-)

**Comment by dagwieers** [comment]
ready_for_review

**Comment by gundalow** [comment]
Given tests are now green an @nitzmahone approval above I'm merging this into `devel`

**Pull request merged**
