### PR TITLE
add example how to use aws_service_ip_ranges result in ec2_group module

### PR DESCRIPTION
**Pull request by markuman**
##### SUMMARY
I add an example how to use the output of lookup plugin `aws_service_ip_ranges` with the `ec2_group` module.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
`plugins/lookup/aws_service_ip_ranges.py`

##### ADDITIONAL INFORMATION

1. fetch the raw data using `aws_service_ip_ranges`
2. prepare a list structure which can be used in `ec2_group` module
3. apply the ip ranges from 1 in a security group using `ec2_group`

### CODE REVIEW

**Comment by acozine** [comment]
Thanks @markuman for submitting this change. The Examples section of a module's documentation usually only shows tasks that use that module. Here you're using other modules, and the example tasks must be used together. 

To make this clear, could you either:
1. Format the tasks as a [block](https://docs.ansible.com/ansible/devel/user_guide/playbooks_blocks.html), so it's obvious they cannot be used separately, or 
2. Add this example to the [AWS guide](https://docs.ansible.com/ansible/devel/scenario_guides/guide_aws.html) instead of to the module documentation

Thanks!

**Comment by markuman** [comment]
@acozine I've revert the changes in the lookup plugin and add a new section in the aws guide.

**Comment by acozine** [comment]
Thanks @markuman for updating your PR. Unfortunately some merge commits were introduced - can you rebase the branch so it only contains your changes to the AWS guide?

**Comment by markuman** [comment]
hmm rebase does not work as git told me

https://gist.github.com/markuman/65add9d900ae75f051c95835216f26a4

**Comment by markuman** [comment]
...and I already did a rebase because told me to do so because of commit 3ba2b78.   
The result is that ansibot told me again to rebase again because of commit 3ba2b78 and a 2nd commit 7b65829

**Comment by acozine** [comment]
@markuman part of the problem was caused by making changes on the default branch, `devel`. I've cherry-picked your changes onto a clean branch and opened a fresh PR - take a look and let me know what you think. For your next PR, I recommend making a fresh clone of the ansible repo, and then creating a feature branch for the changes you want to make. GitHub has some great tutorials on forking, cloning, branching, and PRs/merging - see https://guides.github.com/. 

Closing this PR in favor of #55783.

**Pull request closed without merging**
