### PR TITLE
folder support on gcp_compute

### PR DESCRIPTION
**Pull request by rambleraptor**
##### SUMMARY

Adds support for searching through folders on gcp_compute

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

gcp_compute

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rambleraptor** [comment]
@aedwa038

**Comment by rambleraptor** [comment]
shipit
ship_it

**Comment by rambleraptor** [comment]
shipit

**Comment by rambleraptor** [comment]
bot_status

**Comment by rambleraptor** [comment]
shipit

**Comment by rambleraptor** [comment]
shipit

**Comment by rambleraptor** [comment]
@bcoca could you merge this in? The bot won't seem to merge it for me.

**Comment by rambleraptor** [comment]
@gundalow or someone else: could I get somebody to merge this in for me?

**Comment by jctanner** [comment]
@rambleraptor @gundalow I believe the merging issue should now be solved by https://github.com/ansible/ansibullbot/pull/1287

**Pull request merged**
