### PR TITLE
kubevirt_vm: Improve create VM from template

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

Improve creating VM from template. Merge VM disks/interfaces with the template defaults.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

kubevirt_vm

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pkliczewski** [comment]
@machacekondra pylint is complaing please fix.

**Comment by machacekondra** [comment]
Fixes: https://github.com/ansible/ansible/issues/54900

**Comment by pkliczewski** [comment]
+1

**Comment by machacekondra** [comment]
bot_status

**Comment by mmazur** [comment]
+1

**Comment by machacekondra** [comment]
@Akasurde Can you please review/merge?

**Comment by mmazur** [comment]
bot_status

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
bot_status

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
bot_status

**Comment by mmazur** [comment]
shipit

**Comment by mmazur** [comment]
bot_status

**Comment by mmazur** [comment]
@mattclay the bot went full skynet, we don't know what it wants, can you help?

**Comment by Akasurde** [comment]
@mkrizek might help you here.

**Comment by mkrizek** [comment]
@mmazur `automerge: automerge !module file(s) test failed` means that the PR changes files outside of modules directory, in this case it's `lib/ansible/module_utils/kubevirt.py`. In such case automerge does not apply and the PR needs to be merged manually.

**Comment by mmazur** [comment]
@mkrizek but that file is ours, we're listed as maintainers of it. That's a bit unfortunate that this gets ignored anyway. :(

**Pull request merged**
