### PR TITLE
WIP: debugging centos8 job failures

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY

WIP: debug centos8

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now da73ed4b1c0d868b7f748dfe2112da6f2ceaf67d

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 8ba2ca95f48c964a9315fe6908433e851fa945d5

**Comment by felixfontein** [comment]
Is this related to #66546?

**Comment by pabelanger** [comment]
Yes, given the test passed here, makes me believe something specific to shippable is happening. My guess is some mirror is out of sync. It would be nice, if we could hold the job from a failed run and inspect the container.

**Comment by felixfontein** [comment]
In case you didn't saw, @samdoran is also working on a fix in #66572.

**Comment by samdoran** [comment]
Yes, we've been talking back and forth about this one.

**Pull request closed without merging**
