### PR TITLE
Add vault support to file lookup plugin

### PR DESCRIPTION
**Pull request by rouge8**
The file lookup plugin now automatically decrypts ansible-vault encrypted files.

For example:

``` yaml
- hosts: localhost
 connection: local
 tasks:
   - name: "Show secret stuff"
     debug: msg="{{ lookup('file', 'files/secret_stuff') }}"

    - name: "non secret stuff"
     debug: msg="{{ lookup('file', 'files/not_secret') }}"
```

If 'files/secret_stuff' is encrypted with ansible-vault, running the example playbook with a provided vault password will print the contents of 'files/secret_stuff'.

This is based on #8110 and #8533, but updated for the latest devel branch and with an added integration test.

### CODE REVIEW

**Comment by sean-abbott** [comment]
I'd like to give a +1 vote for this.

**Comment by cemo** [comment]
+1

**Comment by cknapp** [comment]
+1

**Comment by amygitsthings** [comment]
+1

**Comment by Vyasd** [comment]
+1

**Comment by rouge8** [comment]
Is there anything I can do to make this ready to merge?

**Comment by dwt** [comment]
+1 please merge, that would be super helpful!

**Comment by benodom** [comment]
:+1:  +1 upvote, thanks @rouge8

**Comment by markwoon** [comment]
+1

Would love to see this available soon.

**Comment by rouge8** [comment]
Rebased to resolve the merge conflict, confirmed that the test still passes.

**Comment by rouge8** [comment]
Rebased again to run the tests on Travis CI.

**Comment by rouge8** [comment]
This is out of date again. Should I rebase against the v1 or v2 code?

**Comment by nathanhruby** [comment]
Adding another :+1: 
As far as I am aware, the v2 release is not due for a while yet, probably re-basing against the v1 code would be a better bet

**Comment by rypervenche** [comment]
+1 I would love to have this feature available soon :)

**Comment by leonard84** [comment]
+1

**Comment by abourget** [comment]
+1 !!! heeeyo!

**Comment by amenonsen** [comment]
Just noting that this is yet another change that would benefit from the refactoring proposed in #9050, so that the vault_password doesn't have to be passed around so much. Also relevant are #7298 (still open) and #8533 (closed). Note @bcoca's last comment on #7298, which says that this functionality is planned for inclusion in v2, and these PRs are being left open as a reminder.

**Comment by sivel** [comment]
@rouge8,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by sivel** [comment]
@rouge8,

Hi!

Thank you very much for your submission to Ansible.  It sincerely means a lot to us.

Unfortunately it looks like the code underneath has changed since this was submitted.  Specifically this change was written against a code path that no longer exists in Ansible.

We would like to ask if you could either update the code in this pull request to apply against the current state of Ansible or close this pull request. If we do not hear back from you, we will close this pull request out shortly.

Thank you once again for this and your interest in Ansible!

**Comment by dvigueras** [comment]
Great PR @rouge8 ! I'm looking forward to having it included in Ansible 2.2 :)

**Comment by rouge8** [comment]
I now use [sops](https://github.com/mozilla/sops) rather than ansible-vault, so I don't have time to update this PR for v2.

**Pull request closed without merging**
