### PR TITLE
Add possibility to disable basic auth in the script ConfigureRemotingForAnsible.ps1

### PR DESCRIPTION
**Pull request by equelin**
##### SUMMARY
Add possibility to disable basic auth when configuring Windows host with the script ConfigureRemotingForAnsible.ps1.

Add the switch parameter `-DisableBasicAuth` (set to $false by default). 

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
examples/scripts/ConfigureRemotingForAnsible.ps1

##### ANSIBLE VERSION
Not relevant.

### CODE REVIEW

**Comment by jborean93** [comment]
I'm not going to lie, there hasn't been much action on this script as we want to move away from it due to some of the insecure elements being set by default (basic auth on included).

I'll try and see what we want to do about this though as this is a pretty benign change.

**Comment by dagwieers** [comment]
Beware that the deadline for getting new features/modules accepted in [Ansible v2.5 is nearing](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_5.rst), it is set to either 2018-01-15 or 2018-01-31. If you are blocked, or you need feedback, please discuss on IRC channel #ansible-windows or add a comment to [the Windows Working Group meeting agenda](https://github.com/ansible/community/issues/195) to get it resolved.

**Comment by equelin** [comment]
Hello @jborean93 , feel free to close this PR if needed.

**Comment by jborean93** [comment]
Let's just get it in, disabling basic auth is a good idea from a security perspective. If you are able to fix the conflict I'll merge it in.

**Comment by equelin** [comment]
Ok, merge conflict resolved. Thanks @jborean93.

**Comment by jborean93** [comment]
Thanks @equelin

**Pull request merged**
