### PR TITLE
iptables: Adding multiport module support

### PR DESCRIPTION
**Pull request by josev814**
Adding in destination_ports option to use the multiport module in order to accommodate using multiple comma delimited ports

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

module/plugin/systems/iptables.py

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
```

##### SUMMARY

When using iptables v1.4.7 --to-ports is not supported.  In order to provide better global access to comma delimited ports, I added destination_ports, which uses the multiport module so that --dports would be able to be used.  I included a sample into the documentation along with an explanation of the rule.

```
before with using --to-ports: error is "iptables v1.4.7: unknown option --to-ports Try 'iptables -h' or 'iptables --help' for more information."
now with multiports:
"-A INPUT -p tcp -m multiport --dports 80,443 -j ACCEPT"
```

### CODE REVIEW

**Comment by vangie** [comment]
+1

**Comment by LinusU** [comment]
Nice 👍 

shipit

**Comment by sebastiendarocha** [comment]
Hello @josev814 

Could you rebase your PR ? 

http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

**Comment by maxamillion** [comment]
@josev814 please rebase and we would like to add some tests, please contact us on `#ansible-devel` on `irc.freenode.net` so we can help with the test setup because there will be some nuance due to the impact of iptables changes to a system. Thanks!

**Comment by mattclay** [comment]
Since the tests won't work under Docker they'll need the `skip/docker` alias. That should allow the tests to run on our RHEL VMs while skipping our Docker containers on Shippable.

**Comment by josev814** [comment]
I followed the guide on rebasing my original commit request. 
 Hopefully, I didn't mess anything up. 
[http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html]

**Comment by Akasurde** [comment]
@josev814 Are you still working on this, let us know ? Thanks, needs_info

**Comment by josev814** [comment]
@Akasurde Not sure why my pr is failing.  It seems that this is the test it's failing on.  Is there anything else that I have to do to get the pr merged?
 [https://app.shippable.com/github/ansible/ansible/runs/147458/2/console](https://app.shippable.com/github/ansible/ansible/runs/147458/2/console)

**Comment by prabdeb** [comment]
Much needed feature!

**Comment by DuncanConroy** [comment]
Is there any news when this might get merged?

**Comment by nosmicek** [comment]
If only after almost 3 years those few lines could be merged... Much needed to lower the clutter in setting iptables rules..

**Comment by Shrews** [comment]
Closing in favor of #72928

**Pull request closed without merging**
