### PR TITLE
nmcli: Fix known validate-modules issues

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:
- Adding parameter types
- Fix validate-modules issue
- Improve parameter types and resulting changes

This PR needs to be verified and tested by maintainer(s).

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
nmcli

### CODE REVIEW

**Comment by dagwieers** [comment]
The CI issues are to be expected as we are fixing the version_added parameters and validate-modules is not very flexible here.

**Comment by dagwieers** [comment]
bot_skip

**Comment by dagwieers** [comment]
We have a fix for the sanity tests for this issue at: #52497

**Comment by dagwieers** [comment]
bot_skip

**Review by gundalow — APPROVED** [review]

**Pull request merged**
