### PR TITLE
Issue 56430

### LINKED ISSUE #56430: postgresql_pg_hba TypeError: then pg_hba.conf is wiped
Running ansible-playbook 2.9.0.dev0 

The problem is that using postgresql_pg_hba results in this error:

TypeError: 127.0.0.1/32 and ::1/128 are not of the same version

And then the pg_hba.conf file is wiped.

A similar error occures if the address 192.168.0.0/24 is used in the playbook.

```
(venv3.6) ubuntu@ubuntu-GB-BXi3-5010:~/ansible$ ansible-playbook --version
ansible-playbook 2.9.0.dev0
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/ansible/venv3.6/lib/python3.6/site-packages/ansible
  executable location = /home/ubuntu/ansible/venv3.6/bin/ansible-playbook
  python version = 3.6.8 (default, Apr  9 2019, 04:59:38) [GCC 8.3.0]
(venv3.6) ubuntu@ubuntu-GB-BXi3-5010:~/ansible$
```

This is the playbook:

```
(venv3.6) ubuntu@ubuntu-GB-BXi3-5010:~/ansible$ cat ~/ansible/renderworker/postgres/ansible/setup_postgres_pg_hba.yml
---
- hosts: 192.168.1.110
  become: yes

  tasks:

    - name: Grant postgres access from home
      postgresql_pg_hba:
        dest: /etc/postgresql/10/main/pg_hba.conf
        contype: host
        users: postgres
        source: samenet
        databases: all
        method: md5
        create: true

(venv3.6) ubuntu@ubuntu-GB-BXi3-5010:~/ansible$
```

This is the output from running the playbook:

```
(venv3.6) ubuntu@ubuntu-GB-BXi3-5010:~/ansible$ ansible-playbook ~/ansible/renderworker/postgres/ansible/setup_postgres_pg_hba.yml

PLAY [192.168.1.110] ************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************
ok: [192.168.1.110]

TASK [Grant postgres access from home] ******************************************************************************************************************************************************************************
fatal: [192.168.1.110]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.1.110 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1557891828.8283231-200022434247587/AnsiballZ_postgresql_pg_hba.py\", line 125, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1557891828.8283231-200022434247587/AnsiballZ_postgresql_pg_hba.py\", line 117, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1557891828.8283231-200022434247587/AnsiballZ_postgresql_pg_hba.py\", line 51, in invoke_module\r\n    spec.loader.exec_module(module)\r\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\r\n  File \"/tmp/ansible_postgresql_pg_hba_payload_y9useyqu/__main__.py\", line 709, in <module>\r\n  File \"/tmp/ansible_postgresql_pg_hba_payload_y9useyqu/__main__.py\", line 696, in main\r\n  File \"/tmp/ansible_postgresql_pg_hba_payload_y9useyqu/__main__.py\", line 319, in write\r\n  File \"/tmp/ansible_postgresql_pg_hba_payload_y9useyqu/__main__.py\", line 390, in render\r\n  File \"/tmp/ansible_postgresql_pg_hba_payload_y9useyqu/__main__.py\", line 390, in <listcomp>\r\n  File \"/tmp/ansible_postgresql_pg_hba_payload_y9useyqu/__main__.py\", line 371, in get_rules\r\n  File \"/usr/lib/python3.6/ipaddress.py\", line 652, in __lt__\r\n    self, other))\r\nTypeError: 127.0.0.1/32 and ::1/128 are not of the same version\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP **********************************************************************************************************************************************************************************************************
192.168.1.110              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

And on the target host this is the pg_hba.conf file:

```
ubuntu@ubuntu:~$ sudo cat /etc/postgresql/10/main/pg_hba.conf
# PostgreSQL Client Authentication Configuration File
# ===================================================
#
# Refer to the "Client Authentication" section in the PostgreSQL
# documentation for a complete description of this file.  A short
# synopsis follows.
#
# This file controls: which hosts are allowed to connect, how clients
# are authenticated, which PostgreSQL user names they can use, which
# databases they can access.  Records take one of these forms:
#
# local      DATABASE  USER  METHOD  [OPTIONS]
# host       DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostssl    DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
# hostnossl  DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
#
# (The uppercase items must be replaced by actual values.)
#
# The first field is the connection type: "local" is a Unix-domain
# socket, "host" is either a plain or SSL-encrypted TCP/IP socket,
# "hostssl" is an SSL-encrypted TCP/IP socket, and "hostnossl" is a
# plain TCP/IP socket.
#
# DATABASE can be "all", "sameuser", "samerole", "replication", a
# database name, or a comma-separated list thereof. The "all"
# keyword does not match "replication". Access to replication
# must be enabled in a separate record (see example below).
#
# USER can be "all", a user name, a group name prefixed with "+", or a
# comma-separated list thereof.  In both the DATABASE and USER fields
# you can also write a file name prefixed with "@" to include names
# from a separate file.
#
# ADDRESS specifies the set of hosts the record matches.  It can be a
# host name, or it is made up of an IP address and a CIDR mask that is
# an integer (between 0 and 32 (IPv4) or 128 (IPv6) inclusive) that
# specifies the number of significant bits in the mask.  A host name
# that starts with a dot (.) matches a suffix of the actual host name.
# Alternatively, you can write an IP address and netmask in separate
# columns to specify the set of hosts.  Instead of a CIDR-address, you
# can write "samehost" to match any of the server's own IP addresses,
# or "samenet" to match any address in any subnet that the server is
# directly connected to.
#
# METHOD can be "trust", "reject", "md5", "password", "scram-sha-256",
# "gss", "sspi", "ident", "peer", "pam", "ldap", "radius" or "cert".
# Note that "password" sends passwords in clear text; "md5" or
# "scram-sha-256" are preferred since they send encrypted passwords.
#
# OPTIONS are a set of options for the authentication in the format
# NAME=VALUE.  The available options depend on the different
# authentication methods -- refer to the "Client Authentication"
# section in the documentation for a list of which options are
# available for which authentication methods.
#
# Database and user names containing spaces, commas, quotes and other
# special characters must be quoted.  Quoting one of the keywords
# "all", "sameuser", "samerole" or "replication" makes the name lose
# its special character, and just match a database or username with
# that name.
#
# This file is read on server startup and when the server receives a
# SIGHUP signal.  If you edit the file on a running system, you have to
# SIGHUP the server for the changes to take effect, run "pg_ctl reload",
# or execute "SELECT pg_reload_conf()".
#
# Put your actual configuration here
# ----------------------------------
#
# If you want to allow non-local connections, you need to add more
# "host" records.  In that case you will also need to make PostgreSQL
# listen on a non-local interface via the listen_addresses
# configuration parameter, or via the -i or -h command line switches.




# DO NOT DISABLE!
# If you change this first entry you will need to make sure that the
# database superuser can access the database using some other method.
# Noninteractive access to all databases is required during automatic
# maintenance (custom daily cronjobs, replication, and similar tasks).
#
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

```
And now, after the playbook was run the pga_hba.conf file is empty:

```
ubuntu@ubuntu:~$ sudo cat /etc/postgresql/10/main/pg_hba.conf
ubuntu@ubuntu:~$

```

### PR DESCRIPTION
**Pull request by sebasmannem**
##### SUMMARY
Fixes #56430: postgresql_pg_hba TypeError: then pg_hba.conf is wiped
1: Type error occurs, because IPv6Network (probably /128) is compared to IPv4Network (probably /32). This is fixed by replacing the sorted keyfunction with a proper __lt__ function, that handles types better.
2: The file is written in a corrupted state, because the content is rendered into the file directly.
I changed this, to first render into a var, then open file, and the write var to file, so that an error during render does not end up in a partially written file.
3: I added some extra integration test cases, to better overcome issues like these.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
postgresql_pg_hba

##### ADDITIONAL INFORMATION
With the new solution, the order parameter is no longer usable.
It is deprecated in 2.9 and will be removed in 2.11.

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
shipit

**Comment by Andersson007** [comment]
@sebasmannem , thank you for this PR!
If you like to see this bug fixed in 2.8 branch in the next minor release, **after** this is merged, please, do a backport PR https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

**Comment by Andersson007** [comment]
shipit

**Comment by sebasmannem** [comment]
As soon as it gets merged, I will do a backport PR. Thanks for the tip.

**Comment by Andersson007** [comment]
@tcraxs @andytom could you, guys, look at this

**Comment by sebasmannem** [comment]
Hi @dagwieers , can you merge this into devel, so I can make a backport PR for it?

**Comment by andytom** [comment]
shipit

**Comment by Andersson007** [comment]
where is automerging...

**Comment by Andersson007** [comment]
bot_status

**Comment by Andersson007** [comment]
@sebasmannem , also contributors have requested a changelog fragment https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs, could you please add this? (anyway it will be needed for backport)

**Comment by Andersson007** [comment]
Thanks all!

**Pull request merged**
