### PR TITLE
git fix docs and wrapper script

### LINKED ISSUE #77582: Git module not accepting host key
### Summary

If I create a new user and install ansible with:
```
[root@awx-devel ~]# useradd tester
[root@awx-devel ~]# sudo su - tester
[tester@awx-devel ~]$ python3 -m venv ~/ansible_git_test_venv
[tester@awx-devel ~]$ source ~/ansible_git_test_venv/bin/activate
(ansible_git_test_venv) [tester@awx-devel ~]$ pip install ansible==6.0.0a1
```

And confirm I have the latest changes to the git module:
```
(ansible_git_test_venv) [tester@awx-devel ~]$ ansible-doc git | grep "Be aware that this disables a protection against MITM attacks"
        Be aware that this disables a protection against MITM attacks.
```

Then create a simple playbook like:
```
(ansible_git_test_venv) [tester@awx-devel ~]$ cat <<__EOF__ >./test.yml
> ---
> - name: Test git
>   hosts: localhost
>   connection: local
>   tasks:
>     - name: update project using git
>       git:
>         dest: "temp"
>         repo: "git@github.com:test/private_repo.git"
>         version: "HEAD"
>         force: "False"
>         accept_hostkey: True
>       register: git_result
> 
>     - debug:
>         var: git_result
> __EOF__
```

Running this playbook causes an issue:
```
(ansible_git_test_venv) [tester@awx-devel ~]$ ansible-playbook test.yml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Test git] ****************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
ok: [localhost]

TASK [update project using git] ****************************************************************************************************************************
The authenticity of host 'github.com (140.82.112.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
It's not "respecting" the accept_hostkey parameter.
```

After doing some debugging I can see that the env var is correctly being set and that moves down into the subprocess running git but I can't find any documentation that the git client actually does anything with an environment variable called GIT_SSH_OPTS.

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0b0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tester/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tester/ansible_git_test_venv/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/tester/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/tester/ansible_git_test_venv/bin/ansible
  python version = 3.10.3 (main, Mar 18 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.1.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

RHEL 8, Fedora 35

### Steps to Reproduce

```yaml (paste below)

```
---
- name: Test git
  hosts: localhost
  connection: local
  tasks:
    - name: update project using git
      git:
        dest: "temp"
        repo: "git@github.com:test/private_repo.git"
        version: "HEAD"
        force: "False"
        accept_hostkey: True
      register: git_result

    - debug:
        var: git_result

### Expected Results

I expected to not get prompted on the host key.

### Actual Results

```console
TASK [update project using git] ****************************************************************************************************************************
The authenticity of host 'github.com (140.82.112.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
It's not "respecting" the accept_hostkey parameter.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by bcoca**
fixes #77582

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

git

### CODE REVIEW

**Comment by sivel** [comment]
This all looks good.  Have you had time to review tests to see why it wasn't caught previously?

**Comment by bcoca** [comment]
When i run the tests manually they fail on devel, but pass on this PR, still looking at what happened on the original merge.

**Comment by sivel** [comment]
`GIT_KEY` is no longer used in the wrapper, and isn't respected by `git` itself.

That code needs to be updated to something like:

```diff
diff --git a/lib/ansible/modules/git.py b/lib/ansible/modules/git.py
index 4dbca5f3f6..92b31d559c 100644
--- a/lib/ansible/modules/git.py
+++ b/lib/ansible/modules/git.py
@@ -486,7 +486,9 @@ def set_git_ssh_env(key_file, ssh_opts, git_version, module):

     # deal with key file
     if key_file:
-        os.environ["GIT_KEY"] = key_file
+        key_opt = '-i %s' % key_file
+        if key_opt not in ssh_opts:
+            ssh_opts += ' %s' % key_opt

         ikey = 'IdentitiesOnly=yes'
         if ikey not in ssh_opts:
```

With that change, I can get all of the tests depending on `github_ssh_private_key` to pass when I inject my key into tests.

**Comment by sivel** [comment]
Ok, I've now tested against `centos7`, `rhel/8.5`, `fedora34`, `fedora35`, `freebsd/12.3` and `freebsd/13.0` with my locally hacked tests to supply a valid key for GitHub, since many tests don't run in CI currently.

I think that's a pretty wide set of coverage.

**Review by sivel — APPROVED** [review]

**Comment by sivel** [comment]
Please open a backport for stable-2.13

**Pull request merged**
