### PR TITLE
Fix for SLES 11.4, which has now also an /etc/os-release file.

### PR DESCRIPTION
**Pull request by photoninger**
SuSE added a "/etc/os-release" file with SLES 11 SP4 and now the setup module returns "0" in "ansible_distribution_release" instead of "4"
Because "VERSION_ID" is not an the last line of this file, release was always set to "0" in the loop "for line in data.splitlines():"

Here is an example of "/etc/os-release":
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"

### CODE REVIEW

**Comment by alxgu** [comment]
Thank you for your PR. It works fine. 
I would suggest to change line 423 -> if release.group(1):

**Comment by alxgu** [comment]
You need to rebase your commit
https://robots.thoughtbot.com/keeping-a-github-fork-updated

**Comment by photoninger** [comment]
I am sorry, I messed up my branch (used merge were I should have used rebase). 
I made a new clean branch and a new proper PR: https://github.com/ansible/ansible/pull/12909

**Comment by alxgu** [comment]
maybe this should PR should be closed

**Comment by abadger** [comment]
PR #12909 has been merged.  Closing this one.

**Pull request closed without merging**
