### PR TITLE
Zabbix 3.4 support fix for zabbix_template module.

### PR DESCRIPTION
**Pull request by evilgn0me**
As of 3.4 Zabbix version application does not have 'updateExisting'.

### CODE REVIEW

**Comment by logan2211** [comment]
Is that option based on the version of the Zabbix server, or the version of the configuration json being imported? ie. does a zabbix 3.4 server accept `updateExisting` if the json schema has a 3.2 version?

Where I'm going with this: I think we might need to conditionally add in that option on older zabbix versions. If it is based on the schema version that will be easy because Zabbix forces you to provide a versioned json with `configuration.import`

**Comment by evilgn0me** [comment]
It does not accept updateExisting. You will receive api error 'Invalid parameter "/rules/applications": unexpected parameter "updateExisting"'

**Comment by evilgn0me** [comment]
There is same thread in puppet template module - https://github.com/voxpupuli/puppet-zabbix/issues/449

**Comment by logan2211** [comment]
Could you incorporate something like https://github.com/Logan2211/ansible/commit/51487c013aa0038240a6c262ca37cd1e95dcd8d3 so we can avoid possibly breaking behavior on versions prior to 3.4?

**Comment by evilgn0me** [comment]
okay

**Comment by logan2211** [comment]
shipit

**Comment by eikef** [comment]
shipit

**Comment by eikef** [comment]
bot_status

**Comment by eikef** [comment]
There may be an uppercase/lowercase conflict with your nick, @Logan2211; it's referenced as lowercase in zabbix_template.py, which may be confusing the bot. I added a PR to add you to the maintainers via BOTMETA.yml instead, and we can fix the uc/lc thing after. :)

**Comment by logan2211** [comment]
Ahh ok thanks @eikef

**Comment by eikef** [comment]
shipit

**Comment by eikef** [comment]
bot_status

**Pull request merged**
