### PR TITLE
Sx5 868 pr keycloak group

### PR DESCRIPTION
**Pull request by elfelip**
##### SUMMARY
Add functionalities to keycloak_group module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
keycloak_group

##### ADDITIONAL INFORMATION
Add role management to Keycloak_group module. Add a new list type for attributes to support Ansible variable as name.

### CODE REVIEW

**Review by rrey — CHANGES_REQUESTED** [review]
Hi !
I think this PR contains things that are unrelated to the PR. (The netapp stuff for example).
There is a lot of stuff regarding roles, and I think a module that handles the roles in keycloak would make more sense.

**Comment by elfelip** [comment]
> Hi !
> I think this PR contains things that are unrelated to the PR. (The netapp stuff for example).
> There is a lot of stuff regarding roles, and I think a module that handles the roles in keycloak would make more sense.

Hi Rémi.
Maybe I can do cleaner PR without netapp stuff. Roles in this context are used to grant realm roles and clients roles to the group. I also did a pull request for a keycloak module to manage realm roles. Client Roles are managed by the keycloak_client PR.

**Comment by rrey** [comment]
Don’t you think that role management would deserve a dedicated module ?

**Comment by elfelip** [comment]
Hi @rrey 
We devloped the following modules for Keycloak. 
keycloak_client.py, keycloak_component.py, keycloak_identity_provider.py, keycloak_role.py, keycloak_authentication.py, keycloak_group.py, keycloak_realm.py and keycloak_user.py
They are used to manage our production Keycloak environment for almost two years now. We have integration tests running every day on those modules to test them against new Keycloak/Ansible versions.
Our main repository is https://github.com/Inspq/ansible.git
Integrated tests are in the test/units/modules/identity/keycloak/ directory of that repo.
My name is Philippe Gauthier and I am from Quebec. We can user another channel to talk about those modules in french.
Thankyou.

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
