### PR TITLE
[2.8] Redirect inventory script links

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #71732 to stable-2.8.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/scenario_guides/guide_azure.rst
docs/docsite/rst/scenario_guides/guide_infoblox.rst
docs/docsite/rst/scenario_guides/guide_packet.rst
docs/docsite/rst/user_guide/intro_dynamic_inventory.rst

### CODE REVIEW

**Comment by acozine** [comment]
Hm, if we're doing version-specific links, shouldn't these point to the stable-2.8 branch?

**Comment by felixfontein** [comment]
@acozine I wanted to do that first, but then originally the links pointed to `devel`, so I thought I'd keep them pointing at `stable-2.9`, since that's the latest (stable) Ansible version having the files.

I'm really not sure. I think both `stable-2.8` and `stable-2.9` would be fine.

**Comment by acozine** [comment]
Fair enough, you convinced me. Maybe it will even encourage upgrading!

**Comment by felixfontein** [comment]
@acozine thanks for reviewing and merging :)

**Pull request merged**
