### PR TITLE
Fixes #15215 - Inventory script does not work with assumed roles

### LINKED ISSUE #15215: Inventory script does not work with assumed roles from the command line
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2 dynamic inventory script

##### ANSIBLE VERSION
ansible 2.0.1.0

##### OS / ENVIRONMENT
On Ubuntu Linux, and Amazon Linux on AWS

##### SUMMARY
I cannot assume a role on the command line by exporting the new temporary credentials as environment variables and run the inventory script.

I have my 'master' AWS account's credentials in ~/.aws/credentials, then I assume a role on another account, and export the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SECRET_TOKEN and AWS_SESSION_TOKEN values it gives me. When I run the inventory script (which I have updated from latest devel, as of now) I get:

```
ERROR: "Authentication error retrieving ec2 inventory.
 - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment vars found but may not be correct
 - Boto configs found at '~/.aws/credentials', but the credentials contained may not be correct", while: getting EC2 instances
```

I am using the latest inv/ec2.py as of now.

Thanks

### PR DESCRIPTION
**Pull request by ozbillwang**
##### ISSUE TYPE

- Feature Pull Request
##### ANSIBLE VERSION

```
no special
```
##### SUMMARY

add support to dynamic ec2 host inventory from `system environment`, `.boto`, and assume role from `.aws/config`
Fixes #15215

```
If you set system environment 

AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN

You can run directly
./ec2.py  --list

If you set profile with aws_security_token in `~/.boto` or `~/.aws/credentials`

./ec2.py --profile marketingadmin --list

If you set profile with assume role in `~/.aws/config`

./ec2.py --profile marketingadmin --list

```

### CODE REVIEW

**Comment by ozbillwang** [comment]
the latest build error is not related my code.

https://github.com/ansible/ansible/blob/ed35e8bce21180529e72f5bbe1d853b67ddac870/test/integration/roles/test_uri/tasks/main.yml#L178

```
- name: test basic auth
  uri:
    url: 'http://httpbin.org/basic-auth/user/passwd'
    user: user
    password: passwd
```

**Comment by nethershaw** [comment]
This fixes EC2 dynamic inventory while running inside an EC2 instance configured only with an IAM role. Please merge.

**Comment by willthames** [comment]
Does this do more than #15196 - certainly there's code in common.

**Comment by ozbillwang** [comment]
@nethershaw 

I follow the comments I made on Apr 17, 2016 in #15215 , there are four scenarios, my updates are fixed them all. So not only for IAM-role

@willthames 

Don't know that PR. Seems there are many ways to do the same job. No time to test that, my one is good enough and I already implemented several projects with it.

**Comment by nethershaw** [comment]
@SydOps Unfortunately your fixes are applied to a much older version of upstream ec2.py, which means you have reverted a number of other fixes in the process, notably https://github.com/ansible/ansible/pull/15890. My earlier endorsement of this pull request was premature; we cannot use this ec2.py.

Please rebase your fixes on the current upstream devel branch so that they do not conflict.

**Comment by ozbillwang** [comment]
@nethershaw  Yes, I knew. My PR was blocked by another PR #15378 first which was merged just before mine. It has a feature that several reviewers did not agree, but it got merged. 

If I need merge mine, I have to deal conflict with #15378, which I think it is a wrong commit and hope to roll it back. So I don't want to spend the time to understand #15378 or spend my time base on a wrong code. 

Then @defionscode tried to help to fix the conflict, but until now I don't see any progresses.

**Comment by afeld** [comment]
I believe this has been superseded by https://github.com/ansible/ansible/pull/15196.

**Comment by SydOps** [comment]
@afeld 

No, #15196 is not good enough.

**Comment by ozbillwang** [comment]
I close this PR. 

There are too many conflicts which I have no time to fix it currently. I need sync upstream to my fork now.

The updated ec2.py file is independent file, you can download it from 

https://github.com/BWITS/ansible/blob/bugfix/15215/15451/contrib/inventory/ec2.py

or

https://gist.github.com/SydOps/d8277880867dec21f1d61155e3cbd6a0

**Pull request closed without merging**
