### PR TITLE
Ansible-galaxy requirements support a include directive

### PR DESCRIPTION
**Pull request by Lujeni**
## Context

As the tasks file, the first goal of this directive is to include files and combine them to form clean, reusable abstractions.
## Tests

``` yaml
# nginx.yaml

---
- src: https://github.com/bennojoy/nginx
  path: roles/
  name: nginx_server1
```

``` yaml
# requirements.yaml

---
- include: nginx.yml

- src: https://github.com/bennojoy/nginx
  path: roles/
  name: nginx_server2
```

``` bash
$ ansible-galaxy install -r requirements.yaml
```
## update

`2015-11-16`: rebase + add a test part
`2016-02-08`: rebase

Thanks

### CODE REVIEW

**Comment by ultrabug** [comment]
:+1:

**Comment by btall** [comment]
it seem good :+1:

**Comment by Lujeni** [comment]
Hello, 

There is a way to accelerate this PR review/integration?

Regard

**Comment by bcoca** [comment]
Sorry for any delays, we are finalizing teh 2.0 release which means we are focusing on bugs that affect 2.0 and new features will have to wait a bit.

**Comment by Lujeni** [comment]
@bcoca Hello, do you need more tests or informations to integrate this feature into the next version ?
Thanks

**Comment by jimi-c** [comment]
Merged, thanks! This will be included in Ansible 2.2.0.

**Pull request merged**
