### PR TITLE
Revisiting default values of the yum_repository module

### PR DESCRIPTION
**Pull request by jtyr**
##### SUMMARY
This PR is revisiting the default values of the `yum_repository` module. It's fixing some of the default values and adding note explaining what the default values actually mean in the scope of this module.

##### ISSUE TYPE
Docs Pull Request

##### COMPONENT NAME
`yum_repository`

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### ADDITIONAL INFORMATION
Related to PR #45796.

### CODE REVIEW

**Comment by acozine** [comment]
@jtyr here is why I think documenting the `yum.conf` defaults in the Ansible module documentation is misleading:

If the documentation states that the default setting for `gpgcheck` is `no`, a user might create a playbook with a `yum_repository` task that has no setting for `gpgcheck`. The user would expect no checks to happen.

Now let's say the user runs this playbook on 65 machines. 50 of those machines are using the default settings for `yum` but 15 of them have an entry in `/etc/yum.conf` setting `gpgcheck` to `yes`. My understanding is that in this case, a check would occur on those 15 machines.

If Ansible sets a default, the behavior of the module should be consistent across all target machines.

If my understanding is correct, then when the parameter is not set in Ansible, the behavior of the module depends on the settings on the target machine(s), which may not be consistent.

**Comment by jtyr** [comment]
@acozine The behavior *of the module* is consistent across all machines. What's not consistent is the machines themselves. If the user want to have consistent result, he/she has define all necessary parameters and/or manage the `yum.conf` file. It's simple as that.

**Comment by acozine** [comment]
With a default setting of `foo`, you should get **the same** results (regardless of the settings on the target machines) in these two cases:
1. parameter not set
2. parameter set to `foo`

With the `yum_repository` module, you may get **different** results in the two cases:
1. `gpgcheck` parameter not set
2. `gpgcheck` parameter set to `no`

Ansible does not have a default setting for this parameter. And the documentation should reflect that.

**Comment by jtyr** [comment]
All default values in this module are YUM default values. In order to get consistent behaviour, we would have to enforce values of all parameters for every repo we define. That would create very ugly repo files. I'm sure nobody wants that. This is why the module is showing YUM defaults so the user knows what the value normally is. If the system is overriding the default YUM values in the `yum.conf` file, the user should manage that file in order to get consistent behaviour.

**Comment by acozine** [comment]
@jtyr if the user sets the value of `gpgcheck` to `no` in a task or playbook, what will happen on a machine with a setting of `yes` in the `yum.conf` file?

**Comment by jtyr** [comment]
If the user uses `gpgcheck: no` then the specific repo will not perform any GPG checks regardless what's in the `yum.conf`.

**Comment by acozine** [comment]
In that case, documenting `no` as the default setting for `gpgcheck` in the Ansible `yum_repository` module is inaccurate. Setting `gpgcheck=no` != not setting the parameter. 

The Ansible documentation describes the behavior of Ansible, not of other related systems. It is not, nor can it ever be, a one-stop shop for learning how to manage unix/linux servers. Users can learn about the behavior of `yum`, the defaults and settings of `yum.conf`, and other related issues elsewhere. We can include warnings and pointers where it's most helpful, but the Ansible documentation must accurately describe Ansible itself.

**Pull request closed without merging**
