### PR TITLE
fix delegation vars usage (debug still shows inventory_hostname)

### LINKED ISSUE #34259: delegated task uses an incorrect 'ansible_become_pass'
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegate_to

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /Users/tagir/.config/ansible/ansible.cfg
  configured module search path = [u'/Users/tagir/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
```
 ANSIBLE_PIPELINING(/Users/tagir/.config/ansible/ansible.cfg) = True
 CACHE_PLUGIN(/Users/tagir/.config/ansible/ansible.cfg) = jsonfile
 CACHE_PLUGIN_CONNECTION(/Users/tagir/.config/ansible/ansible.cfg) = .
 CACHE_PLUGIN_TIMEOUT(/Users/tagir/.config/ansible/ansible.cfg) = 60
 DEFAULT_BECOME_METHOD(/Users/tagir/.config/ansible/ansible.cfg) = su
 DEFAULT_GATHERING(/Users/tagir/.config/ansible/ansible.cfg) = smart
 DEFAULT_JINJA2_EXTENSIONS(/Users/tagir/.config/ansible/ansible.cfg) = jinja2.ext.do
 DEFAULT_MODULE_NAME(/Users/tagir/.config/ansible/ansible.cfg) = shell
 DEFAULT_ROLES_PATH(/Users/tagir/.config/ansible/ansible.cfg) = [u'/Users/tagir/git/ansible/r oles']
 DEFAULT_STDOUT_CALLBACK(/Users/tagir/.config/ansible/ansible.cfg) = debug
 RETRY_FILES_ENABLED(/Users/tagir/.config/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
In my environment `ansible_become_pass` is defined on a per-host basis. This does not play well with the delegated tasks, because instead of using the password of the host the task is delegated to, the password of the delegating host is used.

##### STEPS TO REPRODUCE
Sample inventory file:
```yaml
---
all:
  hosts:
    ns1:
      ansible_become_pass: ns1
    ns2:
      ansible_become_pass: ns2
    ns3:
      ansible_become_pass: ns3
```

Sample playbook:
```yaml
---
- hosts: all
  tasks:
    - debug: msg="{{ ansible_become_pass }}"
      delegate_to: ns1
```

##### EXPECTED RESULTS
`ansible_become_pass` to be `ns1` for every run of the delegated task.

##### ACTUAL RESULTS
The value of the `ansible_become_pass` is taken from the variables of the respective host.

```
$ ansible-playbook -i inventory.yml playbook.yml

PLAY [all] **********************************************************************************

TASK [debug] ********************************************************************************
ok: [ns1 -> None] => {}

MSG:

ns1

ok: [ns2 -> None] => {}

MSG:

ns2

ok: [ns3 -> None] => {}

MSG:

ns3


PLAY RECAP **********************************************************************************
ns1                        : ok=1    changed=0    unreachable=0    failed=0
ns2                        : ok=1    changed=0    unreachable=0    failed=0
ns3                        : ok=1    changed=0    unreachable=0    failed=0
```

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

fixes #34259
alternative to #56082

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

core

### CODE REVIEW

**Comment by equinox0815** [comment]
I have a similar problem than #30630 but instead of `become_*` variables i try to set `ansible_host` based on other inventory variables. A minimal version of my inventory looks like this:

```
[all:vars]
host_domain=example.com
ansible_host={{ inventory_hostname }}.{{ host_domain }}
ansible_user=root

[hosts]
host-a
host-b
```
Using delegation the `ansible_host` variable is not resolved correctly. The following playbook prints the hostname of `host-a` where it should print the hostname of `host-b` instead:
```
- hosts: host-a
  tasks:
  - command: hostname
    register: result
    delegate_to: host-b
  - debug:
      var: result.stdout
```
PR #56082 fixes this problem, this PR does not. 

Also neither of the PR's correctly handles interpreter discovery if `host-a` and `host-b` use different interpreter paths. So if for example on `host-a` ther variable `discovered_interpreter_python` is set to `/usr/bin/python3` and `host-b` uses `/usr/bin/python`, the above playbook would fail because `/usr/bin/python3` is not found on `host-b`.

**Comment by bcoca** [comment]
@equinox0815 my PR will not fix 'debug display' as it only changes the data passed into the connection and become plugins themselves. 

The problem with #56082 is that though it fixes some cases it still uses the original inventory_hostname data when no corresponding data from delegated host exists, this is still incorrect.

I'll look into the templating, but in general we are supposed to use the data from the original host for things, so 'inventory_hostname' should still be the original one.

**Comment by equinox0815** [comment]
@bcoca: It's not the debug display that is not working here. The debug module only prints  what is returned by the command module that calls `hostname` on a delegated host. I use this to check whether the command task is correctly delegated. Which is not the case with this PR. Of course this is because `ansible_host` itself is generated based on variables from the original host not the one that the task is delegated to.

**Comment by bcoca** [comment]
@equinox0815 understood, but your example was using debug, even if var had the value you wanted it would not be displayed there, but used in the connection itself.

That aside, I can confirm we conserve 'inventory_hostname' as it is only way to identify the current host, so I don't think we'll be able to give you the result you want due to how variables are lazily templated.

You can use `set_fact` to work around this, but not a variable declaration. I do have a couple of branches in which i toy with a 'non lazy' variable definition, which would enable this.

**Comment by equinox0815** [comment]
@bcoca hmmm, ok. Not sure if understand this correctly. Why would var hold the wrong value here? I thought the way my example works is proof that the command module actually wasn't called on the correct host right?
If so this means there is no way to override `ansible_host` based on any variables? That would be a bummer.
I assume this is also true for `ansible_port` or any other variable that is relevant when it comes to connecting to the host. Is there a list of variables that should be considered when it comes to this?
Also what about the interpreter discovery. Consider the following inventory:
```
[all:vars]
ansible_user=root

[hosts]
host-a ansible_host=host-a.exmaple.com
host-b ansible_host=host-b.example.com
```
Where `host-a` only has `/usr/bin/python3` and `host-b` only has `/usr/bin/python` which is in fact Python 2.x.
In this situation the same playbook as above does not work because the command task is now correctly delegated to `host-b` but cannot be executed since Ansible tries to call `/usr/bin/python3` which it cannot find on `host-b`. If this is not possible either doesn't this mean that host delegation and interpreter discovery will only work if both hosts happen to use the same interpreter path?

**Comment by bcoca** [comment]
it is not the 'wrong value', it is templated 'on demand' and when you 'demand' it during a delegated task, `inventory_hostname` ALWAYS refers to the original host the task ran for.

**Review by jimi-c — APPROVED** [review]

**Pull request merged**
