### PR TITLE
[cloud] ec2_vpc_nat_gateway: fix check mode

### PR DESCRIPTION
**Pull request by kimb**
##### SUMMARY

Fix check mode with already allocated eip.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ec2_vpc_nat_gateway

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 6473595238) last updated 2017/10/18 18:27:16 (GMT +300)
  config file = /home/blomkim/.ansible.cfg
  configured module search path = [u'/home/blomkim/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/blomkim/src/ansible/lib/ansible
  executable location = /home/blomkim/src/ansible/bin/ansible
  python version = 2.7.12 (default, Jun  2 2017, 15:18:54) [GCC 4.9.4]
```

##### ADDITIONAL INFORMATION

when use in a playbook as such:
```
  - ec2_vpc_nat_gateway:
      state: present
      region: "{{ region_long }}"
      subnet_id: "{{ subnet.public_a }}"
      eip_address: "{{ nat_eip }}"
      if_exist_do_not_create: True
      wait: True
    register: nat_gateway_facts
  - debug: var=nat_gateway_facts

```
in check mode this **fails** with the error:
```
fatal: [dpc010]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "allocation_id": null, 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "client_token": null, 
            "ec2_url": null, 
            "eip_address": "54.194.90.131", 
            "if_exist_do_not_create": true, 
            "nat_gateway_id": null, 
            "profile": null, 
            "region": "eu-west-1", 
            "release_eip": false, 
            "security_token": null, 
            "state": "present", 
            "subnet_id": "subnet-8916bed2", 
            "validate_certs": true, 
            "wait": true, 
            "wait_timeout": 320
        }
    }, 
    "msg": "EIP 54.194.90.131 does not exist", 
    "success": false
}
```
without check mode the play succeeds (as expected) with output:
```
ok: [dpc010] => {
    "nat_gateway_facts": {
        "changed": false, 
        "create_time": "2017-09-26T11:53:57+00:00", 
        "failed": false, 
        "msg": "NAT Gateway nat-0cf4f97a0ee5e87b0 already exists in subnet_id subnet-8916bed2", 
        "nat_gateway_addresses": [
            {
                "allocation_id": "eipalloc-e7232b85", 
                "network_interface_id": "eni-ceccbacf", 
                "private_ip": "10.58.0.91", 
                "public_ip": "54.194.90.131"
            }
        ], 
        "nat_gateway_id": "nat-0cf4f97a0ee5e87b0", 
        "state": "available", 
        "subnet_id": "subnet-8916bed2", 
        "success": true, 
        "vpc_id": "vpc-6861100f"
    }
}
```

##### WITH THESE CHANGES

After these changes check mode will succeed, with output:
```
ok: [dpc010] => {
    "nat_gateway_facts": {
        "changed": false, 
        "create_time": "2017-09-26T11:53:57+00:00", 
        "failed": false, 
        "msg": "NAT Gateway nat-0cf4f97a0ee5e87b0 already exists in subnet_id subnet-8916bed2", 
        "nat_gateway_addresses": [
            {
                "allocation_id": "eipalloc-e7232b85", 
                "network_interface_id": "eni-ceccbacf", 
                "private_ip": "10.58.0.91", 
                "public_ip": "54.194.90.131"
            }
        ], 
        "nat_gateway_id": "nat-0cf4f97a0ee5e87b0", 
        "state": "available", 
        "subnet_id": "subnet-8916bed2", 
        "success": true, 
        "vpc_id": "vpc-6861100f"
    }
}
```
And if the gateway doesn't exist, in check mode, it correctly reports as changed.

(I also suspect some of the other emitted facts are incorrect, but that's outside the scope of this pull request)
```
TASK [ec2_vpc_nat_gateway] *********************************************************************************************************************
changed: [dpc010]

TASK [debug] ********************************************************************************************************************
ok: [dpc010] => {
    "nat_gateway_facts": {
        "changed": true, 
        "create_time": "2017-10-18T15:44:05.347333", 
        "failed": false, 
        "msg": "NAT gateway nat-123456789 created", 
        "nat_gateway_addresses": [
            {
                "Allocation_id": "eipalloc-e7232b85", 
                "allocation_id": "eipalloc-1234567", 
                "network_interface_id": "eni-1234567", 
                "private_ip": "10.0.0.102", 
                "public_ip": "55.55.55.55"
            }
        ], 
        "nat_gateway_id": "nat-123456789", 
        "state": "available", 
        "subnet_id": "subnet-8916bed2", 
        "success": true, 
        "vpc_id": "vpc-12345678"
    }
}
```

### CODE REVIEW

**Comment by kimb** [comment]
But now some tests fail with:
`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

@s-hertel : Aren't these tests wrongly expecting check mode to cause the module not to contact AWS?

**Comment by s-hertel** [comment]
@kimb Fixing check mode is really helpful, thanks for opening the PR. :-)

If running with check mode the module can contact AWS for information but not make any changes.
So if I were to run
```
  - ec2_vpc_nat_gateway:
      state: present
      region: "{{ region_long }}"
      subnet_id: "{{ subnet.public_a }}"
      eip_address: "{{ nat_eip }}"
      if_exist_do_not_create: True
      wait: True
```
with check mode and the gateway doesn't exist yet, I would expect changed = True (to indicate that a change will happen when run without check mode even though nothing has actually changed) and a successful run and maybe some (perhaps hypothetical) details (like the gateway id).

So, for example, it's weird and seems wrong to me that the module would do this:
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_vpc_nat_gateway.py#L504-L505
In check mode we *should* describe the addresses - we just shouldn't create/modify/delete an address.

If I replace line 504 with 'if True:' so it always runs (obviously not an acceptable solution; just testing what happens if check mode can use that code path) I get the promising output:
```
changed: [localhost] => {
    "changed": true,
    "create_time": "2017-10-18T20:24:50.325080",
    "invocation": {
        "module_args": {
            "allocation_id": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "client_token": null,
            "ec2_url": null,
            "eip_address": "34.236.172.205",
            "if_exist_do_not_create": true,
            "nat_gateway_id": null,
            "profile": "shertel",
            "region": "us-east-1",
            "release_eip": false,
            "security_token": null,
            "state": "present",
            "subnet_id": "subnet-78421b31",
            "validate_certs": true,
            "wait": true,
            "wait_timeout": 320
        }
    },
    "msg": "NAT gateway nat-123456789 created",
    "nat_gateway_addresses": [
        {
            "Allocation_id": "eipalloc-b4dd5281",
            "allocation_id": "eipalloc-1234567",
            "network_interface_id": "eni-1234567",
            "private_ip": "10.0.0.102",
            "public_ip": "55.55.55.55"
        }
    ],
    "nat_gateway_id": "nat-123456789",
    "state": "available",
    "subnet_id": "subnet-78421b31",
    "success": true,
    "vpc_id": "vpc-12345678"
}
META: ran handlers
META: ran handlers

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

I hope that makes sense and isn't more confusing. So I think rather than supplying check_mode=False as you're doing here, this needs something else - since it looks like get_eip_allocation_id_by_address() and gateway_in_subnet_exists() should handle check mode and are failing to do so correctly.

**Comment by s-hertel** [comment]
^ Oops. Didn't mean to close that!

**Comment by kimb** [comment]
Thanks for helping me trying to figure this out.

This module seems strange to me. It's as if check mode is meant to be only used for testing the module, and not to actually check for changes. This seems most evident on line 487, where it is used to 'falsify the results'.

Firstly, the check mode false outputs in the module only make sense for testing:
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_vpc_nat_gateway.py#L219-L245
I think this is something that could be mocked to boto3 for integration testing, but doesn't belong in the actual module. Additionally, such extensive and complicated tests may just get cumbersome and provide little value. Could I just delete these lines and all tests relying on the falsification of results in check mode?

Secondly, functions such as get_eip_allocation_id_by_address() and gateway_in_subnet_exists() are read only operations, and as such shouldn't even need to know if check mode is in use, right?  As such, shouldn't I just remove the check_mode parameter from these functions?
(Even though this would in essence be like having 'if True' as you suggested, with the else branch just removed)

**Comment by kimb** [comment]
So basically:
1. remove result falsification in check mode
2. delete tests assuming said falsification

**Comment by s-hertel** [comment]
@kimb This looks good to me. The unit tests should probably be replaced with either unit test mocks or placebo recordings or integration tests. Are you interested in taking a stab at one of those? Otherwise I'll write some integration tests when I have time.

**Comment by kimb** [comment]
@s-hertel I can certainly try. Could you point me at an example of a well-written integration test?

**Comment by s-hertel** [comment]
No pressure. I think ec2_group is is probably the most well-tested module we have right now: https://github.com/ansible/ansible/blob/devel/test/integration/targets/ec2_group/tasks/main.yml.

**Comment by willthames** [comment]
More details on integration tests should you (correctly) choose to take that path ;) 

https://willthames.github.io/2017/07/17/so-you-want-to-test-aws-modules-for-ansible.html

**Comment by kimb** [comment]
@willthames Thanks, got the vagrant ansible testing box set up. I'm using a dedicated AWS account with IAM credentials set in `test/integration/cloud-config-aws.yml`.
But trying to run ec2_group tests:
`[vagrant@localhost ansible]$ ansible-test integration --docker -v ec2_group`
starts up fine, but fails at:
```
TASK [ec2_group : test state=present for ipv6 (expected changed=true)] *********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (InvalidParameter) when calling the AuthorizeSecurityGroupIngress operation: ipv6-ranges is not a valid parameter. IPv6 rules can only be specified for VPC security groups.
fatal: [localhost]: FAILED! => {"changed": false, "error": {"code": "InvalidParameter", "message": "ipv6-ranges is not a valid parameter. IPv6 rules can only be specified for VPC security groups."}, "msg": "Unable to authorize in for ip 64:ff9b::/96 security group 'ansible-test-localhost-18182520' - An error occurred (InvalidParameter) when calling the AuthorizeSecurityGroupIngress operation: ipv6-ranges is not a valid parameter. IPv6 rules can only be specified for VPC security groups.", "response_metadata": {"http_headers": {"connection": "close", "date": "Mon, 13 Nov 2017 13:30:34 GMT", "server": "AmazonEC2", "transfer-encoding": "chunked"}, "http_status_code": 400, "request_id": "1a0e6d4e-12c4-43dc-953a-6718ee823683", "retry_attempts": 0}}
```
Am I doing something wrong? As far as I know AWS doesn't support ipv6 without a vpc, but I'm hesitant to think this test has been broken all along.

**Edit**: This happens because my testing account is old enough to support EC2-Classic. See #32976

**Comment by kimb** [comment]
@s-hertel seems like I won't be timely writing tests for this...

**Comment by Akasurde** [comment]
Hi @kimb, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
