### PR TITLE
Backport #38707: ec2_vpc_route_table: Update matching_count parsing on find_subnets fu…

### PR DESCRIPTION
**Pull request by ZuZuD**
##### SUMMARY
- Backport of #38707 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
```
lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py
test/integration/targets/ec2_vpc_route_table/tasks/main.yml
```

##### ANSIBLE VERSION
```
2.5
```

##### ADDITIONAL INFORMATION
see [the original PR](https://github.com/ansible/ansible/pull/38707 "PR #38570")

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/64562/67/tests

This test is marked unstable, so the issue may or may not be related to the PR. I've restarted the tests.

**Comment by mattclay** [comment]
More failures: https://app.shippable.com/github/ansible/ansible/runs/64574/67/tests

Restarting again.

**Comment by mattclay** [comment]
Failing again: https://app.shippable.com/github/ansible/ansible/runs/64651/67/tests

The tests passed for me when run locally (without the modifications from this PR). I'll restart the tests.

**Comment by ZuZuD** [comment]
Finally, the tests passed thanks @mattclay 
Any idea why it reached the 300s timeout during subnet creation?

**Comment by mattclay** [comment]
@ZuZuD I don't know why the timeout occurred.

**Pull request merged**
