### PR TITLE
Added ec2_keypair module for #5003

### PR DESCRIPTION
**Pull request by willthames**
New ec2_keypair module with appropriate documentation
and useful options for addition/removal/recreation of a keypair.

### CODE REVIEW

**Comment by willthames** [comment]
I used the following testsuite:

```
- hosts: localhost
  connection: local
  vars: 
    dest: "~/.ansible/keys"
    name: "ansiXYZ"
    region: "ap-southeast-2"

  tasks:
  - action: ec2_keypair name='{{name}}' dest='{{dest}}' region='{{region}}' state='absent'

  - action: ec2_keypair name='{{name}}' dest='{{dest}}' region='{{region}}' state='absent'

  - action: ec2_keypair name='{{name}}' dest='{{dest}}' region='{{region}}'

  - action: ec2_keypair name='{{name}}' dest='{{dest}}' region='{{region}}'

  - action: file state=absent dest='{{dest}}/{{name}}.pem'

  - action: ec2_keypair name='{{name}}' dest='{{dest}}' region='{{region}}'
    ignore_errors: True

  - action: ec2_keypair name='{{name}}' dest='{{dest}}' region='{{region}}' force=True

  - action: ec2_keypair name='{{name}}' dest='{{dest}}' region='{{region}}'
```

**Comment by willthames** [comment]
Ah, this doesn't do keypair imports. I'll work on that.

**Comment by jctanner** [comment]
@willthames I think you and @zbal might want to collaborate: https://github.com/ansible/ansible/pull/5256

I'm grateful that so many people are contributing, but without discussing your development efforts on ansible-devel, race conditions like this are bound to happen.

**Comment by zbal** [comment]
I like the Force option - that's always something I thought about, but I'm not a big fan of reading and writing keys directly on the FS, it makes it harder to pipe actions together.

I see more this module as a ec2 key manager alone, that would then delegate to other modules the responsibility to read and write; ex. 
- read via `with_file` lookup plugin, 
- write via local action `line_in_file`

That would allow easy extension, and read/write to ldap for enterprise, or any other source / destination.

**Comment by willthames** [comment]
@zbal I do like your approach. I think I'll close this one and I'll just contribute tweaks as a pull request against your branch for a few minor cosmetic improvements around how AWS keys are handled etc (also there are some checks that you make that can be handled by the AnsibleModule framework out of the box).

**Pull request closed without merging**
