### PR TITLE
BSD UTC timezone is not always idempotent

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller <admiller@redhat.com>

##### SUMMARY
This fixes an idempotent issue in the BSD timezone code. (Problem originally outlined here: https://github.com/ansible/ansible/pull/40739#issuecomment-392211473)

When run a second time against the same FreeBSD host with `ansible-test integration timezone user --remote freebsd/11.1 -v` the tests will fail with:

```
TASK [timezone : ensure timezone reported as changed in checkmode] **********************************************************************
fatal: [testhost]: FAILED! => {
    "assertion": "timezone_set_checkmode.diff.before.name == 'Etc/UTC'",
    "changed": false,
    "evaluated_to": false
}
```

The before timezone is reported as `UTC` instead of the expected `Etc/UTC`. This happened because the files are compared with `filecmp` and both `UTC` and `Etc/UTC` are the same file, which means that the user could provide either and it would think no change was needed to the `/etc/localtime` symlink. That doesn't work because of how the rest of the module treats the file paths.

##### ISSUE TYPE

 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
timezone

##### ANSIBLE VERSION

```
ansible 2.7.0dev0 (timezone 1aff7579d9) last updated 2018/05/29 17:33:58 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admiller/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admiller/src/dev/ansible/lib/ansible
  executable location = /home/admiller/src/dev/ansible/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

### CODE REVIEW

**Comment by maxamillion** [comment]
cc @mattclay

**Review by mattclay — APPROVED** [review]
Excellent. Thanks for tracking this one down.

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by tmshn** [comment]
Sorry if I miss the point, but...the problem you are seeing is from here, right?
https://github.com/ansible/ansible/blob/v2.6.0a2/test/integration/targets/timezone/tasks/test.yml#L5-L16

Then, what you should fix is not strategy 2, but 3 or 4, I think.

**Comment by maxamillion** [comment]
@tmshn I don't follow, please elaborate.

**Comment by tmshn** [comment]
Let me clarify, I'm talking about the **latter step** of this configuration.

```yaml
# From test/integration/targets/timezone/tasks/main.yml
- name: set timezone to Etc/UTC
  timezone:
    name: Etc/UTC
  register: original_timezone

# From test/integration/targets/timezone/tasks/test.yml
- name: set timezone to Australia/Brisbane (checkmode)
  timezone:
    name: Australia/Brisbane
  check_mode: yes
  register: timezone_set_checkmode
```

The current timezone is set to `Etc/UTC` (which is same as `UTC`), and trying to change it into `Australia/Brisbane` (though it's check mode).

- `planned_zonefile == /usr/share/zoneinfo/Australia/Brisbane`
- `localtime_file == /etc/localtime (== /usr/share/zoneinfo/Etc/UTC == /usr/share/zoneinfo/UTC)`

Thus, `already_planned_state` must be `False`, and fallback to subsequent strategies.

--- 

I might misunderstand the situation, so feel free to point out.
And let me know if you know how to run integration test on my local machine.

**Comment by maxamillion** [comment]
I'm curious why you assert that `already_planned_state` much be `False` when the `filecmp.cmp` will return true if you compare `/usr/share/zoneinfo/Etc/UTC` to  `/usr/share/zoneinfo/UTC`

That test case itself wasn't triggering the failure, but the failure was occurring when it would run in succession with the user tests because the mix of `UTC` vs `Etc/UTC`.

Run `ansible-test integration timezone user -vvv` on a FreeBSD 11.1 machine as per the [integration tests docs](https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html).

**Comment by tmshn** [comment]
Sorry about my misunderstanding.
I ran the test on a FreeBSD 11.1 instance on GCE, and now know that the cause of the failure is coming from the _former_ step of the the configuration I wrote above, rather than the _latter_.
That's why you're talking about the difference of `/usr/share/zoneinfo/Etc/UTC` and `/usr/share/zoneinfo/UTC`.

However, still I don't see this pr really fixes the problem. I'm getting the same error on the same point, even using the latest `devel` branch.

**Comment by maxamillion** [comment]
@tmshn can you provide information about the failure you're seeing? This patch fixed the issue in CI, it's possible we have two problems around this.

**Comment by tmshn** [comment]
@maxamillion  I opened the new pr #41234, and am going to report more detailed information about this.
That is still WIP, but let's have a discussion there.

**Pull request merged**
