### PR TITLE
First attempt at standardizing DOCUMENTATION string

### PR DESCRIPTION
**Pull request by jpmens**
Must be first docstring/assignment in module file please, so we can use AST to retrieve. (I'm not sure how else to "find" that string...)

### CODE REVIEW

**Comment by mpdehaan** [comment]
Required options can't have a default, so "default: basename of url" doesn't make sense to me, still looking

**Comment by mpdehaan** [comment]
The rest of this looks good to me so far.  I would probably YAML-wrap the long lines.

We could also add a top-level requirements: [] section to list any libraries or command line tools that might be needed.  Like apt requires a python-apt, pip requires pip be installed first, etc.

Package names are distro specific so it would be mostly informational.

**Comment by jpmens** [comment]
Done. Tell me if I should re-submit Pull Request.

**Comment by mpdehaan** [comment]
looks like you might need to press update at least or something as I only see 97070e2 ?

**Comment by jpmens** [comment]
Done.

I was thinking of adding a `source: core` or something to allow for future `source: contrib` modules...

**Comment by mpdehaan** [comment]
Looking at this just a bit more.

Notes should proably be a list as well, to allow easy insertion of paragraph breaks when dumping to HTML.

I am thinking the same needs to be true for description.

The alternative would be newlines in the YAML, which I'm not sure how to do and it would probably be a bit messy.

Assuming that, I think we can go full speed ahead and document everything.

FYI -- in case I didn't make it clear already, there won't be a need to generate the rst/\* files as I am likely wanting to generate bootstrap HTML instead -- there's going to be a new documentation site probably in the next 2 or so weeks.   I'll take care of writing the thing that produces those docs.

Not a priority but just thinking about it -- One thing that might be nice is a script to generate module manpages for each module -- that's been requested before but not something we've been able to do.   Not sure what manpage section those would go in, but I assume it would be like man ansible-module-get_url etc ?

Update:  I may also need to do HTML links or inline styling in a few places.  If you are doing anything to generate LaTeX, you may want to try to throw away HTML tags <.*> or something similar.  There shouldn't be too much of that.

**Comment by jpmens** [comment]
Re notes & description: I agree to making lists -- will try.
Re HTML links & inline styling: **DISAGREE** with adding HTML: I'd mentioned that earlier: we need a language-agnostic markup for that. I was thinking along the lines of Markdown or rST or something easy which can be "translated" by either Python or Jinja2.

**Comment by mpdehaan** [comment]
Yeah, point.   That could get ugly.

So we could just add a:

see_also:
    - link_name1: link_address1
    - link_name2: link_address2

and only the webapp could use it and render those after the examples.  That
may be enough.     Should be ok.

The idea of using Markdown or rST inside of YAML would hurt my brain :)

**Comment by mpdehaan** [comment]
Merged, feel free to decorate any of the other modules, I can add stuff to the YAML as needed.  Looks very future proof to me now.

Thank  you very much for figuring this all out.  This is great.

**Pull request merged**
