### PR TITLE
cron feature and test cases

### PR DESCRIPTION
**Pull request by dsummersl**
squashed pull request

### CODE REVIEW

**Comment by mpdehaan** [comment]
Great thanks, this is in queue for testing!

**Comment by mpdehaan** [comment]
Ok, a few questions/things.

I see you've got some history from your subversion branch (where we didn't take the subversion tests earlier) mixed in.   Please remove that as we didn't want tests to depend on SVN or network access.

The question part -- I see you have this in there:

```
    result = self._run('cron', [ "name=\"job 1\"", "minute=1", "hour=1", "day=1", "job=\"ls -alh > /dev/null\"" ])
```

To me, that seems to imply it would be editing the users actual crontab file while they are running the test.   This seems to be undesirable and we'd want a way to specify the crontab file directly as an override for test purposes?

Anyway, let me know -- and see about tweaking the test.  The module seems pretty solid!

**Comment by dsummersl** [comment]
Hey,

Sorry about the SVN stuff, np...

Yeah the cron tests actually run against the cron - I added a setup/teardown to the tests to backup and restore the original cron. But I can change that to specify some kind of 'testing mode' via the module parameter list if you like.

**Comment by mpdehaan** [comment]
I'd suggest a "crontab=<filename>" parameter, defaulting to the normal
expected cron path?

**Comment by dsummersl** [comment]
I'm guessing you mean as in crontab=/var/spool/cron/crontab/crontabs/<user>? That seems a but unsafe: validation is handled by crontab whereas direct poking of files wouldn't be...

I'm realizing both my tests are basically getting excluded b/c they rely on network or svn/cron to do the actual testing, and realizing I probably shouldn't be testing them in TestRunner (which is intended to test...TestRunner :) ?). I should be testing these in their own unit tests, where I can then mock out the network/cron/svn calls as needed. Been looking into this a little bit and it looks like I could do this if I make a TestCron.py that:
- generates the cron module with its boilerplate
- **import** my module, mock out my subprocess calls

Would that be an acceptable unit test for you? If so I'd like to convert the subversion tests to that as well...

**Comment by mpdehaan** [comment]
On Sun, Sep 30, 2012 at 7:51 AM, Dane Summers notifications@github.comwrote:

> I'm guessing you mean as in crontab=/var/spool/cron/crontab/crontabs/?
> That seems a but unsafe: validation is handled by crontab whereas direct
> poking of files wouldn't be...

I'd be happier just removing the unit test in that case for now.   The
module won't evolve much and the most important things are seldom hit in
the units.

> I'm realizing both my tests are basically getting excluded b/c they rely
> on network or svn/cron to do the actual testing, and realizing I probably
> shouldn't be testing them in TestRunner (which is intended to
> test...TestRunner :) ?). I should be testing these in their own unit tests,
> where I can then mock out the network/cron/svn calls as needed. Been
> looking into this a little bit and it looks like I could do this if I make
> a TestCron.py that:
> - generates the cron module with its boilerplate
> - _import_ my module, mock out my subprocess calls
> 
> The test isn't a requirement for inclusion, but I've become a pretty big
> fan of flexmock lately.  However, the way modules get executed by ansible
> in SSH mode makes mocking out module code rather difficult. I think that's
> ok as long as you've exhaustively manually tested it.

It's more of an integration test thing.

> Would that be an acceptable unit test for you? If so I'd like to convert
> the subversion tests to that as well...

Let's get cron in there later and look at this after.
- It should probably be possible to insert an extra function after the
  boilerplate injected stuff to replace certain functions, yes.

**Comment by dsummersl** [comment]
Okay, I've taken out the test for now. And I'll take a look at flexmock and module testing in general on another branch for a future pull request.

**Comment by dsummersl** [comment]
...taken out the tests, rather...

**Comment by mpdehaan** [comment]
Thanks... Please resubmit this without the removal of the tests, just so it contains the good parts.  So basically you get to squash again :)

Also see what we are doing with module documentation and copy some of the other modules to add a documentation header -- this is going to be required for all modules now and prevents you from having to generate a seperate pull request to add documentation for the cron module (so it's a pretty cool thing really).

**Comment by dsummersl** [comment]
will do!

**Pull request closed without merging**
