### PR TITLE
Linode: docs note for py3 limitation and deprecated API

### PR DESCRIPTION
**Pull request by decentral1se**
##### SUMMARY

Two documentation fixes:
  * Let people know about linode-python py2 limitation (see https://github.com/ansible/ansible/issues/44695)
  * Let people know about which API the module uses

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

linode

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by decentral1se** [comment]
Realising I probably should have merged this all in with https://github.com/ansible/ansible/pull/44719 as well ...

A lot of pull requests around here ;)

**Comment by decentral1se** [comment]
Bump Bump Bump :shark: :shark: :shark:

**Comment by decentral1se** [comment]
@InTheCloudDan / @rwaweber can I get this one on the big merge train in the sky?

**Comment by InTheCloudDan** [comment]
shipit

**Comment by rwaweber** [comment]
@lwm you should be able to comment with a “shipit” to get the attention of ansibot now that you’re a maintainer

**Comment by decentral1se** [comment]
shipit

:champagne:

**Comment by decentral1se** [comment]
bot_status

**Comment by decentral1se** [comment]
bot_broken

I'm new around here but I see **2** `shipits` here and the bot says only **1**?!

This PR is lurking here for 18 days now. I can't seem to get it merged ...

**Pull request merged**
