### PR TITLE
Accept status code from a list of valid codes.

### PR DESCRIPTION
**Pull request by ghost**
As discussed on the mailing list, it is desirable that that uri module can accept any one of a list of http status codes, rather than just one. 

https://groups.google.com/forum/#!msg/ansible-project/ksesTAi2LEM/rNDneEKBQIkJ

### CODE REVIEW

**Comment by ghost** [comment]
And here is a usage example:

```
---
- hosts: all
  sudo: yes
  pre_tasks:
  tasks:
   - name: create the admin user (can repeat multiple times)
     action: uri
         url=http://localhost:8080/riak-cs/user
         method=POST
         body='{"email":"admin12@admin.com","name":"admin12"}'
         HEADER_Content-Type=application/json
         status_code=201,409
     register: create_admin_result
     ignore_errors: True
```

**Comment by mpdehaan** [comment]
So this has some debug stderr in here that needs to be removed.

Romeo Theirault was also going to add a new type called "int_list" to do casting, if not added, I would at least be sure to cast all members to ints.

**Comment by ghost** [comment]
Well spotted, and good points. How does this look now?

**Comment by rrtj3** [comment]
Hi @picsolvebryan, thanks for making a go at this. @mpdehaan, this may be a good initial commit until I can get around to sending in the pull request for the int_list type. This should work, but will obviously error if someone passes in something that's not a number.

**Comment by binarytemple** [comment]
Thanks guys, yes @romeotheriault I agree. It will probably be better to have this working now, and then add the stronger type guarantee later.

**Comment by binarytemple** [comment]
@romeotheriault @mpdehaan Is it possible to merge this pull request? I'd like to get some Ansible Galaxy roles out there.

**Comment by mpdehaan** [comment]
Merged, thanks!

**Pull request merged**
