### PR TITLE
Add creates= and removes= to the script: action

### PR DESCRIPTION
**Pull request by jeromew**
After a discussion on ML.
This patch adds 
- creates=
- removes=

on script module

### CODE REVIEW

**Comment by jeromew** [comment]
the PR has been rebased on 01/01/2014 + the 2 parameters have been documented as appearing in 1.5

please tell me if there anything I can do

**Comment by jeromew** [comment]
the PR has been rebased on 17/01/2014

**Comment by jeromew** [comment]
the PR has been rebased on 11/02/2014

**Comment by risaacson** [comment]
@jeromew, Can you add some documentation to library/commands/script that would cover these changes along with examples?

**Comment by mpdehaan** [comment]
This is minor but there are also some minor indent errors around

```
 +                        result=dict(
 +                            skipped=True,
 +                            msg=("skipped, since %s exists" % creates)
 +                            )
 +                        )
```

Basically indent skipped and msg also and this is fine.

**Comment by jeromew** [comment]
@risaacson oh I see now examples have been lost through my squash operations. I'll update the PR.

**Comment by jeromew** [comment]
@risaacson , @mpdehaan PR has been updated hopefully meeting your expectations

**Comment by jeromew** [comment]
@risaacson do you have commit privileges on ansible ? I am ready to do what it takes so that this PR does not wait another 3 months ;-)
Tell me is there is anything I can do that is missing apart from the doc I added and the reformating request from mpdehaan.

Thanks

**Comment by risaacson** [comment]
@jeromew I do.
Looking at this now.

**Comment by risaacson** [comment]
@jeromew this is merged. I did a little bit of work to make sure that the new functionality is in our integration tests. If you haven't seen much about them take a look as it is good stuff.

Thanks for your PR and patience as we got it in.

**Pull request merged**
