### PR TITLE
[stable-2.10] Add AlmaLinux to the family of Red Hat-like operating systems (#73541)

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Backport of #73541 for Ansible 2.10.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/module_utils/facts/system/distribution.py`

### CODE REVIEW

**Comment by sivel** [comment]
In the same vein as our thinking with interpreter discovery, is this safe for backport?  Could someone be relying on the prior behavior to identify AlmaLinux?

**Comment by samdoran** [comment]
Potentially. It's a very new distro, so maybe it hasn't been around long enough for people to rely on whatever it is being identified as currently.

In general I see misidentifying an OS as a bug.  I'm not adamant about backporting this, though.

**Comment by rgroux** [comment]
hello @all

why this merge is blocked? it can be useful to have this patch backported to previous release, and the impact in the code is very small.

Thanks
/Richard

**Comment by samdoran** [comment]
@rgroux This PR is not blocked. We merge PRs close to release time. We make new releases about every four weeks. I would expect the next round of releases in mid March.

**Comment by rgroux** [comment]
> @rgroux This PR is not blocked. We merge PRs close to release time. We make new releases about every four weeks. I would expect the next round of releases in mid March.

Thanks for all, and sorry for the confusion.

**Pull request merged**
