### PR TITLE
acme_certificate: add select_chain option

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This option allows to choose an alternate chain (when provided) depending on some criteria on the certificates in the chain. Can be for example used to select a chain with a more compatible root certificate (i.e. corresponding to the cross-signed intermediates in case of Let's Encrypt), if the CA provides such chains.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
acme_certificate

### CODE REVIEW

**Comment by felixfontein** [comment]
Will rebase once #62381 is merged.

**Comment by felixfontein** [comment]
Still rebased now since all tests fail when there's a conflict.

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
Restarting tests

**Review by resmo — APPROVED** [review]
nice work!

shipit

**Comment by felixfontein** [comment]
@resmo thanks a lot for reviewing this! :)

rebuild_merge

**Pull request merged**
