### PR TITLE
feat: support postgres 10 in azure_rm_postgresqlserver

### PR DESCRIPTION
**Pull request by palmerabollo**
##### SUMMARY
Add support to Azure Postgres 10.x (see [azure official docs](https://docs.microsoft.com/lv-lv/azure//postgresql/concepts-supported-versions)).

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
azure_rm_postgresqlserver

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = None
  configured module search path = [u'/Users/xyz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:31:33) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION

See azure portal screenshot

screen shot 2018-10-13 at 11 08 08

### CODE REVIEW

**Review by ryansb — APPROVED** [review]

**Comment by yuwzho** [comment]
shipit

**Review by yuwzho — APPROVED** [review]

**Comment by Fred-sun** [comment]
@yuwzho @yungezz Could you help confirm how the PR going? need go ahead to merge or further review? Thanks!

**Review by zikalino — APPROVED** [review]

**Comment by zikalino** [comment]
perhaps version should not be a choice at all?

**Comment by palmerabollo** [comment]
@zikalino agree, otherwise the module will be outdated every few months. 

In the AWS alternative ([rds](https://docs.ansible.com/ansible/devel/modules/rds_instance_module.html) and [rds_instance](https://docs.ansible.com/ansible/devel/modules/rds_instance_module.html)), the engine version is open. If not specified, it defaults to the current Amazon RDS default engine version.

**Comment by palmerabollo** [comment]
Why is still https://docs.ansible.com/ansible/latest/modules/azure_rm_postgresqlserver_module.html outdated? Isn't it autogenerated from source code?

**Pull request merged**
