### PR TITLE
Zabbix: new module zabbix_user_info

### PR DESCRIPTION
**Pull request by sky-joker**
##### SUMMARY
This pull request adds a module to get information of Zabbix user.
Tested with Zabbix Server(3.0, 3.2, 3.4, 4.0, 4.2).

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
zabbix_user_info

##### ADDITIONAL INFORMATION
This pull request reflected the following advice.
https://github.com/ansible/ansible/pull/56968

### CODE REVIEW

**Review by D3DeFi — APPROVED** [review]
good job! :)
-label needs_triage
shipit

**Review by D3DeFi — APPROVED** [review]
shipit

**Review by rubentsirunyan — APPROVED** [review]
shipit

**Comment by sky-joker** [comment]
Thank you @goneri for merging!

**Pull request merged**
