### PR TITLE
fix non location error

### PR DESCRIPTION
**Pull request by yuwzho**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_subnet

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by Fred-sun — COMMENTED** [review]
[line 286](https://github.com/ansible/ansible/pull/52312/files#diff-b30eae795f473c7c9a9f699d2da5eb48L286) ,When the locations parameter is not configured, it is the location of the resource group where the default subnet is to be located

**Comment by yuwzho** [comment]
@Fred-sun Thanks for pointing it out. Please re-try

**Comment by Fred-sun** [comment]
@yuwzho Thanks for your update, I have tried and get PASS result.

**Comment by Fred-sun** [comment]
@yungezz @zikalino Could you help review this PR when you're available? Thanks!

**Review by yungezz — APPROVED** [review]

**Pull request merged**
