### PR TITLE
integration tests for docker_container

### LINKED ISSUE #44679: docker_container should have integration tests
##### SUMMARY
@pilou- refactored some docker integration tests in #42306, with one aim being to add integration tests also for `docker_container`. This work should be continued so there are actually some integration tests.

Just opening this issue so we won't forget about it, and to keep track in case someone wants to start working on it :)

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.7.0
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This mimicks the tests for `docker_swarm` and `docker_secret`, and is derived from https://github.com/felixfontein/ansible-docker_container-test.

Fixes #44679.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by felixfontein** [comment]
That was easier than I thought :)

**Review by kassiansun — APPROVED** [review]

**Comment by kassiansun** [comment]
shipit

**Comment by felixfontein** [comment]
I rebased to `devel` and included a regression test for #45700.

**Comment by felixfontein** [comment]
@kassiansun I guess you have to re-shipit this!

**Comment by felixfontein** [comment]
@mattclay Can you take a look at this?

**Comment by gundalow** [comment]
bot_status

Confused why the `test` label hasn't been added

**Comment by kassiansun** [comment]
shipit

**Comment by felixfontein** [comment]
Rebasing to see whether there are conflicts between these tests and the docker_swarm/docker_stack tests (similar to the problems from yesterday).

**Comment by ghost** [comment]
[Success](https://app.shippable.com/github/ansible/ansible/runs/84605/summary) for [this commit](https://github.com/ansible/ansible/pull/45747/commits/1bacfba7e8fd40a13bf1e57173b62803d36191f9) indicates that there are no conflicts :)

**Comment by willthames** [comment]
rebuild_merge

**Comment by ghost** [comment]
@kassiansun @willthames Thanks for reviewing and merging! :)

**Pull request merged**
