### PR TITLE
better error on bad playbook encoding

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

better error message on bad playbook encoding
```python
ERROR! Unexpected Exception: 'utf8' codec can't decode byte 0xf1 in position 44: invalid continuation byte
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 81, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 77, in _load_playbook_data
    ds = self._loader.load_from_file(os.path.basename(file_name))
  File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 120, in load_from_file
    file_data = to_text(b_file_data, errors='surrogate_or_strict')
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/_text.py", line 232, in to_text
    return obj.decode(encoding, errors)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 44: invalid continuation byte
```
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

playbook
##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Review by jctanner — APPROVED** [review]
shipit

**Comment by abadger** [comment]
shippable failure is from talking to a Fedora package repository.  Problem cleared up on subsequent run.  So unrelated to this change.

**Comment by abadger** [comment]
A bugfix for a non-major, non-regression is a candidate for 2.4.1 instead of 2.4.0.  I don't see any way that this patch makes things worse, though (Was a traceback before. If something is wrong with the new code it would be a traceback in error handling of that traceback).  So I cherry-picked for 2.4.0rc4.

**Comment by abadger** [comment]
Note:  Probably should do 
``` python
raise AnsibleParserError("Could not read playbook (%s) due to encoding issues: %s" % (to_native(file_name), to_native(e)))
```

Try seeing what happens if file_name is u'café' on Python2 to see why.

**Pull request merged**
