### PR TITLE
Fix and add more tests for method option change

### PR DESCRIPTION
**Pull request by obourdon**
##### SUMMARY
Fix for issue [#45761](https://github.com/ansible/ansible/issues/45761)

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/107500/9/tests

**Comment by obourdon** [comment]
@mattclay yes I saw that when it occurred yesterday, currently working on this. Fix should be ready later today

**Comment by obourdon** [comment]
@hryamzik @gundalow Could you please review and merge? Many thanks in advance

**Comment by hryamzik** [comment]
LGTM

**Review by resmo — APPROVED** [review]
shipit

**Comment by gundalow** [comment]
@obourdon thank you for this bug fix and extending the tests!
@hryamzik @resmo thank you for the reviews. 
Merged into `devel` for release in Ansible 2.8

**Comment by obourdon** [comment]
@gundalow @hryamzik @resmo many thanks for the reviews and merge

**Pull request merged**
