### PR TITLE
Add big switch big mon inline chain modules

### PR DESCRIPTION
**Pull request by tedelhourani**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ansible-modules-extras/network/bigswitch/bigmon_chain.py
ansible-modules-extras/network/bigswitch/bigmon_chain_endpointpair.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel f508d29c16) last updated 2016/11/25 17:56:01 (GMT -700)
```

##### SUMMARY

```

```

### CODE REVIEW

**Comment by tedelhourani** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3549

**Comment by gundalow** [comment]
Hi,

I see you've got a note that you require Python 2.6+ from 
From https://github.com/ansible/ansible-modules-extras/pull/3549 this seems to about dealing with exceptions, the following guide should help you write this in a Python 2.4+ compatable way

http://docs.ansible.com/ansible/dev_guide/developing_modules_python3.html#exceptions


Thanks

**Comment by tedelhourani** [comment]
Thanks, I removed the >= 2.6 requirement. And the code now follows the compatibility recommendation in

http://docs.ansible.com/ansible/dev_guide/developing_modules_python3.html#exceptions

**Comment by privateip** [comment]
Please only submit a single module per PR

**Pull request closed without merging**
