### PR TITLE
Allow firmware update for (SP, ACP, Shelf, Disk)

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Allow firmware update for (SP, ACP, Shelf, Disk)
##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
- na_ontap_firmware_upgrade.py 

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]
shipit

**Review by thedoubl3j — APPROVED** [review]
Looks good. Test coverage % is good, docs look. lgtm

**Comment by thedoubl3j** [comment]
@carchi8py looks like some CI stuff moved around. looks like you guys are missing some boilerplate stuff

**Comment by carchi8py** [comment]
@thedoubl3j thanks, fixed it.

**Review by lonico — APPROVED** [review]
shipit

**Pull request merged**
