### PR TITLE
Simple augeas module

### PR DESCRIPTION
**Pull request by paluh**
This module uses augeas python bidings so it adds additional requirements.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Nice, very much looking forward to testing this out.

Previously had some reservations, but lineinfile is fiddly and I'd
definitely prefer this kind of thing for most use cases!

Great!

**Comment by paluh** [comment]
I want to add some debugging tips - should I place them in 'description' section?

**Comment by mpdehaan** [comment]
EXAMPLES might be good for that.   It's a free form text field and is much
easier than embedding examples in the DOCUMENTATION string.

I still need to switch all the remaining modules to use it.

**Comment by mpdehaan** [comment]
Any suggestion on what the syntax is to use this on an arbitrary INI file to add a new value below a section header?

For instance, if I wanted to add a new ansible server to the webservers group?

I tried a few things and it returns "success=True" without making some changes, so it looks like we _might_ want to beef up the error handling.

Still very interested, let me know what you think about the error handling.  It seems I can feed it paths to files that don't exist and it returns success.

**Comment by paluh** [comment]
> Any suggestion on what the syntax is to use this on an arbitrary INI file to add a new value below a section header? (...)  For instance, if I wanted to add a new ansible server to the webservers group?

There is a little problem with inventory files as they are not really `.ini` files. Inventory files have custom format which accepts hosts lists as section records (not usual 'key=value' lines) with arguments list (parsed with shell escaping). I think that it requires separate parser, but I'm not sure if I'm able to write one (and if I have enough time now). I will propose really **basic** augeas lens - I'm assuming that you have `augeas` module copied into `library` directory, so please copy it there or work on my fork:
- here is simple inventory parser, which handles only **small** subset of inventory files - no comments, no hosts variables, no shell quoting etc. (I'm not augeas master so for sure it can be written better) - let's save it in current directory in `./inventory.aug`:
  
  ```
  module Inventory =
    autoload xfm
  
    let entry_re = /[A-Za-z][A-Za-z0-9._:\-]+/
    let title = IniFile.title entry_re
    let entry_list = counter "elem"
        . Build.opt_list [ seq "elem" . store entry_re ] Util.doseol+
    let lns = Util.doseol* . [ title . Util.doseol* . entry_list . Util.doseol+ ]*
  
    let filter = incl "*.ini" . Util.stdexcl
    let xfm = transform lns filter
  ```
- here are some tests which shows what above parser can parse (to run tests just copy below code into `test_inventory.aug` and run: `$ augparse -I . test_inventory.aug`. If there is no error output, all tests pass.):
  
  ```
  module Test_inventory =
  
    let lns = Inventory.lns
  
    (* empty group not allowed *)
    test lns get "[webhosts]\n" = *
  
    (* one element group *)
    test lns get "[webhosts]\nweb1.example.com\n" =
      { "webhosts"
          { "1" = "web1.example.com" }
      }
  
    (* multiple elements group *)
    test lns get "[webhosts]\nweb1.example.com\nweb2.example.com\n" =
      { "webhosts"
          { "1" = "web1.example.com" }
          { "2" = "web2.example.com" }
      }
  
    (* multiple elements group *)
    test lns get "[webhosts]  \nweb1.example.com  \nweb2.example.com\n[dbhosts]  \ndb1.example.com  \ndb2.example.com\n" =
      { "webhosts"
          { "1" = "web1.example.com" }
          { "2" = "web2.example.com" }
      }
      {  "dbhosts"
          { "1" = "db1.example.com" }
          { "2" = "db2.example.com" }
      }
  
    (* handle empty lines *)
    test lns get "[webhosts]  \nweb1.example.com  \n     \n\nweb2.example.com\n" =
      { "webhosts"
          { "1" = "web1.example.com" }
          { "2" = "web2.example.com" }
      }
  
    (* add new host to webhosts group *)
    test lns put "[webhosts]\nweb1.example.com\nweb2.example.com\n" after
     set "/webhosts/01" "web3.example.com"
     = "[webhosts]\nweb1.example.com\nweb2.example.com\nweb3.example.com\n"
  ```
- let's create really simple inventory file `./hosts.ini`:
  
  ```
  [webservers]
  webserver1.example.com
  webserver2.example.com
  ```
- now we can try our ansible module against it:
  
  ```
  # this should show `hosts.ini` if our example inventory file was parsed correctly
  /path/to/ansible/hacking/test-module -m library/augeas -a 'loadpath="./" root="./" command=match path="/files/*"'
  
  # this should print inventory sections
  /path/to/ansible/hacking/test-module -m library/augeas -a 'loadpath="./" root="./" command=match path="/files/hosts.ini/*"'
  
  # this should print inventory webservers section content
  /path/to/ansible/hacking/test-module -m library/augeas -a 'loadpath="./" root="./" command=match path="/files/hosts.ini/webservers/*"'
  
  # this should append new server to webservers section
  /path/to/ansible/hacking/test-module -m library/augeas -a 'loadpath="./" root="./" command=set path="/files/hosts.ini/webservers/01" value="new.example.com"'
  ```

> I tried a few things and it returns "success=True" without making some changes, so it looks like we might want to beef up the error handling. (...) let me know what you think about the error handling. It seems I can feed it paths to files that don't exist and it returns success.

Good catch - I've found this problem too. I'm not sure how we can verify this kind of errors, but I'm sure that we **should** inform user about all parsing problems (including wrong/missing file paths). After quick investigation it seems that `augeas.Augeas` doesn't raise any exception in case of `set` or `save` on non existing file/path, so I don't know if it will be easy or possible to fix this without module API changes (an alternative API can take file path and config subpath separately).

**Comment by mpdehaan** [comment]
Yeah even a basic INI file I found it would not produce any errors when
trying to manipulate it.

Or even if the destination file was missing.

I'm worried about including this if it raises more problems than it fixes,
just due to the general complexity of augeas lenses and quality of error
handling.

Thoughts welcome, not rejecting the idea, just concerned.

**Comment by paluh** [comment]
INTRO

It seems that in augeas API since two years (exactly since 2011-02-06: https://github.com/lutter/augeas/commit/3935d62d020413e77a3c0b8e358b32e58c3954ff) there is `aug_span` function which returns detailed information about passed `context` (path to a variable). This information contains precise information about variable/value definition: filename, line numbers etc.

On the other hand in official python bindings support for this functionality has been introduced just after latest release (latest release `python-augeas 0.4`:  http://git.fedorahosted.org/cgit/python-augeas.git/log/ - "Add span API call to match C API Francis Giraldeau  2011-03-31"), so most distributions doesn't contain this method.

For example on my server machines (Debian wheezy) and on my latop (Arch) libaugeas has `aug_span` function but python bindings doesn't expose it.

SUMMARY

I've added support for file existence validation (if you pass path but augeas doesn't find any file for it module will indicate this failure). My implementation doesn't break backward compatibility (module can be used with older versions of libaugeas too) and is implemented as follows:
- if there is `span` method in `Augeas` class there is nothing to do
- if augeas.match('/augeas/span') is not empty it means that libaugeas exposes `aug_span` and we can extend `Augeas` class with `span` method (I've copied original implementation)
- if `libaugeas` doesn't support desired functionality validation can be turned off through `validate_filepath` param

TODO
- I'm going to add additional validation for `set` command (check whether value was saved correctly)
- I'm going to change naming convention `s/path/context/` as it is closer to augeas standards

PROPOSITIONS/QUESTIONS ;-)

What do you think?

**Comment by paluh** [comment]
TODO
- Change naming convention s/path/context/ as it would be closer to augeas standards
- Extend API: add `lens` and `incl` params (they will mirror logic from puppet module: http://projects.puppetlabs.com/projects/1/wiki/puppet_augeas#Loading-generic-lenses-for-non-standard-files)

**Comment by mpdehaan** [comment]
Thanks!

I'd like to get some more folks to help review and test, can you post this to the mailing list.

**Comment by paluh** [comment]
Ok, I think this is reasonable suggestion, because I'm not entirely sure if proposed API can cover all common use cases.

I'm going to finish my TODO's (in next two days), so API and code will be cleaned up and then I'm going to ask about opinions on mailing list.

**Comment by paluh** [comment]
I'm going to finish additional quite big issue before I'll post any mailing list announce.

I have to add multiple commands support (similar to puppet augeas API) without it this, module is half useful:

```
augeas commands="set /files/etc/hosts/01/ipaddr 192.168.0.1
                 set /files/etc/hosts/01/canonical pigiron.example.com
                 set /files/etc/hosts/01/alias[1] pigiron
                 set /files/etc/hosts/01/alias[2] piggy"
```

I'm going to take inspirations straight from puppet module: https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/augeas/augeas.rb.

**Comment by mpdehaan** [comment]
Ok, sounds like this is not finished.

Please submit it when you think it is rock solid and has a bunch of examples of how to use it, and then I'm happy to include it.

In general, we don't take pull requests and get things working after they are in tree, we want to see them fixed up first.

Hope this is ok and let me know when you are ready.

Thanks!

**Comment by paluh** [comment]
Ok, thats clear! I've just started with simple module (which I had been using extensively), but it's obvious that I should cover more sophisticated use cases + more verbose error handling. I hope I will find some time soon to finish this work.

**Comment by paluh** [comment]
Hi,

I've implemented all my TODO tasks and additional extensive error handling. Please notice that my module is mainly augeas error reporter now :-P and it provides support for reporting missing files and augeas errors (I mean listing/filtering "/augeas//errors" in error reports). Of course there is a lot of space for additional extensions, but I'm afraid that I'm not able to verify/test alone what is missing.

Could you reopen this pull request, so I can post some information to mailing list about this proposition?

**Comment by mpdehaan** [comment]
Ok, it sounds like all the other modules are equally terrible.

I'm inclined to not include it then.

**Comment by mpdehaan** [comment]
If you are saying yours are better, that's great, maybe I misread.

Still given feature freeze is tomorrow it looks like this would be a 1.2
thing.

**Comment by paluh** [comment]
Yes, I've tried to say that my module implements better error handling than you can find in (other tools) (sorry for my English ;-)) (it's strange, because some parts of my previous comment are missing... probably I've deleted it accidentally).

I know that there is a lot of space for additional extensions (more functionality and debugging capabilities) but I think that (as you suggested earlier) it should be revisited and evaluated/tested by wider audience.

In current state I've really focused on simplicity and error handling :-P

> Still given feature freeze is tomorrow it looks like this would be a 1.2 thing.

That's even better - I think this API requires some discussion.

**Comment by mpdehaan** [comment]
Let's not discuss other CM tools in the bug tracker, thanks.

**Comment by mpdehaan** [comment]
Yeah, sure, let's discuss what it needs to do in 1.2 timeframe.

My concern is creating a module that is so confusing it makes the list about "how do I get augeas to not suck" and that would just be distracting.

In most cases, templates are a far better way to manage config files, and they rarely cause any questions to come up.

Aug is just useful for when people can't centrally manage properly, which is not really a production server issue, it's more of a desktop issue.

**Comment by paluh** [comment]
> Aug is just useful for when people can't centrally manage properly, which is not really a production server issue, it's more of a desktop issue.

It really depends - consider simple use cases:
- two independent modules/playbooks want to add some values to existing list in configuration file (for example `user.yaml`  and `ssh_tunnel.yaml` want to add entry to `AllowedUsers` in `sshd_config`)
- you don't want to replace whole configuration but only modify it a bit. Lets say that you want to create `playbook` which is able to configure single network bridge in `/etc/network/interfaces` and use it multiple times

Augeas allows you quite easily write parsers and **test** them (as I've posted above - simple lens with tests). And what is more important it contains **a lot** of predefined lenses.

Of course if you think that augeas can create more problems then solve, I should stop developing this module now ;-) . I want to create module which only simplifies access to this tool (really simple API and error reporting) - nothing more. And of course I don't want you to merge this if there are any doubts about it ;-)

**Comment by mpdehaan** [comment]
The assemble module can actually handle the "two independent playbooks"
case pretty well.

Though Ansible's approach is rather that would set variables and try to use
one template, versus over-abstracting and making it harder to understand
what your destination file actually is.

Even if this is not something we include in core, we could still link to it
on the contrib page.

I think whether that is possible is mainly a function of how many examples
you can include, and what the error handling behavior is like.

**Comment by paluh** [comment]
> I think whether that is possible is mainly a function of how many examples
> you can include, and what the error handling behavior is like.

I've included four examples (one simple and three more sophisticated) in module documentation.

I've implemented following validation and error handling support:
- missing files - verify if given path matches any file and in case of missing file try to find closest match (as I've described above I was forced to extend `Augeas` class to accomplish this with current python-augeas official version)
- path validation (some paths can fail on even on `match` call, some are failing during `save`)
- in case of any error try to present appropriate `/augeas//error` nodes (all augeas error reports are kept in `/augeas` subtree)

I've removed `set` result validation as it was mainly heuristic, but I'm open for suggestions.

If you think that it is not enough for stable/core module I'm afraid that I'm not able to match you requirements. I hope that it is not due to my broken approach or my API design decisions.

> Though Ansible's approach is rather that would set variables and try to use
> one template, versus over-abstracting and making it harder to understand
> what your destination file actually is.

So maybe I've wrong point of view. I don't want to modify ansible approach/philosophy but I though that parameterized playbooks are designed for such reuse/modularization.

**Comment by paluh** [comment]
To stop discussion under this outdated pull request I've created separate repository for this module: https://github.com/paluh/ansible-augeas. I'm going to send some words to mailing list in a few days.

**Comment by mpdehaan** [comment]
Ok, thanks, ML thread would be good!

**Comment by drzraf** [comment]
@paluh @bcoca, IMHO [augeas](https://github.com/paluh/ansible-augeas/) module  is one of the most useful out-of-tree module pointing to the best sysadmin practices (and a RedHat impulsed software (!)).
Can we get this issue reopened and, why not, have the module merged if @paluh agree?

**Comment by drzraf** [comment]
@mpdehaan care to reopen/reconsider? @paluh what about updating the PR to latest version?

**Comment by abedwardsw** [comment]
hi, I would also like to see this module included in base ansible.

**Pull request closed without merging**
