### PR TITLE
[2.7] backport cs_instance fixes

### PR DESCRIPTION
**Pull request by resmo**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

cs_instance

##### ANSIBLE VERSION

```paste below
2.7
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by yadvr — APPROVED** [review]
LGTM, checked against original PRs which were back ported.

**Comment by yadvr** [comment]
shipit

**Review by yadvr — APPROVED** [review]
shipit

**Comment by abadger** [comment]
<strike>Merged for the 2.7.1 release.</strike>

EDIT: Shippable  is failing will try rerunning shippable later to see if this is indeed ready to merge.

**Comment by abadger** [comment]
Errr.... Not yet merged.  shippable is failing here.  It may be a shippable problem, though, not a problem with the PR.  I'll check back in later and see if I can restart the CI job and it will pass.

**Comment by abadger** [comment]
Merged for the 2.7.1 release

**Pull request merged**
