### PR TITLE
fixed/extended module package/zypper

### PR DESCRIPTION
**Pull request by berendt**
- Introduced new parameter recommends to be able to install
  and updated packages without installing recommend packages.
- Made disable_gpg_check usable with updating packages.
- Changed SuSE to SUSE in the description, because that's the
  correct name of the company. Have a look at
  http://en.wikipedia.org/wiki/SUSE for verification.

### CODE REVIEW

**Comment by mpdehaan** [comment]
So with this patch the "version_added" attribute needs to be added in the documentation for the new parameter.

Also, is the default for recommends the way it worked before this change?

Thanks!

**Comment by berendt** [comment]
@mpdehaan Recommends works the way it worked before. Recommends is used by default by zypper and the default in the Ansible module is yes.

**Comment by berendt** [comment]
Any news here?

**Comment by alxgu** [comment]
The feature to disable "install recommends" is already in 1.8 devel https://github.com/ansible/ansible/pull/7379
Did not see your pr :-(

**Comment by berendt** [comment]
Ok. Then this pull request can be abandoned.

**Pull request closed without merging**
