### PR TITLE
Azure SDK 2.0.0

### LINKED ISSUE #19451: Add support for Azure multi-cloud
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
contrib/inventory/azure_rm.py
lib/ansible/module_utils/azure_rm_common.py

##### ANSIBLE VERSION
New feature - latest

##### SUMMARY
Not all Azure cloud are public azure with endpoint to 'https://management.azure.com/'
For instance:
- Azure China: 'https://management.chinacloudapi.cn/'
- Gov Azure: 'https://management.usgovcloudapi.net/'
- German Azure: 'https://management.microsoftazure.de/'

Currently the azure_rm module provides no possibility to do configure that. This has to be done at two place:
- Inside the authentication ServicePrincipalCredentials or UserPassCredentials by adding `resource="endpoint"
- Inside the client by using base_url parameter

Example:
```python
endpoint = 'https://management.usgovcloudapi.net/'
self.azure_credentials = UserPassCredentials(
    self.credentials['ad_user'],
    self.credentials['password'],
    resource=endpoint
)
self._compute_client = ComputeManagementClient(
    self.azure_credentials,
    self.subscription_id,
    base_url=endpoint
)
```

Code MUST check that endpoint is ending with a /, since this is requirement from AD and you will get an invalid token otherwise. Should be done at the SDK level, but it's not done for now, so double-check here is safer.

I'll try to do a PR asap, just wanted to track this down.

### PR DESCRIPTION
**Pull request by lmazuel**
##### SUMMARY

This PR updates the Azure modules to [azure sdk 2.0.0](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure_2.0.0).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

modules/azure/azure_rm_resource_group
module_utils/azure_rm_common

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### ADDITIONAL INFORMATION
We just released azure SDK 2.0.0, with a feature that I thought would be nice in Ansible: the ability to use AzureCLI credentials to use the SDK. Meaning, you can use the "az login" command to authenticate through azure, and then run Ansible direcly:

```
$ export AZURE_CLI_DEFAULT_PROFILE=true
$ az login
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code FKKB8T54Q to authenticate.
$ ansible-playbook rg_test.yml --connection=local

TASK [Create a resource group] **************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Delete a resource group] **************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```

This uses the authentication method used for CLI (you can define service principal, user password or device login)+ default subscription_id + default cloud (then could be German Cloud, etc). This allows Ansible to be easily used for sovereign cloud (fix #19451)

- [az login](https://docs.microsoft.com/cli/azure/authenticate-azure-cli): access to credentials
- [az account set --subscriptions](https://docs.microsoft.com/cli/azure/manage-azure-subscriptions-azure-cli): access to subscription_id
- [az cloud set --name](https://docs.microsoft.com/cli/azure/cloud#set): access to base_url (sovereign cloud)

This first commit is just step one, I wanted your opinion on this before doing more.

TODO for this PR:
- Check/adapt all `azure` module against SDK 2.0.0. This should simple, with small changes (see azure_rm_resourcegroup in this first commit)

Future roadmap (another PR this summer)
- Autoadapt the api-version passed to the RestAPI using the CLI profile. The endpoint URL is step1, but it's possible that a given api-version is still not available in a not-public Azure cloud, meaning changing the endpoint is not enough. We have the information in the CLI, but this requires a little more work right now to plug at the SDK level. So users might get "api-version not supported" error message in the meantime an api-version is not deployed to sovereign cloud they want to use. Also AzureStack support for Ansible will need this for sure (api-version are not the latest one).

@nitzmahone @chouseknecht @devigned

### CODE REVIEW

**Comment by lmazuel** [comment]
@nitzmahone @chouseknecht I made a full review of all the Azure ARM plugins and fix some exceptions catching that were incorrect. Otherwise, everything LGTM and ready to merge.

Has Ansible a testsuite for that? Even a manual testsuite? I don't have Playbooks with all scenarios, so I'm unable to be 100% sure everything is covered correctly. I will try to write some usual playbook (VM, etc.), but if you have something already, worth a new try.

With this PR merged, documentation should say "azure >= 2.0.0 or azure-cli >= 2.0.6". I can review the documentation if necessary (is it on Github too?)

**Comment by nitzmahone** [comment]
@tstringer - Here's the original repo we developed this stuff in: https://github.com/ansible/azure-testing. It has the outdated beginnings of the integration test suite I mentioned yesterday. If you want to use that as a starting point to mess with integration tests, it might be easier than starting from scratch (or it might not :D )... Let me know if you have any questions!

As for this PR, the code changes generally look OK to me, except that there's a new common arg -
 `cli_default_profile`. We'd want to cherry-pick these changes to at least the stable-2.3 branch, and probably stable-2.2 as well, but we don't typically make any UI changes to already-shipped releases. We could probably make an exception, since these are preview modules and we really want the fixes for 2.0.0. That will also need to be added to the module docs (which will likely start triggering validation failures in CI once we cherry-pick them back, since `version_added` will be > the current version on that branch).

**Comment by 4c74356b41** [comment]
hey, so this is not yet done? any eta?

**Comment by trstringer** [comment]
@4c74356b41 great question! We're currently working hard on implementing the support for azure==2.0.0. At the moment, we are focused on implementing integration testing for Azure modules in Ansible. It is key that we have this all panned out so that we don't cause regressions and unnecessary bugs with introducing the recently updated Azure SDK for Python.

We will keep the community updated! Thanks again! 😄

**Comment by 4c74356b41** [comment]
@tstringer great news, but any eta on this? week? month? quarter? year?

**Comment by trstringer** [comment]
@4c74356b41 I would say it's a safe assumption that in the next month we should have a firm understanding of how much work it'll take to integrate azure==2.0.0. Depending on how much integration testing uncovers, that line could go either way after a thorough regression test.

**Comment by nitzmahone** [comment]
These changes and updates were merged in #27920.

**Comment by 4c74356b41** [comment]
hey thanks, I guess my question now is, how is this being distributed? do i just grab the code from this repo? I've never done this, I've only installed ansible with pip\apt\yum. Any articles\hints?

**Comment by trstringer** [comment]
@4c74356b41 "how is this being distributed?" What are you referencing by "this"? Do you mean the Azure Python package dependencies? In that case, from source you would `pip install .[azure]`, and when the ansible package is updated in PyPI it would be `pip install ansible[azure]`.

**Comment by 4c74356b41** [comment]
no, i mean this version of ansible with fixes for azure 2.0.0

**Comment by trstringer** [comment]
Not sure I understand. Ansible will be distributed how it always is. If you are looking to use these changes in your environment now, you'd have to use source instead of PyPI or your package manager.

**Comment by 4c74356b41** [comment]
so is there a document covering how to use source? sorry for asking newbie questions, but I've never done this with ansible

**Comment by trstringer** [comment]
Not a n00b question at all, take a look at [this information that shows how to run Ansible from source](https://github.com/tstringer/ansible-dev-by-example#environment-setup). I hope that helps! You may have to get clever with scripting that out so that a shell script does some handwaving over all of this.

**Comment by 4c74356b41** [comment]
ok, hopefully 2 last question, when these fixes become available using pip? why does that document mention python3. i thought ansible doesnt work with python3?

**Pull request closed without merging**
