### PR TITLE
fixes #3609 Add max_fail_pct to playbook

### LINKED ISSUE #3609: Rolling updates should allow max percentage of failure
While doing rolling updates, would be nice to have a configurable parameter to indicate max number of node failures allowed before stopping the playbook. The reason is if there is some issue in upgrade and tomcat or some other step fails to comeup on many machines, We should stop the playbook and not take down majority of the nodes.

i.e. Suppose in playbook i configure, 

```
# From the group of servers , if 5% have failed, Stop running the playbook
 - hosts: {{host_group}}
   serial: 10
   maxfail: 5%
```

So if you have 300 servers, and serial: 25 and maxfail: 5%. In the first 2 runs combined, (50 servers) , 15 servers failed , like 10 in 1st and 15 in second. Stop the playbook

### PR DESCRIPTION
**Pull request by kavink**
This implements an additional option along with serial option, So if total number of failures for a batch execeed max_fail_pct \* total number of hosts in the batch, do not go to the next serial batch.

Default behavior remains same as before.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Suggest perct gets spelled out here:

max_fail_percentage

In queue for review!

**Comment by kavink** [comment]
Ok Thanks! Changed it.

**Comment by mpdehaan** [comment]
This looks very clean, in queue for testing, thanks!

**Comment by jimi-c** [comment]
One interesting thing I've noticed about this is, if the hosts are failed during the fact gathering stage (for example, not reachable), they will not go towards the failed host count. That may be something you want to correct in a future pull request. As this stands, it appears to work correctly once the task executions start.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request closed without merging**
