### PR TITLE
Apply tags conditionally so that the module does not throw up an error

### PR DESCRIPTION
**Pull request by brtkwr**
…r when using an older distro of openstacksdk

(cherry picked from commit c517538bd81149f5b507617e5f3385f98ec4642a)

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by abadger** [comment]
2.7 is only open for critical and security bugfixes at this point. If you think that this is a critical bugfix, you can take this to the core irc meeting https://github.com/ansible/community/tree/master/meetings#tuesdays to get an official ruling. Otherwise I'll close this PR soon since it won't be merged to this branch.

**Comment by cloudnull** [comment]
+1 to what @abadger said. While this is a clean cherry-pick, the patch doesn't seem like it meets the critical bug fix criteria. That said, if it is critical It'd be great to get a little more information as to why.

**Comment by brtknr** [comment]
Where is a critical bug fix defined? I'd like to make the claim that it is critical because os_stack module in 2.7.10 claims to have a feature which is broken without this patch. That said, the rest of Ansible will probably live without it but its rather annoying having to move to 2.8 just to use this patch.

**Comment by abadger** [comment]
Critical bug fix is left to the discretion of the committers (and the meeting mentioned earlier is the venue for getting that decision from them).  Some of the things I personally look for (The more of these a bugfix falls under, the more likely a bug would be deemed critical):

* Is the bug a regression from any past 2.7 releases?  (More likely to be critical)
  * Is the bug a regressions from 2.6 or earlier? (Not as likely to be critical but can contribute)
* Does the Ansible core engine fail if the patch is not applied? (More likely to be critical)
  * Does an important, widely used module/plugin fail if this patch is not applied? (More likely to be critical)
* Is there a workaround for the issue? (Less likely to be critical; might merge documentation of the workaround, though.)
* Who does the bug affect?  Many users or just a few?  Large customers?  Is it in the critical path for these or is it just a niche use case?  (More likely to be critical)

**Comment by jamescassell** [comment]
> Critical bug fix is left to the discretion of the committers (and the meeting mentioned earlier is the venue for getting that decision from them). Some of the things I personally look for (The more of these a bugfix falls under, the more likely a bug would be deemed critical):
> 
> * Is the bug a regression from any past 2.7 releases?  (More likely to be critical)
>   
>   * Is the bug a regressions from 2.6 or earlier? (Not as likely to be critical but can contribute)
> * Does the Ansible core engine fail if the patch is not applied? (More likely to be critical)
>   
>   * Does an important, widely used module/plugin fail if this patch is not applied? (More likely to be critical)
> * Is there a workaround for the issue? (Less likely to be critical; might merge documentation of the workaround, though.)
> * Who does the bug affect?  Many users or just a few?  Large customers?  Is it in the critical path for these or is it just a niche use case?  (More likely to be critical)

Would be great to add these to the docs somewhere!

**Comment by brtknr** [comment]
I would argue that what makes this somewhat critical is that it is not in the presence of tags (which produces a warning) but the absence of tags argument (which is how most users would most likely opt to use the module) which would lead to failure without any comprehensible warning or error message.

**Comment by jamescassell** [comment]
original PR is at https://github.com/ansible/ansible/pull/56575 -- the merged commit was 18f22de67e8304aebf4e78e2dfa6fe7831e635a3

If this is determined to be critical, the backport should be re-done against that Commit ID, not the c517538 id.

**Comment by samdoran** [comment]
@brtknr As an aside to whether or not this should be backported, it looks like this was cherry picked from a commit in your PR branch. The cherry pick should be from the commit in the `devel` branch, in this case 18f22de67e8304aebf4e78e2dfa6fe7831e635a3.

**Comment by Shrews** [comment]
IMO, this is a new feature. You are setting the minimum version of the openstacksdk library to a release that was just released on May 10, 2019 for an older version of Ansible. The tags parameter would not have been supported when 2.7 was actively maintained because openstacksdk didn't support it during that period. So it wasn't really a bug, though it may be so now. Not critical.

**Comment by samdoran** [comment]
@abadger This was voted on as not critical to Ansible in the [IRC meeting on 2019-06-04](https://meetbot.fedoraproject.org/ansible-meeting/2019-06-04/ansible_core_irc_public_meeting.2019-06-04-19.10.log.html#l-88). If the maintainers of the OpenStack moduless weigh in and deem it is causing widespread issues that cannot be addressed by upgrading to Ansible >=2.8.1, then we can reconsider.

**Pull request closed without merging**
