### PR TITLE
Pretty-print the JSON output

### PR DESCRIPTION
**Pull request by lorin**
Indents the JSON output and separates out stdout and stderr so newlines are visible.

Makes it easier to read what appears on standard output when tasks fail.

### CODE REVIEW

**Comment by mpdehaan** [comment]
pretty printing is a good idea, but due to the architecture of things, there's never going to be any stderr from a module error.  I'll take a look in a bit, we can probably tweak this some.   I also want to make sure it's always getting JSON at this point, as I'm not positive.

**Comment by mpdehaan** [comment]
haven't forgot about this, shouldn't be any problems -- will take a look next week.

**Comment by mpdehaan** [comment]
Take a look at what I did in e259a93 -- it seems the on_unreachable callback doesn't really occur on parse errors (nor would that have stderr/stdout) and we wanted to capture command failures (possibly this is just me misreading your original commit).   on_unreachable should only really be called on exceptions now, at least, it seems that way.    This leaves verbose not splitting out stderr/stdout in the same way, but I think that is probably ok for now -- though I'd take a patch to make this similarly work for verbose (-v -v -v) mode.

**Comment by mpdehaan** [comment]
(closing this one)

Let me know if this needs further work still.

**Comment by lorin** [comment]
I assume you mean c63189f650? Looks good to me.

**Comment by mpdehaan** [comment]
Yeah, that's the one!

Good deal.

**Pull request closed without merging**
