### PR TITLE
libssh2 transport -- requires pylibssh2

### PR DESCRIPTION
**Pull request by mgwilliams**

### CODE REVIEW

**Comment by mpdehaan** [comment]
This needs to gate the import of libssh2 like so:

HAS_SSH2 = True
try:
   import libssh2
except:
   HAS_SSH2 = False

...

class WhateverConstructor(object)

```
def __init__(self):
   if not HAS_SSH2:
       raise Exception("...")
```

**Comment by mpdehaan** [comment]
Nice work, btw.   

One addition -- I also can't apply this until sudo is supported.   This will probably be on hold until 0.5, so please see if you can work on these two things and resubmit when that's en route.   We need absolute parity with the paramiko version for inclusion.

The other thing that MIGHT be worth doing is, if it works perfectly, detect whether libssh2 can be imported and choose the faster connection automatically.   But we won't do that until people have had a chance to test it and mark it good to go.

**Comment by mpdehaan** [comment]
closing to avoid accidentally hitting the merge button.

**Comment by mgwilliams** [comment]
Thanks! I wasn't expecting anything before 0.5. I'll try to add sudo over
the weekend as well as import protection.

**Comment by mpdehaan** [comment]
Excellent.

By probably I do mean definitely.   It may very well be fine but I need to let people pound on things for a while to avoid having to do point releases.   The overhead of doing those releases is not fair on package maintainers, so it's best to stabilize all things for a while prior to doing a rev.  Plus have to save things to look forward to to 0.5.  I think that coupled with proposed playbook upgrades will be fantastic.

We can also tell people who don't have it in their distro to just install the native lib with RPM and the Python module with pip in the short term, I'd bet.

**Pull request closed without merging**
