### PR TITLE
renaming info -> facts

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Undoing the changes for 2.8.
As agreed we will introduce _info in 2.9.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
multiple

### CODE REVIEW

**Comment by zikalino** [comment]
@yungezz following our discussion with @nitzmahone  last thursday, I think we can merge this pr.
just single test randomly failed. i am restarting it.

**Review by bcoca — CHANGES_REQUESTED** [review]
-1 as already discussed, the renaming to _info was not a requirement, but the 'not naming them _facts' always was

**Review by bcoca — CHANGES_REQUESTED** [review]
you should really not mix rename with code fixes

also renaming to _facts is still against the rules

**Comment by zikalino** [comment]
@bcoca not mixed. I accidently checked in the code not intended intro this pr and removed id. so it's still just renaming.
I also want to have all the azure modules renamed to _info, but after long discussing it simply has to wait until after 2.8 is released......

**Comment by bcoca** [comment]
i set up for discussion in tomorrow's core irc meeting, working groups cannot override core votes.

**Comment by yungezz** [comment]
HI @nitzmahone  Matt, could you pls help to share the history and background of the azure _facts modules changing and removing of `ansible_facts`  in output in the meeting? thanks.

**Comment by zikalino** [comment]
@bcoca what time is the core meeting?

**Comment by bcoca** [comment]
https://github.com/ansible/community/blob/master/meetings/README.md

**Comment by zikalino** [comment]
@bcoca thx!

**Comment by zikalino** [comment]
@bcoca @nitzmahone could we merge this pr?

**Comment by yungezz** [comment]
per IRC core meeting result as commented in https://github.com/ansible/ansible/issues/54280#issuecomment-479172664, we'll merge this PR then.

**Review by yungezz — APPROVED** [review]

**Pull request merged**
