### PR TITLE
Add DigitalOcean inventory plugin

### PR DESCRIPTION
**Pull request by neomantra**
Intended to complement the recently added digital_ocean module.

More info/motivation/examples can be found at the original project page, which I intend to delete if/when this script gets accepted:
https://github.com/neomantra/ansible-digitalocean

Don't hate me for single-line ifs -- I think it is readable where I use them!?

### CODE REVIEW

**Comment by zbal** [comment]
Sweet ! I'll give it a shot very soon.

**Comment by mpdehaan** [comment]
Very cool, merged in, thanks!

**Comment by bobobo1618** [comment]
Using this myself I'm getting some strange errors:

```
Traceback (most recent call last):
  File "./plugins/inventory/digital_ocean.py", line 451, in <module>
    DigitalOceanInventory()
  File "./plugins/inventory/digital_ocean.py", line 182, in __init__
    self.load_all_data_from_digital_ocean()
  File "./plugins/inventory/digital_ocean.py", line 294, in load_all_data_from_digital_ocean
    self.build_inventory()
  File "./plugins/inventory/digital_ocean.py", line 328, in build_inventory
    image_name = self.index['image_to_name'][droplet['image_id']]
KeyError: '495741'
```

I'm using Ansible from Git and Python 2.7 on Arch Linux 64 bit.

**Comment by mpdehaan** [comment]
Ok can you please file a bug?  This is a pull request ticket that is already closed, so it will be lost.

Thanks!

**Comment by zbal** [comment]
@bobobo1618 could you give me the command you ran when you had this error? or at least a way to reproduce ?
Not sure whether the inventory or the the digital_ocean is at fault.

We updated the dopy library 2/3 days ago, could you give a shot with the latest version ?

**Comment by neomantra** [comment]
@zbal:  please follow-up here: #3438

**Pull request merged**
