### PR TITLE
ACME: simplify code

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
I noticed that #33792 improved `fetch_url` to handle header names in a harmonized way for both Py2 and Py3. Let's see whether the tests agree :)

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/acme.py

##### ANSIBLE VERSION
```
2.8.0
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/83841/93/tests

**Comment by felixfontein** [comment]
The tests fail because of some bad assumptions (the code always assumes `content-type` is returned by server) and because of #45628.

**Comment by felixfontein** [comment]
With #45628, it now works :)

**Comment by resmo** [comment]
shipit

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
Hmm, there's something wrong with the bot. There should be two maintainer shipits (one direct by resmo, one indirect by me), but the bot lists none.

**Comment by gundalow** [comment]
bot_status

**Comment by felixfontein** [comment]
I created an issue for ansibot here: ansible/ansibullbot#1045

**Comment by felixfontein** [comment]
For PRs which include both modules and modlue_utils changes, it used to work; see ansible/ansible#45051

**Review by gundalow — APPROVED** [review]

**Pull request merged**
