### PR TITLE
Bugfixes in integration tests to run as unprivileged user (on Debian sid)

### PR DESCRIPTION
**Pull request by leegarrett**
##### SUMMARY

This is a list of some fixes needed to run integration tests on Debian sid as unprivileged user. Some are Debian-specific, others fix it for all distros.

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by leegarrett** [comment]
Just force pushed an update to fix the shellcheck errors.

**Comment by leegarrett** [comment]
The integration tests fail on `ansible-playbook-callbacks`, which reports back different numbers. I guess I need to update those? It's not quite clear to me what this test is supposed to safeguard against.

**Comment by webknjaz** [comment]
FYI, it might be easier to review smaller patches targeting one thing each. Plus, it would reveal which of the changes break the tests more clearly. 33 files is not something an average reviewer would find time in their calendar to review regularly.

**Comment by leegarrett** [comment]
> FYI, it might be easier to review smaller patches targeting one thing each. Plus, it would reveal which of the changes break the tests more clearly. 33 files is not something an average reviewer would find time in their calendar to review regularly.

Good point, thanks for the feedback. I'll split it up into smaller, more digestable changes then.

**Comment by webknjaz** [comment]
@leegarrett plz note that many people have gone on vacations until the next year. I recommend you to ping somebody in those PRs in 2025.

**Comment by leegarrett** [comment]
Thanks for the heads-up, will do.

**Pull request closed without merging**
