### PR TITLE
Display more info when SSH errors occur

### PR DESCRIPTION
**Pull request by msabramo**
This is in the same vein as #9603, but it is more ambitious in that it attempts to display more helpful info for a number of different SSH errors.

Sample outputs:

```
fatal: [vagrant] => SSH Error: Host key verification failed.
    while connecting to 127.0.0.1:2222
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help
 diagnose the issue.
```

```
fatal: [vagrant] => SSH Error: ssh: connect to host 74.125.239.52 port 22: Operation timed out
    while connecting to 74.125.239.52:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help 
diagnose the issue.
```

```
fatal: [vagrant] => SSH Error: ssh: connect to host 192.26.5.1 port 22: Network is unreachable
    while connecting to 192.26.5.1:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help
diagnose the issue.
```

```
fatal: [vagrant] => SSH Error: Permission denied (publickey,password).
    while connecting to 69.163.167.30:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help 
diagnose the issue.
```

```
fatal: [vagrant] => SSH Error: ssh_exchange_identification: Connection closed by remote host
    while connecting to 74.125.239.52:80
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help 
diagnose the issue.
```

```
fatal: [vagrant] => SSH Error: bad permissions: ignore key: 
/Users/marca/.vagrant.d/insecure_private_key
    while connecting to 127.0.0.1:2222
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help 
diagnose the issue.
```

Cc: @sontek, @aconrad, @sudarkoff

### CODE REVIEW

**Comment by msabramo** [comment]
Mailing list discussion:

https://groups.google.com/forum/#!topic/ansible-project/H-hv_w44IdY

**Comment by nathancahill** [comment]
:+1:

**Comment by aconrad** [comment]
Great improvement!

**Comment by mindware** [comment]
I want this in :+1:

**Comment by msabramo** [comment]
@wolfgangkarall: Well, that was an unintended side-effect. I'm thinking that it's because the `raw` module is very low-level and not really recommended except in very special cases. See http://docs.ansible.com/raw_module.html

Can you use `command` or `shell` for what you're doing?

**Comment by msabramo** [comment]
@wolfgangkarall: I guess if you really need the `raw` module not to emit verbose output, then you could change the code as follows:

``` diff
diff --git a/lib/ansible/runner/connection_plugins/ssh.py b/lib/ansible/runner/connection_plugins/ssh.py
index b174396..4827404 100644
--- a/lib/ansible/runner/connection_plugins/ssh.py
+++ b/lib/ansible/runner/connection_plugins/ssh.py
@@ -269,7 +269,8 @@ class Connection(object):
         if utils.VERBOSITY > 3:
             ssh_cmd += ["-vvv"]
         else:
-            ssh_cmd += ["-v"]
+            if self.runner.module_name != 'raw':
+                ssh_cmd += ["-v"]
         ssh_cmd += self.common_args

         if self.ipv6:
```

I'm not sure if this qualifies as a bug or not. Maybe one of the ansible devs can answer on that.

**Comment by bcoca** [comment]
i might just make that fix now

**Comment by bcoca** [comment]
try with latest devel, fixed in  https://github.com/ansible/ansible/commit/19ba26e9a5ddb4aa1d326ae058e8a79b349345dc

**Comment by wolfgangkarall** [comment]
Yes, I need the raw module, because there are a couple of Solaris machines I'd like to treat with ansible which don't have anything apart from plain SSH + shell.

@bcoca Thanks, latest devel works fine. :+1:

**Pull request merged**
