### PR TITLE
Bump up pylint to 2.15.4 

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

##### SUMMARY

upgrading from pylint release 2.15.3 to 2.15.4 which includes fix for issue https://github.com/PyCQA/pylint/pull/7541.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by Qalthos — CHANGES_REQUESTED** [review]
2.15.4 was just released which should also fix this issue.

Also would be better to edit `sanity.pylint.in` and properly regenerate the file.

**Comment by trishnaguha** [comment]
CC @mattclay

**Review by Qalthos — APPROVED** [review]

**Comment by webknjaz** [comment]
This PR is broken because the constraints files haven't been re-generated using the proper script. It manifests in the CI as follows:
```console
01:08 ERROR: Cannot install -r requirements/sanity.pylint.txt (line 8) and astroid==2.12.10 because these package versions have conflicting dependencies.
01:08 
01:08 The conflict is caused by:
01:08     The user requested astroid==2.12.10
01:08     pylint 2.15.4 depends on astroid<=2.14.0-dev0 and >=2.12.11
01:08 
01:08 To fix this you could try to:
01:08 1. loosen the range of package versions you've specified
01:08 2. remove package versions to allow pip attempt to solve the dependency conflict
01:08 
01:08 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
01:08 A command failed with status 1: /root/.ansible/test/venv/sanity.pylint/3.11/0c4fdbb8/bin/python /tmp/ansible-test-7ogmzjvp-pip.py install --disable-pip-version-check -r requirements/sanity.pylint.txt
```

**Comment by mattclay** [comment]
I'm working on a replacement PR.

**Comment by mattclay** [comment]
Superseded by https://github.com/ansible/ansible/pull/79103

**Pull request closed without merging**
