### PR TITLE
Update playbooks_roles.rst

### LINKED ISSUE #7241: Docs refer "vars_files" before their definition
##### Issue Type:

Documentation Report
##### Ansible Version:

1.5.3
##### Environment:

N/A
##### Summary:

[Here](http://docs.ansible.com/playbooks_roles.html#roles), docs says:

> Now that you have learned about vars_files...

But actually, "vars_files", not mentioned in any of previous chapters. Their definition takes place [here](http://docs.ansible.com/playbooks_variables.html#variable-file-separation) - in next chapter.

### PR DESCRIPTION
**Pull request by nmadhok**
Fixes https://github.com/ansible/ansible/issues/7241

### CODE REVIEW

**Comment by jimi-c** [comment]
Rather than hard-coding the link here, could you use the sphinx built-in reference function instead? That way if the docs are reorganized in the future, links won't break. Example reference:

<pre>
:ref:`vars_files &lt;variable_file_separation_details&gt;`.
</pre>

Where the label name is one of the labels in the docs, ie. `.. _variable_file_separation_details:`. More details can be found here: http://sphinx-doc.org/markup/inline.html#role-ref

**Comment by nmadhok** [comment]
@jimi-c This can be merged now. Made the requested changes!

**Comment by nmadhok** [comment]
@jimi-c This is ready to be merged!

**Comment by nmadhok** [comment]
@jimi-c It's been 10 days and this hasn't been merged yet. It's such a small change but what's taking such a long time?

**Comment by jimi-c** [comment]
@nmadhok we work on issues based on their prioritization, and we've been primarily working on clearing out P1/P2's lately. Please be patient, and we will get to it as soon as possible.

Thanks!

**Comment by nmadhok** [comment]
@jimi-c Sure. Just seemed like a long duration to me to merge a small change. Keep me posted!

**Comment by jimi-c** [comment]
Merged, thank you!

**Comment by nmadhok** [comment]
@jimi-c Thanks!

**Pull request merged**
