### PR TITLE
Added ansible_ssh_config variable

### PR DESCRIPTION
**Pull request by phil777**
This variable enables to provide a different ssh config file (ssh option -F)
in inventories so that connection parameters can be adjusted without
poking at the user's default .ssh/config file.

This pull request is related to https://github.com/ansible/ansible/pull/2970 discussion and largely inspired from @rodlogic pull request.

### CODE REVIEW

**Comment by mpdehaan** [comment]
you can already set this via ANSIBLE_SSH_ARGS or in ansible.cfg, not sure we need another option for this.

**Comment by echohead** [comment]
from the peanut gallery, i agree ANSIBLE_SSH_ARGS should be sufficient:
   [https://github.com/ansible/ansible/pull/2970#issuecomment-22166241]

**Comment by phil777** [comment]
Then how can I do this ?

[network1]
ansible_ssh_config=ssh_config_net1
webA
dbA

[network2]
ansible_ssh_config=ssh_config_net2
webB
dbB

If you really want to simplify the number of variables, then ansible_ssh_host, ansible_ssh_port, ansible_ssh_user
could be moved to ssh config file. But, IMHO, ansible is not targeted at my grandmother but at people that manage hundreds of computers in complex environments. They will cope with another variable.

I agree that from an ergonomic point of view, its is bad to have twice the same control, but  ANSIBLE_SSH_ARGS is not the same thing. The environment variable is nice to overload a behavior that is already working. It is not nice to make it work. I don't want to have to wrap my main ansible binaries. 

Wrapping binaries is ugly. Either I put them in /usr/local/bin, and I have a system-wide setting that I cannot put inside a VCS , or I put them in the ansible folder but I have to change my PATH, hence a user-wide modification. And in both cases, it is a deviation from standard (the standard being: call the genuine ansible-playbook binary on the provided playbook) hence it has to be documented and taken care of when migrating from one box to another or when having a new guy in the team. I don't see the gain in simplicity here. 

So please reconsider your choice.

**Comment by phil777** [comment]
Also, thinking more about big principles, IMHO, there are 2 sets of information that ansible use:
- its configuration (where to find ansible hosts, where to find its modules, default fork, etc.)
- its application data (hosts to manage, how to connect to them, what to install etc.)

They do belong to 2 different worlds and are managed differently. IMHO, putting how to connect to managed hosts in an ssh config files is nice to keep the inventory file light, and it makes sense. But ssh config files belong to ansible application data like inventory file, and inventory file must be able to delegate the management of connection to ssh config files. And all these are application data. They should not need some action in the ansible configuration world.

I think that ANSIBLE_SSH_ARGS or ansible.cfg is not the nice answer to this and I hope I convinced you :)

**Comment by mpdehaan** [comment]
Closing due to theoretical discussion about big principles that has drifted away from the previous bug report.

Seems we can just use the parameter given thousands upon thousands of people are ok with that :)

**Comment by phil777** [comment]
Ok fair enough. I should have restrained myself to a simple "why not". I read twice the "how to contribute" and it seems those discussions belong to the googlegroups. Sorry to have digressed here. I hope my enthusiasm is not seen as me being mean.

**Comment by mpdehaan** [comment]
Not at all, we are bound to disagree some on feature discussions!

**Pull request closed without merging**
