### PR TITLE
Added a new check to check whether an network interface is in promiscuou...

### PR DESCRIPTION
**Pull request by cristobalrosa**
Added a new check to the setup module that retrieves whether a net interface is on promiscuous mode

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this.

I'm a bit concerned about the possible portability of this check.  Can you let us know about under what environments and cases this was tested?

Also, just as a code standards thing, please leave a space after a comment. "# foo" is more readable than "#foo" and is consistent with the rest of the source.

Thanks!

**Comment by cristobalrosa** [comment]
Hi @mpdehaan,

I have tested it against a Debian, an ubuntu and a Fedora system. I haven't tested it against a BSD like system. I think maybe on a BSD-like system the ethernet card information is located in a different place.

Systems in which it has been tested:
Linux ubuntu 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Linux devel 3.9-1-amd64 #1 SMP Debian 3.9.6-1 x86_64 GNU/Linux

Fedora 18: Linux localhost.localdomain 3.6.10-4.fc18.i686 #1 SMP Tue Dec 11 18:24:49 UTC 2012 i686 i686 i386 GNU/Linux

**Comment by jimi-c** [comment]
@cristobalrosa it looks like you let some other's commits bleed into your branch there. Could you be sure to create a feature branch for commits so that won't happen? Just create a new branch from the origin/devel branch and then use the "git cherry-pick" command to bring your one commit over to it. Then you can resubmit the PR from that branch.

**Comment by cristobalrosa** [comment]
@jimi-c  I'm sorry for the mistake. 
Here you are the new pull request using a new feature branch. 
https://github.com/ansible/ansible/pull/4282

Thanks

**Pull request closed without merging**
