### PR TITLE
added initial file for v2 api of newrelic

### PR DESCRIPTION
**Pull request by 116davinder**
##### SUMMARY
1. Removed Support for NewRelic V1 api for recording deployment
2. Added support for NewRelic V2 Api 

##### ISSUE TYPE
New Module Pull Request

##### COMPONENT NAME
newrelic_deployment

##### ANSIBLE VERSION

```
[davinderp@ansible-srv ~]$ ansible --version
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/davinderp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION
After checking NewRelic Website, as they have depricated v1 api with xml format and they also exposed new v2 api with json/xml so i start this PR to support new v2 api and remove old version.

```

```

### CODE REVIEW

**Comment by 116davinder** [comment]
anyone knows? how to go for community review

**Comment by nathanwebsterdotme** [comment]
+1

**Comment by nathanwebsterdotme** [comment]
@metaboy ready_for_review

**Comment by nathanwebsterdotme** [comment]
@ansibot ready_for_review

**Comment by 116davinder** [comment]
anyone can merge it ?

**Comment by 116davinder** [comment]
@ansibot ready_for_review

**Comment by 116davinder** [comment]
@ansibot bot_status

**Comment by 116davinder** [comment]
@ansibot ready_for_review

**Comment by Constantin07** [comment]
when this PR is going to be reviewed ? Can it be merged ?

**Comment by 116davinder** [comment]
@Constantin07 I don't know, It has been waiting for more than 2 year and I didn't manage to find the right process as well like who should review it / who should merge it.

**Comment by 116davinder** [comment]
created PR on New Repository:
https://github.com/ansible-collections/community.general/pull/876

**Pull request closed without merging**
