### PR TITLE
Fix paramter confusion between directory and passwordstore

### LINKED ISSUE #31934: Lookup passwordstore - parameter passwordstore is implemented as directory
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
lib/ansible/plugins/lookup/passwordstore.py
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/passwordstore.py#L158-L163

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/n3ph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/home/n3ph/git/reservix/devops/ansible/roles']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Debian Stretch

##### SUMMARY
The parameter passwordstore is implemented as directory

##### STEPS TO REPRODUCE
```yaml
  - name: root | build passwordstore command
    set_fact:
      #passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} passwordstore={{ passwordstore_devops_path }}"
      passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} directory={{ passwordstore_devops_path }}"

  - name: root | get default root password
    set_fact:
      root_password_hash: "{{ lookup('passwordstore', passwordstore_cmd) | password_hash('sha512') }}"
```

##### EXPECTED RESULTS
Should be implemented as documented
https://docs.ansible.com/ansible/devel/plugins/lookup/passwordstore.html#options

##### ACTUAL RESULTS

```
fatal: [default]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: "}
```

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Remove `directory` and use `passwordstore`
Expand possible tilde in passwordstore path

Fixes #31934

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/lookup/passwordstore.py

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/n3ph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

### CODE REVIEW

**Comment by n3ph** [comment]
##### SUMMARY
Remove `directory` and use `passwordstore`
Expand possible tilde in passwordstore path

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/lookup/passwordstore.py

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/n3ph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

**Comment by n3ph** [comment]
Could someone please update the pull request topic accordingly? I messed up the ownership.. :-/

**Comment by bcoca** [comment]
this changes the lookup in backward incompatible ways ... even worse it does not make any note in docs about it.

**Comment by n3ph** [comment]
If you recommend I will revert the removal of directory and fix the issue by code duplication... 
Anyway I do not understand why passwordstore and directory were introduced both at a time.
At the moment the Docs are wrong. Its not possible to use either one of them correctly (regarding the tilde)

**Comment by bcoca** [comment]
I'm not sure how this ever worked or stopped working, but i can tell from git history both parameters were in the lookup since the beginning. The documentation was recently added (by me) and mostly reflected what was in the code regarding parameter handling. I did not go deep into how it functioned nor tested the existing examples.

I would like to resolve this w/o breaking anyone's existing usage and have the docs reflect how to correctly use the plugin, I'm unsure at this point what that entails, but i'm fine with adding a note that 'directory' was removed because it never worked and was mistakenly added. From my initial read it seams both parameters were supposed to be aliases but that somehow got broken before submitting.

**Comment by morphje** [comment]
I will take a look at what I've originally wrote (I've see too much computer at this moment, gotta quit while I'm still somewhat humanoid) . However personally I would recommend to just use an environment variable to define your pass database. 

ps. sorry for not seeing this sooner. I'll go an add my new github account as maintainer to this module

**Comment by gundalow** [comment]
@n3ph @morphje How can we progress this?

needs_info

**Pull request closed without merging**
