### PR TITLE
rename bigiX_device_facts -> bigiX_device_info

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Renames `bigip_device_facts` and `bigiq_device_facts` to `_info` since they do not return `ansible_facts`. Continues #56822.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
bigip_device_facts
bigiq_device_facts

### CODE REVIEW

**Comment by felixfontein** [comment]
FYI: this PR includes no new modules, it renames two modules.

**Comment by caphrim007** [comment]
if @wojtek0806 is ok with this, then I am too

**Comment by caphrim007** [comment]
I should also mention that F5 typically follows a 4 release deprecation cycle when doing major changes like this. This would mean that the symlink would be removed in 2.12 I think? something to add to the backlog

**Comment by felixfontein** [comment]
Since this rename will only appear in Ansible 2.9, it should be removed in 2.13. If it is removed a bit later, shouldn't be a problem either :)

**Comment by caphrim007** [comment]
@felixfontein ok. @wojtek0806 to add to his backlog, and one of us will remove it in 2.13. will wait for Woj to +1 this PR, then i'll merge.

**Comment by wojtek0806** [comment]
lgtm

**Comment by felixfontein** [comment]
@caphrim007 @wojtek0806 thanks a lot for reviewing this!

**Pull request merged**
