### PR TITLE
WIP: galaxy-cli: add check mode for install

### PR DESCRIPTION
**Pull request by resmo**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
galaxy-cli

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY
add a check mode for install, this allows a.o. to run ansible-galaxy on a CI regulary to find if updates would be available if version is e.g.  master branch.

### CODE REVIEW

**Comment by calfonso** [comment]
@resmo is this still in progress?

**Comment by resmo** [comment]
@calfonso rebased, ready for review

**Comment by bcoca** [comment]
this really does not check if the role will be install, just lists the one in the requirements file.

to really do a 'check' code would have to be added to `lib/ansible/galaxy/role.py`'s install method

**Comment by resmo** [comment]
I am getting old... I confused this PR with #21412 . This is still WIP, obviously.

**Pull request closed without merging**
