### PR TITLE
Adds apt-rpm module for ansible

### PR DESCRIPTION
**Pull request by evgkrsk**
Simple apt-rpm wrapper (based on urpmi module).

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not sure apt-rpm is widely used enough to include this in core.

Feel free to make your case!

**Comment by evgkrsk** [comment]
I use apt-rpm based Linux distro: ALT Linux (http://distrowatch.com/table.php?distribution=alt). It's surely widely used in russian-speaking countries.

It's very inconvient to use various wrappers to manage packages without proper ansible's module.

**Comment by mpdehaan** [comment]
This sounds reasonable, it seems like _perhaps_ some of the code from the apt module might want to be moved into module_utils so it could be shared, but I'm not sure.

**Comment by evgkrsk** [comment]
Hmm... no, I think it is not the case. apt-rpm (ported by Conectiva) does not have python's 'apt' module (AFAIK). First thing I tried is to patch apt module to work with apt-rpm :-)

I see no code to share with apt module, at a moment.

**Comment by evgkrsk** [comment]
ping?

**Comment by mpdehaan** [comment]
Merged, thanks!

I renamed this to "apt_rpm" to line up with other modules.

**Pull request merged**
