### PR TITLE
Enhanced mount module to make 'src' optional

### PR DESCRIPTION
**Pull request by fsoyer**
Enhancement of "mount" module from Seth Vidal : 
- Made 'src' parameter optional : 
  I wanted to be able to act on lines in fstab like this : 
  - SERVER 1 = /dev/mapper/vg0_lv_home /home ext4 defaults 1 2
  - SERVER 2 = /dev/mapper/LogVol00/lv-home /home ext4 defaults 1 2
    where 'src' are different but 'name' is the same. If 'src' is provided, a test is made like before, elsewhere it looks only at 'name' parameter.
- Added a parameter 'delmp' (means "delete mount point", can be rename if you want) for the unset_mount and unmount functions, because removing the directory under the mount point, without ask for it before, was too dangerous, IMHO (think : for some reason I want to umount /tmp, but I don't want to remove the directory !!)
- Added 2 states only_if_present and only_if_mounted to modify a line ONLY IF it is present in fstab.

Tested here, please test and validate if you find this useful.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm a bit unclear about what this does exactly.

What happens if the new states are used in each case?

What do we get by not being able to specify a src for the point point?

Can you show me an example of when I would use delmp?

My first thought is all of these options are a bit confusing and not something we want to do, but I possibly can be persuaded.

**Comment by fsoyer** [comment]
Michael,
I gave an example in the description, I made this changes because I had the case on 2 kinds of servers.
One of the security points that I check on a new server, is to be sure that the /tmp mount point have the option "noexec".
On server1, under CentOS 6.3, /tmp is a LVM volum at /dev/mapper/vg_server1-lv_tmp.
On server2, under Blueonxy 5108, /tmp is /dev/mapper/VolGroup00-tmp. In fact, I saw a lot of different names for the LVM volums on different systems. And, to answer before the question, no, we don't want to do manually the partitionning at install time, we let the installers of each system do their jobs.
As you can see, if I want to address a playbook on this two kinds of system (respectively 40%/60% of my servers), I can use only the "/tmp" mount point regardless of the volum name (so: the "src" part).
And last thing, certain old servers under CentOS 5 don't have a volum for /tmp !... So if I want to use this same playbook, I don't want that the mount module add a line in fstab in this case, regardless if it was present or not, when it try to change the options (this is what it does before, so I had errors at the next reboot on this servers !).

All other tasks in the playbook (and there is more than 20 different in it !) works on all systems, the only problem was this mount points checks. Isn't it a pity to have different playbooks for different systems only for this behavior ?

Maybe can this options be named differently to be more clear ?

**Comment by mpdehaan** [comment]
So I guess my understanding now is that the mount module can only manage mount points that it itself inserted, and you want to build something a bit more dynamic. 

I'd be interested if you could come up with names and examples that would help me understand more about the usage.

In the meantime, as for what you say about different systems, I'd be very tempted to template out fstab using ansible facts.

**Comment by fsoyer** [comment]
> I'd be interested if you could come up with names and examples

Others than ones given in the preceding comment ? That's real names and src on (my) real servers, what other examples want you ?
I needed the second behavior (only_if_...) because a third kind of server (generally "one-task" servers like DNS, or firewall,...) don't use LVM, the disk contains only one partition / (so no partition /tmp), and I didn't want that the mount module creates the line in fstab in this case.

> In the meantime, as for what you say about different systems, I'd be very tempted to template out fstab using ansible facts

Sorry, not sure to understand what you mean ?

**Comment by groks** [comment]
SSDs and thinly provisioned LUNs can benefit from discards, but it requires all pieces of the storage stack to have the option set. So I would like to put the following tasks in a role:

``` yaml
- name: enable discards in lvm
  lineinfile: dest=/etc/lvm/lvm.conf
              backrefs=yes
              regexp='(\s*)issue_discards\s?='
              line='\1issue_discards = 1'
              insertafter='^devices {'

- name: enable discard option for mount points
  mount: name=${item} opts=+discard
  with_items:
    - /
    - /home

- name: enable discard option in crypttab
  crypttab: name=${item} opts=+discard
  with_items:
    - /
    - /home
```

`lineinfile` handles `lvm.conf` no problem.

`mount` has the problem @fgth identified: too many required parameters. I want to set the discard option on some mount point, if that mount point exists, without knowing any of the other opts or src etc. So `opts` also needs to handle additions as well as specifying the complete state, like `chmod ug+w` can.

Obviously a `crypttab` module doesn't yet exist, but it is a similar style of file which is not amenable to `lineinfile` editing, and would benefit in the same way `mount` would from being able to specify additional options.

**Comment by phraktle** [comment]
I would also like to have this functionality to make src an optional parameter. Example use case: I would like to ensure the root filesystem is mounted with the noatime option, on a heterogeneous set of servers (e.g. local vagrant VM, various EC2 instances, where the mount src varies).

**Comment by phraktle** [comment]
Here's my ugly workaround / hack:

```
- name: check if root is mounted with noatime
  shell: awk '$2 == "/" && $4!~/noatime/ {noatime_missing=1} END{exit noatime_missing}' /etc/fstab
  ignore_errors: true
  register: root_mount_ok
  changed_when: "root_mount_ok.rc != 0"

- name: query root mount options
  when: root_mount_ok.rc == 1
  shell: awk '$2 == "/" { print $1; print $2; print $3; print $4; print $5; print $6 }' /etc/fstab
  register: root_mount_info

- name: remount root with noatime
  mount: name=/
    state=mounted
    src={{ root_mount_info.stdout_lines[0] }}
    fstype={{ root_mount_info.stdout_lines[2] }}
    opts=noatime,{{ root_mount_info.stdout_lines[3] }}
    dump={{ root_mount_info.stdout_lines[4] }}
    passno={{ root_mount_info.stdout_lines[5] }}
  when: root_mount_ok.rc == 1
```

**Pull request closed without merging**
