### PR TITLE
Docker api 2 inventory

### PR DESCRIPTION
**Pull request by mtekel**
##### SUMMARY

Make `docker.py` inventory script work with 2.0 libraries.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`contrib/inventory/docker.py`

##### ANSIBLE VERSION
any

### CODE REVIEW

**Comment by sivel** [comment]
Why can't we support both libraries at once in a single script like we do for the docker modules?

I would prefer that approach over 2 separate inventories

**Comment by mtekel** [comment]
Thanks for the tip, I have updated the script.

**Comment by mtekel** [comment]
This looks OK now, let me know if you need me to change anything else...

**Comment by milo-minderbinder** [comment]
Forgive me if this is a poor place to discuss, but I was thinking of creating an issue & submitting a PR to address a core issue with this docker dynamic inventory script. In its current state, it adds one or more docker hosts to the inventory, and any of the containers on those docker hosts. It also adds a group for each of the same, such that:

* The `inventory_hostname`s and `group` name and the corresponding  for each docker hosts is set to the URI used to connect to the Docker API, which results in Ansible hosts with names like `unix:///var/run/docker.sock` or `https://127.0.0.1:2376`. 
* Similarly, for containers, among the groups automatically created for each is one which takes the format `image_[*repository*/]<*image*>[:*tag*]`, which results in groups like `image_milo/centos:7`

This causes a couple of problems.
1. Managing `host_vars` and `group_vars` for these hosts becomes very painful due to filesystem file naming restrictions, which generally do not permit filenames containing a `/`. As a consequence, `host_vars` and `group_vars` need to be set in the host file, instead of managed through per host/group files and/or directories. 
2. As is likely often the case, if one of the docker hosts is running locally on the Ansible host, and `localhost` is listed in the inventory, plays targeting `all`, for example, will be run twice on the Ansible host (i.e. once against `localhost` and again against `unix:///var/run/docker.sock`). This could raise problems, and it also highlights again the issue it creates with `host_vars` and `group_vars` management, since you'd need to ensure common variables are set in the hosts file. This problem also arises if one of the inventory hosts is also one of the docker hosts (e.g. `foo.example.com` and `https://foo.example.com:2376`)
3. As of v.2.4.0 (I think), Ansible emits a warning for all of the dynamically added docker hosts & containers, for example: `[WARNING]: Found both group and host with same name: unix:///var/run/docker.sock`

In addition to these issues, I think semantically it doesn't make sense for the URI scheme (https://, unix://) to be part of the `inventory_hostname` in Ansible, since Ansible is managing hosts, not services on hosts. Nor does it make sense for the docker API port to be part of the name, which may be confused for a non-standard ssh port.

Thoughts?

Also, is there documentation/guidance somewhere which clearly defines what constitutes valid `inventory_hostname`s and `group` names, or possibly a dynamic inventory test script to verify that dynamic inventory scripts are not violating any such naming rules/conventions?

**Comment by sivel** [comment]
@milo-minderbinder yes, that seems to be off topic for this PR.  Create a new issue or send an email to the ansible-devel mailing list.

This PR is simply about adding support to use the v2 of the python docker module.

**Comment by dminca** [comment]
**Relates to:** #22993

**Comment by gundalow** [comment]
Closing and reopening to retrigger CI. This PR looks sensible, could people please review

**Comment by mtekel** [comment]
Hi,

this has been open for quite a while and not merged. Now it has conflicts. I can resolve these - but is the intention to ever merge this?

**Comment by gundalow** [comment]
I was hoping someone else would test this, I don't have this setup locally. Happy to merge if someone else gives this a shipit.

**Comment by mtekel** [comment]
Hi,

the test should be as simple as having latest, or reasonably recent docker installed - should be version 2.0+. When you run this script without patch, it fails. With patch it should not blow up and list running containers...

**Comment by abadger** [comment]
This change is simple enough (and similar enough to what's in the docker modules) that I'm willing to just merge it.  I'll rebase and merge today.

**Review by ryansb — APPROVED** [review]

**Comment by abadger** [comment]
Just checked and found that this was fixed via https://github.com/ansible/ansible/pull/27540 merged this morning.

**Pull request closed without merging**
