### PR TITLE
Fix apt-get - wrong merge

### PR DESCRIPTION
**Pull request by analytically**
This fixes issue #3277.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Passing data=None seems good here, but are you sure we don't want to pass the binary_data flag anymore?

**Comment by analytically** [comment]
Not entirely sure. Binary_data is just a flag that will insert a newline to stdin if the data is not binary. It's not used anywhere else in Ansible, and works without on Ubuntu 13.04 and my setup. It could actually be removed from run_command I think.

**Comment by mpdehaan** [comment]
On the contrary, I think it was explicitly added for this particular module to fix something about having binary keys passed in here.

**Comment by analytically** [comment]
https://github.com/ansible/ansible/pull/3162 - yes ok, we need to add binary_data then.

**Comment by analytically** [comment]
I've added the binary_data, can you merge?

**Comment by mpdehaan** [comment]
Fixed this myself a few days ago, so should be good to go.

**Pull request closed without merging**
