### PR TITLE
New modules: rax_cbs and rax_cbs_attachments

### PR DESCRIPTION
**Pull request by sivel**
This pull request adds 2 new Rackspace Public Cloud modules for dealing with cloud block storage.

The base of this work was forked from pull request #4864, and then the requested recommendations were applied on top.

### CODE REVIEW

**Comment by sivel** [comment]
cc @claco Just pinging you so you know I got this resubmitted with the requested changes.

**Comment by claco** [comment]
@sivel You sir, are a scholar and gentleman. :+1:

**Comment by mpdehaan** [comment]
Merged this now, I'll update the version_added info and changelogs.

**Comment by mpdehaan** [comment]
Was reading old diff, I think we're good actually, thanks!

**Pull request merged**
