### PR TITLE
Fix #21312, since dev is a list, it should be converted to a string

### LINKED ISSUE #21312: filesystem@devel: The file [/dev/xvdf] does not exist and no size was specified.
That is most likely related to #20551 

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
filesystem

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
Default

##### SUMMARY
filesystem module fails on CoreOS with:
```
mke2fs 1.42.13 (17-May-2015)\nThe file [/dev/xvdf] does not exist and no size was specified.\n
```

##### STEPS TO REPRODUCE

```yaml
- filesystem: fstype=ext4 dev=/dev/xvdf force=yes
```

##### EXPECTED RESULTS
Filesystem is created on a given block device.

##### ACTUAL RESULTS
Error is thrown.

```
fatal: [35.157.42.174]: FAILED! => {
    "changed": false, 
    "err": "mke2fs 1.42.13 (17-May-2015)\nThe file [/dev/xvdf] does not exist and no size was specified.\n", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "dev": [
                "/dev/xvdf"
            ], 
            "force": true, 
            "fstype": "ext4", 
            "opts": null, 
            "resizefs": false
        }
    }, 
    "msg": "Creating filesystem ext4 on device '['/dev/xvdf']' failed", 
    "rc": 1
}
```

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
filesystem

### CODE REVIEW

**Comment by bcoca** [comment]
no, we either need to revert my previous 'fix' that allowed for mulitple devices or go forward and make this so for all code paths.

**Comment by mscherer** [comment]
Well, going for "all code path" mean duplicating the same code to do the join, so I just refactored once

**Comment by bcoca** [comment]
and what happens in line 219 ? 

it needs to handle it as a list for the rest of the code or revert my initial change and disallow dealing with multiple devices

**Comment by mscherer** [comment]
I was in fact wondering if we should decide on a case by case basis of which one do support more than 1 device, as I am quite sure it would fail for most but btrfs. So maybe we should revert the patch for now, since freeze is soon.

**Comment by mscherer** [comment]
Fixed in b3b76826e5

**Pull request closed without merging**
