### PR TITLE
Fix cli context check for network_cli connection

### LINKED ISSUE #64575: Backward incompatible change in cli_command module
##### SUMMARY

```
- name: CHANGE PASSWORD TO WORKSHOP DEFAULT
  cli_command:
    command: "{{item}}"
    prompt:
      - "New password"
      - "Retype new password"
    answer:
      - "{{admin_password}}1"
      - "{{admin_password}}1"
    check_all: True
  loop:
    - "configure"
    - "rollback"
    - "set system root-authentication plain-text-password"
    - "commit"

- name: TURN ON NETCONF ON PORT 830
  junos_netconf:

```

The above task is working on current `stable-2.9` and broke in `devel` in the last few days.
https://github.com/ansible/ansible/commit/c27e47327f902dddf0b93767e387cacdfc12e11f is probably related.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

  - cli_command

##### ANSIBLE VERSION

  - devel

##### CONFIGURATION

  - N/A

##### OS / ENVIRONMENT

  - N/A

##### STEPS TO REPRODUCE

  - Task provided above

##### EXPECTED RESULTS

  - To work normally

##### ACTUAL RESULTS

```
failed: [trtr3] (item=rollback) => changed=false 
  ansible_loop_var: item
  item: rollback
  msg: |-

    rollback
                      ^
    syntax error.
 
    ec2-user>

failed: [rtr3] (item=set system root-authentication plain-text-password) => changed=false 
  ansible_loop_var: item
  item: set system root-authentication plain-text-password
  msg: |2-

     expecting <command>.

    ec2-user> set system   oot-authentication
                  ^

    syntax error, expecting <command>.

    ec2-user> set systemroot-authentication   lain-text-password
                  ^
    syntax error, expecting <command>.

    ec2-user>
```

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

Fixes #64575

*  Check cli context for network_cli connection
   at the start of new task run only.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible/cli/scripts/ansible_connection_cli_stub.py

##### ADDITIONAL INFORMATION

```paste below

```
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/232

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Review by Qalthos — APPROVED** [review]

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by Spredzy** [comment]
For the `ansible/workshops` this PR fixes the issue we are observing when testing with `devel`. Thank you @ganeshrn

**Review by Qalthos — APPROVED** [review]

**Review by Qalthos — APPROVED** [review]

**Comment by ganeshrn** [comment]
@Spredzy Thanks for testing the PR. @Qalthos Thank you for your review.

**Pull request merged**
