### PR TITLE
Documentation - indentation to 2 chars

### PR DESCRIPTION
**Pull request by mavimo**
In accord to discussion in ML documentation have 2 indentation chars.

I test also make webdocs  and all work fine.

### CODE REVIEW

**Comment by mavimo** [comment]
I find a list of errors in docs, I can fix it after merge of this PR to simplify conficlt resolving on merge:

#### CRITICAL:
- authorized_key => double description (aready DONE in this commit, to make possible generate docs)
- cloudformation => TASK in examples (aready DONE in this commit, to make possible generate docs)

#### HIGHT:
- ping => missing version_added
- setup => missing version_added
- ec2_facts => missing version_added

#### NORMAL:
- vagrant => missing description in examples
- copy => duplicate "others" in "options"
- fireball => Comment about spacing
- get_url => Comment in docs, examples out of documentation

#### LOW:
- django_manage => move choises in options.command after description
- group => move author e dependencies on bottom
- lvg => invert code with description in examples
- nagios => invert code with description in examples
- pause => invert code with description in examples

#### UNDEFINED:
- lineinfile => EXAMPLES with `r'''`` ??

**Comment by mavimo** [comment]
@mpdehaan if you can merge I'll start to fix docs error on WE :)

**Comment by mpdehaan** [comment]
I generally do _not_ accept whitespace patches as they break attribution in source control history

Can I ask what the problem was with the indentation and generating the docs from it?

**Comment by mavimo** [comment]
No problem on docs genration, as [discussed in ML](https://groups.google.com/forum/?fromgroups=#!searchin/ansible-project/Ansible$20modules$20documentation/ansible-project/2s7Fb-57eF4/i5b1R0AgRYQJ) I change it only to improve consistence on code.

Please let me know if is a rejected PR, so I can directly fix other bugs in docs.

**Comment by mpdehaan** [comment]
Yep, I'm going to close this one, thanks.

**Pull request closed without merging**
