### PR TITLE
Fix loader for filters

### PR DESCRIPTION
**Pull request by abadger**
##### SUMMARY
This is an alternative for https://github.com/ansible/ansible/pull/37730

Instead of adding more to the API, I bisected back to the commit where this was introduced: f921369445900dcc756821e40c9257d5359087af and tried to modify that to get it to work.  With that commit, just removing the call to os.path.basename was needed.  In devel, there was more needed.  I've fiddled around to get that working but I haven't yet confirmed that this doesn't break something else.  Pushing it to a PR so that we get integration tests to run with this.

Also includes the test cases from https://github.com/ansible/ansible/pull/37730

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/loader.py

##### ANSIBLE VERSION

```
devel 2.5 2.4
```
The problematic commit was introduced for ansible-2.4.0

### CODE REVIEW

**Comment by abadger** [comment]
I definitely like this better than #37730.  The addition of the initialization code and the conditionals based on that feel very wrong to me.  However, one thing I don't like about this PR is that I have to repeat the calls to reverse the list wherever the code is used.  Because of that, I think I'm currently leaning towards taking part of @alikins advice here... I think that we should have a Jinja2Loader which subclasses PluginLoader.  The only thing that would differ on is that it would reverse the list before returning it.

There's something bothering me about that strategy too but I think what it is is that most plugins either use all() or get().  There's not a lot of them which use both.  So it feels like subclassing isn't right because each class is actually implementing a different interface.  On the side for creating subclasses, though, is that it's better than the current situation.  Currently we have all of the code in one giant class but different types of loaders never exercise a large part of the code.  So separating out two of the three types which use all() might be the first step towards organizing this into the all() based plugins and the get() based plugins....  @sivel, if you like that idea, I'll convert this PR to using a Jinja2Loader subclass for the filter and test plugins and we can think on where to go from there for refactoring in the 2.7 timeframe.

**Comment by bcoca** [comment]
The only ones that need to load `all()`l are tests/filters as we need to pre-populate them inside jinaj2 for them to be available. Callbacks and vars plugins use it because of 'legacy autoloading'.

I do want to change how vars plugins are loaded so we can ship more with Ansible, probably have the same 'whitelist' property that callbacks have to keep backwards compatibility with existing 3rd party.

Callbacks are the only ones that use both `all` and `get`, for loading 'non stdout' and stdout ones respectively.

**Comment by sivel** [comment]
@abadger if you feel comfortable creating subclasses, go for it.  I think that would make things much more clear.

**Comment by abadger** [comment]
Test failure on rhel test host is an unrelated problem installing pigz for docker.  Noted earlier in the testing working group meeting.

@sivel ready for your review.

**Review by bcoca — APPROVED** [review]

**Pull request merged**
