### PR TITLE
Using correct content type (as per version 10 of ACME draft).

### LINKED ISSUE #37164: Letsencrypt: ACME v2 calls need to send correct Content-Type
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION
2.5.0

##### SUMMARY
From soon on, ACME v2 clients will be required to send the correct content type when sending requests to the server (see https://community.letsencrypt.org/t/jws-post-content-type-header-enforcement/55055). The ACME v2 production server will reject requests which don't have it from March 29th on.

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #37164.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION
2.5.0

##### ADDITIONAL INFORMATION
Needs to be fixed for ACME v2, as otherwise the client won't work from March 29th on. See https://community.letsencrypt.org/t/jws-post-content-type-header-enforcement/55055

### CODE REVIEW

**Comment by felixfontein** [comment]
Ok, I found two more bugs/problems. The second is a problem with the `ModuleFailException` class; apparently, in Python, `self.args` is reserved and will always be a tuple in subclasses of `Exception`. I'm using a different variable name now (c6f384c78e96214612e96904bd5031280717a922).

**Comment by felixfontein** [comment]
The first problem is that for ACME v2, Pebble no longer wants a content (such as `keyAuthorization`) when validating challenges. The fix 835285bf75e21b16bdd350a434a92d5ffb1c1356 works fine with the v1 staging server and with the Pebble v2 testing server. Unfortunately, it *does not* work with the current v2 staging server. There, I get an `urn:ietf:params:acme:error:malformed` error: `Unable to update challenge :: provided key authorization was incorrect`.

The change in Pebble was introduced in https://github.com/letsencrypt/pebble/commit/65f06474321e6ebb68e802d466478064fa2c7d16 and looks like it will be the new default behavior, so the behavior of the current v2 staging server seems to be incorrect. @cpu, can you confirm this?

**Comment by cpu** [comment]
Hi @felixfontein,

> The change in Pebble was introduced in letsencrypt/pebble@65f0647 and looks like it will be the new default behavior, so the behavior of the current v2 staging server seems to be incorrect. @cpu, can you confirm this?

You're right, the V2 staging server will not expect a `KeyAuthorization` shortly, this is fixed in master but isn't deployed to staging. [This commit](https://github.com/letsencrypt/boulder/commit/49d55d9ab56bb959d95b9f6baf00eaadb3192c72) should resolve this on Tuesday.

Apologies for making this awkward situation where your code works for Pebble but not V2 Staging (or vice versa). In retrospect it might have been better to wait to land that Pebble change until the V2 staging endpoint was updated.

**Comment by felixfontein** [comment]
Hi @cpu, thanks for confirming this! I wanted to verify this before we start merging this PR, as Ansible 2.5 will be released soon and these fixes should go into it before it is released. :)

@resmo: I think this PR is good to go. Can you take a look? Also, as said above, this should go into 2.5 as it fixes bugs there (one general bug, and two ACME-v2-specific ones). How should I proceed for this? Create a PR for a specific RC branch?

**Comment by cpu** [comment]
> Hi @cpu, thanks for confirming this! I wanted to verify this before we start merging this PR, as Ansible 2.5 will be released soon and these fixes should go into it before it is released. :)

No problem! Keep the questions coming :-) Thanks for working on Ansible support for ACMEv2!

**Comment by resmo** [comment]
@felixfontein perfect.

shipit

**Comment by resmo** [comment]
cherry-picking to 2.5

**Comment by resmo** [comment]
@felixfontein having a conflict in cherry-picking with some features, would you mind creating a PR against stable-2.5 branch with the necessary changes?

**Comment by felixfontein** [comment]
Sure, can do that! Thanks!

**Comment by felixfontein** [comment]
Done, see #37190. The problem was that the exception related changes weren't in the 2.5 branch, so one of the three commits wasn't needed after all. I created a PR with the changes from the other two commits.

**Comment by felixfontein** [comment]
Thanks everyone!

**Comment by felixfontein** [comment]
@cpu Now that the ACME v2 endpoint is deployed, I tried to get certificates with Ansible 2.5. But it seems that the deployed version of Boulder still doesn't accept the empty challenge response as mandated by https://tools.ietf.org/html/draft-ietf-acme-acme-10#section-7.5.1, which is the only Pebble accepts. I get `{'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Unable to update challenge :: provided key authorization was incorrect', 'status': 400}`. (The staging v2 endpoint seems to accept the correct challenge response.) Do you know when the real v2 endpoint will be updated so that it also accepts the correct challenge response?

**Comment by felixfontein** [comment]
Anyway, when sending the key authorization content, it does work! \o/ I just got a couple of valid wildcard certs for my domains! :)

**Comment by cpu** [comment]
>  Do you know when the real v2 endpoint will be updated so that it also accepts the correct challenge response?

@felixfontein This Thursday, March 15th. (If you want the gory details our current release process is documented here: https://github.com/letsencrypt/boulder-release-process)

> Anyway, when sending the key authorization content, it does work! \o/ I just got a couple of valid wildcard certs for my domains! :)

Glad to hear it! :tada: :lock: :tada:

**Comment by felixfontein** [comment]
@cpu Thanks a lot for your reply! Thursday is perfect :) And thanks for the document, that's definitely interesting.

**Comment by felixfontein** [comment]
@resmo @cpu @tiggi It looks like the change was deployed; I just was able to get a couple of non-wildcard, wildcard and mixed (like *.example.com and example.com in same cert) certificates using the client in Ansible's `stable-2.5` branch! :tada:

**Comment by cpu** [comment]
@felixfontein Yup! Deployed this afternoon. Thanks for confirming :+1: :tada:

**Comment by tiggi** [comment]
On 15/03/18 21:59, Felix Fontein wrote:
> @resmo <https://github.com/resmo> @cpu <https://github.com/cpu> @tiggi 
> <https://github.com/tiggi> It looks like the change was deployed; I just 
> was able to get a couple of non-wildcard, wildcard and mixed (like 
> *.example.com and example.com in same cert) certificates using the 
> client in Ansible's |stable-2.5| branch! 🎉

I'll test tomorrow morning and report back.
Thanks!

**Comment by tiggi** [comment]
On 15/03/18 21:59, Felix Fontein wrote:
> @resmo <https://github.com/resmo> @cpu <https://github.com/cpu> @tiggi 
> <https://github.com/tiggi> It looks like the change was deployed; I just 
> was able to get a couple of non-wildcard, wildcard and mixed (like 
> *.example.com and example.com in same cert) certificates using the 
> client in Ansible's |stable-2.5| branch! 🎉

Verified to be working for normal hostnames, but not for wildcards.

**Pull request merged**
