### PR TITLE
lineinfile: Added findfirst

### PR DESCRIPTION
**Pull request by trineliseavik**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
```
lineinfile
```
##### ANSIBLE VERSION
```
ansible 2.4

```

##### SUMMARY

```
 Used with C(state=present) and C(insertbefore) or C(insertafter). If specified, 
        the insert will be done with the first occurence.
```

### CODE REVIEW

**Comment by egkristi** [comment]
Works perfectly.

**Comment by trineliseavik** [comment]
How do i merge this branch?

**Comment by trineliseavik** [comment]
bot_status

**Comment by bcoca** [comment]
dupe of #33825

**Pull request closed without merging**
