### PR TITLE
Haiyuazhang management group

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

New module azure_rm_managementgroup ----- relate with #66047.
This module aimed to create/delete/update azure management group.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

azure_rm_managementgroup
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@haiyuazhang Would you please help take a look above error info? Why do we define "updatable=False" and "disposition='/'" variables when we initialize parameters? The error message above does not allow you to define additional parameters. Thank you very much!

**Comment by gundalow** [comment]
Should this go straight into the Azure collection?

**Comment by Fred-sun** [comment]
> Should this go straight into the Azure collection?

Yes, theoretically it should be created in the Azure collection, I will confirm with the community maintainer again, thank you very much for your reminding!

**Comment by Fred-sun** [comment]
@haiyuazhang Could you please help to confirm whether it will be created in Azure collection? Thank you very much!

**Comment by gavinfish** [comment]
shipit

**Review by haiyuazhang — APPROVED** [review]
shipit

**Comment by Fred-sun** [comment]
Hi All, Already added to [ansible-collections](https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_managementgroup.py), this PR will be turned off. Thank you very much!

**Pull request closed without merging**
