### PR TITLE
Implement nesting lookup plugins

### PR DESCRIPTION
**Pull request by srgvg**
As proposed at #4060

This should allow to implement everything and more
than currently is possible in the not documented, not supported,
soon to be deprecated include: + with_items: construct

```
  - debug: msg="{{item}}"
    with_flattened:
    - lookup('first_found', ['/etc/network/interfaces', '/etc/sysconfig/network'])
    - lookup('fileglob', '/boot/*')
    - lookup('file', '/etc/hostname')
    - lookup('lines', 'ls /boot/grub/')
    - lookup('pipe', 'hostname --fqdn')
    - lookup('sequence', 'start=5 end=10 stride=5')
```

A test playbook and it's output can be found at https://gist.github.com/sergevanginderachter/7092035

[Review on Reviewable](https://reviewable.io/reviews/ansible/ansible/4627)

### CODE REVIEW

**Comment by srgvg** [comment]
Note to reviewers: I'm not happy with how I did the parsing of the lookup() line, but I'm not sure how I should improve that. Pointers would very welcome!

**Comment by srgvg** [comment]
After 4 months, I'll allow myself to make a _bump_.

**Comment by jirutka** [comment]
+1

**Comment by srgvg** [comment]
Resolved merge conflicts due to the original patch's old age.

**Comment by mpdehaan** [comment]
Possibly cleaner as:

```
with_lookups:
    - first_found: <usual arguments>
    - fileglob: '/boot/*'
```

Or something?

**Comment by bcoca** [comment]
If i'm reading this correctly you just want to avoid writing:

```
   with_flattened:
    - "{{lookup('first_found', ['/etc/network/interfaces', '/etc/sysconfig/network'])}}"
```

I'm not sure we want to add more implicit templating as it makes it very problematic to report on undefined variables. Closing this for now but keeping it in mind for our current revamping of templating in general.

**Comment by srgvg** [comment]
Really guys? 
- The current implemention syntax was _very_ _explicitly_ demanded by @mpdehaan at the time. 
- @bcoca this did a lot more than your example; it's about having a way to nest lookups

Not constructive to suddenly close this after more than a year.

**Comment by bcoca** [comment]
I understand what was demanded at the time, we have more information now and we are shying away from implicit vs explicit templating.

I might be misunderstanding, but I took my example from yours, you can chain lookups and nest them already, you just need to be explicit about it.

**Comment by srgvg** [comment]
The inline {{ lookup(,,) }} thing is _afaik_ just resulting in a comma separated list, not a plain list that can be flattened with other lookups, so i don't see how we currently have an working alternative.

`we are shying away from implicit vs explicit templating`

I have no clue what that means. Is there something documented about that?
Is that some change to be expected to be more explicit in "v2"?

Given v2 is announced as the next release, 1.9, is actually usefull to submit patches on the current codebase?

**Comment by bcoca** [comment]
- afaik lookups return lists, I had been using them nested in my own playbooks for a while
- it means  when: {{ expression }} (explicit) vs when: expression (implicit), this does not mean we are breaking current functionality, but considering how problematic this is I shy away from adding more.
- v2 does not mean current is stopped, some features might be delayed as they are easier or better implemented in v2, I suggest posting to ansible-devel about new things before going through the effort.

**Pull request closed without merging**
