### PR TITLE
Add a 'capture' jinja2 filter

### PR DESCRIPTION
**Pull request by tartansandal**
This filter returns the string captured by an arbitrary regex capture group.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you please share some examples of this being used in a playbook or template?  (I'm trying to understand why the regex filter isn't sufficient, etc)

**Comment by tartansandal** [comment]
The regex filter just returns a boolean.  The capture filter returns the captured string.  This was inspired the thread "format url module output" from 9 days ago. David Neudorfer wanted to extract the error code from some XML spew that his web app was producing.  Here's the email snippet:

```

- debug: var=domain_name_purchase.content

To return the data I need. How do I drill down even further? 

I'd like to return "ApiResponse Status" and check if it was ERROR or SUCCESS and what "Error Number" is was

ok: [162.243.95.241] => {

    "domain_name_purchase.content": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<ApiResponse Status=\"ERROR\" xmlns=\"http://api.namecheap.com/xml.response\">\r\n  <Errors>\r\n    <Error Number=\"4014104\">Possible duplicate create command for unavailable domain. Try again after 11/20/2013 7:29:46 AM UTC</Error>\r\n  </Errors>\r\n  <Warnings />\r\n  <RequestedCommand>namecheap.domains.create</RequestedCommand>\r\n  <CommandResponse Type=\"namecheap.domains.create\">\r\n    <DomainCreateResult Domain=\"elitereceipt202321412341234.com\" ChargedAmount=\"0\" DomainID=\"0\" OrderID=\"0\" TransactionID=\"0\" WhoisguardEnable=\"false\" FreePositiveSSL=\"false\" NonRealTimeDomain=\"false\" />\r\n  </CommandResponse>\r\n  <Server>WEB1-SANDBOX1</Server>\r\n  <GMTTimeDifference>--5:00</GMTTimeDifference>\r\n  <ExecutionTime>0.02</ExecutionTime>\r\n</ApiResponse>", 

    "item": ""

}
```

Not exactly sure what he wants the "Error Number" for but I can imagine it being useful if he wants to send and email or a pager message.

I confess, I have no actual use for this in my current setup, but I do remember wanting to do this at some point in the past, so I thought it would be a harmless addition.

**Comment by tartansandal** [comment]
Also here's the example usage from the original pull request from 9 days ago
(before I messed up the PR by pushing to the wrong branch):

For example, if 

```
{{ foo_string }} 
```

gives us 

```
abc1234def
```

then

```
{{ foo_string | capture('abc(\d+)def') }}
```

gives us

```
1234
```

and

```
{{ foo_string | capture('abc(\d+)(\w+)', 2) }}
```

gives us

```
def
```

**Comment by sivel** [comment]
I would still like to think that this is achievable without adding an additional filter.

We have 'regex', 'match' and 'search'.  Right now they return boolean values.  We can easily extend these by adding an additional argument with a default value to specify that they should return booleans.  Something such as:

``` diff
diff --git a/lib/ansible/runner/filter_plugins/core.py b/lib/ansible/runner/filter_plugins/core.py
index 495e17e..6944a4e 100644
--- a/lib/ansible/runner/filter_plugins/core.py
+++ b/lib/ansible/runner/filter_plugins/core.py
@@ -99,7 +99,7 @@ def fileglob(pathname):
     ''' return list of matched files for glob '''
     return glob.glob(pathname)

-def regex(value='', pattern='', ignorecase=False, match_type='search'):
+def regex(value='', pattern='', ignorecase=False, match_type='search', boolean=True):
     ''' Expose `re` as a boolean filter using the `search` method by default.
         This is likely only useful for `search` and `match` which already
         have their own filters.
@@ -110,15 +110,19 @@ def regex(value='', pattern='', ignorecase=False, match_type='search'):
         flags = 0
     _re = re.compile(pattern, flags=flags)
     _bool = __builtins__.get('bool')
-    return _bool(getattr(_re, match_type, 'search')(value))
+    result = getattr(_re, match_type, 'search')(value)
+    if boolean:
+        return _bool(result)
+    else:
+        return result

-def match(value, pattern='', ignorecase=False):
+def match(value, pattern='', ignorecase=False, boolean=True):
     ''' Perform a `re.match` returning a boolean '''
-    return regex(value, pattern, ignorecase, 'match')
+    return regex(value, pattern, ignorecase, 'match', boolean)

-def search(value, pattern='', ignorecase=False):
+def search(value, pattern='', ignorecase=False, boolean=True):
     ''' Perform a `re.search` returning a boolean '''
-    return regex(value, pattern, ignorecase, 'search')
+    return regex(value, pattern, ignorecase, 'search', boolean)

 def unique(a):
     return set(a)
```

If `boolean=False` is passed to the filter, then it would return the standard data structure returned by each of those `re` methods, which would be usable from within jinja.

**Comment by tartansandal** [comment]
Hmm ... so with the above example, usage would be like

```
{{ foo_string | match('abc(\d+)', boolean=False).group(1) }}
```

that reads a bit odd to me.

**Pull request closed without merging**
