### PR TITLE
make debconf compare apples to apples (booleans)

### LINKED ISSUE #25481: debconf misreports changed status for boolean variables
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
debconf module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/pieter.nagel/setup/lautus_ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Nothing relevant

##### OS / ENVIRONMENT
Ubuntu 16.04.2 LTS

##### SUMMARY
When using debconf module to set a boolean value to true, the module keeps reporting a 'changed' status even if the value is already true.

##### STEPS TO REPRODUCE
Run the following task twice:

```yaml
- name: 'Accept the Oracle Java license'
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: boolean
    value: true
```

##### EXPECTED RESULTS
At least on the second run, I expect the task to show ok in green.

##### ACTUAL RESULTS
I see changed in yellow everytime. Running with --diff reveals that the module does not know that 'true' and 'True' are already the same value:
```
TASK [tau_common : Accept the Oracle Java license] ****
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "shared/accepted-oracle-license-v1-1": "true"
+    "shared/accepted-oracle-license-v1-1": "True"
 }

changed: [dev3.lautus.net]
```

### PR DESCRIPTION
**Pull request by bcoca**
hope to fix #25481

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

modules/debconf

### CODE REVIEW

**Comment by chemnic** [comment]
I think this is causing the following error:
```
MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/ansible_debconf_payload_1rgqczcg/__main__.py", line 191, in <module>
  File "/tmp/ansible_debconf_payload_1rgqczcg/__main__.py", line 164, in main
UnboundLocalError: local variable 'existing' referenced before assignment
```

**Comment by bcoca** [comment]
@chemnic i cannot reproduce, please open a new issue with a reproducer

**Comment by bcoca** [comment]
nvmd, foudn it .. i should test with 'non boolean'

**Comment by chemnic** [comment]
Yes. Fixed. Thank you.

**Pull request merged**
