### PR TITLE
docker_image: fix default handling of old docker-build options nocache and rm

### LINKED ISSUE #56588: Error when trying to build docker image with 'nocache: true' option on Ansible 2.8.0
##### SUMMARY

Ansible throws error when trying to build docker image with `nocache: true` option. If you remove that option it runs fine. On previous version 2.7.10 it runs fine

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_image

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /home/shash/git/evalink-live/ansible.cfg
  configured module search path = ['/home/shash/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```
Problem is not reproduces with Ansible 2.7.10

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/home/shash/git/evalink-live/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/shash/git/evalink-live/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/shash/git/evalink-live/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m -o IdentitiesO>
DEFAULT_CALLBACK_WHITELIST(/home/shash/git/evalink-live/ansible.cfg) = ['profile_tasks']
DEFAULT_LOCAL_TMP(/home/shash/git/evalink-live/ansible.cfg) = /home/shash/.ansible/tmp/ansible-local-13245fiqdtgo1
DEFAULT_TIMEOUT(/home/shash/git/evalink-live/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/shash/git/evalink-live/ansible.cfg) = False
```
Problem is not reproduces with Ansible 2.7.10.

##### OS / ENVIRONMENT

Arch Linux with kernel version 4.19.40-1-lts.  Problem reproduce on localhost and with the remote hosts

##### STEPS TO REPRODUCE

1. Upgrade Ansible to 2.8.0
2. Run playbook below on local on remote host

```yaml
---
- hosts: all
  tasks:
  - name: Build test docker image
    docker_image:
      nocache: true
      path: "."
      name: test-image
```
Place any Dockerfile in `.` - even simpliest one like this will do:
```
FROM node:6-slim
```

##### EXPECTED RESULTS

Built docker image

##### ACTUAL RESULTS

Playbook falls with the error
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Cannot specify both nocache and build.nocache!"}
```
But in verbose output `build.nocache` is not set:

```paste below
TASK [Build test docker image] **************************************
task path: /home/shash/tmp/bugg/test.yml:4
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: shash
<localhost> EXEC /bin/sh -c 'echo ~shash && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/shash/.ansible/tmp/ansible-tmp-1558107847.9550486-121646861135580 `" && echo ansible-tmp-1558107847.9550486-121646861135580="` echo /home/shash/.ansible/tmp/ansible-tmp-1558107847.9550486-121646861135580 `" ) && sleep 0'
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/docker/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/docker/common.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/file.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/process.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/_utils.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/parameters.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/validation.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/distro/_distro.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/common/collections.py
Using module file /usr/lib/python3.7/site-packages/ansible/modules/cloud/docker/docker_image.py
<localhost> PUT /home/shash/.ansible/tmp/ansible-local-6742wc5ulh4q/tmpbisonb1t TO /home/shash/.ansible/tmp/ansible-tmp-1558107847.9550486-121646861135580/AnsiballZ_docker_image.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/shash/.ansible/tmp/ansible-tmp-1558107847.9550486-121646861135580/ /home/shash/.ansible/tmp/ansible-tmp-1558107847.9550486-121646861135580/AnsiballZ_docker_image.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/shash/.ansible/tmp/ansible-tmp-1558107847.9550486-121646861135580/AnsiballZ_docker_image.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/shash/.ansible/tmp/ansible-tmp-1558107847.9550486-121646861135580/ > /dev/null 2>&1 && sleep 0'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "archive_path": null,
            "build": {},
            "buildargs": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "container_limits": null,
            "debug": false,
            "docker_host": "unix://var/run/docker.sock",
            "dockerfile": null,
            "force": null,
            "force_absent": false,
            "force_source": false,
            "force_tag": false,
            "http_timeout": null,
            "load_path": null,
            "name": "test-image",
            "nocache": true,
            "path": ".",
            "pull": null,
            "push": false,
            "repository": null,
            "rm": true,
            "source": null,
            "ssl_version": null,
            "state": "present",
            "tag": "latest",
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "use_tls": null,
            "validate_certs": false
        }
    },
    "msg": "Cannot specify both nocache and build.nocache!"
}
```
If you remove `nocache: true` from the playbook it creates docker image

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
docker_image crashes if `nocache` is set to `true` (instead of `build.nocache`). Also, if `build` is not set, `build.rm` has the wrong default. Fixes #56588.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_image

### CODE REVIEW

**Comment by felixfontein** [comment]
@DBendit @WojciechowskiPiotr @akshay196 @danihodovic @dariko @jwitko @kassiansun @softzilla @tbouvet it would be great if someone could review this, so we can get this merged!

**Comment by Andersson007** [comment]
@felixfontein , what about integration tests to be sure that these changes work as expected and don't break anything?

**Review by Andersson007 — CHANGES_REQUESTED** [review]
@felixfontein , what about integration tests to be sure that these changes work as expected and don't break anything?

**Comment by Andersson007** [comment]
!needs_revision

**Review by Andersson007 — APPROVED** [review]

**Pull request merged**
