### PR TITLE
Issue 46477 Fix Module onyx interface for supporting new json changes

### LINKED ISSUE #46477: onyx_interface module failed because of change in json output.
##### SUMMARY
Failed to run onyx_interface module because of changes in returned json output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/lib/ansible/modules/network/onyx/onyx_interface.py

##### ANSIBLE VERSION

``
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] 

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### STEPS TO REPRODUCE

```
- hosts: switch132
  gather_facts: no
  connection: network_cli
  become: yes
  vars: 
    ansible_network_os: onyx
  tasks:
    - onyx_interface:
         name: Eth1/2
        description: test-interface
        speed: 1G
        mtu: 3500
         

```

##### EXPECTED RESULTS
attached yml file should be passed successfully when run it

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY
Fixes #46477 by adding support for json changes

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
/lib/ansible/modules/network/onyx/onyx_interface.py

##### ANSIBLE VERSION

```
ANSIBLE VERSION
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ganeshrn** [comment]
@anasbadaha The PR contains merge commit. Please rebase the PR, refer https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html for steps to rebase

**Comment by ganeshrn** [comment]
@samerd As you are module author please review this PR

**Comment by samerd** [comment]
> @samerd As you are module author please review this PR

Reviewed: fine with me.

**Comment by ganeshrn** [comment]
@anasbadaha @samerd Thank you!

**Pull request merged**
