### PR TITLE
Facts subset and cleanup

### PR DESCRIPTION
**Pull request by abadger**
##### Issue Type:
- Feature Pull Request
##### Summary:

This builds on @Yannig's PR #13443 to implement a way to restrict fact gathering.  After discussion between Yannig, @bcoca and myself, the changes needed to also include a fix for FieldAttributes to transofmr comma separated strings into lists.  Further discussion with bcoca lead to merging the ability to exclude facter and ohai into the same configuration value/play parameter.  Documentation, code, and tests updated accordingly.  There will need to be an ansible-module-utils-core update to go along with this.  I'll submit that next.

### CODE REVIEW

**Comment by abadger** [comment]
@Yannig, @bcoca If you'll be so kind as to review this and https://github.com/ansible/ansible-modules-core/pull/3247 to see if it's suitable that would be great!

**Comment by nitzmahone** [comment]
fails from ad-hoc (eg ```ansible localhost -m setup```)- gather_subset should default to all...

**Comment by nitzmahone** [comment]
Oh yeah- :+1:

**Comment by abadger** [comment]
Latest commit makes the integration tests assert on failure.

**Comment by Yannig** [comment]
@abadger: well done :)
The way to exclude facts using '!' is a good idea.
Using ohai or facter as a subset option is also a good idea.
So, you can go ahead and merge this !

**Comment by abadger** [comment]
Thanks  @nitzmahone and @Yannig  for reviewing!  Thanks @Yannig for the first 90% of the work to get this feature started :-)

**Comment by Yannig** [comment]
@abadger You're welcome :)

**Pull request merged**
