### PR TITLE
openssl_* modules: private key errors

### LINKED ISSUE #54083: openssl_privatekey (and potentially openssl_csr and later openssl_certificate): problem with private key encryption tests with cryptography backend
##### SUMMARY
An issue so I don't forget about this :)

In the test runs for #53924, there was a [spurious failure](https://app.shippable.com/github/ansible/ansible/runs/114737/52/tests) in the openssl_privatekey tests:

```
02:38 TASK [openssl_csr : Generate publickey - PEM format] ***************************
02:38 fatal: [testhost]: FAILED! => {"changed": false, "msg": "Password was given but private key is not encrypted."}
02:38 ...ignoring
02:38 
02:38 TASK [openssl_csr : Generate publickey - PEM format] ***************************
02:38 fatal: [testhost]: FAILED! => {"changed": false, "msg": "Could not deserialize key data."}
02:38 ...ignoring
02:38 
02:38 TASK [openssl_csr : Generate publickey - PEM format] ***************************
02:39 fatal: [testhost]: FAILED! => {"changed": false, "msg": "Password was not given but private key is encrypted"}
02:39 ...ignoring
02:39 
02:42 TASK [openssl_csr : assert] ****************************************************
02:42 fatal: [testhost]: FAILED! => {
02:42     "assertion": "'assphrase' in passphrase_error_1.msg or 'assword' in passphrase_error_2.msg",
02:42     "changed": false,
02:42     "evaluated_to": false,
02:42     "msg": "Assertion failed"
02:42 }
```

For some reason, in https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L1289-L1332, instead of returning `Bad decrypt. Incorrect password?`, the error `Could not deserialize key data.` was created. But only once (and it didn't happen before as far as I know).

(The failure happened with cryptography==2.1.4 on OpenSUSE 15.1.)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_privatekey

##### ANSIBLE VERSION
```
2.8.0
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Hopefully fixes #54083.

Updates #53489.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssl_certificate
openssl_csr
openssl_pkcs12

### CODE REVIEW

**Comment by felixfontein** [comment]
Fixing the typos uncovered some more "strange" errors for PyOpenSSL: in some cases, it simply throws `OpenSSL.crypto.Error([])`. I'm converting that to `'Error while deserializing key'` now...

**Comment by felixfontein** [comment]
Main problem: what to do with input files we cannot parse? See #36738 / #53222.

**Comment by felixfontein** [comment]
Plan for this PR:
 - rebase to include the changes from #54085 (that should be merged first)
 - extract changes to openssl_* tests from #53222 (the WIP for invalid file handling for assessing the problem)
 - add fixes to change handling of invalid inputs

**Comment by felixfontein** [comment]
This is essentially ready. This PR contains #54085, so I'll keep it as WIP until #54085 is merged, and then I'll rebase and remove the WIP marker.

Feel free to already review this. Or help getting #54085 merged so this one can proceed :)

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
ready_for_review

**Comment by Shaps** [comment]
shipit

**Review by resmo — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
@Shaps @resmo thanks for reviewing and merging! :)

**Pull request merged**
