### PR TITLE
Split regular and handler results into their own queues

### LINKED ISSUE #69457: Using the free strategy with a mix of tasks and roles with handlers can lead to failure
##### SUMMARY

If you use the free strategy with a complex playbook that has a mix of regular tasks, roles and handlers, some nodes may fail because the strategy attempts to load ansible roles as files when handlers are run.

I tracked it down to the _do_handler_run in the lib/ansible/plugins/strategy/__init__.py because included_files are not check to see if they are a role before being included. 

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/free.py#L240-L259
vs
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/__init__.py#L1005-L1031

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

free.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/centos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS8

##### STEPS TO REPRODUCE

```yaml
TBD.
```

##### EXPECTED RESULTS

No error because it correctly loads the role

##### ACTUAL RESULTS

```paste below
fatal: [overcloud-novacompute-0]: FAILED! => {
    "reason": "Could not find or access '/home/centos/config-download/overcloud/tripleo_timezone' on the Ansible Controller. Traceback (most recent call last):\n  File \"/usr/lib/python3.6/site-packages/ansible/plugins/strategy/__init__.py\", line 869, in _load_included_file\n    data = self._loader.load_from_file(included_file._filename)\n  File \"/usr/lib/python3.6/site-packages/ansible/parsing/dataloader.py\", line 94, in load_from_file\n    (b_file_data, show_content) = self._get_file_contents(file_name)\n  File \"/usr/lib/python3.6/site-packages/ansible/parsing/dataloader.py\", line 162, in _get_file_contents\n    raise AnsibleFileNotFound(\"Unable to retrieve file contents\", file_name=file_name)\nansible.errors.AnsibleFileNotFound: Unable to retrieve file contents\nCould not find or access '/home/centos/config-download/overcloud/tripleo_timezone' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n"
}

```

### PR DESCRIPTION
**Pull request by jimi-c**
When mixed with the free strategy (or any custom strategy that does not behave in
a lock-step manner), the linear methodology of _wait_on_handler_results may cause
race conditions with regular task result processing if the strategy uses
_process_pending_results directly. This patch addresses that by splitting the queues
used for results and adding a flag to _process_pending_results to determine which
queue to check.

Fixes #69457

### CODE REVIEW

**Review by sivel — APPROVED** [review]
+1 from me. I don't know that I like the name `do_handlers`, but 🚲 🏠 .  We could make the kwarg, the actual results queue that you pass into the function. Or if omitted fall back.

**Comment by mwhahaha** [comment]
This is failing in my environment because the handler doesn't seem to actually be invoked when it needs to on the systems so subsequent tasks that assumed it works are failing.

To add a real world scenario, we have a role that adds kernel modules (br_netfilter) with a handler that reloads systemctl/modules and then a subsequent role that sets some sysctl values (net.bridge.bridge-nf-call-arptables). The handler is not being invoked prior to the task setting the sysctl values so its failing because /proc/sys/net/bridge/bridge-nf-call-iptables doesn't exist until the kernel module is loaded

**Comment by mwhahaha** [comment]
So actually it's just invoking a single role, https://github.com/openstack/tripleo-ansible/blob/master/tripleo_ansible/roles/tripleo_kernel/tasks/main.yml is the role. It's supposed to setup the kernel module, flush handler, configure sysctl values all in a run.  It's running the handler before moving on to the sysctl configuration.

**Comment by mwhahaha** [comment]
Ok I reran with a clean environment and this appears to properly invoke handlers as needed without the previously reported error.  +1

**Review by bcoca — APPROVED** [review]

**Review by mwhahaha — APPROVED** [review]
+1 Tested in my env and was successful with free

**Review by cloudnull — APPROVED** [review]
:+1:

**Pull request merged**
