### PR TITLE
Sshkey module without cluttered merges.

### PR DESCRIPTION
**Pull request by bradobro**
Michael, I'm re-submitting the sshkey module without the messy merges. I'll keep trying until I get it right.

### CODE REVIEW

**Comment by mpdehaan** [comment]
thanks, this is in queue for merging once we start 0.5

can you share some sample usage so we can know how to document it?

**Comment by bradobro** [comment]
Prelim docs are already in the module docstring.

--Brad Olson (from phone)
On May 12, 2012 12:26 PM, "Michael DeHaan" <
reply@reply.github.com>
wrote:

**Comment by mpdehaan** [comment]
Ok, some small review comments/changes:

(A)

I think to accept this we also should have a way to say in a playbook that we can pull in a string from a file, like so, since it is hard to update the keys if there are copies of them in multiple places.   Basically key=STRING is very cumbersome and I think we could easily do something like this:
- action:  sshkey key=[[/path/to/key/on/local/disk]] user=...

This should be doable in the template function of utils.py and it would just work magically throughout ansible

Basically it is introducing some new syntax for saying "get the contents of this file as a string and insert it right here".

(B)

No other modules have the debug option, so I think it's fair to always include the traceback, versus starting a convention where that has to be added to a lot of modules and remembering which have it.    Ansible's convention is to have the failure message in "msg", so you could just use exception.message in that case and it would be sufficient.

(C) 

From looking at enforce_state() it looks like the write is always triggered even if no change needs to be made.  This is not actually idempotent.  It would definitely trigger something watching the file for changes.    Can you make it such that it does not rewrite the file unless a change is needed?

(D)

Take care of these and I think we can merge this.   Though it is probably better named "authorized_key", so I think we also want to rename it?

**Comment by mpdehaan** [comment]
I will do (A), so don't worry about that one.  Think I promised to do that earlier.

The other three things should be pretty easy.  This looks good, thanks!

**Comment by bradobro** [comment]
Welcome. Yes, not sure I grok how to do A or have time to get my head into it. Will address the rest. Might be next week. My open source hours are about used up.

**Comment by mpdehaan** [comment]
You know how I feel :)

**Comment by bradobro** [comment]
This PR was based on 0.4's devel, and I must have messed up a rebase because it won't merge without a mess. So...pushed the diffs here for conversation/examination, but replacing with PR #433. Sorry bout that. 

CLOSE and use PR #433.

**Comment by mpdehaan** [comment]
closing per request

**Pull request closed without merging**
