### PR TITLE
Fix purefa_volume for QOS and erroneous delete

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Ensure that QOS parameters are only sent when the API version of the array supports them.
Ensure that rerunning a playbook over a deleted volume doesn't eradicate it unless specifically requested.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
purefa_volume

### CODE REVIEW

**Review by bblanham — CHANGES_REQUESTED** [review]
Concerning QOS:
Still getting the following error:

line 233, in update_volume
KeyError: 'bandwidth_limit'

you're still referencing vol_qos but it only gets assigned if flasharray supports the QOS API.

Concerning erroneous delete:
That appears to be working as I would expect.  Second delete on already deleted volume does not make a change.

**Comment by sdodsley** [comment]
@bblanham I think that has fixed it.

**Review by bblanham — APPROVED** [review]
Looks like latest changes fixed it.  Am able to update volume and delete is working as expected.

**Comment by genegr** [comment]
shipit

**Pull request merged**
