### PR TITLE
Only template values in vars_prompt rather than all vars

### LINKED ISSUE #37984: variable for hosts from vars_prompt no longer accepted
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

playbook

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### OS / ENVIRONMENT

Running from: Debian GNU/Linux 8.10 (jessie)

##### SUMMARY

hosts no longer accepts a variable from vars_prompt
This worked fine prior to version 2.5.0

##### STEPS TO REPRODUCE

```yaml
---
- hosts: "{{ target }}"
  vars_prompt:
    - name: target
      prompt: "Enter target(s) (separate by ',')"
      private: no
      when: target == ""
```

##### EXPECTED RESULTS

To be prompted for "targets" before execution, unless provided with -e "target=something"

##### ACTUAL RESULTS

```
ansible-playbook 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: upgrade-packages.yml ********************************************************************************************************************************************************************************
1 plays in playbooks/upgrade-packages.yml
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'target' is undefined

The error appears to have been in '/root/playbooks/upgrade-packages.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- hosts: "{{ target }}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

This allows the use of variables in vars_prompt fields as well as allows variables entered in the prompt to affect play vars rather than throwing an undefined error.

Fixes #37984

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
`playbook_executor.py`

##### ANSIBLE VERSION

```
2.6
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests due to traceback:

```
2018-04-25 15:52:23 Traceback (most recent call last):
2018-04-25 15:52:23   File "/root/ansible/bin/ansible-playbook", line 118, in <module>
2018-04-25 15:52:23     exit_code = cli.run()
2018-04-25 15:52:23   File "/root/ansible/lib/ansible/cli/playbook.py", line 122, in run
2018-04-25 15:52:23     results = pbex.run()
2018-04-25 15:52:23   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 152, in run
2018-04-25 15:52:23     batches = self._get_serialized_batches(new_play)
2018-04-25 15:52:23   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 247, in _get_serialized_batches
2018-04-25 15:52:23     if len(serial_batch_list) == 0:
2018-04-25 15:52:23 TypeError: object of type 'int' has no len()
```

**Comment by mattclay** [comment]
CI failure in integration tests due to traceback:

```
2018-07-12 17:42:44 Traceback (most recent call last):
2018-07-12 17:42:44   File "/root/ansible/bin/ansible-playbook", line 118, in <module>
2018-07-12 17:42:44     exit_code = cli.run()
2018-07-12 17:42:44   File "/root/ansible/lib/ansible/cli/playbook.py", line 122, in run
2018-07-12 17:42:44     results = pbex.run()
2018-07-12 17:42:44   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 152, in run
2018-07-12 17:42:44     batches = self._get_serialized_batches(new_play)
2018-07-12 17:42:44   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 247, in _get_serialized_batches
2018-07-12 17:42:44     if len(serial_batch_list) == 0:
2018-07-12 17:42:44 TypeError: object of type 'int' has no len()
```

**Comment by mattclay** [comment]
CI failure due to traceback in integration tests:

```
2018-07-27 18:43:11 the full traceback was:
2018-07-27 18:43:11 
2018-07-27 18:43:11 Traceback (most recent call last):
2018-07-27 18:43:11   File "/root/ansible/bin/ansible-playbook", line 118, in <module>
2018-07-27 18:43:11     exit_code = cli.run()
2018-07-27 18:43:11   File "/root/ansible/lib/ansible/cli/playbook.py", line 122, in run
2018-07-27 18:43:11     results = pbex.run()
2018-07-27 18:43:11   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 152, in run
2018-07-27 18:43:11     batches = self._get_serialized_batches(new_play)
2018-07-27 18:43:11   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 247, in _get_serialized_batches
2018-07-27 18:43:11     if len(serial_batch_list) == 0:
2018-07-27 18:43:11 TypeError: object of type 'int' has no len()
```

**Comment by dbpiv** [comment]
I have run the fix 47 times (various combinations of vars_prompt and passing extra-vars) and I have had no issues.

**Pull request merged**
