### PR TITLE
dynamodb_table: Use AnsibleAwsModule

### PR DESCRIPTION
**Pull request by sramakr**
##### SUMMARY

Support Boto3 for dynamodb_table module

Allows to support new features available with dynamodb_table.
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

dynamodb_table
##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = [u'/Users/sramak001/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sramak001/scratch/myenv/lib/python2.7/site-packages/ansible
  executable location = /Users/sramak001/scratch/myenv/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/84044/68/tests

**Comment by mattclay** [comment]
The Windows test failure is unrelated to this PR. The sanity test failures are valid.

**Comment by mattclay** [comment]
@sramakr Please [rebase your PR](https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html). That will restart the tests. If the tests fail after that, I'll take a look.

**Comment by sramakr** [comment]
@mattclay Thanks! I rebased the PR. Strange that shippable says it's success but still it's reported as CANCELED.

**Comment by sramakr** [comment]
@mattclay More of a general question, are there documentation or guidelines on doing unit testing? I mean, wanted to check if there are any aws modules unit tested with mock interface. I couldn't find any , but I want to be sure.

**Comment by mattclay** [comment]
@sramakr It looks like devel was merged into your branch instead of being rebased, since there are merge commits showing up on the PR now. The PR also still shows as having conflicts in the GitHub UI.

**Comment by mattclay** [comment]
@sramakr For unit testing AWS modules, take a look at the existing unit tests using placebo:

https://github.com/ansible/ansible/tree/devel/test/units/modules/cloud/amazon/

For general unit testing guides:

https://docs.ansible.com/ansible/devel/dev_guide/testing_units.html
https://docs.ansible.com/ansible/devel/dev_guide/testing_units_modules.html

If you have additional questions you may also want to join the #ansible-aws IRC channel on Freenode.

**Comment by sramakr** [comment]
@mattclay getting access denied exception for the default security token. but runs locally using my personal token.

**Comment by mattclay** [comment]
@sramakr We need to update our CI system to support the additional permissions, which is why it is working for you locally and not in CI.

**Comment by sramakr** [comment]
@mattclay awesome! thanks.

**Comment by sramakr** [comment]
@mattclay Is the CI/CD fixed? Also, need reviews for this PR. Do you know who I should request it from? Appreciate the help. Thanks.!

**Comment by mattclay** [comment]
@sramakr This PR is still on the list waiting for CI updates:

https://github.com/ansible/ansible/issues?utf8=%E2%9C%93&q=label%3Aneeds_ci_update+

As for  review, I recommend asking in the #ansible-aws IRC channel on Freenode.

**Comment by davehewy** [comment]
@sramakr having followed a chain of comments I found myself at your PR. Though you upgrade this to boto3 (which is great :)). You didn't implement the missing feature you originally set out to. SSE? Would it not be worth squeezing it into this PR?

**Comment by sramakr** [comment]
@DaveHewy  True :-) Actually that's how I started this PR. I should be able to update with SSE change.

**Comment by davehewy** [comment]
@sramakr i've done this for you, as it was required for some work i was doing yesterday. i used your existing pr and blitzed in the missing functionality. feel free to source it from here - https://github.com/DaveHewy/ansible/blob/boto3_dynamodb_table_sse_stream/lib/ansible/modules/cloud/amazon/dynamodb_table.py

fyi - the update functionality for SSE is not available yet. For example transitioning a table via an update_table() from no SSE to SSE does not work after creation. The feature is stated as coming soon! Plus the update functionality is very messy in this module. I had to have a shower after finishing this quick code edition :)

Exact boto3 error msg
```
The error was: ClientError: An error occurred (ValidationException) when calling the UpdateTable operation: One or more parameter values were invalid: Update table encryption is coming to your account soon
```

**Comment by sramakr** [comment]
@DaveHewy Thanks for the feedback. I need to take some time to clean this module and properly reorganize. Just didn't couldn't get to it. Thanks again, I will test this functionality as well.

**Comment by sramakr** [comment]
@DaveHewy Refer to https://github.com/ansible/ansible/issues/39538#issuecomment-419079157 Seems like amazon started default encryption at rest for dynamodb tables.

**Comment by davehewy** [comment]
@sramakr have you had a chance to work on this anymore?

**Comment by sramakr** [comment]
@DaveHewy Yes, I will have an updated PR this weekend.

**Comment by sramakr** [comment]
@DaveHewy Updated commit with SSE and Streams. Probably need to add integration and unit test.

**Comment by krotscheck** [comment]
Return type should probably include the stream ARN.

**Comment by jillr** [comment]
Hi @sramakr, I'm really sorry for how long it took to get this looked at. I'm updating the CI policies now in https://github.com/mattclay/aws-terminator/pull/66, however there are 2 test assertions that are incorrect.  In these assertions:
test/integration/targets/dynamodb_table/tasks/main.yml:37
test/integration/targets/dynamodb_table/tasks/main.yml:56

The actual message returned by the previous task is `"message": "The security token included in the request is invalid."`.  It's possible this is something that changed on AWS' side, that's been known to happen.  If anyone is able to pick this PR back up it would be great to get it rebased and updated.

**Comment by sramakr** [comment]
Thanks @jillr ! it's been a long time, since I did this, need some time to catch up. But I will try my best to review and rebase.

**Comment by anryko** [comment]
@sramakr could you please add new `create_table` on-demand resource provisioning feature as well?
```
BillingMode='PROVISIONED'|'PAY_PER_REQUEST'
```

**Comment by anryko** [comment]
Added a PR with `billing_mode` and `point_in_time_recovery`: https://github.com/sramakr/ansible-1/pull/1

**Comment by anryko** [comment]
@sramakr are you planning on finishing this any time soon or should I present my PR directly to ansible repo as a new one?

**Comment by sramakr** [comment]
Thanks Andrej,

I will finish up the PR asap.

Thanks
Sriram

**Comment by Akasurde** [comment]
Hi @sramakr, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
