### PR TITLE
Fix exception with load_provider function

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Fix exception when using ios_user on connection=local

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test ios_user

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now b56f507f03cfe1fb782027b80f71a4f0b1af352e

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 65a98aa4123776c8b619ac27ff5b99b2af16c55b

**Comment by danielmellado** [comment]
Hi @pabelanger I don't think the OSX run would matter to this. Would there be any way to skip it to be run for network integration?

**Comment by pabelanger** [comment]
I'm not to sure to be honest, will have to wait until somebody else answers.

**Review by trishnaguha — APPROVED** [review]
LGTM. I believe this is the fix on the top of https://github.com/ansible/ansible/pull/56271. Requesting @qalthos to review. This should also fix the opened issue https://github.com/ansible/ansible/issues/56737

**Review by Qalthos — APPROVED** [review]

**Pull request merged**
