### PR TITLE
Fix changing of nic parameters in vmware_guest

### PR DESCRIPTION
**Pull request by McNetic**
##### SUMMARY
Currently, changing the parameters of a nic via vmware_guest does not correctly us pyvmomi api. This pull request fixes that and thus makes it possible for example to change a nic's mac address.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@McNetic Thanks for your PR. Could you please add integration test for this change ? You can start [here](https://github.com/ansible/ansible/blob/devel/test/integration/targets/vmware_guest/tasks/main.yml).

**Comment by Akasurde** [comment]
There is a failure in https://app.shippable.com/github/ansible/ansible/runs/49740/55/console
```
"msg": "The conditional check 'clone_d1_c1_f0.results[0]['instance']['hw_eth0']['addresstype'] == 'manual'' failed. The error was: error while evaluating conditional (clone_d1_c1_f0.results[0]['instance']['hw_eth0']['addresstype'] == 'manual'): 'dict object' has no attribute 'instance'" }
```

**Comment by McNetic** [comment]
Yes, I noticed. I don't know how to execute the test locally, so I have to take some time to figure why it fails... I suppose some parameters have to be left out when changing the vm... Please ignore this until I fixed the test...

**Comment by mattclay** [comment]
@McNetic You can run the tests locally by running `source hacking/env-setup` and then `ansible-test integration vmware_guest --docker -v`. This will run the tests using docker containers, so you'll need to have docker available.

**Comment by mattclay** [comment]
CI failure in integration tests:

https://app.shippable.com/github/ansible/ansible/runs/50102/56/tests

**Comment by Akasurde** [comment]
@McNetic Any news ?

**Comment by McNetic** [comment]
No, sorry. Currently, I have no time to look into this.

**Comment by Akasurde** [comment]
@McNetic Could you please rebase the branch and we can take this forward ?

**Comment by McNetic** [comment]
Well, I rebased the changes and tested it again on my esx host. I don't see why it fails in the tests. Unfortunately, I currently cannot contribute more time to this...

**Comment by Akasurde** [comment]
Closing this issue due to inactivity. Feel free to rebase PR and submit again. 

Thanks for the contribution.

**Pull request closed without merging**
