### PR TITLE
Mongo Inventory

### PR DESCRIPTION
**Pull request by prakritish**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

mongo.py
mongo.ini

##### ANSIBLE VERSION

```
[root@prakritish1 ~]# ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[root@prakritish1 ~]#
```

##### SUMMARY

This is an inventory module which allows users to user Mongo DB to
store inventory information. As ansible allows various hostvars, I thought
it's much more simpler to use Mongo to store relevant information in a
collection rather than using SQL with empty columns.

```
[root@prakritish1 inventory]# ./mongo.py --list
{"web": ["prakritish3.mylabserver.com"], "_meta": {"hostvars": {"prakritish3.mylabserver.com": {"ansible_become_user": "root", "ansible_become": true, "ansible_ssh_pass": "abcde12345", "ansible_user": "user", "ansible_become_pass": "abcde12345"}}}}
[root@prakritish1 inventory]# ./mongo.py --host prakritish3.mylabserver.com
{"ansible_become_user": "root", "ansible_become": true, "ansible_ssh_pass": "abcde12345", "ansible_user": "user", "ansible_become_pass": "abcde12345"}
[root@prakritish1 inventory]# ansible -i ./mongo.py prakritish3.mylabserver.com -m command -a "/sbin/ifconfig"
prakritish3.mylabserver.com | SUCCESS | rc=0 >>
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.31.31.229  netmask 255.255.240.0  broadcast 172.31.31.255
        inet6 fe80::4f3:58ff:fe4a:4d67  prefixlen 64  scopeid 0x20<link>
        ether 06:f3:58:4a:4d:67  txqueuelen 1000  (Ethernet)
        RX packets 1173  bytes 337505 (329.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1225  bytes 150710 (147.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 18  bytes 1136 (1.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1136 (1.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@prakritish1 inventory]#
```

### CODE REVIEW

**Comment by mattclay** [comment]
Please [rebase](https://docs.ansible.com/ansible/dev_guide/developing_rebasing.html) your PR to re-run CI.

**Comment by prakritish** [comment]
The PR is rebased as requested!

**Comment by gundalow** [comment]
Close/open to trigger CI

**Comment by Akasurde** [comment]
Please submit a new inventory plugin request to https://github.com/ansible-collections/community.general. Thanks for your contribution.

**Pull request closed without merging**
