### PR TITLE
s3_bucket: add check mode support

### PR DESCRIPTION
**Pull request by zyv**
##### SUMMARY
This PR adds check mode support to `s3_bucket`.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
s3_bucket

### CODE REVIEW

**Comment by s-hertel** [comment]
Please add [tests](https://github.com/ansible/ansible/tree/devel/test/integration/targets/s3_bucket) for check mode.

**Comment by zyv** [comment]
@catcombo, could you please have a go at the integration tests? I believe that it shouldn't be too complicated...

From what I've gathered after having a glance at the linked directory, you just need to go into tasks subdirectory and duplicate mutating blocks so that they come first and feature `check_mode: yes` - the assertions must still work, however, and subsequent copies that run with `check_mode: no` should still perform requested changes.

**Comment by felixfontein** [comment]
Code looks good, and I agree having tests would be nice.

> From what I've gathered after having a glance at the linked directory, you just need to go into tasks subdirectory and duplicate mutating blocks so that they come first and feature `check_mode: yes` - the assertions must still work, however, and subsequent copies that run with `check_mode: no` should still perform requested changes.

Exactly. I'm not sure how the AWS tests currently look like, but the "optimal" pattern is to do every thing four times:
 1) once with check mode - should change
 2) once without check mode - should change
 3) once with check mode - should not change (idempotency)
 4) once without check mode - should not change (idempotency)

(The order of 3 and 4 can of course be swapped.)

If idempotence checks aren't there yet, I would just add 1) and leave 3)+4) for later. (Except if you have time - idempotence checks are always good to have!)

**Comment by felixfontein** [comment]
There are a couple of tests which don't have check mode pendants:
 - Create more complex s3_bucket
 - Try to update the same complex s3_bucket
 - Remove a tag for s3_bucket
 - Do not specify any tag to ensure previous tags are not removed
 - Remove all tags
 - Create bucket with dot in name

Is this intentional?

**Comment by Akasurde** [comment]
Hi @zyv, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
