### PR TITLE
Declare list as a literal

### PR DESCRIPTION
**Pull request by remyleone**
##### SUMMARY

Declare list as literal to make them more efficient.

##### ISSUE TYPE

 - Bugfix Pull Request

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.6.0 (fix_deprecated cbdae1b688) last updated 2018/04/06 11:13:21 (GMT +200)
  config file = None
  configured module search path = [u'/Users/sieben/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sieben/workspace/ansible/lib/ansible
  executable location = /Users/sieben/workspace/ansible/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### CODE REVIEW

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this PR because this is sweeping change over many systems and modules, which makes it very hard to revise and test for a minor speed gain, which is not that relevant in when it comes to modules. We prefer that changes of this nature be done 'opportunistically' when already updating the code for other reasons.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourageopen dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by bcoca** [comment]
@sieben In any case, if you want to submit PRs for this change for specific systems/modules we are open to it, the 'sweeping' nature of this PR is what we mostly have an issue with.

**Comment by remyleone** [comment]
So you would prefer to have 20 pull requests rather than a single one?
Would they be merged?

**Comment by abadger** [comment]
Additionally, in general it is easier to make changes than to get reviews of the changes.  So you should optimize for people to review your PRs.  This means, opening separate PRs for each module (or in some cases, a group of modules that has an organized set of people working on that group).  I sometimes will review and merge micro-optimizations (you can ping me, I'm abadger1999 on IRC) but I would be more hesitant to do so for code which another team is making the decisions for.  So separating the changes to modules and plugins from the changes to the core engine would be essential for getting me to review the core engine changes.

**Comment by abadger** [comment]
@sieben n In regards to whether the 20 pull requests would be merged... for modules, that depends on the maintainers of each module.  I will commit to reviewing and merging (if the code is good) list-as-literal changes for core code.  Ping me on IRC (abadger1999 on irc.freenode.net, #ansible-devel channel) when it's ready so that I can look at it.

**Pull request closed without merging**
