### PR TITLE
module_utils/avi.py: fix broken import

### PR DESCRIPTION
**Pull request by pilou-**
##### SUMMARY
Fix [broken import](https://github.com/ansible/community/wiki/Testing%3A-progress-tracker#fixing-broken-imports) in `module_utils/avi.py`.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
module_utils/avi.py

##### ANSIBLE VERSION

```
ansible-playbook 2.5.0 (devel c9f2b931db) last updated 2017/09/07 17:22:11 (GMT +200)
```

### CODE REVIEW

**Comment by grastogi23** [comment]
Hi @pilou- 
The current code is based off [PEP 440](https://www.python.org/dev/peps/pep-0440/). I also double checked from other websites. In case of Avi both would work. I just want to make sure there is good reason for it. Using LooseVersion is only PEP 386 compatible which has superseded by PEP440. Also, this shouldn't be breaking imports.

+label needs_triage

**Comment by pilou-** [comment]
[`test/sanity/import/skip.txt`](https://github.com/ansible/ansible/pull/29116/files#diff-82900ce059a532a9a7309cb0856adbab) contains `lib/ansible/module_utils/avi.py`. That means that `module_utils/avi.py` fails to pass import sanity test. This can be tested using `ansible-test` command:
```
$ ansible-test sanity --test import --python 3.6

Sanity check using import with Python 3.6
ERROR: Found 1 import issue(s) on python 3.6 which need to be resolved:
ERROR: lib/ansible/module_utils/avi.py:36:0: ModuleNotFoundError: No module named 'pkg_resources'
```

`pkg_resources` is not part of the Python standard library and isn't a dependency of `avi` module: then `pkg_resources` package could be missing on the target host. On the other hand, `distutils.LooseVersion` is included in the Python standard library.

**Comment by grastogi23** [comment]
ok sounds good. 
-label needs_triage
+label shipit

**Review by grastogi23 — APPROVED** [review]

**Comment by pilou-** [comment]
Pull request rebased due to a conflict on `test/sanity/import/skip.txt`.

@grastogi23: you will need to re add a `shipit` comment (shipit count is reset after a rebase).

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@grastogi23 @pilou- Should this go into `devel` and `stable-2.4`?

**Comment by pilou-** [comment]
@gundalow It isn't required: successful `import` sanity test is not a goal of 2.4, besides there are other modules which aren't fixed yet.

**Pull request merged**
