### PR TITLE
Add Digital Ocean private networking, virtio parameters

### PR DESCRIPTION
**Pull request by jdnier**
New private_networking and virtio parameters have been added to dopy.py. This patch updates the argument_spec so Ansible will allow them, adds documentation, and enables these options.

### CODE REVIEW

**Comment by mpdehaan** [comment]
short code review note:

instead of choices=BOOLEANS this should use type=bool  (see other modules doing this)

**Comment by mpdehaan** [comment]
If this was added recently, do we need to do any checking against whether the dopy module is new enough and catch exceptions and raise a friendly error if not?

**Comment by jdnier** [comment]
So, to clarify,

```
virtio = dict(type='bool', choices=BOOLEANS, default='yes')
```

should be

```
virtio = dict(type='bool', default='yes')
```

correct? It seems to be done both ways. For example,

```
~/git/ansible/library/cloud
% grep bool *       
+ digital_ocean:            virtio = dict(type='bool', choices=BOOLEANS, default='yes'),
+ digital_ocean:            private_networking = dict(type='bool', choices=BOOLEANS, default='no'),
* digital_ocean:            wait = dict(type='bool', choices=BOOLEANS, default='yes'),
  ec2_ami:            wait = dict(type="bool", default=False),
  ec2_ami:            no_reboot = dict(default=True, type="bool"),
* linode:            wait = dict(type='bool', choices=BOOLEANS, default=True),
  quantum_network:            router_external                 = dict(default=False, type='bool'),
  quantum_network:            shared                          = dict(default=False, type='bool'),
  quantum_network:            admin_state_up                  = dict(default=True, type='bool'),
  quantum_router:        admin_state_up                  = dict(type='bool', default=True),
* rax:            wait = dict(type='bool', choices=BOOLEANS),
* rax_clb_nodes:            wait=dict(default=False, choices=BOOLEANS, type='bool'),
  rds:            multi_zone        = dict(type='bool', default=False),
  rds:            upgrade           = dict(type='bool', default=False),
  rds:            wait              = dict(type='bool', default=False),
  rds:            apply_immediately = dict(type='bool', default=False),
* route53:            overwrite       = dict(required=False, choices=BOOLEANS, type='bool')
  s3:            overwrite      = dict(default=False, type='bool'),
```

Should `type='bool'` and `choices=BOOLEANS` ever appear together?

There are other examples elsewhere.

```
~/git/ansible/library
% find . -type f | xargs grep BOOLEANS | grep bool
./packaging/zypper:            disable_gpg_check = dict(required=False, default='no', choices=BOOLEANS, type='bool'),
./packaging/yum:                                   choices=BOOLEANS, type='bool'),
./net_infrastructure/dnsmadeeasy:            #hardlink=dict(requred=False, default=False, type='bool', choices=BOOLEANS)
./web_infrastructure/htpasswd:        create=dict(type='bool', choices=BOOLEANS, default='yes'),
./system/service:            enabled = dict(choices=BOOLEANS, type='bool'),
./system/user:            generate_ssh_key=dict(choices=BOOLEANS, type='bool'),
./notification/mqtt:            retain = dict(default='no', choices=BOOLEANS, type='bool'),
./cloud/linode:            wait = dict(type='bool', choices=BOOLEANS, default=True),
./cloud/route53:            overwrite       = dict(required=False, choices=BOOLEANS, type='bool')
./cloud/digital_ocean:            virtio = dict(type='bool', choices=BOOLEANS, default='yes'),
./cloud/digital_ocean:            private_networking = dict(type='bool', choices=BOOLEANS, default='no'),
./cloud/digital_ocean:            wait = dict(type='bool', choices=BOOLEANS, default='yes'),
./cloud/rax:            wait = dict(type='bool', choices=BOOLEANS),
./cloud/rax_clb_nodes:            wait=dict(default=False, choices=BOOLEANS, type='bool'),
```

**Comment by jdnier** [comment]
Yes, it was added recently. Using dopy < 0.2.2 would result in a TypeError if Droplet.add() is called, due to unrecognized arguments. I've added a try/except block and call fail_json() when an exception is raised.

**Comment by mpdehaan** [comment]
This was just added by another pull request, take a look and see if you would like to tweak it any.

Sorry for the redundancy!   Lots of interest in this feature :)

**Comment by jdnier** [comment]
Looks largely the same. However, your original concern about the proper use of type=bool is still not addressed. Here's what you said above:

```
short code review note:
instead of choices=BOOLEANS this should use type=bool (see other modules doing this)
```

And here's the code (same in both pull requests):

```
+            virtio = dict(type='bool', choices=BOOLEANS, default='yes'),
+            private_networking = dict(type='bool', choices=BOOLEANS, default='no'),
```

Is that still a concern? As I pointed out in comments above, it seems inconsistently applied across various modules. Would you clarify what intended usage should be?

**Pull request closed without merging**
