### PR TITLE
docker_service: parse scale parameter correctly to 2.7

### PR DESCRIPTION
**Pull request by danihodovic**
##### SUMMARY
Backporting https://github.com/ansible/ansible/pull/45508 to 2.7.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_service

### CODE REVIEW

**Comment by danihodovic** [comment]
@felixfontein @jwitko mind having a look at this one :) ?

**Comment by jwitko** [comment]
@danihodovic Maybe this just needs a rebase but I'm seeing changes in this PR that are identical to https://github.com/ansible/ansible/pull/45508 ? 

Edit:  I'm seeing that this is clearly meant to be a back-port, but I'm unclear on how that works?  to me it looks like identical changes being merged in to the same `devel` branch ?

**Comment by danihodovic** [comment]
@jwitko I targeted the wrong base branch. My bad

**Comment by felixfontein** [comment]
Haha, I see you already found out yourself how to do backports. I guess I should have read the other mails first before writing [this](https://github.com/ansible/ansible/pull/45508#issuecomment-430786223) :D

**Review by felixfontein — APPROVED** [review]
shipit

Can you also create a backport PR for 2.6?

**Comment by danihodovic** [comment]
> Haha, I see you already found out yourself how to do backports. I guess I should have read the other mails first before writing this :D

The Ansible docs were very straightforward when it came to this.
https://docs.ansible.com/ansible/2.5/community/development_process.html#backport-pull-request-process

I'm eager to patch this because I need it for my own work :) 


> Can you also create a backport PR for 2.6?

Sure thing :+1:

**Comment by felixfontein** [comment]
In any case, don't worry that this PR will be kept open for some time. Even if backport PRs are `shipit`ed, they won't be merged automatically, but will wait until the release manager for the release this backport is for merges them manually. This usually happens 1-3 days before release. 2.7.0 was released two weeks ago, so 2.7.1 will probably be released next week or the week after.

**Comment by danihodovic** [comment]
> In any case, don't worry that this PR will be kept open for some time. Even if backport PRs are shipited, they won't be merged automatically, but will wait until the release manager for the release this backport is for merges them manually. This usually happens 1-3 days before release. 2.7.0 was released two weeks ago, so 2.7.1 will probably be released next week or the week after.

Sounds good. Thank you for all the help in this process!

Do you think it's a good idea to submit backports for 2.5?

**Comment by felixfontein** [comment]
I don't think so; the [release announcement of 2.5.10](https://groups.google.com/forum/#!msg/ansible-project/39WHM9rQuqY/Rb1pgcA3AQAJ) said:

> 2.5.10 is the last scheduled release in the 2.5 series as it transitions to "critical security fixes only". Future 2.5 series releases will be made only if security issues are discovered that are deemed critical enough to be backported and released.

**Comment by abadger** [comment]
merged for the 2.7.1 release

**Pull request merged**
