### PR TITLE
Yet another trivial fix for PyDev

### PR DESCRIPTION
**Pull request by rlewczuk**
For some reason PyDev does not recognize ansible.runner import. Dunno why, so it was simpler to narrow down this import a bit.

### CODE REVIEW

**Comment by rlewczuk** [comment]
One more bugfix in file module - it wasn't deleting dangling symlinks (pointing to nowhere) it was supposed to do when state=absent.

**Comment by mpdehaan** [comment]
tip for later -- please don't mix commits -- start a new branch for each new topic you are working on

**Comment by mpdehaan** [comment]
in queue to review commit 1 and 3 in the next day or so.   Will be manually merging to avoid the merge commit.

"git rebase" is generally a good way to avoid merge commits (versus using git pull -u or git merge, git pull --rebase is equivalant)

**Comment by rlewczuk** [comment]
Sorry for that (I'm still learning how to use git). Hopefully these two are one-liner and two-liner :)

**Comment by mpdehaan** [comment]
manually cherry picked and pushed back up to devel.

thanks!

**Pull request closed without merging**
