### PR TITLE
Add posix groups to the list of returned facts

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by bcoca** [comment]
we already have the getent module doing this, do we really need to add this to the standard facts?

**Comment by mscherer** [comment]
Indeed, didn't see this module. I personally prefer when I do not need to run extra modules for getting facts, but yeah, maybe that's not needed...

**Comment by hloeffler** [comment]
wasn't there the idea of having "get_facts" modular/configurable?
I don’t want it any slower than now.

**Comment by bcoca** [comment]
So someone brought up that on some systems with many users/groups this can take along time.

I would either defer to the getent module or add this as a modular option to fact gathering, off by default

**Comment by mscherer** [comment]
Let's do that with getent, closing the PR

**Pull request closed without merging**
