### PR TITLE
Add os_nova_service

### PR DESCRIPTION
**Pull request by mnaser**
##### SUMMARY
This module is useful for maintenance tasks such as disabling
a compute node in order to perform maintenance operations on it.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
os_nova_service

### CODE REVIEW

**Comment by mnaser** [comment]
The third party check error is unrelated.

**Comment by mnaser** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by Akasurde** [comment]
@mnaser Thanks for the contribution. Closing as per above.

**Pull request closed without merging**
