### PR TITLE
iam.py: return iam.role dict when creating roles

### PR DESCRIPTION
**Pull request by patlachance**
##### SUMMARY

I couldn't find an easy way to retrieve the 'role_id' associated to a given AWS IAM role.

The 'iam_role' module returns the 'role_id' but providing 'assume_role_policy_document' is mandatory, which is cumbersome when you just need to fetch the 'role_id' of a existing role.

Example use case where the 'role_id' is required: [restrict access to S3 Buckets to specific IAM roles](https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/)

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

modules/cloud/amazon/iam.py

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### ADDITIONAL INFORMATION

```
Before this patch
    "role_result": "role_name": "my-new-role"

After this patch
    "role_result": {
        "arn": "arn:aws:iam::A1B2C3D4E5F6:role/my-new-role",
        "assume_role_policy_document": "%7B%22Version%22%3A%222012-10-17%22%2C%22Statement%22%3A%5B%7B%22Effect%22%3A%22Allow%22%2C%22Principal%22%3A%7B%22Service%22%3A%22ec2.amazonaws.com%22%7D%2C%22Action%22%3A%22sts%3AAssumeRole%22%7D%5D%7D",
        "create_date": "2017-09-02T14:32:23Z",
        "path": "/",
        "role_id": "AROAA1B2C3D4E5F6G7H8I",
        "role_name": "my-new-role"
    }, 
```

### CODE REVIEW

**Comment by patlachance** [comment]
Not sure what is the meaning of the 'stale_ci' tag. Any action needed on my side?

**Comment by patlachance** [comment]
@samdoran anything else needed to get this code merged?

**Review by juliedavila — APPROVED** [review]

**Comment by juliedavila** [comment]
shipit

**Comment by samdoran** [comment]
rebuild_merge

**Pull request merged**
