### PR TITLE
New Module: Na_ontap_unix_user

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Manage Unix users on a ONTAP system

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
* na_ontap_unix_user

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by carchi8py** [comment]
It looks like the test "no-get-exception" is catching things that are not issue

We have a function called test_get_exception which is not related to the function get_exception() your trying to prevent. 

    def test_get_exception(self):
        set_module_args(self.mock_args())
        with pytest.raises(AnsibleFailJson) as exc:
            self.get_user_mock_object('user-fail').get_unix_user()
        assert 'Error getting UNIX user' in exc.value.args[0]['msg']

**Comment by mattclay** [comment]
I'm working on a fix right now. I'll re-run the tests once it's merged.

**Comment by carchi8py** [comment]
Ok @mattclay should i not add na_ontap_unix_user.py to the no-get-exception.py exception list then? If so i'll revert that change.

**Comment by mattclay** [comment]
@carchi8py Yes, you can revert that change now. The test has been fixed.

**Comment by beeankha** [comment]
I ran the test locally and it ✔️

**Review by beeankha — APPROVED** [review]
lgtm

**Review by lonico — APPROVED** [review]
shipit

**Pull request merged**
