### PR TITLE
Fix URL in dev_guide documentation

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/developing_modules_general.rst
docs/docsite/rst/dev_guide/developing_modules_checklist.rst

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Review by dharmabumstead — APPROVED** [review]

**Comment by dharmabumstead** [comment]
Looks good to me. @gundalow, please have a look and merge if you're OK with it.

Thanks @Akasurde!

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Thanks :)

**Comment by Akasurde** [comment]
@gundalow @dharmabumstead Thanks for reviews and comments.

**Pull request merged**
