### PR TITLE
Adds integration test steps to win_regedit test to cover Extras 2090

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

```
ansible 2.2.0 (tests_for_extras_2090 14cadeb1eb) last updated 2016/04/28 08:45:24 (GMT +100)
  lib/ansible/modules/core: (detached HEAD f3fef24e49) last updated 2016/04/28 08:41:46 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 0b66156f25) last updated 2016/04/28 08:41:46 (GMT +100)
  config file = 
  configured module search path = Default w/o overrides

```
##### SUMMARY

Adds a small test to win_regedit to cover the change I made under ansible modules extra 2090.

Fix has already been merged this is just about increasing test coverage

```
Run as follows:
add windows hosts to inventory as per windows setup instructions.

cd test/integration
export TEST_FLAGS='-i /etc/ansible/hosts -t test_win_regedit'
time make test_winrm 

```

### CODE REVIEW

**Comment by dagwieers** [comment]
@jhawkesworth Why were these integration tests never merged ?

**Comment by jhawkesworth** [comment]
@dagwieers because no-one had time to review them.

**Comment by dagwieers** [comment]
I will review them ! Can you rebase ?

**Comment by dagwieers** [comment]
PS We now have check-mode and diff support as well. I guess we could test check-mode support in the integration tests now too. (Improving the integration tests was my next endeavour after all the cleanup stuff was merged)

**Comment by jhawkesworth** [comment]
Check mode and diff mode tests would be awesome.
I tried to implement diff mode for win_file here: https://github.com/ansible/ansible-modules-core/pull/4175 but iirc nitzmahone wasn't happy with the implementation so it never got merged.

I believe you can set check mode programatically in playbooks, but not diff mode (yet), so I'm not sure if there are any diff mode tests.  Should be doable I think but might need to be in a separate test target so ansible-playbook can be run with --diff - although .. probably hard to test things if playbook is in diff mode (speculating - I have not tried).

tried to rebase but got merge conflicts - I'll have to try again later.

**Comment by dagwieers** [comment]
@jhawkesworth Regarding ansible/ansible-modules-core/4175, I don't like it either ;-) I don't see how it would work, because you need to read out the `ansible_diff` parameter. Also, the output of diff-support should be on-par with the python output, and I can't see what would be produced by your code easily.

But we'll get there, I am adding more stuff to your etherpad.

**Comment by jhawkesworth** [comment]
Thanks.  iirc I just tried to port the equivalent python code from file module.  It produced some output but maybe things have moved on, and likely I missed how the rest of ansible was supposed to work.

**Comment by jhawkesworth** [comment]
ok I need to fix the following, which I will do next time I am at my laptop.

2017-02-17 08:23:22 test/integration/targets/win_regedit/tasks/main.yml
2017-02-17 08:23:22   397:19    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   397:24    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   397:29    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   397:34    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   397:39    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   397:44    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   397:49    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   409:19    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   409:24    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   409:29    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   409:34    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   409:39    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   409:44    error    too few spaces after comma  (commas)
2017-02-17 08:23:22   409:49    error    too few spaces after comma  (commas)

**Comment by jhawkesworth** [comment]
@dagwieers - as requested (assuming CI run completes successfully this time)

ready_for_review

**Comment by dagwieers** [comment]
@jhawkesworth Not a lot to review, I think CI did most of the work already ;-)

shipit (although I have no shipit powers for Windows)

**Comment by jhawkesworth** [comment]
Can anyone else just check this small change to the integration tests for win_regedit over?
@jborean93 @mattclay @gundalow

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged, thanks for adding the idempotent test

**Pull request merged**
