### PR TITLE
Ec2 snapshot tests

### PR DESCRIPTION
**Pull request by robjailall**
##### SUMMARY
Added a bunch of unit tests for existing and new functionality of the ec2_snapshot module (found here: https://github.com/ansible/ansible-modules-core/pull/1143)

I believe I can get rid of that subproject update and squash  the commit once ansible-modules-core pull is merged.

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/modules/core
test-requirements.txt
test/units/module_tests/TestEC2Snapshot.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by abadger** [comment]
@jimi-c @bennojoy @bcoca What do we think of these tests? They use the moto library to allow us to unittest (rather than integration test) the ec2_snapshot module.  If this is a good strategy I can rebase it and it could serve as an example for unittesting other boto-based modules in the future.

**Comment by abadger** [comment]
Talked with @jimi-c over the weekend and he likes this approach.  May not get merged in time for v2 as there's a lot of work to be done in v2 and we're approaching our milestones but this is a strategy that he likes.

**Comment by robjailall** [comment]
I don't know if you already discussed this, but it's a little weird to have the test for a module be separate from the code for a module.

**Comment by jimi-c** [comment]
@robjailall we have discussed that, and plan on moving things around/reorganizing things a bit so that the code to test modules lives in the respective repo rather than simply in core. That will most likely be a post-2.0 thing though.

**Comment by sivel** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run `git rebase` against this branch to bring it up to date
- Make sure to reset your git submodules using `git submodule update`
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
