### PR TITLE
Remove closed statement with no effect

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/monitoring/logicmonitor.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by bcoca** [comment]
it was written that way to keep 2.4 compatibility, though it really should have only needed 1 and use finally instead of except.

**Comment by Akasurde** [comment]
@bcoca OK I will close this then.

**Comment by bcoca** [comment]
i did not mean for you to close it, just explaining the origin

as of Ansible 2.4 we don't maintain python 2.4/2.5 compatibility anymore.

**Comment by woz5999** [comment]
shipit

**Comment by Akasurde** [comment]
@resmo @woz5999 Thanks for review.

**Pull request merged**
