### PR TITLE
Fix checksum check and redownload logic

### LINKED ISSUE #64016: ansible 2.8.6 get_url repeatedly downloads file with force==no
##### SUMMARY
Unlike in version 2.8.5, get_url module repeatedly downloads an URL even if destination exists with Ansible 2.8.6

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.8.6
  config file = None
  configured module search path = [u'/Users/XXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXX/.virtualenvs/ansible2.8/lib/python2.7/site-packages/ansible
  executable location = /Users/XXX/.virtualenvs/ansible2.8/bin/ansible
  python version = 2.7.16 (default, Sep  2 2019, 11:59:44) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
MacOS

##### STEPS TO REPRODUCE

```yaml
$ touch foofile
$ cat > test_playbook.yaml
---
- hosts: localhost
  connection: local

  tasks:
    - name:           Fetch file
      get_url:
        url:          http://google.com
        dest:         ./foofile
        force:        no

$ ansible-playbook -i 'localhost,' test_playbook.yaml
```

##### EXPECTED RESULTS
No changes, since "foofile" already exists. With the same playbook, a run with Ansible 2.8.5 results in:
```
PLAY RECAP ********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS
File gets overwritten/downloaded every time
```
$ ansible-playbook -i 'localhost,' test_playbook.yaml
PLAY [localhost] **************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************
ok: [localhost]

TASK [Fetch file] *************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### PR DESCRIPTION
**Pull request by whs-dot-hk**
##### SUMMARY

|checksum_mismatch|force|Explain|redownload|
|---|---|---|---|
|F|T|Checksum match but force redownload|yes|
|F|F|Checksum match no redownload|no|
|T|T|Checksum not match redownload|yes|
|T|F|Checksum not match redownload|yes|

Fixes #64016

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

get_url
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@whs-dot-hk Thanks for your contribution. Could you please check this PR https://github.com/ansible/ansible/pull/64626 which seems to solve the issue ? Thanks.

needs_info

**Comment by whs-dot-hk** [comment]
@Akasurde, I have observed that no download happen when checksum match and `force` is set to `no`

While the other cases re-download always happens

PR #64626 didn't consider the case when `force` is `yes` and checksum match, which will skip re-download

**Comment by Akasurde** [comment]
@whs-dot-hk Thanks for the feedback, could you please provide same review on PR #64626 as well.

**Comment by whs-dot-hk** [comment]
@Akasurde Hi, review added to PR #64626

**Comment by Derioss** [comment]
I make some test with python:3.7.6-slim-buster and debian:testing-slim
With ansible 2.8.4 and 2.8.5 it's ok on both, on 2.8.6+ - latest stable the issue appear

The issue seems to be appear after this change : 
```python
        # Not forcing redownload, unless checksum does not match
        if not force and checksum and not checksum_mismatch:
            # Not forcing redownload, unless checksum does not match
            # allow file attribute changes
```
This code  works

```python
        # Not forcing redownload, unless checksum does not match
        if not force and not checksum_mismatch:
            # Not forcing redownload, unless checksum does not match
            # allow file attribute changes
```

**Comment by bmillemathias** [comment]
Hi @whs-dot-hk 

Could you rebase your patch ?

**Comment by whs-dot-hk** [comment]
Looks like it have been fixed

**Comment by bmillemathias-1a** [comment]
> 
> 
> Looks like it have been fixed

Ah, Thanks anyway.

**Pull request closed without merging**
