### PR TITLE
apt: suppress automatic daemon startups

### PR DESCRIPTION
**Pull request by multi-io**
##### SUMMARY
This PR adds a new parameter `suppress_daemon_actions` (bool, default false) to the apt module. When the parameter is enabled, daemon startups (or, more generally, any service actions like start, stop, restart) will be suppressed during the module's operation. This is useful when you're installing a package like apache2 or ntp and want to explicitly start the corresponding daemon in a later task, rather than having apt (or rather, one of the package maintainer scripts) start it automatically during package installation.

The flag works by temporarily installing a policy script (`/usr/sbin/policy-rc.d`, see https://people.debian.org/~hmh/invokerc.d-policyrc.d-specification.txt) suppressing daemon actions for the runtime of the module, and removing it again (or replacing it with the previously existing policy file, if any) at the end.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
apt

##### ANSIBLE VERSION
```
ansible 2.4.0 (apt-suppress-daemons 64367c3d2d) last updated 2017/05/23 02:27:50 (GMT +200)
  config file = /Users/oklischat/src/ansible/ansible.cfg
  configured module search path = [u'/Users/oklischat/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/oklischat/src/ansible/lib/ansible
  executable location = /Users/oklischat/src/ansible/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```
(upstream base commit is e9e661ebbbf59c1ab397ab386517242a37e9f857)

##### ADDITIONAL INFORMATION

Sample session:

Install ntp, first without `suppress_daemon_actions`:

```
root@5c7d0b46c97f:~# ansible localhost -m apt -a 'name=ntp state=present'
localhost | SUCCESS => {
...
}
# check that the package is installed and the daemon is running
root@5c7d0b46c97f:~# dpkg -l ntp; ps ax | grep ntp | grep -v grep
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                          Version                             Architecture                        Description
+++-=============================================================-===================================-===================================-================================================================================================================================
ii  ntp                                                           1:4.2.8p4+dfsg-3ubuntu5.4           amd64                               Network Time Protocol daemon and utility programs
 6420 ?        Ss     0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 107:109
root@5c7d0b46c97f:~#
```

Test again, with `suppress_daemon_actions` set:

```
# purge the package first
root@5c7d0b46c97f:~# apt-get purge ntp
....
root@5c7d0b46c97f:~#
root@5c7d0b46c97f:~# dpkg -l ntp; ps ax | grep ntp | grep -v grep
dpkg-query: no packages found matching ntp
root@5c7d0b46c97f:~#

# install again, with suppress_daemon_actions
root@5c7d0b46c97f:~# ansible localhost -m apt -a 'name=ntp state=present suppress_daemon_actions=yes'
localhost | SUCCESS => {
.....
        "invoke-rc.d: policy-rc.d denied execution of start.",
.....     
}

# package installed, daemon NOT running
root@5c7d0b46c97f:~# dpkg -l ntp; ps ax | grep ntp | grep -v grep
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                          Version                             Architecture                        Description
+++-=============================================================-===================================-===================================-================================================================================================================================
ii  ntp                                                           1:4.2.8p4+dfsg-3ubuntu5.4           amd64                               Network Time Protocol daemon and utility programs
root@5c7d0b46c97f:~#
```

### CODE REVIEW

**Comment by bcoca** [comment]
does the 'env var trick' not work anymore?

**Comment by multi-io** [comment]
You mean this? https://askubuntu.com/a/77530 -- It probably does. One can also just create the policy-rd.d file at the beginning of the playbook. This PR provides just a small convenience, I'm not overly passionate about it.

**Comment by bcoca** [comment]
yep the  hack with RUNLEVEL=1, might be worth documenting as alternative to the option. I really dislike creating/deleting policy files on the fly (not that .deb gives you much choice here).

**Comment by mkrizek** [comment]
@multi-io @bcoca We have the following documented in the apt module docs [1]:
```
- name: Install apache service but avoid starting it immediately
  apt: name=apache2 state=present
  environment:
    RUNLEVLEL: 1
```

which does the same thing without adding code to the module. I'd be leaning towards closing this PR in favor of the above solution. Thoughts?

[1] http://docs.ansible.com/ansible/latest/modules/apt_module.html#examples

**Comment by multi-io** [comment]
OK with me.

**Comment by bcoca** [comment]
closing as per above

**Comment by dentarg** [comment]
> does the 'env var trick' not work anymore?

@bcoca that seems to be the case

https://www.alextomkins.com/2018/03/runlevel-apt-get-install-package-alternative/ says:

>An old documented way of preventing services from starting immediately after installation in Debian/Ubuntu is using the RUNLEVEL environment variable to trick the runlevel helper into returning a response that the system isn't fully running, such as:
>
>     RUNLEVEL=1 apt-get install nginx
>
> Sadly this doesn't work in newer versions of Debian/Ubuntu, the official way is to use the policy helper script ...

and here I am in Ubuntu 14.04 failing to install gearman without it being started:

```
vagrant@vagrant-queueserver:~$ sudo RUNLEVEL=1 apt-get install --no-install-recommends -y gearman-job-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
Recommended packages:
  memcached
The following NEW packages will be installed:
  gearman-job-server
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/110 kB of archives.
After this operation, 419 kB of additional disk space will be used.
Selecting previously unselected package gearman-job-server.
(Reading database ... 63184 files and directories currently installed.)
Preparing to unpack .../gearman-job-server_1.0.6-3_amd64.deb ...
Unpacking gearman-job-server (1.0.6-3) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up gearman-job-server (1.0.6-3) ...
gearman-job-server start/running, process 4337
Processing triggers for ureadahead (0.100.0-16) ...
vagrant@vagrant-queueserver:~$ ps aux | grep gearman
gearman   4337  0.0  0.9 481528  4724 ?        Ssl  09:20   0:00 /usr/sbin/gearmand --log-file=/var/log/gearman-job-server/gearman.log
```

**Pull request closed without merging**
