### PR TITLE
apt_repository: fix update cache after state=changed. Closes GH-4136

### PR DESCRIPTION
**Pull request by resmo**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Seems valid to me, though if adding multiples it would run a lot of cache updates.

Can we update the cache for just that repo?

**Comment by resmo** [comment]
I don't think this is possible, there is just one big index. 

we could add an option for updating the index similar as in apt module (default would be yes): 

```
 apt_repository: ... update_cache=no
```

**Comment by jimi-c** [comment]
I think adding the option would be good, also this is going to introduce a dependency on python-apt so the module documentation will need an update as well.

**Comment by jimi-c** [comment]
Whoops, nevermind, python-apt is already listed as a dep for that module.

**Comment by resmo** [comment]
@jimi-c implemented.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
