### PR TITLE
Fix mail module for python 3.7.0

### PR DESCRIPTION
**Pull request by guoqiao**
In python 3.7.0, changes in `ssl.py` breaks `smtplib.SMTP_SSL`, which
then breaks `mail` module in ansible.

Run this line in python shell:

    import smtplib;smtplib.SMTP_SSL().connect(host='smtp.gmail.com', port=465)

Before python 3.7.0, we will get:

    (220, b'smtp.gmail.com ESMTP j13-v6sm3086685pgq.56 - gsmtp')

In python 3.7.0, we get such error at `lib/python3.7/ssl.py` line 843, method `_create`:

    ValueError: server_hostname cannot be an empty string or start with a leading dot.

The ssl module is using host info on SMTP_SSL instance, which is not set.
The fix/workaround is simple, just pass host info to it:

    import smtplib;smtplib.SMTP_SSL(host='smtp.gmail.com').connect(host='smtp.gmail.com', port=465)

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

mail

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel fff5fb2077) last updated 2018/08/23 10:50:40 (GMT +1300)
  config file = /home/joeg/vagrant/ansible.cfg
  configured module search path = ['/home/joeg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/joeg/.pyenv/versions/3.7.0/envs/ansible/src/ansible/lib/ansible
  executable location = /home/joeg/.pyenv/versions/ansible/bin/ansible
  python version = 3.7.0 (default, Jul 23 2018, 11:49:27) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jborean93** [comment]
@guoqiao are you able to add a changelog fragment at https://github.com/ansible/ansible/tree/devel/changelogs/fragments with the details on this fix?

**Comment by guoqiao** [comment]
@jborean93  Sure,  pushed.

**Comment by jborean93** [comment]
Thanks @guoqiao

**Comment by jborean93** [comment]
Please have a look at https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process for details on how to backport this to the stable-2.6 branch so it is included in the 2.6.x releases.

**Pull request merged**
