### PR TITLE
Backport of 64585: Don't return module error when mysql_connect fails

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Backport of #64585 : Don't return module error when mysql_connect fails

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
```lib/ansible/module_utils/mysql.py```
```lib/ansible/modules/database/mysql/mysql_info.py```

### CODE REVIEW

**Comment by juergenhoetzel** [comment]
```json
{
"changed": false, 
"msg": "unable to find /root/.my.cnf. Exception message: (1045, u\"Access denied for user 'root'@'localhost' (using password: NO)\")"
}
```
about the failed test: Maybe the root password must be resetted? because other tests depend on it? I wonder why this did not occur on the `devel` branch.

**Comment by ffdybuster** [comment]
The test system in `devel` was changed so that the DB is uninstalled after every test and reinstalled for the next. If that change wasn't backported, this behavior is to be expected. I guess long-term it would be better to port that change back to stable-2.9 as well, but for now removing the test from the backport is also OK (but run it manually before to make sure it works).

**Comment by Andersson007** [comment]
i removed the tests and ran ansible-test locally from branch 2.9 using centos6, passed without errors.
just pushed to here. will see results..

**Comment by Andersson007** [comment]
mysql_info was also checked locally, all was ok

**Comment by Andersson007** [comment]
passed! thanks all!

**Pull request merged**
