### PR TITLE
Auto install roles

### PR DESCRIPTION
**Pull request by willthames**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 9e6988c7b5) last updated 2016/04/16 23:37:26 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 5409ed1b28) last updated 2016/04/16 23:37:29 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 3afe117730) last updated 2016/04/16 23:37:29 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides

```
##### SUMMARY

Implementation of auto roles install ansible/proposals#7

There are some enhancements that I'd like to make
- It would be nice if `roles_path` and `roles_file` could be obtained from ansible.cfg and also be relative to e.g `playbook_dir`. I'm not sure if ansible.cfg can manage that
##### NOTES:
- Incorporates #15414 and #12904 because they're both useful to have (#12904 is the basis of this work anyway - I could split out #15414 if need be)
- Fixes to failing tests are coming along nicely. The test suite has found some odd edge cases, which is great.

### CODE REVIEW

**Comment by willthames** [comment]
@chouseknecht @bcoca this is the draft implementation of my auto install roles proposal

I know there is more to your proposals, but I think that the implementation of your proposals wouldn't be much different on top of this implementation (other than that this implementation should simplify how modules interact)

**Comment by bcoca** [comment]
A few of things just from the head of this:
- I don't want to use another requirements entry/file but have this part of normal playbook execution, there should be no need to specify roles N times. 
- This feature should be configurable and needs the ability of specifying whitelisted sources.
- if we need to install roles manually we have ansible-galaxy for that, i don't think we should overload playbook with the same options, it is already a stretch to have the 'autoinstall' in playbook, lets not push the manual also.

I'm more partial to start with galaxy and handover to playbook (like pull does) than this intermingling of both.

 Also, a lot of this code seems to swap places between galaxy and playbook classes and not sure why this is needed.

**Comment by willthames** [comment]
To address your points in turn:
- No new requirements file exists. This just uses the same requirements file. Specifying the sources of the roles should be independent of specifying which roles are used (similar to how you use a pom.xml or a requirements.txt to specify versions of libraries rather than importing a versioned module in source code). I have zero intention of changing this bit.
- I can add a couple of configuration pieces for whitelist and auto_install 
- I can eliminate the command line options, and it will simplify the change, definitely.

Some of the code swaps make sense. I can probably move some back, I was struggling to avoid circular dependencies, but there are other ways to do that.

**Comment by willthames** [comment]
@bcoca, what do you think should be the behaviour of the whitelist by default, when auto role install is not enabled? 

Presumably default whitelist should not prevent someone already using galaxy to install roles from then installing roles in the future. But neither do I think that the whitelist should only be used when auto installing roles. Does that mean the default whitelist should be everything?

**Comment by bcoca** [comment]
No, i proposed it ONLY for the autoinstall, if we want to use it for all galaxy installs i would say we need a 2nd setting to toggle that behavior (galaxy_use_whitelist=False|true).

The default whitelist is always empty.

**Comment by willthames** [comment]
@bcoca, the reason for the code moves is that playbooks using ansible.cli.galaxy to install roles seems like a missing abstraction (compared to ansible.cli.galaxy and ansible.cli.playbook using some common code). A lot of role installation stuff happens in ansible.playbook.role.requirement so it kind of made sense to move the shared code (reading roles file, installing roles from that file) into the same place. That refactor doesn't have to happen, but makes the code a little easier to understand, but if there's a better way of doing the abstractions, I'd be happy to hear it.

What I don't want to do is shell out to ansible-galaxy if I can avoid it, as that seems like a nasty hack.

**Comment by willthames** [comment]
Ok, vastly simplified this (although some of the refactor is still present because it's role installation shouldn't really be a concern of the CLI but of the role code (whether that should be somewhere in ansible.galaxy.role or ansible.playbook.role.requirement is debatable, but the latter is currently where some role installation occurs))

Added `auto_install_roles` and `auto_install_roles_whitelist` plus a test case (the docs and ansible.cfg under test/integration shows how this works)

Command line options removed so that roles will be installed by ansible-playbook only if roles_file is present in the playbook and auto_install_roles is on in configuration.

**Comment by bcoca** [comment]
Since we are still discussing the proposal, I"m going to wait on that part is final.

**Pull request closed without merging**
