### PR TITLE
Lookup docs

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

updating lookups to have docs for ansible-doc

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

lookup
##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Comment by alikins** [comment]
edit: IGNORE for the moment. May be from wrong branch.

Generated docs hit a couple of errors:

```
/home/adrian/src/ansible/docs/docsite/rst/plugins/lookup/random_choice.rst:5: WARNING: duplicate label random_choice, other instance in /home/adrian/src/ansible/docs/docsite/rst/playbooks_loops.rst
/home/adrian/src/ansible/docs/docsite/rst/plugins/lookup/cartesian.rst:70: WARNING: unknown document: common_return_values
/home/adrian/src/ansible/docs/docsite/rst/plugins/lookup/etcd.rst:87: WARNING: unknown document: common_return_values
```

The duplicate lable issue is legit but playbooks_loops should probably rename it's target/label to fix. So no change needed to plugin docs.

The 'common_return_values' errors are because the gen docs have:

``` rst
    :doc:`common_return_values`
```

but since the rst is now in rst/plugins/lookup/ the doc ref is wrong. It would need to be:

``` rst
    :doc:`../../common_return_values`
```

Not sure if it makes sense to have the relative doc reference in the plugin docs. I'll see if a :ref: works.

Missing docs from the remaining lookup plugins:

```
** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/dnstxt.py, dnstxt ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/nested.py, nested ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/filetree.py, filetree ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/csvfile.py, csvfile ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/password.py, password ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/list.py, list ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/inventory_hostnames.py, inventory_hostnames ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/lastpass.py, lastpass ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/dig.py, dig ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/sequence.py, sequence ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/first_found.py, first_found ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/hiera.py, hiera ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/indexed_items.py, indexed_items ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/items.py, items ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/redis_kv.py, redis_kv ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/consul_kv.py, consul_kv ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/flattened.py, flattened ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/fileglob.py, fileglob ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/passwordstore.py, passwordstore ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/dict.py, dict ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/subelements.py, subelements ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/shelvefile.py, shelvefile ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/cyberarkpassword.py, cyberarkpassword ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/random_choice.py, random_choice ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/credstash.py, credstash ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/hashi_vault.py, hashi_vault ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/lines.py, lines ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/file.py, file ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/env.py, env ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/url.py, url ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/keyring.py, keyring ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/together.py, together ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/pipe.py, pipe ***
*** ERROR: MODULE MISSING DOCUMENTATION: ../../lib/ansible/plugins/lookup/chef_databag.py, chef_databag ***

```

**Comment by abadger** [comment]
Yeah, should change the anchors in playbook_loops.  OTOH, fixing those to namespace labels is something we need an overall docs decision on eventually (ping: @dharmabumstead & @gundalow )

Since common_return_values is generated, I think the generator should handle making that a :doc:relative_path link rather than trying to use :ref:  (If it wasn't generated, I'd agree that it's ugly to force the plugin author to know about the file system layout).

**Comment by alikins** [comment]
notes in https://github.com/ansible/ansible/pull/30280#issuecomment-329230390  may be bogus, may have been in wrong branch.

**Comment by bcoca** [comment]
had not touched playbook_loops ....

no idea where 'common_return_values' comes from, its not in the docs im writing, also they would NOT apply to lookups, those are 'module specific'

**Comment by alikins** [comment]
common_return_values was from the template, fixed now in via a ref in https://github.com/ansible/ansible/pull/28901

random_choice is updated there as well.

**Review by dharmabumstead — APPROVED** [review]

**Review by dharmabumstead — APPROVED** [review]

**Comment by abadger** [comment]
cherrypicked for 2.4.1

**Pull request merged**
