### PR TITLE
Add host affinity to the documentation template

### PR DESCRIPTION
**Pull request by Fale**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
Many

##### ANSIBLE VERSION

```
2.2
```

##### SUMMARY
Add a field to document host affinity and start to use it. ATM we have many modules that declare this kind of stuff in the examples, but imho is better to have a section about it (people might not read the examples)

### CODE REVIEW

**Comment by Fale** [comment]
Any comments on this?

**Comment by bcoca** [comment]
-1 from me, I don't think this is best way to reflect that modules don't need to execute on target machine but on behalf of it.

Also localhost is not always the 'right delegated host' as many users have different network security and might need to execute these on different 'jump hosts' which actually have access to the service and not on the Ansible controller.

**Comment by Fale** [comment]
@bcoca I agree that there are cases where this does not apply strictly.
There are many places in the doc where there is written that that command must be run in localhost (mainly in examples).
I think that we should either:
* Remove all those comments and leave it to the user to figure it out
* Put it in a more prominent location

I think both options are fine, but considering the points raised in your comment, I would now go more on the first one

**Comment by bcoca** [comment]
I've corrected a few of those, but have not made it a mission to rewrite them all. I would make a note in each module with a  rephrase from 'running on localhost' to 'this is not meant to run directly on the target, you normally want to delegate it to 'localhost' or a specific host with access to the API/resource'

**Comment by Fale** [comment]
Do you rememeber any module where you fixed those, so I can put a similar note on the other modules as well?

**Comment by gundalow** [comment]
@Fale You should be able to find which modules it was by looking at the git history for Brian in the modules directory.

I'm going to close this issue as we don't want to do it this way.

A guide that states "device and API centric modules normally execute from localhost or a 'specific host with access' " is a better approach.

**Pull request closed without merging**
