### PR TITLE
Fix nested parameters in module docs

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Fix nested parameters in module docs

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME
module docs

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Review by dharmabumstead — APPROVED** [review]

**Comment by gundalow** [comment]
Need this as without it the network docs are http://docs.ansible.com/ansible/devel/modules/nxos_config_module.html are broken, no suboption table for `provider`

**Comment by dagwieers** [comment]
@gundalow I added `&nbsp;` because otherwise the same reduction in HTML may be attempted with the same result.

**Comment by nitzmahone** [comment]
This doesn't cherry-pick cleanly to stable-2.5- can someone please resolve conflicts and do a PR?

**Comment by nitzmahone** [comment]
NM, I figured it out. Cherry-picked to stable-2.5

**Pull request merged**
