### PR TITLE
fix an idempotence bug in apt-repository where 'ppa' is used in a plain http://ppa. ....

### LINKED ISSUE #2831: apt_repository doesn't ever skip even when repo already there
given task: 

```
    - name: ensure nginx source in sources.list
      apt_repository: repo='deb http://ppa.launchpad.net/nginx/stable/ubuntu/ precise main' state=present
```

`changed` is always true, even when running multiple times and the repo is already there.

```
$ ansible-playbook test.yml -i dev -vvv
<snip>
TASK: [ensure nginx source in sources.list] *********************************** 
<192.168.0.32> ESTABLISH CONNECTION FOR USER: foo on PORT 22 TO 192.168.0.32
<192.168.0.32> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1367527951.12-31597969997604 && chmod a+rx $HOME/.ansible/tmp/ansible-1367527951.12-31597969997604 && echo $HOME/.ansible/tmp/ansible-1367527951.12-31597969997604'
<192.168.0.32> REMOTE_MODULE apt_repository repo='deb http://ppa.launchpad.net/nginx/stable/ubuntu/ precise main' state=present
<192.168.0.32> PUT /tmp/tmpLWW20u TO /home/foo/.ansible/tmp/ansible-1367527951.12-31597969997604/apt_repository
<192.168.0.32> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=dvubfgxdhwlxhtvknntcnuyprhfgoana] password: " -u root /bin/sh -c '"'"'/usr/bin/python /home/foo/.ansible/tmp/ansible-1367527951.12-31597969997604/apt_repository; rm -rf /home/foo/.ansible/tmp/ansible-1367527951.12-31597969997604/ >/dev/null 2>&1'"'"''
changed: [192.168.0.32] => {"changed": true, "repo": "deb http://ppa.launchpad.net/nginx/stable/ubuntu/ precise main", "state": "present"}
</snip>
```

Version info:

```
$ ansible-playbook --version
ansible-playbook 1.2
```

### PR DESCRIPTION
**Pull request by srgvg**
...... url

fixes #2831

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not sure this is an idempotence bug or just a flat out logic bug where the repo url gets split wrong, but looks solid to me.

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by srgvg** [comment]
it was indeed more than just an idempotence bug, but what's in a name :)

**Comment by mpdehaan** [comment]
Idempotence, you keep saying that word!  :)

</Princess Bride>

**Pull request merged**
