### PR TITLE
When var name is the same as var content, try to template it before reporting that var is not defined.

### PR DESCRIPTION
**Pull request by Yannig**
Add asserts in test_var_blending to check this special corner case.

### CODE REVIEW

**Comment by Yannig** [comment]
The tests are broken due to a bug in make tests-py3 (https://github.com/ansible/ansible/issues/13638)

**Comment by Yannig** [comment]
@jimi-c any comment?

**Comment by jimi-c** [comment]
@Yannig I've seen this, just lower priority at the moment. It looks fine, the only thing I'd like to see cleaned up is that it's 4 commits. If you want to squash it down, that'd be helpful, otherwise I'll just do it when we merge it.

**Comment by Yannig** [comment]
@jimi-c squash down into a single commit against last devel.

**Comment by abadger** [comment]
Merged to devel

**Comment by abadger** [comment]
And cherry-picked to stable-2.1 as well.  Thanks @Yannig !

**Comment by Yannig** [comment]
@abadger thanks :)

**Pull request merged**
