### PR TITLE
Add consul_template module

### PR DESCRIPTION
**Pull request by mmorev**
##### SUMMARY
This implements a plugin to enable rendering of templates using values from HashiCorp Consul and Vault key-value stores.
It uses consul-template binary, that should exist in $PATH on Ansible controller.
consul-template documentation: https://github.com/hashicorp/consul-template
vault documentation: https://www.vaultproject.io/docs/what-is-vault/index.html

Module renders template locally on Controller and then sends result file using Ansible core Copy module, using any defined options not used by consul_template. So it can use almost all of Copy options, backup and validation, as well as --check and --diff playbook arguments. All of this was tested.

Also consul-template allow use of environment variables in templates. So i have implemented use of task environment option, despite of its main purpose to define environment on remote machine.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
consul_template

##### ADDITIONAL INFORMATION
You can simply try to use this module. Download latest version of Vault and Consul-template binaries from HashiCorp official site (https://releases.hashicorp.com/) and place them in any location defined in your $PATH. Then follow instructions below.

Run Vault "dev mode" server with no need to configure it, then set required environment variable containing its address:
```
$ vault server --dev --log-level=warn &
$ export VAULT_ADDR=http://127.0.0.1:8200
```
Vault Dev Server documentation page: https://www.vaultproject.io/docs/concepts/dev-server.html

Put some test values into Vault:
```
$ vault kv put secret/testsecret secretkey=secretvalue
```

Put a template in file, for example, secret.vtmpl:
```
# secret.vtmpl:
{{ with secret "secret/testsecret" -}}
secretkey={{ index .Data.data "secretkey" }}
{{- end }}
```

Create a simple playbook which use consul_template module and example template:
```
# render.yml:
- hosts: localhost
  tasks:
  - consul_template:
      src: secret.vtmpl
      dest: /tmp/secret
```

Run play:
```
$ ansible-playbook render.yml
```

Check that ansible created a file `/tmp/secret` and it contains our secret value:
```
$ cat /tmp/secret 
secretkey=secretvalue
```

### CODE REVIEW

**Comment by mmorev** [comment]
ready_for_review

**Comment by mmorev** [comment]
-label test

**Comment by mmorev** [comment]
Failed tests are not related to code changes. Please review. Thanks
ready_for_review

**Comment by sivel** [comment]
Hi!

Thank you very much for your submission to Ansible. It sincerely means a lot to us that you've taken the time to contribute.

Per recent announcements at AnsibleFest Atlanta 2019, going forward we are no longer accepting new one off modules/plugins, or modules/plugins that create a new category.

However, we recommend looking into providing this functionality through Ansible Galaxy via Ansible Collections. You can find more information about collections at https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html.

Thank you once again for this and your interest in Ansible!

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by mmorev** [comment]
@sivel Why is it a new category? You have already a hashi_vault lookup plugin and (Jinja) template action plugin. This module is a combination of these - it parses file just like Template does and substitutes values using Vault (and also Consul kv-store if needed), like hashi_vault does. Also it is effectively integrates with and uses existing code - Copy and Fetch action plugins and their parameters, and documentation fragments too.
Please, reopen this PR if possible.

**Pull request closed without merging**
