### PR TITLE
Add support for tags in DO inventory

### LINKED ISSUE #15752: Add support for DigitalOcean tags to external inventory script
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME
digital ocean dynamic inventory script

##### ANSIBLE VERSION

n/a
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

n/a
##### SUMMARY

Support DigitalOcean's new tags feature in the inventory script with a new CLI option, auto-generated groups, and returned host-specific variables.

n.b.: tags are currently only available as a feature in DO's API, but not in the web control panel.
##### STEPS TO REPRODUCE
- Add `--tags` [CLI option](https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py#L85) to retrieve all tags.
- Add `tag_TAG` [generated group](https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py#L40).
- Add `do_tags` [variable](https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py#L50) when run against a host.
##### EXPECTED RESULTS

`./digital-ocean.py --tags --pretty` should output e.g.

```
{
  "tags": [
    "tag_1",
    "tag_2",
    "tag_3"
  ]
}
```

`do_tags` variable could be e.g. a comma-separated list of tags on that droplet.
##### ACTUAL RESULTS

n/a

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes #15752

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
contrib/inventory/digital_ocean.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
ready_for_review

**Comment by chavenor** [comment]
Is this ready to go?   Been sitting ready to go for some time.

**Comment by Akasurde** [comment]
@chavenor Yes. You can use this patch and test it. This will get merged once code review is done.

**Comment by chavenor** [comment]
Ok sounds good.

**Comment by Akasurde** [comment]
@BondAnthony Can you please review this ?

**Comment by BondAnthony** [comment]
@Akasurde while your code looks good and it makes logical sense I believe you have one minor problem. The latest version of Dopy 0.3.7a doesn't reflect the same changes that GitHub.com/wiredcraft/dopy has currently. It looks like Wiredcraft never released the last batch of code that was developed in 2016. How do you foresee users being able to install the unreleased version of Dopy?

I did test your inventory changes with the unreleased version of dopy, it does work.

**Review by BondAnthony — CHANGES_REQUESTED** [review]
Not approving only because you have a broken dependency.

**Comment by chavenor** [comment]
@BondAnthony it seems those other packages do not have any activity.  I did find one that had some recent activity.  I reached out to see if there is interest to support Ansible.

**Comment by BondAnthony** [comment]
@Akasurde would you be open to collaborating on a rewrite of the DO inventory script to remove ‘dopy’ dependency?

**Comment by Akasurde** [comment]
@BondAnthony Yes. Sure. I will open a PR for this. I found an existing bug for ansible/ansible#16827

**Comment by Akasurde** [comment]
Closing this PR in-favour of https://github.com/ansible/ansible/pull/29176

@chavenor Could you please test new PR ?

**Pull request closed without merging**
