### PR TITLE
add self-signed https endpoint for ansible-test

### PR DESCRIPTION
**Pull request by heiderich**
##### SUMMARY

This prodives a https endpoint with a self-signed CA certificate. The main motivation is to provide infrastructure for integration tests for https://github.com/ansible/ansible/pull/71979.
 
##### COMPONENT NAME

ansible-test

##### ADDITIONAL INFORMATION

For more information and an example use case see https://github.com/ansible/ansible/pull/71979.

### CODE REVIEW

**Comment by webknjaz** [comment]
Where are the TLS certs? Also, have you considered using https://trustme.rtfd.io?

**Comment by heiderich** [comment]
@webknjaz The certificates are created in https://github.com/ansible/http-test-container/, see https://github.com/ansible/http-test-container/pull/7/ and https://github.com/ansible/http-test-container/pull/9/. I did not consider using https://trustme.rtfd.io as @sivel suggested the approach taken here in https://github.com/ansible/ansible/pull/71979#issuecomment-702390025.

**Comment by heiderich** [comment]
The test https://github.com/ansible/ansible/pull/73463/checks?check_run_id=1825269854 was aborted after exceeding the 50 minute time limit.
In the test https://github.com/ansible/ansible/pull/73463/checks?check_run_id=1825017573 a request limit was exceeded (https://dev.azure.com/ansible/ansible/_build/results?buildId=5706&view=logs&j=57a03880-e1e5-5cd4-bfd6-4d4355c774ae&t=2400f0c8-b9ad-5252-96cc-0767cddb7a29&l=10075).
I do not see a relation to the changes in this PR. Maybe both are temporary problems.

May someone trigger the test pipeline again, please? @samdoran @webknjaz

**Review by jborean93 — APPROVED** [review]
Changes look good, reran the tests and they should now be green.

**Pull request merged**
