### PR TITLE
ansible-test - Update sanity test requirements

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Update pylint to 2.9.6 to get around a false positive for `undefined-variable` in a decorator.

https://github.com/PyCQA/pylint/issues/3791

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

`test/lib/ansible_test/_data/requirements/sanity.pylint.in`
`test/lib/ansible_test/_data/requirements/sanity.pylint.txt`

##### ADDITIONAL INFORMATION

<details>
  <summary>Simple reproducer</summary>
  
```python
import pytest

data = {
    "one": [{"out": "out", "expected": "expected"}],
    "two": [{"out": "out", "expected": "expected"}],
}


@pytest.mark.parametrize(
    ("key", "item", "expected"),
    ((key, case["out"], case["expected"]) for key in data for case in data[key])
)
def some_test(key, item, expected):
    assert key
    assert item
    assert expected
```
</details>

<details>
  <summary>Command output</summary>
  
```shell
> ansible-test sanity --docker default --python default example.py

Starting new "ansible-test-controller-I5CwyzNd" container.
Adding "ansible-test-controller-I5CwyzNd" to container database.
Running sanity test "action-plugin-docs"
Running sanity test "ansible-doc"
Running sanity test "changelog"
Running sanity test "compile" on Python 2.7
Running sanity test "compile" on Python 3.5
Running sanity test "compile" on Python 3.6
Running sanity test "compile" on Python 3.7
Running sanity test "compile" on Python 3.8
Running sanity test "compile" on Python 3.9
Running sanity test "compile" on Python 3.10
Running sanity test "compile" on Python 3.11
Running sanity test "empty-init"
Running sanity test "future-import-boilerplate"
Running sanity test "ignores"
Running sanity test "import" on Python 2.7
Running sanity test "import" on Python 3.5
Running sanity test "import" on Python 3.6
Running sanity test "import" on Python 3.7
Running sanity test "import" on Python 3.8
Running sanity test "import" on Python 3.9
Running sanity test "import" on Python 3.10
Running sanity test "import" on Python 3.11
Running sanity test "line-endings"
Running sanity test "metaclass-boilerplate"
Running sanity test "no-assert"
Running sanity test "no-basestring"
Running sanity test "no-dict-iteritems"
Running sanity test "no-dict-iterkeys"
Running sanity test "no-dict-itervalues"
Running sanity test "no-get-exception"
Running sanity test "no-illegal-filenames"
Running sanity test "no-main-display"
Running sanity test "no-smart-quotes"
Running sanity test "no-unicode-literals"
Running sanity test "pep8"
Running sanity test "pslint"
Running sanity test "pylint"
ERROR: Found 1 pylint issue(s) which need to be resolved:
ERROR: example.py:11:75: undefined-variable: Undefined variable 'key'
See documentation for help: https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/pylint.html
Running sanity test "replace-urlopen"
Running sanity test "runtime-metadata"
Running sanity test "shebang"
Running sanity test "shellcheck"
Running sanity test "symlinks"
Running sanity test "use-argspec-type-path"
Running sanity test "use-compat-six"
Running sanity test "validate-modules"
Running sanity test "yamllint"
FATAL: The 1 sanity test(s) listed below (out of 46) failed. See error output above for details.
pylint
FATAL: Command "docker exec ansible-test-controller-I5CwyzNd /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/community/general LC_ALL=en_US.UTF-8 /usr/bin/python3.10 /root/ansible/bin/ansible-test sanity example.py --containers '{}' --metadata tests/output/.tmp/metadata-79iptrbd.json --truncate 173 --color yes --host-path tests/output/.tmp/host-63lcc6wn" returned exit status 1.
```
</details>

I've found I can work around this by using different variable names in the comprehension than the function signature.

### CODE REVIEW

**Comment by samdoran** [comment]
I figured this would break some things, but I was hoping it was a small enough change it wouldn't.

**Comment by samdoran** [comment]
Ah, that's another bug in `pylint` that was fixed already. I'll bump the version gently.

**Comment by samdoran** [comment]
Turning into a bit of a rabbit hole...

**Comment by samdoran** [comment]
I disable a few checkers that are [new for pylint 2.10](https://pylint.pycqa.org/en/v2.10.2/whatsnew/2.10.html#new-checkers). I'm not sure if those should be disabled in the `collection.cfg` as well.

**Comment by mattclay** [comment]
@samdoran I have a local branch where I've started work on upgrading `pylint` to support Python 3.11. It includes most of the changes you have here, and more, since it's moving to an even newer version of `pylint`. There's probably not much point in doing this update yet since we'll need to follow it up with another.

**Comment by samdoran** [comment]
@mattclay Sounds good! I'll close this.

**Pull request closed without merging**
