### PR TITLE
Fix #5679 again after recent changes in core

### LINKED ISSUE #5679: lineinfile ignores newline “\n” in the line argument
I need to insert a multiline string with the _lineinfile_ module. According to [this article](http://fabian-affolter.ch/blog/the-lineinfile-module-of-ansible/), the special char `\n` should work, but in the current version it doesn’t.

```
lineinfile:
    dest=/tmp/file
    regexp='^MY_CONF='
    line='#some comment\nMY_CONF=value'
```

Result:

```
#some comment\nMY_CONF=value
```

Instead of:

```
#some comment
MY_CONF=value
```

Neither an actual new line doesn’t work:

```
lineinfile:
    dest=/tmp/file
    regexp='^MY_CONF='
    line='#some comment
          MY_CONF=value'
```

Result:

```
#some comment MY_CONF=value
```

### PR DESCRIPTION
**Pull request by jirutka**
My previous fix for #5679 stop working after some recent changes in Ansible and the test case I’ve wrote wasn’t ported to the new test suite. There’s a fix that works on the current version and also a new test.

### CODE REVIEW

**Comment by spasche** [comment]
I gave it a try and found out that it is not idempotent when you try to add a line with a new line (thus two lines). If the action is run more than once, the two lines are appended at the end even if they are already there.

**Comment by jirutka** [comment]
Yeah, that’s true. This module is designed to work with just single lines and it’ll not be trivial and clean to make this work correctly with multiple lines IMHO.

**Comment by spasche** [comment]
Right, I understand. Maybe we need a "linesinfile" module ;-)

**Comment by jirutka** [comment]
I’m actually working on a module specifically for managing “key=value” configuration files (shell-like, Java properties, ini, …) that will handle most of the problems I have with lineinfile. :)

**Comment by spasche** [comment]
Great, looking forward to it :)

While a key value manipulation module would be nice to have, a use case I encountered several times which might not be covered using a key value mechanism is simply to add block of lines after a specific position in a file (section in a samba smb.conf file for instance). It would be nice to have a way of doing that. But sorry, I digress ;-)

**Comment by mpdehaan** [comment]
FYI there is the ini_file module.  I'd probably welcome "API" compatible upgrades versus bifurcating it if possible.

Always better to just use template when you can!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
