### PR TITLE
Updating License Information

### PR DESCRIPTION
**Pull request by amuraleedhar**
SUMMARY

Updating License after review from Lenovo legal team.

ISSUE TYPE

Documentation Pull Request

COMPONENT NAME

lib/ansible/plugins/terminal/enos.py

ANSIBLE VERSION

ansible 2.5.0
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

ADDITIONAL INFORMATION

This is an effort to create config modules for enos based switches from Lenovo.

### CODE REVIEW

**Comment by gundalow** [comment]
I wonder if a single PR would be better for this

**Comment by amuraleedhar** [comment]
Hi John,

I tried a single PR and it failed on some errors like
Some issue in formatting or what, I got no clues.
Then I used a divide and rule strategy, which worked.
So pardon me for this time. I know the guidelines in this regard.

-Anil

The test ansible-test sanity --test ansible-doc --python 2.6 [explain<https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/ansible-doc.html>] failed with 3 errors:

lib/ansible/modules/network/enos/enos_command.py:0:0: has a documentation error formatting or is missing documentation.

lib/ansible/modules/network/enos/enos_config.py:0:0: has a documentation error formatting or is missing documentation.

lib/ansible/modules/network/enos/enos_facts.py:0:0: has a documentation error formatting or is missing documentation.

The test ansible-test sanity --test ansible-doc --python 2.7 [explain<https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/ansible-doc.html>] failed with 3 errors:

lib/ansible/modules/network/enos/enos_command.py:0:0: has a documentation error formatting or is missing documentation.

lib/ansible/modules/network/enos/enos_config.py:0:0: has a documentation error formatting or is missing documentation.

lib/ansible/modules/network/enos/enos_facts.py:0:0: has a documentation error formatting or is missing documentation.

The test ansible-test sanity --test pep8 [explain<https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/pep8.html>] failed with 1 error:

lib/ansible/utils/module_docs_fragments/enos.py:14:1: E302 expected 2 blank lines, found 1

**Comment by gundalow** [comment]
OK

**Comment by gundalow** [comment]
Closing as this has been replaced by https://github.com/ansible/ansible/pull/36840

**Pull request closed without merging**
