### PR TITLE
Fixed `'HashiVault' object has no attribute 'verify'"}`

### PR DESCRIPTION
**Pull request by kimmelserj**
##### SUMMARY

Moved `verify` attribute initialization. It fixed exception `'HashiVault' object has no attribute 'verify'"}` at 134 line: `self.client = hvac.Client(url=self.url, verify=self.verify)`

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
plugin

##### ANSIBLE VERSION
```
ansible 2.5.0b2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
```

##### ADDITIONAL INFORMATION
```
---
- hosts: localhost
  tasks:
  - debug: msg="{{ lookup('hashi_vault', 'secret=secret/my--secret:value auth_method=approle') }}"
```

```
ansible-playbook site.yml
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *****************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Authentication method 'approle' not supported"}
	to retry, use: --limit @/site.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

### CODE REVIEW

**Review by gofman8 — APPROVED** [review]

**Comment by maxamillion** [comment]
@kimmelserj your example output shows an unhandled exception, is that supposed to be the fixed version of the module?

**Comment by kimmelserj** [comment]
@maxamillion Yes, it fixes the cause of the exception.

**Comment by kimmelserj** [comment]
@maxamillion I use this fix in my playbooks a couple months. It works correct. But, I use approle only.

**Comment by maxamillion** [comment]
@kimmelserj oh ok, the error initially reported didn't match that output so I was confused. Thanks!

**Pull request merged**
