### PR TITLE
Changed atomic_replace to atomic_move, now ti DOES move atomically

### PR DESCRIPTION
**Pull request by bcoca**
Also updated modules that use it (and expected) atomic move from atomic replace

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by tartansandal** [comment]
Sadly this uses unified try/except/finally which does not exist in python 2.4. This breaks the setup module on my CentOS 5 machines.

**Comment by bcoca** [comment]
I can change this to have them nested then, but not sure how this affects
the setup module.

**Comment by mpdehaan** [comment]
Yes, that's important, we need to fix this.   I'll attack this now and we
can race.

@bcoca, what do you mean about the setup module?

**Comment by mpdehaan** [comment]
finally removed, @bcoca, let me know if this is not the fix that you would
prefer.

**Comment by bcoca** [comment]
i just forgot module_common affects all modules, my brain didn't connect my
updates that were only used in specific ones vs the syntax check that
occurs on all modules, hence my puzzlement over the reported error in the
setup module.

your change looks fine, mine just added an extra try: finally wrapping the
try: excepts

we might want to make the function a module level one, many modules don't
have a good tmp cleanup and leave stuff laying around.

On Sun, Apr 28, 2013 at 4:03 PM, Michael DeHaan notifications@github.comwrote:

> finally removed, @bcoca, let me know if this is not the fix that you would
> prefer.
> 
> On Sun, Apr 28, 2013 at 3:59 PM, Michael DeHaan michael.dehaan@gmail.comwrote:
> 
> > Yes, that's important, we need to fix this. I'll attack this now and we
> > can race.
> > 
> > @bcoca, what do you mean about the setup module?
> > 
> > On Sun, Apr 28, 2013 at 3:49 PM, Brian Coca notifications@github.comwrote:
> > 
> > > I can change this to have them nested then, but not sure how this
> > > affects
> > > the setup module.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/ansible/ansible/pull/2766#issuecomment-17141248>
> > > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/2766#issuecomment-17141504
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Pull request closed without merging**
