### PR TITLE
2.8: ansible-test yamllint: fix UnicodeDecodeError (#55364)

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Backport of #55364

(cherry picked from commit f8bebc61c8e176f8ebde9743a59b162d1df6ae6a)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

test/runner/lib/util.py

### CODE REVIEW

**Comment by abadger** [comment]
This is fine but makes me wonder... Is this ansible-test only run under python3? The surrogateescape error handler will throw an error on python2.

**Comment by mattclay** [comment]
@abadger I believe this code path is only used in CI under Python 3.6. I did try using an invalid error handler name on Python 2 and did not receive an error. Do you know what conditions are required to trigger the error?

**Comment by abadger** [comment]
@mattclay, the error has to actually be provoked.  For instance

``` python

u'café'.encode('ascii', errors='surrogateescape')
```

I believe the error thrown is a LookupError

**Comment by mattclay** [comment]
@abadger OK, that makes sense. So this will fail on Python 2 if we try to encode a value which can't be encoded with UTF-8, since that's what is used by ansible-test.

**Comment by mkrizek** [comment]
Don't we skip `encode` since `data` passed are always `bytes` (or are they not?) on Python 2 though?

**Comment by mattclay** [comment]
@mkrizek Yes, I think all current uses will only send `bytes` on Python 2.

**Pull request merged**
