### PR TITLE
route53: optimize zone_id lookup when hosted_zone_id is provided

### LINKED ISSUE #60102: route53: Skip zone listing when hosted_zone_id is set
##### SUMMARY
Improve route53 module performance when ZoneID is know

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

route53

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /home/bruno/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### STEPS TO REPRODUCE

* Define a long list of DNS records
* Use a `loop` with `route53` module to update them

```yaml
route53:
  state: present
  zone: example.com  # should not be required when hosted_zone_id is present
  private_zone: true  # should not be needed when hosted_zone_id is present
  hosted_zone_id: "XXXXXXXXXXX"
  record: "{{ item.name }}"
  ttl: "{{ item.ttl }}"
  type: "{{ item.type }}"
  value: "{{ item.value }}"
  overwrite: true
with_items: "{{ dns_records }}"
```

##### EXPECTED RESULTS

Since hosted_zone_id is provided, this should be a simple request to Route53 API

##### ACTUAL RESULTS

Currently the code in [route53.py](https://github.com/ansible/ansible/blob/41235ac05a7a52f102422da17d40b5952e722095/lib/ansible/modules/cloud/amazon/route53.py#L567) do a zone lookup witch may lead to a full listing with (possibly) pagination by boto.
This lookup returns a `zone` reference but only it's `id` attribute is read.
So, since the hosted_zone_id is the same id obtained above, and is developer responsibility to ensure it's correct, this lookup should be ignored and the provided hosted_zone_id used in place.

### PR DESCRIPTION
**Pull request by bkmeneguello**
##### SUMMARY
Don't lookup zone_id when hostted_zone_id parameter is provided

Fixes #60102

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
route53

### CODE REVIEW

**Review by jillr — COMMENTED** [review]
Thanks for this patch @bkmeneguello. Could you please add some integration tests to `test/integration/targets/route53/tasks/main.yml` that will exercise the module using `hosted_zone_id`?

**Comment by bkmeneguello** [comment]
@jillr ok, tests added

**Comment by jillr** [comment]
Thanks very much for the unit test @bkmeneguello, those are definitely a nice bonus to have. However we use [integration tests](https://github.com/ansible/community/blob/master/group-aws/integration.md)  to exercise the module code against AWS.  For this module that would mean adding some tasks to `test/integration/targets/route53/tasks/main.yml` that use the new option and assert the desired result of using the module with the option.

**Comment by bkmeneguello** [comment]
@jillr ok, integration test added (I never found these tests before, nice to know)

**Comment by jillr** [comment]
Integration test lgtm, thanks @bkmeneguello. Unfortunately the unit test is failing CI, looks like boto authentication isn't being handled in the mocks. We generally depend on integration tests because of the complexity of trying to mock out third party endpoints like AWS so you may want to just remove the unit test entirely from this PR, I'm happy to merge once CI is passing one way or another.

**Review by jillr — APPROVED** [review]

**Pull request merged**
