### PR TITLE
Pep8 fixes for apache2 module

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/web_infrastructure/apache2_mod_proxy.py
lib/ansible/modules/web_infrastructure/apache2_module.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Review by robinro — APPROVED** [review]
LGTM

**Review by n0trax — APPROVED** [review]

**Comment by n0trax** [comment]
shipit

**Comment by robinro** [comment]
shipit

**Comment by resmo** [comment]
Thanks all!

**Comment by Akasurde** [comment]
@resmo @robinro @n0trax Thanks.

**Pull request merged**
