### PR TITLE
Adding "together" lookup method. This will matrix transpose arrays that a...

### PR DESCRIPTION
**Pull request by bradleyy**
Transpose a list of arrays:
    [1, 2, 3], [4, 5, 6] -> [1, 4], [2, 5], [3, 6]
    Replace any empty spots in 2nd array with "":
    [1, 2], [3] -> [1, 3], [2, ""]

And then feed the result like with_items would

### CODE REVIEW

**Comment by mpdehaan** [comment]
A few questions/comments

(A) transpose is a name I don't care for this, .   From the list, I believe we suggested "with_together", as most folks won't know what "zip" means.  

(B) It should support lists of more than two items, have you tried this? 

(C) have you tested with something like

with_together:
- varname1
- [ 1, 2, 3 ]

(D)  For undefined variables it seems it should provide None, not empty string, so it would be easy to also pass in empty strings

(E)  seems like this should probably use itertools.zip for implementation ?

Thanks!

**Comment by bradleyy** [comment]
a) I must have missed the discussion; I named it transpose because it's doing something that looks just like a matrix transposition. I will alter this and update the pull request.

b) I have-- I ran it with the https://github.com/ansible/ansible-examples/blob/master/language_features/loop_nested.yml example (changing with_nested to with_transpose), and it did as expected:

[ 'red', 'blue', 'green' ], [ 1, 2, 3 ], [ 'up', 'down', 'strange'] -> ['red', 1, 'up'],['blue', 2, 'down'],['green', 3, 'strange'](munged for clarity)

As I mentally walk through the code, I'm somewhat dubious on this behavior, I'll dig in further.

c) If I understand your question correctly:

with_nested := [4,5,6]

with_nested, [1,2,3] -> [4,1],[5,2],[6,3]

This is the use case I outlined in #3503 ; namely something like the following:

```
name: put DB filenames in file
shell: ls {{download_dir}}/*.sql | sort
register: sql_files

name: put DB names in var
shell: ls *.sql | sort | sed -e 's/.sql//' chdir={{download_dir}}
register: db_names

name: install DBs
action: mysql_db db={{ item[0] }} state=import target={{ item[1] }}
with_nested: "{{ db_names.stdout_lines }}, {{ sql_files.stdout_lines }}"
```

I know that the "{{ db_names.stdout_lines }}, {{ sql_files.stdout_lines }}" "isn't supposed to work", but it actually does, empirically, so just ignore that for the purposes of demonstration. It effectively does all the same stuff as the with_nested (the actual code change is 3 lines replaced with 2), it just transforms the arrays differently.

d) I will alter this and update the pull request. What are your thoughts on providing an optional default on this? Is that even contextually possible (I can't think of a way to pass this in sanely)?

e) I thought about this; I don't feel that I understand well enough all the things that are going on in this code to really comment on that. In looking at the code, I've seen some things that seem like they don't work, or are superfluous, but I just don't have enough experience to really comment. 

My goal here was to just do a minimal, working solution-- which is why I asked beforehand if a 98% code overlap was okay. I'm hesitant to do greater surgery without a much better understanding of the codebase.

Related: any thoughts on making (a) test case(s) for this? Is there a decent starting point that I might crib from?

**Comment by bradleyy** [comment]
RE: c) above:

  vars:
    foo:
      - 'asdf'
      - 'wer'
      - 'cv'
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }} c={{ item[2] }} d={{ item[3] }}"
      with_together:
        - foo
        - [ 'red', 'blue', 'green' ]
        - [ 1, 2, 3 ]
        - [ 'up', 'down', 'strange']

Does what I'd expect: ['asdf', 'red', 1, 'up'], ...

**Comment by mpdehaan** [comment]
nice!

**Comment by mpdehaan** [comment]
merged in, thank you!

**Pull request merged**
