### PR TITLE
ec2_ami_copy: Fix unreferenced variable error

### LINKED ISSUE #47595: ec2_ami_copy: When using tag_equality with wait, error occurs
##### SUMMARY

When using the ec2_ami_copy module with the tag_equality and wait parameters set to true, if the AMI exists, an error occurs.  Unhandled exception. (local variable 'image_id' referenced before assignment)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_ami_copy.py

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/custom_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### STEPS TO REPRODUCE

When tag_equality and wait parameters are set and AMI exists, the problem presents itself.

```yaml
  ec2_ami_copy_pdx:
    source_region: "us-east-1"
    source_image_id: "ami-0a65asfd4"
    name: TestAMI
    tags:
      Name: "TestAMI"
    tag_equality: yes
    wait: yes
```

##### EXPECTED RESULTS

The ec2_ami_copy module should not create a new AMI and should recognize that one exists.

##### ACTUAL RESULTS

An error message occurs when running the module.

```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ec2_ami_copy_payload_bJvVsP/__main__.py", line 193, in copy_image
    ImageIds=[image_id],

fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
      aws_access_key: null
      aws_secret_key: null
      description: null
      ec2_url: null
      encrypted: false
      name: TestAMI
      profile: null
      region: null
      security_token: null
      source_image_id: ami-0a65asfd4
      source_region: us-east-1
      tag_equality: true
      tags:
        Name: TestAMI
      validate_certs: true
      wait: true
      wait_timeout: 600
  msg: Unhandled exception. (local variable 'image_id' referenced before assignment)
```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fixes: #47595

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ec2_ami_copy.py

##### ANSIBLE VERSION

```paste below
2.8-devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @willthames

**Comment by Akasurde** [comment]
@s-hertel Could you please review this ? Thanks.

**Review by s-hertel — APPROVED** [review]

**Comment by s-hertel** [comment]
rebuild_merge

**Comment by Akasurde** [comment]
@s-hertel Thanks for review and merge.

**Pull request merged**
