### PR TITLE
Basic working idempotent S3 module

### PR DESCRIPTION
**Pull request by lwade**
Sorry for the earlier hiccup, I need to spend some time with a git tutorial :)

### CODE REVIEW

**Comment by tgerla** [comment]
Nice! A few questions:
1. Is the 'key' parameter really required? The docs say it is but the code and example line says otherwise. 
2. For the TODO on line 148, maybe you could use the md5sum of the file and the E-Tag from the server if the key already exists? (like I did in my little patch to boto_rsync: https://github.com/tgerla/boto_rsync/commit/25a559fb6f61d0db23dcb1b2ee462d6403154836)

Nice work!

-Tim

**Comment by rrtj3** [comment]
Hey lwade, nice to see a S3 module. I'm could be off here but towards the end of your module you have:

``` python

# return a time-expired URL for access later in other plays etc.
    print json.dumps({
       "url": url
    })
    sys.exit(0)
```

Any reason that shouldn't be a module.exit_json() instead?

Romeo

**Comment by lwade** [comment]
Hi @romeotheriault,

Agreed.  Looking at other modules I see they return the parameters passed to them in a module.exit_json statement. Should we be looking to follow the same or a different convention here:

module.exit_json(changed=True, "url": url)  

?

@tgerla - good catch, key isn't a required argument so I will correct the docs.  Regarding etag and md5sum, great idea.  Let me fix the docs and other bits so this module can go in and then I'll create another pull for the md5 stuff, if that's ok?

**Comment by lwade** [comment]
After looking to tidy this up a little, I've been thinking about usability.  I'm thinking of removing the action parameter entirely, having both state and action seems almost counter intuitive.  The object is either in S3 or not.  With the action removed I'd then add a different parameter "download" (or similar) which is mutually exclusive to the state.  It's just ensures it pulls the contents down based on bucket and filename(key). 

Thoughts?

**Comment by rrtj3** [comment]
On Mon, Mar 11, 2013 at 9:32 PM, Lester Wade notifications@github.comwrote:

> Hi @romeotheriault https://github.com/romeotheriault,
> 
> Agreed. Looking at other modules I see they return the parameters passed
> to them in a module.exit_json statement. Should we be looking to follow the
> same or a different convention here:
> 
> module.exit_json(changed=True, "url": url)

Yup, this looks correct to me.

**Comment by mpdehaan** [comment]
@lwade I think the get/put and create/delete are sufficiently different a seperate parameter may be ok, if we can't think of a need/reason to split this into two modules.  I'll go with your judgement.

exit_json does need to be fixed though.

Want to update this one?

Thanks!

**Comment by lwade** [comment]
@mpdehaan I've gone ahead and simplified the module enough to warrant a new pull request.  I didn't like the idea of too many options which to me felt confusing, since state really should boil down to whether the object exists in S3 or not (not state = present but only if its a put operation).  I'll open a pull request for this with a download option to follow shortly after (which is an alternative to using the returned url).

**Pull request closed without merging**
