### PR TITLE
Include vars updated to work with directories

### PR DESCRIPTION
**Pull request by linuxdynasty**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

include_vars_dir
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

include_vars.py now allows you to include an entire directory and its nested directories of variable files. Created this PR in favor of #17195

Features..
- Ignore any list of files.
- Only include files nested by depth (default=unlimited)
- Match only files matching (valid regex)
- Sort files alphabetically and load in that order.
- Sort directories alphabetically and load in that order.

```
    - include_vars: 'vars/all.yml'

    - name: include all.yml
       include_vars:
          file: 'vars/all.yml'

    - name: include all yml files in vars/all and all nested directories
      include_vars:
        dir: 'vars/all'

    - name: include all yml files in vars/all and all nested directories and save the output in test.
      include_vars:
        dir: 'vars/all'
        name: test

    - name: include all yml files in vars/services
      include_vars:
        dir: 'vars/services'
        depth: 1

    - name: include only bastion.yml files
      include_vars_dir:
        dir: 'vars'
        files_matching: 'bastion.yml'

    - name: include only all yml files exception bastion.yml
      include_vars:
        dir: 'vars'
        ignore_files: 'bastion.yml'
```

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible/17207)

### CODE REVIEW

**Comment by linuxdynasty** [comment]
Builds are failing not cause of this module `ERROR! Unexpected Exception: The 'pycrypto>=2.6' distribution was not found and is required by ansible`

**Comment by linuxdynasty** [comment]
@nitzmahone Can you check on the build when you have a moment please. @jimi-c I made the changes we discussed on irc. I added the whitelist for (json, yml, and yaml). I kept the ignore_list as a parameter and not as a default that is extended, which I am using currently. I also removed the unit tests in favor of integration tests.

**Comment by nitzmahone** [comment]
@linuxdynasty Yeah, cryptography did a release this weekend that broke all our remote tests- I stuffed a fix in this afternoon and re-queued your PR build.

**Comment by abadger** [comment]
Discussed at today's meeting.  Merged!  Thanks @linuxdynasty for working on this and keeping on top of us to get it reviewed and merged!

**Comment by linuxdynasty** [comment]
Np and thank you guys for all the hard work you guys have done to build a product like Ansible.

**Comment by linuxdynasty** [comment]
@abadger this is the PR for the updated documentation https://github.com/ansible/ansible-modules-core/pull/4609

**Pull request merged**
