### PR TITLE
Update EC2 inventory script to support ELB grouping.

### PR DESCRIPTION
**Pull request by joaogbcravo**
##### SUMMARY
Update EC2 inventory script to support ELB grouping.

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
plugins/inventory/ec2.ini
plugins/inventory/ec2.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by joaogbcravo** [comment]
Guys, any new about this ?

**Comment by joaogbcravo** [comment]
Ping.

**Comment by jstoja** [comment]
@s-hertel This inventory plugin changed so much that I don't think this PR would handle it properly, even rebased. What do you think?

**Comment by s-hertel** [comment]
@joaogbcravo We are not actively working on the inventory scripts since adding the inventory plugins (new in Ansible 2.4). This feature should be addressed by creating an ELB inventory plugin using boto3. You can check out the new EC2 inventory plugin for reference. https://docs.ansible.com/ansible/latest/plugins/inventory/aws_ec2.html.
Feel free to reach out if you have questions.

**Pull request closed without merging**
