### PR TITLE
Remove exit code from traps in tests

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Having the trap exit with a specific code will override the exit code that caused the trap to run, which could mask errors.
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`test/integration/targets/incidental_inventory_docker_swarm`
`test/integration/targets/incidental_inventory_vmware_vm_inventory`

### CODE REVIEW

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
@samdoran Since both of these issues are in incidental tests, the same issues likely exist in the collections they were migrated to.

**Comment by samdoran** [comment]
I opened a PR for the Docker inventory test. https://github.com/ansible-collections/community.general/pull/391

**Comment by samdoran** [comment]
PR for the VMware inventory test: https://github.com/ansible-collections/vmware/pull/198

**Comment by samdoran** [comment]
I looked through the tests calling `trap` and didn't find any others setting the exit code explicitly.

**Pull request merged**
