### PR TITLE
docsite/rst/playbooks_tags.rst: Added section on tag reuse

### PR DESCRIPTION
**Pull request by wltjr**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

playbooks_tags
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added section on reuse of tags to playbook tags documentation

### CODE REVIEW

**Comment by wltjr** [comment]
Is there anything further I need do here, or is this PR still under consideration? I think the checks failing are from something else. I can rebase and re-push if needed. Thanks!

**Comment by dharmabumstead** [comment]
I did a mild tweak. Please feel free to rebase and re-push if needed.

**Comment by dharmabumstead** [comment]
And thanks!

**Comment by wltjr** [comment]
Think it is rebased now, something funky happened and when I pushed after rebase no change... Just deleted and re-pushed the branch.

**Comment by dharmabumstead** [comment]
Thanks @wltjr!

**Comment by wltjr** [comment]
Sure thing will see about producing some better stuff than just docs :)

**Pull request merged**
