### PR TITLE
add a description to the entrypoints example of the argument spec

### PR DESCRIPTION
**Pull request by evgeni**
##### SUMMARY

it's not said anywhere that `description` is an optional field and without it other tools (like antsibull-docs) reject the example as invalid

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE
- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bcoca** [comment]
The description field IS optional for runtime use, not that we advise leaving it out as it is what most users will look at to figure out what that variable does.

**Comment by evgeni** [comment]
doesn't leaving it out in the example *do* advise on leaving it out? :)

that said, would probably a good idea to have the list explicitly state which fields are optional and which required?

**Comment by bcoca** [comment]
not all examples need to be complete nor show recommended practice, just 'what/how things work'.

That said, yes, we should have a schema with each field explaining type, usage, default and if required or not

**Comment by felixfontein** [comment]
This PR conflicts with #79994, which completely replaces the example.

**Comment by samccann** [comment]
Thanks @evgeni for this docs PR. Given there are two other PRs with more detail on the argspec, I'm closing this one in favor of the others (including https://github.com/ansible/ansible/pull/80658).

**Pull request closed without merging**
