### PR TITLE
Fix/archive empty file

### LINKED ISSUE #34569: Archive module does not adds empty(zero-size) files to dest archive
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
archive

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY
Archive module does not add empty(zero-size) files to archive. I think it is caused by this condition https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/archive.py#L319

In this condition we are comparing file that we adding to archive with just created archive. In case of empty file it should not work. Why do we need this condition?

##### STEPS TO REPRODUCE
1. Create directory and few empty files in it
2. Fill files except one with some data
3. Apply playbook to this directory

```
$ ls -la ~/test-archive-bug/
total 12
drwxrwxrwx 0 user user 4096 Jan  8 13:20 .
drwxr-xr-x 0 user user 4096 Jan  8 13:16 ..
-rw-rw-rw- 1 user user    2 Jan  8 13:12 1.txt
-rw-rw-rw- 1 user user    2 Jan  8 13:12 2.txt
-rw-rw-rw- 1 user user    0 Jan  8 13:12 3.txt
```
```
$ cat test.yml
```
```yaml
- hosts: all
  tasks:
    - name: Test archive
      archive:
        path: /home/user/test-archive-bug
        dest: /home/user/test.tar.gz
        format: gz
```
```
$ ansible-playbook test.yml -c local -i localhost,
```
4. See that file with zero-size was not added to archive

##### EXPECTED RESULTS
That all files including empty file will be added to archive

##### ACTUAL RESULTS
Empty(zero-size) file was not added to archive

### PR DESCRIPTION
**Pull request by nbendafi-yseop**
##### SUMMARY

Fixes #34569
Removes a call to filecmp that probably protected against adding the archive file to itself (but is unnecessary). This change fixes an issue where empty files were not being added to archives

This PR is just a rebase of PR #56139, stale for months.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`archive` module

##### ADDITIONAL INFORMATION
<details><summary><i>ansible-test integration  --allow-root --allow-destructive --docker archive</i> 
</summary><p>

```bash
Running archive integration test role

PLAY [testhost] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [testhost]

TASK [archive : Ensure zip is present to create test archive (yum)] ************
skipping: [testhost]

TASK [archive : Ensure zip is present to create test archive (apt)] ************
changed: [testhost]

TASK [archive : Set liblzma package name depending on the OS] ******************
skipping: [testhost]

TASK [archive : Ensure liblzma-dev is present to install backports-lzma] *******
skipping: [testhost]

TASK [archive : Find brew binary] **********************************************
skipping: [testhost]

TASK [archive : Get owner of brew binary] **************************************
skipping: [testhost]

TASK [archive : Install package] ***********************************************
skipping: [testhost]

TASK [archive : Ensure backports.lzma is present to create test archive (pip)] ***
skipping: [testhost]

TASK [archive : prep our files] ************************************************
changed: [testhost] => (item=foo.txt)
changed: [testhost] => (item=bar.txt)
changed: [testhost] => (item=empty.txt)

TASK [archive : archive using gz] **********************************************
changed: [testhost]

TASK [archive : debug] *********************************************************
ok: [testhost] => {
    "msg": {
        "archived": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "arcroot": "/root/ansible/test/results/.tmp/output_dir/",
        "changed": true,
        "dest": "/root/ansible/test/results/.tmp/output_dir/archive_01.gz",
        "expanded_exclude_paths": [],
        "expanded_paths": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "failed": false,
        "gid": 0,
        "group": "root",
        "missing": [],
        "mode": "0644",
        "owner": "root",
        "size": 217,
        "state": "file",
        "uid": 0
    }
}

TASK [archive : verify that the files archived] ********************************
ok: [testhost]

TASK [archive : check if gz file exists and includes all text files] ***********
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : archive using zip] *********************************************
changed: [testhost]

TASK [archive : debug] *********************************************************
ok: [testhost] => {
    "msg": {
        "archived": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "arcroot": "/root/ansible/test/results/.tmp/output_dir/",
        "changed": true,
        "dest": "/root/ansible/test/results/.tmp/output_dir/archive_01.zip",
        "expanded_exclude_paths": [],
        "expanded_paths": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "failed": false,
        "gid": 0,
        "group": "root",
        "missing": [],
        "mode": "0644",
        "owner": "root",
        "size": 317,
        "state": "file",
        "uid": 0
    }
}

TASK [archive : verify that the files archived] ********************************
ok: [testhost]

TASK [archive : check if zip file exists] **************************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : archive using bz2] *********************************************
changed: [testhost]

TASK [archive : debug] *********************************************************
ok: [testhost] => {
    "msg": {
        "archived": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "arcroot": "/root/ansible/test/results/.tmp/output_dir/",
        "changed": true,
        "dest": "/root/ansible/test/results/.tmp/output_dir/archive_01.bz2",
        "expanded_exclude_paths": [],
        "expanded_paths": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "failed": false,
        "gid": 0,
        "group": "root",
        "missing": [],
        "mode": "0644",
        "owner": "root",
        "size": 163,
        "state": "file",
        "uid": 0
    }
}

TASK [archive : verify that the files archived] ********************************
ok: [testhost]

TASK [archive : check if bzip file exists] *************************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : archive using xz] **********************************************
changed: [testhost]

TASK [archive : debug] *********************************************************
ok: [testhost] => {
    "msg": {
        "archived": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "arcroot": "/root/ansible/test/results/.tmp/output_dir/",
        "changed": true,
        "dest": "/root/ansible/test/results/.tmp/output_dir/archive_01.xz",
        "expanded_exclude_paths": [],
        "expanded_paths": [
            "/root/ansible/test/results/.tmp/output_dir/foo.txt",
            "/root/ansible/test/results/.tmp/output_dir/empty.txt",
            "/root/ansible/test/results/.tmp/output_dir/bar.txt"
        ],
        "failed": false,
        "gid": 0,
        "group": "root",
        "missing": [],
        "mode": "0644",
        "owner": "root",
        "size": 224,
        "state": "file",
        "uid": 0
    }
}

TASK [archive : verify that the files archived] ********************************
ok: [testhost]

TASK [archive : check if xz file exists] ***************************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : archive and set mode to 0600] **********************************
changed: [testhost]

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost]

TASK [archive : debug] *********************************************************
ok: [testhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "stat": {
            "atime": 1573821619.1603184,
            "attr_flags": "",
            "attributes": [],
            "block_size": 4096,
            "blocks": 8,
            "charset": "unknown",
            "checksum": "0d51d04c0531f7252cae80f58823fd0f4b20ab2f",
            "ctime": 1573821619.1603184,
            "dev": 49,
            "device_type": 0,
            "executable": false,
            "exists": true,
            "gid": 0,
            "gr_name": "root",
            "inode": 258093,
            "isblk": false,
            "ischr": false,
            "isdir": false,
            "isfifo": false,
            "isgid": false,
            "islnk": false,
            "isreg": true,
            "issock": false,
            "isuid": false,
            "mimetype": "unknown",
            "mode": "0600",
            "mtime": 1573821619.1603184,
            "nlink": 1,
            "path": "/root/ansible/test/results/.tmp/output_dir/archive_02.gz",
            "pw_name": "root",
            "readable": true,
            "rgrp": false,
            "roth": false,
            "rusr": true,
            "size": 217,
            "uid": 0,
            "version": null,
            "wgrp": false,
            "woth": false,
            "writeable": true,
            "wusr": true,
            "xgrp": false,
            "xoth": false,
            "xusr": false
        }
    }
}

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove our gz] *************************************************
changed: [testhost]

TASK [archive : archive and set mode to 0600] **********************************
changed: [testhost]

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost]

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove our zip] ************************************************
changed: [testhost]

TASK [archive : archive and set mode to 0600] **********************************
changed: [testhost]

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost]

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove our bz2] ************************************************
changed: [testhost]

TASK [archive : archive and set mode to 0600] **********************************
changed: [testhost]

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost]

TASK [archive : Test that the file modes were changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove our xz] *************************************************
changed: [testhost]

TASK [archive : test that gz archive that contains non-ascii filenames] ********
changed: [testhost]

TASK [archive : Check that file is really there] *******************************
ok: [testhost]

TASK [archive : Assert that nonascii tests succeeded] **************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove nonascii test] ******************************************
changed: [testhost]

TASK [archive : test that bz2 archive that contains non-ascii filenames] *******
changed: [testhost]

TASK [archive : Check that file is really there] *******************************
ok: [testhost]

TASK [archive : Assert that nonascii tests succeeded] **************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove nonascii test] ******************************************
changed: [testhost]

TASK [archive : test that xz archive that contains non-ascii filenames] ********
changed: [testhost]

TASK [archive : Check that file is really there] *******************************
ok: [testhost]

TASK [archive : Assert that nonascii tests succeeded] **************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove nonascii test] ******************************************
changed: [testhost]

TASK [archive : test that zip archive that contains non-ascii filenames] *******
changed: [testhost]

TASK [archive : Check that file is really there] *******************************
ok: [testhost]

TASK [archive : Assert that nonascii tests succeeded] **************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [archive : remove nonascii test] ******************************************
changed: [testhost]

TASK [archive : Remove backports.lzma if previously installed (pip)] ***********
skipping: [testhost]

PLAY RECAP *********************************************************************
testhost                   : ok=52   changed=22   unreachable=0    failed=0    skipped=8    rescued=0    ignored=0
```
</p></details>

### CODE REVIEW

**Comment by Akasurde** [comment]
@jpmens Could you please review this? Thanks in advance.

**Comment by jpmens** [comment]
@Akasurde LGTM

**Comment by jpmens** [comment]
shipit

**Comment by Akasurde** [comment]
rebuild_merge

**Pull request merged**
