### PR TITLE
Replacement for apt_repository.

### PR DESCRIPTION
**Pull request by sashka**
1. Debian Squeeze is supported out of box now.
2. Repository type "deb" or "deb-src" should be explicitly specified.
3. If a source had beed added it must be possible to remove it.
4. PPA can be only used against Ubuntu hosts.

### CODE REVIEW

**Comment by jimi-c** [comment]
Do we want to change the version_added field? It's true this is a complete rewrite of the module, but that doesn't necessarily change when the original module was added to the core modules.

**Comment by sashka** [comment]
@mpdehaan please change version_added yourself, when you merge this.

**Comment by jimi-c** [comment]
@sashka I'm taking over a lot of the day to day merging stuff, so I can fix that, just wanted to get other's opinions - I'm not sure if this situation has been encountered before.

**Comment by srgvg** [comment]
@jimi1283 afaicr this is the first module being rewritten; 
sounds like version_added should remain the original version, as this is supposed to be backwards compatible

**Comment by jimi-c** [comment]
@sashka could you rebase this? It looks like it won't merge cleanly due to other changes. I'll get this tested today.

**Comment by sashka** [comment]
@jimi1283 rebased. please check.

**Comment by jimi-c** [comment]
Thanks, testing now.

**Comment by jimi-c** [comment]
Merged, thanks! Since I reverted the version_added field, github isn't reflecting the status update correctly, so I'm closing this manually.

**Pull request closed without merging**
