### PR TITLE
Second batch for _facts -> _info rename

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Continues #56822.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
jenkins_job_facts
intersight_facts
github_webhook_facts

### CODE REVIEW

**Comment by felixfontein** [comment]
FYI: this PR includes no new modules, it renames three modules.

**Review by acozine — APPROVED** [review]
Docs changes look good.

**Review by dsoper2 — APPROVED** [review]
Shipit

**Comment by felixfontein** [comment]
bot_status

**Comment by felixfontein** [comment]
CC @stpierre as author of github_webhook_facts and jenkins_job_facts

**Review by Andersson007 — CHANGES_REQUESTED** [review]
@felixfontein , check there please
```
./lib/ansible/modules/source_control/_github_hooks.py:  alternative: Use M(github_webhook) and M(github_webhook_facts) instead.
```

**Review by Andersson007 — APPROVED** [review]
great, thanks!

shipit

**Comment by felixfontein** [comment]
@acozine @dsoper2 @Andersson007 thanks a lot for reviewing this!

**Pull request merged**
