### PR TITLE
Ansible vault: a framework for encrypting any playbook or var file.

### PR DESCRIPTION
**Pull request by jctanner**
```
$ ansible-vault --help
Usage: ansible-vault [create|decrypt|edit|encrypt|rekey] [--help] [options] file_name

Options:
  -h, --help  show this help message and exit

See 'ansible-vault <command> --help' for more information on a specific command.
```
- create: start a new encrypted file
- decrypt: unencrypt file(s) in place
- edit: open an encrypted file in the default editor
- encrypt: encrypt file(s) in place
- rekey: decrypt with previous password, re-encrypt with new password

```
$ ansible-playbook -i inventory site.yml --ask-vault-pass
Vault password:
```

### CODE REVIEW

**Comment by sivel** [comment]
I may have missed it here, but will there be an ansible.cfg configuration option for ask_vault_pass ?

**Comment by jctanner** [comment]
@sivel I'll look into adding that. For now, it produces an error if any file is encrypted and no password is given.

**FIXED**

**Comment by mpdehaan** [comment]
Hi everybody -- There will be a ansible-project mailing list thread about this shortly -- we can answer questions on that thread once we get it up there.

**Comment by mpdehaan** [comment]
We've talked about adding "soft imports" so the crypto libs aren't brought in unless used, and will be adding this as a package dependency

**Comment by mpdehaan** [comment]
Possibly some things going on with pycrypto from pip and RHEL underlying libs....

**Comment by mpdehaan** [comment]
If I don't have the library installed I get:

python Crypto.Foo.Bar.Something.AES is not installed

This should probably say something like "pycrypto is not installed.  Fix this with your package manager, for instance, yum-install python-crypto OR (apt equivalent)"

**FIXED**

**Comment by mpdehaan** [comment]
Installing from pip seems to be able to generate a version that is incompatible with the EL6 guest.  We may have to intercept that error and warn about it.   (testing this shortly)

**Comment by mpdehaan** [comment]
ansible-vault should probably print "encryption successful" or "decryption successful" for commands that don't spawn an editor.

**FIXED**

The message "add more entropy" should probably say "add more entropy (suggest using mouse inputs".  I'm guessing some people won't know what entropy sources are.

**FIXED**

**Comment by mpdehaan** [comment]
The message on an invalid decryption should mention the decryption failed

[root@localhost ansible]# ansible-playbook /tmp/test.yml -i /tmp/hosts -c local --ask-vault-pass
Vault password: 
ERROR: A vault password must be specified to decrypt /tmp/test2.yml

**FIXED**

**Comment by mpdehaan** [comment]
Just got that from entering the password correctly with vars_files.

**Comment by mpdehaan** [comment]
When specifying an invalid password with vars_files, I get the message:

fatal: [localhost] => A vault password must be specified to decrypt /tmp/group_vars/region

This should be changed to be more clear

"Vault password incorrect for /tmp/group_vars/region"

As above, it's unclear if a password was supplied or not, and we do know.

**FIXED**

**Comment by mpdehaan** [comment]
I'm also unable to get group-vars working with the correct password so this seems generic on my platform

**Comment by mpdehaan** [comment]
password on encrypt or create should probably be a double prompt

**FIXED**

**Comment by mpdehaan** [comment]
and also rekey

**Comment by mpdehaan** [comment]
We also want to add pycrypto to the dependencies for at least the RPM and dpkg builds.

**Comment by mpdehaan** [comment]
Can remove "if 1" here:

https://github.com/jctanner/ansible/commit/98f079f62a7ba6f0325977252ff01604e29eaf31#diff-b270ccfb9473766a7e7790c7ff58f277R169

**FIXED**

**Comment by mpdehaan** [comment]
This check should probably be explicitly against None as empty string is also False:
-    if not password:

**FIXED**

**Comment by mpdehaan** [comment]
(Note: earlier comment about pycrypto from pip is not a thing, correctly refused to install, which is good)

**Comment by mpdehaan** [comment]
ansible-vault create should not the start the file with "---" and nothing should assume "---" must be in the file as we may want to also support JSON files.

**FIXED**

**Comment by bcoca** [comment]
testing on Ubuntu, works nicely so far, aside from already made comments
for password verification (you've seen how often i mysytpe).

**Comment by mpdehaan** [comment]
For rekey, should not ask for new password if decrypt on old password fails, should also double up on the new password prompt.

**Comment by mpdehaan** [comment]
ERROR:  global name 'out path' is not defined

this is what you get when you try to rekey an unencrypted file.  Should instead error out that the file was unencrypted

**FIXED**

**Comment by mpdehaan** [comment]
The "-n" parameter for rekey should be removed (was removed elsewhere so this is just a straggler)

**FIXED**

**Comment by bcoca** [comment]
When using edit, I would try delete/unlink the tempfile, even though
permissions are already restrictive (stdin to vim?).

Also is the tmp dir configurable? I am partial to ~/.cache.

**Comment by mpdehaan** [comment]
in utils/vault.py this can be simplified:

```
# read first line of the file
with open(filename) as f:
    head=[f.next() for x in xrange(1)]
```

To:

```
head = f.next()
```

and then later just use head vs head[0]

Easier might just be to use .read with a byte limit and use ".startswith"

**FIXED**

**Comment by mpdehaan** [comment]
per code standards, the instance Vault should be assigned to a variable "V", should be named "vault = Vault(...)" or "my_vault", etc.

**FIXED**

Also if Vault is a useful class we should not be calling private methods on it.   (V._strip_sha).   Should this funciton be named "decrypt?" or something similar?

**Comment by mpdehaan** [comment]
encrypt seems to assume writing to a file.    There should be an in-memory version for unit test purposes and a seperate function/abstraction/layer that writes to files.

(consider maybe using a cStringIO)

**Comment by mpdehaan** [comment]
various "f = open" ... "f.close" logic could be written in utils/vault.py to use the "with" operator.

**Comment by mpdehaan** [comment]
In "_strip_sha", instead of "del_lines[0]" do 

'\n'.join(lines[1:])

**FIXED**

**Comment by mpdehaan** [comment]
There is support for a version in the header string but the code doesn't have a way to know if the version of a future vault is "too new".

The code should have a constant "VAULT_VERSION_MAX" or similar and raise an error if the header exceeds it.  Similarly probably also a "VAULT_VERSION_MIN".   For the initial release both of these could be 1.0

**FIXED**

**Comment by bcoca** [comment]
also, could there be a choice of encryption methods? AES is nice but
sometimes policy requires us to use specific suites and lengths .

**Comment by mpdehaan** [comment]
We just noticed gather_facts: no affects it a little.  WIP.

(Need to plumb through to Runner in ansible-playbook)

**FIXED**

**Comment by bcoca** [comment]
ansible-vault create file.test.yml, creates the encrypted file even if I
quit out of the editor, I would expect it not to.

**Comment by jctanner** [comment]
@bcoca the cipher is "pluggable" so that contributors can submit others. Check how the "AES" class is loaded.

**Comment by jctanner** [comment]
@bcoca "creates the encrypted file even if I quit out of the editor," ...

How are you "quitting"?

**Comment by bcoca** [comment]
On Mon, Feb 17, 2014 at 5:52 PM, jctanner notifications@github.com wrote:

> the encrypted file even if I quit out of the editor," ...
> 
> How are you "quitting"?

:q! <= not a smiley

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jctanner** [comment]
Superseded by https://github.com/ansible/ansible/pull/6058

**Pull request closed without merging**
