### PR TITLE
Adding ipmi settings for zabbix host

### PR DESCRIPTION
**Pull request by kagerman**
##### SUMMARY
Updated the zabbix_host module that also it also can configure IPMI settings (ipmi_authtype ipmi_privilege, ipmi_username, ipmi_password) on Zabbix Host

##### ISSUE TYPE
 - Feature Pull Request
 
##### COMPONENT NAME

zabbix_host

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.1.0
  config file = /home/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

### CODE REVIEW

**Comment by D3DeFi** [comment]
Hi, this unfortunately introduces duplicate work already implemented in #23855. Thanks for the effort, but I would like to stick with the previous PR as it already has been reviewed and incorporated few of our suggestions.

@eikef What is your opinion on this? I can give this code a quick test if needed.

**Comment by eikef** [comment]
I am unsure. #23855 was ready to merge before the most recent set of updates to the code and is now in conflict; it was lacking check_all_properties handling (which this PR appears to do), and there hasn't been any activity in a couple of weeks. 

It sucks that there was duplicated effort. I haven't looked at this PR in-depth yet either.

**Comment by kagerman** [comment]
Hello. Anyway I add to PR documentation and exapmple section with ipmi-*.
Please let me know whether you will consider this PR.
Thx.

**Comment by D3DeFi** [comment]
Just gave it some testing. This seems to incorporate every change I have requested in the #23855. It does have a little bit better documentation as well. As for the tests, everything seems to work with Zbx server 3.2. Good job.

If we decide to go with your PR after all, you'll have my 'shipit'.

**Comment by eikef** [comment]
Generally this looks good, but there are some idempotency problems.

If one does not specify any of the IPMI options, this will nevertheless update the authtype and privilege to -1 and 2, respectively (whereas not specifying ipmi_password and ipmi_username will leave those fields alone since they are then None). 

So if after 

```
    - name: test1
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_server_url }}"
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        host_name: ExampleHost
        ipmi_authtype: 4
        ipmi_privilege: 4
        ipmi_username: username
        ipmi_password: password
```
you do 

```    
    - name: test2
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_server_url }}"
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        host_name: ExampleHost
```
The authtype and privilege will be set to -1 and 2, respectively (and incidentally, the ipmi_username and ipmi_password will be reset if you change either authtype or privilege, so in this case they will be set to empty as well).

A fix for that might be to not define defaults for those two options in ansible. I have not tested that though.

Other than that this looks good.

**Comment by kagerman** [comment]
Hi! In last commit I change default values for ipmi_authtype and ipmi_privilege

**Comment by eikef** [comment]
shipit

**Comment by D3DeFi** [comment]
shipit

**Comment by eikef** [comment]
bot_status

**Comment by eikef** [comment]
@kagerman the automerge workflow did not work because there are commits by multiple Github users in your PR -- namely the first commit is by a different account than the subsequent ones.
If they are all by you, can you please squash them into a single commit, or alternatively confirm that the first commit is also by you so the core team can squash/merge on your behalf?

(if you squash and we do shipits again, the bot should then automerge the PR, otherwise manual intervention by the core team is necessary).

**Comment by kagerman** [comment]
Yes I confirm that the first commit made by me.
For some reason, github client did not correctly load the account

**Comment by gundalow** [comment]
Squashed and merged into `devel`, will be released in Ansible 2.5.0

**Pull request merged**
