### PR TITLE
Add support for a new lookup: with_batch

### PR DESCRIPTION
**Pull request by dmsimard**
##### SUMMARY
This adds support for a new lookup, ``with_batch``, which provides the ability to batch a larger list into a list of smaller lists, with the max length of the smaller lists defined by the ``batch_lookup_size`` variable or defaulting to ``5``.

The use case is explained and demonstrated in the docs and integration tests included in the commit.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
plugins/lookups/batch

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```

##### ADDITIONAL INFORMATION
Example run from included integration test:

```
PLAY [Test playbook] ************************************************************************************

TASK [test : Configure variables for batch lookup plugin test] ******************************************
ok: [localhost]

TASK [test : Run items asynchronously in batch] *********************************************************
included: /home/dmsimard/dev/ansible-sandbox/playbooks/roles/test/tasks/execute_batch.yml for localhost
included: /home/dmsimard/dev/ansible-sandbox/playbooks/roles/test/tasks/execute_batch.yml for localhost
included: /home/dmsimard/dev/ansible-sandbox/playbooks/roles/test/tasks/execute_batch.yml for localhost

TASK [test : Increment batch count] *********************************************************************
ok: [localhost]

TASK [test : Executing a batch of 2 items] **************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": [
        1, 
        2
    ]
}

TASK [test : Async sleeping for batched_items] **********************************************************
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)

TASK [test : Check sync status] *************************************************************************
changed: [localhost] => (item={'_ansible_parsed': True, '_ansible_item_result': True, u'async_item': 1, '_ansible_no_log': False, u'ansible_job_id': u'480561658577.6217', u'started': 1, 'changed': True, u'finished': 0, u'results_file': u'/root/.ansible_async/480561658577.6217', '_ansible_item_label': 1})
FAILED - RETRYING: Check sync status (30 retries left).
changed: [localhost] => (item={'_ansible_parsed': True, '_ansible_item_result': True, u'async_item': 2, '_ansible_no_log': False, u'ansible_job_id': u'296429500413.6241', u'started': 1, 'changed': True, u'finished': 0, u'results_file': u'/root/.ansible_async/296429500413.6241', '_ansible_item_label': 2})

TASK [test : Increment batch count] *********************************************************************
ok: [localhost]

TASK [test : Executing a batch of 2 items] **************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": [
        3, 
        4
    ]
}

TASK [test : Async sleeping for batched_items] **********************************************************
changed: [localhost] => (item=3)
changed: [localhost] => (item=4)

TASK [test : Check sync status] *************************************************************************
FAILED - RETRYING: Check sync status (30 retries left).
changed: [localhost] => (item={'_ansible_parsed': True, '_ansible_item_result': True, u'async_item': 3, '_ansible_no_log': False, u'ansible_job_id': u'441057840499.6326', u'started': 1, 'changed': True, u'finished': 0, u'results_file': u'/root/.ansible_async/441057840499.6326', '_ansible_item_label': 3})
changed: [localhost] => (item={'_ansible_parsed': True, '_ansible_item_result': True, u'async_item': 4, '_ansible_no_log': False, u'ansible_job_id': u'117512915709.6350', u'started': 1, 'changed': True, u'finished': 0, u'results_file': u'/root/.ansible_async/117512915709.6350', '_ansible_item_label': 4})

TASK [test : Increment batch count] *********************************************************************
ok: [localhost]

TASK [test : Executing a batch of 1 items] **************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": [
        5
    ]
}

TASK [test : Async sleeping for batched_items] **********************************************************
changed: [localhost] => (item=5)

TASK [test : Check sync status] *************************************************************************
FAILED - RETRYING: Check sync status (30 retries left).
FAILED - RETRYING: Check sync status (29 retries left).
changed: [localhost] => (item={'_ansible_parsed': True, '_ansible_item_result': True, u'async_item': 5, '_ansible_no_log': False, u'ansible_job_id': u'612682492163.6437', u'started': 1, 'changed': True, u'finished': 0, u'results_file': u'/root/.ansible_async/612682492163.6437', '_ansible_item_label': 5})

TASK [test : debug] *************************************************************************************
ok: [localhost] => {
    "batch_count": "3", 
    "changed": false
}

TASK [test : assert] ************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY RECAP **********************************************************************************************
localhost                  : ok=18   changed=6    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by odyssey4me** [comment]
👍 excellent, more control than just using forks

**Comment by evrardjp** [comment]
I like it.

**Comment by sivel** [comment]
This can already be achieved by just using `|batch` directly with `with_items`

```
---
- hosts: all
  vars:
    things:
      - 1
      - 2
      - 3
      - 4
      - 5
  tasks:
    - debug:
        var: item
      with_items:
        - "{{ things|batch(2)|list }}"
```

which produces:

```
ok: [localhost] => (item=[1, 2]) => {
    "item": [
        1,
        2
    ]
}
ok: [localhost] => (item=[3, 4]) => {
    "item": [
        3,
        4
    ]
}
ok: [localhost] => (item=[5]) => {
    "item": [
        5
    ]
}
```

-1 from me

**Comment by dmsimard** [comment]
So, it turns out that I ran with some wrong assumptions:
- "with_items" always flatten nested lists: Wrong, it only flattens the first depth
- The batch jinja2 filter returns a generator, not a list which is incompatible with with_items: Wrong, you can empty the generator and provide the list like so ``{{ foo | batch(2) | list }}``

I'll close this.

**Comment by dmsimard** [comment]
Docs PR to document the things unearthed by the discussion around this topic: https://github.com/ansible/ansible/pull/24457

**Pull request closed without merging**
