### PR TITLE
VMware: Add new module: vmware_host_service_facts

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This adds module to gather facts about VMware host service facts.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_host_service_facts.py
test/integration/targets/vmware_host_service_facts/aliases
test/integration/targets/vmware_host_service_facts/tasks/main.yml

##### ANSIBLE VERSION

```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @pdellaert @tchernomax

**Review by pdellaert — APPROVED** [review]
LGTM
shipit

**Review by tchernomax — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@pdellaert @tchernomax Thanks for review and merge.

**Pull request merged**
