### PR TITLE
include_vars : auto leef param

### PR DESCRIPTION
**Pull request by pae23**
##### SUMMARY
This pull request offers a new boolean param for the include_vars.
It permits to auto add the path name as leefs in the vars dict.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
include_vars

##### ANSIBLE VERSION
devel

##### ADDITIONAL INFORMATION
For example, if you have a var dir with:
- subdir1/
- subdir1/file1 containing
```
---
- myvar : value1
```
- subdir2
- subdir2/file2 containing
```
---
- myvar : value2
```

without this param you'll only get : 
dict {myvar : value2}

with this param, you'll get:
dict {subdir1 : { file1 : { myvar : value1} } , {subdir2 : { file1 : { myvar : value2} } }

If you like this feature, I'll write the documentation for too. If you have better idea for the param wording, I can change it too.

### CODE REVIEW

**Comment by bcoca** [comment]
-1 just from possible directory names  not being valid variable names, but if you really want a var heir ..write it directly in YAML .. there is no need to get it indirectly from dir structure.

**Comment by pae23** [comment]
For variable name, I can add a validity test.
My needs is to guarantee by design that the content of a yaml file can't override other variables and stay in a subtree I decided (because in my usecase, those yaml file are written by third parts)

**Comment by bcoca** [comment]
you can easily use the existing `name=` option to guarantee this and have predictable variable names

**Comment by pae23** [comment]
You're right for a file include_var but for a recursively dir, that doesn't help.

**Comment by nitzmahone** [comment]
This seems a little too niche-case for typical usage, so we're going to decline. If you think there are more generally-applicable uses for this, feel free to come discuss at an IRC meeting... Thanks!

**Pull request closed without merging**
