### PR TITLE
Remove required field on service_account_file in gcp_compute plugin inventory

### LINKED ISSUE #57344: gcp_compute dynamic inventory not working with auth_kind: application/machineaccount
##### SUMMARY

Gcp_compute plugin inventory doesn't work when params auth_kind is not set to serviceaccount and service_account_file is defined.
The module accept others values for auth_kind ( application and machineaccount) which not working in ansible 2.8 and ansible devel

The bug was introduced by adding a required field on service_account_file params which not required with auth_kind others values

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.0 + devel
```

##### STEPS TO REPRODUCE

```bash
export GOOGLE_APPLICATION_CREDENTIALS=account.json
ansible-inventory -i inventories/gcp_compute.yml --graph
```

gcp_compute.yml

```yaml
plugin: gcp_compute
auth_kind: application
zones: # populate inventory with instances in these regions
  - europe-west1-b
  - europe-west1-c
  - europe-west1-d
projects:
  - lab-k8s
filters: []

```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

```paste below
gcp_compute.yml with auto plugin: No setting was provided for required configuration plugin_type: inventory plugin: gcp_compute setting: service_account_file
```

### PR DESCRIPTION
**Pull request by LucasBoisserie**
##### SUMMARY

Fixes #57344

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

gcp_compute inventory plugin

### CODE REVIEW

**Comment by rrey** [comment]
lgtm ship_it

**Comment by kustodian** [comment]
lgtm

This should also be backported to 2.7/2.8.

**Comment by rrey** [comment]
ship_it

**Comment by rambleraptor** [comment]
shipit

**Pull request merged**
