### PR TITLE
Add types to docker module fragments

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
Add types to common docker module parameters.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docker module docs

### CODE REVIEW

**Comment by felixfontein** [comment]
The CI failure is totally unrelated to the PR.

**Review by felixfontein — APPROVED** [review]
Thanks for updating the module docs fragment!

LGTM

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Merged into `devel`, thanks!

**Comment by felixfontein** [comment]
@dagwieers thanks for adding the types!
@gundalow thanks for merging!

**Pull request merged**
