### PR TITLE
Update conjur_variable.py

### PR DESCRIPTION
**Pull request by izgeri**
##### SUMMARY
Update the link in the Conjur documentation to point to the correct current URL
for information on Conjur machine identity.

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jvanderhoof** [comment]
shipit

**Review by cbudz — APPROVED** [review]
Looks good to me, thanks @izgeri

**Comment by cbudz** [comment]
@acozine This is ready to merge.

**Comment by cyberark-bizdev** [comment]
shipit

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @izgeri for the Ansible documentation fix!

**Comment by izgeri** [comment]
@samccann how long does it usually take changes like this to propagate to the official documentation site? I'd like to keep an eye out for it, but I'm not sure what the timeline is :) I'd appreciate any info you can share.

**Comment by samccann** [comment]
PRs are merged into the 'devel' branch and republished overnight.  If you want this on the 'latest' aka 2.9, then you'll need to backport it. You can see the steps to do this at:
https://docs.ansible.com/ansible/latest/community/development_process.html#backporting-merged-prs

Thanks!

**Pull request merged**
