### PR TITLE
vmware_guest_facts: Add delegate_to directive to example

### LINKED ISSUE #22840: Unable to use the module to query Vmware host
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
vmware_vm_facts module

##### ANSIBLE VERSION
N/A

##### SUMMARY
Hi Guys,

For the most part I have got anisble almost working to talk to my Esxi host. I have created my playbook to use the module "vmware_get_facts" but when I run my "ansible-playbook vmware.yml" file I get the error

"FAILED! => {"changed": false, "failed": true, "msg": "pyvmomi is required for this module"}
[WARNING]: Could not create retry file '/etc/ansible/playbooks/vmware.retry'. [Errno 13] Permission denied: u'/etc/ansible/playbooks/vmware.retry'"

My python version is 2.7 and I have installed the PyVmomi module using pip install pyvmomi and then pip install --upgrade pyvmomi, however i still get the error which says the module isnt installed? (wierd).
I have gotten past all the authentication errors but sadly stuck on this...

Any ideas?!

-A

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY

Without it, this is not going to do what most people expect.

This fixes #22840

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

vmware_guest_facts

##### ANSIBLE VERSION

v2.3

### CODE REVIEW

**Comment by nerzhul** [comment]
ofc better examples means less errors

shipit

**Review by nerzhul — APPROVED** [review]

**Comment by dagwieers** [comment]
@gundalow @jctanner Can we merge this ?

**Comment by gundalow** [comment]
Is this for 2.3.1?
Unless it's a critical issues I don't believe even it will make it for 2.3.0.

**Comment by dagwieers** [comment]
@gundalow It's a documentation fix. If those cannot go into v2.3 then don't backport. At least it applies to v2.3 and newer. Same as #22932 BTW

**Comment by gundalow** [comment]
Merged into 'devel`
We will soon be generating docs for devel +2.3 +2.2,so I'll make a note to backport this once stable-2.3 is opened up again.

**Pull request merged**
