### PR TITLE
Change "arguments" to "missing_arguments"

### PR DESCRIPTION
**Pull request by wzyboy**
`if arguments: raise Expcetion('... missing arguments ...')` is way too confusing...

### CODE REVIEW

**Comment by amenonsen** [comment]
This PR can be closed, the underlying code in devel is completely different and this is no longer relevant.

**Comment by wzyboy** [comment]
This pull request became stale because the maintainer did not merge it ...

**Comment by amenonsen** [comment]
Sure, it's unfortunate that it got lost in the huge backlog. Sorry about that. But the fact remains that it is no longer relevant, so this PR should be closed.

**Comment by wzyboy** [comment]
Okay...

**Pull request closed without merging**
