### PR TITLE
Fix fetching ios default running config

### LINKED ISSUE #39342: failed with ios_config module that using wrong "show running-config all"
**ISSUE TYPE**
Bug Report

**COMPONENT NAME**
ios_config

**ANSIBLE VERSION**

> ansible 2.5.1
>   config file = /root/ansible-network/ansible.cfg
>   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/dist-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

**CONFIGURATION**
DEFAULT_HOST_LIST(/root/ansible-network/ansible.cfg) = [u'/root/ansible-network/inventory']
DEFAULT_TIMEOUT(/root/ansible-network/ansible.cfg) = 30
HOST_KEY_CHECKING(/root/ansible-network/ansible.cfg) = False

**OS / ENVIRONMENT**
Ubuntu 16.04

**SUMMARY**
I'm using ansible 2.5.0 and trying to use ios_config to config my cisco switch but getting this error:

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: R2#
> fatal: [172.199.1.3]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_MB6pxe/ansible_module_ios_config.py\", line 5
> 73, in <module>\n    main()\n  File \"/tmp/ansible_MB6pxe/ansible_module_ios_config.py\", line 476, in main\n    config, have_banners = get_running_config(module, config)\n
>  File \"/tmp/ansible_MB6pxe/ansible_module_ios_config.py\", line 374, in get_running_config\n    contents = get_config(module, flags=flags)\n  File \"/tmp/ansible_MB6pxe/ans
> ible_modlib.zip/ansible/module_utils/network/ios/ios.py\", line 117, in get_config\n  File \"/tmp/ansible_MB6pxe/ansible_modlib.zip/ansible/module_utils/connection.py\", lin
> e 149, in __rpc__\nansible.module_utils.connection.ConnectionError: **show running-config all**\r\n                       ^\r\n% Invalid input detected at '^' marker.\r\n\r\nR2#
> \n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

I think this module use "show running-config all" is wrong because in my switch it should be "show running-config full"

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/39342
If default option is enable in that case only
add 'all' or 'full' flag

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by SteveRodrigue** [comment]
Same bug for me.... ios_config is ALWAYS fetching config using "show run all" even if explicitly set "defaults: no" in my playbook.

**Review by rcarrillocruz — APPROVED** [review]

**Comment by ganeshrn** [comment]
Cherry-pick to stable-2.5 https://github.com/ansible/ansible/pull/39608. Fix will be available in 2.5.3

**Comment by myownhost** [comment]
I tried the fix https://github.com/ansible/ansible/pull/39475 in my ansible. Works fine for me, but the problem after installing the patch is that the `defaults: yes` parameter also only execute the command `show running-config` and not `show running-config all`.

**Comment by ganeshrn** [comment]
@myownhost Ah, the module side changes are missed. Please apply PR https://github.com/ansible/ansible/pull/39741 as well and retest.

**Comment by myownhost** [comment]
@ganeshrn test this morning was successfull with the patch https://github.com/ansible/ansible/pull/39741.
Many thanks.

**Comment by ganeshrn** [comment]
@myownhost Thanks for the confirmation.

**Pull request merged**
