### PR TITLE
fixing security group instability

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Fixing nsg test instability

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

azure_rm_securitygroup

##### ANSIBLE VERSION
2.5

##### ADDITIONAL INFORMATION
Test was using same facts variable as azure_rm_networkinterface test and it was causing interference between tests.

### CODE REVIEW

**Comment by zikalino** [comment]
@mattclay i think the problem is fixed now. please merge.

**Comment by mattclay** [comment]
@zikalino The tests still fail when running together:

```
ansible-test integration azure_rm_networkinterface azure_rm_securitygroup --docker -v
```

When I ran this against this PR it failed with the following error:

```
Exception: Error deleting security group testnic001noip - Azure Error: InUseNetworkSecurityGroupCannotBeDeleted
Message: Network security group /subscriptions/6d22db98-3e5f-4ab9-bdf9-2f911a2775f7/resourceGroups/ansible-core-ci-prod-75d39718-1fca-4421-9083-7042e8f8eca2-1/providers/Microsoft.Network/networkSecurityGroups/testnic001noip cannot be deleted because it is in use by the following resources: /subscriptions/6d22db98-3e5f-4ab9-bdf9-2f911a2775f7/resourceGroups/ansible-core-ci-prod-75d39718-1fca-4421-9083-7042e8f8eca2-1/providers/Microsoft.Network/networkInterfaces/testnic001noip.

**Comment by zikalino** [comment]
@mattclay i will try to look deeper into that. i thought my update should fix the problem. it's a kind of puzzling how these w tests could be mixed together. it just looks like they were running in the same resource group....

**Comment by mattclay** [comment]
@zikalino See my explanation here: https://github.com/ansible/ansible/issues/37766#issuecomment-377252735

**Comment by zikalino** [comment]
@mattclay than's for explaining. i was puzzled, as i made an assumption that every test should be guaranteed that it runs in a new resource groups. it may actually explain some other failures too.

sometimes test fails when in the same resource it's::
- creating resource
- deleting resource
- creating resource with the same name
so i have to be very careful about that.

I think right now a good way to solve it is to delete only the security group created in that particular test.

**Pull request closed without merging**
