### PR TITLE
CPM plugcontrol for WTI Power Devices

### PR DESCRIPTION
**Pull request by syncpak**
##### SUMMARY
Added the module cpm_plugcontrol to be able to reboot, turn the power on and off with WTI Power devices.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
cpm_plugcontrol

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (cpm_plugcontrol 75803e3d97) last updated 2018/10/26 09:21:37 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kenp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kenp/ansible/lib/ansible
  executable location = /home/kenp/ansible/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by syncpak** [comment]
Hi @samdoran, I am trying to check-in some new modules but I am getting my check-ins canceled.
All i can see is this error:

irc on_cancel: chat.freenode.net#ansible-notices
  Validating input
  Generating change view
  Generating message
  Generating build details
  Generating triggered by details
  Sending IRC notification
No connection returned for server: close

Is there something that i am missing?

Thanks

**Comment by syncpak** [comment]
Hi @samdoran, sorry, never mind, i needed to rebase the branch, sorry for bugging you.

**Comment by syncpak** [comment]
@actionemb, @vientiane, @mattsene, @dmobergIT please note this is the new pull for the cpm_plugs (now named cpm_plugcontrol) module, there is another module coming to configure the plugs parameters.

**Comment by dmobergIT** [comment]
Got it, will look at it this week. Please also ping my when the Power Plug configuration is also done.

**Comment by actionemb** [comment]
Do I need any BETA code for my CPM to get this new module to work ?

**Comment by syncpak** [comment]
@actionemb for this module (cpm_plugcontrol) no BETA code is needed on your WTI device. That being said, make sure that have the latest release code for your CPM (v.6.56)

**Comment by syncpak** [comment]
Hello @actionemb , @vientiane , @mattsene, @dmobergIT , there is a companion module for the plugs called cpm_plugconfig located here, https://github.com/ansible/ansible/pull/47989

**Comment by mattsene** [comment]
Will this work with your VMR units ?

**Comment by actionemb** [comment]
I noticed that the status of the current state of the plug's state is "as of time of modules is run" Is there a way to get "what the plugs state is going to be?"

**Comment by mmorrisdev** [comment]
Where can i set the boot delay for the plugs?

**Comment by syncpak** [comment]
@mmorrisdev we broke up the control and configuration of the plug, the configuration can be found here. https://github.com/ansible/ansible/pull/47989

**Comment by syncpak** [comment]
shipit

**Comment by mattsene** [comment]
shipit

**Comment by vientiane** [comment]
shipit

**Comment by wtinetworkgear** [comment]
shipit

**Comment by scarshouldofwon** [comment]
shipit

**Pull request merged**
