### PR TITLE
proxmox_kvm: While a VM is beeing created, vm has no name item

### LINKED ISSUE #58194: [proxmox_kvm] Error in get_vmid when called 'too early' after the creation of a VM
##### SUMMARY
For a fraction of second after the creation of a new VM, the VM name is not yet defined in its relative dictionary returned by the proxmoxer when querying the list of VMs (proxmox.cluster.resources.get(type='vm')). 

Accessing to this non existing attribute as an element of a dictionary instead of using the get function on the dictionary raise an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxmox_kvm

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /home/pguermo/Projects/superluminal-pdp/etc/ansible.cfg
  configured module search path = ['/home/pguermo/Projects/superluminal-pdp/library']
  ansible python module location = /home/pguermo/.virtualenvs/superluminal-pdp/lib/python3.5/site-packages/ansible
  executable location = /home/pguermo/.virtualenvs/superluminal-pdp/bin/ansible
  python version = 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
```

##### STEPS TO REPRODUCE
Create several VMs on proxmox in a row. 
```
  proxmox_kvm:
    api_host: "{{ pve_host_fqdn }}"
    api_user: "{{ pve_user }}"
    api_password: "{{ pve_password }}"
    validate_certs: "{{ validate_certs }}"
    node: "{{ pve_node }}"

    name: "{{ ansible_host }}"
    pool: "{{ pool_id }}"
    vmid: "{{ vmid }}"

    description:  "{{ description | default(vm.description) }}"
    net:          "{{ net         | default(vm.net) }}"

    balloon:  "{{ balloon   | default(vm_defaults.balloon) }}"
    cores:    "{{ cores     | default(vm_defaults.cores) }}"
    ide:      "{{ ide       | default(vm_defaults.ide) }}"
    memory:   "{{ memory    | default(vm_defaults.memory) }}"
    ostype:   "{{ ostype    | default(vm_defaults.ostype) }}"
    scsi:     "{{ scsi      | default(vm_defaults.scsi) }}"

    state: present
  delegate_to: localhost
```

Some VMs will not be created. 

If you add traces in the function get_vmid(proxmox, name) of  ansible/modules/cloud/misc/proxmox_kvm.py, you'll notice that for some new VMs of the list, the dictionary doesn't have a 'name' entry. The `vm['name']` is then failing.

Use instead `vm.get('name')`. It will returns None if there is no name entry in the dictionary and the check `if vm.get('name') == name` can be processed properly.

### PR DESCRIPTION
**Pull request by pguermo**
##### SUMMARY
Fixes #58194

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
proxmox_kvm

### CODE REVIEW

**Comment by xenlo** [comment]
What's the status of this PR?

We are impacted by this one, and apply manually the patch each time is really annoying.

**Comment by xenlo** [comment]
@felixfontein, as discuss on IRC:
- Changelogs fragment has been added, 
- and I confirm that I tested this change.

**Review by felixfontein — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@pguermo @xenlo thanks for fixing and testing this!

I'll create a backport so it should end up in 2.8.x eventually.

**Pull request merged**
