### PR TITLE
parted: Fixed issue #22996

### LINKED ISSUE #22996: [parted] module 'parted' is not idempotent
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
git pull from stable-2.3 branch and 'make rpm'
$ rpm -qa | grep ^ansible
ansible-2.3.0.0-100.git201703241924.58f002d.stable23.el7.centos.noarch

##### OS / ENVIRONMENT

CentOS 7.3 x86_64

##### SUMMARY

First run of parted module is successful.
Second run of parted module is not idempotent, returns "parted: invalid token: primary"
##### STEPS TO REPRODUCE

```
ansible-playbook config-partition.yml -s -K --extra-vars="target=somemachine.domain.tld"
```
Inside a role is the following:
```
# Install parted
- name: Install parted
  yum:
    name: parted
    state: present

# Use entire storage for /dev/sdb1 (default)
- name: NFS parted /dev/sdb
  parted:
    label: gpt
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
  environment:
    PATH: "/usr/bin:/usr/sbin"
  become: yes
```
Returns with a "rc": 1 and "err": "parted: invalid token: primary\n"

}

##### EXPECTED RESULTS

I expected to be able to use the 'parted' module in an idempotent way without trapping "rc: 1" errors.
##### ACTUAL RESULTS

```
Verbose output:
fatal: [somemachine.domain.tld]: FAILED! => {
    "changed": false,
    "err": "parted: invalid token: primary\n",
    "failed": true,
    "invocation": {
        "module_args": {
            "align": "optimal",
            "device": "/dev/sdb",
            "flags": [
                "lvm"
            ],
            "label": "gpt",
            "name": null,
            "number": 1,
            "part_end": "100%",
            "part_start": "0%",
            "part_type": "primary",
            "state": "present",
            "unit": "KiB"
        }
    },
    "msg": "Error while running parted script: parted -s -m -a optimal /dev/sdb -- unit KiB set 1 lvm on set 1 primary off",
    "out": "",
    "rc": 1
}
```

### PR DESCRIPTION
**Pull request by ColOfAbRiX**
##### SUMMARY
Fixes #22996
The logic to check for an existing label was incorrect. Added a check on the name too.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
parted

##### ANSIBLE VERSION
```
ansible 2.4.0 (bugfix/22996 84e6bfcea8) last updated 2017/04/07 16:07:06 (GMT +000)
  config file = 
  configured module search path = [u'/home/fcolonna/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fcolonna/ansible_dev/ansible/lib/ansible
  executable location = /home/fcolonna/ansible_dev/ansible/bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### ADDITIONAL INFORMATION
This is an important bugfix for the module going live on the next release 2.3.0 and should be included in that version too.

The output below uses twice the task provided by @kwohlfahrt on #22996

Before the change both tasks change the partition:
```
TASK [Create partition] ********************************************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "disk": {"dev": "/dev/sdb", "logical_block": 512, "model": "VMware Virtual disk", "physical_block": 512, "size": 5242880.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 5241856.0, "flags": [], "fstype": "", "num": 1, "size": 5240832.0, "unit": "kib"}], "script": "unit KiB mklabel gpt mkpart primary 0% 100% unit KiB name 1 foo"}

TASK [Create partition] ********************************************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "disk": {"dev": "/dev/sdb", "logical_block": 512, "model": "VMware Virtual disk", "physical_block": 512, "size": 5242880.0, "table": "gpt", "unit": "kib"}, "partitions": [], "script": "unit KiB mklabel gpt"}
```

After the change the second task doesn't touch it:
```
TASK [Create partition] ********************************************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "disk": {"dev": "/dev/sdb", "logical_block": 512, "model": "VMware Virtual disk", "physical_block": 512, "size": 5242880.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 5241856.0, "flags": [], "fstype": "", "name": "foo", "num": 1, "size": 5240832.0, "unit": "kib"}], "script": "unit KiB mklabel gpt mkpart primary 0% 100% unit KiB name 1 foo"}

TASK [Create partition] ********************************************************************************************************************************************************************************************************************
ok: [localhost] => {"changed": false, "disk": {"dev": "/dev/sdb", "logical_block": 512, "model": "VMware Virtual disk", "physical_block": 512, "size": 5242880.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 5241856.0, "flags": [], "fstype": "", "name": "foo", "num": 1, "size": 5240832.0, "unit": "kib"}], "script": ""}
```

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
I commented on the issue (#22996) with a further problem, that partitions are not resized if they already exist.

**Comment by ColOfAbRiX** [comment]
I've seen it, thank you, but I haven't got time till after Easter.

**Comment by resmo** [comment]
shipit

**Comment by resmo** [comment]
@kwohlfahrt could you comment on this PR since you reported the issue. See https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md

**Comment by kwohlfahrt** [comment]
@resmo - I was under the impression that ColOfAbRiX was still working on some changes, based on my latest coments. Would it be normal for that to be a new PR then?

**Comment by ColOfAbRiX** [comment]
Yes, there is another issue reported, but I'm not sure if I should include it here?

**Comment by kwohlfahrt** [comment]
In that case, I'm happy that the original issue is resolved by this PR. I don't think I have permission to trigger any ansibot actions, but shipit anyway :)

**Comment by resmo** [comment]
bot_status

**Comment by ColOfAbRiX** [comment]
Not sure what is requested to me for this PR, if anything.

@kwohlfahrt Can you open a separate issue for the size problem? It will make things cleaner.

**Comment by ColOfAbRiX** [comment]
shipit

**Comment by ColOfAbRiX** [comment]
shipit

**Pull request merged**
