### PR TITLE
Add callback binjson.py

### PR DESCRIPTION
**Pull request by rongzeng54**
##### SUMMARY
This callback converts ansible command (ad-hoc) into JSON output to stdout

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
binjson.py

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul 12 2017, 17:32:34) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
```

##### ADDITIONAL INFORMATION
JSON data is easy to handle

```
#before#
$ ansible -m shell -a "hostname" localhost
localhost | SUCCESS | rc=0 >>
testserver

#after#
$ ansible -m shell -a "hostname" localhost
{
    "host": "localhost",
    "msg": "",
    "rc": 0,
    "status": "SUCCESS",
    "stderr": "",
    "stdout": "testserver"
}
```

### CODE REVIEW

**Comment by samdoran** [comment]
There is already a JSON callback plugin that can be used to output in JSON. To enable callbacks when running `/usr/bin/ansible`, set [`ANSIBLE_LOAD_CALLBACK_PLUGINS=1`](http://docs.ansible.com/ansible/latest/config.html#envvar-ANSIBLE_LOAD_CALLBACK_PLUGINS)

**Comment by samdoran** [comment]
One difference between your PR and the existing JSON callback plugin is the timing of the output. The existing callback waits until the end, then dumps the entire output at once. This is what most JSON consumers expect.

If you have a use case for outputting the JSON in real time, you could submit a PR adding this feature to the existing JSON callback.

**Comment by rongzeng54** [comment]
HI @samdoran 
The existing JSON callback plugin(https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/json.py) is just for playbook but not ansible.
When i listen v2_runner_on_* event for playbook, seems i cannot listen it for ansible on the same time because there is not event like v2_playbook_on_stats. 
So i add one new callback just for ansible but not playbook.

**Comment by sivel** [comment]
@rongzeng54 if you invoke `ansible` using `ANSIBLE_LOAD_CALLBACK_PLUGINS=1`, you can use the existing `json` callback:

```
$ ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_STDOUT_CALLBACK=json ansible localhost -m ping
{
    "custom_stats": {},
    "plays": [
        {
            "play": {
                "id": "784f43a0-97cc-41c7-bddb-000000000007",
                "name": "Ansible Ad-Hoc"
            },
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false,
                            "_ansible_parsed": true,
                            "action": "ping",
                            "changed": false,
                            "invocation": {
                                "module_args": {
                                    "data": "pong"
                                }
                            },
                            "ping": "pong"
                        }
                    },
                    "task": {
                        "id": "784f43a0-97cc-41c7-bddb-000000000009",
                        "name": "ping"
                    }
                }
            ]
        }
    ],
    "stats": {
        "localhost": {
            "changed": 0,
            "failures": 0,
            "ok": 1,
            "skipped": 0,
            "unreachable": 0
        }
    }
}
```

**Comment by rongzeng54** [comment]
@sivel 
maybe my version is wrong?

[zr@xxx jumper]$ ansible --version
ansible 2.4.1.0
  config file = /home/zr/jumper/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jul 20 2017, 16:11:29) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
[zr@xxx jumper]$ ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_STDOUT_CALLBACK=json ansible localhost -m ping
[zr@xxx jumper]$ ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_STDOUT_CALLBACK=minimal ansible localhost -m ping
localhost | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}

**Comment by sivel** [comment]
This requires the newly released ansible 2.5.0.

**Pull request closed without merging**
