### PR TITLE
add apt_key module

### PR DESCRIPTION
**Pull request by jvantuyl**
Pretty straightforward.  Give it a URL with an exported GPG key for signing an
Apt repository.  It downloads it and will install it using apt-key.  It's even
smart enough to tell if it's already there (i.e. actually tells you if it
changed or not).  Shouldn't require anything more than any Debian already has (gpg, grep, apt itself).

### CODE REVIEW

**Comment by mpdehaan** [comment]
Seems like you could also do this with get_url and notifying a command, so I'm not sure this belongs in core, but if you send me an update for the docs RST file I think we can easily link to it for 'contrib' purposes.

Thoughts from others?

**Comment by jvantuyl** [comment]
Well, you can't really use apt-repository without it (at least, if there are signing keys).  I figured it was necessary to really round out the apt functionality.

The real magic is in the "check and see if we already have this key id" and "check to see if the key we downloaded was really the id we were looking for".  The former is an optimization that speeds up my deploys / prevents me from hammering the poor upstream webservers (and creating all of the joy of having a few thousand web requests that just aren't necessary, slow things down, and can fail causing spurious badness).  The latter is a pretty important way to protect against getting man-in-the-middled for my repo key (which we take moderately seriously here).

Also, perhaps it's silly, but commands don't ever seem to show "ok", they always show "changed".  I actually alert when a deploy never seems to get a solid deploy (i.e. all steps didn't make any changes).  This makes it so that there is always some built-in churn in my deploys, which really makes the stats much less useful.  In fact, it would be really nice if there was a way that command could be told a way to map exit-codes to ok/changed/failed.  Ditto for raw (which always lists no changes) and the other commands based on command.

Then there's brevity / clarity.  It doesn't really make sense (to me, at least) to have three or four entries in the file when I could have one that concretely says what's being done.  Consider applying the same standard to apt-repository.  It's just a trivial file copy to /etc/apt/sources.list.d these days... why have it at all?  I contend that it's critical because it's vastly better to have a file that is filled with a description of what it's doing than one filled with a bunch of confusing details about how it's being done.  I'd much rather have more modules in core that implement a clear function idempotently than to hold them out based on "it's possible using other commands"--especially something as central as package management.

**Comment by jvantuyl** [comment]
As far as "update for the docs RST file", what exactly do I need to do?  Was that the formatting fix I just pushed for the DOCUMENTATION string (which was broken by angry tab characters)?

I have generated the rst with the module_formatter.py but I can't tell where to check it in.  Where would you like it?

**Comment by mpdehaan** [comment]
What I mean is we could list in 'these are useful modules' but maybe not put it in core, since as I mentioned you could just use get_url with this plus the command module.   I am currently struggling with whether every time you run two commands together that warrants a new module or not... it seems to be a slippery slope to have a lot for all of those use cases, on one hand nice to have them, makes stuff readable, but more to maintain, more modules to skim over and understand... so I'm inclined to just link to it?

Others have thoughts?

**Comment by sfromm** [comment]
I'm not a debian user, so please let me know if I'm off base.  Is the key associated with an apt repository?  If so, would this better added to the _apt_repository_ module?  That way, an apt repository and associated key could be set up in one task and from one module.

**Comment by jvantuyl** [comment]
It's a little involved.  These keys are used to sign the "release" file which determines which packages are considered "safe" when you do an "apt-get install".  Over time, a repository may have many keys (as they expire or are revoked). During transitions, you may need both keys, too.  A key can also be used to sign multiple repositories.  It's not really a clean mapping from keys to repositories in either direction.

It doesn't really make sense to put this into _apt_repository_, I think, as there'd just end up being a separate invocation in most cases and it really would only serve to make both modules more complicated.

Details on secure apt [here](http://man.he.net/man8/apt-secure).

**Comment by mpdehaan** [comment]
I was also thinking it seemed to make more sense as an argument to the apt repository module, but your explanation makes sense to me.

**Comment by jvantuyl** [comment]
I could integrate it there if you'd prefer.  If so, I'd think the commandline would be something like:

apt_repository key=45ABCDEF state=absent

I suppose if you combined key and repo it would imply that both were present or absent?  Seems a bit ambiguous IMHO, which was why I had broken it out.

If you'd like me to put apt_key into apt_repository instead, I can do that.  Probably wouldn't be too much work.  In general, I prefer lots of tiny commands that can be aggregated.  Though being able to recurse through into play instead of just one-level includes is probably necessary to make that really useful.

**Comment by jvantuyl** [comment]
Any direction on this?  What do I have to do to get this merged?

As a user, this is critical for anybody that has to work against a Debian image more than about a year out of date (as it must be done to make apt-get update work since they rotate their keys regularly).  As such, I see it as core apt functionality.  There is not a Debian or Ubuntu system that I deploy that won't need this module.

**Comment by jvantuyl** [comment]
Rebased to stay current...

**Comment by joshskinner-wf** [comment]
i think this would be a wonderful addition to core.  "rounds out apt support" is the "key"

+1

**Comment by jvantuyl** [comment]
Rebased to stay current again.

**Comment by dhozac** [comment]
This uses fingerprint when it means key ID. I think it should support state=absent to remove revoked keys. `match.groups()[0]` is a rather odd form of `match.group(1)`. get_key_fingerprint uses module without having it available. This probably should use module.run_command for better error messages. I'm not sure it makes sense to limit it to one key. I'm not familiar with Debian policies, but you'd typically list several keys in one file.

**Comment by jvantuyl** [comment]
Typically Debian has one key per repository, so one key per is usually okay.  How would you match up the urls to keys?  Would you insist that each URL contain all of the keys (unusual in standard usage)?  Would you have each URL in some sort of list correspond to a key id in some other list?  For that use-case, I'd probably use with_item anyways, so... whatever works.

I fixed the terminology to use key_id everywhere.  Good eyes on that one.

Revoking keys with state=absent is a great idea.  Implemented.

Is module.run_command documented anywhere?  Wasn't aware of it.

match.group(1) is fine, changed.  I had been changing things around when debugging the regex and left it where it worked.

In addition to the above, I've made error handling much more robust, added code to ensure that the appropriate binaries are available in the PATH, and written tests.

**Comment by mpdehaan** [comment]
Merged, @jvantuyl may I suggest you post about this on the list and see if some folks would like to use/test?

Thanks!

**Comment by abourget** [comment]
How do I get a key from an Ubuntu PPA ?

I'm looking at this page:

```
https://launchpad.net/~vbulax/+archive/collectd5
```

and I want to add his key.  Which URL do I put up in apt_key ?

That might prove useful in the docs too :)

thanks

**Comment by jvantuyl** [comment]
Hmmm, haven't tested it, but I would expect it to look something like:

apt_key id=013B9839 url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xC1F5057D013B9839 state=present

I'm not sure if gpg will pull the key out of the webpage text or not, so you may need to download it and rehost it somewhere else (and use that URL).

**Comment by mpdehaan** [comment]
In which case we should make it work with local filesystem paths also :)

**Comment by jvantuyl** [comment]
Oh, that's a really good idea.

**Comment by abourget** [comment]
Yeah that URL wouldn't work.. as it's an HTML page with a <pre> tag that
shows the ASCII key..

But there's the apt-key program that deals with that.. why not use that on
the other side.. it's conveniently similar to the name of the module, isn't
it ?  And using apt-key, you can specify the keyserver and the ID to get
the correct key.

Alexandre

**Comment by jvantuyl** [comment]
Actually, I tested it and GPG does work.  I figured this might work because, I believe, apt-key uses gpg internally anyways.  Since GPG originally was designed to extract such things from e-mails, it's remarkably forgiving about the wrapping.

curl 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xC1F5057D013B9839' | gpg --import --dry-run

KeyServer support is a great idea (as is local files), but this actually should work as is.  Does this not work?  It works when I run a manual test, but I'm just doing a contrived example.

**Pull request merged**
