### PR TITLE
New release v2.16.6

### PR DESCRIPTION
**Pull request by nitzmahone**
##### SUMMARY

New release v2.16.6

##### ISSUE TYPE

Feature Pull Request

### CODE REVIEW

**Comment by felixfontein** [comment]
Is there a reason there was no release candidate for 2.16.6 this week, but instead the real release? The 2.16.5 release was only three weeks ago.

**Comment by samccann** [comment]
Also folks pointed out the download is ansible_core-blalba and not ansible-core-blabla (aka underscore vs hyphen) - Is this an intentional change?

**Comment by sivel** [comment]
> Is there a reason there was no release candidate for 2.16.6 this week, but instead the real release? The 2.16.5 release was only three weeks ago.

It was accidental, and we've just decided to let it roll as is, we aren't going to yank the release, or replace it with .7rc1.



> Also folks pointed out the download is ansible_core-blalba and not ansible-core-blabla (aka underscore vs hyphen) - Is this an intentional change?

This is a change in `setuptools` that was released 3 or 4 days ago. https://setuptools.pypa.io/en/stable/history.html#v69-3-0

I'm not sure we've made a decision specifically which way we are going in regards to the name change.  Likely we keep it and keep rolling.

**Comment by felixfontein** [comment]
@sivel will the next 2.16.x release be in five weeks then (to go back to the original schedule), or will 2.16.7 follow in 4 weeks (and its rc1 in 3 weeks)?

**Comment by sivel** [comment]
> will the next 2.16.x release be in five weeks then (to go back to the original schedule)

Yes, there will be a 5 week gap until the next 2.16 GA.

**Pull request merged**
