### PR TITLE
[backport][eos] : Add "mode" to l2_interfaces

### PR DESCRIPTION
**Pull request by GomathiselviS**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
l2_interfaces.py

### CODE REVIEW

**Comment by sc68cal** [comment]
This PR probably has the wrong target for the base branch, hence the exposion of commits

**Review by sc68cal — CHANGES_REQUESTED** [review]
wrong base branch for merge

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
closing the PR because of numerous conflicts.

**Pull request closed without merging**
