### PR TITLE
WIP: testing MM backport

### PR DESCRIPTION
**Pull request by rambleraptor**
##### SUMMARY
WIP: Testing MM ability to merge with Ansible

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`gcp_*`

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by abadger** [comment]
What is the story behind this backport request?  from the test failures, it appears to include new features so it wouldn't be accepted as a backport.  Even if the tests were passing, I'm not sure that it would be doable to review this change for suitability as a backport given that it is so big and touches so many modules.

It also lacks changelog entries to tell users which bugs are being fixed by it.

**Comment by gundalow** [comment]
Happy to chat with you about this, `gundalow@redhat.com`

**Comment by rambleraptor** [comment]
I was just trying something out and wanted to see the CI results. Feel free
to delete the PR!

**Comment by abadger** [comment]
Cool.  Thanks :-)

**Pull request closed without merging**
