### PR TITLE
systemd: fix global scope

### PR DESCRIPTION
**Pull request by tchernomax**
##### SUMMARY

major rewrite of systemd.py

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

systemd

### CODE REVIEW

**Comment by tchernomax** [comment]
ping @bcoca I fixed the checks

**Comment by bcoca** [comment]
I'm not sure this change is correct, nor what it is trying to solve, @tchernomax can you give examples?

**Comment by tchernomax** [comment]
@bcoca 

# what I am trying to solve

Without this fix:
```
max@mde-oxalide % ansible localhost -m systemd -a 'name=dbus-broker.service enabled=true scope=global' -b
localhost | FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/systemctl --global",
    "msg": "Failed to connect to bus: No such file or directory",
    "rc": 1,
    "stderr": "Failed to connect to bus: No such file or directory\n",
    "stderr_lines": [
        "Failed to connect to bus: No such file or directory"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

with this fix:
```
max@mde-oxalide % ansible localhost -m systemd -a 'name=dbus-broker.service enabled=true scope=global' -b
localhost | SUCCESS => {
    "changed": false,
    "enabled": true,
    "name": "dbus-broker.service",
    "status": {}
}
```

# why it fail without this fix

```
    if unit:
        …

        # check service data, cannot error out on rc as it changes across versions, assume not found
        (rc, out, err) = module.run_command("%s show '%s'" % (systemctl, unit))

        if request_was_ignored(out) or request_was_ignored(err):
            # fallback list-unit-files as show does not work on some systems (chroot)
            # not used as primary as it skips some services (like those using init.d) and requires .service/etc notation
            (rc, out, err) = module.run_command("%s list-unit-files '%s'" % (systemctl, unit))
            if rc == 0:
                is_systemd = True

        elif rc == 0:
            # load return of systemctl show into dictionary for easy access and return
            if out:
                result['status'] = parse_systemctl_show(to_native(out).split('\n'))

                is_systemd = 'LoadState' in result['status'] and result['status']['LoadState'] != 'not-found'

                is_masked = 'LoadState' in result['status'] and result['status']['LoadState'] == 'masked'

                # Check for loading error
                if is_systemd and not is_masked and 'LoadError' in result['status']:
                    module.fail_json(msg="Error loading unit file '%s': %s" % (unit, result['status']['LoadError']))
        else:
            # Check for systemctl command
            module.run_command(systemctl, check_rc=True)
        …
```

The module try to run `systemctl --global show …service`, which is not possible.
`systemctl show …` intend to show the status/properties of a unit.
By default `systemctl show X` == `systemctl --system show X`, it ask to the system systemd manager the status of it's unit X (system unit, not user unit).
`systemctl --user show X` ask the current user systemd manager the status of it's unit X (user unit, not system unit).

The `--global` systemctl parameter is only valid for the `enable` and `disable` subcommand ; man systemctl:
> --global
> When used with enable and disable, operate on the global user configuration directory, thus enabling or disabling a unit file globally for all future logins of all users.

So `systemctl --global show …` fail.

# what I did

rewrite the faulty portion of code to:
* if possible we use `systemctl show`
* else we use `systemctl list-unit-files`
* if it doesn't work either check if systemctl exist

# what may break (what to check)

AFAIK we can't use `systemctl show` only when `--global` and when the module is run in chroot, as this comment suggest:
> # fallback list-unit-files as show does not work on some systems (chroot)

If there is other condition when we can't use `systemctl show` my fix should be changed

**Comment by bcoca** [comment]
I see the issue, but I don't think this is the correct solution, handling the usage of `--<scope>` correctly seems the better fix

**Comment by tchernomax** [comment]
@bcoca Can you explain (like pseudo code) what you mean by:
> handling the usage of --<scope> correctly

**Comment by bcoca** [comment]
@tchernomax refresh ticket, i updated my post

**Pull request closed without merging**
