### PR TITLE
New module: Add module for Packet API IP address assignment (cloud/packet/packet_ip_address)

### PR DESCRIPTION
**Pull request by t0mk**
##### SUMMARY

New module for assigning reserved IP addresses to devices in the Packet Host.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME

modules/cloud/packet/packet_ip_address.py

##### ANSIBLE VERSION

```
> ansible --version
ansible 2.4.0 (packet-ip-address 4f18d54dfc) last updated 2017/03/30 16:40:11 (GMT +300)
  config file =
  configured module search path = [u'/home/tomk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

Using the module in this PR (`packet_ip_address.py`) is easier, if we can ensure that the device, to which an IP address should be assigned, is in the `active` state. I improve handling of the `active` state of the packet_device module in https://github.com/ansible/ansible/pull/23127. Although there is no dependency between the packet_device and packet_ip_address modules, it would be consistent for the users of the packet modules, if https://github.com/ansible/ansible/pull/23127 is merged before this PR.

### CODE REVIEW

**Comment by t0mk** [comment]
Hey, could the maintainers please take a look at this? 

It's a module for handling IP address resource in the Packet host.

I will monitor the Packet PRs to Ansible, and I can do improvements if the maintainers request any.

**Comment by t0mk** [comment]
ready_for_review

**Comment by nurfet-becirevic** [comment]
shipit

**Comment by t0mk** [comment]
looks good

**Comment by t0mk** [comment]
shipit

**Comment by baldwinSPC** [comment]
shipit

**Pull request merged**
