### PR TITLE
Added merge_type to kubevirt_template module

### LINKED ISSUE #54215: kubevirt_template module is not passing merge_type
##### SUMMARY

kubevirt_template module is not passing the merge_type to the parent class, which makes it fail 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubevirt_template
##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
running the module example fails with key error of merge_type
```

##### ACTUAL RESULTS

```paste below
Traceback
The full traceback is:
Traceback (most recent call last):
  File "/home/vparekh/.ansible/tmp/ansible-tmp-1553237982.1-20313872141039/AnsiballZ_kubevirt_template.py", line 114, in <module>
    _ansiballz_main()
  File "/home/vparekh/.ansible/tmp/ansible-tmp-1553237982.1-20313872141039/AnsiballZ_kubevirt_template.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vparekh/.ansible/tmp/ansible-tmp-1553237982.1-20313872141039/AnsiballZ_kubevirt_template.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_kubevirt_template_payload_M6iyQQ/__main__.py", line 359, in <module>
  File "/tmp/ansible_kubevirt_template_payload_M6iyQQ/__main__.py", line 351, in main
  File "/tmp/ansible_kubevirt_template_payload_M6iyQQ/ansible_kubevirt_template_payload.zip/ansible/module_utils/kubevirt.py", line 128, in __init__
  File "/tmp/ansible_kubevirt_template_payload_M6iyQQ/ansible_kubevirt_template_payload.zip/ansible/module_utils/k8s/raw.py", line 115, in __init__
KeyError: 'merge_type'

```

### PR DESCRIPTION
**Pull request by vatsalparekh**
##### SUMMARY

Fixes #54215
##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by machacekondra** [comment]
Thanks a lot. shipit

**Comment by machacekondra** [comment]
@vatsalparekh please fix the syntax issues.

**Comment by Akasurde** [comment]
@vatsalparekh Could you please write a unit test for kubevirt_template module ? Thanks.

**Comment by machacekondra** [comment]
@Akasurde we have unit tests here: https://github.com/ansible/ansible/pull/52558

**Comment by machacekondra** [comment]
shipit

**Comment by Akasurde** [comment]
shipit

**Comment by pkliczewski** [comment]
:+1:

**Pull request merged**
