### PR TITLE
Check rc instead of parsing for errors.  

### PR DESCRIPTION
**Pull request by apenney**
This now catches the case where the remote branch has been deleted and you're still trying to pull against it.

### CODE REVIEW

**Comment by sfromm** [comment]
@apenney Can you add a if rc != 0 blurb after line 158?  Also, I think lines 226 and 226 (previously 224 and 225) become unnecessary.

**Comment by apenney** [comment]
Updated again, can you take another look @sfromm?

**Comment by sfromm** [comment]
Looks fine to me.

**Comment by mpdehaan** [comment]
I like delegating code reviews :)

Thanks @apenney and @sfromm

**Pull request merged**
