### PR TITLE
Added support for windows password retrieving

### PR DESCRIPTION
**Pull request by hryamzik**
##### SUMMARY

Added support for windows password retrieving

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ec2 inventory script

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

### CODE REVIEW

**Comment by hryamzik** [comment]
> `2018-01-25 17:47:09 test/utils/shippable/shippable.sh: line 104: test/utils/shippable/other.sh: No such file or directory`

That doesn't look related to this PR.

**Comment by mattclay** [comment]
I've restarted CI for this PR. The error was due to recent infrastructure changes.

**Comment by hryamzik** [comment]
@ryansb is there anything preventing merge?

**Comment by hryamzik** [comment]
CC @gundalow

**Comment by s-hertel** [comment]
Hi @hryamzik. Since adding the inventory plugins in 2.4 we aren't working on adding new features to the contrib scripts. Using boto3 fixes issues the inventory script had, and the inventory plugin infrastructure improves caching as well as more flexibly creating groups and hostvars. If you need this feature, please submit a pull request modifying https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/aws_ec2.py. Feel free to reach out if you have questions.

**Pull request closed without merging**
