### PR TITLE
choosing cowsay file at random by each task.

### PR DESCRIPTION
**Pull request by yteraoka**
Current "ANSIBLE_COW_SELECTION=random" is only chosen at random only once at the time of initialization. 
This Pull Request choose it on each task.

### CODE REVIEW

**Comment by bcoca** [comment]
+10 "moos" to this patch

**Comment by srgvg** [comment]
MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO MOOO MOO MOOOO MOOO MOO MOOO MOOO

**Comment by cchurch** [comment]
:cow:

**Comment by mpdehaan** [comment]
no further pull requests will be taken in for the random cow, due to the possibliity of selecting bad cows, due to the allowance of cowsay to pick NSFW cows.   

We really should just remove random.

That all being said, we have tons of pull requests in the backlog and spending a second on this is disrespecting all of those other tickets.

**Pull request closed without merging**
