### PR TITLE
Don't use deprecated syntax for "except"

### PR DESCRIPTION
**Pull request by lw**
http://docs.python.org/3.3/howto/pyporting.html#capturing-the-currently-raised-exception

And remove trailing whitespace.

### CODE REVIEW

**Comment by sivel** [comment]
This change would break python 2.4 and 2.5 compatibility which is a requirement.

Additionally from what I have heard, python 3 support is not currently on the roadmap.

**Comment by lw** [comment]
I see. I use Arch Linux which has Python 3 by default, and I was therefore getting a syntax error on these. If only Python 2 is supported, can you put `python2` explictly in all shebangs, to avoid using the system default?

**Comment by sivel** [comment]
The shebang actually doesn't matter due to how the files are invoked, see http://www.ansibleworks.com/docs/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

**Comment by mpdehaan** [comment]
Ansible does support python2 (reasons: Red Hat and Ubuntu use python 2 by default and are the lion's share of our user base), but not all distros have python2 as a symlink.

Feel free to modify your /usr/bin scripts if you so desire.

**Comment by lw** [comment]
That FAQ explains how to handle Python 2 on the server. I was getting these errors on the server. How do I fix them?

**Pull request closed without merging**
