### PR TITLE
Add Cloud Init variables for Proxmox_KVM module

### PR DESCRIPTION
**Pull request by nuttybrewer**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by nuttybrewer** [comment]
Just found similar pull request [here](https://github.com/ansible/ansible/pull/40663). Let's merge these together and get the module complete. This is stopping us from adopting ProxMox in our AWX/Tower implementation.

**Comment by lukasmrtvy** [comment]
Very crucial would be adding a support to cloud-init option `cicustom` ( https://pve.proxmox.com/wiki/Cloud-Init_Support ) which will provide universal meta tag for rest of official cloud-init options.

These are PRs for (partial)cloud-init support:
https://github.com/ansible/ansible/pull/54108 @nuttybrewer
https://github.com/ansible/ansible/pull/40663 @FireDrunk
https://github.com/ansible/ansible/pull/42571 @morph027 

Some kind of reconciliation would be a great ..

**Comment by FireDrunk** [comment]
I don't think 'cicustom' is that important. It's useful if you don't use Ansible to configure the VM. Then you can inject something alongside the VM to make it do something upon startup (during Cloud-Init initialization).
When you are using ansible, you just need the IP of the machine and connect to it with your playbooks, and configure the machine.

From my perspective the really important stuff are the ciuser, sshkeys and the network stuff that makes the VM either use DHCP, or a static IP which we can use in Ansible to connect to the newly created VM.

**Comment by morph027** [comment]
I think so too. #40663 and #42571 are basically the same, so we can :game_die: which one to pick ;)

There were also mentions and comments from @helldorado inside these two.

**Comment by lukasmrtvy** [comment]
@FireDrunk agree, but if You are spinning VM without openssh-server package  (hypothetically) , then `cicustom` is a way how to install package and then You can connect with Ansible for example.

**Comment by FireDrunk** [comment]
> 
> 
> @FireDrunk agree, but if You are spinning VM without openssh-server package (hypothetically) , then `cicustom` is a way how to install package and then You can connect with Ansible for example.

Good point, didn't think of that! I'm fine on working on to merge all existing PR's to 1 'good' one, but it's been a bit quiet from all ends of this PR. Maybe @helldorado can enlighten us? :)

**Comment by DaveMcBrave** [comment]
What is the status on this one? I want to spin up Clones with Cloudinit. It would be highly appreciated.

**Comment by nazco** [comment]
Would be really great to hear something on this issue.

**Comment by lukasmrtvy** [comment]
There is also needed to suport Resize API endpoint, but there are a lot of other things that needs to be implemented:

Use case:
- Create cloud-init image ( Proxmox: not possible with API yet )
- Clone image 
- Config VM ( Proxmox:  its not idempotent, every POST to config endpoint will change mac address on VM, this will break cloud-init, also ciuser has will be different, even with a same value) 
- Resize scsi0 disk (root partition) from default cloud image ( Proxmox:  Resize API endpoint does not support async mode, you can use some pause workaround, but its ugly hack for now )

Cloud-init is not ready on proxmox yet, trust me... oVirt is far more better in this... 
Better to stick with PXE provisioning...

**Comment by helldorado** [comment]
Hi @lukasmrtvy  I also had the problem of resize with terraform. I made a local patch and everything is OK now. It should solve the issue of resizing via ansible as well. 

Cf => https://forum.proxmox.com/threads/resize-api-endpoint-put-async.56657/post-265524

**Comment by timansky** [comment]
Is there any progress on this issue?

**Comment by lunarthegrey** [comment]
Would really like to see this get merged. Guess it needs a rebase @nuttybrewer. Not sure what the `needs_revision` label is for.

**Comment by JuddTracy-DAS** [comment]
I would like to see this get merged soon too.  My guess is the needs_revision is since the previous patch said it was first included in 2.8 that those need to be updated to the next release version.

**Comment by laxmanpradhan** [comment]
also very interested in this issue, hoping it gets merged soon

**Comment by alebeta90** [comment]
Hi, I tested this version of the module and there is an issue when trying to do linked clone. Because it should not define the Format option

**Comment by mxkle** [comment]
Tried to test this but currently getting the following error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "authorization on proxmox cluster failed with exception: could not convert string to float: '6.1-7'"}
```
Need to fix my local test env first. Did someone else had more luck by now? Would really like to use this feature.

**Comment by morph027** [comment]
Are your python modules up to date?

proxmoxer 1.0.4?
ansible 2.9.2 (fixed in https://github.com/ansible/ansible/commit/955cebdd0405f1d90a6b8a43767dbbb0d560ec4f)

**Comment by CJCShadowsan** [comment]
So...

...This seems to be the winner of the cloud-init variables for proxmox_kvm hunger games - so what gives?

Is this going to be merged in?

**Comment by nemmeviu** [comment]
+1
Please add the proxmox_kvm cloud_init support

**Comment by morph027** [comment]
I'm pretty sure ansibot will walk into the bar and let us know we need to migrate this pr to https://github.com/ansible-collections/community.general ...

@nuttybrewer Do you want to migrate the PR or should i take care of porting your changes?

**Comment by nuttybrewer** [comment]
Go ahead and migrate it. Thanks!

**Pull request closed without merging**
