### PR TITLE
Load plugins from playbook basedir and configured directories

### PR DESCRIPTION
**Pull request by dhozac**
This time, with tests passing on CentOS 6 and including support for lookup plugins. Also squashed it down to two commits for basedir and configuration.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks like it no longer loads plugins from site_packages, would would break existing users?

**Comment by mpdehaan** [comment]
BTW, I'm asking if it does both, having the new path is a good thing :)

**Comment by dhozac** [comment]
It does site-packages, the configured paths in the configuration file, and the playbook's basedir.

**Comment by mpdehaan** [comment]
good deal, thanks!

**Pull request merged**
