### PR TITLE
Add command variable in failure message

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/misc/virt.py

##### ANSIBLE VERSION
```
2.4devel
```

### CODE REVIEW

**Comment by gundalow** [comment]
You you have examples of what this was before and after your change?

**Review by nitzmahone — APPROVED** [review]
After looking at the whole file to realize what you were fixing (that basecmd is an erroneous variable name), this looks good. Next time a little clearer description of what you're fixing would help move things along faster. Thanks!

**Comment by Akasurde** [comment]
@gundalow Thanks for review, @nitzmahone I will keep this in my mind for future PRs. Sorry for trouble.

**Comment by Akasurde** [comment]
@nitzmahone @gundalow Thanks for reviews and comments.

**Pull request merged**
