### PR TITLE
Docsite: update links to community docs

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Docsite: update links to community docs

I don't put a space between texts and anchors because in the[ RST doc](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html) it's said:
```
Do not include a space between the last word of the link text and the opening angle bracket for the anchor text.
```
though not sure if it's really important

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/community/communication.rst
docs/docsite/rst/community/maintainers_workflow.rst

### CODE REVIEW

**Comment by Andersson007** [comment]
@samccann could you please take a look if i use the anchors correctly?

**Comment by samccann** [comment]
@Andersson007 The problem here is that the steering committee docs today are only published for Ansible (the package) not core docs. While CI here tests against only core docs.  The file you are editing exists in both core and Ansible docs.

The best option is probably to change the publishing so steering committee docs appear in both places. I can't recall why I chose to put steering committee docs only in Ansible package docs, but I can change that quite easily for them to show up in both.

If you agree, I'll create a PR to do this and once it merges, this CI should pass.

**Comment by Andersson007** [comment]
> @Andersson007 The problem here is that the steering committee docs today are only published for Ansible (the package) not core docs. While CI here tests against only core docs. The file you are editing exists in both core and Ansible docs.
> 
> The best option is probably to change the publishing so steering committee docs appear in both places. I can't recall why I chose to put steering committee docs only in Ansible package docs, but I can change that quite easily for them to show up in both.
> 
> If you agree, I'll create a PR to do this and once it merges, this CI should pass.

@samccann i've no objections, so please do it:) Thanks!

**Comment by samccann** [comment]
@Andersson007 ok we are stuck between a rock and a hardplace here. If I add the steering committee docs to core (to fix the CI problems here) then another CI problem pops up because one of the steering committee docs has a ref to collections contribution docs that also don't exist on core docs.

So the base question - should steering committee docs appear on the core docsite? If so, I'll add them and then change the failing :ref: to a hard-coded URL.  If not, then I'll just close this PR and keep the hard-coded URL as that is the only way it will work between docsites right now.

**Comment by Andersson007** [comment]
@samccann the main goal of the PR is to update the link to the review checklist.
I think the Community Steering committee is not about core.
I'm OK with hardcoded links, so i reverted the part of the changes that caused sanity issues.
So I think we can merge it now, PTAL

**Review by samccann — APPROVED** [review]

**Comment by Andersson007** [comment]
@samccann thanks for reviewing and merging!

**Pull request merged**
