### PR TITLE
Allow parameterized playbook includes to define complex variables

### PR DESCRIPTION
**Pull request by dhozac**
To be used like:

```
- include: playbook.yml
  vars:
    mylistvar:
    - item1
    - item2
```

### CODE REVIEW

**Comment by francisbesset** [comment]
:+1:

**Comment by mpdehaan** [comment]
This part:

```
 if len(play.keys()) <= 2:
     141    
+                if len(play.keys()) <= 3:
```

It's unclear what play.keys() is meant to do, and probably deserves some kind of comment or code cleanup.  In any event, just looking at the diff it is not evident why it's bumping from 2 to 3, or whether we break something by doing so.

**Comment by dhozac** [comment]
I think it should just go away. It was there originally to keep includes as single element dicts, but changed to 2 to allow for with_*... I can replace it with an actual check instead.

**Comment by dhozac** [comment]
... check added.

**Comment by mpdehaan** [comment]
yep, agreed on it going away.

This works for me.

**Comment by francisbesset** [comment]
Thank you very much!

ozEu9

**Pull request merged**
