### PR TITLE
Fixes #20196 broken pipe when special chars in mysql password

### LINKED ISSUE #20196: [Bug / Regression] mysql_db import fail to decompress dumps
_From @bmalynovytch on June 2, 2016 15:43_

##### ISSUE TYPE

Bug Report (regression)
##### COMPONENT NAME

mysql_db (import)
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/benjamin/xxxxxxx/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
forks=500
pipelining=True
retry_files_enabled = False

gathering = smart
fact_caching = jsonfile
fact_caching_connection = ./.tmp/ansible
fact_caching_timeout = 3600

[ssh_connection]
control_path = /tmp/ansible-ssh-%%h-%%p-%%r
ssh_args = -o ControlMaster=auto -o ControlPersist=30m
```
##### OS / ENVIRONMENT

Deployment OS: Mac OS X 10.11.5, python v2.7.11 with pyenv/virtualenv
Destination OS: ubuntu jessie/sid
##### SUMMARY

Using `mysql_db` to import Gzipped or Bzipped SQL dumps used to work like a charm with `ansible 2.0.2.0`
Now, compressed imports fail with a `broken pipe` error, either if `.gz` or .`bz2`
Strangely, this does not happen on a small (compressed) file (1.8k gzip compressed, 6k uncompressed)
Maybe related to https://blog.nelhage.com/2010/02/a-very-subtle-bug/
##### STEPS TO REPRODUCE

Try to import a compressed (large enough) SQL dump with mysql_db.
Failure happen with a 3.5MB gzip compressed / 20MB uncompressed dump.

```
- name: Restore database
  mysql_db:
  args:
    name: my_db
    state: import
    target: /path_to_backups/backup-pre-release.sql.bz2
    login_host: "{{ db.host }}"
    login_port: "{{ db.port }}"
    login_user: "{{ db.user }}"
    login_password: "{{ db.passwd }}"
```
##### EXPECTED RESULTS

Import should just work.
##### ACTUAL RESULTS

```
fatal: [xxxxxx]: FAILED! => {"changed": false, "failed": true, 
"msg": 
"bzip2: I/O or other error, bailing out.  Possible reason follows.
 bzip2: Broken pipe
       Input file = /opt/xxxxxx/backup-pre-release.sql.bz2, output file = (stdout)
"}
```

_Copied from original issue: ansible/ansible-modules-core#3835_

### PR DESCRIPTION
**Pull request by rockpunk**
##### SUMMARY

When mysql passwords that include special characters are passed to the mysqldump/mysql binaries, ansible's mysql_db is attempting to quote the password using pipes.quote(). This causes passwords with special characters to be surrounded in single quotes, which are interpreted mysql as part of the password, causing access denied errors.

Specifically: mysql_db was running `cmd = ['mysql',"--password='test1234!'"....]` instead of `cmd = ['mysql','--password=test1234!',...]` (note the extra quotes around the former.)

In an effort to improve the misleading and hard to debug 'broken pipe' errors as well, only returning p1.returncode/p1.stderr1 when _only_ the compression program is in error (for example, target not found, out of memory, etc.). All other cases will return the mysql command's error code and message.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

module/database/mysql/mysql_db.py

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

Steps to reproduce error in devel branch: 

Try to import any compressed database file with login_password='test1234!'. The current 2.4.0.0.devel branch should fail with broken pipe. This branch should succeed. Non compressed targets would also fail with access denied errors, even though the password was indeed correct.

```

```

### CODE REVIEW

**Comment by bmalynovytch** [comment]
Hi @rockpunk, thank you for your contribution.
Could you please rebase your branch in order to get it merged ?

**Comment by rockpunk** [comment]
@bmalynovytch , rebased. please let me know if there are any other issues.

**Comment by bmalynovytch** [comment]
@rockpunk Thank you for your contribution !
Have tested with passwords containing (shell) special chars ? ( `[&><;"'|]` )
I'm afraid there may be a bad regression on that part. 🤔

**Comment by rockpunk** [comment]
hey @bmalynovytch, yes, i have verified that this works with all shell characters. for example all these commands successfully work via subprocess.Popen():

```python
['mysql', '-ss', '-e', 'select 1', '-ufoo_exclaim', '--password=test!']
['mysql', '-ss', '-e', 'select 1', '-ufoo_quote', "--password=test'"]
['mysql', '-ss', '-e', 'select 1', '-ufoo_dblquote', '--password=test"']
['mysql', '-ss', '-e', 'select 1', '-ufoo_dolla', '--password=test$']
['mysql', '-ss', '-e', 'select 1', '-ufoo_lt', '--password=test<']
['mysql', '-ss', '-e', 'select 1', '-ufoo_gt', '--password=test>']
['mysql', '-ss', '-e', 'select 1', '-ufoo_pipe', '--password=test|']
['mysql', '-ss', '-e', 'select 1', '-ufoo_semi', '--password=test;']
['mysql', '-ss', '-e', 'select 1', '-ufoo_and', '--password=test&']
```

**Comment by bmalynovytch** [comment]
> hey @bmalynovytch, yes, i have verified that this works with all shell characters. for example all these commands successfully work via subprocess.Popen():
> 
> ```python
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_exclaim', '--password=test!']
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_quote', "--password=test'"]
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_dblquote', '--password=test"']
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_dolla', '--password=test$']
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_lt', '--password=test<']
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_gt', '--password=test>']
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_pipe', '--password=test|']
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_semi', '--password=test;']
> ['mysql', '-ss', '-e', 'select 1', '-ufoo_and', '--password=test&']
> ```

Great, thanks !
Though, I think some of your tests may be irrelevant as they don't trigger the devil.
For example, you should try adding extra system commands after `;` or env variable name after the `$`, etc ...

**Comment by rockpunk** [comment]
Thanks for the suggestions. FWIW, The above tests also work if you change
the passwords to 'test<special_char>junk'.

**Comment by Andersson007** [comment]
could anyone please check where the bug presented nowadays ?
thanks in advance
needs_info

**Comment by maxim-nazarenko** [comment]
> could anyone please check where the bug presented nowadays ?
> thanks in advance
> needs_info

it is present in freshly installed `ansible 2.9.3` inside Vagrant box (ubuntu/xenial64)

**Pull request closed without merging**
