### PR TITLE
changed get_group to run in O(n*log(n)) instead of O(n^2) by using _grou...

### PR DESCRIPTION
**Pull request by hrld**
...ps_cache_hash

TODO: check if cache needs to be invalidated in more places (someone who knows the code should check for that...)

ansible startup time goes down by 12 seconds with 12k groups in the inventory. Searching in a list is just slow.

See also: https://groups.google.com/forum/#!topic/ansible-devel/YB-6SRvS5MU

### CODE REVIEW

**Comment by amenonsen** [comment]
This looks like an obvious improvement. Perhaps few people have enough groups to benefit from it, but for those who do it must be a dramatic speedup. The change is small and easily rebased to apply to devel. @hrld, do you feel like doing that?

**Comment by amenonsen** [comment]
See also #10034.

**Comment by hrld** [comment]
Currently ansible (from git) with my real inventory eats >500MB RAM and a minute of CPU (ping on one host, output missing...). When there is a v2 version that actually does anything I'll patch it again and update this pull request. It looks like there are some changes in v2 so I should check details with a profiler again.

**Comment by bcoca** [comment]
@hrld if you want this in 2.0, now would be the time to rebase

**Comment by amenonsen** [comment]
Submitted as #12002.

**Comment by abadger** [comment]
#12002 has been merged.  Thanks @hrld and @amenonsen for the work on getting this improvement in!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
