### PR TITLE
fix: Parse docker_service scale parameter to int

### PR DESCRIPTION
**Pull request by danihodovic**
##### SUMMARY

Parses the `scale` parameter to an int. If scale is interpolated with jinja
(e.g when performing arithmetics) it will be a string.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
docker_service

##### ANSIBLE VERSION

```paste below
ansible 2.7.0rc1
  config file = /home/dani/ansible/ansible.cfg
  configured module search path = [u'/home/dani/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dani/.local/lib/python2.7/site-packages/ansible
  executable location = /home/dani/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION

When passing `scale` to the `docker_service` module to start N number of containers
it expects an int. For directly defined values, e.g `5` this works. However for more
complex values, e.g `'{{ (ansible_processor_vcpus - 1) }}'` it doesn't because a string
is passed to the module due to jinja interpolation.

This commit resolves the issue by attempting to parse scale to an int and
failing with an informative error message if the value cannot be parsed.

### CODE REVIEW

**Comment by danihodovic** [comment]
I'm unsure how to prove that this works with tests as I saw no unit test file corresponding to `docker_service`.

Here's an example of the fix running locally:
https://asciinema.org/a/QbMAmQC1zlPAhTbOAysEgWd8G

```
$ \cat docker-compose.yml
---
version: '2.4'
services:
  nginx:
    image: nginx
```

```
$ \cat test.yml
---
- name: Playbook
  hosts: localhost
  vars:
    cpus: '{{ ansible_processor_vcpus - 1 }}'
  tasks:
    - debug: var=ansible_processor_vcpus

    - name: docker service
      docker_service:
        project_src: .
        scale:
          nginx: '{{ cpus }}'
```

**Comment by danihodovic** [comment]
ready_for_review

**Comment by danihodovic** [comment]
bot_status

**Comment by danihodovic** [comment]
ready_for_review

**Comment by danihodovic** [comment]
@chouseknecht any chance you could have a look at this?

**Comment by danihodovic** [comment]
bot_status

**Comment by danihodovic** [comment]
@jborean93 @chouseknecht is there anyone that can review this besides the module maintainer?

**Comment by jborean93** [comment]
The maintainers are the best people to review this as they know the module best. If they aren’t available then maybe we need to find new maintainers. I would go to #ansible-devel on Freenode IRC and see if there is anyone else willing to review it.

Unfortunately I know next to nothing about Docker so I’m not too much help here.

**Comment by felixfontein** [comment]
@jborean93 I think this module (same as some other `docker_*` modules) is essentially unmaintained.

**Comment by jborean93** [comment]
@felixfontein sounds like we need to find another maintainer, is @gundalow aware of this?

**Comment by felixfontein** [comment]
@jborean93 I thought it was kind of common knowledge, somewhat, though I don't know for whom exactly. I'm not sure if someone ever built a list of affected `docker_*` modules.

**Review by felixfontein — APPROVED** [review]
LGTM

**Comment by danihodovic** [comment]
I think you need to issue the ship_it command

**Comment by felixfontein** [comment]
LGTM is an alias of shipit :)

**Comment by felixfontein** [comment]
shipit

(since the last one probably was cleared because of the rebase)

**Comment by felixfontein** [comment]
bot_status

**Comment by danihodovic** [comment]
bot_status

**Comment by felixfontein** [comment]
@danihodovic ansibot seems to be pretty slow for a couple of days now...

@dariko @jwitko @kassiansun @tbouvet Can anyone of you take a look here?

**Review by jwitko — APPROVED** [review]

**Comment by jwitko** [comment]
LGTM

**Comment by felixfontein** [comment]
Awesome! @danihodovic thanks for your work on this! @jwitko thanks for reviewing!

@danihodovic Do you want to create backport PRs (for Ansible 2.6 and 2.7) for this? I can do that, but in case you want to try this yourself... :) Here are some instructions: https://docs.ansible.com/ansible/latest/community/development_process.html#backport-pull-request-process

Also, we forgot to add a changelog for this fix. I guess that's ok for devel, but we should really add something for the backports. You can find an example here: https://github.com/ansible/ansible/blob/devel/changelogs/fragments/46595-docker_container-expected_ports.yml

**Pull request merged**
