### PR TITLE
Correct integration tests for the win_disk_facts module

### LINKED ISSUE #51031: Integration tests for the win_disk_facts are not triggered
##### SUMMARY
I tried to run integration tests for the module win_disk_facts and I realized that tests are not run due to an incorrect evaluation of the precondition.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_disk_facts

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/<user_name>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<folder_path>/ansible/lib/ansible
  executable location = /<folder_path>/Scripts/ansible/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
```

I hate cows!

##### OS / ENVIRONMENT
I tested that using the Vagrant image of Windows Server 2012 R2 jborean93/WindowsServer2012R2 v.0.5

##### STEPS TO REPRODUCE

```yaml
ansible-test windows-integration win_disk_facts -vvv
```

##### EXPECTED RESULTS
The task 'get disk facts on the target' and 'assert disk facts' will be evaluated.

##### ACTUAL RESULTS

```
<OUTPUT_PARTIALLY_OMITTED>

/ TASK [win_disk_facts : check whether storage module is \
\ available (windows 2008 r2 or later)]                  /
 --------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/<folder_path>/ansible/test/integration/targets/win_disk_facts/tasks/main.yml:3
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 2202 TO 127.0.0.1
EXEC (via pipeline wrapper)
changed: [local] => {
    "changed": true, 
    "rc": 0, 
    "stderr": "", 
    "stdout": "", 
    "stdout_lines": []
}
 ______________________________________________________
< TASK [win_disk_facts : get disk facts on the target] >
 ------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/<folder_path>/ansible/test/integration/targets/win_disk_facts/tasks/tests.yml:1
skipping: [local] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
 ___________________________________________
< TASK [win_disk_facts : assert disk facts] >
 -------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/<folder_path>/ansible/test/integration/targets/win_disk_facts/tasks/tests.yml:5
skipping: [local] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}

<OUTPUT_PARTIALLY_OMITTED>

```

### PR DESCRIPTION
**Pull request by it-praktyk**
##### SUMMARY
The pull requests corrects integration tests for the module win_disk_facts.

Fixes #51031 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_disk_facts

##### ADDITIONAL INFORMATION
Due to the bug in the condition tests were not performed. Additionally, assertions were not aligned with the structure returned by the module.

### CODE REVIEW

**Comment by jborean93** [comment]
Before I merge this in it would also be good to add a skip for 2008 and 2008-R2 in the alias file like https://github.com/ansible/ansible/blob/devel/test/integration/targets/win_uri/aliases#L3. We would still need the conditional check that you have right not but this makes ansible-test a bit more efficient when running the integration tests, e.g. it won't spin up a 2008 and 2008 R2 instance if it's not needed.

**Comment by it-praktyk** [comment]
@jborean93, W2K8, W2K8R2 are excluded now.

**Review by jborean93 — APPROVED** [review]
Fantastic thank you @it-praktyk

**Comment by it-praktyk** [comment]
@jborean93, should it be backported to 2.5-2.7?

**Comment by jborean93** [comment]
I believe win_disk_facts was added in 2.5 so yes that would be great.

**Comment by it-praktyk** [comment]
OK, I'll do it soon.

**Pull request merged**
