### PR TITLE
rax* modules improvements

### PR DESCRIPTION
**Pull request by sivel**
- Catch issues with invalid regions
- Ensure we send string only data as meta values in the rax module
- Add public_key/lookup example for rax_keypair
- Clean up import statements

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks like this pull request may need to be rebased.

Also, in the future, I'd recommend moving functions with long argument signatures to use named arguments where possible, as it makes the code easier to trace.   If you can update these, we would appreciate it.

Thanks!

**Comment by sivel** [comment]
Working on this now.

**Comment by sivel** [comment]
I've rebased.  I agree about using named arguments, however I'd like to manage that in a separate pull request.  This will give me more time to test, and a smaller number of changes to test on.

After this pull is merged, I'll begin on that work.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request closed without merging**
