### PR TITLE
Try/finally is a python 2.5 construct, so not working on EL5. Fix #4763

### LINKED ISSUE #4763: accelerate mode python2.4 compliance - (CentOS 5) part 2
Thanks for the fix for Issue #4739, but now I'm getting a different syntax error out of accelerate mode on CentOS 5:

GATHERING FACTS ***************************************************************
fatal: [sc-scm-ansible-stage-p4-master-01.nvidia.com] => Failed to launch the accelerated daemon on sc-scm-ansible-stage-p4-master-01.nvidia.com (reason:   File "/root/.ansible/tmp/ansible-1383284240.36-155321031921927/accelerate", line 336
    finally:
          ^
SyntaxError: invalid syntax
)

I'm running off the tip of the devel branch (currently: d478eaa6a53a)

Thanks!

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by jimi-c** [comment]
I know the fd's should be closed automatically when they go out of scope, however I'd still like to close them explicitly.

**Comment by mscherer** [comment]
Is there any reason ?
If we want to have them closed in all cases, we have to push the code for closing inside the except and outside of the try/except, and I am not sure there is value to be explicit on something that do happen anyway.

**Comment by alanfairless** [comment]
Python will only garbage collect the file object and close the file handle when no references to it remain.  In the case of an exception, the stack trace includes the frame with the local variable containing the file object, so the function will exit with the file still open.  Not all Python implementations use the same garbage collector, and relying on the behavior of the garbage collector is often a cause of subtle bugs.

To be compatible with py2.4, how about something like this?

```
try:
    ...
except Exception:
    fd.close()
    raise
```

**Comment by mpdehaan** [comment]
@alanfairless +1

cc @jimi-c

**Comment by mpdehaan** [comment]
@mscherer can you update this?

Thanks!

**Comment by mscherer** [comment]
pushed a new version.

**Comment by jctanner** [comment]
Tested against an el5 machine, and the exceptions have been resolved. The next problem is that the daemon doesn't actually start, which is due to https://github.com/ansible/ansible/issues/4763#issuecomment-27730406

**Pull request merged**
