### PR TITLE
aci_switch_leaf_selector: Support missing policy_group

### LINKED ISSUE #47668: aci_switch_leaf_selector -> empty parameter "policy_group" results in "None" on ACI-fabric
##### SUMMARY
The parameter "policy_group" is optional for the module aci_switch_leaf_selector what is in principal ok. But when leaving the parameter empty the module will set the value "None" for the parameter. On the ACI fabric then there needs to be a policy named "None" or a target missing failure will happen.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aci_switch_leaf_selector

##### ANSIBLE VERSION
```paste below
╰─ ansible --version
ansible 2.8.0.dev0 (devel 6eb7e2c470) last updated 2018/09/03 08:18:42 (GMT +200)
...
```
I've also tested the latest devel version and the issue still seems to exist.

##### CONFIGURATION
/

##### OS / ENVIRONMENT
ACI Firmware: Version: 3.2(3n)

##### STEPS TO REPRODUCE

```yaml
- name: adding a switch policy leaf profile selector associated Node Block range (w/o policy group)
  aci_switch_leaf_selector:
    host: apic
    username: admin
    password: SomeSecretPassword
    leaf_profile: sw_name
    leaf: leaf_selector_name
    leaf_node_blk: node_blk_name
    from: 1011
    to: 1011
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS
The expected result would be that the parameter "policy_group" is empty so that no policy group will be assigned. 

##### ACTUAL RESULTS
But instead the modules assigns a policy_group named "None".

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This fixes #47668

This should be backported to v2.7, v2.6 and v2.5.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
aci_switch_leaf_selector

##### ANSIBLE VERSION
v2.8

### CODE REVIEW

**Comment by samccann** [comment]
The minor docs change LGTM

**Comment by mrlesmithjr** [comment]
Was this ever back ported to `2.6.x` by chance?

**Comment by dagwieers** [comment]
Nope, that was not allowed in the current backport model.

**Comment by mrlesmithjr** [comment]
Cool deal! Thanks for the follow up!

**Pull request merged**
