### PR TITLE
digital_ocean_domain: fix to allow updating the module param ip between calls

### PR DESCRIPTION
**Pull request by tolland**
##### SUMMARY

If you change the `ip` param of the `digital_ocean_domain` module between invocations, it will fail on the subsequent ones due to not passing the correct record id to the API.

This patch passes the id and allows recreating the default record during the changed process, if required.

To replicate the initial problem create a domain with params `name=somedomain.com` and `ip=x.y.z.1`, and then call the module again to change the `ip` value, e.g. `ip=x.y.z.2` which will result in a a failure.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

digital_ocean_domain

##### STEPS TO REPRODUCE

```yaml
---

- name: digital ocean domain test
  hosts: devhost1

  tasks:

    - block:

      - set_fact:
          domain_to_test: do-example.com

      - name: create digital ocean domain
        local_action:
          module: digital_ocean_domain
          state: present
          name: "{{ domain_to_test }}"
          ip: 8.8.8.8

      - name: update digital ocean domain with different ip
        local_action:
          module: digital_ocean_domain
          state: present
          name: "{{ domain_to_test }}"
          ip: 1.1.1.1

      always:

      - name: delete the test domain
        local_action:
          module: digital_ocean_domain
          state: absent
          name: "{{ domain_to_test }}"


```

##### EXPECTED RESULTS

Expectation is that the domain would be updated by the second invocation of the module, on the same run, or on subsequent runs, if the `ip` is provided by a variable derived from elsewhere.

##### ACTUAL RESULTS

```
TASK [create digital ocean domain] *****************************************************************************************************************

ok: [devhost1 -> localhost] => {
    "changed": false, 
    "domain": {
        "domain": {
            "name": "do-example.com", 
            "ttl": 1800, 
            "zone_file": "$ORIGIN do-example.com.\n$TTL 1800\ndo-example.com. IN SOA ns1.digitalocean.com. hostmaster.do-example.com. 1530092155 10800 3600 604800 1800\ndo-example.com. 1800 IN NS ns1.digitalocean.com.\ndo-example.com. 1800 IN NS ns2.digitalocean.com.\ndo-example.com. 1800 IN NS ns3.digitalocean.com.\ndo-example.com. 1800 IN A 8.8.8.8\n"
        }
    }, 
    "invocation": {
        "module_args": {
            "id": null, 
            "ip": "8.8.8.8", 
            "name": "do-example.com", 
            "oauth_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "timeout": 30, 
            "validate_certs": true
        }
    }
}

TASK [update digital ocean domain with different ip] *******************************************************************************************************************

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ebAVkz/ansible_module_digital_ocean_domain.py", line 199, in main
    core(module)
  File "/tmp/ansible_ebAVkz/ansible_module_digital_ocean_domain.py", line 164, in core
    do_manager.edit_domain_record()
  File "/tmp/ansible_ebAVkz/ansible_module_digital_ocean_domain.py", line 141, in edit_domain_record
    return json['domain_record']
KeyError: 'domain_record'

fatal: [devhost1 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "id": null,
            "ip": "1.1.1.1",
            "name": "do-example.com",
            "oauth_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "timeout": 30,
            "validate_certs": true
        }
    },
    "msg": "'domain_record'"
}

```

##### AFTER FIX

```
TASK [create digital ocean domain] ***************************************************************************************
task path: /home/user/ansible/test-digital_ocean_domain.yml:13
changed: [devhost1 -> localhost] => {
    "changed": true, 
    "domain": {
        "name": "do-example.com", 
        "ttl": null, 
        "zone_file": null
    }
}
TASK [update digital ocean domain with different ip] *********************************************************************
task path: /home/user/ansible/test-digital_ocean_domain.yml:28
changed: [devhost1 -> localhost] => {
    "changed": true, 
    "domain": true
}
TASK [delete the test domain] ********************************************************************************************
task path: /home/user/ansible/test-digital_ocean_domain.yml:46
changed: [devhost1 -> localhost] => {
    "changed": true,
    "event": null
}
META: ran handlers
META: ran handlers

PLAY RECAP ***************************************************************************************************************
devhost1                   : ok=3    changed=3    unreachable=0    failed=0

```

### CODE REVIEW

**Comment by tolland** [comment]
any feedback on this?

**Comment by BondAnthony** [comment]
Hi @tolland sorry for the delay, this PR looks great and tested well. Thank you for the contribution!

shipit

**Review by BondAnthony — APPROVED** [review]

**Comment by BondAnthony** [comment]
bot_status

**Comment by BondAnthony** [comment]
@Akasurde when you have time could you please review this. I'm not sure why the auto merge shipit test failed.

**Comment by Akasurde** [comment]
rebuild_merge

**Comment by BondAnthony** [comment]
Thank you @Akasurde

**Pull request merged**
