### PR TITLE
added tags to ec2_vol no.2

### PR DESCRIPTION
**Pull request by preyk-work**
trying again

### CODE REVIEW

**Comment by preyk-work** [comment]
i hope should be ok now, i had problems with the other pull request https://github.com/ansible/ansible/pull/2483

**Comment by mpdehaan** [comment]
I believe this should use the complex arguments system rather than parsing JSON.

Basically see complex args in the docs for how to pass a hash to the module, and remove the JSON parsing code/

Thanks!

**Comment by mpdehaan** [comment]
also cc @lwade

**Comment by mpdehaan** [comment]
@lwade any comments ?

**Comment by lwade** [comment]
@mpdehaan , yes completely agree but I need to find time to look into it more.  Current downside is that in both ec2 (and thus presumably the ec2_vol module with this patch), specifying tags using ansible (rather than ansible-playbook), breaks the action.

**Comment by mpdehaan** [comment]
Ok, sounds like we cannot merge this then.   Are there problems to also correct in the ec2 module?

**Comment by preyk-work** [comment]
sorry, didnt have much time lately, @lwade did you want to rewrite the whole ec2 to be idempotent anyway?

**Comment by mpdehaan** [comment]
Sounds like this needs more work yet, so closing.

Please submit when ready and coordinate details on the mailing list.

**Comment by lwade** [comment]
@preyk-work sorry for missing this.  Yes, it's on my to-do list.

**Pull request closed without merging**
