### PR TITLE
Add integration tests for grafana_datasource module

### PR DESCRIPTION
**Pull request by rrey**
##### SUMMARY

This patch is adding integration tests for the `grafana_datasource` module.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
grafana_datasource.py

### CODE REVIEW

**Comment by rrey** [comment]
ship_it

**Comment by rrey** [comment]
@seuf can you review this ? Should be trivial I just turned the examples as tests.
I’d like to initiate the Grafana modules test coverage

**Review by seuf — APPROVED** [review]

**Comment by seuf** [comment]
shipit

**Comment by rrey** [comment]
bot_status

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@rrey thanks for adding tests! @seuf thanks for reviewing!

**Pull request merged**
