### PR TITLE
add new net_tools module for fly ADN

### PR DESCRIPTION
**Pull request by andy-pi**
##### SUMMARY

New module Fly allows users to create hostnames, link backends and add rules using Application Delvivery Network Fly's API.

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

fly

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /home/ubuntu/workspace/ansible-roles/env/lib/python3.5/site-packages/ansible
  executable location = /home/ubuntu/workspace/ansible-roles/env/bin/ansible
  python version = 3.5.1 (default, Dec 18 2015, 00:00:00) [GCC 4.8.4]
```

### CODE REVIEW

**Comment by andy-pi** [comment]
For further info please see the article I wrote on the use of this module. This PR is a revised version of the module from my personal repo which the article links to.
[https://fly.io/articles/automating-deployment-using-flys-api-and-ansible-2/](url)

**Comment by goodroot** [comment]
Hello! I'm from fly.io -- this looks great, Andy. 👍

**Comment by andy-pi** [comment]
bot_status

**Comment by andy-pi** [comment]
@akostyuk @alcamie101 @andyhky @briceburg @drcapulet @jpmens @jtyr @mgruener @mpdehaan @nerzhul @ogenstad @ravibhure @romeotheriault
Any chance anyone can help review this new module? Or give some advice if it needs reworking?

**Comment by andy-pi** [comment]
@akostyuk @alcamie101 @andyhky @briceburg @drcapulet @jpmens @jtyr @mgruener @mpdehaan @nerzhul @ogenstad @ravibhure @romeotheriault

Hoping to get this merged! Any module maintainers who can help review and approve this new module I'll send $15 by PayPal as a small token of appreciation when it is successfully merged.

**Comment by maxamillion** [comment]
@andy-pi thank you for the PR! Sorry again about the lag time on this.

Out of curiosity, is there any means via the API to make this module perform idempotent tasks and support `check_mode`? and any chance you could have tests? .... I know integration tests aren't likely because we don't have credentials but unit tests would be good if you don't mind.

and finally, we're looking to do changelogs with all new noteworthy PRs such as new modules, how-to below

## How to
A basic changelog fragment is a .yaml file placed in the
changelogs/fragments/ directory.  Each file contains a yaml dict with
keys like "bugfixes" or "major_changes" followed by a list of
changelog entries of bugfixes or features.  Each changelog entry is
rst embedded inside of the yaml file which means that certain
constructs would need to be escaped so they can be interpreted by rst
and not by yaml (or escaped for both yaml and rst if that's your
desire).  Each PR should use a new fragment file rather than adding to
an existing one.

Here's an example of a changelog fragment for a bugfix:

```
---
bugfixes:
- copy module - The copy module was attempting to change the mode of files for
  remote_src=True even if mode was not set as a parameter.  This failed on
  filesystems which do not have permission bits
(https://github.com/ansible/ansible/pull/40099)
```

You can find more example changelog fragments in the changelog
directory for a previous release:
https://github.com/ansible/ansible/tree/stable-2.6/changelogs/fragments

You can also find documentation of the format including hints on
embedding rst in the yaml in the reno documentation:
https://docs.openstack.org/reno/latest/user/usage.html#editing-a-release-note

The toplevel keys (bugfixes, major_changes, etc) are defined in the
config file for our release note tool.  You can find the keys
recognized for the current release here:
https://github.com/ansible/ansible/blob/devel/changelogs/config.yaml#L6

**Pull request closed without merging**
