### PR TITLE
Update API example for 2.4

### LINKED ISSUE #30598: Ansible API can not run on  2.4
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core) 
##### SUMMARY

http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html
I use Official Demo Can not run successfully
Please Update New Deomo
##### STEPS TO REPRODUCE

```yaml
http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html
```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Update API example in docs for 2.4

Fixes #30598 

##### ISSUE TYPE
Docs Pull Request

##### COMPONENT NAME
docs

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by sivel** [comment]
This will also need cherry-picked to stable-2.4

**Comment by bcoca** [comment]
shipit

**Comment by samvarankashyap** [comment]
+1

**Comment by abadger** [comment]
Do we need to point out things that work differently on 2.0-2.3?

**Comment by sivel** [comment]
@abadger good question.  I did not since the docs are versioned, but I'll defer to @dharmabumstead

**Review by dharmabumstead — APPROVED** [review]
Thanks @sivel

**Comment by dharmabumstead** [comment]
We’ve mostly covered that in the porting guides but if there are places where examples are obsolete they should definitely be updated.

**Comment by bcoca** [comment]
backported to stable-2.4

**Pull request merged**
