### PR TITLE
Add os_stack_tag module

### PR DESCRIPTION
**Pull request by ruizink**
##### SUMMARY

This change adds a new OpenStack module to allow adding or deleting tags in a Heat Stack.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/openstack/os_stack_tag.py

### CODE REVIEW

**Comment by ruizink** [comment]
recheck

**Review by cloudnull — APPROVED** [review]
shipit

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Review by sshnaidm — CHANGES_REQUESTED** [review]
Because we moved Openstack Ansible modules to Openstack repositories, please submit all changes from openstack modules to Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack Thanks for your contribution and sorry for inconvienience.

**Comment by Akasurde** [comment]
@ruizink Thanks for the contribution. Closing as per above.

**Pull request closed without merging**
