### PR TITLE
fix check mode for all iptables options

### LINKED ISSUE #19476: iptables module make policy and flush changes in check mode
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

iptables module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

linux

##### STEPS TO REPRODUCE

```
ansible-playbook /vagrant/play.yml -l localhost --check
```
```yaml
 - hosts: all
   tasks:
     - iptables:
         chain: INPUT
         policy: DROP
       become: yes
```

##### EXPECTED RESULTS

```
ansible-playbook /vagrant/play.yml -l localhost --check

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [iptables] ****************************************************************
changed: [localhost]
```
```
sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination   
```

##### ACTUAL RESULTS

```
ansible-playbook /vagrant/play.yml -l localhost --check

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [iptables] ****************************************************************
ok: [localhost]

```

```
sudo iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination   
```

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

iptables

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

also simplified code paths and changed import away from *
fixes #19476

### CODE REVIEW

**Comment by LinusU** [comment]
> also simplified code paths and changed import away from *

Because of how ansible works by putting together a python file and sending it over the wire, that won't work...

**Comment by LinusU** [comment]
'needs_revision'

**Comment by bcoca** [comment]
@LinusU  the introduction of ansiballz changed that

**Comment by LinusU** [comment]
That's awesome 🙌 

It should still be moved a bit more up to be compliant with PEP 8 though, there was also some spacing which was inconsistent:

screen shot 2016-12-21 at 3 38 11 pm

**Pull request merged**
