### PR TITLE
Support "flat" role-directory structure

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE
- Feature Pull Request
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

For simple roles there is no need for multi-dir role structure (all dirs can contain just one file - "the main.yml file"). In that cases "flat structure" (instead of "my-role/tasks/main.yml" use just "my-role/tasks.yml") may be more handy - easy to create (for in-house ansible usage "ansible-galaxy --init" is excessive), compact output in find/tree/other directory structure expanders, save typo. Patch is not breaking "classic" variant (with complete subdir structure) - nothing should be broken, new handy option is available.

Demonstration:

```
$ tree  # directory structure
.
├── playbook.yml
└── roles
    └── trole
        ├── handlers
        │   └── main.yml
        ├── tasks.yaml
        └── vars.yml

3 directories, 4 files
$ ansible-playbook playbook.yml  # try to execute role (with patch)
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [trole : test task] *******************************************************
ok: [localhost] => {
    "msg": "test"
}

TASK [trole : show var] ********************************************************
ok: [localhost] => {
    "my_var": "awesome value"
}

TASK [trole : run shell command] ***********************************************
changed: [localhost]

RUNNING HANDLER [trole : some handler] *****************************************
ok: [localhost] => {
    "msg": "flushing handler"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0   

$ # it works
$ # "handlers/" is just to show backward compatibility
```

### CODE REVIEW

**Comment by sivel** [comment]
This change has historically been denied.  See https://github.com/ansible/ansible/pull/7080

**Comment by ghost** [comment]
@sivel Thank you for quick reply!

I've read discussions, but didn't find there one of my points - with many roles (and I have about 100, for now) it becomes really hard to list them. To many useless rows, that just dim my eyes.

Sum up with all previous significant comments. I really don't see the "mess" here as Michael DeHaan pointed.

I'm trying to say - there are A LOT of people, who will improve their work with such change, and this change is backward compatible, and it is not really complicating anything (documentation update will be just 3 lines, this change is easy to understand, etc). Current strictness makes small disturbances, but many-many times. :( 

So, maybe it is the time to review the policy? I don't feel it is really about practical aspects, but just about personal tastes.

**Comment by decayofmind** [comment]
+1

**Comment by zedekiah** [comment]
+1

**Comment by MiklerGM** [comment]
+1

**Comment by svpace** [comment]
+1
A lot of the roles in galaxy seems to fall in the "single main.yml per directory" category, especially for defaults, meta and handlers

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. 

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
