### PR TITLE
docker_stack: Cleanup EXAMPLES

### PR DESCRIPTION
**Pull request by hannseman**
##### SUMMARY

Cleanup the examples a bit by using a more commonly used yaml formatting. I'll make it a bit easier for copy-and-pasting.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docker_stack

### CODE REVIEW

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @hannseman for the Ansible documentation fix!

**Comment by hannseman** [comment]
@samccann thanks for the review and merge!

**Comment by felixfontein** [comment]
@hannseman thanks for doing this! Do you want to backport this to stable-2.8?

**Comment by hannseman** [comment]
@felixfontein sure I’ll open up a PR tomorrow

**Pull request merged**
