### PR TITLE
correct message to have consistent pluralisation

### PR DESCRIPTION
**Pull request by ikanobori**
##### SUMMARY

A minor consistency issue I noticed.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
system

##### ANSIBLE VERSION
```
2.6.0
```

##### ADDITIONAL INFORMATION
This should not affect the Googleability of this error :)

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The
                locales you've entered is not available on your system."}
```
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The
                locale you've entered is not available on your system."}
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @acozine @samccann

**Comment by samccann** [comment]
rebuild_merge

**Comment by samccann** [comment]
@ikanobori thanks for the Ansible documentation fix!

**Comment by ikanobori** [comment]
@samccann Thanks for taking minor changes as serious as code changes!

**Pull request merged**
