### PR TITLE
Fix broken urpmi module

### LINKED ISSUE #47154: urpmi broken with 2.7.0 vs 2.5.5
##### SUMMARY

Using urpmi with ansible 2.7.0 is broken compared to the same usage with 2.5.5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Probably in ansible/modules/packaging/os/urpmi.py

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /users-ssd/bruno/prj/musique-ancienne.org/ansible/ansible.cfg
  configured module search path = [u'/users/bruno/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.15 (default, May  1 2018, 17:08:05) [GCC 5.4.0]
```

##### CONFIGURATION

```
DEFAULT_BECOME(/users-ssd/bruno/prj/musique-ancienne.org/ansible/ansible.cfg) = True
DEFAULT_BECOME_USER(/users-ssd/bruno/prj/musique-ancienne.org/ansible/ansible.cfg) = root
DEFAULT_HOST_LIST(/users-ssd/bruno/prj/musique-ancienne.org/ansible/ansible.cfg) = [u'/users-ssd/bruno/prj/musique-ancienne.org/ansible/inventory']
DEFAULT_REMOTE_USER(/users-ssd/bruno/prj/musique-ancienne.org/ansible/ansible.cfg) = xxx
```

##### OS / ENVIRONMENT

Running on Mageia Linux 6.1
Linux victoria2.home.musique-ancienne.org 4.14.70-server-2.mga6 #1 SMP Thu Sep 20 22:18:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  tasks:
  - name: Check that mon is installed
    urpmi: name=mon state=installed
```

##### EXPECTED RESULTS

Here is what I get with ansible 2.5.5:
```
ansible-playbook -vvvv test.yml 
ansible-playbook 2.5.5
  config file = /users/bruno/.ansible.cfg
  configured module search path = [u'/users/bruno/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15 (default, Jun 17 2018, 18:39:32) [GCC 7.3.0]
Using /users/bruno/.ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yml ***********************************************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] *************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************
task path: /users/bruno/prj/mageia/docker/test.yml:2
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bruno
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-fydtaqywqcrqewmforxzvycyhrxwwmjs; /bin/python'"'"' && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Check that mon is installed] *******************************************************************************************************************************************************************************************************************
task path: /users/bruno/prj/mageia/docker/test.yml:4
Using module file /usr/lib/python2.7/site-packages/ansible/modules/packaging/os/urpmi.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bruno
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-mqrxiotjfkzaackzxmgticmhxmkakxju; /bin/python'"'"' && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "force": true, 
            "name": "mon", 
            "no_recommends": true, 
            "package": "mon", 
            "root": null, 
            "state": "installed", 
            "update_cache": false
        }
    }, 
    "msg": "mon present(s)"
}
META: ran handlers
META: ran handlers

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
ansible-playbook -vvvv test.yml 
ansible-playbook 2.7.0
  config file = /users/bruno/.ansible.cfg
  configured module search path = [u'/users/bruno/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15 (default, Jun 17 2018, 18:39:32) [GCC 7.3.0]
Using /users/bruno/.ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yml ***********************************************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] *************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************
task path: /users/bruno/prj/mageia/docker/test.yml:2
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bruno
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ylusxatunijpxvaudmhxohfqachblelm; /usr/bin/python2'"'"' && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Check that mon is installed] *******************************************************************************************************************************************************************************************************************
task path: /users/bruno/prj/mageia/docker/test.yml:4
Using module file /usr/lib/python2.7/site-packages/ansible/modules/packaging/os/urpmi.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bruno
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-yxixemcphofqstjjjdoocwwrepebhudb; /usr/bin/python2'"'"' && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_urpmi_payload_GtD0Gf/__main__.py", line 228, in <module>
  File "/tmp/ansible_urpmi_payload_GtD0Gf/__main__.py", line 218, in main
KeyError: 'package'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_urpmi_payload_GtD0Gf/__main__.py\", line 228, in <module>\n  File \"/tmp/ansible_urpmi_payload_GtD0Gf/__main__.py\", line 218, in main\nKeyError: 'package'\n",                                                                                                                 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
        to retry, use: --limit @/users/bruno/prj/mageia/docker/test.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

### PR DESCRIPTION
**Pull request by pmakowski**
##### SUMMARY
Fixes #47154 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
urpmi

##### ADDITIONAL INFORMATION
Need to be backported to  [stable-2.7]

### CODE REVIEW

**Comment by pmakowski** [comment]
+label affects_2.7
shipit
easyfix

**Comment by pmakowski** [comment]
Shippable timeout should not block this 
!needs_revision
the community_review should be set

**Comment by gundalow** [comment]
@bcornec Hi, does this fix https://github.com/ansible/ansible/issues/47154 for you?

**Comment by bcornec** [comment]
On Wed, Dec 19, 2018 at 02:31:35AM -0800, John R Barker wrote:
> @bcornec Hi, does this fix https://github.com/ansible/ansible/issues/47154 for you?

Yes. I closed the BR associated.

Bruno.
-- 
Des infos sur la musique ancienne  -- http://www.musique-ancienne.org
Des infos sur les logiciels libres -- http://www.HyPer-Linux.org
Home, sweet musical Home -- Lover of Andromède, Béatrice, Early Music, 
Josquin, Linux, Mélisande, Recorder, and Ségolène (not in that order)

**Comment by gundalow** [comment]
rebuild_merge

**Comment by gundalow** [comment]
@pmakowski Once this has been merged can you please raise a backport PR including a `changelog/fragment` file as detailed here https://docs.ansible.com/ansible/devel/community/development_process.html#making-your-pr-merge-worthy so we can get this fix into `stable-2.7`

@pmakowski Thank you for this fix
@bcornec Thank you for confirming the fix is correct

**Pull request merged**
