### PR TITLE
fix "plugins/netconf/ce.py" for  "netconf/capability/exchange".

### PR DESCRIPTION
**Pull request by yuandongx**
##### SUMMARY

fix `plugins/netconf/ce.py` for  `netconf/capability/exchange`
```
<capability>http://www.huawei.com/netconf/capability/exchange/1.0</capability>
<capability>http://www.huawei.com/netconf/capability/exchange/1.2</capability>
```

##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

lib/ansible/plugins/netconf/ce.py
### to fetch attribute 'set-id', such as:
```paste below
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" set-id="989">
  <data>
    <ifm xmlns="http://www.huawei.com/netconf/vrp" format-version="1.0" content-version="1.0">
      <interfaces>
        <interface>
          <ifIndex>2</ifIndex>
          <ifName>Virtual-Template0</ifName>
          <ifPhyType>Virtual-Template</ifPhyType>
     <!-- additional <user> elements appear here... --> 
        </interface>
      </interfaces>
    </ifm>
  </data>
</rpc-reply>
```

### CODE REVIEW

**Comment by hwDCN** [comment]
+1

**Comment by hwDCN** [comment]
+1

**Comment by hwDCN** [comment]
bot_status

**Comment by hwDCN** [comment]
@resmo  Please give us a hand, please.
Thank you so much!

**Comment by xuxiaowei0512** [comment]
@resmo 
ah, thanks. I am going to try my luck.

**Comment by hwDCN** [comment]
+1

**Comment by zhongjun2** [comment]
bot_status

**Review by resmo — APPROVED** [review]
LGTM

code LGTM but can not test or verfiy the fix

**Comment by xuxiaowei0512** [comment]
> LGTM
> 
> code LGTM but can not test or verfiy the fix
@resmo 
I've  tested and verified it on real device befor codes were commited.

**Pull request merged**
