### PR TITLE
Add check for correct parsing of sysctl (PEP8)

### LINKED ISSUE #24453: ValueError in sysctl module when parsing syntax error in sysctl.conf
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sysctl module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.8 (default, Aug 10 2016, 10:26:01) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

RedHat managing RedHat hosts

##### SUMMARY

When the sysctl.conf on the managed host contains syntax errors, sysctl bails out with an error that is hard to debug.

##### STEPS TO REPRODUCE

Create a syntax error in /etc/sysctl.conf and set up a task that uses the sysctl module and wants to parse/change sysctl variables on that host. E.g. add a line that does not start with a hasmark, and does not contain any equal signs.
The issue on our side was that we accidentally entered a comment (line without a =) into /etc/sysctl.conf and forgot to prepend it with a hashmark. 
We are just migrating to ansible, so the file was created mostly manually, it's not yet (fully) under ansible control.

```yaml
- name: set up sysctl values - IF THIS FAILS, check sysctl.conf for syntax errors
  sysctl:
    name:      "{{ item.name }}"
    value:     "{{ item.value }}"
    state:      present
    sysctl_set: yes
    reload:     no
  with_items:
    - "{{ sysctl_values }}"
```

##### EXPECTED RESULTS

Reporting this as an error condition makes sense, but I would expect something that tells me that there was a syntax error in the file, not a straight ValueError from python that is hard to understand. The line.split('=',1) gave it away but I don't think it's really easy to understand what's going on. 

##### ACTUAL RESULTS

```
failed: [testhost1] (item={u'name': u'net.ipv4.tcp_sack', u'value': u'0'}) => {
    "failed": true, 
    "item": {
        "name": "net.ipv4.tcp_sack", 
        "value": "0"
    }, 
    "module_stderr": "Shared connection to testhost1 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_BLCuvV/ansible_module_sysctl.py\", line 397, in <module>\r\n    main()\r\n  File \"/tmp/ansible_BLCuvV/ansible_module_sysctl.py\", line 391, in main\r\n    result = SysctlModule(module)\r\n  File \"/tmp/ansible_BLCuvV/ansible_module_sysctl.py\", line 142, in __init__\r\n    self.process()\r\n  File \"/tmp/ansible_BLCuvV/ansible_module_sysctl.py\", line 162, in process\r\n    self.read_sysctl_file()\r\n  File \"/tmp/ansible_BLCuvV/ansible_module_sysctl.py\", line 323, in read_sysctl_file\r\n    k, v = line.split('=',1)\r\nValueError: need more than 1 value to unpack\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* PEP8 fixes
* Refactoring of code
* Check to skip non-comment lines which doesn't
  contain = character

Fixes #24453

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/system/sysctl.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
@davixx Can you please check changes ?

**Comment by Akasurde** [comment]
@jctanner Could you please review the changes ?

**Comment by Akasurde** [comment]
bump for review

**Comment by Akasurde** [comment]
Closing and re-opening to remove `stale_ci` label.

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
Do I need to do anything to get this PR rolling ?

**Comment by Akasurde** [comment]
shipit

**Comment by Akasurde** [comment]
bot_status

**Comment by Akasurde** [comment]
Can someone please review these changes ?

**Comment by calfonso** [comment]
rebuild_merge

**Comment by Akasurde** [comment]
@calfonso Thanks for review and merge.

**Pull request merged**
