### PR TITLE
The required package for selinux is libselinux-python

### PR DESCRIPTION
**Pull request by jlaska**
A small change to adjust the package name that provides the python selinux library.

### CODE REVIEW

**Comment by bcoca** [comment]
Package name is distro dependant

Brian Coca

**Comment by jlaska** [comment]
The libselinux-python package was the correct name for CentOS and
Fedora. I haven't checked RHEL or Ubuntu.

We can adjust the wording to be generic, suggesting they consult their
distribution for the correct SELinux python library?

**Comment by bcoca** [comment]
python-selinux is the ubuntu one

**Comment by mpdehaan** [comment]
SELinux is a lot more common on CentOS/Fedora/Red Hat.  I'll accept a pull request to stick a slash in there if you want to fix it.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
