### PR TITLE
[Fix #11968] Use the real python interpreter in templates

### LINKED ISSUE #11968: [devel] Python Interpreter not taken in account for template checksum
**Issue Type**: Bug Report

**Ansible Version**
Latest version of `devel`

**Ansible Configuration**

```
[defaults]
remote_user = core

[ssh_connection]
ssh_args = -o StrictHostKeyChecking=no
pipelining = True
```

Also `ansible_python_interpreter` is set to `/home/core/bin/python` on the relevant servers.

I ran the same tests with `pipelining` to False as well.

**Environment**
I try to send a template to my CoreOS servers. They have no Python by default, so the interpreter is manually installed in `/home/core/bin/python`.

**Summary**
Trying to use the `template` action will result in an error 4, which is "No python interpreter".

**Steps to reproduce**
On a server bootstraped with the `defunctzombie.coreos-bootstrap` playbook, try to send a template.

``` yml
- name: generate cloud config
  template: src=cloud-config.yml dest=/home/core/cloud-config.yml
  register: cloud_config_update
```

**Expected results**
The file generated by template should be uploaded to the remote server. This is what happens in `1.9`.

**Actual results**

```
<myhost.mydomain.com> ESTABLISH SSH CONNECTION FOR USER: core
<myhost.mydomain.com> EXEC ssh -C -tt -q -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 myhost.mydomain.com (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1439633685.62-228244614437096" && echo "$HOME/.ansible/tmp/ansible-tmp-1439633685.62-228244614437096")                                                                                                     
<myhost.mydomain.com> ESTABLISH SSH CONNECTION FOR USER: core
<myhost.mydomain.com> EXEC ssh -C -tt -q -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 myhost.mydomain.com rc=flag; [ -r /home/core/cloud-config.yml ] || rc=2; [ -f /home/core/cloud-config.yml ] || rc=1; [ -d /home/core/cloud-config.yml ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/home/core/cloud-config.yml && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'/home/core/cloud-config.yml'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'/home/core/cloud-config.yml'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/home/core/cloud-config.yml)
fatal: [myhost.mydomain.com]: FAILED! => {"changed": false, "failed": true, "msg": "failed to checksum remote file. Checksum error code: 4"}
```

As you can see, it seems that the Python interpreter is simply `python` and not the one specified in `ansible_python_interpreter`. This results in an error code `4`. The value for the servers in question is `/home/core/bin/python`.

### PR DESCRIPTION
**Pull request by Xowap**
Fix https://github.com/ansible/ansible/issues/11968

I am unsure of how to test that correctly, however this piece of code fixed the bug for me.

### CODE REVIEW

**Comment by jimi-c** [comment]
Hi @Xowap, looking at this I believe there's a slightly deeper fix required, which is here: https://gist.github.com/jimi-c/cae961e872dd63de91a1

The problem is that the variables assigned to the Templar() class at that point may or may not be all of the variables required, so to be sure the `_remote_checksum` method should use the fully compiled dictionary provided to the action plugin (essentially what `inject` used to be).

Try that patch out and let me know if you see any problems with it.

**Comment by Xowap** [comment]
Thanks @jimi-c, I've given it a try and there was some syntax issues, so I've fixed it this way: https://gist.github.com/Xowap/b8fe78e31c4507d7d0e3

However it does not work and goes back to telling me `{"changed": false, "failed": true, "msg": "failed to checksum remote file. Checksum error code: 4"}`

**Comment by jimi-c** [comment]
Hrm, ok, we had tweaked it a bit after sharing that with you, as we're not sure pulling them from hostvars is still the way to go in that code. I've updated the gist at https://gist.github.com/jimi-c/cae961e872dd63de91a1, though I wasn't quite sure where you saw the syntax errors? I ran `make tests` and all tests passed successfully with the above gist.

**Comment by jimi-c** [comment]
Nevermind, I was able to spot the issue(s) testing your example from #11968 on a system with the `ansible_python_interpreter` value set. My patch seems to resolve the issue there, and I verified in the `-vvv` output that the different interpreter was being used:

<pre>
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1439654173.85-253332706468148" && echo "$HOME/.ansible/tmp/ansible-tmp-1439654173.85-253332706468148"
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 rc=flag; [ -r /tmp/11968.txt ] || rc=2; [ -f /tmp/11968.txt ] || rc=1; [ -d /tmp/11968.txt ] && rc=3; /opt/python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/tmp/11968.txt && exit 0; (/opt/python -c 'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'/tmp/11968.txt'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (/opt/python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'/tmp/11968.txt'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/tmp/11968.txt)
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> PUT /tmp/tmpfZJKY0 TO /root/.ansible/tmp/ansible-tmp-1439654173.85-253332706468148/source
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1439654175.11-215652984462360" && echo "$HOME/.ansible/tmp/ansible-tmp-1439654175.11-215652984462360"
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> PUT /tmp/tmpnl1dQP TO /root/.ansible/tmp/ansible-tmp-1439654175.11-215652984462360/copy
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /opt/python /root/.ansible/tmp/ansible-tmp-1439654175.11-215652984462360/copy; rm -rf "/root/.ansible/tmp/ansible-tmp-1439654175.11-215652984462360/" >/dev/null 2>&1
changed: [awxlocal] => {"changed": true, "checksum": "5bb42d23b4d597daca001d93821958b463853c2b", "dest": "/tmp/11968.txt", "gid": 0, "group": "root", "md5sum": "fe8567621d9887e1593850966311be4e", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:admin_home_t:s0", "size": 58, "src": "/root/.ansible/tmp/ansible-tmp-1439654173.85-253332706468148/source", "state": "file", "uid": 0}
</pre>

You can see in the checksum step and in the execution of the module that `/opt/python` (which simply a symlink to /usr/bin/python) is being used.

**Comment by jimi-c** [comment]
#  Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request closed without merging**
