### PR TITLE
Adding new module lvol_thin

### PR DESCRIPTION
**Pull request by p53**
##### SUMMARY
Module for managing thin logical volumes, i don't want to merge it into lvol module functionality, because it is quite amount of code and it is more object oriented than lvol module

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
lvol_thin

##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Comment by hryamzik** [comment]
Why does it take `Comma separated list of physical volumes`, not a simple list?

**Comment by p53** [comment]
@hryamzik 
at first i thought that i will just modify lvol module already present, which already has this parameter, but then i rewrote most of the things, but this "feature" left there, i can change it, if it adds value...

**Comment by jborean93** [comment]
@p53, looks like this PR also includes some changes for Windows facts, are you able to separate this into separate PRs?

**Comment by p53** [comment]
ok closing this pull request, creating new #28371

**Pull request closed without merging**
