### PR TITLE
AzureStack Changes - API version and base_url

### PR DESCRIPTION
**Pull request by scassidy-ukcloud-zz**
##### SUMMARY

When creating a Network Security Group in AzureStack using Ansible
when looking at the code the base-url was shown as "none" - this caused the code to use
the standard public azure base-url of "management.azure.com" - this caused ansible
not to work with AzureStack as the URL for AzureStack is not the public one. This address was
set in the credentials file and caused other resources (public ip address, resource grouyp etc...) to
be created OK but did not work for network security groups. After degugging I found that the
local variable is set to the credientials fiule value in this case but the value is not passed to
subsequent functions. This fixes this.

API versions were hardcoded for Azure/AzureStack in Ansible even though the ability
was present to pass the api-version in the playboook. Even though the possibility was there to pass
this it was still hardcoded in Ansible - this fix allows the api version to be passed down and used

##### ISSUE TYPE

 - Bugfix Pull Request
 

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
  
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by scassidy-ukcloud-zz** [comment]
This replaces pull requests 39546 and 39547 as there were issues with those pull request and it is probably better to have changes in the same file in the same pull request instead of seperate ones.

**Comment by scassidy-ukcloud-zz** [comment]
Credentials file used (sensitive information redacted)
[default]
ad_user=************
password=*********
subscription_id=****************
cloud_environment=***********

**Comment by scassidy-ukcloud-zz** [comment]
playbook used (I believe copying and pasting has removed the indentation/.formatting from the YAML)

hosts: localhost
vars:
location: frn00006
resource_group: SC1
storage_account: ansiblepocsa
virtual_network: ansiblevn001
subnet: ansiblesubnet001
publicip: ansiblepublicip001
network_interface: ansibletestnic001
security_group: ansiblesec001
tasks:
name: Create a resource group
azure_rm_resourcegroup:
api_profile: '2017-03-09-profile'
name: "{{ resource_group }}"
location: "{{ location }}"
name: Create storage account
azure_rm_storageaccount:
resource_group: "{{ resource_group }}"
api_profile: '2017-03-09-profile'
name: "{{ storage_account }}"
account_type: Standard_LRS
location: "{{ location }}"
name: Create virtual network
azure_rm_virtualnetwork:
resource_group: "{{ resource_group }}"
name: "{{ virtual_network }}"
api_profile: '2017-03-09-profile'
address_prefixes: "10.10.0.0/16"
name: Add subnet
azure_rm_subnet:
resource_group: "{{ resource_group }}"
name: "{{ subnet }}"
api_profile: '2017-03-09-profile'
address_prefix: "10.10.0.0/24"
virtual_network: "{{ virtual_network }}"
name: Create public ip
azure_rm_publicipaddress:
resource_group: "{{ resource_group }}"
allocation_method: Static
api_profile: '2017-03-09-profile'
name: "{{ publicip }}"
name: Create security group that allows SSH
azure_rm_securitygroup:
resource_group: "{{ resource_group }}"
api_profile: '2017-03-09-profile'
name: "{{ security_group }}"
rules:
name: SSH
source_address_prefix: '*'
protocol: Tcp
destination_port_range: 22
access: Allow
priority: 101
direction: Inbound
name: Create NIC
azure_rm_networkinterface:
resource_group: "{{ resource_group }}"
name: "{{ network_interface }}"
virtual_network: "{{ virtual_network }}"
api_profile: '2017-03-09-profile'
ip_configurations:
name: SC
public_ip_address_name: "name1"
primary: True
subnet: "{{ subnet }}"
public_ip_name: "{{ publicip }}"
security_group: "{{ security_group }}"
name: Create virtual machine
azure_rm_virtualmachine:
api_profile: '2017-03-09-profile'
resource_group: "{{ resource_group }}"
name: ansibletestvm001
vm_size: Standard_D1_v2
storage_account: "{{ storage_account }}"
admin_username: ukcloudadmin
admin_password: Password123!
network_interfaces: "{{ network_interface }}"
image:
offer: CentOS
publisher: OpenLogic
sku: '6.9'
version: 6.9.20180105

**Comment by mattclay** [comment]
CI failure in integration tests due to traceback:

```
Traceback (most recent call last):
  File "/tmp/ansible_tjWSyr/ansible_module_azure_rm_availabilityset.py", line 314, in <module>
    main()
  File "/tmp/ansible_tjWSyr/ansible_module_azure_rm_availabilityset.py", line 311, in main
    AzureRMAvailabilitySet()
  File "/tmp/ansible_tjWSyr/ansible_module_azure_rm_availabilityset.py", line 191, in __init__
    supports_tags=True)
  File "/tmp/ansible_tjWSyr/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 347, in __init__
  File "/tmp/ansible_tjWSyr/ansible_module_azure_rm_availabilityset.py", line 209, in exec_module
    response = self.get_availabilityset()
  File "/tmp/ansible_tjWSyr/ansible_module_azure_rm_availabilityset.py", line 299, in get_availabilityset
    response = self.compute_client.availability_sets.get(self.resource_group, self.name)
  File "/tmp/ansible_tjWSyr/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 965, in compute_client
  File "/tmp/ansible_tjWSyr/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 891, in get_mgmt_svc_client
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/compute/compute_management_client.py", line 78, in __init__
    client_models = {k: v for k, v in self.models(api_version).__dict__.items() if isinstance(v, type)}
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/compute/compute_management_client.py", line 104, in models
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion {'resource_skus': '2017-09-01', 'default_api_version': '2017-12-01', 'virtual_machine_run_commands': '2017-03-30', 'disks': '2017-03-30', 'snapshots': '2017-03-30'} is not available
```

**Comment by scassidy-ukcloud-zz** [comment]
Have resolved all issues shown up by the automated test suite (runnable)

**Comment by nitzmahone** [comment]
Thanks for your contribution...

Proper Azure Stack support is on the Ansible 2.7 roadmap, but requires a lot of bits and pieces that are still in progress (including an Azure Stack CI environment so we can make sure this stuff *keeps* working there once we fix it). After several rounds of discussion with the Azure Python SDK maintainer, we landed on passing the full profiles directly to each client factory instead of individual API versions.

There's a lot of conditional execution that needs to be added to the modules as well, and since Azure Stack itself is a moving target, we have to figure out how to do that to avoid the module code turning into an unmaintainable mess of conditions for N different versions of Stack or making a total hash of the module UIs with Stack-specific args. We have some ideas, but they need to be tried out...

Anyway, it's planned for 2.7, so stay tuned- we'd love to have you try it out and make sure it works for your env once we have everything going. 

Closing this PR, since there's a different approach in progress.

**Comment by cblackuk** [comment]
@nitzmahone Thanks for replying and giving us some insight as to what is happening behind the scenes.

Any idea when 2.7 is scheduled?

On a separate note, everyone is having the same problem - how not to create a lot of conditional statements to cater for Azure Stack but profiles that we kind of have to use is pretty much the approach.

Terraform already managed to get it working so I am really rooting for you guys as getting this working fully would unblock me and my customers to start using the tools we all know and love.

If there is anything we can do to help you guys, let us know.

**Comment by cblackuk** [comment]
@nitzmahone 

As far as I can see 2.7 is out and Azure Stack profiles are still broken. Any ideas?

**Pull request closed without merging**
