### PR TITLE
Allow groups to be defined on a per-host basis

### PR DESCRIPTION
**Pull request by dagwieers**
This makes it possible to define on a per-host basis what groups a host is in.
When managing a large set of systems it makes it easier to ensure each of the
systems is defined in a set of groups (e.g. production/qa/development,
linux/solaris/aix) rather than having to add systems to multiple disconnected
groups.

``` yaml
  - host: system01

  - host: system02

  - host: system03

  - group: linux
    hosts:
    - system01
    - system02

  - group: solaris
    hosts:
    - system03

  - group: production
    hosts:
    - system01
    - system03

  - group: qa
    - system02

  - group: dbserver
    hosts:
    - system01

  - group: ntpserver
    hosts:
    - system02

  - group: webserver
    - system03
```

Can be redefined as:

``` yaml
  - host: system01
    groups: [ linux, production, dbserver ]

  - host: system02
    groups: [ linux, qa, ntpserver ]

  - host: system03
    groups: [ solaris, production, webserver ]
```

### CODE REVIEW

**Comment by mpdehaan** [comment]
Code looks good, add some test code to the inventory tests and I'll take this.

**Comment by dagwieers** [comment]
This should be it. And I learned a bit of python-nose along the way ;-)

**Comment by mpdehaan** [comment]
Thanks... rather than adding an extra test file and a complete new series of test functions, it seems it would make more sense to add a few examples of a host specifying a group to the existing YAML test file, that way we also have tests to make sure things all work together and cohesively, at the same time, and have less test code to maintain.

**Comment by dagwieers** [comment]
Ok, fine by me. I wasn't sure if you wanted both types mixed or even the original yaml modified...

**Comment by dagwieers** [comment]
Done !

**Comment by mpdehaan** [comment]
I was actually thinking of making another group, rather than to change the nature of the existing tests, because those existing tests were testing specific things in those ways -- we do not want to remove those test cases.  If we take out the way they were testing the old thing, those tests don't work the same.

Here's what to do.

At the very bottom of the existing YAML file, without changing the top part...

Just add a new group "asteroids" and one called "rocks", and list each host that is an asteroid and put them in asteroids group in your new way of doing it.   Include a comment in the test file that while you can include hosts by group, you can also do it the other way, and keep these seperate.  The tests are also a way to document what works and what doesn't, so mixing them up too much without a comment is a little confusing too.

List three or four asteroid names, put them in asteroids.

Modify the python test file to make sure all asteroids are rocks, and all rocks are rocks, and all asteroids are asteroids, and the all result includes the various gods and asteroids -- but the various tests about gods should be intact.

What this proves is that you can use the old method and new method in the same file, but that the old way is still 100% working the way it used to work -- which is what the regression test is supposed to do (and your original commit did), but also that you can use them together (which is what the new commit did).  This would allow both.

**Comment by dagwieers** [comment]
I made sure that all the various cases are still in the example. But ok, this means the yaml unit tests will diverge from the other unit tests (wrt. the assertions made). No problems, asteroids rock too !

**Comment by mpdehaan** [comment]
yeah I am a bit paranoid about regressions on code paths where I don't use all the quirks all the time.

Sorry about the chaos, this is one of those places.

It's easier to do things like make sure handlers work manually than test the whole inventory subsystem.

**Comment by dagwieers** [comment]
Ok, I used comic and cartoon character because I was getting confused with asteroids and rocks. Don't even know what they would have in common etc... Hopefully everyone knows garfield and goofy :-)

**Comment by mpdehaan** [comment]
nice, will test and merge shortly

**Comment by mpdehaan** [comment]
Merged and pushed, tests are great, thanks.

FYI -- I applied this as a squash commit.  In the future if you are doing development on a given branch, a good way to generate a squash commit is:

git checkout -b sometopic_finished
git merge sometopic --squash
git commit -a

And then you can make the pull request from the squashed branch, where you can review everything in one single patch as opposed to one patch per commit.   Easier to review and keeps the history in the main git repo more or less atomic.

**Comment by mpdehaan** [comment]
(closing per above)

**Comment by dagwieers** [comment]
Hmm, the downside is that these changes do not reference the discussion in the pull request and people cannot blame me for it ;-)

**Comment by mpdehaan** [comment]
Not sure I understand.

**Pull request closed without merging**
