### PR TITLE
Fortinet FortiManager Device Provisioning Template Module

### PR DESCRIPTION
**Pull request by ftntcorecse**
##### SUMMARY

This module allows the add/edit/delete of Device Provisioning Templates within FortiManager, and the configuration of the options within the templates.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

fmgr_device_provision_template.py
test_fmgr_device_provision_template.py
fixtures/test_fmgr_device_provision_template.json
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 9efc3dc761) last updated 2018/09/27 20:21:00 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/ansible_ftnt/library']
  ansible python module location = /root/ansibleSource/ansible/lib/ansible
  executable location = /root/ansibleSource/ansible/bin/ansible
  python version = 2.6.9 (unknown, Sep 27 2018, 21:07:46) [GCC 5.4.0 20160609]
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ftntcorecse** [comment]
@gdpak -- Do I really need to close and resubmit this one, per the "needs_ci" tag?

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by ftntcorecse** [comment]
This one is ready to ship.

**Comment by gdpak** [comment]
@ftntcorecse , As per discussion on #46715, this code need to be modified to use httapi connection plugin . I think it will be better to raise new PR for this module using new httpapi plugin for fortinet. Can you close this PR ?

**Pull request closed without merging**
