### PR TITLE
apt-get autoremove doesn't remove obsolete packages

### PR DESCRIPTION
**Pull request by snowsky**
##### ISSUE TYPE

 - Bugfix Pull Request

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

The command "apt-get install --autoremove" doesn't remove obsolete packages

```

```

### CODE REVIEW

**Comment by varazir** [comment]
I can confirm this is working on 2.3.0

**Comment by snowsky** [comment]
@varazir you are right, let me fix this. How did you mark a package to be auto-removed?

**Comment by varazir** [comment]
@snowsky I fetched this PR but as I posted in the other thread it's allways showing changed. 

I'm running this now and it still shows changed. 


commit 25e7384cd666f064f5bbdba2f28ea771f03858c0
Merge: b3004e1 8bd65c1
Author: varazir <varazir@gmail.com>
Date:   Mon Mar 13 08:47:38 2017 +0100

    Merge commit 'refs/pull/22232/head' of https://github.com/ansible/ansible into devel

    Updating the APT command

**Comment by snowsky** [comment]
@varazir you are right, I used the wrong variable. Sorry about it. I have just updated it. Please give it another try.

**Comment by varazir** [comment]
@snowsky  Hmm 
Running this now 
commit 3016d52ef7954779424398bb6f32bf7dcc59fc8b
Merge: 8b6d786 b95a164

Still gettings same, it's allways reporting back changed

**Comment by snowsky** [comment]
oh, I did fix the remove part, let me fix the other parts, install/upgrade, etc.

**Comment by snowsky** [comment]
@varazir thanks for testing, it should work now. :)

**Comment by varazir** [comment]
Much better I hope :) Didn't have any pgs to remove so have to wait until then

**Comment by snowsky** [comment]
Thanks. I am thinking if there is a way to mark a package for autoremoving...

**Comment by varazir** [comment]
@snowsky Hmm, I think it's working now, but to good not sure if it removed any as it has said OK each time even after kernel updates and it's normaly then you get to remove the old ones and source. 

Going to add a debug

**Comment by snowsky** [comment]
@varazir I found an issue here, which is no matter there was a package to remove, it will always show no change. I'll fix it later.

**Comment by jjaone** [comment]
Still does  not work. I have "ansible 2.3.0.0" playbook targeting Ubuntu 16.04 host with apt-module as autoremove:yes, and the obsolete packages are not removed or autocleaned

**Comment by jjaone** [comment]
Tried also with the Ansible 2.4.0 (git://github.com/ansible/ansible.git) devel-branch after doing: "git checkout devel", and "make", and "sudo make install" and using that to playbook, which has:
```
- name: srvenv - Autoclean and update apt cache
  become: yes
  apt:
    autoremove: yes
    purge: yes
    force: yes
    update_cache: yes
```

still the apt-module does not delete, remove or autoclean the obsolete packages, but they remain in the system:
 ```
$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-45 linux-headers-4.4.0-59 linux-headers-4.4.0-62 linux-headers-4.4.0-63 linux-headers-4.4.0-64 linux-headers-4.4.0-65
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-image-4.4.0-66-generic linux-image-extra-4.4.0-66-generic
Use 'sudo apt autoremove' to remove them.
```

The apt-module verbose log look like this:
```
ok: [myhost] => {
    "cache_update_time": 11746325, 
    "cache_updated": false, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoremove": true, 
            "cache_valid_time": 7200, 
            "deb": null, 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": true, 
            "install_recommends": null, 
            "only_upgrade": false, 
            "package": null, 
            "purge": true, 
            "state": "present", 
            "update_cache": true, 
            "upgrade": null
        }
    }
}
```

**Comment by snowsky** [comment]
Thanks. I'll take a look. It seems it didn't run install and remove functions.

**Comment by jjaone** [comment]
Thanks @snowsky for looking into this. 

FYI I might have been doing something wrong because now that I looked my source code files (the ones that I have been clone/fetch/pulling from the ansible/Git-brances (devel and stable-2.3) I don't see these commits in os/apt.py file that you have made to resolve this apt-module "autoremove" functionality. 

Is it because these are *all* still PR:s, and they have not yet been merged in those branches?

Or how should I actually review and test these fixes? Do I have to manuallu copy the file contents? Or should I clone/fetch/pull some devel/PR-branch to test these?

**Comment by snowsky** [comment]
@jjaone you can checkout the branch I am using to have the same contents.

**Comment by jjaone** [comment]
Thanks @snowsky for the info, after cloning the ansible repo did this;
```
git checkout stable-2.3
git pull
git fetch origin pull/22232/head:snowskyautoremove
git checkout snowskyautoremove
make && sudo make install
``` 
and still when I run my above play with this ansible-playbook, it produces this in verbose log:
``` 
changed: [myhost] => {
    "cache_update_time": 1490904707, 
    "cache_updated": true, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoremove": true, 
            "cache_valid_time": 0, 
            "deb": null, 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": true, 
            "install_recommends": null, 
            "only_upgrade": false, 
            "package": null, 
            "purge": true, 
            "state": "present", 
            "update_cache": true, 
            "upgrade": null
        }
    }
}
```
and nothing in the target systen gets autocleaned or removed.

So this fix does not work?

**Comment by snowsky** [comment]
I am waiting for my system to have autoremoved packages. Is there a way to mark a package as autoremoved one?

**Comment by jjaone** [comment]
Well, you could achieve that by installing some "metapackage" like mysql-common or "ubuntu-packaging-guide" to ur system and then removing it. That'll leave all dependent packages in the system as "autoremovable". 

In Ubuntu (16.04), find some "metapacakges" with: 
```$ apt-cache search . | grep -i "metapackage\|meta-package"```

Then install one of them, e.g:
```$ sudo apt install ubuntu-packaging-guide```

and remove it:
```$ sudo apt remove ubuntu-packaging-guide```

Now, to see that you actually have some "autoremovable" packages do:
``` 
$ sudo apt-get --dry-run autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libjs-sphinxdoc libjs-underscore ubuntu-packaging-guide-common ubuntu-packaging-guide-html
0 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
Remv ubuntu-packaging-guide-html [0.3.7]
Remv ubuntu-packaging-guide-common [0.3.7]
Remv libjs-sphinxdoc [1.3.6-2ubuntu1]
Remv libjs-underscore [1.7.0~dfsg-1ubuntu1]
```

Or
```
$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libjs-sphinxdoc libjs-underscore ubuntu-packaging-guide-common ubuntu-packaging-guide-html
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

With that you can test ur ansible/apt-module "autoremove" fix and see that it does not work, but leaves those packages in the system when run like the task I have in my playbook above.

**Comment by snowsky** [comment]
Thanks @jjaone. It seems different versions of Ansible is using different file, lib/ansible/modules/core/packaging/os/apt.py and lib/ansible/modules/packaging/os/apt.py are two different files, not sure why we have got 2 in different places.

**Comment by jjaone** [comment]
BTW: I noticed that in the SUMMARY of this PR description it says:

> The command "apt-get install --autoremove" doesn't remove obsolete packages

which is actually correct, cause norrmal user does not have automatically permissions ro remove packages, but if the command is run with sudo:

> sudo apt-get install --autoremove

then it works and correctly removes obsolote and "autoremovable" packages, atleast in Ubuntu.

**Comment by jjaone** [comment]
Ok @snowsky, does that mean, that if ur fix is applied to both of those apt.py files, then it should work?

Those files seem to have quite a lot of differences, so just copying the other on to the other won't work, right?

**Comment by snowsky** [comment]
Let me ask on the devel list to see if anyone knows this.

**Comment by mattclay** [comment]
Starting with `stable-2.3`, modules have been moved from `lib/ansible/modules/core/` and `lib/ansible/modules/extras/` to just `lib/ansible/modules/`.

**Comment by snowsky** [comment]
@mattclay thanks for the info, just curious which PR introduce this change?

**Comment by snowsky** [comment]
And how could I submit a fix for core module since it is locked?

**Comment by mattclay** [comment]
@snowsky There was no PR, but we do have some docs on the [repo merge](https://docs.ansible.com/ansible/dev_guide/repomerge.html).

All changes to modules now take place in the `devel` branch of the [ansible/ansible](https://github.com/ansible/ansible/) repository. Fixes to modules will be backported to their pre-merge repo as needed by the Ansible Core Team.

**Comment by mkrizek** [comment]
@snowsky would you mind rebasing your PR so we can continue with the review? Thanks!

**Comment by bcoca** [comment]
closed because of inactivity

**Comment by jjaone** [comment]
Is it now resolved, where?

**Comment by jjaone** [comment]
@bcoca Is it now resolved, where in which commit and when?

**Pull request closed without merging**
