### PR TITLE
Bump antsibull-docs version to 1.1.0 to support sidecar docs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Some of the results: https://ansible.fontein.de/collections/ansible/builtin/#filter-plugins

Merge requires default test container (for ansible-core) to be rebuilt.

CC @samccann 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs build

### CODE REVIEW

**Comment by sivel** [comment]
There are some refactors and changes going on to the sidecar feature. We might want to let the dust settle a little first to be safe.

**Comment by felixfontein** [comment]
(Failing sanity errors are fixed in #77725.)

**Review by samccann — APPROVED** [review]
Verified on jenkins test and LGTM

**Comment by samccann** [comment]
Once CI passes ;-) The goal on this PR is to wait until there are other changes required for the test containers and group this PR with them.

**Comment by samccann** [comment]
Putting in WIP while sidecar docs dust settles on possible changes ;-)

**Comment by samccann** [comment]
Closed in favor of https://github.com/ansible/ansible/pull/78773

**Pull request closed without merging**
