### PR TITLE
Backport/2.6/51653

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
Backport fix with PostgreSQL server update.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_postgresqlserver

### CODE REVIEW

**Comment by abadger** [comment]
This seems to be failing because the azure test hosts are slightly different in stable-2.6 than they are in devel.  Can you change the alias so that the tests pass?

```
test/integration/targets/azure_rm_postgresqlserver/aliases:0:0: missing alias `shippable/azure/group[1-4]` or `unsupported`
```

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino CI verify fail, Please recheck this PR when you're available! Thanks!

**Comment by abadger** [comment]
@zikalino Once 2.8.0 comes out, 2.6 will move to only getting updates for security issues.  If you want this in 2.6.x, please fix it up ASAP.  Thanks.

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino CI verify fail.  Please update! Thanks!

**Comment by zikalino** [comment]
not essential for 2.6, and too many incompatibilities to resolve, closing

**Pull request closed without merging**
