### PR TITLE
Devel - fix issue #315

### PR DESCRIPTION
**Pull request by mrproper**
reworked groups and/or append logic

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Brendan,

I have just merged https://github.com/ansible/ansible/pull/326 which was submitted a few days earlier and seems to address the same problem -- if you still believe this change is needed let me know, I think you will need to at least "git rebase".

Thanks!

**Comment by mrproper** [comment]
Hi Michael,

That patch doesnt resolve in the scenario if say

user is currently a member of a, b and c
and my groups statement with append is 'a,b'

that code will still trigger usermod -a a,b

the patch i submitted handles if other groups that user is currently a
member of that the groups param is not aware of

Cheers
Brendan

On Tue, May 8, 2012 at 10:03 AM, Michael DeHaan <
reply@reply.github.com

**Comment by mpdehaan** [comment]
ok, thanks for the update -- so these two patches conflict and I think you know what you want better than I do.   On your development branch please run "git rebase origin/devel", correct any conflicts, and then you can update the pull request, and resubmit.

**Comment by mrproper** [comment]
ok sorted out now, merged devel and resolved the conflict

Cheers
Brendan

On Tue, May 8, 2012 at 10:10 AM, Michael DeHaan <
reply@reply.github.com

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
