### PR TITLE
cloud: ovirt: logout if token is not used

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ovirt_*

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This PR changes the logic, so we now logout the user only in case the user passed the username/password. In case user passed token we don't revoke it.

We must use it like this, because in case the user will use `ansible-console` and ENV variables with username password for example, we don't logout the user, which may overload oVirt engine.

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina

**Review by mwperina — APPROVED** [review]
👍

**Comment by machacekondra** [comment]
shipit

**Comment by mwperina** [comment]
@gundalow @ryansb 

Could you please merge it?

**Pull request merged**
