### PR TITLE
postgresql_lang: use query parameters with cursor.execute()

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_lang: use query parameters with cursor.execute()

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/postgresql/postgresql_lang.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by tcraxs** [comment]
LGTM

**Comment by gundalow** [comment]
@Andersson007 @tcraxs Thank as always.

**Comment by Andersson007** [comment]
@tcraxs @gundalow thank you

**Pull request merged**
