### PR TITLE
vmware_guest: rework cpu configuration

### PR DESCRIPTION
**Pull request by nerzhul**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
2.2.1.0
```

##### SUMMARY

 * remove hardware.num_cpus configuration
 * add cpu option
 * add cpu_cores_per_socket option (new feature: manage cpu cores per socket)
 * add fact hw_processor_cores_per_socket_count to know core number per socket

### CODE REVIEW

**Comment by aperigault** [comment]
I remember me an idea from @dagwieers i think, to move hardware customization out of hardware key. If you start it it could be good to move all the content of **harware** out of it ?

**Comment by nerzhul** [comment]
@aperigault i also suggested it, but maybe in another PR, this PR only cover CPU core part, but yes memory and controller type should be outside of hardware before 2.3

**Comment by aperigault** [comment]
LGTM

**Comment by jctanner** [comment]
@dagwieers @dav1x need your thoughts on this change to the argspec.

If we're all in agreement about flattening the hardware argument, we should do that asap.

**Comment by dav1x** [comment]
I like the idea of simplifying the module arguments. This all tests fine btw. LGTM

**Comment by dav1x** [comment]
shipit

**Comment by dagwieers** [comment]
I don't like the flattening of hardware arguments.
I'd rather have a tree of the various hardware components under the hardware-key.

For example:
```yaml
hardware:
  cpu:
    cpus: 2
    cores_per_socket: 2
```
or
```yaml
hardware:
  cpu:
    sockets: 2
    cores_per_socket: 2
```
or
```yaml
hardware:
  cpu:
    physical: 2
    logical: 4
```
All would mean you have 4 cores in total, and 2 actual CPU sockets
Need to check what the relevant names are in the VMware GUI.

**Comment by nerzhul** [comment]
the dictionnary concept is not ansible friendly for two reasons:

* documentation support doesn't like it
* code should support a dict and re-create all AnsibleModule primitives

Moreover CPU is purely machine attribute and immutable with machine

**Comment by jctanner** [comment]
@dagwieers are you okay with this particular PR?

We can move the arg flattening to a separate thread if so.

**Comment by dagwieers** [comment]
@jctanner The arg flattening is part of the PR, so in that respect I am not okay with the PR :-)

@nerzhul You are right that the documentation does not support it well, but we do the same for customization and network, because these attributes go together logically. Also you can hot-add CPUs, just like memory. So in that respect it is not different. But even if it can only be modified if the VM is turned off, it doesn't really matter IMO.

If the documentation infrastructure is not adequate to our needs (which I don't think is a real problem), we need to improve the documentation infrastructure IMO, not the module interface.

What is a real problem today, is the fact that we don't do any type-checking on dict-type parameters. But that's something we have to improve anyhow (I think it was brought up before when we discussed customizations).

**Comment by angystardust** [comment]
@nerzhul so, you're not going to merge this for 2.3 GA, right?

**Comment by nerzhul** [comment]
@angystardust i think this should be merged, and i hope it will be done, as i'm using it heavily in my infrastructure :)

**Comment by nerzhul** [comment]
needs_rebase

**Comment by dagwieers** [comment]
So core is working on having subspecs for parameters, so flattening should not be needed if the concern is that we cannot check types of dictionary-parameters. #21171

**Comment by nerzhul** [comment]
very interesting
a doc support is also needed

**Comment by nerzhul** [comment]
it seems we forget this patch for the 2.3 release... sorry it's too late, will rework on it after 2.3 release

**Comment by jctanner** [comment]
@nerzhul you still have time to get this fixed for 2.4, are you interested?

needs_info

**Comment by mcsalgado** [comment]
I have interest on this feature so I did a rebase of this PR here: https://github.com/mcsalgado/ansible/commit/8dae218f819717e46ab6ae77e307740aa00a05dd

I'm not sure if I should create a separate PR for this or not.

I can also write an additional commit to unflatten the arguments if this is what you guys decided on.

**Comment by Akasurde** [comment]
@nerzhul Are you still working on this ?

**Comment by nerzhul** [comment]
@Akasurde no i don't get time, i'm over busy on other projects, i use vmware_guest but don't get time to modify it

**Pull request closed without merging**
