### PR TITLE
synchronization module take 3

### PR DESCRIPTION
**Pull request by tima**

### CODE REVIEW

**Comment by akuznecov** [comment]
Have tried to use it and got issue with multiple items on dest
Task:

``` yaml
- name: 'SOLR | Deploy cores configuration files '
  synchronize: src=data/core-conf/ dest=/opt/solr/home/cores/$item/conf/ archive=yes delete=yes rsync_path="sudo rsync"
  with_items:
    - dev
    - stage
```

Output:

> TASK: [SOLR | Deploy cores configuration files ] *****************************\* 
> ok: [10.1.250.10] => (item=dev) => {"changed": false, "cmd": "rsync --delay-updates --compress --delete-after --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path 'sudo rsync' --out-format='<<CHANGED>>%i %n%L' data/core-conf/ vagrant@10.1.250.10:/opt/solr/home/cores/dev/conf/", "item": "dev", "msg": "", "rc": 0}
> failed: [10.1.250.10] => (item=stage) => {"cmd": "rsync --delay-updates --compress --delete-after --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path 'sudo rsync' --out-format='<<CHANGED>>%i %n%L' data/core-conf/ vagrant@10.1.250.10:vagrant@10.1.250.10:/opt/solr/home/cores/dev/conf/", "failed": true, "item": "stage", "rc": 12}
> msg: rsync: mkdir "/home/vagrant/vagrant@10.1.250.10:/opt/solr/home/cores/dev/conf" failed: No such file or directory (2)
> rsync error: error in file IO (code 11) at main.c(605) [Receiver=3.0.9]
> rsync: connection unexpectedly closed (9 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]

Seems destination hosts added for each item and we got messy connection string

**Comment by tima** [comment]
@akuznecov could you try again with the patch I just pushed here?

**Comment by mpdehaan** [comment]
Thank you very much Tim with going through all the reorgs and hacking on this one!

Super glad to have this in and this will be really popular.

--Michael

**Comment by aw** [comment]
:+1: this module! :heart: :rainbow:

**Comment by akuznecov** [comment]
@tima same problem here with the patch too

> TASK: [solr | SOLR | Deploy cores configuration files for instances] *********\* 
> ok: [10.1.250.10] => (item={'autopull': 'present', 'name': 'dev', 'db': 'present', 'auth': 'present', 'cron': 'present', 'vhost': 'application', 'domains': 'dev.test.local', 'docroot': u'/var/www/dev', 'solr': 'present'}) => {"changed": false, "cmd": "rsync --delay-updates --compress --timeout=10 --delete-after --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path 'sudo rsync' --out-format='<<CHANGED>>%i %n%L' projects/test/core-conf/ vagrant@10.1.250.10:/opt/solr/home/cores/dev/conf/", "item": {"auth": "present", "autopull": "present", "cron": "present", "db": "present", "docroot": "/var/www/dev", "domains": "dev.test.local", "name": "dev", "solr": "present", "vhost": "application"}, "msg": "", "rc": 0}
> failed: [10.1.250.10] => (item={'autopull': 'absent', 'name': 'stage', 'db': 'present', 'auth': 'present', 'cron': 'absent', 'vhost': 'static', 'domains': 'stage.test.local stg.test.local', 'docroot': u'/var/www/stage/current', 'solr': 'present'}) => {"cmd": "rsync --delay-updates --compress --timeout=10 --delete-after --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path 'sudo rsync' --out-format='<<CHANGED>>%i %n%L' projects/test/core-conf/ vagrant@10.1.250.10:vagrant@10.1.250.10:/opt/solr/home/cores/dev/conf/", "failed": true, "item": {"auth": "present", "autopull": "absent", "cron": "absent", "db": "present", "docroot": "/var/www/stage/current", "domains": "stage.test.local stg.test.local", "name": "stage", "solr": "present", "vhost": "static"}, "rc": 12}
> msg: rsync: mkdir "/home/vagrant/vagrant@10.1.250.10:/opt/solr/home/cores/dev/conf" failed: No such file or directory (2)
> rsync error: error in file IO (code 11) at main.c(605) [Receiver=3.0.9]
> rsync: connection unexpectedly closed (197 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.0]

It only works with modification of last lines of file runner/action_plugins/synchronize.py

``` ruby
        self.runner.module_args = ' '.join(['%s=%s' % (k, v) for (k,
                v) in options.items()])
        return self.runner._execute_module(conn, tmp, 'synchronize',
                self.runner.module_args, inject=inject)
```

to something like this:

``` ruby
        module_items = ' '.join(['%s=%s' % (k, v) for (k,
                v) in options.items()])
        return self.runner._execute_module(conn, tmp, 'synchronize',
                module_items, inject=inject)
```

Here is a part of task with synchronize action:

``` yaml
- name: 'SOLR | Deploy cores configuration files for instances'
  synchronize: src=projects/{{project_name}}/core-conf/ dest=/opt/solr/home/cores/{{item.name}}/conf/ archive=yes delete=yes rsync_path="sudo rsync"
  register: solrxml
  when: item.solr is defined and item.solr == 'present'
  with_items: 
    - $instances
  tags:
    - solr
    - solr-conf
    - search
```

**Comment by tima** [comment]
@akuznecov This pull request is closed. Could you please file a pull request with your changes and someone from the team will look at it.

**Comment by akuznecov** [comment]
@tima thanks for your reply
will create an issue and PR for it soon

**Pull request merged**
