### PR TITLE
fix for #21729, use VERSION_ID instead of PRETTY_NAME to get release

### PR DESCRIPTION
**Pull request by computersalat**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible/module_utils/facts.py
test/units/module_utils/test_distribution_version.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### SUMMARY
see #21729

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests. Here's one of the failures:

```
2017-02-21 21:43:35 >           assert generated_facts[key] == val, msg
2017-02-21 21:43:35 E           AssertionError: Comparing value of distribution_release on openSUSE Leap 42.1, should: x86_64, is: 1
2017-02-21 21:43:35 E           assert '1' == 'x86_64'
2017-02-21 21:43:35 E             - 1
2017-02-21 21:43:35 E             + x86_64
2017-02-21 21:43:35 
2017-02-21 21:43:35 test/units/module_utils/test_distribution_version.py:840: AssertionError
```

Full test results here: https://app.shippable.com/runs/58acb34785f0850f0040e0da/2/tests

**Comment by computersalat** [comment]
@mattclay 
sorry, but your testsuite is just wrong, cause the test suite should **expect** release **1** and not **x86_64** for openSUSE Leap 42.1.
version = 42
release = 1

**Comment by mattclay** [comment]
@computersalat If there is a bug in the unit tests, please update the unit tests as part of your PR.

**Comment by computersalat** [comment]
@mattclay 
updated unit test

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
CI still failing on unit tests: https://app.shippable.com/runs/58acd5a7a0f1360f009fd3eb/2/tests

The unit tests can be run locally with `make tests`.

**Comment by computersalat** [comment]
what dependencies do I need to run ```make tests```
running into lots of ```ImportError```, e.g.
```
======================================================================= ERRORS =======================================================================
__________________________________________________ ERROR collecting test/units/cli/test_console.py ___________________________________________________
test/units/cli/test_console.py:23: in <module>
    from ansible.compat.tests.mock import patch
E   ImportError: cannot import name patch
------------------------------------------------------------------ Captured stdout -------------------------------------------------------------------
You need the mock library installed on python2.x to run tests
___________________________________________________ ERROR collecting test/units/cli/test_galaxy.py ___________________________________________________
test/units/cli/test_galaxy.py:29: in <module>
    from ansible.compat.tests.mock import call, patch
E   ImportError: cannot import name call
_______________________________________ ERROR collecting test/units/contrib/inventory/test_vmware_inventory.py _______________________________________
test/units/contrib/inventory/test_vmware_inventory.py:12: in <module>
    from nose.plugins.skip import SkipTest
E   ImportError: No module named nose.plugins.skip
_________________________________________________ ERROR collecting test/units/errors/test_errors.py __________________________________________________
test/units/errors/test_errors.py:28: in <module>
    from ansible.compat.tests.mock import mock_open, patch
E   ImportError: cannot import name mock_open
_____________________________________________ ERROR collecting test/units/executor/test_play_iterator.py _____________________________________________
test/units/executor/test_play_iterator.py:23: in <module>
    from ansible.compat.tests.mock import patch, MagicMock
E   ImportError: cannot import name patch
___________________________________________ ERROR collecting test/units/executor/test_playbook_executor.py ___________________________________________
test/units/executor/test_playbook_executor.py:23: in <module>
    from ansible.compat.tests.mock import MagicMock
E   ImportError: cannot import name MagicMock
...
```

**Comment by computersalat** [comment]
@mattclay 
I have further added/updated testcases for the distribution_version parsing.
should I add them here ?

**Comment by mattclay** [comment]
@computersalat If they're related to the changes you've made for `get_distribution_SuSE` then yes. Otherwise, open a second PR for those test changes.

**Comment by alikins** [comment]
Looks good to me.

**Pull request merged**
