### PR TITLE
New state on iam_cert module

### PR DESCRIPTION
**Pull request by Lujeni**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/amazon/iam_cert
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

I added a new state: `ping`
Imho it's very useful to retrieve informations about a certificate without manipulation:
- check the expiration date and trigger something...
- retrieve the arn path to create an aws elb with https...
###### good

```
19:54 $ python ansible/hacking/test-module -m ./ansible-modules-core/cloud/amazon/iam_cert.py -a "name=xxx.com state='ping'"
***********************************
RAW OUTPUT

{"upload_date": "2015-03-16T09:36:04Z", "name": "xxx.com", "expiration_date": "2016-09-18T05:47:53Z", "changed": false, "cert_body": "-----BEGIN CERTIFICATE-----\n\nIwQYMBaAFGtpKwm\neO9Z9uifJ+JMspQ39UlTH+t2K+X9IseqwfNA\n-----END CERTIFICATE-----", "invocation": {"module_args": {"profile": null, "new_name": null, "dup_ok": null, "new_path": null, "name": "mmtro.com", "security_token": null, "state": "ping", "region": null, "aws_secret_key": null, "aws_access_key": null, "cert": null, "key": null, "ec2_url": null, "path": "/", "validate_certs": true, "cert_chain": null}}, "cert_path": "/cloudfront/xxx.com/", "arn": "arn:aws:iam::xxx:server-certificate/cloudfront/xxx.com/xxx.com"}


***********************************
PARSED OUTPUT
{
    "arn": "arn:aws:iam::xxxserver-certificate/cloudfront/xxx.com/xxx.com", 
    "cert_body": "-----BEGIN CERTIFICATE-----\/\n41W8XFek9i9WpbFROeqZaZEtIsnZ3c5iQq7kY5k4WkykQKDgpWSOqPLhjsZzAsfb\neO9Z9uifJ+JMspQ39UlTH+t2K+X9IseqwfNA\n-----END CERTIFICATE-----", 
    "cert_path": "/cloudfront/xxx.com/", 
    "changed": false, 
    "expiration_date": "2015-09-18T05:47:53Z", 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "cert": null, 
            "cert_chain": null, 
            "dup_ok": null, 
            "ec2_url": null, 
            "key": null, 
            "name": "xxx.com", 
            "new_name": null, 
            "new_path": null, 
            "path": "/", 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "state": "ping", 
            "validate_certs": true
        }
    }, 
    "name": "xxx.com", 
    "upload_date": "2015-03-16T09:36:04Z"
}
```
##### fail

```
19:54 $ python ansible/hacking/test-module -m ./ansible-modules-core-lujeni/cloud/amazon/iam_cert.py -a "name=ansible.com state='ping'"
***********************************
RAW OUTPUT

{"invocation": {"module_args": {"profile": null, "new_name": null, "dup_ok": null, "new_path": null, "name": "ansible.com", "security_token": null, "state": "ping", "region": null, "aws_secret_key": null, "aws_access_key": null, "cert": null, "key": null, "ec2_url": null, "path": "/", "validate_certs": true, "cert_chain": null}}, "message": "The Server Certificate with name ansible.com cannot be found.", "changed": false, "name": "ansible.com"}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "cert": null, 
            "cert_chain": null, 
            "dup_ok": null, 
            "ec2_url": null, 
            "key": null, 
            "name": "ansible.com", 
            "new_name": null, 
            "new_path": null, 
            "path": "/", 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "state": "ping", 
            "validate_certs": true
        }
    }, 
    "message": "The Server Certificate with name ansible.com cannot be found.", 
    "name": "ansible.com"
}
```

Thanks

### CODE REVIEW

**Comment by Lujeni** [comment]
Migrated from https://github.com/ansible/ansible-modules-core/pull/3922

**Comment by ryansb** [comment]
This functionality would fit better in a `_facts` module, rather than adding a state on the resource. Can you split this out into an `iam_cert_facts` module instead?

**Comment by Lujeni** [comment]
Hello @ryansb 

Should i migrate all the meta informations in this new file ?

thanks

**Comment by Lujeni** [comment]
@ryansb friendly bump.

**Comment by ryansb** [comment]
By "new meta informations" do you mean the ANSIBLE_METADATA key, or all the extra info about the IAM certificate? Since it'd be a new module, I'd recommend taking a look at existing AWS facts modules to see how they're usually written.

**Comment by sivel** [comment]
There also appears to be a merge conflict, which will require a rebase against the current state of devel, and resolving those merge conflicts.

For guidelines on rebasing a pull request, please see: http://docs.ansible.com/ansible/dev_guide/developing_rebasing.html

**Comment by Lujeni** [comment]
I close this pull request, i will create another one with the `iam_cert_fact`.

Thanks

**Pull request closed without merging**
