### PR TITLE
Updated win_disk_facts module

### PR DESCRIPTION
**Pull request by marqelme**
##### SUMMARY
- Added trimmed option to module win_disk_facts
- Removed required administrator privileges

The trimmed option can be used to reduce the output of the module.
Then only the disk fact details will be displayed but no detailed information about the partitions and volumes of the disk.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_disk_facts

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

```

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @jborean93

**Comment by sivel** [comment]
This needs a rebase.  The PR reports changing 602 files.

**Comment by marqelme** [comment]
Hmm don't know why.
I will open a new request...

**Comment by marqelme** [comment]
Opened new PR #37798

**Pull request closed without merging**
