### PR TITLE
added timestamps to response of asa_command and iosxr_command modules

### PR DESCRIPTION
**Pull request by vaneuk**
##### SUMMARY

Added information about time when command was issued on remote device.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

iosxr_command
asa_command
##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/srv/ansible_modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### ADDITIONAL INFORMATION

**example playbook**
```yaml
- name: collect show commands from devices
  hosts: test_group
  connection: network_cli

  tasks:

    - name: collect show commands
      iosxr_command:
        commands:
          - "show clock"
          - "show run vrf mgmt"
      register: output

    - name: debug task
      debug:
        var: output
```

**before**
```
ok: [R01] => {
    "output": {
        "changed": false, 
        "failed": false, 
        "stdout": [
            "16:23:19.904 MSK Fri Jun 29 2018", 
            "vrf mgmt\n!"
        ], 
        "stdout_lines": [
            [
                "16:23:19.904 MSK Fri Jun 29 2018"
            ], 
            [
                "vrf mgmt", 
                "!"
            ]
        ]
    }
}
```

**after**
```
ok: [R01] => {
    "output": {
        "changed": false, 
        "failed": false, 
        "stdout": [
            "16:24:58.318 MSK Fri Jun 29 2018", 
            "vrf mgmt\n!"
        ], 
        "stdout_lines": [
            [
                "16:24:58.318 MSK Fri Jun 29 2018"
            ], 
            [
                "vrf mgmt", 
                "!"
            ]
        ], 
        "timestamps": [
            "2018-06-29T16:24:58", 
            "2018-06-29T16:24:58"
        ]
    }
}
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/72011/3/tests

**Comment by vaneuk** [comment]
@Qalthos @ganeshrn @gdpak @gundalow @kedarX @ogenstad @privateip @rcarrillocruz @trishnaguha @mattclay 
Hi, could someone kindly take a look at this PR? Thanks!

**Comment by vaneuk** [comment]
@Qalthos @ganeshrn @gdpak @gundalow @kedarX @ogenstad @privateip @rcarrillocruz @trishnaguha @mattclay
Hi, firendly ping ). Could someone take a look at this PR?

**Comment by gundalow** [comment]
Needs rebase https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html

**Pull request closed without merging**
