### PR TITLE
postgresql_db: bugfix 56703

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_db: bugfix of [#56703](https://github.com/ansible/ansible/issues/56703)

caused by [#52985](https://github.com/ansible/ansible/pull/52985), this is just a "reverting" PR of it

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by andytom** [comment]
I think this will mean that we will need to reopen #40424 or create another issue somewhere to fix it.

**Comment by Andersson007** [comment]
@andytom , yep, agree

**Comment by Andersson007** [comment]
Let’s merge this, then I’ll open new one for pg_dump

**Comment by F1rst-Unicorn** [comment]
shipit

**Comment by andytom** [comment]
shipit

**Pull request merged**
