### PR TITLE
win_package - Refactor with msp, appx support

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
This is a massive rewrite of win_package that adds the following

* Easier provider separation that will make it easier to add support for further providers in the future
* Support for MSIX packages
* Support for MSP patches
* Added extra http methods when downloading files (utilises the WebRequest module_utils)
* Deprecates some aliases to simplify the various options
* Deprecate the `username` and `password` options in favour of using become to further simplify the module
* Fix up ignored sanity tests

While this adds support for new providers there are no plans on extending the existing ones by adding more options. If in the future we find that there is a demand for adding more configuration to the MSIX packages then that should be done in a separate module. This is similar to how the `package` module is a generic catch all and the `dnf`, `apt` modules expose options per package manager.

Fixes
* https://github.com/ansible/ansible/issues/22789
* https://github.com/ansible/ansible/issues/35377
* https://github.com/ansible/ansible/issues/40973
* https://github.com/ansible/ansible/issues/43818
* https://github.com/ansible/ansible/issues/45950
* https://github.com/ansible/ansible/issues/50765
* https://github.com/ansible/ansible/issues/58044

Supercedes
* https://github.com/ansible/ansible/pull/50864
* https://github.com/ansible/ansible/pull/58089

Still TODO

- [x] Add tests for MSP packages
- [x] Add tests for MSIX packages
- [x] Extend MSI tests for a per user install context
- [x] Add mock tests for the registry provider with `QuietUninstallString` and `UninstallString` that are quoted
- [x] Fix remaining issues that pop up in CI

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
win_package

### CODE REVIEW

**Comment by jborean93** [comment]
The sanity issues seem to be an actual issue with validate-modules. It currently does not recognise `deprecated_aliases` and existing modules that have this option ignore this test. This should be fixed in a separate PR.

**Comment by tremble** [comment]
@felixfontein FYI, looks like we need to update the schema.  Probably a side effect of the age of sivel's original PR

**Comment by tremble** [comment]
@jborean93 I'd recommend adding the ignore.txt entry.  When the test is fixed it'll generate a separate error warning that the ignore entry should be removed.

**Comment by jborean93** [comment]
@tremble I was planning on updating the schema today and opening a PR for that. That should be done by the time I am finished with this PR.

**Comment by felixfontein** [comment]
@jborean93 great, in that case I won't create a PR for it ;)

**Comment by jborean93** [comment]
@felixfontein @tremble I've opened a PR that adds basic validation for the `deprecated_aliases` option https://github.com/ansible/ansible/pull/66965. Once merged then this PRs sanity checks should no longer fail.

**Comment by jborean93** [comment]
I've manually tested the `username`/`password` options against a Samba server as we can't do that in CI. It brought up some limitations of the New-PSDrive option that was being used so I've changed the code to just call `LogonUser` with `LOGON32_LOGON_NEW_CREDENTIALS` and `ImpersonateLoggedOnUser` to access and copy across the file. This process is still going to be deprecated as it's extra code that isn't needed in the module but at least it will work until it is finally removed.

**Comment by jborean93** [comment]
Just realised I forgot the porting guide entries for the various deprecations added. This will be done with https://github.com/ansible/ansible/pull/67374.

**Pull request merged**
