### PR TITLE
Small update to win_dsc: more explicit module syntax

### PR DESCRIPTION
**Pull request by bielawb**
##### SUMMARY

While working with win_dsc and multiple custom DSC resources (mainly class based) I've noticed few problems:
- class based resource require precise module spec when multiple version are installed and fail without it
- binary resource (File) will not report back module name/version, logic around module name fails for it
- when module_version is specified in the task definition ansible will fail every time (module_version was left in properties passed to the resource(s))

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

win_dsc
##### ANSIBLE VERSION

```
2.3.0.0
```
##### ADDITIONAL INFORMATION

I'm testing win_dsc in the context of Ansible Tower, thus I'm using win_dsc as custom module (2.3) rather than a part of ansible core (2.4).

### CODE REVIEW

**Comment by trondhindenes** [comment]
Thanks for this Bartek, all of this totally makes sense. I realize that we don't have any tests for class/binary-based resources - I'll add a PR later to add at least a binary one.

**Comment by trondhindenes** [comment]
shipit

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
bot_status

**Pull request merged**
