### PR TITLE
prevent permission denied failure

### PR DESCRIPTION
**Pull request by yteraoka**
avoid accessing login user's home directory
#1864
# issuecomment-40570064

### CODE REVIEW

**Comment by jimi-c** [comment]
I believe we have fixed this in `module_utils/basic.py`, where `run_command()` will now chdir appropriately. What version are you running this on, as the issue you reference is extremely old?

**Comment by yteraoka** [comment]
hmm..
This issue occurred with Ansible 1.5.4.

$ ansible --version
ansible 1.5.4

**Comment by yteraoka** [comment]
oh,

in module_utils/basic.py

```
        try:
            # make sure we're in the right working directory
            if cwd and os.path.isdir(cwd):
                os.chdir(cwd)
```

When destination directory does not exist (first time), this issue occurs.

**Comment by jimi-c** [comment]
Ok thanks, we'll look into it.

**Comment by jimi-c** [comment]
Looking back at this, and I'm unclear where the problem would be. The clone() call should create the directory and then uses that as the cwd= argument to run_command(), so I'm unclear how this would still be failing. Regardless, a better solution would probably be to check the os.access() rights to the cwd rather than doing a blanket switch to `/`. I'm going to go ahead and close this for now, if you'd like to resubmit it based on what I said above feel free. Thanks!

**Pull request closed without merging**
