### PR TITLE
Return name of datadisk in azure_rm_virtualmachine_info

### PR DESCRIPTION
**Pull request by stawii**
List of attached data disks should return disks names too.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_virtualmachine_facts

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@haiyuazhang Change small, review_need! Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang @gavinfish review need

**Comment by Fred-sun** [comment]
ready_for_review

**Review by gavinfish — APPROVED** [review]
shipit

**Comment by Fred-sun** [comment]
@stawii Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Pull request closed without merging**
