### PR TITLE
ios_facts: CDP Support

### PR DESCRIPTION
**Pull request by jeanders**
CDP support for ios_facts

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/janderson/git/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### CODE REVIEW

**Comment by gundalow** [comment]
@jeanders Thank you for this PR, GitHub tells me this is your first contribution, so double thanks :)

To reduce the change of regressions all new Network features added in 2.4 we require tests to be added.

The test could be a unit, or integration tests.

**Testing Expectations for Network Modules**
In an effort to ensure the highest quality of network modules, all contributions must now include unit tests to exercise each feature of the module. Additionally, do to the nature of mocked interfaces unit tests use, network modules should also include integration tests. The integration tests should be runnable against supported versions of network devices as well as their virtual machine images or containers if available.

Examples of existing unit tests can be found in https://github.com/ansible/ansible/tree/devel/test/units
Examples of existing integration tests can be found in https://github.com/ansible/ansible/tree/devel/test/integration

http://docs.ansible.com/ansible/dev_guide/testing_integration.html#network-tests

**Comment by jeanders** [comment]
@gundalow Hello there. 

I'm running into some difficulties with the unit tests. It seems ios_facts doesn't currently have any tests, and I'm a bit in over my head trying to create a new test section for the whole thing.

**Comment by gundalow** [comment]
@jeanders Apologies, I must have missed your last message in the sea of GitHub email.

If you want to join `#ansible-network` on Freenode IRC someone there should be able to guide you though the process

**Comment by gundalow** [comment]
@jeanders We've discussed this internally and since we don't have any unit test for `ios_facts` we don't expect you to add grown up unit tests.

If you could please rebase this PR then I'll merge it. Thanks in advance.

**Comment by gundalow** [comment]
@jeanders http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html should give you guidance on how to rebase.

Remember to back up the file first :)

**Comment by gundalow** [comment]
@jeanders Would you be able to rebase this?

**Comment by jeanders** [comment]
@gundalow Sorry for the delay. I think I have this rebased now.

Thanks!

**Comment by rcarrillocruz** [comment]
@jeanders can you please rebase? The PR has conflicts due to changes on devel.

**Comment by gundalow** [comment]
@jeanders Could you please rebase, and test.
We will be calling feature freeze for 2.4.0 in a few hours.

**Comment by gundalow** [comment]
@jeanders Any chance you could take a look at this?

**Comment by gundalow** [comment]
not made the cut for `2.4.0`. I think this would be a good feature to get in, so change milestone to `2.5` so we track it.

**Comment by gundalow** [comment]
@jeanders Can you please rebase this so we can merge

**Comment by gundalow** [comment]
We will move forward with https://github.com/ansible/ansible/pull/49129

**Pull request closed without merging**
