### PR TITLE
Remove dev_guide stubs

### PR DESCRIPTION
**Pull request by mariolenz**
##### SUMMARY
I think it's time to remove some Developer Guide stubs.

##### ISSUE TYPE
- Docs Pull Request

##### ADDITIONAL INFORMATION
ansible-community/community-topics#91

_edit:_

I also think the Cisco ACI dev guide should be removed. They've had enough time to move it to their collection but didn't: CiscoDevNet/ansible-aci#298

I've added a second commit to do this. I don't think this legacy stuff should be kept in the ansible-core repository.

### CODE REVIEW

**Comment by mariolenz** [comment]
@samccann Should I open an issue somewhere to discuss this PR, for example in [ansible/docsite](https://github.com/ansible/docsite)? Or should we discuss it here?

**Comment by mariolenz** [comment]
BTW, the link in `docs/docsite/rst/dev_guide/platforms/openstack_guidelines.rst` seems to be broken.

**Comment by samccann** [comment]
The thoughts right now:
1 - PR looks good
2 - Will wait until Jan 30 to merge, giving the collection owner time to respond
3 - Will not put redirects in place. Traffic to these pages are minescule overall.

**Comment by samccann** [comment]
Thanks @mariolenz !

**Comment by mariolenz** [comment]
> Thanks @mariolenz !

You're welcome :-)

**Pull request merged**
