### PR TITLE
WIP: Retry prepare_iosxr_tests setup

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Retry initial socket connection with prepare_iosxr_tests

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible-test network integration for iosxr

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 57562b0280a3f1ba7bf663f8f3f7f71562d6ef3d

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by pabelanger** [comment]
Marking WIP, as this seems to still not fix our network_cli issues

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 46e35f3fb5a35827e9a535c1b3b7fc400e227056

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 8121380cb2931fc3d499e2ce238be20cc5d0e206

**Pull request closed without merging**
