### PR TITLE
Stacki inv and mod

### PR DESCRIPTION
**Pull request by bbyhuy**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- stacki_host

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/vagrant/automata_modules/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Stacki inventory script to dynamically get node information along with a module to interact with front-end Stacki node to add/remove/re-image nodes. 

```
root@vagrant-ubuntu-trusty-64:/home/vagrant/automata_modules/inventory# ./stacki.py --list
{
    "all": {
        "hosts": [
            "192.168.200.50", 
            "192.168.200.51"
        ]
    }, 
    "backends": {
        "hosts": [
            "192.168.200.51"
        ]
    }, 
    "_meta": {
        "hostvars": {
            "test-1": {
                "box": "default", 
                "installaction": "install", 
                "runaction": "os", 
                "interfaces": [
                    {
                        "network": "private", 
                        "default": true, 
                        "ip": "192.168.200.51", 
                        "vlan": null, 
                        "host": "test-1", 
                        "module": null, 
                        "mac": "08:00:27:C7:10:D1", 
                        "interface": "enp0s17", 
                        "options": null, 
                        "channel": null, 
                        "name": null
                    }, 
                    {
                        "network": null, 
                        "default": null, 
                        "ip": null, 
                        "vlan": null, 
                        "host": "test-1", 
                        "module": null, 
                        "mac": "08:00:27:43:4b:51", 
                        "interface": "enp0s8", 
                        "options": "dhcp", 
                        "channel": null, 
                        "name": null
                    }
                ], 
                "appliance": "backend", 
                "cpus": 1, 
                "rank": "0", 
                "ansible_host": "192.168.200.51", 
                "host": "test-1", 
                "rack": "0"
            }, 
            "stacki": {
                "box": "default", 
                "installaction": "install", 
                "runaction": "os", 
                "interfaces": [
                    {
                        "network": "private", 
                        "default": true, 
                        "ip": "192.168.200.50", 
                        "vlan": null, 
                        "host": "stacki", 
                        "module": null, 
                        "mac": "08:00:27:e3:b4:5d", 
                        "interface": "enp0s8", 
                        "options": null, 
                        "channel": null, 
                        "name": "stacki"
                    }
                ], 
                "appliance": "frontend", 
                "cpus": 1, 
                "rank": "0", 
                "ansible_host": "192.168.200.50", 
                "host": "stacki", 
                "rack": "0"
            }
        }
    }, 
    "frontends": {
        "hosts": [
            "192.168.200.50"
        ]
    }
}

```

### CODE REVIEW

**Comment by thaumos** [comment]
@bbyhuy, I'd like to ask if you could submit the dynamic inventory and module as two separate pull requests.

Also, are the Stacki folks aware of your submission?  can we get one of them to +1 any of the PRs?

**Comment by bbyhuy** [comment]
@thaumos, sure, and yes they are aware.

**Comment by thaumos** [comment]
Great! Could you tag a couple of them on your PR's for them to test?  Thanks @bbyhuy

**Comment by bsanders** [comment]
@thaumos @bbyhuy We're (Stacki Devs) definitely aware (and been eagerly awaiting its arrival).  We haven't had a chance to review it but I'll put it on my list for this week.

**Comment by bbyhuy** [comment]
split into 
[#19517 - Inventory](https://github.com/ansible/ansible/pull/19517)
[#19518 - Host Module](https://github.com/ansible/ansible/pull/19518)

**Pull request closed without merging**
