### PR TITLE
[2.9] Fix docs issues in aws_s3_bucket_info and ec2_vpc_vpn

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of https://github.com/ansible-collections/community.aws/pull/47

Fixes the docs that broke ansible-doc (see #69031).

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
aws_s3_bucket_info
ec2_vpc_vpn

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @jillr @acozine @samccann

**Comment by felixfontein** [comment]
Added a backport of ansible-collections/community.aws#55, which fixes more of the same docs problems for AWS modules.

**Review by jillr — COMMENTED** [review]
LGTM, thanks @felixfontein!

**Comment by felixfontein** [comment]
@jillr @acozine thanks for reviewing and merging!

**Pull request merged**
