### PR TITLE
inventory inheritence: add new parent inventory option.

### PR DESCRIPTION
**Pull request by Yannig**
##### SUMMARY
This is a feature idea about inventory inheritance.

Let's take an existing plateform with a huge quantity of variables/parameters. You don't wan't to copy this into the new plateform but instead just want to change the ini file with different server. This option let you specify additional directories where you store your vars directories in order to reuse them.

There's an example in the **test/integration/inventory_inheritence** directory with the following content:
- **simple_inventory/hosts**: simple host file. No vars specified
- **inherit1/group_vars/all**: contain 2 vars declaration (a and b) with 'inherit1' within
- **inherit2/group_vars/all**: contain only a with value 'inherit2'

Let's run some examples:
- Run ansible to retrieve a var value that does not exist: **ansible -m debug -a "msg='a={{a}} b={{b}}'" -i simple_inventory/hosts localhost**

``` yaml
localhost | FAILED! => {
    "failed": true, 
    "msg": "ERROR! 'a' is undefined"
}
```
- Now, specify a parent directory **ansible -m debug -a "msg='a={{a}} b={{b}}'" -p inherit1 -i simple_inventory/hosts localhost**:

``` yaml
localhost | SUCCESS => {
    "changed": false, 
    "msg": "a=inherit1 b=inherit1"
}
```
- And with additional parent directory **ansible -m debug -a "msg='a={{a}} b={{b}}'" -p inherit1:inherit2 -i simple_inventory/hosts localhost**:

``` yaml
localhost | SUCCESS => {
    "changed": false, 
    "msg": "a=inherit2 b=inherit1"
}
```

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/cli/__init__.py
lib/ansible/cli/adhoc.py
lib/ansible/cli/playbook.py
lib/ansible/constants.py
lib/ansible/inventory/__init__.py
test/integration/inventory_inheritence/inherit1/group_vars/all
test/integration/inventory_inheritence/inherit2/group_vars/all
test/integration/inventory_inheritence/simple_inventory/hosts
test/integration/inventory_inheritence/test_inheritence.yml

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by Yannig** [comment]
@bcoca @jimi-c, is there anything I can do about this PR to get it merged into next version of Ansible?

**Comment by jkarneges** [comment]
This would be great to see. I'm looking to separate out some variables, such as `ansible_ssh_private_key_file`, so that the user can supply his own key somewhere without the key having to live in the ansible tree, and without hardcoding the location of the key. In fact the concept of externalizing variables is in the documentation:
http://docs.ansible.com/ansible/playbooks_variables.html#variable-file-separation

Unfortunately, the use of `vars_files` is limited in that it only works within the context of a playbook. Simple ansible commands (e.g. `ansible -m ping`) can't see such vars, which can be a problem when fundamental variables like `ansible_ssh_private_key_file` are needed.

**Comment by Yannig** [comment]
@jkarneges: As you can see, this PR is a little bit old and does not seems to shake a lot of people.

I have managed to get this capabilities with a shell script that is doing this copy and merge into a tmp dir before calling ansible.

Hope it helps.

**Comment by bcoca** [comment]
So after merging #23001 I think this might be easier as a new vars plugin

**Comment by calfonso** [comment]
Closing based upon @bcoca comment.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request closed without merging**
