### PR TITLE
Fixup VMware module docs issues

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
Fix the docs fragments and a few other obvious things to stop new vmware modules needing ignore rules

Also update `ignore.txt` which had some entries missing. Possible bug in `ansible-test` that will be looked at separatly.

##### ISSUE TYPE
 - Bugfix Pull Request
 - Docs Pull Request

### CODE REVIEW

**Comment by gundalow** [comment]
Todo: 
update ignore.txt
cherry-pick

**Comment by gundalow** [comment]
Todo: 
update ignore.txt
cherry-pick

**Comment by Akasurde** [comment]
@gundalow ignore these CI failures, as these module arguments were missing since inception.

**Comment by gundalow** [comment]
ready_for_review
Only issues are the `version_added` which are because I'm documenting options that already existed

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by mattclay** [comment]
I've restarted CI for this PR now that the validate-modules test has been updated.

**Pull request merged**
