### PR TITLE
fix scaleway user data tests

### PR DESCRIPTION
**Pull request by abarbare**
##### SUMMARY

Use environement variable instead of hard coded value for scaleway user data tests

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

scaleway_user_data
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (fix-user-data 686ea77667) last updated 2018/10/06 12:08:53 (GMT +200)
  config file = /Users/abarbare/.ansible.cfg
  configured module search path = [u'/Users/abarbare/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/abarbare/Documents/ansible/lib/ansible
  executable location = /Users/abarbare/Documents/ansible/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

### CODE REVIEW

**Comment by abarbare** [comment]
bot_status

**Comment by jborean93** [comment]
@abarbare seems reasonable enough, is there a reason why the region has changed as well?

**Comment by abarbare** [comment]
@jborean93 The region changed to match all the other tests which are executed on AMS.

**Comment by jborean93** [comment]
Cool thanks for the explanation.

**Pull request merged**
