### PR TITLE
Added metadata support to s3 module

### PR DESCRIPTION
**Pull request by jakekreider**
Created per discussion in [mailing list thread](https://groups.google.com/forum/#!topic/ansible-project/8TgM8IkwEUs).  Updates S3 module to have optional `metadata` parameter to pass to objects during PUTs.

### CODE REVIEW

**Comment by pas256** [comment]
I would like to see 1 more example to show multiple metadata elements can be added. Otherwise, this looks good to me.

**Comment by jakekreider** [comment]
@pas256  Added multiple metadata example per request; please let me know if anything else is needed.

**Comment by mpdehaan** [comment]
version_added parameter to docs needs to be added, @jimi-c can you take care of doing that and merging?

Thanks!

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
