### PR TITLE
Rename 'customvalues' into 'fields' in the interface

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Because both the vCenter API and the vCLI scripts call these entities
*fields* I am inclined to also call it like this in our vmware_guest
interface.

The old vSphere client also calls them attributes in the properties
pane, but in the default VM view they are simply shown as part of the
Annotations. Not sure what the new web gui calls these.

More info in:
https://github.com/ansible/ansible/pull/20052#issuecomment-271729201

### CODE REVIEW

**Comment by dagwieers** [comment]
@nerzhul @jctanner

**Comment by nerzhul** [comment]
@dagwieers customvalues is the vmomi interface name, and it's called attribute in vCenter interface. Thanks VMware to keep names consistent... :(
Fields seems good but i tend to prefer customfields

**Comment by dagwieers** [comment]
@nerzhul I understand where the name comes from, there is indeed an object property customValue of type customFieldValue, but that's more an incidental name IMO. They couldn't call both the type and the instance customFieldValue. (Bad naming on VMware's part, once again)
https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.ManagedEntity.html
https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.CustomFieldsManager.Value.html

I don't mind `customfields:`, except that there are no other fields than custom fields, so I tend to think the "custom" part is unneeded and I prefer shorter names (hence `fields:`) if they don't loose meaning. But no objections. Another option is `custom_fields:`.

Faites vos jeux !

**Comment by dagwieers** [comment]
PS I know that these user interface decisions are boring and based on (different) taste. But we've got only one chance of doing it right. There's no guarantee we are doing the right thing either, but at least we tried our best :-D

And I usually call on @bcoca to give his expert opinion on taste !

**Comment by nerzhul** [comment]
custom_fields seems good for me

**Comment by bcoca** [comment]
here is where aliases make this easy, im fine with the change but add an alias to the other name.

**Comment by dagwieers** [comment]
@bcoca: ok, but it hasn't been exposed (or maybe only a day for people running devel branch) so I'd rather not do a (useless in this case) alias. Do I have to ?

**Comment by bcoca** [comment]
be nice!

**Comment by dagwieers** [comment]
ok

**Comment by bcoca** [comment]
no need to close, just add alias (2 lines change)

**Pull request closed without merging**
