### PR TITLE
Win region module

### PR DESCRIPTION
**Pull request by jborean93**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
win_region

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
Added win_region module to change the windows region/format and unicode settings of a Windows server.

### CODE REVIEW

**Comment by mattclay** [comment]
@jborean93 It looks like [Get-WinHomeLocation](https://technet.microsoft.com/en-us/library/dn375326%28v=wps.620%29.aspx) requires at least Windows Server 2012.

That would explain why the [tests](https://app.shippable.com/runs/584bec54c4749a0f0031a6b3/5/tests) are failing for 2008 and 2008 R2.

**Comment by jborean93** [comment]
Thanks @mattclay I've been trying to setup a local Windows host to test out a replacement for Get-WinHomeLocation and during the process it has made we wonder what the actual version and specs each of the servers have. From my guesses I thought it was;
* 2008 - 3.0
* 2008 R2 - 3.0
* 2012 - 3.0
* 2012 R2 - 4.0

Am I correct in this assumption, is there somewhere where this is documented?

**Comment by mattclay** [comment]
@jborean93 Your assumption on PowerShell versions is correct. We're using the standard EC2 Windows AMIs for our CI tests, and those are the default versions provided. This isn't documented anywhere yet, but I'll be sure to include it in the revised documentation I'm working on for our test infrastructure.

**Comment by jborean93** [comment]
@mattclay I've updated the tests and module to support pre Server 2012 hosts and have gotten a passing build.

**Comment by jborean93** [comment]
ready_for_review

**Comment by dagwieers** [comment]
If you rebase, it's almost ready to be shipped.
I do think we need integration tests for all modules to test idempotency and check-mode.

**Comment by jborean93** [comment]
Thanks @dagwieers I'll rebase and quickly add check mode with tests now that I know how thanks to your reference module :). Was there a particular test you thought was missing in regards to ifempotency checks?

**Comment by dagwieers** [comment]
@jborean93 Clearly I am mixing up modules. You have plenty of integration tests. Well done !

**Comment by jborean93** [comment]
@dagwieers this branch has been rebased and updated to support check mode with tests. The shippable has failed due to a random linux issue not related to this change. The windows tests passed fine.

**Review by dagwieers — APPROVED** [review]

**Comment by dagwieers** [comment]
shipit

**Comment by jhawkesworth** [comment]
shipit

**Comment by jborean93** [comment]
bot_status

**Comment by dagwieers** [comment]
shipit

**Comment by jborean93** [comment]
Looks like the bot doesn't like you @dagwieers :(

REMOVED -jctanner

**Comment by jborean93** [comment]
@dagwieers @jhawkesworth @nitzmahone I had to merge in some changes due to a conflict, nothing else changed but hoping someone would be able to merge this in.

**Comment by jborean93** [comment]
bot_status

**Comment by dagwieers** [comment]
shipit

**Comment by jborean93** [comment]
Hey @dagwieers it seems like your shipits are not counting towards windows modules. According to @gundalow 

```
<gundalow> hum Dag isn't listed as a maintainer in that namespace
<gundalow> which is why only j hawkesworth is counted
```

**Comment by jborean93** [comment]
Hey @nitzmahone would you be able to have a quick look through when you get some time and hopefully merge it in before the release. @jhawkesworth has had a look through before as well as @dagwieers but unfortunately Dag's shipits don't count to Windows modules it seems.

**Comment by jborean93** [comment]
@jhawkesworth looks like I lost your ship it after dealing with a merge are you able to have a look though?

@JimFicarra if you have any time it would be appreciated if you could have a look through.

**Comment by jhawkesworth** [comment]
shipit

**Comment by jhawkesworth** [comment]
bot_status

**Pull request merged**
