### PR TITLE
extend plugin loader skip list to blacklist_exts

### LINKED ISSUE #22268: Wrong file used as module
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 7018aa3316) last updated 2017/03/03 14:56:50 (GMT -400)
```

##### OS / ENVIRONMENT

linux

##### SUMMARY

An emacs backup file `aws.py~` in the module directory is used in preference to a sibling file called `aws`.

##### STEPS TO REPRODUCE

```
mkdir ansible-bug
cd ansible-bug
cat > playbook.yaml <<EOF
---
- hosts: localhost
  connection: local

  tasks:
    - aws: {}
EOF
cat > aws <<EOF
#!/usr/bin/python
from ansible.module_utils.basic import AnsibleModule
module = AnsibleModule({})
module.exit_json(changed=False)
EOF
cat > aws.py~ <<EOF
#!/usr/bin/python
from ansible.module_utils.basic import AnsibleModule
module = AnsibleModule({})
module.exit_json(changed=True)
EOF
ansible-playbook -vvvv -i localhost, -M . playbook.yaml
```

##### EXPECTED RESULTS

`changed=0`

##### ACTUAL RESULTS

`changed=1`

```
(conf-mgmt) aaron:ansible-bug> ansible-playbook -vvvv -i localhost, -M . playbook.yaml
No config file found; using defaults
Set default localhost to localhost
Loading callback plugin default of type stdout, v2.0 from /home/aaron/Dropbox/newscred-src/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: playbook.yaml *************************************************************************************************************
1 plays in playbook.yaml

PLAY [localhost] ********************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************
Using module file /home/aaron/Dropbox/newscred-src/ansible/lib/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: aaron
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/aaron/.ansible/tmp/ansible-tmp-1488571336.12-276444930035913 `" && echo ansible-tmp-1488571336.12-276444930035913="` echo /home/aaron/.ansible/tmp/ansible-tmp-1488571336.12-276444930035913 `" ) && sleep 0'
<localhost> PUT /tmp/tmpb2iKjX TO /home/aaron/.ansible/tmp/ansible-tmp-1488571336.12-276444930035913/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/aaron/.ansible/tmp/ansible-tmp-1488571336.12-276444930035913/ /home/aaron/.ansible/tmp/ansible-tmp-1488571336.12-276444930035913/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/aaron/.ansible/tmp/ansible-tmp-1488571336.12-276444930035913/setup.py; rm -rf "/home/aaron/.ansible/tmp/ansible-tmp-1488571336.12-276444930035913/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [aws] **************************************************************************************************************************
task path: /home/aaron/scratch/ansible-bug/ansible-bug/playbook.yaml:6
Using module file /home/aaron/scratch/ansible-bug/ansible-bug/aws.py~
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: aaron
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/aaron/.ansible/tmp/ansible-tmp-1488571336.5-232883384061572 `" && echo ansible-tmp-1488571336.5-232883384061572="` echo /home/aaron/.ansible/tmp/ansible-tmp-1488571336.5-232883384061572 `" ) && sleep 0'
<localhost> PUT /tmp/tmp5HzZiD TO /home/aaron/.ansible/tmp/ansible-tmp-1488571336.5-232883384061572/aws.py~
<localhost> EXEC /bin/sh -c 'chmod u+x /home/aaron/.ansible/tmp/ansible-tmp-1488571336.5-232883384061572/ '"'"'/home/aaron/.ansible/tmp/ansible-tmp-1488571336.5-232883384061572/aws.py~'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python '"'"'/home/aaron/.ansible/tmp/ansible-tmp-1488571336.5-232883384061572/aws.py~'"'"'; rm -rf "/home/aaron/.ansible/tmp/ansible-tmp-1488571336.5-232883384061572/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {}
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP **************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

Note that when I originally tried to build this test case, I called the module files `my_module` and `my_module.py~` instead of `aws` and `aws.py~`, and it failed to demonstrate the bug. My guess is that it has something to do with the way filenames are hashed by the filesystem -- ansible-playbook uses whichever one comes first in the directory listing. If that's the case then the test might work differently for someone using a different filesystem. As a variant that shouldn't depend on filesystem implementation, try deleting the file `aws`. Then ansible-playbook unambiguously uses `aws.py~` as a module, which I would argue is incorrect behavior.

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

fixes #22268

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

plugin loader

##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Comment by abadger** [comment]
Can't do it this way.  Probably need to have blacklist_extensions +
(.pyc,.pyo)

Pyc and pyo are wanted everywhere except modules and module_utils

**Comment by bcoca** [comment]
No, they are not wanted in any of the places we use BLACKLIST_EXTS as they are part of that tuple. Your change would be redundant.

**Comment by abadger** [comment]
@bcoca that's the problem.  .pyc and .pyo should not be part of BLACKLIST_EXTS.  We want to be able to load plugins from .pyc and .pyo.  Only modules and module_utils want to blacklist those.

**Comment by bcoca** [comment]
@abadger i'm confused, i'm not adding pyc/pyo anywhere, they are already in both places, I'm adding the 'rest' of BLACKLIST_EXTS ( '.swp', '.bak', '~', '.rpm', '.md', '.txt') to this. 

plugin loader ALREADY skipped pyc/pyo and other things using BLACKLIST_EXTS already skip pyc/pyo (inventory scripts for example). Your first comment ENSURES pyo/pyc are skipped here ... not sure what you are trying to say.

**Pull request closed without merging**
