### PR TITLE
Rename checkpoint to check_point due to legal reasons, fix #61145

### LINKED ISSUE #61145: wrong section title, very urgent
Hi,
the section title in the ansible-network-checkpoint documentation is `Checkpoint`
This is a link for the section-title: https://docs.ansible.com/ansible/devel/modules/list_of_network_modules.html#checkpoint
Due to legal issues, we need to change the section title to `Check_Point` (we want to change only the title)
(because there is another company called checkpoint)
**This is very urgent**, cause the feature freeze is in a week.
Thanks
@justjais @crosslogic @chkp-amiads

### PR DESCRIPTION
**Pull request by liquidat**
##### SUMMARY

Fixes #61145 due to legal reasons

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

network/checkpoint module path

##### ADDITIONAL INFORMATION

As mentioned in the issue, there are two companies out there, "checkpoint" and "Check Point". The modules here touch software of the company "Check Point", not "checkpoint", henve the need to rename the path.

As discussed with @gundalow and @thaumos this change does not brake any playbook functionality but mainly changes how the name of the company is displayed in the documentation.

### CODE REVIEW

**Review by gundalow — CHANGES_REQUESTED** [review]
`test/sanity/ignore.txt` needs updating to point to the new directory name for `checkpoint_object_facts.py`

**Comment by gundalow** [comment]
`git mv test/units/modules/network/checkpoint test/units/modules/network/check_point`
Also the `import` contained within there need updating.

**Comment by liquidat** [comment]
I fixed all outstanding issues, the checks have passed as well.

**Comment by liquidat** [comment]
@gundalow Can you please verify if/that your requested changes were addressed?

**Review by gundalow — APPROVED** [review]
Looks good form a technical (ie non legal) review

**Pull request merged**
