### PR TITLE
Fixes#27314 - Handled issue in parsing "exit" in dellos6 running config. 

### LINKED ISSUE #27314: Issue in handling of "exit" in parsing dellos6 running config
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible.module_utils.dellos6

##### ANSIBLE VERSION
```
ansible 2.3.2.0 (stable-2.3 9d435fd47b) 
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides


```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by abirami-n**
##### SUMMARY
Included changes to handle "exit" in dellos6 running-config.
Fixes #27314 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ansible.module_utils.dellos6

##### ANSIBLE VERSION
```
ansible 2.3.2.0 (stable-2.3 9d435fd47b) 
config file = /etc/ansible/ansible.cfg 
configured module search path = Default w/o overrides
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by abirami-n** [comment]
The same changes has to be back-ported to 2.2.

**Comment by gundalow** [comment]
@abirami-n Stable-2.2 only gets security fixes now.

Is this broken in `devel` (2.4)
If so please raise this PR against the `devel` branch` and we will cherry-pick it into `stable-2.3`

needs_info

**Comment by gundalow** [comment]
@skg-net FYI

**Comment by skg-net** [comment]
@abirami-n Please fix against devel and let @gundalow know to backport it to 2.3

@gundalow What is recommendation to handle customer who have not migrated to 2.3 yet and wants the fixes in 2.2?

**Comment by gundalow** [comment]
@skg-net I'd suggest they upgrade to 2.3 :) 
Or wait for 2.4 and upgrade to that. 

You *could* ask them to apply this patch locally (after you've confirmed it works correctly), though that may increase your support overhead.

**Comment by gundalow** [comment]
Please update this PR to be against `devel` and I will put the fix into devel (2.4) and `stable-2.3`

**Comment by abirami-n** [comment]
Closing this PR, since the same has been updated across devel, in the PR #28060

**Pull request closed without merging**
