### PR TITLE
Fix IPv6 addresses getting dropped from hosts list (devel branch)

### PR DESCRIPTION
**Pull request by mcsalgado**
Also see #12329

### CODE REVIEW

**Comment by amenonsen** [comment]
@mcsalgado Could you test PR #12415, please?

**Comment by jimi-c** [comment]
@mcsalgado, the PR above from @amenonsen would supplant this, correct?

**Comment by mcsalgado** [comment]
@jimi-c yes

**Comment by jimi-c** [comment]
@mcsalgado ok great, I'll go ahead and close this as we review that PR.

Thanks!

**Pull request closed without merging**
