### PR TITLE
Fix regression introduced in b77abd0491 causing bug in inventory modu…

### PR DESCRIPTION
**Pull request by ghost**
Fix regression introduced in b77abd0491 causing bug in inventory modules which break functionality in user setting  use_contrib_script_compatible_sanitization  parameter.

Effecting all versions since V2.8.5

##### SUMMARY

Reverted commit b77abd0491

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

amazon.aws.aws_ec2

##### ADDITIONAL INFORMATION

Inventory module usually have setting  "use_contrib_script_compatible_sanitization"
The commit I reverted cause this setting to have no effect 

```paste below

```

### CODE REVIEW

**Comment by sivel** [comment]
Oh, the inventory plugins are being naughty!  They are overriding a private method of the base class:

https://github.com/ansible/ansible/blob/321606b731738a2410ec7e4be8fa5304de1b349b/lib/ansible/plugins/inventory/aws_ec2.py#L617-L618

See https://github.com/ansible/ansible/commit/3e52a6a693f33552766f45b3736728d3d8fe2da3#

**Comment by msh111** [comment]
> 
> 
> Looking at this, I'm not sure what the goal is with reverting this change.
> 
> `self._sanitize_group_name` is an alias of `to_safe_group_name` which accepts no arguments, but calls:
> 
> ```
> original_safe(name, force=True, silent=True)
> ```
> 
> The change this is reverting calls `original_safe(name, force=True)` where `silent` defaults to `False`
> 
> So the behavior is the same, only with a change that it will display the warning.
> 
> Per the documentation of the `[aws_ec2](https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html)` inventory plugin,
> 
> > For [use_contrib_script_compatible_sanitization] to work you should also turn off the `TRANSFORM_INVALID_GROUP_CHARS` setting, otherwise the core engine will just use the standard sanitization on top
> 
> I must be missing something if you validated this change works.

Yes I validated it works like supposed to

**Review by s-hertel — APPROVED** [review]
Here's some context about why this bit of code was changed and a suggested fix to keep the warning in place https://github.com/ansible/ansible/pull/69702#discussion_r443824793. In 2.8 composed groups became sanitized (silently) and was considered a "regression" - the warning was a compromise, but it accidentally broke allowing plugins to override.
That being said, 2.8 was a while ago and we probably don't need the warning anymore, so this looks fine to me.

**Comment by s-hertel** [comment]
Thanks for the fix. I'm working on adding some documentation for `_sanitize_group_name` as well.

**Pull request merged**
