### PR TITLE
Add params for doc_fragments/alicloud

### PR DESCRIPTION
**Pull request by lixue323**
##### SUMMARY
Add params for doc_fragments/alicloud.py

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
plugins/doc_fragments/alicloud.py

### CODE REVIEW

**Comment by Akasurde** [comment]
@lixue323 Could you please move this PR to https://github.com/ansible-collections/community.general since alicloud is moved to this repo? Thanks.

needs_info

**Comment by lixue323** [comment]
@Akasurde Why was alicloud moved to another repo?

**Comment by Akasurde** [comment]
With the introduction of Ansible Collections, all community-supported modules, plugins, etc. are moved to `community.general` collection. The development continues but in the new collection repository: https://github.com/ansible-collections/community.general

Links:

- https://groups.google.com/forum/#!msg/ansible-devel/6UAfogEDtG8/wMTgxBGWCgAJ
- https://github.com/ansible-collections/overview/blob/master/README.rst

**Comment by Akasurde** [comment]
Migrated to https://github.com/ansible-collections/community.general/pull/108

**Pull request closed without merging**
