### PR TITLE
Reset persistent connection only if it is active

### LINKED ISSUE #33237: Reset persistent connection fails with socket not present error
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

plugins/strategy/__init__.py

##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

Run junos integration test:

```yaml
$ ANSIBLE_ROLES_PATH=targets ansible-playbook -i inventory.network junos.yaml -vvvv --diff
```

##### ACTUAL RESULTS

```
TASK [Has any previous test failed?] **************************************************************************************************************
task path: /Users/gnalawad/ansible/ganeshrn/ansible/test/integration/junos.yaml:174
skipping: [junos] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
META: ran handlers
META: ran handlers
ERROR! Unexpected Exception, this is probably a bug: socket_path does not exist or cannot be found
the full traceback was:

Traceback (most recent call last):
  File "/Users/gnalawad/ansible/ganeshrn/ansible/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/Users/gnalawad/ansible/ganeshrn/ansible/lib/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/Users/gnalawad/ansible/ganeshrn/ansible/lib/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/Users/gnalawad/ansible/ganeshrn/ansible/lib/ansible/executor/task_queue_manager.py", line 296, in run
    strategy.cleanup()
  File "/Users/gnalawad/ansible/ganeshrn/ansible/lib/ansible/plugins/strategy/__init__.py", line 146, in cleanup
    conn.reset()
  File "/Users/gnalawad/ansible/ganeshrn/ansible/lib/ansible/module_utils/connection.py", line 140, in __rpc__
    response = self._exec_jsonrpc(name, *args, **kwargs)
  File "/Users/gnalawad/ansible/ganeshrn/ansible/lib/ansible/module_utils/connection.py", line 115, in _exec_jsonrpc
    raise ConnectionError('socket_path does not exist or cannot be found')
ConnectionError: socket_path does not exist or cannot be found
```

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

Fixes #33237

Add check to reset connection only is persistent socket
file exist

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

plugins/strategy/__init__.py
##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by trishnaguha — APPROVED** [review]

**Review by privateip — CHANGES_REQUESTED** [review]
Looking at the code path, I think it would be better to wrap this into a `try...except` block instead as there are other reasons the call to `reset()` might fail

**Review by Qalthos — APPROVED** [review]

**Review by Qalthos — CHANGES_REQUESTED** [review]
@privateip makes a good point

**Comment by ganeshrn** [comment]
ready_for_review

**Comment by ganeshrn** [comment]
@privateip @Qalthos Fixed review comments.

**Review by rcarrillocruz — APPROVED** [review]

**Review by privateip — APPROVED** [review]

**Comment by ganeshrn** [comment]
Thank you for review

**Pull request merged**
