### PR TITLE
loop_control "early exit" feature

### LINKED ISSUE #46203: Feature: Allow until-loops on blocks or includes
##### SUMMARY
It would be quite useful if you can loop over more than one single tasks.

For instance if you have to poll a remote system for some progress and at the same time you want to push this progress to another backend, you could be doing:

```yaml
- hosts: localhost
  tasks:
  - name: Start a long-running task
    uri:
      url: https://some-service/v1/put/new_job
      body: { foo: bar }
    register: new_job

  - until: job_status.json.message in ['Finished', 'Failed']
    block:
    - name: Get job status
      uri:
        url: https://some-service/v1/get/new_job
      register: job_status

    - name: Report job status to web service
      uri:
        url: https://backend-system/v1/post/job_status
        body: '{{ job_status.json }}'
```

There are many uses to this.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Core

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

- Feature Pull Request

posisbly fixes #46203 by providing 'until for includes'
##### COMPONENT NAME

core

### CODE REVIEW

**Comment by karstenjakobsen** [comment]
Looks like a very nice way to these kind of loops!

**Comment by nodeselector** [comment]
Not sure that these changes would fix #46203 I tested @bcoca's branch locally with this playbook:

```yml
- hosts: localhost
  gather_facts: false
  tasks:
  - name: testing block looping
    block:
      - debug:
          msg: "{{ item }}"
    loop:
      - 1
      - 2
      - 3
    loop_control:
      until: item > 2
  ```

Which yields:

```
ansible-playbook test/integration/targets/loop_control/block_play.yml
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the
Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any
point.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! 'loop' is not a valid attribute for a Block

The error appears to be in '/Users/jeffmartin/dev/ansible/test/integration/targets/loop_control/block_play.yml': line 4, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: testing block looping
    ^ here
```
Am I missing something?

**Comment by nodeselector** [comment]
Ah I see what I was missing, this fix would only apply to `includes` not `block`. This works great:

```yml
- hosts: localhost
  gather_facts: false
  tasks:
  - name: testing block looping
    include_tasks: block.yml
    loop:
      - 1
      - 2
      - 3
    loop_control:
      until: item > 2
```

**Comment by abdulrabbani00** [comment]
Can you guys please fix this, the people are really hoping for this feature.

**Comment by pini-gh** [comment]
I've had some success using `when` as described [here](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#using-conditionals-in-loops). This is not exactly an `until` or `break` feature, but it can be used for the same purpose.

**Comment by Mohammad-Atif-Khan** [comment]
@bcoca is this still intended to be made a core feature? would be very useful to have, it makes a lot of sense to be able to break out of a loop based on any condition.

**Comment by bcoca** [comment]
probably, but not a priority right now

**Comment by LennertMertens** [comment]
Is this still being worked on?

**Comment by bcoca** [comment]
@LennertMertens it is still on my list, but it is not planned to make it in anytime soon

**Review by s-hertel — APPROVED** [review]

**Pull request merged**
