### PR TITLE
Fix netbox url with string concat

### LINKED ISSUE #46705: Netbox inventory urljoin vs string concat produces different results
##### SUMMARY

lib/ansible/plugins/inventory/netbox.py dynamic plugin uses both urljoin() and simple string concatenation to produce the API urls used to retrieve data.

@sieben 

api_endpoint: http://server/netbox

urljoin() produces http://server/api/dcim/...
string concat produces http://server/netbox/api/dcim/...
urljoin()
[netbox.py line 243](https://github.com/ansible/ansible/blob/3c7a503a53aee8badf4ae3c93d01da8f496fea4c/lib/ansible/plugins/inventory/netbox.py#L243)
`url = urljoin(self.api_endpoint, "/api/dcim/sites/?limit=0")`

string concat
[netbox.py line 314](https://github.com/ansible/ansible/blob/3c7a503a53aee8badf4ae3c93d01da8f496fea4c/lib/ansible/plugins/inventory/netbox.py#L314)
`self.device_url = self.api_endpoint + "/api/dcim/devices/" + "?" + urlencode(query_parameters)`
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Netbox.py dynamic inventory script
##### ANSIBLE VERSION

```paste below
ansible 2.7.0rc4

copied netbox.py from devel
```

##### CONFIGURATION

```paste below
api_endpoint: http://server/netbox
```

##### STEPS TO REPRODUCE

api_endpoint: http://server/base_url

Use netbox dynamic inventory. urljoin behavior is known.
[python-confusions-with-urljoin](https://stackoverflow.com/questions/10893374/python-confusions-with-urljoin)

```yaml

```

##### EXPECTED RESULTS

http://server/netbox/api/dcim/...

##### ACTUAL RESULTS

http://server/api/dcim/...

```paste below

```

### PR DESCRIPTION
**Pull request by heathdbrown**
##### SUMMARY

Fixes #46705

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

- netbox_inventory

##### ADDITIONAL INFORMATION

The fix in #47655 made the problem worse.

The issue was with how urljoin() removes paths from the configuration.

```
>>> from urlparse import urljoin
>>> urljoin('http://netbox.internalurl.com/netbox', '/api/dcim/platforms/?limit=0')
'http://netbox.internalurl.com/api/dcim/platforms/?limit=0'
```
```
>>> urljoin('http://netbox.internalurl.com/netbox', 'api/dcim/platforms/?limit=0')
'http://netbox.internalurl.com/api/dcim/platforms/?limit=0'
```
```
>>> urljoin('netbox.internalurl.com/netbox/', 'api/dcim/platforms/?limit=0')
'netbox.internalurl.com/netbox/api/dcim/platforms/?limit=0'
```

The way the netbox.py is written the api urls are joined but they all have /api and when merged with /netbox overwrites to /api only which is a missing URL and causes 404s.

Fixing this would mean adjusting /api URL fragments to api OR adjusting the netbox.py to not use urljoin() and use string concat.

### CODE REVIEW

**Comment by remyleone** [comment]
If this patch we would need to be sure that there is no trailing slash for the base_url. `//` are not welcomed by netbox AFAIK

**Comment by heathdbrown** [comment]
@sieben What would be the suggestion in handling this?

(I do not have a ton of coding experience) 

Documentation?
Data validation on the api_endpoint?

**Comment by gundalow** [comment]
@heathdbrown if `api_endpoint` ends with a `/` you could trim it that variable is used

**Comment by winem** [comment]
Did a test on our netbox setup and API calls work with any number of slashes (tested with 1-6 out of curiosity) between the domain part and the actual path. A // in the path itself fails with a 404. 

Examples: 
**working:**
- http://netbox.intern//api/virtualization//clusters/
- http://netbox.intern////api/virtualization//clusters/

**not working:** 
- http://netbox.intern/api//virtualization/clusters/
- http://netbox.intern/api/virtualization//clusters/
- http://netbox.intern/api/virtualization//clusters//

**Comment by gundalow** [comment]
@heathdbrown Could you please rebase this so we can get it merged

**Comment by heathdbrown** [comment]
@gundalow did a rebase and I believe we are good, let me know if there is anything else needed.

**Comment by heathdbrown** [comment]
@gundalow I rebased and I believe this ready now.

**Comment by gundalow** [comment]
@Anthony25 @FragmentedPacket @nikkytub @pilou- @sieben could we please get a final review on this?

**Comment by FragmentedPacket** [comment]
I'm not getting the same result, if I use the requests library and set my url to: `http://netbox-demo.org:32768//api/dcim/devices/` I get a 404 error.

We may want to add the following to account for it unless y'all have tested this and it works?:
```
if self.api_endpoint.endswith("/"):
    self.api_endpoint = self.get_option("api_endpoint")[:-1]
else:
    self.api_endpoint = self.get_option("api_endpoint")
```

Thoughts?

**Comment by winem** [comment]
Not entirely sure but I guess there can be edgecases where api_endpoint ends with // due to a typo for example. I would recommend to use api_endpoint.strip('/') to ensure that all slashes will be droped.

**Comment by heathdbrown** [comment]
@FragmentedPacket and @winem thanks for the review. I will add those in, I think it was mentioned earlier on and I forgot about adding that in.

**Comment by heathdbrown** [comment]
@FragmentedPacket, @winem, @gundalow 

The requested logic is now in the netbox plugin to trim the api_endpoint if it has any trailing '/'.

**Comment by FragmentedPacket** [comment]
@heathdbrown Do you mind changing `self.api_endpoint = self.get_option("api_endpoint")[:-1]` to `self.api_endpoint = self.get_option("api_endpoint").strip('/')`

@winem Is correct on it's best to strip all trailing to be on the safe side.

**Comment by heathdbrown** [comment]
@FragmentedPacket, @winem  I updated with the request to do strip('/'), please review.

**Comment by FragmentedPacket** [comment]
Sorry about this. Just reviewing it, might be a little cleaner way.
```
        REMOVE: self.api_endpoint = self.get_option("api_endpoint")
        # Handle extra "/" from api_endpoint configuration and trim if necessary, see PR#49943
        if self.get_option("api_endpoint").endswith("/"):
            self.api_endpoint = self.get_option("api_endpoint").strip('/')
        else:
            self.api_endpoint = self.get_option("api_endpoint")
```

**Comment by heathdbrown** [comment]
@FragmentedPacket that fails as the self.api_endpoint above the if is the first assignment.

After commenting it out the plugin fails.

**Comment by FragmentedPacket** [comment]
@heathdbrown Did you change the if statement to look at the self.get_option?

**Comment by heathdbrown** [comment]
@FragmentedPacket well that was embarrassing. Thanks for the patience. I have included the complete suggestion.

**Comment by winem** [comment]
Imho, there is no need for the `if` if you use `.strip('/')`. Instead you can just use it when you assign the variable. 

`.strip('/')` will neither do anything nor fail if there is no trailing slash. 

`self.api_endpoint = self.get_option("api_endpoint").strip('/')` should just work.

```
>>> api_endpoint='netbox.com/'
>>> api_endpoint.strip('/')
'netbox.com'
>>> api_endpoint='netbox.com////'
>>> api_endpoint.strip('/')
'netbox.com'
>>> api_endpoint='netbox.com'
>>> api_endpoint.strip('/')
'netbox.com'
```

**Comment by heathdbrown** [comment]
@winem updated to your suggestion and removed the if logic.

**Comment by winem** [comment]
Looks good to me!

**Comment by FragmentedPacket** [comment]
@heathdbrown Hey i'm in the same boat as you lol

Looks good to me as well

**Comment by FragmentedPacket** [comment]
@sieben Do you mind looking this over and approving? 2.8 RC stuff starts the 14th of March

**Comment by sieben** [comment]
LGTM

**Comment by sieben** [comment]
@Anthony25 What do you think about it?

**Comment by nikkytub** [comment]
LGTM as well

**Comment by resmo** [comment]
rebuild_merge

**Pull request merged**
