### PR TITLE
win_lineinfile: Clean up and check-mode support

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_lineinfile

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Changes include:
- Add check-mode support
- Use Get-AnsibleParam with -type support
- Replace $result PSObject with normal hash
- Remove trailing semi-colons
- Fix indentation (majority is tabs, few lines using spaces)

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests. Here's one example:

```
 win_lineinfile-hNqQgo / /root/src/github.com/ansible/ansible/test/integration/targets/win_lineinfile/tasks/main.yml:42 / [windows-2012-R2_RTM] windows: win_lineinfile : insert a line at the beginning of the file, and back it up dest={{win_output_dir}}/test.txt, state=present, backup=yes, line=New line at the beginning, insertbefore=BOF

failure: line= is required with state=present

            {
"changed": false, 
"failed": true, 
"msg": "line= is required with state=present"
}
```

Test results here: https://app.shippable.com/runs/58a50eefb195740f00e28575/6/tests

**Comment by dagwieers** [comment]
So the reason Shippable fails is because the line added does not have a trailing CR+LF (18 bytes / fb51fc3bc893d5910b7cd2047a4e420e2dad3d84) whereas before it did (20 bytes / 84faac1183841c57434693752fc3debc91b9195d). However I did not change anything related to trailing newlines. The logic has not been changed AFAICT, `WriteLines()` is intact it basically joins lines using `$linesep`. So if I want to add a trailing CR+LF I need at add an empty line at the end of the list.

So why did it not need that before ? Any Powershell gurus who understands ? Been wasting too much time on this one today.

cc: @johnnysheppard-isode @jhawkesworth @nitzmahone @jborean93 @trondhindenes @brianlloyd 

PS I waited with implementing check_mode support until the backrefs patch #20926 was merged.

**Comment by dagwieers** [comment]
So testing this locally I can confirm that adding line "This is a new file" creates a new file of just 18 bytes (no trailing CR+LF).
```
[dag@moria crombeen]$ ansible -m win_lineinfile -a 'dest=C:\\Windows\\Temp\\ansible.txt create=yes insertbefore=BOF state=present line="This is a new file"' computer51
computer51 | SUCCESS => {
    "backup": "", 
    "changed": true, 
    "encoding": "utf-8", 
    "msg": "line added"
}
[dag@moria crombeen]$ ansible -m win_stat -a 'path=C:\\Windows\\Temp\\ansible.txt' computer51
computer51 | SUCCESS => {
    "changed": false, 
    "stat": {
        "attributes": "Archive", 
        "checksum": "fb51fc3bc893d5910b7cd2047a4e420e2dad3d84", 
        "creationtime": 1487247940.3561456, 
        "exists": true, 
        "extension": ".txt", 
        "filename": "ansible.txt", 
        "isarchive": true, 
        "isdir": false, 
        "ishidden": false, 
        "islink": false, 
        "isreadonly": false, 
        "isshared": false, 
        "lastaccesstime": 1487247940.3561456, 
        "lastwritetime": 1487247940.3561456, 
        "md5": "25289c2b803207cce00cf4b282949750", 
        "owner": "INGEBOUWD\\Administrators", 
        "path": "C:\\Windows\\Temp\\ansible.txt", 
        "size": 18
    }
}
[dag@moria crombeen]$ ansible -m win_shell -a 'Get-Content C:\\Windows\\Temp\\ansible.txt' computer51
computer51 | SUCCESS | rc=0 >>
This is a new file
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
```

However creating the same file using line "This is a new file\r\n", creates the file that the integration tests expect. So how the hell did the integration tests ever work before ? :-/
```
[dag@moria crombeen]$ ansible -m win_lineinfile -a 'dest=C:\\Windows\\Temp\\ansible.txt create=yes insertbefore=BOF state=present line="This is a new file\r\n"' computer51
computer51 | SUCCESS => {
    "backup": "", 
    "changed": true, 
    "encoding": "utf-8", 
    "msg": "line added"
}
[dag@moria crombeen]$ ansible -m win_stat -a 'path=C:\\Windows\\Temp\\ansible.txt' computer51
computer51 | SUCCESS => {
    "changed": false, 
    "stat": {
        "attributes": "Archive", 
        "checksum": "84faac1183841c57434693752fc3debc91b9195d", 
        "creationtime": 1487247940.3561456, 
        "exists": true, 
        "extension": ".txt", 
        "filename": "ansible.txt", 
        "isarchive": true, 
        "isdir": false, 
        "ishidden": false, 
        "islink": false, 
        "isreadonly": false, 
        "isshared": false, 
        "lastaccesstime": 1487248933.07374, 
        "lastwritetime": 1487248933.07374, 
        "md5": "27ae53130ba6968c28e87f3e25d872e3", 
        "owner": "INGEBOUWD\\Administrators", 
        "path": "C:\\Windows\\Temp\\ansible.txt", 
        "size": 20
    }
}
[dag@moria crombeen]$ ansible -m win_shell -a 'Get-Content C:\\Windows\\Temp\\ansible.txt' computer51
computer51 | SUCCESS | rc=0 >>
This is a new file
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
```

**Comment by jborean93** [comment]
I believe @jhawkesworth make a change to win_file where a touch excluded some BOM marks. Could be wrong but this tripped me up on some tests before that failed all of a sudden https://github.com/ansible/ansible/pull/20876

**Comment by dagwieers** [comment]
@jborean93 Hmm, but that only touches **win_file**, and I assume all tests worked fine the past 2 weeks. The integration test that fails is in fact creating a new file using **win_lineinfile** only. I cannot find anything wrong with #20926 either and again I assume all tests worked fine yesterday when that patch was merged.

**Comment by dagwieers** [comment]
I found the problem ! I did not consider empty "content" strings when a new file was created just before. This was part of replacing $false as default string input by $null.

I found this problem while implementing diff-support. So that's a nice addition that will helps us in the future debug this module. This is the second Windows module implementing diff-support ! (win_regedit being the first)

**Comment by dagwieers** [comment]
ready_for_review

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
