### PR TITLE
Grafana dashboard folder and uid missing

### LINKED ISSUE #61685: Folder support for grafana_dashboard
##### SUMMARY

When creating a dashboard, I'd like to assign it to a folder in Grafana.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`grafana_dashboard`

##### ADDITIONAL INFORMATION

Folders in Grafana are used for ACL etc.. When no folder is referenced, the dashboard ends up in the default folder (and can't be moved as it's managed outside of Grafana).

Here's the API related to creating/updating dashboards:
https://grafana.com/docs/http_api/dashboard/

The relevant bit is `folderId`.

For context, here's the folder API (probably a concern for a different module — `grafana_folder`):
https://grafana.com/docs/http_api/folder/

I'd propose something like this and then map `folder_id` to `folderId`. The default is a value of `0`. And then dashboards end up in "General".

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Import Grafana dashboard
      grafana_dashboard:
        grafana_url: http://localhost:3000
        grafana_api_key: "{{ grafana_api_key }}"
        state: present
        folder_id: 0
        message: Updated by ansible
        overwrite: yes
        path: /path/to/mydashboard.json
```

As an additional motivation, I'm a user of a Grafana role. They are planning to deprecate their dashboard management in favour of this module.

Related: https://github.com/cloudalchemy/ansible-grafana/issues/174

### PR DESCRIPTION
**Pull request by seuf**
##### SUMMARY

Ability to assign a dashboard to a folder in Grafana.

Resolves: #61685
Related: cloudalchemy/ansible-grafana#174

rework of the https://github.com/ansible/ansible/pull/61692 PR with idempotent fiw when we try to import a dashboard without `uid` in the json payload.
Thanks @till for your initial work !!

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME  
`grafana_dashboard`

### CODE REVIEW

**Comment by seuf** [comment]
rebased + squashed commits + fixed pep8 lint.

**Comment by till** [comment]
@seuf What do we do with this?

**Comment by seuf** [comment]
We wait for someone with permission to approve this. maybe @rrey, @samdoran or @gundalow can do something ? They already approved some of my previous PR..

**Comment by rrey** [comment]
bot_status

**Comment by till** [comment]
Ping? 😃

**Comment by rrey** [comment]
shipit 

I think you need 2 community review
You should Ping people on ansible-devel IRC Channel

**Comment by till** [comment]
bot_status

**Comment by gundalow** [comment]
Merging as:
* two people have worked on this, thanks @seuf and @till 
* @rrey has reviewed this
* I have no knowledge of Grafana, though change looks sensible

Thank you all!

**Pull request merged**
