### PR TITLE
Update azure_rm_virtualmachine.py

### PR DESCRIPTION
**Pull request by chclaus**
+label: docsite_pr

##### SUMMARY
Add resource_group values in examples of:
- Power On
- Restart

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
azure_rm_virtualmachine

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@chclaus Thank you very much for the contribution! It's very nice for you to correct the documentation.

**Comment by MyronFanQiu** [comment]
@zikalino @yungezz It's a small doc fix. Correct the content in the `EXAMPLE` from `resource_group` to `resource_group: myResourceGroup`. Please review it when you are free. Thanks!

**Review by jeking3 — APPROVED** [review]

**Comment by jeking3** [comment]
shipit

**Comment by acozine** [comment]
Test failure was a timeout. I don't think it's related to the changes in this PR . . . kicking off a new run.

**Comment by acozine** [comment]
Still seeing the test failures - we're investigating on our end. Stand by . . .

**Comment by acozine** [comment]
Related to #57250.

**Comment by samdoran** [comment]
I have optimized these tests in #57250 to fix these timeouts. Awaiting a final review on that PR, then we can re-run the tests for this PR.

**Comment by acozine** [comment]
Tests ran (and passed) last night. Merging at last!

**Pull request merged**
