### PR TITLE
Add logic to handle multiple actions in an ALB listener rule, Fixes #41861

### LINKED ISSUE #41861: AWS Application Load Balancer module (elb_application_lb) update fails for Listener actions that contain anything other than 'forward'
##### SUMMARY

AWS recently launched a new ALB (Application Load Balancer) featured that allows authentication to be performed by the load balancer using Cognito. This authentication is configured by adding an authentication action to a listener rule. ALB resources with this new authentication feature can be sucessfully created by ansible, however subsequent runs against the resource fail.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

elb_application_lb

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /home/jevers/misc_dev/ansible_alb_test/ansible.cfg
  configured module search path = ['/home/jevers/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jevers/.local/lib/python3.6/site-packages/ansible
  executable location = /home/jevers/.local/bin/ansible
  python version = 3.6.5 (default, Mar 29 2018, 18:20:46) [GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]
```

##### CONFIGURATION

ANSIBLE_FORCE_COLOR(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = -o ForwardAgent=yes -o PreferredAuthentications=keyboard-interactive,gssapi-with-mic,gssapi-keyex,hostbased,pub>
DEFAULT_FORKS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = 100
DEFAULT_GATHERING(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = ['/home/jevers/misc_dev/ansible_alb_test/inventory']
DEFAULT_LOG_PATH(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = /home/jevers/misc_dev/ansible_alb_test/log/ansible.log
DEFAULT_MANAGED_STR(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = Ansible managed: DO NOT EDIT
DEFAULT_MODULE_NAME(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = shell
DEFAULT_REMOTE_USER(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = pi
DEFAULT_SCP_IF_SSH(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
DEFAULT_TIMEOUT(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = 15
DEPRECATION_WARNINGS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
HOST_KEY_CHECKING(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = False

##### OS / ENVIRONMENT

Running Ansible on Fedora 28 (Linux) , managing AWS resources

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      role_account: "{{ACCTID}}"
      role_name: "{{ROLENAME}}"
      resource_state: present
      resource_prefix: alb-auth-test
      vpc_id: "{{VPC}}"
      subnets:
          - "{{SUBNET1}}"
          - "{{SUBNET2}}"
      AuthenticateCognitoConfig: 
          UserPoolArn: "{{USER_POOL_ARN}}"
          UserPoolClientId: "{{USER_POOL_APP_CLIENT_ID}}"
          UserPoolDomain: "{{USER_POOL_DOMAIN}}"
          SessionCookieName: "AWSELBAuthSessionCookie"
          Scope: "openid"
          SessionTimeout: 604800
          OnUnauthenticatedRequest: "authenticate"
  tasks:
      - name: assume role in target account
        sts_assume_role:
            role_arn: "arn:aws:iam::{{role_account}}:role/{{role_name}}"
            role_session_name: "ansible_workstation"
        register: assumed_role

      - name: create alb security group
        ec2_group:
            aws_access_key: "{{assumed_role.sts_creds.access_key}}"
            aws_secret_key: "{{assumed_role.sts_creds.secret_key}}"
            security_token: "{{assumed_role.sts_creds.session_token}}"

            name: "{{resource_prefix}}-sg"
            state: "{{resource_state}}"
            description: "security group for {{resource_prefix}}-alb"
            vpc_id: "{{vpc_id}}"
            rules:
                - proto: tcp
                  from_port: 80
                  to_port: 80
                  cidr_ip: 10.10.3.0/24
                - proto: tcp
                  from_port: 443
                  to_port: 443
                  cidr_ip: 10.10.3.0/24
        register: alb_sg

      - name: create target group
        elb_target_group:
            aws_access_key: "{{assumed_role.sts_creds.access_key}}"
            aws_secret_key: "{{assumed_role.sts_creds.secret_key}}"
            security_token: "{{assumed_role.sts_creds.session_token}}"

            name: "{{resource_prefix}}-tg"
            state: "{{resource_state}}"
            protocol: http
            port: 80
            vpc_id: "{{vpc_id}}"
        register: app_tg
          
      - name: create alb
        elb_application_lb:
            aws_access_key: "{{assumed_role.sts_creds.access_key}}"
            aws_secret_key: "{{assumed_role.sts_creds.secret_key}}"
            security_token: "{{assumed_role.sts_creds.session_token}}"

            name: "{{resource_prefix}}-alb"
            state: present

            security_groups:
                - "{{alb_sg.group_id}}"
            subnets: "{{subnets}}"
            scheme: internal
            listeners:
                - Protocol: HTTPS
                  Port: 443
                  DefaultActions:
                      - Type: forward
                        TargetGroupArn: "{{app_tg.target_group_arn }}"
                  Certificates:
                      - CertificateArn: "{{acm_cert_arn}}"
                  SslPolicy: ELBSecurityPolicy-2016-08
                  Rules:
                      - Conditions:
                          - Field: path-pattern
                            Values:
                                - "*"
                        Priority: '1'
                        Actions:
                            - Type: forward
                              TargetGroupArn: "{{app_tg.target_group_arn }}"
                              Order: 2
                            - Type: authenticate-cognito
                              AuthenticateCognitoConfig: "{{AuthenticateCognitoConfig}}"
                              Order: 1
```

##### EXPECTED RESULTS

1. On the first playbook run, the resource is created
2. the Playbook can be run against the new ALB resource without failure

##### ACTUAL RESULTS

The first Playbook runs sucessfully, and the ALB resource is created.
The playbook is run Again and the 'create alb' task fails with a 'KeyError: 'TargetGroupArn'' Exception

```
TASK [create alb] *********************************************************************************************************************************************************************
task path: /home/jevers/misc_dev/ansible_alb_test/alb.yml:63
Using module file /home/jevers/.local/lib/python3.6/site-packages/ansible/modules/cloud/amazon/elb_application_lb.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jevers
<localhost> EXEC /bin/sh -c 'python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 1028, in <module>
    main()
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 1023, in main
    create_or_update_elb(connection, connection_ec2, module)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 915, in create_or_update_elb
    listener_changed = create_or_update_elb_listeners(connection, module, elb)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 762, in create_or_update_elb_listeners
    rules_to_add, rules_to_modify, rules_to_delete = compare_rules(connection, module, current_listeners, listener)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 693, in compare_rules
    modified_rule = compare_rule(current_rule, new_rule)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 600, in compare_rule
    if current_rule['Actions'][0]['TargetGroupArn'] != new_rule['Actions'][0]['TargetGroupArn']:
KeyError: 'TargetGroupArn'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 1028, in <module>\n    main()\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 1023, in main\n    create_or_update_elb(connection, connection_ec2, module)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 915, in create_or_update_elb\n    listener_changed = create_or_update_elb_listeners(connection, module, elb)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 762, in create_or_update_elb_listeners\n    rules_to_add, rules_to_modify, rules_to_delete = compare_rules(connection, module, current_listeners, listener)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 693, in compare_rules\n    modified_rule = compare_rule(current_rule, new_rule)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 600, in compare_rule\n    if current_rule['Actions'][0]['TargetGroupArn'] != new_rule['Actions'][0]['TargetGroupArn']:\nKeyError: 'TargetGroupArn'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

### PR DESCRIPTION
**Pull request by jeevers**
##### SUMMARY

Recently AWS added support for authentication at the ALB (Application Load Balancer) layer using Cognito and OpenID which involves additional Listener rule actions. 

Currently the 'elb_application_lb' module can create the ALB with these additional rule actions, however updates fail with a KeyError exception as the module expects to be able to access a 'TargetGroupArn' key in the first element in either the 'DefaultActions' keys of the listener or the 'Actions' key of the listener rule.

In this change, the modules checks to see if the lists of actions are equivalent and then updates the actions accordingly. For situations where there are multiple actions, the lists are sorted by the Order key of each element and then compared.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

elb_application_lb

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel 15ce7c5bab) last updated 2018/06/26 14:19:56 (GMT -400)
  config file = None
  configured module search path = [u'/home/jevers/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jevers/misc_dev/ansible/lib/ansible
  executable location = /home/jevers/misc_dev/ansible/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by willthames** [comment]
It looks like the AuthenticateCognitoConfig change requires botocore >= 1.10.30. It might be worth catching exceptions associated with having an older botocore and trying to use this functionality

The elb_application_lb module has a test suite in test/integration/targets - as such, this feature request must have an associated test. A test that checks both older and newer botocore versions would be appreciated (the ecs_cluster test suite has an example of this type of test - see runme.sh)

**Comment by jeevers** [comment]
Currently the new authentication actions require the listener be configured for HTTPS, which in turn requires an ACM certificate be associated with the ALB. The `authenticate-cognito` action also requires a valid Cognito user pool.  Ansible does not have modules for creating ACM certs or Cognito User Pools, so I would not be able to test these additional actions.
Would it be acceptable to use the command (or shell) module to make the necessary awscli call to create these resources? Are there any guidelines I should keep in mind when creating these tests?

**Comment by threewordphrase** [comment]
Bump. Is there anything I can do to help get this merged in? I am about to implement a horrible workaround.

**Comment by jeevers** [comment]
ready_for_review

**Comment by willthames** [comment]
Argh @jeevers, I feel so bad, the runme.sh test stuff doesn't seem to work very well any more - I completely changed how the ecs_cluster test suite works the other week (see #57716) to account for that. Hopefully it's not too much additional work to change it back, I do appreciate it is a chore.

**Comment by jeevers** [comment]
@willthames I was able to modify runme.sh to work with that cloud test suite change:

https://github.com/ansible/ansible/pull/41975/commits/ab583fb622ef049c519906b5735634737ba61038

I just rebased from devel and the tests still run properly. Does this still need to be changed?

**Comment by willthames** [comment]
@jeevers after rebasing on devel (to avoid merge conflicts) and running `ansible-test integration  -vvv unsupported/elb_application_lb --docker` I get

```
TASK [Gathering Facts] *********************************************************
task path: /root/.ansible/test/tmp/elb_application_lb-o03zdgze-ÅÑŚÌβŁÈ/test/integration/targets/elb_application_lb/playbooks/multiple_actions_fail.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1564660806.8732843-207745683631679 `" && echo ansible-tmp-1564660806.8732843-207745683631679="` echo /root/.ansible/tmp/ansible-tmp-1564660806.8732843-207745683631679 `" ) && sleep 0'
Using module file /root/ansible/lib/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-15705d89hms/tmp_74zphp5 TO /root/.ansible/tmp/ansible-tmp-1564660806.8732843-207745683631679/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1564660806.8732843-207745683631679/ /root/.ansible/tmp/ansible-tmp-1564660806.8732843-207745683631679/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/bin/python /root/.ansible/tmp/ansible-tmp-1564660806.8732843-207745683631679/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1564660806.8732843-207745683631679/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "ansible_facts": {},
    "changed": false,
    "failed_modules": {
        "setup": {
            "failed": true,
            "module_stderr": "/bin/sh: 1: /usr/local/bin/python: not found\n",
            "module_stdout": "",
            "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
            "rc": 127
        }
    },
    "msg": "The following modules failed to execute: setup\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by willthames** [comment]
I think I've fixed up the test suite so I'll push up the changes if the test suite passes

**Review by s-hertel — APPROVED** [review]
Looks good to me and the tests pass.

**Comment by willthames** [comment]
rebuild_merge

**Comment by willthames** [comment]
Thanks @jeevers!

**Pull request merged**
