### PR TITLE
Adds one more example

### PR DESCRIPTION
**Pull request by tank-bohr**
##### SUMMARY

Documentation improvement. Addition of example for the most widespread case

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

`rollbar_deployment` module

### CODE REVIEW

**Comment by acozine** [comment]
Thanks @tank-bohr for improving the Ansible documentation with a new example. 

We'd like all examples in the documentation to contain `name:` lines - could you add one for your new example? And preferably one for the pre-existing example as well? See examples in the current module docs for the [group module](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/group.py#L71) and the [blockinfile module](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py#L127) .

**Comment by tank-bohr** [comment]
@acozine thank you. Sure, no problem

**Comment by acozine** [comment]
@tank-bohr thanks for the `name:` lines - now the indentation looks odd, though - have you tested the new examples?

**Comment by tank-bohr** [comment]
@acozine 
> have you tested the new examples?

Yes, of course

**Comment by acozine** [comment]
Thanks @tank-bohr - I'll merge these examples. If you include playbook output in your PR, it enhances the docs PRs and give users another way to find information about a module or use case.

**Pull request merged**
