### PR TITLE
#22147 Implementation of the already documented vlan management on nm…

### LINKED ISSUE #22147: Actions in the nmcli module specifically, creating and modifying VLANs and Bond interfaces will only trigger the nmcli command, and not actually build the command
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Ubuntu 16.04.2

##### SUMMARY
Actions in the nmcli module [specifically, creating and modifying VLANs and Bond interfaces](https://github.com/ansible/ansible/blob/7c003467147b170f015b945b4191b8bd74b6a1b7/lib/ansible/modules/network/nmcli.py#L989-L1007) will only trigger the nmcli command, and not actually build the command.

##### STEPS TO REPRODUCE
```
# ansible localhost -m nmcli -a "state=present vlandev=enp0s25 vlanid=100 type=vlan ip4=192.0.2.100/24 conn_name=vlan100 autoconnect=yes"
localhost | SUCCESS => {
    "Connection": "Connection vlan100 of Type vlan is being added",
    "changed": true,
    "conn_name": "vlan100",
    "state": "present",
    "stderr": "Usage: nmcli [OPTIONS] OBJECT { COMMAND | help }\n\nOPTIONS\n  -t[erse]                                   terse output\n  -p[retty]                                  pretty output\n  -m[ode] tabular|multiline                  output mode\n  -c[olors] auto|yes|no                      whether to use colors in output\n  -f[ields] <field1,field2,...>|all|common   specify fields to output\n  -e[scape] yes|no                           escape columns separators in values\n  -a[sk]                                     ask for missing parameters\n  -s[how-secrets]                            allow displaying passwords\n  -w[ait] <seconds>                          set timeout waiting for finishing operations\n  -v[ersion]                                 show program version\n  -h[elp]                                    print this help\n\nOBJECT\n  g[eneral]       NetworkManager's general status and operations\n  n[etworking]    overall networking control\n  r[adio]         NetworkManager radio switches\n  c[onnection]    NetworkManager's connections\n  d[evice]        devices managed by NetworkManager\n  a[gent]         NetworkManager secret agent or polkit agent\n  m[onitor]       monitor NetworkManager changes\n\n"
}
```

##### EXPECTED RESULTS
Execution of the command `nmcli connection add con-name vlan100 type vlan id 100 dev enp0s25 ip4 192.0.2.100/24`, creating a vlan tagged interface with an id of 100.

##### ACTUAL RESULTS
It appears that the command is not actually constructed, and instead, the command `nmcli` is run without arguments.

```
Using /etc/ansible/ansible.cfg as config file
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1488382327.96-245234744432154 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1488382327.96-245234744432154 )" )
127.0.0.1 PUT /tmp/tmphGpiRK TO /root/.ansible/tmp/ansible-tmp-1488382327.96-245234744432154/nmcli
127.0.0.1 EXEC LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1488382327.96-245234744432154/nmcli; rm -rf "/root/.ansible/tmp/ansible-tmp-1488382327.96-245234744432154/" > /dev/null 2>&1
localhost | SUCCESS => {
    "Connection": "Connection vlan100 of Type vlan is being added",
    "changed": true,
    "conn_name": "vlan100",
    "invocation": {
        "module_args": {
            "ageingtime": "300",
            "arp_interval": null,
            "arp_ip_target": null,
            "autoconnect": "yes",
            "conn_name": "vlan100",
            "dns4": null,
            "dns6": null,
            "downdelay": null,
            "egress": null,
            "flags": null,
            "forwarddelay": "15",
            "gw4": null,
            "gw6": null,
            "hellotime": "2",
            "ifname": null,
            "ingress": null,
            "ip4": "192.0.2.100/24",
            "ip6": null,
            "mac": null,
            "master": null,
            "maxage": "20",
            "miimon": null,
            "mode": "balance-rr",
            "mtu": null,
            "priority": "128",
            "slavepriority": "32",
            "state": "present",
            "stp": "yes",
            "type": "vlan",
            "updelay": null,
            "vlandev": "enp0s25",
            "vlanid": "100"
        },
        "module_name": "nmcli"
    },
    "state": "present",
    "stderr": "Usage: nmcli [OPTIONS] OBJECT { COMMAND | help }\n\nOPTIONS\n  -t[erse]                                   terse output\n  -p[retty]                                  pretty output\n  -m[ode] tabular|multiline                  output mode\n  -c[olors] auto|yes|no                      whether to use colors in output\n  -f[ields] <field1,field2,...>|all|common   specify fields to output\n  -e[scape] yes|no                           escape columns separators in values\n  -a[sk]                                     ask for missing parameters\n  -s[how-secrets]                            allow displaying passwords\n  -w[ait] <seconds>                          set timeout waiting for finishing operations\n  -v[ersion]                                 show program version\n  -h[elp]                                    print this help\n\nOBJECT\n  g[eneral]       NetworkManager's general status and operations\n  n[etworking]    overall networking control\n  r[adio]         NetworkManager radio switches\n  c[onnection]    NetworkManager's connections\n  d[evice]        devices managed by NetworkManager\n  a[gent]         NetworkManager secret agent or polkit agent\n  m[onitor]       monitor NetworkManager changes\n\n"
}
```

### PR DESCRIPTION
**Pull request by joanmarcriera**
…cli module.

##### SUMMARY

Fixes   #22147 , half of it. 
Implementation of the vlan section of nmcli management. 
Nmcli module was not using the parameters for vlan management, it was only calling the nmcli command and giving the output as good. 
Documentation on how to use nmcli module to manage vlan is already in place. 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
module/net_tools/nmcli.py 

##### ANSIBLE VERSION

```
nsible 2.4.0 (fix_implement_nmcli_vlan_integration a224a4f899) last updated 2017/04/28 13:03:20 (GMT +100)
  config file = /home/marc/.ansible.cfg
  configured module search path = [u'/home/marc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/marc/.local/src/github/ansible/lib/ansible
  executable location = /home/marc/.local/src/github/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@joanmarcriera Are you still working on this ?

**Comment by joanmarcriera** [comment]
I'm not working on this now, I moved to other stuff sorry. 

But the PR was good, I did not have the time to check for the couple of failed checks and I left it there.

**Comment by Akasurde** [comment]
@joanmarcriera OK. Sorry to see you go. I will take over this. Thanks for your contribution.

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible/ansible/pull/35343

**Pull request closed without merging**
