### PR TITLE
Implement protected parameter

### PR DESCRIPTION
**Pull request by panticz**
##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mnaser** [comment]
Could you add the `version_added` field to get this merged?

**Comment by mnaser** [comment]
shipit

**Comment by panticz** [comment]
Can this path by added to v2.8.2?

**Review by cloudnull — APPROVED** [review]
shipit

**Pull request merged**
