### PR TITLE
update doc in contrib\inventory\azure_rm.py

### PR DESCRIPTION
**Pull request by yungezz**
##### SUMMARY

Update doc in contrib\inventory\azure_rm.py with maintenance information and link to new batch inventory.

##### ISSUE TYPE

- Bugfix Pull Request

##### ANSIBLE VERSION

```paste below
ansible 2.8
```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by yungezz** [comment]
ready_for_review

**Comment by yungezz** [comment]
@nitzmahone  @jborean93 @kyliel

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@nitzmahone @jborean93 @kyliel @zikalino, ready for review. Could you help to review this PR? Thanks!

**Comment by Fred-sun** [comment]
@nitzmahone @jborean93 @kyliel @zikalino

**Comment by Fred-sun** [comment]
@nitzmahone @jborean93 @kyliel @zikalino Please help review this! Thanks!

**Pull request merged**
