### PR TITLE
Remove deadcode since diff is never used

### PR DESCRIPTION
**Pull request by mscherer**
##### SUMMARY

Flake8 keep warning me about that

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
openssl_certificate

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Maybe add it to the error message instead?

**Comment by mscherer** [comment]
Yeah, it seems like something was planned to be done with this, but I am not sure what. Adding diff mode could be a solution too.

**Comment by MarkusTeufelberger** [comment]
I guess something like `'Invalid issuer component (got %s, expected all of %s to be present, diff: %s)'`, maybe even adding support for diff mode as you said (though this might be difficult with selfsigned/letsencrypt providers).

**Comment by mscherer** [comment]
Since I think the code was written by @Spredzy , let's see if he had something in mind for that, or if there was a reason to not complete it, it will give me time to look up how diff mode actually work if I need to add it.

**Comment by Spredzy** [comment]
Sorry to disapoint I don't recall either at the moment. Since its not used it can be safely removed for now. When the need for this will come again we'll reimplement if, if ever needed. Thanks @mscherer 

shipit

**Pull request merged**
