### PR TITLE
Correct plugin loader context for persistent (#54860)

### PR DESCRIPTION
**Pull request by bcoca**
* Correct plugin loader context for persistent

(cherry picked from commit 6579dfda1717cda64bdb2a6de31f0b8ec7841471)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

connection/persistent

### CODE REVIEW

**Comment by abadger** [comment]
Merged for 2.7.11

**Comment by mattclay** [comment]
This is causing CI failures: https://app.shippable.com/github/ansible/ansible/runs/119235/34/console

The error is `ImportError: cannot import name become_loader`, seen here:

```
17:17 Run command: ansible -m vyos_command -a 'commands=?' -u vyos -i vyos-1-1-8, -e 'ansible_host=ec2-35-174-241-243.compute-1.amazonaws.com ansible_port=22 ansible_connection=local ansible_ssh_private_key_file=test/cache/id_rsa' vyos-1-1-8
17:18 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name become_loader
17:18 vyos-1-1-8 | FAILED! => {
17:18     "msg": "Unexpected failure during module execution.", 
17:18     "stdout": ""
17:18 }
```

**Comment by mattclay** [comment]
This wasn't caught at PR time because the network tests were not triggered by the changes. To work around that for now on a future PR, use `ci_complete` in the commit message.

**Comment by trishnaguha** [comment]
@bcoca @abadger This introduced a bug in local connection plugin #55381 for networking platforms.

**Comment by mattclay** [comment]
@trishnaguha The ImportError in stable-2.7 was fixed in https://github.com/ansible/ansible/pull/55343 -- does that resolve the issue?

**Comment by bcoca** [comment]
@mattclay diff error, this seems to be preexisting, exposed by the change, the network plugins raise errors on import (plugins should not do this).

**Comment by trishnaguha** [comment]
There appears to be a bug in netconf plugin issue instead of here in the persistent plugin.

**Pull request merged**
