### PR TITLE
win_shortcut: Add missing $check_mode definition + bugfix + tests

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_shortcut

##### ANSIBLE VERSION

v2.3

##### SUMMARY

For some reason this entry was missing, possible a merge-conflict gone wrong.

I added integration tests to avoid this in the future, and also included a new bugfix as well.

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to:

```
2017-02-01 19:15:09 An exception occurred during task execution. The full traceback is:
2017-02-01 19:15:09 At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1485976507.52-74074157722496\win_shortcut.ps1:360 char:13

2017-02-01 19:15:09 +             $src = (Get-Command -Name $src -Type Application).Source

2017-02-01 19:15:09 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-02-01 19:15:09 fatal: [windows-2012-RTM]: FAILED! => {
2017-02-01 19:15:09     "changed": false, 
2017-02-01 19:15:09     "failed": true, 
2017-02-01 19:15:09     "invocation": {
2017-02-01 19:15:09         "module_name": "win_shortcut"
2017-02-01 19:15:09     }, 
2017-02-01 19:15:09     "msg": "Property 'Source' cannot be found on this object. Make sure that it exists."
2017-02-01 19:15:09 }
```

**Comment by dagwieers** [comment]
@mattclay Sigh, it works fine on Windows 10 (the only Windows I have here :-))

**Comment by dagwieers** [comment]
ready_for_review

**Review by gundalow — APPROVED** [review]
Good to see idempotent tests.

**Pull request merged**
