### PR TITLE
#2105 :  Vagrant support

### PR DESCRIPTION
**Pull request by robparrott**
added in files from tag 0.0.3 at 
- https://github.com/robparrott/ansible-vagrant 

to add experimental vagrant support

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks again for this.

There are a few style things you should correct, I would probably correct these myself but I have a limited amount of time to test everyone's modules, so it is better if you can.

This is mostly PEP8-ish kind of stuff.

Comments for functions should always use a docstring immediately following the "def", not just single quotes inside the function, or "#" ahead of the function.    You have the docstring quoting in most places but not everywhere, so it just helps to be consistent.

The body of a one-line function should not be defined on the same line as a 'def' statement

Do not use single letter variables

when definiing multiple keys in a hash, use:

```
foo = dict(
        a = 1234,
        b = 5678
)
```

rather than:

```
d['a'] = 1234
d[b'] = 5678
```

this allows less special characters and makes it more readable.

imports like StringIO should be made at the top of the file rather than inside the function where they are used

Do not put any statements on the same line as the colon in an "if" or else, always start a new line.

Anyway, all of those should be pretty easy tweaks, if you can make those I think we can apply this.

**Comment by yeukhon** [comment]
I am a vagrant user but I am too busy to help testing this. 
Here is my quick glance. This is running a host-only. That's fine, but you require users to change the internal IP.
`VAGRANT_INT_IP = "192.168.179.%s"`

Also, it's assumed users don't even know this value, so it would be really nice if it's either strongly stated in the doc or through error if the IP of current machine is different - this means it will do a gather fact  about the current hosts - and users shouldn't turn it off).

If I do git pull and I want everything to be clean, wouldn't I have to edit again and again?
It would be nice if this can either be an argument or somewhere a vagrant inventory file.

Maybe this is not a big deal as of now but vagrant files are assumed to be under certain path by default.

**Comment by mpdehaan** [comment]
please don't use "git merge" when working on live pull requests.

Do "git pull --rebase", that way we do not get merge commits in the history.

A good way to handle this is to permanently alias "git merge" to "git pull --rebase"

**Comment by mpdehaan** [comment]
I'll let you resubmit this with aforementioned style fixes and without the merge commit.

Thanks!

**Pull request closed without merging**
