### PR TITLE
Support check mode for efs_facts

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY
Facts modules support check mode by default

Fix pep8 compliance

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
efs_facts

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel d1652aecf0) last updated 2017/06/30 14:21:05 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible/lib/ansible
  executable location = /home/will/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

### CODE REVIEW

**Review by ryansydnor — APPROVED** [review]
Shipit

**Comment by willthames** [comment]
Looks like this failed for temporary reasons, will close and reopen to fire off tests

**Comment by resmo** [comment]
code lgtm
shipit

**Comment by resmo** [comment]
bot_status

(checking if close-reopen resets shipipts)

**Pull request merged**
