### PR TITLE
Add Amazon SNS notification plugin

### PR DESCRIPTION
**Pull request by mjschultz**
- Supports a default message or a special message for any of SNS's
  protocols (email, sqs, sms, http, https)
  - http://docs.aws.amazon.com/sns/latest/dg/PublishTopic.html

Uses [boto's SNS API](http://boto.readthedocs.org/en/latest/ref/sns.html). For reference, [Amazon's API](http://docs.aws.amazon.com/sns/latest/api/API_Publish.html)

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for the submission!

**Comment by mpdehaan** [comment]
Looks like there maybe should be some error handling around this part to call "fail_json" if the connection fails, so it doesn't traceback:
-    connection.publish(topic=arn_topic, subject=subject,
- ```
                    message_structure='json', message=json_msg)
  ```

Can you update this one? 

Otherwise looks good to me.  Thanks again!

**Comment by mjschultz** [comment]
No problem, I added a BotoServerError handling that just spits out the exception as a string (this seems to be what other aws modules do for the connection).

I also added a failure if the `region` param isn't supplied by the call to `get_aws_connection_info` since if `region=None` I ended up with an AttributeError on the `connection.publish()`. Let me know if there is a better/more appropriate way.

**Comment by mpdehaan** [comment]
Merged, thank you!

**Comment by mjschultz** [comment]
No problem, thanks for ansible!

**Pull request merged**
