### PR TITLE
Document :& host notation and using variables with hosts

### PR DESCRIPTION
**Pull request by lorin**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Merged, thanks!!!

**Comment by mpdehaan** [comment]
(will be available in next doc push)

BTW +1000 on the coderwall idea, really liking that!

**Comment by cherusk** [comment]
That seems up for quite some time. For what version should that work: 2.4?

**Comment by cherusk** [comment]
Figured it:
For 2.3, it was necessary to actaully interpolate the var coming from the include, like ...

e.g.
parent:
- include: child.yml _hosts=new_nodes
...
- hosts: all:&{{_hosts }}
...

**Pull request merged**
