### PR TITLE
Fix for private_key overriding in synchronize module

### PR DESCRIPTION
**Pull request by holser**
##### SUMMARY

Backport of https://github.com/ansible-collections/ansible.posix/commit/4b0b50439d3b7fd232291795ca0deec36e4b59de

##### ISSUE TYPE

* Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/plugins/action/synchronize.py

##### ADDITIONAL INFORMATION

* https://github.com/ansible-collections/ansible.posix/pull/82
* https://github.com/ansible-collections/ansible.posix/issues/131

### CODE REVIEW

**Comment by webknjaz** [comment]
@holser could you please fill out the PR template? https://github.com/ansible/ansible/blob/devel/.github/PULL_REQUEST_TEMPLATE.md

**Review by webknjaz — APPROVED** [review]

**Review by odyssey4me — APPROVED** [review]

**Comment by relrod** [comment]
This backport concerns me from a backwards-compatibility perspective.

The problem this is fixing is undoubtedly a bug, and shouldn't have worked that way. Clearly, task-level arguments should take precedence. But the current behavior has existed since at least 2015 (possibly longer), and it's completely feasible that people are relying on the current behavior (which amounts to "use the passed `private_key` unless a different one is specified in inventory/on commandline"). We would be reversing that logic here.

I have been working really hard to stabilize our stable branches/releases and not break people on z-level upgrades (e.g. 2.9.z, 2.10.z). So although this is clearly broken behavior, I think it's been around long enough that fixing it now is riskier than not.

**Comment by webknjaz** [comment]
> and it's completely feasible that people are relying on the current behavior

Ouch! So it's the [Hyrum's Law](https://www.hyrumslaw.com/) [preventing us from merging](https://xkcd.com/1172/).

FWIW 2.9 can digest collections so it's not the end of the world if we tell the users to use those, right?

**Comment by relrod** [comment]
> FWIW 2.9 can digest collections so it's not the end of the world if we tell the users to use those, right? 

Absolutely! If someone wants the change, they can and should pull in the collection and use it from there. That's an explicit action, and not us reversing the change on a z-level upgrade behind the user's back. :)

**Pull request closed without merging**
