### PR TITLE
vmware_guest: Add multiple nics management + Bug fixes

### PR DESCRIPTION
**Pull request by aperigault**
##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
- Fix var name:
function getfolder return folder_map instead of foldermap.

- Fix bug in deploy_template function:
If folder not start by /vm there is a "no folder matched the path" error

- Power on VM if state is set to poweredon

New feature : Move nic creation out of customizations + Add multiple nics management

### CODE REVIEW

**Comment by aperigault** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/3481

**Comment by aperigault** [comment]
@dav1x @jctanner I added a new feature to allow users to set vlan_id instead of vlan_name in nics configuration (https://github.com/ansible/ansible-modules-extras/pull/3481/commits/7f2e8fc8c5089efc8b9708e35d0bbfc9bede6c12)

**Comment by jctanner** [comment]
ping @Cougar @Abdul-Anshad-A ping, take a look and review if you can please.

**Comment by gundalow** [comment]
Thank you for being very proactive in your efforts to migrate your PR, however it appears that there was a window of time when ansible/ansible:devel was broken and it appears, unfortunately, that your PR was migrated during that window.

Due to this you will need to follow a hopefully very simple process to fix this. Please see https://groups.google.com/forum/#!topic/ansible-devel/0eRSpiGkios

As a thank you for being pioneers, we will actively review your PRs as a priority. Once you've migrated your PR please add it to the Core Agenda https://github.com/ansible/community/issues/147

**Pull request closed without merging**
