### PR TITLE
Prefer https:// links in the docs site

### PR DESCRIPTION
**Pull request by andreaso**
##### SUMMARY

All the changed urls are availible by way of https://. Most of them
already redirect.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
docs site

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (devel b02e0c07d8) last updated 2018/07/21 09:55:30 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/andreas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andreas/labs/ansible/devel/lib/ansible
  executable location = /home/andreas/labs/ansible/devel/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
rebuild_merge

**Comment by jctanner** [comment]
bot_status

**Comment by andreaso** [comment]
@jctanner @maxamillion: Status on getting this one merged?

**Comment by abadger** [comment]
Maxamillion reviewed and looks like his intent was to merge if tests pass.  I see that tests are currently passing so i've merged this to devel.

**Pull request merged**
