### PR TITLE
os_coe_cluster module overrides param labels with wrong behavior

### LINKED ISSUE #52698: os_coe_cluster overrides param labels wrongly by default
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
When users are using os_coe_cluster to create a coe cluster without assigning label params, it would override it to null which has been set in os_coe_cluster_template and cause cluster creation failure.


##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->
os_coe_cluster

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```
ansible 2.8.0.dev0

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
N/A

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
N/A

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```
  tasks:
    - name: Create a new Magnum template
      os_coe_cluster_template:
        state: present
        name: your-coe-template
        coe: kubernetes
        image_id: your-image-id
        keypair_id: your_keypair
        external_network_id: your-publicnet
        public: no
        flavor_id: c1.c4r8
        master_flavor_id: c1.c2r4
        floating_ip_enabled: yes
        network_driver: calico
        volume_driver: cinder
        docker_storage_driver: overlay
        labels:
          kube_tag: v1.12.6
          etcd_volume_size: 20
    - name: Create a new Magnum Cluster
      os_coe_cluster:
        state: present
        name: your-coe-cluster
        cluster_template_id: your_coe_template_id

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
The call will be succeed and the coe cluster will be created successfully.

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->

The call will return succeed with a coe cluster id, but Magnum will fail to create the cluster atfer doing checks on labels:
```
$ openstack coe cluster show 3443c4a0-7a41-494a-bd3d-465f42269c55
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field               | Value                                                                                                                                                                                                                                                                        |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| status              | CREATE_FAILED                                                                                                                                                                                                                                                                |
| cluster_template_id | 68925549-522c-44f1-88fc-b3ff6f237d95                                                                                                                                                                                                                                         |
| node_addresses      | []                                                                                                                                                                                                                                                                           |
| uuid                | 3443c4a0-7a41-494a-bd3d-465f42269c55                                                                                                                                                                                                                                         |
| stack_id            | fbdba500-8f49-4e82-86f2-442206a0d7f8                                                                                                                                                                                                                                         |
| status_reason       | Resource CREATE failed: resources[0]: resources.kube_masters.Property error: resources.etcd_volume.properties.size: 0 is out of range (min: 1, max: None)                                                                                                                    |
| created_at          | 2019-02-21T03:07:05+00:00                                                                                                                                                                                                                                                    |
| updated_at          | 2019-02-21T03:07:34+00:00                                                                                                                                                                                                                                                    |
| coe_version         | v1.11.1                                                                                                                                                                                                                                                                      |
| labels              | {}                                                                                                                                                                                                                                                                           |
| faults              | {u'0': u'resources[0]: Property error: resources.etcd_volume.properties.size: 0 is out of range (min: 1, max: None)', u'kube_masters': u'resources[0]: resources.kube_masters.Property error: resources.etcd_volume.properties.size: 0 is out of range (min: 1, max: None)'} |
| keypair             | id-rsa-k8s-cluster                                                                                                                                                                                                                                                           |
| api_address         | None                                                                                                                                                                                                                                                                         |
| master_addresses    | []                                                                                                                                                                                                                                                                           |
| create_timeout      | 60                                                                                                                                                                                                                                                                           |
| node_count          | 1                                                                                                                                                                                                                                                                            |
| discovery_url       | https://discovery.etcd.io/64d0c805260eca540424879101d31845                                                                                                                                                                                                                   |
| master_count        | 1                                                                                                                                                                                                                                                                            |
| container_version   | 1.12.6                                                                                                                                                                                                                                                                       |
| name                | magnum-ci-autobuild                                                                                                                                                                                                                                                          |
| master_flavor_id    | c1.c2r4                                                                                                                                                                                                                                                                      |
| flavor_id           | c1.c4r8                                                                                                                                                                                                                                                                      |
+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
As labels has been overrided to {}, so magnum can not find resources.etcd_volume.properties.size and throw the error above.

### PR DESCRIPTION
**Pull request by NewpTone**
##### SUMMARY

Fixes #52698

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

os_coe_cluster

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by gundalow** [comment]
CI seems to be failing with 
```
+ lib/neutron_plugins/services/l3:is_networking_extension_supported:438 :   return 0
+ lib/neutron_plugins/services/l3:create_neutron_initial_network:231 :   [[ True == \T\r\u\e ]]
++ lib/neutron_plugins/services/l3:create_neutron_initial_network:233 :   grep ' id '
++ lib/neutron_plugins/services/l3:create_neutron_initial_network:233 :   oscwrap --os-cloud devstack-admin --os-region RegionOne router create --project a8da6570a509478393f41befb7790318 router1
++ lib/neutron_plugins/services/l3:create_neutron_initial_network:233 :   get_field 2
++ functions-common:oscwrap:2338            :   local out
++ functions-common:get_field:727           :   local data field
++ functions-common:oscwrap:2339            :   local rc
++ functions-common:get_field:728           :   read data
++ functions-common:oscwrap:2340            :   local start
++ functions-common:oscwrap:2341            :   local end
+++ functions-common:oscwrap:2345            :   date +%s%3N
++ functions-common:oscwrap:2345            :   start=1550726856386
+++ functions-common:oscwrap:2346            :   command openstack --os-cloud devstack-admin --os-region RegionOne router create --project a8da6570a509478393f41befb7790318 router1
+++ functions-common:oscwrap:2346            :   openstack --os-cloud devstack-admin --os-region RegionOne router create --project a8da6570a509478393f41befb7790318 router1
ConflictException: 409: Client Error for url: https://158.69.73.53:9696/v2.0/routers, Failed to create a duplicate ProviderResourceAssociation: for attribute(s) ['PRIMARY'] with value(s) single_node-04fb7e23-4edd-4a39-b525-79e404cd9785
++ functions-common:oscwrap:2346            :   out=
++ functions-common:oscwrap:2347            :   rc=1
+++ functions-common:oscwrap:2348            :   date +%s%3N
++ functions-common:oscwrap:2348            :   end=1550727000557
++ functions-common:oscwrap:2349            :   echo 144171
++ functions-common:oscwrap:2351            :   echo ''
++ functions-common:oscwrap:2352            :   return 1
+ lib/neutron_plugins/services/l3:create_neutron_initial_network:233 :   ROUTER_ID=
+ lib/neutron_plugins/services/l3:create_neutron_initial_network:234 :   die_if_not_set 234 ROUTER_ID 'Failure creating ROUTER_ID for a8da6570a509478393f41befb7790318 router1'
+ functions-common:die_if_not_set:213      :   local exitcode=0
[Call Trace]
./stack.sh:1333:create_neutron_initial_network
/opt/stack/devstack/lib/neutron_plugins/services/l3:234:die_if_not_set
/opt/stack/devstack/functions-common:220:die
[ERROR] /opt/stack/devstack/functions-common:234 Failure creating ROUTER_ID for a8da6570a509478393f41befb7790318 router1
Error on exit
*** FINISHED ***
```

recheck

**Comment by NewpTone** [comment]
How could I re-trigger openstacksdk-ansible-devel-functional-devstack test? It seems a random fail caused by devstack

**Comment by mattclay** [comment]
Closing and re-opening PR to trigger CI.

**Comment by NewpTone** [comment]
@gtema  Hi, could you please take a look at this patch?

**Review by cloudnull — APPROVED** [review]
shipit

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by Akasurde** [comment]
@NewpTone Thanks for the contribution. Closing as per above.

**Pull request closed without merging**
