### PR TITLE
Updated ios/ios_facts.py to include lldp and cdp neighbors and vss st…

### PR DESCRIPTION
**Pull request by sipenat1**
##### SUMMARY

Added a VSS State Boolean value.  
Added CDP and LLDP Dict objects under interfaces with additional information.
Changed from a single return list "ansible_net_neighbors" to separate CDP "ansible_net_all_cdp_neighbors" and LLDP "ansible_net_all_lldp_neighbors" lists.
   

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ios\ios_facts.py

##### ADDITIONAL INFORMATION
Added a VSS State Boolean value.  
 - When the selected switch is part of a VSS stack "ansible_net_vss": true
Added CDP and LLDP Dict objects under interfaces with additional information.
 - CDP and LLDP often provide different information when dealing with different peer types. 
 - The CDP dict returns:
    - host:
    - remote_ip:
    - remote_platform:
    - remote_port:
 - The LLDP dict returns:
    - host:
    - remote_ip:
    - remote_port: 
Changed from a single return list "ansible_net_neighbors" to separate CDP "ansible_net_all_cdp_neighbors"
 and LLDP "ansible_net_all_lldp_neighbors" lists to enable the end user to access both fact sets and variables. 
   

```paste below
Example of VSS State:
   "ansible_net_vss": true

Example of interface output:

"TenGigabitEthernet1/1/25": {
    "bandwidth": 10000000,
    "cdp": {
        "host": "host.domain.net",
        "remote_ip": null,
        "remote_platform": "VMware ESX,  Capabilities: Switch ",
        "remote_port": "vmnic4"
    },
    "description": "HOSTNAME vmnic4",
    "duplex": null,
    "ipv4": [],
    "lineprotocol": null,
    "lldp": {
        "host": null,
        "remote_ip": "10.0.0.0",
        "remote_port": "Embedded ALOM, Port 1"
    },
    "macaddress": "removed",
    "mediatype": "10GBase-SR",
    "mtu": 1500,
    "operstatus": "up",
    "type": "Ten Gigabit Ethernet Port"
}
```

### CODE REVIEW

**Review by pabelanger — CHANGES_REQUESTED** [review]
Thanks for the PR, I'd like to see us also update tests/integration/targets/ios_facts to also confirm lldp / cdp info is now properly collected.  We'll also be able to start validating this with our network integration tests.

**Comment by sipenat1** [comment]
> Thanks for the PR, I'd like to see us also update tests/integration/targets/ios_facts to also confirm lldp / cdp info is now properly collected.  We'll also be able to start validating this with our network integration tests.
Thank you for the comment. I would be happy to add the information for the test environment. But I need some help in figuring out how to do that. Is there a doc the specifically addresses updating the test environment?

**Comment by pabelanger** [comment]
Great question, our docs are pretty minimal right now. Something that we should improve for new users, but the basic idea would be, update the following tests, to include the new logic you are adding here:

  https://github.com/ansible/ansible/tree/devel/test/integration/targets/ios_facts/tests/cli

You'd add a new ios_facts task, and setup ansible_net_vss, then assert the data was collected. Hopefully the code above providers a good example.

**Comment by Qalthos** [comment]
Have you had a chance to try to update the tests yet?

needs_info

**Pull request closed without merging**
