### PR TITLE
Updated docs for the k8s module to mention how to avoid SSL certificate validation errors

### PR DESCRIPTION
**Pull request by bincyber**
##### SUMMARY

Updated documentation for the `k8s` module to mention how to avoid SSL certificate validation errors.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

k8s

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bincyber/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Nov  5 2018, 14:07:04) [GCC 8.2.1 20181011 (Red Hat 8.2.1-4)]
```

### CODE REVIEW

**Review by fabianvf — APPROVED** [review]

**Comment by fabianvf** [comment]
shipit

**Comment by bincyber** [comment]
Thanks for reviewing @fabianvf

**Comment by samccann** [comment]
Thanks @bincyber for helping to improve the Ansible documentation! Can you also backport to 2.7?  Instructions are here - https://docs.ansible.com/ansible/latest/community/development_process.html?highlight=backport#backport-pull-request-process.

**Comment by bincyber** [comment]
Thanks for merging @samccann. I've backported to 2.7 in #48586

**Pull request merged**
