### PR TITLE
win_chocolatey_config: added module to manage Chocolatey config

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
In continuing with the work of completing https://chocolatey.org/docs/features-infrastructure-automation#chocolatey-integration-implementation-with-common-configuration-managers

Manages Chocolatey config https://chocolatey.org/docs/commands-config.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
win_chocolatey_config

##### ANSIBLE VERSION
```
devel
```

### CODE REVIEW

**Comment by jborean93** [comment]
cc @gep13 @ferventcoder

**Review by nitzmahone — APPROVED** [review]

**Comment by gep13** [comment]
@jborean93 great work on all three of these PR's!!

@dagwieers @nitzmahone Now that they are merged, when can we expect to see them in a released version of Ansible?

**Comment by jborean93** [comment]
@gep13 they will be available in Ansible 2.7 which is expected to be available at the start of October https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_7.rst#id4.

The last thing I'm working on is refactoring the existing win_chocolatey module to fix some current issues and add some features. I should hopefully have that done by the end of this week and start working on updating the Chocolatey docs around Ansible.

**Comment by gep13** [comment]
@jborean93 that sounds great!!  Very much appreciate your work in getting this done!

**Pull request merged**
