### PR TITLE
try autoinstall python-apt, if not available. Closes GH-4079.

### PR DESCRIPTION
**Pull request by resmo**

### CODE REVIEW

**Comment by bcoca** [comment]
I don't thnk most debian/ubuntu admins will like stuff being
'autoinstalled' w/o a prompt or at least a notice, also change might
'upgrade' the package w/o intending it, in any case i would run in the
except block and reimport on success of command.

**Comment by srgvg** [comment]
+1 @bcoca, this is a dependency to ansible that should be explicitly installed

**Comment by resmo** [comment]
@bcoca I would love to let the user know, python-apt is being installed. but unsure if there is a way to print a notice to the user. 

@mpdehaan @jimi1283 is there a way?

**Comment by mpdehaan** [comment]
I strongly disagree with @bcoca and @sergevanginderachter -- in this case the module makes an unreasonable requirement that the user has to hop through and add this module in order to be able to install things.

It would be fine to add it to the list of returned data in the JSON, like appending to the "msg" data "python-apt was auto-installed to enable the future operation of this module"

**Comment by srgvg** [comment]
@mpdehaan can you elaborate on your opinion? Where do you pull the line between this module, and all others that need non-standard libraries?

**Comment by mpdehaan** [comment]
Packages are super fundamental and pretty much the first statement most
people execute in an ansible playbook.

From there, you can use the package module to install any deps.

The idea that the package module is non-functional stock is unacceptable to
me for this reason, and the use of the command module to install it can't
easily produce a changed=0 kind of model very easily.

**Comment by jimi-c** [comment]
So this actually breaks with the modifications I've made to the apt module to allow for better broken installation detection. Since I've moved the try/except for the import up to the top of the file (where it really belongs anyway), using apt/apt_pkg in the functions above break if those are not imported, so we're going to have to figure out a different way to do this.

**Comment by bcoca** [comment]
So from what I can see both packages are mostly used for cache update and
figuring out package state, would it be acceptable to remove the module
dependencies by using base tools? This will require a bit more work in the
module.

**Comment by resmo** [comment]
No problem, closing this PR.

I also have received some concerns auto-installing python-apt. It feels a bit too much magic to me. 

You always have to bootstrap things and there are better ways doing that, like during install (preseed) or low level bash script and so forth.

So, for me, it is not a big deal doing;

```
- name: install debian deps
  raw: apt-get install python-apt -y
```

**Pull request closed without merging**
