### PR TITLE
library/pip: add support for virtualenv's --system-site-packages.

### PR DESCRIPTION
**Pull request by blair**
I went with a long option name, virtualenv_system_site_packages, to be consistent with virtualenv's --system-site-packages command line argument, but feel free to shorten it.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks... Yes, please update this commit with it shortened.

Is site_pkgs too confusing?

**Comment by blair** [comment]
I think it should start with virtualenv at a minimum to imply that its connected.  We could go with virtualenv_site_pkgs???

**Comment by blair** [comment]
This option has no effect if virtualenv isn't used.

**Comment by mpdehaan** [comment]
virtualenv_site_packages works for me

**Comment by blair** [comment]
I've updated the branch (replaced the HEAD commit) with a new commit using virtualenv_site_packages.

**Comment by mpdehaan** [comment]
In queue for inclusion for 1.1 as we're at feature freeze for 1.0 right now (releasing Friday).

Thanks very much!

**Comment by blair** [comment]
Pinging for a pull now that 1.0 was cut.

**Comment by mpdehaan** [comment]
There is no need to ping.   I'll get to it within a week or so.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
