### PR TITLE
[WIP] sphinx API docs spike

### PR DESCRIPTION
**Pull request by alikins**
##### ISSUE TYPE
- Feature Pull Request
##### SUMMARY

A work-in-progress branch for adding sphinx generated api docs, and various cleanups, fixes, and docs strings updates to improve them.

### CODE REVIEW

**Comment by alikins** [comment]
I'll try to keep a recent-ish version of the docs generated with this branch at https://alikins.github.io/

**Comment by dekimsey** [comment]
This would go a long ways to start getting API documentation in core and fleshed out.

Related [proposal](https://github.com/ansible/proposals/issues/20) I just submitted today in-fact touches on this subject.

**Comment by alikins** [comment]
Going to split this into at least two prs, one for just the docs-api/ sphinx infrastructure stuff, and another with just doc string changes.

**Comment by alikins** [comment]
Split this into:
https://github.com/ansible/ansible/pull/16418   docs-api/ sphinx setup
https://github.com/ansible/ansible/pull/16419   doc string changes for better docs

**Pull request closed without merging**
