### PR TITLE
Add --list-vars options function

### PR DESCRIPTION
**Pull request by risingmoon**
I wanted a way to list out variables without running any plays.

Note: Made clean merges/rebase with my code. Should be working now.
REF: https://github.com/ansible/ansible/pull/10143

### CODE REVIEW

**Comment by risingmoon** [comment]
@bcoca There were some merge issues in previous pull request, so I did a pull rebase and so conflicts should be resolved.

**Comment by risingmoon** [comment]
Merge conflict fixed.

**Comment by risingmoon** [comment]
*crickets *

**Comment by bcoca** [comment]
@risingmoon, first of all, sorry for the delay. The issue I had with this PR is that the variables listed are not all possible vars, which I believe would lead to confusion.

Also at this point, runner is deprecated in favor of many new classes you can see in the v2_final branch, it will also probably be much easier to implement this there.

**Comment by amenonsen** [comment]
@risingmoon if you're interested in reimplementing this for v2, now's the time, since current devel has all of the new code @bcoca mentioned earlier, and `--list-tasks` and `--list-tags` support was just implemented. This PR should be closed, since it's outdated.

**Comment by amenonsen** [comment]
Closing per the above comment.

**Pull request closed without merging**
