### PR TITLE
Use public or private IP in Azure Dynamic Inventory

### PR DESCRIPTION
**Pull request by dol3y**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

azurerm
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

```
We need to use the private IP when addressing instances in Azure. This adds the ability to use either the default public IP or the private IP. It can be set in the `init` file or as an environment variable. 
```

### CODE REVIEW

**Comment by calfonso** [comment]
@tstringer could you review this for us and let us know if any changes are required? Thanks!

**Comment by trstringer** [comment]
I'll check this out. This is the first time I'm seeing this, could I get a brief summary on the following:

1. What is the current state/workflow?
1. What is the desired state/workflow?
1. What exactly does this PR add?
1. (optional) any repro or tests run against this PR code

**Comment by samirageb** [comment]
@tstringer I just ran into this today.
To answer your q's:
1. Current state is when you run the dynamic inventory script, you'll get the public IP addresses of the hosts to run commands against
2. If you're on a LAN, you're leaving the FW to run against the public IP addresses of the servers that may be on the same subnet. Ideally you should be getting the private IP addresses for the sake of efficiency, speed if that's preferred/available.
3. Afaict this PR offers a switch to maintain backwards compatibility with ansible behavior today, but also allowing a private ip 'override' to account for the desired behavior previously mentioned.
4. Unknown

**Comment by adolby-rms** [comment]
@tstringer I have not looked at this for a while but yes, as @samirageb has said, it allows Ansible to run against the internal IP. This is required in environments where there is no public SSH access to hosts.

1. The default behaviour is for the dynamic inventory script to set `ansible_host` to the public IP.
2. In our case, we do not assign public IPs to hosts and only connect to the internal IP. As such `ansible_host` gets set to `null` and Ansible is unable to connect to the hosts.
3. This adds an optional toggle in the `.ini` file, which sets the `ansible_host` to the private IP and fixes the connectivity issue. There is no change in behaviour if the flag is omitted.

**Comment by dol3y** [comment]
@tstringer I have not looked at this for a while but yes, as @samirageb has said, it allows Ansible to run against the internal IP. This is required in environments where there is no public SSH access to hosts.

1. The default behaviour is for the dynamic inventory script to set `ansible_host` to the public IP.
2. In our case, we do not assign public IPs to hosts and only connect to the internal IP. As such `ansible_host` gets set to `null` and Ansible is unable to connect to the hosts.
3. This adds an optional toggle in the `.ini` file, which sets the `ansible_host` to the private IP and fixes the connectivity issue. There is no change in behaviour if the flag is omitted.

**Comment by thiagocaiubi** [comment]
Slow revision process keeps people doing the same thing over and over. 😢 

https://github.com/ansible/ansible/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20azure%20private

I think this is best implementation based on all open PRs: https://github.com/ansible/ansible/pull/27692

How can we help?

**Comment by samirageb** [comment]
@thiagocaiubi thank you for the reply. My thoughts are below.

1.  I think the first step would be to merge the desired PR with the latest azure inventory script, so that people can see the latest functionality incorporated / unified in a single file.

2. Version the inventory script so people could have something to compare their version to. For those of us tracking our 'custom' version against the repo, every merge is manual.
  
3. Code/build in a flag that allows for VMs part of Scale Sets (Azure's autoscale groups) to be returned in the results, if desired. This is a serious limitation of the inventory script atm.

4. Expand on the documentation examples within the azure_rm.py or .ini files. For example, the comments state that to use the --host flag in order to return a single host, you must specify a resource group. I have no idea how to do this based on the limited examples in the docs. Ultimately, I want to know how to slice/dice my inventory when using Ansible & the dynamic inventory script, but I don't know how to filter inventory via the CLI because the flags I can use executing the azure_rm.py directly, don't work when I start to use the `ansible` or `ansible_playbook` cmds. 

Hope this helps.

**Comment by samirageb** [comment]
Also, I just tried using PR #27692 and still got public IP addresses returned, despite forcing everything manually to pull the private IP. 

**Update**
After reviewing PR #27692 further, it's definitely incomplete. It fails to update the ansible host with a private IP and is completely missing any reference to the azure_rm.ini file. This thread's PR however, addresses both of those issues, however the implementation in this PR is slightly clunky.

Personally, I've combined the other naming convention with the logic in this PR to create something more consistent with the current style of the script. (Using True/False instead of adding a 3rd state of 'None'. There will always be a destination IP, so a 3rd state in this case isn't likely needed)

Snippet below
e.g. 
```python
for ip_config in network_interface.ip_configurations:
      host_vars['private_ip'] = ip_config.private_ip_address
      host_vars['private_ip_alloc_method'] = ip_config.private_ip_allocation_method
      if self.prefer_private_ip:
          host_vars['ansible_host'] = ip_config.private_ip_address
      if ip_config.public_ip_address:
          public_ip_reference = self._parse_ref_id(ip_config.public_ip_address.id)
          public_ip_address = self._network_client.public_ip_addresses.get(
          public_ip_reference['resourceGroups'],
          public_ip_reference['publicIPAddresses'])
          if not self.prefer_private_ip:
              host_vars['ansible_host'] = public_ip_address.ip_address
          host_vars['public_ip'] = public_ip_address.ip_address
```
If desired, I can try to find time to do a PR against the latest inventory script, incorporating the 'best' changes from the VM PRs, so move things 1-step closer.

**Comment by thiagocaiubi** [comment]
Hi @samirageb, thanks for your response.
The PR I mentioned before is truly incomplete. I was based in a previous [PR](https://github.com/ansible/ansible/pull/18541) by the author. But he made a mess rebasing the commits so he closed in order to open this incomplete one. 
Sorry for pointing the wrong one, it's on me.

In another inventory PR there was a mention about moving this to some sort of plugin strategy. I don't have enough information about the impact of making any changes to the inventory at the moment.

https://github.com/ansible/ansible/pull/21047#issuecomment-335644601

**Comment by yuwzho** [comment]
@nitzmahone is this related to the inventory plugin? Could you take a look?

**Comment by isaacegglestone** [comment]
@yuwzho 

Looks that way to me see the excerpt below from azure_rm.py, if the network interface has a public ip then host_vars['ansible_host'] gets set to the public ip..

Might have been good in the classic days but not too many people running public IPs everywhere anymore, or at least they shouldn't be.

Really need a private option in the azure_rm.py I think.
Or even just disable IP setting all together because otherwise it is falling back to DNS which works fine for me with machines without public IP addresses.  

            for interface in machine.network_profile.network_interfaces:
                interface_reference = self._parse_ref_id(interface.id)
                network_interface = self._network_client.network_interfaces.get(
                    interface_reference['resourceGroups'],
                    interface_reference['networkInterfaces'])
                if network_interface.primary:
                    if self.group_by_security_group and \
                       self._security_groups[resource_group].get(network_interface.id, None):
                        host_vars['security_group'] = \
                            self._security_groups[resource_group][network_interface.id]['name']
                        host_vars['security_group_id'] = \
                            self._security_groups[resource_group][network_interface.id]['id']
                    host_vars['network_interface'] = network_interface.name
                    host_vars['network_interface_id'] = network_interface.id
                    host_vars['mac_address'] = network_interface.mac_address
                    for ip_config in network_interface.ip_configurations:
                        host_vars['private_ip'] = ip_config.private_ip_address
                        host_vars['private_ip_alloc_method'] = ip_config.private_ip_allocation_method
                        if ip_config.public_ip_address:
                            public_ip_reference = self._parse_ref_id(ip_config.public_ip_address.id)
                            public_ip_address = self._network_client.public_ip_addresses.get(
                                public_ip_reference['resourceGroups'],
                                public_ip_reference['publicIPAddresses'])
                            host_vars['ansible_host'] = public_ip_address.ip_address
                            host_vars['public_ip'] = public_ip_address.ip_address
                            host_vars['public_ip_name'] = public_ip_address.name
                            host_vars['public_ip_alloc_method'] = public_ip_address.public_ip_allocation_method
                            host_vars['public_ip_id'] = public_ip_address.id
                            if public_ip_address.dns_settings:
                                host_vars['fqdn'] = public_ip_address.dns_settings.fqdn

            self._add_host(host_vars)

**Comment by yuwzho** [comment]
duplicate_of #36109

**Pull request closed without merging**
