### PR TITLE
[Backport 2.8] Use different headers for each HTTP method

### LINKED ISSUE #55078: Redfish modules don't work with iDRAC 3.30.30.30
##### SUMMARY
We've updated iDRAC to version 3.30.30.30 and now we are having problems with the redfish modules: 406 Not Acceptable. I _think_ the problem is that get_request in redfish_utils doesn't set an 'Accept' header.
Strictly speaking, this should be an iDRAC bug because [RFC 2068](https://tools.ietf.org/html/rfc2068#page-96) explicitly says:

> If no Accept header field is present, then it is assumed that the client accepts all media types.

But since redfish is based on JSON I think it wouldn't hurt to explicitly set an 'Accept: application/json' header... after all, redfish doesn't understand anything _but_ JSON.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
redfish_utils

##### ANSIBLE VERSION
```
ansible 2.8.0a1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.1 (default, Oct 26 2017, 01:54:52) [GCC 6.3.0]
```
```
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/lenzm02/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
##### CONFIGURATION
```
```
```
```

##### OS / ENVIRONMENT
PowerEdge R740xd, iDRAC version 3.30.30.30

##### STEPS TO REPRODUCE
```
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Gathering BIOS Attribute Facts
      redfish_facts:
        category: Systems
        command: GetSystemInventory
        baseuri: 10.20.30.40
        username: admin
        password: "12345"
```
Run with ```ansible-playbook test.yml```.

##### EXPECTED RESULTS
```
PLAY [localhost] ***************************************************************

TASK [Gathering BIOS Attribute Facts] ******************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS
```
PLAY [localhost] ***************************************************************

TASK [Gathering BIOS Attribute Facts] ******************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "HTTP Error 406 on GET request to 'https://10.20.30.40/redfish/v1/', extended message: 'Not Acceptable'"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### PR DESCRIPTION
**Pull request by mariolenz**
##### SUMMARY
Backport of PR #55193

Fixes #55078

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
redfish_utils

##### ADDITIONAL INFORMATION
(cherry picked from commit f88b2cbe597d34f871ee0b4e43632a41ad485253)

### CODE REVIEW

**Review by billdodd — APPROVED** [review]
Reviewed code. Looks good.

shipit

**Comment by mariolenz** [comment]
Can I

shipit

too?

**Comment by jose-delarosa** [comment]
shipit

**Comment by abadger** [comment]
Code looks fine but this needs a changelog fragment before the backport is merged.  https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs-how-to

**Comment by mariolenz** [comment]
> Code looks fine but this needs a changelog fragment before the backport is merged. https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs-how-to

Better now?

**Comment by abadger** [comment]
Merged for the 2.8.0rc1 release

**Pull request merged**
