### PR TITLE
Fixes "unarchive" and "copy" do not expand pathes correctly

### PR DESCRIPTION
**Pull request by muffl0n**
Proposed fix for #6061. 
I'm new to Ansible and Python, so please be gentle. :)

### CODE REVIEW

**Comment by bcoca** [comment]
you really don't want to expanduser locally for dest, in case the user
doesn't exist or has a different home path.

**Comment by muffl0n** [comment]
Sounds reasonable. Unfortunately I have too little experience with Ansible to really understand how to fix it correctly.

**Comment by jimi-c** [comment]
`expanduser` actually correctly expands based on the correct home path, and if the user doesn't exist it just returns the string as-is (for example, `~foo` doesn't change if the user foo doesn't exist). So I think this is fine and doesn't need to be changed.

**Comment by jimi-c** [comment]
Merged, with one small change - I moved the expanduser calls down as otherwise they were sometimes being passed in `None` when the parameter wasn't set, which caused a traceback. Thanks!

**Comment by muffl0n** [comment]
Thanks for merging!

**Comment by bcoca** [comment]
you still have the problem when the user exists and the homes are different across machines. It is a rare corner case, but I've had it happen.

**Comment by muffl0n** [comment]
So maybe one should expand the src locally and the dest on the target machine?
Today I learned that the action_plugins are called locally while "library/files/copy", for example, is copied to the target machine and executed there. Is this correct?

**Comment by jimi-c** [comment]
Yes, I just had to fix it so that the expanduser call was done in the module, so it should be removed from the action_plugin. I'll take care of it.

**Comment by muffl0n** [comment]
@jimi-c Did you have a chance to take a look at this? I tried to create a bugfix on my own but unfortunately didn't succeed. 

Though I found something to care about when fixing this:
homedir of local user "test": /tmp/test
homedir of remote user "test": /tmp/testuser
Playbook "test-unarchive.yml"

```
- hosts: remote
  tasks:
    - unarchive: src=~test/test.tar.gz dest=~test copy=no
      ignore_errors: True
    - unarchive: src=~test/test.tar.gz dest=~test copy=yes
      ignore_errors: True
```

```
$ ansible-playbook -i test test-unarchive.yml 

PLAY [remote] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [remote]

TASK: [unarchive src=~test/test.tar.gz dest=~test copy=no] ******************** 
failed: [remote] => {"failed": true}
msg: dest '/tmp/test' must be an existing dir, src: /tmp/test/test.tar.gz
...ignoring

TASK: [unarchive src=~test/test.tar.gz dest=~test copy=yes] ******************* 
failed: [remote] => {"failed": true}
msg: dest '/tmp/test' must be an existing dir, src: /tmp/test/test.tar.gz
...ignoring

PLAY RECAP ******************************************************************** 
remote                     : ok=3    changed=0    unreachable=0    failed=0
```

As one can see, dest is always expanded locally.
Whether or not you have to expand the src on the locale machine depends on the parameter copy. This parameter is described by "Should the file be copied from the local to the remote machine?".
So if the file is to be copied from the local machine the source has to be expanded locally. Otherwise it has to be expanded on the remote machine.
Currently it is always expanded locally which is wrong if "copy=yes".

PS: I changed unarchive.py to show the debug output above in 958ff640ccc77d092e982520f37bc7a44a93c928

**Pull request merged**
