### PR TITLE
Map Debian 8 to Python 2

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Map Debian 8 to Python 2

Without this change the interpreter discover algorithm `auto` will choose the next documented Debian version which is Debian 10, which chooses Python 3 per default.
However the Python 3 Version on Debian 8 is 3.4, which is incompatible with Ansible.
Therefore if Python 3 is installed on an Debian 8 host, Ansible will refuse to run with the following message:
```
Ansible requires a minimum of Python2 version 2.6 or Python3 version 3.5. Current version: 3.4.2 (default, Oct  8 2014, 10:45:20) [GCC 4.9.1]
```

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible.legacy.setup

##### ADDITIONAL INFORMATION
As this our first MR please let us know, if there is something we missed.

### CODE REVIEW

**Comment by elara-leitstellentechnik** [comment]
As far as I can tell I did not introduce the CI failures. If I misjudged please let me know.

**Comment by nitzmahone** [comment]
Played with this a bit, and while this does fix the problem for Debian 8, I'm not sure it's the right thing to do in general. The underlying problem is an oversight in the version fallback behavior when a distro has only one entry in the interpreter map, but the version being evaluated is older than that entry. I'm thinking the proper behavior would be to drop back to the normal fallback list, which would also solve the problem in your case (since `/usr/bin/python` is at the top of that list).

We'll talk about this one internally a bit and do something for it, but not sure if it'll be this change or dropping back to the fallback Python list.

**Comment by elara-leitstellentechnik** [comment]
Thanks for taking a look this :) Your solutions sounds like a good idea to me. I just want to note, that including this might be good idea regardless, since the only compatible Python version on Debian 8 will always be Python 2.

**Comment by nitzmahone** [comment]
We discussed in today's IRC meeting- we'll do it this way, and if we end up adding new distros or exposing the map as a configurable option, we'll revisit the underlying behavior for "older than all listed". I've added a changelog and fixed an issue with the tests, and we'll get this merged and backported. Thanks!

**Pull request merged**
