### PR TITLE
Add support for replacing an existing openstack keypair

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY

Nova doesn't allow updating keypairs, so one must delete and recreate. Add a 'replace' state to allow
replacing a keypair with new content if necessary.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

os_keypair

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
This is a follow up to https://github.com/ansible/ansible/pull/30565, to deal with merge conflict, lint failures

**Review by cloudnull — APPROVED** [review]
the change looks fine, but its failing CI.

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now c69b36f864ae9c38ca990b759e8b75071b59cbac

**Review by cloudnull — APPROVED** [review]

**Review by cloudnull — APPROVED** [review]
shipit

**Pull request merged**
