### PR TITLE
Make Cloudstack integration tests clean up properly

### PR DESCRIPTION
**Pull request by dpassante**
##### SUMMARY

Make Cloudstack integration tests clean up properly.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

cloudstack

### CODE REVIEW

**Comment by dpassante** [comment]
I have found several integration tests that do not clean up properly.
I will append fixes to the PR.

**Comment by dpassante** [comment]
ready_for_review

**Comment by onitake** [comment]
This is certainly a good addition.
There's one thing that should be kept in mind, however: What happens when tests fail? Are these cleanup tasks still run?

**Comment by dpassante** [comment]
@onitake It is indeed a good practice. If only all the admins thought about it for their production playbooks!

In our case, the cloudstack-sim image is destroyed when tests fail. No need to clean up.

**Pull request closed without merging**
