### PR TITLE
Add sanity test to require elements entry when argument type=list

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY

Add sanity test to require elements entry when argument type=list

While support for "elements" was added a while back, it's not consistently used, even in new modules.  Add a sanity check to improve our use of it.  (Combined with #66385 should ensure that our documentation of arguments is more complete)

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/main.py

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
shipit

**Review by samccann — APPROVED** [review]
docs portion LGTM

**Review by jillr — APPROVED** [review]

**Review by mattclay — APPROVED** [review]

**Comment by gundalow** [comment]
@tremble Thank you, if you could please rebase we can get this merged.

**Review by s-hertel — APPROVED** [review]

**Comment by felixfontein** [comment]
Thanks everyone for improving the sanity tests (both here and in #66385)! :)

**Comment by AlanCoding** [comment]
People might be coming here because they saw new failures pop up, and will be looking for an example for how to fix it...

https://github.com/ansible/ansible/blob/308723c3ca1122363e419070f1fa1d76ff5611a9/lib/ansible/modules/identity/ipa/ipa_role.py#L33-L40

https://github.com/ansible/ansible/blob/308723c3ca1122363e419070f1fa1d76ff5611a9/lib/ansible/modules/identity/ipa/ipa_role.py#L281

This is asking modules to add the expected type of elements inside of a list.

**Comment by tremble** [comment]
Thanks @AlanCoding - 

Specifically, when an argument defines ``type='list'``, you should also define what type of objects you expect that list to contain using ``elements=...``, this will then validate that all entries in that list match the type provided in elements.

In your example it's line 40 which needed to be added, and the ``elements='str'`` entry  on line 281.

**Pull request merged**
