### PR TITLE
ec2 inventory now include Ansible 1.3 style _meta data each host.

### PR DESCRIPTION
**Pull request by lorrin**

### CODE REVIEW

**Comment by jctanner** [comment]
@lorrin can you give a little more explanation of what this does?

**Comment by lorrin** [comment]
@jctanner, thanks for looking. It sets the ec2 properties as host variables. It's possible this is a case of me not groking Ansible correctly, since I'm fairly new to it. I wanted access to the EC2 instance name and other tags. I found that even if I gathered facts and ran ec2_facts (slow!) I still couldn't get my hands on the tags. This seemed silly, since the ec2.py inventory plug-in had had them initially! I discovered that Ansible supports passing host variables in the inventory JSON, but the ec2.py wasn't doing it. (See
http://www.ansibleworks.com/docs/developing_inventory.html#tuning-the-external-inventory-script). This patch populates _meta.hostvars.<host> with all the data already fetched from boto, allowing subsequent access to it.

**Comment by jctanner** [comment]
```
./ec2.py --refresh
{
  "_meta": {
    "hostvars": {
      "54.200.88.160": {
        "ec2__in_monitoring_element": false, 
        "ec2_ami_launch_index": "0", 
        "ec2_architecture": "x86_64", 
        "ec2_client_token": "", 
        "ec2_dns_name": "ec2-54-200-88-160.us-west-2.compute.amazonaws.com", 
        "ec2_ebs_optimized": false, 
        "ec2_eventsSet": "", 
        "ec2_group_name": "", 
        "ec2_hypervisor": "xen", 
        "ec2_id": "i-a9538a9f", 
        "ec2_image_id": "ami-d03ea1e0", 
        "ec2_instance_profile": "", 
        "ec2_instance_type": "t1.micro", 
        "ec2_ip_address": "54.200.88.160", 
        "ec2_item": "", 
        "ec2_kernel": "aki-fc37bacc", 
        "ec2_key_name": "jtanner-ec2-key1", 
        "ec2_launch_time": "2013-12-05T21:42:54.000Z", 
        "ec2_monitored": false, 
        "ec2_monitoring": "", 
        "ec2_monitoring_state": "disabled", 
        "ec2_persistent": false, 
        "ec2_platform": "", 
        "ec2_previous_state": "", 
        "ec2_previous_state_code": 0, 
        "ec2_private_dns_name": "ip-172-31-46-196.us-west-2.compute.internal", 
        "ec2_private_ip_address": "172.31.46.196", 
        "ec2_public_dns_name": "ec2-54-200-88-160.us-west-2.compute.amazonaws.com", 
        "ec2_ramdisk": "", 
        "ec2_reason": "", 
        "ec2_region": "us-west-2", 
        "ec2_requester_id": "", 
        "ec2_root_device_name": "/dev/sda1", 
        "ec2_root_device_type": "ebs", 
        "ec2_security_group_ids": "sg-1fd82f70", 
        "ec2_security_group_names": "default", 
        "ec2_sourceDestCheck": "true", 
        "ec2_spot_instance_request_id": "", 
        "ec2_state": "running", 
        "ec2_state_code": 16, 
        "ec2_state_reason": "", 
        "ec2_subnet_id": "subnet-d13754ba", 
        "ec2_tag_foo": "bar", 
        "ec2_virtualization_type": "paravirtual", 
        "ec2_vpc_id": "vpc-d33754b8"
      }
    }
  }, 
  "ec2": [
    "54.200.88.160"
  ], 
  "i-a9538a9f": [
    "54.200.88.160"
  ], 
  "key_jtanner-ec2-key1": [
    "54.200.88.160"
  ], 
  "mysql1": [
    "mysql1.chegji5plckz.us-west-2.rds.amazonaws.com"
  ], 
  "rds": [
    "mysql1.chegji5plckz.us-west-2.rds.amazonaws.com"
  ], 
  "rds_mysql": [
    "mysql1.chegji5plckz.us-west-2.rds.amazonaws.com"
  ], 
  "rds_parameter_group_default_mysql5_6": [
    "mysql1.chegji5plckz.us-west-2.rds.amazonaws.com"
  ], 
  "security_group_default": [
    "54.200.88.160"
  ], 
  "tag_foo_bar": [
    "54.200.88.160"
  ], 
  "type_db_t1_micro": [
    "mysql1.chegji5plckz.us-west-2.rds.amazonaws.com"
  ], 
  "type_t1_micro": [
    "54.200.88.160"
  ], 
  "us-west-2": [
    "54.200.88.160", 
    "mysql1.chegji5plckz.us-west-2.rds.amazonaws.com"
  ], 
  "us-west-2a": [
    "54.200.88.160"
  ], 
  "us-west-2b": [
    "mysql1.chegji5plckz.us-west-2.rds.amazonaws.com"
  ]
}
```

**Comment by jctanner** [comment]
@lorrin thank you!

**Comment by lorrin** [comment]
@jctanner thanks for the review!

**Comment by lorrin** [comment]
My apologies, this breaks loading inventory from cache. I'll submit a new pull request with a fix.

**Pull request merged**
