### PR TITLE
Typo in OpenBSD Python version

### PR DESCRIPTION
**Pull request by pefmeister**
##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sivel** [comment]
This isn't a typo, it was an intentional switch to 3.7: 53cd0bdd29e087140d303ce23eac6e4eabfcc94d

The other 2.7 references should be bumped to 3.7.

**Comment by pefmeister** [comment]
> This isn't a typo, it was an intentional switch to 3.7: [53cd0bd](https://github.com/ansible/ansible/commit/53cd0bdd29e087140d303ce23eac6e4eabfcc94d)
> 
> The other 2.7 references should be bumped to 3.7.

Thanks for the hint! I just did a test drive on a plain OpenBSD 6.8 system with a playbook that uses mostly core commands, but failed while using community.postgresql, since that has a dependency on py-psycopg2 which uses Python 3.8. While using that one did work for base and community. So bumping it to 3.8 could be a viable alternative, too.

Cheers
Stephan

**Comment by pefmeister** [comment]
In the oncoming release 6.9 (should be out any week now) 3.7 is retired and Python 3 with 3.8 is the new default.

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
cc @acozine this is definitely a typo if we look at the context of the document (a bit above)

**Comment by Andersson007** [comment]
ah, @acozine sorry I didn't see the @sivel 's comment.

**Comment by Andersson007** [comment]
we should change the block:
```
The following example installs Python 2.7 which includes the json library required for full functionality of Ansible. On your control machine you can execute the following for most versions of FreeBSD:

ansible -m raw -a "pkg install -y python27" mybsdhost1
Or for OpenBSD:

ansible -m raw -a "pkg_add python%3.7"
```
it sounds like "run it on OpenBSD to install python 2.9"

**Comment by pefmeister** [comment]
I'd leave out the version in the first paragraph and update the OpenBSD command to reflect that 3.8 (!) should be used. Otherwise we have to change it in a couple of weeks again.

**Comment by acozine** [comment]
@pefmeister thanks for this - if you open a new PR when the new version comes out, you can post a note on freenode IRC in the #ansible-docs channel and we'll take a look.

**Pull request closed without merging**
