### PR TITLE
Fix references to Ansible Collections Overview

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fix the references to Ansible Collections Overview

The current reference doesn't work.

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
The current ref doesn't work. I'm not 100% sure that the ref i added was originally implied but i know the only place with FAQ:)
@gundalow @samccann @acozine @felixfontein could you please take a look

**Review by felixfontein — APPROVED** [review]
Can you grep for the old URL to see whether there are more such errors? I remember that we already fixed this once.

**Comment by Andersson007** [comment]
> Can you grep for the old URL to see whether there are more such errors? I remember that we already fixed this once.

@felixfontein good spot! thanks, found 3 more broken refs

**Review by felixfontein — APPROVED** [review]

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
We need to remove the plugins notes and update the plugins lists some how to show where they've all moved to...

**Comment by Andersson007** [comment]
@felixfontein @samccann thanks for reviewing and merging!

**Comment by samccann** [comment]
... ansible-doc -t cliconf -l  etc works to display the plugins in 2.10 so that's what we should add under the Plugin lists.

**Pull request merged**
