### PR TITLE
Add NetApp ONTAP SVM module

### PR DESCRIPTION
**Pull request by timuster**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

NetApp ONTAP SVM module

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Adding na_cdot_svm.py, a module to manage NetApp SVMs. The design was based on the existing NetApp E-Series modules.

```

```

### CODE REVIEW

**Comment by hulquest** [comment]
LGTM.
shipit

**Comment by hulquest** [comment]
shipit

**Comment by lmprice** [comment]
shipit

**Comment by lmprice** [comment]
shipit

**Pull request merged**
