### PR TITLE
docker_*: hint at DOCKER_CONFIG environment variable

### LINKED ISSUE #48874: Consistent use of docker config path for docker modules
##### SUMMARY

Ansible module `docker_login` takes `config_path` as a parameter. This is generally a good idea as it's not always desirable to write to the default `$HOME/.docker/config.json` file.

This parameter is, however, missing from any other docker modules. The only way to use alternate docker config file with modules like `docker_image` or `docker_container` is to use environment variable `DOCKER_CONFIG`.
Confusingly enough, `DOCKER_CONFIG` needs to point to a **directory** containing the docker `config.json` file. This is poorly documented and unnecessarily confusing. See included snippet for an example. 

The proposed solutions:
 * add `config_path` parameter to all docker modules
 * alternatively, remove `config_path` from `docker_login` module and document the usage of
    `DOCKER_CONFIG` environment variable for all docker modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_*

##### ADDITIONAL INFORMATION

```yaml
---
- vars:
    registry: remote-docker-registry.host.example
    config_dir: /tmp
  block:
  - name: Login to docker registry
    docker_login:
      config_path: "{{ config_dir }}/config.json"
      registry: "{{ registry }}"
      username: username
      password: password
      email: no-reply@localhost.localdomain

  - docker_image:
      name: "{{ registry }}/image:latest"
      repository: "{{ registry }}/image:v1"
    environment:
      DOCKER_CONFIG: "{{ config_dir }}"

```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Provides hint for `DOCKER_CONFIG` environment variable directly supported by docker-py. Fixes #48874.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docker_config
docker_container_facts
docker_container
docker_image_facts
docker_image
docker_login
docker_network
docker_prune
docker_secret
docker_service
docker_swarm
docker_swarm_service
docker_volume

### CODE REVIEW

**Comment by felixfontein** [comment]
The Docker module docs fragments are currently not managed by us (will hopefully change with #49679), so manually CC'ing @akshay196 @chouseknecht @danihodovic @dariko @jwitko @kassiansun @tbouvet @DBendit

**Review by DBendit — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
Unrelated comment to trigger ansibot reprocessing.

**Comment by felixfontein** [comment]
bot_status

**Review by resmo — APPROVED** [review]
LGTM

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@felixfontein @resmo @DBendit Thank you :)
Merged into `devel` for release in Ansible 2.8

**Comment by felixfontein** [comment]
@DBendit @resmo thanks for your reviews!
@gundalow thanks for merging!

**Pull request merged**
