### PR TITLE
Azure load balancer support

### PR DESCRIPTION
**Pull request by trstringer**
##### SUMMARY

This pull request adds support for Azure load balancers

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- azure_rm_loadbalancer
- azure_rm_loadbalancer_facts

##### ANSIBLE VERSION

```
ansible 2.4.0 (az-loadbalancer d73f0b98b3) last updated 2017/06/26 10:37:08 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/trstringer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/trstringer/dev/ansible-dev/ansible/lib/ansible
  executable location = /home/trstringer/dev/ansible-dev/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

### CODE REVIEW

**Comment by trstringer** [comment]
@haroldwongms or @nitzmahone could I get a review on this?

**Comment by trstringer** [comment]
bot_status

**Comment by trstringer** [comment]
As per a discussion with @mattclay and team, we will be keeping this PR open for the ability to test out the integration testing in Azure.

cc // @nitzmahone @haroldwongms

**Comment by haroldwongms** [comment]
Should include the ability to have user provide names for the load balancing rule and NAT rule.  Also, enable ability to specify enable_floating_ip for load balancing rule as that can only be done at provisioning time.

**Comment by codyja** [comment]
I think the azure_rm_networkinterface also needs to be updated to support the **loadBalancerBackendAddressPools** id. Would this also support multiple Load Balancing Rules?

Thanks for the work btw!

**Comment by haroldwongms** [comment]
shipit

**Review by nitzmahone — APPROVED** [review]

**Comment by mattclay** [comment]
@tstringer I've disabled these integration tests in CI since they're failing intermittently:

https://app.shippable.com/github/ansible/ansible/runs/35529/40/tests

Once that issue has been resolved the tests can be re-enabled.

**Comment by trstringer** [comment]
@mattclay thank you! I'll look into those failures. 👍

**Pull request merged**
