### PR TITLE
improve output formating for playbook

### PR DESCRIPTION
**Pull request by davehatton**
Outut from running a playbook looks a little awkward to me - this alters it slightly.
## Before

 ANSIBLE_SSH_ARGS="" ANSIBLE_REMOTE_USER=ansible ansible-playbook ~/playbooks/config_delta/config.delta.yml -v -c ssh

PLAY [kvm] ********************\* 

SETUP PHASE ********************\* 

ok: [office.starground.co.uk]

ok: [jabber.starground.co.uk]

ok: [zabbix.starground.co.uk]

TASK: [fetch src=/etc/passwd dest=/data/transit/configs] ********************\* 

ok: [jabber.starground.co.uk] => {"changed": false, "md5sum": "cbfc11f217062bb0eab9e4a7a0359631"}
ok: [zabbix.starground.co.uk] => {"changed": false, "md5sum": "4bdb5afeca6c234d970c8aee6707d30b"}
ok: [office.starground.co.uk] => {"changed": false, "md5sum": "522e1b4769cf88ae53cdcd2dce281475"}
TASK: [fetch src=/etc/bob dest=/data/transit/configs] ********************\* 

ok: [jabber.starground.co.uk] => {"changed": false, "msg": "missing remote file"}
ok: [zabbix.starground.co.uk] => {"changed": false, "msg": "missing remote file"}
ok: [office.starground.co.uk] => {"changed": false, "msg": "missing remote file"}
TASK: [fetch src=/etc/group dest=/data/transit/configs] ********************\* 

ok: [office.starground.co.uk] => {"changed": false, "md5sum": "efd2c18fa8c5ff3938b1c794158ccfe6"}
ok: [jabber.starground.co.uk] => {"changed": true, "md5sum": "0f17fd9b46ad65a234017b5d8b646ccd"}
ok: [zabbix.starground.co.uk] => {"changed": true, "md5sum": "fbfd8e3b160604c41afa32ab662c96a7"}
TASK: [fetch src=/etc/sysctl.conf dest=/data/transit/configs] ********************\* 

ok: [jabber.starground.co.uk] => {"changed": true, "md5sum": "c97839af771c8447b9fc23090b4e8d0f"}
ok: [office.starground.co.uk] => {"changed": true, "md5sum": "c97839af771c8447b9fc23090b4e8d0f"}
ok: [zabbix.starground.co.uk] => {"changed": true, "md5sum": "c97839af771c8447b9fc23090b4e8d0f"}
TASK: [fetch src=/etc/centos-release dest=/data/transit/configs] ********************\* 

ok: [jabber.starground.co.uk] => {"changed": true, "md5sum": "2cefca706f95cdd38a06a990780e9709"}
ok: [office.starground.co.uk] => {"changed": true, "md5sum": "2cefca706f95cdd38a06a990780e9709"}
ok: [zabbix.starground.co.uk] => {"changed": true, "md5sum": "2cefca706f95cdd38a06a990780e9709"}
PLAY RECAP ********************\* 

jabber.starground.co.uk        : ok=   6 changed=   3 unreachable=   0 failed=   0 
office.starground.co.uk        : ok=   6 changed=   2 unreachable=   0 failed=   0 
zabbix.starground.co.uk        : ok=   6 changed=   3 unreachable=   0 failed=   0 

---
## After

ANSIBLE_SSH_ARGS="" ANSIBLE_REMOTE_USER=ansible ansible-playbook ~/playbooks/config_delta/config.delta.yml -c ssh -v

PLAY [kvm] ********************\* 

SETUP PHASE ********************\* 
ok: [jabber.starground.co.uk]
ok: [office.starground.co.uk]
ok: [zabbix.starground.co.uk]

TASK: [fetch src=/etc/passwd dest=/data/transit/configs] ********************\* 
ok: [office.starground.co.uk] => {"changed": false, "md5sum": "522e1b4769cf88ae53cdcd2dce281475"}
ok: [jabber.starground.co.uk] => {"changed": false, "md5sum": "cbfc11f217062bb0eab9e4a7a0359631"}
ok: [zabbix.starground.co.uk] => {"changed": false, "md5sum": "4bdb5afeca6c234d970c8aee6707d30b"}

TASK: [fetch src=/etc/bob dest=/data/transit/configs] ********************\* 
ok: [jabber.starground.co.uk] => {"changed": false, "msg": "missing remote file"}
ok: [zabbix.starground.co.uk] => {"changed": false, "msg": "missing remote file"}
ok: [office.starground.co.uk] => {"changed": false, "msg": "missing remote file"}

TASK: [fetch src=/etc/group dest=/data/transit/configs] ********************\* 
ok: [jabber.starground.co.uk] => {"changed": false, "md5sum": "0f17fd9b46ad65a234017b5d8b646ccd"}
ok: [office.starground.co.uk] => {"changed": false, "md5sum": "efd2c18fa8c5ff3938b1c794158ccfe6"}
ok: [zabbix.starground.co.uk] => {"changed": false, "md5sum": "fbfd8e3b160604c41afa32ab662c96a7"}

TASK: [fetch src=/etc/sysctl.conf dest=/data/transit/configs] ********************\* 
ok: [jabber.starground.co.uk] => {"changed": false, "md5sum": "c97839af771c8447b9fc23090b4e8d0f"}
ok: [office.starground.co.uk] => {"changed": false, "md5sum": "c97839af771c8447b9fc23090b4e8d0f"}
ok: [zabbix.starground.co.uk] => {"changed": false, "md5sum": "c97839af771c8447b9fc23090b4e8d0f"}

TASK: [fetch src=/etc/centos-release dest=/data/transit/configs] ********************\* 
ok: [jabber.starground.co.uk] => {"changed": false, "md5sum": "2cefca706f95cdd38a06a990780e9709"}
ok: [office.starground.co.uk] => {"changed": false, "md5sum": "2cefca706f95cdd38a06a990780e9709"}
ok: [zabbix.starground.co.uk] => {"changed": false, "md5sum": "2cefca706f95cdd38a06a990780e9709"}

PLAY RECAP ********************\* 
jabber.starground.co.uk        : ok=6    changed=0    unreachable=0    failed=0
office.starground.co.uk        : ok=6    changed=0    unreachable=0    failed=0
zabbix.starground.co.uk        : ok=6    changed=0    unreachable=0    failed=0

---

### CODE REVIEW

**Comment by mpdehaan** [comment]
I don't recall there being whitespace errors before, I'll have to check.

I also use cowsay mode.

**Comment by davehatton** [comment]
even with cowsay the spacing on PLAY RECAP looked out for me.

**Comment by mpdehaan** [comment]
ok, I will look

**Comment by dagwieers** [comment]
I don't understand why the -v output is more condensed (albeit more verbose) than the normal output. In the normal output I get:

```
PLAY [kvm] *********************

SETUP PHASE ********************* 

ok: [jabber.starground.co.uk]

ok: [office.starground.co.uk]

ok: [zabbix.starground.co.uk]

TASK: [fetch src=/etc/passwd dest=/data/transit/configs] ********************* 

ok: [office.starground.co.uk]

ok: [jabber.starground.co.uk]

ok: [zabbix.starground.co.uk]

PLAY RECAP ********************* 

jabber.starground.co.uk : ok=1 changed=0 unreachable=0 failed=0

office.starground.co.uk : ok=1 changed=0 unreachable=0 failed=0

zabbix.starground.co.uk : ok=1 changed=0 unreachable=0 failed=0




PLAY [something] *********************
```

And 4 blanks lines in between plays :-/

**Comment by mpdehaan** [comment]
Yeah, so dag is getting what I get in normal mode (as opposed to what Dave had posted -- one blank line between everything -- I think github or something changed the formatting). 

I'll take a look and see what is up, I mostly want them consistent and 

play1output
play1output
play2header

play2output

is clearly right out.  I don't remember it looking like that though.

**Comment by davehatton** [comment]
Yes, dag is correct, I get the same double spacing without verbose mode - the pull request  fixes that as well

**Comment by mpdehaan** [comment]
I'd also like the "=>" to line up, to do that we'd need to keep track of the longest host name, might be somewhat non-trivial

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
