### PR TITLE
atomic_move fixes

### PR DESCRIPTION
**Pull request by bcoca**
changed atomic_move to be more 'optimistic' which helps deal with corner cases and avoid usless work.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Initially looks good, but as this is super critical, I want to do some testing before merging it.  Large PR queue at the moment so may be just a little bit.

I would be interested in understanding what corner case problems you detected before deciding to make changes, so I can know what kind of bugs this may resolve.

Thanks!

**Comment by bcoca** [comment]
The cases came complaints made in IRC and/or mailing list, specifically
when tmp dir and dest are in same partition but we are not allowed to
create temp files in dest directory due to chflags or selinux.

Knowing how much core functionality depends on this file,copy,template, etc
I expect and welcome heavy testing. I hope that this will prevent errors in
the simple case and only use the workarounds when needed, not just by
default.

On Fri, Jul 12, 2013 at 9:57 PM, Michael DeHaan notifications@github.comwrote:

> Initially looks good, but as this is super critical, I want to do some
> testing before merging it. Large PR queue at the moment so may be just a
> little bit.
> 
> I would be interested in understanding what corner case problems you
> detected before deciding to make changes, so I can know what kind of bugs
> this may resolve.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3519#issuecomment-20912935
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
this is one of the corner cases that will benefit #3335

**Comment by mpdehaan** [comment]
tested this yesterday but apparently didn't merge, merging now, thank you!

**Pull request closed without merging**
