### PR TITLE
Improve behaviour with error_on_undefined_vars

### PR DESCRIPTION
**Pull request by psvo**
- pass fail_on_undefined flag on recursive calls to template function,
  so more undefined variables are catched
- raise correct exception from template_from_string function

### CODE REVIEW

**Comment by psvo** [comment]
I just found this pull request is labeled with 'needs_info', but there is no comment explaining what info is needed. Am I missing something? Thanks.

**Comment by mpdehaan** [comment]
Sorry about not leaving a comment.

Can you provide information on how to reproduce a scenario where this change will show something different?

What is the symptom of point #2 and how do I reproduce it?

**Comment by psvo** [comment]
> Can you provide information on how to reproduce a scenario where this change will show something different?

The simplest case is probably the following:

```
# cat hosts
localhost

# cat group_vars/all.yml 
b: "{{ a }}"

# cat test.yml
- hosts: all
  tasks:
  - debug: msg="{{ b }}"
```

Without my patch udefined variable "a" is not detected:

```
# $ ansible-playbook -c local -i hosts test.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg="{{b}}"] ***************************************************** 
ok: [localhost] => {"msg": "{{a}}"}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

With my patch undefined variable "a" is detected:

```
# ansible-playbook -c local -i hosts test.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg="{{b}}"] ***************************************************** 
fatal: [localhost] => One or more undefined variables: 'a' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/tmp/ansible/test.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0   
```

> What is the symptom of point #2 and how do I reproduce it?

Will look further into this and will post update. It's possible it was triggered only with partial patch. Anyway IMHO this part of code is completely useless or it should raise custom exception. ;-)

**Comment by psvo** [comment]
> > What is the symptom of point #2 and how do I reproduce it?
> 
> Will look further into this and will post update. It's possible it was triggered only with partial patch. Anyway IMHO this part of code is completely useless or it should raise custom exception. ;-)

I was unable to reproduce problem which si "solved" by point #2. So we can probably assume this part of patch is not needed. Original symptom was dying with exception jinja2.exceptions.UndefinedError.

So should I remove it from patch? I feel this version is more robust, but removing it is not a problem.

I would prefer to keep removal of comment "this shouldn't happen..." as this code path is actualy triggered by supplied playbook example.

**Comment by mpdehaan** [comment]
Sure if you would like to update this and send in another that is fine.

**Pull request closed without merging**
