### PR TITLE
Correct usage for shutil.rmtree

### LINKED ISSUE #31225: ansible git fails when archive is used
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`ansible/modules/source_control/git.py`

##### ANSIBLE VERSION

```
  config file = None
  configured module search path = [u'/Users/tasos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
`empty`

##### OS / ENVIRONMENT
macOS High Sierra: 10.13 (17A365)

##### SUMMARY
I use the following:
```yaml
- name: Local repo clone
  git:
    repo: <private repo>
    dest: /tmp/la
    archive: /tmp/la.tar.gz
    version: HEAD
    force: yes
  delegate_to: localhost
```
And I get this error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'shutil' has no attribute 'remove'
fatal: [bench-local -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/jt/2m56cw492n7csdyzx923526r0000gp/T/ansible_wd2oquw9/ansible_module_git.py\", line 1179, in <module>\n    main()\n  File \"/var/folders/jt/2m56cw492n7csdyzx923526r0000gp/T/ansible_wd2oquw9/ansible_module_git.py\", line 1165, in main\n    create_archive(git_path, module, dest, archive, version, repo, result)\n  File \"/var/folders/jt/2m56cw492n7csdyzx923526r0000gp/T/ansible_wd2oquw9/ansible_module_git.py\", line 946, in create_archive\n    shutil.remove(tempdir)\nAttributeError: module 'shutil' has no attribute 'remove'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/Users/tasos/XcodeFiles/hipeds/varan-tocs-artifact-tasos/provisioning/setup.retry
```

##### EXPECTED RESULTS
Not failing

##### Solution?
I found those two lines [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/git.py#L947) and [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/git.py#L953) to use `shutil.remove(tempdir)`. By replacing `shutil.remove(tempdir)` with `shutil.rmtree(tempdir)`, everything seems to work.

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix adds correct usage of shutil.rmtree in git module

Fixes: #31225

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/source_control/git.py

##### ANSIBLE VERSION
```
2.5devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by andronat** [comment]
I think a unit test should be introduced that exercise those lines (like the example I gave in #31225).

**Comment by Akasurde** [comment]
ready_for_review

**Review by mkrizek — APPROVED** [review]
Looks good to me :+1:

**Comment by mattclay** [comment]
CI failure in integration test `test/integration/targets/git/tasks/archive.yml:6`:

'ansible_distribution_major_version' is undefined

This error occurs on FreeBSD and macOS.

**Comment by abadger** [comment]
cherrypicked to stable-2.4 for 2.4.1rc2

**Pull request merged**
