### PR TITLE
win_domain_group_membership - Fix to a fix in extra_args

### LINKED ISSUE #58940: win_domain_group_membership add fails with domain credentials
##### SUMMARY
win_domain_group_membership module gives error when you add members to the group when domain_username/domain_password specified. I am trying to run the module from a windows instance joined to the AD domain controller.

I can run the same from powershell and it works. 
Once added the usernames to the group, win_domain_group_membership (pure option) can delete the user. Pure option is deleting the user properly but cannot add any user. I think somewhere in add part passing credentials are not working properly.
It works when run directly on domain controllers (no need for domain_username/password args).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_domain_group_membership
##### ANSIBLE VERSION

```paste below
2.8.1
2.8.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OS is windows 2019 AWS base AMI

##### STEPS TO REPRODUCE

```yaml
- name: Add UserName to GroupName
  win_domain_group_membership:
    domain_username: '{{ domain_username }}'
    domain_password: '{{ domain_password }}'
    name: groupName
    members:
      - "userName"
    state: pure
```

##### EXPECTED RESULTS

```
ok: [3.00.00.00] => (item={'key': 'groupName, 'value': {'description': 'desc', 'path': 'OU=ra,OU=role,OU=Groups,OU=random'}}) => {
    "added": [],
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "key": "groupName",
        "value": {
            "description": "desc",
            "path": "OU=ra,OU=role,OU=Groups,OU=random"
        }
    },
    "members": [userName],
    "removed": []
}
```

##### ACTUAL RESULTS

```
The full traceback is:
The server has rejected the client credentials.
At line:55 char:21
+ ... up_member = Get-ADObject -Filter "SamAccountName -eq '$member' -and $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Get-ADObject], AuthenticationException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.Security.Authentication.AuthenticationException,Microsoft.ActiveDirectory.Management.Commands.GetADObject

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 55

System.Security.Authentication.AuthenticationException: The server has rejected the client credentials. ---> System.ServiceModel.Security.SecurityNegotiationException: The server has rejected the client credentials. ---> System.Security.Authentication.InvalidCredentialException: The server has rejected the client credentials. ---> System.ComponentModel.Win32Exception: The logon attempt failed
   --- End of inner exception stack trace ---
   at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty& remoteSecurity)
   --- End of inner exception stack trace ---

Server stack trace:
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty& remoteSecurity)
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgrade(Stream stream)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgrade(StreamUpgradeInitiator upgradeInitiator, IConnection& connection, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.ActiveDirectory.WebServices.Proxy.Resource.Get(Message request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   --- End of inner exception stack trace ---
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowAuthenticationRelatedExceptionIfAny(CommunicationException exception)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.Search(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperations.Search(ADSessionHandle handle, ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.GetRootDSE()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetRootDSE()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetConnectedStore()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetCmdletSessionInfo()
   at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
fatal: [3.00.00.00]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: The server has rejected the client credentials."
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************
3.00.00.00              : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### PR DESCRIPTION
**Pull request by ShachafGoldstein**
##### SUMMARY
Fixes: #58940

PR #57429 fixed original issue with the worng name.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_domain_group_membership .ps1

##### ADDITIONAL INFORMATION
Not adding a fragment since there is already one in the original PR

### CODE REVIEW

**Comment by bazimov** [comment]
Thank you!!!

**Comment by ShachafGoldstein** [comment]
> Thank you!!!

No no, thank you 👍

**Comment by jborean93** [comment]
Can't see if the original PR got backported, if it did we should also backport this.

**Comment by ShachafGoldstein** [comment]
> Can't see if the original PR got backported, if it did we should also backport this.

Wasn't

**Pull request merged**
