### PR TITLE
Standardizing the module

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I personally find the options that the service module accepts difficult to relate to. Things like "list_items" may not make sense to people. I think we should get rid of it.

**Comment by mpdehaan** [comment]
Thanks for doing this.  

list_items was actually "list" before.  I completely agree with you about it being confusing.  Since list items just outputs the results of the "status" command, I am fine with doing away with "list" provided the output from status is always included in a successful return.   Not all services respond to "status" but that string should be relatively short if they do not.   (We've talked about a way to pass in a pattern for checking service status from ps if it does not support status and we may do that later)

Let's just let enable should just take "yes" or "no", since this is what the rest of the options in Ansible usually do.   It was kind of silly of me to check all of those before.

If you want to tweak those two things I'll apply this.

Thanks!

**Comment by mpdehaan** [comment]
I'm merging this and removing list=status now...

**Comment by mpdehaan** [comment]
ok also fixed it so state was required and a few things, testing would be great.  Thanks!

**Comment by ghost** [comment]
Sorry I could not work on it earlier. I have a question though: what is the difference between states "started" and "running"?

**Comment by mpdehaan** [comment]
they are just aliases for one another.  The docs will just mention one or the other.

**Comment by mpdehaan** [comment]
also, no problem -- you have been a huge help in porting all of these, appreciate it!

**Pull request closed without merging**
