### PR TITLE
register: fail when invalid var name is specified

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Related https://github.com/ansible/ansible/issues/56042

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`lib/ansible/executor/task_executor.py`

### CODE REVIEW

**Review by bcoca — APPROVED** [review]

**Comment by bcoca** [comment]
we might also want to check against INVALID_VARIABLE_NAMES

**Comment by sivel** [comment]
This can be for a later PR, but we need to extend this to all variables.  We enforce it for `vars` in a playbook also, but not for extra vars, or inventory, etc...

But this is a step in the right direction.

See:
* https://github.com/ansible/ansible/issues/42561
* https://github.com/ansible/ansible/commit/5a5b9f2

> TODO: add this to VariableManager to validate vars loaded from files too

**Review by sivel — APPROVED** [review]

**Comment by bcoca** [comment]
yeah, fine with PR as is, just made comment/note for future

**Review by bcoca — APPROVED** [review]

**Comment by samdoran** [comment]
@mkrizek Do we have plans to backport this to `stable-2.7`? This also (properly) raises an error when trying to register variables that begin with a number rather than silently proceeding.

**Pull request merged**
