### PR TITLE
[cloud] ec2_vpc_route_table: ignore routes without DestinationCidrBlock - fixes #37003

### LINKED ISSUE #37003: ec2_vpc_route_table does not support vpc_endpoint in 2.5.0rc1
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_vpc_route_table

##### ANSIBLE VERSION
```
ansible 2.5.0rc1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/cloud_supervisor/releases/20180305095234/venv/lib/python3.5/site-packages/ansible
  executable location = /opt/cloud_supervisor/releases/20180305095234/venv/bin/ansible
  python version = 3.5.3 (default, Apr 22 2017, 00:00:00) [GCC 4.8.4]
```

##### CONFIGURATION
```
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
In my AWS route table definition, I have routes related to a VPC endpoint. These routes have no CIDR block definition.
In the ec2_vpc_route_table code, to see if a route is the same (in order possibly to delete them, or update rather than create), the DestinationCidrBlock attribute is used. On VPC endpoint routes, this attribute is not set.

In ansible < 2.5 I think these lines were simply ignored (which was fine by me since ec2_vpc_route_table does not handle vpc endpoint routes AFAIK)

I tracked it down to the following change
```patch
 def route_spec_matches_route_cidr(route_spec, route):
-    cidr_attr = 'destination_cidr_block'
-    return route_spec[cidr_attr] == getattr(route, cidr_attr)
+    return route_spec['DestinationCidrBlock'] == route['DestinationCidrBlock']
```

oddly enough my git log points to commit a685b621cdf  but this commit does not have this change when I browse it on github

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Fixes #37003. Regression introduced when porting the module from boto to boto3.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py

##### ANSIBLE VERSION
```
2.6.0
```

### CODE REVIEW

**Comment by willthames** [comment]
Should there be a test for this change? It does look good to me but a test would give me greater confidence before merging.

**Comment by s-hertel** [comment]
Added a test to ensure a VPC endpoint associated with a route table doesn't result in traceback (which is what happens now but not prior to 2.5) with the ec2_vpc_route_table module. It's going to need CI permissions added.

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
Looks good, pending CI updates.

**Comment by s-hertel** [comment]
bot_status

**Comment by willthames** [comment]
This is definitely a backport contender. I'll cherry-pick

**Pull request merged**
