### PR TITLE
gitlab_user: add support to block/unblock user (#61754)

### PR DESCRIPTION
**Pull request by smeeus**
##### SUMMARY
Adds support to `gitlab_user` to block/unblock the account of a given user (#61754)
Fixes PR #61864 rebase question

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
gitlab_user

##### ADDITIONAL INFORMATION
It is currently not possible to specify `state=blocked` or `state=unblocked` to block/unblock the user's account in GitLab.
Previously, the only possible options were to create or delete the account.

### CODE REVIEW

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by mattclay** [comment]
@smeeus GitHub is having issues with this PR. Can you try pushing a new commit to see if that fixes it? If not, close the PR and open a new one.

**Comment by smeeus** [comment]
@mattclay I have pushed a new empty commit. I did notice some weird things happening also before. The new commit seems to fix the problem though.

**Comment by smeeus** [comment]
Closing and re-opening to trigger CI.

**Comment by smeeus** [comment]
Closing and re-opening to trigger CI.

**Comment by smeeus** [comment]
Closing due to migration of modules.

New PR https://github.com/ansible-collections/community.general/pull/188

**Pull request closed without merging**
