### PR TITLE
port ec2_key to boto3

### PR DESCRIPTION
**Pull request by prasadkatti**
##### SUMMARY
port ec2_key to boto3

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
`ec2_key`

##### ANSIBLE VERSION

```
ansible 2.5.0
```

### CODE REVIEW

**Comment by prasadkatti** [comment]
ready_for_review

**Review by willthames — CHANGES_REQUESTED** [review]
There are a lot of test cases being removed - given that we're upgrading a module here, I'd rather remove test cases, with valid reasons, after the existing tests pass.

**Comment by prasadkatti** [comment]
@willthames - A bunch of the tests that are removed are asserting failures when either region is not defined or credentials are missing. Those test cases have more to do with the `boto3_conn` function and are not related to `ec2_key`.

The other group of tests that I removed were the ones using `with_` lookups. Again these tests are testing `with_` rather than ec2_key. We already have a test case where we pass in the `key_material` directly.

I also removed one test which was testing deleting of a key pair with `key_material` also passed in. However, `key_material` is ignored when state=absent. So I removed that test case as well.

**Comment by prasadkatti** [comment]
@willthames - Let me know what you think about my comment above. Do you still want me to keep those test cases and undo my changes (test case deletions)?

**Review by willthames — APPROVED** [review]

**Comment by willthames** [comment]
All seems reasonable to me. As a fairly core module I've added @s-hertel and @ryansb to the review list for a second opinion.

**Comment by prasadkatti** [comment]
@s-hertel @ryansb Have you had a chance to look at this?

**Comment by ryansb** [comment]
Shertel has been at Re:Invent, I'm still testing this.

**Comment by prasadkatti** [comment]
@ryansb - Thanks for the update. :)

**Comment by prasadkatti** [comment]
@s-hertel @ryansb just a gentle reminder to review this PR. Thanks. :)

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
Thank you @prasadkatti

**Pull request merged**
