### PR TITLE
Refactor E-Series FlashCache module to use module_utils

### PR DESCRIPTION
**Pull request by lmprice**
Refactor the NetApp E-Series module to utilize the common module_utils
and doc_fragments.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
netapp_e_flashcache

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/lorenp/ansible/lib/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
This patch is intended to bring the NetApp E-Series modules more in line with the other NetApp modules and with the updated best practices by utilizing doc_fragments and module_utils for common code. This patch is not intended to change any existing functionality or output.

This patch is a simplification of my original PR (#20764); I was asked to split it into one PR per module.

### CODE REVIEW

**Comment by hulquest** [comment]
@mattclay, are we sure the ci failure is legitimate?

**Comment by mattclay** [comment]
@hulquest I added the `ci_verified` label, but didn't leave a comment explaining the failure, so I may have labeled the wrong PR. I've restarted CI and I'll check on the results when it finishes.

**Comment by mattclay** [comment]
CI is currently failing due to an unrelated issue, although that could be masking other issues. I've removed the `ci_verified` label and will re-visit this PR after the unrelated issue is resolved.

**Comment by hulquest** [comment]
Ok, I misunderstood the label.  Thought it meant 'the ci result was verified' instead of the 'the ci tests passed'

**Comment by mattclay** [comment]
Actually, you were right in your interpretation. `ci_verified` is used to mean the result of CI has been manually verified. Once the tests have been re-run (without unrelated issues causing failures), I'll update the PR again.

**Comment by mattclay** [comment]
CI is now passing.

**Comment by hulquest** [comment]
Thanks for the cleanup.  LGTM.
shipit

**Comment by hulquest** [comment]
Adding a second shipit to move things along.

**Comment by hulquest** [comment]
Adding a second shipit to move things along.

**Comment by calfonso** [comment]
@lmprice We would like you to mention that you're re-licensing as we require BSD license for module_utils. We'll need you to check with any other contributors and if there are any, have them comment in the PR that they approve of the license change.

**Comment by hulquest** [comment]
Fix merge conflicts and then shipit

**Pull request closed without merging**
