### PR TITLE
Bug fixes to the Infoblox NIOS modules

### LINKED ISSUE #56856: nios_srv_record with view parameter can't be updated due to "Field is not allowed for update: view" error
##### SUMMARY
The nios_srv_record can't update a SRV record because it passes the view paramater within the PUT request.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_srv_record

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
I've tested on the latest 'devel' and 'stable-2.8' and the problem is still there.

##### CONFIGURATION

```paste below
No output
```

##### OS / ENVIRONMENT

RedHat 7.5, Infoblox WAPI 2.3.1

##### STEPS TO REPRODUCE
Create SRV record with nios_srv_record and then update the comment using nios_srv_record.

```yaml
---
- hosts: all
  become: yes
  tasks:
    - name: Setup-Playbook
      setup: # Executes gather facts on all inventory

- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: create SRV record
    nios_srv_record:
      name: "bug.domain.com"
      port: "10000"
      priority: 1
      target: "target-bug.domain.com"
      weight: 10
      state: present
      comment: "ansible bug"
      provider:
        host: "{{ infoblox_server }}"
        username: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        wapi_version: "{{ infoblox_api_version }}"
      view: "external"
    connection: local
  - name: update SRV record
    nios_srv_record:
      name: "bug.domain.com"
      port: "10000"
      priority: 1
      target: "target-bug.domain.com"
      weight: 10
      state: present
      comment: "ansible bug comment update"
      provider:
        host: "{{ infoblox_server }}"
        username: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        wapi_version: "{{ infoblox_api_version }}"
      view: "external"
    connection: local
```

##### EXPECTED RESULTS
I expect the SRV record 'comment' value to be updated.

##### ACTUAL RESULTS
Received a 'Field is not allowed for update: view' error.

https://gist.github.com/simonlg/4a917bf85507b8e91fa3d83ba59246a9

### LINKED ISSUE #58378: Nios_ptr_record fails adding same PTR record to different views.
##### SUMMARY

The problem is the same as #51204 but for PTR Records and is not fixed in version 2.8.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```nios_ptr_record```

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
``` None ```

##### OS / ENVIRONMENT
 ``` CentOS Linux release 7.5.1804 (Core) ```

##### STEPS TO REPRODUCE
```
    - name  : "Create DNS PTR"
      nios_ptr_record:
        ptrdname : "{{ ptrdname }}"
        ipv4addr: "{{ ip }}"
        state: present
        view: "{{ item }}"
        ttl: "{{ttl|int}}"
        provider: "{{ {'host': Infoblox.host, 'username': Infoblox.username, 'password': Infoblox.password} }}"
      with_items:
         - "{{ views_infoblox }}"

#views = [view1, view2]

```

##### EXPECTED RESULTS
Creation of the PTR in both views

##### ACTUAL RESULTS
```
- view 1 : ok 
- view 2 : 
    "msg": "Field is not allowed for update: view",
    "operation": "update_object",
    "type": "AdmConProtoError"
```

### PR DESCRIPTION
**Pull request by krisvasudevan**
##### SUMMARY

Fixes #56856
Fixes #58378

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

nios_ptr_record
nios_srv_record

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by krisvasudevan** [comment]
@sgiri

**Comment by justjais** [comment]
@krisvasudevan u'll need to update integration tests as you have made `view` as required parameter, so update the respective integration tests for the shippable tests to pass, rest code changes LGTM.

**Comment by krisvasudevan** [comment]
@justjais I've updated both the unit tests and the integration tests.

**Comment by sgiri** [comment]
I am not sure how my userid (sgiri) got in this thread. Was this a mistake?

**Comment by justjais** [comment]
@sgiri plz ignore the tag, as u were tagged by mistake as tag was meant for @s-giri.

**Pull request merged**
