### PR TITLE
Adding Support For Vxlan In Onyx Switches

### PR DESCRIPTION
**Pull request by anasbadaha**
Signed-off-by: Anas Badaha <anasb@mellanox.com>

##### SUMMARY

Adding Support for Onyx Vxlan

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/onyx/onyx_vxlan.py
test/units/modules/network/onyx/fixtures/onyx_show_interfaces_nve.cfg
test/units/modules/network/onyx/fixtures/onyx_show_interfaces_nve_detail.cfg
test/units/modules/network/onyx/test_onyx_vxlan.py

##### ADDITIONAL INFORMATION

```
ansible 2.8.0a1.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.autodirect/mtrswgwork/anasb/ansible_dev8/lib/ansible
  executable location = /.autodirect/mtrswgwork/anasb/ansible_dev8/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

### CODE REVIEW

**Comment by justjais** [comment]
cc. @gundalow

**Comment by anasbadaha** [comment]
Hi @samerd,

Please review the following PR and let me know if you have any comments.

Thanks

**Review by samerd — CHANGES_REQUESTED** [review]
Thanks Anas,
The code looks great, however I have few notes:
1- DOCUMENTATION:
choices: ['True', 'False'] --> type: bool
default: True --> default: true
default: False --> default: false

2- EXAMPLES
remove "protocol nve" as it is not being added in this module

3- function _set_vxlan_config:
a. if there is no match for nve_id, no need to continue.
b. self._current_config['vni_vlan_mapping'] = dict() --> vni_vlan_mapping = self._current_config['vni_vlan_mapping'] = dict()
and use this variable after that instead of accessing the dict again

**Comment by anasbadaha** [comment]
Hi @samerd,

I have fixed all you comments, Please approve if it's OK for you.

Thanks

**Review by samerd — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
