### PR TITLE
Set default of 'yes' for update_cache, as is in the documentation

### PR DESCRIPTION
**Pull request by AndydeCleyre**

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not sure about this, it seems maybe the default should be no and the docs are wrong.

I don't think you would want to update the cache by default.

In any case, changing the default behavior seems undesirable given how apt typically splits this cache setting up.

**Comment by resmo** [comment]
update_cache=yes should be the default, we already discussed this. (otherwise it would also break backward compatibly to 1.2)

**Comment by resmo** [comment]
ahm... are you sure?!?

**Comment by jctanner** [comment]
@AndydeCleyre since it is the default in the documentation, i'm going to merge this. Thanks!

**Pull request merged**
