### PR TITLE
Various small fixes to boolean usage and defaults

### PR DESCRIPTION
**Pull request by dagwieers**

### CODE REVIEW

**Comment by mpdehaan** [comment]
You should use the module.boolean method to cast vs the "in BOOLEANS_FALSE" thing ... See other usage for an example.

**Comment by dagwieers** [comment]
Done.

**Comment by mpdehaan** [comment]
Looks like you did not test this one...

```
force = module.boolean(module.params.get('force')
```

Missing ")"

**Comment by dagwieers** [comment]
Fixed, with some more changes (i.e. using module.params.get)

**Comment by dagwieers** [comment]
My environment forces me to retype changes on an Internet-bound machine, especially if there are few changes this is faster than the alternative...

**Pull request merged**
