### PR TITLE
Scan group_vars/host_vars in sorted order

### LINKED ISSUE #31689: Ansible 2.4 group_vars not parsed lexicographically
##### ISSUE TYPE
 - ~Bug  Report~
- Feature Idea

##### COMPONENT NAME
group_vars

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /opt/ansible/ansible.cfg
  configured module search path = [u'/usr/lib/pymodules/python2.7/ansible/module_utils']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION
```
[root@local test]# ansible-config dump --only-changed
[root@local test]# 
```
##### OS / ENVIRONMENT
```
[root@local test]# uname -a
Linux local 4.13.4-1-ARCH #1 SMP PREEMPT Thu Sep 28 08:39:52 CEST 2017 x86_64 GNU/Linux
```

##### SUMMARY
group variable files of higher lexicographical order do not override lower ones

##### STEPS TO REPRODUCE
```
[root@local test]# for file in $(find -type f); do echo "#File: ${file}"; cat $file; echo; done
#File: ./playbooks/debug.yml
- hosts: localhost
  gather_facts: yes
  tasks:
  - debug: var=myvar

#File: ./playbooks/group_vars/all/02_vars
myvar: "02"

#File: ./playbooks/group_vars/all/00_vars
myvar: "00"

[root@local test]# ansible-playbook -i "127.0.0.1," -c local playbooks/debug.yml 
```

##### EXPECTED RESULTS
ok: [127.0.0.1] => {
    "myvar": "02"
}
##### ACTUAL RESULTS
```
PLAY [localhost] *************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [127.0.0.1]

TASK [debug] *****************************************************************************************************************************************
ok: [127.0.0.1] => {
    "myvar": "00"
}

PLAY RECAP *******************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   


```

### PR DESCRIPTION
**Pull request by NomAnor**
##### SUMMARY
Fixes #31689 

##### ISSUE TYPE
 - Feature Pull Request
 - Docs Pull Request

##### COMPONENT NAME
host_group_vars plugin

### CODE REVIEW

**Comment by samdoran** [comment]
cc @bcoca

**Comment by bcoca** [comment]
I'm ok with adding it, but it should be a toggle as others might be relying on the previous behaviour.

**Comment by logan2211** [comment]
Good fix, restores previous vars loading order from <2.4, tested and working for me. Thanks

**Comment by bcoca** [comment]
backported to 2.4.2

**Pull request merged**
