### PR TITLE
Add a group_by action plugin.

### PR DESCRIPTION
**Pull request by jhoekx**
Example usage:

```

---

- hosts: all
  gather_facts: false
  tasks:
  - local_action: is_provisioned host=${inventory_hostname}
  - local_action: pause seconds=1
  - local_action: group_by is_provisioned, color

- hosts: unprovisioned
  gather_facts: false
  tasks:
  - action: ping

- hosts: blue
  gather_facts: false
  tasks:
  - action: ping
```

With `is_provisioned`:

```
#!/usr/bin/env python

def main():
    module = AnsibleModule(
        argument_spec = dict(
            host=dict(required=True),
        )
    )

    if module.params['host'] in ['firefly']:
        ansible_facts={'is_provisioned':'unprovisioned', 'color':'blue'}
        module.exit_json(ansible_facts=ansible_facts)
    elif module.params['host'] in ['mole']:
        ansible_facts={'is_provisioned':'unprovisioned', 'color':'red'}
        module.exit_json(ansible_facts=ansible_facts)
    else:
        module.exit_json(ok="ok")

# this is magic, see lib/ansible/module_common.py
#<<INCLUDE_ANSIBLE_MODULE_COMMON>>
main()
```

Result:

```
PLAY [all] ********************* 

TASK: [is_provisioned host=${inventory_hostname}] ********************* 
ok: [firefly] => {"ansible_facts": {"color": "blue", "is_provisioned": "unprovisioned"}}
ok: [testsys] => {"ok": "ok"}
ok: [mole] => {"ansible_facts": {"color": "red", "is_provisioned": "unprovisioned"}}

TASK: [pause seconds=1] ********************* 
(^C-c = continue early, ^C-a = abort)
[testsys, firefly, mole]
Pausing for 1 seconds

TASK: [group_by is_provisioned, color] ********************* 
changed: [testsys] => {"changed": true, 
   "color": {"blue": ["firefly"], "red": ["mole"]},
   "is_provisioned": {"unprovisioned": ["firefly", "mole"]}
}

PLAY [unprovisioned] ********************* 

TASK: [ping] ********************* 
ok: [firefly] => {"ping": "pong"}
ok: [mole] => {"ping": "pong"}

PLAY [blue] ********************* 

TASK: [ping] ********************* 
ok: [firefly] => {"ping": "pong"}
```

This is branched from 0.8, on trunk not even 'pause' was working.

### CODE REVIEW

**Comment by mpdehaan** [comment]
group_by needs to be a "bypass host loop" plugin like pause, such that you can say "group_by" and don't have to execute it for each host.  

It should probably also take key=value arguments to be consistent, so like:

```
- action: ...

- group_by: vars=$item
  with_items:
       - a 
       - b 
       - c
```

**Comment by jhoekx** [comment]
It's already a 'bypass host loop' plugin, no? I did the same things as pause, but I could be that I'm missing something.

For the syntax, I was just using what you said in #1457 :-). I don't care too much. Will update it. I also need to handle variable values with spaces in them!

**Comment by mpdehaan** [comment]
Ok, great!

Ah, I didn't read your code yet, just your example.

In which case, local_action is not needed.   No problem.

Yeah, I think what you have instead of "vars=" is probably better.   I suspect some people are eventually going to want operators and stuff, but let's not worry about that for now.   Easy to get this stuck in overthinking it :)

Instead of vars=, yeah, I think you are right... maybe just split on commas and preserve spaces.   

In order to join the "with_items" it will have to be added to the logic that yum and apt have in runner/**init**.py -- which is just a one line tweak.

**Comment by mpdehaan** [comment]
Adding an example to examples/playbooks (group_by.yml) is probably a good thing to do as well.

Thanks!

**Comment by jhoekx** [comment]
Hmm, coding faster than the transatlantic delay.

So, what's your final decision? var or no var?

**Comment by jhoekx** [comment]
I'd say keep 'var'. We also want a prefix argument to prefix the group.

**Comment by mpdehaan** [comment]
var= would be nice in that it could allow for more flags later, I'd say keep it.

So ... what you are saying is... you need an ... Ansible?

**Comment by mpdehaan** [comment]
I'll probably test and merge this tomorrow... thanks!

**Comment by jhoekx** [comment]
An ansible would be helpful to take over the world as planned indeed.

I don't need one to know that you also want documentation :-)

New cool possibilities I thought of:

```
- hosts: all
  tasks:
  ### Create a group of all kvm hosts
  - action: group_by key=ansible_virtualization_type,ansible_virtualization_role

- hosts: kvm-host
  tasks:
  - action: ping
```

There's no support for complex variables right now. That's something that needs to be implemented someday.

**Comment by dhozac** [comment]
Is there a reason to be doing custom variable lookups instead of just letting the template system do it for you? I.e., why not have key="${ansible_virtualization_type}-${ansible_virtualization_role}" define a group named that? This also automatically gives you a way to prefix things, and will be entirely determined by the user, allowing all the same variables as the rest of the playbook.

**Comment by jhoekx** [comment]
Yes, there is a reason. It's a good question (documented in the code). Correct me if I'm wrong though, since this is the first time I write an action_plugin.

This code needs to modify the inventory. This means it has to run outside of a multiprocessing module. Normal action plugins run inside it. So you need `BYPASS_HOST_LOOP`. The code runs just once, for all hosts, so I can not rely on any normal templating.

**Comment by dhozac** [comment]
Yes, you have to run it yourself, but you can still use the same system. And you are in fact running it already. So you could have group_by: name="auto-$ansible_pkg_mgr", which I think would be a far more explainable syntax than using another type of variable lookup and concatenating the results...

**Comment by dhozac** [comment]
It would simplify it down to

``` python
    def run(self, conn, tmp, module_name, module_args, inject):
        args = parse_kv(module_args)
        if not 'key' in args:
            raise ae("'key' is a required argument.")

        inventory = self.runner.inventory

        result = {'changed': False}

        ### find all returned groups
        groups = {}
        for _,host in self.runner.host_set:
            data = inject['hostvars'][host]
            group_name = template(self.runner.basedir, args['key'], data)
            if group_name not in groups:
                groups[group_name] = []
            groups[group_name].append(host)
```

(note that this is using hostvars, which also includes inventory as well as facts.)

**Comment by jhoekx** [comment]
Ok for using hostvars.

I see that your templating approach is better, but it does not work for me right now.

Current 0.9-git is completely broken as I said in my initial pull request. I can't even run the pause action plugin. I get output like:

```
TASK: [pause seconds=1] ********************* 
fatal: [i] => host not found: i


```

It's on my todo list to find out why.

That's why I'm working based on 0.8. 0.8 somehow already templates the line for one of the hosts, so instead of getting '$ansible_machine' in args['key'] I get 'x86_64'.

I'll work on getting 0.9-git in a working state for me.

**Comment by jhoekx** [comment]
The reason it already templates stuff is in the comments in runner/**init**.py:

```
            # We aren't iterating over all the hosts in this
            # group. So, just pick the first host in our group to
            # construct the conn object with.
```

**Comment by dhozac** [comment]
0.9 just needs to change

```
result_data = self._executor(hosts[0][1]).result
```

in Runner.run to

```
result_data = self._executor(hosts[0]).result
```

The reason it is templated was also fixed by my change, you are calling template with inject on the very first line of run.

**Comment by jhoekx** [comment]
Ok, the letter thing I also found, sent a PR.

I'll completely follow your code now and send a new PR against 0.9.

**Pull request closed without merging**
