### PR TITLE
Update AWS SSM lookup to support getting parameters by path (second attempt)

### PR DESCRIPTION
**Pull request by mtb-xt**
##### SUMMARY
Update AWS SSM Parameter storage lookup plugin to support getting parameters by path

AWS SSM Parameter store lookup was added in PR https://github.com/ansible/ansible/pull/23460, but there were requests to add support to look up parameters by path. 

This is my attempt on that. This is a second PR from me, because I've screwed up the history in my original PR https://github.com/ansible/ansible/pull/31505, sorry :(

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
plugins/lookup/ssm.py

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]
```

##### ADDITIONAL INFORMATION
Currently, the lookup plugin only gets a single parameter as in example below:
```
- debug: msg="{{ lookup('aws_ssm', 'Hello', 'region=ap-southeast-2',  ) }}"
```

This PR adds these features:
You lookup the whole parameters hierarchy:
```
 - debug: msg="{{ lookup('aws_ssm', '/Test', 'region=ap-southeast-2', 'bypath', 'recursive=true' ) }}
```
Would return:
```
ok: [localhost] => {
    "msg": [
        {
            "Name": "/Test/secure-test", 
            "Type": "SecureString", 
            "Value": "secure-test"
        }, 
        {
            "Name": "/Test/subpath/test", 
            "Type": "String", 
            "Value": "testsubpath"
        }, 
        {
            "Name": "/Test/test-string", 
            "Type": "String", 
            "Value": "test-string"
        }
    ]
}
```

You can loop through them:
```
         - name: Getting parameters in a loop
           debug: msg='key contains an item named {{item.Name }} with value {{item.Value}}'
           with_aws_ssm:
             - '/Test'
             - 'region=ap-southeast-2'
             - 'bypath'
             - 'recursive=true'
```
would return:

```
TASK [Getting parameters in a loop] *********************************************************************
Tuesday 10 October 2017  16:22:44 +1300 (0:00:00.370)       0:00:01.035 ******* 
ok: [localhost] => (item={u'Type': u'SecureString', u'Name': u'/Test/secure-test', u'Value': u'secure-test'}) => {
    "item": {
        "Name": "/Test/secure-test", 
        "Type": "SecureString", 
        "Value": "secure-test"
    }, 
    "msg": "key contains an item named /Test/secure-test with value secure-test"
}
ok: [localhost] => (item={u'Type': u'String', u'Name': u'/Test/subpath/test', u'Value': u'testsubpath'}) => {
    "item": {
        "Name": "/Test/subpath/test", 
        "Type": "String", 
        "Value": "testsubpath"
    }, 
    "msg": "key contains an item named /Test/subpath/test with value testsubpath"
}
ok: [localhost] => (item={u'Type': u'String', u'Name': u'/Test/test-string', u'Value': u'test-string'}) => {
    "item": {
        "Name": "/Test/test-string", 
        "Type": "String", 
        "Value": "test-string"
    }, 
    "msg": "key contains an item named /Test/test-string with value test-string"
}
```

You can also ask the plugin to return short versions of parameter names (The part after the last slash, not the full path):
```
         - name: Getting parameters in a loop with names shorteting
           debug: msg='key contains an item named {{item.Name }} with value {{item.Value}}'
           with_aws_ssm:
             - '/Test'
             - 'region=ap-southeast-2'
             - 'bypath'
             - 'shortnames'
             - 'recursive=true'
```
Would return:

```
TASK [Getting parameters in a loop with names shorteting] ***********************************************
Tuesday 10 October 2017  16:22:44 +1300 (0:00:00.371)       0:00:01.406 ******* 
ok: [localhost] => (item={u'Type': u'SecureString', u'Name': u'secure-test', u'Value': u'secure-test'}) => {
    "item": {
        "Name": "secure-test", 
        "Type": "SecureString", 
        "Value": "secure-test"
    }, 
    "msg": "key contains an item named secure-test with value secure-test"
}
ok: [localhost] => (item={u'Type': u'String', u'Name': u'test', u'Value': u'testsubpath'}) => {
    "item": {
        "Name": "test", 
        "Type": "String", 
        "Value": "testsubpath"
    }, 
    "msg": "key contains an item named test with value testsubpath"
}
ok: [localhost] => (item={u'Type': u'String', u'Name': u'test-string', u'Value': u'test-string'}) => {
    "item": {
        "Name": "test-string", 
        "Type": "String", 
        "Value": "test-string"
    }, 
    "msg": "key contains an item named test-string with value test-string"
}
```

### CODE REVIEW

**Comment by mtb-xt** [comment]
@willthames this PR is rebased upon the rename of the lookup and the module.

**Comment by mtb-xt** [comment]
@viper233 
to answer your original comment in https://github.com/ansible/ansible/pull/31505:
>I have a problem with lookups within the AWS environment as it seems impossible to pass STS tokens for cross account access. Seeing aws_ssm_parameter_store exists, wouldn't it be better to have aws_ssm_parameter_store_facts?

The original author implemented it this way, and the PR was already approved and merged, but it was lacking the features to get the parameters by path (and those features are already requested by other ansible users). Could we merge my changes as they are (so the people can start using them now), and discuss your objection in a separate issue?

**Comment by willthames** [comment]
@viper233 

I'd be happy to see an aws_ssm_parameter_store_facts module.

With the lookup, you can just pass the security token using `environment` parameters, I believe.

```
- debug:
    msg: "{{ lookup('aws_ssm', 'key', ...) }}"
  environment:
    AWS_ACCESS_KEY_ID: ...
    AWS_SECRET_ACCESS_KEY: ...
    AWS_SECURITY_TOKEN: ...
```
http://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variables

Having said that, I requested new `aws_profile` argument in #23460, there's no reason we couldn't add further parameters if needed (all of this stuff gets done by default for modules, exactly so this stuff doesn't get missed, but we have very few lookup modules, so far)

**Comment by willthames** [comment]
@mtb-xt thanks for the improvement!

**Pull request merged**
