### PR TITLE
Part fix for https://github.com/ansible/ansible-modules-core/issues/1404

### PR DESCRIPTION
**Pull request by jhawkesworth**
Checksum function now allways returns a string.
Also had to amend some integration tests as the checksum is no
longer being returned in an array.

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Fixed the merge conflict, please test

**Comment by cchurch** [comment]
:+1: on the powershell and test_win_copy changes.  Integration tests pass for me when testing against https://github.com/ansible/ansible-modules-core/pull/1438.

Any way you can remove the test_uri and subproject changes?

**Comment by jhawkesworth** [comment]
ok, no idea how the test_uri change got in there.  Will see if I can fix without having to create a fresh branch.

**Comment by jhawkesworth** [comment]
I am closing this in favour of https://github.com/ansible/ansible/pull/11115 which does not include the unintended test_uri and subproject changes.

**Pull request closed without merging**
