### PR TITLE
aws_ec2 inventory plugin: support using tag values as hostnames

### PR DESCRIPTION
**Pull request by flowerysong**
##### SUMMARY

The recently added aws_ec2 plugin supports using hard-coded tag/value pairs separated by '_' as hostnames (e.g. `hostnames: [ 'tag:Stars=Right' ]` will use 'Stars_Right' as the hostname for an instance with that tag set to that value). That's not particularly useful in our environment.

This change retains the existing functionality while adding support for directly using the value of a tag as the hostname.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

aws_ec2 inventory

##### ANSIBLE VERSION

```
ansible 2.5.0 (detached HEAD 6037e73c16) last updated 2018/02/07 21:40:33 (GMT -400)
  config file = /home/ec2-user/ansible-aws-dev/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/ansible-aws-dev/git/ansible.git/lib/ansible
  executable location = /home/ec2-user/ansible-aws-dev/git/ansible.git/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### ADDITIONAL INFORMATION

Before (with `hostnames: [ 'tag:Name=mogo', dns-name ]`)
```
  hosts (17):
    ec2-35-161-254-188.us-west-2.compute.amazonaws.com
    ec2-54-202-90-90.us-west-2.compute.amazonaws.com
    ec2-54-149-232-15.us-west-2.compute.amazonaws.com
    ec2-52-37-117-118.us-west-2.compute.amazonaws.com
    ec2-34-210-102-204.us-west-2.compute.amazonaws.com
    ec2-35-162-110-70.us-west-2.compute.amazonaws.com
    ec2-54-201-67-224.us-west-2.compute.amazonaws.com
    ec2-34-217-81-127.us-west-2.compute.amazonaws.com
    ec2-54-244-40-177.us-west-2.compute.amazonaws.com
    ec2-52-37-161-181.us-west-2.compute.amazonaws.com
    ec2-34-209-247-128.us-west-2.compute.amazonaws.com
    ec2-54-244-191-16.us-west-2.compute.amazonaws.com
    Name_mogo
    ec2-35-162-59-88.us-west-2.compute.amazonaws.com
    ec2-34-217-95-188.us-west-2.compute.amazonaws.com
    ec2-54-202-54-3.us-west-2.compute.amazonaws.com
    ec2-54-200-244-14.us-west-2.compute.amazonaws.com
```

After (with `hostnames: [ 'tag:Name=mogo,CustomDNSName', dns-name ]`:
```
  hosts (17):
    rapid-golem.egress.a.mail.umich.edu
    coy-maenad.mx.a.mail.umich.edu
    russet-maenad.mx.a.mail.umich.edu
    faithful-vodianoi.egress.a.mail.umich.edu
    stale-apsara.mx.a.mail.umich.edu
    confused-naga.mx.a.mail.umich.edu
    rose-kraken.mx.a.mail.umich.edu
    agate-gisela.mx-test.a.mail.umich.edu
    lax-alicorn.mx.a.mail.umich.edu
    ec2-52-37-161-181.us-west-2.compute.amazonaws.com
    agate-euroswydd.syslog.a.mail.umich.edu
    hushed-maenad.mx.a.mail.umich.edu
    Name_mogo
    honest-dunnie.egress.a.mail.umich.edu
    jealous-gaki.mx.a.mail.umich.edu
    classic-dwyfan.rbl.a.mail.umich.edu
    insane-arawn.rbl.a.mail.umich.edu
```

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @s-hertel @ryansb

**Comment by willthames** [comment]
rebuild_merge

**Comment by willthames** [comment]
Thanks for this @flowerysong, it's a great improvement.

**Comment by ebenezar-mccoy** [comment]
Hi, is there a chance that this fix will be merged to 2.5 ?

**Comment by s-hertel** [comment]
@ebenezar-mccoy Backported for 2.5.3 in 84f9303.

**Pull request merged**
