### PR TITLE
Fixes#18663-Bad Handling of existing config in OS6 module

### PR DESCRIPTION
**Pull request by abirami-n**
**ISSUE TYPE**

- Bugfix Pull Request

**COMPONENT NAME**

ansible.module_utils.dellos6

**ANSIBLE VERSION**

ansible 2.2.3.0 (stable-2.2 7cc351a237)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

**SUMMARY**

Back-porting parsing of existing configs in OS6 module to ansible stable_2.2

Fixes#18663

### CODE REVIEW

**Comment by gundalow** [comment]
@dhivyap @skg-net please can you review.

**Comment by gundalow** [comment]
@dhivyap @skg-net please can you review.

Bug in 2.2, so does this need cherry picking into `stable-2.3` and `stable-2.2`

**Review by skg-net — APPROVED** [review]

**Comment by skg-net** [comment]
@gundalow I believe these changes already made into 2.3. If not, we will raise a separate PR.

**Comment by gundalow** [comment]
Merged into `devel` please check if this is needed in other branches.

**Pull request merged**
