### PR TITLE
Backport/2.7/49758

### PR DESCRIPTION
**Pull request by zikalino**
##### SUMMARY
VMSS image reference fix

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_virtualmachine_scaleset

### CODE REVIEW

**Review by yungezz — APPROVED** [review]

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/99318/75/tests

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/99632/75/tests

**Comment by Fred-sun** [comment]
@zikalino Could you help confirm that how about this PR going ahead? need update or further review? Thanks!

**Comment by abadger** [comment]
@zikalino Note that we won't be able to merge this backport unless it is passing tests in shippable.

**Comment by zikalino** [comment]
@abadger apparently I had to add one more fix to this backport. could you merge it now?

**Review by nitzmahone — APPROVED** [review]

**Comment by abadger** [comment]
Thanks all!  Merged for the 2.7.6 release.

**Pull request merged**
