### PR TITLE
New module:  Add Pritunl VPN organisation module (net_tools/pritunl/)

### PR DESCRIPTION
**Pull request by Lowess**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
pritunl_user.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 44fac2eb5a) last updated 2017/05/04 00:58:43 (GMT -700)
```

##### SUMMARY

(Pritunl)[https://pritunl.com/] is an Enterprise Distributed OpenVPN Server. We have been using this technology for about a year and we felt really handy to automate our VPN user management using Ansible.

As Pritunl offers a (REST API)[https://pritunl.com/api], we developed two modules to manage VPN users.

Both modules have been sitting on my laptop for about a year. They have been well tested and they work as expected (respect of idempotency, based on urllib, etc...)

I placed those modules under **net_tools/pritunl** (that's the only point I am not sure about). Feel free to tell me if something needs to updated.

Cheers,
Florian

### CODE REVIEW

**Comment by Lowess** [comment]
Finally, sorry for the mess :)

**Comment by Lowess** [comment]
The PR for pritunl user module has moved to this PR #26584

**Comment by Lowess** [comment]
Any updates on this PR? This module is really handy for people who work with Pritunl. That would be great to have someone checking if we could roll this out in the upcoming releases!

Thanks!

**Comment by Akasurde** [comment]
Please submit new module requests to https://github.com/ansible-collections/community.general repo.
Thanks for your contribution.

**Pull request closed without merging**
