### PR TITLE
Vpc security group

### PR DESCRIPTION
**Pull request by lightglitch**
This allows to use group and group_id with vpc, it was based on #2366 from @samukasmk but with some fixes that we found on our case.

### CODE REVIEW

**Comment by mpdehaan** [comment]
@lwade can you help review this one?

@lightglitch can you please explain the intent/workings of the patch a bit more?

**Comment by lightglitch** [comment]
When you want to launch an instance in a VPC and you want to set the security group you get the error:

```
InvalidParameterCombination: The parameter groupName cannot be used with the parameter subnet
```

that's because when you call _ec2.run_instances_ you can't use _security_groups_ for VPC but use _security_group_ids_.

**Comment by lwade** [comment]
Thanks for the PR @lightglitch.  This one is worth a test, so I think we hold off merging right now and do that next week.  I'll take it upon myself to test next week.  It looks fine though :)

**Comment by dlashua** [comment]
I tested this file and VPC works perfectly. Thanks, @lightglitch!

**Comment by mpdehaan** [comment]
Thoughts @lwade ?

**Comment by lwade** [comment]
Didn't get a chance to test personally but thanks to @spiralpasta for stepping in. Looks fine for merge.

**Comment by mpdehaan** [comment]
looks like this one needs to be rebased in order to merge it, can you do that and retest, @lightglitch ?

**Comment by lightglitch** [comment]
@mpdehaan rebase done

**Comment by mpdehaan** [comment]
@lightglitch Very sorry about this, EC2 is a moving target.

Can you rebase once more?  Thanks!

**Comment by mpdehaan** [comment]
@lightglitch rebase still needed, thanks

**Comment by lightglitch** [comment]
Sorry, I'm busy today. I will do it tomorrow.

**Comment by lightglitch** [comment]
@mpdehaan done, please confirm that is ok with some testing

**Comment by mpdehaan** [comment]
Looks like you've got a merge commit in the history again.

Be sure to always use "git rebase" and start a new branch for each new feature.

Looks like this also has a tab in there due to looking at the last patch.

**Comment by lightglitch** [comment]
@mpdehaan I hope it's ok now

**Comment by mpdehaan** [comment]
yeah, that it is.  Today is merge day so I'll dig in.

also, thanks!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request closed without merging**
