### PR TITLE
New Pure Storage FlashArray module to configure array DNS settings

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
New module to manage DNS settings on a Pure Storage FlashArray

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
modules/storage/purestorage/purefa_dns.py

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

### CODE REVIEW

**Review by sile16 — COMMENTED** [review]
Need to specify in the documentation that both nameservers and domain need to be specified together.  Or write to handle providing individual updates.  Also, the compare of the DNS list, I would not recommend sorting as DNS servers are order aware.  Meaning most DNS implementations use the first DNS server as it's primary, so the order may be important.  It's a minor detail though.

**Comment by sdodsley** [comment]
The code specifies that both are needed together. If you try and do it separately the module will fail. This seems to be the norm for Ansible modules.
Sorting is done to ensure that we don't change the nameservers if they are already specified as the same values in a different order. TBH this is a minor thing in the DNS scheme of things.

**Comment by sile16** [comment]
shipit

**Review by sile16 — APPROVED** [review]

**Comment by gundalow** [comment]
@sile16 @sdodsley `required_if = [('state', 'present', ['domain', 'nameservers'])]` is the correct way of doing this, thanks.

**Pull request merged**
