### PR TITLE
ovirt_host_networks: Fix idempotency

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

Backport of: https://github.com/ansible/ansible/pull/37075
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1539828

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ovirt_host_networks

##### ANSIBLE VERSION

```
2.4.3
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by machacekondra** [comment]
shipit

**Review by mwperina — APPROVED** [review]
shipit

**Comment by mwperina** [comment]
@machacekondra Ondro, could you please rebase?

**Comment by machacekondra** [comment]
This was already backported as part of: https://github.com/ansible/ansible/pull/38341/ Closing..

**Pull request closed without merging**
