### PR TITLE
aci_switch_policy_vpc_protection_group: Fix idempotency

### LINKED ISSUE #43412: aci_switch_policy_vpc_protection_group reports "changed" everytime it runs
##### SUMMARY
aci_switch_policy_vpc_protection_group reports "changed" status back everytime it runs. It makes no difference if the protection_group already exists on APIC or not. The ansible module status shows changed permanently after every run.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aci_switch_policy_vpc_protection_group

##### ANSIBLE VERSION
Ansible 2.6.1
```
$ ansible --version
ansible 2.6.1
```
##### STEPS TO REPRODUCE
```yaml
- name: Set login credentials
  set_fact:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

- name: Create virtual port channels
  aci_switch_policy_vpc_protection_group:
    <<: *aci_login
    protection_group: VPC_LEAF-ACI-101-102
    protection_group_id: 102
    switch_1_id: 101
    switch_2_id: 102
    state: present
```
##### EXPECTED RESULTS
The expected result would be a "changed" status at first run (if protection group was not already there). After creating the status should be "ok" in following ansible-playbook runs.

##### ACTUAL RESULTS
Status of the module shows changed every time.

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This fixes #43412

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
aci_switch_policy_vpc_protection_group

##### ANSIBLE VERSION
v2.8 and earlier

### CODE REVIEW

**Review by achinthagunasekara — APPROVED** [review]

**Comment by dagwieers** [comment]
@jmcgill298 I would appreciate if you could review this change.

**Comment by dagwieers** [comment]
@achinthagunasekara You approved 5 of my PRs in under a minute today, and you have been doing similar activity for at least a few months. Can you please stop approving PRs you did not review yourself ?

**Comment by smnmtzgr** [comment]
I have tested the changes and it seems to work correctly now. I opened the here referenced issue [#43412](https://github.com/ansible/ansible/issues/43412)

**Comment by dagwieers** [comment]
@smnmtzgr Thanks for testing !

**Pull request merged**
