### PR TITLE
Aws lambda tests - repeat merge

### PR DESCRIPTION
**Pull request by mikedlr**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

lambda module

##### ANSIBLE VERSION

```
ansible 2.3.0 (aws_lambda_tests 635ba15d41) last updated 2017/02/22 11:13:58 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

**Do not merge before CI tests complete.  Earlier versions have shown failures in shippable even when local tests have passed for me**

This provides test cases for the lambda module for updating AWS lambda code and configuration.  

One update test case will fail if applied to ansible before

https://github.com/ansible/ansible/commit/22701806c34bb7787e5337b1814b367af7eab211

No change to ansible functionality or operation.

### CODE REVIEW

**Comment by mikedlr** [comment]
@ryansb that passes locally, when run with the whole sequence of tests locally and when run on shippable.  Also I've carefully simplified towards more use of simple native python statements (e.g. try/except/assert rather than assertRaises) which should be more globally portable. 

I'm reasonably confident that you can merge that subject to review and comments.

**Comment by mattclay** [comment]
I ran the unit tests locally (all of them) and didn't see any errors, so these changes are likely to pass on Shippable as well, when run with all the unit tests.

**Comment by mikedlr** [comment]
@mattclay / @ryansb in the current version I cleaned up and simplified the code, avoiding the use of mocking of fail_json() and instead just patching in a local function.  There's an earlier version, b0fb733824f308b4d73b94fffcea1e4a696c7e18, which passes for me when I run 

`pytest test/units/modules/cloud/amazon/test_lambda.py`

and fails when I run 

`make tests`

That earlier version used mocks and **@patch** instead of a simple function and **patch.object**.   I think the problems with the test suite are somewhere there.

**Review by ryansb — APPROVED** [review]

**Comment by mattclay** [comment]
@mikedlr I ended up having to disable two of the tests. When running each test in isolation, they fail. Can you take a look at fixing the two affected tests?

The change to disable the tests is here: https://github.com/ansible/ansible/pull/21932

**Pull request merged**
