### PR TITLE
Revert original ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
As described here https://github.com/ansible/ansible/pull/51657#issuecomment-463658709 and here https://github.com/ansible/ansible/pull/44455#discussion_r213791697

Removing this file causes various use-cases (like opening an issue on a mobile device) to fail. You get a text editor with a link in it you cannot click.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
ISSUE_TEMPLATE.md

### CODE REVIEW

**Comment by webknjaz** [comment]
I'm curious how the person filing an issue from a mobile device is supposed to copy-paste output from terminal... I'd rather go for a big ASCII art "GO BACK TO YOUR COMPUTER AND FILE ISSUE FROM THERE USING APPROPRIAT TEMPLATE" :rofl:

**Review by gundalow — CHANGES_REQUESTED** [review]
Please don't merge this without explicit approval from myself and Tanner.

Also at the moment I'm not sure if this is solving a real problem.

**Comment by webknjaz** [comment]
> Also at the moment I'm not sure if this is solving a real problem.

Exactly. But Dag's effort is good. I'm just not sure how to best solve this. Can we complain about it to GitHub folks?

**Comment by dagwieers** [comment]
I don't understand this. If this is everyone's position, then:
1. where was everybody when I proposed to remove it 6 months ago when we were redesigning this and I wanted to remove this and was told not to? https://github.com/ansible/ansible/pull/44455#discussion_r213791697
2. why did we spend the time and effort to clean up the generic issue template together with the others? Everyone was involved in that effort and reviewed it. 
https://github.com/ansible/ansible/pull/44455/files#diff-1a1c3dd142f76a5fad803a0c52839881

**Comment by webknjaz** [comment]
@dagwieers, things change. People tend to change their minds over time.

**Comment by gundalow** [comment]
FYI I've raised this with GitHub,
I expect the mobile view to link to `new/choose` soon

**Comment by dagwieers** [comment]
> @dagwieers, things change. People tend to change their minds over time.

Remind me to bring up my rejected proposals every 6 months for reconsideration 🤪

**Comment by webknjaz** [comment]
Ref: https://github.com/ansible/ansible/pull/51657/files#r330784048

**Pull request closed without merging**
