### PR TITLE
new module: Manage end point groups [network/aci/aci_epg]

### PR DESCRIPTION
**Pull request by schunduri**
##### SUMMARY
New module - Cisco ACI EPG

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
aci_epg

##### ANSIBLE VERSION

```
v2.4

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by schunduri** [comment]
@dagwieers can you please review the changes and approve it.

**Comment by dagwieers** [comment]
@schunduri I noticed that the short_description was incorrect, so this appears to not be the same module as we reviewed at: https://github.com/datacenter/aci-ansible/blob/master/library/aci_epg.py 

Could you please add the one from the aci-ansible project instead ?

**Review by dagwieers — CHANGES_REQUESTED** [review]
So this is somehow not the same file that was approved on aci-ansible. So I'd like that to be merged instead.

@schunduri If you have problems doing this using Git, let me know and I'll fix it.

**Comment by schunduri** [comment]
@dagwieers I see what you mean now. Took care of it :)

**Review by dagwieers — APPROVED** [review]

**Pull request merged**
