### PR TITLE
Arch linux PKGBUILD

### PR DESCRIPTION
**Pull request by leucos**
Adds PKGBUILD file required to build Arch Linux packages

### CODE REVIEW

**Comment by leucos** [comment]
Note that tests doesn't pass. Since they didn't before on my machine, and since no python has been written, the PR shouldn't harm any kitten around.

**Comment by leucos** [comment]
# Installing on Arch with AUR

ansible is available on [AUR](https://aur.archlinux.org/packages.php?ID=58621)

## Installing with yaourt

```
yaourt -S ansible-git
```

## Installing with pacman

```
curl https://aur.archlinux.org/packages/an/ansible-git/PKGBUILD -sfO && \
makepkg -sic
```

**Comment by mpdehaan** [comment]
make tests not passing is probably because your machine doesn't have your own host in authorized_keys, I'll note that in a README in the test dir.

They should normally pass, but obviously this isn't a code change so no problem.   Thank you, will look into merging tonight.

**Comment by jhoekx** [comment]
You need to change the symlink /usr/bin/python to point to /usr/bin/python2 instead of /usr/bin/python3 for tests to pass on Arch.

**Comment by leucos** [comment]
Thanks jhoekx, I've already done that. Most of the tests work but some don't. I will investigate further later on and open a specific issue on this if it persists.

**Comment by jhoekx** [comment]
@leucos, are you on master or integration? 6f09b41eb5851cab2c0b8d8e91998977405e98b4 fixes all tests for me. I'm also on Arch.

**Comment by leucos** [comment]
@jhoekx tests on integration branch runs fine, but 4 of them fail on master branch : https://gist.github.com/2422412 (note : no facter here, might be one of the causes)

**Comment by jhoekx** [comment]
@leucos Yeah, the fixes didn't make it into master yet, so that's expected. When the next release is made (on monday), they will be available.

**Comment by leucos** [comment]
I fixed PKGBUILD so I'm closing this one and sending an updated PR

**Pull request merged**
