### PR TITLE
remove limitation on sphinx version

### PR DESCRIPTION
**Pull request by samccann**
##### SUMMARY

No need to keep sphinx pinned to 2.1.2.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs/docsite/requirements.txt
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by webknjaz** [comment]
@samccann to also support Sphinx 3.5+ please change `'css_files': (...)` to `'css_files': [...]` (tuple to list syntax) in all the `conf.py` files.

**Comment by webknjaz** [comment]
@samcarpentier per https://www.sphinx-doc.org/en/master/usage/configuration.html, there's a number of config option renames. Just `Ctrl+F` -> `4.0` to locate them. The suggested solution is to use both names for some time.
For example, `master_doc` got renamed to `root_doc` so it's possible to make it cross compatible by having `root_doc = master_doc = 'index'`: https://github.com/ansible-community/sphinx_ansible_theme/commit/b5e180321988dcd57ad479e01e1c5e8da31d7681.

**Comment by samccann** [comment]
Thanks @webknjaz .
I'm running Sphinx 4 beta and getting the following error (in both 2.9 and devel so I don't think it relates to antsibull):
Sphinx parallel build error:
TypeError: 'AnsibleOutputLexer' object is not callable
make[2]: *** [Makefile.sphinx:24: html] Error 2
make[2]: Leaving directory '/home/samccann/ansible/docs/docsite'
make[1]: *** [Makefile:44: htmldocs] Error 2
make[1]: Leaving directory '/home/samccann/ansible/docs/docsite'
make: *** [Makefile:386: webdocs] Error 2

adding @felixfontein as well since I see his name on the pygments_lexer.py file that includes AnsibleOutputLexer...

**Comment by felixfontein** [comment]
@samccann that's interesting. The antsibull sphinx extension uses the exact same code as the extension included in ansible/ansible, and I was able to use the antsibull sphinx extension without problems with Sphinx 4.0.0b2. Is that the same beta you are using?

**Comment by webknjaz** [comment]
> I'm running Sphinx 4 beta and getting the following error (in both 2.9 and devel so I don't think it relates to antsibull):
> Sphinx parallel build error:
> TypeError: 'AnsibleOutputLexer' object is not callable

_I think_ I actually saw some deprecation warning related to that extension when running sphinx 3.0 so maybe the deprecated thing finally got removed. I haven't actually checked as I was focused on the theme-related stuff and I'm not yet at a point when I'd want to try in with Sphinx 4.

P.S. This is why I normally run sphinx with `-n -W --keep-going` to address the deprecation warnings ahead of time, not when they actually start breaking things.

**Comment by webknjaz** [comment]
This is from the theme repo demo (the ext source is the same):
```console
~/src/github/ansible-community/sphinx_ansible_theme/sphinx_ansible_theme/ext/pygments_lexer.py:228: RemovedInSphinx40Warning: app.add_lexer() API changed; Please give lexer class instead of instance
  app.add_lexer(lexer.name, lexer)
~/src/github/ansible-community/sphinx_ansible_theme/sphinx_ansible_theme/ext/pygments_lexer.py:230: RemovedInSphinx40Warning: app.add_lexer() API changed; Please give lexer class instead of instance
  app.add_lexer(alias, lexer)
```


I'm 99% sure this is what you've hit. It should be easy to address tho.

**Comment by webknjaz** [comment]
FWIW my experience matches what Felix says — it doesn't crash in the theme repo with sphinx v4.0.0b1 and v4.0.0b2. The only thing that comes to my mind is that maybe the ext code is not _exactly_ the same in the derived repos as in ansible/ansible...

**Comment by webknjaz** [comment]
@samccann have you considered pinning `sphinx < 4` as the first step to upgrade to v3 and then dropping the top boundary in a separate step?

**Comment by webknjaz** [comment]
Looks like it. But maybe there's something about how the env is set up in ansible/ansible. Dunno.

**Comment by acozine** [comment]
Superseded by #74956

**Pull request closed without merging**
