### PR TITLE
Adding slxos_l3_interface module

### PR DESCRIPTION
**Pull request by bigmstone**
##### SUMMARY
This PR adds the `slxos_l3_interface` module.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`slxos_l3_interface`

##### ANSIBLE VERSION
```
⟩ ansible --version
ansible 2.6.0 (slxos-l3-interface b4b1b4418d) last updated 2018/04/25 13:17:58 (GMT -500)
  config file = None
  configured module search path = [u'/Users/mstone/dev/stackstorm/ansible/library']
  ansible python module location = /Users/mstone/dev/stackstorm/ansible/lib/ansible
  executable location = /Users/mstone/dev/stackstorm/ansible/bin/ansible
  python version = 2.7.14 (default, Mar 29 2018, 15:58:25) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### ADDITIONAL INFORMATION
```
⟩ ansible-playbook --ask-pass -i hosts.yml l3int.yml
SSH password:
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/mstone/dev/stackstorm/ansible-slxos/l3int.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Configure v4 address on eth0/6
      ^ here
```
```
⟩ ansible-playbook --ask-pass -i hosts.yml l3int.yml
SSH password:

PLAY [dc2leaf2] ******************************************************************************************************************************************************************************************************

TASK [Configure v4 address on eth0/6] ********************************************************************************************************************************************************************************
ok: [dc2leaf2]

PLAY RECAP ***********************************************************************************************************************************************************************************************************
dc2leaf2                   : ok=1    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by bigmstone** [comment]
@gundalow This PR is ready to merge.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@bigmstone Can you rebase please, thanks in advance

**Review by ganeshrn — APPROVED** [review]

**Comment by bigmstone** [comment]
@gundalow conflicts resolved, but I wouldn't be shocked if there's more once #39259 is merged.

**Comment by gundalow** [comment]
Hi, 
See if http://docs.ansible.com/ansible/devel/dev_guide/index.html helps with the rebase, thanks in advance.

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Thanks, merged into `devel` for release in Ansible 2.6

**Pull request merged**
