### PR TITLE
Network facts

### PR DESCRIPTION
**Pull request by akhayyat**
Backwards compatible, and fixes a broken scenario: when eth0 has two IPs, the current implementation will create eth0 and eth0:0 interfaces. When it then finds a real eth0:0, it will name it eth0:1.
- Adds new interfaces tree under key `interfaces` (see example below).
  This also does what the old `interfaces` key did.
  Main features of the new tree:
  - An alias for each IPv4 address
  - Adds `type` for each interface, e.g. ether, loopback
  - Distinguishes alias interfaces from additional IPs
  - Reliable (picked from routing table, not just the first non-local address as before) default address, interface, alias, and gateway for each of IPv4 and IPv6
- Keeps old per-interface tree for backwards compatibility

```
"interfaces": {
    "default_ipv4": {
        "interface": "eth0",
        "address": "192.168.1.3",
        "netmask": "255.255.255.0",
        "gateway": "192.168.1.254",
        "alias": "eth0:0"
    },
    "default_ipv6": {
        "interface": "eth1",
        "address": ... ,
        "prefix": ... ,
        "scope": ...,
        "gateway": ...,
    },
    "eth0": {
        "macaddress": xxxx..,
        "mtu": 1500,
        "type": "ether",
        "ipv4": [
            {
                "address": "192.168.1.1",
                "netmask": "255.255.255.0",
                "network": "192.168.1.0",
                "alias": "eth0"
            },
            {
                "address": "192.168.1.2",
                "netmask": "255.255.255.0",
                "network": "192.168.1.0",
                "alias": "eth0"
            },
            {
                "address": "192.168.1.3",
                "netmask": "255.255.255.0",
                "network": "192.168.1.0",
                "alias": "eth0:0"
            }
        ],
        "ipv6": [
            {
                # No changes
                "address": ... ,
                "prefix": ... ,
                "scope": ...
            },
            {
                ...
            }
        ]
    }, # close interfaces.eth0
    "eth1": {
        ...
    }
} # close interfaces
```

### CODE REVIEW

**Comment by akhayyat** [comment]
I am willing to update the docs, if that is a concern.

**Comment by mpdehaan** [comment]
what facts actually changed here and how?   This doesn't tell me what I get from this patch, leaving it up to me to do the before/after diff...

**Comment by akhayyat** [comment]
Description updated.

**Comment by mpdehaan** [comment]
While the organization is mostly good (mixing defaults with real interfaces is a little tricky), I don't like including the data in here twice as it nearly doubles the memory consumption of Ansible on large pools of hosts, so I'm not going to take this.

I would be ok with adding a "default_ipv4_interface" fact as dicussed on list.

**Pull request closed without merging**
