### PR TITLE
Load plugins from playbook basedir

### PR DESCRIPTION
**Pull request by dhozac**

### CODE REVIEW

**Comment by jpmens** [comment]
Very good idea!

**Comment by mpdehaan** [comment]
Yep, very good idea.    One catch... maybe...

In the case where a playbook imports a playbook in a different directory, self.runner.basedir will, IIRC, change -- which may make this difficult to tell what directory to use.

What happens in that case?

**Comment by mpdehaan** [comment]
Thinking about this some more, what we really want to do is make a module path configurable from the config file.

This way even if you have multiple playbooks you don't have to keep them relative to those paths.

Something like

action_plugins =  (blank) 

for the default

and then

action_plugins=/opt/ansible/modules

if you wanted to set it, etc.

It should look in that path as well as the set location.

ditto for connection_plugins, callback_plugins

This might even could default into something like /usr/share/ansible_plugins_enabled/(type)

and we could do Debian-style packaging in

/usr/share/ansible_plugins_avialable

Thus you could have them all installed and then symlink in the ones you wanted to use.

I am thinking a bit ahead, but anyway, long story short, I think these paths should be set from the config file instead of the playbook.

**Comment by dhozac** [comment]
I agree that having them settable in the configuration file is also useful, so that is now implemented as well. However, I think it should still check for plugins in basedir, at least for action_plugins. This is just like library/, and I think it makes the most sense for the cases where you need a push-side module for one specific task. My reason for doing this was my need for a backup action_plugin, which should go with my backup.yml playbook, as that is the only place where it should be used.

**Comment by jpmens** [comment]
And when you're done, Daniel, I'd very much appreciate a short paragraph for https://github.com/jpmens/ansible-booklet on how to configure and what order plugins are searched for. :-) Thanks.

**Comment by mpdehaan** [comment]
Both together sounds good.

**Comment by dhozac** [comment]
Want to reopen this or should I file another pull request?

**Comment by mpdehaan** [comment]
Yeah, send me another pull request.

**Pull request closed without merging**
