### PR TITLE
Add sshpass to Dockerfile for Ansbile integration tests

### PR DESCRIPTION
**Pull request by abraverm**
##### SUMMARY
Support SSH with password to integration tests targets.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
test/utils/docker

##### ANSIBLE VERSION
```
ansible 2.4.0
```

### CODE REVIEW

**Comment by abraverm** [comment]
#25865

**Comment by mattclay** [comment]
@abraverm Please maintain sort order when adding packages to the list.

**Comment by mattclay** [comment]
`sshpass` should be in the list just before `subversion`

**Comment by mattclay** [comment]
Container images are being built on Docker Hub now.

**Comment by mattclay** [comment]
Images have been rebuilt.

**Pull request merged**
