### PR TITLE
Properly parse escaped special arguments

### PR DESCRIPTION
**Pull request by dhozac**
Fixes issue #1134

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for fixing this, but what is "l_args" meaning as a variable name?   :)

**Comment by dhozac** [comment]
I was thinking of list of arguments, but I can change it to something else if you prefer.

**Comment by dhozac** [comment]
Hmm, looking at it some more, I'm going to clean it up some, and just name it args.

**Comment by mpdehaan** [comment]
Thought so, wanted to be sure :)

Fair enough, I'll let you update this PR if that works for you.

**Comment by mpdehaan** [comment]
went ahead and merged this, will take other patches on top and such if needed

**Pull request merged**
