### PR TITLE
Change "raw" functionality to "custom"

### PR DESCRIPTION
**Pull request by tastychutney**
Removed the raw functionality in preference to custom: adds the parameters "custom" and "custom_change".

"custom" contains a full Django admin command, including custom arguments, as you indicated a preference for.

"custom_change", if present, contains a string to look for in the command output that indicates that changes were made.

### CODE REVIEW

**Comment by mpdehaan** [comment]
django_manage is ok because django admin is something else.  It's kind
of established at this point :)

**Comment by tastychutney** [comment]
django_admin.py just does the same thing as manage.py.

Has 1.1 been released?

-scott

**Comment by mpdehaan** [comment]
It's bad form to rename a module in a pull request after it's already been accepted.  Plus as it only does manage.py, that seems reasonable to me.   Rabbit is done similarly.

**Comment by tastychutney** [comment]
Understood.

**Comment by mpdehaan** [comment]
I don't want to accept a pull request that moves something and moves it back so I'll let you submit a version that just makes the changes you need to make relative to the upstream.

Thanks!

**Pull request closed without merging**
