### PR TITLE
Add option for tower inventory to give general metadata

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
This adds an option which, if enabled, will return additional information about the remote tower server which the plugin is returning mirroring content from.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/tower.py

Ansible Tower inventory plugin

##### ADDITIONAL INFORMATION
We need to know license type to tell apart AWX vs. Ansible Tower, and I also thought that version and ansible_version would be of general utility.

Ping @matburt @wenottingham 

Example of using this parameter:

```

ansible-inventory -i private/tower/tower.yml --list --export
```

```json
{
    "_meta": {
        "hostvars": {
            "HostMachinePossiblenew": {
                "ansible_connection": "local", 
                "ansible_host": "127.0.0.1", 
                "remote_tower_enabled": "true", 
                "remote_tower_id": 588
            }
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ], 
        "vars": {
            "tower_metadata": {
                "ansible_version": "2.7.5", 
                "license_type": "open", 
                "version": "2.0.1-1068-g09684e2c41"
            }
        }
    }, 
    "ungrouped": {
        "hosts": [
            "HostMachinePossiblenew"
        ]
    }
}
```

The id and enabled variables are already kind of "metadata", but are host specific.

I did wonder if it might be better to create a new group, and put the variables in there (that way, if you are using multiple inventory sources, they don't get messed up). Either way, it doesn't matter to me. This is my initial pass because it seems like the path of least clutter.

### CODE REVIEW

**Comment by AlanCoding** [comment]
Requesting review @ryanpetrello @rooftopcellist

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
shipit

**Review by matburt — APPROVED** [review]

**Comment by matburt** [comment]
shipit

**Comment by rooftopcellist** [comment]
shipit

**Comment by AlanCoding** [comment]
bot_status

**Comment by AlanCoding** [comment]
> automerge: automerge shipit test failed

What does that mean? Where can I find the output from this test?

**Comment by gundalow** [comment]
Looks like commit was after the last  s h i p i t

shipit

**Comment by kdelee** [comment]
shipit

**Comment by rooftopcellist** [comment]
shipit

**Comment by gundalow** [comment]
That did it thanks, merged into `devel` for release in Ansible 2.8.

**Pull request merged**
