### PR TITLE
Add ipaddr() filter plugin

### PR DESCRIPTION
**Pull request by drybjed**
With `ipaddr()` filter plugin you can test and manipulate IP addresses and network ranges inside Jinja2 templates. `python-netaddr` library is used as the backend and is required on Ansible Controller, but not on remote hosts.

More information and usage examples can be found here: https://github.com/drybjed/ansible-ipaddr-filter

### CODE REVIEW

**Comment by bmoar** [comment]
Beats parsing strings w/ python. public/private query is neat. :+1:

**Comment by kiranos** [comment]
Worked great for me, I have it in filter_plugins/ until merged

**Comment by resmo** [comment]
+1 use it, works for me

**Comment by clickfreak** [comment]
+1, thanx @drybjed !

**Comment by surpr1ze** [comment]
+1

**Comment by redrampage** [comment]
+1

**Comment by magicrobotmonkey** [comment]
+++1 using ansible to configure switches, this is essential!

**Comment by triplem** [comment]
+1

**Comment by abadger** [comment]
Basically looks good :-)  Things to modify:
- Instead of failing on load if the ipaddr library is unavailable, set a flag and fail with the message to install python-netaddr when the filter is used. 

Refactorings (could be done after merge):
- Exception catching would be better if it was targeted at specific exceptions rather than catching almost anything
- Experience with large if-elif-else chains in service and facts make me leary of their long-term maintainability.  Perhaps we should use the dict-dispatching idiom instead:

``` python
def bool_query(v):
    if v:
        return True
[...]
query_actions = {'bool': bool_query, [...]}
[...]
try:
    return query_actions[query]()
except KeyError:
    [...]
    raise errors.AnsibleFilterError(alias + ': unknown filter type: %s' % query)
```

**Comment by abadger** [comment]
@drybjed Okay, here's most of the cleanups to the code: https://github.com/ansible/ansible/compare/pr-9560?expand=1

I smoketested with a few examples from your ipaddr repo but I did not try out all of the functionality.  If you have some playbooks to run further tests to make sure I didn't break things, that would be great.

Two things that aren't in here:
- Specifying exceptions.  I was afraid of changing the behaviour of the code.  I think that most of your bare exceptions are meant to act like "If any error occurred: return False" so that seems like it would be a valid use of an unspecified exception.  If there are exceptions which aren't meant to be used like that, though, they should be specified instead.
- The meaning of this piece of code changed but I'm not sure if it was a bug before:

``` python
        ### ?? 6to4 and link-local were True here before.  Should they still?
        if query and (query not in query_func_map or query == 'cidr_lookup') and ipaddr(query, 'network'):
            iplist = netaddr.IPSet([netaddr.IPNetwork(query)])
            query = 'cidr_lookup'
```

6to4 and link-local weren't in the query_types list.  This conditional was checking for things to be in there.  The logic looks like those queries should have been in query_types before (otherwise they would have become a cidr_lookup when they encountered this conditional) so I think the new code fixes a bug.  What do you  think?

**Comment by drybjed** [comment]
@abadger Thanks for the rewrite! As for `6to4` and `link-local` not being in `query_types`, you're right - looks like I've forgot to add them to that list when I added the code later, I wonder why they still work...

`ipaddr()` is designed to filter both strings and lists, like:

```
'{{ (ansible_all_ipv4_addresses + ansible_all_ipv6_addreses) | ipaddr("public") }}'
```

Most of the filters either return a correct value or `False`, otherwise list functionality would choke on first incorrect value - that way you can just filter out incorrect ones and discard (or just pass in case of `wrap`) the rest.

I'm going to check your version with my playbook and report back shortly if any errors show up.

**Comment by drybjed** [comment]
@abadger: I filtered my example README script through your version and `git` didn't show any changes, so I think we're good to go. :+1:

**Comment by abadger** [comment]
Yay!  Excellent.  Looks like we're good for code then.  We also want to document the new filters.  Do you want to take a stab at consolidating the relevant portions of your README into playbooks_variables.rst ?  We could do it as a separate PR if you want; we just have to make sure it gets documented.

**Comment by drybjed** [comment]
@abadger sure, I'll see what I can do. I wrote that README with inclustion into `playbooks_variables.rst` in mind (it's even in reStructuredText, what a coincidence!), so I think most of it could go there. Will do a separate PR.

**Comment by abadger** [comment]
Thanks @drybjed !  I've merged the modified version.  Feel free to ping me on IRC when you have the documentation PR ready.

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
