### PR TITLE
allow debug to be 'changed'

### LINKED ISSUE #14430: "changed_when: True" does not display the task as changed
Ansible version 2.0.0.2
Expected "Test changed_when" to be "changed" and yellow. Was "ok" and green instead.

**changed_when_test.yml:**

``` yaml

---
- name: Test Play
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Test changed_when
      debug: msg="This should be changed"
      changed_when: True
```

**Result:**

```
PLAY [Test Play] *********************************************

TASK [Test changed_when] *******************************************************
ok: [localhost] => {
    "msg": "This should be changed"
}

PLAY RECAP *********************************************************************
localhost        : ok=1    changed=1    unreachable=0    failed=0
```

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

debug
##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

fixes #14430

### CODE REVIEW

**Comment by mattclay** [comment]
Unit tests need to be updated. They are checking to make sure changed is false.

**Comment by ericcitaire** [comment]
The original behavior is back in 2.3.1.0 (see commit 4b10f3c13c404b30232aa70b49b3f19539107916). Is this intentional?

**Comment by dale-c-anderson** [comment]
It's probably worth creating a new issue to re-fix this. My use case is the same as yours - the operator needs to know that a reboot is necessary, but it shouldn't be done by the playbook.

**Comment by martinm82** [comment]
Did someone create an issue for 2.3.1.0?

**Comment by manelclos** [comment]
Just hit this, any solution please?

**Comment by jamescassell** [comment]
This fix seems to work only when the debug is not subject to `with_items`... rather annoying.

**Pull request merged**
