### PR TITLE
Allow task includes to work with with_items

### PR DESCRIPTION
**Pull request by dhozac**
This will allow constructs such as:
### playbook.yml

```

---
- hosts: all
  vars_files:
  - vars/users.yml
  tasks:
  - include: tasks/user.yml user=$item
    with_items: $users
```
### vars/users.yml

```

---
- username: timmy
  gecos: Timmy
  groups:
  - group1
  - group2
```
### tasks/user.yml

```

---
- name: create user ${user.username}
  action: user name=${user.username} comment=${user.gecos}

- name: add user to groups
  action: user name=${user.username} groups=$item append=yes
  with_items: ${user.groups}
```

Among many others. Similarly for deploying the same codebase with a few different settings.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Sounds good -- I'm not sure if people would attempt with_items on other types of includes but so far no one has asked so I figure this is still a very nice upgrade even if those others do not work that way.

(Playbook includes aren't parameterized anyway.   Maybe they should be?)

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by dhozac** [comment]
Yeah, I didn't think it made much sense for playbook includes to have this, as you can't really have vars at that point. Listing something as an include versus a line in a with_items seems about the same to me.

**Comment by mpdehaan** [comment]
I will file something for 0.9

**Comment by abondis** [comment]
can it be that it only works with vars_files vars and not hosts_vars?

**Comment by mpdehaan** [comment]
Yes this is true as the playbook is parsed prior to thinking about hosts.  You are correct.

-- Michael

**Pull request merged**
