### PR TITLE
[stable-2.13] Convert non-docs *.rst files to *.md (#81217)

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Backport of https://github.com/ansible/ansible/pull/81217

* Rename README.rst to README.md

* Change README format from reStructuredText to Markdown

* Fix whitespace in README.md

* Update setup.cfg to use README.md

* Replace changelog placeholder with README.md

* Update package-data sanity test (cherry picked from commit 38e50c9f819a045ea4d40068f83e78adbfaf2e68)

##### ISSUE TYPE

Docs Pull Request

##### COMPONENT NAME

*.rst

### CODE REVIEW

**Comment by mattclay** [comment]
> No commit pushedDate could be found for PR 81224 in repo ansible/ansible

@webknjaz This is interesting. The first few times I spotted this, I suspected there was something wrong with the PR itself, perhaps due to age. However, seeing it on a recent PR, and having it working on a second attempt has me thinking it's an issue with GH or AZP instead. Have you seen this elsewhere?

**Comment by webknjaz** [comment]
Yes, I've seen this in a few other PRs last night.

I pasted "No commit pushedDate could be found for PR" into the Gmail search box and it returned 1 email dated Jun 22, 2022, and 5 results from Jul 14, 2023.

**Pull request merged**
