### PR TITLE
Feature/module elb security group

### PR DESCRIPTION
**Pull request by mmoyle**
##### SUMMARY
Attach one or more security group to an existing alb. 

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME
elb_security_group

### CODE REVIEW

**Comment by samdoran** [comment]
This would be a good module to add to an [Amazon Collection](https://github.com/ansible-collections?q=aws&type=&language=).

**Comment by mmoyle** [comment]
> This would be a good module to add to an [Amazon Collection](https://github.com/ansible-collections?q=aws&type=&language=).

Hi @samdoran , thanks for the comment. I guess the module would be moved there for 2.10? I am not sure how to run ansible-test in that repo though.

**Comment by jillr** [comment]
Hi @mmoyle. Yep, this would be need to be PR'ed against https://github.com/ansible-collections/community.aws.

https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#developing-collections

To run integration tests on a collection, you'll need to have the collection cloned locally and any dependencies cloned or installed (community.aws depends on https://github.com/ansible-collections/amazon.aws) and the path to the collections in your collections search path.  ie; if I have community.aws in ~/collections/ansible_collections/community/aws then I would:
`export ANSIBLE_COLLECTIONS_PATHS="~/collections:/.ansible/collections:/usr/share/ansible/collections"`
Then you can run ansible-test from the collection directory, like
`jill@lab:~/collection/ansible_collections/community/aws$ ansible-test integration module_name `

**Comment by Akasurde** [comment]
Hi @mmoyle, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.aws<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
