### PR TITLE
cloud: ovirt: add module to manage storage connections

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_storage_connections

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

This patch adds new module to manage storage connections in oVirt.

### CODE REVIEW

**Comment by machacekondra** [comment]
shipit

**Comment by machacekondra** [comment]
@mwperina

**Review by mwperina — APPROVED** [review]
👍

**Comment by machacekondra** [comment]
@ryansb

**Review by mwperina — APPROVED** [review]
👍

**Pull request merged**
