### PR TITLE
systemd/service: check is-enabled stdout as well

### LINKED ISSUE #28247: systemd and service modules don't check is-enabled stdout values, causing false positives
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
systemd
service

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /Users/rsteinfeldt/Documents/discovery-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Aug  8 2017, 13:46:50) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
None of significance

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Both
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py#L536 and
https://github.com/ansible/ansible/blob/stable-2.3/lib/ansible/modules/system/systemd.py#L383
have the same basic logic check failure. Their purposes in each module are essentially the same for the sake of this bug, and both locations need to be fixed:

Neither module properly parses the return code '0' coupled with the stdout value 'indirect'. They return the false positive that a systemd service/Unit file is enabled when it is not, therefore always producing a Changed status and attempting to disable a service when disabling it does nothing.

From the systemctl man page, 0 and indirect indicates that the "Unit file itself is not enabled, but it has a non-empty Also= setting in the "[Install]" section, listing other unit files that might be enabled."

With any systemd service that has an Also= section, ansible will indicate that it has disabled a service that may already be disabled.

##### STEPS TO REPRODUCE
An RHEL 7 type series linux will show this error well:
1. Install rpcbind package.
2. Run [systemd|service] name="rpcbind.service" state="stopped" enabled="no"
3. Running (2) repeatedly will yield an ansible 'changed' state despite the fact that the service is already stopped and disabled.

##### EXPECTED RESULTS (My best guess)
"systemctl is-enabled" should interpret stdout strings when the return code is 0 as follows:
enabled* : Service is enabled.
static: Service is disabled, and if a user is attempting to enable the service, return an error.
indirect: Service is disabled.

I suggest that if a user desires to enable/disable/stop/start/query a parallel Unit file that will make a queried unit file return 'indirect', that they should do so explicitly.

##### ACTUAL RESULTS
A unit service which has a return code of 0 from 'systemctl is-enabled' is assumed to be enabled when it may not be, because stdout return values aren't checked at all.

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/28247

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
systemd
service

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by samdoran** [comment]
Did some testing with these changes and now `state=started enabled=yes` reports a change each time, which isn't covered in the tests. This is probably due to the output of `systemctl is-enabled rpcbind` is `indirect`. The code in the module is looking for `'enabled' in out`, which will be false. Might need to add another test to check for`indirect`, though it's kinda tricky with how to interpret it since it does not clearly indicate if the service is enabled on not. From `systemd` man page:

```
           │"indirect"        │ Unit file itself is not   │ 0            │
           │                  │ enabled, but it has a     │              │
           │                  │ non-empty Also= setting   │              │
           │                  │ in the "[Install]"        │              │
           │                  │ section, listing other    │              │
           │                  │ unit files that might be  │              │
           │                  │ enabled.                  │              │
```

The original issue suggested interpreting `indirect` to mean 'Service is disabled', but this will result in a change reported each time. This doesn't seem ideal.

**Comment by skylerbunny** [comment]
I've done some poking around at this, and I think I understand what we should be testing for. (For what it's worth, it's complicated. Puppet has gone through the exact same misery with this issue, I've discovered; see https://tickets.puppetlabs.com/browse/PUP-7163 and related.)

The key seems to be the [Install] section of a systemd service file. 
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#%5BInstall%5D%20Section%20Options

Given the following conditions, here's what 'systemctl is-enabled X' seems to return, based on my working with rpcbind.service -- of course, after issuing a daemon-reload:
Only 'WantedBy=' or 'RequiredBy=': 'is-enabled' will return either 'enabled' or 'disabled'.
'Also=' AND ('WantedBy=' or 'RequiredBy='): will return 'enabled' or 'disabled'.
ONLY 'Also=': will return 'indirect'.
None of these: will return 'static'.

Based on this behavior, I'd say that the "indirect" stdout return help should more properly say this:
'Unit file is not enabled, and no mechanism to do so exists in the [Install] section. However, the unit file has a non-empty 'Also=' setting in the '[Install]' section, so issuing 'systemctl enable' or 'systemctl disable' against this unit file will attempt to enable or disable those services listed in the 'Also=' section.'

The way we seem to be able to tell if anything happened when we issue a 'systemctl [dis|en]able X' against a unit file with only an 'Also=' section (an 'indirect' status) is if we get output from the result of the disable/enable command: a symlink being created for an enable, or removed for a disable.

**Comment by skylerbunny** [comment]
I gave this thought overnight and did some more testing. I think I'm getting a better understanding of how systemctl enable and disable actually works. (Editorial comment: ...Ugh.) ```systemctl is-enabled``` does not report a state of ```indirect``` if there is another line in the ```[Install]``` section of the unit file which tells it to report a state of ```enabled``` or ```disabled``` with higher priority. Nevertheless, actually *executing* ```systemctl (dis|en)able X``` WILL act on an ```Also=``` line if it is present.

Either we need some other effective way of determining if a unit file authoritatively *HAS* ```Also=``` dependencies in its install section, from the command line (keeping in mind we can't check a unit file itself, because there could be changes in it that haven't been daemon-reloaded), or...

...we're going to have to assume that any Unit with an ```is-enabled``` state of enabled, disabled, or indirect *MAY* have an Also line. In that case, we'd have to fall back to actually issuing ```systemctl (dis|en)able``` to act on that possibility, and report a Change or No Change based on the standard output of that command.

In other words, for systemd Unit X,
1. If user wants 'enable':
  a. If the stdout of ```systemctl is-enabled X``` is enabled, indirect, or disabled, issuing 'enable' may/will do something. Run ```systemctl enable X```. If nothing is returned in stdout, service was already enabled and Ansible has seen no Change. If something is returned, meaning symlinks were modified, Unit X and/or ```Also=``` Units were enabled, and Ansible should report Changed.
2. If user wants 'disable':
  a. If the stdout of ```systemctl is-enabled X``` is enabled, indirect, or disabled, issuing 'disable' may/will do something. Run ```systemctl disable X```. If nothing is returned in stdout, service was already disabled and Ansible has seen no Change. If something is returned, meaning symlinks were modified, the Unit and/or ```Also=``` Units were disabled, and Ansible should report Changed.

**Comment by mkrizek** [comment]
@skylerbunny how to approach this in the check mode though? We shouldn't run `systemctl enable X` in the check mode to see if we should report `changed`, we'd need to revert that which seems silly. Having said that, I don't have better idea at the moment.

**Comment by skylerbunny** [comment]
The real issue seems to be that the check (itself) is not sufficient to determine whether we should actually run the enable or disable, because ```systemctl is-enabled``` doesn't return use cases that Ansible ideally would like to see to do this "the way we do it" or for that matter, the way a rational automation tool will **want** to do it. I've opened a bug with them, https://github.com/systemd/systemd/issues/6681 , asking for a better implementation.

**Comment by mkrizek** [comment]
Closing, we can re-visit once the issue is resolved upstream.

**Pull request closed without merging**
