### PR TITLE
Fix for issue #56137 - problem with Chassis/Power URI

### LINKED ISSUE #56137: Problem with redfish_facts - Chassis - GetChassisPower
##### SUMMARY
The redfish_facts GetChassisPower command does not work on some systems (e.g. HPE iLO 5) because of assumptions in the code about the URI to the power information.

**Root Cause:**

The method used to construct the URI to the Power information assumes some things about the segments.

`redfish_utils.py` line 1046:
```python
                response = self.get_request(self.root_uri + chassis_uri +
                                            "/" + key)
```
In the case of iLO 5 the chassis_uri contains a trailing slash, resulting in a constructed URI with a double slash: `https://<ip>/redfish/v1/Chassis/1//Power`.  A second problem is that this assumes the suburi to Power is `"Power"` which is not guaranteed by spec until Redfish 1.6 and its URI specifications.

A change that is more in line with Redfish principles is to take the URI from the link:

```python
               response = self.get_request(self.root_uri+data[key]['@odata.id'])
```

NOTE:  even this assumes all URIs are relative to root_uri.  A service that used absolute URIs would still not work, but I don't know of any of those.  I wonder if these should be using `urparse.urljoin()` functions and other logic to guarantee proper assembly of segments.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
redfish_facts (problem is in redfish_utils)

##### ANSIBLE VERSION
```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 3.6.3 (default, Mar 20 2018, 13:50:41) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```
ANSIBLE_NOCOLOR(/etc/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles', '/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT
CentOS

##### STEPS TO REPRODUCE

```yaml
- name: Test Redfish modules
  hosts: localhost
  gather_facts: false
  vars:
    baseuri: IPADDR
    user: USERNAME
    password: PASSWORD

  tasks:

    - name: Get Chassis Power
      redfish_facts:
        category: Chassis
        command: GetChassisPower
        baseuri: "{{ baseuri }}"
        username: "{{ user }}"
        password: "{{ password }}"
```

##### EXPECTED RESULTS

Output like this:
```
TASK [Get Chassis Power] ********************************************************************************************************************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"redfish_facts": {"chassis_power": {"entries": [{"PowerCapacityWatts": 500, "PowerConsumedWatts": 0, "PowerMetrics": {"AverageConsumedWatts": 0, "IntervalInMin": 20, "MaxConsumedWatts": 0, "MinConsumedWatts": 0}}], "ret": true}}}, "changed": false}
```

##### ACTUAL RESULTS

The following output:

```
TASK [Get Chassis Power] ********************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'data'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1557169030.74096-151454169883598/AnsiballZ_redfish_facts.py\", line 125, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1557169030.74096-151454169883598/AnsiballZ_redfish_facts.py\", line 117, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1557169030.74096-151454169883598/AnsiballZ_redfish_facts.py\", line 51, in invoke_module\n    spec.loader.exec_module(module)\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_redfish_facts_payload_vijwehp0/__main__.py\", line 346, in <module>\n  File \"/tmp/ansible_redfish_facts_payload_vijwehp0/__main__.py\", line 303, in main\n  File \"/tmp/ansible_redfish_facts_payload_vijwehp0/ansible_redfish_facts_payload.zip/ansible/module_utils/redfish_utils.py\", line 1048, in get_chassis_power\nKeyError: 'data'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### PR DESCRIPTION
**Pull request by mgarrett33**
##### SUMMARY
Assemble the Power URI from @odata.id information in the Chassis resource

Fixes #56137 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
redfish_facts

##### ADDITIONAL INFORMATION
Test against HPE ProLiant servers with iLO 5

BEFORE CHANGE

The following output:

```
TASK [Get Chassis Power] ********************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'data'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1557169030.74096-151454169883598/AnsiballZ_redfish_facts.py\", line 125, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1557169030.74096-151454169883598/AnsiballZ_redfish_facts.py\", line 117, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1557169030.74096-151454169883598/AnsiballZ_redfish_facts.py\", line 51, in invoke_module\n    spec.loader.exec_module(module)\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_redfish_facts_payload_vijwehp0/__main__.py\", line 346, in <module>\n  File \"/tmp/ansible_redfish_facts_payload_vijwehp0/__main__.py\", line 303, in main\n  File \"/tmp/ansible_redfish_facts_payload_vijwehp0/ansible_redfish_facts_payload.zip/ansible/module_utils/redfish_utils.py\", line 1048, in get_chassis_power\nKeyError: 'data'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
AFTER CHANGE

Output like this:
```
TASK [Get Chassis Power] ********************************************************************************************************************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"redfish_facts": {"chassis_power": {"entries": [{"PowerCapacityWatts": 500, "PowerConsumedWatts": 0, "PowerMetrics": {"AverageConsumedWatts": 0, "IntervalInMin": 20, "MaxConsumedWatts": 0, "MinConsumedWatts": 0}}], "ret": true}}}, "changed": false}
```

### CODE REVIEW

**Review by billdodd — APPROVED** [review]
Thanks, @mgarrett33 for the contribution! I reviewed and tested. Looks good.

shipit

**Comment by mgarrett33** [comment]
Thanks you @billdodd.  For submission etiquette:  Am I finished here or is there something else I need to do after your shipit comment?

**Comment by billdodd** [comment]
> Thank you @billdodd. For submission etiquette: Am I finished here or is there something else I need to do after your shipit comment?

@mgarrett33 - You don't need to do anything else. The PR does need one more community maintainer to review and approve. I expect that will happen shortly. (@jose-delarosa @mraineri)

**Comment by jose-delarosa** [comment]
Tested it, doesn't appear to impact Dell systems, same message as before:

```
{
    "ansible_facts": {
        "redfish_facts": {
            "chassis_power": {
                "msg": "Key Power not found.",
                "ret": false
            }
        }
    },
    "changed": false,
    "failed": false
}

```
shipit

**Comment by samerhaj** [comment]
verified on Lenovo system, and works as intended

shipt

**Comment by mraineri** [comment]
shipit

**Comment by resmo** [comment]
I am about to merge this, but this patch seems a good candidate to backport to 2.8 and 2.7. 

To do so, a changelog fragment file is required. See https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment how this should look like. Ping me for any questions. Thanks.

**Comment by mgarrett33** [comment]
@resmo - I hope I did this right.  changelog frag added.

**Pull request merged**
