### PR TITLE
Added apt-get upgrade and dist-upgrade option

### PR DESCRIPTION
**Pull request by RaymiiOrg**
Via issue #766.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks good to me, this is useful!  

Can you add the "versionadded" attribute on this new flag like some of the other modules use?  That way someone reading the docs and using 1.0 won't wonder why the flag is not there.

Thanks!

**Comment by RaymiiOrg** [comment]
I've added the flag, but I'm not sure which version I should choose, so I did 1.1. Should I do a new pull request?

**Comment by RaymiiOrg** [comment]
Oh how nice, github automaticly notices my new commit. Never mind my question then. Should there be a check to see if the 'upgrade' flag is called with other flags like 'package'? So that people get an error if they think the 'upgrade' flag upgrades packages instead of the distro? (apt package=vim upgrade=yes instead of apt package=vim state=latest)

**Comment by mpdehaan** [comment]
Yes, I think that check would be very good.

**Comment by RaymiiOrg** [comment]
That should do it. Simple if check and little doc update.

**Comment by RaymiiOrg** [comment]
@mpdehaan I have the code for the yum upgrade as well, but since github only does pull requests based on branch I cannot commit that yet until this code is in.

**Comment by lardcanoe** [comment]
Just a FYI, in my playbooks I had to use
- command: sudo DEBIAN_FRONTEND=noninteractive; apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade

to prevent prompts, such as those from grub from messing things up.

**Comment by RaymiiOrg** [comment]
@lardcanoe Added them. Thanks!

**Comment by mpdehaan** [comment]
thanks, in queue for merging probably Saturday, much appreciated!

**Comment by lardcanoe** [comment]
I got the solution from http://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt

Note the use of "sudo DEBIAN_FRONTEND=noninteractive"

I actually did need that to prevent the grub prompt. (Tried with/without it).

**Comment by RaymiiOrg** [comment]
@mpdehaan great! Expect another pull request for the Yum code.

@lardcanoe the module already uses nointeractive in the default apt-command: 

```
DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical
```

(Line 103 of the apt module)

the dpkg options however are good.

**Comment by mpdehaan** [comment]
BTW, since github does pull requests by branch a great idea is to start a new branch for each idea you are working on.

**Comment by mpdehaan** [comment]
looking at this now, BTW...

**Comment by mpdehaan** [comment]
merged, thanks!

**Comment by legrostdg** [comment]
The current apt module seems to have no "upgrade" option... Did you really merge commit e78b796?

**Comment by roller** [comment]
I also don't see this change.  e78b796063a409b875b19c68d8a5ffc8b4dcdcc7 and its ansible side parent (f00f3e4d3a1a18f0bb23572e2bd0070405fede6a) are both missing from devel.

**Comment by mpdehaan** [comment]
ok will reopen and look shortly.

**Comment by mpdehaan** [comment]
grr, git won't let me reopen.   Can you send this again?

**Pull request merged**
