### PR TITLE
[Backport] vmware_guest: Fix "KeyError: 'changed'"

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
This is a backport of vmware_guest fix.

Fixes: #27390 

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION
```
Stable-2.3
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by saamalik** [comment]
LOL just ran into this problem today. Would be great if this could be merged

**Comment by Akasurde** [comment]
@saamalik Could you please test this patch and let me know if it's working?

**Comment by Akasurde** [comment]
@jctanner Thanks for review and merge.

**Pull request merged**
