### PR TITLE
Adding ldap_attr module

### PR DESCRIPTION
**Pull request by jtyr**
##### ISSUE TYPE

New Module Pull Request
##### COMPONENT NAME

`ldap_attr`
##### ANSIBLE VERSION

For Ansible 2.3
##### SUMMARY

This PR is adding a new module that allows to add/change/remove LDAP attributes. The module is based on the code from Peter Sagerson who gave me the [permission](https://bitbucket.org/psagers/ansible-ldap/pull-requests/2/adding-params-option-and-other-minor/diff#comment-16809629) to publish it.

### CODE REVIEW

**Comment by jtyr** [comment]
Migrated from https://github.com/ansible/ansible-modules-extras/pull/2951

**Comment by jtyr** [comment]
@drybjed @jangrewe I have moved this PR from the obsolete [ansible-modules-extras](https://github.com/ansible/ansible-modules-extras/pull/2951) project to here and would like to ask you to comment with the magic word ":boat:it" to allow this module to be merged.

**Comment by drybjed** [comment]
shipit

**Comment by jtyr** [comment]
@jangrewe, please could you comment with the _magic word_ to help to merge this module? The `ldap_entry` module has been already merged (#19285).

**Review by privateip — CHANGES_REQUESTED** [review]
missing METADATA

**Comment by jtyr** [comment]
@privateip Please could you point me to some documentation describing the structure of the `ANSIBLE_METADATA` (if that's what you mean by the `METADATA`)?

**Comment by privateip** [comment]
@jtyr see [here](https://github.com/ansible/proposals/issues/30)

**Comment by jtyr** [comment]
@privateip I have added the `ANSIBLE_METADATA` definition. Please review.

**Review by privateip — APPROVED** [review]

**Comment by privateip** [comment]
Thanks... merged into devel

**Pull request merged**
