### PR TITLE
ACI: Do not encode query_string (backport)

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
It appears ACI fails signature authentication when commas are encoded
in the URL. It expects its signature to be created with commas intact.

This is a backport of #56783 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ACI

### CODE REVIEW

**Comment by smnmtzgr** [comment]
bot_status

**Comment by smnmtzgr** [comment]
shipit

**Comment by abadger** [comment]
Could you add a changelog fragment for this since the use of urlencode was present in the 2.8.0 release?

**Comment by dagwieers** [comment]
Sure. There's no escaping the changelog dance I guess :-)

**Comment by abadger** [comment]
Merged for the 2.8.1 release

**Pull request merged**
