### PR TITLE
ec2_tag: move to boto3, implemented diff and max_attempts support

### PR DESCRIPTION
**Pull request by hryamzik**
##### SUMMARY

- fixed issue with role-based profiles by moving to boto3
- added diff support
- added max_attempts support

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME

ec2_tag

##### ANSIBLE VERSION

```
2.6.1
```

##### ADDITIONAL INFORMATION
Relates to #43348.

### CODE REVIEW

**Comment by s-hertel** [comment]
There is another pull request for this in the works right now (https://github.com/ansible/ansible/pull/39712). Do you mind testing it out and seeing if it meets your needs?

**Comment by hryamzik** [comment]
Oh, I've missed it. That PR doesn't add diff and retries options that really help me with large amount of volumes.

**Comment by hryamzik** [comment]
Looks like you've been waiting for a new PR to merge a previous one and get conflicts, lol.

**Comment by hryamzik** [comment]
Hold on, I'm trying to resolve conflicts. Not sure how to tune retries settings for `module.client('ec2')`...

**Comment by hryamzik** [comment]
@s-hertel I didn;t manage to reproduce any connection issues with a new code but it doesn't support diff, [`AttributeError: 'AnsibleAWSModule' object has no attribute '_diff'`](/ansible/ansible/issues/43377). Any ideas how to fix this?

I also [failed](/ansible/ansible/issues/43379) to find a way to push configuration settings to `AnsibleAWSModule`.

**Pull request closed without merging**
