### PR TITLE
when tqm.terminate() called, task queuing should stop at once

### PR DESCRIPTION
**Pull request by ruozeng-w**
##### SUMMARY

When TaskQueueManager.terminate() is called, ansible does not stop queuing task immediately, the last task which is waiting for queuing will still be queued. If we want to terminate a play, it may because there are wrong actions running, or actions are running on wrong targets, we should break the loop once we find that tqm._terminated is True, to minimize damage.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

immediate termination
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jborean93** [comment]
@jimi-c are you able to have a look at this one please? Not sure if your recent performance changes are touching this as well.

**Comment by ruozeng-w** [comment]
Not sure why check is canceled? Any problem of the merge?

**Review by jimi-c — APPROVED** [review]

**Comment by Akasurde** [comment]
@ruozeng-w Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

**Comment by mkrizek** [comment]
> Not sure why check is canceled? Any problem of the merge?

Yes, please [rebase your branch](http://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html) to remove the merge commit.

**Comment by jborean93** [comment]
Closing due to inactivity. If you wish to continue forward with the PR please rebase so the tests can run and add a changelog to document the bugfix.

**Pull request closed without merging**
