### PR TITLE
Update aws_api_gateway to AnsibleAWSModule 

### PR DESCRIPTION
**Pull request by ryansb**
##### SUMMARY

Remove duplicated fail_json_aws function, argspec, and other imports by replacing AnsibleModule with AnsibleAWSModule.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

aws_api_gateway

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by willthames — APPROVED** [review]
Looks good to me - are there tests around aws_api_gateway that have been run to double check this change?

**Comment by ryansb** [comment]
Yup, I ran the tests at https://github.com/ansible/ansible/tree/devel/test/integration/targets/aws_api_gateway on my own account, and they are also run in CI.

**Comment by willthames** [comment]
Cool, thanks Ryan, merged.

**Comment by s-hertel** [comment]
Broke unittest, fixed for the future here: #42712

**Pull request merged**
