### PR TITLE
BUGFIX: fix service mgmt under systemctl

### PR DESCRIPTION
**Pull request by robparrott**
funky argument creation made erroneous calls to start/stop systemctl services.

This fixes for me ... others may want to test.

### CODE REVIEW

**Comment by mpdehaan** [comment]
What was being fed in for 'arguments' in this case?   The space seems like it wouldn't cause problems...

**Comment by robparrott** [comment]
It was being fed something like "iptables iptables." I.e.

   $ systemctl stop iptables iptables

Systemctl barfed because it interpreted the 2nd iptables string as a path.

**Comment by sfromm** [comment]
I think I see the problem.  The module first checks the status of the service in question.  At that time, it sets `self.arguments` to `(self.name, self.arguments)`.  The module then goes back through service_control() after it has determined a change is needed and then sets `self.arguments` to the same value again.  This results in `self.name` being appended to `self.arguments` twice, which then results in `systemctl start iptables iptables`.

What about adding a local variable `arguments` in service_control(), initialized to `self.arguments`, to limit changes to that scope?

One last comment:  should probably set self.syslogging to False when updating this PR.

**Comment by robparrott** [comment]
Hi,

Is there are issue with this fix as proposed?

Thanks,
Rob

**Comment by sfromm** [comment]
Yes, I think so.  The patch does not preserve self.arguments as provided by the user.  service_control() should be updated to limit changes to `arguments` to only that scope.

**Comment by sfromm** [comment]
I proposed an alternate fix in PR #2466.

**Comment by robparrott** [comment]
Go with alternate fix.

**Pull request closed without merging**
