### PR TITLE
Sshkey manager library (like, don't like?)

### PR DESCRIPTION
**Pull request by bradobro**
Michael,

Great to see that ansible activity lately.

I use this library for my own deployments. Not really asking you to pull yet, just give feedback if you might like it for core, changes if so, etc.

Also, my apologies for git malpractice. We're a Mercurial shop (since our service hosts about 45K Mercurial repos). I know you're re-thinking your git flow, but I'd love to see a post from you about which branches you like developers to track against and issue pull requests to.

Good leadership!
--Brad

### CODE REVIEW

**Comment by mpdehaan** [comment]
yeah, pull requests should be against 'integration', which will be renamed 'devel' later.   

I'll look it over later tonight, thanks.  If we like this (haven't reviewed yet), I will probably ask for a squash commit so the merge history doesn't get in there.

**Comment by mpdehaan** [comment]
closing just because it's on the wrong branch, so I don't accidentally merge it with the web button, which would be bad... maybe post to the mailing list so we can discuss, with a link to this.

**Comment by mpdehaan** [comment]
BTW, when you do this, please explain what it does with example usage.... don't make me read the code to try to understand.

How do I interact at the CLI and filesystem level, etc.

**Comment by bradobro** [comment]
Great feedback Michael. Thanks.

**Comment by shlomozippel** [comment]
Hey - Did sshkey make it into ansible? I cant seem to find it in either ansible/ansible or bradobro/ansible trees. I would love to use this module if possible, thanks!

**Comment by shlomozippel** [comment]
Never mind - just found authorized_key :)

**Pull request closed without merging**
