### PR TITLE
Fixes for broken asa_config module

### PR DESCRIPTION
**Pull request by ogenstad**
##### SUMMARY
The ASA modules (networking) stopped working in Ansible 2.3. This PR will fix the asa_config module, however it doesn't yet address all of the functionality. The action plugin asa_config was removed (and will have to be re-added) so the template / backup feature hasn't been implemented yet.

Also the [enable mode decorator](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cliconf/__init__.py#L44-L51) seems unreliable for this code. So it doesn't always work when a isn't logged into enabled mode from the start. It looks like the authorize function doesn't always trigger upon connecting. 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - asa_config

##### ANSIBLE VERSION
```
ansible 2.4.0 (asa_config_migration cf6de2c281) last updated 2017/07/24 08:57:33 (GMT +200)
  config file = None
  configured module search path = [u'/Users/patrick/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/patrick/src/forks/ansible/lib/ansible
  executable location = /Users/patrick/src/forks/ansible/bin/ansible
  python version = 2.7.10 (default, Sep 11 2015, 19:53:23) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by ogenstad** [comment]
Rebased to fix pep-8 issue.

**Comment by ogenstad** [comment]
The unreliable issues mentioned with the @enable_mode decorator was actually due to the below code in the asa action plugin.

```python
        # take the shell out of enable mode
        if pc.become:
            req = json.dumps(request_builder('get', 'disable'))
            out = connection.exec_command(req)
```

This broke the code if you were using multiple tasks in a playbook as the next task would start in disabled mode.

**Comment by ogenstad** [comment]
This should be ready for review now. Haven't looked at the asa_cli module yet, if this is merged it should be easy enough to fix that one.

**Comment by jmcgill298** [comment]
@ogenstad 

ASA5510 running asa915-21-k8.bin

- The doc strings are missing `auth_pass` param

- I  have issues configuring when my AAA account is set to default exec-mode:
  `aaa authorization exec LOCAL auto-enable`
    * without `authorize` and `auth_pass` I get `"msg": "operation requires privilege escalation"`
    * with `authorize: yes` and `auth_pass: "{{ password }}"` I get `"msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
`
   * with `authorize: no` I usually get successfull playbook execution

- creating crypto ike policies and static routes are not idempotent

- AttributeError is raised when setting `save: yes`
  ```"Traceback (most recent call last):\n  File \"/tmp/ansible_MimKNr/ansible_module_asa_config.py\", line 340, in <module>\n    main()\n  File \"/tmp/ansible_MimKNr/ansible_module_asa_config.py\", line 335, in main\n    run(module, result)\n  File \"/tmp/ansible_MimKNr/ansible_module_asa_config.py\", line 286, in run\n    module.config.save_config()\nAttributeError: 'AnsibleModule' object has no attribute 'config'\n"```

**Comment by ogenstad** [comment]
@jmcgill298, thanks for testing!

I'll look at the doc strings. 

For the logins, I think the first error is due to this code. Basically it's a decorator which can be used to ensure that the user is in enable mode. It looks for a prompt which ends with `#`, but I that the prompt at times is evaluated to `None`

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cliconf/__init__.py#L44-L51

The latest commit adding the `strip()` should hopefully solve the second issue. It works for me, but that might also need an added check if it would evaluate to `None` there too. 

>with authorize: no I usually get successfull playbook execution

Can you elaborate on "usually"? :)

>creating crypto ike policies and static routes are not idempotent

Would you be able to share the tasks you use to try this?

>AttributeError is raised when setting save: yes

Ah,  yes that's probably not implemented. I always execute the save as part of a handler instead. But it should be easy to add.

Again, thanks for testing!

**Comment by jmcgill298** [comment]
@ogenstad 

`Can you elaborate on "usually"? :`
Sometimes I get the same errors of unable to open shell or needing to authorize; but most of the time the playbook does execute and apply the necessary configs. Not sure why I would get inconsistent behavior, but it definitely isn't 100% success; and making no changes it works on subsequent executions.

`creating crypto ike policies and static routes are not idempotent
Would you be able to share the tasks you use to try this?`
```
---
- name: ENSURE CONFIG FRAGMENTS EXIST VIA JINJA TEMPLATING
  hosts: asa
  connection: local
  gather_facts: False
  tasks:
    - name: ENSURE FULL VPN CONFIG EXISTS
      asa_config:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        src: "./asa.conf"
        authorize: no
```
```
name 200.1.1.1 ASA2_PUBLIC
object-group network ASA1_INTERESTING_TRAFFIC
 network-object host 100.1.1.20
 network-object 100.1.2.0 255.255.255.0
object-group network ASA2_INTERESTING_TRAFFIC
 network-object host 200.1.1.20
 network-object 200.1.2.0 255.255.255.0
access-list ACL-ASA2 extended permit ip object-group ASA1_INTERESTING_TRAFFIC object-group ASA2_INTERESTING_TRAFFIC
crypto ipsec ikev1 transform-set AES-256_SHA esp-aes-256 esp-sha-hmac
crypto ikev1 policy 200
 authentication pre-share
 encryption aes-256
 hash sha
 group 5
 lifetime 86400
crypto map L2L_MAP 200 match address ACL-ASA2
crypto map L2L_MAP 200 set pfs group5
crypto map L2L_MAP 200 set peer ASA2_PUBLIC
crypto map L2L_MAP 200 set ikev1 transform-set AES-256_SHA
crypto map L2L_MAP 200 set security-association lifetime seconds 28800
crypto map L2L_MAP interface outside
route outside ASA2_PUBLIC 255.255.255.255 100.1.1.2
route outside 200.1.1.20 255.255.255.255 100.1.1.2
route outside 200.1.2.0 255.255.255.0 100.1.1.2
```

I also tried using lines, but got the same result.

**Comment by privateip** [comment]
needs_rebase

**Comment by ogenstad** [comment]
@privateip, the rebase seems to be because of #23336 was merged. However it looks like that was commited due to a documentation bug. No other *_config module seems to return the "responses" key (from the documentation. Should that functionality be in the module or should that PR be reverted?

**Review by BobbyGR — COMMENTED** [review]
Playbook:
---
- hosts: VF
  gather_facts: false
  connection: local
  vars:
    cli:
      host: "{{ IP }}"
      username: "{{ un }}"
      password: "{{ pw }}"
      authorize: no
      transport: cli

  tasks:
    - name: Set default group policy's
      asa_config:
        lines:
          - dns-server value 8.8.8.8 4.2.2.2
        match: line
        parents: 'group-policy NOACCESS attributes'
        provider: "{{ cli }}"
      when:
        - DC == "ATL1"


Worked: Ansible 2.2
Failed with this patch:

fatal: [ATL1-LAB2]: FAILED! => {"changed": false, "failed": true, "msg": "operation requires privilege escalation"}
fatal: [ATL1-LAB1]: FAILED! => {"changed": false, "failed": true, "msg": "operation requires privilege escalation"}

**Comment by BobbyGR** [comment]
So, digging into my issue here.

ansible/plugins/cliconf/__init__.py
   This is where i'm getting a call with the "operation requires privilege escalation".  I changed the output of this to return what str(prompt) and it just came back with "--->"  not even sure how it got that as it's not even in my motd on the ASA.  

if I disable this check, it passes but as expected it didn't do anything. 
authorize:no  as it defaults to '#' upon login

Syslog confirms it's logging in, just not doing anything
Would like to debug it a bit more but everything is pretty nested here. trying to unravel this 
has been fun.

**Comment by BobbyGR** [comment]
Seems it's getting stuck on : '<--- More --->'  
not sure how/when as it logs in and it's just looking for #  

digging deeper...

**Comment by BobbyGR** [comment]
Seems i'm having the same issue I was having in version 2.2

Because I drop the user off already enabled, I had to edit the asa.py (in 2.2) for line #49 and change error: to something like error123: and use authorize: yes to get it to apply anything.

If I use authorize: no, it will not apply the task

So right now if I kill the search for # 
and if I can find where asa.py (2.2) line #49 was moved to 
I should be able to get this to work

Seems a bit heavy but I really want to use ansible for my fleet of asa's and can be available to testing when needed.

**Comment by privateip** [comment]
@ogenstad can you rebase this PR so I can get it merged?

**Comment by ogenstad** [comment]
I can rebase it, however I'd like to chat about the PR which caused this to need a rebase. I think that was merged in error, if it wasn't I will have to fix other issues related to that too. Are you available for a short chat tomorrow?

**Comment by ogenstad** [comment]
@jmcgill298, I looked at the example you provided for the routes

When you use this config:
route outside ASA2_PUBLIC 255.255.255.255 100.1.1.2

The resulting config in the ASA will instead look like this:
route outside ASA2_PUBLIC 255.255.255.255 100.1.1.2 1

That's why it's not idempotent. I would guess it's the same for the other config?

**Comment by ogenstad** [comment]
@privateip, rebased.

**Pull request merged**
