### PR TITLE
Added support of an optional init method for action modules like rsync that need to alter the connection and other inject data before it's established.

### PR DESCRIPTION
**Pull request by tima**
This is a potential solution to #3612 that is blocking #3173.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you link to your example usage in your rsync tree?

I'm probably fine with this, though naming it "init" is somewhat confusing
with "**init**" ... maybe "setup"?

Also you could test with getattr to see if the method was there and avoid
the try/except (and this would avoid catching other AttributeErrors inside)

**Comment by tima** [comment]
I will push my rsync tree momentarily. I'm OK switching the method name. init is just what came to me.

**Comment by tima** [comment]
This commit shows how the rsync module would use it.

https://github.com/tima/ansible/commit/32b8d86d75ee14fa3cc38a8c213ed8cbe47aeb86

**Comment by mpdehaan** [comment]
That seems fine to me.

I'd make sure steps called after are not forced to 127.0.0.1, but I suspect
they should not be.

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
