### PR TITLE
aix distribution facts overhaul

### PR DESCRIPTION
**Pull request by flynn1973**
##### SUMMARY

more usefull aix oslevel facts

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
distribution

##### ADDITIONAL INFORMATION

```
{'ansible_distribution_release': '1', 'ansible_distribution_major_version': '7', 'ansible_distribution_version': '71', 'ansible_distribution_technology_level': '5', 'ansible_distribution_build_date': '1731', 'ansible_distribution_service_pack': '1'}

```

### CODE REVIEW

**Comment by bcoca** [comment]
doesn't this also change the information in non backwards compatible ways?

If you want the 6100- ... format vs the 6.1.0... one i suggest creating new keys instead of repurposing the existing ones.

**Comment by flynn1973** [comment]
its common practice in the aix crowd to use the oslevel -s format, so this change might be reflected positive ;-)

**Comment by flynn1973** [comment]
+label aix

**Comment by flynn1973** [comment]
closed in favour of #63233

**Pull request closed without merging**
