### PR TITLE
Moved generated module RSTs to their own directory.

### PR DESCRIPTION
**Pull request by dharmabumstead**
##### SUMMARY

Moves generated module RSTs to their own subdirectory and updates index.html to point to the modules_by_category file.

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by gundalow — CHANGES_REQUESTED** [review]
This will need some more work, as links from the main docs to any modules are broken, e.g.
```
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/porting_guide_2.4.rst:85: WARNING: undefined label: win_msi (if the link has no caption the label must precede a section header)
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/porting_guide_2.4.rst:85: WARNING: undefined label: win_package (if the link has no caption the label must precede a section header)
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/porting_guide_2.4.rst:90: WARNING: undefined label: win_get_url (if the link has no caption the label must precede a section header)
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/porting_guide_2.4.rst:91: WARNING: undefined label: win_unzip (if the link has no caption the label must precede a section header)
```


Also `make webdocs` doesn't appear to generate html for any modules, nor `list_of_network_$CATEGORY.html` pages.

**Comment by dharmabumstead** [comment]
Should’ve marked it WIP, since I knew I’d have to make another sweep for broken links. 

I will check again, but when I tested this the module HTML and module list pages seemed to generate just fine doing local builds on my system.

**Comment by dharmabumstead** [comment]
@gundalow Let's chat about this on slack Monday. I am getting the 'undefined label' warning on my local build as well, but the links in the local doc build are working.

**Comment by gundalow** [comment]
```
make webdocs
find docs/docsite/_build/ -name "*.html"  | wc -l
303
```

**Comment by gundalow** [comment]
1) `docs/docsite/Makefile`
Need to add `rm -rf modules` into the `clean:` block
Should also keep the existing rm's 60-62 as in case people have files left from a previous `make webdocs`

2) `.gitignore`
needs to include
`docs/docsite/rst/modules/`

**Comment by gundalow** [comment]
3. `docs/bin/plugin_formatter.py`
```
`t = _MODULE.sub(r':ref:`' + r"\1 <module_docs/\1>" + r"`", t)`
```

This will fix the `U(lineinfile)` links in DOCUMENTATION


4. 
Will need to carefully review `make webdocs` output to check for any other broken links

**Comment by bcoca** [comment]
do you want them all 'flat' in module_docs/ or do you want them by category/subcat also?

**Comment by dharmabumstead** [comment]
@bcoca: That'd be OK with me at some point, but for simplicity's sake I'd prefer to leave them flat in the module_docs directory for for now. I just want them out of the root RST directory so I can proceed with the rest of the reorg.

**Comment by gundalow** [comment]
1) Will need rewrite rules on `docs.ansible.com`, though only for 2.5 and on wards
`http://docs.ansible.com/ansible/devel/command_module.html` ->
`http://docs.ansible.com/ansible/devel/module_docs/command_module.html`

2) 
Most of these warnings are caused by this PR
```
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/dev_guide/developing_modules_documenting.rst:191: WARNING: unknown document: ../list_of_all_modules
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/dev_guide/developing_modules_in_groups.rst:25: WARNING: unknown document: ../list_of_all_modules
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/dev_guide/developing_modules_in_groups.rst:29: WARNING: unknown document: dev_guide/testing
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/dev_guide/developing_modules_in_groups.rst:29: WARNING: unknown document: ../list_of_network_modules
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/dev_guide/developing_modules_in_groups.rst:36: WARNING: unknown document: ../list_of_database_modules
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/dev_guide/developing_modules_in_groups.rst:40: WARNING: unknown document: ../list_of_all_modules
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/dev_guide/testing_units.rst:191: WARNING: unknown document: testing_units_running_locally
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/module_docs/win_dsc_module.rst:24: WARNING: unknown document: windows_dsc
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/modules_support.rst:11: WARNING: unknown document: core_maintained
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/modules_support.rst:17: WARNING: unknown document: network_maintained
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/modules_support.rst:17: WARNING: unknown document: list_of_network_modules
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/modules_support.rst:28: WARNING: unknown document: community_maintained
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/playbooks_loops.rst:90: WARNING: unknown document: Jinja2 lookups playbooks_lookups
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/playbooks_loops.rst:90: WARNING: unknown document: filters playbooks_filters
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/playbooks_loops.rst:90: WARNING: unknown document: tests playbooks_tests
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/plugins/callback.rst:16: WARNING: unknown document: mail callback/mail
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/plugins/callback.rst:19: WARNING: unknown document: callback/oxs_say
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/plugins/connection.rst:47: WARNING: unknown document: connection/paramiko
/home/johnb/git/ansible-inc/tmp/dharmabumstead-module-build-move-1/docs/docsite/rst/plugins/lookup.rst:39: WARNING: unknown document: ../template_module
```


3) Will need rewrite rules adding for some/most of (2), especially `core_maintained` ,etc which I believe external sites link to.



Is this really worth all the effort, what's the problem we are trying to solve? If it's files in the way, doesn't `make clean` solve that?

**Comment by dharmabumstead** [comment]
Yes, it's worth the effort; that's why we're doing this. Yes, there are some links that will need fixing.

Unless anyone has an absolute showstopper/build break, I plan on merging this by tomorrow.

**Comment by gundalow** [comment]
Fine as long as the old module URLs continue to work, so the rewrite rules will need adding as soon as this is live.

shipit

**Pull request merged**
