### PR TITLE
windows: fix for checking locked system files

### LINKED ISSUE #30258: win_command,win_shell 'removes'/'creates' argument and win_stat does not detect certain System files
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_command
win_shell
win_stat
+ others?

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT

Managing from: CentOS
Managed systems: Windows

##### SUMMARY
When using the 'removes' or 'creates' argument with win_command or win_shell, some system files such as pagefile.sys, swapfile.sys or hiberfil.sys are not recognized.
Win_stat also omits these files and reports them as non-existing.

##### STEPS TO REPRODUCE

Example step:

```yaml
- name: disable hibernation (remove hiberfil.sys)
  win_command: powercfg.exe -h off
  args:
    removes: '{{ ansible_env.SystemDrive }}\hiberfil.sys'
```

##### EXPECTED RESULTS

Step should run once and the command removes the hiberfil.sys file (hence it should be skipped the next time).

##### ACTUAL RESULTS

Step is never run and skipped with "skipped, since C:\\hiberfil.sys does not exist" in spite the file does exist on the target system.

```
skipping: [testsystem] => {
    "changed": false, 
    "cmd": "powercfg.exe -h off", 
    "msg": "skipped, since C:\\hiberfil.sys does not exist", 
    "rc": 0, 
    "skipped": true
}
```

##### DETAILS
Problem is Powershell 'Test-Path' command, which does omit certain System files - http://www.powertheshell.com/test-path-ignores-hidden-files/ describes the issue and gives a possible fix: eg. in ansible/lib/ansible/modules/windows/win_command.ps1 change Test-Path from
```
If($removes -and -not $(Test-Path -Path $removes)) {
```
to something like
```
if ($removes -and -not ((Test-Path (Split-Path -Path $removes)) -And ([System.IO.Directory]::EnumerateFiles((Split-Path -Path $removes)) -contains $removes))){
```

It seems that not many windows files are affected, but it is annoying when it occurs and it took quite some for me to figure this out. Since win_stat also relies on 'Test-Path', the only workaround I see for my active issue are some raw commands get check the existence of the file.

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
When using `Test-Path` or `Get-Item` on a file that is a hidden system file and is locked (like `C:\pagefile.sys`) they will return `$false` and `$null` respectively even when it does exist. This workaround uses the `Get-ChildItem -Path -Filter` to get a file and return that for modules where this would be useful.

While there are other modules that may be affected by this, I don't believe they would usually touch a file like `pagefile.sys` so I don't believe it is necessary to complicate things there.

This also includes some minor doc fixes to actually set the version `get_md5` for `win_stat` will be deprecated and set the version on the warning message.

This fixes #30258

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
win_command
win_stat
win_shell
win_wait_for

##### ANSIBLE VERSION
```
2.5
```

##### ADDITIONAL INFORMATION
I've done some basic performance tests to see if `Get-ChildItem` with a filter is slower than `Get-Item` or `Test-Path`. In these tests the folder `C:\temp\test` contains just a bit less than 1 million empty files.

##### Test-Path comparison

File Exists
```
PS C:\Users\Administrator.JORDAN> $path = "C:\temp\test\file-123456"
PS C:\Users\Administrator.JORDAN> Measure-Command { Test-Path -Path $path }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 4
Ticks             : 49522
TotalDays         : 5.73171296296296E-08
TotalHours        : 1.37561111111111E-06
TotalMinutes      : 8.25366666666667E-05
TotalSeconds      : 0.0049522
TotalMilliseconds : 4.9522

PS C:\Users\Administrator.JORDAN> Measure-Command { Test-FilePath -path $path }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 4
Ticks             : 49555
TotalDays         : 5.73553240740741E-08
TotalHours        : 1.37652777777778E-06
TotalMinutes      : 8.25916666666667E-05
TotalSeconds      : 0.0049555
TotalMilliseconds : 4.9555
```

File Missing
```
PS C:\Users\Administrator.JORDAN> $path = "C:\temp\test\missing"
PS C:\Users\Administrator.JORDAN> Measure-Command { Test-Path -Path $path }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 1
Ticks             : 15792
TotalDays         : 1.82777777777778E-08
TotalHours        : 4.38666666666667E-07
TotalMinutes      : 2.632E-05
TotalSeconds      : 0.0015792
TotalMilliseconds : 1.5792

PS C:\Users\Administrator.JORDAN> Measure-Command { Test-FilePath -path $path }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 1
Ticks             : 18936
TotalDays         : 2.19166666666667E-08
TotalHours        : 5.26E-07
TotalMinutes      : 3.156E-05
TotalSeconds      : 0.0018936
TotalMilliseconds : 1.8936
```

##### Get-Item comparison

File Exists
```
PS C:\Users\Administrator.JORDAN> $path = "C:\temp\test\file-123456"
PS C:\Users\Administrator.JORDAN> Measure-Command { Get-Item -Path $path -Force }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 1
Ticks             : 16944
TotalDays         : 1.96111111111111E-08
TotalHours        : 4.70666666666667E-07
TotalMinutes      : 2.824E-05
TotalSeconds      : 0.0016944
TotalMilliseconds : 1.6944

PS C:\Users\Administrator.JORDAN> Measure-Command { Get-File -path $path }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 8
Ticks             : 85995
TotalDays         : 9.953125E-08
TotalHours        : 2.38875E-06
TotalMinutes      : 0.000143325
TotalSeconds      : 0.0085995
TotalMilliseconds : 8.5995
```

File Missing
```
PS C:\Users\Administrator.JORDAN> $path = "C:\temp\test\missing"
PS C:\Users\Administrator.JORDAN> Measure-Command { Get-Item -Path $path -Force -ErrorAction SilentlyContinue }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 5
Ticks             : 59818
TotalDays         : 6.92337962962963E-08
TotalHours        : 1.66161111111111E-06
TotalMinutes      : 9.96966666666667E-05
TotalSeconds      : 0.0059818
TotalMilliseconds : 5.9818

PS C:\Users\Administrator.JORDAN> Measure-Command { Get-File -path $path }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 3
Ticks             : 39557
TotalDays         : 4.57835648148148E-08
TotalHours        : 1.09880555555556E-06
TotalMinutes      : 6.59283333333333E-05
TotalSeconds      : 0.0039557
TotalMilliseconds : 3.9557
```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Nice one.
Is there a (performance?) reason for not putting Test-FilePath into module_utils (perhaps not in Legacy but instead maybe in a Filesystem.psm1 )?
A super nice thing to do would be to add something to the dev guide to warn powershell module developers away from using Test-Path, given its limitations.

**Comment by jborean93** [comment]
It seems to be a very niche case where it cannot detect file's. I wasn't able to find a root cause but it seems like files like `C:\pagefile.sys`, `C:\hibernate.sys` are some of the only ones affected and that may be because they are locked by Windows in some case. Looking page we should probably make this a module util though so I will update the PR.

**Comment by dagwieers** [comment]
Should we not move the **Test-FilePath** function into a library ?

**Review by nitzmahone — APPROVED** [review]

**Comment by nitzmahone** [comment]
rebuild_merge

**Review by nitzmahone — APPROVED** [review]

**Comment by nitzmahone** [comment]
rebuild_merge

**Pull request merged**
