### PR TITLE
update ansible-pull installation playbook example

### PR DESCRIPTION
**Pull request by copperlight**
Update playbook that demonstrates ansible-pull installation.  This method of installation relies on an updated ansible-pull that allows specifying a custom playbook, so that each host can run it's own nodes/${ansible_fqdn}.yml from a playbook repo.

These updated examples go along with a separate pull request that updates ansible-pull.

### CODE REVIEW

**Comment by mpdehaan** [comment]
logrotate is very good, but there may not always be a playbook named after the hostname.   The playbook might be named after the group name, which is more likely if the systems are heterogeneous.

What if -P supported an "auto", in which it first looks for hostname.yml (probably relying on asking python what the hostname is) and then defaults to local.yml?   This could also be the default, such that 'auto' is not required. 

Further this should probably be commented _out_ int he example, so by default it uses local.yml and you can engage this behavior if you want.

**Comment by copperlight** [comment]
A very good point -- the -P option allows this flexibility.  As I was building this out, I was focusing at first on the independence of machines, but I definitely see that moving towards group names and classes of machines makes sense.

If I build out -P auto (as a default), does it make sense to search for playbooks at nodes/${ansible_hostname}.yml or shoud the search occur at the top level?  I like pushing the files down one level to keep the top level clear for major playbooks.

Your point about commenting and switching back to local.yml makes sense.

If I push a couple of new commits on these branches to implement these suggestions, do you care if they are squashed or not?

Until now, I have been squashing with rebase -i, which is probably not a good idea anymore, now that I have a open pull request.

**Comment by sfromm** [comment]
Why is _installdir_ defined in ansible_pull.yml?  And why install ansible from git source?  It seems that only encourages users to live off devel on what might be production hosts. 

I'll comment on the -P option in the other PR.

**Comment by sfromm** [comment]
One other thought: I don't think we want to encourage users to leave passwords in plaintext to git repositories that manage infrastructure.  I would excise the example showing how to do that.

**Comment by copperlight** [comment]
installdir was defined in ansible_pull.yml as a supporting mechanism for the git repo clone.  You can clone git repos wherever you like, so you could change this, if you wanted to clone into /opt or another location for some reason.

Most of my work with Ansible lately has been on both Mac OSX and Ubuntu 12.04 systems.  Cloning the public git repo (albeit at a particular version) seems like a good common way of getting it installed on either class of system.  When I first started fiddling with Ansible, I remember seeing the git clone installation instructions first and did not recall seeing the Ubunutu PPA.

Switching from a git clone to a PPA or EPEL is an easy enough thing to do within the playbook, although the git clone feels more immediate, because it is closer to the source.

Since I haven't looked closely at the EPEL or the PPA, do those packages take care of the necessary environment variables?

I could split the middle ground by adding commented out tasks that pull from either the EPEL or the PPA.  If this happens, installdir would likely stay, since it helps feed the crobjob definition.

I can add a "-C release-0.7" to the git clone command so that it is definitively pinned to a release version.

Regarding the password, your point is good, however I couldn't figure out exactly how else to get access to a secured repo.  Perhaps configuring a root SSH key and pinning it to a read-only user in GitHub with access to the repo in question?  I haven't tested this method.

**Comment by sfromm** [comment]
One final thought.  ansible-pull.yml seems very specific to your implementation.  I think you want to encourage the use of best practices such as installing from packages.  And, since ansible-pull.yml is meant to be an example, keep it minimal and topic-specific.  More time is spent installing software manually than setting up the target for ansible-pull.

Sidenote: just saw your latest comment.  I think the above still applies so am leaving as is.

**Comment by copperlight** [comment]
(clicked the wrong button)

I think I get what you are saying; let me take a swipe at making it more generalized.

**Comment by mpdehaan** [comment]
For the record, I'm against any major changes to the ansible-pull example
and in favor of what @sfromm suggested about making ansible-pull take a
playbook name similar to ansible-playbook (and fine if it autodetects when
that argument is not specified).

**Comment by mpdehaan** [comment]
In other words, keep the example simple -- people will make changes as
needed, but should be looking at a reasonably simple example by
default.  I do like the idea of inclusion of a logrotate setup,
however.

**Comment by copperlight** [comment]
Updated ansible-pull example playbook, focusing on simplicity and package re-use.

The example is focused on Ubuntu because I was having some serious problems with RPM dependencies when I was trying to use RHEL 6.2 and EPEL to get Ansible and Python dependencies installed.  Also, the Ubuntu PPA is more up-to-date than EPEL (0.7.2 versus 0.6.1).  However, despite the platform focus, I think this is a pretty clean example.

I created separate playbooks to install and uninstall ansible-pull, because I think this illustrates how a sysadmin can go about keeping their systems clean by undoing their work in a mirrored fashion.

Logrotate example remains intact.

The ansible-pull pull request was updated to take a playbook name like ansible-playbook and it auto-searches for $hostname.yml and local.yml as fall-back options.

**Comment by sfromm** [comment]
How about adding a _is_centos_  variable that detects if it is running on centos and a yum play to install ansible and related packages with _only_if: '$is_centos'_?

The rest of the playbook, while still verbose, is looking better.  Would using with_items for creating the $logdir and $workdir directories help further simplify?

**Comment by copperlight** [comment]
Heh, that was actually my original intention, since it is a great example of how to write a unified playbook.  However, I ran into two problems.

(1) Adding the EPEL and getting the Ansible package requires an extra step compared to the Ubuntu equivalent, since there isn't the equivalent of apt_repository:

```
- name: get EPEL RPM
  action: get_url url=http://mirrors.solfo.com/epel/6/i386/epel-release-6-7.noarch.rpm dest=/tmp thirsty=yes

- name: install EPEL RPM
  action: command rpm -i /tmp/epel-release-6-7.noarch.rpm

- name: install ansible & dependencies
  action: yum pkg=ansible

# RPM dependency problems here
```

If we don't consider this extra verbosity to be a big deal, or there is a better way, then I can roll with it and push it back in.

(2) On my RHEL 6.2 instance, I couldn't get RPM dependencies to be satisfied; specifically the ansible RPM out of EPEL wants python-jinja2 and only python-jinja2-26 exists in yum repos for my particular system.  I could try installing a latest CentOS 6.X machine on VirtualBox to see if I can get that to work.

I was able to test the Ubuntu playbooks successfully for install and uninstall and it would be nice if the Red Hat equivalents worked as well.  However, if we don't particularly care about having the Red Hat playbook work, I can build out a mock-up of what it would look like, if there were no dependency issues.

Combining the directories together would be a bit tighter.

**Comment by copperlight** [comment]
I figured out a better URL and technique to use for EPEL and a fresh install of CentOS 6.3 minimal worked like a charm.

CentOS plays added to the example alongside Ubuntu and successfully tested.

**Comment by sfromm** [comment]
You don't need to specify libyaml, python-babel, or python-crypto for centos.  Those are pulled in via dependencies.  Specifying cronie seems going overboard to me.  Some cron package should already be installed and the example playbook drifts off-topic.

In uninstall, I would only remove ansible-specific items.  The dependencies (eg paramiko) may be used by other applications.

**Comment by mpdehaan** [comment]
discussion can continue, but it's clear this isn't ready yet.

all I want is logrotate

**Comment by copperlight** [comment]
@sfromm Updates complete.

**Pull request closed without merging**
