### PR TITLE
New script to get dynamic inventory from Orion Solar Winds 

### PR DESCRIPTION
**Pull request by cbabs**
##### SUMMARY
New script to get dynamic inventory from Orion Solar Winds.  

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
swinds.py

##### ANSIBLE VERSION
ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

##### ADDITIONAL INFORMATION
Custom dynamic inventory script for Ansible and Solar Winds, in Python.
This was tested on Python 2.7.6, Orion 2016.2.100, and  Ansible  2.3.0.0 - 2.3.1.0

This python script connects to Solar Winds via rest API to create a dynamic inventory in Ansible. JSON data is pulled into the python script via rest https API call to Orion. Groups are based on 'Vendor'. It pulls the 'IPAddress' for hosts field. The impetus for this script was for network devices. As such, the 'IPAddress' was chosen over say hostname. If one wanted to use anisble for servers with DNS using hostnames, replacing the 'IPAdrress' string to 'SysName' should produce that result. One could also change the 'Vendor' to something else like the OS version. I would recommend downloading the SWQL Studio and look under Orion.Nodes table for more options.

### CODE REVIEW

**Comment by gundalow** [comment]
Hi,
The steps on http://docs.ansible.com/ansible/dev_guide/developing_rebasing.html should help you in cleanly rebasing this PR

**Comment by gundalow** [comment]
@cbabs http://docs.ansible.com/ansible/dev_guide/developing_rebasing.html should assist you in fixing this. If you are new to Git I'd suggest backup up the files into a different directory first

If the above documentation doesn't help feel free to as in `#ansible-devel` on Freenode IRC

**Comment by gundalow** [comment]
needs_info

**Comment by alikins** [comment]
Please reopen when the git branch issues are resolved.

Having so many changed files in a pr is causing some problems with repo info tools (like https://ansible.sivel.net/byfile.html) so closing for now.

**Pull request closed without merging**
