### PR TITLE
Add modules for managing illumos networking

### PR DESCRIPTION
**Pull request by xen0l**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
dladm_iptun
dladm_linkprop
dladm_vlan
ipadm_addr
ipadm_addrprop
ipadm_ifprop

##### ANSIBLE VERSION

```
latest
```

##### SUMMARY

These modules extend Ansible's support for configuring networking on Solaris/illumos systems.
With these modules the 90% of networking configuration use cases on Solaris/illumos systems are covered.

### CODE REVIEW

**Comment by privateip** [comment]
Please no more than 1 module per PR

**Comment by xen0l** [comment]
I used this link for reference elsewhere, so I will add a followup comment where to look for PRs:

ipadm_addr - https://github.com/ansible/ansible/pull/19411
ipadm_addrprop - https://github.com/ansible/ansible/pull/19415
ipadm_ifprop - https://github.com/ansible/ansible/pull/19416
dladm_iptun - https://github.com/ansible/ansible/pull/19414
dladm_linkprop - https://github.com/ansible/ansible/pull/19413
dladm_vlan - https://github.com/ansible/ansible/pull/19412

**Comment by xen0l** [comment]
@privateip out of curiosity, there are more PRs with multiple modules inside them. Why did you close only this one?

**Comment by privateip** [comment]
I'm only looking at ones that are labelled networking but as a standard practice we request a single module per PR to make it easier to do code reviews

**Pull request closed without merging**
