### PR TITLE
v2: Fixed logic when looking up become attribute

### PR DESCRIPTION
**Pull request by ahamilton55**
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

``` bash
± % ansible --version                                                                                                                ?[0] !10244
ansible 2.0.0 (detached HEAD fix_task_l) last updated 2015/06/10 20:09:17 (GMT -700)
  lib/ansible/modules/core: (detached HEAD d6ed6113a7) last updated 2015/06/09 17:48:20 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 57813a2e74) last updated 2015/06/09 17:48:20 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/09 16:52:46 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/09 16:52:49 (GMT -700)
  configured module search path = /Users/andrew/workspace/ops/deploy/modules/
```
##### Ansible Configuration:

Nothing has changed in my configuration since this broke with the v2 code.
##### Environment:

OS X 10.10.3
python 2.7.6
##### Summary:

Currently when trying to change the `become` value from a global `yes` to a task level `no` does not work.
##### Steps To Reproduce:

The following playbook is able to reproduce this for me.

``` yaml

---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
      - local_action: command ls -ail
        become: no
```
##### Expected Results:

``` text
 % EC2_REGION=us-west-1 ansible-playbook -i deploy_conf/localhost test.yml

PLAY: ***************************************************************************

TASK [command] ******************************************************************
changed: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
##### Actual Results:

``` text
± % EC2_REGION=us-west-1 ansible-playbook -i deploy_conf/localhost test.yml

PLAY: ***************************************************************************

TASK [command] ******************************************************************
fatal: [localhost]: FAILED! => {"msg": "[sudo via ansible, key=dhylsnsegwlyqivsftvkpiaouxvvdpfa] password: \n", "failed": true, "changed": false, "parsed": false, "invocation": {"module_name": "command", "module_args": {"_raw_params": "ls -ail"}}}

NO MORE HOSTS LEFT **************************************************************

PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

### CODE REVIEW

**Comment by jimi-c** [comment]
Looking at this, I believe this should actually be fixed in the `_get_parent_attribute` method. For example, in task.py:

<pre>
        value = self._attributes[attr]
        if self._block and (not value or extend):
            parent_value = getattr(self._block, attr)
            if extend:
                value = self._extend_value(value, parent_value)
            else:
                value = parent_value
        if self._task_include and (not value or extend):
            parent_value = getattr(self._task_include, attr)
            if extend:
                value = self._extend_value(value, parent_value)
            else:
                value = parent_value
        return value
</pre>

should be:

<pre>
        value = self._attributes[attr]
        if self._block and (value is None or extend):
            parent_value = getattr(self._block, attr)
            if extend:
                value = self._extend_value(value, parent_value)
            else:
                value = parent_value
        if self._task_include and (value is None or extend):
            parent_value = getattr(self._task_include, attr)
            if extend:
                value = self._extend_value(value, parent_value)
            else:
                value = parent_value
        return value
</pre>

Thoughts? Unfortunately I'm having trouble testing this due to another bug that's crept into that code recently:

<pre>
TASK [command] ******************************************************************
fatal: [localhost]: FAILED! => {"msg": "ERROR! privilege output closed while waiting for password prompt:\n", "failed": true}
</pre>

^ ping @bcoca.

**Comment by jimi-c** [comment]
@ahamilton55 I see the above `privilege output closed` error is occurring because of the local connection not quite working with privilege escalation yet, however this works fine with `-c ssh`. Let me know if this solves your problem and I'll merge in my version of the patch (gist here: https://gist.github.com/jimi-c/fe68b8e729d374ef7749).

**Comment by ahamilton55** [comment]
@jimi-c Yeah that patch works for me.

**Comment by jimi-c** [comment]
@ahamilton55 thanks, I've merged my fix in and closed this.

**Pull request closed without merging**
