### PR TITLE
Updated infini* redirects to transition to infinidat collection

### PR DESCRIPTION
**Pull request by ekaulberg**
##### SUMMARY
Updated infini* redirects to transition to infinidat collection

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
infini*

##### ADDITIONAL INFORMATION
As requested in PR3 at https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration

### CODE REVIEW

**Comment by ekaulberg** [comment]
cc @gundalow @thedoubl3j - related to https://github.com/ansible-collections/community.general/pull/607 as discussed via email. Appreciate your quick attention to this.

**Comment by felixfontein** [comment]
#70566 does the same thing, except that it doesn't remove the maintainers from BOTMETA.yml.

**Comment by ekaulberg** [comment]
@felixfontein there is no maintainer for the old removed module - both of the tagged folks are no longer with Infinidat so per discussion with @thedoubl3j I understood they should be removed. Anyway, I can cancel this PR if you'd prefer.

**Comment by felixfontein** [comment]
@ekaulberg in that case your PR is fine - the people mentioned in that line are still able to close PRs/issues for the infini_* modules.

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
I'll create a backport to stable-2.10.

**Pull request merged**
