### PR TITLE
openssl_certificate: Handle dump() in check_mode

### LINKED ISSUE #37867: openssl_certificate on Ansible 2.5 fails: 'NoneType' object has no attribute 'get_notBefore'
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openssl_certificate

##### ANSIBLE VERSION
```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.4 (default, Mar 14 2018, 17:49:05) [GCC 4.9.2]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
[empty]
```

##### OS / ENVIRONMENT
Multiple:
- archlinux
- alpine
- centos
- debian
- fedora
- opensuse
- ubuntu

##### SUMMARY
When using openssl_certificate in Ansible 2.5, an error occurs:
```
AttributeError: 'NoneType' object has no attribute 'get_notBefore
```

##### STEPS TO REPRODUCE
See [the code](https://github.com/robertdebock/ansible-role-httpd) and [the build](https://travis-ci.org/robertdebock/ansible-role-phpmyadmin/builds/357693716) and [the specific line](https://travis-ci.org/robertdebock/ansible-role-phpmyadmin/jobs/357693742#L1116) for details.

```
- name: create ssl key
  openssl_privatekey:
    path: "/tmp/some.key"
  register: key

- name: create ssl csr
  openssl_csr:
    path: "/tmp/some.csr"
    privatekey_path: "{{ key.filename }}"
    common_name: "{{ ansible_fqdn }}"
  register: csr

- name: create ssl certificates
  openssl_certificate:    # <<============ This is the module giving errors.
    path: "/tmp/some.crt"
    privatekey_path: "{{ csr.privatekey }}"
    csr_path: "{{ csr.filename }}"
    provider: selfsigned
```

##### EXPECTED RESULTS
Similar behaviour as Ansible 2.4.

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'get_notBefore'

fatal: [phpmyadmin-ubuntu-artful]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wTx0Xq/ansible_module_openssl_certificate.py\", line 888, in <module>\n    main()\n  File \"/tmp/ansible_wTx0Xq/ansible_module_openssl_certificate.py\", line 862, in main\n    result = certificate.dump()\n  File \"/tmp/ansible_wTx0Xq/ansible_module_openssl_certificate.py\", line 484, in dump\n    'notBefore': self.cert.get_notBefore(),\nAttributeError: 'NoneType' object has no attribute 'get_notBefore'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

### PR DESCRIPTION
**Pull request by Spredzy**
##### SUMMARY

Currently, when ones run the module in check_mode it tries to retrieve
values from the actual certificate generated in the generate() function.

Since in check_mode we call dump() without calling generate(), self.cert
is None, leading to self.cert.get_notBefore(), self.cert.get_notAfter()
and self.cert.get_serial_number() raising an error.

>  NoneType' object has no attribute 'get_notBefore'

The solution is to have two way to handle dump() method, whether its run
in check_mode=True or check_mode=False leading to different way the
information is retrieved.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - openssl_certificate

##### ANSIBLE VERSION

 - devel

##### ADDITIONAL INFORMATION

Fixes: https://github.com/ansible/ansible/issues/37867

### CODE REVIEW

**Comment by robertdebock** [comment]
I've verified this code, works well for me.

**Review by robertdebock — APPROVED** [review]
I ran this code with ansible-2.5.0 (and just this file modified) and it works for me:

```
ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/robertdb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

**Comment by MarkusTeufelberger** [comment]
shipit

**Comment by gundalow** [comment]
Merged into `devel`
PR for `stable-2.5`: https://github.com/ansible/ansible/pull/38462 which I'll merge once green

Thanks for code & reviews

**Pull request merged**
