### PR TITLE
Added module win_domainjoin

### PR DESCRIPTION
**Pull request by trondhindenes**
New module: win_domainjoin.

Joins the computer to the specified AD domain. Parameter for specifying the target OU (distringuishedname) where the computer account should be placed.

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm wondering if this perhaps should be something like win_domain_membership so it could also imply removal

**Comment by trondhindenes** [comment]
Agreed. Updated the module name.

**Comment by mpdehaan** [comment]
Hi!

Just getting time to run through the queue a bit closer now.

We'd like to see a few things tweaked if you don't mind.  If you can help resolve these items, we'd greatly appreciate it:
- parameter names should be with_underscores not runtogether to match Ansible conventions in other modules
- around line 80 in the examples, some things are tabbed or spaced over, and should use spaces and line up with the other lines in the example
- examples in ansible are generally shown using playbook syntax examples rather than /usr/bin/ansible examples, so the /bin/ansible examples should probably be made consistent

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by trondhindenes** [comment]
Gotcha, this version should be better.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
