### PR TITLE
	modified:   lib/ansible/modules/network/ios/ios_command.py

### PR DESCRIPTION
**Pull request by jopaik**
##### SUMMARY

Updating document to show matches regular expression example

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

lib/ansible/modules/network/ios/ios_command.py
##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /users/home/xeccdt4/.ansible.cfg
  configured module search path = [u'/users/home/xeccdt4/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]```


##### ADDITIONAL INFORMATION
<!--- Include additional information to help people understand the change here.
For bugs that don't have a linked bug report, a step-by-step reproduction
of the problem is helpful. -->
Document example to show how to use matches condition under wait_for:
<!--- Paste verbatim command output below, e.g. before and after your change -->
```
Before:
EXAMPLES = """
tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version

  - name: run show version and check to see if output contains IOS
    ios_command:
      commands: show version
      wait_for: result[0] contains IOS

  - name: run multiple commands on remote nodes
    ios_command:
      commands:
        - show version
        - show interfaces

  - name: run multiple commands and evaluate the output
    ios_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] contains IOS
        - result[1] contains Loopback0

  - name: run command that requires answering a prompt
    ios_command:
      commands:
        - command: 'clear counters GigabitEthernet0/2'
          prompt: 'Clear "show interface" counters on this interface [confirm]'
          answer: c
"""

RETURN = """

after:
EXAMPLES = """
tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version

  - name: run show version and check to see if output contains IOS
    ios_command:
      commands: show version
      wait_for: result[0] contains IOS

  - name: run multiple commands on remote nodes
    ios_command:
      commands:
        - show version
        - show interfaces

  - name: run multiple commands and evaluate the output
    ios_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] contains IOS
        - result[1] contains Loopback0

  - name: run multiple commands and evaluate to show 28xx or 29xx series routers and Loopback 0 or 1
    ios_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] matches "2[8-9][0-9][0-9]\s"
        - result[1] matches "Loopback[0-1]\s"

  - name: run command that requires answering a prompt
    ios_command:
      commands:
        - command: 'clear counters GigabitEthernet0/2'
          prompt: 'Clear "show interface" counters on this interface [confirm]'
          answer: c
"""

RETURN = """

```

### CODE REVIEW

**Comment by beeankha** [comment]
Hi @jopaik , thank you so much for submitting your first PR request to this repo!  We'll need to test this before merging, but it's in the works and we'll update on here with a comment as we go through the queue.

**Comment by acozine** [comment]
@jopaik please rebase this PR (see https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html for help on rebasing your branch). We're also requesting a playbook and output showing that the new example works - see the Validation section of https://github.com/ansible/community/issues/311 for the rules, and @IPvSean's comment on https://github.com/ansible/ansible/pull/40369 for an idea of what to do. Reach out if you have questions. Thanks!

**Comment by IPvSean** [comment]
@jopaik can you rebase and re-submit with playbook, playbook output and relevant config as per https://github.com/ansible/community/issues/311 similar to example: https://github.com/ansible/ansible/pull/40369

**Comment by beeankha** [comment]
@jopaik , just pinging to see if you could rebase + provide the info requested above by @acozine and @IPvSean .  If we don't hear back from you by the end of this month (July 2018), we'll close this PR out.

**Pull request closed without merging**
