### PR TITLE
Add openshift inventory plugin

### PR DESCRIPTION
**Pull request by mscherer**
This plugin will list all your git repositories from a openshift
provider, and allow you to manage them using ansible.

The inventory either use a environment variable or reuse the
existing rhc configuration file if it exist.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Great, in queue for review shortly.

I'd be interested in having a conversation about how you are managing things on OS sometime if you want (shoot me an email at michael at ansibleworks.com perhaps?)

Thanks!

**Comment by mscherer** [comment]
I would have loved to discuss this, but I am just a simple user of openshift, I will relay your request to people from the openshift online ops team

**Comment by mpdehaan** [comment]
I think it's fine if you just pass along what you're using it for, really, seeing you did write this, I figure you had a need for it.

Let me know.

Holding off on merging for now.

**Comment by mscherer** [comment]
It was to deploy software using ansible on openshift like I would do on my own servers, ie run stuff like npm install, deploy a specific file, etc. So the idea is to deploy it on a test openshift, and if i decide, to move it to openstack, or my own system, as simple user. ( in my case, this was ethercalc + a plugin ).

**Comment by mpdehaan** [comment]
Sounds reasonable, I'll merge this.   Might be useful for various misc. tasks even if you were using the standard OpenShift management toolchain.

**Comment by mpdehaan** [comment]
merged, thank you!

**Pull request merged**
