### PR TITLE
Close all open filehandle

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/executor/module_common.py
lib/ansible/module_utils/crypto.py
lib/ansible/module_utils/facts/virtual/linux.py
lib/ansible/module_utils/network/aci/aci.py
lib/ansible/module_utils/network/common/config.py
lib/ansible/module_utils/rabbitmq.py
lib/ansible/modules/cloud/amazon/cloudformation.py
lib/ansible/modules/cloud/amazon/iam_cert.py
lib/ansible/modules/cloud/openstack/os_keypair.py
lib/ansible/modules/crypto/openssl_pkcs12.py
lib/ansible/modules/crypto/openssl_publickey.py
lib/ansible/modules/files/assemble.py
lib/ansible/modules/files/unarchive.py
lib/ansible/modules/net_tools/basics/slurp.py
lib/ansible/modules/system/at.py
lib/ansible/modules/system/service.py
lib/ansible/modules/utilities/logic/async_status.py
lib/ansible/modules/web_infrastructure/jenkins_plugin.py
lib/ansible/plugins/action/assemble.py
lib/ansible/plugins/connection/saltstack.py
lib/ansible/plugins/filter/network.py

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
Checked the changes to the crypto modules / module_utils, they look good.

**Comment by bcoca** [comment]
the following files seem fine:
lib/ansible/executor/module_common.py
lib/ansible/plugins/action/assemble.py
lib/ansible/plugins/connection/saltstack.py
lib/ansible/plugins/filter/network.py

the modules and module_utils .. i would not bother as they are implied to be closed as they always execute on a forked process

**Comment by acozine** [comment]
I don't see any documentation changes in this PR. I'm going to remove the `docs` label - not sure why it was applied.

**Review by Qalthos — APPROVED** [review]
+1 for networking changes

**Comment by abadger** [comment]
module_utils does matter as those can be used by controller side code.

modules probably doesn't matter (but could for persistent layers like mitogen or in cornercases like opening a large number of files in a loop) but if the change isn't wrong, it is nicer to clean up after yourself.  I'd leave them.

**Review by bcoca — COMMENTED** [review]
facts should really be using 'get_file_content' as it also deals with many common failure conditions

not a blocker for this PR, just a note that we should eventually change to use that function where possible

**Comment by gundalow** [comment]
So is this good to merge, then a follow up PR can be created to update `facts` to use `get_file_content`?

**Pull request merged**
