### PR TITLE
yum: disableexcludes is supported on centos6

### LINKED ISSUE #51697: disable_excludes errors with disable_includes message
##### SUMMARY
When running the yum module using disable_excludes: all and targetting a Centos6 machine ansible will error with `"msg": "'disable_includes' is available in yum version 3.4 and onwards."`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum module with disable_excludes

##### ANSIBLE VERSION

```
11:27[yum-packages]- ansible --version
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/tfurmston/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tfurmston/ansible2.7/ansible/lib/ansible
  executable location = /Users/tfurmston/ansible2.7/ansible/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
11:27[yum-packages]-

```

##### CONFIGURATION

```
11:27[yum-packages]- ansible-config dump --only-changed
11:28[yum-packages]-
```

##### OS / ENVIRONMENT
ansible machine:
```
11:28[yum-packages]- sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
11:29[yum-packages]-
```
Target machine:
```
cat /etc/redhat-release
CentOS release 6.9 (Final)
```
##### STEPS TO REPRODUCE

Playbook:
```
- hosts: all
  gather_facts: true
  tasks:
    - name: Install a thing
      yum:
        name: kernel-lt
        state: installed
        disable_excludes: all
      when:
        - ansible_facts['distribution_major_version'] == "6"
      register: reboot_required
```
Command:
```
ansible-playbook kernel-lt.yml -i ~/projects/ansible/hosts --limit testbox  --check -vvvv
```

##### EXPECTED RESULTS
I'd expect kernel-lt to be installed

##### ACTUAL RESULTS
Yum module bails because disable_includes is only available in yum 3.4 and above 

```
fatal: [testbox]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": "all",
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [
                "elrepo-kernel"
            ],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 0,
            "name": [
                "kernel-lt"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "installed",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
    "msg": "'disable_includes' is available in yum version 3.4 and onwards."

```

##### ADDITIONAL

I did some digging and these lines  https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum.py#L1482-L1483 is the only instance of disable_includes that I can find.

Commenting this out and running the playbook means it runs as expected.

I'm not sure if I've missed something as disable_includes doesn't appear anywhere else in ansible documentation or repo that I can find and disable_excludes is available in yum 3.3 and below.

It looks like a typo or something to me.

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes  https://github.com/ansible/ansible/issues/51697

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

yum

### CODE REVIEW

**Comment by Akasurde** [comment]
@mkrizek FYI https://github.com/ansible/ansible/pull/34494/files#diff-b3479be3ff6d2becf34cc47a760ccfd4R1311

**Comment by mkrizek** [comment]
@Akasurde so that's where it originates from. So that means the conditional we have now and is being removed in this PR is incorrect, right?

**Comment by mkrizek** [comment]
cc @maxamillion

**Comment by Akasurde** [comment]
`disable_includes` is supported from yum 3.4 onwards, whereas `disable_excludes` is supported since inception. (I am trying to find a document which supports this).

**Comment by maxamillion** [comment]
needs a changelog fragment, but otherwise 👍

**Review by maxamillion — APPROVED** [review]

**Pull request merged**
