### PR TITLE
'force' option for 'file' module.

### PR DESCRIPTION
**Pull request by alopropoz**
Added 'force' option to 'file' module.

With 'force=yes' existing file / directory / symlink will be overwritten instead of 'refusing to convert between directory and link'.
Unit tests included. To let them pass also added 'changed = True' for a case with changed symlink target as per #1008.

I'm totally new to Git and GitHub, if something is wrong, please let me know.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Generally you always want to do "git pull --rebase" rather than doing "git pull / merge" as we don't want merge commits in the history of pull requests.

Also it is a good idea to look up how to do a squash merge so pull requests wind up as one commit.

That being said, I can take care of the squash merge this time.  Be sure you submit documentation on the force= parameter to the ansible/ansible.github.com project.

Edit the rst/modules/file.rst file

**Comment by mpdehaan** [comment]
merged, pushing shortly, thanks!

**Comment by thekad** [comment]
I was scratching my head wondering why the `force` option wouldn't work in 0.9, and finally found it got reverted in SHA: 758370414417414532542c56266a49c8183be4bc but the commit message is not clear about what issues it has

Any specific reason why this got removed and/or any plans to restore said functionality? it is unclear if I can just make do with only_if statements and a bit of python code, but that seems a bit ugly.

**Comment by mpdehaan** [comment]
I don't entirely recall.

Various reasons with the code for force not being functional and force getting overloaded with other meanings and implementations that were causing problems.

**Comment by thekad** [comment]
Fair enough but, the ability to overwrite is still needed. Any plans on bringing it back later or a sane workaround? the use case I can see often is replacing a regular file with a symlink/directory.

**Comment by rabb1t** [comment]
Have the same problem here. If 'force' option has been removed from the main tree, where can I find a workaround for file to be overwritten?

**Comment by rabb1t** [comment]
My bad. It works like a charm with 0.9 version. Inore my previous comment. Thanks.

**Comment by tszming** [comment]
On Ansible 1.2.2

```
touch /tmp/foo
touch /tmp/bar
```

With 

```
file: state=link src=/tmp/foo dest=/tmp/bar owner=root group=root mode=0644 force=yes
```

It return

```
failed: [ansible-test] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/tmp/bar", "size": 0, "state": "file", "uid": 0}
msg: refusing to convert between file and link for /tmp/foo
```

Need a way to unlink the `dest` and link to the `src`

**Comment by jimi-c** [comment]
@tszming I cannot reproduce this on the devel (1.3) branch:

<pre>
$ touch foo bar
$ cat test_link_force.yml 
---
- hosts: all
  gather_facts: false
  tasks:
  - file: state=link src=/root/foo dest=/root/bar owner=root group=root mode=0644 force=yes
$ ansible-playbook -i "localhost," -c local test_link_force.yml 
PLAY [all] ******************************************************************** 
TASK: [file state=link src=/root/foo dest=/root/bar owner=root group=root mode=0644 force=yes] *** 
changed: [localhost]
PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
$ ll foo
-rw-r--r--. 1 root root 0 Aug 22 10:35 foo
$ ll bar
lrwxrwxrwx. 1 root root 9 Aug 22 10:35 bar -> /root/foo
</pre>

**Comment by bcoca** [comment]
I fixed this in my last patch to 1.3, 1.2 will of course 'not work'

**Comment by jimi-c** [comment]
Ahh thanks @bcoca, I missed that patch.

**Comment by greenscar** [comment]
Still seeing this error
failed: [c2astpub1] => (item=/home/cmuser/env_setup/devops/deploy/../../install_files//file.properties) => {"failed": true, "gid": 500, "group": "the", "item": "/home/cmuser/env_setup/devops/deploy/../../install_files//file.properties", "mode": "0777", "owner": "the", "path": "/opt/thetus/install_files/file.properties", "secontext": "unconfined_u:object_r:usr_t:s0", "size": 31, "state": "link", "uid": 500}
msg: refusing to convert between link and file for /opt/the/.ansible/tmp/ansible-1382467841.4-263061804005936/file.properties

**Comment by tszming** [comment]
Tested on 1.3.2 and it is work as expected, thanks.

**Pull request closed without merging**
