### PR TITLE
handle ignore_errors in loop

### LINKED ISSUE #32384: ignore_errors always ignore failures when variable is used to control it
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible-core

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/guenthgr/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
`ansible-config dump --only-changed` returns nothing, but I just have a vanilla ansible.

##### OS / ENVIRONMENT

4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

##### SUMMARY
When I use the 'ignore_errors' options on a task, this works if the boolean is hardcoded like:
```yaml
ignore_errors: false
```

But as soon as the option is set via a variable, that doesn't work any longer:

```yaml
ignore_errors: "{{ ignore_assertion_errors }}"
or
ignore_errors: ignore_assertion_errors
```
In the latter case, this is always handled as `true` so the assertion failures are ignored.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: 127.0.0.1
  vars:
    ignore_assertion_errors: false
  tasks:
    - name: With variable
      assert:
        that: item < 2
        msg: "{{item}} isn't < 2"
      ignore_errors: ignore_assertion_errors
      with_items:
        - 1
        - 2

    - name: With 'false' as hardcoded boolean
      assert:
        that: item < 2
        msg: "{{item}} isn't < 2"
      ignore_errors: false
      with_items:
        - 1
        - 2

```

##### EXPECTED RESULTS
Expect the first task to fail. Second shouldn't even run.

##### ACTUAL RESULTS

First task fails but the failure is ignored.
Second task than fails as expected.

```
TASK [Gathering Facts] **********************************************************************************************************************************
ok: [127.0.0.1]

TASK [With variable] ************************************************************************************************************************************
ok: [127.0.0.1] => (item=1) => {
    "changed": false, 
    "failed": false, 
    "item": 1, 
    "msg": "All assertions passed"
}
failed: [127.0.0.1] (item=2) => {
    "assertion": "item < 2", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "item": 2, 
    "msg": "2 isn't < 2"
}
...ignoring

TASK [With 'false' as hardcoded boolean] ****************************************************************************************************************
ok: [127.0.0.1] => (item=1) => {
    "changed": false, 
    "failed": false, <!--- What did you expect to happen when running the steps above? -->
    "item": 1, 
    "msg": "All assertions passed"
}
failed: [127.0.0.1] (item=2) => {
    "assertion": "item < 2", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "item": 2, 
    "msg": "2 isn't < 2"
}

```

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY

most worked by accident, not using the correct task values
fixes #32384

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
2.4/2.5
```

### CODE REVIEW

**Comment by guenhter** [comment]
```
- hosts: 127.0.0.1
  gather_facts: false
  vars:
    ignore_assertion_errors: false
  tasks:
    - name: With variable
      assert:
        that: item < 2
        msg: "{{item}} isn't < 2"
      ignore_errors: ignore_assertion_errors
      with_items:
        - 1
        - 2
```

Results in the error:

```
ERROR! The task includes an option with an undefined variable. The error was: 'item' is undefined

The error appears to have been in '/private/tmp/playbook.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: With variable
      ^ here
```

On branch `devel` it runs through (falsely but it doesn't crashes)

**Comment by bcoca** [comment]
@guenhter sorry, try again now, i ended up finding a deeper error and ran through several iterations, but at this point it should be correct for all cases.

**Comment by guenhter** [comment]
@bcoca I checked and there is one thing left I don't completely understand (and maybe isn't even a bug).

In the playbook above: 

When I use:

```
      ignore_errors: "{{ignore_assertion_errors}}"
```

This works perfectly fine. BUT

```
      ignore_errors: ignore_assertion_errors
```

seems always evaluate to `false`

I wasn't sure if this is expected so I checked with `changed_when`:

```
      changed_when: ignore_assertion_errors
```

This does exactly what I expect: when the variable is true, it show a change in the recap, if the variable is false it doesn't.

So the good news is, that your fix is working with the `{{ variable }}` expression, but just `variable` doesn't work.

**Comment by bcoca** [comment]
`when:` clauses have an 'implied' `{{ }}` so they do not need it, every other keyword requires the `{{}}` to process variables.

**Comment by guenhter** [comment]
Ok, thanks for the clarification. Than this seems fine.

**Comment by nelsg** [comment]
For information:
I'm faced the same issue when I upgraded from Ansible 2.2.1 to 2.3.2.
After some tests, this regression was introduced with Ansible 2.3.0.
Then caution if you planed to upgrade to a version higher than 2.2.3, choose at least version 2.4.2.

Maybe this fix must be integrated with future version 2.3.3, no ?

**Pull request merged**
