### PR TITLE
Pure Storage facts fix

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Facts were not getting populated into the main ansible_facts dict correctly

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
modules/storage/purestorage/purefa_facts.py
modules/storage/purestorage/purefb_facts.py

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by samdoran** [comment]
Please create a changelog fragment. See [this fragment](https://github.com/ansible/ansible/blob/stable-2.7/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

**Review by resmo — APPROVED** [review]
shipit

**Comment by gundalow** [comment]
Merged into `devel`, if you could please raise a backport PR we can get this into 2.7 as well. Thanks!

**Comment by sdodsley** [comment]
@gundalow backport submitted #50418

**Pull request merged**
