### PR TITLE
Google: gcpubsub_facts -> gcpubsub_info

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Renames the only non-autogenerated Google module for #57277.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
gcpubsub_facts

### CODE REVIEW

**Comment by rambleraptor** [comment]
Thanks a lot for the PR! I'm a Google engineer that's been working on the GCP modules.

We have two new modules (`gcp_pubsub_topic_facts` and `gcp_pubsub_subscription_facts`) that are replacing the gcpubsub_facts module. We can definitely rename this module, but the goal is to deprecate it in the near future.

**Comment by felixfontein** [comment]
The question is whether the module should be deprecated in 2.9 or not. If it will only be deprecated later, it needs to be renamed. If it will be deprecated for 2.9, it's better to not rename it.

**Comment by samccann** [comment]
@rambleraptor can you address the prior comment so we know whether to merge this PR?  thanks!

**Comment by felixfontein** [comment]
@rambleraptor ping

**Comment by felixfontein** [comment]
I've rebased to remove the conflicts with ignore.txt for sanity checks and the porting guide. If nobody complains, I will merge this soon. In case it is still decided (before 2.9's Feature Freeze) that the module should be deprecated instead, the deprecation PR can as a first step revert this PR's commit.

**Review by samccann — APPROVED** [review]
Docs portion LGTM

**Comment by felixfontein** [comment]
@rambleraptor @samccann thanks for your feedback!

**Pull request merged**
