### PR TITLE
Handle file common args in maven_artifact module

### LINKED ISSUE #21577: Handle file common args in maven_artifact module
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module `maven_artifact`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The module should handle default file arguments to set dest file owner, group, mode and others.

##### STEPS TO REPRODUCE

```yaml
- maven_artifact:
  group_id: ...
  artifact_id: ...
  dest: /tmp/artifact.jar
  mode: '0755'
  owner: user
```

##### EXPECTED RESULTS

`/tmp/artifact.jar` is created with filemode '0755' and owned by 'user'.

##### ACTUAL RESULTS

`/tmp/artifact.jar` use default mode and is owned by `remote_user`

### PR DESCRIPTION
**Pull request by zigarn**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

Module `maven_artifact`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

Fixes #21577.

Add handling of file common args in `maven_artifact` module.
Also set required file attributes in case of no download but bad attributes of present file.

### CODE REVIEW

**Comment by calfonso** [comment]
@zigarn would you mind rebasing this, thanks! @chrisisbeef are you able to review this?

**Comment by tumbl3w33d** [comment]
Hi @zigarn, can you rebase this once more, please? I will review it then asap.

**Comment by tumbl3w33d** [comment]
Just noticed this is obsolete. There is another PR (#24965) that does the same thing and will hopefully get merged soon.

**Comment by tumbl3w33d** [comment]
close_me

**Pull request closed without merging**
