### PR TITLE
Make module_utils.known_hosts.get_fqdn work on ipv6

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by abadger** [comment]
I think we have some code to parse ipv6 in https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/addresses.py but unfortunately we can't use that yet because of the modules <=> controller divide.

Would the following be valid host strings that would cause problems?

```
 'ssh://[2001:DB8::abcd:abcd]:22/example.git'
username@[2001:DB8::abcd:abcd]/example.git
username@[2001:DB8::abcd:abcd]:22/example.git
```

**Comment by mscherer** [comment]
I was planning on be doing baby steps, but I can also add them and update the PR after seeing what is broken or not.

**Comment by mscherer** [comment]
So yeah, it break. i guess a more robust code is needed.

**Comment by abadger** [comment]
Thanks @mscherer !

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by abadger** [comment]
Pushed to stable-2.0 and devel

**Pull request merged**
