### PR TITLE
Provide functionality to work with Rackspace's public cloud

### PR DESCRIPTION
**Pull request by omgjlk**
This provides a rax module to create or delete instances in Rackspace's public cloud. It also provides a rax inventory plugin to discover hosts within the cloud as well. Both make use of pyrax, the official python SDK for working with the Rackspace public cloud.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Awesome, will be great to have this in there!

I am thinking it might be nice to have some more examples on how to use the other types of services too?   Or would people just be able to figure that out (cloud_loadbalancers, etc)?

The other thing you may want to show for examples as those lines are getting a bit long is something like:

```
- name: whatever this step does
  rax:
      param1: foo
      param2:  bar
```

Which allows you to break stuff up into more than one line.   If you include the module call in a play that just targets local, the local action isn't needed.

Otherwise it is just:

```
- name: whatever this stuff does
  local_action:
      module: rax
      param1: foo
      param2: bar
```

Releasing 1.1 code Tuesday, so will dig through shortly thereafter!

**Comment by omgjlk** [comment]
On Mar 31, 2013, at 7:41 AM, Michael DeHaan notifications@github.com wrote:

> I am thinking it might be nice to have some more examples on how to use the other types of services too? Or would people just be able to figure that out (cloud_loadbalancers, etc)?

I agree it would be nice. Those other services are non-functional at this time, the first release is just about cloudservers. As support for other services get implemented the examples will get updated too.

> The other thing you may want to show for examples as those lines are getting a bit long is something like:
> - name: whatever this step does
>   rax:
>       param1: foo
>       param2:  bar
> 
> Which allows you to break stuff up into more than one line. If you include the module call in a play that just targets local, the local action isn't needed.
> 
> Otherwise it is just:
> - name: whatever this stuff does
>   local_action:
>       module: rax
>       param1: foo
>       param2: bar

Thanks, I'll update the examples to look more like that.

**Comment by mpdehaan** [comment]
Great!

BTW, if the other services are non-functional, I would remove them from the choices array so people don't try them.

**Comment by mpdehaan** [comment]
merged, thanks... I am wondering if we need to mention the environment variables when the module already takes them, it seems like we might not need to.

**Comment by omgjlk** [comment]
On Apr 5, 2013, at 10:21 AM, Michael DeHaan notifications@github.com wrote:

> merged, thanks... I am wondering if we need to mention the environment variables when the module already takes them, it seems like we might not need to.

I mention them because they are necessary when using the inventory plugin, so I wanted people to be able to specify the credential location and region once rather than once via environment and once as options to the rax module.

I've put in the other recommended changes and those will be in a new pull request.

-jlk

**Pull request merged**
