### PR TITLE
Add roles support for the script module

### LINKED ISSUE #2969: Support scripts dir in roles
Could we extend roles to support scripts?

So 

```
- script: myscript.sh
```

Gets automagically sucked up from, roles/myrole/scripts/myscript.sh

?

### PR DESCRIPTION
**Pull request by srgvg**
allows to put scripts directly in a dir within the
role:  roles/<role>/scripts/..
Same as the copy and template module.

Tests: http://paste.ubuntu.com/5698156/

As requested in and closes #2969

### CODE REVIEW

**Comment by mpdehaan** [comment]
This generally looks good.  I have a bit of a concern that people using 1.2 with scripts up until this point will be broken by this code, so can we first check in the 'scripts/' dir and if the file is there, use it there, and if not, look in the old location?

**Comment by srgvg** [comment]
I might misunderstand you, but what you describe is what happens now. If a scripts dir exists in the role (with the referenced scriptfile), it will use that; if it doesn't (as would happen for people using this before this patch) it would just use the file referenced from a path outside the playbook. Whether just the script file doesn't exist, or the scripts/ dir doesn't exists, doesn't matter in  that.

Also: when using roles, one typically refences just the file, with no path; 
without roles, one would most often put files in templates/ files/ and scripts/ dit beneath the playbook (at least that's what I do), and refence that explicit path in the (role) task. 
So both cases typically need a different path, and would most often not even conflict.

(Also, see the last example in my pastebin testing output.)

**Comment by srgvg** [comment]
(this should be the exact same behaviour as for files/ and templates/, the code is almost a copy paste from there)

**Comment by mpdehaan** [comment]
Ok, so you're saying it _will_ still work from outside the scripts/ dir,
like normal.    That's good then, my fault.  Haven't had time to test yet.

I am inclined to believe it should be "files" though as indicated in the
other ticket.   I think that's fine as the "copy" directory doesn't have a
directory named "copy".

**Comment by srgvg** [comment]
Yes, that's what the path dwim relative function does, AFAICS; 
same as or copy and template resource.
I'll update the PR to use the files/ dir.

**Comment by srgvg** [comment]
updated testing: http://sprunge.us/jaei

**Comment by mpdehaan** [comment]
Looks good, merged, thanks!  Will push updated docs shortly!

**Pull request merged**
