### PR TITLE
Backport azure_rm_image Tag fix for 2.5 (#38131)

### PR DESCRIPTION
**Pull request by maxamillion**
(cherry picked from commit 1c00a14c31827c2777015d49ae70700c06907cdb)

### CODE REVIEW

**Comment by sivel** [comment]
I think you also need a changelog entry added in `changelog/fragments` for this fix.

**Comment by yuwzho** [comment]
Please also include this one: 454096ca59fdaddcf9e5ac850bb20f6b91837c3a , for fixing the same issue.

**Comment by maxamillion** [comment]
@yuwzho included, thank you!

**Comment by yuwzho** [comment]
shipit

**Pull request merged**
