### PR TITLE
Environment file feature

### PR DESCRIPTION
**Pull request by yrobla**
##### SUMMARY
Adds a new keyword for the playbooks, named environment_file. It allows to specify a path to a local file, and sources the vars, propagating into the environment dictionary.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ansible core

##### ANSIBLE VERSION
2.6

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure due to traceback in the integration tests:

```
2018-03-06 18:54:37 Traceback (most recent call last):
2018-03-06 18:54:37   File "/root/ansible/bin/ansible-playbook", line 118, in <module>
2018-03-06 18:54:37     exit_code = cli.run()
2018-03-06 18:54:37   File "/root/ansible/lib/ansible/cli/playbook.py", line 122, in run
2018-03-06 18:54:37     results = pbex.run()
2018-03-06 18:54:37   File "/root/ansible/lib/ansible/executor/playbook_executor.py", line 159, in run
2018-03-06 18:54:37     result = self._tqm.run(play=play)
2018-03-06 18:54:37   File "/root/ansible/lib/ansible/executor/task_queue_manager.py", line 290, in run
2018-03-06 18:54:37     play_return = strategy.run(iterator, play_context)
2018-03-06 18:54:37   File "/root/ansible/lib/ansible/plugins/strategy/linear.py", line 248, in run
2018-03-06 18:54:37     task_vars = self._variable_manager.get_vars(play=iterator._play, host=host, task=task)
2018-03-06 18:54:37   File "/root/ansible/lib/ansible/vars/manager.py", line 420, in get_vars
2018-03-06 18:54:37     all_vars['environment'][idx].update(environment_file_vars)
2018-03-06 18:54:37 AttributeError: 'AnsibleUnicode' object has no attribute 'update'
```

**Comment by acozine** [comment]
@yrobla if you'd like some reviews on this PR, join the [monthly big PR review](https://github.com/ansible/community/issues/407) on freenode IRC tomorrow.

**Comment by samccann** [comment]
@bcoca @sivel - this PR has lingered for quite some time. I can't tell if it is worth someone internally taking it over or if it should be closed?

**Comment by sivel** [comment]
@samccann From my perspective, having looked at this issue for the first time, I'm not sure we are willing to accept this, regardless of the current conflict state.

I'm not necessarily against such a feature, but I'm not necessarily a fan of the implementation.  I'm not positive on the best way forward with such a feature, but I'd like to see us not rely on our own env file parser.

If anything, I believe the proper way forward would be to require a YAML file representing a dictionary/hash, but if we are going that far, the feature itself is probably not necessary.  If a file is necessary, it might make more sense for the user to place a profile/rc file on the remote system, that will be sourced by non-interactive logins.

As such, I am going to close this for now.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible-devel on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

**Pull request closed without merging**
