### PR TITLE
Module for swdepot (HP-UX package manager)

### PR DESCRIPTION
**Pull request by melodous**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you give me some pointers to how widely used this package manager is?

Apologies for not being up to speed on HPUX!

**Comment by melodous** [comment]
Swdepot is the official and core package manager on HP-UX, all software packaged by HP is distributed in this format, the installation or upgrade process is made this software. 

It is like rpm on redhat based distributions or dpkg on debian based distributions. At the same time it have functionalities to manage local or remote repositories but the currently implementation in this PR is focus on local operations, it could install from remote repositories, but not to manage software repositories.

Don't worry about the HP-UX knowledge, sadly for my future only few have it ;)

**Comment by mpdehaan** [comment]
There are some things here I would like to fix prior to further review

First off this style:

```
+    module = AnsibleModule(
+            argument_spec = dict(
+               name = dict(aliases=['pkg'],required=True),
+                state = dict(choices=['present','absent','latest'],required=True),
+                depot = dict(default=None,requied=False)
+                ),
+            supports_check_mode=True
+            )
```

Parens should align with the expression they close above, and equal signs should line up.

Further, sometimes there are spaces inside parens, don't do this:

```
foo( x,y )
```

Instead do this:

```
 foo(x, y)
```

The same applies for parens in if statements.

The copyright statements should be (C) you, but based on the work from people above.

Let me know when you get that sorted and we'll review the rest of it.

Over all looks simple and shouldn't be too many problems in merging.

Thanks!

**Comment by melodous** [comment]
Michael, I already made the changes you suggested me.

Regards

**Comment by jimi-c** [comment]
@melodous It appears that this will not merge cleanly. Could you please rebase against devel and resubmit? Thanks!

**Comment by jimi-c** [comment]
I also meant to ask, could you submit the HP-UX facts change as a separate PR? Unrelated functionality should be separate PR's.

**Pull request closed without merging**
