### PR TITLE
Add a lookup plugin to retrieve latest tagged release version from a GitHub repository

### PR DESCRIPTION
**Pull request by artis3n**
##### SUMMARY
A convenience lookup plugin to get the latest tagged release version of a Github repo. If the reviewers agree on getting this into this repo I will add the ability to use a github token in an env var to look up private repo versions.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
github_version

###### Tests
I was unable to get local unit tests running following the [unit test doc instructions](https://docs.ansible.com/ansible/devel/dev_guide/testing_units.html#running-tests). Due to this I did not write unit tests for this plugin, which I would like to do before this is accepted. I did manually tests all of the cases I have commented in the unit test file, and it's working great.

For example, running `ansible-test units --python 3.6 apt` returns an error that `pytest` is not available in my venv. I can add that easily enough, but that should probably be installed as part of some local dev setup step that I must be missing.

###### Usage
You can accomplish this lookup plugin's behavior through 2 different methods in tasks:

1-task option:

```yaml
- name: Get the latest version
  shell: |
    set -o pipefail
    curl -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/ansible/ansible/releases/latest | jq .tag_name
  args:
    executable: /bin/bash
  changed_when: false
  register: ansible_version
```

2-task option, not using `shell`:

```yaml
- name: Ansible | Get latest release
  uri:
    url: https://api.github.com/repos/ansible/ansible/releases/latest
    headers:
      Accept: application/vnd.github.v3+json
    body_format: json
    return_content: yes
  register: terraform_release

- name: Ansible | Set version
  set_fact:
    # This removes the 'v' from the tag: 'v1.1.0' -> '1.1.0'
    ansible_version: "{{ terraform_release.json.tag_name[1:] }}"
```

Now you can simply use:

```yaml

- name: Ansible | Get latest release
  set_fact:
    ansible_version: "{{ lookup('github_version', 'ansible/ansible')[1:] }}"
```

### CODE REVIEW

**Comment by artis3n** [comment]
> `test/units/plugins/lookup/github_version.py:0:0: missing: __metaclass__ = type`

`__metaclass__ = type` exists in the file so not sure why this check failed.

**Comment by artis3n** [comment]
> The test `ansible-test sanity --test metaclass-boilerplate` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/metaclass-boilerplate.html)] failed with 1 error:
> 
> ```
> test/units/plugins/lookup/github_version.py:0:0: missing: __metaclass__ = type
> ```
> 
> [click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

https://github.com/ansible/ansible/pull/63727/files#diff-0afb2076d5281ee7f8b017e20eef68f6R6

https://media.giphy.com/media/Ysce790SgjJK0/giphy.gif

**Comment by sivel** [comment]
Hi!

Thank you very much for your submission to Ansible. It sincerely means a lot to us that you've taken the time to contribute.

Per recent decisions at AnsibleFest Atlanta 2019, we are no longer accepting new one off modules or plugins going forward.

However, we recommend looking into providing this functionality through Ansible Galaxy via Ansible Collections. You can find more information about collections at https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html.

Thank you once again for this and your interest in Ansible!

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by artis3n** [comment]
Hi @sivel, no problem. That docs link 404s and I don't see anything with "collections" in its name searching the latest public docs. Are collections new / upcoming?

**Comment by sivel** [comment]
My apologies, someone moved the page and I haven't updated the bookmark:

https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html

**Comment by artis3n** [comment]
If anyone comes across this and wants to use the lookup plugin, it is at https://galaxy.ansible.com/artis3n/github_version

**Pull request closed without merging**
