### PR TITLE
Assemble

### PR DESCRIPTION
**Pull request by sfromm**
Issue #80.  Assemble module that assembles a file from a directory of fragments.  Please let me know if you have any comments/suggestions.  Thanks!

### CODE REVIEW

**Comment by mpdehaan** [comment]
I was thinking this would be done with just a module (Puppet fragments style) actually.  The use case is that various modules would create templates in a conf.d style directory and then just cat them together in the end.

This way if the assemble module was run in a particular include it could only make use of the variables in that PARTICULAR include.

Ex:

include setup_app_one.yml port=1000
include setup_app_two.yml port=1234
include setup_iptables.yml

In the above example, can we use the fragment files built from A and B, to see both ports?

**Comment by sfromm** [comment]
Just to make sure I understand correctly, the files to concatenate would exist on the target host, yes?  And those files would have already been templated before assemble is run to concatenate them?

If so, yes I can update the changes to work like that.

**Comment by mpdehaan** [comment]
yes and yes.   It is just basically "cat *" for everything in a directory after sorting the filenames.

src=dirname dest=filename

We would need the runner.py code to chain a call to "assemble" into the "file" module, just in the minimal way that copy and file do that already.

(I need to refactor that eventually as that is starting to become a pattern)

**Comment by sfromm** [comment]
On Fri, May 11, 2012 at 4:38 PM, Michael DeHaan <
reply@reply.github.com

> wrote:
> 
> yes and yes.   It is just basically "cat *" for everything in a directory
> after sorting the filenames.
> 
> src=dirname dest=filename
> 
> We would need the runner.py code to chain a call to "assemble" into the
> "file" module, just in the minimal way that copy and file do that already.
> 
> (I need to refactor that eventually as that is starting to become a
> pattern)

Okay, I have a good chunk of the assemble module written.  I'll remove the
other bits and test.  I'll send a pull-request when it is ready.

sf

**Comment by mpdehaan** [comment]
thanks, apologies on confusion, though it will be definitely good to have those same capabilities!   Much appreciated.

**Pull request closed without merging**
