### PR TITLE
mysql_replication: add master_use_gtid parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add MariadDB GTID support to mysql_replication module
rewrites #20630

Also the CI tests were updated to use later version of MariaDB

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```mysql_replication```

### CODE REVIEW

**Comment by Andersson007** [comment]
@bmalynovytch , @dagwieers , @bobuss, @AndiDog , @gundalow , @wsellars-bw
i'd like to complete this (because i love MariaDB a bit more than MySQL:).
However, I'm a hardcore devotee of ci tests, so, i beleive that we should implement this (for MariaDB in part of mysql_replication) before merging this.
If somebody has a MariaDB cluster for testing, could you please test this.
I need time to implement ci tests.
I wonder if there is a possibility to deploy two servers listening two different ports on the same host to configure master-slave replication (in PostgreSQL it is possible)...

**Comment by bmalynovytch** [comment]
@Andersson007 it is possible and not that hard to do.
You just need to point to different config files when starting manually the daemon.

I intensively work with multi-master clusters and rarely with master-slave clusters so we require me to setup a test env, which I can't for now 🙁

**Comment by Andersson007** [comment]
@bmanojlovic cool, thank you!
manual testing would be good if i can't configure the replication on one host but i'll try to do it

**Comment by bmanojlovic** [comment]
you are attributing wrong person, @bmalynovytch is correct nick handle :)

**Comment by Andersson007** [comment]
@bmanojlovic sorry :) thank you for pointing this out !

**Comment by Andersson007** [comment]
i made basic CI tests https://github.com/ansible/ansible/pull/62648. It must be merged, then i can tests this PR using them

**Comment by Andersson007** [comment]
@bmalynovytch @gundalow , done, with CI now
if it's ok, please, approve and merge

ready_for_review

**Comment by bmalynovytch** [comment]
@Andersson007 Thx for your great work !
I need to dive deep in it and might have a couple of suggestions but don't want to do them before I'm sure they are relevant.
I'll try to give it a look this week.

**Comment by Andersson007** [comment]
@bmalynovytch , ok, thanks, i'll be waiting for your feedback!

**Comment by Andersson007** [comment]
@bmalynovytch , would be cool to have your review asap because of 56767. I changed basic ci tests a bit, so, would be cool to see this merged before i ping the author to complete his pr and add integration tests for that (it would be cool to avoid fixing merge conflicts, etc.)

**Comment by bmalynovytch** [comment]
"In the week" is the best I can do. Could also be "within October" 😉

**Comment by Andersson007** [comment]
@bmalynovytch FYI i changed the basic setup tests which restrict me by another pr https://github.com/ansible/ansible/pull/62993, so you don't need to rush and review this pr at night  (i certainly know you do) :)

**Comment by Andersson007** [comment]
ready_for_review

**Review by felixfontein — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@felixfontein thanks for reviewing!

**Review by bmalynovytch — APPROVED** [review]

**Comment by bmalynovytch** [comment]
Nice job @Andersson007 ! 👍 

shipit

**Comment by Andersson007** [comment]
@bmalynovytch thank you!

**Comment by Andersson007** [comment]
@amenonsen , thanks for merging

**Pull request merged**
