### PR TITLE
Improve apt_repository and supervisorctl

### PR DESCRIPTION
**Pull request by mattupstate**

### CODE REVIEW

**Comment by mpdehaan** [comment]
In queue for review.... 

Please use one branch/pull request per module please in the future so they can be approved/reviewed seperately.

**Comment by mattupstate** [comment]
Figured since I contributed both it was ok. Noted for future, though.

**Comment by mpdehaan** [comment]
merged, thanks

**Comment by mpdehaan** [comment]
FYI -- I just merged a conflict in the supervisorctl module.  As I don't use this one, and you do, you may want to test it and make sure it's still ok.

Should be.   Thanks!

**Pull request merged**
