### PR TITLE
Add how to run unit test link in testing_units_modules doc

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
`testing_units_modules` doc doesn't give any information about how to run unit tests, this PR adds a link to `testing_units` doc which explains how to run tests.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/dev_guide/testing_units_modules.rst

### CODE REVIEW

**Comment by acozine** [comment]
Thanks for the contribution @aminvakil. I like the new paragraph, but I think there might be a better place for it - this page is about adding unit tests to your code. What would you think of putting this added content [here](https://docs.ansible.com/ansible/devel/dev_guide/testing.html) instead?

**Comment by aminvakil** [comment]
@acozine Could you be more specific on where to add it? I was thinking under **Testing the Pull Request** section, but there is already instructions on how to run sanity tests in **Testing within GitHub & Shippable**, so I'm not sure.

**Comment by aminvakil** [comment]
@acozine I moved it under **Testing the Pull Request** and added `sanity` and `integration` tests as well, could you please take another look at this?

**Comment by aminvakil** [comment]
ready_for_review

**Comment by acozine** [comment]
Thanks @aminvakil!

**Pull request merged**
