### PR TITLE
Add module to search and get ldap entries

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
##### SUMMARY
Added a module to search and get LDAP entries

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
`lib/ansible/modules/net_tools/ldap/ldap_get.py`

##### ANSIBLE VERSION
```
ansible 2.4.0 (feature/add_module/ldap_get de0bd50d80) last updated 2017/07/23 00:03:53 (GMT +200)
  config file = None
  configured module search path = ['/home/mouxon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mouxon/Bureau/ansible-ladp/ansible/lib/ansible
  executable location = /home/mouxon/Bureau/ansible-ladp/ansible/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

##### ADDITIONAL INFORMATION
This is used to search for LDAP entries and get them with their attributes
```
- name: Look for the first admin user
  ldap_get:
    search_base: dc=example,dc=com
    search_filter: (user_type=admin)
    first_only: true
  register: ldap_result
```

### CODE REVIEW

**Comment by jtyr** [comment]
Wouldn't it be better to have this functionality as a lookup plugin?

**Comment by GuillaumeSmaha** [comment]
Why not. I didn't think to create it as a lookup plugin.
I can convert it.

**Comment by GuillaumeSmaha** [comment]
Should I create a new PR for this lookup plugin ?

**Comment by jtyr** [comment]
Create a new PR and keep this one open for later reference.

**Comment by GuillaumeSmaha** [comment]
@jtyr I created a new PR https://github.com/ansible/ansible/pull/27358 for the ldap lookup plugin but this PR is still useful because lookup plugins are not execute remote side. So, if my ldap server only listen at loclahost, I couldn't connect to it with a lookup plugin

**Comment by GuillaumeSmaha** [comment]
@jtyr Any news for this PR ?

**Pull request closed without merging**
