### PR TITLE
with_items maps back into a single module call for authorized_key module

### PR DESCRIPTION
**Pull request by kustodian**
This pull request is needed for the `clear_keys` parameter pull request for the `authorized_key` module https://github.com/ansible/ansible-modules-core/pull/42

### CODE REVIEW

**Comment by kustodian** [comment]
We should probably think about making this possible for any module by passing a variable or something, so that future modules don't need to modify core to be able to receive `with_items` elements as a map.

**Comment by jimi-c** [comment]
@kustodian that has been discussed, and we'd be open to reviewing that for sure. Thanks!

**Comment by kustodian** [comment]
That is great news. If you are up for it, I would be interested to make a pull request.

**Comment by BitOne** [comment]
:+1: 
Very much needed for security reason (guy leaving your company, you want to make sure that the present keys are the one valid).

Thanks !

**Comment by amenonsen** [comment]
I think this should be closed now. The PR that depended on it was closed months ago.

**Comment by kustodian** [comment]
Closing this, since it's not needed anymore.

**Pull request closed without merging**
