### PR TITLE
Add $team_mysql

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
A first step to a MySQL Working Group.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
mysql

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Comment by timorunge** [comment]
I think modules which are depending on the MySQL modules should also be included in `BOTMETA.yml`. Here is a quick list of missing files and directories:
- `lib/ansible/modules/database/proxysql/`
- `lib/ansible/utils/module_docs_fragments/proxysql.py`

**Comment by dagwieers** [comment]
@timorunge So are you saying that the MySQL Working Group should also be reviewing and testing ProxySQL ? cc @gundalow

**Comment by timorunge** [comment]
@dagwieers - basically I'm just saying that - in a case like that - the work group should ensure that dependencies are met properly.

**Comment by dagwieers** [comment]
@timorunge Now I see what you mean, you didn't detail that the ProxySQL modules actually use the MySQL module_utils. And without ProxySQL integration tests, that could be problematic. I guess we need to add the ProxySQL modules to the MySQL Working Group.

**Comment by dagwieers** [comment]
@timorunge Thanks for reporting! &rarr; https://github.com/ansible/ansible/pull/52054 :-)

**Comment by timorunge** [comment]
@dagwieers Great.
Yeah, it's more a general approach that it should always be ensured that dependencies are fully covered with (integration) tests. In this case it's just ProxySQL (I was looking around at the core to ensure the same).

**Pull request merged**
