### PR TITLE
Add the option "target" as parameter "appdir" for the command

### PR DESCRIPTION
**Pull request by robertobermejo**
Add path for #8302

### CODE REVIEW

**Comment by mpdehaan** [comment]
Please add the "version_added: '1.7" attribute as this is used to generate the documentation.

Thanks!

**Comment by robertobermejo** [comment]
Updated to the new version

**Comment by dixhuit** [comment]
+1 for this.

**Comment by amenonsen** [comment]
@robertobermejo could you please rebase and submit this to the `ansible-modules-extras` repository?

This PR (against the core repository) should be closed.

**Comment by gregdek** [comment]
Thanks for the PR @robertobermejo. As mentioned above, this should be refiled against the extras repo, so closing this one.

**Pull request closed without merging**
