### PR TITLE
New module: Add a module to support Zabbit proxies. (monitoring/zabbix_proxy) 

### PR DESCRIPTION
**Pull request by yurilaaziz**
##### SUMMARY
Add module to support zabbix proxies 

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
Zabbix_proxy

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

### CODE REVIEW

**Comment by yurilaaziz** [comment]
Hello Could someone check this module please 
cc 
@NickatEpic @andsens @aps-sids @bhcopeland @bpennypacker @brian-brazil @bwhaley @ccollicutt @dstoflet @eikef @ethanculler @hkariti @ivanvanderbyl @kavu @mcodd @n0ts @nate-kingsley @nerzhul @sedward @skornehl @stympy @suprememoocow @tbielawa @woz5999

**Comment by nerzhul** [comment]
code style and features seems okay but i don't use zabbix

**Comment by eikef** [comment]
I'm sorry I didn't get a chance to look at this earlier.

This looks good so far; I've tested it locally. I've revised the documentation some and sent you a pull request to that effect. Once that is in this should be good to merge (though the tls_*-additions in the other modules need to be ported afterwards, but that can be done then).

**Comment by eikef** [comment]
I would unfortunately vote to close this in favor of https://github.com/ansible/ansible/pull/24657 which implements the same functionality, but better (i.e. updates being possible instead of just additions/deletions, and tls functionality already in there).

I'm sorry it has taken this long to get to this PR.

**Comment by eikef** [comment]
close_me

**Comment by eikef** [comment]
close_me

**Comment by resmo** [comment]
PR #24657 was merged in favor, closing.

**Pull request closed without merging**
