### PR TITLE
[backport-2.16] Fix plugin set option (#82300)

### PR DESCRIPTION
**Pull request by bcoca**
* plugin config, ensure set_option correctly casts

  until now we relied on plugin author getting the right type, now the config system itself will process as it would for set_options

(cherry picked from commit 4479c9df13aedec52f4971fb2a5a9c3c9fd92ba1)

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by bcoca** [comment]
it should not, but reboot does many weird things, i'll take a look

**Comment by bcoca** [comment]
soo the reboot test is looking for 'connection_timeout' which is not 'yet' a property of the ssh connection plugin. But that is not a change i introduce here .. guessing tests got pushed back w/o running?!?

**Comment by bcoca** [comment]
related #82526

**Comment by bcoca** [comment]
depends on #82526

**Comment by mattclay** [comment]
This shouldn't be backported, as it's a breaking change, see https://github.com/ansible/ansible/pull/82300#issuecomment-1901153199 for additional details.

**Pull request closed without merging**
