### PR TITLE
vultr: Fix E324 for vultr modules.

### PR DESCRIPTION
**Pull request by Spredzy**
##### SUMMARY

Fix E324 for vultr modules.

##### ISSUE TYPE

 - N/A

##### COMPONENT NAME
 
 - vultr

##### ANSIBLE VERSION

 - devel

##### ADDITIONAL INFORMATION

 - N/A

### CODE REVIEW

**Comment by Spredzy** [comment]
cc @resmo

**Comment by resmo** [comment]
The thing is that we can specify these settings in the vultr.ini (see https://github.com/ansible/ansible/pull/42464/files#diff-d8f2f71b9df96f2b223b6144a01aae65R55) but allow them to be overwritten by the params. Defaulting them in params, disables the feature to set them in vultr.ini. 

The better fix is to update the docs by removing the defaults and make a document note what the "fallback" value is, similar I did for cloudstack https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/module_docs_fragments/cloudstack.py#L38

**Comment by resmo** [comment]
needs_revision

**Review by achinthagunasekara — APPROVED** [review]

**Comment by resmo** [comment]
@achinthagunasekara why did you approve it?

**Comment by Spredzy** [comment]
@resmo updated based on the initial comment. Let me know if that is not what you had in mind.

**Review by resmo — APPROVED** [review]
LGTM

**Pull request merged**
