### PR TITLE
Add support for vrf_name in ios_ntp

### PR DESCRIPTION
**Pull request by miuvlad**
##### SUMMARY
Add vrf_name argument for ios_ntp module.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ios_ntp

##### ADDITIONAL INFORMATION
Adds support for VRF aware NTP servers on ios. A NTP server is now identified by a combination of (vrf, IP).

### CODE REVIEW

**Comment by justjais** [comment]
@miuvlad Thanks for raising the PR, can you plz add tests in `ios_ntp` integration tests as well.

**Review by justjais — CHANGES_REQUESTED** [review]
integration tests for PR is required

**Comment by mibotiaf** [comment]
Team good morning.
Is the VRF option ready to use ?
Thanks !!

**Comment by Akasurde** [comment]
Hi @miuvlad, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/cisco.ios<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
