### PR TITLE
Rename ali_instance_facts -> ali_instance_info

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Continues #56822. The modules do not return `ansible_facts`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ali_instance_facts

### CODE REVIEW

**Comment by felixfontein** [comment]
FYI: this PR includes no new module, it renames a module.

**Review by acozine — APPROVED** [review]
Docs changes look good.

**Review by acozine — APPROVED** [review]
Docs changes look good.

Heh, I'm starting to repeat myself. Good thing it's Friday.

**Comment by felixfontein** [comment]
CC @xiaozhu36 as author of ali_instance_info module.

**Review by Andersson007 — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
Rebased to remove the conflict in the porting guide. Will merge once CI passes.

**Comment by felixfontein** [comment]
@acozine @Andersson007 thanks a lot for reviewing this!

**Pull request merged**
