### PR TITLE
append AWS region to test instance file

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Append the AWS region used in Ansible test when dealing with AWS or Azure hosts. This makes each ansible-test instance unique per region specified.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
ansible-test

##### ANSIBLE VERSION
```paste below
devel
```

### CODE REVIEW

**Review by mattclay — APPROVED** [review]
Looks good. One thing to note though is that since this changes the path of the instance files, switching between older and newer versions of ansible-test (or between branches) will result in them using different instance files.

**Comment by jborean93** [comment]
@mattclay do we want to backport this to unify that behaviour?

**Comment by mattclay** [comment]
Yes, that would be a good idea. That way the HEAD of each supported branch will at least be consistent. It won't help with bisecting, but there's not much we can do about that.

**Comment by jborean93** [comment]
Backport PRs
stable-2.5 https://github.com/ansible/ansible/pull/45884
stable-2.6 https://github.com/ansible/ansible/pull/45885
stable-2.7 https://github.com/ansible/ansible/pull/45886

**Pull request merged**
