### PR TITLE
Update azure_rm_cosmosdbaccount_info.py

### PR DESCRIPTION
**Pull request by azagramac**
#### SUMMARY
Edit name, module "azure_rm_cosmosdbaccount_info"

##### ISSUE TYPE
Error syntax in name module "azure_rm_cosmosdbaccount_info"

##### COMPONENT NAME
"azure_rm_cosmosdbaccount_info"

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Review by gavinfish — APPROVED** [review]
shipit

**Comment by Fred-sun** [comment]
Ping to merge!

**Comment by Fred-sun** [comment]
@AzagraMac Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by Fred-sun** [comment]
@AzagraMac I am going to create a PR in the ansible_collections_azure
 to synchronize your changes. The link is --https://github.com/ansible-collections/azure/pull/82. Thank you very much!

**Pull request closed without merging**
