### PR TITLE
Feature/win stat extra info

### PR DESCRIPTION
**Pull request by jborean93**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
win_stat
powershell.ps1 (module_utils)

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
Changed win_stat module to return more info on the item at a path like
* Revert to returning md5 in the md5 field
* Added more features like checksum algorithm to match stat module
* Return whether the path is a link and the link target
* Return whether the path is shared and the share name
* Lots other

This also changes the Get-FileChecksum method to return different checksums based on an algorithm. The default is still set to SHA1 for compatibility reasons.

This is a PR after the repo merge for 
https://github.com/ansible/ansible-modules-core/pull/5471
https://github.com/ansible/ansible/pull/18339
https://github.com/ansible/ansible/pull/18374

### CODE REVIEW

**Review by nitzmahone — APPROVED** [review]
I'll merge as-is, but I'm still waffling on nuking the PS4+ codepath in Get-FileChecksum- it seems superfluous, since we've no plans to drop PS3 support anytime soon- why not just use the same thing everywhere? I'd be surprised if the PS-native version was noticeably quicker...

**Comment by nitzmahone** [comment]
Thanks @jborean93 !

**Comment by jborean93** [comment]
Thanks for the merge. My thoughts with the version split is when we start looking at nano server where .net stuff has been culled having the native power shell implementation would be useful and it is ultimately easier to remove support for older versions where necessary way in the future.

Happy to go otherwise that's just my thoughts.

**Comment by nitzmahone** [comment]
@jborean93 In this particular case (for nano/.net core), they just changed name of the hash providers- I have the same issue with the checksumming in winrm.py's put_file impl (throwaway-prototyped a working one against nano), but using the native cmdlet instead of conditional names might make more sense... 

I'm doing some testing of the new exec wrapper stuff against nano as I'm building it, just to make sure we don't paint ourselves into a corner. Pretty sure we won't be at a state to light up CI and "official support" (at least transport and some subset of core modules) until 2.4.

**Pull request merged**
