### PR TITLE
Prevent hostnames being interpreted as arguments in hostname module

### LINKED ISSUE #81741: hostname module not fully protected from bad hostnames
### Summary

When provisioning a Centos machine, we accidentally used a bad hostname (due to poor input sanitisation) `-femdi-vm` and this ended up being passed to the command `hostnamectl set-hostname -femdi-vm`, which interpreted it as an invalid flag. 

Having failed with some injection attempts due to the way commands are called, we don't believe this has a security impact.

This was tested on ansible 2.8 and 2.9, but inspecting the current codebase makes us think it will still apply.

In https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/hostname.py#L320 the hostname is just put at the end of the command as is, and thus something with a leading dash can be interpreted as an option.  There are several other commands nearby that would probably have the same issue. It may also affect other non-hostnamectl methods.

A simple fix might be to add a `--` to the command prior to appending the hostname, in order to prevent further option parsing (e.g. so it runs `hostnamectl set-hostname -- -femdi-vm` instead).  We've not made a (simple) pull request implementing this yet, but can do if it seems like the right way to go.  You probably have a better idea of the scope!

### Issue Type

Bug Report

### Component Name

hostname

### Ansible Version

```console
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mgrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.8 (main, Nov 14 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-3)]
```

### Configuration

```console
$ ansible-config dump --only-changed
$
```

### OS / Environment

Centos 7, Fedora 38, but probably generally applicable to anything that uses systemd / hostnamectl.

### Steps to Reproduce

This playbook simply sets a bad hostname

```yaml (paste below)
- name: Hostname demo
  hosts: localhost

  tasks:
  - name: set --> FQDN
    hostname: 
     name: "-femdi-vm"

```
One can run it with `ansible-playbook -i localhost -u USERID -k hostname.yml`

### Expected Results

Either some variant (pretty) of the hostname being set to "-femdi-vm" or being told the hostname is invalid.

### Actual Results

```console
SSH password: hunter2
[WARNING]: Unable to parse /home/USER/localhost as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Hostname demo] *********************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************
ok: [localhost]

TASK [set --> FQDN] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=/usr/bin/hostnamectl: invalid option -- 'f'\n"}

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by mikeggrant-eumetsat**
##### SUMMARY

Adds a double-dash `--` to the hostname changing commands to prevent (nominally invalid) hostnames with a leading dash from being interpreted as arguments.

Fixes #81741 

##### TESTING AND OPTIONAL FURTHER WORK

Tested on Fedora 38 (SystemdStrategy) and worked there (see below).

There's also a second commit for FreeBSD and OpenBSD to do the same change, but I couldn't test it.  The source code for both uses getopt though, so it should support the double-dash:
 - https://github.com/openbsd/src/blob/master/bin/hostname/hostname.c
 - https://github.com/freebsd/freebsd-src/blob/main/bin/hostname/hostname.c

If someone else is able to test that, it would be very nice!

I also looked at Solaris, which calls `hostname` but wasn't able to find source code to confirm that it handles a double dash, nor do I have access to a machine, and thus haven't patched it.

Darwin seems to use getopt (https://opensource.apple.com/source/configd/configd-596.15/scutil.tproj/scutil.c.auto.html) but the syntax is sufficiently different that I didn't want to try an untested patch, and I have no access to a Mac.

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

Prior to the patch (showing that -femdi was interpreted as an option:
```
$ hostnamectl set-hostname prior_to_test
$ ./hacking/test-module.py  -m lib/ansible/modules/hostname.py  -a '{"name": "-femdi"}'
...
RAW OUTPUT

{"failed": true, "msg": "Command failed rc=1, out=, err=/bin/hostnamectl: invalid option -- 'f'\n", "invocation": {"module_args": {"name": "-femdi", "use": null}}}
...
$ hostnamectl
     Static hostname: priortotest
     Pretty hostname: prior_to_test
...
    Operating System: Fedora Linux 38 (Thirty Eight)  ```
```

After the patch:
```
$ hostnamectl set-hostname prior_to_test
$ ./hacking/test-module.py  -m lib/ansible/modules/hostname.py  -a '{"name": "-femdi"}'
...
RAW OUTPUT

{"failed": true, "msg": "Command failed rc=1, out=, err=Hint: static hostname is already set, so the specified transient hostname will not be used.\nCould not set transient hostname: Invalid hostname '-femdi'\n", "invocation": {"module_args": {"name": "-femdi", "use": null}}}
...

$ hostnamectl
     Static hostname: femdi
     Pretty hostname: -femdi
..
    Operating System: Fedora Linux 38 (Thirty Eight)  
```
Note that there is still a partial failure (it returns 0 but hints that the transient name won't be set because it's already statically set to this name - there's a comment in the code on line 341 about this being due to NetworkManager getting unhappy). However, this message is the correct behaviour now, as it shows the hostname is no longer being parsed as an option!

### CODE REVIEW

**Comment by bcoca** [comment]
needs changelog and tests,it (passes existing ones,so  just add one with a problematic host, that this PR solves, to avoid regressions.

**Comment by Akasurde** [comment]
@mikeggrant-eumetsat 
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

also, test cases for this change.

**Comment by mikeggrant-eumetsat** [comment]
Thanks, half done on this, but sidelined by a work deadline - will get back to it this week!

**Comment by mikeggrant-eumetsat** [comment]
Here's a try at a regression test - if this doesn't seem like the right approach, I'd appreciate a hint in the direction to go :)

I see one CI job failed, which seems to be due to not getting the msg variable in the result dict (https://dev.azure.com/ansible/fc938e26-c865-4d62-b731-a77bbe8bf5c4/_apis/build/builds/95272/logs/842).  I'm not sure why this would have failed and the other FreeBSD 13.2 CIs succeeded.  Is it ok to push some commits to this PR to test further, or is there a way to run these tests independently?

**Comment by mikeggrant-eumetsat** [comment]
I installed a FreeBSD 13 VM and updated it to 13.2, and was able to reproduce the problem - it actually succeeds in changing the hostname (to something with a dash in it, but that's ok, because it's not being interpreted as a flag), so there is no "msg" variable in the command_result dict.  The possible cases are:

```
    # it can fail with an invalid option warning => test should fail (interpreted as flag)
    # it can fail (or partially fail) with a warning that dashes are bad characters / hostname is invalid => test should pass (not interpreted as flag)
    #  - in both cases above, the warning will be in the command_result.msg variable.  The hostname may or may not change
    
    # it can succeed (maybe changing the hostname to something weird) => test should pass (not interpreted as flag)
    #  - in this case, there will be no command_result.msg variable
```
I'm trying to figure out how to specify this in such a way that non-existence of msg in some cases doesn't kill it, while still allowing checking the content of msg when it does exist.

**Comment by mikeggrant-eumetsat** [comment]
That seems ok..

## Success examples (after patch)

### Ubuntu 22 (SystemdStrategy)
```
TASK [hostname : Ensure hostname is not interpreted as a flag] *****************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=Hint: static hostname is already set, so the specified transient hostname will not be used.\nCould not
 set transient hostname: Invalid hostname '-flaglike-hostname'\n"}
                                                                                               
TASK [hostname : assert] *******************************************************
ok: [testhost] => {
    "changed": false,                                                                          
    "msg": "All assertions passed"
}
```

### FreeBSD 13.2 (FreeBSDStrategy)
```
TASK [hostname : Ensure hostname is not interpreted as a flag] ***************** 
changed: [testhost] => {"ansible_facts": {"ansible_domain": "", "ansible_fqdn": "-flaglike-hostname", "ansible_hostname": "-flaglike-hostname", "ansible_nodename": "-flaglike-hostname"}, "changed": true, "name": "-flaglike-hostname"} 
 
(carries on)
```


## Regression examples (using current devel with unpatched code, but with regression test)

### Ubuntu 22 (SystemdStrategy)
```
TASK [hostname : Ensure hostname is not interpreted as a flag] *****************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=/usr/bin/hostnamectl: invalid option -- 'f'\n"}

TASK [hostname : assert] *******************************************************
fatal: [testhost]: FAILED! => {
    "assertion": "'hostnamectl: invalid option' not in command_result.msg\n",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

### FreeBSD 13.2 (FreeBSDStrategy)

```
TASK [hostname : Ensure hostname is not interpreted as a flag] *****************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=hostname: illegal option -- l\nusage: hostname [-f] [-s | -d] [name-of-host]\n"}

TASK [hostname : assert] *******************************************************
fatal: [testhost]: FAILED! => {
    "assertion": "'illegal option' not in command_result.msg\n",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

**Comment by vbotka** [comment]
> ### FreeBSD 13.2 (FreeBSDStrategy)
> ```
> TASK [hostname : Ensure hostname is not interpreted as a flag] *****************
> fatal: [testhost]: FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=hostname: illegal option -- l\nusage: hostname [-f] [-s | -d] [name-of-host]\n"}

**FreeBSD rc scripts are not able to set '-.*' hostnames**

It is possible to set the hostname for the current session

```bash
# hostname -- -fendi
# hostname
-fendi
```
However, to make it permanent, configuration in /etc/rc.conf is needed 

```bash
# grep hostname /etc/rc.conf
hostname="-fendi"
```
Unfortunately, the rc script is not able to set such a hostname

```bash
# /etc/rc.d/hostname restart
Setting hostname: -fendihostname: illegal option -- e
usage: hostname [-f] [-s | -d] [name-of-host]
.
```
This makes the '-.*' hostnames unusable in FreeBSD.

**Comment by vbotka** [comment]
For the record: **The first character must be an alpha character**

[RFC-952](https://www.rfc-editor.org/rfc/rfc952) does not allow dash '-' as the first character of a "name" (Net, Host, Gateway, or Domain name). Many essential subsystems, for example [Bind](https://bind9.readthedocs.io/en/latest/reference.html#namedconf-statement-check-names), comply with RFC-952. Even [RH man hosts](https://man.freebsd.org/cgi/man.cgi?query=hosts&apropos=0&sektion=0&manpath=Red+Hat+9&arch=default&format=html) says:

> The format of the host	table is described in RFC 952.

**Comment by bcoca** [comment]
tempted to close this based on @vbotka's comment, but to be fair, `hostname` is not required to be domain name compliant .. but it does create problems when it is not. This is a very rare corner case and most networks would not setup 'non compliant' host names w/o a good reason.


@mikeggrant-eumetsat  what is your use case for having these names work? not just against the RFC, but the underlying tools implementing it.  I'm now leaning towards your comment on better validation vs actually allowing for this type of name to be passed through.

**Comment by mikeggrant-eumetsat** [comment]
@vbotka yes, you're completely right - a dash as the first character of a hostname is clearly not allowed, but does currently get through to the hostname module.  I mentioned in the issue this PR links to that it'd be good to put some stronger validation rules on inputs to exclude this sort of hostname from getting through, but this PR was just about providing a safety net so that if it does get through, it won't be interpreted as an argument.

@bcoca The reason for offering this PR was that we have a (commercial) cloud management system that allowed these sorts of names through and it crashed out in ansible with what I'd consider a "incorrect" error like the "illegal option messages rather than "bad hostname".  While I don't believe there are security implications, it didn't seem right that a hostname should be potentially able to affect the hostname call and it was relatively easy to prevent any misinterpretation as a command flag by including the "--" to terminate option processing.  While it'd be good to do proper input validation as well, having this sort of option-termination as a preventative measure feels like something that should be there anyway (to me, at least, but obviously I'm happy to respect your choices in this!).

(and, yeah, we reported the poor input validation in the cloud management system to the software provider there too!)

Personally I have no use case for this sort of hostname, though I have the impression they're allowed as "pretty" hostnames by systemd?  (https://www.freedesktop.org/software/systemd/man/latest/hostnamectl.html -> _"Note that the pretty hostname has little restrictions on the characters and length used, while the static and transient hostnames are limited to the usually accepted characters of Internet domain names, and 64 characters at maximum (the latter being a Linux limitation)"_)  This in addition to the "transient-but-kinda-useless" usage that you both noted.

**Comment by mikeggrant-eumetsat** [comment]
The ultimate motivation is preventing arbitrary user input from being interpreted as (part of) commands - normally something wise to do for security reasons.  Here, it's relatively harmless as `hostname` doesn't allow much, at least at present - maybe something changes in the future.  However, in the commercial cloud system I referred to, this specific issue actually led us to be able to do a full remote shell compromise by using an appropriately naughty hostname (we used something like `random_hostname ; nc -e bash`).   That system didn't protect itself from user input and was written in a way that allowed shell injection - fortunately ansible is better written in how it executes commands!

I also agree that validation of hostnames is more work, more difficult and harder to maintain / keep up with a complex external environment.  That's why I didn't try to do it and this PR just puts in the option terminator to clearly separate the user-input hostname from the command/options part of the call to hostname, to prevent any misinterpretation.

**Comment by vbotka** [comment]
> ... validation of hostnames is more work, more difficult and harder to maintain / keep up with a complex external environment.

The below test would be fine

```python
if not re.match(r"^(?!-)[a-zA-Z0-9\-]+$", name):
     module.fail_json(msg="Invalid name: %s See RFC-952" % (name))
```
There are similar tests scattered around:
* [cron.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cron.py#L620)
* [vmware_guest.py](https://github.com/ansible-collections/community.vmware/blob/main/plugins/modules/vmware_guest.py#L2335)

An efficient use of the testing resources would be, probably, the unification of such a test. For example,

```python
    module = AnsibleModule(
        argument_spec=dict(
            name=dict(type='str', required=True, rfc=[952]),
```

**Comment by mikeggrant-eumetsat** [comment]
@vbotka What you're proposing would also solve the option problem, by validation at the input end of the problem.  Your fragment there isn't a full validation per RFC 952 or all the other complexities of a "correct" hostname, which seems to vary somewhat by OS (and change over time - this pretty hostname thing seems new-ish to me).  I felt that attempting this was too much for me, as I don't have access to or experience with many of the systems ansible covers, and wouldn't have wanted to do a halfway job on it, hence only addressing the option problem at the command execution end.  If you'd prefer to do that as the solution to this issue, I'm obviously happy to respect your greater experience in ansible's way to do things.

Just to slightly reinforce the point about this option thing being a problem, I looked at hostnamectl (system) and noticed it has a --host=USER@HOSTNAME option that allows one to change the hostname of a remote machine (assuming you have ssh access).  There's also something similar for changing "remote" container hostnames.  These are the sorts of things that one wouldn't want to have someone triggering via a hostname "--host=root@someothermachine arbitrary_hostname".  I tried this with a playbook like:
```
  tasks:
  - name: set --> FQDN on remote host using systemd hostnamectl hostname --host=user@host NAME
    hostname:
     name: --host=root@remotemachine changedhostname
```
and got the option accepted, but happily it was treated as a single argument rather than 2, so didn't execute fully.  This illustrates that the situation is undesirable and, if a new option appears that doesn't need an argument, or someone is smarter than me in finding a way to get a second argument through, or the input validation slips somehow, it would potentially be dangerous.

So, for me, even with input validation, it would still be wise to have the option termination to ensure that there isn't a possibility of misinterpretation.  However, I don't want to drive the discussion in circles (and fully respect the way you've conducted it!), so will happily accept your judgements on this.

**Comment by mikeggrant-eumetsat** [comment]
If I understand correctly, I think you're proposing that I should validate all incoming hostnames in any playbook where I may feel at risk from user input with a filter like the following?
```
#!/usr/bin/env python3

class FilterModule(object):
    def filters(self):
        return {
            "EnsureHostnameIsntAnOption": self.strip_leading_dashes
        }
    def strip_leading_dashes(self, a_hostname):
        return a_hostname.lstrip('-')
```
and use it in tasks like:
```
  - name: set --> FQDN on remote host using systemd hostnamectl hostname --host=user@host NAME
    hostname: 
     name: "{{'--host=root@localhost' | EnsureHostnameIsntAnOption}}"
```

In my case, I don't particularly mind if the hostname is valid or not (and am not sure I'm the right person to check that), so would leave it to the OS to decide that and reject it if not, but I am concerned about option injection, hence only checking for this risk in the filter here.

This would certainly be a possible solution to the issue, but ensuring that ansible isn't giving options to commands it runs doesn't feel (to me) like it should be the playbook author's responsibility - I suspect not many would know they should do this.  In most other cases, ansible makes sensible efforts to call commands safely and prevent uncontrolled injections  (as my failure to escalate this into a remote-host-renaming security issue demonstrates!).

If you judge that to be the correct solution though, we could close the issue with the filter example snippet above..

**Comment by bcoca** [comment]
just stripping or raising an error on  leading `-` seems like a simple solution, then if the hostname is still invalid for the underlying system, that should be reflected in the returns from executing the command.

**Comment by vbotka** [comment]
> just stripping or raising an error on leading `-` seems like a simple solution, then if the hostname is still invalid for the underlying system, that should be reflected in the returns from executing the command.
> 
> note: if just stripping, we should also warn that this is happening

+1

**Comment by mikeggrant-eumetsat** [comment]
Ok, thanks for the consideration on this PR :)  I'll leave the fork up for now in case any parts of it may be useful.

**Comment by vbotka** [comment]
> ... I should validate all incoming hostnames in any playbook

Yes. The best candidate is the Python package [fqdn ](https://pypi.org/project/fqdn/). See the implementation of the filter [fqdn_valid](https://github.com/vbotka/ansible-examples/tree/master/examples/example-299). The test is pretty straightforward. You can put the below asser into a file and include it as appropriate

```yaml
    - assert:
        that: hosts_invalid|length == 0
        fail_msg: "[ERR] Invalid FQDN: {{ hosts_invalid }}"
      vars:
        hosts_valid: "{{ ansible_play_hosts_all|select('fqdn_valid') }}"
        hosts_invalid: "{{ ansible_play_hosts_all|difference(hosts_valid) }}"
      run_once: true
```
JFYI, I've submitted [PR](https://github.com/ansible-collections/community.general/pull/7533) to community.general

**Pull request closed without merging**
