### PR TITLE
Standardizing the apt module

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mpdehaan** [comment]
This looks pretty good.   Here are some code review notes, if you can update the pull request with these tweaked/tested that would be great.

This pair of lines:

json.dumps(msg="could not import apt, please install the python-apt package on this host", failed=True)
-    sys.exit(1)

should be explaced with module.fail_json, the code should not have to call "json." anywhere, basically

Consistency note -- if the apt module accepts "package" as a valid name, it seems yum should also.  (I would make a very small change to add package to the list of yum module aliases).    

This code should not have been removed, because it means the error message is no longer gone:

   if rc:  
            module.fail_json(msg="'apt-get remove %s' failed: %s" % (name, err))

Also this message should not have been removed and should be reinstated:
-            fail_json(msg="'apt-get install %s' failed: %s" % (pkgspec, err))

Rather than having to return  (rc, out, err) from the various functions, you can pass module in to them, and just call module.exit_json and module.fail_json from there, directly, because these will exit the module immediately.   This will also mean you do not have to check for -1 return codes, which technically a Unix program could choose to return, and makes the module shorter.

Thank you!

**Comment by ghost** [comment]
1) For the import error, it would require me to somehow make the module variable global for it to use module.fail_json.

2) Passing the module param to the install and remove functions would actually make me duplicate some params like package and state (which are already a part of module.params)

3) I will reinstate the other error messages

**Comment by mpdehaan** [comment]
(1) That is fine, god point

(2)  This should happen.  You would not have to duplicate any parameters.   If you pass the whole module object, you can get parameters via module.params just fine from those other functions, though there is nothing wrong with passing extra parameters to functions either.    If you don't want to assign them to variables also you can still access them like module.params['foo'] as well, though it's fine to change the function signature so it takes new parameters.

(3)  Thanks!

**Comment by ghost** [comment]
If i make the module a global variable, then I would not need to pass the module variable inside functions as an argument. There are 2 approaches we can follow:
1. Make the module variable global. I will then not pass the variable separately to install and remove functions.
2. Put in the import statements inside the main function (after defining the module) so that I can use module.fail_json. This will require me to pass module variable to the functions

**Comment by mpdehaan** [comment]
Global variables will not pass review.   Just pass "module" to the functions as a first argument.

I am ok with the ImportError calling json and sys.exit() directly, it is just that the return -1, "", "" is kind of ugly and could be refactored by just calling module.fail_json and module.exit_json at the point where we knew we were done.

**Comment by mpdehaan** [comment]
looks good, merged, thanks!

**Pull request merged**
