### PR TITLE
lvg module for managing LVM volume groups

### PR DESCRIPTION
**Pull request by abulimov**
Simple LVM volume groups management module, allows to create or remove vg. Based on lvol module.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks!  In queue for review shortly.

BTW, quick tip -- you can do "type=list" as an argument to the argument_spec to have it auto-cast, BTW, and this will work better with complex argument types.

@jhoekx since you wrote lvol do you want to also help look at this?

**Comment by jhoekx** [comment]
Ok, I added a few stylistic things as comments.

What I would like to see improved in order to avoid false expectations is handling of multiple pvs. There's no vgreduce or vgextend. If you allow a list of pvs, you should handle that.

For older lvm version I think you will also need an explicit pvcreate.

**Comment by abulimov** [comment]
Thanks for stylistic comments, i'll fix it and add explicit pvcreate soon!

**Comment by jhoekx** [comment]
Ok!

I didn't try to write this module because I don't need to change this stuff too often, but will probably start using it once it's there. Thanks.

**Comment by mpdehaan** [comment]
type='bool' is the new way to cast booleans btw, you dont' need to specify choices anymore...

**Comment by mpdehaan** [comment]
thanks everyone, I will wait for a pull request update!

**Comment by mpdehaan** [comment]
anyone want to help test?  Much appreciated, thanks!

**Comment by jhoekx** [comment]
Some quick remarks, no real life tests as I don't have a system where I can test it nearby right now:
- I think you can use `pesize=dict(type='int', default=4)` instead of doing that in code. Those types are a nice addition.
- I would change the name of the `dev` parameter to `pvs` and use `pvs=dict(type='list')`
- I would change the lambda expressions into list comprehensions
  `[ pv['name'] for pv in pvs if pv['vg_name']==vg ]` is easier to understand and shorter than `map(lambda x: x['name'], filter(lambda pv: pv['vg_name'] == vg, pvs))`
- Why do you use `' '.join([`dev` for dev in devs_to_add])``? Just join when you really need to. And the backticks are pretty much deprecated.
- In the same part, why do you need `action`? I think you can just vgextend if `devs_to_add` is thruthy first and then vgreduce if `devs_to_remove`. Or maybe it's my morning head that can't figure out why.

**Comment by abulimov** [comment]
Thanks for advices, I'll fix style problems soon. Where can I read about 'type=' parameters for module arguments? i've found nothing in "Module Development".

**Comment by jhoekx** [comment]
It's not documented as far as I know. I missed it too. The best way to learn about them is to read the code `lib/ansible/module_common.py`!

**Comment by mpdehaan** [comment]
Ok, in queue for testing, thanks!

Module development features that have been added on the current development branch (1.1) are not all documented yet since that has mostly focused on released versions.   I agree it should be there, but it's also true that not all modules are taking advantage of the type checking support just yet either :)   Thanks for putting up with that!

**Comment by mpdehaan** [comment]
Merged, thanks!

**Pull request merged**
