### PR TITLE
cleaning some documentation validation errors

### PR DESCRIPTION
**Pull request by bmillemathias**
##### SUMMARY
cleaned some error reported by `ansible-test sanity --test validate-modules`

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
module git
module get_url
module getent

### CODE REVIEW

**Review by bmillemathias — COMMENTED** [review]
module uri: I'm not really sure `type: str` applies for all, I fixed based on report from `ansible-test` but reading the description some arguments seems they were waiting path (ex: `sslclientcert`)

**Comment by Akasurde** [comment]
@bmillemathias Thanks for the contribution. https://github.com/ansible/ansible/pull/70319 is handling some files which are mentioned in this PR. Could you please skip them or wait for #70319 to get merged?

Thanks,

**Comment by bmillemathias** [comment]
Hi @Akasurde, sure I can wait or delete my PR.

**Comment by Akasurde** [comment]
You may want to target other validation then.

**Pull request closed without merging**
