### PR TITLE
windows/win_shell: remove compressed yaml

### PR DESCRIPTION
**Pull request by Fale**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
windows/win_shell

##### SUMMARY
remove compressed yaml
@gundalow 
@nitzmahone

### CODE REVIEW

**Comment by nitzmahone** [comment]
I put that example in there specifically to show how to pass those without using `args`.

**Comment by Fale** [comment]
I'm not really sure why you closed this. I only replaced the "=" with ":", I've not moved it to args

**Comment by nitzmahone** [comment]
Right, but that's incorrect. Did you actually try it? `args` is required for full YAML syntax on "raw args" modules like shell/command/raw/etc- that's why I think showing the exceptional K=V syntax transformation is somewhat helpful in this case (though arguably it should be on one that isn't subject to path escaping issues like `executable`).

**Comment by Fale** [comment]
I see, sorry for that.
Sadly atm I can't test windows modules, since I don't have any windows target

**Pull request closed without merging**
