### PR TITLE
with_inventory_hostnames inventory based lookup plugin

### PR DESCRIPTION
**Pull request by sdossett**
Nearly identical to 'with_items' except that inventory.Inventory().list_hosts(terms) is used such that list items can be arbitrarily generated from the full inventory, groups, or other subsets of inventory contents.

### CODE REVIEW

**Comment by mpdehaan** [comment]
A cleaner way of doing:

delegate_to: "{{ item }}"
with_items: groups[webservers]

And has the bonus of supporting host patterns. 

I like this!  In queue for testing.

**Comment by mpdehaan** [comment]
Ok, almost works! :)

This ignores the -i parameter passed to Ansible to specify the inventory, which means it's going to almost always pick /etc/ansible/hosts from constructing the object blind.

You should be able to latch on to "runner.inventory" and use that to get the active inventory object, rather than constructing a new one.

Can you update this?

Thanks!

**Comment by sdossett** [comment]
Second commit added to the pull request with changes.

I found that runner.inventory.list_hosts contained just those hosts for the current task which is too limited as the intent is to be able to access the entire inventory contents. However, runner.inventory.host_list is available. I switched to making use of that and now have full inventory available for arbitrary patterns. I confirmed that it works with and without the -i parameter using different inventory files.

**Comment by mpdehaan** [comment]
works great, thanks!

apologies on the delay getting to this one.

**Pull request merged**
