### PR TITLE
docker_image: improve usage

### LINKED ISSUE #29514: docker_image : make action explicit
From @jmcollin78 on 2016-11-07T09:28:27Z
Hi,

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
docker_images

##### ANSIBLE VERSION
```
root$ ansible --version 
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']

```

##### CONFIGURATION
Not relevant

##### OS / ENVIRONMENT
Not relevant

##### SUMMARY
The docker_images module is very difficult to use because there is no action attribute to tells what we want to do. The action is implicit (if path -> build, if tag sometimes it tags sometimes not, ...). It would be more easy to make the action explicit with an action attribute: tag -> tags (alias) an image, build -> build, ...

##### STEPS TO REPRODUCE
Example of difficulty to use there: http://stackoverflow.com/questions/38169244/how-do-i-tag-a-local-docker-image-with-ansible-docker-image-module
How to do the equivalent of: 
```
docker tag <imageSrc> <imageDest> ?
```

Copied from original issue: ansible/ansible-modules-core#5511

### LINKED ISSUE #44077: docker_image module doen't update image on private registry
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/...../ansible/library', u'/...../ansible/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### STEPS TO REPRODUCE
Trying to push an image to a private registry with the above code:

```yaml
- name: pushing spesific image to private registry
  docker_image:
     name: "image"
     repository: "{{ docker_registry }}/user/image"
     state: present
     pull: no
     push: yes
     force: yes
```

##### EXPECTED RESULTS
When the image is already present in private registry, the code should update image from local.

##### ACTUAL RESULTS
Because of force and state values, ansible trying to pull image from docker hub (while pull attribute says no)

```
The full traceback is:
  File "/tmp/ansible_8V8r6f/ansible_modlib.zip/ansible/module_utils/docker_common.py", line 467, in pull_image
    for line in self.pull(name, tag=tag, stream=True, decode=True):
  File "/usr/lib/python2.7/dist-packages/docker/api/image.py", line 200, in pull
    self._raise_for_status(response)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_version": null, 
            "archive_path": null, 
            "buildargs": null, 
            "cacert_path": null, 
            "cert_path": null, 
            "container_limits": null, 
            "debug": false, 
            "docker_host": null, 
            "dockerfile": null, 
            "filter_logger": false, 
            "force": true, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": null, 
            "name": "image", 
            "nocache": false, 
            "path": null, 
            "pull": false, 
            "push": true, 
            "repository": "repository/user/image", 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "latest", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "use_tls": "no"
        }
    }, 
    "msg": "Error pulling image image:latest - 404 Client Error: Not Found (\"{\"message\":\"pull access denied for image, repository does not exist or may require 'docker login'\"}\")"
}
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This tries to improve how the docker_image module can be used, following the ideas from #52596.

Fixes #29514 by introduction of `source` option.
Fixes #44077 (kind of) by splitting up the `force` option.

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
docker_image

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Comment by felixfontein** [comment]
@DBendit @WojciechowskiPiotr @akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet I would really appreciate feedback on this PR. It changes the "user interface" of docker_image quite extensively, in my opinion to the better, but some more eyes than mine might find something I overlooked or have other great ideas how to improve the docker_image module!

**Comment by felixfontein** [comment]
If nobody minds, I'll try to get this merged the beginning of this week. If you're interested in the `docker_image` module, please take a look at it ASAP, or if you need a bit more time, write it here.

**Comment by felixfontein** [comment]
Re-triggering CI.

**Comment by felixfontein** [comment]
shipit

**Comment by gundalow** [comment]
@DBendit @WojciechowskiPiotr @akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet We will merge this in the next few days, so feedback welcome.

**Comment by gundalow** [comment]
As above, merging.

**Comment by felixfontein** [comment]
@gundalow thank you very much for merging! (As always :) )

**Pull request merged**
