### PR TITLE
Fixes yaml examples for Users Module

### PR DESCRIPTION
**Pull request by pavelzag**
##### SUMMARY
This PR fixes the structure of the playbook examples given within the module

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
manageiq_user.py (module)

##### ANSIBLE VERSION
```
ansible 2.4.0 
```

### CODE REVIEW

**Comment by yaacov** [comment]
I do not think we need this, @cben do we need this? 
it sounds wrong to me \o/

**Comment by pavelzag** [comment]
@yaacov It does not work without 
- hosts: localhost
  tasks:

At least AFAIC

**Comment by yaacov** [comment]
@pavelzag I trust @cben on that, let's wait for his opinion on this :-)

**Comment by cben** [comment]
It's true you need this in a *play[book]* you can run, but I think a module doc is only supposed to give examples of individual *tasks*.
https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#examples-block
Let's look at some existing core modules:
https://github.com/pavelzag/ansible/blob/stable-2.3/lib/ansible/modules/files/replace.py#L83
https://github.com/pavelzag/ansible/blob/stable-2.3/lib/ansible/modules/commands/shell.py#L85
=> EXAMPLES are tasks, no `hosts:`, `tasks:` boilerplate.  Seems we don't need this.

**Pull request closed without merging**
