### PR TITLE
hashi_vault: use mount_point kwarg for ldap/userpass login

### LINKED ISSUE #54249: hashi_vault mount_point is ignored for LDAP login
##### SUMMARY
I'm attempting to use `lookup('hashi_vault'...)` plugin with our internal Vault. It is configured for multiple LDAP authentication backends using non-default names (ie. `/v1/auth/my-domain`, `/v1/auth/another-ldap`). In order to authenticate, we need to specify `-path=my-domain` on the CLI which corresponds to the `mount_point` parameter in the plugin to target the correct auth backend. 

However, the underlying client `hvac` ignores this since it's not passed as a kwarg and it's using the `DEFAULT_MOUNT_POINT` value set in the client. When the POST is sent to login on the Vault API, it's sent only to `/v1/auth/ldap/login/my-username`. It _should_ be targeting `/v1/auth/my-auth-backend/login/my-username`.

https://github.com/hvac/hvac/blob/v0.7.2/hvac/api/auth_methods/ldap.py#L355

Proposed fix below:
```diff
--- hashi_vault.py	2019-03-22 13:51:48.000000000 -0400
+++ hashi_vault_fixed.py	2019-03-22 13:52:18.000000000 -0400
@@ -226,7 +226,7 @@
         if mount_point is None:
             mount_point = 'ldap'

-        self.client.auth_ldap(username, password, mount_point)
+        self.client.auth_ldap(username, password, mount_point=mount_point)
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hashi_vault

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = None
  configured module search path = [u'/Users/tom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

hvac 0.7.2

##### STEPS TO REPRODUCE

```yaml
    - name: Lookup tokens in Vault
      set_fact:
        k8s_auth_api_key: "{{ lookup('hashi_vault', 'secret=path/to/k8s-ansible-tokens:token auth_method=ldap mount_point=my-custom-auth-backend url=https://vault.internal.example.com username={{ hashi_vault_user }} password={{ hashi_vault_password }}' ) }}"
      no_log: no
```

##### EXPECTED RESULTS

The `lookup` succeeds and reads the secret into the Ansible task or variable. 

##### ACTUAL RESULTS

```paste below
TASK [Lookup tokens in Vault] ************************************************************************************************************************************************************************************************************************************************
/Library/Python/2.7/site-packages/ansible/plugins/lookup/hashi_vault.py:187: DeprecationWarning: Call to deprecated function 'auth_ldap'. This method will be removed in version '0.8.0' Please use the 'login' method on the 'hvac.api.auth_methods.ldap' class moving forward.
  self.client.auth_ldap(username, password, mount_point)
fatal: [localhost]: FAILED! =>
  msg: 'An unhandled exception occurred while running the lookup plugin ''hashi_vault''. Error was a <class ''hvac.exceptions.InvalidRequest''>, original message: missing client token'

>>> hc.auth_ldap('tom', 'mypass', 'my-custom-auth-backend')
__main__:1: DeprecationWarning: Call to deprecated function 'auth_ldap'. This method will be removed in version '0.8.0' Please use the 'login' method on the 'hvac.api.auth_methods.ldap' class moving forward.
/Users/tom/Library/Python/2.7/lib/python/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://vault.internal.exmaple.com:443 "POST /v1/auth/ldap/login/tom HTTP/1.1" 400 36
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/hvac/utils.py", line 169, in new_func
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/hvac/v1/__init__.py", line 2480, in auth_ldap
    return self.auth.ldap.login(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/hvac/api/auth_methods/ldap.py", line 385, in login
    json=params,
  File "/usr/local/lib/python2.7/site-packages/hvac/adapters.py", line 177, in login
    response = self.post(url, **kwargs).json()
  File "/usr/local/lib/python2.7/site-packages/hvac/adapters.py", line 106, in post
    return self.request('post', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/hvac/adapters.py", line 276, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/usr/local/lib/python2.7/site-packages/hvac/utils.py", line 29, in raise_for_error
    raise exceptions.InvalidRequest(message, errors=errors)
hvac.exceptions.InvalidRequest: missing client token
```

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Fixes #54249

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
hashi_vault

##### ADDITIONAL INFORMATION
I couldn't find any existing tests to update. I'll take a stab at a few basic unit tests.

```
ansible 2.8.0.dev0
  config file = /Users/tom/code/playbook-repo/ansible.cfg
  configured module search path = [u'/Users/tom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tom/code/opensource/ansible/lib/ansible
  executable location = /Users/tom/code/opensource/ansible/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 16:36:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

Test playbook & output:
```yaml
---
- name: Looks up a k8s api key (token) from Hashicorp Vault for later use
  hosts: local
  gather_facts: no
  tasks:
    - name: 'Check mandatory variables are defined'
      assert:
        that:
          - "lookup('env', 'VAULT_USER')"
          - "lookup('env', 'VAULT_PASSWORD')"
          - hashi_vault_secret_field is defined
    - name: Set hashi_vault credentials facts
      set_fact: 
        hashi_vault_user: "{{ lookup('env', 'VAULT_USER') }}"
        hashi_vault_password: "{{ lookup('env', 'VAULT_PASSWORD') }}"
    - name: Lookup tokens in Vault
      set_fact:
        k8s_auth_api_key: "{{ lookup('hashi_vault', 'secret=path/to/my/secret:{{ hashi_vault_secret_field }} url=https://vault.internal.example.com auth_method=ldap mount_point=my-custom-auth-backend username={{ hashi_vault_user }} password={{ hashi_vault_password }}' ) }}"
      no_log: no
```

```bash
ansible-playbook playbooks/lookup-token-hashi-vault.yml -e hashi_vault_secret_field=dev

PLAY [Looks up a k8s api key (token) from Hashicorp Vault for later use] ***********************************************************************************************************************************

TASK [Check mandatory variables are defined] ***************************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [Set hashi_vault credentials facts] *******************************************************************************************************************************************************************
ok: [localhost]

TASK [Lookup tokens in Vault] ******************************************************************************************************************************************************************************
/Users/tom/code/opensource/ansible/lib/ansible/plugins/lookup/hashi_vault.py:229: DeprecationWarning: Call to deprecated function 'auth_ldap'. This method will be removed in version '0.8.0' Please use the 'login' method on the 'hvac.api.auth_methods.ldap' class moving forward.
  self.client.auth_ldap(username, password, mount_point=mount_point)
/Users/tom/Library/Python/2.7/lib/python/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ok: [localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by tomcooperca** [comment]
Any idea how I can trigger another build? Looks like an unrelated test failure. https://app.shippable.com/github/ansible/ansible/runs/115860/42/tests

**Comment by Akasurde** [comment]
@tomcooperca Thanks for the PR. I restarted the test case for you.

**Review by Akasurde — APPROVED** [review]
LGTM

**Review by resmo — APPROVED** [review]
shipit

**Comment by Akasurde** [comment]
@tomcooperca Thanks for the contribution. @resmo Thanks for the review.

**Pull request merged**
