### PR TITLE
added --show-variables command to display evaluated variables

### PR DESCRIPTION
**Pull request by alisaifee**
- variables are displayed per play, and per host
  - variables are displayed in yaml
  - minor refactoring of color functions
    - added yamlc (ansible.color) and dict2yaml (ansible.utils)

### CODE REVIEW

**Comment by jimi-c** [comment]
A couple of things:
1) The any() built-in function was introduced in 2.5, so this would break compatibility with systems still using python 2.4, so that needs to be changed.
2) The color refactoring stuff should really be its own pull request, as its unrelated to the above functionality.

Please make those changes and resubmit. Thanks!

**Comment by alisaifee** [comment]
makes sense. thanks. 
i've submitted a new request at https://github.com/ansible/ansible/pull/3840

**Comment by mpdehaan** [comment]
Also we generally seek to avoid adding a lot of new options, so seems like this could just be something in vvv?

I have various other concerns about this applicability to other use cases so it should be discussed on list before the pull request to save some confusion, I think.

**Comment by mpdehaan** [comment]
@jimi1283 Ansible core of course already requires 2.5 and higher so point 1 does not apply

Definitely agree about breaking up PRs.

**Pull request closed without merging**
