### PR TITLE
ini_file: prohibit section name 'default'

### PR DESCRIPTION
**Pull request by jpmens**
Partial fix for #1682

### CODE REVIEW

**Comment by mpdehaan** [comment]
I think default is probably a perfectly legal section name.

What you probably want to do is default it to "value_not_set" or something very unlikely, and then make the exception say instead that setting the value is required.  Otherwise the error message may be somewhat confusing.

**Comment by jpmens** [comment]
'default' is _not_ a perfectly legal section name, at least not for
ConfigParser. I posted the snippet of docs which says so.

**Comment by mpdehaan** [comment]
ah, I see, so _older_ versions of config parser will raise an error if you use the name default, I understand.

(I also see that it was defaulted to null before, which was fine, I was thinking it assumed 'default' was the default for 'section', which was not the case)

works for me.

**Comment by jkenn99** [comment]
This doesn't work. `ConfigParser.has_section()` can't check for the existence of the DEFAULT section.

**Comment by robparrott** [comment]
FWIW, this merge breaks the ini_file usability for managing any config files in projects like OpenStack, where most configs are set within a [DEFAULT] section.

Seems to really limit its usefulness.

**Comment by jpmens** [comment]
Have you read the history of this issue and references to it?

Configparser _cannot_ handle `[DEFAULT]`.

Pull-request for alternatives welcome.

**Comment by berendt** [comment]
Don't think that this is a fix for the issue discussed in #1682. ConfigParser (or configparser) should be replaced by some other module that's able to handle all sections in INI-like files. I'll take care of an alternative and will provide an updated module ini_file not using ConfigParser.

**Comment by berendt** [comment]
Just opened a pull request to solve the issue with the DEFAULT section. Please have a look at #4696.

**Pull request merged**
