### PR TITLE
use versioned doclink for url references (#74245)

### PR DESCRIPTION
**Pull request by bcoca**
* use versioned doclink for url references

Co-authored-by: Felix Fontein <felix@fontein.de>
(cherry picked from commit c1879a5011cbc8dacc5be44d55940cf0a05deecd)

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME

docsite refs

### CODE REVIEW

**Review by samccann — CHANGES_REQUESTED** [review]
Please do not merge yet!  This is under discussion right now.

**Comment by bcoca** [comment]
@samccann as last Tuesday the ansible/2.11 site got deleted, so this needs to be merged to fix invalid urls in the errors and ansible-doc tty output.

**Comment by samccann** [comment]
Please coordinate with @acozine and @abadger

**Comment by relrod** [comment]
needs_info - per @samccann's comment

**Comment by abadger** [comment]
Closed, it was decided that this is the wrong way to go about this at the 5/18/2021 meeting.

**Pull request closed without merging**
