### PR TITLE
consul + Python 3.5

### LINKED ISSUE #23934: consul + Python 3.5
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Python3.5.2

##### STEPS TO REPRODUCE

Problem with validating if 'script', 'ttl', and 'http' arguments [line in code](https://github.com/ansible/ansible/blob/3164e8b561931b413ee91f537e2ea3273b0a1775/lib/ansible/modules/clustering/consul.py#L363)

In Python2 filter() returned list, but in Python3 - iterator.

```yaml
 - name: registerwith consul
   consul:
     service_name: "my app"
     host: "consul.service.consul"
     service_port: 8080
     script: curl http://localhost:8080
     interval: 20s
```

##### EXPECTED RESULTS

New service registered with consule

##### ACTUAL RESULTS

```
task path: /home/wgriffiths/Development/projects/service-deployment/roles/school-portal/tasks/main.yml:73
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/clustering/consul.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/clustering/consul.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> (0, '/home/ubuntu\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635 `" && echo ansible-tmp-1493070572.82-261055622658635="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635 `" ) && sleep 0'"'"''
<localhost> (0, '/home/ubuntu\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959 `" && echo ansible-tmp-1493070572.82-226439627736959="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959 `" ) && sleep 0'"'"''
<localhost> (0, 'ansible-tmp-1493070572.82-261055622658635=/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635\n', '')
<localhost> PUT /tmp/tmp6ydtAR TO /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a '[localhost]'
<localhost> (0, 'ansible-tmp-1493070572.82-226439627736959=/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959\n', '')
<localhost> PUT /tmp/tmpZeP8XY TO /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd '[localhost]'
<localhost> (0, 'sftp> put /tmp/tmp6ydtAR /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a localhost '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/ /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py && sleep 0'"'"''
<localhost> (0, 'sftp> put /tmp/tmpZeP8XY /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd localhost '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/ /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py && sleep 0'"'"''
<localhost> (0, '', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a -tt localhost '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-wzivoikwiwbckcgvtwkcsmzzfesemldb; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<localhost> (0, '', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd -tt localhost '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-alqpralqsmjuvdbamvmufyxnddzhxybj; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<localhost> (0, '\r\n{"invocation": {"module_args": {"validate_certs": true, "service_id": null, "check_id": null, "timeout": null, "service_port": 8080, "script": "curl http://localhost:8080", "http": null, "service_address": null, "ttl": null, "port": 8500, "token": null, "interval": "20s", "check_node": null, "scheme": "http", "service_name": "my app", "notes": null, "host": "consul.service.consul", "tags": null, "check_name": null, "state": "present", "check_host": null}}, "msg": "object of type \'filter\' has no len()", "failed": true}\r\n', 'Shared connection to localhost closed.\r\n')
fatal: [app02]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "check_host": null,
            "check_id": null,
            "check_name": null,
            "check_node": null,
            "host": "consul.service.consul",
            "http": null,
            "interval": "20s",
            "notes": null,
            "port": 8500,
            "scheme": "http",
            "script": "curl http://localhost:8080",
            "service_address": null,
            "service_id": null,
            "service_name": "my app",
            "service_port": 8080,
            "state": "present",
            "tags": null,
            "timeout": null,
            "token": null,
            "ttl": null,
            "validate_certs": true
        }
    },
    "msg": "object of type 'filter' has no len()"
}
```

### PR DESCRIPTION
**Pull request by wgriffiths**
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Python3.5.2

##### STEPS TO REPRODUCE

Problem with validating if 'script', 'ttl', and 'http' arguments [line in code](https://github.com/ansible/ansible/blob/3164e8b561931b413ee91f537e2ea3273b0a1775/lib/ansible/modules/clustering/consul.py#L363)

In Python2 filter() returned list, but in Python3 - iterator.

```yaml
 - name: registerwith consul
   consul:
     service_name: "my app"
     host: "consul.service.consul"
     service_port: 8080
     script: curl http://localhost:8080
     interval: 20s
```

##### EXPECTED RESULTS

New service registered with consule

##### ACTUAL RESULTS

```
task path: /home/wgriffiths/Development/projects/service-deployment/roles/school-portal/tasks/main.yml:73
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/clustering/consul.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/clustering/consul.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a localhost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<localhost> (0, '/home/ubuntu\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635 `" && echo ansible-tmp-1493070572.82-261055622658635="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635 `" ) && sleep 0'"'"''
<localhost> (0, '/home/ubuntu\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959 `" && echo ansible-tmp-1493070572.82-226439627736959="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959 `" ) && sleep 0'"'"''
<localhost> (0, 'ansible-tmp-1493070572.82-261055622658635=/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635\n', '')
<localhost> PUT /tmp/tmp6ydtAR TO /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a '[localhost]'
<localhost> (0, 'ansible-tmp-1493070572.82-226439627736959=/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959\n', '')
<localhost> PUT /tmp/tmpZeP8XY TO /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd '[localhost]'
<localhost> (0, 'sftp> put /tmp/tmp6ydtAR /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a localhost '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/ /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py && sleep 0'"'"''
<localhost> (0, 'sftp> put /tmp/tmpZeP8XY /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py\n', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd localhost '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/ /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py && sleep 0'"'"''
<localhost> (0, '', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app02/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/f96fc6261a -tt localhost '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-wzivoikwiwbckcgvtwkcsmzzfesemldb; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/consul.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-261055622658635/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<localhost> (0, '', '')
<localhost> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2203 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -i .vagrant/machines/app01/virtualbox/private_key -o UserKnownHostsFile=/dev/null -o ControlPath=/home/wgriffiths/.ansible/cp/a37fa08fdd -tt localhost '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-alqpralqsmjuvdbamvmufyxnddzhxybj; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/consul.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1493070572.82-226439627736959/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<localhost> (0, '\r\n{"invocation": {"module_args": {"validate_certs": true, "service_id": null, "check_id": null, "timeout": null, "service_port": 8080, "script": "curl http://localhost:8080", "http": null, "service_address": null, "ttl": null, "port": 8500, "token": null, "interval": "20s", "check_node": null, "scheme": "http", "service_name": "my app", "notes": null, "host": "consul.service.consul", "tags": null, "check_name": null, "state": "present", "check_host": null}}, "msg": "object of type \'filter\' has no len()", "failed": true}\r\n', 'Shared connection to localhost closed.\r\n')
fatal: [app02]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "check_host": null,
            "check_id": null,
            "check_name": null,
            "check_node": null,
            "host": "consul.service.consul",
            "http": null,
            "interval": "20s",
            "notes": null,
            "port": 8500,
            "scheme": "http",
            "script": "curl http://localhost:8080",
            "service_address": null,
            "service_id": null,
            "service_name": "my app",
            "service_port": 8080,
            "state": "present",
            "tags": null,
            "timeout": null,
            "token": null,
            "ttl": null,
            "validate_certs": true
        }
    },
    "msg": "object of type 'filter' has no len()"
}
```

### CODE REVIEW

**Comment by wgriffiths** [comment]
Original opened as #23934

**Comment by wgriffiths** [comment]
ready_for_review

**Comment by sgargan** [comment]
lgtm, thanks for taking the time to fix this. shipit

**Comment by abadger** [comment]
Rebased and switched the fix from filter +lambda to a list comprehension.  If that passes, this is good to merge.

rebuild_merge

**Comment by abadger** [comment]
Merged to devel and cherry-picked to stable-2.4 for the 2.4.0rc2 release

**Pull request merged**
