### PR TITLE
Backport 2.10: Setup virtualization_facts - add RHV and oVirt type

### PR DESCRIPTION
**Pull request by mnecas**
##### SUMMARY

Backport of #72876

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
LGTM

**Comment by mnecas** [comment]
Hi @relrod,
what is the status of this?
Could we get it merged?

**Comment by relrod** [comment]
The comment from https://github.com/ansible/ansible/pull/73903#issuecomment-815238208 holds here too. This would be a breaking change, since people can and do compare things against those values and change behavior based on them, so this isn't something we're comfortable backporting into 2.10 and lower.

If the behavior is needed in 2.10 and lower, I would recommend using custom facts.

**Comment by sivel** [comment]
Re-opening, and approving for merge.

**Pull request merged**
