### PR TITLE
Splits and rewrites gce_net

### PR DESCRIPTION
**Pull request by nkakouros**
##### SUMMARY
Splits gce_net in two. Under gce_net, the network and subnet functionality remain, firewall stuff has been moved to a new module, gce_firewall.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
gce-net

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nikos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]

```

##### ADDITIONAL INFORMATION
Reasons for rewriting:
---
The original gce_net module is responsible for three things that according to the ansible guidelines and following the separation on the google api should be treated by three separate modules; networks, subnets and firewall rules. This PR keeps the net and subnet functionality in the gce_net module and moves firewall rule creation into a new module, gce_firewall. Networks and subnets make sense to be kept together as network modes dictate what subnets will be available. Firewall rules on the other hand are irrelevant and only need a reference to a network.
Moreover, the original gce_module code is some ansible versions old. As a result, it does not conform to best practices at all.

Changes and problems fixed (in random order of significance):
----
- separation into gce_net and gce_firewall
- robustly support check_mode (multiple check functions introduced)
- new code and logic layout to be more readable
- returns more info available from the google api
- allows array of subnets instead of only one single subnet
- removed gce credentials info which is not module specific but valid and available generally for gce_* modules
- fixed conforming to best practices (for description section, imports, etc)
- uniform indentation
- corrected English

I have been using the new modules for a few weeks fixing bugs and edge cases and I feel that they are pretty stable at this point (unless I have never triggered some code path which I doubt).

### CODE REVIEW

**Comment by nkakouros** [comment]
I have no idea how to fix the 4 failed tests 'ansible-test sanity --test import --python xxx'. Could someone help me through?

**Comment by pilou-** [comment]
@tterranigma When `libcloud` is not available `PROVIDER = Provider.GCE` statement raises a `NamedError` exception. For `gce_firewall.py`, you should move the `PROVIDER = Provider.GCE` (L181) statement in the `try` block (L151) or after the call to `check_libcloud()` (L425). The same for `gce_net.py`.

**Comment by nkakouros** [comment]
@pilou- Thanks for the info!

**Comment by evancarter-iex** [comment]
Do we really want to continue to use libcloud considering Google has this now? https://github.com/google/google-api-python-client and it appears some of the modules are using it already?

**Comment by nkakouros** [comment]
@evancarter-iex If I understand correctly, Google's library allows 'raw' access to the APIs. If my assumption is true, I think that without libcloud we would have to repeat much of the work being done by libcloud itself in the module's code.

**Comment by evancarter-iex** [comment]
@tterranigma yeah thats correct. I have just found libcloud slipping further and further behind, creating a sort of a dead end for keeping stuff up to date with Googles features. And it seems the other modules are moving towards google-api-python-client.
There is some shared library stuff already developed as well: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/gcp.py

**Comment by nkakouros** [comment]
I just saw what the subnetwork module supports in the beta version of the api. A lot more stuff. Given this, maybe it is better to split even gce_net into two, gce_net and gce_subnet. It will also make the aggregate design simpler. I will start working on splitting it. Should I keep trackk of my work in this pull request or create a new one?

**Comment by erjohnso** [comment]
Overall comment, I really like where you're headed here @tterranigma!  I also agree with @evancarter-iex that new modules (or rewrites like this) should move to `google-api-python-client` (see the newest Google module addition and its [requirements](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gce_labels.py#L29-L33))

**Pull request closed without merging**
