### PR TITLE
log on target based on nolog, not verbosity

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

module logs

##### ANSIBLE VERSION

```
2.2,2.3
```

##### SUMMARY

fies #18569

### CODE REVIEW

**Comment by omgjlk** [comment]
This improves the situation, but I still think it would be valuable to log on the target that ansible did _something_, even if all the input data was masked by NOLOG.

**Comment by bcoca** [comment]
no_log is specifically there to turn this logging off.

**Comment by jylenhofgfi** [comment]
Is it possible to backport this fix to the 2.2 branch ? We are affected by this bug.

**Comment by jylenhofgfi** [comment]
I confirm this patch applied correctly to the 2.2 branch too.

**Pull request merged**
