### PR TITLE
Update ce_mtu to fix bugs

### PR DESCRIPTION
**Pull request by yanzhangi**
##### SUMMARY

Contrast before and after adding configuration

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible/modules/network/cloudengine/ce_mtu.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by yuandongx — APPROVED** [review]
+1

**Comment by hwDCN** [comment]
LGMT

**Comment by hwDCN** [comment]
+1

**Review by yuandongx — APPROVED** [review]
LGTM

**Pull request merged**
