### PR TITLE
[2.6] docker_container: fix working_dir

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #42857.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.6.3
```

### CODE REVIEW

**Comment by felixfontein** [comment]
@kassiansun Can you take a look here?

**Comment by kassiansun** [comment]
shipit

**Comment by mattclay** [comment]
Looks good, waiting on rebase.

**Comment by felixfontein** [comment]
@mattclay Thanks for merging the other backports! I've rebased this one, now it's also ready to be merged :)

**Pull request merged**
