### PR TITLE
openssh_keypair - do fail instead of regenerate for password protected and invalid keys

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Recent PR #64436 fixed the behavior for password-protected keys to always regenerate instead of crashing and/or destroying them. The new behavior of regeneration (compatible to what openssl_privatekey does) was discussed at the public project meeting (https://meetbot.fedoraproject.org/ansible-meeting/2019-12-05/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues507.2019-12-05-15.09.html, https://meetbot.fedoraproject.org/ansible-meeting/2019-12-05/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues507.2019-12-05-15.09.log.html) and it was decided that this should be reverted.

I disagree that it should be reverted, since the previous state (sometimes destroying first the public key, and on the next run regenerating the keypair - see #63910) is IMO even worse. Instead, I modified the change from that PR back to a more intermediate state which failed the module in case the existing key could not be read (because it is invalid, password protected, or whatever else).

This breaks backwards compatibility since so far, some invalid keys (like empty files as in the integration tests) were simply regenerated.

CC @MaxBab @samdoran @nitzmahone

This PR does not (yet) allow to make the regenerate behavior opt-in. I want to do that in a separate PR (which will also cover openssl_privatekey), and I'll open a discuss issue for how that should look like later.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openssh_keypair

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
LGTM (the idea in general, the changes, and the CI tests seem relevant)

**Comment by MaxBab** [comment]
LGTM

**Comment by jillr** [comment]
I'm in favor of failing by default unless the user opts-in. it breaks backwards compatibility, but is the safer action.  We didn't have enough cores at the Tuesday meeting for a consensus so it will stay on the agenda for Thursday.

**Comment by MarkusTeufelberger** [comment]
I'm not in favor of this change. Ansible should create a desired state no matter what the initial state is. If people are concerned about keeping previous versions of files around, there's backups for that.

**Comment by Shaps** [comment]
I'd also be in favor of failing by default. You can't rely on people making backups.

**Comment by felixfontein** [comment]
I'm now merging this as there seems to be no more input, and as the core meeting verdict was pretty clear (https://meetbot.fedoraproject.org/ansible-meeting/2019-12-05/ansible_core_public_irc_meeting_https:github.comansiblecommunityissues507.2019-12-05-15.09.log.html). Let's continue the discussion in #65639.

rebuild_merge

**Pull request merged**
