### PR TITLE
ssh_alt.py / decrease # of ssh roundtrips

### PR DESCRIPTION
**Pull request by jeromew**
PR of ssh_alt with a fix for the async case

### CODE REVIEW

**Comment by jeromew** [comment]
Note:
since I will be afk until the end of the week, I think this patch works but I would prefer to take time to improve its readability a little.
I let you decide if you want to merge it now or wait until update it.

**Comment by mpdehaan** [comment]
Thanks for updating!

We'll test things out and make a call about merging it, I'm ok with improving readability and such later if it means we can help get some user testing in, but am also aware that it's going to be hard to get a LOT of user testing in before the holiday break, so if we can give people instructions to test with "git pull" and such, most of our users would be ok with that too.

Appreciate the update!

**Comment by jctanner** [comment]
@jeromew this is passing all of my tests except for the problem @j2sol fixed with https://github.com/ansible/ansible/pull/5254

If you could change the exec_cmd break logic per 5c5042102f70671c5834b553db12f20f7c30e730 , I am ready to merge this in ...

```
            """
            if not rpipes or p.poll() is not None:
                p.wait()
                break
            """
            # only break out if we've emptied the pipes, or there is nothing to
            # read from and the process has finished.
            if (not rpipes or not rfd) and p.poll() is not None:
                break
            # Calling wait while there are still pipes to read can cause a lock
            elif not rpipes and p.poll() == None:
                p.wait()
```

**Comment by omgjlk** [comment]
Also use of ssh_alt does not properly account for ansible_ssh_port among other things.

```
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index 027c1e3..7850fe1 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -434,7 +434,7 @@ class Runner(object):

         host_variables = self.inventory.get_variables(host)
         host_connection = host_variables.get('ansible_connection', self.transport)
-        if host_connection in [ 'paramiko', 'ssh', 'accelerate' ]:
+        if host_connection in [ 'paramiko', 'ssh', 'accelerate', 'ssh_alt' ]:
             port = host_variables.get('ansible_ssh_port', self.remote_port)
             if port is None:
                 port = C.DEFAULT_REMOTE_PORT
@@ -621,7 +621,7 @@ class Runner(object):
             if not self.accelerate_port:
                 self.accelerate_port = C.ACCELERATE_PORT

-        if actual_transport in [ 'paramiko', 'ssh', 'accelerate' ]:
+        if actual_transport in [ 'paramiko', 'ssh', 'accelerate', 'ssh_alt' ]:
             actual_port = inject.get('ansible_ssh_port', port)

         # the delegated host may have different SSH port configured, etc
@@ -879,7 +879,7 @@ class Runner(object):
         if result['rc'] != 0:
             if result['rc'] == 5:
                 output = 'Authentication failure.'
-            elif result['rc'] == 255 and self.transport == 'ssh':
+            elif result['rc'] == 255 and self.transport in ['ssh', 'ssh_alt']:
                 if utils.VERBOSITY > 3:
                     output = 'SSH encountered an unknown error. The output was:\n%s' % (result['stdout']+result['stderr'])
                 else:
```

This bit of code makes the port work again, but I'd be wary of other places in the code that may make assumptions on a transport named "ssh" vs "ssh_alt".

**Comment by omgjlk** [comment]
I"m also seeing a bit of strange or unexpected behavior --
when task is a loop:

```
    - name: touch dirs
      file: path=/tmp/{{ item }} state=directory
      with_sequence: count=4
```

and the host is dark, with ssh there appears to be one attempt to ssh to the host and that will take X seconds to fail, where X is the value of ConnectTimeout. Only one attempt is made and then the host is marked dark.

```
PLAY [Test all the things] ****************************************************

TASK: [touch dirs] ************************************************************
<10.23.149.4> ESTABLISH CONNECTION FOR USER: root
<10.23.149.4> REMOTE_MODULE file path=/tmp/1 state=directory
<10.23.149.4> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'CheckHostIP=no', '-o', 'ControlPersist=300s', '-o', 'ConnectTimeout=5', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=314', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', u'10.23.149.4', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1386872432.91-199330088698626 && echo $HOME/.ansible/tmp/ansible-1386872432.91-199330088698626'"]
fatal: [10.23.149.4] => SSH encountered an unknown error. The output was:
OpenSSH_6.4, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/root/.ansible/cp/ansible-ssh-10.23.149.4-314-root" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.23.149.4 [10.23.149.4] port 314.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 10.23.149.4 port 314: Connection timed out
ssh: connect to host 10.23.149.4 port 314: Connection timed out


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/test.yaml.retry

10.23.149.4                : ok=0    changed=0    unreachable=1    failed=0


real    0m5.691s
user    0m0.504s
sys     0m0.168s
```

With ssh_alt it appears that all the tasks in the loop are attempted before marking the host as dark, in this case 4 items in the loop so 4 connection attempts (in serial) for a time to fail of X*N where X == ConnectTimeout and N == amount of loops.

```
PLAY [Test all the things] ****************************************************

TASK: [touch dirs] ************************************************************
<10.23.149.4> ESTABLISH CONNECTION FOR USER: root
<10.23.149.4> REMOTE_MODULE file path=/tmp/1 state=directory
<10.23.149.4> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'CheckHostIP=no', '-o', 'ControlPersist=300s', '-o', 'ConnectTimeout=5', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=314', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', u'10.23.149.4', '/bin/sh -c /usr/bin/python']
failed: [10.23.149.4] => (item=1) => {"failed": true, "item": "1", "parsed": false}
invalid output was: OpenSSH_6.4, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/root/.ansible/cp/ansible-ssh-10.23.149.4-314-root" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.23.149.4 [10.23.149.4] port 314.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 10.23.149.4 port 314: Connection timed out
ssh: connect to host 10.23.149.4 port 314: Connection timed out

<10.23.149.4> ESTABLISH CONNECTION FOR USER: root
<10.23.149.4> REMOTE_MODULE file path=/tmp/2 state=directory
<10.23.149.4> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'CheckHostIP=no', '-o', 'ControlPersist=300s', '-o', 'ConnectTimeout=5', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=314', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', u'10.23.149.4', '/bin/sh -c /usr/bin/python']
failed: [10.23.149.4] => (item=2) => {"failed": true, "item": "2", "parsed": false}
invalid output was: OpenSSH_6.4, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/root/.ansible/cp/ansible-ssh-10.23.149.4-314-root" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.23.149.4 [10.23.149.4] port 314.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 10.23.149.4 port 314: Connection timed out
ssh: connect to host 10.23.149.4 port 314: Connection timed out

<10.23.149.4> ESTABLISH CONNECTION FOR USER: root
<10.23.149.4> REMOTE_MODULE file path=/tmp/3 state=directory
<10.23.149.4> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'CheckHostIP=no', '-o', 'ControlPersist=300s', '-o', 'ConnectTimeout=5', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=314', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', u'10.23.149.4', '/bin/sh -c /usr/bin/python']
failed: [10.23.149.4] => (item=3) => {"failed": true, "item": "3", "parsed": false}
invalid output was: OpenSSH_6.4, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/root/.ansible/cp/ansible-ssh-10.23.149.4-314-root" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.23.149.4 [10.23.149.4] port 314.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 10.23.149.4 port 314: Connection timed out
ssh: connect to host 10.23.149.4 port 314: Connection timed out

<10.23.149.4> ESTABLISH CONNECTION FOR USER: root
<10.23.149.4> REMOTE_MODULE file path=/tmp/4 state=directory
<10.23.149.4> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'CheckHostIP=no', '-o', 'ControlPersist=300s', '-o', 'ConnectTimeout=5', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=314', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', u'10.23.149.4', '/bin/sh -c /usr/bin/python']
failed: [10.23.149.4] => (item=4) => {"failed": true, "item": "4", "parsed": false}
invalid output was: OpenSSH_6.4, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/root/.ansible/cp/ansible-ssh-10.23.149.4-314-root" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.23.149.4 [10.23.149.4] port 314.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 10.23.149.4 port 314: Connection timed out
ssh: connect to host 10.23.149.4 port 314: Connection timed out


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/test.yaml.retry

10.23.149.4                : ok=0    changed=0    unreachable=0    failed=1


real    0m22.781s
user    0m0.468s
sys     0m0.276s
```

Depending on the number of loops for a given task, and how many hosts might be dark, this could have a pretty drastic impact on performance.

**Comment by mpdehaan** [comment]
@j2sol the one attempt and marked dark thing I think is true of regular ansible as well, because a connection error is a fatal error that ends the loop.  That part is not related to this, I'm pretty sure, and is expected.

The idea of retrying SSH attempts would be a future patchset and shouldn't hold up this one.

**Comment by mpdehaan** [comment]
"With ssh_alt it appears that all the tasks in the loop are attempted before marking the host as dark,"

Oh, just read that part.   Yes, that would be different if so.

**Comment by omgjlk** [comment]
Yeah, I guess I wasn't clear.

I prefer the way things work currently with the ssh module. One attempt and mark as dark. We even override ConnectTimeout so that we fail fast on dark hosts.

The way ssh_alt is setup would add significant delay to our plays and thus would be a non-starter for our environment. My opinion is that ssh_alt should fail on the first connection failure as ssh does -- and any change to that would be a separate feature.

**Comment by jeromew** [comment]
@jctanner I included #5254 in ssh_alt.py

**Comment by jctanner** [comment]
@jeromew great, thanks! 

Have you had a chance to look through @j2sol recent comments?

**Comment by jeromew** [comment]
@j2sol I added 'ssh_alt' tests along with 'ssh' tests in the code base. I could not find other occurences than the one you found via searching on "ssh" and 'ssh'.

**Comment by jeromew** [comment]
@j2sol I confirm that I can reproduce your "dark host" problem. with "ssh" dark hosts are always detected at the _make_tmp_path level. with "ssh_alt" it may be detected because we cannot pipe into the process. I am going to investigate this.

**Comment by jeromew** [comment]
@j2sol, @jctanner : fixed the dark host problem : I thought that the dark host was always detected with an IOError when on stdin.write() but there are cases where the process exits without an exception. I added a line to ssh_alt.py to handle p.resultcode != 0 when we are piping data. cf https://github.com/jeromew/ansible/commit/e68b3ef2e9d93f4ba711a7e526c6396fdb188f94

This fixes the different behavior of ssh_alt versus ssh in my tests.

I am going to push a squashed PR with :
- (#5254) https://github.com/jeromew/ansible/commit/5324fc5a16857182b9217a81bae56fed86fc7ee7
- (port != 22) https://github.com/jeromew/ansible/commit/d911e6db17f9015c8a855b0d9dd84433bd9f2954
- (dark host fatal) https://github.com/jeromew/ansible/commit/e68b3ef2e9d93f4ba711a7e526c6396fdb188f94

**Comment by jeromew** [comment]
@jctanner @mpdehaan - just sent the squashed PR of ssh_alt fixing remarks from @jctanner and @j2sol.

https://github.com/jeromew/ansible/commit/5c965a75f027aa7558d5f072205e974ac4ae68d5

**Comment by jctanner** [comment]
@jeromew this is passing all my tests. Let's hold off on merging it till Monday though so that we aren't scrambling to fix it over the weekend if someone else finds a bug. 

@j2sol any chance you could test this latest edition soon?

**Comment by omgjlk** [comment]
Testing of the 5c965a7 is positive. I haven't ran into any issues, and my complaints are resolved.

**Pull request merged**
