### PR TITLE
doc: add vmware_rest_guidelines

### PR DESCRIPTION
**Pull request by goneri**
Add the development guidelines for the vmware_rest collection.

### CODE REVIEW

**Comment by samccann** [comment]
in case it's not obvious - you'll need a new line between the code-block and its contents.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Docs LGTM. Not sure if @jillr is reviewing as well before we merge?

**Comment by goneri** [comment]
thank you @samccann

**Comment by jillr** [comment]
@samccann you were faster than me, I'm happy if you're happy!

**Pull request merged**
