### PR TITLE
Allow relative paths for jinja2 template extend statements

### PR DESCRIPTION
**Pull request by DavidMikeSimon**
A template cannot extend from another template that in turn extends from _another_ template using a relative path; ansible will assume all relative paths are relative to the first template, breaking the second reference.

This PR adds a test which exhibits this bug and a small fix (based on http://stackoverflow.com/a/8530761/351149) that corrects it.

### CODE REVIEW

**Comment by amenonsen** [comment]
@DavidMikeSimon, do you feel like rebasing this PR onto devel? Your change looks reasonable.

**Comment by DavidMikeSimon** [comment]
@amenonsen Sure, I should be able to get to it this week.

**Comment by DavidMikeSimon** [comment]
@amenonsen Okay, it's working again. The changes had to go a little deeper this time around; it looks like at some point during the transition to v2, ansible lost the ability to do j2 relative extends even _one_ level deep. To correct this, I had to change Templar to allow callers to provide a file path as an alternative to the raw template data.

**Comment by DavidMikeSimon** [comment]
@amenonsen Bump. Anything else I need to do on this PR?

**Comment by jimi-c** [comment]
Hi @DavidMikeSimon, not sure if we want to merge your PR in exactly as it is, however I am interested in fixing the bug you've demonstrated at the very least so we'll hold this open. Also, don't worry about rebasing this again, as we've already asked for it once without merging it.

Thanks!

**Comment by jimi-c** [comment]
Also also, sorry it's taken us so long to follow up on this!

**Comment by bcoca** [comment]
so in current code the extends works with relative paths as long as they are relative to the searchpath.

I can fix the tests to work with just adding `{% extends 'base/grandparent.j2' %}` to parent.j2

**Comment by bcoca** [comment]
@DavidMikeSimon can you resubmit just the tests (modified as i pointed out above)?

**Comment by mattclay** [comment]
The integration tests should be moved from `test/integration/roles` to `test/integration/targets`.

Also, create a `test/integration/targets/test_template_relative_paths/aliases` file with the contents:

```
posix/ci/group2
``` 

That will cause the tests to run as part of the 2nd CI group on Shippable.

**Comment by DavidMikeSimon** [comment]
@bcoca @mattclay No problem, I'll be able to get to this tomorrow.

**Comment by DavidMikeSimon** [comment]
@bcoca On closer inspection, this is a little tricky because changing the line in `parent.j2` to `{% extends 'base/grandparent.j2' %}` would also have caused the test to pass even under the effect of the bug I was attempting to fix in the first place. :-\

If nowadays extends statements in jinja2 templates in ansible are always based on the search_path and ignore the location of the template file itself, then my original bug report isn't relevant anymore. This behavior also lines up with the jinja2 spec, which allows the application to determine the meaning of the argument passed to `extends`. I'll just go ahead and close this issue.

**Comment by DavidMikeSimon** [comment]
However, see #17960

**Pull request closed without merging**
