### PR TITLE
[DNM] Test PR to check vqfx inventory

### PR DESCRIPTION
**Pull request by danielmellado**
##### SUMMARY
[DNM] Test vqfx inventory for junos gate

This PR aims to be testing the new vqfx gate for junos network platform.

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/319
Depends-On: https://github.com/ansible/ansible/pull/66682

- Test Pull Request

### CODE REVIEW

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 40798864c09003c171c893c2577dad381d42f308

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now ecec19f7888bea9f0352db21e2f315da493c1313

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 9e2b5eb734916e4d17b6cc36834ca6e855a28da1

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Pull request closed without merging**
