### PR TITLE
ovirt add vnic

### LINKED ISSUE #42233: please add vnic profile configuration to oVirt modules.
##### SUMMARY
please add vnic profile configuration to oVirt modules. since it doesn't exists today

##### ISSUE TYPE
 - adding this will allow to add specific network configuration to vnics and handle different vm provision flows more elegantly 

##### COMPONENT NAME
ovirt_vnic_profile

##### ANSIBLE VERSION
```
ansible 2.5.0
```

### PR DESCRIPTION
**Pull request by mnecas**
##### SUMMARY

Ovirt add vnic

Fixes #42233  
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ovirt
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mnecas/Desktop/Projects/Redhat/ansible/lib/ansible/modules/cloud/ovirt']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by mwperina — CHANGES_REQUESTED** [review]
Looks good to me, but please remove test/sanity/validate-modules/ignore.txt, no changes should be performed there as a part of this PR

**Comment by machacekondra** [comment]
`ignore.txt` That should be part of different PR/commit.

**Comment by mnecas** [comment]
okay will put it in new commit

**Review by mwperina — CHANGES_REQUESTED** [review]
You still have a mess in ignore.txt, the file shouldn't be even included in the PR

**Comment by mnecas** [comment]
Now it looks like all tests passed, without editing sanity ignore file.
I'm not sure if I should still create another PR.

**Review by mwperina — APPROVED** [review]
shipit

**Review by machacekondra — APPROVED** [review]
shipit

**Comment by mwperina** [comment]
-label affects_2.7
+label affects_2.8

**Comment by gundalow** [comment]
Merged into `devel` for release in Ansible 2.8.
Thank you all for the reviews

If you search for `ovirt` on https://ansible.sivel.net/pr/byfile.html there are a few other PRs open (you can ignore the `remove 2.8 deprecations `. Reviews on those would be very welcome.

If you'd like to become maintainers of Ovirt (so you are notified of issues & PR) and have voting rights, we'd welcome you to raise a PR to add yourself to https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml

Any questions feel free to ping me on `#ansible-devel`

**Pull request merged**
