### PR TITLE
Add ca_path parameter to fetch_url to support custom CA certificate

### PR DESCRIPTION
**Pull request by stepanstipl**
##### SUMMARY
Add support for using custom CA certificate for https calls.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
module_utils/urls

##### ANSIBLE VERSION
devel

##### ADDITIONAL INFORMATION
This is a ground to allow modules to use custom CAs, this is important in use cases when don't want to install CA certs permanently in the system or you want to enforce specific CA cert for validation for increased security.

### CODE REVIEW

**Comment by abadger** [comment]
Some integration tests that make use of this would be nice.  A quick scan didn't seem to indicate that this will fail on python-2.6 but it would be good to have an integration test that verifies that.  Might be hard to do correctly though as you'd have to point at a server that isn't covered by the system's CA and add the public key file that validated the server somewhere.

API-wise, the new option should be optional all the way down the stack rather than being optional at the toplevel but required in the lower levels.

**Comment by stepanstipl** [comment]
Thanks for the review, both good points. I'll look into writing some integration test - I'm thinking about starting a local web server with custom cert and then querying that (but I have to look a bit more at how integration tests are done in Ansible in similar cases).

And the `ca_path` is now optional all the way.

**Comment by jamescassell** [comment]
Likely for the integration test, you could use https://github.com/sgallagher/sscg to generate a signed cert for testing.  (This is included in epel and RHEL 8 Beta.)

**Comment by sivel** [comment]
This will be superseded by https://github.com/ansible/ansible/pull/52855

**Pull request closed without merging**
