### PR TITLE
Assemble module (again)

### PR DESCRIPTION
**Pull request by sfromm**
Issue #80 again.  Now runs/assembles on the target host.

### CODE REVIEW

**Comment by sfromm** [comment]
Forgot to note I'll be away for several days in case this needs further changes.

**Comment by sfromm** [comment]
And one other thing: I can add documentation for the module after this is merged.

**Comment by mpdehaan** [comment]
looks good..

so the execute post template stuff?   Can you explain why that says for template/assemble and not template/copy/assemble?  Seems all three use the file module the same way after.   

in queue for review once the 0.5 branch starts

**Comment by sfromm** [comment]
Do you mean _execute_post_template() in runner.py from commits 3f08fc97, 9570142, and ba164b42?  It was added in 3f08fc97 and 9570142, which was part of the old assemble implementation and then removed in ba164b42 now that assemble is run on the target node.  _execute_template() is in its original form and _execute_assemble() is only there to make sure _chain_file_module() is run.  Let me know if that helps.

**Comment by mpdehaan** [comment]
ok, np -- thanks!

**Comment by mpdehaan** [comment]
can you try to rebase this for devel?   Also if you can resubmit without the intermediate history (just one squashed merge patch) that might be better -- and will also be easier to review/merge.

**Comment by sfromm** [comment]
sure thing.

**Pull request closed without merging**
