### PR TITLE
win_chocolately document improvements, mention win_hotfix and use of become

### LINKED ISSUE #26385: win_chocolatey: Cannot install hotfixes (KB####) over WinRM
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- `win_chocolatey`

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, May  5 2017, 21:21:54) [GCC 6.3.0]
```

##### CONFIGURATION
- Default

##### OS / ENVIRONMENT

- Ansible on **Gentoo**
- Target system is **Windows via WinRM**

##### SUMMARY
[Microsoft does not support](https://support.microsoft.com/en-us/help/2773898/windows-update-standalone-installer-wusa-returns-0x5-error-access-deni) using WUSA over a WinRM connection. If WUSA.exe has a WinRM session for an ancestor, it will exit immediately with "Access denied."

Chocolatey packages that install Windows hotfixes (kb######) use WUSA to install the update after downloading it. If the Chocolatey command is running within a WinRM session, it encounters the same problem.

Special-casing win_chocolatey for names beginning with "kb" is no solution either; some Chocolatey packages depend on these hotfix packages, perhaps even indirectly.

This could be argued as a bug with the Chocolatey packages themselves, as there exists some condition under which installation will fail. However, I believe this is appropriate as an Ansible bug, because the `win_chocolatey` task cannot install hotfixes (or packages depending on them) at all.

##### STEPS TO REPRODUCE

```yaml
- name: Demonstrate bug with installing hotfixes over WinRM
  hosts: all
  tasks:
    - name: Install Chocolatey
      raw: "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
    - name: Attempt to install KB3033929
      win_chocolatey: name=kb3033929
```

Please see [this gist](https://gist.github.com/CFSworks/490cf68574739df11b9deaaee1fcaa67) if you would like to reproduce the bug in Vagrant.

##### EXPECTED RESULTS

Hotfix package should install like any other Chocolatey package.

##### ACTUAL RESULTS

```
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...

PLAY [Demonstrate bug with installing hotfixes over WinRM] *********************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [Install Chocolatey] ******************************************************
changed: [default]

TASK [Attempt to install KB3033929] ********************************************
fatal: [default]: FAILED! => {"changed": false, "choco_error_cmd": "choco.exe install -dv -y kb3033929 -timeout 2700", "choco_error_log": null, "failed": true, "msg": "Error installing kb3033929", "rc": 5}
        to retry, use: --limit @/home/cfsworks/Desktop/winbug/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=2    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### LINKED ISSUE #27155: win_chocolatey fails to deploy packages
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

##### OS / ENVIRONMENT

control machine: OS-X 10.12.6
target machine - Windows 2012 R2 

##### SUMMARY

The following packages fail to deploy:
officeproplus2013
sql-server-management-studio

Extending the win_chocolatey timeout attribute didn't change the result.

Manually running choco on the target machine successfully deploys all packages.

##### STEPS TO REPRODUCE

```yaml
- name: Deploy tools
  win_chocolatey:
    name: "{{ item }}"
  with_items:
    - officeproplus2013
    - visualstudio2013professional
    - sql-server-management-studio
```

##### EXPECTED RESULTS

Successfully deployed all packages

##### ACTUAL RESULTS
```python
TASK [depy.dev : Deploy tools] ***************************************************************************************************************************
task path: /Users/liora/git/depy-backend/depy/ansible/roles/depy/depy.dev/tasks/main.yml:9
Using module file /Users/liora/venv/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
<185.109.149.152> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 185.109.149.152
EXEC (via pipeline wrapper)
failed: [185.109.149.152] (item=officeproplus2013) => {
    "changed": true,
    "choco_error_cmd": "C:\\ProgramData\\chocolatey\\bin\\choco.exe install -dv -y officeproplus2013 -timeout 2700",
    "choco_error_log": null,
    "failed": true,
    "item": "officeproplus2013",
    "msg": "Error installing officeproplus2013",
    "rc": -2147418113
}
Using module file /Users/liora/venv/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
EXEC (via pipeline wrapper)
changed: [185.109.149.152] => (item=visualstudio2013professional) => {
    "changed": true,
    "item": "visualstudio2013professional",
    "rc": 0
}
Using module file /Users/liora/venv/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
EXEC (via pipeline wrapper)
failed: [185.109.149.152] (item=sql-server-management-studio) => {
    "changed": true,
    "choco_error_cmd": "C:\\ProgramData\\chocolatey\\bin\\choco.exe install -dv -y sql-server-management-studio -timeout 2700",
    "choco_error_log": null,
    "failed": true,
    "item": "sql-server-management-studio",
    "msg": "Error installing sql-server-management-studio",
    "rc": 5
}
```

### LINKED ISSUE #29702: uri: status "changed" never thrown
From @oupala on 2016-08-21T15:14:24Z

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

uri
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

standard
##### OS / ENVIRONMENT

debian to raspbian
##### SUMMARY

status "changed" never thrown by a uri task, even if an http call is sent
##### STEPS TO REPRODUCE

Create a task that generate an http call:

```
- name: create the database and the database schema
  uri: url=https://{{ hostname }}/{{ app_path }}/install.php
       creates={{ apps_install_path }}/database.sqlite3
       validate_certs=no
```
##### EXPECTED RESULTS

The task should be executed the first time you launch the playbook, because the file database.sqlite3 does not exist. You can see the http call in the logfile of your http server. The task status should be `ok` or `changed`, I'm not sure what would be the best solution.

On the second run of the playbook, the task shouldn't be executed, because the file database.sqlite3 does exist. You shouldn't see any http call in the logfile of your http server. The task status should be `skipped`.
##### ACTUAL RESULTS

The task is executed the first time, because the file database.sqlite3 does not exist. I can see the http call in the logfile of the http server. The task status is `ok`.

On the second run of the playbook, the file database.sqlite3 does exist. I can't see any http call in the logfile of the http server, which is normal. But the task status is `ok`.

The main problem is then the status report, which is alway `ok` whenever an http call has been sent or not.

```
TASK [myapp : create the database and the database schema] **********
ok: [myserver]
```

Copied from original issue: ansible/ansible-modules-core#4490

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### SUMMARY

Following on from WIndows Sprint 2 review of issues reported with win_chocolatey, this
PR attempts to document its limitations and available workarounds.

Fixes #27155
Fixes #29702 (already closed)
Fixes #26385

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

win_chocolatey
##### ANSIBLE VERSION

```
ansible 2.5.0 (choco_become_doc c1ec4a5341) last updated 2017/09/29 06:48:51 (GMT +000)
  config file = None
  configured module search path = [u'/home/pi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pi/ansible-dev/lib/ansible
  executable location = /home/pi/ansible-dev/bin/ansible
  python version = 2.7.9 (default, Aug 13 2016, 16:41:35) [GCC 4.9.2]

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by dagwieers — APPROVED** [review]
LGTM

**Comment by jhawkesworth** [comment]
For the record I don't think this should be backported as win_hotfix and (more robust) become are 2.4 features.

**Comment by dagwieers** [comment]
I get mixed messages here. Do you mean it should be backported, or should not be backported ?

**Comment by jhawkesworth** [comment]
I meant that it should not be backported.  However, I am wrong!  The change isn't correct for ansible 2.3 but is correct for 2.4.x (and hopefully 2.5 and later versions).

**Comment by dagwieers** [comment]
The reason why I was confused is that you say these are 2.4 features. But 2.4 does require a backport as well since it was branched. So for stable-2.4 these updates are very much needed ;-)

**Comment by jborean93** [comment]
Yep this should be cherry picked to stable-2.4

**Comment by dagwieers** [comment]
@jborean93 We are looking at you ;-) External committers are not allowed to backport AFAIK.

**Comment by jborean93** [comment]
That would help wouldn't it, cherry-picked to stable-2.4 under https://github.com/ansible/ansible/commit/6d82ef83781ab30c8aa3988c37faf532a6b9f513

**Comment by jhawkesworth** [comment]
@jborean93 thanks for the backport

**Pull request merged**
