### PR TITLE
Vorteil module, module-util and documentation-fragement added

### PR DESCRIPTION
**Pull request by jalfvort**
##### SUMMARY

Added new module for Vorteil.io Repo Support

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

vorteil
##### ADDITIONAL INFORMATION

New module being added in this pull requests. I've tested against ansible sanity tests on all modules, and have tried to reduce repeating documentation by creating a documentation-fragment. Additional testing was done with playbooks on local machine, however I didn't push these as most of the functionality of the module requires sensitive information, or requires Vorteil.io to be installed in your local machine.

### CODE REVIEW

**Comment by jalfvort** [comment]
Documentation for Vorteil.io can be found here: https://support.vorteil.io/ 
Though the Vorteil daemon is not needed for testing the vorteil_list_buckets module.
Please feel free to ask for any help using the module.

**Comment by jalfvort** [comment]
Closing due to stale_ci

**Comment by jalfvort** [comment]
Reopening due to stale_ci

**Comment by gundalow** [comment]
@jalfvort Thanks for thei PR. Do you work for Vorteil.io?

It would be great to see a new collection called `vorteil.cloud` (or similar) created that contains these modules.

**Comment by jimi-c** [comment]
Per the above comment from @gundalow regarding the collection repo, we're going to go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jalfvort** [comment]
Hello,

Thanks for taking time out of your days to reply.

@gundalow I do work for Vorteil, and have created a collection that lives at https://galaxy.ansible.com/ansible_vorteil/cloud . 

I also just updated the collection so that it satisfies the new sanity checks. 

I will in the future try to get the Vorteil collection onto https://github.com/ansible-collections .

Thank you.

**Comment by gundalow** [comment]
Hi,
Its fine for the collection to live in https://github.com/ansible-vorteil/vorteil_collection_ansible

If you copy lines 1-24 from https://github.com/ansible-collections/community.grafana/blob/master/.github/workflows/ansible-test.yml and change line 13 to be your namespace/collection then you'll have sanity tests running on every PR.

Please feel free to shout out for help in `#ansible-devel` if you to.

**Pull request closed without merging**
