### PR TITLE
postgres_user module: `role_attr_flags` does nothing when combined with `no_password_changes`

### LINKED ISSUE #19835: postgres_user module: `role_attr_flags` does nothing when combined with `no_password_changes`
_From @woqer on June 24, 2016 18:12_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

postgresql_user
##### ANSIBLE VERSION

```
Ansible 2.1.0.0
```
##### OS / ENVIRONMENT

Mac OS X El Capitan, Version 10.11.4
Tested on Docker official postgres container and on Amazon RDS PostgreSQL DB instance
##### SUMMARY

When running a task with postgres_user module, the option `role_attr_flags` does not set any role attributes when `no_password_change` is set to `yes`
##### STEPS TO REPRODUCE

Run a task with module postgres_user, set any attribute in `role_attr_flags` and the option `no_password_changes` to `yes`

```

---
- hosts: localhost

  tasks:
    - name: create user
      postgresql_user:
        name: testing_user
        password: somerandompassword
        state: present
        login_host: your.amazon.url.to.postges.instance
        login_user: yourdefaultpostgresuser
        login_password: yoursecretpasswordforthedefaultuser
    - name: add attributes to user
      postgresql_user:
        name: testing_user
        no_password_changes: yes
        role_attr_flags: CREATEDB
        login_host: your.amazon.url.to.postges.instance
        login_user: yourdefaultpostgresuser
        login_password: yoursecretpasswordforthedefaultuser
```

##### EXPECTED RESULTS

The user testing_user should have the CreateDB attribute
##### ACTUAL RESULTS

No changes made.

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [create user] *************************************************************
changed: [localhost] => {"changed": true, "user": "test_user"}

TASK [add attributes to user] **************************************************
ok: [localhost] => {"changed": false, "user": "test_user"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```

_Copied from original issue: ansible/ansible-modules-core#4034_

### PR DESCRIPTION
**Pull request by wvidana**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

module postgres_user
##### ANSIBLE VERSION

```
Ansible 2.1.0.0
```
##### SUMMARY

Add an else branch to `user_alter`, since any operation is completely skipped if there is no password change. Only implemented `role_attr_flags` feature.

Fixes https://github.com/ansible/ansible/issues/19835

###### BEFORE

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [create user] *************************************************************
changed: [localhost] => {"changed": true, "user": "test_user"}

TASK [add attributes to user] **************************************************
ok: [localhost] => {"changed": false, "user": "test_user"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```
###### AFTER

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [create user] *************************************************************
task path: /root/ansible/test/samples/test_postgres_user.yml:5
changed: [localhost] => {"changed": true, "user": "testing_user"}

TASK [add attributes to user] **************************************************
task path: /root/ansible/test/samples/test_postgres_user.yml:13
changed: [localhost] => {"changed": true, "user": "testing_user"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by wvidana** [comment]
Migrated from https://github.com/ansible/ansible-modules-core/pull/4038

**Comment by gundalow** [comment]
~~Duplicate of https://github.com/ansible/ansible/issues/19835~~

**Comment by rouge8** [comment]
@gundalow this is a PR, #19835 is an issue

**Comment by gundalow** [comment]
You are indeed correct

**Comment by alikins** [comment]
LGTM

I added a test for this to the postgres intg tests as well (currently at https://github.com/ansible/ansible/compare/devel...alikins:postgresql_user_test_19835)
The tests there fail with devel and pass with this branch.

**Pull request merged**
