### PR TITLE
pulp_repo: adjust version_added after backport was merged

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adjust the `version_added`s to mention 2.9.2 instead of 2.10, as #65014 has been merged to `stable-2.9` for release in Ansible 2.9.2.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
pulp_repo

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @coreaut

**Comment by felixfontein** [comment]
All other CI runs passed; the only error are the two sanity failures mentioned above. These are to be expected since this PR explicitly changes `version_added` from `2.10` to `2.9.2`.

**Comment by coreaut** [comment]
thanks again felixfontein for your help and time with this
shipit

**Review by coreaut — APPROVED** [review]

**Comment by felixfontein** [comment]
@coreaut also thanks to you for fixing the bug!

**Pull request merged**
