### PR TITLE
remove obsolete set_play on play_context

### PR DESCRIPTION
**Pull request by bcoca**
- all tasks already inherit this from play directly

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

play_context
##### ANSIBLE VERSION

```paste below
2.x
```

### CODE REVIEW

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/91372/56/console

```
06:56 ++ ansible-playbook test_force_handlers.yml -i inventory.handlers -v -vvvvvv --tags force_true_in_play
06:56 ++ sort
06:56 ++ xargs
06:56 ++ uniq
06:56 ++ egrep -o CALLED_HANDLER_.
06:57 + '[' CALLED_HANDLER_B = 'CALLED_HANDLER_A CALLED_HANDLER_B' ']'
06:57 Command exited with status 1 after 13.7113640308 seconds.
```

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/92011/56/console

```
01:47 Traceback (most recent call last):
01:47   File "/root/ansible/bin/ansible", line 110, in <module>
01:47     exit_code = cli.run()
01:47   File "/root/ansible/lib/ansible/cli/adhoc.py", line 140, in run
01:47     play = Play().load(play_ds, variable_manager=variable_manager, loader=loader, options=options)
01:47 NameError: global name 'options' is not defined
```

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/92173/66/console

```
02:22 Traceback (most recent call last):
02:22   File "/root/ansible/bin/ansible", line 110, in <module>
02:22     exit_code = cli.run()
02:22   File "/root/ansible/lib/ansible/cli/adhoc.py", line 140, in run
02:22     play = Play().load(play_ds, variable_manager=variable_manager, loader=loader, options=self.options)
02:22   File "/root/ansible/lib/ansible/playbook/play.py", line 118, in load
02:22     return p.load_data(data, variable_manager=variable_manager, loader=loader, options=options)
02:22   File "/root/ansible/lib/ansible/playbook/play.py", line 124, in load_data
02:22     self._set_from_CLI_options()
02:22   File "/root/ansible/lib/ansible/playbook/play.py", line 367, in _set_from_CLI_options
02:22     self.check_mode = bool(self._options.check, strict=False)
02:22 TypeError: bool() takes at most 1 argument (2 given)
```

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/92808/5/tests

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/93985/8/tests

```
>       assert play_context.no_log is True
E       AssertionError: assert <MagicMock name='mock.no_log' id='140499883271280'> is True
E        +  where <MagicMock name='mock.no_log' id='140499883271280'> = <ansible.playbook.play_context.PlayContext object at 0x7fc8adb3fa20>.no_log

test/units/playbook/test_play_context.py:80: AssertionError
```

**Comment by mattclay** [comment]
CI failure in unit tests: https://app.shippable.com/github/ansible/ansible/runs/102577/9/tests

The Azure integration test failures are unrelated.

**Comment by felixfontein** [comment]
@bcoca Every playbook I'm executing now is currently littered with `[DEPRECATION WARNING]: PlayContext.force_handlers should not be used, the calling code should be using play itself instead. This feature will be removed in version 2.19. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.` warnings (which have been introduced in this PR). I'm even getting it with a trivial playbook such as:
```
- hosts: localhost
  tasks: []
```
Is this intended?

**Comment by albers** [comment]
I'm also facing this in a slightly different context:

A playbook with several plays.
The first play invokes a role that calls another role from its task file via `include_role` (also happens with `import_role`).
Every task in that secondary role causes the deprecation warning. 

### playbook
```yaml
# This play causes lots of deprecation warnings
- name: Create VMs
  hosts: swarm_masters
  gather_facts: no
  tags: [deploy]
  roles:
    - ubuntu_cloud_image_host

# This play does not cause any deprecation warnings
- name: Create a Docker swarm
  hosts: swarm_masters
  tags: [swarm]
  roles:
    - ubuntu_host
    - swarm_master
```
### tasks file of role *ubuntu_cloud_image_host*
```yaml
- import_role: name=albers.vmware_ubuntu_cloud_image
```

**Comment by felixfontein** [comment]
@albers the problem I had was fixed in #53705; do you still have this problem after that PR was merged?

**Comment by albers** [comment]
@felixfontein Thanks for the hint.

I was still at 15303b05efea234eb348871244b8094c9c63d939.
Pulling to the current repo state (fa2e8d8fe1bfb47cdc29958411e3787b80e35591) resolved the issue for me.

**Pull request merged**
