### PR TITLE
add pid to logfile entries

### PR DESCRIPTION
**Pull request by mcodd**
Here is the patch I mentioned on the mailing list to add the PID to the log so we can tell interleaved runs apart from one another.

### CODE REVIEW

**Comment by mpdehaan** [comment]
looks like this code needs to deal with the scenario when logger isn't defined, i.e. "if not screen_only and logger is not None" ?

**Comment by mcodd** [comment]
Per discussion on IRC, the definition of and use of "logger" only occur
within blocks that say "if constants.DEFAULT_LOG_PATH != ''" so as things
stand there's no way to use the logger variable without already having set
it.

matt

**Comment by mpdehaan** [comment]
Good deal.  My other thought is the pid should maybe come first for easy grepping of the session info.

**Comment by mcodd** [comment]
Agreed having the pid stand out better than just another space-delimited int makes sense (both from a log parsing and visual perspective).  It's pretty standard for logs to have the datestamp first, though, and I think we should try and keep that.  Wrapping [date] and [pid] in brackets is better, and other logs (apache, syslog) do that too, but we also wrap hostnames in brackets so it's not really a unique separator.  Probably overthinking this at this stage, though.  I like how this looks:

[date] [pid] message

What do you think?  I can submit another pull request doing that instead (and I also want to not set the "mypid" intermediate variable there since it has a global scope in callbacks.py... just do it all in one call "logger = logging.getLogger(str(os.getpid()))")

**Pull request merged**
