### PR TITLE
dnf: Add nobest option

### LINKED ISSUE #69983: Add --nobest to dnf module
##### SUMMARY

dnf has a nobest [option](https://dnf.readthedocs.io/en/latest/command_ref.html#options-label) which does the following:

> --nobest
>     Set best option to False, so that transactions are not limited to best candidates only.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

dnf

##### ADDITIONAL INFORMATION

Docker cannot be installed on CentOS8 without `--nobest` option and later on every time you want to do dnf upgrade you should pass `--nobest` option again, so that it does not complain about `docker-ce` package.

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
Add nobest option for dnf. (Fixes #69983)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
dnf

### CODE REVIEW

**Comment by aminvakil** [comment]
@cbutterfield

Just trying to help, maintainers can help you better but you can use this documentation to use this forked repo temporary.

https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#common-environment-setup

Just change:
```
git clone https://github.com/ansible/ansible.git
```
to:
```
https://github.com/aminvakil/ansible
cd ansible
git checkout dnf_no_best
```
I'm not going to update the branch expect if it needs a rebase to merge this PR, so I suggest keep using `shell: dnf update -y --nobest` or at least wait until (if) this PR merged in devel branch of the main repo.

**Comment by cbutterfield** [comment]
Thanks!

**Comment by maxamillion** [comment]
shipit

**Review by maxamillion — APPROVED** [review]

**Review by mkrizek — APPROVED** [review]

**Comment by mkrizek** [comment]
rebuild_merge

**Pull request merged**
