### PR TITLE
Remove inline comments from inventory tokenizing.

### PR DESCRIPTION
**Pull request by pol**
This removes inline comments from the line prior to tokenizing.  It assumes that comments will always be line suffixes (the last part of a line).  

Test included.

### CODE REVIEW

**Comment by mpdehaan** [comment]
excellent, thanks!

**Comment by bcoca** [comment]
Darnit!  This breaks my inventory!

host myhostvar="234#2343" # this is a comment, but myhostvar is now 234

Brian Coca

**Comment by pol** [comment]
I will add a test for that and fix it.

On Thursday, May 30, 2013, Brian Coca wrote:

> Darnit! This breaks my inventory!
> 
> host myhostvar="234#2343" # this is a comment, but myhostvar is now 234
> 
> Brian Coca
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/3067#issuecomment-18716209
> .

## 

Pol M. Llovet
Research Computing /  Middleware
w: 406-994-3416
c: 406-646-6747

**Comment by pol** [comment]
The "right" way is to write in semantics for understanding the vars syntax
and avoiding any "#" in a var string.  The easy way is to split on " #"
instead of "#".  I am going to do the easy way unless/until there is a
strong demand for storing " #" in varstrings, hostnames or group names.

**Comment by bcoca** [comment]
my actual production case has to do with html anchors "uri#anchor"

I will dispose of any people that start putting spaces at the end
directories or location directives, so I think we are good.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Pull request merged**
