### PR TITLE
add search option to lookup dig

### PR DESCRIPTION
**Pull request by whitekid**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

lib/ansible/plugins/lookup/dig.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY

add search option to lookup dig

usage:

    lookup('dig', 'www', 'search=google.com')

```

```

### CODE REVIEW

**Comment by abadger** [comment]
This should have some documentation added as well in this section: https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/playbooks_lookups.rst#L275

**Comment by abadger** [comment]
needs_revision

**Comment by calfonso** [comment]
@whitekid are you interested in adding documentation per the last comment? Once you do, we'll finish the review.

**Comment by jpmens** [comment]
shipit

**Comment by bcoca** [comment]
@whitekid docs now live in plugin itself, please update those once you rebase

**Comment by Akasurde** [comment]
@whitekid Are you still working on this ? Thanks.

**Comment by whitekid** [comment]
@Akasurde It's been a long time... I'm not working on this... Closing..

**Comment by Akasurde** [comment]
@whitekid I understand. Thanks for the contribution.

**Pull request closed without merging**
