### PR TITLE
vmware_guest: Do not match simply by folder

### LINKED ISSUE #19077: vmware_guest uses another VM when explicitly asked to create a new one
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.2 (with latest vmware_guest from devel)

##### SUMMARY

Something very fishy is going on.

I use vmware_guest to template a new system (unique hostname) that does not exist. But instead the module returns successful (with no change) and returns the facts of another hostname consistently.

Even when I run the same playbook to create 3 new VMs, it returns for each three the same VM facts of this specific running VM.

Any idea why this could be happening ?

We do a very simple
```yaml
- vmware_guest:
    hostname: '{{ vcenter_ipaddress }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    folder: '{{ vcenter_folder }}'
    template: 'windows-2012r2-template01'
    name: '{{ inventory_hostname_short }}'
    state: present
    wait_for_ip_address: yes
    validate_certs: no
    customize: yes
    domain: '{{ domain }}'
    dns_servers: '{{ dns_ip }}'
    ips: '{{ ansible_host }}'
    networks:
      '{{ vm_cidr }}':
        network: 'VM Network'
        gateway: '{{ gw_ip }}'
    register: vmware_facts
    connection: local
```

So nothing fancy at all. vSphere is v5.5

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.3

##### SUMMARY

This relates to #19417
This fixes #19077

Please test !

### CODE REVIEW

**Comment by nerzhul** [comment]
It seems okay, but i will test it tomorrow at work with my creation test playbook to ensure it doesn't break VM creation from scratch

**Comment by dagwieers** [comment]
Confirmed to work.

**Comment by nerzhul** [comment]
shipit

**Comment by nerzhul** [comment]
tested @work with various combinaisons it's okay please merge

**Comment by gundalow** [comment]
Merged to `devel`

**Pull request merged**
