### PR TITLE
E1 legacy pep8 fixes

### PR DESCRIPTION
**Pull request by sivel**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
various

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY
E1 pep8 legacy fixes.  Additionally, there are a few other fixes that were within visual range of other changes.

### CODE REVIEW

**Comment by bcoca** [comment]
we don't normally take style changes as they break attribution

**Comment by sivel** [comment]
Reopening, this will be delayed until after the stable-2.3 branching, and discussed slightly more.

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/21933/files?w=1 is a cleaner way to view the diff

**Comment by sivel** [comment]
I've re-reviewed the changes a few times since submitting, and am confident that they won't cause any problems.

I still plan on having this go into devel after the stable-2.3 branch is made.

**Pull request merged**
