### PR TITLE
[2.7] docsite: remove lexers which have been fixed in Pygments 2.4.0

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #57508 to stable-2.7: removes lexers which have been fixed in Pygments 2.4.0.

This leaves an empty stub; I'm not sure whether we should leave it in (will make backporting easier if we need that again in the future) or delete it (re-adding it is easy as well). Any opinions?

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/_extensions/pygments_lexer.py

### CODE REVIEW

**Comment by abadger** [comment]
I'm okay leaving the stub in since the framework is still present in devel and, as you say, it makes backporting easier.

**Comment by abadger** [comment]
@felixfontein This backport is failing sanity tests.  Since it's docs-only, we can merge it out-of-band from any release but it will need to pass before it can be merged.

**Comment by acozine** [comment]
Local build shows that the errors are coming from:

```
docs/docsite/rst/dev_guide/developing_modules_general.rst:187: WARNING: Could not lex literal_block as "YAML+Jinja". Highlighting skipped.                            
docs/docsite/rst/plugins/inventory.rst:58: WARNING: Could not lex literal_block as "YAML+Jinja". Highlighting skipped.
docs/docsite/rst/plugins/inventory.rst:91: WARNING: Could not lex literal_block as "YAML+Jinja". Highlighting skipped.
docs/docsite/rst/plugins/lookup.rst:75: WARNING: Could not lex literal_block as "YAML+Jinja". Highlighting skipped.
docs/docsite/rst/plugins/lookup.rst:87: WARNING: Could not lex literal_block as "YAML+Jinja". Highlighting skipped.
docs/docsite/rst/plugins/lookup.rst:101: WARNING: Could not lex literal_block as "YAML+Jinja". Highlighting skipped.
docs/docsite/rst/reference_appendices/YAMLSyntax.rst:176: WARNING: Could not lex literal_block as "YAML+Jinja". Highlighting skipped.
```

**Comment by acozine** [comment]
If we backport #50836 to 2.7, that should fix these failures.

**Comment by acozine** [comment]
Ah, we'd also need to backport #50318. I'm going to see if I can get this pulled together.

**Comment by acozine** [comment]
Shippable is failing due to an unstable test. Seems unrelated to these changes, but I've restarted it twice and it still isn't passing.

**Comment by felixfontein** [comment]
@acozine your commit looks good. About failing tests: that's definitely unrelated. I've now also kicked the failed tests once more. Let's see whether it finishes this time...

**Comment by felixfontein** [comment]
@acozine tests ran through this time! \o/

**Comment by felixfontein** [comment]
@acozine thanks for fixing/backporting and merging! :)

**Pull request merged**
