### PR TITLE
Depreciating old modules

### PR DESCRIPTION
**Pull request by schmots1**
##### SUMMARY
This PR is changing the status of our old modules to depreciated

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
na_cdot_*

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Review by carchi8py — APPROVED** [review]

**Comment by amit0701** [comment]
shipit

**Comment by bcoca** [comment]
to really deprecate:
  - update metadata
  - rename with a leading underscore
  - add 'deprecated' to docs and point to alternatives

**Review by bcoca — CHANGES_REQUESTED** [review]
metadata alone is not enough

**Comment by schmots1** [comment]
Requested/Required changes made.

**Review by amit0701 — APPROVED** [review]

**Review by bcoca — APPROVED** [review]

**Comment by schmots1** [comment]
too much has changed.. closing to resubmit

**Pull request closed without merging**
