### PR TITLE
clarify `returned` value of `RETURN` nlock

### PR DESCRIPTION
**Pull request by evgeni**
##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
Spot on!

**Comment by mdellweg** [comment]
Turns out, human readability is not really the state of affairs.

https://gist.github.com/evgeni/86fff8cdb7cc1b131d24083a17a2b019

**Comment by acozine** [comment]
Thanks @evgeni. My first thought was, do we really want to advertise that the field is a string and can contain anything? But then, as your gist demonstrates, people already seem to know that.

**Comment by evgeni** [comment]
@acozine yeah, I'd love to see this field more standardized, but currently it's the wild west out there.

**Pull request merged**
