### PR TITLE
Add a Singleton metaclass, use it with Display

### PR DESCRIPTION
**Pull request by sivel**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
Display

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY
Add a Singleton metaclass, use it with Display

This removes the pseudo singleton created by doing `from __main__ import display`

There are cases where `__main__` may not have `display`, and in those cases, things like verbosity are lost across instances of `Display`.  This makes `Display` act more like a singleton without trying to import from `__main__`.

One example where this failed for me before was building a pex file for executing ansible:

```
$ pex ansible -c ansible -o ansible.pex
$ ./ansible.pex all -i localhost, -c local -m ping -vvvv
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

With this PR applied, I get proper verbosity.

### CODE REVIEW

**Comment by sivel** [comment]
Rebased against devel, and updated new files.  Test failure is unrelated.

**Comment by bcoca** [comment]
So this will still loose the verbosity across forks (which i believe is the problem you experience), a different approach is making 2 display classes, the normal (pre fork) and a 'client' (post fork) that sends info back to the parent fork which then uses the 'singleton' display.

**Comment by sivel** [comment]
I'll play with it more to see if that is the case.  I'll have to come up with a test to verify that.  My tests have been somewhat basic, but I haven't seen any issues so far.

**Comment by sivel** [comment]
I've tested and validated that this does seem to work fine in a fork.  Just as a verification, I confirmed that action plugins are run in a fork based on pid and ppid, and verbosity does work fine in the fork with this change.

The ID of the display instantiated singleton remains the same across all forks.

**Comment by bcoca** [comment]
it won't be the same display singleton, but it matters little since we don't modify verbosity on the forks.

**Comment by bcoca** [comment]
pushed to 2.5 so we can do this with the callback expansion

**Comment by dharmabumstead** [comment]
@bcoca what's up with this one?

**Pull request closed without merging**
