### PR TITLE
Add a 'tower_schedule' module for managing Ansible Tower Schedules

### PR DESCRIPTION
**Pull request by dmsimard**
##### SUMMARY
This adds a tower_schedule module that provides the ability to add
schedules for updating projects and inventory sources as well as running
job templates.

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
tower_schedule

##### ANSIBLE VERSION
devel

### CODE REVIEW

**Comment by dmsimard** [comment]
This is WIP but is in a state ready to get more eyeballs on.

**Comment by AlanCoding** [comment]
I made a PR here that should hopefully address the situation that you have in mind:

https://github.com/ansible/tower-cli/pull/592

This falls short of detecting the case where we do not have a template, and the result action is creation. That would still failing confusingly. However, I think that's validation that might be appropriate for the module to do. If a name is provided, but no template is provided, but the name does not exist, that should be a user error of some type.

**Comment by keilr** [comment]
It would be nice to see this module in Ansible 2.9.

**Comment by ryanpetrello** [comment]
@dmsimard,

Thanks for this PR.

We've recently moved the "Tower modules" into an official AWX collection that now lives at:

https://github.com/ansible/awx
https://galaxy.ansible.com/awx/awx

see: https://groups.google.com/forum/#!searchin/awx-project/collection%7Csort:date/awx-project/pLzVdXFm9is/We2XXLDqCAAJ

If you're still interested in this change, would you mind re-opening a new PR over at https://github.com/ansible/awx/?  If you need assistance, AWX developers are generally available at:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

Thanks!

**Pull request closed without merging**
