### PR TITLE
new module - aws_ses_email_template

### PR DESCRIPTION
**Pull request by wimnat**
##### SUMMARY
New module - aws_ses_email_template

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
aws_ses_email_template

##### ANSIBLE VERSION

```
2.6
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by wimnat** [comment]
shipit

**Comment by wimnat** [comment]
Examples is valid yaml.  Not sure how to bypass the checker on this one.

**Comment by wimnat** [comment]
@willthames @s-hertel hello, do you know a way to get the EXAMPLES check to pass?

**Comment by willthames** [comment]
@wimnat I'd think it's that the docs parsing doesn't use the same YAML parser as Ansible. Using a standard YAML parser, it's clear that it's the `!unsafe` that's the problem:

```
yaml.load(EXAMPLES)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/Users/will/Library/Python/2.7/lib/python/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!unsafe'
  in "<string>", line 6, column 19:
        subject_part: !unsafe "Greetings, {{ name }}!"
```

**Comment by wimnat** [comment]
I could quote it but then of course thats how the example will show which is not correct :/

**Pull request closed without merging**
