### PR TITLE
Ping module fix

### PR DESCRIPTION
**Pull request by ghost**
So I forgot to change the branch in the earlier pull request. I will close it. Please accept this pull request for both - the mount module and the ping module.

Im sorry with all this confusion. Git does not have a nice way of pulling upstream changes + pull requests. I just learnt that 1 branch can have only 1 pull request

### CODE REVIEW

**Comment by mpdehaan** [comment]
Yep, more of an issue with github than git.   One branch per topic is ideal, and you can delete those branches once they are applied.

**Comment by mpdehaan** [comment]
module.exit_json is good form, using json is not something we want to use directly.

**Comment by mpdehaan** [comment]
I'll have to check and make sure I unfix ping on master, that may have snuck by me.

**Comment by ghost** [comment]
I completely missed that json thing. Sorry about that. Shall I fix it?

**Pull request closed without merging**
