### PR TITLE
Spotinst - updating spotinst_aws_elastigroup module to use spotinst_sdk2

### PR DESCRIPTION
**Pull request by jeffnoehren**
##### SUMMARY
Updating module spotinst_aws_elastigroup to use spotinst_sdk2

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
Module spotinst_aws_elastigroup

##### ADDITIONAL INFORMATION
```paste below
ok: [localhost] => {
    "result": {
        "changed": true,
        "failed": false,
        "group_id": "sig-029815e5",
        "instances": [],
        "message": "Created group Successfully."
    }
}
```

### CODE REVIEW

**Comment by talzur** [comment]
shipit

**Comment by jeffnoehren** [comment]
ready_for_review

**Comment by jeffnoehren** [comment]
bot_broken

**Comment by mattclay** [comment]
bot_status

**Comment by mattclay** [comment]
I've restarted tests since the results were stale.

**Pull request closed without merging**
