### PR TITLE
Added Ansible UTM Module for network aaa entities plus info module.

### PR DESCRIPTION
**Pull request by maunzCache**
##### SUMMARY
This PR will add a new utm info module which allows the management of network aaa entries of the Sophos UTM. Also includes an info module. This module integrates with the existing utm_utils .

##### ISSUE TYPE
* New Module Pull Request

##### COMPONENT NAME
* module/web_infrastructure/sophos_utm/utm_network_aaa.py
* module/web_infrastructure/sophos_utm/utm_network_aaa_info.py

### CODE REVIEW

**Comment by getjack** [comment]
@stearz @RickS-C137 Please help out reviewing :)

**Comment by RickS-C137** [comment]
+1

**Review by MatrixCrawler — APPROVED** [review]

**Comment by MatrixCrawler** [comment]
shipit

**Comment by MatrixCrawler** [comment]
@getjack Please split into two PR. Only one new  module per PR

**Review by MatrixCrawler — CHANGES_REQUESTED** [review]
Please split into to PR's

**Pull request closed without merging**
