### PR TITLE
backport cloudformation fixes to 2.4

### PR DESCRIPTION
**Pull request by tedder**
I think this is the right way to do this. cc @abadger to let me know.

### CODE REVIEW

**Comment by tedder** [comment]
linking #31434 #31135 #31436

**Comment by abadger** [comment]
This looks okay to me to hit 2.4.2.  I've asked @ryansb or @s-hertel to evaluate the risk.  If it's low risk I can put it into 2.4.1.rc3 provided that something else requires a 2.4.1rc3.

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
Looks sufficiently low-risk to be in RC3 if that happens.

**Comment by abadger** [comment]
Cool, @s-hertel also thinks it's low risk.  So I'll put this in the queue to go to 2.4.1rc3 if we have to have one for some other blocker bug.  Otherwise it will go to 2.4.2.

**Comment by tedder** [comment]
Yeah, definitely not a blocker or a driver for another RC, but thanks for putting it in flight.

**Comment by abadger** [comment]
Merged to stable-2.4 for the 2.4.2beta1 release.

**Pull request merged**
