### PR TITLE
initial draft acl module

### PR DESCRIPTION
**Pull request by bcoca**
please try to break, works for querying and setting ACLs on files.

Signed-off-by: Brian Coca <briancoca+dev@gmail.com>

### CODE REVIEW

**Comment by mpdehaan** [comment]
in queue for testing, sorry for delay thanks!   This will be nice to have!

**Comment by jimi-c** [comment]
I'm a little confused about this one. The description says the getfacl/setfacl binaries are required, but the code is requiring pylibacl? It would be nice if we didn't require yet another library for this, and it used the binaries when available if the python library was not there.

**Comment by bcoca** [comment]
sorry, wrote the docs before I wrote the module. I tried using the binaries
but getting the check mode and 'changed' was getting very onerous.

I can always give it another stab.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jimi-c** [comment]
No problem. One other thing I noticed is that the .valid() check fails on your examples because a mask entry must exist if you add user entries (the CLI setfacl creates those automatically). I'm guessing that should be an additional check or it should be created automatically like setfacl does.

**Comment by jimi-c** [comment]
I forgot to mention two other small programming errors I ran across:

<pre>
diff --git a/library/files/acl b/library/files/acl
index a95a032..77bc627 100644
--- a/library/files/acl
+++ b/library/files/acl
@@ -91,7 +91,7 @@ def main():
     if entry is None and state in ['present','absent']:
         module.fail_json(msg="%s needs entry to be set" % state)
 
-    if entry.count(":") != 3:
+    if entry and entry.count(":") != 2:
         module.fail_json(msg="Invalid entry: '%s', it requires 3 sections divided by ':'" % entry)
 
     changed=False
@@ -145,7 +145,7 @@ def main():
 
     if changes > 0:
         if not newacl.valid():
-            module.fail_json("Invalid acl constructed: %s" % newacl.to_any_text())
+            module.fail_json(msg="Invalid acl constructed: %s" % newacl.to_any_text())
         if not module.check_mode:
             newacl.applyto(path)
         changed=True
</pre>

**Comment by bcoca** [comment]
hmm, I must have missed the .valid from previous iterations creating the mask by default, I'll try to get a fix tonight.

**Comment by bcoca** [comment]
I can flatten if needed

**Comment by bcoca** [comment]
just a reminder this thing still exists

**Comment by jctanner** [comment]
Brian,

I ran into a problem with slighty older version of getfacl where -c and -p short options do not exist. Could you alter your code slightly to accommodate this?

Example ...

<pre>
jtanner@u1304:~/ansible.acl/library/files$ git diff
diff --git a/library/files/acl b/library/files/acl
index 458a49d..1b50d21 100644
--- a/library/files/acl
+++ b/library/files/acl
@@ -70,7 +70,8 @@ def get_acl(module,path,entry,follow):
     if not follow:
         cmd.append('-h')
     # prevents absolute path warnings and removes headers
-    cmd.append('-cp')
+    cmd.append('--omit-header')
+    cmd.append('--absolute-names')
     cmd.append(path)
 
     return _run_acl(module,cmd)
</pre>

Other than that, I'm ready to merge this.

**Comment by bcoca** [comment]
done

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Merged, thank you!

**Comment by mpdehaan** [comment]
Will update this shortly for minor docs things like "version added is 1.4".

Thanks!

**Pull request merged**
