### PR TITLE
Removed sorting to preserve original order

### LINKED ISSUE #73047: ansible-inventory ignores inventory order and returns hosts sorted by name
##### SUMMARY
_ansible-inventory_ ignores inventory order and returns hosts sorted by name 

_ansible-inventory_ is very convinient to quickly have a look on the inventory, it is very handy when reviewing complex inventories based on many inventory files, scripts and group_vars.

It matters when chronological hosts order (sort by creation time) is more important then names and for projects using group position in patterns, example: groups['servers'][0] as often used for services like grafana and prometheus 

I'd like to use the ansible-inventory command to quickly review inventories and ocassionally use the output for executing predictable tests.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-inventory

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```
```paste below
ansible 2.9.16
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```
```paste below
ansible 2.5.0
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

ansible 2.5.0
  python version = 2.7.12 (default, Oct  5 2020, 13:56:01) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Linux

##### STEPS TO REPRODUCE

ansible --list-hosts all -i host02,host03,host01
```
  hosts (3):
    host02
    host03
    host01
```

ansible-inventory --list all -i host02,host03,host01
```
{
    "_meta": {
        "hostvars": {
            "host01": {},
            "host02": {},
            "host03": {}
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "host01",
            "host02",
            "host03"
        ]
    }
}
```
##### EXPECTED RESULTS

_ansible-inventory_ shows Ansible inventory information, the order provided in the inventory (default). 
[Ordering execution based on inventory](https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html#ordering-execution-based-on-inventory)

##### ACTUAL RESULTS

_ansible-inventory_ command ignores inventory order and returns ordered hosts

### PR DESCRIPTION
**Pull request by bcoca**
fixes #73047

##### ISSUE TYPE

- Bugfix Pull Request
-

##### COMPONENT NAME

ansible-inventory

### CODE REVIEW

**Comment by samdoran** [comment]
I can see how this would potentially need split controller, but the tests running on Python 3.6 and 3.8 are failing. That indicates it may not be the different Python versions causing test failures.

**Comment by bcoca** [comment]
hmm, might be missing another factor, since locally on >=3.8 i do get a reproducible order and only by going to lower python can i get 'randomized' order

**Comment by AlanCoding** [comment]
:+1: I believe the result with this patch would be _much more_ correct than what we get today.

**Comment by jrgoldfinemiddleton** [comment]
Thank y'all for this one.

**Pull request merged**
