### PR TITLE
Allow for the specification of a rhsm_repo_ca_cert if changing baseurl

### PR DESCRIPTION
**Pull request by dodwmd**
If changing the baseurl we should allow for a ca cert to be updated from redhat-uep.pem

### CODE REVIEW

**Review by mkrizek — COMMENTED** [review]
I don't understand how this could work though? How does the option get passed into `subscription-manager`? There is even no such CLI option for it, at least on my testing CentOS 7 instance. Can you clarify? Thanks!

**Comment by dodwmd** [comment]
The configure function of the playbook takes anything with rhsm and
replaces the first underscore with a period, turning rhsm_repo_ca_cert to
rhsm.repo_ca_cert. This option is available in RHEL, I don't have access to
CentOS I would of assumed it also had this option.

**Comment by mkrizek** [comment]
@dodwmd not sure how I missed that :disappointed: Can you fix the issues mentioned in the comment by ansibot above? Thanks!

**Comment by dodwmd** [comment]
@mkrizek done

**Comment by mkrizek** [comment]
Thanks @dodwmd!

**Comment by mkrizek** [comment]
rebuild_merge

**Pull request merged**
