### PR TITLE
hostname - set name correctly on OracleLinux 

### LINKED ISSUE #48752: hostname module incorrect behavior on Oracle Linux
##### SUMMARY
To edit hostname in Oracle Linux 7, use either of following methods:

1. use hostname control utility: hostnamectl
2. use NetworkManager command line tool: nmcli
3. edit /etc/hostname file directly (a reboot afterwards is required)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hostname module

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /home/IAMERS/nasnyder/.ansible.cfg
  configured module search path = [u'/home/IAMERS/nasnyder/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/IAMERS/nasnyder/.ansible.cfg) = [u'/home/IAMERS/nasnyder/hosts']
DEFAULT_MANAGED_STR(/home/IAMERS/nasnyder/.ansible.cfg) = Ansible managed
DEFAULT_PRIVATE_KEY_FILE(/home/IAMERS/nasnyder/.ansible.cfg) = /home/IAMERS/nasnyder/.ssh/bec-admin_id.rsa
DEFAULT_ROLES_PATH(/home/IAMERS/nasnyder/.ansible.cfg) = [u'/home/IAMERS/nasnyder/src/Ansible/roles']
DEFAULT_TIMEOUT(/home/IAMERS/nasnyder/.ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/IAMERS/nasnyder/.ansible.cfg) = 60

```

##### OS / ENVIRONMENT

Target OS is Oracle Linux 7

##### STEPS TO REPRODUCE

To edit hostname in Oracle Linux 7, use either of following methods:

1. use hostname control utility: hostnamectl
2. use NetworkManager command line tool: nmcli
3. edit /etc/hostname file directly (a reboot afterwards is required)

The hostname module appears to utilize the RedHatStrategy strategy class.  The RedHatStrategy class attempts to set the hostname via editing /etc/sysconfig/network.  

This current strategy of setting the hostname via /etc/sysconfig/network for Oracle Linux 7 hosts is undesired and unreliable.  Currently have to code around OL7 hosts due to issues/limitations of the "hostname" module.

```yaml
- hostname:
    name: myserver.fqdn.com

```

##### EXPECTED RESULTS

Expect the hostname module to correctly set the hostname as desired for Oracle Linux 7.  Suggesting using hostnamectl (any of the three methods provided).

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by VictorCovalski**
##### SUMMARY

Fixes #48752

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by VictorCovalski** [comment]
Hi @anotherjesse. Could you please review my PR?

Please let me know if it needs more work.

**Review by samdoran — CHANGES_REQUESTED** [review]
Rather than making changes to the `RedHatStrategy` class, Oralce Linux specific changes should be made in the `OracleLinuxHostname` class.

**Comment by sivel** [comment]
We likely don't want to change the strategy at all, nor create a new one.  There is a line that will use the `SystemdStrategy` if the platform is `Linux` and our facts dictate that it's managed by systemd.

There is likely some more nuanced issue here, that needs resolved.

**Comment by VictorCovalski** [comment]
Thanks for the feedback @samdoran and @sivel.

What would you recommend @sivel? I'm new to open source and Ansible so I might need some guidance before developing an appropriate sollution.

**Comment by sivel** [comment]
This code here should prefer `SystemdStrategy` for hosts managed by systemd:

https://github.com/ansible/ansible/blob/ac0dedda72d605a2240ee99d05a5cecbd25cd80e/lib/ansible/modules/hostname.py#L149-L155

If that is not working, then there must be something there, or something here that isn't working:

https://github.com/ansible/ansible/blob/ac0dedda72d605a2240ee99d05a5cecbd25cd80e/lib/ansible/module_utils/facts/system/service_mgr.py#L43-L53

**Comment by VictorCovalski** [comment]
@sivel  the code you mentioned works as expected on OracleLinux 7 with the default strategy. Just verified it with the following steps.

1. Set up a test environment with Vagrant
```bash
vagrant init oraclelinux/7 https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json
vagrant up
```

2. Create an ansible playbook
playbook.yml
```yml
- name: update hostname
  hosts: default
  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
      name: web02
    become: yes
    debugger: always
```

3. Run ansible
```bash
ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -i inventory --private-key .vagrant/machines/default/virtualbox/private_key -u vagrant playbook.yml -vvv
```

4. Follow the steps on [Debugging](https://docs.ansible.com/ansible/latest/dev_guide/debugging.html)
5. Insert a print statement inside the if statement where platform and systemd are validated to confirm SystemdStrategy is used.

Please let me know if I made a mistake.

**Comment by samdoran** [comment]
I believe the issue is incorrect and misinterprets the the use of `self.strategy_class`. The module is doing the right thing on OracleLinux. As @sivel pointed out earlier, this line results in the use of the `SystemdStrategy` class. I verified that is what is happening on OL7.

https://github.com/ansible/ansible/blob/7443e9d659e48d8a4096d4f64d4610f38188d405/lib/ansible/modules/hostname.py#L152-L153

The `SystemdStrategy` class uses `hostnamectl`.

https://github.com/ansible/ansible/blob/7443e9d659e48d8a4096d4f64d4610f38188d405/lib/ansible/modules/hostname.py#L406

**Comment by samdoran** [comment]
Closing this since the author of the original issue reports it is actually working correctly (https://github.com/ansible/ansible/issues/48752#issuecomment-819588588).

**Pull request closed without merging**
