### PR TITLE
Fix issue with ssl.wrap_socket not using TLSv1 version by default

### PR DESCRIPTION
**Pull request by swimlappy**
Fix a small issue when doing a URL request to a remote that forces TLSv1 and does not support SSLv2 or v3.  Seems we are doing TLSv1 by default anyway in CustomHTTPSConnection.

### CODE REVIEW

**Comment by bcoca** [comment]
I'm thinking that we might want to make this configurable in ansible.cfg as SSL settings WILL change and different environments might be forced to use more insecure ones than the general public.

**Comment by swimlappy** [comment]
@bcoca That sounds OK to me, it adds more flexibility for future changes.

I've also added in code to have ansible respect the "no_proxy" environment variable.  It was completely ignoring that up to this point.  I work in a heavy proxy environment, so this would pretty much be a requirement for me to get this working.

**Comment by swimlappy** [comment]
@bcoca Is this what you had in mind for an ansible.cfg parameter to set the SSL protocol version? Thanks

**Comment by bcoca** [comment]
yes, thanks a lot

**Comment by bcoca** [comment]
this produces syntax errors, I think you left a few parens ')' out

**Comment by swimlappy** [comment]
Bah my github fork is completely messed up. I'll have to redo this.  Not sure what exactly has happened (lack of git experience probably).

**Pull request closed without merging**
