### PR TITLE
Fix calling deprecate with correct arguments (#44726)

### PR DESCRIPTION
**Pull request by machacekondra**
Backport of https://github.com/ansible/ansible/pull/44726

### CODE REVIEW

**Comment by machacekondra** [comment]
@dagwieers @bcoca @mwperina @zikalino

**Comment by machacekondra** [comment]
CI is failing because of: https://github.com/ansible/ansible/issues/46024

**Comment by machacekondra** [comment]
cc @s-hertel

**Comment by abadger** [comment]
This needs a changelog entry.

**Comment by mwperina** [comment]
Ondro, could you please update changelog and rebase the PR?

Toshio, once changelog is updated, can this be merged and included in 2.7.0GA or anything else is needed?

@machacekondra @abadger

**Comment by machacekondra** [comment]
@abadger Changelog added.

**Comment by abadger** [comment]
@mwperina This is coming in too late for 2.7.0 final but it should make 2.7.1.  I'm rerunning the failed test runs on shippable to make sure this isn't the cause of those test failures.

**Comment by abadger** [comment]
Merged to stable-2.7 for the 2.7.1 release.

**Pull request merged**
