### PR TITLE
Set fetch_url() as optionally injectable into aci.py 

### PR DESCRIPTION
**Pull request by RobW3LGA**
##### SUMMARY
- Allows ACI modules to be testable

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- Modifies all 'fetch_url()' calls in aci.py to 'self.fetch_url()' 

##### ADDITIONAL INFORMATION
- A mocked fetch_url() allows ACI modules to be properly unit tested
- This change will also allow ACIModule to become testable
- The mocked fetch_url() would be injectable by attaching the method to AnsibleModule. When an ACI module is called, it creates an instance of AnsibleModule and sends it into ACIModule. This process remains the same
- This proposed change does not disrupt current functionality 

Line 121 as scoped under __init__(...) 
```
# Inject fetch_url() if provided
if self.module.fetch_url:
    self.fetch_url = self.module.fetch_url
else:
    self.fetch_url = fetch_url
```

### CODE REVIEW

**Comment by RobW3LGA** [comment]
- Note that the test failure above is not related to any changes to aci.py that I have made:
Failures
 ansible-test / sanity / pep8
 failure: The test `ansible-test sanity --test pep8` failed with 27 errors:
lib/ansible/module_utils/network/aci/aci.py:184:32: E128 continuation line under-indented for visual indent

- I changed aci.py directly from the browser so if this is something I still need to fix, please let me know (I'm not sure how the indentions could be better formatted)

**Comment by RobW3LGA** [comment]
Coming up on three months since this PR and I have module-specific contributions to make pending your decision on this update, please and thanks.

**Comment by dagwieers** [comment]
I am not convinced that the module_utils needs to be modified in order to be Mocked/tested.
This can be easily done from the tests without having to add this kind of support IMO.
None of the other modules/module_utils need this AFAIK.

**Comment by dagwieers** [comment]
@RobW3LGA I am not contesting that it isn't useful, but you can achieve the same thing by replacing `fetch_url` after importing `module_utils/urls.py`. And that works for *every* module/module_utils (and works for other functions, not just `fetch_url()`) without the need to modify them like in this PR.

**Pull request closed without merging**
