### PR TITLE
Modify ansible-connection so the reading side is nonblocking.

### PR DESCRIPTION
**Pull request by Qalthos**
This avoids a hang on data underflow.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ansible-connection

##### ANSIBLE VERSION

```
2..7
```

### CODE REVIEW

**Comment by abadger** [comment]
I'm pretty sure this will still block.  You have to use something like the selectors code in https://gist.github.com/abadger/3c65c3b2d0a8e776bc2b35cd6b45384f#file-receiver-py to make it do the right thing.

The reason is that the pty might not have data available to read yet.  Using a selector allows you to specify how long you want to block for before giving up.  Without a selector, you can end up waiting forever instead.

**Comment by abadger** [comment]
I was wrong about it hanging... instead, it introduces a race where if the writing side doesn't keep the pipe buffer full, the reading side can fail because there's no new data to read.  You can implement your own userspace loop to handle that but this is really what select/poll/epoll (the apis that selectors is built on) are for.  Blocking until either data becomes available or a timeout is reached and then continuing.  By doing it kernel side where the buffers themselves are being written to, they can achieve this more efficiently than we can in userspace code.

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/81856/29/tests

**Comment by Qalthos** [comment]
This needs to be reworked before continuing

**Pull request closed without merging**
