### PR TITLE
Split modules/network into two parts

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
Given the dedicated team we we have working on Ansible Networking a
clearer split is needed between Networking modules and "things that
happen to use the network"

So move some modules into a new directory, e.g.
```
git mv lib/ansible/modules/networking/basics lib/ansible/modules/net_tools
```

Follow up tasks:
* Update ansibot's `MAINTAINERS.txt`
* Create `net_tools` label
* Review all label:networking and move some to net_tools
* Let tanner know once this is live

After this change:
**network**
```
ls -1 network/
a10
aos
asa
avi
bigswitch
citrix
cloudengine
cumulus
dellos10
dellos6
dellos9
eos
f5
fortios
illumos
__init__.py
ios
iosxr
junos
lenovo
netconf
netvisor
nxos
openswitch
ordnance
ovs
panos
sros
vyos
```

**net_tools**
```
find net_tools/
net_tools/
net_tools/nmcli.py
net_tools/ldap
net_tools/ldap/__init__.py
net_tools/ldap/ldap_attr.py
net_tools/ldap/ldap_entry.py
net_tools/cloudflare_dns.py
net_tools/dnsimple.py
net_tools/__init__.py
net_tools/exoscale
net_tools/exoscale/exo_dns_record.py
net_tools/exoscale/__init__.py
net_tools/exoscale/exo_dns_domain.py
net_tools/ipify_facts.py
net_tools/dnsmadeeasy.py
net_tools/ipinfoio_facts.py
net_tools/snmp_facts.py
net_tools/basics
net_tools/basics/uri.py
net_tools/basics/__init__.py
net_tools/basics/get_url.py
net_tools/basics/slurp.py
net_tools/haproxy.py
net_tools/nsupdate.py
net_tools/omapi_host.py
net_tools/lldp.py
```
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
get_url
##### ANSIBLE VERSION
```
2.4.0
```

### CODE REVIEW

**Comment by bjolivot** [comment]
Not sure I understand why F5 and Haproxy are not in the same directory

**Comment by briceburg** [comment]
makes sense. a post-merge output of `ls -1 net_tools/` would also be helpful

shipit

**Review by trishnaguha — APPROVED** [review]

**Comment by gundalow** [comment]
@briceburg Good idea, description updated to show *after* state of `network` and `net_tools`

**Comment by ravibhure** [comment]
👍 shipit

**Comment by nerzhul** [comment]
shipit

**Review by nerzhul — APPROVED** [review]

**Review by privateip — APPROVED** [review]

**Comment by jtyr** [comment]
shipit

**Review by ganeshrn — APPROVED** [review]

**Comment by ahill00** [comment]
shipit

**Pull request merged**
