### PR TITLE
handlers must be run once

### PR DESCRIPTION
**Pull request by stoned**
so remove all occurences of each host from the handlers notified by
lists

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not sure the "[:]" syntax is neccessary here.

Also can you paste a playbook that reproduces the problem?

**Comment by stoned** [comment]
Here is a test plabook, notice how the handler h1 is run twice

``` yaml
---
- name: have a cake ?
  hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - name: t1
      action: command date
      notify:
        - h1

    - name: t2
      action: command ls
      notify:
        - h1

    - name: t3
      action: command uname
      notify:
        - h1

  handlers:
    - name: h1
      action: service name=rsyslog state=restarted
```

**Comment by stoned** [comment]
When a host a send a notify for the same handler multiple times, it is present multiple times in the handler.notified_by list
But the call handler.notified_by.remove(host)  only removes it once.
Then when the flush_handlers is called again, say because of the post_tasks "call", the handler will be called again.

The proposed patch ensure all occurrences of such a host a removed from the handler.notified_by list.
Yes the [:] trick is not essential :-)

**Comment by mpdehaan** [comment]
Ok, got it, this makes it clear, thanks!

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
