### PR TITLE
Add tests filters

### PR DESCRIPTION
**Pull request by obourdon**
##### SUMMARY
This will allow tests to be carried out condtionally if necessary
using regexp include and/or exclude filters
Reorganize imports into alphabetical order for easier insertion

##### ISSUE TYPE
 - Feature Pull Request
 
##### COMPONENT NAME
interfaces_file

##### ANSIBLE VERSION
```
ansible 2.6.0 (work e2aa1155ba) last updated 2018/04/19 09:51:12 (GMT +200)
  config file = None
  configured module search path = [u'/Users/olivierbourdon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/olivierbourdon/Documents/WORK/OpenNext/TECH/CODE/ANSIBLE/0-REF-ansible/lib/ansible
  executable location = /Users/olivierbourdon/Documents/WORK/OpenNext/TECH/CODE/ANSIBLE/0-REF-ansible/bin/ansible
  python version = 2.7.14 (default, Sep 22 2017, 00:06:07) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### ADDITIONAL INFORMATION
None

### CODE REVIEW

**Comment by obourdon** [comment]
@hryamzik could you please have a look this is an easy one which will ease new tests. Many thanks

**Comment by hryamzik** [comment]
LGTM

**Comment by obourdon** [comment]
@hryamzik many thanks for the review

**Comment by obourdon** [comment]
@gundalow could you please review this very easy/basic one an integrate it ? Many thanks

**Comment by obourdon** [comment]
@gundalow  could you please integrate this easy one please. Many thanks in advance

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@obourdon Thank you for the tests
@hryamzik Thank you for the review

**Comment by obourdon** [comment]
@gundalow many thanks for the merge

**Pull request merged**
