### PR TITLE
pam_limits.py: Fixes #49130 Allow negative number on value parameter

### LINKED ISSUE #49130: Pam module incorrectly enforces limitations on "nice" and "priority"
##### SUMMARY

With a stanza like:

```

- name: Add nice limits for mysql
  pam_limits:
    domain: '@mysql'
    limit_type: soft
    limit_item: nice
    value: -20
```

The pam_limits module will return an error:

```
 amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "msg": "Argument 'value' can be one of 'unlimited', 'infinity', '-1' or positive number. Refer to manual pages for more details."}
```

The man page for limits.conf states:

```
All items support the values -1, unlimited or infinity indicating no limit, except for priority and nice.
```

I believe this module should exclude those two from the input verification.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

pam_limits

##### ANSIBLE VERSION

```
ansible 2.7.2
  config file = /Users/apenney/code/ansible/ansible.cfg
  configured module search path = ['/Users/apenney/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov  6 2018, 18:46:03) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/Users/apenney/code/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m
ANSIBLE_SSH_CONTROL_PATH(/Users/apenney/code/ansible/ansible.cfg) = ~/.ssh/ansible-%%r@%%h:%%p
DEFAULT_HOST_LIST(/Users/apenney/code/ansible/ansible.cfg) = ['/Users/apenney/code/ansible/inventory']
DEFAULT_LOG_PATH(/Users/apenney/code/ansible/ansible.cfg) = /Users/apenney/code/ansible/ansible.log
DEFAULT_ROLES_PATH(/Users/apenney/code/ansible/ansible.cfg) = ['/Users/apenney/code/ansible/roles', '/Users/apenney/.ansible/r
DEFAULT_VAULT_PASSWORD_FILE(/Users/apenney/code/ansible/ansible.cfg) = /Users/apenney/code/ansible/.vault_password
HOST_KEY_CHECKING(/Users/apenney/code/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

Using the block from above should be sufficient.

```yaml

```

##### EXPECTED RESULTS

limits.conf updated appropriately :)

##### ACTUAL RESULTS

a sad build failure :(

```paste below

```

### PR DESCRIPTION
**Pull request by giovannisciortino**
##### SUMMARY
Fixes #49130 

As discussed in issue #49130 the module pam_limits doesn't allow to insert negative numbers as values parameter.

Instead for some limit_items (ie: nice, priority ) negative values are valid values (source: man limits.conf ).

This PR change the checks defined in pam_limits.py in order to allow negative number as valid argument for the value parameter.
 
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
pam_limits.py

##### ADDITIONAL INFORMATION
**PLAYBOOK EXAMPLE**
```
$ cat /tmp/tmp.yml 
- hosts: localhost
  become: true
  tasks:
    - name: Add nice limits for mysql
      pam_limits:
        domain: '@mysql'
        limit_type: soft
        limit_item: nice
        value: '-20'
```

**BEFORE PR**
```
$ ./bin/ansible-playbook /tmp/tmp.yml 

PLAY [localhost] *****************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [Add nice limits for mysql] *************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Argument 'value' can be one of 'unlimited', 'infinity', '-1' or positive number. Refer to manual pages for more details."}
	to retry, use: --limit @/tmp/tmp.retry

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0   
```

**AFTER PR**
```
$ ./bin/ansible-playbook /tmp/tmp.yml 

PLAY [localhost] *****************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [Add nice limits for mysql] *************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0   

$ tail -n 1 /etc/security/limits.conf
@mysql	soft	nice	-20
```

### CODE REVIEW

**Comment by apenney** [comment]
While I love that you fixed this in record time (thank you!) are we sure that we want to drop the -1 check for everything other than nice/priority?  Right now this would let me set -2 for other values that won't actually work.

**Comment by giovannisciortino** [comment]
@apenney thanks for your review, I changed the PR.

Now, the following check has been implemented:
-  If  item isn't 'priority' or 'nice', Argument 'value' can be one of 'unlimited', 'infinity', '-1' or positive number
-  If  item is 'priority' or 'nice', Argument 'value' can be an integer included in the range [-20,19]

Furthermore I modified the code related to the parameters "use_max: true" and "use_min: true" to change the logic used. Now if item isn't 'priority' or 'nice', the unlimited values are ['unlimited', 'infinity', '-1'] else there aren't unlimited values.
This change is needed to allow to use the use the value "-1" as a number(and not an unlimited values) when item is 'priority' or 'nice'.

**Comment by gundalow** [comment]
@apenney Could you please rereview this?

**Comment by gundalow** [comment]
@apenney Hi, was wondering if the updates detailed https://github.com/ansible/ansible/pull/49137#issuecomment-442026004 address your concerns?

**Comment by leolchat** [comment]
This code might throw an exception if the provided value is '--5' for example, but it handles priority instead of simply nice compared to #58784.

**Comment by giovannisciortino** [comment]
@leolchat The last commit include the code to manage the exception when the parameter "value" is '--5' is provided.
It show an error like the following:

```
$ ./bin/ansible localhost -b -m pam_limits -a "domain=@mysql limit_type=soft limit_item=nice value=--5"
localhost | FAILED! => {
    "changed": false, 
    "msg": "Argument 'value' doesn't contain a valid value. Refer to manual pages for more details."
}

```

**Comment by leolchat** [comment]
What is the process to get this reviewed / merged ?

**Comment by Akasurde** [comment]
superseded by https://github.com/ansible-collections/community.general/pull/654.

@giovannisciortino Thanks for the contribution.

**Pull request closed without merging**
