### PR TITLE
Add support for adding the intermediate cert

### PR DESCRIPTION
**Pull request by mscherer**
##### SUMMARY

acme-tiny generate certificate without adding add the LE intermediate
certificate, which make several browsers and curl complain.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
openssl_certificate

### CODE REVIEW

**Comment by mscherer** [comment]
This conflict with https://github.com/ansible/ansible/pull/35145 (so I am a bit annyed at myself from adding 2 stuff at the same location, I will adapt the other PR whatever is merged first, but I would prefer this one)

**Comment by MarkusTeufelberger** [comment]
Sorry for approving the other one first.

Why set the default for including intermediary certs to true?

**Comment by mscherer** [comment]
My gut feeling is that most people who would use letsencrypt would use it for https (as the module is using http-01 challenge). And so I suspect most users would also want a chain certificate by default, since otherwise, browsers and curl would complain (and in the case of browser, they might complain in a non immediate way, since in my experience, this happened mostly with fresh profile). I rather have things work out of the box for most users than not. 

On top of that, I am also unsure of a case where --chain would be a issue. It produce a bigger cert, but that's all, so that's why I kept it as a option (but maybe this can be removed). 

I will rebase the commit, and no problem from approving the other, my fault for rewriting the stuff in 3 differents commits.

**Comment by mscherer** [comment]
ready_for_review

**Comment by MarkusTeufelberger** [comment]
shipit

**Pull request merged**
