### PR TITLE
Add example for non-standard python locations

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Add an example inventory entry for using alternative paths for the python interpreter. This is common on *BSD type systems, but can apply to source installations of Python.

I was not 100% on the wording but figured it would be a start and is a non-impacting change to rest of the product.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

Documentation and examples

##### ADDITIONAL INFORMATION

On *BSD systems Python is installed to /usr/local/bin rather than /usr/bin on Linux systems. While the documentation includes it is a bit hidden and this updates an example to make it more obvious. The same information could be used on Linux systems with Python compiled from source where applicable.

### CODE REVIEW

**Comment by acozine** [comment]
Thanks @evitalis for contributing! Starting in 2.8, we're updating the way Ansible searches for Python on target systems - take a look at  https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.8.html#python-interpreter-discovery for details.

**Comment by evitalis** [comment]
@acozine Thank you for the reply but I am a little confused. Do you mean ansible 2.8 will by default also check /usr/local/bin or does the `ansible_python_interpreter` need set to the new value? If the latter would there still be value in this PR but instead of being /usr/local/bin it show the `auto` option ?

**Comment by acozine** [comment]
@evitalis - Ansible 2.8 will by default check to see if it "knows" where Python is installed on the target system. The details of how it does that, and in which order, are complex, so I won't write them out here. But on 2.8 you should not need to set `ansible_python_interpreter` to run against BSD systems. 

You can test this now by running the `devel` branch from GitHub instead of using the latest version (which is currently 2.7) - see https://docs.ansible.com/ansible/devel/installation_guide/intro_installation.html#running-from-source for information on running from source (aka installing a branch from GitHub).

**Comment by evitalis** [comment]
Thanks. When ansible 2.8 releases I can test and follow up. Can this PR remain open until that time in case it still ends up being applicable?

**Comment by acozine** [comment]
@evitalis okay, I'll leave the PR open for now. 

We cut 2.8 alpha1 yesterday, and welcome testing/feedback on it.

**Comment by evitalis** [comment]
@acozine I will test this soon and follow up with you. I didn't get notified of the comment so I apologize for the delay in response.

**Comment by evitalis** [comment]
@acozine Sorry for the delay and thanks for getting 2.8 out. I no longer use OpenBSD but will try and reach out to the maintainer to have them verify when the port is updated.

**Comment by acozine** [comment]
@evitalis thanks for following up! Ansible 2.8.0 went out last Thursday, so we've all been a bit busy here. 😄 If i don't hear anything in a few weeks, I'll close this PR out.

**Comment by evitalis** [comment]
@jasperla current maintainer on OpenBSD. I no longer use the platform so his input is needed here.

**Comment by acozine** [comment]
Closing as not needed. If anyone out there disagrees, feel free to open a new PR or issue with details.

**Pull request closed without merging**
