### PR TITLE
Fixes for python 2.4 support, better collection of riak version.

### PR DESCRIPTION
**Pull request by jsmartin**

### CODE REVIEW

**Comment by mpdehaan** [comment]
"+try: import simplejson as json
+except ImportError: import json"

Please keep imports on their own line here.

**Comment by mpdehaan** [comment]
Indentation and spacing issues:

```
+            if sys.version_info<(2,6,0):
+                stats_raw = urllib2.urlopen(
+                'http://%s/stats' % (http_conn), None).read()
+            else:
+                stats_raw = urllib2.urlopen(
             'http://%s/stats' % (http_conn), None, 5).read()
```

sys.version < (2,6,0)

and make sure to indent the options after the "(" since it's not at the same level as the previous statement.

**Comment by jsmartin** [comment]
Should be all cleaned up now.

**Comment by jimi-c** [comment]
In queue for testing.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
