### PR TITLE
Support for raw JSON values true, false, null, numbers for module JSON args

### PR DESCRIPTION
**Pull request by djmattyg007**
##### SUMMARY
Support for raw JSON values true, false, null, numbers for module JSON args

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
lib/ansible/module_utils/basic.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by abadger** [comment]
Why do we want these raw types?

**Comment by djmattyg007** [comment]
Because they're valid JSON and it's perfectly valid to want to pass them in to parameters of type `json`.

**Comment by bcoca** [comment]
those are valid JSON values, not a JSON type, which should be a valid  JSON serialized string, which should always begin with { or [ .

**Comment by abadger** [comment]
yeah, so far I'm with bcoca on this... But if you have a use-case to tell us about we can see if we should change our minds.

**Comment by djmattyg007** [comment]
They are valid JSON serialized strings. Look at this output from the python2 REPL:

    [djmattyg007@mylaptop ~]$ python2
    Python 2.7.10 (default, May 26 2015, 04:28:58)
    [GCC 5.1.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import json
    >>> json.dumps(True)
    'true'
    >>> json.loads('true')
    True
    >>> json.dumps(3.2)
    '3.2'
    >>> json.loads('3.2')
    3.2
    >>> json.dumps(None)
    'null'
    >>> json.loads('null')
    >>> print(json.loads('null'))
    None

**Comment by sivel** [comment]
@djmattyg007 I think one thing we are missing here, is what the use case is.  Can you provide an example or task that would benefit from this change?

**Comment by bcoca** [comment]
there is a difference between something valid according to the spec and what a parser can handle

**Comment by abadger** [comment]
Note.. I just checked the spec and indeed, although in the original spec, only serialized objects and arrays are valid: https://tools.ietf.org/html/rfc4627, the 2014 specification (still just a draft standard) specifies that JSON values are valid: https://tools.ietf.org/html/rfc7158#page-4

I'm still not sure we want to do this, though the drawbacks I see right away is that it makes strings ambiguous.  We've been treating strings as manually-serialized json but if we handle this then string could also mean, serialize this string as json.  (The difference is that right now we get this is '{"test": "case"}' and give this out: '{"test": "case"}'.  Handling strings as valid toplevels, we might need to output this: '"{\"test\": \"case\"}"'

So we need some actual use cases in order to decide if there's a practical tradeoff that we'd be making here and therefore need to do something about.

**Comment by djmattyg007** [comment]
I'm in the middle of preparing a use-case. I'm hoping to have it ready in the next couple of days.

I must say that I am a bit confused about the whole situation. If raw values aren't valid serialized JSON strings, why do the json decoders and encoders for both python and PHP (possibly others too, but I'm most familiar with these) handle them just fine? Does it even matter what the spec is? I only encountered this issue at all because as a python developer I expected to make full use of the python standard library `json` component and wasn't able to.

Also, given this only affects the `json` argument type (which always results in a valid serialized JSON string being sent through to the module), why does any string handling need to change?

**Comment by bcoca** [comment]
because this is specifically a change to accept other types other than strings that 'serialize correctly' into JSON. Existing plays would be hitting an 'incorrect type' error while your proposal will basically allow for all types (I believe all are valid JSON values).

**Comment by bcoca** [comment]
In any case, if we choose to allow 'anything the underlying serializer allows', I would make this much simpler:

```
try:
    return json.dumps(value)
Except:
    raise TypeError('%s cannot be converted to a JSON string' % type(value))
```

**Comment by djmattyg007** [comment]
If you're worried about backwards compatibility, perhaps we could support the raw types only under a new flag? (`allow_raw_types` for example)

**Comment by abadger** [comment]
Probably a different type instead of a new flag.

**Comment by djmattyg007** [comment]
My use case is for the `jsonmod` module I submitted in #20064. If I have an object with several settings, like this:

    {
        "settings": {
            "setting1": true,
            "setting2": 2.0,
            "setting3": 4,
            "setting4": null
        }
    }

It would be nice to be able to do the following:

    - name: Update settings
      jsonmod:
        data_json: "{{ item.data }}"
        json_path: "settings.{{ item.path }}"
        path: "/path/to/settings.json"
      with_items:
        - { data: 5.5, path: "setting2" }
        - { data: null, path: "setting3" }

Right now, I'd have to do this:

    - name: Update settings
      jsonmod:
        data_json: {"setting1": true, "setting2": 5.5, "setting3": null, "setting4": null}
        json_path: "settings"
        path: "/path/to/settings.json"

And then I risk clobbering other settings I didn't actually want to set using ansible.

**Comment by bcoca** [comment]
have you tried?
```
- name: Update settings
  jsonmod:
    data_json: "{{ item.data|to_json }}"
    json_path: "settings.{{ item.path }}"
    path: "/path/to/settings.json"
  with_items:
    - { data: 5.5, path: "setting2" }
    - { data: null, path: "setting3" }
```

**Comment by djmattyg007** [comment]
I've finally had a chance to test using the `to_json` filter, and it does make it work. I don't understand why though. Nor do I understand why it should be necessary. IMO it's a usability problem.

**Comment by djmattyg007** [comment]
Is anyone able to explain why the `to_json` filter makes things work as desired?

**Comment by bcoca** [comment]
@djmattyg007  because JSON is a subset of YAML and JSON overlaps with python. 

Since both YAML and Ansible attempt to conserve typing, specifically with lists ( [1,2,3]) and dictionaries ( { "a": "b" } ) this creates a conflict.  

When indicating to ansbile/jinaj2 that you actually want a string with JSON in it (to_json) we can bypass the 'type discovery' and not tamper with it, giving you the desired result in this case. This used to be the default but it created many issues as people expected the lists/dictionaries to remain as such.

I hope that explains it.

**Comment by djmattyg007** [comment]
Where does the type discovery happen within the ansible codebase?

**Comment by calfonso** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. Our reasons for this are:

Based upon the previous comments in the review, we are closing this PR. Let us know if you want to have more discussion on the topic.

However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

https://groups.google.com/forum/#!forum/ansible-devel
In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Pull request closed without merging**
