### PR TITLE
Added shell out errors

### PR DESCRIPTION
**Pull request by Shaps**
updated functions to call self.reporter.error, added codes to doc page

##### SUMMARY
Addresses #18181. Added methods to check for subprocess.Popen and os.call

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`validate-modules`

##### ANSIBLE VERSION
N/A

### CODE REVIEW

**Review by dharmabumstead — APPROVED** [review]
Doc updates OK. Core team devs, please review.

**Comment by mattclay** [comment]
Longer term I'd like to use pylint to check for these kinds of things, but this works OK in the short term.

**Comment by dharmabumstead** [comment]
Closing this one. Feel free to rebase and reopen.

**Comment by Shaps** [comment]
If this is still considered of use I'll reopen a new one instead of rebasing this branch which has gone too far behind

**Comment by abadger** [comment]
@shaps I talked to @mattclay and he says go ahead and open a new PR.  He does want it; just got behind on reviewing it.  One note review note he had was that we should use the ignore.txt file instead of hard-coding the whitelist into validate-modules.

**Pull request closed without merging**
