### PR TITLE
Modify flask_control for vmware_host test suites

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
Fix adds additional helper methods to get information about
host system from vcsim

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
test/utils/docker/vcenter-simulator/flask_control.py

##### ANSIBLE VERSION

```
2.4devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @jctanner

**Comment by mattclay** [comment]
Why is this needed?

**Comment by jctanner** [comment]
@mattclay I think this is a precursor to enable testing on the vmware_host module.

**Comment by mattclay** [comment]
What host name information does this return? If it's the host name of the simulator container, that may cause problems with the tests, depending on how they're executed.

**Comment by jctanner** [comment]
@mattclay it's the host information of the fake esx machines inside vcsim.

**Comment by mattclay** [comment]
That shouldn't be an issue then.

**Pull request merged**
