### PR TITLE
Pep8 fixes for opendj_backendprop_*

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* PEP8 Fixes
* Refactor module params check

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/modules/identity/opendj/opendj_backendprop.py

##### ANSIBLE VERSION
```
2.4 devel
```

### CODE REVIEW

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
ready_for_review

**Comment by dj-wasabi** [comment]
shipit

**Comment by Akasurde** [comment]
ready_for_review

**Comment by Akasurde** [comment]
ready_for_review

**Comment by dj-wasabi** [comment]
shipit

**Review by gundalow — APPROVED** [review]

**Comment by Akasurde** [comment]
@dj-wasabi @gundalow Thanks for reviews and merge.

**Pull request merged**
