### PR TITLE
Add vault version 1.2 details

### PR DESCRIPTION
**Pull request by skyscooby**
Adding some details on the version 1.2 vault format assists in understanding how labelled vault-id works.

+label: docsite_pr

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alongchamps** [comment]
Reviewed during PR day, looks clear to me.

**Review by jamescassell — APPROVED** [review]
shipit

Thanks for adding these details.  I wonder if this `Vault Format` section belongs in the developer section rather than the user_guide, but with a link from here.

**Comment by acozine** [comment]
rebuild_merge

**Comment by acozine** [comment]
Thanks @skyscooby for updating this documentation!

**Pull request merged**
