### PR TITLE
document the "idempotence by md5 hash" of copy

### PR DESCRIPTION
**Pull request by max-l**

### CODE REVIEW

**Comment by max-l** [comment]
I had opend an issue to implement this behavior before knowing it was already implemented : https://github.com/ansible/ansible/issues/5824#issuecomment-33643545

**Comment by mpdehaan** [comment]
Unrelated note to us: looks like the note before should just mention the synchronize module now too.

**Comment by mpdehaan** [comment]
I think we don't need an extra note here on this particular parameter because it's documented with the "force" parameter.

**Comment by max-l** [comment]
The documentation for the "force" param does not say **how** the diff is done. The user experience is improved when you don't have to guess (or hope) that the comparison is not done by brute force.

**Pull request closed without merging**
