### PR TITLE
Implement AND'd filters in ec2.py/ini

### PR DESCRIPTION
**Pull request by tgerla**
##### SUMMARY
This extends the EC2 inventory source filtering syntax to include "&" for ANDing filters together, as suggested by @cchurch a few days ago: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/CV4kOYyw6oU/-SHNI0_hSs0J

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
plugins/inventory/ec2.ini
plugins/inventory/ec2.py

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by memelet** [comment]
Excellent improvement. Working great so far!

**Comment by memelet** [comment]
When I run the script via a soft link, it does not find the ec2.ini file in the link's directory. Is there way for this to work with a link so I don't have to copy ec2.py to inventory/{ops,staging,production}?

**Comment by tgerla** [comment]
Sure, you can set the EC2_INI_PATH environment variable to point to the ec2.ini file's correct location. thanks for testing!

**Comment by blackjid** [comment]
:+1:

**Comment by ckonkel** [comment]
SO is this going to be integrated?? Really useful!

**Comment by aioue** [comment]
Related: #14901

**Comment by pporada-gl** [comment]
Manually merging in this branch works for me.

**Comment by dustyketchum** [comment]
just a warning, using the ec2.py in this commit works as expected to filter inventory, but it breaks the hosts restrictions in playbooks w/ ansible 2.1.1.0 and 2.2.0.0 - 'all' is the only hosts restriction that seems to function, anything else I've tried results in zero hosts

**Comment by jctanner** [comment]
bot_status

**Comment by bcoca** [comment]
I would actually wait for this ansible/proposals#41 now, one of the things we want to add is 'use jinja2 expression as group definition'

**Comment by nicolas-g** [comment]
+1

**Comment by ckonkel** [comment]
Waiting on this to make it in! When? Is there an issue with this approach??

**Comment by tgerla** [comment]
Sorry everyone, I am no longer doing much Ansible work and don't have time to integrate this with the latest codebase. I hope someone finds it useful and adopts it!

**Comment by odedpriva** [comment]
This (very important) enhancement is working for me.

**Comment by mkrizek** [comment]
Taking over in https://github.com/ansible/ansible/pull/30272. Thanks @tgerla!

**Pull request closed without merging**
