### PR TITLE
 	Implement the 'always_run' task keyword which allows one to execute a task even in check mode

### PR DESCRIPTION
**Pull request by stoned**
Please note that this pullup would require my pullup #3389 to be merged cleanly.
Thanks !

### CODE REVIEW

**Comment by srgvg** [comment]
What is the use case for this?

**Comment by stoned** [comment]
It  allows you to write a fact gathering task, with the help of the register keyword, that could be used in other tasks conditions (when keywords) with the added bonus to be accurate in check mode.
To write such a fact gathering task you will also probably want to use the ignore_errors and even ignore_changed keywords.

**Comment by srgvg** [comment]
+1, though this can be a dangerous option

**Comment by stoned** [comment]
I tweaked this to make it independent of #3389 -> PR in  #3522 
Thanks.

**Pull request closed without merging**
