### PR TITLE
Fix integration test error for Azure devtestlab

### PR DESCRIPTION
**Pull request by mmyyrroonn**
##### SUMMARY

Because the behavior change of the Azure devtestlab service, the integration test will fail. Discussed with the service team to double-check and fix the integration test file to unblock the CI test.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_devtestlab

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
review_need

**Comment by MyronFanQiu** [comment]
@zikalino @yungezz @yuwzho Please review this PR when you have time! A PR with same content has been merged into the [azure_preview_modules](https://github.com/Azure/azure_preview_modules/pull/281) repo.

**Comment by yungezz** [comment]
The change itself looks good. Just to double confirm, does this change need any module change/sample change?

**Review by yungezz — APPROVED** [review]

**Comment by MyronFanQiu** [comment]
> The change itself looks good. Just to double confirm, does this change need any module change/sample change?

Yes. After the service team changing the behavior, I think `policy_set_name` field is useless in the `azure_rm_devtestlabpolicy.yml`.  Because the error log is `Error creating the Policy instance: Azure Error: CannotCreateAPolicyUnderNonDefaultPolicySet\nMessage: Policies can only be created under the default policy set.`.
I think we can create another PR to delete this one, but it will bring breaking change. The devtestlab SDK doesn't support multi-API versions. Or I can adjust the documentation and EXAMPLES to guide users fit into the new service behavior.

**Comment by Fred-sun** [comment]
@MyronFanQiu Now what do you do with PR? Waiting for the review or do you need to update the document? Thank you!

**Comment by Fred-sun** [comment]
@MyronFanQiu @Yungezz As for the change with this PR, if there is no other objection, it should be merged, please confirm again. Thank you very much!

**Comment by Fred-sun** [comment]
@yungezz @zikalino The PR change is very small and has been approved. It should be able to be merge, please confirm, thank you!

**Review by yungezz — APPROVED** [review]

**Pull request merged**
