### PR TITLE
Jinja2 filter lookup plugin

### PR DESCRIPTION
**Pull request by jhoekx**
This implements custom jinja2 filters as a lookup plugin as discussed in #1503 .

This is based on #1502 .

Example usage:

```
  - action: template src=templates/jinja2_filters.txt dest=/tmp/jinja2_filters.txt
    with_filters:
    - src=library/custom_filters.py name=generate_uuid
    - src=library/custom_filters.py name=generate_answer
```

### CODE REVIEW

**Comment by jhoekx** [comment]
The last commit makes things like this possible:

```
  - action: template src=templates/jinja2_filters.txt dest=/tmp/jinja2_filters-$item.txt
    with_filters:
    - src=library/custom_filters.py name=generate_uuid
    - src=library/custom_filters.py name=generate_answer
    with_items:
    - item1
    - item2
```

It's a larger change, so please review it carefully.

**Comment by mpdehaan** [comment]
Dislike syntax immensely, all filter plugins should just be available automatically without needing a with.

-- Michael

**Comment by jpmens** [comment]
Considering it's really advanced-type stuff it's not really hideous, I find.
Isn't this a Catch-22-type situation: template must use filter name which isn't yet defined? Would a solution be to load all filters (*.py) found in a particular directory? No idea what that does for performance etc. Or load globbed filters configured with ansible.cfg?

**Comment by jhoekx** [comment]
The other lookup plugins work the same way, no? I wrote 1. magically load filters (see ML) 2. an action plugin (#1503) and now 3, this, because you wanted a lookup plugin. I don't care much about the syntax as long as my template remains pure jinja. We've had plenty of templating performance issues in the past and this and the action plugin won't slow it down further.

In the previous PR you talked about using $LOOKUP, care to explain how that would work in this situation as I can't find anything about it anywhere.

**Comment by dhozac** [comment]
I don't think lookup plugins (including $LOOKUP) in any way should be related to Jinja2 filters. I think the action plugin in #1503, or just loading them all from some set directory, is the way to go.

**Comment by jhoekx** [comment]
For reference, loading from a [directory](https://github.com/jhoekx/ansible/commit/a0efc386ee98fba2c417820696f83b751475b3b9).

**Comment by mpdehaan** [comment]
No.  Will explain later, it can be done much more cleanly.

-- Michael

**Comment by mpdehaan** [comment]
We are crossing streams, open a thread on the list please.

-- Michael

**Pull request closed without merging**
