### PR TITLE
Add session_role to postgresql modules

### LINKED ISSUE #43592: PostgreSQL: Execute SQL with an elevated role
##### SUMMARY
I would like to be able to use a different (PostgreSQL) role to execute my SQL statements than the PostgreSQL `login_user`.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

postgresql_db
postgresql_ext
postgresql_lang
postgresql_privs
postgresql_schema
postgresql_user

## DETAILS
I'd like to be able to execute a playbook as the currently logged in user, but execute the SQL as an elevated user. This would enable (at least) the following:

* auditing of who did what when
* no shared credentials for high privileged users

As an example, this is what I'd like to be able to do:

```sql
CREATE USER login_user1 LOGIN;
CREATE USER login_user2 LOGIN;
GRANT postgres TO login_user1;
GRANT postgres TO login_user2;
```

Then, as `login_user1`, I can do the following:
```sql
SET ROLE postgres;

CREATE USER application_user;
CREATE DATABASE application_database OWNER application_user
```

The mechanism would be similar to the `become_user`, however reusing that parameter may be confusing, so I'm currently proposing `role` (or `session_role`, or `become_role`).

I'm looking for feedback on whether this is a desirable thing and what caveats I should be looking at. A current - not validated - patch that is a first draft of the implementation looks like this:

```diff
--- a/lib/ansible/modules/database/postgresql/postgresql_ext.py
+++ b/lib/ansible/modules/database/postgresql/postgresql_ext.py
@@ -38,6 +38,9 @@ options:
     description:
       - Host running the database
     default: localhost
+  role:
+    description:
+     - The PostgreSQL role to use for executing the commands
   port:
     description:
       - Database port to connect to.
@@ -75,6 +78,7 @@ else:

 from ansible.module_utils.basic import AnsibleModule
 from ansible.module_utils._text import to_native
+from ansible.module_utils.database import pg_quote_identifier


 class NotSupportedError(Exception):
@@ -133,6 +137,7 @@ def main():
     db = module.params["db"]
     ext = module.params["ext"]
     state = module.params["state"]
+    role = module.params["role"]
     changed = False

     # To use defaults values, keyword arguments must be absent, so
@@ -160,6 +165,12 @@ def main():
     except Exception as e:
         module.fail_json(msg="unable to connect to database: %s" % to_native(e), exception=traceback.format_exc())

+    if role:
+        try:
+            cursor.execute('SET ROLE %s' % pg_quote_identifier(role, 'role'))
+        except Exception as e:
+            module.fail_json(msg="Could not switch to role %s: %s" % (role, to_native(e)), exception=traceback.format_exc())
+
     try:
         if module.check_mode:
             if state == "present":
```

### PR DESCRIPTION
**Pull request by feikesteenbergen**
This fixes #43592

### CODE REVIEW

**Review by dschep — APPROVED** [review]
LGTM

**Comment by feikesteenbergen** [comment]
Pushed a rebased patch, no other changes made to the Pull Request

**Comment by Dorn-** [comment]
LGTM, just need to fix the tests

**Comment by mattclay** [comment]
CI failure in integration tests:

https://app.shippable.com/github/ansible/ansible/runs/99154/37/tests
https://app.shippable.com/github/ansible/ansible/runs/99154/38/tests

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/101411/38/tests

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Review by kostiantyn-nemchenko — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
bot_status

**Comment by andytom** [comment]
shipit

**Comment by kostiantyn-nemchenko** [comment]
bot_status

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
shipit

**Pull request merged**
