### PR TITLE
Customisable chunk_size for maven_artifact

### PR DESCRIPTION
**Pull request by jurajseffer**
##### SUMMARY
Since the module implements chunking, it should be customisable. The hard coded default of 8192 isn't optimal for all cases, higher values can produce faster and more reliable downloads.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
`maven_artifact`

### CODE REVIEW

**Comment by turb** [comment]
Thanks, looks like a good idea, however BTW shouldn't we use the high-level function `shutil.copyfileobj` instead of our own low-level `_write_chunks` function, as `get_url` does?

...furthermore I see `get_url` does not set the `length` parameter on `shutil.copyfileobj` (see [documentation](https://docs.python.org/3/library/shutil.html)) and nobody complains about it. Is there something specific in `maven_artifact` that makes tweaking the chunk size a game changer running battlefield playbooks?

**Comment by jurajseffer** [comment]
@turb thanks for your review. The main use case we have for this change is to workaround a module failure problem with this module. We have an unreliable artifact storage that tends to randomly time out. I was getting intermittent module failure with exit code 0. I suspect some sort of failure of the storage being the culprit but `maven_artifact` not handling it properly during chunked download and returning an incomplete module response to Ansible while shutting down cleanly with rc 0. The module failure was about not having start of JSON in the module output, it only contained incomplete set of "Downloading x out of z%" output.

Perhaps your suggestion would alleviate the problem by using a better method that could properly detect a timeout/disconnect etc? However, I'd still like this change merged as an immediate step, with function replacement being second. BTW, are there no tests for this module?

**Comment by turb** [comment]
Thanks for your answer. Yes, looks like the `_write_chunks` function does not handle errors properly - that's the root cause it seems. There must be a way to fix it using the appropriate Python pattern but I think we should use a standard library like `shutil` to do it for us, as it is done in the much more used `get_url` module.

If you really need this code in your playbook right now, maybe you can drop the modified `maven_artifact` in your `library` directory for now?

@tumbl3w33d what do you think? I may try to patch the code with `shutil.copyfileobj` but cannot predict when.

BTW: yes it's a pity this module has no tests. Someone should...

**Comment by jurajseffer** [comment]
@turb yes I'm already using my customised version. My worry is that we could have chunk_size param in 2.7 as changing the fetching mechanism, while there are no tests, may take much longer. It should be customisable anyway.

**Comment by turb** [comment]
For consistency across modules, also poke @jpmens to know if he thinks it would make sense to have a `chunk_size` param in `get_url`.

**Comment by tumbl3w33d** [comment]
@turb if you find time, of course, why not? :grin: 

And the tests... yeah well, you said it right - someone someday should do something. :sweat_smile:  I was dreaming of integration tests with launching Nexus docker containers, it's just a little bit of work to prepare these containers for several scenarios. I'm not even sure the ansible test setup is ready for something like that or whether it's wanted by the project at all, especially since I heard that in the long run, community modules gonna be removed from the main project and can come in in a plugin fashion.
In worst case it would do to have such test suite available on some public repo so module devs could launch them locally to check for regressions.

It's indeed quite exhausting to reproduce certain scenarios. :sweat:

**Comment by turb** [comment]
@tumbl3w33d my question was more about this PR and the idea to add a chunk size param ;)

**Comment by tumbl3w33d** [comment]
Hehe yeah, I know. I just thought I'd use the opportunity to make you go for setting up a test suite :stuck_out_tongue: 
Nah, my reply "if you find time for it" was mainly a response to your suggestion to implement the `shutil.copyfileobj` option. Seems most elegant me. Not a big fan of the `chunk_size` attribute as it just adds noise to the module's interface and I can't imagine anyone is ever gonna use it, to be honest.

On the other hand... if it helps someone, I can live with it. But why not going with the `shutil.copyfileobj` default then? That would be `16*1024`.

**Comment by tumbl3w33d** [comment]
It just came to my mind, that this should actually be a global ansible configuration that you can set in your ansible.cfg (or per host) and all modules which do stuff like that can use the value. I mean, if you have such special case that you need this, why would you set it in 50 modules and not in one place? :thinking:

**Comment by jurajseffer** [comment]
It almost sounds like we can't do anything unless there are automated tests in place.

**Comment by turb** [comment]
It appears I had some time to look at it, and [the patch is quite simple](https://github.com/turb/ansible/commit/6955c9a06e72f6e215b636c642c7d74196839d8c) - mostly about deleting code, which is often a good thing.

@jurajseffer would it be possible to test [this version](https://github.com/turb/ansible/blob/devel/lib/ansible/modules/packaging/language/maven_artifact.py), to see if by any chance `shutil.copyfileobj` correctly manages your issue?

**Comment by jurajseffer** [comment]
@turb thanks, I will give it a try ASAP though I do not have a reproducible test case as the failures were intermittent.

**Comment by jurajseffer** [comment]
@turb I gave it a few runs with your version and didn't see the error. However, I don't have a reproducible test, it's anecdotal :)

**Comment by turb** [comment]
Thanks for testing.

I'll try to work it more, following `get_url`'s lead: have a temp file copied to the target path only if everything checks out. I hope my next message will be about another PR.

**Comment by turb** [comment]
resolved_by_pr 44956

**Pull request closed without merging**
