### PR TITLE
MySQL variables module

### PR DESCRIPTION
**Pull request by banyek**
MySQL variables module for ansible. Can query and set various variables (runtime variables of course) via ansible.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hey thanks for this -- I am curious, does the ini_file module work in this case or in particular is there a special reason this has special management?

Thanks!

**Comment by banyek** [comment]
Nope, this is written to set some variables runtime on servers. 
For example you want to manage a mysql slave failover to switch master with mysql_replication module. 
First, you put the old master to read_only mode, to prevent any writes on it with this module, then you manage the failover, and after this you put the new master to rw mode. 
Or, you just wanna to switch off on all your servers the 'sync_binary_log' like this:
ansible sql-slaves -m mysql_variables -a "variable=sync_binary_log value=0"
etc.
Even you can check the current running variables too.

**Comment by banyek** [comment]
more info here: 
http://ops.kinja.com/mysql-variables-module-for-ansible-1121851799?rev=1376407877

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by banyek** [comment]
woohoo! :dancer:

**Pull request merged**
