### PR TITLE
Add support for volume encryption with EC2

### PR DESCRIPTION
**Pull request by racerpeter**
This is my first PR for ansible-- hoping I didn't **\* it up.

### CODE REVIEW

**Comment by analytically** [comment]
:+1:

**Comment by jimi-c** [comment]
This looks clean and simple enough, however the encrypted option was only added in v2.29.0, so a check for that should be made.

**Comment by racerpeter** [comment]
Just added the change-- did I do that correctly?

**Comment by jimi-c** [comment]
@racerpeter yes and no :) The version_added definitely needed to be there, however it should be set to `1.7`, since that parameter specifies when Ansible added the parameter.

For boto however, there needs to be code in the module to check the boto library version when `encrypted == True`, and to use module.fail_json() to alert the user that their boto library is not current enough to use that feature. The way I'd handle this is:

<pre>
SUPPORTS_ENCRYPTION = hasattr(boto, 'Version') and LooseVersion(boto.Version) >= LooseVersion('2.29.0')
</pre>

(Don't forget to add `from distutils.version import LooseVersion` to the imports section)

You could make this a function (see `library/cloud/ec2` for examples that do it this way) or you could just add it somewhere in the header of the file after the imports. Then:

<pre>
if encrypted and not SUPPORTS_ENCRYPTION:
   module.fail_json(msg="You must use boto >= v2.29.0 to use encrypted volumes")
</pre>

which would go into the main() function. Finally, the call to create_volume() itself should not use that parameter unless it's supported:

<pre>
        try:
            if SUPPORTS_ENCRYPTION:
                volume = ec2.create_volume(volume_size, zone, snapshot, volume_type, iops, encrypted)
            else:
                volume = ec2.create_volume(volume_size, zone, snapshot, volume_type, iops)
</pre>

**Comment by racerpeter** [comment]
Thanks for educating me -- I'll get to work on that!
Peter

**Comment by jimi-c** [comment]
No problem, and welcome to the wonderful world of supporting multiple versions of 3rd party libraries in Python :)

**Comment by racerpeter** [comment]
@jimi-c How does this look?

**Comment by jimi-c** [comment]
You've added the function definition for the encryption check to cloud/ec2, but that needs to go into cloud/ec2_vol. Also, you have an error here:

<pre>
 +import LooseVersion
  from ast import literal_eval
 +from distutils.version
</pre>

That should just be `from distutils.version import LooseVersion` (and also needs to be in ec2_vol).

**Comment by racerpeter** [comment]
My bad-- how about now?

**Comment by jimi-c** [comment]
Thanks, we'll get it into queue to test as soon as possible.

**Comment by birakattack** [comment]
+1

**Comment by analytically** [comment]
:+1:

**Comment by birakattack** [comment]
:+1:

**Comment by jimi-c** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release. During the merge, I squashed it down to a single commit, so closing this manually as GitHub does not pick that up automatically.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by analytically** [comment]
Is support for 'inline' ec2 volumes possible as well?

```
  ec2:
    region: ...
    volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: 50
```

**Pull request closed without merging**
