### PR TITLE
[WIP] Digital Ocean Firewall Rule Management

### PR DESCRIPTION
**Pull request by BondAnthony**
##### SUMMARY

Creation of Digital Ocean firewall rule management module.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/digital_ocean/digital_ocean_firewall.py
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (feature/do-firewalls deb814f8eb) last updated 2018/10/08 06:30:27 (GMT -400)
  config file = /Users/abond/Dev/github/ansible.cfg
  configured module search path = ['/Users/abond/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/abond/Dev/github/ansible/lib/ansible
  executable location = /Users/abond/Dev/github/ansible/bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:14:27) [Clang 9.0.0 (clang-900.0.39.2)]

```

##### ADDITIONAL INFORMATION

Module is currently a work in progress but in it's current state it will create and destroy firewall rules on the Digital Ocean platform.

```paste below

```

### CODE REVIEW

**Comment by kbreit** [comment]
I noticed the PR doesn’t support `state: query`. Any reason?

**Comment by BondAnthony** [comment]
I haven’t had time to finish up the validation condition of checking the users input against the existing rule, line 257. The module in its current state will create and destroy firewalls.

The reason query isn’t supported is because we also have a digital_ocean_firewall_facts module that has already been merged. Docs for the module https://docs.ansible.com/ansible/devel/modules/digital_ocean_firewall_facts_module.html#digital-ocean-firewall-facts-module

**Comment by daraul** [comment]
I got stuck on firewall management for a Droplet I was trying to deploy then manage in one playbook. Running `doctl compute firewall create` with the `shell` module works, but is non-idempotent. I was surprised to find there isn't a `digital_ocean_firewall` module (yet). Looking forward to this being merged.

**Comment by daraul** [comment]
I attempted to test this locally, and was confounded by the comments, and couldn't make heads or tails of it. I couldn't get it to work.

**Comment by BondAnthony** [comment]
@daraul sorry this has been sitting unfinished. I took a look and I think a recent fix is actually causing the problem. I rebased this module off of `devel` and fixed the issue. 

The following should work. Please let me know if you have any issues.

```
---
- hosts: localhost

  tasks:
    - name: DO Firewall
      digital_ocean_firewall:
        name: "nginx-test"
        state: "absent"
        inbound_rules:
          - protocol: "tcp"
            ports: "80"
            sources:
              addresses:
                - "0.0.0.0/0"
        outbound_rules:
          - protocol: "tcp"
            ports: "all"
            destinations:
              addresses:
                - "0.0.0.0/0"
```

**Comment by daraul** [comment]
Ok, I tested the below:

**Comment by alekgr** [comment]
anybody know of the status of the pull.

**Comment by BondAnthony** [comment]
@Alekgr it’s a work in-progress. I’ve been a little occupied with other work and haven’t been able to get back to this. I’m open to someone helping to finish this up.

**Comment by alekgr** [comment]
@BondAnthony understandable. Thank you for fast reply. Do you know it will be ready for 2.10?

**Comment by daraul** [comment]
@BondAnthony I don't mind throwing my hat in, but I need to know what else needs to be done exactly. Never worked on an ansible module before :laughing:

**Comment by Akasurde** [comment]
Hi @BondAnthony, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.digitalocean<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Comment by lucasbasquerotto** [comment]
I changed the file in this pull request so as to allow not only the creation of new rules, but also updates, and to show the correct status (`ok` or `changed`).

File: 

https://github.com/lucasbasquerotto/cloud/blob/0324d4767201b511204bb8582be15121a9f48373/library/digital_ocean_firewall.py

In the tests I did it worked correctly, but I haven't tested all use cases (like load balancers), although it should work because everything is passed together in the requests (it's always done the same way).

I can make a pull request to [ansible-collections](https://github.com/ansible-collections/community.digitalocean), if there's interest.

**Comment by BondAnthony** [comment]
@lucasbasquerotto that would be great thank you!!

**Pull request closed without merging**
