### PR TITLE
ini_file: Add newline between sections

### LINKED ISSUE #29904: ini_file-module does not create empty line between sections in 2.0.0.2
From @my2ndhead on 2016-02-08T19:49:03Z
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

ini_file module
##### ANSIBLE VERSION

2.0.0.2
##### SUMMARY

Compared to 1.9.x the version 2.0.0.2 does not add an empty line between sections. This makes ini-files hard to read.

1.9.x

```
[section1]
key=value

[section2]
key=value
```

2.0.0.2

```
[section1]
key=value
[section2]
key=value
```

Copied from original issue: ansible/ansible-modules-core#2988

### PR DESCRIPTION
**Pull request by bobkarreman**
##### SUMMARY
Fixes #29904 To add newline between sections in ini files

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ini_file

### CODE REVIEW

**Comment by Akasurde** [comment]
CI Failure - 

```
01:12 task path: /private/var/root/.ansible/test/tmp/ini_file-Rk6W_C-ÅÑŚÌβŁÈ/test/integration/targets/ini_file/tasks/main.yml:42
01:12 ok: [testhost] => {
01:12     "ansible_facts": {
01:12         "content1": "\n[drinks]\nfav = lemonade\n\n", 
01:12         "expected1": "\n[drinks]\nfav = lemonade\n"
01:12     }, 
01:12     "changed": false
01:12 }
01:12 Read vars_file 'integration_config.yml'
01:12 
01:12 TASK [ini_file : Verify content of ini file is as expected] ********************
01:12 task path: /private/var/root/.ansible/test/tmp/ini_file-Rk6W_C-ÅÑŚÌβŁÈ/test/integration/targets/ini_file/tasks/main.yml:51
01:12 fatal: [testhost]: FAILED! => {
01:12     "assertion": "content1 == expected1", 
01:12     "changed": false, 
01:12     "evaluated_to": false, 
01:12     "msg": "Assertion failed"
01:12 }
01:12 Read vars_file 'integration_config.yml'
01:12 
```

in https://app.shippable.com/github/ansible/ansible/runs/112386/57/console

Could you please write integration test for this change ? Thanks.

needs_info

**Comment by bobkarreman** [comment]
@Akasurde I adjusted the existing integration test to work with the fix. 

I had some troubles running them locally that's why I just made a PR (sorry) but now I managed.

**Comment by stephenmuss** [comment]
Looks like CI is now passing. This would be nice to have. Is anything preventing it from being merged?

**Review by jamescassell — APPROVED** [review]
shipit

**Comment by bobkarreman** [comment]
@jamescassell Any thing I need to do tho ship this?

**Comment by chadwagoner** [comment]
@Akasurde Anything else needed for this to be merged in?

**Comment by chadwagoner** [comment]
@jamescassell ^

**Pull request closed without merging**
