### PR TITLE
Fix SSH Connection reading problem

### PR DESCRIPTION
**Pull request by iffy**
To fix issue #4917

### CODE REVIEW

**Comment by mpdehaan** [comment]
We absolutely don't want SSH tests in the unit tests, but this in queue to be looked at  and we can possibly cherry-pick the last commit.

Organized live integration tests are of course pending very soon in the main project.

**Comment by iffy** [comment]
@mpdehaan This code doesn't exercise SSH in any way -- please read the code.  It is a unit test for the `select` loop for the subprocess call.  Arguably, the code being tested should be extracted from this SSH code into a reusable, process spawning, output gathering function.

**Comment by jctanner** [comment]
bugfix cherry picked into https://github.com/ansible/ansible/commit/389602b8dda3f9bb8cf189745041e69c77a0fa29

@iffy thank you!

**Comment by iffy** [comment]
@jctanner you're welcome (though it makes me sad to not see the test make it in -- especially for a project that so badly needs tests)

**Pull request closed without merging**
