### PR TITLE
Fixes 17382: Parsing vim/emacs backup files

### LINKED ISSUE #17382: backup files in host_vars override vars.yml
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

host_vars configuration
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/rod/deltoid/servers/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Added vault password file path to ansible.cfg, nothing else.
##### OS / ENVIRONMENT

Arch linux (x86_64)
##### SUMMARY

When reading host_vars, ansible reads vars from a file name "vars.yml~" with priority over a file name "vars.yml". The "vars.yml~" file was created by editing the original file with emacs, which saves the backup by appending a "~" to the filename.
##### STEPS TO REPRODUCE

Create host_vars in a folder as follows:

```
ansible-folder
- host_vars
  - my-server-01
    - vars.yml
        ansible_user: root
        ansible_port: 22
    - vars.yml~
        ansible_user: someone_else
        ansible_port: 9999
```

When connecting to a host (e.g. ansible -i hosts all -m ping), ansible will use the vars saved in vars.yml~.
##### EXPECTED RESULTS

Expected to connect with 'root' on port 22, etc.

```
Using /home/rod/deltoid/servers/ansible/ansible.cfg as config file
SSH password: 
Loaded callback minimal of type stdout, v2.0
<dlt-tx-02> ESTABLISH SSH CONNECTION FOR USER: root
<dlt-tx-02> SSH: EXEC sshpass -d13 ssh -C -vvv -o ControlMaster=no -o ControlPersist=no -o Port=22 -o User=root -o ConnectTimeout=10 -o ControlPath=/dev/null dlt-tx-02 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472954078.5-25255107732476 `" && echo ansible-tmp-1472954078.5-25255107732476="` echo $HOME/.ansible/tmp/ansible-tmp-1472954078.5-25255107732476 `" ) && sleep 0'"'"''
<dlt-tx-02> PUT /tmp/tmpldCjDh TO /root/.ansible/tmp/ansible-tmp-1472954078.5-25255107732476/ping
<dlt-tx-02> SSH: EXEC sshpass -d13 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=no -o ControlPersist=no -o Port=22 -o User=root -o ConnectTimeout=10 -o ControlPath=/dev/null '[dlt-tx-02]'
<dlt-tx-02> ESTABLISH SSH CONNECTION FOR USER: root
<dlt-tx-02> SSH: EXEC sshpass -d13 ssh -C -vvv -o ControlMaster=no -o ControlPersist=no -o Port=22 -o User=root -o ConnectTimeout=10 -o ControlPath=/dev/null -tt dlt-tx-02 '/bin/sh -c '"'"'LANG=en_AU.UTF-8 LC_ALL=en_AU.UTF-8 LC_MESSAGES=en_AU.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1472954078.5-25255107732476/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1472954078.5-25255107732476/" > /dev/null 2>&1 && sleep 0'"'"''
dlt-tx-02 | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "data": null
        }, 
        "module_name": "ping"
    }, 
    "ping": "pong"
}
```
##### ACTUAL RESULTS

Ansible generated an ssh command for the incorrect user/port.

```
Using /home/rod/deltoid/servers/ansible/ansible.cfg as config file
SSH password: 
Loaded callback minimal of type stdout, v2.0
<dlt-tx-02> ESTABLISH SSH CONNECTION FOR USER: someone_else
<dlt-tx-02> SSH: EXEC sshpass -d13 ssh -C -vvv -o ControlMaster=no -o ControlPersist=no -o Port=9999 -o User=someone_else -o ConnectTimeout=10 -o ControlPath=/dev/null dlt-tx-02 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472954135.94-221184064468334 `" && echo ansible-tmp-1472954135.94-221184064468334="` echo $HOME/.ansible/tmp/ansible-tmp-1472954135.94-221184064468334 `" ) && sleep 0'"'"''
dlt-tx-02 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}
```

### PR DESCRIPTION
**Pull request by georgebuckerfield**
##### SUMMARY

Fixes #17382  - stops Ansible from parsing variable files with a `~` suffix and overwriting variables in genuine `.yml` variable files.

For example, given a host_vars directory with the following files:
```
.localhost.yml
localhost.yml
localhost.yml~
```

Only `localhost.yml` will be loaded.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
Ansible Core

##### ANSIBLE VERSION
```
ansible --version
ansible 2.4.0 (fixes-17382-var-backup-files cdf86eb79c) last updated 2017/03/26 08:45:23 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

### CODE REVIEW

**Comment by bcoca** [comment]
this should not be needed as in 592 we exclude files that don't match the expected extensions, but that logic seems to be wrong and the actual culprit.

**Comment by georgebuckerfield** [comment]
Thanks @bcoca - so it looks like that check isn't run if the path is a directory? For example in this scenario:
```
host_vars
  localhost.yml~
```
The file doesn't get parsed. However when it's in a directory:
```
host_vars
  localhost
    vars.yml~
```
It does get parsed. So we could do something like this to run the same extension check when files are loaded from a directory?

```
# do not parse hidden files or dirs, e.g. .svn/
paths = [os.path.join(path, name) for name in names if not name.startswith('.')]
for p in paths:
  file_name, ext = os.path.splitext(p)
  if ext in C.YAML_FILENAME_EXTENSIONS:
    results = self._load_inventory_file(path=p, loader=loader)
    if results is not None:
      data = combine_vars(data, results)
```

I've done a quick test and that seems to work as expected.

**Comment by bcoca** [comment]
the directory parsing calls the same function recursively for each file, which is when that check then applies.

**Comment by georgebuckerfield** [comment]
Ah yes, of course. So it looks like the problem is in the for loop. It's adding the test extension to the full path, not to just the filename (with extension removed). As the first extension in the list of supported extensions is `""`, it will load files with any extension.

So I think we just need to change
```
new_path = path + test_ext
```
To:
```
new_path = file_name + test_ext
```

**Comment by bcoca** [comment]
need to test it, but i believe the following is the correct fix:

```python
diff --git a/lib/ansible/vars/__init__.py b/lib/ansible/vars/__init__.py
index 2f14849f3..0a2b43699 100644
--- a/lib/ansible/vars/__init__.py
+++ b/lib/ansible/vars/__init__.py
@@ -578,15 +578,15 @@ class VariableManager:
         else:
             file_name, ext = os.path.splitext(path)
             data = None
-            if not ext or ext not in C.YAML_FILENAME_EXTENSIONS:
+            if ext in C.YAML_FILENAME_EXTENSIONS:
+                if loader.path_exists(path):
+                    data = loader.load_from_file(path)
+            elif not ext:
                 for test_ext in C.YAML_FILENAME_EXTENSIONS:
                     new_path = path + test_ext
                     if loader.path_exists(new_path):
                         data = loader.load_from_file(new_path)
                         break
-            else:
-                if loader.path_exists(path):
-                    data = loader.load_from_file(path)

         rval = AnsibleInventoryVarsData()
         rval.path = path
```

**Pull request closed without merging**
