### PR TITLE
Inventory CLI - Ignore settings for when vars plugins should run

### LINKED ISSUE #65064: Regression - no longer returning vars plugin host_vars from ansible-inventory
##### SUMMARY
If I have a host with a name like `foo` and have variables inside a file `host_vars/foo.yml` inside of a directory properly passed via `--playbook-dir` to the `ansible-inventory` command, vars from that file are not present in the output.

This used to work. The regression was first seen the night of Nov 4, 2019

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/cli/inventory.py

##### ANSIBLE VERSION
```paste below
ansible --version
ansible 2.10.0.dev0
  config file = /Users/alancoding/Documents/repos/jlaska-ansible-playbooks/ansible.cfg
  configured module search path = ['/Users/alancoding/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/Documents/repos/ansible/lib/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible3/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:23:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION
```paste below
$ ansible-config dump --only-changed
DEPRECATION_WARNINGS(/Users/alancoding/Documents/repos/jlaska-ansible-playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Mac OS

##### STEPS TO REPRODUCE
https://github.com/ansible/test-playbooks/tree/master/inventories

host of interest is `group_one_host_01`

Inventory file: 

```
$ cat inventories/inventory.ini 
ungrouped_host_[01:05]
group_one_host_01 group_one_host_01_has_this_var=True
group_two_host_01 group_two_host_01_has_this_var=True
group_three_host_01 group_three_host_01_has_this_var=True

[group_one]
group_one_host_[01:05]
group_one_and_two_host_[01:05]
group_one_two_and_three_host_[01:05]

[group_one:vars]
is_in_group_one=True
complex_var=[{"dir": "/opt/gwaf/logs", "sourcetype": "gwaf", "something_else": [1, 2, 3]}]

[group_two]
group_two_host_[01:05]
group_one_and_two_host_[01:05]
group_two_and_three_host_[01:05]
group_one_two_and_three_host_[01:05]

[group_two:vars]
is_in_group_two=True

[group_three]
group_three_host_[01:05]
group_two_and_three_host_[01:05]
group_one_two_and_three_host_[01:05]

[group_three:vars]
is_in_group_three=True

[all:vars]
ansible_connection=local
inventories_var=True
```

vars file:

```
$ cat inventories//host_vars/group_one_host_01
group_one_host_01_should_have_this_var: True
```

run:

```
ansible-inventory -i inventories/inventory.ini --list --export --playbook-dir=inventories/ | grep -r "group_one_host_01_should_have_this_var"
```

##### EXPECTED RESULTS
`group_one_host_01_should_have_this_var` should be in the hostvars for `group_one_host_01`

##### ACTUAL RESULTS
The string `group_one_host_01_should_have_this_var` is not seen anywhere in the output.

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Just always run vars plugins for inventory CLI.
Fixes #65064

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/cli/inventory.py

### CODE REVIEW

**Review by AlanCoding — APPROVED** [review]
Checked out branch and confirmed fix according to details in issue

**Comment by s-hertel** [comment]
Perhaps if this only affects tower when --playbook-dir is used, I could limit this change to that scenario. @alancoding Do you know if this behavior is relied on without the --playbook-dir as well?

**Comment by sivel** [comment]
My test case did not depend on `--playbook-dir`, it was all inventory relative.

**Comment by s-hertel** [comment]
@sivel Right. I'm just wondering if the pre-2.10 behavior of ignoring the fact that vars plugins were only on-demand is correct. It definitely makes sense in the case of --playbook-dir though.

**Comment by AlanCoding** [comment]
> Do you know if this behavior is relied on without the --playbook-dir as well?

I don't even think that's possible? The folders `host_vars` and `group_vars` are relevant to the playbook.

We shouldn't ever call it without --playbook-dir, and if we do, I don't think it would be an expectation to have those vars.

**Comment by s-hertel** [comment]
@alancoding I was wondering if tower relies on group_vars and host_vars relative to inventory as well. But I think this is probably best to do regardless. I could see though, that someone might want make ansible-inventory faster by using these settings which is why I feel a little torn about always ignoring the settings.

**Comment by s-hertel** [comment]
Actually... speaking of inventory relative, this is not quite right.

**Comment by s-hertel** [comment]
I think this is more correct now. I'm adding some tests.

**Comment by AlanCoding** [comment]
Is this still a WIP?

**Comment by s-hertel** [comment]
@AlanCoding The vars plugin tests are failing. I was busy with galaxy stuff most of last week but I'm digging into this now. I'm not sure if they're just failing because they were expecting ansible-inventory to support the new options or because I broke something. I'll ask for your review again when I have the tests passing.

**Comment by s-hertel** [comment]
@AlanCoding I believe this is done. Whenever you have some time, if you could test again I'd appreciate it.

**Review by AlanCoding — APPROVED** [review]
re-tested just now and it works

**Comment by s-hertel** [comment]
Thanks for testing @AlanCoding!

**Pull request merged**
