### PR TITLE
collection: Provide additional info about collection name restriction

### LINKED ISSUE #65151: ansible-galaxy message ERROR! Invalid collection name should specify reason collection name is invalid
##### SUMMARY

The written documentation for `ansible-galaxy` and the error message from the program does not offer the user useful information regarding invalid characters in the collection name.  

For example, underscores are permitted in the collection name, but dashes are not.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

ansible-galaxy
##### ANSIBLE VERSION

```paste below
ansible-galaxy 2.9.1
  config file = /home/administrator/ansible/playbooks/ansible.cfg
  configured module search path = [u'/usr/share/ansible', u'/home/administrator/ansible/playbooks/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A
##### ADDITIONAL INFORMATION

```bash
$ ansible-galaxy collection init joelwking.ansible-mongodb -f
ERROR! Invalid collection name 'joelwking.ansible-mongodb', name must be in the format <namespace>.<collection>.

$ ansible-galaxy collection init joelwking.mongodb -f
- Collection joelwking.mongodb was created successfully

```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Fixes: #65151

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE 
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/collection_error_fix.yml
lib/ansible/galaxy/collection.py
lib/ansible/utils/collection_loader.py

### CODE REVIEW

**Review by gundalow — APPROVED** [review]

**Review by samccann — APPROVED** [review]
docs portion LGTM

**Review by jborean93 — APPROVED** [review]

**Comment by jborean93** [comment]
While the changelog is `minor_changes` I think this would be good to backport to stable-2.9. Thanks @Akasurde.

**Comment by Akasurde** [comment]
@samccann @jborean93 @gundalow Thanks for the review.

**Comment by Akasurde** [comment]
Backport 2.9 - https://github.com/ansible/ansible/pull/65276

**Pull request merged**
