### PR TITLE
Fixes #49362 module dnf: install python3-dnf preferably over python2-dnf.

### LINKED ISSUE #49362: python2_dnf is not available for Fedora 30 (rawhide)
##### SUMMARY
Fedora 30 (now rawhide, the unreleased development branch) will [not offer python2-dnf]( https://fedoraproject.org/wiki/Releases/30/ChangeSet#Mass_Python_2_Package_Removal) anymore.

This causes a problem when installing `python2` on Fedora 30.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dnf

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = None
  configured module search path = [u'/home/robertdb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

##### CONFIGURATION
```
[no output]
```

##### OS / ENVIRONMENT
Control node does not matter, I'm using Fedora 29.
Managed node: Fedora 30/rawhide

##### STEPS TO REPRODUCE

Start a fedora rawhide container:

```sh
docker run --rm fedora:rawhide sleep 300
```

Install python2 on it:

```sh
ansible \
  -m dnf \
  -a "name=python2" \
  -i f9f2e079d337, \
  -c docker \
  -e "ansible_python_interpreter=/usr/bin/python3" \
  all
```

Install another package using the default `ansible_python_interpreter`:

```sh
ansible \
  -m dnf \
  -a "name=sos" \
  -i f9f2e079d337, \
  -c docker \
  all
```

Another way to test this: (could be used in the integration tests)

```
# INSTALLPYTHON2
#  The module `dnf` tries to install python2-dnf when it's running on systems
#  that have python2 installed. Fedora 30 and newer have python3 and limited
#  support for python2, for example python2-dnf is missing.

- name: use python3
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: install python2
  dnf:
    name: python2
    state: present

- name: use python2
  set_fact:
    ansible_python_interpreter: /usr/bin/python

- name: install a sample package
  dnf:
    name: python2
    state: present
```

##### EXPECTED RESULTS
Just to have python2 installed, I'm not interested in python2-dnf.

I realize this an edge case, and fixing it may cause more issues, like #22305.

##### ACTUAL RESULTS

```
f9f2e079d337 | FAILED! => {
    "changed": false, 
    "cmd": "dnf install -y python2-dnf", 
    "msg": "Error: Unable to find a match", 
    "rc": 1, 
    "stderr": "Error: Unable to find a match\n", 
    "stderr_lines": [
        "Error: Unable to find a match"
    ], 
    "stdout": "Last metadata expiration check: 0:01:03 ago on Fri Nov 30 10:19:16 2018.\nNo match for argument: python2-dnf\n", 
    "stdout_lines": [
        "Last metadata expiration check: 0:01:03 ago on Fri Nov 30 10:19:16 2018.", 
        "No match for argument: python2-dnf"
    ]
}
```

### PR DESCRIPTION
**Pull request by robertdebock**
##### SUMMARY
This merge request solves issue #49362. It installs python3-dnf, unless python2 is used.

The previous situation preferred python2-dnf over python3-dnf, causing an issue on systems with both python2 and python3.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
dnf

##### ADDITIONAL INFORMATION
Most details can be found in #49362.

I would like to be able to test against Fedora 30, but did not find out how integration works well enough.

### CODE REVIEW

**Comment by maxamillion** [comment]
rebuild_merge

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
@robertdebock thanks for the fix! 👍

**Comment by maxamillion** [comment]
@robertdebock on second review, I think I misunderstood this at first pass and I'm not actually certain this this fixes anything. I'm getting the same behavior with and without the patch in my testing. Also, the integration test fails on Fedora 30 with and without the patch so I'm not certain I follow the intention here. Would you mind walking me through it?

**Comment by maxamillion** [comment]
needs_info

**Comment by robertdebock** [comment]
The intention is that python3-dnf is installed, _unless_ python2 is used. Basically prefer Python 3 over Python 2.

In my humble opinion a module should not install a package at all, I'd be fine with removing the whole logic to install python*-dnf.

**Comment by jborean93** [comment]
Just an FYI as well, I've started seeing the failure in the tests on the upcoming Fedora 29 host which runs on Python 3 https://app.shippable.com/github/ansible/ansible/runs/96941/4/console.

**Comment by maxamillion** [comment]
@robertdebock right, but `python3-dnf` is installed unless python2 is used. That's what the `PY2` check is for. `ansible_python_interpreter` decides python2 vs python3.

**Comment by maxamillion** [comment]
@jborean93 we need to follow up on that because the lack of `python2-dnf` is a reality of Fedora going forward that we need to adapt to because we have no control over them retiring that package.

**Comment by jborean93** [comment]
@robertdebock I've opened a PR to revert this change https://github.com/ansible/ansible/pull/49633. This is because the tests will touch the Python environment when ansible-test is running which is not something we want. The actual changes in the dnf module also don't change anything. It just changes how the if statement is structured but the same behaviour is still there, e.g. `PY2` == `python2-dnf` and `not PY2` == `python3-dnf`.

I'm hoping to get the Fedora 29 enabled in CI sometime today which runs on Python 3 so you will have a better test suite shortly for this scenario. Fedora 30 is still some time away and we probably won't add it until it is released.

**Comment by blaisep** [comment]
OK, it seems the workaround is to edit `defaults/main.yml` by adding:
```
ansible_python_interpreter: $(which python)
```
so that I "pin" the python interpreter to whatever it happens to be at runtime.

@jborean93 I'm running Fedora 29 modular server also and I wonder if you have the test suite working?

**Comment by maxamillion** [comment]
@blaisep FWIW, this work around won't be necessary in Ansible 2.8 because we'll auto detect the python interpreter.

**Comment by robertdebock** [comment]
Fedora 30 is [scheduled to be released](https://fedoraproject.org/wiki/Releases/30/Schedule) in May of 2019.
Ansible 2.8 is [scheduled to be released]( https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) in February of 2019.

That will mean that from May 2019 on, people will have to run Ansible 2.8 or newer.

**Comment by maxamillion** [comment]
Ansible 2.8 is [scheduled to be released](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_8.html) in May of 2019.

**Comment by jborean93** [comment]
@blaisep Fedora 29 is running in our CI right now with Python 3. Hopefully we will be a bit quicker to swap 28 to 30 when 30 is released but that won't happen until around May.

**Comment by blaisep** [comment]
Thanks @maxamillion , I suppose I will have to keep the 'ansible_python` hack in place until the dust clears! Maybe, if we're all really good, @robertdebock will write a role that will detect the discrepancy, create a virtualenv, move all the dependencies in there, complete the task(s) and copy the results to the original context....

**Pull request merged**
