### PR TITLE
Add a fact providing the full hostname, without the domain portion

### PR DESCRIPTION
**Pull request by herbygillot**
truncated.

### CODE REVIEW

**Comment by mpdehaan** [comment]
This was brought up before apparently, with no clear conclusion:

https://github.com/ansible/ansible/pull/2677

https://groups.google.com/forum/#!topic/ansible-project/vpkLqyXFMYE

The worst part of this though is that I don't think many of our users would be able to tell which one to use by looking at the different variable names, which makes this pull request a bit confusing -- and I'm not certain what damage would be done by changing the fqdn fact to return the full platform.node()

This may be very well a case where a local facts module is warranted.

**Comment by herbygillot** [comment]
@mmoya @mpdehaan I am indeed running into the same issue as Anand B. in the referenced thread.

Since socket.get_fqdn and platform.node are taking slightly different code paths, the results aren't the same.

I still think that the full contents of platform.node should be made available as a standard fact.

Since the issue is one of confusion/naming, perhaps the right thing to do here is simply name this fact as `nodename` instead?

**Comment by mpdehaan** [comment]
Works for me, merged, thanks!

**Comment by herbygillot** [comment]
@mpdehaan Thank you.

**Pull request merged**
