### PR TITLE
draft of slack callback module

### PR DESCRIPTION
**Pull request by bcoca**
redo of #8955 with view to v2 ... cannot get arguments passed still not ready for inclusion

### CODE REVIEW

**Comment by jpooler** [comment]
Any update when this will get re-visited? I'm hoping to be able to use slack callbacks without writing my own plugin.

Thanks @bcoca for all your hard work!

**Comment by bcoca** [comment]
if you have a working plugin or can fix this one to work, please contribute, I'll be busy trying to squash 2.0 bugs for the release for a while

**Comment by sivel** [comment]
I am taking a little look at this now.  For one `playbook_on_start` is no longer called.  Also `self.playbook` no longer exists, so the info we got from that is missing.

I need this for work, so I'll likely figure out how to get similar if not the same functionality.

**Comment by sivel** [comment]
For now, I'll go ahead and assign this to me.

**Comment by jpooler** [comment]
Awesome! I assumed we'd want to update to use v2 methods too. I am happy to help test when the time comes or pair up at some point.

**Comment by sivel** [comment]
Here is some initial work.  Not positive I want to handle it all like I have, but it is working with v2 and displays the same information as before.  It required a few changes to make `v2_playbook_on_start` get called as well as adding a `_file_name` attribute to the `Playbook` class.

https://github.com/ansible/ansible/compare/devel...sivel:v2-slack-callback?expand=1

**Comment by jpooler** [comment]
Looks good to me! I am able to post to slack with it as-is.

http://www.ntoggle.com/Jarrod Pooler
DevOps Engineer
jarrod@ntoggle.com
Follow nToggle: https://www.linkedin.com/company/ntoggle-inc
https://twitter.com/ntoggle https://www.facebook.com/ntoggle

**Comment by bcoca** [comment]
closing as it is superceeded by #13408

**Pull request closed without merging**
