### PR TITLE
[WIP] win_file: Fix a few issues and integration tests

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes the following changes:
- Enable more integration tests
- Compatibility with the **file** module
- Fixes a known issue in win_file (see below).

```yaml
- win_file:
    path: C:\Windows\Temp\Users.Default
    state: absent
```

results in:
```
{
    "changed": false,
    "failed": true,
    "module_stderr": "Exception calling \"Run\" with \"1\" argument(s): \"Exception calling \"Invoke\" with \r\n\"0\" argument(s): \"Command execution stopped because the preference variable \r\n\"ErrorActionPreference\" or common parameter is set to Stop: Could not find \r\nitem C:\\Windows\\Temp\\Users.Default.\"\"\r\nAt line:45 char:1\r\n+ $output = $entrypoint.Run($payload)\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE \r\nxception\r\n+ FullyQualifiedErrorId : ScriptMethodRuntimeException\r\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_file

##### ANSIBLE VERSION

v2.4

### CODE REVIEW

**Comment by jhawkesworth** [comment]
stale ci, going to close and open this to get a fresh ci run before investigating further.

**Comment by dagwieers** [comment]
@jhawkesworth I still have to work on this one. I discovered this problem when doing robocopy integration tests during AnsibleFest London, and it was bit too chaotic to focus on this. Still on my list of things to finish before v2.4 freeze.

**Comment by jhawkesworth** [comment]
Thanks.  I suspect it just needs to handle check mode runs properly.

**Comment by jhawkesworth** [comment]
I have fixed up tests for this in my local fork but am unable to push to github at the moment.

**Comment by jhawkesworth** [comment]
I have fixed up tests for this in my local fork but am unable to push to github at the moment.

**Comment by jhawkesworth** [comment]
For what its worth I have pushed fixed tests here: https://github.com/jhawkesworth/ansible/commit/24533a196b15d54c64c2a382b9413186e88148f1

Likely to have been superceeded now

**Pull request closed without merging**
