### PR TITLE
fix collection adjacent loading with --playbook-dir

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

collections

### CODE REVIEW

**Comment by AlanCoding** [comment]
```
ansible-inventory -i my_inventory.yml --list --export --playbook-dir=.
{
    "_meta": {
        "hostvars": {
            "my_host": {}
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "my_host"
        ]
    }
}
```

with https://github.com/chrismeyersfsu/ansible-examples/tree/master/collections_hello_world

failed with devel

**Comment by AlanCoding** [comment]
To be clear, since there is not yet a documented reference behavior on github:

```
ansible-inventory -i my_inventory.yml --list --export --playbook-dir=.
 [WARNING]:  * Failed to parse /Users/alancoding/Documents/repos/ansible-examples/collections_hello_world/my_inventory.yml with auto plugin: inventory config
'/Users/alancoding/Documents/repos/ansible-examples/collections_hello_world/my_inventory.yml' specifies unknown plugin 'redhat.cmeyers.my_inventory'

 [WARNING]:  * Failed to parse /Users/alancoding/Documents/repos/ansible-examples/collections_hello_world/my_inventory.yml with yaml plugin: Plugin configuration YAML file, not YAML
inventory

 [WARNING]:  * Failed to parse /Users/alancoding/Documents/repos/ansible-examples/collections_hello_world/my_inventory.yml with ini plugin: Invalid host pattern 'plugin:' supplied,
ending in ':' is not allowed, this character is reserved to provide a port.

 [WARNING]: Unable to parse /Users/alancoding/Documents/repos/ansible-examples/collections_hello_world/my_inventory.yml as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

Using env `ANSIBLE_COLLECTIONS_PATHS=collections/` fixed it in devel, but this is so that we don't have to use that.

**Review by AlanCoding — APPROVED** [review]

**Comment by kdelee** [comment]
@bcoca hoping to get this backported for 2.8.1 whenever that rolls around

**Review by samdoran — CHANGES_REQUESTED** [review]
Can you add tests to prevent future regressions?

**Review by samdoran — APPROVED** [review]

**Pull request merged**
