### PR TITLE
Docs:os_guide: replaced yes/no with true/false for booleans

### LINKED ISSUE #78923: Docs:os_guide: replace yes/no with true/false for booleans
### Summary

Based on the [steering committee vote to use true/false for booleans,](https://github.com/ansible-community/community-topics/discussions/120) we are going through the guides to adapt to this change.

This issue requests these changes in the `docs/docsite/rst/os_guide/` files.

Changes are: change `yes` to `true`  and `no` to `false`

must be lowercase. Please open one PR to handle thse changes. It should impact 15 files. NOTE - ansibot does not like PRs over 50 files.

The following grep will help you find these occurrences from the `docs/docsite/rst/os_guide/` directory:
`grep -R '\: \(yes\|no\)$' --exclude-dir=locales`

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/os_guide.index.rst

### Ansible Version

```console
$ ansible --version
none
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by kalashjain23**
##### SUMMARY

Replaced yes/no with true/false for booleans
Fixes #78923 

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by kalashjain23** [comment]
> @kalashjain23 Thanks for the contribution! Hacktoberfest is a busy time and it looks like someone is already working on #78923
> 
> I see that you commented on the issue but maybe missed the fact that there is already a PR open for it. Please be sure to look out for that before starting to work.

But @samccann told that I can open a PR as I was the first one to take up on that issue. Please look into that.
-> https://github.com/ansible/ansible/issues/78923#issuecomment-1265660296

**Comment by oraNod** [comment]
@kalashjain23 OK, I do see that another PR was opened before this one and was linked from the issue:

image

I don't want to be rude about it but I think the first PR against the issue is the one that gets merged. Unfortunately conflicts can happen because Hacktoberfest is such a busy time.

**Comment by samccann** [comment]
Hey @kalashjain23 sorry about this. Things do get a bit frantic on the first few days of Hacktoberfest and we end up with duplicate PRs. And with multiple people on our end merging, it's hard to see who promised ownership so to speak.  Please do consider other items on the hacktoberfest list https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest and we'll be adding more this week. We appreciate your help!

**Comment by kalashjain23** [comment]
Hey! It's totally fine, I do understand it gets a bit frantic during Hacktoberfest…
I'll be glad to contribute on other issues. I will take a look on some of them!

**Comment by oraNod** [comment]
Thank you @kalashjain23 ! Looking forward to seeing your other contributions!

**Pull request closed without merging**
