### PR TITLE
fix up service module to make it start processes that are listed to be

### PR DESCRIPTION
**Pull request by skvidal**
running and to report errors from starting them

### CODE REVIEW

**Comment by mpdehaan** [comment]
IIRC, service status is an unreliable string, and some services do report "not running" vs "stopped".  Was I wrong in this?

**Comment by skvidal** [comment]
On Fri, 4 May 2012 05:11:17 -0700
Michael DeHaan
reply@reply.github.com
wrote:

> IIRC, service status is an unreliable string, and some services do
> report "not running" vs "stopped".  Was I wrong in this?

I looked on rhel5 and 6 and anything that uses the status function
from /etc/init.d/functions import returns a rc of '3' if the daemon is
not running.

Some of them return 'stopped' some return 'not running' - so the text
seems more of a crapshoot.

but all of them SEEM to be 3.

I'm happy to keep 'not running', 'stopped' and rc of 3 as the check.

-sv

**Comment by mpdehaan** [comment]
sounds good

**Comment by mpdehaan** [comment]
merged, thanks... assuming the rc=3 is good enough and hopefully consistent on Happy Animals releases and such.

**Pull request merged**
