### PR TITLE
Enhance zypper module: two new options (refresh and without_recommens)

### PR DESCRIPTION
**Pull request by xenji**
Added refresh option for refreshing the repo meta data before ensuring the state.
Added option to skip recommends from zypper.
Added corresponding documentation and some examples.

Changed some of the variable names to be more self explanatory, made some changes according to PEP8.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Can you please submit these without the variable renames and also add the "version_added" attribute to indicate these options are new in 1.7?

Squash commit would also make review easier if you don't mind.

Thanks!

**Comment by xenji** [comment]
Sure I'll add that to the docs and squash it down to one commit.

**Comment by xenji** [comment]
I'll close those two requests and open new ones with the squashed commits

**Comment by alxgu** [comment]
For information, there is already a pull request to skip recommends: https://github.com/ansible/ansible/pull/7379

**Pull request closed without merging**
