### PR TITLE
ovirt: Return also nested attributes of structs

### PR DESCRIPTION
**Pull request by machacekondra**
##### SUMMARY

Previously we returned only nested attributes of the lists not of the
structs, this patch fixes it.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ovirt

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina

**Review by mwperina — APPROVED** [review]
shipit

**Comment by mwperina** [comment]
John, could you please merge?

@gundalow

**Comment by gundalow** [comment]
rebuild_merge

**Comment by remixtj** [comment]
@machacekondra @mwperina any interest in backporting to 2.7?

**Comment by machacekondra** [comment]
@remixtj We can. But there will be soon 2.8 release. I will send a backport.

**Pull request merged**
