### PR TITLE
mkfs module to create filesystems with mkfs command

### PR DESCRIPTION
**Pull request by abulimov**
I've made this simple module to use in clean-OS deployment. Module just wraps mkfs command to make it idempotent.

### CODE REVIEW

**Comment by mpdehaan** [comment]
As this module is very short, it could be handled with a two line "shell/register + shell" command set.

I am unsure about whether we should include it.

If we did, it seems it would be named "filesystem", not "mkfs", as "mkfs" is a bit of a verb, and we are saying "this should be the filesystem".

Would it need to also do other things?

**Comment by srgvg** [comment]
Maybe this functionality could be included in the 'mount' module?
Both module could also handle swap devices

**Comment by abulimov** [comment]
I also thing, that this module is too small, so I think the best way will be to make it a part of some existing module, or to extend this module with some additional functionality. Waiting for your advice.

**Comment by mpdehaan** [comment]
mount feels wrong, because you might not have any intention to mount it.

**Comment by srgvg** [comment]
I don't see any other module that would fit. Agreed, with 'mount' it doesn't fit the labele iether, but maybe a new module 'filesystem' of 'managefs' would be a better name for this.

I'm not sure which policy would be acceptable to merge modules, or convert them to a new name when getting extra features.

**Comment by jsmartin** [comment]
I like the idea of using it as a module vs doing it with command/shell tasks.  It seems cleaner that way.  It seems a common enough task to be included in the core, but hey, that's no up to me. :)

**Comment by mpdehaan** [comment]
Please resubmit this making a module named 'filesystem' and put it under the library/system folder, and I'll take this.

**Pull request closed without merging**
