### PR TITLE
Update debug.py

### PR DESCRIPTION
**Pull request by filviu**
##### SUMMARY
<!— Your description here –>
Corrected indentation according to lint rules.

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ansible.builtin.debug

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jborean93** [comment]
What lint rules are these, the current code is perfectly valid YAML.

**Comment by filviu** [comment]
The nice but very strict people running `ansible-lint` beg to differ :)

Contents of `run.yml`

```yaml
cat run.yml
---
- name: Debug msg lint test
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Prints two lines of messages, but only if there is an environment value set
      ansible.builtin.debug:
        msg:
        - "Provisioning based on YOUR_KEY which is: {{ lookup('ansible.builtin.env', 'YOUR_KEY') }}"
        - "These servers were built using the password of '{{ password_used }}'. Please retain this for later use."
```

Output of `ansible-lint run.yml`

```
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: run.yml
WARNING  Listing 1 violation(s) that are fatal
yaml: wrong indentation: expected 10 but found 8 (yaml[indentation])
run.yml:11

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - yaml[indentation]  # Violations reported by yamllint.

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

`ansible-lint --version`

```
ansible-lint 6.7.0 using ansible 2.13.4
```

**Comment by bcoca** [comment]
@filviu linting is not about correctness, but conformity. A syntax check (correctness) will show that this is still correct yaml, just not to the 'taste' of yaml-lint, which is what ansible-lint uses to check the YAML.

Since this is still correct YAML, I'm going to close this PR.

**Comment by filviu** [comment]
@bcoca I understand that and for my own projects I choose using .yamllint (thanks @webknjaz ) which rules I actually care about. But I assumed that - at least where convenient - docs should pass the linter maintained by the same project. 

Also seemed a harmless enough fix that removes an old style syntax and a warning that could confuse begginers - the very people most likely to use those docs. 

Not to mention https://ansible-lint.readthedocs.io/philosophy/#why-lots-of-official-ansible-docs-examples-are-not-passing-linting made me think that fixes like this are actually wanted.

Anyways this wasted too much of mine and your time to make it worth it so thanks both for the replies.

**Pull request closed without merging**
