### PR TITLE
Enhance maven_artifact with a keep_name option

### PR DESCRIPTION
**Pull request by tumbl3w33d**
It allows retaining the version number in the downloaded artifact's name when the version to be downloaded is dynamically determined ('latest').

So far, the behavior was to overwrite the version string in the artifact name with 'latest' which leaves no trace of what version the downloaded artifact has. E.g., you cannot use this information for further processing like transferring it to an RPM that is built from the artifact.

This fulfills feature request ansible/ansible#22337

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 4d666da2b4) last updated 2017/03/07 00:06:54 (GMT +200)
```

##### SUMMARY
The referenced issue explains the enhancement in detail. The module now allows keeping the version string in the downloaded artifact's name.

### CODE REVIEW

**Comment by bcoca** [comment]
we are in freeze, so now this would most likely be considered for 2.4

**Comment by tumbl3w33d** [comment]
I increased the version_added to 2.4. Unfortunately that makes the test fail yet.
`
ERROR: lib/ansible/modules/packaging/language/maven_artifact.py:0:0: E309 version_added for new option (keep_name) should be 2.3. Currently 2.4
`

**Comment by chrisisbeef** [comment]
Outside of the outstanding question regarding version, this looks good to me.

**Review by chrisisbeef — APPROVED** [review]

**Comment by mattclay** [comment]
@chrisisbeef Once we've created the `stable-2.3` branch (expected around March 15th) you can re-run CI for this PR and tests should pass. You can trigger CI for your PR by rebasing your branch.

**Comment by tumbl3w33d** [comment]
Sorry for the tag chaos. My rebasing went a little wrong at first, but with enough --force I sorted it out. Anything missing yet? @mattclay

**Comment by tumbl3w33d** [comment]
Dear @chrisisbeef would you please comment it with shipit if nothing changed about your approval? :)

**Comment by tumbl3w33d** [comment]
@bcoca swing the shovel please, before the code changes too much for merging. :see_no_evil:

**Comment by tumbl3w33d** [comment]
@chrisisbeef write shipit, please :unamused:

**Comment by calfonso** [comment]
@tumbl3w33d are you interested in being a maintainer of this module?

**Comment by tumbl3w33d** [comment]
@calfonso yeah, I guess I could give it a try.

**Pull request merged**
