### PR TITLE
Parse CLI inventory string with the InventoryINIParser.

### LINKED ISSUE #13931: Can't specify per-host hostvars in CLI inventory parameter
Is the Ansible CLI `-i` inventory arg not parsed using the standard inventory parser?  I'd like to specify `ansible_python_interpreter` on a per-host basis when passing in a comma-separated list of hosts to the CLI using `-i` but it doesn't appear to support [behavioral inventory parameters](http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters).

```
$ ansible -i sark, all -m shell -a date
sark | FAILED | rc=0 >>
Error: ansible requires the stdlib json or simplejson module, neither was found!
```

`sark` is CentOS 5.11, `/usr/bin/python` is 2.4.3.  So:

```
$ ansible -i sark, -e ansible_python_interpreter=/usr/bin/python2.7 all -m shell -a date
sark | SUCCESS | rc=0 >>
Sat Jan 16 11:35:18 EST 2016
```

Works great.  But, what if I want to specify two different hosts in `-i` each of which need a different `ansible_python_interpreter` value?

```
$ ansible -i "sark ansible_python_interpreter=/usr/bin/python2.7," all -m shell -a date
sark ansible_python_interpreter=/usr/bin/python2.7 | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue",
    "unreachable": true
}
```

A simple enhancement here would be to pass the comma-separated list of strings passed in the `-i` arg to whatever parser is used to parse the inventory if it was a file or a command's output.

Or, am I doing this wrong?  Is there a way to achieve what I'm looking for that I haven't figured out, yet?

### PR DESCRIPTION
**Pull request by dossy**
Fixes ansible/ansible#13931.

### CODE REVIEW

**Comment by dossy** [comment]
I tried running the test suite before my commit, and it was already failing, FYI.

**Comment by lathama** [comment]
@dossy is this still of interest? If not please close.

**Comment by dossy** [comment]
I personally use this in my own branch of Ansible.  It would be great to see it merged upstream, but 21 months later, I'm not holding my breath.

I'll go ahead and close this.  If anyone else needs this functionality, they're welcome to use the patch, too.

**Comment by bcoca** [comment]
@dossy, i would look at the new inventory plugins, which can now take over 'inline parsing', see  host_list and  advanced_host_list plugins. As a plugin there would be no reticence as it would not modify the default parser but still be available to those that want an 'extended one'.

**Pull request closed without merging**
