### PR TITLE
FIX: F5 Bigip alias server port not accepting * as input

### PR DESCRIPTION
**Pull request by xdkreij**
##### SUMMARY

bigip_monitor_http.py does not accept * as input for the alias server port, resulting in the following error:

```
"msg": "argument port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: '*'"
```

Changed the behaviour of how the bigip_monitor_XXX.py deals with the input value of the port as followed:

```
class ArgumentSpec(object):
    def __init__(self):
        self.supports_check_mode = True
        argument_spec = dict(
            name=dict(required=True),
            parent=dict(default='/Common/http'),
            description=dict(),
            send=dict(),
            receive=dict(),
            receive_disable=dict(required=False),
            ip=dict(),
            port=dict(type='str'),
```

And

```
    @property
    def port(self):
        if self._values['port'] is None:
            return None

        elif isinstance(self._values['port'], int):
          return int(self._values['port'])

        elif self._values['port'] == '*':
            return '*'
```

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

bigip_monitor_http.py

##### ADDITIONAL INFORMATION

Issue occured during the creation of a basic ansible playbook to create an health monitor on a F5 bigip
appliance. 

Basic task to run:

- name: Create HTTP Monitor
  bigip_monitor_http:
    state: present
    ip: 10.10.10.10
    server: lb.mydomain.com
    user: admin
    password: secret
    name: my_http_monitor
    ip: 0.0.0.0    # results in * All Addresses
    port: '*'        # Causes the error while having the intention to configure it as "* All Ports"
  delegate_to: localhost

**Before**

[fix_bigip_monitor_http.zip](https://github.com/ansible/ansible/files/3121737/fix_bigip_monitor_http.zip)

```
[root@localhost f5_bigip_orchestration]# ansible-playbook -i inventory/hosts -e "target_action=monitor_http target_state=present monitor_name=my-first-test" f5_bigip_orchestration.yml -vvv
ansible-playbook 2.7.10
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
No config file found; using defaults
/home/<path_to_ansible_playbook_location>/f5_bigip_orchestration/inventory/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/home/<path_to_ansible_playbook_location>/f5_bigip_orchestration/inventory/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/<path_to_ansible_playbook_location>/f5_bigip_orchestration/inventory/hosts inventory source with ini plugin

PLAYBOOK: f5_bigip_orchestration.yml ***********************************************************************************************************************************************************
1 plays in f5_bigip_orchestration.yml

PLAY [all] *************************************************************************************************************************************************************************************
META: ran handlers

TASK [include_role : f5_bigip] *****************************************************************************************************************************************************************
task path: /home/<path_to_ansible_playbook_location>/f5_bigip_orchestration/f5_bigip_orchestration.yml:5

TASK [f5_bigip : HTTP Monitor - present] *******************************************************************************************************************************************************
task path: /home/<path_to_ansible_playbook_location>/f5_bigip_orchestration/roles/f5_bigip/tasks/bigip_monitor_http.yml:1
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: <ommited>
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1556287696.84-232139189845796 `" && echo ansible-tmp-1556287696.84-232139189845796="` echo /root/.ansible/tmp/ansible-tmp-1556287696.84-232139189845796 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_monitor_http.py
<localhost> PUT /root/.ansible/tmp/ansible-local-35844UqmGbR/tmpk7S5XZ TO /root/.ansible/tmp/ansible-tmp-1556287696.84-232139189845796/AnsiballZ_bigip_monitor_http.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1556287696.84-232139189845796/ /root/.ansible/tmp/ansible-tmp-1556287696.84-232139189845796/AnsiballZ_bigip_monitor_http.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1556287696.84-232139189845796/AnsiballZ_bigip_monitor_http.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1556287696.84-232139189845796/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_monitor_http_payload_e6zOyC/ansible_bigip_monitor_http_payload.zip/ansible/module_utils/basic.py", line 2096, in _check_argument_types
    param[k] = type_checker(value)
  File "/tmp/ansible_bigip_monitor_http_payload_e6zOyC/ansible_bigip_monitor_http_payload.zip/ansible/module_utils/basic.py", line 1959, in _check_type_int
    return int(value)

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "description": "A test description ", 
            "interval": 5, 
            "ip": "0.0.0.0", 
            "name": "my-first-test", 
            "parent": "http", 
            "partition": "Common", 
            "port": "*", 
            "provider": {
                "auth_provider": null, 
                "password": "<omitted>", 
                "server": "<omitted>", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": 16, 
                "transport": "rest", 
                "user": "<omitted>", 
                "validate_certs": false
            }, 
            "receive": " ", 
            "send": "GET /\\r\\n", 
            "state": "present", 
            "time_until_up": 0, 
            "timeout": 16
        }
    }, 
    "msg": "argument port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: '*'"
}
	to retry, use: --limit @/home/<path_to_ansible_playbook_location>/projects/f5_bigip_orchestration/f5_bigip_orchestration.retry

PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1  

```
**After**

```
<snip>

<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1556285937.59-56233276509559/AnsiballZ_bigip_monitor_http.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1556285937.59-56233276509559/ > /dev/null 2>&1 && sleep 0'
changed: [localhost -> localhost] => {
    "changed": true, 
    "description": "Test description ", 
    "interval": 5, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "description": "Test description ", 
            "interval": 5, 
            "ip": "0.0.0.0", 
            "name": "my-first-test", 
            "parent": "http", 
            "partition": "Common", 
            "password": null, 
            **"port": "*",** 
            "provider": {
                "auth_provider": null, 
                "password": "<omitted>", 
                "server": "<omitted>", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": 16, 
                "transport": "rest", 
                "user": "root", 
                "validate_certs": false
            }, 
            "receive": " ", 
            "receive_disable": null, 
            "send": "GET /\\r\\n", 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "target_password": null, 
            "target_username": null, 
            "time_until_up": 0, 
            "timeout": 16, 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "ip": "*", 
    "parent": "/Common/http", 
    "port": "*", 
    "receive": " ", 
    "send": "GET /\\r\\n", 
    "time_until_up": 0, 
    "timeout": 16
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   


```

### CODE REVIEW

**Comment by caphrim007** [comment]
@xdkreij this PR has far more than what you describe in the description. Additionally, your fix is equivalent to what is already in the F5 module code

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_monitor_http.py#L334

**Comment by xdkreij** [comment]
> 
> 
> @xdkreij this PR has far more than what you describe in the description. Additionally, your fix is equivalent to what is already in the F5 module code
> 
> https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_monitor_http.py#L334

Seems legit. Thanks for pointing that out! I will test their (still in dev i see) code. Any idea when this will move to production?

**Comment by caphrim007** [comment]
@xdkreij 

F5 usually upstreams all of their work to ansible core prior to the community module freeze dates. So for 2.8, the code relevant to port should already be part of the stable-2.8 branch in Ansible

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_monitor_http.py#L331

F5 does not usually backport changes to older versions of Ansible. You can install their galaxy role if you want to get their changes "now" instead of waiting for 2.8

https://galaxy.ansible.com/f5devcentral/f5ansible

**Comment by xdkreij** [comment]
@caphrim007 

Thanks Tim, good to know! Will close this PR and test Ansible 2.8 & the Ansible galaxy role.

Much appreciated!

Kr, Xander


> 
> 
> @xdkreij
> 
> F5 usually upstreams all of their work to ansible core prior to the community module freeze dates. So for 2.8, the code relevant to port should already be part of the stable-2.8 branch in Ansible
> 
> https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_monitor_http.py#L331
> 
> F5 does not usually backport changes to older versions of Ansible. You can install their galaxy role if you want to get their changes "now" instead of waiting for 2.8
> 
> https://galaxy.ansible.com/f5devcentral/f5ansible

**Pull request closed without merging**
