### PR TITLE
ansible-vault edit: replicate sudoedit behavior

### PR DESCRIPTION
**Pull request by darkk**
- do not touch original file if temporary file is not changed,
  but rekey original file if it uses obsolete scheme
- create new encrypted file if it does not exist
- see also #7041 and #7042

### CODE REVIEW

**Comment by mpeters** [comment]
There isn't a test (or example playbook) associated with this PR.
But I can verify that all the unit tests and integration tests pass using:
- ansible 1.8 (testing_pr_8694 98de69b244) last updated 2014/09/18 15:04:22
- Python 2.7.5
- CentOS 7.0

**Comment by bcoca** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by amenonsen** [comment]
I've submitted the "re-encrypt if changed" functionality as #11740 as a rebase of #8602. I'm refactoring the vault code and will include the remaining functionality (re-encrypt to avoid AES) there.

This PR can be closed, considering that the rebase request has not been responded to in several months.

**Comment by bcoca** [comment]
closing via merged #11740

**Comment by darkk** [comment]
@amenonsen thank you :)

**Pull request closed without merging**
