### PR TITLE
Update intro_installation.rst

### PR DESCRIPTION
**Pull request by MichaelBaydoun**
##### ISSUE TYPE
- Docs Pull Request
##### ANSIBLE VERSION

ansible 2.2.0 (devel 4f76222f5b) last updated 2016/06/29 18:10:47 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 2f0f04437b) last updated 2016/06/29 18:10:50 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD f5b7b3b2f2) last updated 2016/06/29 18:10:51 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
##### SUMMARY

markupsafe is a newer requirement, documenting here.

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible/16504)

### CODE REVIEW

**Comment by nitzmahone** [comment]
I don't find markupsafe anywhere in our codebase, nor in setup.py- where's that requirement coming from?

**Comment by MichaelBaydoun** [comment]
When I try to run ansible from source on a new Ubuntu 14.04.4 server, I get a error running ansible --version complaining about no markupsafe.  Sudo pip install markupsafe makes the issue go away.

**Comment by bcoca** [comment]
it is a jinja2 requirement, not an ansible one, if the jinja2 package you are using is not properly setting it as a requirement, that is a bug with that package.

**Comment by MichaelBaydoun** [comment]
Specifically ...

Version of ubuntu

```
✗ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

version of ansible without markupsafe installed (running from source)

```
✗ ansible --version
ERROR! Unexpected Exception: No module named markupsafe
the full traceback was:

Traceback (most recent call last):
  File "/home/mbaydoun/ansible/bin/ansible", line 81, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/home/mbaydoun/ansible/lib/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/home/mbaydoun/ansible/lib/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/home/mbaydoun/ansible/lib/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/home/mbaydoun/ansible/lib/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/home/mbaydoun/ansible/lib/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/home/mbaydoun/ansible/lib/ansible/playbook/base.py", line 32, in <module>
    from jinja2.exceptions import UndefinedError
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe
```

version of ansible with markupsafe installed

```
✗ ansible --version
ansible 2.2.0 (devel 4f76222f5b) last updated 2016/06/29 18:10:47 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 2f0f04437b) last updated 2016/06/29 18:10:50 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD f5b7b3b2f2) last updated 2016/06/29 18:10:51 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
```

**Comment by MichaelBaydoun** [comment]
Installing Jinja2 via pip just like the documentation calls for

```
sudo pip install paramiko PyYAML Jinja2 httplib2 six
```

**Comment by MichaelBaydoun** [comment]
Point being anyone following the instructions for running from source in this document is going to run into the same error.

**Comment by nitzmahone** [comment]
Looks like a busted dist-package of Jinja2- is that really on a brand-new fresh install (AWS or something?)

**Comment by nitzmahone** [comment]
We're not min-version-gating J2 (or anything else) so in that case, it wouldn't try to upgrade... What version of J2 is already there? Maybe if we said Jinja2>=2.8 ...

**Comment by MichaelBaydoun** [comment]
That's a new aws instance, created less than 2 weeks ago, based on the most recent amazon supplied ami.

**Comment by MichaelBaydoun** [comment]
The version of Jinja2 I'm getting with the pip install

```
Jinja2 (2.8)
```

**Comment by MichaelBaydoun** [comment]
So with Jinja2 v2.8 present, and markupsafe not present, the error occurs.

**Comment by MichaelBaydoun** [comment]
From http://jinja.pocoo.org/docs/dev/intro/

```
MarkupSafe Dependency
As of version 2.7 Jinja2 depends on the MarkupSafe module. If you install Jinja2 via pip or easy_install it will be installed automatically for you.
```

So it appears it's not really being installed automatically.  I should raise an issue with the Jinja2 project.

**Comment by nitzmahone** [comment]
But it's a dist-package- I just created an AWS instance from the latest 14.04 AMI and J2 isn't included out of the box as a dist-package. It's probably an issue with whatever apt package that came from.

**Comment by MichaelBaydoun** [comment]
When I remove jinja2 and try to reinstall it, it's trying to install markupsafe but failing, yet reporting successful install at the bottom

```
✗ sudo pip install jinja2
Downloading/unpacking jinja2
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Downloading/unpacking MarkupSafe (from jinja2)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_root/MarkupSafe/setup.py) egg_info for package MarkupSafe

Installing collected packages: jinja2, MarkupSafe
  Running setup.py install for MarkupSafe

    building 'markupsafe._speedups' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
    markupsafe/_speedups.c:12:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.


    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
    ==========================================================================
Successfully installed jinja2 MarkupSafe
```

**Comment by nitzmahone** [comment]
Curious if the bootstrapper here works for you: https://github.com/mattclay/ansible-hacking

It looks like just an issue of not having all the necessary native python deps (python-dev, etc) + a bug where pip's reporting success on a failure. Are you using the ancient pip from apt or did you install a new one?

**Comment by nitzmahone** [comment]
Works for me on a fresh version of that AMI if you install a non-ancient pip (+ all the native deps from apt of course: python-dev, libffi-dev, libssl-dev, git).

**Pull request closed without merging**
