### PR TITLE
Support manjaro arm in hostname module

### PR DESCRIPTION
**Pull request by ovv**
##### SUMMARY

Support manjaro arm in hostname module

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

hostname

### CODE REVIEW

**Comment by sivel** [comment]
It looks like we already support Manjaro (https://github.com/ansible/ansible/pull/64810)

I assume Manjaro-arm isn't a different OS, it's just a different arch?  I wonder if this needs to be solved by using the existing class, by fixing the distribution.

**Comment by ovv** [comment]
Indeed it's a different arch, I guess it would be cleaner to fix the distribution but that probably require a much bigger patch.
Archlinux ARM is supported in the same way: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/hostname.py#L632

**Comment by ovv** [comment]
Hello @Akasurde @sivel, any chances to get that merged ?

**Comment by Akasurde** [comment]
@ovv I am sorry this. Running CI.

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by Akasurde** [comment]
@ovv Thanks for the contribution.

**Pull request merged**
