### PR TITLE
netconf_config: support new src attribute (new Action Plugin)

### PR DESCRIPTION
**Pull request by wisotzky**
##### SUMMARY
To support new attribute 'src' for the netconf_config module.
Cross-check with #24323

##### ISSUE TYPE
 - Feature Pull Request (check #24221)

##### COMPONENT NAME
module netconf_config

##### ANSIBLE VERSION
latest

### CODE REVIEW

**Comment by userlerueda** [comment]
shipit

**Comment by gundalow** [comment]
cc @lpenz

**Comment by lpenz** [comment]
Nice!

Would you mind changing the commit title to something more descriptive? Like "netconf_config: support new src attribute" or mention that it's related to the action plugin.

Right now it's a bit confusing because we will see "Update netconf_config.py" before a "Create netconf_config.py" in the oneline log.

**Comment by wisotzky** [comment]
@lpenz done!

**Review by ganeshrn — APPROVED** [review]

**Comment by ganeshrn** [comment]
@wisotzky Looks good. Thank you!

**Comment by lpenz** [comment]
Very nice, thank you all!

**Pull request merged**
