### PR TITLE
New module to send text message notifications

### PR DESCRIPTION
**Pull request by mattmakai**
This module "text" allows an Ansible script to fire off text message notifications through Twilio (other services can also be added in later if requested).

This is my first pull request to Ansible's core so please let me know what cleanup and other tasks need to be done (I checked the web docs they look fine) before this can be accepted. Thank you!

### CODE REVIEW

**Comment by jpmens** [comment]
A few comments upon glancing at this, if I may (and also if I may not :-)
- version_added says 1.2 which is probably incorrect
- You've named the module "text". For me as a continental European that sounds like text processing :-) Within the docs you write SMS, so why not call the module "sms" or better yet, "twilio" (as that is what you're supporting)?

Other than that, it looks nice.

**Comment by mattmakai** [comment]
JP, great feedback, thanks! I must've made a mistake on the 1.2, I meant to put 1.6. I'll fix that up.

I agree that "text" isn't descriptive enough. I was following the convention of the other notification modules such as jabber and grove. I'm hesitant to call it "sms" because in the future you could also perhaps send a multimedia message with a screenshot if errors occurred.

I could call it "twilio" although I wasn't sure whether it would be better to make it a generic texting module where you could swap services. What do you think of "textmessage" or "text_message"?

**Comment by jpmens** [comment]
Either of the two sound better to me, but maybe wait anf see what one of
the Masters of Merge say. ;-)

**Comment by mpdehaan** [comment]
I think it needs to be called twilio.   Other services may be quite different in API signature.

**Comment by mattmakai** [comment]
Do you want these commits squashed before they would be merged in if you decide to include twilio as a module? I'll have to open a new pull request as I accidentally pushed this second commit before squashing them into a single commit.

**Comment by mpdehaan** [comment]
I'm merging this now, thank you!  It will be good buddies with the new nexmo module!

**Comment by mattmakai** [comment]
awesome, thanks Michael! let me know if there's any clean up you need me to do once it's merged. I think the HTTP request headers may need to be changed up after a conversation I had with one of my colleagues

**Comment by mpdehaan** [comment]
This was merged and github just didn't close it earlier, so taking care of that now.

**Pull request closed without merging**
