### PR TITLE
Ericsson contribute new module

### PR DESCRIPTION
**Pull request by Ansibleyou**
##### SUMMARY

Running command to manage Ericsson device by Ansible automatically.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

eric_eccli
##### ADDITIONAL INFORMATION

Achieving of running command to manage Ericsson device by Ansible automatically.

```paste below

```

### CODE REVIEW

**Comment by Ansibleyou** [comment]
bot_status

**Comment by Ansibleyou** [comment]
ready_for_review

**Comment by Ansibleyou** [comment]
cc @NilashishC @Qalthos @danielmellado @ganeshrn @justjais @rcarrillocruz @trishnaguha
Dear maintainer, what should I do next ? or should I wait ?

**Comment by Ansibleyou** [comment]
bot_status

**Comment by Ansibleyou** [comment]
bot_status

**Comment by Ansibleyou** [comment]
@trishnaguha  
Hi  dear maintainer ,what should  I do next?

**Comment by Ansibleyou** [comment]
ready_for_review

**Comment by itercheng** [comment]
The submit has been timeout.

**Pull request closed without merging**
