### PR TITLE
osx_defaults: diff support

### PR DESCRIPTION
**Pull request by ikemo3**
##### SUMMARY

Added diff support to osx_defaults module.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

osx_defaults

##### ADDITIONAL INFORMATION

example output is below.

```diff
TASK [defaults : osx_defaults] **************************************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-value: true
+value: false

changed: [127.0.0.1]
```

### CODE REVIEW

**Review by jamescassell — COMMENTED** [review]
Does it also work in check_mode?

**Comment by ikemo3** [comment]
I tested that works with check_mode.

In the code, check_mode only affects whether writing or not.
https://github.com/ikemo3/ansible/blob/be456d25f2b19d3acbf3abbbbd2e9616e5196a08/lib/ansible/modules/system/osx_defaults.py#L351

**Review by jamescassell — APPROVED** [review]
shipit

**Review by jamescassell — APPROVED** [review]
shipit

**Comment by ikemo3** [comment]
bot_status

**Pull request closed without merging**
