### PR TITLE
docker_* modules: fix various errors in argument specs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes errors detected by #65437 and #65476.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
docker_image
docker_image_info
docker_login
docker_stack
docker_swarm
docker_swarm_service

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
(Sorry, pushed commit to wrong branch...)

**Comment by felixfontein** [comment]
ready_for_review

**Review by tremble — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@tremble thanks for reviewing this!

**Pull request merged**
