### PR TITLE
ACI: Add signature-based authentication

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR adds signature-based authentication to all ACI modules.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ACI

##### ANSIBLE VERSION
v2.5

### CODE REVIEW

**Comment by dagwieers** [comment]
@cpaggen Please test !

**Comment by dagwieers** [comment]
@jmcgill298 @schunduri @brunocalogero @rsmeyers @cpaggen I'd like to get feedback on the implementation and user interface ASAP. We would like to get it out today if possible.

**Comment by rsmeyers** [comment]
Tested it, seems to be working
Will review later today with @cpaggen

**Comment by dagwieers** [comment]
@mattclay You know what is wrong with the tests ? I find the output very confusing to what is going on and why it is failing.

**Comment by gundalow** [comment]
@dagwieers I've hit rebuild. It's an was an issue in `devel` fixed on Friday

**Comment by rsmeyers** [comment]
recent changes look good for me

**Comment by cpaggen** [comment]
Tested multiple times successfully. Verified cert-auth does not perform as many APIC logins as REST requests. ACI 3.1's nginx rate-limiter never kicks in when using cert-auth.

**Pull request merged**
