### PR TITLE
Add support to use VAULT_TOKEN from the environment

### PR DESCRIPTION
**Pull request by cornfeedhobo**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

hashi_vault lookup plugin
##### ANSIBLE VERSION

n\a

```
ansible 2.1.1.0
```
##### SUMMARY

In the current script, one is required to set the token (a secure value), into a playbook.
This changes the default to pull it from the environment if not explicitly set.

Along the way, I did some general cleanup; please let me know if it's satisfactory.

### CODE REVIEW

**Comment by sivel** [comment]
Style changes are prohibited.  Please revert those specific changes.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

**Comment by cornfeedhobo** [comment]
@sivel Everything here is a PEP8 fix and basic python issues. e.g. using `if foo == True` instead of `if foo is True`. Please look and compare to the other lookup plugins, I am pretty sure I have brought this in line with python and ansible conventions.

**Comment by sivel** [comment]
PEP8 fixes are not accepted.  It breaks attribution, and typically the only people who make those changes are members of the core team, and even then it is infrequent.  Style changes are only permitted on lines that are part of a change for a feature or bug fix.

**Comment by cornfeedhobo** [comment]
That's just silly. Something this sloppy shouldn't have been committed in the first place. I'll maintain my own patch I guess.

**Comment by cornfeedhobo** [comment]
@defionscode After a bit of discussion on irc about this PR, are you still the active maintainer?

**Comment by juliedavila** [comment]
yes

**Comment by cornfeedhobo** [comment]
Well, they suggested I ping you and ask if you object to my changes.

**Comment by juliedavila** [comment]
I like it.

**Comment by cornfeedhobo** [comment]
@defionscode it has been made clear to me that the only way these changes will be merged, is if you do it manually. thanks.

**Comment by bcoca** [comment]
no, the feature is fine, the problem is the style changes. To merge it you just need to remove the style changes from the PR and leave just the feature.

**Comment by cornfeedhobo** [comment]
meh, ya'll can remove them, like i said, i give up. this is an absurd requirement that only scares off contributors. you have spent more time responding and "educating" me about the rules than would need to be spent on parsing this change for any future maintainers.

**Pull request closed without merging**
