### PR TITLE
[WIP] Enable templating and inline vaults for inventory plugins

### LINKED ISSUE #57012: Add  inline vault encryption for YAML inventory plugin source (config) files
##### SUMMARY
When defining a yaml config file for an inventory plugin, I typically want to use ansible vault to encrypt secrets to connect to an  external inventory source. This works perfectly when the full yaml file is encrypted in whole, but fails when values are encrypted inline.

##### ISSUE TYPE
~Bug  Report~
- Feature Idea

##### COMPONENT NAME
vault, inventory

##### ANSIBLE VERSION
at least since 2.6

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
just a local linux host

##### STEPS TO REPRODUCE
Use an Ansible inventory plugin ( not a script), and define a config file for it in yaml format. Encrypt the password *value* to connect to the external resource, in this file with vault inline, with e.g.

`echo -n s3cr3t | ansible-vault encrypt_string --stdin-name password`

##### EXPECTED RESULTS
This just works and the inventory plugin can connect to the external resource.

##### ACTUAL RESULTS
Plugin throws an error, as if the password is wrong. In reality, it is not decrypted, and the `AnsibleVaultEncryptedUnicode` string is passed as the password to the plugin.

### LINKED ISSUE #58281: Automatically template inventory config options
Automatically import existing variables and allow for templating of inventory config options by default for all plugins.

As a side effect, this should also allow for using inline vaults on options.

superset of #58213
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

inventory

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
Fixes #58281
Fixes #57012

Based on #58288. I moved the templating and decryption into ensure_type() since now it fails if the value is an inline vault or a templated var for an option that is not a string.

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Review by diego1q2w — APPROVED** [review]
Looking forward to seeing this on the next release :D

**Comment by s-hertel** [comment]
@diego1q2w Thanks. I have a couple other things I'm trying to finish up, and then I will rebase this. String inline vaults are now supported without this, so this should just add templating.

**Comment by angystardust** [comment]
@s-hertel when you say "now supported", you mean in 2.10/devel or in 2.9? :thinking:

**Comment by s-hertel** [comment]
@angystardust Support for 2.10 was added in https://github.com/ansible/ansible/pull/65023 and it was backported to 2.9 in https://github.com/ansible/ansible/pull/65090.

**Comment by angystardust** [comment]
> @angystardust Support for 2.10 was added in #65023 and it was backported to 2.9 in #65090.
uhm...that's very strange: I wasn't able to properly use inline vaulting in azure inventory plugin using a 2.9

**Comment by s-hertel** [comment]
After looking into this, I realized that the only time #65023 works for inventory plugins is if `type:` is not defined in the documentation (implicitly a string), but doesn't work when type is actually defined as a string, which is the case for most inventory plugins. I opened a PR to fix it.

**Pull request closed without merging**
