### PR TITLE
Fix Examples with bad options

### PR DESCRIPTION
**Pull request by carchi8py**
##### SUMMARY
Some modules were using options were using old names that have since been changed. 

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
* na_ontap_cg_snapshot.py
* na_ontap_cifs_acl.py
* na_ontap_cifs_server.py
* na_ontap_igroup_initiator.py
* na_ontap_ntp.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by lonico — APPROVED** [review]
shipit

**Review by samccann — COMMENTED** [review]
Can you also change -       https://github.com/ansible/ansible/blob/93f7fbcb0c969af34fd161a222507e3eccf262fe/lib/ansible/modules/storage/netapp/na_ontap_cifs_server.py#L74  so the description doesn't reference 'cifs_server_name' anymore?

**Comment by JohnLieske** [comment]
> Can you also change -
> 
> [ansible/lib/ansible/modules/storage/netapp/na_ontap_cifs_server.py](https://github.com/ansible/ansible/blob/93f7fbcb0c969af34fd161a222507e3eccf262fe/lib/ansible/modules/storage/netapp/na_ontap_cifs_server.py#L74)
> 
> Line 74 in [93f7fbc](/ansible/ansible/commit/93f7fbcb0c969af34fd161a222507e3eccf262fe)
> 
>        specified in 'cifs_server_name' exists in the Active Directory, it 
> so the description doesn't reference 'cifs_server_name' anymore?

@carchi8py  ^

**Comment by carchi8py** [comment]
I've made the change internally this morning, waiting for it to finish going through our internal process and then will push out the fix.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @carchi8py for the ansible doc update.

**Pull request merged**
