### PR TITLE
Allow specifying args directly to actions using module: syntax

### LINKED ISSUE #2228: complex args complain: None has invalid type
Hi. When I try to use the new complex args (with devel HEAD) it complains:

> ERROR: action specified for task mail: None has invalid type <type 'NoneType'>

My playbook is like so:

``` yaml

---
- hosts: ${hosts}
  tasks:
    - mail:
      args:
        subject: hello
```

### PR DESCRIPTION
**Pull request by dhozac**
Makes things like

```
- name: do complex things with complex module
  complex:
    setting_a: true
    setting_b:
    - foo
    - bar
```

possible.

Fixes #2228.

### CODE REVIEW

**Comment by dhozac** [comment]
Now with fixed action_plugins and allowing

```
- action:
    module: copy
    src: /path/to/file
    ...
```

too.

**Comment by mpdehaan** [comment]
taking a look at this now...

**Comment by mpdehaan** [comment]
merged in, pushing updates to docs shortly, thanks!

**Comment by mpdehaan** [comment]
ok, now actually pushed

**Pull request merged**
