### PR TITLE
updated metadata dump to do full docs dump

### PR DESCRIPTION
**Pull request by bcoca**
also minor refactor in other options
 by pushing common code into functions

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ansible-doc

### CODE REVIEW

**Comment by ssbarnea** [comment]
I think that this is likely the most useful addition to ansible core I seen in many yeast.

Still I was not able to figure it out on how to use it to dump documentation for all modules and all collections into a single file. Am I correct or this feature is still missing from this PR?

**Comment by sivel** [comment]
> Still I was not able to figure it out on how to use it to dump documentation for all modules and all collections into a single file. Am I correct or this feature is still missing from this PR?

This PR implements exactly that, except that it dumps to stdout.

```console
$ ansible-doc --metadata-dump > dump.json
```

It dumps every plugin (doc, examples, return), for every plugin type, for every collection (including builtins).

Using something like `jq` you can access the `DOCUMENTATION` of a callback from a collection like:

```console
$ ansible-doc --metadata-dump | jq '.all.callback."sivel.toiletwater.dump_stats".doc'
```

**Review by ganeshrn — COMMENTED** [review]
I tested this PR and it is working great. Thanks for doing it.
One minor comment can we add information about plugin redirection from `runtime.yml` file in the JSON doc dump? 
For projects like `ansible-language-server` it will make it easier to get the list of all the plugins names (including redirections) with a single command and provide it as an auto-completion response to code editors using the server.

**Comment by bcoca** [comment]
@ganeshrn this PR will not add extra info, just dump what we have. I am working on diff PR that will add runtime info to the listing (which then will automatically be dumped by this facility), but the original design was to 'find' not to 'list' so it is not an easy endeavor

**Comment by ganeshrn** [comment]
@bcoca Thanks for the update.

**Review by ganeshrn — APPROVED** [review]
Looks good from a functionality aspect.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
