### PR TITLE
New module - postgresql_set

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY

postgresql_set: Change a PostgreSQL server configuration parameter

   - Allows to change a PostgreSQL server configuration parameter.
   - The module uses ALTER SYSTEM command U(https://www.postgresql.org/docs/current/sql-altersystem.html) and apply changes by reload server configuration.
   - ALTER SYSTEM is used for changing server configuration parameters across the entire database cluster.
   - It can be more convenient than the traditional method of manually editing the postgresql.conf file.
   - ALTER SYSTEM writes the given parameter setting to the $PGDATA/postgresql.auto.conf file,
     which is read in addition to postgresql.conf U(https://www.postgresql.org/docs/current/sql-altersystem.html).
   - The module allows to reset parameter to boot_val (cluster initial value) or remove parameter string from postgresql.auto.conf and reload.
   - After change you can see in ansible output the previous and the new parameter value and other information using returned values and M(debug) module.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

postgresql_set
##### ADDITIONAL INFORMATION

   - Check_mode is not supported because ALTER SYSTEM can't be run inside a transaction block
     U(https://www.postgresql.org/docs/current/sql-altersystem.html).
   - Supported version of PostgreSQL is 9.4 and later.
   - For some parameters restart of PostgreSQL server is required.
     See official documentation U(https://www.postgresql.org/).
   - The default authentication assumes that you are either logging in as or
     sudo'ing to the postgres account on the host.
   - This module uses psycopg2, a Python PostgreSQL database adapter. You must
     ensure that psycopg2 is installed on the host before using this module. If
     the remote host is the PostgreSQL server (which is the default case), then
     PostgreSQL must also be installed on the remote host. For Ubuntu-based
     systems, install the postgresql, libpq-dev, and python-psycopg2 packages
     on the remote host before using this module.

##### EXAMPLES
```
# Restore wal_keep_segments parameter to initial state
- postgresql_set:
    name: wal_keep_segments
    reset: yes

# Set work_mem parameter to 32MB and show what's been changed and restart is required or not
# (output example: "msg": "work_mem 4MB >> 64MB restart_req: False")
- postgresql_set:
    name: work_mem
    value: 32mb
    register: set_value

- debug:
    msg: "{{ set_value.name }} {{ set_value.prev_val }} >> {{ set_value.cur_value }} restart_req: {{ set_value.restart_required }}"
  when: set_value.changed
# Ensure that the restart of PostgreSQL serever must be required for some parameters.
# In this situation you see the same parameter in prev_val and cur_value, but 'changed=True'
# (Of course, if you passed the value that was different from the current server setting).

# Set log_min_duration_statement parameter to 1 second
- postgresql_set:
    name: log_min_duration_statement
    value: 1s

# Set wal_log_hints parameter to default value (remove parameter from postgresql.auto.conf)
- postgresql_set:
    name: wal_log_hints
    value: default
```

### CODE REVIEW

**Comment by Andersson007** [comment]
shipit

**Comment by Andersson007** [comment]
bot_status

**Comment by Andersson007** [comment]
I'm in progress to fix it

**Comment by Andersson007** [comment]
shipit

**Comment by Andersson007** [comment]
I don't see why the validate-modules check failed because I haven't changed anything related with kw and the RETURNS block. At the first time this shippable check returned success.
In my system "Sanity check using validate-modules" (and others) has finished without any errors.

**Comment by mattclay** [comment]
@Andersson007 validate-modules was recently updated to more strictly enforce types.

Use `bool` instead of `boolean` and `str` instead of `string` for types.

**Comment by Andersson007** [comment]
> @Andersson007 validate-modules was recently updated to more strictly enforce types.
> 
> Use `bool` instead of `boolean` and `str` instead of `string` for types.

Fixed. Thanks a lot!

**Comment by Andersson007** [comment]
shipit

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
I'm going to rewrite it partially and add integration_tests.

**Pull request closed without merging**
