### PR TITLE
docker_swarm: hopefully fix debug CI problems, and fix check mode

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
There seems to be a problem with the docker_swarm module. This PR is to try debugging what's going on.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_swarm
docker_node
docker_config

### CODE REVIEW

**Comment by felixfontein** [comment]
https://app.shippable.com/github/ansible/ansible/runs/109588/58/tests
https://app.shippable.com/github/ansible/ansible/runs/109593/63/tests
It is interesting that before this call, there's a call to docker_swarm with `state: absent`, and it does nothing. Also, this error should not happen since the module first checks whether the node is in a swarm. So it looks a bit like the swarm node detection is not working.

**Comment by felixfontein** [comment]
Interestingly, the swarm is there, but the node ID is an empty string:
```
{
    "ID":"SIQB:CBA3:ICTR:SGYD:UGJ3:APPN:3URH:ZYZO:EP2C:5ZDW:XJTE:L3NM",
    "Containers":3,
    "ContainersRunning":3,
    "ContainersPaused":0,
    "ContainersStopped":0,
    "Images":29,
    "Driver":"overlay2",
    "DriverStatus":[["Backing Filesystem", "extfs"], ["Supports d_type", "true"], ["Native Overlay Diff", "true"]],
    "SystemStatus":null,
    "Plugins":{
        "Volume":["local"],
        "Network":["bridge", "host", "macvlan", "null", "overlay"],
        "Authorization":null,
        "Log":["awslogs", "fluentd", "gcplogs", "gelf", "journald", "json-file", "logentries", "splunk", "syslog"]
    },
    "MemoryLimit":true,
    "SwapLimit":false,
    "KernelMemory":true,
    "CpuCfsPeriod":true,
    "CpuCfsQuota":true,
    "CPUShares":true,
    "CPUSet":true,
    "IPv4Forwarding":true,
    "BridgeNfIptables":true,
    "BridgeNfIp6tables":true,
    "Debug":false,
    "NFd":48,
    "OomKillDisable":true,
    "NGoroutines":81,
    "SystemTime":"2019-02-22T16:07:08.872339027Z",
    "LoggingDriver":"json-file",
    "CgroupDriver":"cgroupfs",
    "NEventsListener":0,
    "KernelVersion":"4.4.0-1075-aws",
    "OperatingSystem":"Ubuntu 16.04.3 LTS",
    "OSType":"linux",
    "Architecture":"x86_64",
    "IndexServerAddress":"https://index.docker.io/v1/",
    "RegistryConfig":{
        "AllowNondistributableArtifactsCIDRs":[],
        "AllowNondistributableArtifactsHostnames":[],
        "InsecureRegistryCIDRs":["127.0.0.0/8"],
        "IndexConfigs":{
            "docker.io":{
                "Name":"docker.io",
                "Mirrors":[],
                "Secure":true,
                "Official":true
            }
        },
        "Mirrors":[]
    },
    "NCPU":2,
    "MemTotal":3945467904,
    "GenericResources":null,
    "DockerRootDir":"/data",
    "HttpProxy":"",
    "HttpsProxy":"",
    "NoProxy":"",
    "Name":"ip-172-31-6-97",
    "Labels":[],
    "ExperimentalBuild":false,
    "ServerVersion":"18.03.1-ce",
    "ClusterStore":"",
    "ClusterAdvertise":"",
    "Runtimes":{
        "runc":{
            "path":"docker-runc"
        }
    },
    "DefaultRuntime":"runc",
    "Swarm":{
        "NodeID":"",
        "NodeAddr":"172.17.0.4",
        "LocalNodeState":"active",
        "ControlAvailable":true,
        "Error":"rpc error: code = FailedPrecondition desc = grpc: the client connection is closing",
        "RemoteManagers":null,
        "Cluster":{
            "ID":"",
            "Version":{},
            "CreatedAt":"0001-01-01T00:00:00Z",
            "UpdatedAt":"0001-01-01T00:00:00Z",
            "Spec":{
                "Labels":null,
                "Orchestration":{},
                "Raft":{
                    "ElectionTick":0,
                    "HeartbeatTick":0
                },
                "Dispatcher":{},
                "CAConfig":{},
                "TaskDefaults":{},
                "EncryptionConfig":{"AutoLockManagers":false}
            },
            "TLSInfo":{},
            "RootRotationInProgress":false,
            "DefaultAddrPool":null,
            "SubnetSize":0
        }
    },
    "LiveRestoreEnabled":false,
    "Isolation":"",
    "InitBinary":"docker-init",
    "ContainerdCommit":{
        "ID":"773c489c9c1b21a6d78b5c538cd395416ec50f88",
        "Expected":"773c489c9c1b21a6d78b5c538cd395416ec50f88"
    },
    "RuncCommit":{
        "ID":"4fc53a81fb7c994640722ac585fa9ca548971871",
        "Expected":"4fc53a81fb7c994640722ac585fa9ca548971871"
    },
    "InitCommit":{
        "ID":"949e6fa",
        "Expected":"949e6fa"
    },
    "SecurityOptions":["name=apparmor", "name=seccomp, profile=default"],
    "Warnings":null
},
```

**Comment by felixfontein** [comment]
Hmm, it seems to be more complicated. The node ID is also empty when the docker daemon is not in Swarm mode; here (docker not in swarm mode), it looks like:
```
"Swarm":{
  "NodeID":"",
  "NodeAddr":"",
  "LocalNodeState":"inactive",
  "ControlAvailable":false,
  "Error":"",
  "RemoteManagers":null
}
```
The most obvious differences are `LocalNodeState` (`active` vs. `inactive`) and `ControlAvailable` (`true` vs. `false`).

**Comment by felixfontein** [comment]
Hmm, now I got some strange timeouts: https://app.shippable.com/github/ansible/ansible/runs/109737/58/tests

**Comment by felixfontein** [comment]
@tbouvet @WojciechowskiPiotr if you have any idea what could be the problem...

**Comment by WojciechowskiPiotr** [comment]
Are you testing it on `docker_config` integration tests playbook or something else? Local socket or over TCP?

**Comment by felixfontein** [comment]
The swarm module fails during the initialization phase of the docker_config integration tests, possibly caused by something run earlier. During the runs where I saw this error first, a lot of other tests were run before, but on the CI runs in this PR, only setup_docker is executed before docker_config tests start, and then in the docker_config tests, it now dies when trying to remove the Swarm (and before, when it tried to make sure the swarm was around).

On both the CI node where it fails, and on other CI nodes, the same docker versions are running: `Docker CLI version: 18.09.2; Docker API version: 1.37; docker-py library version: 3.7.0`

**Comment by felixfontein** [comment]
(I haven't run this locally yet. On CI, it is using docker-in-docker with local connection (socket).)

**Comment by WojciechowskiPiotr** [comment]
The only difference on my host is that API is 1.39, not 1.37. I am not sure why 1.37 is in use in Shippable. I see the latest tests succeeded.

**Comment by felixfontein** [comment]
Hmm, whyever it works this time... Maybe it's a random problem? I'll restart the tests, and if it still passes, I'll do a rebuild_merge tomorrow morning (so we get another CI run).

This will probably create a conflict with #52886, but I want to merge this first as it hopefully improves the situation for other PRs.

**Comment by felixfontein** [comment]
Re-triggering CI.

**Comment by felixfontein** [comment]
Ok, that was quick. Let's try another rebuild_merge. (I guess it won't automerge because of the changelog fragment, but let's see...)

rebuild_merge

**Comment by felixfontein** [comment]
About 1.37 vs. 1.39: for the shippable docker CI runs, docker-in-docker is used, so while the newest CLI is installed, it uses the daemon running on the CI nodes. The CI nodes are only updated from time to time, so they are probably still running an older docker daemon.

**Pull request merged**
