### PR TITLE
with_items is obsolete - using loop instead

### PR DESCRIPTION
**Pull request by ruzickap**
##### SUMMARY
with_items is obsolete - using loop instead

### CODE REVIEW

**Comment by dagwieers** [comment]
I don't mind this, but at this time it is not obsolete or deprecated (yet). Both are supported.

@acozine Did we decide to rewrite all examples uniformly to using `loop:` ? Or is there such plan ?

**Comment by ruzickap** [comment]
You are right...
But new "documentation" (latest / devel) should contain `loop` examples only - but it's just my opinion.

**Comment by dagwieers** [comment]
@ruzickap Let's see what the Docs Working Group says about this. In any case, I would prefer a single update operation, rather than one PR per file/module. If you are interested to help out in Docs-related discussions/actions, you can join the Docs WG meetings ! https://github.com/ansible/community/wiki/Docs

**Comment by samdoran** [comment]
rebuild_merge

**Pull request merged**
