### PR TITLE
Adding aruba_config module

### PR DESCRIPTION
**Pull request by jmighion**
##### SUMMARY

New module `aruba_config`

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

aruba_config
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (aruba_config 4792b1f615) last updated 2017/07/20 11:27:57 (GMT -700)
  config file = /Users/james/.ansible.cfg
  configured module search path = [u'/Users/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/james/Documents/work/git/ansible/lib/ansible
  executable location = /Users/james/Documents/work/git/ansible/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### CODE REVIEW

**Comment by jmighion** [comment]
shipit

**Comment by jmighion** [comment]
shipit

**Comment by jmighion** [comment]
Unstable. Closing and reopening.

**Review by gundalow — APPROVED** [review]
Would be good to get someone else in the team to have a quick look at this

**Pull request merged**
