### PR TITLE
Fix code blocks, improve english grammar in docsite/rst/test_strategies.rst

### PR DESCRIPTION
**Pull request by dflock**
##### Issue Type:
- Docs Pull Request
##### Ansible Version:

n/a
##### Summary:

Fix code blocks, improve english grammar in docsite/rst/test_strategies.rst
- Fixed the yaml code-blocks to be valid rst & display correctly
- Improved the english for the opening sentence of the 'Testing Lifecycle' section.
##### Example output:

n/a

### CODE REVIEW

**Comment by bcoca** [comment]
`::` is valid rst afaik, and the default block type is already yaml, not sure if that fix is needed.

**Comment by dflock** [comment]
You're probably correct - although the rst documentation (that I could find) is very unclear about this. Making it explicit does make the editing experience _much_ better though, as your editor can then highlight/lint/etc... the contents of the code block.

Also the original document was inconsistent - the first block was explicit, with the rest not. Maybe do it one way or the other?

I'm not sure what the convention is in the Ansible documentation for this, so if you want implicit blocks everywhere, then obviously, feel free to close this pull request. I could then put the grammar fix in another PR, as I should have done originally.

**Comment by bcoca** [comment]
cc @docschick 2c?

**Comment by docschick** [comment]
Just using :: for the code blocks is valid rst: http://www.sphinx-doc.org/en/stable/rest.html#source-code 

I guess I don't see the need in setting the code block explicitly as yaml or anything else (like http://www.sphinx-doc.org/en/stable/markup/code.html), just using :: has been enough for me.  

My personal vote is to keep them simple and standardize on ::  but if contributors want to make them explicit for their own linting needs, etc., that's cool. I'm not against it, just don't see it as always necessary, especially for the simpler code block examples.

**Pull request closed without merging**
