### PR TITLE
Huawei: Add new module to peering

### PR DESCRIPTION
**Pull request by zhongjun2**
SUMMARY
Add a new modules hwc_vpc_peering_connect that can fetch huaweicloud Simple Message Notification.

COMPONENT NAME
lib/ansible/modules/cloud/huawei/hwc_vpc_peering_connect.py

ISSUE TYPE
New Module Pull Request

ANSIBLE VERSION
ansible 2.10

ADDITIONAL INFORMATION
I have tested the changes on the real environment.

### CODE REVIEW

**Comment by zengchen1024** [comment]
shipit

**Comment by zhongjun2** [comment]
-label affects_2.9
+label affects_2.10

**Comment by zhongjun2** [comment]
-label affects_2.9
+label affects_2.10

**Comment by niuzhenguo** [comment]
shipit

**Comment by niuzhenguo** [comment]
shipit

**Comment by zhongjun2** [comment]
ready_for_review

**Comment by TommyLike** [comment]
shipit

**Comment by TommyLike** [comment]
lgtm

**Pull request merged**
