### PR TITLE
Add some examples for local_action and rsync

### PR DESCRIPTION
**Pull request by tgerla**

### CODE REVIEW

**Comment by mpdehaan** [comment]
Yep, should be be mentioned or could cause some confusion.

**Comment by tgerla** [comment]
OK, good point. How's this?

**Comment by mpdehaan** [comment]
merged, thanks!   Will be in next doc-build/push.

**Comment by iamveen** [comment]
This example might be useful. Instead of sudo'ing on local machine, use sudo remotely. I dropped the -a because I didn't want to retain ownership info.

This only works with passwordless sudo on the remote machine.

```
- name: sync openvpn keys
  sudo: no
  local_action: command rsync --rsync-path='sudo rsync' -rpt
                files/fileserver/keys
                {{ansible_ssh_host or inventory_hostname}}:/etc/openvpn/
```

**Pull request merged**
