### PR TITLE
centralize doc/config plugin lists

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
also update list for generation in docsite

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

plugins
##### ANSIBLE VERSION

```
2.5-2.6
```

### CODE REVIEW

**Comment by abadger** [comment]
This looks good to me +1.  CC'ing @dharmabumstead since there's updates to the wording in the template.

**Review by dharmabumstead — APPROVED** [review]
Doc updates look good - thanks @bcoca!

**Comment by abadger** [comment]
Build failures look unrelated but I'm hitting rebuild just in case.

**Comment by abadger** [comment]
cherry-picked to 2.5

**Pull request merged**
