### PR TITLE
new airbrake_deployment module

### PR DESCRIPTION
**Pull request by bpennypacker**
This is my first attempt at a full Ansible module, and it's a pretty simple one.  It sends a notification to Airbrake (http://airbrake.io) of a new deployment, per the API documented at http://help.airbrake.io/discussions/questions/412-deploy-notification-via-api

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged, thanks very much!

**Comment by drewda** [comment]
@bpennypacker Not sure if this is the appropriate place to raise a vaguely related topic... if not, my apologies.

I've been using [Errbit](https://github.com/errbit/errbit), an open-source, self-hosted equivalent to Airbrake, with a compatible API. Just wondering, could this module be extended slightly to allow a user to optionally override the airbrake.io endpoint with a hostname of their own?

**Comment by jctanner** [comment]
@drewda it would be better to discuss this on the list or file a feature request.

**Comment by bpennypacker** [comment]
@drewda - this should be easy enough to implement, although I don't have an environment to test it on.  If you want do as @jctanner suggested and file a feature request then let me know.  I should be able to make the changes fairly quickly and let you test it out for me before having it merged.

**Comment by drewda** [comment]
Sounds good. Thank you, both!

**Pull request merged**
