### PR TITLE
update extra requirements for azure

### PR DESCRIPTION
**Pull request by sputnik13**
##### SUMMARY
Extra requirements for azure are out of date respective to the released
versions from Microsoft, and which are used by az-cli et al.  This prevents
use of newer API features and/or causes ansible azure modules to fail to
execute if they depend on newer azure python module versions.

Additionally, if ansible and azure-cli are installed in the same python virtual
environment, the update to azure python sdk libs, by azure-cli, cause errors
in ansible azure modules due to version incompatibility.

Updating requirements-azure.txt to bring azure python modules' versions
to parity with those used by az-cli 2.0.74.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
requirements-azure.txt

##### ADDITIONAL INFORMATION
While working on an improvement for an azure ansible module, we noticed that the version of azure-mgmt-* libs being loaded when installing ansible with pip install ansible[azure] were all fairly out of date.  This isn't so noticeable when the same python environment is used to install az-cli, which ends up updating all of the azure-mgmt-* libs, but any modules written and tested in such an environment can fail to run in a more "bare bone" python environment with just ansible[azure] installed.

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@mybayern1974 @nitzmahone Please help review this PR and push for merge! Thank you very much!

**Comment by AlanCoding** [comment]
Commenting so I'll get notifications on this, will need to update https://github.com/ansible/awx/blob/9745bfbdb489ef59a52b08968a351e298a1b7d46/requirements/requirements_ansible.in#L8 when it lands

**Comment by Fred-sun** [comment]
ping to merge

**Comment by sputnik13** [comment]
@Fred-sun @mybayern1974 @nitzmahone this PR has been open for almost 3 months, just a dependency requirements change, how can we get this moving?

**Comment by Fred-sun** [comment]
@sputnik13 This is under review and cannot be combined until it is confirmed and tested. I will urge the merger as soon as possible. Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Contributors are very concerned about the progress of this PR. Can you help review and promote the merger? Thank you very much!

**Comment by AlanCoding** [comment]
Some background from prior similar PR: https://github.com/ansible/ansible/pull/61238#issuecomment-527998744

**Comment by nitzmahone** [comment]
My same [comment from before](https://github.com/ansible/ansible/pull/61238#issuecomment-527998744) still applies- it's impossible to expect that Ansible and Azure CLI can share the same venv (which is why Azure CLI installs to its own venvs in all the official OS packages). Dependencies are only updated when a module needs to use new features, which causes the need to re-test (and often re-write) a lot of code. Some of the newer Azure modules are being written/generated against lower-level REST API components, which mitigates the need to update them as often (and also makes them more likely to function properly under newer versions of the SDK), but there's a lot of stuff still using the typed SDK. Recommend close.

**Comment by nitzmahone** [comment]
cc @anshulbehl @thedoubl3j

**Comment by Fred-sun** [comment]
@sputnik13 Can you help resolve the conflict files when you are free? It will push for PR review and meger! Thank you very much!

**Comment by Fred-sun** [comment]
@sputnik13 Thank you for taking the time to contribute to this PR. We will transfer ansible 's azure module related Issue and PR to azure collection (https://github.com/ansible-collections/azure/pulls), can you transfer the Issue to azure collection repo?

**Comment by Akasurde** [comment]
Hi @sputnik13, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
