### PR TITLE
Allow you to pass in arbitrary rsync options

### PR DESCRIPTION
**Pull request by jjshoe**

### CODE REVIEW

**Comment by jjshoe** [comment]
Wasn't sure what to put in for the default for an empty array.

**Comment by jjshoe** [comment]
Probably wouldn't hurt to add an example for this in the future. Happy to address both doc issues as another pull request if anyone has input.

**Comment by jctanner** [comment]
@jjshoe please add at least one example in the docstrings.

**Comment by jctanner** [comment]
Sorry to nitpick, but please make the example use complex args format ...

```
foo:
  - bar
  - baz
```

**Comment by jjshoe** [comment]
Per irc, use https://github.com/ansible/ansible/blob/devel/library/cloud/ec2#L354-L365 as an example

**Comment by jctanner** [comment]
@jjshoe while testing this, I realized that the synchronize action plugin doesn't actually handle complex args properly in the case where rsync_opts is a list. I've merged your PR as is, because we can't actually show a complex args example. I'll file a bug to fixup synchronize's ability to use complex args at some point in the future.

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/issues/6951

**Pull request merged**
