### PR TITLE
Minimize output of actionable callback plugin

### PR DESCRIPTION
**Pull request by t2d**
##### SUMMARY
This PR minimizes the output of the [actionable callback plugin](https://docs.ansible.com/ansible/2.5/plugins/callback/actionable.html).

* Only print playbook banner, when a task has changed/failed
* Only print stats, when a task has changed/failed

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
actionable callback plugin

##### ANSIBLE VERSION
ansible >= 2.0

##### ADDITIONAL INFORMATION
Example output of https://github.com/t2d/ansible-raspberrypi/

before:
```
ANSIBLE_STDOUT_CALLBACK=actionable DISPLAY_SKIPPED_HOSTS=no ansible-playbook playbook.yml --check
PLAY [pi] *******************************************************************************************

PLAY [pi] *******************************************************************************************

TASK [elboletaire.transmission : Make sure transmission is not running] *****************************
changed: [pi]

TASK [elboletaire.transmission : Copy Transmission configuration] ***********************************
changed: [pi]

PLAY RECAP ******************************************************************************************
pi                         : ok=38   changed=3    unreachable=0    failed=0  
```

after: 
```
ANSIBLE_STDOUT_CALLBACK=actionable DISPLAY_SKIPPED_HOSTS=no ansible-playbook playbook.yml --check

PLAY [pi] *******************************************************************************************

TASK [elboletaire.transmission : Make sure transmission is not running] *****************************
changed: [pi]

TASK [elboletaire.transmission : Copy Transmission configuration] ***********************************
changed: [pi]

PLAY RECAP ******************************************************************************************
pi                         : ok=38   changed=3    unreachable=0    failed=0  
```

without change (produces no output):
```
ANSIBLE_STDOUT_CALLBACK=actionable DISPLAY_SKIPPED_HOSTS=no ansible-playbook playbook.yml --check -t samba
```

### CODE REVIEW

**Comment by t2d** [comment]
Can you please re-run the failed checks? I don't believe it has anything to do with my code.

**Comment by t2d** [comment]
I updated the code to make sure, that variables in task names are parsed correctly

**Comment by t2d** [comment]
I rebased my PR and all checks are fine. Can somebody please take a look at it? Also, I'm using this patch in production already: https://github.com/systemli/ansible-drift/

**Comment by agaffney** [comment]
The `actionable` callback plugin has been deprecated in `devel` in favor of similar functionality added to the `default` callback plugin, so it probably makes more sense to add this over there. You are also removing code that is necessary for the plugin to work properly with `strategy: free` and loop tasks with templates in the task name.

**Pull request closed without merging**
