### PR TITLE
Add run_command to module_common and update modules

### PR DESCRIPTION
**Pull request by sfromm**
Related to issue #1738.  I've tested most of the modules except for fireball, mount, subversion, supvervisorctl, and svr4pkg.  

Please comment.  If all looks good, I can go ahead and merge it.

### CODE REVIEW

**Comment by mpdehaan** [comment]
nice! (does not imply actual review, just glad to see this!)

**Comment by dhozac** [comment]
I think args should be allowed (recommended?) to be a list and to only shlex.split if it's not. In general, most commands that take input from the user probably should use lists for args so we can avoid quoting issues for data with spaces in it. (Spaces, the root of all evil.)

**Comment by sfromm** [comment]
@dhozac How about:  Drop shell=(True|False) as a keyword argument to run_command().  If args is a list, invoke Popen() with shell=False; if args is a string, shell=True.  I would think that would then avoid the problems with quoting and spaces.

**Comment by dhozac** [comment]
Yeah, shell=True and a list likely shouldn't happen at the same time. If there ever is a need for it, we can revisit then...

**Comment by mpdehaan** [comment]
Yeah, it seems easiest to just use shell=True exactly like subprocess.

People know the subprocess API, don't make them guess too much.

**Comment by sfromm** [comment]
Decided to clean this up and resubmit.

**Pull request closed without merging**
