### PR TITLE
cloud: ovirt: present state shouldn't change state if not needed

### LINKED ISSUE #27382: ovirt_vms: state:present shouldn't start VM if off
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ovirt_vms.py
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 7351ee9a76) last updated 2017/07/27 08:17:59 (GMT -600)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rgroten/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rgroten/git/ansible/lib/ansible
  executable location = /home/rgroten/git/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Running ovirt_vms module with state:present on a VM that is powered off will result in it being powered on.  This is unexpected as there is a state:started that should be used instead.

##### STEPS TO REPRODUCE

```
yaml
      - name: Create VM
        ovirt_vms:
            auth: "{{ ovirt_auth }}"
            state: present
            name: vm1.example.com
        register: my_vm
```

##### EXPECTED RESULTS

state:present should not change the running state of the VM.  stopped/started should instead be used
##### ACTUAL RESULTS

VM is powered on if off

### PR DESCRIPTION
**Pull request by machacekondra**
This PR fixes: https://github.com/ansible/ansible/issues/27382

##### SUMMARY

Previously when VM had defined `state=present` we used to always start the VM, currently when user uses `state=present` and VM is stopped, we dont' start the VM. If user need to start the VM, he should use `state=started`.

Same for hosts. Previously we used `state=present` to activate the host. Now, if user want to actiave the host he should use parameter `activate=true`. Default value is `true` in order to achieve backward compatibility. 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

ovirt_vms
ovirt_hosts

##### ANSIBLE VERSION

```
2.3.1
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina @ryansb shipit

**Review by mwperina — APPROVED** [review]
Looks good to me, thanks! 👍

**Comment by mwperina** [comment]
shipit

**Comment by mwperina** [comment]
@ryansb

Ryan, could you please merge?

**Comment by ryansb** [comment]
needs_revision

**Comment by machacekondra** [comment]
Resolved conflicts.

**Review by mwperina — APPROVED** [review]
👍 shipit

**Review by ryansb — APPROVED** [review]

**Pull request merged**
