### PR TITLE
Add read support on module etcd3. (#42125)

### PR DESCRIPTION
**Pull request by vasartori**
##### SUMMARY

Add support to only read data on etcd3 kv as consul_kv modules does.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

etcd3
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.7.0.dev0
  config file = None
  configured module search path = [u'/home/victor/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/victor/.local/lib/python2.7/site-packages/ansible
  executable location = /home/victor/.local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### ADDITIONAL INFORMATION

Playbook used:
```yaml
- name: test
  hosts: localhost
  tasks:
  - name: etcd3
    etcd3:
      key: "foo"
    register: foo
  
  - name: debug
    debug:
     msg: "{{foo.value}}"
```

*BEFORE*
```
ansible-playbook etcd.yaml 
PLAY [test] ************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [localhost]

TASK [etcd3] ***********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: value, state"}
	to retry, use: --limit @/home/victor/etcd.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
*AFTER*
```
$ ansible-playbook etcd.yaml 
PLAY [test] ************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [localhost]

TASK [etcd3] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "bar"
}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by maxamillion** [comment]
Reading information from etcd is normally done with the [etcd lookup plugin](https://docs.ansible.com/ansible/latest/plugins/lookup/etcd.html), is there an use case that does not satisfy the requirements of?

**Comment by vasartori** [comment]
Hi @maxamillion 
The plugin etcd3 writes data on v3 backends who use grpc. 
Retrieve data from lookup module works only in v2 backend (http) 

This PR add a simple way to get data from etcd using v3 backend.

Take a look on this simple playbook test:

```yaml
- name: Test
  hosts: localhost
  become: false

  tasks:
   - name: set data on etcd using etcd3 module 
     etcd3:
       key: "foo"
       value: "baz"
       state: "present"

   - name: get data on etcd using etcd3 module
     etcd3:
       key: "foo"
     register: foo

   - name: print data on foo register
     debug:
       msg: "{{ foo.value }}"
   
   - name: print data using lookup etcd
     debug: 
       msg: "{{ lookup('etcd','foo',version='v2',url='http://127.0.0.1:2379') }}"
```
Output:

```
$ ansible-playbook etcd.yaml 
PLAY [Test] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************
ok: [localhost]

TASK [set data on etcd using etcd3 module] ***********************************************************************************************************************************************************
changed: [localhost]

TASK [get data on etcd using etcd3 module] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [print data on foo register] ********************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "baz"
}

TASK [print data using lookup etcd] ******************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}

PLAY RECAP *******************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0  ```

**Comment by maxamillion** [comment]
I follow the requirement change, but it seems to introduce inconsistency in user experience for users retrieving data from etcd2 vs etcd3.

I'd personally prefer the addition of an etcd3 lookup plugin over the addition of a `get` functionality to the module.

**Comment by vasartori** [comment]
I understand, but why we don't do as consul_kv module?
For me sounds more natural get a data at the same place we store data.

**Comment by maxamillion** [comment]
I've added it to the [core development community irc meeting](https://github.com/ansible/community/tree/master/meetings) agenda for discussion.

**Comment by vasartori** [comment]
Thanks!

**Comment by evrardjp** [comment]
Please see the conversation here: https://meetbot.fedoraproject.org/ansible-meeting/2018-07-12/ansible_core_public_irc_meeting.2018-07-12-15.06.log.html

**Comment by vasartori** [comment]
OK! We will work on a lookup module in a new PR...
Thanks for all!

**Pull request closed without merging**
