### PR TITLE
Further cleanup of integration test inventory.

### PR DESCRIPTION
**Pull request by mattclay**
##### SUMMARY

Further cleanup of integration test inventory.

##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

integration test inventory

### CODE REVIEW

**Comment by mattclay** [comment]
@dagwieers You originally added the inventory entries that are being removed. They don't appear to be used by any of the tests. Is there any value in preserving them anywhere?

**Comment by dagwieers** [comment]
@mattclay They are required for the ACI and MSC integration tests, but require the user to fill in specifics.

**Comment by dagwieers** [comment]
Hmm, not these ones though, the ones in inventory.networking.

**Comment by mattclay** [comment]
@dagwieers Does that mean these entries should exist in:

https://github.com/ansible/ansible/blob/devel/test/integration/inventory.networking.template

Perhaps as comments?

**Comment by dagwieers** [comment]
@mattclay I don't know what the purpose is of all these files, fact is that if I want to make this work, I need to add these entries in inventory.networking. And if I want my users/contributors to use the integration tests, they need to set these entries too. The entries for ACI actually work out of the box with the demo ACI infrastructure from Cisco DevNet.

I'd prefer if they weren't commented out, as they shouldn't influence anyone else.

**Comment by mattclay** [comment]
@dagwieers It should be safe to move them to the networking template and leave them uncommented, so I'll do that. Users will still need to create the inventory.networking file as they do now -- but at least the values they need will be in the template instead of the wrong inventory file.

**Comment by dagwieers** [comment]
~If ansible-test had an `-i` option to provide a custom inventory, this could live somewhere else as well.~ It has this option as `--inventory`.
Currently I have it documented here: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general_aci.html#testing-aci-integration-tests

**Comment by mattclay** [comment]
@dagwieers It does: `ansible-test network-integration --inventory PATH`

**Comment by mattclay** [comment]
The `--inventory` option is only available for the `network-integration` command, which is what the `aci` module tests fall under. It appears those docs are out-of-date since they reference the `integration` command instead.

**Comment by mattclay** [comment]
@dagwieers Is the Cisco DevNet demo infrastructure something we could run as part of CI?

**Comment by dagwieers** [comment]
No, because it is not reliable. I would really like to have some automated testing, but all my requests fell on deaf ears.

**Comment by dagwieers** [comment]
Those docs are using `ansible-test network-integration` AFAICT.

**Comment by mattclay** [comment]
@dagwieers Ah, yes, you're right. I had read down to the next section which uses the `integration` command.

**Comment by mattclay** [comment]
@dagwieers What isn't reliable about the Cisco DevNet demo infrastructure? Where were you requests about the testing directed?

**Comment by mattclay** [comment]
Oh, actually I see that that entire doc you referenced is for ACI, so it should be referencing `network-integration` in the last section too: 

https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general_aci.html#testing-for-test-coverage

**Comment by dagwieers** [comment]
It is unavailable often (as anyone has admin rights, people can easily mess it up, like change the admin password or trash the system). If it works, it is a convenience, but it often isn't and you'll have to wait until the system is being reprovisioned.

**Pull request merged**
