### PR TITLE
Fixes #37731 Create Internal Loadbalancers with azure_rm_loadbalancer, support SKU

### LINKED ISSUE #37731: Possibility to create Internal Loadbalancers with azure_rm_loadbalancer
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_loadbalancer

##### ANSIBLE VERSION
```
ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dgermain/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
#empty return
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In azure console, you can create type "Public" loadbalancers with a public IP or type "Interal" loadbalancers using private IP address generated within a virtual network/subnet pair.

##### STEPS TO REPRODUCE
As far as I can tell, you don't have this "type" option in the ansible module

##### EXPECTED RESULTS
Have an option (or another module if the code is too much different) to allow internal loadbalancer creation

##### ACTUAL RESULTS
No option to do so

### LINKED ISSUE #38997: Support SKU for azure loadbalancer
The loadbalancer should support the SKU option with choices `basic` and `standard` from the latest API version

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

azure_rm_loadbalancer

##### ANSIBLE VERSION

```
2.5.0
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by yuwzho**
##### SUMMARY

Fixes #37731
Fixes #38997

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

azure_rm_loadbalancer

##### ANSIBLE VERSION

```
2.6.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by yuwzho** [comment]
@zwindler Could you please try this new feature to create internal loadbalancer.

Before you run your playbook, you need to install changes by running
```bash
nsible-galaxy install git+https://github.com/Azure/azure_preview_modules.git,internal-loadbalancer
```

And sample playbook tasks can be:

```yaml
---
- name: Create an internal load balancer
  hosts: localhost
  roles:
  - azure_preview_modules
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: lbtestfromansiblevn
        address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: lbtestfromansiblesb
        address_prefix: "10.10.0.0/24"
        virtual_network: lbtestfromansiblevn
    register: subnet

  - name: create internal loadbalancer
    azure_rm_loadbalancer:
      resource_group: '{{ resource_group }}'
      name: lbtestfromansible
      frontend_ip_configurations:
        - name: frontendipconf0
          private_ip_address: 10.10.0.10
          private_ip_allocation_method: Static
          subnet: "{{ subnet.state.id }}"
      backend_address_pools:
        - name: backendaddrpool0
      probes:
        - name: prob0
          port: 80
      inbound_nat_pools:
        - name: inboundnatpool0
          frontend_ip_configuration_name: frontendipconf0
          protocol: Tcp
          frontend_port_range_start: 80
          frontend_port_range_end: 81
          backend_port: 8080
      load_balancing_rules:
        - name: lbrbalancingrule0
          frontend_ip_configuration: frontendipconf0
          backend_address_pool: backendaddrpool0
          frontend_port: 80
          backend_port: 80
          probe: prob0
```

**Comment by zwindler** [comment]
Great, I'll take a look at it this morning

**Comment by zwindler** [comment]
I was not able to get your version with ansible-galaxy, so I downloaded the source code from your PR, pulled latest source from github and built ansible to the latest version.

As far as I can tell it works, in the following usecases :
- Your example => works
- Your example but with Dynamic ip allocation instead of Static => works
- My own usecase => works, but I had to add the line "register: subnet" beforehand (like you do in your example)

If I may, this is a little bit convenient (but not blocking) in the case that you add the loadbalancer but the subnet is already existing (from another playbook for ex.). The fact that there is no easy way I know of to get it is not helping (no *azure_rm_subnet_facts* to query the id beforehand).

Still, you can get around this by adding the task to create the subnet even if it's already there, just to get the id so I guess it's enough for now. I'm my own precise case, it's working.

Many thanks for this!

**Comment by yuwzho** [comment]
@zwindler So there comes another feature: add `azure_rm_subnet_facts` module 😄

**Comment by zikalino** [comment]
@zwindler just one question. You mentioned that "I was not able to get your version with ansible-galaxy", could you share some more details what went wrong? that would help to improve our role...

**Comment by zwindler** [comment]
@yuwzho Yeah... sorry about that ;-). But like I said I don't *need* it, the workaround is enough for me.

@zikalino I installed it using the command line provided and when I checked, it was supposed to be installed. But when running ansible-playbook, it didn't used the patched version. It very well may be an error from my part, but as far as I can tell, ansible-playbook was using the 2.4.3 version of the module.

**Comment by yuwzho** [comment]
@zwindler I think I give a not-complete instruction. I also tried on some machine, may meet the same error, If the playbook add a `role`, it should work properly. I have updated the sample given above. Thanks for your feedback, we can give a more complete instruction in later 😄

**Comment by xscript** [comment]
shipit

**Comment by yuwzho** [comment]
bot_status

**Comment by yuwzho** [comment]
@mkrizek Do you know why this was not automerged by bot ?

**Comment by mkrizek** [comment]
@yuwzho yes, the PR adds integration tests which should be looked at by a human to check if the PR isn't disabling tests or something, so that prevents automerge

**Comment by yuwzho** [comment]
ping @jborean93

**Comment by mkrizek** [comment]
bot_status

**Comment by yuwzho** [comment]
Try this PR's change by installing ansible role via git
```
ansible-galaxy install git+https://github.com/Azure/azure_preview_modules.git,internal-loadbalancer
```

And add the role definition in playbook:

```yaml
---
- name: XXXXXXXXXXX
  hosts: localhost
  connection: local
  roles:
  - azure_preview_modules
  tasks:
```

**Comment by zwindler** [comment]
Hi,

I tried the PR using *azure_preview_modules* & *ansible-galaxy* (I managed to make it work this time). I'm not sure if this is a problem or not => Because sku argument is not marked as mandatory, it can lead to this error if you "forget" it

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: __init__() got an unexpected keyword argument 'sku'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_QU9dal/ansible_module_azure_rm_loadbalancer.py\", line 966, in <module>\n    main()\n  File \"/tmp/ansible_QU9dal/ansible_module_azure_rm_loadbalancer.py\", line 963, in main\n    AzureRMLoadBalancer()\n  File \"/tmp/ansible_QU9dal/ansible_module_azure_rm_loadbalancer.py\", line 618, in __init__\n    supports_check_mode=True\n  File \"/tmp/ansible_QU9dal/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 345, in __init__\n  File \"/tmp/ansible_QU9dal/ansible_module_azure_rm_loadbalancer.py\", line 768, in exec_module\n    load_balancing_rules=load_balancing_rules_param\nTypeError: __init__() got an unexpected keyword argument 'sku'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

Aside from this, if I do set the sku, I get this error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'LoadBalancerSku'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_BdzMnW/ansible_module_azure_rm_loadbalancer.py\", line 966, in <module>\n    main()\n  File \"/tmp/ansible_BdzMnW/ansible_module_azure_rm_loadbalancer.py\", line 963, in main\n    AzureRMLoadBalancer()\n  File \"/tmp/ansible_BdzMnW/ansible_module_azure_rm_loadbalancer.py\", line 618, in __init__\n    supports_check_mode=True\n  File \"/tmp/ansible_BdzMnW/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 345, in __init__\n  File \"/tmp/ansible_BdzMnW/ansible_module_azure_rm_loadbalancer.py\", line 762, in exec_module\n    sku=self.network_models.LoadBalancerSku(self.sku) if self.sku else None,\nAttributeError: 'module' object has no attribute 'LoadBalancerSku'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

My ansible playbook

```
[...]
  - name: "Create internal-lb Internal. Subnet previously registered"
    azure_rm_loadbalancer:
      name: "internal-lb"
      resource_group: "{{resourcegroup_name}}"
      sku: Basic
      frontend_ip_configurations:
        - name: "internal-lb"
          private_ip_allocation_method: Dynamic
          subnet: "{{ subnet.state.id }}"
      backend_address_pools:
        - name: "lb-internal"
      load_balancing_rules:
        - name: "https"
          frontend_ip_configuration: "internal-lb"
          probe: "HealthProbe-https"
          frontend_port: 443
          backend_address_pool: "lb-internal"
          backend_port: 443
      probes:
        - name: "HealthProbe-https"
          port: 443
[...]
```

**Comment by yuwzho** [comment]
@zwindler Yes, just updated the ansible galaxy role, you can try to re-install it now by appending `--force` tag. It should be OK.

**Comment by zwindler** [comment]
You're right, it works

Thanks again

**Comment by yuwzho** [comment]
ready_for_review

**Comment by kyliel** [comment]
@nitzmahone , Hi Matt, could you please help review this PR? This is to support a new SKU of LB.

**Comment by nitzmahone** [comment]
rebuild_merge

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
