### PR TITLE
Rename classic elb modules to match new names applied to application …

### PR DESCRIPTION
**Pull request by wimnat**
…LB modules

##### SUMMARY
While creating the new elb_application_lb module we decided on a new naming convention for the LB modules.

This PR updates the names of the older modules.  Hoping to make 2.4 so they go out with the new application LB module

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ec2_elb, ec2_elb_lb, ec2_elb_facts

##### ANSIBLE VERSION

```
2.4
```

### CODE REVIEW

**Comment by mattclay** [comment]
When renaming modules, the `_` prefixed aliases for the deprecated names should be symlinks to the newly renamed modules.

**Comment by wimnat** [comment]
@mattclay i can do this but it doesn't seem to apply to current AWS deprecated modules :/

**Review by s-hertel — APPROVED** [review]

**Comment by mattclay** [comment]
@wimnat Which renamed modules have been copied instead of linked?

**Comment by wimnat** [comment]
@mattclay ah nevermind they modules are fully deprecated not a rename as is the case here.

**Comment by s-hertel** [comment]
shipit

**Comment by wimnat** [comment]
@ryansb - i think this is a case of bot broken because it's a rename so i'm hoping the multi-module rule doesn't apply here.

**Comment by mattclay** [comment]
Removing the broken label so the bot can continue to process this PR.

**Comment by s-hertel** [comment]
bot_status

**Comment by s-hertel** [comment]
@mattclay Is it right to have both the old linked module names and the new module names in the pep8 legacy files? Or should it be one or the other?

**Comment by mattclay** [comment]
@s-hertel Both files need to be listed currently, since ansible-test isn't yet symlink aware.

**Comment by wimnat** [comment]
@s-hertel @willthames 

I've decided this might be a bad idea.

I was looking at boto3 conversion for these modules and I can see improvements we can make as far as returned parameters and module options are concerned.  Would it be better to just create new boto3 versions with the new names and then just deprecate the old modules rather than trying to maintain backwards compatibility?

**Comment by s-hertel** [comment]
@ryansb What should we do with this?

**Pull request merged**
