### PR TITLE
Added additional filter options for instances for EC2 and Eucalyptus

### PR DESCRIPTION
**Pull request by hspencer77**
Added the following filter options:

```
       'ami_launch_index': inst.ami_launch_index,
       'private_ip': inst.private_ip_address,
       'private_dns_name': inst.private_dns_name,
       'dns_name': inst.dns_name,
       'state_code': inst.state_code,
       'architecture': inst.architecture,
       'image_id': inst.image_id,
       'key_name': inst.key_name,
       'virtualization_type': inst.virtualization_type,
       'placement': inst.placement,
       'kernel': inst.kernel,
       'ramdisk': inst.ramdisk,
       'launch_time': inst.launch_time,
       'instance_type': inst.instance_type,
       'root_device_type': inst.root_device_type,
       'root_device_name': inst.root_device_name,
       'state': inst.state,
       'hypervisor': inst.hypervisor
```

Allows more flexibility when dealing with the ec2 module in plays.

### CODE REVIEW

**Comment by lwade** [comment]
Makes sense, good to have it all accessible.

**Comment by mpdehaan** [comment]
This looks like additional info about the ec2 guests returned, can you share why you said 'filter options?'.  Maybe I am missing something but would like to understand.

**Comment by hspencer77** [comment]
Ah, I said filter options because AWS documents these as filters.  I added these initial ones.  I plan to add some more when doing testing with EBS-backed instances later on (i.e. block device mapping stuff).  Below is a list of the supported filters:

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-DescribeInstances.html

Hope it makes sense.  Let me know if there are any questions.

**Comment by lwade** [comment]
Response elements: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-RunInstances.html

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
