### PR TITLE
Fix cherry_picker.toml

### PR DESCRIPTION
**Pull request by szb512**
Fixes cherrypicker.

- Feature Pull Request

cherrypicker

This fixes cherrypicker so there will be no problems with setup.

No command output yet, will upload soon.

### CODE REVIEW

**Comment by szb512** [comment]
Currently not possible.

**Comment by szb512** [comment]
I think it worked.

**Comment by szb512** [comment]
That is not possible.

**Comment by mkrizek** [comment]
@szb512 What are you trying to solve? There is a note with a link on how to install cherry-picker in the documentation - https://docs.ansible.com/ansible/latest/community/development_process.html.

**Comment by szb512** [comment]
Cherry-picker

**Comment by webknjaz** [comment]
@szb512 the cherry-picker is already set up correctly. Is there anything that is not working on your side?

**Comment by szb512** [comment]
Yep.

**Comment by sivel** [comment]
It would be beneficial if you actually explained what you are doing and exactly what is happening so that we can better understand the issue, and potentially assist in resolving the problem.

So far, we are unsure exactly what it is you are attempting to do.

**Comment by szb512** [comment]
I'm trying to fix cherry-picker.

**Comment by sivel** [comment]
> I'm trying to fix cherry-picker.

Please provide more information about what you are trying to fix.  Not just that you are trying to fix cherry-picker.  What about it specifically are you trying to fix.

If you cannot communicate this with us, we will be forced to close this PR.

**Comment by sivel** [comment]
Please feel free to stop by the #ansible-devel IRC channel for more assistance.

**Pull request closed without merging**
