### PR TITLE
change the default value of user to null

### PR DESCRIPTION
**Pull request by chanwit**
##### SUMMARY
Change the default value of user from root to null to conform the current Docker behavior and the current Ansible documentation.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker

### CODE REVIEW

**Comment by felixfontein** [comment]
@hannseman what do you think? Should this have been in #51110?

**Comment by hannseman** [comment]
@felixfontein yes this should have been in #51110. 

This is when reading the current state from docker so if no user have been defined the `user is not None` check in `compare()` will cause this default to be ignored. This is why it wasn't caught by any tests.

I can't really see any bugs that could be caused by this default but it sure is unnecessary to have it. 

@chanwit what caused you to notice this default?

**Comment by felixfontein** [comment]
@hannseman The only difference I can think of when removing this is that if the user specifies `user: root` explicitly, and it hasn't been defined previously (i.e. the image's user was used), then with this change the service will be restarted. In case the image's user was `root`, this is probably unnecessary, but in case it is not, this is important. If that was correct, I'm for merging this. :)

**Comment by hannseman** [comment]
@felixfontein good point, I think you are right about that behaviour.

**Comment by felixfontein** [comment]
Ok, then let's get this merged!

shipit

**Comment by felixfontein** [comment]
@chanwit thank you very much for the PR! It looks like we missed this in #51110. The default value `root` will be completely gone in Ansible 2.8, to be released this May. For the current 2.7 versions, you can use `user: null` to disable the default.
@hannseman thanks for checking!

**Pull request merged**
