### PR TITLE
Add required_if to AnsibleModule

### PR DESCRIPTION
**Pull request by emonty**
There is a common pattern in modules where some parameters are required
only if another parameter is present AND set to a particular value. For
instance, if a cloud server state is "present" it's important to
indicate the image to be used, but if it's "absent", the image that was
used to launch it is not necessary. Provide a check that takes as an
input a list of 3-element tuples containing parameter to depend on, the
value it should be set to, and a list of parameters which are required
if the required parameter is set to the required value.

### CODE REVIEW

**Comment by omgjlk** [comment]
I've wanted something like this before as well, :+1:

**Comment by abadger** [comment]
Talked about this with @j2sol on the live meeting today.  Looks good.  I'll merge and make sure it applies to the v2_final branch as well.

**Comment by bcoca** [comment]
+1

**Comment by abadger** [comment]
Applied cleanly to v2_final as well.  Thanks!  Now we just need to have someone clean up all the modules where this logic is written out manually ;-)

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
