### PR TITLE
doc: guide how to use vultr

### PR DESCRIPTION
**Pull request by resmo**
##### SUMMARY
vutlr docs 

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

vultr

##### ANSIBLE VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jborean93** [comment]
cc @dharmabumstead

**Review by dharmabumstead — CHANGES_REQUESTED** [review]
Is there more to this?

**Comment by resmo** [comment]
@dharmabumstead there is nothing more planed currently. Only how to setup the credentials to get started.

**Comment by dharmabumstead** [comment]
Needs rebase. Feel free to rebase and reopen. Thanks.

**Pull request closed without merging**
