### PR TITLE
Modified the get_url module to respect the content-disposition header if...

### PR DESCRIPTION
**Pull request by Tinche**
... the destination is a directory and the server provides it.

See http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html, section 19.5.1.

### CODE REVIEW

**Comment by mpdehaan** [comment]
in queue for testing, thanks!

**Comment by Tinche** [comment]
Here's a test you can use:

Without the patch:

<pre>ansible all -m get_url -a "url=http://repository.sonatype.org/service/local/artifact/maven/content?r=central-proxy&g=log4j&a=log4j&v=LATEST dest=~/" -i localhost, -c local
"dest": "/home/tin/content",
</pre>

With the patch:

<pre>ansible all -m get_url -a "url=http://repository.sonatype.org/service/local/artifact/maven/content?r=central-proxy&g=log4j&a=log4j&v=LATEST dest=~/" -i localhost, -c local
"dest": "/home/tin/log4j-1.2.17.jar",
</pre>

On the other hand, redirects are still a pain. Both patched and unpatched:

<pre>
ansible all -m get_url -a "url=http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=log4j&a=log4j&v=LATEST dest=~/" -i localhost, -c local
"dest": "/home/tin/redirect", 
</pre>

So I suggest not merging this quite yet, and I'll take a look at the redirect thing. The request itself can modify the URL (via redirect), so the new URL should bubble up to the filename generation logic.

**Comment by Tinche** [comment]
With the latest commit:

<pre>
ansible all -m get_url -a "url=http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=log4j&a=log4j&v=LATEST dest=~/" -i localhost, -c local
"dest": "/home/tin/log4j-1.2.17.jar",
</pre>

**Comment by jctanner** [comment]
@Tinche thank you!

**Comment by Tinche** [comment]
My pleasure, thanks for merging.

**Pull request merged**
