### PR TITLE
Add name_tag option to set name tag on created disk.

### PR DESCRIPTION
**Pull request by berenddeboer**
Add option to give a name to created ec2 volumes, with a lot of volumes they easily get lost otherwise.

Probably this approach needs to be revisited when generic tagging is going to be supported, but this is at least a step forward.

PS: new pull request to make sure it is a clean request.

### CODE REVIEW

**Comment by mpdehaan** [comment]
It feels like we should be able to generically just specify a list of tags like the ec2 module.

it is currently true that in the ec2 module the name tag must be JSON, but I want to see it updated so that if not JSON and actually a complex argument in Ansible we can work with that too, but also simple key=value pairs.  This code should be cleaned up and standardized first, then we need to make this module do the same.

I would hope that it could set multiple tags like the other rather than just setting one tag.

This will also be needing a rebase but per the above we are not ready to merge now.

cc @lwade

**Comment by lwade** [comment]
o.O looks like this has gone a little squiffy. 

Regarding tags, we need an ec2_tag module which we can use to set tags on any resource, then we should back out tag functionality from modules, imo.  Since most things can be tagged in AWS I think this makes most sense.

**Comment by berenddeboer** [comment]
I know we need an ec2_tag module. But now we have nothing, so I reckoned something was better than nothing.

**Comment by jimi-c** [comment]
Merged in the ec2_tag module today, so I'm going to go ahead and close this.

**Pull request closed without merging**
