### PR TITLE
Made ec2_snapshot more useful

### PR DESCRIPTION
**Pull request by hkariti**
- Added wait + wait_timeout options to wait until the snapshot is complete
- Added tagging on creation
- Return more data: original volume's id and size and the snapshot's tags

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged, thank you!

**Comment by Osterjour** [comment]
Do I understand correctly: There is an undocumented wait-param now, which changes the (usual) behavior of the API command from AWS and waits until the snapshot is complete?
I understand that some people wanted to get sure the snapshot is completed (which isn't necessary by the way), but please don't change the known behavior and set wait to false on default.

**Comment by Osterjour** [comment]
This fixes the change of the behavior to the way it SHOULD be (and was till this change): https://github.com/ansible/ansible/pull/7438

**Comment by mariow** [comment]
Second this, the default should be not to wait for the completion of the snapshot as this may take a very long time to complete and as long as the process has been started I can be sufficiently sure that  the snapshot will eventually be created.

**Comment by hkariti** [comment]
Yeah, my bad. Sorry about that.

**Pull request closed without merging**
