### PR TITLE
swdepot: Refactor code

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This PR includes:
- Add RETURN documentation
- Fixes to the documentation and examples
- Simplified logic
- Set default state to 'present'
- Add parameter dependencies
- Use a result dictionary
- Fix check-mode support
- Added integration tests

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
swdepot

### CODE REVIEW

**Comment by dagwieers** [comment]
@davx8342 Would it be possible to test swdepot from this branch, and I can help you create integration tests so we can test idempotency, check-mode and return values at every possible use.

**Review by samccann — APPROVED** [review]
Docs portion LGTM

**Comment by acozine** [comment]
Related to #47869.

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Pull request closed without merging**
