### PR TITLE
docs(modules.elb_application_lb): add an example with source-ip rule

### PR DESCRIPTION
**Pull request by countless-integers**
##### SUMMARY
Adding ALB rules based on source IP of the request was not documented, but it is supported. Structure is a bit different, so knowing [about it](https://github.com/ansible/ansible/blob/ef7d060a3f45814fe7d73927cf29fa05b629407d/lib/ansible/module_utils/aws/elbv2.py#L718) would have saved me some time.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
Module: elb_application_lb

##### ADDITIONAL INFORMATION
n/a

### CODE REVIEW

**Review by jillr — COMMENTED** [review]
Thanks @countless-integers, this change lgtm but the merge conflict will need to be resolved.

**Comment by countless-integers** [comment]
> Thanks @countless-integers, this change lgtm but the merge conflict will need to be resolved.

Ok, I've resolved it by keeping both conflicting examples (as they show 2 different things) and changing `Priority` field.

**Comment by jillr** [comment]
Hi @countless-integers. You don't need to change your example, but to rebase your branch onto devel and resolve the resulting git conflict, and then push the updated branch.  The bot has a link to the Ansible docs about rebasing, [this guide](https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts) about resolving merge conflicts may also be helpful.

**Comment by countless-integers** [comment]
Nvm, messed up the rebase.

**Pull request closed without merging**
