### PR TITLE
Fixed "dictionary changed size during iteration" for zabbix_template …

### LINKED ISSUE #57942: zabbix_template: RuntimeError: dictionary changed size during iteration
##### SUMMARY

When using module: zabbix_template I get RuntimeError: dictionary changed size during iteration

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_template
##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = ansible.cfg
  configured module search path = ['/home/nerijus/ansible/library', '/home/nerijus/ansible/library']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/home/nerijus/ansible/ansible.cfg) = memory
DEFAULT_FORKS(/home/nerijus/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/home/nerijus/ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/home/nerijus/ansible/ansible.cfg) = ['/home/nerijus/ansible/hosts']
DEFAULT_MANAGED_STR(/home/nerijus/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/home/nerijus/ansible/ansible.cfg) = ['/home/nerijus/ansible/library', '/home/nerijus/ansible/library']
DEFAULT_POLL_INTERVAL(/home/nerijus/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_USER(/home/nerijus/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/nerijus/ansible/ansible.cfg) = ['/home/nerijus/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/nerijus/ansible/ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/nerijus/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/home/nerijus/ansible/ansible.cfg) = smart
DISPLAY_SKIPPED_HOSTS(/home/nerijus/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/nerijus/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Fedora 30

##### STEPS TO REPRODUCE

```yaml
 name: Import Zabbix json template configuration for certificate checks
  local_action:
    module: zabbix_template
    server_url: https://zabbix.example.com
    login_user: ansible
    login_password: password
    template_name: "Vhost {{ item.vhost }} certificate checker"
    template_groups: "Vhosts-templates"
    template_json: "{{ lookup('template', 'template.json.j2') }}"
    state: present
  with_items: "{{ nginx_proxy_vhosts }}"

```

##### ACTUAL RESULTS

```paste below
failed: [example.com -> localhost]
...
MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

/home/nerijus/.ansible/tmp/ansible-tmp-1560763543.771961-70643434851177/AnsiballZ_zabbix_template.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/nerijus/.ansible/tmp/ansible-tmp-1560763543.771961-70643434851177/AnsiballZ_zabbix_template.py", line 114, in <module>
    _ansiballz_main()
  File "/home/nerijus/.ansible/tmp/ansible-tmp-1560763543.771961-70643434851177/AnsiballZ_zabbix_template.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/nerijus/.ansible/tmp/ansible-tmp-1560763543.771961-70643434851177/AnsiballZ_zabbix_template.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.7/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_zabbix_template_payload_wk7wm7ro/__main__.py", line 582, in <module>
  File "/tmp/ansible_zabbix_template_payload_wk7wm7ro/__main__.py", line 575, in main
  File "/tmp/ansible_zabbix_template_payload_wk7wm7ro/__main__.py", line 286, in update_template
  File "/tmp/ansible_zabbix_template_payload_wk7wm7ro/__main__.py", line 334, in diff_template
  File "/tmp/ansible_zabbix_template_payload_wk7wm7ro/__main__.py", line 354, in filter_template
RuntimeError: dictionary changed size during iteration

```

### PR DESCRIPTION
**Pull request by D3DeFi**
…when used with newest Python3

##### SUMMARY
Fixes #57942 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
zabbix_template

##### ADDITIONAL INFORMATION
Affects all Zabbix server versions. Playbook template.yml:

```yaml
- hosts: all
  vars:
    mytemplates:
      - mytemp_name: FirstTemplateTest
        mytemp_desc: This is first template
      - mytemp_name: SecondTemplateTest
        mytemp_desc: This is second template

  tasks:
    - name: Create template in Zabbix
      zabbix_template:
        server_url: "{{ zbx_server_url }}"
        login_user: "{{ zbx_user }}"
        login_password: "{{ zbx_password }}"
        validate_certs: "{{ zbx_validate_certs }}"
        template_name: "{{ item.mytemp_name }}"
        template_groups:
          - Templates
        template_json: "{{ lookup('template', 'template.j2') }}"
      loop: "{{ mytemplates }}"
      delegate_to: localhost
```
Jinja2 template.j2:
```json
{
  "zabbix_export" : {
     "templates" : [
        {
           "groups" : [
              {
                 "name" : "Templates"
              }
           ],
           "applications" : [],
           "description" : "{{ item.mytemp_desc }}",
           "name" : "{{ item.mytemp_name }}",
           "items" : [],
           "macros" : [],
           "template" : "{{ item.mytemp_name }}",
           "discovery_rules" : [],
           "screens" : []
        }
     ],
     "version" : "3.0",
     "groups" : [
        {
           "name" : "Templates"
        }
     ]
  }
}
```

### CODE REVIEW

**Comment by D3DeFi** [comment]
tested against Zabbix server 3.0, 4.0 and 4.2 with both python2/3 and ansible version 2.8.1 and 2.9.0.dev0
-label needs_triage
shipit

**Comment by nerijus** [comment]
Works ok with zabbix 4.2 and ansible 2.8.1.

**Comment by rubentsirunyan** [comment]
shipit

**Comment by D3DeFi** [comment]
bot_status

**Pull request merged**
