### PR TITLE
[2.7] docker_image: clarify dockerfile docs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of #57570 to stable-2.7.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docker_image

### CODE REVIEW

**Comment by acozine** [comment]
Known CI issue with paramiko release.

**Comment by felixfontein** [comment]
Tests should succeed once #57648 is merged.

**Comment by acozine** [comment]
Tests have passed, I'm going to merge.

**Comment by felixfontein** [comment]
Thanks for handling this @acozine!

**Pull request merged**
