### PR TITLE
[cloud] ec2_asg: wait for the lifecycle hooks - Fixes #37281 (#37282)

### LINKED ISSUE #37281: ASG rolling update ignores lifecycle hooks
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_asg

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When replacing instances, ASG lifecycle hooks are ignored.
The consequence is that it moves on to the next replacement before the hooks are completed.
It's more evident when the lifecycle hooks take a significant time to complete.

##### STEPS TO REPRODUCE
1. Create an ASG with a lifecycle hooks that take few minutes to complete
2. Update the launch configuration
3. Run a rolling deployment
```yaml
- name: Update launch configuration
  ec2_asg:
    name: test_asg
    launch_config_name: new_test_asg_lc
    desired_capacity: 10
    min_size: 3
    max_size: 20
    wait_for_instances: yes
    replace_all_instances: yes
    replace_batch_size: 2
```

##### EXPECTED RESULTS
There are no more than 2 instances at any time in any of these states:
- Terminating
- Terminating:Wait
- Terminating:Proceed

##### ACTUAL RESULTS
As soon as the instances are in Terminating:Wait module move on to the next batch.
More than 2 instances are in Terminating:Wait or Terminating:Proceed state.

### PR DESCRIPTION
**Pull request by aarnone**
##### SUMMARY
Backport of #37282

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ec2_asg

##### ANSIBLE VERSION
```
2.5
```

##### ADDITIONAL INFORMATION

```
```

### CODE REVIEW

**Comment by jborean93** [comment]
@aarnone are you able to create a changelog fragment in the PR. An example of a fragment can be found here https://github.com/ansible/ansible/blob/stable-2.5/changelogs/fragments/30786-verbose_info_on_os_stack_error.yaml. Basically create a file in that directory with a name that relates to the fix; the contents should be something like

```
bugfixes:
- ec2_asg - fix the wait for lifecycle hooks to complete (https://github.com/ansible/ansible/issues/37281)
```

You can put whatever you want as the entry, this was just an example.

**Comment by aarnone** [comment]
@jborean93 here it is!

**Comment by jborean93** [comment]
Thanks @aarnone, CI failures are unrelated.

**Comment by aarnone** [comment]
It looks like I've created the changelog fragment in the wrong place.
Is it worth reopening to correct that?

**Comment by ryansb** [comment]
Ah, I see the issue. I'll move it manually, no need to reopen.

**Comment by ryansb** [comment]
Fixed in d0cf81883c

**Comment by aarnone** [comment]
Great! Thanks @ryansb

**Pull request merged**
