### PR TITLE
Make template action respect local_tmp. Fixes #34941 (#35005)

### LINKED ISSUE #34941: /tmp directory being used
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

template and potentially more

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.1.0
  config file = /opt/****/ansible.cfg
  configured module search path = [ '/home/****/ansible']
```

##### CONFIGURATION

```
$ cat ansible.cfg | grep tmp
local_tmp = /opt/***/.ansible/tmp
remote_tmp = /opt/***/.ansible/tmp
$

```
##### OS / ENVIRONMENT

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

```
##### SUMMARY

Files are writing to /tmp when remote_tmp and local_tmp is defined

##### STEPS TO REPRODUCE

```yaml

    - name: "{{ site }} - GENERATE JSON REPORT PER SITE STATS ONLY"
      template:
        src: "{{ role_path }}/templates/reports/sites/partial_table.j2"
        dest: '{{ output_dir }}/reports/html/partial/{{ site }}.partial'
```

##### EXPECTED RESULTS

```
localhost                  : ok=360  changed=29   unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
TASK [reports : *** - GENERATE JSON REPORT PER SITE STATS ONLY] ****************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "[Errno 13] Permission denied: '/tmp/tmpuv61yn'"}

PLAY RECAP *********************************************************************
localhost                  : ok=360  changed=29   unreachable=0    failed=1
```

### PR DESCRIPTION
**Pull request by TristanCacqueray**
##### SUMMARY
Backport devel fix

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
templates

##### ANSIBLE VERSION
ansible 2.4.3.0

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @abadger

**Comment by abadger** [comment]
This is more s feature of 2.5 than a bug (local_tmp) was really only used
for the ansiballz cache in 2.4 and prior.  So I'm inclined not to backport
this.

**Comment by TristanCacqueray** [comment]
It can also be considered a bug/regression fix because the 2.3 version of the template module wasn't using a temporary file.

**Comment by abadger** [comment]
2.3 had similar behaviour.  The only difference is that 2.3 created a temporary file and ~2.3~  (EDIT: 2.4) creates a temporary directory into which it places the temporary file.  This is not a regression.  I'm not sure whether it is a bugfix; we didn't have any overarching policy to put local temporary files into local_tmp until 2.5.

**Comment by mattclay** [comment]
Ansible 2.4 is [end-of-life and is no longer supported](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#release-status).

Backports or other changes to EOL branches are not accepted.

**Pull request closed without merging**
