### PR TITLE
ansible-pull: Add --module-args to expose all SCM module args and deprecate old argument specific CLI options. (#48678)

### PR DESCRIPTION
**Pull request by ju2wheels**
- Second PR to complete #48678

##### SUMMARY

This change adds a generic --module-args parameter that allows ansible-pull to pass parameters to the underlying SCM module used to checkout the repo without requiring the addition of CLI flags specific to options of each SCM module.

All existing CLI options that correspond to a specific SCM module parameter are deprecated and a warning has been added when behavior is being overridden to preserve backwards compatibility.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ansible-pull
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by bcoca — APPROVED** [review]

**Comment by maxamillion** [comment]
rekicking CI, I don't think the failure was related.

**Comment by ju2wheels** [comment]
@agaffney Deprecation warnings dropped as suggested. I left in the other warnings that let the user know when the existing deprecated args override the new one for backwards compatibility if both are used.

If thats not recommended either then I will also drop those.

**Comment by agaffney** [comment]
I don't think that you meant to CC me. I don't know anything about this PR.

**Comment by ju2wheels** [comment]
@agaffney I think it was you from Friday's IRC discussion back and forth but if not my mistake.

**Comment by maxamillion** [comment]
The change looks good, but needs tests.

**Comment by ju2wheels** [comment]
@maxamillion Ill work on adding some to the integration shell script when I get a chance this week. Unless im told otherwise, since I dont know what repos to use for recursive cloning tests, im going to use same test repos used in #49000 for the `git` recursive submodule change tests.

**Comment by ju2wheels** [comment]
@bcoca please review the small change above to `--full` backward compatibility condition change. Because `depth` is not an on/off setting like `export`, we need a way to allow no `depth` being set to mean `--full`. So whenever `--module-args` s used in any capacity we do not set `depth=1` as a fallback for backward compatibility if `depth` is not set. If `--module-args` is not used, then the `depth=1` backward compatibility is used.

**Comment by ju2wheels** [comment]
@maxamillion basic integration tests added with a remote repo and a fake role repo using one of the repos already used for `git` testing as described above.

I'll rerun the tests again later, they seem to be failing on other tests.

**Comment by maxamillion** [comment]
rerunning CI, it looks like shippable had a dns issue.

**Comment by ju2wheels** [comment]
I think Ive taken it as far as I can at this point. Ill rebase it again tomorrow and retry but I have no idea whats causing the proxy issue on the /3 set of tests. Does `ANSIBLE_CONFIG` need to be explicitly disabled for all runs like was done on the original tests?

**Comment by bcoca** [comment]
one thing we could add is a `display.deprecated` when any of the deprecated options are used, it is well documented, but most people won't accept it unless there is a runtime warning.

**Comment by mattclay** [comment]
@ju2wheels The test failure is due to the wrong Python interpreter being used during the tests. I suspect the lack of `ansible_python_interpreter={{ ansible_playbook_python }}` in the https://github.com/ju2wheels/test_ansible_pull inventory is responsible.

**Comment by ju2wheels** [comment]
@mattclay all these tests were passing as of last week, so something introduced into devel broke it. All I did was rebase on devel to address the stale_ci, but I will take another look tomorrow.

**Comment by mattclay** [comment]
@ju2wheels Test infrastructure was recently updated to no longer override ansible_python_interpreter. This means that tests can no longer use the wrong interpreter and rely on the override to correct it.

**Comment by ju2wheels** [comment]
@mattclay Are there examples of how to override it by platform only for the integration tests? I have no idea what the default python interpreter on your tests systems are or which are available and in which location.

**Comment by mattclay** [comment]
@ju2wheels Use `ansible_python_interpreter={{ ansible_playbook_python }}`

**Comment by mattclay** [comment]
@ju2wheels Using `ansible_connection=local ansible_python_interpreter={{ ansible_playbook_python }}` for the inventory entry for `localhost` makes it behave like [implicit localhost]( https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html).

**Comment by webknjaz** [comment]
@ju2wheels this needs a conflict resolution

**Comment by ju2wheels** [comment]
@webknjaz Addressed, will review CI tomorrow to make sure its all still passing.

**Comment by webknjaz** [comment]
Hi, I'd like to merge #49000 first.

**Comment by bcoca** [comment]
@ju2wheels can you rebase?

**Comment by nitzmahone** [comment]
Closing for inactivity...

**Pull request closed without merging**
