### PR TITLE
Replaces a open/close to validate access with os.access in azure stor…

### PR DESCRIPTION
**Pull request by atombrella**
…ageblob.

##### SUMMARY
Probably changes semantics according to some minds. I saw `os.access` used in other places in Ansible.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure, cloud.

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by atombrella** [comment]
@felixfontein @Fred-sun I added a changelog fragment, as that was requested in other PRs. It'd be nice if the feedback cycle was somewhat faster for trivial things.

**Comment by Fred-sun** [comment]
@atombrella Yes, because things have been more neglected recently. I will ping community maintenance personnel review and merge. Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang @gavinfish Would you please help review and merge this PR? Thank you very much!

**Comment by Fred-sun** [comment]
Changes are minor, ping to review and merge.

**Review by gavinfish — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
rebuild_merge

**Comment by felixfontein** [comment]
@atombrella thanks for fixing this!
@Fred-sun @gavinfish thanks for reviewing this!

**Pull request merged**
