### PR TITLE
backport of 65679: postgresql_schema: use query_params with cursor object

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
backport of #65679

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
```lib/ansible/modules/database/postgresql/postgresql_schema.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by tcraxs** [comment]
LGTM

**Comment by Andersson007** [comment]
@tcraxs thanks for approving!

**Review by kostiantyn-nemchenko — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko thank you!

**Pull request merged**
