### PR TITLE
Add AWS EC2 elastic IP module

### PR DESCRIPTION
**Pull request by lorin**
Adds a new AWS EC2 module to associate/disassociate instances and elastic IP addresses.

### CODE REVIEW

**Comment by lwade** [comment]
Great, we had a user asking for this and I was just working on the same thing. @lorin ++

**Comment by lwade** [comment]
Minor typo here btw:

```
public_ip = dict(required=True, alises= ['ip'] ), 
```

**Comment by bennojoy** [comment]
+1

This is great, helpful for me too, can we extend it a bit and if the public
ip is not given, it allocates a public ip and assigns
to the instance ?

**Comment by lorin** [comment]
@lwade Good catch on the typo, fixed.

@bennojoy Sure, I can add functionality to auto-allocate a public ip if none is specified.

I'll have the module return the ip address. I'll also need to add a parameter to deal with the scenario where there's already a public ip allocated, since some users may want this behavior to idempotent, and some may want a new floating ip to be allocated and associated each time this module is called with no ip specified.

**Comment by innyso** [comment]
nice!!! Thanks for creating this module, this is definitely a module that i will use for my ec2 provisioning (especially with the auto-allocate functionality)

**Comment by devoncrouse** [comment]
Is this going to get pulled in? We're using it, and have a contribution of our own to enable allocation of VPC EIPs. Also, we'll occasionally run into an error: "The allocation ID 'eipalloc-...' does not exist" - maybe a race condition in boto?

**Comment by jimi-c** [comment]
Yes, we'll definitely be including this in the near future.

**Comment by lorin** [comment]
The comments today reminded me that there had been a previous request by @bennojoy to support allocating elastic IPs, not just associating them. 

That's now been added, you can allocate and associate elastic IPs in one go, or you can do them in separate stages.

**Pull request merged**
