### PR TITLE
[inventory_aws_conformance] use consistent sg order in script

### PR DESCRIPTION
**Pull request by s-hertel**
##### SUMMARY
https://github.com/ansible/ansible/pull/54365#discussion_r269296154

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
inventory_aws_ec2

### CODE REVIEW

**Review by jamescassell — APPROVED** [review]
shipit

**Review by felixfontein — APPROVED** [review]
`k, v in sorted(self._ignore_security_groups.items())` should also work, but this is fine, too.

**Comment by felixfontein** [comment]
shipit

**Comment by s-hertel** [comment]
Thanks, that's nicer.

**Review by felixfontein — APPROVED** [review]
shipit

**Review by jamescassell — APPROVED** [review]
shipit

**Comment by jamescassell** [comment]
bot_status

**Comment by s-hertel** [comment]
Thanks for the reviews

**Pull request merged**
