### PR TITLE
set ansible_os_family from name variable in os-release for clearlinux…

### PR DESCRIPTION
**Pull request by josuedhg**
… OS (#49639)

* set ansible_os_family from name variable in os-release for clearlinux system

Signed-off-by: Josue David Hernandez Gutierrez <josue.d.hernandez.gutierrez@intel.com>

* Add os_family for clear linux and clear linux mixes

Signed-off-by: Josue David Hernandez Gutierrez <josue.d.hernandez.gutierrez@intel.com>
(cherry picked from commit 9202ef60b02053e5b5e6224cc4b5fc9c4c8786b0)

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by josuedhg** [comment]
this is a backport of https://github.com/ansible/ansible/pull/49639, @maxamillion @gundalow

**Comment by maxamillion** [comment]
shipit

**Comment by josuedhg** [comment]
@maxamillion ready

**Comment by josuedhg** [comment]
@gundalow

**Comment by abadger** [comment]
This appears to need a changelog entry and then could be merged.

**Comment by josuedhg** [comment]
@abadger added

**Comment by abadger** [comment]
Merged for the 2.7.6 release

**Pull request merged**
