### PR TITLE
Distribution packaging should install all manpages

### LINKED ISSUE #1069: Distribution packaging does not install all manpages
Looks like the ansible-pull manpage was created after the packaging bits but it wasn't added into the deb and arch build processes. The packaging scripts should install all manpages by default. Note than the RPM package was already doing this.

### PR DESCRIPTION
**Pull request by elementalvoid**
closes #1069

### CODE REVIEW

**Comment by mpdehaan** [comment]
Ah, there it is.  Thx!

-- Michael

**Comment by elementalvoid** [comment]
Sorry about that. Wanted an issue I'd to put in the commit message.

**Comment by mpdehaan** [comment]
No problem!

-- Michael

**Comment by mpdehaan** [comment]
merged, thanks!

**Pull request merged**
