### PR TITLE
Allow the use of YAML data in addition to a YAML file as a playbook.

### PR DESCRIPTION
**Pull request by ed-at-work**
Allow the use of a YAML data structure in addition to a YAML file as a playbook. There's a comment in the code that indicates that this should be possible, but it doesn't actually seem to be from my quick reading of the code. This should bring the code in line with the comment.

### CODE REVIEW

**Comment by mpdehaan** [comment]
We are not really interested in this feature as it would not make it possible to use most of the features of Ansible, including roles.

**Comment by mpdehaan** [comment]
The workaround here would be to make a simple wrapper script that wrote a temporary playbook.

**Comment by ed-at-work** [comment]
Yes, I know.  In the tool I'm building I have two different ways of talking to Ansible, one by calling Playbook.run()  directly and one by shelling out to ansible-playbook. There is an aspect of shelling out that is kind of annoying in the way I'm doing it,  I will just need to make some changes to make it work.

Thanks.  Might want to update the comments in the code as to eliminate confusion-- right now it looks like there's a missing feature.

Curious about how this would affect roles?

**Comment by mpdehaan** [comment]
Will do!

**Pull request closed without merging**
