### PR TITLE
Adds support for route53 aliases, weighted routing policy and ...

### PR DESCRIPTION
**Pull request by jimbydamonk**
health checks. 

Most of the options follow boto:

http://boto.readthedocs.org/en/latest/ref/route53.html

Basic usage 
    - name: Test Add record with latency 
      local_action:
        module: route53
        command: create
        record: yes
        type: CNAME 
        zone: dev.example.com
        identifier: us-west-1
        region: us-west-1
        record: core.test.dev.example.com.
        value: core.us-west-1.dev.example.com

### CODE REVIEW

**Comment by ghost** [comment]
Yes please! Definitely need the alias_dns_name support.

**Comment by coop** [comment]
I'm having a hard time making this work when aliasing an ELB. Do you have any examples that would help with that?

**Comment by jimbydamonk** [comment]
@coop What issues did you have ? 
I normally don't have an alias to my elb. I normally just use a CNAME (but we don't use the elbs a lot)

**Comment by coop** [comment]
When I get into work I can drop you the code I'm using but the error I get
is around the `alias_zone`. I've been trying to mimic the settings I see in
the console: I set the record to `example.foo.com` the value to the public
DNS record of the elb (`blah.elb.us-east-1.AWS.com`) the zone to `foo.com`
the alias to the public DNS record of the elb and it errors out.

Any chance you could put together an example? And I'll shoot through mine
in about an hour.

**Comment by coop** [comment]
``` yaml
# ansible/roles/environment/tasks/route53.yml
- name: route53 | alias elb
  local_action:
    module: route53
    command: create
    record: yes
    ttl: 3600
    type: A
    zone: everydayskeleton.com
    alias: tango.payments.everydayskeleton.com
    alias_zone: everydayskeleton.com
    record: tango.payments.everydayskeleton.com
    value: payments-tango-blue-1881211979.us-east-1.elb.amazonaws.com
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
```

``` yaml
# ansible/roles/environment/tasks/main.yml
- include: route53.yml
```

``` yaml
# ansible/inventories/localhost
[local]
localhost
```

``` yaml
# ansible/modules/route53.yml
# The code from this pull request
```

``` sh
ansible-playbook ansible/environment.yml -i ansible/inventories/localhost --module-path ansible/modules
```

This gives me the following error:

``` sh
thunderdome(feature/ansible_all_the_things*)$ ansible-playbook ansible/environment.yml -i ansible/inventories/localhost --module-path ansible/modules

PLAY [localhost] **************************************************************

TASK: [environment | route53 | alias elb] *************************************
failed: [localhost] => {"failed": true, "item": ""}
msg: Tried to create an alias that targets tango.payments.everydayskeleton.com., type A in zone Z36JJ4RSV0CROF, but that target was not found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/troll/environment.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

I think it's trying to tell me that the zone of the record I'm trying to alias (the ELB) is not under my control which makes sense because I don't have `elb.amazonaws.com` setup in my route53 account like I do `everydayskeleton.com`. Manually wiring this up through the console works no problems - I'm guessing that I'm missing something.

**Comment by jimbydamonk** [comment]
Hey @coop, just got back from vacation. 
I will try and mimic your error and see if I can fix it.

**Comment by jimbydamonk** [comment]
Ahhh... The elb's DNS is not in the same hosted zone. alias_zone needs to be under your account and describe the target zone. (In your case alias_zone should be us-east-1.elb.amazonaws.com but that is not under your control. 

You could try using a CNAME instead:
- name: Create CNAME for load balancer
  local_action: 
    module: route53
    command: create
    overwrite: yes
    ttl: 3600
    type: CNAME 
    zone: 'everydayskeleton.com'
    record: 'tango.payments.everydayskeleton.com'
    value:  'payments-tango-blue-1881211979.us-east-1.elb.amazonaws.com'

**Comment by coop** [comment]
There were a few problems if you want to use an A record (which I _think_ is the supported option via the AWS console - I kept getting errors when using a CNAME and alias record).
- Alias records don't use the `value` property
- The ELB's hosted zone id isn't in the list returned from the server as zones you're allowed to modify (as you mentioned)

I modified the code in this module to **only** support the ELB alias functionality. I'd be happy to submit the diff for someone else to take a look at writing the proper implementation tomorrow at work.

**Comment by jimbydamonk** [comment]
@coop 

I would like to see your diff. 

I manly use CNAME because that is what AWS suggests. http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/using-domain-names-with-elb.html

**Comment by coop** [comment]
You can view the [gist](https://gist.github.com/coop/b867e47d4a4b266f6b1a) in it's entirety but the parts I had to modify:

https://gist.github.com/coop/b867e47d4a4b266f6b1a#file-gistfile1-py-L307-L309: alias records don't require passing the `value` attribute.

https://gist.github.com/coop/b867e47d4a4b266f6b1a#file-gistfile1-py-L329-L332: the ELB domain is owned by AWS and not in your list which raises an error.

https://gist.github.com/coop/b867e47d4a4b266f6b1a#file-gistfile1-py-L384: due to the previous issue I had to modify `zones[alias_hosted_zone_id]=alias_zone_in` to `alias_hosted_zone_id=alias_zone_in`.

I'm not sure why you'd use alias records over a CNAME. iirc it allowed AWS to do some magic but I honestly don't remember why we choose to use it.

**Comment by brokcloud** [comment]
ALIAS queries are free as opposed to a CNAME, because they are internal in route53 according to AWS docs.
Also, you can not make a CNAME for the apex of the domain e.g my.com > www.my.com whereas creating an A ALIAS is just fine.

If you would like some help with this please let me know, I need this myself and would like to get it into master.

**Comment by coop** [comment]
@brokcloud I won't have any time to implement this so feel free to make it work with master. The gist will get you most of the way.

**Comment by mpdehaan** [comment]
Hi all,

I'm going through pull requests now that we've got a lot of critical things out of the way and have come back to revisiting this one.

Can someone share consensus on whether we think this is good to go as is?

Also, looks like this may need a rebase in light of recent code changes.

Thanks!

**Comment by lalitkapoor** [comment]
+1 would really like this to go through

**Comment by linefeedse** [comment]
I have been revisiting this, resolving the merge conflict and incorporated @coop 's changes from the gist. Not a problem so far.
There is however a small snag remaining and that is the alias_hosted_zone_id that somehow needs to be extracted from the ELB you are aliasing. I have not found out how to do that with boto.
The alias_hosted_zone_id is needed here:
https://gist.github.com/coop/b867e47d4a4b266f6b1a#file-gistfile1-py-L384

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Comment by jayzeng** [comment]
@mpdehaan Any chance this can be reopened? It is a major road block without the alias feature for route53.

**Pull request closed without merging**
