### PR TITLE
ansible su root prompt

### PR DESCRIPTION
**Pull request by lvshaco**
case: 
ansible all -m shell -a "whoami" --become-method=su -b -K 

su root prompt, in chinese 密码： (to match the：)

### CODE REVIEW

**Comment by amenonsen** [comment]
This would be better written as `[:：]` rather than `(:|：)`.

**Comment by bcoca** [comment]
they all look like squares to me, not sure what i would be adding, also if the change should be there or in the definition of the SU_PROMPT_LOCALIZATIONS

**Comment by lvshaco** [comment]
@amenonsen [:：] match any byte in it， but：is multi byte ?
@bcoca yes, SU_PROMPT_LOCALIZATIONS is a better place, but it will change all in it，or it can be fix by change " ?: ?" to " ?:? ?"

**Comment by bcoca** [comment]
this branch seems to be full of unrelated commits to the initial patch

**Comment by lathama** [comment]
This pull request appears to be abandoned. Good to close.

**Comment by mattclay** [comment]
Submodules are no longer used in the ansible/ansible repository.

**Comment by mattclay** [comment]
@lvshaco If you're still having issues with su, please open a new issue or submit a new PR, now that the submodules have been merged into the ansible/ansible respository.

**Pull request closed without merging**
