### PR TITLE
unsubscribe cove from docker modules

### PR DESCRIPTION
**Pull request by cove**
##### SUMMARY
unsubscribe from docker notices

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
@cove thanks for the PR. This is being handled in https://github.com/ansible/ansible/pull/65446.

**Comment by Akasurde** [comment]
@cove you can use this PR to add yourself in `ignored` list for docker - https://github.com/ansible/ansible/blob/bcc2ffdbf904a885813ed2007411b0c93936e9f1/.github/BOTMETA.yml#L100

**Comment by Akasurde** [comment]
@felixfontein Could you please take a look? Thanks.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@cove thanks for your work on the docker modules!

**Pull request merged**
