### PR TITLE
move from with_<lookup>: to loop:

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
new loop keyword allows for much simpler loops
old functionality is still available direct lookup use, the following are equivalent
```yaml
  with_nested: [[1,2,3], ['a','b','c']]
```
same as 
```yaml
  loop: "{{lookup('nested', [1,2,3], ['a','b','c'])}}"
```
but nicer as 

```yaml
loop: "{{ [1,2,3]|zip(['a', 'b', 'c']) }}" 
```
Old `with_` loops still work but now have deprecation warning

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

loops
##### ANSIBLE VERSION

```
2.5
```

### CODE REVIEW

**Comment by mattclay** [comment]
Sanity tests hung on pylint test. I'll restart to see if it happens again.

**Comment by sivel** [comment]
Is there a proposal for this?

**Comment by bcoca** [comment]
@sivel, no, this was a wishlist item we've had for a long time, the change itself is actually very simple.

**Comment by sivel** [comment]
> @sivel, no, this was a wishlist item we've had for a long time, the change itself is actually very simple.

It is however a fundamental change.  I'm just confused on when a proposal should be created.  I feel like this is one of those times.  We're making a big decision, with no feedback.  Generally speaking, we make others do a proposal for these types of changes.

I get the feeling that largely things that the core team wants to do, often don't go into proposals, or when they do they are fast tracked without the level of involvement that any other proposal would get.

**Comment by ericcitaire** [comment]
I don't understand the purpose of this change.

### Old version
```yaml
- debug: msg="{{ item[0] }} - {{ item[1] }}"
  with_nested:
    - [1, 2, 3]
    - [a, b, c]
```
This is short, simple and readable.

### New version
```yaml
- debug: msg="{{ item[0] }} - {{ item[1] }}"
  loop: "{{ lookup('nested', [1, 2, 3], ['a', 'b', 'c']) }}"
```
This is **NOT** short, **NOT** simple and **NOT** readable!

### _Nicer_ version
```yaml
- debug: msg="{{ item[0] }} - {{ item[1] }}"
  loop: "{{ [1, 2, 3] | zip(['a', 'b', 'c']) | list }}"
```
This is not the same as `with_nested`! This is the same as `with_together`. And still not as short, simple and readable as the good old `with_together`...

**Pull request merged**
