### PR TITLE
New module postgresql_slot: Add or remove slots from a PostgreSQL database

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add or remove physical or logical slots from a PostgreSQL database.

For more information see:
https://www.postgresql.org/docs/current/protocol-replication.html and
https://www.postgresql.org/docs/current/logicaldecoding-explanation.html

##### ISSUE TYPE
- New Module Pull Request

##### SPECIFIC OPTIONS
- name: Name of the slot to add or remove. aliases: [ slot_name]
- slot_type: Slot type. choices: [ logical, physical ]
- state: The slot state.
- immediately_reserve: Optional parameter the when C(yes) specifies that the LSN for this replication slot be reserved immediately, otherwise the default, C(no), specifies that the LSN is reserved on the first connection from a streaming replication client. Uses only with I(slot_type=physical).
- output_plugin: All logical slots must indicate which output plugin decoder they're using. This parameter does not apply to physical slots. It will be ignored with I(slot_type=physical).

##### RETURN
```
name:
  description: Name of the slot
  returned: always
  type: str
  sample: "physical_one"
queries:
  description: List of executed queries.
  returned: always
  type: str
  sample: [ "SELECT pg_create_physical_replication_slot('physical_one', False, False)" ]
```

##### EXAMPLES
```
- name: Create physical_one physical slot if doesn't exist
  become_user: postgres
  postgresql_slot:
    slot_name: physical_one
    db: ansible

- name: Remove physical_one slot if exists
  become_user: postgres
  postgresql_slot:
    slot_name: physical_one
    db: ansible
    state: absent

- name: Create logical_one logical slot to the database acme if doen't exist
  postgresql_slot:
    name: logical_slot_one
    slot_type: logical
    state: present
    output_plugin: custom_decoder_one

- name: Remove logical_one slot if exists from the cluster running on another host and non-standard port
  postgresql_slot:
    name: logical_one
    login_host: mydatabase.example.org
    port: 5433
    login_user: ourSuperuser
    login_password: thePassword
    state: absent
```

### CODE REVIEW

**Comment by Andersson007** [comment]
instead of [#39902](https://github.com/ansible/ansible/pull/39902)

**Review by gundalow — APPROVED** [review]
Do we have a test for updating from slot_type physical to logical (or reversed)?

**Comment by Andersson007** [comment]
> Do we have a test for updating from slot_type physical to logical (or reversed)?

If I understood your question right it's impossible to make logical from physical, etc.
(technically I can implement this but it looks quite dangerous. better to remove a slot at first, then create new one with suitable type)

**Comment by Andersson007** [comment]
@gundalow , and I remember about moving function connect_to_db() to module_utils.
I've added also get_pg_version().
Going to do it by single PR for all modules.

**Comment by gundalow** [comment]
Does the module need to gracefully error if someone attempts to change `slot_type` then?

**Comment by Andersson007** [comment]
> Does the module need to gracefully error if someone attempts to change `slot_type` then?

@gundalow , lines 243-244 below
```
238     def create(self, kind='physical', immediately_reserve=False, output_plugin=False, just_check=False):
239         if self.exists:
240             if self.kind == kind:
241                 return False
242             else:
243                 self.module.warn("slot with name '%s' already exists "
244                                  "but has another type '%s'" % (self.name, self.kind))
245                 return False
```

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
@Andersson007 Thank you for another great module and test :)

**Pull request merged**
