### PR TITLE
Initial add of the cpm_interface_info module

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Initial add of the cpm_interface_info module, to view ethernet port parameters of WTI devices

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
cpm_interface_info

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by maragon737** [comment]
Is the information for stored or operational interface information?

**Comment by mattsene** [comment]
Hi,

How many Ethernet interfaces can I configure or get the status of ?

**Comment by adam1978978** [comment]
How can I see if the plug is physically plugged into the Ethernet port?

**Comment by wtinetworkgear** [comment]
@maragon737 its both stored and operational. It stores the information and then sets the operational interface information

**Comment by wtinetworkgear** [comment]
@mattsene It depends how many ethernet ports you have in your WTI device. For this query module max would be 3 (eth0, eth1, ppp0). We also have a config module (https://github.com/ansible/ansible/pull/64624), currently this is two as the ppp0 port will have its own module.

**Comment by wtinetworkgear** [comment]
@adam1978978 In the return JSON there is a tag called "is_up", this will be 0 if the cable is disconnected or 1 if there is a cable plugged in. For the cellular port this tag is 0 is there is no active cellular connection or 1 is there is a cellular connection established.

**Comment by Mariom949** [comment]
How do I display the firewall for the Ethernet ports

**Comment by wtinetworkgear** [comment]
@Mariom949 You can not display the firewall information with this module, one if forthcoming with this ability. We will mention you when it has been submitted for testing

**Pull request closed without merging**
