### PR TITLE
modules/terraform: Add the `workspace` parameter

### LINKED ISSUE #43134: Add support of workspaces in terraform module
##### SUMMARY

From Terraform documentation: 
```
Certain backends support multiple named workspaces, allowing multiple states to be associated with a single configuration.
```

The module currently does not support the notion of workspace. Adding it would be helpful.
The default workspace would be "default" and would not break the current usage of the module.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
terraform

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /Users/remirey/dev/grtgas/avignon/ansible.cfg
  configured module search path = [u'/Users/remirey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/remirey/.virtualenvs/avignon/lib/python2.7/site-packages/ansible
  executable location = /Users/remirey/.virtualenvs/avignon/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
# Basic deploy of a service with workspace
- terraform:
    project_path: '{{ project_dir }}'
    state: present
    workspace: staging
```

### PR DESCRIPTION
**Pull request by rrey**
##### SUMMARY

From terraform documentation:
```
The persistent data stored in the backend belongs to a workspace. Initially the backend has only one workspace, called "default", and thus there is only one Terraform state associated with that configuration.

Certain backends support multiple named workspaces, allowing multiple states to be associated with a single configuration. The configuration still has only one backend, but multiple distinct instances of that configuration to be deployed without configuring a new backend or changing authentication credentials.
```

This patch introduces the `workspace` parameter in the terraform module. The module will select
the workspace is it does not exists, or simply select it if it exists.

Fixes #43134

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
terraform

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/Users/remirey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/remirey/.virtualenvs/avignon/lib/python2.7/site-packages/ansible
  executable location = /Users/remirey/.virtualenvs/avignon/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

### CODE REVIEW

**Review by ryansb — APPROVED** [review]

**Comment by ryansb** [comment]
Since workspace-use is a semi-stateful setting (once you `workspace select`, that stays until the next selection), what do you think of adding a cleanup that saves the workspace at the start and restores that one before returning?

**Comment by rrey** [comment]
Good idea
Locally I also added a « delete_workspace » boolean that acts when state = absent 
My use case is inside a CI job that creates a workspace for each feature branch. I wanted a way to remove the workspace after thé destroy call.
What do you think ?

**Comment by rrey** [comment]
@ryansb I closed this PR accidentaly, could you re-open it ?

**Comment by ryansb** [comment]
@rrey I can't because it seems your branch add-terraform-workspace was destroyed. 

I love the idea of also being able to delete a workspace, but to match convention in other modules I would prefer it be named `purge_workspace` instead of `delete_workspace`. 

You can open a new PR from your branch, and I'll be happy to review again and we can get this feature in for Ansible 2.7. Just make sure to add `@ryansb` in the new PR description.

**Comment by rrey** [comment]
ok thx

Edit: new PR : #43489

**Pull request closed without merging**
