### PR TITLE
Fixes #31049 : Missing facts in SunOS module

### LINKED ISSUE #31049: Missing facts on Solaris 11.3 (x86) with Ansible 2.4
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
setup / gather_facts

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/username/git/mailsysteme/ansible.cfg
  configured module search path = [u'/Users/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/Users/username/git/project/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_PIPELINING(/Users/username/git/project/ansible.cfg) = False
DEFAULT_FORKS(/Users/username/git/project/ansible.cfg) = 10
DEFAULT_HOST_LIST(/Users/username/git/project/ansible.cfg) = [u'/Users/username/git/project/staging.ini']
DEFAULT_TIMEOUT(/Users/username/git/project/ansible.cfg) = 60
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/Users/username/git/project/ansible.cfg) = True
DEPRECATION_WARNINGS(/Users/username/git/project/ansible.cfg) = True
RETRY_FILES_ENABLED(/Users/username/git/project/ansible.cfg) = False
```

##### OS / ENVIRONMENT

- macOS Sierra 10.12.6

##### SUMMARY
Since Ansible 2.4.0.0 the setup module drops many facts on Solaris 11.3 (x86) systems which were available in Ansible 2.3. CentOS 7.4 seems not to be affected by this issue.

In a quick diff the following facts are missing:

- ansible_devices
- ansible_memtotal_mb
- ansible_mounts
- ansible_processor
- ansible_processor_cores
- ansible_processor_count
- ansible_swap_allocated_mb
- ansible_swap_reserved_mb
- ansible_swapfree_mb
- ansible_swaptotal_mb
- ansible_uptime_seconds

In my case it was `ansible_mounts` which broke my plays...

##### STEPS TO REPRODUCE

```bash
ansible all -i inventory.ini -m setup
```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by jcea**
##### SUMMARY

Fixes #31049 .

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

SunOS

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /home/jcea/hg/ansible/ansible.cfg
  configured module search path = [u'/home/jcea/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 16:03:25) [GCC 5.4.0 20160609]
```

### CODE REVIEW

**Comment by alikins** [comment]
Looks good to me. Just kicked off a rebuild in shippable, but ready to merge once that passes.

**Comment by mattclay** [comment]
This fix needs to be applied to devel and then cherry picked to stable-2.4. The PR should not be made against stable-2.4.

needs_revision

**Comment by mattclay** [comment]
@jcea Please open a new PR for this fix against the devel branch. Once the fix is merged we can cherry pick to the stable-2.4 branch.

**Comment by jcea** [comment]
@mattclay Sorry, I was not paying attention. New PR #35624. Place, backport to 2.4.

Thanks for your time.

**Pull request closed without merging**
