### PR TITLE
Remove old 'srtd' theme and references.

### PR DESCRIPTION
**Pull request by Xaroth**
##### SUMMARY

The webdocs still had the old (used until 2.4) 'srtd' theme in its tree, as well as references and other files that were no longer used.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
Docs

### CODE REVIEW

**Comment by acozine** [comment]
I built this locally and looked at a few random pages. The formatting on `Note` and `Warning` sections doesn't look correct. For example:

Current docsite [ACI Guide, Auth section](https://docs.ansible.com/ansible/devel/scenario_guides/guide_aci.html#aci-authentication):

screen shot 2018-11-30 at 3 31 24 pm

Local build from this branch, same page:

screen shot 2018-11-30 at 3 33 12 pm

**Comment by acozine** [comment]
After debugging with @Xaroth, discovered the issue above only happens when viewing the output via `file:///path/to/_build/html/filename.html`. If I run a local webserver (`python -m SimpleHTTPServer`) and view the files from `localhost:port#` I see the boxes for `Note` and `Warning`. 

However, on the `devel` branch I get the boxes even with `file:///` . . . unless that's something to do with caching. If anyone has time to test this, post updates on your experiences.

**Comment by samccann** [comment]
Local build (file:///) of this page seems to match the current docsite:

image

**Comment by samccann** [comment]
Hi @Xaroth !  Sorry for the delay here. Can you rebase etc and once shippable passes and I give it another quick test locally, we should be good to merge.

**Review by gundalow — CHANGES_REQUESTED** [review]
I want to do some testing on this before it gets merged, please remind me if I don't get that done next week

**Review by gundalow — APPROVED** [review]
Tested a few pages locally, looks good. Thanks for doing this.

**Comment by acozine** [comment]
Thanks @Xaroth for the PR and for the persistence!

**Pull request merged**
