### PR TITLE
new module: sysctl to handle sysctl entry

### PR DESCRIPTION
**Pull request by davixx**
This is my first module for ansible,
Thanks for documentation and existing module to help me to write new one.
Once this one is OK, i probably push more modules.

Please do not hesitate to tell me if something wrong.

### CODE REVIEW

**Comment by mpdehaan** [comment]
it seems to me most of the time you would manage sysctl by just using the template module to write the file and then doing a "when_boolean: ${last_result.changed}" statement to rerun the CLI if the file changed, or maybe even a simple handler if you can afford to wait to the end of the ansible run.  (Probably could, right?)

Or you could also use the lineinfile module.

Otherwise we'd end up with a module for every type of config file, more or less?

What do you think?   

Perhaps I am missing something from reading the code -- so don't misconstrue this as an outright "no" to the module...

**Comment by davixx** [comment]
Thanks for your answer.

It is the first version of the module.
I'm a new user of ansible, but i can say that a playbook can quickly become a big file.

At now sysctl permit to have one action instead two in the playbook.
I plan to add to the module :
- the choice for the user to activate or not the "sysctl -p" if something change.
- the smart check of the involved sysctl key (by verifying existence in /proc/sys) ; 
- the smart check of the value seen in /proc/sys after the sysctl -p
- some checks (path for sysctl binary and configuration file)

For the rest, i recognize i'm actually not a master of ansible, and may be, there is also some ways that actually permit to use existing module with 2 or more action for doing that.

it's so your choice to pull or not.
if pulled, i will take the time within 14 days to implement previous functionnality.
i had made this first version because it's my first pull request, and i have to be sure i'm not loosing time to develop in python, respecting rules to gain points, and be merged to the ansible/ansible project ; and not only my forked one.

Thanks for your time.

**Comment by mpdehaan** [comment]
Ok, how about you submit it when you think it is complete and contains
those capabilities.   We generally want stuff merged when it's ready for
use by everyone.

When you do that, include some examples and explanations of what the "smart
checks" do if not obvious in the implementation.

**Comment by mpdehaan** [comment]
To be clear, sounds like there is enough for a module here, it's just not done yet.

Let me know if you have other questions.

**Comment by davixx** [comment]
OK ; i will come back soon with another pull request

**Pull request closed without merging**
