### PR TITLE
Update undocumented glossary items

### PR DESCRIPTION
**Pull request by dpiotrowski**
##### SUMMARY
Update some undocumented glossary items:
 - play/roles
 - task/register
 - task/notify

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
Documentation

### CODE REVIEW

**Review by dharmabumstead — APPROVED** [review]
Docs look good - thank!. Core team please sign off.

**Comment by bcoca** [comment]
This file  should not be part of the repo, it is constructed during doc generation and will be overwritten 
you want to update https://github.com/ansible/ansible/blob/devel/docs/docsite/keyword_desc.yml instead.

**Comment by bcoca** [comment]
I removed this file and updated .gitignore to avoid future confusion

**Comment by dpiotrowski** [comment]
Oh well, I've just made a mess of this PR, sorry. I'm going to close it and open a new one once I sort this out.

**Pull request closed without merging**
