### PR TITLE
Feature/ec2 profiles

### PR DESCRIPTION
**Pull request by ghost**
This change allows a user to specify a profile in ec2.ini which will then be referenced automatically by boto when reading credentials from ~/.boto

The benefit is that it allows easily creating inventory directories pointed to different AWS accounts

### CODE REVIEW

**Comment by mpdehaan** [comment]
Should probably be disabled for default, no?   Otherwise this would look for a profile that might not exist?

**Comment by ghost** [comment]
That's why it defaults to None if the config key isn't specified, which is the boto function's default profile value if it's left undefined.

**Comment by ghost** [comment]
I've merged in HEAD (minor conflicts with new features added to ec2 inventory since PR was opened).

I've also commented out the profile in the sample .ini file to emphasize the use of boto profiles is 100% optional

**Comment by mpdehaan** [comment]
# Cleanup Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We do require submissions to be free of merge commits, which cause difficulties in reviewing and merging code, and also affect the history of the source tree.
To resolve this problem, it may be helpful to create a new branch and cherry-pick commits onto it.
- In general, always start a "topic branch" named after each thing you would like to contribute
- use "git pull --rebase" vs "git pull" to stay in tune with upstream, as well as "git rebase" vs "git merge"
- if you have things broken out over many commits, consider submitting just one squashed commit that keeps the history concise

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by ghost** [comment]
Closing PR. Created a new branch and cleanly applied feature to it.

**Pull request closed without merging**
