### PR TITLE
Piolink`s new module for pio_app

### PR DESCRIPTION
**Pull request by sikim-piolink**
##### SUMMARY

Piolink`s new module for pio_app

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

pio_app.py

##### ADDITIONAL INFORMATION

```paste below
You can manage the WEBFRONT-K applications.
```

### CODE REVIEW

**Comment by sikim-piolink** [comment]
shipit

**Comment by sikim-piolink** [comment]
@ansibot shipit

**Comment by sikim-piolink** [comment]
@ansibot bot_status

**Comment by sikim-piolink** [comment]
@ansibot shipit

**Comment by sikim-piolink** [comment]
@ansibot ready_for_review

**Comment by sikim-piolink** [comment]
@seonil9036 review

**Comment by Seonil9036** [comment]
shipit

**Review by Seonil9036 — COMMENTED** [review]
review ok

**Comment by Seonil9036** [comment]
shipit

**Review by Seonil9036 — APPROVED** [review]
ok

**Comment by Seonil9036** [comment]
shipit

**Comment by sikim-piolink** [comment]
shipit

**Comment by sikim-piolink** [comment]
@ansibot bug_resolved

**Comment by Seonil9036** [comment]
LGTM

**Review by Seonil9036 — APPROVED** [review]
ok

**Comment by sikim-piolink** [comment]
shipit

**Review by jda03 — APPROVED** [review]
ok

**Comment by jda03** [comment]
shipit

**Comment by sikim-piolink** [comment]
shipit

**Comment by sikim-piolink** [comment]
ready_for_review

**Comment by sikim-piolink** [comment]
@ansibot bot_status

**Comment by sikim-piolink** [comment]
bot_broken

**Comment by sikim-piolink** [comment]
bot_status

**Comment by sikim-piolink** [comment]
@ansibot bot_status

**Comment by sikim-piolink** [comment]
-needs_triage

**Comment by sikim-piolink** [comment]
-bot_broken

**Comment by sikim-piolink** [comment]
@ansibot ready_for_review

**Comment by sikim-piolink** [comment]
@gundalow 
I want to know the pull request procedure

**Comment by justjais** [comment]
@sikim-piolink Thanks for raising the PR, but from Ansible `2.9` onward we have started moving all module to its own collection and hence we're not accepting any new module in Ansible repo.

So, please create a new Collection with all the required modules and push it to Ansible galaxy. Please ref following to get your collection started:
https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html

**Comment by justjais** [comment]
@sikim-piolink I am closing the PR, so please move the modules to piolink collection as suggested above.

**Pull request closed without merging**
