### PR TITLE
Proposed ansible-rsync to core.

### PR DESCRIPTION
**Pull request by tima**

### CODE REVIEW

**Comment by bcoca** [comment]
don't worry about the phrasing, you have a legion of likes and +10s to this
one (pending implementation review)

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tima** [comment]
@bcoca: well I fixed it so I didn't seem so presumptuous.

**Comment by mpdehaan** [comment]
Thank you!  Due to upcoming holiday weekend, this may not get reviewed instantaneously.  Do not take that for lack of interest!

**Comment by tartansandal** [comment]
Testing this now. Noticed a bit of repetition in the examples documentation. The following might be clearer.

```
local_action: synchronize src=some/relative/path dest=/some/absolute/path
synchronize: src=some/relative/path dest=/some/absolute/path
synchronize: src=some/relative/path dest=/some/absolute/path mode=pull
synchronize: src=some/relative/path dest=/some/absolute/path delete=yes
synchronize: src=some/relative/path dest=/some/absolute/path verbosity=1
```

**Comment by tartansandal** [comment]
A quick pass through the code and I see you have some undocumented module options.

```
rsync_path
local_rsync_path
ansible_rsync_path
private_key
```

I would be great if they could be explained.

**Comment by tartansandal** [comment]
Okay I tried the following playbook:

```
- hosts: all
  tasks:
    - synchronize: src=/home/kal/test dest=/home/kal/test mode=push
```

on a single host and got

```
TASK: [synchronize src=/home/kal/test dest=/home/kal/test mode=push] ********** 
failed: [buffy] => {"cmd": "rsync --archive --delay-updates --compress --quiet --temp-dir /home/a_kal/.ansible/tmp/ansible-1369442412.39-71248828295465 --rsh 'ssh -i None -o StrictHostKeyChecking=no' /home/kal/test a_kal@None:/home/kal/test", "failed": true, "rc": 255}
msg: Warning: Identity file None not accessible: No such file or directory.
ssh: Could not resolve hostname None: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(601) [sender=3.0.8]
```

Where is this 'None' comming from?  Why is it trying to set a private key?

**Comment by dalevizo** [comment]
I tried it with the following syntax and it does the trick to rsync files from my ansible server to a remote host
`local_action: synchronize src=some/relative/path dest=$inventory_hostname:/some/absolute/path`

**Comment by tima** [comment]
@tartansandal:

The rsync paths was something I was the last thing I was working on and wasn't entirely sure it nailed all the uses cases. Here an explanation of each:

**rsync_path**
This is the path of rsync on the remote host rsync is contacting. See --rsync-path in the rsync man page

**local_rsync_path**
This is a pass thru option not meant for public use. The action module looks up a host variable in the inject data structure and puts it in this option for the module that is sent over to the remote host. This is similar to how hosts can define the location of the python interpreter.

**ansible_rsync_path**
This is the host variable associated to the above.

**private_key**
This is another pass thru option not meant for public use. Here we are passing the value of ansible_ssh_private_key_file host variable over to the remote host for its use.

The error you are getting is because the module thinks its working with a remote host for some reason. I'm not sure how you defined your host list of what your intent is. If you are trying to sync files between the same host you need to delegate_to itself. If you want to sync files on the local host (running Ansible) you want to force a local connection thru a local_action or a connection: local. Right now it thinks you are trying to get files from the localhost to the remote host via a (none existent hostname) and private key.

There is probably some better error handling needed here, but I'm pretty sure you aren't defining the task to do what you want.

**Comment by tima** [comment]
@tartansandal On the documentation issue. One of the entries seems like a duplicate because a delegate_to option is missing from the example code though its mentioned in the description. The fourth example should be:

```
- code: |
      synchronize: src=some/relative/path dest=/some/absolute/path'
        delegate_to: delegate.host
  description: Synchronization of src on delegate to dest on the current inventory host
```

Hope that helps. Thanks for your feedback and testing.

**Comment by tartansandal** [comment]
On Wed, May 29, 2013 at 4:53 AM, Timothy Appnel notifications@github.comwrote:

> The rsync paths was something I was the last thing I was working on and
> wasn't entirely sure it nailed all the uses cases. Here an explanation of
> each:
> 
> _rsync_path_
> This is the path of rsync on the remote host rsync is contacting. See
> --rsync-path in the rsync man page
> 
> Thanks for the private option explanation!  I was digging around trying to
> make sense of rsync_path and the the others were confusing me.  I think
> this might be an important option and documenting the '--rsync-path="sudo
> rsync"' might be worthwhile.
> I'll do some more testing and see if I can suggest a documentation string.
> 
> The error you are getting is because the module thinks its working with a
> remote host for some reason. I'm not sure how you defined your host list of
> what your intent is. If you are trying to sync files between the same host
> you need to delegate_to itself. If you want to sync files on the local host
> (running Ansible) you want to force a local connection thru a local_action
> or a connection: local. Right now it thinks you are trying to get files
> from the localhost to the remote host via a (none existent hostname) and
> private key.
> 
> My intent was to simple synchronise a local directory (on the ansible host)
> with a remote host with the same user. The host file was just a one-liner
> containing the host name.  Intuitively, I was thinking src and dest acted
> the same as in the copy module, but I see there is more subtlety here.
> I'll test this a bit more ...

K

Kahlil (Kal) Hodgson                       GPG: C9A02289
Head of Technology                         (m) +61 (0) 4 2573 0382
DealMax Pty Ltd                            (w) +61 (0) 3 9008 5281

Suite 1415
401 Docklands Drive
Docklands VIC 3008 Australia

"All parts should go together without forcing.  You must remember that
the parts you are reassembling were disassembled by you.  Therefore,
if you can't get them together again, there must be a reason.  By all
means, do not use a hammer."  -- IBM maintenance manual, 1925

**Comment by tartansandal** [comment]
On Wed, May 29, 2013 at 5:02 AM, Timothy Appnel notifications@github.comwrote:

> @tartansandal https://github.com/tartansandal On the documentation
> issue. One of the entries seems like a duplicate because a delegate_to
> option is missing from the example code though its mentioned in the
> description. The fourth example should be:
> - code: |
>     synchronize: src=some/relative/path dest=/some/absolute/path'
>       delegate_to: delegate.host
>   description: Synchronization of src on delegate to dest on the current inventory host
> 
> Arrgh! The example descriptions are not being displayed by ansible-doc so I
> missed that. Actually the output of

```
ansible-doc synchronize
```

does not contain any reference to 'delegate'.

Hmmmm...
- code: 'synchronize: src=some/relative/path dest=/some/absolute/path'
   description: Synchronization of src on the localhost to dest on the
  current inventory host

That was what I was trying to do and you suggest adding 'connection: local'?

Kahlil (Kal) Hodgson                       GPG: C9A02289
Head of Technology                         (m) +61 (0) 4 2573 0382
DealMax Pty Ltd                            (w) +61 (0) 3 9008 5281

Suite 1415
401 Docklands Drive
Docklands VIC 3008 Australia

"All parts should go together without forcing.  You must remember that
the parts you are reassembling were disassembled by you.  Therefore,
if you can't get them together again, there must be a reason.  By all
means, do not use a hammer."  -- IBM maintenance manual, 1925

**Comment by mpdehaan** [comment]
Apologies on the testing delay.

Assuming /tmp/test.yml and a directory /tmp/blarg with some files in it and

ansible-playbook /tmp/test.yml -c local

With this task:

```
- synchronize: src=blarg dest=/tmp/blarg2
```

I get:

failed: [127.0.0.1] => {"cmd": "rsync --archive --delay-updates --compress --quiet --temp-dir /home/mpdehaan/.ansible/tmp/ansible-1370028492.0-201533293457676 --rsh 'ssh -i None -o StrictHostKeyChecking=no' blarg root@None:/tmp/blarg2", "failed": true, "rc": 12}
msg: Warning: Identity file None not accessible: No such file or directory.
ssh: Could not resolve hostname None: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]

**Comment by tima** [comment]
Thanks @mpdehaan. Based on what's happen to you and @tartansandal it seems i'm missing something that Ansible thinks it's  synching with something remote rather than keeping it all local.

**Comment by mpdehaan** [comment]
Hi Tim, 

Thanks for the update.

You've got a merge commit in there which I can't merge.  You will want to be careful and keep a topic branch for each thing you work on, and do "git pull --rebase" vs "git merge".

If you can fix this up, I think we'll likely be merging this in early in 1.3, which should not be that bad as so many people run devel HEAD all of the time.

Thanks!

**Comment by tima** [comment]
Closing this out. Resubmitted this pull request as a new and separate topic branch.

**Pull request closed without merging**
