### PR TITLE
new module: panos_query_rules

### PR DESCRIPTION
**Pull request by ivanbojer**
##### SUMMARY
Search for security rules matching specific criteria

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
panos_query_rules

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb  6 2017, 11:22:10) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Comment by jborean93** [comment]
@ivanbojer are you able to rebase your PR by following the docs at http://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html

**Comment by ivanbojer** [comment]
ready_for_review

**Comment by jtschichold** [comment]
:shipit:

**Comment by gundalow** [comment]
Rebase needed, and unit test need to be added

**Comment by ivanbojer** [comment]
Rebase done! We cannot do unit tests in this release as that would need publicly accessible device.

**Comment by ivanbojer** [comment]
Didn't make it for 2.4

**Comment by gundalow** [comment]
@ivanbojer We can help you get this into Ansible 2.5 if you want to reopen the PR...

**Comment by gundalow** [comment]
Unit tests don't need a publicly accessible device, you can mock out the data, see other network modules unit tests

**Pull request closed without merging**
