### PR TITLE
correct collection use for actions calling modules

### LINKED ISSUE #69788: Module redirection fails within collection for command if shell module is used in role within collection
##### SUMMARY

The test case https://github.com/ansible-collections/cisco.ios/blob/master/tests/integration/targets/ios_user/tests/cli/auth.yaml#L63 with task
```
    - name: test sshkey login
      shell: ssh ssh_user@{{ ansible_ssh_host }} -p {{ ansible_ssh_port|default(22)
        }} -o IdentityFile={{ role_path }}/files/test_rsa -o UserKnownHostsFile=/dev/null
        -o StrictHostKeyChecking=no -o BatchMode=yes -o PubkeyAuthentication=yes
        show version

```
fails with error
```
}
2020-05-22 18:07:38,267 p=27402 u=zuul n=ansible | TASK [ios_user : test sshkey login] ********************************************
2020-05-22 18:07:38,267 p=27402 u=zuul n=ansible | task path: /home/zuul/.ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_user/tests/cli/auth.yaml:63
2020-05-22 18:07:38,398 p=27974 u=zuul n=ansible | <162.253.42.96> attempting to start connection
2020-05-22 18:07:38,399 p=27974 u=zuul n=ansible | <162.253.42.96> using connection plugin ansible.netcommon.network_cli
2020-05-22 18:07:38,399 p=27974 u=zuul n=ansible | Found ansible-connection at path /home/zuul/venv/bin/ansible-connection
2020-05-22 18:07:40,807 p=27974 u=zuul n=ansible | <162.253.42.96> found existing local domain socket, using it!
2020-05-22 18:07:40,808 p=27974 u=zuul n=ansible | <162.253.42.96> ssh connection done, setting terminal
2020-05-22 18:07:40,808 p=27974 u=zuul n=ansible | <162.253.42.96> loaded terminal plugin for network_os cisco.ios.ios
2020-05-22 18:07:40,844 p=27974 u=zuul n=ansible | <162.253.42.96> updating play_context for connection
2020-05-22 18:07:40,844 p=27974 u=zuul n=ansible | <162.253.42.96> 
2020-05-22 18:07:40,844 p=27974 u=zuul n=ansible | <162.253.42.96> local domain socket path is /home/zuul/.ansible/pc/1e21ebcf11
2020-05-22 18:07:40,848 p=27974 u=zuul n=ansible | <162.253.42.96> ESTABLISH LOCAL CONNECTION FOR USER: zuul
2020-05-22 18:07:40,849 p=27974 u=zuul n=ansible | <162.253.42.96> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e `"&& mkdir /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/ansible-tmp-1590170860.8482132-27974-108949243179715 && echo ansible-tmp-1590170860.8482132-27974-108949243179715="` echo /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/ansible-tmp-1590170860.8482132-27974-108949243179715 `" ) && sleep 0'
2020-05-22 18:07:40,857 p=27974 u=zuul n=ansible | redirecting (type: modules) cisco.ios.command to cisco.ios.ios_command
2020-05-22 18:07:41,138 p=27974 u=zuul n=ansible | Using module file /home/zuul/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_command.py
2020-05-22 18:07:41,139 p=27974 u=zuul n=ansible | <162.253.42.96> PUT /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/tmpbyt4_0pk TO /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/ansible-tmp-1590170860.8482132-27974-108949243179715/AnsiballZ_ios_command.py
2020-05-22 18:07:41,140 p=27974 u=zuul n=ansible | <162.253.42.96> EXEC /bin/sh -c 'chmod u+x /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/ansible-tmp-1590170860.8482132-27974-108949243179715/ /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/ansible-tmp-1590170860.8482132-27974-108949243179715/AnsiballZ_ios_command.py && sleep 0'
2020-05-22 18:07:41,146 p=27974 u=zuul n=ansible | <162.253.42.96> EXEC /bin/sh -c '/home/zuul/venv/bin/python /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/ansible-tmp-1590170860.8482132-27974-108949243179715/AnsiballZ_ios_command.py && sleep 0'
2020-05-22 18:07:41,409 p=27974 u=zuul n=ansible | <162.253.42.96> EXEC /bin/sh -c 'rm -f -r /home/zuul/.ansible/tmp/ansible-local-27402rj7dtu3e/ansible-tmp-1590170860.8482132-27974-108949243179715/ > /dev/null 2>&1 && sleep 0'
2020-05-22 18:07:41,419 p=27402 u=zuul n=ansible | fatal: [ios-15.6-2T]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "_raw_params": "ssh ssh_user@162.253.42.96 -p 22 -o IdentityFile=/home/zuul/.ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_user/files/test_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o BatchMode=yes -o PubkeyAuthentication=yes show version",
            "_uses_shell": true,
            "warn": true
        }
    },
    "msg": "Unsupported parameters for (command) module: _raw_params, _uses_shell, warn Supported parameters include: commands, interval, match, provider, retries, wait_for"
}
```
There is a short name redirection within the collection from `command` and `ios_command`
https://github.com/ansible-collections/cisco.ios/blob/c6aa603a701ab7d31b71e0b3dd4b08cffc738376/meta/runtime.yml#L134

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
2.10
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by bcoca**
##### SUMMARY
Use action plugin 'collection context' to handle module calling
fixes #69788
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

action

### CODE REVIEW

**Comment by nitzmahone** [comment]
Yeah, I don't think this is the way we want to handle it either... Really, the caller to `execute_module` should be the one deciding what behavior they want. FQCN is obvious, but for any other unqualified module, should it inherit the task's collection order, legacy only/2.9 fallback compat only, or custom search order? Most of these internal cases that are trying to call a very specific module should *not* consult the collections order, they should either be using a real FQCN or `ansible.legacy` to allow user overrides from configured module paths, `library/`, etc.

**Comment by bcoca** [comment]
This is for 'existing' action plugins, I agree new ones should FQCN, but we need something like this for backwards compat. 

As to the 'exact list' that should be in collections .. that is where I can see many ways to go .. at very least this should default to 'self collection', but I can see cases made for keeping the collection list from the task with just re-prioritizing the self one as this PR does, but I also see it as a stretch.

**Comment by bcoca** [comment]
this variant forces 'current collection' as the only part of the list and ignores rest of task collection list
```
            coll_list = []
            names = getattr(self, '_redirected_names', [])
            if names:
                current = names[-1]
                if AnsibleCollectionRef.is_valid_fqcr(current):
                    coll_list = [AnsibleCollectionRef.from_fqcr(current)]
```

**Comment by ganeshrn** [comment]
@bcoca Trigerred `cisco.ios` integration test with this PR as depends-on https://github.com/ansible-collections/cisco.ios/pull/55

**Comment by nitzmahone** [comment]
Diddling the collection search list is not the right thing to do here, regardless- any code change we make here is going to break other things. The callers that actually want to allow a user override can use `ansible.legacy.whatever` without any of this messing about, so long as there's a redirect entry for `whatever` in ansible-base. New code should use the FQCN of the action/module.

So the code change we should be making to "fix" #69788 while still allowing folks to override is to change the internal delegation to `command` inside the `shell` module to `ansible.legacy.command`.

**Comment by bcoca** [comment]
I'm not against adding `ansible.legacy` to our plugins, but we still need to update this code to handle other plugins that have not been updated to do same. Otherwise its a time bomb waiting for someone with 3rd party actions to hit the 'name coincidence' .. in this case 'command' but 'user' and 'host' or 'instance' will probably also happen soon enough. 

After this is fixed in a generic way, I'm all for going to every one of our own action plugins (except normal) and update them to use `ansible.legacy`.

**Comment by ganeshrn** [comment]
@bcoca The integration test is now failing with error.
```
2020-06-03 17:46:48,137 p=3865 u=zuul n=ansible | TASK [ios_acl_interfaces : Populate Config] ************************************
2020-06-03 17:46:48,138 p=3865 u=zuul n=ansible | task path: /home/zuul/.ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_acl_interfaces/tests/cli/_populate_config.yaml:2
2020-06-03 17:46:48,246 p=3911 u=zuul n=ansible | <74.63.204.61> attempting to start connection
2020-06-03 17:46:48,246 p=3911 u=zuul n=ansible | <74.63.204.61> using connection plugin ansible.netcommon.network_cli
2020-06-03 17:46:48,247 p=3911 u=zuul n=ansible | Found ansible-connection at path /home/zuul/venv/bin/ansible-connection
2020-06-03 17:46:50,348 p=3907 u=zuul n=ansible | jsonrpc request: {"params": [[], {"var_options": {"ansible_become_method": "ansible.netcommon.enable", "ansible_port": 22, "ansible_become": "true", "ansible_user": "zuul", "ansible_network_os": "cisco.ios.ios", "ansible_host": "74.63.204.61"}}], "jsonrpc": "2.0", "method": "set_options", "id": "3b56728d-5621-48c4-96a8-425ac8895e1e"}
2020-06-03 17:46:50,349 p=3907 u=zuul n=ansible | jsonrpc response: {"result": "N.", "jsonrpc": "2.0", "id": "3b56728d-5621-48c4-96a8-425ac8895e1e", "result_type": "pickle"}
2020-06-03 17:46:50,350 p=3907 u=zuul n=ansible | jsonrpc request: {"params": [["(dp1\nS'prompt'\np2\nV\nsS'debugger'\np3\nNsS'vars'\np4\n(dp5\nsS'ignore_unreachable'\np6\nNsS'become_user'\np7\nNsS'private_key_file'\np8\nNsS'skip_tags'\np9\nc__builtin__\nset\np10\n((ltRp11\nsS'module_compression'\np12\nVZIP_DEFLATED\np13\nsS'connection_lockfd'\np14\nI6\nsS'diff'\np15\nI01\nsS'sftp_extra_args'\np16\nV\nsS'port'\np17\nI22\nsS'ssh_extra_args'\np18\nV\nsS'squashed'\np19\nI00\nsS'environment'\np20\nNsS'executable'\np21\nV/bin/sh\np22\nsS'remote_user'\np23\nVzuul\np24\nsS'become_method'\np25\nVansible.netcommon.enable\np26\nsS'uuid'\np27\nS'fa163e2d-c8ee-b69d-1a35-000000000013'\np28\nsS'only_tags'\np29\ng10\n((ltRp30\nsS'finalized'\np31\nI01\nsS'module_defaults'\np32\nNsS'no_log'\np33\nI00\nsS'ssh_executable'\np34\nVssh\np35\nsS'docker_extra_args'\np36\nNsS'remote_addr'\np37\nV74.63.204.61\np38\nsS'become_pass'\np39\nNsS'connection_user'\np40\nNsS'shell'\np41\nNsS'force_handlers'\np42\nI01\nsS'ssh_transfer_method'\np43\nNsS'check_mode'\np44\nI00\nsS'start_at_task'\np45\nNsS'run_once'\np46\nNsS'step'\np47\nI00\nsS'become'\np48\nI01\nsS'ignore_errors'\np49\nNsS'password'\np50\nNsS'throttle'\np51\nI0\nsS'name'\np52\nV\nsS'any_errors_fatal'\np53\nI00\nsS'verbosity'\np54\nI4\nsS'become_flags'\np55\nNsS'scp_extra_args'\np56\nV\nsS'connection'\np57\nccopy_reg\n_reconstructor\np58\n(cansible.parsing.yaml.objects\nAnsibleUnicode\np59\nc__builtin__\nunicode\np60\nVansible.netcommon.network_cli\ntRp61\n(dp62\nS'_column_number'\np63\nI25\nsS'_data_source'\np64\nV/home/zuul/.ansible/collections/ansible_collections/cisco/ios/tests/integration/targets/ios_acl_interfaces/tasks/cli.yaml\np65\nsS'_line_number'\np66\nI17\nsbsS'network_os'\np67\nVcisco.ios.ios\np68\nsS'timeout'\np69\nI100\nsS'pipelining'\np70\nI00\nsS'become_exe'\np71\nNsS'ssh_common_args'\np72\nV\nsS'ssh_args'\np73\nV-C -o ControlMaster=auto -o ControlPersist=60s\np74\ns."], {}], "jsonrpc": "2.0", "method": "update_play_context", "id": "e217c895-e391-4788-b45b-36f422d4d679"}
2020-06-03 17:46:50,351 p=3907 u=zuul n=ansible | jsonrpc response: {"result": "N.", "jsonrpc": "2.0", "id": "e217c895-e391-4788-b45b-36f422d4d679", "result_type": "pickle"}
2020-06-03 17:46:50,351 p=3907 u=zuul n=ansible | jsonrpc request: {"params": [["fa163e2d-c8ee-b69d-1a35-0000000000e3"], {}], "jsonrpc": "2.0", "method": "set_check_prompt", "id": "3c08e3d4-0aa4-4cad-a3a1-c10db3e0bd45"}
2020-06-03 17:46:50,351 p=3907 u=zuul n=ansible | jsonrpc response: {"result": "N.", "jsonrpc": "2.0", "id": "3c08e3d4-0aa4-4cad-a3a1-c10db3e0bd45", "result_type": "pickle"}
2020-06-03 17:46:50,352 p=3907 u=zuul n=ansible | jsonrpc request: {"params": [[], {}], "jsonrpc": "2.0", "method": "pop_messages", "id": "22217628-e083-4b21-8790-688c7af9034a"}
2020-06-03 17:46:50,352 p=3907 u=zuul n=ansible | jsonrpc response: {"result": "(lp1\n(S'warning'\np2\nVPersistent connection logging is enabled for 74.63.204.61. This will log ALL interactions to /home/zuul/ansible-debug.txt and WILL NOT redact sensitive configuration like passwords. USE WITH CAUTION!\ntp3\na(S'vvvv'\np4\nS'updating play_context for connection'\np5\ntp6\na.", "jsonrpc": "2.0", "id": "22217628-e083-4b21-8790-688c7af9034a", "result_type": "pickle"}
2020-06-03 17:46:50,374 p=3911 u=zuul n=ansible | <74.63.204.61> found existing local domain socket, using it!
2020-06-03 17:46:50,376 p=3911 u=zuul n=ansible | [WARNING]: Persistent connection logging is enabled for 74.63.204.61. This will
log ALL interactions to /home/zuul/ansible-debug.txt and WILL NOT redact
sensitive configuration like passwords. USE WITH CAUTION!

2020-06-03 17:46:50,376 p=3911 u=zuul n=ansible | <74.63.204.61> updating play_context for connection
2020-06-03 17:46:50,376 p=3911 u=zuul n=ansible | <74.63.204.61> 
2020-06-03 17:46:50,377 p=3911 u=zuul n=ansible | <74.63.204.61> local domain socket path is /home/zuul/.ansible/pc/0f686fbf9f
2020-06-03 17:46:50,380 p=3911 u=zuul n=ansible | <74.63.204.61> ESTABLISH LOCAL CONNECTION FOR USER: zuul
2020-06-03 17:46:50,381 p=3911 u=zuul n=ansible | <74.63.204.61> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/zuul/.ansible/tmp/ansible-local-3865f61sz0 `"&& mkdir /home/zuul/.ansible/tmp/ansible-local-3865f61sz0/ansible-tmp-1591206410.38-3911-120430782290637 && echo ansible-tmp-1591206410.38-3911-120430782290637="` echo /home/zuul/.ansible/tmp/ansible-local-3865f61sz0/ansible-tmp-1591206410.38-3911-120430782290637 `" ) && sleep 0'
2020-06-03 17:46:50,391 p=3911 u=zuul n=ansible | <74.63.204.61> EXEC /bin/sh -c 'rm -f -r /home/zuul/.ansible/tmp/ansible-local-3865f61sz0/ansible-tmp-1591206410.38-3911-120430782290637/ > /dev/null 2>&1 && sleep 0'
2020-06-03 17:46:50,402 p=3865 u=zuul n=ansible | The full traceback is:
Traceback (most recent call last):
  File "/home/zuul/venv/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 155, in run
    res = self._execute()
  File "/home/zuul/venv/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 669, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/zuul/.ansible/collections/ansible_collections/ansible/netcommon/plugins/action/cli_config.py", line 40, in run
    return super(ActionModule, self).run(task_vars=task_vars)
  File "/home/zuul/.ansible/collections/ansible_collections/ansible/netcommon/plugins/action/network.py", line 47, in run
    result = super(ActionModule, self).run(task_vars=task_vars)
  File "/home/zuul/venv/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/home/zuul/venv/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 853, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/home/zuul/venv/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 179, in _configure_module
    current_collection = coll_info[0]
TypeError: 'AnsibleCollectionRef' object does not support indexing

2020-06-03 17:46:50,403 p=3865 u=zuul n=ansible | fatal: [ios-15.6-2T]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
2020-06-03 17:46:50,429 p=3907 u=zuul n=ansible | jsonrpc request: {"params": [[], {}], "jsonrpc": "2.0", "method": "reset", "id": "a2fcbe03-87a9-4f92-91b0-c3c913aa99e8"}
2020-06-03 17:46:50,429 p=3907 u=zuul n=ansible | jsonrpc response: {"result": "N.", "jsonrpc": "2.0", "id": "a2fcbe03-87a9-4f92-91b0-c3c913aa99e8", "result_type": "pickle"}
2020-06-03 17:46:50,430 p=3865 u=zuul n=ansible | PLAY RECAP *********************************************************************
2020-06-03 17:46:50,430 p=3865 u=zuul n=ansible | ios-15.6-2T                : ok=13   changed=0    unreachable=0    failed=1    skipped=0   
```

**Comment by bcoca** [comment]
@ganeshrn we've been going back and forth a lot, if you just want to move on with your test the simplest 'fix' is adding `collections: ['ansible.legacy']` to the shell action.

**Comment by nitzmahone** [comment]
superseded by https://github.com/ansible/ansible/pull/70818

**Pull request closed without merging**
