### PR TITLE
os_keystone_endpoint: endpoint_interface, not interface

### PR DESCRIPTION
**Pull request by GSergeevich**
endpoint_interface in EXAMPLES ,but interface in table.
+label: docsite_pr

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ANSIBLE VERSION

```paste below

```

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by albertomurillo** [comment]
@emonty What was the reason to change `os_keystone_endpoint.interface` to `os_keystone_endpoint.endpoint_interface` during https://github.com/ansible/ansible/pull/20974/ ?

Now the [documentation](https://docs.ansible.com/ansible/2.6/modules/os_keystone_endpoint_module.html) is inconsistent.

I would opt to return it to `os_keystone_endpoint.interface` to make the option less redundant in name and match var `endpoint.interface` in the return values

**Comment by mnaser** [comment]
I'm not sure if @emonty had a chance to reply however there are several places where OpenStack will actually want 'interface' as a parameter.

For example, if you want to create an Keystone endpoint, you'll have to specify the interface, that conflicts with the existing non-trivially named interface.

**Comment by gundalow** [comment]
You can use `aliases` in documentation and argspec to allow both names. 
Currently it looks like only the `DOCUMENTATION` has been updated, but not the code

**Comment by gundalow** [comment]
@GSergeevich Hi, I hope the comments above make sense. I believe this is your first Ansible PR, so please shout out if you need assistance with anything

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by samccann** [comment]
Hi @GSergeevich !  Sorry it has taken us so long to get to this PR. Given the prior comment, I'm closing this out. Please consider applying this fix to the new repo if it is still a problem.

Thanks again for helping out with Ansible documentation!

**Pull request closed without merging**
