### PR TITLE
win_webpicmd: Clean up parameter handling

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_webpicmd

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Changes include:
- Use of Get-AnsibleParam and parameter types
- Replace $result PSObject with normal hash

### CODE REVIEW

**Review by petemounce — APPROVED** [review]
LGTM shipit

**Comment by dagwieers** [comment]
ready_for_review

**Comment by dagwieers** [comment]
bot_status

**Comment by petemounce** [comment]
shipit

**Comment by schwartzmx** [comment]
shipit

**Comment by jhawkesworth** [comment]
Since there are shipits from the module maintainer and schwartzmx I'm just going to merge this.

**Pull request merged**
