### PR TITLE
new openweather_facts module

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

openweather_facts

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

Allows you to know if your server will need a umbrella

### CODE REVIEW

**Comment by nerzhul** [comment]
OWM requires an API key and i didn't see it there, can you add a parameter ?

**Comment by jhawkesworth** [comment]
Doh.  Not working for me.  What am I missing?  Am running from WSL (windows impersonating Ubuntu)  python 2.7.6

```
jon@TENSY:~/ansible-dev$ ansible localhost -m openweather_facts -a "id=524901 units=metric" -vvv
No config file found; using defaults
META: ran handlers
Using module file /home/jon/ansible-dev/lib/ansible/modules/monitoring/openweather_facts.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jon
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jon/.ansible/tmp/ansible-tmp-1486230596.29-26173755836402 `" && echo ansible-tmp-1486230596.29-26173755836402="` echo /home/jon/.ansible/tmp/ansible-tmp-1486230596.29-26173755836402 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpNsJqwg TO /home/jon/.ansible/tmp/ansible-tmp-1486230596.29-26173755836402/openweather_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jon/.ansible/tmp/ansible-tmp-1486230596.29-26173755836402/ /home/jon/.ansible/tmp/ansible-tmp-1486230596.29-26173755836402/openweather_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/jon/.ansible/tmp/ansible-tmp-1486230596.29-26173755836402/openweather_facts.py; rm -rf "/home/jon/.ansible/tmp/ansible-tmp-1486230596.29-26173755836402/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_fRlx9b/ansible_module_openweather_facts.py", line 179, in <module>
    main()
  File "/tmp/ansible_fRlx9b/ansible_module_openweather_facts.py", line 170, in main
    module.fail_json("Failed to get the weather: %s" % info['msg'])
TypeError: fail_json() takes exactly 1 argument (2 given)

localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "openweather_facts"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_fRlx9b/ansible_module_openweather_facts.py\", line 179, in <module>\n    main()\n  File \"/tmp/ansible_fRlx9b/ansible_module_openweather_facts.py\", line 170, in main\n    module.fail_json(\"Failed to get the weather: %s\" % info['msg'])\nTypeError: fail_json() takes exactly 1 argument (2 given)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

**Comment by bcoca** [comment]
he, module is soo old they did not require key when i created it ....

**Comment by jhawkesworth** [comment]
Oh well, I will have to find another way for my ansible-powered Jarvis prototype tell me what kind of hat to pack for my next trip to AnsibleFest now :-)

**Pull request closed without merging**
