### PR TITLE
Added config option to control default of asking or not for sudo passwor...

### PR DESCRIPTION
**Pull request by bcoca**
just simple global config for those that don't want to remember  -K

I removed the per play implementation, as what you want for that seems a bigger rework than what I attempted.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Looks reasonable.

needs to be commented out in the example config file too, so people know the option is there.

**Comment by bcoca** [comment]
will do and resubmit

On Wed, Oct 31, 2012 at 5:44 PM, Michael DeHaan notifications@github.comwrote:

> Looks reasonable.
> 
> needs to be commented out in the example config file too, so people know
> the option is there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/1495#issuecomment-9963290.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001

**Comment by mpdehaan** [comment]
typo to fix:  "enviornment" :)

**Comment by bcoca** [comment]
ispellz horrizblesy

will resubmit

On Thu, Nov 1, 2012 at 7:37 PM, Michael DeHaan notifications@github.comwrote:

> typo to fix: "enviornment" :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/pull/1495#issuecomment-10000152.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001

**Comment by mpdehaan** [comment]
thansk ewe!

**Comment by mpdehaan** [comment]
merged, thx

**Pull request closed without merging**
