### PR TITLE
Refactor iam_role to bring down the complexity score

### PR DESCRIPTION
**Pull request by tremble**
##### SUMMARY
Refactor iam_role to bring down the complexity score

Related to #64623 which will introduce a sanity test using pylint "--max-complexity 20"

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
iam_role

##### ADDITIONAL INFORMATION
Not added a changelog since this shouldn't result in any user-facing changes.

Note: iam_role integration test is 'unsupported' so needs to be manually run locally

### CODE REVIEW

**Review by jillr — COMMENTED** [review]
First pass looks good, tests pass, I would like to give this a second pass before merging though as I went through this over a couple of broken up sessions.

**Review by s-hertel — DISMISSED** [review]
Is compare_attached_role_policies used by anything?

The refactor looks like a big improvement to me.

**Comment by tremble** [comment]
@s-hertel compare_attached_role_policies is used in update_role_assumed_policy

**Comment by s-hertel** [comment]
@tremble I only see compare_assume_role_policy_doc used. It looks like compare_attached_role_policies became dead code after https://github.com/ansible/ansible/pull/22936/files.

**Review by jillr — APPROVED** [review]
LGTM - thanks @tremble!

**Pull request merged**
