### PR TITLE
Fix test case failure for Azure ACS module

### PR DESCRIPTION
**Pull request by ZhijunZhao**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

azure_rm_acs

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/zhijzhao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### ADDITIONAL INFORMATION

```

```

@yuwzho @zikalino @yaweiw

### CODE REVIEW

**Comment by yuwzho** [comment]
shipit

**Comment by ZhijunZhao** [comment]
ready_for_review

**Comment by zikalino** [comment]
shipit

**Comment by ZhijunZhao** [comment]
@nitzmahone

**Review by nitzmahone — APPROVED** [review]

**Pull request merged**
