### PR TITLE
acme_certificate: minimize needed information for stage 2

### LINKED ISSUE #37884: Letsencrypt: Not creating certificates
#### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY
The letsencrypt module in 2.5 only creates empty certificate files when renewing a certificate. This works fine in 2.4.3.

##### STEPS TO REPRODUCE
With Ansible version 2.5, run the below playbook to renew a Letsencrypt certificate with dns-01 challenge.

```yaml
- hosts: 127.0.0.1
  tasks:
    - name: Renew LetsEncrypt certificates
      letsencrypt:
        account_key: /letsencrypt/letsencrypt-account.key
        csr: /letsencrypt/{{ item }}.csr
        dest: "/etc/ssl/{{ item }}.crt"
        acme_directory: https://acme-v01.api.letsencrypt.org/directory
      with_items: "{{ ssl_certs }}"
  vars:
      ssl_certs:
        - www.example.com
```

##### EXPECTED RESULTS
`/etc/ssl/www.example.com.crt` is created with as a valid certificate

Verbose results from 2.4.3.0:
```
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/web_infrastructure/letsencrypt.py
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1521935449.41-132763795794153 `" && echo ansible-tmp-1521935449.41-132763795794153="` echo /home/user/.ansible/tmp/ansible-tmp-1521935449.41-132763795794153 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpLXd6we TO /home/user/.ansible/tmp/ansible-tmp-1521935449.41-132763795794153/letsencrypt.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1521935449.41-132763795794153/ /home/user/.ansible/tmp/ansible-tmp-1521935449.41-132763795794153/letsencrypt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1521935449.41-132763795794153/letsencrypt.py; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1521935449.41-132763795794153/" > /dev/null 2>&1 && sleep 0'
changed: [127.0.0.1] => (item=www.example.com) => {
    "authorizations": [
        {
            "challenges": [
                {
                    "status": "pending", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "http-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz"
                }, 
                {
                    "keyAuthorization": "abcdefghijklmnopqrstuvwxyz", 
                    "status": "valid", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "dns-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz", 
                    "validationRecord": [
                        {
                            "hostname": "www.example.com"
                        }
                    ]
                }
            ], 
            "combinations": [
                [
                    1
                ], 
                [
                    0
                ]
            ], 
            "expires": "2018-04-11T01:26:27Z", 
            "identifier": {
                "type": "dns", 
                "value": "www.example.com"
            }, 
            "status": "valid", 
            "uri": "https://acme-v01.api.letsencrypt.org/acme/authz/abcdefghijklmnopqrstuvwxyz"
        }, 
        {
            "challenges": [
                {
                    "keyAuthorization": "abcdefghijklmnopqrstuvwxyz", 
                    "status": "valid", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "dns-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz", 
                    "validationRecord": [
                        {
                            "hostname": "example.com"
                        }
                    ]
                }, 
                {
                    "status": "pending", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "http-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz"
                }
            ], 
            "combinations": [
                [
                    0
                ], 
                [
                    1
                ]
            ], 
            "expires": "2018-04-11T01:26:31Z", 
            "identifier": {
                "type": "dns", 
                "value": "example.com"
            }, 
            "status": "valid", 
            "uri": "https://acme-v01.api.letsencrypt.org/acme/authz/abcdefghijklmnopqrstuvwxyz"
        }
    ], 
    "cert_days": 89, 
    "challenge_data": {
        "example.com": {
            "dns-01": {
                "resource": "_acme-challenge", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }, 
            "http-01": {
                "resource": ".well-known/acme-challenge/abcdefghijklmnopqrstuvwxyz", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }
        }, 
        "www.example.com": {
            "dns-01": {
                "resource": "_acme-challenge", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }, 
            "http-01": {
                "resource": ".well-known/acme-challenge/abcdefghijklmnopqrstuvwxyz", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }
        }
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "account_email": null, 
            "account_key": "/letsencrypt/letsencrypt-account.key", 
            "acme_directory": "https://acme-v01.api.letsencrypt.org/directory", 
            "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf", 
            "challenge": "http-01", 
            "csr": "/letsencrypt/www.example.com.csr", 
            "data": null, 
            "dest": "/etc/ssl/www.example.com.crt", 
            "remaining_days": 10
        }
    }, 
    "item": "www.example.com"
}

```

##### ACTUAL RESULTS
`/etc/ssl/www.example.com.crt` not created

Verbose results from 2.5
```
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/web_infrastructure/letsencrypt.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1521934672.46-231150476528896 `" && echo ansible-tmp-1521934672.46-231150476528896="` echo /home/user/.ansible/tmp/ansible-tmp-1521934672.46-231150476528896 `" ) && sleep 0'
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-9443jIZoQC/tmpnTgh6s TO /home/user/.ansible/tmp/ansible-tmp-1521934672.46-231150476528896/letsencrypt.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1521934672.46-231150476528896/ /home/user/.ansible/tmp/ansible-tmp-1521934672.46-231150476528896/letsencrypt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1521934672.46-231150476528896/letsencrypt.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1521934672.46-231150476528896/ > /dev/null 2>&1 && sleep 0'
changed: [127.0.0.1] => (item=www.example.com) => {
    "account_uri": "https://acme-v01.api.letsencrypt.org/acme/reg/30973482", 
    "authorizations": {
        "www.example.com": {
            "challenges": [
                {
                    "keyAuthorization": "abcdefghijklmnopqrstuvwxyz", 
                    "status": "valid", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "dns-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz", 
                    "validationRecord": [
                        {
                            "hostname": "www.example.com"
                        }
                    ]
                }, 
                {
                    "status": "pending", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "http-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz"
                }
            ], 
            "combinations": [
                [
                    1
                ], 
                [
                    0
                ]
            ], 
            "expires": "2018-04-23T16:02:57Z", 
            "identifier": {
                "type": "dns", 
                "value": "www.example.com"
            }, 
            "status": "valid", 
            "uri": "https://acme-v01.api.letsencrypt.org/acme/authz/abcdefghijklmnopqrstuvwxyz"
        }, 
        "example": {
            "challenges": [
                {
                    "keyAuthorization": "abcdefghijklmnopqrstuvwxyz", 
                    "status": "valid", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "dns-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz", 
                    "validationRecord": [
                        {
                            "hostname": "example.com"
                        }
                    ]
                }, 
                {
                    "status": "pending", 
                    "token": "abcdefghijklmnopqrstuvwxyz", 
                    "type": "http-01", 
                    "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz"
                }
            ], 
            "combinations": [
                [
                    1
                ], 
                [
                    0
                ]
            ], 
            "expires": "2018-04-11T03:03:41Z", 
            "identifier": {
                "type": "dns", 
                "value": "example.com"
            }, 
            "status": "valid", 
            "uri": "https://acme-v01.api.letsencrypt.org/acme/authz/abcdefghijklmnopqrstuvwxyz"
        }
    }, 
    "cert_days": -1, 
    "challenge_data": {
        "www.example.com": {
            "dns-01": {
                "record": "_acme-challenge.www.example.com", 
                "resource": "_acme-challenge", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }, 
            "http-01": {
                "resource": ".well-known/acme-challenge/abcdefghijklmnopqrstuvwxyz", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }
        }, 
        "example.com": {
            "dns-01": {
                "record": "_acme-challenge.example.com", 
                "resource": "_acme-challenge", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }, 
            "http-01": {
                "resource": ".well-known/acme-challenge/abcdefghijklmnopqrstuvwxyz", 
                "resource_value": "abcdefghijklmnopqrstuvwxyz"
            }
        }
    }, 
    "challenge_data_dns": {}, 
    "changed": true, 
    "finalize_uri": null, 
    "invocation": {
        "module_args": {
            "account_email": null, 
            "account_key": "/letsencrypt/letsencrypt-account.key", 
            "account_key_content": null, 
            "account_key_src": "/letsencrypt/letsencrypt-account.key", 
            "acme_directory": "https://acme-v01.api.letsencrypt.org/directory", 
            "acme_version": 1, 
            "agreement": null, 
            "chain_dest": null, 
            "challenge": "http-01", 
            "csr": "/letsencrypt/www.example.com.csr", 
            "data": null, 
            "dest": "/etc/ssl/www.example.com.crt", 
            "fullchain_dest": null, 
            "remaining_days": 10, 
            "terms_agreed": false, 
            "validate_certs": true
        }
    }, 
    "item": "www.example.com", 
    "order_uri": null
}
```

_Data scrubbed for security_

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Minimizes the needed information for stage 2 of `acme_certificate`. Fixes #37884.

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
acme_certificate

##### ANSIBLE VERSION
```
2.7.0
```

##### ADDITIONAL INFORMATION
For ACME v2, the module only needs to know the order URI to finish stage 2. All authorization information and the finalization URI can be fetched from the order URI. (Also, if the order URI goes 404, we know that something is fishy anyway.)

For ACME v1, the module can get the authorizations by checking the CSR and asking for new authzs for all domains listed as SANs. If the previous run (stage 1) wasn't too long ago, the same authzs will be provided and everything works fine. If they expired, well, bad luck :-)

With these changes, the module will continue to work in all cases where it worked before (I think), and might even start working (at least for ACME v1) in situations where it didn't work before.

CC @apple4ever

### CODE REVIEW

**Comment by felixfontein** [comment]
(I've successfully tested this against Pebble / https://github.com/felixfontein/ansible-acme-test/, and both Let's Encrypt staging endpoints.)

**Review by resmo — APPROVED** [review]

**Comment by resmo** [comment]
@felixfontein ping me if ready to merge (I assume we wait for some feedback from @apple4ever)

**Comment by felixfontein** [comment]
@resmo it should be done; I was mainly CC'ing him so that he knows it is implemented :)

**Comment by resmo** [comment]
got that.

shipit

**Comment by felixfontein** [comment]
@resmo thanks for reviewing and merging!

**Comment by resmo** [comment]
thank you for your works!

**Comment by apple4ever** [comment]
Thanks @felixfontein! This looks great!

**Pull request merged**
