### PR TITLE
Convert to reduced list of known types

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
As a result of https://github.com/ansible/ansible/pull/49966#pullrequestreview-185350749 I looked into what we accept as return types and it seems we accept:
- both 'int' as well as 'integer',
- 'bool' as well as 'boolean'
- 'str' as well as 'string'.
- 'dict' as well as 'dictionary'

We don't allow this for the parameter types in the arg_spec. So I think it's better to align what we accept in both cases.

PS Some modules pretend that the type is a free form text and we don't change that for these exceptions.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
module docs

### CODE REVIEW

**Comment by dagwieers** [comment]
cc @felixfontein

**Comment by dagwieers** [comment]
@gundalow @pabelanger Can we avoid getting messages from @openstack-zuul unless maybe there is a failure ? We want to get the number of notifications/mails down, not up.

**Comment by pabelanger** [comment]
Yes, that is possible a pipeline update to zuul.o.o would fix this, however I would caution only commenting on failure leaves the possibility for no knowing if zuul is actually working or not. Since, we'd never know a failed just broken, if zuul was down for example.

There is already a pretty aggressive file matcher, to only comment when specific files are changed.

**Comment by dagwieers** [comment]
Doesn't the CI overview below give you pretty much the needed information already ?

> ✔ **openstack/third-party-check** — third-party-check status: success 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 󠀠 [Details](https://zuul.openstack.org/)

**Comment by pabelanger** [comment]
It does, but you can see it currently doesn't provider the URL for logs. Today we do that with a comment due to limitation on zuul side with github checks API.

We can propose an update to openstack-zuul and only comment on failure, do we want to bring it up at week meeting to confirm everybody is onboard with the change.

**Comment by dagwieers** [comment]
@pabelanger I understand. If there's an expectation we can fix this in the short term, I wouldn't bother spending any more time on this. However if we have no outlook on when this integration could be fixed, I would discuss this in the Contributor Experience WG, or discuss with @gundalow beforehand? We have to find a good balance.

**Comment by acozine** [comment]
Wow, this is a lot of changes!

When we publish the module docs, do we translate `str` into `string` and `bool` into `boolean`? I think new users will have an easier time with `string` and `boolean` rather than `str` and `bool`. I suspect the full words will be easier to translate (into foreign languages like Japanese) as well - not sure if we need them in the source or just in the output for translation purposes.

**Comment by felixfontein** [comment]
@acozine We don't translate that yet, but #49966 does that (the `documented_type` filter it introduces does the translation).

Anyway, I would prefer the short versions (inside the module files), since they are exactly what is used all over the codebase (in particular in `argument_spec`).

**Comment by dagwieers** [comment]
Yes, exactly, so at the moment we use the python types (str, bool, int) for the arg_spec. At some point when we introduced the documentation of return values, people have been doing both the python types (str, bool, int) as well as the names (string, boolean, integer) as it was not enforced (like it was for the arg_spec). And this basically cleans up the ambiguity of the python types vs the type names.

I don't see a point of doing it differently in the argspec vs the return values. And I don't want to introduce a different standard for the return values than what we already enforced for the return values.

(For completeness, when we enforced the return value types, we had both python and named types, so we accepted both, but I think that's worse)

We translate the type into a type name in another PR so users are not exposed to the internals (as they were before these changes).

**Pull request merged**
