### PR TITLE
Fix network resource module wording and typographical errors (#61613)

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY

Backport #61613 documentation updates

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

eos_interfaces

##### ADDITIONAL INFORMATION

```paste below

```
This is documentation updates related to our new reource modules for network.

Depends-On: https://github.com/ansible/ansible/pull/61711
Depends-On: https://github.com/ansible/ansible/pull/61883
Depends-On: https://github.com/ansible/ansible/pull/61899

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by samccann** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
I've updated depends-on to pull in eos fixes

**Comment by pabelanger** [comment]
Another new failure, I've created https://github.com/ansible/ansible/issues/61909 to help track

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
