### PR TITLE
[WIP] Enable changed var with ufw check mode

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This is essentially a copy of #49948 so I can play around with the tests on real CI :-)

This should NEVER be merged!

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ufw

### CODE REVIEW

**Comment by felixfontein** [comment]
@jbarotin my standard way to debug such stuff is add additional output; in this case, it's interesting to see what the commands executed by the task with the wrong results output; I've added that in a5bd60e3ac67258bc6dcbe869b1bc713742e65e5

Let's see how the result looks like :-)

**Comment by felixfontein** [comment]
The problem seems to be that `grep` doesn't find any of the files:
```
03:40     "stderr_lines": [
03:40         "/bin/grep: /lib/ufw/user.rules: No such file or directory", 
03:40         "/bin/grep: /lib/ufw/user6.rules: No such file or directory", 
03:40         "/bin/grep: /etc/ufw/user.rules: No such file or directory", 
03:40         "/bin/grep: /etc/ufw/user6.rules: No such file or directory"
03:40     ], 
```
Because of that, check mode obviously won't work.

Next try: run `ufw -f reset`, which on my machine prints the paths where the configs are:
```
# ufw -f reset
Backing up 'user.rules' to '/etc/ufw/user.rules.20190113_220819'
Backing up 'before.rules' to '/etc/ufw/before.rules.20190113_220819'
Backing up 'after.rules' to '/etc/ufw/after.rules.20190113_220819'
Backing up 'user6.rules' to '/etc/ufw/user6.rules.20190113_220819'
Backing up 'before6.rules' to '/etc/ufw/before6.rules.20190113_220819'
Backing up 'after6.rules' to '/etc/ufw/after6.rules.20190113_220819'
```

**Comment by felixfontein** [comment]
Here, it's in `/var/lib/ufw`...
```
03:41         "Backing up 'user.rules' to '/var/lib/ufw/user.rules.20190113_211410'", 
03:41         "Backing up 'after6.rules' to '/etc/ufw/after6.rules.20190113_211410'", 
03:41         "Backing up 'user6.rules' to '/var/lib/ufw/user6.rules.20190113_211410'", 
03:41         "Backing up 'before6.rules' to '/etc/ufw/before6.rules.20190113_211410'", 
03:41         "Backing up 'after.rules' to '/etc/ufw/after.rules.20190113_211410'", 
03:41         "Backing up 'before.rules' to '/etc/ufw/before.rules.20190113_211410'", 
```

**Comment by jbarotin** [comment]
Ok I'll add /var/lib/ufw as well

**Comment by felixfontein** [comment]
That doesn't seem to be enough.

**Comment by felixfontein** [comment]
(Besides the unit test failures.)

**Comment by jbarotin** [comment]
Yep, I forgot executing them... it should be ok for the next step now.

**Comment by felixfontein** [comment]
Hmm, looks like `ufw --dry-run delete allow from any to 0.0.0.0 port 23` does not output the IPv6 rules for ufw?

Anyway, I managed to reproduce it. I added
```
- command: ufw allow in 22/tcp
- command: ufw allow in from 224.0.0.251 port 5353 proto udp
- command: ufw allow in from ff02::fb port 5353 proto udp
```
at the top to reproduce the conditions on the test VM, now it also fails for me at the same point.

**Comment by felixfontein** [comment]
Maybe we have to detect whether the rule affects IPv4, IPv6 or both, and grep only the affected protocol rule files to compare to the output of `ufw --dry-run`.

**Comment by jbarotin** [comment]
Yep, we can try to find  `::` in order to detect ipv6

**Comment by felixfontein** [comment]
An IPv6 address doesn't necessarily has `::` in it. It's probably better to use a proper regex for IPv4 and IPv6 addresses (with or without netmask).

**Pull request closed without merging**
