### PR TITLE
Optimise string handling in ansible.utils._clean_data

### PR DESCRIPTION
**Pull request by leth**
As discussed in #8511, [here is the benchmarking info](https://gist.github.com/leth/1f2ba2d6b961fabe5d60).

### CODE REVIEW

**Comment by jimi-c** [comment]
So part of the problem with cStringIO is that it does not handle unicode. If you run the unicode integration test with this patch `(cd test/integration; make unicode)`, you'll see it fail. I believe using io.StringIO() is just as quick, though running your benchmark it doesn't seem to matter much which library you use, the _regex method is quicker leading me to suspect that the underlying buffer is not that important. For example, just replacing cStringIO with StringIO again in your _regex method gives the following benchmark results:

<pre>
length: 2000 density: 0.0
regex   none      0.03549504
orig cs none      1.33576512
orig    none      4.06493807
regex   inventory 0.03513479
orig cs inventory 1.32415199
orig    inventory 4.05717015
regex   both      0.03523111
orig cs both      1.32435417
orig    both      4.04388309
regex   remote    0.03511596
orig cs remote    1.32523990
orig    remote    4.04796195
</pre>

This is slightly slower than cStringIO, but is still much faster than the other methods.

You have at least one typo in the code:

<pre>
-    regex = PRINT_CODE_REGEX if replace_prints else ONLY_CODE_REGEX
+    regex = PRINT_CODE_REGEX if replace_prints else CODE_REGEX
</pre>

which just looks like a cut/paste error from your benchmark code.

**Comment by leth** [comment]
Thanks; sorry about that.

Fortunately swapping back to normal stringio doesn't have much of a performance impact:

```
length: 2000 density: 0.0
regex cs     none      0.02231717
regex non-cs none      0.02372718
regex cs     inventory 0.02257013
regex non-cs inventory 0.02402496
regex cs     both      0.02252388
regex non-cs both      0.02398491
regex cs     remote    0.02258110
regex non-cs remote    0.02402186

length: 20000 density: 0.0
regex cs     none      0.20524287
regex non-cs none      0.20422101
regex cs     inventory 0.20501399
regex non-cs inventory 0.20466089
regex cs     both      0.20503783
regex non-cs both      0.20483708
regex cs     remote    0.21779609
regex non-cs remote    0.21423101
```

I'll update the PR appropriately

**Comment by mpdehaan** [comment]
In your previous comment: 

"Our jenkins server has hung on this step for hours. I've not waited that long locally."

I'm wondering if Jenkins was just waiting for a password and needed to be fed one, or a task went interactive.  Or otherwise, what might be unique about your playbooks to cause trouble here.

**Comment by leth** [comment]
I remember checking once and ansible had no subprocesses and was using 100% CPU.

**Comment by jimi-c** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
