### PR TITLE
Integration tests for notify with variable list.

### PR DESCRIPTION
**Pull request by lberruti**
##### SUMMARY
  make test_notify -C test/integration

It checks notifications with scalar and dict variables.
It tests the notification resolution use the correct priority on resolution of the variables.

##### ISSUE TYPE
Feature Pull Request

##### COMPONENT NAME
test/integration/Makefile
test/integration/inventory.notify
test/integration/roles/test_notify/defaults/main.yml
test/integration/roles/test_notify/handlers/main.yml
test/integration/roles/test_notify/tasks/main.yml
test/integration/test_notify.yml
test/integration/vars/test_notify_vars.yml

##### ANSIBLE VERSION
2.3

### CODE REVIEW

**Comment by bcoca** [comment]
instead of `command: echo`, which doesn't really display anything can we change the handlers to debug statements?

**Comment by lberruti** [comment]
@bcoca, I changed as requested

The last test reveals a possible issue:

```
PLAY: run notify with role default vars *****************************************

TASK [test_notify : test_notify : debug var=handlers_list] **********************
ok: [C] => {
    "handlers_list": "notify_host_c",
    "changed": false
}
ok: [D] => {
    "handlers_list": [
        "default_foo"
    ],
    "changed": false
}
ok: [E] => {
    "handlers_list": [
        "default_foo"
    ],
    "changed": false
}

TASK [test_notify : test_notify : notify with role default vars] ****************
changed: [C] => {"changed": true, "end": "2015-07-07 13:54:20.255547", "stdout": "", "cmd": ["echo"], "start": "2015-07-07 13:54:20.250443", "delta": "0:00:00.005104", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "echo"}}, "stdout_lines": [], "warnings": []}
changed: [D] => {"changed": true, "end": "2015-07-07 13:54:20.290841", "stdout": "", "cmd": ["echo"], "start": "2015-07-07 13:54:20.287289", "delta": "0:00:00.003552", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "echo"}}, "stdout_lines": [], "warnings": []}
changed: [E] => {"changed": true, "end": "2015-07-07 13:54:20.252534", "stdout": "", "cmd": ["echo"], "start": "2015-07-07 13:54:20.247272", "delta": "0:00:00.005262", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "echo"}}, "stdout_lines": [], "warnings": []}

RUNNING HANDLER [test_notify : default_foo] *************************************
ok: [D] => {"changed": false, "ansible_facts": {"called_handler": "default_foo"}}
ok: [E] => {"changed": false, "ansible_facts": {"called_handler": "default_foo"}}

TASK [assert that=called_handler is defined] ************************************
fatal: [C]: FAILED! => {"failed": true, "changed": false, "assertion": "called_handler is defined", "evaluated_to": false}
ok: [D] => {"msg": "all assertions passed", "changed": false}
ok: [E] => {"msg": "all assertions passed", "changed": false}
```

**Comment by samdoran** [comment]
@lberruti: Can you and @mattclay talk and see if these tests are still valid since our testing has changed quite a bit?

needs_info

**Comment by mattclay** [comment]
@lberruti Can you take a look at the existing handlers tests to see if there is anything from your PR that should be added there?

https://github.com/ansible/ansible/tree/devel/test/integration/targets/handlers/

**Comment by mattclay** [comment]
@lberruti Are you interested in updating this PR?

**Comment by lberruti** [comment]
@mattclay This PR was added in order to coverage templating on handlers, i.e.
```
...
vars:
  handlers_list:
    - A
    - B
tasks:
  - command: echo
     notify: '{{handlers_list}}'
...
```
It checks handlers templating made via host_vars, "play vars", "included vars" and "role default vars"

It seems to me that there are none of those tests inside https://github.com/ansible/ansible/tree/devel/test/integration/targets/handlers/

**Comment by s-hertel** [comment]
@lberruti Some other templating tests were added to the handlers target in ec1287ca7e2bda3c4f609c03c3824df5d6c089e2. Since there weren't any for list variables I opened #66423 and added you as a co-author since I don't have permission to push to your remote to update this pull request instead:
```
To github.com:lberruti/ansible.git
 ! [remote rejected]       update_pr/11501 -> test_notify (permission denied)
error: failed to push some refs to 'git@github.com:lberruti/ansible.git'
```

**Pull request closed without merging**
