### PR TITLE
digital ocean module:  Fail if given an unknown state

### PR DESCRIPTION
**Pull request by zupo**
I just lost hours debugging what the hell is going wrong with this module. In the end I found that I mis-spelled the state: "preset" instead of "present". The code just skipped everything, no return, no error report. 

It should fail if given an invalid state.

### CODE REVIEW

**Comment by mpdehaan** [comment]
We generally like to have things 2.4 compliant, can you replace the "format" with the "classic %s"?

**Comment by mpdehaan** [comment]
So the module has a facility for describing valid choices for the state.  This is the best way to assert the states are required.  Let me look at this really quick.

**Comment by mpdehaan** [comment]
Ok I'm a bit confused by this one, see this line in the module:

```
        state = dict(choices=['active', 'present', 'absent', 'deleted'], default='present'),
```

May I ask what version of ansible you might be using?

If it's recent, I'd like to see the line from your playbook with the mispelling so I can see what's up.

**Comment by zupo** [comment]
Sorry, semi-incorrect bug report: the culprit was that my state was "active", which is listed as a valid state, but it does have a case for it in the if-elif tree in the module.

So if state is present or absent, there is code that is ran. If your state is active or deleted, the if-elif does not have a case for it, and nothing is ran.

**Comment by mpdehaan** [comment]
Ok so sometimes the states are invalid choices then, I believe that's what you are saying.

Perhaps the message shouldn't be "unknown state" but instead describe what the valid states are in those cases?

**Comment by zupo** [comment]
Or, even better, remove 'active' and 'deleted' from the choices list.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you still would like this pull request merged, we will need your help making this target the new repo.  If you do not take any action, this
pull request unfortunately cannot be applied.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- Note that python modules in ansible now also end in ".py" and this extension is required for new contributions.
- action_plugins (modules with server side components) still live in the main repo.  If your pull request touches both, which should be
   exceedingly rare, submit two new pull requests and make sure to mention the links to each other in the comments.

Otherwise, if this is a new module:
- Submit your pull request to add a module to https://github.com/ansible/ansible-modules-extras

It may be possible to re-patriate your pull requests automatically, one user-submitted approach for advanced git users
has been suggested at https://gist.github.com/willthames/afbaaab0c9681ed45619

Additionally, should you need more help with this, you can ask questions on:
- the development mailing list: https://groups.google.com/forum/#!forum/ansible-devel

Thanks you very much!

**Pull request closed without merging**
