### PR TITLE
setup.py: Sorts CLI entrypoints

### PR DESCRIPTION
**Pull request by funkyfuture**
##### SUMMARY

when i saw that almost coherently sorted list, i became compulsive.

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by webknjaz** [comment]
This change doesn't seem to make the list sorted, still. Also, it's not a bug to fix so the type is incorrect. Anyway... I think we'll be able to migrate to using declarative packaging configs soon'ish so I don't see the point of updating a dynamic packaging config as it doesn't gain us anything.

-0 from me.

**Comment by funkyfuture** [comment]
where isn't it sorted?

sure, declarative package configs are preferable, but their contents should also be sorted.

**Comment by webknjaz** [comment]
> where isn't it sorted?

Well, you added “scripts” between “config” and “console”. I'm sure that doesn't count as sorted.

**Comment by funkyfuture** [comment]
indeed there are several ways to sort. i simply sorted by key.

**Comment by webknjaz** [comment]
Exactly. Hence, it's not “broken”. If everybody starts re-sorting such things all the time, the Git tree will be polluted with pointless commits with no reasonable justification just because people are in different moods. Which is why I said above that this does not really improve anything for the project, in general. I'm sure, there are other places in the project that aren't sorted as you like. But if we were to adopt a specific way of sorting over the others, we'd need some linting mechanism for consistency across the entire codebase. Though, to me, it's just busy work with no visible/measurable benefits.

**Pull request closed without merging**
