### PR TITLE
os_user: update password only when needed

### LINKED ISSUE #23570: os_user not idemponent
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os_user

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/student/openstack/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

CetnOS 7 (latest)

##### SUMMARY

When os_user module is used, it works correctly, but reports every time state "changed" for users even though they exist.

##### STEPS TO REPRODUCE

Run os_user module repeatedly on same users.

```yaml
- name: "Create OpenStack users"
  os_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    domain: "{{ item.domain }}"
    state: present
    enabled: yes
  with_items: "{{ os_user_list }}"
  environment:
    "{{ os_auth_env }}"
```

##### EXPECTED RESULTS

Users created, but not repeatedly marked as "changed" regardless of users are to be created/modified.
##### ACTUAL RESULTS

Task is executed, but marked as "changed" regardless of users are to be created/modified.

```
TASK [openstack-controller : Create OpenStack users] *****************************************************************************************************************************************
task path: /home/student/openstack/roles/openstack-controller/tasks/proj-role-user.yml:13
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/openstack/os_user.py
<os.controller> ESTABLISH SSH CONNECTION FOR USER: root
<os.controller> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/adb310a101 os.controller '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<os.controller> (0, '/root\n', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<os.controller> ESTABLISH SSH CONNECTION FOR USER: root
<os.controller> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/adb310a101 os.controller '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427 `" && echo ansible-tmp-1492090150.42-90879899317427="` echo /root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427 `" ) && sleep 0'"'"''
<os.controller> (0, 'ansible-tmp-1492090150.42-90879899317427=/root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427\n', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<os.controller> PUT /tmp/tmpC4hq0W TO /root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427/os_user.py
<os.controller> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/adb310a101 '[os.controller]'
<os.controller> (0, 'sftp> put /tmp/tmpC4hq0W /root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427/os_user.py\n', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 6 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /root size 0\r\ndebug3: Looking up /tmp/tmpC4hq0W\r\ndebug3: Sent message fd 6 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427/os_user.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:28118\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 28118 bytes at 32768\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<os.controller> ESTABLISH SSH CONNECTION FOR USER: root
<os.controller> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/adb310a101 os.controller '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427/ /root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427/os_user.py && sleep 0'"'"''
<os.controller> (0, '', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<os.controller> ESTABLISH SSH CONNECTION FOR USER: root
<os.controller> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/adb310a101 -tt os.controller '/bin/sh -c '"'"'OS_AUTH_URL=http://controller:35357/v3 OS_USERNAME=admin OS_PROJECT_DOMAIN_NAME=Default OS_IDENTITY_API_VERSION=3 OS_PROJECT_NAME=admin OS_PASSWORD=OpenStack123 OS_USER_DOMAIN_NAME=Default /usr/bin/python /root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427/os_user.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1492090150.42-90879899317427/" > /dev/null 2>&1 && sleep 0'"'"''
<os.controller> (0, '\r\n{"invocation": {"module_args": {"auth_type": null, "domain": "default", "cert": null, "region_name": null, "availability_zone": null, "verify": null, "update_password": "always", "api_timeout": null, "enabled": true, "default_project": null, "auth": null, "name": "demo", "state": "present", "endpoint_type": "public", "timeout": 180, "key": null, "cacert": null, "email": null, "cloud": null, "wait": true}}, "changed": true, "user": {"username": null, "description": null, "domain_id": "default", "enabled": true, "id": "4ba0470877f8490a802dfd032f7cea18", "default_project_id": null, "email": null, "name": "demo"}}\r\n', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1469\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to os.controller closed.\r\n')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/openstack/os_user.py
<os.controller> ESTABLISH SSH CONNECTION FOR USER: root
<os.controller> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/student/.ansible/cp/adb310a101 os.controller '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
changed: [os.controller] => (item={u'username': u'demo', u'project': u'demo', u'domain': u'default', u'password': u'User123', u'role': u'user'}) => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "api_timeout": null, 
            "auth": null, 
            "auth_type": null, 
            "availability_zone": null, 
            "cacert": null, 
            "cert": null, 
            "cloud": null, 
            "default_project": null, 
            "domain": "default", 
            "email": null, 
            "enabled": true, 
            "endpoint_type": "public", 
            "key": null, 
            "name": "demo", 
            "region_name": null, 
            "state": "present", 
            "timeout": 180, 
            "update_password": "always", 
            "verify": null, 
            "wait": true
        }
    }, 
    "item": {
        "domain": "default", 
        "password": "User123", 
        "project": "demo", 
        "role": "user", 
        "username": "demo"
    }, 
    "user": {
        "default_project_id": null, 
        "description": null, 
        "domain_id": "default", 
        "email": null, 
        "enabled": true, 
        "id": "4ba0470877f8490a802dfd032f7cea18", 
        "name": "demo", 
        "username": null
    }
}
```

### PR DESCRIPTION
**Pull request by fridim**
idempotency for os_user password.

Fixes #23570

##### SUMMARY

This change adds a <code>_password_needs_update()</code> function that tries to connect with current password to determine if the password needs to be changed. If authentication is successful, then password is not changed.

All the previous checks regarding password that was in <code>_needs_update()</code> are now in <code>_password_needs_update()</code>

To authenticate, keystone needs at least 3 things :
- username
- password
- a project the user has a role in

To not over complicate things, it is decided to use default_project of the user for authentication. 

In case a user has no default_project, a warning will be printed, the previous behavior is kept : password will be updated even if it is the same value.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/modules/cloud/openstack/os_user.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (issue-23549 a585167c23) last updated 2017/04/14 18:22:03 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fridim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fridim/sync/dev/ansible/lib/ansible
  executable location = /home/fridim/sync/dev/ansible/bin/ansible
  python version = 3.6.0 (default, Jan 16 2017, 12:12:55) [GCC 6.3.1 20170109]

```

##### ADDITIONAL INFORMATION

Example Playbook
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    password2: "password2"
  tasks:
    - name: delete users
      os_user:
        name: "{{ item }}"
        state: absent
      with_items:
        - 'dummyuser1'
        - 'dummyuser2'

    - name: Create Project
      os_project:
              name: dummyproject
              enabled: True

    - name: "Create OpenStack user dummyuser1"
      os_user:
        name: "dummyuser1"
        password: "password"
        state: present
        default_project: dummyproject
        enabled: yes

    - name: "Create OpenStack user dummyuser2 (no default project)"
      os_user:
        name: "dummyuser2"
        password: "password"
        state: present
        enabled: yes

    - name: add dummy2 to project dummyproject
      os_user_role:
         user: dummyuser2
         project: dummyproject
         role: _member_

    - name: "update password for user dummyuser1"
      os_user:
        name: "dummyuser1"
        password: "{{ password2 }}"

    - name: "update password for user dummyuser2"
      os_user:
        name: "dummyuser2"
        password: "{{ password2 }}"

    - name: "update password for user dummyuser1 again (No change)"
      os_user:
        name: "dummyuser1"
        password: "{{ password2 }}"

    - name: "update password for user dummyuser2 again (Change because no default project)"
      os_user:
        name: "dummyuser2"
        password: "{{ password2 }}"
```

### CODE REVIEW

**Comment by fridim** [comment]
thanks @clopnis for the troubleshooting  on keystone :)


ready_for_review

**Comment by clopnis** [comment]
👍

**Comment by evrardjp** [comment]
Looks good at first sight. Will test.

**Comment by evrardjp** [comment]
I won't have chance to test it in the next days, if someone can take over the testing that would be great.

**Comment by fridim** [comment]
just rebased from devel to fix conflicts.

**Comment by jctanner** [comment]
cc @emonty @j2sol @juliakreger @rcarrillocruz @shrews @fridim @fridim @Thingee 

Could one of you review this?

**Comment by evrardjp** [comment]
Should we update this? Is this PR dying?

**Comment by fridim** [comment]
hello @evrardjp 

Idk, you said
> Looks good at first sight. Will test.

then,
> evrardjp commented on Apr 19, 2017
> I won't have chance to test it in the next days, if someone can take over the testing that would be great.

no one stepped in. It worked when i tested it, but i don't have the environment anymore.

**Comment by evrardjp** [comment]
ok. It's worth keeping an eye on it, IMO.

**Comment by Shrews** [comment]
I'm failing to see the advantage of this change? Could you please elaborate why this is needed?

**Comment by fridim** [comment]
> I'm failing to see the advantage of this change? Could you please elaborate why this is needed?

@Shrews to follow principle of idempotency. Currently, `os_user` by default forces password update if password is provided. If you run this twice:

```
- name: "update password for user dummyuser1"
      os_user:
        name: "dummyuser1"
        password: "{{ password1 }}"
```

result is 'changed' for both run when it should be 'changed' and 'ok'.
This PR fixes that.

**Comment by fridim** [comment]
@Shrews you can also check out original issue https://github.com/ansible/ansible/issues/23570

**Comment by omgjlk** [comment]
So this is going to attempt a login every run, which will A) decrement API limits and B) flag invalid login attempts (which may lead to account lockout).

I'm not entirely sure what our philosophy here is currently with mapping to how the OpenStack API works, but as I understand it, the API always assumes you want to change the password when you supply one. We could follow that here, or drift from the API. I no longer have much stake in this game though so I'll leave it to others to decide.

**Comment by sshnaidm** [comment]
Thanks for submitting patch for Openstack Ansible modules!
We moved Openstack Ansible modules to Openstack repositories.
Next patches should be submitted not with Ansible Github but with
Openstack Gerrit: https://review.opendev.org/#/q/project:openstack/ansible-collections-openstack
Please submit your code there from now.
Thanks for your contribution and sorry for inconvienience.

**Comment by Akasurde** [comment]
Closing as per above.

**Pull request closed without merging**
