### PR TITLE
Add new module 'opennms_node'

### PR DESCRIPTION
**Pull request by vvanouytsel**
##### SUMMARY

Add a new opennms_node module to manage nodes in OpenNMS monitoring system

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

opennms_node

##### ADDITIONAL INFORMATION

This modules allows the user to add/delete nodes to the OpenNMS server.

### CODE REVIEW

**Comment by lxdicted** [comment]
There are a number of OpenNMS related modules in subdirectory lib/ansible/modules/monitoring/opennms I.e.: https://github.com/ansible/ansible/pull/56548

It would be great if you could move your module under this directory, too.

**Comment by vvanouytsel** [comment]
> There are a number of OpenNMS related modules in subdirectory lib/ansible/modules/monitoring/opennms I.e.: #56548
> 
> It would be great if you could move your module under this directory, too.

I will move it to the lib/ansible/modules/monitoring/opennms  directory

**Comment by vvanouytsel** [comment]
ready_for_review

**Comment by vvanouytsel** [comment]
bot_status

**Comment by Akasurde** [comment]
Hi @vvanouytsel, Thank you very much for your interest in Ansible. This plugin/module is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general<br><br>If you have further questions please stop by IRC or the mailing list:<br><br>* IRC: #ansible on irc.freenode.net<br>* mailing list: https://groups.google.com/forum/#!forum/ansible-project<br><br>needs_info<br>

**Pull request closed without merging**
