### PR TITLE
Add new module win_psscript for installing scripts from PSRepositories

### PR DESCRIPTION
**Pull request by briantist**
##### SUMMARY

Adding new module `win_psscript` as a counterpart to `win_psmodule`.

Most common options and scenarios accounted for, including mix/max/required versions, add/remove and update to latest.

Includes tests.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

win_psscript

##### RELATED PRs:
- #67499
- #67594

### CODE REVIEW

**Review by jhawkesworth — APPROVED** [review]
Looks good to me, although I can't test it for myself at the moment.
Would be nice if the examples pointed at real things that might be of use to ansible users, but it shouldn't stop this module from being merged.

**Comment by briantist** [comment]
Thanks @jhawkesworth , I didn't put real scripts in mostly because the only publicly published script I personally use is one that I published a few weeks ago and it probably wouldn't have wide interest (it's related to JEA). Most of the scripts I use are internal to my company and published in their private repository, so I actually didn't have a whole lot of real-world examples. 

I took a look at the popular scripts in PSGallery and changed 2 of the examples to use real ones that seem like they're relatively safe and might be of interest, but if you know of any that a good fit I'd be happy to replace the existing examples with some that are more useful!

**Comment by jhawkesworth** [comment]
Thanks @briantist  only script I've used from PSG is the AnsibleVault one.  Changes look good to me.

**Comment by briantist** [comment]
> Thanks @briantist only script I've used from PSG is the AnsibleVault one. Changes look good to me.
Oh nice, I took a look at that but it's a module so it would be a good example for `win_psmodule`.

**Comment by jborean93** [comment]
PR has been migrated to https://github.com/ansible-collections/community.windows/pull/12.

**Pull request closed without merging**
