### PR TITLE
mysql modules: fix the module's documentation

### LINKED ISSUE #55917: mysql_user module doesnot work for mariadb version 10.4 and above
##### SUMMARY
When trying to change password for root user ( after default installation) mysql_user module doesn't work for mariadb version 10.4 and above. MAriadb 10.4 and above , doesn't have 127.0.0.1 and ::1 host in the default table which means only localhost is allowed to connect after installation.
Even if you pass "login_host" as localhost  in mysql_user module , it some how internally gets resolved to 127.0.0.1 and hence it is not able to connect.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user module

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/roles']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)

```

##### CONFIGURATION

```
xxxx@xxxxx xxxx]$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANY_ERRORS_FATAL(/etc/ansible/ansible.cfg) = True
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = This file was created by Ansible, do not modify manually.
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible/roles']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/pnlrs346/.ssh/vmadmin
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible/roles']
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Target OS : Red Hat Enterprise Linux Server release 7.6 (Maipo)
3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```
- name: 'Set MariaDB root password for the first time (root@localhost)'
  mysql_user:
    name: 'root'
    password: "{{ mariadb_root_password }}"
    host: 'localhost'
    login_host: 'localhost'
    state: 'present'

```

##### EXPECTED RESULTS
TASK [mariadb : Set MariaDB root password for the first time (root@localhost)] ********************************************************************************************************************************************************************
task path: /home/pnlrs346/nagios_/roles/mariadb/tasks/setdbroot_passwd.yml:28
changed: [XXXXX.ah.eu.aholddelhaize.com] => (item=::1) => {
    "changed": true,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "check_implicit_admin": false,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "localhost",
            "host_all": false,
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": "root",
            "name": "root",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "priv": null,
            "sql_log_bin": true,
            "ssl_ca": null,
            "ssl_cert": null,
            "ssl_key": null,
            "state": "present",
            "update_password": "always",
            "user": "root"
        }
    },
    "item": "::1",
    "user": "root"
}

##### ACTUAL RESULTS

```
TASK [mariadb : Set MariaDB root password for the first time (root@localhost)] ***************************************************************************************************************************************************
task path: /home/pnlrs346/nagios_/roles/mariadb/tasks/setdbroot_passwd.yml:20
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_mysql_user_payload_L7VND6/__main__.py", line 588, in main
    connect_timeout=connect_timeout)
  File "/tmp/ansible_mysql_user_payload_L7VND6/ansible_mysql_user_payload.zip/ansible/module_utils/mysql.py", line 79, in mysql_connect
    db_connection = mysql_driver.connect(**config)
  File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 597, in connect
    self._get_server_information()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 966, in _get_server_information
    packet = self._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)

fatal: [XXXXX.ah.eu.aholddelhaize.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "check_implicit_admin": false,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "localhost",
            "host_all": false,
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "name": "root",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "priv": null,
            "sql_log_bin": true,
            "ssl_ca": null,
            "ssl_cert": null,
            "ssl_key": null,
            "state": "present",
            "update_password": "always",
            "user": "root"
        }
    },
    "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1130, u\"Host '127.0.0.1' is not allowed to connect to this MariaDB server\")"
}



```

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes: https://github.com/ansible/ansible/issues/55917
mysql modules: fix the module's documentation

These changes will be visible in all mysql-module-related doc pages.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
```mysql```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by deefour** [comment]
While this provides information needed to work around #55917, adding some context might be helpful. Specifically, this absolutely affects default installs of [MariaDB 10.4.3+](https://mariadb.com/kb/en/authentication-plugin-unix-socket/): 

> In MariaDB 10.4.3 and later, the unix_socket authentication plugin is installed by default, and it is used by the 'root'@'localhost' user account by default. See Authentication from MariaDB 10.4 for more information.

**Comment by Andersson007** [comment]
@deefour thanks! i added an example. Hope it'll help.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @Andersson007 for the Ansible documentation fix!

**Comment by Andersson007** [comment]
@samccan thank you for reviewing and merging!

**Pull request merged**
