### PR TITLE
blockinfile: add --diff support in check mode

### LINKED ISSUE #23198: blockinfile should show diff
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It's very easy to accidentally overwrite changes in content managed via blockinfile because `--diff --check` does not show a diff of the update atm.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  tasks:
  - name: original block
    blockinfile:
      dest: test.txt
      create: yes
      block: |
        foo bar
  - name: updated block
    blockinfile:
      dest: test.txt
      create: yes
      block: |
        foo bar baz
```
`ansible-playbook --diff test.yml`

##### EXPECTED RESULTS
Should show the diff between `foo bar` and `foo bar baz`

##### ACTUAL RESULTS
With `-vvvv` it still only shows the new block content.

### PR DESCRIPTION
**Pull request by giovannisciortino**
##### SUMMARY
With this change, the module blockinfile supports --diff in check mode.

Fixes: #23198

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/g/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/g/PycharmProjects/ansible/build/lib/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### ADDITIONAL INFORMATION
The added code has a very similar layout/structure of the diff check mode implemented in [lineinfile](https://github.com/ansible/ansible/blob/3164e8b561931b413ee91f537e2ea3273b0a1775/lib/ansible/modules/files/lineinfile.py) module

Examples: 
1) Run blockinfile with --check --diff on a new file
```
$ ./build/scripts-2.7/ansible localhost -m blockinfile -a 'dest=/tmp/newFile state=present create=yes block="foo"' --check --diff
--- before: /tmp/newFile (content)
+++ after: /tmp/newFile (content)
@@ -0,0 +1,3 @@
+# BEGIN ANSIBLE MANAGED BLOCK
+foo
+# END ANSIBLE MANAGED BLOCK

localhost | SUCCESS => {
    "changed": true, 
    "failed": false, 
    "msg": "File created"
}
``` 
2) Run blockinfile with --check --diff on a empty file changing file permission 

``` 
$ ./build/scripts-2.7/ansible localhost -m blockinfile -a 'dest=/tmp/existingEmptyFile state=present mode=666 block="foo"' --check --diff
--- before: /tmp/existingEmptyFile (content)
+++ after: /tmp/existingEmptyFile (content)
@@ -0,0 +1,3 @@
+# BEGIN ANSIBLE MANAGED BLOCK
+foo
+# END ANSIBLE MANAGED BLOCK
\ No newline at end of file

--- before: /tmp/existingEmptyFile (file attributes)
+++ after: /tmp/existingEmptyFile (file attributes)
@@ -1,3 +1,3 @@
 {
-    "mode": "0664"
+    "mode": "0666"
 }

localhost | SUCCESS => {
    "changed": true, 
    "failed": false, 
    "msg": "Block inserted and ownership, perms or SE linux context changed"
}
```

### CODE REVIEW

**Comment by resmo** [comment]
Thanks!

**Comment by samdoran** [comment]
@resmo  Wasn't quite ready to merge this yet. This improperly outputs the `diff` in check mode, even when the `diff` parameter isn't set. I should have commented earlier. My bad.

I'll submit a PR with the minor correction.

**Comment by resmo** [comment]
@samdoran oh, my bad, I only tested the diff in check mode :(

**Comment by samdoran** [comment]
No worries. It's the most common combination of settings and how most people use them. But technically they should be able to be invoke separately.

**Pull request merged**
