### PR TITLE
ovirt_host_network: Add save parameter to example

### PR DESCRIPTION
**Pull request by dominikholler**
The parameter 'save' is added to an example and the default
behavior is mentioned in the description of the other
examples.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ovirt_host_network

### CODE REVIEW

**Review by samccann — CHANGES_REQUESTED** [review]
Thanks for helping with Ansible documentation!

Please change each occurrence of 'temporary' to 'temporarily'.

**Comment by dominikholler** [comment]
Done.

> samccann requested changes on this pull request.
> 
> Thanks for helping with Ansible documentation!
> 
> Please change each occurrence of 'temporary' to 'temporarily'.
> 
> 
> 
>

**Comment by machacekondra** [comment]
shipit

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @dominikholler for helping to improve Ansible documentation!

**Pull request merged**
