### PR TITLE
added module git_commit to execute git commit related commands

### PR DESCRIPTION
**Pull request by toshywoshy**
Added a git commit module, the original git module only allows git-clone and git-checkout, my module allows commit related functions such as git-push, git-stash, git-add and git-commit

### CODE REVIEW

**Comment by mpdehaan** [comment]
I'm not sure I understand the usage of ansible to automatically git commit things here.  Can you explain what you are using this for?

Should we decide to not include this in core, this may be something we end up listing in the contrib section.

**Comment by mpdehaan** [comment]
pretty sure this isn't a fit for core, but still interested in explanation

let me know, thanks!

**Comment by toshywoshy** [comment]
- My first use case is that developers forget to checkout their code before we destroy the VM's they are working on, this allows us to commit their code before we destroy the VM
- Another use case is that we use git for keeping our config, if a test or multiple tests runs successfully we want changes to be committed.
- Currently still in testing is adding public keys of new VM machines/users to gitolite so they have permission to read/write to specific repos

**Comment by srgvg** [comment]
@toshywoshy if you'd like, I can pull this in https://github.com/ansible-contrib/ansible-plugins

**Pull request closed without merging**
