### PR TITLE
Test module improvements

### PR DESCRIPTION
**Pull request by hayeah**
Allows the module test runner to:
1. dump the generated module file
2. take json string as complex args to module

### CODE REVIEW

**Comment by mpdehaan** [comment]
The output flag is confusing because it doesn't run the module anymore, I would suggest modifying the help string to "save the module, but do not execute it" ?  Can you update this?

Passing complex args is nice, thanks!

**Comment by hayeah** [comment]
@mpdehaan done

**Comment by hayeah** [comment]
@mpdehaan just following up to see if we can get this merged

**Comment by willthames** [comment]
Oops, reimplemented this last night as #8935.

Mine doesn't have the complex_args feature though.

**Comment by amenonsen** [comment]
Does hacking/test-module actually work any more? I rebased this patch (and #8935) to apply to devel, but I can't get the program to do anything useful (e.g. following the examples in the file results in bad/no output) with or without the patch applied.

**Comment by amenonsen** [comment]
Note that the -j option is no longer needed, which means that #8935 (which has no merge conflicts) should be merged and this PR should be closed.

**Comment by bcoca** [comment]
closed via merging of #11688

**Pull request closed without merging**
