### PR TITLE
Avoid breaking on unicode input when logging to syslog in modules

### PR DESCRIPTION
**Pull request by mtr**
After commit 254f87e, non-ascii input broke logging to syslog.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this.

Out of curiosity can you translate the playbook for those of us whom Google Translate does not work so well?  :)

**Comment by mpdehaan** [comment]
cc @jimi-c can you take a look at this?

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by mpdehaan** [comment]
Forgive me for not inputing the right source language!  :)

**Comment by mtr** [comment]
Thanks for accepting the pull request.  

I didn't put much effort into coming up with meaningful test strings; just ensured that the strings included some non-ASCII characters. I'll translate the different strings here:

## Norwegian

"Loggføring fungerer" = "Logging works"
"Feilsøking" = "Debugging"

## German

"Die Süßigkeit" = "the candy/sweet"

If you want me to, I can of course create a pull request with similar comments in the playbook.

**Comment by jimi-c** [comment]
Nope, that won't be necessary. Thanks again!

**Pull request merged**
