### PR TITLE
added vagrant module with cleanup

### PR DESCRIPTION
**Pull request by robparrott**
Hopefully this should be a cleaner merge.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks! you may want to post to the mailing list to see if some folks using vagrant would like to help test.

**Comment by jcftang** [comment]
I use vagrant quite a bit for testing and development in work. +1 on this, I just gave it a spin with vagrant 1.0.7 and it brought up a VM, this new vagrant module worked fine for me.

I see there is a memory option, I'd love to be able to specify the number of cpu's via this vagrant module and maybe multiple network interfaces as I found recently when testing/developing playbooks for openstack.

**Comment by robparrott** [comment]
The CPU options should be very straightforward ... essentially by matching
the RAM options.

I'm actually using this for OPenStack/CloudStack etc. testing myself, so
the interfaces part is relevant. Note that when the instance starts up, you
actually have two if's: the first is to the host via NAT (10.x), the second
is completely internal (192.168.x.y). This was based on the Lorin's
openstack ansible playbooks.

Rob

**Comment by mpdehaan** [comment]
merged, thank you!

**Pull request merged**
